### ISSUE TITLE
Expando: putIfAbsent

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#10209]
Love it in Map. Would be great in Expando

**Comment by trinarytree** [comment]
it's been 4 years.  any progress?  we've added expandoPutIfAbsent to some util library that benefits only us... and with the inconvenience of extra boilerplatey words and an extra import and build dependency.  it sure would make more sense for it to be part of Expando.

**Comment by lrhn** [comment]
I would recommend just considering `null` to mean absent, and then use:
```dart
expando[object] ??= 42;
```
instead of 
```dart
expando.putIfAbsent(object, () => 42);
```

An `Expando` is deliberately simple. It acts as a field that exists on all objects, and that field has a default value of `null`. Some implementations actually store the value on the object (e.g., in JavaScript).
If you look at the API, there is no way to *remove* an entry, all you can do is setting it to `null`, so the `containsKey` and `putIfAbsent` methods of `Map` doesn't really apply - it is not a map, and the objects are not "keys" as such.

**Comment by trinarytree** [comment]
thanks for the idea - i'll try it out.  i guess i (and kevmoo) were originally thinking of `Expando` more as an analog to `Map`, especially because of the syntax, with the essential difference being weak vs strong reference; but you are making it sound like the intention was to be more like a secret field, and fields don't distinguish between null and absent.  i guess that's a defensible position.

**Comment by lrhn** [comment]
That's our story, and we're sticking to it :)
There is no current plan to change `Expando` to be more `Map`-like.
