### ISSUE TITLE
Int64 and Uint64 methods and types are not supported in Dart2JS's typeddata

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#10275]
ByteData.[getInt64/setInt64/getUint64/setUint64] all throw unsupported exceptions in Dart2JS (they work in the VM).

Similarly, Int64List and Uint64List fail on construction.

It's not clear how to expose this in a way that works on Dart2JS.  The only 64-bit int type we have is fixnum:int64, but that does not subtype num or int.  We have no unsigned 64-bit int type for dart2js.

E.g., here's a signature:

abstract int getUint64(int byteOffset, [Endianness endian = Endianness.BIG_ENDIAN])

If we implement this in Dart2JS, what should the return type be?

**Comment by Bluenuance** [comment]
what is the state of the issue
it says it is blocked because of #1533 but this issue is closed

**Comment by sigmundch** [comment]
Thanks for following up @Bluenuance!

For the same reason we closed #1533, we won't be able to provide the 64-bit variants in typeddata from dart2js.

I'll shortly close this issue as well, since we currently have no plans to change the current behavior.

**Comment by fawdlstty** [comment]
Hello everyone. Is there a new plan for this issue? This problem continues to affect developers.

**Comment by lrhn** [comment]
There is no known plan for allowing `Uint64List`/`Int64List` on the web, because there is no 64-bit integer values, so `int operator[](int index)` would not be able to return the values of a 64-bit integer list.

If the web version of `Uint64List` could return a `BigInt`, then it would be useful, but it wouldn't match the `Dart` type system since a JavaScript `BigInt` is not compatible with an `int` represented as a JavaScript `Number`.
