### ISSUE TITLE
Invalid language tests - reference name "v" in "v" variable initializer

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#10683]
language/block_scope_test
language/lazy_static3_test

It is a compile-time error if e refers to the name v or the name v=.

**Comment by kmillikin** [comment]
The spec has changed so that local variables are in scope for the entire block that they are declared in, and so that a reference to a variable before the end of its initializer expression is a compile-time error.

The tests seem OK.  `language/block_scope_test` was either deleted or renamed.  The similarly-named `language/scope_variable_test` seems OK.
