### ISSUE TITLE
Spec allows function literals in initializer list

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#11509]
Example code:

class C {
&nbsp;final int x;
&nbsp;C() : x = (){ return 42; }();
}

main() {
&nbsp;&nbsp;print(new C().x);
}

This errs with the message:
'file:..../initcall.dart': Error: line 3 pos 13: unexpected token ')'
&nbsp;C() : x = (){ return 42; }();

The grammar allows the syntax.

**Comment by eernstg** [comment]
No milestone now: This correction will be considered as part of a larger update of grammar related parts of the specification, based on [Dart.g](https://github.com/dart-lang/sdk/blob/master/docs/language/Dart.g).

**Comment by eernstg** [comment]
Note comments on #35674, which has just been closed as a duplicate of this one.

**Comment by modulovalue** [comment]
Note: once this is resolved, it would probably make sense to also update the switch expression grammar since there's a similar ambiguity there, too. See: https://github.com/dart-lang/language/blob/main/accepted/3.0/patterns/feature-specification.md#function-expression-in-guard-ambiguity

**Comment by eernstg** [comment]
Thanks for the heads-up!

The error which is reported for the original example today (DartPad, master) is a type error:

```
The initializer type '()' can't be assigned to the field type 'int'.
```

This implies that the text `() { return 42; }` is being parsed as an expression `()` (the empty record) followed by a constructor body, and the `();` that follows is then parsed as the next class member declaration (that has its own syntax errors).

This is all in line with the expected behavior today. There is a rule that prevents function literals from being present in initializer elements. It has never been specified precisely, but that is being clarified now in https://github.com/dart-lang/sdk/issues/54284.

In any case, that rule was (or at least could have been) introduced _in response to this issue_. The initial message of this issue indicates that the grammar allowed this kind of construct, and it doesn't mention any special exceptions for initializer list elements. In other words, this issue was relevant for the language before that rule was introduced, which means Dart as of 2014 or so.

So we can close this one now, and rely on https://github.com/dart-lang/sdk/issues/54284 to clarify the rule that makes this issue obsolete.
