### ISSUE TITLE
VM --package-root parsing incorrectly handles ..

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#11877]
If you try to run &quot;dart --package-root=out/ReleaseIA32/dart-sdk//../packages/ test.dart&quot;, the VM will consider the package root to be &quot;out/ReleaseIA32/dart-sdk/packages&quot; rather than &quot;out/ReleaseIA32/packages&quot;. It seems to incorrectly consider the &quot;//&quot; to be a separate directory which should be moved up when using &quot;..&quot;.

**Comment by nex3** [comment]
This still reproduces.

**Comment by lrhn** [comment]
I'm not sure the behavior is technically incorrect.

The `--package-root` parameter accepts either a URI, a relative URI reference or a local file system path.

On Unix, its not possible to distinguish relative URI references and relative file system paths since both use slashes as separators.

If the provided example is interpreted as a URI reference and resolved against the URI of the entry point then the `//` *is* considered an empty path segment that the `..` backtracks into. That's required by the URI specification.

Still, if the argument can be either, maybe we should default to thinking it's a local path instead of a URI. It's likely to cause fewer surprises for users.

**Comment by nex3** [comment]
It's not good that the parameter is defined in an ambiguous way, but given that it is, we should definitely resolve the ambiguity in the most user-friendly manner possible.

**Comment by iposva-google** [comment]
As far as I am concerned the --package-root parameter is still supported for legacy reasons only. No further work on handling this parameter is planned. We can clarify the help message by saying it is handled as a URI.
