### ISSUE TITLE
Dartium error on startup: libudev.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cbracken** [dart-lang/sdk#12325]
On Ubuntu 13.04, Linux Mint 15, Dartium issues the following error on startup and terminates:

Dartium stdout: /home/user/Applications/dart/chromium/chrome: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

**Comment by daftspaniel** [comment]
To get this working on 32bit Ubuntu MATE
sudo ln -s /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0

**Comment by z3ntu** [comment]
BUMP!
Ubuntu 15.04 64-bit
Still same error! This issue is TWO years old and still not fixed...

**Comment by jessegood** [comment]
+1

**Comment by Ablu** [comment]
+1 on Fedora 22

**Comment by sanmadjack** [comment]
This issue is still occurring. It's been 2 years, why isn't this fixed?

**Comment by gwTumm** [comment]
+1 Please fix this

**Comment by albertog** [comment]
+1

**Comment by regenvanwalbeek** [comment]
+1 Still hitting this on Ubuntu 15.10 64-bit - The ```sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0``` workaround does the trick

**Comment by mulander** [comment]
Until this issue is solved by the upstream a somewhat cleaner solution is to use LD_PRELOAD instead of symlinking in your system which could lead to other apps loading an incorrect version of the library.

Steam ships it's own 32-bit and 64-bit libudev.so.0 here's an example of running dartium using that library preloaded:

`LD_PRELOAD=/home/mulander/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libudev.so.0 ./chrome`
