### ISSUE TITLE
Mixins shadow super methods

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#12456]
Given the following class hierarchy:
class Superclass {
&nbsp;&nbsp;void init() {
&nbsp;&nbsp;&nbsp;&nbsp;print('init super!');
&nbsp;&nbsp;}
}

class Subclass extends Superclass with Mixin {
&nbsp;&nbsp;void init() {
&nbsp;&nbsp;&nbsp;&nbsp;print('init sub!');
&nbsp;&nbsp;&nbsp;&nbsp;super.init();
&nbsp;&nbsp;}
}

class Mixin {
&nbsp;&nbsp;void init() {
&nbsp;&nbsp;&nbsp;&nbsp;print('init mixin!');
&nbsp;&nbsp;}
}

Is it possible to call Superclass.init() when Subclass.init() is invoked? The Mixin class is prevented from calling super.init().

**Comment by a14n** [comment]
The DEP to remove some of restrictions on mixins is available at https://github.com/gbracha/lessRestrictedMixins/blob/master/proposal.md

**Comment by Zectbumo** [comment]
No the answer is not as simple as allowing mixins to call super. There needs to be a way to access the individual super classes because you may not have access to edit those super classes to add a super call. One can't expect that ALL mixin methods in ALL libraries are going to have a super call. There most likely won't be one. There will be cases where you can't edit the mixin method and add your super call. Then what? Simply allowing super to be called is not a full solution.

**Comment by Zectbumo** [comment]
Hopefully you guys can come up with a better elegant syntax than me but I'll throw out an idea to get people thinking.
If you want the output to be:
````
init sub!
init mixin!
init super!
```

then my made up example syntax could be:
```
class Subclass extends Superclass with Mixin {
  void init() {
    print('init sub!');
    (Mixin)super.init();
    (Superclass)super.init();
  }
}
```

This makes things simple. 1) You don't get caught up in unknown and unclear super call paths. 2) It gives you access to the required super classes you want. 3) Easy to read and understand what is going on. 4) And is always available to edit since you have access to edit your Subclass source code any way you wish. Think about it and get back to me please.

**Comment by Zectbumo** [comment]
I created #26194 to show more problems with super

**Comment by munificent** [comment]
While it's not *implemented* everywhere yet, the language now supports super calls in mixins.

**Comment by munificent** [comment]
Hmm, I guess it's still not done, so I'll consider this a duplicate of that main bug: #23770
