### ISSUE TITLE
Unhandled exceptions in isolates does not terminate the VM

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#12587]
The tests

&nbsp;&nbsp;isolate/isolate2_negative_test.dart
&nbsp;&nbsp;isolate/isolate3_negative_test.dart

expect the VM to terminate when there is an unhandled exception in an isolate.

Might be releatd to issue #3734.

**Comment by zanderso** [comment]
This looks stale. The tests named above don't appear to exist anymore.

**Comment by floitschG** [comment]
This is still an issue.
The problem is pretty much, that errors in other isolates are completely ignored.

See for example:
``` dart
import 'dart:isolate';
import 'dart:async';

foo(x) {
  print("throwing");
  throw "in other isolate";
}

main() {
  Isolate.spawn(foo, null);
  new Timer.periodic(const Duration(seconds: 1), (_) { print("tick"); });
}
```

Silently ignoring is the worst of all options. We should come up with a better way to deal with it.
@zanderso, @a-siva : I suggest working together with us (mostly with @lrhn and me, since we designed most of the isolate library), to improve the situation.

**Comment by zanderso** [comment]
@floitschG Could you give this issue a better title? As stated, I think the VM is working as intended. Thanks.

**Comment by floitschG** [comment]
Fair enough. I will close this one.
Let's meet for my example anyway (probably there is already a bug for that one too).
