### ISSUE TITLE
spawnUri load Dart files asynchronously

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#12617]
Right now, spawnUri blocks the entire process while loading the Dart files necessary to start the isolate. This is problematic not only because spawnUri is performing IO, which is otherwise always done asynchronously in Dart, but because it means that neither the library passed to spawnUri nor any of its transitively imported libraries can be HTTP URLs pointed back at the spawning process.

**Comment by nex3** [comment]
This is still an issue.

**Comment by nex3** [comment]
It looks like this no longer reproduces, at least with Dart 1.21. I'm leaving it open for the time being since AFAIK it was fixed accidentally, so there probably still need to be regression tests written.

**Comment by zanderso** [comment]
@a-siva Did you fix this? I am going to close it with "Cannot reproduce". We have so many bugs, we probably shouldn't leave open things we can't reproduce. If it happens again, please file a new bug with updated information and repro steps.

**Comment by nex3** [comment]
@zanderso Can we get some tests for this if we're going to close it? It was a long-standing issue, and if it starts cropping up again code is likely to break.

**Comment by zanderso** [comment]
I'm just cleaning up the issue tracker. I assume that @a-siva has used good judgement as far as testing goes, and has added whatever tests are appropriate. If you find otherwise, then we should open a new issue.

**Comment by nex3** [comment]
@zanderso Added tests where? There are no SDK CLs that refer to this issue.

**Comment by zanderso** [comment]
@nex3 I don't think your request for information about tests is germane to this issue. You're probably going to have to schedule a meeting with someone to get your questions answered.

**Comment by nex3** [comment]
How is it not germane? This issue was tracking a serious bug. We shouldn't close this issue until the bug is thoroughly addressed. Addressing a bug requires not just fixing it, but adding regression tests to ensure it stays fixed.

**Comment by a-siva** [comment]
I did not fix this, I would have closed the bug if I fixed it. I believe this is a duplicate of the first part of  https://github.com/dart-lang/sdk/issues/24849 which was fixed by @turnidge 

Regarding tests we have a number of isolate tests in the regression suite and writing a test to measure the time it takes to spawn an isolate is not the right test. For this case the right test would be the one described in one of the comments above "I was attempting to spawnUri() on a URI that's served by an HttpServer in the same VM, and it deadlocks". 

Let us leave this issue closed as a duplicate of 24849 and use that issue to track addition of a test.
