### ISSUE TITLE
dart2js and VM differ in error on assignment to a static const

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#13964]
const int XX =  ZZ + 42;

main() {
&nbsp;&nbsp;XX = 123;
}

On dart2js I get a NoSuchMethodError, the VM produces a &quot;not a valid compile-time constant&quot; compile error. I'm not sure what the correct thing would be, but in any case both should report the same error.

**Comment by lrhn** [comment]
Just to summarize: The only "problem" here is that the VM evaluates the RHS of the const declaration even if nobody is reading it. It is a compile-time error that the RHS isn't a valid compile-time constant, the only surprise is when (or that) it's reported.

The assignment should fail too, since a const declaration doesn't introduce a setter, and it does fail if the const declaration is valid.

**Comment by munificent** [comment]
We're not planning to clarify this in the language spec. Since the code already has a compile-time error, the runtime behavior is undefined.

**Comment by lrhn** [comment]
When the VM made compile-time errors catchable (instead of killing the isolate), there was a guide to when a compile-time error could reasonably be thrown. 

For const declarations with compile-time errors, the compile-time error should happen in the non-constant code that refers to the constant declaration. That is:
```dart
const x = arglebargle;  // Not valid constant!
foo() {
  return x + 2;
}
```
The compile time error for `x` should happen (at the latest) when you call `foo`.

I think it's slightly confusing that the VM throws a compilation error in this case because `main` doesn't refer to `XX`. It refers to `XX=`, which is not the const declaration.
If you had a program like:
```dart
const X = someError;
void set X(v) { print(v); }
main() {
  X = "Hello world!";
}
```
then (you are certifiable insane, but) the program should not touch the `X` constant.

(Currently it doesn't since implementations fail to allow setters next to constant declarations).
