### ISSUE TITLE
Unicode whitespace in Dart

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#14071]
Consider having the Dart language support all Unicode whitespace characters:

0020;SPACE;Zs;0;WS;;;;;N;;;;;
00A0;NO-BREAK SPACE;Zs;0;CS;&lt;noBreak&gt; 0020;;;;N;NON-BREAKING SPACE;;;;
1680;OGHAM SPACE MARK;Zs;0;WS;;;;;N;;;;;
2000;EN QUAD;Zs;0;WS;2002;;;;N;;;;;
2001;EM QUAD;Zs;0;WS;2003;;;;N;;;;;
2002;EN SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
2003;EM SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
2004;THREE-PER-EM SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
2005;FOUR-PER-EM SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
2006;SIX-PER-EM SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
2007;FIGURE SPACE;Zs;0;WS;&lt;noBreak&gt; 0020;;;;N;;;;;
2008;PUNCTUATION SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
2009;THIN SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
200A;HAIR SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
2028;LINE SEPARATOR;Zl;0;WS;;;;;N;;;;;
2029;PARAGRAPH SEPARATOR;Zp;0;B;;;;;N;;;;;
202F;NARROW NO-BREAK SPACE;Zs;0;CS;&lt;noBreak&gt; 0020;;;;N;;;;;
205F;MEDIUM MATHEMATICAL SPACE;Zs;0;WS;&lt;compat&gt; 0020;;;;N;;;;;
3000;IDEOGRAPHIC SPACE;Zs;0;WS;&lt;wide&gt; 0020;;;;N;;;;;

Of those, two also terminate lines which means they should be included in the NEWLINE grammar rule:

2028;LINE SEPARATOR;Zl;0;WS;;;;;N;;;;;
2029;PARAGRAPH SEPARATOR;Zp;0;B;;;;;N;;;;;

**Comment by munificent** [comment]
Talked about this with the language team. The idea definitely has merit but @lrhn notes that it's really handy that scanners can treat Dart as byte-based (outside of comments and strings) and don't have to do UTF-8 decoding.

Given that, we don't plan to add support for this, at least not at this time. (Closing a bug doesn't mean ruling out the idea forever, just that we don't have any intent to do it within any known timeframe.)

**Comment by peter-ahe-google** [comment]
It's not a problem to fall-back to Unicode processing when scanning source code.

**Comment by munificent** [comment]
Sorry, reclosing. Unless Florian comes back from vacation and re-opens this, the language team has decided we aren't going to pursue it.

**Comment by peter-ahe-google** [comment]
Could you explain why you decided to not pursue it?

**Comment by munificent** [comment]
Sure. We (the language team) only discussed very briefly discussed it. I suggested closing it because it's been open for three years with zero activity, which is a good sign it's not a priority.

Lasse mentioned that not having to worry about non-ASCII characters (outside of comments and strings, where you don't need to UTF-8 decode) makes it a little easier to write scanners.

No one on the language team had any interest in pursuing it. Given that, it's a good candidate for closing. It doesn't mean we're definitely never going to do it, but we don't have any plans to any time soon, and the chances of this being a priority are slim.

The area-language bugs have been pretty unmaintained for quite a while (I've found dozens of duplicates, already-fixed issues, etc.), so I'm trying to get them into a state where they are useful both for the language team, and for the people who want to know what the language team is doing.

I think it's cleaner to close bugs that aren't planned than to leave them around indefinitely on the off chance that we change out minds at some point in the future. We can always re-open or open a new bug then if we do. Until then, the bug is just noise, or may actively confuse a reader who presumes the bug is open because it's something we intend to do.

For this particular bug, I have never heard a single user mention it. It has never once come up in several years of being on the language team. That was enough for me to ask the rest of the team if we could close it as not planned. Florian is on vacation right now, but the others all concurred.

**Comment by peter-ahe-google** [comment]
Why is it relevant how many users you've heard mention this? Are you in some special position where you have a closer connection to users than I have?

The reason for not hearing users complain about it is probably because dart2js is violating the specification and accepting NBSP as white space, see: https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/scanner/scanner.dart#L411

There you can also see how easy it is to deal with characters outside the ASCII, so you don't need to keep repeating that Lasse has misunderstood how non-ASCII characters are handled.

So could you please reconsider this issue, knowing that you either have to introduce a breaking change to dart2js or update the specification?

**Comment by munificent** [comment]
> Why is it relevant how many users you've heard mention this?

Priority is based (in part) on user need. If a lot of users are clamoring for something, that's a good sign that we should do it. Conversely, if no one is complaining, it's probably not worth putting our attention on it right now. We have vastly more important things to do.

> There you can also see how easy it is to deal with characters outside the ASCII, so you don't need to keep repeating that Lasse has misunderstood how non-ASCII characters are handled.

I don't think Lasse misunderstood anything. He said:

> It means that you can make a byte based scanner without having to worry about UTF-8.

This is true. It is apparently the case that dart2js *does* worry about UTF-8 and it's not that hard for dart2js, but that doesn't mean Lasse was misunderstood. He made no claims about how *hard* it is for scanners to do UTF-8 decoding.

> So could you please reconsider this issue, knowing that you either have to introduce a breaking change to dart2js or update the specification?

Sure, thanks for asking nicely. I'd be surprised if this becomes a priority any time soon, but I'll leave the issue open.

**Comment by lrhn** [comment]
Nothing prevents dart2js from having a mode where it accepts more whitespace. That's basically just equivalent to a pre-processing step that converts non-ASCII white-space characters to spaces, and providing it is just a service to some users of the dart2js API. That doesn't mean that we should accept non-ASCII whitespace everywhere or as part of the language. The VM doesn't accept it, nor does the analyzer.

**Comment by peter-ahe-google** [comment]
I'd argue that the specification prevents dart2js from doing so. If the specification doesn't allow something, a valid implementation can't do it. The purpose of the specification is to ensure that our tools behave the same and in a predictable manner.

**Comment by lrhn** [comment]
That is true, and when run in its default setting, I would prefer if dart2js doesn't accept non-ASCII whitespace. 

You mentioned that the problem comes from web-based editors that might insert nbsp. Of course they shouldn't, unless they want to confuse users and tools by intermixing the visible identical space and nbsp, but web tools being what they are, I guess it's not always avoidable.

I don't know exactly which web based editors we are talking about, or where they are used, but if it's something like dartpad which uses dart2js, I wouldn't mind having an option that it can use to (effectively) preprocess the input files.
Still, since the analyzer doesn't accept nbsp, it is probably not dartpad.

**Comment by peter-ahe-google** [comment]
> That is true, and when run in its default setting, I would prefer if dart2js doesn't accept non-ASCII whitespace.

Why? What changed your mind?

**Comment by lrhn** [comment]
I didn't actually change my mind *recently* - as you say, the tools should behave the same and predictably.

I don't mind dart2js exposing functionality that allows users to accept more (implicitly rewriting the incorrect program to a correct one in a well-defined way), which is what I meant by "Nothing prevents dart2js from having a mode where it accepts more whitespace", but for predictability, it should be an opt-in mode.

I originally suggested adding more whitespace, but I haven't actually needed it, and I haven't seen anybody else need it either, so I think it was a red herring. If you have a vertical tab in your code, it's more likely that your file is corrupted than it is that you intended it.

**Comment by lrhn** [comment]
There is still no plan to change the specification on this point.

**Comment by AlraziBashir** [comment]
@lrhn @munificent  what would cause this error:
![Screen Shot 2020-04-10 at 1 11 07 AM](https://user-images.githubusercontent.com/53784936/78966009-b4980480-7acc-11ea-85bb-38c2b2ab8f35.png)
 Flutter Project Failed To Compile With  Compiler message: Error: The non-ASCII space character U+00A0 can only be used in strings and comments.

**Comment by munificent** [comment]
You have a non-breaking space in your code, which is not valid Dart syntax. (This happens sometimes if you copy/paste code from web pages.) You just need to remove that invalid character from before `data` and replace it with a normal space.
