### ISSUE TITLE
improve error message "type 'A' is not a subtype of type 'A'"

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#14353]
This should be a simple fix, but it would really help users diagnose and fix errors.

I've hit this error many times where both types are named exactly the same. The most common scenario when this happens is a canonicalization bug: I have 2 imports to the same library, but one uses &quot;package:&quot; and the other uses a file:// URL, and because of that they are resolved as separate libraries.

Maybe we could change the message so that when both types have the same name, we can also include some extra information about it. For example, instead of:
&nbsp;&nbsp;&nbsp;type 'A' is not a subtype of type 'A'

we could say:
&nbsp;&nbsp;&nbsp;type 'A' is not a subtype of type 'A'
&nbsp;&nbsp;&nbsp;\- the first definition is from 'package:foo/bar.dart'
&nbsp;&nbsp;&nbsp;\- the second definition is from 'file:///a/b/c/packages/foo/bar.dart'

**Comment by filiph** [comment]
I just hit this issue (the original one that fails on importing the same fila via different schemes as one source). 

I'm on Dart 1.21.0. It only happens in checked mode (which is what IntelliJ WebStorm uses when you run a file).

I [made a StackOverflow question](http://stackoverflow.com/questions/41106064/unhandled-exception-type-a-is-not-a-subtype-of-type-a-of-x-where-a-is-fro/) out of it so that people at least get some information how to fix on their end.

But we really should fix it. In case you need a test case, I'll provide it.

**Comment by filiph** [comment]
_Assigning to you, @kevmoo, because you were the last person acting on this bug._

**Comment by kevmoo** [comment]
@filiph It's on the VM's hopper – and I'm not going to be able to fix it. 😬

**Comment by rmacnak-google** [comment]
I believe @crelier fixed this at some point.
