### ISSUE TITLE
dart2js and spec disagree about numerics

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#1533]
The following Dart code:

var x = 123;
print(x is! double);

will print TRUE in Dart VM and FALSE in JavaScript compiled from Frog.

The generated JavaScript code in question:

print((typeof(x) != 'number'));

doesn't match the intention of the original Dart code.

**Comment by sigmundch** [comment]
I don't believe this is something we will change in dart2js. We need to map both int/double to Number to be able to generate code that performs well in JS engines.

We might want to be more explicit/upfront about these exceptions though. Either by making mention of them in the spec or in our documentation. Thoughts?

/cc @floitschG @kwalrath @gbracha

**Comment by icosferu** [comment]
.

**Comment by homer-jay** [comment]
I'm new to Dart and I find the documentation extremely confusing. On the one hand it claims Dart has built in arbitrary precission integers, and this would actually be a plus for developers coming from other languages, something that might motivate them to learn Dart. On the other hand, [this pad](https://dartpad.dartlang.org/7b84a01acb9f3eae8f19ec6c54734a61) proves otherwise. In the end this pad shows a problem with numbers greater than JavaScript's [MAX_SAFE_INTEGER](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

Why is this discrepancy between "VM Dart" and "JS Dart" allowed to exist nowadays? Dart is Dart and it should behave the same in all platforms. Either remove big int support from the VM or add it to dart2js for the sake of sanity. It is not difficult to implement this in dart2js, just use JavaScript's Number type for safe integers and switch to a JS based big int implementation outside of that range. That way you could keep the current performance for safe integers.

**Comment by peter-ahe-google** [comment]
@homer-jay try reaching out in one of these place: https://www.dartlang.org/community
In particular, I think this mailing list is a great place to ask questions like this: https://groups.google.com/a/dartlang.org/forum/#!forum/misc

**Comment by ds84182** [comment]
For anyone else who runs into issues with shifts with Dart2JS and DDC, there's a simple solution.

After doing any bitwise operation on a negative number the resulting number is an unsigned 32-bit integer. You can turn it into a signed 32-bit integer with `.toSigned(32)`. Right shifts properly move the sign bit, but the sign in the JavaScript number gets discarded by Dart2JS and DDC. `print(((-1 >> 1).toSigned(32) >> 1).toSigned(32))` yields `-1` in both the VM (with and without big ints) and the web.

However, I do feel that this should be fixed. Since the VM is now moving to signed 64-bit integers, it would make sense to use at least signed 32-bit integers for bit operations on the web.

With some tests on Chrome and Edge, the result of `((-1) >> 1) << 0` (in JavaScript) preserves the sign bit, while `((-1) >> 1) >>> 0` (in JavaScript) (which is what Dart2JS and DDC emit) does not preserve the sign bit. Changing the latter to the former would give the web the same results that the VM would yield (at least when bit width isn't taken into account), and the web would be consistent with the behaviors JavaScript developers expect (`-1 >> 1` yields `-1` in JavaScript and `4294967295` in Dart compiled JavaScript).

This may become more of an issue in the future, so it would be great to know how much code depends on this weird behavior.

But anyways, I thought of some pros and cons.

Pros:

- Unknown! I'd love to hear from someone who works on Dart2JS or DDC on why we have these differences!

Cons:

- From a glance at code available on GitHub, most libraries use workarounds to get consistent behavior with bitwise operations on both the VM and web.
- This problem has affected developers for years. (This is issue number 1533 out of 31972)
- This problem has been one of the pain points from testing on Dartium and deploying to normal browsers. (Not as much as today thanks to DDC!)
- Sharing code between the VM and the web is tricky. Since developers have Flutter, they'll notice these differences when they try to share logic between the two. A developer might run tests solely on the Dart VM for their common library because it's quicker than running tests in the browser, but they won't hit these weird bits until they use the library on the web.
- Result differs from JavaScript, C, C++, Rust, Go, etc.

**Comment by levifeldman** [comment]
Yea, HELLLOOOO people what the hell is going on, ive been testing dart code for a while to use in my flutter app and now when i try to run it on the web im getting all these errors bout _BigIntImpl,  turing complete code is turing complete code why is there such a probelm? I know, javascript really fucked things up with code on the web big time but wait,  I have a Solution. The Solution is ...... WEBASSEMBLY!!! get dart to compile to wasm and we are golden!! in the fact, this is why wasm was created in the first place, to fix the retartedness that was, that the web only supported javascript with all its fucked up integer lengths and other bs quirks. In the fact, I am sure it will be way simpler to target one compile-target which can be run anywhere(wasm), for the dart than have a dartvm and a dart2js and whatever.

**Comment by sigmundch** [comment]
@levifeldman we appreciate that you later edited and removed your earlier comment. In the future, please take a moment before posting comments to make sure the content has a respectful and constructive tone. It is really important for both developers and the community here.

Regarding bigint - please file a new issue if you have an example we can take a look and test. A code sample that can run in isolation outside the context of flutter is even better, as it will help the team get to the root cause of the issue faster.

Unrelated - I also wanted to take a moment to share an article that was recently added, which explains in more detail the difference in number semantics: https://dart.dev/guides/language/numbers.
