### ISSUE TITLE
can't refer to constructor parameters passed using this.x syntax.

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#15346]
to reproduce:
1  class A {
2    A(x) {}
3  }
4  class B extends A {
5    var _x;
6    B(this._x) : super(_x);
7  }
8  main() {
9    new B(1);
10 }

this yields
'error: line 6 pos 22: illegal implicit access to receiver 'this'
&nbsp;&nbsp;B(this._x) : super(_x);

on line 6, apparently _x refers to the instance variable, instead of to the constructor parameter.
maybe it would make more sense for _x used as an r-value inside a constructor initializer to refer to the
constructor parameter and _x used as an l-value to refer to the instance variable.  e.g.
B(x) : x = 1;  // assign 1 to the instance var x
B(x) : y = x;  // assign the passed in x to the instance var y

Dart VM version: 1.0.1.1_r30601 (Fri Nov 22 17:38:17 2013) on &quot;linux_x64&quot;

**Comment by BlackHC** [comment]
Any plans to fix this? It's been two years already...

**Comment by floitschG** [comment]
It's on our list of things to look at.

**Comment by munificent** [comment]
It's done: #26655

**Comment by BlackHC** [comment]
Woohoo! Thanks! Happy to see this in!

**Comment by munificent** [comment]
Me too!

**Comment by amitoodles94** [comment]
"Mp3Files": "BAKARA01.mp3,BAKARA02.mp3,BAKARA03.mp3,BAKARA04.mp3,BAKARA05.mp3,BAKARA06.mp3,BAKARA07.mp3,BAKARA08.mp3,BAKARA09.mp3,BAKARA10.mp3",

how to store in a list when , come

**Comment by atta1234** [comment]
> It's on our list of things to look at.

it's still exist man in 2020,

**Comment by eernstg** [comment]
I don't see anything for this issue that is not working (and it has been working for years):

```dart
class A {
  A(x) {}
}

class B extends A {
  var _x;
  B(this._x) : super(_x);
}

main() {
  new B(1);
}
```

It is a very special mechanism, because the `_x` which is a formal parameter is only accessible in the initializer list of the constructor (not even the constructor body), but as long as you don't capture it in a function literal (where you would be able to see that the formal parameter keeps the same value even when the field is updated), you shouldn't need to think about it.
