### ISSUE TITLE
Analyzer too aggressive with dead code

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#17730]
I have some code that looks like this:

&nbsp;&nbsp;if (false) {
&nbsp;&nbsp;&nbsp;&nbsp;cacheCompiler.compilerFor(null);
&nbsp;&nbsp;}

The analyzer reports this as dead code.

**Comment by srawlins** [comment]
2 year mark since the last comment.

Where do we want to land on this one? Complain about `if (false)` or not?

Personally, I think its fine if your IDE notifies you about `if (false)` being DEAD, whether you meant it as an intentional "commenting out" or not. It's still something you don't super duper want to check in, and your IDE can remind you of that.

You can also just use `if (1 == 0)` in Dart to avoid the warning.

**Comment by bwilkerson** [comment]
> You can also just use `if (1 == 0)` in Dart to avoid the warning.

Until we get smarter and start recognizing and evaluating constant expressions. :-)

Something else to note is that when this issue was opened we didn't have a way to disable hints, which we now have. It might be fine to produce hints like this when users can explicitly opt out.

Given the limited number of people complaining about this feature, I'm going to close this issue. Someone can re-open it if there's a reason to keep it open.
