### ISSUE TITLE
Exposing a Dart function to JS behaves differently in compiled vs non-compiled mode

### ISSUE THREAD

**Issue by tfortes** [dart-lang/sdk#17752]
**What steps will reproduce the problem?**
1. context['foo'] = myDartFn;
2. context['foo'] is JsFunction;

**What is the expected output? What do you see instead?**
In non-compiled mode this returns true.
In compiled mode (to js) this returns false.

I'd expect it to behave the same way regardless.

**What version of the product are you using? On what operating system?**
1_3_0_dev_6_0

**Comment by ahirschberg** [comment]
I'm getting a similar issue, but I don't think any of the solutions posted here will fix it. I'm using a javascript library with my dart code, and in dartium the interop works fine. When I use the debugger, I can see that my JSObject is set correctly: 
<img src="https://cloud.githubusercontent.com/assets/5578698/18227460/08f65e14-71f3-11e6-9a18-a3b8d80e1250.png" width="400px" />. 

However after compiling via **dart2js**, the exact same code fails because of additional wrapping of the JSObject:
<img src="https://cloud.githubusercontent.com/assets/5578698/18227471/72e424a0-71f3-11e6-96b1-cd23d87791c5.png" width="500px" />. 

Is there a workaround for this?

**Comment by jkriesel** [comment]
I run into the exact same issue when trying to interface with ag_grid.  Is there a solution?   If you have control of the resulting javascript I've found that ._jsObject DOES behave the way you'd like.  In my case I don't really want to modify the core library to make it work with dart, but I might be forced to do so.

**Comment by jkriesel** [comment]
I run into the exact same issue when trying to interface with ag_grid.  Is there a solution?   If you have control of the resulting javascript I've found that ._jsObject DOES behave the way you'd like.  In my case I don't really want to modify the core library to make it work with dart, but I might be forced to do so.

**Comment by jkriesel** [comment]
I run into the exact same issue when trying to interface with ag_grid.  Is there a solution?   If you have control of the resulting javascript I've found that ._jsObject DOES behave the way you'd like.  In my case I don't really want to modify the core library to make it work with dart, but I might be forced to do so.

**Comment by jkriesel** [comment]
I run into the exact same issue when trying to interface with ag_grid.  Is there a solution?   If you have control of the resulting javascript I've found that ._jsObject DOES behave the way you'd like.  In my case I don't really want to modify the core library to make it work with dart, but I might be forced to do so.

**Comment by jkriesel** [comment]
I run into the exact same issue when trying to interface with ag_grid.  Is there a solution?   If you have control of the resulting javascript I've found that ._jsObject DOES behave the way you'd like.  In my case I don't really want to modify the core library to make it work with dart, but I might be forced to do so.

**Comment by ahirschberg** [comment]
I ended up writing a quick and dirty JS wrapper  that intercepts the objects before they reach the javascript library and de-dartifying the object. That's pretty ugly though, it would be nice to see a proper fix for this.
