### ISSUE TITLE
Provide hint when case clause can be simplified

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#18470]
Given code of the form:

&nbsp;&nbsp;&nbsp;&nbsp;switch (event) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case Button.OK:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (likeThisEvent(event)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return true;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return somethingElse(event);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case Button.UP:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...

Analyzer should provide a hint to re-write the code to be simplified to

&nbsp;&nbsp;&nbsp;&nbsp;switch (event) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case Button.OK:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (likeThisEvent(event)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return true;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return somethingElse(event);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case Button.UP:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...

**Comment by srawlins** [comment]
We do currently get a warning. The following code:

```dart
int main() {
  int x;
  switch (x) {
    case 0:
      if (1==2) {
        return 7;
      } else {
        return 9;
      }
    case 1:
      return 1;
  }
  return 0;
}
```

yields the following analyzer warning:

> The last statement of the 'case' should be 'break', 'continue', 'rethrow', 'return' or 'throw'.

**Comment by lrhn** [comment]
I hope the expression-termination work done for NNBD can also allow us to improve behavior for this case, so it recognizes that the case will never "fall through" (reach the end) because there is no control flow that can get there. 
The current specification does not attempt any such thing, it just says that the last statement of the case block must be a control-flow transfer statement, and an `if` statement is not on. It never looks at the branches of that `if` statement.

(We do that termination-detection work to improve promotion for cases where we can see that a non-promoted branch never reaches the following code because it throws/returns, say
```dart
if (x is! Foo) {
  print("Whoops, not Foo!");
  return null;
}
/// x is Foo here.
```
which only works if we can see that the following code is not reachable through the test branch).

**Comment by asashour** [comment]
I guess this should be closed, the case in https://github.com/dart-lang/sdk/issues/18470#issuecomment-540927326 doesn't trigger a warning, because the `if` branches are checked.

**Comment by lrhn** [comment]
Yes, thanks for noticing. The null safety (nee NNBD) feature did improve type promotion and flow analysis to the point where this now works.
