### ISSUE TITLE
Constructors of native classes are not included in mirrors.

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#18541]
The following code:

&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:html';
&nbsp;&nbsp;&nbsp;&nbsp;import 'dart:mirrors';

&nbsp;&nbsp;&nbsp;&nbsp;void main() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var lib = currentMirrorSystem().findLibrary(const Symbol('dart.dom.html'));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var fooClass = lib.declarations[const Symbol('HttpRequest')] as ClassMirror;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var fooInstance = fooClass.newInstance(const Symbol(''), []);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(fooInstance.reflectee);
&nbsp;&nbsp;&nbsp;&nbsp;}

throws:

&nbsp;&nbsp;&nbsp;&nbsp;Uncaught NoSuchMethodError : method not found: 'Symbol(&quot;&quot;)'
&nbsp;&nbsp;&nbsp;&nbsp;Receiver: Instance of 'JsClassMirror'
&nbsp;&nbsp;&nbsp;&nbsp;Arguments: []

It works fine on Dartium. Constructing other classes works as well.

**Comment by stevenroose** [comment]
@floitschG Progress on this?

**Comment by stevenroose** [comment]
@nex3 @floitschG bump..

**Comment by floitschG** [comment]
@sigmundch: I don't have the time to work on this right now, so I removed myself as assignee.

**Comment by stevenroose** [comment]
It is weird that this is so hard to fix. This particular bug seems like a simple mistake that can be fixed quite straightforwardly by the person that designed the mirror system for dart2js..

**Comment by eernstg** [comment]
If nothing else prevents this, you might want to consider using the package reflectable rather than 'dart:mirrors'.

I just created CL https://codereview.chromium.org/1573103003/ which contains checks to verify that the situation described here works with reflectable-transformed code. It also introduces special casing for `List` (whose nameless constructor has non-standard semantics), and fixes a bug which prevented the reflective invocation of factory constructors in abstract classes; so you may need to wait until this CL has been reviewed and landed, but you may also be able to just go ahead and use it.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.
