### ISSUE TITLE
Specify and extend DateTime.parse

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#1878]
We need to specify what Date.fromString should be able to read.
Currently it is implementing (a subset of) ISO 8601.

**Comment by srawlins** [comment]
As per @sgjesse 's [comment], this issue just asks that the documentation feature more specification. It [does now](https://api.dartlang.org/stable/2.0.0/dart-core/DateTime/parse.html). Additionally, there is now a [tryParse](https://api.dartlang.org/stable/2.0.0/dart-core/DateTime/tryParse.html) was added, handling the `onError` request. This issue is complete. RIP February 2012.
