### ISSUE TITLE
Mirrors: newInstance on constructor with optional parameters result in crash when running as JavaScript

### ISSUE THREAD

**Issue by dotdotcommadot** [dart-lang/sdk#19635]
Creating a new instance through reflection on a class that has optional parameters in the constructor, works in Dartium.
But if you than run it as JavaScript, this throws an error.

Example:

import 'dart:mirrors';

class ClazzA
{
&nbsp;&nbsp;&nbsp;&nbsp;ClazzA([dynamic property = null]);
}

void main() 
{
&nbsp;&nbsp;&nbsp;&nbsp;ClazzA clazzA = reflectClass(ClazzA).newInstance(const Symbol(''), []).reflectee;
&nbsp;&nbsp;&nbsp;&nbsp;print(clazzA != null);
}

**What steps will reproduce the problem?**
- If you run this in Dartium, everything works as expected (prints out &quot;true&quot;)
- If you run this as JavaScript, it throws following error:

&quot;Uncaught NoSuchMethodError : method not found: 'Symbol(&quot;ClazzA&quot;)'
Receiver: Instance of 'JsClassMirror'
Arguments: []&quot;

**What is the expected output? What do you see instead?**
- expected behavior: run in both Dartium and JavaScript 

**What version of the product are you using? On what operating system?**
Dart Editor version 1.5.0.dev_04_20 (DEV)
Dart SDK version 1.5.0-dev.4.20

OS: Windows 7

---

**Attachment:**
[mirrors_constructor_test.zip](https://storage.googleapis.com/google-code-attachments/dart/issue-19635/comment-0/mirrors_constructor_test.zip) (5.84 KB)

**Comment by stevenroose** [comment]
This bug looks like a duplicate of this long-standing one: https://github.com/dart-lang/sdk/issues/18541

**Comment by eernstg** [comment]
If nothing else prevents this, you might want to consider using the package reflectable rather than 'dart:mirrors'.

I just created CL https://codereview.chromium.org/1573103003/ which contains checks to verify that the situation described here works with reflectable-transformed code. It also introduces special casing for `List` (whose nameless constructor has non-standard semantics), and fixes a bug which prevented the reflective invocation of factory constructors in abstract classes; so you may need to wait until this CL has been reviewed and landed, but you may also be able to just go ahead and use it.

**Comment by matanlurey** [comment]
Mirrors is no longer supported in Dart2JS.

**Comment by stevenroose** [comment]
*sigh* Killing reflection altogether?
