### ISSUE TITLE
dart2js: HttpRequest.request(responseType: "json") is horribly slow

### ISSUE THREAD

**Issue by jbdeboer** [dart-lang/sdk#19643]
Setting responseType: &quot;json&quot; in HttpRequest causes the browser to parse the response text as JSON.  Since the browser can do this in C++, it should be very efficient.

However, the dart2js implementation is very slow.

I have a benchmark (https://github.com/jbdeboer/angular.dart/blob/jun24-xhr-benchmark/benchmark/web/xhr.dart) comparing responseType: &quot;json&quot; to parsing JSON using dart:convert.

-&gt; Parsing a 429K JSON file with JSON.decode() takes ~300ms.

-&gt; responseType: &quot;json&quot; returns an object fairly quickly, within 11ms. However, accessing that object takes ~9000ms.

A JS profile shows that the time is spent in &quot;_convertNativeToDart_XHR_Response&quot;

---

To run the benchmark:
checkout the above github repo,
cd benchmark/
pub get
pub build
python -mSimpleHTTPServer

navigate to http://localhost:8000/build/web/xhr.html
select either checkbox and click &quot;once&quot;

The results will appear at the bottom of the page after &quot;Done&quot;

The &quot;loop&quot; buttons, nor the stats work for this benchmark.

**Comment by alan-knight** [comment]
Using the json return type may not be that good an idea. I don't think it's supported everywhere. And although the browser can do the decoding in C++, the result then has to get converted into the Dart representation. And that's an expensive conversion, because it's passing through the general structured clone algorithm. Right now that's implemented using a linear search to preserve identity. We should fix that, but it's still doing work to preserve identity on something where it shouldn't matter.

**Comment by rakudrama** [comment]
As soon as we know the value from the response field is JSON (i.e not a String / Document / Blob /  ArrayBuffer), we should convert it with _convertJsonToDartLazy from js_runtime/convert_patch.dart.

This should be no worse than JSON.decode() of a text response.

For the comparison to be fair, you need to include the cost of walking the JSON since JSON.decode() is lazy in converting to Dart objects.  (One way to do this is to JSON.encode the result.)

Sharing the code between dart:html and dart:convert will require a little bit of refactoring to expose the function across libraries.

I see according to http://caniuse.com/#search=xmlhttprequest%20ad IE11 does not support responseType="json".

**Comment by alan-knight** [comment]
This doesn't seem like it should be closed. There's a clear action item.
