### ISSUE TITLE
Dart2js mixin in typed data list does not get the correct type parameter.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#20085]
We have 
&nbsp;&nbsp;abstract class NativeTypedArrayOfInt
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;extends NativeTypedArray
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with ListMixin&lt;int&gt;, FixedLengthListMixin&lt;int&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;implements List&lt;int&gt; {
and
&nbsp;&nbsp;class NativeUint8List
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;extends NativeTypedArrayOfInt
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;implements Uint8List native &quot;Uint8Array,!nonleaf&quot; {

The implementation of NativeUint8List.where is inherited from ListMixin&lt;int&gt;, but when called, its type parameter is missing/dynamic, so the returned Iterable is a WhereIterable&lt;dynamic&gt;, not WhereIterable&lt;int&gt;.

**Comment by rakudrama** [comment]
There are two problems.

```dart
import 'dart:typed_data';
main() {
  var x = new Uint8List(1);
  print(x is List<int>);
  print(x is List<String>);
  print(x.where(null) is Iterable<int>);
  print(x.where(null) is Iterable<String>);
}
```
(prints __true__, __false__, __true__, __true__).

The first problem is that ListMixin.where$1 passes the argument `receiver` to getRuntimeTypeArgument.
The lookup of the substitution function is done on the receiver, but it should be done on the interceptor for the receiver.
It would be best if the interceptor was passed in to getRuntimeTypeArgument, since it is almost always available locally (e.g. as `this`).

```js
       where$1: function(receiver, test) {
        return H.setRuntimeTypeInfo(new H.WhereIterable(receiver, test), [H.getRuntimeTypeArgument(receiver, "ListMixin", 0)]);
      },
```

The second problem is that the mixin application is missing the `$asListMixin` substitution.
It appears to be related to https://github.com/dart-lang/sdk/issues/20113

**Comment by rakudrama** [comment]
This problem will block strong mode.
`getRuntimeTypeArgument` could call `getInterceptor`, but that would be very expensive.
The cost might be reduced by making getRuntimeTypeArgument a method, since the interceptor and receiver are always available in the method (this = interceptor).

The $asListMixin substitution would need to be using interceptor calling convention, passing the receiver as a parameter.

**Comment by sigmundch** [comment]
@rakudrama fixed this when adding `getRuntimeTypeArgumentIntercepted`
