### ISSUE TITLE
[next] Dart should allow cross frame dom access to windows from the same origin.

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#20146]
We currently only allow limited access to the cross-frame windows.  JavaScript allows complete access - so long as the window is from the same origin.  We should just match JavaScript.

At the moment, folks are just using dart:js to circumvent this restriction, so we're not really achieving anything with this.

This change will a fair bit of work - at least the following:
- An API change in dart:html
- Plumbing in dart2js to correctly handle DOM types in different frames
- Plumbing and correct SOP security checks in dartium
- Fixes in js-interop

**Comment by DanielJoyce** [comment]
Bumping into this issue in a multi window chrome app. This is a dumb restriction. Wasted 3 days so far. Thinking of jumping to TypeScript.

**Comment by Jop-V** [comment]
Blocker for me.

**Comment by zoechi** [comment]
I really hope this will be fixed with the next Dartium version due in the next weeks.

**Comment by alan-knight** [comment]
I think that Dartium in 1.13 actually returns a Window rather than a WindowBase for a cross-frame Window. That isn't so much an intentional change as an unintended consequence of going via JS Interop and not inserting the matching type conversion. So what is it you're looking to see fixed in Dartium? At this point the primary effort on Dartium is rolling to a current Chrome version.

@Jop-V can you be more specific about what's blocking you? I don't think dart2js behaviour has changed. But it should still be possible to work around this fairly easily by accessing in JS.

**Comment by mouze** [comment]
I want to write comment here, because we need solve this issue.

DART is very good language and we are pleased to work in it.

We work on large application and we need build some content of page inside iframe.
Content is completely built by main window. It must be in iframe because we need load different style for it, which use CSS3 Media Queries.

We use little hack, but from DART 1.14 there is new bug. And we are also limited by other bugs in JS interop and dart2js.

See:
https://github.com/dart-lang/sdk/issues/25871
https://github.com/dart-lang/sdk/issues/17936
...

thank you for great work
