### ISSUE TITLE
Make new optional

### ISSUE THREAD

**Issue by Zectbumo** [dart-lang/sdk#20750]
I see how `new` makes it familiar to new programmers but the `new` keyword is really not necessary in the end. Dart has named constructors and static methods and it is up to the library maker to decide which is appropriate to use. Currently named constructors need `new' while static methods do not. My focus here is to relieve the programmer of having to remember what side of the bed the library developer woke up on and remembering do I need the new keyword or not. 

Story time:
One day a library developer woke up and said parsing ints from strings is &quot;discovering&quot; the int so therefore it is not a constructor and a static method instead: Integer.parse(); was born. The library user MUST NOT use `new` to construct this Integer. Then another morning a library developer makes Element.html() and this time he think this is a constructor. The library user MUST use `new` to create his Element. This requires the library user to stop and think, do I need `new` or not?, when really in the end the library user just wants an object created; it doesn't matter how it's made.

Before:

```dart
var now = new DateTime.now();
var num = Integer.parse('54');
var elm = new Element.html(<u>54&lt;/u&gt;');
```

After (optional):

```dart
var now = DateTime.now();
var num = Integer.parse('54');
var elm = Element.html('<u>54</u>');
```

A discussion in issue #18241 talks about making `const` and `new` together being optional. This issue was created to focus on just making the `new` keyword optional.

**Comment by ahmetaa** [comment]
@Emasoft,

The percentage of people who do not follow the style guide for method and class names will probably be minuscule (Probably some C# programmers). So Such ambiguity can be tolerable. And, in such cases, analyzer should emit a warning so this is really not a big issue. I believe removing "new" is the way to go.

**Comment by motleytech** [comment]
Reading this conversation has been interesting.

I realized that some of the community really likes the `new` keyword and fights to retain it. I being from the python community don't know of a good reason to have new at all... and was hoping to learn something here.

However, most of what I hear is that "its already here, and its not a big pain, so lets keep it" and "it can lead to less info if a new object is being created". I have never seen the "less info" problem in our 10000 file python codebase... for the simple reason that all classes are Capitalized. And pep8 / pyflakes tests automatically fail if that's not the case.

Also, I am surprised to know that the `new` is technically not required. Why did we agree to get chained to the `new` and even more bizarre, how did we come to depend on it so much that we can't even let it become optional? This is like religion.

**Comment by Zectbumo** [comment]
The `new` conversation is interesting and I am back to add more. I have kept this issue in the back of my mind for about a year now I have found a technical point along the way. So far the discussion has been very opinionated with weak arguments but I have been looking for an actual technical difference. 

Dart:
```dart
class A {}

main() {
  var B = A;
  new B(); // [error on line 5] 'B' is not a type.
}
```

Javascript:
```javascript
function A() {}

var B = A;
new B(); // returns instance of A. This actually works!
```

Dart could be using the `new` keyword to restrict this dynamic usage on purpose for whatever reason. The only reason I can think of is for optimization purposes since Javascript is able to do it. I can see something like this holding the language back from "simply" removing new. It would be nice to hear from someone with deep technical knowledge about this.

P.S. Just to make things clear: I'm still against the enforcement of `new`.

**Comment by zoechi** [comment]
```
class A {}

main() {
  var B = A;
  new B(); // [error on line 5] 'B' is not a type.
}
```
I think this should work with https://github.com/dart-lang/dart_enhancement_proposals/issues/4

**Comment by kasperpeulen** [comment]
I think this may be the way to go, especially with the new linter. For example, you could then make sure the code base always uses uppercase for classes. 

I would prefer removing new keyword completely, but I think this would be better, then the current situation.

**Comment by sethladd** [comment]
FWIW this would help Flutter code, which create a lot of new instances in build() methods.

**Comment by lenkite** [comment]
Kotlin (language for JVM) also omits the new keyword. Look at type safe builders in Kotin. They are *so* beautiful to work with and UI object hierarchies can be constructed with ease and readability is terrific! Dart really needs syntactic sugar here - making new optional would help a bit. 
```kotlin
verticalLayout {
    val name = editText()
    button("Say Hello") {
        onClick { toast("Hello, ${name.text}!") }
    }
}
```

**Comment by floitschG** [comment]
Optional new is an accepted feature.
We are not working on it right now, but it's on our roadmap. Unfortunately, I can't give any timelines.

**Comment by hooluupog** [comment]
Here's my two cents on the subject,
```
class A{
    int a,
    String b;
    A(this.a,this.b);
}
List<A> list = [new A(1,"abc"), new A(2,"abcd"),...];
```
After new being optional, it will be great if i can write
`List<A> list = [(1,"abc"), (2,"abcd"),...];`   
 Both 'new' and 'A' are removed(list's type is already declared, so the types 'A' on the right are redundant).

**Comment by Emasoft** [comment]
@hooluupog What? The Dart design team already made the code unreadable enough making 'new' optional. Now you suggest to make type names optional? How the hell I'm supposed to know what this line of code means, for example?

`myObject.MyMethod([(1,"abc"), (2,"abcd"),...])`

Somebody is forgetting that readability and understanding of code is the MOST IMPORTANT FEATURE of a programming language. Otherwise we would all be better to keep writing in binary 010101...

**Comment by hooluupog** [comment]
@Emasoft I do not suggest to make type names optional.In fact,I fully support strong type. What i mean is to remove unneeded redundancy. Even in Go(which is a very opinionated language),I
can write `list =  []A [{1,"abc"}, {2,"abcd"},...]  //A is a struct in Go.`

**Comment by Emasoft** [comment]
@hooluupog I can still read the type in your Go example. The A is at the right side of the assignement operator. Not in your proposal. At the right side of '=' you don't have type names anymore, and this is confusing. 

Answer my above question:

If I can declare a List<A> just like you say:

`List<A> list = [(1,"abc"), (2,"abcd"),...];`

Then I should be able to pass the same to a method with the following signature:

`void MyMethod(List<A> list);`

But then how I'm supposed to know what this line of code means?

`myObject.MyMethod([(1,"abc"), (2,"abcd"),...])`

Can you see what I mean?

**Comment by lrhn** [comment]
That particular shorthand is unlikely to be accepted. Apart from the lower readability, it's also ambiguous. It looks simple here because the `A` constructor takes two arguments, but what if it was just
```dart
List<B> list = [(x + 2)];
```
It's very non-obvious that you need to coerce `x + 2` to `B`. Also, it assumes that you will use the empty-named constructor (`new B(x + 2)`), but there is no help in using a named constructor - if `B.foo` is the right one to use, this syntax doesn't allow it.
I'm more interested in explicitly omitting the class name where it's given, so maybe something like:
```dart
List<B> list = [.foo(x + 42)];
```
would mean that the omitted thing before the `.` is the expected type.

**Comment by Emasoft** [comment]
@Irhn That point is hard to spot. You can easily miss it, or type it by error. That is an even more unreadable expression. 

Readability must be paramount. Do you know that on average we spend 87% of the development time debugging and looking for errors in the code and only 13% of the time actually writing the code?
After all this years there is still people (script kiddies, mostly) who think that typing less characters is cool or smart... well, I have bad a news for them: it is dumb. The dumbest thing you can do.

**Comment by zoechi** [comment]
I don't think the `.` is too hard to spot (I guess better syntax ideas are always welcome though).
Also I'd expect the analyzer to generate an error in case it is typed unintentionally.

I also don't think writing less code is an important goal, but more code is more to read and redundant information like repeated type annotations often make the code harder to read, which should be a good enough reason to try to get rid of them.

**Comment by Emasoft** [comment]
The `.` is the smallest character of all, of course it is hard to spot! It is also used for MULTIPLE functions. You can have many dots one near each other, with different functions, when you use floating point numbers (0.011*-1.2/4-.A*4.21-.B*0.11-.A-.102+1.2-.A*0.1-.B-.01/.A+.3 <- try to guess if there is a dot that is not right). There is a basic language design imperative, and that is to make errors easy to spot.

**Comment by zoechi** [comment]
It takes as many space as any other character ;-) and there are no other places where `.` comes before a non-numeric character, therefore I find it quite distinctive. `.` before numeric characters is quite seldom and usually stands out as number value. As mentioned I can imagine that there are better options, which is why I wrote "(I guess better syntax ideas are always welcome though)"
And the options are quite limited, because other symbol characters are already in use for other constructs.

**Comment by eernstg** [comment]
Closing: With the feature specification on [implicit creation](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/implicit-creation.md), it has been decided that Dart _will_ have the feature which is requested here. ;-)

For an instance creation expression (say, `new C(42)` or `const C(42)`) it is allowed to leave out the `new` or `const` keyword (yielding `C(42)`). The decision about whether such an expression means `new ...` or `const ...` is a little bit involved, but the main idea is that it will be `const` when ever possible, and otherwise `new`; said feature specification has the details.

**Comment by sethladd** [comment]
Cool! is there a tracking issue for the implementation?

**Comment by eernstg** [comment]
Yep: #30921. Note that the 'Specification' subtask isn't checked, but that is the language specification proper. The design has been finalized and agreed to, and it is documented in the [feature specification for implicit creation](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/implicit-creation.md). That material will later be integrated into the language specification.

**Comment by redradist** [comment]
Guys, from my point of view having "new" keyword for instance creation and without it, seems like noisy
... Because it is two different ways of creation of object ...

Will be new keyword removed in future completly ?

**Comment by lrhn** [comment]
No promises. I hope it will be removed at some point, but it's a low-priority and heavily breaking change, so the cost/benefit ratio is not in its favor as a stand-alone change. 

If we have another *related* language change, we may be able to roll the removal of `new` into that (if you are going to run a migration program on your code, we can remove the `new` for you as well).
It's probably not something we'll do as part of an otherwise unrelated language change.

**Comment by eernstg** [comment]
Eliminating `new` completely is not obviously an improvement. If you use `new e` with some term `e` rather than `e` on its own then you've specified that evaluation must invoke a constructor. This is not an ironclad guarantee that it will yield a fresh object (but the exception, a factory constructor, is written knowing that it should be OK to view the returned object as fresh). So a few well chosen `new` keywords might be helpful for the reader of a piece of code.

Of course, we could also eliminate `new` completely, and then later add support for an `@isNew` annotation on expressions, and enforce that each expression has this marker if and only if it yields a fresh object, with some `document_instance_creation` lint. That would teach those nasty factory constructors a lesson, and solve the halting problem. ;-)
