### ISSUE TITLE
Line-based stepping

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#21081]
The observatory stepping is currently not line-based. So multiple statements on a line, or string interpolations, might make it take more than one &quot;step over&quot; operation to get to the next line. Lines that seem likely to be optimized away get stepped over completely (e.g. var a = 1;).  I like statement-based stepping, but it's not consistent with what the editor debugger does, and for tools that have line-based breakpoint setting and stepping, it's good to have the ability to step by lines.

**Comment by turnidge** [comment]
We have decided not to implement step-by-line in the vm.  Instead clients should implement it themselves, if they need it, by repeated stepping.

In the Observatory debugger, we highlight the current column number while debugging, so this kind of intra-line debugging is a lot less confusing now than it was when this bug was initially filed.

Closing
