### ISSUE TITLE
The error "initializer type '...' cannot be assigned to the field type '...'" should be checked using actual types of constants

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#21119]
The following code:

&nbsp;&nbsp;class A {
&nbsp;&nbsp;&nbsp;&nbsp;const A();
&nbsp;&nbsp;&nbsp;&nbsp;const factory A.foo() = B.foo;
&nbsp;&nbsp;}
&nbsp;&nbsp;class I {}
&nbsp;&nbsp;class B extends A implements I {
&nbsp;&nbsp;&nbsp;&nbsp;const B.foo();
&nbsp;&nbsp;}
&nbsp;&nbsp;class C {
&nbsp;&nbsp;&nbsp;&nbsp;final I i;
&nbsp;&nbsp;&nbsp;&nbsp;const C() : i = const A.foo(); // ERROR
&nbsp;&nbsp;}
&nbsp;&nbsp;main() {
&nbsp;&nbsp;&nbsp;&nbsp;print(const C());
&nbsp;&nbsp;}

Produces the following analyzer error on the line marked &quot;// ERROR&quot;:

&nbsp;&nbsp;The initializer type 'A' cannot be assigned to the field type 'I'

This should be a warning, not an error.  The reason it should not be an error is because an error should only be generated if evaluation of the constant would produce an exception.  Since the actual runtime type of &quot;const A.foo()&quot; is B, and B *is* assignable to I, evaluation of the constant would not produce an exception (in spite of the static type mismatch).

Dart2js produces the correct warning in this case.  The VM has the correct behavior (no exception is thrown).

The reason analyzer is generating the incorrect error is because it is deciding whether to produce the error based on static types rather than the actual types of the constants.

**Comment by MichaelRFairhurst** [comment]
I'm going to deprioritize this to 2.1. The referencing issue (#33304) has also been moved. And this piece of that issue has been filed since 2014, so, it doesn't seem urgent.

If anyone disagrees do by all means weigh in.

**Comment by natebosch** [comment]
The VM currently fail with an error matching analyzer so it's possible this should be close as Working As Intended depending on what the spec says.

**Comment by bwilkerson** [comment]
@leafpetersen What is the correct behavior under Dart 2?

**Comment by eernstg** [comment]
The static type of a constant expression of the form `const A.foo()` shown [in the example](https://github.com/dart-lang/sdk/issues/21119#issue-84591111) is `A` ([specified here](https://github.com/dart-lang/sdk/blob/9388cb3d0c3788ee37f84eddb6bff8e7a6bace62/docs/language/dartLangSpec.tex#L4983)), which makes `i = const A.foo()` a downcast, which is allowed.

The language specification does not mention exact types, so we shouldn't [yet](#33307) consider any usage thereof as specified behavior, but if we make the choice to define exact types and use them to reject downcasts (because a downcast from an exact type is guaranteed to fail), then we could make that initializer an error.

Apparently, this is what already happens (I know that we _do_ have some usages of exact types already, and I'd like to get it specified rather than eliminated ;-).

On top of that, we do have the ability to inspect the actual value of a constant expression at compile-time (because we are allowed, but not required, to evaluate it at that time). This would allow us to detect that this particular constructor invocation will deliver an instance of a proper subtype of the static type, and in that case we could cancel that error again "OK, it will work after all".

But we don't have any verbiage in the specification about ignoring the rules about static types just because a particular expression happens to have a value which can be made available already at compile-time.

So we're dancing around several subtle issues here in order to arrive at a conclusion, but I think it makes sense to say that the `// ERROR` line is indeed an error, and whoever is not happy about that should make sure that the declared types are adjusted to express the intentions a bit more clearly.
