### ISSUE TITLE
Analysis server should support ephemeral ports

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#21477]
Currently, the analysis server's command-line API provides no way of binding itself to an ephemeral port. Or rather, it can bind to one, but it doesn't inform its caller what the concrete port it's bound to is, so it's not all that useful.

**Comment by natebosch** [comment]
I think this might be referring to the port for the diagnostic web server (thats the `--port` flag anyway)? Most other communication happens over stdin/stdout

It's possible now to start up that server and get it's port by making a `getServerPort` request which i think would satisfy this need. In any case we don't have any plans to combine the analysis server with the build server for now so I don't think this issue is worth keeping open.
