### ISSUE TITLE
Many pkg/analyzer and pkg/analysis_server tests are timing out on dart2js

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#21628]
When you examine the dart2js logs, you'll find things like this at the end:

0:00:45.909000 - dart2js - dart2js-d8 release_ia32/pkg/analysis_server/test/edit/sort_members_test
0:00:42.850000 - dart2js - dart2js-d8 release_ia32/pkg/analysis_server/test/edit/fixes_test
0:00:42.618000 - dart2js - dart2js-d8 release_ia32/pkg/analyzer/test/enum_test
0:00:38.021000 - dart2js - dart2js-d8 release_ia32/pkg/analysis_server/test/search/type_hierarchy_test
0:00:36.872000 - dart2js - dart2js-d8 release_ia32/pkg/analysis_server/test/search/member_declarations_test

This means that dart2js takes rather long to compile the listed tests. Since the timeout is 60 seconds, 45 seconds doesn't leave much room if a machine is configured differently. On my machine, these tests time out.

Assuming that there's nothing else to do to make the tests themselves smaller, I think two things are needed:

1) increase the time out (use &quot;Slow, Pass&quot; as test status).

2) report a bug with the dart2js team pointing out that the compiler is too slow, or that the default timeout is too low.

**Comment by floitschG** [comment]
I had to add another test to this list.
Does the analyzer really need reflection for all of its tests? This slows down the testing tremendously.

**Comment by bwilkerson** [comment]
Many of our tests make use of shared utility code, and those utilities are much cleaner if we can store state in the test object (rather than pass around large numbers of arguments). The unittest framework doesn't make it easy to do this; it's much easier when the test code is in classes that can inherit from one another.

We tried a scheme in which we passed static methods in to the 'test' method, something like:

    group('Scanner tests', () {
      test('ampersand', ScannerTest.ampersand);
      test('ampersand_ampersand', ScannerTest.ampersand_ampersand);
      test('ampersand_eq', ScannerTest.ampersand_eq);
      ...
    });

but the bookkeeping required every time we added a new test was painful.

So for the sake of our own productivity, we settled on using reflection. If you have other suggestions for how to write these tests, I'm more than happy to consider them.

**Comment by sigmundch** [comment]
@nex3 is this easier to do with the new `package:test`?

@bwilkerson - one idea would be to materialize the main test file. For example, use the vm + reflection like you do now, but instead of running tests, generate a static file with a main that contains all the group and test calls, and submit the auto-generated file with your tests. With this approach I guess you could replace reflection with a library written with analyzer itself :-)

**Comment by nex3** [comment]
> is this easier to do with the new `package:test`?

Eventually we'll add a plugin system that should make this possible but for now it's no easier than it would have been with the old package.

**Comment by whesse** [comment]
I don't understand why it is hard to do what Brian mentioned above, where he said:

"We tried a scheme in which we passed static methods in to the 'test' method, something like:
test('ampersand', ScannerTest.ampersand);

It would be really good to make the tests faster, to decrease the cycle time on the buildbots.
What do you mean by "the bookkeeping was painful"?

**Comment by bwilkerson** [comment]
It's hard because it requires an extra step that we're not used to having to do and is therefore easy to miss. Every time we wrote a test method we had to remember to go add it to the list of test methods to be run rather than have it be found automatically. It's equivalent to us saying: the test framework will no longer look for files whose name ends in "_test.dart", instead we've created a file named "test_suite.yaml" that you need to edit every time you add a test file, and if you forget to add it we won't be able to tell you that your test isn't actually running.

**Comment by whesse** [comment]
OK, I thought that the test functions would just be in the same file as the class with the static methods, so  that the class and all of its tests would be in the same file, and it would be run by pub run test automatically, since it ends in _test.dart.  Can classes not be put in the individual test files?

**Comment by bwilkerson** [comment]
They are in the same file, but it still proved to be error prone.

**Comment by bwilkerson** [comment]
I believe that the problem is in the test framework, not the tests. If you disagree, please start an e-mail conversation with me.
