### ISSUE TITLE
Add definite assignment analysis for local variables

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#21811]
It would be useful for analyzer to be able to perform a definite assignment analysis on local variables.

**Comment by stereotype441** [comment]
@leafpetersen suggested yesterday that before trying to nail down exactly what the definite assignment rules should be, we may want to test a large corpus of code a few variants of definite assignment analysis (a minimal set of rules, a larger set of rules, a maximal set of rules) to see how much benefit we would get in practice from a more complex vs. less complex implementation.

**Comment by scheglov** [comment]
I ran definite assignment analysis with reporting hints where we cannot prove that the target is not null.
  Projects:
analysis_server
analyzer
analyzer_cli
analyzer_plugin
compiler
dartfix
front_end
kernel
meta
test
testing

  This hint is different than the initial design goal for definite assignment - which was to make sure that if a variable is defined as non-nullable, then it is really never used before it was assigned a value, and because its type is non-nullable, the assigned value will also be verified to be non-nullable (not in definite assignment analysis).  Here, however we don't know if the variable is supposed to be non-nullable, we just try to guess if it could.

  I did not get the point of changing sets of rules yet, but I looked into why we would think that a variable might be null.

1.1. Any reference: 1097
1.2. Only target of IndexExpression, MethodInvocation, PrefixedIdentifier, PropertyAccess: 225
1.3. Not protected with `?.`: 215


Other guards:
1. if (v != null) { ... }
  49

2. if (v is T) { ... }
  19

3. if (v == null || v.foo) {}
  6

4. if (v == null) return;
  20

5. if (v == null) { ... } else { v.foo }
  2

6. if (v == null) {  v = foo; }
  13

7. v == null ? foo : v.bar    or   v != null ? v.foo : bar
  14

8. if (...) else { somethingThrowingException(); }
  12



Problematic:
1. Implicit non-nullability because of other variable values.
  39

2. if (...) else if (...) that probably covers all possible conditions, but no final `else`.
   So, it might be correct, but there is no way to automatically prove it.
  5

3. In tests, maybe actually allowed to be `null` and crash.
  1

4. In tests, set in callback, cannot be proved that always invoked, e.g. setUp() in canonical tests, or Stream.listen().
  29

5. switch (intValue) without `default`.
  1

6. Call local function that sets variables, invoked, and then the variable is read.
  7

7. Local function references a variable that is assigned later, but still before the function invocation.
  1

**Comment by scheglov** [comment]
Example for "Implicit non-nullability because of other variable values". See `InferenceVisitor.visitListLiteralJudgment()`:

```dart
  void visitListLiteralJudgment(
      ListLiteralJudgment node, DartType typeContext) {
[cut]
    List<DartType> formalTypes;
    List<DartType> actualTypes;
    bool inferenceNeeded = node.typeArgument is ImplicitTypeArgument;
[cut]
    if (inferenceNeeded || typeChecksNeeded) {
      formalTypes = [];
      actualTypes = [];
    }
[cut]
    if (inferenceNeeded || typeChecksNeeded) {
      for (int i = 0; i < node.expressions.length; ++i) {
[cut]
        if (inferenceNeeded) {
          formalTypes.add(listType.typeArguments[0]);
        }
        actualTypes.add(getInferredType(judgment, inferrer)); // NB: guarded by inferenceNeeded || typeChecksNeeded
      }
    }
[cut]
  }
```

Or `substituteRange` from `type_algorithms.dart` in Kernel.
```dart
  if (type is KernelFunctionTypeBuilder) {
    List<KernelTypeVariableBuilder> variables;
    if (type.typeVariables != null) {
      variables =
          new List<KernelTypeVariableBuilder>(type.typeVariables.length);
    }
    List<KernelFormalParameterBuilder> formals;
    if (type.formals != null) {
      formals = new List<KernelFormalParameterBuilder>(type.formals.length);
    }
    KernelTypeBuilder returnType;
    bool changed = false;

    if (type.typeVariables != null) {
      for (int i = 0; i < variables.length; i++) { // `variables` cannot be null, guarded by `type.typeVariables != null`
[cut]
```

**Comment by srawlins** [comment]
I imagine this can be closed? We support definite assignment as specified by the Non Null spec.
