### ISSUE TITLE
Mirrors: Need a way to get a Type object with type parameters replaced with dynamic

### ISSUE THREAD

**Issue by justinfagnani** [dart-lang/sdk#21833]
I need to be able to get a type object form a TypeMirror that I can compare against type literals, even with generic types. TypeMirror.originalDeclaration doesn't work, because it doesn't have a reflectedType. Since type literals always have dynamic for the type parameters, I'd like to just replace all type arguments with dynamic.

My use case is something like this:

// factory.dart
registerFactory(Type t, Factory f);

getFactory(Type t);

This library is not tightly coupled to reflection-based code. registerFactory() is always called with a Type liters.  getFactory() is called with a type literal by certain clients.

One client is reflection-based though,

var typeMirror = getMirror();

getFactory(typeMirror.reflectedType); // doesn't work when the type is generic
getFactory(typeMirror.originalDeclaration.reflectedType); // throws when type is generic

Ryan suggests something like:

TypeMirror.rareType

which strips the generic arguments.

**Comment by eernstg** [comment]
This may affect features outside of `dart:mirrors`, but 'area-library' is probably fine.

In particular, we have had several proposals for a feature that might take the shape of `o.runtimeClass` or `Type.classOf(o)` which would differ from (the built-in implementation of) `runtimeType` in that it would yield a representation of the class rather than any particular generic instantiation thereof. One of the important points of having this is that it does _not_ imply that the type arguments of every class that might be the run-time type of `o` (and all its superclasses, and whatnot) must be reified, which may incur a significant penalty in terms of space (and maybe time).

This is not exactly the same thing as obtaining `C<dynamic, ...>` with a suitable number of `dynamic` for any given generic class `C`, because Dart 2 makes that list of actual type arguments an error (and in a reflective setting it would be a dynamic error) whenever `C` declares a bound for any of its type parameters (which is not `Object` or another top type).

So I agree that this is not stale.
