### ISSUE TITLE
Provide a method in the core libraries that indicates whether the app is running on the server or web.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#21832]
Provide a method in the core libraries that indicates whether the app is running on the server or web.

Proposed return values:
web, server

Currently users determine whether they are on the web by hacks such as &quot;1.0 is int&quot; which makes the code vulnerable to changes in dartium flags that impact number semantics.

**Comment by lrhn** [comment]
Why is the distinction needed?
In the perfect world, there wouldn't be any need to distinguish, but obviously we're not in that world.
If it's in order to predict the non-standard integer behavior of JS compiled Dart code, then checking `1.0 is int` is probably the reasonable thing to do. That is exactly the problem, if JS gets integers and we change to compile Dart to those, the test will successfully detect that, even if we are still on the "web".


You could also use `const bool.fromEnvironment('dart.library.html')` as a sign that HTML functionality is available, which probably means the web (whether in Dartium or compiled to JS).

Reporting a specific platform is *dangerous*. For one thing, it's open-ended. Is Flutter considered "server"? It's a client app platform, but it's not web based. So it's probably netiher "web" nor 'server", so we need more possible values, which again means that just returning some magical string is not future proof. 
Your code that does:
```dart
if (... == "web") {
  something
} else {
  // it's server
  something else
}
```
will be wrong. There is no way to cover all platforms, and I'd prefer to not add something to the platform libraries that makes it *harder* for a new platform to adopt Dart.

So, all in all, I don't think we want to answer the question "what 'platform' is this", but if there are more precise questions that would solve the real problems, we might find a place to answer those.

**Comment by matanlurey** [comment]
I think its safe to say this is stale.
