### ISSUE TITLE
Animation-related tests time out on IE 10 and Chrome on MacOS

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#22167]
The tests

html/request_animation_frame_test: Skip # Times out.
html/transition_event_test/functional: Skip # Times out.

time out flakily on IE 10.  This started when we started running co19 tests on the build slaves, increasing the load.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/sdk/issues/53985 which has more details on both of these tests for modern Chrome releases (and not IE since support was dropped).

Improvements to the tests also landed recently in https://github.com/dart-lang/sdk/commit/c439c97b80d6b0d1556e394bd12053864bad45d2, https://github.com/dart-lang/sdk/commit/6b8224d2e5ca9633a2c1d50960f36c268e3b7b75, https://github.com/dart-lang/sdk/commit/e52de71408e7900487a518f8ea579e3b2edd9e04
