### ISSUE TITLE
Add Map.removeWhere

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#22303]
From a user:

I have a map, and I'd like to remove all the items in that map that match a particular condition.

If this was a list, I could do

&nbsp;&nbsp;&nbsp;list.removeWhere((item) =&gt; item.matchesMyCondition);

**Comment by Hixie** [comment]
I had a similar need today. I wanted to remove a value from a map, but didn't know it's key. I wanted to find out its key, then remove it. I ended up having to walk the entire map to find the value, then remove the corresponding key, instead of being able to call a single API function.

**Comment by Hixie** [comment]
I ran into this again. I wanted to iterate over a map holding a cache, removing stale entries. But I can't use a for loop to do that because you can't modify the loop while iterating over it. So I have to first find all the keys I want to remove, then iterate over that list removing them, which is a pain.

**Comment by Hixie** [comment]
Ran into this again, same use case: trying to clear out stale entries in a cache.

**Comment by floitschG** [comment]
Will be in Dart 2.0.

**Comment by bkonyi** [comment]
Documentation [here](https://api.dartlang.org/dev/2.0.0-dev.40.0/dart-core/Map/removeWhere.html). Closing.
