### ISSUE TITLE
Don't suggest using classes from "test" in the package implementation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#22358]
In the picture below RefactoringStatusTest is located in the &quot;test&quot; folder.
Nobody should import test classes from implementation.
So, we should not suggest them.

______
**Attachment:**
[Screen Shot 2015-02-10 at 9.11.36 AM.png](https://storage.googleapis.com/google-code-attachments/dart/issue-22358/comment-0/Screen Shot 2015-02-10 at 9.11.36 AM.png) (82.92 KB)

**Comment by zoechi** [comment]
For code in lib, bin, and web nothing frm dev_dependency should be listed, not only not test

**Comment by danrubel** [comment]
In the analysis server, is there a way to tell whether an element is part of a dev_dependency?

**Comment by bwilkerson** [comment]
Nope. The .packages file contains every package, including dev dependencies, and does not distinguish between them. Which means that you can reference dev dependencies in the lib directory and we cannot tell you that it's wrong.

**Comment by zoechi** [comment]
Can linter rules access `pubspec.yaml` to get that information?

**Comment by lrhn** [comment]
Would it make sense for pub to create a separate `.packages` file in the test directory, or are dev-dependencies used in other places too (other than pub, which should be able to handle itself)?

**Comment by bwilkerson** [comment]
> Would it make sense for pub to create a separate `.packages` file in the test directory, or are dev-dependencies used in other places too (other than pub, which should be able to handle itself)?

I suggested that possibility, but the folks who maintain pub didn't think that was the best solution. I still think it's attractive because it solves the problem for developers that don't use pub, but there is a performance cost that we'd have to solve before it was realistic.

> Can linter rules access `pubspec.yaml` to get that information?

Yes. The alternative that was proposed was for analyzer (and hence linter) to read the `pubspec.yaml` file to get that information. We'd effectively end up doing the same thing as if there were multiple `.package` files, so there's a performance issue to address first.

**Comment by danrubel** [comment]
We could defer reading the pubspec.yaml and performing any lints that depend upon it until after all other analysis was performed. For code completion, if the additional pubspec information was not available (e.g. dev_dependencies was unknown), then it would not use it and effectively provide the current behavior. Given this approach, I don't think there is any performance penalty.

**Comment by bwilkerson** [comment]
For code completion, no. For lints, probably not. But for things like knowing whether `package:foo/foo.dart` was valid inside `lib` or only in `test`, there might be.

**Comment by zoechi** [comment]
@bwilkerson 

> or are dev-dependencies used in other places too (other than pub, which should be able to handle itself)?

`tool` and `example` might also depend on packages that should not end in dependencies of the package user.
AFAIK actually only `lib` and `bin` should not use `dev_dependencies`

I don't know what you mean by  "other than pub"

**Comment by danrubel** [comment]
Jaime added support for filtering suggested types on the RHS based upon expression on the LHS. In addition, we no longer suggest types that are not already imported... but we need to (see https://github.com/dart-lang/sdk/issues/25820). I'm closing this as no longer applicable but added a link from https://github.com/dart-lang/sdk/issues/25820 to this issue so that when we implement, we'll take this discussion into account. Please reopen if there is still a problem.

**Comment by bwilkerson** [comment]
Is this filtering in server or in the client?

**Comment by danrubel** [comment]
in the server
