### ISSUE TITLE
Confusing error message when inheriting from an abstract class with a factory without providing a factory

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#22382]
abstract class Foo {
&nbsp;&nbsp;factory Foo([var message]) =&gt; new _Object();
}

class Bar&lt;T&gt; extends Foo {
}

[error] The generative constructor 'Foo([dynamic message]) → Foo' expected, but factory found (test.dart, line 5, col 7)

This error message is really unclear, especially if you've never seen the actual definition of class Foo (and even then, if you're not particularly familiar with Dart).

I would have been less confused with the following message, or something like it:

&quot;Class Bar extends abstract class Foo which declares a factory 'Foo([dynamic message]) → Foo', but class Bar doesn't provide an implementation for that factory.&quot;

**Comment by NingZhuRedsilence** [comment]
http://stackoverflow.com/questions/29334843/how-to-extend-an-abstract-class-with-factory-constructor

**Comment by Hixie** [comment]
I guess the message should really be "Class Bar extends abstract class Foo which does not declare a generative constructor and therefore cannot be extended", or something?

**Comment by jamesderlin** [comment]
Can https://www.dartlang.org/guides/language/language-tour#exceptions and https://api.dartlang.org/stable/2.2.0/dart-core/Exception-class.html provide an example of how to create a custom `Exception`?  I'm presuming the correct approach is to use `MyException implements Exception` rather than `... extends Exception`, but I don't see anything in the documentation providing guidance on that.

**Comment by MichaelRFairhurst** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/155831
