### ISSUE TITLE
Warning message for invalid assignment using typedef should show typedef name with applied type parameters.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#22915]
With the following code:

typedef T Fn&lt;T&gt;();
void test(Fn&lt;int&gt; f) {
&nbsp;&nbsp;Fn&lt;String&gt; g = f;
}

Analyzer issues a warning message like this: &quot;A value of type 'Fn (/Users/paulberry/tmp/test.dart)' cannot be assigned to a variable of type 'Fn (/Users/paulberry/tmp/test.dart)'&quot;.

This is confusing because the presence of paths suggests that the assignment is invalid because of a path mismatch; but that is not the case.  The actual reason the assignment is valid is because the type parameter T is different between the two types.

A much better warning message would be: &quot;A value of type 'Fn&lt;int&gt;' cannot be assigned to a variable of type 'Fn&lt;String&gt;'&quot;.

Note that invalid assignment hints have a similar problem, e.g.:

typedef T Fn&lt;T&gt;();
void test(Fn&lt;int&gt; f) {
&nbsp;&nbsp;var tmp = f;
&nbsp;&nbsp;Fn&lt;String&gt; g = tmp;
}

**Comment by asashour** [comment]
I guess this should be closed.

With the given example, there is now:

`A value of type 'int Function()' can't be assigned to a variable of type 'String Function()'.`

**Comment by bwilkerson** [comment]
Possibly.

In my mind, the outstanding question here at this point is which of the following options is better:
- display the type produced by unwrapping the `typedef`, such as `'int Function()'`,
- display the name that appears in the user's code, such as `'Fn<int>'`, or
- display both, such as `'Fn<int>' (which is equivalent to 'int Function()')`.

When the `typedef` is only a couple of lines up in the code, and there's only one level of typedef to think about, it's probably not too confusing to show the unwrapped version. But if the `typedef` comes from a third-party package the user might not even realize that the type is defined using a `typedef`, so unwrapping it might cause a lot of confusion. It isn't clear to me that showing the unwrapped version actually helps the user understand either what's wrong or how to fix it.

While I agree that what we have today is better  than what we had when the issue was created, I think maybe we should be doing even better.

@InMatrix In case you have thoughts.

**Comment by InMatrix** [comment]
I agree tying the warning message back to what's exactly in the user's code makes the message look more relevant and actionable, especially when the IDE could show red lines underneath `Fn<String>`.

**Comment by srawlins** [comment]
Since the original issue was fixed, but @bwilkerson brings up a new issue, I've changed the title.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/370701
