### ISSUE TITLE
Enums aren't canonicalized when sent over a port in a compound object

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#23244]
When sending an enum constant directly on a port, the enum constant is canonicalized correctly in the receiving isolate. However, if the enum constant is part of an object, for example, a list or a user-defined class, the enum object isn't canonicalized in the receiving isolate.

import 'dart:async';
import 'dart:isolate';

enum Fisk {
&nbsp;&nbsp;torsk,
}

isolate1(SendPort port) {
&nbsp;&nbsp;port.send(Fisk.torsk);
}

isolate2(SendPort port) {
&nbsp;&nbsp;port.send([Fisk.torsk]);
}

main() async {
&nbsp;&nbsp;var port = new ReceivePort();
&nbsp;&nbsp;await Isolate.spawn(isolate1, port.sendPort);
&nbsp;&nbsp;Completer completer = new Completer();
&nbsp;&nbsp;port.listen((message) {
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Received $message&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;port.close();
&nbsp;&nbsp;&nbsp;&nbsp;expectTorsk(message);
&nbsp;&nbsp;&nbsp;&nbsp;completer.complete();
&nbsp;&nbsp;});
&nbsp;&nbsp;await completer.future;
&nbsp;&nbsp;port = new ReceivePort();
&nbsp;&nbsp;await Isolate.spawn(isolate2, port.sendPort);
&nbsp;&nbsp;port.listen((message) {
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Received $message&quot;);
&nbsp;&nbsp;&nbsp;&nbsp;port.close();
&nbsp;&nbsp;&nbsp;&nbsp;expectTorsk(message[0]);
&nbsp;&nbsp;});
}

expectTorsk(Fisk fisk) {
&nbsp;&nbsp;if (fisk != Fisk.torsk) {
&nbsp;&nbsp;&nbsp;&nbsp;throw &quot;$fisk isn't a ${Fisk.torsk}&quot;;
&nbsp;&nbsp;}
}

**Comment by a-siva** [comment]
https://codereview.chromium.org/1260033004/ was submitted to address this issue.

**Comment by alan-knight** [comment]
This is fixed in the VM, but not in dart2js. I think the test language/issue23244_test wasn't actually verifying the condition. Now it is, and is suppressed.  @rakudrama

**Comment by whesse** [comment]
The test language/issue23244_test is passing on content_shell in checked mode, but failing on dartium.  We don't know if if passes in content_shell in unchecked mode, since that isn't run on the buildbots.

Updating the status file to say it only fails in dartium, not content_shell.  This difference should be investigated.

**Comment by whesse** [comment]
There was a comment in the status file language.status for this failure, saying "spawnFunction cannot be run in dartium".  This seems strange, if the test is passing in content_shell.

**Comment by alan-knight** [comment]
I think the restriction is really that spawn (spawnFunction is the old name) cannot be used from Dart code running in Dartium. If you use spawn in dart2js to spawn JS (or compiled Dart code) it works, and the test in question was running in Dartium but compiled to JS. So the suppression is correct, I just missed that case.

**Comment by iposva-google** [comment]
@alan-knight since you reopened this for dart2js or Dartium I am assigning this over to you. I don't think there anything for Siva to do here.

**Comment by hermanbergwerf** [comment]
I think I've encountered this issue multiple times while working with isolates. Enums that are sent (wrapped in an object) to the isolate retain the correct index but something is broken and you cannot compare them anymore (e.g. a switch with that enum won't work anymore). This is a pretty serious bug for me because now I have to 'recast' all enums in my isolate everytime (using `var value = MyEnum.values[value.index];`).

**Comment by floitschG** [comment]
@hermanbergwerf: on which platform do you encounter this issue?

**Comment by floitschG** [comment]
Never mind. I just saw the other issue: it's dart2js.

**Comment by floitschG** [comment]
@rakudrama: since dart2js can't canonicalize at runtime, we have to send the JS-name (the name of the variable that contains the constant) to the other side. This means that every constant needs to have a way to know it's own name.
Alternatively, the isolate-send function could run through all possible constants and check for identity. Things get more complicated for nested constants, though.

**Comment by lrhn** [comment]
I'm still not convinced that sending a const-created object through a `SendPort` shouldn't copy it like any other object. The object is just an object like any other created with the same constructor.

Enums are different and should be treated specially. If we had value-types, enums would be such, then there wouldn't be any problems with object identity.

**Comment by eernstg** [comment]
But maybe dart2js _should_ have the ability to canonicalize at runtime? For value types we would presumably need to support referential transparency anyway, and canonicalization may be a good choice in some situations.

**Comment by floitschG** [comment]
So far runtime-canonicalization wasn't needed, and I would definitely not want to add it.

**Comment by peter-ahe-google** [comment]
The implicit copy of canonicalized objects breaks programs and adds no value to users.

If copying can't be avoided, it would be simpler if only a few object types can be sent on ports. As implicit copy semantic completely breaks invariants, and we're forced to use JSON serialization anyway. Given that you're forced to use JSON, preventing certain object types from being transferred isn't going to be a problem, and will only serve to help users identify problems in their programs.

**Comment by lrhn** [comment]
I agree that copying objects without calling a constructor is basically broken. There are already problems with hash-based collections (because cloned objects doesn't necessarily have the same hash code as the original) and with any object that has invariants or external state (e.g., using expandos).

It would be safer to restrict to only sending "value objects" (which we don't have, so some approximation). JSON-encodable data plus capabilities can be sent to any isolate, so this is only about which other values can be sent to `spawn`-created isolates. Restricting that to static functions and enums would probably handle most cases. You have to encode your object to List/Map/primitive data, but you also avoid accidentally sending a large chunk of data that your object is pointing to internally.

On the other hand, isolate communication is already hard enough, so do we want to make it harder?

**Comment by peter-ahe-google** [comment]
> On the other hand, isolate communication is already hard enough, so do we want to make it harder?

My point is that the current state of affairs is making isolate communication harder than it needs to be: you have to be aware of implicit copies and take great care to avoid that they happen. By restricting the set of types that can be sent on a port, we would make it *easier* to avoid hard-to-debug problems.

**Comment by floitschG** [comment]
The Dart2js issue is #21817.

**Comment by eernstg** [comment]
Apparently, the connection between this issue and the test `language_2/issue23244_test` is slightly complicated, but it may still be relevant for this issue that an error occurred in that test; cf. #32043 for details.
