### ISSUE TITLE
Provide an API to enable Observatory from within the Dart process

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23320]
We want to be able to ship commands, like 'pub run test' or even globally activated tools that can opt-in to having the observatory running while running.

It's also important that the process can know which port observatory is listening on without having to parse stdout at runtime.

A top-level method in dart:io (or even a static on Platform)

Uri enableVMService({int port})

or similar

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2438613002

**Comment by nex3** [comment]
Where are the tests? I only see [one file](https://github.com/dart-lang/sdk/commit/63e4f69e5e363e13b193572acb74edc4de99c0e6#diff-12) with maybe 20 lines of actual code. Where are the tests that requests with invalid auth codes don't go through? What happens if `enable` is `false`? What happens if `enable` is `true` and there's already a server? Where are the tests for actually accessing members of `ServiceProtocolInfo` rather than just printing the `toString()`?

This also seems substantially under-documented. There's no documentation for the `enable` parameter, there's no indication what hostname or port will be used for the service protocol, there's no way for a new user to figure out what the "service protocol" even is.

**Comment by kevmoo** [comment]
Tests have been updated by @a-siva https://github.com/dart-lang/sdk/commit/b2f3bb6711208346245cd334f54d4472dd443ad0

It'd be great if we could get some improved documentation here.

**Comment by joeconwaystk** [comment]
Was an option to select port ever added here? Can't find it in API ref.
