### ISSUE TITLE
finally executed twice when cancelling async* subscription

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#23436]
The sample program below prints:

counter = 1
counter = 2
counter = 3
counter = 4
stopping the async process
stopping the async process

But it should print &quot;stopping the async process&quot; only once.

import 'dart:async';

process(period) async\* {
&nbsp;&nbsp;try {
&nbsp;&nbsp;&nbsp;&nbsp;var counter = 0;
&nbsp;&nbsp;&nbsp;&nbsp;await for (var tick in new Stream.periodic(period)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;counter++;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print('counter = ${counter}');
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;} finally {
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;stopping the async process&quot;);
&nbsp;&nbsp;}
}

void main() {
&nbsp;&nbsp;final s = process(const Duration(seconds: 1)).listen((val) { });
&nbsp;&nbsp;new Timer(const Duration(seconds: 5), () =&gt; s.cancel());
}

**Comment by mhausner** [comment]
Looking at this now. FWIW, dart2js fails this in a very different way. It never cancels the stream, and elements get generated at full speed, with no delay between 'ticks'.

**Comment by mhausner** [comment]
What seems to happen is not VM-specific. When the async* generator stream s is cancelled, the async library code ends up calling the generator recursively.

In more detail:

When the timer callback executes s.cancel(), the stream controller's cancel() invokes (through a microtask) the continuation in process(). It continues after the await, and executes the finally clause. The finally clause also implicitly cancels the stream iterator of the await-for loop. That cancel() call completes the future of the stream iterator. The completion of this future ends up *synchronously* invoking some callback code that invokes the async* generator again, recursively. (This synchronous callback happens via zone.runUnary() in _Future._propagateToListeners()).

The second execution of the finally clause observed in this bug is due to the recursive execution of the same continuation.

I am not sure yet how to fix this.

**Comment by fsc8000** [comment]
cc-ing @floitschG 

Interesting find. So this may be a async library issue?

**Comment by floitschG** [comment]
Only looked at the dart2js-version so far.
The "full-speed" is only on d8, since we have to simulate timers there. (D8 doesn't provide any means to delay events). In the browser the ticks get fired every 1s.
However, there was a bug in the code that made it ignore the cancel call.
I have a local patch which seems to work (need to write a test now, and get it reviewed).

At least with dart2js the output is not as expected:
```
counter = 1
counter = 2
counter = 3
counter = 4
stopping the async process
```

Will try to have a look at what happens inside the VM.

**Comment by floitschG** [comment]
I uploaded a patch for dart2js: https://codereview.chromium.org/1677063003

One important observation:
when looking at the 'events' (from the test) the Dart VM produces:
[main, listen, finally, cancel, finally]

That is, the `finally` is invoked, before the `cancel` of the `onCancel` of the source-stream.

I believe, what should happen:
- if the async*-function is waiting on an `await`, it is stuck there until the `await` returns. (also see #25703).
- this means, that the `cancel` future has to wait until the next event from the inner stream. (This can be seen in the second test).
- once the event arrives it should cancel the inner stream and wait for that cancel to succeed.
- Then, only, should it run the finally clauses.

/cc @lrhn @sigurdm

**Comment by mhausner** [comment]
The sequence of events in the VM is as follows. Assume
s = async* generator stream returned by process()
sc = _AsyncStarStreamController for s
fi = stream iterator for the await-for loop (iterating over the Stream.periodic() stream)
af = Future returned by fi.moveNext()

1. main
2. s.listen()
3. af completes 4 times with true (the loop iterations printing "counter = ...")
4. Timer completes, callback invokes s.cancel()
5. sc.onCancel() schedules the generator function
6. generator function resumes at await fi.moveNext()
7. await-for loop terminates
8. finally clause of implicit try-finally around the await-for loop calls fi.cancel(), which completes the Future returned by fi.moveNext()
10. The async library (in particular _Future._propagateToListeners()) completes runs the completion callback synchronously
12. The generator function resumes again (recursively) at await fi.moveNext()
13. fi.cancel() is invoked again, but is a no-op since the stream is cancelled already
15. The finally block in process() is executed (first time)
16. Recursive invocation of process() returns
17. The finally block in process() is executed (second time)
18. ....

So, cancel() on the stream iterator *is* called before the finally block.

If the async library didn't invoke the generator function recursively, the continuation invoked in step 6 would terminate and leave the generator in a state where it resumes at the end of the function (a no-op) instead of at the await fi.moveNext().

**Comment by lrhn** [comment]
The original example code has an `async*` function with no yield. Such a function is completely unaffected by calling cancel (except that a final error ends up in the cancel future instead of the stream).

**Comment by mhausner** [comment]
So, the expected outcome of the original example should be that the generator never terminates, because it doesn't yield?

**Comment by lrhn** [comment]
Yes. It has an infinite `await for` and nothing to stop it.

**Comment by floitschG** [comment]
I just looked through the spec, and agree with Lasse: `cancel` is only relevant at `yield` points.
Will update my CL.

**Comment by mhausner** [comment]
VM fix in CL https://codereview.chromium.org/1683763002/

The VM implements the correct behavior for the original example as of 4b6ef00d5996471274a1e685eb32c55419482cf7. It does not cancel the generator function, i.e. the program does not terminate, because the generator never yields a value.

If a yield statement is added to the generator loop, the generator terminates after 4 loop iterations and the finally clause is only executed once.

There is potentially still an issue in the async library because it can execute Future callbacks synchronously, which may lead to recursive invocations of the async code. I don't have an example to demonstrate this, unfortunately.

**Comment by mhausner** [comment]
VM Bug is fixed.
