### ISSUE TITLE
Analyzer should recognize "await new Future.error" as a throw variant

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23493]
This might also be a spec issue, I'm not sure.

As async/await gets more prevalent, the following pattern is coming up more frequently:

&nbsp;&nbsp;&nbsp;&nbsp;await new Future.error(error, stackTrace)

Outside of a catch clause, this is the only way to throw an error and keep its stack trace intact. This is a pretty common use-case in code that handles exceptions in a first-class way, such as testing code. Not recognizing it as a variant of &quot;throw&quot; means that we get spurious warnings about functions not always returning.

**Comment by lrhn** [comment]
This is not an analyzer issue. With null safety, flow analysis and reachability is part of the language.
The expression `throw Future.error(...)` is a normal expression with a static type of `dynamic`, because `Future.error(...)` is a constructor invocation on (inferred) `Future<dynamic>`.

The workaround for code like this is to do `await Future<Never>.error(...)`. That will now have type `Never` and be visibly non-terminating. 
We can't make the `Future.error` constructor statically return `Future<Never>` , because we don't have return types on constructors, not even factory constructors, so it's probably also the only solution.

(One alternative is to change `Future.error` from a constructor to a static method, but that will cause errors everywhere it's used with `new`).

Because a usable workaround now exists, we won't need to, and don't want to, be special-casing the `throw Future,error` construct in the semantics.
