### ISSUE TITLE
need native modInverse and powMod function for big integer

### ISSUE THREAD

**Issue by rinick** [dart-lang/sdk#23502]
**What steps will reproduce the problem?**

this is a dart file which I implemented modeInverse function with native dart big int
https://gist.github.com/rinick/9f1f285dc1e2a18d2d75

this is a java file that's doing the same thing, except it's using the builtin java modInverse function.
https://gist.github.com/samrg472/8f0bae6d291ef2bc2b95

**What is the expected output? What do you see instead?**

it takes 650ms to run the java on my pc, and about 8 seconds to run the dart version (11 seconds in checked mode)

To make dart's native big integer really usable for cryptography purpose, I think it's necessary to have these functions implemented in dartvm. not in dart code: 
modInverse, powMod, gcd.  it would also be nice if toByteArray and fromByteArray can be implemented too.

**Comment by crelier** [comment]
Rick,
Thanks for providing a bigint implementation of modInverse.
I am cleaning it up slightly and will add it to the Dart sdk. The gcd function, if considered useful, will follow later.
One question: how urgent is it for you guys to have a bigint implementation of modInverse supporting an even modulus?

Thanks,
Regis

**Comment by sethladd** [comment]
Thanks for the update, @crelier !

**Comment by rinick** [comment]
@crelier  we don't need even modInverse at the momenet, but the algorithm in my implementation is same as this one
https://gist.github.com/rinick/9f1f285dc1e2a18d2d75
it shouldn't be difficult to implement it.

**Comment by rinick** [comment]
after this change, native modInverse is about 8 times faster than the custom modeInverse implementation.
the same test now takes about 950-1000ms on same PC, 
https://gist.github.com/rinick/ce88242eb6e0a7c25063

**Comment by sethladd** [comment]
Thanks @crelier !

**Comment by sethladd** [comment]
Should we update the CHANGELOG for the SDK?

https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

cc @kevmoo

**Comment by crelier** [comment]
Only if these 4 cls are going to be cherry picked for 1.11 (decision is
with Ivan/Kasper/Rico):
https://codereview.chromium.org/1174513004/
https://codereview.chromium.org/1177873002/
https://codereview.chromium.org/1177063002/
https://codereview.chromium.org/1188843004/

Otherwise for 1.12, sure. The sdk change is this addition to class int:
  /**
   * Returns the modular multiplicative inverse of this integer
   * modulo [modulus].
   *
   * The [modulus] must be positive.
   * Throws a RangeError if no modular inverse exists.
   */
  int modInverse(int modulus);

By the time we ship 1.12, we should also have a gcd method.

Cheers,
Regis

**Comment by rinick** [comment]
right now we are not able to use 1.12,  since it doesn't support the dart2dart compiler. which means all the dart app deployed on our customer's site will have to be open sourced.

We really hope native modInverse feature can be part of 1.11

**Comment by crelier** [comment]
Ivan,

Please, see Rick's message below regarding the integration of modInverse
into 1.11.

Cheers,
Regis
