### ISSUE TITLE
Dart lacks a QueueBase and QueueMixin class in the dart:collection library

### ISSUE THREAD

**Issue by MichaelFenwick** [dart-lang/sdk#23603]
The dart:collection library has a FooBase and FooMixin class for Iterables, Lists, Sets, Maps, and even UnmodifiableMapViews. These classes offer excellent utility in allowing users to implement their own extending classes without having to override or forward anywhere from 20 to 40 methods, saving both hours of programming time as well as making the code significantly more readable. The Queue class, however, despite being a Collection, lacks the corresponding classes, which forces developers to choose between low effort and high readability versus better performance which only a Queue is needed rather than a List.

Both a QueueBase and QueueMixin class should be added to the dart:collection library so that Queues can be extended in a similar manner to all other Collections.

**Comment by zoechi** [comment]
This might be an alternative https://github.com/google/quiver-dart/blob/e63e0e061900c91e07bf06a79581b955523351b9/lib/src/collection/delegates/queue.dart

**Comment by lrhn** [comment]
TBH, I really dislike having almost identical Mixin/Base classes. One class should be enough. Sadly it can't be Queue itself because we put meaningful constructors on that.

Now, I don't actually see many methods on Queue (not inherited from iterable) that can be generalized. It's pretty much only `addAll`, `clear` and `toString` that can be defined without knowing the implementation of the queue.
All the {add,remove}{First,Last] methods are special, as are any operations that remove in the middle of the queue.

If you just want to delegate to a queue, the collection *package* has a delegating queue: http://www.dartdocs.org/documentation/collection/1.1.1/index.html#collection/dart:pkg-collection-wrappers.DelegatingQueue

**Comment by MichaelFenwick** [comment]
I can't say I'm really want both the Mixin and Base classes rather than just the Base class, other than it would make some sense to have both if only for consistency with the other implementation helper classes in the collections package. And while it is true that there isn't too much extra overriding you'd need to do if you went with something like 'class Foo extends Queue with IterableMixin` over `class Foo extends QueueBase`, it'd still be a rather nice (if minor) convenience and I don't suspect there would be many downsides to providing it.

**Comment by matanlurey** [comment]
`DelegatingQueue` is probably fine for most users.
