### ISSUE TITLE
Async: "await for" vs. "listen()" performance

### ISSUE THREAD

**Issue by deftomat** [dart-lang/sdk#23645]
If I subscribe to the streams events via `await for`, then handling the events is significantly slower than using a `listen()` method.

In the case of my [test code](https://dartpad.dartlang.org/aa5b0b65ec3cfb9b5245), I found that `await for` is 2x slower than `listen()`.

I don't know if this is a issue, but it is pretty annoying because `await for` is pretty cool feature.

**Comment by sethladd** [comment]
Just to be clear, did you mean in the VM or dart2js or both?

**Comment by deftomat** [comment]
Issue occurs in both cases.

**Comment by pulyaevskiy** [comment]
Not sure what's the status on this one but I was curious to run these tests myself and look at the numbers.

The original test code from @deftomat worked pretty much the same for me. But I also modified it to use `benchmark_harness` as it is recommended here: https://www.dartlang.org/articles/benchmarking/.

Here is modified version: https://dartpad.dartlang.org/48a9ed61272478edc881
It wouldn't work on Dartpad though, since it doesn't support pub packages.

The results are a bit confusing to me.
There is two benchmarks: `AwaitFor` and `Listen`. I ran each of these separately (the other one just commented out in `main()`).

Here is the numbers I got:

```
AwaitFor(RunTime): 16.702827197169466 us.
Listen(RunTime): 33.082386130656566 us.
```

So the picture is quite opposite to the original test. `AwaitFor` seems to be two times faster than `Listen`.

I ran those on Dart VM only though (1.12.1).
Also if I try to run both tests at the same time (both uncommented in `main()`) I get completely different numbers. And it also depends on the order of the tests too.

For instance, here is numbers when AwaitFor is run first:
```
AwaitFor(RunTime): 16.50255348976935 us.
Listen(RunTime): 80.67423832702362 us.
```

And here is for when Listen is first:
```
Listen(RunTime): 32.27464777418992 us.
AwaitFor(RunTime): 30.14119296371708 us.
```

I was wondering if anyone can shed some light on this and explain why results are so different?
It would be nice to understand why results are so different.

**Comment by pulyaevskiy** [comment]
Oh, looks like `benchmark_harness` doesn't work well with async stuff. I'll play a bit more with it to get something working...

**Comment by matanlurey** [comment]
FYI, AngularDart has requested a lint to remove all uses of `async`/`await` from our code-base:

https://github.com/dart-lang/linter/issues/1010

**Comment by zoechi** [comment]
Isn't that working as expected?
`await for` awaits for each handler call to complete (serial), while `listen` or `forEach` just fire away also for subsequent events when previous handler calls are not yet completed (kinda parallel).
