### ISSUE TITLE
Enhancement: collapse duplicate errors/warnings for the same location?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23659]
Hi,

Please see the errors/warnings output.

Consider this case:

![screen shot 2015-06-17 at 1 34 05 pm](https://cloud.githubusercontent.com/assets/5479/8205968/a5884d5c-14f5-11e5-8a0e-1d8e3fec1c92.png)

Is there a good way to give the developer a single piece of feedback, instead of one warning and two errors?

In this case, I maybe would expect to see something like "incomplete statement or expression"

**Comment by sethladd** [comment]
cc @lukechurch

**Comment by sethladd** [comment]
Here's another good example. Two of the same pieces of feedback, from the same line:

![screen shot 2015-06-17 at 3 37 54 pm](https://cloud.githubusercontent.com/assets/5479/8208243/e68bb9cc-1506-11e5-9fb7-f4c9778b50d6.png)

**Comment by bwilkerson** [comment]
> Is there a good way to give the developer a single piece of feedback, instead of one warning and two errors?

Yes. The warning should be easy to get rid of by noticing that the name of the getter is an empty string. The extra error is a little harder; it requires better recovery in the parser.

> Two of the same pieces of feedback, from the same line:

Those are actually pointing out two separate problems, so it isn't clear to me that we'd want to hide the second. Consider, for example, what you'd want to see if the second name was "MyUserTagSubclass" rather than "UserTag". Wouldn't you want to know that both types were undefined?

**Comment by sethladd** [comment]
> Wouldn't you want to know that both types were undefined?

If they were two types/classes, definitely want to know both are deprecated.

**Comment by srawlins** [comment]
I think this deduplication of errors is now good enough. I don't think we can remove the "Expected ';'" error or the "Expected identifier" error, as each is important; each is distinct, and fixing each fixes a distinct error. They each need to be fixed.
