### ISSUE TITLE
Uri.parse throws FormatException with urls that have brackets

### ISSUE THREAD

**Issue by harankumar** [dart-lang/sdk#23688]
According to the API docs, the `Uri.parse` method is supposed to percent escape any invalid characters if possible. While this does appear to work with the majority of invalid characters, it does not seem to work when brackets are included, instead throwing an exception. For example:
```Dart
print(Uri.parse("https://duckduckgo.com/?q=i+love+[brackets]"));
// FormatException: Invalid character (at character 34)
print(Uri.parse("https://duckduckgo.com/?q=i+love+%5Bbrackets%5D"));
// No Exception
```
Note that this issue occurs both with open and close brackets, both of which have established escape codes. For now, I can simply use the workaround of manually escaping the strings before calling the parse method. If this behavior is intentional, please let me know.

Thank you.

**Comment by lrhn** [comment]
The `Uri.parse` method does not escape invalid characters - it's a validating parser that only parses valid URIs, so an invalid character just makes it throw.
The comment saying that it tries to escape-encode is actually not true, so we should remove that. I think it has been there since the first primitive URI parser implementation.

**Comment by lrhn** [comment]
The documentation has been updated. It's still not allowed to put '[' into the URI unescaped.
