### ISSUE TITLE
dart2js: confusing noSuchMethod & Function.call when using mirrors

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23697]
The following example:

``` dart
@MirrorsUsed(targets: const ['A', 'B', 'C', 'dart.core.Function'], override: '*')
import 'dart:mirrors';

class A {
  int m(int a, int b) => 3;
}

class B implements A {
  Function f;
  noSuchMethod(i) => reflect(f).invoke(#call, i.positionalArguments).reflectee;
}

class C {
  String call(String paramC1, {String paramC2}) => paramC1;
}

main() {
  reflectClass(C).newInstance(const Symbol(''), []).reflectee;
  var mock = new B()..f = (_a,_b) => 4;
  mock.m(0, 3);
}
```

Produces this error:

```
NoSuchMethodError: method not found: 'call'
Receiver: Closure 'main_closure'
Arguments: [0, paramC2: 3]
NoSuchMethodError: method not found: 'call'
Receiver: Closure 'main_closure'
Arguments: [0, paramC2: 3]
    at dart.wrapException (http://localhost:8001/out.js:1499:17)
    at main_closure.dart.Object.noSuchMethod$1 (http://localhost:8001/out.js:5980:17)
    at main_closure.dart.Object.call$2$paramC2 (http://localhost:8001/out.js:6040:21)
    at CachedInvocation.dart.CachedInvocation.invokeOn$2 (http://localhost:8001/out.js:2322:32)
    at JsClosureMirror.dart.JsInstanceMirror._invoke$4 (http://localhost:8001/out.js:4153:39)
    at JsClosureMirror.dart.JsInstanceMirror.invoke$3 (http://localhost:8001/out.js:4065:21)
    at JsClosureMirror.dart.JsInstanceMirror.invoke$2 (http://localhost:8001/out.js:4068:21)
    at B.dart.B.noSuchMethod$1 (http://localhost:8001/out.js:3039:34)
    at B.dart.Object.list$2 (http://localhost:8001/out.js:6095:21)
    at dart.main (http://localhost:8001/out.js:3024:12)
```

The call of `mock.m` should be dispatched to invoke the closure set under `B.f`. For some reason, we are dispatching this to call `C.call`. If you comment out the `call` definition, the code works without a problem.

I still need to look further but maybe this is an issue with CachedInvocation? I need to look further, but @rakudrama, if you see anything obvious from this let me know.

For context: this is a small repro for a problem a user ran into when using angular, di, and mock packages. Class C and the newInstance call for C are derived from di/angular, the noSuchMethod definition in B was derived from how the mock package handles `when...thenCall`.

**Comment by floitschG** [comment]
Lots of red herrings in there. Here is a simplified example:

    @MirrorsUsed(targets: const ['A', 'B', 'C', 'dart.core.Function'], override: '*')
    import 'dart:mirrors';

    class A { foo(x) => 499; }
    class C { foo({x}) => 22;  }

    class B { noSuchMethod(i) => print(i.positionalArguments); }

    confuse(x) { return x; return x; }

    main() {
      confuse(new C());
      print(reflect(new A()).invoke(#foo, [3]));
    }

* No need to go through noSuchMethod. (Just need to have it in the program).
* No need to deal with closures. Same bug happens with normal functions.
* No need to reflect on C. Just instantiating is enough.

So what happened: dart2js stores a mapping from name to encoded name in the output. The bug is/was that it had the named and the unnamed function name mapping to the same encoded name. However, we use that same map to build the inverse map. And that one then only worked if we run through the names in the right order. (If they were in a different order, the named one would overwrite the "good" name). (see screenshots).

Bad case (where we overwrite the unnamed name). Look for "call$2" and "call$2$paramC2":
![bug_bad](https://cloud.githubusercontent.com/assets/8631949/8304869/0405674e-19aa-11e5-9079-bfaadcd013a2.png)

Good case (where we run through the names in the "right" order):
![bug_good](https://cloud.githubusercontent.com/assets/8631949/8304870/040fd4ea-19aa-11e5-907b-44b7821cf857.png)

There are several ways to fix this:

* split the named and unnamed mapping so that we don't run into this issue when we do the inverse mapping. This would basically require to split the `JS_EMBEDDED_GLOBAL('=Object', MANGLED_NAMES)`.
* filter the named-argument function names out. They are only used in one direction and we can ignore them for the inverse mapping.

The latter is more hackish but much easier:

    $ git diff master
    diff --git a/sdk/lib/_internal/compiler/js_lib/js_names.dart b/sdk/lib/_internal/compiler/js_lib/js_names.dart
    index 708b873..26b3656 100644
    --- a/sdk/lib/_internal/compiler/js_lib/js_names.dart
    +++ b/sdk/lib/_internal/compiler/js_lib/js_names.dart
    @@ -113,10 +113,14 @@ class _LazyReflectiveNamesMap {
        List keys = JS('List', 'Object.keys(#)', _jsMangledNames);
        for (String key in keys) {
          var reflectiveName = JS('var', '#[#]', _jsMangledNames, key);
    -      // Filter out all non-string values to protect against polution from
    -      // anciliary fields in [_jsMangledNames].
    -      bool filter = JS('bool', 'typeof # !== "string"', reflectiveName);
    -      if (filter) continue;
    +      // Filter out all non-string values to protect against pollution from
    +      // ancillary fields in [_jsMangledNames].
    +      if (JS('bool', 'typeof # !== "string"', reflectiveName)) continue;
    +      // Filter out named-argument function names. Unnamed names are shorter
    +      // and we just need to make sure not to overwrite one that already exists.
    +      var old = result[reflectiveName];
    +      if (old != null && old.length < key.length) continue;
    +
          result[reflectiveName] = JS('String', '#', key);
    
          String getterPrefix = JS_GET_NAME(JsGetName.GETTER_PREFIX);

**Comment by sigmundch** [comment]
Thanks Florian! Great to see this simplified further.

I'm not familiar enough with the uses of the inverse map - why is it OK to leave out the named-argument function from it? (we can also take this offline and discuss when we meet tomorrow)

**Comment by floitschG** [comment]
The inverse map is used to find the corresponding JS function when trying to do reflective operations. However, for more complicated calls (like with named arguments) we have a `call*` function that deals with them. Even if a call$2$arg function exists the reflective operation automatically goes through `call*`.

(Fwiw: I didn't know/remember this either, and discovered it when debugging).
You can see that in the js_helper.dart `applyFunctionWithNamedArguments` which refers to `JS_GET_NAME(JsGetName.CALL_CATCH_ALL)`.

Note that `_genericApplyFunctionWithPositionalArguments` refers to "call*" directly. Imho this is a mistake. It should go through the JS_GET_NAME as well.

**Comment by mit-mit** [comment]
@sigmundch is this likely to land in 1.14?

**Comment by sigmundch** [comment]
Thanks for checking. I believe it's unlikely - I removed the milestone
