### ISSUE TITLE
Specification is not clear enough for static method warning

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23739]
Dart specification (v3.0, June 2015) reads (10.7 Static methods):

"It is a static warning if a class C declares a static method named n and has a setter named n ="

It's not clear enough if static or instance setter is meant. Please change the statement to either "...and has a static setter named n =" or "and has an instance setter named n ="

**Comment by eernstg** [comment]
No milestone now: This clarification should possibly be performed, but this will not block Dart 2.

Note that the given text (which is still present in the current version of the language specification) may be considered precise: It is a static warning (Dart 2: error) _both_ when said setter is an instance setter, and when it is a static setter. For a static setter there is no difference between 'has' and 'declares' a member, so that's
```dart
class A {
  static void n() {}
  static void set n(value) {}
}
```
For instance setter it can be similar, but also:
```dart
class A {
  void set n(value) {}
}

class B extends A {
  static void n() {}
}
```
In any case, the analyzer fails to emit any diagnostics in this situation. This is reported in issue #32063.

**Comment by eernstg** [comment]
Closing: I still consider `a setter` to be a sufficiently precise way to say `a static setter or an instance setter`.
