### ISSUE TITLE
Typo in specification

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23778]
Dart spec  (3rd Edition, June 2015) 11.1 Superinterfaces

"An interface J is a superinterface of an interface I iff either J is a direct
superinterface of I or J is a superinterface of a direct superinterface of I."

Note "...iff..."

**Comment by eernstg** [comment]
Hmm .. if it is changed to "if" rather than "iff" then it would allow for
additional situations where J is a superinterface of I; are there any
missing cases?

On Thu, Jul 2, 2015 at 8:33 AM, sgrekhov <notifications@github.com> wrote:

> Dart spec (3rd Edition, June 2015) 11.1 Superinterfaces
>
> "An interface J is a superinterface of an interface I iff either J is a
> direct
> superinterface of I or J is a superinterface of a direct superinterface of
> I."
>
> Note "...iff..."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/23778>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by sgrekhov** [comment]
You are right, sorry. Closed
