### ISSUE TITLE
Specification issue in "11.1.1 Inheritance and Overriding"

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23783]
Dart specification (3rd Edition, June 2015) contains the following statement (see 11.1.1 Inheritance and Overriding)

"Furthermore, we define overrides(J, K) to be the set of members m such
that all of the following hold:
• J is the implicit interface of a class C.
• C declares a member m.
• m' has the same name as m.
• m' is accessible to K.
• A is a direct superinterface of J and either
– A declares a member m' or
– m' is a member of inherited(A, K).
Let I be the implicit interface of a class C declared in library L. I inherits all members of inherited(I, L) and I overrides m' if m' ∈ overrides(I, L).
All the static warnings pertaining to the overriding of instance members
given in section 10 above hold for overriding between interfaces as well.
It is a static warning if m is a method and m' is a getter, or if m is a getter and m' is a method."

Seems that there there is an issue.
The last statement here is "It is a static warning if m is a method and m' is a getter, or if m is a getter and m' is a method". How can it be?

According section 10, mentioned in the statement above, "It is a compile-time error if a class has both a getter and a method with the same name." How can be a static warning here then? Let m be a method and m' be a getter. According definition of overrides(J, K) "c declares member m" and "A declares a member m' or m' is a member of inherited(A, K).". That mean the following code

class A {
  int get m => 0;
}
class C extends A {
  int m() { // Compile-time error
    return 1;
  }
}

The only cases, when interface may contain both getter and method with the same name, that I can imagine, is an abstract class like this:

abstract class SI1 {
  int m();
}
abstract class SI2 {
  int get m;
}
abstract class I implements SI1, SI2 {
}

Or another case

class SI1 {
  int m() {
    return 1;
  }
}
class SI2 {
  int get m => 2;
}
abstract class C extends SI1 implements SI2 {
}

But this is not the case described in the statement "It is a static warning if m is a method and m' is a getter, or if m is a getter and m' is a method" because class C does not declare anything here. So the statement "It is a static warning if m is a method and m' is a getter, or if m is a getter and m' is a method" should be either rewritten or removed at all

**Comment by eernstg** [comment]
> "It is a static warning if m is a method and m' is a getter, or if m is a getter and m' is a method". How can it be?

This is about interfaces, i.e., `implements`. Dart allows for more flexibillity in that relation than it does for `extends`.  Trying out the following variant:

```dart
class A {
  int get m => 0;
}

class C implements A {
  int m() {
    return 1;
  }
}

main() {
  new C().m();
}
```

you'll get an error from dartanalyzer (I believe that is actually a bug, it should only be a warning), and the VM runs it without error.

On the other hand, the spec frequently states that getters and methods do no blend, e.g.: 'This implies that a getter can never override a method, and a method can never override a getter or field.' (commentary, Sect. 10.2, spec from June 15). One might wonder why this is not allowed; there might be an inherent conflict, but I think it is just considered to be to weird and error-prone.

Conversely, it is sometimes considered a feature to have this kind of flexibility (e.g., in CLOS where an accessor is just another method), and in particular it can be quite useful when an invocation like `x.foo(y)` is a tear-off invocation rather than a regular method call (so `x.foo` is a getter which computes and returns a function, and that's the one we call). But you can of course declare a getter and override it with another getter that returns a tear-off of a particular method m, hence effectively overriding the inherited getter with a method.

>  "It is a compile-time error if a class has both a getter and a method with the same name."

When a class "has" both members there is a real conflict, not just an unjustified promise about type conformance. We wouldn't know which one to call if we encounter `x.foo(y)` and the value of `x` has both a `foo` getter (potentially returning a closure) and a `foo` method.

> class I ..

I think this case is covered in 11.1.1 around here: 'However, if the above rules would cause multiple members m1 , . . . , mk with the same name n to be inherited (because identically named members existed in several superinterfaces) then at most one member is inherited. in several superinterfaces) then at most one member is inherited. If some but not all of the mi, 1 ≤ i ≤ k are getters none of the mi are inherited, and a static warning is issued.'

> class C ..

This is exactly the case where you will get the warning according to the multi-line excerpt you mentioned at first.

You may of course have spotted an inconsistency, but I think it's all there if you check again. ;-)

**Comment by sgrekhov** [comment]
After detailed investigation I believe that it's all there. Thank you. Closed
