### ISSUE TITLE
Support Class?.member in dart2js

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23795]
As of b11670f89924c1961be8f93d00848c7fa9887f99, `Class?.member` is interpreted the same as `Class.member`. Currently, dart2js treats it as `(Class)?.member`, which throws a `NoSuchMethodError` when accessing static methods.

**Comment by jrote1** [comment]
Should this be added as why would you ever need to call `Class?.member` on a static class as the left side will never be null. For reference C# does not allow this.

**Comment by nex3** [comment]
@jrote1 While it's not clear that there's a good use for `Class?.member`, it's going to do something one way or another, and this change ensures that it does what it looks like it'll do. Consistency has value even in edge cases like this.

**Comment by eernstg** [comment]
With the proposed approach to lightweight metaclasses (
https://github.com/dart-lang/dart_enhancement_proposals/issues/4),
`(MyClass)?.member` would refer to the corresponding static members via the
`Type` instance produced by evaluating `MyClass`. The status of that DEP is
currently "not right now", but otherwise it looks like a reasonably
consistent way to handle it.  "Blocked on metaclasses"? ;)

On Mon, Jul 27, 2015 at 7:35 PM, Natalie Weizenbaum <
notifications@github.com> wrote:

> @jrote1 <https://github.com/jrote1> While it's not clear that there's a
> good use for Class?.member, it's going to do something one way or
> another, and this change ensures that it does what it looks like it'll do.
> Consistency has value even in edge cases like this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/23795#issuecomment-125282135>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by nex3** [comment]
This is in the spec, and so unless that changes it needs to be implemented regardless of any other proposal. This isn't really the place to discuss whether it's a good idea; dart-lang/dart_enhancement_proposals#9 might be better.

**Comment by munificent** [comment]
That isn't the right bug either. :)

It *would* have been good to file issues on [the repo for null-aware operators](https://github.com/gbracha/nullAwareOperators). But the proposal has been accepted now, so discussion is closed. You can see where the DEP committee went over this [here](https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Meetings/2015-06-24%20DEP%20Committee%20Meeting.md#null-aware-operators).

@eernstg, you're right that this makes `(MyClass)?.member` do something different than `MyClass?.member`, which is consistent with how `(MyClass).member` and `MyClass.member` can do something different. If we ever get metaclasses, both of those cases will be resolved.
