### ISSUE TITLE
Neither _GrowableList nor ListBase implement List

### ISSUE THREAD

**Issue by bprosnitz** [dart-lang/sdk#23792]
As a consequence, the following print() calls give true and false respectively. This seems in conflict with the documentation of isSubtypeOf, which states that a call to isSubtypeOf returns the same result as the is operator. 

```
 print(<int>[1,2,3] is List); 
 print(mirrors.reflectClass(<int>[1,2,3].runtimeType).isSubtypeOf(_mclassList)); 
```

As a result, it is difficult to determine if something is a list by reflection.

**Comment by lrhn** [comment]
Both `_GrowableList` and `ListBase` do implement `List` - they inherit that from `ListMixin` which is mixed into `ListBase`. That still does not explain the problem here.

How do you declare `_mclassList`?

If I do `var cList = reflectType(List);` then `reflectClass(<int>[1,2,3].runtimeType).isSubtypeOf(cList)` is true.

If I use `reflectClass` instead of `reflectType`, then it indeed doesn't work, because that returns a mirror representing the generic `List<T>` (the class declaration, not the type you get when you pass a type parameter), and that is not a super-type of `_GrowableList<int>` - or at least it can't say so because it doesn't know what T is yet.

So, conclusion: Use `reflectType` when you want a type you can use with isSubtypeof, use `reflectClass` when you want to access the class declaration.
