### ISSUE TITLE
Race condition when setting up isolate addOnExitListener should be FIXED

### ISSUE THREAD

**Issue by larsbak** [dart-lang/sdk#23819]
If the spawnee terminates quickly the addOnExitListener will not have any effect.
This is completely broken. Please make sure OnExit listener will be executed despite the isolate has already terminated. Default behavior like this is really annoying.
//Lars

```
first.dart
=======
import "dart:isolate";

setup(port) async {
  await for (var msg in port) {
    print("Receiving in first: $msg");
  }
}

main() {
  ReceivePort port = new ReceivePort();
  setup(port);
  Isolate.spawnUri("./second.dart",[], port.sendPort).then((Isolate isolate) {
     RawReceivePort exit;
     exit = new RawReceivePort((_) {
        print("EXIT HANDLER");
        exit.close();
        port.close();
      });
      isolate.addOnExitListener(exit.sendPort);
  });
}

second.dart
=======
import "dart:isolate";

main(args, SendPort port) {
  port.send(42);
  port.send(1243);
}
```

**Comment by floitschG** [comment]
I'm reluctant to change this. We could potentially make this work for `addOnExitListener`, but it wouldn't for `addErrorListener`, or `setErrorsFatal`.

The correct way is to spawn the isolate in a paused state (see Isolate.spawn).

**Comment by sethladd** [comment]
This isn't the first time people have run into this. I'm aware of two others that brought this up.

So to help, we added some notes in the dartdocs: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:isolate.Isolate#id_spawn

**Comment by lrhn** [comment]
It's currently documented on `addOnExitListener`, but it is annoying that it can fail in this way.

The `package:isolate` class `IsolateRunner` creates an isolate and starts out listening for errors and exit. It's more convenient than the core Isolate, which is *very* low-level (the API is based on you sending ports and handling the responses yourself). 
One reason that it's not more elaborate is that it would necessarily be based on ports underneath anyway, and if we hide those ports, you will have hidden receive ports keeping your isolate alive.

If we had ports that didn't keep an isolate alive, we might be able to use those, but that could also be confusing.

I can probably add an "isAlive" on Isolate, which checks whether the control port's isolate is alive (or whether the port is open, which is the same thing). Then you could check first if the isolate is already dead, and only if not you send the onExit listener to it. That's still not safe enough - you get a race condition between checking it the isolate is alive and it receiving your message - delivery can take arbitrarily long and the isolate could die in-between.
The way things are structured, even delivering the message isn't enough if the isolate terminates after receiving the control message but before returning to the event queue. 

So, the design is basically incredibly fragile because there is no guarantees on events being delivered and on delivered events being processed. The only way to be sure is to send the onExit listener, and follow up with a ping event. If you receive a response from the ping, then you are sure the onExit listener was added. Until then, maybe just check if the isolate is alive occasionally. At least the only problem then is a spinning isolate that never returns to the event loop.

I'll try adding the `isAlive` check. I think it's the best we can do without building full two-way communication channel (TCP on top of send-ports).

**Comment by lrhn** [comment]
You can use the `Isolate.spawn` parameter `onExit` to set an exit message port when creating the isolate.
