### ISSUE TITLE
Dart analyzer: excessive warning about wrongly inherited interface method

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23838]
Steps to reproduce.

1) Create dart file with the following code

``` dart
class A {}
class B extends A {}
class C {}
class D extends C {}

abstract class SI1 {
  void foo(A v1, D v2, [int v3]);
}

abstract class SI2 {
  int foo(B v1, [C v2]);
}

abstract class SI3 {
  int foo(B v1, int v2, bool v3, [C v4]);
}

abstract class I implements SI1, SI2, SI3 {}

main() {
  I i = null;
  // We expect that I inherits var foo(var v1, [var v2, var v3, var v4]), so no static warning
  try {
    i.foo(null);
  } on NoSuchMethodError catch(ok) {}
}
```

2) Run it in dartanalyzer

Actual result. 2 warnings
[warning] 'foo' is inherited by at least two interfaces inconsistently, from (A, D, [int]) → void, (B, [C]) → int
[warning] 2 required argument(s) expected, but 1 found

Expected result. According Dart specification (Edition 3, June 2015) 11.1.1 Inheritance and Overriding "Otherwise, if the static types T 1 , . . . , T k of the members m 1 , . . . , m k are not
identical, then there must be a member m x such that T x <: T i , 1 ≤ x ≤ k for
all i ∈ 1..k, or a static type warning occurs. The member that is inherited is
m x , if it exists; otherwise: let numberOf P ositionals(f ) denote the number of
positional parameters of a function f , and let numberOf RequiredP arams(f )
denote the number of required parameters of a function f . Furthermore, let s
denote the set of all named parameters of the m 1 , . . . , m k . Then let
h = max(numberOf P ositionals(m i )),
r = min(numberOf RequiredP arams(m i )), i ∈ 1..k.
Then I has a method named n, with r required parameters of type dy-
namic, h positional parameters of type dynamic, named parameters s of type
dynamic and return type dynamic."

So, in the example above interface I should inherit method var foo(var v1, [var v2, var v3, var v4]) and no static warnings should occur.

Tested at dartanalyzer version 1.11.0-edge.45833
Note. In dart this code works without issues

**Comment by srawlins** [comment]
Analyzer still produces a static warning.

**Comment by eernstg** [comment]
I think this issue can be closed: The current rules require that every class (abstract or concrete) has a well-defined member signature for every member, and this is achieved by having a most specific member signature for each member name `m` among the member signatures of the direct superinterfaces whose type is a subtype of them all.

So, luckily, we don't even try to resolve this kind of ambiguity/conflict any more. ;-)

The requirement is not satisfied for the class `I` and the member name `foo`: The direct superinterfaces have member signatures `void foo(A, D, [int])`, `int foo(B, [C])`, and `int foo(B, int, bool, [C v4])`, and none of these have a function type which is a subtype of them all.

We _can_ declare an abstract member `int foo(A v1, [Object v2, Object v3, C v4])` in `I` in order to resolve this conflict, the problem is not that there is no solution. But we decided that the tools (analyzer, compiler) should not be required (nor even allowed) to create solutions like this, they should be chosen explicitly by developers.

Check out https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#combined-member-signatures for the null-safety update and https://github.com/dart-lang/language/blob/dcd7ca2e75e141106c8c361bbd869088fc840e02/specification/dartLangSpec.tex#L5069 for the detailed rules that the null safety update is updating.
