### ISSUE TITLE
dart:io accessible in content_shell/Dartium?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23940]
This simple program:
```html
<script type="application/dart">
import 'package:http/http.dart' as http;
main() => http.get(null);
</script>
```

fails in content_shell with this bizarre error message:
```
> path/to/dart/repo/client/tests/drt/content_shell --dump-render-tree repro.html
... 
CONSOLE ERROR: Internal error: 'dart:io-patch/platform_patch.dart': error: line 19: native function 'Platform_GetVersion' (0 arguments) cannot be found
  static String _version() native "Platform_GetVersion";
```

What's strange is that content_shell shouldn't be loading the dart:io library in the first place (thank's @iposva-google for pointing this out). Is content_shell built incorrectly?

I am not sure if Dartium has the same issue, but it's possible.

/cc @alan-knight @terrylucas

**Comment by munificent** [comment]
My guess is that this is because the http packages [accesses "dart:io" through mirrors](https://github.com/dart-lang/http/blob/master/lib/src/io.dart#L52) instead of importing it normally.

**Comment by alan-knight** [comment]
I think this is just a poor error message for 

    This program uses dart:io, it won't run here.

If I compile it with dart2js I get 

```
Uncaught Unsupported operation: IOClient isn't supported on this platform.
dart.wrapException @ js_helper.dart:1476
dart.assertSupported @ io.dart:33
dart.get @ client.dart:34
dart.main @ main.dart:22
dart._IsolateContext.eval$1 @ isolate_helper.dart:460
dart.startRootIsolate @ isolate_helper.dart:122
(anonymous function) @ io.dart:23
(anonymous function) @ io.dart:23
init.currentScript @ io.dart:23
(anonymous function) @ io.dart:23
(anonymous function) @ io.dart:23
```

**Comment by alan-knight** [comment]
From the README for http.

"Currently the global utility functions are unsupported on the browser; see "Using on the Browser" below."

**Comment by sigmundch** [comment]
Is there a way to make this a better error message though?

If you explicitly import dart:io you get an error that makes more sense. Not sure if that's a vm diagnostics issue though, rather than a dartium/content_shell problem.

Part of the problem also seems to be that content_shell has the .dart portion and not the .cc portion of the code, otherwise, how did it know that Platform_getVersion is the native name for Platform.version? Should that .dart code be excluded from the snapshot that is preloaded there?

**Comment by alan-knight** [comment]
Maybe? Presumably http is doing its tricks with mirrors in order to avoid the checking that would prohibit loading this on the browser. It could probably check itself and throw an exception in those methods. That would be less general, but I suspect might happen considerably faster than trying to change Dartium.

**Comment by nex3** [comment]
I believe this is a legit bug in content shell. The http package is written to [produce nice error messages](https://github.com/dart-lang/http/blob/master/lib/src/io.dart#L32-L35) when the top-level methods are used without `dart:io` being available; the issue is that content shell isn't producing an error for `currentMirrorSystem().findLibrary(const Symbol('dart.io'))`. Accessing `dart:io`, even through mirrors, should be disabled on content shell and *certainly* should never produce this "Internal error".

**Comment by rmacnak-google** [comment]
dart:io should not be loaded into a regular isolate in Dartium at all

**Comment by johnmccutchan** [comment]
@rmacnak-google has put in a hack so that you cannot access it via mirrors. dart:io is not importable either.
