### ISSUE TITLE
provide dartdoc documentation for all dart keywords

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#23944]
tagging @sethladd @lukechurch @kwalrath @Sfshaza 

I think I already talked about this with lukechurch at some point. But I would really love to see dartdoc information for all dart keywords. I mean things like async, await, for, if, void, null etc.

One of the things I love about dart, is being able to explore libraries by pressing F1 in webstorm, or just clicking on it in dartpad (or now also at dartlang.org with embedded dartpads, awesome :D)

But why not also let users learn the fundamentals of dart in this same manner ? For example, I was exploring some code that uses `await for`, and I haven't used that keyword before. So just by automatism, if I don't understand some code, I press F1 in webstorm, to see if there is more information.

Of course, in this case, I won't get any extra information, but I think I should. Maybe just some brieve description. Possible linking to this excellent article: https://www.dartlang.org/docs/tutorials/streams/ ?

What do you guys/girls think of that ?

**Comment by sethladd** [comment]
Our [Language Tour](https://www.dartlang.org/docs/dart-up-and-running/ch02.html) should have ample documentation for our language features. If it's missing an explanation of language features/keywords, we could use a patch to the docs or please file a bug. :)

If you're looking for more real-time language docs, may I suggest a feature request for Dart Pad? That's an excellent place for beginners to explore Dart.

I'm going to respectfully close this issue here on the SDK, but I encourage you to explore this idea with Dart Pad (and open issues on our Language Tour if it's missing something). Thanks!

**Comment by kasperpeulen** [comment]
@sethladd I was thinking more solving this issue at the level of the analyzer. Because DartPad gets this information in the end from the analyzer. The analyzer provides dartdoc information for dart classes/methods/properties etc, but not for keywords.

The adventage of this would be that not only dartpad would benefit from this, but also other editors like WebStorm, Sublime, atom etc.

**Comment by sethladd** [comment]
> I was thinking about solving this issue at the level of the analyzer.

I believe the analyzer team is working on a plugin infrastructure. This might be a great plugin.

**Comment by kasperpeulen** [comment]
@sethladd oh analyzer plugins sounds awesome :)

but couldn't this be easily added to analyser itself, why would you do this in a plugin ?

I thought about something like this:
![image](https://cloud.githubusercontent.com/assets/1035299/9047784/77768352-3a34-11e5-9454-6f97104f5f40.png)

![image](https://cloud.githubusercontent.com/assets/1035299/9047791/8790fe5c-3a34-11e5-94db-43f3f357fac3.png)
