### ISSUE TITLE
dart:core.List.sort() documentation doesn't say if it is a stable sort and is confusing

### ISSUE THREAD

**Issue by jamesr** [dart-lang/sdk#23976]
The dart:core.List.sort() documentation doesn't say whether the sort is stable and the way it describes the requirements for its arguments is misleading.

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.List#id_sort currently reads:

> void sort([Function int compare(E a, E b)])
> 
> Sorts this list according to the order specified by the compare function.
> 
> The compare function must act as a Comparator.
> 
> List<String> numbers = ['one', 'two', 'three', 'four'];
> // Sort from shortest to longest.
> numbers.sort((x, y) => x.length.compareTo(y.length));
> numbers.join(', '); // 'one, two, four, three'

The link to Comparator says (https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.Comparator):

> Comparator
> typedef int Comparator (T a, T b)
> The signature of a generic comparison function.
> 
> A comparison function represents an ordering on a type of objects. A total ordering on a type means > that for two values, either they are equal or one is greater than the other (and the latter must then be smaller than the former).
> 
> A Comparator function represents such a total ordering by returning
> 
> * a negative integer if a is smaller than b,
> * zero if a is equal to b, and
> * a positive integer if a is greater than b.

I found this confusing.  The Comparator in the example (x.length.compareTo(y.length)) does not define a total order of strings - it defines a strict weak ordering of strings based on a total ordering of their length.  I.e. 'one' and 'two' are not equal strings, but they do have equal length.

I think what dart:core.Lang.sort() intends to say is that it implements an unstable sort and requires compare to be a strict weak ordering of the values.

**Comment by sethladd** [comment]
cc @lrhn

**Comment by lrhn** [comment]
The sort is indeed not guaranteed to be stable (so the example isn't very good since it has two equal elements). It happens to be stable for small lists because we use quicksort with a fallback to insertion-sort for small lists.

The wording could use some tweaking. It might be as little as "zero if a is considered equal to b, and".

It's a matter of perspective whether a comparator defines a weak ordering or a total ordering. From a mathematical point of view, it would probably be considered a strict weak ordering.
Computationally we confuse things by having more than one kind of equality. The mathematical notion of equality should probably be matched by identity, and if we do that, the ordering is not total. It's only total modulo the equivalence introduced by the comparator.

It's probably a good idea to document that non-identical values can be considered equal by the comparator.

**Comment by jamesr** [comment]
C++ documents this requirement as a strict weak ordering: http://en.cppreference.com/w/cpp/concept/Compare
