### ISSUE TITLE
performance issue with generators / sync* ?

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#24032]
With the DartVM 1.11.1 I face a performance issue with `Iterable#first`.

The following code generate a infinite Iterable of prime number:

```dart
/// generate an Iterable of natural number starting from [n]
Iterable<int> from(int n) sync* {
  yield n;
  yield* from(n + 1);
}

/// filter the [source] to skip the multiple of first element (that is a prime number)
Iterable<int> sieve(Iterable<int> source) sync* {
  final prime = source.first;
  yield prime;
  yield* sieve(source.skip(1).where((e) => e % prime != 0));
}

Iterable<int> get primes => sieve(from(2));

main() {
  final sw = new Stopwatch()..start();
  // display (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61)
  print(primes.take(18));
  print(sw.elapsed);
}
```

`sieve` uses a local variable `prime` to make `source.first` only once. If I don't use this local variable the performance are really bad and this huge difference looks like a bug.

```dart 
Iterable<int> sieve(Iterable<int> source) sync* {
  yield source.first;
  yield* sieve(source.skip(1).where((e) => e % source.first != 0));
}
```

With the `prime` local variable the above code runs in `0:00:00.007978`. Without it runs in `0:00:08.135233`. (For the 20 first primes it takes `>1min.` instead of `12ms` with local)

**Comment by gbracha** [comment]
So caching makes a huge difference in an algorithm like this. In a pure functional language, one can always cache, so the implementation will typically do it for you. In an imperative language, it isn't generally safe to cache the results, because the sync* function could depend on something stateful. Dart doesn't try and detect whether a sync* function is pure (it's not that easy without a global analysis). The docs for Iterable state:

Some iterables compute their elements dynamically every time they are iterated, like the one returned by Iterable-generate or the iterable returned by a sync* generator function. 

So this behavior is what you should expect.

**Comment by a14n** [comment]
I agree with you. However I really think there is an issue with the current implementation behind `sync*`/`yield`.

If you simply replace the `from` function to return a list the computation becomes quicker although there are more elements generated compared to the original `from` with `sync*` :

```
Iterable<int> from(int n) => new List.generate(100, (i) => n + i);
```

The same result is output 8 times faster!
