### ISSUE TITLE
question: is adding tests for the generator tools a good idea?

### ISSUE THREAD

**Issue by guillermooo** [dart-lang/sdk#24036]
Not sure if I'll spend time on this, but I might if I need to tweak the existing tools further so that the generator for Python can share more code with existing generators for other languages.

In any case, before I start, I would like to know if it's a good use of my time, i. e., whether the current approach will be continued for the foreseeable future. In the pub README for the analyzer, it is mentioned that the current state of the analyzer is very unstable. I kind of understand that the analysis server is separate from it and that the generators work from a hopefully more stable spec, but nevertheless, any insight about all this would be very much appreciated.

Also, if we end up adding tests, how should we go about it? The current generator tools are a bunch of loose files in a random folder. Should a package be made out of them? Can we start with a few more loose files added to the `../tool/spec` folder and worry about structure later?

@bwilkerson

**Comment by bwilkerson** [comment]
> I would like to know ... whether the current approach will be continued for the foreseeable future.

I don't have a crystal ball :-), but I like having a structured specification that the generator can use to generate code that matches the spec. So, yes, I expect we'll keep it for a long time.

> Also, if we end up adding tests, how should we go about it?

Good question. We don't currently have tools that check the generator, probably because the code that gets generated gets checked by the server tests. If the generator breaks we'll catch it when we integrate the newly generated code. I'm not sure how useful tests for the generator would be.

> Should a package be made out of them?

We considered doing that, but for the analysis server code it's very convenient to have the generated code be generated in place. It saves us a copy step. Of course, that's not a very strong argument...

> Can we start with a few more loose files added to the ../tool/spec folder and worry about structure later?

I think that would be fine, maybe in `test/tools/spec`.

**Comment by guillermooo** [comment]
I suppose tests could be useful for developers if they used a test-first approach at least for the trickiest parts, and perhaps other generated files that Google presumably won't check  could benefit too, i. e., the Python 'bindings'. The Python bindings are not checked by the Sublime Text plugin either, so a little bit of testing could be helpful to catch early some classes of errors.
