### ISSUE TITLE
Cancel in async* is delayed

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24059]
The VM and dart2js both delay the cancellation of async* functions. (Both use `scheduleMicrotask`.)

This is different from a stream-controller which runs cancel-code immediately:

    import 'dart:async';

    get asyncStarStream async* {
      try {
        await new Completer().future;
      } finally {
        print("async* canceled");
      }
    }

    Future testStream(stream) {
      var sub = stream.listen(print);
      return new Future(() {
        print("canceling - ");
        sub.cancel();
        print("canceled * ");
      });
    }

    main() {
      testStream(new StreamController(
            onListen: () { },
            onCancel: () { print("controller canceled"); })
          .stream);
      testStream(asyncStarStream);
    }

prints:

    canceling - 
    controller canceled
    canceled * 
    canceling - 
    canceled * 
    async* canceled

Should we change the behavior and make cancel immediate? From what I can see it consists of simply removing the `scheduleMicrotask` in both implementations. Here is a proposed patch (I ran it through some tests and didn't see any problems): https://gist.github.com/floitschG/7ab51c27908d61065490

/cc @lrhn @mhausner @gbracha

**Comment by lrhn** [comment]
I don't think it's a good idea.
The stream controller's onCancel callback is run immediately, but it might be async and return a future, so we can't say that the actual cancel code is run immediately. In the case of an `async*` function, the actual cancel code is indeed asynchronous (it may contain `await` expressions or any other feature), so starting it one microtask earlier is not worth it maybe being run interleaved with other code.

```dart
var a = 0;
foo() async* {
  try {
    for (int i = 0; i < 10; i++) yield a = i;
  } finally {
    a = -1;
  }
}

main() {
  var stream = foo();
  var sub;
  sub = foo().listen((i) {
     print("$i = $a");
     if (i == 3) sub.cancel();
     print("$i = $a");
  });
}
```
The problem is that calling cancel may now have side-effects. It's not so surprising to the one calling cancel, but it's surprising to the person writing the `async*` function that they have to worry about it - all other parts of the async function are run as individual async events, not interleaved with other direct-style code.
