### ISSUE TITLE
Completion should also replace remainder of identifier

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#24060]
Put the following in a Dart file:

class ClassElement {}
class ClassMemberElement {}
f(ClassElement e) {
}

and place the cursor between "Class" and "Element" in the type of the parameter 'e'. Request code completion and select "ClassMemberElement". It would be nice if the whole identifier were replaced rather than just the portion to the left of the cursor.

**Comment by danrubel** [comment]
This is more of a client decision, not server decision. IntelliJ already does this if you press Tab to select a completion rather than Enter. Currently the API provides [replacementOffset and replacementLength](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#notification_completion.results) to support the current behavior. We could augment this by adding replacementFullLength or replacementIdentifierLength (or a better name) that would be the full length of the identifier being replaced. The client would then have the information to choose which behavior to support.

**Comment by danrubel** [comment]
This is a client decision. In IntelliJ you can replace the remaining characters in the identifier by selecting the completion and pressing Tab.
