### ISSUE TITLE
SplayTree constructor from pre-sorted list

### ISSUE THREAD

**Issue by llamadonica** [dart-lang/sdk#24072]
Currently the SplayTree[Set/Map] has a fromIterable that adds each element to an empty tree. On pre-sorted lists, this seems to be a little less than ideal in terms of the algorithm(O(n*log n) vs. O(n)?), but intuitively, it seems like the resulting tree might be heavily skewed because of the nature of SplayTrees. It seems like SplayTree[Set/Map].fromPresortedIterable would be useful in either case...

**Comment by lrhn** [comment]
The splay tree would be heavily skewed for a sorted list. That's ok - a splay tree expected to even out when you use it, not to be balanced all the time like, for example, an AVG tree or Red/Black tree.

It could still be useful to have a `fromSorted` constructor that assumes elements are sorted, so it can build the structure incrementally (and throw if they turn out to not be sorted anyway).

**Comment by lrhn** [comment]
The way we currently do things, we would probably *test* that the list was sorted, and throw if it wasn't.
That requires a linear number of element comparisons, but that's also what the current constructor does since each `_splay` operation will find a tree already splayed on the largest element and skip out after one comparison.

As such, a `fromSorted` constructor won't actually be a significant improvement in constructor performance, and the current constructor works both for sorted and reverse-sorted inputs.

We could build a more balanced tree initially, if we know that the are were already sorted. That's something we can do *anyway* in the current constructor, by adding some reshufflings along the way if we think we are building too deep a tree.

So, no current plans to add an extra constructor.
