### ISSUE TITLE
dart2js crashes on compiling standalone/io/observatory_test after 06ab2bdbdda2ad1696a842ea44d8fd0d38106f7f

### ISSUE THREAD

**Issue by ricowind** [dart-lang/sdk#24291]
See failure here:
http://build.chromium.org/p/client.dart/builders/dart2js-linux-release-checked-5-5-be/builds/10965/steps/dart2js-d8%20tests%20--checked%20--dart2js-batch%20failures/logs/stdio

I don't see how my change should cause that (except that dart2js will be analyzing other code than before.

@sigmundch @floitschG

**Comment by sigmundch** [comment]
Interesting - not sure what's the cause yet.

It looks like this made `debugger()` reachable.

When we are looking at the annotations of that function (see developer_patch.dart):

```
@patch
@ForceInline
bool debugger({bool when: true, String message}) {
...
}
```

We end up seeing the metadata as:
```
 MetadataAnnotation(patch, 2), MetadataAnnotation(null, 0)
```

First I thought that the second annotation was null because `ForceInline` is malformed (it's import was missing), but adding the import for it didn't fix the crash though.

**Comment by sigmundch** [comment]
the `0` though indicates that the second annotation has not been resolved, which is surprising because resolution should have covered it by the time the inferrer starts running.

/cc @johnniwinther - don't we resolve all annotations for reachable functions during resolution?

**Comment by sigmundch** [comment]
(FWIW - this seems to have changed recently, compiling with dart2js 1.13.0-dev.1.0 seems to work fine on this code.)

**Comment by sigmundch** [comment]
Aha! - the issue is related to patch files, we seem to resolve metadata for the public interface, but not for the patch implementation.

@johnniwinther - This seems like something that might have changed recently while refactoring the resolver code. Could you take a closer look? 

We should also fix the patch file to include the import, but we might as well do both changes together.
