### ISSUE TITLE
Specification: there's no Enum in a compile-time constants list

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24292]
Specification "16.1 Constants" contains list of constant expressions There are no Enum in the list (specification 3 rd Edition / June 2015) but according Enum definition (13 Enums) it is a compile time constant.

**Comment by lrhn** [comment]
Enums are normal objects created using the `enum` syntax. An enum like `enum Foo {foo, bar;}` is defined as being (roughly) equivalent to 
```
class Foo { 
  static const Foo foo = ...;
  static const Foo bar = ...; 
  ...
}
```
As such, `Foo.foo` and `Foo.bar` are compile time constants the same way any other static const declaration is - it doesn't need special mentioning in the compile-time constant list because it's covered by the case "An identifier expression that denotes a constant variable.".

**Comment by eernstg** [comment]
Closing: I do not see the need to take any action here.
