### ISSUE TITLE
polymer 1.0 does not work in dartium browser. 

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/sdk#24308]
I'm working on a project which uses polymer 1.0 JS library and dart. In dartium browser, the polymer lib does work at all.

To reproduce the issue. Simple go to https://elements.polymer-project.org/. Although all the files are loaded, the page is blank.

Not sure if this is the right place to report the issue.

**Comment by sigmundch** [comment]
/cc @jakemac53 -- probably the best place to report this would be in the [polymer-dart](http://github.com/dart-lang/polymer-dart) repo

However in this case it might be already fixed. What specific Polymer.js version are you using? (1.1.2?)

I believe this issue was because Dartium is still based on Chrome 39, and polymer introduced a change in polymer 1.1.2 that broke Chrome 39 compatibility. 

We had similar reports last week and the polymer team was able to make a small change to keep Chrome 39 working. The patch landed here https://github.com/Polymer/polymer/commit/a6694b7f7a6d06149fbcb06d63af99a9e56c6375, which I believe made it into polymer 1.1.3.

I'll mark this issue as closed assuming that was the issue, but let us know if that was not the case.
