### ISSUE TITLE
Is Platform::ResolveExecutablePath really needed? Not cross platform.

### ISSUE THREAD

**Issue by mulander** [dart-lang/sdk#24302]
The way Platform::ResolveExecutablePath is not cross platform and currently not possible to implement in a reliable way on OpenBSD.

This seems to be used to obtain the Dart SDK root:
 - https://github.com/dart-lang/sdk/issues/16994
 - https://github.com/mulander/sdk/commit/c05c8c66069db91cc2fd48691dfc406c818d411d

OpenBSD Developers state that they have no safe way to obtain that info:
 - https://twitter.com/canadianbryan/status/640581498626699264
 - https://twitter.com/canadianbryan/status/640583550840926208

If the code is only used to obtain the SDK path then I think it should be part of installation configuration not part of the runtime.

This issue is related to the porting efforts of getting Dart running on OpenBSD: https://github.com/dart-lang/sdk/issues/10260

**Comment by iposva-google** [comment]
Thanks for raising this concern about OpenBSD.

If OpenBSD really does not allow you to figure out the path a binary has been launched from, then you might need to prescribe the one and only location where the Dart SDK has to be installed for OpenBSD. Since this obviously prevents the side-by-side installation of multiple Dart SDKs on a single machine, we will not hard-code the path in general.

Ideally you will allow this to be overridden on the command line or through an environment variable. I am closing this report as I do not see any action to be taken by the Dart SDK here.
