### ISSUE TITLE
Uri.resolve generate wrong file path

### ISSUE THREAD

**Issue by rinick** [dart-lang/sdk#24304]
this works
```
File f = new File.fromUri(new Uri.file('filder/%2F.txt'));
```

but this has an error 
```
Uri folderUri = new Uri.file('folder');
File f = new File.fromUri(folderUri.resolve('%2F.txt'));
```
file name becomes `/.txt` thus caused a Illegal character error

**Comment by lrhn** [comment]
This is working as intended.

The difference is that `new Uri.file('filder/%2f.txt")` escapes the `%` resulting in `file:///filder/%252F.txt`. Its input is a "file path", and it is escaped when it's converted to a URI path.

The `new Uri.file('folder')` resolves to the URI `file:///folder`. (Note the lack of a trailing slash - this is referencing a *file*, not a *directory*.)

When you do `folderUri.resolve('%2F.txt')`, it first does `Uri.parse('%2F.txt')` to get the URI reference `%2F.txt` (all path, no scheme, and containing the original escape - the input is assumed to be a URI in textual form so percent escapes are retained). 
Then it resolves that against `file:///folder` which becomes `file:///%2F.txt`. Doing `File.fromUri` on that converts the percent-escapes to characters and then uses the path as a file path (with OS-appropriate directory separators). Since `%2F` becomes `/`, and `/` is not valid inside a path segment in a file path, it is rejected with an error.
The first example becomes `filder/%2F.txt` because the percent-escape `%25` is converted to `%`, but the `2F` is not.

If you change `folderUri.resolve('%2F.txt')` to `folderUri.resolveUri(new Uri.file("%2F.txt"))`, then it should work as expected. 

Converting between file paths and URI paths should be done using `Uri.file` (or `Uri.directory`) and `File.fromUri`. Putting a file path into function expecting a textual URI will only work in simple cases.

That said, we should probably document this more.

**Comment by rinick** [comment]
thank you for the explanation,  `folderUri.resolveUri(new Uri.file("%2F.txt"))` fixes my issue

maybe there should be a `resolveFile` method,  it feels awkward to generate a new Uri for every file name just because  resolve will unescape it

**Comment by lrhn** [comment]
If you are working with file names, you should just be using the path library and not worry about URIs. 
When creating a file: URI, it's usually better to keep working with paths until you are done, and then create the URI once.
URIs are actually pretty complex and unless you need the generality of multiple schemes, using them for files is usually overkill.
