### ISSUE TITLE
Inconsistance in created Invocation object

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24331]
According Dart specification 16.18.1 Getter Access and Method Extraction if getter lookup failed then
"If the getter lookup has failed, then a new instance im of the predefined
class Invocation is created, such that :
• im.isGetter evaluates to true.
• im.memberName evaluates to the symbol m.
• im.positionalArguments evaluates to the value of const [].
• im.namedArguments evaluates to the value of const {}.
Then the method noSuchMethod() is looked up in o and invoked with argument
im, and the result of this invocation is the result of evaluating i."

Take a look at the following code

``` dart
class C {
  void noSuchMethod(Invocation i) {
    print(identical(const[], i.positionalArguments));  // prints true
    print(identical(const{}, i.namedArguments)); // prints false
  }
}

main() {
  C o = new C();
  o.someGetter;
}
```

Why empty constant list of positional arguments equals to const[] but empty map of named arguments is not equal to const{}? According the spec behavior should be the same.

Dart VM version: 1.12.0-dev.5.10 (Tue Aug 25 04:09:15 2015) on "linux_x64"

**Comment by rmacnak-google** [comment]
VM in 5ee2da4475e17afd2459716dc86168884a45327a

**Comment by rmacnak-google** [comment]
Opened #24389 for dart2js

**Comment by rakudrama** [comment]
@leafpetersen @gbracha 

The spec says i.namedArguments is `const {}` for getter invocations.

The library function `Function.apply` is declared taking `Map<Symbol, dynamic>`
https://api.dartlang.org/1.12.1/dart-core/Function/apply.html

In the slightly stronger type checking of DDC, the following change the above program is no longer valid. It is guaranteed to fail at runtime passing the Map<dynamic,dynamic>  to the more constrained Map<Symbol,dynamic>.

```dart
void noSuchMethod(Invocation i) {
  Function.apply(print, [i], i.namedArguments);
}
```

Rather than change the implementations (VM, dart2js) to match the spec in a way that is incompatible with DDC, we should _consider_ changing the spec to be compatible with DDC.

The spec could be changed by replacing `const {}` with `const <Symbol, dynamic>{}`,
or to actually specify Function.apply (it is mentioned just once) and ensuring that the third argument is compatible with Invocation.namedArguments.

**Comment by hterkelsen** [comment]
Any word on this? I think that the first suggestion (specifying that `i.namedArguments` is `const <Symbol, dynamic>{}` for getters) is a good idea if we want to make the core types more strong-mode compliant

**Comment by leafpetersen** [comment]
This seems like a good thing to me.  I don't see any real downside to making these be typed. @gbracha , any thoughts on changing the spec to make it so?

**Comment by lrhn** [comment]
Fixed
