### ISSUE TITLE
Dart filter blur doesn't work with Webkit (Safari, Chrome...)

### ISSUE THREAD

**Issue by Pascal6yk1** [dart-lang/sdk#24340]
Hello,

What I need is to control the blur of elements in my website dynamically from my Dart code, according to events (clicks). It works from JS.

From Dart, it works with Firefox, but nothing happens with Webkit (not tested in IE). <strong>It seems that the webkitFilter is not correctly managed by Dart</strong>.

Try this sample:

<pre><code>
&lt;h1&gt;This text will blur in Firefox, not in Webkit&lt;/h1&gt;

import 'dart:html';
import 'dart:core';

main() {
  document.querySelector('h1').style.filter = 'blur(5px)';
}
</code></pre>

<a href="https://stackoverflow.com/questions/32548375/filter-blur-css-property-from-dart">See my article in Stackoverflow</a>.

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/32548375/filter-blur-css-property-from-dart

**Comment by Pascal6yk1** [comment]
Yes ! This is MY question. Can't you see the name Pascal_6yk1 ?

**Comment by zoechi** [comment]
Sorry, I missed that you already added the link to the SO question.

**Comment by alan-knight** [comment]
Missing 'webkit' prefix on the attribute.

**Comment by Pascal6yk1** [comment]
Yes, inside the Dart engine, not in my code. ["Dart  hides vendor prefixes"](https://www.dartlang.org/articles/improving-the-dom/#no-more-vendor-prefixes). There is a bug.

**Comment by alan-knight** [comment]
Yes, it's a bug.

**Comment by alan-knight** [comment]
So the problem is that the detection is done automatically. To set a CSS attribute foo we look and see if there's a foo attribute, and if not, we try Device.cssPrefix + foo. In Chrome (45) there is both a filter and a -webkit-filter attribute. But setting the filter attribute doesn't seem to do anything. I'm not sure what to do about this. We could hard-code filter, but that's pretty ugly. We could check the prefixed version first, but doing that in general risks running into the situation where we have legacy behaviour in the prefixed version that doesn't match the final standard but is preserved for backward compatibility. There are six other attributes that are also duplicated. If we hard-coded it, I'm not sure if we should also hard-code those.

backgroundclip
backgroundorigin
borderimage
clippath
filter
mask
writingmode

**Comment by Pascal6yk1** [comment]
Oups ! Pretty confused for my little head. What I understand in your answer is that Dart can't run webkitFilter, and solving the issue seems to be a big deal. This is not a problem because: 1) Webkit engine will adopt only standard filter in the future, 2) a solution is to make a filter.js file aside Dart code (it's what I've done).

Thank you very much.

**Comment by kevmoo** [comment]
I believe Chrome now supports unprefixed `filter`, which means this now works
