### ISSUE TITLE
It's confusing that --observe implies --pause-isolates-on-exit

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24352]
Currently if you pass `--pause-isolates-on-start` to the VM, it will pause the isolates when they exit as well. This is confusing; if I wanted them to pause on exit, I would have passed `--pause-isolates-on-exit` as well. It's also undocumented.

**Comment by johnmccutchan** [comment]
--pause-isolates-on-start does not imply --pause-isolates-on-exit. You can observe this with a simple helloworld.dart:

main() { print('Hello World'); }

$ dart --enable-vm-service --pause-isolates-on-start

*) Connect with Observatory
*) Navigate to debugger and continue isolate.
*) See the 'Isolate exited' message in the debugger.
*) Navigate to the VM page and see there are no isolates running anymore.

So at this point the isolate has actually exited. However there is a related bug that was stopping the VM from exiting (and therefore the process from exiting). 

https://codereview.chromium.org/1338753004

**Comment by nex3** [comment]
It looks like `--observe` was what was actually triggering this. But it's still undocumented and in my opinion unexpected that just enabling the observatory stops isolates from exiting. It's also contrary to the behavior of `--enable-vm-service`.

**Comment by johnmccutchan** [comment]
--observe is literally an alias for --enable-vm-service --pause-isolates-on-exit

If you want to enable observatory, you use --enable-vm-service

**Comment by zaidite** [comment]
Hi
I came back to this problem again.
Flutter 3.3.10 and Dart 2.18.6

When I run the project in VSC - Dart DebugTool not opening, because in VCS there is a setting that says - do not run Dart DebugTool. And in Intellige Idea and in Android Studio this setting does not exist for dart-project.

![image](https://user-images.githubusercontent.com/2315324/208405294-26f0cd29-af3b-4f08-9a1a-43bb05890827.png)


Is there any way to fix this? 
Add setting for Dart projects in Intellige Idea and in Android Studio - don't run Dart DebugTool.
