### ISSUE TITLE
getIsolate returns invalid parameter error for an expired isolate

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24353]
This is contrary to the behavior of the similar `getObject` RPC, and confusing since the request itself is well-formed.

**Comment by johnmccutchan** [comment]
@nex3 isolateIds are randomly generated 64-bit integers. We have no cheap way of knowing whether an isolateId was valid and is no longer valid. Instead of saying it is an invalid parameter, we could always say that the isolate was collected. This would be inaccurate in the case that someone manufactured an isolateId that was never valid but probably friendlier to legitimate users of the service protocol.

**Comment by johnmccutchan** [comment]
@turnidge

**Comment by turnidge** [comment]
I will return <collected> for plausible isolate ids.
