### ISSUE TITLE
A JsObject which has HTMLElement on its proto chain doesn't get properly wrapped 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#24371]
cc @sigmundch

**Comment by sigmundch** [comment]
For background: this was noticed in the context of polymer 1.0:

Jake was using Polymer.Base through JSinterop, but Polymer.Base extends from the HTML element prototype. This confuses our interop library in dart2js causing it not to wrap the Base, even though this is not an instance of an HtmlElement. In Dartium, the interop library wraps the object correctly.

We found 2 ways to work around this for now:
  * copy in JS code the pieces of Polymer.Base somewhere else, then read those values through js-interop from that new location that doesn't extend from HtmlElement.
  * use `((x) => x is JsObject ? x : new JsObject.fromBrowserObject(x))(js.context['Polymer']['Base'])`, here we need the ternary expression to make sure the semantics are the same in Dartium.

**Comment by jacob314** [comment]
This is by design for the existing dart:js library.
All Node subclasses are expected to return their dart:html equivalents rather than a JsObject. Changing that could break other uses.

I think we should leave JsObject alone and solve this in the context of new wrapperless interop.

The coherent solution in the context of the existing dart:js library would be to make Node extend JsObject but that is probably not worth the complexity and confusion it could cause.

I think the better solution is to only handle this in the context of new JS interop where this becomes straight foward.
You would write
@JsName("Polymer.Base")
external BaseElement get Base;

@JsName()
class BaseElement extends HTMLElement {
 ... your polymer base methods
}

**Comment by sigmundch** [comment]
Note that in our case we were trying to read a static member of Polymer.Base, as in:

```dart
js.context['Polymer']['Base']['deserialize']
```

I agree, though, that we don't want to wrap instances like `new Polymer.Base()`, since those are custom elements and dart:js should continue to treat them like a normal `HtmlElement`s. 

Is there a way we can tell that an access to `Polymer.Base` can be treated differently?

**Comment by jacob314** [comment]
Is Polymer.Base truly an HTMLElement? If so, trying to work around it showing up as an HTMLElement seems like a bad thing. I'd just stick with the JsObject.fromBrowserObject(x) call which is the right way to handle this case in the context of the old JsObject API. I know it is verbose but relative to all the other overhead from wrapper based JsObject calls, it really won't be a performance issue if that is the concern.

Btw in terms of new JS interop this could just be

@JsName("Polymer.Base.deserialize)
external deserialize(data);

**Comment by jakemac53** [comment]
Polymer.Base is not really an HtmlElement, it is a regular object which has HTMLElement assigned to its `__proto__` property.

**Comment by jacob314** [comment]
We won't fix the whole issue but we will make this less paintful in the short term by tweaking
 new JsObject.fromBrowserObject
to not throw if passed an existing JsObject.

**Comment by jakemac53** [comment]
SGTM

**Comment by matanlurey** [comment]
Very stale.
