### ISSUE TITLE
Analyzer doesn't complain for returning the wrong subtype in a function

### ISSUE THREAD

**Issue by Pacane** [dart-lang/sdk#24376]
Assuming the following code

```dart
class User {
  String id;
  String name;

  User();

  User.fromJson(Map map) {
    id = map['id'];
    name = map['name'];
  }
}

Future<List<User>> fetchUsers() async {
  String url = "someUrl";

  var response = await http.get(url);
  Map json = JSON.decode(response.body);
  List<Map> membersJson = json['members']; // expecting this to be a JSON array of User
  var members = membersJson.map((Map map) => new User.fromJson(map));

  return members;
}

List<User> fetchUsersSync() {
  List<Map> membersJson = [{'name': 'joel', 'id': '214'}];
  var members = membersJson.map((Map map) => new User.fromJson(map));
  return members;
}

main() async {
  print(await fetchUsers());
}

main2() {
  print(fetchUsersSync());
}
```

It no case the analyzer tells me that I the return type of my function doesn't match the type that's actually returned (`List<User>` vs `MappedListIterable`)

After discussing with @kasperl in the slack channel I made some tests with dart checked mode vs production mode and here's what I found

When comparing the async function (with `main()` ) in checked vs production modes here's what I get

![image](https://cloud.githubusercontent.com/assets/2762440/9961175/1868a372-5ded-11e5-966e-9bc13bb0bada.png)

The analyzer doesn't yell while developing AND the error looks the same at runtime.

When comparing the sync functions (with `main2()` ) in checked vs production modes here's what I get

![image](https://cloud.githubusercontent.com/assets/2762440/9961220/5f4678c8-5ded-11e5-9ce3-aad029ab752d.png)

Now the checked mode knows that the error happens at the return instruction.

The whole discussion was is Slack, but here are they key points of what @kasperl said:

> Nah, I think this is complicated by the fact that the Iterable is wrapped in a future by the return statement.

> I wonder if that Future is Future<dynamic> or Future<Iterable>. Seems like the former even though you would expect the latter.

> I'm actively investigating how (if possible at all) to get the Future returned from your async function to be more specific than Future<dynamic>. It does seem wrong to me. Opening an issue is definitely warranted and then we can try to capture (at least) parts of this conversation there too!

**Comment by bwilkerson** [comment]
In both cases, the static type of `members` is `dynamic`. Because `dynamic` is assignable to anything, there should not be any error or warning. The behavior of the analyzer is therefore correct.

Even if you were to give `members` an explicit type of `Iterable<User>`, there would be no error or warning. Dart has an unsound type system in which two types T and S are assignable to one another if either T is a subtype of S or if S is a subtype of T. `List<User>` is a subtype of `Iterable<User>`, so the type of the return statement's expression is still assignable to the return type of the method.

We are working on a "strong" mode for analysis that will use a less unsound type system, and I believe that strong mode will catch this kind of error.

**Comment by Pacane** [comment]
@bwilkerson Why is it `dynamic` ? Is it because of the `.decode()` ? If so, is there a way to specify a type annotation to decode (or create an explicit decoder?) so that `members` isn't `dynamic`?

**Comment by bwilkerson** [comment]
The static type of `members` is `dynamic` because you used `var` at the declaration site rather than providing a type annotation.

**Comment by Pacane** [comment]
Oh gotcha, thanks for the info.

**Comment by kasperl** [comment]
The reason why I think this is worth looking into is that it seems impossible to use the `async` modifier to construct a method that dynamically returns an instance of `Future<List<User>>` which means that even in checked mode we get no reasonable errors.

I dislike that even if you change to:

```
Iterable<User> members = membersJson.map((Map map) => new User.fromJson(map));
```

you still get no warning (because of the assignability rules) *and* no checked mode error because the `async` modifiers throws runtime type information away in the process of wrapping the value in a `Future`.

**Comment by bwilkerson** [comment]
> ... it seems impossible to use the `async` modifier to construct a method that dynamically returns an instance of `Future<List<User>>` ...

I don't think I understand what you mean. If the call to `map` were followed by a call to `toList`, the future would be completed with a value of type `List<User>`, as expected.

It's really inconvenient that `map` doesn't return the same type of value as the receiver. I've been tripped up by that several times. The situation would be helped by having a sound type system that could tell me at compile time that I made a mistake, but I have to wonder it the real problem isn't the definition of `map`.

**Comment by kasperl** [comment]
It's not the value the `Future` completes with that's the problem, it's the fact that it is always an instance of `Future<dynamic>` not `Future<List<User>>` which causes all checked mode checks to go through.

**Comment by bwilkerson** [comment]
Ok. That makes sense, thanks.
