### ISSUE TITLE
Specification: no definition for 'dynamic error'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24394]
Specification contains many statements like 'If T is a malformed type (19.1), a dynamic error occurs.'. But there's no definition of what dynamic error is. There is only statement 'Dynamic type errors are type errors reported in checked mode.' (7 Errors and Warnings). Is this the same thing? What exact error should be thrown at runtime if it is 'dynamic error'?

**Comment by lrhn** [comment]
If the quote is correct, the error will likely be a `TypeError`, but you are correct that the specification doesn't say anything (that I can find) - so it's unspecified.
(I can't even see any place saying that "a dynamic error occurs" means that something is thrown, so it should probably at least say that).

**Comment by eernstg** [comment]
I will close this because we do not plan to specify the precise kind of object which is thrown in all cases. The language specification mentions some specific exceptions (like `TypeError` and `AssertionError`), but it does not specify which type of exception to use for most of the dynamic errors. We have about 5 errors where a specified type is thrown and about 48 dynamic errors with no such information. This approach allows implementations some amount of flexibility, and given that an `...Error` should not be caught it should not be necessary for developers to get these types spelled out in a specification.
