### ISSUE TITLE
dart2js: 60% regression on Iteration.concat.manual2

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#24412]
@sigmundch @asgerf @kmillikin 

My recent change has some performance regressions https://chromiumcodereview.appspot.com/1362553002/ dart2js runtime: Harden objectTypeName.

This affects a few cps_ir results too.  (DeltaBlueClosures -13%)

The problem is that by mentioning the interceptor for UnknownJavaScriptObject, I caused an extra test in the getInterceptor specializations. I verified this causes the slowdown on Iteration.concat.manual2.

```javascript
  J.getInterceptor$a = function(receiver) {
    if (receiver == null)
      return receiver;
    if (receiver.constructor == Array)
      return J.JSArray.prototype;
    return receiver;
  };
```

--->

```javascript
  J.getInterceptor$a = function(receiver) {
    if (receiver == null)
      return receiver;
    if (receiver.constructor == Array)
      return J.JSArray.prototype;
    if (!(receiver instanceof P.Object))            // new
      return J.UnknownJavaScriptObject.prototype;   // new
    return receiver;
  };
```

I have mixed feeling about this.  The regression would only occur in stand-alone JavaScript because real web apps will have a getNativeInterceptor call guarded by the same predicate and would incur exactly the same penalty.

I will look at this in the morning and maybe back out part of my objectTypeName change.

**Comment by asgerf** [comment]
There should be a way to test if something is an UnknownJavaScriptObject without that class being considered instantiated.

I think if you write `object is UnknownJavaScriptObject` instead of `identical(interceptor, UnknownJavaScriptObject)` then the backend can constant-fold that if there are no instances of the class, or translate it into whatever form is best, possibly reusing the interceptor obtained from the explicit getInterceptor call.

**Comment by rakudrama** [comment]
Fix available: https://codereview.chromium.org/1366673003

**Comment by rakudrama** [comment]
Fixed regression: https://chromiumcodereview.appspot.com/1363183003/
