### ISSUE TITLE
(Optionally?) treat stdin as broadcast stream

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/sdk#24464]
If I want to ask the user for input in the command line and then fetch the result, I can do something like `stdin.first`, but then the stream is listened to and forever unavailable. Instead, if I want to do it in multiple places, I must set up a broadcasting stream controller:

```dart
var controller = new StreamController.broadcast();
stdin.listen(controller.add); // [1]

// to get the next standard input
print(await controller.stream.first);
```

And that's fine. However, let's consider that I have a library, where a feature of the library is to ask questions to the user and receive input (using the above method), I have forever prevented the user of my library to interact with stdin throughout the process by listening to the original stream [1].

If stdin could provide a method to access stdin as a broadcast stream, we would have a safe method to treat the console as a UI, without messing the process up.

```dart
// If we're depending on that the entire stdin is provided (for example a file input)
stdin.listen(...); // as usual

// Besides that, dart:io could provide another stream, broadcasting the stdin events without
// claiming the original stream

stdinBroadcast.listen(...);
```

**Comment by zoechi** [comment]
I wouldn't directly listen on stdin within a library. Allow the user to pass you the stream she wants you to read from.
With broadcast streams it's easy to miss data. If nobody listens the data is dropped.

**Comment by emilniklas** [comment]
It doesn't matter. If I (aware of the difference between a broadcast stream and a normal stream) need a broadcast stream of user input in the terminal, the only way to acquire that is by listening to stdin, even if that is provided by the user.

So the issue isn't whether or not it's a good idea (which I think is entirely up to the project in question), it's that it is currently **impossible** to react to user input (essential in utility scripting) in two different places without a solution like this:

```dart
Stream _myStdin;
Stream get myStdin => _myStdin ??= _broadcastStdin();
Stream _broadcastStdin() {
  var controller = new StreamController.broadcast();
  stdin.listen(controller.add);
  return controller.stream;
}

main() {
  someMethodFromLibraryOne(myStdin);
  someMethodFromLibraryTwo(myStdin);
}
```

**Comment by lrhn** [comment]
You might be able to  use the `StreamQueue` class from `package:async`.
It allows you to iterate through events, and if necessary create a new stream from the remainder of the original stream.

**Comment by emilniklas** [comment]
@lrhn That looks useful, but it doesn't solve the problem of stdin being a single stream. I'll probably use it though! Thanks!

**Comment by lrhn** [comment]
You can use `stdin.asBroadcastStream()` to get a broadcast version of `stdin`, but I recommend against it. Broadcast streams are almost never the answer to problems like this, they are far too fragile.

The problem is that broadcast streams push events even when noone is listening. That's really what makes them broadcast. The fact that more than one listener can listen to them is really secondary, so if you want two listeners on a single stream, but still want to be have some sort of control over the stream, using broadcast stream is likely to not give you that control. Instead you risk losing some events if you are not *very* careful (e.g., don't use `async` functions [1]).

`stdin` is a single subscription stream because it is a single coherent input split into parts. If you lose some of the input, the rest may not make sense. Broadcast streams are intended for multiple independent events where losing some of them doesn't change the meaning of later events.

From your description, the `StreamQueue` class should be able to handle the input. You can then choose to pass that input to multiple other streams. Alternatively you can use the [`StreamSplitter`](http://www.dartdocs.org/documentation/async/1.3.0/index.html#async/dart:pkg-async.StreamSplitter) class to just split the input into multiple streams.


[1] An `async` function has its body executed "at a later time". That means that calling an async function with a stream makes it impossible for the function to listen to the stream immediately. If it is a broadcast stream, some events might have passed before the function gets to listen to it.

**Comment by emilniklas** [comment]
@lrhn People keep assuming I don't know the implications of a broadcast stream... I do! :grin: The point is, for some tasks, broadcast streams **are** the answer.

Here's what I'm trying to do:

At some point in my console app, I want to non-blockingly pause execution of the current function (await). then **START** a new listener (I'm not interested in the whole stream, only all events from this point on – i.e. a broadcast) on stdin (because that's the only way to access terminal input), and as soon as the stdin stream has fulfilled my request, I want to complete my pending Completer, sending through the input from the user, and then **RELEASE** stdin.

The reason why that's important for this particular use case is that I'm creating a script to reload the current script in a new isolate, and for that to work I need to tear down the current instance as much as possible, so that as soon as the isolate containing the new instance finishes, the current instance will finish as well.

Currently, the solution is to tear down everything **except** the stdin subscription. If I cancel that, the new instance fail to attach its stdin to the current process' (it just doesn't read the input).

However, on Windows, the behaviour is not the same. First of all, if I cancel the stdin listener in the original isolate, the process crashes with a c++ error message:

```
vm\os_thread_win.cc:192: error: Mutex lock failed 6
```

If I don't cancel the subscription, the stdin kind of stack up, so every other stdinput goes to the original isolate, and every other to the isolate.

If I never listen to stdin in the first isolate, the second one does exactly what it's supposed to do, and gets the stdin as usual.

Because of this, I figured if we had broadcast access to stdin alongside the normal stream, we could get events on every isolate independently. In my case, I could then cancel my first isolate's subscription before starting the new isolate, so that I just ignore every broadcasted event on the original isolate, giving the new one the same control as the original one.

I hope this makes sense.

**Comment by lrhn** [comment]
@sgjesse 
It makes some kind of sense to me (so I'm adding Søren who knows stdin better).

It seems to be a problem related to stdin more than streams. You are listening to two different streams, in different isolates, both backed by the same underlying file descriptor. That may explain why inputs are distributed to alternating isolates rather than all sent to both of them.

**Comment by emilniklas** [comment]
@lrhn 
It makes sense to just allow one isolate to access stdin as it is now. It should throw the second time the stream is accessed, no matter what isolate has the listener.

However I stand by that there should be facilities for accessing stdin in a UDP-like manner.

**Comment by emilniklas** [comment]
Okay, so I've figured out a way to do this correctly, but it isn't pretty:

1. In the master isolate, create the broadcast (`stdin.asBroadcastStream()`)
2. Create a child isolate, sending through a `SendPort` that expects a `SendPort` to be sent back.
3. When the send port is sent back from the child, start a new listener on the broadcast, and for every event, send through the bytes to the child isolate: `stdinBroadcast.listen(sendPort.send)`.

That way, the child isolates never touch stdin, but rather get its own stream from the master isolate, who can then create as many child isolates as it wants.

**Comment by lrhn** [comment]
That sounds like a reasonable solution. If you encapsulate this into one class which controls the access to stdin, and where anyone can add a `SendPort` if they want to be notified, then you don't even need to make stdin broadcast - it only has a single listener.

(Not at all obsessive about broadcast streams, no way!)

**Comment by lrhn** [comment]
We are not planning to make Stdin a broadcast stream.
It's fragile as written, but being a broadcast string isn't going to make that better, just different.
