### ISSUE TITLE
Measure the high water mark post GC 

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24483]
We would like to start tracking memory usage as a benchmark, and we think using a high water mark might be a good initial measurement for us. This would be the maximum amount of memory retained post GC throughout the execution of the program.

/cc @johnmccutchan @rakudrama

**Comment by sigmundch** [comment]
I forgot to mention that we intend to extract the information in an automated fashion, but I assume that should be possible like anything else currently supported in observatory, correct?

**Comment by iposva-google** [comment]
Siggi, as far as I understand your request this API already exists in the VM service protocol. All you need to do is to subscribe to the GC events and your VM service client will be told about GCs and the post GC memory use.

Please reach out to @turnidge or @johnmccutchan regarding the protocol implementation or to @nex3 and @cbracken about connecting to the VM service protocol for tools like these.

**Comment by nex3** [comment]
I don't believe there's currently any means of learning about the memory use in [the public VM service protocol](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md).

**Comment by sigmundch** [comment]
Yeah, I spoke with @johnmccutchan yesterday, he said it should be easy to add though.

**Comment by turnidge** [comment]
It's in the private protocol.

If you want to use it now, rather than later, try:

-> streamListen('GC')

Then you will start to receive events where eventKind is 'GC'.  You will
need to inspect these events to determine what their fields are.  Since
this is an unpublished api, it is subject to change.

Todd

**Comment by sigmundch** [comment]
Thanks for the tip Todd, I was able to use the vm service by listening on the gc events today and extracting the used/capacity numbers. Here is what I ended up doing: https://codereview.chromium.org/1384833002/

Any chance this could be exposed directly from a flag in the vm? Or is this only going to be supported via the observatory service? The reason I ask is to see if we can simplify how to integrate this with our benchmark infrastructure: if the vm can print out the result by giving it a flag, we can't avoid pausing isolates on start, won't need to run a second binary on every benchmark.

**Comment by iposva-google** [comment]
It appears to me that this has left the realm of Observatory. So I have updated the labels accordingly.

**Comment by iposva-google** [comment]
Siggi, when you want to get this information from a command line Dart program when running on the VM, you can also run with --verbose-gc and filter the GC messages from the output (e.g. grep for "[ GC("). The messages are on purpose comma separated, so that processing them should be straight-forward from a variety of shell scripts, spread sheets, or other programs.

Example:
[    GC    |  space  | count | start | gc time | new gen (KB) | old gen (KB) | timers | data ]
[ (isolate)| (reason)|       |  (s)  |   (ms)  | used,cap,ext | used,cap,ext |  (ms)  |      ]
...
[ GC(429968702): Scavenge(new space), 2, 0.046, 0.035, 1024, 0, 1024, 1024, 0, 0, 1109, 1114, 1280, 1280, 0, 0, 0.007, 0.010, 0.004, 0.001, 41, 0, 0, 0, ]

Detailed explanation:
[ GC(429968702): Scavenge(new space), 81,
This was a new GC, the second GC to be exact.

0.046, 0.035
Started 0.046 seconds after the isolate start. Duration was 0.035 ms.

1024, 0, 1024, 1024, 0, 0,
New used before 1024KB, after 0KB. New capacity before 1024KB, after 1024KB. No external memory associated with new space before or after.

1109, 1114, 1280, 1280, 0, 0,
Old used before 1109KB, after 1114KB, meaning that 5KB were promoted to old space. Old capacity before and after 1280KB. No external memory associated with old space before or after.

0.007, 0.010, 0.004, 0.001, 41, 0, 0, 0, ]
Detailed timers and counters used for GC internal algorithm analysis.

**Comment by iposva-google** [comment]
P.S. Your VM service based tool looks pretty nice and we might want to use it as an example of how to use the VM service protocol outside of the Observatory.

@johnmccutchan  @turnidge , what do you think of making this into an example on how to use the VM service protocol in a programmatic fashion? Obviously only once we have finalized the GC APIs.

**Comment by rakudrama** [comment]
I'd like to clarify something here that I originally mentioned on the work in progress https://codereview.chromium.org/1391473002/ .

We are primarily interested in is tracking the size of the data structures in our program, not the amount of memory required to run the program (though that is useful too).

It would be nice if there was a metric that hid details like old or new heaps.
What we want is a max-used over all heaps (old, new, whatever you invent
tomorrow) that reflects the #bytes of data that the program can reach.  i.e. a
metric that is a property of the program (at some arbitrary GC 'samples') that
is mostly independent of any policy or mechanism of the GC.

**Comment by sigmundch** [comment]
> We are primarily interested in is tracking the size of the data structures in our program, not the amount of memory required to run the program (though that is useful too).

good point @rakudrama - I initially had in mind just to measure the latter as an approximation of the former, but it's true that this has more noise and it's preferable to measure the real thing instead. I'm not sure how feasible it is to measure that from the vm without forcing a full GC, though.

**Comment by johnmccutchan** [comment]
Generational heap usage maximums: https://codereview.chromium.org/1384003004/

**Comment by johnmccutchan** [comment]
@rakudrama @sigmundch New CL should fix this bug. Please let me know here if it isn't what you had in mind.

**Comment by sigmundch** [comment]
@johnmccutchan yes - thank you so much for the fix and the quick turnaround!

**Comment by johnmccutchan** [comment]
@sigmundch The VM team is still internally discussing the best way to surface this information so this may not be the final form.

**Comment by sigmundch** [comment]
@johnmccutchan -- playing around with the output today: what is the difference between `new.used.max + old.used.max` and `global.used.max`?

I was thinking they should add up to the same, but I'm getting difference results (e.g 36M vs 68M)

**Comment by johnmccutchan** [comment]
@sigmundch -

* new.used.max and old.used.max are updated after a new and old space GC respectively. These are both accurate (today). The sum of these isn't accurate at all because they are updated at different times.

* old.used.max will stop being accurate once old space GC is happening concurrently because the VM won't be stopping the world anymore and the mutator may be allocating while the GC is calculating how much memory is being used.

* new.capacity.max and old.capacity.max are accurate but they represent the amount of memory reserved from the OS and not the amount of memory used post-gc.

* global.used.max is updated after a GC of either space. It can over count because we query both heaps for their current used amount after either heap was GCed. 

* This global count of post-gc memory usage that you and @rakudrama are asking for isn't known by the VM today and will become harder to answer going forward.

**Comment by sigmundch** [comment]
Got it, thanks again for all the clarifications!
