### ISSUE TITLE
request partial list or map from VM service API

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24536]
Currently, requesting a huge List or Map via the Service Protocol can bog down the VM or even cause OutOfMemory on the client due to the size of the payload. It would be useful if the current VM service protocol API could be extended so that clients could request a given number or range of elements to limit the payload, reduce the performance hit, and prevent OOM.

**Comment by clayberg** [comment]
Note that this is a serious concern from the JetBrains side:

"trying to see contents of huge List or Map takes too long and causes OutOfMemory (VM Service protocol limitation), but finally IDE recovers without crash"

Being able to request a subset of the payload or have the payload delivered in chunks (for example, 100 list or map elements at a time) would be useful for all clients, not just IntelliJ.

**Comment by alexander-doroshko** [comment]
Major clarification. New API for partial list/map would be great but original problem is that [getObject(isolateId, objectId)](https://github.com/dart-lang/vm_service_drivers/blob/master/dart/tool/service.md#getobject) may take ages and finally return gigabyte-size response in case when **objectId** argument is an id of the instance that corresponds to a huge List or Map. That happens because spec requires that `getObject(isolateId, objectId)` returns [Instance](https://github.com/dart-lang/vm_service_drivers/blob/master/dart/tool/service.md#instance) that contains non-truncated `elements` for List or `associations` for Map. 

Suggestions:
- limit the amount of objects returned by Instance.getElements() and Instance.getAssociations() with 100.  Client knows actual List/Map size (Instance.getLength()), so client will understand that returned elements/associations are truncated.
- add ability to query any range of List / Map entries.

**Comment by sethladd** [comment]
Is there a workflow that we could follow, in order to repro? How do we generate a huge List?

**Comment by alexander-doroshko** [comment]
@sethladd fill it in a loop :)

**Comment by sethladd** [comment]
@alexander-doroshko thanks for the detail and info!

**Comment by iposva-google** [comment]
Based on the Instance reference you get, you do know whether it is one of the potentially unbounded objects and you also know the referenced objects length from the reference. I would investigate a getRange call instead of complicating the getObject call.

Also one thing you should be aware of when accessing partial information: The contents of the subranges may shift while the program is in flight.

**Comment by alexander-doroshko** [comment]
Ok, I agree that I have information about list/map size before asking getObject(), and I can make a decision at client side not to call getObject() for it. Just thought that protocol could take care about bad clients that call getObject() without checking size before doing that. Well, it's up to you.

`getRange` functionality sounds good to me. It is called when isolate is suspended. Unlikely list/map contents can change while calling consequent getRange() unless `get` routine implementation of this List/Map changes contents (which is not an expected collection behavior).

**Comment by turnidge** [comment]
I have decided to add offset and count parameters to getObject.  Change landing soon.

**Comment by alexander-doroshko** [comment]
Thank you very much!
