### ISSUE TITLE
analyzer with --supermixin doesn't warn if application base class isn't of the right type.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#24535]
Example:

```
class C {}
class D extends C {}
class O = Object with D;  // Should warn because class would not be a subtype of C if not for the "with D".
```

The analyzer does not currently warn about this.

Quote from https://github.com/gbracha/lessRestrictedMixins/blob/master/proposal.md

> When a mixin is applied, the resulting type is a subtype of the mixin type, as it is today. However, if the resulting type would not otherwise be a subtype of the declared supertypes of the mixin, a warning is issued. Hence, a mixin application would have to declare, directly or indirectly, that its superclass implements the mixin's superclass, and that it implements the mixin's superinterfaces in order to be warning-free.

**Comment by srawlins** [comment]
Still an issue.

**Comment by eernstg** [comment]
Note that `--supermixin` is going away, but Dart 2 (in an upcoming release, not the initial release of Dart 2) will have a separate notion of `mixin` declarations. This issue would then need to be adjusted to fit https://github.com/dart-lang/sdk/blob/master/docs/language/informal/mixin-declaration.md, noting that the new `on` clause may not work in the exact same manner as the `extends` clause works in a class which is used to derive a mixin for some mixin application.

**Comment by srawlins** [comment]
Fixed with 1st-class mixin language feature? This code:

```dart
class C {}
mixin D on C {}
class O = Object with D;
```

now triggers an analyzer error: "'D' cannot be mixed onto 'Object' because 'Object' does not implement 'C'."

**Comment by eernstg** [comment]
Good catch, thanks! The original program using `D extends C` is rejected by the analyzer (with the message that `D` cannot be used as a mixin because it extends a class which isn't `Object`), which is the correct response. Allowing it would be a threat to soundness in various ways.

Also, the [variant using `mixin .. on`](https://github.com/dart-lang/sdk/issues/24535#issuecomment-519351626) creates essentially the same threat to soundness, but that's detected as well.

So we can close this issue because it reports on a danger that doesn't exist today.
