### ISSUE TITLE
VM service protocol for pausing on exceptions

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#24531]
For parity with the old debugger protocol, clients need a way to tell the VM to pause when it hits an unhandled exception or when it hits any exception.

**Comment by iposva-google** [comment]
CC @turnidge @johnmccutchan 

As far as I understand the equivalent to the old protocol is available as a private API in the service protocol. It is not publicly exposed yet because we are thinking about expanding it, but for now you should be able to use the private protocol for feature parity with the old legacy debug protocol.

Hence not blocking 1.13. Assigning to Todd to evaluate future extensions and eventually making this part of the public service API.

**Comment by johnmccutchan** [comment]
@iposva-google Correct. The private API is available and can be used in the meantime. But we might want to make the API public in time for the 1.13 release. 

The _setExceptionPauseInfo takes an "exceptions" parameter which, today, can be three values "none", "all", and "unhandled". If we make this RPC public and in the future we need to expand upon how it works we can add a new value to the exceptions parameter. This would not break legacy clients. I just think we need to be sure that we are happy with the "setExceptionPauseInfo" RPC name.

**Comment by danrubel** [comment]
I'm happy to call private API from the java client until the public API is available. We're locking down the java client code shortly for upcoming IJ. I can call the private API until the public API is available. If we decide I should call the private VM API for now, then I ask that you keep the private API backward compatible for one full IJ release cycle (~ 6 months) beyond when the public API is available. I'll switch to the public API as soon as it is available.

**Comment by johnmccutchan** [comment]
Strawman of a public version of the API: https://codereview.chromium.org/1399743002/

**Comment by danrubel** [comment]
That looks like what we need. Thanks!

**Comment by rmacnak-google** [comment]
Was implemented years ago.
