### ISSUE TITLE
Strong mode message about "will need runtime check to cast to type" isn't relevant to pure VM users

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#24542]
```dart
void foo(int bar) { }
dynamic bar() => 2;

void main() {
  foo(bar());
}
```

gives this message:

```
[hint] bar() (dynamic) will need runtime check to cast to type int (.../test.dart, line 6, col 7)
```

**Comment by sethladd** [comment]
cc @vsmenon @leafpetersen

**Comment by vsmenon** [comment]
Is this a request to fix the wording of the message?  (As opposed to suppressing the message?)

E.g., something like "(dynamic) is implicitly cast to type int here"?

**Comment by Hixie** [comment]
As a VM user, I don't know what to do with this message. It doesn't make sense to me.
Either:
- There is a bug here even in code that will only ever run in the VM, in which case I would like to know what it is so I can fix it, or
- There is no bug here when you're targetting VMs only, in which case I don't want to ever see the message, or
- There might be a bug in some cases, but there isn't in this specific case, in which case I want a way to tell the analyzer that I know what I'm doing here and for it to please shut up for this specific line of code (but not later lines of code that _do_ have the bug that leads to this message).

**Comment by sethladd** [comment]
> (dynamic) is implicitly cast to type int here

Not sure if that's helpful, because Dart doesn't have "casts" in the way other languages do. So I'd be worried that message would be misleading/confusing in a different way.

Maybe: "(dynamic) is implicitly used as type int here" ?

Regardless, I'd be worried that code will have a lot of hints like that (because dynamic is a legit thing to do in Dart), and thus real bugs will be lost in the noise. Unless Strong Mode really discourages dynamic ?

And +1 to an ability to silence hints/warnings at a specific location when the author acknowledges that they understand the risks.

**Comment by lrhn** [comment]
I would prefer strong mode to be something you had to opt in to manually, e.g., by choosing to use the dev-compiler. Giving a warning that only applies to strong mode by default is very confusing.
Or at least mark the warning as `[Strong mode only]`.

**Comment by Hixie** [comment]
These warnings only apply if you have --strong set.

**Comment by jmesserly** [comment]
fixed in https://github.com/dart-lang/sdk/commit/f092c247fd7317339608483dd9613bae89cd4b20, sorry about that. These were supposed to be hidden behind `--strong-hints`, which is itself a hidden undocumented flag :)
