### ISSUE TITLE
String, bytes and encoding on MS Windows

### ISSUE THREAD

**Issue by Gen8** [dart-lang/sdk#24558]
Hi,

I have not found any way to convert between a list of bytes and a string on Windows.
There is no encoding or converter for bytes storing Windows-1252 or UTF-16 text.

**Comment by lrhn** [comment]
For UTF-16, you can just use `String.fromCharCodes` for that. It's so direct we don't even have a transformer.

For Windows-1252, we should add a converter to package:convert. Preferably one that can be used for any code page (any mapping between byte and code point).

**Comment by Gen8** [comment]
A charcode in UTF-16 is 16 bit in size.
A byte is just 8 bits.
I tried:
		File file = new File(filename);
		List<int> bytes = file.readAsBytesSync();
		//return file.readAsStringSync(encoding: SYSTEM_ENCODING);
		//return new Latin1Decoder().convert(bytes);
		//return new Utf8Decoder().convert(bytes);
		return new String.fromCharCodes(bytes);
and it did not work.

**Comment by sgjesse** [comment]
Right now we only have codecs for ASCII, Latin-1 and UTF-8 in `dart:convert`, and `String.fromCharCodes` which will convert from UTF-16.

If - as you mention - the file you are reading is in codepage 1252 - you will need to supply a new converter.

The code for the Latin-1 codec is here: https://github.com/dart-lang/sdk/blob/master/sdk/lib/convert/latin1.dart, and I think replacing the code in `_addSliceToSink` to do a mapping instead of just `String.fromCharCodes` should do the trick.

We don't plan on adding more codecs to `dart:convert`. Please open an issue with the [convert package](https://github.com/dart-lang/convert).

**Comment by lrhn** [comment]
If you have bytes and need 16-bit words, you should convert it to a `Uint16List`.
Most likely the bytes are already a `Uint8List`, in which case it's easy, otherwise you will have to copy them to a buffer.

We don't have a conversion from *bytes* interpreted as UTF-16. That would depend on byte ordering, so it's not trivial.

Example:
```
Uint16List toUint16(List<int> bytes) {
   if (bytes is! Uint8List) bytes = new Uint8List.from(bytes);
   Uint8List byteList = bytes;
   return byteList.buffer.asUint16List(byteList.offsetInBytes, byteList.lengthInBytes ~/ 2); 
}
```
