### ISSUE TITLE
runtimeType from object returned by async function prints as _Future

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24559]
Testing this on DartPad, which is really dart2js.

Consider this code:

```
import 'dart:async';

Future<int> doAsyncThing() => new Future.value(42);

usingAsync() async => doAsyncThing();

main() {
  var thing = usingAsync();
  
  // what is the runtimeType of thing ?
  print(thing.runtimeType); // _Future
  
  
}
```

Actual: This code will print `_Future`
Expected: `Future`

**Comment by sigmundch** [comment]
I believe this is actually working as intended: the runtimeType is the type of the implementation of the future. Turns out that `Future` is an interface, and it's factory methods allocate a private class called `_Future`.

Not always we use the same library code for the VM and for dart2js, but in this case we do. So if you run your example in the VM, it will also print `_Future`.

**Comment by sethladd** [comment]
Ah, interesting. Good to know that runtimeType can return privately named implementation types. Thanks for the quick response!
