### ISSUE TITLE
Please merge revision several Dartium revisions into dev channel

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#24633]
@whesse @mit-mit @kasperl
@kevmoo @terrylucas 

This merges two CLs that move top-level methods used for JS-interop Dartium out of the public dart:html api, two which fix custom element issues, one for corresponding test suppressionsm, and a DEPS update for Webkit.  By combining them in one cherry-pick, they all merge cleanly. If desired, the DEPS and tests could be applied separately.

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>
5bd1ce68d1301f017234dc3696bb1fafaaf8cbbe     - Fixed native element extension, custom events, _VMUpgrader
3e48b42360297ae8f306668fc74331f7a80a2526     - move make_dart_rectangle out of dart:html into html_common
a86f7dbeb047e7ca99dca3c0e3cfcb51f6f952af     - Custom elements should work only in html and svg namespaces
2f999508446428d18c0962a47ab4f00c4a03d87a     - Move additional methods from dart:html into html_common
6ab000fbd3db499d7cd83e232f09a30d1ffa281f     - Update test suppressions
7aedf74616bffdedebb7c50aea8a98a0749a07b1     - DEPS update for webkit change: Make Dart objects passed to JavaScript expose the Dart toString method

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>
This merges cleanly and all tests pass. I had an earlier version with only three of them, but edited this to have a clean merge.

**Comment by alan-knight** [comment]
Terry points out that this does merge cleanly if we incorporate all the Dartium-related updates into one. So, instead

  5bd1ce68d1301f017234dc3696bb1fafaaf8cbbe - Fixed native element extension, custom events, _VMUpgrader

  3e48b42360297ae8f306668fc74331f7a80a2526 - move make_dart_rectangle out of dart:html into html_common

a86f7dbeb047e7ca99dca3c0e3cfcb51f6f952af - Custom elements should work only in html and svg namespaces

2f999508446428d18c0962a47ab4f00c4a03d87a - Move additional methods from dart:html into html_common

6ab000fbd3db499d7cd83e232f09a30d1ffa281f - Update test suppressions

7aedf74616bffdedebb7c50aea8a98a0749a07b1 - DEPS update for webkit change: Make Dart objects passed to JavaScript expose the Dart toString method

Now this merges cleanly and all tests pass.

**Comment by whesse** [comment]
These hashes don't exist.  Perhaps you cherry-picked them to dev locally, and then gave me the resulting hashes.  I need the original commits in the master branch.  It was hard to find them, because the descriptions here are different from the descriptions in the commits.

I also don't understand what you mean when you say they have conflicts when cherry-picked individually, but not when cherry-picked together.  What commands are you using, and what conflicts do you get?  Could it be that you are cherry-picking them in a different order than they were originally committed?

I'll cherry-pick the 5 commits that I could find: (listed from earliest to latest)

4653701a7656136d2725b76497cf1a67a15dd4f4
       - Fixed native element extension, custom events, _VMUpgrader
e562934defd630f77755d77c6f9108552977e4a0 
      - Custom elements should work only in html and svg namespaces 1a1820bbe3bf3b393105a342b414730f9ba105d3 
     - move make_dart_rectangle out of dart:html into html_common
208e3f981a3e724dce8510332e1c0a576d89e3be
      - Update test suppressions
a9362610ee429a0b69653635039696f86976f564
      - Move additional methods from dart:html into html_common

Cannot find this one.  There seems to be no commit to master that changes DEPS this way: "DEPS update for webkit change: Make Dart objects passed to JavaScript expose the Dart toString method"

**Comment by whesse** [comment]
Cherry picked with no merge conflicts to 1.13.0-dev.7.3

**Comment by whesse** [comment]
Merged into 1.13.0-dev.7.3

**Comment by alan-knight** [comment]
Sorry about that, not sure what I did with the hashes.

Originally I had done just three of them, and one of the ones that was missing modified some of the same code, so if you didn't cherry-pick it as well it didn't merge cleanly.
