### ISSUE TITLE
Request for an Unmodifiable Set

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24652]
I see an unmodifiable list view and map view in dart:collection, but didn't find an unmodifiable set view. Do we have something like that? If not, could we consider adding it?

(request from customer)

**Comment by zoechi** [comment]
I usually use `UnmodifiableListView` for sets but a real `UnmodifiableSetView` would be nice to make it more clear for the user of the API what is actually returned.

**Comment by lrhn** [comment]
You can use the one in `package:collection` (http://www.dartdocs.org/documentation/collection/1.1.3/index.html#collection/dart:pkg-collection-wrappers.UnmodifiableSetView).
We have unmodifiable list and map mainly because we have list and map literals and several instances of API that returns unmodifiable lists or maps (e.g., `Invocation`). Unmodifiable sets are much more rare.

**Comment by sethladd** [comment]
Thanks for the follow up!  I understand that we want to work towards smaller core libraries, and that some functionality will be in packages.

cc @hixie

**Comment by Hixie** [comment]
We should have set literals also. There are places in Flutter's codebase right now where we're working around the lack of Set literals, FWIW.

**Comment by sethladd** [comment]
See: https://github.com/dart-lang/sdk/issues/3792

**Comment by Hixie** [comment]
Right. I'm just saying that if the argument is that we shouldn't have an UnmodifiableSet because we don't have a Set literal, that that's fine, since we should have a Set literal anyway. :-)
