### ISSUE TITLE
Uint8List.fromList show throw range errors

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/sdk#24708]
Currently, Uint8List.fromList will silently swallow values that are outside of the allowed range.

Should throw: RangeError

Example:
```dart
var lst = Uint8List.fromList([1, 2, 257]);
print(lst); ///[1, 2, 1]
```

**Comment by rakudrama** [comment]
Typed lists truncate on assignment to an element.  `Uint8List.fromList` is consistent with `operator[]=`.

```dart
var lst = Uint8List.fromList([1, 2, 257]);
print(lst); ///[1, 2, 1]

lst[0] = -1;
lst[1] = 260;
print(lst); ///[255, 4, 1]
```

We went with truncation rather than error for a bunch of reasons:

- We found it was basically impossible to implement the check you desire when compiling to JavaScript without taking a big performance hit.
- Typed lists are often used for handling large amounts of data (otherwise you might as well use a regular list).  If you put the checks in, it is hard to always remove them and convert copying loops to block copies.
- It is sometimes convenient.  The world you desire requires you to truncate yourself, e.g. `lst[i] = b & 255`.
- You can still check yourself, e.g. `assert(items.every((e) => 0 <= e && e <= 255))`.
- There is Uint8ClampedList, which is used in browsers to access image data. It has built in a different conversion (clamping rather than truncation). That makes no sense if you must manually clamp. We avoid [this pain](https://www.java.net/node/668465).
- If the user must do manual truncation, then Float32List is a problem since there is no (other) truncation to convert from double (float64) to float32 (where e.g. 1e40 becomes +Infinity)

**Comment by butlermatt** [comment]
I can totally respect the reasoning behind it. I guess in my instance it was a surprise. Perhaps add doc comments (for all typed lists) to indicate that values will be truncated to appropriate sizes with this constructor?

**Comment by sgjesse** [comment]
@lrhn

**Comment by lrhn** [comment]
Fixed
