### ISSUE TITLE
Please merge revisions 5ec298794bf70d1855d74321d63c635007d92578, ba6078197ba8093706873569d123cd94aa897308, and 396ed51cf04cfdfd3f33e6803a32e6a9cbfeefcf into dev channel

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#24734]
@whesse @mit-mit @kasperl

The first two commits are analyzer strong mode fixes, the third is a general analyzer bug that was causing problems with rolling flutter onto a new SDK (#24713).  Batching these up, since they overlap and apply cleanly when applied in sequence.  Let me know if it's better to split them out and provide an explicit merge CL.

Fix loop var inference on type params:      5ec298794bf70d1855d74321d63c635007d92578
Fix warnings on `Iterable<T> -> List<T>`:  ba6078197ba8093706873569d123cd94aa897308
Fix broken substitution for generics:           396ed51cf04cfdfd3f33e6803a32e6a9cbfeefcf

These merge cleanly when applied in sequence (top to bottom), VM and analyzer tests pass.

**Comment by whesse** [comment]
If we have to commit a lot more analyzer fixes, that are interleaved with these, it would be best to have all of the fixes in order, so they commit cleanly.  I'll see what I get today as analyzer cherry-pick requests.  I can figure out the order of them, so you don't need to do anything more.  In general, as long as they merge cleanly, in order, that is best for me, since I just do the git cherry-pick command on each commit.

I usually assume that multiple issues have been filed in the order of their commits, so I do issues from bottom to top, but commits within a single issue from top to bottom.

**Comment by leafpetersen** [comment]
Awesome, thanks.  Let me know if you hit any conflicts and need help resolving.

**Comment by kevmoo** [comment]
I will get you an updated, very long list of things to merge

**Comment by kevmoo** [comment]
Subsumed by https://github.com/dart-lang/sdk/issues/24742
