### ISSUE TITLE
Please, clarify await for specification

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24748]
The Dart Programming Language Speciﬁcation Version 1.9 reads:

> 17.6.3 Asynchronous For-in
> ...
>  Execution of a for-in statement of the form await for (ﬁnalConstVarOrType?
> id in e) s proceeds as follows:
>  **The expression e is evaluated to an object o.** It is a dynamic error if o is
> not an instance of a class that implements Stream. Otherwise, the expression
> await v f (16.30) is evaluated, where v f is a fresh variable whose value is a fresh
> instance (10.6.1) f implementing the built-in class Future.
>  The stream o is listened to, and on each data event in o the statement s is
> executed with id bound to the value of the current element of the stream. If s
> raises an exception, or **if o raises an exception**, then f is completed with that
> exception. Otherwise, when all events in the stream o have been processed, f
> is completed with null (16.2).

Please, clarify the following:
- The result of for-in statement if evaluation of expression e raises an exception.
- Phrase 'if o raises an exception' is confusing - o is an object (not a statement), 
  it can not raise exception directly.
- The result of for-in statement if stream is already "closed", for example by another 
  asynchronous for-in loop.

**Comment by alsemenov** [comment]
The chapter for break statement reads:
> If s E is an asynchronous for loop (17.6.3), its associated stream subscription
> is canceled. 

Please, clarify whether the stream subscription is cancelled,  when all events in the stream have been processed in asynchronous for-in loop.

**Comment by gbracha** [comment]
(1) If e raises an exception, it gets propagated as usual. As a rule, the spec does not clutter every evaluation path with discussions of normal and abrupt completion unless something special is done in those cases.

(2) Since o is a stream, it may raise an exception in the sense that an exception is thrown when a new element is being added. So this describes what the onError handler for the stream subscription will do.  We should add a note explaining this informal usage, yes.

(3) A closed stream has no subsequent data events, so there is nothing to iterate over. 

(4)  Stream are canceled by finally clauses (see 17.11) and at function termination (16.14) as well as break and continue statements. They are not canceled otherwise.
