### ISSUE TITLE
(This CL fixed by a later commit) Please merge revision d0f456a910675bab3b47b80fddf1fda5ee9b7fa8 into dev channel

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#24782]
@whesse @mit-mit @kasperl

Issue: fixes calling JavaScript getters with return type of Function as methods.

What revision(s) needs to be merged
d0f456a910675bab3b47b80fddf1fda5ee9b7fa8

**Comment by kevmoo** [comment]
@jacob314 that commit doesn't seem to exist

**Comment by kevmoo** [comment]
I think @jacob314 meant d0f456a – he should confirm

**Comment by jacob314** [comment]
Yes I did. Thanks @kevmoo

**Comment by whesse** [comment]
Merged in 1.13.0-dev.7.7.

**Comment by whesse** [comment]
This cherry-pick caused test failures, due to the lines

                } else if (returnType.treatAsDynamic ||
                    _compiler.types.isSubtype(returnType,
                      backend.coreTypes.functionType)) {

There is no coreTypes member of JavaScriptBackend in the dev channel.  Perhaps it was introduced in a more recent CL on bleeding-edge.

The tests, which fail locally also, are:
python tools/test.py -mrelease -cdart2analyzer -rnone --write-debug-log --write-test-outcome-log -t240 utils/recursive_import_test

and

python tools/test.py -mrelease -cdart2analyzer -rnone --write-debug-log --write-test-outcome-log -t240 utils/recursive_import_test

among others.

We either need to take this out, or add a cherry-pick which fixes this error.

**Comment by whesse** [comment]
Also breaks some dart2js tests:

 python tools/test.py -mrelease -cdart2js -rnone --use-sdk -t60 html/js_function_getter_trust_types_test

**Comment by jacob314** [comment]
The test failure is spurious.
Here's the cl to patch to suppress it
https://github.com/dart-lang/sdk/commit/7f546e9e0c6bb23afef071a1082cd8acf310ebbd

**Comment by jacob314** [comment]
here's the one line CL to fix the issue. I can land it to dev myself or you can land it.
https://codereview.chromium.org/1422853007

**Comment by whesse** [comment]
I'll land it in the next version, thanks.

**Comment by jacob314** [comment]
Thanks!

**Comment by whesse** [comment]
The fix was merged in 1.13.0-dev.7.8
