### ISSUE TITLE
Add urlSafe to Base64 Codec

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#24813]
There should be a urlSafe option in the Base64 Codec that follows https://tools.ietf.org/html/rfc4648#page-7

I will try to make a Code Review to support this.

**Comment by kevmoo** [comment]
CC @nex3

**Comment by nex3** [comment]
I believe @lrhn's position is that this extra functionality belongs in the `convert` package, not the core SDK.

**Comment by kaendfinger** [comment]
It's such a minor difference from what's already in here, I don't see why it shouldn't just be added to `dart:convert` - I could be missing something though....

**Comment by lrhn** [comment]
It does not belong in the BASE64 codec - that has the name "base64", and the URL-safe encoding should have name "base64url". So, it should at least be a separate codec. 

We try not to put too much into the platform libraries if it can safely be put into a package - counterweighed by wanting the things we do put in to be full-featured enough to use.

The tradeoff for BASE64 is to make encoding to actual BASE64 available, and decoding is lenient enough to parse both that and base64url encoding.

We could put base64url encoding into dart:convert. It really is a very small change from BASE64 - encoder only, since the decoder accepts both alphabets already. 

The "Url and filename safe encoding" is really a mis-nomer because there is nothing problematic with "+" and "/" in URIs unless you use for www-form-encoded. I don't see using base64-encoding as a file name as a big use-case.

That said, it's a very small change, and I can live with having a second codec.

**Comment by Andersmholmgren** [comment]
Is this planned any time soon? It is stopping any packages that require url safe base64 from upgrading past 0.9.2 of the `crypto`, such as those that implement standards like `jwt`.

If not then I fear `pub get` hell is looming for such packages in the future :/

**Comment by lrhn** [comment]
In the perfect world, I would put this functionality in `package:convert` but still extend the implementation in `dart:convert`. That's just not very easy since half the implementation is private, so I'll add it to `dart:convert` anyway. It's a fairly small change, replacing one 64-character string with another.

**Comment by Andersmholmgren** [comment]
Awesome. Thanks

**Comment by lrhn** [comment]
Fixed
