### ISSUE TITLE
Wrong analyzer warning on self-assignment 

### ISSUE THREAD

**Issue by manuelF** [dart-lang/sdk#24858]
See this snippet (dartpad with warning: https://dartpad.dartlang.org/4c353a7cf8726b4336ab)

```dart
class Base {}
class A implements Base {
  Base member;
}
void main() {
  A a = new A();
  wrong(a);
}
void wrong(Base base) {
  if (base is A)   base = base.member;
}
void right(Base base) {
  Base anotherBase = base;
  if (base is A) anotherBase = base.member;
}
```

Dart analyzer is not inferring in the 'wrong' function that base is actually of type A, so it says that there is no such thing as base.member. However, if you assign it to a different variable of the same type, instead of doing a self-assignment, then it knows that base is of type A, and can access the member field.

**Comment by lrhn** [comment]
This is what the language specification requires.
The "type promotion" of `base` to be `A` insider the statement guarded by `base is A` only applies if there is no assignment to `base` inside the statement.

That means that the static type of the second `base` in `base = base.member` is still `Base` - it's not promoted to `A` because of the assignment. The language specification requires a warning here.

**Comment by BlackHC** [comment]
But but... shouldn't the inferred types only be dismissed after the assignment? The language specification should maybe be worded differently then? Ie what is the intention here?
