### ISSUE TITLE
Analysis Server search_getTypeHierarchy() says that class is a subclass of itself

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24866]
Consider this code and ask Analysis Server to search_getTypeHierarchy() for class `SomeClass`.
```
class SomeClass {}
class Mixin1 implements SomeClass {}
class Mixin2 extends SomeClass {}
class Interface1 implements SomeClass {}
class Interface2 extends SomeClass {}

class Foo extends SomeClass
    with Mixin1, Mixin2
    implements Interface1, Interface2 {}
```
Result includes class Foo as a subclass of itself:
![image](https://cloud.githubusercontent.com/assets/4499789/11061420/15df4c56-87b8-11e5-87c8-b69b11df4918.png)
As a result IDE shows confusing tree:
![image](https://cloud.githubusercontent.com/assets/4499789/11061353/84ab71e2-87b7-11e5-919b-fd48390368ca.png)

**Comment by scheglov** [comment]
I believe the problem has been already fixed in https://github.com/dart-lang/sdk/commit/a19b2985dcee58b92a5324842051b72642793e4b .

I've opened a merge request for it now.
https://github.com/dart-lang/sdk/issues/24906


The test case works fine for me now.
![image](https://cloud.githubusercontent.com/assets/384794/11132300/0ac3c508-8944-11e5-9d2c-ddee6e3280a2.png)
