### ISSUE TITLE
Analyzer reports errors on reference-before-declaration for dart-doc comments.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#24880]
```
main() {
  /// [a] is a variable.
  var a;
}
```

Gives an error: Local variables cannot be referenced before they are declared.

I guess it is underspecified, but it seems to be desirable to be able to mention the variable declared in the documented declaration.

**Comment by lrhn** [comment]
The specification does not specify the scope of a comment preceding a local variable declaration, so I agree it's not a spec violation. It's still wrong. Generally the scope is chosen so that it allows you to describe the visible features of the commented element (members of a class, parameters of a function). It should be possible to refer to the commented variable itself.

**Comment by askeksa-google** [comment]
The analyzer no longer produces an error in this case.
