### ISSUE TITLE
Add a diagnostic service to allow clients to subscribe to server logging streams.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#24901]
Essentially we want a way for clients to register interest in logging information from the server.  Potentially, we want some kind of level idiom (`info` or `fine`/`finer`).

In short order we want to do away with hacks like https://github.com/dart-lang/sdk/issues/24900 where for expedience we're using an error notification to carry what is really just information.

**Comment by devoncarew** [comment]
Would love to have this on a general purpose `diagnostics` domain :)

**Comment by pq** [comment]
> Would love to have this on a general purpose diagnostics domain :)

:+1:

**Comment by devoncarew** [comment]
Thoughts on this? Is it important to add this to the `diagnostic` domain, or does the existing `server.error` stream work ~well enough for this purpose?

**Comment by pq** [comment]
> does the existing server.error stream work ~well enough for this purpose?

Not as it's defined but maybe that's a better place to look.  What we *really* want is something like `server.info`.

**Comment by bwilkerson** [comment]
In my mind, the question is what kind of information are we passing back and why?

In the case of #24900, this is a short term work-around. The longer term goal is to remove the need to run `pub list-package-dirs` entirely, at which point we won't need the notification. I'm sort of ok with using `server.error` for short-term solutions in order to avoid creating new API that won't be needed very long (well, depending on your definition of "long").

Is there other information that we think it's useful to pass back to clients?

**Comment by kevmoo** [comment]
@pq Are we running on this for 1.14?

**Comment by pq** [comment]
@kevmoo : not for 1.14...

**Comment by pq** [comment]
Closing as stale.
