### ISSUE TITLE
drop unmangled names if requested or if they are not needed

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24976]
We seem to keep around the unmangled names of symbols, regardless of whether they are needed. For example, `#foo.toString()` will make us keep the name "foo" in the generated code. Even if you use `@MirrorsUsed(symbols: const [])` to specify that no symbol name is needed.

Can we drop the unmangled name in this case?
Could we provide some short hand to help our users specify this intention without having to import `dart:mirrors` just for this?

This would allow developers to use symbols as const uuids.

**Comment by tbosch** [comment]
+1 (from the Angular team)

**Comment by ochafik** [comment]
Note that it seems weird that a symbol retrieved from noSuchMethod (through Invocation.memberName) is mangled, while a symbol created with the hash syntax isn't.

I would favour equality of treatment between all symbols: toString shouldn't ever print the unmangled name, that's what [MirrorSystem.getName](https://api.dartlang.org/133732/dart-mirrors/MirrorSystem/getName.html) is for.

In other terms, the criteria to decide to keep symbol's unminified names should be "is MirrorSystem.getName" used anywhere in the program, rather than "is Symbol.toString()" used, which is impossible to tell for sure anyway.
