### ISSUE TITLE
1.13 -> window.console.log of Dart Object

### ISSUE THREAD

**Issue by pinnisi** [dart-lang/sdk#25006]
I used to window.console.log on my objects to debug, but since latest update I only get "DartObject" on console.
![cattura](https://cloud.githubusercontent.com/assets/9946496/11298426/1cf39abe-8f7f-11e5-881f-f1eab37e19be.JPG)

**Comment by kevmoo** [comment]
@pinnisi Is this in Dartium or in Chrome?

**Comment by pinnisi** [comment]
Dartium
Il 20/nov/2015 18:32, "Kevin Moore" <notifications@github.com> ha scritto:

**Comment by alan-knight** [comment]
Yes, that's printing the JS wrapper instead of the Dart object.

A workaround is

      window.console.log(myObject.toString())

**Comment by kevmoo** [comment]
@alan-knight is this cherry-pick worthy for 1.14? Can we get this fixed in 1.15?

**Comment by jacob314** [comment]
The fix for this issue needs to be done in webkit C++ code and there would likely be significant merge conflicts in the fix moving from 39 to 45 given files known to be renamed or refactor in webkit for that time range. Unless it is extremely high priority I would recommend moving this to 1.15.
There would be a half baked solution for this that would be fine to do for 1.14 but it would result in objects that kinda display correctly in console but look a bit different than other Dart objects displayed in dartium debugger.

**Comment by kevmoo** [comment]
I'm going to bump to 1.15 – we should make sure we track this early in the next milestone, though.

**Comment by jacob314** [comment]
Grabbing this bug as it is Dartium debugger related.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by jacob314** [comment]
This is fixed in 1.15.
