### ISSUE TITLE
webgl call vertexAttribDivisorAngle does not work when transpiled to JS and run on firefox

### ISSUE THREAD

**Issue by muth02446** [dart-lang/sdk#25020]
To reproduce clone 

https://github.com/rhulha/ChronosGL

and try the instancer example 
https://github.com/rhulha/ChronosGL/blob/master/example/instancer.html

**Comment by kevmoo** [comment]
@muth02446 is this API implemented on Firefox?

Which version of Firefox are you testing?

**Comment by alan-knight** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Using_Extensions

I think at a minimum you'd need the webgl.enable-draft-extensions flag set.

**Comment by alan-knight** [comment]
So the problem on Firefox is 
> receiver
ANGLE_instanced_arrays {  }
> receiver.constructor
function Object()
> J.getInterceptor$x(receiver)
Object { ^: "JavaScriptObject;", constructor: UnknownJavaScriptObject(), $isUnknownJavaScriptObject: UnknownJavaScriptObject() }
> receiver.constructor.prototype
Object { , 15 more… }

So the receiver ANGLE_instanced_arrays has constructor Object and we're not getting a useful interceptor for it. It does have __proto__: ANGLE_instanced_arraysPrototype, but no constructor.
@rakudrama

**Comment by alan-knight** [comment]
After discussion with Stephen, I think it would be possible for dart2js to also look at the prototype if the object just has Object as a constructor. In the short term, it should be possible to do a workaround, although it's pretty ugly. Basically, if the object looks like the expected Dart type (non-Firefox browsers), do Dart things. Otherwise, use JS interop.

```
      var ext = gl.getExtension("ANGLE_instanced_arrays");
      if (ext is AngleInstancedArrays) {
        ext.vertexAttribDivisorAngle(index, 1);
      } else {
        ext = new JsObject.fromBrowserObject(ext);
        ext.callMethod("vertexAttribDivisorANGLE", [1]);
    }
```

**Comment by muth02446** [comment]
I tried to get the workaround to work but the furthest I got was that were no errors in the console but also nothing drawn to the screen.

**Comment by alan-knight** [comment]
I really don't know enough about WebGL to know if that's the workaround failing or if there's just some different problem. What happens if you just do that in JavaScript? So, if it's something that only happens once or a couple of times, comment out that line in the Dart sources and replace it with debugger(); or a print statement where you put a breakpoint or something. When it gets there, manually call that operation in JS. See if that fixes the problem. Or if it's something that's called too often for that, do a pub build, edit the compiled output and replace that line with manual JS that calls the operation.

If that makes the appropriate things draw, then there's a problem with the workaround. If it doesn't, then it probably indicates there's something else that's not working in Firefox.

**Comment by muth02446** [comment]
This is still broken with FF 45 and dev channel dart sdk 1.16

**Comment by muth02446** [comment]
This works in firefox 48.0
