### ISSUE TITLE
DartAnalyzer stops working from time to time / autocompletion in IntelliJ fails

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25039]
It's still the same like in #24812 
The scanning process is much faster now but it still stops / hangs from time to time. Time to time means here about 5 or 6 times per day.

**Comment by kseo** [comment]
Also in WebStorm.

**Comment by scheglov** [comment]
Is the DAS process alive when you stop getting completion and navigation?
Try to use the following to find all the DAS processes `ps -jax | grep IntelliJ_IDEA`.

Unfortunately the issue as it is now is not actionable.
Without additional information in form of test cases we can reproduce or at least logs... there is nothing we can do :-(

**Comment by MikeMitterer** [comment]
As you can see - DA is running.
You probably also saw in the logs that it's not a DA-crash. In my opinion DA doesn't recognize code-changes correctly. Before I made the SS I added a new dart-file via IJs File/New/<from file template>
This template contains one main class and 3 private classes. After this DA stopped working.

![screenshot-1941](https://cloud.githubusercontent.com/assets/116654/11419081/6f09f9b0-9425-11e5-931b-de37b223d9ad.png)

**Comment by MikeMitterer** [comment]
I tried the same thing again after restarting IJ - now it worked! 
But check out my video: http://www.mikemitterer.at/fileadmin/_temp_/da-bug-v2.mp4 
At 4:59 you can see that DA is not able to resolve HtmlElement As you can see the mdl-package is a LOCAL-Package!!! Could this be a problem for DA? As you can see I tried several things but nothing helped. At this time DA is still working (right terminal)
From 8:33 on - DA stopped working!

**Comment by MikeMitterer** [comment]
@bwilkerson Why did you set these Analyzer-Problems (#25035 or #25046 | #24611 ) to priority medium or they are not assigned at all (as @alexander-doroshko just pointed out)

If you have to work with an IDE where the autocompletion doesn't work or at least stops working 5 or 6 times a day this drives you (at least me) crazy!!!! I really like Dart because of it capabilities but because of such things I really regret that I haven't set on JS6 or TS. DA is a central component also for other IDEs  - solving all the issues should have the highes possible priority - *not medium*

**Comment by bwilkerson** [comment]
> Why did you set these Analyzer-Problems (#25035 or #25046 | #24611 ) to priority medium? Some of them are not assigned at all (as @alexander-doroshko just pointed out) ... DA is a central component also for other IDEs - solving all the issues should have the highes possible priority - not medium

If everything were marked with the same priority, then the priority would be meaningless. :-)

There is no simple rule for assigning priority, but there are a number of factors. We tend to assign a higher priority to issues that are caused by an exception being thrown than to other issues because exceptions frequently leave the server in an inconsistent state, which leads to other, sometimes seemingly unrelated, problems. The frequency of the occurrence of the issue is also a factor.

I understand your frustration, and hope that we can quickly resolve the issues you're experiencing. We are working to solve all of our issues as quickly as possible. I assure you that a priority of "medium" does *not* mean "unimportant" or "should be ignored indefinitely".

**Comment by scheglov** [comment]
At 4:25 or so I see that IDEA sent `analysis.setSubscription` with `NAVIGATION` and `HIGHLIGHTS` services, but it got back just empty navigation notification.
![image](https://cloud.githubusercontent.com/assets/384794/11477885/e3f13146-973e-11e5-85b5-11d7163af1d0.png)
Also analysis was "done", but the rest of notifications were not sent anyway.
Usually this means that there was some exception during analysis.

Could you please follow this [document](https://docs.google.com/document/d/1s4PTof1x7RyxXYX1yO31ByvZsQoDMM7edFIW1SKP25U) and enable `idea.fatal.error.notification=enabled`? These exceptions might have been logged into the instrumentation log, but it's hard to catch on the video.

I also see at 13:56 or so that the DAS process stopped logging anything, but continued to use CPU. So, it was probably in the infinite loop. Again, the same document may help to find out why. Basically probably this part of the code will be visible in `CPU Profile` in Observatory.

Unfortunately when DAS is in an infinite loop, its HTTP server does not work, because it is served by the same isolate as analysis, which is... busy.

**Comment by alexander-doroshko** [comment]
Note that even with `idea.fatal.error.notification` disabled errors are logged in idea.log files (Help | Show Logs), so @MikeMitterer can check log files. 
`idea.fatal.error.notification` makes errors more visible in the IDE and allows to report to JetBrains. `idea.fatal.error.notification` is always enabled in EAP builds.
We already have a bunch of DAS traces in our JetBrains database reported by @MikeMitterer. I've sent them to @scheglov by email. Thanks Mike for reporting them! If there are any that you didn't report, you'll find them in idea.log files.

**Comment by MikeMitterer** [comment]
If you want/need more logs - here are they from today: http://www.mikemitterer.at/fileadmin/_temp_/idea-log-151201.zip

I pick out this exception from 14:38 (my time - GMT+1) - see below.
I don't know if it's relevant or not but I am curios...  - this FileSytemException (.../samples/spa_todo/build/web/) can happen if I "pub build" (on the cmdline) while DA is analyzing in the IDE - but this should not be an extraordinary use case...
```
Dart analysis server, SDK version 1.13.0, server version 1.12.0, FATAL error: Failed to handle request: {clientRequestTime: 1448956052309, params: {included: [/Volumes/Daten/DevLocal/DevDart/BeanValidator.Dart, 

[!!! HERE I HAD TO CUT OUT THE DIR-LIST BECAUSE IT WAS WAY TO LONG FOR THIS POST !!!]

/Volumes/Daten/DevLocal/DevDart/WebApp.Base.UI.MDL/tool/templates, /Volumes/Daten/DevLocal/DevJava/MobileAdvertising/classes], packageRoots: {}}, method: analysis.setAnalysisRoots, id: 3}
FileSystemException: Directory listing failed, path = '/Volumes/Daten/DevLocal/DevDart/MaterialDesignLiteSite/samples/spa_todo/build/web/' (OS Error: No such file or directory, errno = 2)
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:913)
#1      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:715)
#2      _rootRunBinary (dart:async/zone.dart:930)
#3      _CustomZone.runBinary (dart:async/zone.dart:818)
#4      runZoned.<anonymous closure> (dart:async/zone.dart:1220)
#5      _CustomZone.handleUncaughtError (dart:async/zone.dart:784)
#6      _nullErrorHandler (dart:async/stream_impl.dart:575)
#7      _rootRunBinary (dart:async/zone.dart:926)
#8      _CustomZone.runBinary (dart:async/zone.dart:818)
#9      _CustomZone.runBinaryGuarded (dart:async/zone.dart:724)
#10     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#11     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#12     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#13     _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:396)
#14     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:331)
#15     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:395)
#16     _BroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:267)
#17     _rootRunBinary (dart:async/zone.dart:926)
#18     _CustomZone.runBinary (dart:async/zone.dart:818)
#19     _CustomZone.runBinaryGuarded (dart:async/zone.dart:724)
#20     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#21     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#22     _DelayedError.perform (dart:async/stream_impl.dart:606)
#23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#25     _rootRun (dart:async/zone.dart:903)
#26     _CustomZone.run (dart:async/zone.dart:802)
#27     _CustomZone.runGuarded (dart:async/zone.dart:708)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#29     _rootRun (dart:async/zone.dart:907)
#30     _CustomZone.run (dart:async/zone.dart:802)
#31     _CustomZone.runGuarded (dart:async/zone.dart:708)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#34     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:199)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

**Comment by scheglov** [comment]
It seems that this is the only exception in the logs.
I've opened a new issue against the `watcher` package.
https://github.com/dart-lang/watcher/issues/20

**Comment by MikeMitterer** [comment]
Thanks! 
I experienced again a very strange behavior: www.mikemitterer.at/fileadmin/_temp_/DA_ignores_test.mp4
In this case DA analyzes something but it doesn't show the result on the frontend (IJ)

Second thing is that if I `ps aux | grep dart` it doesn't show the port anymore...
![screenshot-1942](https://cloud.githubusercontent.com/assets/116654/11527208/cdf966a4-98df-11e5-894b-ba973386864f.png)

**Comment by scheglov** [comment]
Yes, I see that DAS doesn't send errors for the file.
Unfortunately I don't know why.
I can only guess that it might be a bug and there is an exception logged.
But without additional information there is nothing we can do.

Yes, `--port` was removed from DPI by default, because it was a potential security hole - anyone logged on the same machine could access it. You would need to enable it manually as described in the [document](https://docs.google.com/document/d/1s4PTof1x7RyxXYX1yO31ByvZsQoDMM7edFIW1SKP25U). And yes, enabling the port could provide us with additional information, like errors associated with the `basicevent_test.dart` file.

**Comment by MikeMitterer** [comment]
I've enabled the port. There is no error, no exception - but DA ignores my request.
Check out the video: http://www.mikemitterer.at/fileadmin/_temp_/da-does-not-resolve.mp4

[Analysis Server - Cache Entry-2.pdf](https://github.com/dart-lang/sdk/files/50576/Analysis.Server.-.Cache.Entry-2.pdf)
[Analysis Server - Cache Entry.pdf](https://github.com/dart-lang/sdk/files/50577/Analysis.Server.-.Cache.Entry.pdf)

**Comment by MikeMitterer** [comment]
![screenshot-1950](https://cloud.githubusercontent.com/assets/116654/11585682/03d74cca-9a6e-11e5-9287-10efceb7827f.png)

[MaterialObserve.dart.zip](https://github.com/dart-lang/sdk/files/51812/MaterialObserve.dart.zip)
```
         Dart analysis server, SDK version 1.13.0, server version 1.12.0, error: Failed to index: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/lib/src/directive/components/MaterialObserve.dart
         The null object does not have a getter 'nameOffset'.
         NoSuchMethodError: method not found: 'nameOffset'
         Receiver: null
         Arguments: []
         #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
         #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
         #2      IndexableElement.offset (package:analysis_server/src/services/index/indexable_element.dart:47)
         #3      ElementCodec.encode2 (package:analysis_server/src/services/index/store/codec.dart:111)
         #4      LocationData.LocationData.forObject (package:analysis_server/src/services/index/store/split_store.dart:587)
         #5      IndexNode.recordRelationship (package:analysis_server/src/services/index/store/split_store.dart:522)
         #6      SplitIndexStore.recordRelationship (package:analysis_server/src/services/index/store/split_store.dart:990)
```

**Comment by MikeMitterer** [comment]
The more I see from DA internals the more I come to the conclusion that DA doesn't hang. It is just so inefficient that it looks like if it would hang. If DA is on 100% it takes about 20secs until IJ updates it's view (editor tab) according to what DA found. Everytime after I "pub update" DA goes up to 100% and rescans the filelist. As said in other postings - no caching and doing the same work over and over again this makes DA look so bad!

**Comment by scheglov** [comment]
1. How do you know that DA rescans files? :-)

2. DA analyzes the current file (we call it a priority file) first, and the rest - later. So, even though full analysis may take long time, for the current file should get results quickly. That said, slow displaying analysis errors in IDEA may be related to using `analysis.getErrors` request instead of listening for `analysis.errors` notification. There is nothing you can do now, but @alexander-doroshko thinks that this may be something to fix in the next version of the Dart plugin.

3. I agree that analyzing the same files multiple times is bad. @stereotype441 works now on what we call `summaries`, which should speed up analysis, use caching and enable sharing, even between packages.

**Comment by MikeMitterer** [comment]
2 + 3 Looking forward to see these things implemented - cool + Thanks!
1 - just a guess :-)) but what else is it doing? It does not write log infos - it just sits there and consumes processor power...

**Comment by scheglov** [comment]
For the cases when DA just sits and does not log anything, I would *love* to see Observatory CPU information.

1. Open Observatory.
2. Go to the `cpu profile` page. Wait for it.
3. `Clear` the existing state.
4. Do what causes DA to just sit and do nothing, if this is `pub update`, it is hopefully easy to reproduce.
5. At the moment when DA start writing to logs after a period of doing nothing visible, hit the `Refresh` button.
6. Expand the profile. This is something hard to describe how to do, I need to rely on your help. In general if something uses much CPU it is worth to expand - it will let us know from where it is called. If there are two or three paths where the most CPU is used, expand all of them.
7. Print the page into PDF and send it to us.

**Comment by scheglov** [comment]
Not reproduced, don't know if solved.

**Comment by ened** [comment]
How do you run dartanalyzer through the observatory?

**Comment by ened** [comment]
@scheglov this is on 2.0.0-dev.65.0 - dart analyzer keeps burning 100% CPU on my project. VS Code completion / IntelliSense therefore broken.

[Dart VM Observatory.pdf](https://github.com/dart-lang/sdk/files/2140918/Dart.VM.Observatory.pdf)

**Comment by ened** [comment]
In my case, this was fixed by setting the analysis_options.yaml file to:

```
analyzer:
  exclude: 
    - ios/.symlinks
```

So it seems the new .symlinks structure is not yet compatible with DA, once DA is run as a daemon.
