### ISSUE TITLE
Add way to inhibit warnings/hints locally.

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25051]
I know there is already a closed ticket #23872 for this but it's so annoying. I have this problem over and over again. (Intellij/ Dart plugin)

Like in this code:
```dart
    String _getFilename(html.Blob blob) {
        Validate.notNull(blob);
        if(blob is html.File && (blob as html.File).name.isNotEmpty) {
            return blob.name;
        }
        return filename;
    }
```
Maybe sometime in the future DA is able to resolve this but we need the solution NOW.
In Java I can turn off warnings via code comments - can't you provide a similar thing for DA?

**Comment by lrhn** [comment]
The warning is correct and the cast is unnecessary - according to Dart semantics and the analysis server's analysis - so your actual problem is that you need to use a tool that doesn't work well without the otherwise unnecessary cast, and you want to be able to keep the cast (at least until the tool is fixed) without being overburdened by warnings. 
That is, you want to inhibit some (but not all) hints provided by the analyzer, in some way.

I don't think there currently is a way to do this, so making this an enhancement request for the analyzer.

**Comment by MikeMitterer** [comment]
This is an old problem and it's not just one or two warnings in my case - I get about 30 or 40 of them for my whole project - this pollutes the Analyzer-Output-Window in IntelliJ and makes it almost unusable.

Here is the Java-way: http://www.codejava.net/java-core/the-java-language/suppresswarnings-annotation-examples 

Warnings and hints are great but sometimes they can't be controlled globally.

I'm afraid that no one takes care about this problem (no priority, nobody assigned...) - the analyzer has a lot of other problems which should be fixed before this one.

**Comment by devoncarew** [comment]
The analyzer now supports an `// ignore: issue_code` syntax. Here's an example: https://github.com/flutter/flutter/blob/d9916bbb337ecc4968a175792d11edbe76af991d/packages/flutter/lib/src/services/activity.dart#L26

/cc @pq

**Comment by pq** [comment]
For a bit more background on this support see: 

https://docs.google.com/document/d/1YJCkxnklLR2aKzQUrp6cWmqk7yUhfJwtaXIGcjZIk-Y/edit
