### ISSUE TITLE
Specification: unclear conditional property extraction

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25087]
Dart Language Specification (3rd Edition, June 2015) contains the following text (16.18 Property Extraction)
"One might be tempted to conclude that for e != null, e?.v is always equivalent
to e.v. However this is not the case. If e is a type literal representing a type with
static member v, then e.v refers to that member, but e?.v does not."

It's unclear what should (or may) be returned by e?.v in the case described above.
```dart
class C {
  static String id1() => "id1";
  static String get id2 => "id2";
  static String id3 = "id3";
}

main() {
  print(C.id1 == C?.id1); // prints true
  print(C.id2 == C?.id2); // prints true
  print(C.id3 == C?.id3); // prints true
}
```
Tested on Dart VM version: 1.14.0-dev.1.0 (Wed Nov 18 18:17:16 2015) on "windows_x64"

Please describe the case when e.v is not equivalet to e?.v (when e != null) or remove this text from the specification

**Comment by lrhn** [comment]
The text describes the case, what you are seeing is the VM (and dart2js and the analyzer) not implementing the spec as written.
The VM should have thrown on `C?.id1` because the `Type` object for `C` does not have an `id1` getter.
Dart2js gives the same result as the VM, and the analyzer does not warn that `Type` doesn't have an `id1` member.

(The implemented behavior is much more useful and predictable, so maybe the spec should change to match that instead of the other way).

**Comment by sigmundch** [comment]
This was actually changed in the latest draft of the spec - I believe the current behavior is the behavior we want to support in the future (see https://github.com/dart-lang/sdk/commit/b11670f89924c1961be8f93d00848c7fa9887f99)

/cc @gbracha

**Comment by sgrekhov** [comment]
Now behaviour is according the new spec. Closed
