### ISSUE TITLE
In dart:core Uri, queryParameters is a Map, while it should be Multimap

### ISSUE THREAD

**Issue by mtayseer** [dart-lang/sdk#25199]
Code to reproduce

```dart
var uri = Uri.parse('http:/google.com?a=1&b=2&b=3');
print('${uri.queryParameters}'); 
// Output {a: 1, b: 3}, while it should be {a: 1, b: [2, 3]}, or {a: [1], b: [2, 3]}
```

This is needed in the case that I've \<select multiple> in my form.

**Comment by lrhn** [comment]
True. Currently you have to encode the query part manually if you have more than one element with the same key.

We don't have a MultiMap class, and changing the interface at this point would be a breaking change. To support this we may need to add new parameters/getters that handles multiple occurrences of the same key properly.

**Comment by mtayseer** [comment]
I believe we can introduce a `MultiMap`/`ParametersMap` class. 

The behavior should be that `uri.queryParameters['b']` returns `1`, and `uri.queryParameters.getAll('b')` returns `[1, 2]`

[Java](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getParameter(java.lang.String)) & [Werkzeug](http://werkzeug.pocoo.org/docs/0.11/datastructures/#werkzeug.datastructures.MultiDict.get) provide similar APIs

**Comment by lrhn** [comment]
Adding a multi-map now for `Uri.queryParameters` would be a breaking change.
We already have a behavior for `uri.queryParameters["b"]` (returning 3 probably) which would change if we made it return a list.

I'm afraid we will need a separate getter that returns a `Map<String,List<String>>` (or, potentially, a multimap like you describe). I'm still looking for a good name for that getter since `queryParameters` is used.

**Comment by mtayseer** [comment]
If we keep the same behavior of `uri.queryParameters["b"]`, change the type to `ParamsMap<String, String>` (which inherits `Map<String, String>`), is it still a breaking change?

**Comment by lrhn** [comment]
No, I don't think that would be breaking. I've had similar thoughts, but have rejected them so far.

It's problematic if anybody anywhere has implemented the `Uri` interface, but that's not really likely (and all the other changes we have made to Uri has had the same problem).

The returned map must be a full map, with extra functionality on top.
That means that we introduce a new type, the `ParameterMap` which extends `Map` with extra functionality (like perhaps an `Iterable<String> allValues(String parameterName)`). 
The forEach and keys/values iterables must still match the existing map operations, so any operations on the full value sets must be extra operations, which means learning a new API to use them, instead of just having a Map<String, Iterable<String>>.

It's not out of the question - we have done the same thing in other cases (Runes.iterator extends Iterator) - but it's something we try to avoid it if there is a better alternative to be found. The fewer types users need to concern themselves with the better.

In this case, I'm not convinced there is a better alternative, so I'll see if this can be made to work meaningfully.

**Comment by lrhn** [comment]
There is now a `Map<String, List<String>> get queryParametersAll` that gives access to all the parameters.
