### ISSUE TITLE
DartDoc output for IOSink looks funny

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#25196]
Dartdoc: https://api.dartlang.org/1.13.0/dart-io/IOSink-class.html
Source: https://github.com/dart-lang/sdk/blob/9f8da952179ef1b7a2d9ac06da5e48c0efa1d333/sdk/lib/io/io_sink.dart#L8

Markdown: [StreamConsumer<List<int>>]
Output: StreamConsumer>

**Comment by jtmcdole** [comment]
Huh, github choked on it as well. its StreamConsumer<List<int>>

**Comment by jtmcdole** [comment]
...
StreamConsumer\<List\<int\>\>

**Comment by floitschG** [comment]
We have to decide if dartdoc should support this use case (which apparently is not valid markdown) or not.

/cc @lrhn @keertip

**Comment by lrhn** [comment]
I'm not sure dartdoc should support it. The square brackets means that the content is a reference to a declaration, and if you include the type parameter, it's not longer that - it's just a piece of code.

On the other hand, rejecting any input is hard for dartdoc since we probably don't want to block the generation of the remaining docs. I would suggest that any square-bracket link where the content isn't a reference to a declaration (a qualified identifier, optionally prefixed by "new  " to refer to the default-named constructor rather than the class), dartdoc should emit a warning and treat it as a code segment (like it was backquote-delimited).

**Comment by floitschG** [comment]
I think we can keep it the way it is (same behavior as github), and just update the comment.
I uploaded a CL.

**Comment by srawlins** [comment]
This is fixed.
