### ISSUE TITLE
There is no defaultValue/defaultChecked setter & getter on *InputElement

### ISSUE THREAD

**Issue by unsacrificed** [dart-lang/sdk#25213]
InputElement has defaultValue&defaultChecked setter&getter. But specialized *InputElement does not have (i.e. no defaultValue in TextInputElement, no defaultCheck in CheckboxInputElement). It is annoying in some cases.

**Comment by unsacrificed** [comment]
Also, why where is no something like minAsNumber and maxAsNumber in NumberInputElement (but valueAsNumber exists)?

**Comment by alan-knight** [comment]
I can see defaultValue is confusing. It shouldn't prevent you from doing anything because TextInputElement is abstract, and the instance you get is always an InputElement. But it might confuse the type checking. There's some tension with having a bunch of different classes on top of something that's a single instance with a mutable type in JS.

For minAsNumber and maxAsNumber those are probably reasonable, but we're trying to not be in as much of the business of adding methods (and thus code size) on top of the DOM.

**Comment by unsacrificed** [comment]
Thanks for explanation.
Is it possible to create my own subclass from InputElement (or should I use another class?) for:
1. defining additional methods (minAsNumber).
2. defining custom constructors (something like MyOwnTextInputElement, but without type checking issue so constructor return MyOwnTextInputElement, not InputElement).
At least I don't know how to construct parent.

**Comment by zoechi** [comment]
You can create a custom element like Polymer does, but also without Polymer but you need to load the polyfills to support other browsers tha Chrome. 
The best example I found is http://stackoverflow.com/questions/26820844/registering-custom-element-in-dart-lang/26823139#26823139

**Comment by unsacrificed** [comment]
IMHO, creating custom element is overkill. I just want to have more consistent api and avoid type issue. PS: I use my own functions to accomplish it for now.

**Comment by alan-knight** [comment]
You can't just create a subclass. For example, if you do a document.query the system wouldn't know to return an instance of your subclass. And constructing the parent is tricky, because you expect it to create something that the browser recognizes. That's what a lot of the complexity in custom elements is about.
Defining your own functions works, but is not that convenient. You could also define a JQuery style wrapper that wraps the object and adds methods, but it's also not so convenient. We don't, unfortunately, have an extension method mechanism at this point.
