### ISSUE TITLE
Strong mode analyzer ignores function types in conditional operator

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#25248]
Dart VM version: 1.14.0-dev.4.0.
This is OK:
```dart
typedef int ProcessFunction(int v);
int foo(int a) => a * 2;
int bar(int b) => b * 3;

ProcessFunction process;

void main() {
  var t = true;
  if (t) process = foo;
  else process = bar;
}
```
However this
```dart
typedef int ProcessFunction(int v);
int foo(int a) => a * 2;
int bar(int b) => b * 3;

ProcessFunction process;

void main() {
  var t = true;
  process = t ? foo : bar;
}
```
 results in `WARNING: t ? foo : bar (Function) will need runtime check to cast to type (int) → int`.

**Comment by leafpetersen** [comment]
There are two related issues here.  The first is that the analyzer (normal mode) does not currently implement least upper bound for function types, see:  #23381 and #23663  .

The second is that we shouldn't really be using the dart spec version of least upper bound, since it produces very bad results in lots of places.

https://github.com/dart-lang/dev_compiler/issues/288
https://github.com/dart-lang/sdk/issues/19425

Getting a DDC lub implemented is on my list of things to do fairly soon.

**Comment by jmesserly** [comment]
@leafpetersen is an improved LUB something we want to tackle in Q1?

**Comment by leafpetersen** [comment]
Yes.  It doesn't have to be complete, but the function case comes up surprisingly often, in addition to the EfficientLength kind of issue.

**Comment by jmesserly** [comment]
I've merged https://github.com/dart-lang/dev_compiler/issues/288 into this issue. There's some useful discussion on that bug, but the code is part of analyzer now.

**Comment by jmesserly** [comment]
I think @munificent fixed the first part (LUB in normal mode) ... I think we still need a strong-mode LUB, as the spec version is not sound.

**Comment by jmesserly** [comment]
merging this into https://github.com/dart-lang/sdk/issues/25802
