### ISSUE TITLE
Inexplicable errors with mixture of imports, typedefs, mixins, and callbacks

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25246]
This test has three files.

test1.dart:
```dart
import 'test2.dart';
class ConcreteClass extends Object with MixIn { }
void main() {
  new ConcreteClass().test();
}
```

test2.dart:
```dart
import 'test3.dart';
typedef _unused();
class MixIn {
  var test3 = new Test3(() { });
  void test() {
    test3.test();
  }
}
```

test3.dart:
```dart
class Test3 {
  final fn;
  Test3(this.fn);
  void test() {
    fn();
  }
}
```

If you run this by just calling `dart test1.dart' with the current stable SDK (1.13), on Linux, you get:

```
'file:///.../test1.dart': error: line 4 pos 22: unexpected token '.'
  new ConcreteClass().test();
```

**Comment by crelier** [comment]
As far as I can tell, the error occurs when the parser is trying to parse the anonymous closure passed as argument to Test3 on this line:
  var test3 = new Test3(() { });

For some reason, the parser thinks this closure is in script test1.dart instead of test2.dart, and it obviously finds unexpected tokens at the correct token position, but in the wrong script.

The closure is question has the internal name Object&MixIn_Object&MixIn._<anonymous closure>

I am reassigning to Matthias.

**Comment by travissanderson-wf** [comment]
I have run into this same issue and it appears to only reproduce if you have the mixin defined in a different file.  It works in one file as you can see in [dartpad]( https://dartpad.dartlang.org/57664b9e5aac26089b3c).  If you split it into a separate file, it seems to cause a parsing issue and gives seemingly unrelated error which makes debugging the issue almost impossible.  See [mixin_issue.zip](https://github.com/dart-lang/sdk/files/63462/mixin_issue.zip) - if you remove the import of 'mixme.dart' and put the mixin definition in main.dart, it will run.  Otherwise you get something like this:
```
$ dart main.dart
'mixin_issue/main.dart': error: line 4 pos 23: unexpected token ';'
	var test = new Test();
                      ^
```

**Comment by iposva-google** [comment]
@crelier Based on the workaround which was identified by @a-siva and your analysis it is pretty clear that the closure is being created with the wrong owner class. I am wondering whether this is a problem only in field initializers or whether this is a more common problem.

@Hixie regarding the pattern of using an empty closure by writing it out everywhere such as "() {}": Not sure whether this is only in the example code provided or generally used, but it would be beneficial to allocate a single closure object and assign it to a static. This way you only define a single function instead of at every source location where you repeat that pattern.

**Comment by Hixie** [comment]
@iposva-google Thanks. In this case it was just for the example (the original code is a sorting function for a HeapPriorityQueue).

**Comment by mhausner** [comment]
https://codereview.chromium.org/1533823004/

**Comment by mhausner** [comment]
Committed patchset #2 (id:20001) manually as
8293e9665b8cf08615098e61236097bfccdedcfd (presubmit successful).
