### ISSUE TITLE
ARM Glibc 2.11 and Dart VM

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/sdk#25256]
How would I build a Dart VM for ARMv5TE (Dreamplug) which has a glibc version of 2.11?

Static builds of the Dart VM no longer work under different glibc versions due to BoringSSL due to uses of getaddrinfo() and other such symbols.

**Comment by kaendfinger** [comment]
@zanderso @rmacnak-google

**Comment by whesse** [comment]
It should be easy to disable BoringSSL compilation in the by setting variables in the .gyp files.  This is what we do when we build Dartium.  

Setting 'dart_io_secure_socket%': 1 instead of 0 in runtime/tools/gyp/runtime-configurations.gypi should stop the compilation and linking of the boringssl code.

After making the change, you need to do gclient runhooks again, to run gyp, to make new build files.

**Comment by kaendfinger** [comment]
@whesse Thanks. Is there a solution that will allow me to keep BoringSSL and compile under glibc 2.11? I have tried multiple solutions:
- Ubuntu 14.04 and compiled glibc 2.11 and tell compiler to use it
- Ubuntu 10.04 with already installed glibc 2.11 (Issue here seems to be no ARMv5TE cross compiler toolchains that have glibc 2.11)
- Compiling directly on the device (Slow, old GCC 4.2 or GCC 4.4 compiler doesn't seem to work with Dart)
- Statically linking glibc into the binary (no longer works after BoringSSL)
- Building a custom glibc with `--enable-static-nss`, installing on Ubuntu 14.04, and compiling with `-static`

**Comment by whesse** [comment]
It sounds as if you know as much about this as I do, so I can only suggest trying to build BoringSSL, directly, and see if it can run with that libc.  I think that BoringSSL may only support recent libc and OSs, since one of its goals is to be simpler and cleaner by removing older support code.  Only those platforms needed for chromium and android are actively supported by its maintainers.  See the repository at https://boringssl.googlesource.com/boringssl/+/master and file issues at chromium.org.

This is a pretty old architecture, and libc version, so I don't see us being able to do much to support it.

**Comment by zanderso** [comment]
@iposva-google

**Comment by kaendfinger** [comment]
@whesse Ok, thanks. Is one possible alternative to compile with OpenSSL instead? I'm not sure how drop-in OpenSSL is for BoringSSL, but I do know it's a fork. Thanks in advance :)

**Comment by whesse** [comment]
You could try building a version of Dart from before version 1.13, since those versions have OpenSSL, not BoringSSL.  Those aren't that old yet.  But new features and bug fixes will not get ported back to them.

**Comment by mraleph** [comment]
Assuming stale. Please reopen if it still matters.
