### ISSUE TITLE
Strong mode: runtime type checks, not consistent?

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25255]
The following seems not consistent to me:

![image](https://cloud.githubusercontent.com/assets/1035299/11791440/5e1fa52a-a2a1-11e5-8c51-339cba290964.png)

Not sure if this is an issue, or my lack of understanding of strong mode. 

It seems to me that `func1` also needs a runtime type check. Why do I only need it for `func2`?

**Comment by bwilkerson** [comment]
@leafpetersen

**Comment by jmesserly** [comment]
@kasperpeulen yeah you're right, it will need a runtime check either way. 

I think the idea was that `List<int>` type of checks are more likely fail, because generics often lose their types and end up as `List<dynamic>` in existing Dart code. Those types of checks will fail in strong mode at runtime.

But a lot of what we've done with inference and generic methods is precisely to avoid that problem. So I'm not sure if the distinction makes sense anymore. Thanks for filing this, we definitely need to revisit.

The code for this is here, BTW:
https://github.com/dart-lang/sdk/blob/2a190aa11aae93b6b85c1e0f826b8367ba02b255/pkg/analyzer/lib/src/task/strong/info.dart#L107

it's the difference between DownCastImplicit and DownCastComposite.

**Comment by kasperpeulen** [comment]
![image](https://cloud.githubusercontent.com/assets/1035299/23326522/9dee49d4-fafe-11e6-98f5-dc84a996648c.png)

seems fixed now with this setting:
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
