### ISSUE TITLE
Spec: Clarify implicit receiver use by closures

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25265]
Current the VM and dart2js will accept the following program. I think this program should be rejected because of implicit use of the receiver in the initializer of f. The VM and dart2js happen to optimize this away, but compilation errors should not depend on a particular implementation's optimizations.

class C {
   var f = () => 42;
}

main() {
  print(new C().f());
}

**Comment by sigmundch** [comment]
I don't believe this is an optimization - I believe we are detecting statically that there is no implicit access to the receiver in that closure. For example, this code would be optimized, but we will report an error that `g` cannot be used inside that initializer:

```dart
class A {
  var g;
  var f = () => false ? g : 3;
}

main() => print(new A().f);
```

**Comment by rmacnak-google** [comment]
The receiver is in scope, and a high quality implementation should be able reify the state of computation at any time. Removing it from the closure's context is an optimization.

**Comment by leafpetersen** [comment]
Hmm, I would say that removing it from the closure's context is part of the definition of safe-for-space closure conversion.  Closing over variables that are not referenced is a space leak.

**Comment by sigmundch** [comment]
I see - maybe then we can clarify what is the scope of a closure in an initializer.

If the scope includes the instance, I totally agree this seems like an optimization. However, we can alternatively say that all closures defined on initializers are like "static" closures, their scope doesn't include an enclosing class instance. That was my understanding of the spec thus far.

Regardless of how this is technically phrased: I hope we can continue supporting for this feature, since it is otherwise more boilerplate our users would need to write to initialize a closure.

**Comment by lrhn** [comment]
I don't see any implicit use of any receiver.
The declaration `var f = () => 42;` is evaluated in the initialization scope during object creation (before handling constructor parameters). The closure is evaluated in a scope where there is no access to `this`, but since it doesn't use `this`, that is not a problem. This is no different from:

```dart
var f = _createf();
static _createf() => () => 42;
```

which is perfectly fine.
(It is different in the sense that type parameters are available in the initialization scope, but not in the static scope, but there are no type parameters in the example).


The spec doesn't say what the initialization scope is exactly, it just says:

> A fresh instance (10.6.1), i, of class R is allocated. For each instance variable
> f of i, if the variable declaration of f has an initializer expression e<sub>f</sub> , then e<sub>f</sub>
> is evaluated, with the type parameters (if any) of R bound to the actual type
> arguments V<sub>1</sub>, . . . , V<sub>l</sub>, to an object of and f is bound to of . Otherwise f is
> bound to null.

So, instance field initializers are evaluated in a scope that contains type parameters, and at a time before `this` exists. This is the same scope that initializer list expressions are evaluated in (except without the constructor parameters), and it does not allow access to `this`.

**Comment by rmacnak-google** [comment]
If that's true, then this program should be accepted, with the toString interpreted as a top-level call.

class C {
  var f = () => toString();
}

main() {
  print(new C().f());
}

**Comment by lrhn** [comment]
The code
```dart
class C {
  var f = () => toString();
}
```
does indeed see `toString` as a top-level name *if it exists*. If there is no `toString` declaration in the static scope (there isn't) then it is interpreted as `this.toString`, which will then fail because `this` is available in the scope of the function.

If you add a `toString() => "x";` at top level, the program runs.

**Comment by rmacnak-google** [comment]
The rule for `toString()` becoming `this.toString()` only applies when `this` is in scope.

**Comment by lrhn** [comment]
No, the rule applies everywhere except in top-level and static functions
The function here is neither top-level nor static.

Maybe it should be changed to only apply when `this` is in scope, and maybe that was the intent and we just forgot that there are more cases than those two where you can't see `this` (constructors, field initializers, both of which are in a type-parameter scope but not an instance scope), but that's not what the spec currently says (section 16.14.3 - Unqualified Invocation).

**Comment by munificent** [comment]
Reassigning to area-specification because I don't think there's any actual language change being proposed here? Lasse, is there anything that needs to be clarified in the spec? If not, want to close this?

**Comment by lrhn** [comment]
I think it would be a good idea to not convert `x` to `this.x` in cases where `this` is not in scope. It gives lousy error messages. It should be possible to extend the cases where the expansion doesn't apply to also covert field initializers and initializer list expressions (and I think those are probably the only ones that need to be fixed).

**Comment by eernstg** [comment]
No milestone now: We may need to reword the treatment of `this` as Lasse mentioned, but this will not block Dart 2.

**Comment by eernstg** [comment]
Closing: As of 8fa22ea447303d5a544b1762c4bb5366b8634db9, the situations where implicit access to `this` occurs are specified in such a way that each potential error is mentioned, and the non-error cases are specified to be treated as if the access had used `this` explicitly. In particular, a function literal like `() => 42` is known to not contain any accesses to an enclosing object.
