### ISSUE TITLE
Strong mode can be extremely slow on some large projects

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25271]
A couple of large projects have observed extremely slow (orders of magnitude) slowdown running strong mode.  This bug is to track and diagnose this.

I've done some instrumentation of the batch mode analyzer, and what I see is that the individual tasks are not taking longer, but that we are re-resolving dramatically more compilation units.  So this might be a bad interaction with analyzer caching?  Not sure yet.  What I see is as follows.  

I've instrumented the BuildCompilationUnit task to log whenever it either builds a fresh compilation unit from source, or else pulls a compilation unit out of the cache and re-resolves it.  For a non-strong mode run, I see the following:

Compilation unit elements built: 2492
Compilation unit elements re-resolved: 9533
Unique compilation elements re-resolved: 2378

So there are 2492 compilation units, of which 2378 get re-resolved at some point, on average about 4 times each.

In strong mode, letting the process run for a couple of minutes and then killing it, I see:

Compilation unit elements built: 2492
Compilation unit elements re-resolved: 48811
Unique compilation elements re-resolved: 2378

So there are 2492 compilation units, of which 2378 get re-resolved on some point, on average about 20 times each.

I don't understand entirely what I'm seeing yet - at least all of the same compilation unit elements are being built and then re-resolved, but for some reason a huge number of compilation units are being repeatedly re-resolved.  This looks like it could be a bad cache interaction, but not sure yet.  I'm going to add instrumentation to see how many units are being completed.

@bwilkerson I don't totally understand what it means for a compilation unit element to be in the cache but need to be re-resolved.  Why does this happen?  Does this mean that something got evicted from the task model cache but not the analyzer cache?  There should be no invalidation happening, I don't think, since we are in batch mode.

cc @dgrove @skybrian

**Comment by skybrian** [comment]
Wild guess: there's a hard-coded parameter in driver.dart:

/// The maximum number of sources for which AST structures should be kept in the
/// cache.
const int _maxCacheSize = 512;

I don't know if that relates directly to resolved elements, but would bumping that up make a difference?

**Comment by bwilkerson** [comment]
> I don't totally understand what it means for a compilation unit element to be in the cache but need to be re-resolved. Why does this happen?

I'm not totally sure what you mean by "re-resolved", but that doesn't make sense to me either. If the compilation unit was flushed from the cache then it would also need to be re-parsed before being re-resolved. Could you send me a patch (or something) with the changes you've made in order to gather these numbers?

> Does this mean that something got evicted from the task model cache but not the analyzer cache?

If by "task model cache" you mean the results being stored by the work items, no, that isn't really a cache; nothing ever gets flushed, although the work item will be discarded if some result in the analyzer cache is invalidated.

> There should be no invalidation happening, I don't think, since we are in batch mode.

Agreed. It might be worth putting in a breakpoint (or something) where the cache state gets invalidated (in cache.dart on lines 352, 414, and 566) to verify that assumption.

> ... there's a hard-coded parameter in driver.dart ... I don't know if that relates directly to resolved elements, but would bumping that up make a difference?

I believe that that's dead code now. The new task model changed the way caching works. The number of AST's in the cache is now controlled by the AST_CACHING_POLICY. If it's working as expected, the max is currently set at about 630 AST's, which might well be too few.

@leafpetersen You could try changing the cache size by changing the AST_CACHING_POLICY. Pick the number of AST's you want and multiply by 13 to get the number to use in the constructor.

**Comment by leafpetersen** [comment]
I'll send you a patch by email.  The BuildCompilationUnitElement task (line 759 of dart.dart) either builds a new compilation unit (and does some level of resolution on it), or else pulls one out of cache, and calls the DeclarationResolver to re-associate some of the element model with the AST (I believe that this only re-creates the state that buildCompilationUnit leaves things in, and that subsequent re-resolution will happen as usual, but I'm not sure).  I'm calling the case where a new compilation unit gets built "Compilation unit elements built", and the case where the declaration resolver gets called on something pulled out of cache "Compilation unit elements re-resolved".

I added something to log when resolution is finished, and in the strong mode case nothing is reaching completion.  This suggests that we're doing a fairly breadth-first traversal of the project, which would definitely have bad cache behavior.  If this is the case, the question is whether this is because of something intrinsic to the project (e.g. everything is one massive library cycle), or if the tasks are just not getting scheduled in a cache friendly way.

I'll look at mucking with the AST_CACHING_POLICY when I get a chance to get back to this.

**Comment by bwilkerson** [comment]
> I believe that this only re-creates the state that buildCompilationUnit leaves things in, and that subsequent re-resolution will happen as usual, but I'm not sure

Correct.

> Compilation unit elements re-resolved

So yes, that would be the case where we've flushed the AST for a compilation unit and then determined that we still need it.

> This suggests that we're doing a fairly breadth-first traversal of the project ...

That's definitely possible. It would be interesting to know which tasks are causing us to have to recreate the resolved AST. We ought to be able to figure that out from the stack of work items currently being worked on.

Increasing the cache size will almost certainly help with this. It would also be interesting to know (a) how large the cache needs to be to avoid needing to recreate flushed ASTs, and (b) the largest cycle in this code base.

**Comment by leafpetersen** [comment]
One thought that I had last night:  we use code in the task model like the following to express a dependency requirement that certain tasks be run before certain others:

      // Require that full inference be complete for all dependencies of the
      // current library cycle.
      'orderLibraryCycles': LIBRARY_CYCLE_DEPENDENCIES.of(unit).toList(
          (CompilationUnitElementImpl unit) => RESOLVED_UNIT9
              .of(new LibrarySpecificUnit(unit.librarySource, unit.source)))

I believe that this will require the actual RESOLVED_UNIT9 AST to be present, and that this will force it to be re-computed if it is not in cache.  But my understanding is that the element model is never evicted, and in most cases I believe that all we care about is that the task has been run for the dependencies and the element model computed.  So re-resolving the unit itself would be wasted work.  If my understanding here is correct, then we might want to just track whether the unit has been computed, e.g. some sort of RESOLVED_UNIT9_COMPLETE target that doesn't get evicted very easily?

There are a few tasks which I think actually might need the RESOLVED_UNITs themselves, e.g. InferInstanceMembersInUnitsTask, but I'm not sure that this is a good idea in any case.  My sense is that at least that task should be re-structured to avoid traversing outside of the target unit.

**Comment by bwilkerson** [comment]
Excellent observation! I think you're absolutely right. We should perform a complete audit of the current tasks to make sure that they have the right dependencies. One way to empirically prioritize that task would be to get a list of the tasks that we are gathering resolved ASTs for at the point at which we have to re-create the ASTs.

> ... my understanding is that the element model is never evicted ...

That's true today, but I expect that to change when the summaries support is added (because it will be less expensive to recreate the element models when we need them).

> My sense is that at least [the InferInstanceMembersInUnitsTask] should be re-structured to avoid traversing outside of the target unit.

I don't know that it's necessary to be quite that restrictive, but we should definitely explore the possibility. There's a trade-off we need to be aware of: one way to remove the need for the AST is to store more data in the element model, but that increases the size of the element model, which is a problem at least until we can flush element models. We made that trade-off for evaluation of constants, and I'm OK with making it again, but we have to weigh the cost and benefit.

**Comment by jmesserly** [comment]
> There are a few tasks which I think actually might need the RESOLVED_UNITs themselves, e.g. InferInstanceMembersInUnitsTask, but I'm not sure that this is a good idea in any case. My sense is that at least that task should be re-structured to avoid traversing outside of the target unit.

FWIW, it looks like the AST is completely unused in InstanceMemberInferrer--it works entirely off the Element model.

(it does jump across libraries though, because it will infer supertypes--the task model doesn't understand that dependency, hence the "hasBeenInferred" flag we need to clear in TypeResolverVisitor)

**Comment by leafpetersen** [comment]
There actually seem to be some "READY_RESOLVED_UNITX" flags already there.  I did a quick experiment on the plane with replacing uses of RESOLVED_UNIT9 in the various 'orderLibraryCycles' dependency inputs with READY_RESOLVED_UNIT10 and the strong mode time dropped to within a few seconds of the normal analyzer time.  I didn't carefully verify that this exact flag captures all the right dependencies yet, but I think something like this ought to do the trick.

I'd forgotten that the InstanceMemberInferrer just works off the element model, that addresses that concern.

**Comment by leafpetersen** [comment]
Strong mode analysis for this app now takes 43 seconds on my laptop, vs 24 seconds for regular analysis.
