### ISSUE TITLE
Instance creation expression with malformed const construcror reports an error

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#25294]
According to Dart Language specification (4th edition, Dec 2015) "16.12 Instance Creation":

"It is a static type warning if the type T in an instance creation expression
of one of the forms
new T.id(a1 , . . . , an , xn+1 : an+1 , . . . , xn+k : an+k ),
new T (a1 , . . . , an , xn+1 : an+1 , . . . , xn+k : an+k ),
const T.id(a1 , . . . , an , xn+1 : an+1 , . . . , xn+k : an+k ),
const T (a1 , . . . , an , xn+1 : an+1 , . . . , xn+k : an+k ) is malformed (19.2) or
malbounded (19.8)."

However, dart (product and checked modes) and dartanalyzer report error when run the test:

``` dart
main() {
  const Undef();
}

> dart  const_ice.dart 
'file:const_ice.dart': malformed type: line 2 pos 9: type 'Undef' is not loaded
  const Undef();
        ^
> dart -c  const_ice.dart  
'file:const_ice.dart': malformed type: line 2 pos 9: type 'Undef' is not loaded
  const Undef();
        ^
> dartanalyzer  const_ice.dart 
Analyzing [const_ice.dart]...
[error] Undefined class 'Undef' (const_ice.dart, line 2, col 9)
1 error found.
```

Tested on Dart VM version: 1.14.0-dev.5.0 (Fri Dec 18 02:28:46 2015) on "linux_x64"

**Comment by munificent** [comment]
As far as I can tell, the analyzer and VM are correctly reporting this compile error from 16.12.2:

> Let e be a constant object expression of the form `const T.id(a1, . . . , an, xn+1 : an+1, . . . , xn+k : an+k)` or the form `const T(a1, . . . , an, xn+1 : an+1, . . . , xn+k : an+k)`. It is a compile-time error if `T` does not denote a class accessible in the current scope.

The spec is a little unclear though, because it says an unknown type is a malformed type as well, so I would expect a fully compliant implementation to have to show *both* the compile-time error here *and* the static warning on malformed types.

I'll leave this bug open for that, unless our Speclords are happy with how it's specced. Either way, the implementations are doing the right thing, I think.

**Comment by eernstg** [comment]
Closing: In Dart 2, these situations are specified to be compile-time errors.
