### ISSUE TITLE
Code completing from a named parameter doesn't help teach me what can go here

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25297]
Consider this code:

`runApp(new Text('hi', style: ));`

I want to know "what goes into style?" so I code complete to see what I could put there.

Expected: some docs or example or type annotation that gives me a hint as to what goes into style.

Actual:

![screen shot 2015-12-19 at 9 53 26 am](https://cloud.githubusercontent.com/assets/5479/11914442/99db44aa-a636-11e5-9bab-0f70ed693d79.png)

If I hit F1, I see that style is a TextStyle. I'd love to see if we can get that info into the flow of code completion and typing.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by jsayol** [comment]
@sethladd FYI, for now you can get that information by using code completion on the constructor itself instead of its parameters. Not as convenient, but still.

![](https://cloud.githubusercontent.com/assets/2029586/11928517/c59862b8-a806-11e5-9320-c25bb929bef8.png)

**Comment by kasperpeulen** [comment]
I think this is an atom issue, because this information should be available from DAS.

Webstorm can show this information using cmd+P:
![image](https://cloud.githubusercontent.com/assets/1035299/11994960/7320e7aa-aa48-11e5-8756-6cd672aba477.png)

DartPad can show this information (behind a flag in localstorage at this moment):

![image](https://cloud.githubusercontent.com/assets/1035299/11994974/c70c0d86-aa48-11e5-9b5c-57686005c23d.png)

**Comment by jsayol** [comment]
Did some digging, this seems to be related to this other issue: #24004

**Comment by sethladd** [comment]
This issue was moved to dart-atom/dartlang#747
