### ISSUE TITLE
dart:jni

### ISSUE THREAD

**Issue by abarth** [dart-lang/sdk#25325]
On Android, Flutter runs the DartVM in a process that also contains a JavaVM.  It would be useful to be able to communicate between the DartVM and the JavaVM.

One approach is to introduce a built-in `dart:jni` library that exposed JNI to Dart.  We could build this library on top of the DartVM C API, but I imagine it would be more efficient to build the library inside the VM.

Most developers wouldn't use `dart:jni` directly.  Instead, they'd use auto-generate Dart code that reflected the Java APIs that they wanted to access.  For that reason, `dart:jni` should be optimized for performance over programmability.

**Comment by mezoni** [comment]
JNI enables programmers to write native methods to handle situations when an application cannot be written entirely in the Java programming language.

The Java Native Interface (JNI) is a programming framework that enables Java code running in a Java Virtual Machine to call and be called by native applications.

This does not means that JNI enables the Dart code to call directly the Java code executed in JVM because Dart code is not a native application (Dart is a scripting language).

P.S.
And I agree that this should work `"Dart -> C++ -> JNI -> Java"` but this requires first to call C++ code from the Dart script which is not the same as `"Dart -> JNI -> Java"`

**Comment by lrhn** [comment]
This sounds like a feature that Flutter could implement, but not something that makes sense in Dart in general. I recommend filing this feature request against Flutter directly.

**Comment by abarth** [comment]
Yes, we could certainly implement this feature using the DartVM C API.  However, I suspect there might be performance advantages to implementing this feature inside the C API.

**Comment by mezoni** [comment]
>> Yes, we could certainly implement this feature using the DartVM C API.

It would be very interesting to look at the implementation.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/engine/tree/master/sky/engine/bindings/jni is much of the code.  @jason-simmons is the author.

**Comment by natebosch** [comment]
Since flutter added and then removed this I don't think we need to continue to consider it for the Dart SDK.
https://github.com/flutter/flutter/issues/4728
