### ISSUE TITLE
pub-mac-be failing with "Too many open files"

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25337]
It looks like all the pub tests are failing on mac with a "too many open files" error (see [this log](http://build.chromium.org/p/client.dart/builders/pub-mac-be/builds/16023/steps/annotated_steps/logs/stdio) for example). It seems that every time the test runner tries to load an isolate, it fails.

**Comment by whesse** [comment]
The problem was the limit on the number of files in the MacOS launcher which launches the buildbot daemon, which limited open files to only 256.  The kernel limits are more like 20,000 and 10,000 open files, which should be fine.  The method of setting the launcher limits changed in Yosemite.  I found the fix, applied it to the slave, and upstreamed the fix to the chrome infrastructure team.

**Comment by nex3** [comment]
Thanks!
