### ISSUE TITLE
Analyzer should report an error on async usage in fletch projects

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#25373]
Fletch does not, and may not in the future, support the async keyword. It would be good if the analyzer reported usage of async in fletch projects as an error. One way to accomplish this would be to have a no-async-allowed flag in the _sdkext file.

**Comment by bwilkerson** [comment]
Yes, we definitely need a way to configure the set of language features supported by a given platform (sdk). That needs to translate into an AnalysisOptions option. (FWIW, I would prefer to keep all of the AnalysisOptions flags as "enableX" rather than having some be "disableX", and it might be cleaner to propagate that upward.)

In this case we will also need to do some work in the parser to put the appropriate support behind the options flag. My guess, though, is that it's sufficient to generate errors in the parser if any of those language features are being used (that is, that it won't require changes elsewhere). We'll need to decide whether it's better to go ahead and produce the same AST structure either way or whether we want the follow-on errors that might result from only accepting the limited syntax.

**Comment by zoechi** [comment]
Sounds cumbersome to enable for example asnyc/await in `.analysis_options` for each server, web, flutter, ... project.

**Comment by bwilkerson** [comment]
Yes, it would be! Users shouldn't need (or probably even be allowed) to configure the system at that level. What we're talking about is adding metadata to the SDK (similar in nature to the .libraries file) that contains this information.

**Comment by zoechi** [comment]
I see, sorry for the noise and thanks for the info.
