### ISSUE TITLE
dart2js: ClassMirror.invoke named arguments are not implemented.

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/sdk#25388]
dart2js dart:mirrors [ClassMirror.invoke](https://api.dartlang.org/135619/dart-mirrors/ObjectMirror/invoke.html) method doesn't accept named arguments. It throws this exception:

```
Unsupported operation: Named arguments are not implemented.
```

**Comment by zoechi** [comment]
Looks similar to #19635

**Comment by stevenroose** [comment]
The one you mention seems to be related to the empty constructors like bug
https://github.com/dart-lang/sdk/issues/18541. This bug is explicit as it
says named parameters are not implemented in dart2js.

**Comment by eernstg** [comment]
If nothing else prevents this, you might want to consider using the package reflectable rather than 'dart:mirrors'. We have had tests using named arguments in invocation of various kinds of methods for a while (including `ClassMirror.invoke`), and there are no known issues with that.

**Comment by sigmundch** [comment]
Agree with @eernstg 

@stevenroose - what are you currently using dart:mirrors for? Even though dart2js has a large implementation of `dart:mirrors`, please bear in mind that its implementation is meant to be used only during development, but it is not recommended for deployment in production apps: the cost it has on tree-shaking and optimizations is too high. That's why we recommend tools that can give you reflective APIs that can later be transformed and compiled into something dart2js can handle more easily, like [smoke][1] or [reflectable][2]. Reflectable is much newer, far more complete and maintained than smoke.

[1]: https://pub.dartlang.org/packages/smoke
[2]: https://pub.dartlang.org/packages/reflectable

**Comment by matanlurey** [comment]
Mirrors has been removed from dart2js in Dart2.
