### ISSUE TITLE
Unable to code complete a method reference (tearoff)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25386]
Consider this code:

![screen shot 2016-01-08 at 2 55 49 pm](https://cloud.githubusercontent.com/assets/5479/12211734/041ea122-b618-11e5-99f7-042f87dca962.png)

Unfortunately, trying to complete increm... does not show me `incrementCounter`

I even tried "reanalyze sources", but that didn't help.

**Comment by danrubel** [comment]
incrementalCounter is a `void` method. Does it make sense to suggest it here? If you change the method to `int incrementCounter`, then does `incrementCounter` appear in the list of suggestions?

**Comment by jwren** [comment]
In this case the type of onPressed is: typedef void VoidCallback();, which is precisely what incrementCounter.  Currently it is not suggested at all.  In the code below, it is possible to get getAnInt() suggested.  Neither are sorted to the top.


The same code to repro faster:

import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';

class FlutterDemoState extends State {
  int counter = 0;
  void incrementalCounter() {
    setState(() {
      counter++;
    });
  }

  int getAnInt() {
    return 1;
  }

Widget build(BuildContext context) {
  return new Scaffold(floatingActionButton: new FloatingActionButton(
    onPressed: ^//incrementalCounter
    // elevation: ^//getAnInt()
  ));
}

}

**Comment by jwren** [comment]
@danrubel, @sethladd is asking for a completion to the function `incrementalCounter`, not the return type/call of the method `incrementalCounter()`.

I have confirmed that `incrementalCounter()` is filtered out because it is a method which returns void.

@sethladd we currently do not offer the function and method as tearoffs, only as invocations.

De-prioritizing for now.  When we go to fix it, we may want to add a new completion type to the protocol.

**Comment by floitschG** [comment]
When the target-type is a function-type then tear-offs are the most common argument. It feels wrong to not even propose a valid (even most useful) identifier.
