### ISSUE TITLE
What should I do that you have deleted the reference which is mentioned that issues was filled by me?

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#25392]
I did not reported some issues on this Github resource but Google trying to deceive other people about that I reported these issues on this Github resource.

Eg.
https://github.com/dart-lang/sdk/issues/7290

In this issues mentioned that `This issue was originally filed by @mezoni`

But I did not reported this issue on this Github resource.
Also I did not reported many other issues here on Github.
And I never reported them anywhere directly (being authenticated) as the Github user [mezoni](https://github.com/mezoni). This is `unsubstantiated lies` from Google.

And I do not want everything to be represented in this form (as the Github user mezoni was reported these issues).

Who can answer me: how all these mentions about me can be deleted from Google Github resources issues as untrue?

**Comment by ricowind** [comment]
@nicolasgarnier @sgjesse @anders-sandholm 
Just a few clarifying questions here:
  - There was a mail send out back in February 2015 asking if you would like to grant google permission to migrate old issues from code.google.com to the github issue tracker, with a link to https://dart-issues-migrator.appspot.com/ where you could sign in and give google access to use a github token to find and match a github user. Did you not sign up for this?
 - Did you actually file the original issue on code.google.com?
In any case, if the answer to any of the above is no, then something in the migration went wrong and we can look into what that is

**Comment by mezoni** [comment]
1) I do not know anything about it (give google access to use a github token to find and match a github user).
2) Yes, this issue was created by Andrew Mezoni but I do not want that it will be associated with another account (with Github account  as in this case).

**Comment by whesse** [comment]
I can edit these comments and delete them manually, but it would be better to do it automatically.  I suppose that Mezoni himself cannot edit the comments and delete the attribution line?

**Comment by nicolasgarnier** [comment]
Hey @mezoni,

I have sent you an email on 2/9/15 with subject "Migration of your Dart issues from Google Project Hosting to GitHub - Please sign up". We sent that email to developers who had reported an issue on the Google Project hosting issue tracker. Below is the content of the email I sent:

>Dear Dart developer,
>
>You are receiving this message because you have created at least one issue on the [Dart Issue tracker](https://code.google.com/p/dart/issues/list) on Google Project Hosting that is still opened.
>
>Dart is moving from Google Project Hosting to GitHub and, as part of that, we’ll migrate the issue(s) you have created.
>
>Please sign up for the migration
>
>Before we move there is one thing we would like you to do: Please visit [dart-issues-migrator.appspot.com](https://dart-issues-migrator.appspot.com/), click on the "Yes, let's do this" button and authorize our issues migrator application on GitHub. This will allow us to re-create your issues and comments as you on GitHub, so that you will be notified of changes to issues you've contributed to. It only takes a few seconds.
>
>Of course you don’t have to give us this permission. If you don't your issues and comments will be owned by the "dartbot" account but will still be attributed to you. We only need your credentials for the transition; once it's done we'll throw them away and—to be sure—you may revoke the token yourself.
>
>Please do this within the next 2-3 weeks as we are planning to move the issues very soon!
>
>If you have questions about the migration please post them on the [dart-misc forum](https://groups.google.com/a/dartlang.org/forum/#!forum/misc) - misc@dartlang.com.
>
>Cheers!

You must have signed up for the migration on [dart-issues-migrator.appspot.com](https://dart-issues-migrator.appspot.com/) because that's the only way we mapped Google accounts from Project hosting issues to a GitHub username. The registration asks you to sign-in both of your accounts to grant us permission. If we didn't have this mapping the migrated issue would have looked like #7288 with a header such as `This issue was originally filed by kguggi...@gmail.com` (similar obfuscated Google account email address that was used in Project Hosting).

Now we can manually manually revert the [102 migrated issues under yourname](https://github.com/dart-lang/sdk/search?q=%22This+issue+was+originally+filed+by+%40mezoni%22&type=Issues) to `This issue was originally filed by ...ezoni@gmail.com` would you like that?

**Comment by mezoni** [comment]
My current settings on https://code.google.com/hosting/settings is:

User Preferences
Username display
andrew.m...@gmail.com
Obscured email address for non-project members (project members see full email)

I think that using current settings would be more correct.
`andrew.m...@gmail.com`

Using name `...ezoni@gmail.com` here is not qiute correct.

**Comment by nicolasgarnier** [comment]
All right I updated my comment above. I'll go ahead and do that...

**Comment by nicolasgarnier** [comment]
Done!
