### ISSUE TITLE
idle cpu usage by the analysis server

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25401]
We're seeing issues with significant power consumption by Atom. In tracking that down I noticed that the analysis server uses cpu even when idle. There are some more details here: https://github.com/dart-atom/dartlang/issues/648.

We should investigate whether the analysis server uses cpu when idle (periodic, frequent timer tasks?), and how to eliminate that.

@danrubel, who might have a line on some timer usage

**Comment by bwilkerson** [comment]
Cross-posted from the atom thread:

I have IntelliJ running in the background. I started it up this morning and forced it to analyze everything, then started being in meetings so I haven't touched it for hours. The analysis server process is consistently reading a CPU usage of 0.0%. I'm not claiming that the problem you're seeing isn't the analysis server, just that it is possible to run server in such a way that it doesn't consume CPU while idle. If server is the problem, then it's probably due to a difference in the ways IntelliJ and Atom are using it, which at least gives us a starting point for investigation.

**Comment by zapu** [comment]
Can confirm with Sublime Text plugin, just decided to try Dart today.

```
zapu@kyuukon ~/darts » ps aux | grep dart
zapu     27479  100  4.4 584552 357952 ?       Sl   sty18  14:57 /usr/lib/dart/bin/dart /usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot --sdk=/usr/lib/dart/ --file-read-mode normalize-eol-always
zapu     28604  7.3  2.3 541228 187952 ?       Sl   00:00   0:11 /usr/lib/dart/bin/dart /usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot --sdk=/usr/lib/dart/ --file-read-mode normalize-eol-always
zapu     28831  0.0  0.0  17908  2284 pts/14   S+   00:02   0:00 grep dart
```

First process constantly eats 100% CPU. Otherwise seems to work fine (I get autocomplete etc. in editor).

**Comment by danrubel** [comment]
The dartlang plugin in Atom has a "Dart plugin status" view which shows the current status of the analysis server. I seem to remember that the plugin uses the [server.status](https://cdn.rawgit.com/dart-lang/sdk/master/pkg/analysis_server/doc/api.html#notification_server.status) API to continually check that the server is responsive. I will follow up with @devoncarew to see if that is the case.

**Comment by devoncarew** [comment]
To follow up re: the status view in atom's plugin, we invoke the `diagnostic.getDiagnostics` API once a second when the status view is open; we do cancel the timer when the view is closed.

**Comment by devoncarew** [comment]
Closing this as I don't see idle usage now; we had done some work in atom to batch up key event changes ==> 10x less analysis.
