### ISSUE TITLE
Add Windows bots to test Edge browser

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25413]
IE 10 is _less_ usage than IE 9. We need to start getting coverage on edge.

**Comment by whesse** [comment]
We are working on it.  We have requested Windows 10 bots, and have them.  We are already running some non-browser tests on them, and just need to start the browser tests.  There may be a problem with a new security setting (UAC?) in Windows 10, but we'll find out.  1.15 milestone is fine.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by mit-mit** [comment]
@whesse is this happening in 1.17?

**Comment by whesse** [comment]
No.  There is too much other stuff I'm doing in the next two weeks.  I would give it a P1, but that might be misleading because it could be a month before it is done.

**Comment by whesse** [comment]
We have now stopped testing on IE10.  Testing on Edge is now a priority.  Renaming issue to mention Edge only.

**Comment by whesse** [comment]
@sortie @sigmundch

**Comment by whesse** [comment]
@athomas @mkj-gram 

I have managed to rdesktop to our Windows 10 bots by following the instructions from chrome-infra, using VNC Viewer from RealVNC, connecting to localhost:8000 after setting up tunneling to port 5900.

In Powershell, I can get to cmd.exe by running it, and then I can start browsers with commands like:
start iexplore http://www.google.com
and
start microsoft-edge:http://www.cnn.com

I think we need to try various arguments to dart:io Process.start to get the right command to start the browser in a subprocess, but this should be doable, since Dart SDK is building OK on Windows 10.

Then we can make the browser_controller.dart classes for IE in tools/testing/dart use these commands to start the browsers on Windows 10, and get test.py working there.

**Comment by whesse** [comment]
I ws able to open Edge in the chrome-bot account by following the instructions at
https://appuals.com/microsoft-edge-cant-be-opened-using-the-built-in-administrator-account/

**Comment by athomas** [comment]
Another writeup of basically the same instructions as in the previous link: https://4sysops.com/archives/why-the-built-in-administrator-account-cant-open-edge-and-a-lesson-in-uac/

**Comment by athomas** [comment]
@whesse Trying the above solutions makes Edge run, but all the builds fail instantly. So I'm not sure that will work. However, it might just work if we were to use the most recent version of Windows 10 (15063): 
http://winaero.com/blog/run-apps-uac-disabled-windows-10/

Any reason why our VM use the very first Windows 10 version (Build 10240)?

**Comment by parlough** [comment]
I'm going to close this under the justification that supported versions of Edge now use Chromium, and ddc and dart2js both have Chrome bots set up for Windows.

There are so many Chromium derivatives, I'm not sure it's worth testing them. If anyone feels so, please reopen :)
