### ISSUE TITLE
Please, clarify specification for yield statement

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25421]
The Dart Programming Language Speciﬁcation (4th edition draft) version 1.11, section 17.16.1 Yield reads:

> Execution of a statement s of the form yield e; proceeds as follows:
> First, the expression e is evaluated to an object o.
> If the enclosing function m is marked async\* (9) and the stream u associated with m has been paused,
> then execution of m is suspended until u is resumed or canceled.
> Next, o is added to the iterable or stream associated with the immediately
> enclosing function.

The specification does not clarify the case if evaluation of the expression e throws exception.
In general it is not clear how the exceptions in generator functions are handled.
One might assume that exception is propagated to the iterable or stream, returned by the generator.
However I believe such assumption is not obvious and I would prefer a clear statement in the specification.

**Comment by lrhn** [comment]
The specification generally doesn't say much about what happens if evaluation of a sub-expression throws. That is specified in the semantics of the `throw` expression - control flow is redirected to the closest dynamically enclosing handler. (This also applies to exceptions raised without a `throw` operator - like those for type errors or other errors that throw at runtime).

The enclosing handler in an async generator function is either one declared inside the function, or it reaches the point where the function terminates. In that case, the handling is specified in section 16.14 (Function invocition) - when the function terminates:
> If the current exception x is defined:
> – x is added to s.
> – If s has been canceled then its cancellation future is completed with x as an error.

where /s/ is the stream controller controlling the stream returned by the call to the function.

That is, the exception is output on the stream if the stream is still open, or it is output on the future returned by the call to `StreamController.cancel` which closed the stream. The latter is for errors happening during clean-up - when a stream subscription on a stream from an async* function is cancelled, the `yield` statements stop yielding and instead act as return statements. This can trigger cleanup-code in finally blocks which can then fail - that error ends up in the future returned by `cancel`.
