### ISSUE TITLE
Analyzer requires matching generic types on both sides of if-null operator 

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/sdk#25466]
Given the following code the analyzer complains that:
```
WARNING: The argument type 'EfficientLength' cannot be assigned to the parameter type 'Iterable'
```

```dart
class Bar {
  final List<String> content;

  Bar(List<String> content)
      : this.content = new List.unmodifiable(content ?? []);
}
```
I can make this go away by removing the generic type on the constructor param or add it to the default empty list literal in the if-null operator: https://dartpad.dartlang.org/b94dd63ebef7ef8c16ee

Please disregard that there would be better ways to express this particular behavior, this is just a boiled down example.

**Comment by lrhn** [comment]
This is a known problem with the way the language specification defines the least upper bound of `List<dynamic>` and `List<String>` - it happens to be `EfficientLength` (an otherwise completely irrelevant private class defined somewhere in the List type hiererchy). See #19425.

The analyzer is required to give this warning by the language semantics, so if anything needs to change, it's the semantics.
