### ISSUE TITLE
~ operator on `int`s produces different results in dart2js and Dart VM

### ISSUE THREAD

**Issue by dynaxis** [dart-lang/sdk#25493]
See https://dartpad.dartlang.org/52c05fa3241bffb603c4 .
For instance, `~0` is `-1` in JS and Dart VM, but dart2js produces a different result.

 4 294 967 295 = 0xffffffff

So bit-by-bit the dart2js output is correct if we assume 32-bit int, but it's not what it should be.

I ran it with 1.13.2 on various browsers including firefox and chrome latest, and also tried with 1.14.0-dev.7.0. All tests were performed on Windows 10 64 bit.

**Comment by kevmoo** [comment]
CC @sigmundch @srawlins – known delta w/ the VM?

**Comment by dynaxis** [comment]
Initially I thought so. But dart2js doesn't spit out errors upon ~ operator on numbers (since only `int` has ~ operator, I guess dart2js should treat the operand as an `int`) and then shouldn't the result be consistent with what the API doc says? See https://api.dartlang.org/1.13.2/dart-core/int/operator_bitwise_negate.html .

JS converts an operand to a 32bit signed integer when doing ~, and the result is again a signed 32bit integer. At least, the 32bit integers should work as expected, and I see it is doable in dart2js (if not, my apolgies).

Also regardless of whatever the resolution of this issue is, it would be good if those corner cases are documented clearly in the API doc. ;)

**Comment by lrhn** [comment]
Dart2js treats all bit-operations as if they were performed on 32-bit unsigned integers, and return 32-bit unsigned integer results. This includes the ~ (bitwise negation) operator. Dart2js also does not have integers separate from doubles, so any double with an integer value will be accepted as an integer: `double x = 27.5; x /= 2.5; print(x is int);` (which is wrong because `/` always returns a double).

However, it should give an error on `~1.1`, which it doesn't. That's a bug apart from the integer-related inadequacies - the ~ operator is, as you say, only on `int`, not on `num`, so `~1.1` should fail. It seems to be missing an "is int" check in the interceptor.

**Comment by dynaxis** [comment]
@lrhn I've never known such implementation detail. I always assumed that I can safely hold integers up to and including 53-bit. So considering other bitwise operators than ~ is difficult to implement in JS for integers up to an including 53-bits, I rather prefer to have them done just as JS does. It's more consistent with Dart VM's behavior, IMHO. Is there any possibility to change the current implementation?

**Comment by dynaxis** [comment]
I changed all of my codes affected by this issue to work well with dart2js by writing `-x - 1` instead of `~x`. I know my ignorance in JS semantics made me make wrong assumptions on bitwise operations on `int`s (I was mainly a server side guy). But please document it clearly in the API doc. Thanks.

**Comment by dynaxis** [comment]
To support my argument, `-1 & -1 == -1` in dart vm but `-1 & -1 == 4294967295` with dart2js. In JS, `-1 & -1 === -1`. Preserving sign is more consistent with both JS and Dart VM?

**Comment by lrhn** [comment]
I believe the current choice was made because code that relies on bitwise operations for performance (like encryption) typically wants unsigned values.

Picking either signed or unsigned as the result is wrong in some cases, so some choice had to be made (and implementing Dart integers wasn't considered viable in JS), so since performance was the reason not to do bitwise operations above 32 bits, it would be counter-productive to pick the implementation that penalized the code that needed that performance the most.

I don't think we should expect it to change at this point, at least until JS introduces integers.

**Comment by dynaxis** [comment]
@lrhn Thanks for sharing what was the rationale behind the current choice of implementation. Here goes my final thought:

First of all, I can understand that implementing bitwise operations for ints wider than 32bits is not an option in the same spirit as not fully implementing Dart's int semantics. But if that's the case, it would be really appreciated if the corresponding _API doc and spec states what's different in dart2js more thorougly_. Currently only 53bit thing is mentioned, so in some cases quite misleading.

And considering Dart VM behaves much like JS in terms of signs of ints and JS seems to require additional operation(s) other than the designated bitwise operation to produce unsigned result, I don't still get how unsigned results can improve performance of Dart codes translated to JS via dart2js. I hope to know what was the case and dig into it for myself, but also don't want to bother you for this matter. ;)

So not raising an error on something like `~1.1` is an bug we found as a byproduct of this discussion. But it would be beneficial to document the current implementation of `int` and associated operations in a little bit more detail, IMHO.

**Comment by dynaxis** [comment]
@lrhn was it the reason for choosing unsigned results that some browsers convert the signed results back to floating point representations? If so, I get signed results may affect the performance. Sorry for finally bothering you.

**Comment by lrhn** [comment]
I wasn't the one making the final decision on what dart2js bitwise operators does, so I can't tell you the exact trade-offs that were considered. I do believe that making certain encryption libraries work efficiently was a goal, and that unsigned numbers were apparently better for some reason, but I can't say exactly what that reason was.

**Comment by lrhn** [comment]
Again, I don't know the exact criteria used when the decision was made. I don't think it's due to doubles being better unsigned. If anything, a signed number would require fewer numbers being converted back into doubles. 

JavaScript engines often use a tagged 31-bit signed integer representation for integers when possible, falling back on doubles only when the value is non-integral or outside that range. That means that 32-bit unsigned numbers are not using half of the possible "small integer" representations, and has to convert more numbers to double as a result. That is, if it needs to represent the result as a JavaScript number at all.
Whether that's necessary depends on the exact operations being done. If a sequence of operations can be seen to be purely 32-bit unsigned, then it's possible that the JavaScript engine optimizes it to be computed with 32-bit unsigned machine instructions, and only converts back to a JavaScript number at the very end. 
It's similar to how asm.js marks every unsigned 32-bit value by doing `>>>0` (conversion to uint32) after the operation. It takes up room in the source, but he generated code won't contain it if it can just a uint32 result from the previous computation directly.

**Comment by dynaxis** [comment]
@lrhn Thank you very much. My theory was incorrect with wrong assumptions on the working of low-level stuffs. I guessed old IEs may not have such storage optimization, and conversions from signed int to double is more expensive than the other way around. Both assumptions are obviously wrong. (after leaving the above comment, I did my homework studying how values are represented in various modern JS engines)

I got that the decision would have made for applications where a sequence of unsigned int operations, which can be optimized by modern JS engines, needs to perform well.

**Comment by rvaleev** [comment]
Just faced that bug. Coded in dart and browsed in Chromium, all works fine. But once I did dart2js transformation it start fall down. Digging inside brought me here, and I see that strange discussion. If we say that dart2js compile to executable on browsers, than it should do it and hide all possible leaks of abstractions. I would mark that issue as a blocker.

**Comment by a14n** [comment]
I just faced this bug. 
* on the dart VM `~0` returns `-1`
* in a JS console `~0` returns `-1`
* on dartpad `~0` returns `4294967295`

**Comment by mraleph** [comment]
The specification is being amended to specify this behaviour as intentional. See https://github.com/dart-lang/language/issues/1129 - so this is not a bug (though it is an unfortunate divergence in semantics between JavaScript and native targets).

**Comment by lrhn** [comment]
Also, this is not *new*. The JS compiled numbers have behaved like this since early days of dart2js.
The spec change isn't changing anything, except documenting in more detail how JS number operations already behave. 

*All* bitwise operators compiled to JavaScript are restricted to 32 bits *and* they result in an unsigned 32-bit number.
The result had to be either signed or unsigned (Dart did not, and still doesn't, have a `>>>` operator which generates unsigned numbers), and either could be annoying to some people and useful to tohers. It was decided that the uses most in use of performance (like crypto) would be better served with unsigned numbers.
