### ISSUE TITLE
List.fold generic type parameters not inferred

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25491]
The code below produces the following error:

```
[warning] x (dynamic) will need runtime check to cast to type List<String> (/Users/leafp/tmp/scratch.dart, line 4, col 20)
```

Suggesting that we are not successfully inferring the generic type parameters for `fold`.  I would have thought we would be catching this.  I don't think this is an instance of #25490, but maybe an interaction between the upwards inference on the arguments and the downwards inference on the closure parameter? 

```dart
void main() {
  List<int> o;
  var x = o.fold(0, (x, y) => x + y);
  List<String> y = x;
}
```

**Comment by jmesserly** [comment]
funny enough, we have a test specifically for "fold" ... let me dig in

**Comment by jmesserly** [comment]
@leafpetersen here's what I see in terms of hints:
```
  info: [INFERRED_TYPE_CLOSURE] line 12, column 29 of /main.dart: (x, y) => x + y has inferred type (dynamic, int) → dynamic
            var x = o.fold(0, (x, y) => x + y);
                              ^^^^^^^^^^^^^^^
  info: [DYNAMIC_INVOKE] line 12, column 39 of /main.dart: x + y requires dynamic invoke
            var x = o.fold(0, (x, y) => x + y);
                                        ^^^^^
```
I believe what happens is:
1. We instantiate with T as dynamic.
2. That pushes down (dynamic, int) → dynamic to the closure.
3. When we come back up, we see that type as the 2nd arg to fold. LUB of "int" and "dynamic" will be "dynamic"

So I think we need #25490, unless I'm missing something.

If there's some way we could infer from only the first argument, we'd get T:int, but we'd still need to push that type down to the lambda, right? At least for checking. Otherwise I don't see how we know that the '+' is a valid operation.

**Comment by leafpetersen** [comment]
Ah right.  Annoying.  I guess for now you just have to put types on the arguments.
