### ISSUE TITLE
Specification should be more clear in parametrized types definition

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25494]
``` dart
class C<T1, T2> {
}

main() {
  C c = new C();
}
```

The code above produces no static warning. According the spec (19.8 Parameterized Types)
"Let T be a parameterized type G < S1, . . . , Sn >. If G is not a generic
type, the type arguments Si, 1 <= i <=n are discarded. If G has m != n type
parameters, T is treated as as a parameterized type with m arguments, all of
which are dynamic.
In short, any arity mismatch results in all type arguments being dropped, and
replaced with the correct number of type arguments, all set to dynamic. Of course,
a static warning will be issued."

I don't think that static warning should be issued here. The code

``` dart
    List lst = new List();
```

should not produce a warning. But specification doesn't clearly say about this. It does not say that m > 0. It says about  "**any** arity mismatch". So I think specification should be more clear here

**Comment by lrhn** [comment]
The section on parameterized types only apply to cases where there is a type parameter (`G<S1, ..., Sm>`), as the second paragraph assumes. That is, this section is not the one that converts `List` to `List<dynamic>`. Instead that happens in section 19.6 where it says:
>  If a generic type is used but type arguments are not provided, then the type arguments default to the unknown type.
> This means that given a generic declaration `G<T1, . . . , Tn>`, the type `G` is
equivalent to `G<dynamic, . . . , dynamic>`.

So, the part of the specification that handles generic types with no type parameters will convert it to a type application with the correct number type parameters, all being dynamic.

**Comment by sgrekhov** [comment]
Is there a part of the specification that converts G<dynamic, . . . , dynamic> to G? Because
```dart
class C<T1, T2> {}

main() {
  C<int, int, String> c1 = new C<int, int, String>();
  print(c1.runtimeType); // prints C

  C<dynamic, dynamic> c2 = new C<dynamic, dynamic>();
  print(c2.runtimeType); // prints C
}
```
Is this a bug or not? 19.8.1 Actual Type of Declaration says:
"Let T be the declared type of a declaration d, as it appears in the program
source. The actual type of d is
• [A1, . . . ,An/U1, . . . ,Un]T if d depends on type parameters U1, . . . ,Un, and
Ai is the value of Ui, 1 <= i <= n.
• T otherwise."
Probably the last case (T otherwise) should cover this but there are no mention about dynamic or arity mismatch

**Comment by lrhn** [comment]
It's not a bug, it's just a feature of `Type.toString`. The type is `C<dynamic,dynamic>` - at runtime you can't have a `Type` object that represents a generic class without type parameters applied. When printing a type that has only dynamic as type parameters, the toString function leaves out the type parameters, probably for brevity. 

Section 19.8.1 is talking about the types appearing inside a generic class. If the type depends on the class' type parameters, then the actual type is the one you get when putting in the actual type arguments, if it doesn't depend on the type parameters, it's just itself. So, for `class C<T> { List<T> foo(int x) => []; }` inside an instance of `C<bool>`, the /actual/ return type is `List<bool>` and the actual parameter type is just `int` (that's the "T otherwise" case).

**Comment by munificent** [comment]
Sounds like the spec is clear enough here?
