### ISSUE TITLE
Specification for yield statement is incomplete

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25539]
Dart Programming Language Speciﬁcation (4th edition draft) version 1.11 chapter 17.16.1 Yield reads:

> If the enclosing function m is marked async\* and the stream u associated
> with m has been canceled, then let c be the ﬁnally clause (17.11) of the inner-
> most enclosing try-ﬁnally statement, if any. If c is deﬁned, let h be the handler
> induced by c. If h is deﬁned, control is transferred to h. If h is undeﬁned, the
> immediately enclosing function terminates.

There are several issues with this text:
1. There is no way for handler h to determine, whether it is executed normally or as a result of the associated stream cancellation. Is it possible to reserve some special exception (StreamCanceled, for example), so the there can be defined a special handler for the case of stream cancellation?
2. The text mention only innermost enclosing try-ﬁnally statement. What about other enclosing try-ﬁnally statements? Will their 'finally' handlers be executed and in which order? 
3. It is not clear, what happens after handler h is executed? Does the enclosing function terminate?

**Comment by lrhn** [comment]
Ad 1. It's true that there is no way to directly see whether the current stream subscription has been cancelled.
You can code around it if you really want (being cancelled means that a `yield` statement acts as a return, so wrapping the yield as `var value = yieldExpr; isCanceled = true; yield value; isCanceled = false;` would mean that `isCanceled` is true only if the subscription was canceled at the latest `yield`.
In general that doesn't seem to be necessary. Most tear-down will have to happen whether you cancel or just complete normally, or if not, you will have updated some internal state along the way that you can use to determine what's happening. 
Also, if being cancelled caused the yield to throw, you would *need* to have a handler for that case, which is often not needed. Say:

    Stream concatStream(Iterable<Stream> stream) async* {
       for (var stream in streams) yield* stream;
    }

This function works perfectly well without any error handling, and cancel is propagated without having to do anything about it.
Again, in practice I haven't seen a need for a special "cancelled" signal.

Ad 2. The innermost finally block will transfer control to the next surrounding finally block, if any, unless it does some other control flow. A finally block can contain a `break`, `continue`, `return` or `throw` statement which redirects control, otherwise it continues to do the same thing that got it to enter the finally block to begin with.

Ad 3. See 2 - the finally handler transfers control somewhere else when it exits.

**Comment by alsemenov** [comment]
Ad 1. The next paragraph reads:
>The stream associated with an asynchronous generator could be canceled by
>any code with a reference to that stream at any point where the generator was
>passivated. Such a cancellation constitutes an irretrievable error for the genera-
>tor. At this point, the only plausible action for the generator is to clean up after
>itself via its ﬁnally clauses.

So this makes me consider the finally block as stream cancellation handler.
But when I created a test for this, I realized that the finally block is executed always 
(as it should be). So I believe this is confusing, because single finally block should 
serve two functions: handle normal try-catch block exit and handle stream cancellation.

I agree that throwing a special exception may be not a good idea. 
But some means to provide a special handler only for stream cancellation would be great.

Ad 2. Please, compare with similar cases in chapters 'Break' and 'Continue':
>Furthermore, let s1 , . . . , sn be those try statements that are both enclosed in sE
>and that enclose sb , and that have a ﬁnally clause. Lastly, let fj be the ﬁnally
>clause of sj , 1 ≤ j ≤ n. Executing sb ﬁrst executes f1 , . . . , fn in innermost-
>clause-ﬁrst order and then terminates sE .

Is it possible to define execution of finally handler in similar way?

**Comment by lrhn** [comment]
I think Gilad is the best person to answer that.
