### ISSUE TITLE
VM: Snapshots don't properly handle ephemerons.

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#25559]
```
import 'dart:isolate';
import 'dart:developer';

class Box {}

main() {
  var port = new RawReceivePort();
  port.handler = ((reply) {
    print("Got reply: $reply");
    var box1 = reply[0];
    var colors = reply[1];
    if (colors[box1] != "red") {
      throw "Missing color of box1";
    }
    var box3 = new Box();
    if (colors[box3] != null) {
      throw "Bogus color of box3";
    }
    port.close();
  });

  Isolate.spawn(child, port.sendPort);
}

child(replyPort) {
  var box1 = new Box();
  var box2 = new Box();
  var tag = new UserTag("blue-tag");
  var colors = new Expando();
  colors[box1] = "red";
  colors[box2] = "green";
  colors[tag] = "blue";

  // Note that 'tag' is not reachable from this message.                                                                                           
  replyPort.send([box1, colors]);
}
```

yeilds

```
Invalid argument(s): Illegal argument in isolate message : (object is a UserTag)
#0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:193)
#1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:177)
#2      child (file:///usr/local/google/home/rmacnak/dart1/sdk/a.dart:36:13)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:264)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by lrhn** [comment]
You are sending an `Expando` across a `SendPort`, along with one of the keys. That should work - we guarantee that the same object sent twice in the same message will be deserialized to the same object in both instances, so the key in the expando should match the accompanying object.

I guess this is the VM's internal implementation of `Expando` that fails to serialize in some way.

**Comment by rmacnak-google** [comment]
Two implementation issues:
 - The serializer writes ephemerons as if they were strong references
 - The deserializer neglects to rehash the Expando

**Comment by iposva-google** [comment]
The question really is how you access the Expando object in the receiving isolate and how you preserve the identify of the Expando object across multiple messages.

**Comment by lrhn** [comment]
You should probably not preserve the identity of the expando object. Like most other objects, it should be copied when sent. That could mean that you will eventually send multiple expando objects, each with potentially different keys. Only objects sent multiple times as part of the same message need to have their (relative) identity preserved.

As an optimization, any non-constant key of an expando that isn't sent in the same message can be dropped as well, since it will be unreachable on the other end (or you can just wait for GC).
(This assumes constants are converted to similar constants on the receiving end).
