### ISSUE TITLE
Specification: no definition of static variable assignment

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25581]
Dart Language specifivation 4th Edition (December, 2015), "16.19 Assignment"
> Evaluation of an assignment a of the form v = e proceeds as follows:
> Let d be the innermost declaration whose name is v or v =, if it exists.
> ...
> Otherwise, if d is the declaration of a static variable, static getter or static
> setter in class C, then the assignment is equivalent to the assignment C.v = e.

But specification doesn't contain definition of C.v = e. Detailed definition of C.v = e assignment should be added to the spec. For example the statement above contains
>  ...d is the declaration of a static variable, static getter or static setter in class C...

What if d is the declaration of a static getter? What should be in this case? NoSuchMethosError? But if there are static implementation of noSuchMethod()? According the spec it should be described in those part of the spec that describes C.v = e assignment but the current specification miss it

**Comment by lrhn** [comment]
The specification of C.v = e is part of e<sub>1</sub>.v = e<sub>2</sub>. When e<sub>1<sub> is a type literal (and evaluates to a `Type` object), the `Type` object forwards the setter to the static setter on the class.

Now, if class has a static getter and no static setter, then setter lookup on the type object fails.
That means that `noSuchMethod` is called on the type object with a suitable invocation.
The `noSuchMethod` on Type objects are inherited from `Object`, so that means that a `NoSuchMethodError` is thrown. The only controversial part here is that it appears that the type object will be the reported receiver so it doesn't look like a static call gone wrong. That may need fixing.

You can't have a static implementation of `noSuchMethod` because it's a compile-time error to have a static method with the same name as an inherited instance member, and type object inherit `noSuchMethod` from Object. That ensures that the type object won't have a user-written `noSuchMethod`.

**Comment by sgrekhov** [comment]
Ok, thank you. Now it's clearer. But there are still an issue for me. I didn't find the place in the specification where it is said that when evaluating an expression e1, if e1 is the name of the class then it evaluates to an instance of a Type object. Where is this statement?

**Comment by lrhn** [comment]
That would be section 16.33 "Identifier reference" which says (among other things):

> * If `d` is a class or type alias `T`, the value of `e` is an instance of class `Type` (or a subclass thereof) reifying `T`.

**Comment by sgrekhov** [comment]
@Irhn thank you. One more question. Where it is said that implementation of noSuchMethod() in class
Object must throw NoSuchMethodError? I didn't find it nor in Language nor in API specification. If so that means that it is allowed to be an implementation of Dart that doesn't throw NoSuchMethodError for e.v = x expressions, if e evaluates to an instance of some class that has noSuchMethod() inherited from an Object. I'm I right?

**Comment by lrhn** [comment]
The behavior of `Object.noSuchMethod` is only described in the platform library (https://api.dartlang.org/1.14.0/dart-core/Object/noSuchMethod.html), it's not part of the language specification. That means that, technically, you could have a Dart language implementation that doesn't throw in `Object.noSuchMethod`, but in practice that won't happen. The same thing goes for a lot of other "basic" functionality - the specification doesn't say what `int.operator+` does either, but it implicitly relies on the behavior being simple enough that it can be used as a compile-time constant operation.

**Comment by lrhn** [comment]
No plan to change the description here. The `noSuchMethod` on type objects is magically able to make a distinction between `C.foo` and `(C).foo` and give useful error messages.
