### ISSUE TITLE
enable core dump collection on dart2js buildbots

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#25645]
To debug random crashes that only occur on dart2js build bots we need to alter test runner to pass `--abort_on_assertion_errors` to underlying batch compiler process and change buildbot scripts to collect cores and upload them somewhere.

Fletch bots seem to have all necessary Python code to do that.

/cc @iposva-google @mkustermann

**Comment by mkustermann** [comment]
Additionally we also need to archive either a) a unstripped dart binary or b) a file which contains the extracted symbols (see for example [here](http://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target) for option b) ).

@whesse If you put this into annotated steps scripts, remember that this option is only present in the bleeding edge version of sdk, since @mraleph just added it, and not in the other channels/branches.
