### ISSUE TITLE
io/htp_proxy_test and io/secure_builtin_roots_test are timing out

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#25649]
The two standalone tests
io/htp_proxy_test 
io/secure_builtin_roots_test 
are timing out and need investigation.

**Comment by mraleph** [comment]
I noticed today that these tests are just disabled since Feb 2, 2016. Did something happen in this area? We have random timeouts on `io/*http*` tests - they might be connected. Can somebody revisit this issue?

**Comment by mraleph** [comment]
This issue has been last updated 304 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

Note: as comment above indicates this tests have been disabled. We should not have disabled tests.

**Comment by dcharkes** [comment]
This issue has not been updated for another year. Tests are still disabled. Investigating whether these are still issues.

These tests are also disabled by other status file entries (for other configurations. Sometimes even without issue numbers (I'll list the commits):

`io/http_proxy_test` is also disabled because of issue #27638, and by commits https://github.com/dart-lang/sdk/commit/bd2a8e1d60f (migrate most of the tests in standalone to be strong mode) and https://github.com/dart-lang/sdk/commit/848d3f4218a (Normalize standalone_2).

```dart
$ git grep -n 'io/http_proxy_test'
pkg/status_file/test/data/standalone_2_vm.status:68:io/http_proxy_test: Skip # Issue 27638
tests/standalone_2/standalone_2.status:100:io/http_proxy_test: Skip # These tests have started timing out and issue 25649 has been filed to investigate, skipping these tests temporarily to get the bots to be green again.
tests/standalone_2/standalone_2.status:134:io/http_proxy_test: Skip # Flaky.
tests/standalone_2/standalone_2_kernel.status:114:io/http_proxy_test: Skip # Flaky.
tests/standalone_2/standalone_2_vm.status:33:io/http_proxy_test: Skip # Issue 27638
```

Disabled by commits https://github.com/dart-lang/sdk/commit/dc35b04a189 (Update status file for different status on bots vs local) and https://github.com/dart-lang/sdk/commit/31d3d2c6b3a (Follow up fixes to make bots green), and because of issues #32137 and #32138:

```dart
$ git grep -n 'io/secure_builtin_roots_test'
tests/standalone_2/standalone_2.status:101:io/secure_builtin_roots_test: Skip # These tests have started timing out and issue 25649 has been filed to investigate, skipping these tests temporarily to get the bots to be green again.
tests/standalone_2/standalone_2_kernel.status:124:io/secure_builtin_roots_test: Timeout, Pass # Times out on bots.
tests/standalone_2/standalone_2_kernel.status:165:io/secure_builtin_roots_test: Pass, Timeout
tests/standalone_2/standalone_2_kernel.status:177:io/secure_builtin_roots_test: Skip # Issues 32137 and 32138.
```

The tests run fine on mac:

```dart
$ tools/test.py -m release -v standalone_2/io/http_proxy_test
Test configuration:
    custom configuration(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: mac, vm-options: [], timeout: null, preview-dart-2)
Suites tested: standalone_2
Running "vm" command: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --sync-async --ignore-unrecognized-flags --packages=/Users/me/dart-sdk/sdk/.packages /Users/me/dart-sdk/sdk/tests/standalone_2/io/http_proxy_test.dart
Done dartk-vm release_x64 standalone_2/io/http_proxy_test: pass

$ tools/test.py -m release -v standalone_2/io/secure_builtin_roots_test
Test configuration:
    custom configuration(architecture: x64, compiler: dartk, mode: release, runtime: vm, system: mac, vm-options: [], timeout: null, preview-dart-2)
Suites tested: standalone_2
Running "vm" command: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --sync-async --ignore-unrecognized-flags --packages=/Users/dacoharkes/dart-sdk/sdk/.packages /Users/dacoharkes/dart-sdk/sdk/tests/standalone_2/io/secure_builtin_roots_test.dart
Done dartk-vm release_x64 standalone_2/io/secure_builtin_roots_test: pass
```

The status file was updated at some point that one of these tests works on mac: https://github.com/dart-lang/sdk/commit/caede1d2ef7.

The status files line with _this_ issue number only disables it on linux:
```
[ $system == linux && ($runtime == flutter || $runtime == vm) ]
```

I'll try re-enabling these tests on linux to see whether they still fail.

**Comment by dcharkes** [comment]
Tests have not timed out last two weeks, closing issue.
