### ISSUE TITLE
yield* does not throw exception, which is thrown by getter current

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25662]
The Dart Programming Language Speciﬁcation (4th edition draft) version 1.11, chapter 17.16.2 Yield-Each reads:

>    Execution of a statement s of the form yield* e; proceeds as follows:
>    First, the expression e is evaluated to an object o.
>    If the immediately enclosing function m is marked sync* (9), then:
> 1. It is a dynamic error if the class of o does not implement Iterable. Otherwise
> 2. The method iterator is invoked upon o returning an object i.
> 3. The moveNext method of i is invoked on it with no arguments. If moveNext
> returns false execution of s is complete. Otherwise
> 4. **The getter current is invoked on i. If the invocation raises an exception ex,
> execution of s throws ex.** Otherwise, the result x of the getter invocation
> is added to the iterable associated with m. Execution of the function m
> immediately enclosing s is suspended until the nullary method moveNext()
> is invoked upon the iterator used to initiate the current invocation of m,
> at which point execution of s continues at 3.

The following test demonstrates violation of highlighted sentences.

```dart
class TestException {
}

class IteratorStub extends Iterator<int> {

  @override
  int get current => throw new TestException();

  @override
  bool moveNext() => true;
}

class IterableStub extends Iterable<int> {

  Iterator<int> get iterator => new IteratorStub();
}

var actualException;

Iterable generator(Iterable iterable) sync* {
  try {
    yield* iterable;
  } on TestException catch (x){
    actualException = x;
  }
}

main() {
  IterableStub its = new IterableStub();
  var empty = generator(its).isEmpty;
  print("empty: $empty (expected: true)");
  print("actualException: $actualException");
}
```
Output:

> Unhandled exception:
> Instance of 'TestException'
> #0      IteratorStub.current (file:///D:/test.dart:7:22)
> #1      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:55)
> #2      Iterable.isEmpty (dart:core/iterable.dart:376)
> #3      main (file:///D:/test.dart:31:30)
> #4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
> #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Expected output:

> empty: true (expected: true)
> actualException: Instance of 'TestException'

Dart VM version: 1.14.0 (Thu Jan 28 10:51:15 2016) on "windows_x64"

**Comment by iposva-google** [comment]
@mhausner Sounds similar to some of the issues you have been looking at recently.

**Comment by mhausner** [comment]
Here is what dart2js with the d8 runtime produces:

empty: false (expected: true)
actualException: null

Interestingly, the getter "current" never is called. Thus, no exception is thrown. I don't know why "current" is not called. moveNext is invoked.

/cc @floitschG

**Comment by floitschG** [comment]
@kmillikin: iirc, the yield* has been added, so that we don't need to worry about nested iterables (to avoid the exponential explosion). I believe that this means that we shouldn't deal with each individual value in the sync* function.

If that's the case, then yield* should just pipe through its values (potentially throwing if one of the moveNext or current throws). Obviously, we could also make it dependent on potential try/catch around the yield* (which would require more work from the VM and dart2js).

If we pipe the values just through we have two options:
- fetch the nested current as soon as moveNext succeeded, or
- redirect the outer current to the nested current.

Currently the VM fetches as soon as moveNext succeeded, and dart2js redirects.
It is trivial to switch from one to the other (see patch below), so if we don't fetch each value individually we should decide which one we prefer.

```
diff --git a/sdk/lib/_internal/js_runtime/lib/async_patch.dart b/sdk/lib/_internal/js_runtime/lib/async_patch.dart
index 4d91d79..86cc1ee 100644
--- a/sdk/lib/_internal/js_runtime/lib/async_patch.dart
+++ b/sdk/lib/_internal/js_runtime/lib/async_patch.dart
@@ -441,12 +441,10 @@ class _IterationMarker {
 class _SyncStarIterator implements Iterator {
   final dynamic _body;
 
-  // If [runningNested] this is the nested iterator, otherwise it is the
-  // current value.
   dynamic _current = null;
-  bool _runningNested = false;
+  Iterator _nestedIterator = null;
 
-  get current => _runningNested ? _current.current : _current;
+  get current => _current;
 
   _SyncStarIterator(this._body);
 
@@ -474,11 +472,12 @@ class _SyncStarIterator implements Iterator {
 
 
   bool moveNext() {
-    if (_runningNested) {
-      if (_current.moveNext()) {
+    if (_nestedIterator != null) {
+      if (_nestedIterator.moveNext()) {
+        _current = _nestedIterator.current;
         return true;
       } else {
-        _runningNested = false;
+        _nestedIterator = null;
       }
     }
     _current = _runBody();
@@ -493,8 +492,7 @@ class _SyncStarIterator implements Iterator {
         JS('', 'throw #', _current.value);
       } else {
         assert(_current.state == _IterationMarker.YIELD_STAR);
-        _current = _current.value.iterator;
-        _runningNested = true;
+        _nestedIterator = _current.value.iterator;
         return moveNext();
       }
     }
```

**Comment by mhausner** [comment]
Looking at the original bug report again, I think the expectation "empty: true (expected: true)" is incorrect. IteratorStub.moveNext() returns true, so it is fair for an implementation to say that the stream is not empty. Thus, I think the dart2js output is correct.

If you replace the the call to isEmpty with this:

var e = generator(its).first;

Then a TextException is thrown, as expected, but it is not caught in the catch-block of the generator.

```
d8 out.js
sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: Instance of 'TestException'
          throw e;
          ^
Instance of 'TestException'
    at dart.wrapException (out.js:586:17)
    at IteratorStub.dart.IteratorStub.get$current (out.js:1665:17)
    at _SyncStarIterator.dart._SyncStarIterator.get$current (out.js:1192:24)
    at dart.main (out.js:1656:10)
    at action (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at out.js:1976:23
    at init.currentScript (out.js:1962:7)
    at out.js:1973:5

[d2 sdk]$ 
```

I'm still looking into why the VM doesn't catch the exception.

**Comment by alsemenov** [comment]
As reporter of the bug I agree that the expectation "empty: true (expected: true)" is incorrect. But as @mhausner noticed, the bug is still valid, if `isEmpty` is replaced by `first`

**Comment by alsemenov** [comment]
After second thought I think that expectation  "empty: true (expected: true)" is correct.
Let's consider the `Iterable` instance returned by function `generator`.
If its `isEmpty` gives false (because underlying `iterator.moveNext()` returns true), then we can ask for some element via, for example, `first`. `first` description reads:

> Returns the first element.
> 
> Throws a StateError if this is empty. Otherwise returns the first element in the iteration order, 
>equivalent to (iterator..moveNext())..current.
 
Since underlying `iterator.current` throws exception, which is caught in `generator()`, there is nothing to return. So there is contradiction: `Iterable` returned by the `generator()` is actually empty, but . Therefore `first` have to throw  a StateError. 

From the developer point of view we have an unexpected StateError. Unexpected, because underlying errors were caught and handled.

**Comment by kmillikin** [comment]
@alsemenov that is indeed a contradiction.  To me it suggests that the spec behavior is not actually the desired behavior.  `yield* iterable` should only throw if evaluation of `iterable` or `iterable.iterator` throws.  It should not call `.current`.  (I think this is what @mhausner and @floitschG are suggesting above.)

If we have the function:

```dart
Iterable id(Iterable it) {
  yield* it;
}
```

Then `id(E)` should behave just as `E`.  With the spec behavior, they can be distinguished by:

```dart
void safelySkip5(Iterable it) {
  var iterator = it.iterator;
  for (int i = 0; i < 5; ++i) {
    if (!it.moveNext()) return;
  }
}
```

Since one of the use cases of generator functions is to avoid computing values until they are demanded, I don't think yield* should demand values before they are *really* demanded.

cc @gbracha

**Comment by floitschG** [comment]
Expanding on Kevin's comment: there are two different ways of looking at `yield*`:
1. `yield*` is syntactic sugar for a loop that iterates over the given iterable and `yield`s the elements.
2. `yield*` passes the iterable to the user (going through some functionality that flattens it).

In the first case, errors in the nested iterable are passed to the user (and the try/catch is ignored). In the second case the try/catch triggers, but the evaluation is less efficient. The reason we added `yield*` was to be more efficient (and avoid some exponential behavior).

Note that we have a similar question with `async*`, where stream-controllers have an `addStream` function. Both implementations pass nested streams (given to `yield*`) to that function and pass through the errors.

```
import 'dart:async';

foo(s) async* {
  yield* s;
}

foo2(s) async* {
  await for (var x in s) yield x;
}

main() {
  var sc = new StreamController();
  var s = foo(sc.stream);  // <== foo or foo2
  s.listen(print, onError: print);
  sc.add(1);
  sc.addError(2);
  sc.addError(3);
}
```

Depending on whether we use `foo` or `foo2` in the main, the output is different here.
If it's `foo`, then we see 1, 2 and 3. Otherwise, the error `2` shuts down the `foo2` stream and `3` is dropped.

Kevin and I are arguing that this is the most useful and reasonable semantics: `yield*` should pass the iterable/stream to the controller and not run through the elements by itself.

**Comment by mhausner** [comment]
What @floitschG explained is a good summary. Here is a code example for the synchronous case.

```
class IteratorStub extends Iterator {
  get current { throw "Error in current"; return 0; }
  moveNext() => true; 
}

class IterableStub extends Iterable {
  Iterator get iterator => new IteratorStub();
}

Iterable foo(iterable) sync* {
  try {
    yield* iterable;
  } catch(e) {
    print("Caught in foo: $e");
  }
}

Iterable bar(iterable) sync* {
  try {
    for (var i in iterable) yield i.current;
  } catch(e) {
    print("Caught in bar: $e");
  }
}

main() {
  IterableStub its = new IterableStub();
  try {
    var a = foo(its).first;  
  } catch(e) {
    print("caught in main: $e");
  }
}
```

When foo is invoked from main, the VM produces:
```
[d2 sdk]$ dart ~/tmp/s1.dart
caught in main: Error in current
```
When bar is invoked from main, the VM produces:
```
[d2 sdk]$ dart ~/tmp/s1.dart
Caught in bar: Error in current
caught in main: Bad state: No element
```

The try-catch in foo() does not catch the "Error in current" error because the flattening happens outside of foo(), in a piece of library code that implements the iterator class for sync* Iterable objects. This is essentially case (2) in @floitschG's explanation.

I'm holding off with a fix until we decide which semantics we really want.

**Comment by alsemenov** [comment]
So far I have no good advice for you.
However I must note:
1. All implementations must behave the same way. 
2. Try-catch should catch the exceptions everywhere.
3. I am afraid I do not understand, why there is need in 
```dart
Iterable foo(iterable) sync* {
    yield* iterable;
}
```
which is equivalent to 
```dart
Iterable foo(iterable) sync* {
    return iterable;
}
```
Why would a developer need to write such generator?

**Comment by kmillikin** [comment]
I'm not suggesting that a developer would write such a generator.  It's an equality that a developer would use to reason about the behavior of programs containing yield*.

(You mean to leave sync* off the second implementation of foo, there's no return in generator functions.)

**Comment by alsemenov** [comment]
I am sorry, I forgot to remove sync* in second implementation

**Comment by mhausner** [comment]
As of 761ee7ec042670e11742e6e1b99c1973c1ce750c the VM no longer eagerly fetches the current element of the yielded iterable. The VM and dart2js now do the same thing.

We'll take care of the spec to reflect that the flattening of the yielded iterator does not happen in the context if the yield* statement.

**Comment by mhausner** [comment]
We will update the Spec to it reflects that the flattening of a yield* happens outside of the scope of the yield* statement, in the (invisible) caller of the sync* generator function.

**Comment by alsemenov** [comment]
The issue about specification is #25634

**Comment by rakudrama** [comment]
If __yield*__ ignores that it is inside a try-finally, how does one write code that manages resources?

We could honour the specification, but recognize that we can't tell where the __yield*__ is flattened when it is not inside a try-statement that observes the exceptions and completion. Expand __yield*__ to a loop inside a try-statement and pass the iterable out for latter flattening when it its not.

**Comment by kmillikin** [comment]
@rakudrama, it is not the intent that it can ignore whether it is inside a try-finally.

The issue here is that according to the 4th ed. spec `yield* e` evaluates `e`, calls `moveNext()` on it, **and then calls the getter `current`**.  This last part should be removed from here, since "searching" the function body for a `yield` or `yield*` is driven by `moveNext` and should not call `current`.

Otherwise, if a generator function used yield* with an iterator where computing `current` is expensive, the iterator corresponding to the generator function invocation incurs the expense of calling `current` for each call to `moveNext` and there's no way to avoid it.

It should still be the case that exceptions are thrown and caught, but it's the call to `current` on the generator function's iterator that throws when `current` throws on the "inner" iterator, not the call to `moveNext` that throws when `current` throws on the "inner" iterator.  I would argue that this more closely matches the programmers expectation anyway.

**Comment by rakudrama** [comment]
@kmillikin Sorry for my confusion, which stems from several things:

1. Neither `moveNext()` nor `current` are currently executed in the try-scope of the yield* on VM and dart2js.
2. MappedIterable.moveNext() computes a `_current` value uses the underlying iterator's `current`.

It makes sense for yield* not to call `.current`, so that `.length` and `.skip(n)` do not evaluate the elements, but that is a bit limited when `a.map(f).length` may or may not apply `f` depending on the type of `a`.

Is there an issue for tracking that moveNext() over the yield* argument currently 'ignores' an enclosing try-statement? 

---
```
class MappedIterator<S, T> extends Iterator<T> {
  T _current;
  final Iterator<S> _iterator;
  final _Transformation<S, T> _f;

  MappedIterator(this._iterator, T this._f(S element));

  bool moveNext() {
    if (_iterator.moveNext()) {
      _current = _f(_iterator.current);
      return true;
    }
    _current = null;
    return false;
  }

  T get current => _current;
}
```

**Comment by kmillikin** [comment]
That does seem like a bug and I couldn't find an issue.  I filed https://github.com/dart-lang/sdk/issues/26262
