### ISSUE TITLE
set a limit on the number of problems the analysis server sends to the IDE

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25670]
When a large Dart project is misconfigured (say, a directory is renamed or goes away), the analyzer can easily send many thousands of problems to the IDE due to missing imports. In some cases this can cause the IDE to become unresponsive. We should set a hard limit on this (perhaps a max of 1000 per analysis root).

Ideally the analyzer would send only the most important messages that are likely the root of the problem. If an import is missing, there's little point in also reporting on the downstream consequences of it.

**Comment by bwilkerson** [comment]
The other option is to ask clients to filter. The advantage there is that users could be given an option to display all of the errors if they (thought they) wanted to see them.

**Comment by zoechi** [comment]
It's difficult to change the filter when the IDE becomes unresponsive.
I also think if a file has a "big" number of errors and warnings, hints and linter warnings become irrelevant.

**Comment by alexander-doroshko** [comment]
@skybrian, @zoechi Is this a theoretical issue or you really noticed the problem in some IDE (which one)?
I tested WebStorm 11.0.3 and IntelliJ IDEA 15.0.3 with 102000 of problems from the analysis server. There were zero lags in IDE responsiveness. Grouping and filtering features at IDE side work well too. I think IDE is able to work with millions of errors too.
IDEs that have problems dealing with too many errors may limit the number of handled ones themselves, IMO there's not need for such feature at server side.

**Comment by zoechi** [comment]
@alexander-doroshko 
I'm using WebStorm and working is often quite cumbersome, WebStorms reindexing and Dart Analyser fighting for CPU resources.
I was sure I reported an issue recently about that but can't find it :-( 
I have some projects with lots of **small** sub-projects (which are not related in any way by dependencies) and it seems DartAnalyzer analyses the whole project as soon as I start editing a single file.
I'm considering buying a new PC but I'm not sure this will change much.

I can't point down the performance issues down to the number of reported errors but it sounds wasteful to get thousands of meaningless hints that I then need to filter while waiting for the IDE to respond eventually.

**Comment by alexander-doroshko** [comment]
@zoechi Your comment may be valid or not, but it is not related to the requested feature about limiting the number of problems that server sends to the IDE. My point is that this feature at server side is not needed because the number of errors sent is not itself a problem and IDEs may do whatever they want with them.

We can discuss ways of making IDE performance better with large projects, but definitely not in comments to this request.

**Comment by skybrian** [comment]
How well this scales depends on the editor. I didn't see it myself, but I heard there was O(n^2) bug in the Dart plugin for IDEA (now fixed). Probably other editors would run into it if they just do the naive thing when displaying errors (no filtering and not testing how it scales).

If we want people to have a good experience in a variety of editors (with varying quality Dart plugins), I think we should default to a safe limit that will perform well out of the box. Perhaps there could be an option to increase or remove the limit when the editor plugin is prepared to handle it.

**Comment by bwilkerson** [comment]
I think that if authors of clients request this feature, or if we find evidence (in hard numbers) that it's the right thing to do, that we should revisit it.

In the meantime, I think we'd be doing more good for our users to improve our ability to recover from errors so that we do not generate 10's (or 100's) of errors for the same root cause.
