### ISSUE TITLE
RTE dart2js when creating a Uint8Array from a MappedListIterable

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#25704]
The following code runs fine in DartVM, but RTE's after dart2js:

Stream<Uint8List> get value$ => _state$.stream
    .map((Iterable<Tuple6<int, int, Shape, Rotation, Color, bool>> cells) => cells.map(_cellToValue))
    .map((Iterable<int> list) => new Uint8List.fromList(list)); // this line RTE

The js debugger complains about a method '$index' not found from within an isolate

To fix this, I had to call toList on the MappedIterable first:

Stream<Uint8List> get value$ => _state$.stream
    .map((Iterable<Tuple6<int, int, Shape, Rotation, Color, bool>> cells) => cells.map(_cellToValue))
    .map((Iterable<int> list) => new Uint8List.fromList(list.toList(growable: false))); // no more RTE

**Comment by sigmundch** [comment]
My guess is that this is as intended since `Uint8List.fromList` is declared to expect a List. I assume that if you run the first program in checked mode, then the dartvm also produces a RTE. Correct?

It seems that the dart2js implementation of this constructor does assume that the input is a List, while the VM doesn't only relies on the APIs that are also part of Iterable, so it just happens to work there. We could change the code [here][1] to do `result.addAll(list)` instead, but it's likely going to be more expensive.

[1]: https://github.com/dart-lang/sdk/blob/5e615e9c3118f783c1ab883686e5acac5a1ab781/sdk/lib/_internal/js_runtime/lib/native_typed_data.dart#L407

/cc @lrhn

**Comment by frankpepermans** [comment]
I need to doublecheck but I think it works in the vm with checked true. Even the analyser strict mode doesn't complain for me.

**Comment by lrhn** [comment]
It wouldn't give a warning because you are passing an `Iterable` to a function expecting a `List`, and `Iterable` is assignable to `List`.

It should fail at runtime in checked mode because the `Iterable` isn't actually a `List`.
