### ISSUE TITLE
Unexpected deadlock on stream cancellation

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25703]
The following code demonstrates the problem:
```dart
import 'dart:async';

Stream<int> generator(Stream<int> input, Future startTrigger) async* {
  await startTrigger;
  yield* input;
  print("generator finished");
}

main() async {
  Completer c = new Completer();
  Stream<int> s = generator(new Stream.fromIterable([1, 2, 3]), c.future);
  StreamSubscription<int> ss = s.listen(
      (int i){
        print(i);
      }
  );
  print("subscribed");
  ss.pause();
  print("subscription paused");
  await ss.cancel();
  print ("subscription cancelled");
  c.complete(); // pass control to yield*
  print("startTrigger released");
}
```

Output:
>subscribed
>subscription paused

Expected output:
>subscribed
>subscription paused
>subscription cancelled
>startTrigger released

Dart VM version: 1.14.1 (Wed Feb 03 11:59:06 2016) on "windows_x64"

Dart VM stops execution of the program on line `await ss.cancel()` .
I guess there is some deadlock and due to #23797 Dart VM stops the program.
I reported this issue, because it is not clear to me why cancelling the subscription 
to the stream, which is waiting for events, cause the deadlock?
I expected, that stream subscription can be cancelled anyways.

**Comment by floitschG** [comment]
The behavior is the same on the VM and on dart2js.
I haven't yet looked at the spec, but this is probably the expected behavior.

I looked a bit at dart2js. In the current implementation, the async*-controller only runs the finalizers of the async* body, when the 'await' expression could return.
That is, in the following example, "finally" is only printed, when `someFuture` completes.
```
foo(someFuture) async* {
  try {
    await someFuture;
  } finally { print("finally"); }
}
```

When calling `cancel` on the Stream-subscription it will return a future, that is completed, once all finalizers have been run.
It will:
- wait for the 'await' to finish.
- then invoke all finalizers
- complete the cancel-future.

In your example the `await` never finishes, and the VM (and dart2js) correctly recognize that there won't be any progress in the program anymore and stop.

**Comment by lrhn** [comment]
I agree with Florian.
The async generator function is blocked at `await startTrigger;`.
The cancel of the subscription won't have any effect until the generator reaches a `yield` statement, so the future returned by the `cancel` call won't ever complete. That means that `await ss.cancel();` won't complete, so you won't reach `c.complete()` below. At this point you have no scheduled microtasks or timers, so your program terminates. The two `await` statements are waiting on futures that won't complete.

Canceling a subscription on a stream from an async generator function has two effects:

- All yield statements in the generator function invocation now act like return statements, and
- The termination of the function invocation completing will be used to complete the cancel future.

Apart from that, the cancel doesn't do anything. It won't stop execution at an `await`, only at a `yield`.

**Comment by alsemenov** [comment]
I'd like to clarify the point of this issue.
Method `StreamSubscription.cancel()` means to me `stop receiving events from given stream`
I do not care if the stream is blocked or waiting for something. Just exclude me from subscribers of this stream and let me go further. 
The official description for method `StreamSubscription.cancel()` reads

> Cancels this subscription. It will no longer receive events.
> 
> May return a future which completes when the stream is done cleaning up. This can be used if the stream needs to release some resources that are needed for a following operation, for example a file being read, that should be deleted afterwards. In that case, the file may not be able to be deleted successfully until the returned future has completed.
> 
> The future will be completed with a null value. If the cleanup throws, which it really shouldn't, the returned future will be completed with that error.
> 
> Returns null if there is no need to wait.

My point is that stream clean up is not related to cancelling the subscription. Stream clean up should be performed independently from subscription cancelling. Otherwise it cause deadlocks similar to described in this issue. With current description the method should be renamed to something like `cancelAndCloseStream`

Also it is not clear to me why the sample code does not deadlock if I use broadcast wrapper:
```Stream<int> s = generator(new Stream.fromIterable([1, 2, 3]), c.future).asBroadcastStream();```

**Comment by floitschG** [comment]
The future for cancel calls was introduced specifically to make sure that the stream has the time to clean up. Specifically, we wanted to be able to cancel a stream that was reading from a file, and be sure that the file wasn't open anymore, when the future for `cancel` was completed.

Broadcast streams provide fewer guarantees than single-subscription streams. A subscription to a broadcast stream can't be sure that the stream is fully canceled (since it might have more subscribers), and therefore won't wait for the stream to clean up (even if it was the last subscription).

**Comment by lrhn** [comment]
If you don't care about stream clean-up and just want to go on, all you need to do is *not* await the future returned by calling `cancel`. By awaiting that future you chose to wait for stream clean-up. Since the stream generator function is blocked for another reason, in async code not related to being a generator, it won't get to the clean-up that you are waiting on. That's not unique to async generator functions, it could also happen with a `StreamController` where the `onCancel` callback returns a `Future` that never completes.

As Florian says, the stream returned by `asBroadcastStream` doesn't forward the cancel future of the original stream subscription to the broadcast-stream subscriptions. It's unclear which one would get it anyway. If you need to handle clean-up, you can do it in the `onCancel` callback you can pass to `asBroadcastStream`.

I disagree that cancel and clean-up is unrelated. For a single-subscription stream, the two are tightly coupled. An alternative could be to send a done event after the cancel has completed, but that complicates the story about not getting events after calling cancel.

In any case, it's not something we can or will change now.

**Comment by alsemenov** [comment]
Do I understand correctly, that `cancel` does not immediately return `Future` instance? But unsubscribes the listener first and only then schedule stream clean up and return `Future`. In other words, is it guaranteed that listener is unsubscribed, when `cancel` returns?
If it is so, I think, the description of method `cancel` should be improved to avoid confusion.

**Comment by floitschG** [comment]
Once `cancel` has been invoked, the listener will not get any message anymore.

I will try to make this more clear in the documentation.

**Comment by floitschG** [comment]
Updated the documentation in 381c12df4ade7cfe67aedd391a1896072a6fc799
