### ISSUE TITLE
Add line & column to AnalysisError

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#25717]
If readily available in the analyzer, this would help speed up error reporting in DDC's transformer (where Barback's error reporting requires line & column).

**Comment by bwilkerson** [comment]
The information is available in an instance of LineInfo, which can be accessed through the AnalysisContext. If you use AnalysisContext.getErrors(Source source) to access the errors, the AnalysisErrorInfo that is returned has the LineInfo in it. Otherwise you can use AnalysisContext.getLineInfo(Source source) to access it separately.

**Comment by ochafik** [comment]
Awesome, thanks Brian!
