### ISSUE TITLE
Would like a way to disable analysis of all pub_cache packages

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#25722]
Flutter has lots of packages and we want to analyze all of our local packages, but we don't want to analyze any pub_cache packages.

We could build a whitelist if that's necessary.

Right now our analyzer wrapper invokes the analyzer but then filters out anything under .pub_cache:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze.dart#L291

This came up again because we had an environment where PUB_CACHE was set, and that regexp was no longer matching. :/  e.g.:
https://build.chromium.org/p/client.flutter/builders/Linux/builds/43/steps/flutter%20analyze/logs/stdio
(url may be invalid after some number of days).

Maybe the new analyzer plugins already allow this?  A quick look didn't seem that they could control what got analyzed:
https://github.com/flutter/experimental-temporary-dartanalyzer-fork

@pq @Hixie

**Comment by pq** [comment]
Nope.  Plugins won't really handle this (and nor should they I think).  The underlying issue is that we need to communicate better to the analyzer CLI exactly what resources we want to have analyzed (and not use blunt instruments like the `--package-warnings` flag).  To get us where we really want to get I think we want support for directory-based analysis (https://github.com/dart-lang/sdk/issues/25129).

Feel free to re-open if you disagree!
