### ISSUE TITLE
Release build not working in firefox and causing stack size errors in Chrome

### ISSUE THREAD

**Issue by Meai1** [dart-lang/sdk#25731]
Hi, 
I tried switching to Dart today but I'm not sure I should do it when I cant do release build right?

I have attached a full code sample that illustrates the problem if you compile it in release mode.

Firefox 43.0.03/46.0a2 nightly
Firefox/Debug: everything works
Firefox/Release: doesnt show anything on page, error in console has no description

Chromium 39.0/Chrome 48.0
Chrome/Debug: everything works
Chrome/Release:  Uncaught RangeError: Maximum call stack size exceeded.

[web.zip](https://github.com/dart-lang/sdk/files/123309/web.zip)

**Comment by sigmundch** [comment]
@Meai1 thanks for filing the bug - just to figure out how to repro:
 - what do you mean by release mode/debug? Do you mean when compiling with `pub-build --mode=release`?
 - which version of the SDK are you using?

**Comment by Meai1** [comment]
In intellij when I click on the pubspec.yaml there is an option to press "release", that's the one I mean.
The SDK was 1.14.1

**Comment by sigmundch** [comment]
OK I can reproduce by building via `pub build` as well.

I'm not entirely sure what the problem is at this moment.

Custom elements `created` callback is invoked synchronously when creating the DOM tree. The stack overflow sometimes indicates that a nested element is created while your created callback was invoked. I don't see anything in your code that could cause that, but interestingly if I move the body of `.created` into an asynchronous callback, then your code works fine in release mode in chrome. 

I am not sure if the validator might be causing some issues, in particular if I changed the validator and replace it with the trusted tree-sanitizer (see example below), then again, I can get the app to work in release mode in chrome.

```dart
var validator = new NodeValidatorBuilder.common();
class MyCustomElement extends HtmlElement {
    factory MyCustomElement() => new Element.tag('x-custom');
    MyCustomElement.created() : super.created() {
      this.appendHtml('<div>example</div>', validator: validator);
    }
  }

void main() {
  initWebComponents().then((_) {
    document.registerElement('x-custom', MyCustomElement);
    var myBar = new MyCustomElement();
    document.body.append(myBar);
  });
}
```

/cc @alan-knight maybe he is aware of something in the default validator builder that could be causing this?

**Comment by alan-knight** [comment]
I haven't seen anything like this before, but the validator does create the elements in a document fragment. Maybe it could somehow get into a cycle where it then tries to recreate the element again in another document fragment? The trusted sanitizer just skips the whole process. That's probably what you want to do anyway, if it's constant HTML that you wrote, so there's no possibility of hostile HTML.

**Comment by kevmoo** [comment]
We're going to deprecate registerElement
