### ISSUE TITLE
DateTime constructors: non-informative exception if null argument passed

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25746]
```dart
new DateTime.fromMillisecondsSinceEpoch(null, isUtc: true);
```
The code above produces
```
Unhandled exception:
The null object does not have a method '*'.

NoSuchMethodError: method not found: '*'
Receiver: null
```
The same proble. The code
```dart
new DateTime.fromMicrosecondsSinceEpoch(null, isUtc: true);
```
The code above produces
```
Unhandled exception:
The null object does not have a method '~/'.

NoSuchMethodError: method not found: '~/'
Receiver: null
```
Dart API documentation doesn't specify what should happen if null instead of int passed as an argument, but, I believe, there should be either no exception at all or somethihng more informative, like FormatException or ArgumentError

**Comment by floitschG** [comment]
The core libraries don't do explicit null-checks, and rely on common nullpointer exceptions.
This will get better, once we have non-nullable types.

In general we don't document what kind of Error is thrown (we do that only for exceptions). Programs should therefore not rely that a specific error is thrown. (This is the reason why we often use the wording "It is an error to..." instead of stating which kind of error is thrown. It also gives us the flexibility not to throw at all).
