### ISSUE TITLE
Short sleeps on Windows do not work reliably

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#25757]
As seen from tests/standalone/io/sleep_test.dart

stderr:
  Unhandled exception:
  Expected: a value greater than or equal to <1>
    Actual: <0>
     Which: is not a value greater than or equal to <1>

**Comment by sgrekhov** [comment]
This issue is still actual.

```dart
import "dart:io";

test(int dur) {
  Stopwatch sw = new Stopwatch();
  sw.start();
  sleep(new Duration(milliseconds: dur));
  sw.stop();
  print("Expected ${dur} milliseconds. Acually slept for: milliseconds: ${sw.elapsedMilliseconds}, microseconds: ${sw.elapsedMicroseconds}");
}

main() {
  test(5);
  test(100);
  test(100);
  test(100);
  test(1000);
  test(1000);
  test(1000);
  test(0);
}
``` 
This program prints
Expected 5 milliseconds. Acually slept for: milliseconds: 8, microseconds: 8095
Expected 100 milliseconds. Acually slept for: milliseconds: 98, microseconds: 98570
Expected 100 milliseconds. Acually slept for: milliseconds: 99, microseconds: 99950
Expected 100 milliseconds. Acually slept for: milliseconds: 100, microseconds: 100943
Expected 1000 milliseconds. Acually slept for: milliseconds: 999, microseconds: 999955
Expected 1000 milliseconds. Acually slept for: milliseconds: 999, microseconds: 999956
Expected 1000 milliseconds. Acually slept for: milliseconds: 1001, microseconds: 1001940
Expected 0 milliseconds. Acually slept for: milliseconds: 0, microseconds: 8

Dart VM version: 2.2.0-dev.1.1 (Thu Dec 13 12:40:26 2018 +0100) on "windows_x64"

**Comment by dcharkes** [comment]
Okay, if (at least one of) the OSes specify the `sleep` command to be approximately instead of at least x milliseconds, then we need to either change the Dart spec to approximately, or do a fix in Dart to sleep some extra if we slept too short. This is a language/library design decision.

**Comment by lrhn** [comment]
The likely issue here, which is one we have seen before, is that the granularity of `sleep` is lower than the one of `Stopwatch`.
If you do a 10 millisecond sleep at a time ending in ...35876 µs, then the system might think that 10 ms has passed at ...45123 because the time truncated to milliseconds _have_ advanced by 10. The µs granularity stopwatch can detect that only 9.247 ms have actually passed.
It means that the error is always less than one ms.

I believe our timers "solved" that problem by adding one ms to the wake-up time (from `timer_impl.dart`)
```dart
int wakeupTime = (milliSeconds == 0) ? now : (now + 1 + milliSeconds);
```
The `+ 1` is there exactly for this reason. It does mean that we wait *too long* in almost all cases. The user feed-back (read: bug reports) suggested that it was better to err in that direction.
