### ISSUE TITLE
Several mixin application issues

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25765]
There are several issues here and its unclear which one is an issue and which one is not.

1) It's not clear from the specification if is it allowed or not if superclass is used as a mixin

``` dart
class S {
}
class C extends S with S {
}
main() {
  new C();
}
```

This code produces no warnings in analyzer but when runned

```
error: super type 'S' may not be listed in implements clause of class 'S&S'
class C extends S with S {
                       ^
```

2) The following code works (no warnings in analyzer, no errors when runned)

``` dart
class A {
}
class S extends A {
}
class C extends S with A {
}
main() {
  new C();
}
```

In fact both `S with S` and `S with A` should not add anything to the superclass of C, but one of them works and the other not. 

3) Again the code below works well

``` dart
class S {
}
class M {
}
class C extends S with M, M, M, M {
}
main() {
  new C();
}
```

Was this intended?

Please clarify which of the cases above are bugs and which one not. 

Tested on Dart VM version: 1.15.0-dev.2.0 (Wed Feb 10 02:55:12 2016) on "windows_x64"

**Comment by anders-sandholm** [comment]
Not clear if this is a spec (area-language) or implementation (area-vm) issue.
Feel free to reassign labels as you see fit.

**Comment by lrhn** [comment]
Never noticed this issue before, sorry.

I think the behaviors are all correct.

There is nothing inherently wrong with mixing a mixin derived from a class on top of the class itself.
The only reason you get an error is that applying a mixin also makes the class *implement* the mixin's class' interface, and there is a specific rule saying that you are not allowed to extend and implement the same type in the same class declaration (not because it matters, it would work perfectly fine, it's just not useful, so it's assumed to be an error).

So, the `S with S` mixin application introduces a new anonymous class that both extends `S` and implements `S` and that gives an error.

The `S with M, M` introduces a new anonymous class for `S with M` which implements `M`, and an anonymous class for `(S with M) with M` which also implements `M`, but each class only implements M once, and `M` itself is not the superclass of any of them.
