### ISSUE TITLE
Mixin superclass members are not mixed into

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#25762]
If mixin class has a superclass, members of this superclass are not mixed into derived class. Example:
```dart
class S {
  int get g1 => 1;
}

class M1 {
  int get g2 => 2;
}

class M2 extends M1 {
  int get g3 => 3;
}

class C extends S with M2 {
}

main() {
  C c = new C();
  print(c.g1);
  print(c.g2);
  print(c.g3);
}
```
Result of running this program is:
```
Unhandled exception:
Class 'C' has no instance getter 'g2'.

NoSuchMethodError: method not found: 'g2'
Receiver: Instance of 'C'
```
Tested on Dart VM version: 1.15.0-dev.1.0 (Tue Feb 02 15:23:34 2016) on "windows_x64"

**Comment by kasperl** [comment]
This is entirely by design; see https://www.dartlang.org/articles/mixins/.

_In a language supporting classes and inheritance, a class implicitly defines a mixin. The mixin is usually implicit—it is defined by the class body, and constitutes the delta between the class and its superclass. The class is in fact a mixin application—the result of applying its implicitly defined mixin to its superclass._

You can mix in both `M1` and `M2` to get the effect you're after.

```dart
class C extends S with M1, M2 {
  ...
}
```

**Comment by sgrekhov** [comment]
@kasperl thank you for clarification. But I think there is an issue anyway because Dart analizer produces no any warning in the case from the description. Going to fill a separate issue for that

**Comment by kasperl** [comment]
@sgrekhov That's a very, very good point. The analyzer should definitely find and flag this issue. I believe the warning should come in the form of a warning that `C` doesn't implement the `g2` method.

The language spec says in section 12.1 (slightly rewritten):

_Let C be a class declaration that includes M in a with clause. It is a static warning if C does not implement, directly or indirectly, all the direct superinterfaces of M._
