### ISSUE TITLE
element.animate() returning type Animation instead of documented AnimationPlayer

### ISSUE THREAD

**Issue by tonyclickspace** [dart-lang/sdk#25799]
Demo: https://dartpad.dartlang.org/f4ad8d86e1b01d901950

Working as of Dart 1.12.2
Stopped working, Dart 1.13.0+

Part of the Web Animation API.

**Comment by alan-knight** [comment]
The spec, and the underlying browser behaviour changed. See https://developer.mozilla.org/en-US/docs/Web/API/Element/animate 

This should be fixed when we (very shortly) update the HTML library to be based on Chrome 45 IDL instead of Chrome 39, as part of the Dartium roll. But the fix is that the documented type will become Animation.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by terrylucas** [comment]
Closed in dev channel new sdk/lib generated from 45 IDLs are checked into bleeding edge.
