### ISSUE TITLE
Add UnreachableError to core

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#25809]
We should have an UnreachableError in core.
These are one of the few throw-locations, were the existing errors don't cover the use-case.

**Comment by lrhn** [comment]
I think I would use an assert for that instead of a throw. Asserts are exactly for things that won't happen. 

You shouldn't have unreachable code at all (for several reasons, one being that you can't test it), but some switch statements don't have a default case and defensive programming says that you should be prepared to handle a fallthrough. If reaching the default case isn't a caused by a `StateError` or `ArgumentError`, I would just write `assert(false); // unreachable`

**Comment by floitschG** [comment]
The problem with asserts are, that they don't count for "this function doesn't return something".

**Comment by lrhn** [comment]
If we are just trying to silence a warning, I wouldn't object to `throw "unreachable";` or `throw new FallThroughError(); // unreachable` or even `throw 0; // unreachable`.

I don't want to introduce a new error type with no real semantic meaning (since it will never be instantiated). That would suggest to users that they should be using the class instead of avoiding unreachable code. I just don't think the problem is big enough that it's worth the cognitive overhead of having the extra class.

**Comment by floitschG** [comment]
I'm not sure I agree. All errors should never be instantiated. If a specific point is reached something went wrong. Unreachable errors are usually more tied to the controllable source, but in the end they fulfill a similar role to, for example, `StateError`.
Especially for unreachable errors, I would like to see the stacktrace in the error object. Therefore `throw "unreachable"` doesn't fit, imho.

**Comment by lrhn** [comment]
Other errors *should* not be instantiated. They are only triggered when users of the code is using it incorrectly. That is, they are cross-API messages reporting an incorrect use of an API.

For errors *inside* a component, where the error is created by the writer of the code, we generally use asserts. If you can reach "unreachable" code by using an API incorrectly, then it's not unreachable, and you should be using `ArgumentError` or `StateError`. If not, I would still prefer to use an assert.

There are two problems being solved here - detecting a programming error inside a component, which is what assert is for, and avoiding warnings in switch statements with no default.

One solution for the latter is:
```dart
var v = something;
switch (v) {
   case A: ...
   case B: ...
   default:
     assert(v == C);
     ...
```
That is: Make the switch a total function, and add the assert.
I would do exactly the same thing if I was using `if` statements:
```dart
var v = something;
if (v == A) {
  ...
} else if (v == B) { 
  ...
} else {
  assert(v == C);
  ...
}
```

Another option is to add a default case apart from the real cases and add something there.
That something should both report the error using an assert and, if necessary, look to the analyzer like it aborts. (The spec static analysis doesn't recognize flow - it will still assume that you can pass trough a switch even if each case aborts - so I guess this is mainly to satisfy the analyzer).

I'd probably do something like:
```dart
default:
  assert(false);  // unreachable
  throw 0;  // appease analyzer
```

Throwing 0 won't capture a stack trace, but the assert will do that while you are debugging the code. As an alternative, you can throw `null`, which will create a `NullThrownError` object (at least until we get rid of that wart in the language).
