### ISSUE TITLE
Prefix reference resolution and Find Usages if the same import prefix used for 2 imports

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25828]
```
import 'dart:core' as prefix;
import 'dart:html' as prefix;

var a = prefix.String;
var b = prefix.Element;
```

Problems:
1. Both references (in var declarations) are resolved to the same `prefix` declaration. Should be resolved to different ones.
2. Find Usages for both `prefix` declarations return the same result: 2 usages. Expected: 1 corresponding usage for each `prefix`.

(originally filed as [WEB-15735](https://youtrack.jetbrains.com/issue/WEB-15735))

**Comment by bwilkerson** [comment]
This is working as expected.

Within a given namescope, a given name, such as `prefix`, can only be mapped to one thing. We model that by having a single PrefixElement to represent `prefix`, no matter which import the following identifier comes from.

The real problem here is that there is no declaration of the prefix to which references can be resolved. The presence of a prefix in an import directive isn't the declaration of the prefix, it is a reference to an implicitly declared identifier. Referencing the same prefix in multiple import directives still implies the declaration of a single identifier.

Note that if we treated the names as being somehow different then we'd run into other hard questions. For example, if the same prefix is used by multiple import directives and is used to reference a name that doesn't exist, to which identifier do you resolve the prefix? Or conversely, if the prefix is used to reference a name defined in both libraries (which is, granted, invalid code), to which identifier do you resolve it?
