### ISSUE TITLE
The specification of rethrow should be simplified

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#25857]
The specification of rethrow seems too complicated:

> Let f be the immediately enclosing function, and let on T catch (p1, p2) be the immediately enclosing catch clause (17.11).
> 
> A rethrow statement always appears inside a catch clause, and any catch clause is semantically equivalent to some catch clause of the form on T catch (p1, p2). So we can assume that the rethrow is enclosed in a catch clause of that form.
> 
> The current exception (16.9) is set to p1, the current return value (17.12) becomes undefined, and the active stack trace (17.11) is set to p2.

During execution of an on-catch clause, the spec has the current exception and active stack trace available, because they are only made undefined after executing the on-catch clause's statement (or in the case of a return, throw, or rethrow before this rethrow, but then we wouldn't be here).

So I don't think we have inspect the program to find the enclosing on-catch clause, to look up the value of the immutable (!) parameters.  Instead, these three paragraphs can be deleted from the spec, other than the part "Let f be the immediately enclosing function."

Similarly, when rethrowing at the end of a finally clause entered with a current exception, we can simplify this:

> Then, if x is defined, it is rethrown as if by a rethrow statement (17.10) enclosed in a catch clause of the form catch (vx, vt) where vx and vt are fresh variables bound to x and t respectively.

By instead restoring the current exception and active stack trace (or never making them undefined in the first place) and rethrowing, without resort to describing a nonexistent catch clause with fresh variables.

Finally, it's a bit of a wart that the catch parameters are implicitly final unlike other variables in Dart.  That restriction seems arbitrary and should be lifted.

**Comment by lrhn** [comment]
See also issue #19823.
The variables didn't use to be final.

**Comment by kmillikin** [comment]
I forgot to mention that this change requires the current exception and active stack trace to be per activation, rather than global.  That's not necessarily a bad change to make anyway.

**Comment by lrhn** [comment]
I would still be slightly worried by that change.
The one thing that made using a single global "current exception" and "current return value" convincing to me was that it only has a value during control transition. Keeping the value in this global variable while user code runs was a can of worms.
It *may* be fixed by having a set of variables per function invocation, but since exceptions can leave an invocation and be caught in another, it need to be very careful about details.

I'd rather introduce catch-clause execution specific variables used only for rethrow, moving the current exception and stack into those from the global "current" variables. That is, basically what we have now, except not using the same variables for both user access and rethrow.

**Comment by kmillikin** [comment]
The spec around `rethrow` has been revised.  This issue is resolved.
