### ISSUE TITLE
Tarball for arm is too big - 8 unstripped copies of Dart

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25867]
The arm tester has only 10 GB of disk space, and the cross-compiled build of Dart makes a tarball with 8 unstripped binaries, all of which are 160 MB or greater.  Can we remove some of these binaries from the tarball, and strip most of the rest, maybe just on the cross-compiler bot.

Do we really need to build 6 copies of Dart anyway?  This is also slowing building times on everything, because the different targets actually compile files from scratch with different variable settings.

@iposva-google @a-siva @zanderso

**Comment by iposva-google** [comment]
On my machine the binaries are approximately half the size from the ones you reported. (e.g. the dart binary is 73948437 vs 162782961 bytes). What ARM cross compiler is being used on the buildbots? Locally I have used:
/usr/bin/arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Ubuntu/Linaro 4.8.2-16ubuntu4) 4.8.2

"Do we really need to build 6 copies of Dart anyway? This is also slowing building times on everything, because the different targets actually compile files from scratch with different variable settings." is sort of the point. If we did not need the different variable settings, then we would not build different binaries.

Still we will investigate whether we can remove one of these binaries and repurpose an existing binary in its place.
