### ISSUE TITLE
Support syntactic (only) support for generic methods in the VM.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#25869]

**Comment by gbracha** [comment]
As far as I know, generic methods are are an experiment being conducted in DDC.  They most certainly are not an approved feature of Dart. Whether we we want to move forward with the experiment, either by further experimentation in the VM or by making it an official proposal to TC52 etc., is something that has not been decided or even discussed. The exact semantics are not necessarily finalized for example. So for now, this bug is on hold.

**Comment by floitschG** [comment]
This bug is for adding the syntactic support behind a flag. Removing the flag will require approval from TC52.
