### ISSUE TITLE
Make .info.json file more stable across releases

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25936]
It's often nice to look at diffs to understand how the JS is changing – but for even medium-sized apps there is huge churn with a small change.

It'd be nice if the numeric ID, perhaps some sort of name-based SHA or something to improve diffs?

**Comment by sigmundch** [comment]
Totally agree! 

We have the infrastructure changes to make it easier to change the info format in the future. We need to either support multiple versions of the info format (which we can do) or migrate the visualizer app to use our new infrastructure, so we can make breaking changes in the format.

I'm closing this bug entry though, since we are tracking this by the following 2 issues in the dart2js_info repo:
 https://github.com/dart-lang/dart2js_info/issues/12
 https://github.com/dart-lang/dart2js_info/issues/5
