### ISSUE TITLE
html/js_typed_interop_side_cast_exp_test failing on browsers

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#25937]
The test html/js_typed_interop_side_cast_exp_test has started failing on all browsers using dart2js.

There is a discussion about this test with the cps_ir compiler, at https://github.com/dart-lang/sdk/issues/24978, but this is now failing with the non-cps compiler.

Suppressed in html/html.status.

**Comment by sigmundch** [comment]
Thanks Bill - yes this started failing with the new IDL roll in a similar way.

/cc @jacob314 - a general question remains on whether we want to support this experimental flag anymore (the test runs with a special flag). If not, we can delete the logic and the test.

**Comment by alan-knight** [comment]
The general dart2js case started working with https://codereview.chromium.org/1811213002

I'm not sure if this should be closed or left open for the other questions.

**Comment by sigmundch** [comment]
oh cool - then let's keep it. It makes sense that this was why it was failing: if we retain all native types for any reason, we don't tree shake code that this test otherwise expects to be gone.

This gives me some assurance that the `dart:html` annotations are likely complete now.

I'm inclined to keep the feature and test for now, it will help us figure out how things play out with strong mode in the future. At that point we will likely have only one mode, and we should be able to either make the default be the behavior with or without the flag.

**Comment by whesse** [comment]
It should be left open as long as the line referencing it is there in the status file.  Is there a reason it wasn't changed in the status file?

**Comment by alan-knight** [comment]
I did change the status file for dart2js. There was also a line for cps_ir that I left in, and it's skipped for Dartium by design.
