### ISSUE TITLE
NodeList does not implement Iterable<Node>

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#25943]
In pkg/compiler/lib/src/tree/nodes.dart, dartsj2 defines a `NodeList` class with an `iterator` getter that returns an `Iterator<Node>`. However, it does not declare that it implements `Iterable<Node>`, nor does it implement (or inherit or mixin) all of the fun methods we know and love from Iterable.

I'm working on adding better type checking around for-in statements. Analyzer right now does absolutely no analysis (!). The spec defines some funny structural typing, which would make the dart2js code in question pass correctly, but is pretty complex to analyze and doesn't seem to fit with the rest of Dart or add a lot of value to users.

My goal is to implement nominal checking so that the iterator in a for-in loop is expected to implement `Iterable<T>`. As far as I can tell, this is the only real example of code in the entire repo that doesn't already pass that tighter checking.

**Comment by johnniwinther** [comment]
This is deliberate since most Iterable methods would be slow on NodeList as long as it is based on Link. The real solution here is to change NodeList to use List and _then_ maybe make it implement Iterable by forwarding to the List.

**Comment by lrhn** [comment]
Why would they be slow - or slower than other literables (that aren't also List or Set)? 
A linked list is an excellent example of something to iterate through, and the `NodeList` iterator is efficient, so the `Iterable` methods are as efficient as can be expected of an `Iterable`.

Or is the problem that the name suggests that it's a `List` and therefore someone could mistakenly assume that `length` is fast?

**Comment by kmillikin** [comment]
I've frequently found it annoying that NodeList did not implement the Iterable interface.  We always end up writing a for in loop using the iterator which isn't really any faster than the missing method implementation would be and requires a reader to reason about it to figure out which pattern its implementing.

So I vote yes!

**Comment by johnniwinther** [comment]
The slow `length` is the main culprit.

**Comment by lrhn** [comment]
Iterables do not promise to have a non-slow `length`. Rather the opposite - if nothing else is stated, you should assume it to be linear. 
That's why we check if an `Iterable` is a `List`, `Set` or `Queue` in some places, before assuming an efficient length.

`NodeList` may be slightly more mislading than average because it's named `List`, and `List` has efficient length.

**Comment by rakudrama** [comment]
Fixed by: https://chromiumcodereview.appspot.com/1783053005/

Eventually I would like to revert the NodeList part of this CL and change all the for-in sites to use __.nodes__.

I also want to get rid of Link. There is no size where this is more space-efficient that a fixed-length or unmodifiable list provided you use the same empty list everywhere.

**Comment by munificent** [comment]
Thanks for fixing this!
