### ISSUE TITLE
Observatory: Can't see all of a _List

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26004]
I want to see more of this list:

    _List (1024) {  ⊟   
      [ 0 ] aaa
      ...
      [ 99 ] xxx
      924 omitted elements
    }

I'd like there to be a way to add more elements so I can see various chunks of the list.

---

Perhaps have a link called

    [ 100 - 1023 ] 924 elements

that when clicked expands into (is replaced by)

    [ 100 - 199 ] 100 elements
    [ 200 - 299 ] 100 elements
    ...

and these in turn expand to the actual elements 100 at a time.
Huge lists would break down by 100k, 10k, 1k ranges to allow logarithmic navigation.

**Comment by johnmccutchan** [comment]
@turnidge

**Comment by turnidge** [comment]
I am implementing a simpler version of this functionality - I am adding a [see next N] link at the bottom which allows the user to double their view each time.  I think that having a more complex UI could make sense here sometime in the future - allow the user to specify an offset and a count, but it would take more time than I have to throw at it at this moment.  For now, I'm going to commit something simple so that this data is, at the very least, viewable.
