### ISSUE TITLE
Observatory: Include size in display of known Set implementations

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26005]
It would be helpful for known Set implementations to have better display, including the size summary

We have

```
_List (6) {  ⊞  }
_ImmutableList (3) {  ⊞  }
_InternalLinkedHashMap (143) {  ⊞  } 
```

but

```
_CompactLinkedHashSet {  ⊞  } 
```

**Comment by turnidge** [comment]
For things like _List, _ImmutableList and _InternalLinkedHashMap, these are implemented in the vm and we are able to include the length without invoking any dart code.  To add the same for non-vm classes, we would need to do a bit of evaluation, which could have side-effects.  We generally try to avoid evaluating except when requested by the user.

I'm not closing the bug though because this would be nice information to see in Observatory.  I'm thinking it over.
