### ISSUE TITLE
Mockito's "any" incompatible with strong mode analyzer

### ISSUE THREAD

**Issue by charliereams** [dart-lang/sdk#26036]
There are various contexts in which the analyzer complains about the "any" matcher, e.g. named arguments, function-typed parameters, and certain others, with the error message `Unsound implicit cast from dynamic to <some type>`. Is there a suggested work around for this?

cc/ @ochafik

**Comment by zoechi** [comment]
maybe adding this comment before the line with the warning

// ignore: DOWN_CAST_COMPOSITE

**Comment by leafpetersen** [comment]
For context, we generally warn about these because they are places where you might get unexpected results from the cast because of a reified dynamic.  For example:

```dart
dynamic x = [3];
List<String> l = x;
```
This will run fine on the VM (at least until you start using the contents of `l` as `String`s), but will throw a runtime type error on DDC.   If you're confident that the cast in question is correct, and you don't want to/can't write the code in such a way as to make that apparent to the typechecker, you have three options:

1) Ignore the error directly at the use site as suggested above (though I think you probably need STRONG_MODE_DOWN_CAST_COMPOSITE) 
2) Put in an explicit cast.
3) Use a helper function, such as one of the ones below.  The advantage of this over the explicit cast is that on the VM/dart2js, these ought to be fully inlined away resulting in no runtime cost.

```dart
// ignore: STRONG_MODE_DOWN_CAST_COMPOSITE
/*=To*/ downcast/*<From, To extends From>*/(From x) => x;
// ignore: STRONG_MODE_DOWN_CAST_COMPOSITE
/*=To*/ cast/*<To>*/(dynamic x) => x;

void test2() {
  dynamic d;
  List<int> x = downcast/*<dynamic, List<int>>*/(d);
  List<int> y = cast/*<List<int>>*/(d);
}
```

**Comment by charliereams** [comment]
AFAICT casting won't work, since "any" really isn't an object of the appropriate type. Disabling the error will work, but it's not great to have to disable warnings all over the place, even in tests. Is there any route to a better solution in the future? (Note that in other languages's implementations of Mockito, "any" is a generic method rather than a static constant, which should be possible to replicate in Dart soon.)

**Comment by leafpetersen** [comment]
Other than making any into a generic method (which you can do now with the comment based syntax), I don't have any immediate suggestions.  Obviously that would be a breaking change in the API.

I guess this is a use case for generic getters, which we haven't planned to support so far.  I'd have to think about how they would work out.

**Comment by ochafik** [comment]
cc/ @vsmenon

**Comment by srawlins** [comment]
This has been fixed via https://github.com/fibulwinter/dart-mockito/pull/26, https://github.com/dart-lang/sdk/issues/26863, and https://github.com/dart-lang/dev_compiler/commit/e5c2aac3fbb503fe0ede030dca9bfdc36bb0093a. Thanks @leafpetersen, @TedSander, @jmesserly, and @dskloetg for lots of work and input!
