### ISSUE TITLE
noSuchMethod when accessing AnimationEvent.type, and more

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#26049]
SDK: 1.15

Test code:

```
elem.addEventListener("webkitAnimationEnd", (e) {
  print("$e"); //=> [object AnimationEvent]
  print("${e is AnimationEvent}"); //=> false. Bug?
  print("${e.type}"); //=>noSuchMethod. Bug?
});
```

Tested Browsers: Dartium, Chrome and Safari
The result all the same.

**Comment by alan-knight** [comment]
That looks like it's not converting the AnimationEvent to a Dart object, but coming back with a JsObject instead. If you printed e.runtimeType that would probably be more indicative. Do you have a more complete program that reproduces this? How are you invoking the animation? Is there a reason you're using the event listener rather than the event streams?

**Comment by tomyeh** [comment]
It is caused by the use of event type in [DQuery](https://github.com/rikulo/dquery). Like JQuery, it uses type for dispatching event. I rewrote the dispatching mechanism to remove this dependency. A bit less efficient but it works fine now.

BTW, no only type is not missing, target is also not available.

Sorry, I don't retrieve the part triggering the animation. It is a bit complicated in our program. If you still need it, I'll make one when I have time.

**Comment by alan-knight** [comment]
If it's coming back as a JsObject I wouldn't expect any methods to be visible. I wonder if DQuery is patching prototypes or constructors, which might throw off our identification of the object.

**Comment by tomyeh** [comment]
No, it is not about DQuery. It is how I found this issue.

**Comment by matanlurey** [comment]
Please re-open if this is still the case with the latest `2.0.0-dev` SDK.
