### ISSUE TITLE
Make import quick fix configurable

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26050]
I wan't to consistently import with `show ...` 

For the first import from a specific library I always have to navigate to the created import statement at the top of the file and add `show SomeName` manually. Only for additional imports the `update library x import` option adds identifiers to the `show` list.

Sadly `update library x import` is always the last option of several. Importing is quite common while I rarely use the other fixes.

![image](https://cloud.githubusercontent.com/assets/405837/13904207/31d426b4-ee99-11e5-829c-df0634beb8d4.png)

Often there are also additional less common fixes, to make the menu even longer, (like `create xxx`).

Using `as` or `show` isn't explicitly mentioned in the Dart style guide, but was often suggested by Dart team to be used as the preferred import style because it's the most reliable way to import.

Expected behavior:
- Option to make imports with `show` the default (.analysis_options)
  - don't list `Import library xxx` if there is already and import for that library `xxx`, instead show only the `Update library xxx import` fix.
- `Update library x import` should be the first option if available.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
1. Actually there was a bug with the order of Quick Assists in IDEA. It was always alphabetical instead of using the order from the Analysis Server. It was fixed recently. So, now the popup looks better.
![image](https://cloud.githubusercontent.com/assets/384794/13925521/cdb6c1d4-ef45-11e5-96c5-65ba74394ba5.png)

2. I agree that with `import xxx show Y` we should not propose just `import xxx`.
    https://codereview.chromium.org/1816163002

3. Using `.analysis_options` is a big harder to do, will look at it later.

**Comment by srawlins** [comment]
I can see us implementing this feature by having a linter rule, `always_use_show`, and the configuring the fixes and assists which add imports to tweak what they insert based on the enablement of that rule.
