### ISSUE TITLE
Error message for incorrect type def has poor UX

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#26073]
I observed a user trying to guess the typedef syntax today, and the error messages weren't helpful in guiding them. 

See e.g. https://dartpad.dartlang.org/3a45a8a1060f8c72a863

It seems like the problem is in mixin error recovery.

I'm not quite sure what the 'The 'typedef' mixin application was replaced with 'class'' message is trying to say, so not quite sure how to help. If you can give me a pointer to the part of the spec that is specifying that we need to notify the user of the error I'll try and draft a more robust alternative.

**Comment by bwilkerson** [comment]
> If you can give me a pointer to the part of the spec that is specifying that we need to notify the user of the error I'll try and draft a more robust alternative.

I can't because it doesn't exist any more. :-)

A mixin application, such as:

    class C = A with B;

used to be written as

    typedef C = A with B;

When the change was made we continued to parse the old form and generated an error that attempted to indicate that the `typedef` form was no longer supported. When analyzer saw

    typedef y = foo(int x);

it appears to have "recovered" by assuming that this was an attempt to define a mixin application using the old syntax. I suspect that the right thing to do at this point is to remove that backward compatibility support and the associated confusing error message.

**Comment by srawlins** [comment]
Recovery could certainly still be improved here. On this example:

```dart
typedef y = foo(int x);

void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
  }
}
```

There are 6 errors on line 1:

```
  error • Invalid generic function type. • 26073.dart:1:11 • invalid_generic_function_type
  error • Expected to find ';'. • 26073.dart:1:13 • expected_token
  error • Expected a method, getter, setter or operator declaration. • 26073.dart:1:16 • expected_executable
  error • Expected to find ';'. • 26073.dart:1:21 • expected_token
  error • Expected a method, getter, setter or operator declaration. • 26073.dart:1:22 • expected_executable
  error • Unexpected text ';'. • 26073.dart:1:23 • unexpected_token
6 errors found.
```
