### ISSUE TITLE
Code navigation in IntelliJ is broken with 1.16.0-dev.2.0

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#26072]
Code navigation to Dart SDK members doesn't work after 1.16.0-dev.2.0:
![ij](https://cloud.githubusercontent.com/assets/3479527/13987472/26ae390c-f121-11e5-8d4e-1442ebaedbfd.png)
Dart VM version: 1.16.0-dev.2.0 (Tue Mar 22 09:47:03 2016) on "windows_x64"
IntelliJ IDEA 2016.1, build 145.258
Dart plugin 145.222

**Comment by zoechi** [comment]
Works for me in 

> Dart VM version: 1.16.0-edge.07a52f67110885d204496cf6fa196ca783f6a48f (Tue Mar 22 16:31:16 2016)

Is DartAnalyzer running? Sometimes the analyzer hasn't yet started working or crashed for some reason and then it might need some manual action to get it working again, like pressing one of the buttons on the top left of the Dart Analysis view

![image](https://cloud.githubusercontent.com/assets/405837/13987784/7c286406-f109-11e5-84ab-b66198440de7.png)

**Comment by lexaknyazev** [comment]
DartAnalyzer is running, even code completion work. And navigation to project members works too.

**Comment by zoechi** [comment]
If you kill the analyzer using the skull icon and wait until it is back and done analyzing, it still doesn't work?

**Comment by alexander-doroshko** [comment]
This is a Windows-specific problem, I'll write technical details in a minute.

**Comment by alexander-doroshko** [comment]
The problem is that Dart Analyzer from SDK 1.16.0-dev.2.0 doesn't respect `--file-read-mode=normalize-eol-always` option. 

IntelliJ IDEA / WebStorm expects all offsets that is gets from the Analysis Server are calculated against file content with normalized line breaks. Normalization here means changing all `\r\n` sequences to `\n`.

For example expected `String` class offset in `SDK/lib/core/string.dart` file is 3291, and Analysis Server always returned it correctly. But since SDK 1.16.0-dev.2.0 it returns incorrect one: 3382, that's exactly because not normalized CRLFs on Windows are counted as 2 characters.

cc @bwilkerson, @scheglov

**Comment by scheglov** [comment]
The problem is caused by [enabling using SDK summaries](https://codereview.chromium.org/1812013002/).
I'm [rolling this change](https://codereview.chromium.org/1831503002) back now.

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/08989ce327510eaf63a2609509f3e7052563f07b
