### ISSUE TITLE
Clipboard events treated as JsObjectImpl in Dartium

### ISSUE THREAD

**Issue by jeffhilleman-wf** [dart-lang/sdk#26084]
After upgrading to the 1.15.0 sdk and testing our application in Dartium the copy/paste handlers are throwing errors because the events are no longer returned as type ClipboardEvent but instead as type JsObjectImpl.

```
window.addEventListener('copy', _handleCopy);

void _handleCopy(Event event) <-- This will throw a type error
```

**Comment by travissanderson-wf** [comment]
+1 subscribing

**Comment by joelmarks-wf** [comment]
+1

**Comment by alan-knight** [comment]
Thanks. That seems to be fixed for me in 1.16 dev. Can you confirm if that works for you? Also, does it make a difference if instead you do

       window.on['copy'].listen(_handleCopy);

**Comment by travissanderson-wf** [comment]
confirmed it is resolved for me as well in 1.16 dev.2.0

**Comment by travissanderson-wf** [comment]
@alan-knight I get the same exception in Dart 1.15 using the window.on['copy'] style listener

**Comment by alan-knight** [comment]
OK, the reason it isn't getting wrapped as a ClipboardEvent object in Dart is that in 1.15 there is no ClipboardEvent class. The dart2js annotation maps it to a generic Event, and it doesn't get a wrapper in Dartium. I conjecture this might be due to changes in Chrome 45. 

 It's hard to do much about that, so working with it as a JsObject is about the best I can see. You'd probably need to put conditional code so that the code wouldn't stop working in 1.16. Or use 1.16 dev.

**Comment by travissanderson-wf** [comment]
@alan-knight is there no path to correct this in a point release in 1.15? we tend to shy away from adopting the dev channel in our dev environments so that we use the same SDK that we use to ship our production builds

**Comment by alan-knight** [comment]
It does not seem simple to make a patch, although I haven't discovered the underlying reason.

One thing you could do as a short-term workaround is just define the class yourself. 

```
@JS('ClipboardEvent')
class ClipboardEvent {
  external get clipboardData;
}
```

which seems to make Dartium return an instance of your ClipboardEvent. But it's not happy if it tries to extend Event. And there seems to be an issue in dart2js, but I don't have the right version of that, so I'm not sure if it ought to work or not.
