### ISSUE TITLE
Code completing after a named param shows me methods that return the wrong thing

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#26092]
_From @sethladd on March 24, 2016 23:29_

![screen shot 2016-03-24 at 4 28 55 pm](https://cloud.githubusercontent.com/assets/5479/14034135/9ac62f04-f1dd-11e5-9068-97e2eb7e67ff.png)

Atom 1.6.0, dartlang 0.6.8, SDK 1.15.0-dev.5.0 running on macos.

_Copied from original issue: dart-atom/dartlang#904_

**Comment by sethladd** [comment]
_From @devoncarew on March 25, 2016 3:50_

This will need to be moved over to the sdk repo.

**Comment by bwilkerson** [comment]
I believe that it's appropriate for these options to be shown because there are often chains of invocations that do eventually return the right type of value, but it seems reasonable to me that the type be used to rank the suggestions so that things that return the context type appear earlier in the list. I believe that we are now doing that, so I'm going to close this issue as having been solved.
