### ISSUE TITLE
Need sign a Debian repository. Dropping SHA-1 support in APT

### ISSUE THREAD

**Issue by DisDis** [dart-lang/sdk#26098]
In current moment, debian repository signed SHA-1 key.
Ubuntu 16.04 64bit / apt(1.2.7, 1.2.8+)
After run:
```bash
sudo apt-get update
```
Output:
```
E: Failed to fetch https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/Release  No Hash entry in Release file /var/lib/apt/lists/partial/storage.googleapis.com_download.dartlang.org_linux_debian_dists_stable_Release, which is considered strong enough for security purposes
```

Please update sign key.
More info: https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/

**Comment by vpigrad** [comment]
This is a blocker since the new LTS version of Ubuntu blocks installing packages that only have an MD5 or SHA1 key.  Google announced they were deprecating SHA1 a long time ago, so I don't understand why Google is refusing to add SHA256 keys.

To see the missing keys:

cat /var/lib/apt/lists/partial/storage.googleapis.com_download.dartlang.org_linux_debian_dists_stable_Release

**Comment by kevmoo** [comment]
@whesse ?

**Comment by jeffascentis** [comment]
You can still manually install Dart on Ubuntu:

`wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/debian_wheezy/dart_1.15.0-1_amd64.deb
dpkg -i dart_1.15.0-1_amd64.deb`

But, not being able to use the package manager is annoying.  Also, finding the file to download is a challenge since there are no index pages.  /dart-archive/channels/stable/ and the other directories return a 404 rather than showing a list of files.

**Comment by whesse** [comment]
I will ask the author of the internal tool that creates and signs the repositories about this.

**Comment by whesse** [comment]
The tool that creates our repositories has been updated, just a couple days after the stable repo was last updated.  I'll just recreate the signed repo, and upload the new version with the SHA256 hash.

**Comment by DisDis** [comment]
@whesse thanx

**Comment by whesse** [comment]
New stable repo updated, signed with SHA256 hashes.
