### ISSUE TITLE
Make Stream.asyncMap() and Stream.asyncExpand() generic

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26125]
The `Stream.asyncMap()` and `Stream.asyncExpand()` methods should have generic parameters in strong mode.

**Comment by nex3** [comment]
Oh, also `Stream.drain()`!

**Comment by leafpetersen** [comment]
@floitschG Any chance you'd have some cycles to add this to your other SDK/strong mode stuff?

**Comment by ochafik** [comment]
and `Stream.firstWhere` / `lastWhere` please!

**Comment by floitschG** [comment]
I will try to find some time.
I have to do lots of perf stuff next week, so this could take longer.

@ochafik: I assume you mean that `Stream.firstWhere` / `lastWhere` should return `T`?

**Comment by ochafik** [comment]
Sorry, yes: although not sure if it should return a real `Future<T>` or use the generic method notation to avoid potentially changing the API in a semi-breaking way.

Note that the following seems to work (& fixes the strong-mode errors I'm getting):
```dart
  Future/*<T>*/ firstWhere(bool test(T element), {Object/*=T*/ defaultValue()}) {
```

**Comment by floitschG** [comment]
Yes. It would be a breaking change (which is why we haven't fixed it before).

We will discuss, if we want to go with the comment-annotation or if we want to fix the signature.

**Comment by nex3** [comment]
I would also like to see `firstWhere()`, `lastWhere()`, and `timeout()` have generic parameters added, but I didn't include them here because—as Florian notes—that would be a breaking change. It's also not inherently tied to strong mode, since they'd just use the stream's own types.

If we *are* making breaking changes to `firstWhere()` and `lastWhere()`, I'd love to see the optional parameter renamed `orElse` for consistency with the Iterable methods of the same names.

**Comment by ochafik** [comment]
I don't think the syntax I suggested would be a breaking change?

**Comment by nex3** [comment]
It's a breaking change for strong mode users—currently they're allowed to return whatever type they want from `defaultValue()` regardless of the collection type. For spec mode users it also represents a new type of situation in which their code isn't automatically strong-mode compatible, not just because they were doing something sketchy with types, but because the API no longer allows you to do things it had explicitly allowed before. Which is not to say we shouldn't do it, but it's not a trivial change.

**Comment by floitschG** [comment]
@ochafik the syntax you suggested wouldn't be a breaking change.
However, the correct way to fix this method is to return 'T'. It doesn't make much sense to return anything else, and the Iterables already do that.

**Comment by lrhn** [comment]
The `firstwhere` is one of the cases where we wanted a `Stream<Apple>` to be usable as a `Stream<Fruit>`. It's the original design of generics in Dart: not safe, but reasonable - a list of apples *is* a list of fruit.
That means that `firstWhere` of a `Stream<Apple>` being used as a `Stream<Fruit>` should allow a default that is a `Fruit`.

So, what it should really be is: `S firstWhere<S super T>(bool test(T element), S defaultValue())`.
That's Java notation, I don't think we can express the covariant type variable in Dart (but maybe we should).

**Comment by eernstg** [comment]
Here's a slightly broader view on this:

A caller of `firstWhere` cannot satisfy the requirement that the given `defaultValue` argument must return a `T` because the receiver with statically known type `Stream<Fruit>` could be an instance of `Stream<Apple>` at runtime: The caller simply can't know statically that the given argument must return an `Apple`. But the caller could very well satisfy that `defaultValue` must return an `S` which is a supertype of `T` (`Fruit`, `Object`, and others will do).

So using `T` as the return type for `defaultValue` is not just a breaking change, it's a signature that could never be called safely.

But that's just like the situation with any other contravariant usage of a class type argument, as long as we have covariant generic types. For instance, the same situation would arise if the `defaultValue` had directly been the default value rather than a function capable of delivering it (it would then have been declared as `T defaultValue`).

This means that we might as well consider this as an example of the more general case where a class type argument occurs in a contravariant position.

Currently, 'DDC injects runtime checks on parameters in method invocations whose type is a class type parameter' (https://github.com/dart-lang/dev_compiler/blob/master/doc/RUNTIME_SAFETY.md) and a similar check would be needed for all other contravariant occurrences (e.g., we would need to check the type of `defaultValue` dynamically if it were declared as `T defaultValue()`). These checks are actually the _same_ checks as the ones that checked mode performs when the arguments are passed (with the gotcha that function type subtyping is overly forgiving for spec mode, and possibly based on the same runtime semantics for DDC).

So we already have a strategy in place for these contravariantly positioned class type parameters. Isn't that enough?

There is an extra bit of goodness that we can achieve by using the `S super T` trick. It does not help the body of the callee, but it may help the enclosing code at the call site:

The reason why it does not help the body of the callee is that such an argument would effectively have type `Object`. The reason why it might help the context of the call site is that the invocation might have a more informative type, exactly because we happen to be able to use the method type argument `S` in the return type. In the example, the call site would be able to rely on getting a `Fruit`.

It seems that we have a poster child for using a `super` bounded method type argument here, and there may be a number of similar cases in the core libraries and beyond, because the issue arises for all contravariantly positioned usages of a class type argument (as long as the implementation can tolerate that the type as seen from inside the receiver class is `Object`).

To me, this sums up to a feature request: We actually want those super bounds on method type arguments!

**Comment by floitschG** [comment]
I agree that the `List<Fruit>`-`List<Apple>` case is important, but I'm actually more worried about nullable types. I imagine that many `firstWhere` calls currently return `null` when the element is not found. If the generic type is non-nullable we might have a problem then (depending on how we deal with non-nullable generic types).

**Comment by lrhn** [comment]
That still suggests that `S firstWhere<S super T>(bool test(T element), S defaultValue())` is the correct type since `SomeType?` should be a supertype of `SomeType!`. That is, if you have a non-null-element collection (say a `List<Apple!>`) and want to find the first that something, or null if none, then the return type of `firstWhere` is `T?` so you have to call it as `coll.firstWhere<Apple?>((x) => x.isRipe, () => null)`, and with a little luck, type inference will be able to deduce the type parameter from the return type of `() => null` as the most specific superclass of `Apple!` and `Null` - `Apple?`.

**Comment by nex3** [comment]
`Iterable.firstWhere()` does explicitly return `T`. If that's going to be a problem going forward, we should change it as soon as possible—changing it later could cause pretty massive breakage once everyone's on strong mode.

It's really unfortunate that the `defaultValue`/`orElse` parameters mean that the simple case of just calling `firstWhere()` with a single argument has a much broader type than necessary. I suppose we'll be able to handle that with overloads in the future, but those seem like they're a long way away.

**Comment by leafpetersen** [comment]
@yjbanov brought up Future.catchError in a code review, I think this may involve the same issues?

**Comment by nex3** [comment]
`Future.catchError()` is a particularly weird case, because the return value *should* be inferred from the return value of the callback, but the callback may take multiple forms so that's not expressible. The ideal signature for it would be:

```dart
S catchError<S>(
    S callback(Object error) | S callback(Object error, StackTrace stackTrace),
    {bool test(Object error)});
```

but without union types, it's not clear that adding a generic parameter is better than just leaving it untyped and requiring a manual cast.

**Comment by leafpetersen** [comment]
An issue to consider with both firstWhere and catchError is that of what reified type the return future has.  If what is returned is a `Future<dynamic>`, then casting it to anything specific will fail.  Returning a `Future<T>` where `T` is the original element type presumably will fail when `defaultValue` or `callback` return a supertype of `T`.  So the generic might be needed just to get the reified type right, even if we can't express the contra-variant bound statically.

**Comment by nex3** [comment]
By "casting" I more meant casting the value in the future, rather than casting the future itself. This can happen easily using async/await, and casting within the body of the future also makes sense. Also, I'm working on making type-asserting wrappers for async types in the `async` package right now.

One thing that worries me with making `catchError()` generic is that it would make it easier to write code like this:

```dart
void processString(Future<String> string);

processString(future.catchError((error) => 12));
```

If `catchError`'s signature were `S catchError<S>(Function callback, {bool test(Object error})`, this code (I believe) typechecks due to downward inference but fails at runtime because the `Future` contains an `int` and not a `String`. If `catchError` is dynamic, the user is forced to explicitly acknowledge that they're making an out-of-band assertion about the type of the future. Erring on the side of safety rather than convenience seems especially worthwhile here since futures are mostly used with async/await these days anyway rather than by calling explicit methods.

**Comment by leafpetersen** [comment]
cc @munificent

**Comment by floitschG** [comment]
The `firstWhere` and `lastWhere` are already covered in issue 25397.

**Comment by leafpetersen** [comment]
This seems to be done, closing.
