### ISSUE TITLE
Failures with newly checked in JsInterop

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#26134]
Fix 43 failures with new JsInterp optimizations.

**Comment by alan-knight** [comment]
I haven't run all of these, but all the ones I've looked at so far fall into two categories.

1) Exception mismatches - tests that are looking for a specific exception or specific exception text, and we're throwing something else in DartCustomBindings.cpp

2) A strange caching bug with custom elements. The scenario is
  - create a custom element from something that that has its own class (e.g. div, a)
  - create a custom element from something that doesn't have its own class (e.g. abbr)
The second one will end up having the Dart class of the first. See e.g. WebPlatformTest/custom-elements/instantiating/createElement_A02_t01

   We create an AnchorElement. If, beforehand, we do document.createElement("abbr") then the class will be HtmlElement. If we do it afterward, it will be AnchorElement. If we switch and use DivElement first, possibly followed by AnchorElement, then the abbr will be a DivElement. So it seems like we're either caching something internally or else we're messing with the prototype in a way that then gets carried forward so that our type lookup is wrong. Possibly there's an interaction with upgrading the element?

The lookupType method in conversions_dartium.dart is where the lookup should happen, but I'm suspicious of something in computeInterceptor (DartJsInterop.cpp), because the lookupType is never even called for the abbr element.

The critical line seems to be 

            var elemProto = js.JsNative.callMethod(js.JsNative.getProperty(js.context, 'Object'), "create", [js.JsNative.getProperty(baseElement, 'prototype')]);

in registerElement in html_dartium.dart.  Before that line is executed for some other element type, document.createElement("abbr") returns an HtmlElement, afterwards it returns an instance of the other element type, although with a tagName of "abbr".

**Comment by dgrove** [comment]
Any updates on this?

**Comment by mit-mit** [comment]
@terrylucas @alan-knight what is the status here? I'm assuming this does not block releasing 1.16 to stable?

**Comment by mit-mit** [comment]
Removing 1.16 flag as there seems to be no urgency here... @kevmoo pls confirm.

**Comment by kevmoo** [comment]
@terrylucas @jacob314 Are these regressions? Just test issues?

**Comment by jacob314** [comment]
This bug can be closed with Terry's latest custom element CL.
