### ISSUE TITLE
vm: Too much time spent seaching exported libraries

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26145]
Running

    dart main.dart

takes 6 seconds on my machine even though almost no line of code is executed more than a few times.
This is so slow that you can compile it with dart2js and run the output faster!

This repro is an extreme example of what happens on Dartium running large angular apps.
I see call stacks with two or three recursive calls to `dart::Library::LookupReExport`.

[ReExport.zip](https://github.com/dart-lang/sdk/files/196888/ReExport.zip)

**Comment by rakudrama** [comment]
A related problem is that the VM does not detect the error of two re-exported libraries exporting different definintions of the same name into scope that uses the name.

**Comment by fsc8000** [comment]
@mhausner

**Comment by mhausner** [comment]
Looking up names in a graph like the one in this example is slow at first, but gets faster over time because the lookup results are cached.

The non-detection of re-exporting a name twice (denoting different objects) is a known bug. Lookup of global names would unfortunately be even more expensive if this was implemented correctly. Right now the lookup in re-exported namespaces terminates when the first name is found. We'd have to continue looking in all other namespaces to ensure there is no conflicting name. That is done for imports, but not re-exports.

**Comment by mhausner** [comment]
CL https://codereview.chromium.org/1902563002/ introduces a cache that speeds up the example by about 50 times.

**Comment by mhausner** [comment]
The sample code in this bug now takes less than 0.15 seconds to run to completion on my old-ish mac pro:

time dart ~/tmp/exp/main.dart 
Instance of 'C22'
Instance of 'C1'
Instance of 'X'
Instance of 'Y'
Instance of 'X'

real	0m0.117s
user	0m0.122s
sys	0m0.029s

Committed patchset #4 (id:60001) manually as
b4ac99a4121769b132499eef3a15b9a70f0e1fce (presubmit successful).
