### ISSUE TITLE
Analyzer regression between 0.27.2 -> 0.27.3-alpha.6: Files are no longer cleared

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#26164]
Repro steps:
  - Pull the dart-services repo (https://github.com/dart-lang/dart-services), `pub get`, `dart tools/grind.dart test`
(Passes)

Change the pubspec.yaml to `analyzer: 0.27.3-alpha.6`
`pub upgrade`
`dart tools/grind.dart test`

Tests now fail.

dart-services needs to clear files from the context between each usage. This is done by e.g.

(analyzer.dart, ln 127).
```
      // Delete the files
      changeSet = new ChangeSet();
      sourcesList.forEach((s) => changeSet.removedSource(s));
      _resolver.clear();
      _context.applyChanges(changeSet);
      _ensureAnalysisDone(_context, _MAX_ANALYSIS_DURATION);
```

This no longer seems to work. The verification tests fail as the analyzer is still reporting the old results.

```
 PASS: analyzer.dartdoc multi file missing import
  FAIL: analyzer.dartdoc multi file clean between operation
    Expected: empty
      Actual: [
      AnalysisIssue:error: Target of URI does not exist: 'bar.dart' [1],
      AnalysisIssue:warning: The function 'bar' is not defined. [4]
    ]
  
```

This will block our ability to upgrade dart-services.

**Comment by scheglov** [comment]
I was able reproduce the problem.
The problem is caused by the incomplete `StringSource` implementation in `dart-services`.

1. The property `uri` is now required.
2. The property `encoding` is not what you think it is :-)  It should be encoded *representation* of the source, its ID. Content encoding, like `UTF-8` is not needed at this level, because `Source` already provides the contents as `String`.

With these two problems fixed I see that all tests pass.

```
[cut]
  PASS: Summarizer Html and css detection
  
  All 108 tests passed.
  unittest-suite-success

finished in 60.842 seconds.
```

**Comment by lukechurch** [comment]
Thanks @scheglov 

It looks like I can just defork our implementation of StringSource from the one in the Analyzer package - and that resolves it.
