### ISSUE TITLE
Problem in the analyzer or in the VM (or in both)

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#26180]
```
  // VM parses: OK
  // VM executes: OK
  // Analyzer parses: Fail
  var good1 = const Symbol("#unary-");
  // VM parses: Fail
  // VM executes: Unknown
  // Analyzer parses: Fail
  var good2 = #unary-;
```

Anybody here tested the following?
- VM parser
- Analyzer constant expression evaluator
- VM error messages (such as the `Class 'XXX' has no instance method 'unary-'`)

Also question: Method name (which is a symbol) `unary-` is a legal name?

P.S.
According to this message (`Class 'XXX' has no instance method 'unary-'`) a class can to have a method declaration with a name `unary-`.
That is, a symbol `unary-` is a legal symbol.
If it is a legal symbol then should be a way to declare it literally as and other symbols.
Eg.

``` dart
var name1 = #-;
var name2 = #unary-;
```

**Comment by lrhn** [comment]
The VM accepts any string as parameter to `const Symbol`, whether it's something that creates a meaningful symbol or not. That's why it accepts `const Symbol("#unary-")`, which isn't a useful symbol name. The symbol you are looking for is `const Symbol("unary-")` and is, as you say, the name of the unary prefix minus operator (the one declared as `operator-()`).

The specification of the `Symbol` constructor actually says that it should reject invalid parameters, even when used as `const`. That requires a hack because `const` execution can't validate the input, and the VM hasn't added such a hack.

There is no way to write a symbol literal for that particular symbol, so `#unary-` isn't a symbol literal - it's the symbol `unary` followed by a minus. If you write `#unary-2` you will see that it parses, and then fails at runtime because symbols don't implement binary minus. So, maybe there should be a way to write it as a literal, but currently there isn't.

**Comment by mezoni** [comment]
>> The specification of the Symbol constructor actually says that it should reject invalid parameters, even when used as const. That requires a hack because const execution can't validate the input, and the VM hasn't added such a hack.

Thank you for the clarification.

**Comment by mezoni** [comment]
@lrhn 
How to corretly determine that a class declares a unary minus operation?
If I will use an `invalid` symbol that it would be incorrect because in the future this option can fail (due the specification).
But I will not use `invalid` symbol (which is correct) then how I find it in the type members declarations by the name?
Please, give me a Dart technical support (answer) how I should use it because this is mutually exclusive constraint (according to your previous answer).
Thank you in advance.
