### ISSUE TITLE
To super or not to super? That is the question.

### ISSUE THREAD

**Issue by Zectbumo** [dart-lang/sdk#26194]
The super method call pattern offers little control for the author and furthermore is not reliable. You have little control when these super calls are being made in 3rd party libraries. The subclass has no control to call or not call methods in the super chain. The use of super is not reliable because a library may or may not be calling super and you may or may not want a super call. Here is an example:

Let's say you import Mixin_A and Mixin_B and you want to make class One and class Two using some of the available mixins and of course you want all the init() methods to be called:

```
// Imported lib you cannot change
class Mixin_A {
    init() {
        print("init A");
        super.init(); // The lib author can't know to call super here or not
    }
}
// Imported lib you cannot change
class Mixin_B {
    init() {
        print("init B");
    }
}

// this is your code that you can change
class One extends Object with Mixin_B, Mixin_A {}
class Two extends Object with Mixin_A {}

main() {
    var one = new One();
    one.init(); // If super is not called by lib then Mixin_B.init() will not get called

    var two = new Two();
    two.init(); // If super is called by lib then Exception: Super class of class 'Two' has no instance method 'init'.
}
```

As you can see here that allowing super in mixins is a bad idea and will cause problems. It really should be removed and replaced with a better idea that provides full control over the code execution. I pointed this out in #12456 and came up with a mockup syntax that solves a lot of the issues that super brings. Applying that idea would result in this code:

```
// Imported lib you cannot change
class Mixin_A {
    init() {
        print("init A");
        // no super call allowed in mixins anymore so it never causes a problem
    }
}

// this is your code that you can change
class One extends Object with Mixin_B, Mixin_A {
  void init() {
    (Mixin_A)super.init();
    (Mixin_B)super.init();
  }
}
```
Like I said in #12456 
1) You don't get caught up in unknown and unclear super call paths. 2) It gives you access to the required super classes you want. 3) Easy to read and understand what is going on. 4) And is always available to edit since you have access to edit your Subclass source code any way you wish.

My request is:
1) Not allow super calls in mixins.
2) Have a super call from a subclass not call methods on any mixin classes and only call up the `extends` chain.
3) Provide some syntax to call any method from any included mixin even though there are name clashes.

As a reminder Wikipedia explains:
> In object-oriented programming languages, a mixin is a class that contains methods for use by other classes without having to be the parent class of those other classes. **How those other classes gain access to the mixin's methods depends on the language.** Mixins are sometimes described as being "included" rather than "inherited".
> Mixins encourage code reuse and can be used to **avoid the inheritance ambiguity** that multiple inheritance can cause [1] (the "diamond problem"), or to work around lack of support for multiple inheritance in a language.

https://en.wikipedia.org/wiki/Mixin

**Comment by lrhn** [comment]
The `Mixin_A` class should give you a warning because you are calling a super method that isn't declared in the mixin class' superclass (which is `Object`). You have to say that the class actually extends a class that declares such a method, and then you will be warned if you apply the mixin to a class that doesn't implement that declared superclass.

> Let S<sub>static</sub> be the superclass of the immediately enclosing class. It is a static
type warning if S<sub>static</sub> does not have an accessible (6.2) instance member named
`m` unless ... (something that doesn't apply here)

and

> Let M<sub>A</sub> be a mixin derived from a class M with direct superclass S<sub>static</sub>.
Let A be an application of M<sub>A</sub>. It is a static warning if the superclass of A
is not a subtype of S<sub>static</sub>.

So, in your case, the `Mixin_A` class should be written *knowing* that the superclass has an init method, and you can assume that it is used in a setting where it does, otherwise it should not be using `super` invocations at all.

The `Mixin_B` class is the problem. It happens to implement a method with the same name as `Mixin_A` and with a compatible signature, so you don't get any warnings when `Mixin_B` overrides the inherited method, potentially oblivious to the fact that it's even there. 
That's not unique to mixins, nor is it a new problem. 

In C#, the "override" declaration is required when you override a virtual method. If you accidentally override, you will likely not have that annotation, and you will get a warning.
Dart only has `@override` as an annotation, so it's not part of the specification. The analyzer might be able to warn you if you override a method without specifying it, but I don't know it well enough to be sure.

All in all, I don't think super-calls in mixins are as fragile as you say because you have to declare the superclass on the mixin class. The overriding problem is unrelated to super-calls - it's a matter of one class inheriting two independent methods, possibly from separate interfaces, but with sufficiently compatible signatures (so you don't get a warning about that), and one of them overriding the other.

There is no good solution for having two separate methods called "init()" inherited from two unrelated classes - except perhaps making one of the classes a part object instead of mixing the implementation into the inheritance chain. Then you would have:

    class One extends Object with Mixin_A implements Mixin_B { 
       Mixin_B _b;
       init() {
         super.init();
         _b.init();
       }
    }

(Good old "favor composition over inheritance").

**Comment by Zectbumo** [comment]
> …otherwise it should not be using super invocations at all.

Right, so the lib author that made Mixin_A will not call super in their mixin class and then there is no way to call init() for Mixin_B. Now what?

> There is no good solution for having two separate methods called "init()" inherited from two unrelated classes - except perhaps making one of the classes a part object instead of mixing the implementation into the inheritance chain.

Which is why I'm asking for the ability to explicitly call the super methods individually at the location where we have full control of source code. We need some sort of ability to call these unaccessible methods. "there is no good solution" as you said so let's solve this issue and make a good solution.

```
(Mixin_A)super.init();
(Mixin_B)super.init();

// or

Mixin_A.super.init();
Mixin_B.super.init();
```

**Comment by eernstg** [comment]
I think the real issue here is that the existence and placement of a super invocation is semantically significant for clients (here: mixin applications), which means that it "should" be part of the formal interface of the class which provides the mixin, e.g., `Mixin_B`. 

However, we don't have any mechanisms for making the existence of a super invocation a part of "the type of the mixin" such that we can ask type checkers to check it, and get the kind of safety that you are asking for.

Hypothetically, it would be quite simple to add some kind of type property to each method (say, a modifier `super`). We could then (1) enforce that any method carrying the `super` modifier must contain a super invocation, (2) decide that `super` invocations on an abstract method are allowed and will do nothing, and you could then write a bunch of mixins with a method `super init()` extending a `Mixin_Base` class declaring an abstract `init();`, and it would then be trivial for static analysis to ensure that only `super` methods are used in any mixin application involving `init()` methods. The semantics of super invocations in mixed-in methods will then ensure that the entire chain of methods is invoked .. if that super invocation is actually reached, that is:

You'd still need to consider whether you would enforce that `super` is called on all paths in the control flow. How about out-of-memory on a seemingly benign `new` expression, do we have to prevent `new` on every path prior to the super invocation? Surely there are lots of dark corners here, as usual. ;-)

So that's probably a lot heavier than most people would want. But it would still be possible to use a stand-alone checker along with a convention about a certain `@callsSuper` metadata annotation to obtain this kind of checking in a near-sound manner, even without changing the language. Oh, and you'd have to live with the concrete `init() {}` in `Mixin_Base` rather than an abstract `init();`, but otherwise it is possible to get close.

**Comment by lrhn** [comment]
> Right, so the lib author that made Mixin_A will not call super in their mixin class and then there is no way to call init() for Mixin_B. Now what?

Rewrite the classes.
What you have here is a known problem in inheritance based designs. It's not unique to mixins, it can happen in a normal inheritance chain too.

Say you have:

    class Base { }
    class Sub1 extends Base {}
    class Sub2 extends Sub1 {}

declared in separate libraries with some members that are not relevant here. Everything works, everyone is happy.

Then the `Base` class author introduces an `init` function in a new version of his library, and calls it from  his constructor.
The `Sub2` class author thinks this is great and adds his own override of `init` in a new version of his library, dutifully delegating to the `super.init`, and depending on the new version of the original library.
Independenly the `Sub1` class author gets the same idea and introduces an `init` method in a new version of his library, depending on the original version of the original library.

Now, you try to update all the libraries in your project. Adding a method is a backwards-compatible minor-version change, so you get all the new versions, and everything stops working because the `Base` version of init is never called (and the `Sub2`->`Sub1` version is called twice).

No mixins involved, just incompatible (but individually backwards-compatible) changes to the classes in the inheritance chain.

This is the same problem you have here, just using mixins. The middle class introduces an unrelated init function (it is unrelated, otherwise it would know that it has to call super.init()) that happens to override another init function. That's the bug - having two unrelated functions with the same name in the same inheritance chain. If they had different signatures, it would stand out more and be caught early, but since they are compatible, it gets to runtime before causing trouble.

The solution doesn't change: It hurts, so don't do that.

Or use and require `@override` everywhere (in which case it should be a language level feature, not just an annotation) - then you would get the warning that `Sub1` overrides `init` without writing `@override`, and you can see the problem is there.

You seem to have an idea that the mixins may be used on both classes that have and don't have an init method in the superclass. That won't work. Either they declare a super-type that has an init, and then they can and *should* call `super.init()` because the `super.init` documentation says so, or they don't and then the init functions are completely unrelated.

Another option, if multiple classes all introduce unrelated `init` functions (which makes me a little worried about the OO design since I would prefer initialization to be in constructors), is to call them something different: `initBase`, `initSub1`. Then you won't get the conflict.

**Comment by zoechi** [comment]
I didn't try to fully understand the arguments but https://github.com/dart-lang/sdk/blob/0c1e85ebadaa0680d4ff30acc1f3ac823c53756e/pkg/meta/lib/meta.dart#L57 sounds like what @eernstg mentioned.

**Comment by lrhn** [comment]
@eernstg 
>However, we don't have any mechanisms for making the existence of a super invocation a part of "the type of the mixin" such that we can ask type checkers to check it, and get the kind of safety that you are asking for.

That's where the Beta language's "inner" invocations really shines - you don't *override* your superclass method, you *extend* it. The superclass method calls the subclass method explicitly, and if it doesn't, you can't extend it at all.

Example: A loop-construct implementation and it being specialized with an inner body:

    Cycle: (#do (Loop: inner Cycle; restart Loop :Loop) #)

    ...; Cycle(#do Keyboard.get->Screen.put #); ...

(syntax be damned, the idea is cool!)

**Comment by eernstg** [comment]
About https://github.com/dart-lang/sdk/blob/0c1e85ebadaa0680d4ff30acc1f3ac823c53756e/pkg/meta/lib/meta.dart#L57: Well well, I didn't know it was already in place, and the analyzer also knows about it (see the `MUST_CALL_SUPER` hint in analyzer/lib/src/generated/error.dart). So that's indeed the kind of annotation that I was thinking about. The error message is a bit confusing (I'll create an issue on that), but otherwise it works. ;-)

**Comment by eernstg** [comment]
Indeed, BETA is always a good reference for fresh air. In gbeta I changed this a bit: There is an implicit INNER at the end of each main part unless there is an explicit INNER (anywhere in the same main part). But in both of these designs you can still have the equivalent of 'if (false) then INNER' which looks like it will keep the chain alive unless you start doing flow analysis, and on top of that there's the issue of how to handle the cases where you _do_ want to break the chain (because of an error, or whatever). It's not easy to make constraints on behavior work really well..

**Comment by Zectbumo** [comment]
@lrhn wrote:
> What you have here is a known problem in inheritance based designs. It's not unique to mixins, it can happen in a normal inheritance chain too.
> …
> It is the same problem you have here, just using mixins.

You are bringing up a different issue. The issue you brought up has a simple solution. After the base class updates the client author detects their program doesn't work anymore and the author adds a super.bar() call to his bar() method. Your problem is fixed. The issue I bring up has no such simple solution since the mixin author nor the app author can do anything about my case without the Dart language changing to give me access to the individual mixin class methods. The problem is not the same.

**Comment by eernstg** [comment]
I think a slightly restricted version of the issue you brought up has a simple solution (the one we discussed already):

```dart
import 'package:meta/meta.dart';

class MixinBase {
  @mustCallSuper
  void init() {}
}

class Mixin_A extends MixinBase {
  init() {
    super.init();
    print("  init A");
  }
}

class Mixin_B extends MixinBase {
  // Wrong, and gets hint: 'This method overrides .. @mustCall super ..'.
  init() {
    print("  init B");
  }
}

class One extends MixinBase with Mixin_B, Mixin_A {}
class Two extends MixinBase with Mixin_A {}
class Three extends MixinBase with Mixin_A, Mixin_B {}

main() {
  print("One:");
  new One().init(); // init B, init A: OK.
  print("Two:");
  new Two().init(); // init A: OK.
  print("Three:");
  new Three().init(); // init A: B is missing, which is what the hint said.
}
```

You'll get the hint with `dartanalyzer --supermixin <your-entry-point>.dart` (there's still a typo in the diagnostic message, but otherwise it works).

The only thing missing is that this approach requires you to announce up front that those `init` methods have something to do with each other (they must all override something like `MixinBase.init` in order to get the static check).

If the methods have nothing in common except the spelling of their name then they might as well have different names as tell (say, some of them could be named `init`, others `setup`, and yet others `initialize`, and some of those `init` methods might even have been renamed to `start` in the next version of those libraries that you cannot edit).

In this case it's not unreasonable to request that you create a connection in code that you control, for instance by setting up a chain of methods (like `MixinBase.init` and its overriding methods above, with a non-clashing name, e.g., `myInit`), and let those methods invoke the others (`initialize`, `setup`, `init` etc.) using forwarding. For disambiguation you could interleave the mixins such that each uncontrollable third-party mixin (with `initialize` etc.) is followed by one of your mixins, which will then use `super.initialize(..)` etc. to call the third-party method from `myInit`. This would also provide enough flexibility to handle the situations where some of the target methods do actually call each other using `super` calls, and whatever else might happen.

**Comment by Zectbumo** [comment]
I don't think that's a valid solution to move forward with issue. Ideally mixins should be included but not be part of any inheritance pattern thus not having to call super or be part of the super chain. I would actually prefer that a super call does NOT call any mixin methods and give me direct access to each and every mixin class to call my own methods as I require.

**Comment by lrhn** [comment]
That's a very different mixin model than the one Dart has chosen. In Dart, a mixin application is exactly the same as extending the superclass, it's not something that's attached to the class "on the side". That makes the model simple (since it's already there). If you can access the mixins individually, it's not clear to me what happens if mixins contain members with the same names. Say:

    class C {}
    class D { foo() { bar(); }  bar() { print("D"); } }
    class E { foo() { bar(); }  bar() { print("E"); } }
    class F extends C with D, E {
      baz() { E.super.foo(); D.super.foo(); } // prints what?
    }

**Comment by Zectbumo** [comment]
I don't want exactly the same. Exactly the same runs into all the other issue any other language that allows multiple inheritance has. I'm looking at this from a point of view where mixins should keep to themselves and not play as big of a part with the inheritance system. Make mixins significantly different. From this point of view calling bar() would call their own respective bar() method. The output of baz() would unsurprisingly be E D. If one wants to override methods then one can use the tried and true `extends` chain.

**Comment by eernstg** [comment]
If, as stated, you 'prefer that a super call does NOT call any mixin
methods' then I'm afraid you just don't want mixins.

Mixins were introduced in Flavors (
https://inst.eecs.berkeley.edu/~cs164/fa05/doc/flavors.htm) as a way to use
(type-unchecked) multiple inheritance to add "abstract subclasses" to an
inheritance chain (CLOS and variants thereof define multiple inheritance in
terms of a linearization), and mixins as a stand-alone language mechanism
was defined by Gilad Bracha (http://www.bracha.org/oopsla90.ps) in a way
that also clearly inserts them into an inheritance chain. Even Scala traits
are treated the same way (they ought to have been designated as mixins, but
Martin Odersky just happened to prefer the word 'trait' ;-).

Traits (as in http://scg.unibe.ch/archive/phd/schaerli-phd.pdf) are quite
similar to mixins, but they are different in that they satisfy a
'flattening' property, which implies that several traits added to the same
superclass will be unordered. If there are any name clashes then you will
have to apply renaming or similar operators to individual traits to
eliminate the clashes. But even in that model, the methods defined by the
traits which are added to a given superclass will be inserted into the
inheritance chain: Super calls will invoke trait methods just as well as
class methods, depending on which one is nearer according to the
inheritance chain. You could say that traits which are added "at the same
time" to an inheritance chain will be "melted together"; otherwise they
work very much like mixins.

You are, of course, free to argue that we should have something which is
completely different from mixins, but (apart from the worries about
breaking changes) with such an argument should also come a justification
that the proposed model is a good design. Is there anything in the
literature or in existing languages that uses the approach that you
recommend?


On Sat, Apr 16, 2016 at 1:42 AM, Alfred Morgan <notifications@github.com>
wrote:

> I don't want exactly the same. Exactly the same runs into all the other
> issue any other language that allows multiple inheritance has. I'm looking
> at this from a point of view where mixins should keep to themselves and not
> play as big of a part with the inheritance system. Make mixins
> significantly different. From this point of view calling bar() would call
> their own respective bar() method. The output of baz() would unsurprisingly
> be E D. If one wants to override methods then one can use the tried and
> true extends chain.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26194#issuecomment-210686122>
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by Zectbumo** [comment]
> If, as stated, you 'prefer that a super call does NOT call any mixin methods' then I'm afraid you just don't want mixins.

I'll try to keep that in mind.

> Is there anything in the literature or in existing languages that uses the approach that you recommend?

Well, I would like to focus on the missing functionality in Dart and that is Dart losses access to the methods of the inherited classes when there is a naming collision. I guess any language that has the ability to pass in a this/self reference can get around this access problem. Here's a Python example:
```
class Mixin_A:
    def init(self):
        print "init A"
class Mixin_B:
    def init(self):
        print "init B"
class One(Mixin_A, Mixin_B):
    def init(self):
        Mixin_A.init(self)
        Mixin_B.init(self)
class Two(Mixin_A): pass

one = One()
one.init() # init A init B

two = Two()
two.init() # init A
```

**Comment by eernstg** [comment]
I keep hesitating whenever you suggest that it should be possible to address methods "in the middle of the inheritance chain" using scope resolution operators (similarly to `C::foo()` in C++). The main reason is that this makes it possible to pick out a method implementation whose behavior is invalid for a subclass. The programmer may be unaware of this, because the dependency has been introduced after the time where the scope resolution operator was written. In general, it is dangerous to let remote code (even in a subclass, but certainly for an external caller) make the decision about which implementation of a given method selector is the right one to invoke. That makes me prefer mechanisms where the basic choice ("call the most specific implementation") rules, and the only exception is `super` invocations (which are semi-encapsulating because they just request the "next" method, not a specific implementation).

But one way to make all those methods available to the ultimate subclass would be to enable method aliasing at mixin applications: `class C extends B with M1 rename .., M2 rename .. {}`. This is an idea straight from trait-land, and it would certainly enable mixins to work together more smoothly when there are accidental name clashes. This makes sense especially with accidental name clashes, because there is no conceptual reason why those methods should hide each other, and it also allows for relatively centralized management of the renaming, such that it can be updated in case the original methods are renamed or moved around.

How do you like that?

**Comment by Zectbumo** [comment]
> I keep hesitating whenever you suggest that it should be possible to address methods "in the middle of the inheritance chain" using scope resolution operators…

I see.

> This is an idea straight from trait-land, and it would certainly enable mixins to work together more smoothly when there are accidental name clashes.
> …
> How do you like that?

That's a great step and should solve my specific issue. I would want to confirm we are thinking an alias and not a rename, as the traits paper you linked earlier mentioned:
> Defining an alias y for a method x in the trait T just establishes an alternative name y without affecting the original one.

I don't know what the syntax to specify multiple aliases defined for the same trait would be but I only need one right now but if multiple can be specificed I can see someone abusing aliasing essentially every method of a whole class. This brings up a concern of reading other people's code. If I see an unfamiliar name used in code then I will have to look in an additional place (the alias definition) to find where this name was defined. 

This aliasing trait methods might have to happen anyway for the language to move forward but now I'm thinking: "Be careful what you wish for." and leaning towards what you said "you just don't want mixins".

**Comment by Zectbumo** [comment]
So I thought over the question. If mixins is not what I want then what else would I want? The answer might be a dose of Zope components explained here in this Twisted documentation http://twistedmatrix.com/documents/12.3.0/core/howto/components.html
This interesting concept is designed to handle same named methods from inheritance. Could Dart borrow a page from this playbook?

**Comment by lrhn** [comment]
@eernstg wrote:
> That makes me prefer mechanisms where the basic choice ("call the most specific implementation") rules, and the only exception is super invocations (which are semi-encapsulating because they just request the "next" method, not a specific implementation).

Not only that, the encapsulation is at the single "class extends other class" level - the super call is relative to the actual declared superclass of the class containing the super call. It doesn't know how that class has that method, but if you `extends Foo` then calling `super.bar()` is calling the same `bar` that you would get with `new Foo().bar()`. The superclass encapsulation is total - you don't know what superclass it has, and it can change that at any time, as long as it still exposes the same interface in the end.

That's the same reason I argue against allowing `super.super.foo()` - it breaks the encapsulation of the superclass.

**Comment by eernstg** [comment]
About http://twistedmatrix.com/documents/12.3.0/core/howto/components.html:

Interesting! I noted that their notions of "Interfaces" and "Adapters" refer to the usage of a proxy object which delegates to the original target and supports a given interface (so O1 is a `Foo` and can't be a `Bar`, but we can create an O2 which delegates to O1 as needed and is a `Bar`). They have support for registering adapters (which would create a suitable O1 of the requested type, and tie it up to the given O1), which makes it easy to get a "version" of a given object that has a specific interface.

Note that the approach they describe involves only simple forwarding (`myMethod` in O2 calls `myMethod` on O1 using a plain method call), and that doesn't work in non-trivial cases (this is known as "the self problem", cf. http://web.media.mit.edu/~lieber/Lieberary/OOP/Delegation/Delegation.html). Nevertheless, the idea to use (genuine) delegation to express many, many things including inheritance and the Facade design pattern has been well-known since the 80'ies: Just check out the language SELF. So there's no doubt that we could do loads of cool things with real delegation support.

You might be able to use `noSuchMethod` to do this (whenever `noSuchMethod` is invoked, just perform the same invocation on the delegatee), especially if you don't insist on static type checking. But it's not really a mechanism which is intended to carry as much weight in Dart as it was in SELF.

However, the most basic idea behind delegation is that the method invocations involve more than one object. I keep thinking that the wish to call several different `init` methods separately reveals that they are simply distinct methods (which is the reason why I claimed that the name clash would be accidental, and the reason why I suggested that the methods should use a renaming mechanism or extra mixins to avoid the name clash): With N distinct methods `init1` .. `initN` it's not surprising that you can call any subset of them you want, including all of them, in any particular order. The same thing would be true if you use instances of all those classes which would otherwise be used as mixin classes. Your main object could have a field for each of them, say, `forwardee1` .. `forwardeeN`, and then you could distinguish the `init` methods with that: `forwardee1.init(); .. forwardeeN.init()`. Do you actually need to inherit from all those mixins?

**Comment by floitschG** [comment]
I haven't read the full bug, but I believe you can solve your problem by renaming the init from Mixin_A.
That is, by giving access to it through a different name.
I modified your example by adding a Mixin_Rename_A_Init that provides an alias for A's init method.

``` dart
// Imported lib you cannot change
class Mixin_A {
    init() {
        print("init A");
    }
}
// Imported lib you cannot change
class Mixin_B {
    init() {
        print("init B");
    }
}

class Mixin_Rename_A_Init extends Mixin_A {
  init_A() {
    super.init();
  }
}

// this is your code that you can change
class One extends Object with Mixin_B, Mixin_Rename_A_Init, Mixin_A {
  init() {
    super.init();
    super.init_A();
  }
}
class Two extends Object with Mixin_A {}

main() {
    var one = new One();
    one.init(); // If super is not called by lib then Mixin_B.init() will not get called

    var two = new Two();
    two.init(); // If super is called by lib then Exception: Super class of class 'Two' has no instance method 'init'.
}
```

**Comment by Zectbumo** [comment]
@floitschG thanks, your workaround actually does solve my immediate need. I think at this point this specific issue is closed but I believe the conversation I had with with @eernstg lead us down two paths for the future of Dart, each meriting their own issue.
1) Mixins (Traits) need method aliasing.
I think method aliasing is going to be required and put in the language eventually but I'm not so hot about pushing the idea since I think multi-inheritance enters ugly town so you can count me out and I'll take a workaround for now.

2) Support for genuine delegation.
This has my attention. @eernstg, it sounds like you have the best handle on this and I would happy to continue the conversation in a new issue. Is there something I can do to be of assistance?

**Comment by lrhn** [comment]
> 1) Mixins (Traits) need method aliasing.
> I think method aliasing is going to be required and put in the language eventually

I sure hope so. It's a simple feature (either pure syntactic sugar or very efficiently optimized), so you should just write:
```dart
int foo(x, y, z) = bar;
```
and it's equivalent to:
```dart
int foo(x, y, z) => bar(x, y, z);
```
Just like you currently do with redirecting factory constructors.

> 2) Support for genuine delegation.

I hope for that too, so you can easily implement an interface `Foo` by delegating to a field or expression that evaluates to a `Foo` value. 
```dart
class Bar implements Foo as _foo {  // Has all undefined members of Foo redirect to _foo.x.
   Foo _foo = new FooThatBlinks();
   bar1() => foo1();
}
```
(Or something)

Both definitely on my radar - but then, I'm all about adding features, it takes other people to hold me back :)

**Comment by eernstg** [comment]
Just a bit of clarification, will comment in more detail later: Using mixin classes like `Mixin_Alias_B_Init` in Florian's example to obtain a renaming effect for `init` in `B` is exactly the technique that I was referring to when I said 'For disambiguation you could interleave the mixins ..'.

In that context I was _using_ the renaming to bring several methods (with the same name or different names, it works in both situations) into the same super-invocation chain, but you can of course also "rename" methods with the same name to have distinct names, and then call them from some ultimate subclass using the distinct names.

**Comment by Zectbumo** [comment]
@eernstg yeah, I closed the issue so we didn't have people continue to re-solve the issue. I had my workaround and was happy with the direction that we were going. Now we just need a new thread created for delegation. (please link here so I can follow)
