### ISSUE TITLE
Update the spec to allow void as a symbol literal

### ISSUE THREAD

**Issue by mezoni** [dart-lang/sdk#26202]
```
16.6 Symbols

symbolLiteral:
‘#’ (operator | (identifier (‘.’ identifier)*))
;
```

```
types[#void] = voidType;
```

The `void` is a reserved word (nor operator nor identifier) but analyzer does not detect this violation of the language specification.

**Comment by mezoni** [comment]
If I will use this option:

```
new Symbol("void");
```

Then my Dart code (because it violates of the language specification) can be considered as not a vulnerable and a reliable software?

**Comment by bwilkerson** [comment]
I don't see anywhere in the specification that states or implies that this is invalid. Should analyzer be producing an error, or should the VM be accepting this?

**Comment by mezoni** [comment]
@bwilkerson

This is invalid Dart code when a symbol literal used not with `operator` or `identifier` or `identifier.identifier` etc.

```
symbolLiteral:
‘#’ (operator | (identifier (‘.’ identifier)*))
;
```

This is the same as if a symbol literal used with something other.

Eg.

```dart
// Not a valid Dart code
var s = #123;
// Not a valid Dart code
var s = #for; 
```

You undestand? This is by the Dart syntax.

>> I don't see anywhere in the specification that states or implies that this is invalid.

I think that specification states that not valid Dart (by the grammar) code should produce error.
Symbol literal is a part of the language grammar, the same as the other literals.
This code should produce a `parser error` because it has syntax error.

```dart
var s = #for; 
```

You undestand?

**Comment by eernstg** [comment]
The spec (looking at v1.11, Aug 19 2015) section 16.33 defines 'IDENTIFIER' in an unsurprising way (basically, it's '\$?[a-zA-Z_][a-zA-Z_0-9]*'), and it says 'identifier ::= IDENTIFIER'. So by this definition `void` is a perfectly good 'identifier'. 

But section 20.1.1 lists the reserved words and specifies that 'A reserved word may not be used as an identifier; it is a compile-time error if a reserved word is used where an identifier is expected.', which means that reserved words are _not_ included in the set of identifiers (which adjusts the meaning of 'identifier ::= IDENTIFIER' by a magic remote effect ;-).

I'd say this `#void` invalid.

However, I think this is a matter of adjusting the spec rather than adjusting implementations; we could have `symbolLiteral: '#' (operator | (IDENTIFIER ('.' IDENTIFIER)*));` and thus allow for the reserved words in this position as well.

Any problems with that, @gbracha?
