### ISSUE TITLE
Profiler_GetSourceReport fails with low optimization_counter_threshold

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#26214]
(failures seen with threshold 5 and 7, not with 10)
xcodebuild/DebugX64/run_vm_tests --optimization-counter-threshold=7 Profiler_GetSourceReport

/sources/git-two/sdk/runtime/vm/profiler_test.cc:2434: error: expected: controlFlowPc != 0

**Comment by sgmitrovic** [comment]
Also issues with tests:
Profiler_CodeTicks
Profiler_FunctionTicks

Tests run without background compilation with threshold at 7.

**Comment by johnmccutchan** [comment]
`Profiler_GetSourceReport` fails because it is very sensitive to the shape of the compiled code. Different optimization counter thresholds change it too much.

I have a fix for `Profiler_FunctionTicks` https://codereview.chromium.org/2465763004

`Profiler_CodeTicks` fails with different optimization counter thresholds (in different ways) because it is sensitive to inlining decisions.
