### ISSUE TITLE
StreamSubscription callback setters should run callbacks in the zone they were set

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26226]
Consider the following code:

```dart
import 'dart:async';

void main() {
  var controller = new StreamController();
  var subscription = controller.stream.listen(null);

  runZoned(() {
    subscription.onData((_) => print("data: ${Zone.current[#test]}"));
    subscription.onError((_) => print("error: ${Zone.current[#test]}"));
    subscription.onDone(() => print("done: ${Zone.current[#test]}"));
  }, zoneValues: {#test: true});

  controller.add(null);
  controller.addError("");
  controller.close();
}
```

This prints

```
data: null
error: null
done: null
```

which seems wrong. The `onData()`, `onError()`, and `onDone()` functions are called within the `runZoned()` zone, but the callbacks they register are called in the same zone as the call to `Stream.listen()`.

**Comment by floitschG** [comment]
This was a deliberate choice.
`onData`, `onError` and `onDone` are not the locations where the program goes asynchronous, but the `listen` call is. We make sure that the callbacks are registered at the subscription's zone, though. That is, the `onData` (resp. the others) will call `zone.registerCallback` on the zone of the `listen` call.

Working as intended.

**Comment by nex3** [comment]
What does "the program goes asynchronous" mean? Do you expect your users to understand that concept? If so, where is it documented?

I believe that users (those who think about zones at all) don't have any internal metaphor about our code "going asynchronous"—certainly not relating to zones. The metaphor we do understand is one of dynamic scope, which is explicitly endorsed by the documentation. We understand that a callback is run in the same zone it was registered in. This metaphor is universally true across all asynchronous APIs *except this one*, and should be true everywhere.

**Comment by lrhn** [comment]
I tend to agree with Natalie. 

The initial listen on a stream is scoped entirely in the zone where the `listen` is called - all the way down to the source stream, no matter how many times it was wrapped. That's why the functions passed to `map` and `where` don't register in a zone, they will run in the `listen`-zone. That makes sense - the subscription - the active part of the stream - belongs to that zone.

The callbacks that are set at a later time may have been created in a different zone. They should remember that zone because that's what they visually look like (if they are written inline at least).
(That may add extra overhead for the `onError` callback to check if the zones have the same error handler).

**Comment by natebosch** [comment]
@lrhn - should we reopen this for consideration? Or is the fact that it hasn't come up again in almost 4 years a sign that we don't need to worry about it?
