### ISSUE TITLE
language: tail yield* in sync* generators

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26256]
I see this pattern used:

``` dart
Iterable<int> from(int n) sync* {
  yield n;
  yield* from(n + 1);
}
```

It would be nice if this pattern was handled well. Current implementations build a deeper and deeper stack of iterators, leading to quadratic time and linear space to enumerate the elements.
We could define the tail-position `yield*` of a generated iterator to _replace_ the current iterator. That would ensure the above code runs in linear time and constant space.

**Comment by lrhn** [comment]
I'm not sure how you replace the iterator, but some internal implementation could probably pass the internal access to the iterator to the new function call, instead of creating a new iterator for the call. 
It's an optimization that can be done if the call is recognizable as a "sync*" function. (And something similar can be done for yield* in async* functions too).

**Comment by lrhn** [comment]
Since there is no language change in this, the current specification allows optimizing the feature as long as it's indistinguishable from the current behavior, I'm closing this issue.
