### ISSUE TITLE
yield* ignores exception handlers in sync* functions

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#26262]
The spec has `moveNext` called at the point of a `yield*`, but both dart2js and the VM ignore exception handlers at the point of yield\* .

``` dart
import 'dart:collection';

class AlwaysThrowingIterator implements Iterator {
  bool moveNext() => throw 'moveNext';
  get current => throw 'current';
}

class AlwaysThrowing extends IterableBase {
  Iterator get iterator => new AlwaysThrowingIterator();
}

f() sync* {
  try {
    yield* new AlwaysThrowing();
  } catch (e) {
    print('caught $e in f');
  }
}

main() {
  try {
    for (var x in f()) {
      print(x);
    }
  } catch (e) {
    print('caught $e in main');
  }
}
```

Should print `caught moveNext in f` but prints `caught moveNext in main`.

**Comment by floitschG** [comment]
As mentioned in #25662, it might make more sense to just treat a `yield*` as "here are the next elements". In the async world, we use `controller.addStream` where it is pretty clear, that the caller of that method does not care for errors anymore and hands them over.

**Comment by lrhn** [comment]
I'm not sure the solution that work for a `Stream` can be applied to an `Iterable`.

A stream is push based and has a built-in error channel so it can't *fail*. Yielding all the contents of the stream is well-defined.

An iterable can throw in both `moveNext()` and `current` (but really, really shouldn't in `current`). There is no natural place to put such an error. It *looks* like `try { yield* foo; } catch (e) { ... }` encapsulates the `foo` iteration, so if `foo` iteration throws and it bypasses the `try/catch`, it is surprising because there is no logical path that error could have followed to get from `yield* foo` to the `moveNext()` call.

**Comment by rakudrama** [comment]
Florian - how do you write this if `yield*` passes up the whole collection?

```
linesFromFile(filename) {
  var handle = open(filename);
  try {
    yield* linesFromFileHandle(handle);
  } finally {
    close(handle);
  }
}
```

**Comment by floitschG** [comment]
At that point I would do a loop.

It looks like everyone else agrees that the try should deal with errors from the iterable, so we should probably go with that one. (The current solution is just my preference. The other one is fine too).
We need to figure out what we want to do with Streams, though, since they should have similar semantics.

**Comment by lrhn** [comment]
The spec is clear, and now both VM and dart2js catches the error.
