### ISSUE TITLE
Please, clarify the conformance of math functions

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26261]
The description for `dart:math` package ( https://api.dartlang.org/stable/1.15.0/dart-math/dart-math-library.html ) reads:

> Mathematical constants and functions, plus a random number generator.

Please, clarify the level of conformance of provided math functions.
1. How the used algorithms and calculated results correspond with certain published algorithms? 
2. Should the functions return the same results across all supported platforms?

For example, the following test

``` dart
import "dart:math" as Math;

main() {
  print(Math.acos(-0.74603174603174605000));
}
```

produces different results on linux `2.4128792028463875` and windows `2.412879202846388` platforms
Is it normal behavior?

**Comment by whesse** [comment]
The transcendental functions in cmath are not defined to return exact results, only (very good) approximations.  Therefore, they will not always return the same values on different platforms.  The tests should allow at least a 1 or 2 ulp difference.

**Comment by alsemenov** [comment]
I think it is a subject of specification to define the degree of the approximation. Otherwise it is not possible to create correct test. There will always be some implementation which gives greater ulp difference than the test expects.

**Comment by lrhn** [comment]
We have no plan to specify the precision.
The results are provided by platform functions that we have no control over, so we can only promise to give as precise a result as we have available.
If Dart implemented its own trigonometric functions, we could decide what the precision is. 
Since we are not, we'll have to make do with what we have available, including what arbitrary JavaScript engines include.

For interesting reading: https://bugs.chromium.org/p/v8/issues/detail?id=3006, https://bugzilla.mozilla.org/show_bug.cgi?id=967709.
