### ISSUE TITLE
void is not supported as a generic method type argument

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#26275]
Reported by @jacob314 over at https://github.com/dart-lang/dev_compiler/issues/496

---

Repro:

``` dart
wrapZone/*<E, R>*/(/*=R*/ callback(/*=E*/ evt)) {

}
...
wrapZone/*<Event, void>*/(someCallback).
```

**Comment by jmesserly** [comment]
CC @leafpetersen 

It'd be nice to have some consistency around `void` -- this was something I always found annoying about generic function types in C# (and our func.dart package has a similar problem)

That said this seems like a Dart 2 issue, rather than something we can address in the short term.

**Comment by zoechi** [comment]
Shouln't it be `Null` instead of `void` or is this about support `void` as alternative to `Null`?

**Comment by lrhn** [comment]
In Dart, `void` is not a type expression. It's something you can write instead of a type expression as the return type of a function. So, you can't use it as a type parameter, even if the type parameter is going to be used as a return type. 

In this particular case, I'd consider parameterizing the class with the function type instead of with the parameter and return type:
```dart
wrapZone/*<F extends UnaryFunction>*/(/*=F*/ callback)
```


Persoanlly, I'd accept `void` as a type anywhere. It doesn't make a lot of *sense* as a parameter type, but if you really want it, I don't have a problem with that.

(The "void" type represents the empty type, a type with no value, hence the name. It doesn't make sense in places other than return types because you can never produce a value of that type - and for return types it only makes sense because `null` is assignable to any type, even `void` - with non-nullable types, a `void!` function would be one that never returns, e.g., always throws).

**Comment by jmesserly** [comment]
CC @leafpetersen ... does it make sense to kick this to area-language instead of strong-mode. I don't think there's anything actionable we can do in the implementation

**Comment by jmesserly** [comment]
I'm going to reclassify this as area-language, I don't think it's something we can address via strong mode

**Comment by leafpetersen** [comment]
Under consideration for the language.

**Comment by munificent** [comment]
De-duping with newer but more active other issue: #27504.
