### ISSUE TITLE
Optimize Uri.parse for "data:" scheme

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#26280]
At the moment, getting a content of a `data:` URI with `Uri.parse(...).data.contentAsBytes()` results in at least 4 full string scans:
1. [Loop](https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/uri.dart#L548) inside `IN_PATH` state 
2. Loop inside `Uri._normalize` called from `Uri._makePath`
3. `path.split` in `_removeDotSegments` called from `Uri._makePath`
4. `contentAsBytes()`

Maybe the first three scans can be avoided in case of `data:` scheme?

**Comment by lrhn** [comment]
The `Uri` class is validating, so some sort of validation is needed, and a data URI parsed as a hierarchical URI will need to recognize embedded `#` and `?` characters in order to have the correct query and fragment parts.

We might go for an optimistic parsing of the input as a data URI, and only fall back to the complex hierarchial parsing if it's not a valid data URI. It will mean special casing of the "data" scheme, but we do recognize so that seems fair.

**Comment by lrhn** [comment]
Even optimistic parsing won't necessarily be enough. The `Uri` class does all sorts of normalization which it must do for data: URIs too. It's always going to be more efficient to just use `UriData.parse(...).contentAsBytes()` directly instead of going through `Uri.parse`, not matter how efficient we make the latter.

**Comment by lrhn** [comment]
I've made `Uri.parse` defer to `UriData.parse` for `data:` URIs. That actually means that it skips some normalizations, but I think that's the correct behavior. A `data` URI isn't hierarchial, and the `Uri` class and its default normalizations are really intended for hierarchial URIs.

**Comment by lrhn** [comment]
I've moved back on this decision now, and actually added some normalization.
