### ISSUE TITLE
Wrong 'Invalid override' message in subclass 

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#26313]
The following code:

    abstract class Foo {
       List<Object> get a;
       Foo update(List<Object> a);
       toString() => 'Bar: $a';
    }

    class Bar extends Foo {
      final List<int> a;
      Bar(this.a);
      Bar update(List<int> l) => new Bar(l);
    }

Runs with out error, but in strong-mode generates the following message:

    ERROR: Invalid override. The type of Bar.update ((List<int>) → Bar) is not a subtype of Foo.update ((List<Object>) → Foo).

It is similar to Issue 26251, but not the same as it is using 'Object' not 'dynamic'

**Comment by eernstg** [comment]
It is indeed an invalid override: Strong mode enforces contravariance for argument types in function subtyping and hence also for method overriding (https://github.com/dart-lang/dev_compiler/blob/master/doc/STATIC_SAFETY.md). So `List<int>` must be a supertype of `List<Object>` in order to make the override correct, and since Dart generic classes are everywhere-covariant this means that `int` must be a supertype of `Object`, and that isn't true.
