### ISSUE TITLE
Detect impossible equalities

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#26311]
Strong-mode could / should prevent accidental heterogeneous (in)equalities "when it can":
```dart
var x = "1";
if (x == 2) print("Hey");
//  ^
// [error]: A 'String' instance can never be equal to a 'num'.
```

Of course, this is only possible (accurate) for classes that can't be implemented by user classes (`String`, `num`, etc):
```dart
class Foo {}
class Bar {}
class FooBar implements Foo, Bar {}

Foo foo = ...;
Bar bar = ...;
if (foo == bar) // Foo and Bar aren't related, yet this can be true because of FooBar
```

**Comment by mezoni** [comment]
Your judgements are wrong.
This is correct operation and it allowed.
Nothing wrong, everything is well in your case.

```
bool operator ==(Object other) 
```

https://github.com/dart-lang/sdk/blob/master/runtime/lib/string_patch.dart#L249

**Comment by eernstg** [comment]
You might want to take a look at 'Related Types' (
https://books.google.dk/books?id=-7OrCAAAQBAJ&pg=PA434&lpg=PA434) where
Johnni Winther describes a number of similar considerations in the context
of Java.

The point is that it is unlikely (if not impossible) that a comparison for
equality among objects of different types will produce the result `true`,
and if your code contains an `if` whose condition is always `false` (even
though that's not necessarily so easy to see) then your program is probably
buggy. If you really want to force such a comparison then you can cast the
operands to a common supertype.

But it will almost never be guaranteed that the comparison yields `false`,
because anyone can write a class that implements arbitrary other types
(except a few built-in ones like `int` and `String`), so it's more
reasonable to make it a lint than a warning or even an error.


On Thu, Apr 21, 2016 at 2:11 PM, mezoni <notifications@github.com> wrote:

> Your judgements are wrong.
> This is correct operation and it allowed.
> Nothing wrong, everything is well in your case.
>
> bool operator ==(Object other)
>
>
> https://github.com/dart-lang/sdk/blob/master/runtime/lib/string_patch.dart#L249
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26311#issuecomment-212886397>
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by ochafik** [comment]
> then your program is probably buggy

That's the point of this proposal: detect buggy programs :-)

> it will almost never be guaranteed that the comparison yields `false`,
> because anyone can write a class that implements arbitrary other types
> (except a few built-in ones like `int` and `String`)

Agreed, it's precisely what I suggested: "when it can" (int, bool and String are frequent enough to catch misuses, imho).

**Comment by ochafik** [comment]
Note: TypeScript detects these cases (cc/ @leafpetersen)

**Comment by zoechi** [comment]
This seems related dart-lang/linter#229

**Comment by mezoni** [comment]
@ochafik 
>> Note: TypeScript detects these cases (cc/ @leafpetersen)

This is incorrect comparison because in Dart language everything is an instance of the `Object` but in Typescript this is not true.

And I agree that this is an illogical action (which maybe a bug) but analyzer is not a tool which should used for detecting illogical actions in the source code, for such purpose should be used other tools.

**Comment by eernstg** [comment]
Surely, the analyzer's main job is to track specified error and warning
situations, but I don't think it is unreasonable to give a hint when
objects of unrelated types are compared for equality. So it doesn't have to
be a different tool.

On Thu, Apr 28, 2016 at 2:57 PM, mezoni <notifications@github.com> wrote:

> @ochafik <https://github.com/ochafik>
>
> Note: TypeScript detects these cases (cc/ @leafpetersen
> <https://github.com/leafpetersen>)
>
> This is incorrect comparison because in Dart language everything is an
> instance of the Object but in Typescript this is not true.
>
> And I agree that this is an illogical action (which maybe a bug) but
> analyzer is not a tool which should used for detecting illogical actions in
> the source code, for such purpose should be used other tools.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26311#issuecomment-215414956>
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by alexeieleusis** [comment]
Are there any cases besides the ones covered in https://github.com/dart-lang/linter/pull/232 that we want to implement?

**Comment by ochafik** [comment]
@alexeieleusis Not that I can think of, good work / thanks for adding that lint!

Closing (unless anyone feels strongly this should make it to strong mode?)
