### ISSUE TITLE
Please, clarify specification List.getRange()

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#26332]
The description of method `List.getRange(int start, int end)` reads:
( https://api.dartlang.org/stable/1.15.0/dart-core/List/getRange.html )

> Returns an Iterable that iterates over the objects in the range start inclusive to end exclusive.
> 
> An error occurs if end is before start.
> 
> An error occurs if the start and end are not valid ranges at the time of the call to this method. 
> The returned Iterable behaves like `skip(start).take(end - start)`. 
> That is, it does not throw exceptions if this changes size.

It is not clear, how the range is determined to be valid.
Let's assume that `start` and `end` are indexes:
`var list = [1];`
`list.getRange(-1,0)` - invalid, because index can not be negative
`list.getRange(0, 1)` - valid, because `end` is exclusive
`list.getRange(1,1)` - invalid, because `start` is inclusive and index value 1 is invalid.

In fact `list.getRange(1,1)` returns an empty list, which means that range `[1,1)` is considered as valid.
This may be explained with help of `skip(start).take(end - start)`, which will produce an empty list for `[1,1)`. But the range `[2,2)` should also be valid then. But in fact it is not.

Please, clarify input range verification rules.
Also, please, clarify whether `list.getRange(list.length, list.length)` returning empty list is valid, intended behavior or not.

**Comment by lrhn** [comment]
A range from `start` to `end` is valid for a list if `0 <= start <= end <= list.length`.
The range starts at `start` and has length `end - start`. An empty range is valid (with `end` == `start` aka. length == 0).
So we define this somewhere in general? Otherwise it might be a good idea to document it on `List`.

So, for `list = [1]`, `list.getRange(1, 1)` is valid.
Saying that start is "inclusive" is a simplification. It's almost correct, but the real explanation is that it's interval arithmetic and the numbers are not indices of elements, they are indices of positions between elements. The position zero is just before the first elements, the position `list.length` is just after the last element, and the rang between positions `start` and `end` are the elements between those positions. That's just too complex to document, so we say "start is inclusive, end is exclusive" and skimp on the explanation of what it means when `start == end` (including `start == list.length`).

The `getRange` method returns an iterable, not a list, so `list.getRange(list.length, list.length)` returns an empty `Iterable`. That's valid and intended. It might be slightly counter-intuitive that `getRange(1, 1)` and `getRange(2, 2)` are different when they both define an empty range, but if `2` isn't a valid position in the list, then the latter is likely indicating a logical error in the program, where the former is just an empty sub-range of the list.

The "behaves as `skip(start).take(end-start)`" only applies if the requirement of the previous statement didn't raise an error - otherwise there is no returned `Iterable`. I don't remember whether the behavior is exactly like `skip+take` if the underlying list's length changes - but it's not unlikely that it uses the exact same `Iterable` implementation.

**Comment by floitschG** [comment]
Uploaded a CL: https://codereview.chromium.org/2632393003
