### ISSUE TITLE
"Functions marked 'async' must have a return type assignable to 'Future'"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26334]
Shouldn't `dynamic` work here?

```dart
dynamic main() async {
  ...
}
```

**Comment by jmesserly** [comment]
did you mean to write `Future<dynamic>` (aka `Future`)? or maybe just omit the return type?

I mean technically we could let you write `dynamic` or `Object` there, but it's just throwing away information, so it is all downside and no upside :). It will always return a Future. async methods desugar into:

```dart
main() {
  // note: strong mode will put "T" there based on what is returned. VM leaves it off
  return new Future/*<T>*/(... magic compiler generated function ...);
}
```

**Comment by zoechi** [comment]
I find it cumbersome to import `dart:async`, for example for lots of sync test files for the return type of `main()` where I never care about. 
I expected explicit `dynamic` (like in my original post) to be sufficient when I don't want to specify a more concrete type.

I have strong-mode and almost all linter rules enabled (always_specify_type, always_declare_return_types)

**Comment by jmesserly** [comment]
Would you be okay with implicit return type? You can just write:
```dart
main() async {
  ...
}
```
Pros:
* it's short
* no import of "dart:async" required
* it's precise (return type will be known as "Future")

**Comment by zoechi** [comment]
Would this be an exception for `main()` in `always_declare_return_types`?

I don't feel strong about this issue. I mostly reported because I assumed there is something broken. 
If this is just a special rule for `async` functions this makes sense though.  

Is this behavior enabled just by enabling strong-mode or by some linter rule?

**Comment by jmesserly** [comment]
yeah, for always_declare_return_types. IMO that's the sort of thing we'll likely want to revisit w/ strong mode. It shouldn't force you to do something when inference would conclude the exact thing IMO. (We don't in general infer return types, but async/sync*/async* functions and ones that just extend a superclass method, like implementing `toString() => "MyObject"`, are the exceptions)

**Comment by zoechi** [comment]
Ok, sounds great :)

**Comment by leafpetersen** [comment]
Is there any downside to allowing async functions to return anything which is a supertype of Future?

**Comment by jmesserly** [comment]
@leafpetersen -- theoretically, no downside. From a practical standpoint, yes: we'll generate worse code for essentially no benefit. (Not to mention, someone has to make a CL, add tests, etc...)

It sounded like the underlying issue here was the `always_declare_return_types` linter rule forcing a (in this case, useless) return type declaration.

**Comment by zoechi** [comment]
I'm still wondering. The linter rule `always_declare_return_types` shouldn't force a specific type annotation, only that one is provided. Strong-mode should check that the provided type is compatibel with the types of assigned values. `dynamic` allows to assign everything. Therefore `dynamic` should not produce a warning.

Of course, I usually will provide a more specific type to get full benefit from the analyzer, but sometimes, when there is nothing to gain from a concrete type I just use `dynamic`.

Where is the flaw in my reasoning?

**Comment by jmesserly** [comment]
If you're writing code for the web, using explicit `dynamic` will cause a lot more runtime type checks and dynamic dispatch and stuff like that to be generated by Dart Dev Compiler. Whether that is a factor for you, I'm not sure. :)

e.g.
```dart
import 'my_main.dart' as my_main;
// ...
  test('main works', () async {
    await my_main.main(); // <-- DDC inserts implicit runtime check here.
    // (because we didn't know it was a Future. It claimed it could return any kind of value.)
  });
```
Since this example was `main` it probably doesn't matter :). If you go around and do this for a lot of your async methods or packages, it will cause suboptimal code generation by users DDC.

Also in general, we would really like strongly typed code to become more of the norm. What seems to have happened here is, writing out `Future` is annoying because of the extra `import "dart:async"`. We anticipated that, and that's why we infer `Future` for you, to make the best thing also the easiest to write :). But you also are running linter, which has a `always_declare_return_types` rule. Which leads to the `dynamic` annotation. Our inference and linter got conflicting eachother a bit so that's something we'll need to think through.

But yeah, this is totally good as an issue to file. :)

**Comment by bwilkerson** [comment]
Sounds to me like the lint rule shouldn't require return types when strong mode is enabled and the return type will be inferred. Either that or we need a second rule that works the way I just described (`usually_declare_return_types`?), so that people who really do want return types everywhere, needed or not, can have them.

@hixie @pq

**Comment by leafpetersen** [comment]
I'm pretty sure we don't ever infer a return type for a named function (except for propagating super class method types to overrides).  We infer return types for anonymous functions, but they already have no place to write down a return type, so I don't think we're talking about them.  So I don't understand where strong mode inference comes into this at all?

We currently, and I believe should continue to, check that everything that is returned from an async function is either a `Future<T>` or a `T`, where `Future<T>` is the return type of the function.  Is this what is meant by inference here?

If we allow async functions to have non `Future` return types, then we would only be able to do this check when the return type is in fact `Future`.  

In my best of all worlds, I would have the `async` keyword take a type parameter, so that code would look like this:

``
ReturnType myFunction(int x) async<int> => int
```

and we would only require that `Future<int> <: ReturnType`.   This isn't the Dart syntax though.  I think that as a second best compromise, we're best off requiring that the return type be explicitly `Future<T>`, essentially making the return type be part of the async syntax.

**Comment by jmesserly** [comment]
> I'm pretty sure we don't ever infer a return type for a named function (except for propagating super class method types to overrides).

Ah, right. I remembered the code, forgot it only kicked in for function expressions. That makes sense though. So no inference on these.

(it's confusing because FunctionDeclaration wraps a FunctionExpression, and FunctionDecls can be all kinds of things from statements to top-level functions to getters/setters, so in a visitor it's not always obvious if the code runs only for function *expressions* or not ... then in DDC, our JS AST has a similar but slightly different representation... hard to keep it all straight =/ )

**Comment by floitschG** [comment]
A `Future<int>` is a `dynamic` and thus should work. I can easily imagine cases where this is necessary. For example, if I want to subclass and override that method and return a different type. Without the `dynamic` I would be forced to always return a Future.

**Comment by Hixie** [comment]
> Also in general, we would really like strongly typed code to become more of the norm.

For the record, at least in Flutter's case, a lot of our customers couldn't care less about typing and have no interest in writing types. The way you can use Dart in both an explicitly-typed manner and an implicitly-typed manner is a big part of Dart's appeal. It means the same framework can be used by programmers coming from a Java/C++/ObjectiveC world with "real" typing and programmers coming from a Python/JavaScript/PHP world with no typing, without either side having to get used to the other side's conventions.

**Comment by jmesserly** [comment]
sorry about that, should've chosen my words more carefully :)

But yes totally agree different users, and I especially like the "high performance library writer" vs "app author" distinction. I'd sort of grouped @zoechi into the "advanced user bucket" because of the always really awesome bug reports and feedback (thanks!!! :) ) ... so that was the context of my comment.

Naturally we support explicit `dynamic` as well as leaving types off in all kinds of cases in strong mode, that was a very important design goal.

This one corner case of `async` methods might be classified a bit specially because we've seen a lot of incorrect usage (folks think `int f() async { return 42; }` should work, or that they can return their custom future type: `Cancelable f() async { ... }`). And in general, explicit dynamic is not preferred compared to implicit (https://www.dartlang.org/effective-dart/design/#avoid-annotating-with-dynamic-when-not-required). That's all I was trying to get at.

**Comment by jmesserly** [comment]
> A Future<int> is a dynamic and thus should work. I can easily imagine cases where this is necessary. For example, if I want to subclass and override that method and return a different type. Without the dynamic I would be forced to always return a Future.

I'm not sure if this is what you're talking about, but this example is not allowed in strong mode:
```dart
import 'dart:async';

class Base {
  Future<int> foo() async => 42; 
}
class Derived extends Base {
  dynamic foo() => new Future.value('oops!!!');
}

main() async {
  int x = await new Derived().foo();
  print(x + 1);
}
```
```
[error] Invalid override. The type of Derived.foo (() → dynamic) is not a subtype of Base.foo (() → Future<int>). (test.dart, line 7, col 3)
```

**Comment by jmesserly** [comment]
sent fix out for review https://codereview.chromium.org/1924113002/ :)
(looks like this may have been unintended result of disallowing `SubFuture`)

**Comment by jmesserly** [comment]
@zoechi -- fix is landed. Will show up in the next 1.17 dev release. Cheers!

**Comment by zoechi** [comment]
@jmesserly :Great! Thanks for all the great feedback to my issues :)
