### ISSUE TITLE
Dartium fails compile on mac

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#26344]
We have seen this error before, and it is showing up again: 

tools/build/mac/verify_order: unordered symbols in /b/build/slave/dartium-mac-full-be/build/src/out/Release/Chromium Framework.framework/Versions/A/Chromium Framework:
_Dart_CreatePrecompiledSnapshotAssembly
_Dart_CreatePrecompiledSnapshotBlob
ninja: build stopped: subcommand failed.

It seems to have started on Apr 25.

@alan-knight @jacob314 @terrylucas

**Comment by terrylucas** [comment]
Fixed with below 2 CLs VM added 2 new DART_ APIs that need to be defined in the framework.order file for Mac builds.

[Chromium CL](https://src.chromium.org/viewvc/chrome/branches/dart/dartium/src?view=rev&revision=18554681ff1dfb53a553375c1b0c641fb3d63a1a)
[Dart CL](https://github.com/dart-lang/sdk/commit/a96e92050836b642c0d0df362b0763c821e243a2)
