### ISSUE TITLE
The which property of MouseEvent is not found in Dart 1.16

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#26354]
The removal of the which property from MouseEvent is on purpose or a bug?

The button and buttons properties are less consistent across different events. For example, in the click event, they are both zero, and in the mouse move event, the button property can't really tell if left-button is pressed. Not mentions Safari doesn't support buttons.

With the which property, it is easier to have a more generic event handler.

**Comment by zoechi** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which

> Non-standard
This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

Use instead https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

**Hint**: Left button is `0` instead of `1` in `which`

See also:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which

> Deprecated
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.

**Comment by floitschG** [comment]
Thanks @zoechi.
Tentatively closing.

**Comment by tomyeh** [comment]
IMO, deprecated or non-standard is not a good reason to make this call. For example, both keyCode and charCode are deprecated (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). Are you going to remove them too? If so, there is no reliable way to get the keystroke (the key property is not supported in Safari and stable Chrome)!

**Comment by tomyeh** [comment]
One more thing: without the which property, you can't know in Safari, if any mouse button is pressed when handling mousemove! Reason: the buttons property is not supported in Safari.

**Comment by alan-knight** [comment]
Generally our policy, for better or worse, is that we generate the APIs from Chrome IDL. We have some manual suppressions/renames, but generally we don't remove things until they disappear from Chrome IDL. That hasn't happened with "which", so I'd call it a bug that it's gone. And it may well be a bug in the generation script or a change to the IDL format that affects other APIs as well, and this is just the first one to get noticed. So it should definitely be investigated.

**Comment by tomyeh** [comment]
Understood. Thanks.

**Comment by mit-mit** [comment]
Clearing 1.17 as we are past the last full push.

**Comment by alan-knight** [comment]
Oh yeah, fixed just after the 1.17 fork.
