### ISSUE TITLE
Should generic methods subtype monomorphic methods (and how)

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#26361]
The proposed sub-typing for generic methods (and consequently the proposed override semantics) allow a generic method/function to be a subtype of a monomorphic function in certain cases.  This needs some more thought as to whether this is something we want to support (consider codegen implications) and if so, exactly what semantics we want to support.

In the current strong mode generic method prototype, the override of `m` below will succeed, but the override for `g` will fail.  This is because when we see the override of a non-generic with a generic, we simply instantiate to bounds, which produces a non-subtype for `g`.  It is statically safe to allow the override, as witnessed by choosing an instantiation of `int` for g.  I believe that we should be able to compute this instantiation without too much difficulty if we choose to.

``` dart
class C {
  dynamic m(dynamic x) => x;
  int g(int x) => x;
}
class D extends C {
  T m<T>(T x) => x;
  T g<T>(T x) => x;
}
```

A subtle but important question is whether we support this via pure subtyping (that is, we allow a generic function to flow to a use location that expects a non-generic function), vs coercive subtyping (that is, at the location where a generic function gets subsumed into a monomorphic type, we add an instantiation to make it monomorphic).  This has language implications (since I think it means that we can't support the overrides above in the coercive case), and codegen implications (since in the non-coercive case we need to support calling a generic function using the non-generic calling convention.

**Comment by eernstg** [comment]
If we consider a generic function (of type F) to be a function from a list of type arguments (<T1..Tk>) to a non-generic function (of type F(T1..Tk)), then there is hardly any other choice than coercion. (Surely there would be cases where we cannot determine statically whether a given function should be coerced, and how).

If we consider a generic function to be more like a non-generic function that happens to take a named parameter (whose name is not a legal identifier) containing the actual type arguments then there is no difference in kind between the generic and non-generic functions. Statically known coercion can be carried out by wrapping the generic function in a function literal that passes the relevant type arguments to the named parameter. In cases where coercion "should" have been performed, but wasn't because it wasn't statically known, we will simply fall back to the normal semantics of named parameters and use the default value (`dynamic` for all type arguments, of course). When a wrong number of type arguments are passed it is easy to detect at runtime (and it may or may not be known at compile time such that we can warn), and if we make an attempt to pass some type arguments to a non-generic function then it is simply an error, as always with unknown named parameters.

It seems likely that the latter approach would fit a lot better for Dart.

It would allow for invocations of `D.g` via a receiver of static type `C` (type arguments are not passed, but will be `dynamic`), and similarly for `m`. A similar scenario seems to break down if we insist that `C.g` and `D.g` are different _kinds_ of entities, as the first approach would have it.

The static checks are more tricky, of course. It would be nice if a generic method that has an instance that is a subtype (as a function) of the method that it overrides would also be a type correct overriding declaration. It might even work out fine, that the pervasive use of `dynamic` makes it accept all the invocations that the overridden method would accept. But it sounds like a tricky area that we need to dive into in more detail. ;-)

**Comment by leafpetersen** [comment]
We decided not to support this.
