### ISSUE TITLE
Build SDK independently of developer environment

### ISSUE THREAD

**Issue by mmaquevice** [dart-lang/sdk#26384]

**Comment by whesse** [comment]
We have a tool to create docker repos containing the Dart SDK already, at https://github.com/dart-lang/dart_docker.  This is for a dev repo, that allows rebuilding Dart, though.

For a Docker repository that includes all the tools needed to build Dart, it would seem strange that it includes those needed to build, but not the full set of requirements we need in order to check out and build (mainly, depot_tools is missing).

Could you explain in more detail what the purpose of this Docker repo would be, and what it does?
If we did want to provide a dart-dev repo, supplying dart and the tools for rebuilding it, why shouldn't we create it as part of the scripts in the dart_docker repo. In that case, it would be most useful if it also included the checked-out Dart repo and dependencies, wouldn't it?

It seems like this file here would be used when you already have a checked-out Dart repo with its dependencies, and just want a VM with the compilers to operate on that directory. Could you explain in detail what problem this is solving, and why this is the best solution?  This would also need more documentation, as a Wiki file or a markdown document.

@sgjesse

**Comment by a14n** [comment]
I would have like to have a container when I made contributions to the SDK. Installing all the dependencies to build it was boring and polluted my machine with things I didn't care about.

**Comment by mmaquevice** [comment]
I know there is a dart_docker repo containing the Dart SDK already. However the purpose of this DockerFile is different : it enables you to build the SDK (not build an image containing the SDK). The docker container stops once the SDK is built.
The result is that if a problem occurs when building your SDK, you can be sure it does not come from your environment. 

Another advantage is that you don't have to install manually all the dependencies you need to launch the build.

I agree this would need more documentation, and perhaps a more generic configuration of the DockerFile to cover all the different ways to build the SDK. If you think this feature could be be helpful, I'd be glad to do it.

**Comment by whesse** [comment]
OK, my main question is why this doesn't include the dependencies needed to download the source repo and all of its dependencies in third_party.  I would think that depot_tools, containing gclient, is even more unlikely to be on someone's platform already, than git, python, and g++ are.  So how were you able to check out the source, without these dependencies and more, already?

It also seems easier to just publish this as an independent repo, that people can get, rather than adding a file to the SDK repo.  If it did go into the SDK repo, it should maybe go into the tools directory, instead of the root directory.  

Most importantly, the only things I see installed are git, gcc, python, and make.  Those are absolutely standard tools, that anyone building any project from source will need on their system.  I think the group of people that want to build Dart from source, and don't want to (permanently) install git, g++, python, and make, would be very very small.  This seems to me to be a big problem with the suggestion.

**Comment by mit-mit** [comment]
Closing as there has been no reply on this for almost a month. @mmaquevice feel free to reopen with more details.
