### ISSUE TITLE
VM Service: provide information about token character offsets

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26390]
Right now, [`Script.tokenPosTable`](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#script) includes the line and column numbers for token positions, but there's no information about the character offset of the token in the source file. Although line and column information is human-friendly, when working with code the character offset is often of paramount importance. It would be great if the service provided easy access to it, possible in the form of a `Script.tokenOffsets` list.

**Comment by turnidge** [comment]
I don't want to add a character offset table to the protocol, since it can be derived from the information already available.

For those reading this bug in the future, here is some pseudocode for deriving the character offset map from tokenToLine and tokenToColumn maps:

var offset = 0;
var lineOffset = {};
for (var i = 0; i < script.lines.length; i++) {
  lineOffset[i] = offset;
  offset += script.lines[i].length;    
}
for (var tokenPos in tokenToLine.keys) {
  tokenToOffset[tokenPos] =  lineOffset[tokenToLine[tokenPos] - 1] + tokenToColumn[tokenPos];
}
