### ISSUE TITLE
Returning a Future from an async function is underspecified.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26430]
The specification for `return` statements of an async function states:

> Let `S` be the runtime type of `o`. In checked mode:
> - If the body of `f` is marked `async` (9) it is a dynamic type error if `o` is not `null` (16.2) and `Future<S>` is not a subtype of the actual return type (19.8.1) of `f`.

That means that the function:

``` dart
Future<int> foo(int x) async {
   if (x == 0) return 0;
   return foo(x - 1);
}
```

should cause a dynamic type error in checked mode. The value returned is `foo(x-1)` which is a `Future` and `Future<Future>` is not a subtype of `Future<int>`.

This isn't actually implemented, and the future is allowed to be returned in both production and checked mode (and in strong mode because there is code using it).

It's convenient to be able to return a future from an async function without awaiting it explicitly. The implementations accept this because they are based on an underlying `Completer` and you can complete a completer with a future (it implicitly waits for the futures result and completes with that).

However, the specification does not specify what happens if you return a future from an async function. It just states that:

> If f is marked `async` (9), then a fresh instance (10.6.1) `o` implementing the
> built-in class `Future` is associated with the invocation and immediately returned
> to the caller. The body of `f` is scheduled for execution at some future time. The
> future `o` will complete when `f` terminates. The value used to complete `o` is the
> current return value (17.12), if it is defined, and the current exception (16.9)
> otherwise.

That doesn't actually say how you complete a future with a future value. The `Completer` class is the best example of what should happen (which is also what the implementations do), but that's hardly a specification.

There is a problem with doing things this way: You can return a `Future` containing an error from an `async` function and completely avoid a `try`/`catch` in the function. Example:

``` dart
Future safeFunction(computation()) async {
   try {
      return computation();
   } catch (e) {
      return null;
   }
}
```

This function appears to be completely safe an unable to complete with an error. However if computation returns a `Future` with an error, the `Future` returned by `safeFunction` will complete with the same error, to everybody's surprise.

I think the behavior should be changed, and the specification changed to actually specify the new behavior. 
Basically it should work as if all `return e;` statements in async functions were replaced by `return await e;`.
This ensures that an error from `e` (async or not) is raised inside the function where it can be caught. It also ensures that the type of the expression is always a non-Future type (at least as long as the future is well-behaved, system futures can't complete with a future). That means that the type check above is correct - if `await e` evaluates to `o` and `S` is the runtime type of `o`, then `Future<S>` must be assignable to the return type of the function. There is no need to add a flatten to this check (which would otherwise be needed in order to match the implemented behavior).
An implementation should be allowed to not actually wait if the expression `e` evaluates to a non-future (which may be detectable at compile time).

**Comment by zoechi** [comment]
Would this implicitly make the function `async`? Would this behave the same in Dartino with disabled async/await (I think it was Dartino where there was an option added to disable it)

**Comment by lrhn** [comment]
No, this is all about async functions. I just forgot to add the `async` to the example function (thanks for noticing :).

**Comment by lrhn** [comment]
Adding language because I actually want to solve this with a language change - to make `return expr;` do an implicit await.
It *will* change behavior (and require implementation change) because it means that the `catch` in the first example will catch the error from the `computation()` call. If there is no catch, implementations can just pass the future into `Completer.complete` like they currently do, and the result will be the same.

**Comment by eernstg** [comment]
I think it matters whether there are any plausible designs where `return e` returning a future from an `async` function is actually exactly what is intended. After all, you can do `return e` as well as `return await e`, and if both are plausible then we shouldn't decide up front that one of them will implicitly be "corrected" into the other one, thus making it hard for a developer to express the one that we have chosen to consider wrong (and potentially very confusing that it doesn't "just work").

For instance, you might want to directly pass on the exception, if any, from the `computation`, and there might be more code locally in `safeFunction` which may raise and catch "`safeFunction`s own" exceptions. Twisted, maybe, but not unthinkable.

Maybe the "wrongest" cases are the ones where there is a throw/catch which would catch an exception from `return await e`, but which is statically known to never catch anything with `return e` (except out of memory ;-). But it wouldn't be easy to single out those wrongest cases, and it would certainly be confusing if we add `await` in some cases and not in others.

Unfortunately, we can't just keep the current semantics and emit a hint/warning/whatever to point out constructs that are likely to be wrong: We don't have a mechanism in place for specifying that a certain "wrong" construct is actually what is intended, in a specific location.

So if we agree that the use cases are too twisted and nobody would use them unless by accident, we could do this. Otherwise it would be nice if we could instead nudge the developer to add that `await` that he/she probably meant in the first place, without drowning the occasional actual user in noise.

Another closely related issue is of course `computation()` used as a statement: The code is buggy because that statement should have been `await computation()` even though there is no (useful) return value, and when the `await` is missing things will happen in a different order than the intended one, causing various hard-to-debug problems.

So maybe we could deal with both issues at the same time, by inserting `await` or warning/hinting that it's missing, whenever there is an expression of type `Future<Something>` without an `await` in an async function?

**Comment by lrhn** [comment]
I actually think it's a problem that the error isn't thrown.
Take this example:
```dart
int foo(x) { ... }
int bar(x) {
  try {
    return foo(x); // Might fail, depending on x.
  } catch (e) {
    return 0;
  }
}
``` 
This is a perfectly good function. Now, something happens and `foo` has to be async, so we rewrite according to the usual rules
```dart
Future<int> foo(x) { ... }
Future<int> bar(x) async {
  try {
    return foo(x); // Might fail, depending on x.
  } catch (e) {
    return 0;
  }
}
``` 
We "forgot" to put an await on the `foo` call, because it's OK to return a future. Nobody warns us, the types are perfectly OK - but now `bar` can actually throw (return a throwing `Future`), completely contrary to what it was designed for. Whoops.

I actually would prefer if the future returned by `foo` was awaited in the `return` statement, and any errors raised there. 

I can see that we now have two possible behaviors, and I'm removing one of them, but If you really want to propagate the error, all you have to do is to not catch it. 
In most cases there are no catch clauses anyway, and the implementations can keep just completing with the future.

**Comment by eernstg** [comment]
Closing: As of today, the language specification already requires essentially the behavior which is requested by this issue:

> Basically it should work as if all `return e;` statements in async functions were
> replaced by `return await e;`.

```
First the expression $e$ is evaluated, producing an object $o$.
If the body of $f$ is marked \ASYNC{} (\ref{functions}) and the run-time type
of $o$ is a subtype of \code{Future<$flatten(S)$>}, then let $r$ be the result of
evaluating \code{await $v$} where $v$ is a fresh variable bound to $o$.
Otherwise let $r$ be $o$.
Then the return statement returns the value $r$ (\ref{completion}).
```

where `$S$` is the actual return type of the enclosing function. So `return` will _always_ await a future (except the ones that are required via the return type: if the return type is `Future<Future<int>>` and `$o$` is a `Future<int>` then we should use that future to complete the returned future, not await the `int` and then fail because we can't complete a returned `Future<Future<int>>` with an `int` value).
