### ISSUE TITLE
No warning and no dynamic error if malbounded type is used

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26444]
```dart
class A {}
typedef g<T extends A, U>(T t, U u);

void f(int i, int j) {}

main() {
  g foo = f; // no dynamic error in checked mode, no analyzer warning
}
```
Note that the first parameter of function f is int which doesn't extend A, so its type is malbounded
Tested on Dart VM version: 1.17.0-dev.2.0 (Tue May 03 12:11:17 2016) on "windows_x64"

According Dart specification (4th edition, December 2015) 

> 19.8 Parameterized Types parameterizedTypes
> ...
> Otherwise, let Ti be the type parameters of G and let Bi be the bound of
> Ti, i 2 1..n,. T is malbounded iff either Si is malbounded or Si is not a subtype
> of [S1, . . . , Sn/T1, . . . , Tn]Bi, i 2 1..n.
> Note, that, in checked mode, it is a dynamic type error if a malbounded type is
> used in a type test as specified in 19.2.
> Any use of a malbounded type gives rise to a static warning.
>

**Comment by lrhn** [comment]
I don't think it's wrong, even if it is annoying.
You might be assuming that the `T` type defaults to `A` if omitted, but that is not the case.

When you use `g` with no type parameters, the type parameters default to `dynamic`. That means that you are checking whether `f` has a type assignable to `(dynamic, dynamic)->dynamic`, which it does.

The check of the parameters require that `dynamic` is a subtype of `A`, which it also is (`dynamic` is both a sub-type and a super-type of everything because "A subtype of B" is defined as "A[bottom/dynamic] is more specific than B" and bottom is the least specific type and dynamic is the most specific type).

**Comment by floitschG** [comment]
As @lrhn stated. This is working as intended.

**Comment by zoechi** [comment]
A linter rule that checks for constraints in generic type parameters and requires them to be passed explicitely would be nice. Like http://dart-lang.github.io/linter/lints/always_specify_types.html but more focused than requiring types everywhere.

**Comment by jwren** [comment]
@pq for linter mention
@leafpetersen will strong mode save the day here?

**Comment by leafpetersen** [comment]
Yes, strong mode makes implicitly instantiated typedefs and generics instantiate to their bounds instead of to `dynamic`.
