### ISSUE TITLE
NSME in ErrorVerifier._checkForMissingRequiredParam.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26440]
When trying to repro issues with `@required` (https://github.com/flutter/flutter/issues/3843), I was greeted with this (using Adam's patch).

```
NoSuchMethodError: method not found: 'getField'
Receiver: null
Arguments: ["reason"]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ErrorVerifier._checkForMissingRequiredParam (package:analyzer/src/generated/error_verifier.dart:4260)
#3      ErrorVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/error_verifier.dart:832)
#4      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6127)
#5      ConditionalExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2557)
#6      RecursiveAstVisitor.visitConditionalExpression (package:analyzer/dart/ast/visitor.dart:1455)
#7      ErrorVerifier.visitConditionalExpression (package:analyzer/src/generated/error_verifier.dart:543)
#8      ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2551)
#9      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7396)
#10     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1749)
#11     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7391)
```

**Comment by pq** [comment]
It looks like in this case the constantValue for the `@required` annotation is `null`. In `error_verifier`:

```
ElementAnnotationImpl annotation = _getRequiredAnnotation(param);
...
DartObject constantValue = annotation.constantValue;
String reason = constantValue.getField('reason')?.toStringValue();
```

Easy to guard against but before I do, I'd be curious why this is happening (and only sometimes).

@scheglov @bwilkerson : thoughts?

**Comment by bwilkerson** [comment]
Is the `param` from a different library than the one being verified?

If so, then this is a well known issue. The short story is that we evaluate constants in two cases: (1) when producing a fully resolved AST in a library all of the constants in that library will have had values computed for them, and (2) if the value is needed in order to compute the value of another constant required for the first reason.

As a result, if you're accessing the value of a constant outside the current library you have to first ensure that the library containing the constant has been fully resolved. However, requiring that as part of the task model will have some negative implications for performance, so we should talk about how best to accomplish this.

**Comment by pq** [comment]
Thanks Brian.  You're spot-on that this param is defined in a separate library (`flutter`).  Unfortunately this is by far the common case and compromises the value of the "details" field in `@required`.

We should talk about approaches but in the short term I'll add a guard unless you have other thoughts.

Aside: in this specific case will the value be in the summary when we summarize the flutter library?

**Comment by bwilkerson** [comment]
> ... in the short term I'll add a guard ...

Sounds good to me.

> ... will the value be in the summary ...

I think the current answer is "no", summaries don't contain constant values, but do have everything necessary to evaluate them.

**Comment by pq** [comment]
> I think the current answer is "no", summaries don't contain constant values, but do have everything necessary to evaluate them.

I'm thick.  (Or didn't ask the right question 😄 .)  Does this mean summaries will help here or not?

**Comment by bwilkerson** [comment]
No, they won't help.

**Comment by pq** [comment]
😞 

I keep imagining that summaries will come barreling over the horizon to solve ALL of our problems!  Ah well.  In that case, yes, let's talk about how to get this fixed or remove the "details" param from `@required`.

**Comment by bwilkerson** [comment]
Yeah, summaries are not a silver bullet.

The heart of the issue here is that we need to do as little work as necessary to get the results we need, but this is a case where we need more work to be done than previously. If we can do the work lazily then we'll can still minimize the amount of work we have to do. If not, then we end up doing the work in case we need it, which we won't most of the time.

**Comment by pq** [comment]
Guard landed in https://github.com/dart-lang/sdk/commit/63b7b6f3c2524435a5d24776ef36ad5e32a776c9.

Bumping over to you @bwilkerson to update once you've got the new API we discussed in place.

Thanks!

**Comment by bwilkerson** [comment]
That API was added in https://codereview.chromium.org/1966323002/, but has not yet been published.

**Comment by pq** [comment]
Fixed as of https://github.com/dart-lang/sdk/commit/23b02bc35112ebb955e006b87b3fbe03c5e071d7; tested w/ https://github.com/dart-lang/sdk/commit/e1fad5cddbbf23cf3c6c4592d76e0654171f0f3a.

We should be good to go for the next DEV release. 👍 

cc: @abarth
