### ISSUE TITLE
handleUncaughtError called twice if Future has two listeners

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26447]
If you have a Future with two listeners that completes with an error inside a Zone with a handleUncaughtError handler, the handler gets called twice.

```dart
import 'dart:async';

Future<Null> test() async {
  throw 'error';
}

void main() {
  Zone zone = Zone.current.fork(
    specification: new ZoneSpecification(
      handleUncaughtError: (Zone self, ZoneDelegate parent, Zone zone, dynamic error, StackTrace stackTrace) {
        print('handleUncaughtError called');
      }
    )
  );
  zone.run(() {
    Future<Null> f = test();
    f.whenComplete(() { });
    f.whenComplete(() { });
  });
}
```

**Comment by Hixie** [comment]
@iposva-google suggested that I should cc @floitschG on this.

**Comment by lrhn** [comment]
Yes. That's working as intended.

When you have two listeners on a future, you create two new futures which are completed with the result of the listener. That means that the  error effectively gets split into two independent errors in two separate futures. So you have to catch both to avoid having an uncaught error, and that's also why you get two uncaught errors if you don't catch either of them. You still only get one error *per future* that completes with an error without having any listeners (at the time of the completion - adding one later doesn't go back and prevent the error from being uncaught, which is why you should add listeners soon after creating the future).

Write your code as:
```dart
Future<Null> f = test();
Future f1 = f.whenComplete((){});
Future f2 = f.whenComplete((){});
```
and it might be easier to see why that both `f1` and `f2` complete with unhandled errors. If you rewrite as:
```dart
Future<Null> f = test();
Future f1 = f.whenComplete((){});
Future f2 = f1.whenComplete((){});  // <-- chainining instead of parallelizing.
```
then you only have one unhandled error.

In general, it's a good idea to only have one listener on a future, if at all possible. Makes everything so much simpler. If you use async/await syntax, that very easily becomes the default way of writing things - awaiting the same future twice really stands out as silly since you can just bind the result to a variable the first time.

**Comment by Hixie** [comment]
The unhandled error is in f, not in f1 or f2. Having it reported twice just leads to bad output when I print the error in the unhandled error handler. I don't have any control over how many handlers the chain of futures has -- it could easily be dozens. That's all in user code.

What should I do instead? Cache pointers to all the reported exceptions and only report them if I haven't seen them before?

Is there some way to mark the error as "handled" for all branches?

(This bug is visible e.g. in the test harness. The test harness dumps the exception from an uncaught error handler on the zone for the test. If the test is async and the returned future is part of a tree of future handling, it can easily end up dumping the same error multiple times.)

**Comment by lrhn** [comment]
The unhandled error is most certainly in both `f1` and `f2`. You can see that if you later add a `catch` handler to either `f1` or `f2`, that catch handler will see the error. Example:

```dart
import "dart:async";
main() {
  runZoned(() async {
    var f = new Future.error("BAD");
    var f1 = f.whenComplete(() {});
    await new Future.delayed(const Duration(seconds: 2), (){});
    var f2 = f.whenComplete(() {});
    await new Future.delayed(const Duration(seconds: 2), (){});
    f1.catchError((e) { print("f1: $e"); });
    f2.catchError((e) { print("f2: $e"); });
  }, onError: (e) {
    print("Zone uncaught: $e");
  });
}
```

**Comment by Hixie** [comment]
I guess I'll make my exception handler catch all the exceptions and compare them before reporting them. Thanks for the explanation.
