### ISSUE TITLE
async doWhile stops iteration when f returns non-Future

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#26462]
According to https://api.dartlang.org/stable/1.16.0/dart-async/Future/doWhile.html 

"Future doWhile(dynamic f())
. . .
The function f may return either a bool or a Future that completes to a bool. If it returns a non-Future, iteration continues immediately. "

However, if f returns a non-Future (new Object() in the test below), iteration stops.

```dart
import "dart:async";

const N = 5;

main() {
  int num = 0;

  Future f() {
    print("-- $num");
    if (num == 2) {
      num++;
      return new Object();
    }
    Completer c = new Completer();
    if (num < N) {
      num++;
      c.complete(true);
      return c.future;
    } else {
      c.complete(false);
      return c.future;
    }
  }

  Future future = Future.doWhile(f);

  future.then((fValue) {
    print("num $num");
  })
  .catchError((e) {
    print("catchError: $e");
  });
}
```
dart test.dart 
-- 0
-- 1
-- 2
num 3

Tested on Dart VM version: 1.17.0-dev.3.0 (Wed May 11 01:53:34 2016) on "linux_x64"

**Comment by lrhn** [comment]
The documentation says that it must return either a `bool` or a `Future` evaluating to a `bool`. You return a value that is neither, and the result is a type error in checked mode. The error isn't visible in production mode, but it still stops execution because `new Object()` is considered false in a boolean test.

More precisely: In checked mode it fails because `Object` isn't assignable to `Future` - you return `new Object()` from a function `f` declared to return `Future`. If you change the return type of `f` to allow `Object`, you get a type error later where `Object` isn't `bool` in a test. That test becomes false in production mode which is what stops your iteration.

**Comment by ngolovleva** [comment]
Thank you for clarification.
However, it is not clear, what phrase 'If it returns a non-Future, iteration continues immediately.' from the specification means? If all returned non-Future (except true and false) are treated as false (or may be not all?), this means, that iteration should stop (as false was returned), not continue.
May be it makes sense to clarify the specification?

**Comment by lrhn** [comment]
Yes, that is more confusing than necessary. It says "Must return bool or future. If it returns a non-future ...", and the last part should just be "If it returns a bool ...", there is no reason to use the negative, and "iteration continues immediately" forgets to mention that this is only if it wasn't stopped by returning false.

So it could definitely use a rewording.

**Comment by lrhn** [comment]
Documentation has now been improved.
