### ISSUE TITLE
Analyzer doesn't catch async functions that are assigned to typedefs that don't return Future

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26474]
This doesn't have any warnings or lints:

``` dart
/// Notice how this returns void, not Future<Null> or dynamic.
typedef void Test();

void main() {
  Test t = () async { }; // this closure returns a Future, but there's no error here
  dynamic r = t() as dynamic;
  print(r.runtimeType); // prints "_Future"
}
```

**Comment by leafpetersen** [comment]
Even in strong mode a function returning anything can be used where a function returning void is expected (the idea being that ignoring the return value is always ok in Dart since the calling conventions are the same).  Is this something you would want to forbid entirely? Or just for async/Future returning functions?  Note that because functions with no return type get typed as returning `dynamic`, it gets pretty annoying to not allow this - we initially didn't allow this in strong mode and found that we were getting lots of extra errors that didn't seem to add value.

**Comment by Hixie** [comment]
The case we particularly were worried about was this one: https://github.com/flutter/flutter/pull/3992/files

We saw people doing:

```dart
   setState(() async {
     // ...
   });
```

...which is actually equivalent to:

```dart
   setState(() { });
   // ...
```

This is a problem in any case where you have a function that expects to invoke a synchronous callback and do something before and after.

So to answer your question, I think it's mostly about functions that are marked "async".

**Comment by lrhn** [comment]
Arguably, it's a code smell to ignore the return value from an async function. Ignoring a `Future` means that any error it might report will be uncaught and may crash your program.

It's not *that* simple, though. If you know an async function can't fail, and you don't need to wait for it, ignoring the future is the right thing to do. You need to ignore at least one future in every async program (if nothing else, the return from `main`). Also, an error being uncaught might be deliberate because it's being caught by a zone. There are plenty of cases where ignoring a `Future` is correct, so it's hard to make a heuristic for when to warn.

I've occasionally done `() async { something(...); }();` as a "shorthand" for `scheduleMicrotask(() { something(...); });`.

**Comment by Hixie** [comment]
FWIW, the assertion added in https://github.com/flutter/flutter/pull/3992 yesterday (which wouldn't be necessary if the analyzer caught such things) has already caught a bug for one of our customers. So while I agree that this isn't an easy case to reason about, I think there is real value in having the analyzer do something along these lines.

**Comment by leafpetersen** [comment]
Would you also want a warning for other places where a Future is ignored?

```dart
void test() {
  // warn here?
  doSomethingReturningFuture(...);
}
```

**Comment by Hixie** [comment]
In our test framework we go out of our way to catch cases where people aren't awaiting the API:
https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/test_async_utils.dart

I'm not sure that the analyzer can really catch such misuse reliably though. The code above also handles someone catching the future but not waiting for it to complete before calling the next future-returning function.

So to answer your question, "probably not".

**Comment by ochafik** [comment]
Note: general case of statically detecting unawaited futures is tracked at https://github.com/dart-lang/sdk/issues/24171

**Comment by natebosch** [comment]
We don't have any plans to make `Future Function()` _not_ a subtype of `void Function()` so I don't think there are any more actions to take on this issue.
