### ISSUE TITLE
LinkedHashMap doesn't call isValidKey for operator[]

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26491]
According the documentation (https://api.dartlang.org/stable/1.16.0/dart-collection/LinkedHashMap/LinkedHashMap.html)

> LinkedHashMap({bool equals(K key1, K key2), int hashCode(K key), bool isValidKey(potentialKey)})
> Creates an insertion-ordered hash-table based Map.
> ...
> If using methods like operator[], remove and containsKey together with a custom equality and hashcode, an extra isValidKey function can be supplied. This function is called before calling equals or hashCode with an argument that may not be a K instance, and if the call returns false, the key is assumed to not be in the set. The isValidKey function defaults to just testing if the object is a K instance.

But in fact `isValidKey` is called if `remove` and `containsKey` are used but is not called if `operator[]` is used. Proof:

```dart
bool myEquals(int key1, int key2) {
  print("myEquals: " + key1.toString() + ", " + key2.toString());
  return key1 == key2;
}
int myHashCode(int key) {
  print("myHashCode: " + key.toString());
  return key.hashCode;
}
bool isValidKey(var potentialKey) {
  print("isValidKey: " + potentialKey.toString());
  return potentialKey is int;
}

  main() {
    LinkedHashMap map = new LinkedHashMap(equals: myEquals, hashCode: myHashCode, isValidKey: isValidKey);
    print("start []");
    map[1] = 11;
    print("-------------");

    print("start []");
    map[1] = 12;
    print("-------------");

    print("start remove()");
    map.remove(1);
    print("-------------");

    print("start containsKey()");
    map.containsKey(1);
    print("-------------");

    print("start []");
    map[1] = 2;
    print("-------------");

    print("start containsKey()");
    map.containsKey(1);
    print("-------------");
}
```
The programm above produces the following output:
```
start []
myHashCode: 1
-------------
start []
myHashCode: 1
myEquals: 1, 1
-------------
start remove()
isValidKey: 1
myHashCode: 1
myEquals: 1, 1
-------------
start containsKey()
isValidKey: 1
myHashCode: 1
-------------
start []
myHashCode: 1
-------------
start containsKey()
isValidKey: 1
myHashCode: 1
myEquals: 1, 1
-------------
```
As you can see `isValidKey` is not called for `operator[] `

**Comment by lrhn** [comment]
You are not actually calling the `[]` operator. The code does `map[1] = 2;` which calls the `[]=` operator instead, and that operator does not use the `isValidKey` check. 

The `isValidKey` is intended to be used when the custom `equals` and `hashCode` functions are not defined for all `Object` instances. 
The `operator[]`, `remove` and `containsKey` methods take `Object key` as argument, not `K key`, so to make the methods safe, you must either support `Object` in `equals`/`hashCode` or filter non-`K` keys out using the `isValidKey` test. 
The `[]=` operator does not have that problem since its key is typed as `K`, so it doesn't use the `isValidKey` function.
