### ISSUE TITLE
Anonymous function with missing return value

### ISSUE THREAD

**Issue by pinnisi** [dart-lang/sdk#26554]
Having the following code:

``` dart
typedef bool FCallback(int);

class Test {
  FCallback callback;
  Test(this.callback);
}

void main() {
  new Test((int n) {
  });
}
```

if I forget to return a value from inline function no warning or error is shown, even in strong mode.

example: https://dartpad.dartlang.org/eaf2a561957c06546c5e2cdce933aa16

**Comment by lrhn** [comment]
I can't speak for strong mode, but this is the correct behavior according to the Dart specification.

Your test constructor's parameter has the function type `int->bool`.
You are calling it with a function with a static type of `int->dynamic`.

The static type analysis can't see any problem with that. The type parameter matches, and the return type is `dynamic` which overrides all type checks. Statically, your program is perfect.

Now, you have a function of type `int->dynamic` with no explicit `return` statement. Again, that's not something the spec warns about. The analyzer would warn you if you had a function returning `bool` and no return statement, but it won't warn you when the return type is `dynamic` - that might mean `void`.

So, the problem is that you can't specify a return type for a function expression (at least not without using a `=>` body), and the implicit `dynamic` return type turns off the warnings you are looking for.


Would strong mode type inference be able to assign a return type to the function expression?

**Comment by pinnisi** [comment]
With strong mode enabled if I put

**return "a string"**

in inline function I have the following warning
**The return type 'String' is not a 'bool', as defined by the method ''.**
so I think it will be better to show a warning even with missing return

**Comment by leafpetersen** [comment]
Yes, strong mode will infer a type here.  My guess is that since standard Dart provides no way to give a return type for a closure, there is no check for missing returns in them.  It seems reasonable to me that strong mode should give a warning or error here.

**Comment by lrhn** [comment]
(Dart 1.0 does assign a return type to function expressions on the form `(...) => expr` - the return type is the static type of `expr` - but the return type of a function expression with block body `{ ... }` is always dynamic.)

**Comment by eseidelGoogle** [comment]
We got a report from Stack Overflow of a Flutter user confused by this.  See #28018 for details.

**Comment by eseidelGoogle** [comment]
We had another flutter user report confusion about this: https://github.com/flutter/flutter/issues/7956

Also https://github.com/dart-lang/sdk/issues/28233 may be related to this (or a dupe)?

**Comment by leafpetersen** [comment]
Agreed that this should be handled in strong mode.  Closing as a duplicate in favor of https://github.com/dart-lang/sdk/issues/28233 , let me know if there are additional issues here.

**Comment by ollydixon** [comment]
I'm seeing this issue in Flutter 2.0 with voids. I can't return early (good princicles of clean coding)

For example:

<img width="623" alt="Screenshot 2021-03-04 at 12 02 55" src="https://user-images.githubusercontent.com/6940726/109954374-8ec9ae80-7ce1-11eb-868b-5ce8bbf8e220.png">

**Comment by eernstg** [comment]
Could you add some more detail, e.g., a snippet of code that shows the problem in [dart-pad](https://dartpad.dev/?null_safety=true)?

**Comment by lrhn** [comment]
The function appears to have a return-type other than `void`. In that case you need to write an expression after the `return`. 
Try writing `return null;`. If that doesn't work, it will most likely tell you which type you need to return instead.

**Comment by ollydixon** [comment]
@iarkh my bad, it was a library that was return Future<void> and not void.
