### ISSUE TITLE
VM crash in co19/src/Language/Statements/Continue/async_loops_t10.dart 

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#26577]
test4 results in seg fault.
test5 and test6 fail the listEquals check.

**Comment by mhausner** [comment]
test4() crashes because the VM has a bug in finally-block inlining with unresolved forward references of switch case labels.

The jump target of the 'continue L' statement is unresolved when parsed. The VM assumes it's a forward reference within the same switch statement, and thus does not inline the enclosing finally blocks. However, the forward reference is to a switch case outside the finally blocks (implicitly defined by await-for). When the jump is finally resolved, the VM doesn't inline the finally blocks as it should.

**Comment by mhausner** [comment]
CL https://codereview.chromium.org/2030763002/ fixes this. The implicit finally clauses of the await-for statements were not inlined in front of the forward jump to the outer switch statement.

**Comment by mhausner** [comment]
Fixed in 1859ce46c337e4e047e6543c561ff77af7910074
