### ISSUE TITLE
Please merge fba5cbc to DEV.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26572]
@whesse @mit-mit @kasperl

Please merge https://github.com/dart-lang/sdk/commit/fba5cbc425e54b015d9ffefac4e0789d5502846c to STABLE.  This change fixes a breakage (tracked in https://github.com/dart-lang/sdk/issues/26562) in `dartdoc`.

Thanks!

**Comment by mit-mit** [comment]
@pq, this is merge to 1.17 dev (to become 1.17 stable later this week), right?

**Comment by pq** [comment]
Yes, exactly right.  Sorry for any confusion @mit-mit!

**Comment by whesse** [comment]
This CL changes the version number of analyzer from 0.27.4-alpha.8 to 0.27.4-alpha.9.  But stable is at 0.27.4-alpha.7, so this will create a new version of analyzer that is not identical to any that already has a number.  Should it be 0.27.4-alpha.7.1? Are we sure that applying the patch without the changes to -alpha.8 is correct?

The pubspec.yaml and CHANGELOG don't merge because of this.

**Comment by mit-mit** [comment]
Looks like this was merged in https://github.com/dart-lang/sdk/commit/5eae061da7c499696c72e288a425092602115798. @whesse we can close this, right?

**Comment by pq** [comment]
Looks good from my perspective.

**Comment by whesse** [comment]
Merged in 1.17.0-dev.6.1.
