### ISSUE TITLE
Analyzer doesn't infer type from "is" check against abstract class

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#26576]
Analyzer doesn't infer type from `is` check against abstract class if variable was annotated with explicit type.
https://dartpad.dartlang.org/c6d0fee76a4986d8be05e1288d288e1c

**Comment by bwilkerson** [comment]
It doesn't actually have anything to do with the fact that `I` is an abstract class, it has to do with the way type promotion is defined in the spec (section 16.34):

> Let _v_ be a local variable or a formal parameter. An is-expression of the form _v_ <b>is</b> _T_ shows that _v_ has type _T_ iff _T_ is more specific than the type _S_ of the expression _v_ and both _T_ != <b>dynamic</b> and _S_ != <b>dynamic</b>.

But `I` is not more specific than `A` (as defined in section 19.4). Hence, we cannot promote the type here and this is working as expected.

**Comment by lexaknyazev** [comment]
So why in the code snippet above `a1 is I` evaluates to `true`, if `I` is not more specific than `A`?

**Comment by bwilkerson** [comment]
Because of the difference between analysis-time (equivalent to compile-time) and run-time semantics. When we're performing a static analysis of the code we don't try to do full flow analysis. You told us that `a1` could be any kind of `A` and we don't try to figure out that it will always be a `B` at this point in the code. But at run time the VM knows that the value of `a1` it's an instance of `B` and hence also an instance of `I`.

**Comment by lexaknyazev** [comment]
Thanks. Is it a correct way to suppress such analyzer warnings?
```dart
 if (a1 is I) (a1 as Object/*=I*/).foo();
```

**Comment by bwilkerson** [comment]
Nope. Try putting that into DartPad; you'll see two errors rather than one.

There are three ways to disable the warning. The best is to add an explicit cast to the tested for type:

```
if (a1 is I) (a1 as I).foo();
```

The other two involve telling analyzer not to type check your code (which I don't recommend). One is to replace the line with the warning with:

```
if (a1 is I) (a1 as dynamic).foo();
```

The other is to change the declaration to:

```
var a1 = new B();
```

**Comment by lexaknyazev** [comment]
> Try putting that into DartPad; you'll see two errors rather than one.

DartPad and IntelliJ don't give any errors with strong mode enabled. Ctrl-click on `foo()` in IntelliJ navigates correctly to `I.foo()`.

**Comment by bwilkerson** [comment]
Correct. That's because, with strong mode enabled, the code is effectively rewritten to

```
if (a1 is I) (a1 as I).foo();
```

Without strong mode the content of the comment is ignored. But there's no reason to make the code valid only when strong mode is enabled :-)
