### ISSUE TITLE
isValidKey is not called before compare call in different Map constructors

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26575]
See https://api.dartlang.org/stable/1.16.0/dart-collection/LinkedHashMap/LinkedHashMap.html or https://api.dartlang.org/stable/1.16.0/dart-collection/SplayTreeMap-class.html. The idea of isValidKey is to call it before custom hashCode, equal or compare functions. But constructors and []= operators called these functions without isValidKey call. For example:
```dart
import "dart:collection";

bool myEquals(int key1, int key2) {
  print("Equal called");
  return key1 == key2;
}

int myHashCode(int key) {
  print("myHashCode called");
  return key.hashCode;
}

bool isValidKey(var potentialKey) {
  print("isValidKey called");
  return potentialKey is int;
}

main() {
  LinkedHashMap map = new LinkedHashMap(equals: myEquals, hashCode: myHashCode,
      isValidKey: isValidKey);

  map[1] = 11;
  map[101] = 11
  map[2] = 11;
  map[3] = 12;
}
```
This programm produces the following output:
```
myHashCode called
myHashCode called
myHashCode called
myHashCode called
```
myHashCode is called without isValidKey call. So if potential key has wrong type exception will be thrown.
Another example:

```dart
import "dart:collection";

class C {
  int value;
  C(this.value);
}

int compare(C key1, C key2) {
  print("Compare called");
  return key1.value - key2.value;
}

bool isValidKey(var potentialKey) {
  print("isValidKey called");
  return potentialKey is C;
}

  main() {
    C c1 = new C(1);
    C c2 = new C(2);
    C c3 = new C(3);

    Iterable source = [c1, c2, c3];
    SplayTreeMap map1 = new SplayTreeMap.fromIterable(source, compare: compare,
        isValidKey: isValidKey);

    SplayTreeMap map2 = new SplayTreeMap(compare, isValidKey);
    map2[c1] = 1;
    map2[c2] = 2;
    map2[c3] = 3;

    SplayTreeMap map3 = new SplayTreeMap.from({c1: 1, c2: 2, c3: 3}, compare, isValidKey);
  }
```
Output is
```
Compare called
Compare called
Compare called
Compare called
Compare called
Compare called
```
Again, compare function is called without isValidKey call and wrong key will break the programm

**Comment by floitschG** [comment]
Probably related to #26498

**Comment by lrhn** [comment]
The idea if `isValidKey` is to call it on objects passed to `containsKey, `remove` and `operator[]`, not any other method. Those three methods are special in that their argument type is `Object`, not `K`. The `isValidKey` is there to allow you to use equality and hash-code computations that only work for `K` instances. That allows you to use a `Map<SubClass, X>` as a readable `Map<SuperClass, X>` without breaking. The equality and hash-code computations must still work for all `K` instances, and since `operator[]=` takes an argument of type `K` (and can't be allowed to work with a superclass instance anyway), there is no need to call `isValidKey`.

Having `isValidKey` might have been a mistake. It solves a particular problem, but it's not necessarily a problem that is hard to solve without it, and the extra complexity of worrying about `isValidKey` is worse than the problem of requiring equality and hash-code to just work on all objects.

**Comment by sgrekhov** [comment]
Ok. But I think the current implementation is bad anyway. It allows to put element to collection without ability to remove it from there.
```dart
import "dart:collection";

class C {
  int value;
  C(this.value);
}

int compare(C key1, C key2) {
  return key1.value - key2.value;
}

bool isValidKey(C potentialKey) => potentialKey.value != 3;

main() {
  C c1 = new C(1);
  C c2 = new C(2);
  C c3 = new C(3);

  Iterable source = [c1, c2, c3];
  SplayTreeMap map = new SplayTreeMap.fromIterable(source, compare: compare,
      isValidKey: isValidKey);

  print(map.length); //3
  print(map[c3]); // null
  print(map.containsKey(c3)); // false
  print(map.remove(c3)); // null
}
```
Element c3 is in the collection but cannot be read or deleted!!! If isValidKey is called on every operation of adding elements to collection that allows to avoid cases like the above

**Comment by sgrekhov** [comment]
There are more harm than good from isValidKey in the current implementation
