### ISSUE TITLE
Analyzer: Allow trailing commas in parameter and argument lists.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#26647]
This is the analyzer-specific issue for #26644. That issue has the details.

- [x] parser (https://github.com/dart-lang/sdk/commit/aea4632375d9cbedff2b3ce87dd8b46b1e2645be)
- [x] code completion
- [x] flip the bit (option on by default)

**Comment by bwilkerson** [comment]
@jwren @danrubel Note that this will impact code completion because it will no longer make sense to recover from the non-error, which means that there won't be a synthetic identifier added after the trailing comma.

**Comment by lrhn** [comment]
It might be a clue if there is a space after a comma, instead of a newline or end-paren/brace, that the user wants completion on that line. I don't know if you want to be that speculative.

**Comment by bwilkerson** [comment]
There are two parts to the question. The first is whether editors should request code completion when the user types a comma. I'm guessing that the answer is 'yes' because it will probably be far more common to type an argument value after the comma than not.

The second is how we decide what suggestions to make when completion is requested. In the current system we recover from the error of having an extra comma by inserting a synthetic zero-width identifier, which is what we use when computing completions. Now that the "extra" comma is no longer an error we'll need to use something else (the comma itself, perhaps) when deciding what completions to suggest.

**Comment by pq** [comment]
Parser support is implemented behind the parser `parseTrailingCommas` flag as of https://github.com/dart-lang/sdk/commit/aea4632375d9cbedff2b3ce87dd8b46b1e2645be.

**Comment by danrubel** [comment]
Code completion has been updated as of https://github.com/dart-lang/sdk/commit/37a6f6256680d2f7e948a43d7da82baaabf45d65

**Comment by sethladd** [comment]
Is there a flag to enable this support?

**Comment by pq** [comment]
I *thought* the option had been turned on by default in one of @danrubel's CLs but now I see that's not the case.   Re-opening while I look a little closer.

**Comment by pq** [comment]
Bit-flip up for review: https://codereview.chromium.org/2185873002/
