### ISSUE TITLE
sdk/tools/testing/dart/test_runner.dart imports unexisting library

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26666]
Please remove the line

`import 'package:yaml/yaml.dart';`

from file sdk/tools/testing/dart/test_runner.dart

There are no this library and the file became broken because of it

**Comment by whesse** [comment]
There is no area-test.  Marking area-infrastructure.

The change https://codereview.chromium.org/2019163002 made the test infrastructure depend on packages, where it didn't depend on packages before.

I think this should be reverted, by taking the needed code from the yaml package, and copying it into the tools/testing/dart directory.

The test scripts cannot be run now in a checkout of Dart, unless build has been run, because only the build step creates the links to packages that form the default package root.  If there is any way to undo this additional dependency, including by reverting this change, I think we should do it.  It is an important property that the test scripts are completely self-contained, and do not depend on any code outside themselves and the built-in dart: libraries.

A workaround for this problem is to run gclient sync, gclient runhooks, and then build.py -mrelease runtime in the checkout you want to run tests in.  But we have plenty of places where we only check out the repo on the bots, and don't run build, and want to run tests, so this workaround is not enough.

**Comment by sigmundch** [comment]
_My apologies for my slow response, I just returned from a long leave_

@whesse - I don't think we need to revert the change or copy the code. As part of the change I added a [.packages][https://github.com/dart-lang/sdk/blob/f4b1d502f3fa771f1e87a136d5c79dcd3cc3d63a/tools/.packages] file specifically for this reason: so that the runner can work without having to do any build steps.

@sgrekhov - how are you executing this script? Technically the vm should automatically find the .packages file, but if it didn't, you can provide it and point it at `sdk/tools/.packages`. The only  extra requirement is that you need to check out the Dart SDK using the gclient tools so that files under third_party/pkg/ are downloaded automatically. If you are using this code in a different way, you'd need to install the packages listed in that .packages file and update the paths in the file to find them in the correct location of your system.

**Comment by sgrekhov** [comment]
@sigmundch I just run co19_tests.dart in command line and it runs test_runner somehow

**Comment by whesse** [comment]
co19_tests.dart is just a helper script, to run the co19 tests in many configurations, and print a report.  I ususally comment out blocks of it, when running, to test one component at a time.  The package root needed by test.py is set up when dart is built, not when the repo is checked out, so you need to do a gclient sync, gclient runhooks, and tools/build.py with the same modes and architectures that the co19_tests.dart uses, which is -mrelease,debug --arch=ia32,x64.

Feel free to add the new configurations to the co19_tests.dart script - it should not be relied on as a comprehensive set, just as a script to help us in updating the status files.


The issue about removing the package dependencies is still valid, I think, in that we really really want the testing scripts not to depend on more features of dart than they absolutely need to.  I will be working on a .package file for the whole checkout, so that the built package_root with the links can be removed.  That should be able to replace this, but I was still intending to create this file when building dart, not check it in.  So this won't help the bots that don't run a build step, like the cross-compiled target bots.

**Comment by whesse** [comment]
This issue is now obsolete, since all tools and scripts in the checkout should use the /.packages file that is checked into the sdk repo.  Since this is solid and stable, it is now ok for test.dart to use packages, when necessary.
