### ISSUE TITLE
String split returns strange List result.

### ISSUE THREAD

**Issue by iburton** [dart-lang/sdk#26679]
SDK Version: 1.17.0 (and whatever Dartpad is currently running)
Can be reproduced, see: https://dartpad.dartlang.org/5178537f6461ab790885e40973219a45

When executing 
"".split(" ") returns what appears to be an empty list upon inspection, however when asking for the length of the list (or calling isEmpty or isNotEmpty), we get an unexpected result that indicates there is one member.

**Comment by rakudrama** [comment]
This is working as designed.
Both `[]` and `[""]` will print as  `[]` since the printing does not quote the string.
See https://github.com/dart-lang/sdk/issues/26388

This *is* confusing. We would not want to add quotes when printing a top-level string but perhaps we should add quotes (and escape special characters) when the string is within a List or Map.

Note that printing is not the same as viewing a value in the debugger. If you want printing to produce 'pretty' values then perhaps you should use a library that does that. Real applications usually generate generate strings via a process of internationalization and localization and don't usually rely on the toString() of some value.
