### ISSUE TITLE
KeyboardEvent.key is always null

### ISSUE THREAD

**Issue by dskloetg** [dart-lang/sdk#26699]
According to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode `charCode` and `keyCode` are deprecated and `KeyboardEvent.key` should be used instead. But in Dartium `KeyboardEvent.key` seems to be always `null`.

**Comment by zoechi** [comment]
See also #26354

**Comment by alan-knight** [comment]
Keyboard events are a mess of things that are deprecated and things that don't work. Dartium is just passing through the getter to the underlying JS object. If it's null in Dartium, but not null in Chrome, then that's an issue. Though it might just be an issue that's been fixed in between the Chromium version Dartium is based on and the latest.

**Comment by alan-knight** [comment]
And it looks like that, since the MDN page for key indicates Chrome support starts in version 51.

**Comment by jacob314** [comment]
This issue shouldn't be closed until dartium is upgraded to version 51 or a polyfill is added for the missing functionality.

**Comment by terrylucas** [comment]
Closed some rework (Dartium 50 Dart 1.24.2 Stable) and Chromium 50 has deprecated some as well.
