### ISSUE TITLE
Analyser reporting unsound typecast when using yield*

### ISSUE THREAD

**Issue by derfurth** [dart-lang/sdk#26708]
Since 1.17 in strong mode the analyser reports an unsound typecast in the following code:
```
class Bar<E extends Bar> {
  final String name;
  final List<E> children = [];

  Bar(this.name);

  Iterable<E> searchAll(String name) sync* {
    for (var child in children) {
      if (child.name == name) yield child;
      yield* child.searchAll(name);
    }
  }
}
```
The analyser reports after yield*
```
 WARNING: Unsound implicit cast from Iterable<dynamic> to Iterable<E>
```

Is it an analyser issue or is the behavior expected? In 1.16 the analyser wasn't complaining.

**Comment by lrhn** [comment]
I'm guessing the return type of `child.searchAll` is `Iterable<dynamic>`?

**Comment by derfurth** [comment]
Yes in 1.17 it is 
```
Signature: Bar.searchAll(String name) → Iterable<dynamic>
Static type: (String) → Iterable<dynamic>
```

while in 1.16
```
Signature: Bar.searchAll(String name) → Iterable<Bar<dynamic>>
Static type: (String) → Iterable<Bar<dynamic>>
```

**Comment by lrhn** [comment]
I'm not a strong mode expert, but I think it makes some kind of sense.
Inside `searchAll`, all you know is that `E` is `Bar<dynamic>`, so `child.searchAll` is expected to return an `Iterable<dynamic>` which is not assignable to `Iterable<E>` ... because strong-mode!

Can you change the declaration of `Bar` to `class Bar<E extends Bar<E>>`?

It makes it pretty much impossible to instantiate `Bar` itself, but you can create a subclass like `class Baz extends Bar<Baz>{ Baz(String s) ; super(s); }` and instantiate that with `E` everywhere being `Baz`.

**Comment by derfurth** [comment]
Yes, `class Bar<E extends Bar<E>>` fixes it! And since in my code Bar was abstract it's fine :)
