### ISSUE TITLE
Allow users to force methods not to be inlined

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26705]
Sometimes it's important that a method not be inlined. Right now there are various hacky ways to do it, like adding multiple returns or `if (false) throw ""`, but these are gross and may stop working at any time. It would be great if there were a more explicit way to control this.

The SDK's private `extend` package has a [`@NoInline`](https://github.com/dart-lang/sdk/blob/master/pkg/expect/lib/expect.dart#L399-L403) annotation which does this, but that's not accessible to external packages. Moving that annotation to the [`meta`](https://pub.dartlang.org/packages/meta) package would be great.

My use case for this comes from `test`. To solve dart-lang/test#420, I need to determine the source location where the `test()` method was called, which involves capturing a stack trace and using source maps to translate the JS frames into Dart frames. But when `test()` is inlined, none of those frames point to the user's `main()` method. The source maps indicate instead that the call to `test()` is in `package:test/test.dart` since that's where it was inlined from. If I can reliably prevent this inlining, I can ensure that the stack trace is always usable.

**Comment by hterkelsen** [comment]
I think we could move `@NoInline` from `expect` to `meta` without any issues. My only concern is that people will abuse this to _try_ to squeeze out some extra performance from `dart2js`, when in fact they will be hurting the performance of their app in the long term. I think we'll be OK though, as long we don't add the corresponding `@ForceInline`...

**Comment by rakudrama** [comment]
We should make @NoInline and @ForceInline available and document them.
It is much better that developers use these annotations rather than use tricks like `return; return;`.
The tricks will become broken, and we can experiment with ignoring the annotations to see if they are helpful or cargo-cult.

There is a second set of annotations in js_runtime. We should try to use the new annotations in place of these too.

Maybe we need better names, since we can't inline many functions. There is also the issue that we sometimes don't inline (or inline much more cautiously) due to the call site rather than the function.

We would also like to make a change to the sourcemap tracking and format so that the stack range from inlining is available (i.e. a location in the JS corresponds to a list of source locations). This would make the stack traces less confusing.

**Comment by nex3** [comment]
Maybe `@noInline` and `@tryInline`?

**Comment by matanlurey** [comment]
I'd honestly prefer the inlining algorithm was fixed - but I could see value in `@noInline` as an experimental feature until then.

**Comment by nex3** [comment]
@matanlurey What exactly needs to be fixed about it in order to make `@noInline` unnecessary?

**Comment by matanlurey** [comment]
@MichaelRFairhurst had a hacky experiment where he was able to reduce the size of our internal CRM application at Google by ~7% messing around with the current heuristic, so maybe he can share precise details: https://codereview.chromium.org/2994823002/.

We (the AngularDart team) specifically have seen three issues with inlining today (in dart2js):

* Inlining is based on the size of the resulting JS AST?

This makes sense _sometimes_, and other times does not. In particular, default arguments seem to trip up the current heuristic quite a bit. I've used @hterkelsen's little playground here (https://hterkelsen.github.io/dart2js_playground/):

```dart
void main(input) {
  print(doThing(b: input));
}

String doThing({
  a: '<A A A A A>', 
  b: '<B B B B B>', 
  c: '<C C C C C>',
}) => '$a$b$c';
```

... outputs ...

```js
P.print("<A A A A A>" + H.S(input) + "<C C C C C>");
```

That looks good! But what if we use `doThing` multiple times?

```dart
void main(input) {
  print(doThing(b: input));
  print(doThing(b: input));
  print(doThing(b: input));
}

String doThing({
  a: '<A A A A A>', 
  b: '<B B B B B>', 
  c: '<C C C C C>',
}) => '$a$b$c';
```

... outputs ...

```js
P.print("<A A A A A>" + H.S(input) + "<C C C C C>");
P.print("<A A A A A>" + H.S(input) + "<C C C C C>");
P.print("<A A A A A>" + H.S(input) + "<C C C C C>");
```

Err! That's less good. Yeah, we're emitting code that is going to marginally better on a cold VM, but in the process we are also not allowing V8/JS VMs to inline (we basically "took" an inline better served by their VM), and the resulting code size is much larger than if we just use renamed `doThing` to `d` and re-used it.

Here's me "forcing" `@noInline`-like behavior:

```dart
void main(input) {
  print(doThing(b: input));
  print(doThing(b: input));
  print(doThing(b: input));
}

String doThing({
  a: '<A A A A A>', 
  b: '<B B B B B>', 
  c: '<C C C C C>',
}) {
  return '$a$b$c';
  return null;
  return null;
  return null;
  return null;
  return null;
}
```

... outputs ...

```js
main: [function(input) {
  P.print(F.doThing("<A A A A A>", input, "<C C C C C>"));
  P.print(F.doThing("<A A A A A>", input, "<C C C C C>"));
  P.print(F.doThing("<A A A A A>", input, "<C C C C C>"));
}, "call$1", "main__main$closure", 2, 0, 7],
doThing: function(a, b, c) {
  return a + H.S(b) + c;
}
```

We've now forced emitting `doThing`, which means V8 can optimize it, and frequent uses of it will be "hotter" than inlining ourselves. We didn't fix the inlining issue though - optional parameters don't play well here. Look what happens when I switch to `??=` instead:

```dart
void main(input) {
  print(doThing(b: input));
  print(doThing(b: input));
  print(doThing(b: input));
}

String doThing({
  a, 
  b,
  c,
}) {
  a ??= '<A A A A A>';
  b ??= '<B B B B B>';
  c ??= '<C C C C C>';
  return '$a$b$c';
  return null;
  return null;
  return null;
  return null;
  return null;
}
```

... outputs ...

```js
main: [function(input) {
  P.print(F.doThing(null, input, null));
  P.print(F.doThing(null, input, null));
  P.print(F.doThing(null, input, null));
}, "call$1", "main__main$closure", 2, 0, 7],
doThing: function(a, b, c) {
  if (b == null)
    b = "<B B B B B>";
  return "<A A A A A>" + H.S(b) + "<C C C C C>";
}
```

Getting there. Code-size is getting smaller, and the function will stay hotter.

There are a lot more scenarios than this (@rakudrama mentioned some to do with `const` folding), but this is just a few examples of how the current inlining behavior doesn't necessarily do what you'd expect, and it's legitimately hard to work around them.

**Comment by nex3** [comment]
Even if inlining were perfectly calibrated to code size, I'd still want `@noInline` in order to ensure that, for example, stack traces were preserved in important situations.

**Comment by matanlurey** [comment]
I think @rakudrama's point:

> We would also like to make a change to the sourcemap tracking and format so that the stack range from inlining is available (i.e. a location in the JS corresponds to a list of source locations). This would make the stack traces less confusing.

... makes a lot more sense for this particular scenario.

**Comment by nex3** [comment]
If it's possible to do that reliably, that would be great.

**Comment by rakudrama** [comment]
@matanlurey We will address inlining _quality_ as part of the migration to Kernel. You will see nothing until Kernel lands, then it will be a bit worse until we make it a bit better. With Kernel we will be able to implement inlining heuristics that we can't implement today.

In the meantime, as @nex3 explains, there are reasons other than code size or run time performance to want to disable inlining.

**Comment by matanlurey** [comment]
@rakudrama Are there any tracking issues/plans for inlining? I'm sort of worried of going into changing anything without a concrete plan - otherwise I'd rather just see the current heuristic implemented as-is then possibly regress.

i.e. I'd like to see

`scenario` -> `expectation`, with explanations of why, i.e.

* Better pattern for V8
* Helps with code size
* Helps with constant folding

**Comment by rakudrama** [comment]
- The initial request (to not inline selected methods) is available via [this annotation](https://github.com/dart-lang/sdk/blob/master/pkg/meta/lib/dart2js.dart#L20)
- We are implementing a plan for sourcemaps to be augmented with inlining information. This will allow stack traces to be processed off-line to add inlined frames

I'd like to close this issue.

**Comment by matanlurey** [comment]
Yup, lets close it!
