### ISSUE TITLE
Test standalone/packages_file_test is too slow

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26715]
The packages tests are too slow (see below)

0:03:46.597755 - vm - none-vm debug_x64/standalone/packages_file_test/10
0:03:20.432422 - vm - none-vm debug_x64/standalone/packages_file_test/13
0:03:19.418986 - vm - none-vm debug_x64/standalone/packages_file_test/15
0:03:09.938428 - vm - none-vm debug_x64/standalone/packages_file_test/11
0:02:38.387243 - vm - none-vm debug_x64/standalone/packages_file_test/14
0:02:30.449558 - vm - none-vm debug_x64/standalone/packages_file_test/12
0:02:29.233065 - vm - none-vm debug_x64/standalone/packages_file_test/17
0:02:27.671753 - vm - none-vm debug_x64/standalone/packages_file_test/16
0:01:01.441193 - vm - none-vm debug_x64/standalone/packages_file_test/03
0:01:00.552346 - vm - none-vm debug_x64/standalone/packages_file_test/05
0:01:00.036965 - vm - none-vm debug_x64/standalone/packages_file_test/06
0:00:53.149272 - vm - none-vm debug_x64/standalone/packages_file_test/02
0:00:51.604234 - vm - none-vm debug_x64/standalone/packages_file_test/04
0:00:47.935153 - vm - none-vm debug_x64/standalone/packages_file_test/01

**Comment by johnmccutchan** [comment]
@a-siva @lrhn

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2072793002

**Comment by floitschG** [comment]
Afaik Lasse already spent a significant amount of time improving the tests (and splitting them).
The test needs to spawn new isolates and new instances of the VM. I don't think there is much that can be done to avoid that. (Last time I saw Lasse, he was still working on an improvement that reused VMs, but I think that's already in).

Couldn't you just skip the tests in debug mode instead of disabling them in every mode?

@a-siva Lasse already spent weeks writing these tests. If you ever run into issues isolating the failure we will be happy to help figuring out what the exact problem is. I would prefer not spending more time on them.

**Comment by johnmccutchan** [comment]
@floitschG AFAIK Lasse has not landed the reused VMs change. There is also the issue of the complexity of these tests.
