### ISSUE TITLE
socket_bind_test still fails sometimes

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26716]
It seems this test still fails sometimes - possibly another error condition that is not properly handled by the test itself? @mkustermann 

https://build.chromium.org/p/client.dart/builders/vm-linux-debug-simarm-be/builds/852/steps/vm%20tests/logs/stdio

```
FAILED: none-vm debug_simarm standalone/io/socket_bind_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 57270
#0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:505)
#1      _RootZone.runUnary (dart:async/zone.dart:1204)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=DebugSIMARM out/DebugSIMARM/dart --ignore-unrecognized-flags --package-root=out/DebugSIMARM/packages/ /mnt/data/b/build/slave/vm-linux-debug-simarm-be/build/sdk/tests/standalone/io/socket_bind_test.dart
Took 0:00:00.730646

Short reproduction command (experimental):
    python tools/test.py -asimarm --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg -t480 standalone/io/socket_bind_test
```

**Comment by johnmccutchan** [comment]
Another failure last night: https://build.chromium.org/p/client.dart/builders/vm-mac-release-x64-be/builds/13791/steps/vm%20tests/logs/stdio

@mkustermann Should we just skip the test because it's buggy?

**Comment by mkustermann** [comment]
Skipping the test is as good as removing it completely. There is therefore no point in skipping it.

The stacktrace from the VM does unfortunately not show the line in `main.dart`, though I suspect it's the same part of the test I've been looking into together with Florian.

There is no other test which ensures that one can bind two socketes on IPv6 only and IPv4 on the same port (which is ensuring the dart:io implementation is correctly implemented). Obviously this test depends on state in the OS (free ports) and since we cannot control other processes running on the system there is always a slight probability of a port clash.

If this still happens a lot, I would suggest putting in a retry mechanism -- so assuming the clash happens with probability p then retrying 3 times would make the test only red with probability `p*p*p`. WDYT?

**Comment by johnmccutchan** [comment]
A retry mechanism sounds like it might work

**Comment by mkustermann** [comment]
I'll make a CL to do that and we'll see if that reduces the flakiness.

**Comment by mkustermann** [comment]
We'll see if the retry mechanism makes the flakiness go away. Feel free to re-open if it does not.

**Comment by fsc8000** [comment]
Thanks!
