### ISSUE TITLE
Wrong JSON encoding of strings with Unicode character

### ISSUE THREAD

**Issue by B3rn475** [dart-lang/sdk#26721]
If a JSON response from the service socket contains a UTF-32 character > 0xFFFF it is truncated.
Example: http://unicode-table.com/en/10021/

How to reproduce:
```
dart --observe --vm_name=Strange𐀡Name <script>.dart
```
The actual name returned is ```Strange!Name``` (the character ```0x00010021``` is encode as ```\u0021```)

Possible bug in https://github.com/dart-lang/sdk/blob/0c1e85ebadaa0680d4ff30acc1f3ac823c53756e/runtime/platform/text_buffer.cc#L84

Do we need to actually encode non ASCII characters?
From the JSON official documentation it seems not. http://json.org/

**Comment by lrhn** [comment]
You don't have to encode non-ASCII characters in JSON as escapes, but if you don't, you may need to encode them anyway, probably as UTF-8.

The function in `text_buffer.cc` appears to only expect UTF-16 code units, so it won't handle U+10021 correctly. It seems someone is calling that function with non-UTF-16 data. It doesn't help that the function takes a `uint32_t` as argument instead of the more precise `uint16_t`.
