### ISSUE TITLE
UnmodifiableListView extends class that is not part of Dart API

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#26736]
Please see https://api.dartlang.org/stable/1.16.0/dart-collection/UnmodifiableListView-class.html

> Inheritance Object ListBase<E> UnmodifiableListBase<E> UnmodifiableListView

But `UnmodifiableListBase` is not part of the Dart API. This has several consequences
First, I think, `UnmodifiableListBase` shold be made internal `_UnmodifiableListBase`
Second, it shouldn't be shown in documentation. Otherwise documentation became wrong. For example, it shows `operator []=` as inherited (it is really inherited from `UnmodifiableListBase`, but documentation shows `operator []=` as inherited from `ListBase` (because `UnmodifiableListBase` is not part of the API and has no documentation)). But `operator []=` in `ListBase` sets the value while `operator []=` in `UnmodifiableListView` throws `UnsupportedError`

Documentation issue regarding showing of internal interfaces is dart-lang/dartdoc#1173

**Comment by lrhn** [comment]
This is similar to issue #26643 in that it exposes an interface from `dart:_internal`.

We can't make `UnmodifiableListBase` private because it's from a different library (`dart:_internal`).
We can either find a way to hide it from the DartDoc, move the class to `dart:collection` and make it private, or move it and keep it public.
The first option is still open (as an issue against the dartdoc tool), the second one is likely to fail because `UnmodifiableListBase` is also used in libraries other than `dart:collection`, so the third option looks better and better.

**Comment by floitschG** [comment]
This issue was moved to dart-lang/dartdoc#1481
