### ISSUE TITLE
Please remove angel_framework 1.0.0-dev+4pub

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/sdk#26771]
This was a typo when working with WebStorm. It is overriding 1.0.0-dev+5 and a tad annoying.

Thanks in advance.

**Comment by whesse** [comment]
There is a problem with deleting this version.  We can only delete individual versions on pub if they are not the most recent version, and since 4pub is sorting above 5 and 6, it is the latest version.

It is sorting above 5 and 6 because strings sort above numbers.  You could make a build number higher than 4pub by using something like a.5 or pre.6, so the entire version number would be
1.0.0-dev+a.5

A better solution would be to use numbers in the prerelease component, not in the build number.  The part after - and the part after + are treated separately, so if you stop using the +, then you will have something that sorts higher.  The parts are then split on ".", and sorted piece by piece on those components.
So:
1.0.0-dev.7 will sort higher than 1.0.0-dev+4pub
So you could switch either to 1.0.0-dev.7, or to 1.0.0-dev.1+7, whichever you want.
We use the former scheme, like 1.17.0-dev.4.2, in versioning the Dart sdk.

Once you add a new version which is later than the 4pub one, we can delete the 4pub one.

The only way to delete only the 4pub version, without adding a new one with more than "dev" between the - and +, would be to delete the entire project, and re-upload all the versions.

**Comment by thosakwe** [comment]
Thanks very much for the explanation. I'll switch to the dot scheme, and
double-check my pubspec before uploading from now on.
