### ISSUE TITLE
Cannot read property 'then$1' of undefined when cancelling periodic stream subscription

### ISSUE THREAD

**Issue by dustinlessard-wf** [dart-lang/sdk#26777]
When attempting to cancel a subscription to a periodic stream, doing something like this:
```dart
import 'dart:async';

Stream<dynamic> _myPeriodicStream;
StreamSubscription _myStreamSubscription;

void main() {
  _myPeriodicStream = new Stream<dynamic>.periodic(new Duration(milliseconds:100));
  _myStreamSubscription = _myPeriodicStream.listen((_){});
  _myStreamSubscription.cancel().then((_){
    print('cancelled subscription');
  });
}
```

An error is thrown:
```shell
Uncaught TypeError: Cannot read property 'then$1' of undefined
```

A quick trip to the function comments shows:
```dart
* Returns a future that is completed once the stream has finished
   * its cleanup. May also return `null` if no cleanup was necessary.
   *
   * Typically, futures are returned when the stream needs to release resources.
   * For example, a stream might need to close an open file (as an asynchronous
   * operation). If the listener wants to delete the file after having
   * canceled the subscription, it must wait for the cleanup future to complete.
```

Why return a null in the case of no cleanup being necessary? It's a bit unexpected to have to check if we're getting a null back instead of a Future.  I expected that in the case of no cleanup, we would simply get a Future that immediately resolves.

**Comment by floitschG** [comment]
Initially, `close` was a void function.
We later realized that this was a mistake and changed the API. However, for backwards-compatibility reasons we still had to allow the old void-functions. Since these void functions implicitly return `null`, we allow `null` as return value for `close`.

If you use async/await syntax, you don't need to care, since `await null` works fine.

Leaving this issue open, since we should probably update the documentation to recommend returning a `Future` and update our own Subscriptions.

**Comment by floitschG** [comment]
Commit didn't stick. Will have to investigate why some tests are failing.
