### ISSUE TITLE
Missing compile-time error when a class using "super" is mixed in

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#26774]
```
$ cat test.dart 
class A {
  foo()  => print('A.foo');
}

class B {
  foo() => super.foo();
}

class S1 extends A with  B { }

main() {
  print(new S1().foo());
}

$ dart test.dart
A.foo
null

$ dartanalyzer test.dart
Analyzing [mixin.dart]...
[error] The class 'B' cannot be used as a mixin because it references 'super' (test.dart, line 9, col 26)
[warning] The method 'foo' is not defined in a superclass of 'Object'. (test.dart, line 6, col 18)
1 error and 1 warning found.

$ dart2js test.dart
mixin.dart:6:12:
Warning: Can't resolve 'foo' in a superclass of 'B'.
  foo() => super.foo();
           ^^^^^^^^^^^
mixin.dart:9:26:
Error: Cannot use class 'B' as a mixin because it uses 'super'.
class S1 extends A with  B { }
                         ^
mixin.dart:6:12:
Info: Use of 'super' in class used as mixin.
  foo() => super.foo();
           ^^^^^^^^^^^
Error: Compilation failed.
```

The analyzer and dart2js agree here, I therefore suspect that the VM implementation is incorrect.

**Comment by lrhn** [comment]
The current specification allows super-calls in mixin classes.
There is nothing inherently wrong with the program, and the VM is behaving correctly. Dart2js haven't implemented the spec yet (#23773), and I'm guessing the VM is hiding the functionality until it's fully supported.

I'd probably prefer to require B to be abstract, since it's `super.foo()` call is known to be bad on an instance of `B`, but to support mixins we allow super-calls even when the super-class does not have the method implementation. It's a warning, not an error, and since the VM doesn't show warnings, it works as expected.
