### ISSUE TITLE
Decide whether to eliminate propagated types from analyzer

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26795]
This is a prerequisite for issue #26794.

**Comment by bwilkerson** [comment]
It's important to distinguish between type propagation for statics (static fields and top-level variables) and local type propagation. I believe that only the former is a prerequisite for summaries and hence covered by this issue.

My inclination is to stop performing type propagation for statics, but it then becomes a question of when to do so.

I think we should stop because the type propagation that analyzer is doing for statics is equivalent to the inference that strong mode performs. When strong mode is the only mode there will no longer be any value to having type propagation do the same work. Hence, any work we do now to support propagated type information in summaries would need to be backed out later.

The question is when to stop. I believe that disabling type propagation will hurt the UX for everyone not using strong mode. I would prefer to minimize the length of time that the quality of the UX is diminished. We could clearly disable it today, but that would maximize the impact. The other reasonable option that I know of is to wait until we *must* disable it: the point at which we start using summaries in analyzer.

**Comment by stereotype441** [comment]
In a discussion today, we decided to proceed with eliminating propagated types of static fields and top-level variables now.  Issue #26794 is now unblocked.
