### ISSUE TITLE
Extends clause is not used for typing

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26817]
In the following example, the 'create' function is not assignable to `(TaskSpecification, Zone) -> dynamic`.

``` dart
typedef T TaskCreate<T, S extends TaskSpecification>(
    S specification, Zone zone);

Object/*=T*/ createTask/*<T, S extends TaskSpecification>*/(
      Zone zone, TaskCreate/*<T, S>*/ create, TaskSpecification/*=S*/ specification) {
  // use `create` as (TaskSpecification, Zone) -> dynamic.
}
```

The message from the analyzer:
```
Unsound implicit cast from (S, Zone) → T to (TaskSpecification, Zone) → dynamic
```

**Comment by jmesserly** [comment]
I think that's an example of wanting covariant parameters (unless I'm confused, which is often the case :) ) . Here's a simplified example running on Dart VM without generic methods:
```dart
class TaskSpecification {}
class MyTaskSpec extends TaskSpecification {}
takesMyTaskSpec(MyTaskSpec m) {}

typedef TakesAnyTaskSpec(TaskSpecification t);
main() {
  TakesAnyTaskSpec t = takesMyTaskSpec;
  t(new MyTaskSpec()); // works at runtime

  // type 'TaskSpecification' is not a subtype of type 'MyTaskSpec' of 'm' where
  t(new TaskSpecification());
}
```

it's an error because `(TaskSpecification, Zone) → dynamic` says the callback must accept any TaskSpecification, but the "create" function could in fact require a subtype S.

The error message could be a lot more helpful though.

**Comment by floitschG** [comment]
Ah. correct.
Didn't pay enough attention.
