### ISSUE TITLE
Argument to List.remove() should be typed T

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#26852]
If you have a list of Ts, then there's never a valid reason to be removing an object from the list that isn't of type T, and doing so is an indication of a bug (e.g. you're saying `remove(0)` instead of `removeAt(0)`).

**Comment by lrhn** [comment]
This was a deliberate choice.

We treat generics in Dart as if they are covariant - a `List<int>` *is a* `List<num>`.
There are some collection methods that can't be used covariantly, like `add`, because they try put something into the collection that isn't allowed there. You can't put a double into a `List<int>`. Those methods fail if you try to use them incorrectly (at least in checked mode).
And then there are some methods that do work perfectly when used covariantly, including `contains` and `remove`. Treating a `Set<int>` as a `Set<num>` is an abstraction that is't broken by trying to remove a double from the set - the operation is a success and the set is unchanged.
So, to allow these operations (and `contains` in particular), the methods are typed to accept any object.

If you check the Java collection API, you'll find the same behavior. C# is different, likely because their generics are invariant and they have built in `Cast` methods to convert the collection to a collection of a supertype.

**Comment by Hixie** [comment]
I guess that makes sense?

To me it seems like if you know that you've got a Set of ints, then removing 0.5 is wasted CPU cycles, and indicates a problem with your algorithm. You shouldn't be removing things that you can prove you never added. But maybe this means it's more of a lint than a type error.
