### ISSUE TITLE
Generalize assert syntax

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#26866]
With reference to https://github.com/dart-lang/sdk/issues/17682 for background, the language specification should be adjusted such that it uses the grammar rule

`assertStatement: assert '(' expression ')' ';'`

rather than the current one which uses `conditionalExpression`. The wording of the paragraph starting with 'The conditional expression _e_ ..' in section 17.17 should be adjusted accordingly.

The language team analysis of this issue is available at https://gist.github.com/eernstg/50a327addd96035d5393a507c0ea2d9a.

**Comment by bwilkerson** [comment]
Should we also update the specification to reflect the optional message that I believe is already supported by all of the platforms?

**Comment by floitschG** [comment]
Let's do this independently, but yes.

**Comment by lrhn** [comment]
Is the optional message supported anywhere? I don't think we ever agreed on a design.

**Comment by bwilkerson** [comment]
Analyzer supports an optional message (see https://github.com/dart-lang/sdk/issues/24217). According to https://github.com/dart-lang/sdk/issues/24213 it is also supported in dart2js and the formatter (though that issue was never updated to reflect that analyzer supports it). The discussion was around whether to require the second argument to be a `String` or whether to allow any object and use `toString()` to convert it to a string.

**Comment by lrhn** [comment]
... or not convert it at all, and keep it as-is in the `AssertionError` object.

**Comment by munificent** [comment]
Closing this because the commit message says it's fixed.

GitHub's "auto-close" looks for certain strings like "Fixes #...", but "fixes issue #..." isn't one of them. :)
