### ISSUE TITLE
Compiler should enforce void return type, at least in the case of native methods

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#26861]
See
   https://codereview.chromium.org/2118633002/ 
   https://github.com/dart-lang/sdk/issues/26740

The motivating example is that AudioNode.connectNode changed from having a void return type to AudioNode sometime between Chrome 46 and 53. In checked mode, dart2js complains that we are returning a value from a void function. The compiler should be able to enforce that if we said the function was void we don't return a value, at least for the case of calling out to native APIs that may change in this way, and possibly in general.

@rakudrama 
@floitschG

**Comment by lrhn** [comment]
It's not the first time we have had problems because a `void` function actually returns something non-null.
One of the reasons that is possible is that you:

1. can return the result of a void function from another void function, and
2. you can override a void function to be non-void in a subclass.

That means that `void foo(Bar bar) => bar.voidFunc();` may return a non-null value if `Bar's` subclass overrides `voidFunc` to be non-void, and there is nothing the type system can do about it.

I don't think it's feasible to prevent the second item - we do want to be able to specialize a `void` function in subclasses. However, the reason we are allowed to do so is that there is an implicit promise that nobody uses the result of a `void` function for anything.
That suggests that we should prevent uses of void results everywhere, not just almost everywhere. That means no returning of a `void` result, even if the current function is `void`. You have to write `f(); return;` instead of `return f();` 

That would also put an end to the horrible practice of using `=>` in void functions! :)

**Comment by natebosch** [comment]
I think we ended up reversing our thinking - we explicitly allow using `=>` in void functions now.

Is there anything left to do here?

**Comment by joshualitt** [comment]
Closing because its not clear we can do better.
