### ISSUE TITLE
HOT RELOAD: Hot reload bots don't have ipv6 configured

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26871]
Results in many test failures

https://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-live-reload-be/builds/2/steps/checked%20vm%20tests/logs/stdio

**Comment by johnmccutchan** [comment]
@rmacnak-google @a-siva FYI

**Comment by whesse** [comment]
Yes, I know.  All these new bots without IPv6 have the builder_tag no_ipv6,
so we can skip the failing tests in the status files.  We should split them
all into separate ipv6 and ipv4 versions.  We have to do this because the
new machines are all cloud engine.
On Jul 12, 2016 21:02, "John McCutchan" <notifications@github.com> wrote:

@rmacnak-google <https://github.com/rmacnak-google> @a-siva
<https://github.com/a-siva> FYI

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/sdk/issues/26871#issuecomment-232146370>, or mute
the thread
<https://github.com/notifications/unsubscribe/AErap075d1Xw-FjBDN8OSVARZQ08MnxJks5qU-TZgaJpZM4JKtzK>
.

**Comment by johnmccutchan** [comment]
@whesse How do I check for the builder_tag?

Is it this:

[ $no_ipv6 ]
...: SkipByDesign # Relies on ipv6

**Comment by whesse** [comment]
I think $builder_tag == no_ipv6.  Grep the repo for builder_tag, and find
it in status files.

On Tue, Jul 12, 2016 at 9:34 PM, John McCutchan <notifications@github.com>
wrote:

> @whesse <https://github.com/whesse> How do I check for the builder_tag?
>
> Is it this:
>
> [ $no_ipv6 ]
> ...: SkipByDesign # Relies on ipv6
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dart-lang/sdk/issues/26871#issuecomment-232154698>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AErapxo6j0rnGe9nU3fccYsi4R9dasC4ks5qU-w9gaJpZM4JKtzK>
> .
>



-- 
William Hesse

**Comment by johnmccutchan** [comment]
That worked. Thanks!
