### ISSUE TITLE
lib/math/double_pow_test can fail because we generate different NaNs in optimized vs unoptimized code

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26887]
FAILED: none-vm-checked debug_x64 lib/math/double_pow_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.identical(expected: <NaN>, actual: <NaN>) fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.identical (package:expect/expect.dart:148:5)
#2      test (file:///b/build/slave/vm-linux-debug-x64-live-reload-be/build/sdk/tests/lib/math/double_pow_test.dart:139:12)
#3      main (file:///b/build/slave/vm-linux-debug-x64-live-reload-be/build/sdk/tests/lib/math/double_pow_test.dart:161:32)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --enable_type_checks --hot-reload-test-mode --optimization-counter-threshold=5 --no-background-compilation --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /b/build/slave/vm-linux-debug-x64-live-reload-be/build/sdk/tests/lib/math/double_pow_test.dart
Took 0:00:08.038699

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --hot-reload --builder-tag no_ipv6 --checked -t120 lib/math/double_pow_test

**Comment by johnmccutchan** [comment]
@fsc8000 Any idea?

**Comment by johnmccutchan** [comment]
@crelier This might be a canonicalization issue with reload.

**Comment by crelier** [comment]
I cannot reproduce this failure locally with this command:
out/DebugX64/dart --enable_asserts --enable_type_checks --hot-reload-test-mode --optimization-counter-threshold=5 --no-background-compilation --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ tests/lib/math/double_pow_test.dart

Any other command I should try?

**Comment by johnmccutchan** [comment]
@crelier That's the right command but it is extremely difficult to reproduce. I haven't been able to locally.

**Comment by johnmccutchan** [comment]
Just noting that I haven't seen this since the first time.

**Comment by johnmccutchan** [comment]
Closing because I've never seen this issue again and no one can reproduce it.

**Comment by johnmccutchan** [comment]
Visible on the bots after enabling this test again.

**Comment by johnmccutchan** [comment]
@fsc8000 Can you take a look at this? It's easy to reproduce now.

**Comment by johnmccutchan** [comment]
@fsc8000 I suspect that the issue is the difference in optimized and unoptimized pow. It's not a canonical instance issue.

**Comment by fsc8000** [comment]
This is an issue of NaN being computed in different ways: I observed that even in C++ NAN from math.h and 0.0/0.0 differ in the sign bit. The test should not assert that NaNs are identical.

**Comment by johnmccutchan** [comment]
@lrhn The test is buggy, please fix it.

**Comment by floitschG** [comment]
If I remember correctly we specified (long long ago) that NaNs are identical to each other.

Since users can see the actual values by storing them into typed arrays (which were added a later point) we might want to change the spec (if it's even part of a written spec).

In any case: if we make them non-identical, then the test shouldn't be flaky, since it must keep track of the NaNs.

**Comment by fsc8000** [comment]
It is an unnecessary burden on the implementation to make NaNs identical. The spec mandates it, but this would be a good candidate to relax the spec, since it would allow an implementation to use C library functions of the platform without checking for the correct bit pattern.

**Comment by fsc8000** [comment]
https://codereview.chromium.org/2247553002/

**Comment by lrhn** [comment]
Dart IEEE-754 doubles are `identical` if they have the same bits. That includes NaNs with payloads or sign. The spec says this in a roundabout way, but the effect is that you only have to compare bit patterns.
The spec *doesn't* require different NaNs to be identical, rather the opposite, for the reason Florian S says - it would be unnecessarily cumbersome (not a lot of cumberance, but completely unnecessary, so the tradeoff is clear). I do believe we changed that at some point, so Florian L is probably correct that we required NaNs to be identical in the beginning, matching JavaScript behavior.

It feels wrong to have *distinguishable* values that are `identical`, and NaNs with payloads or sign are such values because you can store them into typed-data lists and see the bits. We don't want to normalize NaN values when storing or loading from a `Float64List`.

The `pow` method is specified in [https://api.dartlang.org/stable/1.16.1/dart-math/pow.html](much detail). 
It is intended to match the IEEE-754 "pow" function, but it just says that an operation with a NaN input becomes NaN (except for a couple of exceptions where one of the operands may be NaN). We don't distinguish between quiet and signaling NaNs, and we don't say which NaN to use, so it isn't technically wrong to return different NaNs for different cases. I think the problem here is that the VM generates the result by calling a C library function that has the appropriate behavior, and we are not in control of which NaN it produces.

I would really prefer if we always generate the positive zero-payload quiet-NaN if possible, but I know that the negation operator doesn't do that (nor does it in the IEEE-754 spec), which is likely the problem we are seeing for computed NaNs.
For cases where one of the inputs is NaN, we should always return one of the existing NaN values, and I think C libraries probably do that.

**Comment by fsc8000** [comment]
Thanks. I checked on my Linux box with C there are different NaNs if you do
```0.0/0.0``` vs. ```NAN``` from math.h. One has the sign bit set, and the other does not. Other than that they are identical.
