### ISSUE TITLE
HOT RELOAD: Handle complex message passing and reloading isolates with shared origins

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26893]

**Comment by johnmccutchan** [comment]
Ryan suggests modifying the origin of the reloaded isolate so it longer matches and complex messages can no longer be sent.

Lars suggests reloading all isolates with a shared origin atomically. This would allow complex message passing applications to be reloaded in a consistent way. We need to add support for stopping all isolates with the same origin simultaneously.

**Comment by johnmccutchan** [comment]
@larsbak @turnidge FYI

**Comment by rmacnak-google** [comment]
Adding some context so I don't forget.

By shared origin we mean isolates derived from spawnFunction. Logically such isolates have the same code, which is why they are allowed to pass arbitrary objects when messaging each other. When the code of one isolate in a spawnFunction family changes, either we must disallow further use of arbitrary messages or make the same change to all other isolates in the family.

A related bug is that the implementation of spawnFunction will load the child isolate from sources, which could have changed since the parent was loaded. The parent and child would be permitted to send arbitrary objects in messages to each other with classes the other isolate potentially does not have.
