### ISSUE TITLE
--no-implicit-dynamic should take @optionalTypeArgs into account

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26901]
![image](https://cloud.githubusercontent.com/assets/405837/16896559/e7fbce82-4b97-11e6-88e7-fae65ab20d46.png)

``` dart
@optionalTypeArgs
class MapDataItem<K, V> extends DelegatingMap<K, V> implements DataItem<K, V> { ... }
```

**Comment by kevmoo** [comment]
FYI @jmesserly

**Comment by jmesserly** [comment]
what is `@optionalTypeArgs` ...?

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/meta

**Comment by jmesserly** [comment]
Hmmm. But what's it used for? I don't understand why it's a good idea. It seems to defeat the purpose of --no-implicit-dynamic, which is opt in, but is intended to give you confidence there is no "accidental dynamic" in your code anywhere.

There is a way to get similar behavior with strong mode+no-implicit-dynamic:
```dart
class MapDataItem<K extends Object, V extends Object> extends DelegatingMap<K, V> implements DataItem<K, V> { ... }
```
By adding `extends Object` it changes the default behavior, now it will implicitly instantiate with Object, which unlike dynamic, is a somewhat safe default. At least, much safer and seems more in the spirit of "no-implicit-dynamic".

I suppose we could combine them and have `@optionalTypeArgs`  mean implicit Object. Or we just make implicit Object always. The problem is, it doesn't help if you plan on downcasting:

```dart
f(MapDataItem<String, int> m) { ... }

var myItem = new MapDataItem(...);
f(myItem); // boom, cast failure!
```

That's why we were trying to encourage type arguments. With a type like `MapDataItem<K, V>` we should pretty much always infer from the constructor key/value type anyway (ctors have upwards+downwards inference now).

CC @leafpetersen as well

**Comment by zoechi** [comment]
I didn't realize that generic type parameter constraints are used this way. I tried it and it seems to solve my problem.

I like this better than `@optionalTypeArgs` which I used for exceptions to `always_specify_types`

**Comment by zoechi** [comment]
BTW :beers: :beers: :beers: for  `--no-implicit-dynamic`. I was missing this since I started using Dart.

**Comment by jmesserly** [comment]
awesome! Let us know if that feeling changes based on experience :) I will leave this open because it's at least an inconsistency we should think about. And I do worry about taking away the nice "raw type" syntax. Let us know and we can bump the priority to figure out something good for that.

**Comment by jmesserly** [comment]
Closing this issue as stale; we do have work planned for new `--strict` flags in Analyzer that should be easier to use compared to `--no-implicit-dynamic`
