### ISSUE TITLE
Cannot store parsed double into Float32List

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#26951]
```
var a = new Float32List(1);
a[0] = double.parse('1.2');
print(a[0]); // Prints 1.2000000476837158
```
(https://dartpad.dartlang.org/802761b418584c06b84e80030fb45fff)

How can I get it to print `1.2`?

**Comment by hermanbergwerf** [comment]
Same issue with:
```
var a = new Float32List(1);
a[0] = 1.2;
print(a[0]);
```

**Comment by hermanbergwerf** [comment]
I now use this function to get around this issue, but it's not a great solution.
```
final digits = value.floor().toString().length;
final factor = pow(10, 8 - digits);
value = value * factor;
value = value.roundToDouble();
value = value / factor;
```

**Comment by lexaknyazev** [comment]
32-bit (single-precision) representations of `1.2` and `1.2000000476837158` are the same:
```dart
var a = new Float32List(1);
a[0] = 1.2;
print(a.buffer.asUint8List()); // [154, 153, 153, 63]
a[0] = 1.2000000476837158;
print(a.buffer.asUint8List()); // [154, 153, 153, 63]
```
However, `a[0]` returns a 64-bit (double-precision) floating-point number. So you have to round returned value or store data as Float64List for more precision.

**Comment by rakudrama** [comment]
This is all working as intended. Floating point arithmetic rarely represents the fractional decimal digits of a number exactly.

If you want to control the number of decimal digits in the String representation, consider using `x.toStringAsPrecision`, `x.toStringAsFixed`, or `NumberFormat` from the [Intl package](https://pub.dartlang.org/packages/intl).

To learn more about floating point arithmetic and the IEEE 754 floating point 32-bit and 64-bit (`double`) formats here: [What Every Computer Scientist Should Know About Floating Point Arithmetic](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.22.6768)

As Alexey noted, 1.2 and 1.2000000476837158 have the same 32-bit floating point representation.

What you might not realize is that the problems of an inexact representation start earlier.
`1.2` cannot be represented exactly as a `double`.
The nearest `double` values to 1.2 are:

A= 1.199999999999999733546474089962430298328399658203125
B= 1.1999999999999999555910790149937383830547332763671875
C= 1.20000000000000017763568394002504646778106689453125

"1.2" is converted by `double.parse` to the 64-bit double that represents the nearest value to 1.2, i.e B= 1.1999999999999999555910790149937383830547332763671875
When this value (B) is printed, it is printed as "1.2", since if we convert "1.2" to a double again, we get back the same bits (B). This gives the _illusion_ that the fractional digits are handled precisely when the value is actually an approximation that can be represented in the `double` format.
