### ISSUE TITLE
How does the Dart VM work?

### ISSUE THREAD

**Issue by define-private-public** [dart-lang/sdk#26967]
I'm sorry for using the issue tracker to ask the question, but I couldn't find that much information about how the Dart VM works aside from this article: https://www.dartlang.org/articles/dart-vm/why-not-bytecode

So far the only thing that I can infer is that the Dart VM creates an AST of my source and then it traverses the tree to execute the code.  Is this correct?

**Comment by eernstg** [comment]
I'm not working on the VM and I can't immediately point out any design documents available to the public, so I'll leave it to others to give a better answer. But I can say a couple of things:

The gory details of the implementation are available directly because this is open source: check out https://github.com/dart-lang/sdk/tree/master/runtime/vm.

Next, you seem to conclude that the vm interprets abstract syntax trees (presumably because the web page you mention doesn't say anything that contradicts this, and it mentions loading source code directly), but that's far from the truth: It compiles to native code on several different platforms (including Android, Linux, MacOS, Windows) and processors (including ia32, x64, arm, arm64, mips).

Finally, the best place to ask a question like this would be found by checking out https://groups.google.com/a/dartlang.org/forum/#!forum/misc and following the guidelines at the top of that page.
