### ISSUE TITLE
Incorrect DYNAMIC_INVOKE hint with immediate call of closure

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26962]
The following code produces the strong mode hint DYNAMIC_INVOKE (`((x) => 1.0)(() {return 1;}) requires a dynamic invoke`):
```dart
    var v = ((x) => 1.0)(() { return 1; });
```
According to @leafpetersen, in general, applying a function with arguments of type dynamic is a dynamic invoke in DDC because of its "fuzzy arrows" feature, however this case should be recognized as a case where no dynamic invoke is actually required.

**Comment by jmesserly** [comment]
hmmm, tricky one.

I wonder what we're doing for FunctionExpression's type, if it's a strict or fuzzy arrow. My guess is we use fuzzy arrow right now, because we'd want a fuzzy arrow if we use that type in upwards inference, for example `var x = (x) => 1.0)`.

Assuming the problem is the invocation of `(x) => 1.0` (which is my guess), we could handle this in FunctionExpressionInvocation.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2211053002
