### ISSUE TITLE
abstract required for JS interop classes (used with implements)

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#26969]
Unfortunately, correctly using implements for MyChart e.g.,

```
@anonymous
@JS()
class MyChart implements Chart {
    external set domain(String v);
    external set measure_pct(String v);
    external set measure(String v);
}

```
will cause the following analyzer error:

```
package:ads.awapps2.infra.chart.directives/chart_directive.dart:19:
[WARNING] Missing concrete implementation of
setter 'HovercardTemplateFormatters.domain',
setter 'HovercardTemplateFormatters.measure' and
setter 'HovercardTemplateFormatters.measure_pct' 
[NON_ABSTRACT_CLASS_INHERITS_ABSTRACT_MEMBER_THREE]

ERROR: please check Dart analyzer errors and warnings above. They are breaking the build.
```
This requires me to add the abstract keyword to all @JS() classes e.g.,

```
@anonymous
@JS()
abstract class Chart {
  external factory Chart();
  external String get label;
  external set label(String v);
}

@anonymous
@JS()
abstract class MyChart implements Chart {
    external set domain(String v);
    external set measure_pct(String v);
    external set measure(String v);
}

```

This shouldn't be necessary for JS-Interop classes (they're always abstract - right?).

**Comment by bwilkerson** [comment]
They might always be abstract, but there has to be a way for tooling, such as the analyzer, to know that. Without language changes there are only two solutions that I can think of:
- explicitly declare all `@JS` classes as `abstract`, or
- add special knowledge of the `@JS` annotation to every tool (whose behavior depends on knowing whether or not a class is abstract).
The first seems preferable to me.

That said, the question here is whether there should be some way to specify that a constant, when used as an annotation, should imply certain modifiers so that tools can statically look at the constant and apply those modifiers. (It would be easier if annotations were a little more constrained (weren't allowed to be just any compile time constant).) For example, something like

```
class MyAnnotation implies abstract {
  const MyAnnotation();
}
```

**Comment by floitschG** [comment]
I'm probably missing something...

The specification for abstract states:

> An abstract method (respectively, abstract getter or abstract setter) is an
> instance method, getter or setter that is not declared external [...]

Why are the 'JS' classes then abstract?

**Comment by bwilkerson** [comment]
Good question.

@terrylucas How do the methods from HovercardTemplateFormatters come into play and how is it defined?

**Comment by terrylucas** [comment]
This will not be necessary in the future - not worth considering for a short lived time.
