### ISSUE TITLE
Should Map.putIfAbsent() be generic?

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#26983]
I'm reviewing [this patch](https://codereview.chromium.org/2184303002/diff/1/lib/src/ascii_tree.dart?context=10&column_width=80&tab_spaces=8), which has (slightly simplified here):

```dart
String fromFiles(List<String> files) {
  var root = <String, Map>{};
  for (var file in files) {
    var directory = root;
    for (var part in path.split(file)) {
      directory = directory.putIfAbsent(part, () => <String, Map>{})
          as Map<String, Map>;
    }
  }
}
```

The `as` cast sticks out because it's clearly casting to the exact type that the closure returns. The problem is that the closure returns a tighter type than the map's own value type. The value type is just `Map`, but the closure returns a `Map<String, Map>`.

We could fix this by making `putIfAbsent()` generic:

```dart
class Map<K, V> {
  S putIfAbsent<S extends T>(key, S ifAbsent()) { ... }
}
```

But I'm not sure if the additional complexity in the signature carries its weight. Thoughts?

cc @nex3

**Comment by nex3** [comment]
I vote yea. I think the signature is still pretty clear even with the generic annotation, and it reduces the number of casts our users have to make.

**Comment by lrhn** [comment]
I think there are far too many places where you can add extra type-overriding type parameters, but it won't necessarily make for a pleasant API.

Remember that `putIfAbsent` can return the existing value, which may be `T` and not `S`. You might know that it will be an `S`, but but if you just did an `operator[]` lookup, you don't get the chance to override the return type. The return type of `T` is the best the map itself can promise, so changing it is a way to implicitly add a cast. Might as well make it explicit instead of hiding it in a non-self-documenting type parameter.

**Comment by munificent** [comment]
> Remember that putIfAbsent can return the existing value, which may be T and not S.

Ah, of course! How could I forget. In that case, never mind. :)
