### ISSUE TITLE
Incorrect type inference when swapping type parameters in a constructor call

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26990]
The following code (inspired by HashBiMap.inverse from https://github.com/google/quiver-dart/blob/master/lib/src/collection/bimap.dart) produces strong mode errors:
```dart
    class Pair<T, U> {
      T t;
      U u;
      Pair(this.t, this.u);
      Pair<U, T> get reversed => new Pair(u, t);
    }
 ```
The errors are:
- At `new Pair(u, t)`: `The return type 'Pair<U, U>' is not a 'Pair<U, T>', as defined by the method 'reversed'.`
- At the `t` in `new Pair(u, t)`: `The argument type 'T' cannot be assigned to the parameter type 'U'.`

It seems like incorrect type parameters are being inferred for the call to the `Pair` constructor.

This behavior started happening in 8d2c6d033afd3427a28b3e0dc2d53649db404db8.

**Comment by bwilkerson** [comment]
@jmesserly

**Comment by jmesserly** [comment]
good catch!

it looks like an incorrect capture bug.

I wonder if we have a similar bug with generic functions. We certainly tried very hard to avoid this class of bug in them :)

If not, there's a few possibilities on what could be going on. Constructors have some notable differences:
- their downward inference uses matchType instead of the type variable constraint solver used for inference on generic functions/methods. (This is currently a TODO in the code)
- they go through some contortions to get back to the "uninstantiated" constructor function type, which generic functions/methods don't need to worry about (this one might be a TODO as well :) )
- we never fully refactored interface type generics to avoid capture like we did with function types 

Anyway I'll dig in, but that's kind of a scary bug. Hopefully it's something little and not "omg this is fundamentally broken" :)

**Comment by jmesserly** [comment]
Couldn't reproduce this with generic functions, so it seems specific to constructors (which makes sense)

**Comment by jmesserly** [comment]
got it. Our substitution for the "extends" clause w/ recursive bounds was incorrectly affecting inference for this. Fix on the way

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2205993002/

**Comment by scheglov** [comment]
Possibly related: https://codereview.chromium.org/2376213003
