### ISSUE TITLE
Dartium fails on non-typed List in gl.uniform*v

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#27018]
According to WebGL IDL, `uniform*fv(location, v)` should accept both `Float32Array` and `sequence<float>` for `v`.

This call:

``` dart
gl.uniform2fv(location, <num>[1.0, 0.0]);
```

fails in Dartium (1.18.1) with 

```
Uncaught Unhandled exception:
TypeError: Failed to execute 'uniform2fv' on 'WebGLRenderingContext': No function was found that matched the signature provided.
#0      Blink_JsNative_DomException.callMethod (dart:_blink:23416)
#1      BlinkWebGLRenderingContext.uniform2fv_Callback_2_ (dart:_blink:20794)
#2      RenderingContext.uniform2fv (dart:web_gl:3168)
```

but works in Chrome after dart2js compiling.

Call with typed array works in both cases:

``` dart
gl.uniform2fv(location, new Float32List.fromList(<num>[1.0, 0.0]));
```

**Comment by alan-knight** [comment]
That error is coming from JavaScript. Dartium passes both cases through to exactly the same place. See https://api.dartlang.org/stable/1.18.1/dart-web_gl/RenderingContext/uniform2fv.html

The reason is probably that in the version Dartium is based on (46) the IDL says 

```
    void uniform2fv(WebGLUniformLocation? location, Float32Array v);
    void uniform2fv(WebGLUniformLocation? location, sequence<GLfloat> v);
```

Also, that doesn't look like it's generally valid. See 
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniform

and in particular the line listing the types

A Float32Array for floating point vector methods (methods with "fv").

**Comment by lexaknyazev** [comment]
Just tested: Chrome & Firefox actually allow non-typed arrays. [IDL](https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl) too.
Moreover, dart2js-compiled call with non-typed array works in Dartium.

**Comment by alan-knight** [comment]
Hmm. That's peculiar. It suggests that the problem might be with passing the List through JS interop.

**Comment by lexaknyazev** [comment]
> It suggests that the problem might be with passing the List through JS interop.

Very likely: same bug with `vertexAttrib*fv` functions.

**Comment by matijakevic** [comment]
Any ongoing fixes for this issue?

**Comment by matanlurey** [comment]
Dartium is no longer being maintained, and is being phased out in `2.x`.

https://webdev.dartlang.org/tools/dartdevc

**Comment by matijakevic** [comment]
This isn't an issue with Dartium, happens when code is dart2js'd too.
