### ISSUE TITLE
Find out why we need to treat tools in the path recipe module specially

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#27028]
This code is in our dart recipes:

```
  api.path.c.dynamic_paths['tools'] = None
  api.bot_update.ensure_checkout(force=True)
  api.path['tools'] = api.path['checkout'].join('tools')
```

We should find if this is necessary.

**Comment by whesse** [comment]
According to the code in the path module, it is.  The overridden api.path.__setitem__ checks that the key is already present in dynamic_paths before adding the value to it, and the examples do it by explicitly setting it to None in the configuration.

We could drop the 'tools' path, since it is barely used, and just as simple to join 'tools' to the checkout path when it is used.

**Comment by athomas** [comment]
I'll remove the tools path for the new swarming recipes.
