### ISSUE TITLE
(Request) Add a getHighlights method to the analysis service

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27062]
Currently you can only get highlights via subscription for an entire document and not on-demand. Our [current implementation](https://github.com/Dart-Code/Dart-Code/pull/65) subscribes when required, gets the whole document data, then unsubscribes, but only uses the data for the curernt symbol under the cursor. This is really wasteful (on a big file we're getting all data rather than just the symbol we care about!).

While we could cache all this data in the integration, it seems a bit pointless if the server already also has it in-memory.

It would be great if we could request this (like we can for other things, like hovers).

**Comment by bwilkerson** [comment]
> ... but only uses the data for the current symbol under the cursor.

I don't understand what IDE feature you're trying to implement with this information. Could you clarify what you're trying to accomplish?

The purpose of the notification is to provide an IDE with the information needed to provide coloring or other "highlighting" to tokens in a file in order to convey syntactic and semantic meaning. It lets the client know, for example, that some particular identifier is actually a keyword in the language (an example of syntactic highlighting), or that some other identifier refers to a static const field in a class (an example of semantic highlighting).

The expectation, when we wrote the interface, is that clients would always apply this highlighting to everything in the file in order to make it easier for the user to locate important information (such as interpolation expressions inside string literals).

> While we could cache all this data in the integration, it seems a bit pointless if the server already also has it in-memory.

The value of having server tell the client when some data like this has changed is that the client doesn't have to try to guess when it needs to ask for updated data. For example, if the client is highlighting references to static fields and the file 'a.dart' is open and visible and contains a reference to a static field imported from 'b.dart', if the user performs a git checkout operation and 'b.dart' is changed such that the field is no longer static, then server will tell the client that the highlighting of that identifier needs to be updated. If server weren't proactive, it would be hard for the client to know that its information is out of date.

**Comment by DanTup** [comment]
Ugh, I totally got confused writing this case...

In Code, the things implemented is called a Highlight provider, but it's for highlighting symbols that are the same as the thing your cursor is on! What I actually meant was the Outline, which I actually raised as #27064. We use the same data (Outlines) for two features in this way, but I mistakenly thought we were using two different sets of data (because of confusion with the "highlight" name!).

So, this is a nonsense request, and what we actually want is #27064 but for two reasons! Sorry! :grin:

**Comment by bwilkerson** [comment]
No problem :-)

But if I understood what you described, it sounds like outline won't really get you want you want for the Highlight provider. I think what you're looking for is the `analysis.occurrences` notification.

(And the same explanation for why it makes sense for this to be a notification applies: changes to imported files can change the resolution of symbols in ways that clients shouldn't have to anticipate.)

**Comment by DanTup** [comment]
@bwilkerson Sorry, I'm totally not with it today. Occurrences is the thing we're using; this should've been a request for getOccurrences (I'll update the title). The problem is that we're asked by Code for this on-demand (eg. when a user puts their cursor in a symbol) but we currently have to subscribe to Occurrences and get data for the entire document, to only use one part of it. On a large file this is going to be a huge amount of data when we only need a fraction (and where response time is important).

So, does it seem reasonable for this to be a request for a `getOccurrences`?

**Comment by DanTup** [comment]
I see why I got confused - in the PR for this, there was a reformat around the other one we have (that uses outline) so I saw it in the diff... further down was the implementation using occurrences!

**Comment by bwilkerson** [comment]
> The problem is that we're asked by Code for this on-demand (eg. when a user puts their cursor in a symbol) ...

Yeah, that's the way IntelliJ works as well. Click on an identifier and have the other references to the same element highlighted.

> So, does it seem reasonable for this to be a request for a `getOccurrences`?

I'm not sure, hence the discussion. :-)

In addition to the issue discussed before (not being able to know when the current set of occurrences has changed due to changes outside the file) there's also a question of performance. If you have to spend time requesting data from server, and it has to re-compute it each time, it might be slower than if you have the data cached locally and can just access the piece you want. (I don't have numbers, I'm just guessing, so I might be wrong.)

I know that I often use this feature to help trace back the origin of some object. "Oh, 'foo' must have been null here. Click on 'foo' to find out where it was last assigned a value. Oh, it was from calling a getter on 'bar', so 'bar' must be wrong. Click on 'bar' to find out where it came from." It seems like it might be nice to not have to make a request each time I click.

Also, keep in mind that you only need this data for the active editor, so there's only one piece of data to "cache". You just need to clear it when the active editor (and hence your subscriptions) changes and store it when you get it.

**Comment by DanTup** [comment]
> not being able to know when the current set of occurrences has changed due to changes outside the file

I'm not sure I understand why something outside of the file would change this? (that's not to say I don't think it will, it just sounds like more than I was expecting - which is just highlighting a variable and all instances of it?)

>  If you have to spend time requesting data from server, and it has to re-compute it each time, it might be slower than if you have the data cached locally and can just access the piece you want

I would agree; if it needs computing then caching it in the editor seems like the best option. However I didn't expect it to, so not sure if I've misunderstood or maybe the functionality you're thinking of is better than I was (which is basically a slightly more advanced version of Codes "highlight this word throughout the document")?

> It seems like it might be nice to not have to make a request each time I click.

I would agree, but the current notification system replaces an entire files occurrences at once, so we're potentially updating a list of 500 symbols on every few keypresses and might never use the info (or might only use one). We'd also presumably need some way to index this so we can look it up quickly from an offset. For something used on-demand, this doesn't seem ideal.

That said; you're far more familiar with these things than me, so your input/suggestions are very much encouraged and appreciated! @devoncarew might also have opinions on this; he did the current implementation and probably has a reasonable understanding of both the Code functionality and the analysis server?

**Comment by devoncarew** [comment]
I think it would be nice to have a targeted request/response API for get occurences (and separately, for the outline information). It matches how some clients want to use the API.

We do have a workaround in place currently - based on the notification API - so this probably isn't a high priority. More rounding out the API, and perhaps part of (a much longer term project) to add support for the language server [protocol](https://github.com/Microsoft/language-server-protocol).

**Comment by bwilkerson** [comment]
> I'm not sure I understand why something outside of the file would change this?

Dart resolves names in the lexical scope before names in the inheritance scope. Consider:

a.dart
```
class A {}
```

b.dart
```
import 'a.dart';

class B extends A {
  int x;
}

class C extends B {
  int getX() => x; // <-- what does this resolve to?
}
```

The `x` in `getX` resolves to the `x` inherited from `B`, so clicking on either should highlight both. But if we modify `a.dart` to include this line:

```
final int x = 0;
```

then the `x` in `getX` will resolve to the top-level variable named `x` defined in `a.dart`. Hence, changing `a.dart` changed the resolution in `b.dart`. Now, if you click on either of the `x`s in `b.dart` you should only highlight the identifier you clicked on.

> ... if it needs computing ...

Server *could* cache the information, but it doesn't (primarily because of the way the protocol is currently designed. If we change the protocol then we might change that, so this was something of a non-issue (my brain just hadn't fully adjusted to the possible future).

**Comment by DanTup** [comment]
Thanks for explaining; I understand now :)

I don't know if the current implementation will be a problem; I guess we can see how it goes. If it seems to perform badly with large files we can revisit and see if caching in the editor would be better.

If you can do it well, I still think this would be a good feature, but I don't fully understand the effort involved, nor would I need to implement it! I'll leave it to you to re-open if you want it on your list.

Thanks again both!
