### ISSUE TITLE
Move HttpDate out of dart:io package

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#27071]
[HttpDate](https://api.dartlang.org/dev/1.17.0-dev.1.0/dart-io/HttpDate-class.html) can be moved out of the `dart:io` package as far as I can tell.  Feel free to close this issue if there is a good reason for it to be server-only.

**Comment by johnpryan** [comment]
I created a package to help with this issue for now: https://pub.dartlang.org/packages/http_date

**Comment by floitschG** [comment]
The IO library should not depend on any package, and since the `http_headers` in `dart:io` uses the `HttpDate` class, this would introduce a dependency on a package.

Also, the IO library is also used by the dart VM itself (to load source-files, ...). I believe that the VM currently does not depend on any package, in which case adding a new dependency would make things more difficult, too.

For now, I think that the package is a good solution (even though I feel really bad advocating for code duplication...)
