### ISSUE TITLE
Getter/setter “is used reflectively but not in MirrorsUsed” warning after dart2js compilation

### ISSUE THREAD

**Issue by snitko** [dart-lang/sdk#27074]
In my class, I have getters and setters which are working thanks to `NoSuchMethod` - that is, they're not explicitly defined. After I compile and run the js, I get the following error in the browser console:

    Warning: 'closes_in=' is used reflectively but not in MirrorsUsed. This will break minified code.

In this case, `closes_in=` is an example of such a setter and there are some other warnings related to other getters/setters too. I do have a `@MirrorsUsed` with the name of the library/class included and the resulting compiled js is actually smaller than it was without using `@MirrorsUsed` statements.

However, if a `-m` flag is passed to `dart2js`, then when the js program runs it fails - as predicted by the warning message.

Thus, I have two questions:
1. How do I write my `@MirrorsUsed` statement so that the warning goes away?
2. If it's not possible, how do I suppress the warning message? (because if it's not possible to solve the problem, then my only option would be to NOT minify the file then).

I can't find relevant documentaion for this, thus I'm posting it into the issues. Hope this is something that just needs a better explanation, rather than a fix.

**Comment by floitschG** [comment]
I'm taking a stab in the dark (missing too much context), but probably you just have to add
`@MirrorsUsed(symbols: const ["foo", "bar", ...])` on an import of `dart:mirrors`, where `"foo"`, `"bar"`, ... are the names of the fields you want to support. The example in the `MirrorsUsed` class covers this case:
https://api.dartlang.org/stable/1.18.1/dart-mirrors/MirrorsUsed-class.html

Alternatively, you should just use symbols instead of getting the string-representation of the symbol.

If you don't know the names of the members that are invoked on your class, *and* you need their string-representations, then you don't really have a choice but to run in unminified mode. Afaik, dart2js doesn't have a mode where it minifies everything but the members (which is what would be needed).

Ccing @sigmundch in case I missed something.

I don't think there is anything actionable, so I'm closing this bug for now.
