### ISSUE TITLE
Function doesn't implement toString in strong mode

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#27097]
Analyze the following in strong mode:

```dart
typedef bool Predicate<T>(T object);

void f(Predicate<int> p) {
  print(p.toString());
}
```

This should not produce any errors, but generates:

ERROR: The method 'toString' is not defined for the class 'Function'. (test.dart:19)

**Comment by jmesserly** [comment]
Probably caused by https://github.com/dart-lang/sdk/commit/efa73a440e66364abd1b278a27c245d724c760e5

Related open bug: https://github.com/dart-lang/sdk/issues/27050

What happens is element_resolver often treats any FunctionType as "Function" -- this is bad for strong mode because it leads to soundness problems and other loss of type information.

But unfortunately I don't think the system understands that FunctionTypes still inherit from "Object" and thus should support calling those methods. It is probably a simple fix to "_resolveInvokedElementWithTarget".

(Aside: in general I wish we understood better during resolution that Object methods are on anything. We have some other strong mode logic to work around this, e.g. even when the target is "dynamic" we can usuall resolve the Object methods/getters).

**Comment by jmesserly** [comment]
thanks for taking a look Leaf, let me know if I can help with any additional info :)

**Comment by leafpetersen** [comment]
https://codereview.chromium.org/2252183002/
