### ISSUE TITLE
Using `pub upgrade --no-package-symlinks` breaks package reflectable

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#27096]
Checking the status for package reflectable, I noted that many tests are failing since https://github.com/dart-lang/package-bots/commit/f582ad4a04bb2cc13604fe41274cbc8b655904e2, https://chromiumcodereview.appspot.com//2235233004. The change made in that commit is that `pub upgrade --no-package-symlinks` is used on the package bots rather than a plain `pub upgrade`.

Several other packages are affected by the same commit and not yet fixed: collection, core-elements, dart_style, googleapis_auth, http, intl, logging, mock, paper-elements, polymer-expressions, sample-pop_pop_win, serialization.dart.

In reflectable, for transformed-code tests (that is, in the 'build' directory tree) the core problem seems to be that the programs are executed using a '--packages' option, for instance:
```
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart-sdk/bin/dart \
    --ignore-unrecognized-flags \
    --packages=out/ReleaseIA32/package_copy/reflectable/test_reflectable/.packages 
    /b/build/slave/packages-linux-reflectable/build/dart/out/ReleaseIA32/package_copy/reflectable/test_reflectable/build/test/name_clash_test.dart
```
This is fine for untransformed code (e.g., running from a 'test' directory in the package root), but I suspect that it should not be done for tests in the 'build' directory tree (e.g., 'build/test/...').

Here's why:

The 'build' directory tree should be self-contained in the sense that it should be capable of being zipped into an archive and unpacked on a different host (e.g., a server). The build directory tree contains a 'packages' directory (not a symlink) with package directories and files (not symlinks), which is required for the zip/move/run scenario to work. Because of this, it is a misleading test to pass the --packages option and thus relying on a '.packages' file outside 'build', referring to files which may not be available at all in a zip/move/run scenario.

In order to run the tests in a way that tests whether the 'build' directory tree is working and self-contained, I believe that the execution should use a --package-root=.. option rather than the current --packages option for tests in 'build', in spite of the fact that --no-package-symlinks is used for `pub upgrade`.

As a side-effect, I believe that this approach wouldn't break reflectable..

**Comment by whesse** [comment]
It sounds correct, that pub build creates a package directory with actual copies of all packages under build/test and/or build/web, and we should run with that package root, instead of the .packages file.

In the long run, we want to stop using test.dart to test packages, and only use pub run test --server....
But let's fix this, definitely.  I'll make the package bots use a --package-root argument when they are running on subdirs of the build directory.

The other packages you mention were only failing on dartium tests, because the http server in test.py isn't handling .package files yet, except for two, dart_style and intl, which I have filed separate issues for.

**Comment by whesse** [comment]
This should be fixed by CL https://chromiumcodereview.appspot.com/2250303003

**Comment by whesse** [comment]
Fixed
