### ISSUE TITLE
dart2js: String.split on an empty string returns a non-empty array

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#27123]
Test program:

```dart
void main() {
        print("".split(","));
}
```

Prints `[]` in the Dart VM and in Dartium. Prints `[""]` when compiled to JavaScript.

**Comment by lrhn** [comment]
That's likely the same thing. The correct result is a list containing an empty string.
The Dart `toString` of that is `[]` (because `String.toString()` doesn't  add any quotes).

When you print it in JavaScript, are you looking at the result in a browser console? The console doesn't `toString` the result, instead it shows a representation of the actual value. Since a Dart `List` is a JavaScript `Array` and a Dart `String` is a JavaScript `String` too, you get the console representation of the JavaScript value `[""]` which shows as `[""]` in the console.

**Comment by ds84182** [comment]
Alright, I just checked what you suggested and Dart does make an array with an empty string... This is quite weird because the code I was using looked a bit like this:
```dart
element.style.animation = ((element.style.animation ?? "").split(',')
      ..add("${keyframes.duration}ms $easing ${keyframes.name} both")).join(',');
```
It may just be that Dartium has a lower tolerance for invalid CSS than Google Chrome. I'll check later today.

**Comment by floitschG** [comment]
Closing for now.

**Comment by ds84182** [comment]
Welp, Dartium strips erroneous commas from the front of CSS property values while Chrome simply ignores the property and moves on.

**Comment by floitschG** [comment]
Consider filing a new issue for this.
