### ISSUE TITLE
Future.wait([f1, f2]) does not have the correct return type

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27134]
This code has a warning `WARNING: Unsound implicit cast from List<dynamic> to List<List<A>> ([my_test] bin/test2.dart:6)`.

```dart
import 'dart:async';

foo() async {
  Future<List<A>> f1 = null;
  Future<List<A>> f2 = null;
  List<List<A>> merged = await Future.wait([f1, f2]);
}

class A {}
```

but if I extract `[f1, f2]` into a local variable, it does not have this warning.

```dart
import 'dart:async';

foo() async {
  Future<List<A>> f1 = null;
  Future<List<A>> f2 = null;
  var futures = [f1, f2];
  List<List<A>> resultsList = await Future.wait(futures);
}

class A {}
```

**Comment by jmesserly** [comment]
other workarounds, you could also put an explicit type on the list `<Future<List<A>>>[f1, f2]` or on the generic method `var resultsList = await Future.wait/*<List<A>>*/(futures);`.

but yeah, this should work. What should happen is `await` creates a `T | F<T>` downwards context, then generic method downward inference picks the `T` branch because the return type of Future.wait is a List. However I'm not sure if either of those steps are currently implemented. I'm fairly sure the second one is not.

**Comment by jmesserly** [comment]
the high level issue here is https://github.com/dart-lang/sdk/issues/25490, that downwards and upwards inference aren't unified. It's possible we push down `List<Future<dynamic>>` as the context for Future.wait's argument type. If we do that then it probably prevents the upwards ListLiteral inference that could otherwise easily figure out the list type argument (and thus, the generic method call on the way back up).

**Comment by jmesserly** [comment]
Guess above was correct. It was downwards generic method inference dropping the `Future<T>` possibility from `T | Future<T>`. Fixed in this CL: https://codereview.chromium.org/2280463002/

**Comment by scheglov** [comment]
See also https://github.com/dart-lang/sdk/issues/27151.
