### ISSUE TITLE
Suspicious line-level CPU profile information

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27152]
I cannot fathom how `thisData.visitId == id` can use `2.06%` of CPU, on a fairly large run.
This is a trivial field access, and the target class is always the same, so it must be a monomorphic access.

The same is for `int cacheLength = caches.length;` - using `3.94%` for reading `length` of a `List` - I don't believe it.

At the same time `visitor(target, thisData);` - the callback that actually does some work (not much, but it must be much more than just a field access).

![image](https://cloud.githubusercontent.com/assets/384794/17956746/e8e23c88-6a40-11e6-8e87-ea0ac52e7aec.png)

**Comment by johnmccutchan** [comment]
a) Observatory's profiler is a sampling based one. So these are percentages of samples and not CPU usage. Interpreting these numbers as time or CPU usage is incorrect.

b) The first column represents inclusive percentage of samples not exclusive so the 3.94% is the percentage of samples where this function was waiting for a callee to complete. It would also be ticked waiting for a GC or compilation to complete.

c) The source profile blurs unoptimized and optimized code for the function. They have different performance characteristics and in unoptimized code some "fast" operations still require transitioning from Dart to C and back. 

d) The PC -> line mapping is approximate and there is room for improvement. I suggest you create a reproduction that demonstrates a bad PC -> line mapping -- I can then look at the disassembly and see what source lines the compiler attributed to each code address and then I can fix the compiler so that it properly tracks the line number for that code block. 

Consider the "2.06%" line, what is happening on this line is:

we load the local for id
we load the local for thisData
we invoke the getter for visitId
we test for equality
we branch based on the result of the test

There may also be register spills / copying to/from the stack / class id checks / other compiler backend stuff that is attributed to that line because it is part of the machinery of evaluating the expressions, comparing them, and branching.

**Comment by scheglov** [comment]
Yes, I understand that it's a sampling profiler. But this means that statistics might shift or be not quite exact on a small number of runs. In this case the method is a hot one, it is executed many thousand times, maybe a million times. And statistics always have the same pattern, with high time associated with lines that IMHO cannot use much time, as I think after looking on code of other methods.

[method_code.pdf](https://github.com/dart-lang/sdk/files/437438/method_code.pdf)
[method_statistics.pdf](https://github.com/dart-lang/sdk/files/437437/method_statistics.pdf)
