### ISSUE TITLE
Consider adding a means to turn on default lints with an analysis option.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#27189]
The analyzer supports a default set of lints with the `--lints` flag.  We should consider a means to flip this bit with `.analysis_options` as well.  (See https://github.com/flutter/flutter/pull/5573 for discussion.)

**Comment by bwilkerson** [comment]
FWIW, I think support for lint groups is the better way to do this. We could have a single solution that would satisfy all of the known use cases instead of multiple solutions that overlap and conflict. The `--lint` option could be extended to take a group, and if none is given could default to the "default" group.

**Comment by pq** [comment]
Closing in favor of ongoing discussions of "meta-lints": https://github.com/dart-lang/linter/issues/288
