### ISSUE TITLE
observatory - persistent_handles_page test Fail in FF

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#27187]
@johnmccutchan @B3rn475 

Feel free to close this bug if you don't intend to fix this. I just wanted to let you know that I marked an observatory test as failing in FF. I was cleaning up the bot status files to get the bots green again (mainly triaging some dart2js failures now that we are testing --fast-startup), but while I was at I ran into your test failure. Here is the commit where I updated the status file:
https://github.com/dart-lang/sdk/commit/f6680d13a2ad1a19049333f123b6073e2d3542a1#diff-30b422238f48b187d8548ae36b557b90R49

**Comment by B3rn475** [comment]
I think that we can try a more drastic approach.
I see that the main failures during --fast-startup are due to custom components.
Due to the fact that all of our tests use custom components I think that we can disable all of them if fast-startup is set.
What do you think about this?

For what concerns persistent_handles_page it is having the same problem of allocation_profile and cpu_profile_table, disabling it on FF and Safari is Ok.

**Comment by B3rn475** [comment]
https://github.com/dart-lang/sdk/blob/8e7725a8b4dfbf758cbaecb1db05ce4b73dcaf41/runtime/observatory/tests/observatory_ui/observatory_ui.status

**Comment by sigmundch** [comment]
Sorry I was out on an errand and didn't get to reply sooner.

So our plan is to add support for custom-elements to the fast-startup emitter soon, once we do I think we probably want to re-enable these tests (or keep them enabled and marked as failing at this time). I am thinking that eventually observatory might prefer to use it over the default emitter. The typical trade-off with this emitter is startup speed vs code size. Since observatory is shipped with the SDK, I think the code-size is less of a concern.

**Comment by B3rn475** [comment]
I think that by now keeping the bots green is a priority, when fast-startup will support custom elements we will think about enabling it for Observatory and if so we will enable the tests again.
