### ISSUE TITLE
DoubleLinkedQueue does not throw if modified while iterating

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27183]
Test co19/LibTest/collection/DoubleLinkedQueue/DoubleLinkedQueue_class_A01_t01.dart fails because the subtest LibTest/collection/Queue/removeWhere_A02_t02.test.dart fails to throw, when it runs with a DoubleLinkedQueue.

**Comment by whesse** [comment]
Suppressed in tests/co19/co19-co19.status

**Comment by lrhn** [comment]
Not throwing on concurrent modification isn't necessarily a bug. That's always a "best effort" approach. 
I'll look at the test and see if it's OK.

**Comment by lrhn** [comment]
I don't actually see a LibTest/collection/Queue/removeWhere_A02_t02.test.dart in the Dart repository after doing `gclient sync`. Do you know where I can find the file?

**Comment by floitschG** [comment]
The co19 tests haven't been rolled yet.
You have to go to the original repository:
https://github.com/dart-lang/co19/blob/master/LibTest/collection/Queue/removeWhere_A02_t02.test.dart

I agree with Lasse: throwing is best-effort and not guaranteed.

**Comment by lrhn** [comment]
I've looked at it, and `DoubleLinkedQueue` only throws if its current element is removed from the list, otherwise it continues to iterate.

That is acceptable behavior - we don't throw concurrent modification errors because we want to, but because not throwing would require us to return do something inconsistent instead.
Iterating an iterable shoud
- Give the same result every time if the underlying object hasn't changed.
- Should not produce any element that was removed before iteration started.
- Should not produce any element that wasn't in the object at some point during iteration.
- Should produce all elements that were in the object during the entire iteration. 
- Must not produce any element more than once.
(An "element" is whatever the underlying object/collection thinks it is, so a List can have two "elements" with the same value, a Set cannot).

If we think we can't satisfy this requirement, we throw. We don't *guarantee* anything, we just use a "best effort" approach with minimal overhead to detect some common cases.

That is why we throw when a `List` changes length. We think of lists as maps from integer positions to values, with each index being an element, but we also think of an "insert" operation as *moving* elements, not just adding indexes at the end and updating all the values. So if a length change was due to an "insert" operation, and we might produce the same element twice if we continue iteration from the same position. If it was a remove operation, we might skip elements. If you just sort the list, we do think of it as keeping the elements and updating the values. We don't actually know if the length change was due to an insert or an `add` at the end. The latter would be fine, but we don't know because we just remember the length (minimal overhead, sufficient to detect a single insert operation). We could do more complex stuff instead, like a dirty-flag incremented by insert/remove operations (and any other operation that might cause problems), but not by `add` and `removeLast`. It's just not worth it - the general rule of "don't modify during iteration" is sufficient if people follow it, and if not, we might catch it. Or not.

For the double-linked queue, it will only produce elements that are in the list at some point during the iteration, it will report all elements that are in the queue during the entire iteration, and it will only report each element once.
In fact, anything added after the `current` element will be found by iteration, anything added before `current` won't. Just don't remove `current`, and you are safe. (Or is it `current.next` that we remember, I haven't checked, that would allow you to remove `current` which can be useful in some cases).

In any case, the point where it throws is where it can't complete the iteration because its pointer into the structure goes stale, and it can't continue, so it might fail to produce some elements. That is bad, so we throw.

All in all, the iteration is working as intended, the problem is the test assuming that a particular modification triggers a concurrent modification error.

**Comment by peter-ahe-google** [comment]
The test is still suppressed and tagged with this bug number in the status file.

**Comment by whesse** [comment]
To close this, you would have to file a co19 issue to change the test, link to this issue, and replace the issue number in the status file with the co19 issue.  Then you could close this, or you could wait until the co19 issue is fixed and the fixed version is rolled in DEPS, to close it.

**Comment by lrhn** [comment]
The co19 test has been updated.
