### ISSUE TITLE
Have a way to exclude fields from release builds

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27193]
There are a lot of debug-only fields in Flutter's framework. We'd like to be able to annotate them such that the compiler knows to never include them at all in release builds.

These fields are always unused in non-debug builds. It's possible the compiler is already optimising them out. However, it would be nice to have an explicit way to say "if this is used in a non-debug build, it's an error", so that we can be guaranteed that the fields aren't in fact included.

This can also affect profile builds vs release builds, see e.g. https://github.com/dart-lang/sdk/issues/27192

**Comment by lrhn** [comment]
I don't particularly like `#ifdef` programming. It makes it very hard to reason about the actual program.

Dart has configurable imports, and I believe it should be possible to do imports depending on whether you are in checked mode or not.
In Strong Mode/Dart 2, there won't be a production mode and a checked mode, so there will likely just be an "asserts enabled" flag, but then you should be able to do imports based on that too.

Using that for individual fields would require moving parts of a class into a separate library (e.g., as a debug mixin that is either empty or not), but I think it should be doable. Possibly even automatable using code generation based on annotations.

**Comment by floitschG** [comment]
I doubt that we will add more support than configuration-specific imports.

Alternatively, we could think of an annotation that is used during release builds to check if the field really is not used. That is, put the burden on the tools and not the language.

For example, --dump-info would be a good candidate for checking that code has been removed. Currently, --dump-info is only a dart2js feature, but the native compilers could/should eventually have similar easy-to-parse information files.

Closing for now, since we don't intend to change the language.
/cc @mraleph @asgerf

**Comment by asgerf** [comment]
I've been thinking of the possibility of a `@debug` annotation, which could work a bit like const correctness in C++. A method without the `@debug` annotation would only have restricted access to methods and fields marked with `@debug`, similar to how a const method cannot call a non-const method in C++.

In release, then strip out everything marked with `@debug`. The difference can still be observed using dynamic calls, mirrors, or noSuchMethod, and we'll just have to live with that. The analogy to const correctness is that because the main method is const (non-debug), you can never call a non-const (debug) method without cheating - Dart is just a bit too dynamic to actually guarantee this.  And this dynamicness is exactly why tree shaking cannot always be trusted to get rid of the debug fields automatically.

With the kernel IR, it's the sort of thing I'm hoping we could do as a package-provided IR transformer so we wouldn't need to specify it in the language. Package-provided IR transformers are quite a way off into the future, but maybe we could do a prototype just for flutter if someone has the time.
