### ISSUE TITLE
No callback called on close for StreamController w/o subscription

### ISSUE THREAD

**Issue by ilyaklyaus** [dart-lang/sdk#27203]
https://dartpad.dartlang.org/1595edf7439a8ec62e7c5f2b48813203

Happens in VM as well

**Comment by floitschG** [comment]
This seems to be a documentation issue...

On the `_StreamController` class (internal) the documentation for `close` reads:

> The returned future is completed when the done event has been delivered.

In your example, nobody has listened to the stream yet, so Since nobody has listened to the stream yet, the future isn't completed either.

If you add the following code at the end of `main` the future is completed:
```
  Timer.run(() {
    sc.stream.listen(print);
  });
```

We should copy that documentation to the `StreamController` interface.

**Comment by natebosch** [comment]
Closing as a duplicate of #19095 since that one has more context.
