### ISSUE TITLE
A way to mark try-finally blocks as checked-mode-only

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27274]
It would be nice if there was a way to indicate to the AOT compiler that a particular try-finally block could be ignored (running the try and finally blocks without exception handling) in release builds, trading performance for resilience. Many try-finally blocks in Flutter's codebase are only actually intended to help debugging in debug builds.

**Comment by fsc8000** [comment]
The VM should be able to make empty finally blocks zero-cost. Right now, there is always a cost for try-finally.

For example,
```
try {
  do_something();
} finally {
  assert(expr);
}
```
should equivalent to just calling do_something() in unchecked production mode. Is that a pattern that matches what you're seeing?

**Comment by Hixie** [comment]
we see that as well, but in this case what is debug-only is the throwing of the exception, such that in release builds we don't care about the exception handling (or rather, we care more about perf).

The pattern then is:
```dart
   flag = true;
   try {
     workAffectByFlag();
   } finally {
     flag = false;
   }
```

We care about the exception handling in checked mode so that e.g. hot reload can recover from an exception and find its flags are still in a coherent state, but in release builds we'd be happy just having:

```dart
   flag = true;
   workAffectByFlag();
   flag = false;
```

**Comment by fsc8000** [comment]
I see. Seems, there are two orthogonal issues here:
1. the finally is actually empty (e.g. in production mode, and only contains assert statements)
2. the finally can be ignored in production mode because the exception is not useful in production mode

I landed a fix for (1) 

(2) Seems is more difficult - similar to issues #27192 or #27193 - conditionally including/excluding code from the program. I guess it could already be achieved with code duplication and the unwieldy ```if (const bool.fromEnvironment("PRODUCTION")```, but I'd really like to "fix" this by making try/catch/finally faster in general instead.

**Comment by fsc8000** [comment]
Re-labeling this as a language issue. There is nothing VM-specific we can do, except reducing the overhead of try-catch to as close to zero as possible (which is a separate issue). The case of empty try-finally is already fixed with the CL above.

**Comment by lrhn** [comment]
If you rewrite as:
```dart
flag = true;
try {
  workAffectedByFlag();
} finally {
  assert(() { assert = false; return true; });
}
```
it should make the finally code only run when asserts are enabled.

I don't think it's practical to make control flow operations dependent on whether asserts are enabled or not. Asserts should exactly not change anything outside of the assert. Having two different control flows is too big a change between assert/non-assert mode. 

(In Dart 2, there won't be a checked mode, but there will probably still be an assert-enabled mode, so this is still a relevant question).

**Comment by fsc8000** [comment]
Note that in the original code, the flag would still be reset even in unchecked mode as long as there is no exception. You'd need to add the opposite of ```assert``` to express this - reset the flag outside the finally, but only in unchecked mode.

**Comment by lrhn** [comment]
True, it wasn't clear to me what the intent was, but if you want to clear the flag and you assume that the function call won't throw when not developing, then you need something like.
```dart
flag = true;
try { 
  workAffectedByFlag();
  flag = false;
} finally {
  assert(!(flag = false));  // For development only, should not throw unless there is a bug.
}
```

**Comment by floitschG** [comment]
Alternatively, you could try to use `withX` functions:

``` dart
withFlag(() {
  workAffectByFlag();
});

void withFlag(f) {
  flag = true;
  try {
    f();
    flag = false;
  } finally {
    assert(!(flag = false));
  }
}
```

I think that this currently wouldn't be inlined (because of the try/catch), but that's something we could work on.
Obviously, this wouldn't work nicely, if you have lots of different flags, or if the try-body wants to do `return`, `break` or `continue`.

Otherwise, I agree with Lasse: having `assert` influence the control flow is something we currently don't want to do.

**Comment by Hixie** [comment]
In release mode, will these two code snippets compile down to the same thing?:
```dart
flag = true;
try { 
  workAffectedByFlag();
  flag = false;
} finally {
  assert(() { flag = false; return true; });
}
```
```dart
flag = true;
workAffectedByFlag();
flag = false;
```

In practice, sometimes the "flag = false" part is really several lines of code with side-effects, so duplicating them isn't really practical, but if the above snippets do compile down to the same then that certainly makes it less of an issue.
