### ISSUE TITLE
Boolean conversion for strong mode

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27277]
`if (null) {}`
This code produces no issues in dartanalyzer strong mode and with --no-implicit-casts. Is this intended? Shouldn't it be (for strong mode) an error in analyzer and a compile error in vm?

**Comment by lrhn** [comment]
No, sadly not.
You get a static warning if the value isn't assignable to `bool`, but since `null` is assignable to anything, there is no error. In checked mode the code will at runtime, in production mode it will treate `null` as `false` and run. 

That's one more reason to add non-nullable types, so we can require that conditions are non-nullable `bool`.

**Comment by jmesserly** [comment]
> That's one more reason to add non-nullable types, so we can require that conditions are non-nullable bool.

+1!

@sgrekhov we could perhaps fix this particular example. It is rather interesting in that this one is an error with `--no-implicit-casts`
```dart
main() {
  var x = null;
  // [error] Conditions must have a static type of 'bool'
  if (x) {}
}
```
Dart 1 has a "the type of `null` is bottom" rule that probably confuses things, which is why your initial example doesn't report an error, but the one above does.

**Comment by jmesserly** [comment]
we probably can't fix this until we have non-nullable types.
