### ISSUE TITLE
No compile error if evaluation of compile time constant causes an error

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27278]
According to the Dart specification (4-th edition, December 2015) 16.1 Constants

> It is a compile-time error if an expression is required to be a constant
> expression but its evaluation would raise an exception.

But the following code produces no error in dartanalyzer and only runtime error in vm

``` dart
main() {
  const m = 1 % 0;
  print(m);
}
```

There should be a compile error.

Tested on Dart VM version: 1.20.0-dev.1.0 (Tue Aug 30 01:45:01 2016) on "windows_x64"
dartanalyzer version 1.20.0-dev.1.0

**Comment by lrhn** [comment]
Correct.

I actually think the VM is behaving correctly - it just reports the compile-time error as an uncaught `IntegerDivisionByZeroException`. If you check it, it doesn't actually execute any code prior to the const declaration in the function, and you can't catch the error (yet, since catchable syntax errors is being worked on).

**Comment by natebosch** [comment]
The analyzer has a really weird error on this code:

`A value of type 'double' can't be assigned to a variable of type 'int'.`

Why does it think the variable is typed int?

**Comment by lrhn** [comment]
Because the static type of `1 % 0` is int. The specification says:

>The static type of an expression *e<sub>1</sub> % e<sub>2</sub>* where *e<sub>1</sub>* has static type `int` is `int` if the static type of *e<sub>2</sub>* is `int`, and `double` if the static type of *e<sub>2</sub>* is `double`.

It's more surprising that it thinks the result is a `double` when it should be a run-time error (and hence a compile-time error because the run-time error occurs in a required const expression).
I'm guessing the analyzer gets infinity or NaN as result instead of catching the division by error.

**Comment by lrhn** [comment]
It's also interesting that the VM still exposes compile-time errors at run-time. The constant evaluation is generally deferred from the common front-end to the backends because it depends on the integer semantics and the available `String.fromEnvironment` values. The VM is then further deferring that until a function is first called. If the function contains a constant error, then the call throws, and the compile-time error can be caught at run-time.
This makes it even more important that the analyzer catches all compile-time errors since running the program on the VM might not expose them all.

**Comment by srawlins** [comment]
Now the analyzer simply reports the correct error:

```
Analyzing 27278.dart...
  error • Evaluation of this constant expression throws an exception. • 27278.dart:2:13 • const_eval_throws_exception
1 error found.
```

(There are other issues open regarding the UX of this message, but at least it is reported.)
