### ISSUE TITLE
Inconsistency between type inference and implicit argument casts.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#27280]
Note that this is not a request for a change, but just a note that we have a potential inconsistency.

Look at the code below.

Analyzer complains that `ERROR: Could not infer type parameter T, dynamic must be of type num. ([analyzer] bin/test.dart:6)`. This is perfectly understandable, we might require that all types we use for inferencing `T` must be at least compatible with `T` bound.

But at the same time, when we call a non-generic method, which also requires that the second argument must be `int`, we are find with it.

```dart
class C {
  var f;

  foo() {
    if (f is String) {
      bar(0, f.length);
    } else {
      // assume 'int'
      [0, 1, 2].sublist(0, f);
    }
  }

  bar/*<T extends num>*/(num/*=T*/ a, num/*=T*/ b) {}
}
```

@keertip @bwilkerson @jmesserly

**Comment by jmesserly** [comment]
yeah. I think this is an intended result of the "could not infer is an error" change, but Leaf can confirm :)

fwiw, we also want to error on the implicit cast, so it will be ... eventually consistent :)

**Comment by jmesserly** [comment]
also, regardless of inference, we issue an error if you explicitly tried to use dynamic. Don't even need generic methods:
```dart
class Foo<T extends num> {}
bar/*<T extends num>*/(num/*=T*/ a, num/*=T*/ b) {}

main() {
  // [error] 'dynamic' does not extend 'num'
  bar/*<dynamic>*/(1, 2);
  // [error] 'dynamic' does not extend 'num'
  Foo/*<dynamic>*/ f;
}
```

**Comment by leafpetersen** [comment]
I don't immediately see a good way in general to end up with the property that you would want here.  It would maybe look something like treating the constraints as assignability constraints rather than subtyping constraints, at which point I think you would end up working over disjunctions of constraints (`T <: SomeType | T :> SomeType`), which seems like it's bumping up the complexity.  It's possible it could be worked out.  I'm not sure that I see this as a path worth chasing down, but interesting example.

We could filter out arguments of type `dynamic` from contributing to upwards inference, much as we do with downwards inference, which I think would address this specific issue.  Not sure how I feel about that - in some ways it makes sense, but it means that if you change the type of `f` to `Object` above you'd get an inference error that you wouldn't get with `var`.

**Comment by keertip** [comment]
@srawlins

**Comment by keertip** [comment]
@jmesserly , @leafpetersen  so how do we move forward on this one? Seeing a number of failures in internal code due to this error.

**Comment by jmesserly** [comment]
@keertip -- if inference fails, you can use explicit type args: `bar/*<num>*/(0, f.length);`

you can also help inference out with an explicit cast: `bar(0, f.length as int)`

or add a type to `f` so it's not dynamic.

**Comment by jmesserly** [comment]
going to close for now as I believe this works as intended. Definitely feel free to summon us on internal code though if we can help figure out how to make it error free

**Comment by scheglov** [comment]
Thank you, John.
The intention here was not learn how to fix the code, but mostly to let you know about what looked for us as an inconsistency. If we're going to make rules consistent, even eventually, that's great :-)

**Comment by keertip** [comment]
Thanks John!

**Comment by jmesserly** [comment]
@jacob314 hit this as well
