### ISSUE TITLE
generic method downwards inference doesn't preserve future-unions

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#27284]
Please forgive my terminology in the title, and correct as needed.

Here's an example:

```dart
import 'dart:async';

/*=T*/ x/*<T>*/(/*=T*/ f()) => f();

main() async {
  Future<String> c() => new Future<String>.value('Hey');

  // Srtong mode error here.
  String s = await x(c);
  print(s);

  // But not here.
  Future<String> temp = x(c);
  String s2 = await temp;
  print(s2);
}
```

Here's analyzer output:

```
$ xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --strong b.dart
Analyzing [b.dart]...
[error] Could not infer type parameter T, Future<String> must be of type String. (/Users/srawlins/code/dart-repo3/sdk/b.dart, line 9, col 20)
[error] The argument type '() → Future<String>' cannot be assigned to the parameter type '() → String'. (/Users/srawlins/code/dart-repo3/sdk/b.dart, line 9, col 22)
2 errors found.
```

So analyzer says "Hey `x` is going to return the same type as `c` (`Future<String>`), but you're assigning to String. Boo."

This is at this code: https://github.com/dart-lang/sdk/tree/e976e692be5fcd33a69d11269d9b0d59f14d2838

**Comment by keertip** [comment]
@jmesserly , @leafpetersen

**Comment by jmesserly** [comment]
(btw, I'm subscribed to analyzer-strong-mode so I'll see them once tagged)

what is going on here:

`await` induces a `T | Future<T>` union type, but our inference is intentionally limited for those (because Dart doesn't really have union types). So when we try to infer the generic type arg for `x` we have to make an arbitrary choice.

I'm not sure we can do much better here, given current constraints in the language (no union types), and https://github.com/dart-lang/sdk/issues/25490 which is not implemented yet. In general inference isn't going to be 100% of all generic methods, as cool as that would be :)

My best idea for this is: we *could* let the future-union into the inference system (_StrongInferenceTypeSystem) for the upper bound. But we'd have to be careful to "collapse" it to one of the alternatives before we finish, and when we GLB it with other upper bounds.

Another possible fix, if the language changed to have "await" require a Future argument, we can simplify away the future-union entirely.

**Comment by srawlins** [comment]
Interesting. I'm happy to let this close if that's the only possible action today (and I'm happy to leave open for others).

I'll note though that the workaround doesn't look great. If I stumbled across `Future<A> fa = x(); A a = await fa;`, I would thoroughly furrow my brow.

Looks like the union types issue is #4938.

**Comment by leafpetersen** [comment]
Interesting example.  Unfortunate that the right choice is completely constrained by the argument but that we don't find it.   It's not out of the question that unifying upwards and downwards inference could fix this, since we wouldn't need to commit to one or the other choice from downwards inference before considering the parameter.

**Comment by jmesserly** [comment]
oh yeah definitely leave this open. It's a neat example :)

As Leaf says it will likely be fixed, or made a lot easier to fix, by unified upwards+downwards inference (#25490 that I linked earlier). Or we may attack as a one off. It is a shame that we don't prefer the "Future" choice given an `await` context. Future is a much more useful thing to await (I'm not a fan of `await 42` personally :) )

> I'll note though that the workaround doesn't look great. If I stumbled across `Future<A> fa = x(); A a = await fa;`, I would thoroughly furrow my brow.

There are a few other ways around this:

1. explicitly pass the generic method type args: `String s = await x/*Future<String>*/(c);` the comments will go away soon too.

2. use var on the left side: `var s = await x/*Future<String>*/(c);`

**Comment by jmesserly** [comment]
this happened again in https://github.com/dart-lang/test/pull/469/files

**Comment by jmesserly** [comment]
This bug is hit a fair amount. I'll take a shot at a fix.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2425143002/
