### ISSUE TITLE
Function type parameter upcasts are incorrectly treated as downcasts

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/sdk#27381]
When you typedef a function type then try to assign one instance of the function to another with a different parameter type, you get an unsound implicit cast error even when the the cast appears to be an upcast.  See the following code for an example:

```
typedef R FunctionType<R, P>(P input);

class CustomClass {
  String name;
  hi() { print ("hi, I'm $name");}
  CustomClass(this.name);
}

void main() {
  FunctionType<CustomClass, String> builder = (String input) => new CustomClass(input);
  FunctionType<CustomClass, Object> f2 = builder; // analyzer error here
  f2("matt").hi();
}
```

Error from analyzer:
11: Unsound implicit cast from (String) → CustomClass to (Object) → CustomClass [STRONG_MODE_DOWN_CAST_COMPOSITE]

**Comment by lrhn** [comment]
The analyzer is correct.

You are assigning a value of (static) type `(String)->CustomClass` to a variable of type `(Object)->CustomClass`. That is indeed a down-cast. It is not a *safe* cast because follow-up code could safely call an `(Object)->CustomClass` function with an integer, and your `String`-expecting function can't handle that. 

It's a little confusing because the function type is described using a generic typedef and generic *class* types are covariant in the type parameters (a `List<int>` is-a `List<Object>`). Function types don't work that way, they are entirely structural. The type system doesn't compare `FunctionType<CustomClass, String>` to `FunctionType<CustomClass, Object>`, it directly compares `(String)->CustomClass` to `(Object)->CustomClass`, and the latter is a subtype of the former, not the other way around.
