### ISSUE TITLE
Can't do bit-wise operations on Booleans.

### ISSUE THREAD

**Issue by indiealexh** [dart-lang/sdk#27396]
Take the following code:
```Dart
bool val1 = true;
bool val2 = false;
bool result = val1 ^ val2;
```

The above quite logical code would throw: 

> Unhandled exception:
> Class 'bool' has no instance method '^'.

As a result to be able to xor booleans together I have to do the following:

```dart
main() {
  bool val1 = true;
  bool val2 = false;
  bool result = xorBool(val1,val2);
}

bool xorBool(bool item1, bool item2) {
  var xorValue = (item1?1:0) ^ (item2?1:0);
  return (xorValue==1?true:false);
}
```

This seems seriously in error considering in JavaScript, Java, C# etc I can directly do bit-wise operations against a Boolean value.

Or as someone else pointed out `(val1 != val2)`

**Comment by lrhn** [comment]
The recommended solution is to use `!=` for xor on booleans.

It is possible to add `^` (and `&` and `|` as non-shortcircuiting versions of `&&` and `||`) as operators on the `bool` class, but we have so far decided not to do that.

(I'm not sure I will include JavaScript in the list of languages that define `^` on booleans because the result is not a boolean value - it's just doing numeric conversion on the operators and then integer bitwise xor on that result. That said, it does work because the result can be converted back to a boolean automatically too).

**Comment by indiealexh** [comment]
Its not a blocking problem, but coming from many languages that do directly allow bitwise operators on booleans seemed like an odd decision.

What is the reasoning behind this?

**Comment by lrhn** [comment]
The original request was #1080. The reasoning was that it could be confusing to have `&` do one thing on integers and another on bools.
