### ISSUE TITLE
content shell failing on Travis with  1.20.0-dev.7.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27418]
stdout:	content_shell: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by content_shell)

https://travis-ci.org/dart-lang/test/jobs/162079680#L687

Description: Ubuntu 12.04.5 LTS

Release: 12.04

Codename: precise

**Comment by whesse** [comment]
There is an existing issue filed on this.  You have to use a trusty Travis image, not a precise one.

**Comment by kevmoo** [comment]
I thought we did the dance with this last milestone and went back to the older GLIBC version.

Did we go back to the new one?

**Comment by whesse** [comment]
Yes, we did go back, so it may be a sign of something broken that content shell is now needing 2.18.  But other travis users are compiling the SDK themselves, so they need to go to trusty to get at C++11 compiler.

So if it was only travis, I would say to go to trusty.  But we didn't intend released builds to have the higher libc yet - I'll look into it.  But you should use trusty on travis.

**Comment by kevmoo** [comment]
Sadly, if we go to trusty on travis our builds will get A LOT slower.

It feel really weird that this just changed – should investigate, me thinks.

**Comment by kevmoo** [comment]
@whesse updates here? This will bork us on Travis for 1.20

**Comment by whesse** [comment]
Yes. I'll fix this. Fixed other things today.

**Comment by whesse** [comment]
The 32-bit builds of dartium, content_shell, and chromedriver are all from Precise 12.04, so they should work fine.  The 64-bit build is being built on a Trusty machine, so that is where the new glibc requirement is coming from.  Can you use 32-bit content_shell for your testing?
You can even use 32-bit dartium with the 64-bit SDK, with no problem.

I would prefer not to downgrade the builders to Precise 12.04 if possible, and since our plan is to drop support for precise after the long-term support period ends next spring, I think the current setup is OK.  The SDKs are built on trusty, using a sysroot, but that would be harder to make work for a dartium build.

**Comment by mit-mit** [comment]
Per release meeting discussion: It would be preferable to stay with Precise for Dart 1.x and then make the upgrade once we get to Dart 2.

**Comment by whesse** [comment]
Verified that the dartium 64 builder is again producing builds with only a 2.14 glibc requirement.  Will wait until we publish a dev build that works on travis before closing.

**Comment by kevmoo** [comment]
Verified fixed in 1.20-dev.10 – on travis!

**Comment by a14n** [comment]
https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/

>We are super happy to announce the open public beta of container-based Ubuntu 14.04 "Trusty" job execution, which may be used by ensuring the presence of the following fields in one's .travis.yml:

>```
sudo: false
dist: trusty
```

**Comment by a14n** [comment]
See also https://github.com/travis-ci/travis-ci/issues/5695#issuecomment-259221773

**Comment by kevmoo** [comment]
Just tried this w/ the AngularDart repo

https://travis-ci.org/dart-lang/angular2/builds/174294337

It seems we don't get backward compat – so we need to decide if we're going to jump all the way in.
