### ISSUE TITLE
Buildbots not observing .packages for Observatory

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#27412]
One Safari bot is red due to this problem.

@johnmccutchan 

FAILED: dart2js-safari release_x64 observatory_ui/vm_connect/element_test
Expected: Pass 
Actual: CompileTimeError
Unexpected compile-time error.
CommandOutput[dart2js]:

stdout:
runtime/observatory/lib/app.dart:21:1:
Error: Can't read 'package:usage/usage_html.dart' (Error reading 'third_party/pkg/usage/lib/usage_html.dart'  (No such file or directory)).
import 'package:usage/usage_html.dart';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by johnmccutchan** [comment]
@whesse Observatory's packages are sealed in //third_party/observatory_pub_packages and the Observatory source has a .packages file that points into that directory. We need the bots to respect this.

**Comment by whesse** [comment]
My plan for addressing this is to:
1) Make sure the --packages flag to test.py works perfectly for all suites, including observatory, when specified explicitly (giving the .packages file).
2) Make a default setting for it which is [sdk]/.packages.  This has also been asked for from others, because when intelliJ makes extra .package files all over, it breaks things.
3) If the suite being tested is in observatory, make the default the observatory .package file.  We can do this internally to test.py, making a separate "configuration" object for the observatory suite.  The package spec is not global to test.py, but specific for each configuration object, so we should be able to treat one suite differently from others.

**Comment by johnmccutchan** [comment]
Sounds like a reasonable plan

**Comment by whesse** [comment]
All parts of this plan have been carried out in CL https://codereview.chromium.org/2361813003/

I have detected a failure when the .packages file in the root of the checkout is deleted, and one from somewhere completely different is used - some dart2js compilations seem to not get the flag.
But as long as .packages remains at the root, adding the extra --packages flag works, and fixes the issue in the case of observatory_ui tests.

**Comment by johnmccutchan** [comment]
Thanks Bill!

**Comment by whesse** [comment]
Tests are now failing because the package spec runtime/observatory/.packages is not checked into the repo.  Most of our testers do not build anything, but instead download the SDK, and run tests using that.  Since the actual packages for observatory are checked in and downloaded from the cloud to a fixed location, I think the .packages file should be checked in, rather than generated.  That is what we switched to for the main repo, and I think it makes things much simpler and better.  Could you do that for observatory?  Just run a build, check in the packages file, and remove the step that generates it from the .gypi and BUILD.gn files.

**Comment by whesse** [comment]
We can even just check in the .packages file, and leave the step that overwrites it - I'll send a CL.

**Comment by johnmccutchan** [comment]
This can now be closed right?

**Comment by whesse** [comment]
The one final problem is that Safari cannot test browsers with test.py with more than one configuration.  So the configurations will be listed separately in the dart2js-nobuild recipe.  Making a CL now.

**Comment by whesse** [comment]
Removing the step that updates .packages from the GYP build in https://codereview.chromium.org/2370773002

Removal of the step from the GN build is listed as separate issue #27427
