### ISSUE TITLE
Support Web Components v1

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/sdk#27445]
The `dart:html` library should deprecate the current v0 specifications of Custom Elements and Shadow DOM and move to using v1 of both specifications.

**Comment by donny-dont** [comment]
DDC related issue https://github.com/dart-lang/sdk/issues/27311

**Comment by donny-dont** [comment]
@floitschG anything to follow for this? Chrome 54 shipped and comes with the v1 specs enabled.

**Comment by kevmoo** [comment]
@donny-dont there are a *LOT* of things we need to fixup in `dart:html` – we're holding off until DDC is locked and loaded. It'll be *much* easier to get everything working when our dev story is 100% javascript.

**Comment by kulshekhar** [comment]
> when our dev story is 100% javascript

I'm not sure I understand this. Could you please add some more info. Is it JS compatibility you're referring to or the possible inclusion of javascript specific tools in the build step, along with DDC?

**Comment by zoechi** [comment]
@kulshekhar the problem is the Dart VM in Dartium where during development some Dart code is directly executed by the Dart VM in Dartium  but other stuff runs in JS land. 
With Bazel and DDC they are working on building a developer story with fast edit-reload cycles with standard Chrome (without a Dart VM being involved) to simplify interop between the Dart code (transpiled to JS) and the native JS world.

**Comment by kulshekhar** [comment]
Thanks @zoechi 

That makes sense now :sweat_smile:

**Comment by eukreign** [comment]
Any updates on this, we're in 2017 now :-D

**Comment by matanlurey** [comment]
I imagine there won't be any progress on this until Dart 2.0 rolls out completely removing Dartium.

I'd check back in a few more months, or use JS interop to "build your own":
https://pub.dartlang.org/packages/html5

**Comment by eukreign** [comment]
Who's still following this issue in 2018? Sorry, couldn't resist. Maybe 2018 will be the year Dart finally gets Web Components v1!

**Comment by kevmoo** [comment]
We're in the process of updating our `dart:html` APIs – https://dart-review.googlesource.com/c/sdk/+/24501

That roll – and getting rid of Dartium – should make it easier to support the latest Browser features.

Having said that, our primary framework – AngularDart – is not using WebComponent features, so it's not a big priority for us.

My suggestion: once we've updated `dart:html` and friends, let us know specific APIs that are missing/broken

**Comment by elmcrest** [comment]
That's really sad.
In my mind a serious "community centered" effort should kind of use and depend on different independent blocks. to make the idea more clear, `AngularDart` for sure needs some stuff handling DOM and it seems sane to me to use something like `dart:html` as a basis.
so, every work from google would be contributed back to the basis and others building on top of this basis would automatically benefit - somehow like the whole OpenSource-Idea, no? ;) 

currently ` Dart` is more like: "You want to do web? Sure, use AngularDart." (Hint: AngularDart != "the web")

**Comment by matanlurey** [comment]
@elmcrest Hi Marius.

I realize and understand you are disappointed. I'm one of the TLs of AngularDart, and let me make it clear I think web components are awesome, and would love Dart to support them well. The primary take away here is _well_ though, and that will take a little bit of effort, because the current HTML libraries and browser bindings aren't well suited for this.

We could probably get some _hacky_ support quicker, but it won't be something useful to most customers. It's something we'd like to revisit after Dart2 launches, but until then - again to be very honest - it's just not a priority. We care, but we have limited time and resources, and have to use them efficiently, like I'm sure you do on your project(s) and company.

Thanks for your patience!

**Comment by eukreign** [comment]
The *entire* point of Web Components is that it's a "framework" that is built-in to browsers. You can just use it, without any extra libs or 3rd party frameworks.

AngularDart emulates many features of Web Components, why does it do that instead of just using Web Components directly?

**Comment by matanlurey** [comment]
@eukreign:

> The entire point of Web Components is that it's a "framework" that is built-in to browsers

Well, sort of. It has [yet to be supported in Microsoft Edge](https://caniuse.com/#feat=custom-elementsv1), for example, which is quite a large market segment still, and the polyfill performs quite badly. So until it works everywhere, it's not free.

> AngularDart emulates many features of Web Components, why does it do that instead of just using Web Components directly

AngularDart (and JS/TS, and React, and Vue, and Ember) all were created before web components were a thing. A lot of these framework authors have evaluated web components and found them severely lacking. Here is [one of the leads of React](https://docs.google.com/document/d/1QZxArgMwidgCrAbuSikcB2iBxkffH6w0YB0C1qCsuH0/edit), arguably the most popular framework today:

> We’re not going to use it at all at Facebook. We’re not going to build React on it because there’s a strong model difference – imperative in Web Components to declarative in React. Web Components doesn’t have an idiomatic way to define things like where events go. How do you pass data when everything is a string? We see it more as an interop layer that lets various frameworks talk to each other.
> 
> In talking to the Atom team, this doesn’t solve different framework idioms as it doesn’t have an opinion on how they relate.

Again, it's not that support will never be offered, but it's unlikely to happen in any immediate time frame. There are other APIs that are more useful for our users, like web workers, service workers, and more right now.

Thanks for understanding!

**Comment by eukreign** [comment]
@matanlurey would you also say that Dart Observatory is a simple script that would have been better written in JavaScript or TypeScript? Because that's built in Dart using Web Components V0 by Dart Team. It's in [this](https://github.com/dart-lang/sdk/tree/master/runtime/observatory/lib/src/elements) very repo.

I've also built a [fully featured spreadsheet and word-processor](https://github.com/systori/systori/blob/dev/systori/dart/lib/src/editor/editor.dart) using Dart and Web Components V0.

I understand you have to shill for AngularDart since it's your project but people do build large, complex, web applications with Dart and without using AngulartDart.

The issue is that v0 is old and more browsers support v1, but Dart has not been keeping up.

**Comment by elmcrest** [comment]
I also disagree to prefer typescript over dart for little snippets. The undefined, NaN, 0, false, null, whatever hell is one point, imports and package management still another...
Dart can really shine even for small snippets and if your build system is already setup anyway, why wouldn‘t I want to use dart for everything?
One truth tends to get hidden/ignored more and more these days: Javascript sucks! ;)

**Comment by matanlurey** [comment]
I'm locking this conversation for now since it's getting non-productive. This is something that is interesting to us, but it's not on the immediate roadmap at this time.

**Comment by kevmoo** [comment]
We don't plan to support this API in the short term. None of our core users require it and would involve substantial effort to implement it correctly.
