### ISSUE TITLE
Should async*/sync* functions allow a return type different from Iterable/Stream?

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27470]
This is the language part of https://github.com/dart-lang/sdk/issues/27468

**Comment by lrhn** [comment]
The answer is (obviously?) no.

The problem is the wording - you need to allow a subtype of `Future` to allow `Future<int>`. That shouldn't allow `MyOtherFuture`, so the wording should be tightened.

Allowing you to write `MyOtherFuture foo() async {...}` won't help anybody, only provide a pitfall.
In Dart 2.0 it would make the function not compile since it doesn't actually return the subtype.
In Dart 1 checked mode it would always throw when returning.

**Comment by lrhn** [comment]
Fixed.
The spec now only allows a supertype of `Future<T>` (for some `T`) for async functions, `Stream<T>` for async*` functions and `Iterable<T>` for sync* functions.
