### ISSUE TITLE
covariant parameters should have a wider parameter type at runtime

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27484]
Forked from https://github.com/dart-lang/sdk/issues/27353. When we have an `@checked` parameter, it is more user friendly to widen the parameter type in the tear off function. This allows it to be used in more places. It is sound because of the callee side parameter type check.

**Comment by jmesserly** [comment]
Here's an example of why the current behavior is bad:
```dart
class Base {
  m(Object x) => x;
}
class Derived extends Base {
  m(@checked int x) => x + 42;
}
typedef TakesA<T>(T x);

main() {
  Base b = new Derived();
  b.m(100);

 // but the runtime type is currently `int -> dynamic`, from Derived.m
  Object f = b.m;
  // Runtime cast failure. We could allow this.
  TakesA<Object> x = f;
  // confusingly, this would be legal.
  TakesA<Object> y = b.m;
}
```

**Comment by eernstg** [comment]
We have one more proposal on the table which is closely related: We could introduce a notion of **guarded function parameters**. Such a parameter would have an associated type check (generated by the compiler) in the body of the function. The statically known type of such a function could use _any_ type for such a parameter without jeopardizing heap soundness (type errors could occur, but they would be detected at call time rather than polluting the heap with type incorrect values); in particular, a covariant parameter could be a guarded parameter.

The point is that a guarded function would be capable of supporting precise `is` checks (so "manual" type checking would allow developers to rediscover the actual parameter types and call the function safely), and the guarded function would have a special subtype check which ignores guarded parameter types (essentially, they count as `Object` during `as` and type annotation related checks).

**Comment by jmesserly** [comment]
@eernstg oh, that's really interesting in having different `is` vs `as` behavior. I think my above proposal came from @leafpetersen but I'm happy to try implementing something else in DDC.

**Comment by leafpetersen** [comment]
I'm not sure what we're doing with functions yet.  As a general principle, I'm pretty uncomfortable with anything that gets us into the situation in which we have and `f` which has type `T`, but for which `f is T` evaluates to `false`, which I think is implied by the comment above.

I believe our current POR is to make the reified type of these covariant override parameters `Object`.

**Comment by eernstg** [comment]
Indeed: If `f` is a guarded function of type `T! -> S` (using `!` to mean "guarded") it would pass a type test for `U -> S` for all `U`, but it would only return true for `f is V -> S` when `V <: T`, i.e., when the dynamically tested argument type is actually sound with respect to `f` (which means that the guard won't throw when we pass a `V`).

One way to explain it is that the `is` test asks whether `f` "is" a function of this type, and the dynamic checks associated with type annotations and `as` expressions ask whether `f` is capable of working "as" a function of that type (which could be (1) because it has a subtype according to the standard co/contra function subtype rule, or (2) because it protects some arguments using guards, and the rest of the signature satisfies the standard subtype rule).

If you don't maintain this distinction then you can never recover the information about the actual parameter types, and then you might as well use (or let the compiler generate) a wrapper function with sufficiently general argument types (say, `Object`) in the first place.

**Comment by leafpetersen** [comment]
> If you don't maintain this distinction then you can never recover the information about the actual parameter types, and then you might as well use (or let the compiler generate) a wrapper function with sufficiently general argument types (say, Object) in the first place.

I don't think this is quite true.  Presumably you don't allow the application of something of type `T! -> S` to an argument of type `V` unless `V : T`.  This is really the key point of the flutter use cases: they want the documentation benefit at the declaration site ("this function expects a callback that accept some kind of `Event`"`), and they want some checking at the use site ("the user passed a function that expects something related to `Event`").  Just using `Object` doesn't get you that UI.

**Comment by eernstg** [comment]
In the flutter use case, and with Bob's design for obtaining a wrapper function (thus avoiding language extensions entirely), 'sufficiently general' would mean `Event`. I would expect a compiler generated wrapper function to get a similar (sufficiently but not overly general) set of argument types, based on the type expected by the syntactically enclosing expression for the function that gets wrapped.

So you should be able to obtain a wrapper function which has the "nice" type you want.

I'm just pointing out that if you wrap a `SpecialEvent -> void` function in an `Event -> void` function then (unless you have special magic in the wrapper function) you will never be able to recover information about safe invocations of that function: It would happily confirm in an `is` test that it is a `DifferentEvent -> void`, but it would still throw a type error if you pas an actual `DifferentEvent` to it. A guarded function would reveal that it is not a `DifferentEvent -> void`, but it is a `SpecialEvent -> void`.

For the static checks on applications of a function of type `T! -> S` there are no special rules: It is treated just like a function of type `T -> S`.

For higher order usage we may wish to apply the same kind of "flag obviously wrong constructs" discipline that Dart has had all the time in the shape of assignability: So an expression of type `T! -> S` can be assigned to a variable of type `U -> S` whenever `U <: T` (which is the safe direction) or `T <: U` (which is the direction that establishes the covariance that guarded functions were created for in the first place).

I believe that the higher order _dynamic_ checks (for type annotations and `as`) should ignore the guarded argument types. This allows the guarded function to be used widely (without jeopardizing soundness because "it knows how to protect itself"), and it means that we don't have to generate dynamic checks at every _upcast_ for function types (otherwise an expression of type `T -> S` could have dynamic type `U! -> S` where `U <: T`, and it might then fail to have the supertype `V -> S` where `V <: T` but `U` and `V` are unrelated).

**Comment by munificent** [comment]
Ah, so we do have an open bug for this. Getting it up to date with reality and what's left to do:

Currently, the reified type of a covariant parameter in a tear off is Object in dev_compiler. According to the latest informal spec (#28176), it should be the least upper bound of the corresponding parameters in all of the overridden methods.

So:

```dart
abstract class Inter {
  void foo(covariant int n);
}

class Base {
  void foo(covariant num n);
}

class Derived extends Base implements Inter {
  void foo(double d) {}
}
```

Here, the reified runtime type of `new Derived().foo` is `(num) → void`.
