### ISSUE TITLE
Make bottom a user-visible type

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27488]
Every now and then, we run into cases where user code would like to explicitly use the ["bottom" type](). An example from Flutter is:

``` dart
class PopupMenuEntry<T> {
  ...
};

class PopupMenuDivider implements PopupMenuEntry<dynamic> {
  ...
}

<PopupMenuEntry<LeaveBehindDemoAction>>[
  ...
  new PopupMenuDivider(),
  ...
]
```

Here, `PopupMenuDivider` can be used as a `PopupMenuEntry<T>` for any `T`, so it should ideally implement something like `PopupMenuEntry<bottom>`.

Likewise, an empty constant list is a valid `List<T>` for any `T`. Bottom also comes up if you want to define a function that is known to never return—either because it throws, exits the process, or loops infinitely.

In Scala and Swift, this type is named "Never".

For Dart, we should decide if we want to expose it or not, and, if so, what we name it.

**Comment by leafpetersen** [comment]
@sethladd @Hixie @abarth

**Comment by floitschG** [comment]
Isn't that `void`?

**Comment by leafpetersen** [comment]
No.  `void` in dart behaves more like `dynamic`, with assignability restrictions.  We could turn `void` into  bottom, but that would mean changing a number of things: most notably, `T -> S` (where S is not `void`) can no longer be a subtype of `T -> void`.

**Comment by eernstg** [comment]
I argued that `void` should be a supertype of `Object` without implicit downcasts (in order to be a black hole where everything can go in, but nothing comes out: `void foo() => whatever;` is ok but `2 + foo()` isn't). This also preserves `T -> S` as a subtype of `T -> void`.

It would be really nice if we were able to come up with another set of type rules such that `void` could at the same time be a black hole and the name of the empty type ("void" just sounds right for that purpose), but I can't immediately see how we could do that.

**Comment by floitschG** [comment]
As expected (I still wanted to push a bit) making `void` be used for bottom doesn't work (even with runtime checks, etc.).
I can see the use cases for it, but ultimately I think it's not worth the complexity.

**Comment by leafpetersen** [comment]
This example might be another motivation for this feature:  https://github.com/dart-lang/sdk/issues/27522 .

**Comment by munificent** [comment]
I'll take a stab at writing a proposal for this. ✍️

**Comment by dgrove** [comment]
@munificent Can you give an update on this?

**Comment by munificent** [comment]
I have [a full proposal](https://github.com/dart-lang/dart-lang-evolution/pull/117) that I'm discussing with the language team. I've responded to all of the feedback I've gotten so far.

I'll bring it up at next week's meeting to see if we can move it forward.

**Comment by leafpetersen** [comment]
status: We are discussing whether to add a new type or re-target `Null`.  This has some small implications for future migrations, but is otherwise fairly equivalent.  Hopefully decision this week, and then will be ready for implementation.

**Comment by alexeieleusis** [comment]
There are tests of the kind `if (reference is Type)...` wouldn't retargeting `Null` make this conditions `true`? Isn't that a breaking change? Some of those comparisons expect that if `reference` is `Null` then the condition is false. I am sure there is something I am not understanding. Could you please further explain?

**Comment by lrhn** [comment]
The `is` test is indeed special. If we use `Null` as a bottom type, it is because we interpret all other types as nullable, and if we do that everywhere then a lot of code is going to break when an `is` tests accept `null`. As a solution, we will have to treat the type in an `is` test as *not* nullable, unlike everywhere else. Like an `as` test currently checks for `null` and accepts it, and `is` test would have to test for `null` and not accept it (unless the corresponding *non-nullable* type is actually a supertype of `Null`, so `is Null` should still work)

It's annoying to have an exception, but in the short run, I don't think it's going to be a problem.
If we eventually move to explicitly nullable types, like `int?`, it means that `is` tests is one place where you should not add the `?` to get the existing behavior.

**Comment by floitschG** [comment]
Removing 1.50 milestone from this bug. We are starting with https://github.com/dart-lang/sdk/issues/28024 and will consider `Nothing` when we add non-nullable types.

**Comment by leafpetersen** [comment]
Closing this.  The change in #28024 address the original intent of this request.
