### ISSUE TITLE
Different behavior of Analyzer 1.19.1 and 1.20 in a strong mode

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27494]
```dart
import 'dart:async';

f() async => 1;

test() async {
  await Future.wait([f()]);
}
main() {
  test();
}
```
In the code above analyzer 1.19.1 (in a strong mode) finds no issues.
Analyzer 1.20.0-dev.10.0 (strong mode) reports "[error] Could not infer type parameter E, dynamic must be of type Future<dynamic>."

I'm not sure, but for me there should be no error

**Comment by bwilkerson** [comment]
@jmesserly I looked at this in IntelliJ, and it looks like we're not inferring a return type for `f`, so `f` has the type `() -> dymanic`. I would have assumed that we would have inferred a return type of `Future<int>`. Is this a bug, or is my understanding incorrect?

Independently, if we cannot infer a better type for the type parameter for Future.wait, should we be inferring `dynamic`?

**Comment by jmesserly** [comment]
CC @leafpetersen

1. We never infer return types of top-level functions. So the return type of `f` is `dynamic`. Perhaps we could do something for `async` `async*` `sync*` functions. The problem is in strong mode, you want `Future<T>` for some T, not `Future<dynamic>`. Finding T would require looking at the method body.

2. the inference error is correct. If we cannot determine a type argument via inference we issue an error, we don't implicitly use dynamic. The reason this particular one looks confusing is because `await someGenericMethod` often hits https://github.com/dart-lang/sdk/issues/27284

**Comment by jmesserly** [comment]
duping against https://github.com/dart-lang/sdk/issues/27284
