### ISSUE TITLE
Analyzer doesn't warn abstract operator in a concrete class

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27508]
Dart spec (4th edition, Dec 2015), 10.4 Abstract Instance Members

> It is a static warning if an abstract member m is declared or inherited in a
> concrete class C unless:
> • m overrides a concrete member, or
> • C has a noSuchMethod() method distinct from the one declared in class
> Object.

``` dart
class A {
  operator ==(dynamic other);
}
main() {
  new A();
}
```

No warning in analyzer in a nostrong mode and no error in a strong mode
Tested in analyzer 1.19.1 and 1.20-dev.10.1

**Comment by scheglov** [comment]
I believe there should not be any error.
`A.operator==` overrides concrete `Object.operator==`.
@eernstg

**Comment by eernstg** [comment]
The tricky point here is that 'No warning in analyzer in a nostrong mode and no error in a strong mode' implies nnbd.

In sdk_nnbd, the signature of `Object.==` is `bool operator ==(Object)` (not `Object?`). This means that we are taking the opportunity to promise developers who are writing an `operator ==` that the received argument cannot be null (this follows from the special treatment of null during evaluation of expressions of the form `e1 == e2`).

This actually makes `A` an error: It is concrete, and yet it doesn't implement its interface. Intuitively, it's because because the interface states that any object of type `dynamic` can be passed, but the implementation inherited from `Object` does not accept null. Technically it is because `bool operator ==(Object)` is not a valid override of `bool operator(dynamic)`.

So I agree that this example, assuming nnbd, should be a warning in weak checking mode and an error in strong checking mode.

Note, however, that we can't say it is because there is an abstract member declaration _D_ in a concrete class. That's no problem, as long as the member signature of _D_ is implemented, that is, there is a superclass from which a concrete implementation _D1_ is inherited, and the signature of _D1_ is a correct override of the signature of _D_.

Finally, it's worth double checking that the missing error didn't arise because the test was performed in a way where the analyzer relied on sdk when it should rely on sdk_nnbd for this error to arise?

**Comment by scheglov** [comment]
Thank you!

With NNBD SDK the current version of analyzer actually reports a compile time error.
So, I think the issue can be closed at this point.

For the issue that was open in 2016, I'm amazed by the level of precognition with which this test case was constructed.
