### ISSUE TITLE
No error in analyzer for some generics

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27556]
``` dart
class I<T> {}
class J<T> extends I<T> {}
class K extends J {}
class C implements K {}

typedef J f(J<K> i);
typedef K f_1(I<J> i);
typedef C f_2(J<J> i);

class Checker_I<T extends I<f>> implements I {
}
main() {
  new Checker_I<I<f>>();
  new Checker_I<I<f_1>>();
  new Checker_I<I<f_2>>();
}
```

dartanalyzer in a nostrong mode produces:
[warning] 'I< f_1 >' does not extend 'I< f >' 
[warning] 'I< f_2 >' does not extend 'I< f >' 

In a strong mode it produces No issues found

There should be an error in a strong mode here

Tested in dartanalyzer 1.19.1 and 1.20.0-dev.10.1

**Comment by leafpetersen** [comment]
Why do you think this is a bug?  I believe these checks reduce to asking whether `f_1 <: f` and `f_2 : f`.  In strong mode:
  - `f_1 <: f` iff `K <: J` and `J<K> <: I<J>`
      - 'K <: J' holds immediately
      - `J<K> <: I<K> <: I<J>` since `K <: J`
  - `f_2 <: f' iff `C <: J` and `J<K> <: J<J>`
      - 'C <: J` by transitivity through `K`
      - `J<K> <: J<J>` since `K <: J`

**Comment by sgrekhov** [comment]
According https://github.com/dart-lang/dev_compiler/blob/master/doc/STATIC_SAFETY.md

>  Strong mode effectively treats all standard Dart static warnings as static errors.

So if there is a warning in a nostrong mode there should be an error in a strong mode here. But there is no strong mode error

**Comment by eernstg** [comment]
The reason why there is a warning in non-strong mode but no issues in strong mode is that the two modes use different subtype rules. As Leaf mentioned, the required subtyping relationships exist in strong mode. But in non-strong mode we get the following:

- To make `I<f_1> <: I<f>` true, we must have `[\bottom/dynamic]I<f_1> << I<f>` (19.4 Interface Types).
- So we must have `[\bottom/dynamic]f_1 << f`, i.e., `I<J<bottom>> -> K << J<K> -> J<dynamic>`.
- So we must have `I<J<bottom>> << J<K>  /\  K << J<dynamic>` (19.5).
- But the former is not true.

So the unexpected warning arises because the non-strong subtype rule uses the `<<` rule for function types, which uses covariance even for argument types.

Different rules, different outcome, no problem. ;-)

**Comment by eernstg** [comment]
So this issue is really about the following: https://github.com/dart-lang/dev_compiler/blob/master/doc/STATIC_SAFETY.md should be corrected, because it contains the claim that 'Strong mode effectively treats all standard Dart static warnings as static errors', and that is too imprecise.

**Comment by jmesserly** [comment]
closing this out, we now document the Dart 2 type system elsewhere.
