### ISSUE TITLE
Static variables are reused in local isolates with --fast-startup

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27558]
The co19 test co19/LibTest/isolate/Isolate/spawn_A04_t04 is failing on a very diverse collection of platforms.  The test should be investigated to see if it is pointing out a real failure in the async library.

It is failing if:  $compiler == dart2js && ($runtime == jsshell || ($fast_startup && ($runtime == safari || ($minified && $runtime == d8))))

**Comment by floitschG** [comment]
This is not an isolate problem. Changed the title accordingly.
This is a bug in the `--fast-startup` emitter. Static variables variables are reused in different *local* isolates.
This is not a problem for browsers as long as they support webworkers. However, in d8 and browsers that don't support webworkers we fall back to local isolates (where we run them in the same JS isolate).
The fast-startup emitter doesn't separate the static variables of the local workers.

Example:
``` dart
import 'dart:isolate';

final fin = () { print("initializing fin"); return true; }();
int global = 0;

f(arg) {
  print("calling lazy global");
  var x = fin;
  print("called");
  print("global: $global");
}

main() {
  f(null);
  global++;
  Isolate.spawn(f, null);
}
```

Run it with and without `--fast-startup`.

I have a vague memory of this being on purpose since it simplified the compiler and the output. If I remember correctly we agreed that isolate tests would need to be run with content_shell.

/cc @sigmundch : do you remember if that's what we had agreed on?

**Comment by sigmundch** [comment]
I honestly can't recall whether we discussed where to run isolate tests, but running them only in content_shell seems like a fair requirement.

In general - if we only to support isolates when webworkers are available, should we change the isolate library to fail proactively in that case & delete the local isolates logic?

**Comment by sigmundch** [comment]
@floitschG - what do you think about failing proactively and deleting the local-isolates logic?

Regarding this original bug, I'll mark it as "wont fix". FYI - after some fixes to custom-elements + js-interop, the test is now passing in safari. The test is only failing on d8 and jsshell.
