### ISSUE TITLE
Request: Static macro for implementing a class with another class (Dynamic Proxy)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27562]
On all Dart platforms, `noSuchMethod` is implementable to allow a "safe" amount of meta-programming (i.e. without use of `dart:mirrors`) to implement a class at runtime. This is pretty sweet, and is useful for simple dev-mode or test-only implementations.

In `package:mockito`:

``` dart
import 'package:mockito/mockito.dart';

void main() {
  var animal = new MockAnimal();
  var strawberries = new Food('strawberries');
  when(animal).eat(strawberries).thenReturn('Yummy!');
  print(animal.eat(strawberries)); // Prints "Yummy!"
}

class Animal {
  String eat (Food food) { ... }
}

class MockAnimal extends Mock implements Animal {}
```

The little bit of `class ... extends Mock implements ...` isn't a huge pain, but often gets repeated hundreds or thousands of times across large internal code-bases, and _also_ allows bad practices like implementing some methods but still extending `Mock`.

My preference, introducing a special function called `implement` (name can be changed):

``` dart
// In mockito.dart
T mock<T>() => implement(T, Mock)

// In user code
void main() {
  var animal = mock<Animal>();
  ...
}
```

/cc @srawlins who helps own Mockito.

**Comment by lrhn** [comment]
This is basically a request for a "dynamic proxy" (like [Java Proxy](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/reflect/Proxy.html)).
- You specify the type at runtime.
- You specify a handler/callback that receives a reflection of the invocation (like `noSuchMethod` does).

It differs from the current behavior in that you can specify the type  dynamically, instead of statically having to implement an interface to make the `is` checks succeed.

It's a sort of reflection, but so is `noSuchMethod`. The only difference is that you can't mix implemented methods with `noSuchMethod` hits on such an object, and the *runtime* system has to have a way to create instances of any interface that all forward to the handler. That also means that you can finally intercept `toString` and `hashCode` without having to be clever.

**Comment by a14n** [comment]
@matanlurey how about create a `source_gen` generator to do the job ?

```dart
library my.example;

@WithMockOf([Animal, Food])
import 'package:mockito/mockito.dart';

part 'example.g.dart';
```

and the generated part:

```dart
class MockAnimal extends Mock implements Animal {}
class MockFood extends Mock implements Food {}
```

What do you think?

**Comment by matanlurey** [comment]
The goal here is not to require source generation for something as trivial as a mock.

It's very likely we could _polyfill_ this type of behavior with `source_gen` as an example though.

**Comment by matanlurey** [comment]
I no longer want this feature :)
