### ISSUE TITLE
(Dart.next): Tigher generic type signature for Iterable, List

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27609]
We have at least two [1] [2] lints that seem to just be making up for a lack of tigher typing in the core `List` and `Iterable` interface. Is there a tracking issue somewhere for tightening these up, i.e.

```dart
abstract class List<T> {
  T remove(T object); // Replaces T remove(Object object)
}

abstract class Iterable<T> {
  bool contains(T object); // Replaces bool contains(Object object);
}
```

[1]: https://dart-lang.github.io/linter/lints/iterable_contains_unrelated_type.html
[2]: http://dart-lang.github.io/linter/lints/list_remove_unrelated_type.html

**Comment by lrhn** [comment]
There is no plan to tighten the types of `remove` or `contains`.

In Dart, even in strong mode, a `List<int>` is-a `List<Object>`. The typing here allows you to use `contains` and `remove` with objects on a `List<Object>`, even if it really is a `List<int>`.
We match Java in the typing of [`remove`](https://docs.oracle.com/javase/7/docs/api/java/util/List.html#remove(java.lang.Object)) and [`contains`](https://docs.oracle.com/javase/7/docs/api/java/util/List.html#contains(java.lang.Object)).

The lint makes sense because you are checking the *static* type of the list being removed from - if the types don't match, you can guarantee that the remove won't *do* anything, so it's silly code, not wrong.

The type annotation has to match the *actual* type of the list, and if that doesn't match the static type, then type system and static lints won't help you, you will still get a runtime error if you try to remove a non-`int` from `List<int>` assigned to a `List<Object>` variable. That's the runtime error we avoid by allowing the call and letting it do nothing.

**Comment by floitschG** [comment]
I agree with Lasse.
Initially, we actually had the tighter types but had to go back.

Not planned.

(That said: I'm very supportive of the linter checks).
