### ISSUE TITLE
(Dart.next) Semantics of throw <not-a-Error|Exception>

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27611]
Dart allows anything to be `throw`n, but the style guide recommends just throwing something that inherits from `Error` or `Exception`. Can we either:

1. Make throwing a string literal automatically wrap in an `Exception` or (`Error`) class
2. Disallow throwing anything that isn't an `Exception` (or `Error`) 

/cc @munificent

**Comment by munificent** [comment]
I think there's an argument that the language should allow things the style guide discourages. The style guide is sort of implicitly scoped to "real" code that you care enough about to check into source control, share with others, etc.

If you're hacking some local throwaway script, by all means, throw strings, use hacky names for your variables, make everything mutable and public.

**Comment by matanlurey** [comment]
I agree with that. How about option 1 then, where every literal is implicitly `Error`?

**Comment by zoechi** [comment]
http://dart-lang.github.io/linter/lints/only_throw_errors.html

**Comment by lrhn** [comment]
Let's just say that requiring thrown exception classes to extend `Exception` is not universally considered a reasonable requirement.

IOW: I personally disagree completely with the style guide on that, it's a needless restriction. The non-errors that an API throws is part of the API contract. It can be any class that makes sense.
The `Exception` class is a marker interface. Marker interfaces are not necessarily a problem, depending on how they are used, but in this case it adds no value at all. There is *nothing* common to exception objects, it's a role that objects play, but not something that you ever need to check.

**Comment by floitschG** [comment]
There is not enough benefit to break existing programs. For clean programs it's probably a good recommendations, but Dart works fine without requiring the rule, so there is no need to enforce it.

Throwing is used for two purposes: bugs and exceptional cases. If the bug is something that can happen on API boundaries or for other users (like passing in "-1" to an array-index), then you should probably throw an `Error`. They have the advantage that they automatically capture the stacktrace (and they give your API a more professional feel). If it's just a `throw` in your code to make sure you didn't forget an `enum` value (which should just be unreachable code), then it shouldn't really matter what you throw. (This is especially true, if you are not in a widely shared library).

If the `throw` is used for an exceptional case, then the most important thing is, that the type is unique to handle. Otherwise the `on X catch` wouldn't work. In general, it's a good idea to have a specific class for that, and (just in case it's not handled by the caller), making it an `Exception` class makes it clear that this is not an error. As Lasse pointed out: if you are catching within your own library, then you could just forego the additional class. It's sometimes faster, but should happen rarely.

Option 1 (wrapping everything into an `Error`) would force non-Exception/Error classes to become Errors which is not necessarily the intent.
