### ISSUE TITLE
"Update library ..." should be shown before other import quick fixes

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#27629]
![image](https://cloud.githubusercontent.com/assets/405837/19569615/aa9cbdd0-96f6-11e6-89b1-c8b176d1c70b.png)

AFAIR this was fixed not too long ago but was "broken" recently.

Not sure if this is an analyzer or WebStorm issue.

> Dart VM version: 1.21.0-edge.61bf8abd754a7ee5e2fba49db1b192ee18e1c540 (Wed Oct 19 16:52:58 2016) on "linux_x64"

> WS 2016.2.2

**Comment by bwilkerson** [comment]
@jwren How does WebStorm order the quick fixes?

**Comment by bwilkerson** [comment]
@jwren ping

**Comment by alexander-doroshko** [comment]
WebStorm preserves the order of the quick fixes, as returned by the Analysis Server.

'Suppress error with comment' and 'Suppress error with EOL comment' quick fixes are added by WebStorm itself. I think WS shouldn't add 'Suppress...' actions to the first-level quick fix popup if there are other quick fixes available, but it's a separate questions.

I guess there's some mess in the quick fix order in this case because there are several different errors at the given offset (nested error ranges) and therefore several different sets of quick fixes. In case of several sets of quick fixes IDE has no clue how to order them.

**Comment by bwilkerson** [comment]
Good point; perhaps we need to fix that by adding a 'relevance' measure to quick fixes. It's also possible, though, that it would work well to order them based on the lengths of the ranges. We should also look at the errors and see whether some of them are follow-on errors that should simply be suppressed.

**Comment by bwilkerson** [comment]
Also, the 'Suppress error with comment' and 'Suppress error with EOL comment' quick fixes should specify which error is being suppressed when there are multiple errors in the same location.

**Comment by alexander-doroshko** [comment]
> 'Suppress error with comment' and 'Suppress error with EOL comment' quick fixes should specify which error is being suppressed when there are multiple errors in the same location.

Sure, thanks!
