### ISSUE TITLE
Allow implicit dynamic in parameter declarations

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#27623]
Currently if you run `dartanalyzer` with `--no-implicit-dynamic`, it will complain about parameters without type annotations. However, according to [the style guide](https://www.dartlang.org/guides/language/effective-dart/design#avoid-annotating-with-dynamic-when-not-required), parameters that take multiple types (but not [any type](https://www.dartlang.org/guides/language/effective-dart/design#do-annotate-with-object-instead-of-dynamic-to-indicate-any-object-is-accepted)) should have no type annotations. Since non-annotated parameters follow the styleguide and are likely to be intentional, emitting errors for them doesn't seem useful.

**Comment by natebosch** [comment]
IMO we should change the style guide on this one.

When I tried this out on some code written by folks new to Dart I was able to catch real bugs caused by unintentionally omitted parameter type arguments.

I think we have a lint that could also catch this so we could make an argument that it shouldn't be rolled into no-implicit-dynamic and can be opted into with the lint instead.

**Comment by nex3** [comment]
What do you suggest as the explicit type for these arguments?

**Comment by natebosch** [comment]
Either explicit `dynamic` or `Object` would be fine with me.

**Comment by nex3** [comment]
@munificent Can you weigh in from a style guide perspective?

**Comment by munificent** [comment]
Yeah, I think the style guide should be changed. Dart's culture around typing has shifted some and I think most users do want to have to deliberately opt in to dynamism.

**Comment by nex3** [comment]
Will the style guide endorse explicit `dynamic` or `Object`?

**Comment by nex3** [comment]
In that case, I'll close this out. I've filed dart-lang/site-www#392 to track the style guide change.
