### ISSUE TITLE
some member names likely don't work right for types with "call" method

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#27647]
(moved from https://github.com/dart-lang/dev_compiler/issues/593)

In particular, those that are inherited from JS Functions, like "name" and "length".

We also allow shadowing methods like "call" and "apply". This may cause problems in our runtime, or in JS code that gets these objects. We should probably symbolize call/apply to avoid collision.

**Comment by greglittlefield-wf** [comment]
We needed to work around this issue to use the DDC, so I implemented a runtime fix to the issue with the `name` accessor until the underlying issue is fixed, if anyone's interested:
  - [implementation](https://github.com/Workiva/over_react/blob/1.12.1/lib/src/util/ddc_emulated_function_name_bug.dart#L75)
  - [usage](https://github.com/Workiva/over_react/blob/1.12.1/lib/src/component_declaration/component_base.dart#L308-L311)
  - [tests](https://github.com/Workiva/over_react/blob/1.12.1/test/over_react/util/ddc_emulated_function_name_bug_test.dart)


It's hacky and brittle and I'm not super proud of it, but it gets the job done if you *really* need to work around this issue.

**Comment by jmesserly** [comment]
CC @vsmenon @grouma -- this is the bug for some member names not working on "callable" classes

**Comment by jmesserly** [comment]
Here's a test demonstrating the issues:
```dart
class Foo {
  final name = 'FOO!';
  final length = 123;
  call() => 'hello world';
  bind(int x) => x + 40;
  apply(x, y) => 'called apply($x, $y)';
}
main() {
  var f = new Foo();
  print(f());
  // Fails because Dart sets these with `this.name =` and `this.length =` and
  // that's ignored because the data properties are not writable
  // (http://www.ecma-international.org/ecma-262/6.0/#sec-function.length)
  print(f.name);
  print(f.length);
  // works because Dart method shadows the JS ones (probably breaks JS interop)
  print(f.apply(1, 2));
  print(f.bind(2));
  // This happens to work because DDC checks `f instanceof Function` rather than
  // `typeof f == "function"`, causing it to tearoff the `call` method rather
  // than directly calling `f.apply`.
  print((f as dynamic)());
}
```
One way to fix this would be to treat classes with `call` methods as a "native type" because they are instances of JS functions at runtime. But that's a pretty blunt instrument.

**Comment by jmesserly** [comment]
this was fixed. callable classes are not subtypes of function types any longer, so we do not represent them the same way in JS
