### ISSUE TITLE
Relaxing constraints of constant expression

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#27658]
Following points of current specification might be something worth reconsideration especially for AOT compilation.

- Classes with non-final members can't be instantiated as constant, but non-final built-in types such as int and List can.
- Constant constructors have to be marked as``const``regardless of being able to be called with``new``.  In addition, the system can likely know the call site contexts to distinguish constant.
- Formal parameters of constant constructors aren't "potentially constant expressions" which can be used in initializer lists or bodies of them.﻿

**Comment by lrhn** [comment]
Both `int` and constant `List` classes are constant. You can thing of `const [list,literal]` as creating an instance of a different class than `[non,const,list,literal]`, and the const class is as const as anything. It's special in that it's can have different lengths anyway, and that is special. Integers have no non-final fields either.

Constant constructors are required to have only potentially constant expressions as initializers and have no body. We could allow any constructor satisfying this to be used with const, without needing to mark it as `const`, but not doing that is deliberate. It would make it a breaking change to add a body to such a constructor, or to change an initializer list expression to being not-potentially const, even if the author never intended the class to be used to create constants. That's why the author has to opt *in* to a constructor, and thereby the class, being constant capable. It's a significant commitment that restricts further changes to the class. If a constructor isn't marked `const`, it's because it's not intended to be `const` and using it as such can and will break in a future update.

Formal parameters of constant constructors *are* potentially constant expressions and they can be used in initializer lists. They can't be used in bodies since const constructors can't have bodies.
They can't have bodies because we want to guarantee that the constructor can be "evaluated" at compile-time without executing any user-provided code, both to avoid diverging and to avoid needing an interpreter for the entire language in the compiler.

All in all, loosening those particular restrictions is not something we plan to do, unless we do a complete overhaul of the entire constant system.

**Comment by Cat-sushi** [comment]
I understand that int is a class that has only final field and only variable referring it can be mutable.
But, I don't understand that immutable List can be replaced, added and removed the members of it.
Anyway, that's not the point.

I was talking about something breaking change, and I have come to think that this place is not appropriate such a thing.
Thank you anyway.

**Comment by lrhn** [comment]
Const lists are completely immutable, you can't change anything about them. They are as compile-time constant as any other const. A const list does have a `remove` method, but it will throw if you try to call it.

It's true that this is probably not the best place to start out with a new change suggestion.
It *is* the correct place to ask for changes, but not a great place for discussions about them.
I'm all for discussing changes to `const`, even breaking ones. :)
There are just some things that can't be broken without the result no longer being compile-time constants.  In that case, the discussion will be about removing const and replacing it with something else. That's also cool.

**Comment by Cat-sushi** [comment]
Yes const lists such as ``const [1, 2, 3]`` is immutable.
I meant `[1, 2, 3]`` or ``List(3)`` is mutable, at the same time ``const [1, 2, 3]`` is legal.

**Comment by Cat-sushi** [comment]
I said that I understand int is immutable, but I change my mind that int is mutable, because `i++` must not be re-construction process.
Of course `const 1` is constant, anyway.

**Comment by Cat-sushi** [comment]
> Formal parameters of constant constructors are potentially constant expressions and they can be used in initializer lists.

They can't.
```
class A {
  final int a;
  const A(this.a);
}

class B {
  final A a;
  const B(x) : a = const A(x); // error: Arguments of a constant creation must be constant expressions
}
```

**Comment by lrhn** [comment]
The integer objects themselves are immutable. Doing `i++` is equivalent to `i = i + 1;` and `i + 1` is a method call that returns a different integer. It changes which value the variable `i` is bound to, but the integer objects themselves never change. Due to the way things are defined, it works as if there is exactly one `int` object with the value 1, one with the value 2, etc., and `int.operator+` returns the integer object corresponding to the addition of the values of its operands.

The constant lists are not the same type of list as the non-constant lists, so one being mutable and the other not isn't special. What is interesting is that `const [listliteral]` is the only way to create instances of the constant list class.

Formal parameters of const constructors can be used as *potentially* const expressions. However, the code `const A(x)` requires `x` to be an actual compile-time constant expression, not just potentially one. That's because it would thenbe an error to write `new B(new SomeMutableSubclassOfA())`, so we can't allow a potentially constant value to flow into the `const A(...)` expression.
That *is* an annoying restriction, and one we would like to do something about. One idea is to allow you to write something equivalent to `auto A(x)` which would be equivalent to `const A(x)` when the constructor is called using `const` and equivalent to `new A(x)` when called using `new` Then it would be OK to let `x` occur in that expression because it would keep const values and non-const values separated and never create a const value with a non-const value inside.

**Comment by Cat-sushi** [comment]
> Doing `i++` is equivalent to `i = i + 1;` and `i + 1` is a method call that returns a different integer. 

I see.
> The constant lists are not the same type of list as the non-constant lists.

I understand that, but it is something surprising.

> One idea is to allow you to write something equivalent to `auto A(x)` which would be equivalent to `const A(x)` when the constructor is called using `cons`t and equivalent to `new A(x)` when called using `new`

Once, I thought something like this and I think this is reasonable.
At the same time, I think `const` deemed as `auto` is also OK, because `const` constructor can be called with `new`, anyway.

**Comment by Cat-sushi** [comment]
```
print("${([1,2,3]).runtimeType}"); // List
print("${(const [1,2,3]).runtimeType}"); // List
print("${([1,2,3]).runtimeType == (const [1,2,3]).runtimeType}"); // false
```
Surprising!
Is there any specification document of these types?

**Comment by Cat-sushi** [comment]
ECMA-408 seys both of them are ``List<dyamic>``.

**Comment by lrhn** [comment]
There is no documentation of the actual types used to implement list literals. It's an implementation details how they are represented under the hood, all that is promised is that they implement the `List` interface, which they do so `const [] is List<dynamic>` *is* true.

Both `List` and `int` are really interfaces, the actual implementation classes are hidden from view, and depending on the implementation would be extremely brittle since there is no promise that it won't change in a future version.

The list implementation types also overwrite the `runtimeType` getter to further hide the implementation details - otherwise code might work differently between different platforms. The same things is done for `int` which is actually three different types internally in the VM (for small, medium and big integers).

You can tease the actual type out of the VM using reflection:
```dart
import "dart:mirrors";

String className(Object object) =>
    MirrorSystem.getName(reflect(object).type.qualifiedName);

main(){
  // Run on 64-bit VM.
  print(className(const []));     // dart.core._ImmutableList
  print(className(new List(0)));  // dart.core._List
  print(className([]));           // dart.core._GrowableList

  print(className(0));                    // dart.core._Smi
  print(className(0x7fffffffffffffff));   // dart.core._Mint
  print(className(0x10000000000000000));  // dart.core._Bigint

  print(className(0.5));                  // dart.core._Double
}
```
You can see that the actual classes are private classes in the VM's version of `dart:core`.
The dart2js compiled version instead has the types `_interceptors.JSArray`, `_interceptors.JSInt` and `_interceptors.JSDouble`.

**Comment by Cat-sushi** [comment]
I have understood `runtimeType` is exceptional.

Sorry, I miss lead you to describe detail things.
The only thing what I want to know is the reason why user defined classes has stricter restriction to be constant.
I guess that checking expressions constant without specific class representation is too difficult for the system, so user defined types can have only final members but they can't have constructor bodies, and so on, correct?
For what it is too difficult, for JIT compilation ,for AOT compilation or for both of them?
Might Strong Mode change this situation?

**Comment by lrhn** [comment]
The only reason `List` and `Map` are special is that there are literals in the syntax to describe them.
That allows the language to treat const literals differently from non-const literals..

The reason that `num`, `String`, `bool`, and `null` values are special is that the compiler is able to know for certain how their methods/operators work. The classes are sealed and cannot be implemented or extended, so if something is an `int`, the compiler knows how its `+` operation works.

The design for compile-time constants has made some choices:
- can be computed at compile time without executing any user code
- are canonicalized
- evaluates to objects not different from other objects of the same class
- are created using the same constructor as non-const objects

Together these choices have some consequences:
- Const constructors can't contain user code. No body, no method calls except on num/bool/string objects.
- Objects must be deeply immutable, otherwise they can't be canonicalized - so no non-final fields.
- The constructor initializer list expressions must work both in const and non-const calls, which is why we have introduced the "potentially constant expression" which is very limited, but does allow you to do some simple operations in the constructor.


With those restrictions in place , many changes can make a class or constructor no longer compatible with being const, so we require the class author to opt in to being const. Using a non-const declared class to create const objects is fragile, so we don't allow it. That's a consequence of the restrictions we required above and a wish for authors to write stable dependable code where you can predict which changes might break clients of the class.
That's why you can't use any class that has final fields and a simple constructor with `const` - it's for your own protection.

All in all, the restrictions are there for a reason, most caused by the initial choices about how compile-time constants in Dart should work. Loosening those restrictions isn't as easy as removing one particular restriction because that would make constants no longer act like constants were intended to work. If anything, it's easier to add more specialized constant expressions, with fine tuned limits, than it is to remove an existing constraint completely.

Possible additions could be:
- const instance fields: Liike final fields, but can be *read* at compile time from a compile-time constant instance). Alone this breaks the field/getter symmetry, so it probably also needs ...
- const getters/methods: Methods where the body is a single return of a potentially compile-time constant expression which can only refer to parameters or const instance fields on the same object. These can be called at compile time as a compile-time constant expression. But then we still have to find a way to prevent recursion, otherwise the compiler might never complete.
- make `c[i]` a compile time constant expression if `c` is a list or map constant and `i` is a constant index of the appropriate type. But this only works for literal list or map constants, not for any constant object that happen to implement `List` or `Map`.

As you can see, there are things to do, but most have a catch that means it's not trivial to add the feature. That means that there has to be a comparable advantage to adding them, otherwise it's just complication without benefit.

Another option is to remove compile-time constants completely and add other features that gives the same benefits for places where you need it (canonicalization, immutability, computed only once, but not necessarily all of them at the same time). That's a major change, so again it requires the benefit to be worth the effort.

So, we're definitely *thinking* about const, it's not always the best solution for what it's being used for, but changing it isn't simple.
