### ISSUE TITLE
stack traces printed when async methods are involved can be hard to read and debug

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#27661]
We had numerous requests to make stack traces more complete when the stack traces involve
async methods
- Request from the flutter team
  "IIRC there was some discussion of making VM stack traces nicer/shorter?  i.e. pulling some
  of what package:stacktrace does into the VM?"
  Note: the stacktrace produced from package:stacktrace has some issues (deemed to be slow, has
  stuff like zones etc. in the stack trace which do not mean anything to the end user)
- This was one of the issues that came up in the recent ACX/Dart/Angular surveys
  "Better stacktraces especially with async calls"
- Report from digilogic on an uncaught exception
  #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
  #1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
  #2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
  #3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
  #4      _RawReceivePortImpl._handleMessage
  
  (dart:isolate-patch/isolate_patch.dart:149)

**Comment by a-siva** [comment]
@mit-mit @johnmccutchan @rmacnak-google

**Comment by tvolkert** [comment]
I had an interesting case of this yesterday where I was getting a stack overflow due to infinite recursion, and package:stack_trace completely hid the relevant details.

For reference:
- https://github.com/flutter/flutter/pull/7189 fixed the infinite recursion
- https://github.com/flutter/flutter/pull/7197 added tests that would have failed without the fix
- https://gist.github.com/tvolkert/e4eb57d81cfcee1f0d2f1d0db38e6d90 shows the message from package:stack_trace

**Comment by Hixie** [comment]
FWIW what I'd really love to see from Flutter's perspective is if the stack frames were provided in a form where it could be inspected programmatically, rather than just as a string.

**Comment by mit-mit** [comment]
Tagging for Q1 as 28175 was closed as a dupe of this, and that has the tag.

**Comment by mit-mit** [comment]
Moving to 1.23.
