### ISSUE TITLE
@JS doesn't travel trough summaries

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#27672]
If you have two classes in two different files:

### One.dart:
```dart
     @JS("OneJS")
     class One {
       external myMethod();
     }
```
### Two.dart
```dart
     class Two extends One {
     }
```
The generated code looks ok when building the files together with ddc and class `Two` will correctly extend the global `OneJS`.

If you build them separately and using summaries to build `Two.dart` , the code generated will be wrong with the class `Two` trying to extend the non existent `One` dart class.

**Comment by bwilkerson** [comment]
@stereotype441 @scheglov

**Comment by vsmenon** [comment]
I hit a similar issue the other day.  It appears the annotation in the summary, but not deserialized by default.

FWIW, in DDC, we call:
```
metadata.constantValue
```

Do we need to use this instead?
```
metadata.computeConstantValue();
```

That might have been working for me, but I haven't had a chance to test more thoroughly.

**Comment by jmesserly** [comment]
I'd be happy to switch to `computeConstantValue` if that's a good workaround?

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2458693003/

**Comment by stereotype441** [comment]
I *think* that should work but I'm not in a good position to test it.

In general, the rule of thumb is that you have to use computeConstantValue
unless you've taken some action to ensure that constants have been
computed. (It's kind of a foot gun in the API)

On Thu, 27 Oct 2016, 19:57 Jennifer Messerly, <notifications@github.com>
wrote:

I'd be happy to switch to computeConstantValue if that's a good workaround?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/sdk/issues/27672#issuecomment-256721431>, or mute
the thread

**Comment by jmesserly** [comment]
Interesting. @stereotype441 if we've got a resolved AST (w/ errors computed) are we likely to have constants available? We're using .constantValue for 3 other places, all of them seem to be working because they're for resolved ASTs, but maybe we'd be safer to call computeConstantValue (is there any downside to doing so?)

CC @vsmenon who was chatting about this with me

**Comment by stereotype441** [comment]
The only downside to calling computeConstantValue is a performance cost, but it's extremely minor (a single null check in the case where the value has already been computed).  So yeah, I would recommend changing those 3 other call sites to use computeConstantValue too.

Maybe we should change the behavior of .constantValue to be equivalent to computeConstantValue (and perhaps deprecate it as well), so that the possibility of this sort of bug goes away.  @bwilkerson what do you think?

**Comment by bwilkerson** [comment]
sgtm
