### ISSUE TITLE
const constructors can't call const constructors

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27679]
I wish this was possible:

```dart
class A	{
  const	A(this.value);
  final	int value;
}

class B	{
  const B(int value) : a = const A(a);
  final	A a;
}
```

**Comment by lrhn** [comment]
So do I.
It's non-trivial, though.

The expression `const A(a)` must work both when `B` is invoked with `new` and with `const`. The expresion can't be const and depend on a runtime value (as it would when invoked with `new`) and it also can't be non-const when invoked with `const`. We currently don't have any syntax that allows different behavior depending on context.

We could say that `const A(a)` would be implicitly treated as `new A(a)` in non-const invocations (because it can't possibly mean `const`), but that's likely to be too confusing.

If we make `new` optional in constructor invocations, and we make `const` implicit in const contexts, then writing just `A(a)` could mean either `const` or `new` depending on how `B` is called. That's the most likely solution since it hinges on other changes that would be nice, but it does depend on other non-trivial changes hitting the language first.
