### ISSUE TITLE
StreamTransformer.bind dartdocs should be fleshed out

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27739]
The documentation for `StreamTransformer.bind` says that the pause state should be propagated, but it doesn't say how to handle error events from the incoming stream. Should error events be propagated? Should they be ignored? Should they cancel the output? Are they a valid subject for transformation? What are the best practices for writing transformers?

**Comment by lrhn** [comment]
It doesn't say anything, because there is nothing special to say - any function from `Stream` to `Stream` can be used. Even the comment about propagating pause is general stream behavior - if you are listening on a stream and don't want new events for a while, pause the subscription until you do.
All events are valid targets for transformation because you can do anything at all. What you do with them depends on what you want the transformer to do. The general rules for streams apply to the output stream you create (basically: don't forget to close it when you are done).

Best practice for writing transformers is to figure out what the transformation should do - what is the connection between input and output stream events - and then implement that.

**Comment by Hixie** [comment]
Just pasting that comment verbatim into the docs would already be a huge improvement. :-)
