### ISSUE TITLE
StreamSubscription.cancel docs are unclear about the contract

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27738]
The docs for `StreamSubscription.cancel` say:

- That you can return null.
- That you should not return null.

- That the returned Future's value must be null.
- That the returned Future's type is dynamic.

- That the returned Future may complete with an error.
- That the returned Future should not complete with an error.

This makes dealing with this API difficult. Should a consumer expect to handle null return values? Futures that can resolve to an error? Values other than null?

We should make a decision on each of these three issues, and then define the contract accordingly, to remove the confusion.

Additionally, the dartdocs should be clearer about whether cancel will trigger onDone.

**Comment by lrhn** [comment]
Agree.
The problem comes from the original API being a void function, and then later realizing that it makes sense in some cases to have an asynchronous cancel (when you want to wait for the cancel to complete, e.g., before removing the file being read or similar).

It is annoying to have to wait for a future if the cancel is actually synchronous, but that's a problem with async in general.

(The cancel call will definitely not trigger `onDone` since "done" is an event and you won't receive any events after calling cancel).

**Comment by natebosch** [comment]
I think this is more clear now. In particular two sections of the docs help:

"For historical reasons, may also return null if no cleanup was necessary. Returning null is deprecated and should be avoided."

"A returned future completes with a null value. If the cleanup throws, which it really shouldn't, the returned future completes with that error."
