### ISSUE TITLE
Add --disable-mirrors flag to dart2js

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/sdk#27759]
With [configurable imports](https://github.com/lrhn/dep-configured-imports/blob/master/DEP-configured-imports.md), it is possible for libraries to test for `dart:mirrors` support. Since [Flutter does not support `dart:mirrors`](https://github.com/flutter/flutter/issues/1150), I think a lot of libraries that rely on mirrors should offer an alternative non-mirrors version with reduced functionality ([example](https://github.com/PointyCastle/pointycastle/issues/107)) whenever possible.

Since dart2js is an environment where usage of mirrors can be unfavorable, it makes sense to use the non-mirrors variants of libraries if possible.

I believe providing this flag is a good way to encourage library developers to provide such an alternative implementation and gives flexibility to dart2js users to consider the option of running their applications without mirrors support.

**Comment by floitschG** [comment]
DBC: `--fast-startup` does not support `dart:mirrors`. If you want to experiment with dart2js code that doesn't support `dart:mirrors` you can try that. Since that also comes with some code-size increase it's obviously not a complete solution to your problem.

**Comment by stevenroose** [comment]
Is `--fast-startup` a flag for dart2js? I can't seem to find it:
```
$ dart2js --help -v | grep fast
$ dart2js --version
Dart-to-JavaScript compiler (dart2js) version: 1.20.1
```

**Comment by sigmundch** [comment]
Ah, good point, it is not a documented flag yet because we were waiting until we had it covered by our test bots, which we do now. We should add the documentation for it. Meanwhile, it is understood by the compiler though, so you should be able to pass it in.

You should be able to see the difference in the output: the flag changes the way code is emitted to use more straightforward JS idioms. It is bigger than the default emitter, but tends to be faster to load (hence the name `--fast-startup`)

**Comment by rmacnak-google** [comment]
FWIW, such a flag should be `--enable-mirrors=false` for compatibility with the VM.

**Comment by stevenroose** [comment]
Does this exist yet?

**Comment by matanlurey** [comment]
@stevenroose In Dart2, there will be no mirrors support on the web at all.

@sigmundch I think we can effectively close this as no longer planned.
