### ISSUE TITLE
html query_all test is flaky on DDC / chrome canary

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27794]
This test occasionally flakes and only on chrome canary:

https://travis-ci.org/dart-lang/sdk/builds/174739421

**Comment by vsmenon** [comment]
Oddly, it's got a static error too (at least against the regular SDK):

```
[error] A value of type 'ElementList<Element>' can't be assigned to a variable of type 'List<CanvasElement>'. (tests/html/queryall_test.dart, line 48, col 33)
```

This doesn't appear strong mode specific.  @alan-knight do you know if the DDC API is different?

**Comment by vsmenon** [comment]
I should note there are also several deprecation hints on the test:
```
[hint] 'queryAll' is deprecated and shouldn't be used. (/Users/vsm/dart/sdk/tests/html/queryall_test.dart, line 32, col 24)
```

**Comment by alan-knight** [comment]
queryAll is marked deprecated, but "because it's semantics will be changing in the future". I'm not sure what that means, especially because it just forwards to querySelectorAll, which isn't deprecated. 

The static error isn't different in the SDK version. I'm not sure what is and isn't allowed. It seems that
`List<Sub> foo = new List<Super>();`
is statically valid but a runtime error. However
`List<Sub> foo = new ElementList<Super>();`
is a static error, where
`class ElementList<T> extends ListBase<T> {}`

I don't know how to see the failure from that link. What happens when it flakes? And if it has a static error how does it run at all?

**Comment by vsmenon** [comment]
Ahh, I was looking at the wrong version.  It looks like this test has strong mode errors fixed in the DDC copy:

```
diff test/codegen/lib/html/queryall_test.dart  ../../tests/html/queryall_test.dart 
4a5,7
> library NodeListTest;
> import 'package:unittest/unittest.dart';
> import 'package:unittest/html_config.dart';
7,8d9
< import 'package:expect/minitest.dart';
< 
9a11,12
>   useHtmlConfiguration();
> 
45c48
<       var all = queryAll('canvas');
---
>       List<CanvasElement> all = queryAll('canvas');
61c64
<       var canvases = all.where((e) => e is CanvasElement);
---
>       Iterable<CanvasElement> canvases = all.where((e) => e is CanvasElement);
```

**Comment by vsmenon** [comment]
So, it seems to just timeout, and only occasionally.

See the log here: https://api.travis-ci.org/jobs/174739424/log.txt?deansi=true

It's not terribly informative though.  I think this covers all the recent errors I see here:

https://travis-ci.org/dart-lang/sdk/builds

**Comment by alan-knight** [comment]
The test is simple enough that this seems like it might just be a canary bug.

**Comment by vsmenon** [comment]
Shall we skip for now?:

https://codereview.chromium.org/2492903002

**Comment by jmesserly** [comment]
this is no longer skipped
