### ISSUE TITLE
feature request: support blocking until Future completes

### ISSUE THREAD

**Issue by pexatus** [dart-lang/sdk#27812]
The class `Future<T>` should have a non-async method `T get()` that waits for the Future to complete and returns its value, similar to the method `get()` in Python's `multiprocessing.pool.AsyncResult` class: https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.AsyncResult

The method should be non-async so that it can be called from a non-async function in a way that will block execution until it is finished.

Currently, to access the Future's result, the only two ways to achieve it that I'm aware of are either

1. create a function callback that will handle the return value when it is produced, and

2. make the calling function async, as well as all functions up the call stack all the way up to main(), and prepend "await" in front of them. 

Option (2) is ugly and bad style, allowing a called function to dictate design across the rest of the program. 

Speaking to the virtues of (1), I appreciate that in many of the web/mobile applications the Dart developers envision, it will create an unsightly delay in the UI to block until (for example) a File is opened.

However, the Dart VM allows standalone scripts run from the command line. For such a program, it makes perfect sense to have a single thread of execution that blocks until a File is opened, especially if none of the subsequent code can execute until that File is opened and its contents read. Some programs really do need to run in linear order from start to finish. It is awkward and counterproductive in this situation to impose an event-driven, callback-heavy framework.

**Comment by lrhn** [comment]
That's not really generally possible with the current execution model of Dart.
Blocking execution waiting for a future to complete will prevent the future from completing since it's being completed by Dart code. Some operations can be performed blocking. That is mostly I/O which is why many functions in `dart:io` has a `Sync` version like [readSync](https://api.dartlang.org/stable/1.20.1/dart-io/RandomAccessFile/readSync.html)). Having a special kind of Future for those operations that can be waited for isn't really practical - you just use the `Sync` version of the function instead.

So, not all `Future`s can reasonably support a blocking `get` method. For example getting the content of an HTTP request requires quite a bit of local work in Dart code to receive, decode and combine the content. Blocking the isolate won't work. Not blocking the isolate means that your function *is* async, and there is no way to hide that.

For this to actually work, the runtime would need a way to suspend a single execution stack without suspending everything, allowing other asynchronous tasks to continue running until the stack is resumed.
There are two problems with that:

1. We can't do that when compiling to JavaScript, and
2. it makes it unpredictable where a function can be preempted by other code running. If you call a function that calls a `Future.get` method, then arbitrary code can run before that future gets back. Reasoning about state becomes much harder.

The only real solution is to treat *all* functions like they are `async`, but when compiling to JavaScript, that can get prohibitively expensive - all functions must be prepared to be suspended at all function calls, not just where there is an `await` in an `async` function.

All in all, it's not practically possible to get the value of a `Future` in a synchronous way.

**Comment by pexatus** [comment]
Ah, I was unaware of the sync versions of these I/O methods. Thank you for pointing that out.
