### ISSUE TITLE
Analyzer does not infer type of dynamic class fields after typecheck

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/sdk#27813]
For  function scoped dynamic variables the type is inferred inside a block that checks the type. For example
```dart
if (dynamicVar is String) {
  // dynamicVar is inferred to be String
}
```
However this doesn't work for class fields as in the following example:

```dart
class Test  {
  dynamic classVariable;
  List<String> stringList;

  void checkClassVariable() {
    if (classVariable is String) {
      // ERROR: Could not infer type parameter E, dynamic must be of type String. ([untitled1] bin/main.dart:7)
      stringList = [classVariable];
    }
  }

  void checkMethodVariable() {
    dynamic methodVariable;
    if (methodVariable is String) {
     // Type is inferred 
      stringList = [methodVariable];
    }
  }
}
```

**Comment by eernstg** [comment]
This works as designed.

The feature is called _type promotion_ in the language specification, and it is specified to apply to local variables and function/method parameters, but not instance variables, static variables, nor library variables (aka global variables).

The reason why this feature does not generalize to those "more global" kinds of variables is that it is based on an analysis which ensures that the given variable keeps the same value between the type test and the usage. Since arbitrary code can access those "more global" variables (including instance variables, if the enclosing object is accessible), it is much more complex (and in general it is an undecidable question) whether the variable is mutated between those two points in time. So the language avoids diving into that tar pit.
