### ISSUE TITLE
Don't force the developer to put the "super call" as last function in initializer list (strong_mode)

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#27816]
Please!!! this looks so ugly!!! super must be first in Java, BaseClass-call must be first in C++ - in Dart it should be the last function - not what we want...

**Comment by lrhn** [comment]
If it's only the way it looks that is a problem, I think it is something we can learn to live with.
The reason for wanting to move it last is that it will be executed after the initializer list. Putting it where it is actually executed makes reading and understanding the code easier.

It doesn't have to be that way, we could easily change it to execute before the initializer list, but the current style is already to write the call at the end of the initializer list, and the VM has always executed it there, so there is no compelling reason for changing it at this point.

**Comment by MikeMitterer** [comment]
The main reason IS readability!!! I really don't care what the current style is if the current style is bad. As said above - Dart is the only language I know where the super-call is the last function in the initializer-list. 

'**Dart should follow the conventions** and not doing it's own business if it's not necessary.

**Comment by floitschG** [comment]
Java has the super call first, but they also run into issues because of this:

``` java
// In T.java.
class T {
  T() {
    virtual();
  }
  public static void main(String[] args) {
    new TT();
  }

  void virtual() {}
}

// In TT.java.
class TT extends T {
  final int fin;

  TT() {
    super();
    this.fin = 499;
  }

  void virtual() {
    System.out.println(fin);
  }
}
```

This program prints "0". This means that the *final* field `fin` has two values: `0` and `499`. Dart fixes this, by ensuring that all (final) fields are initialized before they can be accessed. This implies that all fields  must be set before the super-constructor body can be invoked.

The current semantics allow the `super` call to be at any position, but that doesn't actually mean that the super constructor is invoked at the time of the `super` call. In fact, it only initializes the super fields at that time. The actual super constructor-body is only invoked at the end of the initializer list. This means that Dart (so far) had a two-phase initialization: first the fields, then the bodies.

This sounds relatively simple, but in practice it is very hard to implement, and very confusing when users actually want to depend on the order in which constructor bodies are invoked. It is completely unexpected that a `super` call in an initializer list doesn't actually invoke the super constructor at that time.

The simple solution is to have the `super` call at the end of the initializer list, which is when the constructor call actually happens. This makes the location of the super constructor consistent with the time of execution. (As a benefit it simplifies our implementations, but that wouldn't be a reason for the change).

I understand that this might require projects to change their conventions, forcing them into a style that isn't familiar to them. In our experience (and we have used this convention for a very long time) this style quickly becomes natural.

While we understand that our convention is now different from other languages, we do think that the benefit (having a clear simple semantics of how objects are created) outweighs the cost of adapting code and getting used to the new style.

**Comment by MikeMitterer** [comment]
:+1: :ok_hand: + Thanks!
