### ISSUE TITLE
Strong mode analyzer complains of handler method with dynamic optional arg but not identical free function

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/sdk#27822]
In the below example the last line produces an error in strongmode but the free function with identical signature does not. It seems to me that that both are valid args to `listen`.
``` dart
void receive([dynamic e]) {}

void listen(void receiver(String s)) {}

class Listener {
  void receive([dynamic e]) {}
}

main() {
  // This is OK
  listen(receive);
  final listener = new Listener();
 // But not this
 // ERROR: The argument type '([dynamic]) → void' cannot be assigned to the parameter type '(String) → void'. ([untitled] bin/main.dart:12)
  listen(listener.receive);
}
```

![screen shot 2016-11-15 at 12 32 49](https://cloud.githubusercontent.com/assets/6475621/20304383/2c7f4122-ab30-11e6-9e7d-f33da253c44f.png)

**Comment by leafpetersen** [comment]
This is, unfortunately, working as intended.  Strong mode currently treats concrete functions with `dynamic` parameters (`receive` above) differently from general expressions with a function type for which the parameter is `dynamic` (`listener.receive` above).  This is in order to be able to handle certain coding patterns that were otherwise hard to express, but unfortunately it disallows the `listener.receive` pattern above. 

If you make the parameter type of `receive` be `Object`, then it will work.  Alternatively, you can add a cast to the intended receiver type.

@jmesserly It occurs to me looking at this code that perhaps the right thing to do for now is to make this an implicit cast instead of an error. 

cc @lrhn @eernstg @floitschG @munificent

**Comment by jmesserly** [comment]
this has been fixed. no more fuzzy arrows :)
