### ISSUE TITLE
vmservice server needs to bind and listen on systems where only IPv6 is supported (IPv4 disabled)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#27841]
By default the vmservice server binds and listens on 127.0.0.1 which is localhost for IPv4
we need to bind to both 127.0.0.1 and ::1 on the same port number in order to serve
on systems setup either for IPv6 or IPv4.

**Comment by nex3** [comment]
@rmacnak-google Does that CL bind to both `::1` *and* `127.0.0.1` on machines that support both? Just binding to whatever `localhost` refers to isn't enough.

**Comment by rmacnak-google** [comment]
No, the vmservice only ever binds to one address. As discussed in the CL, attempting to bind the same port on both ::1 and 127.0.0.1 is flaky.

**Comment by nex3** [comment]
There are ways to work around the flakiness; see [`HttpMultiServer.loopback()`](https://github.com/dart-lang/http_multi_server/blob/master/lib/http_multi_server.dart#L124-L152). It's very important that both addresses be bound, because Mac OS is not at all consistent about which IP `localhost` binds to. Users have run into this issue before and it's caused serious issues.

**Comment by rmacnak-google** [comment]
This issue is about IPv6-only systems.

**Comment by nex3** [comment]
> This issue is about IPv6-only systems.

In point of fact, the original comment says "we need to bind to both 127.0.0.1 and ::1 on the same port number". But if you insist that this isn't the right place to track that, can you open a new issue? This is an important piece of functionality and complaining about which issue it's discussed in doesn't change that.
