### ISSUE TITLE
Test import_short_absolute fails on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27870]
The commit

https://github.com/dart-lang/sdk/commit/227b74cb55e441dbf39b43815187c166cb2570de

introduces a test in pkg/analyzer/test/src/summary/resynthesize_common.dart that fails on Windows.

**Comment by stereotype441** [comment]
Working on it.

**Comment by stereotype441** [comment]
This is tricky.  The test which was added asks analyzer to analyze a file containing an import statement of the form:

    import "/a.dart";

The analyzer converts this to the URI `file:///a.dart`, and then attempts to use the path package to convert it to a file path.  On Linux and mac, the path package converts this back to `/a.dart`, which seems reasonable.  On Windows, it converts it to `a.dart`, which seems wrong, because `a.dart` is a relative path.

Note that the `Uri.toFilePath(windows: true)` method has different behavior: it converts `file:///a.dart` to `\a.dart`.  I'm not sure if that's any more meaningful than `a.dart` (since it's an absolute path without a drive letter), but at least it doesn't look like an absolute path.

I will file a bug against the "path" package and commit a temporary workaround that disables this test on Windows.
