### ISSUE TITLE
Better shell scripting support 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#27880]
Dart works nice on the cmdline but it could be even simpler.

Current state is that I need a full Dart structure with pubspec.yaml, bin-folder aso.

But if you take python, bash or similar only one file is necessary to write nice an powerful scripts.

Here is what I want:

cmdline:
```bash
$ pub install args
```

myscript.dart
```dart
#!/usr/bin/env dart

import 'dart:io';
import 'package:args/args.dart';

void main(List<String> arguments) {
 ...
}
```

**Comment by platelk** [comment]
For me dart already have want you want, we can achieve this with `pub global`, you can see the documentation here [pub-global](https://www.dartlang.org/tools/pub/cmd/pub-global)

For `pub global activate` you still require to have a full 'dart folder architecture' but the share is easy, you can take a look at the [grinder package](https://pub.dartlang.org/packages/grinder)

Otherwise you can use snapshots which allow you to have only one file to share/use and then simply use it with `dart you_app.snapshots` (You can rename it to avoid the .snapshots ;) )

And then you can combine the two technique and then have a pretty nice install/usage flow.

* Develop
* Create snapshots
* `pub global active --source you_app_snapshot`
* `you_app_snapshot args1 args2`

But maybe this workflow don't match your requirement. if not, I will be interested to knows it and maybe help =)

**Comment by MikeMitterer** [comment]
Try this:

make new dir, cd to the new dir, crate this script, chmod 700 it and
than execute:

```dart
#!/usr/bin/env dart

import 'package:uuid/uuid.dart';

main() {
    var uuid = new Uuid();
    print(uuid.v4());
}
```

**Comment by MikeMitterer** [comment]
@platelk I know this workflow and it's nice for, as said, a bit !!! larger projects. 
If you compare it with a python-script it doesn't look so cool anymore.

With python I "pip install <module>", write my script (single file) - and that's it. The same with bash-scripts - no need for config-files like pubspec.ymal, not global active - nothing. It just runs.

Don't get me wrong - the  "global activate"-thing is cool if you write larger scripts with fix dependencies, with submodules and so forth. But just to automate things via script the effort is to high. If you look at all the python scripts available, what they do with jus on single file - that's cool!

**Comment by zoechi** [comment]
Where should `'package:uuid/uuid.dart';` come from? Without a `pubspec.yaml` it doesn't exist.

**Comment by floitschG** [comment]
My understanding is, that `#!/usr/bi/env dart` scripts should have a way to search common locations for packages and just use the latest version there.

Alternatively, we could support a common set of packages (or a date-based system):
``` dart
#!/usr/bin/env dart-2016.1`
...
```

This would use the packages that were released before/at 2016.1.

At the moment we are not prioritizing development of shell scripts, though.
Since there are no immediate plans to do anything about this issue, I will close this bug. This doesn't mean that we won't ever add the feature, but it would happen naturally when we focus more on shell-scripting again.

**Comment by thosakwe** [comment]
@MikeMitterer Until then, try [this](https://pub.dartlang.org/packages/scripts). Feel free to submit a PR as well.

**Comment by Timmmm** [comment]
[`dscript`](https://pub.dev/packages/dscript) looks like a really nice solution. Unfortunately the repo has been deleted. It would be really cool if something like it were into the official Dart tool so you didn't need to install anything except Dart.

**Comment by Timmmm** [comment]
Huh actually I didn't realise but except for the embedded `pubspec.yaml`, you can already do this:

```
 $ cat main.dart
#!/usr/bin/env dart

void main() {
	print('Hello, World!');
}
$ ./main.dart
Hello, World!
```

But sadly it's not very useful without any packages. You probably want at least `path`, `process` and `http`.
