### ISSUE TITLE
Allow await outside of async functions

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [dart-lang/sdk#27911]
I've had several issues with websockets and trying to implement asynchronous execution (cause this is a web app, and I can't block properly), but when trying to wait for the response to a request, I have to use await. This in-turn forces the function return a `Future`, which then needs to be `await`ed by the parent that called it. This causes a domino effect until all of the code ends up being asynchronous, which isn't what I want. I've tried using `.then`, but it does not force the system to wait, instead it simply calls a function once the `Future` is done, which means I cannot use it for returning a value, or to wait till I get the response, and continue to parse data. 

Below is a runnable version of the code that is giving me issues. It is not 100% done, so there are unrelated warnings in some places (runnable meaning that you can paste it into dartpad)

```dart
import 'dart:async';
import 'dart:html';
import 'dart:convert';

class TKWMApi {
  String uri;
  WebSocket connection;
  bool isOpen = false;

  TKWMApi(String uri) {
    this.connection = new WebSocket(uri);
    this.connection.onOpen.listen((_) {
      this.isOpen = true;
    });
  }

  List<String> getTags() {
    if (!isOpen) {
      return [];
    }
    else {
      Map<String, dynamic> request = {
        "method": "get_tags",
        "data": {}
      };
      Future<MessageEvent> responseFuture;
      connection.send(JSON.encode(request));
      responseFuture = connection.onMessage.first;
      var x = responseFuture.then((x) => x.data);
      print(x);
    }
  }

  String init(String sentence) {
    if (!isOpen) {
      return "";
    }
    else {
      Map<String, dynamic> request = {
        "method": "init",
        "data": sentence
      };
      var response;
      Future<MessageEvent> responseFuture;
      connection.send(JSON.encode(request));
      responseFuture = connection.onMessage.first;
      responseFuture.then((ev) { response = ev.data; return response; });
    }
  }
}
Future sleep2() {
  return new Future.delayed(const Duration(seconds: 1), () => "2");
}

main() async {
  var gg = new TKWMApi("ws://localhost:8765");
 // This is so that it doesn't enter an infinite loop of being in the CONNECTING state and so that I can send stuff
  await sleep2();
  var ll = gg.init("Bobby mate");
  print(ll);
}
```

**Comment by lrhn** [comment]
The contagious nature of asynchronous code is a known issue, but not one that is easily fixed.

If we could just `await` in a synchronous function, we wouldn't need to have asynchronous functions, so there is a reason things work the way they do.

The nature of a synchronous function is that when you call it, it does its work and returns to the caller immediately. Nothing else happens between the call and the return except what the called function itself chooses to do. You can implement this behavior with a single stack.

Some functions can't complete their job immediately. Some of those choose to *block*, stopping all execution until it's ready to return (this is what the `Sync` functions in `dart:io` do). That makes sense when all the function does is to wait for something external, and you don't mind waiting for it.

If you don't want to block *everything* while waiting for a response, you can choose to let the function be asynchronous. An asynchronous function returns immediately, but instead of returning the result, it returns a `Future` which will eventually have the result. That allows execution to continue without blocking, still using only a single stack, and you have a way to get notified when the result is ready.

Since your asynchronous function can contain an `await`, then there is no way it can immediately return the result, so it has to return a future too. 

If a synchronous function could contain an await, then it can't also immediately return a result that depends on the eventual value of the awaited future. It *has* to delay. And it can't *block* because that would prevent all other code from running, and then the future would never be completed.

The one possible solution would be to have more than one stack, so you can block one function and still execute other functions while you wait. It's not even a bad idea - there's just no way to compile that to JavaScript, so we are stuck with one-stack waiting-means-asynchronous for now.

If your code is asynchronous, then it is asynchronous. There is no way out of that.

**Comment by MicroTransactionsMatterToo** [comment]
Yep, I've worked it out. I'm going to build an event listening structure instead

**Comment by MicroTransactionsMatterToo** [comment]
I'll post it here in case someone else has the same issue

**Comment by MicroTransactionsMatterToo** [comment]
Ok, so this is how I did it

```
import 'dart:async';
import 'dart:html';
import 'dart:convert';

/// Provides an interface to the TKWM WebSocket API
///
/// Listen for method responses using the equivalent Stream
class TKWMApi {
  String uri;
  WebSocket connection;
  bool isOpen = false;
  StreamController<dynamic> eventController;
  StreamController<Map<String, dynamic>> responseController;
  StreamController<Object> errorController;
  StreamController<Object> questionController;
  StreamController<Object> translationController;
  StreamController<Object> tagController;

  /// Errors reported by API are here
  Stream<dynamic> get onError => errorController.stream;

  /// All responses from the API
  Stream<dynamic> get onResponse => responseController.stream;

  /// Any question queries from the API
  Stream<dynamic> get onQuestion => questionController.stream;

  /// Responses to [getTags]
  Stream<List<String>> get onTag => tagController.stream;

  ///_Deprecated: Causes error, use [onResponse] instead
  @Deprecated("Sometime")
  Stream<dynamic> get onEvent => eventController.stream;


  TKWMApi(String uri) {
    this.connection = new WebSocket(uri);
    this.connection.onOpen.listen((_) { this.isOpen = true; });
    this.connection.onMessage.listen(this._parseResponse);
    // Create streams
    this.eventController = new StreamController.broadcast();
    this.responseController = new StreamController.broadcast();
    this.errorController = new StreamController.broadcast();
    this.questionController = new StreamController.broadcast();
    this.tagController = new StreamController.broadcast();
    this.translationController = new StreamController.broadcast();
  }

  void getTags() {
    if (!isOpen) {
      return;
    }
    else {
      Map<String, dynamic> request = {
        "method": "get_tags",
        "data": {}
      };
      connection.send(JSON.encode(request));
    }
  }

  /// Calls the API's init method using given [sentence]
  void init(String sentence) {
    if (!isOpen) {
      return;
    }
    else {
      Map<String, dynamic> request = {
        "method": "init",
        "data": sentence
      };
      var response;
      connection.send(JSON.encode(request));
    }
  }

  /// Parses any response recieved from [connection]
  void _parseResponse(MessageEvent message) {
    this.responseController.add(message.data);
    Map<String, dynamic> decoded;
    // Decode JSON
    // Add error to stream if it fails to decode
    try {
      decoded = JSON.decode(message.data);
    } on FormatException catch (e, tr) {
      this.errorController.addError("Invalid JSON response", tr);
      return;
    }
    // Check to see whether `isError` is true
    // If so, add to Error stream
    if (decoded["isError"] != null) {
      this.errorController.addError(decoded);
      return;
    }
    // Grab the type of method called
    String methodName = decoded["method_called"];
    // Switch here
    switch (methodName) {
      case "init":
        break;
      case "get_tags":
        this.tagController.add(decoded["data"]["tags"]);
        break;
      case "get_questions":
        this.questionController.add(decoded["data"]);
        break;
      default:
        break;
    }
  }

  /// Closes all streams
  close() async {
    this.connection.close(0, "Session Ended");
    await this.translationController.close();
    await this.errorController.close();
    await this.questionController.close();
    await this.responseController.close();
    await this.eventController.close();
  }
}
```
