### ISSUE TITLE
Expose core/collection tests for other packages to run against

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#27912]
For example, it would be great to not to have to write and re-write tests for custom implementations of `List`, `Set`, `Map`, etc. My imagined scenario here is using in `package:collection`, for example:

```dart
import 'package:collection/collection.dart';
import 'package:collection_test_suite/collection_test_suite.dart';

main() {
  runTestSuite(() => new DelegatingList());
}
```

**Comment by floitschG** [comment]
I don't remember if we still support publishing packages from withing the SDK, but if yes, this could be feasible.

@lrhn what do you think?

**Comment by lrhn** [comment]
I don't think we have any core-library tests that are in separate packages, but I don't see a fundamental problem with it. We can access packages inside the tests, so having a `testIntegerMap` function from a package instead of a local helper file shouldn't be a problem.

The biggest issue is that the tests aren't written for reuse, they do what we need them to do and nothing more. It would take some reworking to extract the useful, but not too specialized, tests from the existing test code.

**Comment by matanlurey** [comment]
I'm guessing this is infeasible
