### ISSUE TITLE
Dart API: compareTo() should better document double.NAN and double.INFINITY values

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27924]
Please see compareTo() documentation at https://api.dartlang.org/stable/1.20.1/dart-core/num/compareTo.html

> For ordering, the double NaN value is considered equal to itself, and greater than any numeric value (unlike its behavior in operator==)
...
Positive infinity is greater than any finite value (any value apart from itself and NaN)

So there are two statements.  
1) double.INFINITY is greater than any other value except NAN
2) NAN is greater  than any other values (without exceptions)

From the above one may conclude that  NAN is greater than INFINITY. But in fact
```dart
  print(double.NAN > double.INFINITY);
  print(double.NAN < double.INFINITY);
  print(double.NAN == double.INFINITY);
```
Prints `false` for all 3 cases. 
So compareTo() documentation should clearly explain what is expected behaviour when comparing NAN and INFINITY

**Comment by floitschG** [comment]
The behavior of `compareTo` is independent of `==`, `<` and `>`. The side note ("unlike its behavior in operator==") points this out.

The correct behavior is thus: `print(double.NAN.compareTo(double.Infinity)); // => 1`.

For doubles we can't make `compareTo` and `<`,`>`,`==` work consistently, since `compareTo` wants a complete order. However, the IEEE standard makes this impossible with `NaN` and `0.0 == -0.0`.

I will update the comment.
