### ISSUE TITLE
Please merge various revisions into dev channel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27962]
@whesse @mit-mit @kasperl 

These are various DDC fixes blocking internal customers.  I've already cherry-picked these there.

These should go into 1.21 if we have further internal pushes from dev.

This includes the following hashes:

201c5b9297e5b701d4ee03ac42e6325629baf73c
ec81359fc0cfeebe4faf8e91db04ed4b4c7c9685
106c623a9f39cc56b4a16b166158e83cef12bd23

They do not quite merge cleanly (minor conflicts on summary file).  I've resolved against dev and uploaded them as a single CL here:

https://codereview.chromium.org/2544203002/

Builds and tests pass.

**Comment by whesse** [comment]
Because the binary file ddc_sdk.sum is not uploaded in the cl, I could not apply the patch.  I applied the patch for all the other files (9 modified, 2 added), and then ran the tool/patch_sdk.sh script, and committed the modified ddc_sdk.sum.  Running the tool again made no new changes, so I assumed it worked correctly.  I also tried running dartdevc, and it ran.

In the future, please commit a ddc cherry-pick with resolved conflicts to a private branch in the github repo, so I can cherry-pick it from there.

Merged in 1.21.0-dev.11.2
