### ISSUE TITLE
Encoding.getByName('system') returns null

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#27982]
Seems like maybe it should be special-cased to return `SystemEncoding` since `SystemEncoding.name => 'system'`.  Otherwise, it's not symmetric.  e.g. you expect the following to work:

    Encoding.getByName(encoding.name) == encoding

**Comment by lrhn** [comment]
The `Encoding.getByName` function doesn't know about all possible encodings, only the ones that are defined in the `dart:convert` library.
The system encoding comes from `dart:io` and isn't available on all platforms.

The `SystemEncoding` isn't a specific encoding, it depends on the platform as to how it behaves, so documenting that something is using the `"system"` encoding is fragile. 
It would probably be better if there was no `SystemEncoding` class, just a `Encoding get systemEncoding` getter that returns the *actual* encoding so you can get its real name.

So, I don't think it would be a good idea to add `"system"` as a recognized key for `Encoding.getByName` because `system` isn't the name of any actual *encoding*.

( I'm considering changing the `name` getter on SystemEncoding to returning the name of the actual encoding, if possible, but that requires figuring out what Windows code page is actually being used, and it would still not work with `Encoding.getByName`).
