### ISSUE TITLE
Wrong value returned by int.stringAsFixed()

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27985]
According to the https://api.dartlang.org/stable/1.20.1/dart-core/num/toStringAsFixed.html

> If the absolute value of this is greater or equal to 10^21 then this methods returns an exponential representation computed by this.toStringAsExponential(). Otherwise the result is the closest string representation with exactly fractionDigits digits after the decimal point

But in fact the code:
```dart
  int y = pow(10, 21) - 1;
  print(y.toStringAsFixed(0));
  print(y.toStringAsFixed(10));
  print(y.toStringAsFixed(20));
```
produces the following
```
1e+21
1e+21
1e+21
```
According to the documentation output should be:
```
999999999999999999999
999999999999999999999.0000000000
999999999999999999999.00000000000000000000
```

**Comment by lrhn** [comment]
Try:
```dart
print(pow(10, 21) - 1 < pow(10, 21));
```
and you'll see that subtracting one doesn't actually give you something smaller than 10^21. The problem is that 10^21 is greater than 2^53, so not all numbers in that range are representable as doubles. It happens that 10^21 is exactly representable as a double, and the next lower representable number is 10^21-2^17.

Will the wonders of double numbers never seize :)
