### ISSUE TITLE
int.gcd() wrong behavior or documentation issue?

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27997]
See int.gcd() documentation at https://api.dartlang.org/stable/1.20.1/dart-core/int/gcd.html

> If both this and other is zero, the result is also zero.

What if only one of the arguments is zero? Now
```dart
  print(0.gcd(0)); // prints 0
  print(1.gcd(0)); // prints 1
  print(0.gcd(1)); // prints 1
```
From matematic point of view GCD is not defined if one of the arguments is zero (see for example https://en.wikipedia.org/wiki/Greatest_common_divisor). If both of the arguments are zero we define that result is zero and specify it in the documentation. But in case when only one of the arguments is zero the current behaviour is not correct. This function should either throw an exception, either documentation should clearly define that in this case this method returns not the value that mathematician expects

**Comment by alexeieleusis** [comment]
0.gcd(0) certainly is not defined, but you could make it 0 by convention since every number divides 0 in integer arithmetic.

For all other pairs is the expected behavior, look here https://en.wikipedia.org/wiki/Euclidean_algorithm one of the implementations returns the other value in case one of the operands is 0. It is also specified in the page you refer to.

Feel free to reopen if I am mistaken.

**Comment by lrhn** [comment]
Agree. The GCD is defined when at least one of the operands are non-zero, which is also what the Wikipedia page says. The integer `1` *is* a common divisor of `0` and `1`. The problem with `GCD(0, 0)` isn't that there isn't a common divisor, but that there isn't a greatest one since all integers divide zero.
