### ISSUE TITLE
Contexts misbehaving with new analysis driver

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#27995]
Using the latest analysis server as of bb92055 I'm seeing some weird behaviors in IntelliJ's "problems" view.  I make a change to analyzer (which I expect would break a lot of projects), but I only see problems show up in one project (kernel).

My analysis roots are:
- pkg/analysis_server
- pkg/analyzer
- pkg/analyzer_cli
- pkg/dev_compiler
- pkg/front_end
- pkg/kernel

When I look at analysis server's web interface, the contexts look really wrong.  I see that it has created two contexts:
- analyzer
- kernel

In the "analyzer" context, there is one priority file (the file I currently have open, which is `pkg/analysis_server/lib/starter.dart` - that's weird because I would expect this to show up as a priority file only in an "analysis_server" context).  There are zero "added files" (which seems completely wrong--analyzer contains a lot of files).  There are 606 "implicitly analyzed files", including files from analysis_server, analyzer, front_end, and some of their dependencies (meta, args, async, charcode, cli_util, collection, convert, crypto, csslib, glob, html, isolate, linter, logging, path, plugin, source_span, string_scanner, typed_data, utf, watcher, when, which, yaml, dart_style, package_config).

In the "kernel" context, the same priority file appears (really surprising, since `pkg/analysis_server/lib/starter.dart` has nothing to do with kernel), 80 added files (all in "pkg/kernel"), and 422 implicitly analyzed files (a similar set to the ones above, but without analysis_server).

There's no sign of files from analyzer_cli or dev_compiler anywhere.

This has forced me to turn the new analysis driver off.

I believe these problems showed up sometime between Friday morning and this morning, but I'm not certain.

**Comment by scheglov** [comment]
Do you have `.packages` file in your `analysis_server` folder?

**Comment by stereotype441** [comment]
No, I just have the one at the root of the SDK repo.

**Comment by scheglov** [comment]
I have seen something like yesterday. I had to remove `.packages` because there was an exception because of missing `LintConfig.parseMap`.  Only problems in the current file were reported. I fixed it by removing `.packages`, so using the one from the root of SDK repo. I guess I should have done this long ago.

But it seems that you should not have this problem.
It must be something different then.

**Comment by scheglov** [comment]
I was not able to reproduce the problem.

I still wonder if there was an exception during contexts building.
@bwilkerson 

I don't think that extra priority files is a reason for this behavior.
We analyze priority files inly if there are already scheduled for analysis because there were also added, or `getResult` was called for them.

![image](https://cloud.githubusercontent.com/assets/384794/20901420/4c525aae-bae7-11e6-8cd1-61135b180b94.png)

**Comment by stereotype441** [comment]
Ok, thanks for checking.  I will try to debug locally.

**Comment by stereotype441** [comment]
Found the problem.  I had an old version of linter, because the version of analysis server I'm testing comes from a hodgepodge of sources.  With the proper linter, things are working for me again.
