### ISSUE TITLE
Isolate.pauseCapability description is incorrect

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28002]
The [description for property Isolate.pauseCapability](https://api.dartlang.org/stable/1.20.1/dart-isolate/Isolate/pauseCapability.html) reads:

> Capability pauseCapability
> read-only
> Capability granting the ability to pause the isolate.
> 
> This capability is used by pause. If the capability is not the correct pause capability of the isolate, including if the capability is null, then calls to pause will have no effect.
> 
> If the isolate is started in a paused state, use this capability as argument to resume to resume the isolate.

It is not clear how to use the `pauseCapability`. 
It is read-only, so it is not clear how it can be changed in order to be used by `pause`. 
Also the [description ](https://api.dartlang.org/stable/1.20.1/dart-isolate/Isolate/resume.html)of `Isolate.resume()` reads:

>The capability must be one returned by a call to pause on this isolate, otherwise the resume call does nothing.

So it might be incorrect to use `Isolate.pauseCapability` with `Isolate.resume()`

**Comment by lrhn** [comment]
The capabilty doesn't change, it is set when the object is created.
You don't use it actively, it is used by the `pause` function, which uses it to document to the isolate that the caller is allowed to pause it. 

The capability is visible because you can extract it and use it to create a new Isolate object.
You can also create another `Isolate` objects without a pause capability. That `Isolate` object can't be used to pause the corresponding isolate.

The pauseCapability of an Isolate object *should* either be the one corresponding to the controlPort's isolate or it should be null (that's what the `Isolate` constructor tries to say). 
You can create the Isolate object with any capability, the type checked won't notice, but it's not going to work. Since control port messages are generally fire-and-forget, there is no error if you use the wrong capability, it just doesn't do anything.

The `resume` documentation is correct. If you read the documentation for the `paused` parameter, it says:
> If the [paused] parameter is set to `true`,  the isolate will start up in a paused state, just before calling the [entryPoint] function with the [message], as if by an initial call of `isolate.pause(isolate.pauseCapability)`. To resume the isolate, call `isolate.resume(isolate.pauseCapability)`.

That means that `isolate.pauseCapability` can be treated as the return value of a `pause` call.

**Comment by kevmoo** [comment]
@lrhn Should we close this, or is there some improvements we can make here?

**Comment by lrhn** [comment]
I'm making some improvements (I hope, at least some changes) in https://codereview.chromium.org/2549363003/

**Comment by alsemenov** [comment]
Could you also correct the typo in the last sentence?

> If the isolate is started in a paused state, use this capability as argument **to resume to resume** the isolate.

**Comment by lrhn** [comment]
Absolutely. Good catch.

**Comment by alsemenov** [comment]
I think it is also worth to mention, that it will not be possible to resume the isolate, which is started in paused state, if the `pauseCapability` is not correct.

**Comment by lrhn** [comment]
I don't think it should be necessary to repeat that an invalid capability doesn't work. That's stated in the `resume` method.  And it *shouldn't* be invalid.

In practice, an isolate is either created using a spawn function, and then the capability is correct, or it's created using the `Isolate` constructor, and then whoever created it is responsible if it doesn't work. The capability *should* never be wrong, it should either be `null` or correct - anything else is just somebody messing with you. The `Isolate` constructor does say that the capabilities should be the ones taken from the original isolate that the control port came from (or a subset of them).

**Comment by srawlins** [comment]
Closing as @lrhn's doc fix landed.
