### ISSUE TITLE
Directory listing returns incorrect contents for /tmp

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28015]
The following program:

```dart
import 'dart:io';

main() async {
  print(new Directory("/tmp/").listSync());
  print(await new Directory("/tmp/").list().toList());
}
```

prints this output for me:

```
[Directory: '/tmp/uplink-soecks.root.443873550', Directory: '/tmp/.org.chromium.Chromium.qIIf0M']
[Directory: '/tmp/uplink-soecks.root.443873550', Directory: '/tmp/.org.chromium.Chromium.qIIf0M']
```

I have many more than two entries in my `/tmp` directory, and I'd expect to see all of them when I list the directory.

I've reproduced this on 1.21.0-dev.9.0 and on stable versions as far back as 1.16.0. I'm using Ubuntu 14.04 LTS.

**Comment by whesse** [comment]
This is verified on my Linux machine as well.

By moving files around to different directories, and listing using Dart, I have found that the directory list seems to get truncated when it gets to the file
 srwxr-x--- 1 whesse eng      0 Dec  7 02:58 chromoting.whesse.ssh_auth_sock
which may be a named pipe, not an actual file.
Removing this file from a directory causes the entire directory to be listed successfully, adding this file to a directory causes that directory listing to be truncated.

I think the C++ native code implementing directory listing for Dart can't handle receiving an entry which isn't the normal file, directory, or symbolic link type, and fails.  This failure is turning into an end-of-stream, rather than an error.

If the file type isn't Link, File, or Dir, the code just falls through to line 196, and returns kListDone.

This just needs to be fixed by covering the other cases of sockets, pipes, devices, etc from https://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html

**Comment by zanderso** [comment]
Should the entries that are not regular files be skipped or listed? I would say listed, but I'm not 100% sure that this is consistent with the API docs (which say only "files", "directories", and "links" are listed), so I will punt to @floitschG for confirmation.

**Comment by zanderso** [comment]
https://codereview.chromium.org/2556313002/

**Comment by nex3** [comment]
I'd expect them to be listed as `File`s.

**Comment by zanderso** [comment]
As I said, I would expect so as well, but I'm not going to land a change without the owner of the API weighing in here.

**Comment by whesse** [comment]
I think Lasse is the library api owner.

**Comment by zanderso** [comment]
@lrhn
