### ISSUE TITLE
Heap snapshot crashes VM

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#28030]
@rmacnak-google 

Only happens in Flutter but any Flutter application will do. I've tried running in Dart's debug mode and no assertions blow up.

The crash happens in object_graph.cc on line 35:

`(*current)->SetMarkBit();`

It is always an Instructions object. It is not from the VM isolate. 

I have worked around the bug for my demo tomorrow by not marking Instruction objects.

**Comment by rmacnak-google** [comment]
I suspect it has to do with W^X code. IIRC, it is enabled by default in the VM but disabled in the standalone embedder. If this is correct, we should expect the heap snapshot to work for Flutter in AOT because all Instruction objects are in the VM isolate. We should also expect crashes from other heap tools that use object_graph.cc, such as retaining paths or retained size.

**Comment by johnmccutchan** [comment]
@rmacnak-google Siva and I debugged the issue yesterday. For some reason (will figure it out this afternoon):

`thread->isolate()->heap()->WriteProtectCode(false);`

Doesn't make the executable pages writable. Our bots are always running with code protection disabled so we haven't been testing this in awhile.

**Comment by johnmccutchan** [comment]
This has been worked around in Flutter by disabling code write protection entirely.

The VM bots are running with code write protection enabled.

I suspect there is a race condition around marking code pages writable. Maybe we need an atomic reference counter?
