### ISSUE TITLE
RangeError is thrown instead of IndexError

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28036]
According to the documentation (https://api.dartlang.org/stable/1.21.0/dart-core/IndexError-class.html) IndexError is
> A specialized RangeError used when an index is not in the range 0..indexable.length-1.

But
```dart
    List l = [1, 2, 3];
    l[7];
```
produces RangeError, not IndexError.
Shouldn't IndexError be thrown here instead?

**Comment by lrhn** [comment]
That would probably be convenient and give a better error message, but it's not required. Any `Error` can be thrown, using a specialized subclass is only a utility provided to get consistent and useful error messages.

**Comment by sgrekhov** [comment]
If RangeError thrown here then why IndexError class is needed? When IndexError is thrown in Dart API? Or IndexError is targeted for developers to use in their own code?

**Comment by floitschG** [comment]
As far as I can tell, we never use `IndexError` so far. I believe that's just an oversight.
In general, we are not that concerned about the actual `Error` class that is thrown (since programs shouldn't need to deal with them), so there is not a huge pressure to change the current behavior, but since we already have the class it would make sense to go through the code and change `new RangeError` instantiations with `new IndexError` ones when it makes sense.

The particular case of indexing into an array is, unfortunately, much harder, because dart2js and the VM have intrinsics to optimize array accesses. This means, that changing that specific error is not as simple as just changing a `new RangeError` somewhere.

**Comment by lrhn** [comment]
The `IndexError` helper class was added later than the `RangeError` class. We haven't gone through old code and changed it, because it's not wrong. I do use `IndexError` in new code when it applies, mainly through [RangeError.checkValidIndex](https://api.dartlang.org/stable/1.21.0/dart-core/RangeError/checkValidIndex.html).

**Comment by natebosch** [comment]
Do we have any plans to change anything here?

**Comment by lrhn** [comment]
No concrete plans to go back and change old code, no. It is *not wrong*, so changing it is not a priority (aka, any other relevant work takes precedence over doing that).

If we modify the code anyway, for another reason, we can also update the errors.
