### ISSUE TITLE
dart2js/ddc: Allow re-using interfaces in `dart:io`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28078]
Specifically, I'd like to re-use the file interfaces, i.e.

- Directory
- File
- FileMode
- FileStat
- FileSystemCreateEvent
- FileSystemDeleteEvent
- FileSystemEntity
- FileSystemEntityType
- FileSystemEvent
- FileSystemException
- FileSystemModifyEvent
- FileSystemMoveEvent

For example, this should be legal in ddc/dart2js:

```dart
import 'dart:io';

/// Implements the `File` API backed by Google Drive.
class GoogleDriveFile implements File {
  ...
}
```

Originated from https://github.com/matanlurey/file/pull/10 by @tvolkert

/cc @jacob314 and @vsmenon

**Comment by lrhn** [comment]
Allowing you to import a `dart:io` that doesn't work (and it really can't work in a browser) is dangerous. 

You can test whether a library is available, and use that for configuration dependent imports. If `dart:io` seems to be supported, some libraries will try to use it. If it doesn't actually work, that makes the program fail, even though it could have succeeded by using `dart:html` instead. One example is `package:resource` which uses either `File` or `XmlHTTPRequest` to load resources, depending on what is available.

I recommend making a copy of the interfaces that you care about and use those instead (and by all means improve them where possible, Posix files might not be exactly what you need). You can use `dart:io` if it's available, but importing it if it doesn't work is really too too dangerous to allow.

**Comment by tvolkert** [comment]
The specific use case lies in https://github.com/matanlurey/file/blob/master/lib/src/interface/file_system.dart, where we provide a file system abstraction based on `dart:io` interfaces.  Some implementations (such as the [in-memory file system](https://github.com/matanlurey/file/blob/master/lib/src/backends/memory/memory_file_system.dart)) will implement those interfaces without actually delegating to `dart:io` at all, so we'd like to be able to use those in a browser.

Using separate interfaces in really sub-optimal, because you want libraries to be able to use without it leaking to callers, who will then have to switch away from their existing use of `dart:io` interfaces (or creating a shim layer to translate back and forth between the two, which is bad for a number of reasons).

**Comment by lrhn** [comment]
If you use a configurable import to use either `dart:io` (if available) or `myOwnInterfaces.dart` (if `dart:io` is not available), then the user cannot see the difference. Either they are using the `dart:io` interfaces, or there are no `dart:io` interfaces and nothing to be incompatible with.

The big problem is that you are assuming client libraries that import `dart:io` - otherwise they can't be expecting a `File` or similar.  We can't allow that if you don't actually have a `dart:io` library that works. There is no way to distinguish a library that imports `dart:io` for the `File` interface from one that uses `new File(path).readAsStringSync()`. If a library imports `dart:io`, it is incompatible with platforms where `dart:io` doesn't work (and therefore isn't available).

There is a solution, which is to make a `dart:io_types` library that only declares abstract interfaces, and a `dart:io` library that provides implementations of these interfaces. It's actually a great idea, but it was not the way the `dart:io` library was designed, and that means that we have lots of static methods, constructors and global variables with no abstraction. Changing that would be completely breaking for anything using the existing library, so unless we make a `dart:io2`, I just don't see that happening.

(Constructors are just static methods, static methods are just global variables, global variables invariably suck because of lack of abstraction and lack of decoupling. Adding abstraction after the fact means that you have two ways to do the same thing, one of which still suck.)

**Comment by tvolkert** [comment]
Ok, I think I got the desired use case working using conditional imports - https://github.com/matanlurey/file/pull/18

**Comment by matanlurey** [comment]
I think @jacobr already did this a while back.
