### ISSUE TITLE
Strong mode does not treat implicit call method tear offs as definite functions

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28087]
For the code below, the analyzer issues an error for the first line of `main`, but not for the other two.  We should treat implicit call method tearoffs as definite functions as well.

```dart
class A {
  void foo(x) {}
  void call(x) {}
}

void take(void f(int x)) {}
void main() {
  take(new A());
  take(new A().call);
  take(new A().foo);
}
```

**Comment by jmesserly** [comment]
Isn't it correct to not issue an error, because`top -> void <: int -> void`? It looks like it's working correctly to me? The tear-offs are being treated as definite functions, that's why they end up `top -> void` instead of `bottom -> void`. (Intuitively, if I will only pass that function an int, then a function that accepts any object will work.)

The bug seems like it's on the first line? It looks like we don't understand the interface type w/ a call method should be a subtype of the function type. Perhaps because it's treating "call" as a fuzzy arrow.

Also BTW, there's another subtlety here with tear-offs. They are definite arrows, but they aren't an exact type. That is different from functions where the two properties tend to go together. With methods you can tear them off and get a subtype:
```dart
class A {
  void foo(x) {}
  void call(x) {}
}
class B extends A {
  void foo(x, [y]) {}
  void call(x, [y]) {}
}
void take(void f(int x)) {}
void main() {
  A a = new B();
  take(a);      // actually B.call
  take(a.call); // actually B.call
  take(a.foo);  // actually B.foo
}
```

**Comment by leafpetersen** [comment]
Sorry, I wasn't clear.  Yes, I believe that the first line should *not* be an error, not that the next two lines *should* be errors.
