### ISSUE TITLE
HashSet.from(Iterable elements) creates a set ordered in unpredictable way.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#28083]
Dart API Spec reads about `HashSet.from(Iterable elements)` constructor:

`Creates a hash set as by new HashSet<E>() and adds each element of elements to this set in the order they are iterated.`

This means that elements of the created set should be ordered in the same way as original `Iterable` object. 

However, this is not so in some cases. For example, the following test example shows that elements from the same Iterable can be ordered in the different way from tun to run:

``` dart
import "dart:collection";
main() {
  print(new HashSet.from([1, 2, 3, "string", null, []]));
}
```

Just run it several times and compare output.

Here are my results of several runs on my Windows desktop, I am using dart 1.21.0:

{1, [], 2, null, 3, string}
{1, 2, null, 3, [], string}
{1, 2, null, 3, string, []}
{1, 2, [], null, 3, string}
{1, 2, null, 3, string, []}
{1, [], 2, null, 3, string}
{1, 2, null, 3, [], string}
{[], 1, 2, null, 3, string}
{1, 2, null, 3, [], string}
{1, [], 2, null, 3, string}

If I print elements of the set using set.forEach(element)  construction, I get the same result: the order of the elements is unpredictable.

**Comment by lrhn** [comment]
A `HashSet` is not required to iterate elements in the order they are added. A `LinkedHashSet` does that, but a `HashSet` doesn't have to, and indeed doesn't. 

The "in the order they are iterated" does have an effect, which is why it's there - if two not-identical-but-equal elements are in the iterator, the one added first will be the one in the resulting set. We could probably remove that clause without anybody noticing, and just not guarantee anything about the order elements are added in, but as usual, we can't be absolutely sure nobody is depending on it.

Purely as a curious observation, if you look at the output, you'll actually see that it's fairly consistent. The only element that moves around is the empty list. That's because it's the only element that uses its identity hash code as its `hashCode`. The rest have the same hash code every time the program is run, and the `HashSet` is deterministic, so the only thing different between runs is where the empty list is placed in the hash table.

**Comment by floitschG** [comment]
Maybe the following would make the dartdoc easier to understand:
https://codereview.chromium.org/2567393002/
