### ISSUE TITLE
Performance of hot reloading a flutter app with the new front-end is acceptable

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28090]
@johnmccutchan @a-siva @sigmundch Please populate this issue with performance targets.

**Comment by johnmccutchan** [comment]
We have lots of data from the Flutter performance bots. For Flutter Gallery a hot reload takes ~800 milliseconds. That time includes synchronizing sources onto the device, reloading, and reassembling the Flutter application.

**Comment by dgrove** [comment]
@a-siva What are your current thoughts on this?

**Comment by a-siva** [comment]
Here are our current numbers from the flutter hot reload benchmarks (numbers were taken from
runs done on 1/7/2018

```
                                                                               **baseline**      **preview-dart-2**
hotReloadMillisecondsToFrame                              1203 ms      1184 ms
  hotReloadDevFSSyncMs                                         412 ms       459 ms
  hotReloadFlutterReassembleMs                              762 ms       709 ms
  hotReloadVMReloadMs                                              29 ms         16 ms

hotReloadMillisecondsToFrameAfterChange           1239 ms      1235 ms
  hotReloadDevFSSyncMs                                          393 ms       451 ms
  hotReloadFlutterReassembleMs                               377 ms       393 ms 
  hotReloadVMReloadMs                                             469 ms      391 ms 

hotRestartMillisecondsToFrame                                  4250 ms      4680 ms

full_debug_build_millis                                               19134 ms     27925 ms
```

The numbers are pretty comparable, except for the initial debug build time which is off by about 40%
One we have strong mode wired up and are able to demonstrate that it does not regress the hot reload
numbers we should be able to close this bug.

**Comment by jensjoha** [comment]
How do we re-create the `full_debug_build_millis` number?

**Comment by mraleph** [comment]
I think these are recreated by running task `flutter_gallery_android__compile` from devicelab tasks

**Comment by jensjoha** [comment]
So it basically boils down to
```
flutter packages get
flutter clean
time flutter build apk --debug --local-engine=android_debug
flutter clean
time flutter build apk --debug --local-engine=android_debug --preview-dart-2
```

First thing to notice is that (in both cases) it actually (via gradle) runs `flutter build flx` twice. I think that's being fixed though. Locally that changes it to
baseline: 15 s -> 14 s
preview-dart-2: 25 s -> 18 s
(note that all of these numbers are best-of-a-few-runs as it varies wildly).

**Comment by jensjoha** [comment]
I think we need a more specific goal here that isn't "be on par with the 'baseline'", because it seems to me that most of what we can possibly do will also benefit the 'baseline'.

Here's basically what happens on `build apk`:
* A number of initializing steps for gradle (takes ~3 seconds on my machine)
* Basically running `build flx` twice (as noted above that can probably be removed though -- and it hits `preview-dart-2` harder because the baseline is faster on the second run when nothing has changed). This is what actually compiles stuff. `build flx` basically consists of these 2 steps:
   * Compile ('baseline' does a script snapshot whereas with `--preview-dart-2` we actually compile the whole thing). For 'baseline' that takes ~2 seconds the first time and ~0.5 seconds the second time, whereas with `--preview-dart-2` it takes ~3 seconds every time.
   * Assemble which is basically finding all assets (as well as the compiled from above) and zipping it. Finding all assets takes maybe a second and zipping it then takes time proportional to the amount of data it zips which is larger for `--preview-dart-2` than for the 'baseline'. For baseline it takes ~0.5 seconds, whereas for `--preview-dart-2` it takes ~1.5-2 seconds.
* Various other gradle-contained build steps  (e.g. for flutter_gallery it involves a bunch of stuff for  `connectivity`, `device_info`, `url_launcher` and `video_player`) (takes ~5-8 seconds) as well as additional steps for the actual app (packageDebug, transformNativeLibsWithMergeJniLibsForDebug, transformResourcesWithMergeJavaResForDebug etc) (also taking several seconds).

So what can be done:
* As noted above, don't run `build flx` twice. It helps both pipelines (although `preview-dart-2` benefits more) - so while it will tighten the gap it won't close it.
* Compile faster --- well, maybe, but we're actually not much slower there...
* Somehow minimize the time spend on gradle stuff. I have no idea if that's possible, but if it is it would help both pipelines so it isn't going to close the gap.
* Make zipping faster somehow. Again I have no idea if that's possible, but if it is it would help both pipelines (although `preview-dart-2` benefits more) so while it will tighten the gap it won't close it.

**Comment by mraleph** [comment]
Flutter has been switched to the Dart 2 pipeline, which means we deemed the performance acceptable. The work to improve hot reload and cold start times will continue but this issue is behind us now.
