### ISSUE TITLE
Better optimization for short-lived Map and List literals

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28107]
If I want to create a new `List`, implementation, say `LinkedList`, that's straightforward enough.

The interesting part is supporting a `.from` factory constructor and using a list literal, for example:

```dart
abstract class LinkedList<T> implements List<T> {
  factory LinkedList.from(List<T> list) {
    var l = new LinkedList._();
    l.addAll(list);
  }
}
```

So today, in user code, one may write:

```dart
new LinkedList.from([
  1,
  2,
  3,
  ...
])
```

See the problem? We're allocating a new list... Just to throw it away and use it to create a new structure.

This problem is also evident with the map-literal, for example:

```dart
abstract class DomElement {
  void setStyle(String name, String value);

  void setStyles(Map<String, String> map) {
    map.forEach(setStyle);
  }
}
```

```dart
domElement.setStyles({
  'color': 'red',
  'height': '50px',
  ...,
})
```

So on the one-hand we have the nice (JS-land) experience of Map and List literals, but on the other hand we allocate objects just to use their structures, and then they get GCd. Could the dart2js backend (and others?) optimize this away?

For the `List` example (strawman dart2js):

```js
var l = new LinkedList();
l.add(1);
l.add(2);
l.add(3);
...
```

For the `Map` example:

```js
domElement.setStyle('color', 'red');
domElement.setStyle('height', '50px');
```

I realize it would not always be safe to make these sort of "advanced" inline changes, but in cases where it _is_ safe (i.e. the `List` or `Map` literal is created prior to a constructor or method invocation where it is directly used), it would be real nice.

**Comment by kevmoo** [comment]
I had a related (and perhaps complementary) feature idea around read-only literals.

Something like

```dart
var foo = r[a, b, c];
var bar = r{'a': a};
```

Where I'm stealing the notion of the `r` prefix from raw String – although in this case it means `readonly`.

This would allow folks to create such literals without requiring constant values – and could allow the compiler/VM to make the optimizations your suggest with less fear...

**Comment by rakudrama** [comment]
I'm hesitant to add too many optimizations like the ones suggested. The payoff has to be worth the investment.

We do recognize some special cases, e.g. for-in on lists.

Clever optimizations tend to work only some of the time, and it is hard to predict the code you will get.
It is hard to do automatically, e.g. since errors will give you a different call stack, and it is hard to tell there would be no errors. It is usually the job of the compiler to preserve the behaviour of the program :-)
Doing special optimizations can be a big maintenance problem - there is all this code in the compiler that is in effect a second much more complex (partial) implementation of the library and needs to be kept in sync.
Currently dart2js has no special knowledge of LinkedList - it is just code.

If you really care about having the compiled code be a certain way, then you should probably write the source that way. I'd rather invest in language level features that help. For example, cascades help somewhat:

```dart
... = new LinkedList()..add(1)..add(2)..add(3)

domElement
  ..setStyle('color', 'red')
  ..setStyle('height', '50px');
```

Are there other constructs we should be adding to the language that make it easy to express what we want _and_ simpler for the implementation to compile well reliably?

Perhaps `new LinkedList<int>[1, 2, 3]` 
could _mean_ `new LinkedList<int>()..add(1)..add(2)..add(3)`.
This could work for any class with a zero-argument constructor and a __add__ method that allows one argument (Set, Queue etc).

Perhaps we should have list/iterable comprehensions in the language instead of in the library.

**Comment by matanlurey** [comment]
I like your suggestion more @rakudrama but I was trying to make it easier for y'all :)

/cc @yjbanov who has also talked about wanting what you suggested.

**Comment by matanlurey** [comment]
I'm guessing this is unlikely to be addressed outside of new language features.

**Comment by lrhn** [comment]
I agree. This is too specific in the form provided here (applies to collections with `add` only).
If we get some notion of var-args, it should be possible to make functions like this work in general, and if the compiler inlines the constructor, it might even be possible to avoid all the intermediate allocations, perhaps reading values directly off the stack instead of allocating a list object.
