### ISSUE TITLE
Analysis Driver call to AnalysisContext performs unnecessary tasks

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#28110]
We don't need to perform any inference.
The element model is already linked.

This forces us to read and resolve parts.
At the moment there is a bug with this - we don't put part content into the content cache.

![image](https://cloud.githubusercontent.com/assets/384794/21200358/d4df06d6-c1fb-11e6-8067-e61735aa56ea.png)

**Comment by scheglov** [comment]
A workaround.
https://codereview.chromium.org/2571373002

**Comment by stereotype441** [comment]
Actually it looks from the screenshot like the problem isn't related to inference.  What's happening is that we need to parse and resolve all the compilation units of a library in order to see which local elements are used/unused, so that we can generate "unused X" hints.

In principle, we could change things so that we record the set of names referenced by each compilation unit, and then when one compilation unit changes, we could update its "unused X" hints based on the recorded data, without having to re-resolve other compilation units.  But it would be a nontrivial architectural change, so I would want to see some data indicating that it's worth it.  My intuition is that having to re-resolve all parts of a given library in order to update that library's errors/warnings is not too much of a burden anyhow.

**Comment by bwilkerson** [comment]
@scheglov Is this still relevant, or can we close it as being stale?

**Comment by scheglov** [comment]
No, this is not relevant anymore.
