### ISSUE TITLE
Assigning Iterable<int> to List<int> should error in Strong mode?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#28121]
https://dartpad.dartlang.org/fe7c16639d3c8839c0e81f4f52776f48

List.length is O(1) vs. Iterable.length is O(N), the user thinks they're making an O(1) call, but gets O(N).

```
void main() {
  List<int> items = numbers.where((i) => i > 2);
  
  if (items.isEmpty) {
    print("no items!");
    return;
  }
  
  if (items.length > 100) {
    print('too long!');
    return;
  }
  
  print(items.toList());
}

var iterationCount = 0;

Iterable<int> get numbers sync* {
  print('Hello! ${++iterationCount}');
  for (var i = 0; i < 10; i++) {
    yield i;
  }
}
```

Console:
```
Hello! 1
Hello! 2
Hello! 3
[3, 4, 5, 6, 7, 8, 9]
```

Thanks to @kevmoo for the illustration.  Presumably there is already a warning for this and dartpad just doesn't have it on when it turns on strong_mode?  @leafpetersen would know.

**Comment by leafpetersen** [comment]
This is just a downcast.  Strong mode allows implicit downcasts, unless you turn them off with --no-implicit-casts.  The runtime component of strong mode specifies that there is a downcast inserted there by the compiler (like a checked mode check) which would fail at runtime, so you would get a runtime error with this code on DDC.  But the VM does not yet implement the runtime component of strong mode.  I believe that in this case though, checked mode will catch this error for you.

We've discussed making --no-implicit-casts the default with some very terse syntax to allow it (e.g.   `List<int> x = !staticallyIterableButDynamicallyAListSoJustLetMeUseItHere;`) but this would be a fairly large change to the language.

So I think any warnings in the languages as it stands would probably have to be an opt-in lint, and not part of strong mode since it's not clear to me what the general argument for warning on this cast but not others is?

**Comment by eseidelGoogle** [comment]
I see, so as far as the analyzer is concerned, where() could actually have returned an instance of a List as the Iterable, and so it's happy trust you and let you downcast it to a Subclass (List) and then later let the VM blow up at runtime when you call a Subclass method on your Superclass (Iterable).

https://dartpad.dartlang.org/f7c25988ef490eeba4f54d436624aff7

```
class Superclass {
  void method() {print("method");}
}

class Subclass extends Superclass {
  void subOnlyMethod() {print("submethod");}
}

Superclass foo() {
  return new Superclass();
}

void main() {
  Subclass bar = foo();
  bar.method();
  bar.subOnlyMethod();
}
```

**Comment by eseidelGoogle** [comment]
@Hixie assures me this is a feature. :)  And that I'm just late to the party.

**Comment by eseidelGoogle** [comment]
@rmacnak-google informed me that the original example in comment 0 should produce an exception in --checked mode in the VM, which it does:

```
Unhandled exception:
type 'WhereIterable' is not a subtype of type 'List<int>' of 'items' where
  WhereIterable is from dart:_internal
  List is from dart:core
  int is from dart:core

#0      main (file:///src/dartdoc/main.dart:2:29)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by eseidelGoogle** [comment]
My new favorite part of this is that:
```
  Subclass bar = new Superclass();
```
is a (strong mode) analyzer error:
`ERROR: Type check failed: new Superclass() (Superclass) is not of type Subclass`

But this:
```
  Superclass foo() => new Superclass();
  Subclass bar = foo();
```
is not. :)

**Comment by eseidelGoogle** [comment]
I'm not sure there is anything to do here.  Happy to close.  Just me learning to Dart.

**Comment by leafpetersen** [comment]
> My new favorite part of this is that:

Yes.  This is a bit ad hoc, but basically if we see you do something that is 100% guaranteed to fail a runtime cast (i.e. in this case assigning a new instance of the wrong type to a typed variable) we issue an error.  But we don't try to look "through" function calls to detect this.
