### ISSUE TITLE
Closure conversion: length is always renamed

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#28131]
_From @karlklose on November 8, 2016 5:39_

Due to the `File.length()` method, closure conversion renames property accesses to `length`, which seems to bypass some optimizations in the VM and causing slow performance for lists.

_Copied from original issue: dart-lang/kernel#43_

**Comment by lrhn** [comment]
It's probably a breaking change to make `File.length` a getter, but it's one more nail for `dart:io` version 1's coffin. We should seriously consider a rewrite for Dart 2.0.

**Comment by peter-ahe-google** [comment]
It's a breaking change no matter what number you use. The key thing to consider is what is the benefit of a certain change, and what is the potential impact of making that change.

I'd argue that the potential impact of making this change is minuscule, because we've push Dart much more as a web platform than a server platform.

It may make sense to create a new bug to track the possibility of changing dart:io. This bug is about if someone creates a method with the same name as an important getter, it can cause problems. Those problems are mitigated by strong mode.

**Comment by sjindel-google** [comment]
I believe this bug is obsolete. The current design of closure conversion doesn't rename property accesses.
