### ISSUE TITLE
Changelog should mention new assert with message feature

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28134]
Right now it just have an entry for DDC, but this should be listed as a general feature:
https://github.com/dart-lang/sdk/issues/24213

**Comment by mit-mit** [comment]
@munificent, something for you?

**Comment by munificent** [comment]
> @munificent, something for you?

No, I added the one for DDC. :)

It's up to each person on the Dart team to add their work to the CHANGELOG if it's user-visible.

**Comment by mit-mit** [comment]
@munificent this is a general language features implemented in all parts of the stack. So individual comments by each tool in our stack is *not* what we need! What we need is a general comment detailing what the new language feature actually is.

And it looks like in this case we implemented something different from the DEP, so some kind of spec/docs is especially needed.

**Comment by lrhn** [comment]
Agree. When all the flags are removed, we should add an entry to the CHANGELOG. Maybe something like:
> Allow a second optional argument in `assert` statements, e.g., `assert(floo >= 0, "The floo is too damn negative")`. The message can be any object, and it is accessible as `AssertionError.message`.

**Comment by mit-mit** [comment]
Lasse, we are pretty much there, see https://github.com/dart-lang/sdk/issues/24213#issuecomment-267581717, and I will make sure that one gets done before we cut stable.

**Comment by munificent** [comment]
> So individual comments by each tool in our stack is not what we need!

I think that's useful in the interim when the current state of reality in the repo is that only some implementations support it.

> What we need is a general comment detailing what the new language feature actually is.

Yes, absolutely. My hope is that whoever is the *last* one to add their implementation to the CHANGELOG can collapse them all into a single entry.

My goal here is to have some sort of process where the people landing changes are also the people updating the CHANGELOG. Since any given person is usually only responsible for a single implementation, it's hard to dictate that one of them should write the CHANGELOG entry stating that *all* implementations are done. They can't be expected to know that.

But, if they go to add their entry to the CHANGELOG and see that all of the other implementations are there already, maybe they can know enough to collapse them together? Or maybe we just have someone who does have that global knowledge do a pass through the CHANGELOG right before a release?

Either way, if we let individual implementers add implementation-specific entries to the CHANGELOG, at least the information is there. We can tweak the representation later, but if we let people commit user-facing changes without updating the CHANGELOG at all, then it's very hard to know what's in the release.

**Comment by mit-mit** [comment]
> Yes, absolutely. My hope is that whoever is the last one to add their implementation to the CHANGELOG can collapse them all into a single entry.

I think we are speaking past each other here -- I wrote my comments specifically with this issue in mind, as this is already supported everywhere, so there is no last one. And I am hoping for a somewhat longer entry than "We now support asserting with a message", or an up to date specification entry we could link to (the bug says we implemented something different from the spec).

> My goal here is to have some sort of process where the people landing changes are also the people updating the CHANGELOG. 

Yes, that sounds fair in general for partially implemented things.
