### ISSUE TITLE
Specify covariant overrides

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28164]
This is the specification issue for #27486 

- [x] 1.50 spec
- [x] 2.0 spec

**Comment by mhausner** [comment]
Please publish a formal spec so I can implement this in the VM.

**Comment by eernstg** [comment]
We have been working on a document (docs/language/informal/covariant-overrides.md) about this feature in this [pull request](https://github.com/dart-lang/sdk/pull/28176). We finally reached a workable solution to the syntax issues (and I finally had some contiguous time to get an informal spec extracted ;-). You'll find  the informal spec at the beginning of the document, which should be suitable for implementation. For convenience, [here is a direct link to the current version](https://github.com/dart-lang/sdk/blob/7beccc2fbb1de0abb4ce1464256b2a8549c89029/docs/language/informal/covariant-overrides.md).

**Comment by eernstg** [comment]
The informal specification has been merged into the sdk repository, it's now available [here](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-overrides.md).

**Comment by eernstg** [comment]
A CL introducing covariant overrides in the context of Dart 1.50 is available [here](https://codereview.chromium.org/2678003002/).

**Comment by dgrove** [comment]
Can this be closed?

**Comment by eernstg** [comment]
The [abovementioned CL](https://codereview.chromium.org/2678003002/) has been landed, and that addresses this issue for 1.50 (first bullet).

We do not have a language specification for 2.0, but we do have informal specs for covariant parameters: [induced by keyword](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-overrides.md), [induced by class covariance](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-from-class.md). However, this issue is about the full specification, not the informal specs. So we cannot yet close it: We need a full 2.0 specification for covariant parameters.

**Comment by eernstg** [comment]
Marked the 1.50 specification as complete because no more work will be done specifying Dart 1.x.
The informal specifications mentioned [above](https://github.com/dart-lang/sdk/issues/28164#issuecomment-288014982) still need to be integrated into `dartLangSpec.tex`.

**Comment by eernstg** [comment]
Added milestone for reaching the level where the feature specification of covariant overrides is stable. In particular, [this CL](https://dart-review.googlesource.com/c/sdk/+/37664) needs to be landed or abandoned.

**Comment by eernstg** [comment]
Removing the Dart 2 milestone: [Said CL](https://dart-review.googlesource.com/c/sdk/+/37664) has now been landed, and the only remaining task is to integrate the feature spec (all of it, not just that update) into the language specification, which is not blocking Dart 2.

**Comment by eernstg** [comment]
Closing: This feature was made part of dartLangSpec.tex in 614ae7f362ac2df8500c050862e76c4fc66b8822.
