### ISSUE TITLE
Override equality operator for error and exception classes

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#28222]
I want to use a pattern like this when testing exceptions:
```dart
expect(() => ..., throwsA(equals(new XError('specific message'))));
```

However, this is not possible when using core classes, like `ArgumentError`, because they do not override equality stuff.

**Comment by lrhn** [comment]
We don't generally override equality unless there is a specific equality on the type that is significantly more "natural" than all other possible equalities. For errors to work like you want them to, we would be picking some properties - the message, or constructor arguments (which constructor, if there is more than one), or ... - to compare while ignoring other properties - e.g., the stack trace. It's not clear that there is a most natural equality relation to pick, so we prefer not to pick any.

Using identity as equality is a reasonable choice - also because checking equality of all properties, including the stack trace, would likely be equivalent.

It seems your use-case is primarily unit testing (which is good, you shouldn't be making too many assumptions about exactly which error is thrown in normal code), and hopefully only for errors that you throw yourself (again, don't make too many assumptions, any error will do to report a failure, the subclasses are only for convenience and reusable error messages).
I don't think that usage is significant enough to warrant a change.

**Comment by floitschG** [comment]
Extending Lasse's comments:
In general we keep a strong distinction between exceptions and errors.

Exceptions are things that should be handled by the program. These are things that can happen in perfectly legal programs (although it should be rare: "an exceptional event").
Since they must be dealt with by the program they have several characteristics:
1. the reason (and all necessary data) is program readable.
2. they should be documented in dartdoc
3. they should have their own type, so that a `on X catch` can deal with it.
4. they don't contain a stacktrace by default. Allocating stacktraces is expensive and if the program deals with the exception anyway, there is no reason to spend time on it.

Errors, on the other hand, are when the programmer made an error. They should never happen in production. Programs should not need to deal with them, except for reporting/logging.
As such they have different characteristics:
1. the reason (and all the data) is human readable.
2. the conditions should be documented in dartdocs, but their type should not. As a developer I don't need to know if passing in -1 throws a `RangeError` or an `ArgumentError`. In both cases, the user of the API did something wrong and should fix it.
3. there is no need for a specific type: the program should not deal with specific errors. A `on ArgumentError catch` doesn't make sense: the developer should make sure that error isn't thrown in the first place. Basically, all errors should always be caught in a catch-all clause, since we are catching something we didn't anticipate (otherwise we would have fixed the reason for it in the first place).
4. they contain stacktraces by default. Since errors should never happen, we are willing to spend more time constructing the stacktraces. Since errors should usually go to the developer (for debugging), they are also generally helpful.

I hope this explains why errors don't need to have an equality that deals with its content. 

For unit tests, where bad API calls are tested, we generally recommend to just do `is` checks, to make sure that the reason for the error is actually the one we anticipated.
