### ISSUE TITLE
ImmutableMap.putIfAbsent is unsupported operation

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#28241]
```dart
main() {
  (const { "Foo": "Bar" }).putIfAbsent("Foo", () => throw "Missing value");
}
```

This program fails, complaining that "Unsupported operation: Cannot set value in unmodifiable Map".

However, I'm not setting a value in a map: I'm trying to avoid looking up the same object twice.

**Comment by lrhn** [comment]
This is deliberate. An unmodifiable map disallows all operations that *can* change the map, whether they do or not. We don't want to get into the details of whether `map[key]=value` actually changes the map if `map[key]` is already `value` or whether `map.clear()` should be allowed on an empty unmodifiable map.
If we had a separate interface for "read-only maps", it would not have a `putIfAbsent` method, and that is how we decide which methods to not implement.

I can see that `putIfAbsent` can be used in a way that never actually puts anything, even if the element isn't there, but I don't think we want to special-cast support for that particular case on unmodifiable maps. It's too clever. It's much easier to say "methods that can change the map, don't work at all" than describing for each method *when* it fails. To be honest, if I had to implement the read-part of `putIfAbsent`, I would have thrown immediately when recognizing that the key isn't there, and not called the `orElse` function at all. There isn't one clear semantics for a partly functional method, but there is one for a fully non-functional one, so that's the one we use.

The error message could probably be improved, though.

**Comment by peter-ahe-google** [comment]
Please reconsider: putIfAbsent is a special case that doesn't necessarily modify a map, this is because `putIfAbsent` is special, it's name might be confusing, but it's shorter than: `getValueIfContainsKeyOtherwiseCallCallbackThatCanDefineKeyUnlessThisMapIsUnmodifiable`.

**Comment by lrhn** [comment]
But should it throw if the key isn't there, or call first the function and then throw? And why? 
It seems like specializing for a specific use-case.

My guess is that you can most of the same effect by using a helper function like 
```dart
getIfThere(Map map, key, [orElse()]) {  
  var result = map[key];
  if (result != null || map.containsKey(key)) return result;  // Only second lookup if value is null.
  if (orElse != null) return orElse();
  throw "not there";
}
```

You could argue that we should have a function like that on `Map` (and I don't disagree - personally, I'd like to have `MapEntry? lookup(key)` and `MapEntry lookupOrInsert(key)` where the MapEntry allows you to read or modify the associated value without further lookups), but changing the `Map` interface is not something we do easily (sadly!).

Using `putIfAbsent` for something it's not intended for (it *is* intended for *putting* a value, avoiding that by throwing is a cute hack, but not an intended feature), and then specializing it for that use, is something I'd prefer to avoid. I'd rather work towards adding other features to do that, even if it might be harder to get through.

**Comment by peter-ahe-google** [comment]
> It seems like specializing for a specific use-case.

It's generalizing to handle a common use case.

> Using `putIfAbsent` for something it's not intended for (it *is* intended for *putting* a value, avoiding that by throwing is a cute hack, but not an intended feature)

This is exactly what `putIfAbsent` is intended for. The name may imply something else to you, but that is a matter of naming, not intention. I can say so with high confidence as the method was originally added on my request modeled on `at:ifAbsentPut:` from `Smalltalk` where this method often is used in a similar way (using non-local return) see [a Smalltalk manual](https://www.gnu.org/software/smalltalk/manual-base/html_node/Dictionary_002daccessing.html). 

Even if we were able to modify the map interface, I'd still argue that map entry aren't a sufficient replacement. The problem is of performance: an implementation based on map entries is much slower than using open addressing directly on an array. Consequently, if you introduce map entries you either have to create temporary objects (making the lookup method have reduced performance compared to operator []) or generally reduce performance of maps by dictating a sub-optimal implementation strategy for everyone not needing map entries.

Fortunately, making this change to `putIfAbsent` is rather simple, and shouldn't break any existing programs with reasonable behavior.

So again, please reconsider.

**Comment by lrhn** [comment]
> This is exactly what putIfAbsent is intended for.

It might have been when it was introduced, but the name is wrong for that behavior and the intent was never documented, so by now, the intent is actually to be used for putting a value if there isn't one already, and not a clever workaround for that. I say that as the one who most recently updated the documentation for the method (and who wrote the `UnmodifiableList` mixin).
(If you liked it, you should'a put a doc on it!)

It's true that an entry-based API has more overhead that direct access - for allocating the entry object and checking for concurrent modification. On the other hand, it allows doing several different updates without having to add specialized methods on the map class for each.


I think the `at:` message in Smalltalk fails if the key isn't there. If we did that, you didn't need anything else. Instead we have the worst of all worlds - a get operation that returns null if the key isn't there *and* allowing null as a value. I hope NNBD will avoid that in most cases, but for your use, it seems you need to store null as a value (otherwise you could just check `==null` to see that the key wasn't there).

Do you actually need `at:ifAbsentPut:`, or is it really just `at:ifAbsent:`? I wouldn't mind adding a `V get(K key, [V ifAbsent])` method to `Map`, and it would work for unmodifiable maps too, but as usual, I don't get to make that decision alone :(.

**Comment by peter-ahe-google** [comment]
It's `at:ifAbsent:` I need.

**Comment by floitschG** [comment]
That is actually something we are considering:

`get(T x, [ifAbsent])`

(or similar).
The reason this would be interesting is, because we could then make a normal index-access non-nullable and throw if it's not there. The `get` (or `lookup`) function would simply return `null`.

**Comment by peter-ahe-google** [comment]
Yes, the direct "translation" of `at:ifAbsent:` would be the `get` method Florian mentions. In Smalltalk, what's called `at:` would be `[]` in Dart, and `at:put:` would be `[]=`.

**Comment by floitschG** [comment]
I created another issue for this: #28272 
Let's track the feature request there.
