### ISSUE TITLE
Flaky: lib/math/coin_test is flaky by design

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#28256]
This test chooses a random seed and then flips a coin 10,000 times.  It expects no more than a 10% difference between the number of heads and the number of tails.  Occasionally this will flake:

```
coin_test seed: 27477
Heads: 5241
Tails: 4759
Ratio: 1.1012817818869511
```

It doesn't happen often, but it might be a good idea to rewrite this to use a fixed seed.  @a-siva

**Comment by lrhn** [comment]
It is flaky by design, but expected to not flake very often (if at all).

This is, IIRC, a regression test for a random implementation that wasn't actually random enough on the last bit. The idea was to make something that did test randomly, to avoid testing just hitting a sweet spot and not seeing a problem somewhere else. Then the test was repeated enough that the odds of failing (if the RNG is truly random) is less than one in a million. (Well, I thought we did that, not sure if it was actually landed, see https://github.com/dart-lang/sdk/issues/6317).

Maybe we have to up the rounds because the RNG isn't truly random.

**Comment by kmillikin** [comment]
I don't think we plan on changing this test.
