### ISSUE TITLE
run / runSync fails on Mac for "pub global" activated packages (which / type problem on Mac)

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28332]
It works if I specify the path e.g.
     
    # Grinder - passes the first param to Process.runSync
    run("/Users/mikemitterer/.pub-cache/bin/sitegen", arguments: [ "-c" ]);

it fails if I use it this way:  

    run("sitegen", arguments: [ "-c" ]);

.pub-cache/bin is on my PATH - sitegen works from the commandline

Reason - you are using internally `which` to determine the path to the executable.
`which` fails for pub global activated apps on Mac. `type` works.

Try it e.g. with stagehand.

**Comment by nex3** [comment]
I'm not sure why I was assigned here... I don't think it's a pub issue. We're putting executables on the path in a totally normal way, so if infrastructure can't find them it's probably a bug in that infrastructure.

**Comment by natebosch** [comment]
I'm able to run pub global activated packages on mac and linux with `Process.runSync` and `/usr/bin/which` finds them (since I do have `$HOME/.pub_cache/bin` on my `$PATH`). Note that our help docs used to reference `~/.pub_cache/bin` and we updated to `$HOME/.pub_cache/bin` since it's more reliable. Not sure if that could be impacting you here.

I can't repro this issue, if this is still a problem for you please add another comment with more details and we can investigate.
