### ISSUE TITLE
Uri() allows invalid path element

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28359]
```dart
main() {
  var uri = new Uri(path: "//");
  print(uri.toString()); // prints ////
}
```
According to RFC 3986 (https://www.ietf.org/rfc/rfc3986.txt)

>  If a URI   does not contain an authority component, then the path cannot begin  with two slash characters ("//")

May be it makes sense to throw an exception in constructor in this case?

**Comment by lrhn** [comment]
The URI Reference `//` is parsed as an empty authority and no path. If you check RFC 3986, it says:

>```
>relative-ref  = relative-part [ "?" query ] [ "#" fragment ]
>
>relative-part = "//" authority path-abempty
>               / path-absolute
>               / path-noscheme
>               / path-empty
>```

so we match the `"//" authority path-abempty` production because `authority` can be empty (through `host` and `reg-name`) and so can `path-abempty`.

**Comment by sgrekhov** [comment]
It seems for me that there is still some issue here.
```dart
  var uri = new Uri(path: "", scheme: "", host: "", userInfo: "");
  print(uri.toString()); // prints //

  uri = new Uri(path: "//", scheme: "", host: "", userInfo: "");
  print(uri.toString()); // prints ////
  print(uri.authority); // prints an empty string
  print(uri.path); // prints //
```

In the second case we have `//` then an empty `authority`  and `path` started with  `//`

**Comment by lrhn** [comment]
Those cases look correct to me.

The empty `userInfo` is omitted in the `toString` (because an empty user-info is considered equivalent to no user-info, and not showing it is a kind of normalization). 
An empty scheme is considered equivalent to no scheme (because schemes can't be empty anyway)

That leaves us with an authority (because you specify `host`, you get an authority, so the URI string will start with a `//` to initiate the authority).
That is followed by an *empty* authority and then the `//` of the path.

That is correct behavior - the URI does contain an authority (an empty one) which is different from not containing an authority, so the RFC rule about URIs without an authority does not apply.

The leading "//" is not part of the authority, it is a delimiter that signifies that there is one. That's why it is in the `toString` but not in `uri.authority` (like `?` delimits the query, but isn't part of it).

**Comment by sgrekhov** [comment]
Ok, thank you. But let's go back to the initial example:
```dart
  var uri = new Uri(path: "//");
  print(uri.toString()); // prints ////
  print(uri.hasAuthority); // prints false
  print(uri.path); // prints //

```
Here we have no autority (`uri.hasAutority == false`). Why URI is `////`? I believe that here we have `//`, then empty `autority` and then  `path //` which is wrong

**Comment by lrhn** [comment]
Oooh, yes that *is* a bug. It should say that it has an authority.
Seems some logic only existed in the `toString` method, and when I added `hasAuthority`, that was no longer a safe approach.

**Comment by lrhn** [comment]
Fixed in the above CL.
