### ISSUE TITLE
exception when analyzing a non-strong mode project with a strong mode sdk

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28384]
Context here: https://github.com/flutter/flutter-intellij/issues/622

```
NoSuchMethodError: The getter 'addedFiles' was called on null.\nReceiver: null\nTried calling: addedFiles
Object._noSuchMethod (dart:core-patch/object_patch.dart:44)\n#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)\n#2      ContextManagerImpl._computeFlushedFiles (package:analysis_server/src/context_manager.dart:1059)\n#3      ContextManagerImpl._destroyContext (package:analysis_server/src/context_manager.dart:1288)\n#4
```

This is when the new analysis driver is enabled. This is blocking rolling the latest sdk into flutter; fuschia is seeing this as well. We need to fix this - or disable the new driver - and roll a new sdk.

**Comment by scheglov** [comment]
We require that each SDK, strong mode or spec mode, has summary.
`EmbedderSdk.getLinkedBundle()` returns `null` in spec mode.
There is nothing to fix in the analysis driver.

We could make `EmbedderSdk` always use strong mode.

**Comment by bwilkerson** [comment]
> You know more about `EmbedderSdk`, does it need to run in spec mode?

`EmbedderSdk` is only used when there is an `embedder.yaml` file in a package. To the best of my knowledge, 'flutter' is the only package that includes this file, so AFAIK it would be safe to say that packages that use an `embedder.yaml` file to control the SDK require dependent packages to be analyzed in strong mode.

Note, however, that I said more than you did. If we just change `EmbedderSdk` to always use the strong mode summary, then we could end up analyzing code in the dependent package using spec mode and the SDK using strong mode. I don't know whether that would create any problems, but we might want to propagate the "strongness" out to the dependent package in order to be sure.

**Comment by scheglov** [comment]
Yes, I realize that just making `EmbedderSdk` strong is not enough.
We need to make the whole context to use strong mode.
Any packages are analyzed in the context / driver will also be analyzed in strong mode.
Do I miss something?

**Comment by bwilkerson** [comment]
Not that I know of.

**Comment by scheglov** [comment]
An alternative solution: generate both `spec.sum` and `strong.sum` in Flutter tools, and change `EmbedderSdk` to look for the correct one depending on analysis options, as the other SDK impleentation does.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2627423004/

**Comment by devoncarew** [comment]
Thanks!

@whesse, this is an important enough fix (blocking the roll of the latest dart dev sdk into flutter) that we should do a new dev sdk.

**Comment by scheglov** [comment]
@devoncarew `EmbedderSdk` was [fixed](https://github.com/dart-lang/sdk/commit/c5b994750e98982c3d1ff733bc799bfff01f5d87).
Should we close this issue?
