### ISSUE TITLE
Reify the correct function type when covariant parameters are inherited from a mixin application

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28395]
I'm in the middle of implementing correct tear-off types (#27484) for covariant overridden methods (#27486) in DDC and I ran into an issue I don't plan to fix right now. Filing a bug so I can link to it. Consider:

```dart
class M1 {
  method(covariant int a, int b) {}
}

class M2 {
  method(int a, covariant int b) {}
}

class C extends Object with M1, M2 {}
```

Assuming we stick with the current plan of reifying all covariant parameters using Object, then this:

```dart
new C().method;
```

The reified type should be (Object, Object) → because C inherits the mixin application of M2 and M1 and along that inheritance chain, both parameters to `method()` end up marked `covariant`.

Unfortunately, the way covariance inheritance is tracked in the analyzer doesn't handle that. It stores it on parameters for actual declarations., but there's no actual source declaration of a version of `method()` where both parameters are inheriting `covariant`. It's only in the dynamic application of M1 as the superclass of M2 where we get an inheritance chain that covers both.

**Comment by munificent** [comment]
cc @leafpetersen @jmesserly

**Comment by lrhn** [comment]
This particular example could be fixed by using `int` as the bound (it is the least upper bound), but that doesn't work in general.
```dart
class C {
  method(covariant Object a, Object b) {}
}
class D {
  method(int a, covariant int b) {}
}
class E = C with D;
```
I can't see a good way to actually implement `E.method` without introducing a new method implementation on top of the one inherited from `D`.

**Comment by munificent** [comment]
> or copying and modifying the D method into the mixin application (which gives code duplication).

I think that's probably what the user would intuitively expect to happen.

> One option is to allow strong mode to disallow such mixin applications (superclass has covariant method parameter and mixin doesn't) if the mixin doesn't declare it in its supertype.

Yeah, we could do that. It might be the right conservative approach for now. But, man, explaining that error to users is going to be impossible.

**Comment by eernstg** [comment]
This case is covered by the informal specification already: Both parameters of `method` are covariant, in both examples. So the analyzer should report that the first parameter of `method` in class `Object with M1, M2` and in class `C with D` is covariant, even though that parameter isn't covariant in `M2` resp. `D` (it is not just lacking the modifier `covariant`, it actually isn't covariant).

**Comment by munificent** [comment]
Yes, I agree the behavior is well specified. This issue is because DDC doesn't implement this corner case correctly yet.

**Comment by eernstg** [comment]
Sorry, I wrote it like that because my first thought was 'oops, did I forget that case?'. But I _was_ also considering the implementation. ;-)

A real issue might be that the analyzer needs to work on the mixin applications (such as `C with D`) rather than referring directly to the class that delivers the mixin (here, `D`). I'm not sure, but my impression is that when a `ClassElement` has one or more `.mixins`, each of which is an `InterfaceType` which has a `.classElement`, the class elements directly represent the classes from which the mixins are obtained, and there is no representation of the mixin application. So you won't find an object representing the mixin applications `C with D` or `Object with M1, M2` anywhere, you'll only find the classes `C` and `D` and `M1` and `M2`. This makes it more difficult to give members of the mixin applications any properties that the mixin-delivering classes don't have (say, there's a parameter which is covariant), so there might be a need for introducing a direct representation of the mixin applications, or at least thinking about such a representation when it is somehow emulated by other objects.

**Comment by munificent** [comment]
Yes, I think you're on track. In general, the analyzer seems to assume most objects reasoned about by the type system point back to some source location on disc. That may have been true at some point, but it's definitely not true now, and it makes it difficult to deal with things like function types which may be synthesized out of thin air.

Mixin applications are another example of that.

**Comment by jmesserly** [comment]
@leafpetersen thoughts on current priority of this?

Here's the current behavior:
```dart
class M1 {
  method(covariant int a, int b) {}
}
class M2 {
  method(int a, covariant int b) {}
}
class C extends Object with M1, M2 {}

main() {
  print(new C().method.runtimeType);
}
```
dartdevk correctly prints: `(Object, Object) => dynamic`
dartdevc incorrectly prints: `(int, Object) => dynamic`

**Comment by leafpetersen** [comment]
Probably pretty low priority. Fairly unlikely anyone will run into it in web code, and once DDC moves to kernel it should be essentially irrelevant.

**Comment by srawlins** [comment]
Closing as DDC now uses kernel exclusively; there may still be a theoretical issue in analyzer, but its been many moons. Please re-open if still an issue.
