### ISSUE TITLE
Mirror: Infer return type of lambdas and anonymous closure

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#28396]
There is no way in dart to declare the return type of a lambda function or an anonymous closure. But dart analyzer can infer it.

Seems like mirror library cannot do the same. When I try to reflect the return type of this lambda, it returns `dynamic`. But it is quite clear that it is statically typed and returns `String`.

```
muxer.get('/user/:id', (String id) => id);
```

Is it possible for mirror to infer return type of the lambda or an anonymous closure.

**Comment by lrhn** [comment]
Correct. The *static* return type of a function expression using arrow notation is the static type of the body expression. The runtime return type of the function is just `dynamic`. This is necessary because the VM doesn't contain an implementation of the static type system, so it has no way to know the static return type. This is just for arrow-notation function expressions, anything using a block body is dynamic both statically and at runtime.

The mirror library just looks at the actual runtime type, and, since it is just part of the VM, it can't figure out the static type either.

So, no.

**Comment by rmacnak-google** [comment]
Mirrors are not just part of the VM. Both Dart implementations provide them, and source mirrors, which cover the reflection used in this issue, do not require a runtime.

Mirrors give access to declared parameter and return types, and unfortunately Dart doesn't have a way to declare a return type on closure expressions. Inferred types are also as yet not part of Dart.  So currently you'd need to do something like

```
String f(String id) => id;
muxer.get('/user/:id', f);
```

**Comment by leafpetersen** [comment]
Inferred types will be reified via kernel in the future, but there are no plans to back port this.  I would expect that once inferred types are reified in the VM, the mirrors library will pick them up.
