### ISSUE TITLE
No warning when superclass returns void and subclass doesn't

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#28405]
https://dartpad.dartlang.org/7e91971bf9428a4e7aa389cf373bb750

```
class A {
	void doesNotError() {}
  int doesError() => 1;
}

class B extends A {
  @override
  int doesNotError() => 1;
  
  @override
  void doesError() {}
}
```

Both of these should be errors, but only `doesError` causes an error.  It's a warning in non-strong mode and a (slightly different) error in strong_mode, but regardless, the `doesNotError` should also produce an error in my opinion?

**Comment by lrhn** [comment]
The `doesNotError` is a valid Dart 1 and strong-mode override. You are allowed to specialize a `void` function to return something. It's a "safe" override in that nobody calling `A.doesNotError` will ever look at the returned value, so it can't be wrong.

**Comment by bwilkerson** [comment]
The `@override` annotation is a red herring. It doesn't change the semantics of what a valid override is. I've changed the title to reflect that.

**Comment by eseidel** [comment]
How I got into this was that was using `@override` in all of my (sprawling number of) subclass overrides to make sure to catch cases where I changed the signature of the superclass method (or mis-typed one of the subclass ones).  That seems to be it's intended use?
https://api.dartlang.org/stable/1.21.1/dart-core/override-constant.html
But unclear if I'm using that correct either. :)

I was surprised when I changed the type of one of my overrides that it didn't error (hence this bug), yet when I changed the type in a different way it did.

If this is an intentional feature of the language, that's fine.  I guess I expected the language (and/or `@override`) to cause stricter behavior here.

**Comment by bwilkerson** [comment]
> That seems to be `@overrides`'s intended use?

Actually, no. The language defines the semantics of what is and is not a valid override. The annotation is used to declare that a method is being defined *because* it is overriding a method in a supertype and that a diagnostic should be produced if that ceases to be the case (presumably because the overridden method was removed).

**Comment by lrhn** [comment]
I think the current behavior is working as intended. 
There is no warning in this case because you still override the superclass method correctly.
If you had overridden it incorrectly, you would have gotten a warning from the type system.
If you didn't override anything any more, you would have gotten a warning from the analyzer because of `@override`.
From both perspectives, your code was flawless, so "no warning" is correct.
