### ISSUE TITLE
Dart 2 JS: Null pointer converted to 'undefined' string

### ISSUE THREAD

**Issue by elielevysunwave** [dart-lang/sdk#28409]
We have a map in dart with no key value pairs defined in it (an empty map.)

Map m = {};

In dart when we do:

print('${m["test"]}');

It prints null.

When compiled to JS and run inside Chrome, it prints:

undefined

This caused a bug in our application in production.

This problem does not occur in Dartium. We can run the compiled JS in Dartium, and it prints null.

Our dart version is 1.21.0
Dart VM version: 1.21.0 (Wed Dec  7 06:44:15 2016) on "macos_x64"

We tested it in Chrome for Mac and Windows. Same results.
Chrome Version 55.0.2883.95 (64-bit)

**Comment by sigmundch** [comment]
@elielevysunwave - It's quite possible, but I have not been able to reproduce the issue. We use both `null` and `undefined` in the code compiled from dart2js. This was part of the design of dart2js to make the code we generate more succinct and efficient. We do, however have special logic in our `toString` implementation make them both stringify as `"null"`. 

Any time you call `print`, we first call `toString`, which makes `undefined` disappear. The only way I can show in the console that there is an undefined value is if I use something like `window.console.log`, which doesn't call toString first.

If you try your example in https://dartpad.dartlang.org/, are you able to reproduce it there too?

**Comment by elielevysunwave** [comment]
Here is the code to reproduce it in dartpad:

import 'dart:html';

void main() {
  Map m = {};
  String id = m['id'];
  InputElement input = new InputElement();
  input.setAttribute('data-id',id);
  var value = input.attributes['data-id'];
  print('value = $value');
}

The output in the console is:

[{"id":"undefined"}]

when you run it in dart, or the js version in Dartium it sends:
[{"id":"null"}]

Thanks for your help,

Elie

**Comment by sigmundch** [comment]
Ah - yes, that makes sense. The issue here is that your null value is translated to a string under the hood inside the DOM APIs. The `setAttribute` call is getting `undefined` but when you read `intput.attributes` you are getting a String value `"undefined"` for the attribute instead.  You'll see that the following code prints "true, false" and "false, true" if you add it at the end of your example:

```dart
print("before and after:");
print("is null? ${id == null}, ${value == null}");
print("is String? ${id is String}, ${value is String}");
```

Unfortunately, I don't believe this is something we can fix on our end. We need to preserve how we use null and undefined interchangeably to keep apps small and fast. My recommendation is that you wrap where you rely on this to use a check against null first, so you don't set null/undefined attributes in the first place or do it in a predictable way.

For example, wrap calls to setAttribute to check for null first, or use the `??` operator to provide a value when the data is null. For example:
```dart
input.setAttribute('data-id', id ?? "null");
```

**Comment by elielevysunwave** [comment]
I understand, and appreciate your attention to the issue.

However, It has a different behavior in dartium than chrome. That shouldn't
be the case. It should be consistent across the same platform.

This problem started after we upgraded to the latest dart version. In prior
versions we didn't have the problem.

Thanks again,

Elie


On Jan 17, 2017 4:40 PM, "sigmundch" <notifications@github.com> wrote:

Ah - yes, that makes sense. The issue here is that your null value is
translated to a string under the hood inside the DOM APIs. The setAttribute
call is getting undefined but when you read intput.attributes you are
getting a String value "undefined" for the attribute instead. You'll see
that the following code prints "true, false" and "false, true" if you add
it at the end of your example:

print("before and after:");
print("is null? ${id == null}, ${value == null}");
print("is String? ${id is String}, ${value is String}");

Unfortunately, I don't believe this is something we can fix on our end. We
need to preserve how we use null and undefined interchangeably to keep apps
small and fast. My recommendation is that you wrap where you rely on this
to use a check against null first, so you don't set null/undefined
attributes in the first place or do it in a predictable way.

For example, wrap calls to setAttribute to check for null first, or use the
?? operator to provide a value when the data is null. For example:

input.setAttribute('data-id', id ?? "null");

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/sdk/issues/28409#issuecomment-273308740>, or mute
the thread

**Comment by sigmundch** [comment]
I totally agree, and I wish we had consistent semantics everywhere as well. There are some corner cases where had to give up on consistency in order to have a fast runtime. These places where null/undefined show up is one such case. Numbers are another (we map numbers to JS Number, which means that in Dartium you can distinguish 1.0 and 1, but when compiled with dart2js you unfortunately cannot).

I'm actually surprised this changed for you recently though. I'm also curious about what changed on our end to make you run into this issue for the first time now. Before you updated to the lastest version, did you used to have the behavior like it is in Dartium today or like in dart2js?

Nothing jumps out as a change we did in dart2js that would change the behavior here, but maybe something changed on the Dartium side? @terrylucas might have some insights on that.

**Comment by elielevysunwave** [comment]
Thank you again.

My understanding is that this was working consistently as in dartium...

I need to check to be sure. This introduced a bug in our application in
production.

For sure it worked and works in dartium where we ran or QA testing prior
going live.

The feature was in production for at least a month. I am not sure our users
(that run the compiled js version in chrome) were using it until now that
they reported the problem.

I will let you know.

Thanks again,

Elie
