### ISSUE TITLE
dartk: Static setter/getter should be taken into account when resolving references

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28417]
From `tests/language/static_setter_get_test.dart`:

```
class Class {
  static set o(_) {}
  m() => o; /// 01: static type warning
  noSuchMethod(_) => 42;
}

main() {
  Expect.throws(() => new Class().m()); /// 01:
}
```

/cc @kmillikin & #28263

**Comment by lrhn** [comment]
This is actually an interesting case that I wasn't aware of :).

The spec says about the identifier expression `id`:
> Let *d* be the innermost declaration in the enclosing lexical scope whose
> name is `id` or `id=`. If no such declaration exists in the lexical scope, let *d* be
> the declaration of the inherited member named `id` if it exists.

That's not really well-defined since there can be both an `id` and an `id=` declaration in the same scope, so which one is it? It matters, because it's only a warning if one is static and the other is dynamic, and the program should have a semantics in that case.
Implementations favor the getter over the setter (reasonably, I'd say, but not mandated).

(Another interesting thing is that this looking at declarations includes abstract getters and setters too).

**Comment by mraleph** [comment]
Fixed in Fasta! Hooray.
