### ISSUE TITLE
analyzer package: parseGenericMethods enabled by default

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#28438]
The current package `analyzer` on pub (0.29.3) doesn't have support fo generic method activated by default.

This fails:
```dart
import 'package:analyzer/analyzer.dart';
main() {
  parseCompilationUnit('T foo<T>() {}');
}
```

Angular2 uses the method `parseCompilationUnit` in the pub transformer, so we have some errors when we use generic method in an angular app.

Please publish a new version of the analyzer 0.29 with `parseGenericMethods = true`.

**Comment by bwilkerson** [comment]
It will probably be a while before we publish such a version, but as a work around you could copy the code in analyzer.dart and modify the creation of the parser (line 112) to additionally set `parseGenericMethods` to true.

**Comment by xavierhainaux** [comment]
Your work around is what I do right now. But it means I have to use dependency_overrides and this is what I try to avoid.

I thought generic methods was an official feature: http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html
Why not just enable it by default?

**Comment by bwilkerson** [comment]
Rather than a dependency override, I was just thinking of a copy-paste style solution. :-) Ugly, but effective.

The feature is enabled by default on bleeding edge; we just haven't pushed out a new version of the 'analyzer' package that has it enabled, and pushing out a new version probably won't happen for a couple of weeks because of some other work that we want to finish first.

**Comment by xavierhainaux** [comment]
Ok, I can wait a few weeks ;-) Thanks

The copy-paste works for my own tools, but the blocking part is that `parseCompilationUnit` is used in Angular2 and I cannot change this code easily.
