### ISSUE TITLE
warn that custom-elements cannot use type-arguments

### ISSUE THREAD

**Issue by frank-rollpin** [dart-lang/sdk#28457]
I extended a DivElement with a mixin, and got surprising behavior when compiled to JS (works just fine in Dartium). Upon closer inspection, it turned out that the example works if we either not use mixin, or not call methods on the created instance (such as '..classes.add('tree-view')'). 

See the code and the exception below:

```dart
import 'dart:html';

class TreeViewNode<TValue> { }

class TreeViewGroup<TGroupValue, TItemValue> extends DivElement
    with TreeViewNode // works if we remove this line
{
  static final String tagKey = 'tree-view-group';
  int level = 0;

  TreeViewGroup.created(): super.created() {
    appendText('I am a tree view');
  }

  factory TreeViewGroup() => new Element.tag('div', tagKey);
}

main() {
  document.registerElement(TreeViewGroup.tagKey, TreeViewGroup, extendsTag: "div");

  document.body.append(new TreeViewGroup()
    ..classes.add('tree-view') // works if we remove this line
  );
}
```

```html
<!doctype html>
<html>
<head>
    <script defer type="application/dart" src="index.dart"></script>
    <script defer src="packages/browser/dart.js"></script>
</head>
<body>
</body>
</html>
```

Exception:
```
Uncaught TypeError: Cannot set property '$$TreeViewGroup_level' of undefined
    at _callConstructor_closure.TreeViewGroup$created [as $constructor] 
```

**Comment by sigmundch** [comment]
@frank-rollpin  thanks for filing the bug.

It seems the issue here is actually a result of the type-arguments in TreeViewGroup. We add the arguments to the constructor even though the html library doesn't expect them to be there.

Sometimes dart2js is able to optimize away how the type arguments are used, and you found two ways in which it does that :), that's why it looks so strange.

Because it is not possible to create custom elements without going through the DOM API, I don't believe we will have a way to specify the type-arguments in the DOM calls. Even now that we have generic methods, a single API like `document.createElement` won't work for different number of type-arguments.

I learn towards providing a warning about it instead, and practically ignore the type-arguments in dart2js. Meanwhile, you should be able to workaround this by removing the type-arguments in TreeViewGroup.

**Comment by sigmundch** [comment]
FYI - I just updated the title of the issue now that we know what's the underlying problem. Based on your examples, here is another repro that isolates the issue without mixins:

```dart
import 'dart:html';

class A<T> extends DivElement {
  int level = 0;
  A.created(): super.created();
}

main() {
  document.registerElement('x-a', A, extendsTag: 'div');
  var x = new Element.tag('div', 'x-a');
  document.body.append(x);
  print(x.runtimeType);
}
```

**Comment by sigmundch** [comment]
Turns out there is a secondary issue here: the order of the arguments in the constructor we generate are wrong and the type arguments should be added at the end.

Today we have:
```js
A$created: function($T, receiver) {
    receiver.$$A_level = 0;
    return receiver;
}
```

but we should generate `receiver` first.

For your specific example, this could circumvent the issue, but in the end you wont be able to provide type-arguments for this type, so I'd still recommend not using type arguments here.

The reason it might be useful is that if you have another subclass that always provides concrete types for the type-arguments and you only instantiate the subclass, then that code will be able to work if we fix the arguments order. 

For example if we had:
```dart
class B extends A<int> {
   ...
}
```

and we never created `A`, but create `B` instead.

**Comment by kevmoo** [comment]
We're going to deprecate this API.
