### ISSUE TITLE
analyzer doesn't narrow the type after an is-check when you're reassigning

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#28483]
```dart
void main() {
  var z = foo();
  if (z is B) {
    z = z.x;
  }
}

A foo() {
  return new B();
}

class A {}

class B extends A {
  A x;
}
```
https://dartpad.dartlang.org/713e0c7eadf3d54a3f4bafb25a13b4ec

This gives a strong-mode error on the `z = z.x` line in `main`. You can work around it by doing `z = (z as B).x`. It seems like analyzer should know that `z` is a `B` on the RHS of the first assignment to `z` in the `if` block.

**Comment by bwilkerson** [comment]
This is the correct behavior according to the specification. There is ongoing work to enhance the circumstances under which type promotion is applied, but I doubt we're going to do enough flow analysis that assignment would not prevent the application of promotion.

Also, because `B.x` has a static type of `A`, the type of `z` would only be `B` on the right hand side of the assignment, and we would have to be able to demote the type back to `A` for the rest of the block. But demotion isn't currently a concept in the specification.

**Comment by greglittlefield-wf** [comment]
Possibly related: https://github.com/dart-lang/sdk/issues/28428

**Comment by leafpetersen** [comment]
Improvements to type promotion are in the pipeline, but this is not currently planned.
