### ISSUE TITLE
strong mode LUB/GLB returns different results depending on order for top/bottom types

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#28513]
current behavior:
```dart
// LUB returns first type
LUB(dynamic, Object) == dynamic
LUB(Object, dynamic) == Object
LUB(Null, bottom) == Null
LUB(bottom, Null) == bottom
// GLB returns second type
GLB(dynamic, Object) == Object
GLB(Object, dynamic) == dynamic
GLB(Null, bottom) == bottom
GLB(bottom, Null) == Null
```

it would be nice to bring some consistency here. I think this is the desired behavior?
```dart
// for the purposes of these functions:
// bottom <: Null <: Object <: dynamic 
LUB(dynamic, Object) == dynamic
LUB(Object, dynamic) == dynamic
LUB(Null, bottom) == Null
LUB(bottom, Null) == Null
GLB(dynamic, Object) == Object
GLB(Object, dynamic) == Object
GLB(Null, bottom) == bottom
GLB(bottom, Null) == bottom
```
(naturally, non-nullable types might bring some changes to this)

EDIT: void is another type to consider, and `FutureOr<T>` where T is a top type.

**Comment by jmesserly** [comment]
Related issue here. Should `Null <: bottom`? that feels kinda wrong. Just chatted with @leafpetersen and we think it may be possible to fix that one

**Comment by MichaelRFairhurst** [comment]
Ping @leafpetersen instantly running into this with generalized void, as @jmesserly had predicted here. Perhaps that's ok, but GLB(dynamic, void) used to be dynamic and now its void even though GLB(void, dynamic) is unchanged.

This may not be a problem on the whole, but, its not a good sign for quickly supporting it.

**Comment by leafpetersen** [comment]
I'd say treat `void < Object< dynamic` for the purposes of `LUB` and `GLB`.

**Comment by stereotype441** [comment]
Added area-front-end since Leaf's proposed change would need to be made to both the analyzer and the front end.

**Comment by eernstg** [comment]
I think it is a slippery slope to try to introduce a micro structure on the subtype relation such that something like `dynamic <: Object <: void` is assumed (in any case `void` needs to be at the top, if we do this at all, because backward compatibility plus voidness preservation mandates that `void foo()` can be overridden by `Object foo()` and `dynamic foo()`, but not vice versa).

But we know that `void` cannot just be considered to be a proper supertype of all other types, because the discipline associated with expressions of type `void` cannot be maintained if `int x = print('Hello');` is considered to be a plain downcast. Similarly, no subtype relation can justify that `x.y` is OK for `x` of type `dynamic` even though `x` is not statically known to have a member named `y` (because we do not want to let `dynamic` be the bottom type, not even "sometimes"). So, no matter what, we need to consider `void` and `dynamic` to be something else than just two more types with a specific placement in the subtype relation.

One possible approach is to consider them to be `Object` _plus_ an extra bit (meaning "ignore this value" resp. "allow dynamic lookups"). Those extra bits are irrelevant to subtype related queries, but they must be taken into account in various situations (e.g., type checks on member lookup).

I would prefer to keep LUB and GLB clean, such that they consider `dynamic`, `Object`, and `void` as equivalent. Let's call them `top`, collectively. So we just have this:
```
LUB(top, X) == LUB(X, top) == top, for all X.
LUB(Null, bottom) == Null
LUB(bottom, Null) == Null
GLB(top, top) == top
GLB(Null, bottom) == bottom
GLB(bottom, Null) == bottom
```
This makes it a separate issue how to carry the remaining properties over to the result, and it may or may not work to do this in the same way for all purposes.

I do realize that it would be much easier to just decide that `dynamic <: Object <: void`, and get everything else as a consequence of that, but I'm not convinced that we can get the desired outcome. If that had been possible we would just have defined such an ordering and then made them separate types long ago!

**Comment by eernstg** [comment]
Sorry about not offering a solution here, but I felt the need to indicate that there is a potential problem, and we shouldn't ignore it. If everything just works as desired with `dynamic <: Object <: void` in some sense then Hurrah! ;-)

**Comment by leafpetersen** [comment]
> I think it is a slippery slope to try to introduce a micro structure on the subtype relation such that something like dynamic <: Object <: void

This is not what I proposed, sorry if it was unclear (I used `<` instead of `<:` deliberately, but vaguely). All I'm trying to do here is define a consistent answer for what LUB and GLB should say when given various combinations of the above.

**Comment by stereotype441** [comment]
Reopening since a similar fix will need to be made to front_end

**Comment by eernstg** [comment]
> This is not what I proposed, sorry if it was unclear (I used < instead of <: deliberately ..)

Right, I intended to make exactly the same distinction (vaguely ;-) by talking about a "micro structure on subtyping", rather than plain "subtyping". So we agree, presumably, that all the top types are considered to be the same type with respect to subtyping (i.e., `dynamic <: Object <: void <: dynamic`), but the `<` micro structure could be added to the subtyping hierarchy in order to run the regular LUB/GLB algorithms (and other, similar algorithms) and then automatically have the "extra bits" on the top type threaded through the computation.

This is a smart move, because we'll get all answers automatically: It determines how to thread the "dynamic bit" of the top type specified by the spelling `dynamic` through the typing of `b ? e1 : e2`, it disambiguates `void` against `Object` for class interface computations, etc.etc.

The point I was making is that this might not work as desired, no matter which `<` micro structure we choose.

In particular, we may wish to disallow `(b ? e1 : e2).foo(42)` even though the type of `e2` is `dynamic`, because the type of `e1` is `Object` which does not have a `foo`. In that case we'd have `dynamic < Object`. But we would then still allow it for all non-top types, e.g., where `e1` has type `int`, because LUB of `int` and `dynamic` would surely be `dynamic`. My point is: The subtyping microstructure won't thread the "dynamic bit" through the computation the way we want, no matter which ordering we choose for `<` among the top types. Maybe the natural rule for the conditional operator would be "for `b ? e1 : e2`, if `e1` and `e2` have type `dynamic` the type of the expression is `dynamic`; if one is `dynamic` and the other is `T` != `dynamic`, the type of the expression is `T`; if the types are `T1` and `T2`, respectively, the type of the conditional expression is `LUB(T1, T2)`.

Maybe we won't do that (now!), but I'm just not convinced that we can make the shortcut to decide on an ordering for `<` and then rely blindly on a general LUB/GLB algorithm.

**Comment by MichaelRFairhurst** [comment]
> One possible approach is to consider them to be Object plus an extra bit (meaning "ignore this value" resp. "allow dynamic lookups"). ...
>
> I would prefer to keep LUB and GLB clean, such that they consider dynamic, Object, and void as equivalent. ...
>
> ...
>
> This makes it a separate issue how to carry the remaining properties over to the result

I think this is an interesting mental model to apply here, and one that can be reduced (under many heuristics) to `void < Object< dynamic`.

So, in this case we only have two bits to worry about; we can assume Object has an empty bitmask.

0x0 = Object. Nothing special
0x1 = "has methods not statically known"
0x2 = "Not usable"

If we refer to a bitmask, then the only type left is 0x3. But what would that even be? It would be an unusable dynamic. Or, a void with unknown static methods. In either case, all usages would be an error, given that void can only be used for `e;`, `(e)`, `e as T`, and `return e` in a void function. None of these involve checking the 0x1 bit.

There are some convoluted examples of where we could maybe say that 0x3 is like a void that *can* be used where dynamism *affects* the result, ie, `e.x` is allowed on 0x3. However, that pretty much rules out all of the ways `void` isn't allowed to be used, except the operators you can't overload like `&&`, and `return e` where the outside isn't void. Doesn't seem useful at all.

So its really not a bitmap. What it really is is an enum.

So where in a bitmap, we'd have to choose which bits carry in which cases...in an enum, we just have to decide, which enum "wins" in a tie, in which cases.

Assuming that we want `GLB(notTop, Top)` to return the Top passed in (seems self evident), that just leaves the questions of `GLB(Top, Top)` and `LUB(Top, Top)` and it stands to reason that they should be opposites.

Therefore, we no longer have an enum, but an ordinal. And like a bitmap can have arbitrary bits (Object could have been 0x1), this ordered set can have an arbitrary order. 

Obviously this logic is a bit flawed -- we can't choose just any order, we have to choose the *right* order. But it at least establishes *somewhat* logically, that *some* an order is the correct approach.

**Comment by eernstg** [comment]
> Assuming that we want `GLB(notTop, Top)` to return the Top passed in (seems self evident)

Interesting! ;)

I suppose that should be `notTop`, or it should be `LUB` rather than `GLB`. If it's `LUB` then we actually have a probable counter example:
```dart
(b ? aDynamicExpression : 42).foo();
```
Should that be allowed? If we take the stance that it is an error to evaluate `42.foo()` indirectly in Dart 2 here, because it should be a compile-time error to evaluate it directly, we might want to have a rule which says "for conditional expressions, let `T` be LUB of the branches; if `T` is not a top type then the static type of the expression is `T`; if `T` is top then the static type of the expression is `dynamic` if both branches have type `dynamic`; it is `void` if any branch has type `void` (doesn't matter, that's an error in a subexpression anyway, if we don't change that ;-); otherwise it has type `Object`."

We could of course use the type `dynamic` if there is any `dynamic` anywhere (rather than when no other types are present), but I'm pretty sure that this will be considered a surprising loss of typing precision, especially if the expression is complex and large.

In contrast, when the interface of a class is computed, we would want `void` return types to "go away" if anything else is present, because it is allowed to override a void-returning method by a non-void-returning method (e.g., `int foo()` may override `void foo()`); again, `dynamic` as a return type should probably only be present in the result if it is present everywhere, possibly except for `void` (so if we have `void foo()` and `dynamic foo()` and `Object foo()` from superinterfaces, and the class doesn't declare `foo`, it's implicit interface would have `Object foo()`).

If there's a simple computation based on bit operators or a micro structure on the types or whatnot, I'm all for finding that and using it (that simplifies everything), but at this point is expect the best approach to be special treatment of the few situations where LUB/GLB and similar concepts are used.

**Comment by MichaelRFairhurst** [comment]
Before I finish reading!

> But I suppose that should be notTop, or it should be LUB rather than GLB. 

Yes, probably! I tend to get Top/Bottom backwards in my head, I intuitively view subtypes as higher in the type tree, instead of lower in the type hierarchy :( Its a bad intuition I still haven't unlearned 100%. Reading the rest from there though!

**Comment by leafpetersen** [comment]
I don't have strong feelings about `dynamic < Object < void` vs the opposite direction.  Putting `dynamic` at the top of the micro-structure is most "dart 1.0": if you have `dynamic` anywhere in there, it takes precedence.   The opposite direction gives you stronger error checking: if you have `Object` or `void` in there anywhere, then it takes precedence.

`dynamic` at the top is least likely to break existing code.  Not sure how much putting it at the bottom would break in practice, could be tested.

**Comment by MichaelRFairhurst** [comment]
Interesting counter-example. Yeah, I personally would prefer LUB(notTop, Top) to be Object based on this.

In fact, to make it more complicated, I'd want LUB(notTop, void) to be void, too.

Also, can we rely on rules like "for conditional expressions, let T be LUB of the branches; if ...", how would that affect LUB(Future<int>, Future<void>) ?

And in the case of unifying superinterface methods, isn't that GLB anyways?

So let's say that LUB of anything with void is void. And that LUB of Top with anything is Object, except LUB(dynamic, dynamic), in which case its dynamic (perhaps following from how LUB of anything with itself is itself, at higher priority than the rules I just defined).

That would seem to imply the opposites for GLB. So GLB(T, void) is always T (be it dynamic, object, ...). I'm not sure what the opposite of LUB(notVoid, notTop) implies about GLB. And GLB(dynamic, dynamic) would still be dynamic from the same self-comparison rules.

Then, unless I'm still backwards on something here, which is quite likely, that means that GLB((void) -> Object, (dynamic) -> void) would be (dynamic) -> Object. This seems pretty ideal to me.


Now the question of how this gets modeled with bits is not too crazy:

```
isDynamic = 0x1;
isVoid = 0x2;
lub_result.flags = (isDynamic & a.flags & b.flags) | (isVoid & (a.flags | b.flags));
```

and for glb, it'd be `(isVoid & a.flags & b.flags) | (isDynamic & (a.flags | b.flags))`.

**Comment by eernstg** [comment]
> I'd want LUB(notTop, void) to be void, too.

Agreed: If a branching (`?:`) shouldn't allow us to use the value of an expression of type `void` even though the other branch is a non-`void` _top type_, saying "when the other branch is a non-`void` _type_" is an obvious and reasonable extension.

> ... how would that affect LUB(Future<int>, Future<void>) ?

This is the same question as "how do these bits thread through composite type terms?". This is where we'd have an answer for free if we can stick to some notion of "dynamic < Object < void". But we may be able to handle it in the recursive case anyway: 

If `LUB1(void, T) == void` for all `T` then we could have rules like `LUB1(C<T1..Tk>, C<S1..Sk>) == C<LUB1(T1,S1),.. LUB1(Tk,Sk)>` when `C` is a generic class (and we may need to think a little before we let the same rule apply to typedefs). `LUB1` would then be the LUB we are using for `?:`. We may be so lucky that we can find a `LUB` that works everywhere, in which case there will just be `LUB` rather than `LUB1` for `?:`, `LUB2` for computation of class interfaces, etc.

> .. unifying superinterface method, isn't that GLB anyways?

We actually don't unify anything (Dart 1 did that, but Dart 2 won't). It is required that there is a method signature which is most specific, and that one wins. (The only computation done on this signature is to mark formal parameters as covariant if there is _any_ superinterface, direct or indirect, where that parameter is covariant; but that property is irrelevant to clients, it only affects code generation for method implementations, because they must perform a dynamic check of the type of each "covariant actual argument", i.e., each actual argument bound to such a formal parameter.)

However, I'm working on a feature specification which will handle the top type variants in this particular situation, and that might be a kind of a `LUB2`.

We would use `GLB` on the return types, though, and that might be a `GLB2`. We need to consider which decision is the right one to take, and then we can check out whether that can be expressed in a simple manner (say, with a single universal `LUB`).

We would definitely like to have associativity and commutativity, because we're operating on a set of method signatures that may contain more than two elements, and because there is no suitable ordering (it would be possible, but not pretty, to use the textual ordering).

**Comment by lrhn** [comment]
The way I see LUB, it's a way to pick a "safe approximation" to multiple types. That means that the ways you can use the LUB of two types must be the intersection of how you can use either of those types ("it's only safe for the approximation if it's safe for both").

If we look at safeness as what you can do to the type, then we can look at `o.foo` and `o.toString()`. The former is allowed on `dynamic`, but not on `Object` or `void`. The latter is allowed on `dynamic` and `Object`, but no on `void`.

That suggests to me a LUB of:
```
LUB(void, *) = LUB(*, void) = void  // void always wins.
LUB(Object, *) = LUB(*, Object) = Object (where * is not void).
LUB(dynamic, dynamic) = dynamic
LUB(dynamic, NonTop) = LUB(NonTop, dynamic) = Object 
```
The last line is the most surprising one, and the one thing that means this is not just `dynamic <: Object <: void`, but we do need a type that is a supertype of both `dynamic` and `NonTop`, so it needs to be a top-type. We don't *know* that `NonTop.foo` is allowed for all `foo`, so we cannot go to `dynamic` - that would allow *more* than one of the operands. We don't want `dynamic` to be infectious. The only solution is `Object`.

For GLB, it should probably allow using the result in any way that either operand can be used. It must be a subtype of both types.
That would mean:
```
GLB(NonTop, topType) GLB(topType, NonTop) = NonTop
GLB(dynamic, topType) = GLB(topType, dynamic) = dynamic
GLB(Object, void) = GLB(void, Object) = GLB(Object, Object ) = Object
GLB(void, void) = void
```
(Basically the opposite of LUB).

**Comment by MichaelRFairhurst** [comment]
> For GLB, it should probably allow using the result in any way that either operand can be used. It must be a subtype of both types.

This example I think is questionable:

```
GLB(dynamic, topType) = GLB(topType, dynamic) = dynamic
```

This means `x = c ? void Function(dynamic) : void Function(int)` would produce a `voidFunction(dynamic)`. I'm not sure I like this; in this case I think the parameter `dynamic` expresses that there is little/nothing known about its input. I think it should then defer to `int` to carry the restrictions over, and we'd get `void Function(int)`.

but otherwise I tend to strongly agree

**Comment by lrhn** [comment]
In the example `x = c ? void Function(dynamic) : void Function(int)`, the `int` is not a top type, so the winner would be `void Function(int)`.

**Comment by eernstg** [comment]
Here's an attempt to summarize:
```dart
LUB(T, T) == T, for all T.
LUB(S, T) == LUB(T, S), for all S, T.
LUB(void, T) == void, for all T.
LUB(dynamic, T) == Object, for all T != void, dynamic.
LUB(Object, T) == Object, for all T != void.
LUB(bottom, T) == T, for all T.

GLB(T, T) == T, for all T.
GLB(S, T) == GLB(T, S), for all S, T.
GLB(void, T) == T, for all T.
GLB(dynamic, T) == T, for all T != void.
GLB(Object, T) == T, for all T != void, dynamic.
GLB(bottom, T) == bottom, for all T.
```
The main points are the following:

- For `void`, LUB makes the type contagious; e.g., `b ? print('Hello!') : Object()` is considered to be marked "Do not use!" because at least one of the branches is marked as such; in contrast, GLB makes `void` ephemeral; e.g., `b ? (void x) => 42 : (dynamic x) => x` gets type `dynamic Function(dynamic)` because we cannot trust that the argument of the given closure is marked "Do not use!". This could actually be modeled by letting `void` play the role as a proper supertype of all other types.
- For `dynamic`, LUB makes the type ephemeral, because the result only preserves the "dynamic bit" when both branches have it, and so does GLB. I believe that this could not be modeled by putting `dynamic` anywhere in any partial order that refines subtyping.
- For `Object`, LUB respects the "void bit", deletes the "dynamic bit", and otherwise does the obvious (subtype) thing; GLB deletes all bits and then does the obvious (subtype) thing.
- For `Null`, I believe we should not need any deviation from the general rules (letting `T` be `Null` here and there).

@leafpetersen &amp; @lrhn?

**Comment by dgrove** [comment]
Any updates here @eernstg ?

**Comment by eernstg** [comment]
Leaf tried out two models: One which is as described in [the CL](https://dart-review.googlesource.com/c/sdk/+/53211), and another one which came up as a less breaking alternative (because the first one was frowning at a rather large number of locations). The latter one may be summarized as `Object < dynamic < void`, and it seems to be only very slightly breaking, so I'd expect that one to be the preferred choice for now. @leafpetersen and @lrhn?

**Comment by lrhn** [comment]
It's fine with me. We can use that ordering in other cases where we have to distinguish `Object` and `dynamic` (like override rules).
I think it will even extend cleanly to `FutureOr<Object> < FutureOr<dynamic> < FutureOr<void> < Object`, etc.

**Comment by leafpetersen** [comment]
The proposed change above, while overall very positive in terms of catching inadvertent dynamic code, is too breaking to land now.  The small fix described above (moving `dynamic` below `void` so that `void` doesn't get lost when combined with `dynamic`) is de facto non-breaking.  I will file issues to make the fix.

**Comment by eernstg** [comment]
Sounds good! I'll cancel the above-mentioned [CL](https://dart-review.googlesource.com/c/sdk/+/53211) because we won't do what it says at this point, and I'll see if I can find a good way to ensure that we can find it again if we decide to do it after a while (maybe we could add it to the SDK and immediately delete it again, such that we can find it in the git history).

**Comment by eernstg** [comment]
I've updated the [CL about upper/lower bounds of extreme types](https://dart-review.googlesource.com/c/sdk/+/53211) to use a simple `Object < dynamic < void` setup, and moved the previous (more strict) proposal to the discussion section.

**Comment by eernstg** [comment]
Said [CL](https://dart-review.googlesource.com/c/sdk/+/53211) has now been landed, and hence we have [these rules](https://github.com/dart-lang/sdk/issues/28513#issuecomment-391253520).

**Comment by dgrove** [comment]
Is this now a CFE, Analyzer, or both issue?

**Comment by eernstg** [comment]
I believe that we can now close it: This issue was used to handle the language design discussion which was concluded with the commit of [extreme-upper-lower-bounds.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/extreme-upper-lower-bounds.md). In the mean time, #33340 was created in order to handle the CFE implementation, and #33341 the analyzer implementation.
