### ISSUE TITLE
Inferring void as type parameter?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#28528]
In the example below, we infer `bar` as `bar<Void>`.  Is that intended?  The result is a runtime type error in DDC.

```
void bar<T>(T f(T x), y) {
  f(y);
}

void foo(x) {
  print(x);
}

void main() {
  bar(foo, 42);
}
```

DDC throws (when `f` is applied to `y`, `y` is cast to `T`):

```
Type 'int' is not a subtype of type 'void'
```

**Comment by vsmenon** [comment]
@jacob314 was running into something this.  @leafpetersen ?

**Comment by leafpetersen** [comment]
The inference has some interesting wrinkles, but I'll follow up separately.  It's mostly in line with what we are thinking for void.  cc @lrhn 

I believe the immediate issue with the runtime cast failure was fixed in https://codereview.chromium.org/2671113002/ , so changes in the treatment of void are being tracked elsewhere.

**Comment by lrhn** [comment]
This is an interesting case for inference because there are multiple types to infer from.
```dart
void bar<T>(T f(T x), y) {
  f(y);
}
```
Does this function declaration infers `y` to be `T`?
It has to, doesn't it? The only other alternative is dynamic, but you can't call `f` with a dynamic value as argument.

```dart
void foo(x) {
  print(x);
}
```
This should infer `x` to be `Object`. No problem there.
```dart
void main() {
  bar(foo, 42);
}
```
The only thing to infer a type of here is `T` of `bar`.
The only option is `void` because `foo` isn't assignable to `int Function(int)`.

Happily, 42 is assignable to `void`, and with that fixed, I think it should work.

**Comment by eernstg** [comment]
Granted, SML style type inference will take the complete body of a function which is subject to type inference into account. But I don't think we should start doing such a thing in Dart, because we have subtype polymorphism and mutability (so we'll hit undecidability issues as well as the various pragmatic difficulties).

I would expect developer feedback to deal with the type of `y` only indirectly, and only after a couple of steps:

A. (1) With no type annotation and no constraints, the type of `y` is inferred to be `dynamic`; (2) the invocation `f(y)` contains a downcast (dynamic --> T), which is accepted silently.

B. If we use a more tight discipline (that we can currently request with `implicit-dynamic: false` in .analysis_options) then (1) the type of `y` is inferred to be `Object`; (2) the invocation `f(y)` is still a downcast (Object --> T), which may be accepted silently.

But, in practice, `dartanalyzer --strong` warns, presumably because there are cases where Dart 1 run-time semantics and strong mode static checks are conflicting, and this cast threatens to reveal the inconsistency.

C. With `implicit-dynamic: false` and `implicit-casts: false`, (1) `y` gets type `Object` and (2) the downcast in `f(y)` must definitely be flagged.

So we can help developers catch this issue when they opt in to use a tight discipline, and then they'll be nudged into adding a suitable type annotation to `y`. But I don't see it as reasonable nor realistic to expect inference to come up with a suitable type for `y`.

**Comment by leafpetersen** [comment]
> This is an interesting case for inference because there are multiple types to infer from.
```dart
void bar<T>(T f(T x), y) {
  f(y);
}
```
> Does this function declaration infers y to be T?
> It has to, doesn't it? The only other alternative is dynamic, but you can't call f with a dynamic value as argument.

There is no inference whatsoever done in this code in strong mode.  We do not infer function parameter types (except through method override inference).  `y` is declared as `dynamic` (since leaving a type off of a function parameter is another way of writing `dynamic`, again modulo method signature inheritance).  The call `f(y)` is an implicit downcast from `dynamic` to `T`.

```dart 
void foo(x) {
  print(x);
}
```
> This should infer x to be Object. No problem there.

Again, no inference, you wrote `dynamic` (just using a very concise syntax).

```dart
void main() {
  bar(foo, 42);
}
```
> The only thing to infer a type of here is T of bar.
> The only option is void because foo isn't assignable to int Function(int).

The second parameter places no part in inference, since the second parameter of `bar` was declared as taking type `dynamic`.   The first parameter implies a constraint `void <: T`, and a second constraint  `T <: dynamic`.  I believe that in your proposal Lasse, there is no type which satisfies these two constraints, and so this will be an inference failure.

> Happily, 42 is assignable to void, and with that fixed, I think it should work.

I think it won't, given my current understanding of your proposal.
