### ISSUE TITLE
Please, clarify Isolate.removeOnExitListener() description

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28535]
The [description](https://api.dartlang.org/stable/1.21.1/dart-isolate/Isolate/removeOnExitListener.html) for method Isolate.removeOnExitListener()  reads:

> void removeOnExitListener(
> SendPort responsePort
> )
> Stop listening on exit messages from the isolate.
> 
> If a call has previously been made to addOnExitListener with the same send-port, this will unregister the port, and it will no longer receive a message when the isolate terminates. A response may still be sent until this operation is fully processed by the isolate.

Please, clarify the following cases:

1. responsePort is invalid, i.e null
2. responsePort has not been supplied to addOnExitListener () before
3. the same responsePort has been supplied to addOnExitListener () several times

**Comment by lrhn** [comment]
We don't generally document what happens when a parameter is `null`. It is assumed to be an error (but may or may not be reported). We document what `null` means only when it is allowed.

For 2. - that port will not get messages about that isolate exiting. It didn't use to, and it still doesn't.
For 3.The `addOnExitListener` documentation states that adding the same port more than once doesn't do anything for the following calls, so that can't happen.

We should probably add some extra text to document this.
