### ISSUE TITLE
Rasta needs to construct LabeledStatements with non-null bodies

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#28533]
Consider the following dart program:

    main() {
      switch(1) {
        case 1: {}
        case 4:
            print('foo');
      }
    }

Dartk produces something like the following:

      static method main() → dynamic {
        #L1:
        switch(1) {
          #L2:
          case 1:
            {
              {}
              throw new core::FallThroughError::•();
            }
          #L3:
          case 4:
            {
              core::print("foo");
              break #L1;
            }
        }

However, for Rasta, when it encounters that "break #L1" it creates a [new LabeledStatement with a body of null](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/kernel/kernel_visitor.dart#L396) (this also happens with continue just below that). The JumpTarget.statement is pointing to the correct jump location, so it's just a matter of getting a hold of the correct Kernel Statement node rather than the original Node and passing that in when constructing the new LabeledStatement. 

So, something like:

    ir.LabeledStatement getBreakTarget(JumpTarget target) {
        return breakTargets.putIfAbsent(
            target, () => return new ir.LabeledStatement(target.statement)); 
      }

where target.statement actually points to the kernel version of that node.

**Comment by peter-ahe-google** [comment]
Sorry, it's a bit confusing. Rasta and fasta are two different things, that I've worked on and that kinda does the same thing (compiles Dart to Kernel IR).

Rasta was based on dart2js, and we decided to abandon that in favor of dartk. But the dart2js team decided to keep rasta alive as a way to migrate the backend to Kernel.

Later on, I decided to experiment with a completely new approach for compiling Dart to Kernel. This turned out to be much faster than both dartk and rasta, and have a better fit with modular compilation.

I haven't worked on rasta since I started the fasta project. But if you need my help with this bug, let me know.
