### ISSUE TITLE
consider accepting non-breaking changes in patch file

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28542]
Currently the patching mechanism strictly checks that every patched member is identical. The check is completely syntactic.

A question came up in a code review about whether we should allow some exceptions:

- omitting the return type of a function that was dynamic in the original library:
```dart
// original:
external dynamic noSuchMethod(Invocation i);

//patch omits dynamic:
@patch noSuchMethod(Invocation i) { ... }
```

- chaning the name of a parameter in a inline function type:

```dart
// original:
external void f(g(name));

// patch changes `name` for `n`, but this name is not part of the signature
@patch void f(g(n)) { }
```

The context of the review is here: https://codereview.chromium.org/2655223005/.

**Comment by sigmundch** [comment]
About the first case: thinking more about this, I believe you might have been done that on purpose because of strong-mode semantics, is that right? (I mean, because strong-mode could infer a different type when it's omitted but it wont if it's specified as dynamic)

**Comment by stereotype441** [comment]
> About the first case: thinking more about this, I believe you might have been done that on purpose because of strong-mode semantics, is that right? (I mean, because strong-mode could infer a different type when it's omitted but it wont if it's specified as dynamic)

Agreed.

Regarding the second case, we *could* allow this at the expense of complicating the patching algorithm (currently it checks that the signatures match by just comparing token streams; that logic would have to be replaced by something more complex).  Note also that the name *would have been* semantically relevant if it had been enclosed in "{}".

Personally I think it's a better use of our time to just keep the patch files in sync with the SDK files rather than complicate the patching logic to allow these variations.

See my comments on https://codereview.chromium.org/2655223005/ for more information.

**Comment by stereotype441** [comment]
Closing this as a "won't fix" for now.  We can reopen if we change our minds.
