### ISSUE TITLE
Infer type of static final members?

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#28541]
If I write

```
class Foo {
  final int bar = 5;
}

new Foo()
    .bar
    .isDynamicSoICanDoAnythingWithIt;
```

`Foo.bar` is dynamic even in strong mode.

Is there a reason why it can't be inferred in this case to be `int`? I can see if it weren't `final` that using a higher type than `int` could be intentional, but if its `final` I don't see a reason not to use the exact type.

This is affecting my angular analysis. Output properties must be a subtype of `Stream`, are usually final, and don't always declare the type:

```
  @Output
  final thisIsCommon = new EventEmitter<X>();
```

My analysis code raises the error on `alsoValidOutput` that it should be of type `OutputEmitter`, but its of type `dynamic`. I should probably accept `dynamic`, or report a different warning, but I also think that it should be possible to infer this is of type `EventEmitter` since its `final`.

Is there a reason why we don't do this?

**Comment by eernstg** [comment]
(I'm assuming that the type annotation `int` in the declaration of `bar` should not have been there----as long as it is present, inference is obviously irrelevant.)

In spec mode (that is, non-strong mode), there is no inference, and the type of `bar` must be dynamic.

In strong mode the analyzer prints the following:
```
[error] The getter 'isDynamicSoICanDoAnythingWithIt' isn't defined for the class 'int'. (/Users/eernst/lang/dart/scratch/201701/001.dart, line 8, col 17)
1 error found.
```
It looks like there's some other unexpected aspect of the situation where you had a problem.

I'm closing this now because it seems that the issue implied in the title isn't it. Please resubmit if needed!

**Comment by MichaelRFairhurst** [comment]
looks like I ran `dartanalyzer --strong test.dart` instead of `dartanalyzer test.dart --strong`... Thanks Eric

**Comment by matanlurey** [comment]
@MichaelRFairhurst Open a new issue on that one -- definitely confusing for our users.
