### ISSUE TITLE
Raw types in bounds should be allowed when the raw type bound is ground

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#28580]
If a parameterized type `A` is used somewhere in a type bound with no type arguments, it is currently treated as an error in strong mode unless the type parameter to `A` has no bound.  This should be relaxed to also allow this in any case where the bound on the type parameter to `A` does not reference any other type parameters to `A`.  Examples:

```
class A<T> {}

/// Already allowed, A is treated as A<dynamic>
class B<T extends A> {}

class C<T extends A<int>> {}

/// Currently disallowed, should be allowed, C is treated as C<A<int>>
class D<T extends C> {}

/// Currently disallowed, should be allowed, List<C> is treated as List<C<A<int>>
class E<T extends List<C>> {}
```

**Comment by mit-mit** [comment]
This does not block 1.22; tagging 1.23

**Comment by eernstg** [comment]
As I argued elsewhere, we should consider treating `A` as `A<Object>` rather than `A<dynamic>`: Allowing dynamic invocation of arbitrary members on expressions whose type is the type argument of `A` is a non-trivial source of unsoundness, so we may wish to ask programmers to request that explicitly&mdash;and write the type they want if they are actually not happy about `Object`.

**Comment by scheglov** [comment]
I implemented this change, partially.

There is a problem though. If we allow "instantiate to bounds" for bounds, we cannot resolve bounds in arbitrary order, we need to do this in dependency order. This works with the new analysis driver, because we can resynthesize in any order. But not with the old tasks based analysis. And we're going to remove it in the near future, so I think it is not worth making it work with the old implementation.

@bwilkerson This basically means that we need to stop using task based analysis everywhere and remove it.

**Comment by dgrove** [comment]
Any updates here?

**Comment by scheglov** [comment]
I'm working on moving DDC to the new analysis driver, so that we could use resynthesized types.
Once this is done, we will be unblocked to implement this feature only in one place.

**Comment by dgrove** [comment]
Is this likely to make it for 1.23?

**Comment by scheglov** [comment]
Yes, I think so.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2762863002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/ef527a9bdef02534817fcb2cada5b3d4cef34c97

**Comment by scheglov** [comment]
Unfortunately, I had to [roll the change back](https://github.com/dart-lang/sdk/commit/2bf5caed4e1a11c63fc2b8541ca222e364a7093b). There are problems that I was not able to fix quickly enough. At this point I don't think I will able to make it for `1.23`.

**Comment by dgrove** [comment]
Is this happening for 1.24?

**Comment by dgrove** [comment]
@leafpetersen is this happening for 1.24? (ie, this week)

**Comment by leafpetersen** [comment]
Moving to 1.25.  @scheglov @bwilkerson is this feasible to implement in the analyzer for 1.25, or should we leave this to the new front end to resolve?

**Comment by devoncarew** [comment]
@leafpetersen, is this a blocker for alpha2? If no, I'll move it out of the milestone.

**Comment by leafpetersen** [comment]
Moving it out is fine.

**Comment by bwilkerson** [comment]
Closing as obsolete. Please re-open if that's not the case.

**Comment by leafpetersen** [comment]
This still seems to reproduce with bleeding edge analyzer.

**Comment by dgrove** [comment]
@bwilkerson - can you please move this to Dart2-beta3/beta4/stable, or remove the milestone?

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Any update?

**Comment by MichaelRFairhurst** [comment]
I ran into merge issues trying to patch in the reverted CL since its pretty out of date at this point. Didn't get it working by the time I got derailed.

Thanks for the reminder, I'll get back on it.

**Comment by MichaelRFairhurst** [comment]
Just to give an update on the progress of this, I was able to merge the reverted change and update it to work for function types.

I did however just hit a stack overflow that will be tough to fix. Now the problem is that linking the summaries depends on instantiating to bounds, which requires linking summaries.

a.dart
```
class A<T extends B> {}
```

b.dart
```
class B<T extends A> {}
```

Since the infinite loop here is caused by `typeA.instantiateToBounds()` calling `typeB.typeArguments` calling `typeB.instantiateToBounds()`, I'm not sure I see a place where I can easily track & break this.

I will continue to work on it but may need to go over it with @scheglov

**Comment by eernstg** [comment]
In the example, `B` must have a simple bound ([search 'We say' in this document](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md)), which is true if `A` has a simple bound, which is true if `B` has a simple bound, and it is specifically stated that such a circularity implies that the answer is 'No'.

So the function that determines whether a given bound is simple should keep a set of bound declarations visited so far, and return `false` if at any point a bound declaration is visited which is already in that set.

So how does that fit into the current implementation, is there on such `bool simpleBound(...)`? Does it get lost in modular compilation and summaries and stuff? Otherwise, it should be doable, and hopefully not too costly (in a lot of cases it may be possible to avoid allocating an actual `Set`, which might be important).

**Comment by MichaelRFairhurst** [comment]
Yeah, the problem is that in order to detect cycles, I need to inspect the
A's type parameters. Behind the scenes, asking for the type parameters
causes the bounds to be instantated to bounds. This causes it to loop
infinitely if I ask for the type parameters of either type.

There is likely some solution where I peek into which type I'm using,
however, I'm not sure that's the best solution..

**Comment by eernstg** [comment]
When a bound `B` is instantiated to its bounds there should be a check that `B` has simple bounds. That should be enough to catch the cycle.

**Comment by MichaelRFairhurst** [comment]
Right, the problem is that the only way to check if B has simple bounds is
to get it's type parameters. In getting it's type parameters, it runs
background logic to deserialize from disk. And one step in that process is
to instantiate the B's bounds (A in this case) to bounds. This causes
A.instantiateToBounds to call A.instantiateToBounds before B.typeParameters
returns a value.

I could make a new method getTypeParametersWithoutInstantiatingBounds or
something like that to get around this I think.

**Comment by eernstg** [comment]
I shouldn't try to guess my way through these things because I don't know the CFE implementation details. But it seems reasonable to say that the deserialization should check that bounds are simple, because it's apparently executing the instantiate-to-bound operation that shouldn't even be attempted. Maybe the CFE should attach some kind of metadata to each type variable indicating whether it has or does not have a simple bound, such that the answer comes directly, pre-computed, from the serialized data?

**Comment by eernstg** [comment]
OK, thanks @stefantsov! &mdash; and it still stands that I should just stop guessing at implementation details. ;)

**Comment by MichaelRFairhurst** [comment]
a few hurdles overcome to get to: https://dart-review.googlesource.com/c/sdk/+/52062

**Comment by MichaelRFairhurst** [comment]
This change has landed, and hopefully it sticks!
