### ISSUE TITLE
Please cherry pick fix for issue 28610 into the 1.22.0.dev

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#28627]
Please cherry pick fix for https://github.com/dart-lang/sdk/issues/28610 into the 1.22.0.dev branch
The Cl that fixes it is https://github.com/dart-lang/sdk/commit/1ff4a5a16b8f452c0534d2a04347cdcde480e26f

**Comment by whesse** [comment]
This cherry-pick does not merge.  It depends on the the commit https://github.com/dart-lang/sdk/commit/97f968de1c54db99b5f567d3fd6379756e2416f7
which is not in 1.22 because it was landed after the last full push to dev.

Either this fix is not needed, because teh issue was introduced by that prior CL, or that prior CL needs to be cherry-picked as well to 1.22.

**Comment by eernstg** [comment]
I believe this was settled in #28610: The whole [generic function type syntax](https://github.com/dart-lang/sdk/issues/27527) feature is at milestone 1.23; in 1.22 we only deprecate certain usages of the identifier `Function`, such that we will have fewer update conflicts when this syntax is introduced.

**Comment by a-siva** [comment]
Sorry my bad I was under the impression that it went into 1.22. will close this issue.
