### ISSUE TITLE
Should allow `void` closure in calls to `Future.then()`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#28647]
I expect to be able to write this code:

```dart
import 'dart:async';
import 'dart:math';

void main() {
  new Future.value(new Random().nextBool()).then((b) {
    if (b) return;
    print('Did not return');
  });
}
```

With 1.22.0-dev.10.3 I get a strong mode warning: `[warning] Missing return value after 'return'.`

I expect to be able to use `return` as an early exit in a method that I don't intend to return a value. Changing to `return null;` works - but masks intent.

**Comment by leafpetersen** [comment]
This is fixed in bleeding edge here: https://codereview.chromium.org/2667343005/

This will be cherry picked into dev for 1.22.

There is a separate question as to whether this should be inferred as `Future<Null>` or `Future<void>`.  Currently it is inferred as the former, there is an argument that the latter would be better.  That won't be resolved for 1.22 though.  Feel free to file an area language bug on that.
