### ISSUE TITLE
Strong mode should infer top/bottom types for generic types inside constant expressions

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28685]
If an inference for a constant expression needs to match a generic type, strong mode should infer `Null` (or later `Nothing`).

For example:
``` dart
List<T> foo<T>() {
  return const [];
}
```

**Comment by leafpetersen** [comment]
I think @eernstg was going to follow up on this, but just to mention:

My guess is that the right approach (ignoring type bounds) is to infer a type as usual, and then replace all covariant occurrences with Null and contravariant occurrences with dynamic or Object.  This yields a type which is a subtype of the precise inferred type.  

I haven't thought through whether bounds add anything interesting to the problem or not.

**Comment by lrhn** [comment]
That makes sense for cases where the `T` isn't the actual type. E.g.:
```dart
List<T Function(T Function(T))> foo<T>() => const [];
```
In this case, the inference wants a `List<Something>` that is a subtype (and therefore assignable) to `List<T Function(T Function(T))>` for any `T` (and T isn't even bounded here, so it's "easy").

Obviously `List<Null>` is a solution, but less precise than possible since `List<Null Function(Object Function(Null))>` is also one. I guess we want the greatest lower bound that can be reasonably found. Or, is that really important? You can't use the class at runtime anyway, and you can assign it to any static type you care about, so does it matter that the runtime type isn't precise?

If we do infer a preciser type, with a bound on `T`, we'd use the bound instead of `Object`. With an F-bound, we'll ... do whatever we do for F-bounds (fail, default to `Object` or introduce the anonymous infinite type) instead of `Object`. The contravariant positions are still satisfied by `Null`.

**Comment by eernstg** [comment]
I believe that would be the way to go.

Just double checking, it is possible to create a constant expression where we would like to have a type argument inferred, where we need to match a formal type parameter of an enclosing declaration (such that we must find a constant value that fits with all possible actual type arguments), and where the inferred type argument occurs contravariantly:
```dart
typedef void Foo<T>(T t);
void foo<T>(T t) {}
void bar<T>([Foo<T> arg = foo]) {}

main() {
  bar<int>();
}
```
For the default value `foo` of `arg` in the declaration of `bar`, we need to infer `foo<Object>` or `foo<dynamic>` rather than `foo<Null>` (at some point, `foo<Nothing>`), ignoring that we don't support these generic instantiation tear-offs yet.

Bounds _do_ create the usual problems. We would have a rule like this: 'for a formal type parameter which is used in a contravariant position, replace it by the least upper bound of all possible actual type arguments', as well as the (unproblematic) 'for a formal type parameter which is used in a covariant position, replace it by the Null (or Nothing)':

```dart
class C<S extends C<S>> {}
class C1 extends C<C1> {}

typedef void Foo<T>(T t);
void foo<U extends C<U>>(U t) {}
void bar<V extends C<V>>([Foo<V> arg = foo]) {}

main() {
  bar<C1>();
}
```
We cannot use `foo<Object>` nor `foo<dynamic>` because the given type arguments do not satisfy the bounds (and even though we may contemplate using malbounded type annotations, this is a malbounded runtime entity, so that's still just plain wrong ;-), and we cannot express the least upper bound of all the possible type arguments `U` satisfying `U extends C<U>`.

So I'd give the same recommendation that I usually do for instantiate-to-bound: Refuse to solve this problem, i.e., reject that default value at compile time.

Adjusting the title to catch up with the developments so far.

**Comment by eernstg** [comment]
Ah, I forgot to reload so I didn't see your response first, Lasse.

Just for completeness, though, I could add that we do have cases where inference con't provide a sufficiently "universal" type:
```dart
typedef T Foo<T>(T t);
T foo<T>(T t) => null;
void bar<T>([Foo<T> arg = foo]) {}

main() {
  bar<int>();
}
```
In this case neither a top nor a bottom type will work (because we have both covariance and contravariance), so there will of course be some cases where we must declare that the inference failed and the program is rejected.

**Comment by leafpetersen** [comment]
I don't think we've committed to treating instantiated tearoffs of generic functions (`foo<T>` in @eernstg's example above) as const objects?  Or did we decide that was fine?  If so, then yes, there are some examples we can't find a sound approximation for and will have to error out.  I don't expect that to be a common issue.

The point that @lrhn makes about simply using `Null` as the type argument to the outermost type constructor and not worrying about getting the most precise runtime type seems like a good one.  I think there's probably a reasonable definition that can be made around this.  I don't immediately see any benefit to having a more precise type offhand.

**Comment by eernstg** [comment]
Right, const objects are specified syntactically, and the supported syntactic forms do not include generic tear-offs like `foo<T>`.

We could (1) add syntactic support for generic tear-offs, and add this form to the list of constant expressions, with constraints as needed (e.g., can't use formal type parameters in scope); and we could (2) add support for generic tear-offs via inferred type arguments (such that we can have them semantically for expressions like `foo`), without adding syntactic support (`foo<T>`).

The things I said were intended to be compatible with (2), but I needed a hypothetical (1) in order to explain what I meant; finally, we could of course have both (1) and (2).

**Comment by lrhn** [comment]
On Fri, Feb 10, 2017 at 12:46 PM, Erik Ernst <notifications@github.com>
wrote:

> Right, const objects are specified syntactically, and the supported
> syntactic forms do not include generic tear-offs like foo<T>.
>
I believe we already allow instantiation at tear-off. Like:

T id<T>(T x) => x;
int Function(int) intId = id;  // id inferred and instantiated as id<int>

At least the strong-mode analyzer in dartpad considers intId to require an
int argument, and accepts the assignment from id, which it shouldn't for
any type parameter different from `int`. (OK, I use a typedef, not
Function, because dartpad doesn't have the Function syntax yet :)

I do think it is something of a problem that we don't allow you to write
the same thing explicitly. That makes it a case where inference does
something that you can't do explicitly. (Another case is inference of
return type on non-"=>" function expressions).

We could (1) add syntactic support for generic tear-offs, and add this form
> to the list of constant expressions, with constraints as needed (e.g.,
> can't use formal type parameters in scope); and we could (2) add support
> for generic tear-offs via inferred type arguments (such that we can have
> them semantically for expressions like foo), without adding syntactic
> support (foo<T>).
>

I think we should add the syntax in any case.

The question of whether it is a const expression is a separate concern. It
doesn't have to be, even if we have the syntax.

I think our conclusion is that it's *possible*. In a const context, or with
a constant type parameter, `id<String>` can be treated as constant and
canonicalized - without `id<T>` - T a type variable - having to be
canonicalized to the same thing, even if `T` happens to be `String`.

I think it would be a good idea to allow `id<int>` as a compile-time
constant. It is a likely candidate for a default parameter or similar uses.

I also think that it's not essential and is something we can add later
without breaking anything (few people should depend on the non-identity of
function values).

(And as a side note, exposing the identity of objects sure does break a lot
of nice optimizations for objects that the compiler knows to be immutable).
:)


> The things I said were intended to be compatible with (2), but I needed a
> hypothetical (1) in order to explain what I meant; finally, we could of
> course have both (1) and (2).
>

I believe we have (2) already. I think we should have (1), either constant
capable or not.

>
/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by leafpetersen** [comment]
See comment on this bug here: https://github.com/dart-lang/dart-lang-evolution/issues/111  for the last state of the discussion around partial instantiations, and the inference thereof. There is an open issue against strong mode analyzer to restrict inference to only inferring partial instantiations on tearoffs (not on function expressions).
