### ISSUE TITLE
Consider upgrading "missing required parameter" to a warning.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#28693]
_(It's too subtle as a hint and too easily over-looked.)_

**Comment by mit-mit** [comment]
Huge +1. Flutter uses parameters extensively, so this leads to really poor error UX.

**Comment by bwilkerson** [comment]
Two alternatives that I can think of off-hand:
- use the analysis options file to increase the severity of the diagnostic, or
- update the way the clients display hints to make them more prominent.

**Comment by pq** [comment]
@bwilkerson : I'm curious why not just escalate the hint to a warning?  When would you ever want to elide a required parameter?

**Comment by bwilkerson** [comment]
> When would you ever want to elide a required parameter?

I can't think of any rational reason.

> I'm curious why not just escalate the hint to a warning?

Errors and warnings are defined by the language spec. Hints are not. This is not defined in the spec, therefore it's a hint.

**Comment by mit-mit** [comment]
Getting the spec changed is possible; we are making a number of languages changes currently

**Comment by bwilkerson** [comment]
I think there are good argument to be made against doing so. First, the spec should not describe the semantics of code outside the SDK, and the `@required` annotation is not part of the SDK. That could, of course, also be changed. Second, the semantics of the language should not depend on annotations, and having a specification defined warning based on the use of an annotation seems dangerously close. (The second argument is, as I understand it, why we now have a `covariant` keyword rather than the annotation we used to have.)

**Comment by lrhn** [comment]
The one change that we can do (short of putting `@required` into the SDK and specifying its meaning in the spec, or even add `required` to the language in some format) is to allow tools to emit "warnings" for things that are not specified in the spec.

The current distinction is that a *warning* and *errors* are specified, and required, by the specification. All tools doing static analysis should emit the same warnings and compile-time errors.
That means that users can write programs that are warning free and expect them to be warning free for everybody else too.

The "solution" to this restriction is that all other useful information from the analyzer is called "hints", because they're not allowed to be called "warnings". The analyzer is quite a lot smarter than the spec requires, and it uses annotations to get a better idea of the author's intentions, so it can warn about actual problems that the spec doesn't have a warning for. 

It's a political decision, not a technical one, to not allow the analyzer to invent its own "warnings", so we could reconsider that decision. In strong mode, there are few warnings because most cases that cause warnings in the Dart spec have become errors in strong mode. With luck, we might get to the point where there are no warnings, only errors or working programs. At that point, there is no reason not to allow the analyzer to use "warning" for things that it considers a breach of intent, even if the program looks like a semantically correct Dart program.

(Just for `@required`. if we get non-nullable types, we could choose to make a named parameter with a non-nullable type and no default value, be effectively required).

**Comment by eernstg** [comment]
One extra comment on the nature of `@required` parameters.

We can make a distinction between mechanisms with a semantic content and mechanisms which are exclusively concerned with well-formedness. An example of the former is function invocation (invoking a function "does something" at run time), and an example of the latter is `@required` parameters (it just serves to flag some programs as "not well-formed" because they fail to provide actual arguments for one or more such parameters in some invocations, but the mechanism doesn't do anything at run time).

This is a useful distinction because the semantic mechanisms _must_ be part of the language whereas the well-formedness mechanisms can be outside the language; e.g., we can allow them to be enforced or ignored without breaking any language invariants, they can be checked by compilers or by separate tools like linters, and we can even have support for user defined well-formedness, e.g., adherence to business rules according to a specification in metadata, expressed in some domain specific language, etc.

I generally recommend that we keep well-formedness out of the language per se, but strive to offer well-supported mechanisms in this area in the tool-chain. Analyzer hints is a good example of such a thing, and so is the linter. One good thing about the hints is that they are standardized (insofar as the analyzer is standardized for doing static checks on Dart programs); conversely, the linter can be configured in a lot of [different](https://www.dartlang.org/guides/language/analysis-options#the-analysis-options-file) [ways](http://dart-lang.github.io/linter/lints/).

The main point is that the language as such will easily get "too big", and the ability to keep well-formedness checks out of the language is an obvious thing to keep in mind.

**Comment by devoncarew** [comment]
I think a take-away from this discussion is that it is OK for the linter to generate both hints and warnings, esp. in cases where the linter is helping to validate the well-formedness of the code. The user is still opting into the linter, and presenting things at the right level of impact to the user is helpful.

**Comment by bwilkerson** [comment]
Minor nit: this hint (not lint) is from the analyzer, not the linter, and users are not opting in to the production of this hint.

I absolutely agree that it would be better if this hint were a warning. I actually think that all of our hints should either be warnings or demoted to lints. I do not believe that any (significant number of) our users care about the original distinction between errors and warnings, nor am I convinced that such a distinction has much value in strong mode. Hence, I would prefer to see the specification define the errors and for analyzer to define the warnings.

But I'm not going to create any warnings that are not proscribed by the specification until I have heard from the language team that they no longer mind having us do that. They have not yet said so.

**Comment by devoncarew** [comment]
> users are not opting in to the production of this hint.

They may very well be, right? They're using code that chooses to use the `@required` annotation. The issue we found in the UX study is not whether we should surface it or not, but that we're not surfacing it strongly enough.

**Comment by eernstg** [comment]
> we're not surfacing it strongly enough.

I can see the temptation to align the severity with the type of diagnostic message, but I think we should consider those two things as somewhat **orthogonal**.

Originally, compile-time **errors** were statically known faults that would preclude execution (say, cyclic inheritance), and **warnings** were statically known faults or likely faults where execution could take place (say, an `UnknownType` used as a type annotation could be considered to mean `dynamic`, and `e is UnknownType` could throw if it were reached at run time). This is a civilized keep-on-truckin' approach: We can run programs even during transitional periods where the program is actually known to be incorrect, such that developers can use experimental runs as a source of information about the program. Later, when developers wish to clean up their software they just need to eliminate the warnings.

**Hints** are not necessarily different from warnings wrt their inherent severity, but they are generally considered less severe. Finally, **lints** are perhaps seen as yet another layer, more in the direction of coding style, bad smells, etc, and **user-defined** checks would probably tend to be at a similar level, i.e., "not so severe".

However, consider a user-defined business rule. Let's just assume that we have a tool for checking this rule, so there could be a diagnostic message in IntelliJ, and it could be filtered. Violation of that rule could easily be so severe that it absolutely must be resolved before the next version of the software is shipped, and possibly the social organization of the work dictates that it must happen right now.

In general, I think it's possible for diagnostic messages at all those "less severe" levels to be really severe, in some contexts. At the same time, it's obviously possible to change the behavior of a tool for each type of message, such that it gets treated as more severe than it must be for technical reasons (like "we just can't run this program, so this is a compile-time error").

Hence, I see "we're not surfacing it strongly enough" as a request for control and configurability of our tools, such that every message can get the appropriate treatment for the given context.

**Comment by sethladd** [comment]
We can crank up the severity of this feedback for our Flutter users, via analysis options. If you want to start there, to test the impact of making this feedback more prominent for Flutter developers, happy to help.

**Comment by pq** [comment]
> We can crank up the severity of this feedback for our Flutter users, via analysis options. 

👍 https://github.com/flutter/flutter/issues/8087

**Comment by pq** [comment]
@Hixie: is the current configuration via options working OK?  Can we close this out?

**Comment by Hixie** [comment]
I have no context regarding this issue. I don't really understand the difference between "error" and "lint" and the other steps in between; in my workflow and IDE they all show up the same and are all equally important. If it's about other IDEs, then I defer to the people who use those IDEs. cc @devoncarew

**Comment by pq** [comment]
Cool.  Thanks @Hixie.  From the user's perspective I don't think the distinctions are that interesting either and in any event we can finesse presentation in analysis options.  Closing this one for now.
