### ISSUE TITLE
Argument "key" in Map.remove(key) should be typed to the key type of the map

### ISSUE THREAD

**Issue by markrusciano-wf** [dart-lang/sdk#28690]
The prototype of the method to remove an object from a `Map<K, V>` is `V remove(Object key)`. 

It would be helpful if the key argument were typed (i.e. `V remove(K key)`) so that the analyzer would warn if an object other than a key was passed in.

I've ran into this issue when switching between working with maps and lists where I occasionally mistake the remove method of a map with the remove method of a list and pass in a value to `Map.remove` rather than than a key.
 
Example:
https://dartpad.dartlang.org/a59ec0390001a9a183d160d2f017b348

Edit: previous dartpad example was incorrect, it is now fixed.

**Comment by lrhn** [comment]
The choice of `Object` as argument type is deliberate.
Since Dart has covariant generics, you can do:
```dart
Map<Object, Object> map = <String, String>{"foo": "bar"};
print(map["foo"]);  // prints "bar".
map.remove("foo");
```
"A string map *is* an object map!" (it sounds better with lists, but it still applies to maps).
The idea is that you can still use all the operations that only works on the values already in the map, but not the ones that tries to modify it, because we don't want non-string keys or values getting into the map.

For that to work, the index and `remove` operations must accept `Object`. The same applies to methods like `Iterable.contains` and `Set.remove`.

It *is* annoying that you can't get a warning when you try to remove a key that we can statically see is (probably) not in the map anyway, but there isn't a good way to express that the *static* type of `remove` on a `Map<K,V>` should be `(K)->V`, but that actual type is `(Object)->V`. So, we had to pick one, and it is the one that allows using a `List<int>` as a `List<Object>`, because that is too convenient to lose.

**Comment by markrusciano-wf** [comment]
@lrhn Thank you for the explanation! This makes a lot more sense to me now.
