### ISSUE TITLE
Inconsistent rounding for toStringAsFixed

### ISSUE THREAD

**Issue by cmilner** [dart-lang/sdk#28704]
The following set of assertions passes:
      expect((0.55).toStringAsFixed(1), '0.6');
      expect((1.55).toStringAsFixed(1), '1.6');
      expect((2.55).toStringAsFixed(1), '2.5');
      expect((3.55).toStringAsFixed(1), '3.5');
      expect((4.55).toStringAsFixed(1), '4.5');
      expect((5.55).toStringAsFixed(1), '5.5');
      expect((6.55).toStringAsFixed(1), '6.5');
      expect((7.55).toStringAsFixed(1), '7.5');
      expect((8.55).toStringAsFixed(1), '8.6');
      expect((9.55).toStringAsFixed(1), '9.6');
      expect((10.55).toStringAsFixed(1), '10.6');
      expect((11.55).toStringAsFixed(1), '11.6');

Values between 2.55 to 7.55 round down while the other numbers round up.
I'd expect it to follow similar rules to the round method:
Rounds away from zero when there is no closest integer: (3.5).round() == 4 and (-3.5).round() == -4.

**Comment by rmacnak-google** [comment]
@floitschG

**Comment by floitschG** [comment]
This is working as intended. It's a consequence of how floating-point numbers work...

When Dart reads a fractional number, it is converted into an [IEEE double-precision number](https://en.wikipedia.org/wiki/Double-precision_floating-point_format). Since doubles only use 64 bits, the number might not be represented exactly. In fact, for your given numbers, the internal representations are "rounded" (roughly) as follows:
```
0.55 -> 0.550000000000000044409
1.55 -> 1.55000000000000004441
2.55 -> 2.54999999999999982236
3.55 -> 3.54999999999999982236
4.55 -> 4.54999999999999982236
5.55 -> 5.54999999999999982236
6.55 -> 6.54999999999999982236
7.55 -> 7.54999999999999982236
8.55 -> 8.55000000000000071054
9.55 -> 9.55000000000000071054
10.55 -> 10.5500000000000007105
11.55 -> 11.5500000000000007105
```

The `toFixed` function uses the internal representation to decide how to round the numbers, which explains the results you see.
There is unfortunately not much we can do. You happened to write "6.55" as number literal, but if you had written "6.54999999999999982236" the literal would have been read in the same way: `6.54999999999999982236 == 6.55` is true.
The only (reasonable) way to avoid these rounding issues, would be to use a different internal representation, but all CPUs are heavily optimized for doubles, and switching to a different representation would have huge performance implications. It would also make interfacing with other languages much much harder.

Finally, for your amusement, here is a similar problem:
```
print(0.1 + 0.2);
print(0.1 + 0.2 == 0.3);
```
