### ISSUE TITLE
Unhelpful error message when a final variable get assigned a value again

### ISSUE THREAD

**Issue by InMatrix** [dart-lang/sdk#28721]
Please see the screenshot below: 
![screen shot 2017-02-09 at 4 25 59 pm](https://cloud.githubusercontent.com/assets/348942/22810351/084b04fc-eeed-11e6-9221-90b1be1fcc26.png)

"'Name' can't be used as a setter because it is final." is pretty hard to understand in this simple main function. Can we say something that better explain the concept of final variables? E.g., "Final variables can be only assigned once."

**Comment by bwilkerson** [comment]
I think we need to distinguish between final local variables and final fields. It makes sense (I think) to discuss setters when dealing with fields because that's what's actually being referenced. But local variables have no setter associated with them. Let me know if you disagree.

I do think, though, that the error message should be improved even in the case where we should validly be discussing a setter.

**Comment by sethladd** [comment]
@InMatrix @lukechurch any ideas for a better error message here? What's the proposal?

**Comment by InMatrix** [comment]
I found the following explanations of "final" in [A Tour of the Dart Language](https://www.dartlang.org/guides/language/language-tour) and I think that's a good place to start:

* "A final variable can be set only once."
* "You can't change the value of a final or const variable."

**Comment by sethladd** [comment]
Um, yeah. That's clear to me, when we're talking about a local variable.

For a final local variable:

"A final variable can be set only once. This variable was previously set at <line num, char num>."

For a final field:

"Final fields do not have setters, and cannot be set more than once."

How does that sound?

**Comment by sethladd** [comment]
@bwilkerson good call on the difference between field local vars and final fields. Thanks.

**Comment by InMatrix** [comment]
sgtm! Thanks!
