### ISSUE TITLE
Unable to run fasta benchmarks on stable Dart VM

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#28758]
I've been using this Dart VM for benchmarking Fasta:

```
Dart VM version: 1.20.1 (Wed Oct 12 14:58:37 2016) on "macos_ia32"
```

After adding "covariant" annotations to Fasta, I can no longer use that VM.

I think short-term, we should avoid the covariant keyword, but let's discuss how to best work around this.

**Comment by sigmundch** [comment]
Ah, correct - `covariant` hasn't reach the stable channel yet. It is in the current 1.22 dev-channel though, which should hit stable very soon. I am guessing that you prefer to only use the stable channel, right? Or is the dev channel OK for you to use?

I'll see if I can temporarily disable these, if not I can either make the errors visible or temporarily replace `covariant` with the `@checked` annotation. The latter would require a tiny dependency on `package:meta` to get the `@checked` annotation. I know that you prefer to minimize any dependency on other packages, so I'll try to keep this as the last option if that's your preference - Note that in this case it is temporary and we control it (by design, `package:meta` was always meant to be a single library containing just a few annotations and nothing else).

**Comment by peter-ahe-google** [comment]
I'm not expecting that you fix this, Siggi, I just wanted to have conversation about the best approach for this.

I'd like to keep using the same VM, as I'm seeing some performance regressions as I move to newer versions. This is something I'll be discussing with the VM.

My thinking is that we can just use the same trick we used in `forEach`. Another option would be to disable this check in the options file, but that seems to be more of a nuisance than what we did for `forEach`.

**Comment by peter-ahe-google** [comment]
I'll fix this, but I want input from you guys: @sigmundch @stereotype441.

**Comment by stereotype441** [comment]
My two cents: I a preference towards performance testing with as recent a VM as possible (ideally bleeding edge) on the theory that identifying performance regressions caused by VM changes is just as important as identifying performance regressions caused by code in Fasta itself.  But it's not a strong preference.  Besides, I believe we're going to be switching over to Golem performance tests very soon, and my understanding is that they always test with a bleeding edge VM.

**Comment by peter-ahe-google** [comment]
@stereotype441 I agree with your observations, so I test on both versions after I noticed the regression.

**Comment by sigmundch** [comment]
Thanks Peter - yes, indeed, the approach we used in forEach is great for
this too.

Hope the VM folks can pin point the underlying issue without too much
trouble.

**Comment by sigmundch** [comment]
I believe this is now obsolete? Feel free to reopen if I missed something.
