### ISSUE TITLE
Provide a way to strip symbols from release builds in a way that stack traces can still be symbolicated offline

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28785]
This is to address the regression mentioned on https://github.com/flutter/flutter/issues/8188.

cc @rmacnak-google @abarth

**Comment by a-siva** [comment]
@fsc8000 

Why does this issue have the 'spec-violation' label on it?

Why was the issue closed, is the size increase not a problem anymore?

**Comment by fsc8000** [comment]
Is this something we would only do in product (aka Flutter release) mode?

**Comment by abarth** [comment]
Yes.

**Comment by abarth** [comment]
By the way, there's a commonly used file format for symbols that many tools know how to interpret.  Ideally the Dart AOT compiler would generate symbols in the same format (e.g., as gcc and llvm do) so that tools that already understand that format can symbolicate stack traces without too much modification.
