### ISSUE TITLE
Add indent and bufferSize properties to JsonUtf8Encoder

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28805]
JsonEncoder (https://api.dartlang.org/stable/1.22.0/dart-convert/JsonEncoder-class.html) has read-only indent property, but JsonUtf8Encoder (https://api.dartlang.org/stable/1.22.0/dart-convert/JsonUtf8Encoder-class.html) hasn't. I think it makes sense to add it. Read-only bufferSize property may be usefull also. I can prepare a pull request if needed

**Comment by lrhn** [comment]
It's slightly complicated by the class not actually storing the original `indent` string, but only the UTF-8 encoding of it.
A corresponding getter will need to UTF-8-decode the stored bytes again.

I'm not sure it's actually an important property to reveal. It's unlikely that a user will have an existing `JsonUtf8Encoder` available, but won't know which indentation it uses. I guess it was made public in the original just because it was there, which is not a good reason.
So, all in all, I don't think it's worth it unless someone comes up with an actual need for the value.

I see no reason to reveal the buffer-size. That's really just an internal implementation detail that the caller of the contstructor can chose if they think it matters.

Still, thanks for the offer.
