### ISSUE TITLE
Add inifnity and negative infinity to integers

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#28831]
I see (and write) a lot of code to does something like this:

```dart
var recency = getDaysSinceLastSession();
if (recency != null && recency < 7) {
  // ... do something
}
```

The problem is that `getTimeSinceLastSession` can't easily communicate that there is _no_ last session other than by using `null` or by returning some kind of proprietary "very large value".

With `double` values, this is easy to fix: the function will just return `double.INFINITY`. But `int` doesn't have this. I wonder if this decision could be revisited, especially if we also ponder non-nullability-by-default.

([Link](http://stackoverflow.com/questions/32338554/is-there-an-int-infinity-for-dart) to Seth's SO question from 2015 on this very topic.)

**Comment by lrhn** [comment]
I'm pretty certain we won't be adding any infinite values to integers. 

It's obviously not impossible to add an infinite integer (doubles did it), and since Dart has arbitrary sized integers, we are not limited to a fixed number of bits. so adding a bigint-infinity isn't impossible.
It's just impractical. 

It's also the reason that this is necessary. If we had an `INT_MAX` that was at least as great as any `int`, you could use that instead of an infinity.

We'd need to decide what it means when integer infinity occurs in arithmetic expressions. What is `inf + 4`, `inf - inf`, `-4 ~/ inf`, `inf~/inf`. For doubles, some of those operations become NaN - so maybe we would need an integer NaN too? (That alone is reason enough to say no!)
Should `4 ~/ 0` be infinity instead of throwing? Are we just reinventing doubles?

Also, if we ever choose to restrict integers to a fixed number of bits, we'd lose the infinities again.

All in all, the use-cases are rare enough, and the complications complex enough, that I don't think it will be worth it to add non-integers to the `int`  type.

What you can do is to use `num recency = double.infinity;` and work from there.
It'll likely be slightly slower, because the code can't optimize for "integers only", but it will be correct (up to ~1e+308 at least - then your integers will become double infinity when compared).

**Comment by NatoBoram** [comment]
But.. why aren't Infinity / Nan on `num` in the first place?
