### ISSUE TITLE
Unicode BOM is not discarded by Utf8Codec.decode()

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#28834]
Please see https://api.dartlang.org/stable/1.22.0/dart-convert/Utf8Codec/decode.html

> String decode(
> List<int> codeUnits, {
> bool allowMalformed
> })
> Decodes the UTF-8 codeUnits (a list of unsigned 8-bit integers) to the corresponding string.
> 
> If the codeUnits start with a leading UNICODE_BOM_CHARACTER_RUNE this character is discarded.

In fact, if the codeUnits start with a leading UNICODE_BOM_CHARACTER_RUNE it is not discarded

```dart
  Utf8Codec codec = new Utf8Codec();
  List<int> toDecode = codec.encode("1 Some string");
  toDecode[0] = UNICODE_BOM_CHARACTER_RUNE;
  print(codec.decode(toDecode, allowMalformed: true)); // � Some string
  codec.decode(toDecode, allowMalformed: false); // FormatException: Bad UTF-8 encoding 0xff (at offset 0)
```
In both cases above BOM is not discarded

**Comment by floitschG** [comment]
I updated (or will update) the description (https://codereview.chromium.org/2707893002/)

The `UNICODE_BOM_CHARACTER_RUNE` is a rune, and thus not encoded as utf8. In fact, its value is 0xFEFF. Encoded, this rune is represented as `[239, 187, 191]`. If you add these three bytes in front of a UTF8 string, then they will be discarded.

To make your example work you would need to change it as follows:
``` dart
import 'dart:convert';

main() {
  Utf8Codec codec = new Utf8Codec();
  List<int> toDecode = codec.encode("1 Some string").toList();
  toDecode.insertAll(0, codec.encode(new String.fromCharCodes([UNICODE_BOM_CHARACTER_RUNE])));
  print(codec.decode(toDecode, allowMalformed: false));
  codec.decode(toDecode, allowMalformed: false); // FormatException: Bad UTF-8 encoding 0xff (at offset 0)
}
```

Note that you don't need to specify the `allowMalformed` anymore, since a BOM character isn't malformed.

**Comment by sgrekhov** [comment]
@floitschG  you've updated Utf8Decoder.convert() documentation. Please, update Utf8Codec.decode() as well

**Comment by floitschG** [comment]
Done. and thanks.
