### ISSUE TITLE
please, clarify description of Object.hashCode

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#28844]
The [description](https://api.dartlang.org/stable/1.21.1/dart-core/Object/hashCode.html) for property Object.hashCode reads:

> int hashCode
> Get a hash code for this object.
> 
> All objects have hash codes. Hash codes are guaranteed to be the same for objects that are equal when compared using the equality operator ==. Other than that there are no guarantees about the hash codes. **They will not be consistent between runs** and there are no distribution guarantees.
> 
> If a subclass overrides hashCode it should override the equality operator as well to maintain consistency.

It is not clear whether the same value will be returned for subsequent calls inside same virtual machine?
I.e. 
```dart
main() {
  Object o = new Object();
  int h1 = o.hashCode;
  int h2 = o.hashCode;
// is it always h1==h2, regardless of time and place they were obtained from the same instance?
}
```

The question actually splits in two:
1. How the `Object.hashCode` implementation works?
2. How descendants, overriding the `hashCode` should be implemented? (i.e. if it is allowed to return different values for different reads?)

I do understand, that `hashCode` value must be constant during virtual machine execution time, but I'd like this to be clearly documented.

**Comment by zoechi** [comment]
Returning different values for the same instance would break `HashMap` which I think is the main use case for `hashCode`. 
For custom implementations you can use https://github.com/google/quiver-dart/blob/cf4607db1b4a9b0220ab79a98e14f201053238d6/lib/src/core/hash.dart directly or as example.
https://en.wikipedia.org/wiki/Hash_table might also be helpful

**Comment by lrhn** [comment]
Since an object is equal to itself, it must return the same `hashCode` as itself - as long is it hasn't changed in a way that changes its equality. So, the `hashCode` mustn't change unless the object does.

If a mutable object changes in a way that makes it equal to some other object, it should return a matching `hashCode` for the new equality.
(If the equality is broken, like not being reflexive or symmetric or transitive, then it's probably also hard to satisfy the `hashCode` requirement, but that'll likely be the least of your problems in that case.)

The `Object.hashCode` method returns the same value as `identityHashCode` on the object (that's documented on `identityHashCode`). That value never changes as long as the object exists.

Overriding methods must satisfy that if `o1 == o2` then `o1.hashCode == o2.hashCode`. Apart from that, there are no constraints (apart from the general "don't do something silly that surprises users").

**Comment by alsemenov** [comment]
Do I understand correctly, that `hashCode` is not allowed to be null? Otherwise, `HashMap` will be broken. Since `int` is not a primitive type, it is not quite obvious. Could you document this?

**Comment by lrhn** [comment]
We generally do not document when things cannot be null, only when they can be null. That goes for both parameters and return values. I have updated the documentation on `hashCode`, so now it explicitly says that the hashCode is an integer.
