### ISSUE TITLE
mapToString has a useless ternary expression

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#28847]
I noticed that the compiled `Maps.mapToString` contains this:
```dart
      t1 = result.get$_contents();
      return t1.charCodeAt(0) == 0 ? t1 : t1;
```
I'm guessing we still need the `charCodeAt(0)` call in case it throws an exception due to `t1` being empty, but it would be nice to compile this to:
```dart
      t1 = result.get$_contents();
      t1.charCodeAt(0);
      return t1;
```

@rakudrama , what do you think?

**Comment by rakudrama** [comment]
The code is inlined from a method called `flattenString`. The exact form is as-designed.

---

Most JS engines use cons-strings, representing `+` operations as a tree.
This allows large strings to be constructed quickly by repeatedly using `+` to construct a large string from single character or other small strings, represented essentially as a list-like tree.
This makes indexing O(N), so if the string is indexed, it is flattened in-place, overwriting the tree node with a pointer to a single large string that can be indexed O(1).

The problem is that the tree nodes are 10-20x bigger than the characters they represent when there has been repeated `+` of very small strings.
This bloat caused some customer programs to run out of memory.
So StringBuffer forces the string to be flattened by indexing it.
The problem with your suggestion is that the JS optimizer knows that charCodeAt(0) never causes an exception, so it removes the operation, resulting in a unflattened tree-string.

The expression `t1.charCodeAt(0) == 0 ? t1 : t1` ensures that if the result is used, it will have been indexed, and hopefully flattened by the JS engine.
