### ISSUE TITLE
Remove (underscore) _-prefix for library-private fields

### ISSUE THREAD

**Issue by passsy** [dart-lang/sdk#28853]
Coming from Java/Kotlin this prefix drives me crazy. Here are some reasons why the underscore prefix wasn't a good decision:

- Refactoring requires an IDE. When changing a field from `public` to `private` (or vice versa) the variable name has to be changed everywhere. This requires an intelligent IDE to find all usages because a simple find and replace may also accidentally change other code. A modifier, like in Java, can be changed without touching the name. This may cause compilation errors when restricting the visibility but is fine when promoting fields.
- Diffs are huge. Changing a single visibility may result in huge diffs because the change must be applied for every use.
- The name of a variable shouldn't have a function at all. When a prefix makes my code better readable I can add it on my own. But I should be able to decide if `m`, `_` or 💩 is the best choice for me.
- IDEs are smart. Modern IDEs can detect the visibility of a variable and [highlight it visually](http://jakewharton.com/just-say-no-to-hungarian-notation/). Adding this information manually, over and over again, is not required anymore.
- It's the only prefix in dart. Other prefixes from the JavaScript world such as [`k` for enums](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#Prefixes) aren't required. Why is this one required?

Possible alternatives:

```dart
class PrivateFieldExample {

    String _test = "normal dart 1.x";

    private String test = "like Java";

    @private
    String test = "could also be an annotation";

    internal String test = "Kotlinish, because _ doesn't mean private but library-private";

    // library-private could be the default modifier for fields (or at all)
    // whereas public fields must be marked as such
    String test = "private by default";
    public String test = "public because defined like that";
}
```

I haven't found any documentation why the underscore was used in the first place. I'd like to understand the reason behind this decision and what it would require to change it.

**Comment by lrhn** [comment]
Privacy has two purposes: access restriction and clash avoidance.
If a class has a private member, outside clients can't access it, but they also can't accidentally clash with the member if they extend the class. The former is nice to have, but not really essential. The latter is necessary to prevent simple refactorings from being breaking changes.

In statically typed languages, any member access is allowed by recognizing the static type of the receiver, and seeing that it has a publicly visible member of that type. In such languages, you can't override a public virtual member with a private one (because that would be unsafe). That is, you statically know, at each member access, what the declared visibility of the member is.

Dart, on the other hand, is a dynamic programming language. You can write a function like
```dart
foo(dynamic o) => o.someMethod();
```
That function will call a `someMethod` on *any* object (and fail at runtime if the object doesn't have one). If an object in the same library has a private `someMethod` declaration, should that be callable by `foo`? If the same object has a non-private `someMethod` as well, should that be called? How is an IDE to know?

To make *dynamic* calls simpler and more efficient, Dart makes it absolutely clear that a private member doesn't have the same name as a public member. That means that the invocation `o.someMethod()` can work on any object, without any static information, and without having to check visibility at runtime, and so can `o._someMethod()`.

There are definitely other approaches that could have been used. E.g., the Go language uses the case of the first letter as a privacy marker (upper-case public, lower-case private). Other dynamic languages don't have privacy at all (JS) or use a similar scheme (Python's `__` prefix).

To be honest, I don't mind the `_` at all any more. It's a prefix, so it doesn't get in the way of the actual name, and it was deliberately chosen to be inconspicuous.

**Comment by passsy** [comment]
Thanks a lot for the insights! I totally forgot about dynamic calls. It makes perfect sense to prevent name clashes. 

My goal behind making things private is not to prevent access. I want to be clear what's public API and what's only for internal use and give guidance for the IDE. Couldn't such a prefix be added _automatically_ by the compiler? If someone intends to use my private API they should be either "guess" the method name dynamically or use the mirrors API.

Just quick answers of your questions:

- What if the object [with the private function] was from a different library?
-> throw `NoSuchMethodError` with dynamic access (`o.someMethod()`) but allow discovery of this method via mirrors API or dynamically with pure guessing (`o.$private$someMethod()`)

- If the same object has a non-private someMethod as well, should that be called?
-> It shouldn't be allowed to define the same signature with different visibilities at once.

- How is an IDE to know?
-> The IDE never suggests private methods/fields outside of the defined lib.

**Comment by lrhn** [comment]
> What if the object [with the private function] was from a different library?
> -> throw NoSuchMethodError with dynamic access (o.someMethod()) but allow discovery of this method via mirrors API or dynamically with pure guessing (o.$private$someMethod())

That's basically the approach Python is using. Dart wanted to actually make private mean private, so the name is something that you can't guess. Which is sometimes annoying, because you can't access it for testing either, so we have things like `@publicForTesting` too. On the other hand, it does prevent users from relying on your internal methods, no matter how convenient it might seem to them at the time. I believe some of the early thinking here was guided by experiences from Java - users don't care why their code breaks, they just don't want it to happen, even if they are relying on something that's intended as private. If it has stayed available and consistent for several versions, and it's convenient, then there is a real risk that users will depend on it anyway.

> If the same object has a non-private someMethod as well, should that be called?
> -> It shouldn't be allowed to define the same signature with different visibilities at once.

That's exactly the problem that sharing a name-space causes. If a super-class has a private member, can a subclass declare a public member with the same name? This answer says no, but that means that adding a *private* members can cause an extending class to be an error. The dependency between a class and its superclass is already the tightest dependency in the language, and if you also don't allow the superclass to add private members, it is really becoming impossible to refactor the superclass.

> How is an IDE to know?
> -> The IDE never suggests private methods/fields outside of the defined lib.

If it's only for suggesting, then I guess that would work. For the dynamic call, it can't suggest anything anyway. I guess coloring can also work for the cases where you do know the type of the receiver.
So, it can do stuff, but it will have to give up in some cases too.

**Comment by floitschG** [comment]
The "_" approach is also very simple: when compiling the code, replace any leading "_" of identifiers with a token that is unique to the current library. After that, the compiler does not need to deal with privacy anymore.

Example:
``` dart
var _foo;
print(_foo);

// Replaced with
var <lib1_token>_foo;
print(<lib1_token>_foo);
```

This also explains, why private variables don't clash when they are in different libraries, but can be overridden in the same library:

``` dart
// In lib1.dart
import 'lib2.dart';

class A {
  String _foo() => "A";
  void bar() { print(_foo()); }
}

class C extends B {
  _foo() => "C";
}

// In lib2.dart:
import 'lib1.dart';

class B extends A {
  _foo() => "B";
  void gee() { print(_foo()); }
}

class D extends C {
  _foo() => "D";
}

main() {
  new A().bar();  // => "A" as expected.
  new B().bar();  // => "A"  (bar doesn't see the `_foo` from `B`.
  new C().bar();  // => "C"  (bar sees the overridden `_foo`)
  new D().bar();  // => "C"
  new B().gee();  // => "B"
  new C().gee();  // => "B"
  new D().gee();  // => "D"
}
```

**Comment by floitschG** [comment]
Closing, since there is no plan to change the privacy rules in Dart.
