### ISSUE TITLE
Is runtime/bin/service_object_patch.dart dead code?

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#28882]
I see a number of issues in runtime/bin/service_object_patch.dart that leads me to conclude that it's dead code.

Notice that the error messages below are from the concatenated version of io.dart, and I believe all the errors originate from service_object_patch.dart.

```
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart: Error: Method not found: '_makeServiceError'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:975:40: Error: Method not found: '_sockets'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:984:38: Error: Method not found: '_sockets'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1005:39: Error: Method not found: '_files'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1014:40: Error: Method not found: '_files'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1020:42: Error: Method not found: '_processes'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1029:39: Error: Method not found: '_processes'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1178:34: Error: Method not found: 'sw'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1246:37: Error: Method not found: 'response'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1348:37: Error: Method not found: 'response'.
xcodebuild/ReleaseX64/patched_sdk/lib/io/io.dart:1387:37: Error: Method not found: 'response'.
```

**Comment by mraleph** [comment]
I think this is indeed a dead code. I could see in the Git history how it gradually got broken, e.g. @ricowind with https://github.com/dart-lang/sdk/commit/01eff8ce18be7eceb6ce0be1097005965edf2588 broke code using `NativeSocket._sockets` added by https://codereview.chromium.org/302173007. 

This managed to rot so much precisely because nobody run a proper compiler on all Dart files in the runtime.

I think this needs thorough review and maybe we should purge most of this code. @johnmccutchan what do you think? Does anybody needs these endpoints? Should we just kill this code or should we try to fix it?

@peter-ahe-google Peter, the first error `Error: Method not found: '_makeServiceError'.` seems to be a bug in fasta though. There is such static function in that file.

**Comment by johnmccutchan** [comment]
The service protocol support in dart:io shouldn't be removed.

**Comment by mraleph** [comment]
@johnmccutchan tests are probably testing something else and not this code because the code in question in `runtime/bin/service_object_patch.dart` references all kinds of non-existent methods and will _not_ work if called.

**Comment by mraleph** [comment]
I took a look at `file_service_test.dart` and found out that it tests something completely different: `ext.dart.io.*` service protocol extensions created by `dart:developer.registerExtension`, which (I think) superceeded the prototype implementation in `service_object_patch.dart`. I deleted the file and a bit of related C++ code and all tests continue to pass. https://codereview.chromium.org/2715253002

**Comment by mraleph** [comment]
@peter-ahe-google now we are down to a single error when compiling the SDK libraries:

```
$ out/ReleaseX64/dart pkg/front_end/lib/src/fasta/bin/compile_platform.dart --packages=.packages out/ReleaseX64/patched_sdk/ out/ReleaseX64/patched_sdk/platform.dill
out/ReleaseX64/patched_sdk/lib/_builtin/_builtin.dart:26:31: Error: Method not found: 'main'.
```

**Comment by peter-ahe-google** [comment]
Nice! Thank you.
