### ISSUE TITLE
"Constant creation cannot use a type parameter/variables"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28892]
Minimal reproduction:
https://dartpad.dartlang.org/bf960d4891ec8a8df2f430167e5aa769

```dart
class IsTyped<T> {
  final IsAlsoTyped<T> isAlso;
  
  const IsTyped([this.isAlso = const IsAlsoTyped<T>()]);
}

class IsAlsoTyped<T> {
  const IsAlsoTyped();
}

void main() {
  // A static error in strong-mode, a dart2js compilation error when run.
	// const a = const IsTyped<String>();
  // print(a.runtimeType);

  const b = const IsTyped<String>(const IsAlsoTyped<String>()); // OK
  print(b.runtimeType); // IsTyped<String> (Correct)
  
  const c = const IsTyped(const IsAlsoTyped<String>());
  print(c.runtimeType); // IsTyped (Did not infer <String>?)
}
```

In strong-mode there is a single static error:

```
// The object type 'IsAlsoTyped<T>' cannot be assigned to a parameter of type
// IsAlsoTyped<String>
const a = const IsTyped<String>();
```

When run via dart2js (didn't try the VM), a compile-time error happens:

```
// Constant expressions can't refer to type variables.
// Try removing the type variable or replacing it with a concrete type.
const IsTyped([this.isAlso = const IsAlsoTyped<T>()]);
```

---

At the very least, hopefully these error messages can be cleaned up - but I'd like some guidance on what exactly the rules are here, how it differs in strong-mode (if at all) - and if something like this is possible in the near future.

**Comment by zoechi** [comment]
Seems related to #28750

**Comment by lrhn** [comment]
The rule is that you cannot refer to a non-constant value inside a const expression. Const expressions are evaluated once, potentially at compile-time, so they cannot depend on anything that is only available at runtime, and they cannot depend on anything that might change. That includes type parameters.

The rule has been relaxed in some implementations of strong mode, which explains the discrepancy, but it was never allowed in spec-mode Dart, and it's not intended to be allowed in strong mode either.

You might be able to use `const IsAlsoTyped<Null>()` as the constant value instead of referring to the type parameter. It's assignable to all `IsAlsoTyped<T>` types, and since it's const, it's immutable, so you are unlikely to get into problems with the type being `Null`.

**Comment by natebosch** [comment]
cc @leafpetersen 

This came up as an area where using strong mode analyzer and testing on the VM does not catch a compile-time error in Dart2Js.

We might want to make this more strict in strong mode.

**Comment by jmesserly** [comment]
This example actually works now (prints `IsTyped<String>` for both). However this is not correct behavior anymore in Dart 2. This is supposed to be rejected as `const IsAlsoTyped<T>()` is not a valid constant expression. There's another bug tracking that fix, so I'm going to close this one out.
