### ISSUE TITLE
dart2js infers bad type for provided list

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28919]
In the following example, dart2js somehow gets the type for `x` wrong.

``` dart
int foo([List _methods = const []]) {
  final methods = new List.from(_methods);
  for (int i = 0; i < 3; i++) {
    methods.add((int x) => x + i);
  }
  return methods[0](499);
}

main() {
  print(foo());
}
```

Interestingly, just changing the initialization of `methods` "solves" the problem:
``` dart
int foo([List _methods = const []]) {
  final methods = []..addAll(_methods);
  for (int i = 0; i < 3; i++) {
    methods.add((int x) => x + i);
  }
  return methods[0](499);
}

main() {
  print(foo());
}
```

Initializing it with `_methods.toList()` is also buggy.

Running dart2js with `--disable-type-inference` also leads to correct results. This is clearly an issue with the type inference...

/cc @rakudrama 

thanks to @hermanbergwerf for finding this issue.

**Comment by dgrove** [comment]
any updates on this?

**Comment by rakudrama** [comment]
This is what I think is going on:

During type propagation, summary edges are added from the inputs at a call site to the parameters of the target, bypassing the call. There is no node representing an argument at the call - the ssa value is used, in the case of the methods.add call, the closure.

During tracing, isAddedToContainer and isParameterOfListAddingMethod work together to decide if (1) a value flows into a container and process the flow, or (2) if it flows into the function to be handled 'normally'. It is busted because isAddedToContainer is used at the call site where the receiver type is checked, and isParameterOfListAddingMethod is tested on the parameter (reached by the summary edge), independent of the call site or state of the receiver.  Thus it is possible for isAddedToContainer be false (the type returned by List.from is not a container type since we forgot to add List.from to the special rules for allocated lists) and isParameterOfListAddingMethod to be true (for JSArray.add's value parameter), preventing flow into the body. Tracing stops, leaving the closure both uncalled and unescaped, so the parameter type is <empty>.

The processsing of calls should probably be changed so that the decision on argument-to-parameter flow for the special cases occurs at the call site, where the parameter(s) of the targets satisfying isParameterOfListAddingMethod are explicity enqueued.

**Comment by rakudrama** [comment]
Fix available: https://codereview.chromium.org/2762493002/
