### ISSUE TITLE
Set environment variable on all bots (sdk and pkg) for telemetry

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28925]
PUB_ENVIRONMENT=dart_bots

See https://github.com/dart-lang/pub/pull/1521

**Comment by kevmoo** [comment]
@whesse ping?

**Comment by whesse** [comment]
I don't see many bots on the main waterfall that are running pub. Only the pub and pkg bots.  What do you mean about the sdk bots?  Which sdk bots are running pub?

I'll put the environment variable in the recipes for those bots.  Environment variables are kind of tricky, because we can't just set them on the builders - they get cleared.  Every step that runs a command needs to have that extra environment added to it, in the optional "env" parameter to the step.  So an enviroment variable isn't necessarily easier to set than adding a command-line option.

**Comment by whesse** [comment]
To be clear: you want this environment variable set on all the buildbot steps that run pub.
If someone manually runs "tools/test.py pkgbuild" on their local machine, this variable won't be set.

**Comment by kevmoo** [comment]
> If someone manually runs "tools/test.py pkgbuild" on their local machine, this variable won't be set.

Is there a common entry point that runs pub in these cases? Could we wrap those and set the environment?

...I don't consider these cases to be a big deal, though. Just want to be able to sample out the big cases...

**Comment by kevmoo** [comment]
Commit - https://github.com/dart-lang/package-bots/commit/6147541a417c631564fd36eeba7ee5d9f5ec1e38

@whesse would we call this "done"?

**Comment by whesse** [comment]
There is also the commit https://chromium-review.googlesource.com/c/456296/, which affects the pkg bots on the main waterfall.  The pub bots on the main waterfall are only running all the pub unit tests, using the test package.  These may run some parts of pub, also in subprocesses, but we don't have control over that.  We could add the environment variable to the commands that run the tests, if it is needed, but I don't see that it is.  Here is what we run:
Enter directory =  third_party/pkg/pub
Running /b/build/slave/pub-linux-be/build/sdk/out/ReleaseX64/dart-sdk/bin/dart /b/build/slave/pub-linux-be/build/sdk/third_party/pkg/test/bin/test.dart --reporter expanded --no-color

**Comment by kevmoo** [comment]
Looks good as of today!

Fixed with 6147541a417c631564fd36eeba7ee5d9f5ec1e38
