### ISSUE TITLE
Autocompletion window shows wrong type for final, implicitly typed object (dynamic instead of real type)

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28976]
First SS shows wrong type info:
![capturfiles-20170307_010311](https://cloud.githubusercontent.com/assets/116654/23655780/d718fb7e-0336-11e7-9aa4-94a74d477161.png)

Second SS shows the type info (now correct) if I STRG+hover over _records 
![capturfiles-20170307_010407](https://cloud.githubusercontent.com/assets/116654/23655785/dce01862-0336-11e7-85e9-62883ebfb4ad.png)

**Comment by alexander-doroshko** [comment]
@floitschG Code completion is powered by the Analysis Server, IntelliJ IDEA just renders suggestions. In this case `'dynamic'` type is given by the server, so I'm changing `area-intellij` to `area-analyser`. Minimal case to reproduce is:
```
main() {
  final _records1 = new List<String>();
  final _records2 = new List<String>();
  _rec<invoke completion here>
}
```
This may be by design, vars are declared as dynamic (cc @bwilkerson). Not sure why Static type on Cmd+hover is not dynamic on Mike's 2nd screenshot. For me it is:
![image](https://cloud.githubusercontent.com/assets/4499789/23745623/eab98362-04c9-11e7-8a28-e945e1db2475.png)

**Comment by zoechi** [comment]
@alexander-doroshko did you enable strong mode?

**Comment by alexander-doroshko** [comment]
No. Ok, with the strong mode I have the same as on your screenshots. For completion server still gives 'dynamic' type.

**Comment by bwilkerson** [comment]
With type inference being improved, this should now be working much better.
