### ISSUE TITLE
Failures in dart2js with Firefox 52

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#28983]
@sigmundch @whesse

**Comment by alan-knight** [comment]
https://codereview.chromium.org/2732963006/

**Comment by alan-knight** [comment]
Calling this high priority, because there are failures in basic things like number parsing.

**Comment by rakudrama** [comment]
These seem to be related to reclassifying U+180E MONGOLIAN VOWEL SEPARATOR.
We should decide what is the correct behaviour, and split out tests with U+180E

**Comment by alan-knight** [comment]
Given the root cause, this no longer seems high priority.

**Comment by vsmenon** [comment]
fyi - these tests are starting to fail on chrome 59 now as well.

**Comment by lrhn** [comment]
We should probably track ECMAScript here because the reasoning is to allow use of ECMAScript functions directly when compiling to ECMAScript, at least as long as they do mostly the same thing as what we want.
ECMAScript 2017 says to use the latest version of Unicode (https://tc39.github.io/ecma262/#sec-conformance).

In the future, we will probably need some kind of strategy here - do we want to track the Unicode standard or the ECMAScript implementations (and if so, which ones)? The implementations are probably always going to trail the Unicode specification.

**Comment by floitschG** [comment]
This is now handled by #29060.
