### ISSUE TITLE
is-checks should not throw

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28988]
The following program leads to a runtime exception in DDC:

``` dart
typedef int F();
typedef String G();

Object foo() => () { return 499; };

main() {
  Object f = foo();
  print(f is F);
  print(f is G);
}
```

```
true

.../dart_sdk.js:2540
  throw new _js_helper.StrongModeErrorImplementation(message);
  ^
Strong mode is-check failure: () -> int does not soundly subtype G(() -> String)
```

**Comment by leafpetersen** [comment]
This is basically working as intended.  In order to preserve semantic coherence with non-strong mode platforms, we throw an exception at runtime if you ask an "is" check that we can't guarantee will produce the same result on all platforms.  It's based on a heuristic, so we could in principle do better, but I'm not sure it's a priority for us right now.

**Comment by floitschG** [comment]
Sounds like a good idea. However, the error message should be completely different then.

**Comment by vsmenon** [comment]
Filed #29216 for the error message.  Let's keep this one for the throw.

**Comment by vsmenon** [comment]
As long as we have this throw, we'll need to avoid code like this:

https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/future_impl.dart#L459

@floitschG @lrhn @leafpetersen - thoughts?  DDC could start just returning the sound result (instead of throwing if the answer differs from Dart 1).  There is the semantic coherence issue Leaf mentions above though.

**Comment by lrhn** [comment]
I would suggest starting to migrating DDC to Dart 2 semantics now. 

I know there are cases where code will do different things in the presence of `dynamic`, but you already do that with `List<dynamic>` not being assignable to `List<int>`, so I don't see `x is List<T>` being a bigger difference just because it happens at runtime. 

With `FutureOr`, we actually need to do the `is Future<T>`, not just `is Future`, to detect the correct `Future` branch of, e.g., `FutureOr<Future<Object>>`.
Not that I expect people to actually write that, but it's valid code and we should act correctly on it.

**Comment by jmesserly** [comment]
this one became more urgent, because we need to make sure the migrated Dart 2 tests can use these `is` checks without throwing.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/2996573002/
