### ISSUE TITLE
IntelliJ: Some lints/warnings persist in the editor after clearing

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28986]
<img width="527" alt="screen shot 2017-03-07 at 7 21 21 pm" src="https://cloud.githubusercontent.com/assets/168174/23688792/5b6615cc-036b-11e7-8f2f-c7ba98233fbd.png">

I fixed a lint of `comment_references`, and it no longer shows up in the analyzer view, but the little yellow mark remains. Clicking "re-analyze" does not fix it. It was fixed by restarting the analysis server though.

/cc @jwren

**Comment by alexander-doroshko** [comment]
@matanlurey 

>it no longer shows up in the analyzer view 

This probably means that the issue is at the IDE end. If you have a sample project and/or steps to reproduce (even if not 100% reproducible) it makes sense to file it in [JetBrains issue tracker](https://youtrack.jetbrains.com/issues/WEB) (Subsystem: Dart). Otherwise, it may be lost/forgotten/underestimated here.

**Comment by matanlurey** [comment]
This seems to have largely gone away in the last ~6 months.
