### ISSUE TITLE
Analyzer @override weird behavior

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#29009]
When adding a member field to a class named `override`, the analyzer gives the _Annotate overridden members_ warning. E.g.
```dart
abstract class Base {
  int get number;
}

class Test implements Base {
  int override = 2;
  
  @override
  int get number => 1;
}
```
(in fact this particular example gives a different error, that is even weirder, _Annotation can be only constant variable or constant constructor invocation_)

Does this mean I cannot use the names used for annotations as class fields? I thought annotations could only reference a const class constructor, not anything inside the class itself.

**Comment by bwilkerson** [comment]
An annotation can either reference a const class constructor (if they include an argument list) such as
```
@SeverityLevel(1)
```
or they can reference a constant variable (top-level variable or static field), which is what `override` is defined as (a top-level variable).

In either case, the names in an annotation are resolved just like any other identifiers, by looking at the surrounding scope. In this case, the first identifier named `override` that is found in scope is the instance field. But because instance fields cannot be used as annotations, you get the error message "Annotation can be only constant variable or constant constructor invocation".

The other error ("Annotate overridden members") is produced here because analyzer isn't first checking that the name `override` would be visible in this context.

Other than renaming the field, the other option would be to add an `ignore` comment to disable the lint.
