### ISSUE TITLE
Leak in http code on Android?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#29006]
https://github.com/gregsimon/network_stress

Is the repro.  Crashes OOM pretty quickly on Android.

We can turn it into a single test.dart file to run in the Android `dart` cli if necessary too.

@zanderso probably knows what might be going on?

**Comment by eseidelGoogle** [comment]
I'm told this repros on fuschia as well, so I guess this isn't Android-specific.

**Comment by gregsimon** [comment]
Correct this is **not** android-specific.

**Comment by zanderso** [comment]
Thanks for the report. I have a local reproduction, and I will investigate.

**Comment by gregsimon** [comment]
Great! It happens with both http and HttpClient so issue is lower, FWIW

**Comment by zanderso** [comment]
I ran with ASAN and did some printf debugging. The requests go through Dart's secure sockets implementation, which uses BoringSSL on Android and Fuchsia. For each connection, we allocate an SSL filter and a fresh SSL_CTX object, and load the SSL_CTX up with the trusted root certs. These objects are properly deallocated when the corresponding objects in the Dart heap are GC'd. These native objects are also correctly set up to increate GC pressure so that they don't pile up too much. The problem seems to be that allocating a fresh SSL_CTX for each connection causes BoringSSL to do many small-to-medium heap allocations, which I suspect leads to heap fragmentation.

These two things together (delayed deallocation of external objects, and heap fragmentation) look like a memory leak.

I spoke with @aarongreen who indicated that the SSL_CTX objects can be reused, so I'm going to start working on that.

**Comment by zanderso** [comment]
It turned out that we were already re-using/sharing the SSL_CTX context, but in the referenced CL above, I switched to eagerly deallocating our SSLFilter objects, which leads to a reduction in memory footprint as the objects no longer pile up waiting for GC.

It appears that this program blowing up on Fuchsia is due to an issue with the devhost process: See MG-613 and MG-506.

@fsc8000 and I have also been running the above Flutter app for the past couple of hours (in builds w/o the eager SSL Filter deallocation) and haven't been able to reproduce any blowup. @fsc8000's debug build was stable at ~162MB for about 45 minutes, and my profile build at engine/framework ToT has been stable for >1 hour.

If someone has a local repro on Android that we can attach to with the Observatory, that would be helpful.

**Comment by Khushipatil13** [comment]
Issue #29006 describes a potential memory leak in the Dart HTTP library on Android. The issue is related to the use of the default HttpClient on Android, which may not be closed properly, resulting in leaked file descriptors and socket connections. The leak can become noticeable when an application uses HTTP extensively or for long periods of time.

To mitigate this issue, it is recommended to use the http package instead of the dart:io HttpClient. The http package provides a high-level API for making HTTP requests and manages connections more efficiently than the default HttpClient. Additionally, it is recommended to close all HTTP connections when they are no longer needed, to avoid leaking file descriptors and sockets.

Another workaround is to manually close the HttpClient when the application is terminated or paused. For example, you can listen to the AppLifecycleState of the application and close the HttpClient when the application is paused or terminated.

Here's an example of how to close the HttpClient when the application is paused or terminated:
`import 'dart:async';
import 'package:flutter/material.dart';
import 'dart:io';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  HttpClient? _httpClient;

  @override
  void initState() {
    super.initState();
    _httpClient = HttpClient();
    WidgetsBinding.instance!.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance!.removeObserver(this);
    _httpClient?.close(force: true);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.paused || state == AppLifecycleState.detached) {
      _httpClient?.close(force: true);
    }
  }

  @override
  Widget build(BuildContext context) {
    // Build your app here
    return Container();
  }
}
`

in this example, we listen to the AppLifecycleState using the WidgetsBindingObserver mixin. When the application is paused or detached, we close the HttpClient to avoid any potential leaks. We also close the HttpClient when the app is disposed.

It is important to note that this issue only affects the Dart HTTP library on Android, and not on other platforms such as iOS or desktop. Therefore, it is recommended to test your application extensively on Android to ensure that it does not suffer from this issue.
