### ISSUE TITLE
VM crash with native stack dump

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#29025]
The following snippet crashes the vm with a native stack dump:
```dart
typedef T F<T>(T t);

class C<T extends F<C<T>>> {}

class D extends C<D> {
  C<D> call(C<D> x) => x;
}

main() {
  F<D> f = new D();
  var d = f(f);
  print(d);
}
```

`dart --version`: Dart VM version: 1.23.0-dev.0.0 (Tue Feb 14 14:23:50 2017) on "linux_x64".

**Comment by eernstg** [comment]
This one, too:
```dart
typedef T F<T>(T t);

class C<T extends F<T>> {}

class D extends C<D> {
  D call(D x) => x;
}

main() {
  F<D> f = new D();
  var d = f(f);
  print(d);
}
```

**Comment by crelier** [comment]
This is a tough one.
When finalizing an generic type, we check its upper bounds.
In order to very the upper bound F of the type parameter T (i.e. D) of the super type of D (i.e. C<D>), we need a type test checking if class D is a subtype of F, i.e. we need to check the signature of its call method, which is only available after class D has been compiled. However, in order to compile D, its super type must have been finalized.
In this very tricky case (thanks for the report!), we need to somehow postpone bound checking until after the class has been compiled.
