### ISSUE TITLE
Fasta's scanner and parser should support generic comment syntax

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29043]

**Comment by lrhn** [comment]
It would be really great if we could avoid reimplementing that hack. 
Sadly, there are currently a few hacks where it's still being used, even if we have the real syntax available:
- At least one class (`StringSplitter`) where the actual `implements` clause is different between Dart 1 and strong-mode because the original typing isn't valid in strong-mode.
- Some cases where an `as` cast is required in strong-mode, but would be unnecessary overhead in Dart 1, so the cast is `as dynamic /*=TheActualType*/`.

The latter can be removed, but with a performance cost in Dart 1.0 (it likely has that cost in strong mode too). The former is a breaking change to remove, and we plan to do that only with Dart 2.0.

**Comment by stereotype441** [comment]
Dart no longer has any need for the generic comment syntax, so this is no longer necessary.
