### ISSUE TITLE
No analyzer warning for duplicate type parameters in scope

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#29057]
Take this code:

```dart
class A<T> {
  List<T> t;
  
  void fn<T>(List<T> t) {
    this.t = t;
  }
}
```

https://dartpad.dartlang.org/3cbff059ad7b36d650761793b07c79d8

Is this allowed by the language? It's a new question, right? Since only recently could one entity with type annotations be declared in the scope of another (a paramterized function inside a parameterized class).

I hope it's not allowed, since you cannot access the outer T from inside the function. If it is allowed, what about a Hint?

**Comment by srawlins** [comment]
Is this an error as defined by the spec, @lrhn, @leafpetersen?

**Comment by eernstg** [comment]
This is a compile-time error because we don't have assignability between `List<S>` where `S <: Object` and `List<T>` where `T <: Object` (and no known relation between `S` and `T` exists) in this program:

```dart
class A<T> {
  List<T> t;
  
  void fn<S>(List<S> t) {
    this.t = t;
  }
}
```
The two programs only differ by a renaming, and this only serves to emphasize (as you mention) that we have an outer `T` and an inner `T` in the original program.

**Comment by srawlins** [comment]
Sorry, I opened this actually at a more innocent looking example; let's not intertwine the two `T`s:

```dart
class A<T> {
  List<T> t;
  
  void fn<T>(List<T> t) {
    print(t);
  }
}
```

As you mention, we have an outer `T` and an inner `T`, so I guess it's kosher, as they don't interact in this example. I'd suggest a Hint or a Lint.

Analyzer (2.0.0-dev.58.0) _does_ give an error for the original example now (albeit a head-scratcher):

```none
error • A value of type
    'List<T> (/usr/local/Cellar/dart/2.0.0-dev.58.0/libexec/lib/core/list.dart)' can't be assigned to a variable of type
    'List<T> (/usr/local/Cellar/dart/2.0.0-dev.58.0/libexec/lib/core/list.dart)' at c.dart:5:14 • invalid_assignment
```

**Comment by eernstg** [comment]
Ah, so I over-interpreted the title words 'No analyzer warning' because the actual example (the version we have now) _does_ give rise to an analyzer warning (an error, actually). Sorry, I should have checked that.

But then we're actually talking about this: Should we make scope based shadowing an error more frequently than we do today? Or this: Should we add new mechanisms to denote an entity named `n` when the declaration has been shadowed by another declaration named `n`? We could have support for `outer.T`, or something like that. There could be even more angles on it.

We do have some odd exceptions (e.g., it is a compile-time error to have declarations of a constructor `C.n` and a static getter `n` in the same class), but otherwise we have a pretty simple notion of unified lexical scoping, and we do allow shadowing in general. So we'd be talking about adding more exceptions in this area..

In any case, I think it would reduce the potential for confusing the reader if the example were changed back to the one that's only about scoping, not about (missing) subtype relations. ;-)

**Comment by leafpetersen** [comment]
I'd rather not make this a language error, I think.  I'd be fine with a lint, but this definitely makes things harder for code generators - you need to mangle type parameter names to be sure you don't conflict.  We already allowed this in Dart 1 for term level parameters:

```dart
void foo(int x) {
  void bar(int x) {
    print(x);
  }
  bar(3);
}
```

I don't really think that an additional type level restriction is worth it.

**Comment by srawlins** [comment]
Ah, I see. I'm cool with that. I think there is nothing to add to the language or analyzer. I've opened [a lint rule request](https://github.com/dart-lang/linter/issues/1009) and I'll close this.
