### ISSUE TITLE
IntelliJ Rename Field gets confused about multiple projects

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#29051]
Rename of a field that @overrides a base getter (the `types` field here: https://github.com/google/built_value.dart/blob/master/built_value/lib/src/num_serializer.dart#L12 ) works if I have only one project open, but fails if I have another project open with that same files.

1. Close all IntelliJ projects
2. Open project with that file, do rename --> works; revert
3. Open another project with that file, do rename in original project --> fails that it can't edit file in other project
   `Can't edit file outside of the project content: /usr/local/google/home/davidmorgan/uh/ddc-video-repro/google3/third_party/dart/built_value/lib/src/string_serializer.dart`

I see a similar issue when renaming a field that is overridden elsewhere in the code. It appears to look for files that need updating outside the current project, then try to edit them, then fail.

**Comment by alexander-doroshko** [comment]
@davidmorgan Since version 2017.1 ([Release Candidate available](https://www.jetbrains.com/idea/nextversion/)) IntelliJ IDEA starts a separate Dart Analysis Server per project, so this problem is not actual anymore.

I guess you use 2016.3 where there's a single Analysis Server that serves all open projects. With it the IDE fails to do cross-project refactorings. Would be great if you could check and confirm. I guess this issue can be closed.

**Comment by davidmorgan** [comment]
Yes, I am on 2016.3.1. Thanks.

**Comment by bwilkerson** [comment]
Please re-open if you still see the problem after upgrading.
