### ISSUE TITLE
Make Dartium ServiceWorker-friendly

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#29093]
Currently it is not possible to develop ServiceWorkers with Dartium (45.0.2454.104). A few items I've found blocker (so far):

- While Chrome has a special tab (Application / Service Workers) for checking their status and unregistering them, Dartium has no similar screen.

- Neither the `dart:html` version, nor the `package:service_worker` (using `package:js`) seems to work for various different reason. Previously I've got Exceptions that I was not able to surround with `try-catch`, today it is failing silently, without any error, it just do not work.

- At one point I've seen the compiled `.dart.js` version to be running, but I was not able to get another working version of that. Loading the `.dart` version never worked.

For testing, please take a look at the examples in either of the following libraries, especially the PWA library's `pwa_defaults` example.
https://github.com/isoos/service_worker
https://github.com/isoos/pwa

/cc @filiph 
suggested label: area-dartium

**Comment by filiph** [comment]
The simplest possible 'fix' for Dartium is to just ignore ServiceWorker altogether. 

Right now Dartium crashes the app (outside userspace, so un-catch-ably). That means that once the user starts playing around with ServiceWorker, Dartium stops to be an option, and they suddenly have to deal with looong dart2js refreshes, even when not working on SW stuff.

Since ServiceWorker is a _progressive_ enhancement, it's okay to just keep on trucking. Either show a warning or not. The point is that I can still developer and debug the core app with instant refresh dev cycle, and only switch to dart2js for SW stuff.

I know DDC fixes this but unless we very quickly move the whole world from Dartium to DDC, this fix still makes sense, imho.

**Comment by kevmoo** [comment]
We're not going to get this working in Dartium. DDC will be our dev path here.

CC @jacob314 @terrylucas @dgrove for commentary, if any
