### ISSUE TITLE
Inconsistencies of Dart grammar in the Specification

### ISSUE THREAD

**Issue by gabrc** [dart-lang/sdk#29115]
I found the following inconsistencies regarding some grammar productions between the Dart Language Specification (4th ed, Dec 2016) and the Dart compiler implementation. They should simply require a fix to the spec.

* In **topLevelDefinition**, the spec does not allow **staticFinalDeclarationList** to contain **metadata**, but the compiler allows it.

* In **topLevelDefinition**, the spec requires **staticFinalDeclarationList** to be either **final** or **const**, but the compiler allows one to be neither.

* In **topLevelDefinition**, the spec does not allow get/set functions to contain **metadata**, but the compiler allows it.

* In **formalParameterList**, if no optional/named parameters are present, the compiler allows **normalFormalParameters** to have a trailing comma, but the spec does not allow it.

* In **optionalPositionalFormalParameters**, a trailing comma is allowed by the compiler but not the spec.

* In **namedFormalParameters**, a trailing comma is allowed by the compiler but not the spec.

**Comment by eernstg** [comment]
Thanks for reporting these issues, Gabriel! I'm currently working my way through the grammar and I have noticed them; you'll get a consistent grammar soon.

In my (half-done) grammar, I've changed `libraryDefinition` to contain `(metadata topLevelDefinition)*` rather than a plain `topLevelDefinition*`, but that entails some other adjustments in order to avoid duplication of `metadata`.

With respect to `staticFinalDeclarationList`: It's used for `final` and `const` declarations, and it requires initialization for every declared variable. If your top level variable is neither `final` nor `const` then you have the option to leave out the initializing expression. For that you'd use `variableDeclaration` --- but this means that you cannot even opt in and initialize it, so I've corrected that to `initializedVariableDeclaration`. 

Top level getters and setters will be allowed to have metadata because of the abovementioned change to use `(metadata topLevelDefinition)*`.

For the trailing commas, you're probably looking at a version of the spec which is so old that it doesn't contain that change (we haven't published all spec updates as ECMA documents). For instance:
```
formalParameterList
    :    '(' ')'
    |    '(' normalFormalParameters (','? | ',' optionalFormalParameters) ')'
    |    '(' optionalFormalParameters ')'
    ;
```
Take a look at (the spec source)[https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex] to see all updates.

So you're right that we need to go over the grammar and fix several problems, but we are indeed doing that.

I'll close this issue because all elements in it are already known---but thanks for taking a careful look at it, and telling us about it!

**Comment by eernstg** [comment]
You can check out the grammar I'm working on [here](https://codereview.chromium.org/2688903004/).

**Comment by floitschG** [comment]
Reopening until the spec is actually updated.

**Comment by gabrc** [comment]
Thank you for the response. I just have 2 minor comments to make.

1. In [https://github.com/dart-lang/sdk/blob/master/
docs/language/dartLangSpec.tex] and previous specs, getOrSet is not used
anywhere.

2. In the Dart API implementation, some functions are declared with
"native", but this does not appear in the spec. Even though users do not
use it, should we include the "native" function declarations in the grammar
too?

**Comment by eernstg** [comment]
Right, getOrSet is not used; it is in fact gone in [the grammar I mentioned](https://codereview.chromium.org/2688903004/). We will need to keep track of all these changes, but I currently plan to go over the resulting grammar (when it works well enough) and make all the adjustments in the spec in one go, relying also on all the notes I've written about these changes when I made them. This issue serves as a reminder in that process as well.

The keyword (or whatever it is) `native` is actually not part of the language, because there is no promise to Dart developers in general that they can connect Dart code with, say, C code by means of a `native` declaration. This is only possible in core libraries because they are connected with the language implementation itself. So I don't expect `native` to become part of the language specification.

**Comment by eernstg** [comment]
No milestone now: This correction is part of a larger update of grammar related parts of the specification, based on [Dart.g](https://github.com/dart-lang/sdk/blob/master/docs/language/Dart.g).
