### ISSUE TITLE
Name conflicts be downgraded from an error

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29146]
Resolution conflicts are now errors instead of warnings in strong mode:

E.g., given:

`f1.dart`:
```
class Error {}
```

`f2.dart`:
```
import 'f1.dart';
void main() { print (new Error()); }
```

we get:

```
Analyzing [f2.dart]...
[error] Element 'Error' from SDK library 'core.dart' is implicitly hidden by 'f1.dart'. (/Users/vsm/ddctest/f2.dart, line 2, col 26)
1 error found.
```

Should we downgrade this back to warning?  It's causing some problems on internal, generated protobuf files.  The pb code should probably be better about prefixing too.

**Comment by vsmenon** [comment]
@floitschG @leafpetersen @bwilkerson - any objections to downgrading this back to a warning?

I do suspect warnings are somewhat ignored in the internal build, so there is some danger that downgrading will mask real bugs.

**Comment by leafpetersen** [comment]
As long as we can in fact deterministically resolve which name matches to what, I don't think I care that much whether it's a warning or an error.

**Comment by lrhn** [comment]
The override rules are there for a reason. It allows us to add members to platform libraries without conflicting with other libraries. If shadowing the platform library version is an error, then we have lost the advantage of allowing the override to begin with.
It shouldn't be an error, and probably shouldn't have been a warning to begin with,.

One of the design goals of Dart 2.0 is to not have warnings in the language specification.
If it doesn't work, it's an error. If it works, don't warn about it.

In this case, I'd say it's not-an-error, so it should just be allowed.

Now, if the code *doesn't* work, but it would work if you were seeing the `dart:core` version, then we can give a good *error* message telling you why your program is broken.

It's unlikely that you can shadow a core class by accident, use the wrong class, and not get a type error. That was much easier in Dart 1 (you only got warnings anyway), but in Dart 2 I don't think this will happen by accident, and if it's not an accident, then we shouldn't get in the way of it.

**Comment by keertip** [comment]
@vsmenon , @leafpetersen, could you folks decide what needs to be done here and make the changes? This is currently breaking bleeding edge in google3.

**Comment by vsmenon** [comment]
@keertip : I think @lrhn changed the name (`StreamGroup`) that's blocking the roll.

**Comment by keertip** [comment]
@vsmenon, yes I saw that, but this has the potential to break targets for the next similar change in the SDK.

**Comment by vsmenon** [comment]
I've moved this to a 1.25 analyzer task.

@floitschG can you please clarify if you guys want this to be a warning (current non-strong behavior I think) or nothing at all?

**Comment by eernstg** [comment]
I don't see anyone mentioning the distinction between a conflict with names from a system library and another library, and conflicts between two non-system libraries. The former were designed to go away implicitly ('the import of L_1 [which is where the system library name came from] is implicitly extended by a `hide N` clause', and there is a 'static warning'), such that we could add stuff to system libraries without breaking _everything_, especiallly with 'dart:core', and the latter are simply statically known conflicts (with no obvious asymmetry, so the language can't reasonably resolve the conflict).

Hence, these two cases are treated differently for a reason, and I don't think it's an improvement to drop that distinction. So I'd prefer to keep the "implicit hide" mechanism for system libraries, and keep considering non-system/non-system conflicts unresolved. The Dart 1.x spec indicates that the latter is a static warning plus a run-time semantics that always fails, but I would have no problem making non-system/non-system conflicts an error.

But I also think we should give developers a heads-up at system/non-system conflicts: If you are reading the code and see a familiar name then you're quite likely to assume that it's the well-known declaration from a system library, and not some arbitrary other declaration of the same name. This is very likely to create misunderstandings and hence bugs.

So it's a good idea to keep the current "implicit hide" mechanism and make system/non-system conflicts a warning (rather than an error). But non-system/non-system conflicts will have to be failing, and they are statically known, and they make the semantics of the program ambiguous, so the strong mode style would be to keep them as errors (rather than emitting a warning and throwing at runtime).

**Comment by bwilkerson** [comment]
@vsmenon What is the purpose for assigning this issue a milestone?

**Comment by vsmenon** [comment]
Recent SDK changes broke the internal roll.  Fixing this would ease future rolls.

**Comment by vsmenon** [comment]
@keertip @srawlins

**Comment by floitschG** [comment]
Could we make this a priority for 1.25?

In particular, we are planning to deprecate `SplayTreeMap` from `dart:collection` and move it to the `collection` package instead.
However, at the moment, this would mean that every user that imports `dart:collection` and `package:collection` at the same time would have an error with strong mode. Ideally, a user should not even see a warning/hint, if the shadowed class is deprecated.

**Comment by vsmenon** [comment]
This is also blocking marking package:crypto as strong-mode clean (used internally).

@devoncarew - will someone on the analyzer team be able to do this?  I suspect it's not a lot of work - just downgrading.

**Comment by vsmenon** [comment]
I.e., these should not be errors:

```
[error] Element 'Base64Encoder' from SDK library 'dart:convert' is implicitly hidden by 'encoder.dart'. (package:crypto/src/base64.dart, line 72, col 16)
[error] Element 'Base64Decoder' from SDK library 'dart:convert' is implicitly hidden by 'decoder.dart'. (package:crypto/src/base64.dart, line 83, col 3)
[error] Element 'Base64Decoder' from SDK library 'dart:convert' is implicitly hidden by 'decoder.dart'. (package:crypto/src/base64/decoder_sink.dart, line 15, col 9)
[error] Element 'Base64Encoder' from SDK library 'dart:convert' is implicitly hidden by 'encoder.dart'. (package:crypto/src/base64/encoder_sink.dart, line 15, col 9)

Please fix all errors before compiling (warnings are okay).
```

**Comment by devoncarew** [comment]
> This is also blocking marking package:crypto as strong-mode clean (used internally). I suspect it's not a lot of work - just downgrading.

The prioritization sgtm - re-assigning to @bwilkerson.

**Comment by jmesserly** [comment]
oops ... I didn't see Vijay's comment above about assignment ... anyway I've got a fix for this if interested : https://codereview.chromium.org/2916223002

**Comment by bwilkerson** [comment]
I sent mine out for review this morning (https://codereview.chromium.org/2920853002/) but missed updating the ddc status. You should commit yours.

**Comment by jmesserly** [comment]
oops. sigh. i'm not paying any attention today. my apologies! but yeah I can land it with the DDC status update. Thanks so much :)
