### ISSUE TITLE
Fasta needs API for modular compilation

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#29172]
Several FE integration issues depend on an ability to compile given the library or even just a snippet of Dart code to unlinked Kernel binary. 

Current compilation paths all produce fully linked binaries that include the whole application plus its transitive dependencies.

**Comment by mraleph** [comment]
This issue is on the critical path and needs an owner. /cc @a-siva @kasperl

**Comment by kasperl** [comment]
From a glance, Peter and Kevin seem like the right owners for this. Thanks, Slava!

**Comment by sigmundch** [comment]
@mraleph I believe this is supported today by the FE when using the [kernelForBuildUnit][1] API. Let me know if that's not enough for what you need, otherwise I believe we can close this issue.

The API requires you to provide outline .dill files for dependencies used by the code you want to compile. We call these "input summaries" in the API (we are trying to also unify terminology with the analyzer summaries). The output will contain an outline of those input summaries marked as external libraries. There is also a BinaryPrinter that can serialize only non-external libraries, so it would include only what you are compiling (if you want).

See also:
 * [unit tests of modular compilation][2], shows how we do a sequence of modular builds, providing .dill files as input summaries.
 * kernel-service.dart shows how to call [serializeProgram with a filter][3]

[1]: https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/kernel_generator.dart#L55
[2]: https://github.com/dart-lang/sdk/blob/master/pkg/front_end/test/kernel_generator_test.dart#L174
[3]: https://github.com/dart-lang/sdk/blob/c78b338a52120bef388f7cdcd6e7f4fe04c56484/utils/kernel-service/kernel-service.dart#L113

**Comment by kmillikin** [comment]
I think the remaining missing piece is an API to be used for expression evaluation (e.g., in a debugger).  That is issue #31755.
