### ISSUE TITLE
How can we debug remote minified code as if it were served locally?

### ISSUE THREAD

**Issue by dustinlessard-wf** [dart-lang/sdk#29194]
We develop our apps in Dart, transpile it to minified javascript, and then deploy the javascript + sourcemaps to our production environment.

There are times when **we want to debug the production code (breakpoints, stepping over/through, etc) within the context we developed it in - Dart.**  We don't really want to deploy our Dart files though.

We’ve attempted to use Chrome Workspaces to map the `main.dart` file that is referenced in our sourcemap to a local copy of the file, and this works.  The problem is all the other dart files that are in play.  Those each need to be individually mapped, which is problematic by itself. Considering our dependencies are contained within the pub cache, and only referenced through the .packages file, it becomes impractical to continue with this approach.

We’ve also attempted to accomplish this goal via Webstorm, but found that it doesn't support mapping remote javascript to local Dart code via sourcemaps.

We’ve also attempted to use a proxy like ‘Charles’ but found it suffered from the same issues that the Chrome Workspaces approach suffers from.

**Are there any known ways to accomplish this?**

**Comment by sigmundch** [comment]
Thanks for the question - you may want to consider posting the question on stack-overflow as well. I believe other users also monitor that channel, so you may get additional ideas.

What I've seen many developers do is to have a staging server. This is practically identical to production, but an environment that only developers can access. Because of their limited visibility, you can safely attach the Dart sources or any other debug information, without actually deploying that externally to your users.

Hope this helps!

**Comment by sigmundch** [comment]
I don't believe there is any work pending on our end, so I'll close this issue shortly.
