### ISSUE TITLE
Spurious analyzer error when assigning generic closure literal to typed variable

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29236]
The code below should have no errors, but results in a single error, on the declaration of `f`.

```
    error • A value of type '<T>(T) → int' can't be assigned to a variable of type 'Foo(T) → int' at /Users/leafp/tmp/test.dart:6:11 • invalid_assignment
```

```dart
typedef Foo = int Function<T>(T x);
int foo<T>(T x) => 3;
void test() {
  var g = <T>(T x) => 3;
  // All three of the following should be equivalent from a typing standpoint
  g = <T>(T x) => 3;
  Foo f = <T>(T x) => 3; // error on this line
  Foo h = foo;
}
```

**Comment by jmesserly** [comment]
Commented about this in https://github.com/dart-lang/sdk/issues/29237#issuecomment-291566634 but my guess is that the "typedef Foo" is not creating a FunctionTypeImpl that is generic (type.typeFormals.isNotEmpty). The reason the last line `Foo h = foo;` works is most likely due to implicit instantiation (turning it into `Foo h = foo<dynamic>;`)

**Comment by mit-mit** [comment]
Should this be 1.23 @kevmoo ?

**Comment by leafpetersen** [comment]
It's possible this bug is just an instance of #29237 .  If not, if this is something specific to closure literals, I would say that this one could be pushed off.

**Comment by leafpetersen** [comment]
This specific issue was fixed by  https://codereview.chromium.org/2798663003/
