### ISSUE TITLE
Request for analyzer to evaluate and check asserts in initializer lists

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#29268]
Now that we have "const asserts" and "asserts in initializer lists" (which, Flutter is now using. Thank you!), it would be even more helpful if the analyzer could, at static analysis time, check those asserts for us.

If we can see we're violating an assert, while editing the code, that would lead to an even more fluid developer experience.

Thanks!

**Comment by eernstg** [comment]
Assert in initializer lists are now [part of the language](https://github.com/dart-lang/sdk/commit/609d26a2274ccde0f74725f4df7e081ebc8ea020), so this issue is now concerned with all customers and not Flutter alone.

This feature is covered by some tests, but one of them was just modified (`language{,_2}/assertion_initializer_const_error2_test.dart`). That test used to have a misplaced comma which introduced a syntax error in all other cases than `cc02`. So there was a `CompileTimeError` in case `none`, and all the other cases that ought to have `MissingCompileTimeError` until this feature is implemented instead had the syntax error, making it look as if the analyzer is already checking initializer assertions correctly. Cases `cc10` and `cc11` include a trailing comma in the assert, and they get the desired compile time error because that is treated as a syntax error. In summary, this test ought to track the implementation of assert-in-initializer, but almost all cases had misleading outcomes. I just adjusted  the language & language_2 analyzer status files accordingly:
```
assertion_initializer_const_error2_test/none: Pass
assertion_initializer_const_error2_test/cc10: Pass # Issue 29268
assertion_initializer_const_error2_test/cc11: Pass # Issue 29268
assertion_initializer_const_error2_test/*: MissingCompileTimeError # Issue 29268
```

**Comment by srawlins** [comment]
I'm not sure what const asserts are. It's possible the analyzer could still implement some kind of feature for this, but I'll close this old issue out in favor of any new ones.
