### ISSUE TITLE
pkg/meta: Support noreturn annotation on functions

### ISSUE THREAD

**Issue by postmasters** [dart-lang/sdk#29334]
This should have similar effect as GCC:

https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes

It is helpful in two cases:

1. To ensure that a noreturn function actually does not return any value, even void. It should terminate by calling to other noreturn functions.

2. To eliminate dead code in the same basic block after the call to a noreturn function.

**Comment by postmasters** [comment]
#29213

**Comment by amatveyakin** [comment]
How does this related to `@alwaysThrows` annotation (#17999)?

**Comment by eernstg** [comment]
With the upcoming null-safety feature, the properties mentioned [here](https://github.com/dart-lang/sdk/issues/29334#issue-221343070) are obtained with a function whose return type is `Never`. It is a compile-time error for such a function to `return`, and also to be able to reach the end of the function body (which implicitly means `return;` at that point). So it's coming!

This makes `@alwaysThrows` obsolete as well.

I'll close this issue, because there is no doubt that the null-safety feature bundle is coming, and it will deliver these features.
