### ISSUE TITLE
Bogus "Invalid constant value" analysis error

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#29358]
Here's the source file: https://fuchsia.googlesource.com/sysui/+/master/widgets/lib/scrollable_input_text.dart

Here's the analyzer error:
```
error • Invalid constant value at apps/sysui/widgets/lib/scrollable_input_text.dart:1:1 • invalid_constant
```

This is with a Dart SDK built from sources sync'd at:
```
commit 38e8b1509e8c983cd454c86d1f10561dc0de1ae0
Author: Konstantin Shcheglov <scheglov@google.com>
Date:   Tue Apr 11 11:28:00 2017 -0700

    Issue 29109. Resynthesize PrefixElement(s) to fix constants evaluation.
    
    R=brianwilkerson@google.com, paulberry@google.com
    BUG= https://github.com/dart-lang/sdk/issues/29109
    
    Review-Url: https://codereview.chromium.org/2815713003 .
```

The analyzer invocation is as such (paths edited):
```
dartanalyzer --packages=/path/to/.packages --dart-sdk=/path/to/sdk apps/sysui/widgets/lib/
```

/cc @apwilson @zanderso

**Comment by scheglov** [comment]
I agree that the reported error is bogus.

FWIW, we had this problem before too, but it was better hidden :-)

As I said in https://github.com/dart-lang/sdk/issues/29109#issuecomment-293317477, we have been reporting errors with offsets in one file, but associating errors with another file. So, these offset were wrong anyway. They just were not `0`, so not such obvious.

I think that the actual reason why you see these problems at all is because Flutter uses assert in constructor initializers, but this feature is not enabled in analysis options for your project. I might be wrong though. Anyway, this does not affect the fact that we should fix the problem is analyzer.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2825813002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/19353f9e633313e9b7452a51e9a80b09a16d25f0

**Comment by scheglov** [comment]
It works for me with this CL, and correctly annotates `const FractionalOffset(0.0, 0.5)` nodes.

**Comment by pylaligand** [comment]
I confirm that the bogus error is gone, thanks!

What do we need to add to our analysis options file to get rid of the error with FractionalOffset?

**Comment by scheglov** [comment]
I think something [like this](https://github.com/flutter/website/pull/497/files).

**Comment by pylaligand** [comment]
That worked.

**Comment by pylaligand** [comment]
It sounds like I spoke too early as the error is still there after I edited the options file:
```
error • Evaluation of this constant expression throws an exception at apps/sysui/armadillo/lib/armadillo.dart:50:22 • const_eval_throws_exception
```
pointing at
```
          alignment: const FractionalOffset(0.4, 0.5),
```
(https://fuchsia.googlesource.com/sysui/+/993cda740a03ca92b61f55ff6f1a1862b4a46536/armadillo/lib/armadillo.dart#50)
and an options file with
```
    enableAssertInitializer: true
```
(https://fuchsia.googlesource.com/sysui/+/993cda740a03ca92b61f55ff6f1a1862b4a46536/.analysis_options#4)

**Comment by apwilson** [comment]
Seems to be related to a cross package boundary.  If I use a constructor from another package with asserts in the initializer I get an analysis error.  If I pull the exact same code into my package the error goes away.

**Comment by Hixie** [comment]
cc @bwilkerson

**Comment by scheglov** [comment]
I don't understand how to reproduce the problem. Could you please specify which git repositories to check out (preferably exact commands) and which folders to open?

**Comment by apwilson** [comment]
I *think* a repro case is to make a dart package that has a class that
asserts in it's const constructor.  Then make a second dart package that
imports and uses that const constructor.

On Apr 24, 2017 8:44 AM, "Konstantin Scheglov" <notifications@github.com>
wrote:

I don't understand how to reproduce the problem. Could you please specify
which git repositories to check out (preferably exact commands) and which
folders to open?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/sdk/issues/29358#issuecomment-296712735>, or mute
the thread

**Comment by bwilkerson** [comment]
Do both packages enable the use of asserts in initializer lists?

**Comment by apwilson** [comment]
yes

**Comment by scheglov** [comment]
I can reproduce this using the command line analyzer.

**Comment by scheglov** [comment]
And it works fine when I open the folder that contains both packages in IDEA, so analyze them using Analysis Server. I suspect there might be a bug with finding and using `.analysis_options` files.

**Comment by pylaligand** [comment]
If that's the case then https://github.com/dart-lang/sdk/issues/29429 is likely another instance of the issue, although the resulting error/warning is different.

**Comment by scheglov** [comment]
Yes, I thought so too.
They're both caused by not parsing assert initializers correctly.

**Comment by pylaligand** [comment]
Is there any more information we can provide you with for these two issues?

**Comment by bwilkerson** [comment]
Given that #29429 should now be fixed, is there still a problem here that we need to be working on?

**Comment by pylaligand** [comment]
Nope!
