### ISSUE TITLE
Unused class causes bogus "illegal recursive type" error.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#29357]
The following file:

    abstract class A<T extends A<T>> {}

    abstract class B<T extends A<T>> {}

    class C<U> extends B<D<U>> {}

    class D<U> extends A<D<U>> {}

    main() {
      new D();
    }

Causes the VM to output the error message:

    error: line 7 pos 22: illegal recursive type 'D<U>'

(Note that line 7 pos 22 is the location of the second `D` in `class D<U> extends A<D<U>> {}`)

Analyzer and dart2js don't report any errors for this file.

Interestingly, commenting out the line `class C<U> extends B<D<U>> {}` makes the error go away.  This is surprising because the class `C` is not reachable from the code containing the error (in fact, the class `C` is not used at all!)

**Comment by crelier** [comment]
The Dart Language Specification does not disallow the declaration and use of non-contractive types. They are nevertheless disallowed as an implementation restriction in the VM since they cause divergence.
However, you are right that something does not look right in this test case. I suspect that the detection of non-contractive types is broken. I'll have a look. Thanks for the report.
