### ISSUE TITLE
Future needs a method that returns void and catches all results

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29361]
I wish there was an equivalent to "then" or "whenComplete" and so forth that represented the "end" of the Future chain.

That is, this method would return `void`, and would count as catching any error thrown by the future.

Something like:
```dart
finishWith(T value, dynamic error, StackTrace stack);
```

...(where `error == null` indicates the future completed).

For example:

```dart
   Future<String> foo = fetchValueFromNetwork();
   Future<int> bar = foo.then<int>(convertValueToData);
   bar.finishWith((int value, dynamic error, StackTrace stack) {
     if (error != null) {
       print('Failed: $error');
     } else {
       print('Got $value!');
     }
   });
```

This would make working with Futures much more satisfying. The current model is problematic because whatever you do with a Future, you always end up spawning another Future that itself needs to be dealt with and the chain never really ends.

**Comment by Hixie** [comment]
Another reason to want this is that there's currently no way to respond to a future ignoring whether it failed or not, _and eating any exception_. If you use `whenComplete`, errors are still considered unhandled.

You end up having to do:

```dart
future.then((T value) {
  // handle future completion...
}, onError(dynamic exception, StackTrace stack) {
  // duplicate code above to do the same in the error case...
});
```

**Comment by Hixie** [comment]
We're now working around this in Flutter by providing our own version of this in our Future subclass:
https://github.com/flutter/flutter/pull/10016/files#diff-f9a90c555622b4ac16b6dd52ffc68b65R369

**Comment by Hixie** [comment]
@matanlurey is this fixed?

**Comment by lrhn** [comment]
There is no way to "eat" an exception. All exceptions must be explicitly handled, no exception must be dropped on the floor. That's a deliberate choice.

Having to use two different functions for `then(onValue, onError: onError)` is a better API than one that takes three arguments and requires you to deduce which mode the function is called in depending on whether `error` is `null`. 

I would just recommend using `catchError` to handle errors, and then assume no errors after that.
Instead of 
```dart
future.then((T value) {
  // handle future completion...
}, onError(dynamic exception, StackTrace stack) {
  // duplicate code above to do the same in the error case...
});
```
you do:
```dart
var handled = future.catchError(ignore).whenComplete(() {
  // handle future completion...
});
Null ignore(x, [_]) => null;  // helper, or just write (_)=>null inline.
```

Another option that does seem to solve the immediate problems is to use `Result.capture` from `package:async` on the future. This gives a future again, one which completes with a `Result` which is a *tagged* union of a result and an error. That's also a better API than a three-argument callback, and it allows you to drop the result since errors are captured and turned into `ErrorResult` instances, not actual errors.

In either case, there is no current plan to change the `Future` API for Dart 2.

**Comment by Hixie** [comment]
`whenComplete` doesn't solve this problem because it returns a future and doesn't expose the value (or error).

IMHO we should reopen this bug since the underlying issue isn't resolved.

**Comment by lrhn** [comment]
In the example I gave, the `whenComplete` returns a future that you can ignore. If you want to handle the value, use:
```dart
future.catchError((e, s) { 
  handleError(e, s); // however.
  return null;
}).then((value) {
 // Act on result if it isn't null.
});
```
Again, you can freely ignore the returned future. Ignoring returned futures is perfectly acceptable.

Still, there are no plans to change the `Future` API at the current time.

**Comment by Hixie** [comment]
> returns a future that you can ignore

The linter complains "Await future-returning functions inside async function bodies" if you use `whenComplete`, so it doesn't address the original request of this bug.

```dart
import 'dart:async';
Future<void> main() async {
  new Future<void>.value().catchError(() => null).whenComplete(() { }); // error on this line
}
```

To reiterate, I wish there was an equivalent to "then" or "whenComplete" and so forth that represented the "end" of the Future chain. This is as opposed to "whenComplete", which returns a Future, and therefore is by definition not the "end" of the chain.

There is currently no way in Dart to cleanly write this code:

```dart
   Future<String> foo = fetchValueFromNetwork();
   Future<int> bar = foo.then<int>(convertValueToData);
   bar.finishWith((int value, dynamic error, StackTrace stack) {
     // lots of code, variable declarations, etc...
     String result;
     if (error != null) {
       // code that uses the earlier variable declarations
       result = 'Failed: $error';
     } else {
       // code that uses the earlier variable declarations in a different way
       result = 'Got $value!';
     }
     // lots of code that uses the earlier variable declarations and result...
   });
```

> Still, there are no plans to change the Future API at the current time.

I understand; changing those plans is exactly why I filed this bug, and since they haven't changed, the bug is still unresolved and should be open. :-)

**Comment by natebosch** [comment]
This issue seems to cover two topics:

1. A single API for error or value case.  Here is your example using `Result` from `package:async` to solve this problem.

```dart
  Future<String> foo = fetchValueFromNetwork();
  Future<int> bar = foo.then<int>(convertValueToData);
  Result.capture(bar).then((result) {
    // lots of code, variable declarations, etc...
    String result;
    if (result.isError) {
      // code that uses the earlier variable declarations
      result = 'Failed: ${result.asError.error}';
    } else {
      // code that uses the earlier variable declarations in a different way
      result = 'Got ${result.asValue.value}!';
    }
    // lots of code that uses the earlier variable declarations and result...
  });
```

2. An API which returns `void` instead of `Future` to make it easier to use `unawaited_future` lint. I think, in general, we want to avoid mixing `async`/`await` code with `.then`/`.whenComplete` code.

Here is your example using `Result` and `await`:

```dart

Future<int> _fetchDataFromNetwork() => fetchValueFromNetwork().then(convertValueToData);

...   
  var result = await Result.capture(_fetchDataFromNetwork());
  // lots of code, variable declarations, etc...
  String result;
  if (result.isError) {
    // code that uses the earlier variable declarations
    result = 'Failed: ${result.asError.error}';
  } else {
    // code that uses the earlier variable declarations in a different way
    result = 'Got ${result.asValue.value}!';
  }
  // lots of code that uses the earlier variable declarations and result...
```

or:

```dart
  int value;
  dynamic error;
  StackTrace stackTrace;
  try {
    var foo = await fetchValueFromNetwork();
    value = await convertValueToData(foo);
   } catche(e, st) {
     error = e;
     stackTrace = st;
   }
  // lots of code, variable declarations, etc...
  String result;
  if (error != null) {
    // code that uses the earlier variable declarations
    result = 'Failed: ${result.asError.error}';
  } else {
    // code that uses the earlier variable declarations in a different way
    result = 'Got ${result.asValue.value}!';
  }
  // lots of code that uses the earlier variable declarations and result...
```

**Comment by Hixie** [comment]
`package:async` doesn't solve the problem, it works around the problem. Sure, we can work around the problem (and do, as noted earlier in this bug); the request here is to solve the problem.

> in general, we want to avoid mixing async/await code with .then/.whenComplete code

There's plenty of times you want to mix them, for example if you want to run multiple tasks in parallel but want the bulk of the code to be readable.

**Comment by hacker1024** [comment]
I have some code that looks like this:

```dart
class QueueItem<T> {
  final Completer completer;
  final Future<T> Function() buildFuture;

  ...
}

...

final _queue = Queue<QueueItem<T>>();

...

while (_queue.isNotEmpty) {
  final item = _queue.removeFirst();
  final future = item.buildFuture();
  item.completer.complete(future);
  await future;
}
```

I iterate through a queue, creating and forwarding futures to the completers in the items. I also need to wait for each future to complete before continuing to the next item. At the moment, there's no clean way to avoid leaking errors here: Errors get forwarded through the completer, but are also unhandled in the `await` statement.

I'm also using null safety, so `whenComplete` isn't an option as returning null throws another error.

The only possible way to ignore errors in the `await` seems to be the following:

```dart
try {
  await future;
catch (_) {}
```

This doesn't make it very clear that the error is being handled elsewhere.

Especially due to the problem with `whenComplete` and null safety, perhaps this issue can be reconsidered?

**Comment by lrhn** [comment]
There is no simple way to ignore errors of a future. You can obviously do `.catchError((_)=>null);`, but only if future has a nullable type.
Using `whenComplete` is not an option because it doesn't actually stop errors. All it can do is throw more/other errors as well. It shouldn't be a problem to return `null` from the `whenComplete` handler because the return value is ignored completely.

I think what you want is something like:
```dart
extension IgnoreFuture on Future<Object?> {
  static void _ignore(void _) => null;
  Future<void> get whenDone =>
      this.then<void>(_ignore, onError: _ignore);
  void ignore() {
    this.whenDone;
  }
}
```
Then you can write: `await future.whenDone;` and get a `void` when the future completes in one way or another, but with all errors ignored. (Or just `future.ignore();` when you don't even want to wait for it, and don't care when or if it completes).

The `whenDone` also swallows any error, which is usually a *bad* thing. You should be sure that is what you want.
In the example here, the error is propagated and handled elsewhere, because the future is awaited twice.

Any time a future is awaited more than once, you're in "clever code" territory. There is no way to make it clear at one place that the same future is also used somewhere else.
(I guess we could potentially add an `ignore`/`whenDone` which would ignore the error, but also not consider the error *handled*, so you'd still get an error if someone else doesn't handle the error. I don't think the complexity is worth it, though.)

**Comment by hacker1024** [comment]
@lrhn

> In the example here, the error is propagated and handled elsewhere, because the future is awaited twice.

That doesn't seem to be happening. Instead, even if I use `catchError` on the completer's future, it's still thrown as an unhandled error when I await it.

> ```dart
> extension IgnoreFuture on Future<Object?> {
>  static void _ignore(void _) => null;
>  Future<void> get whenDone =>
>      this.then<void>(_ignore, onError: _ignore);
>  void ignore() {
>    this.whenDone;
>  }
>}
>```

Thanks for the suggestion. I think I'll just stick with my existing method anyway now as it seems much simpler.

**Comment by lrhn** [comment]
There is now `.ignore()` on futures.
