### ISSUE TITLE
Can't both mixin and extend a class with a factory default constructor

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29395]
Consider this code:
```dart
class Superclass {
  const Superclass(this.foo);
  final int foo;
}

abstract class Mixin {
  factory Mixin(int baz) = _FixedMixin;
  int get baz;
  int get baz2 => baz * 2;
}

class _FixedMixin extends Mixin {
  _FixedMixin(this.baz);
  @override
  final int baz;
}

class Subclass extends Superclass with Mixin {
  Subclass(int foo, this.bar) : super(foo);
  final int bar;
  @override
  int get baz => foo + bar;
}

void main() {
  new Subclass(1, 2);
  new Mixin(3);
}
```

It won't compile because `illegal implicit call to factory 'Mixin()' in super class` in the constructor of `_FixedMixin`.

But if I add a named constructor in `Mixin` so I can defer to it in `_FixedMixin`, instead `Subclass` gets unhappy because `mixin class 'Mixin' must not have constructors`.

**Comment by eernstg** [comment]
The problem here is that the superinitializer clause in a generative constructor (which may be explicit like `super(foo)` in `Subclass` or implicitly generated as `super()` like in `_FixedMixin`) must invoke a generative constructor, and in this case it attempts to invoke a factory constructor.

The chain of superinvocations in a generative constructor invocation is tailored exactly for well-defined instance creation and initialization, and a factory constructor invocation is pretty much the same thing as a static method invocation (just differing in the ability and requirement to use `new` in invocations), and that's not semantically compatible with the job that a generative constructor must perform. (A generative constructor initializes instance variables in a TargetClass-to-Object sweep and runs constructor body code in an Object-to-TargetClass sweep, and generative constructors do not return anything, they just work on the initialization of `this` object; that's very different from a static method invocation that returns an object).

So we're not going to get support for invoking a factory in a superinitializer.

As you mention, adding a named constructor in `Mixin` and using that in the superinitializer for `_FixedMixin` won't work, because `Mixin` is then not usable as a mixin. That restriction (a mixin cannot have a non-factory constructor) is a lot easier to lift, at least in some cases (but not trivial, and we don't have a working design for doing it at this point, although we do have some ideas that seem promising). But, unfortunately, you're not going to get that feature in the near future.

So let's consider the main point of your example (I suppose): You want to be able to say `new Mixin(3)` in main, that is, you want to "create instances of the Mixin class" in a way that looks exactly like creation of instances of other classes, except that we'll really get an instance of `_FixedMixin`.

You could just use a static method as a factory (common concept) rather than using an actual `factory` constructor:

```dart
abstract class Mixin {
  static Mixin create(int baz) => new _FixedMixin(baz);
  int get baz;
  int get baz2 => baz * 2;
}
...
void main() {
  new Subclass(1, 2);
  Mixin.create(3);
}
```
I guess this is undesirable because you want clients' code to use `new Mixin(3)`, such that we can "believe" that `Mixin`s can be created directly, just like `Subclass`.

I guess the best workaround at this point would be to have a naming convention whereby the name of a mixin reflects the fact that it is a mixin, and an associated class which is intended for instance creation would have a name which can easily be predicted as soon as you know about this convention:

```dart
class Superclass {
  const Superclass(this.foo);
  final int foo;
}

// Assume `Foo` is a meaningful name for the role played by this class,
// then name it `FooMixin` to show that it is a mixin.
abstract class FooMixin {
  int get baz;
  int get baz2 => baz * 2;
}

// This is a helper class that just exists to "finalize" a `FooMixin` such that
// we can create instances directly.
class Foo extends FooMixin {
  Foo(this.baz);
  @override
  final int baz;
}

class Subclass extends Superclass with FooMixin {
  Subclass(int foo, this.bar) : super(foo);
  final int bar;
  @override
  int get baz => foo + bar;
}

void main() {
  new Subclass(1, 2);
  new Foo(3);
}
```
Don't you think that would actually work for you and for the developers who are using your classes?

**Comment by Hixie** [comment]
There are certainly workarounds (in this particular case I just required that users use the subclass constructor directly instead). But they are workarounds and less satisfying than it would be if this limitation didn't exist.

Would just ignoring factory constructors for the purposes of mixins and so forth help at all?

**Comment by eernstg** [comment]
> I just required that users use the subclass constructor directly

That's actually very nearly what I proposed, except that I suggested that the names could be chosen such that this would be a rather natural thing (to use a "foo mixin" you'd use `with FooMixin`, and to obtain a new "instance of foo" you'd use `new Foo(..)`). That might be seen as a reasonable naming scheme rather than an irritating work-around ;-), and it does help readers of the code to see that `FooMixin` is a class which is mainly intended to derive mixins from.

> Would just ignoring factory constructors for the purposes of mixins and so forth help at all?

When I looked at the example I saw conflicts between constructors with the same name: you wanted to use `factory Mixin()` such that clients could do `new Mixin()` and get a `_FixedMixin`, but when `Mixin()` is a factory constructor we can't have the implicitly specified default constructor (`Mixin() : super() {}`) because of the name clash, so it wouldn't help us even if we were to ignore that factory constructor (for any purpose, including mixins). Apart from that, we can already use factory constructors in mixins:
```LaTeX
It is a compile-time error if a declared or derived mixin explicitly declares a
constructor which is not a factory constructor.
```

I think there's another little trick that might be more helpful:
```dart
class Superclass {
  const Superclass(this.foo);
  final int foo;
}

abstract class Mixin {
  factory Mixin(int baz) = _FixedMixin;
  int get baz;
  int get baz2 => baz * 2;
}

class _FixedMixin extends Object with Mixin {
  _FixedMixin(this.baz);
  @override
  final int baz;
}

class Subclass extends Superclass with Mixin {
  Subclass(int foo, this.bar) : super(foo);
  final int bar;
  @override
  int get baz => foo + bar;
}

void main() {
  new Subclass(1, 2);
  new Mixin(3);
}
```
The idea is that we do _not_ `extend Mixin` anywhere, even `_FixedMixin` applies it in a mixin application. That's kind of fair, because `Mixin` was written in order to be mixed in anyway.

**Comment by lrhn** [comment]
Mixin application does ignore factory constructors. Whether the mixin has a factory constructor or not does not affect mixin application.

The problem comes from mixin classes not *really* being usable as normal classes. There are too many interlocking constraints. Most prominently, you can only extend something with a generative constructor and mixins cannot have generative constructors - except the default one you get if you don't write any constructors (including factory constructors). So, either use it as a mixin, or use it as a superclass, but only do both if you can get by with only the default constructor and no factory constructors.

Mixins are restricted, and in some cases more restricted than convenient, but it's also not trivial to remove the restrictions.

**Comment by eernstg** [comment]
> Mixin application does ignore factory constructors

In this case the factory constructor actually does make a difference, because the existence of _any_ constructor (including `factory Mixin(..)`) prevents `Mixin() : super() {}` from being  implicitly specified. In this particular case we couldn't ignore the factory constructor because it would be a name clash to go ahead and implicitly declare `Mixin() : super() {}`, but it won't help to give the factory constructor a different name as long as every explicitly declared constructor will prevent that implicitly declared one.

And this matters for mixin application, because we can't even write a benign constructor --- like `Mixin._() : super();`, as a stand-in for the implicitly declared one, though avoiding the name clash with the factory constructor --- because then `Mixin` can't be mixed in.

That's the reason why I mentioned the possibility to use the static method `static Mixin create(int baz) ..` in [this comment](https://github.com/dart-lang/sdk/issues/29395#issuecomment-296151106), as an alternative to the `factory Mixin..` constructor.

I certainly agree that there are too many interlocking constraints, in particular when they are not necessary, but I also recognize that the complexity will blow up if we do a lot of work on allowing all the benign corner cases..

**Comment by lrhn** [comment]
A `mixin class` can now have factory constructors and trivial generative constructors.
(A plain `mixin` still can't have factory constructors, which is an unnecessary restriction, but that's another issue.).
