### ISSUE TITLE
Dart2js Crash in mixin-test

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29441]
FAILED: dart2js-d8-checked release_ia32 language/mixin_type_parameter6_test
Expected: Pass 
Actual: Crash
Unexpected compile-time error.

See: https://build.chromium.org/p/client.dart/builders/dart2js-linux-d8-hostchecked-4-5-be/builds/2910/steps/dart2js%20d8%20checked%20tests/logs/stdio

**Comment by rakudrama** [comment]
I did a little digging.

The crash is late (in emitter's ProgramBuilder).
MappedListIterable is in the set of needed-for-rti classes even though it is not instantiated.
The crash is an assertion that the superclass is also in the set.
This seems to be a mistake in adding MappedListIterable.

**Comment by sigmundch** [comment]
Johnni - tentatively sending this your way since I believe you are most likely to know where the issue lies.

It seems like this case only shows up on little programs like this test, since the MappedListIterable gets included easily by larger programs.

This issue showed up as I was cleaning up the dart2js patches to match the generic arguments used in the unpatched dart:core (https://github.com/dart-lang/sdk/commit/5dc841c1ca8e8b7add60865658274d5ad2a762af)

Here is a tiny repo:
```dart
main() {
  <String>[].map(null);
}
```

Then run:
```
sdk/bin/dart2js_developer --checked repro.dart
```
