### ISSUE TITLE
Stream.where() & firstWhere() should support FutureOr<bool> callbacks

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#29457]
The following should be legal:

```
abstract class Foo {
  Future<bool> get isValid;
}

Future<Foo> firstValidFoo(Stream<Foo> stream) =>
    stream.firstWhere(
      (Foo foo) => foo.isValid,
      defaultValue: () => null,
    );
```

However, it's not legal because the `test` argument of `Stream.firstWhere()` is `bool test(T element)`.  We should allow it to be `FutureOr<bool> test(T element)`.

**Comment by lrhn** [comment]
A `firstWhere` where the test may be asynchronous is a very different function. There are decisions you need to make: Should the stream be paused while waiting for the test result? If not, should you pick the first value in the stream whose test completes to true. Or should you pick the value whose test first completes to true? Sure, it's easy to make *a* choice, but I'll bet that eventually someone will want each of the possible versions for something.
Keeping the test synchronous means that it's simple, there is only one possible version.

*Every* time you have a synchronous function parameter, someone might want to use it with an asynchronous function instead. The only solution that handles all problems is to make *all* callback functions (potentially) asynchronous, and by extension, every function that takes a callback function should also be asynchronous (which isn't a problem in this case, which is why the request has some merit). 
Still, it gets ridiculous quickly, so we have to draw a line somewhere.

So, while I'm sympathetic to the problem, it's really just another case of asynchrony being contagious (see http://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/ for a beautiful write-up). 
We don't want to add potential asynchrony every place it can potentially apply. 

For this case, you can use one of the generic asynchronous transformations, e.g.:
```dart
// Not handling the case where there is no valid one.
Future<Foo> firstValidFoo(Stream<Foo> stream) =>
   stream.asyncExpand((Foo foo) async* { if (await foo.isValid) yield foo; })
          .firstWhere((_) => true, defaultValue: () => null);
```
or 
```dart
Future<Foo> firstValidFoo(Stream<Foo> stream) => 
    stream.asyncMap((Foo foo) async => (await foo.isValid) ? foo : null)
          .firstWhere((foo) => foo != null);
```
(the `asyncExpand`, like `expand` is *very* generic, it corresponds to `flatMap` and can implement both `where` and `map` in a single operation, so if you are missing some functionality, you can usually write it with a single expand operation).
