### ISSUE TITLE
VM doesn't accept literal function type as type bound.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#29481]
Example:
```dart
class C<T extends num Function(num)> {
//class C<T extends numfun> {
  final T func;
  C(this.func);
}
main() {
  var c = new C<int Function(int)>((int x)=>x*2);
  print(c.func(21));
}
typedef num numfun(num x);
```
This fails to compile. If switching to the commented out line instead, it will work, so the problem is with recognizing the new function type syntax in the type parameter bound, not function types in general.

**Comment by a-siva** [comment]
Is this legal syntax? dart2js, dartanalyzer and dartdevc also seem to fail on this test.

**Comment by lrhn** [comment]
Yes, it's valid syntax. The grammar in the informal specification still uses the `type` production for the bound, and that production allows an immediate function type.

There is a constraint that the bound must not be a *generic* function type (one that takes a type parameter), but that's not a syntactic constraint, and it doesn't apply to this example.

**Comment by crelier** [comment]
@lrhn Can you please point to the document stating the constraint about the bound not being a generic function, so I can pick the correct wording in the error message? Also, is there a regression test submitted for this issue? Thanks.

**Comment by eernstg** [comment]
The constraint about generic function types is discussed already in [Leaf's DEP](https://github.com/leafpetersen/dep-generic-methods/blob/master/proposal.md). The constraint has not been mentioned in recent documents, due to a communication glitch. I have updated the informal specification of the [Generic Function type Alias feature](https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa) to include the constraint, at the end of the section on static analysis.

**Comment by crelier** [comment]
Thanks for the pointers!

**Comment by natebosch** [comment]
Analyzer and CFE seem to accept this syntax now.  Analyzer produces the error `'(int) → int' doesn't extend '(num) → num'` and that error is missing from CFE, but since this issue is filed about syntax I think it's resolved.
