### ISSUE TITLE
Static errors in analysis_server after cloning

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/sdk#29517]
Mostly, they come from a dependency not being specified or pointing to a version that does not yet have the specified functionality/modifications. I am not sure what the "protocol" is to handle such things.

I'll submit a PR just to show what error fixed I did.

**Comment by bwilkerson** [comment]
When you cloned the SDK, did you then run `pub` in `pkg/analysis_server`? Because if you did that would explain the issue you're seeing. The correct way to fix the problem is to remove the `.packages` file that was created. There is a hard-coded `.packages` file in the root of the SDK repository, and that's the file that should be used for all development of packages within the SDK repo. 

Note that you'll also need to run the following two commands
```
gclient sync
gclient runhooks
```
in order to get everything configured correctly for development.

We should probably remove the `pubspec.yaml` file from the analysis server package. It's wrong, as you discovered, and unnecessary because we don't currently have any plans to publish the analysis server package as a separate package.

**Comment by daniel-v** [comment]
Yes, I did run pub.

No, I have not run the mentioned commands. I was following https://github.com/dart-lang/sdk/wiki/Building

Might I be missing a link to a "how to get started with core SDK package development" page?

**Comment by bwilkerson** [comment]
That page should have what you need. If you haven't already, "Install Chromium's depot tools" as per your platform (that's where `gclient` is defined). The "Getting the source" section mentions running `gclient sync` (which probably runs `runhooks` for you, although I once thought it didn't and might still be laboring under that delusion :-).

**Comment by daniel-v** [comment]
Thanks for speedy replies. I guess the related PR and this issue can be closed as my "fix" assumptions' were based on the wrong yet crucial pieces of information.

Can it be stated in general, the `pkg` folder contents are not packages per se? Or is `pkg/analysis_server` a special in that regard? 

Should I want to build on top of dev version of `analysis_server`, how can I include it in my project? Is `.packages` file sufficient for pub to recognize a path as a package?

**Comment by bwilkerson** [comment]
> I guess the related PR and this issue can be closed ...

The PR can. The issue can stay open until you don't have any more questions.

> Can it be stated in general, the pkg folder contents are not packages per se?

No, some (most?) of the packages in that directory are published to `pub.dartlang.org`, but not all of them are. The `analyzer` package, for example, is published.

> Should I want to build on top of dev version of `analysis_server`, how can I include it in my project?

I would be interested to know why you are interested in building on top of the analysis_server package. As I said before, we aren't currently planning on publishing it as a package, but I'd be interested to know whether you've found a use case that should make us reconsider. The analysis server *does* provide a public API for other tooling to use, but that API is the wire protocol, and using it doesn't require the package to be depended on (in the `pub` sense).

Unless we publish the analysis_server package, any package you create that has a dependency on it would need to use a dependency override, and that would prevent you from publishing your package.

> Is `.packages` file sufficient for pub to recognize a path as a package?

As far as I know, pub requires a pubspec.yaml file in order to determine the packages dependended on by a package. It won't look at a `.packages` file. So the presence of a `.packages` file won't cause pub to treat a directory as a package. (So, yes, I think that if we removed the `pubspec.yaml` file from the `analysis_server` directory it would prevent any other packages from depending on the analysis server package.

**Comment by daniel-v** [comment]
I went ahead and close the PR.

I enjoy your willingness to answer related questions. This is really good form.

> I'd be interested to know whether you've found a use case that should make us reconsider

I am lookin at [dart-lang/angular_analyzer_plugin](/dart-lang/angular_analyzer_plugin) . It depends on it. Other than that, I can't - at this point - offer other use cases. The promise of that plugin is more than enough for me to go through these hoops.

> We should probably remove the pubspec.yaml file from the analysis server package.

> if we removed the pubspec.yaml file from the analysis_server directory it would prevent any other packages from depending on the analysis server package

How would one go about working on something like angular_analysis_plugin should this removal happen?

**Comment by MichaelRFairhurst** [comment]
Mostly we currently depend on it for temporary reasons.

However, it did occur to me that we will depend on it even after the new plugin architecture. Because we call the dart CompletionContributors on dart snippets within HTML. Maybe that code should be moved to its own package?

**Comment by bwilkerson** [comment]
To expand a bit on @MichaelRFairhurst's response: The plan is to provide first-class support for writing plugins to the analysis server. That support will require plugins to depend on the (not yet ready for use) analyzer_plugin package, which we will be publishing as soon as it's ready for beta testers. The portions of the analysis_server package that the angular plugin (and others) depend on will be moved into the analyzer_plugin package so that plugins can access it.

So, the current situation is an unfortunate, but temporary, mess. I can't make any promises, but we hope to have the angular plugin ported to the new framework by the end of the quarter, unless other factors force it to be delayed.
