### ISSUE TITLE
Periods in queryParameter names

### ISSUE THREAD

**Issue by jkriesel** [dart-lang/sdk#29520]
Because period is valid in HTML field names this can create a problem when trying to interface to get requests that could contain a field a name like "hub.challenge".  PHP converts that period to an "_" to allow for normal field operations.  

I propose Dart leverage the same convention. I've encountered a problem with RPC where I cannot retrieve a field value from a query parameter because a dart variable cannot be "hub.challenge".

**Comment by lrhn** [comment]
What are you using to convert a query parameter name to a Dart variable? Is this Angular or something similar?

**Comment by jkriesel** [comment]
The classes in dart rpc.  However, doesn't this need to be standard approach for dart lang?

**Comment by lrhn** [comment]
The language isn't deciding how to interpret URLs,  and the URI class does not enforce an interpretation of the names. Matching a string to a parameter name isn't something Dart supports in general (symbols, yes, but not strings). So, if you have a string and want to match against a parameter name, you need pick a strategy for those strings that can't directly be converted to an identifier symbol.

It seems `package:rpc` should handle this case better. I've filed https://github.com/dart-lang/rpc/issues/109, feel free to add more context there (I've never used `package:rpc` myself, so my description might not be very usable).

**Comment by kasperl** [comment]
Did you intend to close this one, @lrhn?

**Comment by jkriesel** [comment]
Understood that the RPC library is deciding, but shouldn't the approach be a standard just like it is in PHP similar to Dart's standard naming convetions?

**Comment by lrhn** [comment]
Dart is not generally making a connection between a string and a variable name. PHP allows direct usage of a string as a variable (like `"${$a}"` being equivalent to `"$foo"` if the `a` variable holds the string `"foo"`). It allows you to go directly from a string to a variable, so the language has to concern itself with that - string/variable conversion is embedded deeply into the language itself.

In Dart, you can't reify a string as a variable name. Even with mirrors, there is a distinction between strings and variable names (`Symbol`s), and you have to actively map between the two. So, the *Dart language* doesn't have a strategy for interpreting a string as a variable name. You can do `new Symbol(string)`, but symbols are used for things other than variable names too, so it's your job to ensure that the string actually corresponds to a variable name. We could add a convenience methods `Symbol.variable` that converts any string to a valid variable name, but ... there really hasn't been a need for it. There is no unified approach to doing such a conversion, because it's simply not something you are expected to do at all.

Now, some frameworks want to do it anyway, using reflection and string/symbol mappings. That's their prerogative, trading convenience for reflective overhead and lack of static checking (but then, I might be biased :smile:). They are still the ones who need to ensure that the string they pass to the `Symbol` constructor is a variable name, if they want to use it as a variable name. Here, the RPC package fails to do that.

**Comment by tschnoelzer** [comment]
> Because period is valid in HTML field names this can create a problem when trying to interface to get requests that could contain a field a name like "hub.challenge". PHP converts that period to an "_" to allow for normal field operations.
> 
> I propose Dart leverage the same convention. I've encountered a problem with RPC where I cannot retrieve a field value from a query parameter because a dart variable cannot be "hub.challenge".

Hi @jkriesel ,

did u find a solution? I am facing same problem for webhook verifying using RPC 

`@ApiMethod(path: 'webhook')
  CmbResponse webhook({String hub.mode, String hub.challenge, String hub.verify_token}) {
`
