### ISSUE TITLE
Strange value returned by Window.getMatchedCssRules()

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#29538]
Compile the code below to JavaScript and run it in a browser
```dart
import "dart:html";

main () {
   var x = window.getMatchedCssRules(document.body, "before");
   print(x); // prints null
   print(x == null); // prints false!!!
   x.z; // Uncaught TypeError: Cannot read property 'get$z' of null
}
```
How can it be? Tested on Dart-to-JavaScript compiler (dart2js) version: 1.24.0-dev.2.0, Chrome 58

**Comment by sigmundch** [comment]
Thanks for filing the bug.

The issue here appears to be a bug in some annotations in the `dart:html` library. We use annotations to specify the native behavior of DOM APIs, one of those annotations indicates what we expect the return value of this function to be. I don't believe "Null" was included as a possible result, so dart2js believes `window.getMatchedCssRules` cannot return a null value and optimizes the `print(x == null)` into `print(false)`. I'll send a fix shortly.

**Comment by sigmundch** [comment]
actually, I'm not as familiar as I thought on how to properly fix this @alan-knight @rakudrama - there is no .template containing this definition, so I'm guessing this is generated directly from the IDL, do you know how to add the extra annotation we need?

**Comment by rakudrama** [comment]
Fix available https://codereview.chromium.org/2857143003/
