### ISSUE TITLE
No break on exception when it is in try / finally

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#29550]
When there's an unhandled exception in code, and that code is wrapped in try / finally, VM will not break on the exception and will crash instead.

Repro:

```
main() {
  try {
    var a = [1];
    var b = a[1];
  } finally {
    print("Done");
  }
}
```

Note that this is the case even when the try / catch block is several frames removed from the exception, and even if there are async gaps between them. This means that working on larger codebases, developer will often encounter places where breaks on exception don't work (because there is often some try / finally somewhere up the call stack).

In contrast, the code below will correctly break on exception in debug mode: 

```
main() {
  var a = [1];
  var b = a[1];
}
```

Workaround:

```
main() {
  try {
    try {
      var a = [1];
      var b = a[1];
    } catch (e) {
      print(e); // Add breakpoint here.
      rethrow;
    }
  } finally {
    print("Done");
  }
}
```

I'm not sure if the "doesn't break on exception if there's any `finally` block up the callstack" behavior is intended behavior. If so, then this at the very least breaks my expectations. If not, this seems like a bug.

Adding [repro_break_on_unhandled.zip](https://github.com/dart-lang/sdk/files/975115/repro_break_on_unhandled.zip) for faster repro.

**Comment by filiph** [comment]
Oh, I should probably add this is tested in IntelliJ WebStorm 2017.1, Dart v1.23.0. But I think I've seen this in Observatory as well, and in previous versions of Dart.

**Comment by a-siva** [comment]
I believe because there is a finally block there the exception is not considered unhandled and hence the breakpoint is not hit. You state that it breaks your expectations. Do you think we should better document what we consider 'unhandled exceptions' in the tools?

**Comment by filiph** [comment]
Thanks for the explanation!

My expectation was that `finally` won't make the exception handled, only `on` or `catch` will. So clarifying this in documentation would help.

The larger problem is that it's really hard to debug anything that is wrapped in a try-finally block (which is almost all code once we're working with a closeable sink or client). In Java + IntelliJ IDEA, you can set "Java Exception Breakpoints". They are not ideal (you hit several breakpoints in std lib every time you run anything), but they let you debug exceptions anywhere.

![screen shot 2017-05-30 at 11 33 05](https://cloud.githubusercontent.com/assets/919717/26599008/e6fa24be-452b-11e7-9c81-fa6e9bb5f77d.png)

![screen shot 2017-05-30 at 11 38 11](https://cloud.githubusercontent.com/assets/919717/26599160/7ed331b8-452c-11e7-9fca-e8520b8532a6.png)

Is this just a tooling issue, then? If we ask IntelliJ to add "Dart Exception Breakpoints", will they have the API there to use?

**Comment by filiph** [comment]
To come back to the handled/unhandled point, it seems like Java only marks an exception as handled if it's in the `catch` statement. In other words, in Java, `finally` does not make an exception handled. 

```
package com.company;

public class Main {

  public static void main(String[] args) {  // <-- no 'throws' required here
    try {
      System.out.print("hi\n");
      throw new Exception();
    } catch (Exception e) {
      System.out.print("handled\n");
    } finally {
      System.out.print("finally\n");
    }
  }
}
```

Remove the catch block and Java forces a `throws` clause on the `main` function.

I'm not saying we want to copy Java but it's definitely a source of expectations.

**Comment by DanTup** [comment]
I just came across this while looking to see if we had an issue open for https://github.com/Dart-Code/Dart-Code/issues/1597. I don't think it's the same, but I thought it worth commenting here...

I think the behaviour described above is definitely bizarre. If the exception is not unhandled, then it wouldn't make sense for the VM to crash. My understanding of the "break on unhandled exceptions" functionality is that it will break the debugger on any code that would crash (eg. the exception gets all the way up the stack without being caught) so that it can be debugged. Here we have code that will crash, but we don't break on it. It feels totally wrong this way - there's no way to break on all exceptions that would crash, but we can break on "some subset of them".

C# and JavaScript both behave as Java is described above. Here's Chrome breaking on an exception inside a `try` with a `finally` with break-on-exceptions but not break-on-handled-exceptions enabled:

![Screenshot 2019-05-09 at 11 31 07 am](https://user-images.githubusercontent.com/1078012/57447041-02b5df80-724e-11e9-956b-92f06dbfae91.png)

**Comment by DanTup** [comment]
@ZichangG I wondered if the fix for #36907 would also handle this. It seems like it *does* now result in the debugger breaking, but with an incorrect position:

<img width="439" alt="Screenshot 2019-05-21 at 12 20 40 pm" src="https://user-images.githubusercontent.com/1078012/58091976-e0fc1700-7bc2-11e9-86a9-cb5f056d8f28.png">

In v2.3 it doesn't pause at all. The screenshot above is from the latest nightly.

**Comment by ZichangG** [comment]
This behavior is expected if stacktrace is supposed to show where the debugger actually is pausing. 
There is an exception on `var b = a[1]` and be thrown as a handled exception. Then it prints "Done" and rethrow the exception as unhandled. Debugger will pause on this exception and collect the stacktrace. Since this implicit rethrow does not have a token position, the line number is -1. 
I think it might be better to remove the highlight on main() since the line number is not valid.

**Comment by DanTup** [comment]
@ZichangG I can't remove the highlight, this is what VS Code does when we give it an invalid location (if just goes to the start of the file).

I'm not sure I understand why we don't have the right location of stack trace here though - the one printed to the console *does* show line 4 (see the right side):

<img width="707" alt="Screenshot 2019-05-22 at 8 41 25 am" src="https://user-images.githubusercontent.com/1078012/58156195-781da900-7c6d-11e9-8607-dcfb1e404d6e.png">

Can't this stack trace be provided when we pause here?

**Comment by ZichangG** [comment]
The difference is the window on the left side of VScode shows where program currently pauses(The first picture you posted). But in debug console, it prints the stacktrace where the exception is generated(Second picture). 
The exception is generated at line 4 as a handled exception and stores the stacktrace(was printed in debug console). Then the exception is implicitly caught and rethrow as a unhandled exception. This time debugger will pause on exception but does not have a valid token position since rethrow is synthetic.

**Comment by DanTup** [comment]
Ah, got it. In that case I think the display in VS Code is unavoidable (but not a big deal).

Probably this is issue is resolved then?

**Comment by ZichangG** [comment]
Yep. I'll close this issue :)
