### ISSUE TITLE
Can a function type alias have a type variable with the same name as itself?

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29555]
Is this legal:

```
typedef F<F>(F f);
```

I can't even find a specification of what it means to have type parameters on a function type alias.

The specification says:

>The effect of a type alias of the form  <code>typedef _T_ _id (T<sub>1</sub>_ _p<sub>1</sub>, ..., T<sub>n</sub>_ _p<sub>n</sub>, [T<sub>n+1</sub>_ _p<sub>n+1</sub>, ..., T<sub>n+k</sub>_ _p<sub>n+k</sub>])_</code> declared in a library _L_ is is to introduce the name _id_ into the scope of _L_, bound to the function type _(T<sub>1</sub>, ..., T<sub>n</sub>, [T<sub>n+1</sub>_ _p<sub>n+1</sub>, ..., T<sub>n+k</sub>_ _p<sub>n+k</sub>])  -> T_.
>The effect of a type alias of the form <code>typedef _T_ _id (T<sub>1</sub>_ _p<sub>1</sub>, ..., T<sub>n</sub>_ _p<sub>n</sub>, {T<sub>n+1</sub>_ _p<sub>n+1</sub>, ..., >T<sub>n+k</sub>_ _p<sub>n+k</sub>})_</code> declared in a library _L_ is is to introduce the name _id_ into the scope of _L_, bound to the function type _(T<sub>1</sub>, ..., T<sub>n</sub>, {T<sub>n+1</sub>_ _p<sub>n+1</sub>, ..., T<sub>n+k</sub>_ _p<sub>n+k</sub>})  -> T_. . In either case, iff no return type is specified, it is taken to be `dynamic`.
Likewise, if a type annotation is omitted on a formal parameter, it is taken to be `dynamic`.

Notice the absence of type parameters from the above text.

**Comment by lrhn** [comment]
Immediate thought: Sure, no problem. 
The type parameter is a "local" variable scoped inside the typedef, the typedef's own name is declared in the scope outside it, so the local variable should shadow the outer one, and everything is honky dory.

As the opposing view, we don't allow type parameter of a class to have the same name as the class, or as any member. The members make sense, they can be seen to be at the same scope level as the type variables (whether they actually are or not, it's easier to not confuse anything), and having the same name as the class would probably preclude writing constructors, so it's better to disallow it.
We could say that a type parameter having the same name as the typedef itself is confusing, and should be disallowed, but we haven't done so yet, and there is no *technical* reason to do it.

All in all, I'd allow it, unless someone comes up with a good reason against.

**Comment by bwilkerson** [comment]
It seems inconsistent to me to allow it for typedefs but not for classes. My belief is that inconsistencies like this make it harder for people to understand a language, so I would disallow it, if it were up to me.

@lukechurch What do you think the impact on usability would be?

**Comment by lrhn** [comment]
The consistency I'm looking at is that nothing inside a class can have the same name, including constructors, which is the reason the class's own name is prohibited for members and type parameters.
It's not that there is a problem with the type parameter conflicting with the class, it's the conflict with the constructor that is the reason. That problem isn't there for the typedef (no internal declarations to conflict with).
We allow names to shadow, even closely declared ones, unless there is a reason not to. Every rule we add is an exception (unless it's covered by the "no conflict in a single scope" rule).

If we had used `new(x)` or `new.foo(x)` for constructors instead of `ClassName(x)` and `ClassName.foo(x)`, there wouldn't be a technical need to disallow the class name as a member name or type parameter name. It might be confusing, but lots of things can, and we have style guides to fix most of those, not language requirements.

**Comment by leafpetersen** [comment]
My inclination would be to say that unlike classes where the class name is in scope in the body (and hence forbidding the shadowing is helpful), the typedef name is not in scope in the body and hence there is no reason to forbid it.

**Comment by lrhn** [comment]
Technically, the name of the typedef *is* in scope inside itself, it's just not *allowed* to refer to itself (directly or indirectly, to avoid a structurally infinite type).
> Any self reference in a typedef, either directly, or recursively via another typedef, is a compile time error.
You couldn't *have* a direct self reference if it wasn't in scope.

Still, that's not a reason to prohibit nested uses of the name. We do allow functions to have variables, or even parameters, that have the same name as the function, they're just shadowing the outer declaration and there is nothing inherently wrong with that, if used with care (well, readability, but nothing *technically* wrong).

```dart
typedef Foo Foo<Foo>(Foo x);
foo<foo>(foo){var foo;print(foo);}
class C<T> {  C(C, T) { print("$C $T"); } }
main() {
 new C("Hello", "world!");
 foo<int>("param");
 Foo<int> f = (int x) => x;
}
```
This runs today, in checked mode and analyzer strong mode, so we already allow the type parameter of a typedef to have the same name as the typedef. 
I see no reason to change that.

**Comment by eernstg** [comment]
No milestone now: The specification needs to be clarified as indicated, but this is independent of Dart 2.

**Comment by lrhn** [comment]
So, in short, it's legal.
We may want to consider making it not legal, bu we haven't yet.

**Comment by eernstg** [comment]
Resolving and closing: The current specification actually implies that, as mentioned by @leafpetersen,

> [The] typedef name is not in scope in the body

which means that there is no conflict. So the answer to the question raised by this issue ('Can a function type alias have a type variable with the same name as itself?') is 'yes', and references to the resulting type alias in parameterized types is well-defined.

Here's how this comes about:

First, note that specification of generic entities has (for a long time, maybe since they were added at all) been kept separately in section 'Generics', which is the reason why there is nothing about type arguments in section 'Type Aliases':

@peter-ahe-google wrote:
> The specification says: [...] Notice the absence of type parameters

But generic type aliases have always been covered in section 'Generics'. The text in 'Generics' about type aliases was rather economic on details, but it was made considerably more explicit and precise in 02bb4379a2d82fd4fe310bc200929047c3da4782.

So here's the status today:

Generic type aliases are specified [here](https://github.com/dart-lang/sdk/blob/b0017d758c6bb958c01c0bbe569143c44b819070/docs/language/dartLangSpec.tex#L4499).

The associated type for a given type alias is defined [here](https://github.com/dart-lang/sdk/blob/b0017d758c6bb958c01c0bbe569143c44b819070/docs/language/dartLangSpec.tex#L4518); note that it does not refer to the name of the type alias, it simply extracts the relevant type from an old-style declaration by replacing the name by `Function`, and for a new-style type alias it simply takes the type which is specified to the right of `=`.

The meaning of a parameterized type (`F<T1, .. Tk>` where `F` denotes a type alias) is specified as the result of substituting actual arguments (`Tj`) for formal parameters (`Xj`) in the associated type.

For instance, with `typedef F<F>(F f)`, the associated type is `dynamic Function(F)`, and the application `F<int>` denotes the type `[int/F]dynamic Function(F)`, that is, `dynamic Function(int)`.

This means that it never makes any difference that the type alias itself also has the name `F`, because the specification of the meaning of the type alias never refers to the name.

So the situation today is that we have an explicit and well-defined treatment of this kind of apparent name clash, and there is nothing special about it (there is no clash).

We rely on [capture-free substitution](https://github.com/dart-lang/sdk/blob/b0017d758c6bb958c01c0bbe569143c44b819070/docs/language/dartLangSpec.tex#L379) to ensure that any occurrence of a type variable in a generic function type will get the intended value (that is, the job otherwise done by scopes is done using capture-free substitution, but only for generic function types). For example, we will not change the parameter type `X` to `MyTypeArgument` in `[MyTypeArgument/X]void Function<X>(X)`, because the generic function type introduces its own type parameter `X` and this means that we don't replace `X` by anything else in that generic function type. So the result is `void Function<X>(X)` and not `void Function<X>(MyTypeArgument)`.

I noted, however, that this issue indirectly points the finger at the fact that the use of substitution for generic function types is different from the approach used for other parts of Dart: The type variables introduced by a generic function type are never entered into any scopes, and never looked up in any scopes. This works correctly, but it's different from the treatment of other names.

I created #35698 to resolve whether we should change the approach and introduce the notion of a type parameter scope for a generic function type.

**Comment by lrhn** [comment]
> \[The] typedef name is not in scope in the body

We might want to change this to say that it is in scope, but you are not allowed to refer to it.
The alternative is that you may refer to something else with the same name, which should have been shadowed by the declaration:
```dart
import "foo.dart" show Foo;
typedef Foo = Foo Function(Foo);
```
We don't want this to be allowed, the `Foo` in the typedef should refer to the nearest enclosing declaration, then the typedef should be rejected for being cyclic. We should not allow this and make the `Foo` in the function type refer to the imported type, that's just too confusing.

**Comment by eernstg** [comment]
> We might want to change this to say that it is in scope..

That is exactly the topic of #35698, so please comment on that issue as needed.
