### ISSUE TITLE
void semantics: double check that these co19 tests pass for the right reasons

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#29565]
Some co19 tests started passing after the CL landed with the new `void` semantics.

See:
https://build.chromium.org/p/client.dart/builders/dart2js-linux-drt-2-2-be/builds/3162/steps/dart2js%20drt%20co19%20fast-startup%20checked%20tests/logs/stdio

For example:
`tests/co19/src/WebPlatformTest/html/dom/elements/global-attributes/dataset-enumeration_t01.dart` has this code:
```dart
void main() {
      void testEnumeration(array) {
        var d = document.createElement("div");
        for (var i = 0; i < array.length; ++i) {
          d.setAttribute(array[i], "value");
        }
        return d.dataset.length;
      }

      test(() { assert_equals(testEnumeration(['data-foo', 'data-bar', 'data-baz']), 3); },
        "A dataset should be enumeratable.");
      test(() { assert_equals(testEnumeration(['data-foo', 'data-bar', 'dataFoo']), 2); },
        "Only attributes who qualify as dataset properties should be enumeratable in the dataset.");

      checkTestFailures();
}

**Comment by lrhn** [comment]
The test has a `void` function returning an `int` value. That used to be a checked-mode error and static warning, it's now only a static warning - and that matches that it now passes in checked mode. With the new check, `void` doesn't check anything at runtime, where it used to test that the value was `null`.

Using the `void` function's result wasn't detected because `assert_equals` takes `dynamic` as argument.

The test should preferably still be rewritten to avoid the warning and type-discrepancy, but it seems to be secondary to what the test is written to test, it's just a random type error that was actually caught in checked mode.

**Comment by floitschG** [comment]
Agree with Lasse. I went through all the affected tests and they are mistakes in the tests.

I filed https://github.com/dart-lang/co19/issues/111
