### ISSUE TITLE
Travis: Cover bug for things that annoy me

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29582]
I don't know what repository to file issues under, so please move (or direct me).

- [ ] Checking for `dartfmt` breaks across SDK versions.

For example, your `package:silly_monkey` is formatted with the `1.23.0` version of `dartfmt`, but you are testing your package with `1.24.0-dev` as well. There should be an easy way to only check `dartfmt` with stable.

- [ ] No way to reproduce build locally.

One of the advantages of a custom `presubmit.sh` script was you could actually run the build locally. How am I supposed to `git clone XXX`, make a change, and verify my change works without creating a pull-request and waiting for travis? Some guidance or a tool would be great.

**Comment by matanlurey** [comment]
@grouma showed me this, which helps solve `dartfmt`:

> https://github.com/dart-lang/test/blob/master/.travis.yml

This sort of brings a third issue though: I don't even know where our travis configuration is documented. We need some sort of knowledge base (on site-www, or in a wiki, or somewhere) to be able to refer to this.

**Comment by grouma** [comment]
Travis support is documented on the official website here: https://docs.travis-ci.com/user/languages/dart/

Corresponding code resides here: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb

**Comment by floitschG** [comment]
@whesse: do you have any input?

**Comment by whesse** [comment]
We don't use Travis to verify that our CLs work correctly, but the buildbots at https://build.chromium.org/p/client.dart/console

We intend to implement a commit queue and a system of trybots, as part of migrating our code review system.  Right now, testing locally with tools/test.py -mrelease will test the VM, and dart2js can be tested with tools/test.py -mrelease -cdart2js -rchrome -j4, for example.
Multiple runtimes, compilers, tests suites, and options can be tested with tools/test.py, but it is not well documented.  Running it with the --help option, or looking at tools/testing/dart/test_options.dart will show the command line options.

There is no easy way to test locally whether your change will break any of the buildbots, which is why we plan to implement a trybot system.  Travis is used by a subteam of the Dart project to test dartdevc, the Dart Developer Compiler, but is not testing the main components of Dart.

**Comment by matanlurey** [comment]
@kevmoo and @nex3 have done enough here to make me happy :)

**Comment by kevmoo** [comment]
@matanlurey is happy. I'm screenshotting this...
