### ISSUE TITLE
Different order of initializers call on VM and dart2js

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#29596]
```dart
init(var x) {
  print(x);
  return x;
}

class C {
  var x;
  var y;

  C() : y = init("y"), x = init("x") {
    init("C");
  }
}

class D extends C {
  var a;
  var b;

  D() : super(), a = init("a"), b = init("b")  {
    init("D");
  }
}

main() {
  var d = new D();
}
```
The programm above running on VM produces the following output:
```
a
b
y
x
C
D
```
Now compile it by dart2ja and run generated JavaScript. The output is:
```
y
x
a
b
C
D
```
Which order of initializers call is correct?

Tested on Dart VM version: 1.24.0-dev.4.0 (Tue May 09 02:15:50 2017) on "windows_x64", Dart-to-JavaScript compiler (dart2js) version: 1.24.0-dev.4.0. Chrome 58.0.3029.96 (64-bit)

**Comment by lrhn** [comment]
According to the last published spec, it's probably dart2js. According to the current spec in the repository, it's the VM.
The specification of object initialization wasn't entirely clear (field initializers weren't specified in a consistent way), and when rewriting that, we also decided to document the VM's behavior as the intended one.

So, the evaluation order of initialization for a class is:
- field initializers declared in the class, in source order
- initializer list expressions and super-call arguments, in source order
- recursive superclass initialization (if class isn't `Object`)
- constructor body executed

For a larger example:
```dart
class C {
   var c1 = init("c1");
   var c2;
   var c3;
   C(this.c3) : c2 = init("c2") { init("C"); }
}
class D extends C {
  var d1 = init("d1");
  var d2;
  D() : super(init("c3")), d2 = init("d2") { init("D"); }
}
init(x) { print(x); return x; }
main() {
  new D();
}
```
This should print:
```
d1
c3
d2
c1
c2
C
D
```
(and it is current the VM behavior).

We are considering to require the super-call to be at the end of the initializer list in Dart 2.0. There is no good reason for allowing it earlier since the only thing it affects is when the argument expressions are evaluated. For now, the super-call can syntactically be anywhere in the initializer list, but the superclass initialization always happen after the subclass initializer list.

**Comment by sigmundch** [comment]
fixed by using the CFE
