### ISSUE TITLE
dart2js feature request: --enable-assert

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#29601]
As discussed here https://github.com/dart-lang/pub/issues/932 it would be cool to turn on asserts without having to enable checked mode.

At the moment assert is rather useless because turning on checked mode slows down the whole application. 

**Please add a flag to dart2js to turn on asserts.**
`enableAssert: true` in pub would be the logical next step

**Comment by zoechi** [comment]
asserts are development-only and checked-mode is development-only, therefore this makes sense.
Do you want to have asserts enabled in production?

**Comment by matanlurey** [comment]
You can create your own "do-only-when" flag using `bool.fromEnvironment`:

```dart
const _someMode = const bool.fromEnvironment('someMode');

void conditional(void run()) {
  if (_someMode) {
    run();
  }
}

main() {
  print('Hello World');
  conditional(() {
    print('You are in someMode.');
  });
}
```

This is tree-shaken in dart2js when 'someMode' is false. You can set it to true using `-D`:

```bash
$ dart2js -DsomeMode=true
```

There are similar ways to enable flags in Dartium and the Dart VM.

**Comment by MikeMitterer** [comment]
@zoechi The problem is that I have to enable checked-mode just for assert - this should not be necessary. If it's necessary to turn on asserts in production depends on the situation, hopefully not but sometimes??? you never know, depends on the bug ;-)

@matanlurey Thank for this hint, nice. I would prefer having an option for standard assert but in the meantime thats a nice approach.

**Comment by eernstg** [comment]
[Here's a CL](https://codereview.chromium.org/2879153005/) which adds an `--enable-assert` option to dart2js. It may be helpful during development in cases where full checked mode semantics is too much of a performance hit, but correctness checks expressed using `assert` would still be nice to have.

It is of course technically very similar to the approach using `bool.fromEnvironment`, but it may be more convenient in practice to use `assert`, e.g., because some of the asserts are located in libraries which weren't written with this particular issue in mind, or just because a large project uses several different names for the "Dart environment variable" which which is used in the `bool.fromEnvironment` approach.

Note that there is no guarantee that the dart2js team will actually accept adding this feature.

**Comment by eernstg** [comment]
Landed support for `--enable-asserts` (the option was renamed in order to match the existing option for the vm) for dart2js and the testing framework in commit 3b05eb95530b1684a3fbcc69bda1784db393b966.
