### ISSUE TITLE
MapMixin should check types

### ISSUE THREAD

**Issue by jfphilbin** [dart-lang/sdk#29612]
Is there some reason that MapMixin._containsKey_ doesn't check the key's type?

Current definition: 

    bool containsKey(Object key) => keys.contains(key);

Proposed definition:

    bool containsKey(Object key) => key is K && keys.contains(key);

Likewise for MapMixin._containsValue_:

Current definition: 

    bool containsValue(Object value) {
      for (K key in keys) {
        if (this[key] == value) return true;
      }
      return false;
    }

Proposed definition: 

    bool containsValue(Object value) {
      if (value is! V) return false;
      for (K key in keys) {
        if (this[key] == value) return true;
      }
      return false;
    }

**Comment by rakudrama** [comment]
You are suggesting adding tests (a cost) to avoid some problem. I'm not
clear what problem you are trying to avoid.

For keys: if a test `is K` is desirable, it would also be desriable in the
implementation of `keys.contains()`. Adding it here would be adding the
inefficiency of a redundant test.

For values: if a program is using containsValue with the 'wrong' type, that
points to an inconsistency in the program. Does this happen often enough
that the cost of the test is worthwhile? The test just short-circuits the
loop. If, as I expect, most programs are using 'reasonable' arguments to
containsValue, this is a wasted test.

Even in strong mode, `null` is a permitted key or value, but does not pass
`is K` or  `is V`, so the test is more complicated.

In dart2js there are optimizations to remove unused type parameters when
not running in --checked mode. This makes objects smaller and the generated
code smaller and faster. These optimizations are defeated by the use of `is
V`, so it might also have negative effects on any generic class where the
type is eventually used in Map<K,V>.

**Comment by jfphilbin** [comment]
Stephen,

 

Thanks for your response. See my comments (JFP:) below.

 

Jim Philbin

Co-Chair, DICOM Standards Committee

Principal

Poplar Hill Informatics

jfphilbin@gmail.com

**Comment by lrhn** [comment]
On Sun, May 14, 2017 at 1:13 AM, Jim Philbin <notifications@github.com>
wrote:

> Stephen,
>
>
>
> Thanks for your response. See my comments (JFP:) below.
>
>
>
> Jim Philbin
>
> Co-Chair, DICOM Standards Committee
>
> Principal
>
> Poplar Hill Informatics
>
> jfphilbin@gmail.com
>
>
>
> From: Stephen Adams [mailto:notifications@github.com]
> Sent: Saturday, May 13, 2017 02:39 PM
> To: dart-lang/sdk <sdk@noreply.github.com>
> Cc: Jim Philbin <jfphilbin@gmail.com>; Author <author@noreply.github.com>
> Subject: Re: [dart-lang/sdk] MapMixin should check types (#29612)
>
>
>
> You are suggesting adding tests (a cost) to avoid some problem. I'm not
> clear what problem you are trying to avoid.
>
> For keys: if a test `is K` is desirable, it would also be desriable in the
> implementation of `keys.contains()`. Adding it here would be adding the
> inefficiency of a redundant test.
>
>
>
> JFP: I assumed the compiler would be able to optimize away the cost of this
>
> test in almost all cases. The same goes for keys.contains().


The compiler might be smart, but if the test makes a difference, it can't
be compiled away. If it doesn't make a difference, why put it there?

I'm guessing that you think it's an optimization - if you pass a non-K
object to the containsKey method, it can bail out early.

However, it does add an extra operation, and an extra branch, to all
containsKey calls. If most of the calls are with K instances, then it's
just an unnecessary overhead, no matter how efficient the type check is.
We believe that to be the case - most calls are with valid keys.

For the cases that aren't valid keys, hash maps are pretty efficient. They
should quickly figure out that the key isn't there, so the saving isn't
that great, even if type checks are efficient.



>
>
>
> For values: if a program is using containsValue with the 'wrong' type, that
> points to an inconsistency in the program. Does this happen often enough
> that the cost of the test is worthwhile? The test just short-circuits the
> loop. If, as I expect, most programs are using 'reasonable' arguments to
> containsValue, this is a wasted test.
>
>
>
> JFP: If I declare a Map to have type <K, V>, then I don't want to have to
> worry
>
> about verifying the keys have type K and Values have type V. If I must
> check
>
> the type of keys for containsKey, containsValue, keys.contains, and
>
> values.contains, then the cost of my time is much higher then the CPU cost
>
> of the test.


If you declare a Map<K, V>, then the keys will have type K (strong
mode/checked mode at least). You don't need to check it.

The containsKey, containsValue and keys.contains methods take Object as
argument. They work for objects other than the valid keys. If a K object
happens to think it's equal to a non-K object (then you are doing something
wrong, but) then containsKey would recognize it.

The reason for allowing objects other than K is that it allows supertypes.
You can do:
   Map<num, num> numMap = <int, int>{ 4: 4, 5: 5};
That's a valid assignment in Dart due to covariant generics.
It makes sense to do:
   numMap.containsKey(3.14)
That is why containsKey doesn't throw when it gets a non-K value.
If it did, this containsKey call would throw because the argument isn't an
int.


>
>
> Even in strong mode, `null` is a permitted key or value, but does not pass
> `is K` or `is V`, so the test is more complicated.
>
>
>
> JFP: When I write 'Map<K, V>, I expect 'null' to be an invalid key.


You'll have to change your expectation then, it's valid.

There are good arguments in either direction, but currently, all types are
nullable in Dart.



>
> In dart2js there are optimizations to remove unused type parameters when
> not running in --checked mode. This makes objects smaller and the generated
> code smaller and faster. These optimizations are defeated by the use of `is
> V`, so it might also have negative effects on any generic class where the
> type is eventually used in Map<K,V>.
>
>
>
> JFP: At a minimum it seems that adding an `assert(key is K)` and
> `assert(value is V)`
>
> Would help.
>

Help what?
You can't *add* a key that isn't a K, or a value that isn't a V. The map
itself is soundly typed.
The containsKey method is *deliberately* accepting values that are not
valid keys. Adding an assert to that would break programs that expects this
behavior.

/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by jfphilbin** [comment]
Lasse,

 

Thank you for your explanation.  Now I get it.

 

BTW, I'm a big fan of Dart, especially strong mode.

 

Jim

 

Jim Philbin

Co-Chair, DICOM Standards Committee

Principal

Poplar Hill Informatics

jfphilbin@gmail.com
