### ISSUE TITLE
analysis driver cache is large

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29648]
The cache is large (1 GB), and the directory contains a lot of files. This has issues when deleting the directory, listing the contents of the directory, or code completing file names in the directory.

I think there was an issues related to this, but was unable to find.

We should consider segmenting the directory into subdirectories, so a file named `fff8f4960d612103b41bb2be96929e9f.linked` might be stored in a `ff/` subdirectory.

/cc @scheglov

**Comment by scheglov** [comment]
Hm... I'm not sure whether to solve this or not.

Segmenting by first letters will work well only if there is uniform distribution of keys. It is now, because we use hashes, but this is contract above `ByteStore`. OTOH, even if this contract is ever violated, at worst we will have the same situation we are in now.

Segmenting will instead make a lot of smaller problems :-) . E.g. to delete the folder you still need to list all these files, now in 256 sub-folders. As for listing and file completion, it does not seem to be a necessary operation for users.

**Comment by devoncarew** [comment]
no work is planned here
