### ISSUE TITLE
dart2js produces unresolvable hints about as checks

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#29693]
When compiling the following code, most of which is taken from the `collection` package:

```dart
Map<K2, V2> mapMap<K1, V1, K2, V2>(Map<K1, V1> map,
    {K2 key(K1 key, V1 value), V2 value(K1 key, V1 value)}) {
  key ??= (mapKey, _) => mapKey as K2;
  value ??= (_, mapValue) => mapValue as V2;

  var result = <K2, V2>{};
  map.forEach((mapKey, mapValue) {
    result[key(mapKey, mapValue)] = value(mapKey, mapValue);
  });
  return result;
}

void main() {
  print(mapMap({}));
}
```

dart2js 1.23.0 produces these hints:

```
test.dart:3:26:
Hint: Method type variables are treated as `dynamic` in `as` expressions.
Try using the upper bound of the type variable, or check that the blind success of the test does not introduce bugs.
  key ??= (mapKey, _) => mapKey as K2;
                         ^^^^^^^^^^^^
test.dart:4:30:
Hint: Method type variables are treated as `dynamic` in `as` expressions.
Try using the upper bound of the type variable, or check that the blind success of the test does not introduce bugs.
  value ??= (_, mapValue) => mapValue as V2;
                             ^^^^^^^^^^^^^^
```

However, if I remove the `as` checks, I get the following strong mode errors:

```
    error • A value of type '(K1, V1) → K1' can't be assigned to a variable of type '(K1, V1) → K2' at test.dart:3:11 • invalid_assignment
    error • A value of type '(K1, V1) → V1' can't be assigned to a variable of type '(K1, V1) → V2' at test.dart:4:13 • invalid_assignment
```

It seems to me that dart2js shouldn't complain about an issue if that issue can't be fixed. It also seems strange that dart2js is printing different hints than the analyzer—I thought we weren't doing that anymore.

This is breaking a `test` package tests, so I'm marking it S1.

**Comment by lrhn** [comment]
Those messages are hints. Since dart2js isn't compiling in strong mode, it ignores method type parameters, so the `as K2` isn't actually doing anything (it's equivalent to `as dynamic`). It's emitting a hint about that because the user might not be aware that the cast does nothing. It's just a hint, not a warning or error, and you are free to ignore it. It's Dart 1, so it is *most likely* not a problem, the program will keep running anyway unless you are in checked mode, and then it'll get caught soon enough.

**Comment by eernstg** [comment]
I think it's worth adding one thing here: The main issue here is that you're performing static analysis according to one dynamic semantics (for strong mode) and then running the program with a different one (Dart 1.x).

This very nearly "just works", but you've encountered one case where the difference might introduce a bug, and hence you get a hint about it. Concretely, it might be a bug that `mapKey as K2` works like `mapKey is dynamic`, and hence it succeeds even in the case where `mapKey` is not a `K2`.

The reason why we did not make `.. as K2` a compile-time error/warning (like `.. is K2`) is that `as` has a strong bias toward success: It is frequently the case that `as` expressions succeed, and when they fail it is likely to indicate that something is wrong already. This makes `.. as dynamic` a reasonable approximation of the strong mode semantics, but still different enough to justify the hint.

As far as I can see it is not a bug in your case, because the return values from the functions `key` and `value` are immediately passed on in ways where checked mode checks (if enabled) will ensure the same thing as the "missing" `as` check: The returned key may not be a `K2`, but then `[]=` will fail because it requires a `K2` as its first argument, and similarly for the value and the second argument. Those checks work just fine (in checked mode) because class type variables are reified as needed.

So the conflict that you're seeing is that (1) `as MethodTypeVariable` is inherently bug-prone with strong-mode-analysis-plus-Dart-1.x-semantics, (2) strong mode analysis forces the functions `key` and `value` to return a `K2` resp. `V2`, so (3) you can't write default values for those functions without using the bug-prone construct.

But you might just do the following:
```dart
Map<K2, V2> mapMap<K1, V1, K2, V2>(Map<K1, V1> map,
    {K2 key(K1 key, V1 value), V2 value(K1 key, V1 value)}) {
  var myKey = key ?? (mapKey, _) => mapKey;
  var myValue = value ?? (_, mapValue) => mapValue;

  var result = <K2, V2>{};
  map.forEach((mapKey, mapValue) {
    result[myKey(mapKey, mapValue)] = myValue(mapKey, mapValue);
  });
  return result;
}

void main() {
  print(mapMap({}));
}
```
The point is that `myKey` and `myValue` can have slightly less strict types that allows them to have both the values passed by the caller and the values that you are able to express without using the bug-prone construct.

**Comment by nex3** [comment]
> Since it is just a hint, not a warning or error, you are free to ignore it.

Just because you're free to ignore it doesn't mean it doesn't cause problems. Unresolvable hints are at the very least useless noise after the first time the user sees them, and in dart2js that noise is even visible to downstream consumers of a package in the form of "X hints hidden in package:whatever" messages. In this case, that noise is concretely breaking tests that rely on parsing dart2js output, with no road to fixing those tests since the hints can't be fixed.

@eernstg I understand what the hint is trying to communicate. I don't think it's necessarily a bad thing to tell the user, but without a clear way to resolve it it's producing more harm than good. The fact is that my code works as intended in both strong mode and spec mode, and this hint doesn't leave room for that possibility. Your refactor halfway dodges the issue by making the casts implicit, but if you pass `--no-implicit-casts` it still produces strong mode errors.

Also, I'm still wondering why dart2js is producing different analysis information than the analyzer. Last I heard that was something we were trying to do less of.

**Comment by sigmundch** [comment]
As far as the hints go - I don't believe the intent here was to do any kind of analysis, but to inform about the status of a feature. Erik added these hints to be clear that the compiler supports the syntax but not the semantics (since we don't reify method-type-args and don't insert any checks).

So my question is what is the right way to communicate this our users?

I'm in favor of removing hints that are not actionable or providing a way in which they can be made actionable. Some options we can do:
 * provide the hint, but also give a flag to omits the hint. I don't think this is great, but we do this already with uses of `dart:mirrors`.
 * provide the hints and a way to silence them individually (e.g. an annotation on that line)
 * hide the hints by default, but provide a flag to show them.

Other suggestions?


As far as the dart2js hints go - I'm OK delete them, but I wonder what is the right balance of communication to the user here.

**Comment by nex3** [comment]
I'd be okay with option 2 or 3. Option 1 isn't great, because part of the frustration with these hints is that they're visible to downstream users who may not know how to turn off the hint, especially since it's difficult for them to even tell what hint is being generated.

**Comment by nex3** [comment]
Can we resolve this soon? It's still interfering with our tests.

**Comment by natebosch** [comment]
I'm no longer seeing these specific hints and AFAIK the CFE should be giving consistent warnings. I think this should be safe to close.
