### ISSUE TITLE
Add UNUSED_OPTIONAL_PARAMETER to default analysis

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29731]
The Dart analyzer already warns when a private method, field, or class is unused:

```dart
// unused_method
_foo() {}

main() {}
```

It would be nice to expand this to optional parameters of private methods or functions:

```dart
// unused_optional_parameter
_foo({bar}) {}

main() {
  _foo();
}
```

**Comment by srawlins** [comment]
@bwilkerson Would an unused parameter of a private method be considered an "unused element" (and use the unused_element code)?

**Comment by bwilkerson** [comment]
We didn't include those originally (optional or required) because it is possible for them to be necessary because of inheritance. (Private methods can override other private methods as long as they're in the same library.)

If we can efficiently know that there are no override related restrictions, then it would be valid to mark them as dead code. We could certainly mark unused parameters for top-level functions and static methods.

**Comment by srawlins** [comment]
Yeah I think that sounds good. We currently report unused private methods, first checking whether they override anything or are overridden by anything. So we could use the same or similar logic when validating optional parameters. Thanks!
