### ISSUE TITLE
Building with create_sdk doesn't include the require.js file for dev compiler

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#29749]
Steps to reproduce:

`./tools/build.py --mode release --arch x64 create_sdk`

Expected `out/ReleaseX64/dart-sdk/lib/dev_compiler/amd/require.js` to exist, but it doesn't.

If I do a build without `create_sdk` it does exist.

**Comment by vsmenon** [comment]
@jakemac53 are you seeing this on tip?  I cannot seem to repro:

```
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk] rm out/ReleaseX64/dart-sdk/lib/dev_compiler/amd/require.js 
remove out/ReleaseX64/dart-sdk/lib/dev_compiler/amd/require.js? y
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk] ls -la out/ReleaseX64/dart-sdk/lib/dev_compiler/amd/
total 15912
drwxr-xr-x  4 vsm  eng      136 May 30 12:50 .
drwxr-xr-x  7 vsm  eng      238 May 30 12:24 ..
-rw-r--r--  1 vsm  eng  6264127 May 30 12:22 dart_sdk.js
-rw-r--r--  1 vsm  eng  1876072 May 30 12:22 dart_sdk.js.map
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk] ./tools/build.py --mode release --arch x64 create_sdk
ninja -C xcodebuild/ReleaseX64 create_sdk
ninja: Entering directory `xcodebuild/ReleaseX64'
[6/6] STAMP obj/create_sdk.stamp
[vsm-macbookpro2.roam.corp.google.com:/Users/vsm/dart/sdk] ls -la out/ReleaseX64/dart-sdk/lib/dev_compiler/amd/
total 16088
drwxr-xr-x  5 vsm  eng      170 May 30 12:50 .
drwxr-xr-x  7 vsm  eng      238 May 30 12:24 ..
-rw-r--r--  1 vsm  eng  6264127 May 30 12:22 dart_sdk.js
-rw-r--r--  1 vsm  eng  1876072 May 30 12:22 dart_sdk.js.map
-rw-r--r--  2 vsm  eng    86482 May  3 06:06 require.js
```

**Comment by vsmenon** [comment]
@jacob314 @munificent - anything change here recently?

**Comment by jakemac53** [comment]
Hmm, I synced to tip this morning right before filing this bug and saw the issue. I don't know much about our build script but do you need to delete the out directory manually maybe before each build?

**Comment by vsmenon** [comment]
Talked to @jakemac53 - looks like he wasn't running `gclient runhooks` and the gn file had changed underneath.

**Comment by jwren** [comment]
I think the issue is fixed: I just did a `rm -rf out/`, rebuilt the sdk with `./tools/build.py --mode release --arch x64 create_sdk`, and then was unable to get the issue to reproduce I originally described (require.js not found).

However, after `pub serve` starts, if I add a comment in any dart file, I get the following stack trace from the running `pub serve`

Build error:
Failed to load source asset untitled|web/main.dart___jb_tmp___: Could not find asset untitled|web/main.dart___jb_tmp___.
package:pub/src/barback/pub_package_provider.dart 116  PubPackageProvider._assertExists
package:pub/src/barback/pub_package_provider.dart 110  PubPackageProvider.getAsset
===== asynchronous gap ===========================
package:barback/src/graph/asset_cascade.dart 146       AssetCascade.updateSources.<fn>
dart:async                                             new Future.sync
package:barback/src/graph/asset_cascade.dart 146       AssetCascade.updateSources
package:barback/src/graph/package_graph.dart 194       PackageGraph.updateSources.<fn>.<fn>
dart:async                                             new Future.sync
package:barback/src/graph/package_graph.dart 280       PackageGraph._inErrorZone.<fn>
dart:async                                             runZoned
package:barback/src/graph/package_graph.dart 279       PackageGraph._inErrorZone
package:barback/src/graph/package_graph.dart 194       PackageGraph.updateSources.<fn>
dart:collection                                        _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach
package:barback/src/graph/package_graph.dart 191       PackageGraph.updateSources
package:barback/src/barback.dart 95                    Barback.updateSources
package:pub/src/barback/asset_environment.dart 670     AssetEnvironment._watchDirectorySources.<fn>

**Comment by jakemac53** [comment]
@jwren if you can get a repro please file a separate bug, this looks like some tmp file probably created by intellij, not sure why it would have been requested from pub serve.

**Comment by alexander-doroshko** [comment]
@jakemac53, temporary files like `main.dart___jb_tmp___` appear because of the IDE's 'safe write' feature (that is enabled by default). When saving an edited file IDE first creates a new temp file, then deletes the original file and finally renames the temp file to the original file name. 
Two years ago we already had a problem with it was fixed at Pub side (actually in the underlying 'watcher' package): https://github.com/dart-lang/sdk/issues/21402.

**Comment by jakemac53** [comment]
Ok, my guess is this was some sort of timing issue with the file being deleted after the asset for it was created and handed to some user code? We could file a separate bug but its not related to this bug.

**Comment by alexander-doroshko** [comment]
I failed to reproduce the issue related to 'safe write' myself (Dart SDK 1.24.0-dev.6.5 on Windows).
@jwren if you have a repro please file an issue.
