### ISSUE TITLE
ClassElement.allSupertypes getter is missing results

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29767]
It does not appear to visit interfaces of mixins.

This looks mainly like it affects analysis_server; analyzer itself only uses the getter for protected member checking, so it probably doesn't come up much.

**Comment by kevmoo** [comment]
Bumping the priority. Just hit this looking at `UnmodifiableListView` – no `List` or `Iterable`.

Guessing this implementation is not digging into implementations of the Mixins?

Since this is exposed on ClassElement, it can affect any user of the Analyzer API – so the pain goes beyond analysis server

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/3000183002/
