### ISSUE TITLE
incorrect checking of covariant parameters

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#29760]
I don't think this behavior is intended:
```dart
abstract class I {
  m(num x);
}
/*abstract*/ class B implements I {
  m(Object x) => x;
}
class C extends B {
  m(covariant String x) => print(x + '!?!');
}
main() {
  I i = new C();
  i.m(42);
}
```
this results in a runtime check failure on `C.m`. There are no compiler errors.
```
Type 'int' is not a subtype of type 'String'
```
however if I uncomment `abstract class B` it correctly issues:
```
[error] Invalid override. The type of 'C.m' ('(String) → dynamic') isn't a subtype of 'I.m' ('(num) → dynamic')
```
The problem can be seen by reading _OverrideChecker._checkAllInterfaceOverrides; we are stopping our interface search once we encounter a concrete class. This means `covariant` parameters do not get checked against all of their superinterfaces.

**Comment by eernstg** [comment]
That's right. Here is the relevant sentence from the [informal spec](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-overrides.md):
```
For a covariant parameter, the override rule is that its type must be
either a supertype or a subtype of the type declared for the corresponding
parameter in each of the directly or indirectly overridden declarations.
```
`covariant String x` is a covariant parameter. Being a super-or-sub of `num` is one of the things it must satisfy, so the declaration `C.m` violates the override rule. This also illustrates that it is incorrect to stop searching when class B is reached, no matter whether it's concrete or abstract.

We do have ways to avoid searching the entire clausal supertype graph (that is, following all the `extends`, `implements`, and `with` links) in some cases: 

- We could store a bit indicating that the type annotations for a given parameter in all its clausal supertypes are the same type, in which case the supertype traversal can be pruned. That would presumably be a quite common situation.

- We could also store a bit indicating that the type annotations for a given parameter form an increasing sequence along all clausal supertype paths, in which case the checking can stop if the new declaration uses a subtype (we could swap the types `num` and `Object` in the example to create such a situation, and we would then know that `int` would be a subtype of all the relevant types and `String` is a violation of the super-or-sub requirement).

In general, it's very inconvenient to have to traverse the entire clausal supertype graph, but we expect covariant parameters to be rare, so with a little luck it shouldn't matter much in practice. Otherwise we may want to use tricks like the above to prune the search whenever possible.

**Comment by jmesserly** [comment]
this may be fixed now -- I recently cleaned up a lot of bugs in interface override checking) -- I will double check & make sure we have a test case

**Comment by jmesserly** [comment]
still reproduces. Interestingly CFE seems to have the same bug (and it fails to issue an error for `abstract` as well)
