### ISSUE TITLE
synthetic function types are not substituted correctly

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29778]
EDIT by @jmesserly: see comment here https://github.com/dart-lang/sdk/issues/29778#issuecomment-317149157 for description of the problem.

This bug has been recurring rather often and showed up in several other bugs, #30822 and #30207 

original bug description by Leaf follows:

---

The following program:

```dart
void main() {
  Null Function<R>(R Function(int)) f = <S>(g) {};
}
```

produces the following incorrect error when run against bleeding edge analyzer:

```
  error • A value of type '<S₀>((int) → S) → Null' can't be assigned to a variable of type '<R>((int) → R) → Null' at /Users/leafp/tmp/test.dart:2:41 • invalid_assignment
```

The inferred type for the lambda is `<S₀>((int) → S) → Null`, instead of the presumably correct `<S₀>((int) → S₀) → Null` .  

It looks like downwards inference is correctly choosing a new canonical type variable `S₀` to use to match up `R` and `S`, but is then constructing the final inferred type using a mix of `S` and 
`S₀` to produce an invalid type.

**Comment by jmesserly** [comment]
possibly related substitution problem: https://github.com/dart-lang/sdk/issues/30207

**Comment by jmesserly** [comment]
so, this happens any time we construct a (synthetic) function type, such as in TypeSystem. The resulting object cannot be substituted correctly because its free variable list (`FunctionTypeImpl.typeParameters`) is empty (because it did not have an enclosingElement scope chain available to populate the free variables).

This is going to be tricky to fix, but I'm working on it.

Other interesting finds:
* function types are not considered equal unless their `typeArguments` arrays are. So `int -> int` is not the same as `{int/T} T -> T` ... I thought we'd fixed this, but it's back
* GLB/LUB seems to ignore(!!) typeFormals of a generic function

**Comment by jmesserly** [comment]
Here are two more repros from #30822 
```dart
main() {
  T Function() Function<T>() g =
      <S>() {
    S Function() f;
    if (f != null) return f;
    return () => f();
  };
}
```
and
```dart
// Wants a function that takes a function and returns a same-typed function.
void foo(T Function() Function<T>(T Function() f) parameterName) {}

// Using a function literal. -> the return type needs to be inferred.
foo(<T>(T Function() f) {
  if (true) return f;
  return () => f();
});
```

**Comment by jmesserly** [comment]
another example from https://github.com/dart-lang/sdk/issues/30207 is tests/language_2/generic_methods_generic_function_result_test.dart

**Comment by jmesserly** [comment]
this was recently fixed https://dart-review.googlesource.com/c/sdk/+/59160, #33159
