### ISSUE TITLE
Accept platform.dill in incremental kernel generator

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#29835]
Currently frontend requires sdk sources to compile dart to kernel. Please consider enabing frontend to use platform.dill to get interface/implementation details instead of actual core dart sdk sources.

Flutter developers will use frontend to produce kernel binaries that will be sent to the device. Those kernels have to be compatible with platform.dill that was built as part of Flutter engine, that resides on the device. Having actual [writeable] sdk sources available on the workstation potentially creates room for mismatch between core API that was targeted by generated kernel and core API defined in platform.dill in Flutter engine.

**Comment by sigmundch** [comment]
@aam -  if I understand correctly, I think this is already implemented. I may be misunderstanding or missing some detail, of course.

Today, front_end accepts reading in `platform.dill` and we use it for most unit tests in the bots. If you are using the public APIs (like incremental_kernel_generator), then this input platform.dill needs to be specified in `CompilerOptions.sdkSummary`.

Is that what you needed?

**Comment by scheglov** [comment]
Kernel Driver does not use `platform.dill`, it uses `TranslateUri` to get SDK URIs and files, and processes SDK files as all other files. This lets us handle everything consistently instead of handling SDK specially. E.g. we use API signatures of all libraries in the transitive closure to compute the cache key. If we process SDK libraries as other libraries, we can use their API signatures and recompile as needed when some SDK libraries change. If we get SDK libraries from elsewhere, we need to invent a new mechanism for getting SDK signatures, preferably fine grained.

We cache compilation results in the file system cache, so SDK is compiled only once. And because we load or compile only libraries which actually used by the application, we don't pay the price of loading the whole `platform.dill` file. Security through obscurity is not strong enough, `platform.dill` is also writable.

**Comment by aam** [comment]
@sigmundch , interesting, I didn't know about that option. However, if I specify that I still need to provide `Map<String, Uri> dartLibraries` option, right? And I'm not sure what am I supposed to give it if I don't have that Uri mapping. Currently I'm using `lib/libraries.json` that is part of `flutter_patched_sdk`.

@scheglov , I guess main point about `platform.dill` would it be that it is exact same `platform.dill` that is used on the device(by VM) and on the workstation(by IKG) as flutter_tools currently does include it into app.flx package sent to the device for execution.

**Comment by scheglov** [comment]
OK, I see. Even if `platform.dill` is changed, it still be the same during compilation and execution. That's nice.

**Comment by sigmundch** [comment]
I apologize for the confusion - I somehow managed to forget all of this context even though we discussed this just last week. I apparently managed to clear my mental cache after just 2 days OOO :)

@aam - what is the status today: do we have the flutter-SDK sources available when running flutter_tools on the flutter developer setup (note: we believe it is OK to exclude patch files because the outline without the patches should be identical to the outline after patching)? Or is this issue blocking somehow the integration with flutter_tools?

**Comment by aam** [comment]
@sigmundch , we do download some sort of [Dart SDK sources](https://storage.googleapis.com/flutter_infra/flutter/4f5d6fab1187c1f5749a52ab5b4277d1bd51ee79/sky_engine.zip) when flutter runs on flutter developer's workstation for the first time. They are packaged and uploaded to the cloud with [the flutter engine build](https://build.chromium.org/p/client.flutter/builders/Linux%20Engine/builds/1454/steps/gsutil%20upload%20sky_engine.zip)),
But the way they are packaged(pkg/sky_engine/lib, pkg/sky_engine/skd_ext I think they are primarily for dart analyzer).

**Comment by aam** [comment]
This doesn't block integration with flutter_tools - worst case scenario we upload full copy of flutter_patched_sdk sources (in addition to platform.dill with flutter dart:ui) for time being. We can also investigate how existing Dart SDK sources packaged into pkg/sky_engine, pkg/sky_engine/sdk_ext is used, and try to repurpose those for IGK.

**Comment by sigmundch** [comment]
I believe @scheglov completed the implementation in 06e94bc36007bbbdafa44b694b3aac55d17e7ebc
