### ISSUE TITLE
Representation of redirecting factory bodies in Kernel AST

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29841]
To support modular compilation, we need a a way to represent redirecting factories, including the unresolved kind. I've mocked it up in Fasta in [RedirectingFactoryBody](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/redirecting_factory_body.dart).

See also #29169.

**Comment by mkustermann** [comment]
When doing the kernel2kernel constants transformation I've run into this issue, since the redirecting factory constructor's body has a `StaticGet(target-constructor)` and my code treated all static tear-offs as constants (and there's no such thing as a constructor tear-off yet).

Also `package:kernel/verifier.dart`  barfs on a fasta generated dill file (we use this verifier e.g. in `pkg/kernel/bin/transform.dart`).

If we need to preserve the information in modular compilation outputs, it seems to make sense to have a construct in Kernel IR to represent it (is it e.g. needed for `dart:mirrors`?).

If we decide to do it differently, e.g. by lowering factory constructors to have a body with a tailcall and a hint to not show it in stack frames, then we might not need it.

Would be wonderful if we could come up with a solution to fix this issue.

**Comment by kmillikin** [comment]
@stefantsov Could you take a look at implementing this when you get a chance?

**Comment by stefantsov** [comment]
@kmillikin Sure. I plan to start working on it today.

**Comment by askeksa-google** [comment]
The representation is there. It is currently not emitted correctly, which is tracked by https://github.com/dart-lang/sdk/issues/28421 and https://github.com/dart-lang/sdk/issues/28424
