### ISSUE TITLE
Creating map literals may be expensive in DDC

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#29865]
An internal customer had code that was running slowly when creating many map literals.  I don't have data as to whether this code was fast enough in dart2js (the customer reported slowness in dartium as well) but it would be worth verifying that our map literal creation code paths are fast enough.

This is especially true for string keyed maps (as was the case in the customers code).  I believe that we represent string maps in an optimized way (essentially as JS objects with the keys as properties), so it may be possible for us to codegen map literals directly as the underlying representation objects if we're not already doing so.

**Comment by jmesserly** [comment]
I did some digging. JsLinkedHashMap performance is really bad in DDC. There's a ton of low hanging fruit here: by inlining a few helpers, fixing the cells to be a JS object literal (rather than a Dart class w/ reified generic), and skipping covariant generic checks for private members, I was able to get nearly 10x speedup. And there's even more room here, I didn't even try touching issues like having the compiler/runtime class collaborate on the data representation, or other tricks for tracking linked hash map ordering.

**Comment by jmesserly** [comment]
Also note, ES6 does offer us some options if we want to rely on the built in iteration order. http://2ality.com/2015/10/property-traversal-order-es6.html

I'll have to investigate to see if we can use it in any cases (it might be too different).

Another thought: for identity hashcode/equality of Dart objects, one possibility is to create a symbol key that corresponds to that object. Since we'd have to cache the hashCode anyway, caching a symbol gives us a way to have a unique hash object. Also ES6 map may be worth investigating.

**Comment by jmesserly** [comment]
Okay looking into this more, finding lots more potential improvements.

So the identity map (`new Map.identity`) looks like it should already be pretty fast (I'm going to optimize it some more). We should use that for Maps with `int` and `String` keys. Furthermore, we can have the generic `==`/`hashCode` map use identity semantics for any classes that don't override `==`/`hashCode`. The existing code only knows how to do that for `String` and `int`, but my guess is that the vast majority of things people put in hash tables use identity semantics. That way, we'd only be paying for `==` and `hashCode` when those are actually used by the runtime key values.

**Comment by leafpetersen** [comment]
Awesome!  Can't wait to try some of this out.

**Comment by jmesserly** [comment]
fyi, I'm making progress here. I need to simplify `Object` member dispatch first (in particular: so we always call `hashCode` and `equals` through the extension member name), which has been a bit tricky.

**Comment by jmesserly** [comment]
Update: I'm almost done with some extensive optimizations for Maps/Sets, the main thing blocking me is some existing bugs we have with extension members (because I would like to enable map & set tests--some of these are marked failing currently).

One thing I still need to add is faster `new Map`/`new Set`

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/8167 has the improvements. I'm waiting for another CL or 2 to land though before sending it out; right now it includes those other CLs.
