### ISSUE TITLE
Support mixins in the VM

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#29881]
(not a new problem, just creating an issue to track it)

To support modular compilation we need to change the mixin transformation and void coping the code of mixins. The idea would be that the actual copying of the code will be handled when loading kernel in the VM or when compiling in dart2js.

One approach we discussed is to add a new node to the IR to represent a Procedure whose code is elsewhere, then the mixin transformer will inject these "forwarding" procedures without having to explicitly copy the body of the methods in a mixin.

**Comment by kmillikin** [comment]
The more I think about a transformation that generates mixin application classes but leaves their methods out, the less I see any benefit.  It seems like just a more bulky encoding of the mixin application.

Our original motivation for the transformation was that only afterward could we resolve super get, set, and method invocation into direct get, set, or method invocation.  As far as I can see we will still have to postpone that until link time.

Because we have syntax for representing mixins, we have to have static and runtime semantics for them.  I think we should therefore just leave them to a back end to eliminate if they want.  (For the VM back end, it's a separate issue whether they want to have the front end eliminate all of them, some of them, or none of them.)

**Comment by sigmundch** [comment]
Thanks Kevin - that actually makes a lot of sense to me, and I'm happy with that idea moving forward. Feel free to close this issue then.

@a-siva - what makes sense for the VM: does the VM want mixins to be transformed by the FE?

If so, there are a couple consequences:
 * we'd have to ship platform.dill with the sdk and use it in kernel-service, that way the front-end can have access to the code before applying the mixin transformation.
 * we'd have to make it possible to only apply the transformation at link time in IKG. I opened #30958 to start the design discussions on it.

**Comment by kmillikin** [comment]
Let's continue the discussion of what to do with mixins in the VM here.

* The current approach is to translate them away by generating the class declaration that would be the result of the mixin application.  This class requires and thus depends upon the bodies of methods in the mixin class.

Pros: the VM backend doesn't need to know that mixins exist, it only sees normal classes.

Cons: we can't compile against an outline of the platform libraries because we will potentially need the body of every method.  In the incremental recompilation case, every library that uses a mixin class depends on the implementation of the mixin class's library.

* The other extreme is to always leave mixins in the IL for the VM.  The VM's reader would act as a linker and generate mixin application classes.  It would need access to method bodies in the mixin class (but these bodies are present in the VM's heap object model) and we would only be able to resolve super calls when we are compiling methods to flow graph because they would be left unresolved in Kernel.

Pros: We can compile against an outline of the platform libraries and mixin applications do not depend on the method bodies of the mixin class when compiling from Dart to Kernel.

Cons: The VM's Kernel reader has to construct mixins.

* A third way is to translate mixins away in the front end as we are currently doing, by compiling against the full binary of the platform libraries.  To support the incremental case we require Flutter code to annotate mixin classes (this is a step toward an eventual `mixin` declaration distinct from classes) so that they (and only they) can have their method bodies considered part of a compiled interface.

Pros: everyone is satisfied?

Cons: complicated implementation and potentially considered onerous for programmers.

(I write that in order to translate mixin applications away in the front end we would need the full compiled Kernel binary of the platform libraries.  This isn't the only way to do it.  We could ship the compiled method bodies as part of the front end snapshot and then add an API for the front end to read the compiled body out of the VM's heap.)

**Comment by kmillikin** [comment]
This is currently not planned (at least, not by the Kernel or Front End teams).
