### ISSUE TITLE
Triage failing lib_strong tests using dartdevc

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#29922]
Many tests are failing under DDC with my new support for dartdevc in test.dart. I haven't triaged them yet to figure out why.

**Comment by whesse** [comment]
Some of these are labeled "Pass, Timeout".  These could be labeled "Slow" if they are just going over the limit sometimes.  Otherwise, they should be marked "Skip" - we don't get useful info out of running timing-out tests.

We are now thinking of introducing a --fast mode for testing that will skip Slow and Timeout tests, so that will also help fix the problem, so they will be skipped in fast mode.

**Comment by mraleph** [comment]
This issue has been open for 6 months. I see 83 status lines referring to it in the status files. Please triage the tests at your earliest convenience. Thanks.

**Comment by jmesserly** [comment]
I've gone through these a few times (as well as language_2, corelib_2) to get a general sense of what bugs may be present in DDC.

Most of the tests are not Dart 2 (strong mode) clean, and they have similar failures in other Dart 2 impls. We may need some kind of cross team effort to triage and fix tests to be Dart 2 clean for runtime behavior. (The Dart 2 test migration was good for static behavior, less so for runtime errors or other changes in functionality between Dart 1 and Dart 2.) I think we can track improving tests via some other mechanism like OKRs, rather than a single issue. So I think we can close this.

To help out the team, I've been attempting to update tests for Dart 2 whenever I touch the relevant test(s) or corresponding DDC functionality.

**Comment by munificent** [comment]
> The Dart 2 test migration was good for static behavior, less so for runtime errors or other changes in functionality/behavior between Dart 1 and Dart 2.

I think we did an OK job on runtime errors (you might be surprised how much substantive test changes were made), but we knew there would be a lot of mistakes slipping through the cracks.

Thank you for continuing to fix the tests!
