### ISSUE TITLE
DDC does not allow inherited class in typedef argument 

### ISSUE THREAD

**Issue by sh4869** [dart-lang/sdk#30009]
For the following code,

```dart
class Parent {
}

class Child extends Parent {
}

typedef void F(Parent arg);

void _f(Child a){
}

class TestClass {
  final F f;
  TestClass(this.f);
}

void main(){
  var x = new TestClass(_f);
}
```
This code isn't problem on the Dart VM and Analyzer, but in dev_compiler,

```console
[error] The function '_f' has type '(Child) → void' that isn't of expected type '(Parent) → void'. This means its parameter or return type does not matc
h what is expected. (test.dart, line 18, col 25)

Please fix all errors before compiling (warnings are okay).
```

**Comment by sh4869** [comment]
With `--strong` option, same error occurred on analyzer.

**Comment by lrhn** [comment]
Just to elaborate ... the error is correct. The strong-mode type-system is safe(ish), so you can't use `_f` as a function in a position where an `F` function type is expected. The `F` type allows the function to be called with a `Parent` object, but the `_f` function doesn't accept a `Parent` as argument. That's why `void Function(Child)` is not a subtype of `void Function(Parent)`. The other direction would work, though, because a function that accepts a `Parent` can be used as a function that accepts a `Child` since all `Child` objects are also `Parent` objects.
