### ISSUE TITLE
dart2js no longer replaces function stub with concrete implementation when compiling mixins

### ISSUE THREAD

**Issue by ajrcarey** [dart-lang/sdk#30005]
Consider the following interface, and a partial implementation of that interface as provided by a mixin:

```
@interface
abstract class MyInterface {

  void doThingA();

  void doThingB();

}

@mixin
abstract class MyInterfacePartialImplementation
implements MyInterface {

  @override void doThingA() {
    // ... do A-like things that we know will be the same across all implementations
  }

  @override void doThingB() {
    // ... do B-like things that we know will be the same across all implementations

   ...

    // ... but ensure that we also do one implementation-specific thing that we can't possibly know about
    // at interface time - but we know it's going to be necessary, so we want to insist an implementor
    // provides it

    this._doImplementationSpecificThingB();
  }

  void _doImplementationSpecificThingB(); // Stub out the implementation-specific thing
    // so any implementor of this interface consuming this mixin will be required to implement it.

}
```

Any implementor of this interface can get almost all the implementation functionality they require simply by including the mixin; they need only implement the stub specified by the mixin:

```
@implementation
class SomeImplementationOfMyInterface
extends Object
with MyInterfacePartialImplementation
implements MyInterface {

  @override void _doImplementationSpecificThingB() {
    // a concrete, implementation-specific implementation of the stub required by the mixin
  }

}
```

Prior to at least 1.24.1, and probably 1.24.0, this pattern worked perfectly well. The stub in the mixin was correctly replaced by the concrete implementation in the implementation during compilation to javascript by dart2js.

However, since 1.24.1, this no longer works; the stub is copied across to the compiled code instead, and the concrete implementation is dropped. Obviously the resulting javascript does not work.

The problem is also present in 1.24.2.

An option would be to move the stub of _doImplementationSpecificThingB() up to the interface itself, but it then becomes part of the public interface. The purpose of the pattern is to create a contract that implementors must provide, but without polluting the public interface with implementation details that a consumer should neither know about nor care about. The pattern worked correctly up to 1.23.x.

**Comment by ajrcarey** [comment]
I suspect the problem may be to do with the use of underscores specifying private member functions rather than public. Removing the underscores corrects the behaviour.

**Comment by sigmundch** [comment]
@ajrcarey thanks for filing the issue. I think what you said in your last comment is indeed the source of the problem: if your base class and subclass are in different libraries, that private name is not visible anymore. If you want users that mix MyInterfacePartialImplementation to implement an additional method, then that method needs to be public.

If you use a private method like you have, but also mix the class in the same library (where the private method is visible), I believe the code will also work.

I'll mark the bug as closed because I believe there is no action on our end, but feel free to reopen if I misunderstood the issue.

**Comment by ajrcarey** [comment]
Sorry for the delay in replying. Yes, I think your explanation explains it: the functions that are package private to the mixin class cannot cross the package boundary and be mixed in to a concrete class in a different package. This explains the dart2js behaviour. Looking at the code again, I believe that this was the first time the mixin class had been consumed from a different package, which explains why everything worked correctly previously.

I am a little puzzled, though, as to why the dart analyzer doesn't flag an issue here. After all, the concrete class declared in package B (by mixing in an abstract class in package A that contains package private functions) is not syntactically valid. Shouldn't dart analyzer be screaming at me about that? At the moment, the IDE is telling be that the code is valid. Only at compilation time do I find out it's not - even though, in retrospect, the reason it's not valid does make perfect sense.

**Comment by sigmundch** [comment]
It's a bit trickier - Dart detects a lot of issues at compile-time but some are only detected at runtime. In this case I believe analyzer and dart2js are consistent: none of them complain at compile-time, but the generated js code complains at runtime. I believe you'll get a similar runtime error in DDC or in Dartium as well.

I'm not sure if this is a situation that should be detected at compile-time. Part of the problem is that it is not clear where or how to signal the problem in an actionable way. The problem is not in the declaration of the mixin because it is OK to do that within the same library. The problem could be reported at the application of the mixin saying that the class can't be applied as a mixin, but that might be surprising to users of the code because they only see the public APIs of the mixin.

If it were to be reported at compile-time, the language team would need to add it to the language specification, so I've added `area-language` for them to take a look.

Language team, this is a reduced example of the situation:

***a.dart***:
```dart
abstract class M {
  public() => _private();
  _private();
}
```

***b.dart***:
```dart
import 'a.dart';
class A extends Object with M { 
  _private() {}
}
```

**Comment by ajrcarey** [comment]
I understand. Looking at the problem from the perspective of merely a programmer, not a language designer, I would definitely expect syntax errors, such as a mangled class definition, to fall into the class of errors that are detected at compile time rather than run-time. Detecting syntax errors at run-time feels like scripting language behaviour to me, not compiled language behaviour. Personally I'd be in favour of simply disallowing private functions and fields in classes that are consumed as mixins, as (a) it's unambiguous, (b) it's simple, and (c) it covers all the use cases equally, but perhaps that's a bit too draconian.
