### ISSUE TITLE
Bots are not testing the version of dart2js included in the sdk

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#30019]
We recently encounter a bug in script snapshots that cause the use of dart2js on Golem to fail. No bot detected this failure because the bots are running "batch mode" dart2js instead of the dart2js that is shipped in the SDK

**Comment by rmacnak-google** [comment]
@sortie

**Comment by rmacnak-google** [comment]
(That is, no test bot on the console page. Obviously the Golem bots hit this.)

**Comment by whesse** [comment]
Thanks for this info - I didn't know that the batch mode wasn't using the sdk dart2js.  Can we make it use the sdk dart2js?

**Comment by whesse** [comment]
I'm not convinced that the bots aren't running the dart2js from the SDK - it looks to me like they are.  What is the evidence that they aren't?

I've checked the bots and their arguments, and when running locally, if I give the arguments --use-sdk
 --cdart2js --dart2js-batch, then the process that is started has command line:
/usr/local/google/home/whesse/ssd/sdk/out/ReleaseX64/dart-sdk/bin/dart /usr/local/google/home/whesse/ssd/sdk/out/ReleaseX64/dart-sdk/bin/snapshots/dart2js.dart.snapshot --enable-diagnostic-colors --library-root=/usr/local/google/home/whesse/ssd/sdk/out/ReleaseX64/dart-sdk --batch

So it seems that everything is running from the built SDK, which makes sense, since we don't build on the bots, only download the SDK.
