### ISSUE TITLE
Dartium & Dart2js discrepancies

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#30049]
I've found two discrepancies in dart2js and Dartium whilst playing around with my project: https://github.com/jimmyff/cellular_automata

Firstly the Dartium version is significantly faster than the JS version by about a factor of 10 in terms of FPS.

Also the generator function provides different results:
```
(x, y) => ((x ^ y) + y - x) == 0 || ((x ^ y) + y - x) % y == 0
```
Correct Dartium version:
![Correct Dartium version](https://user-images.githubusercontent.com/298850/27688553-de7b0b78-5cd2-11e7-956c-7f0771e96c86.png)

Incorrect Dart2js version:
![Incorrect Dart2js version](https://user-images.githubusercontent.com/298850/27688567-eb424ba0-5cd2-11e7-8909-880d91896e90.png)

**Comment by rakudrama** [comment]
Are **x** and **y** negative?

In dart2js we had to limit the range and domain of bitwise operators like '**^**'.
These operations are expected to be fast, so we cannot do much more than use the underlying JavaScript operations, which are reduce the inputs to signed 32 bit values and produce a signed 32 bit result.
We found that the signed 32 bit values were hard to use and caused some important bit-vector programs to fail, so we decided to force the values to unsigned 32 bit values instead.
With either restriction (signed 32 bit or unsigned 32 bit) there are some programs that fail.

The speed difference is probably due to dart2js being an ahead-of-time compiler and Dart VM in Dartium being ajJust-in-time compiler.  The JIT can see **x** and **y** are small integers with a special efficient representation, so after a couple of quick checks to verify this assumption, the rest of generated machine code is similar to what you would get in C.

You can get closer to the VM's great performance in dart2js:
1. declare x and y to be int:  (**int** x, **int** y) => ...
2. Compile with --trust-type-annotations
3. Some remaining slowdown is probably due to **%** (modulo) in **((x ^ y) + y - x) % y == 0**.  You could try using **remainder** instead, which compiles to JavaScript **%** (remainder). Since the inputs can be negative, you can't generally replace modulo with remainder, but in this case it works because the result is compared to zero.

**Comment by jimmyff** [comment]
With regards to the discrepancy with the generator functions: Yes x & y can be negative, `0,0` is the middle of the grid. I still don't understand why dartium vs dart2js shows a different result?  My dart generator function is ported from a javascript function that I know works correctly: 
```
(x, y) => ((x ^ y) + y - x) % y == 0
```
(I've tried implementing `.remainder()` instead of modulo but it hasn't altered the output.)

With regards to performance, it's actually the processing of the running cellular automata (eg: conway's game of life) which is highlighting the performance discrepancy. As per your suggestion I've added `trust-type-annotations` and `trust-primitives`. A heavily populated 512x512 grid runs at full speed (capped at 20fps) on Dartium however 4fps on chrome -on my macbook. I haven't optimised the processing of the automata which I know will make a difference big difference in terms of performance gains (for both) but I'm surprised that Dartium & JS are *so* far apart - I guess I'll just have to work around JS performance being much slower that JIT Dart.

**Comment by jimmyff** [comment]
As Dartium is soon going away I thought I better quickly do the work to find this discrepancy. I've got the generated values by both Chrome + Dartium for comparison:

### ENDLESS_SIERPINSKI

```dart
MathematicalGenerators.ENDLESS_SIERPINSKI: (int x, int y) =>
        (x ^ y) + x - y == 0
```

[Chrome results](https://github.com/dart-lang/sdk/files/1706763/ca_ENDLESS_SIERPINSKI_chrome.txt)
[Darium results](https://github.com/dart-lang/sdk/files/1706764/ca_ENDLESS_SIERPINSKI_dartium.txt)
[Diff](https://github.com/dart-lang/sdk/files/1706765/ca_ENDLESS_SIERPINSKI_diff.txt)


Example Chrome:
```
(-64 ^ 64) + -64 - 64 = 4294967040
(-64 ^ 63) + -64 - 63 = 4294967168
```

Example Dartium:
```
(-64 ^ 64) + -64 - 64 = -256
(-64 ^ 63) + -64 - 63 = -128
```


### SIERPINSKI_MOUNTAINS

```dart
MathematicalGenerators.SIERPINSKI_MOUNTAINS: (int x, int y) =>
        ((x ^ y) + y - x) == 0 || ((x ^ y) + y - x).remainder(y) == 0,
```

[Chrome results](https://github.com/dart-lang/sdk/files/1706766/ca_SIERPINSKI_MOUNTAINS_chrome.txt)
[Dartium results](https://github.com/dart-lang/sdk/files/1706767/ca_SIERPINSKI_MOUNTAINS_dartium.txt)
[Diff](https://github.com/dart-lang/sdk/files/1706768/ca_SIERPINSKI_MOUNTAINS_diff.txt)

Example Chrome:
```
((-64 ^ 64) + 64 - -64) = 4294967296
((-64 ^ 63) + 63 - -64) = 4294967422
```

Example Dartium:
```
((-64 ^ 64) + 64 - -64) = 0
((-64 ^ 63) + 63 - -64) = 126
```

**Comment by rakudrama** [comment]
As explained before, we had to choose between two possible ways of limiting the range.
Since xor does not move (shift) the bit you are expecting to be interpreted as a sign bit, you can obtain the generator function you want by forcing the xor value to be signed:
 `(x ^ y).toSigned(32)`

**Comment by matanlurey** [comment]
I think we can close this. We aren't supporting Dartium anymore.
