### ISSUE TITLE
strong mode Error type to use for generic functions/methods

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30095]
Strong mode introduces some new runtime failures compared with checked mode.

DDC currently throws these with an internal type "StrongModeErrorImplementation" that is not exposed to users. I believe we should fix this, and use some Error type that exists in the SDK. Most of the new errors relate to generic methods:
* dynamic calls with the incorrect number of generic type arguments. noSuchMethod does not support generic method type arguments, see: https://github.com/dart-lang/sdk/issues/27323.
* dynamic calls that violate type parameter bounds of a generic function.
* instantiateToBounds failure at runtime. This happens when type arguments are not passed to a generic function, and then instantiateToBounds results in an error (because of a recursive constraint that cannot be solved by the spec algorithm).

I believe we could treat the wrong number of type arguments similar to a wrong number of arguments, and include it as NoSuchMethodError. That's covered by #27323.

The other two could be treated as CastError, similar to how checked more handles incorrect argument types. Or perhaps some other error type is more appropriate.

There's one other case of "StrongModeError" currently: some `is` checks are disallowed to avoid conflict with Dart1 semantics. But this is supposed to be removed, see: https://github.com/dart-lang/sdk/issues/28988.

**Comment by jmesserly** [comment]
CC @vsmenon @leafpetersen

**Comment by lrhn** [comment]
The `noSuchMethod` (or rather, the `Invocation` class) needs to accept type arguments eventually.
Adding a field to an interface is a non-breaking change in Dart 1 and a breaking change in Strong-Mode, so I guess there is no reason to delay it. We should just go ahead and do it as soon as possible.

The malbounded type argument – I guess there is no corresponding problem with classes because you can't invoke a constructor dynamically. If we do constructor tear-offs, we might get that problem too.

I think the instantiate-to-bounds error can be treated the same - it's an invalid instantiation, either because the user provided an invalid type argument or because the system provided an invalid type argument (because it couldn't find a valid one for you). The error messages might need to differ, though.

**Comment by jmesserly** [comment]
thanks! based on this discussion I'll fix this in DDC

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3008053002/
