### ISSUE TITLE
No warning when missing calls to super constructor with @required parameters

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#30117]
I'm presumably holding it wrong.  But as far as I can tell, this should give me an analyzer error:

```dart
import 'package:meta/meta.dart';

class A {
  String param;
  A({@required this.param}) {
    assert(param != null);
  }
}

class B extends A {
  // This should warn!
  B();
}

class C extends A {
  // This should also warn!
}

void main() {
  new A(param: 'foo');
  new B();
  new C();
}
```

**Comment by bwilkerson** [comment]
What kind of warning are you expecting to see?

**Comment by dominicfrost-wf** [comment]
I am interested in an issue for a related reason; the fact that the @required annotation does not actually enforce a params requiredness. If not provided, the analyzer simply marks the line with a hint.

I love using named params. They allow APIs to easily evolve over time, while maintaining backwards compatibility. Adding a new param doesn't break the signature of the API, and therfore allows for the incremental addition / removal of feautures. 

One thing that is missing, however, is the ability to make a named param required. The @required annotation does not do this. It appears that the @required annotation currently behaves as the opposite of the @deprecated annotation. By this, I mean that it notifies consumers of params that will eventuially be required, much like the @deprecated annotation notifies consumers of params that will eventually be removed. I do like this as a feature, as it makes the communication of upcoming changes more transparent, but the nomenclature of the @required annotation is misleading in this case.

Ideally, I think the @required annotation would be strict, and force consumers to provide it, otherwise error. However a change like that would likely cause problems for everyone that expects it to behave the way it already does. A more realistic solutions would be to add a new annotation that was a strict required annotation, perhaps @requiredstrict.

Thoughts?

**Comment by zoechi** [comment]
or leave `@required` as it is and add `@requiredSoon`

**Comment by dominicfrost-wf** [comment]
but `@required` would behave the exact same way as`@requiredSoon`.

**Comment by zoechi** [comment]
No, `@required` would be an error and `@requiredSoon` a hint.

**Comment by dominicfrost-wf** [comment]
`@required` does not currently error, it hints, or am I missing something?

**Comment by zoechi** [comment]
I don't know, but I think it should, otherwise it should be named `@considerPassing` ;-)

**Comment by bwilkerson** [comment]
Dart does not assign run-time behavior to annotations [1]. If you want an error to be produced that would prevent offending code from being executed (or would allow execution but cause a run-time exception to be thrown when the violating code is executed) the feature would need to be moved from an annotation to a keyword. If you'd like to request that, please create a new issue in 'area-language'.

In the absence of language support for these semantics, the best we can offer is an annotation that users can ignore. We missed a use case, and need to fix that, hence this issue.

[1] That's why we moved from the `@covariant` annotation to the `covariant` keyword.

**Comment by dominicfrost-wf** [comment]
Ah gotcha. Thanks for the explanation @bwilkerson.

**Comment by srawlins** [comment]
Very similar to https://github.com/dart-lang/sdk/issues/30261, but likely different fix, so keep each open.

**Comment by Hixie** [comment]
FWIW, this would have caught a bunch of errors in the flutter tool that I just had to track down manually instead (and which had gone unnoticed for a long time -- I only caught them by accident because I was doing something nearby).

**Comment by bwilkerson** [comment]
FWIW, the equivalent code using the `required` keyword does produce an error under null safety.

**Comment by srawlins** [comment]
Downgrading to P4 as null safety and `required` are the real path forward.

**Comment by eseidelGoogle** [comment]
Honestly just feel free to close (this any any other problems eliminated by null safety).  The likelihood of us optimizing for non-null-safe dart at this point seems extremely low.

**Comment by eseidelGoogle** [comment]
(I took action based on me having opened the bug -- through my other account -- please feel free to re-open if I've done wrong here. :)
