### ISSUE TITLE
[Regression?] VM's behavior of stdin/out/sink changes in 1.25.0?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30119]
I don't see anything documented in https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md.

But a test fails @ `1.25.0-dev.4.0` [on travis](https://travis-ci.org/dart-lang/io/jobs/251815068):

```
test/process_manager_test.dart: spawn should forward stdin to another process [E]     
  Expected: [
              'You said: Ping',
              '\n'
                ''
            ]
    Actual: [
              'You said: Ping\n'
                ''
            ]
     Which: was 'You said: Ping\n'
              '' instead of 'You said: Ping' at location [0]
```

In `1.24.0` (stable) both travis and locally I get `['You said: Ping', '\n']` from the following:

```dart
final spawn = await processManager.spawn(
  'dart',
  arguments: [p.join('test', '_files', 'stdin_echo.dart')],
);
spawn.stdin.writeln('Ping');
await spawn.exitCode;
expect(stdoutLog, ['You said: Ping', '\n']);
```

Here is the source of `stdin_echo.dart`:

```dart
import 'dart:io';

void main() => stdout.writeln('You said: ${stdin.readLineSync()}');
```

You can reproduce via `pub run test` at the following commit: https://github.com/dart-lang/io/commit/7107db5e093af206a23688abb8f8fbc830032351

**Comment by lrhn** [comment]
This doesn't look like behavior that we want to promise one way or the other.

Calling `spawn.stdin.writeln('Ping')` will send "Ping" followed by a newline. Whether that is sent or received as a single message or two (or five individual characters) is completely implementation dependent, and likely affected by the platform and the timing as well – even if the message and the newline are sent individually, if the receiver doesn't poll stdin before both are sent, it will likely see all the characters, the process communication is character based, not message based.

So this can be due to any number of inconsequential changes, and the test is being overly specific about what result it expects.

**Comment by matanlurey** [comment]
Promise or not, shouldn't it stay consistent @lrhn?

**Comment by lrhn** [comment]
Not really, no. If there is no promise, it is a mistake to depend on a concrete behavior.

As I said, if you send the chars "Ping" and the char "\n" to a process' stdin, it won't see the individual packages, it will just see characters – stdin is character based after all. 
If it polls between receiving "Ping" and receiving "\n", that will generate two events in the stdin stream. If it polls only after receiving both, it will generate only one event. That's timing based, so it's not something that needs to stay consistent. It is affected by timing and buffering at any level (from OS to Dart code).

You could argue that we shouldn't have made the Dart stdin string based when the underlying thing is actually character based, because that can cause these kinds of ambiguities. You might even be right, but being completely character based is likely to be inefficient.

In this case, I have no idea why the test changed behavior, but either behavior is correct, and the test is faulty for assuming one of them is the only valid one.
