### ISSUE TITLE
List.take(null) should throw some meaningful exception

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30155]
Currently it just treats `a.take(null)` as if `a.take(a.length)`.

**Comment by lrhn** [comment]
Good catch. We use the same code for `take` and `getRange`, and the latter allows omitting the end. We need to add a check to the `take` method on `List`.

**Comment by lrhn** [comment]
I'd personally be OK with trying to fix this bug.

It's more permissive than it needs to be, but there is also absolutely no need for the functionality, and no discoverability. The documentation for `List.take` doesn't document this behavior, and it's likely some list implementations don't actually work that way. The documentation inherited from `Iterable` does not say that `null` is allowed, which would be the only reason to assume that it is.

So, it's a bug-fix. It's breaking, but hopefully nobody depends on the behavior since it's not actually necessary - and if anything, we might catch a few errors by actually throwing on a `null`.

(And for the record, it's not equivalent to `a.take(a.length)` but to `a.subRange(0)` - it doesn't lock down the number of elements when you call `take`, but allows you to iterate all elements of the list at the time of iteration).

**Comment by lrhn** [comment]
Not fixed yet, but will definitely become invalid with NNBD.

**Comment by lrhn** [comment]
https://dart-review.googlesource.com/c/sdk/+/140602
