### ISSUE TITLE
Enhancement: @subClassMustOverride for package:meta

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#30175]
This would be useful for when a package declares a base implementation of a method but sub types are required to override the base implementation.

Right now I'm implementing superclass type lookup for objects by requiring the objects to override a method. Subclasses are required to override a method to implement correct behavior. An implementation can be seen here:

```dart
typedef void TypeVisitor(Type type);

class Event {
  @mustCallSuper
  @subClassMustOverride
  void visitTypes(TypeVisitor visitor) {
    visitor(Event);
  }
}

class MessageEvent extends Event {
  @override
  void visitTypes(TypeVisitor visitor) {
    visitor(MessageEvent);
    super.visitTypes(visitor);
  }
}

class EventDispatcher {
  void dispatchEvent(Event event) {
    event.visitTypes((type) => _dispatchInternal(event, type));
  }
  void _dispatchInternal(Event event, Type type) {
    // Dispatch to (or create) a stream for this type...
  }
}
```

Failing to override the method would result in an analysis warning. An abstract class extending a class with @subClassMustOverride methods will not have an analysis warning, but classes that extend that abstract class will.

**Comment by creativecreatorormaybenot** [comment]
I propose (based on @Hixie, see #41347) to call it `@mustOverride` instead.

**Comment by Peng-Qian** [comment]
any updates...

**Comment by bwilkerson** [comment]
Sorry, but no, there hasn't been any progress on this issue.

**Comment by rmtmckenzie** [comment]
I'd just like to add a use-case - this would be great for ensuring that objects implement more a useful equals, toString, etc.

**Comment by jamesderlin** [comment]
A basic use case would be to have properly enforced `.clone()` methods.

**Comment by bwilkerson** [comment]
No, sorry, there's been no progress.

**Comment by henriqueArrazao** [comment]
My gosh, since 2017?? What a shame

**Comment by A-Castanho** [comment]
Nothing yet?

**Comment by srawlins** [comment]
No, sorry, there's been no progress.

**Comment by srawlins** [comment]
I thought about what particulars we might want for this annotation (and I like the name `@mustOverride`):

* The annotation is for class instance non-abstract members, and _maybe_ for mixin instance non-abstract members, including methods, operators, getters, setters, and fields.
* A hint is reported if anything else is annotated with `@mustOverride` (extension methods, library-level elements, parameters, constructors, static members, enum members).
* For a class _C_ with superclasses S<sub>1</sub>, S<sub>2</sub>, ..., (and mixins M<sub>1</sub>, M<sub>2</sub>, ...?) and with instance members annotated with `@mustOverride` m<sub>1</sub>, m<sub>2</sub>, ..., m<sub>n</sub>, a hint is reported if _C_ does not directly override all of m<sub>1</sub>, m<sub>2</sub>, ..., m<sub>n</sub>.
  * To be specific here: if a class _S_ has a `mustOverride` member named _m_, and a mixin _M_ also has a non-abstract member named _m_, and a class _C_ has no body, but extends _S_ with _M_, we have an error. Yes? Dependent on whether _S_ is a superconstraint of _M_?
* For a mixin _M_ with superconstraints S<sub>1</sub>, S<sub>2</sub>, ..., and with instance members annotated with `@mustOverride` m<sub>1</sub>, m<sub>2</sub>, ..., m<sub>n</sub>, a hint is reported if _M_ does not directly override all of m<sub>1</sub>, m<sub>2</sub>, ..., m<sub>n</sub>.

**Comment by bwilkerson** [comment]
I know it's a bit longer, but I think it's also more correct to name the annotation `mustBeOverridden`. The shorter `mustOverride` sounds like you want the analyzer to verify that the annotated method is an override, which is what `override` does.

**Comment by srawlins** [comment]
While less correct, I think `@mustOverride` fits with `@mustCallSuper`. 🤷

**Comment by srawlins** [comment]
I like @Hixie 's original term, "re-abstracting". Maybe `@reabstract`

**Comment by jamesderlin** [comment]
> I like @Hixie 's original term, "re-abstracting". Maybe `@reabstract`

It's much less clear what `@reabstract` means.  For example, it could easily be interpreted to mean that the class that uses can no longer be instantiated.

**Comment by srawlins** [comment]
I was joking. Sorry for that.

**Comment by bwilkerson** [comment]
> While less correct, I think `@mustOverride` fits with `@mustCallSuper`.

I'd argue that something like `mustBeCalledByOverrides` might be a better name for the latter because it better expresses the intent being made explicit. (It isn't the case that the author intends that the method being annotated call `super`, which is an interpretation that someone not familiar with the annotation could easily have.)

But ignoring that, with the latter there's an implied object. The more complete version is `overridesMustCallSuper`. Given that the annotation is on a member one could argue that the implied object isn't too hard to figure out. In this case the more complete version is `subclassesOfTheEnclosingClassMustOverride` (or maybe `subtypes`?), and that implied object seems less obvious to me.

**Comment by scheglov** [comment]
I'm dubious about named mixin application like `class N = S with M;`.
IIUC, the spec says that `N` has members of `M`.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/384794/180338867-794bddc6-a734-4d8f-b599-bcb6129df2a5.png">
So, formally, it is as if copied members of `M` into a `class N extends S implements M { ... }`.

**Comment by scheglov** [comment]
Do we require such overrides for abstract classes? If we look at such methods as "abstract" in some sense, then by the same logic, there will be a concrete class that overrides eventually, but this abstract helper does not have to.

And because mixins are sematically rewritten as abstract classes...
<img width="713" alt="image" src="https://user-images.githubusercontent.com/384794/180340091-2cf787d9-a5b0-45dc-9437-bf67eaefad2e.png">
...they don't have to override.

**Comment by bwilkerson** [comment]
> I'm dubious about named mixin application ...

I agree, a mixin application already has an override if the mixin has an override, but doesn't if the mixin doesn't.

> Do we require such overrides for abstract classes?

I asked the same question on the CL. I wasn't thinking about the mixin application case, but it would apply if the mixin doesn't define a concrete override of the member.

**Comment by srawlins** [comment]
> I agree, a mixin application already has an override if the mixin has an override, but doesn't if the mixin doesn't.

SG.

> Do we require such overrides for abstract classes?

Yes. Without a motivating example, I don't see any reason to allow a class (abstract or not) to omit an override.

**Comment by eernstg** [comment]
Here's an argument why it would make sense to enforce `@mustBeOverridden` with each concrete class, but not with abstract classes:

In any given class, the superinterface graph can be inspected. For any running instance member body we'll ever encounter, the dynamic type of `this` is going to be a concrete class `C`.

This means that if something must be done in order to ensure that the instance of `C` has the correct behavior (with respect to `@mustBeOverridden` or actually with respect to anything), it is sufficient if it has been checked that every instance of `C` will do what is needed.

This is actually quite convenient, because it is not possible to provide an implementation of a member `m` in a class which is created by a mixin application. (So if we require all subtypes/subclasses of a given class to have a declaration of `m` then we're stuck if a class has a mixin application anywhere in its superclass chain.) But mixin applications are always abstract anyway, so that problem goes away if all abstract classes are allowed to have no such declaration.
