### ISSUE TITLE
Intrinsify Closue_equals

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#30181]
Many profile samples are taken in this runtime call during Flutter animations on Fuchsia.

/cc @a-siva

**Comment by zanderso** [comment]
Here is the runtime implementation.

https://github.com/dart-lang/sdk/blob/master/runtime/lib/function.cc#L33

**Comment by alexmarkov** [comment]
The Flutter use case which inspired this issue is actually about storing many closures in the HashSet and frequently calling contains() to check is a particular closure in the set. In such case, the profile showed that majority of time is spent in Closure_equals.

However, I found that Closure_equals is called excessively due hashcode collisions. Hashcode for closures  was calculated as the hascode for the underlying function, so it is the same all implicit instance closures created for a particular method, regardless of different receiver objects. After improving hashcode for closures in CL [https://github.com/dart-lang/sdk/commit/203955bc48fdbd03b7b030c4e6dbcd20920201ec](https://github.com/dart-lang/sdk/commit/203955bc48fdbd03b7b030c4e6dbcd20920201ec), there is a significant speedup of HashSet.contains() for closures and Closure_equals is no longer the bottleneck in this use case.
