### ISSUE TITLE
Improve FE's APIs when working with erroneous code

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30194]
Once https://codereview.chromium.org/2982093003/ lands, we'll have that by default an error causes a throw. We want to change this as follows:

  - Make all public APIs that return a value to return a result object instead:
    - if compilation was successful, the result includes the program/summary that was requested
    - if not, the result includes all errors in a List
  - `onError` handler is still used to handle errors as they come up
  - `throwOnError` will be false by default and then only used by developers to debug issues
  - Define flags to tune what it means to have a successful compilation:
     - no errors (default)
     - no errors or warnings (if a flag like `warningsAreFatal` or `treatWarningsAsErrors` is on)
  - Add a flag to compile with errors (`emitWithErrors`)
  - Ensure errors are only reported once (we have some duplication when using the public API)
  - Ensure recoverable and unrecoverable errors are tracked separately internally and externally (possibly by using a new marker/severity to expose recovered errors externally). The idea is that (a) we can use this to decide whether to emit code when `emitWithErrors` is true, and clients can filter out errors as well.
  - And finally add test coverage for all these cases.

**Comment by peter-ahe-google** [comment]
I'm really confused about this bug. Why is throwOnError set to true now?

**Comment by peter-ahe-google** [comment]
Any option ending with "AreFatal" is for debugging the compiler, not for use to change the exit code. It's possible that we need to rename all these options.

**Comment by peter-ahe-google** [comment]
I'm blocked by some of these issues and I've started working on some of them.

**Comment by sigmundch** [comment]
For the public API, we need a good set of defaults to prevent errors from being accidentally ignored. 

We have had two design ideas for this: 
 - make the default error handler print and throw on errors. (what we have today)
 - return a Result object which contains the errors and a `null` program when errors

We'll still support returning a program that was built with error recovery by providing an extra API option (like compile-with-errors), it just wont be on by default.

**Comment by sigmundch** [comment]
Looking at your CL I understand that there is a third issue here: today we throw something that was meant to be internal (`deprecated_InputError`), if we want the default handler to throw and that is the design we want to use, then we would need to throw something else. I personally prefer the Result object approach.

**Comment by peter-ahe-google** [comment]
My understanding is that the language team wants to simplify the error/warning/hint situation by turning all warnings into errors. This is being done under the assumption that our tools are resilient towards errors and recover well.

For this reason alone, I think the default should be to not throw on errors.

This requires us (front_end/fasta) to become better at recovering from errors: we should never pass through code that is malformed.

On example of this is a method like foo:

```
abstract class C {
  foo() async;
}
```

It's illegal for an abstract method to be marked async. So a client of the front_end should never see such a method. In this particular situation, I can see two ways of recovering:

1.

```
abstract class C {
  foo();
}
```

2.

```
abstract class C {
  foo() async {
    throw new CompileTimeError("An abstract method can't be marked 'async'.");
  }
}
```

In this particular case, I think option 2 is preferable, and the general lesson is that errors should be handled by keeping all the information in the original program but add additional nodes to ensure an error is produced at runtime.

This way we make it so that it is completely safe to ignore errors, but any client that doesn't want error recovery will be able to opt in to throwing eagerly.

I believe the default is important for our unit tests as well. I believe we want to ensure that aborting early is the uncommon thing in unit tests.

**Comment by sigmundch** [comment]
We talked a bit about this offline and should continue discussing it. I think we have different perspectives/understanding of what is the general plan for the language behind this. In particular, about:

> This is being done under the assumption that our tools are resilient towards errors and recover well.

My understanding was different: it really depended on the tool. Tools like analyzer have to be very resilient towards errors, but batch tools like ddc/dart2js or possibly even the vm, would instead fail early and simply not produce an output (or not run) unless you explicitly request them to do so.

**Comment by sigmundch** [comment]
note: make sure we allow no-main as a recoverable error

**Comment by kmillikin** [comment]
We have already improved this and will continue to do so on an ongoing basis.  There's no risk of us losing sight of the issue.
