### ISSUE TITLE
Dart2js fails on tests/language_2/generic_methods_generic_function_result_test.dart

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#30208]
Dart2js fails compiling tests/language_2/generic_methods_generic_function_result_test.dart

```
tests/language_2/generic_methods_generic_function_result_test.dart:21:33:
Error: Expected ')' before this.
  Expect.equals(123, list[1]<int>(100, 23));
                                ^
Error: Compilation failed.
```

**Comment by sigmundch** [comment]
Reassigning to front-end area, since this seems like the error here is in the parser for generic method syntax.

**Comment by peter-ahe-google** [comment]
We need to get a specification for this. Last time I heard about this, it was *considered* as a future extension, not actually on the table.

**Comment by crelier** [comment]
Yes, sorry, the test is using a generic function type as type argument in List in the return type, which is not allowed. See related issue #30207.

I will fix the test and revisit both issues as needed.

**Comment by crelier** [comment]
The test has been updated, but it still fails.

**Comment by peter-ahe-google** [comment]
Thank you, Regis!

**Comment by bwilkerson** [comment]
This issue might be impacted by https://dart-review.googlesource.com/c/sdk/+/12040.

**Comment by eernstg** [comment]
Peter, I know and understand that you strongly prefer an update to dartLangSpec.tex, but we haven't yet added this feature there.

However, we've had an informal specification which includes the relevant grammar productions at least since Oct 20, 2016 (see [here](https://github.com/dart-lang/sdk/issues/27501#issuecomment-255202036)):
```
argumentPart:
    typeArguments? arguments
selector:
    assignableSelector | argumentPart
```
which is by the way identical to the rules we have in the [current version](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generic-method-syntax.md) and in [Dart.g](https://github.com/dart-lang/sdk/blob/c2f11254c8d9829940a38dccb5f5b93a5d92b94c/docs/language/Dart.g#L811) today.

The issue #27501 where this syntax was introduced was closed on Nov 30, 2016.

Granted, we do need to make dartLangSpec.tex catch up with all the language changes, but is there anything else that we could do that would make you accept that a language feature has been introduced (as opposed to 'being considered as a future extension'), beyond the actions and documents that I already mentioned?

**Comment by sjindel-google** [comment]
I have added `language_2/generic_no_such_method_dispatcher_simple_test` to temporarily substitute for testing generic no such method errors in Kernel. We should remove that test when this is fixed.

**Comment by fishythefish** [comment]
Closing since this no longer seems to be an issue. Also deleting `language_2/generic_no_such_method_dispatcher_simple_test`.
