### ISSUE TITLE
VM Snapshot of project with native extensions

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#30209]
Feature request: it would be nice to create a source snapshot for code using native extensions, and rely on the packages file for locating the native libraries.

**Comment by jtmcdole** [comment]
@zanderso

**Comment by jtmcdole** [comment]
Note; it works for "script" snapshots if I log into the device and pass --snapshot.

**Comment by rmacnak-google** [comment]
When running from source, we resolve native extension imports relative to the importing library. When running from a snapshot, we reload native extensions the same way, remembering the URI of the importing library from the source program that generated the snapshot. This works out okay if the snapshot is being used as a cache, since the native extension hasn't moved. But this probably isn't a good policy if the snapshot is being used for deployment and ends up on a different machine at a new path. Another way to resolve this would be to locate native extensions relative to the snapshot instead of the original source library. Would that work for you?

**Comment by jtmcdole** [comment]
We found that by using --packages, we can update the .packages file to have file:// URIs to the native extensions and this gets around it.  The idea being that we want to deploy to multiple machine types, but run the same dart ui.

**Comment by natebosch** [comment]
How can I tell where it is looking for native extensions?

I've got a case where when I run from Dart sources a native extension is working - it tries to read it next to the Dart sources based on the `.packages` file, but when I run from a snapshot it is trying to read the file from some place under `/usr/` instead.

**Comment by mit-mit** [comment]
Closing: native extensions are deprecated are expected to be removed, see https://github.com/dart-lang/sdk/issues/45451.
