### ISSUE TITLE
Overriding a private property is possible without any warning

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/sdk#30218]
I think it is quite dangerous that you can override a private property and there are no warnings or errors or lints. Imagine if you are extending or mixing in a class from a library and happen to use a name that exists in the base class. 

https://dartpad.dartlang.org/7f44022aeb0ab5b31958eb23131951af
```
class StupidA {
  String _value = "Eh";
  
  // lexically this should always be "Eh", right? but it's really a shortcut for this._value
  // and since StupidB inherits this method, "this" ends up being the instance of StupidB
  // and thus ends up getting "Bee" instead
  String get value => _value; 
}

class StupidB extends StupidA {
  // silently overwrites _value in the base class, possibly by accident because we didn't
  // actually know that the base class has a _value field
  String _value = "Bee"; 
}

void main() {
  var b = new StupidB();
  print(b.value); // prints Bee
}
```

Here's another example with mixins:
https://dartpad.dartlang.org/498a0539d60b237314661adeabb54b9d
```
class ClassA {
  String _value = "Eh";
  
  String get value => _value;
}

class ClassB extends ClassA {
  String _value = "Bee";
}

class ClassC {
  String _value = "Sea";
}

class ClassD extends ClassA with ClassC { }

void main() {
  var b = new ClassB();
  print(b.value); // prints Bee
  
  var d = new ClassD();
  print(d.value); // prints Sea
}
```

I'm not sure exactly what it SHOULD do but it feels really dangerous that if you happen to have a private property that has the same name as a base class or mixin that it stomps it without warning.

**Comment by eernstg** [comment]
For the class case (`StupidA`, `StupidB`), this is working as intended. The 'private' access level in Dart is scoped to the library (as opposed to, say, Java, where `private` is scoped to the class and the default access level is scoped to the package). This means that `StupidB` is able to see and override `_value`, but only as long as it is in the same library. If a class `C` in a library L1 defines a member named `_value` and a subclass `D` of `C` in a different library also defines a `_value`, those two members are simply different, and no overriding takes place. You can think about this as if each library consistently renames all its private members to fresh names. This works as intended, even though it may cause some confusion that 'private' means different things in different languages.

The mixin case is more tricky, because it would be possible for two distinct private members with the same name to be brought together by a third party who uses both of them as mixins:
```dart
// In 'foo.dart'.
class M1 { int _value; ... }
class M2 { void _value() {} ... }

// In 'bar.dart'.
import 'foo.dart';
class C extends Whatever with M1, M2 { ... }
```
The class `C` brings together two unrelated declarations of `_value`. That matters even though `C` does not have access to any of the `_value` members. That mixin application would create a class `C` where `_value`-from-'foo.dart' has two conflicting declarations, and the implementations of methods inherited from `M1` and `M2` may require "their own declaration" of `_value` in order to work correctly. So that kind of conflict should be prevented. The Dart specification and tools have known problems in this area, and they are currently being fixed, e.g., #28809, #29751.
