### ISSUE TITLE
analyzer: `continue` to another case incorrectly warns about missing return statement

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/sdk#30259]
```dart
bool f(int x) {
  switch (x) {
    case 1:
      continue a;
    a:
    default:
      return true;
  }
}
```
yields the analyzer info _This function declares a return type of 'bool', but doesn't end with a return statement_.

**Comment by srawlins** [comment]
What a fun catch. For reference, the analyzer _does_ have a pretty good notion of whether a case exits:

```dart
// Analyzer understands that this always returns:
bool f(int x) {
  switch (x) {
    case 1:
      return false;
    default:
      return true;
  }
}

// And that this does _not_ always return:
bool f(int x) {
  switch (x) {
    case 0:
      print('hey');
      break;
    case 1:
      return false;
    default:
      return true;
  }
}
```

Just not a perfect notion 😄 .

**Comment by pschiffmann** [comment]
Now that you've brought this issue back to my mind, here's another one:

The analyzer warns about a missing `break` statement if a case ends with a function call, even though that function is annotated with `alwaysThrows`.

```dart
@alwaysThrows
void f() => throw new Exception('');

void g(int i) {
  switch (i) {
    case 0:
      f();
    case 1:
      break;
  }
}
```

I guess this is really low priority, so I guess I can just leave this here instead of opening a new issue :-)

**Comment by srawlins** [comment]
Haha, another good catch.

**Comment by srawlins** [comment]
On second glance, I think this is not permitted by the language:

#### 17.15 Continue

> Let _s<sub>c</sub>_ be a **continue** statement.

> If _s<sub>c</sub>_ is of the form **continue** _L;_, then let _s<sub>E</sub>_ be the the innermost labeled **do** (17.8), **for** (17.6) or **while** (17.7) statement or case clause with label _L_ enclosing _s<sub>c</sub>_.

> ...

> It is a compile-time error if no such statement or case clause _s<sub>E</sub>_ exists within the innermost function in which _s<sub>c</sub>_ occurs.

If I'm reading that right (I find that second sentence hard to read...), then label on a **continue** statement must refer to a label _that encloses the continue statement itself_.

@eernstg Can you weigh in on whether the [original example](https://github.com/dart-lang/sdk/issues/30259#issue-245561701) is valid, vis-a-vis the **continue** statement?

**Comment by eernstg** [comment]
> If I'm reading that right (I find that second sentence hard to read...), then label
> on a continue statement must refer to a label that encloses the continue statement itself.

The spec excerpt [here](https://github.com/dart-lang/sdk/issues/30259#issuecomment-411921415) isn't quite up to date, and the current text implies that the [initial example](https://github.com/dart-lang/sdk/issues/30259#issue-245561701) is OK:

```
Let $s_c$ be a \CONTINUE{} statement.
If $s_c$ is of the form \code{\CONTINUE{} $L$;},
then it is a compile-time error if $s_c$ is not enclosed in either an
\code{\AWAIT{} \FOR{}} (\ref{asynchronousFor-in}),
\DO{} (\ref{do}), \FOR{} (\ref{for}), or \WHILE{} (\ref{while})
statement labeled with $L$, or in a \SWITCH{} statement with a case clause
labeled with $L$, within the innermost function in which $s_c$ occurs.
```

The example is OK because `continue a` occurs such that there is an enclosing `switch` statement inside the innermost enclosing function, and (somewhere, anywhere) in that `switch` statement there is a case clause which is labeled with `a`.

So this issue would then be concerned with the analyzer diagnostic. However, the spec does not justify flagging this situation as an error. In the following snippet `$s$` is the last statement in the case clause (or the last statement in a block statement, as in `{ ... $s$ }`). :

```
It is a compile-time error if $s$ is not a \BREAK{}, \CONTINUE{}, \RETHROW{} or \RETURN{} statement
or an expression statement where the expression is a \THROW{} expression.
```

But in this case `$s$` _is_ a `continue` statement, so we should be OK. The analyzer emits an `Info` diagnostic, and the spec doesn't have any particular opinion about that, but I believe we can conclude that there is no need to emit that message for the original example.

**Comment by srawlins** [comment]
Thanks @eernstg!! (I only assigned you for the question.) I'll take a look into this, as I was spelunking into the DeadCode analyzer / ExitDetector.

**Comment by srawlins** [comment]
The Null Safety language feature includes new flow analysis which the analyzer uses for MISSING_RETURN and DEAD_CODE analysis. `dartanalyzer --enable-experiment=non-nullable` now reports no error on this code.
