### ISSUE TITLE
Analysis server doc/api.html has a huge amount of content on a single line

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#30292]
Right near the bottom of `pkg/analysis_server/doc/api.html` there is a huge amount of content on a single line:

https://github.com/dart-lang/sdk/blob/e81f653a3ed94c42b80341fbd7b5c530e849b9fc/pkg/analysis_server/doc/api.html#L4622

This means if you make a minor modification to `spec_input.html` and then regenerate the file that line is "changed" which is quite difficult to see from the diff (and may also complicate merge/rebases).

This probably isn't a big deal to the existing devs, but I'm hoping to make contributions that will involve re-generate these files and I would feel much better if I could see the diffs more easily! The rest of the file is formatted nicely, so I think this is just an oversight and not deliberate. Probably the fix is just inserting a newline somewhere in the codegen script.

(cc @bwilkerson)

**Comment by DanTup** [comment]
Actually, now I start looking at more of this file, there's quite a lot of this! The content that comes directly from the input file is formatted well (since the newlines/indenting are copied), it's just big chunks of generated code that are on long lines.

@bwilkerson would you accept a PR that just adds a bunch of `writeln` calls, or do you not care too much about this file since you can just review the input file and re-run the script to be sure what's in here?

**Comment by bwilkerson** [comment]
Personally, I don't worry about reviewing the generated files, because reviewing the input file has always been sufficient.

> It's easy enough to commit the result of regeneration as its own commit to avoid it being mixed with "real" changes but seems like a lack of newlines makes it unnecessarily noisy!

We actually have a test that will fail if the generated files don't agree with the input file, so we can't commit them separately. But it's easy enough to ignore the generated files while doing a code review.

What *is* sometimes useful is to make the changes to the input file, then get those reviewed, then run the generator before the actual commit to verify that everything generates cleanly (and the test doesn't break).
