### ISSUE TITLE
aot_snapshot_build_millis regression

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30317]
Flutter's `aot_snapshot_build_millis` benchmark regressed (from 14-15s to 16-17s) after we rolled the engine in https://github.com/flutter/flutter/pull/11456.

The mostly likely candidate that was included in that roll is https://github.com/flutter/engine/pull/3931, which rolled Dart from a83a69ff3eff845980308779cadbdb80cc03a603 to 1d384ca3ff4aa03bb83471c1c9591a77f1ccd530.

**Comment by rmacnak-google** [comment]
@yjbanov What mode does this benchmark run in?

**Comment by yjbanov** [comment]
`flutter build aot -v --release --no-pub --target-platform --android-arm`

https://github.com/flutter/flutter/blob/4b957bf02870c26ef5248e81a2ce5fd15efd281c/dev/devicelab/lib/tasks/perf_tests.dart#L193

**Comment by rmacnak-google** [comment]
Locally, the results are quite noisy, but averaging 20 runs I see a weak _improvement_ from 17155 to 16996 ms.

**Comment by alexmarkov** [comment]
According to dashboard, there are regressions on Mac (complex_layout_build) and Windows (flutter_gallery_win_build). There is no regression on Linux (flutter_gallery_build).

**Comment by alexmarkov** [comment]
Was able to reproduce the gen_snapshot slowdown reliably on MacBook.
Bisected regression to 8d6bc876f0eddb3cb248e112f4684616be82542c.

/cc @zanderso

**Comment by alexmarkov** [comment]
@zanderso @rmacnak-google @a-siva 

Ok, here is the full story.

Zach's change removed heuristic for running the 1st full GC early which caused regression of gen_snapshot execution time. Without this heuristics old gen grows larger (can be observed with --log-growth option) and number of objects to mark during the full GC is much higher.

Without this heuristic full GC times are 954ms, 1255ms, 501ms (2710ms total); with heuristic the full GC times are 626ms, 493ms, 168ms (1287ms total). This is the reason for regression of gen_snapshot execution time from 9.2s to 10.7s on my system.

The interesting thing is why full GC takes so long. During full GCs, 99% of the time is spent while marking objects ("roots/marking" column in --verbose-gc output). Marking is performed in 2 threads in parallel. The problem is that gen_snapshot is running on simulator and in simulator mode atomic operations are implemented with locking a global mutex ([simulator_arm.cc#L1096](https://github.com/dart-lang/sdk/blob/master/runtime/vm/simulator_arm.cc#L1096)). This results in a huge number of contentions between 2 marking threads, and on Mac (and probably Windows) a lot of time is spent in kernel. It seems like Linux scheduler is smart enough to prevent regression in this highly contended case, so there is no regression on Linux.

As an experiment, I made VM option --marker-tasks available in product mode and tried to run gen_snapshot with --marker-tasks=0 (without parallel marking). As the result, I execution time dropped to 8.0s with 1st GC heuristic and 8.2s without heuristic.

I can conclude that
1) the heuristic for running full GC for the 1st time is still useful, so restoring it is the right thing;
2) we can improve performance of gen_snapshot if we reconsider number of marker tasks in simulator mode and/or how atomic operations are implemented in simulator mode.

**Comment by zanderso** [comment]
@alexmarkov Thanks for the detailed analysis!
