### ISSUE TITLE
Meta-issue for discussion of the proposal to eliminate call methods

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30349]
This issue is to provide a forum for community discussion and feedback related to the proposal to eliminate the special treatment of call methods in Dart 2.0.

This entry will be updated when a proposal is available.

cc @munificent @eernstg @floitschG @lrhn

**Comment by brianegan** [comment]
Would there be any option to `implement` a `typedef` as a replacement? 

`call` is defo weird, but it can be useful. A type-safe alternative would be really cool.

**Comment by lrhn** [comment]
Implementing a function type would still make the object itself callable.
If we eliminate the magic `call`, then all objects will either be functions or non-callable objects, but none will be both. You can still tear off the original `call` method and pass that along instead of the object itself when you need a function.

One case that isn't covered is the combination of `noSuchMethod` with the `call` method to simulate functions of arbitrary interfaces. Those won't work well in a strong-mode/Dart 2 setting because the object doesn't actually implement those function types, and it would likely be a problem even in Dart 1 in checked mode.

**Comment by leafpetersen** [comment]
Closing this in favor of https://github.com/dart-lang/sdk/issues/32152
