### ISSUE TITLE
Meta-issue for discussion of the proposal to allow generic constructors

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30355]
This issue is to provide a forum for community discussion and feedback related to the proposal to allow constructors for classes to take additional generic arguments independent of the generic arguments of their class.

Currently strong mode allows generic functions and methods with a syntax like `int foo<T>(List <T> l) ...`, but constructors are not generic - they can only get the type parameters of the class.
An example case could be `List.mapped<S>(Iterable<S> source, E map(S value)) ...` where the type of the source doesn't depend on the type of the created list `List<E>`.

This entry will be updated when a proposal is available.

cc @munificent @eernstg @floitschG @lrhn

**Comment by brianegan** [comment]
I wrote in an issue for this, and I'm fully in favor! https://github.com/dart-lang/sdk/issues/30041

This creates a weird dichotomy between `factory` constructors and `static` constructors, because we sometimes need constructors with generics. It's confusing for both library consumers and adds complexity for folks learning the language: Why isn't there one true way for class construction?

Thanks for opening up the discussion and hearing our thoughts :)

**Comment by eernstg** [comment]
This feature was also requested in https://github.com/dart-lang/sdk/issues/31360.

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/26391 since it's older.
