### ISSUE TITLE
Please, clarify Stream.asBroadcastStream() behavior

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#30395]
The description for method dart:async:Stream.asBroadcastStream() reads:

> Stream&lt;T&gt; asBroadcastStream({
> void onListen(
> StreamSubscription&lt;T&gt; subscription
> ),
> void onCancel(
> StreamSubscription&lt;T&gt; subscription
> )
> })
> Returns a multi-subscription stream that produces the same events as this.
> 
> The returned stream will subscribe to this stream when its first subscriber is added, and will stay subscribed until this stream ends, or a callback cancels the subscription.
> 
> If onListen is provided, it is called with a subscription-like object that represents the underlying subscription to this stream. It is possible to pause, resume or cancel the subscription during the call to onListen. It is not possible to change the event handlers, including using StreamSubscription.asFuture.
> 
> If onCancel is provided, it is called in a similar way to onListen when the returned stream stops having listener. If it later gets a new listener, the onListen function is called again.
> 
> **Use the callbacks, for example, for pausing the underlying subscription while having no subscribers to prevent losing events, or canceling the subscription when there are no listeners**.

As follows from description, it is possible to unsubscribe the returned stream from the original stream via `onListen` or `onCancel` callbacks. Please, clarify the behavior of returned stream after it is unsubscribed. For example, if method `listen` is called, will it throw error or just send done event immediately or something else?

The following sample code demonstrates the current behavior:
```
import "dart:async";

main() {
  Stream s = new Stream.fromIterable([1,2,3]);
  Stream b = s.asBroadcastStream(onListen:(ss) {ss.cancel();});

  b.listen(print, onDone:() { print("done1");});
  b.listen(print, onDone:() { print("done2");});
  b.listen(print, onDone:() { print("done3");});
}
```
Output:

> done2
> done3

Please, note that `done1` is never printed, which is quite strange.

**Comment by lrhn** [comment]
> As follows from description, it is possible to unsubscribe the returned stream from the original stream via `onListen` or `onCancel` callbacks.

It's possible to *cancel* the subscription on the original stream. When that happens, no further events will occur on that subscription, and hence no further events will be emitted to subscriptions on the returned stream. 
So, when you cancel, there will be no further events emitted on the corresponding subscription.

What happens in the example is that the second and third listen are listening on a stream that knows it's done (because its internal state knows that the original stream was cancelled), but apparently it cannot tell the difference between being cancelled and having sent a done event, so it does what an already completed broadcast stream does - it sends a done event when you try to listen to it.

We should be consistent and not send any done events.

The usage here is not intended - cancelling the original in response to a listen is not really useful, so I have no problem with just stopping events without a "done" when it happens. The functionality is there so you can cancel or pause in response to not having any listeners. The `onListen` might not even need the argument, but it's there for consistency (and maybe so you can pause if you really want to).

**Comment by alsemenov** [comment]
I think that the first listener should receive done event. 
Let's rewrite the sample code for ease of reference:
```
import "dart:async";

main() {
  Stream s = new Stream.fromIterable([1,2,3]);
  Stream b = s.asBroadcastStream(onListen:(ss0) {ss0.cancel();});

  StreamSubscription ss1 = b.listen(print, onDone:() { print("done1");});
  StreamSubscription ss2 =  b.listen(print, onDone:() { print("done2");});
  StreamSubscription ss3 =  b.listen(print, onDone:() { print("done3");});
}
```
So we have two different stream subsciptions: `ss0` (between returned stream and original stream) and `ss1` (some external listener). When `ss0` is cancelled no further events are sent from the original stream. This is correct and expected behaviour. However `ss1` have not been canceled and waits for events. `ss1` has no relation to `ss0` and has no way to 'understand' that there will be no more events.
So I think it is a duty of the returned stream to inform all listeners about the situation by sending done event.

**Comment by lrhn** [comment]
As I said, it's not really important. In practice, you should never call `cancel` in response to `onListen`.
That said, it's probably safer to send the done then. It makes no difference when `source.cancel` is called when there is no listeners, which is the case we are actually supporting, but it is more consistent and easily explainable. It's simpler than disallowing `cancel` during `onListen`.

**Comment by lrhn** [comment]
I think the current behavior will stand, and the documentation should be updated to say that a cancel while there are listeners will leave those listeners without a done event.
