### ISSUE TITLE
Calling "optimize imports" should only process .dart files, not all files in the project

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#30414]
Select project in IDEA,
Click  'optimize imports'.

Plugins starts processing all files in the project including `.xml`, `.bin` and `.png`.
Should only process relevant like `.dart` and maybe `.yaml`

**Comment by alexander-doroshko** [comment]
@JFixby, this is definitely not a Dart SDK issue :). It is the IDE that processes all the files that you requested to process. 
For the `*.dart` files IDE delegates imports optimization to the Dart Analyzer, for other files IDE itself looks if 'optimize imports' action is applicable for the file and does whatever it thinks should be done.
Doesn't look like a bug, neither at the SDK nor at the IDE end. I suggest to close the issue.

**Comment by JFixby** [comment]
Ok, it just does the processing too long. Probably limiting file-types would improve the speed.

I post it here because it is always unclear whether an issue is related to a formatter, IDE, plugin, language or smth else.

**Comment by alexander-doroshko** [comment]
I believe that IDE does file-type filtering. In pseudo-code it is
```
for (each file in scope) {
  if (possibleToOptimizeImports(file.getType()) {
    doOptimize();
  }
}
```
It may take long because there are too many files or because there are too many Dart files. For each Dart file, IDE has to ask Analysis Server, wait for its answer and apply the change if any. I guess for thousands of Dart files it is waiting for the server answer what takes time. But anyway it is a single-time operation, isn't it? Once in a life you optimize imports and reformat all the files in the project and afterward you format / optimize only version control-changed files. To do it you use the change list in the IDE's Version Control tool window or simply mark the 'Optimize Imports' check box in the IDE's Commit dialog.
