### ISSUE TITLE
Consider making Stream two different classes

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30428]
_Names below are temporary and awful and someone can think of better ones._

My proposal:
* `AsyncIterator`: Pull-based, single-subscriber, buffering, either async or sync.
* `EventSource`:  Push-based, multi-subscriber, non-buffering, either async or sync.

The fact there are _4_ different types of stream controllers that can be created from `new StreamController` is very confusing to our users. I've seen 3-4 page docs floating internally just to explain the difference, and they are still misused - I think primarily because of naming.

Being more specific, i.e. `AsyncIterator`, makes it very clear what the purpose of the class is - in this case it's an `Iterable` data source with methods that execute asynchronously instead of synchronously. This is what I'd expect for say, `stdin`, reading a file on disk/on the network, etc.

And `EventSource` is exactly that - a way to register callbacks to get notified when an event occurs. OK to drop on the floor, basically.

**Comment by lrhn** [comment]
My personal favorite would be to remove broadcast streams and sync controllers completely. Then we are down to one kind of stream.

If you ever need something that you can listen to more than once, just provide more than one stream (say, a `Stream<MouseEvent> get onClick` that returns a new stream each time. 
Alternatively, allow some (still non-broadcast) streams to be listened to more than once, but each listener will be completely independent, as if they were listening on different streams. Basically make some streams *replayable* rather than multi-subscriber.

The iterator is harder to work with than a stream. You can already use the `StreamQueue` to wrap a stream, and I think it's much better than the old `StreamIterator` class (which tried to match the synchronous `Iterator` which is really a square-peg-round-hole exercise).

**Comment by zoechi** [comment]
> If you ever need something that you can listen to more than once, just provide more than one stream (say, a Stream<MouseEvent> get onClick that returns a new stream each time.

This would require to manage a list of still-listened-to streams in custom code, which seems quite inconvenient for such a widely used pattern. If another class like the mentioned `EventSource` is provided to cover that, it would be fine of course.

**Comment by lrhn** [comment]
No current plans to change the `Stream` API
