### ISSUE TITLE
Improve dart.bind and dart.fn in DDC

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30498]
Tearoffs seems to be fairly slow in DDC right now, with a fair bit of time spent in defineMemoizedGetter as called from dart.bind.  We should consider optimizing this code, and possibly caching tearoffs.

**Comment by jmesserly** [comment]
fyi: I am working on some improvements here.

**Comment by jmesserly** [comment]
I think the problem with `dart.fn` is we need to inline it (and remove the special case for `dynamic` functions) ... it's just setting the `[dart._runtimeType]` symbol, but it goes through 2 calls to get there.

Also we call `dart.fn` for top-level functions which is usually not necessary (similar to statics). Also we may be able to do some simple escape analysis for local functions (sadly we have to treat Iterable methods as escaping =\ ... perhaps we could have knowledge that Iterables from the core library are safe). In addition, we may also want to see if we can create the associated function type faster.

More radical ideas: encoding type info in the name and/or recoverable via `Function.prototype.toString` such as a comment. Basically, move the cost to when the RTTI is requested, rather than paying up front. This only works when we aren't closing over a generic type param, though, and it might be expensive.

**Comment by jmesserly** [comment]
This should be a fair bit better now. We should reopen if we see it again though.
