### ISSUE TITLE
Consider alternative or additional subtype caching policies in DDC

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30495]
We currently keep one monolithic subtype cache, and use it for all kinds of checks. It might be more efficient to keep small caches on instances or on types for specific kinds of checks.  The getter for the subtype cache map shows up hot in some profiles.

**Comment by jmesserly** [comment]
yeah, we can certainly save at least the first Map lookup. I'll see if I do something here

**Comment by jmesserly** [comment]
Also I noticed, we may want to change `addTypeTests` to avoid the extra level of nesting.

I think the new `TypeName.is` pattern replaces `dart.is` anyways, so we can just convert those helpers to work in terms of the current class. Then it becomes possible to assign the method instead of forwarding to it, saving 1 stack frame.

Of course some of the methods are doing `obj instanceof this` ... some quick checks seem to indicate that instanceof is pretty slow. We may want to put a property on the instance prototype for faster testing.

**Comment by jmesserly** [comment]
More investigation: the `instanceof` check is okay. While we can optimize that, for now it's the only thing saving us from problems with `dart.is`

`getReifiedType` looks like (one of) the things that's killing us. Working on a fix for that.

I'll see about optimizing that. No reason for it to be as slow as it currently is.

**Comment by jmesserly** [comment]
Okay, so I've improved the caching. However, the real issue is we need to use the TypeRep's more. Dispatching on the type is really powerful. We can quickly check the instance for the right `typeof` and get the reified type. Hitting `TypeRep.is` is way better than hitting `dart.is`

I'm going to optimize a few of the cases that are missing right now, in particular functions, native types, generics.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3003613002/
