### ISSUE TITLE
Consider alternative codegen patterns for arrays in DDC

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30496]
DDC currently handles polymorphic arrays by setting the prototype on array instances.  This is quite expensive in V8, and shows up quite hot in many profiles.  There is a suspicion that it might be making other array operations slower as well.

Consider and evaluate other approaches (e.g. wrapping, attaching types to the instance, etc).

**Comment by matanlurey** [comment]
Maybe `WeakMap`?

**Comment by jmesserly** [comment]
> Maybe WeakMap?

I don't think that will help, the issue with `JSArray<E>` is the reified generic `E`. We need to store that, at the very least. But we also need to make sure we can construct/cache the types that depend on `E` (such as for covariance checks, returning iterators, etc)

**Comment by jmesserly** [comment]
FYI @leafpetersen I am happy to try changing the code generator. It would be nice to see if wrapping helps before we go down that road, though.

**Comment by leafpetersen** [comment]
I'll take a whack at a wrapping implementation next week, see what it does.

**Comment by jmesserly** [comment]
disclaimer: arbitrary microbenchmark

- Current:
  list-literal-dynamic(RunTime): 1214.3290831815423 us.
  list-literal-typed(RunTime): 3342.237061769616 us.
- Wrapping:
  list-literal-dynamic(RunTime): 1737.619461337967 us.
  list-literal-typed(RunTime): 2276.4505119453925 us.
- Tagging the type:
  list-literal-dynamic(RunTime): 1327.1400132714002 us.
  list-literal-typed(RunTime): 1992.03187250996 us.

The benchmark includes a setter call, to test fetching the type (since this could be slightly slower in the "tagging" option). I don't think the tagging really has any downsides with the current approach, other than that I have no idea how we'll implement it in the code generator :)

I'm curious if the tagging approach would speed up our other generic classes. Not sure, though. It's more tricky to implement the general case.

**Comment by jmesserly** [comment]
Oh also here are the numbers from the benchmark you sent me @leafpetersen 

current: 1633 ms
wrapping: 392 ms
tagging: 324 ms

**Comment by leafpetersen** [comment]
Interesting.  It would be good to test array access operations with these three approaches as well.

**Comment by leafpetersen** [comment]
If you have a CL for these, there is one particular internal test that is highly constrained by array performance, and I'd be interested in trying them out on it.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3007113002/

**Comment by jmesserly** [comment]
https://codereview.chromium.org/3007113002/
That's for the wrapper approach. I had to get it to be fairly complete to be testable in real apps. It breaks assumptions in the compiler (because `JSArray<E>` is both a native and non-native type now, depending on whether `E == dynamic`) and in many of our JS snippets (`List<E>` is no longer a raw JS Array in most cases).

**Comment by jmesserly** [comment]
I'm waiting to hear back from @leafpetersen whether this CL was worth landing. It sounds like it didn't make a noticeable difference. In which case, we should close this issue.

**Comment by leafpetersen** [comment]
Need to run more experiments with this, I'll try to take a look tomorrow.

**Comment by jmesserly** [comment]
@leafpetersen FYI here's a new issue to change all of generics: https://github.com/dart-lang/sdk/issues/31003

**Comment by leafpetersen** [comment]
@jmesserly I think you were looking at broader changes here.  Should this stay open or is it superseded or obsolete?

**Comment by jmesserly** [comment]
yeah we can merge this into https://github.com/dart-lang/sdk/issues/31003 which will also fix this issue
