### ISSUE TITLE
Investigate performance of dart.mixin and copyProperties

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30500]
copyProperties (particularly as called from dart.mixin) shows up as hot.  We should see if we can optimize this code, and/or optimize our use of it.

**Comment by jmesserly** [comment]
Yeah I just noticed this looking at `dart.mixin` ... it's even worse than our normal setSignature. Working on a fix.

**Comment by jmesserly** [comment]
this should be improved somewhat by https://dart-review.googlesource.com/c/sdk/+/7442 ... I don't know whether to call this "fixed" or not though. We still need to copy things at setup time, due to how mixins work. I suspect "unrolling" mixin classes to successive applications would help this (as well as many other things: mixin constructor performance, stack traces, and generally reducing the bug farm around the `dart.mixin` helper trying to replicate many of the things that are normally done by _emitClassDeclaration at compile time.)

**Comment by leafpetersen** [comment]
This was mostly a reminder to myself to look at the code and see if there were obvious opportunities.  If you've taken a pass and feel like the code itself is adequate given the architecture I'd go ahead and close it.  If this becomes an issue, I can open a new issue around the higher level design.

**Comment by jmesserly** [comment]
We could unroll mixins at compile time, that may help performance at the cost of code size. I'm not sure, though. It would look something like:
```js
class Object$ListMixin extends core.Object {}
Object$ListMixin.prototype.add = ListMixin.prototype.add;
Object$ListMixin.prototype.addAll = ListMixin.prototype.addAll;
...
... set signatures for Object$ListMixin ...
...

class MyList extends Object$ListMixin {
  ...
}
```
It would almost certainly help runtime execution, because the constructor(s) for Object$ListMixin would be faster.

**Comment by jmesserly** [comment]
i'm fixing this as part of https://github.com/dart-lang/sdk/issues/31003

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/16337

**Comment by jmesserly** [comment]
that CL landed :)
