### ISSUE TITLE
Allow referencing a prefixed library identifier

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30518]
In AngularDart, we introduced a metadata list called `exports` to allow top-level and static constants, methods to be used directly in an HTML template, in a type-safe way. For example:

```dart
import 'dart:math' as math;

@Component(
  selector: 'comp',
  exports: const [
    math.max,
  ],
  template: 'The biggest number is: {{math.max(10, 20)}}', // Should output "20"
)
class Comp {}
```

Especially with internationalization, it's common to want to create a bunch of helper methods:

```dart
class MyMessages {
    static String get categories => Intl.message(
        'Categories', 
        desc: 'Label text for the title');
}
```

This runs against the Dart style guide (creating a `class` just for having static methods), but is the only declarative way a user can use our `exports: [...]` field:

```dart
import 'my_messages.dart' as my_messages;

@Component(
  selector: 'comp',
  exports: const [
    my_messages.MyMessages,
  ],
  template: '{my_messages.MyMessages.categories}',
)
class Comp {}
```

---

## Proposal

Allow the limited use of a prefixed library identifier, perhaps just as a `Symbol` for now:

```dart
// my_messages.dart
String get categories => Intl.message('Categories', desc: 'Label text for the title');
```

```dart
import 'my_messages.dart' as my_messages;

@Component(
  selector: 'comp',
  exports: const [
    my_messages, // <-- Same as #my_messages, but valid Dart.
  ],
  template: '{my_messages.categories}',
)
class Comp {}
```

/cc @hterkelsen

**Comment by lrhn** [comment]
Why don't you just *use* `#my_messages`? It's valid dart and means the same thing.

Is it because you don't get any checking that there actually is a `my_messages` declaration in scope?
Because ensuring that is a more general feature that I'd be quite a lot more inclined to consider :)

I would also like to have a way to write a symbol representing a program entity, so, say, `#!my_messages` would refer to the specific `my_messages` in scope, and it's an error if there isn't one (and refactoring can properly rename it).

That's a very different featrue, though. Just allowing the use of a prefix object as a value in ... some cases? Which? Always when used as a value? ... is not really a feature that's worth its own weight.

(Syntax needs more work, obviously.  Heck, I'd accept the entity-reference as the meaning of `#foo`, and require you to write `const Symbol('foo')` to get the arbitrary (and non-private only) symbol).

**Comment by zoechi** [comment]
I think with reflection availability being that limited, it would be a great feature.
Often I add metadata to classes so that I can get classes, constructors, methods, ... by name
without depending on reflection. 
Often I use code generation for this if its for a bigger set of classes, but also often I do it manually. 
I think the feature carries its weight.
