### ISSUE TITLE
Performance regressions (velocity tracker microbenchmark)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30521]
When we rolled the Flutter engine from fef7d827d6e22830ee6c88e8260f118a6b3fbcd9 to a246501917b8b77e856db253817ce7c2cc25b9c2 in https://github.com/flutter/flutter/pull/11643, which included rolling Dart from 734beef0624a9b246e892c95ca0c301c5d318331 to 491390eeaa7974f44a8931d10a899c39c0df8dda in https://github.com/flutter/engine/pull/3984, the following benchmarks regressed:

*Execution time benchmarks:*
microbenchmarks velocity_tracker_iteration

See also https://github.com/dart-lang/sdk/issues/30472

**Comment by rmacnak-google** [comment]
@dnunez02  Bisecting points to 4c471b3f2733529d1b263596550b9bae3b38d88c.

dart 0567e8cbd8bca7f6fd2c60251cabce6ede0e3227
3662.9, 3569.4, good
dart 4c471b3f2733529d1b263596550b9bae3b38d88c
3880.2, 3824.5, bad

**Comment by Hixie** [comment]
Any news on this? Is that a patch we can revert?

**Comment by Hixie** [comment]
(It's been almost ten days since the regression and we really don't like having known regressions in our tree because it makes catching additional regressions quite hard.)

**Comment by Hixie** [comment]
I think the revert above has now landed, rolled into the Flutter engine, and the engine rolled into Flutter, but this regression is still visible in Flutter's benchmarks.

**Comment by alexmarkov** [comment]
First, the range of dart-sdk revisions for the regression is https://github.com/dart-lang/sdk/commit/15258fd7a76cbf49a1b3eb86d8695602e792abb5 to https://github.com/dart-lang/sdk/commit/491390eeaa7974f44a8931d10a899c39c0df8dda (dart-sdk was rolled twice in the corresponding range of revisions of engine).

I double confirmed that the initial regression was caused by the commit https://github.com/dart-lang/sdk/commit/4c471b3f2733529d1b263596550b9bae3b38d88c (performance is good before that commit and regressed after the commit).

However, I found that the fix https://github.com/dart-lang/sdk/commit/e9d358921dddbee84c39c951220d5a844b097bb5, which reverted 2 commits (https://github.com/dart-lang/sdk/commit/4c471b3f2733529d1b263596550b9bae3b38d88c and the follow-up https://github.com/dart-lang/sdk/commit/78745901799347a9184689b01c92a039fbd76698), didn't bring the performance of regressed benchmark back (performance after the fix/revert is still bad and roughly the same as before fix).

Further investigation showed that in order to bring performance back, the commit https://github.com/dart-lang/sdk/commit/878a5f26537ec80a78a36707d46f54a2da4ab1ed should be also reverted: after reverting this commit on top of the dart-sdk tip the performance of the benchmark improves to pre-regression level.

@rmacnak-google

**Comment by rmacnak-google** [comment]
@a-siva 

https://github.com/dart-lang/sdk/commit/878a5f26537ec80a78a36707d46f54a2da4ab1ed is aimed at reducing pause times, and it is expected to somewhat decrease throughput. I recommend re-baselining this benchmark.

**Comment by Hixie** [comment]
The specific benchmark is on some pretty sensitive code (the velocity tracker), and it runs for a short amount of time (<4s). I'm reluctant to take a 5% hit on performance here, especially since the same drop isn't seen on any other benchmark.

**Comment by alexmarkov** [comment]
We figured out that the score of this benchmark, running in "flutter run --profile" mode, highly depends on the size of the new generation. It starts from 1MB and may or may not grow up to 16MB. The decision to grow the new gen is based on heuristic which is based on memory usage statistics.

Back in July, the commit https://github.com/dart-lang/sdk/commit/699f84f94141e405330ab1bd15dc7b58ba3067df broke the memory usage statistics. Since that commit, the new gen growth heuristic was basing on the incorrect memory usage statistics and it was making a decision to grow heap. As the result, benchmark score improved.

Then, commit https://github.com/dart-lang/sdk/commit/4c471b3f2733529d1b263596550b9bae3b38d88c fixed the memory usage statistics. The new gen was not growing and it was perceived as the regression, so this issue was filed.

Then, the heuristic was replaced with new one in the commit https://github.com/dart-lang/sdk/commit/878a5f26537ec80a78a36707d46f54a2da4ab1ed. The new heuristics was not looking at the broken statistics and was making decision to not grow heap anyway.

Then, commit https://github.com/dart-lang/sdk/commit/4c471b3f2733529d1b263596550b9bae3b38d88c which was fixing memory usage statistics was reverted in the https://github.com/dart-lang/sdk/commit/e9d358921dddbee84c39c951220d5a844b097bb5. However, the new heuristic was not growing new gen regardless of whether the memory usage statistics is broken or not. So the benchmark was still regressed even after this revert.

After looking into it, it seems like the right thing would be to fix memory usage statistics and use new heuristic. In such case, the benchmark would remain regressed - on the level before https://github.com/dart-lang/sdk/commit/699f84f94141e405330ab1bd15dc7b58ba3067df has broken memory usage statistics in July.

Separately, we may think about adding more heuristics to grow new gen.

Also, note that running this benchmark in release mode ('flutter run --release') results in a much better score, which varies much less depending on the new gen growth (because of the extra overhead in each garbage collection in profiling mode). So we may think about switching flutter micro-benchmarks to release mode.

**Comment by Hixie** [comment]
That makes a lot of sense. Thanks for the detailed explanation.

FWIW, in terms of Flutter, my impression is that our work is "bursty", in that there will be idle periods (see https://github.com/flutter/engine/pull/4012 for work on making better use of the idleness). In that environment, my guess would be that we should err on the side of allowing larger amounts of garbage to pile up while the code is running, on the assumption that we'll be able to clean it up during idle periods.

**Comment by Hixie** [comment]
In conclusion, I'll rebaseline the test.
