### ISSUE TITLE
Analyzer has problems with sub-packages (e.g. samples/cmdline/...) 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#30525]
For my l10ndart-package I provide a example in samples/cmdline:
https://github.com/MikeMitterer/dart-l10n-gettext

The project-structure is a valid dart structure.
The GUI-Analyzer (IntelliJ) shows an error-message, after pressing enter, the previously marked line becomes valid. Strange! Please check out my video:
[analyzer_bug.mp4.zip](https://github.com/dart-lang/sdk/files/1245090/analyzer_bug.mp4.zip)

As always with these Analyzer-Errors - den cmdline version works:
```bash
> cmdline $ dartanalyzer lib/cmdline.dart
Analyzing lib/cmdline.dart...
No issues found!
```
# Version information

- `IDEA 172.3968.1`
- `1.24.2`
- `IU-172.3968.1, JRE 1.8.0_152-release-915-b10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1920x1080, 1920x1080, 2560x1440`

**Comment by bwilkerson** [comment]
Having the error disappear when you pressed enter might be the IDE discarding diagnostics for the file until receiving new diagnostics from server (rather than server reporting no errors and then reporting errors again). I'd need the instrumentation log to know for sure.

Did the file `samples/cmdline/.packages` exist before server was started? (I'm wondering whether the absence of that file might be causing this behavior.)
