### ISSUE TITLE
Allow generic method type parameters in "is" and "as" expressions

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30530]
To minimize incompatibility between strong mode and the non-strong VM, analyzer currently reports a static error if you try to use a generic method's type parameter in an "is" or "as" expression:

```dart
bool f1<T>(Object o) => o is T;
```

With 2.0, generic method type parameters are reliably reified, so my understanding is this should be allowed.

cc @leafpetersen

**Comment by lrhn** [comment]
I agree. Strong mode now needs to be Dart 2 compatible, not Dart 1 compatible, where there is a difference.

**Comment by eernstg** [comment]
Right, we discussed these error messages in relation to the [informal specification of generic method syntax](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generic-method-syntax.md), but I'm surprised that the analyzer emits the same error message with `--strong`.

However, these messages are actually relevant for people who use strong mode static analysis and Dart 1.x dynamic semantics (e.g., because they deploy code generated by dart2js), so we actually ought to ensure that a complete switch to Dart 2 dynamic semantics has occurred (including deployed code, of course) before we remove that message.

**Comment by leafpetersen** [comment]
@asiva @crelier How far off of support for reified generic method parameters are we?

**Comment by bwilkerson** [comment]
> ... we actually ought to ensure that a complete switch to Dart 2 dynamic semantics has occurred ...

Is there an issue for tracking that? If so, I'd like to mark this issue as being blocked by it.

**Comment by crelier** [comment]
> @asiva @crelier How far off of support for reified generic method parameters are we?

Reification of generic functions is ready in the VM and is controlled by the flag --reify-generic-functions. However, the flag is still false by default, blocked by the zone cleanup change by Florian (and maybe other things) https://codereview.chromium.org/2893893002/

**Comment by leafpetersen** [comment]
This is fixed now.  https://dart-review.googlesource.com/c/29821/
