### ISSUE TITLE
VM: DateTime handles Daylight Saving Time incorrectly

### ISSUE THREAD

**Issue by weisong0** [dart-lang/sdk#30550]
In DartVM (timezone is in U.S.), the following code
```dart
void main() {
  // In the U.S., March 12, 2017, 2:00:00 am clocks were turned forward
  // 1 hour to Sunday, March 12, 2017, 3:00:00 am local daylight time instead.
  var a = new DateTime(2017, 3, 12, 2);
  print(a);
  print(a.millisecondsSinceEpoch);
}
```
Will output (which is incorrect):
```
2017-03-12 01:00:00.000
1489309200000
```

However In Dart2Js, the time is correct:
```
2017-03-12 03:00:00.000
1489312800000
```

**Comment by mehmetf** [comment]
This is a fairly critical issue for Flutter apps. Our production app got affected due to this today.

@floitschG could you please give us an estimated time to fix?

@sethladd @eseidelGoogle @Hixie FYI

**Comment by eseidelGoogle** [comment]
FYI @a-siva

**Comment by lrhn** [comment]
If you also print `a.timeZoneOffset`, it appears to print the same time zone in both case (-8h for `TZ=America/Los_Angeles`).
With the script `dp.dart`:
```dart
main(args) {
 for(var arg in args) {
   var d = DateTime.parse(arg);
   print(d);
   print(d.millisecondsSinceEpoch);
   print(d.timeZoneOffset);
   print("--");
 }
}
```
I get:
```
$ TZ=America/Los_Angeles dart dp.dart "2017-03-12 01:59:59.999" "2017-03-12 02:00:00.000" "2017-03-12 03:00:00.000"
2017-03-12 01:59:59.999
1489312799999
-8:00:00.000000
--
2017-03-12 01:00:00.000
1489309200000
-8:00:00.000000
--
2017-03-12 03:00:00.000
1489312800000
-7:00:00.000000
--
```
The first and third entry are one millisecond apart, as expected.

The `2:00:00.000` time does not exist (there was no 2 o'clock that day), so it seems the system is normalizing it in a surprising way, by subtracting one hour instead of adding one.

**Comment by floitschG** [comment]
I started working on this almost immediately, but ran into a limitation of iOS.
https://dart-review.googlesource.com/c/sdk/+/9300

I will try to finish it this week.

**Comment by floitschG** [comment]
Since the mentioned CL is not yet ready to land, I had a look at the current implementation, trying to figure out what went wrong. Initially this was a mystery: the code was implementing the ECMAScript spec (for compatibility) and yet Dart was having different results.
I finally found this line in [V8's sourcecode](https://github.com/v8/v8/blob/089dd7d2447d6eaf57c8ba6d8f37957f3a269777/src/date.h#L118):

> Literally following spec here leads to incorrect time computation at the points were we transition to and from DST.

New CL up: https://dart-review.googlesource.com/c/sdk/+/14044
It comes with the same issues as V8: it doesn't work correctly in timezones that don't have a 1 hour transition.

**Comment by mehmetf** [comment]
Thanks!

> It doesn't work correctly in timezones that don't have a 1 hour transition.

Could you please elaborate with an example? Do you mean it does not work for countries which do not follow DST? or for countries/regions where the transition is not 1 hour (but 1/2 hour or 2 hours)?

**Comment by floitschG** [comment]
It will have difficulties at the DST shift, if the savings is not an hour (30 minutes or 2 hours). Basically, this issue is not fixed for these countries.

**Comment by deadsoul44** [comment]
Is this problem still not solved?

**Comment by a-siva** [comment]
I tried it with the latest Dart version and it seems to print the correct value
```
sivalinuxmach[sdk]>out/DebugX64/dart /tmp/time.dart
2017-03-12 03:00:00.000
1489312800000
sivalinuxmach[sdk]>cat /tmp/time.dart
void main() {
  // In the U.S., March 12, 2017, 2:00:00 am clocks were turned forward
  // 1 hour to Sunday, March 12, 2017, 3:00:00 am local daylight time instead.
  var a = new DateTime(2017, 3, 12, 2);
  print(a);
  print(a.millisecondsSinceEpoch);
}

```

Closing issue.
