### ISSUE TITLE
DDC pulls in unused libraries

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/sdk#30562]
When working on projects that have server-side and client-side aspects, the dev compiler seems to always pull in the server-side portions, even though they are not referenced by the client app.

At first, I thought that the solution would be to split up the server and client into separate projects, but even when they are separated, the errors continue.

This project is an example: https://github.com/angel-example/poll

In addition to some strong-mode errors (which are my own fault), I see the following:

```
Error compiling dartdevc module:json_god|lib/lib__json_god.js

[error] Undefined class 'Schema'. (package:json_god/src/validation.dart, line 5, col 9)
[error] Undefined class 'Schema'. (package:json_god/src/validation.dart, line 10, col 44)

Please fix all errors before compiling (warnings are okay).
Error compiling dartdevc module:body_parser|lib/lib__body_parser.js

[error] Invalid override. The type of 'BodyParser.bind' ('(HttpRequest) → Stream<BodyParseResult>') isn't a subtype of 'StreamTransformer<List<int>, BodyParseResult>.bind' ('(Stream<List<int>>) → Stream<B
odyParseResult>'). (package:body_parser/src/body_parser.dart, line 8, col 3)
```

However, the `body_parser` package is only ever used with the server-side project (`poll_server`). My only guess is that I am using `angel_websocket` in the client, which includes support for both the server and the client. I'm still confused, because the files I am importing are browser-specific, and don't have any references to `body_parser`.

I'm not sure if this is a bug in the compiler, or somewhere else.

**Comment by jmesserly** [comment]
I'm guessing this is an issue with the build system including all files, even ones that aren't imported

**Comment by thosakwe** [comment]
@jmesserly Thanks for the response! Is there any way to exclude files from `pub build`/`serve` that aren't part of my project?

**Comment by jmesserly** [comment]
Hmmm not sure. @natebosch might know?

**Comment by natebosch** [comment]
@jakemac53 - do we have documentation on using excludes with DDC?

@thosakwe - are these files included in the root package (the package you build from) or from a dependency?

I thought the implicit modules should work such that we won't try to build code that you aren't transitively importing so hopefully it will be enough to just specify what to include/exclude from your package.

**Comment by jakemac53** [comment]
Is this only happening for `pub build` or is it happening for `pub serve` as well?

**Comment by jakemac53** [comment]
My assumption here is that it only fails in `pub build`, because it is trying to compile some other app you have under bin/tool/test/etc which isn't a web app. In that case you could just `pub build web` directly and that should resolve your issues.

Another possibility is that you are importing something from the `lib/src` of a package directly, but that is getting rolled up into a larger module (originating from some file under `lib`) which does contain server side code.

**Comment by thosakwe** [comment]
It's happening with `pub serve` as well.

Also, I'm fairly certain that the library doesn't import any server-side code; I wrote it: https://github.com/angel-dart/websocket/blob/master/lib/browser.dart

It works without DDC, just not sure what's going on.

**Comment by jakemac53** [comment]
Ok, it looks like the issue is the 2nd option I mentioned where you have an import to `package:angel_framework/src/http/angel_http_exception.dart` from `package:angel_client/angel_client.dart`.

That file gets rolled up into a more general shared module which depends on `json_god` among other things.

To fix this please move that file to `lib` so it becomes its own module, and that should resolve your issue.

**Comment by thosakwe** [comment]
Thanks!
