### ISSUE TITLE
Two buildbots attempt to run test.py with unrecognized '--failure-summary'

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30563]
Somehow two sharded buildbots (out of 14) try to run tests with ''--failure-summary", which fail because of that:
-  https://build.chromium.org/p/client.dart.fyi/builders/vm-kernel-precomp-linux-release-x64-5-6-be/builds/2398/steps/vm%20tests/logs/stdio
- https://build.chromium.org/p/client.dart.fyi/builders/vm-kernel-precomp-linux-debug-x64-1-8-be/builds/2253/steps/vm%20tests/logs/stdio

Compare to https://build.chromium.org/p/client.dart.fyi/builders/vm-kernel-precomp-linux-release-x64-4-6-be/builds/1282/steps/vm%20tests/logs/stdio, for example.

@whesse , is this something you can help with or can give pointers where the the config files that should be fixed please?

**Comment by whesse** [comment]
These two builders were failing because the "update scripts" step at the beginning were failing, so they are not getting the updated recipe that the other bots are getting.  I tried rebooting them, using the "graceful shutdown" button on the internal waterfall page (see gardening instructions).  If that doesn't work, I'll log in and force the update scripts step to run by hand.

**Comment by whesse** [comment]
Rebooting fixed one, and logging in, deleting directories, and running gclient sync (in the builder scripts directory, not the individual builder directory) fixed the other.
