### ISSUE TITLE
Migrate DDC to Kernel

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30570]
This is a tracking issue to move DDC over to Kernel / the new frontend infra.

@jmesserly @sigmundch @kmillikin @natebosch

**Comment by jmesserly** [comment]
Excellent!

I think these are the big things we'll need from the front end. Some of these may be done already:

- [ ] modular compilation (must not require source code for dependencies to compile a build target, instead some kind of built artifact can be supplied)
- [ ] type inference for expressions/statements (including local function return types)
- [ ] type inference for class members (infer types from overridden member)
- [ ] type checking for expressions/statements
- [ ] marking implicit downcasts
- [ ] override checking (including explicit `covariant` keyword)
- [ ] covariant generics support (marking parameters, inserting casts for unsafe returned function types)
- [ ] marking dynamic call sites

**Comment by kmillikin** [comment]
The current status is that this is all mostly there or being implemented now.

Kernel is (only) a typed IR, so the front end will have to perform type inference if it is capable of producing well-typed Kernel.  The checks required for type soundness are either represented explicitly in the Kernel code as checks, or else implicitly required by the operational semantics.

We will implement a typechecker so you can verify your input and also that the result of any transformations is still well typed.

**Comment by vsmenon** [comment]
Regarding modularity, mixins are something we may need to work out.  As I understand it, kernel lowers mixins away.  To do this, it needs code (i.e., method bodies for mixed in classes) from dependencies.  This is not present in summaries.

So, it sounds like we need to either:
(1) Add mixins to summaries (or the kernel equivalent).  Summaries are critical path on large builds, so we'll need to be careful if we're adding anything here.

(2) Don't lower mixins in Kernel.  Apply mixins at link-time / run-time.  This is what DDC does today.

**Comment by vsmenon** [comment]
BTW, on mixins, all things being equal, we'd prefer kernel lower them.  Doing them at runtime (re-wiring JS prototypes on the fly) has been pretty complicated.

**Comment by sigmundch** [comment]
The current APIs are designed to support option (2): we'd simply opt-out from applying the mixin transformation when compiling for ddc.

Option (1) might be trickier since we'd prefer not to have to add to summaries the methods for all classes that could possibly be used as mixins. If the language team decides to mark mixins explicitly in the future, that could make this option more viable.

We might have an option (3): Kevin did some work to make the mixin transformation more modular. His approach was that he would materialize the mixin application, but instead of coping the methods explicitly, he would include references to where the code would be copied from. Could this help address some of the complexities you hit today at run-time? What I'm thinking is that this could let you create the right prototype chain in advance rather than modifying them on the fly.

**Comment by scheglov** [comment]
About the option (3) for mixin transformation, is [this issue](https://github.com/dart-lang/sdk/issues/29881) fixed?

**Comment by sigmundch** [comment]
Good question for @kmillikin  - I recall he had planned to work on it, but I honestly don't know the status. Thanks for linking it here.

**Comment by stereotype441** [comment]
I checked off two items from @jmesserly's list; they are already implemented in front_end:
- type inference for expressions/statements (including local function return types, top-level/static fields)
- type inference for class members (infer types from overridden member)

I *think* I have probably done most of this item already:
- reified type information, including generic function/method type args and type parameter bounds, as well as all inferred type args

...but I'm not entirely sure what "and type parameter bounds" refers to, so it's possible that's not yet done.

I have already started on these and I'm hoping to have them completed in September:
- covariant generics support (marking parameters, inserting casts for unsafe returned function types)
- marking dynamic call sites

**Comment by jmesserly** [comment]
> ..but I'm not entirely sure what "and type parameter bounds" refers to, so it's possible that's not yet done.

@stereotype441 -- this means for a generic function or method like `T max<T extends num>(T x, T y)`, we need the bound for `T` (in this case, `num`) available at runtime. That supports dynamic invokes: `dynamic m = math.max; m<String>('a', 'b'); `. At runtime, we see if the type argument is a subtype of the type parameter bound.

(In general, it's slightly more complex than that, because bounds can be recursive. We first instantiate all of the type parameter bounds using the actual type arguments. Then we check that the actual type arguments are subtypes of the corresponding instantiated type bounds.)

**Comment by stereotype441** [comment]
@jmesserly Ok, thanks.  I haven't done any work on that, so I'll leave it unchecked.

**Comment by jmesserly** [comment]
tracking this in https://github.com/dart-lang/sdk/issues/31116
