### ISSUE TITLE
Fasta should report the appropriate diagnostic when the type arguments to a redirecting factory don't match.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#30579]
There are two cases:

* The new expression can use the wrong number of type arguments, and
* The redirecting body can  use the wrong number of type arguments.

```dart
class C<T> {
  factory C() = D<String>; // Should be two arguments here.
}

class D<T, S> implements C {
  D();
}

main() {
  new C<String, String>(); // Should be one argument here.
}
```

**Comment by peter-ahe-google** [comment]
To be clear: @stefantsov is stating that one of the cases in the test above are handled correctly. This means that there's still another problem left to fix.

**Comment by peter-ahe-google** [comment]
@stefantsov thanks for checking :-)

**Comment by dhil** [comment]
I can potentially fix the issue with factories as I have to inspect the type parameters and arguments in order to fix #32988.

**Comment by dhil** [comment]
My WIP [CL 74580](https://dart-review.googlesource.com/c/sdk/+/74580/1) resolves the second part of this issues
```
$ fasta compile --strong bug.dart
bug.dart:2:17: Error: Expected 2 type arguments.
  factory C() = D<String>; // Should be two arguments here.
...
```

Though, I have implemented a little "hack" to remain compatible with the analyzer, since it happily accepts
```dart
class A {
  factory A() = B;
}
class B<T> implements A {
  B();
}
```
That is if all types arguments are omitted, then we substitute "dynamic" for every type variable (that seems to be what the analyzer is doing). I have asked the language team whether it even should be allowed to omit type arguments.

**Comment by eernstg** [comment]
Drive by comment: The way Dart 2 provides missing type arguments in the case where there is no information which can be used during inference is via ['instantiate-to-bound'](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md). This basically means that we will use the declared bound rather than `dynamic` (but we'll still use `dynamic` when no bounds are declared), and we'll run a certain iterative algorithm to come up with suitable values for more tricky cases.

**Comment by dhil** [comment]
@eernstg Thanks! I suppose neither of my test programs declared any bounds.

**Comment by dhil** [comment]
As of [de984e5](https://github.com/dart-lang/sdk/commit/de984e58cbe29a13c078e20ee992f006ad33c891) the second case of this issue has been resolved.
