### ISSUE TITLE
Analyzer strong mode doesn't take into account @proxy annotation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#30573]
```dart
@proxy
class C {
}

main() {
  C c = new C();
  try{
    c.m;
  } on NoSuchMethodError {
    print("Ok");
  };
}
```
The code above produces no issues in dartanalyzer, but in a strong mode it reports an error   `error - The getter 'm' isn't defined for the class 'C'`

dartanalyzer version 1.25.0-dev.11.0

**Comment by bwilkerson** [comment]
That's actually working as intended. The purpose of the `@proxy` annotation is to say "the members of this class will be implemented in noSuchMethod, so don't complain when you can't statically locate the members."

**Comment by sgrekhov** [comment]
@bwilkerson, please clarify why this is as intended? As you said idea is "don't complain when you can't statically locate the members". But we have an error in a strong mode here!

If you meant that this is ok becouse class C doen't override noSuchMethod(), then it isn't the case. Analyzer strong mode produces an error with the overriden noSuchMethod() as well

**Comment by bwilkerson** [comment]
Sorry! I didn't read the original report carefully enough.

I don't actually know what's intended for strong mode. In Dart 1.0 the type system isn't sound, so it makes sense to have ways to get around static errors (because those errors can sometimes be wrong). I believe that in Dart 2.0 the type system will be sound and the `@proxy` annotation will be removed. Strong mode is a partial step from 1.0 to 2.0; it's type system mostly sound, but I don't know that anyone made a conscious decision about how the `@proxy` annotation ought to work. Hence, I'm not sure whether or not this is a bug.

**Comment by lrhn** [comment]
The `@proxy` annotation is removed in Dart 2.
It's fair game for strong mode to not support it since strong mode is now just a preliminary version of Dart 2. If it's not supported by now, there is no reason to waste any work on doing it.

**Comment by bwilkerson** [comment]
Good to know, thanks!
