### ISSUE TITLE
Fasta does not type variables introduced by auxiliary let-nodes in strong mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30582]
When I compile the code below with Fasta and `--strong-mode`:

```dart
main() {
   var foo = [1, 2, 3];
   print(--foo[0]);
}
```

```console
$ ./pkg/front_end/tool/fasta compile -o t/t.dart.dill --strong-mode --platform=./out/ReleaseX64/patched_sdk/platform.dill t/t.dart
```

I get the following Kernel out:

```dart
     core::List<core::int> foo = <core::int>[1, 2, 3];
     core::print(let final dynamic #t1 = foo in 
                 let final dynamic #t2 = 0   in
                 let final dynamic #t3 = #t1.{core::List::[]}(#t2).{core::num::-}(1) in
                 let final dynamic #t4 = #t1.{core::List::[]=}(#t2, #t3) in
                 #t3);
```

Notice that `foo` got inferred correctly, but all other artificial variables like `#t1` are completely untyped. This seems suboptimal - especially because `#t1.[]` has a resolved interface target. 

This also breaks `Expression.getStaticTypeAsInstanceOf` method - if you invoke it on `#t1.{core::List::[]}(#t2).{core::num::-}(1)` node it will report an error that  'dynamic is not a subtype of List'

I think this demonstrates that 

- Kernel needs to have a specification describing what does it mean for Kernel to be in strong mode;
- Kernel needs a visitor that would verify that Kernel AST is consistently typed;
- Fasta needs to assign types to these auxiliary variables just like it assigns them to user declared variables;

/cc @kmillikin @stereotype441 @sigmundch

**Comment by stereotype441** [comment]
Agreed, this is a bad situation.  I'll assign the bug to myself, and fix the front end to assign types properly in this particular use case.  And I'll try to find and fix other places where front_end fails to assign a type to auxiliary let-variables.

In the long run it would be very nice indeed to have a kernel visitor that verifies consistent typing, because there's always a risk that we'll miss something.  I believe @kmillikin has a task he's working on that should do this ("kernel type verification")--is that correct, Kevin?
