### ISSUE TITLE
language/conditional_import tests fail on dart2js-drt

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#30587]
Failing tests:
`language/conditional_import_string_test`
`language/conditional_import_test`

Reproduction: `python tools/test.py -m release -c dart2js -r drt language/conditional_import`

**Comment by sigmundch** [comment]
@karlklose - could you share the URL of the bot log where it happened?

This is passing for me locally, so I wonder if it was a flaky issue on the test or on the infrastructure by any chance. Depending on how flaky it appears, I may be inclined to undo the status changes rather than marking it flaky.

**Comment by karlklose** [comment]
@sigmundch Today it does not reproduce, but yesterday I could reproduce it locally. Maybe it has to do with the version of drt?

**Comment by sigmundch** [comment]
It's quite possible, but I'm also not sure.

I'll undo the .status change to make the bots green again, but let me know if you happen to see it again.
