### ISSUE TITLE
AOT snapshot size regression with --preview-dart-2 on Flutter Gallery. 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30616]
@aam reports that AOT snapshot size is 300K larger

**Comment by askeksa-google** [comment]
The kernel snapshot contained the kernel data for all function bodies. Omitting this took care of most of the extra size of the Isolate data:

- Source snapshot size: 2632473
- Kernel snapshot size before: 5599063
- Kernel snapshot size after: 2744877

This still leaves the 300k extra instructions (7503920 vs 7208448). It seems this difference is mainly due to the kernel snapshot containing more functions (19855 vs 19011).

There are many small differences between the function sets. One big difference is in the number of anonymous closure functions (1917 vs 1115). The majority of these seem to be coming from asserts in initializer lists. Every assert in an initializer list produces a closure when going through kernel.

**Comment by aam** [comment]
With today's update of flutter, the Dart change reached flutter benchmarks and you can see nice impact it made there: https://flutter-dashboard.appspot.com/benchmarks.html

**Comment by a-siva** [comment]
@askeksa-google  The snapshot size as reported above is close to the size reported from the source based snapshot, can we close this issue?

**Comment by askeksa-google** [comment]
Yes. The main remaining difference is the 300k extra instructions, which seem to be mainly due to asserts in initializers. There is a separate issue for that: https://github.com/dart-lang/sdk/issues/30914
