### ISSUE TITLE
Analyzer not showing an error in strong mode.

### ISSUE THREAD

**Issue by marcinsydor** [dart-lang/sdk#30613]
I have two classes:
```
class A {
  String name;
}
class B extends A {
}
```
Than initilize objects:
```
void main() {
  var o = new B();
  o = new A();
}
```

As I expect the analyzer showing me an error.
`error: A value of type 'A' can't be assigned to a variable of type 'B'.`

When I set a name:
```
void main() {
  var o = new B();
  o = new A()
    ..name = 'My Name';
}
```
The error gone.

It looks like a bug in the analyzer to me.

My environment:
Mac OS: 10.12.4
WebStorm: 2017.2.3
Dart VM: 1.24.2

**Comment by zoechi** [comment]
![image](https://user-images.githubusercontent.com/405837/30019263-39d20bcc-9160-11e7-9b89-9c54b6e82feb.png)

It seems you haven't enabled strong mode

https://dartpad.dartlang.org/a8e35a0705c7a45345ba2165235d61ac

![image](https://user-images.githubusercontent.com/405837/30019337-7aae4412-9160-11e7-9feb-62d33d538465.png)

Strong mode will be the default in Dart 2.0

See also https://www.dartlang.org/guides/language/analysis-options

**Comment by marcinsydor** [comment]
I've enabled strong mode in pubs pubspec.yaml file.

Try
void main() {
  var o = new B();
  o = new A()
    ..name = 'My Name';
}
It does not showing the error.

**Comment by floitschG** [comment]
Dart has implicit downcasts.

Since `A` is a superclass of `B` Dart inserts an implicit downcast check.

DDC seems to have some additional checks to catch obvious errors (like assigning a `new` that doesn't go to a factory constructor), but doesn't do this for `..` (cascades).

**Comment by stereotype441** [comment]
As @floitschG explained, implicit downcasts are usually allowed in Dart, which is why the second example in the bug report is allowed.  However, if the RHS of the assignment has a sufficiently simple form, the compiler know the *exact type* of the RHS, so it knows whether the implicit downcast would fail.  When this happens, it goes ahead and issues a compile-time error to help you catch mistakes earlier.  Unfortunately, there's no 100% reliable algorithm for determining the exact type of the RHS at compile-time, so when the expression is sufficiently complex, we don't try.  Currently, cascade expressions are deemed "too complex", which is why adding `..name = 'My Name'` causes the compile-time error to go away.

We could certainly make the "exact type" analysis more sophisticated so that it handled cascade expressions.  But it's probably not worth the effort, because when we introduce NNBD, implicit downcasts are going to be removed from the language entirely, and so "exact type" analysis won't be necessary.  Considering that we're actively working on NNBD right now, it seems like there's not a lot of benefit to beefing up a stage of analysis that's going to go away soon.

So I'm closing this bug.
