### ISSUE TITLE
Merge `Stream.map` and `Stream.asyncMap`, use `FutureOr`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#30658]
`asyncMap` already handles either synchronous or asynchronous work but it's signature isn't as useful as `map` in Strong Mode.

I think we could have a single method `Stream<S> map<S>(FutureOr<S>  Function(T) convert)`

**Comment by lrhn** [comment]
It's possible, and not entirely unreasonable.
It will make the code less efficient in the synchronous case (it has to check each return value to see if it's an `S` or not), and have to pick one of the possible strategies for waiting on futures–but that's what we do for `asyncMap` now anyway, so it's not a big difference.

**Comment by floitschG** [comment]
The signature of `asyncMap` is already `Stream<E> asyncMap<E>(FutureOr<E> convert(T event))`.

In theory, you could always call `asyncMap` instead of `map` and it should work. It's often nicer to think of `map` as something that converts directly (aside from the fact that it might be more efficient), so the separation between `map` and `asyncMap` makes sense (even if `asyncMap` really covers `map`).
