### ISSUE TITLE
Variable Type differs at 'Closures' for Idea plugin and DartPad

### ISSUE THREAD

**Issue by salmansamie** [dart-lang/sdk#30679]
While learning Dart I came by this "closure" issue where the same code outputs two different Data Types. I initially thought it was the Dart plugin issue. 

But when contacted the Dart Plugin team at https://youtrack.jetbrains.com/issue/WEB-28706#u=1505198646728, I was clarified of the concepts where dart2js and DartVM processing may differ. But the question is, why will the variable type differ as such? Shall we have a fix to this?
@devoncarew  @lukechurch 

- How to reproduce?
 Run the following code in Intellij IDEA and DartPad:

 ```
   makeAdder(int x) => (int y) => x / y;

   void main() {
     var add2 = makeAdder(15);
     var result = add2(3);
     print(result);
     print(result.runtimeType);
   }
 ```

- What's the issue?
 The outputs are different. 

> DartPad gives:

```
  5
  int 
```
   

> but the IDE gives:

```
  5.0
  double
```

- What's expected? 
Outputs are expected to be the same.

**Comment by eernstg** [comment]
As Günter mentioned in [his comment](https://youtrack.jetbrains.com/issue/WEB-28706#comment=27-2413779) on the 'Variable Type differs at 'Closures' from that of the DartPad' issue, the behavior you mention is caused by the treatment of numeric types when compiling to JavaScript vs. when running on the Dart virtual machine. In particular, it has nothing to do with closures.

The [documentation of the `int` class](https://api.dartlang.org/stable/1.24.2/dart-core/int-class.html) explains it like this:
```
When compiling to JavaScript, integers are implemented as JavaScript numbers. When
compiling to JavaScript, integers are therefore restricted to 53 significant bits because
all JavaScript numbers are double-precision floating point values. The behavior of the
operators and methods in the int class therefore sometimes differs between the Dart VM
and Dart code compiled to JavaScript.
```
It would have been wonderful to have full support for Dart numeric types on the web, but the performance hit makes it an unrealistic choice to emulate true Dart numerics in JavaScript.

Note also the treatment of bit operations as described in [this comment on issue #25493](https://github.com/dart-lang/sdk/issues/25493#issuecomment-171890267).

**Comment by salmansamie** [comment]
Thanks for pointing this out.
