### ISSUE TITLE
incorrect type inference for const-constructor invocations

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30677]
When I compile this code with Fasta + strong mode

```dart 
class Foo<T> {
  Foo<T> get empty => const Bar();
}

class Bar<T> implements Foo<T> {
  const Bar();
}
```

I get 

```
  class Foo<T extends core::Object> extends core::Object {
    default constructor •() → void
      : super core::Object::•()
      ;
    get empty() → z::Foo<z::Foo::T>
      return const z::Bar::•<z::Foo::T>();
  }
  class Bar<T extends core::Object> extends core::Object implements z::Foo<z::Bar::T> {
    const constructor •() → void
      : super core::Object::•()
      ;
  }
```

`const z::Bar::•<z::Foo::T>` is an incorrect type. Const-constructors should not accept non const type arguments.

According to @floitschG this should be `const z::Bar<Null>()` instead.

**Comment by stereotype441** [comment]
I agree that this is problematic, and that inferring `const z::Bar<Null>()` instead makes sense.

But I need to implement this in a general way, and I'm not sure what the general rule is.  I don't see anything in https://github.com/dart-lang/sdk/blob/2cf8040c9e047518e6673c6b92a8e917c3ff5ff3/docs/language/informal/local-inference.md explaining how to deal with const constructor invocations.

Speculation: when inferring the type of a const constructor invocation, any TypeParameterType appearing in the context should be replaced with either `Null` or `Object` (depending whether it appears in a covariant or contravariant position within the context).

@floitschG, @leafpetersen, @jmesserly, does that seem reasonable to you?  Note that I can't take any guidance from the analyzer implementation because it has the same bug.

**Comment by jmesserly** [comment]
> does that seem reasonable to you?

yup!

>Note that I can't take any guidance from the analyzer implementation because it has the same bug.

(FWIW, it was correct behavior for strong mode when we originally implemented it :) ... but the design has changed since then.)

**Comment by stereotype441** [comment]
@jmesserly Thanks.  Working on a fix.

**Comment by leafpetersen** [comment]
Agree with the resolution, see here for more discussion:  https://github.com/dart-lang/sdk/issues/28685

It sounds like I can go ahead and close #28685 now?

**Comment by stereotype441** [comment]
Note that I only applied the fix to the new front end.  Maybe keep #28685 open to document the fact that analyzer still has the old behavior?
