### ISSUE TITLE
Improve the `Type` class

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30717]
Add
`new Type.of(o)`
`Type.isSubTypeOf(Type)`
`Type.isSuperTypeOf(Type)`
`Type.isTypeOf(o, allowSubTyping: true)` ?  (`num.isTypeOf(5)` -> true)

**Comment by lrhn** [comment]
Consider whether it's worth making it `class Type<T>`. It makes some things easier, like contraining the type objects:
```dart
abstract class Registry {
   void put<T>(Type<T> type, T instance);
   T get<T>(Type<T> type);
}
```
The type of the expression `int` would be `Type<int>`, both static and runtime.
You could then also create a `new Type<List<int>>()` directly.

Consider making `Type.of` static instead of a constructor (not real need for being a constructor, but then, with optional new, nothing really does), and typing it as `Type<T> of<T>(T object)`. (That works as a constructor too).

I would remove the "allowSubtyping" for `isTypeOf` and always do proper instance-of checks. If you need type equality, you can do `type == Type.of(o)`.

**Comment by matanlurey** [comment]
I'd be curious what the effect on `dart2js` would be. Does this mean `Type` would have to retain much more reified information in order to support this methods? If so, does @rakudrama think this could be accurately tree-shaken?

I'd be worried that this just automatically becomes an anti-pattern if it is discovered that it adds dart2js code size. Unless this solves some huge issue/ask for Flutter that I don't know about?

**Comment by floitschG** [comment]
Should not have any noticeable effect on dart2js. It already has all the information.

**Comment by matanlurey** [comment]
But does that limit how much information dart2js can remove, I mean?

I don't see any reason to retain RTTI for determining if two arbitrary types are super/sub.

**Comment by floitschG** [comment]
This kind of RTTI is already available, since dart2js needs to build up the prototype chains.

**Comment by matanlurey** [comment]
I was under the (wrong?) impression that say, given the following structure:

```dart
class A {
  foo();
}

class B implements A {
  foo() {}
}
```

That the prototype-chain would not have to include `A` if `is A` never occurs in the program

**Comment by floitschG** [comment]
If `A` never occurs in the program, then you can't ask for a relationship with `B` either.

Someone would need to explicitly reference `A` somewhere.

Note, that we don't give any way to walk hierarchies. This means that tree-shaken classes still are tree-shaken. When a user referenced `A` (as in `var a = A`) then it isn't tree-shaken.

**Comment by lrhn** [comment]
We're not planning on doing this, for the usual reasons of it making it harder to tree-shake types, and you should be using type parameters instead of `Type` objects.
