### ISSUE TITLE
A broadcast Stream transformation maintains the next stream is a broadcast stream

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30723]
The current `isBroadcast` flag is true, when the stream is a broadcast stream, or when a broadcast stream was transformed.

The documentation currently reads:
> On either kind of stream, stream transformations, such as [where] and [skip], return the same type of stream as the one the method was called on, unless otherwise noted.

This makes it sound, like the returned stream is a broadcast stream. However, multiple `listen` calls to the transformed stream should just forward the subscription to the original stream.

We should either update the documentation, or remove `isBroadcast` (or replace it with something more useful).

**Comment by natebosch** [comment]
I'm not quite sure I understand the issue with documentation.

The returned stream is indeed a broadcast stream right? The docs for `.transform()` already call out that whether the result is broadcast or not depends on the `StreamTransformer` implementation.

@lrhn - do you see anything to do here?

**Comment by lrhn** [comment]
I'm also not sure what the issue here is. We were planning on changing some Stream behavior for Dart 2, including that stream operations would be lazy, like iterable operations, and pass all listen calls through to the original stream (so each listener gets its own operation, instead of creating a new broadcast stream that gets the transformed events only once).
We didn't change that, so I guess this issue doesn't apply anyway.
