### ISSUE TITLE
Consider whether we need both `reduce` and `fold` on `Iterable`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30746]
I can never remember which is which and need to look them up every time I use them.
Is there any way we can combine these two into one? It's probably not possible to make it useful with current type inference rules, but let's try.

**Comment by rakudrama** [comment]
Please keep them separate.

Not only do they have different type, they have different behaviour on singleton collections.
e.g. `[1].reduce((a, b) => throw a)` does not throw.

If you try to merge them, you will end up with something like Common Lisp's REDUCE function which has several named optional arguments. Even with better inference rules, the type also becomes much more complicated (the return type is now the type of the Iterable *or* the type of the combiner), and the type becomes data-dependent.

**Comment by ds84182** [comment]
I say keep both.

There are cases where `fold` comes in handy (e.g. taking a `List<List<int>>` and turning it into a `Set<int>` with `list.fold(new Set<int>(), (a, b) => a..addAll(b))`). 

There are also cases where `reduce` comes in handy (e.g. finding the largest or smallest value in a list with `list.reduce((a, b) => a > b ? a : b)`.

Reduce also throws if the given list is empty, which is useful when you reduce on something that is empty (otherwise you'd return null, which could cause nulls to propagate through a program and break things).

On the other hand, fold is a no-op if the list is empty (it just returns the object passed in, which is great when you know the list can potentially be empty and you want to return a value).

**Comment by lrhn** [comment]
I don't want to remove functionality, just see if there is a better way to expose it that doesn't require you to distinguish them by names that are not self-explanatory.
There might not be - a single method with multiple modes is not an improvement, and it is likely impossible to type well in strong mode.

**Comment by lrhn** [comment]
There probably is no good way to change this that isn't more costly than having me look up the functions when I use them. Let's not do anything.
