### ISSUE TITLE
Add `unmodifiable` bool flag to `Iterable.toList`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30748]
Currently we can create a growable or fixed-length list with `Itearable.toList`. Consider making it possible to make an unmodifiable list as well.

**Comment by rakudrama** [comment]
It feels a bit awkward to allow nonsense API calls like `.toList(growable: true, unmodifiable: true)`.
Does every `toList` implementation need to check and throw on this case?

For the purpose of whole program type analysis in dart2js, it is preferable if as many methods as possible return objects of a single type. Then the type becomes less data-dependent and more optimization opportunities are found. So .toList(), .toFixedList(), .toUnmodifiableList() would help produce better optimized code. Since we already have **growable:**, I don't think **unmodifiable:** makes things worse for type analysis.

Would  `new List<T>.unmodifiable(...).toList(unmodifiable: true)` be defined to return the receiver?
This would be valuable in freezing data without creating copies.

**Comment by matanlurey** [comment]
I personally liked @rakudrama suggestion on another thread about different methods:

```dart
abstract class Iterable<T> {
  List<T> toList();
  List<T> toFixedList();
  List<T> toUnmodifiableList();
}
```

That being said, unmodifiable lists aren't used that often because of the performance overhead of having to wrap a list, so I don't know if making it simpler to create one is a great pattern for Dart.

**Comment by lrhn** [comment]
Changing the `Iterable` API is a non-starter at this point.
