### ISSUE TITLE
Analyzer: New functions types and inference failures

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30758]
DartPad shows this nicely (make sure to enable `Strong Mode` to see the errors):
https://dartpad.dartlang.org/039f886163201de475206b011b71b540

This also occurs as latest as:
```sh
$ dart --version
> Dart VM version: 1.25.0-dev.16.4 (Wed Sep 13 01:47:12 2017) on "macos_x64"
```

## New function type (inline)

**Incorrectly infers as `dynamic`**

```dart
class GraphVisitor1 {
	T _find<T>(T Function<T>(int example) fn) => null;
  
  void doThing() {
    _find((e) => e.abs());
    // ^^^^^ No auto-complete, 'e' is inferred as dynamic by the analyzer.
  }
}
```

## Old function type

**Correctly infers as `int`**

```dart
class GraphVisitor2 {
  void _find(void fn(int example)) => null;
  
  void doThing() {
    _find((e) => e.abs());
    // ^^^^^ Auto-complete, yay! 'e' is inferred as int.
  }
}
```

## Old typedef

**Correctly infers as `int`**

```dart
typedef void OnIntA(int example);

class GraphVisitor3 {
  void _find(OnIntA fn) => null;
  
  void doThing() {
    _find((e) => e.abs());
    // ^^^^^ Auto-complete, yay! 'e' is inferred as int.
  }
}
```

## New typedef

**Incorrectly infers as `dynamic`**

```dart
typedef OnIntB = T Function<T>(int example);

class GraphVisitor4 {
  T _find<T>(OnIntB fn) => null;
  
  void doThing() {
    _find((e) => e.abs());
    // ^^^^^ No auto-complete, 'e' is inferred as dynamic by the analyzer.
  }
}
```

**Comment by jmesserly** [comment]
So this is working as intended. The "new" examples are not equivalent to the "old", they're declaring generic function types. A generic function type is one like `<T>(T) -> T` ... that means "for any type T, this function takes a parameter of type T and returns a value of type T".

You cannot pass a normal function expression like `(e) => e.abs()` to a generic function. That should be a compile error. You could pass something like `<T>(e) => e.abs()` but you'll get an error that T does not support `.abs()` ... that illustrates the problem. Your lambda doesn't work for all T, it only works for `int` specifically. The problem here is the type signature of _find is not equivalent to the "old" syntax.

Here's a version of the "new" examples that are equivalent to the "old" examples:
```dart
class GraphVisitor1 {
	T _find<T>(T Function(int example) fn) => null;
  
  void doThing() {
    _find((e) => e.abs()); // infers int -> int
  }
}
```
and 
```dart
typedef OnIntB<T> = T Function(int example);

class GraphVisitor4 {
  T _find<T>(OnIntB<T> fn) => null;
  
  void doThing() {
    _find((e) => e.abs()); // infers int -> int
  }
}
```
both of those work

**Comment by matanlurey** [comment]
Thanks make perfect sense, thank you!
