### ISSUE TITLE
New "Function" syntax and current release status

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30761]
It might make sense to document somewhere that in _stable_ it is almost completely unusable (due to analyzer crashes, and due to it not being implemented in the VM), and even in _dev_ there are a lot of quality-of-life issues that make using it over the old typedef unsuitable:

_EDIT_: Re-organized the list of issues as-of 2017/10/15.

**Still broken**: 

* https://github.com/dart-lang/sdk/issues/30732 
  (VM: New typedef doesn't support annotations on parameters)
* https://github.com/dart-lang/sdk/issues/30596 
  (Analyzer: no analyzer syntax error when using the old function type syntax inside a function 
  type using the new syntax)
* https://github.com/dart-lang/sdk/issues/30759 
  (Analyzer: Implement missing methods and new functions quick fix)on a class type argument)
* https://github.com/dart-lang/sdk/issues/31804
  (Analyzer: Inheriting nested function-typed parameters)

**Not specific to the new syntax**:

* https://github.com/dart-lang/sdk/issues/30379 
  (Analyzer function type parameters are not correctly scoped)
* https://github.com/dart-lang/sdk/issues/30180
  (Analyzer does not fail on invalid generics use)

**Fixed or otherwise closed**:

* ~~https://github.com/dart-lang/sdk/issues/30729~~ (Analyzer: crashes with new typedef + named arguments)
* ~~https://github.com/dart-lang/sdk/issues/30758~~
* ~~https://github.com/dart-lang/sdk/issues/30595~~
* ~~https://github.com/dart-lang/sdk/issues/30375~~
* ~~https://github.com/dart-lang/sdk/issues/30760~~
* ~~https://github.com/dart-lang/sdk/issues/31107~~ (Analyzer: Using function types inside of named initializing formals)
* ~~https://github.com/dart-lang/sdk/issues/29665~~ (Analyzer crash using a function type as a bound)
* ~~https://github.com/dart-lang/sdk/issues/31708~~ (Analyzer crash/parse error in foreach types)
* ~~https://github.com/dart-lang/sdk/issues/30858~~ (Analyzer: Using function types inside of `<...>`)

Some of these are admittedly P2, others have workarounds, and some are P1.

Did we use this feature at all in our libraries or SDK before releasing?

/cc @anders-sandholm @mit-mit @kevmoo

**Comment by jmesserly** [comment]
I fixed analyzer resolution & DDC recently, FYI. I haven't had a chance to go through and close out old bugs though. So it's worth retesting any older ones.

**Comment by matanlurey** [comment]
Thanks! I think engineering effort here (and responsiveness!) has been awesome, my main issue has been with release management and verification :)

**Comment by jmesserly** [comment]
> Thanks! I think engineering effort here (and responsiveness!) has been awesome, my main issue has been with release management and verification :)

Yeah, agreed. I thought it worked already, so I used it in a test case and was really surprised by crashes. That's how I ended up implementing Analyzer and DDC support :). It's definitely in a confusing state still (I'm not sure the state of it in other implementations, for example the Dart Formatter seems to crash on the syntax).

**Comment by vsmenon** [comment]
@anders-sandholm @kevmoo - what's the right way to track this?

**Comment by jcollins-g** [comment]
#30146 is specific to the new syntax.

**Comment by jcollins-g** [comment]
@matanlurey Use of the new function syntax outside of a typedef was not handled properly in dartdoc and I didn't notice until something broke our dartdoc asserts in https://github.com/dart-lang/dartdoc/issues/1505.  That something was https://github.com/dart-lang/sdk/commit/38bf70d7ac4ea695adc65ae3d7d0fa083b4dcd46, specifically, the use of the Function syntax here:

https://github.com/dart-lang/sdk/blame/38bf70d7ac4ea695adc65ae3d7d0fa083b4dcd46/sdk/lib/async/zone.dart#L573

Since our asserts would have started firing sooner otherwise, I can say with some confidence that we haven't used the Function syntax in this manner inside the SDK until that CL.

**Comment by kevmoo** [comment]
Another issues with this – caused by rolling out support in pkg/http2 - https://github.com/dart-lang/http2/issues/14

**Comment by MichaelRFairhurst** [comment]
Added two other bugs that seem to belong here

**Comment by MichaelRFairhurst** [comment]
I closed 
#29665
(Analyzer crash using a function type as a bound on a class type argument), seems to be fixed in latest.

Also looks like I should not have added #30147
(Analyzer: crash with partial application of generic function typed function), its actually not related to generic function types but generic methods in general.

**Comment by MichaelRFairhurst** [comment]
https://github.com/dart-lang/sdk/issues/30858 is still open because the "fix" caused a secondary issue. It's a pretty deep issue related to synthetic generic element types which I've not had much luck with. Latest solution involved turning off an assertion and is up for review: https://dart-review.googlesource.com/c/sdk/+/20481

**Comment by MichaelRFairhurst** [comment]
Added a few more bugs here. Some maybe shouldn't be here based on being maybe more general and/or low priority, but, I wanted to err on the side of tracking too much.

**Comment by MichaelRFairhurst** [comment]
The big one (#30858) closed, though not without creating some other subtle issues which are noted in https://github.com/dart-lang/sdk/issues/31804

**Comment by matanlurey** [comment]
I haven't run into any problems here for a while. Thanks!
