### ISSUE TITLE
kernel: how to represent in memory and store analyzer summary data

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30898]
This issue revisits a design question about how we add information to the kernel format that is needed for analyzer summaries.

Today we add fields to the kernel AST, mark them `@informative`, and serialize them together with the AST nodes. @peter-ahe-google has expressed concern that this might bloat the AST and make all tools pay a cost when this is only needed for analyzer summaries.

Questions:
* Long term: How should we represent this data in memory and in the serialized format? (some ideas that a few of us have discussed are included below)
* Short term: What do we do until this design is complete, so we are not blocked by this?

@kmillikin @peter-ahe-google - please let us know about the short-term question. Our current plan is to continue adding fields with the `@informative` annotation, and migrate to the new design as soon as we decide on one.

/cc @scheglov @stereotype441 

--- 
Here are some of the proposals we have been discussing here and there:

For the in-memory representation:
 - keep adding fields and mark them `@informative` (in-memory cost for non-analyzer users is N extra fields)
 - add a single field "informativeData" that contains a list of informative nodes (in-memory cost is 1 extra field)
 - reuse the existing medatada list, and encode the informative data as metadata (in-memory cost is 0, but representation feels harder to work with).

For the storage representation:
  - serialize `@informative` data inline, like we do today
  - split informative data into a separate file
  - keep informative data in the same file, but don't always store it inline. Treat data differently depending on its intent, in particular, we may want to put data relevant to outlines in a separate section of the file so that the cost is very low when the data is excluded

**Comment by kmillikin** [comment]
Other systems have separated the compiled interfaces from the compiled implementations.  We're using Kernel for both and we should (re)consider whether we should split them up.

We use Kernel as the compiled interface of a Dart module so that we can resolve and typecheck against it without reparsing and analyzing the source code.  And we also  use it as the intermediate representation of a compiled Dart module that we can further analyze, optimize, and lower.

This makes us scratch our head when we have to consider "what is the effect on the Dart interface of transforming this Kernel code" and "what is the Dart interface of Kernel code that was never Dart code in the first place".  And it makes us push back on things that make the language a better interface format but a worse intermediate representation or vice versa.

We should consider: splitting compiled interface from compiled intermediate representation, at least in the design if not on the file system, by introducing Kernil (interface) and Kernol (object) languages.  (I'm just trolling with the names.)  When a compiled implementation undergoes transformation and is serialized out, we could use a different magic number that breaks that connection to its compiled Dart interface (alternately, strip out the interface section of the file).

**Comment by sigmundch** [comment]
About the short-term question - how should we proceed?

Konstantin has a couple CLs that he sent out that continue using the `@informative` annotation, can he continue using that approach for now?

**Comment by kmillikin** [comment]
In the very very short term: keep using @informative and adding things to the binary format.

In the short term: We're going to add an optional section to the binary that is a serialized map from Kernel nodes (offsets) to back-end-specific binary data.  I think we should look at whether that would be a good way to move @informative out of line for the time being.

In the intermediate term: our semantics of separate compilation and linking will include a logical distinction between compiled interface of Dart code and compiled implementation.  Once we've settled on that it will be easier to design a good representation for each purpose.

**Comment by peter-ahe-google** [comment]
I'm not convinced that we can afford to add anymore fields to the AST objects we keep in memory. These additional fields are causing increased memory pressure and will over time degrade performance. Additionally, we've started adding fields to AST objects that will cause memory leaks for clients like dart2js.

I think there are perfectly reasonable ways to work around this, for example, using maps similarly to ClassHierarchy.

What we're currently doing will not allow us to reach the performance goals we have, so something needs to change.

It is my opinion that it requires a small amount of effort now, and we'll have a flexible solution that will be easy to tweak in the future.

**Comment by jensjoha** [comment]
Wasn't this "fixed" by a52d4b0f75dbc6c2b561b8c00726e67c90c37cca?

**Comment by peter-ahe-google** [comment]
It was.
