### ISSUE TITLE
dart2js_extra/unconditional_dartio_import_test failing on kernel after dart2js imports dart:io

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#30902]
The builder https://luci-milo.appspot.com/buildbot/client.dart/dart2js-linux-d8-minified-3-5-be/7855
is failing on this test after the CL that adds dart:io to dart2js.  The type of the error changed from CompileTimeError (which was in the  status file, so not an expected result, but with no issue filed) to RuntimeError.

This status is noted in the status file tests/compiler/dart2js_extra/dart2js_extra.status.
The CL which changed the status (which may actually be an improvement, not a regression) is
https://dart-review.googlesource.com/c/sdk/+/8341

FAILED: dart2js-d8 release_x64 dart2js_extra/unconditional_dartio_import_test
Expected: CompileTimeError 
Actual: RuntimeError
CommandOutput[dart2js]:

**Comment by sigmundch** [comment]
Thanks Bill for updating the status!

In case this happens again in the near future, feel free to update the .status without creating a bug if the failure relates to dart2js_with_kernel.

We decided not to create individual issues for anything under the 'dart2js_with_kernel' section because we are basically using the status file as our triaging tool directly while the integration with kernel is in progress.

**Comment by sigmundch** [comment]
documented now in the status file.
