### ISSUE TITLE
Kernel should have an AssertInitializer node

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#30914]
Kernel should have an `AssertInitializer` node. The current encoding misuses the `LocalInitializer` and makes the feature unnecessarily convoluted.

**Comment by peter-ahe-google** [comment]
I disagree. `Assert` should be an expression.

**Comment by johnniwinther** [comment]
So do you want an `ExpressionInitializer` as well or do you prefer to hide the assert in an `LocalInitializer` of an unused local of a weird valid (a value of type `void` is presume) ?.

**Comment by rakudrama** [comment]
We need to omit the assert initializer when compile options dictate, so need to clearly match the entire thing, embedded side-effects and all.

We would like to avoid having to pattern-match inside some other initializer to attempt to identify the assert initializer. Perhaps an AssertInitializer contains an AssertExpression.

Whatever we do, we need something properly defined and described in kernel/lib/ast.dart in order to work on https://github.com/dart-lang/sdk/issues/30038 without having to go back for re-work as ideas change.

**Comment by peter-ahe-google** [comment]
I'd use LocalInitializer. That's more flexible.

**Comment by rakudrama** [comment]
@kmillikin As a first step, can we define in kernel/lib/ast.dart how an assert initializer will look?

Then the parser(s) can generate that tree, and the compilers can generate code for it.

The current form where dart2js sees a LocalInitializer containing a closure application is not suitable since it leaves residual code when assertions are not enabled.

**Comment by kmillikin** [comment]
As a first step:

`AssertInitializer` is an initializer that contains an `AssertStatement`.  The representation is here: https://dart-review.googlesource.com/c/sdk/+/14760

Do you have any concerns with it?

**Comment by johnniwinther** [comment]
It clearly marks the initializer so I'm ok with it.
