### ISSUE TITLE
DDC is incorrectly hoisting types

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30912]
The following:

```dart
class Foo {
}

class Bar {
}

typedef Type Func<S extends Foo, T>(T s);

class Baz<S extends Foo, T extends Bar> {
  Func<S, Bar> func;
}

void main() {
  dynamic baz = new Baz();
  print(baz.func);
}
```

fails with:

```
ReferenceError: S is not defined ReferenceError: S is not defined
```

**Comment by vsmenon** [comment]
@jmesserly @leafpetersen - can one of you take a look?  If I can `Func<S, Bar>` to `Func<S, T>`, no error - looks like a bug in the hoist logic.

**Comment by jmesserly** [comment]
I can take a look. I hope it's not an instance of https://github.com/dart-lang/sdk/issues/30379 (because that one is showing up everywhere lately).

**Comment by jmesserly** [comment]
The reason this is broken is that `S` is not used in the function type, so it doesn't appear at all after the typedef has been instantiated. The function type is just `(Bar) -> Type`, so no free variables, and hoisting is legal. The problem is we emit it using the typedef (to preserve the name perhaps).

I'm guessing no one has hit this combo before, as unused type parameters aren't super common.

Shouldn't be too hard to fix.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/9125
