### ISSUE TITLE
Test pkg/analyzer/test/generated/strong_mode_kernel_test flakes on analyzer win7 bots

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#30917]
Test pkg/analyzer/test/generated/strong_mode_kernel_test sometimes flakes with RuntimeError on two analyzer win7 bots. Here are some instances of the issue:

analyzer-win7-release-strong-be:
* [3991](https://build.chromium.org/p/client.dart/builders/analyzer-win7-release-strong-be/builds/3991/steps/analyzer%20unit%20tests/logs/stdio)
* [3988](https://build.chromium.org/p/client.dart/builders/analyzer-win7-release-strong-be/builds/3988/steps/analyzer%20unit%20tests/logs/stdio)
* [3986](https://build.chromium.org/p/client.dart/builders/analyzer-win7-release-strong-be/builds/3986/steps/analyzer%20unit%20tests/logs/stdio)

analyzer-win7-release-be:
* [7385](https://uberchromegw.corp.google.com/i/client.dart/builders/analyzer-win7-release-be/builds/7385/steps/analyzer%20unit%20tests/logs/stdio)
* [7380](https://uberchromegw.corp.google.com/i/client.dart/builders/analyzer-win7-release-be/builds/7380/steps/analyzer%20unit%20tests/logs/stdio)

**Comment by stefantsov** [comment]
Another instance of the issue, this time, on analyzer-linux-release-strong-be: [4123](https://uberchromegw.corp.google.com/i/client.dart/builders/analyzer-linux-release-strong-be/builds/4123/steps/analyzer%20unit%20tests/logs/stdio).

**Comment by whesse** [comment]
The failure is always in the same subtest of this very large test, so I suggest the analyzer team disable this one subtest, and remove the status file suppression I will be entering in pkg/pkg.status3 in the [ $runtime == vm && $system == windows] section.

I tried disabling this one subtest by deleting it from the test file, but this caused other failures because it is a reflective interface implementation of something.  I strongly think that you would like to keep running all the other subtests, and should take this one out so you can remove the status line.

**Comment by whesse** [comment]
The subtest is StrongModeLocalInferenceTest_Kernel | test_factoryConstructor_propagation, by the way.
@scheglov @bwilkerson

**Comment by aam** [comment]
Same test failed on [pkg-mac-release-be] bot(https://uberchromegw.corp.google.com/i/client.dart/builders/pkg-mac10.11-release-be/builds/8022/steps/package%20unit%20tests/logs/stdio)

**Comment by whesse** [comment]
CL with status change, now on all platforms, at https://dart-review.googlesource.com/c/sdk/+/9621

**Comment by scheglov** [comment]
This should help
https://dart-review.googlesource.com/#/c/sdk/+/9744

**Comment by whesse** [comment]
Great!
