### ISSUE TITLE
Allow $ok.ok string interpolation

### ISSUE THREAD

**Issue by Meai1** [dart-lang/sdk#30938]
**Problem:**
Currently I'm required to type out the braces: `${ok.ok}` instead of writing the shorter form `$ok.ok`
This new feature is supposed to fix the ambiguity created from allowing `$ok.ok` but it not doing what you think it's going to do.

**Motivation:**
It's a very common thing to want to print a variable of some class, probably the most common usecase for string interpolation. Yet it always requires typing the braces, even though it seems quite natural to extend the featureset to support `$ok.ok` because `$ok` without the braces already works as well.
I feel like anybody who would write `$ok.ok` and expect it to only print the contents of `$ok` would be exhibiting terrible coding style, that's very confusing to look at and read and it's unlikely anybody relies on that exact current printing behavior. 

**Possible edge cases:**
In case you really do want to print the dot, you could allow escaping it with `\.` like so: `$ok\.ok` or dont allow it at all and simply show a regular analyzer error "missing variable .ok on object", which makes more sense anyway and requires no special extra escaping rules, the analyzer would already know what to do if we allow it.

**Possible drawbacks:**
People might want more features on top of this if we allow it, like full function calls with the shorter syntax. I'm not against it, but I'm just remarking that it's a possibility.
Breaking change.

**Comment by lrhn** [comment]
I admit that it happens relatively often to me while debugging - both the deliberate `"${object.prop}"` and the `"$object.prop=${object.prop}"`.

The counter points would be:
1. Parsing complexity. Not really an issue - a `('.' identifierNoDollar)*` grammar is regular and easily parsed.
2. False positives. How often do you want to write `.identifier` as string content after an interpolation, where this change forces you to write *more*. That's likely to be fairly rare (I always either put a space after the `.`, or I'm likely to be in the debug case above and then I can save the other braces instead). Workarounds: `"$x\.y"` or `"${x}.y"` (I'd probably prefer the latter, I find it more readable).
3. User complexity (mental overhead, not implementation, implementation is simple). How often does the case happen in practice vs. how often it causes more complexity for users. Is it confusing that `"$foo.bar"` works and `"$foo[bar]"` does not? Is it confusing that whitespace is significant (`"$x. no!"` is different from `"$x.no"`) when it isn't outside of strings? etc ... It's now a new sub-language, where "one identifier only, otherwise use braces" is a simple rule to explain and understand.

My biggest worry is the mental complexity. That's where it becomes *design*, not just an implementation issue. Like, should we allow whitespace around the `.`? If so, false positives become much more likely. I not, it subtly differs from real expressions.

Still, it's definitely useful in some cases and the technical side should be simple. Worth considering.

**Comment by srawlins** [comment]
I think this is a non-starter in terms of its effects on existing code. This would immediately break any current code like `"$ok.ok"`, in hard-to-track, hard-to-error ways.

There is a lot of code like this already. Code like "File saved to $name.txt", "$foo.$bar" (since variables may start with `$`, this would have to be treated like `"${foo.$bar}"` under this new feature).

**Comment by lrhn** [comment]
I think it's fair to close this. It's not something we are even considering, partly because it's a breaking change with very little impact, and partly because it complicates the mental model for users - meaning it's not a very good design.
If we ever decide to improve the power of string interpolations, it'll likely be much further reaching than just allowing dotted identifiers, and then it's a different feature.
