### ISSUE TITLE
Spawned isolate doesn't throw "boolean expression must not be null" assertion

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#30941]
Dart SDK 2.0.0-dev.2.0 on windows_x64 (VM, checked mode)
```dart
import 'dart:async';
import 'dart:isolate';

Future main() async {
  run(null); // prints Failed assertion: boolean expression must not be null
  await Isolate.spawn(run, null); // fails silently
}

void run(bool v) {
  try {
    if (v) {
      print('OK');
    }
  } catch (e) {
    print(e);
  }
}
```

**Comment by lexaknyazev** [comment]
It turns out that the main isolate exits before exception is caught in the code above. Switching the order of `run` invocations helps:
```dart
import 'dart:async';
import 'dart:isolate';

Future main() async {
  await Isolate.spawn(run, null); // Failed assertion: boolean expression must not be null
  run(null); // Failed assertion: boolean expression must not be null
}

void run(bool v) {
  try {
    if (v) {
      print('OK');
    }
  } catch (e) {
    print(e);
  }
}
```

Behavior is different when no exception should be thrown - in that case both isolates invoke `print`:
```dart
import 'dart:async';
import 'dart:isolate';

Future main() async {
  run(true); // OK
  await Isolate.spawn(run, true); // OK
}

void run(bool v) {
  try {
    if (v) {
      print('OK');
    }
  } catch (e) {
    print(e);
  }
}
```

Or when exception is different:
```dart
import 'dart:async';
import 'dart:isolate';

Future main() async {
  run(null); // IntegerDivisionByZeroException
  await Isolate.spawn(run, null); // IntegerDivisionByZeroException
}

void run(_) {
  try {
    1 ~/ 0;
  } catch (e) {
    print(e);
  }
}
```

**Comment by mkustermann** [comment]
Apologies for the very late reply here.

A few things to note here:

* [Isolate.spawn<T>(void Function(T) fun, T message)](https://api.dart.dev/stable/2.13.4/dart-isolate/Isolate/spawn.html) is now generic. We have therefore a compile-time guarantee that the argument passed to the `fun` function is of the right type.
* Running this with NNBD enabled will result in a compile-time error, since passing `null` to a non-nullable `bool` parameter is incorrect
* Running this in non-NNBD will allow it to use `null` in the `bool` parameter of the function being spawned, but not in the `if (parameter)` condition, which should throw.

Right now the Dart VM (our command-line VM embedder) will terminate the process once the initial `main` isolate has died. So one cannot expect the helper `run` isolate to have printed the exception at the time the `main` isolate dies - it is a race.

To see that the actual exception is always printed, one can keep the `main` isolate alive until the helper isolate has died, e.g. via:
```dart
// @dart=2.9
import 'dart:async';
import 'dart:isolate';

Future main() async {
  final onError = ReceivePort()..listen((e) => print('error: $e'));
  final onExit = ReceivePort();
  await Isolate.spawn(run, null,
      onError: onError.sendPort, onExit: onExit.sendPort);

  final si = StreamIterator(onExit);
  await si.moveNext();
  onError.close();
  onExit.close();
}

void run(bool v) {
  try {
    if (v) {
      print('OK');
    }
  } catch (e, s) {
    print(e);
    print(s);
  }
}
```

Running this will result in 
```
% dart test.dart
Failed assertion: boolean expression must not be null
#0      run (file:///.../test.dart:19:9)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

The fact that the exit of the initial `main` isolate will terminate the process is working-as-intended.

@lexaknyazev I hope that gives you enough explanation on what is happening. So I'll close this issue. If I misunderstood the issue here or you have other issues, please re-open or file a new issue.
