### ISSUE TITLE
Attempt to export a part adds main() that does not exist in Dart code

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30960]
With `test.dart`:
```dart
library L;
export 'lib1.dart';
```

Where `lib1.dart` is:
```dart
part of lib;
```

Results in
```kernel
library;
import self as self;

static method #main() → dynamic {
  throw "file:///test.dart:2:1: Error: A part can't be exported.\nexport 'lib1.dart';\n^";
}
```

But this `main()` does not exist in `test.dart`, so this causes mismatched AST and element model error in Analyzer.

**Comment by scheglov** [comment]
I think that maybe runtime behavior and semantic information should be separated, so that errors are recorded in a way that does not introduce artificial nodes that does not exist in code.

**Comment by peter-ahe-google** [comment]
This is a known issue around error recovery in Fasta. This happens when we call one of the deprecated error methods in [pkg/front_end/lib/src/fasta/deprecated_problems.dart](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/deprecated_problems.dart).

At some point we need to go through all these methods and replace them with something that recovers from the error. But this is kinda blocked on #29840.

**Comment by peter-ahe-google** [comment]
The issue with `#main` is tracked in #31833.
