### ISSUE TITLE
Analyzer/DDC doesn't recognize Object is not callable

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#30987]
```dart
void main() {
  var object = new Object();
  object('Foo', 'Bar');
}
```

Neither in the analyzer (w/ strong-mode) or in the DDC compiler step does this fail, only runtime.

**Comment by eernstg** [comment]
The language specification 16.14.4 Function Expression Invocation has 
```
It is a static warning if the static type $F$ of $e_f$ may not be assigned to a function type.
```
where `$e_f$` is the expression denoting the function which is being invoked, here `object`. This means that, in Dart 1.x, function invocation is allowed to rely on a downcast (to `Function`) in order to justify that it is a function at all.

In that sense it is similar to argument passing, initialization, etc, but more permissive than member lookup (that's presumably because there is no "natural" type to downcast `x` to in order to justify a member access like `x.y`, because there could be several subtypes with a member named `y`). Basically, we can rely on a downcast when the target type is well-defined.

In the concrete example, `Object` is ok because it is a supertype of `Function`.

We might want to change this for Dart 2, based on the general wish to check types more strictly.

However, the current approach seems at least to have a certain logic to it, and you could say that _all_ these downcasts should be managed by developers using certain policies: Maybe they'll use `--no-implicit-casts`, maybe the IDE can make all downcasts blink ;-), or whatever.

I've created an issue for the language team to discuss this.

**Comment by eernstg** [comment]
We discussed this a bit and agreed; the language specification was updated (5f713bdd194123e11e2b9db33dfc0f8c578a20d7) to reflect that it is now a static warning to call an `Object`. (All static warnings in the spec will be changed to compile-time errors soon).

**Comment by matanlurey** [comment]
Thank you!

**Comment by srawlins** [comment]
Analyzer now prints the following for @matanlurey 's original code:

> 'object' isn't a function.
