### ISSUE TITLE
initialize `new List(len)` items with null

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#31002]
We can use `Array.prototype.fill` to do this. It may have some overhead at allocation time, but it avoids the slowness associated with accessing an array with holes.

(After this change, we may also want to reconsider if we need to handle JS `undefined` as Dart `null` in DDC. If we know Dart code never creates `undefined` we could optimize null checks, `==` and `identical`. However, it may still be required due to undefined from HTML and/or JS interop.)

**Comment by mraleph** [comment]
I filled https://bugs.chromium.org/p/v8/issues/detail?id=6892 just in case.

**Comment by vsmenon** [comment]
@mraleph 

I did this, which does show a small perf benefit:

https://dart-review.googlesource.com/c/sdk/+/11242

For `new List(n)`, it generates:

```
var list = new Array(n);
list.fill(null);
```

From, your comment, though, it doesn't fix the issue with holes.

**Comment by mraleph** [comment]
@vsmenon it fixes issue with holes, but I don't think `fill(...)` is super efficient by itself right now. It is written in JS... 

(Note: there is a difference between array containing any holes and array having holey element kind - element kind is more pessimistic because it can't track when the last hole disappears).
