### ISSUE TITLE
generate modular metadata in modular API

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31006]
When reading a modular kernel file, DDC needs to know where module an external library belongs to, that way it can create the corresponding dynamic dependency in the generated code.

For example, imagine 3 modules (a,b,c) in a chain:
- module a, contains a1.dart, a2.dart and is compiled into a.dill
- module b contains b.dart that imports a1.dart, it is compiled by reading a.dill and the module is generated into b.dill (which includes external references to a1.dart)
- module c contains c.dart which imports b.dart, it is compiled to c.dill which contains tree-shaken pieces from a and b.

When DDC generates .js code from c.dill, it identifies that a1.dart/a2.dart/b.dart are all external references, but it needs to know that code from b.dart is loaded from module "b", while code from a1.dart is loaded from module "a".

To make this possible, we need to include some information in the c.dill file to identify where libraries belong to.

**Comment by sigmundch** [comment]
I propose we solve this by using the recently added metadata payloads in the kernel format. We'd attach to each external library a string containing a module name. The module name might be an input to this kind of modular API.

**Comment by jmesserly** [comment]
thanks!

We may also need to know all library URI(s) that were present in each module/summary, as our scheme for inventing unique library names within a module needs to avoid choosing conflicting names.

For example, let's say DDC compiles two libraries "foo.dart" and "src/foo.dart" into the same module "foomod". Instead of calling them both "foo", we can give them unique names, like "foo" and "src_foo".

Later when I go to `import "path/to/src/foo.dart"`, we first find the module name "foomod". Then we need to recompute the library name, in this case "src_foo". If we know all libraries in "foomod" we can run the same algorithm.

(We can't translate raw import URIs, because they're very verbose, and absolute file URIs are a big problem. Also users do not typically combine 2 packages into the same module, so DDC current strips off the package prefix, because it is usually the module name. Both of these can lead to conflicting names in pathological cases.)

**Comment by sigmundch** [comment]
Interesting.  Indeed, my original proposal would not be sufficient because our modular "tree-shaking" could basically delete libraries from modules where they are not used, so you wouldn't be able to detect these conflicts.

We should be able to include metadata that lists all URIs in a module, but I wonder if some annotation on the individual libraries could be enough. When picking a unique id, does your algorithm care about the path of other conflicting libraries? Or just about the fact that a library has a name conflict?

Maybe later in the week we can brainstorm a bit more about this. It might not be possible anyways to do something like what I suggest without baking-in a DDC specific details, so we might have to always include all URIs.

**Comment by sigmundch** [comment]
@jakemac53 @vsmenon just discussed this in person today.

We agreed that, since now we no longer plan on using tree-shaking, we can simply store the module name on each library metadata. When loading a program, DDK will compute a table with all libraries that belong to the same module name and use that to compute the appropriate import path like it does today.

**Comment by sigmundch** [comment]
Closing this issue as the underlying need for modular compilation in DDK has been addressed.

In particular, we have added enough support to distinguish where source files are loaded from and to derive a module name for them. In the end we implemented the following solution:
 - We added support to transform outlines before we emit them as summaries.
 - When building summaries for DDK, the summary generator ensures that summaries only contain the files being compiled and none of the dependencies (summaries are truncated .dill files)
 - When compiling with DDK, we use a custom-uri-scheme so the absolute URI of a summary easily maps to a module name.

If we need to change how we encode the module name (and not use the file name for it), we can do so in the future by adding metadata during summary generation (also via the same mechanism of transforming outlines).
