### ISSUE TITLE
Add ability to make own class awaitable

### ISSUE THREAD

**Issue by jrote1** [dart-lang/sdk#31040]
It would be good to allow developers to make their own classes awaitable, kind of like C# does where you can add a `GetAwaiter` method. Something similar in Dart could be a useful addition. For example it could make the following code simpler by removing the need to call the execute method.

`await page.enterText("#id","").click("#btn").verify((p)=>).execute();`

**Comment by lrhn** [comment]
It's an interesting idea. 
Currently any class can implement `Future`, but that's not what you want here. What you want, if I understand it correctly, is more like the relation between `Iterable` and `Iterator`, where `Future` is the `Iterator` - a way to request an operation to *start* and return a future representing its result.

Type-wise it's harder to explain in Dart. An `await e` is already valid for any type (because you can await values, which makes `FutureOr<int> result = ...; await result;` meaningful.
It could either be static-type-based (only trigger when the static type is an awaitable class type that cannot be a future), or dynamic (each await checks the type the value - if it's a `Future`, it's awaited directly, if it's awaitable, it's started and the result future is awaited, otherwise it's just completed).

All in all, if it's not purely static-type based, I fear that it will just cause an extra overhead on all awaits.

I'm not sure it's a feature that carries its own weight. It makes the story around awaiting and futures more complicated without providing any actual expressive strength (you can always just do `.awaiter` yourself). If you are writing a DSL, the briefness is nice, but for most normal code, it's unlikely to make a big difference (most async operations just return a future).

**Comment by lrhn** [comment]
This would be an implicit "convert to future" operation, which would be triggered by `await`.
It's probably more readable to just have a `Future<void> run()` method, and do `await ...run()`.
It makes it clear where the asynchronous operation *starts*.
