### ISSUE TITLE
Incremental compiler produces incorrect super call in mixin application in Flutter Gallery

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31043]
For this code https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/binding.dart#L53 incremental kernel generator produces incorrect invocation of initInstances method `this.{=bin::BindingBase::initInstances}();`:
```
 abstract class ___BindingBase&SchedulerBinding&GestureBinding&ServicesBinding 
extends bin5::__BindingBase&SchedulerBinding&GestureBinding implements bin4::Ser
vicesBinding {
...
    method initInstances() → void {
      this.{=bin::BindingBase::initInstances}();
      let final dynamic #t1438 = ui::window in let final dynamic #t1439 = #t1438
.onPlatformMessage = pla3::BinaryMessages::handlePlatformMessage in #t1438;
      lic::LicenseRegistry::addLicense(this.{bin4::ServicesBinding::_addLicenses
});
    }
```

Compare to batch compiler:
```
  abstract class ___BindingBase&SchedulerBinding&GestureBinding&ServicesBinding 
extends bin::__BindingBase&SchedulerBinding&GestureBinding implements bin6::Serv
icesBinding {
...
    method /* from file:///Users/aam/projects/flutter/test_root6/flutter/flutter
/packages/flutter/lib/src/services/binding.dart */ initInstances() → void {
      this.{=bin::__BindingBase&SchedulerBinding&GestureBinding::initInstances}(
);
      let final dynamic #t1132 = ui::window in let final dynamic #t1133 = #t1132
.onPlatformMessage = pla2::BinaryMessages::handlePlatformMessage in #t1132;
      lic::LicenseRegistry::addLicense(this.{bin6::ServicesBinding::_addLicenses
});
    }
```

This causes full restart of Flutter Gallery app to fail because app state has not been properly initialized when app restarts:
```

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:60199/
For a more detailed help message, press "h". To quit, press "q".
R

Performing full restart...
Syncing files to device Android SDK built for x86...
Restarted app in 5,221ms.
I/flutter (12865): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12865): The following NoSuchMethodError was thrown building DefaultTextStyle(inherit: true, color:
I/flutter (12865): Color(0xd0ff0000), family: monospace, size: 48.0, weight: 900, decoration: double Color(0xffffff00)
I/flutter (12865): TextDecoration.underline):
I/flutter (12865): The getter 'schedulerPhase' was called on null.
I/flutter (12865): Receiver: null
I/flutter (12865): Tried calling: schedulerPhase
I/flutter (12865): When the exception was thrown, this was the stack:
I/flutter (12865): #0      Object.noSuchMethod (flutter_patched_sdk/lib/core/object.dart:109:5)
I/flutter (12865): #1      NavigatorState._cancelActivePointers (package:vector_math/hash.dart:1:711309626)
I/flutter (12865): #2      NavigatorState.push (package:vector_math/hash.dart:1:711293714)
I/flutter (12865): #3      NavigatorState.initState (package:vector_math/hash.dart:1:711289135)
I/flutter (12865): #4      StatefulElement._firstBuild (package:vector_math/hash.dart:1:711413744)
```

**Comment by sigmundch** [comment]
Just some additional pointers to help investigate:
 - the implementation of initInstances for which Alex shows the generated code is here:
https://github.com/flutter/flutter/blob/9eae8b83ff6722c5fe028d0a1e28b9f813df6980/packages/flutter/lib/src/services/binding.dart#L25

- this file contains a lot of code that uses this code in a chain of mixins: 
https://github.com/flutter/flutter/blob/18f0d3aef711914c395c2cde37ac116bf171d970/packages/flutter/lib/src/rendering/binding.dart#L350

**Comment by scheglov** [comment]
I can reproduce this in a unit test.

The problem happens because for some reason `super. initInstances ()` is compiled as a `DirectMethodInvocation` instead of `SuperMethodInvocation`. Don't know why yet.

**Comment by sigmundch** [comment]
@scheglov - one idea: I believe the mixin transformation changes superMethodInvocations into DirectMethodInvocations - if you turn off the mixin transformer, is it generated correctly?

**Comment by scheglov** [comment]
Yes, this happens because we transform classes like `class B extends A {}`, which are later used as mixins in `class C extends A with B {}`. But at this point  any method in `B` has any of its `SuperMethodInvocation` already transformed into `DirectMethodInvocation`.

Is this a feature? Do we need to transform all `SuperMethodInvocation` to `DirectMethodInvocation` in final kernels to make it run faster? And this is transformation independent of mixin transformation?

**Comment by scheglov** [comment]
Hm... We need both versions of a class - one with `SuperMethodInvocation`s resolved to `DirectMethodInvocation`s - for the case when the class is used on its own, and another with `SuperMethodInvocation`s left intact - for the case when the class is mixed into another class.

The resolution of `Super*` to `Direct*` is potentially damaging, because it is possible to write code that cannot be resolved in a standalone class, but is valid once it is mixed-in.
```dart
class A {
  void foo() {
    super.bar();
    print('foo after bar');
  }
}

class B {
  void bar() {
    print('bar');
  }
}

class C extends Object with B, A {
}

main() {
  new C().foo();
}
```

Here invocation of `super.bar()` in `A.foo` is unresolved.
But it works fine in `C`.

**Comment by sigmundch** [comment]
I think this comes back to the fact that mixin-transformation is not modular. 

Consider this script as a repro:
```dart

import 'package:front_end/front_end.dart';
import 'package:front_end/src/fasta/kernel/utils.dart';
import 'package:front_end/src/testing/compiler_common.dart';
import 'package:kernel/kernel.dart';
import 'package:kernel/target/targets.dart';

main(args) async {
  var sources = <String, dynamic>{
    'a.dart': '''class A {
                   foo() => 1;
                 }

                 class M extends A {
                   foo() => super.foo();
                 }

                 class B extends A {
                   foo() => 2;
                 }

                 class C extends B with M {}
                 ''',
    'b.dart': '''import "a.dart";
                 class D extends B with M {}''',
  };


  /// If the script is called with "none" we use the NoneTarget, otherwise
  /// we use the default vm target which applies the mixin trasformation.
  var options = args.length > 0 && args[0] == "none"
      ? (new CompilerOptions()..target = new NoneTarget(new TargetFlags()))
      : null;

  var unitA = await compileUnit(['a.dart'], sources, options: options);
  sources['a.dill'] = serializeProgram(unitA);
  print('\n===a.dill===');
  writeProgramToText(unitA);

  var unitB = await compileUnit(['b.dart'], sources,
      inputSummaries: ['a.dill'],
      options: options);
  print('\n===b.dill===');
  writeProgramToText(unitB);
}
```

What should be done is that
- `super` in M should be compiled to a super call and not converted to a direct call
- when `_B&M` is synthesized, the super copied from M should be translated to a direct call to B's method (not A)

The mixin transformer is somehow changing boths. Because of this, when you compile the second unit, you no longer have super in M and the code we generate is incorrect.

If you however disable the transformation (supply "none" to the script above) you will see in the output that M.super is generated corrrectly.

The case with an unresolve super works because of some error-recovery done in fasta, which the mixin doesn't see.

**Comment by sigmundch** [comment]
To clarify - most of the transformation could be fine, as long as it doesn't modify the original class in place. The fact that somewhere we are changing M.super call to a direct call is the problem.

The script above verifies that this is not done by fasta because using the none target keeps the call as we expect. I just tried commenting out only the mixin transformation, and I can verify that the M.super call is rewritten by the transformation.

**Comment by scheglov** [comment]
Yes, the mixin transformer with processes `M` separately, and replace supers with directs. And then when we mix-in `M`, there are no any supers anymore.

I cannot disable the mixin transformer, can I? All supers have to be resolved into directs, right?

**Comment by sigmundch** [comment]
> I cannot disable the mixin transformer, can I?
Correct, we can't get rid of the transformation entirely today, but last week we started talking about changing this.

Kevin mentioned their plan is not to make it modular anymore, so there are two options in the future: the VM does the transformation itself or we need to do a big transformation after we build the entire program in the front end. I prefer the former, especially because the latter would meant that IKG has to reassemble the full program every time, apply the transformation, and possibly send down all libraries? That doesn't seem very incremental to me.

I'll reach out to Siva and Kevin to define what we need to do here.

> All supers have to be resolved into directs, right?
The ones in the generated mixins yes, however I think the change to M.super might be a bug and shouldn't be done.

**Comment by aam** [comment]
@scheglov @sigmundch Is there anything I can do to help with this?
As things stand right now, this bug results in broken Restart in Flutter tools hot reload and prevents from adding more representative hot reload tests(tests which actually involve changing source code).

**Comment by sigmundch** [comment]
Kevin and I briefly synced up on this and concluded that we need some amount of design work for this. I'm afraid this will take some time to get fixed. We are meeting in person next week to dive in detail into this.

Some ideas we are considering include:
 * applying the transformations directly in the VM (we are not really excited about this approach)
 * applying the transformations after the incremental compile (this has some challenges because we are not producing a full program, only a partial program)
 * adding to the outlines the untransformed mixins, so we can apply the transformation incrementally (this requires that we mark mixins in a special way using some annotation, and would require adding the annotation to the flutter codebase).
 * possibly splitting the transformation in the short term: it already works as two steps cloning and then resolving super calls. This specific bug is caused by the latter step, so I am considering whether we could do the cloning work in the FE, but skip the resolution of super calls and do that in the VM. This is would only be a short-term fix because we have plans to change in IKG to be more modular, and at that point the cloning piece will be problematic as well.

Too early to tell what we'll do, but I can keep you posted.

**Comment by sigmundch** [comment]
Just to follow up: we decided to move the mixin transformer to the VM and remove it entirely from IKG

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/18320 has proposed solution

**Comment by scheglov** [comment]
Just to be sure that we have the same understanding of what should be done, not in any way pushing or something.

This is the first part of required mixin changes, right? There is also the second half of the transformer - copying methods, which also should not be done in order compile against outlines of dependencies vs. full libraries?

**Comment by aam** [comment]
Thanks @scheglov , I was not aware that the copying part done as kernel transformation is problematic too. Are we saying that when compiling against outlines there will be no mixin bodies to copy since outlines don't have bodies?

**Comment by scheglov** [comment]
Yes, outlines have no bodies, and we would like to compile against outlines.

**Comment by sigmundch** [comment]
Correct - my understanding when I spoke with Kevin last week was that all of the mixin transformation will be done within the VM, including the coping of method bodies. The mixin transformer will be completely turned off when using IKG.

It will not be deleted because maybe whole-program AOT optimizing compilers will turn it on (but they will not be running with IKG). Those optimizing compilers might also want to do the rewrite of super calls ahead of time, so we might want to keep that code around in some form (either disabled under a flag, or as as it is now after the full mixin transformation is available on the vm side)

**Comment by a-siva** [comment]
Can we update this issue based on the discussion we had this morning and potentially close it?

**Comment by aam** [comment]
New plan is leave mixin transformation in frontend only, don't bring it over to VM. Having mixin transformation done in VM would have enabled IKG to compile apps against outline, but the claim is that outlines don't actually provide good performance advantage, not worth pursuing. (I am curious how performance advantages of outlines were measured).

So basically things will stay the way they were implemented as of https://github.com/dart-lang/sdk/issues/31043#issuecomment-341736007 with only super mixin resolution done in VM. All further work on bringing mixin transformation to VM will be abandoned.
