### ISSUE TITLE
Instantiate to bounds for error cases is different in Analyzer and FrontEnd

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31074]
```dart
class C<T extends C<T>> {}
C c;
```

```kernel
true
library;
import self as self;
import "dart:core" as core;

class C<T extends self::C<self::C::T>> extends core::Object {
  default constructor •() → void
    : super core::Object::•()
    ;
}
static field self::C<dynamic> c;
```

Analyzer produces `C<C<dynamic>> c`.
FrontEnd produces `C<dynamic> c`.

https://dart-review.googlesource.com/c/sdk/+/5765 does not give exact answer, but as I understand it, I think that the front-end behavior is closer to the specification proposal, because 
> If no bound is given in _Fj_, the selected value for _Xj_ is `dynamic`.

and

> If this process terminates then the selected value is the final
value of the bound in _Fj_. If it does not terminate, the instantiate
to bounds process has failed.

**Comment by lrhn** [comment]
Either choice is a valid super-bounded type. The question is which is more useful to users.
If the class had been declared as `class C<T extends Comparable<T>> {}` instead, then it makes some sense to pick `C<Comparable<dynamic>>` over `C<dynamic>` because the former helps the user more. 
That is, it expands `T` to the bound but replaces recursive references by `dynamic`, rather than just giving up on expanding and replacing `T` with `dynamic` at the top. (One vs zero expansions of the bound, either will do, two is *right* out).

**Comment by eernstg** [comment]
Konstantin, thanks for the input! I haven't finished, and it's getting late here in CEST, so I'll finish the updates to `instantiate-to-bound.md` tomorrow.

**Comment by eernstg** [comment]
Added the other issue ("enhance instantiate-to-bound such that it also works with a typedef") to the same discussion where the language team works on "create super-bounded types".

**Comment by eernstg** [comment]
`instantiate-to-bound.md` has been debated again and the ability to unfold an infinite type once and create a super-bounded type has been added. In other words, `class C<X extends C<X>> {...}` allows for raw usages like `C c`, which means `C<C<dynamic>>`. If the developer prefers to make it an error when we step outside the unfolding, it's possible to use an explicit super-bounded type like `C<C<Object>>` (so all member lookups except for the members of `Object` will now be compile-time errors when we step outside) or even, when we support that, `C<C<void>>` (so that even touching the object where the static typing stops will be an error).

The relevant CL is [here](https://dart-review.googlesource.com/c/sdk/+/14042), and I expect it to land very soon.

**Comment by jensjoha** [comment]
Compiling 
```
class C<T extends C<T>> {}
C c;
class D<T extends Comparable<T>> {} 
D d;
```

with --strong yields the following:
```
library;
import self as self;
import "dart:core" as core;

class C<T extends self::C<self::C::T>> extends core::Object {
  default constructor •() → void
    : super core::Object::•()
    ;
}
class D<T extends core::Comparable<self::D::T>> extends core::Object {
  default constructor •() → void
    : super core::Object::•()
    ;
}
static field self::C<self::C<dynamic>> c;
static field self::D<core::Comparable<dynamic>> d;
```

which seems to be what we want. Can we close this issue?

**Comment by scheglov** [comment]
SGTM
