### ISSUE TITLE
dartanalyzer is so slow

### ISSUE THREAD

**Issue by Fandekasp** [dart-lang/sdk#31108]
I tried to search for similar issues before posting, but with 5000+ open issues, I don't even know how you guys are managing it :O 
Nov 2016: https://github.com/dart-lang/sdk/issues/25109

I'm trying to use `dartanalyzer` from the vim ALE plugin for auto-linting on file modification. But as reported in their [github](https://github.com/w0rp/ale/issues/1002), I need to wait almost 10 secs when opening the default example file (111 lines), using a Dell XPS 13 9360..
A modern linter should lint such a file in milliseconds. Are there any actions being taken in order to improve the perfs of dartanalyzer ? When can I hope to see a 100x improvement of it ?

Thank you in advance for the support
Cordially

**Comment by bwilkerson** [comment]
> Are there any actions being taken in order to improve the perfs of dartanalyzer?

Yes. We are in the process of moving analysis onto a new front end code base that was specifically designed with performance in mind.

> When can I hope to see a 100x improvement of it?

I don't have a time frame for when this work will be complete, but we're probably looking at a small number of months rather than, say, a small number of days.

> I'm trying to use dartanalyzer from the vim ALE plugin for auto-linting on file modification.

The analysis server is already about 10 times faster than the command-line analyzer, partially because it was designed for exactly this purpose (and I expect the performance of server to also be improved by the new front end).

I would strongly encourage the ALE developers to switch over to using the analysis server for their purposes. (They can find a specification of the protocol here https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html.)

**Comment by matanlurey** [comment]
FWIW, another member of the Dart team ( @natebosch ) is working on an (unofficial) plugin for vim doing exactly that - https://github.com/natebosch/vim-lsc. Maybe you can collaborate.

**Comment by natebosch** [comment]
https://github.com/natebosch/dart_language_server wraps the analysis server following the Language Server Protocol 

I think I have seen some talk of ale getting support for LSP but I don't know if that has gotten anywhere. As Matan mentioned  https://github.com/natebosch/vim-lsc works with this server and there is https://github.com/prabirshrestha/vim-lsp but I don't have any experience with it.

**Comment by Fandekasp** [comment]
Going with langserv is good. Will look into it, thank you for the day and
detailed replies :)
