### ISSUE TITLE
Not renaming top-level field/access consistently.

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31117]
This prints null (I think after https://dart-review.googlesource.com/c/sdk/+/12481):

```dart
int name = 42;

void main() {
  print(name);
}
```

We generate:

```javascript
dart.defineLazy(staticname, {
  get name_() {
    return 42;
  },
  set name_(_) {}
});
staticname.main = function() {
  core.print(staticname.name);
};

```

**Comment by vsmenon** [comment]
@jmesserly - should we be keeping the top-level as `name` here or fixing the access to `name_`?

**Comment by jmesserly** [comment]
In the current design, all static name references must go through _emitStaticMemberName (either directly, or via _emitMemberName/_declareMemberName).

Top level names are not member names, so they should not go through this renaming step. The bug likely occurs because top-level and static class fields are emitted via a similar code path. Here's a fix:

```dart
--- a/pkg/dev_compiler/lib/src/analyzer/code_generator.dart
+++ b/pkg/dev_compiler/lib/src/analyzer/code_generator.dart
@@ -4205,7 +4205,9 @@ class CodeGenerator extends Object
--- a/pkg/dev_compiler/lib/src/analyzer/code_generator.dart
+++ b/pkg/dev_compiler/lib/src/analyzer/code_generator.dart
@@ -4205,7 +4205,9 @@ class CodeGenerator extends Object
       var element = node.element;
       assert(element.getAncestor((e) => identical(e, target)) != null,
           "target is $target but enclosing element is ${element.enclosingElement}");
-      var access = _emitStaticMemberName(name);
+      var access = target is ClassElement
+          ? _emitStaticMemberName(name)
+          : (_emitJSInteropStaticMemberName(element) ?? _propertyName(name));
       accessors.add(closureAnnotate(
           new JS.Method(
               access,
```
I believe this bug occurred because `_emitLazyFields` is kinda weird. Normally we'd emit top-level names via _emitTopLevelName. But that emits the full name, and here we just want the member part of it.

The use of `_emitJSInteropStaticMemberName` is pretty bogus, but it matches old behavior. These aren't really static members, they're top-level ones, and if it's a JavaScript field we shouldn't be emitting it at all. Maybe there's a check elsewhere (because the must be marked isExternal?), I'm not sure. If JS fields can't reach this path, you can just use `_propertyName(name)` for the else branch.
