### ISSUE TITLE
Analysis Server: unable to resolve imports for one package in multi-root environment 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#31126]
For the `build` package (https://github.com/dart-lang/build) we have a few packages all under a top level directory. I can open that top level directory and things work generally, except for one of the directories `e2e_example`. This one always shows a ton of analysis errors (but `dartanalyzer .` doesn't complain).

You can repro by checking out the repo (https://github.com/dart-lang/build) and opening the root folder up in vscode or intellij (both of them have the same issue). You should see errors such as https://gist.github.com/jakemac53/3edf46c5611292894ac4622f2d5ff8d3.

The really weird thing is some packages do seem to be resolvable, for instance package:test and package:build_test imports work, but package:build, package:e2e_example, etc don't work.

**Comment by bwilkerson** [comment]
I just cloned the repo and ran `pub upgrade` in each subdirectory. The upgrade worked everywhere except in `build_compilers`, where I got the following output:
```
Resolving dependencies... (2.4s)
Package build_runner has no versions that match >=0.5.0 <0.6.0 derived from:
- build_compilers depends on version ^0.5.0
```
I get one error reported in 'build_runner/test/server/serve_integration_test.dart':
```
error: A value of type '(Request) → dynamic' can't be assigned to a variable of type '(Request) → FutureOr<Response>'. (invalid_assignment at [build_runner] test/server/serve_integration_test.dart:42)
```
24 in 'e2e_example/tool/build.dart', and a huge number in 'build_compilers' (because of not having a `.packages` file).

The errors in 'e2e_example' are because the `analysis_options.yaml` file in the root directory says to exclude that directory, so server doesn't look inside it to find the `pubspec.yaml` (and hence it's being analyzed without a `.packages` file).

**Comment by jakemac53** [comment]
Ah! I totally forgot we had listed it in the excludes for the root `analysis_options.yaml`. I am a bit confused exactly why that would cause analysis errors (maybe the editors could handle some error case better?).

I have removed the exclude and now the world is happy though, so I am happy. Thanks!
