### ISSUE TITLE
Implement FileByteStore that doesn't grow with incremental compilations

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31138]
There are two implementations of persistent ByteStore available now: [`FileByteStore`](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/byte_store/file_byte_store.dart#L143) itself that grows infinitely as requests to do incremental compilation are processed and [`EvictingFileByteStore`](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/byte_store/file_byte_store.dart#L30) that has a maximum cap on its size, but will either grow up to that size even for small applications with incremental compilations or won't have space for all artifacts for large application.

For Flutter we would like to have a FileByteStore implementation that doesn't necessarily have a maximum size limit, but grows with the size of the application being compiled, rather with the number of incremental compilation requests.

@a-siva

**Comment by scheglov** [comment]
`FileByteStore` is a wrong abstraction level to solve this problem. It stores whatever it is asked to store, and does not know the structure and source of neither keys, nor values.

This problem can be solved on the `KernelDriver` level by using completely different approach to tracking dependencies - using files and modification times, vs. content of files; using single result per file. This is quite a serious change and it will create performance problems for Analysis Server users.

What problem do you want to solve?

**Comment by aam** [comment]
We want to preserve incremental compiler state between Flutter build/run iterations without running users out of disk space.

See https://github.com/flutter/flutter/pull/12417#issuecomment-334823031 too.

**Comment by scheglov** [comment]
With `EvictingFileByteStore` you will not run out of disk space.

**Comment by aam** [comment]
> With EvictingFileByteStore you will not run out of disk space.

Right, but it 
> will  either grow up to that size even for small applications with incremental compilations or won't have space for all artifacts for large application.

**Comment by scheglov** [comment]
Can we make the cache big enough for large applications?
I think growing cache for small applications is not a problem if the cache size is still limited.

**Comment by aam** [comment]
> Can we make the cache big enough for large applications?
> I think growing cache for small applications is not a problem if the cache size is still limited.

We can make cache big enough, if we make a guess as to how large applications can be(what would be your guess, though?)
However then if user has several small apps that they intensively work on, they will run out of space because the cache for each of those app will grow to that max size we have chosen to accommodate large application.

**Comment by scheglov** [comment]
Ah, this might be a point of misunderstanding.
We use a single cache, shared across of all `KernelDriver`s.
So, users never run out of disk space.
The worst thing that can happen is that some results will be evicted.

For Analysis Server we use `1GiB`.
I think kernel files are bigger, especially when we will move to storing transitive outlines.
So, "5GiB ought to be enough for anyone" :-)

**Comment by aam** [comment]
Okay, it never occurred to me that IKG cache was envisioned to be used across multiple applications. It has its advantages and disadvantages. I assume we are comfortable that cached entities are truly reusable across multiple applications, right? Then how will it handle the case where different versions of IKG(coming with different versions of Flutter) will try to use it?

It might be that the cache solves different problem that what we need to solve for Flutter. For Flutter  we just need to persist IKG state to disk so we don't have to parse files we just parsed. Could IKG initialize itself from kernel .dill file produced by previous IKG compilation?

**Comment by scheglov** [comment]
It actually has a lot of advantages - there always was a problem in Analyzer when we has to analyze several checkouts of internal repository, or even several folders in the same repo. For Analyzer these were different analysis roots, so each was parsing and resolving the same files many times. But these files have almost always the same content, so we can reuse all their results.

Each key we put into `ByteStore` is salted with the version of `KernelDriver`. So, the keys are different for different IKG versions. Each version will see and use only their own results in the cache. It is not fine grained, we could in theory reuse some data, e.g. declared names. But it makes the system less stable to mistakes.

The cache results can be reused across IKG restarts (as long as it is the same version of course). If some files don't change, we don't parse or compile them - we load unresolved data (e.g. import/export URIs, defined names, referenced names) from the cache, using the file content hash as the key. If there are library cycles where none of the files changed, we load kernels for these cycles from the cache. Only when files are changed, or the results has been evicted from the cache, we compile anything.

**Comment by a-siva** [comment]
@scheglov the caching strategy you are proposing seems complicated for the problem we want to solve, we need a simple map 
<library_uri> => <kernel data corresponding to library>
we don't need multiple versions of the library we are interested only in the latest version and anytime we recompile a library we will update the kernel data corresponding to it.
The approach of having  a large cache which is shared across multiple kernel drivers just complicates the problem with one instance/version of the kernel driver in a developer session potentially degrading or having an effect on the performance of another instance in another developer session.

**Comment by scheglov** [comment]
Is this a real problem that users have?
Do they often run multiple Flutter development sessions in parallel?

**Comment by a-siva** [comment]
This would be true on Fuchsia where multiple modules which interact with each other are being developed and debugged in parallel.

**Comment by scheglov** [comment]
This does not sound as a typical use case.
Do you think it is?

**Comment by a-siva** [comment]
Not sure why you don't consider it a typical use case, we have people today in the Fuchsia team developing like this.

**Comment by scheglov** [comment]
Well, from my experience I very rarely have to debug more than one application.

If you start two processes, and so request kernels for both, these keys will be marked as recently used, and will be the last to be evicted from the cache.

**Comment by sigmundch** [comment]
I feel the flutter and analysis-driver use cases are different enough that we can't necessarily apply the same solution to both.

I'd like to provide enough flexibility so that the flutter team can adjust what they want to do. 

If I understand things correctly they want a cache that doesn't save historical data, but only the last accepted state of the app and the current not-accepted state. It seems to me that what they are asking for might be doable without a big change in the architecture. In particular, if we look at the hashes stored in `_currentSignatures` and `_lastSignatures`, we can probably figure out what keys from the cache are relevant at a given moment. So when we get a call to `acceptDelta` we can clear all the signatures in the cache that are not actively used.

This might mean adding an API to the cache to get notified about when entires are no-longer used by an IKG instance, and let the cache decide what to do (in the case of the flutter team, they can clear the cache at that moment because they know their cache is not shared).


I know there are disadvantages that you've seen from analysis driver with this design: like redoing work when the user makes edits that return the app to a previous state, and wasting work across IKG instances, but it will definitely help compare IKG to the old hot-reload the VM had in the past.

**Comment by scheglov** [comment]
Well, for IKG this might work.

It is not as simple as just final result signatures, `KernelDriver` might cache some intermediate results, like unlinked information for file to with URIs (which is used to avoid parsing files on every restart). We need somehow associate these intermediate results with files to know that this opaque key is actually a new results for that file, so that the value associated with the previous key with the same suffix (e.g. `.unlinked`, `.kernel`) can be removed. In order to do this we need to extend `ByteStore` API to accept these file tags, suffixes are parts of keys and can be used from keys.

We could make a `ByteStore` implementation that handles files and suffixes, and keeps all its results in memory, and commits them to the file system only on `acceptDelta`. This means that IKG and its special `ByteStore` will need to know about details of `KernelDriver` implementation, but I guess it is OK.

This will work well for updates, but we need a way to know files to results mapping when we create a new `ByteStore` instance. This mapping has to be in a file, and we need update it carefully in case if there are multiple instances running against the same directory in parallel. Hm.. each IKG instance has its own `invalidate` and `acceptDelta`, so while one might accept results for a file, another still might want to get old results if there were not `invalidate` for it. Well, or we might use separate directories for each application. Which means that all Flutter packages, and all other shared packages, will be compiled every time for each application. This is a shame. It seems that it is less expensive if we sometimes have to recompile some files in rare cases when one IKG did `invalidate` and another not.

And another question to consider is whether we want to use the same file system cache for Analysis Server and development session. If something has already been compiled for Analysis Server purposes, why compile it second time for running? Ah... this will work only if we use the same `Target` :-(

**Comment by sigmundch** [comment]
> Well, for IKG this might work.

Cool - let me know if it will be helpful to meet and brainstorm some details, or to discuss API design for this.

> ...

It seems pretty clear that we have a large design space, and that it's too early to commit to any specific approach :-). For flutter, yes: I think they can start by using a different directory each time and they can be careful to not share anything on the first implementation. Later they can optimize this further and switch to a better cache that has sharing.

Correct also that we might not be able to share .dill for multiple targets, I'll ask Kevin a bit about this while he is here.

**Comment by scheglov** [comment]
Actually, I have a better idea.

We still use the shared cache.
But we add a concept of "temporary protected results".

These results are not evicted until they are older than a specified duration (e.g. 24 hours).
This ensures that results for abandoned projects will be eventually cleaned up.

Any accepted kernel will be added to temporary protected results. Once a kernel is not an accepted one, for example because the file to which it corresponds was recompiled and the signature is different now, we remove the previous key from temporary protected results. So, it will be evicted according to the general LRU rule.

This will ensure that even when we run multiple Flutter applications, none of the applications will lose its expensive kernel results, and will be always ready to run.

And we still can share results that are sharable, like same packages :-)

**Comment by sigmundch** [comment]
@aam @a-siva - does that work for you?

I sense that they might want to basically clear everything that is not protected at times. So if you include the option to clear everything that is not protected (e.g. a `flush` method on the cache), that might let them play with different heuristics and decide what works best for them.

**Comment by a-siva** [comment]
Once a kernel is accepted you add it to the temporary protected results, will you at that point immediately remove the previous version of kernel from the temporary protected results?
And yes having a flush method will be helpful.

**Comment by scheglov** [comment]
Yes, once new results are accepted, old results will be immediately removed from the temporary protected results.

As for the `flush` method, I think it is not necessary. It is hard to accept just "we want" without a justification what user problem we are solving. Cache is a possibility to share and reuse results. If you forcibly flush it every time, you lose this possibility. This should be weighted against the problem we are solving by flushing.

**Comment by a-siva** [comment]
Agreed but why don't you let the users of the cache deal with how they want to use the cache instead of enforcing ''you will keep your cache and you will share and reuse results''. If it turns out that sharing and reuse of results in beneficial they would certainly not flush it as often.

**Comment by sigmundch** [comment]
@scheglov - I think the problem here is that they need to evaluate their options first before deciding whether using a cache helps their users.

To be able to do this evaluation, they need to compare it against a no-cache option (an option where they don't store anything on disk other than the protected results.). The `flush` method would give them that option and they will be able to decide what to do.

If you prefer that this is not exposed in the `package:front_end` API, we could make this new cache with protected results extensible, so flutter can subclass it and add the flush method only for their ikg.

**Comment by scheglov** [comment]
OK, I fine with adding `flush` for experimenting.

**Comment by aam** [comment]
Awesome to see the discussion!

> But we add a concept of "temporary protected results".

This concept sounds good to me, I would call it "accepted state", though, perhaps. The thinking is that closely mirrors what was accepted by the client. Did I get that right?

> These results are not evicted until they are older than a specified duration (e.g. 24 hours).

For completeness sake I would consider adding special value for that duration: 0 - meaning that outdated files are removed right away(so space-constrained user doesn't have to do `flush` after every `accept`). Potentially having '-1' indicating that files are never removed unless manually `flush`ed might be useful too, but not sure.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/15861

**Comment by aam** [comment]
Obsolete now.
