### ISSUE TITLE
Dart pad and dartanalyzer bug, `-i` instead of `--i` does not produce a warning.

### ISSUE THREAD

**Issue by TastyCatFood** [dart-lang/sdk#31173]
The following code freezes dartpad and does not produce a warning:
<code>
void main() {
  for(int i=5;i>0;-i){
    print('hi');
  };
}
</code>    
  
Running a similar code offline:  
dartanalyzer detects `+i` and produce the following warning:  
   error • Expected an identifier at test.dart:14:35 • missing_identifier  
But ignores `-i`.
   
Dart VM version: 1.24.2 (Thu Jun 22 15:42:21 2017) on "linux_x64"  
dartanalyzer --version   dartanalyzer version 1.24.2

**Comment by bwilkerson** [comment]
Analyzer doesn't produce an error because `-i` is a valid expression. The value of that expression is to apply the unary operator `-` to the value of `i`, which in the case of integers will return an integer with an equal magnitude and opposite sign. It produces an error for `+i` because the language does not support a unary `+` operator.

While it would be nice if analyzer could detect which expressions have a side-effect, that kind of analysis is not currently supported.

**Comment by TastyCatFood** [comment]
Thanks for explaining, it all makes sense now.   

`-i is a valid expression`,  I get what you mean and you are right but `-i` in ,`for(int i=10;i>=0;-i)` is also not a valid expression in the context...  

Since GCC throws the following for a similar input:  
```
 warning: statement with no effect [-Wunused-value]
     for(int tes=50;tes>0;-tes){
     ^
```   
I have a feeling the dart analyzer surprises some users.    
Not a high priority matter that I agree though.
