### ISSUE TITLE
Kernel should not mark external members as abstract

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#31233]
Kernel should not mark external members as abstract.

**Comment by peter-ahe-google** [comment]
We've discussed this with @kmillikin and it seems to be an oversight in Fasta. An abstract method is something that shouldn't be called because it doesn't have an implementation. An external method has an implementation, but it's provide outside the language.

Furthermore, an abstract method is something that can only appear in abstract classes. External method can appear in both abstract and non-abstract classes.
