### ISSUE TITLE
[VM] Parser confused by `void` in new Function types

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31279]
The following does not trigger any failure with the analyzer:

```dart
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

library library.library;

// This fails in Dart SDK 2.0.0-dev.6.0.
//
// Launch normally, i.e. "dart example.dart".
void main() {
  new Example();
}

abstract class Base {
  void update(void Function(Iterable) updates);
}

class Example implements Base {
  void update(covariant void Function(List) updates) {}
}
```

But at runtime, the VM _does_ throw. I'm not sure what the right behavior is.

```
Unhandled exception:
'file:///Users/matanl/git/vm-class-snafu/example.dart': error: line 19 pos 25: ',' or ')' expected
  void update(covariant void Function(List) updates) {}
```

If you change from the _new_ function type syntax to the _old_, the same thing happens.

I'm having a hard time repro-ing outside of a much larger project, but it is also possible for this syntax _not_ to trigger a syntax crash, but instead cause the `Example` class to not me invokable, causing errors like the following:

```
  NoSuchMethodError: No constructor 'Example' declared in class 'Example'.
  Receiver: Example
  Tried calling: new Example()
```

If someone is interested, I can help them reproduce this bug.

**Comment by matanlurey** [comment]
Here is the reproduction case:

https://github.com/dart-lang/code_builder/pull/157/commits/03d51a7e41aa020b1d083f14aa5f31cbf4e483f2

Undo that diff, and you should see the error above.

**Comment by eernstg** [comment]
I can see a VM bug in the parser (using the 2.0.0-dev.6.0 vm): The parser does not accept a function type with return type `void` after `covariant` (which fails with both the old and the new function type syntax, as you mention).

The other tools seem to work fine. The correct behavior during static analysis is to accept the example. There shouldn't be any run-time errors, either.

The example is a little bit tricky, though, because it declares a parameter covariant in a situation where the given parameter type is actually contravariant. That is, it has the following structure:
```dart
class A {}
class B implements A {}
class C implements B {}

void main() {
  new Example();
}

abstract class Base {
  void update(B updates);
}

class Example implements Base {
  void update(covariant A updates) {}
}
```
There is nothing wrong with this: It allows an overriding declaration to use covariance, e.g., a subclass `class Example2 implements Example` could have `void update(B updates) {}` or `void update(C updates) {}`. But it's a situation which is a bit more complex than the typical covariant parameter declaration.

**Comment by eernstg** [comment]
Here's another context where `void` in a new function type confuses the vm parser:
```dart
main() {
  List<void Function(int)> functions = [(int i) => print(i + 1)];
  functions[0](42);
}
```
This causes the following:
```
'file:///usr/local/google/home/eernst/lang/dart/scratch/201711/n008.dart': error: line 5 pos 8: unexpected token 'void'
  List<void Function(int)> functions = [(int i) => print(i + 1)];
       ^
```

With a type alias it works fine:
```dart
typedef void F(int);

main() {
  List<F> functions = [(int i) => print(i + 1)];
  functions[0](42);
}
```
and it also works with the new function type syntax in the type alias: `typedef F = void Function(int);`.

**Comment by eernstg** [comment]
@matanlurey, I hope it's OK with you that I adjust the title of this issue, otherwise please re-adjust it as needed. ;)
