### ISSUE TITLE
Stopwatch: Support `process.hrtime` when running in Node (not browser)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31303]
https://nodejs.org/api/process.html#process_process_hrtime_time

Would be nice to get higher resolution on Node for perf testing

**Comment by kevmoo** [comment]
CC @nex3

**Comment by joshualitt** [comment]
This is a really interesting idea. However, we're currently moving towards more real world benchmarking of production apps vs microbenchmarks. 

I'm going to close this for the time being because it isn't well aligned with our current focus. If many people feel this is valuable it is something we can revisit.
