### ISSUE TITLE
VM has incorrect reified types of async methods/futures in strong mode

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31324]
Consider the following code:
```dart
import 'dart:async';
class A {}
Future<A> f() async {}
main() {
  print(f().runtimeType);
  print(f() is Future<A>);
}
```

In strong mode, an async method whose static return type is `Future<A>` should return a Future whose reified type is `Future<A>` (or a subtype thereof).  This is necessary so that clients can call `then` on the resulting future, passing in a callback whose argument type is `A`.

When I run the above program using the VM, it prints:
```
_Future
false
```

Which seems to indicate that the VM is not filling in the proper type argument.

See also related tests:
```
tests/language_2/async_congruence_local_test.dart
tests/language_2/async_congruence_method_test.dart
tests/language_2/async_congruence_top_level_test.dart
tests/language_2/async_congruence_unnamed_test.dart
```

**Comment by lrhn** [comment]
Dart 1 only returned `Future<dynamic>` from `async` methods, so the current VM behavior is expectable.

Returning a different kind of future depending on the static type annotation doesn't really work well without type inference. It's all well when you actually write the return type, but for async function expressions, you have to rely on the inferred type. Also, not all async functions have a plain `Future<X>` type as return type. Take:
```dart
void f0() async {}  // No hint, use Future<Object>.
Object f1() async {}  // No hint, use Future<Object>.
f2() async => 2;  // Future<int> ? Or Future<Object>?
Future f3() async => 2;    // Future<dynamic> most likely (instantiate to bounds)
FutureOr<void> f4() async {}  // Future<void>, most likely.
FutureOr f5() async => 4  // I'm not sure what to think ;)
```
Do we have a specification of what to do?

**Comment by stereotype441** [comment]
@lrhn I agree that when no return type is actually written we should use the inferred static type.

I'm not aware of any spec for this.  The spec I would propose is:
> Let `T` = `flatten(S)`, where `S` is the static return type of the async function or method.  The runtime type of the future returned by the async function or method should implement `Future` with type argument `T`.

So for your examples above I would say:
```dart
void f() async {}  // Unspecified since this is an error in Dart 2.0
Object f1() async {}  // Future<Object>
f2() async => 2;  // Future<dynamic> (because type inference infers a return type of `dynamic`)
Future f3() async => 2;  // Future<dynamic>
FutureOr<void> f4() async {}  // Future<void> (because flatten(FutureOr<void>) = void)
FutureOr f5 async => 4  // Future<dynamic>
```
But I'm open to other suggestions.

CC @leafpetersen

**Comment by lrhn** [comment]
```dart
void f0() async {}  // Is valid, should probably return Future<Object>, same as f1.
f2() async => 2;  // Should infer Future<int> and return that. Does it not infer from the body expression?
```
I agree on the rest.

Since we require the return type to be assignable from some `Future<T>`, it can only really be `Object`, `void`, `dynamic`, `Future<X>` and `FutureOr<X>`. With that constraint, returning a `Future<flatten(returnType)>` should be safe, even if if only accidentally so, but I would prefer to just do:
> Let *T* be the return type of the surrounding async function. If *T* is a type variable *Y*, let *T* be the bound of *Y*. Then, if *T* is `Future<X>` or `FutureOr<X>` for any type `X`, then return an instance of `Future<X>`. Otherwise return an instance of `Future<Object>`. 

I don't want any `Future<void>` or `Future<dynamic>` instances unless you deliberately ask for them (and they'll be equivalent to `Future<Object>` instances anyway at runtime)
 
I guess we don't allow 
```dart
T foo<T>() async {}
```
at all (at least we shouldn't, it's unsafe without a bound that prevents `foo<int>()`), and 
```dart
T foo<T extends Future<Object>>() async {}
```
works as written, returning a `Future<Object>`. 
As usual, I have no idea what to do about:
```dart
T foo<T extends Future<T>>() async {}  // or ... extends FutureOr<T>.
```
F-bounds FTW!

**Comment by leafpetersen** [comment]
I think for the most part I agree with the summary that @lrhn gives above.

For soundness, async functions must return a value whose runtime type is a subtype of their declared type.  This means that either we use the inferred type, or we throw a cast error any time the inferred type is not `Future<dynamic>` or a super type thereof, which is not useful.

Conceptually, I think of there being a missing `<T>` on the `async` keyword, and inference has to fill in the `T` in `async<T>`.  It does so by using the return type, whether inferred or not.

Some notes:

1) It is useless to allow an `async` function to have a return type which is a custom subtype of `Future`, since there will be a mandatory downcast, which will fail (`async` doesn't have the hooks to allow plugging in a custom `Future` factory).  Strong mode gives an error if you try to do to (similarly with `sync*`, and I believe `async*` as well).  

2) I don't think generic async functions are currently well-supported, but there's probably no reason not to allow them.  This does raise a question about point 1) though: if we require the return type to be a supertype of `Future<Null>`, then the generic examples above will not work.

3) I'd really like to eliminate all future flattening if possible.  Is there good motivation for the use of it in the original Dart 1.0 spec?

Perhaps the following extension of @lrhn's terminology might cover all of the above:

> Let T be the return type of the surrounding async function. If `T` is a type variable `Y`, let `T` be the bound of `Y`. Then, if T is `Future<X>` or `FutureOr<X>` for any type `X`, then return an instance of `Future<X>`. Otherwise return an instance of `Future<Object>`.  It is a static error if `Future<Null>` is not a subtype of `X`.

It's not immediately clear to me that there is any value in allowing `FutureOr<T>` as the return type, but I guess it doesn't hurt anything.  Are there good motivations for allowing it?

**Comment by leafpetersen** [comment]
@lrhn Can you expand on why you think `void` should be allowed as a return type for async functions?  Currently strong mode makes that an error.

**Comment by lrhn** [comment]
@leafpetersen 
An `async` function should be allowed to say that its return value should be ignored, just as any other function. An `async` function can use `await`, which is reason enough to be one, whether it actually returns a useful value or not. I would see myself using this as:
```dart
void main() async {
  ... something await something ...
}
```

I don't know if there is a problem with `void f() async { return; }` - if we don't allow `return` with not expression in an `async` function, we should. We should even allow it in one with return type `Future<void>`.
I guess I'm saying that whether you can/should use `return;` or `return e;` should be based on the *flatten* of the actual return type inside an `async` function. If we don't do that yet, we should.

**Comment by mraleph** [comment]
We currently build the following in Kernel: 

```
    final asy::Completer<asy::FutureOr<a::A>> :completer = asy::Completer::sync<asy::FutureOr<a::A>>();
```

so transformed method is actually returning `Future<FutureOr<A>>` is not properly handled in the VM (see https://github.com/dart-lang/sdk/issues/31377).

I am gonna fix Kernel to build `asy::Completer<A>` instead.

**Comment by leafpetersen** [comment]
> An async function should be allowed to say that its return value should be ignored, just as any other function.

Ok.  I don't have strong feelings about this at all, just a vague sense from background discussions that ignoring the result of async functions was generally considered badness.

**Comment by lrhn** [comment]
Ignoring a `Future` is often a bad sign because you can be ignoring an error that will tear down your isolate. That's why an async function returning a future shouldn't be ignored. However, "being `async`" and "returning a `Future`" are separate concepts - you can have non-`async` functions returning `Future`s and you shouldn't ignore those. You can have `async` functions return non-`Future`/ignorable values (return type `Object` or `dynamic` as usual, and now also `void`).

Ignoring the result of an async function that *itself* states that you should ignore it (by having `void` as return type) should be perfectly OK.

**Comment by leafpetersen** [comment]
> You can have async functions return non-Future/ignorable values (return type Object or dynamic as usual, and now also void).

I don't think so, unless something is really changing?  An async function is going to return a Future, not matter what you declare the return type to be, and no matter what you return (or don't return) from the body.  At least, that's how they work now, is this changing?


> Ignoring the result of an async function that itself states that you should ignore it (by having void as return type) should be perfectly OK.

Ok.

**Comment by matanlurey** [comment]
Honestly using `async/await` _without_ returning a `Future` is a bug.

**Comment by lrhn** [comment]
> Honestly using async/await without returning a Future is a bug/error.

I think that's needlessly simplistic.
I have no scruples writing:
```dart
void main() async {
  await somethin();
  await for (var x in other);
}
```
or 
```dart
void dispatch(operation) async {
  try {
    (await getServer()).dispatchOperation(operation);
  } catch (e) {
    logger.log(e);
  }
}
```
These are *perfectly reasonable* functions. They are *designed* to do something and not return a result.
You can easily write these using non-`async` syntax, e.g.:
```dart
void dispatch(operation) async {
  getServer().then((server) => server.dispatchOperation()).catchError(logger.log);
}
```
There is nothing wrong with this, it's completely equivalent to the `async` version above. Remember, being `async` is an *implementation* detail, not a part of the function signature.

There are requests for a way to ignore a future, because sometimes you do know that the future returned by an async operatation, because some operations are known to not return anything relevant (and it gets in the way of people using linters that complain if you ignore a future). Some of those functions should probably just return `void`.
(Another idea is to cast the result to `void`: `operationToIgnore() as void;` - ignore *that*!).

**Comment by matanlurey** [comment]
> ```dart
> void main() async {
>  await somethin();
>  await for (var x in other);
> }
> ```

This might be really common code for the Dart Infra teams to write, but is not common otherwise, as you wouldn't use this pattern on the client code (you'd want to show loading indicators, error messages on failure, etc).

**Comment by lrhn** [comment]
>>You can have async functions return non-Future/ignorable values (return type Object or dynamic as usual, and now also void).

> I don't think so, unless something is really changing? 

My bad phrasing. You can have async functions *declared* as returning `Object` or `dynamic`. That was always the case. Since we changed `void`, they should also be allowed to declare themselves as returning `void`.

We complain if the declared return type of an `async` function is not something that a future can be assigned to, which means if it isn't `Object`, `dynamic`, `void`, `FutureOr<X>` or `Future<X>` (for some `X`), because we know that a future *will* be returned. It's just as if the body of a normal (non-async, non-generator) function contained a `return someFuture;`. That's a compile time error unless that future can be assigned to the declared return type. It can if the return type is `void`, so no need for a *special* case for `void`.

**Comment by leafpetersen** [comment]
> Since we changed void, they should also be allowed to declare themselves as returning void.

Ok.  It certainly seems to be a case where the programmer is expressing intent.

> We complain if the declared return type of an async function is not something that a future can be assigned to, which means if it isn't Object, dynamic, void, FutureOr<X> or Future<X> (for some X), because we know that a future will be returned. It's just as if the body of a normal (non-async, non-generator) function contained a return someFuture;. That's a compile time error unless that future can be assigned to the declared return type. It can if the return type is void, so no need for a special case for void.

This doesn't seem right.   We currently most certainly do give an error if you write `return someFuture` in a non-async `void` function.   Am I missing your point?  Or has this changed in some way?  Do we intend to allow:

```
void foo {
  return 3;
}
```

**Comment by lrhn** [comment]
We don't want to allow that example, no.

The thing with `async` functions is that you always return a future, whether you write `return e;` or not.
So, if an `async` function has a return type that you cannot assign a `Future` to, it's a strong mode error. That's why we have constraints on the valid return types of `async` functions (similarly for async* and sync*, but there is never a reason to have one of those and ignoring the result, so we don't see that happening, but `void foo() async* {}` is technically valid).

If there are `return e;` statements in the body, we *also* check that *Future<flatten(X)>*, where *X* is the static type of `e`, is assignable to the declared return type. (If there are no returns, all we need to know is that `Future<Null>` is assignable to the return type, which is what we already checked above).

**Comment by leafpetersen** [comment]
Works for me.

**Comment by matanlurey** [comment]
@lrhn I have opposition to this. See a background issue:

https://github.com/dart-lang/angular/issues/710

It should be safe to write the following interface for a framework:

```dart
abstract class Widget {
  void update() {
    print(1);
    doUpdate();
    print(2);
  }
  void doUpdate();
}

class MyWidget extends Widget {
  @override
  void doUpdate() { /* Fine. */ }
}

class AsyncWidget extends Widget {
  @override
  Future<void> doUpdate() { /* Error. We aren't going to await this. */ }
}
```

Unless I misunderstand, your proposed changes would make both cases legal. The only benefit I can see is being able to use "async/await", which honestly has been more of a source of bugs than user benefit.

**Comment by Hixie** [comment]
I don't really understand what the proposed change is here.

**Comment by matanlurey** [comment]
To make it legal to have an implicit (explicit?) return of `Future` in a `void` method.

**Comment by Hixie** [comment]
Seems a bit weird. I'd probably disallow it by style guide. I don't have an opinion on whether the language itself should disallow it. Can you return anything else in a void method?

**Comment by leafpetersen** [comment]
> Seems a bit weird. I'd probably disallow it by style guide. I don't have an opinion on whether the language itself should disallow it. Can you return anything else in a void method?

Explicitly returning something in a `void` method is forbidden.  But you are allowed to pass a function with return type `dynamic` where a function with return type `void` was expected.  This means that if you call a function with return type `void`, you might get anything back.

I believe we are all in agreement that explicitly returning something from an `async` method with return type `void` would be an error.  But every `async` function (even one typed to return `void`) implicitly returns a future, even if it doesn't do an explicit return. So the question is, should we then reject `async` functions with the return type `void` but no explicit return?

**Comment by lrhn** [comment]
> So the question is, should we then reject async functions with the return type void but no explicit return?

I say no. I see no reason to disallow it, and plenty of reasons for actually using it.

Back when it was an error to return a `Future` from a `void` function, we could disallow `void`+`async` functions early because we knew they would fail when called. That is no longer the case, so now the restriction is just preventing users from writing their fire-and-forget async code using async syntax.

The "workaround" would be:
```dart
void fireAndForget() {
  () async {
    actual body using await.
  } ();
}
```
Let's not make people do that. :)

**Comment by eernstg** [comment]
I see a declaration like `void fireAndForget() async { .. }` as an indication that the returned value (which could of course be anything, but will be a `Future<T>` for some `T`) is not intended to be useful. You could argue that `Future<void> fireAndForget() async { .. }` is somehow a "more correct way to say the same thing", but that would actually indicate that it is useful to synchronize with the termination of the action taken, and the phrase "fireAndForget" clearly says that you shouldn't even need to synchronize.

So, to me, `void` seems to be the most informative return type you can give for a "fireAndForget" action.

Next point: Does this make sense from the body of the function? I think it does, because the body of an `async` function _never_ explicitly returns anything --- the return value is the future which is created implicitly at the beginning of the body, and explicit `return` statements will provide a value for completing that future. The body of the `async` function does not have access to that future because it is not denoted by a name in scope, so we will never get the conflict where something is explicitly returned and the return type is `void`. You could claim that it is implied that the value that completes the future should then be ignored, but that's a separate step, and I do not think that we need to take that step. In other words, I see no problem allowing `return e;` in `void f(...) async {...}`.

So `void f(...) async {...}` is perfectly fine, and useful, and we do not need any new concepts or rules for dealing with it.

**Comment by Hixie** [comment]
How do I catch an exception from one of these void-returning async functions?

**Comment by lrhn** [comment]
> How do I catch an exception from one of these void-returning async functions?

You don't, because there is no exception. If the async function fails, it probably handles it internally, like all other fire-and-forget functions. 
There is nothing *new* here, you could always write functions like that using `then` calls.
```dart
void fireAndForget() async {
  var x = await something();
  var y = await x.more();
  y.doIt();
}
```
is just an async equivalent to:
```dart
void fireAndForget() {
  something.then((x) {
    x.more().then((y) {
      y.doIt();
    });
  });
}
```
If anything here throws asynchronously, you can't handle it. It's an unhandled async error, and *it's deliberate* - the function's author *told* you that there would be no return value. They, not you, are in charge of handling issues. Otherwise they should have written it differently.

So, if you write code like this, you are probably certain that errors won't happen, or you are handling them yourself. Not every asynchronous function can meaningfully be a void function, but those who can should be allowed to.

**Comment by Hixie** [comment]
> If the async function fails, it probably handles it internally, like all other fire-and-forget functions.

My experience is that most exceptions aren't caught. :-)

**Comment by lrhn** [comment]
> My experience is that most exceptions aren't caught. :-)

I hope that most *errors* are not caught, but *exceptions* are (to use the Dart terminology, where "exceptions" are deliberately thrown and intended to get caught, and errors are unintended and expected to crash your program).

In either case, that shouldn't affect whether you can write `void foo() async { ... }`, because you can already write `void foo() => future.then(...);`.

Or, in other words, `async` is an annotation on the *body*, it should not affect the typing.
It acts like it's an implicit `=> new Future().._completeWith(asyncBody)`, and previously we disallowed such `void .. => nonVoidExpression` functions, but now we don't, and `async` *bodies* do not need to be special.
