### ISSUE TITLE
Cannot preserve reified type in general

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31371]
The following code fails at runtime with `'UnmodifiableMapView' is not a subtype of type 'Map<String, List<int>>'` - we currently have no way of typing this correctly.

This is blocking an internal team.

```
Object freeze(Object obj) {
  if (obj is List) {
    return new List.unmodifiable(obj.map(freeze)); // ObservableList in internal example
  } else if (obj is Map) {
    obj.forEach((k, v) {
      obj[k] = freeze(v);
    });
    return obj;
  }
  return obj;
}

void main() {
  var data = <String, List<int>> {
    'hello': [1, 2],
    'world': [3, 4],
  };
  print(data.runtimeType);
  data = freeze(data);
  print(data.runtimeType);
}
```

**Comment by vsmenon** [comment]
@floitschG @anders-sandholm

**Comment by eernstg** [comment]
As long as we have covariance and no direct support for `opening` existential types, we can't hope to express the actual type arguments of a given `List` or `Map` statically. So we can't pass that/those actual type argument(s) to the `_.unmodifiable` methods (which aren't generic anyway, at this point), nor as type arguments to `map` or `new Map()`, etc. We could deal with this kind of problem at the type system level, but that would require some notable extensions.

Moreover, there are lots of places in the given example where the type information is lost.

However, we might still be able to improve the situation a bit by letting the implementation of `List.unmodifiable()` create a list whose type argument is the same as the incoming `Iterable`, and similarly for `Map.unmodifiable`. That might not be so hard (for native methods like these), and it would preserve the actual type arguments in a number of situations where they are currently lost, essentially for free.

Another approach would be to add more methods to the given classes (`List` and `Map`, so it's of course a delicate issue to make changes, but for one's own classes it might be easier to just go ahead and do it):

We could have methods for creating a new data structure of the same type:

```dart
class List<E> .. {
  ...
  List<E> get cloneEmpty => <E>[];
  List<E> get unmodifiableCopy; // Native.
}

class Map<K, V> .. {
  ...
  Map<K, V> get cloneEmpty => <K, V>{};
  Map<K, V> get unmodifiableCopy; // Native.
}
```
which would be used rather than `new Map()`, `List.unmodifiable`, etc.

As long as you use these "run-time type preserving methods" you'd preserve the actual type arguments, and you would be able to work around the remaining sore spots: a `myList.map((x) => e);` would become `List newList = myList.cloneEmpty; myList.forEach((x) => newList.add(e));`, etc.

So we would need to do many things before it really works, but it wouldn't be impossible.

**Comment by vsmenon** [comment]
@eernstg the actual internal example involves a wrapper list type.  E.g.,

replace:

```
return new List.unmodifiable(obj.map(freeze));
```

with

```
return new ObservableList(obj.map(freeze));
```

where we need to thread the type param through.

**Comment by vsmenon** [comment]
Some options:

(1) Add a method to `List` or `Iterable`:
```
typedef Builder<S> = Function<S>(List<S>);
class Iterable<T> {
  ...
  build(Builder f) => f<T>(this); 
}
```

The code above becomes something like:
```
return obj.build(<T>(list) => new ObservableList<T>(list.map(freeze)));
```

(2) A language / pattern matching feature:

```
if (obj is List<?T>) {
  // T is bound to the reified type of obj
  return new ObservableList<T>(obj.map(freeze));
}
```

(3) Other?

**Comment by vsmenon** [comment]
(3) Following @eernstg 's thought on opening a type - add a method to `Type`.

```
class Type {
  // If [obj] is an instance of `this`, return the application of the universal function `f`.
  open(obj, f);
}
```

The following:
```
Map.open(<String, int>{}, <K, V>()=>K);
```
would return `String`.

The above would become:

```
if (obj is List) {
  // T is bound to the reified type of obj
  return List.open(obj, <T>() => new ObservableList<T>(obj.map(freeze));
}
```

@lrhn @leafpetersen - this is a library-esque variant of Lasse's pattern matching suggestion.

**Comment by rakudrama** [comment]
The impact of  `obj is List<?X>` is, for dart2js, not very different to `obj is List<X>`.
We need the same information as the current subtype check.

Is the new local name **X** a value binding, or a type binding?

In my proposed new type representation, where all type expressions are accessed via a single lookup in a single type-environment object, the matching operation would return a new, extended, environment binding `X` on success, and `null` on failure.
This is why I think it should be a type binding. The matching operation can be cached, but I worry a little that the number of local environments (permanent because they are cached) is multiplied by the number of parameterizations of List.

What is the scope of X?

The versions with `open` look impossible for a compiler to analyze.

**Comment by leafpetersen** [comment]
> Is the new local name X a value binding, or a type binding?

Type binding.

**Comment by lrhn** [comment]
The scope of `object is List<?X>` would be the code directly gated by that test. That is, the same places where we would do type promotion of `object` due to the `is` check. In fact, the static type of `object` would be promoted to `List<X>` in that scope.

It's similar to the idea of introducing new variables in type checks, like `x is List<int> list` which would introduce `list` as the type-promoted version of the value of `x` in the following scope. It works even if `x` cannot be promoted itself (e.g., because it's not a local variable).

**Comment by eernstg** [comment]
It's important that `object is List<?X>` binds `X` as a type, such that we can proceed and use it as a type, e.g., `return new Map<int, X>();`, and it is also crucial that the run-time value of `X` is the exact, actual type argument of `object` at the type `List`, not just the statically known approximation. Otherwise we wouldn't satisfy the main requirement of this issue: preserving the types.

This also means that we can support safe operations that we cannot express today:
```dart
void f(List xs, Object o) {
  if (xs is List<?X>) {
    if (o is X) xs.add(o);
  }
```
The invocation `xs.add(o)` does not require a dynamic check on the type of the actual argument, because it is _statically known_ that the type of `o` is a subtype of the typing requirement on the argument to `xs.add`. Today, we can't create any such situations at all outside the body of `List`.

We may or may not have that already, but we would then need to have an entry point for `List.add` which does not type check its actual arguments. In a tight loop, that might matter.

**Comment by sigmundch** [comment]
We just discussed the `Type.open` and how it can impact dart2js, our fear is that it doesn't prevent users from writing something like:

```dart
(complexExpression).runtimeType.open(...)
```

It will be easier for us to implement this feature if we can know statically what type is being "opened". One way to achieve this is to make `open` a static function that takes the raw type as a type argument, instead. For example:

```dart
openType<R>(R instance, Function f);
```

So a user would write:
```dart
if (xs is List) {
  openType<List>(xs, <T>() => ...);
}
```

**Comment by eernstg** [comment]
Definitely an existential `open` should open a statically known type. Consider the situation where the type is the dynamic type of the given instance: We need to bind some names of type variables to the corresponding actual type arguments, and for the dynamic type we wouldn't know the number of type arguments (`class B<X> extends A<X, X> {...}`, so we have 1 or 2 type arguments if the type could be `A` or `B`)  nor the meaning of each type argument (`class B<X> extends A<List<X>> {...}` so we have `X` or `List<X>` as "the type argument" if the type could be `A` or `B`). It's simply not very helpful to know that we have the type arguments `SomeType, AnotherType` for a given instance if we don't know which generic type received those type arguments.

It will make much more sense if the existential open refers to a specific, statically known type:

```dart
if (x is A<?X>) {
   ... // `X` is in scope, has bound from `A`, and `x` has type `A<X>`.
}
```

In its scope, `X` is bound to the actual type argument for the class `A` of the value of `x`. It is important that it is the actual type argument and not just some statically known approximation. In other words: Assume that this actual type argument at some point in the execution (it could be different next time we reach the same point in the code) is `S`. Then `x is A<S>` would evaluate to true, and there would be no subtype `U` of `S` such that `x is A<U>` is true. In other words, `X` is the _exact_ type argument of `x` at `A`.

The value of `x` might still be an instance of some subtype of `A<X>`, like `B<Y>` where `X` is `List<Y>`, but the important point is that when `T` is the value of `X` at run time, `x` has type `A<T>`, and there is no subtype `S` of `T` where `x is A<S>` is true.

This is what it takes to make the following type safe (no implicit casts, not even covariance related ones):

```dart
if (xs is List<?X>) {
  X x = xs[0];
  xs.add(x);  // No implicit downcast needed here.
}
```

There is no implicit downcast because `x` is known to have the type which is the element type of that list, not just a statically known supertype thereof.

(Of course, we have special cases like this:
```dart
class MyList extends List<num> {
  void add(int a) {...}
}
```
which are "doubly covariant", but it's no problem to spot these and generate an extra covariance check at the beginning of the body of `MyList.add` in a specialized entry point that is otherwise not type checking its argument.)

I would naively assume that `x is G<?X1..?Xk>` is no harder to support than it is to perform a test like `x is G<T1..Tk>` for any given type argument list `T1..Tk`. In that case it is necessary to check the given instance (the value of `x`) and see if it has any generic instantiations of `G` in its supertype graph, and then check that the actual type arguments given to `G` in the supertype graph is an element-wise list of subtypes of `T1..Tk`. This is something that we support today and that we have no proposals for eliminating, so, apparently, we can tolerate the costs incurred by being able to do that.

As I mentioned, `openType` would have to be rather magic in order to enable meaningful type checking of the second argument: Generic functions taking different numbers of type arguments are simply unrelated, so the type of the second argument of `openType` would have to be a plain `Function`, or `openType` would have to have it's own specialized built-in type checker.

So I'd clearly prefer `if (x is G<X1..Xk>) {...}` over `openType`.

**Comment by vsmenon** [comment]
Chatted with @leafpetersen @sigmundch @rakudrama @crelier and @a-siva on implementation feasibility in the backends.

Proposal right now is add `openType` - as sketched out by Siggi above - to `dart:_internal`.

I.e.,
```
Object openType<T>(T instance, Function f);
```

with a runtime error if the type param arity of `T` and `f` mismatch.

We feel this is doable and low risk in the near term in the vm, dart2js, and ddc, and is mostly the same plumbing we'd need for a future language change.

This still leaves the question of how to expose to users.  Given timeline / urgency, I suspect we'll need to expose `openType` more or less as is somewhere.

**Comment by eernstg** [comment]
OK, this means that we could get the dynamic semantics with the smallest amount of disruption, and it would still be possible to introduce strongly typed language support for this feature later on. Cool!

**Comment by floitschG** [comment]
I would go for a simpler version that only accepts `List`, as this can potentially be easier to implement. If necessary we can always make `openType` more flexible. (After all, it's only visible from the specific package that is allowed to import `dart:internal`).

The easiest is to create a Google3 package and allow it to import `dart:internal`. At least in dart2js it's straight-forward to make an exception for a library that has a specific path.

**Comment by leafpetersen** [comment]
From offline discussion, it sounds like the preferred path is to try to expose this as little as possible, which means something like the `dart:internal` approach that @floitschG suggests above.  This keeps the user facing surface minimal.

I'm a little concerned that this formulation does allow users to open type variables:

```dart
class C<T> {
   foo(T x) {
     openType<T>(x, <S>() {print(S);}
    }
}

void main() {
  new C<List<int>>().foo([]); 
}
```

I don't think this matters from a primitive implementation standpoint, but it does mean that we couldn't later on simply implement the `openType` function using the proposed language feature, at least as we've discussed it so far.  Perhaps that should be supported by the language feature as well?  That is, perhaps you should be able to write something like:

```dart
foo(T x) {
      if (x is ?<S?>) { 
          print(S);
       }
    }
```

In any case, keeping the user facing surface of this minimal is probably good.  This might be an argument for at least starting with the suggestion from @floitschG to only expose this at specific concrete types.

**Comment by leafpetersen** [comment]
Okay, the plan is as follows:

- Expose the full `openType` API in an SDK visible only library
  - If it is better for the implementations, this can also be restricted to support only the specific interfaces exported (see below), but we may need to expand the set of exported interfaces 
- Expose a set of monomorphic unpack functions at specific interfaces in a Google internal only package for now, in anticipation of further language changes to address the use case.

The unpack functions exposes in the package will include at least (exact names TBD):

```dart
T unpackIterable<T>(Iterable instance, T Function<S>(Iterable<S>));
T unpackList<T>(List instance, T Function<S>(List<S>));
T unpackMap<T>(Map instance, T Function<K, V>(Map<K, V>));
```

**Comment by munificent** [comment]
Here's my in-progress patch: https://dart-review.googlesource.com/c/sdk/+/26467

Right now, it just exposes the full `openType()` function (I called it `extractTypeArguments`) in the package API. Should I clamp it down to just the functions you list?

**Comment by leafpetersen** [comment]
Yes, the packages should only expose `extractListTypeArguments` et al.

Also, is it worth passing the instance to the callback as shown above to make the common case where you want to use the dispatched on value at the appropriate type easy?

**Comment by anders-sandholm** [comment]
Yay - happy to see this one moving forward. 
Will be great to get more of the migration work unblocked.

**Comment by lrhn** [comment]
The type-specific functions are luckily easy to write, you only need one per class hierarchy that shares a type variable (so one for `Iterable<T>`, then `List<T>` etc. can be written in terms of the iterable one).
```dart
// Use the system functionality.
R unpackIterable<R>(Iterable iterable, R callback<T>(Iterable<T> iterable)) =>
    _extractTypeArguments<Iterable>(iterable, <T>() => callback<T>(iterable as Iterable<T>)) as R;

// Just use unpackIterable for all other iterables.
R unpackList<R>(List list, R callback<T>(List<T> list)) => 
    unpackIterable<R>(list, <T>(Iterable<T> iterable) => callback<T>(iterable as List<T>));
// Ditto for Set, Queue.

Object _extractTypeArguments<T>(T value, action<T>()) => 
    internal.extractTypeArguments<T>(value, action);
```

**Comment by munificent** [comment]
Closing this now that there is an API to do it. It may not be the ultimate solution — we probably want real language support and syntax — but it's sufficient for now.
