### ISSUE TITLE
Please merge revision 0af5298845574517862e0a4cfabace1488ec2196 into stable channel

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/sdk#31378]
@whesse @mit-mit @kasperl

<Describe the critical problem this merge is fixing - include issue numbers if applicable>

Issue #24693. This allows users to create a SecurityContext that trusts the builtin root CAs, and which can be modified without affecting other code that relies on SecurityContext.defaultContext (which was previously the only way to obtain a SecurityContext with builtin trust roots).

This is needed by Dart gRPC, to allow us to modify the SecurityContext to specify protocols for ALPN, without other libraries making TLS requests suddenly (and unexpectedly) defaulting to HTTP/2.

<What revision(s) needs to be merged - please annotate revisions with reason if more than one>

0af5298845574517862e0a4cfabace1488ec2196

<Please try out the merge yourself. If there are merge conflicts please resolve these and upload the cl to rietveld and provide a link here>

This merged cleanly.

**Comment by whesse** [comment]
Merged in stable 1.24.3.  This is still in the process of being released, but the linux and windows SDKs are available at http://gsdview.appspot.com/dart-archive/channels/stable/raw/1.24.3/sdk/ . Please test them to see that this issue is fixed, and that the merge of https://codereview.chromium.org/2903743002 also works as intended.

**Comment by jakobr-google** [comment]
Thanks! I've tested the linux, windows, and macOS builds. All work for me. :)
