### ISSUE TITLE
Deterministic VM and Snapshot builds

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#31427]
- [x] Canonical const object tables should not be hashed by address
- [x] Concurrent sweep should be disabled for stable heap iteration order
- [x] WriteStream::Align etc should zero skipped bytes
- [x] Code collection, usage counter decay and background compilation should be disabled when creating app-jit snapshots
- [ ] The tag handler should canonicalize URIs as URIs relative to the working directory instead of as absolute URIs
- [x] The loader should return results in the order requested
- [x] The seed for identity hashes should be deterministic
- [x] Don't embed the build time in the binary (version.cc)
- [x] Disable clang/gcc build ids
- [x] Make Observatory build deterministic

@zanderso @sortie @athomas

**Comment by davidmorgan** [comment]
Great to see this being worked on. Please let me know when you're done--as there are some places we had to stop using snapshots and will want to start using them again.

**Comment by zanderso** [comment]
@rmacnak-google Can you mark the things that are done?

**Comment by mraleph** [comment]
These tests are really flaky on linux x64 and ia32 release builds as well.

Examples of builds:

https://ci.chromium.org/buildbot/client.dart/vm-linux-release-x64-be/26111
https://ci.chromium.org/buildbot/client.dart/vm-linux-release-x64-be/26124
https://ci.chromium.org/buildbot/client.dart/vm-linux-release-ia32-be/26554

I am marking them `Pass, Fail` by default because this is too much flakiness.

**Comment by rmacnak-google** [comment]
I currently have no plans to work on relativizing URIs, which providing a stronger kind of reproducibility than we require for effective sharing on Fuchsia.

What is a multi-root system? It doesn't sound related to this issue.

**Comment by keertip** [comment]
When generating dart 2 snapshots for flutter in google3, we had problems with hot reload not working due to full paths in the generated kernel files. @aam added support for passing in a root and uri scheme to frontend server so that when a scheme is specified, the generated kernel file no longer contains full paths. If the vm did something similar, script snapshots would be deterministic.

**Comment by dgrove** [comment]
Do we need more work for Dart2Stable? (My impression is no, in which case we could move this out of the milestone).

**Comment by rmacnak-google** [comment]
This is resolved for Dart 2; we won't resolve it for Dart.
