### ISSUE TITLE
Type inference of function expressions leads to unfortunate cast failures

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31436]
Consider the following code:

```dart
void f(Object o) {
  int Function() g;
  g = () => o; // (1)
  print(g());
}
main() {
  f(1);
}
```

The front end compiles this to:
```
library;
import self as self;
import "dart:core" as core;

static method f(core::Object o) → void {
  () → core::int g;
  g = (() → core::Object => o) as{TypeError} () → core::int;
  core::print(g.call());
}
static method main() → dynamic {
  self::f(1);
}
```

As a result, when the program is run, an exception occurs at `(1)`.

I *think* the front end is following the informal spec for type inference correctly; the informal spec says this about type inference of function expressions (see https://github.com/dart-lang/sdk/blob/2cf8040c9e047518e6673c6b92a8e917c3ff5ff3/docs/language/informal/local-inference.md):

> - The expression `<T>(P x) => e` is inferred as `<T>(P x) => m` of type `<T>(P)
>   -> M` in context `<S>(Q) -> N`
>   - If `e` is inferred as `m` of type `M` in context `N[T/S]`
>   - Note: `x` is resolved as having type `P`  for inference in `e`

When inferring `() => o`, the context is `() -> int`, therefore we infer `o` in context `int`.  It has type `Object`, therefore `() => o` is inferred as having type `() -> Object`.

But this is not useful, since `() -> Object` is not a subtype of `() -> int`.  So the front end generates code that is guaranteed to fail.

It seems like we would be more in line with user intent if we changed the rule to:

- The expression `<T>(P x) => e` is inferred as `<T>(P x) => m` of type `<T>(P)
  -> N` in context `<S>(Q) -> N`
  - If `e` is inferred as `m` of type `M` in context `N[T/S]`
  - Note: `x` is resolved as having type `P`  for inference in `e`

(Note: I changed `<T>(P) -> M` to `<T>(P) -> N` in the first line)

In which case the code above would be compiled to:

```
library;
import self as self;
import "dart:core" as core;

static method f(core::Object o) → void {
  () → core::int g;
  g = () → core::int => o as{typeError} core::int;
  core::print(g.call());
}
static method main() → dynamic {
  self::f(1);
}
```

and the program would run to completion without raising an exception.

@leafpetersen what do you think?

**Comment by leafpetersen** [comment]
> think the front end is following the informal spec for type inference correctly;

Well, since I don't seem to have specified what the type of `o` in context `K` should be, I could try to argue that it's not....  but I won't.  :)  I really need to put some more work into that.

The spec (or at least your very reasonable reading of it) is not matching the intent here.  The return type from the context type should be pushed down into the body, and used as both the static and runtime return type of the function.  In the piece of spec that you quote, this would correspond to either using `N[T/S]` as the return type, or equivalently ensuring that whenever you infer in context `K` , the resulting term has inferred type `K`.

Interestingly, we get this half-wrong in the existing analyzer based implementation.  We use the incorrect `() -> Object` type statically, but seem to do the right thing for the reified type.  You can see this with the following code, which correctly prints `() -> int` as the runtime type when run on DDC.

```dart
void f(Object o) {
  int Function() g;
  g = () => null; // (1)
  print(g.runtimeType);
  print(g());
}
main() {
  f(1);
}
```

**Comment by stereotype441** [comment]
Hmm, after further research I re-discovered #29606.  It seems that analyzer's rule is:
- For function expressions declared with `=>` syntax, if the type inferred from the RHS of the `=>` is `dynamic`, the function gets its return type from the context; otherwise it gets its return type from ths RHS of the `=>`.
- For function expressions declared with `{}` syntax, if the type inferred from the function's return statement(s) is a subtype of the return type from the context, then that type is used for the return type; otherwise the return type from the context is used.

I replicated this rule in my initial implementation of type inference for the front end, which explains the behavior described above.

So, if I make a variation on my previous example, this Dart code:
```dart
void f(Object o, int i) {
  num Function() g;
  g = () { return o; }
  g = () { return i; }
}
```

currently compiles to:
```
static method f(core::Object o, core::int i) → void {
  () → core::num g;
  g = () → core::num {
    return o; // (1)
  };
  g = () → core::int {
    return i;
  };
}
```

Which seems quite reasonable, assuming that (1) is changed to `return o as{TypeError} core::num;`.

So I propose that we address this bug by changing the behavior of `=>` functions so that they match `{}`.  As a side effect that will let us close #29606.

**Comment by leafpetersen** [comment]
I think what you are proposing is a variant of something that @eernstg has advocated for: using a more precise synthesized (upward) type for inferring the type of closures, since function variance is sound.  I think there are two things I like about your proposal: firstly that it only uses the upward type when it's a subtype of the context type (hence ensuring substitutability), and secondly that it does inference on the body using the downwards context first.  This means that the following example should work correctly:

```dart
void test() {
  List<Object> Function() g;
  g = () { return [3]; } 
  assert(g is List<Object> Function());
  assert(g is! List<int> Function());
  g().add("hello"); // No runtime error
  List<int> l = [3];
  g = () { return l; } 
  assert(g is List<Object> Function());
  assert(g is List<int> Function());
  g().add("hello"); // runtime error
}
```

cc @lrhn @munificent @floitschG for thoughts.

**Comment by eernstg** [comment]
I believe the **idea** that you refer to and that I was pushing was that (1) with a mutable entity (such as a mutable List) we must use the type-from-context directly to obtain the inferred type of a list literal and other instance creation expressions, because "having a `List<int>` with type-from-context `List<Object>` will break when you add a `String` to it, and the developer explicitly requested `List<Object>`", but (2) when creating an **immutable entity** it is OK to give it a type which is a **proper subtype of the type-from-context**.

In particular, we can assign a proper subtype of the type-from-context to a **function literal**, so we can give it more general argument types and a more special return type (so, e.g., we can infer the type `int Function(Object)` for `(o) => 42` in a context where the type-from-context is `num Function(Null)`). This would be helpful for making the "most general" function types on the form `T Function(Null, ...)` useful; with a requirement to use the type-from-context directly on function literals, the resulting functions would end up having `Null` as the argument types, which all but prevents successful invocations.

I suppose this is what you call 'using a more precise synthesized (upward) type for inferring the type of closures', except that we may choose that subtype by upward inference, or we may use any type we want which lies between those two extremes (type-from-context vs. upwards inferred).

In the [**example**](https://github.com/dart-lang/sdk/issues/31436#issuecomment-347707541), the first assignment to `g` would provide the type-from-context `List<Object> Function()` to `() { return [3]; }`, so we may give that function literal any type which is a subtype thereof, e.g., the type `List<int> Function()` that we would get from upwards inference.

So I'd say that the example does not use this idea, it just gives the function literal the type-from-context precisely. It's not obvious that we want to use a proper subtype thereof, however, because it would make the invocation of `add("Hello")` a run-time error, and the developer did explicitly state that a `List<Object>` was the intended return type. So I think that's working in a way that makes a lot of sense!

I suspect that this is a general phenomenon: It is probably a good idea to **follow** the **type-from-context** slavishly **with** respect to **return types**, because return types are covariant and hence it is generally possible to express whatever is intended. With **argument types**, however, we need `Null` to express "anything goes" due to contravariance, so they are more likely to **justify** these proper subtypes (i.e., having a type annotation which is a **proper supertype** of `Null`).

The second assignment to `g` is different: In this case we do _not_ use the type-from-context (which would give `() { return l; }` the type `List<Object> Function()`, and `return l;` would then include an implicit upcast from `List<int>` to `List<Object>`). I can see that this is in fact the behavior we get from dartdevc today. I suppose we could justify it as follows: (1) a function literal is immutable, so we can safely give it a type which is a proper subtype of the type-from-context, (2) the bottom-up analysis gives us the return type `List<int>`, (3) during bottom-up analysis, we did not make any "non-trivial" choices (such as deciding whether `[3]` should mean `<int>[3]` or `<Object>[3]`), so this time we actually use the bottom-up type (as opposed to the treatment of `() { return [3]; }`)

So maybe the crucial issue here is actually the notion of "do we have a bottom-up type which does not embody non-trivial decisions?", which seems to guide the choice between the two different treatments of a function literal.

**Comment by leafpetersen** [comment]
Ok, I'd like to see us do the following for inferring the return types of functions (closures and local named functions):

1) Arrow functions are inferred exactly as if they were de-sugared into block bodied functions
2) For block bodied functions, inferred in a typed context with return type `K`:
   - Inference for the return expressions `E0...En` is done in context `K`, yielding inferred types `M0...Mn`
   - If `M = LUB(M0...Mn)` is a subtype of `K`, then the inferred return type of the function is `M`
   - Otherwise, the inferred return type of the function is `K`
3) For block bodied functions inferred in an empty return context, inference is done as in 2), and the inferred return type is `M`.

Notes:
 - Inference is always done using the context type, if any
   - Hence any inference of unsafely covariant generic parameters is done using the context type
 - The inferred return type of the function is always a subtype of the context type
 - The inferred return type may be a subtype of the context type
 - There is no need to revisit return expressions to insert implicit downcasts:
    - If any `Mi` is not a subtype of `K`, then we know that the return type of the function will be `K`, and a downcast can be inserted.
   - If `Mi` is a subtype of `K`, then the final return type will either be `K`, or an upper bound that includes `Mi`, and in either case, no downcast is required.

Examples:

```dart
void test() {
  List<Object> Function() g;
  g = () { return [3]; } 
  assert(g is List<Object> Function());
  assert(g is! List<int> Function());
  g().add("hello"); // No runtime error
  List<int> l = [3];
  g = () { return l; } 
  assert(g is List<Object> Function());
  assert(g is List<int> Function());
  g().add("hello"); // runtime error
  Object o = l;  
  g = () { return o; } // No implicit downcast on the assignment, implicit downcast on the return 
  assert(g is List<Object> Function());
  assert(g is! List<int> Function());
  assert(g is! Object Function());
  g(); // No runtime error;
  o = 3;
  g(); // Failed runtime cast on the return type of f
}
```

This reconciles the current inconsistent behavior in analyzer strong mode.  Using this approach will be more friendly for some existing coding patterns that currently don't work well, such as:

```dart
find(List<Object> l, Object o) => l.firstWhere((e) => e == o, orElse: () => null);
find(<int>[3], 3);
```

which currently throws at runtime with the following error because of the inferred type of the closure:

```
Type '() => Object' is not a subtype of type '() => int' in strong mode Error
 ```

Modulo reflective uses that look at the string representation of the runtime type, this should be non-breaking.

This deviates from the simple inference story that "the downwards context always wins", but in a mostly invisible way.  You may get something which is always substitutable for the downwards context type.  In the rare case that a user is relying on the following, this will not do what they expect:

```
Object Function() g = () => 3;
assert(g is! int Function());  // Assertion will fail with this change
```

I think that on net this change results in less surprising behavior.

@lrhn @eernstg @stereotype441 Please let me know if you see issues with this that I'm not seeing.

**Comment by stereotype441** [comment]
This sounds reasonable to me.  I'll get to work on the front end implementation in the next few days and I'll update this bug if I run into any problems.

**Comment by leafpetersen** [comment]
As a secondary followup, @eernstg raises the possibility of extending the idea of using the principal type (rather than the context type) for argument types as well as return types (as discussed in the previous comment).  That is, when inferring the type of a closure `(x) => E` in a downwards context `Null -> T`, us `Object` for the type of `x` instead of `Null`.  

Pros:
  - The resulting inferred closure is strictly substitutable for the version inferred with `Null`
  - This makes using `Null ->  T` as the type of "any unary function returning T" much more usable, since the inferred function will no longer fail if dynamically applied to a non-null value.
  - No additional (and no fewer) method send errors and warnings will be emitted (`Null` and `Object` have the same method set.

Cons:
  - With --no-implicit-casts, additional cast errors may show up
  - Less static and runtime checking if you actually intend the type to be Null
  - Implementation cost

This is something that can be done later as an essentially non-breaking change, which argues for pushing it off.

On the other hand, this change would likely on balance reduce migration cost, since currently using `Null -> T` as the type of "any unary function" interacts badly with inference.

```
Object apply(Object Function(Null) f, Object x) {return (f as dynamic)(x); }
apply((x) => x; 3); // Throws a runtime error
```

I'm fairly disinclined to make additional changes to inference now unless the implementation and migration cost is very close to zero.  @stereotype441 , thoughts?

**Comment by stereotype441** [comment]
Moving the discussion of the secondary followup to its own separate issue to avoid confusion: https://github.com/dart-lang/sdk/issues/31546

**Comment by jmesserly** [comment]
quick question @stereotype441 -- the test you added called bug31436_test is marked "RuntimeError" on every platform, is that intended?

It looks like it just had an assert condition flipped:
```dart
  assert(g is List<Object> Function());
  assert(g is! List<int> Function());
  assert(g is! Object Function());
```
The last assert is guaranteed to fail if the first assert succeeded, because `() -> List<Object>` is a subtype of `() -> Object`. If I fix that line to be `assert(g is Object Function());` it passes on DDC/K. I'll see about getting a CL for that.

**Comment by stereotype441** [comment]
@jmesserly Oops, I believe you are right.  I'll be happy to review that CL when you've got it ready.
