### ISSUE TITLE
gen_snapshot fails on kernel file (flutter aot --preview-dart-2)

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31431]
5ac157c5724c1ea58ea9813d86a09a96e9e8cc58 seems to be the culprit of `flutter aot --preview-dart-2` build failures on https://flutter-dashboard.appspot.com/build.html (https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_gallery__preview_dart_2_build.dart)

cc: @a-siva

**Comment by mkustermann** [comment]
I've reverted this CL in d38c08d97358ebe4ee30e557bfee339dddda9b7a and try rolling the revert into engine/flutter and then rolling flutter into google3.

After some debugging, I found that the issue is caused by 5ac157c which causes us to no longer load the root library anymore which makes us crash somewhere deep in the library dictionary lookup code.

I've also added a check in the code to avoid SEGV in this case but rather report an error, see pending CL here: https://dart-review.googlesource.com/c/sdk/+/23002

**Comment by a-siva** [comment]
See my comment in https://github.com/dart-lang/sdk/commit/5ac157c5724c1ea58ea9813d86a09a96e9e8cc58

**Comment by aam** [comment]
Solved by d38c08d
