### ISSUE TITLE
Type inference for for-in statements is limited

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31440]
Consider the following code:
```dart
T f<T>() => null;

void test(Iterable<num> iter) {
  for (var w in f()) {} // (1)
  for (var x in iter) {} // (2)
  for (num y in f()) {} // (3)
  num z;
  for (z in f()) {} // (4)
}
```

The front end currently type infers this as:
```dart
T f<T>() => null;

void test(Iterable<num> iter) {
  for (dynamic w in f<dynamic>()) {} // (1)
  for (num x in iter) {} // (2)
  for (num y in f<Iterable<num>>()) {} // (3)
  num z;
  for (z in f<dynamic>()) {} // (4)
}
```

The inference in (2) and (3) seems reasonable to me.  (1) and (4) seem like they could be inferred better.

I would like to change (1) to infer as:
```dart
  for (dynamic w in f<Iterable<dynamic>>()) {} // (1)
```

And I would like to change (4) to infer as:
```dart
  for (z in f<Iterable<num>>()) {} // (4)
```

I believe this will make it easier to implement the necessary implicit downcasts for for-in loops.

Similar changes will have to be made for "await for" loops, using `Stream` rather than `Iterable`.

@leafpetersen and @munificent, what do you think?

**Comment by leafpetersen** [comment]
I think what you're suggesting is that if the variable used in the `for(x in exp)` is declared to have type `T`, then use `Iterable<T>` as the downwards context while inferring `exp`.  

I think this works great when `exp` has some type which is a subtype of `Iterable<T>`, but not so great when it doesn't.  We ran into this before:

https://github.com/dart-lang/sdk/issues/25916

I suppose we could do the downward inference, but special case the downcast to cast each element as it comes out rather than cast the whole thing, but that probably makes your implementation harder, not easier?

We could go back to casting the iterable, but that feels little unfriendly.  

@munificent thoughts?

**Comment by stereotype441** [comment]
@leafpetersen Yes, that's what I'm suggesting, but just to be clear: DDC _already_ uses `Iterable<T>` as the downwards context when inferring `for (T x in exp)`; it's only when `x` is a previously declared variable, or when `x` is declared without a variable (`for (var x in exp)`) that it uses `dynamic` as the context.  So all I'm proposing is to make the downwards context consistent among these two cases.  I think the impact of that change should be low, since tightening up the downward context should only change behavior in the case where `exp` needs to undergo type inference; if `exp` already has a type (e.g. because it's a reference to a previously declared variable), then the downward inference context is ignored.

But I'm glad you brought up #25916, because it makes it clear that even if the downward context is `Iterable<T>`, that doesn't mean that `exp` should be implicitly downcast to `Iterable<T>` at runtime; rather, the individual elements _yielded_ by the iterable should be implicitly downcast to `T` at runtime.  I'll make sure the implicit downcast logic (which I'm working on now) is consistent with this DDC behavior.

**Comment by munificent** [comment]
> So all I'm proposing is to make the downwards context consistent among these two cases.

That sounds reasonable to me.

>  the individual elements *yielded* by the iterable should be implicitly downcast to T at runtime. 

Yup! This should work:

```dart
for (int i in <Object>[1, 2, 3]) { ... }
```

From the user's perspective, the sequence expression itself doesn't really have a meaningful generic type. All they care about is the types of the values that it produces. And it's pragmatically useful to support the above case because that's a common pattern to work around variance issues where you have a collection whose static type is more general than the set of values you know it contains.

**Comment by leafpetersen** [comment]
Ok.  This all sounds reasonable to me.
