### ISSUE TITLE
Can default constructor infer "const" for me?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31446]
This is a common pattern in Flutter among others:

```dart
class HelloWorldWidget extends StatelessWidget {
  Widget build(_) => new Text('Hello World');
}
```

I can't create this widget `const` though:

```dart
(_) => const HelloWorldWidget();
```

... unless I add the following boilerplate:

```dart
class HelloWorldWidget extends StatelessWidget {
  const HelloWorldWidget();

  Widget build(_) => new Text('Hello World');
}
```

I somewhat understand not making this auto-const:

```dart
class Example {}
```

But what about this:

```dart
abstract class Base {
  const Base();
}

class Example extends Base {}
```

**Comment by lrhn** [comment]
Making a class "const-able" is a commitment. Any number of changes are incompatible with that. Most of these changes affect the constructor (having a body, having a computation in the initializer list), but just adding a non-final private field can prevent the class from being const.

If your constructor is automatically const, then clients of your class might start using that, whether you meant it or not. If you didn't intend that const, then doing any of these (otherwise invisible) changes is now breaking because the automatic const becomes automatically non-const. There is no warning at your end, you just break your clients on something that you never intended to do.

So, `const` is a commitment, and we require you to opt-in to it explicitly.  I don't see that changing.

If writing the const constructor is too cumbersome, we could work on shorter syntaxes for that.
Maybe you can get away with just `const constructor();` instead of having to write the name (having to repeat the name is already annoying). Maybe we can allow you to write `const class X { ... }` which will ensure ... something (but we probably can't make all constructors const, so I'm not sure exactly what we would promise - at least we can make the default constructor const, but it's a lot of syntax to reserve for such a small effect).

In any case, not introducing `const` automatically is a feature, and we prefer it that way.

**Comment by zoechi** [comment]
Perhaps a quick-fix on the class for a default const constructor would do?

**Comment by matanlurey** [comment]
I haven't seen the need for this in a while

**Comment by eseidel** [comment]
I ran into this today:

```
class Foo {}

class Bar extends Foo {
  final int one;
  const Bar(this.one);
}
```

I was surprised that I had to add `const Foo();` to make Bar be allowed to be const.  I guess I understand better after Leaf's response, but I was still surprised.  🤷

**Comment by pedromassango** [comment]
Just hit this today. Reading through this thread (specifically https://github.com/dart-lang/sdk/issues/31446#issuecomment-346756128) made me realize that this feature makes sense.
