### ISSUE TITLE
||= operator crashes the compiler

### ISSUE THREAD

**Issue by dskloetg** [dart-lang/sdk#31464]
I have an `x = x || y` in my code and when I change it to `x ||= y` it crashes the compiler when I try to build the app. The unit test works fine though.

http://cl/177018393
http://sponge/55d81721-568d-459f-a71f-480c5828082b

**Comment by lrhn** [comment]
The `||=` operator isn't valid Dart 1, it will be valid Dart 2.
(Shoulnd't crash anything, though).

**Comment by sigmundch** [comment]
Hi @dskloetg, thanks for filing.

It appears that I already fixed this issue, it just hasn't been rolled to you. The fix landed in 606e8502f8, which appears to be included in the sdk 2.0.0-dev.4 (from your logs, it seems you are using 2.0.0-dev.3).

I'm closing the issue here assuming this will be fixed on your end as soon as we roll the new sdk.
