### ISSUE TITLE
Generic part of runtimeType is not preserved

### ISSUE THREAD

**Issue by kezhuw** [dart-lang/sdk#31466]
```dart
import 'dart:async';

class GenericValue<T> {
  const GenericValue(this.value);
  
  final T value;
  
  factory GenericValue.from(T value) {
    return new GenericValue(value);
  }
  
  static fromValue<V>(V value) {
    return new GenericValue<V>(value);
  }
}

void main() {
  int i = 0;
  print((new GenericValue(i)).runtimeType);
  print((new GenericValue<int>(i)).runtimeType);
  print((new GenericValue.from(i)).runtimeType);
  print((GenericValue.fromValue(i)).runtimeType);
  print((GenericValue.fromValue<int>(i)).runtimeType);  

  print('\n');

  print((new GenericValue(i)) is GenericValue<String>);
  print((new Future.value("xxxx")) is Future<int>);
  print((new List.from(const <int>[1, 2])) is List<String>);
}
```

Outputs:
```

GenericValue
GenericValue<int>
GenericValue
GenericValue
GenericValue

true
true
true
```
Dart VM version: 1.24.2 on "macos_x64", same result on [DartPad](https://dartpad.dartlang.org/718810461be7f390b095191ebed91f39) with strong mode enabled.

No sure whether this is related to #30355, #31360 and #31324 .

**Comment by eernstg** [comment]
With dartdevc you get the following output:
```
GenericValue<int>
GenericValue<int>
GenericValue<int>
GenericValue<int>

false
false
false
```
which might be the output that you expect. The reason why you don't get this with the virtual machine and with dart2js generated code is that they do not implement the dynamic semantics of strong mode. In particular, they will not perform type inference, so `new GenericValue(i)` will mean `new GenericValue<dynamic>(i)` etc; and `dynamic` is a bottom type as well as a top type, so `GenericValue<dynamic>` is a subtype of `GenericValue<String>`).

There is no special connection to #30355 or #31360 (generic constructors), because it is already possible to provide all the required type arguments for this example without that feature. Similarly, the topic of #31324 does not overlap with this issue.

However, you can make the choice to avoid type inference by specifying all the type arguments explicitly:
```dart
import 'dart:async';

class GenericValue<T> {
  const GenericValue(this.value);
  
  final T value;
  
  factory GenericValue.from(T value) {
    return new GenericValue<T>(value);
  }
  
  static fromValue<V>(V value) {
    return new GenericValue<V>(value);
  }
}

void main() {
  int i = 0;
  print(new GenericValue<int>(i).runtimeType);
  print(new GenericValue<int>(i).runtimeType);
  print(new GenericValue<int>.from(i).runtimeType);
  print(GenericValue.fromValue<int>(i).runtimeType);

  print('\n');

  print(new GenericValue<int>(i) is GenericValue<String>);
  print(new Future<String>.value("xxxx") is Future<int>);
  print(new List<int>.from(const <int>[1, 2]) is List<String>);
}
```
With that, you'll get the same behavior from dartdevc, and you will also get it from the virtual machine with `dart --reify-generic-functions test.dart` if the above snippet is stored in `test.dart`. 

You can't go all the way with dart2js, unfortunately, but you will get this:
```
GenericValue<int>
GenericValue<int>
GenericValue<int>
GenericValue


false
false
false
```
The missing bit is that the type argument passed to the generic function `GenericValue.fromValue` does not get reified and hence it's not available for `new GenericValue<V>(value)` in the body.

So you can get somewhat closer today, if you're willing to be more explicit on type arguments.

With the upcoming language update (Dart 2) you will get support for reified type arguments and inference in all Dart tools.

**Comment by kezhuw** [comment]
It might sound expected in the implementation sense. But from client's perspective, I gain no guarantee from static typing against third party usage. Image a function with argument `List<String> strs`, it bomb when calling `strs[0].length` while it should bomb at function calling time, better if compile time.

Also it introduces gotchas and coding burden to do intuitive programming.

Last, thanks! And expecting to see release of Dart 2.

**Comment by eernstg** [comment]
> It might sound expected in the implementation sense. But from client's perspective..

You're right, we can't quite avoid surprises during this time of transition where programs are sometimes checked according to the strong mode rules (and the Dart 2 rules will be very similar), and the run-time semantics is still Dart 1. I hope that discussions like this one will help sorting out the cases where such a clash occurs.

> Image a function with argument `List<String> strs`, it bomb when calling `strs[0].length`
> while it should bomb at function calling time, better if compile time.

That doesn't happen in general. What you saw was (1) no inference, hence type arguments are `dynamic` rather than an inferred `int` or similar; (2) `dynamic` is a bottom type as well as a top type; and (3) type arguments passed to generic functions are not reified (type arguments to classes are reified). That's all it takes to get the behavior you reported.

However, if you run programs in Dart 1 checked mode (as well as in strong mode, that is: dartdevc, and in the upcoming Dart 2), you will get all the type checks needed for maintaining heap soundness. That is, if you have a variable (which includes locals, instance variables, parameters, etc) of type `T` and assign a value to that variable (which includes passing an actual argument corresponding to a given formal parameter) of type `S`, where we do not have `S <: T`, you'll get a dynamic error. In particular, if you pass an instance of a type that is not a subtype of `List<String>` for the parameter `strs` then you'll get a dynamic error at the call, rather than an error during execution of the function body, e.g., at `strs[0].length`. So it's almost correct to say "that just can't happen (except in Dart 1 production mode)".

The one thing that would still make it possible to have such a failure is the fact that `List<dynamic>` is a subtype of `List<String>` _in Dart 1_ (that is, during execution with the virtual machine or when running dart2js generated code), so if `strs` is a `List<dynamic>` then `strs[0].length` may be a `noSuchMethod` event.

So it's true what you are saying (it can "bomb when calling `strs[0].length`"), but only when a couple of issues have conspired against us, some of it caused by incomplete support for strong mode execution and the rest caused by considering `dynamic` as a subtype of all other types. And it will be fixed.

**Comment by kezhuw** [comment]
Got it! Thanks!
