### ISSUE TITLE
Clarify how Dart2JS will implement Dart 2.0

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31463]
I'm currently treating them in my head as the following:

| Tool       | Description                        |
| -------- | ------------------------- |
| DDC       | Developer/Debug Mode.  |
| Dart2JS | Production Mode.             |

That means I don't expect Dart2JS to [fully] implement Dart 2.0. For example:

```dart
void method3<A, B, C>(A a, B b, C c) {
  // Implementation detail.
  return _combine3(a, b, c);
}

void main() {
  method3([1, 2, 3], 'Hello', {'name': 5});
}
```

... is this required to emit the ~following code? ...

```js
main: function() {
  F.method3(
    [1, 2, 3], 
    "Hello",
    P.LinkedHashMap__makeLiteral([C.Type_List_naM, true]),
    [[P.List, P.int],
    P.String,
    [P.Map, P.Type, P.bool]]),
  );
}
```

If so I can't possibly see how we can emit decent JavaScript. It's just not meant to propagate _another_ type system around in production code. I totally understand having this in DDC or in Dart2JS in some sort of debug mode where you want to do heap soundness checks.

**Comment by lrhn** [comment]
Technically, an implementation of Dart should implement the Dart semantics. Dart 2 doesn't have a production mode where types aren't checked, like Dart 1 did.

If a program isn't using some data at run time, the compiler can throw it away. That's just an optimization - we don't require anything about the resulting code except that it's behavior is indistinguishable from the correct semantics. If we can compile the entire program down to `print(false);`, then that's fine too (but likely not possible due to that pesky undecidable halting problem).

In this case, if it's clear that the type parameters are not used (they are inferred and only used to type check the values they are inferred from?), then compilation can probably realize that it can omit them. If the types are also used to infer type parameters for `_combine3`, then maybe they are used. It's all optimization and irrelevant-code+data elimination.

Now, most likely we will also have an *invalid* Dart implementation mode in dart2js, one that is similar to the current `--trust-type-annotations` or similar. With that, more optimizations are possible, and as long as the program is correct in some specific ways, the compiled program will still behave correctly. If the program isn't correct, the failure mode will be inconsistent with the Dart semantics.

**Comment by matanlurey** [comment]
@lrhn:

> Now, most likely we will also have an invalid Dart implementation mode in dart2js

Let me stop you there. There is nobody who will use the other mode (i.e. spec mode).

**Comment by matanlurey** [comment]
While I think all of my concerns are still valid (and nobody is using spec mode, as expected), I don't see this issue being beneficial anymore.
