### ISSUE TITLE
Implementation of correct int64 integer semantics using new frontend

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#31479]
We should have proper int64 semantics implemented using the new frontend.

  * [ ] VM implementation
  * [ ] Analyzer implementation

This is a placeholder issue so it can be referred to in status files.

**Comment by mkustermann** [comment]
For reference, the VM has currently faulty logic [here](https://github.com/dart-lang/sdk/blob/0bf5ca8e47510410c829edea82ea5028ed052a7c/runtime/vm/object.cc#L18373):

```c++

static const char* kMaxInt64Plus1 = "9223372036854775808";

RawInteger* Integer::New(const String& str, Heap::Space space) {
    ...
    if (FLAG_limit_ints_to_64_bits) {
      if (strcmp(cstr, kMaxInt64Plus1) == 0) {
        // Allow MAX_INT64 + 1 integer literal as it can be used as an argument
        // of unary minus to produce MIN_INT64 value. The value is automatically
        // wrapped to MIN_INT64.
        return Integer::New(kMinInt64, space);
      }
      // Out of range.
      return Integer::null();
    }
    ...
}
```

**Comment by kmillikin** [comment]
@sjindel-google will take on the front-end part of this.

**Comment by alexmarkov** [comment]
It looks like a duplicate of https://github.com/dart-lang/sdk/issues/31339. And that issue is already referenced in status files.

@mkustermann, you're completely right about the kernel front-end: it doesn't handle integers according to the spec yet. However, could you please clarify why the quoted logic is faulty? Afaik VM supports both MIN_INT64 and unsigned hex literals without kernel / with old VM parser. The only sidestep from the spec is that VM allows MAX_INT64+1 literals to be used everywhere (spec restricts their usage to arguments of unary-).

**Comment by mkustermann** [comment]
@alexmarkov According to florian integer literals outside of int64 range cause a compile-time error, which the VM doesn't implement. The only exception is if the integer literal uses hex syntax, which makes us not issue a compile-time error.

**Comment by alexmarkov** [comment]
@mkustermann, is there any other problem in the VM besides accepting MAX_INT64+1 literal where it should not be accepted? All other literals should be handled correctly, including compile-time errors for literals which are out of range (except MAX_INT64+1). This exception was done deliberately in order to avoid rejecting correct programs with MIN_INT64 when running without kernel. With proper handling of literals in the kernel front-end it is harmless and shouldn't matter. As soon as we drop old parser and fully switch to the kernel front-end we could remove this logic.

**Comment by mkustermann** [comment]
This sounds good @alexmarkov . I guess the reason this slipped into c++ is that flutter wanted to try out the int64 semantics without using the new frontend.

I didn't know about the other bug you filed back then, I've just run into this during work making the constant transformation ready to be enabled by default in aot. We had then more discussions with language team and I've added a test to the language_2 suite, which checks for the compile-time error (couldn't find an existing test).

**Comment by a-siva** [comment]
as mentioned by @alexmarkov can we close this as a duplicate of #31339

**Comment by alexmarkov** [comment]
AFAIK common front-end has all necessary support for Dart 2.0 fixed-size integers, so closing this issue.
