### ISSUE TITLE
Dart2JS: Fields of sealed classe not promoted to JS field

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31506]
```dart
void main(_Foo input) {
  if (input?.name != null) {
    print(true);
  }
}

class _Foo {
  String name;
}
```

... emits ...

```js
if ((input == null ? input : input.get$name()) != null)
  P.print(true);
```

I imagine this is safe to promote to `input.name`, instead of generating a method?

**Comment by rakudrama** [comment]
`Foo` is not defined in your program.

**Comment by matanlurey** [comment]
Sorry, this was a bug, but is still true once defined.

**Comment by rakudrama** [comment]
Please provide exact repro instructions.

Without `--trust-type-annotations`, `input` could be anything non-null, e.g. a String. get$name() ensures a NoSuchMethodError for a String or other non-_Foo argument.

With `--trust-type-annotations`, the input is _Foo or null, but since there is no `new _Foo()`, it is only `null`. The code I see for main in this case is completely optimized away:

```js
    main: [function(input) {
    }, "call$1", "bug1a3l__main$closure", 2, 0, 7],
```
