### ISSUE TITLE
Socket doesn't implement addError() from StreamSink

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#31504]
The `Socket` class is [declared as implementing](https://github.com/dart-lang/sdk/blob/3347b700dfab614507132594a1bcd8a7630eadd9/sdk/lib/io/socket.dart#L516) `IOSink`, which in turn implements `StreamSink`. However, it doesn't actually seem to have an `addError()` method. You can see this by running the following code:

```dart
import 'dart:io';

main() async {
  (await Socket.connect('google.com', 80)).addError;
}
```

Running against Dart 2.0.0-dev.7.0, this produces:

```
Unhandled exception:
NoSuchMethodError: Class '_Socket' has no instance getter 'addError'.
Receiver: Instance of '_Socket'
Tried calling: addError
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      main (file:///usr/local/google/home/nweiz/goog/pkg/test/test.dart:4:44)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by lrhn** [comment]
Added throwing `addError`. The socket can't send the error anyway (and therefore probably shouldn't have been a `StreamSink` to begin with, just a `Sink`.

**Comment by nex3** [comment]
@lrhn Which commit added `addError`?

**Comment by lrhn** [comment]
That would be 3a769b9dbedfef6f18d14ba39dd2ba667019e8f1
The added method just throws. We can make it forward the error to the `done` future and close the socket. If so, we should probably document that that is what a `Socket` does when you add an error.

**Comment by brianquinlan** [comment]
@lrhn

I'm not sure what the advantage of forwarding the error to `done` would be. Presumably we want people to call `Socket.addError` once, realize that it doesn't have useful semantics, and fix their code.

So how about I just document that `Socket.addError` will throw so maybe the broken code won't get written in the first place?

**Comment by lrhn** [comment]
I don't remember the reasoning either. Maybe it was just the only possible place to put an error.

Adding an error to a sink is intended to push it to the *other end*. In this case, that makes no sense, because the other end is not code which can handle an error. 

The `done` future completes when the other end says that it's done, or communication breaks down with the other end (whatever that means). It's a place where errors happening due to an `add` failing *can* be reported.

So, if `addError` is supposed to work, its only possible intent would be to cancel the connection (an error has happened at the sink-side which prevents normal continuation, otherwise why tell the sink about it), which also means that it would make sense to signal the other end that the sink is done, and put the error into the `done` future to document the reason things broke down.

But then you can also just call `close`, and since it's probably your own code waiting for the `done` future, you can signal it in a different way.
Making `addError` throw `UnsupportedError`, and documenting it as not supported, SGTM.

**Comment by nex3** [comment]
I think the important use-case here is people writing code that's polymorphic over different `StreamSink`s. It's very useful to have _consistent_ behavior there, even in cases where some sinks may not fully support some operations.

I think throwing `UnsupportedError` is wrong here for two reasons. First, it's inconsistent with `WebSocket`, which forwards the _original_ error to `done`. Second, it hides information about the underlying cause of the error—it's likely that if polymorphic `EventSink` code encounters an unrecoverable exception, it'll pass it to its sink because it has no better way of handling it. Throwing away that error message and replacing it with an `UnsupportedError` is actively unhelpful for debugging.

Note that the [`stream_channel`](https://pub.dev/documentation/stream_channel/latest/stream_channel/StreamChannel-class.html) package, which specifically exists to provide a polymorphic view over two-way channels, _requires_ that sinks that can't send errors forward them as-is to `done`.

**Comment by lrhn** [comment]
Seems like a good enough reason to me.
So, send it to `done` and close the sink (because completing `done` means the sink is closed).
