### ISSUE TITLE
`pub build` fails when nested in a directory named `packages`

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#31500]
Several folks in Fuchsia have hit this issue when building Topaz (TO-604). An equivalent error in the standalone Dart SDK can be reproduced with:

```
mkdir -p packages/dart-sdk
cd packages/dart-sdk
gclient config --unmanaged https://dart.googlesource.com/sdk.git
gclient sync
cd dart-sdk/sdk
./tools/build.py -mrelease runtime
```

```
FAILED: observatory/build/web/main.dart.js 
python ../../tools/observatory_tool.py --sdk=True --silent=True --directory /usr/local/google/home/rmacnak/packages/dart-sdk/sdk/out/ReleaseX64/gen/observatory_copy/runtime/observatory/ --command build /usr/local/google/home/rmacnak/packages/dart-sdk/sdk/out/ReleaseX64/observatory/build
Command failed: /usr/local/google/home/rmacnak/packages/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/dart /usr/local/google/home/rmacnak/packages/dart-sdk/sdk/tools/sdks/linux/dart-sdk/bin/snapshots/pub.dart.snapshot build -DOBS_VER=2.0.0-edge --output /usr/local/google/home/rmacnak/packages/dart-sdk/sdk/out/ReleaseX64/observatory/build
output: Loading source assets...
Loading dart_to_js_script_rewriter, initialize/build/loader_replacer, initialize, web_components/build/mirrors_remover and web_components transformers...
Building observatory...
[Info from Dart2JS]:
Compiling observatory|web/main.dart...
Build error:
Transform Dart2JS on observatory|web/main.dart tried to load missing input dart-sdk|lib/sdk/out/ReleaseX64/gen/observatory_copy/runtime/observatory/web/packages/$sdk/lib/dart_shared.platform.
Build failed.
```

**Comment by rmacnak-google** [comment]
CC @zra @abarth

**Comment by matanlurey** [comment]
Is this a new error? Pub hasn't really changed this behavior in a long time.

(I believe Bob is OOO, @jakemac53 is your best hope)

**Comment by rmacnak-google** [comment]
I don't believe pub has changed, just people are now building in a directory structure the Dart SDK hasn't seen before.

**Comment by matanlurey** [comment]
Can they temporarily not use the name `packages` to avoid this being a P1?

**Comment by rmacnak-google** [comment]
@abarth Should `fx` be running the build in a chroot to minimize environment differences?

**Comment by abarth** [comment]
Which use of the name `packages` in Fuchsia is causing the trouble?  We map the Dart SDK to /some/path/picked/by/the/developer/third_party/dart.

> Should `fx` be running the build in a chroot to minimize environment differences?

That would be nice.  We currently clear out the environment before running the build.  However, not everyone is required to use `fx`.  It would be helpful to know what specific use of the work `packages` is causing the trouble in order to think up workarounds.

**Comment by abarth** [comment]
I found To-603, which describes the problem in more detail.  It sounds like the word "packages" is in the part of the path that the developer picks on their own, which is probably why @rmacnak-google suggested a chroot.

Maybe a good option in the sort term is just to improve the error message.  If the Dart SDK build cannot function in a subdirectory of "packages", perhaps the build could error out with a friendly message explaining the problem, linking to this issue, and suggesting the workaround of having the develop move their source tree to another directory until this issue is resolved.

**Comment by munificent** [comment]
Moving the bug over to: https://github.com/dart-lang/pub/issues/1753. I'll follow up there.

**Comment by jakemac53** [comment]
Closing since pub build no longer exists in dart 2.
