### ISSUE TITLE
Dart2JS: static final fields more expensive than lazy statics

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31501]
[Not expecting this to be handled before CFE]

Reproduction case:

```dart
void main(dynamic disableTreeShaking) {
  disableTreeShaking.foo = [
    new DartLazyField().useBar(),
    new UserLazyField().useBar(),
  ];
}

class DartLazyField {
  static final _bar = new Bar();

  DartLazyField() {
    return; return;
  }

  useBar() {
    return _bar;
    return null;
  }
}

class UserLazyField {
  static Bar _bar;

  UserLazyField() {
    _bar ??= new Bar();
    return; return;
  }

  useBar() {
    return _bar;
    return null;
  }
}

class Bar {}
```

Generates:
```js
DartLazyField: {
  "^": "Object;",
  useBar$0: function() {
    return $.$get$DartLazyField__bar();
  },
  DartLazyField$0: function() {
    return;
  },
  static: {
    DartLazyField$: function() {
      var t1 = new F.DartLazyField();
      t1.DartLazyField$0();
      return t1;
    }
  }
},
UserLazyField: {
  "^": "Object;",
  useBar$0: function() {
    return $.UserLazyField__bar;
  },
  UserLazyField$0: function() {
    if ($.UserLazyField__bar == null)
      $.UserLazyField__bar = new F.Bar();
    return;
  },
  static: {
    UserLazyField$: function() {
      var t1 = new F.UserLazyField();
      t1.UserLazyField$0();
      return t1;
    }
  }
},
```

You'll notice that even though `_bar` is always only accessible to the class it lives in, and is only ever accessed as a getter in `useBar()`, Dart2JS isn't able to optimize the getter, and it's actually _more_ expensive when `static final` than when I don't use final and manually assign it lazily.

`DartLazyField`:

```js
  useBar$0: function() {
    // Method call, which in turn I assume does a null check, etc.
    return $.$get$DartLazyField__bar();
  }
```

`UserLazyField`:

```js
  useBar$0: function() {
    // Simple JavaScript field.
    return $.UserLazyField__bar;
  }
```

**Comment by rakudrama** [comment]
These are not exactly the same:

- If `new Bar()` has a side effect, e.g. printing, that occurs in UserLazyField's constructor but in the first call to DartLazyFields.useBar().
- If `new Bar()` throws, UserLazyField will retry, DartLazyField will stay `null`.
- The Dart lazy initializer will detect initialization cycles instead of overflowing the stack.

dart2js has some optimizations surrounding a lazy static load: repeated loads in the same function are replaced with direct loads.

It is hard to say which is 'more expensive' when they are so different.

The comment "I assume" is not correct. There is no check on a lazy field getter's second call. The getter is updated to directly return the static:

```js
function() {
            return this[fieldName];
          };
```

If the JavaScript engine inlines this function it becomes the same as the direct property access.

Do you have measurements of some kind to substantiate "static final fields more expensive than lazy statics"?

**Comment by matanlurey** [comment]
I checked closer, and you're correct. I didn't realize it monkey patched! Thanks!
