### ISSUE TITLE
Generic type not able to find correct concrete type

### ISSUE THREAD

**Issue by binoypatel** [dart-lang/sdk#31526]
Hi 

I am trying to implement pretty basic scenario with generics, here is what I am trying to do:

1).  Base.dart
`class Base {
}`
2). User.dart
```
class User extends Base {
   int Id;
   string Name;
   User.fromMap(Map map) {
      Id = map["Id"];
      Name = map["Name"];
   }
}
```
3). Customer.dart
```
class Customer extends Base {
   int Id;
   string Name;
   Customer.fromMap(Map map) {
      Id = map["Id"];
      Name = map["Name"];
   }
}
```
4). Mapper.dart
```
class Mapper {
   static T fromMap<T extends Base>(Map map) {
      switch(T.runtimeType) {
         case User:
            return new User.fromMap(map);
         case Customer:
            return new Customer.fromMap(map);
      }
      return null;
   }
}
```
Dart analyzer is showing me following errors:
[dart] The return type 'User' isn't a 'T', as defined by the method 'fromMap'.
[dart] The return type 'Customer' isn't a 'T', as defined by the method 'fromMap'.

When I change T to Base then it works but that is not what I want. Ideally, I don't even want to use Base but I believe then dart will not understand how to relate T to User or Customer class.

If this is not achievable then let me know the best approach to achieve this.

Thanks for your help,
Binoy

**Comment by lrhn** [comment]
There is a number of issues here. The most aggrevating one is that you should write just `T`, not `T.runtimeType`. The `runtimeType `of `T` is `Type`, not `User` or `Customer`.

Second, `Type` objects override the equals operator, so they should not be usable as switch-case values. You should use equals checks instead: `if (T == User) { ... } else if (T == Cusomer) { ... }`.

The return type problem comes up because the system cannot see that `T` is the same as the returned value. This function can return both `User` and `Customer`, and `T` can bo either, so one of them is wrong. The compiler isn't clever enough to realize that your switch avoids that.
So, write: `return new User.fromMap(map) as T;` to get around that.

**Comment by binoypatel** [comment]
ok cool this really helped me understand the Dart as I am C# developer up until :) 
It would be nice to have Dart understand the concrete return type
