### ISSUE TITLE
StdinException when reading byte from stdin

### ISSUE THREAD

**Issue by mkj-gram** [dart-lang/sdk#31530]
When reading from stdin on linux (ubuntu 14.04) a StdInExpection is thrown occasionally when sending data to a program with the message

StdinException: Error reading byte from stdin, OS Error: No such file or directory, errno = 2

It does not happen every time, so it can be a bit hard to reproduce.

To observe the error, modify pkg/status_file/bin/lint.dart to print something on line 67, fx: print("WHOOPS");

Then invoke the following:
for ((i=0;i<1337;i++)); do dart pkg/status_file/bin/lint.dart -t < tests/co19/co19-dart2js.status; done | grep WHOOPS

@mkustermann

**Comment by mkustermann** [comment]
Thanks for the repro!

I briefly looked at it and it seems to have todo with checking off `errno` after calling `getchar`. When I add printing on the `c == EOF && errno != 0` case, I get sometimes:
```
getchar() failed: : No such file or directory
Whoops
```

When clearing out `errno` before calling `getchar` the issue seems to go away:
```diff
diff --git a/runtime/bin/stdio_linux.cc b/runtime/bin/stdio_linux.cc
index a6eddbedf2..72a095f16a 100644
--- a/runtime/bin/stdio_linux.cc
+++ b/runtime/bin/stdio_linux.cc
@@ -18,8 +18,10 @@ namespace dart {
 namespace bin {
 
 bool Stdin::ReadByte(int* byte) {
+  errno = 0;
   int c = NO_RETRY_EXPECTED(getchar());
   if ((c == EOF) && (errno != 0)) {
+    perror("getchar() failed: ");
     return false;
   }
   *byte = (c == EOF) ? -1 : c;
```

The `getchar` manpage says:
```
 fgetc(), getc() and getchar() return the character read as an unsigned char cast to an int or EOF on end of file or error.
```

Which seems to indicate it's not possible to distinguish an error from a real end-of-file, since both result in `EOF` being returned. The manpage doesn't mention setting of `errno`, so it might not be safe to use it.

Assigning to @zanderso  as it got introduced in 9506cb9975719fe4475e5d45780cab4426fd5663.

Maybe the right thing to do is not using `getchar()` if stdin is a pipe and use `read()` as with other pipes/files which does in fact specify error behavior in `errno`.

**Comment by jensjoha** [comment]
I ran into something different actually --- a different exception. I landed the CL I could reproduce it on yesterday, so I'll see if I can consistently reproduce it again and create another bug report.

**Comment by jensjoha** [comment]
While I got both
```
StdinException: Error reading byte from stdin, OS Error: Connection refused, errno = 111
```
and
```
StdinException: Error reading byte from stdin, OS Error: Inappropriate ioctl for device, errno = 25
```

before I can no longer reproduce it, so probably the fix for this issue fixed the issues I was seeing as well. Thanks!
