### ISSUE TITLE
Proposal: use the principal type for inferring argument types of closures

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31546]
This arose as a [comment](https://github.com/dart-lang/sdk/issues/31436#issuecomment-349093433) in #31436.  I'm moving it to its own issue to avoid cluttering discussion in #31436.

Quoting from the comment:
> As a secondary followup, @eernstg raises the possibility of extending the idea of using the principal type (rather than the context type) for argument types as well as return types (as discussed in the previous comment).  That is, when inferring the type of a closure `(x) => E` in a downwards context `Null -> T`, us `Object` for the type of `x` instead of `Null`.  
> 
> Pros:
>   - The resulting inferred closure is strictly substitutable for the version inferred with `Null`
>   - This makes using `Null ->  T` as the type of "any unary function returning T" much more usable, since the inferred function will no longer fail if dynamically applied to a non-null value.
>   - No additional (and no fewer) method send errors and warnings will be emitted (`Null` and `Object` have the same method set.
> 
> Cons:
>   - With --no-implicit-casts, additional cast errors may show up
>   - Less static and runtime checking if you actually intend the type to be Null
>   - Implementation cost
> 
> This is something that can be done later as an essentially non-breaking change, which argues for pushing it off.
> 
> On the other hand, this change would likely on balance reduce migration cost, since currently using `Null -> T` as the type of "any unary function" interacts badly with inference.
> 
> ```
> Object apply(Object Function(Null) f, Object x) {return (f as dynamic)(x); }
> apply((x) => x; 3); // Throws a runtime error
> ```
> 
> I'm fairly disinclined to make additional changes to inference now unless the implementation and migration cost is very close to zero.  @stereotype441 , thoughts?

**Comment by stereotype441** [comment]
Would this apply just to arguments whose type is `Null` in the context or to all arguments whose type isn't explicitly specified in the closure?

If it applies to all arguments whose type isn't explicitly specified in the closure, I worry that this would lead to frustrating errors, e.g. the following code would have a compile-time error:
```dart
int Function(int) addOne = (x) => x + 1;
```
...because the inferred type of `x` would be `Object`, and `Object` doesn't declare support for the `+` operator.

I'm also fairly disinclined to make additional changes to inference now, however if we're just talking about `Null`, then I think the impact would be fairly low so I'd be open to making the change.

**Comment by eernstg** [comment]
The point is that we _can_ assign a proper supertype of the type-from-context for immutable entities like functions, but we _don't have to_ apply it everywhere (or at all).

So we can point out a single case like "when the type-from-context specifies `Null` as the type of a given parameter", and then we can make the choice to use another type as the annotation for that parameter (say, `Object`). In all other cases we just wouldn't use the opportunity to use a different parameter type than the one that we got from the context.

The resulting type of the function literal would then be a subtype of the type-from-context, so it would generate _fewer_ cast errors when the function is passed around than it would, had it been given the type-from-context.

In the body of such a function literal, the formal parameter would formerly have had type `Null`. No implicit casts would then be needed (they're all downcasts, and no such thing is needed for `Null`) in the body, and there may now be some additional downcasts when the same formal parameter now has type `Object`. So the body may certainly give rise to additional cast errors in this situation, with `--no-implicit-cast`. As you mention, lookups should not change because `Null` has just the members from `Object`.

But I doubt that it is pragmatically more useful to let the parameter have type `Null` than type `Object`.

The `addOne` example would not be affected, simply because the type-from-context does not specify `Null` as the type of any formal parameter.

**Comment by leafpetersen** [comment]
> ...because the inferred type of x would be Object, and Object doesn't declare support for the + operator.

No this would be a special case only for downwards contexts of the form "Null -> something", and only when applying such a context to a closure literal.

**Comment by leafpetersen** [comment]
> Hence, I think it wouldn't be disruptive except for possibly some really special corner cases, and it would make the "general" function types like void Function(Null) much more useful.

Yes, I agree.

**Comment by leafpetersen** [comment]
My one other concern is that this can feed into inference.  For example:

```dart
Future<Null> f;
var a = f.then((x) => [x]); 
a.then((l) => (l as List<int>));
```

Before this change, `a` would be inferred as `Future<List<Null>>`, and the cast on `l` would succeed.

After this change, `a` would be inferred as `Future<List<Object>>` .

This really still seems like a pretty unlikely thing to actually crop up though.

On balance I'm in favor.  @stereotype441 is going to look at making this change, expects it to be very small.  

@lrhn @eernstg  objections?

**Comment by eernstg** [comment]
If `[x]` were indeed a `List<Null>`, the code using `l` might easily fail even though `l as List<int>` succeeds, e.g., `(l as List<int>).add(42)`.

We might want to twist the example a bit and consider the known useful case, namely `const <Null>[]`. 

But if the type of the parameter doesn't influence the return type of the function literal we don't have the multi-step propagation of `Null`-or-`Object` which is the cause of concern here.

So if we can't twist this example to look more like a real problem I think we'll be ok. ;-)

**Comment by leafpetersen** [comment]
> Here's a no-go, for free: How about adding nil to dart:core, as a convenient shorthand for const <Null>[]? ;-D

Maybe allow `(` and `)` for list literals while we're at it?  :)
