### ISSUE TITLE
Kernel representation of forwarding stubs is very inconvenient

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31562]
Because they require special treatment, backends have to "pattern-match" against their bodies and compile them differently from other functions.

A representation more akin to redirecting factory constructors would make implementation easier.

**Comment by stereotype441** [comment]
This sounds like a nice way to address #31027 as well

**Comment by stereotype441** [comment]
Note to whoever is implementing this: there are two things one might mean by the "target" of a forwarding stub:
1. The interface target that would have been used had the forwarding stub not been present.  I call this the "interface target" of the forwarding stub.  Error messages based on static type analysis should use this target.  The analyzer should use this target for "go to definition".
2. The method that the forwarding stub forwards to at runtime.  I call this the "super target" of the forwarding stub, since it is always in the superclass chain.  The VM, dart2js, and DDC should use this target to determine which method the forwarding stub should invoke at runtime, and which types should be used for type checking.

Consider:
```dart
class A {
  void f(int x) { ... }
}
abstract class I {
  void f(covariant Object x);
}
class B extends A implements I {}
```

`B` will contain a forwarding stub for `f`.  Its interface target is `I::f`.  Its super target is `A::f`.

The target the VM cares about is the super target, and we already have a different bug about the interface target (#31519).  So let's say that this bug is about the super target.
