### ISSUE TITLE
'awaitable' page fault detection

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/sdk#31584]
With async/await, dart does have a form of coroutines. There needs to be an "awaitable" concept which can handle page faults, re-invoke a scheduler, and continue w/ next coroutine where the data dependency is loaded in memory. Could be simple as something which sits atop typed arrays, and allows one to await a memory page before looking at it's contents.

https://github.com/dart-lang/sdk/issues/31493

**Comment by floitschG** [comment]
async/await allows you to write programs as if you had coroutines, but fundamentally it is just using `Future`s under the scene. This has two implications:
1. the execution order is defined by how the futures behave
2. you don't always have coroutine-like separate executions. Since async/await functions can be interleaved with `.then` or `.catchError` calls, the implementations can't build up separate stacks for each of them.

Allowing users (in general) to deal with page faults is too low-level in general. We don't intend to expose this information to the users. (We might use it ourselves internally for other operations, like GC marking ...), though.
