### ISSUE TITLE
Access to type of DeclarationMirror

### ISSUE THREAD

**Issue by montyclt** [dart-lang/sdk#31597]
Hello,

I need to access the type of `DeclarationMirror`. In the [DeclarationMirror public API](https://api.dartlang.org/stable/1.24.2/dart-mirrors/DeclarationMirror-class.html) I can't see any method or property to access the type, but in Dartium, the API's "missing" property `type` is working and returning a `ClassMirror` with the type of the `DeclarationMirror`.
```
> declare is DeclarationMirror
< true
> declare.type
< ClassMirror on 'Logger'
> declare.type.reflectedType
< class Logger
```

Is safe using this way to get the type of `DeclarationMirror`?

If it is not safe, there is any other way safer to access it?

Thanks to all! 😘

**Comment by eernstg** [comment]
`DeclarationMirror` is implemented by `LibraryMirror`, `MethodMirror`, `TypeMirror`, and `VariableMirror`, and in particular for a `LibraryMirror` there is no notion of "its type" (and it would be non-trivial to give it a type and make it useful, because libraries are not first-class entities).

`MethodMirror` doesn't have a `type`, but it has a `returnType`, and it has `parameters`, each of which is a `ParameterMirror` which is a subtype of `VariableMirror`, and they have a `type`, which is a `TypeMirror`.

So you just need to determine which kind of declaration you expect to have, and then you can ask for "its type" in a well-defined (and hence safe) manner.

Note that it is potentially quite expensive in terms of the size and speed of the generated code to use mirrors in a Dart program for the web (that is, when generating JavaScript) whereas it is no problem on the Dart virtual machine. If you do need mirrors on the web you may wish to consider using the [package reflectable](https://pub.dartlang.org/packages/reflectable) where you can use code generation to support very nearly the same set of features as you get from the built-in mirror system.

**Comment by montyclt** [comment]
@eernstg Thanks you for the response. I've noticed my `declare` object is actually a `VariableMirror` (field of class).
