### ISSUE TITLE
Invocation of super.abstractMethod() is not resolved.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31593]
Here is an edge case test in Analyzer.

```dart
abstract class A {
  int m();
  noSuchMethod(_) => 42;
}

class B extends A {
  int m() => super.m();
}
```

It reports no static errors, because `A` has `noSuchMethod()`.

But FrontEnd also does not provide resolution for `super.m()`, which is bad for Analyzer - we want users to know that it resolves to `A.m()`, so that semantic highlighting and search work.

**Comment by lrhn** [comment]
I would make this a compile-time error. There is no `m` *implementation* in the superclass of `B`. Calling `super.m()` is a compile-time error because it refers statically to a member which isn't there.

That's not the same as a dynamic invocation (`new A().m()` is valid because the interface of `A` has a member `m`, but `A.staticM()` is not because the class `A` has not *static* member `staticM`). A super-invocation is a static invocation, and it's either safe or a compile-time error.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/#/c/sdk/+/28120 makes it hint even if there is `noSuchMethod()`. Making it an error with the new front-end sounds good to me.

**Comment by askeksa-google** [comment]
The example gives an error from CFE now.
