### ISSUE TITLE
error_on_bad_override does not work with covariant in Dart 2 mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31646]
```dart
abstract class Base {
  void f(covariant Base foo) { }
}

class Child extends Base {
  void f(Child foo) { }
}

main() {
  new Child();
}
```

```
$ pkg/vm/tool/dart2 --error_on_bad_override t/flu.dart
Unhandled exception:
't/flu.dart': error: line 2 pos 8: signature type '(Child) => void' of function 'f' is not a subtype of signature type '(Base) => void' of function 'f'

  void f(covariant Base foo) {
       ^
't/flu.dart': error: line 8 pos 8: class 'Child' overrides method 'f' of super class or interface 'Base' with incompatible parameters
  void f(Child foo) {
       ^

#0      _startIsolate.<anonymous closure> (dart:isolate:1257:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate:1147:12)
```

/cc @a-siva @kmillikin @crelier 

We need to decide:

a) if we want to fix it or 
b) if we want to make `--error-on-bad-override` a nop in Dart 2 mode (assuming that front-end reports all incorrect overrides itself)

[Flutter passes this flag to VM in debug mode so this is the first issue you hit when trying to run things. We can work-around it by not passing it.]

**Comment by crelier** [comment]
I do not think we should support it anymore. It was never specified and most probably does not find all problems anyway, but the flutter guys turned all possible flags on to find errors as early as possible.

**Comment by a-siva** [comment]
Agree with you regis, can we disable this option in 2.0 mode (assigning it to you).

**Comment by eernstg** [comment]
I think this was already implied in the [original description](https://github.com/dart-lang/sdk/issues/31646#issue-281876754) of the situation, but let me make it explicit: The declaration of `f` with signature `void f(Child foo)` in `Child` is a _correct_ override of `void f(covariant Base foo)` in `Base` (this is true in Dart 2 because of the `covariant` modifier which makes `Child.f.foo` a covariant parameter; it's also correct in Dart 1, but that's not important here). So if `--error-on-bad-override` is not eliminated (turned into a nop), it should be modified such that no exception is thrown here.
