### ISSUE TITLE
Add Dart 2.0 migration stubs to packages that implement Timer, Iterable, List, Set, Queue and Map

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#31664]
Dart 2.0 adds several instance members to a number of core library classes including Timer, Iterable, List, Set, Queue and Map.  To manage the transition, migration stubs will be added to a number of core packages that implement these interfaces to ensure that these packages remain unbroken during the transition.  These migration stubs can be replaced by full implementations at any time.

Stub template here: https://gist.github.com/lrhn/b99fe5f73a10b3b1a91579853056d08b .

TODO:
- [x] Remove hint suppression and whitelist in kernel and fasta for `hide` of `MapEntry` added in:
  - https://dart-review.googlesource.com/c/sdk/+/33662
  - https://dart-review.googlesource.com/c/sdk/+/33663

cc @anders-sandholm @lrhn @matanlurey @grouma @keertip

**Comment by leafpetersen** [comment]
cc @lrhn @anders-sandholm @keertip @grouma @matanlurey @srawlins @vsmenon @dgrove @kevmoo @mit-mit @Hixie

**Comment by leafpetersen** [comment]
This is essentially done, leaving open to track the TODO above.

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/44882

**Comment by leafpetersen** [comment]
Done.

**Comment by mofada** [comment]
Hello, today I read the official documentation and found that [Timer](https://api.flutter.dev/flutter/dart-async/Timer-class.html) has an implementation class [RestartableTimer](https://api.flutter.dev/flutter/package-async_async/RestartableTimer-class.html), and then try to use it, I imported dart:async, because Timer is inside the dart:async package. But can't find the RestartableTimer class. Why not add the RestartableTimer to the dart:async package?
Also, the get tick of RestartableTimer will throw an exception, I found it based on the comment. But Timer's get tick is normal.

**Comment by srawlins** [comment]
It is pretty confusing, but the RestartableTimer class is part of [`package:async`](https://pub.dev/packages/async), the async package, not the `dart:async` library. The package allows (theoretically) developers to publish changes quicker than changes in the Dart SDK, as part of the `dart:async` library.

In any case, yeah it looks like [RestartableTimer#tick](https://pub.dev/documentation/async/latest/async/RestartableTimer/tick.html) is not implemented yet. That package is maintained over at https://github.com/dart-lang/async. It looks like we do not have an issue yet for that method. You could open a bug over there and we can prioritize it.

**Comment by mofada** [comment]
Ok, I just submitted the [issues](https://github.com/dart-lang/async/issues/88) there, thank you.
