### ISSUE TITLE
Rethink for operator overloading

### ISSUE THREAD

**Issue by Aetet** [dart-lang/sdk#31683]
There's great concepts at kotlin for operator overloading:
https://kotlinlang.org/docs/reference/functions.html#infix-notation
https://kotlinlang.org/docs/reference/operator-overloading.html

Which can reduce boilerplate code and helps to write in more fp-style way.

Is it possible to add them to dart?

**Comment by lrhn** [comment]
Dart has overloadable operators already, so I guess you are asking for the infix function call syntax.

Infix function calls allow you to write `e1 foo e2` instead of `e1.foo(e2)`. That's (arguably) not a big improvement, and it comes with a cost of having a very low precedence. That means that in compound expressions, you'll likely need to parenthesize the infix function call, so it's `(e1 foo e2)` instead of `e1.foo(e2)`.
See also: https://discuss.kotlinlang.org/t/specify-operator-precedence-for-infix-functions/2685

I agree that some functions will read better that way, but I'm not sure the feature is worth the parser complication, at least not the way it's currently working in Kotlin. Without a way to control precedence, it's a functionality that doesn't really scale - it works fine for a single binary expression, but when using it in compound expressions, it loses out. If you do control precedence, then parsing becomes *much* harder since you need to know the declaration of a specific name before knowing how to parse it, and we usually prefer to do parsing first and resolution afterwards.

**Comment by leafpetersen** [comment]
@lrhn do you want to keep this open to track anything?  This isn't on the medium term roadmap, and I don't think it's anything that we won't think to consider if we have a use case that needs it.  Closing for now, feel free to re-open (or re-file in language) if you want to track it.
