### ISSUE TITLE
flutter_gallery_win__compile debug_full_compile_millis regression

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31684]
Debug compile time on Windows for Android has been progressively getting slower over the last couple of weeks:

![screen shot 2017-12-18 at 2 36 23 pm](https://user-images.githubusercontent.com/551196/34131529-d9863fa6-e400-11e7-9e3a-452370592c4a.png)

**Comment by aam** [comment]
Curiously, this regression is really Windows-specific as `flutter_gallery_android__compile debug_full_compile_millis` doesn't show this trend.

android:
![debug_full_compile_android](https://user-images.githubusercontent.com/381137/34222738-665a127e-e571-11e7-82c0-22926e935f5a.png)

windows:
![debug_full_compile_win](https://user-images.githubusercontent.com/381137/34222740-68fd6256-e571-11e7-85c7-f365bf392dec.png)

**Comment by Hixie** [comment]
complex_layout_ios__compile debug_full_compile_millis has actually also regressed recently.

**Comment by Hixie** [comment]
and `flutter_gallery_ios__compile debug_full_compile_millis`.

**Comment by aam** [comment]
I believe one significant source of regression is cf1de7d46c, which regressed performance of `gen_snapshot`(below) for flutter_gallery on Windows seems to have dropped by ~6% (6181ms vs 5847ms).

@mkustermann 
```
C:\src\flutter\engine\src\out\\android_profile\gen_snapshot --await_is_keyword --causal_async_stacks --vm_snapshot_data=C:\src\flutter\engine\src\out\host_debug_unopt\gen\flutter\lib\snapshot\vm_isolate_snapshot.bin --isolate_snapshot_data=C:\src\flutter\engine\src\out\host_debug_unopt\gen\flutter\lib\snapshot\isolate_snapshot.bin --packages=C:\src\flutter\flutter\examples\flutter_gallery\.packages --dependencies=build\snapshot_blob.bin.d --print_snapshot_sizes --snapshot_kind=script --script_snapshot=build\snapshot_blob.bin --enable-mirrors=false lib/main.dart
```

**Comment by mraleph** [comment]
Snapshot building times should be significantly improved when 226c715 gets rolled into Flutter. My measurements show something close to 30% (5847ms goes to 38xx ms) on Windows.

The real problem is architectural though: we are using ARM simulator to execute vm-service code which handles loading of the Dart code. This is a lot of unnecessary overhead. 

With Dart 2 model the loading of the Dart code is done by front-end server which is executed in a proper host Dart VM. Script snapshots will be removed. This would solve the problem.

We also have plans to refactor the compilation pipeline in a way that allows a single Dart VM binary to use several backends (e.g. both ARM and x86 ones), while currently a single Dart VM binary can only have a single compiler backend inside. This is a big refactoring and I think Dart 2 switch would (hopefully) happen before we finish it. However if Dart 2 switch would not happen then this refactoring would speed up `gen_snapshot` even more.

Finally if it remains a problem we could undo changes from 2 years ago and switch `gen_snapshot` back to using custom code loader written in C++. I don't think this is desirable though.

**Comment by aam** [comment]
Thanks @mraleph . Any ideas on why only Windows was affected by flowgraph-driven generation?

**Comment by mraleph** [comment]
I think they are both affected - my current theory would be that ARM simulator is just slower on Windows due to MSVC doing worse job than clang/gcc.
