### ISSUE TITLE
Clarify override inference behavior in Dart 2

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31797]
The following triggers a static error if the commented code is uncommented:

```dart
class A<E> {
  void foo(E x) {
    print('A');
  }
}

class B<E> {
  void foo(Object x) {
    print('B');
  }
}

abstract class C<E> {
  void foo(E e);
}

class D<E> extends A<E> with B<E> /*implements C<E>*/ {
  void foo(x) {
    print('D');
  }
}

void main() {
  var a = new D<int>();
  print(a.foo.runtimeType);
}
```

If the `implements` clause is added, I get:
```
Error: Can't infer the type of 'x': overridden members must all have the same type.
Specify the type explicitly.
  void foo(x) {
```

Two issues:
- Adding `C` as a supertype should not change anything.  No new constraint has been added (- the constraint from `A.foo` has just been duplicated).
- I believe the intended behavior is to infer the LUB (what happens when the `implements` is commented out).  In that case, the error is wrong.  Overridden members don't have to have the *same* type.

**Comment by vsmenon** [comment]
Note, this is coming up in actual code here:

https://github.com/dart-lang/html/blob/master/lib/dom.dart#L971

where the new CFE is triggering a similar error.

**Comment by vsmenon** [comment]
@leafpetersen, @lrhn  - what's the intended behavior?  As we sticking with `LUB` inference here or not?

**Comment by vsmenon** [comment]
Hmm, if the intent is *not* `LUB`, the current CFE behavior is probably right.  Re-filing on language.

**Comment by vsmenon** [comment]
Labelling as `P1` to nail down the behavior.  If we go with:

`exact`: We'll need to backport the change to analyzer and fix code to adhere to the stricter semantics (e.g., `package:html`).

`LUB`: We'll need to fix the CFE.

**Comment by leafpetersen** [comment]
I believe that we had specified this as being an error.  @eernstg I think if I remember correctly you wrote up a draft spec of this, does that agree with what you have?

I wonder though whether we shouldn't compute this by first computing an inherited interface (as if there was no concrete method), and then using that for override inference.  This would allow us to pick the minimum of the inherited interfaces.  Alternatively, we could do this on a per parameter/return type granularity, choosing the minimum of the inherited types.  This is a bit closer to inventing a type though.

I'm not keen on using LUB - it's got too many unpleasant corners.

@lrhn thoughts?

**Comment by eernstg** [comment]
> .. a draft spec ..

There is https://codereview.chromium.org/2225753002 which is a draft spec of top level inference, and that CL adds a specification of 'instance member signature inference'. However, that draft has not (yet) been developed to a point where method signature conflict issues are covered (the work on that draft was halted because we concentrated on writing feature specs, and because the whole area of inference needed further clarification).

I'd say that we should stick to the motto that we have been using in several similar situations: Don't invent complex entities (like method signatures), but support implicit detection and usage of a most-specific variant, and support explicit disambiguation for the remaining cases when possible. Of course, `abstract class C { get foo; }` and `abstract class D { foo(); }` can't be reconciled, but developers can resolve all the things which are ambiguities rather than hard conflicts --- so they should be OK.

I'd recommend that when we have a well-defined method signature in the class interface, we will use elements from there (for the return type, for type annotations on individual formal parameters, and for formal type parameters and their bounds); otherwise (when there is no most specific method signature for the given method) a compile-time error occurs. The class may or may not be fixable, but the next move is in any case the developer's. Luckily, the developer only needs to add a type annotation on the relevant formal parameter(s) or a return type in order to disambiguate a whole method signature, so there is no syntactic overhead in the disambiguation.

This means that instance member signature inference is near-trivial as soon as we have a robust and complete way to compute a class interface.

**Comment by stereotype441** [comment]
FYI, the current analyzer behavior is to require all overridden members to have the same type (for any parameters whose type is to be inferred), however the error reporting path is broken, so when the types don't match, no error is reported; instead, the analyzer silently infers a type of `dynamic` for the parameter that had a mismatch.

Once we reach a consensus on what behavior we want, I'll make sure the appropriate logic is implemented in both the analyzer and the front end.

**Comment by eernstg** [comment]
I just wrote a rough draft of a [specification of flattened interfaces](https://gist.github.com/eernstg/872bf60e8a2d942ccb514e80142ede25) in Dart. It's based on Lasse's preferred model (where interfaces do not have an inheritance structure, they just "have" all the methods whether declared in the bottom class or obtained from superinterfaces).

One purpose of writing this was to clarify the situation with covariant parameters, but I believe that the whole setup would fit nicely for saying the things that we want to say about method signature conflicts.

I'm not sure this document is sufficiently uncontroversial to justify a CL which puts it into the SDK, hence the placement as a standalone gist.

**Comment by vsmenon** [comment]
Fixed the bug title.  :-)

**Comment by eernstg** [comment]
Ah, so we had a bug title bug; that's a fancy concept, so maybe we should name it, and get a title bug title! ;-)

**Comment by lrhn** [comment]
I think can see where the error comes from, and I think it shouldn't be an error.
The declaration: `extends A<E> with B<E> implements C<E>` has superclass `A<E> with B<E>`, which should have a signature for `foo` of `void Function(covariant Object)`. The `Object` comes from `B`, the `covariant` from `A`.

(And yey - that's another case of introducing covariance from the side, so the *mixin application* of `B.foo` becomes covariant even if `B.foo` itself is not - there is no synthetic forwarder here to add the covariance, we really do need to modify the mixed-in method!)

Then class `D`` declares a `foo` with no argument type. That means it should copy its type from its superinterfaces, but the superinterfaces disagree, `void Function(covariant Object)` from `A<E> with B<E>` and `void Function(covariant E)` from `C<E>`. So, which one? 

So, the approach that gives us the current error is to say that we do not guess a type, you have to have only one possible type among the super-interface members before we inherit the parameter type from it. Here, you do not.

If we don't want to make that an error, we could loosen the restriction so the superinterfaces don't have to have the *same* signature, they just need to have one of them that is most specific, and then we use that one (and it's still an error if there is no most specific super-interface member signature, and you try to inherit typing from them).

**Comment by eernstg** [comment]
> the superinterfaces don't have to have the same signature, they just need to
> have one of them that is most specific, and then we use that one 

That is exactly the approach that I was advocating (maybe I didn't make it 100% explicit).

> They are wrongly assuming .. [then: how it works]

No matter how the error arises, the 'flattened interfaces' approach fits the description of how it works: `A<E>` would have a flattened interface which is used with the-mixin-of-`B<E>` for the computation of a flattened interface for `A<E> with B<E>`; that flattened interface plus the one for `C<E>` is used with `D<E>` to compute the flattened interface for `D<E>`. At each step there may be conflicts that give rise to compile-time errors, or "pre-solved conflicts" (where we have multiple contributions of some sort, but one of them is most specific in some sense) where we accept the given "solution".

In any case, I don't remember ever having discussed a design for Dart containing a rule of the form ".. must have the same type", so that's an issue in any case.

**Comment by lrhn** [comment]
Yes, doing the "pick most precise signature from super-interface, then inherit omitted type annotations from that" will solve the problem and if you omit all type annotations, your method will get the same signature as your interface would have inherited otherwise. That's a good behavior, and easily explained.

Basically: You can only omit type annotations on a member declaration if you could omit the entire declaration and still inherit a proper interface member signature.

Let's do that, instead of requiring all super-interface member signatures to be the same (which is, admittedly, the simplest way to avoid ambiguity).

**Comment by sigmundch** [comment]
Just wanted to share two more examples that trigger this problem, in a way that I believe is very surprising to users.

Both examples should be handled by the proposal of "picking the most precise signature from super-interface first, then infer", but if that is not feasible, I hope we can do something special about `Object` on the first example below.

example1:
```dart
class A {
  operator==(Object x) => false;
}

class B extends A implements Object {
  operator==(x) => false;
}
```
(note that using any interface instead of `implements Object` would also show the error)

example2:
```dart
abstract class I1 {
  m(int x);
}

class A1 extends I1 {
  m(num x) => null;
}

class B1 extends A1 implements I1 {
  m(x) => null;
}
```

Seeing that types can't be inferred here is especially surprising because the interface (Object/I1) is also an interface of the base class (A/A1).

**Comment by eernstg** [comment]
This has been p1-high, area-language for a while.

I'd [still](https://github.com/dart-lang/sdk/issues/31797#issuecomment-356954322) recommend that we use the notion of the ['combined interface'](https://github.com/dart-lang/language/blob/0e6b07cba963a3cea76b148ccc90ddc0decb86e5/specification/dartLangSpec.tex#L4018) of the superinterfaces to resolve which method signature to use in order to perform override inference. This approach will also detect ambiguities, because they will cause the computation of the combined interface to fail (which will prevent inference, but might be resolved by a manually written signature).

It seems natural to use that method signature for override inference which would have been used as the signature in the interface of the class, had there not been any overriding declaration.

If we wish to go that way then we'd need to adjust the specification of inference accordingly ([here](https://github.com/dart-lang/language/blob/3b46550bd069bb62c2f30300039711f886741edb/resources/type-system/inference.md#method-override-inference)). @leafpetersen, would you support this? @munificent, @lrhn, wdyt?

If we need a long discussion before we can decide on this then we might want to move this issue to the language repo. Otherwise, if we agree on something rather quickly then we could re-purpose this issue to be about the implementation of that behavior.

**Comment by leafpetersen** [comment]
@eernstg should this be covered by the combined member signature changes we made in the null safety release?  I still see some inconsistencies on the original example when running with null safety enabled, specifically:
  - The analyzer reports a hint when the commented code is added in.
  - The CFE reports an error when the commented code is added in.

My quick read is that neither should be an error with the combined member signature changes, is that correct?

**Comment by eernstg** [comment]
@leafpetersen yes, we specified that the combined member signature is used for override inference and updated combined member signatures to work better with null-safety. This means that we will gather the most specific member signatures for each member from all superinterfaces (this set consists of member signatures that are mutual subtypes), and apply `NNBD_TOP_MERGE` to them, which will yield the single member signature that we need. Adding `implements C<E>` in the example should make no difference because `void foo(E)` is not most specific.

So I'd say that no diagnostics (errors, warnings, hints) should be emitted.

**Comment by vsmenon** [comment]
Does this need to be a P1?  I see I marked as such a while ago, but doesn't seem like it's been much of an issue.

**Comment by leafpetersen** [comment]
It doesn't need to be P1, but I do want to have it for the null safety beta since the fact that it's not fixed indicates a big in the null safety member signature computation.

**Comment by franklinyow** [comment]
Removing P1, it will still be part of Null Safety Beta Epic

**Comment by vsmenon** [comment]
Is this still an issue?  We didn't get this in for the beta.  What priority do we want on this?

**Comment by eernstg** [comment]
Note that, with **legacy** code, the analyzer implements the specified approach (using the combined member signature from superinterfaces), but the common front end reports an error and requires that superinterfaces have the same member signature.

With **null safety**, both the analyzer and the common front end use the combined member signature.

The feature specification [inference.md](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md) where the change from error-if-different to use-combined-signature was made specifies both the legacy language and the language with null safety, and the section [Override inference](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#method-override-inference) does not indicate which version(s) of the language it is applicable to, so it is reasonable to say that it applies to both legacy code and code with null safety.

With that, I believe we can say that it is very nearly implemented already, but we might want to ask the front end team to switch to the combined member signature approach also for legacy code. This would be a non-breaking change, and it would make the tools consistent.

**Comment by franklinyow** [comment]
@johnniwinther
