### ISSUE TITLE
Non-abstract `noSuchMethod` required to suppress "interface not implemented" errors

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31791]
Consider the following code:
```dart
abstract class I {
  void foo();
}
class C implements I {
  dynamic noSuchMethod(Invocation invocation);
}
```
The spec says:
> Let `C` be a concrete class that does not have a `noSuchMethod()` method distinct from the one declared in class `Object`.
> It is a static warning if the implicit interface of `C` includes an instance member `m` of type `F` and `C` does not declare or inherit a corresponding non-abstract instance member `m` of type `F'` such that `F' <: F`.

In https://dart-review.googlesource.com/c/sdk/+/32620/2/pkg/front_end/testcases/inference/future_then_conditional_2.dart#b13, @lrhn argues that this should be interpreted to mean "does not have *an implementation of* `noSuchMethod()` distinct from the one declared in class `Object`".  In the code above, class `C` contains a *declaration* of `noSuchMethod()`, but its *implementation* of `noSuchMethod()` is the one inherited from `Object`, so this would mean that the code above should have a warning (error in Dart 2.0) indicating that `C` is missing a concrete implementation of `foo`.

Current behavior of the analyzer merely requires class `C` to have a *declaration* of `noSuchMethod()`, so the above code is accepted without complaint.

If we want to make this behavioral change, the spec language should be clarified, and we'll have to update the analyzer, as well as any code in the wild that uses the pattern above (it will have to be changed so that it has a concrete override of `noSuchMethod` that calls `super`).

**Comment by lrhn** [comment]
In my mental model, interfaces are just sets of signatures, they don't remember where the member was declared (if it's declared anywhere, considering implicit getters and setters and covariant forwarders).

A class contains member implementations, and each implementation remembers where it was declared (because it needs to know that to `handle super.foo()` invocations). A class has an interface.

A *class declaration* introduces both a class and an interface (known as the implicit interface of the class).

That means that when I say that a *class* has a `noSuchMethod` different from the one in `Object`, I'm definitely (intending to be) talking about implementation. 
Adding an abstract method does not affect the *class* at all, and since it has the same signature as the one in the superclass, it doesn't change the interface either. An abstract method declaration with the same signature as the superclass is a no-op at the class/interface level.
That's not clear from the text, and that mental model isn't reflected in the specification (yet).

(If we include annotations in the mix, then I guess the interface member signature will include that annotation, so it is distinguishable from the superclass interface signature. It's unclear to me what happens to annotations when the signature is inherited in an abstract subclass).

**Comment by eernstg** [comment]
We touched upon this also in the informal spec of noSuchMethod forwarders:
```
We say that a class _C_ _has a non-trivial_ `noSuchMethod` if _C_ declares
or inherits a non-abstract method named `noSuchMethod` which is distinct
from the declaration in the built-in class `Object`.
```
The inclusion of `non-abstract` is intended to ensure that it is a method implementation, not just an abstract declaration. So we have already discussed this topic and agreed that an implementation counts, and an abstract declaration does not. I agree with Lasse that dartLangSpec.tex does not specify this explicitly. [Here](https://dart-review.googlesource.com/c/sdk/+/32763)'s a CL that clarifies the situation in dartLangSpec.tex, so when that's landed/rejected the situation should be resolved.

**Comment by leafpetersen** [comment]
I don't feel very strongly about this either way.  It feels like it's somewhat convenient not to have to write the explicit forwarder to super, but on the other hand, the resulting code is somewhat obscure.  Sure, LGTM.

**Comment by lrhn** [comment]
I don't think it'll happen much outside of unit-tests. It's a class that claims to implement an interface, but where the unimplemented methods all throw `noSuchMethod` errors. That's not a good desing for anything except quick hacks, and I'd probably still do:
```dart
noSuchMethod(i) { throw new UnimplementedError(); }
```
instead.

**Comment by eernstg** [comment]
[Said CL](https://dart-review.googlesource.com/c/sdk/+/32763) has been landed.

**Comment by stereotype441** [comment]
I'm starting work on a front end fix for this.

**Comment by stereotype441** [comment]
Whoops, ignore my previous comment (I updated the wrong bug).  This bug is still up for grabs.

**Comment by srawlins** [comment]
Analyzer now reports:

> Missing concrete implementation of 'I.foo'.
