### ISSUE TITLE
Implement tooling for migrating code away from deprecated Dart 1.0 constant names

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#31822]
As step 2 of the wave 1 core library changes, we need to remove the old deprecated constant names.  To make this feasible, we should have a migration script that can be run as part of the flutter upgrade process to port code over to the new constant names.  

Tracking issue for removing the deprecated names is https://github.com/dart-lang/sdk/issues/31813.

Tracking issue for the overall core lib migration is https://github.com/dart-lang/sdk/issues/31812.

**Comment by leafpetersen** [comment]
cc @lrhn @anders-sandholm @keertip @grouma @matanlurey @srawlins @vsmenon @dgrove @kevmoo @mit-mit @Hixie

**Comment by leafpetersen** [comment]
@bwilkerson @devoncarew @matanlurey 

Matan has some internal tooling that could potentially be open sourced to do this.  

This also feels like something that the analyzer basically already supports via re-factoring.  Is there a way to access this programmatically via the command line API?  That is, provide some sort of renaming schema and run the command line analyzer to generate the appropriate edits?

**Comment by matanlurey** [comment]
That solution might be enough for external projects, but won't work in google3.

**Comment by bwilkerson** [comment]
> Is there a way to access this programmatically via the command line API?

Not currently, no. It is certainly possible to implement such a tool, and I don't think it would take very long. We just need to find resources.

**Comment by devoncarew** [comment]
I think for this, we should enhance the `@deprecated` annotation to more easily support automated refactorings. There are some deprecations that we could easily tool, like a rename, if the deprecation annotation supported enough into to reference the new symbol.

**Comment by bwilkerson** [comment]
Here's a straw-man proposal, just to get the discussion going.

**Extend the `Deprecated` annotation with additional information to support automated migration tooling.**

The constructor for the class `Deprecated` should be extended to take addition named parameters whose values can be used by tools to automate the migration of use sites from the deprecated API to a newer API when one exists.

One of the simplest use cases for this support is to rename a member. For this I propose that we add the named parameter `{String renameTo}` whose value, when provided, is the name that ought to be used wherever the deprecated member is referenced.

I chose the name `renameTo` because I think it makes sense for these to be written as if they were instructions to the user. Consider one use:
```
@Deprecated(renameTo: 'infinity')
static const double INFINITY = infinity;
```
This single parameter is not sufficient for all deprecation use cases. For example, if one function is being replaced by another, it's quite possible that the new function will have a different signature and that more work will be required to update use sites. Similarly, a deprecated class might be replaced by a class with a different set of type parameters. Such use cases will require additional (or different) data; hence the suggestion to make these named parameters. I propose we address those cases as we find need for them.

We should also recognize that some deprecations will not be amenable to automated tooling and/or will be infrequent enough to not justify the time required to support them.

(I'll also note, parenthetically, that the existing parameter to the constructor is being misused in order to carry this information, when it documented as being intended to be used to indicate when the declaration will be removed.)

**Comment by kevmoo** [comment]
@bwilkerson – in the case of the SDK consts for v2, though – we could just hard-wire some logic to help the rename – without requiring updates to annotations.

...right?

**Comment by bwilkerson** [comment]
Sure. We can hard-wire anything. It just won't help for things we don't know about :-)

**Comment by kevmoo** [comment]
Understood. We're in a situation now where the P0 is all things we know
about. :-)

**Comment by kevmoo** [comment]
Published here – https://pub.dartlang.org/packages/dart2_fix

@dgrove @devoncarew – can we close this as fixed?

**Comment by dgrove** [comment]
Closing
