### ISSUE TITLE
armv6 cross build fails to generate snapshot

### ISSUE THREAD

**Issue by stschake** [dart-lang/sdk#31857]
Following the instructions in the wiki for Raspberry Pi 1, the build fails with the following:

`
../../runtime/vm/object.h: 5555: error: Handle check failed: saw ICData target:'*' num-args: 2 num-checks: 0 type-args-len: 0 expected Instance
`

Full stacktrace: [stacktrace.txt](https://github.com/dart-lang/sdk/files/1622664/stacktrace.txt)

**Comment by stschake** [comment]
I'm currently bisecting between 2.0.0-dev.1.0 (good) and 2.0.0-dev.12.0 (bad). Is it enough to do a "gclient sync" after checking out a different revision of the sdk git?

**Comment by whesse** [comment]
Yes it is.  That should do the gclient runhooks as well.  I'm not sure that version 2.0 will have support for ARMv6, so you might do just as well to use stable version 1.24.3, which is known to be working.  Most of the changes since then have been to add 2.0 features behind flags, which won't make much difference to your programs.

If you do pin down the commit that breaks ARMv6 compilation, though, please let us know, and it may be an easy fix that will keep ARMv6 running.

**Comment by whesse** [comment]
@zanderso @mit-mit

**Comment by stschake** [comment]
The culprit according to bisect is fda4ab3dbf5e ("[vm] Move the info_array for ObjectPool inline.") @rmacnak-google 

Full log: 
[bisect_log.txt](https://github.com/dart-lang/sdk/files/1623068/bisect_log.txt)

**Comment by rmacnak-google** [comment]
I suspect it's an issue with decoding a shorter object pool reference.

**Comment by stschake** [comment]
Thanks, e6ebdcc fixed the problem. Flutter working nicely again on the Zero :)
