### ISSUE TITLE
Missing error for type variable conflicting with a member name

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31851]
```dart
class A<T> {
  set T(x) {}
}
```

```
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (master)$ pkg/front_end/tool/fasta compile --strong /Users/scheglov/dart/test/bin/test.dart
Note: strong mode support is preliminary and may not work.
```

The specification requires the error, see `10 Classes`:

![image](https://user-images.githubusercontent.com/384794/34794944-3d0db502-f605-11e7-9e7d-edf64c50d86c.png)

**Comment by jensjoha** [comment]
This no longer seem to be a problem. The example now gives:
```
t.dart:2:7: Error: Conflicts with type variable 'T'.
  set T(x) {}
      ^
t.dart:1:9: Context: This is the type variable.
class A<T> {
        ^
```

This is also tested by language_2/type_variable_conflict_test which passes. For some reason though, I cannot find that it should have ever failed :/

**Comment by jensjoha** [comment]
Update: Fixed by 5780deb18ae0785a96a50039f04a7099551dfc9b

And also the issue closed by that commit (#33827) was really a duplicate of this one.

**Comment by jensjoha** [comment]
Update #2: Actually, the test I mentined earler doesn't test the set case. I'll add that to the test.

**Comment by eernstg** [comment]
The setter case is new, because its name is `T=` rather than `T`. The current text is a bit stronger (still section 10 Classes in dartLangSpec.tex) and uses `basename` (which strips off the `=` from setter names):
```
If a generic class named $G$ declares a type variable named $X$,
it is a compile-time error if $X$ is equal to $G$,
if $G$ has a member whose basename is $X$,
and if $G$ has a constructor named \code{$G$.$X$}.
```
Also, it fixes a glitch: Having the same name as a constructor was impossible (because a constructor name is either the name of the class, which is already a conflict, or of the form `C.id`, and it's `id` that can't be the name of a type variable).

But it looks like the actual checks follow the new rules, so we should be OK! ;-)
