### ISSUE TITLE
Expose JS function outside of SDK

### ISSUE THREAD

**Issue by ranquild** [dart-lang/sdk#31891]
What do you think about exposing JS function outside of SDK code? This is very useful optimization, can be used by framework-level code. 

`JS('var', '#[#]', this, index);`

Kotlin does this already https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/js.html

**Comment by kevmoo** [comment]
thoughts @rakudrama @sigmundch ?

**Comment by lrhn** [comment]
I've definitely wanted that when writing platform-specific code. The affordances of `dart:js` are not impressive, and I didn't want to depend on `package:js` for something which was really mainly calling `Math.imul`.

Typing is an issue. It's a variadic function, which we can't do, so either it needs to be special-cased throughout the toolchain, or it has to just be typed as `Function`. The latter would prevent tools from helping you with the type of the first two arguments.

The "type string" (first parameter) might not be very user-friendly. It's designed for internal use, and looks quite powerful. Would we want a slightly simpler syntax if we release it for general use? Or maybe make the function generic so you write `JS<int>("Math.imul(#, #)", v1, v2)` instead of using a string.
There are things you can't write then, but it's quite a lot more readable to general Dart users.

**Comment by joshualitt** [comment]
Closing due to the preference for using js-interop over exposing internal SDK constructs.
