### ISSUE TITLE
Unexpected Stdout behavior for Ascii encoding with allowInvalid property set to true.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#31894]
The following test example:
```dart
import "dart:convert";
import "dart:io";
List<int> aList = [3000];
main(List<String> args) async {
   if(args.length == 0) stdout.encoding = new AsciiCodec(allowInvalid: false);
   print("Start here:");
   stdout.add(aList);
   String executable = Platform.resolvedExecutable;
   String eScript = Platform.script.toString(); 
  print("Start in a new process:");
   if(args.length == 0) await Process.run(executable, [eScript, "--checked"],
       stdoutEncoding: new AsciiCodec(allowInvalid: false));
}
```
sets stdout encoding to Ascii with invalid symbols allowed, then it adds non-ascii integer to stdout. Then it does the same in the separate process started from current Dart.

As a result, in the first case stdout contains `U+FFFD` Unicode special (non-ascii) symbol, and in the second case `FormatException` is thrown.  See stack trace in the end of this bug for more details.

No exceptoions in any case for latin1 encoding.

On the first glance, behavior should be the same in both cases.
So what is wrong and which behavior is expected?

Please also note:

Stdout.add Dart API Spec reads:
`Adds byte data to the target consumer, ignoring encoding. The encoding does not apply to this method, and the data list is passed directly to the target consumer as a stream event.`
AsciiCodec Dart Spec API reads:
`If allowInvalid is true, the decode method and the converter returned by decoder will default to allowing invalid values. If allowing invalid values, the values will be decoded into the Unicode Replacement character (U+FFFD). If not, an exception will be thrown. Calls to the decode method can choose to override this default. Encoders will not accept invalid (non Latin-1) characters.`

(Is in misprint that encoder gets Latin1 characters here?)

Sample output is:
```
Start here:
�Start in a new process:
Unhandled exception:
FormatException: Source contains non-ASCII bytes.
#0      _SimpleAsciiDecoderSink.add (dart:convert/ascii.dart:293)
#1      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#2      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#6      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#7      _StreamController._add (dart:async/stream_controller.dart:667)
#8      _StreamController.add (dart:async/stream_controller.dart:613)
#9      _Socket._onData (dart:io-patch/socket_patch.dart:1617)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#13     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#14     _StreamController._add (dart:async/stream_controller.dart:667)
#15     _StreamController.add (dart:async/stream_controller.dart:613)
#16     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1203)
#17     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

Process finished with exit code 255
```

**Comment by iarkh** [comment]
For Latin-1 encoding I see that there are no exceptions anyway, but stdout contains different symbols finally.

Is it a separate bug or the same problem?

Sample code is:
```dart
import "dart:convert";
import "dart:io";
main(List<String> args) async {
   if(args.length == 0) stdout.encoding = new Latin1Codec(allowInvalid: false);
   stdout.add([700]);
   stdout.writeln();
   String executable = Platform.resolvedExecutable;
   String eScript = Platform.script.toString(); 
   if(args.length == 0) await Process.run(executable, [eScript, "--checked"],
       stdoutEncoding: new Latin1Codec(allowInvalid: false)).
   then((ProcessResult results) {
     print(results.stdout);
     String s = results.stdout;
     print(s.codeUnits);
     print("�".codeUnits);
   });
}
```
Sample output is:
```
�
¼

[188, 10]
[65533]
```
BTW - Dart API Spec for Lati1Codec reads:
`If allowInvalid is true, the decode method and the converter returned by decoder will default to allowing invalid values. Invalid values are decoded into the Unicode Replacement character (U+FFFD). Calls to the decode method can override this default.
`

**Comment by lrhn** [comment]
You use `stdout.add` which ignores encoding, so you don't get any errors on that when doing it in the same process. It just truncates to 8 bits for non-ASCII characters, which is why you get `[188, 10]`, aka `[700 % 256, "\n".codeUnitAt(0)]`.

For the new process, you specify a stdout encoding *in the original process*. That means that the spawning process captures the stdout *bytes* of the spawned process, and runs them through the ASCII encoding.

The spawned process also emits `[188, 10]`, the 188 is then captured by the original process and put through the ASCII encoder, which doesn't allow invalid values, so it throws on the 188.

If you use Latin-1 or UTF-8 encodings, 188 is not invalid, so it will print something.

**Comment by iarkh** [comment]
Hi Lasse, 

Сould you please clarify - what is the difference? 

Both original and spawned processes deals with stdout consumers of the same type, and stdout encoding is the same for both of them. 

Add methos is called inside the process, i.e. output conteте is not passed from one process to another...

Is described behavior bug or not?

**Comment by lrhn** [comment]
The output *is* actually passed from the child process to the parent process.
The output is the bytes 188 (from `stdout,add([700])`, which ignores the `stdout.encoding` that you set because `stdout.add` does that, so it just outputs 700 & 255) and 10 (from `stdout.writeln()`, which is valid ASCII).

When the output of the child process is passed back into the parent process, it is *decoded* using the `stdoutEncoding: new AsciiCodec(allowInvalid: false)` that you passed to `Process.run`. Since the byte 188 is not valid ASCII, that decoding fails and throws.

If you look at the stack trace, you can see that the data is being decoded (it's throwing in `_SimpleAsciiDecoderSink.add`) and that the data comes from a socket. This shows that it really is the stdout of the child process being decode by the parent process.
