### ISSUE TITLE
DDC invokes super with dynamic call

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31973]
DDC fails on the below:

```dart
class A {
  Function foo = (x) => print(x);
}

class B extends A {
  void set foo(Function f) {
    super.foo(f);
  }
}

void main() {
  var b = new B();
  b.foo = (x) => x;
}
```

with

```
    dart.dsend(super, 'foo', f);
               ^^^^^

SyntaxError: 'super' keyword unexpected here
```

It should (like the VM) print the closure in the setter.

**Comment by jmesserly** [comment]
This bug is interesting! Initially DDC had the assumption that method invocation syntax node (`o.m(a)`) would be dispatched by `dcall` when `o.m` was resolved statically, but the call itself was dynamic. That did not work in certain cases (I don't recall the details--perhaps due to fuzzy arrows & methods?). So we switched it to use `dsend`. But that had the consequence of breaking super calls.

Anyways the fix is to bring back the `dcall` for this case (when `super` is involved).

I'll double check but I strongly suspect DDC+Kernel is immune to this bug.
