### ISSUE TITLE
Analyzer incorrect override error with mixins and generic methods

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#31977]
The code snippet below gives the following error when analyzed:

```
  error • Inconsistent declarations of 'cast' are inherited from <K2>() → M<K2>, () → dynamic at /Users/leafp/tmp/mixin_test.dart:13:7 • inconsistent_method_inheritance
```

This is clearly an incorrect error message (none of the variants of `cast` have the type mentioned above), and I don't believe that there is any reason to give an error here at all.

@lrhn anything I'm missing about the mixin override semantics?

cc @keertip @srawlins 

 Tested with:
```
dartanalyzer version 2.0.0-edge.bc22c3e0508ce1f0969949c78220fe97a03cc6ca
```

Reproduction example:
```dart
class M<T> {
  M<K> cast<K>() => null;
}

class _FM {
  M<K2> cast<K2>() => null;
}  

abstract class GV extends Object with _FM implements M<dynamic> {}

class _GV extends Object with _FM implements GV {}
```

**Comment by lrhn** [comment]
The `Object with _FM` class is valid (it can't not be with `Object` as super-class and `_FM` a valid class to derive a mixin from).

The signatures of the two `cast` methods are (alpha-)equivalent, and the `_FM` implementation is a valid implementation of the interface signatures of both `_FM.cast` and `M<whatever>.cast`,
so `GV` is a valid class (even if it hadn't been abstract). It inherits a `cast` implementation from its superclass (`Object with _FM`) and the signature of `GV.cast` is inherited from either the superclass interface or the `M<dynamic>` interface. It doesn't matter which one it is, they are equivalent. 

The `_GV` class inherits the same implementation from `Object with _FM`, and it has to satisfy the `GV.cast` signature, which it does.

(It is possible to have an `abstract class X extends Y implements Z {}; class _X extends Y implements X {}` set-up where `X` is valid and `_X` is invalid, but that requires the abstract class to not implement its interface. That is not the case here.)

So, I agree that the program is correct. I'm *guessing* that the merging of `M<K>` and `M<K2>` fails, which in Dart 1 would give `dynamic`. It won't in Dart 2, so it doesn't explain the problem.

Just to be precise: The `_FM.cast` method implementation has a signature on the form `M<#1> Function<#1>()` - the name of the type parameter doesn't matter, so I've replaced it with its index. 
We don't have a way to write that directly, so we have to recognize alpha)equivalence of method signatures so that it's equivalent to any method on the form `M<X> Function<X>()`, no matter identifier is used for `X`. (In the new `Function` syntax we omit the names of positional parameters, which means that we don't have to say that the names don't matter, but for type parameters, we need the names since they can, and usually do, reoccur in the signature).

So, `M<K> Function<K>()` is a equivalent to `M<K2> Function<K2>()`. A method on that form is a valid implementation of either interface. When inheriting a method signature from a super-interface (which is what `GV` does), it doesn't matter which one is inherited.

**Comment by eernstg** [comment]
DBC - by a complete accident, the current version of dartLangSpec.tex contains the following:
```
A common way to say this is that we do not distinguish function types
which are alpha-equivalent.
```
I won't mention whose fault it is that this verbiage was accepted into the language specification. ;-)

**Comment by scheglov** [comment]
This code does not cause Analyzer to report any error anymore.
I think this was fixed during switching to `InheritanceManager2`.
