### ISSUE TITLE
Add option to set User Agent for Websocket

### ISSUE THREAD

**Issue by charafau** [dart-lang/sdk#32008]
Hi! We use websockets for chat communication and we found out that there's no way to set User Agent when using `dart:io` websocket class.

Here is quick demo to reproduce it:

https://github.com/charafau/websocket_test/tree/master/bin

request which comes to server looks like this:

```
request: user-agent: Dart/2.0 (dart:io), my app
connection: Upgrade
cache-control: no-cache
accept-encoding: gzip
content-length: 0
sec-websocket-version: 13
host: localhost:8080
auth: charafau
sec-websocket-extensions: permessage-deflate; client_max_window_bits
sec-websocket-key: EUmYYgrmVHhGk5JiYSxQTw==
upgrade: websocket
```
I tried to override user-agent with headers but it's just added, not replaced. 

My suggestion is to change current `connect` method from 

```dart
static Future<WebSocket> connect(String url,
          {Iterable<String> protocols,
          Map<String, dynamic> headers,
          CompressionOptions compression: CompressionOptions.DEFAULT})
```

to 

```dart
static Future<WebSocket> connect(String url,
          {Iterable<String> protocols,
          Map<String, dynamic> headers,
          CompressionOptions compression: CompressionOptions.DEFAULT,
          String userAgent})
```

so ABI won't break and developers will be able to set user agent. 

if that's ok I can make PR for it.

**Comment by zanderso** [comment]
For better or worse, internally, WebSocket uses a single global HttpClient to set up all connections. The HttpClient fills in the user-agent using its userAgent field if it is non-null. Modifying the HttpClient's userAgent field in the connect call could yield confused/surprising results if concurrent connection attempts pass different userAgent parameters.

Instead, I'd recommend adding a static getter/setter userAgent to WebSocket so that it is obvious that the userAgent is being modified globally for all WebSocket connections. Happy to take a look at a PR that does that.

**Comment by charafau** [comment]
Thank you @zanderso I applied my changes, I just need to write some tests and figure out how to format file and make PR to this. Give me few days and I should make it happen.

**Comment by zanderso** [comment]
This is done. Thanks @charafau !
