### ISSUE TITLE
Make `new List.from([], growable:false)` return a constant, immutable empty list

### ISSUE THREAD

**Issue by parren-google** [dart-lang/sdk#32018]
This would reduce the number of empty list objects created when mapping lists to other lists.

To be specific, return this thing if `elements.isEmpty` in https://api.dartlang.org/stable/1.24.3/dart-core/List/List.from.html.

**Comment by lrhn** [comment]
The list being created is not just a `List`, it's a `List<Something>`, so you can't reuse the same constant empty list for every call.
It matters what the type argument is since it affects the behavior of `toList`, `toSet` and `+` (in Dart 2), so we can't just return a `const <Null>[]` (which would be assignable to any list type), because code like:
```drat
List<int> backup = new List.from(someIntegerList, growable: false);
List<int> buffer = backup.toList()..add(0);
```
would be invalid.

So, since the returned value depends on the class type parameter, we can't use a constant value. We (probably) don't want to cache an empty list per type argument.

**Comment by parren-google** [comment]
I see. I've explored a bit in AdWords just with empty BuiltLists, and for some places I got about 8000 empty out of 9000 created BuiltLists when I clicked around a bit. I'm sure many of these were short-lived or replaced during Angular update cycles though.

Overall, I suspect empty non-growable lists are rare enough to not warrant a cache. Might be different for BuiltList.
