### ISSUE TITLE
BigInt needs to implement num and operate on num

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#32073]
I was looking at converting the test `tests/kernel/unsorted/loop_test.dart` to the new 64-bit limit on integer literal.

```
fact(n) {
  var f = 1;
  while (n > 0) {
    f *= n;
    --n;
  }
  return f;
}

...

  Expect
      .isTrue(fact(42) == 1405006117752879898543142606244511569936384000000000);
```

I'd like to update this test to the 64-bit overflow semantics, and to preserve the original BigInt test, that is:

```
  Expect.isTrue(fact(new BigInt.from(42)) ==
      BigInt.parse("1405006117752879898543142606244511569936384000000000"));
  Expect.isTrue(fact(3.14159) == 1.0874982674320444);
```

Unfortunately, this doesn't work because `BigInt.>` doesn't accept a `num` (and throws when compared to 0).

This leads me to conclude that updating existing code to work with `BigInt` is going to be really hard unless `BigInt` is modified to implement num.

**Comment by peter-ahe-google** [comment]
I'm marking this as P1 as I believe this issue needs to be resolved before shipping Dart 2.0. Otherwise, please just close it.

**Comment by alexmarkov** [comment]
@floitschG @lrhn

**Comment by alan-knight** [comment]
It is quite inconvenient. I decided not to try and support BigInt in Intl at the moment. It works fine with num, Int64, and MicroMoney, but those support operations like dividing by num.

**Comment by RdeWilde** [comment]
I would love to get this into Dart2. It makes working with BigInt much more easy and removes a lot of code fuzz

**Comment by franklinyow** [comment]
@alexmarkov 
Please re-evaluate this and do one of the following:

1. Add it to a milestone if it is still P1
2. Change priority label and add milestone if no longer P1
3. Close, if this issue is no longer needed

**Comment by alexmarkov** [comment]
FWIW I think this is nice to have, but it is not P1.
This improvement falls into the core library area, so I'll defer to @lrhn or @leafpetersen .

**Comment by lrhn** [comment]
We don't have any current plans to make `BigInt` implement `num`.

Implementing `num` is not without cost. For example, compiling to JavaScript can assume that any `num` is a JavaScript number and treat it more efficiently. If a `num` can also be a `BigInt`, then every `num + num`  operation in JavaScript would potentially have to check both operands for being `BigInt` before taking the efficient path.

We would also have to specify what `BigInt + double` and `BigInt + int` (and vice versa) evaluates to. Likely `double` for `BigInt + double` and `BigInt` for `BigInt + int`, but in JavaScript, integers are also doubles, so that could easily introduce subtle errors.

So, no current plan, not expecting this to happen unless something changes (like JavaScript getting both efficient integers and big integers)
