### ISSUE TITLE
dart2js doesn't defer as much as it should

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/sdk#32093]
We have a large application that after dart2js results in 100+ parts. We structure our application code in such a way that the only thing we need in the main bundle are framework pieces – essentially enough to render the application "shell". The application is then made up of a bunch of pieces that are all deferred loaded on demand. Ideally, this lets each piece of the application manage their own codebase independently without affecting the main bundle size.

The way we enforce this deferred boundary is by having each piece of the application provide a lightweight entry point that pretty much only exposes a lightweight "config" class that provides some static information upfront. The actual code is all hidden behind a deferred import and the config class has an async "load" function that calls `loadLibrary()` on that deferred import. Assuming that every application piece does this correctly, the main application only ever imports these config classes, meaning that the main bundle should never include anything more than these config classes.

Recently we've been investigating the result of our dart2js build because we suspected that we were not deferring everything that we should have been. In doing so, we discovered that several of these application pieces have a lot of their actual code (beyond the lightweight entry point) being pulled into the main JS bundle. We inspected their entry point setup and walked imports/exports to make sure they weren't inadvertently importing things they shouldn't have been in their entry point. This was a bit tedious so we even created a tool that uses the analyzer to walk all of the imports, deferred imports, and exports starting at `web/main.dart` and builds a graph that we can then query for all non-deferred paths from one file to another. In doing so, we discovered a couple offending imports that we removed, but even after that fix, we still saw way too much code from these pieces end up in the main bundle when we would have expected them to be deferred.

We tried coming up with a reduced test case, but unfortunately we were unable to recreate this behavior – my only guess here is that part of the problem lies in the size/complexity of our application.

We're at our limits in terms of trying to debug this issue (even tried using this dart2js dump-info visualizer: https://dart-lang.github.io/dump-info-visualizer/ – but our `.info.json` file for our build is over 600mb, which unsurprisingly crashes that page) so we're hoping that maybe someone with more expertise in this area can help. We've looked at the dart2js_info tools and used a couple of them to help create a more readable breakdown of the parts (which is partially how we identified this issue in the first place), but maybe there are some other strategies we can employ with those tools to understand how dart2js decides what to defer versus what it puts in the main bundle? Any guidance would be greatly appreciated!

**Comment by sigmundch** [comment]
Hey @evanweible-wf, thanks for filing this bug!

You are right that we need better tools for this. The dart2js_info tools get us part way there, but I think we need to store some additional data in the .info.json files to fully encode how the deferred slicing is made and so that tools can display this information. I believe we have the notion of dependencies in the info flies, which is what the [core-deps tool](https://github.com/dart-lang/dart2js_info#code-deps-tool) uses, but I don't believe we distinguish well between direct and deferred dependencies.

Re the visualizer: the dart2js_info tools should give you similar or more power to the dump-info-visualizer, we are however making progress in replacing that UI with a more scalable solution, but that wont be available until after we ship 2.0 in dart2js.

Until then, the only other suggestion I can think of is to instrument the compiler itself. Here are some pointers if that's something you would be interested in playing with. I'd selectively print information during the algorithm when [dependencies are detected](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/deferred_load.dart#L449) - knowing your app, you may be able to identify when you are seeing a dependency edge (from an `element` in main to a `dependency` that should not be in main), or to start from a dependency that clearly should not be pulled, and identify where it was pulled from and iterate until you find the culprit edge. It also helps to show a full [dump](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/deferred_load.dart#L801) of the result right [after the algorithm runs](https://github.com/dart-lang/sdk/blob/master/pkg/compiler/lib/src/deferred_load.dart#L697).

Hope this helps!

**Comment by evanweible-wf** [comment]
@sigmundch thanks for the pointers, I've started down this path but am unsure on the best way to go about running a local version of dart2js. I've checked out the `sdk` repo at the 1.24.3 tag and added some print statements at your suggested locations, but I'm having trouble running it.

Currently I'm just running `dart bin/dart2js.dart ...` from the `sdk/pkg/compiler` directory, but end up with this error:

```
The compiler crashed: Error reading '../../../sdk/lib/dart_client.platform'  (No such file or directory)
```

Is there a way to just run a local dart2js directly? Or do I need to build/run a local copy of `pub` and use `pub build`? Or do I possibly need to build a local version of the entire SDK (i.e. https://github.com/dart-lang/sdk/wiki/Building)?

**Comment by sigmundch** [comment]
I believe you should be able to run it without building the entire SDK.  It's possible that the `bin/dart2js.dart` file is out of date, though. I see the same error when I try it locally.

Try instead running the one inside lib/src:
```
dart pkg/compiler/lib/src/dart2js.dart
```
This is what ends up being wrapped and compiled as a snapshot when we ship an sdk (and worked for me locally at this moment).

**Comment by evanweible-wf** [comment]
@sigmundch that worked for me, thanks!

**Comment by joshualitt** [comment]
We've made a lot of improvements here, and we're now able to defer class types separately from classes which should help further.

If this is still an issue in your application, please file a new bug with an explicit repro.
