### ISSUE TITLE
Implement mixin application inference behind the super-mixins flag - analyzer

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#32146]
This is the analyzer version of #32019.  I've landed a partial implementation here: d9d2dc405bec9583831c5edd69a07ffac4cca621, but it needs further work to deal with mixins that don't pass their type parameters directly through to their superclass constraint.

**Comment by leafpetersen** [comment]
@stereotype441 Just a note about the language tests for this feature to avoid potential confusion: fuzzy arrows mean that currently `dynamic -> dynamic` is assignable with (e.g.) `int -> int`, which can cause confusion in language tests which can't cleanly distinguish between different compile time errors.  Some of the mixin language tests are "passing" on DDC, even though the inference is not working (presumably because DDC uses the legacy task model?), because of this.  Not really an issue, since DDC doesn't need to support these - just wanted to mention this caveat.
