### ISSUE TITLE
Core library async cast failure

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32143]
The program below causes a cast failure in the async library when run with DDC, but not with the Dart VM with --preview-dart-2 on.  I believe it should be well-typed both statically and dynamically, and so I think there is both a bug in the async libraries, and possibly a VM bug lurking here.  Starting with the libraries to verify that there is a bad cast there (if not, then this may be a DDC bug).  Repro below:

run with

```
dart -c --preview-dart-2 
```
or
```
pkg/dev_compiler/tool/ddc
```

```dart
import 'dart:async';

Future<T> test<T>(FutureOr<T> callback(int x)) {
  return new Future<int>.value(3).then(callback);
}

FutureOr<Future<int>> callback(int x) {
  return new Future<int>.value(x);
}
void main() async {
  print(await test<Future<int>>(callback));
}
```

cc @lrhn for the library question (is this in fact a bad cast?)

**Comment by lrhn** [comment]
I can't see where the cast error would be (and I can't figure out how to run DDC on Windows, so I'll check later).

The `callback` function looks correct (returning `Future<int>` from a function expected to return `FutureOr<Future<int>>` is correct. It should return a `Future<int>`.
The `test `function` looks correct, and there is no `async` magic going on. It should return a `Future<Future<int>>`. That's probably where things fail.
The `main` method should print `[Instance of Future<int>]` (or whatever `Object.toString` does for a `Future`). The await should only remove one level of future.

There is definitely a bug because the VM prints `3`, so either the `Future<int>` is not wrapped in the `then` call of `test` (which should cause a failure in checked mode?) or `await` unwraps too much.

If you just write `await callback(42)`, it's a little unclear what it should do, but to be type safe, it must actually check whether the result of `callback` is a `Future<Future<int>>` before unwrapping, and not unwrap a `Future<int>`. That is, its semantic behavior depends on the static type (because if it doesn't, it will try to return 42 in a context expecting `Future<int>`.

Not sure that's correctly implemented everywhere.

**Comment by lrhn** [comment]
Now gives a type error on other backends as well.
