### ISSUE TITLE
frontend_server compiler needs to be able to avoid using build-time absolute paths in the output kernel file.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#32168]
At present moment frontend_server wrapper around Fasta compiler uses physical file system which results in absolute paths showing up in the generated kernel file. There are cases where using actual build-time physical file system paths doesn't make sense, instead some synthesized file uris should be used.

There is MultiRootFileSystem (https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/multi_root_file_system.dart) that could help with that.

**Comment by aam** [comment]
cc @keertip @sigmundch @peter-ahe-google

**Comment by sigmundch** [comment]
Note that the multi-root file system solves 2 problems:

* use custom URIs to refer to files from the app (`org-dartlang-app:///path/to/file.dart` instead of `file:///absolute/folder/with/path/to/file.dart`)
* overlay more than one physical folder as if it was a single folder. This is useful in systems like bazel where generated code and source code is in one virtual folder, even though it is stored physically in separate places.

To solve the problem stated above, you only need the first part, which can basically be address by instantiating a multi-root file system with a single root. To integrate with build systems like bazel, we will need the second piece.

**Comment by peter-ahe-google** [comment]
As far as I know, pkg/front_end provides all the necessary API.
Please reopen this bug in a different area if there's more work to be done outside the front-end.

**Comment by sigmundch** [comment]
I think this was labeled with the wrong area. As I understand it, this was meant to track the work of updating flutter's frontend_server - @aam, am I correct? Should this be moved to the flutter repo instead?

**Comment by aam** [comment]
@sigmundch , correct. I opened this issue in dart-lang because I thought this use case is not relevant for public flutter use.
