### ISSUE TITLE
Confusing treatment of `return` vs. `return e`.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32177]
The language specification mandates the following:
```
It is a static warning if a function contains both one or more explicit return statements
of the form \code{\RETURN;} and one or more return statements of the form
\code{\RETURN{} $e$;}.
```
Of course, that means 'compile-time error' in Dart 2, unless we specifically change it.

Instead, we may wish to specify that a statement of the form `return;` is an error when the return type is not `void` (and considering how to handle `FutureOr<void>` separately). We already specify (in [generalized-void.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md)) that a statement of the form `return e;` is an error if the return type is `void` and `e` does _not_ have type `void` (or `FutureOr<void>`, which is an exception that we may or may not take away again).

One property that we may wish to ensure is that a function with return type `FutureOr<void>` is allowed to use `return;` in "the `void` case" and `return e;` in "the `Future` case":
```dart
FutureOr<void> foo(Future<void> future) {
  if (b) return;
  return future;
}
```

One thing that we may not want to allow is returning an arbitrary expression of type `void` when the return type is `FutureOr<void>`, because that "void expression" could evaluate to _any_ object, including a `Future<Something>`, in which case it would be interpreted as "the `Future` case" by the caller, even though it was obtained from an expression of type `void` and hence intended to be ignored.

**Comment by lrhn** [comment]
(My personal preference is to not allow `return voidExpression` ever, but I guess you know that :)

I think the most consistent version would be:
- Consider `return;` and `return voidExpression;` completely equivalent.
- Only allow `return [voidExpression];` in a function with a return type that `void` is assignable to.

We say that `void` is assignable to a type iff the the type is `void` or it is `FutureOr<T>` and `void` is assignable to `T`. (So, it's `FutureOr*<T>`).

The only question is, do we allow `return nonVoidExpression;` in a funtion with return type `void`.
I'm tempted to say yes because we already allowed `void ..() => nonVoid` (because it's "convenient", but it is *not* consistent). The only caveat is that we are doing users a disservice because a `return e` *suggests* that a value is returned, and if it isn't, that means it's bad for readability. So, we're not helping anyone by allowing it. 
That suggests that the answer is no, don't allow `return nonVoid;` in a function with a `void` return type.

Together this allows both `return;` and `return Future<void>()` in a `FutureOr<void>` returning function, so that's good.

I still think `void ... =>e` should not return the expression, it should be considered equivalent to `void ... { e; return; }` not `void ... {return e; }`.

**Comment by eernstg** [comment]
> Consider `return;` and `return voidExpression;` completely equivalent

Maybe. I'm assuming it means "allowed in the same situations". I'm less happy about making it mean the same thing semantically, because this would be yet another situation where the dynamic semantics is modified by the typing, and it's not even consistent because it hardly applies to the situations where the type in question is `void` because it's a type variable with that value.

> Only allow `return [voidExpression];` in a function with a return type that `void` is assignable to.

This includes one case that I've mentioned and argued against:
```dart
FutureOr<void> foo(void f()) {
  return f();
}

void bar(Object x) => print(x);

main() {
  bar(foo(print));
}
```

The problem is that when we allow `foo` to "return void to `FutureOr<void>`", we're silently leaking the supposedly meaningless value returned from `f` into a type that has no constraints on evaluation, and in particular, `bar` gets to `print` the value returned from `f` (which happens to be `print` also).

In that sense it's no better than allowing `Object x = voidExpression;`, which has never been considered OK (in discussions about 'generalized void').

Because of that, I'd prefer to allow `return [voidExpression];` _only_ in a void function, and developers would then have to use `voidExpression; return;` instead when the enclosing function returns `FutureOr<void>`.

> .. don't allow `return nonVoid;` in a function with a `void` return type.

Agreed!

> .. allows both `return;` and `return Future<void>()` in a `FutureOr<void>` returning function,
> so that's good.

Agreed, we want that! But in that case we could specifically allow `return;` in a function returning `FutureOr<void>` (plus, of course, in a function returning `void`).

> I still think `void ... => e` should not return the expression, it should be
> considered equivalent to `void ... { e; return; }`

This, luckily is a more local rule than the rule which says that `return voidExpression;` should replace the returned value by null (because `=>` functions tend to be quite small), but it does still have the same built-in anomaly that it will (probably) not work in the case where the return type is a type variable that in a given situation has the value `void`.

**Comment by lrhn** [comment]
> Maybe. I'm assuming it means "allowed in the same situations"

I'd prefer if `return voidExpression;` was equivalent to `voidExpression;return;`. I can settle for less, but that would be my preference.

The type variable isn't an issue to me since it will never actually be `void` at runtime, and at compile-time it's a type variable, not `void` either.


I can see the issue with 
```dart
FutureOr<void> foo() {
  return voidExpression;
}
```
but I don't see a distinction between this and
```dart
FutureOr<void> foo() => voidExpression;`
```
or even
```dart
Futureor<void> foo(void Function() bar) => bar();
Object something() => actualValue;
foo(something);
```
which is valid because non-`void`-returning functions are assignable to `void`-returning function types.
Which is why I *also* want `=> voidExpression;` to be equivalent to `{ voidExpression; return; }`. I believe that to be the one thing that *actually* prevents returning a meaningful value where it isn't expected.

I actually don't see a good way to prevent code like:
```dart
FutureOr<void> foo(Object bar) { 
  return bar;
}
```
The `bar` has type `Object` and unless we define `Object` to not be a supertype of `void`, this is an implicit down-cast to `FutureOr<void>` (which is not `void`, so we don't get special-casing unless we ask for it), and it will succeed at runtime if the value is assignable to either `Object` or `Future<Object>`, which everything is.
I don't know if making `void` a proper super-type of `Object` will change that. It would still make `Object` assignable (by implicit downcast) to `Future<void>`, but perhaps not to `void`(?), so we might be able to force this to be an implicit downcast to `Future<void>`.

So, my (standing) proposal is to make `return voidExpression;` and `=> voidExpression;` both evaluate the expression first and then act like `return;`. It dodges a number of issues. It is type-based compilation, but I can live with that (we allowed `void ...() => anything;`, so we can't claim to be purists :).

**Comment by eernstg** [comment]
Note that #32443 requests support for 
```dart
Future<void> f(...) async { ... return; ... }

// and this would seem similar:
Future<void> f(...) { ... /* no returns */ ... }
```
which seems natural given that `return;` is OK in a non-async function.

**Comment by pulyaevskiy** [comment]
I have a different use case which does not involve Futures and more relevant to JS interop.

In JS a function can contain both `return;` and `return e;` where the first is treated as returning `undefined`. Some JS libraries depend on this behavior. One such library is Firebase JS client
([docs for example function using this feature](https://firebase.google.com/docs/reference/js/firebase.database.Reference#transaction)).

I'm working on an [interop package](https://pub.dartlang.org/packages/firebase_admin_interop) wrapping that library and needed to find a way to return `undefined` without upsetting analyzer and Dart2 type system. This is what came up with:

```dart
  Function _createTransactionHandler<T>(TransactionHandler<T> handler) {
    // This is a workaround for analyzer which complains if a function contains
    // return statements with and without value.
    void undefined() {}

    // Firebase requires us to return JS `undefined` to indicate we want 
    // to abort the transaction.
    return (currentData) {
      final data = dartify(currentData);
      final result = handler(data);
      if (result._abort) return undefined(); // workaround continues...
      return jsify(result.data);
    };
  }
```

The above currently works in Dart 2.0.0-dev.32.0. But I'm worried that there maybe plans to make this invalid without leaving any alternatives.

Update: while writing this comment I think I found an alternative way to make the above work without relying on such workaround. Looks like JS interop allows me to define a binding to the value of `undefined` so I can rewrite my code as this:

```dart
  @JS()
  external get undefined;

  Function _createTransactionHandler<T>(TransactionHandler<T> handler) {
    // Firebase requires us to return JS `undefined` to indicate we want 
    // to abort the transaction.
    return (currentData) {
      final data = dartify(currentData);
      final result = handler(data);
      if (result._abort) return undefined;
      return jsify(result.data);
    };
  }
```

I think I'll probably switch to this version, but still leaving this comment here as I feel like it still highlights a relevant use case.

**Comment by eernstg** [comment]
@pulyaevskiy, I believe the approach you describe in the update is a good solution, and it should work also in the future. In particular, when `undefined` has type `dynamic` and the function literal which is being returned just needs to be a `Function`, the actual value of `undefined` is unrestricted at the Dart level (so you won't have to worry about spurious dynamic type check failures).

You might tighten the return type to `Function(dynamic)`, which would enable the recipients of the returned value to detect that it is wrong to pass two arguments to it, or to use named arguments, etc. But I guess that doesn't matter because the returned value is never handled by Dart code.

**Comment by eernstg** [comment]
Closing: The specification of the treatment of `return;` vs. `return e;` has been updated in [invalid_returns.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/invalid_returns.md), which eliminates the discrepancy described in this issue.
