### ISSUE TITLE
New lines are not printed correctly to the console after running dart with Process.Run

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#32172]
This is causing Flutter bug: https://github.com/flutter/flutter/issues/14696

Based on analysis by @DanTup, consider the following repro steps:

Create `test.dart`:
```dart
import "dart:io";

main(List<String> args) async {
  print("Hello\nworld1");
  await Process.run(args[0], ['--version']);
  print("Hello\nworld2");
}
```

Output from Dart SDK 23 and 22 on Windows:
![image](https://user-images.githubusercontent.com/13644170/36251134-5ad6f0f6-1240-11e8-8b3e-9fe4b3da4d5a.png)

**Comment by DanTup** [comment]
It's likely in one of these changesets:

https://github.com/dart-lang/sdk/compare/2.0.0-dev.22.0...2.0.0-dev.23.0

Based on the message/contents, I wonder if it's this?

https://github.com/dart-lang/sdk/commit/c9700040c344133f496e6451dffe20de3121acb6

**Comment by mit-mit** [comment]
One more datapoint: If I change the test.dart program to this, then the newline is properly printed:
```
import "dart:io";

main(List<String> args) async {
  print("Hello\nworld1");
  await Process.run('C:\\Windows\\explorer.exe', []);
  print("Hello\nworld2");
}
```

**Comment by DanTup** [comment]
I haven't tried, but my guess is that if you made the repro script in nodejs or something else you'd see the same problem; I think the issue is in the VM being spawned rather than in the spawning of processes. I think it only seems to happen the parent process too, the issue doesn't seem persist back in the console after the parent process finishes.

**Comment by mit-mit** [comment]
cc @bkonyi @zanderso looks like this might be caused by https://github.com/dart-lang/sdk/commit/c9700040c344133f496e6451dffe20de3121acb6 ?

**Comment by mit-mit** [comment]
tagging p0 as this blocks the flutter beta release

**Comment by zanderso** [comment]
I verified that https://github.com/dart-lang/sdk/commit/c9700040c344133f496e6451dffe20de3121acb6 is the cause. Reverting here: https://dart-review.googlesource.com/c/sdk/+/41840

**Comment by shinayser** [comment]
I am experiencing this issue in this very moment doing some tests with dart for server use cases.

```
Requisições por segundo: 830.1
Requisições por segundo: 831.3Requisições por segundo: 828.6

Requisições por segundo: 830.4
Requisições por segundo: 830.1Requisições por segundo: 828.6
Requisições por segundo: 829.1
Requisições por segundo: 829.7
```
`Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"`

**Comment by DanTup** [comment]
@shinayser can you open a new issue and provide the script that's writing the output? This issue was specifically caused when you spawn a Dart VM between lines - is that what you're doing?

Also - where are you seeing this output? If it's in something like VS Code's Debug Console, I think it's something else (I noticed some newline issues there yesterday when testing some scripts). If so, please raise with a repro at https://github.com/Dart-Code/Dart-Code. Thanks!
