### ISSUE TITLE
No analyzer strong mode error for void sync* and async* functions

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#32192]
Consider the following code
```dart
void h() sync* { }

main() {
  h();
}
```
Alanyzer in nostrong mode produces warning
`  warning - Functions marked 'sync*' must have a return type assignable to 'Iterable'`
I'm expecting an error in a strong mode but there is, surprisingly, no issues!

The same is true for async* functions
```dart
void h() async* { }

main() {
  h();
}
```
`  warning - Functions marked 'async*' must have a return type assignable to 'Stream'`
in a nostrong mode and no issues in a strong one

Tested on dartanalyzer version 2.0.0-dev.26.0 on Windows

**Comment by eernstg** [comment]
Note that in 9f9987f709ef0370367803859572b7fa6d2b844c we updated the feature specification [generalized-void.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md) to specify the following:
```
It is a static warning (in Dart 2: a compile-time error) if a function marked
`async*` or `sync*` has return type `void`.
```
So the declarations of `h` are compile-time errors specifically because they use `void` as their return type, not because of a missing assignability relationship.

Assignability has changed because of a different change, though, so that's probably the reason why the strong mode analysis does not flag this declaration: `void` used to be related to `dynamic` and the bottom type, only, but in Dart 2 it is a top type (like `Object` and `dynamic`), and this means that it _is_ assignable to `Iterable` today, but wasn't previously.

So the Dart 2 static analysis needs to implement the (newly added) specific rule about `void`, and these situations will then again be flagged as errors.

**Comment by srawlins** [comment]
@eernstg The text you refer to:

> It is a static warning (in Dart 2: a compile-time error) if a function
marked `async*`, or `sync*` has return type `void`.

does not seem to have made it out of the generalized-void into the language spec.

I see that CFE enforces this rule; the analyzer still does not. Should it?

**Comment by eernstg** [comment]
Good catch, thanks!

We do indeed not have any warnings or errors for return type `void` on a `sync*` function (or `async*` for that matter), we only require that the return type is a supertype of `Iterable<T>` for some `T` (`Stream<T>` for `async*`). I believe this is a mistake, and I created PR dart-lang/language#1060 to fix it.

**Comment by srawlins** [comment]
Thanks much!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/153953

**Comment by eernstg** [comment]
Thanks! The spec update dart-lang/language#1060 has landed.
