### ISSUE TITLE
Hover on instance fields doesn't always work

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#32212]
Post #32083, with the following example:

```dart
class Foo {
  final int _a;
  final int _b;
  int _c;

  Foo(this._a) :
    _b = 7 {
      _c = 21;
  }
}

void main() {
  var f = new Foo(42);
  print(f._c);
}
```

Hover works on the fields (declaration site) for `_a` and `_c`, but not `_b`.  

Stepping into the constructor from `main` also stops on those same field declarations *and* the constructor itself.  That is surprising but does correspond to the 5 lines in the generated code:

```
    this[_a] = null;
    this[_c] = null;
    this[_a] = a;
    this[_b] = 7;
    this[_c] = 21;
```

@jmesserly

**Comment by jmesserly** [comment]
Chatted about this:
- null assignment to `_a` is redundant code, we can eliminate that
- null assignment to `_c` is required (JS interop requires fields to be null rather than undefined) and we can't trust the body `_c = ` will be executed before `this` is visible (in this particular example of it's safe, because Foo extends Object and the assignment is the very first statement and the value expression doesn't use `this` ... but in general we don't know that)
- stepping behavior onto fields is intentional because fields can have initializers. Perhaps we should suppress it for implicit `null` fields (but that would break hover on them...)
- we don't step on `_b` fieldbecause it has a constructor initializer and that's the hoverable expression we mark.
- we could add a comment `this[_b]` or something like that for the `_b` field. It's tricky because whether it's necessary or not depends on how the constructors are written are whether the constructor itself ended up marking the field (as happened for `_a` and `_c` here)
- note that public fields won't have this problem, because of their virtual accessors, they should always support hover.

**Comment by jmesserly** [comment]
we can probably build on https://dart-review.googlesource.com/#/c/sdk/+/42085, though it'll need a few more tweaks. There's not a sensible node to put the comment on, so we'll have to add an empty statement or something like that, and make sure to filter out all fields that were already mapped by the constructor or by a virtual accessor pair.

**Comment by jmesserly** [comment]
@vsmenon ...this is actually worse than I thought. I don't think this can be fixed without Chrome support.

A few problems:

The hover spans for most field initializers above only work inside the constructor, because that's the scope they're marked in.

Even using a comment to mark the span, it doesn't work in a method unless that method already uses the field. I suspect it's because the private field symbol isn't captured in the closure, so V8 thinks the symbol isn't in scope.

Also virtual fields don't work consistently either. Currently, hover for `obj.foo` (a call site) will show the virtual getter(/setter) and allow jumping/breakpoints and "step into" for field getters/setters. However that breaks hover on the field declaration.

This all makes sense--the whole notion of declaration site hovering is not a thing in JS, because JS doesn't have "declaration site" for fields. (indeed, TypeScript does not map them: https://sokra.github.io/source-map-visualization/#typescript)

We may need to give up on declaration site hovering. (and perhaps we can change stepping on constructor field init so it's only the intiailzier expressions that are marked.)
