### ISSUE TITLE
Analyzer: Export `dynamic` from `dart:core`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32227]
The `dynamic` type should be should be exported by the `dart:core` library under the `dynamic` identifier.

As a built-in identifier, it's possible to declare members named `dynamic` (even thought you probably shouldn't), and those will shadow the `dynamic` in `dart:core`.

See #29125.

**Comment by jakobr-google** [comment]
Still an issue with dartanalyzer v 2.0.0-dev.48.0. When can we expect this to be fixed?

**Comment by bwilkerson** [comment]
What is the impact of this bug on users and/or clients?

**Comment by jakobr-google** [comment]
That's more or less it, yeah. In this case, it was prompted by package:googleapis (and anything else generated by package:discoveryapis_generator). I seem to attract code generation...

When we generate code (for either protobuf or discovery APIs), the problem is that the source schema may have definitions that end up shadowing things in dart:core, which leads to analysis warnings. A good example is 'Error', which is quite common as a response object.

My current issue is with discoveryapis_generator, where we generate code that imports dart:core with a prefix ('core'). We therefore refer to dynamic as `core.dynamic`, which seems to work in VM and dart2js, but analyzer reports errors for it.

**Comment by devoncarew** [comment]
@jakobr-google, do you have a work-around for this? This doesn't seem to be a recent regression.

**Comment by lrhn** [comment]
Jakob has left the building, but no, there isn't a good workaround except manually editing the files.
We have people doing manual editing every time they roll a new version of google-apis (see https://github.com/dart-lang/sdk/issues/32228#issuecomment-397595085).

**Comment by devoncarew** [comment]
@MichaelRFairhurst will be working on the Dart2Stable issues (in priority order).

**Comment by MichaelRFairhurst** [comment]
I have a solution to this which is maybe not particularly clean, maybe there's a better option that will come up in review or maybe it will be OK as is.

https://dart-review.googlesource.com/c/sdk/+/62730

**Comment by stereotype441** [comment]
Reopening since the fix was reverted.

**Comment by fishythefish** [comment]
Reopening since analyzer still permits the following:

```dart
import "dart:core" as mycore;

void main() {
  dynamic;
}
```

Analyzer should report that the name `dynamic` is undefined.

**Comment by devoncarew** [comment]
Do you see an issue if you give the field a name?

**Comment by fishythefish** [comment]
Yes:
```dart
import "dart:core" as mycore;

void main() {
  dynamic x;
}
```

The error that analyzer reports says that the built-in identifier `dynamic` can't be used as a type. It should instead be reporting that `dynamic` is an undefined name.

(I also get a hint that `x` is unused, which is fine.)

**Comment by srawlins** [comment]
Working now:

```dart
import "dart:core" as mycore;

void main() {
  dynamic x; // error here: Undefined class 'dynamic'.
  mycore.dynamic y; // no error.
}
```
