### ISSUE TITLE
Type inference should exploit "is" and "is!" semantics

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#32236]
Consider this implementation of equals excerpt from the code shown in [this section](https://www.dartlang.org/guides/libraries/library-tour#implementing-map-keys) of the [Library Tour](https://www.dartlang.org/guides/libraries/library-tour):

```dart
  @override
  bool operator ==(dynamic other) {
    if (other is! Person) return false;
    Person person = other; // (*)
    return ...
  }
```

As of Dart 2-dev.26, the type of `other` at (*) is dynamic.
Couldn't it be inferred as `Person`?

Similar arguments can be given for an `if` condition that makes use of `is`.

cc @kwalrath @stereotype441 @leafpetersen @eernstg

**Comment by eernstg** [comment]
The language specification gives some hints about the rationale for making exceptions about `dynamic` during type promotion (where we are considering `v is T` and `S` is the static type of `v`):
```
We do not want to refine the type of a variable of type \DYNAMIC{}, as this could lead to more warnings rather than fewer.
The opposite requirement, that $T \ne \DYNAMIC{}$ is a safeguard lest $S$ ever be $\bot$.
```
So the main point was, arguably, to let dynamic code be dynamic code.

We probably still want to maintain that no variable can be promoted _to_ `dynamic` (which is unlikely anyway, because `dynamic` is now a top type), but support for promoting _away_ from `dynamic` seems to be in line with the general development of the language from Dart 1 to Dart 2. I just marked this issue with area and type for a language enhancement request.

**Comment by leafpetersen** [comment]
Promotion from dynamic is part of Dart 2, but promotion in the continuation of a conditional is not.   I believe that the extended type promotion proposal that @bwilkerson wrote up handles this (and more), and that proposal had broad support on the language team.  While technically breaking, I'm still hoping that we will be able to land this post Dart 2 either as a minimally breaking change, or by using some sort of opt-in mechanism.

**Comment by eernstg** [comment]
Sorry, I overlooked that the example relies on `return` and `is!`. However, there is also #30906 which is about promotion and `dynamic` in Dart 2.

**Comment by lrhn** [comment]
Done.
