### ISSUE TITLE
The return type of `operator []=` should be `void` if omitted

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32241]
In Dart 2, if the return type for an `operator []=` is omitted it should be inferred as `void`. As of Feb 2018, the tools do not yet do that.

## Implementation tasks

It is likely that almost all tools will obtain the correct behavior from the common front end.

- [x] Front end (#32242)
- [x] Analyzer (#32243)
- [x] Specification (done in dd3f935cf5a0881ce102cb23595a20cecc08bd3d)

**Comment by eernstg** [comment]
Ah, I closed this because I saw a complete list of check boxes. But your response, @MichaelRFairhurst, seems to imply that the right thing to do would be to add more check boxes in the initial comment (in this case, I guess: for the non-CFE-analyzer), and then deal with that in a new sub-issue.

It looks like several folks thought it was done already: [This comment](https://github.com/dart-lang/sdk/issues/31779#issuecomment-358151529) was added to #31779  right after [I mentioned](https://github.com/dart-lang/sdk/issues/31779#issuecomment-355959593) that the language specification had been updated to require an `operator []=` with no explicit return type to have return type `void`: It says that 'The analyzer was fixed in bb52d1a. This CL should fix the front end: https://dart-review.googlesource.com/#/c/sdk/+/35005'. If it's a bug in one of those updates, maybe those CLs would be worth re-reading?

**Comment by MichaelRFairhurst** [comment]
Closing this again because its fixed for real this time!

> for the non-CFE-analyzer

in this case that's actually not specific enough! For non-CFE analyzer, we have two modes. One is deprecated, and that's the one DDC uses unfortunately. In the other path, it was implemented with tests and all that jazz.

To fix it in the deprecated path, I just landed https://dart-review.googlesource.com/c/sdk/+/43889

> add more check boxes in the initial comment ... and then deal with that in a new sub-issue.

I figured that this issue was only opened because of the DDC issue, so I would reinterpret the issue as about DDC itself...however, I did kind of break from the way you had started it and probably should not have! And I didn't update the title/description etc, so that also probably was not a great choice on my part.

Thanks Erik!
