### ISSUE TITLE
DDC: FutureOr<bool> can't be assigned to FutureOr<Null>?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32284]
```dart
FutureOr<Null> asyncInitDonePromise;

...

asyncInitDonePromise = new Future.value(true);
```

... causes a runtime exception:

`The literal 'true' with type 'bool' isn't of expected type 'FutureOr<Null>'`

Why? Isn't that fine?

**Comment by leonsenft** [comment]
No, `Null` is bottom. Think the opposite of `dynamic`/`Object`.

`dynamic` <- `bool` <- `Null`

Assignments can go left-to-right here, but not the other way. This API would work is it was `FutureOr<dynamic>`, since you can assign a `bool` to `dynamic`. The only thing you can assign to `Null` is `null`.

I think. 🤔

**Comment by leafpetersen** [comment]
What @leonsenft said.  Maybe you want `FutureOr<void>`?

**Comment by matanlurey** [comment]
Ah, that is what I want! Thanks!
