### ISSUE TITLE
Add a fix-it for `prefer_single_quotes` lint

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32301]
Would be awesome!

CC @bwilkerson

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/43580

**Comment by kevmoo** [comment]
Woo hoo!

**Comment by a14n** [comment]
@bwilkerson IIUC the patch adds a content assist to convert String literals. But I don't see any `prefer_single_quotes` in the diff. Shouldn't there be some changes in `pkg/analysis_server/lib/src/services/correction/fix.dart` and `pkg/analysis_server/lib/src/services/correction/fix_internal.dart` to provide a quickfix for this lint?

**Comment by kevmoo** [comment]
Commit: https://github.com/dart-lang/sdk/commit/716daa3b0d20c155a7b7055f65b604b68ada39b0

@bwilkerson – how do I use this in IntelliJ? I can't find the option...

**Comment by bwilkerson** [comment]
Sorry about the delay, I missed the reference.

I didn't implement it as a fix, I implemented it as an assist so that it's available whether the lint is being used or not.

If you're running a recent enough build, it ought to be available via the lightbulb drop down. I didn't check to make sure that IntelliJ shows assists when there are errors, but it ought to.
