### ISSUE TITLE
type argument dropped in strong-mode dart2js platform

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32303]
I'm not sure about the cause of this issue and unfortunately I haven't been able to isolate this to a small unit test outside of the sdk itself, so I'm not sure if it's just strong-mode or a mix of strong-mode and patch files that is making this happen at this time.

Here is what I'm seeing: calls to `new JSArray<E>.list(length)` are compiled with the `E` dropped in strong-mode. Here is how to see this:
* build a legacy sdk platform.dill for dart2js:
```
python ./tools/compile_platform.py --target=dart2js dart:core sdk/lib/libraries.json dart2js_platform.dill dart2js_outline.dill 
```

* build the strong sdk platform.dill for dart2js:
```
python ./tools/compile_platform.py --target=dart2js --strong dart:core sdk/lib/libraries.json dart2js_platform_strong.dill dart2js_outline_strong.dill 
```

* dump the context of each as text:
```
pkg/front_end/tool/fasta dump-ir dart2js_platform.dill > legacy.txt
pkg/front_end/tool/fasta dump-ir dart2js_platform_strong.dill > strong.txt
```

* look for calls to the JSArray.list factory constructor and see the difference.

For example, the definition of ListIterable.toList has one such call that, in legacy mode, includes E:
```
...
else {
  result = _in::JSArray::list<_in2::ListIterable::E>(this.{_in2::ListIterable::length});
} 
...
```

but in strong mode it doesn't:
```
...
else {
  result = _in::JSArray::list(this.{_in2::ListIterable::length}); 
}
...
```

Note: dart2js is making progress on implementing pieces of strong-mode by using the legacy .dill file at this moment, but this is clearly a blocking issue before. I have labeled this as high-priority for now, but could easily become critical

@stereotype441 @peter-ahe-google

**Comment by sigmundch** [comment]
I figured out the root cause: this issue relates to ec9c927b180f35f17d94f7fae7c97e94e9482056 where we resolve type arguments of redirecting factory invocations.

If I force "strongMode = false" in [getRedirectionTarget][1], then the problem goes away.

@stefantsov - could you take a look?

[1]: https://github.com/dart-lang/sdk/blob/b3056d8083ccc50a5bb918a3e0e6dadb817dd9ca/pkg/front_end/lib/src/fasta/kernel/redirecting_factory_body.dart#L130

**Comment by stefantsov** [comment]
`strongMode = false` works because type arguments of redirecting factories are handled differently in the strong mode and the legacy mode, but we need to fix the former.  Right now I have two ideas for what could the the root of the issue:

* Patching mechanism doesn't handle type parameters well.
* Type inference *within* redirecting factory constructors doesn't work.

I'm investigating.

**Comment by stefantsov** [comment]
So, it really looks like an issue with patching.  We resolve the targets of the redirection eagerly.  And it seems that in some cases we're doing it before patching is done.  Of course, the non-patched "external" method declarations don't declare type arguments for the right hand side of the redirection, and so we loose the arguments in this case.  The legacy mode works because it just passes through whatever was specified.

I had a refactoring in mind to move resolution of redirecting factory targets to some later stage in CFE.  It seems that it's a good time to do that now, because it should also solve this issue.  I hope I'll have the answer soon if that's really the case.

**Comment by sigmundch** [comment]
Makes sense - thanks for keeping us updated!

**Comment by stefantsov** [comment]
Ok, so the issue was with the patching, but not with the order in which resolution of redirection targets and patching happens.  The problem was with how the body that encodes the redirection attributes (the target and the type arguments) was propagated to the patched factory.  It was basically ignored :(  It is most likely an oversight on my part.

I've written a fix: https://dart-review.googlesource.com/c/sdk/+/44180.  The patched factory now uses the type arguments from the right hand side of the patching redirecting factory to build its body.  It also fixes the references to type parameters in those type arguments, because they now should reference type parameters of the patched factory, not those from the patching redirecting factory.

@sigmundch I've tried to see how the platform files are generated with the CL applied, and it looks like the strong-mode platform now has the previously missing type arguments.  Could you verify that the issue is solved by the CL?

That being said, the refactoring that moves the resolution of the targets of redirecting factories to a later stage of the compilation process is still a goal, it just has nothing to do with this issue :)

**Comment by sigmundch** [comment]
Thanks @stefantsov ! I patched it locally and I can verify that it will unblock us, thank you so much!
