### ISSUE TITLE
Boolean conversion in dart 2

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#32336]
According to @lrhn 

```
if(null) {
///
}
```
should be a compile time error in dart 2, and something like
```
if(foo) {
///
}
[...]
dynamic foo() { return null; }
```
should be a runtime error.

The current behavior is that - in general - it is seen as "if(false)", and in checked mode (which doesn't really make sense in combination with strong mode) it gives an assertion error: `Failed assertion: boolean expression must not be null`.

This is currently - not quite correctly I think - tested in language_2/bool_check_test.

@lrhn did I get anything wrong here, or am have I left something out?

**Comment by lrhn** [comment]
Disclaimer: I don't know the details of what strong mode says, so this is my opinion of how I would want it to be, not necessarily how it's actually specified.

Dart 2/strong mode is, effectively, Dart 1's checked mode with a stronger function subtyping rules (and inference, but let's just consider this as a post-inference issue).

In checked mode, a non-`bool` value in a condition is a runtime error. It happens to be defined as an assertion error, but that's just a convenience because Dart 1 conflates checked mode and enabled assertions. It allowed the spec to define only one "boolean coercion" function and use it in both checked and production modes.
I think Dart 2 should runtime err on a non-`bool` value in a condition too. It's a type error, and should happen whether assertions are enabled or not.

I also think that it should be a compile-time error if the static type of a condition is not bool or down-castable to bool (or, stated differently, if it's not assignable to *non-nullable* `bool`).
I'm not sure that's what we do, and if just require it to be assignable to the nullable `bool` type, then it's probably not a big issue (very few things actually have static type `Null`). It's definitely simpler to define for now, and we can always change it when we introduce non-nullable types.

**Comment by jensjoha** [comment]
Also language_2/bool_condition_check_test.

**Comment by jensjoha** [comment]
Other things to consider:
```
negFalse(x, y) => x != null ? !y : false;
negNull(x, y) => x != null ? !y : null;

main() {
  print(negFalse([], null));
  print(negNull([], null));
  var y = {};
  print(negFalse([], y));
  print(negNull([], y));
}
```

**Comment by lrhn** [comment]
Boolean conversion happens in various places in Dart 1:
* conditions (`if`, `while`, `for`, `?:`).
* boolean operator operands (`&&`, `||`, `!`).
* Switch case comparison (redundant because the case values are either system types or can't override `Object.==`).

We should treat it the same everywhere.

**Comment by eernstg** [comment]
> I also think that it should be a compile-time error if the static type of a 
> condition is not bool or down-castable to bool (or, stated differently, if it's
> not assignable to non-nullable bool).

This is very nearly `--preview-non-null-types-just-for-control-structures`. ;-)

Maybe we should consider introducing a full-fledged non-null `bool` ... and `int` ... and `String` ...? It could be seen as a similar approach as that of adding `FutureOr` (which is useful in its own right, but also allows us to explore the properties of union types in Dart).

**Comment by leafpetersen** [comment]
We could (but don't seem to currently) disallow `if (null) {}` because it is a guaranteed cast failure (just as we disallow `List<int> x = <dynamic>[]` even though the downcast is type valid.

Modulo that, all Dart 1 boolean conversion locations should be treated as requiring a boolean argument.  
- If the argument is not assignable to bool, static error
- Otherwise, if implicit-casts are on (as they are by default), it's an implicit downcast

So `!x` when `x` is not `true` or `false` should throw a runtime type error.

**Comment by leafpetersen** [comment]
This popped up internally, cc @srawlins

**Comment by srawlins** [comment]
Yes this popped up for me in an internal Flutter test. I think basically `flutter test` _is_ throwing a runtime error, but `flutter --preview-dart-2 test` is _not_ throwing a runtime error, when null is used in a boolean, like `foo && null`.

CC @a-siva

**Comment by crelier** [comment]
I am going to hook up the existing run time checks when in strong mode, but I will not change the kind of errors thrown, which are:
- AssertionError if value is null.
- TypeError if value is not of type bool.

Please, let me know if you need a different behavior.

**Comment by leafpetersen** [comment]
I'm in agreement with @lrhn that it would be cleaner to make the runtime error uniformly `TypeError` (especially since the error is emitted even if assertions are not enabled), but I'm fine with keeping this as `AssertionError` for now (which is what DDC currently does as well).  It's a very small breaking change to make later.

**Comment by crelier** [comment]
OK, great. We can update the tests and their expectations later when we uniformly report a `TypeError`. Thanks.
