### ISSUE TITLE
type arguments should not be null

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#32428]
After [change 45021](https://dart-review.googlesource.com/45021), these tests fail in dartdevk:

```
language_2/bug32353_test
Uncaught Error: type arguments should not be null: ...

language_2/recursive_mixin_test:
Uncaught Error: type arguments should not be null: ...
```

**Comment by jmesserly** [comment]
A few things were going on here:

1. This fix needs to be made to dartdevk https://dart-review.googlesource.com/c/sdk/+/19024

2. dartdevk needs to ignore synthetic mixin classes rather than trying to compile them (it has its own unrolling shared with dartdevc. Eventually dartdevk may be able to migrate to CFE/Kernel's unrolling, but for now it needs to ignore it.)
