### ISSUE TITLE
IntelliJ: Annoying to use `dev` channel, does not stay in sync

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32436]
Once a week I run `brew upgrade`, and then sometime that week open a project with IntelliJ, and its stuck on an earlier version, and I run into weird issues because I expect `dart --version` to == the version used by IntelliJ.

Is that an option I can configure? If not, can we add one?

I imagine `which dart` (or similar) is fine for most platforms.

**Comment by alexander-doroshko** [comment]
@matanlurey, what Dart SDK path do you have configured in Preferences | Languages & Frameworks | Dart? It should be `/usr/local/opt/dart/libexec` - it always points to the latest one installed by brew.

**Comment by matanlurey** [comment]
Wow, thanks @alexander-doroshko!

Maybe that can be the _default_, if possible?

**Comment by alexander-doroshko** [comment]
It ***is*** the default. I mean if Dart SDK combo box (Preferences | Languages & Frameworks | Dart page) is empty (which is true for a brand new IDE installation) then IDE prepopulates it with `/usr/local/opt/dart/libexec` text.
Otherwise, the Dart SDK combo box contains all previously used valid Dart SDK paths and shows the most recently used as the default one. It may be `/usr/local/opt/dart/libexec` or may be not - we respect the latest user's choice.

**Comment by matanlurey** [comment]
Ack. Maybe I've been using for such a long time that it doesn't seem like that.

Thanks!

**Comment by alexander-doroshko** [comment]
As far as I remember `brew` itself gives a hint right in the terminal that Dart SDK path to be used in the IDE is `/usr/local/opt/dart/libexec`.
