### ISSUE TITLE
Duration.InDays() works incorrect (?)

### ISSUE THREAD

**Issue by runningmaster** [dart-lang/sdk#32431]
Example (incorrect):
```
void main() {
  print(
      "${new Duration(milliseconds: (new DateTime(2014, 03, 30).millisecondsSinceEpoch-new DateTime(2014).millisecondsSinceEpoch)).inDays}");

  print(
      "${new Duration(milliseconds: (new DateTime(2014, 03, 31).millisecondsSinceEpoch-new DateTime(2014).millisecondsSinceEpoch)).inDays}");
}

$ dart ./test.dart 
88
88
```
Example (correct):
```
void main() {
  print(
      "${new Duration(milliseconds: new DateTime(2014, 03, 30).millisecondsSinceEpoch).inDays - new Duration(milliseconds: new DateTime(2014).millisecondsSinceEpoch).inDays}");

  print(
      "${new Duration(milliseconds: new DateTime(2014, 03, 31).millisecondsSinceEpoch).inDays - new Duration(milliseconds: new DateTime(2014).millisecondsSinceEpoch).inDays}");

$ dart ./test.dart 
88
89
}
```

Versions:
```bash
$ flutter --version
Flutter 0.1.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 6993b203c0 (7 дней назад) • 2018-02-27 17:39:49 -0800
Engine • revision e133da723c
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

$ dart --version
Dart VM version: 2.0.0-dev.28.0.flutter-0b4f01f759 (Tue Feb 20 17:53:06 2018 +0000) on "linux_x64"
```

**Comment by zoechi** [comment]
Looks suspicious to daylight saving interfering

**Comment by guyzk** [comment]
Have the same issue
When using difference.inDays between 1/3/19 and 1/4/19 the result is 30 days instead of 31.
My country moved to Daylight saving on 29/3.

Is there any roadmap to a fix?

**Comment by erf** [comment]
I experienced the same as @guyzk 

I live in Norway. 

Example:
```
    int numOfDaysInPeriod = DateTime(2020, 4).difference(DateTime(2020, 3)).inDays;
```
Expected result: `31`

Actual result: `30`

**Comment by ssivagnanam** [comment]
Hi Team,

When i compare two DateTime objects (04/10/2020 with 05/10/2020) using difference() method. I am getting Duration result as 23:30:0:00.00000.
Note : This issue occurs only in Australian Eastern Time Zone(Daylight saving).

Flutter : 1.17.5
Dart SDK : 2.8.4
Environment : VS Code (Mac OS).

**Comment by lrhn** [comment]
All of these issues occur around daylight saving, and are working as intended. The number of milliseconds between the two points in time are not a whole multiple of 24 hour, and 23 hours is not a day according to `Duration.inDays`.
If you want to count *days* between two calendar dates, use UTC time instead of local time, otherwise issues like this will crop up.

(The Australian example looks a little weird, because it's only changing time by 30 minutes. Some places do that, Australian *Easter* Time Zone shouldn't, according to my [brief search](https://www.timeanddate.com/time/time-zones-interesting.html). Are you sure you're not on Lord Howe Island time. Dart doesn't actually understand time zones, it gets its information from the operating system, so check your location).

All in all, working as intended.
