### ISSUE TITLE
Error: Superclass has no getter named 'serverApi' with --preview-dart-2

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32448]
I have a mixin

```dart
abstract class FirebaseDaoMixin implements DaoBase {
  @override
  ServerApiFirebase get serverApi => super.serverApi as ServerApiFirebase;
}
```
an abstract base class required to be implemented by the mixin

```dart
abstract class DaoBase {
  DaoBase(this.serverApi);

  final ServerApi serverApi;
```

and a class where I use it
```dart
class UserDaoFirebase extends UserDao with FirebaseDaoMixin {
  UserDaoFirebase(ServerApi serverApi) : super(serverApi);

  void foo() {
    serverApi.bar();
  }
}
```
```
compiler message: lib/src/server_api_firebase/firebase_dao_mixin.dart:11:44: Error: Superclass has no getter named 'serverApi'.
compiler message:   ServerApiFirebase get serverApi => super.serverApi as ServerApiFirebase;
compiler message:                                            ^^^^^^^^^
```
Works fine without `--preview-dart-2`

```
 (backoffice) $ flutter doctor -v
[✓] Flutter (Channel dev, v0.1.9, on Mac OS X 10.13.3 17D102, locale en-AT)
    • Flutter version 0.1.9 at /Users/zoechi/flutter/flutter
    • Framework revision 70f60b17d7 (2 days ago), 2018-03-05 08:55:10 -0800
    • Engine revision 97b22348c8
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68
```

**Comment by mraleph** [comment]
This 

```
abstract class FirebaseDaoMixin implements DaoBase {
```

should be this

```
abstract class FirebaseDaoMixin extends DaoBase
```

**Comment by zoechi** [comment]
@mraleph I don't think this is valid. Perhaps with supermixins enabled but that doesn't work with dart2js
The class where the mixin is applied to extends `DaoBase`

`class UserDaoFirebase extends UserDao ...`

**Comment by mraleph** [comment]
Yes, you can't use super-mixins anywhere outside of Flutter - and in Dart 2 `super` calls are only well-formed if class has appropriate super class.

So I think you can't write the code that would be both dart2js and Flutter compatible.

**Comment by zoechi** [comment]
@mraleph I updated the comment. Actually I use super-mixins. I had to change the implementation for Angular to not use that mixin. Sorry, I got a bit confused. 

But the code works fine without `--preview-dart-2` and in Dart1 and seems legit to me.

**Comment by mraleph** [comment]
Dart 1 does not report and error for "unbound" super calls. It is a static error in Dart 2.

/cc @lrhn Lasse, am I explaining it correctly?

**Comment by lrhn** [comment]
@mraleph is almost correct, and tools are probably mostly correct too. I doubt anyone gets everything right.

Looking at:
```dart
abstract class FirebaseDaoMixin implements DaoBase {
  @override
  ServerApiFirebase get serverApi => super.serverApi as ServerApiFirebase;
}
```

This should cause a warning in Dart 1.
The `super.serverApi` invocation should cause cause a warning because the super-class interface does not contain a `serverApi` member. From the ECMA Dart spec, section 16.7.3:
> Let *S<sub>static</sub>* be the superclass of the immediately enclosing class. It is a static type warning if *S<sub>static</sub>* does not have an accessible (6.2) instance member named *m* unless *S<sub>static</sub>* or a superinterface of *S<sub>static</sub>* is annotated with an annotation denoting a constant identical to the constant `@proxy` defined in dart:core. 

*Implementing* `DaoBase` doens't help. It does not introduce any constraint on the actual superclass that the mixin will be applied to. It only affects the interface of the `FirebaseDaoMixin` class, not its static superclass, which is the one that is the actual constraint.

The static warning that MrAleph is probably thinking of is the case where the static super-class declares the super-invoked member, but it is abstract. In that case, there is no warning even though executing the code as written will surely fail.

Now, this is only a static warning, so you might not get it if you only run the VM (or if some other tool forgets to show it).

In Dart 2, super-mixins are removed. You can't write a super-invocation in a class used to derive a mixin. You can't do a super-invocation where the super-class doesn't have a *concrete* implementation that you are targeting.

If this is Flutter code, we have provided a way to keep using a variant of the Dart 1 super-mixin behavior in Dart 2 *only until we provide a better alternative*, and then it should be using the rules for that variant. That one would still require the static supertype to declare the member, and since we don't do warnings any more, this is a Dart 2 + Flutter-mixins compile-time error (as the compiler correctly tells you).

**Comment by zoechi** [comment]
@mraleph @lrhn 
Thanks for the feedback. 
Should the issue be closed?

**Comment by lrhn** [comment]
I guess this can be closed. All tools are working as expected, the only problem is that the Flutter compilation fails to provide static warnings in Dart 1 mode. 
I can't tell whether that's because they just don't run the analyzer, or because the analyzer fails to report the warning.
