### ISSUE TITLE
Regression of AOT snapshot size due to change in mixin applications

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32458]
The change https://github.com/dart-lang/sdk/commit/9f56e283721ce7809f028680133484a6b24f9202 increased size of AOT snapshots.

```
tools/build.py -a x64 -m release runtime runtime_kernel
pkg/vm/tool/precompiler2 hello.dart hello.snapshot
ls -l hello.snapshot
```

Before change (at 3f71dc5dd297454f0fba5df2c196a155b6d97a49): 5,277,568 bytes
After change (at 9f56e283721ce7809f028680133484a6b24f9202): 5,940,000 bytes

Also, size of vm_platform_strong.dill increased:

Before: 5,245,186 bytes
After: 5,712,456 bytes

Is it possible to hide duplication of mixin applications behind an option and disable it for VM?

/cc @peter-ahe-google @mraleph @a-siva

**Comment by kmillikin** [comment]
Thanks for catching this.  We're not exactly duplicating them, we've just removed some (ad hoc) de-duplication.

I'm somewhat reluctant to have backend-specific encodings of mixins, because it's a pretty complicated corner of the language.

We should investigate how much flattening the classe hierarchy created for compositions saves us.  This code:

```dart
class M0 {}
class M1 {}
class M2 {}

class S {}

class C extends S with M0, M1, M2 {}
```
introduces three intermediate classes where we might be able to have only one.

We should also consider a whole-program mixin canonicalization pass for AOT that could catch more opportunities and make a better decision about sharing and code size.

**Comment by peter-ahe-google** [comment]
I also discussed this with @crelier and it turns out what I was doing before was very similar to the's VM approach in legacy mode.

Unfortunately, the previous solution generates classes that violate the rule that all  generic types must be instantiated with the same type argument. This has the following consequences:

* dart2js can't generate correct code and fails a number of tests.
* fasta can't infer the correct type arguments for mixin applications used by flutter.

The implication of this is that we can't do all of the de-duping in the mixin transformer because it would break incremental compilation and restarting from a .dill file in flutter.

Another thing to consider is that mixin applications are supposed to be light-weight, but due to the mixin transformer we blow them up in size. We're always doing this although its only really necessary when super calls in mixins are enabled.

/cc @rakudrama

**Comment by kmillikin** [comment]
To be explicit: we agree that the magnitude of the regression is alarming, and we should do something to fix it.

**Comment by sigmundch** [comment]
DBC - if the corelibs were benefiting from sharing across multiple classes, could we manually replicate the sharing by explicitly using named mixin applications?

For example, turn:
```dart
class S {}
class M0 {}
class M1 {}
class D extends S with M0, M1 {}  // generates _D&...
class E extends S with M0, M1 {}  // generates _E&...
```

into:
```dart
class S {}
class M0 {}
class M1 {}
class M = S with M0, M1; // generates a shared _M&...
class D extends M {}
class E extends M {}
```

**Comment by mkustermann** [comment]
As discussed offline with Peter, we'll raise this to P1.

**Comment by alexmarkov** [comment]
Implemented canonicalization of identical mixin applications as a separate transformation on kernel AST and measured sizes.

Current baseline (https://github.com/dart-lang/sdk/commit/e150bf638c93a16d9f4fb0288a1222fe9c059f8f):
```
flutter_gallery:
[+9851 ms] VMIsolate(CodeSize): 5667
           Isolate(CodeSize): 2488403
           ReadOnlyData(CodeSize): 2159256
           Instructions(CodeSize): 7572112
           Total(CodeSize): 12225438
hello.snapshot: 5508864
```

Baseline + https://github.com/dart-lang/sdk/commit/9f56e283721ce7809f028680133484a6b24f9202 is reverted:
```
flutter_gallery:
[+9253 ms] VMIsolate(CodeSize): 5667
           Isolate(CodeSize): 2386695
           ReadOnlyData(CodeSize): 2120392
           Instructions(CodeSize): 7253408
           Total(CodeSize): 11766162
hello.snapshot: 4810656
```

Baseline + canonicalization of identical mixin applications:
```
flutter_gallery:
[+9159 ms] VMIsolate(CodeSize): 5667
           Isolate(CodeSize): 2370077
           ReadOnlyData(CodeSize): 2124384
           Instructions(CodeSize): 7280912
           Total(CodeSize): 11781040
hello.snapshot: 4828640
```

/cc @stefantsov @peter-ahe-google
