### ISSUE TITLE
inconsistencies in constants representations with CFE

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32511]
Dart2js with the new frontend produces a different representation of constants that:
 * use "!="
 * use redirecting const factory constructors.

Examples:
* `1 != 2` is represented as `!(1 == 2)` with the CFE

* with the following code, `const B<int>()`  is represented as `const A<B<int>>`
```
class A<T> implements B {}
class B<S> {
  const factory B() = A<B<S>>;
}
```

Some of these cases are seen in `tests/compiler/dart2js/model/constant_expression_test.dart`

/cc @johnniwinther

**Comment by lrhn** [comment]
The type of `A<B<S>>` is `B<dynamic>`, which is often not a valid instance of `B<S>`. 
In particular `const B<int>()` should be a compile-time error because `const A<B<int>>()` would throw when returned from the `B<int>` constructor (because it doesn't implement `B<int>`, which is the return type of the constructor).

Am I missing something?

**Comment by eernstg** [comment]
I'd say that the factory declaration ought to be a compile-time error because it will not satisfy the requirement that the factory returns an instance of the required type. Let's assume that the requirement is satisfied for all `S`, that is, `A<B<S>> <: B<S>`. Then we must have `B<dynamic> <: B<S>`. But that is obviously not true for all `S`.

So the factory is "unsafe" in the sense that the bounds on type variables of `B` do not ensure that the invocation of the `A` constructor will pass type arguments that satisfy the bounds.

However, the language specification does not make this requirement explicit, and even though we have [an update](https://dart-review.googlesource.com/c/sdk/+/28140) in the pipeline which will make it an error to violate redirecting (factory or not) constructor type annotations in an invocation, we still do not have anything which directly says "a redirecting factory constructor which passes actual type arguments to the redirectee constructor must do so in a way where every actual type argument list to the enclosing class which satisfies the type variable bounds must also satisfy the type variable bounds on the redirectee". That's exactly the property that the factory in `B` above does _not_ have.

So it may well be reasonable to make this a compile-time error, but right now it isn't. I

**Comment by eernstg** [comment]
I think we should make unsafe redirection in a redirecting factory constructor a compile-time error at least when redirecting to a generative constructor: In that case the static type of the newly created object is known _exactly_ from the redirection expression, so it's not just a downcast (or sidecast, the two types could be completely unrelated with today's treatment), it is a downcast which is statically guaranteed to fail every single time. Just like `List<int> xs = <num>[];`.

For a redirecting factory whose redirectee may return a subtype (say, it's redirecting to another redirecting factory and at some point to a regular factory) we could say that this is a regular downcast, it may or may not succeed, so we allow it (and prohibit it with `--no-implicit-casts`) as usual.

**Comment by lrhn** [comment]
Which is saying that we should treat it as a normal assignment. If the RHS is known *exactly*, we can make the guaranteed cast error into a compile-time error, otherwise (if redirecting to another factory constructor) we fall back on an implicit down-cast. 

We can choose to special-case chains of redirecting factory constructors, because we know that the value is unchanged along the chain, but it's probably not worth it.

**Comment by eernstg** [comment]
I just made this issue part of the background material for [the CL on checking redirections](https://dart-review.googlesource.com/c/sdk/+/28140).

**Comment by sigmundch** [comment]
Thanks for looking into this - I had not looked in detail at the inconsistencies of this example with 2.0 semantics (there are more in https://github.com/dart-lang/sdk/blob/f66854a7008d2dc722269fd57820130c86782c66/tests/compiler/dart2js/model/constant_expression_test.dart#L140).

The reason I filed this bug was that I noticed that dart2js has different representations for these constants when using its old front-end and when using the new front-end.

Even in 2.0 valid code like:
```dart
class A implements B { const A(); }
class B { factory B() = A; }
```

Dart2js shows differences. Here if you creating the constant `const B()`, dart2js represents it as `const B()` with the old frontend, but as `const A()` in the new front end.

**Comment by vsmenon** [comment]
@sigmundch - I moved this to Beta 3 (trying to delete the beta1 milestone).  Is this still an open for dart2js?

@lrhn - Is there a separate issue to file for the for the CFE here?  Siggi's original example is a static error in Analyzer (assignability error) but allowed by CFE.

I.e.. the following is a static error in DDC but just prints `false` in DDK:
```dart
class A<T> implements B {}
class B<S> {
  const factory B() = A<B<S>>;
}

void main() {
  print(new B<int>() is B<int>);
}
```

**Comment by sigmundch** [comment]
still relevant, beta3 sounds good
