### ISSUE TITLE
Observatory: stop using pkg:browser

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32539]
Should no longer be needed.

```html
<script async type="application/dart" src="main.dart"></script>
<script async src="packages/browser/dart.js"></script>
```
to
```html
<script defer src="main.dart.js"></script>
```

Also cleanup

```
runtime/observatory/.packages:6:browser:../../third_party/observatory_pub_packages/packages/browser/lib/
runtime/observatory/pubspec.lock:30:      path: "../../third_party/observatory_pub_packages/packages/browser"
runtime/observatory/pubspec.yaml:26:    path: ../../third_party/observatory_pub_packages/packages/browser
runtime/observatory/web/index.html:10:  <script async src="packages/browser/dart.js"></script>
```

**Comment by kevmoo** [comment]
We're going to deprecated pkg:browser – we need to remove all usage from the SDK

CC @a-siva @devoncarew

**Comment by whesse** [comment]
This seems to be breaking dart2js tests on firefox and safari, including observatory tests.

**Comment by sigmundch** [comment]
I made a comment on the CL - I believe the issue is not about removing package:browser, but about removing web_components. The webcomponents polyfill is necessary in old browsers like IE11 for anything using custom elements, so my guess is that removing that package is causing a lot of the issues.

@kevmoo - I recall you were trying to remove all dependencies on web_components, but can we? It seems it was removed from the DEPS a while back, but indirectly it was available in the repo is because it was pulled in by the observatory-packages dependency. We however have tests in `html` that rely on the polyfill script, so my thinking is that we should bring it back as an explicit dependency in DEPS. Separately, if observatory tests need it too, we should probably include it in the observatory_pub_dependencies as well.

**Comment by a-siva** [comment]
I don't believe observatory needs it, we did a round of clean up couple of year back to remove all usage of web components from observatory.

If some other test was using the side effect that observatory-packages was pulling in web_components then the tests need to ensure that web_components is explicitly pulled in.

**Comment by sigmundch** [comment]
I believe the cleanup remove all uses of polymer, but it seems that observatory is built using a lot of custom elements (classes that extend HtmlElement), and use the custom element API (https://github.com/dart-lang/sdk/blob/master/runtime/observatory/lib/src/elements/helpers/tag.dart#L23)

While this is part of `dart:html`, this API works in modern browsers out of the box, but it needs the webcomponents-lite.js polyfill on old browsers.

**Comment by sigmundch** [comment]
Just had a quick chat with @kevmoo to clarify about next steps.

Here are my suggestions:
* readd web_components to observatory - since it is used by the app and it is needed to test it in old browsers, it seems accurate to keep it around. If we do this first, we can unbreak the broken bots faster, then we can work on disentangling this dependency between html & observatory (which I also believe shouldn't exist).
* make webcomponents-lite.js available in the SDK repo to use it in html tests (and hence remove that odd dependency). One way would be to readd web_components to sdk/DEPS (note that it is now moved to the dart-archive org, so we'd need to create a mirror for it pointing at https://github.com/dart-archive/web-components). Other ideas are to copy webcomponents-lite.js directly in the SDK repo.

Thoughts?

**Comment by a-siva** [comment]
regarding use of custom elements API in observatory, we would like to get rid of it but yes until that is done we will add web_components back to observatory-packages.

and yes please open a new issue for adding web_components to sdk/DEPS so we don't go through the same failures when we remove web components from observatory after cleaning up custom elements API..

**Comment by sigmundch** [comment]
Thanks Siva. Filed: https://github.com/dart-lang/sdk/issues/32742

**Comment by a-siva** [comment]
One other item to consider, do we really want observatory to be supported on older browsers?

**Comment by dgrove** [comment]
I don't think we need to support older browsers.

**Comment by sigmundch** [comment]
good point, I agree - this is mostly a development tool. Similary DDC only works on modern browsers that support ES6

**Comment by a-siva** [comment]
I will turn off these observatory tests on the older browsers and not bother with restoring web_components.

**Comment by sigmundch** [comment]
Note: #32742 is now fixed - the web components dependency is now explicitly listed in our DEPS for the html tests. This may accidentally turn the observatory tests green, but I still agree with @a-siva that it is a good idea to turn off testing on browsers where observatory is not supported.

**Comment by a-siva** [comment]
Turning off of observatory_ui tests on older browsers has landed. Closing this issue.

**Comment by whesse** [comment]
Fixed the dart2js builders requesting this file in https://dart-review.googlesource.com/c/sdk/+/60845
