### ISSUE TITLE
improve type error messages to facilitate Dart 2 migration

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32564]
`type '_Future' is not a subtype of type 'Future<bool>' where` errors are quite confusing for various reasons. Most common source of confusion are due to: 

* `<dynamic>` is omitted;
* `_Future` is an internal implementation type;
* why is  this not caught in compile time? 

I suggest we try to improve this message like this:

```
value of type '_Future<dynamic>', implements 'Future<dynamic>' and not 'Future<bool>', which is expected here.

Note that in Dart 2 dynamic is no longer a wildcard type. See http://dartlang.org/xyz for more details about this issue and how to address it. 
```

Based on flutter/flutter#15654 and other similar issues.

/cc @leafpetersen @a-siva @crelier

**Comment by crelier** [comment]
In a first step, I propose to completely hide the private class `_Future`, as we map Smi and Mint to int, and map it to `Future`. Then, in strong mode, raw generic types should be displayed with dynamic as their explicit type argument(s). So let's show `List<dynamic>` instead of just `List`, and `Map<dynamic, dynamic>` instead of `Map`.

In this case, the error becomes simply:
`type 'Future<dynamic>' is not a subtype of type 'Future<String>' where ...
`
Adding more explanation and links to docs in the error message seems a bit much, but we can always revisit if necessary.

I'll send a cl.

**Comment by matanlurey** [comment]
+1. @vsmenon @jmesserly I'd like to see the same improvement to DDC for the error message.

**Comment by lovasoa** [comment]
@crelier why not add a simple explanation or link explaining why A<dynamic> is not converted to A<MyType>? When coming from another language, it is confusing to get runtime errors about this. It would have saved me a lot of time when I first ran into this issue.
