### ISSUE TITLE
CFE: Implement missing override checks

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#32613]
CFE doesn't fully implement all checks related to overriding/inheriting members yet.
This includes reporting the following errors:
* When method is "overridden" with getter/field and vice versa.
* When static member conflicts with inherited instance member with the same name.

Currently, some of these errors are reported by VM. However, we would like to add tree shaking kernel transformation which removes conflicting members and VM no longer has a chance to report these errors. This issue will be used to silence failing tests for override checks in status files.

/cc @kmillikin @stefantsov @mraleph

**Comment by kmillikin** [comment]
As of 8f6c6c2a8edd514cdb6533541189a6572318facd it is now an error to declare an instance method and inherit an instance getter or setter with the same name, or to declare an instance getter or setter and inherit an instance method with the same name, or to inherit both an instance method and an instance getter or setter with the same name.

We don't catch the cases of static members conflicting with inherited instance members.  While we do catch duplicated declarations of methods and getters in the same class, we do not catch duplicated declarations of a method and a setter with the same name (presumably we should, which is related to issue #33077).

Note that there's an unfortunate interaction where we will signal an error for any conflicting inherited members, and also signal an error that they are not both implemented if the class is not abstract.  Since you can't actually fix the second problem by implementing both of them, we should find a way to suppress that error.

**Comment by eernstg** [comment]
Please note that the specification of member declaration conflict rules are being updated, cf. https://github.com/dart-lang/sdk/issues/33235. I believe that the behavior requested here matches the updated specification, but it may be useful to consult the table [here](https://github.com/dart-lang/sdk/issues/33235#issue-326617285) in order to clarify corner cases.

**Comment by leafpetersen** [comment]
I'm not 100% clear where the implementation is on this.  It sounds like most (but not all) of this is implemented in the CFE?  Probably relatively rare that this breaks something, but it will be a breaking change to fix.  I'm ok with leaving it as an open bug against Dart 2, but we will need to fix it at some point.

**Comment by jensjoha** [comment]
From the tables here: https://github.com/dart-lang/sdk/issues/33235#issue-326617285
It seems that 
```
has instance setter `n=`      has instance method `n`       2450 or 2451
```
is not handled, i.e. it should give an error, but doesn't.

and that
```
declares constructor `C.n`    has instance method `n`
declares constructor `C.n`    has instance getter `n`
```
should be allowed but isn't.

**Comment by jensjoha** [comment]
Oh, and there's also some tests tagged with 32613 that fails...

**Comment by dgrove** [comment]
Any updates on this, @jensjoha ?

**Comment by jensjoha** [comment]
https://dart-review.googlesource.com/c/sdk/+/64500 should make it comply with the tables at https://github.com/dart-lang/sdk/issues/33235#issue-326617285
https://dart-review.googlesource.com/c/sdk/+/64542 should fix tests tagged with 32613

**Comment by jensjoha** [comment]
and https://dart-review.googlesource.com/c/sdk/+/64840

**Comment by dgrove** [comment]
@stefantsov Can this be closed?

**Comment by stefantsov** [comment]
I believe so.
