### ISSUE TITLE
Clarify the behavior of invalid call against tearoff generated from NoSuchMethod-forwarding stub

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32630]
Consider:

```dart
class A {
 dynamic noSuchMethod(Invocation i) {
   print("A.noSuchMethod");
   return null;
 }
 void foo();
}

main() {
 A a = new A();
 dynamic f = a.foo;
 f(42);
}
```

What is the behavior on line 12?
DDC's behavior is to call `Object.noSuchMethod`, not `A.noSuchMethod`.
@leafpetersen confirms that this is implied by the informal spec. for NSM-forwarding.

However, @stefantsov and I were both confused about this, so it would be helpful to update the informal or formal specification with a clarification on this point.

@lrhn

**Comment by lrhn** [comment]
Leaf is correct.
The behavior is exactly the same as if `A.foo` had been declared as:
```dart
void foo() => this.noSuchMethod(Invocation.method(#foo, []));
```
At the invocation `f(42)`, the invocation fails, so it (effectively) calls `f.noSuchMethod(Invocation.method(#call, [42]))`. Functions do not override `Object.noSuchMethod`, so that is what you see.

(We *should* consider whether we actually want to keep using `#call`-Invocations for mis-called functions, but since functions can no longer have an overridden `noSuchMethod`, the exact details aren't really important).

@eernstg , is there an easy way to update the stand-alone specification of this?

(I would personally like to make torn-off methods forward their invalid calls to the `noSuchMethod` of the `this` object, but that's still just a wish).

**Comment by eernstg** [comment]
I agree completely with Lasse's analysis, so the feature specification update would just be a clarification. Here's a [CL](https://github.com/dart-lang/sdk/issues/32630) for that.

Alternatively, we could explore a completely different semantics where we would do much more to enable these invocations of `noSuchMethod` to go back to the original receiver (here, `A.noSuchMethod`), but that would be a much bigger step.

**Comment by vsmenon** [comment]
Is this still an open issue?

**Comment by leafpetersen** [comment]
Seems to be fixed in the VM now.
