### ISSUE TITLE
DDC throws TypeError instead of nSM with unexpected named arguments

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#32653]
Example:
```dart
void foo(int x) {}
main() {
  dynamic f = foo;
  try {
    f(x: 42);  // Should cause NoSuchMethodError.
  } on NoSuchMethodError {
    // expected.
  }
}
```
The error thrown here is not a `NoSuchMethodError`, but a 
```
Type 'NativeJavaScriptObject' is not a subtype of type 'int'
```
which suggests that the call succeeds even if the argument structure is entirely wrong.
Change the argument type of `foo` to `dynamic`, and then the invocation succeeds and you have access to the named-arguments-map.

**Comment by jmesserly** [comment]
Yeah there are a few bugs in DDC's invalid call handling:
- throws TypeError instead of calling NSM for argument count mismatches
- in the above example, treats the named argument map as a positional argument

... those might be the same issue, but I'll double check. The other one is tracked as https://github.com/dart-lang/sdk/issues/32088

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/48940
