### ISSUE TITLE
Regarding the implementation of conflicting generics in the case of subtypes

### ISSUE THREAD

**Issue by aemino** [dart-lang/sdk#32668]
As per commit 2993476, my code began erroring because of the new restriction on implementing the same interface multiple times with different generics.
However, consider the following code...
```dart
abstract class Base {}
abstract class Mixin<T extends Base> {}

abstract class A extends Base with Mixin<A> {}
abstract class B extends A with Mixin<B> {}
```
Should this be a compile-time error? In this example, `B` is a subclass of `A`, which isn't quite as questionable as using two generics that are not in the same inheritance tree.

**Comment by eernstg** [comment]
Yes, that is a compile-time error, there is no support for having two instantiations of the same generic class with different type arguments in the set of superinterfaces of any class, and we have `Mixin<A>` together with `Mixin<B>` here.

You could argue that this case is "less dangerous" than, say, `Mixin<int>` and `Mixin<String>` together, but even in that case you could add `Mixin<Null>` (here: in the `implements` clause of `B`) which would "resolve the conflict" by being most specific among all interfaces. So in reality there is only a small difference between the two situations.

You might be able to use `abstract class A<T> extends Base with Mixin<T> {}` and `abstract class B extends A<B> {}` (the `with` clause on `B` is redundant now).

**Comment by aemino** [comment]
Although I completely understand not allowing a _supertype_ of a generic in a mixin that has already been implemented, would a _subtype_ not be reasonably safe?  Perhaps I'm mistaken here.

Either way, not having the ability to override mixins causes a bit of an issue.  Your suggested workaround would certainly work, but I feel that attaching a generic to the class definition is a bit of a weird solution.  The purpose of adding a generic mixin to the class is to mixin methods with a particular type signature, in my case.  Delegating the generic to the primary `A` and potentially `B` class feels like an odd solution to this problem.  Those are just my two cents.

**Comment by eernstg** [comment]
> would a subtype not be reasonably safe?

Yes, it is in principle safe. It's actually easy to see: When you have a variable of type `Mixin<A>`, its value at run time might have type `Mixin<B>`, so there is no inherent violation of the expectations during static analysis if the same entity could also have both of those types as superinterfaces.

However, it is a source of complexity in a number of situations. For instance, if we wish to introduce the ability to declare that a given type variable has an exact value (let's assume the notation `!T` for a type variable whose value is exactly `T` rather than "something which is `T` or a subtype thereof"):

```dart
List<!C> cs = ...;
cs.add(new C());
```

If we allow an instance to implement both `List<C>` and `List<D>` where `D` is some subtype of `D` (or maybe some completely unrelated type, depending on the level of adventures we want to embark on) then this notion would be poisoned. In particular, we wouldn't be able to promise that the invocation of `add` is statically safe, and we wouldn't be able to obtain the performance benefits of avoiding all those dynamic checks that would otherwise be one of the main reasons for putting `!` into your code.

So we wanted to keep things simpler at this point, and making sure that we don't close a lot of doors for future development. The price for doing that is that `implements Mixin<A>, Mixin<B>` is not supported, but we expect the trade-off to be beneficial in the bigger picture.

> feels like an odd solution

Think about it like this: "`A` makes the promise that the signatures we need from `Mixin` are the ones that we will get with `Mixin<A>`".

Then maybe it makes more sense: It's simply not right for `A` to make such a promise, because we can't keep it anyway when we get to other classes like `B`. So `A` should not make such a promise; so `A` needs to be told from the outside which type argument to pass to `Mixin`; so `A` must be generic. Voila! ;-)

**Comment by aemino** [comment]
Thank you for the thorough appreciation -- I really appreciate it.

While your solution works in the example I initially gave, my predicament is a bit more elaborate and less generalized than the example code I initially provided (I'm trying to mimic the concept of dual-associated-types).  To avoid turning this into a "code help" thread, I'm going to go ahead and close this issue.

**Comment by eernstg** [comment]
Thanks for the kind words! I hope it works out for you.
