### ISSUE TITLE
Downcasting Futures

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#32672]
Consider this example with CFE (tested on `2.0.0-edge.8abeb56ebb35896754a1014da4415d570fd7c474`):
```dart
import 'dart:async';
import 'dart:typed_data';

void main() {
  // upcast Uint8List -> List<int>
  final List<int> data = new Uint8List(10);

  // implicit downcast
  Uint8List target1;
  target1 = data; // OK

  // declaration downcast
  final Uint8List target2 = data; // OK

  // explicit downcast
  final target3 = data as Uint8List; // OK

  // ------------------------------------------------

  // upcast Future<Uint8List> -> Future<List<int>>
  final Future<List<int>> futureData = new Future.value(new Uint8List(10));

  // implicit downcast
  Future<Uint8List> futureTarget1;
  // type '_Future<List<int>>' is not a subtype of type 'Future<Uint8List>'
  futureTarget1 = futureData;

  // declaration downcast
  // type '_Future<List<int>>' is not a subtype of type 'Future<Uint8List>'
  final Future<Uint8List> futureTarget2 = futureData;

  // explicit downcast
  // type '_Future<List<int>>' is not a subtype of type 'Future<Uint8List>' in type cast
  final futureTarget3 = futureData as Future<Uint8List>;
}
```

Does it mean that `Future` must be awaited before downcasting its value?

**Comment by eernstg** [comment]
It is certainly a source of spurious failures to downcast a wrapper like a future (e.g., a `Future<num>`) because the wrapper describes the type of the wrapped value in terms of an upper bound (so the `Future<num>` will fail in a cast to `Future<int>`, but the value obtained after completion might still be an `int`). You get the same kind of phenomenon if you have a `List<num>` which contains only `int` values: Downcasting the list to `List<int>` will and should fail, but if every element is an `int` then the downcast on each element will succeed.

The failures you describe have exactly this structure, so one way to put it is that a `Future` should indeed be awaited before you downcast the value.
