### ISSUE TITLE
Delayed Stream is causing Dart process to hang

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#32728]
Windows 10
SDK 2.0.0-dev.40

When I run this test via command line, my process hangs until the Stream actually completes:

```
test('listen on delayed event', () async {
    var s = new Stream<Null>.fromFuture(
            new Future<Null>.delayed(const Duration(days: 1)))
        .listen(null);

    await s.cancel();
  });
```
This causes a timeout, for example with a Travis build.

If I lower the Duration to 5 seconds for example, then my terminal becomes responsive again after this 5 second interval.

Expected: since I cancel my subscription, the delayed Stream should be discarded and my process should just terminate.

**Comment by matanlurey** [comment]
Future's are not cancellable, that is, there is no way to cancel the underlying action.

If you want your code to work this way, you'll need to write something custom with `Timer`. But this will be weird anyway, since Streams are meant for repetitive actions, and a Future/standard Timer only fires once.

Just use a one-shot timer?
