### ISSUE TITLE
Something wrong with the initialization of the Float32x4

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#32743]
_From @gyrdym on April 2, 2018 19:37_

Hi, fellows.

I've noticed, that during a creation of a Float32x4 value, `y` lane doesn't contain the original value. I have the example:
```dart
final vector = new Float32x4(-81796400.0, -81295300.0, -85285400.0, 0.0);
```
`vector.y` is expected to be equal to `-81295300.0`, but, instead, it equals `-81295296.0` for some reasons (Dart version: `Dart VM version: 1.24.3 (Wed Dec 13 18:05:29 2017) on "windows_x64"`).  Also, I have the live example - [unit tests in my repo branch](https://github.com/gyrdym/simd_vector/blob/simd-type-issue/test/float32x4_vector_test.dart) (the last two tests, starting at line 222). Hope, you will sort the problem out. Thank you!

_Copied from original issue: dart-lang/typed_data#11_

**Comment by mraleph** [comment]
@gyrdym

32-bit floating point number has 24 bits of mantissa precision. `81295300` in binary is `100110110000111011111000100`. This requires 25bits of mantissa precision to store precisely, if you take the leading 24 bits that gives you `100110110000111011111000...`, note how `100` (`4` in decimal) was cut off.  That's why you get `81295296.0` when you convert `81295300.0` to a float32 value.

**Comment by gyrdym** [comment]
@nex3 @mraleph thank you all for the concise and proper explanation!
