### ISSUE TITLE
No quick fix for missing import of `EdgeInsets`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32765]
![image](https://user-images.githubusercontent.com/405837/38315425-c156bd08-3828-11e8-89f3-04cc228edb22.png)

I could add all other identifies using a quick-fix

![image](https://user-images.githubusercontent.com/405837/38315530-f3a65ab6-3828-11e8-871d-e262d30a4119.png)

![image](https://user-images.githubusercontent.com/405837/38315459-d4785f86-3828-11e8-90bf-384eae2fe2bd.png)

```
(dart2) $ flutter --version
Flutter 0.2.2-pre.7 • channel dev • https://github.com/flutter/flutter.git
Framework • revision c0d1eb7513 (28 hours ago) • 2018-04-03 12:52:53 +0200
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357
```

I had this issue with `EdgeInsets` several times in different libraries already.
I don't know what's special about this one class.

**Comment by bwilkerson** [comment]
I suspect, though I haven't been able to confirm this, that the problem is that server is finding the class in an internal library and is not figuring out that it's re-exported from a public library. We must have done something to fix that for the rest of the material classes, but the fix probably isn't general enough to cover this case.

**Comment by zoechi** [comment]
`BorderRadius` and `Radius` also don't show the "add import" suggestion

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/54303
