### ISSUE TITLE
Analyzer implicit new/const insertion doesn't handle static const fields correctly

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32789]
The code below, with bleeding edge analyzer, produces the following error:

```
Analyzing /Users/leafp/tmp/ddctest.dart...
  error • Const variables must be initialized with a constant value at /Users/leafp/tmp/ddctest.dart:7:15 • const_initialized_with_non_constant_value
  error • Can't define the const constructor because the field 'd' is initialized with a non-constant value at /Users/leafp/tmp/ddctest.dart:8:3 • const_constructor_with_field_initialized_by_non_const
2 errors found.
```

I believe this code should be accepted.  This comes up in flutter example code.

```dart
class S { 
  static const foo = S();
  const S();
}

class C {
  final D d = D(s: S.foo);
  const C();
}

class D {
  static const foo = D();
  const D({S s});
}


void main() {
  C();
}
```

**Comment by bwilkerson** [comment]
@leafpetersen @lrhn @eernstg  I believe that the original problem no longer exists after the update to optional new and const. That said, it raises an interesting point. The spec gives the following condition as one of the conditions for being _in a constant context_:

> if _e_ is the initializing expression of a constant variable declaration.

Should this be taken to include the initializing expression of a final instance field when there is one or more `const` constructors? (I believe that the answer is "yes" because otherwise creating a `const` instance would have the wrong semantics.)

If so, should we update the spec to make that a little more explicit?

**Comment by lrhn** [comment]
Good point. It wasn't mentioned at all, mainly because we didn't think of it as a const requiring position.
The spec says, and should keep saying, that:
> It is a compile-time error if a constant constructor is declared by a class *C* if any instance variable declared in *C* is initialized with an expression that is not a constant expression.

As such, the position requires a constant, and we could make it a const context.

On the other hand, it's not a *local* property of the declaration. If you remove the constant constructor, you change the behavior of the field from constant to non-constant. If you introduce a constant constructor, your `_cache` field might suddenly be initialized with a constant map instead of a mutable map., with no warning until you try to modify the map at runtime.

I worry that this effect-at-a-distance will be error prone. If we didn't think of it as an obviously constant context, there is a good chance that users won't either. The safe approach would be to *not* make the RHS of fields in classes with const constructors be const contexts, you can always write `const` in front and get the effect anyway.

My immediate response would be that I prefer that. 
Leaf, WDYT?

**Comment by leafpetersen** [comment]
Based on a quick test, Lasse's preferred semantics are also what the VM currently implements, which suggests that this is the non-breaking approach.  So I'm fine with that.

Given that it seems like it might be nice for us to make it legal to have `const` instance variables, since it's cleaner to write `const x = C()` than `final x = const C()`.  Maybe something to add to our "small cleanup" list?

**Comment by lrhn** [comment]
I would prefer to reserve const instance fields for fields that can actually be *read* as a const expression.

(Currently any public field of a const-constructed object can technically be read off the object again, but that breaks getter/field symmetry. One option is to introduce const instance fields that promise to stay const, so it's a breaking change to make them a getter, at least unless we get const getters).

**Comment by lrhn** [comment]
I read 
> Given that it seems like it might be nice for us to make it legal to have const instance variables, since it's cleaner to write `const x = C()` than `final x = const C()`. Maybe something to add to our "small cleanup" list?

as suggesting that `const x = C();` was equivalent to `final x = C();` as instance field declarations, except that it introduces a const context. 
I am interested in using `const x;` as an instance field declaration as something different from `final x;` in that it allows *const access* (`const bar = const Foo().x`). That's not a small clean-up, so I didn't expect that to be the feature you were asking for. I'd prefer not to use the syntax for const instance fields on a minor clean-up :)

Also, you should *never* have a final field with an initializer expression in a const class. Instead of  `final x = const expr;`, you should write `get x => const expr;` and not allocate a useless field.

**Comment by eernstg** [comment]
Cool! So the initializer for a `final` instance variable in a class with a `const` constructor is not a constant context (and the feature spec remains unchanged in this respect), but the linter might recommend replacing the whole declaration by a getter. `const get x => expr;` might get a special treatment (it could be allowed to invoke such a getter in a constant expression if we constrain overrides as needed), but it's a non-breaking change to add support for that later.

**Comment by leafpetersen** [comment]
> I am interested in using const x; as an instance field declaration as something different from final x; in that it allows const access (const bar = const Foo().x)

Why is this different and not just an extension?  Once you have `const` instance variables, you could then at some point allow reading them (I guess you'd have to disallow overriding them with getters) and then perhaps at some point also allow overriding with some restricted form of getters?

**Comment by bwilkerson** [comment]
I believe that this was fixed by https://dart-review.googlesource.com/c/sdk/+/50280. Do you want to leave this open for the language discussion?

**Comment by leafpetersen** [comment]
Thanks, closing it!  We can take our discussion to the pub where it belongs.
