### ISSUE TITLE
dartdevc: `Type` values obtained from a typedef should represent the underlying type, not the typedef

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32785]
This is the dartdevc specific issue for #32782, which has the details. Note that it is possible that it will be resolved because the issue is handled by the common front end.

**Comment by jmesserly** [comment]
this will be a fix to DDC's runtime code. DDC hasn't implemented `Type.operator==` to understand type equality. So it will only work when we have identical underlying types (DDC usually canonicalizes function types, but typedefs are intentionally kept distinct from anonymous function types, for `toString()` purposes. Also DDC should not rely on type canonicalization as much as it does, so this will be nice to fix for that reason too.)

**Comment by jmesserly** [comment]
bumping priority, see comment by @matanlurey here: https://github.com/dart-lang/sdk/issues/34429#issue-358832991

**Comment by matanlurey** [comment]
Thanks @jmesserly! Just so I understand, the user complained that:

> It looks like in this case, DDC will let you provide a different value for each typedef, and let you compare them with `identical` as you might expect. But then when compiled with dart2js, it considers them different function types. My hunch is that dart2js throws away all the typedef names, and instead represents both of them as the same type?

... so, are you saying instead DDC should consider these different as well, like Dart2JS?

**Comment by matanlurey** [comment]
Internal issues:
* [b/69866909](b/69866909)
* [b/114776563](b/114776563)

**Comment by jmesserly** [comment]
thanks. I reopened the other one (https://github.com/dart-lang/sdk/issues/34429#issuecomment-420109008), in case we want to change dart2js behavior for identical. I'll look over the internal bugs. Probably we don't want to make them identical in dart2js, but I'll let those folks comment on that. 

It seems like a good idea to fix this one, though. If DDC offers you `==`, you'll have something that is consistent across DDC and dart2js that you can use. (`==` is better to rely on as it is spec'd)

**Comment by jmesserly** [comment]
I found my fix above (https://github.com/dart-lang/sdk/issues/32785#issuecomment-381270818), I'm still a little concerned with it because it changes function type canonicalization. I'm going to try and split that part out, so I can land just the `==` and `hashCode` changes.

**Comment by jmesserly** [comment]
Further investigation: DDC almost never preserves typedefs. They get converted into their underlying function type any time they're used as a type argument. (Might've been a workaround for this bug.)

Because of this, and in light of #34429, I'm leaning towards having typedefs being replaced by their function type in Type literals. This will make them identical.

`toString()` on the type literal will be worse, but we already lose track of typedefs in most cases, so it seems like a moot point. And this fixes Angular's issue, so that's nice. (The error message in cast errors will remain the same. For example, implicit casts to typedef types will show the typedef name, as they do now.)

I'm worried about dependence on `identical` for Types, as it may cause problems for DDC in the long run. Future performance improvements to DDC may conflict. But this is kind of my fault anyways, for making canonicalization too useful & available on everything (except typedefs). 🤷

**Comment by jmesserly** [comment]
CL out: https://dart-review.googlesource.com/c/sdk/+/74664

**Comment by jmesserly** [comment]
Sorry this is taking so long, we haven't had much code reviewer bandwidth for DDC. I'll see if I can find someone to review it.
