### ISSUE TITLE
May need to fix NSM forwarder behavior with mixins

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32792]
We need clarification about whether NSM forwarders are inserted after mixin application and whether mixed-in implementations with NSM forwarders override user-written implementations. The informal spec. is not clear about this.

1. What is the behavior of this program under Dart 2.0 semantics?
```dart
class M {
  dynamic noSuchMethod(Invocation invocation) {
    print("noSuchMethod");
    return null;
  }
}

abstract class I {
  int foo();
}

class C extends Object with M implements I {}

main() {
  var c = new C();
  var k = c.foo;
  print("hi");
  k();
}
```

For reference, our current behavior is:
```
hi
noSuchMethod
```

2. What is the behavior of this program under Dart 2.0 semantics?
```dart
abstract class I {
  int foo();
}

class M implements I {
  dynamic noSuchMethod(Invocation invocation) {
    print("noSuchMethod");
    return null;
  }
}

class S {
  int foo() {
    return 3;
  }
}

class C extends S with M {}

main() {
  (new C()).foo();
}
```

For reference, out current behavior is:
```
noSuchMethod
```

@leafpetersen: Please correct the priority/milestone based on your understanding of the impact that changing our behavior with these programs will have on "Bazel" and Flutter.

**Comment by leafpetersen** [comment]
The current behavior is my understanding of the correct behavior for Dart 2.

This is what is implemented by DDC, and what I propose we ship in Dart 2.

@lrhn ?

**Comment by dgrove** [comment]
Can you all please reach a conclusion on Friday?

**Comment by lrhn** [comment]
> whether NSM forwarders are inserted after mixin application

All classes are subject to NSM forwarder insertion if they are not abstract, has a non-default nSM and do not implement their interface. That goes for classes introduced by mixin applications too, it doesn't matter how the class is declared.

The first example is straight-forward. The class `C` is not abstract, it inherits a non-default noSuchMethod from its superclass `Object with M` and it has no implementation for the `foo` method of its interface. The fact that the superclass happens to be a mixin application is not relevant. The output is correct.
Even if the class `C` was declared as `class C = Object with M implements I;`, it would still get an NSM forwarder for `foo` because it satisfies the three requirements.

The second example is more interesting because you actually copy the existing NSM forwarder for `foo` from `M` and shadows the inherited `foo` from `S`. I agree that we should stick to the simple behavior of treating NSM forwarders the same as if they had been written explicitly, which means that the shadowing happens and printing "noSuchMethod" is correct.

Whenever you mix in a non-abstract class (which extends `Object`, because mixin classes must do that), you would expect to get an implementation of all members of the implemented interfaces (well, except `Object`). 

Most mixin classes are, or should be, abstract anyway.

**Comment by dgrove** [comment]
This should be closed, then?

**Comment by leafpetersen** [comment]
Closing this, we can open implementation specific issues if there's anything left to do.
