### ISSUE TITLE
Analyzer should warn when you assign something to a variable of type "void"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#32827]
The problem with `void` is that if you return or assign something into a slot of type `void`, it's silently swallowed. It's almost always a bug (or at best misleading in the code) to do this, as far as I can tell. We should have a lint to catch cases of doing this. This would let us move Flutter from using `Null` to using `void` in many places without risking introducing new bugs.

cc @pq @a14n

**Comment by Hixie** [comment]
cc @leafpetersen @munificent

**Comment by leafpetersen** [comment]
cc @lrhn

**Comment by lrhn** [comment]
The language allows assigning anything to `void` because it allows the use-case `void foo() => expr;` rather than `void foo() { expr; }`, which users have asked for, especially for setters (which are also `void` functions). You might want the lint to accept those uses.

Any other specific assignment to a variable (including returns or argument passing) with static type `void` is not necessary, and I personally have no problem linting against them.

**Comment by Hixie** [comment]
I think it'd be interesting to have two lints, one for each of the groups of cases you mention.

**Comment by a14n** [comment]
Could you provide snippets that show where you want lints?

**Comment by Hixie** [comment]
A classic case would be:

```dart
import 'dart:async';

void main() {
  Completer<void> completer = new Completer<void>();
  completer.complete(1); // LINT
}
```

But more generally:

```dart
class A<T> {
  T value;
  void test(T arg) { }
}

void main() {
  A<void> a = new A<void>();
  a.value = 1; // LINT
  a.test(1); // LINT
}
```

Interestingly there is already a lint for the case of returning a value from a `void` method:

```dart
void main() {
  return 1; // The return type 'int' isn't a 'void', as defined by the method 'main'.
}
```
