### ISSUE TITLE
Analyzer does not reject non-const partial instantiations for default parameter values

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32913]
This is the analyzer specific issue for the default parameter issue from https://github.com/dart-lang/sdk/issues/32415 .

Partial instantiations of generic methods are only `const` objects if their type arguments are `const` types.  The analyzer should statically reject the following program, but currently doesn't.

```dart
dynamic _defaultCallback<T>(T t) => t;
class C<T> {
  final dynamic Function(T) callback;
  // Should be statically rejected
  void foo([dynamic Function(T) f = _defaultCallback]) {}
  // Should be statically rejected
  const C({this.callback = _defaultCallback});
}

// Should be statically rejected
void bar<T>([dynamic Function(T) f = _defaultCallback]) {}

void main() {
  print(new C<int>().callback);
}
```

-----

**Comment by eernstg** [comment]
The example program could be deemed erroneous because those generic function instantiations use `T` and are then not constant, but it also seems possible to allow for a certain kind of inference "slack" that we have discussed a few times: We could instantiate as `_defaultCallback<Object>`.

This differs from the canonical example of inferring `const <Null>[]` from `const []` where a `List<T>` is expected and `T` is not constant, but given that the location is contravariant it's the same kind of slack for the type as a whole: We can choose a proper subtype of the type-from-context because the value is immutable, and there is actually a type which is a subtype of all the possible types-from-context, namely `dynamic Function(Object)`.

**Comment by lrhn** [comment]
I agree that it's fuzzy. The default value position *must* (currently) be const, but does not introduce a const context, so you have to write `const []` to get a constant list. 

That doesn't help you to write a const tear-off because we don't have a syntax like `const _defaultCallback`. Maybe we should (introducing a const context anywhere might be useful).
We also don't have syntax for `_defaultCallback<Object>`, so there is no pretty solution.

We could change the inference system to know that a default value should be inferred as-if it's in a const context, even if it isn't.
Or the user can change `_defaultCallback` to not be generic, since the genericity isn't used anyway:
```dart
dynamic _defaultCallback(Object t) => t;
...
  void foo([dynamic Function(T) f = _defaultCallback]) {}
```

**Comment by bwilkerson** [comment]
@leafpetersen Is this still an issue that we need to address for Dart 2 Stable?

**Comment by leafpetersen** [comment]
@bwilkerson  It would be good to fix this.

**Comment by MichaelRFairhurst** [comment]
I'm going to deprioritize this based on the discussions here. We're low on resources for 2.1.

It seems like whatever we do may change for some kind of "partial const" feature, or maybe const contexts of parameters needs to change. Therefore the work done now may only be valid for a short time and I think its better to focus on more well-defined bugs. It's also listed as a P2.

If anyone disagrees, do please weigh in.

**Comment by MichaelRFairhurst** [comment]
This actually has an even simpler repro:

```
dynamic _defaultCallback<T>(T t) => t;                                           
const f = _defaultCallback;
```

This is also broken, and if we fix this, we'll fix the original repro as well, I believe.

**Comment by MichaelRFairhurst** [comment]
We have violations of this in our own SDK:

```
R _rootRunUnary<R, T>(                                                           
    Zone self, ZoneDelegate parent, Zone zone, R f(T arg), T arg) {              
  ...
}
...
  _ZoneFunction<Function> get _runUnary => 
    const _ZoneFunction<Function>(_rootZone, _rootRunUnary);
```

**Comment by MichaelRFairhurst** [comment]
```
[error] Const variables must be initialized with a constant value. (dart:_http/overrides.dart, line 9, col 24)
[error] Arguments of a constant creation must be constant expressions. (dart:async/zone.dart, line 1245, col 48)
[error] Arguments of a constant creation must be constant expressions. (dart:async/zone.dart, line 1247, col 48)
[error] Arguments of a constant creation must be constant expressions. (dart:async/zone.dart, line 1249, col 48)
[error] Arguments of a constant creation must be constant expressions. (dart:async/zone.dart, line 1251, col 48)
[error] Arguments of a constant creation must be constant expressions. (dart:async/zone.dart, line 1253, col 48)
[error] Arguments of a constant creation must be constant expressions. (dart:async/zone.dart, line 1255, col 48)
[error] Const variables must be initialized with a constant value. (dart:io/overrides.dart, line 9, col 24)
```

**Comment by MichaelRFairhurst** [comment]
Internal CL 230792951

**Comment by lrhn** [comment]
The examples with `const f = _defaultCallback;` and `_runUnary` are not this kind of errors. In both cases, the generic function itself is used, not a generic instantiation of it, so there is no non-constant instantiation.
The error report saying:
```
[error] Arguments of a constant creation must be constant expressions. (dart:async/zone.dart, line 1245, col 48)
```
is incorrect. In all the cases, the arguments/values *are* constant expressions (references to static functions with no generic instantiation). For example, the function `_rootRunUnary` is directly assignable to `Function`, so there should be no generic instantiation here.

**Comment by MichaelRFairhurst** [comment]
Thanks Lasse for the quick response and correction. That certainly makes a big difference :)

It looks like we'll have to solve #32918 first. Current code does not do a partial instantiation, I don't think, but rather merely passing a subtype check. In any case, these issues are clearly very closely related and I may just end up solving both.

**Comment by MichaelRFairhurst** [comment]
Talked to @stereotype441 and this is independent of #32918. I missed the critical part about how inference behaves differently in the const contexts, and this, as covered here, is not a context, where #32918 is.

**Comment by MichaelRFairhurst** [comment]
OK, https://dart-review.googlesource.com/c/sdk/+/91105 is ready for review, seems to catch this, and passes TAP internally except for two violations.

The two fixes: cl/231432647 and cl/231440759

I'll also prepare a "breaking change" draft before landing

**Comment by stereotype441** [comment]
@MichaelRFairhurst it looks like https://dart-review.googlesource.com/c/sdk/+/91105 was code reviewed but not landed.  Can you get this landed?

**Comment by stereotype441** [comment]
After discussion with @MichaelRFairhurst, we've realized that:
- The front end implemented this change ~1 year ago without doing a breaking change announcement (oops)
- Mike's attempt to send a breaking change announcement ran into permissions issues (which is why no announcement went out)

It seems that making a breaking change announcement at this point would be silly, since the front end has prohibited this pattern for nearly a year.  Any code out in the wild that's affected by this change has surely already been updated.  So we think all that remains to do is to implement the correct logic in the analyzer.  This is nearly complete (just need to fix some unit testing issues).  However, since this no longer affects code in the wild, it doesn't seem like we should classify it as P1 anymore.
