### ISSUE TITLE
Assertion failure in Type::CloneUninstantiated in Topaz build

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#32927]
```
$ fx set x64 out/debug-x64 --args 'dart_debug=true'
$ fx full-build
...
../../third_party/dart/runtime/vm/object.cc: 17520: error: expected: IsCanonical()
```

dart=f76dad0adcf6766d73351354da653d6a793b5abc
engine=37e5df053024c1158b436ff0cd843116c25bdf14
flutter=1c3f6a851fcf33e8ef1bbb52bdae5ed116e463f4
topaz=cad814090fb99231f754b6a117defcad2e3b37b6

@crelier

**Comment by crelier** [comment]
The upper bound RenderBox of type parameter T below is not canonicalized:
"TypeParameter: name T; index: 0; class: RenderProxyBoxMixin; bound: RenderBox"
This is encountered while applying mixins to this class:
"Library:'package:flutter/src/rendering/proxy_box.dart' Class: RenderBox@174392247&RenderObjectWithChildMixin@176266271&RenderProxyBoxMixin"

Requiring the upper bound to be canonical is too strong, since cycles are easily formed via bounds, the reason why upper bounds are first finalized before being canonicalized.
I'll remove the assert.
