### ISSUE TITLE
Missing error on duplicated key in map literal

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#32983]
Iff all keys in a map literal are compile-time constants, it is a compile-time error if two keys are equal.

Caught by `language_2/compile_time_constant_o_test`.

**Comment by a-siva** [comment]
The Dart VM does not report a duplicate key error, the output from running this test
```
Unhandled exception:
Expect.identical(expected: <{foo: 499}>, actual: <{foo: 42, foo: 499}>) fails.
#0      Expect._fail (package:expect/expect.dart:651:5)
#1      Expect.identical (package:expect/expect.dart:177:5)
#2      main (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/tests/language_2/compile_time_constant_o_test.dart:32:10)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by lrhn** [comment]
For the record (because the original message didn't say that): Two constant keys may be equal, if they are not in a constant map. Two keys of a constant map (which must necessarily be constant) must not be equal.

**Comment by sgrekhov** [comment]
This issue is still actual.

The code below works and doesn't produce any error

```dart
class C {
  final a;
  final b;

  const C(this.a, this.b);

  bool operator== (other) => this.a == other.a;
}

main() {
  const m1 = <int, String>{1: "val1", 1: "val2"};
  var m2 = const <String, int>{"key1": 1, "key2": 2}; 
  const m3 = <C, int>{const C(1, 2): 1, const C(1, 3): 2};
  var m4 = const <C, int>{const C(1, 2): 1, const C(1, 3): 2};
}
```
Dart VM version: 2.2.1-dev.1.1 (Fri Mar 15 10:54:11 2019 +0100) on "windows_x64"

**Comment by eernstg** [comment]
The example [here](https://github.com/dart-lang/sdk/issues/32983#issuecomment-474216618) should definitely produce errors, but a couple of them may not be relevant: We should get an error because `m1` has two keys with the value `1`, and ditto for `m1` and `"key1"`; but with `m3` and `m4` we should get an error because `C` does not have a primitive operator `==` (spec, section 'Maps'):

```
It is a compile-time error if the operator
‘==’ of the key of an entry in a constant map literal is not primitive (10.1.3).
```

So we would have to rely on canonicalization and `Object.==` (that is, not overriding it in `C`) in order to get the errors associated with duplicate keys in constant maps.

Also, it might remove a source of confusion to use `hashCode => a.hashCode` (even though the dynamic error associated with returning an instance of `C` won't occur as long as we are considering an example with compile-time errors).

**Comment by kmillikin** [comment]
This will be fixed when the new front end constant evaluator is enabled.
