### ISSUE TITLE
CFE reports an error as a crash when using part and import statements

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#32999]
```dart
// File main.dart
library test_lib;
import 'test.dart';
part "part_of_the_lib.dart";

main() {
  test();
}
```
```dart
// File test.dart
library test_lib;
part "part_of_the_lib.dart";

test() {
  foo();
}
```
```dart
// File part_of_the_lib.dart
part of test_lib;

bar() {}

foo() {
  bar();
}
```
Now run `dart --preview-dart-2 main.dart `
Output:
```
Crash when compiling file://.../test.dart,
at character offset null:
part_of_the_lib.dart:8:1: Internal problem: Couldn't find 'bar'.
bar() {}
```
Now run `dart main.dart` and there will be no issues.
Also no issue in analizer even with --preview-dart-2 option

Dart VM version: 2.0.0-dev.50.0 (Wed Apr 25 11:29:49 2018 +0200) on "windows_x64"

**Comment by lrhn** [comment]
@leafpetersen 
Is it a strong-mode/Dart 2 *error* to import two libraries with the same name? It's a warning in Dart 1, so consistency would suggest that it's an error. It's not a very *important* error, though.

**Comment by eernstg** [comment]
Of course, it's an issue that `dart --preview-dart-2` (that is, the common front end) says `Crash when compiling ...`, so that should be fixed no matter which treatment the situation gets thereafter.

We could say that (1) it's an error if a program contains two libraries with the same, non-empty name, or that (2) it's an error if a part has an ambiguous `part of` directive because multiple libraries in the program has the indicated name, or we could say that (3) it's an error if a part _P_ has an ambiguous `part of` directive because multiple libraries in the program has the indicated name _and_ they specify `part U` where `U` denotes _P_, and we could even (4) allow the latter.

(4) can be perfectly well-defined, but it conflicts with separate compilation, so we probably don't want that; (3) is possible (though confusing, because you could be looking at `library L` and `part of L`, and the latter would still not necessarily be a part of the former). You could say that (1) is overly strict, because there is simply nothing that goes wrong because of that type of library name conflict (which is already sort of implied by the fact that we accept having several libraries with the empty name).

So, to me, (2) seems to be a reasonable level of strictness: If you say `part of L`, there can't be two libraries named `L` in the current program.

But what does the spec say now? I remember that it used to be a name clash, and Gilad made an adjustment specifically to make it OK to have two or more libraries whose name is empty (to allow `library` directives to be omitted entirely). Here's the relevant update to dartLangSpec.tex (commit a0e4f281609de0e4c66676c299f630d570e9e276):

```
-It is a static warning to import two different libraries with the same name.
+It is a static warning to import two different libraries with the same name unless their name is the empty string.
...
-... It is a static warning to export two different libraries with the same name.
+... It is a static warning to export two different libraries with the same name unless their name is the empty string.
```

So that's the wording that makes it a warning (in Dart 2 presumably: error) for direct imports to have this type of name clash, and the update eliminates the conflict for the empty name, but it is not obvious to me that it would be a name clash to have two libraries with the same name in the same program, as long as no library imports/exports both of them directly.

This means that we currently have something which is not any of the levels (1)..(4) that I mentioned (and I really don't think it's a problem to import or, especially!, export two libraries with the same name), so I'd recommend that we adjust the specification to make it (2).

**Comment by leafpetersen** [comment]
cc @vsmenon @sigmundch @bwilkerson @jmesserly 

I'm interested in implications (if any) for tools.  Library names are mostly pointless from the user perspective in Dart, right?  So it doesn't seem terrible to import the same library names.  But it doesn't seem especially useful either.

**Comment by jmesserly** [comment]
> I'm interested in implications (if any) for tools. Library names are mostly pointless from the user perspective in Dart, right?

DDC ignores library names. They're often not well maintained (e.g. still use an old file name or path). The style guide encourages using the `part of` syntax that accepts strings: https://www.dartlang.org/guides/language/effective-dart/usage#do-use-strings-in-part-of-directives

So in this case, you'd have to pick `part of "main.dart"` or `part of "test.dart"`.  The old `part of lib_name` syntax is deprecated right?

**Comment by leafpetersen** [comment]
@lrhn Any thoughts?

I'm somewhat disinclined to make it an error for two libraries with the same name to *exist* in a program, since it feels like causing breakage for no really good reason, and in ways that users can't necessarily control (e.g. they use two packages, both of which have an internal library named "internal_lib").

I would prefer to not allow the same files to be included in different libraries at all, but I seem to remember that we have code which uses this "feature".

**Comment by lrhn** [comment]
My suggestion is to do what DDC does: Ignore library names.
Then allow `library;` with no name and even `part;` with no `of name`, and forget that library names ever existed.

I don't care if someone wants to include the same part in multiple libraries. It's textual inclusion, so you get what you ask for (separate statics, potentially completely different declarations because type names mean different things). I am worried about someone using parts as an API for abstracting ("import this part, declare the `Foo` and `Bar` types, and then you have a customized class for your types"), but if that's an issue, maybe we should just provide a better feature for doing that kind of modularity.

In practice, all imports are package imports. The case that duplicate library name checking was about was to avoid importing the same library via different paths. That just doesn't happen for imports (it happens for entry-points, but we should fix that instead).
If two distinct package names refer to libraries with the same name, you probably did it on purpose (e.g., to have two different versions of the same library at the same time).

Complaining about a conflict between self-appointed names in a global name-space is just not a good idea.

**Comment by eernstg** [comment]
Sounds like you'd prefer to declare that there is no conflict, even when `part of foo.bar;` in a part _P_ is resolved to multiple distinct libraries _L<sub>1</sub> .. L<sub>k</sub>_ named `foo.bar` in the same program (just like `part;` would be happily matched up with multiple nameless libraries, as long as they all specify `part _P_;`).

I can see that it should be a non-problem for compilers to handle this, as long as modular compilation schemes do not generate code for a part, but it would be somewhat confusing if IntelliJ is showing a part file (which is embedded in several distinct semantic contexts in the same program) and it doesn't really know which typing environment to use for completion etc.

**Comment by askeksa-google** [comment]
We are going for option (3) for now: make it an error to include the same file as a part in more than one library in the same program. https://github.com/dart-lang/sdk/issues/33225 tracks the necessary spec change.

**Comment by askeksa-google** [comment]
Before the fix in https://dart-review.googlesource.com/c/sdk/+/56521 can be landed, we need duplicate parts cleaned out from the co19 test framework code: https://github.com/dart-lang/co19/issues/149
