### ISSUE TITLE
infra: logs cleanup

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33078]
This may be already on your radar, but I've noticed a few frictions when it comes to accessing logs:
  * logs are long and take a while to load (and failures tent to be summarized at the end)
  * not all bots use the same log format (different flags for test.py)
  * logs from browser tests are noisy

Overall, it would be nice if we could make changes to make it easier to extract errors from the build bot results. Some ideas that can help here:
* unify on a single format for calling test.py on all configurations
* remove unnecessary text in the buildbot format from test.py, for example we no longer need the progress indicators (since luci doesn't support these):
```
!@@@STEP_CLEAR@@@
!@@@STEP_TEXT@ 99% +16656 -1 @@@
```
* create a separate log file containing only failures, ensure that every step contains a link to it, and educate team members about it
* review logs from browser tests and see what can be done to reduce the output to just logging the failure message (currently we include debug messages from the test_controller.js and a dump of the DOM, both of which are not valuable when inspecting failures of langauge and corelib tests)

**Comment by whesse** [comment]
Most of these issues have been resolved by storing test logs in a logs.json file, and uploading them to cloud storage.
The logs viewer, which is linked to from the results feed, shows logs for individual failing tests.

Testing has been extensively changed since this issue was created, and test logs are no longer sent to stdout for test steps. Test.py is called using recipes and options are taken from test_matrix.json.  Closing the issue as completed and/or obsolete.
