### ISSUE TITLE
Inconsistent override errors on setters and methods

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33077]
The analyzer in preview-dart-2 mode issues errors on the overrides of `n` and `o` in the code below, but not on `m`.

This seems inconsistent, but possibly consistent with the spec:

"It is a static warning if a class C declares an instance method named n and has a setter named n=."

@lrhn @eernstg I presume this is not intentional?  Do we need a spec fix? 

Assuming this is not intentional, I will file an analyzer bug and a spec bug if needed.

```dart
class B {
  int m() { return null; }
  void set n(int x) {}

}
class A extends B {
  void set m(int x) {}
  int n() { return null; }
  int o() { return null; }
  void set o(int x) {}
}


void main() {
}
```

cc @kmillikin @bwilkerson

**Comment by lrhn** [comment]
I agree that we should disallow it.
I'm not sure what the spec currently says, but I see no good reason to not have the symmetric warning if the class declares an instance setter and has a method with the corresponding getter-name, and make that a Dart 2 error.

That would mean that in Dart 2, you either have a *property* (getter and/or setter) or a method, but never a combination.

**Comment by kmillikin** [comment]
The spec says it's a warning to have a setter and declare an instance method with the same name.  (Why only instance methods?)

It doesn't seem to be a warning to have a method and declare a setter with the same name, or to have both a method and setter with the same name.  So this seems like a weirdly specific warning, but I ignore those anyway.  Since it becomes a Dart 2 error, then there's a real inconsistency.

Spec has this non-normative commentary: "Hence, a setter name can never conflict with, override or be overridden by a getter or method."

It's hard to know if this is intended to allow having both a setter and a method, and randomly warning about some cases, or if this is just an observation.

(The whole bit about requiring setter names to be decorated in a particular way seems overly specific.  You just have to distinguish them some way, which I think the spec always does anyway, and you might do that by having them stored separately from getters and methods, or by having a tag bit on them, or any other way you like.  If we just said that they had to be distinguished, we could use the much more pleasant "with the same name" instead of "named n... and named n=....".)


A related question: it seems consistent with the discussion in this issue to also make it an error to declare both a method and a setter with the same name in the same class.  As far as I can see, the spec allows that and the tools do too.  But if we do allow that, then there isn't any real benefit to preventing you from having both some other way.

**Comment by eernstg** [comment]
We have a bunch of rules about name conflicts, so let's get an overview (looking at dartLangSpec.tex from fe3f87f192fbec44ba77c6f01334b8bcb849a63d):
```
Member1           Member2           Location             Conflict   Spec_line_number
------------------------------------------------------------------------------------
n                 n                 same scope           error      342, 1274
n, static         n, instance       same class           error      1275
n                                   in class n           error      1302
n                                   in class w/ty.var n  error      1303
n, getter         n, method         same class           error      1420
n, member         C.n, constructor  same class           error      1632
n, top-level      p, prefix         same library         error      8603
n, exported       n, exported       not same decl.       error      8778

n, inst.method    n=, setter        declares resp. has   warning    1325
n, stat.getter    n=, inst.setter   declares/has         warning    1433
n=, stat.setter   n, inst.member    declares/has         warning    1492
n, stat.method    n=, setter        declares/has         warning    2171
n, library name   n, library name   both imported        warning    8673  (n not empty)
n, library name   n, library name   both exported        warning    8779  (n not empty)
```

I'll take it for granted that `warning` means `error` now (or that we don't care in this context). The rules
would apply as follows:

```dart
class B {
  int m() { return null; } // Not 1325: doesn't have setter m=.
  void set n(int x) {}
}

class A extends B {
  void set m(int x) {} // Not 1325: doesn't declare instance method `m`.
  int n() { return null; } // 1325.
  int o() { return null; } // 1325.
  void set o(int x) {}
}
```

As far as I can see we have the unintended missing case that @leafpetersen and @kmillikin mentioned, and we will be able to cover it by simply adding the following sentence (say, as a new line 1326):

```
It is a static warning if a class $C$ declares a setter named $n=$ and has an instance method named $n$.
```
We could also change the existing line 1325 as follows:
```
It is a static warning if a class $C$ has an instance method named $n$ and has a setter named $n=$.
```
but that would make it less obvious where to _report_ the problem, so I'd prefer the former.

The remaining question is whether we need to revise the rules about static members as well.

> warning to have a setter and declare an instance method with the same name.
> (Why only instance methods?)

I believe the static methods are covered by line 2171. We might combine the two, but they may sit in different sections such that it's confusing to say both things in one of those sections. Will take a look.

> It doesn't seem to be a warning to have a method and declare a setter with the same name,

Double-checking what I found, this would be covered by line 1492 for static setters (vs. both instance methods and instance getters), and by line that I suggested we should add above for all setters vs. instance methods. So we should be OK with that part now.

> or to have both a method and setter with the same name.

We'd need to split this into 'declare method, have setter' and 'declare setter, have method' in order to have an obvious location to make the complaint. For 'declare static method, have setter' we have line 2171; for 'declare instance method, have setter' we have line 1325; for 'declare static setter, have method' we have line 1492; for 'declare instance setter, have instance method' we have the newly added line;  for 'declare instance setter, have static method' the situation would necessarily be 'declare instance setter, declare static method' (because static methods aren't inherited), so that would be a simple name clash, covered by line 342.

If we can agree on this then we only need to add that single new line.

**Comment by lrhn** [comment]
It's not enough to have "declare methods, have setter" and "declare setter, have method" as cases, we also need to disallow "have setter and method" where both are inherited from different interfaces.
That goes for the other rules as well.

I would go for:

The *base name* of a Dart declaration name is the name itself for getter and method names, the name without the trailing `=` for setter names, and the name without a prefix `ClassName.` for constructors (the unnamed constructor has the empty base name).

* Is's an error if any classs declares two members with the same base name, unless one is a getter and the other is a setter, and either both are static or both are instance members.
* It's an error if a class declares a setter or getter if any of its super interfaces has a method with the same base name.
* It's an error if a class declares a method if any of its super interfaces has a setter or getter with the same base name.
* It's an error if a class super-interface has a method and another super-interface of the same class has a getter or setter with the same base name.
* It's an error if any class declares a static member and any of its super-interfaces contains a member with the same base name.
* (Not sure if) It's an error if a class declares a constructor and any of its super interfaces has a member with the same base name.

(As usual, it gets complicated because we can't actually speak of the *class*, or its interface, before we have checked that the declaration is well-formed and consistent, so we talk about *declarations* being incompatible with each other or with well-formed super-interfaces).
I believe we do currently allow constructors with the same name as inherited members.

**Comment by eernstg** [comment]
I've uploaded a spec update as described in https://dart-review.googlesource.com/c/sdk/+/54410.

**Comment by eernstg** [comment]
[Said [CL](https://dart-review.googlesource.com/c/sdk/+/54410) does not take [this comment](https://github.com/dart-lang/sdk/issues/33077#issuecomment-387759128) into account.]

I'll try to use these ideas (but I'll soon leave for one of the numerous Danish spring time holidays, so I won't be able to update the CL today ;-). I'm sure we can fiddle around with these rules a lot in order to find an optimal expression of the intent (that I don't really think we disagree about). A couple of comments come to mind:

The treatment of conflicts in superinterfaces is targeted by [interface-conflicts.md](https://dart-review.googlesource.com/c/sdk/+/40080), and I believe it may be useful to treat these errors as possible events during the construction of the interface of a class (which is a step that I'd like the spec to have explicitly, soon).

About the whole 'base name' concept: I agree that we may be able to combine some rules using this concept.

However, there is a certain amount of conflict in the fact that we currently specify errors about declarations of setters in the section about setters, and similarly for getters. So we'd ideally have 'It's an error if a class declares a setter or getter' in both sections..

For 'declares two members with the same base name', we would already have a simpler rule (line 342) saying that a plain name clash is an error. For the 'both are static or both are instance' part, this covers the case where both declarations occur in the same class, so we would still need rules for 'declares static setter, has instance getter' and 'declares static getter, has instance setter' somewhere.

For 'error if a class declares a method if any of its super interfaces has a setter or getter with the same base name' we might simply want to say '.. declares a method if it has a setter or getter with the same base name'. This would make it tempting to unify this bullet with bullet 1.  ;-)

In any case, I'll take a look and see if all these ideas can be combined into something which is overall simpler and more obvious than that which is on the table aleady (in the spec in and in the CL that I uploaded).

**Comment by leafpetersen** [comment]
I'm a little unsure about the desired behavior on the various combinations of static/instance conflicts. 

> It's an error if a class super-interface has a method and another super-interface of the same class has a getter or setter with the same base name.

Are you referring to static + instance here, or just instance?  If the former, why?

More generally:

- We want to allow a superclass static member to coexist with a subclass instance member
  - Certainly of the same kind (i.e. method/method)
  - Any reason not to allow it of a different kind (I think Lasse's rules forbid this)?
- We (apparently) don't want to allow a superclass instance member to coexist with a subclass static member
  - Whether matching or not?
  - Why do we not want this?  
    - Because adding the superclass instance member is already a breaking change?
    - Because it makes the resolution ambiguous (did I mean the instance member or the static member?)
- We (apparently) don't want to allow an instance member and a static member to be declared in the same class
  - regardless of kind
  - why not?
    - Because it makes the resolution ambiguous again?

**Comment by eernstg** [comment]
Here's a correlation between these issues and the [CL that I mentioned above](https://dart-review.googlesource.com/c/sdk/+/54410):

> - We want to allow a superclass static member to coexist with a subclass instance member
>   - Certainly of the same kind (i.e. method/method)
>   - Any reason not to allow it of a different kind (I think Lasse's rules forbid this)?

The CL (and the current rules) allow this, all kinds.

> - We (apparently) don't want to allow a superclass instance member to coexist with a subclass static member
>   - Whether matching or not?
>   - Why do we not want this?
>     - Because adding the superclass instance member is already a breaking change?
>     - Because it makes the resolution ambiguous (did I mean the instance member or the static member?)

I believe the motivation for having these conflicts (Dart 1: warnings) was originally that these mixed setups are too error-prone: `x++` in the body of a method in class `C` might refer to a static setter and an instance getter when `C` 'declares' the setter and 'has' the getter (line 1492), and that's unlikely to be a meaningful semantics for this expression.

When the kinds match it is a regular name clash (same class) or a "shadowing" relationship, e.g., when `C` declares a static method `foo` and also inherits an instance method `foo`. We could allow this kind of shadowing and resolve the ambiguity ("nearest declaration wins", presumably), but I think it's too confusing to be a good idea.

> - We (apparently) don't want to allow an instance member and a static member to be declared in the same class
>   - regardless of kind
>   - why not?
>     - Because it makes the resolution ambiguous again?

The spec does make a distinction between the static scope and the instance scope of a class, but I'd actually prefer to merge the two scopes exactly because it would then be a simple name clash (rather than a special rule that applies exactly for this situation with two nested scopes, and not for any other pair of nested scopes).

With that, I believe that the arguments relying on 'declares' and 'has' apply directly to the special case where the two declarations are in the same class.

This all matches up with the CL I mentioned before. Maybe we could land that, and then I'll try to use the 'base name' idea to make the whole thing simpler, in a separate CL?

**Comment by eernstg** [comment]
The [CL](https://dart-review.googlesource.com/c/sdk/+/54410) has now been landed. Closing.

**Comment by lrhn** [comment]
> - We want to allow a superclass static member to coexist with a subclass instance member
>  - Certainly of the same kind (i.e. method/method)
>  - Any reason not to allow it of a different kind (I think Lasse's rules forbid this)?

No reason at all - they *cannot* be the same kind since the "static bit" is part of the kind, and the two should be completely decoupled.

>- We (apparently) don't want to allow a superclass instance member to coexist with a subclass static >member
>  - Whether matching or not?
>  - Why do we not want this?  

If a superclass has an instance member and a subclass has a static member of the same name, then that static member blocks you from overriding the instance member. It's also confusing for users that the same class has two `foo` members, one inherited instance member and one declare static member, both showing up in documentation.

>    - Because adding the superclass instance member is already a breaking change?

It may be, yes

>    - Because it makes the resolution ambiguous (did I mean the instance member or the static member?)

No, that part is clear (but maybe not to users).

>- We (apparently) don't want to allow an instance member and a static member to be declared in the >same class
>  - regardless of kind
>  - why not?
>    - Because it makes the resolution ambiguous again?

That actually does make the resolution ambiguous in the *lexical* scope. We'd have to give some sort of priority to either the instance member or the static member, so when you write `foo`, it picks the one that you want. We'd likely want to make it prefer the instance member inside instance methods and the static member inside static members (or we'll think that's too complex and confusing).

**Comment by leafpetersen** [comment]
Ok, SGTM.  @eernstg is this reflected in your last spec update or do we have more to do here?

**Comment by eernstg** [comment]
I think it is covered by the updated that reduces these member conflicts to a 4 element list (patchset 5 of [this CL](https://dart-review.googlesource.com/c/sdk/+/56800)): There is no rule that matches the case where _C_ declares an instance member and a superclass declares a static member; rule 4 in the list prevents the declaration of a static member with basename `n` when the class has an instance member with basename `n`, so the issues with

> If a superclass has ...

will not arise. With 

>> don't want to allow an instance member and a static member to be declared in the same class ...
>
> That actually does make the resolution ambiguous in the lexical scope. We'd have to
> give some sort of priority to either the instance member or the static member

There is a static scope and an instance scope, and the latter has the former as its parent, so in that sense we have a clear semantics already. But I think that it's a really tricky kind of nesting, and we should protect users from getting confused because an instance member is invisible in a static method (so we get a global name instead, or an "undefined identifier" error); or a static member is shadowed by an instance member in an instance method; or even that we allow the instance method and the static method with the same name to coexist between the same pair of braces.

That's all a big mess, so I strongly prefer the existing approach where we make all these name clashes errors rather than letting them shadow each other (or a revised scope structure where we don't have a static scope and an instance scope nested inside each other at all).

In this area, nothing changes with the new 4-element-list formulation of the rules, but compared to the old rules (before this CL) we've made the change that a constructor `C.n` conflicts with a static setter `n=` in the same class.
