### ISSUE TITLE
Annotations are not inherited from mixins with --preview-dart-2

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33099]
This code prints `true` without `--preview-dart-2` and prints `false` with it.
@bwilkerson 

```dart
import 'dart:mirrors';

const _FailingTest failingTest = const _FailingTest();

class _FailingTest {
  const _FailingTest();
}

class MyTest {
  @failingTest
  void foo() {}
}

class MyTest2 extends Object with MyTest {}

main() {
  ClassMirror classMirror = reflectClass(MyTest2);
  classMirror.instanceMembers
      .forEach((Symbol symbol, MethodMirror memberMirror) {
    if (memberMirror.simpleName == #foo) {
      print(memberMirror);
      print(_hasFailingTestAnnotation(memberMirror));
    }
  });
}

bool _hasFailingTestAnnotation(MethodMirror method) {
  var r = _hasAnnotationInstance(method, failingTest);
  print('[_hasFailingTestAnnotation] $method $r');
  return r;
}

bool _hasAnnotationInstance(DeclarationMirror declaration, instance) =>
    declaration.metadata.any((InstanceMirror annotation) {
      print('annotation: ${annotation.reflectee}');
      return identical(annotation.reflectee, instance);
    });
```

**Comment by kmillikin** [comment]
This was reverted because it broke some Flutter tests.  I am investigating.

**Comment by kmillikin** [comment]
This same code was used to generate noSuchMethod forwarders, and so the change to always copy annotations caused nSM forwarders to have the same annotations as the method they represented (they should not, according to the language team).  This revealed a bug: the nSM forwarders would be marked external if the method they represented was (but they are not external).  This was relatively benign until they had a corresponding `@ExternalName` annotation, which caused a crash.

We will fix the bugs in nSM forwarders and then reland the fix for this issue.

**Comment by kmillikin** [comment]
@stefantsov will implement removing annotations (including parameter annotations) from NSM forwarders (and clearing the external bit).  He'll land a fix for this issue at the same time.
