### ISSUE TITLE
Make `mixin` and `interface` a builtin identifier or reserved word

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33113]
We should reserve these now for future compatibility (i.e. with the upcoming mixin feature).

Is builtin identifier enough, or do we need this to be a reserve word?

cc @lrhn @eernstg 

Update: Make them builtin identifiers.
- [ ] Analyzer issue: https://github.com/dart-lang/sdk/issues/33131
- [ ] Front end issue: https://github.com/dart-lang/sdk/issues/33132
- [x] Spec issue: https://github.com/dart-lang/sdk/issues/33133

**Comment by lrhn** [comment]
I believe being a built-in identifier is enough. The words are only expected at the beginning of a top-level declaration (likely not even preceded by `abstract`), so preventing them from being types or prefixes will allow us to recognize their meaning immediately.

Making them reserved words is a much more breaking change, since it would break existing code that uses the names as variables or class members. Such code exists.

@peter-ahe-google

**Comment by leafpetersen** [comment]
Concretely (for reference) all of the following will become errors (and similarly for `interface`):

```dart
import "dart:core" as mixin;

typedef mixin(x);

class mixin {}

class Foo<mixin> {}
```
