### ISSUE TITLE
The CQ analyzer bot should test for hint violations

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#33116]
It appears that the analyzer bot used in the commit queue does not catch issues related to hint and lint violations (see https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/analyzer-analysis-server-linux/156 as an example). This can allow a CL to be committed that will then cause some of the other bots to fail. While the CQ bot can't reasonably test everything, this seems like a reasonable test to add given that it will affect all of the platforms.

**Comment by stereotype441** [comment]
The root cause of the problem is that due to #28649, we currently disable analysis tests for all packages in strong mode: https://github.com/dart-lang/sdk/blob/137942aca55ac34bf08286f70f9199e137cef054/pkg/pkg.status#L172-L174

However, currently the analyzer try bot *only* attempts to do analysis in strong mode.  As a result, all analysis of the `pkg` subdirectory is skipped.

I'm looking into whether we can safely remove the `Skip` shown above.  If we can, I'll do that.  If we can't, I'll temporarily update the try bot to analyze `pkg` in non-strong mode.

**Comment by stereotype441** [comment]
It is safe to remove the `Skip`.  Fix out for review: https://dart-review.googlesource.com/c/sdk/+/55302
