### ISSUE TITLE
No error when run dart class with incorrect instantiation to bound

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33184]
Dart SDK Version: 2.0.0-dev-55.0
OS: Windows 10

Dart 2.0 [Instantiate To Bound](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md) Spec reads:

> It is a compile-time error if a formal parameter bound B contains a type T on the form qualified and T denotes a generic class G (that is, T is a raw type), unless every formal type parameter of G has a simple bound.
> 
> In short, type arguments on bounds can only be omitted if they themselves have simple bounds. 

The following simple code example tries to make instantiation to bound with non-simple bounded class (and See also examples from the `Background `section). T of D does not have a simple bound, so raw D cannot be a bound, so it should throw compile error:
``` dart
class D<T extends Comparable<T>> {}
class E<T extends D> {}
main() {
  print(new E());
}
```
Indeed, dartanalyzer throws expected error here:
```
$> dartanalyzer --preview-dart-2 test.dart
Analyzing test.dart...
  error - Type parameter bound types must be instantiated at test.dart:2:19 - strong_mode_not_instantiated_bound
1 error found.
```
But when I run this test with dart, no error happens here:
```
$> dart --preview-dart-2 test.dart
Instance of 'E<D<Comparable<dynamic>>>
```
I believe this is incorrect and error should be thrown here.

**Comment by eernstg** [comment]
Right, the raw type `D` used as a bound prevents instantiate-to-bound on `E` because the generic class `D` doesn't have simple bounds on all its type parameters.

It may be the case that the analyzer is too strict (it sounds like it will not accept any raw types as bounds, but it's only the ones that do not themselves have simple bounds that cannot be used raw as bounds), but that doesn't change the fact that `dart --preview-dart-2 ..` should reject the program.

**Comment by iarkh** [comment]
I observe similar things with typedefs, so is this a same issue or we should file another bug instead?

Sample code is:
``` dart
typedef F<X> = X Function();
typedef G<X extends F> = X Function();
main() {}
```
Sample output is:
```
$>dart --version
Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "windows_x64"

$>dartanalyzer test.dart
Analyzing test.dart...
  error - Type parameter bound types must be instantiated at test.dart:2:21 - strong_mode_not_instantiated_bound
1 error found.

$>dart test.dart

$>
```

**Comment by eernstg** [comment]
I believe it's a good idea to create separate issues when there's a good chance that the bug fix would involve different locations in the tools. It is surely also a good idea to include a reference to one from the other if it is known that they are similar.

However, the `typedef` example shows the opposite problem: `dartanalyzer` rejects the raw type `F` just because it is raw, and it should actually detect that `F` has simple bounds and hence it can be raw. It is likely that the VM does not yet implement the checks at all, so it's lucky to get the correct behavior in this case. ;-)

**Comment by iarkh** [comment]
OK, I've just created a new issue: #33625.

**Comment by stefantsov** [comment]
I remember fixing it some time ago.  Sorry I didn't keep track of this particular GitHub issue.

At current `master` branch when the example program from the original message is run, `dart` reports the following (note that `--preview-dart-2` is not needed, because it's on by default now):

```
$ out/ReleaseX64/dart /tmp/foo.dart
file:///tmp/foo.dart:3:9: Error: Generic type 'D' can't be used without type arguments in a type variable bound.
Try providing type arguments to 'D' here.
class E<T extends D> {}
        ^
```
