### ISSUE TITLE
PropertySet compiled incorrectly in string interpolation

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#33195]
```dart
class Broken {
  int index = 0;
  String broken() => 'X${++index}';
}

main() {
  print(new Broken().broken());
}
```
Dart VM with --preview-dart-2 should print "X1".  Prints "Xnull".

I think we need to have the string interpolation with at least two parts to trigger it.

**Comment by mraleph** [comment]
The bug is caused by how we implement temporaries in Kernel-to-IL layer: we simply reserve a slot on the stack that is filled with `null` and then replace the value using `StoreLocal`:

```
    t1 <- LoadLocal(:temp0 @-4)
    t2 <- Constant(#1)
    t3 <- Constant(#null)                       // reserve the space <--\
    t4 <- LoadLocal(this @2)                                            |
    PushArgument(t4)                                                    |
    t4 <- LoadLocal(this @2)                                            |
    PushArgument(t4)                                                    |
    t4 <- InstanceCall:12( get:index<0>, t4)                            |
    PushArgument(t4)                                                    |
    t4 <- Constant(#1)                                                  |
    PushArgument(t4)                                                    |
    t4 <- InstanceCall:14( +<0>, t4, t4)                                |
    t4 <- StoreLocal(:temp3 @-7, t4)            // fill the space ------/
    PushArgument(t4)
    InstanceCall:16( set:index<0>, t4, t4)
    StoreIndexed(t1, t2, t3)                    // Note: t3->definition() is Constant(#null)
```

However this means that in some places in the unoptimized graph we end up with instructions that have constant operands, which are not actually constant (because the value on the stack can be replaced).

Like for example the `StoreIndexed(...)` above. 

The template for `StoreIndexed` would optimize for constant value on the right-hand side (not knowing that it is not constant) - which means it would end up storing `null`.

**Comment by mraleph** [comment]
The fix is out for review: https://dart-review.googlesource.com/c/sdk/+/56112
