### ISSUE TITLE
Wrong static type for sync return in a FutureOr method

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33212]
On 2.0.0-dev.56.0
running `dart --preview-dart-2 main.dart`

Expected: `Future<int>`
Actual: `Future<dynamic>`

This caused a runtime error in build_runner

```dart
import 'dart:async';

FutureOr<int> getInt() async => 42;

main() {
  print(getInt().runtimeType);
}
```

**Comment by kevmoo** [comment]
CC @leafpetersen

**Comment by eernstg** [comment]
We may need to amend the specification, because it says nothing about the actual type argument of the future returned from an `async` function:
```
If f is marked async (9), then a fresh instance (10.6.1) o implementing
the built-in class Future is associated with the invocation. Then the body
of f is executed until it either suspends or completes, at which point o is
returned.
```
Given that a `Future<dynamic>` will not work in Dart 2, and given that it makes sense to use exactly the type argument `T` for the returned future in a function with actual return type `Future<T>`, I believe that we should specify that.

**Comment by crelier** [comment]
This is most probably a duplicate of https://github.com/dart-lang/sdk/issues/33196

**Comment by kevmoo** [comment]
Looks like it!

Duplicate of #33196
