### ISSUE TITLE
runtimeType surprise

### ISSUE THREAD

**Issue by sorenbronsted** [dart-lang/sdk#33232]
### Dart version:
Dart VM version: 1.24.3 (Mon Dec 18 16:57:48 2017) on "linux_x64"

I have created the following on dartpad:
https://gist.github.com/sorenbronsted/4a547ab30483bd75b982023aeb86042a

### Result:
ul
HtmlElement
UL
false
A

I seems that I can not rely on the runtimeType for elements in library dart:html, but on the other hand I can rely on my own classes. I can't see why there should be any difference.

**Comment by lrhn** [comment]
Your code contains an error. The line `print(l.runtimeType is UListElement);` should be `print(l is UListElement);`. If you make that change, then it *does* print `true`, and (magically) the `l.runtimeType` changes to `UListElement` too.

HTML DOM element classes are a little surprising in that the classes only exist if you need them. To reduce the deployment size of your application, the Dart2JS compiler only includes the classes that you actually use. In this example, the `UListElement` class wasn't considered used because the expression `l.runtimeType is UListElement` was determined to be false at compile-time (a `Type` object is never a `UListElement` object).

**Comment by sorenbronsted** [comment]
Ok Thanks. I have made another gist :-) 
 https://gist.github.com/sorenbronsted/d2414e32f0cd2936d19d199fa3653861

**Comment by natebosch** [comment]
Current output is:

```
ul
f1
div
f2
```

As far as I can tell that is the expected output.

**Comment by sigmundch** [comment]
It might not be relevant to your use case, but I want to take the opportunity to note that we normally don't recommend using `.runtimeType` to distinguish between objects, and in general we discourage using `.runtimeType` if it's possible to do things differently.

The reason is that .runtimeType has a big cost in the generated code from dart2js, even if you enable aggressive optimizations levels like `-O3`. Using it in a few places may force the dart2js compiler to include type information for most types at runtime, even when you only intend to use it on a few of them.
