### ISSUE TITLE
Kernel const evaluation must use platform integers

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33285]
See https://github.com/dart-lang/sdk/issues/33282 for context.  

The semantics of const object evaluation depends on the platform.  On platforms that compile to JS, literals are interpreted as doubles, and integer operations are performed using double operations.

This issue is to verify that no const evaluation is done using the wrong semantics, since in the short term dart2js and ddc will be relying on receiving faithful representations of the original program literals in order to issue errors.

cc @rakudrama @jmesserly

**Comment by kmillikin** [comment]
We don't do any const evaluation using the wrong semantics because we don't do any const evaluation.  Eventually we should, and we're definitely aware that the different platforms have different number semantics.

**Comment by jmesserly** [comment]
yeah, FWIW, dev_compiler overrides kernel's ConstantEvaluator class, in particular evaluateBinaryNumericOperation and canonicalize, so we can handle JS number semantics. It's not the cleanest approach but it's working alright. (we needed to override it anyway to handle "outline summaries". They make constant fields look like their values are `null`).

**Comment by mkustermann** [comment]
@jmesserly @leafpetersen 

The kernel2kernel constant evaluator in `package:kernel` was written by me. Currently we only use it in our AOT compilation in the VM (and hopefully in the JIT in the non too-distant future as well).

The front-end itself doesn't use it (that was what @kmillikin is referring to), so we run it as an extra transformation afterwards. It surfaces also compile-time errors which the front-end didn't catch (since it doesn't do constant evaluation atm afaik).

If you would want to restructure the `package:kernel/transformations/constants.dart` to make the interface nicer for the `package:dev_compiler`, you are welcome to send a CL to me!
