### ISSUE TITLE
analyzer / cfe inconsistency on inferring dynamic vs Object

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#33324]
The following fails statically with ddk (`Error: The getter 'length' isn't defined for the class 'dart.core::Object'`), but passes with ddc.  If I print `l.runtimeType`, I get `List<dynamic>` with ddc and `List<Object>` with ddk.  

```
void main() {
  Function f = (x) => x;
  var l = ["hello"].map(f).toList();
  l.add(42);
  print(l.first.length);
}
```

Filing on language to determine correct behavior.

**Comment by leafpetersen** [comment]
Another example: this code

```dart
void main() {
  dynamic f;
  List x;
  var a = x.map(f);
  int b = a;
}
```

Produces an error indicating that `a` is being inferred as `Iterable<Object>`.   I suspect that the greatest closure computation is being done filling in with `Object` instead of `dynamic`.  For this example, the downwards context on `f` is `dynamic -> ?` so the choice of what to fill in for `?` in the greatest closure computation would result in `Iterable<Object>` or `Iterable<dynamic>` for `Object`/`dynamic` respectively.

**Comment by kmillikin** [comment]
This issue breaks dart2js on Google's tests.  A workaround has been committed but it will affect other users so I'm giving it a high priority to figure out what's going on, how easy it is to change, and what other effects that will have.

**Comment by stefantsov** [comment]
A bit of context for the fix.  Absence of handling of `defaultType` in some Kernel visitors resulted in some mistakes in distinguishing between omitted bounds and `Object` provided explicitly for the bounds.  In its turn, it resulted in more type variables being marked as having explicit `Object` as their bound.  It was exactly the case for the examples above: `Object` was provided because it was assumed the explicit bound of the type variable provided by the programmer.

**Comment by keertip** [comment]
Thanks for the fix! Came across another test failure due to this.
