### ISSUE TITLE
Implicit generic type argument interpreted as type bound instead of dynamic

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#33334]
Consider the following simplified code excerpt from [Language Tour: Restricting the parameterized type](https://www.dartlang.org/guides/language/language-tour#restricting-the-parameterized-type):

```dart
class SomeBaseClass {}
class Foo<T extends SomeBaseClass> { String toString() => 'Foo<$T>'; }
main() => print(new Foo());
```

This used to print
- `Foo<dynamic>`

but it now prints

- `Foo<SomeBaseClass>`.

Has the default for bounded generic type parameters changed?

I see this behavior under both of these environments:

- **Dart VM version: 2.0.0-dev.60.0** on "macos_x64"
- **DartPad**: https://dartpad.dartlang.org/d54353f704d7fca84d2a553ecf58c46f (which contains the full code excerpt from [Language Tour: Restricting the parameterized type](https://www.dartlang.org/guides/language/language-tour#restricting-the-parameterized-type)).

cc @kwalrath @munificent @kevmoo

**Comment by eernstg** [comment]
Yes, Dart 2 uses [instantiate-to-bound](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md) to make this choice. The basic idea is that inference will use the bound itself when no constraints apply (using `dynamic` when no bound has been declared), so `List` means `List<dynamic>` and `Foo` means `Foo<SomeBaseClass>`.

When the given bound is an F-bound we need to handle the cyclic dependency:
```dart
class C<X extends C<X>> {}

C c; // What should this mean?
```
We could express the least upper bound of all types of the form `C<T>` as an infinite `C<C<C<...>>>>`, but we've introduced developer-controlled finite unfoldings instead: 'Super-bounded types'. They are described in the new section 'Super-bounded Types' in the language specification. Until now that concept has been specified in the feature specification [super-bounded-types.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/super-bounded-types.md); that document is now background material (because the topic is now part of [the language specification](https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex)), but it may still be a useful read because it contains a bunch of motivational/explanatory material written during the development of this concept.

The basic idea behind a super-bounded type is that it is a controlled way to violate the declared bounds, and in general it is only possible to do this using a top type (such as `dynamic` or `Object`).
 
So the raw `C` above actually means `C<C<dynamic>>`, and the type argument `dynamic` is allowed even though it violates the bound declared for `X` in `C`, which makes that type super-bounded.

Super-bounded types can only be used descriptively (that is, as type annotations and similar "descriptive" situations where we express how some existing object should be structured) and not prescriptively (where we are creating a new object). I would expect super-bounded types to be out of scope entirely for the language tour, and that should be easy to achieve if there are no F-bounds (so we never need any super-bounded types).

**Comment by chalin** [comment]
Erik: thank you for the nice summary, and the link to the language spec and background reading!

I had scanned the 2-dev [SDK changelog](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md) entries but found nothing relevant. It seems that the most recent mention of "instantiate-to-bound" appears in [1.22.0 - 2017-02-14](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#1220---2017-02-14) via strong mode. Also, it seems that the 1.22 implementation was partial:

> Strong mode's initial behavior sometimes produced surprising, unintended results. For 1.22, we take a simpler approach and then report an error if a good default type argument can't be found.

Is the implementation complete now?

There probably should be a 2-dev changelog entry mentioning the recent change in semantics (if only to mention that the semantics are now matching the language spec)? WDYT?

**Comment by chalin** [comment]
@kwalrath, @kevmoo - actually, maybe we should mention this in the [migration guide](https://www.dartlang.org/dart-2#migrating-yo) or the [Fixing Common Type Problems](https://www.dartlang.org/guides/language/sound-problems) page?

**Comment by kwalrath** [comment]
This seems very detailed compared to what's currently in the [migration guide](https://www.dartlang.org/dart-2#migrating-yo), but (on the other hand) does it have a predictable error message like most of what's in the [Fixing Common Type Problems](https://www.dartlang.org/guides/language/sound-problems) page?

How are most people going to encounter this?

**Comment by chalin** [comment]
> This seems very detailed compared to what's currently in the migration guide, 

Agreed.

> does it have a predictable error message like most of what's in the Fixing Common Type Problems page?

Not that I can think of.

Actually, giving this more thought, this probably isn't a change that most devs will notice. I just thought that it should be listed _somewhere_.

WAI, so closing this issue.

**Comment by eernstg** [comment]
I can see that this issue is closed, but it still seems to be the relevant place to add the following remark:

> Actually, giving this more thought, this probably isn't a change that most devs will notice.

I think this is true, because they will typically just experience that the raw types they already have or that they write into new code "are working" (so maybe they won't notice that anything has changed at all around raw types).

But that only goes skin-deep&mdash;they may experience new compile-time errors elsewhere (compared to Dart 1):

```dart
class C<X extends num> {
  X x;
}

main() {
  C c = ...;
  // The following used to rely on `c.x` having type `dynamic`, it is now an error.
  c.x.whatever(42);
  // This error may be confusing because it "just" tries to use a `num` as an `int`,
  // and the developer may not realize that `c.x` used to have type `dynamic`, so a
  // common reaction might be "How on earth did this type change from `int` to `num`?!"
  if (c.x.isEven) {...}
}
```

So the remaining question is whether it is relevant to consider developers coming straight from Dart 1, or we may assume that _everybody_ has already adjusted their code in a number of ways in order to make it strong mode compliant. And even in that case we did change instantiate-to-bound such that strong mode never did exactly the same thing as that which is now specified for Dart 2 (and, I believe, implemented by all tools except maybe for a few bugs in corner cases).

All in all, this looks like a reasonable candidate for being mentioned on the [Fixing common type problems](https://www.dartlang.org/guides/language/sound-problems) page.

**Comment by chalin** [comment]
> All in all, this looks like a reasonable candidate for being mentioned on the Fixing common type problems page.

Thanks for the example! SGTM: https://github.com/dart-lang/site-www/issues/914
