### ISSUE TITLE
Don't Constant-fold the negative sign in -2^63 in Kernel

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#33351]
Work items

- [x] Revert fix for #31770, i.e. always create a `unary-` node
- [x] Fix for DDK to interpret value as uint64
- [x] Add configuration to CFE for web ints
- [x] Add parse error for web int literals that cannot be represented exactly
- [x] Use this configuration from dart2js
- [x] Use this configuration from DDK
- [ ] Ensure analyser devc also generates an error for int literals that cannot be represented exactly
- [x] Document `IntLiteral.value` as holding a uint64 value
- [ ] (Optional) Add configuration for portability warning

----
As per the discussion here: https://github.com/dart-lang/sdk/issues/33282 
Dart2js will treat ints as *unsigned* int64 and then convert to a platform int. I have implemented this but we have noticed that Kernel is doing some constant folding of the negation sign. Consider the following program:

    void main() {
      int x = -3;
      int y = -9223372036854775808;
    }

This results in the following kernel:

    static method main() → void {
      core::int x = 3.unary-();
      core::int y = -9223372036854775808;
    }

As you can see, in the case of the literal "3" (and really any value through -9223372036854775807), we have the value 3 and then the unary negation operator is assigned to it. However, in the case of -9223372036854775808, there is no addition of the unary negation operator. This is problematic because dart2js then has no way to distinguish between whether the user wrote 0x8000000000000000 (which would be positive in JS) and whether the user actually wrote -9223372036854775808. 

We need a way of knowing which the user originally wrote.
(cc @rakudrama for FYI)

**Comment by rakudrama** [comment]
I think it would be adequate to leave the `unary-` node in place, since for the VM

    -(-9223372036854775808) = -9223372036854775808

**Comment by kmillikin** [comment]
This was intentional (#31770).

What I think we should do is represent integer literals as platform integers in Kernel, but that requires us to be provided a target-specific implementation of `int.tryParse`.

**Comment by rakudrama** [comment]
I think the fix for #31770 was, in hindsight, the wrong fix - we have since nailed down the spec that 0x8000000000000000 is positive when compiled to JavaScript.

If we represent integer literals as platform integers, they need a compile-time type other than `int`.
`IntLiteral.value` would probably be `BigInt`, or typed to allow BigInt for out-of-int values, (e.g. dynamic).

If the purpose of IntLiteral is to represent integer literals from some source code, we can document that `IntLiteral.value` is to be treated as unsigned, keep the unary minus, and fix DDK to read the intValue as unsigned.

If the purpose of IntLiteral is to represent any integer value on the target (e.g. the result of constant folding), then we need a non-int type, and it is possible that BigInt is not sufficient (e.g. constant fold + in JavaScript to get infinity, but we would also decline to constant-fold in this case.)

If kernel/ast.dart is not part of the Dart 2.0 API, we can go with one and change it later.

/cc @vsmenon I believe DDK has a bug of interpreting 0x8000000000000000 as negative.

**Comment by rakudrama** [comment]
Work items

- [ ] Document `IntLiteral.value` as holding a uint64 value
- [ ] Revert fix for #31770, i.e. always create a `unary-` node
- [ ] Fix for DDK to interpret value as uint64
- [ ] Add configuration to CFE for web ints
- [ ] Add parse error for web int literals that cannot be represented exactly
- [ ] Ensure analyser devc also generates an error for int literals that cannot be represented exactly
- [ ] (Optional) Add configuration for portability warning

**Comment by dgrove** [comment]
Is this on target for Dart2Stable?

**Comment by lrhn** [comment]
Still gives the wrong result:
```dart
Expect.equals(-0x8000000000000000, int.tryParse("-0x8000000000000000"), "-minint");
```
fails with
```
Expect.equals(expected: <9223372036854776000>, actual: <-9223372036854776000>, '-minint') fails.
```
(see `corelib_2/int_try_parse_test.dart` when I land that line).

**Comment by jensjoha** [comment]
Am I understanding this correctly:

* You want to keep the unary- on `-9223372036854775808` because you want to be able to distinguish `0x8000000000000000` from `-9223372036854775808` because the former would be positive in Javascript and the later would be negative in Javascript.
* You want to issue an error on integers that cannot be represented exactly as for instance, say, `0x8000000000000000` and `-9223372036854775808`

?

From the chrome console:
```
> 0x8000000000000000
9223372036854776000
> -0x8000000000000000
-9223372036854776000
> -9223372036854775808
-9223372036854776000
> 9223372036854775808
9223372036854776000
```

It seems to me that adding the error makes the first part obsolete, or am I missing something?

**Comment by jensjoha** [comment]
Oh, and also, btw, the current thing added to dart2js to issue a warning (134e00fd73dd01a34d8ceed83d49d620ab7ed346) for this file:
```
main() {
  print(-0x8000000000000000);
  print(0x8000000000000000);
  print(-9223372036854775808);
  print(-9223372036854775807);
}
```

gives me 1 warning: `e integer literal 9223372036854775807 cannot be represented exactly in JavaScript and will be rounded to 9223372036854775808.`.

And the output (run via test.py and d8 in this case) I get this:
```
-9223372036854776000
9223372036854776000
-9223372036854776000
-9223372036854776000
```
so not really `9223372036854775808`...

**Comment by rakudrama** [comment]
1. `9223372036854775808` can be represented exactly, as can any other power of 2 up to about 2^1023

2. Be careful interpreting the JavaScript console window printout. JavaScript unashamedly uses doubles. There are many possible digit strings that parse to the same double value, so JavaScript chooses the formatted one as the one with the fewest nonzero digits. That is not necessarily the most honest string, but is it is a string that when converted back to double, has the same double bits, so it is not exactly a lie.  In this range adjacent double values differ by 1024, so 922xxx6000 is a 'cleaner' but equivalent alternative to 922xxx5808.

3. The implication of the above is that all printed values in diagnostics must be BigInt values, not doubles, since the VM could in the future reasonably also do this kind of 'cleaner' output.

4. The code from (134e00fd73dd01a34d8ceed83d49d620ab7ed346) should be moved to the parser so that we get warnings from code that is parsed, rather than code that is compiled. At that time fix it to not print via a double value.

**Comment by jensjoha** [comment]
I won't pretend to understand how it can both be exact and not print the right thing, but I'll accept it. I have a CL out with the checking code from 134e00fd73dd01a34d8ceed83d49d620ab7ed346 moved into fasta.

**Comment by jmesserly** [comment]
https://github.com/dart-lang/sdk/issues/33287 is tracking the DDC issue. It sounds like the Kernel/CFE/dart2js side of things is done, feel free to reopen if I misunderstood that.
