### ISSUE TITLE
Support auto fix function on dartanalyzer command

### ISSUE THREAD

**Issue by moznion** [dart-lang/sdk#33358]
- Dart SDK Version: `Dart VM version: 2.0.0-dev.59.0 (Tue May 29 22:11:36 2018 +0200) on "macos_x64"`
- dartanalyzer Version: `dartanalyzer version 2.0.0-dev.59.0`

ESLint (and other linters) has a function to fix problems automatically.
https://eslint.org/docs/user-guide/command-line-interface#--fix

Could you support such option by `dartanalyzer` command?

**Comment by bwilkerson** [comment]
Whether we would include the functionality in `dartanalyze` or in another command-line tool, yes, we've talked about this for a long time and would love to do so. Unfortunately, this hasn't yet reached a priority where we can allocate resources to working on it.

That said, we do have fix support in the analysis server, the tool behind our IDE integrations. I know that fixes are supported in both IntelliJ and VS Code, but I don't remember whether they're currently supported in other tools. It isn't automatic yet, but I thought I'd mention it in case it helps in the meantime.

**Comment by Daniel-BD** [comment]
Any update on this? :)

**Comment by bwilkerson** [comment]
There are no plans at the moment to include this functionality in `dartanalyze`, but we do have a separate tool named `dartfix` that has support for automatically applying fixes to code. The number of fixes is supports is somewhat limited at the moment, but we do intend to improve the coverage over time. It isn't currently shipped as part of the SDK, but is available as a package on `pub.dev`, which means you can use `pub global activate` and `pub global run` to run it.

I'm going to close this issue because I suspect that `dartfix` is the way we'll provide this functionality going forward.

**Comment by shilangyu** [comment]
For those that are looking for `dartfix` on pub.dev: it has been discontinued and it is now bundled with the SDK under `dart fix`
