### ISSUE TITLE
Immediate delay of async functions

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#33397]
A fairly large number of functions/methods have been getting an initial "await null;" added in order to preserve the pre-sync-async semantics. It might be worth considering some language support for this convention. For example, we could allow a modifier of the form:
```
m() async! {}
```
to mean that a future is created and returned before any of the statements in the body have been executed.

**Comment by lrhn** [comment]
I also expect that these functions were written under the assumption that they had time to do some more setup before the function started, and that is no longer the case.
Future functions will not be written under that assumption, so their code will just be written differently to begin with.

If you really want to wait a microtask, you can always add `await Future.microtask((){});`. (We should make the argument optional on `Future.microtask`).

**Comment by lrhn** [comment]
Adding more kinds of method bodies is a non-goal. That the body of a function behaves differently due to some magical marker is already complicating enough (I see people writing `async` even if they don't use `await`, maybe because they think that's what you are supposed to do when you return a Future).
