### ISSUE TITLE
VM --preview-dart-2 – different behavior with triple-quote strings and newline characters

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33404]
2.0.0-dev.60.0

```dart
main() {
  var value = '''\n
return val;
}''';

  print(value.length);
  print(['-->', value, '<--'].join(''));
}
```

`dart test.dart`
```
14
-->
return val;
}<--
```

`dart --preview-dart-2 test.dart`
```
15
-->

return val;
}<--
```

Very much a regression...

**Comment by kevmoo** [comment]
@mraleph @lrhn – I feel I've chatted w/ one of our about literals lately...

**Comment by kevmoo** [comment]
Just reproduced at 3971e76a92fc5c6522b09c98046c7f52d6ff7b54

**Comment by kevmoo** [comment]
Upon reflection (and given my limited understanding of the nuances here), I feel like the `--preview-dart-2` behavior is *more* correct. Just wanted to raise it to confirm...

**Comment by lrhn** [comment]
It is a fix and a deliberate change.
The Dart 1 spec said:
> If the first line of a multiline string consists solely of the whitespace characters defined by the production WHITESPACE 20.1), possibly prefixed by \, then that line is ignored, including the new line
at its end. 

Since `n` is not WHITESPACE, then `\n` should not be ignored. The VM had a long-standing bug of replacing escapes with characters before determining whether to ignore the first line of the multiline string, something that is not allowed by the spec at all.
Not everyone agreed whether it was a VM bug or a spec bug: https://code.google.com/p/dart/issues/detail?id=23020

The front-end didn't implement this bug, and it implemented the new specification of what a line actually is (Dart 1 didn't say so), so now all platforms agree

We should just disallow the backslashes completely, they serve no purpose, and it's still hard to determine whether a backslash just before the newline is ignored or not. And they make no sense in a raw string.

**Comment by kevmoo** [comment]
Thanks for the details!

**Comment by kevmoo** [comment]
@lrhn – closing out then...I fixed my code so it worked the same in both configurations
