### ISSUE TITLE
Some language_2 tests doesn't reflect the Dart 2 semantics for noSuchMethod forwarders

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#33498]
The tests in question are the following:

* language_2/super_operator_index6_test
* language_2/super_operator_index7_test
* language_2/super_operator_index8_test

They should be rewritten under the assumptions that abstract classes don't get noSuchMethod forwarders and that noSuchMethod forwarders aren't mixed in from the mixins.

**Comment by lrhn** [comment]
Thanks for noticing.

**Comment by stefantsov** [comment]
@lrhn I think there's one more, but I'm not completely sure about this one:

* language_2/super_no_such_method4_test

Marking it with this issue number in the status files for now.

**Comment by eernstg** [comment]
The test `language_2/super_no_such_method4_test.dart` gets complaints about a superinvocation (that there is no `super.foo`) and that's correct (given that nSM forwarders are not provided by `with A`). So the most informative fix might be to make that test a multi-test and mark line as `foo() => super.foo(); //# 0: compile-time error`.

The spec has (section 'Super Invocation'):

```
Let $S_{static}$ be the superclass of the immediately enclosing class.
It is a static type warning if $S_{static}$ does not have an accessible (\ref{privacy})
instance member named $m$.
```

In the context of Dart 2, 'static type warning' has consistently been considered to mean 'compile-time error'. It is currently marked as a hint by the analyzer, so we may need to worry about breakage, but following the spec the way we otherwise read it now, it should be an error.

**Comment by lrhn** [comment]
Agree on super_no_such_method4_test.

Both super_operator_index7_test and super_operator_index8_test are failing because the super-interface doesn't declare the operators, so that's a plain strong-mode error unrelated to `noSuchMethod`.
They should work if I add the operator signatures.
