### ISSUE TITLE
Analyzer doesn't complain when a map's closure doesn't have a return statement

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#33492]
This has no analyzer messages at all but prints "(null, null, null, null)":

```dart
void main() {
  List<int> list = <int>[0, 1, 2, 3];
  print(list.map((int value) { new Object(); }));
}
```

This causes real bugs, e.g.: https://github.com/flutter/flutter/issues/15831

Even adding an explicit type to the `map` method doesn't cause an issue, which is weird; I'd have expected the closure to have a return type inferred and for that to trigger the "method with return type doesn't have a return" message.

**Comment by matanlurey** [comment]
I'm guessing this is because it implicitly returns `null`, which of course, is an `int`?

(I do agree, at minimum, this should be a hint/warning, if not an error)

**Comment by eernstg** [comment]
The context for the invocation of `map` does not constrain the type argument, so the type of the function literal is computed bottom-up to `Null Function(int)`, and for a function with that return type it is allowed to have `return;`, and/or reach the end.

We are currently adjusting exactly in which cases we'd allow `return;` and reaching the end, but return type `Null` seems to come up so frequently, in part because of inference, that we will at least need to be very careful in order to outlaw it; `return;` has always had a well-defined semantics that makes the function return the null object, and so does reaching the end, so in that sense it is perfectly meaningful to allow `Null f() { return; }` and `Null f() {}`.

Given that a value of type `Null` doesn't convey any information it seems meaningful as well to allow code that "doesn't make a choice for what to return", because that choice would be completely forced anyway.

So we are not very likely to be able to make this an error in the language. The main problem could then be claimed to be that it is _non-obvious_ that the function literal `(int value) { new Object(); }` has return type `Null`.

I can see that it is still the case when we change the example to have a context type for that function literal:

```dart
void main() {
  int Function(int) ff = (int value) { new Object(); };
  print(ff.runtimeType); // Prints `(int) => Null` on the VM.
}
```

This is all fine and sound (as long as we don't have non-nullable types), because `ff` will indeed return a value which is ok for the expectation of an `int`.

However, it's possible that we could use a **lint** to catch situations where a function with return type `Null` flows into a target (e.g., is passed as an actual argument for a formal parameter, or assigned to a variable) with declared type `T Function(...)` for some `T` which is not `Null`. The motivation is that it is likely that the caller of said function will be disappointed that the function _always_ returns the null object. Such a lint might also flag something that amounts to `List<int> myInts = <Null>[];` and other cases with a similar structure, so it's not completely obvious how to get it right, but it looks like a useful approach to try to lint it.

**Comment by srawlins** [comment]
With null safety, and an explicit non-nullable type annotation, (like `.map<int>(...)`), analyzer reports:

> error • The body might complete normally, causing 'null' to be returned, but the return type is a potentially non-nullable type. • a.dart:3:35 • body_might_complete_normally

As @eernstg says, Null will be the inferred return type. A linter rule might catch `Iterable.map` without return statements. Something like https://github.com/dart-lang/linter/issues/855.
