### ISSUE TITLE
Dartium has expired

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/sdk#33580]
Latest stable Dart version: 1.24
Dartium refuse to launch: "This version of Dartium has expired".

![screenshot427](https://user-images.githubusercontent.com/5110923/41762696-e0cfd8f2-75fb-11e8-8f6e-7c8db5a806ce.png)

**Comment by sigi77** [comment]
Same here, I reinstalled Dart with Dartium, hoping a new Chromium binary will be installed, which was not the case

**Comment by pinnisi** [comment]
Same here

**Comment by sestegra** [comment]
As this version will stay the latest 1.x version, I suggest to remove this expiration.

**Comment by sestegra** [comment]
See the workaround on Mac
```
$ brew install libfaketime
```
Then create ‘/usr/local/bin/dartium-fake’ script
```
export DYLD_FORCE_FLAT_NAMESPACE=1
export DYLD_INSERT_LIBRARIES=/usr/local/Cellar/libfaketime/0.9.7_1/lib/faketime/libfaketime.1.dylib
export FAKETIME="-15d"
exec "/usr/local/Cellar/dart/1.24.3/Chromium.app/Contents/MacOS/Chromium" "$@“
```
Finally, add execution permission on it.
```
$ chmod +x /usr/local/bin/dartium-fake
```

**Comment by zoechi** [comment]
In TALK-general @dan-conachi mentioned

```sh
export DARTIUM_EXPIRATION_TIME=1577836800; ./chrome-wrapper
```

**Comment by sestegra** [comment]
@passerbyflutter See last comment, it should work on Window as well.

**Comment by Stargator** [comment]
Someone on StackOverflow asked if there was a way to release a "final" version of Dartium that won't expire since Dart 2 doesn't use it and there will no longer be any updates to Dartium.

**Comment by johnpryan** [comment]
On a mac, you can use the `launchctl` command to set this as a system-wide environment variable:

```
launchctl setenv DARTIUM_EXPIRATION_TIME 1577836800
```

**Comment by rafikiadmin** [comment]
Dart is a superb development platform, but if Google is not going to support us...  I would love to see someone from the Dart team respond here.

**Comment by zoechi** [comment]
@rafikiadmin there are easy workarounds. I don't see how this is a serious issue.

**Comment by rafikiadmin** [comment]
Ok. I guess that is true. I guess it is fine.

**Comment by kwalrath** [comment]
In dart-lang/site-www#962 @jooseplall reports being unable to use the workaround on Windows (windows 10). @passerbyflutter can you give us any tips?

**Comment by munkacsimark** [comment]
### Solution on macOS:

0. Chromium app must be in `/usr/local/Cellar/dart/1.24.3/`
1. `$ brew install libfaketime`
2. Create a file `/usr/local/bin/dartium-fake` with following content:
    ```bash
    export DYLD_FORCE_FLAT_NAMESPACE=1
    export DYLD_INSERT_LIBRARIES=/usr/local/Cellar/libfaketime/0.9.7_1/lib/faketime/libfaketime.1.dylib
    export FAKETIME="-15d"
    exec "/usr/local/Cellar/dart/1.24.3/Chromium.app/Contents/MacOS/Chromium" "$@"
    ```
3. `$ chmod +x /usr/local/bin/dartium-fake`
4. You can now run Dartium with `dartium-fake` command

**Comment by Stargator** [comment]
> @rafikiadmin there are easy workarounds. I don't see how this is a serious issue.

Oh okay, so when we attract people to use Dart 1, **right now**. And Dartium doesn't work when they run tests, that's fine.

That's the kind of experience the Dart Team wants for newcomers.

No that's not the best experience for newcomers who hear about Dart 2 and want to try out the stable version of Dart. A fix **should** be released so that, **at the very least**, the first-time experience for potential users is the best it can be.

Otherwise, we can probably forget about growing this community and drop Dart, if we can't work to ensure the tools needed work as expected out of the box.

**Comment by tmst** [comment]
I was happy to overlook the missing Chrome VM. But this is just too much. I refuse to transpile and debug generated code. Looks like it's time for me and Dart, my last great hope for a decent web client development experience, to part ways.

**Comment by zoechi** [comment]
@tmst Have you even tried?
Works quite well already and they are still working on improvements.

**Comment by kwalrath** [comment]
@Stargator You're right, Dart 2.0 isn't released on stable channel yet, but the Flutter SDK uses Dart 2, and of course Dart 2 is what's on dev channel releases of the Dart SDK. We strongly encourage everyone to switch to Dart 2 now, unless you have a really good reason for remaining on Dart 1.x.

 I'll try to make the VM/web download pages more clearly feature downloading Dart 2.

**Comment by kwalrath** [comment]
I've created a PR to make the installation directions clearer (on both www.dartlang.org & webdev.dartlang.org): dart-lang/site-shared#23.

**Comment by kevmoo** [comment]
Closing now that Dart 2.0 is released.

**Comment by dnalbach** [comment]
This is a sad state of affairs for enterprise software projects that can't easily switch from Dart 1.x to Dart 2.x.

**Comment by zoechi** [comment]
@dnalbach do the workarounds not work for you?

**Comment by dnalbach** [comment]
No they do not, and having an expiration warning in a browser used primarily for development and testing that no end user would actually use seems unprofessional to me. Dart is a language, not a framework. This is being treated like a consumer product, but languages are business products, and this is tooling for a business product. We still use JVMs back to 6 for some of our enterprise projects, and Java has very strong legacy support.

Dart was promoted heavily and we bought into it for awhile, but it rapidly became a second-class citizen in Google's world and we have moved away from it as much as possible in new projects because of the way things like this have been handled.

**Comment by Stargator** [comment]
@dnalbach This is an effect of the mindset that people will quickly adopt the latest and greatest.

Sometimes organizations or projects are slow to adapt and it doesn't leave a good impression if one day the build no longer works because of something expired. Then that team/organization either have to upgrade their stuff or drop their use of the tool.

I can't blame you for the latter.

**Comment by dnalbach** [comment]
@Stargator I agree, my concern is that the timeframes for businesses and end consumers are dramatically different. If a new language is going to be treated like a consumer change/deprecation model, then it isn't going to be viable for most enterprises, who need years to adapt, not months.

**Comment by kevmoo** [comment]
I'm sorry for the pain this has caused. Maintaining Dartium had become literally impossible given the Chrome team's evolution of the browser. Dropping it (and moving to the dev compiler model) actually means it's easier for us to support customers long-term since we no longer have to coordinate with such a large dependency.

**Comment by rinick** [comment]
> I'm sorry for the pain this has caused. Maintaining Dartium had become literally impossible given the Chrome team's evolution of the browser. Dropping it (and moving to the dev compiler model) actually means it's easier for us to support customers long-term since we no longer have to coordinate with such a large dependency.

not supporting it is one thing. but stopping people from using it unless they can find some workaround themselves , that's totally different.

**Comment by kevmoo** [comment]
Time limiting the browser was mandated by the Chrome team, I believe. We wanted to push folks away from running a Chrome browser that wasn't being actively patched

**Comment by dnalbach** [comment]
I understand, but that's consumer thinking. The only people using Dartium are developers, and it doesn't make sense for that audience.

**Comment by Stargator** [comment]
@kevmoo Thanks for the insight that the time limiting was mandated by the Chrome team. It's understandable that you could only work within the constraints given to you.

Does that mean that even if the version of Dartium was the same, you couldn't just reissue it with a new expiration for at least another year?

**Comment by kevmoo** [comment]
Does the suggestion at https://github.com/dart-lang/sdk/issues/33580#issuecomment-400978229 not work?

We don't have the ability to build Dartium any more, sadly...well, it'd take a heroic effort to get everything working so we COULD build Dartium again
