### ISSUE TITLE
Ugly error message if generic function is used as a type parameter and DartPad issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#33581]
Generic functions is not allowed to be used as a type parameter. Please see #33555. But if we try to do that then an error is ugly and non-informative. Example:
```dart
typedef T = void Function<X>();
void tFunc<X>() {}
T t = tFunc;

class Test<X> {}

main() {
  try {
    new Test<T>();
    print("No error");
  } on Error {
    print("Error caught");
  }
}
```
This code produces:
```
'file:///D:/Google/dart/co19/test.dart': error: generic function type '<X>() => void' not allowed as type argument of type 'Test<<X>() => void>'
#0      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```
It is unclear from this error if it a compile error or a runtime one which is not caught by try-catch block.

Interesting moment is that in [DartPad](https://dartpad.dartlang.org/) this code works and prints "No error"

Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "windows_x64"

**Comment by anders-sandholm** [comment]
Not clear if this is a front-end or vm issue (and dart2js issue.) 
cc @lrhn @leafpetersen

**Comment by lrhn** [comment]
Probably all of the above. It should be a compile-time error, so the front-end should catch it.

**Comment by eernstg** [comment]
Closing:

DartPad now reports an error `Generic function has type parameters '<X>', so it may not be used as a type argument`, just like other compile-time errors. So I think we can consider the DartPad aspect of this issue as resolved. `dartanalyzer` on the command line acts in the same way (2.1.0-dev.6.0 and latest commit 2fa11436004e5f8235ddff39ee1bac58aaaee534 as well).

It was noted in #34741 that the error message is still confusing, so that part would be covered already as well: Nothing extra for area-analyzer here.

Finally, the VM (2.1.0-edge.ddf67772bbfe60371c1bf2a2731fedac76cd20f7) clearly fails at run time:

```
Unhandled exception:
'file:///usr/local/google/home/eernst/lang/dart/scratch/201810/n021.dart': error: generic function type '<X>() => void' not allowed as type argument of type 'Test<<X>() => void>'
#0      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

So this issue should only be concerned with the fact that the common front end does not detect usages of a generic function type as a type argument. But that's already covered by #30931, so we can close this one.

@kmillikin, I wouldn't normally close an area-front-end issue, but I believe this one can actually be closed. Please reopen if you think I'm wrong.
