### ISSUE TITLE
"Unable to create a refactoring" when trying to MOVE_FILE

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33605]
This may be related to #32701, but I think that's just a bad error whereas I think my request here is good (so it's bad that the error is vague, but I think there shouldn't be an error). I'm trying to rename a file with `MOVE_FILE` but I get this error back (v2.0.0-dev.63.0).

```js
{
	"id": "134",
	"method": "edit.getRefactoring",
	"params": {
		"file": "/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/create_method/class_a.dart",
		"kind": "MOVE_FILE",
		"length": 0,
		"offset": 0,
		"options": {
			"newFile": "/Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/lib/create_method/class_a_222.dart"
		},
		"validateOnly": false
	}
}
{
	"id": "134",
	"result": {
		"initialProblems": [
			{
				"severity": "FATAL",
				"message": "Unable to create a refactoring"
			}
		],
		"optionsProblems": [],
		"finalProblems": []
	}
}
```

(cc @bwilkerson @scheglov)

Also; does this API support moving/renaming a folder or do I have to list the files and send individual requests?

**Comment by scheglov** [comment]
This refactoring is not implemented currently.

**Comment by DanTup** [comment]
Doh! I pushed to get an API in VS Code to give us a notification *before* the rename (based on the docs for this) assuming it already existed =)

In that case, when it is implemented, could we make it support directories so we don't have to send a load of events when a directory is renamed?

**Comment by bwilkerson** [comment]
That sounds reasonable to me.

I don't know how big a task it will be to write this refactoring, but I know that it isn't currently on the schedule for Q3. (Unless you have time to take a look at it.)

**Comment by DanTup** [comment]
I'll certainly try! I have a few biggish things coming up that I'm not sure how much time they'll take, but I'd really like to deliver this so I'll definitely try and find time.

I guess like the standard rename should a good example of producing edits I can look at; but is there anything that does something like finding all the imports/part statements I could use? Probably we'd need to enumerate them all and resolve relative paths to figure out which ones point at the file(s)/folder(s) being renamed. Actually; maybe the standard rename does similar if all the references aren't indexed?

I guess I can do some digging and list some questions.

**Comment by bwilkerson** [comment]
> I guess like the standard rename should a good example of producing edits I can look at ...

Actually, `analysis_server/lib/src/services/refactoring/extract_widget.dart` would be a better example. We are switching our code to use the `DartChangeBuilder` (`analyzer_plugin/lib/utilities/change_builder/change_builder_dart.dart`) to build edits, but the rename refactoring hasn't been updated yet.

> ... is there anything that does something like finding all the imports/part statements I could use?

@scheglov would know this better than I. I know we have code to search for references to identifiers, but I don't know whether we have something similar for references to files.

**Comment by DanTup** [comment]
Great, thanks! I'll try and find some time to dig in :-)

**Comment by DanTup** [comment]
@bwilkerson @scheglov Any opinions on this? I have code that looks like:

```
// Update outgoing references inside this file
await changeBuilder.addFileEdit(library.source.fullName, (builder) {
  final oldDir = pathContext.dirname(oldFile);
  final newDir = pathContext.dirname(newFile);
  _updateUriReferences(builder, library.imports, oldDir, newDir);
  _updateUriReferences(builder, library.exports, oldDir, newDir);
  _updateUriReferences(builder, library.parts, oldDir, newDir);
});
```

This is to create edits for a file being moved (eg. to fix relative paths inside it). Currently a test fails when the renamed file had no relative imports/exports/paths because we return an "empty edit" instead of "no edit" (because of the first line). It feels clumsy to have to pre-scan all the imports/exports/parts to figure out if we need any edits for this file before calling `addFileEdit` (because we end up enumerating them twice; because we can't nicely store the edits up without introducing some data type to hold them).

Is it reasonable to make changeBuilder not emit any edits that were empty or something?

**Comment by DanTup** [comment]
Or maybe in change_childer_core.dart `addFileEdit` could skip adding the change if it didn't get any edits:

```dart
verride
Future<Null> addFileEdit(String path, void buildFileEdit(FileEditBuilder builder)) async {
  FileEditBuilderImpl builder = await createFileEditBuilder(path);
  buildFileEdit(builder);
+ if ((builder.fileEdit.edits?.length ?? 0) > 0) {
    _change.addFileEdit(builder.fileEdit);
+ }
  await builder.finalize();
}
```

**Comment by bwilkerson** [comment]
> Is it reasonable to make changeBuilder not emit any edits that were empty or something?

I've thought about this before, and debated with myself about how best to support this case. I had a concern about whether the behavior you proposed would be surprising, but I tend to think that that's outweighed by the principle that it should be hard for clients of an API to do the wrong thing, and emitting an empty file edit seems wrong on some level. So, in general, I'm in favor of this proposal.

That said, I think it's a little harder to implement correctly than your proposed change because the invocation of `finalize` can add new edits. (At the moment it's being used to add import directives, which is unlikely to happen if there were no other edits, but isn't impossible. Also, we might want to delay adding other edits for a different purpose in the future, and I'd rather leave that possibility open.) And, if I recall correctly, `finalize` currently assumes, in a fairly subtle way, that the file edit has already been added to the change.

If the latter proves to be wrong, then we could move the invocation of `finalize` before the add and everything should work. If not, then we probably need to introduce a new `shouldBeAdded` method to `FileEditBuilderImpl` that would return `true` if (a) there are existing edits or (b) the `finalize` method would add any edits. (Doing the latter might be easier than figuring out whether the subtle order dependency actually exists. :-)

**Comment by DanTup** [comment]
> Also, we might want to delay adding other edits for a different purpose in the future, and I'd rather leave that possibility open

That's valid; I thought the edits were being copied from the builder in this line, but it actually just keeps a reference, so they may be edited later - however that means they'd happen after `finalize` - I'm not sure if that could cause other issues.

I've had a look, but I'm not sure of the best way to handle this. We could possibly strip them out further up (eg. in getRefactoring() in edit/edit_domain.dart) but the further up it's done, the more likely it'll need repeating in other code. We could also add an alternative `addFileEdit` (eg. `conditionallyAddFileEdit` or something), or maybe create a new builder for each file and then add a way to append one builder onto another. Nothing sounds ideal; but lmk what your preference is.

Ofc, we could also just pre-check the imports here, but it probably means if either enumerating twice or building the list into an alternate data structure, and that seems messier.

**Comment by bwilkerson** [comment]
I started trying to explain what I was thinking about, but realized I was writing the code, so I put it together in a CL (https://dart-review.googlesource.com/c/sdk/+/63901).

**Comment by DanTup** [comment]
Great; thanks! 👍

**Comment by bwilkerson** [comment]
As you noticed, that CL causes some of the server tests to fail. They're failing because we're expecting to return an empty, but otherwise validly formed `SourceFileEdit` from the experimental `edit.importElements` request, but with this change we're not producing a source file edit at all.

I think that there are two options. The first is to not commit this CL and to require clients to confirm that an edit will be made before invoking `addFileEdit`. The other is to make the source file edit optional (in the request's result) and require clients to test to see whether one exists (rather than to just iterate over an empty list). I'm fine with either, but thought some discussion might be good before making a decision.

**Comment by DanTup** [comment]
Hmm, neither seem ideal. For checking whether we'll create an edit first, we need to scan through imports/exports/parts/etc. and see if any of them uris in them will require updating - but we can't update them. To avoid enumerating twice, we'd end up keeping track of the edits in an alternative data structure, which feels like it somewhat undermines the edit builder.

Maybe we could make it optional in addFileEdit? Eg. an `allowEmptyEdit` or `omitEmptyEdit` named param? Or if the cases where we do want it are always likely to be where there was a single file edit, maybe an `addSingleFileEdit` method that always added (or another method to work the other way)? It'd definitely be nice if the API made it easy to use whichever way you wanted. If in future there were many places that did it both ways, we should avoid either option requiring too much additional work.

**Comment by bwilkerson** [comment]
The more I think about it, the more I like the idea of changing `edit.importElements` to have an optional `SourceFileEdit`. We have been fairly consistent about making possibly empty collections optional in order to reduce (a) the time required to serialize and deserialize them and (b) the number of bytes being sent across the wire. I think that making it optional is perfectly consistent.

**Comment by DanTup** [comment]
Ok cool; are you going to update the tests in your CL or do you want me to take a look?

**Comment by bwilkerson** [comment]
I'll upload an update to my CL after I get home.

**Comment by DanTup** [comment]
This was resolved by @jwren. VS Code can't use it yet because the required APIs are marked provisional (so we can't publish extensions that use them) but I plan to ship once they un-flag them.
