### ISSUE TITLE
stock_animation_close_first_frame_average and others more noisy (performance regression)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#33637]
A number of related benchmarks got much more noisy (and slower on average) after we rolled to Dart engine `a83b37d35acd8afd82be3f567a4b7231d5bdb928`.

Most notably, the following `microbenchmarks` benchmarks are all much more noisy and slower now:
* stock_animation_subsequent_frame_average
![stock_animation_subsequent_frame_average](https://user-images.githubusercontent.com/551196/41934866-b002db7c-793c-11e8-8b44-e7a123b94ba4.png)
* stock_animation_open_first_frame_average
![stock_animation_open_first_frame_average](https://user-images.githubusercontent.com/551196/41934868-b018defe-793c-11e8-84e2-e2e1b2980b14.png)
* stock_animation_close_first_frame_average
![stock_animation_close_first_frame_average](https://user-images.githubusercontent.com/551196/41934869-b02bd950-793c-11e8-9ec1-65852b61c465.png)

**Comment by alexmarkov** [comment]
The regression is due to https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7.

Results of 8 runs of animation_bench at https://github.com/dart-lang/sdk/commit/35b17f373014cdb54dc7f80cfa59cc7d5f9f3803 (before) and https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7 (after).

### stock_animation_open_first_frame_average

Before:
Results: 29760 | 27271.7 | 26993.7 | 27234.4 | 27998.7 | 27361.9 | 27269.1 | 28521.3
Min: 26993.7
Avg: 27801.35
StdDev: 935.3571633

After:
Results: 30308.6 | 30416 | 27780.6 | 29190.6 | 30074.3 | 28905.9 | 29409.8 | 27152.7
Min: 27152.7
Avg: **29154.8125** (+4.87%)
StdDev: **1182.75997** (+26.45%)

### stock_animation_close_first_frame_average

Before:
Results: 3601.2 | 3914.7 | 3722.2 | 3815.6 | 3778.2 | 4009.3 | 3814.1 | 3867
Min: 3601.2
Avg: 3815.2875
StdDev: 123.0990361

After:
Results: 4241.8 | 3570.1 | 5435.9 | 7530 | 3569.8 | 5358.7 | 3481.1 | 5339.7
Min: 3481.1
Avg: **4815.8875** (+26.23%)
StdDev: **1390.570376** (+1029.64%)

### stock_animation_subsequent_frame_average

Results: 2718.6 | 2802.5 | 2876.6 | 2876.3 | 2897.9 | 2780.5 | 2820.1 | 2783
Min: 2718.6
Avg: 2819.4375
StdDev: 60.89405173

Results: 3025.7 | 4163.3 | 4101.3 | 3977.4 | 4137.3 | 3992.5 | 4226.2 | 4167.9
Min: 3025.7
Avg: **3973.95** (+40.95%)
StdDev: **392.7077066** (+544.9%)

/cc @zanderso

**Comment by alexmarkov** [comment]
GC statistics: https://gist.github.com/alexmarkov/9ac44bc2b29a9d0225c55594f7ebbf64
In a bad run after https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7 there are many full GCs.
Maybe we should tweak the external allocations GC heuristic in order to decrease number of full GCs.

**Comment by rmacnak-google** [comment]
https://github.com/dart-lang/sdk/commit/98a2e90d4f0ce1e0fa092d3fde7cbec2b8b6a6ce
