### ISSUE TITLE
It is OK to declare a const constructor in a class with a mixin

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33644]
This code should not give any errors, according to the current state of the language specification.

```dart
class M {
}
class A extends Object with M {
  const A();
}
```

See `12.1 Mixin Application`:
![image](https://user-images.githubusercontent.com/384794/41951545-3d7a13ec-7980-11e8-935c-9fdc37f4993f.png)
`M` has no fields, so `Object with M` has a constant default constructor.

**Comment by stefantsov** [comment]
I believe this issue and https://github.com/dart-lang/sdk/issues/33645 have the same cause: fasta doesn't allow mixin applications to have const constructors.

**Comment by stefantsov** [comment]
I did some research (that is, talked to @eernstg :)), and it seems that it's not ok to _declare_ a const constructor in a mixin application, but a const constructor is _implicitly delcared_ in case there's one in the superclass of the mixin application, and the mixin doesn't have fields.

So I think the example program in the original post of this issue should result in a compile-time error.  The following example program is supposed to demonstrate the effect of implicitly declared const and not-const constructors in a mixin application.

```dart
class M {}

class S {
  const S.foo();
}

class A extends S with M {
  // The following is implicitly declared:
  //
  //     const A.foo() : super.foo();
}

class N {
  int bar;
}

class B extends S with N {
  // The following is implicitly declared:
  //
  //     B.foo() : super.foo();
}

main() {
  A a = const A.foo();  // Ok.
  B b = const B.foo();  // Compile-time error.
}
```

**Comment by stefantsov** [comment]
Ok, I had another conversation, and it seems that what I've written above is misleading.  The implicitly declared constructors are declared within the mixin application class (`S with M` and `S with N` in my example above), not within the class that extends it (`A` and `B` in the example above).  The class that extends a mixin application is a regular class that may have const constructors in case there are const constructors in its superclass (that is, the mixin application class).

So, the example program in the original post should compile without errors, as rightfully suggested.  And the compiler should produce a compile-time error for my example program, because there are no constructors `foo` declared either in `A` or `B`.

Sorry for the inconvenience!

**Comment by eernstg** [comment]
Agreed! (so [this example](https://github.com/dart-lang/sdk/issues/33644#issue-336065586) has no error; and the constructors are not implicitly created in [`A` and `B`](https://github.com/dart-lang/sdk/issues/33644#issuecomment-410664149), but in their immediate superclasses).
