### ISSUE TITLE
It is an error when the class has a const constructor, and a mixin declares a field.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33645]
See https://github.com/dart-lang/sdk/issues/33644

**Comment by stefantsov** [comment]
I believe this issue and https://github.com/dart-lang/sdk/issues/33644 have the same cause: fasta doesn't allow mixin applications to have const constructors.

**Comment by eernstg** [comment]
I believe that the title may give rise to some confusion. Maybe it could be 'It is an error for a class to have a constant constructor if its superclass is a mixin application `S with M` where `M` has a field'?

The "interesting" case where an error arises even though everything seems to be OK is the following:
```dart
class S { const S.foo(); }
class M { final x = 42; }
class A extends S with M { const A.foo(): super.foo(); }
```
In this situation we could have written the mixin application as a regular class (with an explicit declaration of the forwarding constant constructor), and everything would just work:
```dart
class S { const S.foo(); }
class SwithM extends S { final x = 42;  const SwithM.foo(): super.foo(); }
class A extends SwithM { const A.foo(): super.foo(); }
```
So even in this case where "it should just work", we get an error because the mechanism that generates forwarding constructors just won't generate a constant one when there is a field.

The justification for making this an error is that a final field with a constant initializing expression is a pretty useless thing. ;-)
