### ISSUE TITLE
Unresolved URIs reported without locations.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33718]
For example, when `package:foo` is not defined in `.packages`:

```dart
import 'package:foo/foo.dart';
```

We get `Could not resolve the package 'foo' in 'package:foo/foo.dart'.`. In Analyzer we need the problem location to report it in IDE in a useful way.

**Comment by stefantsov** [comment]
I have started working on this in [CL 63942](https://dart-review.googlesource.com/c/sdk/+/63942).

To try it out I've written the following Dart program:

```dart
import 'dart:io';

  import 'package:foo/foo.dart';

main() {}
```

When I try to compile it, it now produces the error message with the appropriate location:

```
$ pkg/front_end/tool/fasta compile --strong --dump-ir /tmp/asdf.dart
file:///tmp/asdf.dart:3:3: Error: Could not resolve the package 'foo' in 'package:foo/foo.dart'.
  import 'package:foo/foo.dart';
  ^
package:foo/foo.dart:1: Error: Not found: package:foo/foo.dart.
library;
import self as self;

static method #main() → dynamic {
  throw "package:foo/foo.dart:1: Error: Not found: package:foo/foo.dart.";
}
```

@scheglov Could you try to patch in the CL and see if it solves the issue for Analyzer?

**Comment by scheglov** [comment]
This CL moves us a bit further, but then we hit another problem: some errors cause CFE to stop compiling and generate an exception throwing `main`.

So, this file:
```dart
import 'package:foo/foo.dart';

main() {
  print(42);
}
```

Is compiled `pkg/front_end/tool/fasta compile --strong --dump-ir /Users/scheglov/dart/test/bin/test.dart` into:
```kernel
file:///Users/scheglov/dart/test/bin/test.dart:1:1: Error: Could not resolve the package 'foo' in 'package:foo/foo.dart'.
import 'package:foo/foo.dart';
^
package:foo/foo.dart:1: Error: Not found: package:foo/foo.dart.
library;
import self as self;

static method #main() → dynamic {
  throw "package:foo/foo.dart:1: \u0027[31mError: Not found: package:foo/foo.dart.\u0027[39;49m";
}
```

I think this is https://github.com/dart-lang/sdk/issues/33686, i.e. there is no `dart:core`, no resolution for other, valid parts of the file.


There is also a problem with the location of the error.
In the CL it is the first character of the `import` directive.
I think it should be the location of the URI in the offending directive.
![image](https://user-images.githubusercontent.com/384794/42414931-7ccd3830-81f5-11e8-838d-1811f8c72786.png)

**Comment by stefantsov** [comment]
Thanks for taking a look, Konstantin!

I believe that this GitHub issue and https://github.com/dart-lang/sdk/issues/33686 are orthogonal.  This one asks for locations on imports that can't be resolved, and https://github.com/dart-lang/sdk/issues/33686 asks to not omit parts of erroneous programs.

They are orthogonal in the sense that we may solve them separately.  For example, we solve this GitHub issue first, and the locations will be assigned to malformed imports that are not omitted in the output.  However, the imports themselves may be missing in the output until https://github.com/dart-lang/sdk/issues/33686 is solved.  And once https://github.com/dart-lang/sdk/issues/33686 is solved, all of the imports will be shown, and the malformed imports among them will have the locations right away because this GitHub issue is fixed.

So, I see nothing that can prevent us fixing this GitHub issue and closing it even though https://github.com/dart-lang/sdk/issues/33686 is still there.

As for the location itself, that it should point to the URI, and not the `import` keyword, I'll fix in in [CL 63942](https://dart-review.googlesource.com/c/sdk/+/63942) and ask for your review.

**Comment by scheglov** [comment]
Yes, you are right, this issue is separate.
It just not the only one, but it is fine.

I realized that I did not express myself precise enough.
In Analyzer all errors have not only offset, but also length. This make errors more obvious in IDE. So, in case of an unresolved URI we highlight not just the first character of the URI, but the whole URI string.

**Comment by stefantsov** [comment]
I referenced this issue in the list for causes of deprecated_InputError in https://github.com/dart-lang/sdk/issues/33686 and suggest to track that aspect of the issue there.  I suggest track the adding of length of the URI in the error message here.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
