### ISSUE TITLE
TreeNode.enclosingLibrary?

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33807]
It exists for some TreeNode(s), but not for all.
Are there any that are not enclosed in a library?
Is it possible to add `enclosingLibrary` to TreeNode?

We associate metadata with TreeNode(s), and would like to flush metadata when a library is invalidated. So, we need a way to go from a TreeNode to the enclosing Library. For now I'm adding [a helper](https://dart-review.googlesource.com/c/sdk/+/64400) in Analyzer.

**Comment by stefantsov** [comment]
I believe that the original intention was to give `enclosingLibrary` only to the immediate children of libraries, such as `Class` and `Typedef`.  `Member` has `enclosingLibrary` because top-level procedures and fields are `Member`s.  There's a way to get to the enclosing library from a class member, but I think it was done to make the getter work for all `Member`s.

Anyways, I'm putting a P3 label to this, as there's a workaround available.

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
