### ISSUE TITLE
Propagation of inner type with Future with Dart 2

### ISSUE THREAD

**Issue by sestegra** [dart-lang/sdk#33806]
Dart VM version: 2.0.0-dev.67.0 (Tue Jul 3 18:17:07 2018 +0200) on "macos_x64"

Let's assume following code.

``` dart
import 'dart:async';

class Zoo {
  Map<String, Animal> animals = <String, Animal>{};

  void add(Animal animal) => animals[animal.name] = animal;

  Animal get(String name) => animals[name];
  Cat getCat(String name) => get(name);
  Dog getDog(String name) => get(name);

  Future<Animal> asyncGet(String name) async => await new Future<Animal>.value(animals[name]);
  Future<Cat> asyncGetCat(String name) async => await asyncGet(name);
  Future<Dog> asyncGetDog(String name) async => await asyncGet(name);

  Future<Cat> badAsyncGetCat(String name) => asyncGet(name);
  Future<Dog> badAsyncGetDog(String name) => asyncGet(name);

  String toString() => "Zoo: $animals";
}

class Animal {
  String name;
  String toString() => "$runtimeType: $name";
}

class Cat extends Animal {
  void meow() => print("$name: Meow !");
}

class Dog extends Animal {
  void waouf() => print("$name: Waouf !");
}

Future<Null> main() async {
  var zoo = new Zoo()..add(new Animal()..name = 'Foo')..add(new Cat()..name = 'Felix')..add(new Dog()..name = 'Brutus');
  print(zoo);

  // Sync zoo
  {
    var animal = zoo.get('Felix');
    print(animal.runtimeType);

    var cat = zoo.getCat('Felix');
    print(cat.runtimeType);

    var dog = zoo.getDog('Brutus');
    print(dog.runtimeType);

    var nobody = zoo.getCat('Nobody');
    print(nobody.runtimeType);
  }

  // Async zoo
  {
    var animal = await zoo.asyncGet('Felix');
    print(animal.runtimeType);

    var cat = await zoo.asyncGetCat('Felix');
    print(cat.runtimeType);

    var dog = await zoo.asyncGetDog('Brutus');
    print(dog.runtimeType);

    var nobody = await zoo.asyncGetCat('Nobody');
    print(nobody.runtimeType);
  }

  // Bad async zoo
  {
    var cat = await zoo.badAsyncGetCat('Felix');
    print(cat.runtimeType);

    var dog = await zoo.badAsyncGetDog('Brutus');
    print(dog.runtimeType);

    var nobody = await zoo.badAsyncGetCat('Nobody');
    print(nobody.runtimeType);
  }
}
```

The output result is following.
```
$ dart animal.dart
Zoo: {Foo: Animal: Foo, Felix: Cat: Felix, Brutus: Dog: Brutus}
Cat
Cat
Dog
Null
Cat
Cat
Dog
Null
Cat
Unhandled exception:
type 'Future<Animal>' is not a subtype of type 'Future<Cat>'
#0      Zoo.badAsyncGetCat (async.dart:17:46)
#1      main (file:///async.dart:75:25)
#2      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:482:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

I understand well the thrown exception.

I would like to raise the point, because I found the "workaround" with async/await that sounds weird.

So, as Future is a kind of special type, I suggest that the inner type propagation should be allowed for Future.

What do you think about it ?

**Comment by jakemac53** [comment]
cc @leafpetersen do you have any suggestions here? In general I think any `return await` is an anti-pattern, and a situation in which doing that solves an error is less than ideal?

**Comment by lrhn** [comment]
I don't think `Future` is special. The issue here also occurs with other classes as well. It's the same reason `List<int> x = <num>[1, 2, 3];` fails. A `Future` really is just a collection with up to one value.

It's also not something that is easy to change. We do not allow objects to change their type parameters (that's extremely unsafe since collections typically have invariants based on those type parameters).
So, we can't change the type of future after it has been created, and I don't think the `Future` class should be special-cased to allow it just for that.

The `asyncGet` returns a `Future<Animal>`. It's declared as:
```dart
Future<Animal> asyncGet(String name) async => await new Future<Animal>.value(animals[name]);
```
(The body is unnecessarily confusing, it could just be `=> animals[name];)
An async function returns its future *before* executing all of its body. That means that when we know the animal, it's too late to change the actual type parameter of the returned future.


I don't think there is anything wrong with `return await future` (or just `return future` in an *async* function, then the return will await for you anyway). It shouldn't be done *unnecessarily*, but then, nothing should. Here it is necessary because you need to change the type of the future.


(Arguably, all error futures should be `Future<Null>` instances :smile:)

**Comment by leafpetersen** [comment]
If I understand the issue correctly, the question is when we have something of the form:

```
  Future<T> foo() async => f();
```

whether we should "de-sugar this" into:

```
  Future<T> foo() => new Future<T>(() => f() as Future<T>)
```

or 

```
  Future<T> foo() => f().then<T>((x) => x as T)
```

That is, should we cast the future and then await it, or await it and then cast the result?

I think this is largely a question of what invariants we want to build into the library code and the implementations.

**Comment by lrhn** [comment]
@leafpetersen 
I think the issue here is with non-async functions. For async functions, like your example, we already do the latter:
```dart
Future<T> foo() => f().then<T>((x) => x as T)
```
because a return (including a `=>`) in an asyunc function unwraps one level of `Future`.

The trouble-methods here are `badAsyncGetCat`/`Dog`, which are not `async`, and therefore do not unwrap. Changing `=>` to `async => await` fixes the type issue, and so would just chaning it to `async =>`.

**Comment by leafpetersen** [comment]
@lrhn Right you are, I missed that those were non-async.



> Changing => to async => await fixes the type issue, and so would just chaning it to async =>.

The latter part isn't really true though, unfortunately, since we cast to `FutureOr<Animal>` which fails.  We might want to fix that later - it should be non-breaking to relax this.

**Comment by lrhn** [comment]
Ack, true. In any case, I think the request here was that a `Future<Animal>` which has been completed with a `Cat` can be treated as a `Future<Cat>`. I don't see that happening, or if it does, it's a more general feature than just futures, and a much bigger one too.
