### ISSUE TITLE
Articles on dart-lang.org have scary "obsolete" message

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#33960]
For example `https://www.dartlang.org/articles/libraries/zones`. This is the top Google result for "dart zones", but it has a big red error message on the top saying "Content of this page might be obsolete."

I fear this will turn away users if we don't have an appropriate substitute.

**Comment by vsmenon** [comment]
@kwalrath

**Comment by kwalrath** [comment]
I'm not sure what to do about the articles. The banners are there because most of the articles _do_ have some obsolete content. In fact, most of the articles would have been published on Medium, rather than dartlang.org, if that had been an option at the time. Many of the writers are not inclined to update their articles and/or are no longer with Google.

How about I get each article reviewed by the most knowledgable people I can find on the subject, and then add a note at the top of each article that addresses the following points:

* Who should read (or not read) the article, and why (or why not).
* What's changed since the article was written.
* What's still true.
* What's important.
* Where else they can find information on this topic.

For articles that have important content, we should consider either updating the article or writing more maintainable documentation somewhere — perhaps in the dart-lang/sdk repo, where engineers working on the source code are more likely to encounter and update it.

What do you think?

**Comment by vsmenon** [comment]
That sounds good to me.  For Zones (@lrhn), I don't think we actually changed much at all for Dart 2.

**Comment by sjindel-google** [comment]
I think that's a solid solution. It will take time however, is there something we can do avoid scaring users in the meantime though? Perhaps changing the message to something like "This is a community-contributed article and may be out of date," and using a yellow banner instead of red.

**Comment by kwalrath** [comment]
Sure, we can change the banner easily. I'll do that today.

**Comment by kwalrath** [comment]
https://github.com/dart-lang/site-www/issues/663 is the tracking bug for reviews.

**Comment by kwalrath** [comment]
The less scary warnings are up, e.g. https://www.dartlang.org/articles/libraries/zones:

![image](https://user-images.githubusercontent.com/2164483/43157890-2064bae6-8f33-11e8-9aff-a5c18fc13cb3.png)

(although that screenshot makes me realize that I need to change the sides of the page from red to yellow)

**Comment by sjindel-google** [comment]
Thanks! I think that's much less likely to scare away a potential user who is just Googling for documentation.

**Comment by leafpetersen** [comment]
I think this can be closed now?

**Comment by kwalrath** [comment]
Yes, we can close it since dart-lang/site-www#663 is tracking this.
