### ISSUE TITLE
Spec: ensure that references to abstract super properties is an error

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33963]
The specification may be missing text making it an error to make references to abstract members via `super`.  This bug is to track ensuring that this is in the text, and fixing it if not.

See:
https://github.com/dart-lang/sdk/issues/33662
https://github.com/dart-lang/sdk/issues/33951

**Comment by eernstg** [comment]
This is already implied by the text in https://dart-review.googlesource.com/c/sdk/+/51323. I added commentary in that CL to make this point more explicit. Marking this issue as blocked on that CL.

**Comment by kmillikin** [comment]
It's important to write this into the spec.  I spent a long while yesterday trying to figure out where the spec said this, concluded that it actually didn't say this at all and we had a bug in the front end, and then prepared a bug fix before discovering that the spec had been amended in the issue tracker.

Also note as a matter of process that this isn't a "bug fix" in the spec, it's a breaking change to a presumably deliberate behavior of Dart 1.  That's not to say that you guys shouldn't make such changes, but that you absolutely *need* to write them into the spec somehow to keep it consistent. 

I would like to be able to use the spec as a way of answering questions about how the language should behave.

**Comment by kmillikin** [comment]
It's not another matter that this wasn't ever changed in the spec.  That's the exact same matter.

I don't think it's a substantial change to the language and I hope I didn't imply that.

**Comment by eernstg** [comment]
Sorry, then I misunderstood the following:

> ... this isn't a "bug fix" in the spec, it's a breaking change to a presumably
> deliberate behavior of Dart 1

It is _definitely_ the intention that dartLangSpec.tex should contain the normative language on all of Dart, so there's no question that it is important to write these things into the spec, and [51323](https://dart-review.googlesource.com/c/sdk/+/51323) does just that for this particular topic, and many others. We also have to integrate all the feature specs into dartLangSpec.tex before we're done, of course, and there will be new feature specs at that time, going the same way.

**Comment by kmillikin** [comment]
If we aren't in position to make a big change to the spec, can we at least change this part:

```latex
Let $S_{static}$ be the superclass of the immediately enclosing class.
It is a compile-time error if $S_{static}$ does not have an accessible (\ref{privacy}) instance member named $m$.
```
to say that the super class has to have an accessible non-abstract instance member?

**Comment by eernstg** [comment]
Since CL 51323 was landed in 5af984438298212fd821a091c013602b419340e5, we have the following about superinvocations:

```
Let \SuperClass{} be the superclass (\ref{superclasses})
of the immediately enclosing class for $i$,
and let $L$ be the library that contains $i$.
Let the declaration $d$ be
the result of looking up the method $m$ in \SuperClass{}
with respect to $L$ (\ref{lookup}),
and let $F$ be the static type of $d$.
Otherwise, if the method lookup failed,
let the declaration $d$ be the result of looking up
the getter $m$ with respect to $L$ in \SuperClass{}
(\ref{lookup}),
and let $F$ be the return type of $d$.
If both lookups failed, a compile-time error occurs.
```

This is based on method lookup, and lookup (in general) ignores abstract declarations, which means that it is a compile-time error to have a superinvocation when there is only an abstract declaration&mdash;as mentioned in the next paragraph which is commentary. Also, the static analysis is based on the declaration which was actually looked up:

```
Otherwise (\commentary{when one of the lookups succeeded}),
the static analysis of $i$ is performed as specified in Section~\ref{bindingActualsToFormals},
considering the function to have static type $F$,
and the static type of $i$ is as specified there.
```

So this issue should be resolved for superinvocations: The target declaration must be concrete, and the types are checked.

For the section `\ref{superGetterAccessAndMethodClosurization}` (which contains a sentence that could be the one that you mention&mdash;there are 3 similar sentences in the current text and none of them is completely identical to it), the only changes in CL 51323 were font fixes. So we'll do that in an iteration soon to come, making it similar to the text about superinvocations.

I believe that the remaining two occurrences are similar: The fix is needed, but this need is known, and we'll fix it soon.

I don't expect that it will introduce any breakage. For instance, we get a compile-time error here:

```dart
abstract class A {
  void foo(num n);
}

class B extends A {
  void foo(num n) => super.foo(n);
}

main() {
  B().foo();
}
```

So the analyzer already complains about a superinvocation for a method when there is no implementation, and the variant where `foo` is a getter is flagged as an error, too.

So I believe the current status for this issue is as follows: We need to update the spec for getters, setters, and assignment similarly to the fixes that we have already made for methods. And I think we _can_ do that.

**Comment by eernstg** [comment]
Removing 'blocked' label: CL 51323 has now been landed and the remaining work can proceed.

**Comment by eernstg** [comment]
Closing: This issue is concerned with the specification, and the specification was updated as needed when CL 51323 was landed.
