### ISSUE TITLE
Setting a bound to Null results in, "bound cannot be a supertype of itself"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#33991]
This code fails:

```
class C<T extends Null> {}
```

Its true that the bound is a supertype of itself, because the bound is a supertype of all types. And I'm not sure if there's ever a use for this, as the only valid value for T is Null since Null has no supertypes, and so the lower bound is also the upper bound, meaning that an equivalence is the only satisfactory type.

Still, seems like this error should not be reported?

**Comment by eernstg** [comment]
Correct, it is not an error any more, cf. #33709. (The issue was that `T` is a supertype of `Null`, not that `Null` is a supertype of anything, but I'm pretty sure we are talking about the same thing).

**Comment by eernstg** [comment]
Closing: `dart` and `dartanalyzer` do not report an error for this case today, which is the correct behavior. With NNBD the bound `X extends Null` will not be completely useless (only very nearly so), but it is still not an error. The tools also accept the program with `--enable-experiment=non-nullable`, so that's fine as well.

We used to have an error for the bottom type (until now: `Null`) as a bound: 'It is a compile-time error if a type parameter is a supertype of its upper bound', but that rule is now 'It is a compile-time error if a type parameter is a supertype of its upper bound when that upper bound is itself a type variable.', so `X extends Null` and even `X extends Never` are fine today.
