### ISSUE TITLE
analyzer test failures when switching the parser to fasta

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33992]
@danrubel; I'll use this issue as something to reference in the code for tests that we mark as failing.

**Comment by bwilkerson** [comment]
Are there failures to track here, or should we close this?

**Comment by devoncarew** [comment]
This is referenced in the sdk code in 28 places. We should likely improve the granularity here, but we do want to keep the issue open.

**Comment by scheglov** [comment]
I have a question about failing quick fixes, mostly for `await`, but there is one for `var` as well.

We now report 4 errors:
```
AnalysisError:/project/test.dart(20..24): The built-in identifier 'await' can't be used as a type.,
AnalysisError:/project/test.dart(26..28): The value of the local variable 'foo' isn't used.,
AnalysisError:/project/test.dart(26..28): Expected to find ';'.,
AnalysisError:/project/test.dart(30..30): Expected an identifier.
```

In theory we could update analysis of errors in quick fixes to understand `The built-in identifier 'await' can't be used as a type.`. Or are there changes planned for parser to report something more specific for `await` and reducing the number of reported errors?

**Comment by bwilkerson** [comment]
If server is using the error code to differentiate between two or more cases (which I believe is the case here), then the fasta parser needs to generate the right code for the right situation.

We also need to improve the way the parser recovers so that follow-on errors are not generated.

I don't know who will be doing the work, but I suspect that we ought to create an issue, and possibly add it to a checkbox list in the appropriate tracking issue. (Personally, I'd create a single "meta" tracking issue for all such issues, whereas I think we now have three, but I don't care enough to do the work myself.)

**Comment by srawlins** [comment]
I'm closing this as stale. If there are actionable issues, they should be tracked more specifically.
