### ISSUE TITLE
VMService doesn't expose collection members for enough types

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#34004]
Currently the `getObject` vm service method provides the ability to get collection members but only for a very restricted set of types.
Currently only primitive `Map`, `List` and dart:typed_data  objects are supported.
https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#getobject

It would be nice if `HashMap` and `Set` were all supported. Currently Flutter uses `HashMap` instead of `Map` for some common objects so users get a much worse debugging experience as the members of the Map are not easily viewed.

It would be ideal if offset and count members were honored for all classes implementing List, Map, and Set rather than just the native classes. VM Service consumers would be responsible for deciding whether to call the method on Collection objects that aren't the trusted dart:core List, Map, or Set implementation types.

**Comment by rmacnak-google** [comment]
The VM service provides members for _List and _InternalLinkedHashMap because the representation of these objects is hidden within the VM and an ordinary object representation through getObject's "fields" is not available. getObject intentionally never runs Dart code. If a client of the VM service wishes to get a more structured view of any type (one could do this for DateTime or Uri even), it is free to run Dart code to get at the structure, but the client is responsible for  the errors and side effects this can cause.
