### ISSUE TITLE
Dart2 & dart2js performance problem

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#34000]
I have a package that implements a render/game loop. When I use the `--preview-dart-2` performance/frames-per-second drops about 30%.

You can witness the slow dart2 version here:
https://jimmyff.github.io/cellular_automata_web/cellular_automata.html?rules=game_of_life&width=256&height=256&display=fixed&render_size=2&generator=cells

If I remove `--preview-dart-2` from build.release.yaml then I get a 20-30% gain on frames per second.

Demo project source code that shows the issue is here:
https://github.com/jimmyff/cellular_automata_web/tree/master/demos

Package source code here:
https://github.com/jimmyff/cellular_automata/tree/master/

**Comment by jimmyff** [comment]
You can get a quick idea for the performance difference by comparing the above with this version that wasn't built with dart2:
https://jimmyff.github.io/cellular_automata/cellular_automata.html?rules=game_of_life&width=256&height=256&display=fixed&render_size=2&generator=CELLS

NB: This isn't a totally fair test as the above demo uses an older version of the package, but it shows the performance difference nicely without you needing to download the project yourself.

**Comment by lexaknyazev** [comment]
Afair, `--trust-type-annotations` flag is deprecated. Could you try replacing it with `--omit-implicit-checks`?

**Comment by jimmyff** [comment]
Wooo. I knew `trust-type-annotations` had gone but wasn't aware of `omit-implicit-checks`. I'm now seeing a small performance boost!

Thanks very much @lexaknyazev !

**Comment by sigmundch** [comment]
Thanks @jimmyff for filing, and indeed I was also going to suggest what @lexaknyazev said. 

For now, the dart2 implementation of dart2js meets the dart2 semantics, but in doing so it adds a lot of extra checks. We think we will be able to optimize many of these checks in the future, but until we do so, the `--omit-implicit-checks` is a way to remove them.

Bear in mind that, unlike our future optimizations, this flag is unsafe (just like trust-type-annotations was). We always recommend that you do testing and development without the flag to make sure you have good coverage with the checks, that way you don't have strange surprises when you remove the checks on your production app.

I'm about to close this bug because we'll be tracking the different optimizations separately (for example, https://github.com/dart-lang/sdk/issues/34003).

**Comment by jimmyff** [comment]
Okay, I'll follow that ticket. Thanks for the input
