### ISSUE TITLE
Unexpected behaviour of ContentType operator == 

### ISSUE THREAD

**Issue by alexd1971** [dart-lang/sdk#34061]
* Dart SDK Version: Dart VM version: 2.0.0-dev.69.4 (Fri Jul 27 11:42:55 2018 +0200) on "macos_x64"
* MacOSX

```dart
import 'dart:io';

final contentType = ContentType('application', 'json');
print(contentType == ContentType.json); // expected true but prints false
```
or
```dart
import 'dart:io';

final contentType = ContentType('application', 'x-www-form-urlencoded');
print(contentType == ContentType('application', 'x-www-form-urlencoded')); // expected true but prints false
```

**Comment by matanlurey** [comment]
This is documented in https://api.dartlang.org/dev/2.0.0-dev.69.5/dart-core/Object/operator_equals.html:

> The default behavior for all Objects is to return true if and only if this and other are the same object.

It would be prohibitively impossible to provide a custom `operator==` for all objects.

**Comment by alexd1971** [comment]
Thank you.
It is not necessary to provide custom operator== for all objects. But two objects of the same content type logically expected to be equal

**Comment by shyndman** [comment]
I can't help but feel this was closed in error. 

`ContentType` is precisely the kind of object that one would compare against a constant in order to change a program's behavior (in this case, to automate response parsing). The fact that it doesn't is _surprising_ to a consumer of the API. 

Would the Dart team reconsider this decision? Is the cost really so great?
