### ISSUE TITLE
Dartanalyzer does not throw error when Callable function result is assigned to incorrect type. 

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34087]
Dart SDK Version: 2.0.0_dev.69.5
OS: Windows 10

The following code sample declares a callable function and try to assign its result ta a variable of incorrect type:
``` dart
class A<X> {}

class F {
  X call<X extends A<X>>() { return null; }
}

main() {
  F testme = new F();
  A<A> a1 = testme();
  A<A> a2 = testme.call();
}
```
Here analyzer expectedly fails on the `A<A> a2 = testme.call();` but passes with `A<A> a1 = testme();`.

I believe it should fail similarly in both cases.

Sample output is:
```
Analyzing test.dart...
  error - Couldn't infer type parameter 'X'.

Tried to infer 'A<A<dynamic>>' for 'X' which doesn't work:
  Type parameter 'X' declared to extend 'A<A<A<dynamic>>>'.
The type 'A<A<dynamic>>' was inferred from:
  Return type declared as 'X'
              used where  'A<A<dynamic>>' is required.

Consider passing explicit type argument(s) to the generic.

 at test.dart:10:20 - strong_mode_could_not_infer
  hint - The value of the local variable 'a1' isn't used at test.dart:9:8 - unused_local_variable
  hint - The value of the local variable 'a2' isn't used at test.dart:10:8 - unused_local_variable
1 error and 2 hints found.
```
Dart fails with both cases similarly which is expected.

**Comment by eernstg** [comment]
Actually, I'd expect `A<A>` to mean `A<A<A<dynamic>>>`, because it is `A` applied to the raw type `A`, which is completed by instantiate-to-bound to mean `A<A<dynamic>>`.

With that, the expected type for `testme.call()` in `main` is `A<A<A<dynamic>>>` which would also be the attempted inferred value for the actual type argument passed to that function call, and it should then still fail for essentially the same reason.

That said, I agree that it should fail in exactly the same way in the previous line of `main`, on `testme()`.
