### ISSUE TITLE
Observatory not working in Firefox

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#34107]
Firefox `61.0.1`, `Dart VM version: 2.0.0-dev.69.5 (Unknown timestamp) on "linux_x64"`.

![image](https://user-images.githubusercontent.com/4458965/43891812-8ba13be2-9bca-11e8-9708-fd72c3874455.png)

**Comment by bergwerf** [comment]
I primarily use Firefox and every time I use the Observatory I have to open Chromium. For the sake of usability I would highly appreciate if someone looks into this. Let me know if I can do something to help. I have no idea where to start to fix this unfortunately.

**Comment by vsmenon** [comment]
@sigmundch - does the source map error mean anything to you?

**Comment by vsmenon** [comment]
We may also need a build of observatory without minification to get a readable stacktrace.

**Comment by sigmundch** [comment]
Re sourcemaps: the error seems to indicate that the `.map` file is not served by the VM.

This is likely intentional though: my understanding is that observatory is shipped as compiled JavaScript with the VM, but the original sources of observatory are not included and were not meant to be in the shipped SDK.

Given that the issue likely reproduces at tip of tree, I think the best way to debug this would be to rebuild without minification. Alternatively, you could use  deobfuscator tools locally to resynthesize the stack trace (similar to how web apps do deobfuscation server side when shipping apps to production.) We have tools in the SDK repo under `pkg/dart2js_tools/bin/deobfuscate.dart` if you need them.

**Comment by jensjoha** [comment]
Aren't people focusing on the wrong thing here?
As in #34293 --- it doesn't *work* at all --- true, there's also some warning about source maps, but for normal users, that doesn't really matter. What matters is, that loading observatory in firefox just shows a blank page.

I've extracted the following error message and stack trace (the stacktrace seems slightly off -- I don't know why).

```
NoSuchMethodError: method not found: 'registerElement' (receiver.registerElement is not a function)

runtime/observatory/lib/src/elements/helpers/tag.dart:22:10
runtime/observatory/lib/elements.dart:207:33
org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/async_patch.dart:313:19
[...]
third_party/observatory_pub_packages/packages/stack_trace/lib/src/stack_zone_specification.dart:209:7
[...]
runtime/observatory/web/main.dart:16:5
org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/async_patch.dart:313:19
```

It seems that the problem (or, at least the first problem) is that
https://github.com/dart-lang/sdk/blob/bed1bab2cd4b79694db9ace0e5497b8bb9eb1ab8/runtime/observatory/lib/src/elements/helpers/tag.dart#L23
is not supported by most browsers (https://caniuse.com/#feat=custom-elements) (and seemingly deprecated too, https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement).

Notice also, that the chrome console says
```
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
```

and the details page says
```
Method for registering (creating) custom elements in script.
 
 V0 is deprecated at M70, and will be removed in M75, around, Jun 2019.
 For more info: https://groups.google.com/a/chromium.org/d/msg/blink-dev/h-JwMiPUnuU/sl79aLoLBQAJ 
 
 The spec is superceded by Custom Elements V1 and Blink is the only engine that implements V0 APIs.
 https://www.chromestatus.com/feature/4696261944934400
```

So it seems to me that this has to be fixed very soon.
/cc @a-siva @bkonyi @rmacnak-google

**Comment by sigmundch** [comment]
Thanks for taking a look and reviving this thread @jensjoha 

Long ago there as a decision to remove the polyfill for custom elements from observatory (see https://github.com/dart-lang/sdk/issues/32539, https://github.com/dart-lang/sdk/commit/c1432bf7a3669ab4484978a5ceaaf8ad16e459b5, and https://github.com/dart-lang/observatory_pub_packages/commit/d3a3aebefbd35aa30fe7bbc2889b772b398f7d7f), so that and the changes in custom elements would explain why this is broken and is likely to break further once V0 gets removed.

A short-term workaround would be to readd the polyfills, but long term observatory would need to move away from using custom elements via `dart:html`, since it will not support custom-elements v1 (see https://github.com/dart-lang/sdk/issues/27445)
