### ISSUE TITLE
1.0 is int not double in dart web.

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/sdk#34105]
1.0 is int not double in dart web.

```
~ dart --version
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
```

same code 
```
const str = """{"num1":1.0,"num2":1.1}
    """;

  var map = json.decode(str);
  var n1 = map["num1"];
  if (n1 is int) {
    print("is int");
  } else if (n1 is double) {
    print("is double");
  } else {
    print("is other");
  }
  print(map["num1"].runtimeType);
  print(map["num2"].runtimeType);
```

run in dart vm or flutter then result is 
```
is double
double
double
```

run in dart web
```
is int
int
double
```

What do I do to make 1 recognises double instead of int?

**Comment by eernstg** [comment]
Numbers in Dart are represented natively when compiling to JavaScript, that is, every number is represented using the IEEE 754 double-precision format. As an optimization, in ways that programmers cannot observe, a JavaScript virtual machine may choose to use a different representation (such as a 64 bit 2's complement format), but "in principle" a JavaScript number is a `double`, and it is far too expensive to faithfully emulate a genuine `int` type on top of that. So you won't get anything but `double`s on the web at this point. In the future we may get other choices, but we'll see when that happens. ;-)

So right now Dart web numbers use JavaScript `Number` objects to emulate the desired semantics as closely as possible.

In particular, when testing whether a number has type `int`, it is tested whether the given double value is a whole number, not whether it "is an integer", and this means that you will get the following:

```dart
main() {
  print(1.0 is double); // 'true'
  print(1.0 is int); // 'true'
}
```

It would be very, very nice to have a more faithful semantics for Dart numbers on the web, but it is not considered realistic because of the performance implications.

Returning to your question, this means that `1` is recognized as an `int` and `1.0` is recognized as a `double`, but you also get `true` if you swap the types.

For some additional details, check #25493.

**Comment by CaiJingLong** [comment]
thx,get it.
You mean I just need to change the order, decide whether it's double, and then decide whether it's int, to get the truth type.

**Comment by eernstg** [comment]
With the JavaScript `Number` semantics it is in fact so that `int` is a subtype of `double`, which means that you could test for `is int` first; if `true` then you can use it as an `int`, otherwise test `is double`; if `true` then you can use it as a `double`; otherwise it is not a number at all. With the opposite order you'd never discover that some numbers are `int`s, which might break your code.

**Comment by CaiJingLong** [comment]
Actually I found this problem by writing a json2dart web page for the json_serializable library.
I want to get the number type to generate dart code, but I can't. So in the dart web project,I use `num` instead of `int` to achieve my goal.
