### ISSUE TITLE
Why not infer Null for parameter type of empty List in RHS of ?? operator

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34117]
Disabling implicit casts in the angular analyzer plugin, I don't get the inference I expect here:

```
        for (final subDirective in (view?.directives ?? [])) {                   
          usesDart.add(subDirective.source.fullName); 
```

I get the error "dynamic is not a subtype of String" because subDirective is inferred to be a dynamic because I don't have type parameters to `[]`.

Why is this?

My solution is to write `<Null>[]` but I am only really doing so because I don't want to write the full `<AbstractDirective>[]`, and `Null` is safe, but, it should be inferred, no?

**Comment by lrhn** [comment]
That would require the inference to be quite a bit smarter than it actually is (and likely can be).

The expression `(view?.directives ?? [])` occurs in a context with no type hint. The type of the left operand of `??` is `List<AbstractDirective>`. The type of the right operand is inferred to be `List<dynamic>` because there are no hints to any other type. We don't generally pass type hints from one operand to another, only from context to sub-parts, so the type of the first operand does not affect the second operand. 
The fact that both `dynamic` and `Null` would work is evidence that there is no clue from the context, and in that case, inference goes with `dynamic`.

Further, the program *works* if you don't enable the extra-linguistic "no implicit casts" restriction. The language and its type inference is not aware of that restriction. It sees `dynamic` is a viable solution to the type constraints, and with implicit down-casts it will succeed at run-time too.

The one hint that you can see, but the general inference algorithm can't, is that the value is only used for reading, not writing, so picking `Null` instead of `dynamic` will not cause an error (like it would if anyone did `(... ?? []).add("foo")`). That a generic value is only used in ways where its type variable occurs covariantly is too hard to detect (and likely undecidable in general).

**Comment by MichaelRFairhurst** [comment]
Thanks Lasse, that makes sense.

In my head I think of this as `view?.directives ?? <infer type>[]`.

> The fact that both dynamic and Null would work is evidence that there is no clue from the context, and in that case, inference goes with dynamic.

What I likely then want is to disable implicit dynamic, because this strikes me as a silent inference failure.

> The one hint that you can see, but the general inference algorithm can't, is that the value is only used for reading, not writing, so picking Null instead of dynamic will not cause an error (like it would if anyone did (... ?? []).add("foo")). That a generic value is only used in ways where its type variable occurs covariantly is too hard to detect (and likely undecidable in general).

That's not how I think of this, for two reasons.

Firstly, the opposite is true as well.

```
var f = view?.directives ?? [];
List<Directive> l = f; // fails if f is List<dynamic>
```

So while it may be a good explanation of why not Null, its not a good explanation of why dynamic. Its unreasonable to expect that I would expect the program to infer one or the other when neither is indicated or guaranteed to work better than the other.

_Although, I'm assuming there _are_ good reasons why we usually infer Top here instead of Bottom, when the user has restricted the type to neither in a way we could tell_.

The other thing is that from my perspective, I see one branch that requires inference and one branch that does not. I think of that as a hint. This could easily be a heuristic:

```
  if (lhs.isPrecise && rhs.requiresInference) {
    analyze(lhs);
    rhs.constraint = lhs.type;
    infer(rhs);
  } else if (rhs.isPrecise && lhs.requiresInference) {
    analye(rhs);
    lhs.constraint = rhs.type;
    infer(lhs);
  } else {
    infer(lhs);
    // don't forward any constraint from the lhs to the rhs so that ordering doesn't matter
    infer(rhs);
  }
```

Realistically, however, its probably just as good to have implicit-dynamic disabled.

Closing unless you think there are any other lessons to be learned here, other than that implicit-dynamic is useful in this case.
