### ISSUE TITLE
Compile failed to detect wrong upcasting of function type

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#34129]
As shown below, a `BF` function shall NOT be assigned to a `AF` variable since B is a subclass of A. However, the compiler doesn't detect it.

Note: it will be detected correctly at run time.

```
class A {
}
class B extends A {
}
//--- 2nd test --//
typedef void AF(A a);
typedef void BF(B b);

void t1(void bf(B b)) {
  AF af = bf; //compiler shall detect error here
}

void main() {
  t1((B b) => null);
}
```

**Comment by lrhn** [comment]
I believe this is an implicit down-cast. It's possible for the value of `bf` to be a function accepting `A`, so the compiler inserts a run-time check instead of rejecting it as a compile-time error.

It's effectively the same as assigning a value of type `A` to a variable of type `B` - you get an implicit down-cast to `B` at run-time.

**Comment by tomyeh** [comment]
Got it. My bad:( Thanks for your quick response.
