### ISSUE TITLE
Dart2js accepts "null" as argument to "!".

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34147]
Example:

```dart
main() {
  bool x = null;
  print(!x);  // Should throw, prints "true" in dart2js.
}
```

**Comment by rakudrama** [comment]
Will `!` accept only a nonnullable operand with NNBD?

**Comment by lrhn** [comment]
Yes, the type expected by conditions and boolean operators will (overwhelmingly likely) be non-null `bool`.

All these operations currently throw if they get a null value (exept when implementations forget to check), so they are prime examples of operations whose operands will become non-nullable.

**Comment by eernstg** [comment]
Note that dart2js fails to raise a dynamic error because null occurs where a `bool` is required in other situations as well. https://github.com/dart-lang/sdk/issues/36193#issue-420684809 reports that `if (e) ..` will run the else branch rather than raising a dynamic error. Just tried another one (using dart2js from ac4eca7eb9a0d82ee853aca6f18afe917ab17835):

```dart
main() {
  print("Before loop");
  while (null) {
    print("In loop!");
    break;
  }
  print("After loop");
}
```
Surprisingly, this prints 'Before loop', then 'After loop', and then once more 'After loop'. With do-while, `null` counts as false (so it prints 'Before loop', 'In loop!', 'After loop' as semi-expected):

```dart
main() {
  print("Before loop");
  do {
    print("In loop!");
    break;
  } while (null);
  print("After loop");
}
```

**Comment by fishythefish** [comment]
https://dart-review.googlesource.com/c/sdk/+/98780 should fix this. The error message might look wrong (see the CL summary), but we should at least be producing errors.
