### ISSUE TITLE
Different behavior of int.compareTo() for the VM and a browser

### ISSUE THREAD

**Issue by Sharom** [dart-lang/sdk#34184]
The method `compareTo()` returns different results for the comparison of `0` and `-0` on the VM and in a browser.

* **Dart SDK version:** 2.0.0 on "macos_x64"
* **Browsers:** Safari 11.1.2, Google Chrome 68.0.3440.106 (64-bit)
* **OS:** Mac OS 10.13.6

**Code to reproduce:**
```dart
void main() {
  print(0.compareTo(-0));
  print((-0).compareTo(0));
}
```

**Expected output:**
```
0
0
```

**VM output:**
```
0
0
```

**Browser output:**
```
1
-1
```

**Comment by lrhn** [comment]
The browser is behaving correct because it is not implementing `int` the same way as the VM.
When compiling to JavaScript, instances of `int` are also instances of `double`, so the value of the integer literal `0` is the same as the value of the double literal `0.0`.
When we use the `-` operator of that value, we get `-0.0`, and `-0.0` compares less than 0 (aka 0.0).

So, this is an unavoidable consequence of the way Dart integers are compiled JavaScript.

**Comment by Sharom** [comment]
@lrhn Don't tell me that this is normal, that this is a limitation of JavaScript.
Operator `==` works correctly with `int`. Why `compareTo` must be different?

Sure, we have a limitation of range for `int` when we compile a code to JS. But behavior defined by API must be the same! `int` must behave as integral value, not as `double`.

**Comment by matanlurey** [comment]
There is no such thing as an int or double in JavaScript

**Comment by Sharom** [comment]
> There is no such thing as an int or double in JavaScript.
I know, but we are talking about Dart and Dart provides `int`.

It's clear that JS `number` is in use under the hood and we have some limitations. But `number` under the hood — detail of implementation.

In my opinion, behaviour of `int` must be identical for VM and for WEB (with the exception of range).

**Comment by Sharom** [comment]
Ok, I got it.

**Comment by lrhn** [comment]
No problem. I didn't take any offense, but thank you for the consideration.
