### ISSUE TITLE
Implement @sealed-based analyzer codes

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#34232]
I think we need 3 codes for analyzer's `@sealed` analysis:

* [x] `INVALID_SEALED_ANNOTATION`, which reports when `@sealed` annotates something other than a class or mixin.
* [x] `INVALID_USE_OF_SEALED_CLASS`, which reports when a `@sealed` class is used as a super-class, outside of its package.
* [ ] ~~`UNSEALED_SUB_CLASS_OF_SEALED_CLASS`, which reports when a valid (same-package) sub-class of a sealed class is not also annotated with `@sealed`.~~ deciding against; instead https://github.com/dart-lang/dartdoc/issues/1886 can help to document.

**Comment by srawlins** [comment]
Hi @bwilkerson, what do you think about the 3rd bullet above? I'm thinking we can do without, as other rules that could have a similar requirement, don't.

E.g. all subclasses of an `@immutable` class are not required to also be labelled `@immutable`. Instead the rules of `@immutable` are enforced on all subclasses of an `@immutable` class, instead of direct subclasses. The same is currently done for `@sealed`, so I think it would be nice to not require every single subclass of a `@sealed` class to be explicitly marked as such.

WDYT?

**Comment by bwilkerson** [comment]
I think it's perfectly reasonable for an annotation to impact declarations other than the one it's textually associated with. We have several like that (such as `immutable`). And I think it makes sense for `sealed` because I think the author's expectation is that there won't be any subtypes, direct or indirect.

But I also think there's an interesting documentation question. If a class is sealed indirectly, then it's harder for a user to see that it's sealed. I have to wonder whether dartdoc documents these transitively applied annotations. (@jcollins-g)

But I'd define `sealed` as not being required on subclasses and resolve the documentation question more globally.

**Comment by jcollins-g** [comment]
If the analyzer tells us an annotation exists in the element metadata, we should document it, but we don't attempt to transitively apply annotations outside of what the analyzer tells us.  It's possible we could implement that though.  Dartdoc already knows about a handful of "special" objects that are documented in an unusual fashion (`Object`, `Interceptor`, and `@pragma`) and this would be another two added to that list.  While this adds special casing, it'd be relatively straightforward to do nice things like refer directly to the class declaring the `@sealing` in documentation.

**Comment by srawlins** [comment]
OK, I've opened https://github.com/dart-lang/dartdoc/issues/1886. Let's call this complete then 😄.

**Comment by srawlins** [comment]
The only thing left to do is release meta 1.1.7. @bwilkerson is that something you can do?

**Comment by bwilkerson** [comment]
Yes. Is everything ready?

**Comment by srawlins** [comment]
Oops, lemme correct the doc comment on `sealed` before releasing. https://dart-review.googlesource.com/c/sdk/+/88289

**Comment by srawlins** [comment]
OK meta package should be ready to release!

**Comment by bwilkerson** [comment]
done

**Comment by srawlins** [comment]
I'm calling this one closed. Thanks for everyone's input!
