### ISSUE TITLE
CFE infers type arguments which do not conform to bounds

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34230]
Consider the following example:

```dart
void foo<T extends int>(T x) {
  print(T);
  int y = x;
  print(y);
  print(3 + y);
}

main() {
  dynamic x = 'abc';
  foo(x);
}
```

CFE produces the following kernel:

```
  static method foo<T extends core::int = core::int>(tes::foo::T x) → void {
    core::print(tes::foo::T);
    core::int y = x;
    core::print(y);
    core::print(3.{core::num::+}(y));
  }
  static method main() → dynamic {
    dynamic x = "abc";
    tes::foo<dynamic>(x);
  }
```

CFE infers `<dynamic>` type arguments for `foo()`, while `foo()` can only take `<T extends int>`.
This kernel is not a properly typed.

VM relies on kernel being correctly statically typed and omits checks in certain cases. This test prints the following when run:

```
dynamic
abc
Unhandled exception:
NoSuchMethodError: Class 'String' has no instance method '_addFromInteger'.
Receiver: "abc"
Tried calling: _addFromInteger(3)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      int.+ (dart:core/runtime/libintegers.dart:12:38)
#2      foo (file:///usr/local/google/home/alexmarkov/work/dart/sdk/test_hello8.dart:6:11)
#3      main (file:///usr/local/google/home/alexmarkov/work/dart/sdk/test_hello8.dart:11:3)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

This is a clear violation of soundness of types.

I think CFE should infer correct type arguments which conform to bounds (`<int>` in this case) and insert implicit cast from dynamic to int on the caller side. If such inference is not possible, CFE should issue a compile-time error instead of producing incorrectly typed kernel.

/cc @kmillikin @mraleph @leafpetersen

**Comment by alexmarkov** [comment]
In similar case involving generative constructor CFE issue a compile-time error:

```dart
class A<T extends int> {
  A(T x) {
    int y = x;
    print(T);
    print(y);
  }
}

main() {
  dynamic x = 'abc';
  new A(x);
}
```

```
Error: Can't use a super-bounded type for instance creation. Got '#lib1::A<dynamic>'.
Specify a regular-bounded type instead of the super-bounded type. Note that the latter may be due to type inference.
  new A(x);
      ^
```

However, if constructor is converted to a factory, there is no error:

```dart
class A<T extends int> {
  A(T x) {
    int y = x;
    print(T);
    print(y);
  }

  factory A.fact(T x) => new A(x);
}

main() {
  dynamic x = 'abc';
  new A.fact(x);
}
```

Output:
```
dynamic
abc
```

**Comment by eernstg** [comment]
> CFE infers `<dynamic>` type arguments for `foo()`, while `foo()` can only take `<T extends int>`.
> This kernel is not a properly typed.

Right, an invocation of a generic function creates a new entity (a stack frame) where the type arguments are reified and available for creation of new objects. Because of that property, type arguments passed in a generic function invocation (inferred or explicit, that doesn't matter) must satisfy the bounds.

This is worth noting because we allow certain bounds violations (see [this feature spec](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/super-bounded-types.md) or search for 'super-bounded' in a recent version of the language specification) in situations where there is no reification. It is easy to forget that a stack frame is so much like a regular object in this respect, so I've heard the expectation expressed many times that super-bounding is allowed also for generic function calls. It ain't. ;)

**Comment by stefantsov** [comment]
Yes, it is an instance of https://github.com/dart-lang/sdk/issues/33308.  I'm closing this one as a duplicate, and will reference it in https://github.com/dart-lang/sdk/issues/33308 as a source of more test cases.
