### ISSUE TITLE
Dartanalyzer does not allow declare class A with "X extends FutureOr<A<X>>" type parameter .

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34264]
Dart SDK Version: 2.1.0-dev.2.0
OS: Windows 10 (64 bit)

The following code sample declares two classes with `Future` and `FutureOr` type parameters:
```dart
import "dart:async";

class B<X extends Future<A<X>>> {}
class A<X extends FutureOr<A<X>>> {}
```
Dart passes with both code lines, i.e. just print `OK` as a result.

Dartanalyzer  passes with class `B<X extends Future<A<X>>> {}` and fails with `class A<X extends FutureOr<A<X>>> {}`, sample output is:
```
Analyzing test.dart...
  error - 'X' doesn't extend 'FutureOr<A<X>>' at test.dart:4:30 - type_argument_not_matching_bounds
1 error found.
```
I believe this is incorrect result and analyzer should pass both for `Future` and `FutureOr` parameters.

**Comment by askeksa-google** [comment]
The spec says (in 10.9):
"It is a compile-time error if the type in the extends clause of a class C is a type variable (14), a type alias (19.3.1), an enumerated type (13), a malformed type (19.1), a deferred type (19.1), type dynamic (19.6), or type FutureOr<T> for any T (19.7)."
So the class declaration with FutureOr as supertype is not valid Dart. See also https://github.com/dart-lang/sdk/issues/33744

**Comment by eernstg** [comment]
Oh, but in this case we do not use `FutureOr<..>` as a superclass, we use it as the bound of a type variable (in this case: an F-bounded one), and I couldn't spot any reason why that would be an error.

It's not even impossible to find a type argument that satisfies this constraint: `A<Null>` would do, and with `class C extends A<C> {}`, `A<C>` would do as well (`C` can be given as an actual type argument to `A` in the first place because `C <: A<C> <: FutureOr<A<C>>`), and similarly for `class D extends Future<A<D>>> {}` and `A<D>`.

**Comment by iarkh** [comment]
And anyway, analyzer and dart should behave in the same way here.

**Comment by eernstg** [comment]
Closing: `dart` as well as `dartanalyzer` accepts the example program as of a49217bc3aa46e5406ad72017901490c2913c409.
