### ISSUE TITLE
Dart memory leak using Flutter, using 23GB of memory

### ISSUE THREAD

**Issue by abacaj** [dart-lang/sdk#34271]
`Dart version 2.1.0-dev.1.0.flutter-69fce633b7`

I started my Flutter app as normal in debug mode using VSCode and dart.exe is using all of my system memory:

![image](https://user-images.githubusercontent.com/7272343/44665812-d9696200-a9e4-11e8-9054-5d7afe29249c.png)

Any ideas?

**Comment by mraleph** [comment]
We would need the full command line for that `dart.exe` - it might be running many different things.

To get the full command line open command line (`cmd.exe`) and type:

`wmic process where "name like '%dart%'" get processid,commandline`

Alternatively you can you [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).

**Comment by abacaj** [comment]
Interesting, I am not able to consistently reproduce this, I ended the dart task and now it is running correctly.

**Comment by mraleph** [comment]
I am going to close this one - please let us know if the situation happens again.

**Comment by HerrNiklasRaab** [comment]
Same Problem here, open dart project in vs code, an this happens:
![unbenannt](https://user-images.githubusercontent.com/28401593/46971551-95c5d700-d0bc-11e8-882a-39d9cc4037fa.PNG)

I am using 16 GB RAM on my Pc. 
This started happening while working without any reason as, far as I no. 
VS Code Version is: 1.28.1
This always happens if i start VS Code. VS Code shows analysing and something like search or go to definition don't work.

Link to source code will follow, as soon as it's uploaded.
