### ISSUE TITLE
Dart2JS does not remove unused fields

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#34279]
An internal user identified that one of the code-size issues of the current AngularDart compiler is that it needlessly created class fields where a local property would have been fine in many situations. We thought that this would have been optimized by Dart2JS, but it was not:

```dart
class Animal {
  String name;

  void build(String name) {
    this.name = name;
    print(this.name);
    return;
    return;
  }

  void doOtherThings() {
    return;
    return;
  }
}

void main(Map external) {
  String name = external['name'];
  var a = new Animal();
  a.build(name);
  a.doOtherThings();
}
```

... emits ...

```js
main: function($external) {
  var a = new F.Animal();
  a.build$1(C.JSNull_methods.$index(H.interceptedTypeCheck($external, "$isMap"), "name"));
  a.doOtherThings$0();
},
Animal: {
  "^": "Object;0name",
  build$1: function($name) {
    this.name = $name;
    H.printString(H.S($name));
    return;
  },
  doOtherThings$0: function() {
    return;
  }
}
```

Notice the `this.name = $name`, even though this has no effect on the program.

(In our case, there were sometimes dozens of fields per class, and 100s/1000s of classes).

**Comment by rakudrama** [comment]
I don't really think removing 'unused' fields in this example is a reasonable expectation.
It would be _cool_ if we could do it, but it is harder than it might appear.

The initial program _does use_ the field -- `print(this.name)`.
The point at which the field becomes unused (optimization part of compiling method Animal.build) is after dart2js has committed to the layout of Animal.

You should assume that the program does what is written, and sometimes 'optimizations' can it is done a little more efficiently.

The generator should avoid generating code that requires heroic optimization - then the code will run better on DDC too.
I did ask het@ to open an internal issue to use local variables in the generated build() methods.

I'm going to close this issue since I don't see a path to removing fields unless they are obviously unused.
