### ISSUE TITLE
Analyzer should signal a static error when invoking a non-function

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#34320]
The analyzer signals this error in most cases, but the exception seems to be `Object` methods invoked on objects of static type `dynamic`.

```dart
main() {
  dynamic d;
  d.hashCode();
}
```
Though it does correctly know that `d.hashCode` has type `int`.  We'd like this to be an error, but it's a breaking change so we should be careful rolling it out .

@leafpetersen

**Comment by kmillikin** [comment]
I just checked and the Analyzer does signal the error when invoking the result of `toString()`, so it seems like it's only the getters on `Object` that trigger the issue.

**Comment by eernstg** [comment]
That is indeed not covered explicitly in [dynamic-members.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/dynamic-members.md), so with the current specification the expression `d.hashCode()` is allowed, and it has static type `dynamic`.

I suspect that we can make it an error (following the rationale behind the other rules in that feature spec: we can prove that it will fail):

Section 16.18.1 Ordinary Invocation specifies that for `d.hashCode()`, at run time, we perform method lookup. This lookup is guaranteed to fail (because `noSuchMethod` can't kick in, and no class can declare a method that overrides a getter), so we proceed to perform a getter lookup (and that will succeed, because `Object` has a concrete `hashCode`, and overriding declarations may exist but cannot make the lookup fail). The return type is guaranteed to be `<: int`, and no function type will satisfy that, nor will any user-written class that has a `call` method be `<: int`.

With that in place we can promise that `d.hashCode()` will fail, and hence it makes sense to make it a compile-time error.

However, the same reasoning would not apply for `d.runtimeType()`, because it _would_ be possible to override `runtimeType` and return an instance whose dynamic type implements `Type` and has a `call` method.

So we need to go through a twisted justification in order to make `d.hashCode()` a compile-time error, and it's probably going to be a lone exception.

(Moreover, if we introduce `dynamic<T>` and hence get a dynamic type for all regular types, not just `Object`, then we presumably couldn't make all those additional getters behave in the same way, because they're more likely to be like `runtimeType` where the invocation may succeed, than being like `hashCode` where it's guaranteed to fail: With `dynamic<Rectangle> r = e; r.upperLeft(whatever: 'xyzzy')` the interface of `Rectangle` may have a getter `upperLeft` with return type `Point`, but an override of `upperLeft` could return an instance of a subtype of `Point` that has a `call`).

That makes me doubt that it's worth the trouble to make `d.hashCode()` a compile-time error. Isn't it ridiculously rare, anyway? ;-)

**Comment by kmillikin** [comment]
Here we really do need to see how https://github.com/dart-lang/sdk/blob/master/docs/language/informal/dynamic-members.md is going to get written into the spec.

My reading is that the intent of "For instance, d.hashCode has type int and d.runtimeType has type Type." is that the language should behave as if d.hashCode exists and has type int.  And the spec is clear that it is a static type error to invoke that because it is not assignable to a function type: "If $T.m$ exists, it is a compile-time error if the type $F$ of $T.m$ may not be assigned to a function type."

We would need a twisted justification, in my mind, to make this not be a static type error.

The case of dynamic.runtimeType is identical.  It has static type Type.  If you want to invoke that, I'm sorry, you can't do that.  You can write (d.runtimeType as dynamic)() if you need to work around it.

d.hashCode() might not be ridiculously rare.  Programmers will forget hashCode is a getter and not a method (like, any Java programmer) or their fingers will just slip.  It's clearly just a typo or a braino and I don't know why it wouldn't be an error.

I'd vote we save the programmer who accidentally writes d.hashCode() at the cost of mildly inconveniencing the programmer who overrides runtimeType to return something callable.

**Comment by eernstg** [comment]
Let me see how we could achieve that. First, here's how I concluded that the type is `dynamic` according to the current wording in 'dynamic-members.md'. First we have this catch-all clause:
```
For an instance method invocation `e` (including invocations of
getters, setters, and operators) where the receiver has static type
`dynamic` and `e` does not match any of the above cases, the static
type of `e` is `dynamic`.
```
So we need to check that no other case applies. The language specification (section 'Function expression invocation') clearly indicates that `d.hashCode()` is an ordinary method invocation, the crucial sentence being the following one:
```
If $e_f$ is a property extraction expression (\ref{propertyExtraction}),
then $i$ isn't a function expression invocation and is instead recognized
as an ordinary method invocation (\ref{ordinaryInvocation}).
```
I take this to mean that the potentially applicable case in dynamic-members.md is the following one:
```
Let `e` be an expression of the form `d.m(arguments)` where the static type
of `d` is `dynamic`, `arguments` is an actual argument list, and `m` is a
method declared in `Object` whose method signature has type `F`. ...
```
But that one doesn't match, because there is no such method in `Object`.

However, I think we could get the effect you want by adding one more case:
```
Let `e` be an expression of the form `d.m(arguments)` where the static type
of `d` is `dynamic`, `arguments` is an actual argument list, and `m` is a
getter declared in `Object`. It is a compile-time error if the return type of that
getter is not assignable to a function type.
```
This would prevent things like `d.runtimeType(42)` even though it might succeed, and the motivation for doing that would be that it is too error prone, and developers can still write `(d.runtimeType as dynamic)(42)`, as you mentioned.

**Comment by eernstg** [comment]
Here's [a CL](https://dart-review.googlesource.com/72700) that makes `d.hashCode()` an error.
@lrhn, @leafpetersen, do you support this change?

**Comment by eernstg** [comment]
[dynamic-members.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/dynamic-members.md) has now been updated such that `d.hashCode()` is a compile-time error.

The criterion used is that `d.m(...)` should be type checked as a function expression invocation when `m` is a getter in `Object`. This will allow for type rejecting `d.runtimeType()` as well, because it makes an attempt to call an entity of type `Type`, and it would allow for checking argument lists for getters returning a function type with some arguments, etc. In other words, it extends the static checks to several new situations where any violation of those checks is a guaranteed dynamic error. _Plus_ some cases that we are now outlawing because we consider them to be very likely mistakes (such as `d.runtimeType()`).

Finally, it also includes the cases where we are calling an `Object` member using a cascade (in which case we ignore the returned value, but it is still relevant that some situations are errors).

**Comment by eernstg** [comment]
@kmillikin, when [this change](https://dart-review.googlesource.com/72700) has been resolved: if it is landed, do we then need an issue for the front end as well?

**Comment by kmillikin** [comment]
No, it is implemented for the CFE in https://dart-review.googlesource.com/c/sdk/+/72403/

**Comment by kmillikin** [comment]
Yes:

```
Error: 'hashCode' isn't a function or method and can't be invoked.
  (true as dynamic)..hashCode();
                     ^
```

**Comment by eernstg** [comment]
Cool, thanks!

**Comment by leafpetersen** [comment]
LGTM, thanks.

**Comment by lrhn** [comment]
LGTM too, `dynamic Object` FTW.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/76560
