### ISSUE TITLE
Analyzer is too strict for redirecting factory constructor parames

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34338]
Revealed by default_implementation2_test, by chance (#34337).

This is rejected:

```
abstract class A {                                                           
  factory A(dynamic x) = B;                          
}                                                                                
                                                                                 
class B implements A {                                     
  B(int x) {}                 
}      
```

Per the spec:

```
It is a compile-time error if the static argument list type (\ref{actualArgumentLists}) of
\code{($e_1 \ldots,\ e_p,\ x_1$: $e_{p+1}, \ldots,\ x_q$: $e_{p+q}$)}            
is not an assignable match for the formal parameter list of the redirectee
```

That means that the factory constructor is valid.

Note: we should probably **not** fix this until #34336 is fixed, as the analyzer is protecting users from that soundness bug, currently.

We should also triage this test (#34337) and confirm that we don't want to change the spec here, before fixing.

**Comment by lrhn** [comment]
I believe we actually intended this to be an error (so likely we want to fix the spec). Since the type accepted by `B` is statically known, there is *no* argument to `A` which can succeed if it isn't an `int`. You might as well make the parameter type of `A` be `int`.

We are being extra strict for redirecting factory constructors because we know that the value is always being forwarded completely unmodified. Any time a user gets to write an expression, we need to assume that they might know more than we do, but in this particular case, there is nothing more to know, the value that is accepted by the `dynamic` type annotation *must* also be acceptable by the `int` type annotation, and the user is probably making a mistake by widening the type in `A`. So, we make them fix that.

**Comment by eernstg** [comment]
Closing: Given that this issue is labeled `area-analyzer` and `type-bug`, but the analyzer does indeed raise a compile-time error when it should do so, I believe that the correct action here is to close the issue. 

I also believe that the CFE is covered on the same topic by #34336, so it wouldn't be useful to re-label this issue as `area-front-end`.

**Comment by MichaelRFairhurst** [comment]
Reopening because I don't see any issues filed regarding fixing the spec

**Comment by MichaelRFairhurst** [comment]
Actually, closing, I'll go off of #34337
