### ISSUE TITLE
Test config_import_corelib_test needs triage

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34332]
This test fails fasta and analyzer, and will never pass static analysis:

```
import 'config_import_corelib_general.dart'                                      
    if (dart.library.io) 'config_import_corelib_io.dart'                         
    if (dart.library.http) 'config_import_corelib_http.dart' as lib;    
  
main() {                                                                         
  var io = const bool.fromEnvironment("dart.library.io");         
                                                                                 
  var cy = new SubClassy();                                                      
                                                                                 
  if (io) {                                                                      
    Expect.isTrue(lib.ioSpecific());                                           
```

I'm not sure if this is a valid test for Dart 2.

**Comment by lrhn** [comment]
It is valid when compiled for a platform where `dart:io` is available. 
It is *not* valid when compiled for any other platform, because the run-time guard of `if (io)` doesn't prevent the body from being compile-time checked against the actually imported library.

(I assume a later part of the test will be invalid for the `dart:io`-supporting platform too, so most likely the test is always invalid).

We should split it into separate tests, and mark them failing or succeeding per platform, to ensure that we don't always reject a program just because it doesn't work on all platforms.

**Comment by MichaelRFairhurst** [comment]
Just to confirm, as well: these will never pass for the analyzer, right?

**Comment by fishythefish** [comment]
https://dart-review.googlesource.com/c/sdk/+/116057
