### ISSUE TITLE
Analyzer infinite loop/crash: recursive type parameter bounds

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34333]
```
/*@compile-error=unspecified*/ class A<T> implements B<List<T>> {}               
                                                                                 
/*@compile-error=unspecified*/ class B<T> implements A<List<T>> {}               
                                                                                 
main() {                                                                         
  new A();                                                                       
  new B();                                                                       
} 
```

from conflicting_generic_interfaces_hierarchy_loop_infinite_test

Does not fail on CFE.

Does not crash if "List" is removed.

Marking a P2 because it seems it does not happen. However, this is not good at all, so I put it in Dart 2.1, even though I expect this case may slip.

**Comment by lrhn** [comment]
The problem seems to be recognizing that `A<T>` implementing `A<List<List<T>>` is invalid. It is invalid just because `A` contains itself (even if it's with a different type parameter) as its own super-type.

It should be invalid with the `List`s removed as well since it still means that `A<T>` is a super-type of `B<T>` which is a super-type of `A<T>`, so `A` still has itself as a super-type. The super-type hierearchy *must* be non-cyclic for any type, otherwise that type is invalid. (Anything depending on an invalid type is also invalid, but probably shouldn't get a separate error).

I like to think of it so that we do type-hierarchy validation before we ever try to use `A` as a type for anything.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/81661
