### ISSUE TITLE
LinkedListEntry subclass  broken?

### ISSUE THREAD

**Issue by mkliger11** [dart-lang/sdk#34363]
dart 2 for Flutter ios/android
Mac OSX

My problem is I have a LinkedListEntry (subclassed as per the docs) object that does not seem to return correctly. I have a function that returns an entry within a LinkedList, and when I designate it to return a LinkedList entry's next or previous pointer, the function returns the original pointer (instead of .next, .next.next, .previous, whichever). My LinkedList is a class member variable that is iterated through, which gives the function the ability to access its data and thus return the pointer.

For simplicity, my code is as simple as: 

    myLinkedListClassMemberVariable.forEach((entry)
    {  
        if(someBool)
           return entry.next; // this will never return the actual .next, only the entry itself
       else
           return entry;
     });

This could be a silly mistake in which I do not understand how DART/Flutter returns values/memory from functions, however, I have found zero documentation referencing this enigma. Regardless, DART should not allow for any deep return at all of the original pointer, if this is indeed the intended behavior.

Additionally, the dart 'linkedlist' class and its associated 'linkedlistentry' class is truly a pain to deal with. There is little to no documentation on how to properly subclass the LinkedListEntry type! It almost seems to be broken at times. I concede it probably gets used very little though. 

As someone who usually builds his LinkedLists from scratch in c/c++, I have never spent so much time wasted on getting this data structure to work properly.

**Comment by eernstg** [comment]
I can't immediately spot what you are referring to when you say 'the docs', but one thing seems likely (because you say 'deep return' at some point): You might be thinking that the `return` statements will return from the enclosing function for the entire statement, similarly to a non-local return in Smalltalk, Ruby, etc:
```dart
int foo(int i) {
  (int j) { return j; }(i + 1); // Create a function literal (aka lambda) and call it.
  return 0;
}

main() {
  print(foo(41)); // Prints '0', not '42'.
}
```
But the `return` statement in that function literal does _not_ return from `foo`, it just returns from the function literal (and the returned value is discarded because we're just executing an expression and ignoring its value).

In general, `return` always returns from the immediately enclosing function, also when that is a function literal. So what you are actually doing is returning `entry.next` or `entry` to the call site in `forEach`. But `forEach` does not expect any returned values, so that value is just discarded.

There is no support for non-local returns in Dart (but you can throw exceptions, which is also a mechanism that will unwind the stack down to some level, if caught). It rarely comes up, probably because the common Dart libraries and style do not tend to create the need.

If you want to return something from a function which is applied to all elements in a list you probably want to use `map`:
```dart
var xs = [1, 2];
var ys = xs.map((x) => x + 1).toList();
```
where the function literal `(x) => x + 1` returns `x + 1`, and the result is `[2, 3]`.

For the list stuff, I'd suggest that you use a plain `List` rather than a `LinkedList`, which is a vastly more common choice, and also the result you'd get from evaluating literals like `[1, 2]`, unless, of course, you have a very specific reason to insist that it must be a `LinkedList`.

**Comment by lrhn** [comment]
You cannot access "memory" in Dart, just references to objects (well, and typed data lists for numbers).

The overhead of a linked list is usually two extra pointers per entry, but `LinkedList` uses three pointers because each entry has a link to the `LinkedList` object it belongs to.

The memory overhead of a normal growable list (like `[]`) is ~1.3 pointers per element on average while adding elements (because it's using one pointer per actual element, and wasting one pointer per slot in the backing store that isn't used, and on average a quarter of the backing store is empty while you are adding). There is extra time and temporary memory overhead while growing the list, but if you know the list size ahead of time, you can also do better.

For performance, I'd pick a normal list unless you need to add or remove in the middle of the list, then a linked may be more efficient.

**Comment by mkliger11** [comment]
Thanks for your help. I appreciate it.
