### ISSUE TITLE
The analyzer must implement the Dart 2.1 integer literal changes.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#34360]
Analyzer specific issue for #34355.

The analyzer needs to be prepared for the changes. 

Allowing integer literals in a double context should not be hard, since the analyzer already has a type inference implementation which knows about context types, but it needs to not reject integer literals as too large before it knows the context and target platform.

If the analyzer doesn't know the target platform, it cannot reject literals that are valid when compiled to JavaScript, but not when compiled for the VM, but it can choose provide a hint to the user when a literal isn't valid for both. Constant computations may need to be implemented twice, once for each kind of backend, since the validity of code depends on integer semantics.

**Comment by MichaelRFairhurst** [comment]
This is partially landed as of https://dart-review.googlesource.com/c/sdk/+/73841.

https://dart-review.googlesource.com/c/sdk/+/74496 gets us most of the rest of the way there, but that relies on an imperfect hack to work around #33441. I think the plan is to have that hack removed as part of the fix to #33441 and mark this as closed at that point.

**Comment by MichaelRFairhurst** [comment]
https://dart-review.googlesource.com/c/sdk/+/74496

**Comment by jmesserly** [comment]
I think there's a problem, that can be illustrated by this example:
```dart
main() {
  double d = 18446744073709551616;
  print(d);
}
```
Analyzer accepts this, but the IntegerLiteral has null `value`.

As @lrhn noted on the CFE bug: https://github.com/dart-lang/sdk/issues/34357

> The front-end could store the numeric value of integer literals as a BigInt, or it could store both the int64 and double interpretations of the literal, with a null-value when the literal is not valid for that interpretation (and an early error if the value isn't valid for either, like 2^64+1).

... ideally we store enough information for users of the Analyzer tree (such as DDC) to handle this correctly. In the meantime, I should be able to re-parse the token.lexeme, but that doesn't seem ideal? Wouldn't constant computation also need a meaningful value to be stored? Perhaps in a `doubleValue` field or something like that.

There's also a test failure tests/language_2/double_literals/implicit_double_context_test.dart, the status file refers to #34444 but that bug has been closed, so I'm not sure what's going on, but the test does not pass static analysis w/ Analyzer.

Tentatively reopening, since this bug is linked from the main bug #34355 and there still seem to be some issues (alternatively: we could open a new bug, and link to it from there?)

**Comment by jmesserly** [comment]
The analyzer checking issues are fixed in https://dart-review.googlesource.com/c/sdk/+/76343

I didn't change IntegerLiteral, it looks like IntegerLiteralImpl re-parses the literal anyways? Not a big deal but it'd be nice to store the BigInt once. In any case, that's not worth keeping the bug open (IMO) so I'll close it once the fix in my CL lands.
