### ISSUE TITLE
Add a lint: avoid_implementing_value_types

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#34379]
The [`operator==` method states][1]:

> Override this method to specify a different equality relation on a class.
> 
> The overriding method must still be an equivalence relation. That is, it must be:
> 
> * Total: It must return a boolean for all arguments. It should never throw or return null.
> * Reflexive: For all objects o, o == o must be true.
> * Symmetric: For all objects o1 and o2, o1 == o2 and o2 == o1 must either both be true, or both be false.
> * Transitive: For all objects o1, o2, and o3, if o1 == o2 and o2 == o3 are true, then o1 == o3 must be true.

[1]: https://api.dartlang.org/stable/2.0.0/dart-core/Object/operator_equals.html

This is _impossible_ to do properly (in most cases) for classes that override `operator==` (hereby called _value types_ - though I am open to a better name to avoid conflating this with traditional structs or primitives:

```dart
class X {
  final String name;

  const X(this.name);

  @override
  bool operator==(o) => o is X and name == o.name;

  @override
  int get hashCode => name.hashCode;
}

// LINT: avoid_implementing_value_types: X implements equality and should not be implemented.
class Y implements X {
  String get name => 'Y';
}
```

Importantly, this would prevent using a mock-pattern too:

```dart
// LINT: avoid_implementing_value_types: X implements equality and should not be implemented.
class MockX implements X {
  @override
  noSuchMethod(_) => null;
}
```

I believe this is "softer" than a `@doNotMock` annotation, and applies generally more correctly. If we wanted to make it slightly more permissive, we could say it _is_ valid to implement as long as `operator==` is implemented in the sub-class identically to the parent, but that seems hard and rare.

/cc @davidmorgan @srawlins for thoughts.

**Comment by lrhn** [comment]
> This is impossible to do properly (in most cases) for classes that override operator== (hereby called value types - though I am open to a better name to avoid conflating this with traditional structs or primitives:

A better name is probably a good idea because traditional "value types" are defined entirely in terms of their public state, so you *can* implement that equality again.

Subclassing those classes and adding more state is a spearate problem for equality, and not one that has a good solution - or really any at all (the `ColorPoint` problem).

What is good about value types is that that you typically don't need to mock them, you can create them with any necessary state.

The problem you are describing here is more about classes which override `==` based on *private* state. Those are impossile to re-implement symmetrically, and any implementation of the class will likely not even pass equality as an argument to the real `operator==`.

**Comment by matanlurey** [comment]
@lrhn: Even for public state, it is unreasonable to expect users would know to copy-paste the semantics of `operator==` and `get hashCode` when/if they change, which leads me to believe the lint should just cover all cases.
