### ISSUE TITLE
mock_writable_final_private_field_test needs triage

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34377]
Related to #30848.

This test constructs a private Symbol, which throws an exception:

```
const Symbol("_x=");
```

The test needs to be rewritten such that it can pass in analyzer (somehow it does with CFE).

**Comment by lrhn** [comment]
The test is indeed wrong, and it shouldn't pass. 
Even if we allowed `const Symbol("_x=")`, it would not create a symbol for the *private*  setter name (or a name corresponding to any source entity). 

I'm guessing it "works" in the CFE because the CFE defers some constant evaluation to the back-ends, and at least the VM has never enforced input validation on the `Symbol` constructor. The VM should still not create a symbol that is equal to the setter for the private `_x` member.

There is currently no simple way (outside of dart:mirrors) to create a symbol for a private setter name (you can capture it with `noSuchMethod`, but that's it). We should probably extend the syntax to allow `#_x=` as a symbol literal.

There would be a reason to allow `Symbol("_foo")` because `_foo` is a valid non-private *library* name, and there is no other way to create that symbol. We also do not allow that now.
