### ISSUE TITLE
analyzer: no error for overriding a setter with a static function

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34371]
```
class A {
  set foo(x) => null;
}

class B extends A {
  static void foo() => null;
}
```

revealed by method_override7_test/03

**Comment by leafpetersen** [comment]
Is the second `foo` supposed to be static?

**Comment by leafpetersen** [comment]
cc @eernstg can you verify that this test is consistent with the updated override conflict rules?

**Comment by MichaelRFairhurst** [comment]
@leafpetersen yes, thanks, fixed!

**Comment by eernstg** [comment]
In the example as stated now, `B` declares a static method with name `foo` and has an instance setter with basename `foo`, and that's an error:
```
Let $C$ be a class.
It is a compile-time error if $C$ declares a ... method named $n$, and has a getter or a setter with basename $n$.
```
The test marks the declaration of the setter with `//# 03: compile-time error`, so the test is correct. It would actually also be a compile-time error if `B.foo` had been an instance method, but we're OK because that is tested in `method_override8_test.dart`.

I can see that the status entry in `tests/language_2/language_2_analyzer.status` mentions issue 11497 (which is irrelevant, and closed), so it might be useful to change that to 34371.

Btw, the corresponding status entry in `tests/language_2/language_2_kernel.status` does not mention any issue, it's just `MissingCompileTimeError`, but I guess it would confuse matters to say 34371 there (and the front end team might well handle all those missing compile time errors in some other way that I don't know about).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/73301
