### ISSUE TITLE
Analyzer: Support mixins when extending classes that have constructors containing optional arguments

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34375]
As of https://github.com/dart-lang/sdk/commit/63c6851dd01514e9d9e6cb96da0430e15b66d576, this is legal.

```
class Mixin {}

class A {
  A([int x = 4]);
}

class B extends A with Mixin {} // valid
```

Revealed by mixin_forwarding_constructor4_test

It's also allowed by the front-end, and a nuisance for many folks, see #15101

I'm putting this in 2.1 because it should be so so easy to do, and people bump up against it. Seems like low hanging fruit.

**Comment by eernstg** [comment]
Right, as of 63c6851dd01514e9d9e6cb96da0430e15b66d576 there is support for implicitly inducing forwarding constructors of additional forms into a class created by mixin application: The induced constructors can now have optional arguments, and they can be constant:

```dart
class A {
  A([int i]);
  const A.cc();
}

class M {}

class B extends A with M {
  B(int i): super(i);
  B.d(): super();
  const B.cc(): super.cc();
}
```
The constructors in `B` used to be an error because the class `A with M` did not have any constructors (because no constructors were induced when the candidate constructor in the superclass had optional arguments, and the induced ones weren't constant even when they could have been constant). (... OK, maybe the constructor named `B` used to work as well, but its argument wasn't optional, I'm not quite sure how it used to be, but that shouldn't matter so much here ...)

But that spec update doesn't change any rules about explicitly declared constructors, so they will still make it an error to extract a mixin from any given class. In particular, it is an error to extract a mixin from the class `A` [here](https://github.com/dart-lang/sdk/issues/34375#issue-357033563), because `A` contains a constructor declaration (at all, const/not, optionals/not).

**Comment by MichaelRFairhurst** [comment]
Thanks @leafpetersen  and @eernstg, yep, I confused the base class constructor for the mixin constructor. Fixed.
