### ISSUE TITLE
Observatory timeline reports negative "Self Time"

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#34398]
E.g., on a hello world script, try
`out/ReleaseX64/dart --enable-vm-service:54975 --pause_isolates_on_exit --complete_timeline hello.dart`, go to `http://127.0.0.1:54975/#/timeline`. One of the `Dart ThreadPool Worker`s will have `CompileFunctionOptimizedBackground` with a `OptimizationPasses` below it. Clicking on the `OptimizationPasses` - for many, but not for all, or them - shows something like

```
Title | OptimizationPasses
-- | --
Category | Compiler
Start | 196.638 ms
Wall Duration | 6.480 ms
CPU Duration | 6.480 ms
Self Time | -0.257 ms
CPU Self Time | -0.258 ms
```

where we can see that it is so fast that it actually travels back in time...

**Comment by rmacnak-google** [comment]
Timelines in Observatory are visualized by the third-party program called Catapult. Self time is computed by subtracting out the durations of child events, and strange results like negative time are possible due to rounding. This seems especially likely for events like optimization compilation that have a large number of child events for subphases. Also longer CPU duration than wall duration can sometimes occur because the two clocks can't be queried simultaneously.
