### ISSUE TITLE
Feature Request: Add removeFirst method for Lists

### ISSUE THREAD

**Issue by drbcode** [dart-lang/sdk#34421]
Consider a list for example: `List<String> friendIDList`

This is legal:
```dart
friendIDList.removeLast();
```

This is not legal:
```dart
friendIDList.removeFirst();
```

We have to use:
```dart
friendIDList.removeAt(0);
```

Will it be a good idea to implement `removeFirst` method for above data type?

**Comment by lrhn** [comment]
We deliberately didn't add a `removeFirst` method to `List` because it has bad peformance characteristics.
Removing the first element will move every element of the list, whereas `removeLast` is a constant time operation. Giving `removeFirst` equal exposure could, and likely would, encourage users to use it without considering the performance. 
The `removeAt` method spells out that it is potentially inefficient, and it's sufficiently different from `removeLast` that users might read the documentation, where it would be easy to assume that `removeFirst` and `removeLast` are equivalent.

If you want a data structure with efficient `removeFirst`, you should use a `Queue` instead.
