### ISSUE TITLE
Wrong 'This package doesn't depend on' error for example

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#34457]
This package https://github.com/MikeMitterer/dart-l10n-gettext
has two examples: browser + cmdline. Each of these examples has it's own pubspec
and it's own lib.

Both the IDE and `pub publish` give me
```
* line 9, column 1 of example/browser/deploy/main.dart: This package doesn't depend on browser_example.
  import 'package:browser_example/_l10n/messages_all.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 9, column 1 of example/browser/web/main.dart: This package doesn't depend on browser_example.
  import 'package:browser_example/_l10n/messages_all.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 8, column 1 of example/cmdline/bin/cmdline.dart: This package doesn't depend on l10n_exsample_cmdline.
  import 'package:l10n_exsample_cmdline/_l10n/messages_all.dart';
```
This is wrong! 
As always in such cases - dartanalyzer on the cmdline works as expected but the other tools are printing a wrong error message.

And BTW - I forgot to mention: The examples work just fine!

### IDE ----------------------------------------------------------------------------
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.2407.10, built on September 12, 2018
IntelliJ IDEA EAP User
Expiration date: October 12, 2018
JRE: 1.8.0_152-release-1293-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

### OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G22010
Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

### Software installed -----------------------------------------------------------
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
Pub 2.0.0

NPM: 6.2.0

**Comment by natebosch** [comment]
That directory has a well defined convention in pub which should not have its own pubspec.

https://www.dartlang.org/tools/pub/package-layout#examples

Since that directory is treated specially on the pub site and we want to keep giving help where we can we don't have plans to change our validation. You can ignore these validation warnings, or you can rename the directory to one which does not have a convention in pub - you could use `usage_examples` or something if you want that style of example.

If you want to use the pub convention you could remove the nested pubspecs and add the missing dependencies as `dev_dependencies` in the root package's pubspsec.

**Comment by MikeMitterer** [comment]
OMG! I had all my examples in a `samples` folder just because of such problemes. I thought Dart 2 finally solved this and I moved from `samples` to `example`.

Because of those small, but really annoying, things I can't recommend Dart anymore. My Dart-codebase is to big to change but if I could I would change to one of the other competitors.
