### ISSUE TITLE
VM and Flutter CFE targets should only support strong mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#34468]
It turns out we still sometimes use legacy mode - which is unexpected. 

We should add errors when trying to use VmTarget with strongMode set to false.

/cc @alexmarkov @a-siva

**Comment by mit-mit** [comment]
`dart` seems to also still accept the old `--checked` flag

**Comment by dgrove** [comment]
Any further updates, @a-siva @mraleph ?

**Comment by a-siva** [comment]
Yes we still accept '--checked' flag. This essentially equivalent to --enable-asserts.

Did we make a decision on whether we want to deprecate the '--checked' flag ?

**Comment by mit-mit** [comment]
This is being discussed over in https://github.com/dart-lang/sdk/issues/32442

**Comment by mit-mit** [comment]
Opened https://github.com/dart-lang/sdk/issues/34660 to track removing `--checked` from the VM. With that @mraleph I think we can close this issue as the other cleanup was completed, right?

**Comment by mraleph** [comment]
This bug is actually about `strongMode` flag that is used pervasively through front-end and parts of the VM code.

VM also has a `FLAG_strong` which also needs to be removed.

**Comment by kmillikin** [comment]
We will remove it from the CFE.

**Comment by dgrove** [comment]
Adding @peter-ahe-google based on the comments in https://dart-review.googlesource.com/c/sdk/+/78660

**Comment by peter-ahe-google** [comment]
I suggest that we push this to the next release. I'm actively working on this, but there's a lot of places that are still (mostly likely unintentionally) relying on `strongMode = false`. This is my plan:

1. Convert all `strongMode` flags in package:kernel and package:front_end to `legacyMode`.
2. When I don't see `legacyMode: true`, I'll completely remove the flag.
3. Rename "vm_platform_strong.dill" to "vm_platform.dill" (I think this can be done in parallel).
4. Audit all the places that use `legacyMode: true` and either convert them to Dart 2, or delete them (I can ask for help with this).

It's hard form me to estimate the amount of work required before I have a burn-down list. That's because `strongMode: false` is the default in most cases, and not explicit in code. This is why I'm converting all strongMode options to explicitly named arguments so I can search for `legacyMode: true`.

**Comment by dgrove** [comment]
+1 that this is important, but doesn't gate, this release.

**Comment by a-siva** [comment]
I guess I am fine with some internal tests using the legacy mode but we need to make sure that it is not possible for command line Dart users or Flutter/Fuchsia to run the VM in non strong mode.
We are in the process of creating a CL that will remove the following flags from the VM
--strong
--reify_generic_functions
--error_on_bad_override
--enable_type_checks
--error_on_bad_type

**Comment by peter-ahe-google** [comment]
I've created a CL that removes the non-strong VM platform.dill files from the SDK. This should help prevent command-line users from running the VM in non-strong mode.

**Comment by peter-ahe-google** [comment]
This is the CL https://dart-review.googlesource.com/c/sdk/+/79520

**Comment by a-siva** [comment]
When https://dart-review.googlesource.com/c/sdk/+/79431 lands there will be no way to run the VM in non strong mode.

**Comment by a-siva** [comment]
The VM and Flutter only run in strong mode now, it is not possible to use non strong mode.
