### ISSUE TITLE
Unexpected type exception during the assigning Future variable to FutureOr.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34482]
Dart SDK Version: 2.1.0-dev.4.0
OS: Windows 10 (64 bit)

The following test example creates `Future` object and assign it to the variable of `Future ` type in different ways:
``` dart
import "dart:async";

main() {
  Future f = new Future(() => 12345);
  Future<FutureOr> f1 = f;

  FutureOr fo = f;
  f1 = fo;
}
```
Dartanalyzer passes with it without errors.

Dart passes here on the line 5 (`Future<FutureOr> f1 = f;`) and fails on the line 8 (`f1 = fo;`) with the following error:
> Unhandled exception:
> type 'Future<dynamic>' is not a subtype of type 'Future<FutureOr<dynamic>>'
> #0      main (file:///D:/DART/sdk/tests/co19/src/LanguageFeatures/Instantiate-to-bound/Future/test.dart:8:3)
> #1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
> #2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

It seems like such behavior is incorrect: `f0` and `f1` actually points to the same `Future` object, so assigning `f1` to `f` and `fo` should cause the same result.

**Comment by lrhn** [comment]
The static and run-time type of `f` is `Future<dynamic>`.
The static type of `f1` is `Future<FutureOr<dynamic>>`.
The static type of `fo` is `FutureOr<dynamic>`.

The assignment of `fo` to `f1` is statically valid because `FutureOr<dyamic>` is a super-type of `Future<FutureOr<dynamic>>` (most easily recognized by seeing that the type `Future<dynamic>` is between the two and obviously related to them). 
The assignment is a *down-cast* (assigning from super-type to sub-type), so at run-time, an extra check is added to check that the *value* has type `Future<FutureOr<dynamic>>`. 
Since the value has type `Future<dynamic>`, that check *should succeed* (like it did in line five). The VM fails it for some reason. The program runs without problem in dart2js.

So, definitely a bug.

**Comment by mraleph** [comment]
Seems related to the subtype relationship implementation in the VM. Tentatively assigning to @crelier

**Comment by crelier** [comment]
Thanks for the report. A fix is on its way.
