### ISSUE TITLE
Behaviour of "Rename" on a constructor call is confusing

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34484]
I've always thought this was a little strange but figured it was by design and didn't raise it. However it's been mentioned to me a couple of times by VS Code users now, so I thought it may be worth discussing.

Given the code:

```dart
class A {
}

main2() {
  var a = new A();
}
```

If you invoke `Rename` on `new A();`, it'll rename the default constructor (which doesn't exist, so it'll create it) to the name provided:

```dart
class A {
  A.newName();
}

main2() {
  var a = new A.newName();
}
```

I can see some logic here but it doesn't seem to be the behaviour users expect (especially in the case where there was no existing default constructor, though even if there was it still feels weird to me). I think most people are expecting this to rename the class.

Similarly, if the call had been `new A.something()` I would expect a rename on the `A` to rename the class and a rename on `something` to rename the constructor but the whole range renames the constructor.

In IntelliJ I think it's a little more obvious what'll be renamed because there's a text description, though in VS Code we don't get to show anything except the rename box (pre-filled with the old name - which in the case from above is blank, though I don't think that's obvious enough to indicate it's not renaming the class):

<img width="355" alt="screen shot 2018-09-17 at 8 00 07 am" src="https://user-images.githubusercontent.com/1078012/45609393-b95f1880-ba4f-11e8-8c08-c555006dc171.png">

I don't know if this has come up before (outside of VS Code) or whether anyone feels strongly about the current behaviour and/or changing it?

(cc @bwilkerson @scheglov)

**Comment by bwilkerson** [comment]
I don't know the "right" answer here, but I've looped in Tao in the hope that he might be able to provide additional insight (when he returns next week).

What I do know is that it's a tricky question. While I completely understand why users are confused, I can give you some of the motivation for why it is the way it currently is. Consider the following:
```
class C {}
void f(C c) {}
void g() {
  f(null);
}
```
If the user selects the first `f` and asks to rename, we rename the function being declared. If the user selects the second `f`, we rename the function being referenced. If the user selects the first `C`, we rename the class being declared. If the user selects the second `C`, we rename the class being referenced.

There's a pattern, and we thought it would be less confusing to follow the pattern. The problem is that the pattern seems to break down a bit in most users' minds. The spec is clear:

> A _constructor name_ always begins with the name of its immediately enclosing class, and may optionally be followed by a dot and an identifier _id_.

But I suspect that using the same name for both the class and the default constructor throws people off.

We decided to be (mostly) true to the spec. So, given
```
class A {
  A();
  A.named();
}

main() {
  var a1 = new A();
  var a2 = new A.named();
}
```
If the user selects the second `A` they are selecting the name of the constructor, so we rename the constructor. If they select (any portion of) the first `A.named`, we once again rename the constructor being declared. Similarly, if the user selects either the `A` or `A.named` in the body of `main`, then we rename the constructor being referenced.

I said "mostly" above, because we don't actually rename the whole constructor, only the identifier following the period. We thought that most users wouldn't expect "rename this constructor" to mean "and potentially rename the class as well". We could have done that. The rename dialog for `A.named` could initially contain "A.named", and if the user replaced it with "B.foo" we could rename the class `A` to `B`.

It wouldn't be completely inconsistent. When the user renames a class we rename the constructors. If we didn't, they would no longer be constructors. But, as I said, it's hard to know which is the best UX in this case.

**Comment by timsneath** [comment]
I hit this issue and assumed it was a bug at first. Screen capture of how the current UX operates for those who are interested here:
https://drive.google.com/file/d/16mABrmfBTsCqmOUvy8WyO1Oih5t9zk0e/view?usp=sharing

**Comment by DanTup** [comment]
> The rename dialog for `A.named` could initially contain "A.named", and if the user replaced it with "B.foo" we could rename the class `A` to `B`.

Although it seems slightly weird, I think that would be less weird to me than what's reported above - as that way the user could rename just the class (eg. changing `A` to `B`) or give the constructor a name (eg. change `A` to `A.something`).

That said, I do think treating the classes name as the "class name" and providing two separate renames for the class part and constructor identifier. I understand it would make changing a constructor from the default to a named one (or back) wouldn't be as simple then, but it does "feel" more natural to me (to me, there's not a massive difference between a named constructor and a static method, and this is how static methods behave).

**Comment by bwilkerson** [comment]
> That said, I do think treating the classes name as the "class name" and providing two separate renames for the class part and constructor identifier.

Just to clarify, I think you're suggesting that selecting `A` would rename the class and selecting `named` would rename the constructor.

> I understand it would make changing a constructor from the default to a named one (or back) wouldn't be as simple then, ...

We could make an empty name mean to rename a named constructor to the default constructor (which might not be obvious), but I think it would be impossible to go the other way because there's no name to select.

**Comment by DanTup** [comment]
>  I think you're suggesting that selecting A would rename the class and selecting named would rename the constructor.

Yeah, that's correct. So in the code:

```
var a = new Class.fromThing()
            ^1  ^2^3      ^4
```

Invoking the rename between ^1 and ^2 would pre-populate with `Class` and rename the class, and from ^3 to ^4 would populate with `fromThing` and change the constructor's identifier. I think this is what happens if you dropped `new` and make `fromThing` a static method (and I think from the outside, static methods and named constructors seem very similar).

> We could make an empty name mean to rename a named constructor to the default constructor

Yeah, that sounds like a good idea too 👍

**Comment by scheglov** [comment]
```
var a = new Class.fromThing()
        ^0  ^1  ^2^3      ^4
```

What do you think about ^0?
Class? Constructor? No-op?

**Comment by DanTup** [comment]
I'd probably say a no-op. I don't feel strongly about it though - if you hit rename on `new` and it was pre-populate with `Class` then I think it's still clear what's happening. The difference in the original case here is that for the default constructor the box is empty and it's easy for the user to assume they're supposed to type a new class name. When the box is populated already, there's much less room for confusion.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/75380

**Comment by DanTup** [comment]
Thanks! 👍
