### ISSUE TITLE
Dart VM scripts take 14s+ on starting when package:build* imports present

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/sdk#34487]
Dart VM version: **2.1.0-dev.4.0** (same with stable 2.0.0 version) on Kubuntu Linux 18.04 64bits

This is the ad-hoc script made for testing this issue:
```dart
import 'package:path/path.dart'; //with this import it takes 2 seconds
import 'package:build/build.dart'; //with this one, 14s

main(args) {
  print("time!");
}
```
This are it's executions:

> $ time dart bin/benchmark.dart #with just package:path
> time!
> 
> real    0m1,860s
> user    0m2,359s
> sys     0m0,210s

> $ time dart bin/benchmark.dart #with package:build added
> time!
> 
> real    0m13,680s
> user    0m19,956s
> sys     0m0,856s

On pubspec.yaml the only build dependency I have is:

> build_runner: '^0.9.0'

PD: Had same issue with another package before, debugging it in Observatory showed that 95% of the time was taken by the VM in "pthread_cond_wait" function, however I don't remember having it import package:build*

**Comment by matanlurey** [comment]
I am not sure there is specific work to do here - the new workflow for Dart 2 is that frequently used scripts should use [snapshots](https://github.com/dart-lang/sdk/wiki/Snapshots) and there is a tool, [`build_vm_compilers`](https://pub.dartlang.org/packages/build_vm_compilers) for an incremental build story.

**Comment by natebosch** [comment]
I suspect the main thing is the expanded size of the transitive imports. `package:path` is very small and has no other dependencies. `package:build` has other transitive dependencies - the heaviest is probably `package:analyzer` so there is a lot more files the VM is reading, parsing, and resolving.

You'll probably see similar behavior importing `package:test`.

All of this is fallout of the Dart 2 VM being slower to run from source than the Dart 1 VM. As @matanlurey pointed out you can take snapshots for faster startup, or try `build_vm_compilers` to see if it helps the incremental workflow.

I'm going to close this since the start-from-source slowdown is a known issue without any immediate resolution. Feel free to file issues over at https://github.com/dart-lang/build if you have difficulty using `build_vm_compilers`.
