### ISSUE TITLE
pkg/meta: using a function with a @required parameter as tear-off does not warn about missing required parameter

### ISSUE THREAD

**Issue by denniskaselow** [dart-lang/sdk#34491]
Dart VM version: 2.1.0-dev.4.0 (Fri Sep 7 16:44:38 2018 +0200) on "windows_x64"

```dart
import 'package:meta/meta.dart';

void main() {
  // analyzer info: The parameter 'paramB' is required.
  doStuff(1);
  // nothing wrong here according to the analyzer
  // but I would expect the analyzer to inform me about the missing parameter
  [1].forEach(doStuff);
}

void doStuff(int paramA, {@required bool paramB}) {}
```

**Comment by matanlurey** [comment]
My guess (?) is this is WAI (working-as-intended), since `@required` is not a language feature, and the tools are not tracking the intention of this annotation - you see some of the discussion at https://github.com/dart-lang/language/issues/15 for details.

For example, what about the following cases:
* Is `@required` applicable to function types `void Function({@required String name})`?
* Is `@required` inherited across `extends`/`implements`/`with`?

One silly idea to move forward is to introduce a lint, i.e. `avoid_tearoff_required`, for the above case.

/cc @Hixie @bwilkerson @munificent

**Comment by munificent** [comment]
Yeah, this is a good example of why relying on metadata annotations for features like this doesn't give as nice of an experience as baking the feature fully into the language.

Because `@required` isn't part of the language, it's not part of the type system. Even if analyzer was changed to statically propagate the `@required` through tear-offs and function types, it's still not able to do that to the *runtime* type of the function, so you'll still be able to get into bad situations.

**Comment by Hixie** [comment]
What bad situations? `@required` is only for static analysis, it shouldn't do anything at runtime.

**Comment by matanlurey** [comment]
@Hixie:

Here is one:

```dart
import 'package:meta/meta.dart';

class A {
  void doThing() => print('doThing()');
}

class B {
  void doThing({@required String name}) => print('doThing($name)');
}

void main() {
  B b = B();
  A a = b;
  // Required not linted... resulting in:
  // Runtime error: `name` is null.
  a.doThing();
}
```

**Comment by eernstg** [comment]
The grammar does not currently allow metadata on the parameter types in a "new style" function type like `void Function({@required String name})`, but I don't see any particular difficulties in adding support for that.

However, it may be somewhat tricky to support that with an analysis which is an enhanced version of the one we have currently to use this kind of information on function types. We would flag certain casts as violations of "requiredness preservation":

```dart
void foo1({int i}) {}
void foo2({@required int i}) {}

void Function({@required int i}) f1;
void Function({int i}) f2;
void Function() f3;

main() {
  f1 = foo1; // OK, requiredness can be overestimated, no problem.
  f2 = foo1; // OK, extended type unchanged.
  f3 = foo1; // OK, regular function type upcast.
  f1 = foo2; // OK, extended type unchanged.
  f2 = foo2; // Flagged as bad, forgets requiredness.
  f3 = foo2; // Flagged as bad, forgets required parameter.
}
```
It may be surprising that we are flagging otherwise always-ok transitions like upcasts as bad, and there may be some tricky corners around type variables:

```dart

Y foo<X extends Y, Y>(X x) => x;

main() {
  Function() f = foo(({@required int i}) => i); // Bad!
}
```
It is surprising that the invocation of `foo` is "bad", because the declaration seems safe (it is a plain upcast to return `x` because `X extends Y`).

We can't see at the call site that the execution of `foo` will perform an upcast from the first to the second type argument (so it will be overkill to flag all such generic function calls), and we can't see in the implementation that it is unsafe to perform that upcast (so it will be overkill to flag all such function declarations). But that upcast for this call site will be an upcast from `Function({@required int i})` to `Function()`, and that would allow us to "forget a required parameter".

There may be an easy and elegant solution, but it hasn't dawned upon me yet. ;-)

PS: I don't think this difficulty has anything to do with being part of the language or not, there's nothing stopping the linter from knowing all the things that the type checker knows, and then some, and there's nothing (other than convention) stopping the type checker from seeing metadata.

**Comment by eernstg** [comment]
Ah, I forgot this: The relationship between `A.doThing` and `B.doThing` [here](https://github.com/dart-lang/sdk/issues/34491#issuecomment-422097289) is exactly one of those situations involving an upcast: It is generally considered safe to access a `B` using the static type `A`, but when some upcasts are bad (like that from `void Function({@required String name})` to `void Function()`) we make standard OO subsumption a problem.

**Comment by Hixie** [comment]
@matanlurey I assume B extends A? I don't understand why that's a runtime error caused by `@required`. It's exactly what would happen if the annotation was absent. Fundamentally that code is bogus, anyway, and ideally would be linted by something else (the subclass is changing the API in ways that aren't valid in reasonable OOP).

**Comment by srawlins** [comment]
`@required` is being replaced by `required`, so no further work will be done to support `@required`.

**Comment by denniskaselow** [comment]
I just tested with `required` instead of `@required` and it's working correctly.
