### ISSUE TITLE
dartdevk: eliminate covariance checks on private fields/members

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#34531]
split from https://github.com/dart-lang/sdk/issues/31116

We need to eliminate covariance checks where possible, for example:
```dart
class C<T> {
  T _x;
  m(T x) {
    _x = x;
  }
}
main() {
  C<int>().m(42);
}
```
We should not create a JS property for `_x` here.

In DDC+Analyzer this is implemented mostly in Analyzer's checker.dart, it should be easy to port this to Kernel.

**Comment by jmesserly** [comment]
I should note: this is useful for other types of private members too, so if we can do it then we should. I can't recall why Analyzer only handles fields (it may have just been simplicity).

**Comment by eernstg** [comment]
A kind of types that is likely to be relevant for these considerations are _path-dependent types_ (introduced [here](https://dl.acm.org/citation.cfm?id=679845) and [here](https://dl.acm.org/citation.cfm?id=680013), proven sound [here](https://dl.acm.org/citation.cfm?id=1111062), adopted for Scala, e.g., as discussed in the book ['Programming Scala'](https://www.oreilly.com/library/view/programming-scala/9780596801908/ch12s07.html), studied [here](http://lampwww.epfl.ch/~amin/dot/fpdt.pdf), etc), and the most tricky part is that they require stable denotations of objects. For instance, the following is safe even though `X` is a type parameter of a class and hence treated covariantly:
```dart
class C<X> {
  X x1, x2;
  swap() {
    // No covariance checks needed for any of these assignments.
    X tmp = x1;
    x1 = x2;
    x2 = tmp;
  }
}
```
This is safe because all the occurrences of "the type `X`" are based on the actual value of the type variable `X` of `this`. We can maintain safety for other objects than `this` as long as there's no mutation:
```dart
class D<X> {
  final C<X> c = C<X>();
  swap() { X tmp = c.x1; c.x1 = c.x2; c.x2 = tmp; }
}
```
However, we're kind of lucky here because we know that `c.X == this.X`. In the general case we wouldn't be able to declare a local variable like `tmp` with the appropriate type:
```dart
class D2<X> {
  final C<X> c = e; // Some complex computation.
  halfSwap() { c.x1 = c.x2; }
}
```
We cannot guarantee `c.X == this.X`, only `c.X <: this.X`, which means that `X tmp = c.x1` would be safe, but `c.x2 = tmp;` would be a downcast (due to covariance, so we're back where it is not safe to eliminate the associated covariance checks).

So if we want to take this beyond `this` then we'd need to keep an eye on immutability and exact types, and even in the case where we have the former and not the latter, something like `halfSwap` is still safe. We can't assume that the `X` of one object is the same as the `X` of any other object with the same static type, but we may have weaker properties like subtyping.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/79432
