### ISSUE TITLE
CompilationUnit.toSource() - removes comments

### ISSUE THREAD

**Issue by DisDis** [dart-lang/sdk#34539]
* Dart SDK Version (`dart --version`)
2.0 Stable
analyzer: 0.32.5
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Console App

If the code contains comments, then when Compilation Unit.toSource() is called, they are removed

```
   var source = '''
  /* Comment1 */
  /// Comment2 
  class C1 { 
  // Comment 3
  }''';
  var ast = parseCompilationUnit(source);
  print('Equal: ${source == ast.toSource()}');
  print('Orig: "${source}"');
  print('Ast:  "${ast.toSource()}"');
```

Output:
```
Equal: false
Orig: "  /* Comment1 */
  /// Comment2 
  class C1 { 
  // Comment 3
  }"
Ast:  "class C1 {}"
```

**Comment by bwilkerson** [comment]
That is true. The method `toSource` probably wasn't designed for your use case. Can you tell me what it is that you're trying to do? I might be able to suggest an alternative.

**Comment by DisDis** [comment]
@bwilkerson I want to split the package into several packages. I need to patch the import/export section in dart files.
Code: https://github.com/DisDis/code_health/blob/code_transfer/lib/src/code_transfer/actions.dart#L52

**Comment by bwilkerson** [comment]
Ok. The recommended / supported way to modify source code is by modifying the content of the file directly (string manipulation). The analyzer package doesn't support code modification via the AST structure.

The AST nodes carry position information (offset and length), so it's easy to know which range of characters to replace. The only "trick" is to edit the file from largest offset to smallest (by iterating over the directives in reverse order) so that each edit does not invalid the offsets for the next edit.

**Comment by DisDis** [comment]
@bwilkerson Thanks for the help.
