### ISSUE TITLE
Different results for same computation on doubles

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/sdk#34537]
I have a function which does some algorithmic stuff, and then I have an assert to check whether the results are correct. Sometimes, the assert get triggered, on very small difference. Why is there this difference?

```
expect: 30.563099922634418
actual: 30.56309992263442
```

Most of the time, the result is correct!

**Comment by lrhn** [comment]
Can you post the "algorithmic stuff" and the input values? 
If the function is completely deterministic, then there shouldn't be any difference, but if the operations may occur in a different order (perhaps because the input is a `HashSet` of values, which won't necessarily iterate in the same order every time), then rounding differences may accumulate to the point where they are visible.

Obviously, there is also the option of CPU bugs, or unoptimized code going to C code and accidentally triggering 80-bit precision on some operations. It's impossible to say without knowing the code and data.

**Comment by MohiuddinM** [comment]
```
import 'dart:math';

double func(double val, double exp, int i) {
  List<double> prevVals = [.1, .2, .3, .4, .5, .6, .7, .8, .9];
  double rand = Random().nextDouble();

  double ans = prevVals.map((prevVal) => -(prevVal * val) / rand).toList().last;
  ans *= rand;

  if (ans != -exp) print('mismatch at $i: ans: $ans, exp: ${-exp}');
  return ans;
}

void main() {
  double val = Random().nextDouble();
  double exp = .9 * val;
  for (int i = 0; i < 100; i++) func(val, exp, i);
}
```

Example Output: 
```
mismatch at 8: ans: -0.7216616054026102, exp: -0.72166160540261
mismatch at 13: ans: -0.7216616054026102, exp: -0.72166160540261
mismatch at 39: ans: -0.7216616054026102, exp: -0.72166160540261
mismatch at 55: ans: -0.7216616054026102, exp: -0.72166160540261
mismatch at 70: ans: -0.7216616054026099, exp: -0.72166160540261
mismatch at 88: ans: -0.7216616054026099, exp: -0.72166160540261
mismatch at 93: ans: -0.7216616054026102, exp: -0.72166160540261
```

**Comment by MohiuddinM** [comment]
Tested on:
Dart 2.0 (stable) x64 Windows 10

**Comment by mraleph** [comment]
@MohiuddinM you can't expect that `(-(prevVal * val) / rand) * rand` is equal to `-(prevVal * val)` when using floating point arithmetic.

This is working as expected.

**Comment by MohiuddinM** [comment]
@mraleph The above is not the original code. But maybe its the same issue with original code. Can you please guide why this is happening? And what should I do to avoid the assert getting triggered?

**Comment by lrhn** [comment]
The issue here is that you expect: `(-(0.9 * val) / rand) * rand` to equal `-(0.9 * val)`. Double numbers to not promise that. Division by a double might lose precision, and multiplying that double value again then gives a different result than what you started with.

The value `0.9` is not precisely representable as a double. The actual value is 0.90000000000000002220446049250313080847263336181640625.
Because of that, `-(0.9 * val)` most likely uses all 53 bits of precision of the double for its actual value. When you then divide that by some random number which is not a power of 2, you will lose precision, and multiplying by the random number again most likely gives a different result.
