### ISSUE TITLE
Analyzer treats `mixin` as concrete class

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34566]
### What I was doing

I expect the following mixin to be valid, but instead:

```dart
mixin A {
  int get foo;
  //      ^
  //      "'foo' must have a method body because 'A' isn't abstract."
}
```

### Versions

- Flutter SDK 0.4.3-pre.1162
- Visual Studio Code 1.27.1
- Dart Code 2.18.0

@stereotype441 @JekCharlsonYu @leafpetersen

**Comment by scheglov** [comment]
[The spec](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) says "A mixin cannot be marked as abstract. All mixins are effectively abstract because they don't need to implement the members of the required superclass types."  But, it also says "We could say that a mixin must implement all other members than the ones declared by the required superclass types, and then allow the declaration to be marked as abstract if it doesn't."

So, my understanding is that you are not allowed to declare abstract members in mixin declarations.

@eernstg Can you please confirm this, or clarify the mixin spec to make it clear that it is allowed to declare abstract members in mixins?

**Comment by scheglov** [comment]
OTOH, mixins are equivalent to abstract classes.
So, they *are* abstract.

**Comment by lrhn** [comment]
Yes, mixins can declare abstract members. In that regard, they are equivalent-ish to abstract classes in that they don't need to have an implementation of their interface.

When we say that the mixin cannot be marked as `abstract`, it's intended to convey that it wouldn't make a difference if you did mark it abstract. I can see that it might need some elaboration.

(Concrete classes can declare abstract members too, as long as there is a valid implementation in a super-class).

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/76303

**Comment by yjbanov** [comment]
> Concrete classes can declare abstract members too, as long as there is a valid implementation in a super-class

Wow! Mind blown 💥👨💥

Thanks for fixing this!
