### ISSUE TITLE
unnecessary_parenthesis confused by await

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#34597]
```dart
import 'dart:async';

void test(Future<int> f) async {
  await (f..timeout(const Duration(seconds: 1), onTimeout: () { print('took longer than one second'); }));
  print('finished');
}

void main() {
  test(Completer<int>().future);
}
```

->

```
   info • Unnecessary parenthesis can be removed • test.dart:4:9 • unnecessary_parenthesis
```

...but removing the parentheses changes the logic, because `await` binds more tightly than `..`.

**Comment by a14n** [comment]
@eernstg @lrhn lookink at [the part in Dart spec about precedence](https://github.com/dart-lang/sdk/blob/7c54fab8a5736343aa6bef1f45c2e1c5152a94b4/docs/language/dartLangSpec.tex#L11424-L11461) I don't see any reference to `await`. Where should it be in this list?

**Comment by lrhn** [comment]
An `await` is a unary prefix operator, it binds exactly as tightly as `!`, `~`, and unary `-`.
That's a good precedence for a prefix operator, since it allows you to write `await object.method()` without having to parenthesize the `(object.method())`.

It is, on the other hand, often inconvenient if you want to chain a sequence of synchronous and asynchronous operations. It would have been more convenient if the await was a postfix operator in those cases.

As a side note, I think the code above should trigger the "unawaited future" lint. The future returned by `f.timeout` is never available, and therefore certainly never awaited. I guess the lint doesn't trigger because there is no expression actually *evaluating to* that future, but if `f` completes with an error within one second, that error *will* become an unhandled error in the (unavailable) future.

**Comment by lrhn** [comment]
An `await` is a unary prefix operator, it binds exactly as tightly as `!`, `~`, and unary `-`.
That's a good precedence for a prefix operator, since it allows you to write `await object.method()` without having to parenthesize the `(object.method())`.

It is, on the other hand, often inconvenient if you want to chain a sequence of synchronous and asynchronous operations. It would have been more convenient if the await was a postfix operator in those cases.

As a side note, I think the code above should trigger the "unawaited future" lint. The future returned by `f.timeout` is never available, and therefore certainly never awaited. I guess the lint doesn't trigger because there is no expression actually *evaluating to* that future, but if `f` completes with an error within one second, that error *will* become an unhandled error in the (unavailable) future.

**Comment by eernstg** [comment]
@a14n, we should probably add `await` to the table you mention; but that table is not normative, so it is in any case the grammar that counts. As Lasse indicated, `await` is treated the same as several other prefix operators:

```
unaryExpression
    :    (prefixOperator ~SUPER) => prefixOperator unaryExpression
    |    (awaitExpression) => awaitExpression
    |    postfixExpression
    |    (minusOperator | tildeOperator) SUPER
    |    incrementOperator assignableExpression;

awaitExpression
    :    AWAIT unaryExpression;
```

Checking the grammar, when looking at `await`, we could expect a `unaryExpression` and parse it as an `awaitExpression`; but we could also choose `postfixExpression`, then `primary selector`, then `identifier argumentPart`, etc, in cases like the following
```dart
await(
  f..timeout(const Duration(seconds: 1),
  onTimeout: () { print('took longer than one second'); }),
);
```
... hehe ... which will parse the whole statement as an invocation of the function `await`, which works in a lot of places because `await` is only parsed as a keyword in `async` and `async*` functions. ;-)

So the parsing process does not allow us to use precedence as the complete truth, and we have never studied in complete detail to which extent it would be possible to prove that there is a precise notion of precedence which would faithfully correspond to the actual grammar, and in that case what the table would look like.

Maybe we should write it twice above the table that it isn't normative, or maybe we should delete the table entirely. ;-)

**Comment by a14n** [comment]
Thanks for explanations.

I usually use [the Operators section on _language tour_](https://www.dartlang.org/guides/language/language-tour#operators) but `await` is not mentioned. So I ended up in the spec.

I think it is worth to have such a table of precedence because most of developers will prefer to have a quick summary instead of analysing a full grammar.

**Comment by Hixie** [comment]
> if `f` completes with an error within one second, that error _will_ become an unhandled error in the (unavailable) future

Interesting... why? Won't the "await" forward it to the future returned by "test"? (There is a separate lint that complains about "test" itself returning void such that its Future will always be ignored, FWIW.)
