### ISSUE TITLE
Flutter and VM behaving differently on data reception

### ISSUE THREAD

**Issue by shamblett** [dart-lang/sdk#34591]
I have this [issue](https://github.com/shamblett/mqtt_client/issues/34) raised on one of my packages. Basically its saying when data is received from, in this case an MQTT broker, Dart on the VM is OK no matter what the data size, but flutter seems to have a problem in that it raises exceptions when processing the data.

If there is a fix for this then I guess its in the flutter runtime or maybe in typed_data, i..e at a lower level than a package.

**Comment by matanlurey** [comment]
I would continue to raise this issue https://github.com/shamblett/mqtt_client/issues/34 or on the Flutter repository (https://github.com/flutter/flutter/issues/new), there isn't much actionable here.

**Comment by zoechi** [comment]
Moved to https://github.com/flutter/flutter/issues/22657

**Comment by zoechi** [comment]
@mraleph should we close https://github.com/flutter/flutter/issues/22657 ?
I don't see the benefit of tracking it twice.

**Comment by mraleph** [comment]
There is absolutely no reason to file this over at Flutter because both execution and networking are handled by the Dart VM. So it's going to be exactly the same people looking at the problem no matter where you file the bug. 

@shamblett we can look into the issue if you have a standalone reproduction e.g. a Flutter project that can be cloned and run on a device or in the emulator to reproduce the problem. 

Without reproduction we can't really do much, unfortunately. 

@zanderso Zach, do you by chance know if dart:io has any issues with networking on Android that can lead to message truncation? 

@zoechi please close that one.

**Comment by shamblett** [comment]
I don't have a flutter environment but the guys reporting this do, as you can see from the issue @cbenhagen is using flutter on android, @Smartauto and @josvos also have environments, I think one is emulated and they all see the same thing, suggest you ask one of those for an environment set up.

**Comment by mraleph** [comment]
@shamblett from my reading of the comments on the issue it actually looks like the issue is resolved (at least for @josvos, and seems for @Smartauto to but they are just not testing it correctly). So I am going to go ahead and mark this issue as resolved too.
