### ISSUE TITLE
Wrong generic type of list if instance is created by class mirror

### ISSUE THREAD

**Issue by Devtronic** [dart-lang/sdk#34607]
`Dart VM version: 2.1.0-dev.0.0.flutter-be6309690f (Fri Aug 10 06:04:10 2018 +0000) on "windows_x64"`

Is it possible to create a generic list by reflection?

```dart

void main() {
  var originalList = new List<int>();
  var createdList = createNewList<List<int>>();

  print(originalList.runtimeType); // List<int> 
  print(createdList.runtimeType);  // List<dynamic>, should be: List<int>
}

List createNewList<T>() {
  var clsMirror = reflectClass(T);
  var instanceMirror = clsMirror.newInstance(const Symbol(''), []);

  // do something internal with the list....

  return instanceMirror.reflectee;
}

```

**Comment by matanlurey** [comment]
You will need to use [`reflectType`](https://api.dartlang.org/stable/2.0.0/dart-mirrors/reflectType.html), not `reflectClass`, in order to refer to a class with generic type arguments. For example (I have not tested this, but I know something roughly like this works):

```dart
import 'dart:mirrors';

List<T> createNewList<T>() {
  var clsMirror = reflectType(List, [T]) as ClassMirror;
  // ... everything else you have ...
}
```

(In the future, something like Stack Overflow is highly preferred for general Q&A. Thanks!)
