### ISSUE TITLE
Dart does not throw exception when instantiate variable of A<X extends A<X>> class

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34623]
Dart SDK Version: 2.1.0-dev.6.0
OS: Windows 10 (64 bit)

The following sample code tries to assign a variables of different types to [A<X extends A<X>>] variable:

``` dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

class A<X extends A<X>> {}

main() {
  A source1;
  var fsource1 = toF(source1);
  F<A<dynamic>> target1 = fsource1;
  F<A<A<dynamic>>> target2 = fsource1;
  F<A<A<A<dynamic>>>> target3 = fsource1;
  F<A<A<A<A<dynamic>>>>> target4 = fsource1;
}
```
Here  `F<A<A<dynamic>>> target2 = fsource1;` is a correct result of instantiate-to-bounds algorythm and should pass. All the other cases should fail.

However, this is not so:
Analyzer fails with all of them including correct case (`F<A<A<dynamic>>>`) - there is existing issue #34560.

At the same time, nothing is rejected in runtime - dart just passes here.

Actually, it should pass with the  `F<A<A<dynamic>>> target2 = fsource1;` case and reject all the others with exception.

**Comment by eernstg** [comment]
I just double-checked the analyzer (because I knew that #34560 had been closed), and we do indeed get error messages for some bound violations that should be accepted because they occur in a super-bounded type. So I added a comment on #34560 that the issue is yet not fully resolved.

However, [the response](https://github.com/dart-lang/sdk/issues/34560#issuecomment-425828848) includes `invalid_assignment` errors for lines 11, 13, and 14 (not 12), so the assignability checks in the analyzer seem to be correct.

I added labels to reflect the fact that this issue is then concerned with the front end bug of not detecting the compile-time errors in the declarations of `targetN` for `N` in 1, 3, 4.
