### ISSUE TITLE
dart should have a `dart:crypto` library

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#34659]
Dart should have a built-in package providing cryptographic algorithms.
This could be modeled after the [golang "crypto" package](https://golang.org/pkg/crypto/), [node.js crypto module](https://nodejs.org/api/crypto.html), [Web Cryptography](https://www.w3.org/TR/WebCryptoAPI/), or similar.

The reason for this is simple:
 * the package eco-system will need cryptography (for calling GCP, AWS, Azure)
 * rolling your own crypto invites vunerabilites, side-channel attacks
   (A good JIT could in theory offer additional side-channels)
 
On the technical it's worth noting that:
 * dart-sdk already links statically with boringSSL for TLS
 * there is _currently_ no good way to distribute binary modules on pub

By supporting TLS dart-sdk already comes with a lot of cryptography, we just need to expose more low-level algorithms.

note: I'm aware of [package:crypto](https://pub.dartlang.org/packages/crypto), but it is missing a lot of algorithms. For example [googleapis_auth](https://pub.dartlang.org/packages/googleapis_auth) is rolling it's own [RSA implementation](https://github.com/dart-lang/googleapis_auth/tree/7c8f113f34ecda7a8264a2b679bf6385c23e26ad/lib/src/crypto).

**Comment by cedx** [comment]
It would be also cool if we could use the [Crypto.subtle](https://developer.mozilla.org/fr/docs/Web/API/Crypto/subtle) APIs from `dart:html`. Currently [the API exposed by Dart](https://api.dartlang.org/stable/2.4.0/dart-html/Crypto/subtle.html) is unusable.

**Comment by knopp** [comment]
This needs to get higher priority. There is no way any dart AES implementation is going to be on par with handwritten assembly from boringssl. Also it's very strange and potentially unsafe to have to duplicate basic crypto algorithm when dart already ships with boringssl.
Please expose this, perhaps with API similar to Crypto.subtle, in that case you can have parity with dartjs.

**Comment by terrier989** [comment]
A provisional solution could be exporting (prefixed) BoringSSL functions as undocumented C functions that may be removed in any future version. Cryptographic packages could then look up the symbols with _dart:ffi_:
```
DynamicLibrary.executable().lookup("unstable_boringssl_ED25519_sign");
```
Whenever Dart/Flutter or BoringSSL decides to stop supporting something, a package could fall back to an implementation written in Dart.

Developers who want to use _crypto.subtle_ in browsers may find [package:cryptography](https://pub.dev/packages/cryptography) useful.

**Comment by edyu** [comment]
I just want to say I agree with everything that was said and yes [package:cryptography](https://pub.dev/packages/cryptography) is very helpful but would be nice to have a real dart:crypto library.

**Comment by jonasfj** [comment]
I started drafting what I thought would be a good crypto library for Dart. But retaining all the BoringSSL symbols I would have needed in the Flutter SDK would have grown the SDK size by a few hundred KBs... Which is kind of a problem at the moment, hence, I don't think this is going to happen anytime soon.

My humble attempt at a crypto library became [package:webcrypto](https://pub.dev/packages/webcrypto), which is just a side-project, still under active development. It uses `dart:ffi`+BoringSSL or `crypto.subtle` and does not attempt to roll a Dart implementation of any primitives.

In any case, it's also nice to see pure-Dart implementations like `package:cryptography`, having portable cryptography is cool :D

**Comment by mit-mit** [comment]
Closing this now that we have https://pub.dev/packages/webcrypto in a pretty complete state.

**Comment by markg85** [comment]
Please reopen this issue.

While a library that mimics the web is, probably, useful to some. It's useless to other and rather limited.
My case is cryptography using ed25519 and x25519, neither are supported in the web crypto ecosystem nor in that dart library. 

To make it more annoying, new web features would have to be picked up in that library too.
x25519 is, since a few weeks, supported in chrome: https://caniuse.com/?search=x25519
ed25519 is experimental: https://caniuse.com/?search=ed25519

A cryptographic journey i just went on was using both ed25519 and x25519 for E2EE. I loaded PEM keys from file and must have the ability to export a key in JWK (not JWT).
* [Webcrypto](https://pub.dev/documentation/webcrypto/latest/search.html?q=pem): not possible, can't read PEM
* [cryptography](https://pub.dev/packages/cryptography) also can't read PEM nor can it output JWK (nor read). It also seems to be abandoned though it's [fork](https://github.com/emz-hanauer/dart-cryptography) isn't that much better.
* [pointycastle](https://pub.dev/packages/pointycastle) has a lot but also [misses](https://github.com/bcgit/pc-dart/issues/83) the exact features i'm after.

Now i can work around the limitations of not being able to load PEM. I can do so with alternative libraries or even extract the key and go for a method that a library does support. But then you hit the next issue. Sign and verify. If they don't support that then the whole library is useless to me. As an aside, yes, `cryptography` does support the keys i need but doesn't support sign/verify. And for my case, that means the mentioned libraries are all useless. And that is where i do get stuck and scratch my head looking for a solution. I'm probably, unless someone has a great suggestion, going to FFI route to C++, C or [Rust](https://www.youtube.com/watch?v=HF8gHAakb1Q). Not sure yet which one.

So that doesn't leave a lot of options for the Dart ecosystem.

Given that very much these days relies on cryptography in some shape or form, it's be a missed opportunity for dart to not a strong native cryptography library.
