### ISSUE TITLE
Function parameter is replaced to dynamic instead of Null by instantiate-to-bound algorithm.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34689]
Dart SDK Version: 2.1.0-dev.6.0
OS: Windows 10

The following code source declares some functions and than prints type of the created functions:
``` dart
Type typeOf<X>() => X;

typedef G1<X> = X Function();
typedef G2<X> = Function(X);
typedef G<X, Y extends X> = X Function(Y);

main() {
  print(typeOf<G1>());
  print(typeOf<G2>());
  print(typeOf<G>());
}
```
Sample output is:
```
() => dynamic
(dynamic) => dynamic
(dynamic) => dynamic
```
According to the Instantiate-to-bound Spec, should not it be 
> (dynamic) => Null
for the second and third cases instead?

Is function parameter of a parametrized type a conravariant occurence? Should it be replaced by `Null` (not `dynamic`) here?

**Comment by eernstg** [comment]
Right (I guess the order is a typo), we should get
```
() => dynamic
(Null) => dynamic
(Null) => dynamic
```
It's actually the June 5, 2018 commit bfa8be887a980cba385fbfad2b9a129a4c7e3eb4 of dartLangSpec.tex which specifies the variance of each type parameter of a type alias (e.g., `X` is covariant in `G2`), the rules in instantiate-to-bound.md haven't changed in that respect. Note that this ensures that we give the same treatment to `X` when it occurs as a formal parameter of a raw `G2` which is subject to i2b and when we write the underlying type directly:

```dart
typedef G2<X> = Function(X);
class A<X, Y extends G2<X>> {}
class B<X, Y extends Function(X)> {}
A a; // Means `A<dynamic, G2<Null>> a;`.
B b; // Means `B<dynamic, Function(Null)>`.
```

It would be both confusing and inconvenient if we had defined all type parameters to a parameterized type to be covariant:

```dart
// HYPOTHETICAL approach, ignore variance of type alias parameters.
typedef G2<X> = Function(X);
class A<X, Y extends G2<X>> {}
class B<X, Y extends Function(X)> {}
A a; // Would mean `A<dynamic, G2<dynamic>> a;`.
B b; // Would still mean `B<dynamic, Function(Null)>`.
```

The main problem is that i2b on `B` then produces something which is _not_ a supertype of all admissible choices for the omitted type arguments:

```dart
// HYPOTHETICAL situation continued.
A a2 = A<dynamic, G2<int>>();
```

The initialization of `a2` will fail at run time because `A<dynamic, G2<int>>` is not a subtype of `A<dynamic, G2<dynamic>>`, or we may have a notion of exact types that allows tools to detect that it will fail already at compile-time and make it a compile-time error.

In any case, i2b on `C` should produce a supertype of all regular-bounded types of the form `C<...>` (and even though we haven't tried to prove that, we have been looking for counter-examples and haven't found any). It is not a matter of soundness, but i2b should produce types that "cover all possible type argument lists" in order to be as useful and comprehensible as possible.

**Comment by eernstg** [comment]
This is another case where the bug fix in [CL 80140](https://dart-review.googlesource.com/c/sdk/+/80140) makes a difference; for a few more words on that, see [this comment](https://github.com/dart-lang/sdk/issues/35114#issuecomment-437313004).

With 80140, a raw `G2` means `G2<Null>` and a raw `G` means `G<dynamic, Null>`, as I said [here](https://github.com/dart-lang/sdk/issues/34689#issuecomment-427318212).

But without 80140 a raw `G2` means `G2<dynamic>` and a raw `G` means `G<dynamic, dynamic>`.

**Comment by eernstg** [comment]
Closing: CL 80140 was landed in 2018, and the common front end has been using the specified rule for about a year at this point, so there is no work to do with the front end. The corresponding issue in the analyzer is handled via https://github.com/dart-lang/sdk/issues/34699.
