### ISSUE TITLE
Super mixin. Runtime error instead of compile error if super-constraint interface member is not implemented

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#34691]
```dart
class A {
  String get g => "g";
}

class C {
  noSuchMethod(Invocation i) {
    print("C.noSuchMethod ivocked");

  }
}

mixin M on A {
  test() {
    super.g;
  }

  noSuchMethod(Invocation i) {
    print("M.noSuchMethod ivocked");
  }
}

class MA extends C with M {
}

main() {
  print(new MA().g);
  print(new MA().test());
}
```
This code produces
```
M.noSuchMethod ivocked
null
C.noSuchMethod ivocked
null
```
There should be a compile error, because super-constraint interface of the mixin is not implemented (no implenetation of the getter g)

**Comment by eernstg** [comment]
No, I agree that we should get a compile-time error, but the reason is a little bit different: In `C with M`, it is required that `C` has `A` as a superinterface (that means directly or indirectly, via `extends`, `implements`, or `with`). But that's not the case, so we shouldn't even go into checks of the properties of the resulting mixin application, it's just an immediate error to apply `M` to `C`.

If we were to add `implements A` to `C` then `C with M` would be OK. But then `C` would also have an implicitly induced `noSuchMethod` forwarder for the getter `g`, which means that there _would_ be a `super.g` that the body of `M.test` can invoke in `C with M` (and it _is_ OK to perform a superinvocation of such a forwarder). So in that case there would not be a compile-time error.

**Comment by eernstg** [comment]
Cf. our discussion at the meeting earlier today, I just checked that the current tools (version 2.1.0-dev.8.0) _do_ reject the example above:

```
> dart n004.dart
n004.dart:24:7: Error: '#lib1::C' doesn't implement '#lib1::A' so it can't be used with '#lib1::M'.
class MA extends C with M {
      ^
> dartanalyzer n004.dart
Analyzing n004.dart...
  error • The class doesn't implement the required class 'A' at n004.dart:24:25 • mixin_application_not_implemented_interface
  error • The class doesn't have a concrete implementation of the super-invoked member 'g' at n004.dart:24:25 • mixin_application_no_concrete_super_invoked_member
2 errors found.
```
So, today, we do get the compile-time error that we should have in the first place.

Adjusting the example such that we don't have that error, we can concretize what I said at the end of the previous comment, and that shows that we do have an analyzer bug here:

```dart
class A {
  String get g => "g";
}

class C implements A {
  noSuchMethod(Invocation i) {
    print("C.noSuchMethod invoked");
  }
}

mixin M on A {
  test() {
    super.g;
  }

  noSuchMethod(Invocation i) {
    print("M.noSuchMethod invoked");
  }
}

class MA extends C with M {
}

main() {
  print(new MA().g);
  print(new MA().test());
}
```

This program causes `dartanalyzer` version 2.1.0-dev.8.0 as well as a fresh one from commit 11707cab410906df65b72e94fd59b2f51690c9e7 to emit an error:

```
> dartanalyzer n005.dart
Analyzing n005.dart...
  error • The class doesn't have a concrete implementation of the super-invoked member 'g' at n005.dart:24:25 • mixin_application_no_concrete_super_invoked_member
1 error found.
> current_dartanalyzer n005.edart
ERROR|COMPILE_TIME_ERROR|MIXIN_APPLICATION_NO_CONCRETE_SUPER_INVOKED_MEMBER|/usr/local/google/home/eernst/lang/dart/scratch/201811/n005.dart|24|25|1|The class doesn't have a concrete implementation of the super-invoked member 'g'.
```

This is a bug in the analyzer: It _is_ allowed to invoke a noSuchMethod forwarder in a superinvocation; for the mixin application `C with M`, the superclass is `C`; `C` implements `A`, and `C` has a non-trivial noSuchMethod, so `C` has a noSuchMethod forwarder for `String get g`.

At run time the invocation of `super.g` in `M`, when occurring in the mixin application `C with M`, must invoke that noSuchMethod forwarder which will in turn invoke `noSuchMethod`; but that method is overridden in `C with M` by `M.noSuchMethod`, so the returned value must be  `"M.noSuchMethod"`, which is also what we get from `dart`.

So there is no 'area-front-end' issue here, but there is an 'area-analyzer' issue.

@sgrekhov, maybe you could adjust the issue? We could use 'area-analyzer' and indicate in the initial comment what the issue is now known to be, or we could close this one and create a new one for the analyzer.

**Comment by sgrekhov** [comment]
@eernstg, thank you. I created #35090. This issue is closed
