### ISSUE TITLE
Analyzer processes function params of parametrized types incorrectly.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34699]
Dart SDK Version: 2.1.0-dev.6.0
OS: Windows 10

This bug is similar with #34689, but it's about analyzer, not runtime.

The following code sample declares `typedef G<X extends A<X>> = Function(X)` and assigns such an object to the variables of the different types:
```
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

class A<X> {}
typedef G<X extends A<X>> = Function(X);

main() {
  G source;
  var fsource = toF(source);
  F<G<A<Null>>> target = fsource;
  F<G<A<dynamic>>> target1 = fsource;       //# 01: compile-time error
}
```
According to the instantiate-to-bound Spec, `F<G<A<Null>>> target = fsource;` should statically pass and `F<G<A<dynamic>>> target1 = fsource;` should fail.

However, this is not so: instead, `F<G<A<Null>>> target = fsource;` fail and `F<G<A<dynamic>>> target1 = fsource;` pass.

Analyzer sample output is:
> Analyzing test.dart...
>   error - A value of type '<Y extends (A<dynamic>) → dynamic>() → void' can't be assigned to a variable of type '<Y extends (A<Null>) → dynamic>() → void' at test.dart:10:26 - invalid_assignment
>   hint - The value of the local variable 'target' isn't used at test.dart:10:17 - unused_local_variable
>   hint - The value of the local variable 'target1' isn't used at test.dart:11:20 - unused_local_variable
> 1 error and 2 hints found.

**Comment by eernstg** [comment]
This is a tricky corner of the i2b mechanism: We otherwise seek to obtain a supertype of all regular-bounded types, but that property does not hold in the case where a contravariant occurrence of a type variable is nested in a number of enclosing type expressions where each layer occurs covariantly in the next one.

(Here we have just one: `X` occurs covariantly in `A<X>`.)

We _could_ have chosen to replace the "biggest enclosing covariant type expression" by `Null`, rather than just replacing the type variable, and we would then have gotten the result that `G` by i2b is transformed into `G<Null>` rather than `G<A<Null>>`.

The current definition implies that we could have `class B<X> implements A<X> {}`, and then the following would fail as indicated at run time:

```dart
G<B<int>> bar() => (B<int> b) => null;
G g = bar(); // Dynamic error.
```

However, I chose to keep the specified structure in the result of i2b (so we don't "delete `A`" when we compute i2b of `G`, because it's mentioned specifically as a bound).

This means that your analysis is correct, even though the result violates a property that we've otherwise strived to maintain.

It should be noted that we are likely to be able to go to the more radical model later on if this turns out to be a problem in practice, because it is likely to be a non-breaking change (in practice) to make some rather marginal raw types mean something which is a bit more general.

**Comment by eernstg** [comment]
This is another case where the bug fix in [CL 80140](https://dart-review.googlesource.com/c/sdk/+/80140) makes a difference; for a few more words on that, see [this comment](https://github.com/dart-lang/sdk/issues/35114#issuecomment-437313004).

With 80140, a raw `G` means `G<A<Null>>`, but without 80140 a raw `G` means `G<A<dynamic>>`.

So your analysis reflects the situation where 80140 has been landed, and I hope we can get there.

**Comment by eernstg** [comment]
[CL 80140](https://dart-review.googlesource.com/c/sdk/+/80140) was landed in 2018. `G` should be expanded by instantiation to bound to `G<A<Null>>` without null safety, and `G<A<Never>>` with null safety.

Note that the CFE currently (ecc87a177fad538728998b4c49f043b4bf9212bd) performs instantiation to bound as described above, so the change should not be breaking. Also note that the current behavior of the analyzer treats a type alias and the expansion of the type alias differently:

```dart
class A<X extends void Function(X)> {}

typedef F<X> = void Function(X);
class B<X extends F<X>> {}

void main() {
  void foo(A a, B b) {
    int i;
    i = a; // Error, showing what `A` means.
    i = b; // Error, showing what `B` means.
  }
}
```

The errors at assignments to `i` give rise to the following error messages (without null safety):

```
ERROR|COMPILE_TIME_ERROR|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/lang/dart/scratch/202009/n024.dart|9|9|1|A value of type 'A<void Function(Null)>' can't be assigned to a variable of type 'int'.
ERROR|COMPILE_TIME_ERROR|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/lang/dart/scratch/202009/n024.dart|10|9|1|A value of type 'B<void Function(dynamic)>' can't be assigned to a variable of type 'int'.
```

which shows that the raw `A` is considered by the analyzer to mean `A<void Function(Null)>`, and the raw `B` is considered to mean `B<void Function(dynamic)>`. Instantiation to bound should replace `X` by `Null` (without null safety, and `Never` with null safety) when it occurs contravariantly, so perhaps the analyzer considers the type argument of `F` as something other than contravariant.

With null safety we get the following error messages:

```
ERROR|COMPILE_TIME_ERROR|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/lang/dart/scratch/202009/n024.dart|9|9|1|A value of type 'A<void Function(Null)>' can't be assigned to a variable of type 'int'.
ERROR|COMPILE_TIME_ERROR|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/lang/dart/scratch/202009/n024.dart|10|9|1|A value of type 'B<void Function(dynamic)>' can't be assigned to a variable of type 'int'.
ERROR|COMPILE_TIME_ERROR|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/202009/n024.dart|7|12|1|'void Function(Null)' doesn't extend 'void Function(void Function(Null))'.
```

which shows the same thing (plus the need to replace `Null` by `Never`, cf. dart-lang/language#1133).

**Comment by leafpetersen** [comment]
@scheglov can you estimate how much work it would be to fix this in the analyzer?

**Comment by scheglov** [comment]
Probably 2 days.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/164860
