### ISSUE TITLE
Flutter AOT build crashes on super-mixins

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34704]
To reproduce, check out Flutter at https://github.com/flutter/flutter/commit/3c56e6c77dc5c351d610d5c2a11d86e8be88519f then `cd examples/flutter_gallery` and run `flutter build aot`. You should see this error:

```
Unhandled exception:
Missing canonical name for Reference to #lib29::_RendererBinding&BindingBase&ServicesBinding
#0      BinaryPrinter.writeReference (package:kernel/binary/ast_to_binary.dart:532:9)
#1      BinaryPrinter.visitSupertype (package:kernel/binary/ast_to_binary.dart:1637:7)
#2      Supertype.accept (package:kernel/ast.dart:4998:26)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:242:7)
#6      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:768:5)
#7      Class.accept (package:kernel/ast.dart:973:30)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#9      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#10     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:242:7)
#11     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:620:5)
#12     Library.accept (package:kernel/ast.dart:409:30)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#15     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
#16     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:234:11)
#17     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49:5)
#18     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:328:5)
#19     FrontendCompiler.writeDillFile (package:vm/frontend_server.dart:398:13)
<asynchronous suspension>
#20     FrontendCompiler.compile (package:vm/frontend_server.dart:360:13)
<asynchronous suspension>
#21     _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
<asynchronous suspension>
#22     starter (package:frontend_server/server.dart:133:27)
<asynchronous suspension>
#23     main (file:///b/build/slave/Linux_Engine/build/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#24     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Compiler terminated unexpectedly.
```

@JekCharlsonYu @a-siva

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/78383 fixes the crash by making mixin deduplication transformation more robust.

**Comment by kmillikin** [comment]
To clarify, we are currently using isAnonymousMixin for two things: mixin application classes and the superclass constraints of mixin declarations.  The former of these are reachable as superclasses, and the latter are reachable as super-interfaces.

Eventually, the mixin declaration superclass constraints will be represented more directly as just a list of interfaces, there will be no intermediate names introduced, and they won't be seen by your deduplication pass.  So in the meantime, just finding a way to skip them will probably be OK.

**Comment by alexmarkov** [comment]
Kevin, thank you for the explanation. I think the fix is correct as long as isAnonymousMixin classes representing constraints are only accessible from a list of interfaces and it's OK to de-duplicate them (in case they have same supercass and implemented interfaces).

> They're just classes. In general, they could appear anywhere that a class could and pattern matching on them is inherently brittle.

This transformation uses isAnonymousMixin flag to distinguish anonymous mixin applications, which should not be referenced from arbitrary places in a program (as they're anonymous), and remove duplicates among them. It won't be correct to do this for arbitrary _non-anonymous_ classes.

Maybe the new mixin syntax would allow us to remove the duplicated anonymous mixin applications in the front-end at the first place, and eventually we will be able to drop this transformation without regressing size of AOT-compiled Flutter applications.

**Comment by kmillikin** [comment]
I don't think mixin declarations will enable us to eliminate these.  We have these classes because we decided early on that Kernel didn't have 'anonymous' classes.  Every class in the hierarchy corresponds to a class declaration that you can point to.  This includes anonymous mixin application superclasses in `class C extends S with M` and all the intermediate classes in `class C = S with M0, M1, ..., Mn`.

We wanted these classes for a lot of small reasons: there is an obvious place to put their properties, serialization/deserialization just works, you can build a map or set keyed by classes that includes everything in its domain, they have a body for transformations to insert code if they need, etc.

In retrospect, encoding the mixin declaration superclass constraints as a mixin application superclass was a mistake.  We were (I was) led astray by the suggestion that it would work in [the proposal](https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md).  It doesn't work because the order of mixin application matters.  When you inherit overlapping signatures with the same name there can be orders that will be a compile-time error and orders that will work (by overriding the more specific signature with the more general one that you intend to choose), and sometimes there is no order that will work at all.

We initially did it for this reason because we wanted to reuse the existing code in our compiler, and because we didn't want any changes at all in the VM.

The answer to the question of what these mean and where they can occur is too vague.  We intend to clarify things.

**Comment by yjbanov** [comment]
Thanks for fixing! I verified on a local build that the fix works in all modes (JIT, AOT profile, AOT release). Will attempt to land the mixin syntax change in Flutter immediately after https://github.com/flutter/flutter/pull/22866 lands.
