### ISSUE TITLE
Unable to set breakpoints in global lambda

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34742]
(Raised at https://github.com/Dart-Code/Dart-Code/issues/1249 by @kentcb)

Given this code:

```dart
import 'package:test/test.dart';

typedef void VoidCallback();

void main() {
  final workingCase = SomeClass(() {
    // set a breakpoint on the following line and it will be hit
    print("Executing");
  });

  test("breakpoint works", () {
    workingCase.execute();
  });

  test("breakpoint does not work", () {
    nonWorkingCase.execute();
  });
}

class SomeClass {
  final VoidCallback execute;

  SomeClass(this.execute);
}

final nonWorkingCase = SomeClass(() {
  // set a breakpoint on the following line and it will not be hit
  print("Executing");
});
```

If you put breakpoints on the two marked locations, the second one gets rejected:

> "details":"addBreakpointWithScriptUri: Cannot add breakpoint at line '28'"

If you run the file with `dart --observe --pause-isolates-on-start .\test\broken_test.dart` and then open in Observatory, the second breakpoint (the one that is missed) does not appear as a valid location to add a breakpoint:

![obs](https://user-images.githubusercontent.com/1078012/46718965-c349f500-cc64-11e8-9bc7-81a65d51c4dd.png)

As far as I can see, the only difference between the code is that one is inside the `main` method and the other is not.

**Comment by ZichangG** [comment]
The reason for this problem is that during source report generation, field like nonWorkingCase has not been examined. One solution is to allow the initializer of field to have breakpoints set. It required both start token position and end token position.

However, it seems like end token position of field is not included in the kernel file. Here is an screenshot of KernelLoader. end_position_ remains -1 after reading.
![screenshot from 2019-01-09 12-21-55](https://user-images.githubusercontent.com/45517515/50927050-744e6000-140b-11e9-88bc-c68968d56143.png)

**Comment by jensjoha** [comment]
The field should now have an end position.
