### ISSUE TITLE
Recursive types fail at static analysis but not runtime

### ISSUE THREAD

**Issue by har79** [dart-lang/sdk#34763]
The following:

```
class Foo<F extends Foo<F>>{}

main() {
  Foo foo;
  Foo<Foo> fooFoo;
  print('hello');
}
```
-- https://dartpad.dartlang.org/d8c30a41d578d74d3c6e9c503f3004a3

runs successfully but throws an error during static analysis:<br>
`'Foo<Foo>' doesn't extend 'Foo<Foo<Foo>>'.`

`Foo` is equivalent to `Foo<Foo>` (which is equivalent to `Foo<Foo<Foo>>` etc.) so this seems like an error in the analyzer. It normally wouldn't be an issue because there's no *need* to write `Foo<Foo>`, but the analyzer reports the type of `Foo foo` as `Foo<Foo>`. This is used by the built_value package when generating code and can cause the generated code to fail static analysis: https://github.com/google/built_value.dart/issues/507.

**Comment by eernstg** [comment]
This is a bug. We have the following expansion (cf. [instantiate-to-bound](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md)) of the types you mention (that is, the short version on the left has the meaning which is indicated on the right of `-->`):
```dart
Foo --> Foo<Foo<dynamic>>
Foo<Foo> --> Foo<Foo<Foo<dynamic>>>
```
These types are well-formed, because they are super-bounded, because `Foo<Foo<Null>>` and `Foo<Foo<Foo<Null>>>` are regular-bounded (that is, they satisfy their bounds). Let's take the latter, checking that its type argument satisfies the bound:

```dart
Foo<Foo<Null>> <: Foo<Foo<Foo<Null>>> because
Foo<Null> <: Foo<Foo<Null>> because
Null <: Foo<Null>
```
So the analyzer should accept `Foo<Foo>` as a correctly super-bounded type, and it's not an error to use a superbounded type as a type annotation.

**Comment by stereotype441** [comment]
This was fixed in b1a54154f83c3267628be6d4892e24cba8662ba7.  I'm not sure which version of the SDK dartpad is running, but evidently it's running an earlier version.

I'm closing this bug since the code is correct.  @devoncarew do you know who I should talk to about getting dartpad updated?

**Comment by stereotype441** [comment]
Correction: I just found out that it's @jcollins-g I should be asking about dartpad

**Comment by jcollins-g** [comment]
Dartpad will get an update once the bugfix lands in a stable version of Dart.
