### ISSUE TITLE
Analyzer throws compile error when declare a class with typed parameter which depends on parameterized typedef

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34833]
Dart SDK Version: 2.1.0-dev.7.1
OS: Windows 10

Here is a sample code which declares a class with typed typedef parameter which is parameterized itself:
``` dart
class A<X> {}
typedef G<X extends A<X>> = X Function();
class B<X extends A<G<X>>> {}

main() {
  print(B);
}
```
Dart passes with this and prints `B` actual type, no errors here:
> B<A<() => dynamic>>

Analyzer throws compile error instead:
>   error - 'X' doesn't extend 'A<X>' at test.dart:3:23 - type_argument_not_matching_bounds

Seems like there should not be compile error here, or at least dart and analyzer should behave in the same way.

**Comment by eernstg** [comment]
When checking the declaration of type parameters of `B`, we only have the assumption `X <: A<G<X>>`, but we need to use that to prove `X <: A<X>` in order to verify that the type `G<X>` can be used in the first place (#34628 illustrated why we don't want to even consider using the existence of `G<X>` in the bound as evidence that "then `X` must have been chosen such that it is an acceptable argument to `G`, and hence `X <: A<X>` must hold). We do have expansions like this:

```dart
X <: A<X Function()>
   <: A<A<X Function()> Function()>
   <: A<A<A<X Function()> Function()> Function()>
   <: A<A<A<A<X Function()> Function()> Function()> Function()>
   ...
```
But I don't see how it could be proven that `X <: A<X>` from the available assumptions. So I think the analyzer is correct in rejecting `B`.

However, I don't understand why the analyzer says that the problem is that we don't have `X <: A` (which would mean `X <: A<dynamic>`) given that we need `X <: A<X>` in order to justify the use of `G<X>`.

**Comment by srawlins** [comment]
Analyzer now only reports:

> 'X' doesn't conform to the bound 'A&lt;X>' of the type parameter 'X'.

So I think we're good.
