### ISSUE TITLE
--sync-async doesn't work, maybe?

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#34853]
Code:
```dart
import 'dart:async';

void scheduler() {
  print('+ scheduler');
  Future.microtask(() {
    print('MICROTASK');
  });
  print('- scheduler');
}

void caller() async {
  print('+ caller');
  await scheduler();
  print('- caller');
}

void main() async {
  print('+ main');
  await caller();
  print('- main');
}
```

Result:
```
[function-apply-await-sync]$dart test.dart 
+ main
+ caller
+ scheduler
- scheduler
MICROTASK
- caller
- main
[function-apply-await-sync]$dart --version
Dart VM version: 2.1.0-dev.5.0+google3-v2.1.0.dev.5.0 (google3) on "linux_x64"
```

Why does `MICROTASK` run before `caller` terminates? is this expected behavior?

**Comment by jonasfj** [comment]
@lrhn, samir suggests you would know if this is expected semantics.. coming from node.js I'm obviously surprised (and I wonder if we have these semantics when compiled with dart2js).

**Comment by natebosch** [comment]
any `await` introduces a microtask. You could write that caller as:

```dart
void caller() async {
  print('+ caller');
  scheduler();
  await null; // or await Future.microtask(); I _think_ is equivalent
  print('- caller');
}
```

Being able to `await` things that aren't futures is one of the potential bugs that we unfortunately didn't have time to turn into a static error.

**Comment by lrhn** [comment]
First, `caller` and `scheduler` should have `Future<void>` as return type, not `void`. Don't await `void` (even if it is technically allowed)!

Other than that, the code is working as intended. 
Async functions with no asynchrony in the body *do* return immediately. They return an already completed future. Waiting on a future (or `await`ing anything) will always cause a delay.

The behavior is:
* enter `main`.
* print "+ main"
* enter `caller`
* print "+ caller"
* enter `scheduler`
* print "+ scheduler"
* schedule a microtask (#1)
* print "- scheduler"
* complete future of `scheduler` call with null
* return future from `scheduler` call to `caller`.
* `caller` awaits future from `scheduler` call, registering a callback
* since the future is already completed, it schedules a microtask (#2) to call the callback.
* return future of `caller` to `main`
* `main` awaits future from `caller`, registering a callback
* that future is not yet completed, so nothing else happens yet.
* `main` returns a future that no-one will ever see.
* return to the event queue.
* Microtask #1 triggers
* print "MICROTASK"
* return to the event queue.
* Microtask #2 triggers
* `caller`'s callback is called, continues after await
* print "caller -"
* `caller` completes its returned future with null.
* `main`'s await callback is called, continues after await
* print "main -"
* `main` completes its returned future with `null`
* return to the event queue.
* All queues are empty, program ends.

The thing that you are probably missing here, because of the `void` return type, is that `scheduler` and `caller` return futures. Due to sloppy void enforcement (which we sadly needed to do to not break a lot of old sloppy code), you get to await a `void` expression which actually contains a future value.
Even if the void functions actually returned null, it wouldn't have changed anything, the `await` expressions would still schedule microtasks for that, the only difference is that `main`'s await would be triggered by microtask #3 instead of the completion of `caller`'s future. The order would be the same.

**Comment by natebosch** [comment]
Minor nitpick on the explanation -

> The thing that you are probably missing here, because of the `void` return type, is that `scheduler` and `caller` return futures

`scheduler` is not `async` in that example and does not return a future. This is falling to the other case you describe:

> the `await` expressions would still schedule microtasks for \[the null value\]

@jonasfj - 

> But if the async functions are synchronous, that is they don't do anything async I would expect them to return immediately rather than deschedule at the `await` point which seems to be happening here.

I don't typically work in node.js, but my understanding of the spec for `await` in javascript is that it behaves similarly to `await` in Dart. If you `await` a value that is not a Promise, including null, then it behaves as if you turned that value into a promise with `Promise.resolved()` which will not invoke it's `then` callback synchronously. The function `scheduler` _is_ returning synchronously, but `caller` does not continue past the `await` synchronously - as it wouldn't in javascript either.

**Comment by jonasfj** [comment]
Yeah, it's possible I have confused myself :)

Thanks for all the explanations..
