### ISSUE TITLE
Flutter engine not ready for debug yet

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#34872]
https://github.com/dart-lang/sdk/commit/984c407bb303304ab48ac39a2e4f91d0e987884a introduced failure:

[ERROR:flutter/shell/common/shell.cc(182)] Dart Error: Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure>
(dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
result 7353a2e5-2c85-41ea-af16-e8eb2581e731
7353a2e5-2c85-41ea-af16-e8eb2581e731 out/host_debug_unopt/engine_test.dill 0
00:00 �[32m+0�[0m: canvas APIs should not crash�[0m
../../third_party/dart/runtime/vm/object.cc: 9856: error: expected:
Dart::vm_snapshot_kind() == Snapshot::kFullAOT
Dumping native stack trace for thread 3414
  [0x00000000029c5c2f] Unknown symbol
  [0x00000000029c5c2f] Unknown symbol
-- End of DumpStackTrace

**Comment by jason-simmons** [comment]
This failure happens when code in the `dart:ui` package that is built into the Flutter engine throws an `AssertionError`.

In the Dart VM, `Script::Source` returns null because the `dart:ui` script has a `kind` of `kKernelTag`.  This results in an assertion failure in `Script::GetSnippet`, which is called while throwing the `AssertionError`.

Does the Flutter engine need to build the `dart:ui` Dart code in a different way?

**Comment by a-siva** [comment]
The code in Script::GetSnippet seems to assume that it will always find the source in JIT mode
```
const String& src = String::Handle(Source());
  if (src.IsNull()) {
    ASSERT(Dart::vm_snapshot_kind() == Snapshot::kFullAOT);
    return Symbols::OptimizedOut().raw();
  }
```
That assertion about snapshot being FullAOT seems incorrect
