### ISSUE TITLE
Analyzer issue with super bounded function type

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34906]
Broken out of #34663
 
```typedef G<X, Y extends Function(X)> = X Function(Function(Y));

main() {
  G<dynamic, Function(Null)> target;
}
```

Analyzer complains that `(Null) -> dynamic` is not a subtype of `(dynamic) -> dynamic`, which is true, however, this should be a valid super-bounded type.

Per Erik:

> So in order to verify that T is a correct super-bounded type we ought to check that G<Null, Function(Object)> is regular-bounded, i.e., that Null <: dynamic and Function(Object) <: Function(Null), which is true for both. That's one bug, in the area of verifying super-bounded types.

CC @leafpetersen @eernstg @lrhn

**Comment by eernstg** [comment]
The fact that each parameter of a generic type alias has a specific variance was specified much earlier than 57f895c7a41ae55ce19fea403cbaec77d4671a45 (from today), that happened in dartLangSpec.tex as of bfa8be887a980cba385fbfad2b9a129a4c7e3eb4 (2018-06-05).

So when the feature specification [instantiate-to-bound.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md) specifies actions like `replacing every contravariant occurrence of Xj by Null`, it applies to the bound of `Y` which goes from `Function(X)` to `Function(Null)` in the i2b algorithm, yielding the type `G<dynamic, Function(Null)>` which is in focus here.

However, that doesn't even rely on the variance of `Y` in `G`, because that's a covariant type parameter, which means that the introduction of the notion of any other variances than 'covariant' affected generic type aliases in general, but it made no difference for `G` as defined here: We used to consider every type argument of a parameterized type as a covariant occurrence, and that's a bug which was fixed in bfa8be887a980cba385fbfad2b9a129a4c7e3eb4, but `Y` is indeed covariant.

The other commit, 57f895c7a41ae55ce19fea403cbaec77d4671a45, is concerned with the specification that satisfaction of the bounds of a generic type alias _H_ must imply satisfaction of all bounds in all types on the right hand side of _H_ (assuming the new syntax for type aliases). That makes no difference for the concrete `G` that we're discussing here: It satisfies that constraint.

So the behavior described by Mike is all correct, and 57f895c7a41ae55ce19fea403cbaec77d4671a45 makes no difference.
