### ISSUE TITLE
Performance drop in TypeChecks.CovariantCheck (simdbc)

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#34918]
Using the new loop framework for the register allocator did not show performance differences (as expected, since it replaces the old code with almost semantically equivalent code), except for simdbc on covariant check. Please investigate.

 ` | TypeChecks.CovariantCheck | -11.2 % | RunTime | dart-simdbc-checked | Odroid-C2 | linux-armv8 | -2.25 x noise`

**Comment by aartbik** [comment]
By just changing linear_scan.*, I can reproduce this for ReleaseSIMDBC

JIT Before:
TypeChecks.IsCheck(RunTime): 4059.9326855983772 us
TypeChecks.CovariantCheck(RunTime): 3556.9338543516874 us.

JIT After:
TypeChecks.IsCheck(RunTime): 4243.845351694916 us.
TypeChecks.CovariantCheck(RunTime): 3971.319432539683 us.

**Comment by aartbik** [comment]
I trace a minor difference to:

split v0 [0, 145) between [0, 71)
  split sibling [52, 145)                      vs            split sibling [68, 145)   

which is solely due to "better" outermost loop information.

**Comment by aartbik** [comment]
With a slight tweak to the heuristic to get the old behavior back (essentially accepting a loop header from a previous block if the current block has no successor), I also get the better performance back.

TypeChecks.IsCheck(RunTime): 4025.1567927565384 us.
TypeChecks.CovariantCheck(RunTime): 3563.3357384341634 us.

I am not sure though if such a change makes sense, or whether this was just hitting a lucky spot with register allocation.

@mraleph

**Comment by mraleph** [comment]
I am gonna look at this next week and will figure out if heuristic needs to be tweaked.

**Comment by aartbik** [comment]
@mraleph did you give this some more thought?

**Comment by mraleph** [comment]
Got to this today. Looked at the generated code and managed to load the old reasoning back into the head again. 

I think we need to revert the old heuristic: the reason why more precise loop information does not work here, is linearity of the register allocation.  

We have a picture like this:

```
                    +---------------------------+
                    |                           |
                    v                           |
                    |xxxxxxx|         |xxxxxxxxx|
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
            *---------------------o   -----------  
                    ^       ^         ^
                    H       S         X

```

Here `.` mark instructions. The arrow shows back-edge of the loop. `x` mark loop blocks. `*` is a definition of a value, `o` is use. 

Observe that for a value to be live out of the loop it needs to be live through the whole loop. 

If we split at `S` we risk to allocate `H to S` into one register `R0` and `S to ...` into another register `R1`. 

This would introduce parallel moves `R1 <- R0` at `S` (which is outside of the loop) and at `X` which is inside of the loop. 

That's why heuristic was structured in terms start and end positions in the loop - essentially it checks if the candidate lifetime position for a split is inside the loop _or there are some blocks that follow that are inside of the loop_. Because splitting in the middle of the loop would disconnect prefix that covers first blocks in the loop from the blocks that follow, increasing chance of "disconnected" allocations.

**Comment by mraleph** [comment]
The correct fix would probably be to build old style "linear loop nesting" information from the new loop nesting information. Would you mind doing that, Aart?

**Comment by aartbik** [comment]
Excellent picture! (I will use that in the documentation) Yes, I will try to incorporate this idea while still using exact loop information (which I think we should keep of course :-).
