### ISSUE TITLE
Dart shows unclear error message when raw A() constructor of class A<X extends A<X>> is called

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#34950]
Dart SDK Version: 2.1.0-dev.8.0
OS: Windows 10 (64 bit)

The following test example calls raw `A()` constructor of  `A<X extends A<X>>` class.
``` dart
class A<X extends A<X>> {}
main() {
 A();
}
```
Both analyzer and dart throw a compile time error here and this is correct result according to i-2-b spec.
Dart error message is:
```
test.dart:3:2: Error: Inferred type argument '#lib1::A<dynamic>' violates the corresponding type variable bound of 'A::'.
Try specifying type arguments explicitly so that they conform to the bounds.
 A();
 ^
test.dart:1:9: Context: Bound of this variable is violated.
class A<X extends A<X>> {}
```
If I comment `A();` constructor call, no compile errors here in dart.

So I just suppose that the second error message here is excess as actually line 1 is correct and `class A<X extends A<X>> {}` declaration is valid.

**Comment by lrhn** [comment]
Line 1 is correct, and the message does not say otherwise. It merely lists the declaration of `A` whose bound is violated in line 3.

Maybe it would be clearer if `"bound of this variable is violated." ended in a colon instead of a full stp.

**Comment by kmillikin** [comment]
The first line is the error.  The second line is context explaining the error.  We should consider ways that we could make this more obvious (put Error:/Context: before the position?  Indent Context: so it looks nested under Error:?).

We're using a style where error messages are always complete sentences.  Still "Bound of this variable is violated." might better be "Here is the type variable whose bound is violated." or "The type variable whose bound is violated is here."

It's also more confusing than it needs to be because of the `#lib1::` stuff.  We are in the process of fixing it so it is more like:

```
test.dart:3:2: Error: Inferred type argument 'A<dynamic>' violates the corresponding type variable bound of 'A'.
Try specifying type arguments explicitly so that they conform to the bounds.
 A();
 ^
test.dart:1:9: Context: Here is the type variable whose bound is violated.
class A<X extends A<X>> {}
```

@askeksa-google do we have a list of error messages that might need improving or a process for tracking them?

**Comment by askeksa-google** [comment]
I have created the label **improve-diagnostics** to track issues about error messages like this one.

For this particular context message, I think the formulation that would be most consistent with existing context messages would be "This is the type variable whose bound is violated.".

**Comment by kmillikin** [comment]
You are right.  I missed that the context message actually pointed to the `X`:
```
Context: Bound of this variable is violated.
class A<X extends A<X>> {}
        ^
```

**Comment by askeksa-google** [comment]
The error messages have been reformulated to clarify that the message about the variable is a context to the error.
