### ISSUE TITLE
Unexpected HTTP Caching on Real Devices but not on Emulator

### ISSUE THREAD

**Issue by p30arena** [dart-lang/sdk#34966]
## Steps to Reproduce

I'm using dart:io HttpClientRequest

My Web Server returns an ETag, so a client might want to cache the response,
but I couldn't find any docs on how to disable caching on client side.
The caching happens on an Android API 25 Device, but on an API 23 Emulator, the response is not cached.

Should I add a **cache-control: no-cache** header to my response from server or is this configurable from client side?

**Comment by arcas0803** [comment]
This should be in the documentation, for people to know the behaviour of the client. And, be able to configure this, would be nice too.

**Comment by natebosch** [comment]
I don't think there is a good place for us to document Android specific behavior around the network. If anywhere the best place to document this might be https://docs.flutter.dev/data-and-backend/networking

If you'd like to ask for more flutter documentation you can file an issue at https://github.com/flutter/website

Since there are no code changes we can make here I'll close this for now. cc @brianquinlan in case you think I'm overlooking anything.
