### ISSUE TITLE
Implicit const inference and param default values?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#34975]
Version: `Dart VM version: 2.1.0-dev.7.1+google3-v2.1.0.dev.7.1 (google3) on "linux_x64"`

```dart
class Options {
  final String a;
  final String b;
  const Options({this.a = 'a', this.b = 'b'});
}

void goodFunction([Options o = const Options()]) {
  print(o.a);
  print(o.b);
}
void badFunction([Options o = Options()]) {
  //                          ^^^^^^^^^
  // Default values of an optional parameter must be constant.
  print(o.a);
  print(o.b);
}

void main() {
  goodFunction();
  badFunction();
}
```

Both analyzer and dart2js flag this as an error. I have not tried the VM or DDC. WAI?

**Comment by lrhn** [comment]
We deliberately did not make the optional parameter default-value a const context.
That allows us to later change the semantics to allow non-constant expressions as default values without breaking existing code that omits `const`.

It is annoying that there is a difference, but it would also be annoying if we change the behavior so that the code above creates a new `Options` object each time (maybe, this code is probably fine, other code may not).
