### ISSUE TITLE
dart:async is optional in Flutter but not in the 2.0.0 SDK

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#34972]
The 2.0.0 analyzer will catch usages of `dart:async` that are missing an import, but the Dart SDK provided by Flutter seems to allow it. This forces users to switch back and forth between SDKs when developing for Flutter and web

* Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
* MacOSX

**Comment by lrhn** [comment]
In Dart 2.1, the `dart:core` library started exporting `Future` and `Stream`. Since you can write functions returning `Future` or `Stream` without importing `dart:async` (by using `async` or `async*` function bodies), we decided that you should be able to write the type of those functions too without having to import `dart:async`.

It does mean that any code using that feature should have an SDK requirement of 2.1.0.
The Flutter project has been releasing development versions of the Dart SDK, so they already have the feature, while the stable Dart 2.1 release hasn't been made yet.

(Analyzer people, would it make sense to detect uses of `Future` and `Stream` without an import when a package has an SDK requirement &lt;2.1.0?)

**Comment by stereotype441** [comment]
Related: #34978.

**Comment by srawlins** [comment]
I'll close this as stale.
