### ISSUE TITLE
Flaky crash "object.cc: 13831: error: expected: receiver_class_id != kIllegalCid" on standalone_2/io/raw_socket_write_destroy_test

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#35010]
Can be reproduced on mac/simdbc64

tools/test.py -m debug -a simdbc64 -n dartk-reload-mac-debug-simdbc64 --repeat 100  standalone_2/io/raw_socket_write_destroy_test

```
FAILED: dartk-vm debug_simdbc64 standalone_2/io/raw_socket_write_destroy_test
Expected: Pass
Actual: Crash

--- Command "vm_compile_to_kernel" (took 999ms):
DART_CONFIGURATION=DebugSIMDBC64 /Users/alexmarkov/dart/sdk/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/DebugSIMDBC64/vm_platform_strong.dill -o /Users/alexmarkov/dart/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_standalone_2_io_raw_socket_write_destroy_test.dart_3/out.dill /Users/alexmarkov/dart/sdk/tests/standalone_2/io/raw_socket_write_destroy_test.dart --packages=/Users/alexmarkov/dart/sdk/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 12.000353s):
DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --hot-reload-test-mode --short_socket_read --short_socket_write --sync-async --ignore-unrecognized-flags --packages=/Users/alexmarkov/dart/sdk/.packages /Users/alexmarkov/dart/sdk/xcodebuild/DebugSIMDBC64/generated_compilations/dartk/tests_standalone_2_io_raw_socket_write_destroy_test.dart_3/out.dill

exit code:
-6

stderr:
../../runtime/vm/object.cc: 13831: error: expected: receiver_class_id != kIllegalCid
Dumping native stack trace for thread 2807
  [0x000000010a107e64] dart::Profiler::DumpStackTrace(void*)
  [0x000000010a107e64] dart::Profiler::DumpStackTrace(void*)
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -m debug -a simdbc64 -n dartk-reload-mac-debug-simdbc64 --repeat 100 standalone_2/io/raw_socket_write_destroy_test
```

**Comment by alexmarkov** [comment]
This test also failed in ICData::GetTargetAt

```
../../runtime/vm/object.cc: 13955: error: expected: Object::Handle(Array::Handle(ic_data()).At(data_pos)).IsFunction()
Dumping native stack trace for thread 1703
  [0x000000010f0d2e64] dart::Profiler::DumpStackTrace(void*)
  [0x000000010f0d2e64] dart::Profiler::DumpStackTrace(void*)
```

**Comment by mraleph** [comment]
Ah, I see - this is the race due to hot reload testing mode. We clear ICData which breaks "atomicity" promise of the growth protocol: outside of hot reload scenarios adding a check means allocating a new ic_data_ array, populating it and then publishing it by storing it into the ic_data_ field.

However with hot reload this is not true - we simply zap ic_data_ array with sentinel values and then we start reusing entries. Which means that background compiler might see partially written entries - which it can't cope with.

**Comment by rmacnak-google** [comment]
We disable background compilation at the beginning of a reload. How can it be running?

**Comment by mraleph** [comment]
Sorry, for being a bit unclear. We do indeed stop the background compiler. The race happens after we finish reloading and start it again. 

Imagine you have the code:

```dart
bool foo(x) => x is Simple;
```

Where `x is Simple` turns into a call-site to a `_simpleInstanceOf` which is marked as checking two arguments.

[In reality on the fast path it only needs to check the cid of the receiver - but the reason for 2 checked arguments is to make code in the IC miss handler work, as it needs to look at both arguments]

```cpp
    if (dart::SimpleInstanceOfType(type)) {
      instructions += Constant(type);
      instructions += PushArgument();  // Type.
      instructions += InstanceCall(
          position, Library::PrivateCoreLibName(Symbols::_simpleInstanceOf()),
          Token::kIS, 2, 2);  // 2 checked arguments.
      return instructions;
    }
```

Imagine we reach this callsite. It would result in ICData that looks like this `ICData { ic_data_: [receiver-cid, type-cid, _simpleInstanceOfTrue/False, count, 0, 0, 0, 0] }`.

Now hot reload happens. During hot reload `ICData::Reset(zone)` is called and it does the following: 

```cpp
    const intptr_t num_args = NumArgsTested();
    const bool tracking_exactness = IsTrackingExactness();
    if (num_args == 2) {
      ClearWithSentinel();
    } else {
      const Array& data_array = Array::Handle(
          zone, CachedEmptyICDataArray(num_args, tracking_exactness));
      set_ic_data_array(data_array);
    }
```

Call-sites to `_simpleInstanceOf` have two checked arguments, so we hit `ClearWithSentinel` and we get `ICData { ic_data_: [0, 0, 0, 0, 0, 0, 0, 0] }`

(Unfortunately there is no comment for why `num_args == 2` is treated specially this way.)

Then we start running normal code again and resume background compiler. 

Now the following situation can arise: 

Mutator thread comes to function `foo`, a IC miss handler is called and it does `ICData::AddCheck` which does this:

```
  intptr_t index = -1;
  data = FindFreeIndex(&index);
  ASSERT(!data.IsNull());
  intptr_t data_pos = index * TestEntryLength();
  // (*) we will start writing checks entry into data starting at position data_pos.
```

Here `data` would be the same as `this->ic_data()` and `index` would be `0` because we have overwritten the first record with sentinel. 

Meanwhile background compiler might be optimizing the very same function and it will be cloning the same `ICData` object that we are mutating. 

Which creates an inconsistent copy because mutator will be writing data into the same `ic_data` array that is already visible to other threads.

That is how this race happens.

**Comment by rmacnak-google** [comment]
Oh, I see. I believe the special treatment for num_args == 2 had something to do with SmiAddInlineCache et al insisting they always have the Smi case as the first entry.

**Comment by mraleph** [comment]
I think we need to remove `FindFreeIndex` and go to fully clearing `ICData`.

We might need to embed some additional information into "rebind" rule - but we should be able to completely clear ICData during reload.
