### ISSUE TITLE
dart compile error

### ISSUE THREAD

**Issue by zhangdengjie** [dart-lang/sdk#35051]
Analyzer Feedback from IntelliJ
error: The class 'A2' can't be used as a mixin because it references 'super'. (mixin_references_super at [gsy_github_app_flutter] lib\test\DemoMixins.dart:56)
# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

**Comment by dgrove** [comment]
@stereotype441 please close if there's not enough info to process.

**Comment by stereotype441** [comment]
@zhangdengjie Based on a web search it looks like the file in question is https://github.com/CarGuo/GSYGithubAppFlutter/blob/master/lib/test/DemoMixins.dart.  Is that correct?

Assuming that's true, the error message is legitimate.  Previously, Flutter allowed freely mixing in a class that referenced super, but we had to remove that feature due to difficulties with ahead-of-time compilation.  The way to get that functionality now is to define the mixed-in type using the `mixin` syntax rather than `class`.  So for example if you replace:
```
class A extends Base {
  ...
}
```
with:
```
mixin A on Base {
  ...
}
```
and make a similar change to A2, you should not see any errors anymore.
