### ISSUE TITLE
[Constants-Phase1] Analyzer Issue for Constants Implementation

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35080]
Request: As per [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md), 

***Analyzer and CFE
**The analyzer and CFE implements support for the new constant and potentially constant expressions behind the experimental flag.

Phase 1 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60)

Tasks:
- [x] Cast Operator
- [x] Type Test Operator
- [x] Equality Operator
- [x] The operator >>>
- [x] The operator &
- [x] The operator |
- [x] The operator ^
- [x] Short-Circuit &&
- [x] Short-Circuit ||
- [x] Short-Circuit ??
- [x] Short-Circuit ?:
- [x] Fix #33441
- [x] Address co19 failures
- [x] Verify that no test failures occur if `IsEnabledByDefault.constant_update_2018` is set to `true`
- [ ] Add an SDK constraint hint #36296

**Comment by bwilkerson** [comment]
@lrhn @mit-mit 

I started looking at what it would take to implement this experiment, and I found that some of the work is already done. For example, the `&&` and `||` operators have been lazy in the analyzer since 1/30/18 (https://dart-review.googlesource.com/37540).

We could potentially put the current implementation behind the flag and then revert the change to make them eagerly evaluate their arguments, but I'm concerned that that would break existing users.

Are we certain that all of these changes are really different than the 2.1 behavior?

How would you like me to handle this situation?

**Comment by bwilkerson** [comment]
The rules for equality ('==' and '!=') were updated on 8/23/18 (https://dart-review.googlesource.com/71340), so they are also already in 2.1.

**Comment by lrhn** [comment]
It seems that `==` and `!=` works everywhere (analyzer, dart2js, VM),
but `&&` and `||` only works in the analyzer and VM, they fail in dart2js.
In the VM, anything goes, really, even things that were never valid. It's probably a case of CFE missing errors, where dart2js has its own constant system catching the error, and running the old rules.

It does mean that there might be code out there using these features, passing the analyzer and running on the VM, so we can't retract the already working functionality. 
So, `==`, `!=`, `&&` and `||` functionality should keep working without the experimental flag in the analyzer and VM (CFE). Dart2js is free to keep it not working without the experimental flag, or just follow the CFE.

**Comment by stereotype441** [comment]
Note that when people start using the new cast and type test operators, they are likely to run into trouble due to #33441, because the analyzer doesn't always assign correct types to constants that are maps or lists.  Accordingly, I'm adding a bullet item to fix #33441 before we consider the implementation complete.

**Comment by MichaelRFairhurst** [comment]
#33551 has been closed, the real issue behind it is #35441, which will not affect this issue to nearly the same degree.

I'm still hoping to solve #35441 this week, but its not in my opinion a blocker.

**Comment by stereotype441** [comment]
We've now completed all the implementation work we know about, but the co19 tests aren't passing, so we're investigating that.

**Comment by stereotype441** [comment]
I'm placing this in the Dart2.3 milestone because @kmillikin and I believe some work may be necessary in order to make the analyzer and the front end behave consistently in Dart 2.3.  I'll be meeting with him tomorrow to clarify the details and I'll update this bug after I do so.

**Comment by stereotype441** [comment]
Ok, I've just finished meeting with @kmillikin.  The FE is planning to ship the full functionality of this feature in Dart 2.3, so the analyzer team will plan to do so as well.

**Comment by dgrove** [comment]
Is there more remaining here for 2.3? ( #36296 is no longer in the milestone, but is in the meta-issue list above)

**Comment by bwilkerson** [comment]
Not all of the SDK constraint checks have been implemented, but I'm not sure that the remaining ones are worth worrying about. I don't know how @stereotype441 feels about it, but I'd be fine with closing this.

**Comment by stereotype441** [comment]
Closing since the only remaining work is covered under #36296
