### ISSUE TITLE
No error in analyzer for covarians super invocation in mixin

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#35111]
Example:

```dart
class A {
  bar(num n) {}
}

mixin M on A {
  test() {
    super.bar(3.14); // Runtime error: type 'double' is not a subtype of type 'int' of 'i'
  }
}

class B extends A {
  bar(covariant int i) {}
}

class MA extends B with M {}

main() {
  new MA().test();
}
```
There should be a compile error. Even for a covariant parameter, we do not drop the requirement that an invocation must pass arguments of assignable types (and here the statically known argument type for the superinvocation in `B with M` is `int`, but the argument is a `double`).

Dart VM version: 2.1.0-dev.9.3 (Thu Nov 8 01:13:22 2018 +0100) on "windows_x64"

**Comment by lrhn** [comment]
I think I'd be fine to with litting this compile and fail at run-time.

The current specification does not make an exception for mixin-created classes, it just requires each class, and each super invocation, to be consistent. The intent of the mixin declaration specification was that you only need to check the super invocations against the interface, and the super-class against the interface for methds that are super-invoked. Having to check the concrete super-invocation for a covariant argument breaks that.
It also may not be the right thing to do, because it will disallow perfectly good programs.

The super-invocation of a mixin is basically intended as an interface invocation. A `convariant` argument is a way to break interface safety by adding a run-time check. We allow this because there are use-cases where the argument will always follow the same conventions, even if we cannot statically see that.

When we disallow this code, then we might disallow instances where the super-invocation is fine, because the argument has an underlying invariant that makes it match the covariant parameter, even if the static type does not.

**Comment by eernstg** [comment]
Right, I argued in https://github.com/dart-lang/sdk/issues/34693#issuecomment-427733456 that this should be a compile-time error, because that's a direct consequence of the model that the language specification uses, where a mixin application `C with M` is specified to be equivalent to a declaration of a subclass of `C` (containing various material including certain declarations from `M` plus some forwarding constructors).

However, the [mixin feature specification](https://github.com/dart-lang/language/blob/master/accepted/2.1/super-mixins/feature-specification.md) specifies a different check when it comes to superinvocations in method bodies of the mixin:

```
we check that the actual super-class of a mixin application of $A<U, V>$ has valid implementations of super$A<U, V>.m for each member that is invoked via a super invocation in $A$.
```

This means that in a case like `bar(covariant int i)` in `B` we just note that this _is_ an admissible implementation of `bar(num n)`, and then we do not raise an error like the one that I argued we should raise (based on the "equivalent to class declaration model").

So I'll need to think about how we can adjust the specification to reflect this, but it is indeed consistent with the feature spec to postpone this error to run time.

**Comment by nshahan** [comment]
@lrhn @eernstg 

Could someone take a look at the test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Super-mixins/covariance_t07.dart

Based on the comment at the top I believe it is meant to be testing for the runtime failure discussed in this thread. Currently the test is failing (no exception thrown) on all backends but the example shown in the first post here does throw as expected. Is the test constructed correctly?

**Comment by eernstg** [comment]
The test should use `new X()` rather than `new Y()` in line 43.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/co19/issues/1541.

**Comment by eernstg** [comment]
I'll close this issue.

The conclusion here is that it is too costly to re-check superinvocations of methods in mixins (such as `super.bar(3.14)`) at mixin each application (such as `B with M`). We will check such superinvocations once when checking the mixin, based on the `on` clause, and ignore the fact that it can be detected at compile time that this invocation will fail in `MA`. It is then a dynamic error if an invocation with a type violation is executed at run time.

Note that only `covariant` parameters can make a correct override fail in this manner. This implies that normal invocations of `bar`, e.g., with receiver type `A`, can also be accepted by the type checker, and yet fail with a type error at run time. In other words, we're only allowing this dynamic type error for methods that are already prone to cause dynamic type errors.

The corresponding spec update is handled in https://github.com/dart-lang/language/issues/2625. There is no known implementation effort, the dynamic error is already raised as expected in several tests.
