### ISSUE TITLE
(Set Literals) VM Support

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35124]
***** Request: 
As per implementation Plan:

Task5 : Task2 (VM support)
- [ ] [VM implements backend support]()

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by askeksa-google** [comment]
The initial implementation of set literals will desugar them in the front end such that no changes are necessary in the VM. Thus VM support for set literals is postponed until such a time that we decide (for performance of other reasons) to change this implementation strategy to implement set literal support directly in the backends.

The VM code will contain some references to this issue in comments (added by https://dart-review.googlesource.com/c/sdk/+/85681), so those should be kept in sync if this issue is closed or re-purposed.

**Comment by alexmarkov** [comment]
In order to optimize set literals in VM, I think we should do the following:

- [ ] Provide optimized implementation in core library for const and non-const set literals (like _ImmutableMap and Map._fromLiteral).
- [ ] Support SetLiteral kernel AST nodes in VM-specific kernel transformations such as constant evaluation and TFA.
- [ ] Support SetLiteral kernel AST nodes in VM - touch ScopeBuilder, StreamingFlowGraphBuilder, ConstantEvaluator, KernelReaderHelper::SkipExpression(), KernelFingerprintHelper::CalculateExpressionFingerprint().
- [ ] Support SetLiteral kernel AST nodes in bytecode generator.

**Comment by mit-mit** [comment]
@a-siva @alexmarkov is this not done?

**Comment by a-siva** [comment]
We think it is not necessary at this point to have special nodes to implement 'set literal' directly in the backend. I have created a new issue https://github.com/dart-lang/sdk/issues/36077 (enhancement) for optimized intrinsified implementation for set literal operations in core library.

Closing this as done.
