### ISSUE TITLE
Flush the analysis server cache after each bot run

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#35161]
We believe that the build bots keep the analysis cache in ~/.dartServer/.analysis-driver and suspect that this cache is not getting deleted on the Flutter/Dart head-head-head bot. As a result, any cached errors are continued to be reported until a file change that invalidates them., leading to problems. We need to have the cache deleted to avoid this problem

See the comments for https://dart-review.googlesource.com/c/sdk/+/84041 for some background.

**Comment by athomas** [comment]
Is it possible to make the analysis server put it's cache in a different place by means of an argument or an environment variable?

**Comment by bwilkerson** [comment]
Unless I'm missing something when looking at the code, there currently is no way to do so.

It would be possible to add such support, but I don't know off hand how long that would take.

**Comment by athomas** [comment]
@sortie do we already have solved this for benchmarks?

It would be a lot cleaner to implement this in the infrastructure if we had some way to move the cache out of the home directory rather than having to delete it from where it is. Basically, we'd move it to a directory that is guaranteed by the infrastructure to be cleaned after every run. This is what we do with the pub cache for pub integration tests (see https://www.dartlang.org/tools/pub/environment-variables).

**Comment by sortie** [comment]
See https://dart-review.googlesource.com/c/sdk/+/70540

ANALYZER_STATE_LOCATION_OVERRIDE can be set to a directory. I do that when running the analyzer benchmarks.

**Comment by stereotype441** [comment]
Is the analyzer branch head-head-head bot setting ANALYZER_STATE_LOCATION_OVERRIDE?  The failure in https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/flutter-analyze-analyzer/155 looks like it was caused by this issue.

**Comment by athomas** [comment]
https://chromium-review.googlesource.com/c/chromium/tools/build/+/1608425/
Should fix this for all test matrix-based builders when it lands.
