### ISSUE TITLE
Analyzer Doesn't Warn About Bad Assignment

### ISSUE THREAD

**Issue by corwinsheahan-wf** [dart-lang/sdk#35197]
Dart version: 2.1.0

Hi there!

I've found what may be a bug in the dart analyzer. 

The following code produces this run time exception: 
`Uncaught exception:
TypeError: Instance of 'JsLinkedHashMap<dynamic, dynamic>': type 'JsLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'`

Here's the snippet:
```
class Foo {
  set fooValue(Map<String, dynamic> value) => null;
}

void main() {
  var badMap = {};
  badMap[10] = 'value1';
  Foo()..fooValue = badMap;
}
```
This code exhibits no analyzer errors/warnings, despite an assignment from a map keyed with `dynamic` to one keyed with `String`. Should there be an analyzer error on `..fooValue = badMap`.

**Comment by lrhn** [comment]
Dart allows assignments that are not safe, so called "implicit down-casts".
Because `Map<dynamic, dynamic>` is a super-type of `Map<String, dynamic>`, the value of `badMap` might actually be a `Map<String, dynamic>`. So, the static type system allows the assignment `Foo()..fooValue = badMap`, because it might succeed, but it implicitly inserts a run-time check to ensure that the value is actually of the correct sub-type.
It wasn't, so the assignment fails at run-time.

**Comment by eernstg** [comment]
@corwinsheahan-wf, you can make each implicit downcast an error by giving the command line option `--no-implicit-casts` to the analyzer.

**Comment by eernstg** [comment]
`badMap` will be a `Map<dynamic, dynamic>` because there is no information available at the declaration to give it any other type (and we consider it too fragile to use the entire scope of a variable in the inference of the type of that variable, so the type will be determined from its declaration alone).

So it's OK to store a key-value pair which is of types `String` and `String`, respectively, but you cannot pass `badMap` to `fooValue`, because it wants a `Map<String, dynamic>` (or any subtype thereof).

So there's an implicit downcast, but they won't change any objects, they will just make the program throw if we encounter an object of type `T` and the required type is `S`, and `T` is not a subtype of `S`.

**Comment by corwinsheahan-wf** [comment]
Gotcha, thanks for the reply @eernstg!

**Comment by stereotype441** [comment]
Closing since the analyzer is behaving correctly
