### ISSUE TITLE
when implements concrete class(Implicit interfaces),the subclass constructor with parameters "super" syntax error

### ISSUE THREAD

**Issue by tearf001** [dart-lang/sdk#35209]
* Dart SDK Version : Dart SDK 2.1.0
* happened at https://dartpad.dartlang.org/
* Chrome
````dart
class Person {
  var _name;
  Person(this._name);  // or  Person(String s) {  _name = s ; }
  //...
}
// An implementation of the Person interface.
class Impostor implements Person {
  var _name;
  Impostor(String s):super(s);//Error: Too many positional arguments: 0 allowed, but 1 found.
  //....
}
````
It do "super"in different way from "extends", these codes can work when using "extends".
Maybe I don't get the idea of Dart's implements(Implicit interfaces).
some workable codes like these
````dart
Impostor(String s):super();
````
but since the super class has no "no-parameter" constructor, what does it mean?

**Comment by lrhn** [comment]
The difference between `extends` and `implements` is that with `extends` you inherit the implementation, with `implements` you do not, you merely promise to implement the same members yourself.

When you extend a class, you inherit its members and state, so you also have to initialize that state. That's why you have to call the superclass constructor.
When you implement an interface, you get no members or state that way, so it makes no sense to call a constructor of the interface (and indeed, you can't). The interface is a "super-interface", not a "super-class".

In your imposter constructor, you *can* write `Imposter(String s): super();`. The reason that works is that `Imposter` does have a super-class: `Object`. If you write no `extends` clause, then you implicitly `extends Object`. So, the `super()` refers to `Object`'s unnamed zero-argument constructor, not to `Person`.
You don't `*need* to write the `super()` call. If you write no super-call in a generative constructor initializer list, it automatically adds a `super()` for you.

**Comment by tearf001** [comment]
Thank you every much.
I'v got it . I do NOT get the idea constructor with this parameter, it plays as default constructor.
When I create constructor without parameter ,complier remind me of "already has default constructor"
I 'v learned the extends and implements again.
