### ISSUE TITLE
Dart - Stream<T>.last not returning anything?

### ISSUE THREAD

**Issue by ZhennanWu** [dart-lang/sdk#35211]
Stream<T>.last.then(foo) is never executed. I don't know if it is me using it the wrong way. If it is, then what is the correct way of getting the last element in a Stream? I'm having a hard time finding relevant demos in Dart docs.

Dart SDK : 2.1.0
Platform: Windows, and [Dartpad](dartpad.dartlang.org)

## Demo Code

```
import 'dart:async';

void main(){
  final sc=StreamController<int>();
  final s=sc.stream;
  sc.add(1);
  sc.add(2);
  print("Printing the last\n");
  s.last.then(print);
  sc.add(3);
  
  
  final sc2=StreamController<int>();
  final sbc2=sc2.stream.asBroadcastStream();
  sc2.add(1);
  sc2.add(2);
  print("Broadcast stream printing...\n");
  sbc2.first.then(print);
  sbc2.last.then(print);
  sc2.add(3);
}

```
## Output

```
Printing the last

Broadcast stream printing...

1
```

**Comment by lrhn** [comment]
The `Stream.last` call will not know which event is the last event until you *close* the stream controller (to send a "done" event). For all it knows, another event may be added at a later time, and then that event should be the "last" event.
Since neither stream is closed, the `last` futures never complete. You must call `sc.close()` and `sc2.close()` to trigger the completion of the `last` futures.

**Comment by ZhennanWu** [comment]
Oh... Thank you for the reply.

**Comment by kayumarie** [comment]
What you are looking for is `Stream#value`
