### ISSUE TITLE
Tried to initialize from a previous compilation (build/app.dill), but couldn't. Error message was 'NoSuchMethodError: The method 'getReference' was called on null

### ISSUE THREAD

**Issue by riteshbxr** [dart-lang/sdk#35216]
Error message requested me to file this bug!

* on VSCode (Dart Extension 2.20, Flutter extension 2.20)
* SDK Versions
> Flutter 0.9.5-pre.3 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision c0605c1950 (5 days ago) • 2018-11-15 17:10:43 +0530
> Engine • revision 5646e86a6f
> Tools • Dart 2.1.0 (build 2.1.0-dev.9.3 
> 9c07fb64c4)

* Compiling for android
* Android Device Lenovo TB3 730X

> flutter run
> Launching lib/main.dart on Lenovo TB3 730X in debug mode...
> Initializing gradle...                                       0.8s
> Resolving dependencies...                                    2.8s
> Gradle task 'assembleDebug'...
> 
> Compiler message:
> Warning: Tried to initialize from a previous compilation (build/app.dill), but couldn't. Error message was 'NoSuchMethodError: The method 'getReference' was called on null.
> Receiver: null
> Tried calling: getReference()'. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

----

**Comment by jensjoha** [comment]
Thank you for reporting this.
I think this was fixed with 4a7f3d575c8b5856650b1c2e31c9f1abfa60fadc (which as far as I can tell wasn't included in the "Dart 2.1.0 (build 2.1.0-dev.9.3 9c07fb6)").

I will update the message we give to provide more info though --- that way we should in the future be able to say with more certainty if something was already fixed, or, if not, actually fix it.

Thanks again for taking the time to report this issue.
