### ISSUE TITLE
FutureOr<void> function warns of missing return

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35237]
With the following code:

```dart
void a() {}
FutureOr<void> b() {}
```

The second function gives a hint about a missing return:

> This function has a return type of 'FutureOr\<void\>', but doesn't end with a return statement.

It's not entirely obvious what I should do - it's not valid to write `return void` and I can't change the signature because it comes from a base class (the `void` is a type arg and has a real type for other implementations). It doesn't complain if I write `return null` though it feels weird (and I've not got as far as running it to confirm that's ok yet).

**Comment by DanTup** [comment]
Actually, I don't get any warnings if I change the return type to just `void` even though the method it's overriding is `FutureOr<T>` so maybe that's the better solution :-)

**Comment by eernstg** [comment]
The feature specification ['invalid_returns.md'](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/invalid_returns.md) does not make it explicit in which cases it is allowed to complete the body of a function normally (that is, to "fall through" at the end), and it allows only `void`, `Null`, and `dynamic` as the declared return type.

Basically, `FutureOr<void>` is outlawed because it is confusing and error prone to fall through (and implicitly return `null`) to that return type.

With the given information about the broader context, it sounds to me like `void` is a quite suitable return type here.

**Comment by DanTup** [comment]
So is it valid to override a `Future<T>`-returning method with just `void` when `T` is `void` (I guess the same applies to any other type - overriding a `FutureOr<int>` and just declaring `int` as the return type)?

I expected that the override would have to declare the exact same type, but certainly this seems to work in my tests (assuming my tests correctly cover this 🤷‍♂️).

**Comment by DanTup** [comment]
And a slight tangent, I guess the same question applies to arguments... If I use `void` as a typearg and it's used as a param, what's the best way to write it?

```dart
abstract class Foo<T> {
  doFoo(T thing);
}

class Bar extends Foo<void> {
  doFoo(void _) {
    // Is `void _` the best option here?
  }
}
```

**Comment by DanTup** [comment]
> The type FutureOr<void> is not conceptually very useful, by the way

Yeah, I didn't set out to use it, it just was a consequence of some generics. I have a base class for some handlers - some will return values and some will not. It feels clumsy making all those that do not `return null;` so using `void` as the return type arg seem (seemed?) like a reasonable thing.

> I think `doFoo(void _)` is fine.

Cool :) It's similar to the above - my generic handler has a type arg for the parameter type, but one of the methods doesn't take the arg so I use void.

Unfortunately calling it isn't quite so simple, because it doesn't seem valid to pass `void` or not pass an argument:

```
abstract class Foo<T> {
  doFoo(T thing);
}

class Bar extends Foo<void> {
  doFoo(void _) {}
}

test() {
  final a = new Bar();
  a.doFoo(); // invalid
  a.doFoo(void); // invalid
  a.doFoo(null); // valid?;
}
```

It feels dirty passing `null` when the sig says `void`, but I'm guessing there's nothing better I can put there?

It seems like there's probably nothing to do here, so unless you think there's something that can/should be improved, feel free to close this. Thanks for the info!

**Comment by eernstg** [comment]
> doesn't seem valid to pass `void` or not pass an argument

The overriding declaration is allowed to make the argument optional: `doFoo([void _]) {}`, so that would enable the form `doFoo();` (this is because `Function([void])` is a subtype of `Function(T)` for all `T`). Passing `void` does not work because that's syntactically not an identifier (for historical reasons). Passing `null` is valid (and fine: It makes sense to use a value with no information in a situation where that value is intended to be discarded), but it is not so informative (because anyone who looks at the call site might think that this is an argument of some useful type `T`, and we're passing `null` in order to indicate that it's omitted, or something like that). So `doFoo()` looks best to me at this point. ;)

> feel free to close this. Thanks for the info!

Will do, and thank you!
