### ISSUE TITLE
Implicit const does not work on default values

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#35248]
Simple example:

```dart
void f([List<String> names = []]) {}
//                           ^^ Default values of an optional parameter must be constant.

```

**Comment by lrhn** [comment]
This is a deliberate choice. We want to keep our options open wrt. making default values non-constant. If we made them implicit constant now, then people could write code, like yours above, that would change behavior if we stopped requiring them to be constant.

There are two places where we require constants, but do not force the expression to be constant: Default values and field initializers of classes with constant constructors. The latter is because there is no *syntactic* context that shows you that the expression is constant (unlike expressions inside a `const`, or specific positions where const is always required), so we want you to make it explicit.
