### ISSUE TITLE
The message sent by client SecureSocket will be separated at 4096th byte. 

### ISSUE THREAD

**Issue by willyabs** [dart-lang/sdk#35249]
When client SecureSocket continually send messages util 4096th byte, the message is separated into two parts to server. For example, an message is 100 bytes, when client have sent 41 messages, the 41th message that server received will be separated into 96 bytes and 4 bytes.

These are the sample apps that can repro this issue:
- The server app is written using android sdk:
  https://github.com/willyabs/TestServerSocket
- The client app is written using flutter sdk:
  https://github.com/willyabs/Flutter-client-socket-sample

Issue log:

- client send to server:
  I/flutter ( 3774): send bytes len: 1000
I/flutter ( 3774): send bytes len: 1000
I/flutter ( 3774): send bytes len: 1000
I/flutter ( 3774): send bytes len: 1000
I/flutter ( 3774): send bytes len: 1000

- server received:
D/TcpClient: receive bytes len: 1000
D/TcpClient: receive bytes len: 1000
D/TcpClient: receive bytes len: 1000
D/TcpClient: receive bytes len: 1000
**D/TcpClient: receive bytes len: 96
D/TcpClient: receive bytes len: 904**

Build System:
- Flutter 0.10.2 • channel beta • https://github.com/flutter/flutter.git
- Framework • revision d8cbb80206 (4 weeks ago) • 2018-10-26 01:30:21 -0400
- Engine • revision 6c2ade9fa2
- Tools • Dart 2.1.0-dev.8.0.flutter-bf26f760b1
- Using Windows

**Comment by sortie** [comment]
Hi, new maintainer of dart:io here. Can you clarify this issue a bit? Does this contradict what SecureSocket is documented to do? If I understand correctly, you consider this a performance issue?

What you're describing sounds like the ring buffer algorithm. I'm guessing the SecureSocket implementation, the SSL library, the kernel, or any network devices in the middle, or even the client's kernel, or the client's SSL library, or the client's SecureSocket implementation might be fragmenting the packet in this way. Messages are usually received into a ring buffer, and it wraps when it is full. It's probably more efficient to invoke the callback twice with each part of the fragmented message rather than running it once with a combined message, although that does depend on whether your application can handle fragments.

Fragmentation is normal though for TCP applications as it does not guarantee that segment boundaries are preserved, so I imagine the Dart socket implementation would be allowed to too.

I guess the next steps would be to identify exactly where this fragmentation is coming from. Can you supply a minimal dart program that demonstrates the problem? Is this limited to SecureSocket, or does it also happen under the regular non-encrypted Socket? It'd be interesting to use tcpdump to check if the messages were fragmented in transit.

**Comment by sortie** [comment]
Hi, any update?

**Comment by hatem-amer** [comment]
The TLS 1.3 specification (RFC 8446) defines a maximum plaintext record size of 16384 bytes.
But RawSecureSocket wont send more than 4096 bytes in a single TLS 1.3 Application Data record

[Wireshark_4096_1.txt](https://github.com/user-attachments/files/22699503/4096_1.txt)
```dart
import 'dart:convert';
import 'dart:io';

void main(List<String> args) async {
  final socket = await RawSocket.connect(InternetAddress("192.0.46.8"), 443);
  final sslSocket = await RawSecureSocket.secure(
    socket,
    host: "www.iana.org",
    keyLog: (line) => File("/tmp/SSLKEYLOGFILE.log").writeAsStringSync(line, mode: FileMode.writeOnlyAppend),
  );
  await for (var event in sslSocket) {
    switch (event) {
      case RawSocketEvent.read:
        print(sslSocket.read()?.lengthInBytes);
        break;
      case RawSocketEvent.write:
        sslSocket.writeEventsEnabled = false;
        final buffer = ascii.encode(_req.padRight(4096 + 1));
        // final buffer = ascii.encode(f.padRight(16384));
        final wrote = sslSocket.write(buffer);
        print("wrote: $wrote out of ${buffer.lengthInBytes}");
        break;
      default:
        throw "Unexpected event $event";
    }
  }
}

final _req = [
  'GET / HTTP/1.1',
  'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'Accept-Encoding: gzip, deflate, br, zstd',
  'Accept-Language: en-US,en;q=0.9',
  'Cache-Control: no-cache',
  'Connection: keep-alive',
  'DNT: 1',
  'Host: www.iana.org',
  'Pragma: no-cache',
  'Sec-Fetch-Dest: document',
  'Sec-Fetch-Mode: navigate',
  'Sec-Fetch-Site: none',
  'Sec-Fetch-User: ?1',
  'Upgrade-Insecure-Requests: 1',
  'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36',
  'sec-ch-ua: "Chromium";v="134", "Not:A-Brand";v="24", "Google Chrome";v="134"',
  'sec-ch-ua-mobile: ?0',
  'sec-ch-ua-platform: "Linux"',
  '',
].join("\r\n");
```
