### ISSUE TITLE
Fix dart:html SharedArrayBuffer

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#35344]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

- Needs ctor that takes in a `length`
- Needs a `slice` method
- Need to figure out how to align with `dart:typed_data`

**Comment by kevmoo** [comment]
Along with [Atomics](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics) allows sharing data without copying via shared workers and WASM

**Comment by nullrocket** [comment]
Is there any way to work around this not being fully implemented in dart:html ?

**Comment by kevmoo** [comment]
@nullrocket – are there specific things you NEED implemented?

**Comment by srujzs** [comment]
> Is there any way to work around this not being fully implemented in dart:html ?

Yes, the suggested way is to write your own interop using `package:js`'s `@staticInterop` to handle missing/broken methods. See https://github.com/dart-lang/sdk/blob/main/sdk/lib/html/doc/WORKAROUNDS.md for more details on how you can do this. Let me know if this insufficient for your use case, thanks!

**Comment by nullrocket** [comment]
I could get a SharedArrayBuffer instantiated using the workarounds.md mentioned above, I also could get Atomics working using it.  What I couldn't figure out is passing an instance of a SharedArrayBuffer as an Int32Array / Int32List  parameter to the atomics methods.  I will be honest trying to use that doc for someone who isn't super familiar with the internals of the js interop libs to begin with is like throwing random magic at the issue til it kinda works.   Not saying that its useless but it does assume a lot more familiarity with the problem than I have to begin with.

I will give it another shot with the latest updates mentioned by the closing commit and see where I am.

**Comment by srujzs** [comment]
I don't think the `dart:html` changes will help with that - it just exposes missing members.

> What I couldn't figure out is passing an instance of a SharedArrayBuffer as an Int32Array / Int32List parameter to the atomics methods.

The `typed_data` (where many of the array types live) story is complicated, and I'm not sure we expose methods to do something like this there, so I'd just use something like this with `package:js` and `js_util`:

```
@JS('Int32Array')
external Object? get int32ArrayConstructor;

...

var array = js_util.callConstructor(int32ArrayConstructor, [sharedArrayBuffer]);
```

I agree that our documentation could use work/consolidation. The workarounds doc was more meant to workaround the common issues people see using interop, provided they are familiar with `js_util` and `package:js`. I'm not sure how familiar you are with both libraries, but https://pub.dev/packages/js has some information on more general usage. `js_util` unfortunately just has the code documentation I believe.

FYI longish term - we want to move to more interop-based bindings instead of the confusing `dart:html` syntax we have today. Hopefully, the consolidation of tooling and libraries will make it more evident how to use them.
