### ISSUE TITLE
prohibit access to members that are not marked as entry points through Dart VM C API

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#35369]
Flutter would like to have a way to test that all members which are accessed by name from native side are correctly annotated with `@pragma('vm:entry-point')` annotation. 

Currently we print an error to the console, but this is not discoverable and can't be used for testing. 

We should introduce a VM flag `--verify-entry-points` which turns on strict checking of `@pragma('vm:entry-point')` annotations. When this flag is turned on any attempt to access a member by name via C API should result in an error. 

Then we should turn on this flag for Flutter so that we catch any issues with missing annotations as early as possible.

/cc @goderbauer

**Comment by mraleph** [comment]
@sjindel-google please take a look at this next, we just hit another case where Engine was reflectively accessing something that it should not: it was tearing off a static function, which is not something that `entry-point` annotation allows one to do.

**Comment by sjindel-google** [comment]
We should definitely extend the error reporting to looking up other members besides classes.

However, I don't believe Flutter should enable the behavior of crashing on non-annotated member lookup outside testing. I enabled this previously and had to revert it due to https://github.com/flutter/flutter/issues/24329. This source of that bug seems to be the consequence of incomplete Flutter test coverage: the `UNREACHABLE()` was never triggered during testing, because there was no test which tried to resolve the specific member which was not annotated. It's unfortunate then if we break users who could have otherwise run their code successfully in non-obfuscated mode.

Currently we print an error message on lookup of a non-annotated class. I'm going to extend this to cover all members which can be resolved. I'll also add a flag `--verify-entry-points` which makes this error fatal.

**Comment by mraleph** [comment]
>  It's unfortunate then if we break users who could have otherwise run their code successfully in non-obfuscated mode.

I think there are two parts to it:

- We need to make sure that potential errors are caught in JIT mode during testing. This means that Flutter `debug` mode should enable a stricter testing: whenever we try to access a member that is not marked with `entry-point` annotation it should *throw an error*.

- We need to report good error messages when people are trying to access non-existent members in AOT (before crashing).

I think a very important thing here is that there is no guarantee that user would run their code successfully - something that is not tree-shaken today, might get tree-shaken tomorrow.

**Comment by sjindel-google** [comment]
I think we agree. I'm not sure how to address the second point though: are you suggesting that we should always print an error when a member lookup fails? There's no way in general to know whether the lookup failed because the member was tree-shaken or if it never existed.
