### ISSUE TITLE
test.dart has misleading error if the builder hasn't built the base commit

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#35360]
This may be because I'm using a builder we just turned on. But a better error message would be nice:

```
./tools/test.dart -b dart2js-minified-csp-linux-chrome language2/conditional_import_string_test
```

produces:
```
Base commit is 1a814793cec106dffa2703f6a71321ee49570b13
Finding build to compare with...
Unhandled exception:
NoSuchMethodError: The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      buildNumberOfCommit (file:///usr/local/google/home/sigmund/dart/git_all/sdk/tools/test.dart:107:14)
<asynchronous suspension>
#2      main (file:///usr/local/google/home/sigmund/dart/git_all/sdk/tools/test.dart:155:29)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

/cc @sortie

**Comment by sortie** [comment]
Hi Siggi,

This happens when your base commit hasn't been built on the builder in question. It's because the buildbucket API used to locate builder builds didn't respond an empty 'builds' when there were no builds, but instead omitted the field entirely. Oops, I knew that, but wrote the code wrong. I'll just make a quick fix.

Btw, you were using an older version of test.dart from December 4, some key bug fixes to test.dart went in on December 7.

Jonas

**Comment by sortie** [comment]
Fixed.
