### ISSUE TITLE
Dart lang should provided us an web framework 

### ISSUE THREAD

**Issue by netroby** [dart-lang/sdk#35363]
Dart lang should provided us an web framework .
Which like kotlin provided us ktor, Scala provided us playframework, Groovy provided us Grails.
Dotnet provided us asp.net mvc.
If there was a web framework built with dart (with official support)
More developers would like learn dart and use it.
Dart lang is a language which been  underestimate |

**Comment by mrmcq2u** [comment]
Whats wrong with just using angel?

**Comment by Indribell** [comment]
I had this same discussion just yesterday with a college. For Dart being a very Web focused language, it is strange how a lot of libraries like mysql, postgresql, etc are all external 3th party developed packages. 

This has even have created issue where people recommended sqljocky but this library is now incompatible with Dart 2. Some people have continued the work under a different package name but its not exactly what you expect. The whole switch over from Dart 1 to Dart 2 is slightly messy because public information is now out of date and now makes people look at libraries that are not even supported anymore. 

For a product developed at Google, it very strange that this detail of Google serving old information ( because of the naming ) gets overlooked. Might have been better to use a different name.

**Comment by netroby** [comment]
@mrmcq2u angle-dart seems good, but pub as official tools, should be have the tool inside the box.

**Comment by dgrove** [comment]
https://webdev.dartlang.org/angular is a full-featured web framework provided by google. Hope this meets your needs.

**Comment by natebosch** [comment]
The original request was for a server-side web framework angular is a client side web framework.

For now the Dart team is focusing on being an awesome client side language. We're really happy that the community is also doing cool things on the server side - as of right now that won't be an area that the Dart team is prioritizing.

**Comment by Indribell** [comment]
Thank you for this update. This also explain the lacking AOT compiler in the SDK.

As we wanted Dart for a more all around projects ( including server focused projects ), this means we will drop our exploration of Dart for future project. Thank you again for this update.

**Comment by netroby** [comment]
ping @dgrove , Angular not server side web framework.
