### ISSUE TITLE
lib_2/isolate/issue_21398_parent_isolate1_test crashes out on reload

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#35374]
```
FAILED: dartk-vm debug_x64 lib_2/isolate/issue_21398_parent_isolate1_test
Expected: RuntimeError
Actual: Crash

--- Command "vm" (took 08.000718s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --no-background-compilation --hot-reload-test-mode --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/lib_2/isolate/issue_21398_parent_isolate1_test.dart

exit code:
-6

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
type '_SendPortImpl' is not a subtype of type 'String'
#0      spawnFuncTest.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/lib_2/isolate/issue_21398_parent_isolate1_test.dart:75:18)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#4      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#5      _StreamController._add (dart:async/stream_controller.dart:640:7)
#6      _StreamController.add (dart:async/stream_controller.dart:586:5)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
../../runtime/vm/isolate.cc: 1919: error: Isolate did not reload before exiting and --check-reloaded is enabled.

thread=5163, isolate=issue_21398_child_isolate11.dart:main()(0x55ebd5752000)
  [0x000055ebd2be5f9c] dart::Profiler::DumpStackTrace(void*)
  [0x000055ebd2be5f9c] dart::Profiler::DumpStackTrace(void*)
  [0x000055ebd2e9bf02] dart::Assert::Fail(char const*, ...)
  [0x000055ebd2ad227b] dart::Isolate::Shutdown()
  [0x000055ebd2a84685] dart::Dart::ShutdownIsolate(dart::Isolate*)
  [0x000055ebd2ad170d] Unknown symbol
  [0x000055ebd2b0b7cc] dart::MessageHandler::TaskCallback()
  [0x000055ebd2ca69ac] dart::ThreadPool::Worker::Loop()
  [0x000055ebd2ca648a] dart::ThreadPool::Worker::Main(unsigned long)
  [0x000055ebd2bdfcf5] Unknown symbol
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-reload-linux-debug-x64 lib_2/isolate/issue_21398_parent_isolate1_test
```

**Comment by dcharkes** [comment]
All bots except analyzer and fasta are flaking.

Since yesterday (2019-02-21 22:39:39 UTC) this test started flakily passing.

On the reload-rollback bots the runtime error shows up as a crash.

```sql
select configuration, result, count(*) as count, min(commit_time) as earliest, max(commit_time) as latest
from `dart-ci.results.results`
where name = "lib_2/isolate/issue_21398_parent_isolate1_test"
group by configuration, result
order by configuration, result
```

Row | configuration | result | count | earliest | latest |  
-- | -- | -- | -- | -- | -- | --
1 | analyzer-asserts-linux | Pass | 1100 | 2018-12-07 15:51:28 UTC | 2019-02-22 02:23:45 UTC |  
2 | analyzer-asserts-mac | Pass | 855 | 2018-12-07 13:19:24 UTC | 2019-02-22 02:23:45 UTC |  
3 | analyzer-asserts-win | Pass | 989 | 2018-12-07 15:51:28 UTC | 2019-02-22 02:23:45 UTC |  
4 | analyzer-linux | Pass | 1198 | 2018-12-07 15:51:28 UTC | 2019-02-22 02:23:45 UTC |  
5 | app_jitk-linux-debug-x64 | Pass | 7 | 2019-02-21 22:48:10 UTC | 2019-02-22 02:23:45 UTC |  
6 | app_jitk-linux-debug-x64 | RuntimeError | 678 | 2018-12-07 13:19:24 UTC | 2019-02-21 21:23:19 UTC |  
7 | app_jitk-linux-product-x64 | Pass | 10 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
8 | app_jitk-linux-product-x64 | RuntimeError | 1111 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
9 | app_jitk-linux-release-x64 | Pass | 10 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
10 | app_jitk-linux-release-x64 | RuntimeError | 1050 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
11 | dartk-asan-linux-release-x64 | Pass | 10 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
12 | dartk-asan-linux-release-x64 | RuntimeError | 909 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
13 | dartk-checked-linux-release-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
14 | dartk-checked-linux-release-x64 | RuntimeError | 1163 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
15 | dartk-linux-debug-ia32 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
16 | dartk-linux-debug-ia32 | RuntimeError | 960 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
17 | dartk-linux-debug-simdbc64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
18 | dartk-linux-debug-simdbc64 | RuntimeError | 1077 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
19 | dartk-linux-debug-x64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
20 | dartk-linux-debug-x64 | RuntimeError | 1072 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
21 | dartk-linux-product-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
22 | dartk-linux-product-x64 | RuntimeError | 1140 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
23 | dartk-linux-release-arm64 | Pass | 9 | 2019-02-21 22:48:10 UTC | 2019-02-22 02:23:45 UTC |  
24 | dartk-linux-release-arm64 | RuntimeError | 827 | 2018-12-07 13:19:24 UTC | 2019-02-21 21:23:19 UTC |  
25 | dartk-linux-release-ia32 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
26 | dartk-linux-release-ia32 | RuntimeError | 1141 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
27 | dartk-linux-release-simarm | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
28 | dartk-linux-release-simarm | RuntimeError | 1090 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
29 | dartk-linux-release-simarm64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
30 | dartk-linux-release-simarm64 | RuntimeError | 1052 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
31 | dartk-linux-release-simdbc64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
32 | dartk-linux-release-simdbc64 | RuntimeError | 1124 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
33 | dartk-linux-release-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
34 | dartk-linux-release-x64 | RuntimeError | 1145 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
35 | dartk-mac-debug-simdbc64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
36 | dartk-mac-debug-simdbc64 | RuntimeError | 832 | 2018-12-07 13:19:24 UTC | 2019-02-21 21:23:19 UTC |  
37 | dartk-mac-debug-x64 | Pass | 10 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
38 | dartk-mac-debug-x64 | RuntimeError | 822 | 2018-12-07 13:19:24 UTC | 2019-02-21 21:23:19 UTC |  
39 | dartk-mac-product-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
40 | dartk-mac-product-x64 | RuntimeError | 958 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
41 | dartk-mac-release-simdbc64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
42 | dartk-mac-release-simdbc64 | RuntimeError | 956 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
43 | dartk-mac-release-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
44 | dartk-mac-release-x64 | RuntimeError | 952 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
45 | dartk-optcounter-linux-release-ia32 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
46 | dartk-optcounter-linux-release-ia32 | RuntimeError | 1086 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
47 | dartk-optcounter-linux-release-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
48 | dartk-optcounter-linux-release-x64 | RuntimeError | 1149 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
49 | dartk-reload-linux-debug-x64 | Crash | 346 | 2018-12-13 02:24:49 UTC | 2019-02-21 21:23:19 UTC |  
50 | dartk-reload-linux-debug-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
51 | dartk-reload-linux-debug-x64 | RuntimeError | 687 | 2018-12-13 02:24:49 UTC | 2019-02-21 19:39:09 UTC |  
52 | dartk-reload-linux-release-x64 | Crash | 492 | 2018-12-13 12:53:09 UTC | 2019-02-21 21:01:39 UTC |  
53 | dartk-reload-linux-release-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
54 | dartk-reload-linux-release-x64 | RuntimeError | 594 | 2018-12-13 02:24:49 UTC | 2019-02-21 21:23:19 UTC |  
55 | dartk-reload-mac-debug-simdbc64 | Crash | 685 | 2018-12-13 03:07:06 UTC | 2019-02-21 17:28:19 UTC |  
56 | dartk-reload-mac-debug-simdbc64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
57 | dartk-reload-mac-debug-simdbc64 | RuntimeError | 123 | 2018-12-13 19:29:26 UTC | 2019-02-21 21:23:19 UTC |  
58 | dartk-reload-mac-release-simdbc64 | Crash | 521 | 2018-12-13 02:24:49 UTC | 2019-02-21 17:06:49 UTC |  
59 | dartk-reload-mac-release-simdbc64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
60 | dartk-reload-mac-release-simdbc64 | RuntimeError | 390 | 2018-12-13 02:24:49 UTC | 2019-02-21 21:23:19 UTC |  
61 | dartk-reload-rollback-linux-debug-x64 | Crash | 52 | 2018-12-13 02:24:49 UTC | 2019-02-21 21:01:39 UTC |  
62 | dartk-reload-rollback-linux-debug-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
63 | dartk-reload-rollback-linux-debug-x64 | RuntimeError | 989 | 2018-12-13 02:24:49 UTC | 2019-02-21 21:23:19 UTC |  
64 | dartk-reload-rollback-linux-release-x64 | Crash | 68 | 2018-12-13 02:24:49 UTC | 2019-02-20 10:24:10 UTC |  
65 | dartk-reload-rollback-linux-release-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
66 | dartk-reload-rollback-linux-release-x64 | RuntimeError | 1023 | 2018-12-13 02:24:49 UTC | 2019-02-21 21:23:19 UTC |  
67 | dartk-win-debug-ia32 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
68 | dartk-win-debug-ia32 | RuntimeError | 833 | 2018-12-07 13:19:24 UTC | 2019-02-21 21:23:19 UTC |  
69 | dartk-win-debug-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
70 | dartk-win-debug-x64 | RuntimeError | 932 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
71 | dartk-win-product-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
72 | dartk-win-product-x64 | RuntimeError | 1040 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
73 | dartk-win-release-ia32 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
74 | dartk-win-release-ia32 | RuntimeError | 1009 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
75 | dartk-win-release-x64 | Pass | 12 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
76 | dartk-win-release-x64 | RuntimeError | 1032 | 2018-12-07 12:17:55 UTC | 2019-02-21 21:23:19 UTC |  
77 | dartkb-compile-linux-debug-x64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
78 | dartkb-compile-linux-debug-x64 | RuntimeError | 992 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
79 | dartkb-compile-linux-release-x64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
80 | dartkb-compile-linux-release-x64 | RuntimeError | 1050 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
81 | dartkb-interpret-linux-debug-x64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
82 | dartkb-interpret-linux-debug-x64 | RuntimeError | 992 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
83 | dartkb-interpret-linux-release-x64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
84 | dartkb-interpret-linux-release-x64 | RuntimeError | 1050 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
85 | dartkb-mixed-linux-debug-x64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
86 | dartkb-mixed-linux-debug-x64 | RuntimeError | 992 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
87 | dartkb-mixed-linux-release-x64 | Pass | 11 | 2019-02-21 22:39:39 UTC | 2019-02-22 02:23:45 UTC |  
88 | dartkb-mixed-linux-release-x64 | RuntimeError | 1050 | 2018-12-07 15:51:28 UTC | 2019-02-21 21:23:19 UTC |  
89 | fasta-linux | Pass | 965 | 2018-12-07 15:51:28 UTC | 2019-02-22 02:23:45 UTC |  
90 | fasta-mac | Pass | 855 | 2018-12-07 13:19:24 UTC | 2019-02-22 02:23:45 UTC |  
91 | fasta-win | Pass | 872 | 2018-12-07 15:51:28 UTC | 2019-02-22 02:23:45 UTC

**Comment by dcharkes** [comment]
I don't know which commit fixed this yesterday, but as this test is no longer crashing I'm closing this issue.
