### ISSUE TITLE
pkg/analyzer/test/file_system/memory_file_system_test failing on pkg-win-release

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#35387]
The change 68889c97 "Rework the file system tests so that most tests are shared" appears to have broken the memory_file_system_test test on pkg-win-release.

| BOT              | TEST                                                   | RESULT        | EXPECTED |
|------------------|--------------------------------------------------------|---------------|----------|
| pkg-win-release  | pkg/analyzer/test/file_system/memory_file_system_test  | RuntimeError  | Pass     |

The error was first seen in this build: https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/pkg-win-release/3389

Here is the log of when it first occured: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8927426076106741600/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0

I'm not sure about the impact of this bug, so I didn't approve the new failure and left the pkg-win-release builder red. Please either fix the issue, or if the bug is non-critical, please use the new status file free workflow as announced internally to approve the new failure.

**Comment by bwilkerson** [comment]
> I'm not sure about the impact of this bug, so I didn't approve the new failure ...

Thanks! The failing test isn't critical, but as with most of the analyzer and server tests, disabling a single file disables all of the tests in that file, and that's not good. It's much better for us to mark the single test as failing.

> Please either fix the issue ...

I am now testing a possible fix for that test (https://dart-review.googlesource.com/c/sdk/+/87100). If that passes then the bot should turn green again. If not, then I'll fix it a different way.

> ... or if the bug is non-critical, please use the new status file free workflow as announced internally to approve the new failure.

I can't actually do that because of the problems I'm having running the depot tools. I can't get past the first step. :-( I'm continuing to work with the team that supports them to try to fix the problem, but it's a very slow process.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/87100 appears to have fixed it.

**Comment by sortie** [comment]
Yep. Thanks Brian!
