### ISSUE TITLE
Exclude not working when opening a file

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#35475]
_From @marius-h on December 21, 2018 16:34_

Excluding files in the analyzer options and restarting the server afterwards, hides the errors in those files as intended. However, whenever you open up an excluded file, the errors show up in the console as long as you don't restart the analysis server.

### Steps to reproduce

1. Change your analysis_options.yaml file to look like this:
```yaml
analyzer:
  exclude:
    - lib/**.g.dart # exclude generated JSON models

linter:
  rules:
    - always_specify_types
```
2. Add a file which ends with ".g.dart" and use the 'var' keyword in there.
3. Restart the analysis server => no error shows up; as intended
4. Open up the file you've created in Step 2 => errors show up in the analysis console, despite the file being excluded in analysis_options.yaml

### Environment

- IntelliJ IDEA 2018.3 (Ultimate Edition) Build #IU-183.4284.148
- Dart plugin v183.4733
- Flutter plugin v31.3.4
- Dart VM version: 2.1.0-dev.9.4.flutter-f9ebf21297
- Flutter version: Flutter 1.0.0 revision 5391447fae

_Copied from original issue: dart-lang/linter#1322_

**Comment by pq** [comment]
Hi @marius-h.  IIRC this is a side-effect of the way the analysis server prioritizes analysis of open files.

@scheglov, @bwilkerson : could you confirm?

**Comment by kikuchy** [comment]
Still we have same problem. What's going on?

* IntelliJ IDEA 2019.2.4 (Ultimate Edition) Build #IU-192.7142.36, built on October 29, 2019
* Dart plugin v192.7402
* Flutter plugin v40.2.4
* Dart 2.5.0
* Flutter 1.9.1+hotfix.6 revision 68587a0916

**Comment by pq** [comment]
@bwilkerson, @scheglov: would it be reasonable to filter excluded files out from priority paths when we set `priorityFiles`?

https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/analysis/driver.dart#L343-L351

**Comment by bwilkerson** [comment]
I'm not convinced that that's the best way to get what we want. The priority files are the files that should be prioritized for analysis in order to improve the UX (for things like navigation, etc.). Not including an opened file in the list of priority files means that users might see a delay before we have analysis support.

I think it might be better to use the exclusion list to filter some of the notifications (_not_ responses) such as analysis errors. Users have indicated that they never want to see diagnostics in excluded files, but that doesn't mean that they don't want other support.

**Comment by pq** [comment]
> Users have indicated that they never want to see diagnostics in excluded files, but that doesn't mean that they don't want other support.

This makes a lot of sense to me.  Thanks!

**Comment by bounty1342** [comment]
I have almost the same issue.

Differences :
- Vs Code
- Not limited to *.g.dart but all generated files

``` yaml
analyzer:
  exclude:
    - lib/main.reflectable.dart
    - lib/core/internationalization/i18n.dart
    - lib/**.g.dart
```

Regards

**Comment by nstrelow** [comment]
What's the status of this? I have inexperienced teammates which tempted to fix changes in generated .g.dart files.

[json_serializable](https://pub.dev/packages/json_serializable) generates a lot of `as` statements, which I am trying to block with `avoid_as`.

**Comment by lrhn** [comment]
Seems the problem isn't analyzing to find static types and completion, as much as it's applying lints and warnings.
Could we avoid applying lints and warnings to open files, as if they had `ignore_for_file: <everything>`?

**Comment by pq** [comment]
> I think it might be better to use the exclusion list to filter some of the notifications (not responses) such as analysis errors.

@bwilkerson is this filtering on the client or server side?  (I'd expect the latter but just want to be sure.)

**Comment by bwilkerson** [comment]
The client should never need to understand the analysis options file, so everything related to filtering should happen on the server side.

**Comment by scheglov** [comment]
IIRC the issue is that while we don't analyze exclude files when a directory with them is open, we do analyze when we open the file itself, in order to provide semantic services (e.g. highlighting or navigation). And when we analyze, we send diagnostics. And when we close the file, we don't tell the IDE to remove diagnostics, and so they stick in the IDEs analysis view.

Not sending diagnostics would solve the problem.

**Comment by scheglov** [comment]
I believe this is fixed already.
See https://github.com/dart-lang/sdk/blob/0376883986471eb32109f42d1f93df991092737d/pkg/analysis_server/test/analysis/notification_errors_test.dart#L263 and https://github.com/dart-lang/sdk/blob/8d2bafa624dd813b8dc25d5fdd958c03cc57e184/pkg/analysis_server/lib/src/lsp/lsp_analysis_server.dart#L1215.
