### ISSUE TITLE
Doc comment on TypeAlias and subclasses regarding syntax is wrong.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35485]
Current syntax comment for TypeAlias:

> typeAlias ::= 'typedef' typeAliasBody
>
> typeAliasBody ::= classTypeAlias | functionTypeAlias

And for ClassTypeAlias:

> classTypeAlias ::= SimpleIdentifier TypeParameterList? '=' 'abstract'? mixinApplication
>
> mixinApplication ::= TypeName WithClause ImplementsClause? ';'

Which would suggest that a class type alias is declared with `typedef Foo = Bar with Baz;`. Which is incorrect; the keyword `class` is used, not `typedef`.

I think the best solution is to not specify any keyword in from of typeAliasBody; It should just be:

> typeAlias ::= classTypeAlias | functionTypeAlias

Then GenericTypeAlias specifies `metadata` as the first element, while the others do not...

**Comment by eernstg** [comment]
Note that the language specification has been generalized for type aliases such that they can declare an alias for any type, not just a function type (as of commit 02bb4379a2d82fd4fe310bc200929047c3da4782).

This is a new language feature, presumably not implemented anywhere yet (but [accepted](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md)).

The syntax `typedef Foo = Bar with Baz;` has not been available for quite a while (it was not available in October 2013 when the language specification was added to the SDK repo, cf. the [typedef grammar snippet](https://github.com/dart-lang/sdk/blob/59611b2414f81f2cf3bfe5f221970bab2a646e99/docs/language/dartLangSpec.tex#L5646)). Hence, the grammar snippets you mention were obsolete already as of late 2013. This must be a documentation issue, however, the actual parser has obviously been updated many times since then.

I'm not sure what's the best approach to keeping this kind of documentation up to date, but note that the current grammar snippet can be found [here](https://github.com/dart-lang/sdk/blob/c9a55b437a5995d0c599773fd517165b7e8e525b/docs/language/dartLangSpec.tex#L13574).

The metadata issue is known (#28283), and it will be resolved by integrating the results from building 'Dart.g' into the language specification. In Dart.g, the metadata is included for every `topLevelDefinition` [in one rule](https://github.com/dart-lang/sdk/blob/c9a55b437a5995d0c599773fd517165b7e8e525b/docs/language/Dart.g#L177), and various occurrences of `metadata` have been removed from other rules.

**Comment by shilangyu** [comment]
Fixed in #52515 with comments. Not sure what should be done with `metadata`, as I understand it can be removed?

**Comment by eernstg** [comment]
Yes, `<topLevelDefinition>` rules do not include `<metadata>` any more, that's covered by having `<metadata> <topLevelDefinition>)*` in the rule for a library as a whole (`<libraryDefinition>`). The current grammar rule is as follows:

```ebnf
<typeAlias> ::=
    'typedef' <typeIdentifier> <typeParameters>? '=' <type> ';' |
    'typedef' <functionTypeAlias>;
```

**Comment by shilangyu** [comment]
In AST land this `<metadata>` looks like it is handled by `AnnotatedNode` (and `TypeAlias <: AnnotatedNode`), so I'll remove it from the docs `TypeAlias` docs.


In the PR I raised a few other issues, perhaps I should mention them here:

<details>
<summary>Background information</summary>
analyzer's AST `TypeAlias` has three subtypes,

- `FunctionTypeAlias`, for example `typedef void hello();`
- `GenericTypeAlias`, for example `typedef hello = void Function();`
- `ClassTypeAlias`, for example `class A = C with M;`
</details>


- The AST node `TypeAlias` has a getter called `typedefKeyword` which says it will return the token for the 'typedef' token. This, however, is not true. For a class type alias this will return the token for 'class'. Is that something that should be fixed (at least the docs)?
- The language spec calls this feature "mixin classes" or "mixin application class" https://github.com/dart-lang/language/blob/cc2c933b1ae5a2c837f89ca4490040ff158a676f/specification/dartLangSpec.tex#L5428. In the AST this is called "ClassTypeAlias". This is somewhat confusing, especially when trying to find any documentation for this feature. Which, to my knowledge is very scares. I could not find any mention of it on dart.dev. The lang spec is also outdated, since it does not mention dart 3 class modifiers.
- Maybe I am nitpicking here, but is this really a "type alias"? It introduces a new nominal type which exists at runtime, unlike standard `typedef`s. I feel like it shouldnt be in the `TypeAlias` bucket, unless I am missing something.

As a side note, it is quite unclear what this "mixin application class" feature is for exactly, or what problems it solves. Scanning the whole `sdk` repo, I have found a total of 3 uses outside of test cases.

**Comment by bwilkerson** [comment]
> In AST land this `<metadata>` looks like it is handled by `AnnotatedNode` (and `TypeAlias <: AnnotatedNode`), so I'll remove it from the docs `TypeAlias` docs.

I think we should (if we don't already) follow this rule for the "grammar" productions in the AST node documentation:
- if a portion of the grammar is contained in a child node, then the child node should be referenced in the production, and
- if a portion of the grammar is inherited from a parent node, then it should be repeated in the child node's documentation.

In other words, if someone is reading the docs for a node class `N`, I think the production should include everything that is in an instance of the class `N`, whether it's declared locally or inherited. I think this will make it easier for readers to figure out where the information is located in the AST.

> Maybe I am nitpicking here, but is this really a "type alias"? It introduces a new nominal type which exists at runtime, unlike standard `typedef`s. I feel like it shouldnt be in the `TypeAlias` bucket, unless I am missing something.

It might be nitpicking, but I think it's a fair question. The answer is that it probably shouldn't be a subtype of `TypeAlias`.

The reason for the current situation is the same as one of the other questions you asked in the CL. The type hierarchy of the node classes has evolved over time, and sometimes we have missed the need to restructure the hierarchy as a result of changes to the language. But, while we would prefer to have the AST structure be better, there's a cost to changing it because of the number of other packages / tools built on our API, and we have to weigh the cost of making changes against the benefit. Sometimes that's a hard call to make, so we tend to err on the side of keeping the API stable.

**Comment by eernstg** [comment]
From a language perspective, I'd say that a mixin application class (`<mixinApplicationClass>`) is a class declaration, very similar to other class declarations, and basically unrelated to a type alias declaration.

The syntax used to be something like `typedef C = A with M;`, so that's probably the history that explains why it was considered to be a kind of type alias.

(It could have been an alias mechanism if we had used a semantics where `typedef C1 = A with M;` and `typedef C2 = A with M;` would declare two names for the same class, by canonicalization of the class declaration which is the semantics of `A with M`. But we don't do that, as you mention, @shilangyu, so there's basically no justification for using the word 'alias' around these declarations.)

So it might be a nice simplification if the mixin application classes could be moved over to the class declaration AST hierarchy. (Of course, that's just a random drive-by comment from a language guy ;-)

**Comment by shilangyu** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/305840

**Comment by srawlins** [comment]
Fixed back in last June :D. Thanks @shilangyu !
