### ISSUE TITLE
can a mixin extends a mixin

### ISSUE THREAD

**Issue by mohamedHassanKa** [dart-lang/sdk#35528]
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"

----
I have a class who is a mixin  that class contains all the shared variables . and i want another mixin to access to one of this   but for some reason the secon mixin can't find the variable .
`mixin User on Model {
bool _isLoading ;
}`
`
mixin Utility on User {
  bool get isLoading {
    return _isLoading;
  }
}`
is there any solution for this

-----

**Comment by lrhn** [comment]
Seems like a bug to me.

The `Utility` mixin requires a superclass implementing the `User` *interface*. That means that it will itself also implement that interfaces, so `_isLoading`, aka. `this._isLoading` should be valid (as long as both mixins are declared in the same library, since the name is library private).

It *appears* to be working in dartpad:
```dart
mixin Foo { int get _foo => 42; }
mixin Bar on Foo { int get bar => _foo; }
class O = Object with Foo, Bar;
main() {
  print(O().bar);
}
```
prints 42.

How do you run/analyze your code?

**Comment by mohamedHassanKa** [comment]
I have solved it when i was refactoring my code i changed the utility class into another file and since `_isLoading` is a private the compiler coldn't find it so i changed _isLoading to isLoading

**Comment by vsmenon** [comment]
Sounds like this was working as intended (_ means private to library).  If I misunderstood, please reopen.
