### ISSUE TITLE
utf8.encode should return Uint8List

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35521]
...for similar reasons as described in https://github.com/dart-lang/sdk/issues/31547, https://github.com/dart-lang/sdk/issues/27818, and https://github.com/dart-lang/sdk/issues/31784.

For now I'm just going to assume it returns a Uint8List and cast the return value, but that's dubious at best.

**Comment by lrhn** [comment]
That would be a reasonable change.
It's technically breaking since someone might implement Utf8Codec, but they *really* shouldn't.

**Comment by tvolkert** [comment]
The APIs make this difficult because to do this, you'd have to change `Encoding` to extend `Codec<String, Uint8List>`, which would in turn mean that you'd be forcing callers of `utf8.decode()` (and similar for ASCII, Latin1, etc) to _pass in_ `Uint8List`.  Conceptually, that seems like an equally logical change to make, but it's also not backwards compatible and much more likely to break callers.

It may still be worth it - it just requires more care.

**Comment by lrhn** [comment]
We can change `Utf8Codec.encode` and `Utf8Encoder.convert` to return `Uint8List` without changing the API for `Encoding`. A `Uint8List` is-a `List<int>` so it satisfies the `Codec`/`Converter<String,List<int>>` interface.

**Comment by tvolkert** [comment]
https://dart-review.googlesource.com/c/sdk/+/101742

**Comment by tvolkert** [comment]
Breaking change request: https://github.com/dart-lang/sdk/issues/36900

**Comment by tvolkert** [comment]
This is done now.
