### ISSUE TITLE
Mixin applications should support const constructors.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#35548]
The specification states that a mixin application of a mixin that contains no instance variable declarations will forward const constructors as const constructors.
The analyzer does not support this, instead it gives the error
```
Const constructor can't be declared for a class with a mixin that declares a field.
```
The front-end supports the feature, but the analyzer is preventing us from using it.
(See, e.g., this [CL](https://dart-review.googlesource.com/c/sdk/+/85704/)).

**Comment by scheglov** [comment]
I think that the CL you are referencing has errors reported by Analyzer because it has static fields.

The spec does not make distinction between instance and static fields.
It seems that static fields should not matter, but it is not specified explicitly.
![image](https://user-images.githubusercontent.com/384794/50793184-35d66b00-127c-11e9-8fbe-20c7606d4e92.png)

I will prepare a CL to ignore static fields for the purpose of checking for this error.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/88600
