### ISSUE TITLE
Analyzer: spread collections phase 1

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35569]
Phase 1 covers foundational support, i.e. parsing the new syntax, type checking it, and evaluating `...` in constant collections.

Note that this should be behind an experimental flag.

See the language tracking issue: https://github.com/dart-lang/language/issues/164
And the feature specification: https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/feature-specification.md
And the implementation plan: https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/implementation-plan.md

Remaining tasks include:
- [x] Record additional implicit downcasts to support DDC (still determining whether additional work is needed here)
- [x] Warn if the feature is used in a project with too old an SDK constraint #36046
- [x] Fix language and co19 test failures
- [x] Ensure we’re reporting errors for deferred library references in const references
- [x] Summary support
- [x] Follow up on failing tests tagged in the repo with #35569
- [x] Fix any remaining failures that appear when experimentally enabling the feature (see https://dart-review.googlesource.com/c/sdk/+/95660)

**Comment by stereotype441** [comment]
Note that the language team is currently writing tests for this feature: https://dart-review.googlesource.com/c/sdk/+/89085

**Comment by bwilkerson** [comment]
I have checked off the classes for which the necessary changes have already been committed. I have pending changes for several of the remaining classes, but didn't want to mark them as complete before they're committed.

Is `SourceVisitor` the class by that name in dart_style, or the class named `_SourceVisitor` in analyzer? If it's the former, then it probably shouldn't be on this list. If it's the latter then we should rename it and mark it complete (because it doesn't require any changes).

**Comment by stereotype441** [comment]
> Is `SourceVisitor` the class by that name in dart_style, or the class named `_SourceVisitor` in analyzer? If it's the former, then it probably shouldn't be on this list. If it's the latter then we should rename it and mark it complete (because it doesn't require any changes).

It was the one in dart_style.  I've removed it from the list.
