### ISSUE TITLE
Dart lang run very slow

### ISSUE THREAD

**Issue by netroby** [dart-lang/sdk#35619]
I am running dart lang to print simple hello world, as compare to python

```
fs hello # cat main.dart 
#!/usr/bin/env dart
void main() {
    print("hello world");
}
fs hello # cat main.py
#!/usr/bin/env python
print("hello world");
fs hello # time dart main.dart 
hello world
dart main.dart  5.13s user 0.34s system 143% cpu 3.799 total
fs hello # time python main.py 
hello world
python main.py  0.03s user 0.02s system 96% cpu 0.045 total

```

looks dart lang very slow, is it normal ?

**Comment by mraleph** [comment]
Can you give some information about your system (e.g. OS and hardware)?

Also is your `dart` by any chance a symbolic link? (could you post output of `ls -al $(which dart)`). 

In any case you can take a snapshot if you need to run some program repetitively:

```dart
$ dart --snapshot=main.snapshot main.dart
$ time dart main.snapshot
```

**Comment by netroby** [comment]
```
fs hello # dart --snapshot=main.snapshot main.dart
fs hello # time dart main.snapshot
hello world
dart main.snapshot  0.81s user 0.08s system 162% cpu 0.551 total
fs hello # time python main.py 
hello world
python main.py  0.04s user 0.00s system 97% cpu 0.045 total
fs hello # time dart main.dart 
hello world
dart main.dart  5.12s user 0.37s system 144% cpu 3.794 total

```

**Comment by netroby** [comment]
my pc cpu 

AMD E-350 Processor
8GB memory

**Comment by mraleph** [comment]
Time running from snapshot seems reasonable.

Do you have some concrete performance requirement that you would like to meet?

**Comment by mraleph** [comment]
What you are measuring is *startup latency* for a very small program. Dart does more things on startup - so startup latency is somewhat higher. However it only matters if you are running something that does no actual work and you would like to really quickly start the app which does nothing.

To illustrate the point about "doing more work": when you run VM it starts a couple of helper isolates, which is not something that you really benefit from usually. I made a dirty patch where I suppress start up of those isolates: 

```
╭─ ~
╰─$ time dart hello.snap
Hello, World!
dart hello.snap  0.20s user 0.05s system 195% cpu 0.127 total
╭─ ~
╰─$ time dart --donot-start-helper-isolates hello.snap
Hello, World!
dart --donot-start-helper-isolates hello.snap  0.05s user 0.02s system 103% cpu 0.066 total
```

Yes, this improves startup time (and memory usage probably) - but it is unclear if this is something that is important or not because it is only going to be visible on very small programs. 

I did however file a bug to clean this up https://github.com/dart-lang/sdk/issues/35700
