### ISSUE TITLE
Analysis server takes average 97s to return code completions

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#35625]
I would like a way to bundle multiple requests in a single payload that contains a list of questions/tasks for analysis server that receives a single response with information about all of them to minimize roundtrips between analysis server and my client.

**Comment by bwilkerson** [comment]
What problem are you seeing that's motivating this request?

**Comment by lambdabaa** [comment]
> What problem are you seeing that's motivating this request?

My case is a bit specific that I want to make it as fast as possible to benchmark code completions, but I imagine that many clients could take advantage of the ability to make fewer requests by batching and this would allow analysis server to make a number of optimizations by intelligently coalescing and ordering tasks to minimize duplicate work.

**Comment by bwilkerson** [comment]
Ok. So this is a request for better performance and a proposal for one way to achieve that. But in order to evaluate the proposed solution I'd like to understand the problem better.

The proposal appears to assume that the communication between client and server is taking a significant amount of time (that reducing the number of round trips would significantly improve performance). That doesn't match our initial performance tests, but it's been a while since we ran those tests so my data might be out of date. Do you have evidence to support this assumption?

Which requests are your client sending to server?

For each, are they sent once or multiple times?

Is server just generally slow, or are there a particular subset of requests that appear to be slow (and if so which ones)?

**Comment by lambdabaa** [comment]
Profiling from my benchmark:

ncalls  tottime  percall  cumtime  percall filename:lineno(function)
15    0.000    0.000 2454.657  163.644 analysis_server.py:61(predict)
15    0.000    0.000 1456.196   97.080 analysis_server.py:142(make_get_completions_request)
15    0.000    0.000   48.159    3.211 analysis_server.py:122(make_set_analysis_roots_request)
15    0.000    0.000  950.300   63.353 analysis_server.py:133(make_set_priority_files_request)

For each token that I'm looking for analysis server to code complete, I do

1. Set analysis roots to the file's parent directory (avg 3s).
2. Set the file as a priority file (avg 63s).
3. Make the code completion request (avg 164s).

Note that in the case of the code completion requests, the timer starts when the request is made and stops once we've received a completion suggestions notification.

**Comment by bwilkerson** [comment]
Did I understand correctly: you're doing all three steps for each token?

If so, that isn't necessary. Server remembers the current state. You should see an improvement if you:
```
set the analysis root to the file's parent directory (or better yet root of the package) once,
for each file in the analysis root {
  set the file as the priority file
  for each token in the file {
    request completions
  }
}
```

**Comment by lambdabaa** [comment]
Cool, I'll go ahead and give that a shot, thanks!
