### ISSUE TITLE
Dart HTML is missing "removeAttribute", "removeAttributeNS"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#35655]
Historic issue: https://github.com/dart-lang/sdk/issues/19934.

As mentioned on #19934, `dart:html#Element` is missing `removeAttribute[NS]`.

You _can_ use `element.attributes.remove`, but:

* There is no way to do this for namespaced attributes.
* The code emitted is sub-optimal because it cannot inline "removeAttribute":

```dart
import 'dart:html';

void main(Object e) {
  _example(e as Element);
}

@pragma('dart2js:noInline')
void _example(Element e) {
  e.attributes.remove('title');
}
```

... emits ...

```js
main: function(e) {
  F._example(H.interceptedTypeCast(e, "$isElement"));
},
_example: function(e) {
  e.get$attributes().remove$1(0, "title");
}
```

/cc @kevmoo for triage.

**Comment by rakudrama** [comment]
1. I think it is reasonable to add the requested methods since `getAttribute[NS]` is already there to sidepass the Map abstractions.

2. "There is no way to do this for namespaced attributes.":
`element.getNamespaceAttributes('namespace').remove('title')` will remove a namespaced attribute.

3. "The code emitted is sub-optimal because it cannot inline "removeAttribute""
The emit example is not representative since `main` is not expected to be passed an Element. If you pass a created element, the code is slightly better. It can be improved with a few annotations to generate the expected code (similar to how HtmElement.classes.add generates e.classList.add).

**Comment by matanlurey** [comment]
> I think it is reasonable to add the requested methods

:+1: 

> `element.getNamespaceAttributes('namespace').remove('title')`

Wow, I didn't even see this method. Thanks!

> `The emit example is not representative since main is not expected to be passed an Element`

Ah I see, thanks. Yes, I see now:

```dart
import 'dart:html';

void main(Object e) {
  _example(DivElement());
}

@pragma('dart2js:noInline')
void _example(Element e) {
  e.attributes.remove('title');
}
```

... generates ...

```js
main: function(e) {
  F._example(document.createElement("div"));
},
_example: function(e) {
  C.DivElement_methods.getAttribute$1(e, "title");
  C.DivElement_methods._removeAttribute$1(e, "title");
}
```

... which is a little strange, the JS-interop invocation of `removeAttribute` is still better.

> It can be improved with a few annotations to generate the expected code

Fair enough. That might be worth doing, as well.

**Comment by rakudrama** [comment]
Note that compiling with `--omit-implicit-checks` (or `-O3`) is a little less strange:

```dart
void _example(Element e) {
  e.attributes.remove('title');
}
```
```js
    _example: function(e) {
      e.getAttribute("title");
      e.removeAttribute("title");
    }
```

We should be able to get this with lower levels of optimization, so I opened https://github.com/dart-lang/sdk/issues/35681 for that.
