### ISSUE TITLE
Runtime errors in new co19_2 set_literal tests

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#35682]
Two new co19_2 tests added for the set-literals feature produces runtime errors

co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart
co19_2/src/LanguageFeatures/Set-literals/non_constant_set_literals_A02_t01.dart

```
out/DebugX64/dart --no-background-compilation --enable-experiment=set-literals --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws2/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart
Unhandled exception:
type '_CompactLinkedHashSet<dynamic>' is not a subtype of type 'LinkedHashSet<int>'
#0      test4 (file:///usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart:26:31)
#1      main (file:///usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart:32:17)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
sivalinuxmach[sdk]>vi tests/co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart
```
```
out/DebugX64/dart --no-background-compilation --enable-experiment=set-literals --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws2/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/LanguageFeatures/Set-literals/non_constant_set_literals_A02_t01.dart 
Unhandled exception:
Expect.isFalse(true) fails.
#0      _fail (file:///usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.isFalse (file:///usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/Utils/expect_common.dart:48:5)
#2      Expect.iterableEquals (file:///usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/Utils/expect_common.dart:386:12)
#3      main (file:///usr/local/google/home/asiva/workspace/dart-ws2/sdk/tests/co19_2/src/LanguageFeatures/Set-literals/non_constant_set_literals_A02_t01.dart:55:10)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

**Comment by crelier** [comment]
Regarding co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart, it looks like an inference issue to me.
Strictly speaking, type '_CompactLinkedHashSet<dynamic>' is not a subtype of type 'LinkedHashSet<int>'. The question is whether the literal {} in test4() should have been inferred the type _CompactLinkedHashSet<int> instead of _CompactLinkedHashSet<dynamic>.
I think so, because {} in test2() and in test3() have both type _CompactLinkedHashSet<int>.

Regarding  co19_2/src/LanguageFeatures/Set-literals/non_constant_set_literals_A02_t01.dart, removing  "const" on this line:
`  var s2 = const <Object> {'3', 1, 4, null, 1, null,};
`
makes the test pass.
The question is whether a const and a non-const set literals with identical values are considered "iterableEquals" by module Expect. I do not know the answer.

**Comment by lrhn** [comment]
The lines in semantics_A05_t01 are:
```dart
Set<Object> test() => {};
Iterable<int> test2() => {};
FutureOr<Iterable<int>> test3() => {};
LinkedHashSet<int> test4() => {};
```.
All of these should cause the literal to be a set (and likely do). Inference should infer `int` as type argument for the last three and `Object` for the first. The `_CompactLinkedHashSet<dynamic>` suggests that inference failed to do that in one of the last three cases (most likely the `FutureOr<Iterable<int>>` one). Looks like a bug in type inference.

I don't know `iterableEquals`, but it should probably recognize two sets with equal elements in the same order as equal.

**Comment by eernstg** [comment]
@crelier wrote, about `non_constant_set_literals_A02_t01.dart`:
> removing "const" .. makes the test pass

The [feature spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md) has, in section 'Constant Set Literals': 'It is a compile-time error if any two of the values are equal according to ==', so we shouldn't get far enough to even consider the question about the behavior of `iterableEquals`.

**Comment by crelier** [comment]
@eernstg Thank you Erik for pointing that out. I have filed co19 issue https://github.com/dart-lang/co19/issues/229 regarding the second test non_constant_set_literals_A02_t01.dart.

@lrhn Thanks for confirming. The last case (test4) is indeed missing the int type argument. I am reassigning this issue to @kmillikin.

**Comment by kmillikin** [comment]
@askeksa-google can you take a look at co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart?

**Comment by askeksa-google** [comment]
I have encountered this limitation in type inference before, in some of the other set literal tests. But it is not specific to set literals. We generally don't infer the type arguments from the context when the outer type of the context is a proper subtype of the type of the inferred expression. For instance:
```dart
class A<T> {
  factory A() => new B<T>();
}
class B<T> implements A<T> {}
B<int> x = new A();
```
Here, the created instance has type `A<dynamic>`.

As far as I can see, the CFE and analyzer agree on this behavior.

**Comment by peter-ahe-google** [comment]
I think this may be a case of the test being out of sync with the latest specification. It is testing this assertion:

```
 * @assertion If s is an emptySetOrMapLiteral with no typeArguments and static
 * context type C, then if LinkedHashSet<Null> is assignable to C and
 * LinkedHashMap<Null, Null> is not assignable to C, then s is a set literal,
 * otherwise s is a map literal.
```

This matches what the specification said prior to c565d4e477efc72a27edd182cc149cd629b6568c.

**Comment by a-siva** [comment]
Can a co19 issue be filed for this so the test is fixed.

**Comment by askeksa-google** [comment]
The comment in the test is indeed incorrect, but the change to the specification does not change whether the literal is a map or set literal. The new criterion for being a set literal is that it is a subtype of `Iterable` (and not of `Map`), which is still the case.

It sounds like it is the intent that the type argument should be inferred from the context here (@eernstg, @lrhn, can you confirm?). This would be a cross-tool change, which could be considered breaking.

**Comment by leafpetersen** [comment]
> It sounds like it is the intent that the type argument should be inferred from the context here

If by "here" you mean this example:

```dart
LinkedHashSet<int> test4() => {};
```

Then no, inference will fail to infer a type argument here and will default to dynamic.  I believe that the spec does say that this will disambiguate to a set literal (since the context type is a subtype of `Iterable<Object>`, but for inference we will be checking the matching problem `Set<X> <: LinkedHashSet<int>`, solving for `X`.  There are no choices of `X` which solves that constraint problem, so it fails and we default to `dynamic`.

So I believe the test is incorrect.

**Comment by vsmenon** [comment]
Regarding `semantics_A05_t01.dart`, 

I'm seeing an unexpected compile-time error with analyzer-based DDC:

```
[error] The set literal type 'Set<?>' isn't of expected type 'LinkedHashSet<int>'. The set's type can be changed with an explicit generic type argument or by changing the element types. (tests/co19_2/src/LanguageFeatures/Set-literals/semantics_A05_t01.dart, line 26, col 3
```

and an unexpected runtime error with kernel-based DDC:

```
Error: Type '_HashSet<dynamic>' should be '_HashSet<int>' to implement expected type 'LinkedHashSet<int>'.
```

Which is the expected result?

**Comment by kmillikin** [comment]
@vsmenon the analyzer is correct that it's a compile-time error, though the error message isn't crystal clear.

The static type of the set literal in

```dart
LinkedHashSet<int> test4() => {};
```
is `Set<dynamic>` which is OK as far as that goes.  But there should be a compile-time error because of exact types: we are trying to assign it to `LinkedHashSet<int>` which is not a supertype of `LinkedHashSet<dynamic>`.

CFE doesn't have the exact type rules implemented yet, so it lets the program through and you get a runtime error instead.

**Comment by askeksa-google** [comment]
The analyzer and CFE now agree to report a compile-time error for the first test (which does not exist anymore in the co19 suite) and the second test now passes.
