### ISSUE TITLE
missing_return should know about enums and switches

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#35710]
_From @Hixie on August 20, 2018 23:11_

If you assert that a variable of enum type is non-null before a switch, and then you have a switch where every enum value is handled and terminates (returns, throws, or exits), then it should not flag that function as not ending with a return. (The usual pattern today is to `return null` after the switch to silence the analyzer, but that's what would happen anyway if the statement wasn't there, in the case of the variable being null in a release build.)

For example:

```dart
enum Foo { a, b, c }

String hello(Foo value) {
  assert(value != null);
  switch (value) {
    case Foo.a: return 'A';
    case Foo.b: return 'B';
    case Foo.c: return 'C';
  }
  // This should not be flagged by missing_return                                                                            
}
```

cc @a14n 

_Copied from original issue: dart-lang/linter#1139_

**Comment by lrhn** [comment]
In Dart 2, the "implicit" return of `null` at the end of a function is only allowed in `void` functions. In all other functions, a missing return is considered an error (or at least a warning) because it could be hiding an actual programming error. You need to be explicit about returning a value from non-void functions.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/149606
