### ISSUE TITLE
[Feature request] Support debug adapter protocol. 

### ISSUE THREAD

**Issue by LinArcX** [dart-lang/sdk#35717]
Hi guys. I corius to know is there any plan to support debug adapter protocol(DAP) in Dart language? 
https://microsoft.github.io/debug-adapter-protocol/
Other IDEs can use this feature to create plugins for their eco system. For example I can still use vim and use dap for debugging.

**Comment by alexander-doroshko** [comment]
@mit-mit I'm not sure 'area-intellij' is the right label here. This sounds like a question for the VM team. I'm not from Google, I can only guess that the answer is 'No'.

Speaking of IntelliJ, I'm not aware of any plans to support generic Debug Adapter Protocol. IntelliJ supports each technology separately. So if Dart VM team decides to switch to Debug Adapter Protocol, IntelliJ will support it as a part of the Dart plugin.

**Comment by a-siva** [comment]
We don't currently have any plans to support debug adapter protocol (DAP). It is not in our 2019 plans. I will let @mit-mit figure out if we should support it longer term (post 2019).

**Comment by jonas-jonas** [comment]
Would be nice to have this http://github.com/eclipse/dartboard and potentially Dart-Code too @DanTup.

**Comment by DanTup** [comment]
Dart-Code does already have an implementation of DAP, though it's written in TypeScript (and therefore needs to run in a nodejs VM) and has a bunch of VS-Code specific behaviour (it was written when DAP was really just "the VS Code debug protocol"). In theory it could be ported/re-implemented in Dart and made generic.

FWIW - I don't think there's any reason this work would need to be done in the VM (or by the VM Team, or even Google), at least initially. Unlike the analysis server which was trickier to proxy because of mismatches in the requests, VS Code is already essentially proxying this without any issues. It could easily be built as a Pub package (though this would make running it slightly trickier, but maybe dart2aot can simplify that in the future?) and considered for including in the SDK in future if appropriate.

**Comment by jacob314** [comment]
@DanTup I believe you are working on this. Now that we have DDS, it is practical to implement this as part of the Dart SDK.
Fyi @bkonyi

**Comment by DanTup** [comment]
The next versions of the Dart/Flutter SDKs include DAP implementations. Instructions on using and any custom messages they support are documented here:

- Dart: https://github.com/dart-lang/sdk/blob/main/pkg/dds/tool/dap/README.md
- Flutter: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md

It's up to the editor to start the correct debug adapter based on the context it has for the project that's open and whether the user is trying to run tests.

VS Code isn't using them yet as there are a few minor things outstanding it needs (nothing significant that would prevent other editors using them), but will do soon.

Please file issues and ping me if you have any issues integrating against these.
