### ISSUE TITLE
Best strategy for predictable if-statement inlining?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#35728]
Hi (likely @rakudrama but maybe others) Dart2JS team!

We (AngularDart) are experimenting with multiple strategies to reduce code size. One of our strategies relies on removing how much (of our, not Dart2JS) code is hoisted from child views in the template to their parent - i.e. less code duplication. At the same time, we want to mitigate performance costs, so [I tried experimenting here](https://gist.github.com/matanlurey/16e16d761dfbd1ce88aabd17f53fd681):

```dart
void main() {
  var p = Parent();
  p.build();
}

/// Building block for generated code in AngularDart or similar systems.
abstract class View {
  void build();

  /// When a parent view knows a child view *must* return something, it may
  /// use this method to get an optimized lookup of the provided service
  /// by [token].
  Object injectEager(Object token);  
}

class FooService {
  @override
  toString() => 'Foo';
}

class BarService {
  @override
  toString() => 'Bar';
}

class Parent extends View {
  Child _child;
  
  @override
  build() {
    _child = Child();
    _child.build();
    print(_child.injectEager(FooService));
  }
  
  @override
  injectEager(_) => throw UnsupportedError('');
}

class Child extends View {
  FooService _foo;
  BarService _bar;

  @override
  @pragma('dart2js:noInline')
  build() {
    _foo = FooService();
    _bar = BarService();
  }
  
  @override
  injectEager(Object token) {
    if (FooService == token) {
      return _foo;
    }
    if (BarService == token) {
      return _bar;
    }
    throw UnsupportedError('');
  }
}
```

The idea is we don't want to expose `._foo` and `._bar` directly as public APIs (for other reasons), but the hope was Dart2JS could tell `injectEager(<token>)` was always immediately successful and inline the result into the parent class, generating something like:

```js
Parent: {
  "^": "View;0_child",
  build$0: function() {
    var t1 = new F.Child();
    this._child = t1;
    t1.build$0();
    H.printString(H.S(t1._foo));
  }
},

Child: {
  "^": "View;0_foo,0_bar",
  build$0: function() {
    this._foo = new F.FooService();
    this._bar = new F.BarService();
  },
}
```

Instead, unfortunately, it generates this:

```js
Parent: {
  "^": "View;0_child",
  build$0: function() {
    var t1 = new F.Child();
    this._child = t1;
    t1.build$0();
    // 1. Reloads this._child (doesn't re-use t1)?
    // 2. Calls a method that definitively should return.
    H.printString(H.S(this._child.injectEager$1(C.Type_FooService_76D)));
  }
},

Child: {
  "^": "View;0_foo,0_bar",
  build$0: function() {
    this._foo = new F.FooService();
    this._bar = new F.BarService();
  },
  // 3. Can't tell (?) that this method should not be needed or some branches are dead code.
  injectEager$1: function(token) {
    var t1, t2;
    t1 = C.Type_FooService_76D.get$_typeName();
    t2 = token.get$_typeName();
    if (t1 === t2)
      return this._foo;
    t1 = C.Type_BarService_h00.get$_typeName();
    t2 = token.get$_typeName();
    if (t1 === t2)
      return this._bar;
    throw H.wrapException(P.UnsupportedError$(""));
  }
}
```

I tried:

* Adding `@pragma('dart2js:tryInline')` to `injectEager`
* Change `==` to identical
* Using a different `token` type (i.e. `int` instead of `Type` to see if types were treated special)

i.e.:

```dart
  @override
  @pragma('dart2js:tryInline')
  injectEager(int token) {
    if (identical(token, 1)) {
      return _foo;
    }
    if (identical(token, 2)) {
      return _bar;
    }
    throw UnsupportedError('');
  }
```

... but similar code to above is emitted.

**Comment by rakudrama** [comment]
There are some limitations on the current inliner, one being that it works mainly with expression-like code that has a single return. You could try making injectEager have a single return statement, either by using a `?:` conditional or using a local and return that. There are a lot of things that could be better with dart2js inlining, but they (almost) all require a large effort to fix and we have always had more pressing issues.

Addressing other comments:

 1. `this._child` is reloaded because it is not final and it is very hard to prove that `t1.build$0()` does not somehow call `this.build$0()` and overwrite `this._child`. You know invariants that the compiler can't figure out, so generate code accordingly. See "Use local variables in build() method".

 2. It is not clear that the method should definitely return. There are plenty of places that could throw, including the explicit throw and in the definition of `Type.==`. You have to do a lot of work for each call site to 'see' what is obvious - for example, `.get$_typeName()` has side-effects, so how do you know you can leave them out? (We should probably make TypeImpl.== noInline.)

 3. If we did inline the code, the method might go away, but not of there was another call site that could hit the target, e.g. through some code where we only know the receiver is a subtype of `View`, so potentially hitting any override of `View.injectEager`. It might be worth considering replacing lifecycle-methods-with-overrides with static methods (or at least uniquely named methods). General lifecycle methods would only be needed if the methods are called from a general call site, e.g. an interpreter.

**Comment by matanlurey** [comment]
> It is not clear that the method should definitely return.

:-/, it is never called with anything that would make it throw. I understand though.

> It might be worth considering replacing lifecycle-methods-with-overrides with static methods (or at least uniquely named methods). General lifecycle methods would only be needed if the methods are called from a general call site, e.g. an interpreter.

The issue with this approach is due to build-time constraints, we need to declare our public API ahead-of-time (i.e. "outline" our API), and we would not be able to do this. The only thing I could imagine doing would be:

```dart
class Child {
  // This is guaranteed, but we don't declare it as such in our header file/outline.
  getA() => _a;
}

class Parent {
  build() {
    var c = Child();

    // Hope that Dart2JS type inference effectively removes the `as dynamic`.
    var a = (c as dynamic).getA();
  }
}
```

**Comment by matanlurey** [comment]
Sorry @rakudrama I do not follow, do you mean:

```dart
class Child {
  static injectEager(Child instance, Object token) {
    var result;
    if (identical(FooService, token)) {
      return instance._foo;
    }
    return result;
  }
}
```

**Comment by matanlurey** [comment]
We found several workable solutions (ternary, single return), so I am closing this issue.
