### ISSUE TITLE
MessagePort not transferring via WebWorker postMessage().

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#35730]
**Environment:**
- Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"
- Version 73.0.3673.0 (Official Build) dev (64-bit)

**Issue Or Not**
Not black & white, as there is no documentation and a reading of the source also does not shed any light. Never the less, I have raised the issue on [StackOverflow](https://stackoverflow.com/questions/54264262/transfering-a-messageport-via-webworker-postmessage) and have stalked a few folks on gitter. Unfortunately no luck, I can not accept that I am the first people to attempt to do this, hence it could just be a knowledge gap.

**Area**
- dart:html
- Worker, in particular  ```postMessage(Object message, [ List<Object> transfer]) -> void```
- MessageChannel/MessagePort

**Assumptions**
1. MessagePort is a cloneable transferable object. [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Transferable)
2. MessagePort is the way to go when needing to communicating between two workers, independent of the thread which launched each of the workers.

**Core Problem**
After passing the messagePort to the work it arrives in as an instance of ```'JsLinkedHashMap<dynamic, dynamic>'``` and there is no way to retrieve the MessagePort instance.

_Sounds stupid right!_

**Reproduction**
The simplest reproduction I have managed is the following.

1. Inside a main.dart:

```dart
import 'dart:html';

import 'dart:collection';

void main() {
  querySelector('#output').text = 'Your Dart app is running.';

  Worker w = Worker('lib/my_worker.dart.js');

  MessageChannel msgChn = MessageChannel();

  HashMap trsMsg = HashMap.from({'port': msgChn.port1});
  w.postMessage(trsMsg, [msgChn.port1]);
}
```

2. In our worker code.
```dart
import 'dart:html';

class MyWorker {
  DedicatedWorkerGlobalScope dws = DedicatedWorkerGlobalScope.instance;

  MyWorker() {
    print('Worker Running');

    dws.onMessage.listen((MessageEvent evt) {
      print(evt.data);
      print(evt.data.runtimeType);
      var strSec = evt.data['_strings'];
      print(strSec);
      MessagePort mp = strSec['port'];
    });
  }
}

main() {
  MyWorker();
}
```

3. In the build.yaml.
```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - -O1
```

_The result:_

![screen shot 2019-01-23 at 12 34 01 pm](https://user-images.githubusercontent.com/349890/51576660-3d983f80-1f0b-11e9-8334-44d6c8a6a230.png)

I have tried a number of different approaches to this whole problem, including but not limited:

1. Using a LinkedHashMap for the trsMsg.
2. Building the trsMsg Hash from Iterables, that was a longshot.
3. Sending port 2 instead of port 1,
4. Inlining anything and everything I could.
5. Cast and recast on the worker side.
6. Changing every build options I could think of.
7.  Using the Js library to create an anonymous ```MessageEvent```
8. Not using the dart:html library at all. Instead using ```@JS()``` for everything from the worker to the port.

Clearly running out of ideas and getting down to long shots.

 **Expected Behaviour**

- Instead of getting an unusable ```[object MessagePort]``` showing up in the worker, simply being able to access an ```Instance of MessagePort``` from within the ```MessageEvent.data``` would be ideal. For that matter being to access the transferred ```MessagePort``` in everywhere in the worker would do the job.

Thanks in advance and I hope it is something thing simple I am doing or not; communicating between web workers without messagePort is a nightmare.

**Comment by sigmundch** [comment]
@rayk thanks for filing this issue

I took a closer look and it appears there are several issues at play.

* Not sure why, but the data cloning seems broken at the moment.

  Technically before sending a message we should be doing a structural clone that converts our Dart types to the clonable JS types.

  The fact that you see internals of the map implementation (like _strings) is pretty odd.

  I tried switching to send an array instead, and I also run into issues, although I got some things working by accident. In particular, type information we may attach to object instances seems to be interfering with the cloning and validation that happens when calling postMessage. If I use the dart2js flag `--omit-implicit-checks` a lot of this type information is removed, which made my example below work.

* the worker is missing the implementation of MessagePort. This is why the cast fails. We are checking that something is an instance of MessagePort, but we don't have the type because we didn't see a creation for that type. Adding code like `new MessageChannel()` somewhere in the worker program is a possible workaround.

I'm not recommending you do this, but the program below was able to exchange a message back and forth. I'm just posting it here to help investigate our next steps:

main program:
```dart
import 'dart:html';

void main() {
  Worker w = Worker('worker.dart.js');
  MessageChannel msgChn = MessageChannel();
  w.postMessage([msgChn.port1], [msgChn.port1]);
  msgChn.port2.onMessage.listen((m) => print("parent got: " + m.data));
}
```
the worker:
```dart
import 'dart:html';

class MyWorker {
  DedicatedWorkerGlobalScope dws = DedicatedWorkerGlobalScope.instance;

  MyWorker() {
    print('Worker Running');

    dws.onMessage.listen((MessageEvent evt) {
      print(evt.data);
      print(evt.data.runtimeType);
      print(new MessageChannel().port1);
      MessagePort port = evt.data[0];
      print(port);
      port.postMessage("hola hola");
    });
  }
}

main() {
  MyWorker();
}
```

/cc @rakudrama

**Comment by sigmundch** [comment]
A few more details:
* the worker.postMessage API directly invokes the DOM API instead of first doing a structural clone (the cloning call is missing entirely, see how we do have that clone call in MessagePort.postMesage)
* if called manually, cloning fails because it doesn't have a rule to bypass MessagePort instances

@terrylucas - Both of issues above appear to be bugs in the dart:html generated library

* finally, to have the type available in the worker, it is possible that all we need to do is to update what values are expected on deserialization (_serializedScriptValue in our dart:html_common library)

**Comment by sigmundch** [comment]
Quick update: I can verify that the 3 issues above address the original bug:
* need to update Worker.postMessage to ensure we do a structural clone (adding the clone manually fixes the issue too)
* need to update serialization code to include MessagePort
* need to list MessagePort as a possible deserialization type (this fixes the worker issue)

I'll prepare a fix tomorrow for the 2nd and 3rd issue.
@terrylucas - could you help us fix the first issue on your end?

**Comment by rayk** [comment]
Thanks @sigmundch and @terrylucas,  the ```--omit-implicit-checks``` really is the big clue here I totally missed. Keep me updated and I shall make sure I seed some article into the community showing off port passing using dart:html_common library.

**Comment by sigmundch** [comment]
I just landed 60d7e8f72f4b651d1cc76795057c5ebdbca145e6 and 6bcb017c56e805ffc5cdf781c8fb3b9784065ee7 and things are working much better now.

I can compile these 2 programs with no flags (no `--omit-implicit-checks` needed), and run them correctly:

main.dart:
```dart
import 'dart:html';

void main() {
  Worker w = Worker('worker.dart.js');
  MessageChannel msgChn = MessageChannel();
  w.postMessage({'port': msgChn.port1}, [msgChn.port1]);
  msgChn.port2.onMessage.listen((m) => print("received message from worker: " + m.data));
}
```

worker.dart:
```dart
import 'dart:html';

class MyWorker {
  DedicatedWorkerGlobalScope dws = DedicatedWorkerGlobalScope.instance;

  MyWorker() {
    print('Worker Running');

    dws.onMessage.listen((MessageEvent evt) {
      print(evt.data);
      print(evt.data.runtimeType);
      MessagePort port = evt.data["port"];
      print(port);
      port.postMessage("port is working!");
    });
  }
}

main() {
  MyWorker();
}
```

The output I get is:
```
Worker Running
{port: Instance of 'MessagePort'}
JsLinkedHashMap<dynamic, dynamic>
Instance of 'MessagePort'
received message from worker: port is working!
```

The fixes are on the master branch at this time, and will be available in the next dev release.

**Comment by leonsenft** [comment]
Thanks for this fix @sigmundch. Is there any chance we could have the transferred `MessagePort` exposed on the `MessageEvent` as well? https://github.com/dart-lang/sdk/issues/32688

It's passed in, and presumably transferred correctly, but the [ports](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/ports) property is [missing](https://api.dartlang.org/stable/2.1.0/dart-html/MessageEvent-class.html) from `MessageEvent` in `dart:html`.

**Comment by sigmundch** [comment]
Just spoke with @terrylucas - he will be adding it shortly

**Comment by leonsenft** [comment]
Awesome thanks! :+1:

**Comment by edyu** [comment]
I actually found an easy way (but not automated way) to run worker.
In a web project such as angulardart project, just call
`dart2js <source file location from the top level> -o web/<destination file name>.dart.js`

For instance, say the source file is under `<project>lib/src/worker/worker.dart`
`dart2js lib/src/worker/worker.dart -o web/worker.dart.js`
Then I can reference worker.dart.js from the main program (doesn't have to be in the main function.
I found this to be easier than relying on DDC until DDC fixes the problems with -O0.
