### ISSUE TITLE
analyzer regression on pub.dartlang.org

### ISSUE THREAD

**Issue by Sh1d0w** [dart-lang/sdk#35732]
Hi I am the maintainer of  https://pub.dartlang.org/packages/multi_image_picker

Until today my package did not had any Health errors. However since today, I've released a new version, and the analyzer on pub.dartlang.org shows those problems:

<img width="653" alt="screenshot 2019-01-23 at 12 30 13" src="https://user-images.githubusercontent.com/5074917/51600446-ad59fa80-1f0a-11e9-8840-7926f3970cfa.png">

However locally analyzer does not report any issues as it should be because I haven't included `non_constant_identifier_names` in my config

https://github.com/Sh1d0w/multi_image_picker/blob/master/analysis_options.yaml

For some reason it seems like pub.darlang.org ignores the package analysis_options and uses its own rules, which is regression from what we had before.

**Comment by zoechi** [comment]
@isoos

**Comment by isoos** [comment]
> For some reason it seems like pub.darlang.org ignores the package analysis_options and uses its own rules, which is regression from what we had before.

`package:pana` and the pub site does use rule replacement, and we are doing it from the very beginning. This is to enforce a minimum/common set of rules, and not to rely on the ones that the package author provided. We also update the rules from time-to-time, following the toolset defaults.

In this case, your package is a Flutter plugin, and we use the defaults recommended for new Flutter projects to analyse it: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml

Last week we've released a new version of pub site that used the updated rules, that's why you see the change. As the recommended defaults change over time, `pana` and pub site will follow it, and it could result in changes in the analysis results.

Looking at you code, it seems that you are using the final fields with uppercase, which is usually for classes. As the package is popular, I wouldn't do a single breaking update to it, rather a gradual one:

- You can introduce a non-breaking migration path: renaming the fields to lowerCamelCase, and keeping a getter for the CamelCase versions.

- You can use [ignore rules](https://www.dartlang.org/guides/language/analysis-options#ignoring-specific-analysis-rules) to ignore a specific rule, clearing it for now, but hopefully addressing it later.

**Comment by Sh1d0w** [comment]
@isoos I see, thanks for the info and the suggestions. I will amend as per your recommendations.

Cheers!

**Comment by zoechi** [comment]
Does `pub publish` also check according to these rules?

**Comment by isoos** [comment]
> Does pub publish also check according to these rules?

Not yet, but hopefully we'll get there:
https://github.com/dart-lang/linter/issues/1365

**Comment by Sh1d0w** [comment]
> Does `pub publish` also check according to these rules?

I guess thats why I've got confused. Moreover the official reference on this topic does not reflect those recent changes, instead it shows the old rules available https://pub.dartlang.org/help#health

**Comment by pq** [comment]
Sorry for the confusion @Sh1d0w.  This is exactly what we're trying to head-off in the long-run.

I've added a few notes to dart-lang/linter#1365 with documentation ideas but this is really helpful context.  Cheers!

/fyi @kwalrath
