### ISSUE TITLE
make VM fail with a clear error message if stack size is too small for it to operate

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#35745]
30896b87f11595dac573c6a1873a9a49fa818a21 bumped the size of the "redzone" by 4x (from 4 * KB * kWordSize to 16 * KB * kWordSize). 

We hit a problem with this internally (contact @cskau-g for more info): if we execute on a fiber with a small stack (and fiber stacks are small by default: actually only 64 * KB!) then we immediately hit a stack overflow during kernel loading during isolate startup when we call into Dart to perform some constant evaluation, which recursively hits another stack overflow while trying to create stack overflow exception object and so on ad infinitum until you hit an actual stack overflow and crash. 

Instead VM should crash early if the size of the stack minus redzone size is too small (well, negative in this case?)

/cc @a-siva

**Comment by mkustermann** [comment]
Being really surprised that our runtime needs more than 4 KB to handle stack overflow, I have looked now into it a bit and found out that most of that stack space is consumed by the DRT_* functions, they have a `StackZone` which has an embedded `Zone`, which has an embedded `VMHandles` which has a `HandlesBlock` inlined into the object of more than 1 KB.

See here:
```
(gdb) p sizeof(dart::StackZone)
$1 = 2160
(gdb) p sizeof(dart::Zone)
$2 = 2136
(gdb) p sizeof(dart::VMHandles)
$3 = 1056
```

It might be that the compiler will make the object aligned to it's largest member, which makes `Zone` to become almost twice as large as `VMHandles`.

=> Sometimes our compiler makes nested handle scopes which can significantly increase the stack.

Shrinking the in-line handles block or moving it completely to the heap will allow us to go back to a smaller red zone.

/cc @rmacnak-google @mraleph

**Comment by rmacnak-google** [comment]
The first handle block is also wasted because every StackZone is immediately followed by a HANDLESCOPE.

**Comment by mkustermann** [comment]
@liamappelbe 

The reproduction is very simple:
```
% git diff
diff --git a/runtime/vm/os_thread.h b/runtime/vm/os_thread.h
index a82ef6f926..a720376549 100644
--- a/runtime/vm/os_thread.h
+++ b/runtime/vm/os_thread.h
@@ -209,7 +209,7 @@ class OSThread : public BaseThread {
   static void DisableOSThreadCreation();
   static void EnableOSThreadCreation();
 
-  static const intptr_t kStackSizeBuffer = (16 * KB * kWordSize);
+  static const intptr_t kStackSizeBuffer = (4 * KB * kWordSize);
 
   static const ThreadId kInvalidThreadId;
   static const ThreadJoinId kInvalidThreadJoinId;

% tools/build.py -mrelease -ax64 runtime_kernel

% cat test.dart
enum Fruit {
  apple, banana,
}

getFruit() => Fruit.apple;

recurse() {
  try {
    recurse();
  } catch (e, st) {
    print("$e ${getFruit()}");
  }
}

main() {
  recurse();
}

% out/ReleaseX64/dart test.dart
zsh: segmentation fault  out/ReleaseX64/dart e.dart
```

This reverts the increase in redzone from [cl/86821](https://dart-review.googlesource.com/c/sdk/+/86821/2/runtime/vm/os_thread.h)


(This is from https://github.com/flutter/flutter/issues/25041#issuecomment-445097904 )

**Comment by cskau-g** [comment]
@liamappelbe Are there any obvious blockers preventing us from applying something like the patch in the comment above?
(I've CC'd you on an internal bug where folks are blocked on this.)

**Comment by liamappelbe** [comment]
Sorry, I didn't realize it was blocking anyone. I thought we had hacked around it with the stack size increase and I've been working on other stuff. I'll prioritize it now.

**Comment by liamappelbe** [comment]
Is the goal of this bug still just to make the VM fail with a clear error message? I'm not sure how that unblocks anyone.

**Comment by mkustermann** [comment]
> Is the goal of this bug still just to make the VM fail with a clear error message?
> I'm not sure how that unblocks anyone.

We could do several things:

a) Instead of using the constant evaluator to create the `StackOverflowError` exception object, we can simply allocate and canonicalized it (it's constructor is empty and there are no fields to initialize) - this avoids the recursive SOW issue described in the original comment - https://github.com/dart-lang/sdk/issues/35745#issue-402686428

b) We should make our runtime use less stack space, by e.g. not allocating over 2 KB of in-line handle stacks

c) We should more accurately measure the maximum "red zone" that the runtime needs for a) throwing a StackOverflowError exception and b) bootstrapping the isolate

Finally we should reduce the red zone constant down.

**Comment by cskau-g** [comment]
Thanks, Liam.
I think getting a proper error is a good first step. And I realised that's what this issue is actually tracking.

The team blocked by the stack size issue used to be able to increase the stack size to get around the issue, but due to a new system design they're no longer able to do that and stuck with the default Fibers stack size.

**Comment by liamappelbe** [comment]
Filed https://github.com/dart-lang/sdk/issues/36100 to track that work. I don't have the expertise necessary to fix these sorts of problems quickly :P
