### ISSUE TITLE
Getting a CompilationUnit from Element no longer possible.

### ISSUE THREAD

**Issue by BrennanGambling** [dart-lang/sdk#35749]
I'm currently using the source_gen package and need to obtain a CompilationUnit from an Element but it seems that all of the accessors and methods that made this possible are now deprecated. 
Essentially I'm trying to parse through the input source code to look for a MethodInvocation of a specific method with specific parameters.
Any suggestions on how to move forward on this?

**Comment by kevmoo** [comment]
@BrennanGambling – which version of `package:analyzer` are you using now? Look at your `pubspec.lock` file

**Comment by stereotype441** [comment]
@natebosch can you advise about what the proper workflow is?

**Comment by natebosch** [comment]
I think today it requires going through a deprectated API - the forwards compatible (but deprecated because it's temporary) API is going through a `ParsedLibraryResultImpl`

See https://github.com/dart-lang/source_gen/blob/1605509decdc3af8573d73fec54e29a3901092d6/source_gen/lib/src/type_checker.dart#L301

Once we bump to `package:build` version 2.0.0 I _think_ the preference will be to used `ResolvedUnitResult` instead of `CompilationUnit`, and the way to get there would be `libraryElement.session.getParsedLibraryByElement(libraryElement).units`.

**Comment by stereotype441** [comment]
> Once we bump to `package:build` version 2.0.0 I _think_ the preference will be to used `ResolvedUnitResult` instead of `CompilationUnit`, and the way to get there would be `libraryElement.session.getParsedLibraryByElement(libraryElement).units`.

Note that at https://github.com/dart-lang/build/issues/1998 we're discussing the possibility that instead of bumping `package:build` to version 2.0.0, we'll simply bump `package:analyzer` to version 0.35.0.

I hope to publish version 0.35.0 of `package:analyzer` real soon (perhaps today).

**Comment by stereotype441** [comment]
@jakemac53 now that dart-lang/build#1998 has been closed, can we close out this issue?

**Comment by jakemac53** [comment]
Oh, I see the new api that Nate suggested should work now is the implication - if somebody can confirm here it does work then I think we can close this yes.
