### ISSUE TITLE
[vm/ffi] Support FFI in AOT configurations

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35765]
This task excludes callbacks: https://github.com/dart-lang/sdk/issues/37295

**Comment by sjindel-google** [comment]
## API changes

There are no API changes needed to implement AOT support, since we already require that the native type signatures passed to `fromFunction` and `asFunction` are fully instantiated at compile-time

## Implementation

Most of the FFI entry-points already work. The two which need support are `fromFunction` and `asFunction` since they trigger code compilation. This specific task only concerns `asFunction` (for Dart to native calls).

Presently, `asFunction` invokes the at runtime to generate trampolines. In order to avoid this, we need to:

1. Record the signatures of all `asFunction` call-sites in the program and store this information in the Kernel binary

2. Read the list of signatures in the precompiler and generate trampolines. Also store the trampolines in a library where they can be identified at runtime.

3. Lookup cached trampolines in the FFI library at runtime.

### Kernel stage

We propose to introduce a new metadata repository ("FfiCachedFunctions"?) in the Kernel binary which holds a set of `FunctionType`s along with an associated ID (int), which can be manufactured sequentially by `_FfiUseSiteTransformer`. Each `fromFunction` call-site will be re-written to pass the ID as an argument to (an internal copy of) `fromFunction`, and the metadata entries will be associated with the `dart:ffi` library.

### Precompiler

The precompiler will scan the all entries in the metadata repository and generate trampolines for them. Instead of all retaining the same name ("FfiTrampoline"), they will named according to their ID for resolution in `asFunction` (e.g., "FfiTrampoline_XXX").

### Runtime

`fromFunction` will simply access the ID passed by the modified Kernel code and resolve the corresponding function in the "dart:ffi" library.

**Comment by dcharkes** [comment]
This keeps kernel architecture agnostic, and does the architecture dependent assembly generation in the precompiler. lgtm

**Comment by sjindel-google** [comment]
Martin pointed out that this design would not allow the trampolines to be tree-shaken. To generate minimal code, we should implement the cache much later in the pipeline.

## Kernel

We will still have to annotate call-sites of `fromFunction` so the precompiler can recognize them, but we will not commit to generating any functions at this point.

## Precompiler

In the precompiler we will identify the `asFunction` call-sites during FG-building and create the `FfiTrampoline` functions immediately, which will be added to the precompiler queue. The precompiler can replace the `asFunction` call with IL to construct the closure immediately, something like:

```
ctx <- AllocateContext(1);
addr <- LoadField(receiver, RawPointer::c_memory_address);
StoreInstanceField(ctx, addr, 0);
cls <- AllocateObject(kClosureCid);
fn <- Constant(<trampoline function>);
StoreInstanceField(cls, fn, RawClosure::function_);
```

## Runtime

There are no runtime changes required -- `asFunction` is circumvented entirely in AOT.

**Comment by sjindel-google** [comment]
`lookupFunction` poses a challenge to this solution, because it contains a call-site to `asFunction` which doesn't have statically-instantiated type-arguments. We could identify it like `asFunction` in the FGB, but generating IL for it would be much more complicated.

Perhaps we can elaborate it in Kernel instead?

**Comment by sjindel-google** [comment]
@alexmarkov and I discussed the design today and he identified a few issues:

### `getStaticType` is unreliable

Due to #34081 we can't reliably access the receiver type of an interface call to `Pointer.asFunction` later in the pipeline, when the call-site annotator runs. We could throw an error in these cases, but it would force us to reject valid code. Alternatively, we could record the receiver type in the FFI transformation and store it into the call-site metadata, but the tree-shaker might delete classes used by the metadata.

### KBC doesn't support metadata yet

Since we need to process the `asFunction` call-sites during flow-graph building, we need access to the full receiver type of `asFunction` there as well. Threading it through a metadata repository won't work for KBC, since KBC doesn't support metadata yet.

## Solution

We discussed solving these issues by avoiding reliance on metadata altogether. The FFI transformation should be responsible for computing the receiver type and replacing the call to `asFunction` with an internal method which takes the receiver type as a constant argument. E.g.:

```dart
T _asFunctionInternal<T extends Function>(Type receiverType, Pointer receiver);
```

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/107407
