### ISSUE TITLE
Unexpected shell created when starting a Dart process from a process started with `ProcessStartMode.detachedWithStdio` on Windows

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#35809]
Update: Minimal repo and details provided in https://github.com/dart-lang/sdk/issues/35809#issuecomment-460015954

Initial comment:
`Process.start` with mode `detachedWithStdio` does not forward IO. The process will correctly start and print to the created cmd output, however no IO is received on the Dart side.

**Comment by grouma** [comment]
Note that a `cmd` Window is always created, regardless of the `runInShell` option. Could this be related?

**Comment by grouma** [comment]
I tried to repo this with a small example but I was unable to do so. I believe the issue is that `pub.bat run` starts the process in a detached cmd window.

**Comment by grouma** [comment]
I finally have a handle on this with a minimal repo. 

Issue:
If a process that is spawned with mode `ProcessStartMode.detachedWithStdio` spawns another Dart process without `ProcessStartMode.detachedWithStdio` it will pop open a new empty cmd shell titled `path\to\sdk\bin\dart.exe`. This is unexpected as no window should open.

Sample code:

Entrypoint (`lib\main.dart`):
```dart
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

void main() async {
  var process = await Process.start(
      Platform.executable, [p.join('lib', 'detached.dart')],
      mode: ProcessStartMode.detachedWithStdio);
  process.stdout.transform(utf8.decoder).listen(print);
  await process.exitCode;
}
```

Spawned process (`lib\detached.dart`):

```dart
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

void main() async {
  var process =
      await Process.start(Platform.executable, [p.join('lib', 'nested.dart')],
          // This creates a new shell!
          // Using ProcessStartMode.detachedWithStdio does not.
          mode: ProcessStartMode.normal);
  await process.stdout.transform(utf8.decoder).listen(print);
  await process.exitCode;
}

```
Nested process (`lib\nested.dart`):
```dart
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

void main() async {
  var process =
      await Process.start(Platform.executable, [p.join('lib', 'nested.dart')],
          // This creates a new shell!
          // Using ProcessStartMode.detachedWithStdio does not.
          mode: ProcessStartMode.normal);
  await process.stdout.transform(utf8.decoder).listen(print);
  await process.exitCode;
}
```

**Comment by bkonyi** [comment]
After some digging I'm thinking that this behavior might be working as intended. When the first process is spawned with the `ProcessStartMode.detachedWithStdio` flag, the process is created with no associated console. When the detached process attempts to spawn the nested process with `ProcessStartMode.normal`, the new process attempts to inherit the console from its spawner (the original detached process). However, since there's no console to inherit, the nested process spawns its own ([see DETACHED_PROCESS here](https://docs.microsoft.com/en-us/windows/desktop/procthread/process-creation-flags)).

We don't see this sort of behavior on POSIX systems as Windows has a significantly different approach when it comes to handling processes and consoles. In this situation, the detached process should probably be using `ProcessStart.detachedWithStdio` to achieve the desired results.

**Comment by grouma** [comment]
Thanks for taking a look Ben. I don't think I had the right mental model for detached. I agree that this is likely working as intended. For my specific case I need to ensure that all nested processes are started as `detachedWithStdio`. It's a littler cumbersome but I guess that's the only option.
