### ISSUE TITLE
Future force explicit and typed return to void 'C' bad

### ISSUE THREAD

**Issue by jackokring** [dart-lang/sdk#35830]
Windows version intellij, Jan 2019.

I consider it a big that asynchronous functions do not insist on an explicit Future return type   specification. How do I turn on such a feature?

Also when a typed return excluding 'void' is used without using the value, could the analyser insist I use some syntax such as 'null fn();' to indicate I know I'm throwing away a Future or anything for that matter and not using it.

Thanx.

**Comment by pq** [comment]
Thanks for the feedback @jackokring.  We've done a bit of work on the linter to help steer folks away from common async pitfalls so your input is really appreciated.  For the void case, you might also check out [avoid_void_async](http://dart-lang.github.io/linter/lints/avoid_void_async.html). 

/cc @MichaelRFairhurst

**Comment by pq** [comment]
Cycling back to this I don't see anything actionable beyond trying
[avoid_void_async](http://dart-lang.github.io/linter/lints/avoid_void_async.html) and following @lrhn's advice to use `unawaited` as an escape hatch.

Feel free to re-open if you think otherwise or feel free to open follow-up issues on the linter as well.

https://github.com/dart-lang/linter/issues/new/choose


Thanks again for the feedback!
