### ISSUE TITLE
Represent typedefs at runtime?

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#35853]
After switching to CFE, VM no longer creates classes for typedefs.
As a result, typedef's name is lost and not available at run time:
* in type literals
* in dart:mirrors
* in messages of failed type checks

Consider the following example:
```dart
import 'dart:mirrors';

typedef bool Predicate(int);

main() {
  print(Predicate);
  print(reflectType(Predicate));
  print(42 as Predicate);
}
```

Currently (in Dart 2) it prints:
```
(dynamic) => bool
FunctionTypeMirror on '(dynamic) -> dart.core.bool'
Unhandled exception:
type 'int' is not a subtype of type '(dynamic) => bool' in type cast
```

When run on Dart SDK 1.24.3 this example prints
```
Predicate
TypedefMirror on 'Predicate'
Unhandled exception:
type 'int' is not a subtype of type 'Predicate' in type cast where
  int is from dart:core
```

What is the desired behavior?
* If we would like to retain information about typedefs at run time, we should make sure CFE saves enough information about typedefs into kernel files and VM restores that info.
* If the current behavior is OK, then we should cleanup dart:mirrrors API (deprecate/remove TypedefMirror) and cleanup all code related to typedef classes from VM.

/cc @lrhn @leafpetersen @rmacnak-google @a-siva

**Comment by eernstg** [comment]
The language specification explicitly requires that two instances of `Type` that reify a type must be equal according to `operator ==` when they reify the same type, and also mentions the special case `\code{Type} instances for distinct type alias declarations declaring a name for the same function type are equal`. The point is that reified types should faithfully reflect the underlying type.

However, it is also recommended that such reified types can differ in other ways (in particular, they can return different strings from `toString()`), such that developers can get access to additional information which may be helpful (such as "this reified type was obtained by evaluating the type alias named `Foo`").

So there is nothing in the language specification that prevents a type alias reification from being able to report the name of that type alias.

However, it may very well be a breaking change to start using different instances for the same underlying function type in cases where it is currently the same instance, because there may be usages where object identity is used (say, in a mapping from types to functions), so it's not obvious that we can just make the requested change for free.

**Comment by lrhn** [comment]
I think the current behavior is OK. It's what I expect.

Dart class types are nominative, function types are structural. That means that two function types with the same type arguments, return type, and parameter signatures is the *same* function types. There is only one.

Type aliases *are* aliases, currently only for function types. We may introduce aliases for class types too.

As @eernstg wrote, that means that there can't be two different function types with the same function signature. It must be the same *type*.

Constant types are compile-time constants. We don't promise to canonicalize such types, but we do in some cases, and people might be relying on it.
Example:

So:
```dart
typedef F1 = int Function(int);
typedef F2 = int Function(int);
main() {
 const f1 = F1;
 const f2 = F2;
 print(f1 == f2); // Must print true. Fails in dart2js.
 print(identical(f1, f2));  // May print `true` or `false`, currently prints `true` on VM, `false` in dart2js.
}
```

**Comment by eernstg** [comment]
> `print(f1 == f2); // Must print true. Fails in dart2js.`

Just wondering if that would actually be true today, I just tried `dart2js` version 2.1.1-dev.3.2, and it does not fail.

**Comment by lrhn** [comment]
It fails on version 2.2.0-edge (tip of tree), so this might be a regression.

**Comment by alexmarkov** [comment]
@a-siva @rmacnak-google any thoughts?
Should we just do a cleanup in the VM and deprecate TypedefMirror?

**Comment by eernstg** [comment]
I'd think that deprecating TypedefMirror would be one step too far. We have the following dartdoc for `LibraryMirror.declarations`:

> Returns an immutable map of the declarations actually given in the library.
>
> This map includes all regular methods, getters, setters, fields, classes and
> typedefs actually declared in the library. The map is keyed by the simple
> names of the declarations.

So I'd expect the following to work (that is, to compile and run without errors, and print something that makes sense for a `TypedefMirror` on `F`):

```dart
library main;
import 'dart:mirrors';

typedef int F(int);

main() {
  LibraryMirror libraryMirror = currentMirrorSystem().findLibrary(#main);
  TypedefMirror typedefMirror = libraryMirror.declarations[#F];
  print(typedefMirror);
}
```

Interestingly, it runs, but it prints 'null'!

This would imply that it is already impossible to find type alias declarations via the `declarations` of the enclosing library. But that looks like a bug to me! If you're exploring a library using the `declarations` of a mirror on it, wouldn't you expect to get to the type alias declarations? How would you explain that they are omitted?
