### ISSUE TITLE
Warning: Tried to initialize from a previous compilation

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#35866]
During a `flutter test` run I got the following message. Reported here as requested.

```
Compiler message:
Warning: Tried to initialize from a previous compilation (file:///Users/goderbauer/dev/flutter/packages/flutter/build/testfile.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///var/folders/t2/r2h8ytq53_x45hn80bhpb0ww0044f6/T/initialize_from.dillVuR3Vz/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
```
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/2834235/initialize_from.dill.gz)

**Comment by goderbauer** [comment]
See also: https://github.com/dart-lang/sdk/issues/35695, https://github.com/dart-lang/sdk/issues/35476

**Comment by jensjoha** [comment]
https://github.com/flutter/engine/commit/194608290eee2f09cc9f60ddd4a41e57d8708e51 was done at around the time this bug was submitted.
Is it possible that you checked out a (slightly) older version of flutter, and then tested with that?

If the initialize-from-dill file was created with a version on or after  https://github.com/flutter/flutter/commit/9b053dd0d75a11e3dc678aded8cf940d3af5e104 and you then went back to a version of flutter before https://github.com/flutter/flutter/commit/b5e09735917cd75e4f3b5bf3b66adf7ea88bf3c2, we cannot initialize from the dill because the assumed sdk-file doesn't include the "enum Brightness" (we cannot find `root::dart:ui::Brightness`).

We certainly need a mechanism to catch stuff like this. I created https://github.com/dart-lang/sdk/issues/36032 for that.

**Comment by jensjoha** [comment]
I'll assume the above was correct. #36032 was created to remedy such situations (although its still not fixed).
