### ISSUE TITLE
Dart SDK readme is outdated

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#35898]
The `README` that [appears in the Dart SDK as supplied by Flutter](https://github.com/dart-lang/sdk/blob/master/README.dart-sdk) is outdated; it refers to a `packages/` subdirectory that doesn't exist, doesn't mention the `lib/` subdirectory, and has incorrect information about the contents of `version` and `revision`. Would be nice to update it appropriately.

**Comment by adrijshikhar** [comment]
@timsneath i would like to work on this issue.

**Comment by timsneath** [comment]
Great! 

You don't need my permission :) Feel free to submit a pull request, and we'll help you.

**Comment by parlough** [comment]
Fixed by a few commits over the past few years, including but not limited to: https://github.com/dart-lang/sdk/commit/baaf9200f599e26386bca653fded801fa2153c9e, https://github.com/dart-lang/sdk/commit/e4b830057a3383813d163fa08e4b123df68c4e65, and https://github.com/dart-lang/sdk/commit/bbdbd0728751f284eb5773453508946c1c35567b.
