### ISSUE TITLE
inconsistent treatment of void in literals

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#35893]
Illustrated on example:
```
void bar() {}
void func(Map map) {}
void main() {
  var z=  {"x": bar()}; // OK
  print(z); // prints {x: null} -OK
  print({"x": bar()}); // prints {x: null} -OK
  func(z); // OK
  // had to comment out b/c error: The expression here has a type of "void"
  //func({"x": bar()}); // WHY error???
  func({"x": bar()} as Map); // "info: Unnecessary cast" but call succeeds in runtime
  // but why was it declared "unnecessary" if it didn't work without it?
}
```

**Comment by lrhn** [comment]
This is an error.
As the specification is currently written, `{"x": bar()}` should be an error everywhere. A `void`-typed expression is a compile-time error except in a small list of cases. Those cases include assignment and parameters where the receiver has static type `void`, but it does not mention literals.

Both the analyzer and front-end miss this case. They seem to be working as if a `void` typed expression is allowed anywhere the context-type is `void`. Maybe that's what the specification should have been saying instead, but "context type" was not used in the specification at the time the list was written.

So, they accept `var z = {"x": bar()};` because the inferred type of `z` is `Map<String, void>`. 

The call `func({x: bar()}` fails because the context type of that map is `Map<dynamic, dynamic>`, and you can't use a `void` expression where a `dynamic` type is expected.

The `func({"x": bar()} as Map)` is unnecessary *as a cast* because the static type of `{"x": bar()}` is `Map<String, void>` which is assignable to `Map<dynamic, dynamic>`. It's not completely unnecessary because introducing it changes the context type for the map expression (there is no context type inside a `cast`, because the cast is there to convert between the expressions own type and the surrouding context type).

So, the tools are consistent and possibly smarter than the specification. It's still a bug.

**Comment by eernstg** [comment]
It is true that the specification does not mention composite literals (lists and maps) where some type arguments are `void`, but we do have such cases in a number of tests that were created in order to support the implementation. For instance, [`void_type_usage_test.dart`](https://github.com/dart-lang/sdk/blob/a5c53b03cd4a2bb5097077643279a7a7188dabfb/tests/language_2/void/void_type_usage_test.dart#L21) has the following:

```dart
...
Object testVoidParam(void x) {
  ...
  <void>[x];   //# param_literal_void_list_init: ok
  <Object>[x];   //# param_literal_list_init: compile-time error
  var m1 = <int, void>{4: x};   //# param_literal_map_value_init: ok
  var m2 = <void, int>{x : 4};   //# param_literal_map_key_init: ok
  var m3 = <dynamic, dynamic>{4: x};  //# param_literal_map_value_init2: compile-time error
  var m4 = <dynamic, dynamic>{x : 4};  //# param_literal_map_key_init2: compile-time error
  ...
}
```

Cases like this were added to this test file in 1a832455e67e1cc4f30e840160747095237b416d, clearly built on the expectation that elements in composite literals should be allowed to have type `void` when the corresponding type argument of the enclosing literal is `void` (inferred or specified). This might be a case where we should adjust the specification to express the intention that we have put into the test files (and that the implementations follow), rather than insisting on the current language in the spec.

**Comment by eernstg** [comment]
Discussed this with @lrhn IRL, changing labels.

**Comment by eernstg** [comment]
Given the discussions here, we might be just about to relax the rules such that collection literals can contain elements/keys/values of type `void`.

But then we have the following input, which might serve to say "no!, you can't do that":

This [StackOverflow question](https://stackoverflow.com/questions/55350820/fat-arrow-notation-with-curly-braces-in-setstate-dart-flutter) describes a situation where a developer who is new to Dart gets confused about a combination of things (`() => {...}` returns a set literal, but the `{...}` was assumed to be the body, and that set literal contained expressions of type `void` like `print(something)`).

With ['unified collections'](https://github.com/dart-lang/language/blob/master/accepted/future-releases/unified-collections/feature-specification.md), we could even have a set literal looking like this:

```dart
{ for (var i in xs) if (b) print("Hello, world!") }
```

Maybe, after all, it would be more helpful to keep the restriction ("a collection literal element/key/value cannot have type `void`"), such that we flag a larger subset of these set-literal-understood-as-a-block-of-statements situations?

**Comment by tatumizer** [comment]
Closing for the lack of interest.
