### ISSUE TITLE
Support Web Components v1

### ISSUE THREAD

**Issue by elmcrest** [dart-lang/sdk#35904]
hey again,

since the original issue was closed by @matanlurey I'm forced to create a new one, right?

I just wanted to add to issue #27445 the recent deprecation warning from Chrome. So after Chrome M73 my app will be broken even in Chrome... Google Dart Team, please help!

![telegram-cloud-file-2-255434779-298849-3260950519069668829](https://user-images.githubusercontent.com/931919/52562324-76d31980-2dfe-11e9-9673-65814c9a7d86.jpg)

**Comment by jmesserly** [comment]
Hi there! Is it possible you could use a polyfill?

I'd be interested in hearing more about the use case. Typically we only support features that are supported by all modern browsers; custom elements aren't implemented in Edge (although that will likely change once it is built on Blink), and Safari only has partial support (no subclassing existing element types). Custom Elements V0 were marked "experimental" in dart:html because we expected the spec would change (it wasn't standardized yet) and it wasn't clear if cross browser support would materialize.

Another thought here: would it be possible to migrate your app to one of our supported frameworks, such as https://webdev.dartlang.org/angular?

**Comment by elmcrest** [comment]
Not really, no. Also I dont‘t really agree on browser support... sure Safari is behind but Apple will eventually support it. 
And whatever that Edge is you‘re talking about, I don‘t mind non-relevant browsers ;)

So, yes, v0 was experimental - but I was assuming that‘s in favor of v1 which is standardized meanwhile, no?

If Angular wasn‘t such a beast and right from the developer experience completely non-progressive, it might be an Option... but as it is, not really. 

So I guess I have to port it to Typescript, which really sucks... peoject Hummingbird would be nice but Flutter is still only mobile, so also a long way to go.

**Comment by jmesserly** [comment]
Thanks for the feedback! That's really helpful. We'll consider what to do here, and whether supporting V1 is feasible with current architecture of dart:html. In the meantime, merging this into #27445.
