### ISSUE TITLE
Should we document that AssertionError is not intended for direct use?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#35923]
It's not clear to me that `AssertionError` should have a public constructor but removing it would be breaking.

What should we say in the doc comment about this error and it's constructor? Is it intended to be used by user code? If so, how?

cc @lrhn

**Comment by lrhn** [comment]
I see no reason to make any effort to prevent use of `AssertionError`.

All errors are intended to represent *programming errors* - they are expected to crash the program (or a contained part of it), and maybe get printed or logged. The only important information in an `Error` object is the `toString` message and the stack trace.
We have multiple error classes only because it makes it easier and more efficient to ensure consistent `toString` formats. If someone wants to use the format of an `AssertionError` for some reason, perhaps because they are manually throwing in code that only run with assertions enabled, then I see no problem with that.

Example:
```dart
static bool _debugValidate(object) {
  if (object is Floo) {
    if (!object.isFine) throw AssertionError("Floo is not fine");
    if (!object.isCrunchy) throw AssertionError("Floo is not crynchy");
    // or something more complicated.
  } else if (object is Fwee) {
    if (object.fweeness < 10) throw AssertionError("Fwee is not fwee enough");
  }
  return true;
}
...
  assert(_debugValidate(object));
...
```

That's a valid abstraction to make. You can write the message as the second operand of `assert`, but if you don't want to repeat the same logic again, it's easier to just throw manually when you see the mistake. (You might loose out on the VM's ability to show the text of the failing test in the `toString` message, but showing `_debugValidate(object)` isn't more informative than the custom message).
