### ISSUE TITLE
Dartanalyzer: Missing line/column information, Unexpected error for int-to-double cast

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#35940]
Our flutter-analyze builder turned recently red in [build](https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/flutter-analyze/866). The failure [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8921597460841759520/+/steps/analyze_flutter/0/stdout):
```
⏩ RUNNING: cd .; bin/flutter analyze --dartdocs --flutter-repo --dart-sdk /b/s/w/ir/cache/builder/sdk/out/ReleaseX64/dart-sdk
Analyzing 3 directories...                                      

  error • A value of type 'int' can't be assigned to a parameter of type 'double' • packages/flutter/lib/src/animation/curves.dart:1:1 • const_constructor_param_type_mismatch

1 issue found. (ran in 75.5s)
```

Notice the `:1:1`, i.e. line/column information is missing.

Also I was under the impression we have support in all tools for automatic int-to-double-literal conversion. Is this not the case? Does flutter explicitly turn on this warning?

@stereotype441 for routing the issue.

**Comment by stereotype441** [comment]
I'm able to reproduce this problem on the trybot `flutter-analyze-try`, e.g.: https://ci.chromium.org/p/dart/builders/luci.dart.try/flutter-analyze-try/32.  I'm now adding instrumentation to try to figure out what's going wrong.

**Comment by stereotype441** [comment]
Instrumentation has revealed that the error occurs when the analyzer is evaluating the constant `Curves.easeInOutExpo`, which is defined as `Cubic(1.0, 0, 0, 1.0)`.  Note that all parameters of the `Cubic` constructor have type `double`, so the two zeroes should be interpreted as `0.0`, and there should be no error.

Two weird things about this:
- The only constant that has this problem is `Cubic.easeInOutExpo`.  Other constants passing `0` to `Cubic` are fine (e.g. `easeInOutQuint`, which is defined as `Cubic(0.86, 0, 0.07, 1.0)`).
- https://github.com/flutter/flutter/commit/4309fe863af1dae98cd6e938880c377a85fffeb7 suppresses the bogus error, despite the fact that it doesn't touch the constant in question.

Here's my current working theory: prior to https://github.com/flutter/flutter/commit/4309fe863af1dae98cd6e938880c377a85fffeb7, the file `packages/flutter/test/animation/curves_test.dart` contained the constant value `const FlippedCurve(Curves.easeInOutExpo)`.  To check for constant evaluation errors in this constant value, the analyzer had to evaluate it, which in turn forced evaluation of `Curves.easeInOutExpo`.  Since this evaluation occurred while analyzing `packages/flutter/test/animation/curves_test.dart`, type inference was not performed in the file `packages/flutter/lib/src/animation/curves.dart` (where `Curves.easeInOutExpo` is declared), so the analyzer did not know that the integer zeroes should be converted to doubles, and it reported an error.  The reason `easeInOutQuint` had no similar problem is that it was never used inside of another constant, so the analyzer never had to constant evaluate it outside of the library it was declared in.  The reason https://github.com/flutter/flutter/commit/4309fe863af1dae98cd6e938880c377a85fffeb7 worked around the problem was because it removed the usage `const FlippedCurve(Curves.easeInOutExpo)`.

If this theory is correct, you should be able to work around the bug by replacing `const FlippedCurve(Curves.easeInOutExpo)` in `packages/flutter/test/animation/curves_test.dart` with just `FlippedCurve(Curves.easeInOutExpo)`.

I have to head to work soon, and then I'll be in meetings until 10:30.  I'll get back to this bug ASAP after that.  @tvolkert if you decide to try the above workaround in the meantime, let me know how it goes.  Either way, as soon as I'm free I'll confirm this theory and work on an analyzer fix.

**Comment by mkustermann** [comment]
I made a PR to temporarily just use double literals in https://github.com/flutter/flutter/pull/27929

Though the build is currently broken so I cannot land it atm.

**Comment by stereotype441** [comment]
I made a small unit test in the analyzer reproducing this issue: https://dart-review.googlesource.com/c/sdk/+/93284.  @scheglov is planning to look at it this afternoon.

**Comment by scheglov** [comment]
`test.dart`
```dart
class C {
  final double d;
  const C(this.d);
}
const C constant = const C(0);
```

`other.dart`
```dart
import 'test.dart';
class D {
  final C c;
  const D(this.c);
}
const D constant2 = const D(constant);
```


What happens is that when we analyze `other.dart`, we compute `constant2`, so we need the value of `constant`, but we don't have enough type inference information about `constant`, and don't know that `0` should considered `double`. So, we record an error in the evaluation result of `constant`. Later, when we analyze `test.dart`, we don't evaluate `constant` again, because it has already been evaluated. Unfortunately, it was evaluated incorrectly, and has an error that it should not have in the first place. To work this around, and make another work around work, we will clear constant evaluation results for the file we are analyzing.

**Comment by tvolkert** [comment]
Seeing similar behavior re-surface in https://github.com/dart-lang/sdk/issues/36013
