### ISSUE TITLE
False error message "type arguments should not be null" when compiled by dartdevc

### ISSUE THREAD

**Issue by fidlip** [dart-lang/sdk#36001]
Given this simple code to describe situation:
```dart
void main() {
  E();
}

abstract class A<T> {
  A();
}

abstract class B<T> extends A<T> {
  B() : super();
}


class E extends B<F> {}

class F extends B<E> {}
```
I got runtime error message when compiled with dartdevc:
```
Uncaught Error: type arguments should not be null: T => {
    class B extends main.A$(T) {}
    (B.new = function() {
      B.__proto__.new.call(this);
    }).prototype = B.prototype;
    dart.addTypeTests(B);
    B.prototype[_is_B_default] = true;
    return B;
  }
    at Object.dart.throwInternalError (dart_sdk.js:3587)
    at Object.makeGenericType [as B$] (dart_sdk.js:3750)
    at main.dart:25
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

When I tried to compile with dart2js, everything went as expected, so I presume it is really bug in dartdevc.
I've attached prepared simple project:
[dart-test-generic.tar.gz](https://github.com/dart-lang/sdk/files/2889295/dart-test-generic.tar.gz)

* Dart VM version: 2.1.1 (Unknown timestamp) on "linux_x64"
* Latest  Chrome and Firefox

**Comment by jmesserly** [comment]
setBaseClass is getting called to soon (before `test.E` is declared). I believe the issue is that `dartdevc` does not support mutually recursive non-generic classes (E and F in this example).

The ideal long-term fix is to change how DDC represents reified generic types (https://github.com/dart-lang/sdk/issues/31003), which would make it unnecessary to evaluate generic type arguments during module initialization.

A quick fix would be to change `body.addAll(deferredSupertypes);` so the deferred supertypes are evaluated near the end of the current module (after all classes are defined). Or alternatively, after the classes they depend on have been declared (but that requires more bookkeeping).

**Comment by jmesserly** [comment]
Testing a fix now. Thank you for the great illustration of the bug! That made it easy to track down.

**Comment by fidlip** [comment]
Thanks a lot for fast investigation! Looking forward to see it in action.

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/93924
