### ISSUE TITLE
operator "??" does not support throw expression - by design?

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#36014]
Expression `x ?? expr`, intuitively, should be equivalent to `x != null ? x : expr`, but it is not. 

```
x != null ? x : throw "error"; // OK
x ?? throw "error"; // Error
``` 
Is it so by design?

**Comment by sch1111878** [comment]
use '?:' instead?

**Comment by tatumizer** [comment]
> use '?:' instead?

I could use many things instead, but I was trying to point out an inconsistency in definitions.

**Comment by eernstg** [comment]
That's a syntax error; just use `x ?? (throw "error")`.

The underlying reason is that `??` requires an operand which is a `<logicalOrExpression>`, but `<throwExpression>` is derived directly from `<expression>` (so it's "more general" than `<logicalOrExpression>`).

**Comment by lrhn** [comment]
The precedence of `throw` is such that this does not work. See also #24891.

The `throw` operator binds weakly. It means that `throw foo + bar` means `throw (foo + bar)` and not `(throw foo) + bar`, because the latter is meaningless anyway. 
(In hindsight, that might not have been the best choice, because it prevents things like `foo ?? throw bar`, and you would not write `throw foo + bar` anyway, and it's confusing that it works differently from `await`).

As Erik has said, you have to wrap your throw in parentheses.

**Comment by tatumizer** [comment]
I think parentheses are fine, it just didn't occur to me that it could be a precedence problem.
In case someone's wondering why I needed it, the example is something like 
```var lastName = map["lastName"] ?? (throw "missing lastName")```

I'm closing the issue then. Thanks.
