### ISSUE TITLE
Enhancement suggestion: Allow null to be used in List.from()

### ISSUE THREAD

**Issue by sjmcdowall** [dart-lang/sdk#36012]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
2.1

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Flutter

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

I asked on gitter but no answer to this and I don't see this anywhere else..

So I am just putting this out there but is there a reason why "we" couldn't allow the use of null in the List.from operator to basically mean an empty list of whatever type? 

I am writing quite a bit of redundant code of the type:

```
 List<Foo> var = List<Foo>.from(var2 ?? <Foo>[]);
```

Because var2 could be null (it's coming from an outside source) .. I can't think of any downside to this but .. what do I know :)

Just thinking that 

```
 List<Foo> var = List<Foo>.from(var2);
```

Would be pretty clean and I wouldn't have to catch/try errors or write in the ?? stuff every time..

Just an idea..

**Comment by lrhn** [comment]
We plan to add non-nullable types to Dart, with the goal of catching errors where a value is accidentally `null`. Allowing `null` here would allow an *accidental* `null` value.

The parameter to `List.from` will become non-nullable, and in general, we will not treat `null` the same as "empty" (for strings or collections). It is a different value, and it's not clear that a `null` value represents no *elements* rather than no *collection*, or that the two cases should always be conflated. It might be convenient in this particular case, but it will be wrong in other cases.

So, I can see that it is convenient, but you will have to do either what you do here, or:
```dart
List<Foo> v = var2 == null ? [] : List.from(var2);
```
That's also more efficient than creating a new intermediate list, and the calling `List.from` with that list.

**Comment by sjmcdowall** [comment]
@lrhn -- OK fair enough.  However, to be exact and to avoid the mean linter errors the code really would be more like:

```
List<Foo> v = var2 == null ? <Foo>[] : <Foo>List.from(var2);
```

Which sort of brings up the question -- why can't Dart just "know" the types implied in cases like this?  Especially the [] case .. but even the .from() I would think could be implied as to the type? 

Cheers

**Comment by lrhn** [comment]
Dart should, and does, know the types. 

The code I wrote correctly infers the `<Foo>` on both the `[]` literal and the `List.from` constructor invocation from the context type. It has no warnings in the analyzer and runs in the VM, at least when run on the current tip-of-tree version of Dart.

**Comment by sjmcdowall** [comment]
Sorry I was unclear -- it's the dart linter that complains:

```
Specify type annotations.dart(always_specify_types)
(new) List.from(Iterable<dynamic> elements, {bool growable: true}) → List<String>
```

Which given the "always_specify_types" makes sense I guess .. and certainly **not** a core Dart SDK issue :) .  Just FYI - This is from the official Google Flutter Dart analyze_options.yaml  recipe (for lack of a better word).

Cheers!

**Comment by mraleph** [comment]
@sjmcdowall note that Flutter Framework has its own (strict) programming style, which does not necessarily match what is recommended for end users. They have a user analysis config (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml) which does not specify `always_specify_types`.

**Comment by sjmcdowall** [comment]
@mraleph -- Thanks -- wasn't aware of the "user" options version .. just been using the stricter one. 

Cheers!
