### ISSUE TITLE
The File.renameSync changes modified date of a file.

### ISSUE THREAD

**Issue by glennmichaelmejias** [dart-lang/sdk#36030]
* Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
  Engine • revision 7375a0f414
  Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
* Ubuntu 18.04.1 LTS

**Comment by zoechi** [comment]
I found https://stackoverflow.com/questions/21094274/how-to-rename-file-without-changing-the-modified-date (mv vs rename) which might be related

**Comment by lrhn** [comment]
The [Posix `rename` documentation](https://pubs.opengroup.org/onlinepubs/009695399/functions/rename.html) does not mention updating the modified time of the file, only of the containing directories, so it would probably be best if the Dart rename didn't update anything on the file (at least when renaming within the same partition, otherwise the rename operation is probably doing a move operation rather than kjust a rename).

**Comment by liamappelbe** [comment]
Looks like this was inadvertently fixed a while ago, so I added a regression test.
