### ISSUE TITLE
CFE not lowering set-literals in annotations

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36041]
The same code that causes a stack trace on the VM (https://github.com/dart-lang/sdk/issues/36040) is statically rejected by `dart2js`. I don't see a CFE error on the VM so I'm not sure if it's the same root cause or not.

Minimal repro:

```dart
class Foo {
  const Foo(Set<String> s);
}

@Foo({'a'})
void main() {}
```

Attempting to compile with `Dart-to-JavaScript compiler (dart2js) version: 2.2.0` results in:

```
Error: Not a compile-time constant.
@Foo({'a'})
     ^
Error: Compilation failed.
```

**Comment by natebosch** [comment]
DDC does not report any errors.

**Comment by sigmundch** [comment]
Note: this error no longer shows in master but still needs to be fixed in the CFE. To properly reproduce it, pick a commit before 15cd12beb4f7f342f1eeaa51b3d5de75c802c9c2.

In particular:
 * We have [disabled the CFE lowering][1] and we now handle Set literals directly in dart2js.
 * earlier CLs that add some of the features to be able to do this lowering included handling of set-literals in constants. [That logic][2] hides the CFE bug.

These changes are not in the stable channel and, IMO, should not be cherry-picked.

[1]: https://github.com/dart-lang/sdk/commit/7b86d78f0762ed397ddd7e9d28ea240872ed7810
[2]: https://github.com/dart-lang/sdk/commit/15cd12beb4f7f342f1eeaa51b3d5de75c802c9c2

**Comment by askeksa-google** [comment]
CFE bug is fixed in https://dart-review.googlesource.com/c/sdk/+/93941
