### ISSUE TITLE
Analyzer should recognize sealed classes via @pragma as well as @sealed

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#36044]
Currently the analyzer has Hint codes that are reported when notions of "sealed" classes are violated. This is only triggered when a class is annotated with `@sealed`, where `sealed` comes from the meta package. For cases where authors would like to avoid a new package dependency and import of `package:meta/meta.dart`, we could also consider a class annotated with `@pragma('analyzer:sealed')` as a sealed class as well.

CC @rakudrama

**Comment by bwilkerson** [comment]
What is the rationale for not having a dependency on 'meta'?

**Comment by rakudrama** [comment]
I want to change the protobuf code generator to generate libraries using the annotation.
It is not clear to me how the generator conveys to the build system that the generated library has another dependency. @pragma side-steps the issue.
I can try importing 'meta' into a protobuf runtime library and re-exporting the constant.

**Comment by lrhn** [comment]
Does the generated code have *any* dependency, say on `package:protobuf` itself? If so, `package:protobuf` could re-export `sealed` from `package:meta`, so it's available to the generated code.

(Alternatively, `package:meta` could just use `const pragma("analyzer:sealed")` as the value of `sealed`, instead of introducing a new class. Then you can recreate the value without depending on `package:meta`. It's obviously less readable than just `@sealed`).

**Comment by rakudrama** [comment]
I'll try re-exporting .

**Comment by srawlins** [comment]
Dropping this request.
