### ISSUE TITLE
Dart2JS encodes Object and void more expensively than dynamic

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#36075]
Sometimes we want to use `Object` or `void` in order to signify that some generic bound is unused or unimportant, and we don't want to accidentally encourage dynamic calls (via `dynamic`). For example, we have the following code in `AppViewData` in AngularDart:

```dart
class AppViewData {
  List<dynamic> projectedNodes;
}
```

In a routine refactor, I went and changed this to:

```dart
class AppViewData {
  List<Object> projectedNodes;
}
```

... but that actually caused a noticeable code-size regression:

```js
- this._compView_0.create$2(0, t1, []);
+ this._compView_0.create$2(0, t1, H.setRuntimeTypeInfo([], [P.Object]));
```

Can we treat `Object` (and `void`) as the "same" type signature as `dynamic`?

AFAICT, this has no impact on the runtime of the program (here is Dart2JS):

```dart
void main() {
  final lDynamic = <dynamic>[];
  final lObject = <Object>[];
  final lVoid = <void>[];
  
  print(lDynamic is List<Object>); // true
  print(lVoid is List<Object>);    // true
  print(lObject is List<dynamic>); // true
  print(lObject is List<void>);    // true
  print(lVoid is List<Object>);    // true
  print(lVoid is List<dynamic>);   // true
}
```

Can we, at least in a significant enough `-oX` mode, consider `<Object>` or `<void>` a no-op?

/cc @rakudrama @sigmundch

**Comment by matanlurey** [comment]
This will also cause problems with the lints that @srawlins is adding for us around strict inference.

**Comment by lrhn** [comment]
Dart 2 is designed so that there need not be any no run-time behavioral difference between `void`, `Object` and `dynamic`. We statically reject uses of `void` and we statically allow dynamic invocations on objects with static type `dynamic`, but there is no run-time subtype check or instance type check that can distinguish `void`, `Object` and `dynamic`. You should only need one of the types at run-time.

The only reason to retain a difference is for debugging purposes, so `<Object>[].runtimeType` and `<dynamic>[].runtimeType` prints differently, but the specification doesn't require this, and printing `List<Object>` in both cases is a valid implementation. The `Type` objects for `List<Object>` and `List<dynamic>` should be `==` equal (they aren't currently, but they should be).

**Comment by rakudrama** [comment]
The generated code here is likely to change a lot as we completely redesign the type representation #36085.

The distinction that we really need is `<void>`/`<dynamic>`/`<Object>` vs `<any>`, where `any` is a Dart1 style `dynamic` for JS-interop.
Since `<any>` is reserved to a simple JavaScript Array literal (`[]`), all the others will all require some code, unless we can tell that the type information is unused via some form of improved escape analysis*.

@matanlurey Can you quantify the 'noticeable code-size regression'? I think I'd like to revisit this issue after changing the type representation unless it is blocking. I notice that >40% of calls to `create()` pass an empty list. Could that be generated as an optional argument or separate named method?

----
* /cc @sigmundch Escape analysis is interesting here. In a large app there are thousands of calls to `create()`. The List argument passed to `create()` flows to the `AppViewData.projectableNodes` field. It can come from a List literal, or from the `projectableNodes` field of a different `AppViewData` instance. The list is indexed in many places, but not much else happens to it. Our current tracing approach from creation points might yield good results with unbounded tracing, but it would require O(N^2) tracing in this graph.

**Comment by matanlurey** [comment]
@rakudrama:

> Since `<any>` is reserved to a simple JavaScript Array literal (`[]`), **all the others will all require some code**, unless we can tell that the type information is unused via some form of improved escape analysis (see below).

Why do the other top-types need type information? Is a `List<Object>` worth encoding differently than `List<Any`>?

> Can you quantify the 'noticeable code-size regression'? 

Every single time we have a `List<dynamic>` in AngularDart we'd like to use a `List<Object>` without paying the cost of encoding it as `List<Object>`. It's not a large increase, but since it doesn't actually help in anyway implementing Dart semantics (see @lrhn's points) I'd prefer if it did not cost more.

> Could that be generated as an optional argument or separate named method?

Yeah, but out of scope of this particular request.

**Comment by matanlurey** [comment]
As per offline discussion, considering that `List<dynamic>` will become more like `List<Object>`, I will close this issue and wait for `List<JSAny>`. Thanks!
