### ISSUE TITLE
chars and natively iterable strings. 

### ISSUE THREAD

**Issue by ViralTaco** [dart-lang/sdk#36110]
`for (Char c in string) aMap[c] = c.toInt();`
Am I going to have to write that class? 
I mean is expecting all the primitives found in Java or C# too high of an expectation? 
Come on. 

Dart 2.2.0 macOS

**Comment by julemand101** [comment]
I am not entirely sure what you want but have you looked at the following:
https://api.dartlang.org/stable/2.2.0/dart-core/String/codeUnits.html
https://api.dartlang.org/stable/2.2.0/dart-core/String/codeUnitAt.html

**Comment by lrhn** [comment]
Expecting all operations in the Java *and* C# platform libraries might actually be too high an expectation. (Netiher C# nor Java satisfies that either :)

Dart does not have a native "character" type, just integers. Like Java, a char (code-unit, really0 is just an 16-bit unsigned integer, and in Dart, there is only one `int` type, so that's what a char is.

As @julemand101 suggested,
```dart
for (var char in string.codeUnits) aMap[char] = char;
```
should do something similar to the C# interpretation of your code.
