### ISSUE TITLE
Dart produces unexpected error message for `(null as String).length` expression

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#36119]
Dart SDK Version: 2.2.0-dev 2.1, 2.1.1-dev.3.2
OS: Windows 10 64 bit

The following test example tries to assign invalid expressions to three constants - c1, c2, c3:
``` dart
 main() {
  const c1 = null.length;
  const c2 = 1.length;
  const c3 = (null as String).length;
}
```

Each of these three lines expectedly throw compile time error. All is OK with analyzer, but dart output looks strange for `c3` variable.

`(Null as String).length` is not a valid construction and compile error should be thrown. But still it's  unclear why dart treats `null as String` as `bottom-type` class here. This happens only if `c3` is declared as a constant and with dart only. 

For `c1` and `c2` class names are detected correctly in the example above.

Does it go way with constant_update_2018 implementing or it's a side effect of some other problem?

Herer is a sample output:
> test.dart:4:20: Error: As expression is not a constant expression.
>   const c3 = (null as String).length;
>                    ^^
> test.dart:2:19: Error: The getter 'length' isn't defined for the class 'Null'.
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'length'.
>   const c1 = null.length;
>                   ^^^^^^
> test.dart:3:16: Error: The getter 'length' isn't defined for the class 'int'.
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'length'.
>   const c2 = 1.length;
>                ^^^^^^
> test.dart:4:31: Error: The getter 'length' isn't defined for the class 'bottom-type'.
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'length'.
>   const c3 = (null as String).length;
>                               ^^^^^^

**Comment by lrhn** [comment]
The `null.length` and `length` expressions are static type errors, so those never get to be evaluated.
The `(null as String).length` expression is type-correct, and is only an error because it throws when evaluated (at least with constant_update_2018 enabled).

The error here, "As expression is not a constant expression" suggests that this is run without constant_update_2018, because `as` expressions were not allowed as constant expressions before that.

I'm guessing the analyzer error-corrects the `as` expression to assume constant_update_2018 (might as well, since it knows it will become valid) and continues evaluation. It then *also* hits the throwing because `length` is not a defined on `Null`.
The error message for that is confusing, though, since it seems to be using the old static type of `null` (bottom, not `Null` as it is now) for the error message.

**Comment by srawlins** [comment]
The analyzer now produces sane messages here, without any reference to "bottom-type."
