### ISSUE TITLE
Analyzer doesn't appear to implement "greatest closure" part of the type inference spec.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#36129]
The type inference specification (https://github.com/dart-lang/language/pull/218) defines a "greatest closure" operation on types, but AFAICT there's no implementation of this operation in the analyzer.  @leafpetersen could you suggest some test cases we can use to determine whether the analyzer correctly implements this functionality?

If it does correctly implement this functionality, we should find where the code is that implements it, and add comments or rename methods so that we can find it in the future.  If it doesn't, we should implement it.

**Comment by leafpetersen** [comment]
This is implemented in the analyzer in generated/type_system.dart, in methods named `upperBoundForType` (aka greatest closure with respect to `?`) and `lowerBoundForType` (aka least closure with respect to `?`).

I'm not sure whether invariant uses are handled correctly or not (for whatever value of correctly we can manage, since there's not really a right answer there) but I believe the implementations are correct otherwise.

**Comment by stereotype441** [comment]
Thanks @leafpetersen!  I'm updating the code to use the term "greatest closure" so that next time we search for it we'll find it: https://dart-review.googlesource.com/c/sdk/+/96141
