### ISSUE TITLE
DDC / dart2js: Uncaught TypeError whe run with compiled js

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#36136]
* Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
* MacOSX
* Chrome

### foo.dart
```
library foo;
class Foo {

}
```

### bar.dart
```
library bar;

import 'foo.dart';

class Bar extends Foo {

}
```

### main.dart
```
import 'dart:async';
import 'package:quickstart/foo.dart';
import 'package:quickstart/bar.dart' deferred as comp;

void main() async {
  createFoo = (String type) {
    return handler[type]();
  };

  _addBeFoo('Bar',  () {
    return comp.loadLibrary()
      .then((_) => new comp.Bar());
  });

  Foo bar = await createFoo('Bar');
  print(bar);
}

typedef FutureOr<T> _Be<T>();
typedef FutureOr<Foo> beFoo(String type);

beFoo createFoo;
final handler = <String, _Be<Foo>>{};

void _addBeFoo(String type, _Be<Foo> beFoo) {
  handler[type] = beFoo;
}

```

There is no type error when run with `webdev serve`
But throw type error when run with js version (build with `dart2js -m -oweb/main.dart.js web/main.dart 
`)

```
main.dart.js:103 Uncaught TypeError: Closure 'minified:bD': type '(dynamic) => dynamic' is not a subtype of type '(Null) => FutureOr<minified:y>'
    at Object.a (main.dart.js:103)
    at Object.c (main.dart.js:322)
    at m.v (main.dart.js:1572)
    at m.u (main.dart.js:1577)
    at bF.$0 (main.dart.js:1936)
    at bE.$1 (main.dart.js:1933)
    at main.dart.js:1145
    at bw.a (main.dart.js:744)
    at bw.$2 (main.dart.js:1513)
    at Object.dd (main.dart.js:726)
```

**Comment by sigmundch** [comment]
Thanks @jimmyshiau for reporting this issue. And thank you so much for making a concise example that illustrates the problem!

Turns out you have run a known issue where deferred loading has a bug in dart2js. We ignore inferred types and as a result we incorrectly split programs in ways that break how types are reified. We statically think your closure `(_) => new comp.Bar()` returns a `Bar`, but at runtime we think it returns a `dynamic` because of this bug. 

The fix for this bug makes a lot of code to be loaded eagerly, so we are blocking releasing the bug fix until we fix how we split the code as well so we don't add a lot of work for people that depend on this feature.

You can find more details in https://github.com/dart-lang/sdk/issues/35311 if you are interested. You can also read about this in the [CHANGELOG](https://github.com/dart-lang/sdk/blob/a6a5a2b6359bf08e91a99992c238fd6dad623ed9/CHANGELOG.md#dart2js-1)

The inconsistency you see when using `webdev serve` comes from the fact that only dart2js actually splits the program when using deferred loading (the development compiler accepts the syntax, but still downloads all the code eagerly).

To fix the problem in your application, there are two options:
* Make sure the type `Bar` doesn't show up as an inferred type anywhere. To do that, you'd need to change your code from:
```dart
  .then((_) => new comp.Bar())
```

to

```dart
  .then((_) => new comp.Bar() as dynamic)
```

* Or, opt-in to use the algorithm that fixes the soundness issue by passing `--new-deferred-split` to dart2js. This will as a result download `Bar` with the main unit, so its possible this is not what you want.

In the next few months we will be implementing option (2) mentioned in that other bug, and at that point `--new-deferred-split` will be on by default.
