### ISSUE TITLE
The constant set element type 'double' can't override the == operator 

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#36159]
This code `const s = {1.0};` emits an compile time error.
> The constant set element type 'double' can't override the == operator. dart(const_set_element_type_implements_equals)

Dart VM version: 2.2.1-dev.0.0 (Unknown timestamp) on "linux_x64"

**Comment by Cat-sushi** [comment]
I think this is a analyzer issue.
I can run it.

**Comment by lrhn** [comment]
The error is expected and required behavior, so if you can run the code, then we have a bug in the VM and/or front-end.

A const set (or map key) cannot override `operator ==`, except for a small list of allowed system types. The `double` type is not on that list.

**Comment by matanlurey** [comment]
This error does not make any sense. Why not just add this as to the "small list of system types"?

**Comment by Cat-sushi** [comment]
For clarification, I didn't override `operator ==` of `double`.
I just declared a const Set.

**Comment by lrhn** [comment]
The `double` class itself overrides the `operator==` inherited from `Object`. It needs to because otherwise 0.0 would not equal the double -0.0, or the integer 0. The `operator==` of `Object` is just `identical`, and 0.0, -0.0 and 0 are not identical, but they are equal.

We could add `double` as a type that has compile-time constant equality, but it is not without consequences.

Both the constant and non-constant set literal (following map keys and switch cases) use `==` for equality. We don't want constant sets to have a different equality than non-constant maps. For the constants, we also don't want to run user code at compile-time, so we restrict to classes which don't override `Object.operator==` or which are on a short list of allowed system types that all act "nicely" (`String`, `int`, `Type` and `Symbol` only, even `bool` is not on the list). Basically, we want to be able to use identitiy in most cases without breaking the `==` contract (we can't use a user-written `hashCode` either), and constants of those classes are usually canonicalized (`Type` objects are not, sadly, so it might have been a mistake to allow them).

Currently the constant `Set` restrictions (which were copied from the constant `Map` keys and switch case values) are that you are not allowed to have two values which are *equal* according to `==`.
If we allow doubles, you still can't have a constant set trying to contain more than one of 0, 0.0 and -0.0., and it's very unclear whether `{double.nan, double.nan}` is allowed. Avoiding having to deal with NaN is one good reason to not allow doubles.

Maybe ee could allow doubles and just disallow NaN. Avoiding having both 0.0 and -0.0 in the same constant set literal should be doable (and if not, it's a compile-time error with a readable error message),
and avoiding integers and doubles with the same numerical value is also usually doable.

If sets of doubles are often used, then we may want to consider whether a change is worth it.

**Comment by Cat-sushi** [comment]
I myself don't have real use case of it, but I just feel it's not intuitive.

**Comment by Cat-sushi** [comment]
I myself don't have any real use case of it, but I just don't feel it's intuitive.

**Comment by Cat-sushi** [comment]
Const func/ method/ constructor/ operator can be a solution?
I mean only const func/ method/ constructor/ operator should be run at compile time of AOT.

**Comment by Cat-sushi** [comment]
I think dart has become more AOT compiled language, so compile time const becomes more important for optimization especially  in context of AOT compilation.

**Comment by Cat-sushi** [comment]
I'm confused.
What does this mean?
```dart
class C {
  final double x;
  const C(this.x);
}

const cp0 = C(0.0);
const cm0 = C(-0.0);

main(){
  print(identical(0.0, -0.0)); // falee
  print(0.0 == -0.0); // true
  print(identical(cp0.x, cm0.x)); // false
  print(cp0.x == cm0.x); // true
  print(identical(cp0, cm0)); // false
  print(cp0 == cm0); // false
  print(const{cp0, cm0}); // Error: Two values in a constant set can't be equal.
}
```

I suspect that the `const` `Set` in the last print line runs the `operator ==` of double.

**Comment by lrhn** [comment]
@Cat-sushi 
That's a bug. Where do you see this behavior?
There should not be an error on the last line. The two objects `cp0` and `cm0` are distinct and do not override `Object.operator==`, so they are also not equal according to `==`. It's just two completely distinct objects using identical for equality, and you should be able to make a set of those.

It *could* have been an issue when compiling to JavaScript because the dart2js `identical` just uses `===` which considers -0.0 and 0.0 as equal. When run on dart2js, this code prints true four times, but then prints false twice and succeeds creating the set. The VM runs this code without problem, but there is an error in the analyzer.
I'll file a bug.

**Comment by Cat-sushi** [comment]
> Dart VM version: 2.2.1-dev.1.0 (Unknown timestamp) on "linux_x64"

I executed it via VS Code.
