### ISSUE TITLE
Unhandled exception in approve_results.dart script

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36157]
I was trying to pre-approve test status changes using

tools/sdks/dart-sdk/bin/dart tools/approve_results.dart -b vm* -p https://dart-review.googlesource.com/c/sdk/+/94441/7

but then got the following exception

Unhandled exception:
Exception: The log at https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8919605319691735136/+/steps/gsutil_find_latest_build/0/logs/raw_io.output_text_latest_/0?format=raw doesn't exist
#0      loadLog (file:///usr/local/google/home/ajcbik/drive2/dart/sdk/tools/approve_results.dart:86:5)
<asynchronous suspension>
#1      todoFallbackLoadLog (file:///usr/local/google/home/ajcbik/drive2/dart/sdk/tools/approve_results.dart:107:20)
<asynchronous suspension>
#2      loadResultsFromBot (file:///usr/local/google/home/ajcbik/drive2/dart/sdk/tools/approve_results.dart:129:21)
<asynchronous suspension>
#3      main (file:///usr/local/google/home/ajcbik/drive2/dart/sdk/tools/approve_results.dart:493:14)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#9      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:737:16)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _cancelAndValue (dart:async/stream_pipe.dart:63:12)
#16     Stream.first.<anonymous closure> (dart:async/stream.dart:1170:11)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#22     _JsonStringDecoderSink.close (dart:convert/runtime/libconvert_patch.dart:1489:11)
#23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#25     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#26     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#27     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#28     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#29     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#30     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#31     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#32     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#33     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#34     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#35     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#36     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#37     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#38     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#39     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#40     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#41     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#42     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#43     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#44     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#45     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#46     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#47     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#48     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#49     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#50     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#51     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#52     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#53     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#54     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#55     _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#56     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#57     _StreamController.close (dart:async/stream_controller.dart:622:5)
#58     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#59     _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#60     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#61     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#62     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#63     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#64     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#65     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#66     _StreamController._add (dart:async/stream_controller.dart:640:7)
#67     _StreamController.add (dart:async/stream_controller.dart:586:5)
#68     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#69     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#70     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#71     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#72     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#73     _StreamController._add (dart:async/stream_controller.dart:640:7)
#74     _StreamController.add (dart:async/stream_controller.dart:586:5)
#75     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#76     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#77     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#78     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#79     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by aartbik** [comment]
@crelier

**Comment by crelier** [comment]
Even when the preapproval command does not crash, preapproved tests are still failing after committing.
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8919530372267517456/+/steps/test_results/0/logs/tests_that_began_failing/0

Shows:
The following tests began failing (needs approval):

vm/cc/CodeExecutability is new and failed (Crash, expected Pass)


Here is my preapproval done before committing:
regis@belenos:~/dart1/sdk$ tools/sdks/dart-sdk/bin/dart tools/approve_results.dart -p https://dart-review.googlesource.com/c/sdk/+/95263/11 -b vm-kernel-win*
Selected bot: vm-kernel-win-release-x64
Selected bot: vm-kernel-win-release-ia32
Selected bot: vm-kernel-win-product-x64
Selected bot: vm-kernel-win-debug-x64
Selected bot: vm-kernel-win-debug-ia32

The following tests are now failing:

| BOT                        | TEST                    | RESULT | EXPECTED | 
| -------------------------- | ----------------------- | ------ | -------- | 
| vm-kernel-win-debug-ia32   | vm/cc/CodeExecutability | Crash  | Pass     |
| vm-kernel-win-debug-x64    | vm/cc/CodeExecutability | Crash  | Pass     |
| vm-kernel-win-product-x64  | vm/cc/CodeExecutability | Crash  | Pass     |
| vm-kernel-win-release-ia32 | vm/cc/CodeExecutability | Crash  | Pass     |
| vm-kernel-win-release-x64  | vm/cc/CodeExecutability | Crash  | Pass     |

1804 of 50334 tests are failing (3.58%)
25 of 50334 tests are flaky (0.05%)
0 of 50334 tests were fixed since last approval (0.00%)
5 of 50334 tests were broken since last approval (0.01%)

Note: It is assumed bugs have been filed about the above failures before they are approved here.
Note: Approving the failures will turn the bots green on the next commit.
Warning: Preapproval is currently not sticky and somebody else approving before your CL has landed will undo your preapproval.
Do you want to approve? (yes/no) [yes] 

Uploading approved results...
Uploaded approved results for vm-kernel-win-debug-ia32
Uploaded approved results for vm-kernel-win-debug-x64
Uploaded approved results for vm-kernel-win-release-x64
Uploaded approved results for vm-kernel-win-product-x64
Uploaded approved results for vm-kernel-win-release-ia32
Successfully approved results, the next commit will turn bots green

**Comment by crelier** [comment]
Actually, preapprovals worked on some bots, but not all.

**Comment by crelier** [comment]
Also, some bots are not recognized by the script:
tools/sdks/dart-sdk/bin/dart tools/approve_results.dart -b dart2js-strong-win-x64-firefox
error: No bots matched pattern: dart2js-strong-win-x64-firefox

**Comment by sortie** [comment]
Hi. This happens whenever tryjobs have encountered infrastructure issues (alas, it happens) and approve_results fails to find the results. It can't proceed with approving the builders you requested (all of them by default) and stops. I'll improve the tool so it emits a warning and continues with the remaining builders, and tells you to look at the appropriate build for infrastructure issues.

**Comment by sortie** [comment]
Done. Be sure to update your approve_results.dart and let me know if there's any more problems.
