### ISSUE TITLE
Function can return super class as result instead of defined type

### ISSUE THREAD

**Issue by grundid** [dart-lang/sdk#36150]
The following example compiles fine, gives however runtime type errors:

```dart
class SuperClass {}

class SubClass extends SuperClass {}

SubClass getSubClass() {
  SuperClass test = SuperClass();
  return test;
}

```
This fails (correctly) if SuperClass is returned directly (The constructor returns type 'SuperClass' that isn't of expected type 'SubClass'.dart(strong_mode_invalid_cast_new_expr)):

```dart
SubClass getSubClass() {
  return SuperClass();
}
```

I detected this behavior when returning an Iterable where a Set was defined as return type:

```dart
Set<String> getNames() {
  return data.map((element) => element.name);
}
```

* Dart SDK Version (`dart --version`)
Dart VM version: 2.2.1-dev.0.0 (Wed Feb 27 18:37:05 2019 +0100) on "macos_x64"

**Comment by lrhn** [comment]
This is expected behavior.

Dart allows a statically superclass-typed value to be used where a subclass is expected, the compiler automatically inserts an "implicit downcast". 

It does mean that you get run-time errors rather than compile-time errors when you do such a down-cast, and the value ends up not being of the subclass type anyway.

The reason it is caught for `return Superclass()` is that the compiler is slightly more clever for a few expressions where it knows the *exact* type of a value. Since `Superclass` is a generative constructor, the compiler knows that the result of `Superclass()` is never an instance of `Subclass`.
When you assign the value to a variable, that knowledge is lost. The return statement just sees a variable typed `Superclass` which *could* contain a value of type `Subclass`.

**Comment by grundid** [comment]
Thank you for the explanation. Coming from the Java world, this behavior was a little unexpected.

The above error with the Iterable was only caught when compiling the release code with dart2js (AngularDart). During development the type error did not appear.
This would mean that I could have a Set that was an Iterable and that could contain the same value multiple times, right?

**Comment by lrhn** [comment]
If your value was an iterable and not a set, then it can contain the same element more than once, yes. You also can't add anything to it.

The development compiler is probably skipping some type tests for performance, but those tests are there for your protection. The language inserts them in order to prevent accidental run-time type incompatibilities from happening.
