### ISSUE TITLE
Ability for `==` to pretend to be a sealed type hurts performance

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#36166]
This issue is regarding Dart2JS, but seems to be due to a language requirement, so filing `area-meta`.
See also https://github.com/dart-lang/fixnum/issues/38.

Dart allows providing a user-implemented `==` function. For example:

```dart
class Size {
  final int bytes;

  const Size({this.bytes = 0});

  @override
  int get hashCode => bytes.hashCode;

  @override
  bool operator==(Object o) => o is Size && bytes == o.bytes;
}

void main() {
  var kiloByte = Size(bytes: 1024);
  var aLotOfBytes = Size(bytes: 1024);
  print(kiloByte == aLotOfBytes); // true
}
```

Cool! Unfortunately, you can also _pretend_ to be equal to something you are not equal to:

```dart
class Evil {
  const Evil();
  bool operator==(Object o) => true;
}

void main() {
  var evil = Evil();
  print('Hello' == evil); // false
  print(evil == 'Hello'); // true
}
```

Other than being a huge potential for bugs and weird invariants (`Set`, `Map`, etc), this also hampers Dart2JS' performance and is causing users to write strange non-idiomatic code. For example, I'm seeing:

```dart
// This is a silly example. Do not read too much into it, just wanted an example.
bool isNewSeniorCitizen(Map<String, Object> json) => 
  // Intentional: Emits better code, and this is called on a hot path.
  65 == json['age'];
```

I took the time to write a little sample program and compile it with Dart2JS:

```dart
@JS()
library example;

import 'package:meta/dart2js.dart' as dart2js;
import 'package:js/js.dart';

// Used to avoid Dart2JS understanding the whole world.
@JS()
external T defeatDart2JS<T>();

void main() {
  _checkSealedToNull();
  _checkNullToSealed();
  _checkSealedToAny();
  _checkAnyToSealed();
}

@dart2js.noInline
void _checkSealedToNull() {
  final string = defeatDart2JS<String>();
  print(string == null);
}

@dart2js.noInline
void _checkNullToSealed() {
  final string = defeatDart2JS<String>();
  print(null == string);
}

@dart2js.noInline
void _checkSealedToAny() {
  final object = defeatDart2JS<Object>();
  print(5 == object);
}

@dart2js.noInline
void _checkAnyToSealed() {
  final object = defeatDart2JS<Object>();
  print(object == 5);
}
```

... emits ...

```js
{
    main: function() {
      D._checkSealedToNull();
      D._checkNullToSealed();
      D._checkSealedToAny();
      D._checkAnyToSealed();
    },
    _checkSealedToNull: function() {
      // OK!
      P.print(self.defeatDart2JS() == null);
    },
    _checkNullToSealed: function() {
      // OK!
      P.print(null == self.defeatDart2JS());
    },
    _checkSealedToAny: function() {
      // OK!
      P.print(5 === self.defeatDart2JS());
    },
    _checkAnyToSealed: function() {
      // Interceptor, because we do not know if == or === can be used.
      P.print(J.$eq$(self.defeatDart2JS(), 5));
    }
};
```

Unfortunately, I am not in expert in Dart2JS. If someone can show me how to modify the compiler to always ignore the interceptor call, I could try and run some benchmarks and/or compile large apps inside Google and observe the compile-time overhead.

**Comment by rakudrama** [comment]
dart2js is limited in what it can do here. Since you can write `Evil`, we have to honor the language semantics. The VM has the same problem. Every receiver-dispatched language has this fundamental asymmetry between receiver and argument. If the receiver static type is `Object`, then we have to do some kind of dispatch to find the right method.

There are some simpler cases where we could do better, see #29618.

When the receiver is a primitive `J.$eq$` avoids the interceptor:
```js
    $eq$: function(receiver, a0) {
      if (receiver == null)
        return a0 == null;
      if (typeof receiver != "object")
        return a0 != null && receiver === a0;
      return J.getInterceptor$(receiver).$eq(receiver, a0);
    },
```
Since a lot of the `getInteceptor` code is checking again for primitive types, we could add a check here for a non-interceptor object and call it's `$eq` method directly, i.e. add this line:
```js
      if (receiver instanceof P.Object)
        return receiver.$eq(receiver, a0);
```
If the interceptor is used for other reasons the call will look like `t3.$eq(thing, 65)` and not enter the `J.$eq$` one-shot interceptor. But since you have the interceptor, you gain little benefit from not using it.


What would it take to compile `json['age'] == 65` to `json.$index["age"] == 65`?

First, dart2js would have to prove no class implements an 'evil' `operator==`. This is fragile because all it takes is one poorly written `==` method for the answer to be 'no'. I found one pretty quickly. In a sufficiently large program there will always be a bad one. We could maybe drive this to zero with the right lints.

Let us say we can prove that every implementation of `==` (except `num.==`) returns false when passed an `int`, and no implementation of `==` throws or has side-effects for `int`.
What do we do? For a limited number of types we could reduce `a == b` to `identical(a, b)`.

With regards to doing an experiment:
 I don't think you can completely ignore the interceptor call, otherwise dart2js will generate `a.$eq(0, b)` for `a == b` where `a` is a native class, which will crash. I would be surprised if there were no cases where this was a problem. I don't expect much change in compile time or code size, so the experiment is mainly for assessing performance impact. What would you replace the interceptor call with?

**Comment by matanlurey** [comment]
@rakudrama:

> dart2js is limited in what it can do here.

No expectation to make Dart2JS violate the language semantics, I... guess I'm asking for the language to change 😝. I guess, hypothetically, Dart2JS could look at every `operator==` live in the app, and see if they pretend to be various sealed types, and use that to optimize, but I'm guessing that isn't easy nor cheap.

> I found one pretty quickly. In a sufficiently large program there will always be a bad one. We could maybe drive this to zero with the right lints.

I would strongly support a lint that adds this restriction, how would you define it? If we could enable it in google3, we could add the appropriate `-oN` level of Dart2Js optimizations that can take advantage of that lint.

> I don't think you can completely ignore the interceptor call ... where `a` is a native class

Why is that? I guess what I am asking for is to _always_ lower to `identical` if the RHS is a sealed type.

**Comment by lrhn** [comment]
I'm not sure which realistic language change could possibly make a difference here.
(For example making `x == y` be implemented as `x.==(y)&y.==(x)` would fix the asymmetry, but hurt performance, so it's probably not viable).

The `==` is just a method invocation, there is nothing special about it. Anything here applies to any other method too.
(You might think there *should* be, and I'm inclined to agree, but we follow Java and C# in allowing you to override a virtual `equals`/`Equals` from `Object`, which is a choice that allows `HashMap` to "just work").


The optimization possible here seems to be that when all subclasses of the RHS class have the same `==` method, then the `==` method can be inlined. That goes for any virtual method that you can statically determine to be a specific variant, it's not just `==`. A sealed class can ensure that all subclasses are known. So can a private class. Any public class may be implemented elsewhere, so you need whole-program analysis to avoid the problem.

If that inlined equality is just `identical`, then things are easy. Enums is a good example of this, they are guaranteed to be sealed classes and don't override `Object.==`.

**Comment by matanlurey** [comment]
@lrhn: 

> The `==` is just a method invocation, there is nothing special about it. Anything here applies to any other method too.

That is not strictly speaking true. The language has special provisions, for example, to always treat a RHS of `null` differently. I guess what I am asking is to _extend_ that provision to _any_ sealed class on the RHS that does not implement `==` (i.e. `String`, `int`, `bool`, enums).

```dart
class Evil {
  operator==(_) => true;
}

void main() {
  print(Evil() == null); // false
}
```

**Comment by rakudrama** [comment]
@matanlurey `String`, `int`, `bool` are interfaces. The classes that implement those interfaces _do_ implement `==`, e.g. https://github.com/dart-lang/sdk/blob/master/runtime/lib/string_patch.dart#L268

**Comment by matanlurey** [comment]
@rakudrama: On Dart2JS they should be able to be treated as sealed without `==`, hence this bug.

**Comment by rakudrama** [comment]
@matanlurey, you asked "If someone can show me how to modify the compiler to always ignore the interceptor call, I could try and run some benchmarks and/or compile large apps inside Google and observe the compile-time overhead."

I have prepared a CL that rewrites `a == b` as `b == a` when `b` has a primitive type.
https://dart-review.googlesource.com/c/sdk/+/96667

Please report back on your findings.

**Comment by matanlurey** [comment]
Thank you! I will take an AI to try this!

**Comment by eernstg** [comment]
@matanlurey wrote:
> The language has special provisions, for example, to always 
> treat a RHS of null differently. I guess what I am asking is to extend that provision

Right, we have the notion of ["having a primitive operator `==`"](https://github.com/dart-lang/language/blob/ccf643aae01f746787994d66a22bd62063aa4d85/specification/dartLangSpec.tex#L2511). We use this in the specification to single out which objects can be compared during constant expression evaluation even though they may override operator `==` to be different from the one in `Object`.

So we could specify that `e1 == e2` gives special treatment in the case where `e1` has a primitive operator `==`. Then we could lint all the situations where `a == b` is used, and `b` is statically known to have a primitive operator `==`, but `a` is not.

This would include a few more dynamic type checks, but only in order to recognize those few platform classes that have a primitive operator `==`, and it would only be needed in the case where `a` has a type which is a supertype of such a platform class (that's something like top types and `num`, but nothing else). I have no idea whether that would be beneficial for performance, but we could benchmark that.

**Comment by matanlurey** [comment]
I am closing this as probably not possible, unfortunately :(
