### ISSUE TITLE
Inundated with lots GC events are overwhelming our memory charts.

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#36167]
GC events seem to fire many times, within 100-300 ms of the previous GC.  This causes a lot of events be recorded in our memory profiling chart.  Currently, I don't display a GC event if the previous GC happened with 500 ms.

Dart 2.2.1 Mac/Linux using Flutter 1.2

Can this be fixed or should I look at something in particular for a real GC?

**Comment by mraleph** [comment]
Please provide a reproduction. It can very well be that the code you are testing on is triggering GC every 100-300 ms (e.g. because new space overflows - thus triggering a scavenge). 

I don't think VM would issue a GC event if no event has occurred. /cc @rmacnak-google 

Also consider asking questions using dart-vm-team@ mailing list instead of the issue tracker, which is primarily used to track bugs.

**Comment by rmacnak-google** [comment]
A scavenge every 100ms is reasonable. DeltaBlue on desktop has a scavenge every 20ms.
