### ISSUE TITLE
Process.run and Powershell

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#36175]
Am I just escaping this wrong?  When I want to pass a script through to powershell, I have to do strange tricks.  I've tried several other combinations, but only this one works with the strange last formulation.

```dart
import 'dart:io';

Future<void> main() async {
  var script = 'ls';
  var result = await Process.run('powershell.exe', ['-command', script]);
  print('Trying powershell.exe -command $script');
  print(result.stdout); // good!
  script = '"Get-CimInstance Win32_Process -Filter \\\"name=\'dart.exe\'\\\""';
  result = await Process.run('powershell.exe', ['-command', script]);
  print(result.stdout); // errors
  print(result.stderr); // At line:1 char:42
                        // + "Get-CimInstance Win32_Process -Filter \"name='dart.exe'\""
                        // +                                          ~~~~~~~~~~~~~~~~~~
                        // Unexpected token 'name='dart.exe'\""' in expression or statement.
                        //     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
                        //     + FullyQualifiedErrorId : UnexpectedToken
  result = await Process.run('powershell.exe -command $script', []);
  print(result.stdout); // good!
}
```

**Comment by ZichangG** [comment]
Because the script as an argument will be escaped before passing into process, \\\" is problematic (I guess \" is what you want). And the beginning and ending double quotes should be removed, escaping function will add it automatically. 

`script = '"Get-CimInstance Win32_Process -Filter \\\"name=\'dart.exe\'\\\""'; // original one`
`script = 'Get-CimInstance Win32_Process -Filter \"name=\'dart.exe\'\"'; // works well for me`
