### ISSUE TITLE
dart2js wrapper creates illformed global object

### ISSUE THREAD

**Issue by mischnic** [dart-lang/sdk#36225]
The wrapper code created by dart2js creates an illformed global object (I don't really know anything about dart, so I unfortunately can't produce a dart code example).

`dart-sass` (take a look at the first three lines of the dart2js output at https://unpkg.com/dart-sass@1.17.2/sass.dart.js) has this problem when running in the browser.
Many getter properties on the overwritten `self` global object throw an error in all major browsers.
With a bundler, the produced JavaScript resembels this snippet:

```js
(function(global){
  // make sure to keep this as 'var'
  // we don't want block scoping
  var self = Object.create(global);
  // ...

  // above is created by dart2js

  console.log(self.location) // Error thrown described below
})(self);
```
(Pasting this alone into Firefox already triggers the behaviour)

**Chrome 72**:
In main (window) context: works
Running in a Web Worker: `Uncaught TypeError: Illegal invocation`
**Firefox 65**:
window: `TypeError: 'get location' called on an object that does not implement interface Window`
Worker: same error as in window (`... interface WorkerGlobalScope`)
**Safari 12**:
window: works
Worker: `The WorkerGlobalScope.location getter can only be used on instances of WorkerGlobalScope`

Dart SDK Version: `Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"`

**Comment by sigmundch** [comment]
/cc @nex3

@mischnic thanks for filing the bug.

I believe the issue here is not a dart2js bug, but an issue on how to consume the sass library in the browser.

Sass is compiling the code to run in nodejs, and uses a preamble to setup the javascript to run properly in that environment. The code you are referring to comes from that preamble (see https://github.com/mbullington/node_preamble.dart/blob/d98c8959347a9dac55e80a537c739ace0988b4fb/lib/preamble.dart#L6)

I'm not familiar enough to know whether there there is support for loading Sass directly in the browser,  but @nex3 is the lead of that project and should be able to help.

I'll close the issue here, but feel free to continue the conversation here or to reopen if I misunderstood and there is an action item for the dart2js team.

Cheers!

**Comment by mischnic** [comment]
Thanks for pointing me in the right direction!

> there is support for loading Sass directly in the browser

No, and my issue with dart-sass was already closed (not really sure why though): https://github.com/sass/dart-sass/issues/621.

**Comment by sigmundch** [comment]
In case it is useful, the preamble is added by the commands in dart-sass that generate the npm bundle here https://github.com/sass/dart-sass/blob/master/tool/grind/npm.dart#L57

if you are building things locally, you can remove the preamble there? While you are debugging things, you can also remove the `-O4` flag for dart2js to help you see unobfuscated code that is easier to debug. 

> ... my issue with dart-sass was already closed (not really sure why though): sass/dart-sass#621.

Can't say for sure, but it sounds like it was closed just because the idea was to move the discussion to stackoverflow instead?

**Comment by mischnic** [comment]
> if you are building things locally, you can remove the preamble there? While you are debugging things, you can also remove the -O4 flag for dart2js to help you see unobfuscated code that is easier to debug.

The main issue is that, in my situation, the compiled `dart-sass` is installed as a dependency in `node_modules`. So I can't really (persistently and safely) modify `dart-sass` itself.

> Can't say for sure, but it sounds like it was closed just because the idea was to move the discussion to stackoverflow instead?

That didn't work out at all 😄 
And there's even an issue regarding supporting running sass in the browser:  https://github.com/sass/dart-sass/issues/25, my issue wasn't really a "request for support".
