### ISSUE TITLE
sourcemaps aren't working with kernel/ddk externally (maybe internally too)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36236]
Need to investigate whether this is an issue with package:build, package:test, package:front_end, or package:dev_compiler.

I added the dev_compiler area for now just because there isn't a better option until we know more.

**Comment by jakemac53** [comment]
It looks like this isn't working because the Dart uris we get back have the `org-dartlang-app://` scheme - which makes sense on the kernel side of things given that is the uri we use to load the dart files.

We will have to figure out if we want to strip that out before writing the sourcemaps or handle it some other way.

**Comment by jakemac53** [comment]
I was able to clean this up in the source maps after the fact (within build_web_compilers), which while a bit gross does at least put the code in the place that has the knowledge of what needs to actually be done.

**Comment by jmesserly** [comment]
I believe @sigmundch designed the "org-dartlang-app://" scheme but I'm not sure the intent w.r.t. source maps.

You can pass `--multi-root-scheme` to configure it to something else, would that work? Or do you need the source maps to exactly match DDC+Analyzer? I seem to recall trying to make DDK match DDC, but I don't recall why that change didn't land.

**Comment by sigmundch** [comment]
Yeah, the special scheme has a bad interaction with source-maps.

We use it to hide machine-specific location information (tmp folders, etc) that especially interfere in distributed build systems like bazel. The main thing that makes it works for the CFE is that we use a custom URI scheme. For that reason, the URIs are incompabtible with browser's sourcemaps out of the box (since browsers will not understand any custom scheme). 

Our solution internally to support source-maps in dart2js is that we post-process the .source-map file and replace the scheme with a relative path that the development server understands. We could alternative have a flag to do that when invoking the compiler itself, but we found it simpler and more compositional to do it as a separate step.

Would that be feasible to do for DDK in `webdev serve`?

We haven't look into it, but someone recommended we look into generating source-maps with root-relative paths and provide a `sourceRoot` in the source-map header instead. It is equivalent to what we already do, but it would keep minimal the updates we need to make to the sourcemap files.

**Comment by jmesserly** [comment]
> We haven't look into it, but someone recommended we look into generating source-maps with root-relative paths and provide a sourceRoot in the source-map header instead. It is equivalent to what we already do, but it would keep minimal the updates we need to make to the sourcemap files.

Oooh, +1 that sounds very useful.

**Comment by vsmenon** [comment]
@jakemac53 @jmesserly - is the plan to handle in webdev / pbr or in ddk?

**Comment by jmesserly** [comment]
I think Siggi's theory is correct: ideally this should be handled by the server, because it knows where the files will be served from, and the compiler doesn't. We can make that transform easier by using the `sourceRoot` feature of source maps.

That's a longer term plan. Short term, if you need DDK to attempt to match DDC semantics, I can try to implement it. I'm not sure if we have all of the relevant information, but maybe we do.

**Comment by vsmenon** [comment]
@jakemac53 is post-processing in build.  Dropping this from 2.3.

**Comment by jakemac53** [comment]
One thing to note is this might make a `sourceRoot` change harder to land in the future - we will probably need to guard it behind a flag. That does sound like a better approach but manually editing all the sources works for now.
