### ISSUE TITLE
DDC on dev channel of Dart SDK breaks quiver

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#36264]
DDC on the dev channel of the SDK fails to compile quiver with the following error:

```
[SEVERE] build_web_compilers|ddc on package:package_resolver/package_resolver.dartdevc.module:
Error compiling dartdevc module:package_resolver|lib/package_resolver.ddc.js
[error] The imported library ''current_isolate_resolver_stub.dart'' can't have a part-of directive. (package:package_resolver/src/package_resolver.dart, line 12, col 8)
[error] The imported library ''utils_isolate_stub.dart'' can't have a part-of directive. (package:package_resolver/src/utils.dart, line 15, col 8)
Please fix all errors before compiling (warnings are okay).
}
```

https://travis-ci.org/google/quiver-dart/jobs/508581699

/cc @jmesserly @vsmenon @kevmoo

**Comment by jmesserly** [comment]
It looks like this is a package issue that has been fixed:
https://github.com/dart-lang/package_resolver/issues/26

**Comment by yjbanov** [comment]
Cool. Feel free to close whenever is appropriate.

**Comment by jmesserly** [comment]
Sounds good! I noticed https://github.com/dart-lang/package_resolver/issues/23 has more context on it. Seems a bad dependency constraint was published or something like that.

**Comment by natebosch** [comment]
A `pub upgrade` should solve this as long as you get `build_modules` version `1.0.8` or above.

What happened is that DDC was looking to follow the condition import _without_ `dart.library.isolate`, but when we were deciding which sources to make available to DDC we were treating it as if it was _with_ `dart.library.isolate`. The fix was to correct the list of dart libraries that DDC makes available so that we follow the correct branch on imports when deciding what files to use for compilation.

**Comment by yjbanov** [comment]
@natebosch Is the problem that we're caching `.pub-cache` here https://github.com/google/quiver-dart/blob/master/.travis.yml#L71?

**Comment by natebosch** [comment]
No, this shouldn't have anything to do with reusing a `.pub-cache`. That cache should be hermetic and never cause failures.

The problem was that `build_modules` never worked with conditional imports on `dart.library.isolate`, and it was never surfaced because no packages used such a conditional import. When we added one in `package_resolver` it exposed the bug in `build_modules`.
