### ISSUE TITLE
Runtime failure in package:test bootstrapping code with kernel/ddk

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36275]
We can now successfully build the tests but we get runtime failures (in the tests themselves).

The failure looks like this (unfortunately we don't have source maps working yet):

```
Cannot set property Symbol(_scanner) of [object Object] which has only a getter
  package:string_scanner/string_scanner.ddc.js 865:22       new
  package:string_scanner/string_scanner.ddc.js 612:14       get state
  package:boolean_selector/boolean_selector.ddc.js 853:112  [_getNext]
  package:boolean_selector/boolean_selector.ddc.js 835:60   peek
  package:boolean_selector/boolean_selector.ddc.js 845:29   scan
  package:boolean_selector/boolean_selector.ddc.js 988:38   [_and]
  package:boolean_selector/boolean_selector.ddc.js 982:28   [_or]
  package:boolean_selector/boolean_selector.ddc.js 972:32   [_conditional]
  package:boolean_selector/boolean_selector.ddc.js 965:40   parse
  package:boolean_selector/boolean_selector.ddc.js 224:61   parse
  package:test_api/test_api.ddc.js 848:140                  <fn>
  package:test_api/test_api.ddc.js 778:32                   _wrapFormatException
  package:test_api/test_api.ddc.js 848:70                   parse
  package:test_api/test_api.ddc.js 1532:129                 deserialize
  package:test_api/src/remote_listener.ddc.js 116:28        <fn>
  dart:sdk_internal 24965:9
```

I am not sure if this is a dev_compiler or kernel issue, or an issue in the code which only surfaces on the web for some reason.

**Comment by jakemac53** [comment]
For repro instructions you can checkout the `kernel-caching` branch of the build repo (http://github.com/dart-lang/build), cd into the `_test` directory, and run `pub run build_runner test -- -p chrome test/hello_world_test.dart`.

**Comment by jmesserly** [comment]
It looks like a bug in the compiler, I'll investigate.

**Comment by jmesserly** [comment]
I can reproduce by running DDC -k on https://github.com/dart-lang/string_scanner/blob/master/test/span_scanner_test.dart

**Comment by jakemac53** [comment]
> I can reproduce by running DDC -k on https://github.com/dart-lang/string_scanner/blob/master/test/span_scanner_test.dart

great, that should make it easier to diagnose hopefully :)

**Comment by jmesserly** [comment]
CFE is (correctly?) inserting a noSuchMethod stub for private getters such as `_scanner` in this example:
```
/// A class representing the state of a [SpanScanner].
class _SpanScannerState implements LineScannerState {
  /// The [SpanScanner] that created this.
  final RelativeSpanScanner _scanner;

  final int position;
  int get line => _scanner._sourceFile.getLine(position);
  int get column => _scanner._sourceFile.getColumn(position);

  _SpanScannerState(this._scanner, this.position);
}
```
The reason is that `LineScannerState` is in another library, so `LineScannerState._scanner` is not implemented here. Thus the nSM stub is correct, as long as its name correctly refers to its originating library, not the library with `_SpanScannerState`. I'll double check that.

DDC/K does not currently have the capability of referring to library-private names in another module, but I'm guessing that won't affect you because all of the package sources will be compiled together. I am putting together a fix for the cross module issue (library-private names will be exported, see https://github.com/dart-lang/sdk/issues/36252). The fix for that issue might fix this one too, I'll check.

**Comment by jmesserly** [comment]
Simple repro:
```dart
import 'test2.dart';
class C implements B {
  final int _x;
  C(this._x);
}

main() {
  var c = C(42);
  print(c._x);
}

// in test2.dart
class B {
  final int _x;
  B(this._x);
}
```

**Comment by jmesserly** [comment]
https://dart-review.googlesource.com/c/sdk/+/97441
