### ISSUE TITLE
Dart Native Extension: Plase provide a hook to extension "finalization" code

### ISSUE THREAD

**Issue by MoacirSchmidt** [dart-lang/sdk#36305]
Dart VM Native Extensions API already provide a hook for "init " extension:

Example:
```
sample_extension_Init()
```

Could you please provide a similar hook to "done" or "finalize" the extension?
```
sample_extension_Done()
```

The motivation is that on Windows OS all threads which uses COM Objects must call CoInitializeEx().

I usually call CoInitializaEx on "Init" hook but there is no place to call CoUninitialize();

Thanks in advance!

**Comment by dcharkes** [comment]
@kevmoo Native extensions is not the same as ffi.

**Comment by mkustermann** [comment]
@MoacirSchmidt Have you tried using `dart:ffi` instead of native extensions? It is more flexible, provides similar functionality and is much faster for calls between Dart <-> C.

We see the future of Dart <-> C interop in FFI and not our old native extensions.

> The motivation is that on Windows OS all threads which uses COM Objects must call CoInitializeEx().

Would you want such a callback to be invoked on shutdown of the application? (as long as dart code runs the native extensions would need to stay loaded)

**Comment by mit-mit** [comment]
Closing: native extensions are deprecated are expected to be removed, see https://github.com/dart-lang/sdk/issues/45451.
