### ISSUE TITLE
FFI: Support hardfp calling conventions on Linux ARM

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#36309]
We have only implemented the softfp calling convention, which is used by Android and iOS (regardless of whether hardfp support is available).

Linux ("gnueabi") uses the hardfp calling convention, we which must implement to support FFI on Linux ARM.

**Comment by dcharkes** [comment]
To implement:

> Any result whose type would satisfy the conditions for a VFP CPRC is returned in the appropriate number of consecutive VFP registers starting with the lowest numbered register (s0, d0, q0).

Float in s0, double in d0.

> There is one VFP co-processor register class using registers s0-s15 (d0-d7) for passing arguments.

Floats in s-registers, doubles in d-registers.

> Note that the rules require the ‘back-filling’ of unused co-processor registers that are skipped by the
alignment constraints of earlier arguments. The back-filling continues only so long as no VFP CPRC has been allocated to a slot on the stack.

Source: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ihi0042f/index.html

**Comment by mkustermann** [comment]
Let's try to target to have this ready by D27, so our configuration space is completed and `dart:ffi` works on all sdks we distribute.

**Comment by dcharkes** [comment]
In order to implement this we need refactor our logic in the FFI to compute the location of where arguments should be. We currently use the `Location` that is shared with the rest of the compiler that compiles everything according to the Dart ABI. And those `Location`s only support q-registers.

(Side note: supporting structs-by-value (https://github.com/dart-lang/sdk/issues/36730) requires the same refactoring. That introduces even more locations that are not used in the Dart ABI. Arbitrary size stack locations, allocated memory with a pointer in a register, etc.)

Let's see if it's feasible to get that done by D27.

**Comment by vsmenon** [comment]
How is this looking?  Flutter will begin picking release candidates tomorrow. ( fyi @mraleph @a-siva )

**Comment by dcharkes** [comment]
That's far fetched.
