### ISSUE TITLE
Allow a redirecting const constructor on a const-incompatible class

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#36315]
Currently, if you have a class that's not `const`-compatible it can't have a redirecting `const` constructor. This seems like an unnecessary restriction, since the constructor will redirect to a class that *is* `const`-compatible. See [this DartPad](https://dartpad.dartlang.org/ccc13e229087d69f308630d225e183a2) for an example.

**Comment by lrhn** [comment]
Good catch. Seems like an oversight in the specification to me.
The rules about non-constant initializers or non-final fields should only apply to generative constant constructors.

**Comment by eernstg** [comment]
Good catch indeed! ;-)

It should definitely be possible to have a constant redirecting factory constructor in a class, even in cases like the [dartpad example](https://dartpad.dartlang.org/ccc13e229087d69f308630d225e183a2) where that class couldn't have a constant generative constructor itself.

I think the problem arises because we have one location in the spec which makes an assumption tacitly, and we should make this assumption explicit:

In the section 'Constant Constructors', there is no grammar snippet or anything else that reveals exactly which constructors are included in the set 'constant constructors' as discussed at that point. However, we do have several sentences like ['The superinitializer that appears, explicitly or implicitly, in the initializer list of a constant constructor'](https://github.com/dart-lang/language/blob/965c37cc3a225abca63567c127840df0bf492613/specification/dartLangSpec.tex#L3435). This implies that a 'constant constructor' (in this section) has an initializer list and a superinitializer, even though they may be implicit, and this actually implies that it is a non-redirecting generative constant constructor.

With that, nothing that applies to a 'constant constructor' in this section is applicable to a redirecting factory constructor, in which case the dartpad example does not have a compile-time error.

But we should definitely adjust the wording in the spec to make it explicit that we're talking about a 'constant non-redirecting generative constructor' here, because it's impossible to see that a sentence like ['It is a compile-time error if a constant constructor is declared by a class $C$ if any instance variable declared in $C$ is initialized with an expression that is not a constant expression'](https://github.com/dart-lang/language/blob/965c37cc3a225abca63567c127840df0bf492613/specification/dartLangSpec.tex#L3428) does not apply to factories without scrutinizing the text around that sentence.

I created https://github.com/dart-lang/language/issues/289 which is concerned with the spec update.

**Comment by kevmoo** [comment]
@eernstg @lrhn – can this be closed? Or moved to the language repo?

**Comment by eernstg** [comment]
The issue dart-lang/language#289 holds the area-language part; that's about clarification of the wording in the spec. There is no doubt that there should not be an error when a class `C` has a constant redirecting factory constructor based on the properties of `C`, it is enough that the redirectee is a constant constructor, and the constancy related constraints are applied as usual based on the end point of the redirection chain.

The remaining effort in this issue is then to fix the relevant tools (analyzer, maybe CFE) such that the spurious error is not reported.
