### ISSUE TITLE
BigInt divide (/) operator should return a BigInt

### ISSUE THREAD

**Issue by TheBosZ** [dart-lang/sdk#36310]
> Dart VM version: 2.2.0-dev.0.0 (Mon Nov 19 15:10:42 2018 +0100) on "windows_x64"

I'm working on factoring large numbers and I came across a problem. When I divide a BigInt by another BigInt, the result is a double. Which means it gets truncated.

```dart
BigInt upper = BigInt.parse('9426890448883247745626185743057242473809693764078951663494238777294707070023223798882976159207729119823605850588608460429412647567360000000000000000000000');
BigInt divisor = BigInt.from(99);
print(upper / divisor); //9.522111564528534e+151
print((upper ~/ divisor) + upper.remainder(divisor)); //95221115645285330763900866091487297715249431960393451146406452295906132020436604029120971305128576967915210612006146064943562096640000000000000000000000
```

If I do an integer-division and add the remainder, it works as expected.

**Comment by kevmoo** [comment]
CC @lrhn

**Comment by lrhn** [comment]
In Dart, integer division uses the `~/` operator and always returns a non-fractional value.
The `/` division may return a fractional result and is always a double. 
That's also true for non-big integers.

We can't make `/` return a bigint because `BigInt.one / BigInt.two` cannot be represented exactly as a big-int. Dart does not have a "big decimal" type with arbitrary precision and a fractional part, which could otherwise have been the type of `/`.

So, as you recognized, you just have to use `~/`.
