### ISSUE TITLE
Document that JsonEncoder and JsonDecoder are not 1:1 Stream transformers

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36351]
I would not have expected `stream.transform(JsonEncoder())` to behave differently from `stream.map(JsonEncoder().convert)` - but it does. The latter emits a single String for a given input, the former will emit multiple Strings for a single input.

I think in other cases, like `Utf8Codec` the `.bind` is 1:1.

**Comment by lrhn** [comment]
There is a very significant difference when *decoding*, also for `uff8`, and you should probably always use `transform`. Never use `map` for *decoding*, unless you know that each event is a self-contained message.

The difference is that transform treats the entire stream as one large message, which has been chunked into smaller parts for transport, whereas `map` with a `convert` function treats each event as a separate unit to be decoded independently.

For UTF-8 decoding, you will see a difference if the bytes of an encoding of a single code point is spread over two messages. Say, the first event ends in `\xC3` and the next event starts with `\xA5` (because `\xC3\xA5` is the encoding of U+00E5, aka `å`), then the `map` approach will give two independent encoding errors, and the `transform` approach will correctly save the `\xC3` prefix byte until it has seen the continuation byte in the next event.

For encoding, it's not as clear-cut, but you can still see a difference for UTF-8 if one string bends with a lead surrogate and the next starts with a tail surrogate, then the `transform` encoding will combine those two into a single code point and a four-byte encoding, where the `map` approach will not.

For `JsonEncode`, you can only encode a single object. The `map` approach encodes the object in the event as a single string, because that's what `JsonEncoder().convert` returns.
The `transform` approach knows that it's creating a stream, and so it allows itself to use an internal buffer and flush as a new stream event when the buffer is full.

Whether `utf8.encoder` does the same thing or not is an implementation detail. Do not depend on it.

So, all in all, there is a difference even for `utf8`, even if you rarely hit it, and you should use the approach which matches what you are doing. The two approaches are not interchangable, and should not be expected to be.

**Comment by lrhn** [comment]
Or, in other words, *no* `StreamTransformer` promises to generate events in a one-to-one correspondance with input events, and very likely *none of them do*.

If the converter treats the source stream as chunks of a single input, then it is very likely that it maintains state between the chunks, and it's possible that it chunks its output differently from its input.

The `JsonEncoder` is perhaps unique in that it only accepts a single input, so I'll add a comment for that.

**Comment by natebosch** [comment]
> Or, in other words, _no_ `StreamTransformer` promises to generate events in a one-to-one correspondance with input events, and very likely _none of them do_.

Makes sense. I think it would be worth documenting this on `Codec`.

**Comment by lrhn** [comment]
It's hard to find a place to put the documentation that a stream converter doesn't have to be a one-to-one correspondance between input and output events. First of all becasue it's a negative property, writing it everywhere it applies is like saying everywhere that this function does not throw an `UnimplemnetedError`. Second, because it's not a *general* property of any of the abstract types, so we have to find the places where people *would* look for documenatation about the input/output behavior, and it's not at all clear to me where that is.

I'm fairly sure `Codec` is not the place. If I have a `JsonCodec`, I am very unlikely to read the documenation on `Codec` because the more specific documentation on `JsonCodec` covers all I need to know (I'd think, since I don't know what isn't there). Documenting it on `JsonCodec` might be possible, but then it should really be repeated on *almost* every `Codec` we have. 

I think the best places to document this might be `Stream.map` and `Stream.transform`, so I'll do that, and see where else might seem reasonable.

**Comment by natebosch** [comment]
That seems like a reasonable compromise.

FWIW I hit this because of some confusion around this API in `stream_channel`:  https://pub.dartlang.org/documentation/stream_channel/latest/stream_channel/StreamChannelTransformer/StreamChannelTransformer.fromCodec.html

This API is _not_ safe to use with `StreamChannelTransformer.fromCodec(JsonCodec())`. That might be why [`jsonDocument`](https://pub.dartlang.org/documentation/stream_channel/latest/stream_channel/jsonDocument.html) was implemented separately.

The only real world usage I see is `StreamChannelTransformer.fromCodec(utf8)`. Sounds like that is only safe if one message is expected since the code could split the string arbitrarily?

I wonder if I should have dropped that API in the last breaking change - `StreamChannelTransformer.map(T Function(S), S Function(T))` might have been safer, with usage like `StreamChannelTransformer.map(jsonEncode, jsonDecode);` or `StreamChannelTransformer.map(utf8.encode, utf8.decode);`
