### ISSUE TITLE
VM: Restore checking fingerprints of recognized methods

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36376]
VM used to check source fingerprints of 'recognized' methods in core libraries.

Condition in `Function::CheckSourceFingerprint` includes `kernel_offset() <= 0` which is false since Dart 2. We need to restore these checks.

/cc @aartbik @mraleph @a-siva @rmacnak-google

**Comment by cskau-g** [comment]
I believe this (temporarily) invalidates the comment here:
https://github.com/dart-lang/sdk/blob/c5ea3e85a097a52a063e4d8c061ad3b51299b15a/runtime/vm/compiler/recognized_methods_list.h#L12-L13

Since the code to generate the new fingerprints has been disabled:
https://github.com/dart-lang/sdk/blob/c5ea3e85a097a52a063e4d8c061ad3b51299b15a/runtime/vm/object.cc#L9165-L9170

Unless there's some other mechanism I'm unaware of we should probably amend the first comment to clarify expectations.

**Comment by alexmarkov** [comment]
Fingerprints checking was disabled once again when we had 2 versions of core libraries (sdk and sdk_nnbd).
After SDK unforking we have only one version of core libraries, so we should re-enable fingerprints checking by removing this `#if` and updating all fingerprints.
