### ISSUE TITLE
Adding a return type to a factory constructor reports no errors (but breaks formatter)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36400]
This code reports no errors:

```dart
class Test {
  Test factory Test() {
    return null;
  }

}
```

However trying to format it results in "The formatter produced unexpected output".

I'm not sure whether the code is valid and this is a formatter bug, or whether this is invalid code and should have an error (non-factory constructors to error if you give them a return type).

**Comment by bwilkerson** [comment]
> "The formatter produced unexpected output"

I believe that the formatter has a safety check that ensures that the changes it makes are all whitespace changes and that that's what produced this output (because the return type disappeared in the parsing).

@danrubel This is syntactically invalid, so I would have expected a parse error. My guess is that either the parser is failing to produce an error, or the error isn't being translated to an `AnalysisError`.
