### ISSUE TITLE
Parser error with generics

### ISSUE THREAD

**Issue by rmawatson** [dart-lang/sdk#36401]
* Dart SDK Version (`dart --version`)
Dart VM version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "windows_x64"

The dart parser appears to incorrectly parse parameterized generic types when not instantiated, and considers < to be the less than operator.

The following shows the problem

```
class Test<N>{}

Type GetTypeOfGeneric<T>()
{
  return T;
}

void main() {
	Type t = Test;
  print(t.toString());
  
  //Type t1 = Test<int>; doesn't work
  Type t2 = Test<int>().runtimeType;
  print(t2.toString());
  
  Type t3 = GetTypeOfGeneric<Test<int>>();
  print(t3.toString());
}
```

https://dartpad.dartlang.org/df278a7dad7e5beea1f9f3c76f511275

**Comment by eernstg** [comment]
There is no support for using a parameterized type (like `Test<int>`) as an expression, it's simply a syntax error. There has been some discussion about adding this kind of expression (it would be used for evaluating a parameterized type as an expression, and for explicit [generic function instantiation](https://github.com/dart-lang/language/blob/cc8a98edde6847d386ade8e7617c702deae5f1d6/specification/dartLangSpec.tex#L8984)), but the syntactic details have not yet been worked out, and it's not a given that it will be accepted into the language. The standard solution is a function like the one that you mention (`GetTypeOfGeneric`).

**Comment by rmawatson** [comment]
@eernstg - thanks. I was specifically wanting this to be able to pass as a parameter type to an annotation constructor, something like `@Annotation(type=SomeType)`.

The workaround is to pass an instance, which then is required to have const constructor on that passed type, or the function method above. Its a bit of a shame this isn't supported.

**Comment by eernstg** [comment]
It's quite likely that we will get syntactic support for parameterized types as expressions. One way to do that is to simply make `Test<int>` an expression, but another one which is just about to happen is support for `typedef MyType = Test<int>;`, which allows you to write `@Annotation(type=MyType)`. You might also simply be able to redefine `Annotation` such that the `type` is a type argument rather than a constructor argument. For that you'd need another workaround `const annotation = Annotation<SomeType<int>>();` and then `@annotation`.
