### ISSUE TITLE
strong_mode_invalid_super_invocation analysis error provides a broken URL

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#36403]
If I put the `super()` invocation anywhere but last in a constructor's initialization list, I get an analysis error:

> error • super call must be last in an initializer list (see https://goo.gl/EY6hDP): 'super()' at lib/foo.dart:32:9 • strong_mode_invalid_super_invocation

The provided URL redirects to https://www.dartlang.org/guides/language/effective-dart/usage#do-place-the-super-call-last-in-a-constructor-initialization-list, but there is no corresponding section in Effective Dart for that URL's fragment.

(Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "linux_x64")

**Comment by eernstg** [comment]
This is working as intended: https://github.com/dart-lang/language/blob/cc8a98edde6847d386ade8e7617c702deae5f1d6/specification/dartLangSpec.tex#L3042.

**Comment by jamesderlin** [comment]
Erik, please re-open this and re-read what this bug is about.

This bug is about the broken URL in the error message.  Either Effective Dart should be updated so that the URL actually points to relevant information or the error message should be changed to reference else.

**Comment by eernstg** [comment]
Sorry, I misread the original text as "I shouldn't get an error .." (and that's wrong: it is an error), but I can see, now, that the actual problem is the misplaced URL. So that's what this issue is now about:

`INVALID_SUPER_INVOCATION` in 'pkg/analyzer/lib/src/error/codes.dart' should not refer to `https://goo.gl/EY6hDP`, because that's an obsolete URL.

It looks like there is no mention of this error in 'Effective Dart' (so there is no suitable target for such a URL in that document), but that's true for a lot of other errors as well. It's probably best to simply delete the URL.

**Comment by srawlins** [comment]
The link is no longer present.
