### ISSUE TITLE
Bridge all differences being seen in optimized JIT between the AST based version and the bytecode based version

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36429]
Currently we are seeing a diference in behaviour between the AST based optimizing JIT and the bytecode based optimizing JIT. These differences need to be investigated and fixed.

**Comment by alexmarkov** [comment]
Related issue: https://github.com/dart-lang/sdk/issues/36342

**Comment by alexmarkov** [comment]
Summary on several outstanding benchmarks:

* FluidMotion is slower with interpreter compared to bytecode JIT and default modes due to https://github.com/dart-lang/sdk/issues/36880.
* NavierStokes and NavierStokesTyped are slower with interpreter compared to bytecode JIT and default modes due to https://github.com/dart-lang/sdk/issues/36887 and https://github.com/dart-lang/sdk/issues/36880.
* DeltaBlueClosures is slower on x64 in bytecode modes compared to default mode due to https://github.com/dart-lang/sdk/issues/36889.

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.

**Comment by doodlewind** [comment]
> Bytecode mode is removed from Dart VM.

@alexmarkov Do you mean the Dart Bytecode Interpreter is removed? If so, how does Flutter running its iOS debug mode then? I'm trying to make a minimal Dart VM build on iOS, but no guide or build args can be found. I'd appreciate any tips, thanks.
