### ISSUE TITLE
Move all debugging functionality out from unoptimized code to the interpreter 

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36427]
Move all debugging functionality out from unoptimized code to the interpreter so the unoptimized code does not have to make any of the runtime debugger check calls.

**Comment by crelier** [comment]
It was decided to support simultaneous debugging of interpreted and compiled code (compiled from bytecode or from AST). We can consider this issue as closed, since it is now possible to debug compiled bytecode in the same way as unoptimized code. There are still a few service tests failing when using the mixed mode interpreted/compiled, but they will be addressed as we deploy this mode.
