### ISSUE TITLE
make loading and executing from a kernel file with bytecodes the default execution mode

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36425]
Switch the default execution mode for the VM to load and execute from a kernel file that has bytecodes in it.

**Comment by alexmarkov** [comment]
In order to fully switch to bytecode pipeline in JIT mode, we need to do the following:

- [ ] Make sure performance of bytecode/JIT mode is tracked on Golem and on par with default mode (https://github.com/dart-lang/sdk/issues/36429)
- [ ] Add all missing debugging and vm-service capabilities to bytecode mode.
- [ ] Make sure hot reload works in bytecode mode.
- [ ] Make sure bytecode/JIT mode passes all tests which are passed in default mode (not just a subset of tests).
- [ ] Hook up bytecode to Flutter and make sure there are no regressions.
- [ ] Support mirrors and native extensions in bytecode.

In order to switch to bytecode in AOT mode, we need to do the following:

- [ ] Support AOT metadata in bytecode (writing and reading the metadata). Teach bytecode generator to understand AOT metadata where appropriate (e.g. generate direct calls for devirtualized instance calls).
- [ ] Make sure performance of bytecode/AOT mode is tracked on Golem and on par with default mode.
- [ ] Make sure bytecode/AOT mode passes all tests which are passed in default mode.

/cc @a-siva @mraleph

**Comment by alexmarkov** [comment]
Bytecode mode is removed from Dart VM.
