### ISSUE TITLE
Flakiness dashboard should include DartkCrash

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#36459]
Currently tests which produce `DartkCrash` flakily are completely hidden.

Some VM bugs manifest themselves as flaky runtime-errors in the CFE, so we should include this information in the VM flakiness dashboard.

@mraleph

**Comment by whesse** [comment]
There is currently only one example of a test marked flaky that has a dartk result: a test that expects a static error, and has 83 times had that, and 1 time had a dartk crash.

Our systems have a problem, because if a field isn't present in any of the json input files (the flaky.json files from all the builders), then the field is missing from the merged CSV file, and the dashboard crashes because it tries to display it.  I had solved that by skipping records with dartk crashes, and not having those fields, because they would disappear or reappear depending whether there was any builder with a current dartk flaky test.

I will create a dummy json file, with entries for all the fields we want, and put it in the source directories for our data transfer feed.  This will ensure there are always the dartkcrash fields in the merged CSV file.

**Comment by whesse** [comment]
Dummy json file created, called
dart-test-results/builders/current_flakiness/single_directory/flaky_current_a_dummy_builder.json
with contents shown at end.
Xenon data feed (merge) changed to add the DartkCrash fields in a fixed order, stop dropping those records.
PLX configuration not yet changed to import them.

JSON:
{"configuration":"app_jitk-linux-debug-x64","name":"dummy/test/with/all/flakiness/data/fields","expected":"Pass","outcomes":["CompileTimeError","Crash","DartkCrash","Fail","Pass","RuntimeError","Timeout"],"last_new_result_seen":"2019-06-12T18:41:15.125727","current":"Pass","current_counter":24,"occurrences":{"CompileTimeError":1,"Crash":1,"DartkCrash":1,"Fail":1,"Pass":1,"RuntimeError":1,"Timeout":1},"first_seen":{"CompileTimeError":"2010-01-01T00:00:00","Crash":"2010-01-01T00:00:00","DartkCrash":"2010-01-01T00:00:00","Fail":"2010-01-01T00:00:00","Pass":"2010-01-01T00:00:00","RuntimeError":"2010-01-01T00:00:00","Timeout":"2010-01-01T00:00:00"},"last_seen":{"CompileTimeError":"2010-01-01T00:00:00","Crash":"2010-01-01T00:00:00","DartkCrash":"2010-01-01T00:00:00","Fail":"2010-01-01T00:00:00","Pass":"2010-01-01T00:00:00","RuntimeError":"2010-01-01T00:00:00","Timeout":"2010-01-01T00:00:00"},"matches":{"CompileTimeError":false,"Crash":false,"DartkCrash":false,"Fail":false,"Pass":true,"RuntimeError":false,"Timeout":false},"build_ids":{"CompileTimeError":"dummy_build_id","Crash":"dummy_build_id","DartkCrash":"dummy_build_id","Fail":"dummy_build_id","Pass":"dummy_build_id","RuntimeError":"dummy_build_id","Timeout":"dummy_build_id"},"commits":{"CompileTimeError":"dummy_commit_hash","Crash":"dummy_commit_hash","DartkCrash":"dummy_commit_hash","Fail":"dummy_commit_hash","Pass":"dummy_commit_hash","RuntimeError":"dummy_commit_hash","Timeout":"dummy_commit_hash"}}

**Comment by sortie** [comment]
Sounds good to me. You might want to put `NonUtf8Output` in there as well, since that's the last outcome we don't handle.

Do you filter away `dummy/test/with/all/flakiness/data/fields` on the dashboard?

You need to document gs://dart-test-results/builders/current_flakiness/single_directory/flaky_current_a_dummy_builder.json
 somewhere. Where do you think the right place is?

**Comment by sortie** [comment]
Bill, you added the dummy data, can you also edit the data source / dashboard now to include the flakes for DartkCrash, NonUtf8Output?

**Comment by whesse** [comment]
Thanks for reminding me, I'll put it on my todos for tomorrow.  I think I already added the data, it's just not displayed.

**Comment by whesse** [comment]
Started working on this, ran into dead ends, found I need to run a SQL create external table script to link the new fields of the CSV file into a PLX data source, will continue with that next.

**Comment by whesse** [comment]
go/dart-vm-flakiness and go/dart-flakiness now include DartkCrash flakes as well.  There are currently none of them.  go/dart-vm-flakiness is just go/dart-flakiness with a filter that restricts to dart-vm configurations.
