### ISSUE TITLE
CFE: define 'dart.library.foo' environment variables automatically using the contents of platform dill file

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#36460]
For each public dart:foo library implementation defines dart.library.foo=true environment variable. In order to populate CompilerOptions.environmentDefines before CFE is invoked the list of libraries is hardcoded

https://github.com/dart-lang/sdk/blob/93d0e8279a4d898632ab0aee3f2489f0e8f3ed08/pkg/dev_compiler/lib/src/compiler/shared_command.dart#L25-L49

or derived from Target.extraRequiredLibraries (https://dart-review.googlesource.com/c/sdk/+/98435/1/pkg/vm/lib/kernel_front_end.dart), which is fragile.

It would be cleaner if CFE would define these environment variables automatically using the contents of platform dill file (after reading platform but before doing constant evaluation in the application code).

/cc @kmillikin @askeksa-google @johnniwinther

**Comment by sigmundch** [comment]
They should be defined automatically, but it should not be done blindly based on what's in the platform files. It should instead use the specification provided in `libraries.json`. That's because some targets allow importing libraries for backward compatibility, but still override the conditional imports to indicate that they are not supported.

See also https://github.com/dart-lang/sdk/blob/ddbeda075febd1d1af61f8da9a15dbdbd86de8a9/pkg/front_end/lib/src/api_unstable/dart2js.dart#L211

**Comment by alexmarkov** [comment]
I'm not sure we're carrying `libraries.json` with us everywhere, so it might be unavailable when building applications. We're not setting `CompilerOptions.librariesSpecificationUri` in frontend server or gen_kernel.

We can pass the information about supported libraries from `libraries.json` through platform dill file. Library kernel nodes could be extended with isSupported flag which is set when building platform and tested to populate `dart.library.*` defines when building applications.

**Comment by johnniwinther** [comment]
@alexmarkov Sounds like a good plan. I'll start working on it.
