### ISSUE TITLE
The Dart analyser could deduce that a return statement isn't needed when using switch statement

### ISSUE THREAD

**Issue by sadeernasser** [dart-lang/sdk#36461]
* Dart SDK Version: 2.2.1-dev.2.0 (on Linux)

The Dart analyser could deduce that a return statement isn't needed. Let's suppose I have an enum defined like this:
`enum Car { auto, manual }`

And I have a function that maps each enum value to a string like so:
```
String carToString(Car car) {
    switch (car) {
      case Car.auto:
        return 'Auto';

      case Car.manual:
        return 'Manual';
    }
  }
```
The compiler will not like that and will complain my function doesn't end with a return statement even though my switch statement exhausts all the enum values.

This forces me to return a null or throw an exception after the switch statement to keep the compiler happy but it feel superficial and also my unit tests would never be able to test that path.

**Comment by bwilkerson** [comment]
This is a common frustration, and one that I hope we will be able to address in the near future.

The problem is that `car` can be `null`. Almost all users assume that `null` will never be passed in for an enum value, but it's perfectly legal in Dart to do so. As a result, the switch doesn't actually catch all possible values for the parameter, and hence the error.

Note that as the code was written there is an implicit return of `null` at the end of the method, so if someone were to invoke `carToString(null)`, the method would return `null`.
