### ISSUE TITLE
js number constants need to expose their type based on their internal value

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36477]
**Problem**: 
When using js-number semantics, all values need to be represented as `double`, however at the Dart static type system, we need to consider round numbers as `int`s.

At this time our implementation uses an in-memory class `JavascriptIntConstant` that represents js-numbers. The `JavaScriptIntConstant` extends `DoubleConstant` and overrides `getType` so we get the correct type when compiling an entire program in memory. `JavaScriptIntConstant` is a CFE only class, it gets serialized as a `DoubleConstant`. As a result, after deserialization, the `getType` API always returns `double`, even for integral values.

This causes issues in modular compilation. And in dart2js in consuming constants from the SDK platform files.

**Repro**:

You can reproduce the issue with this example:

*const_issue.dart*:
```dart
import 'dart:html';
const a = <int, String>{
  13: 'bad bad',
};

main() {
  print(KeyCode.ENTER);
  print(a);
}
``` 

Then:
* enable constant-update-2018 by default
* compile the dart2js platform files (so KeyCode.ENTER is compiled to 13.0 as a double)
* then compile the program above, and you'll get this error:

```
const_issue.dart:3:3:
Error: Expected constant '13.0' to be of type 'int', but was of type 'double'.
  13: 'bad bad',
  ^
const_issue.dart:8:9:
Info: While analyzing:
  print(a);
        ^
const_issue.dart:2:24:
Error: Constant expression depends on itself.
const a = <int, String>{
                       ^
const_issue.dart:2:7:
Info: While analyzing:
const a = <int, String>{
      ^
Error: Compilation failed.
```

**Possible solutions**

We have discussed a couple solutions offline:
* Support `JavaScriptIntConstant` as part of the kernel API. This will allow to serialize the special value differently.
* Remove `getType` from constant, and instead delegate to the `Target` or to the `ConstantBackend` how the type is computed.

/cc @fishythefish @johnniwinther @askeksa-google

**Comment by sigmundch** [comment]
I've updated the description above with more context and details.

@kmillikin @askeksa-google - please take a look. If you need us to, we can help with implementation, but we need you to decide how we should solve this.

**Comment by lrhn** [comment]
The JS number model is that all number *values* implement `double` and some implement `int` as well. The actual type of `13` would be some `_JSInt` (which also implements `double`), neither `int` nor `double`. So, while the constant value might be *representable* as a 64-bit floating point value, that does not make the JS-based constant a Dart `double`

Anything that makes `KeyCode.ENTER` be precisely `double` is wrong. Its static type is `int` and the value must be an `int` (and maybe *also* a `double` in the JS number system).

**Comment by askeksa-google** [comment]
I have implemented a quick fix in https://dart-review.googlesource.com/c/sdk/+/98676 which simply looks at the value of every `DoubleConstant` child of a `ConstantExpression` somewhere beneath an `UnevaluatedConstant` left over from the first pass and converts in to `JavaScriptIntConstant` if it is integer-valued. It fixes the error seen for set elements and map keys, plus any other integer-seen-as-double problems that we might have missed.

Longer term, we should clean up the constant evaluator so that it generally looks at the values of constants to determine their int-ness. I see two ways forward here:
1. Handle types of constants completely inside the constant evaluator and remove `getType` from `Constant` (as far as I can see, there are only a few uses of `getType` scattered around, which are easily rewritten, and an upcoming CL - https://dart-review.googlesource.com/c/sdk/+/98677 - removes the dependency on `getType` from the `getStaticType` implementation on `ConstantExpression`, which makes this removal considerably less problematic). Clarify that `IntConstant` and `DoubleConstant` mean (in the JS world) a number _represented as_ int64 or double, respectively, and don't necessarily correspond to the type of the value ("the type" being an undefined property). Update the Kernel type checker to be parameterized by number semantics so it can treat these nodes properly (if we want to type check constants in the first place).
2. Add the type that @lrhn suggested to the core library and make it a subtype of both `double` and `int`. We could add a new `Constant` class, but this would actually be redundant (if we subscribe to the _represented as_ interpretation), since `DoubleConstant` could check whether it is integer-valued and have the return value from `getType` depend on that. This would require `TypeEnvironment` to be parameterized by number semantics. This seems like a more complex solution, and I don't see much benefit from it, unless it is for some reason very important to preserve `getType`.

**Comment by sigmundch** [comment]
Thanks so much Aske!

We have the equivalent of the JSInt type in the dart2js patch files, but to be honest I'm more inclined to go with a solution like (1).

**Comment by fishythefish** [comment]
Yes, I'd prefer (1) as well. I've found it cleanest to think of `IntConstant` as a constant value *represented* by an `int64` and `DoubleConstant` a constant value *represented* by a `double`. We can remove the `getType` API, but at the very least, we should allow the result to depend on the target backend as well as the actual value in question.

If the kernel type checker won't type check constants, then we can keep using an internal `Constant` type to tag `DoubleConstant`s whose Dart type is `int`. (Alternatively, we could test for `int`-ness on each use, but we might as well establish this property at construction.) We would continue not to fold any constant expressions which violate their Dart type contracts. (For example, attempting to bitshift a `DoubleConstant` which isn't tagged as `int` would fail.)

If we can rely on the kernel type checker to type check all constants, then we may be able to simplify the evaluator. We would no longer need the internal `Constant` since we could implement all the operations on all `DoubleConstant`s and rely on the type checker to ensure we're not overly permissive. This approach may be problematic when we see `dynamic` constants.

**Comment by askeksa-google** [comment]
I don't like the tagging, since it is redundant information. And it could easily lead to mistakes if we forget to tag some value that happens to evaluate to an integer. JavaScript Dart regards any integer-valued number as an integer, and I think the internal logic in the constant evaluator should reflect that.
