### ISSUE TITLE
CFE treats initializer lists as constant contexts

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#36533]
The program below is rejected by the analyzer as having an invalid constant (the invocation of `Bar`), but is accepted by the VM running bleeding edge, and in versions that I have tested going back to 2.1 (which suggests that this is not a new issue with the CFE constant evaluation).  Adding an explicit `const` to the invocation of `Bar` in the initializer list causes both implementations to accept the program.

My read of the spec in section 16.3.1 is that initializer lists are not covered as constant contexts, since elsewhere in the spec initializer lists and initializing expressions are treated separately.  

```dart
class Bar {
  const Bar();
}
class Foo {
  final Bar a;
  const Foo(int x) : a = Bar();
}

void main() {
  print(const Foo(1).a);
}
```

**Comment by leafpetersen** [comment]
Assigning to area-language first for verification that the letter of the spec matches its intent here.

**Comment by leafpetersen** [comment]
cc @lrhn @eernstg @munificent

**Comment by lrhn** [comment]
The intent is that a `const` is required here. The initializer list must contain potentially constant expressions, which for object creation means that it must be a constant invocation. It should not be a constant context, so the the `const` is required.

I believe the specification is correct. The "constant contexts" section does not mention initializer list entries, and they are only required to be potentially constant expressions.

**Comment by eernstg** [comment]
I believe the short reason would be that we cannot make an initializer list a constant context, because that would violate a property that we otherwise maintain: An expression which occurs in a constant context must be a constant expression (that's very easy to verify inductively by looking at the specification of constant contexts).

So if we want to get those `const` modifiers for free in an initializer list then we need to consider how to handle a non-constant expression in a constant context, and I suspect that this will be a subtle exercise. ;-)

**Comment by lrhn** [comment]
We could have introduce "potentially constant contexts" where we also automatically insert `const` for object creations, but we chose not to. By requiring `const` to be explicit, we leave the syntax open to perhaps some day allow `new` invocations to create `new` objects and `const` invocations to create `const` objects (the "auto" constness feature).

**Comment by askeksa-google** [comment]
A test for the various constant contexts (covering the known incorrect ones) is here: https://dart-review.googlesource.com/c/sdk/+/98854
