### ISSUE TITLE
dartfix CLI: support for including multiple fixes

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#36539]
Currently we can specify only one but often it's handy to bulk apply a few.

One thought would be to allow a comma-separated list in the `--include` option (linter does this FWIW).

For example:

```
dartfix  --include=use-spread-collections,prefer_for_elements_to_map_fromIterable <mycode>
```

/cc @danrubel @bwilkerson

**Comment by danrubel** [comment]
I [landed support for this](https://dart-review.googlesource.com/c/sdk/+/91780/4/pkg/dartfix/lib/src/options.dart#33) in early February. You can try it out by running dartfix from the SDK repo source, but I have not published the dartfix package since that time. 

Please reopen this if I'm missing something that needs to be tracked.

**Comment by pq** [comment]
Aha, it's a multi-option.  Perfect.  Thanks!
