### ISSUE TITLE
Confusing "Parameters can't override default values" lint when function type is used

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/sdk#36569]
* Dart SDK Version: `2.2.0`, and also whichever version is active on the Pub site
* MacOS, and also whichever OS the Pub site runs on (presumably Linux)
----

Getting an interesting warning in the analyzer.

I have a base class like the following:

```dart
class Router<T> {
  Route<T> addRoute(String method, {Iterable<T> middleware = const []});
}
```

And it's overridden in a class like this:

```dart
class Angel extends Router<Handler> {
  @override
  Route<Handler> addRoute(String method, {Iterable<Handler> middleware = const []});
}
```

I get the following analysis warning. It also shows up on the Pub site, removing 10 health points (happens in two subclasses):

```
Parameters can't override default values, this method overrides 'Router.addRoute' where 'middleware' has a different value.
```

The error persists even when the default value for `Angel.middleware` is removed. Not 100% sure how to fix this, as in the original case, the default value wasn't different from the parent class to begin with.

The same message is also present when I set the default value to `const <Handler>[]`.

Other information that might be relevant:
* `Handler` is a function type

----------------------------
Relevant source files/pages:
* https://pub.dartlang.org/packages/angel_framework/versions/2.0.0-rc.0#-analysis-tab-
* https://github.com/angel-dart/framework/blob/master/lib/src/core/server.dart#L151-L162
* https://github.com/angel-dart/route/blob/master/lib/src/router.dart#L71-L84

**Comment by eernstg** [comment]
The situation where `const []` is used as the default value for a parameter of type `T` which is a type variable with no bound calls for special treatment: A Dart constant must have a one-to-one correspondence with the source code, so we can't make it mean `const <T>[]` where `T` may be different from instance to instance of `Router`. 

So it actually means `const <Null>[]` (and when we add non-null types we will get a real bottom type `Never`, and then it'll be `const <Never>[]`).

And then you're overriding it with a `const <Handler>[]` in `Angel`, and that's not the same default value. But you could use an explicit `const <Null>[]` in `Angel`, which ought to eliminate the error.

**Comment by thosakwe** [comment]
Ah, I see. So if I change the signature of `Router.addRoute` to have `const <T>[]` as its default value, this would resolve itself?

Thanks.

**Comment by eernstg** [comment]
No, because `const <T>[]` is an error in itself (it would not evaluate to a single object, it would be a different one for each `T`, so it is not a constant expression).

**Comment by jakemac53** [comment]
Maybe not the most popular opinion, but I would pretty strongly advise against using default values in any capacity the way they exist today. Their only real value I am aware of is documentation (which you can partially replace with a doc comment).

Doing the `??=` pattern at the top of the method (or some other explicit null check) is the only way to ensure a non-null object, at least until we get non-null types.

It is really easy to get a null otherwise - if anybody wants to wrap a call to your function in another function which exposes the same optional parameter, it is very difficult for them to properly do that. They either have to duplicate the default (the best option, but it isn't forwards compatible) or do a null check themselves and make separate calls.

**Comment by thosakwe** [comment]
I wound up removing the default value from `Router.addRoute` entirely. Thanks @eernstg and @jakemac53

**Comment by jakemac53** [comment]
@eernstg I tried doing the explicit `const <Null>[]` but couldn't get that to work, https://dartpad.dartlang.org/4ddbf810a6517f934acc2822da5d0a71. I am getting this confusing error (at least in dartpad) `A value of type 'List<int> ()' can't be assigned to a variable of type 'List<int> ()'.`.

**Comment by eernstg** [comment]
@jakemac53 wrote:
> I would pretty strongly advise against using default values

Granted, we do not have a good way to abstract over default values, the only way that works faithfully (but not maintainably) is to write the same default value twice:

```dart
void f1([int x = 41]) {}
void f2([int y = 41]) => f1(y); // Remember to update default if `f1` is changed!
```

I usually argue (yes, this comes up now and then ;-) that it should be possible to denote the target default value, somehow. For example:

```dart
void f1([int x = 41]) {}
void f2([int y = f1.default[0]]) => f1(y);

void f3({int z = 14}) {}
void f4({int w = f3.default.z}) => f3(z: w);
```

This would "just do the right thing" because we want that specific default value and we get it, no matter whether the parameters are the same (we might want to forward a named parameter to a positional optional one or vice versa, they might just be positional optionals in a different order, or we want to use defaults for some other purpose like a global `const c = f1.default[0];`.

> `A value of type 'List<int> ()' can't be assigned to a variable of type 'List<int> ()'`

That sounds buggy, and it started between dart-sdk-2.0.0-dev.50.0 and dart-sdk-2.0.0-dev.60.0 for the analyzer and between dart-sdk-2.0.0-dev.63.0 and dart-sdk-2.0.0-dev.64.0 for the vm, so it might well be some shared code (whatever that is..).

I think that should be a new issue on both tools.

**Comment by eernstg** [comment]
@jakemac53 wrote:
> I would pretty strongly advise against using default values

Granted, we do not have a good way to abstract over default values, the only way that works faithfully (but not maintainably) is to write the same default value twice:

```dart
void f1([int x = 41]) {}
void f2([int y = 41]) => f1(y); // Remember to update default if `f1` is changed!
```

I usually argue (yes, this comes up now and then ;-) that it should be possible to denote the target default value, somehow. For example:

```dart
void f1([int x = 41]) {}
void f2([int y = f1.default[0]]) => f1(y);

void f3({int z = 14}) {}
void f4({int w = f3.default.z}) => f3(z: w);
```

This would "just do the right thing" because we want that specific default value and we get it, no matter whether the parameters are the same (we might want to forward a named parameter to a positional optional one or vice versa, they might just be positional optionals in a different order, or we want to use defaults for some other purpose like a global `const c = f1.default[0];`.

> `A value of type 'List<int> ()' can't be assigned to a variable of type 'List<int> ()'`

That sounds buggy, and it started between dart-sdk-2.0.0-dev.50.0 and dart-sdk-2.0.0-dev.60.0 for the analyzer and between dart-sdk-2.0.0-dev.63.0 and dart-sdk-2.0.0-dev.64.0 for the vm, so it might well be some shared code (whatever that is..).

I think that should be a new issue on both tools.

**Comment by eernstg** [comment]
Created https://github.com/dart-lang/sdk/issues/36577 for the vm (front end).
