### ISSUE TITLE
Some dart2js tests start failing when enabling constant-update-2018

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#36597]
https://ci.chromium.org/p/dart/builders/try/dart2js-unit-linux-x64-release-try/12098

**Comment by sigmundch** [comment]
https://dart-review.googlesource.com/c/sdk/+/99280 updates one test and deletes the other two (now no longer needed because they covered behavior under the old dart2js constant evaluator)

I did however discovered one CFE regression in this process. For now I'm commenting out that individual test case. I field https://github.com/dart-lang/sdk/issues/36609 to address it.
