### ISSUE TITLE
@mustCallSuper should guarantee that the method is called on any instance

### ISSUE THREAD

**Issue by dskloetg** [dart-lang/sdk#36657]
@mustCallSuper gives the illusion of a guarantee that the method is always called on any instance. But it doesn't actually always work. We should probably remove it until it guarantee, otherwise people might rely on bad assumptions.

For example, this is currently allowed:

```import 'package:meta/meta.dart';
class C {
  @mustCallSuper
  void a() {}
}
mixin M {
  void a() {}
}
class D extends C with M {}
```

But instances of D can call M.a() without C.a() being called, breaking the @mustCallSuper contract on C.a().

**Comment by srawlins** [comment]
This is a great bug because it has a lot of corners. It certainly highlights the complexity in checking that any class's implementation of a `mustCallSuper` method calls super.

In the example you give, where the mixin has no superclass constraint, we can report that the mixin's implementation cannot possibly call super, so it doesn't satisfy the contract.

In another example, the logic is harder:

```dart
abstract class B {
  @mustCallSuper
  void a();
}
class C implements B {
  @override
  void a() {}
}
mixin M on B {
  void a() {}
}
class D extends C with M {}
```

In this case, when reviewing the mixin M, we find no concrete overridden method `a`, so we don't produce a diagnostic that  `M.a` must call super. But we _should_ report that in the class D, `M.a` has been mixed into a class which _does_ have a concrete method `a` (`C.a`). However, at the time we're analyzing D, we may have lost implementation details of `M.a` (for example, if its declared in a different library which is now read as a summary file).

@bwilkerson suggested a solution offline: we could introduce a new rule, and report on `M.a` that you cannot override an abstract `mustCallSuper` method in a mixin. The logic is that, one cannot tell if `M.a` is a valid override of `B.a` until it has been ultimately mixed in. Mixing M into some classes would require `M.a` to call super, but not in others (based on the existence of a concrete super method).

When we add another class to the mix:

```dart
class E extends B with M {}
```

then it would be illegal for `M.a` to call super, because there is no concrete super method. Without Brian's new rule idea, one diagnostic would report that `M.a` needs to call super, and another would report that `M.a` cannot call super.

I'd like to investigate the feasibility of this new rule by implementing it and testing whether the Flutter codebase violates it, and whether it is violated internally at Google.

**Comment by srawlins** [comment]
Replaced by https://github.com/dart-lang/sdk/issues/48352.
