### ISSUE TITLE
Unsupported operation: ReceivePort.listen

### ISSUE THREAD

**Issue by jvanderen1** [dart-lang/sdk#36664]
# Issue

For some reason, I can't seem to use `ReceivePort` from my browser. After running:

`dart2js main.dart  -o main.dart.js`

And opening my `index.html` file locally, I get the following error from Chrome:

`Uncaught Unsupported operation: ReceivePort.listen`

# Sample Code

`main.dart`
```
// Dependencies
// ------------

// Libraries
import 'dart:isolate';

// Internal
// --------

void main() {
  ReceivePort receivePort = new ReceivePort();

  receivePort.listen((data) {
    receivePort.close();
  });
}
```

# Information

* Dart SDK Version (`dart --version`)

```
dart --version
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
```

* Whether you are using Windows, MacOSX, or Linux (if applicable)

macOS Mojave (10.14.4)

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Chrome and Safari

**Comment by sigmundch** [comment]
@jvanderen1 thanks for reaching out. This is basically not supported by design.

Long ago we supported the isolate API on the web. The implementation would manage isolates using web workers. We found that the isolate abstraction was not a great fit on the web and eventually decided to deprecate it and remove the support.

Starting in 2.0 (see [announcement](https://groups.google.com/a/dartlang.org/d/msg/announce/jh8uN5S0GE4/CQ4MF-OEBgAJ) and [changelog entry](https://github.com/dart-lang/sdk/blob/f3703c1bce74e9d515ba47ccdb435e31e99b99e7/CHANGELOG.md#200---2018-08-07)), the library implementation was changed to throw by default. It would have been nice to actually make it a compile-time error to import `dart:isolate`, but if I recall correctly, we made it a runtime error to make it easier to migrate existing code more gradually.

If you need support for background execution, our current recommendation is to use web workers via js-interop.
