### ISSUE TITLE
Define distribution system for native libraries in Pub and/or Flutter

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#36712]
**Update 2020-03-24**:

For Flutter plugins we can package binaries with with [Cocoapods or Gradle](https://flutter.dev/docs/development/platform-integration/c-interop).

For stand alone Dart packages there are two options:
1) Check in the C/C++ source and provide (preferably cross-platform) build instructions. This is how [our samples](https://github.com/dart-lang/samples/tree/master/ffi) work.
2) Check in pre-built binaries to pub for the supported platforms. For example the [tflite_native package](https://github.com/dart-lang/tflite_native/tree/master/lib/src/blobs).

We would like a better solution, but this is the way to do it for now.

======================================

(Not reviving https://github.com/dart-lang/pub/issues/39 because it contains little relevant context)

We need to define a distribution method in Pub, integrated with Flutter, which enables uses to create packages that depend on "native" libraries.

See [go/dart-ffi-flutter-distribution](http://goto.google.com/dart-ffi-flutter-distribution) for brainstorming on Flutter integration.

**Comment by MarvinHannott** [comment]
I have done FFI wrappers for libsodium and was disappointed when I realised that just putting the dynamic library into the package doesn't work. I mean, it works locally inside sodium and it passes all tests. But it doesn't work when sodium is a dependency of another package because as it seems the dll has to be inside the same package as the executable. That of course defeats the purpose of dependency management.

**Comment by sjindel-google** [comment]
@MarvinHannott  What platform/OS are you running on?

**Comment by MarvinHannott** [comment]
@sjindel-google Windows. But I strongly assume that the same should be true for Linux. As far as I understand, it is because of the way the path to a dynamic library gets resolved. The path has to be static and Dart libraries don't have any information about their own location on the disk like Node.js scripts do. And that's why the programm will look at the environment it gets executed in.

As for now I don't see any practical way to ship any kind of native dependencies. The user would have to manually manage the DLLs and nobody wants that.

**Comment by sjindel-google** [comment]
Most likely native dependencies will be managed by Flutter tools. On Android and iOS this means that native dependencies will be distributed via Gradle repos and Cocoa pods. The story for desktop platforms is till unclear though.

**Comment by MarvinHannott** [comment]
@sjindel-google What I wouldn't like were something like node-gyp which only causes problems and is complicated. Ideally Dart libraries could be shipped with pre-compiled dynamic libraries for various platforms so that dependencies don't have to be build on the target device.

**Comment by sjindel-google** [comment]
Solved for Flutter via https://github.com/flutter/flutter/issues/33227

We don't have a story for packaging native code inside Dart packages independently of Flutter yet, and we're not prioritizing it this year.

/cc @mit-mit

**Comment by dcharkes** [comment]
We are working towards a solution, this is being tracked in:

* https://github.com/dart-lang/sdk/issues/50565
