### ISSUE TITLE
[ffi] Support passing and returning composites (structs) by value.

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#36730]
I wanted to writing bindings for libclang (so that I can generate bindings from C/C++ header files automatically), but I discovered that libclang API uses structs passed and returned by value. 

```
typedef struct {
  unsigned int_data[4];
  void *ptr_data;
} CXToken;

typedef struct {
  const void *data;
  unsigned private_flags;
} CXString;

CINDEX_LINKAGE CXString clang_getTokenSpelling(CXTranslationUnit, CXToken);
```

So I can't really bind to this API. There are some interesting design problems to resolve: e.g. when a structure is returned by value who manages the memory of that struct and how do we prevent people from making a mistake of passing address of that struct to some other method.

**Comment by sjindel-google** [comment]
You could bind to the API btw, with some very simple C wrappers.

**Comment by dcharkes** [comment]
Why did we move this back to Flutter MVP?

**Comment by dcharkes** [comment]
We'll do the api change in MVP #37229, but not the by-value-passing.

**Comment by mannprerak2** [comment]
I noticed something strange
I created a header like this
```c
struct Data
{
    int i;
};

void printData(struct Data);
struct Data createData(int);
```

But If I write bindings like this (using Pointer<Data> instead of passing struct by value)
```dart
typedef printData_func = ffi.Void Function(ffi.Pointer<Data>);
typedef PrintData = void Function(ffi.Pointer<Data>);

typedef create_struct_func = ffi.Pointer<Data> Function(ffi.Int32);
typedef CreateStruct = ffi.Pointer<Data> Function(int);
```
The bindings are working perfectly (tested on ubuntu 19)
Complete code can be found [here](https://github.com/mannprerak2/exp-ffi-dart/tree/master/function_struct_by_value)

Can someone shed some light into this, and
If there are any potential memory leak issues involved?

**Comment by dcharkes** [comment]
The `Data` struct with a single `int` field is treated as a single `int` field in the Linux ABI.

You're storing the _value_ of the int field as the address of the `Pointer`, most likely `ptr.address` will give you the value of the int field.

This will not work for structs that are larger than the architecture size (larger than 8 bytes on 64 bit architectures), and this will not work for structs containing floats.

**Comment by marcofeltmann** [comment]
Is there any documentation how this can be working now?

I'm having a Go library that returns a tuple (double, double) like so:
```
//export provideCurrentPosition
func provideCurrentPosition() (float64, float64) {
…
}
```


The `go build -buildmode c-shared` creates this header file for it:
```
/* Return type for provideCurrentPosition */
struct provideCurrentPosition_return {
        GoFloat64 r0;
        GoFloat64 r1;
};

extern struct provideCurrentPosition_return provideCurrentPosition();
```

I cannot modify this behavior (in fact I could since it is FOSS…) and I'm not very interested in cluttering the Go library in favor for the C interop of dart.

**Comment by dcharkes** [comment]
@marcofeltmann this is currently only available on the master branch (which you'll have to build manually) or on the dev channel (starting from [2.12.0-150.0.dev](https://github.com/dart-lang/sdk/commit/f166571c7bc446c88d5b0882435ca31064cddf91)).

Next beta and/or stable releases will include this feature.

**Comment by TimWhiting** [comment]
Hi, I've been waiting for this feature to wrap some libraries that I've been interested in. It's looking good so far. However, one issue that I'm running into is that the API returns structs by value, but always takes in those same structs by reference. Is there an easy way to create a pointer and then copy the bytes from a NativeType to the ref of the pointer? Or can I get a pointer to the NativeType itself?

```dart
Pointer<T> copyToPointer<T extends NativeType>(T input){
  final p = allocate<T>();
  p.ref = input;
// ^ error here, setter ref is not defined
  return p;
}
```

I know I can move the fields to the pointer one by one, but this is a huge library, and I don't want to have to do it for every type individually. (I'm using ffigen to generate the bindings, and it is currently over 32000 lines, with more headers that I'll probably eventually need to generate bindings for as well). If this isn't something that can/should be done in the SDK, I guess I can try to submit a pull request to the ffigen repo with some setting to automatically generate functions to create a pointer and copy the fields for each of the structs that are generated.

**Comment by dcharkes** [comment]
> However, one issue that I'm running into is that the API I'm wrapping returns structs by value, but always takes in those same structs by reference.

@TimWhiting It would be quite curious if the C API would not be consistent in returning and passing structs by value. If that API returns structs by value, but expects them to be passed in by pointer, it puts the burden of resource management on the user of that API. Is the API public? If it turns out to be a common pattern we might want to try to make the use case simpler.

**Comment by TimWhiting** [comment]
Yes the API is public: 
Here is the C client [library](https://github.com/ros2/rcl/tree/master/rcl) and [docs](http://docs.ros2.org/latest/api/rcl/index.html)
And the C++ API [docs](http://docs.ros2.org/latest/api/rclcpp/index.html)

As an example this [c++ file](https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/node_options.cpp)
contains the following
```cpp
// Creating a pointer
node_options_.reset(new rcl_node_options_t);
// Assigning a return by value result to the underlying memory of the pointer
*node_options_ = rcl_node_get_default_options();
```

Also this [file](https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/init_options.cpp):
```cpp
InitOptions::InitOptions(const rcl_init_options_t & init_options)
: init_options_(new rcl_init_options_t)
{
// assigning a return by value to a pointer
  *init_options_ = rcl_get_zero_initialized_init_options();
  rcl_ret_t ret = rcl_init_options_copy(&init_options, init_options_.get());
  if (RCL_RET_OK != ret) {
    rclcpp::exceptions::throw_from_rcl_error(ret, "failed to copy rcl init options");
  }
}
```

I'm not sure how many structs I would need to do this with, but it's common enough for me to wonder how prevalent.
It's a C library that is designed with the intent that other languages should be using it. I don't know why they made the design decision they did, but I assume they knew that most languages would require a c wrapper that gives the language a pointer to the value rather than the actual value and thus parameters tend to be pointers but not return values? For the most part these are long-lived objects. 

I can submit a new issue for this, and I'll try to quantify better how common this pattern is at least in this library.
