### ISSUE TITLE
Warning: Tried to initialize from a previous compilation 

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#36759]
```
Compiler message:
Warning: Tried to initialize from a previous compilation (.../testfile.dill), but the file was not self-contained. This might be a bug.
```

On: `Dart VM version: 2.3.0-dev.0.3.flutter-1f1592edce (Tue Apr 23 00:32:54 2019 +0000) on "linux_x64"`

[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3119116/initialize_from.dill.gz)

**Comment by jensjoha** [comment]
Thank you for the report.

This is caused by the previous compilation being compiled on the basis of an older version of the sdk where the new version (the one now included in flutter) has changed (specifically in https://github.com/flutter/engine/commit/3e47b4bb39bb4993f03a278ea7b1c11ee6459b06 the getter "left" on class "Rect" was removed and became a field instead.)

This means that the old compilation tries to reference something that no longer exists. This is detected, and we're saying that we cannot initialize from it. This is perfectly fine. Ideally we wouldn't even try to initialize from it, because we would know that the sdk versions doesn't match up, but we cannot do that (yet). #36032 tracks that.
