### ISSUE TITLE
Does "part of" syntax expose the local path in error log?

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#36760]
The library [`encrypt`](https://github.com/leocavalcante/encrypt/blob/master/lib/src/algorithms/rsa.dart) we used is to use `part of` syntax.

For  example,
```
#2  BaseAsymmetricBlockCipher.process (package:pointycastle/src/impl/base_asymmetric_block_cipher.dart:15:15)
#3  RSA.encrypt (file:///Users/foo/.pub-cache/hosted/pub.dartlang.org/encrypt-2.2.0/lib/src/algorithms/rsa.dart:27:30) <-- this
#4  Encrypter.encrypt (file:///Users/foo/.pub-cache/hosted/pub.dartlang.org/encrypt-2.2.0/lib/src/encrypter.dart:11:17) <-- this
```

Is it possible to hide the local path if we publish our library on production?

**Comment by lrhn** [comment]
Am I correct that you are using `part "package:encrypt/src/algorithms/rsa.dart";` in the pointycastle package?

(Unless you are the author of the `encrypt` package, I cannot recommend this. We do not consider the separation into part files a public API, so if the part file is renamed in the future, or embedded in the library file, or the name of the library changes, or the `part of` starts using a relative path instead of a library name, then your code will stop working)

Even with this uncommon usage, there is no reason the part file should be remember a `file:` URI instead of a `package:` URI.
The correct URIs would be `package:pointycastle/src/algorithms/rsa.dart` and `package:pointycastle/src/algorithms/encrypter.dart`, and we should keep those if that is how the import is written.

(Tentatively marking as a front-end issue).

**Comment by leocavalcante** [comment]
@jumperchen 
How are you using the `encrypt` package?
You are importing like this:
```dart
import 'package:encrypt/encrypt.dart';
```
Or like this:
```dart
part "package:encrypt/src/algorithms/rsa.dart";
```
?

**Comment by jumperchen** [comment]
We use this way 
    import 'package:encrypt/encrypt.dart';

**Comment by jensjoha** [comment]
Before 58882ffdd49afdfb53c7be15361340bb64760fe4 there was no real / the VM didn't include "import uris" for parts. With that commit, though, the VM does use the import uri for the part, and that will be used in stacktraces.

E.g. in Dart 2.2 one might get something like this:
```
$ dart issue_36760/main.dart
Unhandled exception:
hello from part
#0      foo (file:///usr/local/whatever/path/part1.dart:4:3)
#1      main (package:foo/main.dart:4:3)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

whereas in Dart 2.3 (not released yet) you will get something like
```
$ dart issue_36760/main.dart
issue_36760/main.dart:1: Warning: Interpreting this as package URI, 'package:foo/main.dart'.
Unhandled exception:
hello from part
#0      foo (package:foo/part1.dart:4:3)
#1      main (package:foo/main.dart:4:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

Scripts that are not part of packages will still be reported by their file uri though.

Please also notice that the VM still knows about the file uri, and - for instance - the script snapshot also contains the file uri (from which it can easily be read!).
