### ISSUE TITLE
Analyzer missing error for 'this' access in a constructor assert

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36779]
After some refactoring I ended up with code like this:

```dart
class Danny {
  int length;
  Danny(String str)
      : length = str.length,
        assert(length != null);
}
```

I forgot to update the `assert` to check `str`, and although this code gives no analysis-time warnings, it fails to run with this compile error:

```
Compiler message:

lib/src/painter.dart:277:16: Error: Can't access 'this' in a field initializer to read 'length'.
        assert(length != null);
               ^^^^^^
```

I think there could/should be an analysis error for this if it's not valid.

**Comment by devoncarew** [comment]
@stereotype441, is this a an issue in the analyzer (for not warning) or in the CFE (for the runtime error)?

**Comment by stereotype441** [comment]
I believe the error is correct, and the bug is in the analyzer.

**Comment by lrhn** [comment]
The bug is in the analyzer.
 The `length` in the assert refers to the instance field, making it equivalent to `this.length`, and you cannot access `this` (or instance fields) in initializer lists.

The places where you can access instance methods, or `this` at all, are: 
* Instance member bodies.
* Constructor bodies.
(The `this` in initializer lists or initializing formals are simply syntactic forms, they do not refer to the object).

If `this` occurs as an expression anywhere else, it is an error. If an implicit access to an instance field occurs anywhere else, it is an error.
(The `C(this.length) : assert(length != 0);` constructor assert does not reference the instance field, it references a new final variable with the same name introduced by the initilaizing formal, no `this` involved)

**Comment by lrhn** [comment]
Appears to be fixed.
