### ISSUE TITLE
Bring Flutter's TimeOfDay class into Dart SDK

### ISSUE THREAD

**Issue by gazialankus** [dart-lang/sdk#36786]
Flutter has the [TimeOfDay](https://docs.flutter.io/flutter/material/TimeOfDay-class.html) class, which is a pretty generic, non UI-specific class that represents the time of day independent of date. It would be great to have it in the Dart SDK so that we can use it in non-Flutter Dart code. 

There was already an issue report in Flutter repo, asking for this class to be made available outside the material package. https://github.com/flutter/flutter/issues/29147

**Comment by devoncarew** [comment]
cc @lrhn

**Comment by lrhn** [comment]
Not sure we want another, more specific, time-related class in the platform libraries. 
We already have `DateTime` for dates/timestamps and `Interval` for a count of hours/minutes/seconds. You should be able to use `Interval` to store a time-in-day as the time since midnight. The only issue with `Interval` is that it isn't capped at 24 hours.

Even if we added such a class, it would likely not be exactly the Flutter `TimeOfDay` design.
We might have seconds, or even milliseconds, probably no const constructor without validation (`TimeOfDay(hour: -5, minutes: 900)`?), and no required named parameters for now.
The Flutter class seems designed for a specific set of (Flutter-related) use-cases, but it is not as general as something should be to be included in the platform libraries. It would be too easy to come up with another use-case that isn't covered, and then we are stuck with an insufficient class.

**Comment by gazialankus** [comment]
Ok, thank you so much for your time, I understand the can of worms that this is likely to open. We will also want it to play nicely with the existing classes, etc. 

I had not considered `Interval`, I think that will be enough for my use case. Thanks.

**Comment by AristideVB** [comment]
What about having a `TimeOnly` like in .NET ? 

https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/
