### ISSUE TITLE
CFE seems to omit the scope that enables generic function types to have F-bounds

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#36870]
Dart SDK Version: 2.3.0-dev.0.5
OS: Windows 10 64 bit

The following source example declares a typedef `AAlias` with `Function` in the right part:

``` dart
class A<X extends A<X>> {}
typedef AAlias = Function<X extends A<X>> ();
main() { print("OK"); }
```
Dart throws a compile time error here whereas analyzer passes without any errors or warnings. Sample output is:
> $> dartanalyzer test.dart
> $> dart test.dart
> test.dart:2:39: Error: Type 'X' not found.
> typedef AAlias = Function<X extends A<X>> ();
> $>

Seems like analyzer should throw an error here too.

**Comment by eernstg** [comment]
This is actually an issue with the front end (and the error is still reported with `dart` from 762113758de67ea48310f87161f4f31b33fd9551):

It is not an error to use `X` in the bound `A<X>`, because any generic function type (including one that occurs on the right hand side of a `typedef`) should have a scope where its type parameters are introduced, such that the type parameters can be used in F-bounds.

Changed the labels and issue title to reflect this.

**Comment by eernstg** [comment]
Just checked, the issue arises independently of the type alias:

```dart
class A<X extends A<X>> {}
Function<X extends A<X>>() f = throw 1; // Error in CFE: Type `X` not found.
main() {}
```

So, apparently, function types never introduce the scope where `X` can be found when checking a bound like `A<X>`, or it does get created but it isn't made the current scope of the bounds.
