### ISSUE TITLE
LSP support for textDocument/implementation

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36896]
Would it be possible to add support for finding the implementations of a class/method to the analyzer `--lsp` mode?

This is one of the missing features I miss the most since I switched over from @natebosch dart_language_server wrapper to the analyzer LSP mode.

For reference, here is the implementation @natebosch had:
https://github.com/natebosch/dart_language_server/blob/d830e6c6373a6dfd62ce896ad73c989dee88cd21/lib/src/shim.dart#L247-L266

/cc @DanTup

**Comment by DanTup** [comment]
Yep, I'll take a look. The implementation linked above is quite different to what we do in VS Code:

https://github.com/Dart-Code/Dart-Code/blob/30c95d10fc6c02531e219edda264009c632253bc/src/providers/dart_implementation_provider.ts#L19

For ex. we only show results that descend from the item you invoked it on (and don't include itself). I'm not sure which is most correct. If you had A -> B -> C and invoked it on B, would you expect both A and C to show up?

**Comment by natebosch** [comment]
> If you had A -> B -> C and invoked it on B, would you expect both A and C to show up?

I use it frequently to get to A in that scenario.

**Comment by DanTup** [comment]
> I use it frequently to get to A in that scenario.

Since this server is potentially used by many IDEs/users, I think it's important we implement what's expected by the user/spec though (there are other commands to navigate to definitions, etc.). For example if there's only one implementation, Go to Implementation could jump directly to it (and if there are zero, do nothing) - but if we always include itself (plus others) this will never happen and the user will always be forced to pick from a list (which isn't as seamless).

My question was more about whether I'd misunderstood the whether implementations could ever be on the other side (eg. if Dart Code's implementation was wrong). I did just try it in TypeScript, and it *seemed* to behave as Dart-Code does, but it was a trivial case.

If Dart Code's behaviour is more accurate, I really think we should do that - and if Vim wants to show both it could combine multiple requests (or we could provide a custom command if the LSP ones don't suit). That way other editors wouldn't end up with confusing Go-to-Implementation functionality?

**Comment by natebosch** [comment]
> I did just try it in TypeScript, and it seemed to behave as Dart-Code does, but it was a trivial case.

If that's the case I'm in favor of matching behavior.

>  if Vim wants to show both it could combine multiple requests

I'd be happy to if I knew what request to make. With other LSP servers, how would you make this jump?

```dart
class B implements A {
  @override
  void doStuff() { // I am here.
    ...
  }
}

class A {
  void doStuff() { // I want to get here
    ...
  }
}
```

**Comment by DanTup** [comment]
Good question! Implementation doesn't feel like the right thing here, since A's implementation isn't really applicable to B (since you're just implementing its interface, not sharing any implementation). The closest I could make in TypeScript is this:

```ts
class A {
	protected doStuff(): void {
		console.log("A");
	}
}

class B extends A {
	protected doStuff(): void {
		console.log("B");
	}
}
```

Go to Implementation doesn't work to get from `B.doStuff()` to `A.doStuff()` (though as you'd expect, the other way around does work). However, for TypeScript `Find References` on `B.doStuff()` *does* include it in the results:

<img width="904" alt="Screenshot 2019-05-15 at 8 14 13 am" src="https://user-images.githubusercontent.com/1078012/57755706-73934680-76e9-11e9-986b-5635238493d8.png">

And the same is true for the doing it on `A.doStuff()`, you get both.

In Dart, this isn't true - "Find References" on either `doStuff()`'s doesn't return the other (only itself).

@bwilkerson @scheglov do you have any thoughts on this? Are you able to navigate as in Nate's example in IntelliJ? If so, which command does it fall under?

**Comment by DanTup** [comment]
(The impl I landed matches TS but doesn't support Nate's use case above - how to do that is still open (and may be worth its own issue - it's not specific to LSP since I don't think we can do this in non-LSP VS Code today either)

**Comment by bwilkerson** [comment]
Yes, IntelliJ has support for this. It subscribes to `analysis.implements` and `analysis.overrides`, which together provide both forward and backward links in the inheritance hierarchy.

**Comment by scheglov** [comment]
See also `search.getTypeHierarchy`, which might be invoked on a class member, and then it return references to member declarations in super- and subclasses.

For example:
```dart
class A {
  void foo() {}
}

class B implements A {
  @override
  void foo() {}
}

class C implements B {
  @override
  void foo() {}
}
```

Requesting
```json
{"id":"256","method":"search.getTypeHierarchy","params":{"file":"/Users/scheglov/dart/test/bin/test.dart","offset":71,"superOnly":false},"clientRequestTime":1557926472112}
```

Results in:

https://jsoneditoronline.org/?id=4a0b9458edf2431681dc8318d06b4f0c

**Comment by DanTup** [comment]
Thanks - though I mean - how is it exposed in IntelliJ? What is the feature/navigation operation called there?

`getTypeHierarchy` is what we're using here, but I'm filtering it in the "Go to Implementation" provider in VS Code (and now in the `textDocument/implementation` handler in LSP) because it doesn't seem to belong in "Go to Implementation" (and also means it would never immediately jump to an implementation - which is nice when there is only one - making you always pick from a list).

I'm trying to figure out if there's a suitable place to include this in the existing VS Code/LSP features. For TypeScript it seems to show up in Find References.. if we were to do the same, would it make sense to add to the servers existing `findElementReferences` or supplement it within the LSP handler + VS Code's provider?).

**Comment by bwilkerson** [comment]
In IntelliJ it shows up as icons in the left-hand gutter (one for items lower in the hierarchy, one for items higher). If there's more than one item, the icon opens a menu to select the one you're interested in; if there's only one then it just navigates immediately.

**Comment by DanTup** [comment]
Aha, got it:

<img width="309" alt="Screenshot 2019-05-15 at 6 09 49 pm" src="https://user-images.githubusercontent.com/1078012/57794909-a74b8c00-773c-11e9-99c3-5bf66d423be2.png">

As it turns out, I already implemented this in VS Code. There's no native feature for it and we called it "Go to Super" (https://github.com/Dart-Code/Dart-Code/issues/505).

The way we implemented it was to use the Outline info to find the method the cursor is in, then send that to getTypeHierarchy (with superOnly: true) and it will give us the super method.

To move VS Code to LSP, we'd need some way to do this - either by exposing the outline data + getTypeHierarchy in some way through the LSP protocol, or by adding a specific custom request for it. I think the latter makes most sense (and would be more easily usable by other editors like Vim). @natebosch what do you think?

**Comment by DanTup** [comment]
In what seems like a huge coincidence, https://github.com/Dart-Code/Dart-Code/issues/1712 was just opened requested the feature we just discussed above 😁

**Comment by DanTup** [comment]
And here's the VS Code issue I apparently opened at the time. Feel free to 👍 ... adding to VS Code and adding to LSP are usually linked :-)

https://github.com/microsoft/vscode/issues/47126
