### ISSUE TITLE
Type narrowing is lost when re-assigning to variable

### ISSUE THREAD

**Issue by LinusU** [dart-lang/sdk#36922]
* `Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"`

I have a state machine modeled as several classes extending from a common abstract class. Each class has methods for transitioning to a different state, making sure that I can only do valid state transitions.

I also have a function, that transitions this state machine thru a few states, and acts on the data in between the different states. This is where I have some problems. Using type narrowing I can easily narrow my `state` type to a particular state. However, when trying to transition into a new state, the type narrowing is lost and the variable is now the abstract base class.

Here is a minimal test case that shows the issue:

```dart
abstract class State {}

class A extends State {
  B b() => B();
}

class B extends State {
  A a() => A();
}

void main() {
  State state;
  
  state = A();
  
  if (state is A) {
    // Here state is correctly typed as A

    // But when adding this line, `state` is suddenly the abstract base class, and
    // the compiler won't let me call `.b()` on it. I expected the right hand `state`
    // here to be `A`, and the left hand `state` to be `B`.
    state = state.b();

    // Here I expected `state` to be typed as `B` since that will always be the case.
    state = state.a();

    // Basically, I should be able to jump between `A` and `B` any number of times.
    state = state.b();
    state = state.a();
  }
}
```

I'd be happy to provide any additional information! ☺️

**Comment by kaneisace** [comment]
You have defined variable `state` as type `State`, so it will only ever appear to be this type - never any subtype. As this (abstract) class has no methods, the compiler will complain when you write code that attempts to call them.

Change your variable definition to `dynamic state;` - this way, you are telling the compiler to "forget" the type at compilation time, and simply try to call methods etc. as it encounters them at runtime.

**Comment by lrhn** [comment]
Your comment says `// Here state is correctly typed as A`. That's actually not correct. The current type promotion is very simple, it never promotes a variable which is assigned in the code which is guarded by the test. The static type of `state` is still `State` after the `if (state is A)` check because `state` is assigned inside the `if` branch.
The type promotion is also never triggered by assignment, only by `is` checks.
We plan to have a better type promotion when we introduce non-null types into the type system. I hope it will be able to handle some assignments too, in some capacity, but I'll not promise that it will work for something as intricate as your code here.

So, currently this is working as intended. For the [improved type promotion](https://github.com/dart-lang/language/issues/81), there isn't much to read yet.

**Comment by LinusU** [comment]
Will follow that issue then, would love it if this would become possible in the future 👍
