### ISSUE TITLE
Language suggestion: shorter function declaration with only one parameter and one line expression

### ISSUE THREAD

**Issue by xareelee** [dart-lang/sdk#36941]
It's just a suggestion for Dart lang, not a bug report. I did not find a way to publish my suggestion, so I file this here.

[Arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) are good, but it can be shorter when there is only one parameter by using underscore `_`.

```dart
function greeting(name) {
  print("Hello ${name}! How old are you, ${name}?");
}

// It can be shorter using a shorthand syntax.
var foo = (name) => print("Hello ${name}! How old are you, ${name}?");

greeting('John');   // Hello John! How old are you, John?
```

It can be shorter using underscore `_` without `(_) =>` syntax. 

```dart
var foo = print("Hello ${_}! How old are you, ${_}?");
// same as 
var foo = (_) => print("Hello ${_}! How old are you, ${_}?");
```

When an expression using underscore `_`, it returns a function which will take only one parameter and pass it to the express. You can use the same parameter in the expression as many times as you want. It might be useful for functional programming.

```dart
[1, 2, 3, 4].map((_ + 1) * _);   // [2, 6, 12, 20]
// same as 
[1, 2, 3, 4].map((_) => (_ + 10) * _);  
```

**Comment by lrhn** [comment]
This suggestion is reminiscent of https://github.com/dart-lang/language/issues/265 (and a number of other language requests in the language repository). So, it is something we are aware of.

One issue with the proposed syntax is that it's not clear where to insert the implicit `(_) =>`.
In `[1, 2, 3, 4].map((_ + 1) * _)`, it is possible to insert it in many places, including:
* `[1, 2, 3, 4].map((_) => (_ + 1) * _)`
* `[1, 2, 3, 4].map(((_) => _ + 1) * (_) => _)`
* `[1, 2, 3, 4].map((((_) => _) + 1) * (_) => _)`
* `(_) => [1, 2, 3, 4].map((_ + 1) * _)`

Most of these can be rejected from the type, but it's dangerous to have a syntax where you can't parse until you have typed the syntax, because typing usually depends on the parsing.
We need to insert an implicit delimiter, and without any guidance, there is a lot of places where it can be inserted. That's why it's a good idea to require the user to tell us where it goes.

**Comment by xareelee** [comment]
@lrhn, Thanks for your reply!
