### ISSUE TITLE
dart::CidRange marked ZoneAllocated, but used with MallocGrowableArray

### ISSUE THREAD

**Issue by mdempsky** [dart-lang/sdk#36955]
Since [dart::Malloc::Realloc uses realloc](https://github.com/dart-lang/sdk/blob/f440f77dd3c0f1d8cb8da66ea92317ffd4c15134/runtime/platform/growable_array.h#L209) to reallocate and move constructed objects around, I thought to add a static_assert to check that T satisfies std::is_trivially_copyable.

This exposed that [dart::CidRange is marked ZoneAllocated](https://github.com/dart-lang/sdk/blob/f440f77dd3c0f1d8cb8da66ea92317ffd4c15134/runtime/vm/compiler/backend/il.h#L163), but is used with [MallocGrowableArray](https://github.com/dart-lang/sdk/blob/f440f77dd3c0f1d8cb8da66ea92317ffd4c15134/runtime/vm/compiler/backend/il.h#L191). I.e., it's marked ZoneAllocated, but then it's allocated in some cases on the C/C++ heap.

This seems unusual to me and at least counter to ZoneAllocated's intention with disallowing normal new/delete and the copy/assignment operators, but I can't see anything immediately wrong with it.

Is there anything that can/should be done here? Maybe just replace MallocGrowableArray<CidRange> with ZoneGrowableArray<CidRange>?

/cc @mkustermann @crelier @mraleph

**Comment by mraleph** [comment]
I think this is completely intentional. At some point `ZoneAllocated` had an assertion in destructor preventing us from using `ZoneAllocated` classes from being used as normal values (e.g. allocating instances of those classes on the stack). However we removed it - because it was making code harder to write (e.g. you were forced to create a value class `CidRange` and then have another class `ZoneCidRange` which would contain `CidRange` inside). 

I view inheriting from `ZoneAllocated` just a convenient way to provide default implementation of `operator new` which allocates in the zone - rather than a guarantee that instance of this class must always reside in the zone.
