### ISSUE TITLE
No error for any member accesses on Null

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#36956]
```
Null x;
x.foo;
```

CFE reports an error, analyzer does not.

**Comment by lrhn** [comment]
That was never a correct behavior, so it is definitely an analyzer bug. 
At some point the `null` expression had type bottom, and `null.foo` might have been acceptable at that point (the spec didn't say either way), but `Null x; x.foo;` was never valid.

**Comment by MichaelRFairhurst** [comment]
What about operators?

CFE does not accept

```
~null;
null + null;
null - null;
// etc
```

and analyzer does.

language_2/null_no_such_method_test seems to indicate it is supposed to be accepted. However, CFE does not accept it, so perhaps we should consider it...effectively banned?

**Comment by MichaelRFairhurst** [comment]
Looking through the spec, it seems that the CFE is doing the right thing here.

```
Let $T$ be the static type of $e$.                                               
It is a compile-time error if $T$ does not have an accessible                    
(\ref{privacy})                                                                  
instance member named $m$, unless either:                                        
\begin{itemize}                                                                  
\item $T$ is \DYNAMIC{}.                                                         
Or                                                                               
\item $T$ is \FUNCTION{} and $m$ is \CALL.
```

**Comment by lrhn** [comment]
Yes, the specification changed for Dart 2.0.
In Dart 1, the expression `null` had type bottom. In Dart 2, it has type `Null`.

So, in Dart 2, `-null` is invalid and in Dart 1 it would have been valid (and a guaranteed run-time error).

The design in Dart 1 was because `Null` was not a subtype of other types, so the least upper bound of `test ? 1 : null` would be `Object`, not `int`. In Dart 2, `Null` is a subtype (but still not a subclass) of `int`.
Nothing really changed for users, it was just a refactoring of the specification, but there was no longer any need for `null` to have type bottom. Since it was error prone anyway, and the introduction of type inference made it possible to propagate the bottom type, we changed `null` to have type `Null` (and then realized we had to tweak inference to not propagate the bottom type anyway, since `throw x` still has type bottom).

In any case: `null.foo` is an error in Dart 2. `Null x; x.foo;` was *always* an error, even in Dart 1.
This goes for all member accesses that are not on the `Null` interface (the same members as on `Object`), whether operators or not.
