### ISSUE TITLE
Dart does not throw compile time error when wrong type is assigned to a variable using the if null operator (??)

### ISSUE THREAD

**Issue by gtrochimiuk** [dart-lang/sdk#36964]
Dart VM version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "macos_x64"

Dart does not throw compile time error when wrong type is assigned to a variable if you use the "if null" operator. Following example compiles without error and then throws a runtime error:
```
class ExampleClass {}

void main() {
  ExampleClass example = 'string' ?? ExampleClass();
}
```

**Comment by lrhn** [comment]
I believe this is a classical example of the way our unification interacts with implicit downcasts.

The static type of `'string' ?? ExampleClass()` is the least supertype of `String` and `ExampleType`, which is `Object`. Since `Object` is a supertype of `ExampleClass`, the assignment is allowed statically as an implicit downcast, and it fails at run-time.

With non-nullable types, the `'string' ?? ...` will likely become either a warning or an error (the expression cannot be null, so the `??` is irrelevant), and when implicit downcasts are disallowed, that particular error will be caught as well.

Until then, the analyzer option [implicit-casts](https://dart.dev/guides/language/analysis-options) can warn you about all downcasts, which will catch cases like this ... and a lot of other downcasts which are probably perfectly fine.

**Comment by gtrochimiuk** [comment]
I see, thank you for the explanation.

**Comment by natebosch** [comment]
Closing since NNBD will also disable implicit casts and there are no specific actions to take on this issue.

https://github.com/dart-lang/language/issues/192
