### ISSUE TITLE
[Feature Request] Add containsAny to the Set API.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/sdk#36985]
Right now the Set API includes a [`containsAll`](https://github.com/dart-lang/sdk/blob/86c71659697b50c9921c2f3ac520ec867b7c14cc/sdk/lib/collection/set.dart#L90) method. It would be nice to have a similar `containsAny` method.

Example:
```dart
final foo = <String>{'a', 'b', 'c'};

foo.containsAny({'a', 'b'}); // Returns true.
foo.containsAny({'c', 'd'}); // Returns true.
foo.containsAny({'d', 'e'}); // Returns false.
```

I know the same can be accomplished with `foo.intersection({'c', 'd'}).isNotEmpty`, or `foo.any({'c', 'd'}.contains)`, but `containsAny` would be a lot cleaner.

**Comment by natebosch** [comment]
This seems like it could be a good addition to `package:collection` once we have extension methods. I don't think we'll want to put this on the class itself since I'm sure there are `implements Set` that would be broken.

**Comment by lrhn** [comment]
If you have a set `s1` and an iterable `i2`, then `s1.containsAny(i2)` can also be computed as `i2.any(s1.contains)`.

We could add the member, but it is not a high priortity. Since it would break all existing implementations of `Set` to add a new member, we most likely won't do that unless something makes the benefit outweigh the costs.

**Comment by johnsonmh** [comment]
Sounds fair, not worth breaking the API for. I agree with @natebosch , it seems like a good candidate for an extension method in `package:collection`.
