### ISSUE TITLE
Dart/Flutter Language inheritance of optional params and static class fields issues.

### ISSUE THREAD

**Issue by wyattbiker** [dart-lang/sdk#36987]
**(I cross posted this to flutter sdk)**

1. Shouldn't the subclass constructor, automatically know the optional fields of it's parent?
2. Shouldn't an instance of a subclass have access to static of it's parent?

If I create a subclass of a Flutter Widget, I would need to list all the optional parameters in the subclass constructor? There could be tens of these, including actions (e.g. onTap). This means if I change a widget to a child widget, I have to initialize the complete optionals as instance variables. I know this can be fixed with `dart:mirrors` but its not supported with Flutter. Is there some other way of coding this?

Below is a very simple example where `width` is not accessible as an optional parameter by child constructor.

Also, static `height` is not accessible by the child class constructor.

```dart
// Parent widget
class PWidget {
  String color = 'red';
  int width;
  static int height = 5;
  PWidget(this.color, {this.width});
}

// Child Widget
class CWidget extends PWidget {
  @override
  String color = 'green';
  CWidget(String color) : color = color, super(color);
}

main() {
  // Width is only define in parent so cannot be accessed 
  CWidget c = CWidget('blue', width: 10);
  // Static height cannot be accessed.
  print(CWidget.height);
}
```

**Comment by lrhn** [comment]
Ad 1. No. There are not such things as "optional fields". The optional constructor parameters do not necessarily correspond to fields. The subclass constructor also doesn't do anything about the superclass constructor's optional, or required, parameters.

The parameters of a subclass constructor are independent of the super-class constructor. That's necessary because in some cases, you want a completely *different* set of parameters:
```dart
class PWidget {
  String color;
  int width;
  PWidget({this.color = "red", this.width})
}
class CWidget extends PWidget
  CWidget(String color) : super(color: color, width: 42);
  CWidget.widthless(String color) : super(color: color);
}
```
Here the `widthless` constructor invocation explicitly does not pass the `width` parameter. If we started automatically passing along a `width` parameter, then we would change the meaning of the constructor.
Nothing happens implicitly here, you have to write all the parameters you want to accept, and forward the ones that you need to forward, because you might want *not* to.

So, in your case the `CWidget` constructor will not have a `width` parameter unless you explicitly write one.
If you create a subclass of a Flutter Widget, I do need to list all the optional parameters in the subclass constructor *if* you actually want them to be available. It is quite possible to make a specialized subclass which does not allow you to provide all the options of the superclass.

Ad 2. Statics are not inherited in any way in Dart. Static member treat the surrounding class like a namespace, so if you want to access `height` from `PWidget`, you need to write `PWidget.height` unless the code is inside the `PWidget` class (because then the static declaration is directly in the lexical scope of the code).

**Comment by wyattbiker** [comment]
Where can I propose an enhancement to Dart's inheritance model?

**Comment by wyattbiker** [comment]
Closing this as I want to submit it differently as an enhancement request.
