### ISSUE TITLE
BigInt.modInverse() result error

### ISSUE THREAD

**Issue by yanxi-me** [dart-lang/sdk#37008]
This tracker is for issues related to:

* Dart core libraries ("dart:core")
* Dart SDK Version: Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "macos_x64"

I found BigInt.modInverse() result sometimes is error, you can reproduce error by the code below:

```dart
main() {
  var q = BigInt.parse(
      "fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f",
      radix: 16);

  var n = BigInt.parse(
      "28ea16430c1f1072754aa5ebbfda0d790605a507c6c9758e88697b0b5dd9e74c",
      radix: 16);

  var nInverse = n.modInverse(q);

  var result = (n * nInverse) % q;

  print('result=$result');
}
```

the result should be `1`, but it is `115792089237316195423570985008687907853269984665640564039457584007908834671662`, which is wrong.

**Comment by lrhn** [comment]
The two numbers are relatively prime (according to `BigInt.gcd`), so there is no reason this should not work.

Also seems to affect the dart2js `BigInt` code (unsurpricingly, since it's mostly a copy of the original VM code).

**Comment by crelier** [comment]
Thanks for the report!
The digits of the returned modInverse were actually calculated correctly, but its sign was wrong. It should have been negative in this particular case.
Since positive modInverse values are preferred, adding the modulus to bring the result positive is a better way to fix this bug.
I'll send a CL shortly.

**Comment by crelier** [comment]
https://dart-review.googlesource.com/c/sdk/+/103664 is under review.
