### ISSUE TITLE
Lsp crash after sending `textDocument/didChange`

### ISSUE THREAD

**Issue by itome** [dart-lang/sdk#37011]
I'm using analysis_server --lsp with `emacs-lsp`
https://github.com/emacs-lsp/lsp-mode/pull/841

```
Sending notification 'textDocument/didChange'.

Params: 
{
  "textDocument": {
    "uri": "file:///home/itome/Projects/animated_list_sample/lib/main.dart",
    "version": 10
  },
  "contentChanges": [
    {
      "range": {
        "start": {
          "line": 103,
          "character": 0
        },
        "end": {
          "line": 103,
          "character": 0
        }
      },
      "rangeLength": 0,
      "text": "          "
    }
  ]
}

```

After sending this message, analysis server crash and emacs-lsp try to restart it.

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
@itome do you get an information on the crash (like an error message)? If not, are you able to run the server with an extra flag like `--instrumentation-log-file=/foo/bar.txt` to capture additional info?

If you have instructions on how you set this up with emacs, I can try to reproduce it locally.

**Comment by itome** [comment]
@DanTup  
I run server with `--instrumentation-log-file` flag.
All logs in the file is this
https://gist.github.com/itome/46a5d7db2d314825bb0bb02f1a1b4043

**Comment by DanTup** [comment]
@itome Thanks! I believe what's happening here is that we're rejecting `textDocument/didChange` because we believe the file has not been opened. This results in us sending back this error:

```
return error(
  ServerErrorCodes.ClientServerInconsistentState,
  'Unable to edit document because the file was not previously opened: $path',
  null,
);
```

Looks like our shutdown code may be triggering too quick for us to log this, so I'll take a look at that. Anyway, the reason we believe the file is not open is logged here:

```
1558362960717:Req:{"jsonrpc"::"2.0","method"::"textDocument/didOpen","params"::{"textDocument"::{"uri"::"file::///home/itome/Projects/animated_list_sample/lib/main.dart","languageId"::null,"version"::0,"text"::"<SNIP>"}}}

1558362960721:Res:{"method"::"window/showMessage","params"::{"type"::1,"message"::"Invalid params for textDocument/didOpen"},"jsonrpc"::"2.0"}
```

The `textDocument/didOpen` request we got is failing our validation. Since it's a notification we can't "return an error" so we instead sent a message back using `window/showMessage` (though I'm not sure if emacs is showing this to you).

Here's the JSON being sent for `didOpen` re-formatted:

```js
{
	"jsonrpc": : "2.0",
	"method": : "textDocument/didOpen",
	"params": : {
		"textDocument": : {
			"uri": : "file::///home/itome/Projects/animated_list_sample/lib/main.dart",
			"languageId": : null,
			"version": : 0,
			"text": : "<SNIP>"
		}
	}
}
```

Notice that the `languageId` field is set to `null`. However, in the [LSP spec](https://microsoft.github.io/language-server-protocol/specification#textdocumentitem) this field does not permit `null`. Our validation is code-gen'd from the spec, which is we don't allow this and fail to process the request.

So this issue will need fixing in the emacs LSP library to not send `null`. If you don't see **Invalid params for textDocument/didOpen** somewhere when opening the file, I'd also suggest raising a request for them to surface this - since it's the only way a server has to indicate an error has occurred to the user for a notification (since there's no response to a notification).

Hope this makes sense - let me know if you have any questions!

**Comment by DanTup** [comment]
I had a look in the emacs-lsp code but it wasn't clear where their languageId comes from. I found this:

https://github.com/emacs-lsp/lsp-mode/blob/84bd71503d7485db1d83c8144ef13305257241a0/lsp-mode.el#L2975

I wonder if maybe it's some configuration that you can modify? If so, you might be able to fix it - though it's probably also worth raising and issue to not send the invalid requests from the server (for ex., maybe emacs-lsp could show a message that there's no language for the current file).

**Comment by itome** [comment]
Thanks! I tested to add `language-id` and now it seems working!
And I created PR to `lsp-mode` -> https://github.com/emacs-lsp/lsp-mode/pull/842

**Comment by DanTup** [comment]
Excellent! Do let us know if you hit any other problems :-)
