### ISSUE TITLE
Dart allows use super-bounded type parameters in the constant expressions

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#37033]
Dart SDK Version: 2.3.1-dev.0.0
OS: Windows 10 64 bit

Recent Dart Language Specification (https://dart.dev/guides/language/specifications/DartLangSpec-v2.2.pdf) reads in the Super-bounded types section:

> It is a compile-time error if a parameterized type T is super-bounded when it is used in any of the following ways:
>    T is an immediate subterm of a new expression (16.15.1) or a constant object expression (16.15.2).

However, currently this is not so.
For example, dart and analyzer does not throw compile error with the following test example (please run it with `--enable-experiment=constant-update-2018` flag):
``` dart
class A<T extends A<T>> {
  const A();
}

const b1 = 1 is A;
const b2 = 1 is A<dynamic>;
const b3 = 1 is A<Null>;
const b4 = 1 is A<void>;

const b5 = 1 is A<A>;
const b6 = 1 is A<A<dynamic>>;
const b7 = 1 is A<A<Null>>;
const b8 = 1 is A<A<void>>;

main() {
}
```

Sample output is:
> $> dart --enable-experiment=constant-update-2018 test.dart
> 
> $> dart --enable-experiment=constant-update-2018 test.dart
> Analyzing test.dart...
> No issues found!

**Comment by eernstg** [comment]
I think the crucial point here is "immediate subexpression". The point is that we wish to maintain the invariant that no instance has a type argument that violates the declared bound, so we can't have the following:

```dart
class A<X extends num> {}

main() => A<Object>(); // Error.
```

But it is OK for a type argument itself to be a super-bounded type:

```dart
class A<X extends num> {}
class B<Y> {}
main() => B<A<Object>>(); // OK.
```

With optional `new` and `const` the "immediate subexpression" qualified gets subtle, because it is tempting to think that each type argument is an immediate subexpression of the instance creation expression, but the intention is that we constrain the type of the instance itself, not the type arguments.

Next thing: I'm not sure why we are considering this reference to a constant object expression or a new expression with reference to the given example, because the example code does not contain any such expressions.

(A constant object expression is [`<constObjectExpression>`](https://github.com/dart-lang/language/blob/0e6111c01e7f35ad358c01570e5c865bd5269ce3/specification/dartLangSpec.tex#L7961).)

All the given expressions are `<typeTest>` and they are constant as specified [here](https://github.com/dart-lang/language/blob/0e6111c01e7f35ad358c01570e5c865bd5269ce3/specification/dartLangSpec.tex#L6200). In particular, the type that we're testing must be a constant type expression, and they can certainly be super-bounded.

**Comment by lrhn** [comment]
I agree, this code should be accepted. If we don't think the specification is not clear enough about that, it is a specification issue.
