### ISSUE TITLE
Analyzer: misleading message for factory constructor signature error

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#37048]
[Edit Jun 12th 2019: This issue is now concerned with the fact that the analyzer emits a somewhat misleading error message for the example below: It says 'assignable', but the reported error is actually about a required subtype relation. Cf. [this comment](https://github.com/dart-lang/sdk/issues/37048#issuecomment-501267392). Edited the title correspondingly.]

---

Dart SDK Version: 2.3.1-dev.0.0
OS: Windows 10 64 bit

Here is a sample code example:
``` dart
class A<X extends A<X>> {
  A() {}
  factory A.foo1() = C<Null>;
  factory A.foo2() = C<A<Null>>; 
  factory A.foo3() = C<A<A<Null>>>;
  factory A.foo4() = C<A<A<A<Null>>>>;
}

class C<X extends A<X>> extends A<X> {
  C() {}
}

main() {}
```
Both dart and analyzer throw compile errors for `foo2`, `foo3`, `foo4` declaring . Both pass without error with `foo1`.

Seems like all four cases should not throw errors here because `A<Null>()`, `A<A<Null>>()`, `A<A<A<Null>>>()`, etc. are valid `A`'s constructor calls.

Sample output is:
> $> dartanalyzer test.dart
> Analyzing test.dart...
>   error - The return type 'C<A<Null>>' of the redirected constructor isn't assignable to 'A<X>' at test.dart:4:22 - redirect_to_invalid_return_type
>   error - The return type 'C<A<A<Null>>>' of the redirected constructor isn't assignable to 'A<X>' at test.dart:5:22 - redirect_to_invalid_return_type
>   error - The return type 'C<A<A<A<Null>>>>' of the redirected constructor isn't assignable to 'A<X>' at test.dart:6:22 - redirect_to_invalid_return_type
> 3 errors found.
> 
> $> dart test.dart
> test.dart:4:22: Error: The constructor function type 'C<A<Null>> Function()' isn't a subtype of 'A<X> Function()'.
>  - 'C' is from 'test.dart'.
>  - 'A' is from 'test.dart'.
>   factory A.foo2() = C<A<Null>>;
>                      ^
> test.dart:5:22: Error: The constructor function type 'C<A<A<Null>>> Function()' isn't a subtype of 'A<X> Function()'.
>  - 'C' is from 'test.dart'.
>  - 'A' is from 'test.dart'.
>   factory A.foo3() = C<A<A<Null>>>;
>                      ^
> test.dart:6:22: Error: The constructor function type 'C<A<A<A<Null>>>> Function()' isn't a subtype of 'A<X> Function()'.
>  - 'C' is from 'test.dart'.
>  - 'A' is from 'test.dart'.
>   factory A.foo4() = C<A<A<A<Null>>>>;
>                      ^

**Comment by eernstg** [comment]
No, the errors are actually correct. For example, we cannot let `A<Null>.foo2()` return a `C<A<Null>>`, because that is not a subtype of `A<Null>`. So the redirections correspond to valid constructor calls, but the resulting object doesn't have the type that we promise for construction of an `A<T>`.

**Comment by iarkh** [comment]
If errors should be thrown here, shouldn't Specification be updated somehow?

It reads:
> It is a compile-time error if a parameterized type T is super-bounded when it is used in any of the following ways:
> ...
> • T is an immediate subterm of a redirecting factory constructor signature (10.6.2).

It does not stay it clearly, but it can be supposed that using **well bounded** constructor (for example, `C<A<Null>>()`) should not throw a error here.

**Comment by eernstg** [comment]
The error arises for a different reason, specified [here](https://github.com/dart-lang/language/blob/0e6111c01e7f35ad358c01570e5c865bd5269ce3/specification/dartLangSpec.tex#L3372). That's the sentence where it is required that a redirection will produce something that has the proper type. A more obvious violation of the same sentence would be this example:

```dart
class A {}
class B {
  factory B() = A;
}
```

The problem is that `B()` evaluates to an instance of `A`, and that is not a subtype of `B`. It terms of the above mentioned sentence the problem is that `A Function()` is not a subtype of `B Function()`, and the reason for looking at the whole function type (rather than just the return type) is that we also need to complain if the parameter list shapes or parameter types do not match up.

**Comment by jensjoha** [comment]
@eernstg does that mean this issue can be closed?

**Comment by eernstg** [comment]
@jensjoha wrote:
> does that mean this issue can be closed?

I just retried the example and noticed that the common front end (`dart`, 92dabc8491e767839fe6269e62f663b1ebb56484) reports the subtype issue that I mentioned, so I believe that there is no CFE issue here.

For the analyzer, it is confusing that the error message talks about 'assignable' even though the specified requirement is a ['subtype match'](https://github.com/dart-lang/language/blob/0e6111c01e7f35ad358c01570e5c865bd5269ce3/specification/dartLangSpec.tex#L3314) for the formal parameter list. But the reported error is concerned with the correct types (e.g., `C<A<Null>>` vs. `A<X>` for `foo2`), and it is raised in those 3 cases where there is no subtype match (and not in the fourth case where we do have the subtype match).

So we can remove 'area-front-end' and rename the issue to indicate that it's about a slightly misleading error message, not about raising compile-time errors that it shouldn't or vice versa.
