### ISSUE TITLE
Keyword collision while trying to send async requests inside async call 

### ISSUE THREAD

**Issue by drbcode** [dart-lang/sdk#37063]
```dart
import 'dart:html' as html;

void main() async {
  var request = new html.HttpRequest();
  request.open('POST', 'http://example.com', async: true);
}
```

Displays:
![async](https://user-images.githubusercontent.com/41248528/58235132-d1650580-7d5d-11e9-9eb8-521c15915ea4.png)

Dart VM version: 2.3.0

**Comment by lrhn** [comment]
That is a bug. 
The specification says:
```latex
It is a compile-time error if either of the identifiers \AWAIT{} or \YIELD{} is used as an identifier in a function body marked with either \ASYNC{}, \code{\ASYNC*} or \code{\SYNC*}.
```
That makes `await` and `yield` context-dependent keywords. They are keywords, but only inside `async`, `async*` or `sync*` methods. That choice was made because we needed the keywords, but did not want to break existing code that already uses the words.
The section *used* to also make `async` reserved, but that was changed for Dart 2.0 (it wasn't necessary).

Seems like the our tools haven't removed them from the reserved list yet.
