### ISSUE TITLE
Analyzer does not throw error when generic function implicit type arguments does not conforms bounds.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#37061]
Dart SDK Version: 2.3.1-dev.0.0
OS: Windows 10 64 bit

Here is a source code example where generic function with two dependent type arguments is called without specifying type parameters:
``` dart
class A<T extends A<T>> {}
void testme<X extends Y, Y extends A<X>>() {}

main() {
  testme();
}
```
Dart throws a compile error here whereas analyzer silently passes. Seems like it should throw a error here too.

Sample output is:
> $> dartanalyzer test.dart
> Analyzing test.dart...
> No issues found!
> 
> $> dart test.dart
> test.dart:5:3: Error: Inferred type argument 'dynamic' doesn't conform to the bound 'Y' of the type variable 'X' on 'testme'.
> Try specifying type arguments explicitly so that they conform to the bounds.
>   testme();
>   ^
> test.dart:2:13: Context: This is the type variable whose bound isn't conformed to.
> void testme<X extends Y, Y extends A<X>>() {}
>             ^

**Comment by lrhn** [comment]
The concrete type argument to a generic function must be regular-bounded (parameters must satisfy the bounds).
The analyzer infers `dynamic` as second type argument here.
It should instantiate to bound, and the mutually recursive bounds of `X` and `Y` should be inferred as `dynamic` and `A<dynamic>` respectively.
Neither of those are valid regularly-bounded type arguments, so it is a compile-time error, exactly like the front-end says (`dynamic` is not a valid argument to `X` because it is not a subtype of `Y`).

(The compiler is free to report that any way it wants, like saying that it cannot infer a type which would satisfy the requirement, instead of reporting that a type that the user never wrote, is incorrect :wink:).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/205635
