### ISSUE TITLE
Analyzer auto-completes classes multiple times

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#37075]
```
$ flutter --version

Flutter 1.6.0 • channel dev • git@github.com:flutter/flutter.git
Framework • revision ed90d05596 (9 days ago) • 2019-05-14 17:09:29 -0700
Engine • revision 832cdacc6f
Tools • Dart 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)
```

Given the following file and imports:

```dart
import 'package:flutter/material.dart';
```

When I type `class X extends Stateless`, I see the following auto-complete:

![Screen Shot 2019-05-23 at 3 03 43 PM](https://user-images.githubusercontent.com/168174/58289718-1132e980-7d6c-11e9-985a-8d8ab09393c2.png)

Note that `StatelessElement` and `StatelessWidget` shows up 3 times each. I think this is because this class is `export`-ed from multiple different entry-points in `package:flutter`?

**Comment by bwilkerson** [comment]
Yes, it's because of having multiple libraries from which the name can be imported. The analysis server is sending additional information about which library each name comes from (and consequently which import will be added if needed), but it appears that not all clients are displaying this information. That alone isn't sufficient to solve the UX issues, but it helps.

**Comment by CMMT20** [comment]
Hello, as you see in the image posted by @matanlurey, 
https://github.com/dart-lang/sdk/issues/37075#issue-447894544

Code completion gives you 2 or more options. The desire option for me in 99% of times is the class constructor, ClassFoo(), Scaffold(), Text()...
It is possible that you get the class constructor as first suggestion in code completion, with all widgets?
what get us to the question:
can you modify, customize relevance tables in order they give more relevance to the class constructor than to the class name?

**Comment by DanTup** [comment]
@matanlurey do you still see this? When the class is not already in-scope, you should see multiple entries, but they'll show which package they will auto-import from if you select them:

<img width="820" alt="Screenshot 2022-03-17 at 16 57 26" src="https://user-images.githubusercontent.com/1078012/158853708-68660942-a8ff-443d-bb18-846827a9baa0.png">

Once already in-scope, they should only appear once:

<img width="764" alt="Screenshot 2022-03-17 at 16 58 20" src="https://user-images.githubusercontent.com/1078012/158853782-ab492a4e-b082-454d-85dc-c82c31a1b5e9.png">

@CMMT20 I believe your request is unrelated to this one - please file a new issue. It would be useful to include an explicit code sample and screenshot of the list you're seeing too - in some cases VS Code may re-rank the items and ignores the ranks given by the analysis server (see https://github.com/microsoft/vscode/issues/79516).

**Comment by CMMT20** [comment]
@DanTup you are right, sorry, and thanks for the warning. Interesting what you said, sometimes the IDE can re-rank the items. That gives me a second way to solve my issue, if i can not solve it changing the relevance tables, perhaps i can do it through the IDE re-ranking.

**Comment by DanTup** [comment]
I don't think you'll be able to change it in VS Code (at least not via settings or an extension) for the same reason I can't control it from the Dart extension. VS Code assumes the rankings from extensions are only relevant before you type a prefix. Once you start typing, VS Code applies filtering client-side, and uses its own relevance scores to try and ensure the most likely items are at the top.

For example, in the original server ranking we might say that `OtherFoo()` is more likely than `Foo()` (perhaps because you're completing in a location where the expected type is `OtherFoo`) but if you type `foo`, VS Code might decide (without any context of types) that `Foo()` is the most likely option because you're exactly typed it.

That said, if you do find a way (that doesn't involve modifying the VS Code source), I'd be interested to hear!

**Comment by CMMT20** [comment]
Ok, it is very interesting all this you say, im learning my way to solve what i need.
If i find a way, i will tell you, sure.

As i have seen, some of the no optimized behaviour in Code Completions come from:
The relevance order comes from source code samples from years ago a lot of times, so it is optimized for that code, not for the one you are writing today. I think the thing will improve a lot, when samples get more current, but specially when get customizables. That is the way im trying to solve this, customizing the relevance tables. Have a good day.

**Comment by srawlins** [comment]
While this issue was filed first, I think there is more discussion at a duplicate issue, over at https://github.com/dart-lang/sdk/issues/40216. I'm closing this in favor of that.
