### ISSUE TITLE
Compile and run a flutter app

### ISSUE THREAD

**Issue by taylorren** [dart-lang/sdk#37086]
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3219081/initialize_from.dill.gz)
Thank you for taking the time to file an issue!

Please see attached file.

**Comment by lrhn** [comment]
Could you describe what we should be looking for?

**Comment by lrhn** [comment]
@jensjoha @aam

**Comment by taylorren** [comment]
> 
> 
> Could you describe what we should be looking for?

I am not sure. This is the first time I submit this kind of thing.

**Comment by lrhn** [comment]
My bad. I have since found out that the tool requested that you upload that file (and which tool, so I can assign it to the correct area, who'll know what this means).

Cheers!

**Comment by jensjoha** [comment]
Best guess: You've "downgraded" from flutter master to flutter beta and in the process the flutter sdk changed.

This makes this issue the 'reverse' of #36851.

To summarize, everything is fine - the compile that reported this will be slower, but the output will be perfectly fine. It is caused by an changed flutter sdk.
