### ISSUE TITLE
add a quick fix for curly_braces_in_flow_control_structures

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#37084]
The `curly_braces_in_flow_control_structures` lint is now enabled and reported in pedantic. It would be nice to have a quick fix for this, for places where it's clear how to fix.

@bwilkerson @pq @srawlins

**Comment by srawlins** [comment]
Similar request: https://github.com/dart-lang/dart_style/issues/664

**Comment by bwilkerson** [comment]
@scheglov 

We already have support for this, but I suspect that it's too hard to use. If a user selects one or more complete statements, when we have assists that will wrap those statements in a block or in any control structure. The part that makes this hard to use is that the complete statement must be selected.

For example, if a user has code like
```
main() {
  if (0 < 1) print('true');
}
```
and they select `print('true');` (a whole statement), then the assists are produced, but if they select anything less than the whole statement, the assists are not produced.

I suspect that the reason we made that choice originally is because we don't have any mechanism by which we can communicate to users what code will be affected by the change if it's different than what they selected. I'm not sure that was a good choice. Given that they can always undo the change, perhaps we should allow selection of a partial statement.

What do other people think?

**Comment by pq** [comment]
> Given that they can always undo the change, perhaps we should allow selection of a partial statement.

+1.  And in general as I've been hit by this elsewhere as well.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/103721
