### ISSUE TITLE
Server: plugin_manager kills plugins when can't resolve the package

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#37217]
If I have a package which loads a third party package as a plugin, and a subpackage which does not reference the third party package, then the plugin crashes.

`my_project/analysis_options.yaml`
```yaml
analyzer:
  plugins:
    angular
```

`my_project/pubspec.yaml`
```yaml
dependencies:
  angular: any
```

`my_project/lib/foo.dart`
```dart
import "package:angular/angular.dart"
...
```

`my_project/subproject/pubspec.yaml`
```yaml
dependencies:
  # none
```

It attempts to start plugins for each root, and since subproject since its own root which doesn't have its own `analysis_options.yaml` it inherits the outer options. However, it cannot resolve the package `angular` inside of subproject, and crashes the plugin for `lib/foo.dart`.

**Comment by MichaelRFairhurst** [comment]
@bwilkerson do you want to take a look at this or do you want me to?

**Comment by bwilkerson** [comment]
I'm happy to let you look into it.

I'm not entirely sure what the behavior ought to be, but I'm confident that crashing the plugin isn't the right behavior. I suspect that what it ought to do is not attempt to use the plugin to analyze anything in `subproject` because it doesn't know which version of the plugin would be appropriate.

If it isn't already doing so, server needs to communicate to the client that `subproject` should be excluded when analyzing `my_project`.

It would also be nice to produce a diagnostic that indicates the nature of the problem so that other users would have an easier time understanding why the plugin isn't analyzing files in `subproject`. I think the diagnostic should be reported against `subproject/pubspec.yaml`. But that might be more work than we can afford to do right now.
