### ISSUE TITLE
Naming conflict of multi-inherited members？

### ISSUE THREAD

**Issue by 84819760** [dart-lang/sdk#37269]
//C# code
interface IInterface1 { string GetValue(); }
interface IInterface2 { int GetValue(); }
class Test : IInterface1, IInterface2
{
    //explicit override:
    string IInterface1.GetValue() => "result";
    int IInterface2.GetValue() => 9527;       
}
void Main(string[] args)
{
        //Use interface
        var test = new Test();
        string resultString = (test as IInterface1).GetValue();
        int resultInt = (test as IInterface2).GetValue();
}
//-------------------------------------------------------------------------
//Dart code
abstract class Interface1 { **String** getValue(); }
abstract class Interface2 { **int** getValue(); }
class Test implements Interface1, Interface2 {
//how to **explicit override**?
}

**Comment by lrhn** [comment]
Dart does not have overloading at all. A class or interface can only have one member with a given name, and it must be a valid override of all superinterface members with the same name.

In this situation, the only valid override would be `Null getValue();` because `Null` is the only type which is a subtype of both `String` and `int`.

You cannot do C#-like overloading of multiple virtual methods in the same interface.
