### ISSUE TITLE
Analyzer produces "strong_mode_not_instantiated_bound" error message which can be more useful.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#37290]
Dart version: 2.4.0-dev.0.0

The following code sample:
``` dart
class A<T extends A> {}
main() {}
```
produces the following output when run processed by dartanalyzer:
> $> dartanalyzer test.dart
> 
> Analyzing test.dart...
>   error - Type parameter bound types must be instantiated at test.dart:1:19 - strong_mode_not_instantiated_bound
> 1 error found.

Strong mode is deprecated now, so mention of it in the error message which appears in default mode looks a little bit strange here. It seems like analyzer should produce something  more informative.

For example, here is dart output:
> $> dart test.dart
>
> test.dart:1:9: Error: Generic type 'A' can't be used without type arguments in the bounds of its own type variables.
> Try providing type arguments to 'A' here.
> class A<T extends A> {}
>         ^

**Comment by lrhn** [comment]
Also, @eernstg, why is it not just a raw type instantiated with `dynamic`, which would be a valid super-bounded type?

**Comment by eernstg** [comment]
> why is it not just a raw type

The relevant error message is actually that `A` cannot occur as a bound, because it is raw and does not have simple bounds. We introduced the concept of a simple bound in order to ensure that tools could have good performance (because there is no need to run a fixed point iteration during instantiation to bound, because cyclic dependencies are non-simple).

So it's very nearly correct that `Type parameter bound types must be instantiated`, it should just have been `Type parameter bound types must be instantiated, unless they have simple bounds`.

For the UX, the very concept of saying `simple bounds` in an error message is not nice, but the underlying problem is actually that `A` is too complex to allow it to be raw as a bound, so it might be OK to say something like `The type parameter bound `A` must receive type arguments`. That's sufficient to tell the developer that `A` must be changed to `A<T>` for some `T`, and then `simple bounds` actually only matter for those folks who want to know exactly when this can happen.

**Comment by srawlins** [comment]
The error message now does not mention strong mode:

> error • Type parameter bound types must be instantiated. • 37290.dart:1:19 • not_instantiated_bound
