### ISSUE TITLE
awaiting `Future.wait` with `FutureOr<Null>` behavior is inconsistent between dart2js/DDC

### ISSUE THREAD

**Issue by smaifullerton-wk** [dart-lang/sdk#37315]
Dart version: 2.3.2
MacOSX Mojave 10.14.3
Google Chrome 75.0.3770.80
(also reproducible in Dartpad)

The below code analyzes fine, but results in an error at runtime when compiled with dart2js.
Both analysis and running the code succeeds with DDC.

```dart
import 'dart:async';

void main() async {
  var noProblem = new Future<Null>.value();
  var problem = createAProblem();
  
  // all good
  await Future.wait([noProblem]);
  
  // not good with dart2js: 
  print(problem.runtimeType); // _Future<Null>
  // Uncaught Error: Error: Cannot use 'in' operator to search for '$isFuture' in undefined
  await Future.wait([problem]);
}

FutureOr<Null> createAProblem() {
  var completer = new Completer<Null>();
  return completer.future;
}
```

However, if I change the type parameter to anything except `Null`, I get static analysis errors: 

```dart
import 'dart:async';

void main() async {
  var problem = createAProblem();
    
  // The argument type 'List<FutureOr<int>>' can't be assigned to the parameter type 
  // 'Iterable<Future>'. 
  // Couldn't infer type parameter 'E'. Tried to infer 'FutureOr<int>' for 'E' which doesn't 
  // work: Return type declared as 'List<E>' used where 'List<Future<?>>' is required. 
  // The type 'FutureOr<int>' was inferred from: List element declared as 'E' but 
  // argument is 'FutureOr<int>'. Consider passing explicit type argument(s) to the generic.
  await Future.wait([problem]);  // static analysis errors
}

FutureOr<int> createAProblem() {
  var completer = new Completer<int>();
  return completer.future;
}
```

Thanks for taking a look.

**Comment by lrhn** [comment]
The type of `Future.wait` is `Future<List<T>> Function<T>(Iterable<Future<T>> futures, {...})`.
It must get an iterable of *futures*.

A `FutureOr<X>` *is-not* (generally) a `Future` ... except for a few edge cases where the type distinction between the value and the future disappears. One such case is when `X` is `Null`.
Because all types in Dart are nullable (for now), `FutureOr<Null>` is *equivalent to* `Future<Null>`—they can assume exactly the same values, a `null` or a `Future<Null>` instance. (In technical terms they are both super- and sub-types of each other, so for subtyping purposes they are completely equivalent).

The expression `await Future.wait([problem])` has types inferred as `await Future.wait<Null>(<FutureOr<Null>>[problem])`. 
Since `FutureOr<Null>` is equivalent to `Future<Null>`, a `List<FutureOr<Null>>` is-an `Iterable<Future<Null>>`, so the call should work.
The dart2js error seems like a genuine bug.

If you change the type of `createAProblem` to returning `FutureOr<int>`, then the type inference cannot make `Future.wait([problem])` work. The type of the list should be `List<FutureOr<int>>`, and that is not assignable to `Iterable<Future<int>>` (or `Iterable<Future<T>>` for any reasonable `T` that we can derive here). Since `List` is a subtype of `Iterable` and `FutureOr<X>` is a supertype of `Future<X>`, a `List<FutureOr<X>>` is neither a subtype nor a supertype of `Iterable<Future<X>>`. Hence it is not assignable, not even with an implicit downcast.

That is why you get a compile-time error. It's a completely *valid* error! For all we know, `createAProblem` might have returned an `int` like 37, and a list containing 37 is *not* a valid argument to `Future.wait`, which expects only futures.

**Comment by smaifullerton-wk** [comment]
Great, thanks for the detailed and fast response!
