### ISSUE TITLE
DecorateType.forElement invoked on a constructor element that is being migrated

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#37347]
Attempting to migrate the following code produces an exception because the code is attempting to call `DecorateType.forElement` for the constructor element associated with `Foo`. It's possible that it's because the constructor is synthetic.
```
void main() => f(Foo());
f(Foo f) {}
class Foo {}
```

**Comment by stereotype441** [comment]
I see the problem: the node builder isn't building a decorated type for the default constructor because it only builds decorated types for methods that it sees in the source code, and the default constructor doesn't appear in the source code.  I'm working on a fix.

**Comment by bwilkerson** [comment]
Does it have similar problems with other synthetic elements (such as the elements created for enum classes or the constructors created for mixin applications)?

**Comment by stereotype441** [comment]
Yeah, probably.  In my fix, I'm adding a comment next to the code in `DecorateType.forElement` that throws the exception, so that if/when this situation arises again, it'll be clear that the fix belongs in NodeBuilder.  Feel free to implement logic for some of the other synthetic elements in follow-up CLs, if you want.

**Comment by stereotype441** [comment]
https://dart-review.googlesource.com/c/sdk/+/107183 addresses the issue for non-generic classes.  I'll leave the bug open while I address generic classes.
