### ISSUE TITLE
Future(() => null) is Future<dynamic> and not Future<Null>?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#37402]
This came up when I was trying to answer [a question on StackOverflow](https://stackoverflow.com/questions/56796121/flutter-and-dart-and-future-is-this-a-known-feature-of-dart-futures-and-null): the following code prints `Future<dynamic>` instead of `Future<Null>`.  Is this expected?

```dart
Future<String> foo() {
  final future = Future(() => null);
  print('${future.runtimeType}'); // Prints: Future<dynamic>
  return future;
}

Future<void> main() async {
  await foo();
}
```

The above code fails at runtime when it tries to return `Future<dynamic>` as a `Future<String>`.  `dartanalyzer` generates no complaints (even with `implicit-dynamic` and `implicit-casts` disabled), so the inconsistency implies there's either an inference bug or an analysis bug.

I tried this with `dart` and `dartanalyzer` from SDK versions 2.3.0, 2.3.2, and 2.4.0.

**Comment by lrhn** [comment]
I believe `Null` is treated specially by type inference, probably mainly for historical reasons.
The `null` value can be any type, and since existing code would happily use `null` as an initializer value for any type, inferring `Null` would break a *lot* of code. 

Example:
```dart
var x = null;
...
x = "foo";
```
If the initializer had been a string, we would have inferred `String` as the type for `x`, but inferring `Null` seems like an obviously *wrong* deduction (no need to ever have a mutable variable with type `Null`).
So, for backwards compatibility, the type of `x` was inferred as `dynamiic`.
A type of `Null` was not considered a strong enough hint to deduce a type, and the type instead becomes `dynamic`.

My guess is that this happens everywhere, even though it's only really necessary for variables.

The workaround is to write `Future<String>(() => null)` or `Future<String>.value(null)` or even `Future<Null>.value(null)`.

**Comment by jamesderlin** [comment]
To clarify: there *is* a bug here in that the analyzer is not consistent with actual behavior.

**Comment by natebosch** [comment]
Either this should be inferred as `Future<Null>` and analyzer is correct while CFE has a bug in inference, or this should be inferred as `Future<dynamic>` and analyzer has a bug.

**Comment by eernstg** [comment]
Agreed that there is a bug, because the choice between `Future<Null>` and `Future<dynamic>` cannot be implementation dependent. But this issue is basically blocked on https://github.com/dart-lang/language/issues/436, which will resolve which implementation has the bug.

**Comment by asashour** [comment]
I think this should be closed. With Dart `2.19.2`, the analyzer triggers a message, and it is similar to the one of the CFE.
