### ISSUE TITLE
VERSION SOLVING FAILED due to build_config ^0.3.1

### ISSUE THREAD

**Issue by hpoit** [dart-lang/sdk#37410]
I'm on Dart 2.4.0, macOS 10.13.6, Chrome, 
WebStorm 2019.1.3, Build #WS-191.7479.14, Licensed
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

https://gist.github.com/hpoit/b6412ff80f9522deed5a8e9476f68604

**Comment by natebosch** [comment]
The message looks actionable to me - you can't have a project that depends on both `build_runner: ^1.5.0` and `build_config: ^0.3.1` because those versions are incompatible. Upgrade the `build_config` dependency to `^0.4.0` and if necessary because of another constraint elsewhere use an override - or downgrade `build_runner` to an earlier version.
