### ISSUE TITLE
CFE infers bottom in some generic async contexts

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#37439]
Snippet:
```
class A {}

class B extends A {}

Future<T> func1<T extends A>(T t) async {
  return func2(t);
}

T func2<T extends A>(T t) => t;

main() async {
  await func1(B());
}
```
This passes in DDC, but kernel-based backends error out with:
```
Unhandled exception:
type 'B' is not a subtype of type 'Null'
```

The CFE generates something like this for `func1`:
```
  static method func1<T extends bot::A = bot::A>(bot::func1::T t) → asy::Future<bot::func1::T> async {
    return bot::func2<<BottomType>>(t as{TypeError} <BottomType>);
  }
```

cc: @natebosch, @leafpetersen

**Comment by Markzipan** [comment]
cc @johnniwinther

**Comment by dgrove** [comment]
Any updates on this, @johnniwinther ?

**Comment by johnniwinther** [comment]
I can verify that we indeed infer bottom type as the type argument for the 'func2' call. Haven't had the time to figure out why.

**Comment by johnniwinther** [comment]
I've added a test for this problem in https://dart-review.googlesource.com/c/sdk/+/112087

**Comment by stefantsov** [comment]
It's an interesting issue.  Apparently, we don't have an answer right now about how to handle the code in the example above w.r.t. the language semantics, but we may have it soon.

/cc @eernstg

**Comment by eernstg** [comment]
We don't have a complete and stable specification of type inference at this point. But in this particular case it seems likely to me that the expression `func2(t)` gets an actual type argument based on the context type `FutureOr<T>` and the bound `A`, so one possible choice is a lower bound of those.

This could be `T`, but that particular lower bound computation is a bit special, cf. [this text](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#futureor). Maybe DDC has that special treatment of this case, and CFE does not?

**Comment by leafpetersen** [comment]
> This could be `T`, but that particular lower bound computation is a bit special, cf. [this text](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#futureor). Maybe DDC has that special treatment of this case, and CFE does not?

The analyzer, when computing lower bounds for the purposes of inference *only*, has an additional rule for `FutureOr`.

```dart
  /// - `GLB(FutureOr<A>, B)` is defined as:
  ///   - `GLB(FutureOr<A>, FutureOr<B>) == FutureOr<GLB(A, B)>`
  ///   - `GLB(FutureOr<A>, Future<B>) == Future<GLB(A, B)>`
  ///   - else `GLB(FutureOr<A>, B) == GLB(A, B)`
  /// - `GLB(A, FutureOr<B>) ==  GLB(FutureOr<A>, B)` (defined above),
  /// - else `GLB(A, B) == Null`
```

I suspect that the issue you are running into with the CFE is that it does not implement this, since this is what allows the inference in the example above.  The example is clearer if you rename it as follows:

```dart
Future<T> func1<T extends A>(T t) async {
  return func2(t);
}

S func2<S extends A>(S t) => t;
```

Inference for `func2(t)` then proceeds as follows:

Subtype matching produces the constraint:
  `? <: S <: FutureOr<T>`
The bound on `func2` adds the additional constraint:
  `? <: S <: A`

Constraint solving asks for the lower bound of `FutureOr<T>` and `A`.

The core lower bound algorithm computes `Null` for this, but the strong mode analyzer implementation has a special extension to lower bound during inference as described above, and so we end up computing the lower bound of `T` and `A`, which, since `T <: A` holds, is computed as `T`.

See [here](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/generated/type_system.dart#L1519) for the relevant analyzer code.

We should probably just make this part of the full lower bound algorithm.

**Comment by eernstg** [comment]
> We should probably just make this part of the full lower bound algorithm.

:+1: 

Just one thing confused me:

> `GLB(A, FutureOr<B>) ==  GLB(FutureOr<A>, B)`

seems to imply things like `GLB(Future<int>, FutureOr<int>) == GLB(FutureOr<Future<int>>, int)`, but the former has `Future<int>` as a subtype of both arguments and the latter only `Null` (pre-NNBD). Maybe it's `GLB(A, FutureOr<B>) ==  GLB(FutureOr<B>, A)`?

**Comment by leafpetersen** [comment]
> Maybe it's `GLB(A, FutureOr<B>) == GLB(FutureOr<B>, A)`?

Yeah, that's just a typo in the comment, should be what you wrote.  The intent is just to specify the symmetric cases.

**Comment by stefantsov** [comment]
> ```dart
>   ///   - `GLB(FutureOr<A>, Future<B>) == Future<GLB(A, B)>`
> ```

We weren't doing this one as well.  Will fix in the same CL.

**Comment by stefantsov** [comment]
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/112722.
