### ISSUE TITLE
mixin error with inheritance

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#37434]
With Dart-2.4.0 I face an error with the following code:

```dart
abstract class A{
  m();
}
abstract class B extends A{
}

mixin M on A {
  f() => m();
}

class C with M implements B {
  m() => null;
}
```

The error is:

```
Error: 'Object' doesn't implement 'A' so it can't be used with 'M'.
 - 'Object' is from 'dart:core'.
 - 'A' is from 'package:a/a.dart' ('lib/a.dart').
 - 'M' is from 'package:a/a.dart' ('lib/a.dart').
class C with M implements B {
      ^
```

As `B` extends `A`, `C` should implements `A` (as it implements `B`).

Am I missing something?

**Comment by eernstg** [comment]
The syntax `class C with M ..` is an abbreviation of `class C extends Object with M ..`, so you're trying to apply the mixin `M` to `Object`, and `Object` does not satisfy the constraint `on A` from the declaration of `M`.

You do not seem to need that, anyway (because there are no superinvocations of any members of `A`), so you could just use the following declaration:

```dart
mixin M implements A {
  f() => m();
}
```

This means that the availability of an `m` method on `this` is required because any concrete class that mixes in `M` must also implement `A`, but you don't require that `m` must be provided by the superclass, and that seems to be what you actually need anyway.

**Comment by a-siva** [comment]
closing issue as question above has been answered.

**Comment by a14n** [comment]
Thanks @eernstg ! I falled in a trap of `on` vs. `implements`.
