### ISSUE TITLE
Type system does not infer the correct type (edgecase)

### ISSUE THREAD

**Issue by lookfirst** [dart-lang/sdk#37454]
###  Version information

* Dart version 2.4.0
* Flutter version 1.7.8+hotfix.2
* Framework revision 2e540931f7
* Engine revision b1cb0d9e9b

```
IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5587.17, built on July 3, 2019
IntelliJ IDEA EAP User
Expiration date: August 2, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: 
Non-Bundled Plugins: GrepConsole, Lombook Plugin, com.intellij.plugins.watcher, name.kropp.intellij.makefile, AutoPackage, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, com.intellij.react.css.modules, org.jetbrains.plugins.go, Dart, io.flutter, izhangzhihao.rainbow.brackets, Pythonid, org.toml.lang, ru.adelf.idea.dotenv, ua.in.dej.myEmmet
```

### Example code

```dart
  makeGpuButtons() {
    var gpus = [];
    gpus.add(Scanner(buttonName: 'GPU'));
    return gpus;
  }

  rowOf(List<Scanner> gpuButtons, int start) {
    return Container(
      child: Row(
          children: [...gpuButtons.sublist(start * 2, start * 2 + 2)]),
    );
  }

  var gpuButtons = makeGpuButtons();
  Column body = Column(children: [rowOf(gpuButtons, 0)]);
```

### Error message

Produces an error on the `rowOf(gpuButtons, 0)` line:

```
flutter: The following assertion was thrown building HomePage(dirty):
flutter: type 'List<dynamic>' is not a subtype of type 'List<Scanner>'
```

### Workaround

In `makeGpuButtons()`, changing...

`var gpus = [];` to `List<Scanner> gpus = [];`

then provides enough of a hint to prevent the issue.

### Comments

There is no warnings or errors in my IDE.

I feel like the type system should be a bit smarter here because there is no way that `makeGpuButtons()` is returning anything other than `List<Scanner>`.

Changing `makeGpuButtons()` to be `List<Scanner> makeGpuButtons()` also does not solve the issue.

**Comment by lookfirst** [comment]
Interestingly enough, this does not have the typing issue and effectively does the same thing.

```
final listOfTwelve = List.generate(12, (index) => ++index);
makeGpuButtons() => listOfTwelve.map((index) => Scanner(buttonName: ‘GPU $index’)).toList();
```

**Comment by lrhn** [comment]
The function 
```dart
  makeGpuButtons() {
    var gpus = [];
    gpus.add(Scanner(buttonName: 'GPU'));
    return gpus;
  }
```
has no declarted return type and no type annotations. The first line is `var gpus = [];`. Absent of any type annotations, that infers a type of `List<dynamic>` for the type literal.
You then add a `Scanner` to the list, which is allowed since anything can be assigned to `dynamic`, and then you return the list, which is valid because you haven't specified any return type for the function.

When you then try to use that `List<dynamic>` where a `List<Scanner>` is required, you get a run-time error. That's working as expected.

The code:
```dart
final listOfTwelve = List.generate(12, (index) => ++index);
makeGpuButtons() => listOfTwelve.map((index) => Scanner(buttonName: ‘GPU $index’)).toList();
```
infers `List<int>` for `listofTwelve` because the function argument has a context type of `?  Function(int)`, and the compiler can see that the function is then a an `int Function(int)`.
The `makeGpuButtons` function then calls `map` on that with, what is inferred as, an `Scanner Function(int)` function, so it concludes that the result is an `Iterable<Scanner>`.

The difference is that here you create the list in the same line where you create the `Scanner`, so the type system has the information available to figure out what kind of list you are creating. In the first example, you create the list first, on a line by itself, and with no type information available. The type inference foes not look ahead, it only bases its inference on things it has already seen.

**Comment by lookfirst** [comment]
@lrhn Thanks for the excellent detailed answer.

```
gpus.add(Scanner(buttonName: 'GPU'));
```

I would think that putting a bunch of Scanner objects into gpus would give enough 'hint' though. Or maybe that is the 'not looking ahead' that you're talking about?

**Comment by lrhn** [comment]
Yes, that is "looking ahead". At the point where the list is created, there is no hint.
The fact that you add `Scanner` instances later hasn't been noticed yet, and it is quite a lot more complicated to have inference that looks both backwards and forwards at the same time (for example, the code which adds the element might depend on the type of the list itself, so now you have a circular dependency).
