### ISSUE TITLE
dart2aot: support creating dynamically linked library

### ISSUE THREAD

**Issue by truongsinh** [dart-lang/sdk#37480]
Similar to https://github.com/dart-lang/sdk/issues/36915, but compile to a dynamically linked library (dll) / shared object (so) instead, so that it can be `dlopen`ed from other languages' FFI (or even Dart's own FFI https://github.com/dart-lang/sdk/issues/34452).

**Comment by truongsinh** [comment]
cc @joshirio

**Comment by shinayser** [comment]
THIS!

**Comment by mkustermann** [comment]
Compared to other languages (such as C or Rust) the Dart language cannot be simply compiled to machine code using `dart2aot` and be self-contained. Instead it needs to run inside an embedder which will contain various parts of the Dart VM (garbage collector, runtime type system, ...).

This means it's simply not possible to just `dlopen()` a AOT-compiled Dart application, look up symbols via `dlopen()` and call functions in them.

In order to achieve this one would need to create a standalone embedder containing the Dart VM. One could then `dlopen()` this embedder and ask it to load an AOT compiled application as well as ask it to execute functions in them. (This is in fact exactly what Flutter does: it has a `libflutter.so` embedder containing the Dart VM).

See also https://github.com/dart-lang/sdk/issues/42667

Since we have no plans to work on a standalone embedder loadable as a shared library and such an embedder could be created by the community, I hope it's all right to close this issue.
