### ISSUE TITLE
Warning: Tried to initialize from a previous compilation

### ISSUE THREAD

**Issue by pedromassango** [dart-lang/sdk#37493]
Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///C:/Users/P

M~1/AppData/Local/Temp/initialize_from.dill2360dbbf-a367-11e9-8829-f439092ec75d/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.

**Comment by jensjoha** [comment]
Thank you for your report. Unfortunately this is not actionable.
We've seen reports like this before, though it is usually caused by a change in the flutter sdk (see also #36759).
To summarize, everything is fine - the compile that reported this will be slower, but the output will be perfectly fine.
