### ISSUE TITLE
VM fails to handle missing static targets after reload

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#37517]
@whesse approved the failure back in February, but I could not find an issue for that.
```
{"name":"lib_2/mirrors/dynamic_load_test","configuration":"dartk-reload-linux-debug-x64","suite":"lib_2","test_name":"mirrors/dynamic_load_test","result":"RuntimeError","expected":"Pass","matches":false,"approver":"whesse","approved_at":"2019-02-14T13:33:48.170187Z","preapprovals":{}}
```

With https://dart-review.googlesource.com/c/sdk/+/106943 (cc @mraleph) the test started to Crash(? But what does `Crash -> RuntimeError` mean in the below diagnostic, @whesse ?) :
```
─➤  tools/test.dart -n dartk-reload-linux-debug-x64 lib_2/mirrors/dynamic_load_test
Testing the named configuration dartk-reload-linux-debug-x64 compared with builder vm-kernel-reload-linux-debug-x64
Base commit is 178cfe6111187e0ed32ee40ae3cba34afb026acf
Finding build on builder vm-kernel-reload-linux-debug-x64 to compare with...
Warning: Builder vm-kernel-reload-linux-debug-x64 hasn't built commit 178cfe6111187e0ed32ee40ae3cba34afb026acf, searching for an inexact previous build...
Warning: Using commit e82ca2f36639a07ae702249a1a4e54d1772b3d51 as baseline instead of 178cfe6111187e0ed32ee40ae3cba34afb026acf for vm-kernel-reload-linux-debug-x64
Downloading results from builder vm-kernel-reload-linux-debug-x64 build 4860...
Downloaded baseline results from builder vm-kernel-reload-linux-debug-x64
================================================================================
Running tests
================================================================================
Test configuration:
    dartk-reload-linux-debug-x64(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: linux, preview-dart-2, hot-reload)
Suites tested: lib_2
[00:02 | 100% | +    1 | -    0]
================================================================================
Test Results
================================================================================
The following tests began failing:

lib_2/mirrors/dynamic_load_test failed again (Crash -> RuntimeError, expected Pass)


/=====================================================================================\
| lib_2/mirrors/dynamic_load_test failed again (Crash -> RuntimeError, expected Pass) |
\=====================================================================================/

--- Command "vm" (took 02.000061s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --suppress-core-dump --no-background-compilation --hot-reload-test-mode --ignore-unrecognized-flags --packages=/usr/local/google/home/aam/p/d/dart-sdk/sdk/.packages /usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/lib_2/mirrors/dynamic_load_test.dart

exit code:
255

stdout:
IsolateMirror on 'main'
LibraryMirror on 'dynamic_load_success'
InstanceMirror on 1
InstanceMirror on 2
LibraryMirror on 'dynamic_load_success'

stderr:
Unhandled exception:
Expect.equals(expected: <LibraryMirror on 'dynamic_load_success'>, actual: <LibraryMirror on 'dynamic_load_success'>) fails.
#0      Expect._fail (package:expect/expect.dart:655:5)
#1      Expect.equals (package:expect/expect.dart:126:5)
#2      main (file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/tests/lib_2/mirrors/dynamic_load_test.dart:27:10)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

--- Re-run this test:
python tools/test.py -n dartk-reload-linux-debug-x64 lib_2/mirrors/dynamic_load_test


Warning: Results may be inexact because commit e82ca2f36639a07ae702249a1a4e54d1772b3d51 was used as the baseline for vm-kernel-reload-linux-debug-x64 instead of 178cfe6111187e0ed32ee40ae3cba34afb026acf
```

**Comment by vsmenon** [comment]
@a-siva - do we need to resolve this for the const update?

**Comment by whesse** [comment]
The crash->runtimeError message means that your local checkout is 178cfe, and it fetched the results from CI for the commit before that, e82ca2f.  On the CI, it is crashing (for both those commits), but the local run of the test on your computer didn't crash, but instead produced a runtime error.  For some reason, the test behaved differently on the CI than it did locally.  Are you certain you rebuilt locally?
Usually, you run test.dart when you have local changes, that you want to compare to the base version from the CI.  That is why it shows differences between the CI run and your local run.

**Comment by a-siva** [comment]
@vsmenon It looks like we went from a crashing status to a runtime failure for these tests I don't think it is critical to resolve these for the const update.

**Comment by rmacnak-google** [comment]
This isn't related to the const update. The const update just affects the timing in this test.

The issue is that the kernel compiler doesn't keep track of the dynamic load in later reloads, so later reloads effectively delete the dynamically loaded library. Depending on when this happens, the test can fail when it asserts a second load should produce the same library or crash when lookups within the deleted library fail.

The first case is related to the bad architecture where kernel compiler duplicates the state of an isolate and easily falls out of sync. Since use of IsolateMirror.loadUri isn't commonly used, issuing an error when reloading an isolate that included a dynamic load may should be okay in the short term.

More interesting is the second case, since this can happen even in the absence of a dynamic load through code from a deleted library being captured in a closure or on the stack. The Dart 1 implementation was resilient here because it would simply emit code to throw a NoSuchMethodError when the target of a static reference did not exist, but the Dart 2 implementation incorrectly believes that compile-time errors prevent this from happening.

**Comment by rmacnak-google** [comment]
See also vm/cc/IsolateReload_PendingStaticCall_DefinedToNSM.

**Comment by sstrickl** [comment]
> The crash->runtimeError message means that your local checkout is 178cfe, and it fetched the results from CI for the commit before that, [e82ca2f](https://github.com/dart-lang/sdk/commit/e82ca2f36639a07ae702249a1a4e54d1772b3d51). On the CI, it is crashing (for both those commits), but the local run of the test on your computer didn't crash, but instead produced a runtime error. For some reason, the test behaved differently on the CI than it did locally. Are you certain you rebuilt locally?
> Usually, you run test.dart when you have local changes, that you want to compare to the base version from the CI. That is why it shows differences between the CI run and your local run.

Assuming you're responding to my comment on issue #37529: I ran the command to run the test directly, not through the testing scripts (with which I still have the bad habit of using the old `test.py`), and looked at the results that way, because using the testing scripts on master just told me `pass` (and it was, in fact, actually passing, because it was an RTE locally as I described, instead of the crash we saw on the bots). And yes, I rebuilt on each commit I tested (IIRC, they were then-current master, the commit where it started failing, and a handful of commits before the commit where it started failing on the bots).

**Comment by aam** [comment]
The test turned red on buidlbot dashboard. It looks like it's been flaky, but no is positively crashing.
