### ISSUE TITLE
Inconsistent Analysis for implicit-casts

### ISSUE THREAD

**Issue by Pacane** [dart-lang/sdk#37518]
```
❯ dart --version
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "linux_x64"
```

analysis_options.yaml has implicit-casts set to `false`

The analyzer gives me a warning on this.
```dart
  Map<String, dynamic> a() {
	var a = {};
    return a;
  }
```

This doesn't give a warning.
```dart
  Map<String, dynamic> a() {
    return {};
  }
```

Both functions crash at runtime because the `Map<dynamic, dynamic>` isn't a subtype of `Map<String, dynamic>`.

Is that normal behaviour?

Example gist. https://dartpad.dartlang.org/2c775766dbe5898c644f807700fa111e

**Comment by vsmenon** [comment]
Note, the second one doesn't crash at runtime (comment out `b()` in your dartpad example).

Dart has (limited) downward contextual type inference.  When you write the map literal without explicit types (i.e., `{}` instead of `<S,T>{}`), Dart will attempt to infer a type from the outer context.  For a `return` statement, it'll use the return type.  For `var a = {}`, it doesn't see any type.  Note, you could write `Map<String, dynamic> a = {}` or `var a = <String, dynamic>{}` to get the right type.
