### ISSUE TITLE
KBC-INT-ReleaseX64 JIT-ReleaseX64 false divergence

### ISSUE THREAD

**Issue by feli-citas** [dart-lang/sdk#37574]
KBC-INT-ReleaseX64 - JIT-ReleaseX64: !DIVERGENCE! 1.13:1174450773 (output=false)

possible timeout while fuzz testing due to bytecode generation

On Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz:
KBC-INT-ReleaseX64: 3.689 + 0.116 = 3.805 seconds
JIT-ReleaseX64: 0.192 seconds

**Comment by devoncarew** [comment]
@feli-citas, when opening an issue, if you know the area if should go into, please assign the appropriate label (`area-vm` for instance). It'll save the issue triagers some time.

**Comment by aartbik** [comment]
I can confirm similar numbers for DEBUG on my desktop (Intel Xeon E5-2690 2.60GHz), reporting user time:

JIT + run: 0m1.501s
AOT compile, run:  0m20.982s, 0m0.064s
Bytecode compile, run:  0m8.169s, 0m1.025s

So it is a bit surprising we would hit the timeout here (since AOT does not excessively time out in our nightly runs).

**Comment by aartbik** [comment]
Felicitas submitted https://dart-review.googlesource.com/c/sdk/+/109682 which will provide a bit more elaborate output for non-output divergences so that next time we don't have to guess what happened. Until then, nothing very actionable in this bug anymore.
