### ISSUE TITLE
JIT-NOINTRINSIFY-ReleaseX64 JIT-STACKTRACEEVERY-ReleaseIA32 true divergence

### ISSUE THREAD

**Issue by feli-citas** [dart-lang/sdk#37573]
JIT-NOINTRINSIFY-ReleaseX64 - JIT-STACKTRACEEVERY-ReleaseIA32: !DIVERGENCE! 1.13:2133853095 (output=true)

```
1.2G	JIT-NOINTRINSIFY-ReleaseX64.out
134M	JIT-STACKTRACEEVERY-ReleaseIA32.out
```

**Comment by aartbik** [comment]
The massive amount of output obscures what is happening. By commenting out the print statements, and printing the actual exception, the divergences become a bit more clear:

JIT DebugIA32:
throws Out of Memory

JIT DebugX64
throws Invalid argument(s): -880

AOT DebugX64
throws Invalid argument(s): -880

**Comment by aartbik** [comment]
So clearly a "false" divergence due to running out of memory in one execution mode. The culprit is the following statement inside a loop (clearly passing in long strings as "padding" is a bad idea).

`var6 = ('+&u\u{1f600}Obv').padLeft(17, (((!(false)) ? (!((!(var2)))) : var3) ? (((~(71)) + ((var9 != var0) ? Float32x4.xwwz : var7[(var3 ? -78 : fld1_1)]))).toString() : var6));
`

which makes the string grow rather quickly (first two iterations below):
```
X2X2X2X2X2X2X2X2X2+&u😀Obv
X2X2X2X2X2X2X2X2X2+&u😀ObvX2X2X2X2X2X2X2X2X2+&u😀ObvX2X2X2X2X2X2X2X2X2+&u😀ObvX2X2X2X2X2X2X2X2X2+&u😀ObvX2X2X2X2X2X2X2X2X2+&u😀
ObvX2X2X2X2X2X2X2X2X2+&u😀ObvX2X2X2X2X2X2X2X2X2+&u😀ObvX2X2X2X2X2X2X2X2X2+&u😀ObvX2X2X2X2X2X2X2X2X2+&u😀Obv+&u😀Obv
```

We had to work around cases like that before (search for "exponentially" in dartfuzz.dart or look for "i" in the API table generator).

@feli-citas perhaps a cool small assignment to make cases like this less likely? We probably want to have the notion of a "small string" as padding parameter?

**Comment by aartbik** [comment]
Here is another one from today's nightly:

 JIT-DebugIA32 - JIT-ReleaseX64: !DIVERGENCE! 1.13:1726486425 (output=true)

` var5 = (((('J\u{1f600}CG').endsWith('m') ? (true ? var0 : (var0 ? true : (false && var0))) : false) ? '' : ('U @T' + 'bBDk\u2665'))).padLeft(33, var5);

**Comment by aartbik** [comment]
This particular padLeft issue fixed by the CL. Note that exponential growth in general due to recursive occurrences is still tracked in https://github.com/dart-lang/sdk/issues/37597
