### ISSUE TITLE
Crashes of  ffi/function_structs_test and ffi/function_test/0 (flaky)

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37629]
We have flaky crashes in the FFI tests, from [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8907026340494291824/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0):
```

/================================================================\
| ffi/function_structs_test broke (Pass -> Crash, expected Pass) |
\================================================================/

--- Command "vm" (took 10.000566s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --random-seed=1621125267 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/ffi/function_structs_test.dart

exit code:
-6

stdout:
TransposeCoordinate(0x51baaa0 {10, 20, 0x51baac0})
returning 0x51baac0
CoordinateElemAt1(0x4534dc0)
sizeof(Coord): 20
coord[0] = {10, 10, 0x4534de8}
coord[1] = {20, 20, 0x4534dc0}
returning 0x4534dd4
SumVeryLargeStruct(0x467a000)
offsetof(a): 0
offsetof(b): 2
offsetof(c): 4
offsetof(d): 8
offsetof(e): 16
offsetof(f): 18
offsetof(g): 20
offsetof(h): 24
offsetof(i): 32
offsetof(j): 36
offsetof(k): 44
offsetof(parent): 48
offsetof(numChildren): 52
offsetof(children): 56
offsetof(smallLastField): 60
sizeof(VeryLargeStruct): 64
vls->a: 1
vls->b: 2
vls->c: 4
vls->d: 8
vls->e: 16
vls->f: 32
vls->g: 64
vls->h: 128
vls->i: 256
vls->j: 512
vls->k: 1024
vls->parent: 0x467a040
vls->numChildren: 2
vls->children: 0x467a000
vls->smallLastField: 1
2048
has parent
has 2 children
returning 2051

stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0xf75b84ef
version=2.5.0-edge.3c05b8199b37b5ed71ed7df2b8c86085cd7ba745 (Wed Jul 24 18:38:43 2019 +0000) on "linux_ia32"
thread=3332, isolate=main(0x454e700)
  pc 0xf75b84ef fp 0xf187edc4 Unknown symbol
  pc 0xf75b84af fp 0xf187edd8 Unknown symbol
  pc 0xf75b5775 fp 0xf187ee10 Unknown symbol
  pc 0xf75af188 fp 0xf187ee20 Unknown symbol
  pc 0xf75af098 fp 0xf187ee38 Unknown symbol
  pc 0xf75aef92 fp 0xf187ee4c Unknown symbol
  pc 0xf75ae28a fp 0xf187ee68 Unknown symbol
  pc 0xf7588d75 fp 0xf187ee80 Unknown symbol
  pc 0xf75adfd8 fp 0xf187ee98 Unknown symbol
  pc 0xf7a00c4d fp 0xf187eec4 Unknown symbol
  pc 0x018ca4a7 fp 0xf187ef38 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
  pc 0x018ca0d4 fp 0xf187ef78 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  pc 0x018cd1da fp 0xf187efb8 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x01900d33 fp 0xf187f0e8 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)
  pc 0x0192dce5 fp 0xf187f138 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x0192e551 fp 0xf187f198 dart::MessageHandler::TaskCallback()
  pc 0x0192eca7 fp 0xf187f1b8 out/ReleaseIA32/dart+0x152eca7
  pc 0x01a489c1 fp 0xf187f1f8 dart::ThreadPool::Worker::Loop()
  pc 0x01a48867 fp 0xf187f228 dart::ThreadPool::Worker::Main(unsigned int)
  pc 0x019bb2a4 fp 0xf187f2e8 out/ReleaseIA32/dart+0x15bb2a4
  pc 0xf7f4d295 fp 0xf187f3a8 /lib/i386-linux-gnu/libpthread.so.0+0x6295
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-optcounter-linux-release-ia32 ffi/function_structs_test


/============================================\
| ffi/function_test/0 succeeded again (Pass) |
\============================================/

--- Command "vm" (took 06.000020s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --random-seed=1877274570 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/ffi/function_test.dart

exit code:
-6

stdout:
SumPlus42(3, 4)
returning 49

stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0xf75af0c0
version=2.5.0-edge.3c05b8199b37b5ed71ed7df2b8c86085cd7ba745 (Wed Jul 24 18:38:43 2019 +0000) on "linux_ia32"
thread=20006, isolate=main(0x44f6700)
  pc 0xf75af0c0 fp 0xf5cbedd0 Unknown symbol
  pc 0xf75af080 fp 0xf5cbede8 Unknown symbol
  pc 0xf75acc82 fp 0xf5cbee0c Unknown symbol
  pc 0xf75abe9c fp 0xf5cbee20 Unknown symbol
  pc 0xf75abd38 fp 0xf5cbee38 Unknown symbol
  pc 0xf75abc32 fp 0xf5cbee4c Unknown symbol
  pc 0xf75aac6a fp 0xf5cbee68 Unknown symbol
  pc 0xf7588d75 fp 0xf5cbee80 Unknown symbol
  pc 0xf75aa9b8 fp 0xf5cbee98 Unknown symbol
  pc 0xf7a00c4d fp 0xf5cbeec4 Unknown symbol
  pc 0x018ca4a7 fp 0xf5cbef38 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
  pc 0x018ca0d4 fp 0xf5cbef78 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  pc 0x018cd1da fp 0xf5cbefb8 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x01900d33 fp 0xf5cbf0e8 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)
  pc 0x0192dce5 fp 0xf5cbf138 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x0192e551 fp 0xf5cbf198 dart::MessageHandler::TaskCallback()
  pc 0x0192eca7 fp 0xf5cbf1b8 out/ReleaseIA32/dart+0x152eca7
  pc 0x01a489c1 fp 0xf5cbf1f8 dart::ThreadPool::Worker::Loop()
  pc 0x01a48867 fp 0xf5cbf228 dart::ThreadPool::Worker::Main(unsigned int)
  pc 0x019bb2a4 fp 0xf5cbf2e8 out/ReleaseIA32/dart+0x15bb2a4
  pc 0xf7f42295 fp 0xf5cbf3a8 /lib/i386-linux-gnu/libpthread.so.0+0x6295
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-optcounter-linux-release-ia32 ffi/function_test/0
```

@sjindel-google @dcharkes

**Comment by sjindel-google** [comment]
I can reproduce both these crashes locally with a handful of runs.

The first crash is only relevant after FFI 32-bit structs (the test is unsupported otherwise). The second crash does not appear to be related to 32-bit structs -- it reproduces before and after.

**Comment by a-siva** [comment]
I am able to reproduce one variant of the crash pretty consistently in precompiled mode:

```
> pkg/vm/tool/gen_kernel --no-aot --platform=out/DebugX64/vm_platform_strong.dill -o /tmp/out.dill tests/ffi/function_test.dart -Ddart.developer.causal_async_stacks=true
> out/DebugX64/dart /tmp/out.dill
```

Fails with the following error:
```
returning 1337
NoSuchMethodError: The method 'FfiTrampoline' was called on null.
Receiver: null
Tried calling: FfiTrampoline(), #0      FfiTrampoline (dart:ffi)
#1      testException (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/tests/ffi/function_test.dart:440:14)
#2      main (file:///usr/local/google/home/asiva/workspace/dart-tot/sdk/tests/ffi/function_test.dart:42:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

SumPlus42(3, 4)

```

**Comment by sjindel-google** [comment]
@a-siva That exception is supposed to be printed. The test throws and catches it, and prints the exception even when it's been caught. The exit code should still be 0.

**Comment by sjindel-google** [comment]
## Problem

This issue is trigged when `FLAG_write_protect_code` is enabled without dual-mapping.
It surfaced as a race condition between the background compiler and the mutator thread:

| Mutator | Background Compiler |
| ------- | ------------------- |
| Running generated code. | Compiling some function. |
|| Requests safepoint to install code. |
| FFICall instruction begins. | 
| Enters safepoint before transitioning to native. ||
| Native code runs, in safepoint. ||
|| Installs code on the same page as the FFICall. |
|| Switches page protection RX -> RW. |
| Returns into Dart code (still in safepoint). ||
| FFICall attempts to exit safepoint. ||
| Generated code to exit the safepoint is not itself executable. Crash.||

This issue uncovers a new constraint that native code (which runs in a safepoint) cannot return or call into generated code directly (in JIT mode with write-protected code and no dual-mapping support).

This bug affects both Dart → native and native → Dart calls.

## Solutions

### Dart → Native

When necessary (`FLAG_write_protect_code && !FLAG_dual_map_code`), we can dispatch through native code through a stub.
Since stub code lives in the VM heap, it will not change protection after an isolate has initialized, since we don't compile more code into the VM isolate.

Instead of this:

```
__ TransitionGeneratedToNative(target_address, FPREG);
__ CallCFunction(target_address);
__ TransitionNativeToGenerated();
```

The generated code would look like this:

```
__ movq(RBX /*callee-saved*/, target_address);
__ movq(TMP, Address(THR, target::Thread::safepoint_and_call_native()));
__ movq(TMP, FieldAddress(TMP, target::Code::entry_point_offset()));
__ call(TMP)
```

The challenge is that we need one volatile non-argument register available to pass the target address and one callee-saved register to save the generated code's return address, since the stack holds arguments and cannot be manipulated by the stub. 
However, we can save additional state in the exit frame if necessary.

### Native → Dart

Native to Dart calls are tricker because we need to manufacture new target addresses during an isolate's lifetime and cannot just point to a VM stub.
Native callbacks live until the end of an isolate, so we can create pages outside the isolate heap which are mapped executable once and never re-used.

#### Allocate instructions outside isolate heap
 
We can allocate the callback's `Instructions` directly outside the isolate heap and point the `Code` object to them. 
This would require that we waste at least one page on each callback, even if its code is less. 
Protections are applied at the page granularity, so we can never mark the rest of the page writable without breaking the callback at the start of the page.

We've observed that the instruction sizes of native callbacks generated by our tests range from 500 - 3000 bytes, so with a page size of 4 KB, we would waste between 7X and 0.33X the trampoline size.

#### Allocate trampolines outside isolate heap

We can save memory by allocating several trampolines of predicable code, which record the callback ID they were generated for and call into the runtime, similarly to the multiple-mapping solution for AOT callbacks. Since callbacks IDs are assigned sequentially, we can predict the trampoline code for callbacks which have not been generated yet, avoiding any wasted memory. However, this solution is more complex and might slightly regress callback performance.

We will likely choose the first solution for now due to its simplicity.

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/111280 fixes the Dart → Native half.

**Comment by sjindel-google** [comment]
Martin pointed out that the GC needs to scan and update embedded pointers in the callbacks' code on IA32, so allocating their instructions outside the heap is not possible.

We'll have to go with the trampolines solution.

**Comment by sjindel-google** [comment]
https://dart-review.googlesource.com/c/sdk/+/111432 addresses the Native → Dart half.

**Comment by sjindel-google** [comment]
I've confirmed in BigQuery that the flaky crashes have stopped.
