### ISSUE TITLE
analysis_options.yaml include tag does not support glob.

### ISSUE THREAD

**Issue by bitsydarel** [dart-lang/sdk#37651]
I defined some lint rules in different yaml files, i tried to include the file in root project analysis_options.yaml but the include tag seems to not support the following pattern:
include: lib/*.yaml

This tracker is for issues related to:
* Analyzer

* Dart SDK Version (`dart --version`)
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOSX

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

**Comment by bwilkerson** [comment]
That is correct. The `include` directive in the analysis options file takes a URI, not a pattern, and can only be used to include the contents of a single file.

We decided not to support including multiple files until there was a strong use case to support the additional complexity that would arise from doing so. So far, this is the only time I've heard of someone wanting to include multiple files. I don't believe that we ever considered supporting patterns, and I'm not sure what that would look like given the requirement that we be able to use URIs.

I'm going to close this as WAI. If you have a strong use case for why you need to include multiple files, and especially for why you need to use patterns rather than just manually list out the files, please open a new issue requesting the enhancement and describing the use case that motivates it so that we can discuss it there.

**Comment by bitsydarel** [comment]
The things is that even manually list out the files is not possible as the include tag can’t be repeated in the same yaml file.

So what happen is that we have a giant analysis_options.yaml with bunch of rules, hard to maintain.

Or is there a way to include mutiple files ?

**Comment by bwilkerson** [comment]
No, sorry, at the moment each file can only include one other. I suppose you could chain the files, but that's might not be significantly better than simply having a single large file.

The file _is_ yaml, so you could add comments between blocks of lints if that helps.

**Comment by LinusU** [comment]
@bwilkerson 

> We decided not to support including multiple files until there was a strong use case to support the additional complexity that would arise from doing so.

I would like to include both `package:flutter/analysis_options_user.yaml` and `package:pedantic/analysis_options.yaml`, is that a good use case? ☺️

**Comment by bwilkerson** [comment]
It's definitely a valid use case. Whether it's a compelling enough use case to get resources assigned to defining and implementing the semantics isn't something I can answer, but I can mention @devoncarew to raise the visibility of the use case.

**Comment by devoncarew** [comment]
> I would like to include both package:flutter/analysis_options_user.yaml and package:pedantic/analysis_options.yaml in a Flutter project, is that a good use case?

I don't think those two sets of lint options have been designed to work together - they're both fairly prescriptive and have conflicting options. I think you'd be better off choosing to base your rule set off one or the other - `flutter/analysis_options_user.yaml` or `pedantic` - and customize that based on local needs.
