### ISSUE TITLE
macOS Catalina kills child process of dart app *if* the dart binary was deleted

### ISSUE THREAD

**Issue by christopherfujino** [dart-lang/sdk#37662]
So this may sound contrived, but it was happening during the `flutter upgrade` flow [see this issue](https://github.com/flutter/flutter/issues/33890). For that particular flow I think I can work around it, but I thought I would document this here. To put it simply, the repro flow is:

1. Start a Dart application
1. Have the app delete the Dart binary it was invoked with
1. Have the app create a child process via `Process.runSync()`
1. The OS will kill the child process

I created a minimal, non-flutter reproduction [here](https://github.com/christopherfujino/catalina-crasher-demo), with a simple Dart app (and somewhat complicated shell script wrapper).

**Comment by mraleph** [comment]
Does it actually kill the child process or it does not allow it to start? 

I have a suspicion that it all fails already at `fork` because OS is trying to perform security checks but the binary is gone. 

I suggest filing Radar issue just in case - because this looks like an OS bug to me and I doubt we can really do anything about this on the Dart side.

**Comment by christopherfujino** [comment]
I agree, there's probably nothing that Dart could do, I just wanted to file this issue to surface it, and help anyone else who potentially runs into it. Feel free to close.

**Comment by a-siva** [comment]
closing per comment above.
