### ISSUE TITLE
Add a field to Loader to indicate that strong null checking is on

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#37683]
When strong null checking is enabled, related warnings become errors (see, for example, [this part](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#errors-as-warnings) of the feature spec), and some optimizations become possible.  We need a compiler flag to enable the strong null checking and the related flag on an internal object, most likely, Loader.

**Comment by johnniwinther** [comment]
Loader now has a `nnbdStrongMode` flag.

This is currently using the non-standard command-line options '--nnbd-strong' since we still have som references to '--strong' that needs removal.

Currently, performing the checks is also guarded additionally by a '--force-nnbd-checks' options. This will be removed when it is not needed to build the nnbd sdk.

**Comment by johnniwinther** [comment]
The `--force-nnbd-checks` flag has now been removed.

**Comment by johnniwinther** [comment]
Errors are now always reported.
