### ISSUE TITLE
Null aware ?? operator hides type

### ISSUE THREAD

**Issue by pasataleo** [dart-lang/sdk#37770]
I don't think this should compile? But it does, the error is only picked up when you run with an uncaught exception:

Uncaught exception:
TypeError: "string": type 'JSString' is not a subtype of type 'int'

```dart
void main() {
  print(getInt());
}

int getInt() => 'string' ?? 0;
```

**Comment by eernstg** [comment]
This is a known issue that will go away.

Here is an explanation about what's going on: https://github.com/dart-lang/dart-pad/issues/1195.

The main point is that (1) it is a large loss of typing precision (due to an upcast based on a least upper bound of unrelated types, followed by an implicit downcast), but (2) this situation will not occur when we introduce non-nullable types (because then we will also require the downcast to be stated explicitly, so you will be made aware of the fact that there is a downcast from `Object`).

You can make the analyzer detect this kind of situation today, by passing `--no-implicit-casts`.
