### ISSUE TITLE
AOT code is 65% slower than JIT on dart_style benchmark

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#37774]
It's expected that AOT is slower than JIT in some use cases, but 65% seems large in this case?

Tested with `Dart VM version: 2.5.0-dev.1.0 (Tue Jul 9 15:27:01 2019 +0200) on "macos_x64"`.

JIT:
```
$ ~/tmp/dart-sdk/bin/dart benchmark/benchmark.dart
Run  #1: 16.13ms ================================================================================
Run  #2: 11.23ms ========================================================
Run  #3: 8.83ms ============================================
Run  #4: 7.47ms =====================================
Run  #6: 7.30ms ====================================
Run  #7: 7.17ms ===================================
Run  #8: 6.93ms ==================================
Run #13: 6.67ms =================================
Run #15: 6.33ms ===============================
Run #17: 6.20ms ===============================
Run #36: 6.10ms ==============================
Run #44: 5.93ms =============================
Run #81: 5.87ms =============================
Best   : 5.87ms =============================
```

AOT:
```
$ ~/tmp/dart-sdk/bin/dartaotruntime benchmark/benchmark.dart.aot
Run  #1: 10.17ms ==================================================
Run  #6: 10.13ms ==================================================
Run  #9: 10.03ms ==================================================
Run #11: 9.83ms =================================================
Run #15: 9.73ms ================================================
Best   : 9.73ms ================================================
```

**Comment by mit-mit** [comment]
cc @cskau-g @mkustermann

**Comment by mkustermann** [comment]
One of the reasons for the big slowness comes from `package:dart_style`s usage of regular expressions.

Regular expressions are currently way slower in AOT than in JIT mode. We use a bytecode interpreter instead of optimized machine code (main reason is that regular expressions can theoretically be generated at runtime - there is no guarantee that patterns are compile-time constants - which means an AOT cannot know the patterns in general).

The main regexp used in this benchmark is `^_?[A-Z].*[a-z]`, defined in [package:dart_style/src/source_visitor.dart](https://github.com/dart-lang/dart_style/blob/master/lib/src/source_visitor.dart#L26):

```dart

final _capitalPattern = RegExp(r"^_?[A-Z].*[a-z]");
...
  static bool _looksLikeClassName(String name) {
    // Handle the weird lowercase corelib names.
    if (name == "bool") return true;
    if (name == "double") return true;
    if (name == "int") return true;
    if (name == "num") return true;

    return _capitalPattern.hasMatch(name);
  }
```

This pattern can also cause a lot of backtracking due to usage of a greedy `.*`.  @munificent Could this regexp be written differently?

We could teach our AOT compiler that compile-time constant patterns supplied to the `RegExp` constructor should be compiled to machine code.

**Comment by mit-mit** [comment]
Optimizing for compile-time constant patterns sounds like a good idea!

**Comment by mkustermann** [comment]
Filed https://github.com/dart-lang/sdk/issues/37774 to track this part.

**Comment by zzjjob** [comment]
expect…

**Comment by mit-mit** [comment]
@zzjjob, can you elaborate?

**Comment by lrhn** [comment]
> Could this regexp be written differently?

Always!

In this case, the backtracking isn't bad. You are unlikely to get non-linear behavior from any implementation. Still, as Martin points out, the greedy match prevents a sub-linear match.

I'd write it as:
```re
^_?[A-Z][^a-z]*[a-z]
```
or 
```re
^_?[A-Z][^]*?[a-z]
```
(which is slightly different from the original because `.` doesn't match line terminators, but I'll assume that doesn't matter). Just replacing `.` with `[^]` should make the original do fewer unnecessary checks.

Or just don't do regexps:
```dart
bool _looksLikeClassName(String name) {   
   if (.... ) ...

  int i = 0;
  if (name.startsWith("_") i++;
  if (name.length < i + 2) return false;
  int firstChar = name.codeUnitAt(i);
  if (firstChar > 0x5b /*Z*/ || firstChar < 0x41 /*A*/) return false;
  while (++i < name.length) {
    int char = name.codeUnitAt(name.length - 1);
    if (char >= 0x61 /*a*/ && char <= 0x7b /*z*/) return true;
  }
  return false;
}
```
(now you only have one problem again).

**Comment by munificent** [comment]
https://github.com/dart-lang/dart_style/pull/835 fixes about half of the performance difference between JIT and AOT. I'm not sure how to profile AOT builds, so I don't know if there is another other low hanging fruit.

**Comment by mkustermann** [comment]
The next thing to notice is that our AOT is very conservative when inlining due to AOT code size. Though we have a flag to tell our AOT compiler to inline more aggressively using `--optimization-level=3`.

On my machine I get:
```
# Product AOT (stripped aot size: 5.7 MB)
Run #90: 11.70ms ===========================================================

# Product AOT --optimization-level=3 (stripped aot size: 7.2 MB)
Best   : 10.50ms ====================================================

# Product/Release JIT (roughly the same perf)
Best   : 8.27ms =========================================
```

So you can get another 10% performance gain via more aggressive optimizations (by accepting the 26% code size increase)

That leaves 21% the AOT would need to improve to reach JIT. Mostly this seems to be caused by our AOT unable to inline:

  * monomorphic call sites for which there could be multiple targets but have only a single target in practice (e.g. `String.codeUnitAt` - in practice it's just `OneByteString`, but it could be also `TwoByteString`/`ExternalOneByteString`/...)
   => Our AOT doesn't do speculative optimizations

  * polymorphic call sites where we actually have multiple targets
   => Our AOT doesn't do polymorphic inlining, but our JIT does (based on runtime feedback)

**Comment by mit-mit** [comment]
Updated results with ``:

```
$ dart run benchmark/benchmark.dart
Run  #1: 10.87ms ======================================================
Run  #2: 9.77ms ================================================
Run  #3: 8.57ms ==========================================
Run  #4: 7.60ms ======================================
Run  #6: 7.33ms ====================================
Run #10: 7.27ms ====================================
Run #12: 6.90ms ==================================
Run #13: 6.83ms ==================================
Run #18: 6.80ms ==================================
Run #20: 6.47ms ================================
Run #27: 6.33ms ===============================
Run #29: 6.30ms ===============================
Run #32: 6.27ms ===============================
Run #43: 6.23ms ===============================
Run #53: 6.17ms ==============================
Run #54: 6.13ms ==============================
Run #56: 6.07ms ==============================
Run #62: 6.03ms ==============================
Run #64: 5.97ms =============================
Run #76: 5.93ms =============================
Run #91: 5.90ms =============================
Best   : 5.90ms =============================

$ dart compile exe benchmark/benchmark.dart
Generated: /Users/mit/tmp/dart_style/benchmark/benchmark.exe

$ ./benchmark/benchmark.exe
Run  #1: 7.00ms ===================================
Run  #3: 6.97ms ==================================
Run  #8: 6.93ms ==================================
Run #21: 6.90ms ==================================
Run #25: 6.87ms ==================================
Best   : 6.87ms ==================================
```

**Comment by mit-mit** [comment]
@mkustermann this looks close enough that we can close this issue?

**Comment by jamesderlin** [comment]
#39260 is another issue about regular expressions being slower with AOT than JIT; the differences reported in that issue seem worse than being 65% (even with Dart 2.12.1).

**Comment by mit-mit** [comment]
Given we've identified the source of this (none-optimized regexp expressions), let's track this in the specific bug for that: https://github.com/dart-lang/sdk/issues/37785
