### ISSUE TITLE
RegExp start matching from specified index

### ISSUE THREAD

**Issue by pd4d10** [dart-lang/sdk#37829]
Is there any API to start matching from specified index, like `lastIndex` in JavaScript?

For example, match `cd` from specify index:

```js
// JavaScript
const r = /cd/g
console.log(r.exec('abcd')) // ['cd']

r.lastIndex = 1
console.log(r.exec('abcd')) // ['cd']

r.lastIndex = 2
console.log(r.exec('abcd')) // ['cd']

r.lastIndex = 3
console.log(r.exec('abcd')) // null
```

I found `matchAsPrefix` method but it seems not work as above. It gets result only when the matched result start is exactly equal to specified index.

```dart
// Dart
var r = RegExp(r'cd');
print(r.matchAsPrefix('abcd')); // null
print(r.matchAsPrefix('abcd', 1)); // null
print(r.matchAsPrefix('abcd', 2)); // Instance of '_RegExpMatch'
print(r.matchAsPrefix('abcd', 3)); // null
```

**Comment by lrhn** [comment]
There is no direct API to find a single match after a specific start position.
You can use `r.allMatches("abcd", 1).first` instead.
If you only need the position of the match, you can use `"abcd".indefOf(r, 1)`.

The `matchAsPrefix` is deliberately giving you the ability to *not* search forward for a match.
Together, `matchAsPrefix` and `allMatches` allow you to search or not search from any position.
The API of `Pattern` is very small because it is also implemented by `String`, so it shouldn't conflict with the string members.

**Comment by pd4d10** [comment]
Clear enough. Thanks for the quick reply
