### ISSUE TITLE
[vm/ffi] Allow struct classes to override sizeOf

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37842]
Since all operations on structs are dispatched to the getters/settings (instance methods which can already be overriden) and the auto-generated `#sizeOf`, we can allow users to define custom struct classes by overriding `sizeOf`.

This would allow, for example, defining structs with different behavior (e.g. different fields) on different platforms.

**Comment by dcharkes** [comment]
> This would allow, for example, defining structs with different behavior (e.g. different fields) on different platforms.

This would not allow people to access those fields right? Only to `allocate` the correct amount of memory and use `elementAt`. Or is there a way we can enable accessing fields which have different offsets or might not exist on various platforms?

**Comment by sjindel-google** [comment]
You could write the fields by hand, or delegate them to different (generated) implementations depending on the platform.

**Comment by mkustermann** [comment]
By allowing user-defined `sizeOf`, we also allow user-defined layout (i.e. number of fields, type of fields, offset/alignment of fields).

In order to generate the right machine code for `Dart -> C` and `C -> Dart` trampolines the VM has to know the exact struct layout for passing structs by value for the current ABI.

How would such struct classes work with by-value calls?

**Comment by sjindel-google** [comment]
I had imagined that there might be some other functions in addition to `sizeOf` which describe the struct layout. But it's a very explicit and heavy-weight solution.

**Comment by mkustermann** [comment]
IMHO we should remove this from the ffi MVP project and consider closing if we don't intend to implement this.
