### ISSUE TITLE
[Phase 2 - Tools] dart2js support for Static Extension Methods

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37843]
If the feature is handled by the front end, there may be no dart2js work. Otherwise, dart2js may need to handle any Kernel changes or otherwise add support for this.

**Comment by sigmundch** [comment]
There is almost no dart2js work, except for massaging the names before emitting source-maps so that stack traces are nicer to read. This is desirable, but not a launch blocker.

**Comment by sigmundch** [comment]
names in stack traces are now fixed - we believe there is no other action item in dart2js for this feature beyond testing that the CFE lowering is working properly.

**Comment by vsmenon** [comment]
Anything left here for D26?

**Comment by sigmundch** [comment]
Don't think so. The only thing is to have validation that there are no dart2js specific test failures. We are not aware of any at this time, but it would be good to validating.

Rather than duplicating this work across teams (since very often failures are common due to CFE or test issues), can we coordinate how we triage the remaining failures?
