### ISSUE TITLE
Analyzer is missing error for getter/setter assignability in extension methods

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37856]
Analyzer is missing the check for assignability of a getter and setter in an extension method, as tested [here](https://dart-review.googlesource.com/c/sdk/+/112645/9/tests/language_2/extension_methods/static_extension_setter_getter_assignability_error_test.dart).

**Comment by stereotype441** [comment]
@leafpetersen the initial attempt to fix this bug accidentally swapped the roles of getter and setter (it checked that the getter type was assignable to the setter type rather than the other way around).  Would you mind adding a language_2 test that verifies that the order?  (I guess it will have to be an NNBD-related test, since the order only matters when NNBD is enabled).  I want to make sure that we have the necessary test coverage to ensure that the CFE team implements the check in the same way

**Comment by leafpetersen** [comment]
I will add a test, but want to resolve a couple of questions about how we organize these tests first.  Expect an email shortly.

**Comment by bwilkerson** [comment]
The initial fix for this bug was correct (the proposal reversed the order used in the language spec and has been updated). https://dart-review.googlesource.com/c/sdk/+/113041

**Comment by eernstg** [comment]
@stereotype441 wrote:
> accidentally swapped the roles of getter and setter (it checked that the
> getter type was assignable to the setter type ...)

@bwilkerson wrote:
> The initial fix for this bug was correct

I'm not quite sure how these two comments interact, but looking at https://dart-review.googlesource.com/c/sdk/+/113041, the intended property seems to be "the getter return type is assignable to the setter parameter type". This is also the direction which is specified in the language specification (since a07b2a10c6da58e0f3c461d778e51b128e2772a5).

Of course, with a symmetric assignability rule it makes no difference, but given that NNBD changes assignability such that it isn't symmetric, it makes sense to consider whether we should duplicate the requirements on getters/setters such that it stays symmetric.

I created https://github.com/dart-lang/language/issues/531 to clarify this issue.

**Comment by bwilkerson** [comment]
At the time that Paul's comment was written the proposal stated the opposite order for comparison than what the spec contained. Leaf updated the proposal to match the spec, making the original implementation correct.

**Comment by eernstg** [comment]
OK, thanks! It might still be desirable to require assignability in both directions, and dart-lang/language#531 would still serve to clarify that.
