### ISSUE TITLE
WASM FFI

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#37882]
Tracking bug for work on supporting WASM libraries in Dart.

**Comment by mnordine** [comment]
Does wasmer have support for interface types, like wasmtime? 

https://hacks.mozilla.org/2019/08/webassembly-interface-types/

**Comment by liamappelbe** [comment]
I don't think so, but it sounds like this is an early stage proposal, so we probably shouldn't rely on it yet.

I investigated both wasmtime and wasmer (as well as some other stuff), and the reason I chose wasmer is that it's way easier to integrate with C++. I'm still just prototyping though.

**Comment by syrusakbary** [comment]
Super excited to see this going! Let us know if we can be of any help :)

**Comment by greatGregLiu** [comment]
how about these? 
https://www.youtube.com/watch?v=Qn_4F3foB3Q

Standardizing WASI: A system interface to run WebAssembly outside the web: https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/

WebAssembly Interface Types: Interoperate with All the Things!: https://hacks.mozilla.org/2019/08/webassembly-interface-types/

**Comment by mraleph** [comment]
For everybody tracking this issue. We are currently evaluating how to move multiplatform Dart<->WASM interop forward. Similarly to our FFI work we would like to collect some examples of code that people would like to use in their Dart applications via WASM. So if you have one that is open source please leave a comment here or on #37355 with a link and which platforms you would like to use it on (Flutter on iOS/Android/Desktop/Web, Dart Web). Thank you.

**Comment by maks** [comment]
@mraleph Thats great news!
One of my initial use cases would be to use the [existing emscripten port for libgit](https://github.com/libgit2/libgit2/pull/4400) compiled to WASM to avoid the need of having to build  separate native libs for every platform the Flutter app using the lib needs to run on (eg. Android, iOS, MacOS, Linux, etc)

**Comment by kaikai4989** [comment]
@maks Great to know! I have a quick question: does your Flutter app run on Web? If the app is only on non-Web platforms (Android, iOS, ...), it seems Dart FFI can support your use cases.

**Comment by maks** [comment]
@kaikai4989  well yes I could use FFI, but that's the reason I want to use WASM is as I said to **avoid** having to build the native lib to use with FFI for android (NDK), iOS, Linux, MacOS, etc
That was why I posted, that I think one of the use cases for people will be using WASM instead of FFI to avoid the need to build native shared libs for every platform they want to support with their Flutter app. Being able to also run on web is for me just an added bonus of using WASM.

**Comment by sffc** [comment]
In addition to the portability aspect, WASM brings sandboxing/security guarantees as well as a fully managed memory model that you don't get with FFI.  WASM is simply the better, more secure, and more future-proof option for client-side shared libraries.

**Comment by hterkelsen** [comment]
We are currently using [CanvasKit](https://skia.org/user/modules/canvaskit), which is [Skia compiled to WebAssembly using emscripten](https://github.com/google/skia/blob/master/modules/canvaskit/canvaskit_bindings.cpp), in Flutter for Web.

[We use CanvasKit](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/compositor/canvas.dart) by loading the JavaScript wrapper script and calling into it with `dart:js` (since we're developing a Dart SDK library `dart:ui` we can't use `package:js`). `dart:js` has significant performance downsides caused by encoding and decoding all of the arguments and return values and copying buffer contents.

If we had direct access to the WASM, we could avoid having to use the wrapper script and JS interop.

**Comment by petersalomonsen** [comment]
@maks WASM support for libgit2 is maintained here:

https://github.com/petersalomonsen/wasm-git

**Comment by pparikhatliaison** [comment]
Why is pubspec for wasm package locked for 2.10.0 sdk: '>=2.10.0-0 <2.10.0'?

**Comment by liamappelbe** [comment]
No good reason. I'll remove that restriction before I publish it.

**Comment by liamappelbe** [comment]
We plan to publish soon, but it's an experimental package. The initial implementation is only for desktop platforms (windows/mac/linux), so no web support yet.

I'm not quite sure what you mean by "compatible with ffi". package:wasm is built on FFI, so I guess you could use both Wasm and FFI in the same project.

**Comment by maks** [comment]
Would it be possible to try this package out now with some sort of dart runtime flag like we had before null-safety was released or is the only way to compile the Dart SDK locally? 
Also are there any public plans on when this package will be available for general use?

**Comment by liamappelbe** [comment]
No runtime flags are required. We moved package:wasm to its own repo: https://github.com/dart-lang/wasm. We're publishing soon, but if you're really keen I suppose you could clone that repo.

**Comment by mit-mit** [comment]
This package has been published, see:

https://pub.dev/packages/wasm

https://medium.com/dartlang/experimenting-with-dart-and-wasm-ef7f1c065577
