### ISSUE TITLE
[Phase 2 - Tools] Dartdoc support for Static Extension Methods

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37888]
This tracks the implementation of dartdoc support for static extension methods.

**Comment by keertip** [comment]
dartdoc issue - https://github.com/dart-lang/dartdoc/issues/2001

**Comment by vsmenon** [comment]
@keertip - anything left to do here?  The above dartdoc issue is closed now.

**Comment by natebosch** [comment]
Dartdoc does not work with extension methods unless they are not exported and don't contain doc reference links.

https://github.com/dart-lang/dartdoc/issues/2033
https://github.com/dart-lang/dartdoc/issues/2032

I don't think we necessarily need to keep this issue open since we have tracking elsewhere.
