### ISSUE TITLE
Only copy language_model into Dart SDK for Flutter distribution

### ISSUE THREAD

**Issue by lambdabaa** [dart-lang/sdk#37908]
We've decided that we only want to include the language_model CIPD dependency in the Flutter Dart SDK distribution.

/cc @athomas @bkonyi

**Comment by athomas** [comment]
At a high level, I believe we need to create a GN variable that defaults to false and disables the changes landed in 9ecd475c03a64bf26a31ef56661d914282dcb720 and is set to true on the Flutter side.

@bkonyi Do you know if we do something similar already?

**Comment by bkonyi** [comment]
If we only want this dependency in Flutter we probably just want to remove any reference to the language_model from the Dart SDK repository and then update the DEPS in flutter/engine to pull the CIPD dependencies. If we do that, we won't need to add a variable to the GN files which is always false for the Dart SDK.

**Comment by athomas** [comment]
The real decision was that the language model shouldn't be included in the SDK distribution. Keeping it in the DEPS would allow testing in the SDK repo. Otherwise all automated tests would need to happen on the Flutter side. That's why I suggested to keep the dependency but don't copy it in the SDK distribution.

**Comment by lambdabaa** [comment]
It sounds like there was an offline discussion to back off from this decision to keep consistency between Dart & Flutter and that the size increase is tolerable for now while I investigate shrinking model size further. /cc @dgrove @devoncarew @mit-mit
