### ISSUE TITLE
Zero fill left shift operator "<<" is getting unexpected value

### ISSUE THREAD

**Issue by everton-e26** [dart-lang/sdk#37917]
I'm using an algorithm to decode a polyline that has a line with the folowing code:

`(3 & 0x1f) << 30` 

running this line in dart results in: `3221225472`

but if run in javascript results in: `-1073741824`

The resulting javascript code value is as expected and correct. I would like to know if the use of this operator in dart is correct?

I apologize if this is not the proper repository for this issue

**Comment by everton-e26** [comment]
The negative result comes from Javascript running on browser console or nodejs. 

I found this bug because I'm "translating" a Javascript library to Dart.

**Comment by lrhn** [comment]
The Dart result is actually correct because Dart on JavaScript defined its shift operations that way.

Dart integers used to be arbitrary precision integers (what is currently retained as the separate type `BigInt`), and it does not make sense to have both `>>` and `>>>` on arbitrary precision integers.
Compiling Dart to JavaScript, without big integers, meant making some compromises. All JavaScript bitwise operations (`|`, `^`, `&`, `~`, `>>`, `<<`) would first truncate to a signed 32-bit number, then perform the operation, and return a signed number. The `>>>` operation was different in that it returned an unsigned 32-bit number. 
Since Dart did not have both `>>` and `>>>`, we had to pick one behavior for `>>`. One of the factors were the speed of cryptographic functions, and to help those, it was chosen that all Dart bitwise operations compiled to JavaScript should return an unsigned number.

That is what you see now, Dart returning that unsigned interpretation of the 32 bits of the result.

C# gives you a negative result because the C# type here is a signed 32-bit integer. If you change the code to:
```C#
long x = 3;
x = x << 30;
Console.WriteLine(x);  // writes positive number.
```

The Swift result is what it is because Swift uses 32- or 64-bit integers depending on platform, and you are likely on a 64-bit platform.

**Comment by everton-e26** [comment]
Thanks for your explanations.

The algorithm I am implementing needs to be signed 32-bit int, so I found a workaround using the **fixnum** package (https://pub.dev/packages/fixnum)
