### ISSUE TITLE
How can I get analyzer/fasta to report compile errors in extensions?

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#37945]
I'm working on adding dartfmt support for extension methods. I'm using analyzer 0.38.1 and front_end 0.1.23 and so far it looks like it's parsing them and giving me good ASTs. Yay!

I have an extension that erroneously declares a field:

```dart
extension A on B {
  var a = 1;
}
```

In this case, I expect analyzer to report a syntax/compile error, which dartfmt will report to the user and abort formatting. Instead, it just silently gives me an extension with all of the fields removed.

Is there a setting I can turn on for this?

**Comment by bwilkerson** [comment]
No, there's only one flag for everything.

When I paste that into a package that has the experiment enabled (and add a declaration of `B`), I see the following error in the IDE:
```
error: Extensions can't declare instance fields. (extension_declares_instance_field at [test_package] lib/test.dart:41)
```
(ignore the line offset, there was other code in the file)

Unfortunately, that isn't a parse error. The grammar in the proposal just says that the body of an extension consists of `memberDeclaration*`, which doesn't preclude instance fields or constructors. (Static fields are allowed, so dartfmt might want to just deal with instance fields anyway.)

**Comment by stereotype441** [comment]
@munificent I'm surprised that you're seeing an extension with all of the fields removed.  What I would expect, since the formatter only asks the analyzer to parse and not to do any further analysis, would be that you would see the illegal field in the AST, and so you could format it normally, just as you would format any other code that had a non-parse-related error.

In fact, we definitely don't want the fields to be removed from the AST, because a lot of other analysis features (completion, quick fixes, etc.) rely on having an AST that completely describes the code, even if there are errors.  If it's the analyzer that's dropping the fields, I'm interested in investigating. Do you have a repro you could upload somewhere?

**Comment by munificent** [comment]
> What I would expect, since the formatter only asks the analyzer to parse and not to do any further analysis, would be that you would see the illegal field in the AST

Maybe it's in there somewhere and I'm not handling it right. I haven't dug into it much. Here's an example I saw:

```dart
The formatter produced unexpected output. Input was:
extension A on B {
  var a = 1;
  b() {}
  c() => null;
  get d {}
  get e => null;
  set f(value) {}
  set g(value) => null;
  var h = 1;
}

Which formatted to:
extension A on B {
  b() {}
  c() => null;
  get d {}
  get e => null;
  set f(value) {}
  set g(value) => null;
}
```

The primary issue was that I'm not getting an error reported that I expected to show up. But I suppose a valid approach might be to have dartfmt actually format variable declarations inside extensions even though they are compile errors. Formatting other kinds of broken code is hard because it's not even clear how you would format it. But, in this case, the formatting is obvious.

> Do you have a repro you could upload somewhere?

For you, sure. :)

Clone https://github.com/dart-lang/dart_style/tree/wip-extension-methods. Then run `dart example/format.dart`. That's the code I mentioned in my comment here. You can also run the tests `pub run test test/formatter_test.dart` to run some other extension method tests. (Don't worry about failures, though, this is WIP.)

**Comment by stereotype441** [comment]
It looks like the analyzer is reporting the errors in the AstBuilder, and dropping the fields from the ASTs.  It's doing a similar thing with constructors and abstract methods that it sees in the extension declaration.  I believe what it should do instead is the same thing that all the other AstBuilder error detection logic does: report the errors but go ahead and include the erroneous code in the ASTs, to aid in error recovery.  Not only will this allow the formatter to format an extension with illegal fields, it means all the other analyzer features (such as completions) will still mostly work.

I started to prototype this in https://dart-review.googlesource.com/c/sdk/+/114380/1, but it's failing some tests because the presence of the illegal members in the AST is causing later crashes in the analyzer.  @bwilkerson, does this sound like a reasonable idea to you?
