### ISSUE TITLE
Enum.SomeValue.toString() doesn't return actual value

### ISSUE THREAD

**Issue by viratshukla** [dart-lang/sdk#37980]
Currently If I try to send a param as string, its sending wrong values.
like - enum SomeEnum {AAA, BBB}

Now If I try SomeEnum.AAA.toString() 
I get 'SomeEnum.AAA'

Actually I should get 'AAA'

Please fix this

**Comment by lrhn** [comment]
The *value* of an enum is the object, not the string. Mxing the *source name* `AAA`, which would be represented at run-time by the symbol `#AAA`, and a string containing the letters `"AAA"`, is error prone and something we *try* to avoid. They are not the same, and should not be expected to be the same.

It would be nice to be able to control the `toString` of enums, but reflecting the source name at run-time is not necessarily the correct approach. For example, the style guide recommends lowerCamelCase for enum values, but you might want SCREAMING_CAPS or lower_snake_case for the strings, or strings that are not valid Dart identifiers at all.

That said, we *do* reflect the name as *part* of the current `toString` (and exacerbate the issue by reflecting the class name too). I would be happy to stop doing that, however ...

Changing the `toString` value is a breaking change because existing code relies on parsing the current `toString` return value to extract the source name. We can't just do that.

I hope to *one day* be able to improve Dart enums, and at that point we might be able to change the `toString` too.

**Comment by bernaferrari** [comment]
Fixed on Dart 2.15, now there is `SomeEnum.name()`.
