### ISSUE TITLE
Problems with analyzer error messages for INVALID_OVERRIDE

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#37993]
I'm pretty sure this used to give a better error message a few months ago:

```
class A	{
  int add(int a, int b) => a + b;
}

class B	extends A {
  @override
  int add();
}

void main() { }
```

Now it says:

```
  error • 'A.add' ('add') isn't a valid override of 'B.add' ('add') • test.dart:5:7 • invalid_override
  error • 'B.add' ('int Function()') isn't a valid override of 'A.add' ('add') • test.dart:6:3 • invalid_override
```

The first error message is entirely bogus.

The second error message is fine up to the second parenthetical, which just repeats the name of the method instead of giving its signature.

**Comment by vsmenon** [comment]
@stereotype441 - I can repro in the latest Dart pad - this does look like a regression.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/117284 fixes the messages. The duplication and the incorrect location are still outstanding issues.

**Comment by eernstg** [comment]
@Hixie wrote:
> The first error message is entirely bogus.

The situation here is similar to the one described in #36191, and in both cases it is indeed confusing when we get an error message of the form "`Superclass.m` isn't a valid override of `Subclass.m`". We'd normally expect the subclass declaration to override the superclass declaration, not the other way round.

However, this kind of check _is_ justified.

Regular override relationships are checked for each case where a member declaration _D2_ overrides another one _D1_ (for instance, when _D2_ is declared in a class `B implements A`, and _D1_ is declared in `A`). However, there is also another kind of override check, which takes place when it is verified that each concrete class has an implementation of each of the members in its interface, i.e., that it fully implements its interface. And this second kind of override check can be "the other way round".

In the given example the concrete implementation `A.add` is inherited by the concrete class `B`, and this means that the member signature `int add(int, int)` must be a correct override of the member signature `int add()` that was added by an abstract declaration in `B`, and it's not a correct override.

I think the problem here is that the "is fully implemented" override check has no extra wording, so we don't get any hints at all why there would need to be an override relationship from a subclass declaration to a superclass declaration (that is, "upside down"). We just treat the "fully implemented" check the same as any other override check.

Maybe the error messages associated with the "fully implemented" check could use a different wording, maybe saying that it isn't correct to _inherit_ `A.add` into `B` because it doesn't correctly override `B.add`?

**Comment by srawlins** [comment]
Thanks for the explanation, @eernstg !!
