### ISSUE TITLE
dart does not report an error when path is not valid

### ISSUE THREAD

**Issue by zeroomega** [dart-lang/sdk#38007]
This tracker is for issues related to:
I think it is related to the **Common Front End** since both dart and dartanalyzer exhibit this issue.

* Dart SDK Version (`dart --version`)
Dart VM version: 2.5.0-edge.f7902889b6e30a8b9d71416e1facf3c509aad06f (Mon Aug 19 20:43:02 2019 +0000) on "linux_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux x64

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A

When I run dart on an invalid path, it return successfully without issues, e.g.

I have a directory contains only `main.dart` in my cwd, when I run

```dart lib/../main.dart```

it succeed without issue even though the directory `lib` does not exist. The path is consider as invalid as all other posix commands will fail, e.g.:

```
file lib/../main.dart
lib/../main.dart: cannot open `lib/../main.dart' (No such file or directory)
```

Dart should report an error in this scenario to be consistent with other tools.

c.c. @petrhosek

**Comment by mraleph** [comment]
Note that `dart` accepts URI rather than classically file paths (this means for example that things like `dart package:foo/bar.dart` work out of the box). So in this context `lib/../main.dart` is treated as a relative URI rather than relative file path.

So I don't think comparison with classical tools really applies (none of them take URIs).

Given this I lean to declare this working as intended.
