### ISSUE TITLE
Dart support for Arduino

### ISSUE THREAD

**Issue by CorvetteCole** [dart-lang/sdk#38142]
I am currently working on building support for compiling to Arduino in Dart. I am just posting this issue to check if there has been any work on this front that I can base off of. Feel free to close this issue if not, a pull request will come later on adding arduino support regardless.

Thanks

**Comment by mit-mit** [comment]
The now discontinued Dartino project (https://github.com/dartino/sdk) was an earlier attempt at running Dart with a custom compiler and runtime targeting embedded devices. What kind of approach do you have in mind?

cc @mraleph

**Comment by mraleph** [comment]
Closing this issue as no action is expected on our side.

**Comment by TheLastGimbus** [comment]
Hey @CorvetteCole, how it went? I googled for this, and this issue seems to be only mention for it in *the internet* - very weird - Dart would be **so awesome** on Arduino! All async features would solve pretty much *main* problems that you run into when trying to do *anything* - many people end up pretty much impelemnting their own event loops because they can't just use a `delay` :roll_eyes: 

Did you at least see if dartino/sdk is anyhow usable/compile-able :eyes: ?

**Comment by CorvetteCole** [comment]
@TheLastGimbus I made some progress with getting Dart to run on the ESP32 platform actually, but sadly have not worked on it in awhile as I've been quite busy with other projects and life in general. I would LOVE to have most of Dart at my fingertips on an ESP32.

I had the basics going on the ESP32, but there were lots of weird bugs and it was nowhere near stable

**Comment by TheLastGimbus** [comment]
Good to know! Yeah, ESP32 is probably more realistic to run on than normal Arduino Uno :laughing: Tho it would be super cool to have it, it would probably require *a lot of* work (as I recently learned from reading issues about efforts to compile Dart to WebAssembly)

We need to look at something like https://tinygo.org/ or maybe Rust...

**Comment by andresruizdev** [comment]
Hello, I'm browsing a little about use dart in ESP8266 or ESP33, any news about that? That will be nice. Thank you

**Comment by CorvetteCole** [comment]
not from me! I've kind of given it up for now. Was a fun hobby but am too busy to work on it these days!
