### ISSUE TITLE
Subclass/superclass constructor parameter name collision

### ISSUE THREAD

**Issue by jtlapp** [dart-lang/sdk#38178]
I would expect every one of the following subclasses to pass a non-null argument to its superclass, but oddly, `Subclass1A` passes null. The others are correct.

There seem to be two necessary factors to producing the error: (1) the subclass and superclass parameter have to have the same name, and (2) the superclass constructor parameter has to initialize an instance variable. Change either and the problem goes away, as demonstrated:

```dart
class Superclass1 {
  Superclass1({this.superParam}) { // instance variable parameter
    var what = (superParam == null ? "null" : "non-null");
    print("${this.runtimeType.toString()} passed $what");
  }
  
  String superParam;
}

class Superclass2 {
  Superclass2({String superParam}) { // method argument only
    var what = (superParam == null ? "null" : "non-null");
    print("${this.runtimeType.toString()} passed $what");
  }
}

class Subclass1A extends Superclass1 {
  Subclass1A({this.superParam}) // subclass and superclass have same param name
    : super(superParam: superParam ?? "default");
  
  String superParam;
}

class Subclass1B extends Superclass1 {
  Subclass1B({this.subParam}) // subclass and superclass have diff param names
    : super(superParam: subParam ?? "default");
  
  String subParam;
}

class Subclass1C extends Superclass1 {
  Subclass1C({String subParam}) // param is not saved in an instance variable
    : super(superParam: subParam ?? "default");
}

class Subclass2A extends Superclass2 {
  Subclass2A({this.superParam}) // subclass and superclass have same param name
    : super(superParam: superParam ?? "default");
  
  String superParam;
}

void main() {
  Subclass1A(superParam: null);
  Subclass1B(subParam: null);
  Subclass1C(subParam: null);
  Subclass2A(superParam: null);
}
```

The above code outputs the following:

```
Subclass1A passed null
Subclass1B passed non-null
Subclass1C passed non-null
Subclass2A passed non-null
```

Happens on both:

* DartPad running SDK 2.4.1 on Chrome 76.0.3809.100
* MacOS 10.12.6 running Flutter 1.7.8+hotfix.4, emulating on Android

**Comment by lrhn** [comment]
This is actually expected behavior. You are hitting a very subtle edge-case of the behavior of initializing formals.
The case that gives you weird behavior is:
```dart
class Superclass1 {
  Superclass1({this.superParam}) { // instance variable parameter
    var what = (superParam == null ? "null" : "non-null");
    print("${this.runtimeType.toString()} passed $what");
  }
  
  String superParam;
}

class Subclass1A extends Superclass1 {
  Subclass1A({this.superParam}) // subclass and superclass have same param name
    : super(superParam: superParam ?? "default");
  
  String superParam;
}

main() {
  Subclass1A(superParam: null);
}
```
The class `Subclass1A` has *two* fields named `superParam`, one declared in `Superclass1` and one in `Subclass1A` itself.
When you call `Subclass1A(superParam: null)`, that immediately initializes the `superParam` in `Subclass1A` to `null`, then calls the `Superclass1` constructor with `"default"`.
That then initializes the `superParam` in `Superclass` to `"default"` and executes the body of the constructor.
The body contains `superParam == null`. That occurrence of `superParam` means `this.superParam`, which means that it is a virtual lookup of `superParam` on `this`. That lookup finds the `superParam` of `Subclass1A` ... which is `null`.

An initializing formal like `{this.superParam}` introduces a name for that parameter into the *initializer list* of the constructor, a final variable which allows you to refer to the value even though the *field* is not yet available. That variable is not in scope inside the constructor body. At that point you *can* access the created object, and so you can access the field itself instead. Except if you shadow that field in a subclass, like you do here.

**Comment by jtlapp** [comment]
> The body contains `superParam == null`. That occurrence of `superParam` means `this.superParam`, which means that it is a virtual lookup of `superParam` on `this`. That lookup finds the `superParam` of `Subclass1A` ... which is `null`.

Thank you so much for that detailed explanation. I should have considered that the initializer list is using instance variables when available instead of parameters.
