### ISSUE TITLE
analyzer fuzz crash: factory constructor inside extension

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38202]
```dart
extension E {
  factory S() {}
}
```

```
Unhandled exception:
_ElementMismatchException: Element mismatch in /test/lib/test.dart at extension E on dynamic
Caused by NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: [](0)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ElementWalker.getConstructor (package:analyzer/src/generated/declaration_resolver.dart:743:55)
#2      DeclarationResolver.visitConstructorDeclaration (package:analyzer/src/generated/declaration_resolver.dart:99:60)
#3      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2625:15)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#5      ExtensionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3935:14)
#6      RecursiveAstVisitor.visitExtensionDeclaration (package:analyzer/dart/ast/visitor.dart:845:10)
#7      DeclarationResolver.visitExtensionDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:190:13)
#8      DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:566:13)
#9      DeclarationResolver.visitExtensionDeclaration (package:analyzer/src/generated/declaration_resolver.dart:189:5)
#10     ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3927:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#15     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:45:12)
#16     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:656:31)
#17     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#18     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#19     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#20     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#23     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1260:63)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)

**Comment by MichaelRFairhurst** [comment]
@pq @bwilkerson

**Comment by stereotype441** [comment]
@danrubel has been working on making the parser report the proper error when a factory constructor is found inside an extension method, so it's possible that his work in that area will address this bug.

**Comment by bwilkerson** [comment]
I can reproduce a failure, but I'm getting a very different stack trace:
```
  type 'ExtensionElementImpl' is not a subtype of type 'ClassElementImpl'
  #0      ReferenceResolver.visitConstructorDeclaration (package:analyzer/src/summary2/reference_resolver.dart:138:22)
  #1      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2625:15)
  #2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
  #3      ReferenceResolver.visitExtensionDeclaration (package:analyzer/src/summary2/reference_resolver.dart:189:18)
```
We need to decide what to do about constructors in extensions.

**Comment by stereotype441** [comment]
@bwilkerson 
> We need to decide what to do about constructors in extensions.

In https://github.com/dart-lang/sdk/issues/37945#issuecomment-524920500 I suggested that we change the parser so that it reports constructors found in extensions using beginMethod/endMethod, so that they show up in the AST as (mostly) legal method declarations.  I think that would address the stacktrace you're seeing.  WDYT?

(@danrubel FYI)

**Comment by bwilkerson** [comment]
I think that representing constructors as methods (dropping initializers and other pieces that don't make sense) would probably be fine for analyzer. I'm not sure what, if any, implications that would have for kernel.

That said, treating invalid constructors as methods doesn't _necessarily_ require changes to the parser. (That is, the recovery could be in the listeners.) I prefer having as much recovery as possible in the parser so that our tools are consistent, but I'd want to understand the implications of such a change before making it.

**Comment by stereotype441** [comment]
I'm going to make a call on this and say we should go through with the plan in https://github.com/dart-lang/sdk/issues/37945#issuecomment-524920500.  I also prefer having the recovery as possible in the parser.  There should be zero implications for kernel, because kernel is only generated when there are no compile-time errors.

**Comment by danrubel** [comment]
All of the extension method errors reported in AstBuilder are now parse errors and reported by the parser proper so that it benefits all of CFE. A test created with the source above now passes. Is there something else that needs to be fixed related to this issue or can this issue be closed?

**Comment by bwilkerson** [comment]
After doing a `git pull`, if I add the following to `analyzer/test/src/dart/resolution/extension_method_test.dart`, I still get the failure shown above:
```
  test_x() async {
    await assertNoErrorsInCode('''
extension E {
  factory S() {}
}
''');
  }
```
The error is caused by the fact that we're adding a constructor to the extension. As I understand it, Paul's proposal is that the parser calls the listener as if a method had been defined rather than as if a constructor had been defined.

**Comment by danrubel** [comment]
Ah! My mistake. On it.
