### ISSUE TITLE
Optional parameter List<T> default arguments

### ISSUE THREAD

**Issue by passsy** [dart-lang/sdk#38200]
```dart
void main() {
  final v = Vector<String>();
  print(v.contains());
  // prints: false;
}

class Vector<T> {
  bool contains([List<T> elements = const []]) {
                                    ^--- error
    if (elements.isEmpty) return false;
    // ...
    return true;
  }
}
```

This code works fine but analyzer reports an error with flag `--enable-experiment=non-nullable`.

```
error: A value of type 'List<Null>' can't be assigned to a variable of type 'List<T>'. (invalid_assignment)
```

I do understand that `const []` results in  `List<Null>` since `T` is unknown at compile-time. But default values have to be `const`.

**What is the correct way to define empty Lists as default value?**

This pattern is [used rather often](https://github.com/passsy/kt.dart/search?q=const+%5B%5D&unscoped_q=const+%5B%5D).

--- 

Tested with Dart VM version: 2.5.0-dev.3.0 (Wed Aug 28 18:39:15 2019 +0200) commit ff6ff4e967 on "macos_x64"

**Comment by lrhn** [comment]
Use `const<Never>[]` instead. 

The reason you used `const<Null>[]` as default value was that `Null` was a subtype of all other types, so the list was assignable to all list types. With non-nullable types, `Never` is a proper subtype of `Null`, so it is the new bottom of the type hierarchy, and what you need to use here.

The *type inference* should infer `Never` here instead of `Null` in NNBD-mode, but we haven't implemented everything yet, and this is probably still not fixed.

**Comment by scheglov** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/133880
