### ISSUE TITLE
Error when field from mixin overrides covariant setter (analyzer)

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#38210]
It should be permissible to override a setter having a covariant parameter with a field whose type is a subtype of the setter parameter type. Nevertheless, both the analyzer and CFE report an error when the field comes from a mixin:
```dart
abstract class A {
  void set x(covariant Object y);
}

class M {
  int x;
}

class B extends Object with M implements A {}
```
This is the analyzer issue. The corresponding CFE issue is [here](https://github.com/dart-lang/sdk/issues/38211).

**Comment by eernstg** [comment]
The language specification defines the cases where an instance method parameter is covariant, and the parameter of the setter `x=` of the interface of `B` in the example is indeed covariant. Also, `Object with M` produces a superclass for `B`, and it has no errors. So `B` should be allowed (but code generation may need to add a forwarding method implementation to `B`, such that the dynamic type check on the argument of `x=` will be performed).

A similar issue arises already with a regular class:

```dart
abstract class A {
  void set x(covariant Object _);
}

class B {
  int x; // Same outcome with separate setter/getter declarations.
}

class C extends B implements A {} // Error reported here.
```

Again, this should not be an error. Finally, a similar issue arises if we assemble the properties one by one:

```dart
abstract class A {
  set s(Object _);
}

mixin M0 {
  set s(covariant Object _);
}

mixin M1 {
  set s(int i) {}
}

class C = A with M0, M1; // Error reported here.
class D extends A with M0, M1 {} // Error reported here.
```

Class `C` and `D` should not be flagged as errors. The error message from the analyzer (commit b31566b29793247d0fdb2281a435e87fdae77cd5) shows the issue particularly clearly:

```
ERROR|COMPILE_TIME_ERROR|INVALID_OVERRIDE|/usr/local/google/home/eernst/lang/dart/scratch/201909/n006.dart|14|28|2|'M1.s=' ('void Function(int)') isn't a valid override of 'M0.s=' ('s').
```

This means that it is considered incorrect for `set s(int i)` to override `set s(covariant Object _)`, which is not true.

Note that phrases like `A with M0` and `A with M0, M1` are checked in terms of the corresponding class declaration ([as specified here](https://github.com/dart-lang/language/blob/99a90923195d82de5aef4ca8c119799d64dfdd2a/specification/dartLangSpec.tex#L4421)), which means that `set s(int i)` needs to be checked for override correctness against `set s(covariant Object _)` as if it had been declared "inline":

```dart
abstract class A_with_M0 extends A {
  set s(covariant Object _);
}

abstract class A_with_M0_M1 extends A_with_M0 {
  set s(int i) {}
}
```

It would be expensive to create all these classes and run the static analysis on each of them (including adding import prefixes and handling private names etc. as needed, in order to ensure that the members preserve their meaning), and luckily a local check on the body of each mixin `M`, once and for all, will do the same job for all applications of `M`. But it's still necessary to check at each mixin application that the actual superclass satisfies the `on` constraints, and that it has concrete implementations of members used in superinvocations.

I believe this means that there is a need to do a little extra work at each mixin application: The computation that determines which parameters are covariant must be done relative to the actual superinterfaces of the mixin application, it is not sufficient to take this information directly from the declaration of the member in the mixin.
