### ISSUE TITLE
Inconsistent errors for annotations on aliased setters.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#38352]
The snippet:
```
class Annotation {
  const Annotation(Object obj);
}

class Bar {}

class Foo {
  @Annotation(Bar)
  set Bar(Bar value) {}
}

main() {}
```

passes in DDC but errors in the CFE with:
```
Error: Not a constant expression.
  @Annotation(Bar)
              ^^^
```

This only happens when Bar is the setter. What's the intended behavior here?

**Comment by vsmenon** [comment]
@lrhn @leafpetersen - is the above legal?

**Comment by eernstg** [comment]
`@Annotation(Bar)` needs to be a constant expression (here: invoking a constant constructor) and is in a constant context, and `Bar` is constant, 

> A simple or qualified identifier denoting a class, a mixin or a type alias
> that is not qualified by a deferred prefix, is a potentially constant and
> constant expression.

so there should not be an error.

**Comment by leafpetersen** [comment]
> so there should not be an error.

I think the relevant question is what scope the annotation is resolved against (and for that matter, the type annotation on the argument to `Bar`.

The CFE resolves the `Bar` in the `@Annotation(Bar)` to the setter name (presumably using the instance scope).

It does the same for a use of `Bar` in a static method, by the way, and also for the type of the parameter to the `Bar` setter.

@eernstg is this well specified?  At first glance, I think the CFE is correct at least for the type annotation case.

```dart
class Annotation {
  const Annotation(Object obj);
}

class Bar {}

class Foo {
  static foo() {
    var x = Bar; // Error in CFE, not in analyzer
  }
  @Annotation(Bar) // Error in CFE, not in analyzer
  set Bar(Bar value) {} // Error in CFE, not in analyzer,
}

main() {}
```

**Comment by eernstg** [comment]
> The CFE resolves the `Bar` in the `@Annotation(Bar)` to the setter name

Right, and that is actually what it should do. We have no special exceptions for the placement of metadata in any other scope than the declaration that it is associated with, so in this case it would be in the instance scope, and this means that lexical lookup will find the setter `Bar=`. It should then conclude that there is no `Bar` declaration available, so it's a bit confusing when it says 'not constant' rather than 'no such declaration'.

According to the current specification the static scope is the enclosing scope for the instance scope, and this means that an instance member named `Bar` or `Bar=` would simply not be visible to a static class member.

But I proposed in dart-lang/language#550 that we should replace those two scopes by a single 'body' scope of a class (because the specified behavior was never implemented, and we are very unlikely to want to get it implemented). With that change, the static member would also find the instance setter when it looks up `Bar`, and we'd again get the error 'no declaration named `Bar`'.

So, assuming that we go through with the scope rule change (which matches the current implementations already), the CFE is right in both cases.

**Comment by lrhn** [comment]
The specification explicitly states:
```
The constant expression given in an annotation is type checked and evaluated
in the scope surrounding the declaration being annotated.
```
so the `@Annotation(Bar)` lookup should find `Bar=` in the scope where the declaration occurs.
(At least when we start consistently treating both `Bar` and `Bar=` as both shadowing declarations of either in outer scopes).

I agree that separating the body of a class into into static and instance scopes is a bad idea.
It would mean that:
```dart
const bar = 42;
class C {
  @Annotation(bar)  // no problem because `bar` is not in the static scope.
  static int x;
  @Annotation(bar);  // compile-time error because `bar` is in the instance scope.
  int y;
  int bar;  // in instance scope, not static scope.
}
```
That's crazy talk! One `{...}` block - one scope! Otherwise users won't be able to figure out what's happening.

**Comment by vsmenon** [comment]
What's the TL;DR here?  

If I read this correctly, the original code is a static error (CFE is right), and we need to fix the broken test.  Is that correct?

**Comment by leafpetersen** [comment]
> If I read this correctly, the original code is a static error (CFE is right), and we need to fix the broken test. Is that correct?

Yes, that is correct.

**Comment by vsmenon** [comment]
Ok, refiling as an analyzer error (fyi @stereotype441 - not high pri).  We'll work on fixing g3 tests.

**Comment by scheglov** [comment]
With switching to new `Scope`s in analyzer in 86ec742832a95a26561aa38df6aa4c7bf4e3ced8 we have single scope for class body - no separation on static and instance scopes.
