### ISSUE TITLE
CFE does not provide a way to determine if no-such-method forwarders refer to an external field.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#38400]
Related to: https://github.com/dart-lang/sdk/issues/38398

In that example, `EditorClass.prototype.isExternal` is true, but `MockEditorClass.prototype.isExternal` is false.

The analyzer provides `PropertyInducingElement` as a means for finding out whether or not a getter/setter is external. It's possible I've overlooked something, but Kernel doesn't seem to have a simple path to this kind of information from a `Procedure`.

**Comment by vsmenon** [comment]
Hmm, I don't think the title of this bug is quite right.

The issue here appears to be that we're not getting the most precise `Member`.  E.g., :
with @Markzipan 's example:

```
  var e = MockEditorClass();
  print(e.prototype);
```

the `Member` we get for `prototype` (on `visitPropertyGet`) is the one from the interface `EditorClass`, not the implementation in `MockEditorClass` (which is a NSM forwarder).

**Comment by Markzipan** [comment]
Oooh, good call. If we have a way to see all (or some union of) those members to determine if the behavior should be "external", that would be sufficient. From what I can tell, the `Procedure` that represents e.prototype doesn't have this info.

**Comment by askeksa-google** [comment]
Can you clarify what it is you need from the CFE here?

The fact that `e.prototype` refers to a `noSuchMethod` forwarder is a dynamic property of the value of `e`. So it would seem this has to do with the way such accesses are dispatched at runtime. What is the information which is missing in Kernel for the DDC backend to be able to implement the desired behavior?

**Comment by vsmenon** [comment]
@Markzipan @natebosch - is there a blocker here or can we rework the code?

@askeksa-google - re "The fact that e.prototype refers to a noSuchMethod forwarder" is what we would expect, but are not seeing.  See my comment above.  `visitPropertyGet` provides the member from the interface (and the member is marked external and not an NSM forwarder) not the more precise member from `MockEditorClass` (which is not external but is an NSM forwarder).  Is that intentional?

If `visitPropertyGet` was provided the more precise member (the NSM forwarder, matching the static type of the receiver), we should generate the same in DDK as DDC.

That said, I think mocking an JS interop type with a `prototype` getter is semi-broken in both - this request would change broken DDK behavior to match broken DDC behavior.  So, asking first if we can rework code.

**Comment by askeksa-google** [comment]
What I mean by this being a dynamic property is that the behavior should not depend on what information is statically available at the call site. If I change the body of `main` to
```dart
  EditorClass e = MockEditorClass();
  print(e.prototype);
```
the behavior of the program is exactly the same. It calls `noSuchMethod` in DDC but not in DDK. In this case, the static information at the call site clearly only includes the `prototype` declaration in `EditorClass`. Thus, it would seem that the difference is not caused by how code for the callsite is generated, but rather by how the runtime dispatch is handled.

**Comment by vsmenon** [comment]
You are right that the behavior should not depend on the static type of the receiver - that's why I think both are broken.

In your snippet above, DDC doesn't appear to call NSM either.  

I'm not sure we have an ask on the CFE here yet.  Assigning to @Markzipan to clarify.  (fyi @sigmundch )

**Comment by Markzipan** [comment]
In an ideal case for DDC, the Procedure representing a dispatch to a noSuchMethod handler would be able to tell us if the original method were external. 

However, Vijay's fix here might be good enough for this use pattern: https://github.com/dart-lang/sdk/issues/38398#issuecomment-533611212

In general, mocking JS interop-enabled objects is a poorly defined area.

**Comment by Markzipan** [comment]
@askeksa-google Looking at the more involved case I posted at https://github.com/dart-lang/sdk/issues/38398#issuecomment-534684495, it would be much easier if we had an easy way of either accessing the original interface from a noSuchMethod Procedure (e.g., noSuchMethodTarget) or otherwise finding out if a noSuchMethod Procedure refers to an external procedure. 

Is there an easy way of doing this in CFE right now?

**Comment by askeksa-google** [comment]
In general there might be several such targets. I don't see an easy way of reliably finding all of them, short of searching through all transitive supertypes. You could call `hierarchy.getInterfaceMember` on the direct supertypes to find some of them, but if a direct supertype inherits more than one, you will only find the first one of those this way.

**Comment by Markzipan** [comment]
Okay - we'll patch this by walking up the inheritance tree in DDC. A bit inefficient, but this is an extremely rare use case. Thanks!
