### ISSUE TITLE
consider reducing entry point alignment requirements in AOT mode

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#38452]
We currently align all entry points by 32 when targeting iOS - while default toolchain aligns by 4 (in other words - does not actually align at all beyond natural instruction size).

We should check what Android NDK default alignment is. 

This might squeeze some air from our AOT snapshots. 

/cc @mkustermann

**Comment by mkustermann** [comment]
Aligning the payload of the `RawInstructions` object is actually of very limited use, because a lot of call sites will end up not at the start of the payload:

Switchable calls have the NSM bailout code at the beginning of the payload, the actual function entry is a few instructions into the payload. So it might make more sense to align these function entries instead.

**Comment by mraleph** [comment]
My suggestion is not to align these at all.

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/117683

**Comment by mraleph** [comment]
@rmacnak-google just to check, the alignment now matches default object alignment, so there is more shrinking to get?

**Comment by mkustermann** [comment]
There's a follow-up CL pending in [cl/118181](https://dart-review.googlesource.com/c/sdk/+/118181)

**Comment by mkustermann** [comment]
@rmacnak-google Are you working on a reland of this?

**Comment by rmacnak-google** [comment]
Yes, I have a working version at https://dart-review.googlesource.com/c/sdk/+/119440/, but I want to clean up the math so it's easier to understand.
