### ISSUE TITLE
There is a problem with dart2js usage

### ISSUE THREAD

**Issue by GanZhiXiong** [dart-lang/sdk#38477]
I have a mobile App that I developed with flutter. Now I wanted to do a cross-platform desktop application, and I tried flutter, but it was too immature. Now I'm doing it with electron. I want to reuse dart's code, so I want to convert dart to JavaScript or TypeScript. I only find dart2js, and then I convert dart to JavaScript using the following command in the official web documentation

```
dart2js -O1 -o test.js test.dart
```
test.dart
![image](https://user-images.githubusercontent.com/27394631/65220437-49192600-daed-11e9-943f-c60c2616babb.png)

Generated JavaScript file test.js
![image](https://user-images.githubusercontent.com/27394631/65220497-6948e500-daed-11e9-8cb5-85d465ba511c.png)

---
**It's just a few lines of dart code, and it generates this much JavaScript code, which is not what I wanted.**

**Comment by sigmundch** [comment]
Sorry to hear that you found the flutter ecosystem immature for your purpose. It would be great to get some feedback about your experience to make sure we understand what you found lacking or if there are parts of its documentation that could be improved. I'm no expert on the flutter side of things, but I can find out someone to cc here who can direct your messages, or please feel free to reach out directly to them.

About the emitted code. Dart has very different semantics than JavaScript, so any Dart to JS compiler will generate code that has some extra code to correctly model our language. This means that the generated code sometimes is not as idiomatic JavaScript as what you'd write by hand. For example, Dart Lists are implemented with native JS Arrays, but they don't have the same operations or errors. This initial tax diminishes as the apps get bigger.

We have two compilers that emit JS. [dart2js][] is our whole-program optimizing compiler meant to generate optimized code when assembling large apps. The optimization it has help delete unnecessary code (for some apps this can be as high as 50% of the original code), perform local optimizations and enable Dart to run fast on a JS engine.  Even when disabling most optimizations, it operates as a whole-program compiler and it is not really meant to be used to export code to JS.

There is a separate development compiler called [dartdevc][ddc] or DDC. That compiler does work more modularly and has the ability to generate ES6 modules for each library (unless your libraries form a cycle, in which case you may have one module for an entire strongest connected component of your import graph). The code generated by this compiler might be easier to work with if you are trying to export your app and start something with it. Again, I don't expect it to be as idiomatic as if you wrote it by hand because of the extra Dart semantics, but it may be a good starting point if you are doing a migration afterwards.

The easiest way to access the dartdevc compiler is to use the [webdev commandline tool][webdev]. This tool takes care of splitting apps into modules and invoking the compiler one module at a time. While invoking dartdevc by hand is possible, it gets complicated when you start tracking dependencies between modules and you need to feed the compiler data about what each dependency does. For that reason, I strongly recommend using the webdev tool, and extract the code it generates.

Hope you find these pointers useful! Thanks again for reaching out and for trying out flutter. And please do reach out to the team to see if they can assist on your flutter use case!

[webdev]: https://dart.dev/tools/webdev
[dart2js]: https://dart.dev/tools/dart2js
[ddc]: https://dart.dev/tools/dartdevc

**Comment by sigmundch** [comment]
It seems I originally forgot to mark the issue as closed. Feel free to reach out if you have additional questions.
