### ISSUE TITLE
Autocompletion should perhaps track upcast dynamic function literal parameter types

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38502]
Related to #25490

```dart
void f(List<Person> people) {
  final byName = people.fold({}, (map, next) => map.^); // want to autocomplete "putIfAbsent"
}
```

Here, we're able to infer that the fold is over type `Map`. However, the parameter `a` is inferred to be dynamic. This is correct behavior for the spec, but not ideal behavior.

We can potentially improve this situation while still following the spec. By recognizing the upcast function literal and providing `Map` autocompletions on `a`.

Note that this only works for dynamic. For any other type, suggesting members that are not members of the static type will lead to an error:

```dart
f<T extends num>(T constraintParam, void Function(T) f) { ... }

void main() {
  f(0, (x) => x.bitLength)); // error: bitLength is not a member of num
}
```

Here the correct solution is to make the type parameter (`int`) explicit.

Making *this* better requires probably a lint or a language change.

**Comment by MichaelRFairhurst** [comment]
filed https://github.com/dart-lang/linter/issues/1726 as a linter idea

**Comment by bwilkerson** [comment]
Under Null Safety, `map` is now inferred to be `Object?` rather than dynamic, which means that upcasting wouldn't help here. It isn't clear that there are enough cases left where we could upcast to improve completion to make it worth the effort, so I'm going to close this. If we find one we can always re-open this issue or create a new one.
