### ISSUE TITLE
If two interfaces are not related, the inference via 'is' doesn't work well

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#38564]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Analyzer

* Dart SDK Version (`dart --version`)
2.4.0

* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOS

In the following code, analyzer doesn't consider as a as an instance B.
On the other hand, if B extends from A, it works well.

```
class A {
}
class B {
  void f() {}
}
void f(A a) {
  if (a is B) a.f(); //analyzer said 'f' is not defined in A
}
```

**Comment by lrhn** [comment]
This is behaving as expected. Dart type promotion can only promote to *one* more specific type. It does not have a notion of *`A` and `B`* unless one is a subtype of the other, so in this case it cannot "promote" to `B` without losing the information that the value is an `A`. We never forget the declared type of a variable, so you can only promote to `B` here if `B` is more specific than `A`.

**Comment by tomyeh** [comment]
Sorry, I don't get it. `a is B` ensures `a` also implements `B`. Why we have to cast explicitly in this case?

**Comment by lrhn** [comment]
Because the static type of `a` in `a.f()` has to be one of `A` or `B`. It cannot be both, there is no type in the type system for that. A variable always have exactly one static type.

Since the declared type of `a` is `A`, we will never throw that type away, so the static type of `a` is `A`, and `A` does not have an `f` member.
If `B` extends `A`, then we *can* promote from `A` to `B` without forgetting that it is also an `A`.

Example:
```dart
abstract class A { int g(); }
abstract class B { int f(); }
main() {
  A a = makeA();
  if (a is B) {
    print(a.g());
    print(a.f());
  }
}
class C implements A, B {
  int g() => 37;
  int f() => 42;
}
A makeA() => C();
```
Here the static type of `a` in `a.g()` and `a.f()` is the same type, that type is either `A` or `B` because that's the only types we are aware of in the code `main` code.
If the type is `A`, we cannot call `f`. If the type is `B`, we cannot call `g`.

It would be highly confusing if a variable declares as `A` did not allow calling `g`, so we ensure that that is the case. So, we have to not promote the variable to `B`, which means that you cannot call `f` on it.

**Comment by tomyeh** [comment]
Got it! Thanks for the explanation.
