### ISSUE TITLE
VM/CFE's error text regarding a non-const default value is incorrect.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38568]
Take this example:

```dart
void f([List<int> a = []]) {}
```

Push this through `dart`:

```
$ dart a.dart 
a.dart:1:23: Error: Constant evaluation error:
void f([List<int> a = []]) {}
                      ^
a.dart:1:23: Context: Can't have a non-constant List literal within a const context.
void f([List<int> a = []]) {}
                      ^
a.dart:1:19: Context: While analyzing:
void f([List<int> a = []]) {}
                  ^
```

The bad message is the middle one, "Can't have a non-constant List literal within a const context." As @eernstg says at https://github.com/dart-lang/language/issues/575#issuecomment-455079417, default parameter values must be const, but default parameter values _do not constitute a const context_.

The message causes confusion because users know that writing `[]` or `Duration(minutes: 1)` in a const context will create a const object. So telling a user, in an error message, that a parameter default value constitutes a const context leads the user to believe they can omit the `const` keyword, which is incorrect.

**Comment by askeksa-google** [comment]
It turns out that particular error message is redundant after https://dart-review.googlesource.com/c/sdk/+/117324, which introduces a new error message for this case.

https://dart-review.googlesource.com/c/sdk/+/118982 removes that error message (and the corresponding ones for set and map literals) and reformulates other messages talking about "const context" to say "in a constant expression" instead.

**Comment by srawlins** [comment]
Thanks, @askeksa-google !
