### ISSUE TITLE
Analyzer does not infer type of field initializer with NNBD type.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#38582]
Example:
```dart
class C<T extends Object?> {
  Map<String, T> _values = {};
}
main() {
 C<int>();
}
```
The analyzer run on this program with `--enable-experiment=non-nullable` gives the error:
```
Analyzing initerr.dart...
  error • A value of type 'Map' can't be assigned to a variable of type 'Map<String, T>'. • initerr.dart:2:28 • invalid_assignment
  hint • The value of the field '_values' isn't used. • initerr.dart:2:18 • unused_field
1 error and 1 hint found.
```
The error is wrong. The type inference should have inferred `<String, T>` as type arguments of the map literal, and it does so if the bound is `Object` instead of `Object?`.

**Comment by scheglov** [comment]
How should the [disambiguating algorithm](https://github.com/dart-lang/language/blob/master/accepted/2.3/unified-collections/feature-specification.md#disambiguating-sets-and-maps) work with NNBD? We have `Map<String!, T!>!` and check it against `Map<Object!, Object!>!`, but because `T extends Object?`, `T!` is not a subtype of `Object!`. Here `!` means "none" nullability suffix.

My guess is that we want to see that the context type is any `Map`, and `Map<Object, Object>` is just a way the spec says this. For NNBD case we could use `Map<dynamic, dynamic>` Correct me, please.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/123006

**Comment by eernstg** [comment]
> For NNBD case we could use `Map<dynamic, dynamic>`.

The language specification uses the concept that '`S` implements `T`' where `S` and `T` are types. When `T` is a raw type `G`, this [means]() that there exist type arguments `T1 .. Tk` such that `S` implements `G<T1 .. Tk>`. When `T` is not raw it simply means that `T` is a superinterface (directly or indirectly) of `S`.

In particular, `List<int>` implements `Iterable` and it implements `Iterable<int>`, but it does not implement `Iterable<num>`.

This concept is then used to disambiguate sets and maps as needed for the given example, [here](https://github.com/dart-lang/language/blob/518a7d9e5b46e89f9ad5d323b39348359e17a4e1/specification/dartLangSpec.tex#L8191).

So we actually abstain from making a choice like `Map<dynamic, dynamic>` vs. `Map<Object?, Object?>`, because the point is in any case just that `Map` is a superinterface of the context type closure, and `Iterable` isn't.
