### ISSUE TITLE
quick fix for diagnostic_describe_all_properties

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#38633]
Follow-up from: https://github.com/flutter/flutter/issues/41513#issuecomment-536117462.

@jacob314: feel free to chime in w/ any implementation notes here.  Any heuristics for code generation would be greatly appreciated!

---

Property subclasses to support

* [x] BooleanProperty -- bool (https://github.com/dart-lang/sdk/commit/23aca57eda0697e2832b11f287ff476d63df6c65)
* [x] ColorProperty -- for Color (https://github.com/dart-lang/sdk/commit/0a63bd4b0acef0a1613ddc5f9e536fc6de052a6b)
* [x] EnumProperty -- for any enum class (https://github.com/dart-lang/sdk/commit/512d763b9daf7e6a436055c9d763ff830d35cf65)
* [x] IntProperty -- int (https://github.com/dart-lang/sdk/commit/512d763b9daf7e6a436055c9d763ff830d35cf65)
* [x] DoubleProperty -- double (https://github.com/dart-lang/sdk/commit/512d763b9daf7e6a436055c9d763ff830d35cf65)
* [x] IterableProperty -- any iterable (https://github.com/dart-lang/sdk/commit/0a63bd4b0acef0a1613ddc5f9e536fc6de052a6b)
* [x]  StringProperty -- string (https://github.com/dart-lang/sdk/commit/512d763b9daf7e6a436055c9d763ff830d35cf65)
* [x] TransformProperty -- Matrix4 (https://github.com/dart-lang/sdk/commit/0a63bd4b0acef0a1613ddc5f9e536fc6de052a6b)
* [x] DiagnosticsProperty for any T that doesn't match one of the other cases (https://github.com/dart-lang/sdk/commit/69b612beec0bc632564a7ea5aacd9bdf59ad5e01)

**Comment by bwilkerson** [comment]
@goderbauer Could you send us a couple of before/after pairs? That would likely be very helpful for informing what the fix should do.

**Comment by jacob314** [comment]
I can provide all the before and after pairs.
 https://api.flutter.dev/flutter/foundation/DiagnosticsProperty-class.html
gives a list of all subclasses. 
ColorProperty -- for Color
EnumProperty -- for any enum class
IntProperty -- int 
DoubleProperty -- double
IterableProperty -- any iterable
StringProperty -- string
TransformProperty -- Matrix4
DiagnosticsProperty<T> for any T that doesn't match one of the other cases.

For each case the quick fix is to either add a line at the end of the existing `debugFillProperties` method or to override the `debugFillProperties` method and then add the property. 
For example, for an int property you would add the line
`properties.add(IntProperty('myPropertyName', myPropertyName));`
method or add a new one. The big time savings for the quick fix is otherwise we were finding it was a real pain to for every single property navigate to the debugFillProperties method to add the property. Sometimes it wasn't obvious where the method was and almost all of these migrations are mechanical.

**Comment by bwilkerson** [comment]
That should be fairly easy to automate. Given the amount of work there is it sounds like we should also consider enabling that via dartfix, which could apply the fix in bulk.

**Comment by jacob314** [comment]
There would still be a bit of manual work to make sure the properties have
the right default values and determine whether each property shouldn't be
added or not so lets hold up on dartfix integration.

**Comment by bwilkerson** [comment]
How do you manually determine the default value for a property? Is it possible to statically determine the right default value for a property? Maybe by looking at the field's initializer and/or the constructors?

How do you manually determine which properties to add? I would have assumed that the lint was able to do this in order to not produce false positives. If that's not the case then we should at least be able to add an 'ignore' comment for properties that shouldn't be added. If you do that, then those diagnostics will be suppressed and given that fixes are only applied where a diagnostic is reported, we should still be able to use dartfix after marking the properties that shouldn't be added.

**Comment by pq** [comment]
Video demonstrating the simple/common case...

![diagProps1](https://user-images.githubusercontent.com/67586/66436962-55521e00-e9dd-11e9-84c8-d56df14d1e8f.gif)

🤘 

/cc @jacob314

**Comment by pq** [comment]
For reference: https://github.com/dart-lang/linter/issues/1420.
