### ISSUE TITLE
Migration engine incorrectly makes a local variable non-nullable

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#38637]
When the migration engine is run over the logging package, it incorrectly makes the local variable `parent` non-nullable in the following constructor:
```
factory Logger._named(String name) {
  if (name.startsWith('.')) {
    throw new ArgumentError("name shouldn't start with a '.'");
  }
  // Split hierarchical names (separated with '.').
  int dot = name.lastIndexOf('.');
  Logger parent;
  String thisName;
  if (dot == -1) {
    if (name != '') parent = new Logger('');
    thisName = name;
  } else {
    parent = new Logger(name.substring(0, dot));
    thisName = name.substring(dot + 1);
  }
  return new Logger._internal(thisName, parent, new Map<String, Logger>());
}
```
If the `name` is the empty string, then `parent` will be null when invoking the internal constructor. I believe that the correct migration would be to mark `parent` as being nullable.

This bug causes the engine to make the field named `parent` non-nullable, causing code to be deleted (commented out) that should not have been deleted.

**Comment by bwilkerson** [comment]
@stereotype441

**Comment by stereotype441** [comment]
I believe this is happening due to #38341.  In short, there is a local variable in a test with an inferred type, and that type is inferred to be the same as the type of `parent`.  The test expects its local variable to be non-nullable, and becuase that type is inferred from the type of `parent`, the migration engine is propagating that expectation back to `parent` itself, rather than inserting a null-check in the test, as it should.  See https://github.com/dart-lang/logging/pull/66/files#r323495145 for details.

Once that bug is fixed we can revisit this one and check whether it still occurs.

**Comment by MichaelRFairhurst** [comment]
Highly suspect this is done
