### ISSUE TITLE
Fix reasons include invalid edges

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#38650]
Run the migration engine over the logging package and look at the reasons for the change to line 25:
```
Level? _rootLevel = Level.INFO;
```
The field's initializer is included as one of the reasons, despite the fact that the referenced field is defined as
```
static const Level INFO = const Level('INFO', 800);
```

**Comment by stereotype441** [comment]
We discussed this and we think what's happening is:
- The instrumentation client looks at the node that is the "reason" for a `?` being added
- The instrumentation client looks at the set of edges that are upstream from that node
- It finds edges that would never have caused the node to be marked as nullable.

We think that what we need to do is expose the `NullabilityEdge._isTriggered` query through the instrumentation interface, so that the instrumentation logic can filter out irrelevant edges when figuring out the reason why something was marked as nullable.  @bwilkerson will try this and we'll see how it goes

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/119422
