### ISSUE TITLE
Analyzer: Evaluation of constant expression using multiple libraries throws an exception

### ISSUE THREAD

**Issue by rebaz94** [dart-lang/sdk#38658]
There is an issue in the analysis server that said

>  Evaluation of this constant expression throws an exception

the code that produces is
```
_$AppDatabase(QueryExecutor e) : super(const SqlTypeSystem.withDefaults(), e)
```

```Flutter 1.10.7-pre.91 • channel master • https://github.com/flutter/flutter.git
Framework • revision e8517a434d (15 hours ago) • 2019-09-30 12:45:03 -0700
Engine • revision 1f454c7533
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 132bee48d0)
```

@simolus3

**Comment by simolus3** [comment]
Some more information on this: [Here](https://github.com/simolus3/moor/blob/6993b265326dc92079dbfe948f70373a1d1b7ed9/moor/lib/src/types/type_system.dart#L10-L18) is the const constructor being called. All of entries in the list literal are simple constant constructors defined in [this file](https://github.com/simolus3/moor/blob/master/moor/lib/src/types/sql_types.dart).

I might be overlooking something, but I believe that this is an issue in the analyzer because

1. it was introduced in Dart 2.5, and the changelog contains no entry that could affect how that code is evaluated
2. It only affects some users
3. Most times the error goes away after typing around in the generated file referenced in the issue description

Some users (me included) hit this issue, but I never managed to consistently reproduce it - the error always went away after restarting the analysis server or typing in the affected file. @rebaz94 said that restarting the analysis server did not fix the problem. We discussed this problem in https://github.com/simolus3/moor/issues/154

**Comment by simolus3** [comment]
I get the same analysis error on `Dart VM version: 2.6.0-dev.4.0 (Mon Sep 30 14:10:31 2019 +0200) on "linux_x64"` on [this line](https://github.com/simolus3/moor/blob/6993b265326dc92079dbfe948f70373a1d1b7ed9/moor/test/data/tables/todos.g.dart#L1277).

All the tests (which definitely run that line) pass though, so the analyzer rejects it but the frontend doesn't?

**Comment by simolus3** [comment]
Smallest repro I could find: Create two Dart files, `base.dart` and `repro.dart`:

```dart
// base.dart
class Base<T> {
  const Base();
}

class A extends Base<String> {
  const A();
}

class Repro {
  final List<Base> bases;

  const Repro(this.bases);

  const Repro.foo() : this(const [A()]);
}

```
and
```dart
// repro.dart
import 'base.dart';

void main() {
  const Foo.bar(); // "evaluation of this constant expression throws exception"
}
```

Notably, the error does not occur when `Foo` is declared in the same file as the `main` method.

**Comment by eernstg** [comment]
Probably:

```dart
void main() {
  const Repro.foo();
}
```

That causes the error with an analyzer from commit 0242dea803fab7d3d2c96cebd393c564e6a6735e, and there's no error when the two libraries are combined into one library.

**Comment by JohnGalt1717** [comment]
In my case the error was that the package had an assert preventing null and because the value was optional in the child class parameter list, it threw the non-descript error message.

At runtime on web it threw an error without a message and on ios/android it throws the proper assert message.

**Comment by srawlins** [comment]
I think this is solved because I can no longer reproduce it. Please re-open if you hit this on a recent version of Dart.
