### ISSUE TITLE
Migration engine incorrectly makes a field non-nullable

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#38696]
When the migration engine is run over the logging package, it "incorrectly" makes the field `parent` non-nullable. (I put "incorrectly" in quotes because it might be that it's working as intended, but just not matching my expectations.)

The field is initialized by a field formal parameter in the following constructor:
```
Logger._internal(this.name, this.parent, Map<String, Logger> children)
    : this._children = children,
      this.children = new UnmodifiableMapView(children) {
  /* if (parent != null) */ parent._children[name] = this;
}
```
Note that the field is explicitly compared to `null` in this constructor. It's also explicitly compared in a number of other places.

The `null` is passed in from a factory, and the fact that the field is assumed to be non-nullable is causing the migration engine to add a null check on `null`:
```
factory Logger.detached(String name) {
  return new Logger._internal(name, null!, new Map<String, Logger>());
}
```
The migration results would be closer to what I believe the authors intended if the field were marked as nullable.

**Comment by stereotype441** [comment]
I believe this is happening due to #38341.  In short, there is a local variable in a test with an inferred type, and that type is inferred to be the same as the type of `parent`.  The test expects its local variable to be non-nullable, and becuase that type is inferred from the type of `parent`, the migration engine is propagating that expectation back to `parent` itself, rather than inserting a null-check in the test, as it should.  See https://github.com/dart-lang/logging/pull/66/files#r323495145 for details.

Once that bug is fixed we can revisit this one and check whether it still occurs.

**Comment by srawlins** [comment]
The dependency is fixed, and the migrator now correctly marks parent as nullable.
