### ISSUE TITLE
DDK does not properly handle partially instantiated const keys

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#38703]
The following snippet prints "PASSED" in all kernel-based backends when in a single module:
```
typedef FuncType<T> = Function();

class Key<T> {
  final FuncType<T> f;
  const Key(this.f);
}

someFunc<T>() {}
const someKey = Key(someFunc);
const Map<Key, String> m = {
  someKey: "PASSED"
};

main() {
  print(m[someKey]);
}
```

But fails in a cross-module context: https://dart-review.googlesource.com/c/sdk/+/119730
Ran with: `dart pkg/dev_compiler/test/modular_suite.dart --configuration-name dartdevk-linux-release --verbose --filter const1`

I'm not sure if this is a CFE issue or if more work needs to be done in DDK. Thoughts on this?

**Comment by askeksa-google** [comment]
It could be that the runtime is not doing constant canonicalization across modules properly. The CFE only canonicalizes constants within the same module.

What goes on could be something like this:

When the CFE sees the `someKey` inside the map, it canonicalizes it for the current module as part of the construction of the `Map` constant. However, when it sees `someKey` in `main`, it asks the `DevCompilerConstantsBackend` whether it should inline the constant and gets told not to. Thus, the value read from `someKey` at runtime is the one canonicalized for the other module. Since `class Key` indexes into the map by object identity, it does not find the entry.

**Comment by Markzipan** [comment]
Thanks, Aske! Turns out this is something on our end; we weren't canonicalizing const objects with const generic function fields.
