### ISSUE TITLE
Complex key hashing grows map too much in DartFuzz

### ISSUE THREAD

**Issue by feli-citas** [dart-lang/sdk#38710]
See [oomtest.dart.txt](https://github.com/dart-lang/sdk/files/3687850/oomtest.dart.txt)
Each iteration of the loop adds a new key to var54. Which often times leads generated programs to run out of memory when it occurs at a higher nesting level.
```
Map<List<bool>, int> var54 = {};
main() {
  for(int i=0; i<10; ++i) {
    var54[[true, false]] = 1;
  }
  print(var54.keys);
}
```

**Comment by aartbik** [comment]
@mraleph @rmacnak-google 

Is this expected and accepted behavior? For example, keying 10x with even just the empty list [] yields
`{[]: 1, []: 1, []: 1, []: 1, []: 1, []: 1, []: 1, []: 1, []: 1, []: 1}`
while keying 10x with null yields the much more intuitive
`{null: 1}`

**Comment by rmacnak-google** [comment]
This is expected. List implements == using identity. `[true, false]` creates a new List for every iteration of the loop, so those keys are distinct. You might use `const [true, false]` to avoid this.

**Comment by eernstg** [comment]
A map uses operator `==` to decide whether one and another key is "the same key", so any number of newly allocated lists (empty or not) will be distinct, and there will be one entry for each of them.

@rmacnak-google just mentioned `const [true, false]`: A constant list is canonicalized, so `const <T>[]` is the same object as `const <T>[]` for any given type `T`, no matter how many copies of the syntax you have:

```dart
Map<List<bool>, int> var54 = {};
main() {
  for(int i=0; i<10; ++i) {
    var54[const [true, false]] = 1;
  }
  print(var54.keys); // Prints '([true, false])'.
}
```

It makes sense to say that two mutable objects (e.g., two mutable lists) are not equal just because they happen to have the same state right now: Equality would then be a property that holds right now but might not hold as soon as any computations have been performed. Object identity will hold, though, because you cannot change the identity of a given object. It will also ensure that both access paths to the same object (e.g., two variables both referencing the same list) will continue to report the same state it any given point in time.

So it's not a mistake that `[] == []` evaluates to false, but for the special case of constants you have canonicalization, which means that lists are compared as-if by their contents (because comparing by contents and comparing by object identity is the same thing after canonicalization).

**Comment by aartbik** [comment]
Actually the problem was not so much the hashing (the use of == makes sense, we were just not sure if every iteration would allocate a new object). The real problem is growing the hash too much in DartFuzz. The const idea might help. 

Renamed the title to reflect this.

**Comment by aartbik** [comment]
Now we can close the bug!
