### ISSUE TITLE
Build for Fuchsia and run tests.

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#38752]
As the Flutter engine does, the Dart SDK repo should consume the Fuchsia SDK and use it to build the Dart SDK (or at least the standalone Dart VM) targeting Fuchsia for testing purposes. This would be similar to how the build and test setup targets Android with the exception that the tests may be easier to run in qemu than on a physical device.

@a-siva

**Comment by athomas** [comment]
We now have the ability to deploy qemu on our bots. We currently use qemu user mode to run FFI tests for arm on an x64 bot.

**Comment by dcharkes** [comment]
A Dart-Fuchsia build, and some test infrastructure landed ([this list contains some relevant CLs](https://dart-review.googlesource.com/q/owner:liama%2540google.com+fuchsia)).

Blocker for running bots currently is needing to run commands in sudo before running the tests (with the current way the test script is set up).

```
To use KVM acceleration, adjust permissions to /dev/kvm using:

sudo chmod 666 /dev/kvm
```

```
To use emu with networking on Linux, configure tun/tap:

sudo ip tuntap add dev qemu mode tap user dacoharkes && \
sudo ip link set qemu up
```

https://fuchsia.dev/fuchsia-src/development/testing/run_an_end_to_end_test?hl=en

If `sudo` use is a big problem maybe we could explore running Dart tests without Kernel-based Virtual Machine support and networking. (Which might be slow and exclude Dart/Fuchsia functionality.)

**Comment by zanderso** [comment]
@godofredoc might have some helpful tips.

**Comment by mkustermann** [comment]
By talking offline to @dcharkes it seems we're still missing:

  * [ ] Add build support for arm64 (only x64 is implemented)
  * [ ] Add test support for AOT (only JIT-x64 is implemented)
  * [ ] Possibly extend testing to all of our test suites
  * [ ] Make our CI system build&test this

inside our repository (i.e. [dart-lang/sdk](https://github.com/dart-lang/sdk)).

@liamappelbe @a-siva Is it planned to get these things up & running? (/cc @athomas for possible root access / ways to have special setup on our CI builders for qemu emulators.)

Apart from doing build&testing in the Dart SDK repository, I assume fuchsia does have it's own CI system where it runs tests for JIT/AOT with Dart and/or Fuchsia embedder on X64/ARM64. Until we have the right setup, @dcharkes could add possible FFI tests there.  @zanderso Do you know where those tests are?

**Comment by zanderso** [comment]
@arbreng for the question about Dart and Flutter tests on Fuchsia CI.

**Comment by godofredoc** [comment]
Flutter is using femu for running x64 tests:

https://cs.opensource.google/flutter/recipes/+/master:recipes/femu_test.py fuchsia has a recipes module encapsulating most of the complexity.

For tun/tap we add the interfaces at machine provisioning time rather than doing it at task execution time(flutter bots are provisioned with salt stack).

For the arm64 qemu do you have special hardware? that may be required for enabling hardware acceleration or it may be too slow.

**Comment by liamappelbe** [comment]
arm64 and aot support would be nice, but I don't have any plans to work on them.

As for extending it to test all suites, the tests are already super slow to run, so I don't think that would be a good idea. Most of the tests are unlikely to behave differently on Fuchsia (eg language tests), so given the constraints we were only planning to test the most important suites. The IO and FFI tests are probably the most important.

**Comment by dcharkes** [comment]
> For the arm64 qemu do you have special hardware? that may be required for enabling hardware acceleration or it may be too slow.

It is too slow, at least the way it is set up now, running a test on the fuchsia arm64 simulator takes 2,5 hours to serve blobs (tested with https://dart-review.googlesource.com/c/sdk/+/173273/24, [logs](https://paste.googleplex.com/6086875216347136)).

Maybe some things could be improved with how `dart_test_debug.far` is set up, because `runtime_tests-0.far` from the Flutter repo only took a minute to run ([logs](https://paste.googleplex.com/4683226309197824)). The flutter testing fars trigger way less `[pm server] 200 /blobs/....` steps.

**Comment by zijiehe-google-com** [comment]
@athomas may know that I am currently working on the effort. I will assign this bug to myself now.

**Comment by a-siva** [comment]
@zijiehe-google-com are you actively working on adding build/tests for Fuchsia in the Dart SDK repo ?
Will you be doing this with the v2 components of Fuchsia ?

**Comment by zijiehe-google-com** [comment]
Hopefully I can find a clear boundary between these two work items, but yes, I am working on them.
