### ISSUE TITLE
DDC subtype check optimization now has a proven counter example

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#38818]
There are edge cases where it looks like DDC will return the wrong result from a subtype check based on this 

https://github.com/dart-lang/sdk/blob/0dd6ea13540588a0c8becc7db58019f0fb00c254/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart#L896-L902

@fishythefish found a counter example to the conjecture that code was based on and it should be removed. See counter example in https://github.com/dart-lang/language/blob/master/resources/type-system/subtyping.md.

**Comment by fishythefish** [comment]
FWIW, I think all of our implementations have this bug. Consider the following program:

```dart
import 'dart:async';

class A implements Future<Future<A>> {
  // Ignore missing implementation
  @override
  noSuchMethod(Invocation invocation) {}
}

void main() {
  List<A> as = [];
  List<FutureOr<A>> foas = [];
  print(as is List<Future<A>>);
  print(foas is List<FutureOr<Future<A>>>);
}
```

This should print
```
false
true
```
since with `B := Future<A>`, we have `A </: B` but `FutureOr<A> <: FutureOr<B>`.

However, we produce
```
false
false
```
since all the implementations seem to perform the same bad optimization and reduce the check `FutureOr<A> <: FutureOr<B>` to `A <: B`.

We should probably file issues against all of the offenders.

**Comment by fishythefish** [comment]
https://dart-review.googlesource.com/c/sdk/+/121653/ should add `language_2/future_or_subtype_test`, which will exercise this behavior. I'll file bugs against backends when it lands. I could write up a fix for dart2js, but enough of the subtyping logic would have to be restructured that I'm just going to kick it down the road until I fully rewrite the subtyping algorithm for NNBD.

**Comment by fishythefish** [comment]
Okay, the test landed, and we have tracking issues:
* #38904 (Analyzer)
* #38905 (CFE)
* #38906 (VM)
* #38907 (dart2js)
