### ISSUE TITLE
Incorrect error when a class implements the same generic interface from a legacy and migrated library

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#38813]
The analyzer issues an error when a class implements the same generic interface from a legacy and a migrated library.

```dart
// migrated
class A<T> {}

class B extends A<int> {}
```

```
// @dart = 2.5
import "test3.dart";

class C extends B implements A<int> {}
```

```
  error • The class 'C' cannot implement both 'A<int>' and 'A<int>' because the type arguments are different. • /Users/leafp/tmp/test.dart:3:1 • conflicting_generic_interfaces
```

This should not be an error - in non-migrated libraries, there should be no errors arising from the interaction of migrated and non-migrated types.

This came up a couple of times in migrating the core libraries.

cc @eernstg @munificent @lrhn @stereotype441 @stefantsov

**Comment by eernstg** [comment]
I have observed this conflict in a library which is opted in as well, so we may need to tolerate this kind of conflict also when it arises in opted-in code.

We cannot expect to avoid the conflicts, because there will be diamond patterns (`C<T>` implements `B1<T>` and `B2<T>`, both of them implement `A<T>`, and the implements links to `B1` and `B2` occur in opted-in respectively opted-out code), and that setup will be visible from opted-in code as well as opted-out code.

**Comment by stereotype441** [comment]
The reason this restriction exists is because we assume that given a reference to one class that implements another, we assume that it is meaningful and well formed to ask "how does this class implement this other class?"  We need to ask this question in order to resolve method calls and do correct type checking.

So let's expand the example above like so:
```dart
// migrated
class A<T> {
  void f(T t) { ... }
}
class B extends A<int> {}
```
```dart
// @dart = 2.5
import "test3.dart";

class C extends B implements A<int> {}
```
```dart
// migrated
void test(C c, int? i) {
  c.f(i);          // (1)
}
```
Should the call at (1) result in an error (or, in weak checking mode, a warning)?  Normally we would answer this question by the following logic:
- The call to `f` resolves to `A.f`.
- To figure out the type of `A.f` in this context, we first need to figure out what the type argument of `A` is.
- To answer that, we ask "how does class `C` implement `A`".  The answer is ambiguous: if we go through `B`, then `C` implements `A<int>`, in which case the type of `A.f` is `void Function(int)`, and we have an error due to the lack of a null check.  But if we go directly via `C`'s "implements" clause, then `C` implements `A<int*>`, in which case the type of `A.f` is `void Function(int*)`, and we have no error.

So if we want to allow for this sort of ambiguity, what should the behavior be?  (And can we figure out a coherent way to implement it?)

**Comment by nshahan** [comment]
@leafpetersen @eernstg It looks like this still could use some attention. This issue is a short term blocker for my DDC implementation work but should go away once more of the core libraries opt in. For me, making progress on the migration has priority over a decisions in the questions raised here.

**Comment by eernstg** [comment]
_tl;dr_  For legacy code, erase. For nnbd code, ignore `*`  _rd;lt_

In legacy code there should not be a notion of having an NNBD type argument in a superinterface (the legacy code just doesn't know what that is). We can get this kind of conflict at the very first step of a migration (where we change `new.dart` such that it is opted in rather than out):

```dart
// ---------- Opted-in library 'new'.
class A<X> {}
class B1 implements A<int> {}

// ---------- Opted-out library 'old'.
// @dart = 2.5
import 'new.dart';
class B2 implements A<int> {}
class C implements B1, B2 {}
```

This situation arises from existing code simply by opting in `new.dart` and leaving `old.dart` unchanged (and opted out). That should not put `old.dart` in a situation where it has a compile-time error that cannot be eliminated unless `old.dart` is opted in. (We could move the declaration of `B2` to another library which is opted in, but that's essentially the same thing as saying "the error in `old.dart` cannot be eliminated").

Presumably this means that static analysis in a legacy file would need to ignore conflicts like the one that we get for "implements a superinterface `S` with more than one list of actual type arguments", when they arise only in terms of NNBD typing distinctions.

But that's already what is [specified](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#legacy-libraries): When legacy libraries are checked they should work on types where nnbd type elements have been erased (in particular, the legacy library cannot see the difference between `int` and `int*`). So I believe this part would be a matter of implementation rather than a matter of clarifying or changing specifications.

During the static analysis of an opted-in library (let's call that 'nnbd code'), [this section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#importing-legacy-libraries-from-opted-in-libraries) specifies that 'types which are imported' from legacy libraries are seen as legacy types, whereas inference erases such types before they are used (say, to perform override inference).

Perhaps we could make a distinction between different kinds of import of such types? At least, it seems tempting to apply erasure to superinterfaces. This would make them identical to the types that are used during inference. It would not be sound, of course:

```dart
// Opted-out 'old.dart'.
class A<X> {
  X x = null;
  X get g => x;
}

class B extends A<int> {}

// Opted-in 'new.dart'.
import 'old.dart';

class C extends B {}
```

The interface of `C` would now have a member signature `g` with return type `int`, but it actually returns null. Nevertheless, this may not be worse than various other sources of unsoundness, and it does eliminate the "implement same superinterface with different type arguments" problem.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125549
