### ISSUE TITLE
DDC subtype checks incorrectly ignore type variables that have not been promoted

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#38816]
DDC subtype checking algorithm elides all rules related to type variables. In many cases this is expected since they will be instantiated but there are edge cases where they have not been promoted. 

@leafpetersen provided an example: 
> This test should print true twice (and does so on the VM), but prints true, false in DDC:

```dart
void foo<T extends num>(T x) {}
void bar<T extends num>(num x) {}

typedef F = Function<T extends num>(T x);

void main() {
  print(foo is F);
  print(bar is F);
} 
```

**Comment by leafpetersen** [comment]
This fails on dart2js as well.  cc @rakudrama @sigmundch

**Comment by fishythefish** [comment]
Yeah, our current RTI implementation of subtype checks doesn't follow the prescribed algorithm, so it's fairly ad-hoc and has a number of issues, some of which I've patched recently.

Our support for generic functions is really poor: to check `f <: g`, we confirm that the type parameters of `f` and `g` have the same bounds, but beyond that, we ignore the bounds and just compare `f` and `g` as if they were non-generic functions. Of course, this doesn't make sense because the return types and parameter types could still refer to type variables. Cases like `foo is F` work because of reflexivity, but `bar is F` breaks because we're comparing `type-variable-at-de-bruijn-index-0` with `num`. There's a longstanding TODO that says that we should, y'know, *use the type parameters*.

This should get fixed anyway when I move us over to the new algorithm, but here's a quick fix: https://dart-review.googlesource.com/c/sdk/+/121501

**Comment by fishythefish** [comment]
https://dart-review.googlesource.com/c/sdk/+/121501 just landed, fixing the issue for dart2js. I added `tests/language_2/issue38816_test` and preapproved the failures for DDC.
