### ISSUE TITLE
The version of Dart reported by Flutter on master/dev/beta branches is wrong

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#38817]
When Flutter is using a non-stable Dart, the version number of Dart that is reported (as used by pub when picking packages for example) is wrong.

e.g. Flutter reports `2.6.0-dev.0.0.flutter-48e93d3d3b` instead of `2.6.0-dev.7.0.flutter-48e93d3d3b` today.

**Comment by athomas** [comment]
Flutter builds set this gn arg:
https://github.com/flutter/engine/blob/master/tools/gn#L188
`dart_custom_version_for_pub = flutter``
Which should then create a version string based on the latest dev tag:
https://github.com/dart-lang/sdk/blob/master/tools/make_version.py#L57

However, there is also a fallback on the VERSION file if the latest dev tag can't be retrieved. Maybe that is what's happening here? Somehow, Flutter builds can no longer access fetch the latest dev tag?

When that happens: "Warning: Could not get the most recent dev branch tag" should be printed somewhere (maybe requires a --verbose).

Now, nothing really has changed on the Dart as far as I can see. The problem is more likely in the Flutter engine's Dart SDK build (Dart's Dart SDKs report their version numbers as expected).

@aam

**Comment by leafpetersen** [comment]
Should this be moved to the flutter issue tracker?

**Comment by aam** [comment]
> When Flutter is using a non-stable Dart, the version number of Dart that is reported (as used by pub when picking packages for example) is wrong.
> 
> e.g. Flutter reports `2.6.0-dev.0.0.flutter-48e93d3d3b` instead of `2.6.0-dev.7.0.flutter-48e93d3d3b` today.

Can you clarify how to see "dev.0.0". This is what I see:

```
╭─aam@mac ~/p/flutter  ‹master› 
╰─➤  bin/cache/dart-sdk/bin/pub --version
Pub 2.6.0-dev.6.0.flutter-48e93d3d3b
╭─aam@mac ~/p/flutter  ‹master› 
╰─➤  bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.6.0-dev.6.0.flutter-48e93d3d3b (Thu Oct 10 00:49:41 2019 +0000) on "linux_x64"
╭─aam@mac ~/p/flutter  ‹master› 
╰─➤  bin/flutter --version
Flutter 1.10.15-pre.68 • channel master • git@github.com:flutter/flutter.git
Framework • revision 6430b440d7 (60 minutes ago) • 2019-10-10 14:14:53 -0700
Engine • revision 5162413111
Tools • Dart 2.6.0 (build 2.6.0-dev.6.0 48e93d3d3b)
╭─aam@mac ~/p/flutter  ‹master› 
╰─➤  git log -1 | cat
commit 6430b440d750f2dc8797e62791839d99652731da
Author: Emmanuel Garcia <egarciad@google.com>
Date:   Thu Oct 10 14:14:53 2019 -0700
```

**Comment by aam** [comment]
I stumbled upon flutter revision e62c68c24 which if I check out from flutter/flutter repo does have dart and pub report `dev-0.0`:
```
╭─aam@host ~/p/flutter  ‹e62c68c24› 
╰─➤  bin/cache/dart-sdk/bin/pub --version
Pub 2.6.0-dev.0.0.flutter-7799f424f4
╭─aam@host ~/p/flutter  ‹e62c68c24› 
╰─➤  bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.6.0-dev.0.0.flutter-7799f424f4 (Mon Sep 16 13:10:59 2019 +0000) on "linux_x64"
```

Looking at the dart sdk built as part of engine artifacts(step 46 in https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/2197) does show dart and pub reporting `dev-0.0`:
```
~/Downloads/flutter_2c4ed36c60ae82a4e834836f079ee91857c431c9_dart-sdk-linux-x64  
╰─➤  dart-sdk/bin/pub --version
Pub 2.6.0-dev.0.0.flutter-7799f424f4
Isolate creation failed
~/Downloads/flutter_2c4ed36c60ae82a4e834836f079ee91857c431c9_dart-sdk-linux-x64  
╰─➤  dart-sdk/bin/dart --version
Dart VM version: 2.6.0-dev.0.0.flutter-7799f424f4 (Mon Sep 16 13:10:59 2019 +0000) on "linux_x64"
```

Building same revision of flutter engine/dart sdk locally doesn't reproduce same behavior:
```
╭─aam@host ~/p/f/flutter/engine/src/flutter  ‹2c4ed36c6› 
╰─➤  git log -1 | cat
commit 2c4ed36c60ae82a4e834836f079ee91857c431c9
Author: Ben Konyi <bkonyi@google.com>
Date:   Mon Sep 16 09:36:40 2019 -0700

    Roll src/third_party/dart a8f433820b..7799f424f4 (3 commits)
    
    dart-lang/sdk@7799f424f4 [CFE] Encapsulate int operations in separate classes for VM and JS
    dart-lang/sdk@eb1a375749 [CFE] Consolidate double special cases for == and identical.
    dart-lang/sdk@7b60ae1a0d [cfe] Fix infer expression
╰─➤  ../out/host_debug_unopt/dart-sdk/bin/dart --version
Dart VM version: 2.6.0-dev.6.0.flutter-7799f424f4 (Mon Sep 16 13:10:59 2019 +0000) on "linux_x64"
╰─➤  ../out/host_debug_unopt/dart-sdk/bin/pub --version
Pub 2.6.0-dev.6.0.flutter-7799f424f4
```

So sounds like an issue with building engine on luci, so adding @dnfield

**Comment by aam** [comment]
Version information is pulled from dart sdk git repo via `git for-each-ref "refs/tags/*dev*" --sort=-taggerdate --format="%(refname:lstrip=2)" --count=1`
Is it possible that some flutter engine builder had git repo, which didn't have those tags updated/refreshed?

**Comment by aam** [comment]
Sorry for the confusion `2.6.0-dev.0.0` for https://github.com/flutter/flutter/commit/e62c68c24 is actually correct because 2.6.0-dev.1.0 was only created on 9/16.

So, back to my original question, @Hixie, what is the way to see `2.6.0-dev.0.0.flutter-48e93d3d3b` reported?

**Comment by Hixie** [comment]
I was quoting one of our users on our chat channel. I see the same thing as you. Maybe this is not an issue?

Do SDK constraints work against the full `2.6.0-dev.6.0` string?

**Comment by Hixie** [comment]
Said user reports:
```
[✓] Flutter (Channel master, v1.10.15-pre.53, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.10.15-pre.53 at /Users/lukepighetti/flutter
    • Framework revision 166fd5975d (10 hours ago), 2019-10-10 11:04:43 -0400
    • Engine revision d25a623d7f
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 48e93d3d3b)
```
Maybe this is macOS-only?

**Comment by Hixie** [comment]
on linux, same build, i do get ...6.0:
```
[✓] Flutter (Channel unknown, v1.10.15-pre.53, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.15-pre.53 at /usr/local/google/home/ianh/dev/flutter
    • Framework revision 166fd5975d (10 hours ago), 2019-10-10 11:04:43 -0400
    • Engine revision d25a623d7f
    • Dart version 2.6.0 (build 2.6.0-dev.6.0 48e93d3d3b)
```

**Comment by aam** [comment]
> Maybe this is macOS-only?

Indeed, on mac I see dev-0.0. And checking pub and dart from dart sdk produced by [engine build](https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/2569) (step 53) shows same dev-0.0.

Not sure what the problem might be.
But I also think that using latest refs/tags available in git repo to stamp the version is problematic partially because it is impossible to reproduce original build as you get more more recent tags pulled(essentially what stumped me in https://github.com/dart-lang/sdk/issues/38817#issuecomment-540833173 above).

**Comment by Hixie** [comment]
For Flutter we use the tag of the most-recently-tagged commit that is still older than the current commit, so version numbers back in time are mostly consistent (the one exception is when we tag a specific commit, that commit and later commits change version number, but that's working as intended).

**Comment by aam** [comment]
> For Flutter we use the tag of the most-recently-tagged commit that is still older than the current commit

Yeah, that's not what we do in dart: https://github.com/dart-lang/sdk/blob/master/tools/utils.py#L511

**Comment by aam** [comment]
I experimented with `git fetch` and `git for-each-ref` commands on buildbot and it's clear that tags for dart repo are not being retrieved correctly. See [sample run](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/aam_google.com/78440eb059777c06efc8c8f4f8e2a01b8eedf138133929dd52bdb74e905c51f9/+/annotations?server=chromium-swarm.appspot.com) where I added steps 6 and 7 to fetch and print tags.

I am not sure about root cause and not sure why this problem only exists on mac bot.

But it is rather serious - seemingly all mac builds since mid-September have dart sdk versioned `dev-0.0` version.

**Comment by a-siva** [comment]
Who should own this issue?

There are two aspects here
- in the short term we should investigate why Utils.GetLatestDevTag() is behaving differently since mid-September
- in the new release process scheme we should move away from using Utils.GetLatestDevTag() to determine the version and instead pick the version up from a version.cc file.

**Comment by aam** [comment]
Sent out https://chromium-review.googlesource.com/c/chromium/tools/build/+/1856340 with a fix that fetches dart tags.

I think difference between mac and linux might be due to how linux bots rarely preserve checked-out workdir, while mac bots often do. And `gclient sync` by itself doesn't seem to pull tags for DEPS repos.
