### ISSUE TITLE
Analyzer: Runtime error when passing a class member function

### ISSUE THREAD

**Issue by dballesteros7** [dart-lang/sdk#38863]
This is an error that happens in the following code:

```dart
typedef alias = Future<void> Function(String a);
void fun(alias a) {}

class X {
  X() {
    fun(bar);
  }
  void bar(String a) {}
}

void main() => X();
```

The error only happens at runtime and it's:

```
Unhandled exception:
type '(String) => void' is not a subtype of type '(String) => Future<void>'
```

On the other hand, with free functions, the error is at compile time (which is the desired case):

```dart
typedef alias = Future<void> Function(String);   
void fun(alias a) {}
void bar(String a) {}
void main() =>  fun(bar);
```
```
test.dart:4:21: Error: The top level function has type 'void Function(String)' that isn't of expected type 'Future<void> Function(String)'.
 - 'Future' is from 'dart:async'.
Change the type of the function or the context in which it is used.
```

**Comment by eernstg** [comment]
> `type '(String) => void' is not a subtype of type '(String) => Future<void>'`

This is true, there is no such subtype relationship. But there is the opposite relationship: `Future<void> Function(String)` is a subtype of `void Function(String)`, and this means that the actual argument `bar` is accepted, and a dynamic check is inserted due to the downcast.

We're currently adding support for non-nullable types (it won't be released for a while, but lots of things are happening right now in order to get there), and when we have them there won't be any of these implicit downcasts any more.

Currently, you can use `--no-implicit-casts` to flag such downcasts as compile-time errors. In that case you will have to write an explicit cast (`fun(bar as Future<void> Function(String))`).
