### ISSUE TITLE
dartdevc and dart2js inconsistent with upcasting int to num

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#38879]
I tried to `+=` a num to an int somewhere. When the num turned out to be a double it was fine in dartdevc, but dart2js threw an error that was somewhat hard to locate (especially since `webdev build` takes about half a minute ;D).

I may have seen an issue about letting the analyzer warn you about this. It seems to me this should already be part of the spec of the analyzer (after all I am trying to assign a num to a var that was declared to be an int, i.e. `+` in the context of `+=` should only accept ints and not nums).

Also it got me wondering if double is the dominant type here (or if `+=` an int to double may sometimes produce an int, that would be a bit scary).

**Comment by lrhn** [comment]
Dart still has implicit downcasts. The meaning of `x += number;` is `x = x + number;`. If `x` is an `int` variable and `number` has static type `num`, then the static type of `x + number` is `num`, and since `num` is a super-type of `int`, we allow you to implicitly downcast the result to `int`. That can fail at run-time, and if `num` happens to be a `double` like 2.5, then it *will* fail at run-time. It can also succeed if `number` is an int.

The type of `int + double` is `double`, which is not assignable to `int`, but `int + num` is `num`, which is assignable through implicit downcast. That makes sense because a `num` *might be* an `int`.

(When compiled to JavaScript, you suffer the added complexity of JavaScript numbers where some doubles are also integers, and all integers are doubles. So, in that case, the code *might* succeed when `number` is 2.0).

It's probably a bug if the same code, with the same values, fail in dart2js and runs in dartdevc.

(I say "still" above because implicit downcasts will be removed with non-nullable types. It made no sense that a nullable type could be implicitly downcast to a non-nullable variable, that would remove most of the reason for having non-nullable types to begin with).

**Comment by bergwerf** [comment]
I think the implicit downcast is a bit tricky (with `var offset = 0;` it is very easy to unintentionally make something an int), but I guess you should only use `num` when developing a clearly separated abstraction and turn everything else into doubles as soon as possible if doubles may turn up somewhere (so the analyzer warns you if your code makes wrong assumptions).

**Comment by sigmundch** [comment]
Thanks for filing the bug. Please let us know if you have an example we can look into to investigate the discrepancy between the two compilers.

@lrhn already pointed out the main caveat I wanted to say, that in web compilers double + double can be an int because we use the same number representation for both (basically by compiling down to JavaScript's `Number`).
