### ISSUE TITLE
DartFuzz output divergence

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#38871]
Output divergence:

```dart
NO-FP NO-FFI FLAT : KBC-MIX-DET-ReleaseX64 - KBC-CMP-SRC-DebugIA32: !DIVERGENCE! 1.59:2631963975 (output)

-- BEGIN REPRODUCE  --

dartfuzz.dart --no-fp --no-ffi --flat --seed 2631963975 /b/s/w/it37w9cB/dart_fuzzHRGSTV/fuzz.dart

-- RUN 1 --

/b/s/w/ir/pkg/vm/tool/gen_kernel --gen-bytecode --platform=/b/s/w/ir/out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/it37w9cB/dart_fuzzHRGSTV/out.dill /b/s/w/it37w9cB/dart_fuzzHRGSTV/fuzz.dart
/b/s/w/ir/out/ReleaseX64/dart --enable-interpreter --deterministic --old_gen_heap_size=128 /b/s/w/it37w9cB/dart_fuzzHRGSTV/out.dill

-- RUN 2 --

/b/s/w/ir/out/DebugIA32/dart --use-bytecode-compiler --old_gen_heap_size=128 /b/s/w/it37w9cB/dart_fuzzHRGSTV/fuzz.dart

-- END REPRODUCE  --

```

**Comment by alexmarkov** [comment]
There are out of memory errors happening at slightly different places on 32-bit vs 64-bit architectures.

In one case OOM happens when allocating index (Uint32List) while rehashing a Map, in the other case OOM happens when allocating List for data, also while rehashing a Map. In the latter case index is already erased when OOM happens and Map elements are lost, which causes divergence in the subsequent code.

Generated fuzz.dart contains the line

```
}}} catch (exception, stackTrace) {      par1 = {if (var15) (ZLibOption.minWindowBits as int) : ((('x3(a' * 26)).padLeft(29, '')), (-((~((Float32x4.xzzy as int))))) : ((false ? var28[(true & (var32[fld0_0[(false ? -78 : var17)]] ? true : (false ? var15 : (SecurityContext.alpnSupported))))] : 'V1cHLXf') + ''), if (((true & var20[-6]) ^ (var29[(false ? var8[-60] : (-((++var17))))] || false))) (-(var9[(~((-((Int32x4.wywy as int)))))])) : 'a\u2665'};
```

which catches OOM and continues. Maybe we can avoid catching OOMs at that level and report it, instead of reporting divergence.

@aartbik could you please take a look?

**Comment by aartbik** [comment]
We should always include OOM clause in try-catch-finally since higher level test runner will treat any OOM situation as a false divergence. CL pending.
