### ISSUE TITLE
Invalid response status code 

### ISSUE THREAD

**Issue by lyf571321556** [dart-lang/sdk#38882]
```dart
Future<Response> login(String userName, String password) async {
  Map requestParams = {
    "password": password,
    "email": userName,
  };
  Response response =
      await _httpClient.post("auth/login", data: json.encode(requestParams));
  return Future.value(response);
}
```

my status code is 8xx,flutter throws an exception: Invalid response status code!

i found some code throw it in the code of "http_parser.dart" in the Flutter SDK.
```dart
if (_statusCode < 100 || _statusCode > 599) { 
  throw new HttpException("Invalid response status code"); 
}
```
But I want to use the customed HTTP statusCode between 200 and 800, such as 801!

**Comment by lrhn** [comment]
The HTTP protocol does not allow status codes outside the 100-599 range, see the [RFC]*(https://tools.ietf.org/html/rfc2616#section-6.1.1).

You can use unspecified codes in *that range*, but the receiver needs to know how to treat the response, and it only does that for codes starting with 1-5. Quoting the RFC:

> HTTP status codes are extensible. HTTP applications are not required
   to understand the meaning of all registered status codes, though such
   understanding is obviously desirable. However, applications MUST
   understand the class of any status code, as indicated by the first
   digit, and treat any unrecognized response as being equivalent to the
   x00 status code of that class, with the exception that an
   unrecognized response MUST NOT be cached.

So, to know the class, the code must be in one of the ranges:

* 1xx: Informational - Request received, continuing process
* 2xx: Success - The action was successfully received, understood, and accepted
* 3xx: Redirection - Further action must be taken in order to complete the request
* 4xx: Client Error - The request contains bad syntax or cannot be fulfilled
* 5xx: Server Error - The server failed to fulfill an apparently valid request
