### ISSUE TITLE
Promotion under NNBD does not promote function types

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#38902]
If I analyze:

```dart
checkType(Object fn) {
  if (fn is Function(int)) {
    fn(123);
  }
}
```

Using:

```
dartanalyzer --enable-experiment=non-nullable temp.dart
```

I get:

```
  error • 'fn' isn't a function at /Users/rnystrom/Documents/temp.dart:3:5 • invocation_of_non_function
```

If I analyze it without passing `--enable-experiment=non-nullable`, I get no errors, as I expect.

**Comment by scheglov** [comment]
It seems that `Dart2TypeSystem.isSubtypeOf(t1, t2)` does not take the branch:
`t1 = {_FunctionTypeImplStrict} dynamic Function(int)`
`t2 = {InterfaceTypeImpl} Object`

```dart
    if (_isTop(t2)) {
      return true;
    }
```

Because when `t2` is `Object!`, `_isTop` does not like it.
```dart
bool _isTop(DartType t) {
  if (t.isDartAsyncFutureOr) {
    return _isTop((t as InterfaceType).typeArguments[0]);
  }
  return t.isDynamic ||
      (t.isObject &&
          (t as TypeImpl).nullabilitySuffix != NullabilitySuffix.none) ||
      t.isVoid ||
      identical(t, UnknownInferredType.instance);
}
```

It id probably incorrect, because [the rules for subtyping](https://github.com/dart-lang/language/blob/master/resources/type-system/subtyping.md#rules) don't make any exclusion for function types in the `Right Object` rule.

**Comment by scheglov** [comment]
Fixed with https://dart-review.googlesource.com/c/sdk/+/122682.
