### ISSUE TITLE
dart2js: new rti: incorrect supertype metadata for erased type variables

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#38949]
Since `Baz` has erased types, A and B should be mapped to `dynamic`, not the erased types
`"Baz":{"Foo":["1","2"]}`

```dart
abstract class Foo<A, B> {
  bool pip(o);
}

class Bar<X, Y> implements Foo<X, Y>  {
  bool pip(o) => o is Y;
}

class Baz<U, V> implements Foo<U, V> {
  bool pip(o) => true;
}


main() {
  test(1);
  test(Bar<String, int>());
  test(Baz<String, int>());
}

@pragma('dart2js:noInline')
test(p) {
  if (p is Foo) {
    for (var o in[1, 'x']) {
      print(p.pip(o));
    }
  }
}
```
There are a couple of benchmarks that fail for this reason.

**Comment by fishythefish** [comment]
Our current RTI need computation doesn't seem to fit well with our new model. In the following code, if we don't account for type erasure, then `"Foo":{"Base":["1","2"]}` will cause `x is Base` to throw (as in Stephen's example). Our RTI need says that `classNeedsTypeArguments` is `false` for `Foo`, so we should instead encode `"Foo":{"Base":["@","@"]}`. However, this causes the last line of `main` to print `false` instead of `true`, since we're now saying that `Foo<String, int> </: Base<String, int>`, but rather `Foo<String, int> <: Base<dynamic, dynamic>`.

```dart
abstract class Base<X, Y> {}

class Foo<X, Y> implements Base<X, Y> {
  Foo();
  factory Foo.bar() => Bar<X, Y>();
}

class Bar<X, Y> implements Foo<X, Y> {}

void main() {
  test(1);
  test(Foo<String, int>());
  print(blah is Base<String, int> Function());
}

Foo<String, int> blah() => Foo<String, int>.bar();

@pragma('dart2js:noInline')
void test(dynamic x) {
  print(x is Base);
}

@sigmundch mentioned that we may want to restructure our RTI need given that we're separating classes and types. Here, the `Foo` *class* may not need type arguments at runtime, but the `Foo` *type* does.
