### ISSUE TITLE
FileSystemEntity.isDirectorySync returns different values with same path

### ISSUE THREAD

**Issue by ZichangG** [dart-lang/sdk#38956]
Here is an example:
``` dart
import 'dart:async';
import "dart:io";

main() async {
  Directory dir = new Directory(Directory.systemTemp.path + Platform.pathSeparator + "test-dir");
  Completer<bool> c = Completer<bool>();
  dir.createSync();
  print(dir.path);
  print(FileSystemEntity.isDirectorySync(dir.path)); // print 'true'
 
  dir.watch(recursive: true).listen((FileSystemEvent event) {
    print(event);
    if (dir.path == event.path) {
      print(FileSystemEntity.isDirectorySync(event.path)); // print 'false'
    }
    c.complete(true);
  });
  dir.deleteSync();
  await c.future; 
}
```
FileSystemEntity.isDirectorySync was called twice with the same `path`. But results are not consistent.
```
/tmp/test-dir
true
FileSystemDeleteEvent('/tmp/test-dir')
false
```
tested on Linux, Mac and Windows.

**Comment by srawlins** [comment]
I think I'm missing something:

1. You create a directory and ask: `FileSystemEntity.isDirectorySync(dir.path)` which returns `true`, because there _is_ a directory at `dir.path`.
2. You delete that directory, then ask again, `FileSystemEntity.isDirectorySync(event.path)` which returns `false`, because there _isn't_ a directory at `event.path`.

I don't see the bug.

**Comment by ZichangG** [comment]
Oh i see. Thanks for clarification!
