### ISSUE TITLE
Why are while-loops much slower than for-loops?

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#39009]
I ran the following snippet at https://dartpad.dev and the `for`-loops are always 1.75 times faster than the `while`-loops. Why is that?

```dart
void main() {
  final n = 1e9, loops = [
    () {
      int j;
      for (int i = 0; i < n; i++) {
        j = 5;
        j *= calculation(j);
      }    
    },
    () {
      for (int i = 0; i < n; i++) {
        int j = 5;
        j *= calculation(j);
      }     
    },
    () {
      int i = 0;
      while (i++ < n) {
        int j = 5;
        j *= calculation(j);
      }
    },
    () {
      int i = 0, j;
      while (i++ < n) {
        j = 5;
        j *= calculation(j);
      }
    },
  ];
  
  for (int i = 0; i < loops.length; i++) {
    final time = DateTime.now();
    loops[i]();
    print('Loop ${i + 1}: ${DateTime.now().difference(time).inMilliseconds}ms');
  }
}

int calculation(int n) => n * n ~/ n;
```

I tested this in an attempt to finding answers to https://github.com/dart-lang/sdk/issues/39006.

**Comment by mraleph** [comment]
Below you can find some analysis of the difference you are seeing. However I would like to discourage you from looking at performance in such a way: micro-optimizing your code by using `for` or `while` based on some microbenchmarks is rarely (if ever) needed.

First of all, I would like to bring to your attention the fact that when you run things in DartPad it compiles Dart to JavaScript, which is then run inside your browser - so this is not going to answer any questions about Dart performance in the context of Flutter - because this would have drastically different performance characteristics from running Dart using its native AOT compiler. Also this introduces a lot of points where things can go slightly wrong. 

Now the code produced from `while` and `for` loops by dart2js is somewhat different. `for` loop benchmark gets compiled to this (`dart2js -O3 --no-minify`):

```js
  V.main_closure.prototype = {
    call$0: function() {
      var t1, i;
      for (t1 = this.n, i = 0; i < t1; ++i)
        ;
    }
  };
```  

while `while`-loop benchmark gets compiled to something like this

```js
  V.main_closure2.prototype = {
    call$0: function() {
      var t1, i, i0;
      for (t1 = this.n, i = 0; i0 = i + 1, i < t1; i = i0)
        ;
    }
  };
```

The code is slightly different (there is one more live variable) - this probably leads to slightly different performance (especially in different browsers). Note that additional live variable appears because you use post increment which returns the previous value of `i` - if you want your `while` and `for` loops to make exactly the same number of iterations you should have written it as `++i < n` - which would also eliminate temporary variable. 

I have slightly changed your code to do multiple runs (to accommodate for JS JIT warmup) and tried reproducing this in Chrome 77 and Safari 13.0.2. 

```dart
  var it = 0;
  while (it++ < 5) {
    for (int i = 0; i < loops.length; i++) {
      final time = DateTime.now();
      loops[i]();
      print('Loop ${i + 1}: ${DateTime.now().difference(time).inMilliseconds}ms');
    }
    print("\n");
  }
```

In Chrome 77 I get 

```
Loop 1: 427ms
Loop 2: 541ms
Loop 3: 543ms
Loop 4: 540ms


Loop 1: 407ms
Loop 2: 406ms
Loop 3: 541ms
Loop 4: 546ms


Loop 1: 270ms
Loop 2: 271ms
Loop 3: 271ms
Loop 4: 270ms


Loop 1: 262ms
Loop 2: 259ms
Loop 3: 258ms
Loop 4: 262ms


Loop 1: 259ms
Loop 2: 258ms
Loop 3: 255ms
Loop 4: 255ms
```

as you can see there is no real difference between `for` and `while`. 

Now in Safari I got: 

```
Loop 1: 525ms
Loop 2: 512ms
Loop 3: 516ms
Loop 4: 517ms


Loop 1: 257ms
Loop 2: 257ms
Loop 3: 512ms
Loop 4: 513ms


Loop 1: 257ms
Loop 2: 258ms
Loop 3: 513ms
Loop 4: 513ms


Loop 1: 256ms
Loop 2: 256ms
Loop 3: 516ms
Loop 4: 508ms


Loop 1: 253ms
Loop 2: 255ms
Loop 3: 508ms
Loop 4: 508ms
```

which indicates a difference. We can look at the generated machine code (you can use `jsvu` to get a JavaScriptCore binary - and then run it with `--dumpDisassembly=true` to get machine code dumped) to establish what exactly happens. Here is what JSC produced for the `for`-loop:

```
                  0x3782f8600390: inc %eax
                  0x3782f8600392: cmp %eax, %ecx
                  0x3782f8600394: jg 0x3782f8600390
```

and here is what it produced for the while loop

```
                  0x28377740058e: mov %ecx, %eax
                  0x283777400590: inc %eax
                  0x283777400592: jo 0x28377740065c
                  0x283777400598: cmp %edx, %ecx        
                  0x28377740059a: jge 0x2837774005a7 
                  0x2837774005a0: mov %eax, %ecx         
                  0x2837774005a2: jmp 0x28377740058e
```

Note few differences: there is an overflow check at `0x283777400592` and there is some register reshuffling (because of the temporary variable). Overflow check arises most likely because range analysis if confused and can't prove that `i` stays within int32 range.

If you rewrite the code into `while (++i < n)` then these artefacts disappear. 

Hopefully this answers your question.

**Comment by creativecreatorormaybenot** [comment]
@mraleph Thanks for the in-depth analysis. In the future I will attempt to do rigorous performance testing using a self-contained sample for reproduction when filing an issue. I see that performance issues are more complex.
