### ISSUE TITLE
Analyzer - CFE type inference inconsistency

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#39030]
The following code produces different inference behavior in the analyzer and CFE. I'm not sure which one is correct or if this is specified explicitly. @eernstg 

This pattern has come up in the process of porting dart:math for NNBD. The type of the parameter of `A.f()` was originally `dynamic` and both tools agreed. While porting the type of the parameter was changed to be `Object`.

```dart
class A {
  final x = 100;
  int f(Object y) => 1;
}

class B {
  int f(y) => 2;
}

class C extends B implements A {
  final x = 3;
  int f(y) {
    if (y is! A) {
      return x;
    }
    return y.x;
  }
}

void main() {
  var b = B();
  b.f(A());
}
```

The `dartanalyzer` produces no errors. The type of the `y` parameter of `C.f()` is inferred to be `dynamic`.

On the other hand the CFE produces the following error:
```
Error: The getter 'x' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'x'.
    return y.x;
```

The dump of the dill file shows that the parameter is inferred to be `Object`.

```
import self as self;
import "dart:core" as core;

class A extends core::Object {
  final field core::int* x = 100;
  synthetic constructor •() → self::A*
    : super core::Object::•()
    ;
  method f(core::Object* y) → core::int*
    return 1;
}
class B extends core::Object {
  synthetic constructor •() → self::B*
    : super core::Object::•()
    ;
  method f(dynamic y) → core::int*
    return 2;
}
class C extends self::B implements self::A {
  final field core::int* x = 3;
  synthetic constructor •() → self::C*
    : super self::B::•()
    ;
  method f(core::Object* y) → core::int* {
    if(!(y is self::A*)) {
      return this.{self::C::x};
    }
    return invalid-expression "tests/language_2/nnbd/type_promotion/mixed_mode_type_promotion_test.dart:24:14: \u0027[31mError: The getter 'x' isn't defined for the class 'Object'.\n - 'Object' is from 'dart:core'.\nTry correcting the name to the name of an existing getter, or defining a getter or field named 'x'.\u0027[39;49m\n    return y.x;\n             ^" as{TypeError} core::int*;
  }
}
static method main() → void {
  self::B* b = new self::B::•();
  b.{self::B::f}(new self::A::•());
}
```

@johnniwinther @stereotype441

**Comment by eernstg** [comment]
> if this is specified explicitly

We do not have a full specification of inference at this point. But in this case the topic is override inference, and for that we have a specification of the [combined interface](https://github.com/dart-lang/language/blob/26ffccba903208ecd138666d206e731f46d62745/specification/dartLangSpec.tex#L4063) of the superinterfaces of a class, and that would be the entity where we look up parameter/return types that we may need in order to perform override inference.

To compute the combined member signature for `f` in the direct superinterfaces of `C` we note that `B` provides `int* Function(dynamic)` and `A` provides `int* Function(Object*)`. The ordering is significant: We will select the textually first one among the minimal ones. So if these two types are considered to be mutual subtypes then we choose the one from `B`: `int* Function(dynamic)`.

This is likely to be the "old analysis" (presumably, there was no error).

Apparently, the new analysis considers `int* Function(Object*)` to be a proper subtype of `int* Function(dynamic)`, which would be the case if `Object*` is considered to be a proper _supertype_ of `dynamic`. With that, there is only one minimal signature, which is the one from `A`, and then we get that.

But `Object*` should not be considered a proper supertype of `dynamic`, so that explanation would indicate that there is a bug in the computation of the subtype relationship.

**Comment by johnniwinther** [comment]
@stefantsov

**Comment by eernstg** [comment]
Surprisingly, the front end seems to require that the member signatures for a given member from superinterfaces must be identical:

```dart
class A {
  int f(int y) => 1;
}

class B {
  int f(num y) => 2;
}

class C extends A implements B {
  int f(y) => 0; // Inferred parameter type should be `num`.
}

void main() {
  var c = C();
  c.f(1.5);
}
```

The analyzer reports no issues for this (so the inferred parameter type must be `num`, or `c.f(1.5)` would have been flagged). But with `dart` we get the following error:

```
n026.dart:10:9: Error: Can't infer a type for 'y' as some of the inherited members have different types.
Try adding an explicit type.
  int f(y) => 0; // Inferred parameter type should be `num`.
        ^
```

This seems to imply that the front end refuses to select the most special signature from the ones offered by superinterfaces (the second step, choosing the textually first one among the minimal ones, doesn't get to run), because we get the error already when it's detected that the signatures aren't all mutual subtypes of each other.

**Comment by eernstg** [comment]
Created https://github.com/dart-lang/language/issues/634 in order to take the discussion about how override inference should work.

**Comment by srawlins** [comment]
Analyzer still produces no errors on the first repro.

**Comment by eernstg** [comment]
I believe we can close this one. @nshahan, please reopen if you disagree.

The original example [here](https://github.com/dart-lang/sdk/issues/39030#issue-510348278) works differently today because `Object` is now a proper subtype of `dynamic`. This implies that the member signature of `C.f` is `int f(dynamic)`, there is no reason to even start thinking about `NNBD_TOP_MERGE` or other tie breakers.

The analyzer (as well as the CFE) are just doing the right thing with the example, considered as a program of today, and it is actually impossible to do anything else (considering the member signature to be `int f(Object)` would violate several common requirements including correct overriding):

- `A.f` has member signature `int f(Object)`.
- `B.f` has member signature `int f(dynamic)`.
- `C.f` has member signature `int f(dynamic)`, which is the least of the available member signatures.

It makes sense to consider the updated version of the program where the delicate choice of a top type is required:

```dart
class A {
  final x = 100;
  int f(Object? y) => 1;
}

class B {
  int f(y) => 2;
}

class C extends B implements A {
  final x = 3;
  int f(y) {
    // y.whatever; // Compile-time error: `y` has type `Object?`, not `dynamic`.
    if (y is! A) {
      return x;
    }
    return y.x;
  }
}

void main() {
  B b = C();
  b.f(A());
}
```

This is again treated correctly by the analyzer (as well as the CFE):

- `A.f` has member signature `int f(Object?)`.
- `B.f` has member signature `int f(dynamic)`.
- `C.f` has member signature `int f(Object?)`.

In this case we need to use `NNBD_TOP_MERGE` to determine the actual parameter type, and we can see [here](https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md#classes-defined-in-opted-in-libraries) that `NNBD_TOP_MERGE(Object?, dynamic) == Object?`.
