### ISSUE TITLE
SDK Error

### ISSUE THREAD

**Issue by rhymelph** [dart-lang/sdk#39078]
## SDK version
2.5.0

You can use this code and run it.
```dart

void main(){
 Test test=Test.fromMap(null);
//throw Exception
}

class Test{
 String id;
 String name;
 Test();

 factory Test.fromMap(Map map)=>map==null?Test():Test()
 ..id=map["id"]
 ..name=map["name"];
}
```
result:
```
E/flutter ( 7677): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 7677): Receiver: null
E/flutter ( 7677): Tried calling: []("id")
....
```

**Comment by eernstg** [comment]
Try this:

```dart
void main() {
  Test test = Test.fromMap(null);
//throw Exception
}

class Test {
  String id;
  String name;
  Test();

  factory Test.fromMap(Map map) => map == null ? Test() : (Test()
    ..id = map["id"]
    ..name = map["name"]);
}
```

The problem is that you are using a cascade whose receiver (that is, `e` in an expression `e..s` where `s` is a cascadeSection) is not the object obtained from `Test()` but rather the one from `map == null ? Test() : Test()`.

It is a known source of confusion that cascades have such a low precedence. However, if we want to allow the right hand side of a cascade assignment to allow for general expressions then the precedence has to be low.

(In `e1..x = e2`, `e2` must be a `expressionWithoutCascade`, and that's nearly any expression).

**Comment by rhymelph** [comment]
@eernstg  thank.

**Comment by eernstg** [comment]
Thanks! For prior discussions about the precence of the cascade syntax, please follow #608 (that's an old issue which was moved here from the SDK repository, so it's much older than the number 608 would imply).
