### ISSUE TITLE
Native executables created with dart2native do not support signing

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#39106]
**NOTE: This issue specifically refers to `dart2native` tool, it does not refer to Flutter on Desktop, as Flutter does not use `dart2native`**

The executables created with `bin/dart2native` use a format that as discussed in the [original issue](https://github.com/dart-lang/sdk/issues/36915#issuecomment-538070879) is not compatible with signing tools such as `codesign` and `signtool`.

**Comment by kulshekhar** [comment]
Would it be possible to assign this issue a label to indicate the priority of this issue from the Dart team's perspective?

To be clear, I'm not looking for a timeline or a particular priority level. Just visibility into the importance of this issue from the Dart dev team's point of view

**Comment by anaisbetts** [comment]
Confirmed this on Windows 10 - signing a binary with `signtool` on Windows will cause it (strangely enough) to act like `dart.exe`

```
C:\Users\ana\code> cat .\test.dart
main() {
        print("Hello world!");
}

C:\Users\ana\code> dart2native -k exe -o test.exe .\test.dart
Generated: c:\users\ana\code\test.exe
C:\Users\ana\code> .\test.exe
Hello world!

C:\Users\ana\code>signtool.exe sign /f mycert.pfx /p sekritPassword .\test.exe
Done Adding Additional Store
Successfully signed: .\test.exe

C:\Users\ana\code> .\test.exe
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

Executes the Dart script <dart-script-file> with the given list of <script-arguments>.

Common VM flags:
--enable-asserts
  Enable assert statements.
--help or -h
  Display this message (add -v or --verbose for information about
  all VM options).
--package-root=<path> or -p<path>
  Where to find packages, that is, "package:..." imports.
```

**Comment by knopp** [comment]
Are there any plans of addressing this? Distributing binaries on Mac and Windows that are not codesigned is not feasible (on Windows you will not get through smart screen, on Mac since Catalina you need hardened runtime and notarization, before catalina there's gatekeeper).

**Comment by dnfield** [comment]
I was hoping to use this to be able to ship a tool from the Flutter engine repo to the Flutter tool.  I won't be able to do so without this feature.

**Comment by tonosama-atlacatl** [comment]
I WANT IT!!!! I Need IT!! I wrote a tool to organize photos/videos/etc... take it from someone that has spent hours helping others install the SDK over the phone... just so they can test my script.

**Comment by mcaubrey** [comment]
Is this a planned feature? It seems like there's been relatively silence on this for the past few months.

**Comment by alexgoussev** [comment]
I very hope this feature will be implemented in the future! I need it!

**Comment by stephantual** [comment]
Adding a vote for this feature, massively important if desktop dart wants to get into the big leagues.

**Comment by haodongh** [comment]
Windows desktop apps without signning, most of people or security software will not trust them.

**Comment by jodinathan** [comment]
is there a workaround to this?

**Comment by Timmmm** [comment]
> I WANT IT!!!! I Need IT!! I wrote a tool to organize photos/videos/etc... take it from someone that has spent hours helping others install the SDK over the phone... just so they can test my script.

It is still possible to run unsigned binaries on Mac and Windows. On Mac you have to right-click the App and select Open (rather than double clicking it), and on Windows you have to click "More info" and then "Run anyway". Completely not obvious, but you shouldn't need to install the SDK just to get a friend to run something!

Plenty of free software is still distributed unsigned on both platforms, though it would obviously be great if code signing was supported.

**Comment by knopp** [comment]
> > I WANT IT!!!! I Need IT!! I wrote a tool to organize photos/videos/etc... take it from someone that has spent hours helping others install the SDK over the phone... just so they can test my script.
> 
> It is still possible to run unsigned binaries on Mac and Windows. On Mac you have to right-click the App and select Open (rather than double clicking it), and on Windows you have to click "More info" and then "Run anyway". Completely not obvious, but you shouldn't need to install the SDK just to get a friend to run something!
> 
> Plenty of free software is still distributed unsigned on both platforms, though it would obviously be great if code signing was supported.

None of these is feasible. Especially if you want to distribute commercial software to general public.

**Comment by Timmmm** [comment]
Not for commercial software, no. I just wanted to point out that you don't need to go as far as installing the Dart SDK to work around this!

**Comment by etx** [comment]
We build a command line app with dart2native the acts as a bridge in Chrome using it's NativeMessaging api. But with the binary in a mac app bundle we can't codesign or notarize 😭

**Comment by gkjpettet** [comment]
This is a compete dealbreaker for our business. How on Earth can one make a commercial product using dart if you can’t code sign?

Has there been any progress here since the issue has been open for a year?

**Comment by thunderstorm010** [comment]
Is this being worked on? There is nearly 2 years past when this issue was created, and there is no PR still.

**Comment by knopp** [comment]
@thunderstorm010, the comment [here](https://github.com/dart-lang/sdk/issues/46445) would sadly suggest otherwise.

**Comment by timotheux** [comment]
So you can't sign the exe, add icon to it, It is not showing any author Metadata like Author, Version, File version, product name, product version etc., which makes it impossible to identify the origin of the exe.

Infact **mraleph** stop short of calling applications produced by dart2native a virus by saying "executables produced by dart2native are not exactly adhering to OS standard executable format (PE on Windows, Mach-O on Mac OS X or ELF on Linux)".

How did this advance past the prototyping stage?

**Comment by maks** [comment]
@timotheux just because it doesn't work for **your** requirements it doesn't follow that the feature isn't useful to others. Dart exe's is *already* useful for a number of production use cases, especially serverside, internal tooling etc.

Sure it would make it *more* useful to be able to be able to sign executables produced the dart2native but please don't imply that it's not fit for purpose already for production use in some environments.

**Comment by timotheux** [comment]
@maks I am not referring to a use case scenario, a requirement or implying that dart2native is not useful. Lets stay on point here.
I have used dart2native for some project where it performed extremely well in the task but couldn't make it to production because it looks like a suspicious exe.

I started wondering why the Dart team will put in a **_huge amount of work and leave out the basics_**. I am simply saying dart2native should not have passed the prototyping stage without an **identity**. Its like having a car on the road without VIN, Make, Model and paint job.

No country will allow such vehicle on their roads because of the inherent dangers.

**Comment by mraleph** [comment]
I suggest to take this discussion somewhere else, because it not relevant for this issue. If you have some concrete use case - it is enough to up vote the issue and leave a comment.  

We recognise the need to support the signing on platforms like Mac OS X and Windows, but so far we did not have resources to make necessary changes. I am hopeful that eventually we will find an opening and address the issue, but we have not made any concrete decisions on this yet.   

@Timotheux 

> I started wondering why the Dart team will put in a huge amount of work and leave out the basics.

That's where you misunderstand how things went - we did an absolute bare minimum of work to support `dart2native`, because we did not have resources to spare on something more robust and that's why its implementation is so hacky. We considerably underestimated the actual demand for this feature. We expected the usage mostly on Linux in server-side environments, and not deployments of CLI programs on Windows/Mac.

**Comment by timotheux** [comment]
@mraleph I will let this rest for now, so that my intensions are not misunderstood. I speak frankly because I love dartlang and dart2native, and I don't want it to end up like the Qt framework (which I once loved too).

**Comment by illia-romanenko** [comment]
@mraleph, thanks for the insight into your decision-making process and your assumptions about the usage. Also, it's great that you see rising demand in codesigning and the new ways of using dart2native. I'm sure that many people are waiting for this feature, so I hope that managers can prioritize. 

In the meantime, could somebody provide a bit more context of that hacky implementation? What is missing, what needs to be done, any relevant documentation (if exists)?

**Comment by mraleph** [comment]
@illia-romanenko `dart2native` is currently implemented in the following way: it takes AOT runtime binary (which is a valid platform executable produced by a native C++ toolchain) and an AOT snapshot (ELF file produced by Dart AOT compiler) and simply concatenates them together. From OS perspective the result is still a valid executable file which simply has a bunch of garbage at the end - but OS can still run it. When AOT runtime binary is run it looks at its own file to see if there is a snapshot appended to it - and if there is then it loads and runs it. 

Problems begin when you try to edit the binary using tools which work with native executable formats (e.g. sign it, change an icon, etc). For these tools the snapshot at the end of the file are simply garbage bytes, so they usually just remove them. 

To fix the problem we need to start properly linking AOT runtime and AOT snapshot together so that the result is a native binary. The simplest way to achieve might be to take a dependency on an existing linker which supports the platforms we support (`lld` probably fits the bill), figuring out few missing pieces (e.g. we need to figure out what format of object files to feed to `lld` and implement necessary support in AOT backend, etc), the figuring out packaging (e.g. I don't think `lld` binary should be shipped with Dart SDK - instead some sort of cloud storage should be setup for on demand SDK components).

**Comment by Levi-Lesches** [comment]
Thanks for the detailed explanation, it helps put the issue in perspective

**Comment by Timmmm** [comment]
Rather than appending it could you add the AOT snapshot as a data segment to the AOT runtime? Then you don't need a linker, just an ELF/Mach-O/PE editor, which is a fair bit simpler (you could probably even write one in Dart fairly easily).

**Comment by mraleph** [comment]
@Timmmm yeah, we considered that as a middle ground option as well (between simple concat and full linking), but it was still way more investment than we could afford to make.

**Comment by lexaknyazev** [comment]
>  ... and simply concatenates them together. From OS perspective the result is still a valid executable file which simply has a bunch of garbage at the end - but OS can still run it. When AOT runtime binary is run it looks at its own file to see if there is a snapshot appended to it - and if there is then it loads and runs it.

A similar approach is also used to create self-extracting archives (e.g. see 7-Zip).

> Problems begin when you try to edit the binary using tools which work with native executable formats (e.g. sign it, change an icon, etc). For these tools the snapshot at the end of the file are simply garbage bytes, so they usually just remove them.

Windows `codesign` tool simply appends another payload at the end thus breaking the following part of AOT snapshot loading:
https://github.com/dart-lang/sdk/blob/f407419d0a43a50132e38fb22d47cf132e7f0d23/runtime/bin/snapshot_utils.cc#L245-L261

Probably, a low-hanging fruit here is to make this code resilient to extra data located after the snapshot.

**Comment by lexaknyazev** [comment]
> AOT runtime binary (which is a valid platform executable produced by a native C++ toolchain)

Strangely enough, Apple's `objdump` does not like it:
```
% objdump -x dartaotruntime

dartaotruntime:	file format mach-o 64-bit x86-64

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: error: 'dartaotruntime': Invalid/Unsupported object file format
```

**Comment by mraleph** [comment]
@lexaknyazev Hmm, that's a bit peculiar. `otool -al` does work on it though.

**Comment by yu-pri** [comment]
> Rather than appending it could you add the AOT snapshot as a data segment to the AOT runtime? Then you don't need a linker, just an ELF/Mach-O/PE editor, which is a fair bit simpler (you could probably even write one in Dart fairly easily).

Hey, @mraleph!

I'm looking into making a workaround for creating signed apps using this option, but I'm not quite sure of the scope of changes for this. 

- Does this approach require modification of the Dart runtime? My guess is that it probably requires changes in how the snapshot is found and loaded, when it is a data segment instead of a lump of bytes at the end of the file. 
- Should it be sufficient to just add the whole snapshot to runtime as a data segment?

**Comment by Timmmm** [comment]
I think you just need to:

1. Find/make a library that is capable of adding segments to ELF/PE/Mach-O files. Something like [LIEF](https://github.com/lief-project/LIEF). 
2. Change the code that appends the snapshot to instead insert it as a new ELF section.
3. Change the code that loads the snapshot to instead find it in the ELF file.

I think the code is around `TryReadAppendedAppSnapshotElf()` and `TryReadAppSnapshotElf()` in `runtime/bin/snapshot_utils.cc`.

**Comment by yu-pri** [comment]
Thanks a lot, @Timmmm!

That's almost verbatim what I've had in mind, wanted to make sure I'm not missing something here.

**Comment by yu-pri** [comment]
@Timmmm, @mraleph 
I've tried doing a small Proof of Concept using @Timmmm's proposed solution.

The process is the following:
1. Modify the `dart-sdk` files to look for the snapshot in a data segment (file offset specified manually for now).
2. Compile the SDK, `dartaotruntime` and the application snapshot.
3. Sign the snapshot.
4. Add the snapshot as a data segment to the runtime file, using [macholib](https://pypi.org/project/macholib/) library.
5. Sign the combined binary.

The above process works well, unless I'm using [hardened runtime](https://developer.apple.com/documentation/security/hardened_runtime) (`codesign -o runtime ...`).

The codesigning process concludes successfully, and if I'm checking the signature using `codesign -dv` -- it says everything's in order. But at runtime the binary gets killed with a `Code Signature Invalid` exception.

Not really sure what might be causing it -- can the runtime be loading some non-signed libraries during runtime?

**Comment by mraleph** [comment]
> Not really sure what might be causing it -- can the runtime be loading some non-signed libraries during runtime?

It loads the snapshot which (as it is currently implemented) requires to map parts of the binary as executable pages even though originally it was not executable - hence the need for  `com.apple.security.cs.allow-unsigned-executable-memory` as you have discovered.

**Comment by BobEvans** [comment]
> **UPD2**: Managed to successfully notarize the binary, and run it via terminal on several Mac machines without getting security popups. Will see if we'll be able to make a PR sometime later.

@yu-pri 
Would you be willing to share your code? I have exactly the same need and would like to not reinvent the wheel.

**Comment by illia-romanenko** [comment]
@BobEvans I worked with @yu-pri on this - and it's rather in the POC stage, so nothing really to share. A lot of steps are just manual to make it work. Currently, that's where we will leave it until it is required for the project we are working on. If you need any tips, you can ping me directly via some social media.

**Comment by BobEvans** [comment]
@illia-romanenko Thanks Illia. I got it working for our case as well.

**Comment by a-siva** [comment]
Any progress updates on this ?

**Comment by techouse** [comment]
Looks like [this got merged](https://github.com/dart-lang/sdk/commit/6ef426d7df7089c033078b2c24b5ab9c14d2dfb9) and is coming in Dart 2.17.0 🚀

**Comment by anaisbetts** [comment]
@sstrickl It seems like you don't have to go super fancy, you could just embed the snapshot as an embedded Resource rather than try to do Tricky things with PE images

**Comment by Ehesp** [comment]
After upgrading to Dart 2.17.0, the commit @techouse referenced causes executables to not sign correctly for me (MacOS).  [This code](https://github.com/dart-lang/sdk/commit/6ef426d7df7089c033078b2c24b5ab9c14d2dfb9#diff-db2031e20cc82df5d18bd3662288aaf2ead92b9452e9ad130b3f0e98a90d931cR314-R332) is erroring with `is already signed`.

**Comment by sstrickl** [comment]
> After upgrading to Dart 2.17.0, the commit @techouse referenced causes executables to not sign correctly for me (MacOS). [This code](https://github.com/dart-lang/sdk/commit/6ef426d7df7089c033078b2c24b5ab9c14d2dfb9#diff-db2031e20cc82df5d18bd3662288aaf2ead92b9452e9ad130b3f0e98a90d931cR314-R332) is erroring with `is already signed`.

Thanks for letting us know! Just so I can narrow things down a bit, can you (@Ehesp) give me the following information:

* OS X version
* Processor type (Intel, M1)
* Result of running `codesign -v -d` on the `dartaotruntime` executable in your Dart SDK

To explain, the code above expects `dartaotruntime`, if signed, to have been signed with an ad-hoc linker-signed signature that'll end up being copied over into the new executable. We then need to update that signature to account for the new contents, but `codesign` should overwrite linker-signed signatures without having to use `-f` to force it.

If that's not true in some cases, then we can probably work around it by simply adding the `-f` flag to the `codesign` call you pointed at to forcibly overwrite _any_ existing signature with a new ad-hoc linker-signed one. However, before doing that, I'd like confirmation that's what's happening and that it's not a more subtle issue that change won't address.

**Comment by sstrickl** [comment]
Actually, no need.  Our official binaries are indeed signed, whereas the binaries used by the testing framework are built fresh and thus linker-signed only. Will create a quick CL to add the `-f` flag.

**Comment by Ehesp** [comment]
Ahh thanks! Please let me know if you need any of that info again.

**Comment by Ehesp** [comment]
@sstrickl not sure if releases are cut manually, but if you could get the fix into a new release I can give it a go.

**Comment by sstrickl** [comment]
@Ehesp if you'd like to test the fix, the latest dev channel binary build at https://dart.dev/get-dart/archive should include the fix. If anyone's interested in trying out the Windows side of things, that dev channel build should also include those changes.

Going ahead and marking this as closed since standalone executables for both Windows and Mac OS X should now be signable, but please let us know if anyone runs into any issues :)

**Comment by liudonghua123** [comment]
Nice work. I can also add an icon to the native executable. see https://github.com/electron/rcedit/issues/91#issuecomment-1084781673, https://github.com/dart-lang/sdk/issues/45373.

**Comment by dnfield** [comment]
@christopherfujino fyi this is what we were discussing yesterday

**Comment by mit-mit** [comment]
macOS steps:
   * sign: `codesign -s [cert ID] bin/[entrypoint].exe`
   * check: `codesign -dv --verbose=4 bin/[entrypoint].exe`

**Comment by jmagman** [comment]
> macOS steps:

I tested this on `flutter_tools` on dart `2.17.0-259.0.dev` on Xcode 13.3 (beta 3), x64 macOS 12.3.

```sh
$ dart compile exe flutter/packages/flutter_tools/bin/flutter_tools.dart
Info: Compiling without sound null safety
Generated:flutter/packages/flutter_tools/bin/flutter_tools.exe
$ codesign -s [cert ID] flutter/packages/flutter_tools/bin/flutter_tools.exe
$ codesign -dv --verbose=4 flutter/packages/flutter_tools/bin/flutter_tools.exe
Executable=/path/to/flutter/packages/flutter_tools/bin/flutter_tools.exe
Identifier=flutter_tools
Format=Mach-O thin (x86_64)
CodeDirectory v=20400 size=184305 flags=0x0(none) hashes=5754+2 location=embedded
VersionPlatform=1
VersionMin=658688
VersionSDK=721152
Hash type=sha256 size=32
CandidateCDHash sha256=7ca0370ce25ce274ecab0798ce26d1c5aa75dd69
CandidateCDHashFull sha256=7ca0370ce25ce274ecab0798ce26d1c5aa75dd69cb0e7ee8b39b975229745d9c
Hash choices=sha256
CMSDigest=7ca0370ce25ce274ecab0798ce26d1c5aa75dd69cb0e7ee8b39b975229745d9c
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=3784704
Executable Segment flags=0x1
Page size=4096
CDHash=7ca0370ce25ce274ecab0798ce26d1c5aa75dd69
Signature size=4782
Authority=Apple Development: [Correct cert name]
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=Mar 31, 2022 at 11:12:59 AM
Info.plist=not bound
TeamIdentifier=[Correct Team ID]
Sealed Resources=none
Internal requirements count=1 size=176
```

Signature is valid and satisfies its Designated Requirement.

Note: `[cert ID]` can be found via `security find-identity -p codesigning`.

**Comment by khainke** [comment]
> @Ehesp if you'd like to test the fix, the latest dev channel binary build at https://dart.dev/get-dart/archive should include the fix. If anyone's interested in trying out the Windows side of things, that dev channel build should also include those changes.
> 
> Going ahead and marking this as closed since standalone executables for both Windows and Mac OS X should now be signable, but please let us know if anyone runs into any issues :)

Is this fix already released / on the stable channel?

**Comment by mit-mit** [comment]
It is not (but we're getting close). You can try it using 2.17 from the beta channel.

**Comment by khainke** [comment]
I have problems signing dart executables with `codesign` for macOS with enabled hardened runtime ...

```dart
>> dart compile exe -o bin/test bin/test.dart
Info: Compiling with sound null safety
Generated: /Users/user/projects/dart_playground/bin/test
>> ./bin/test
Hello World
>> codesign --sign "Cert" --identifier com.example.test -o runtime -f --timestamp bin/test
bin/test: replacing existing signature
>> ./bin/test
[1]    79487 killed     ./bin/test
```

dart code:
```
main(){
  print('Hello World');
}
```

**Comment by mraleph** [comment]
@khainke You probably need to preserve entitlements (try adding `--preserve-metadata=entitlements` to `codesign`).

**Comment by khainke** [comment]
That does not work for me, but adding the `com.apple.security.cs.allow-unsigned-executable-memory`works. But why is this necessary?

`Release.entitlements`:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
</dict>
</plist>
```

```
>> dart compile exe -o bin/test bin/test.dart
Info: Compiling with sound null safety
Generated: /Users/user/projects/dart_playground/bin/test
>> codesign --sign "Cert" --identifier com.example.test -o runtime --entitlements lib/macos/Release.entitlements --timestamp bin/test
>> ./bin/test
Hello World
```

**Comment by mraleph** [comment]
> But why is this necessary?

Because snapshot itself is still not represented as a native format. I have not reviewed the implementation but I guess we still just put an ELF file into a Mach-O file (though respecting Mach-O structure now) and then use our ELF loader to load it up. 

To drop `allow-unsigned-executable-memory` we need to put snapshots executable code into the text segment.

**Comment by techouse** [comment]
Just tested it with Dart 2.17.0 and it works like a charm :)

```bash
#!/usr/bin/env bash

dart compile exe bin/main.dart -o build/app
codesign -v -s XXXXXXXXXX -i com.example.test build/app
codesign -dv --verbose=4 build/app
```

**Comment by johnpryan** [comment]
For more information about signing, see the [signing section](https://dart.dev/tools/dart-compile#signing) on the dart compile page.

**Comment by techouse** [comment]
I can confirm that I've successfully signed and notarised a compiled binary with Apple following this [exhaustive StackOverflow answer](https://stackoverflow.com/questions/64652704/how-to-notarize-an-macos-command-line-tool-created-outside-of-xcode#answer-64733472). 🚀

**Comment by ArtGangsta** [comment]
It's a bit silly to have implemented the feature in this way, tagging the binary at the end of created EXE.  That's something we did back in the 90s.   
It was clearly done out of ignorance and convenience.   The proper solution was to include an alternative which requires native toolking support, and simply "sucks in" the binary into the executable in some form.   I mean, you can literally link in any arbitrary file into an executable, and it's available as an "extern" from C.  You can determine what it is using objdump -t (from gcc).
Rather than delivered the "exe" that you concact with, you would have delivered the object files for that platform, and require the developer to have at least a linker available -- or maybe figure out a way to include a redistributable compatible linker with the SDK.

Honestly for something as ambitious as dart2native, the incremental work would have been trivial compared to the overall effort, and certainly would have completed the story.   Let's be honest -- it wasn't considered until the alternative approach was working, and only then we ran out of time.

**Comment by Rexios80** [comment]
I'll make this super easy for future people that end up here:

1. Get a "Developer ID Application" certificate
  a. Open Xcode
  b. Go to Preferences > Accounts > Manage Certificates
  c. Click the "+" button and create one
2. Install [gon](https://github.com/mitchellh/gon)
  a. `brew install mitchellh/gon/gon`
3. Create a `gon.json` file
```json
{
    "source": [
        "{your_app_exe}"
    ],
    "bundle_id": "{com.example.yourDartApp}",
    "apple_id": {
        "username": "{your email}",
        "password": "@env:NOTARIZATION_PASSWORD",
        "provider": "{your App Store Connect Team ID}"
    },
    "sign": {
        "application_identity": "Developer ID Application: {your team name}",
        "entitlements_file": "Release.entitlements"
    },
    "zip": {
        "output_path": "build.zip"
    }
}
```
4. Create a `Release.entitlements` file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
</dict>
</plist>
```
5. Go to https://appleid.apple.com/account/manage and create an "App-Specific Password"
6. Run in terminal: `export NOTARIZATION_PASSWORD={your_app_specific_password}`
7. Run in terminal: `gon gon.json`

And that should be it

**Comment by Rexios80** [comment]
Okay apparently that doesn't work even though all the tools are saying the thing is signed properly...

**Comment by techouse** [comment]
@Rexios80 I've used that technique of mine a few days ago and it works like a charm.

Check your certificates (you are probably aware of the fact that you need a paid Apple Developer license) and entitlements.

**Comment by Rexios80** [comment]
Do I need any entitlements besides `com.apple.security.cs.allow-unsigned-executable-memory`? Before I added that my app just instantly crashed even after bypassing the unidentified developer warnings. Now my app runs fine, but macOS still claims it's unidentified. I would imagine notarization would fail if my certificates were invalid.

**Comment by techouse** [comment]
@Rexios80 did you get an email from Apple saying that your binary has been successfully notarized?

**Comment by Rexios80** [comment]
@techouse Yes that's why this is so weird

**Comment by Rexios80** [comment]
Also the notarization logs show no issues

**Comment by cbenhagen** [comment]
> To drop `allow-unsigned-executable-memory` we need to put snapshots executable code into the text segment.

@mraleph is there already an open issue for this?
