### ISSUE TITLE
Please merge #e65d95e into stable channel

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#39243]
**commit(s) to merge**: e65d95e8c869a6ef26a5fdb6951267ea06c3e6fe

**merge instructions**: clean merge

**reason**: addresses a scalability/OOM blocker for a large external customer. This reduces the total memory used by dart2js when compiling their app from 20G to 15G (approx). See #27883 for details.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @vsmenon

**Comment by robbecker-wf** [comment]
I'm not sure if this is waiting for 2.7, but if that's going to be a while, is there any chance we could get this released as a 2.6.1 patch release?

**Comment by athomas** [comment]
The current plan is to release a 2.6.1 early next week.

**Comment by robbecker-wf** [comment]
I'm seeing 2.6.1 in the CHANGELOG https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md
but not in the available downloads or on brew. Do I just need to be more patient or is something stuck?

**Comment by robbecker-wf** [comment]
Oh hey, there it is! Thanks!

**Comment by athomas** [comment]
Released in 2.6.1.

**Comment by athomas** [comment]
@robbecker-wf Yes, you need to be more patient :)

The changelog needs to be updated before the release is published. So that will always precede the release. Also, there may be issues during the release (e.g. unexpected test failures, one of the release channels being down) that might delay the release further.
