### ISSUE TITLE
Can the dart file compress file size like golang?

### ISSUE THREAD

**Issue by biij5698** [dart-lang/sdk#39319]
The golang can compress file size use command:
go build -ldflags "-s -w"
Can the dart file do the same thing?

**Comment by keertip** [comment]
@biij5698, Please describe what you are looking to do with Dart so we have enough information to answer your question/s.

**Comment by biij5698** [comment]
I want to reduce the size of the file what compiled by "dart2native -k exe/aot"

**Comment by keertip** [comment]
@cskau-g

**Comment by cskau-g** [comment]
@mraleph

**Comment by muv1** [comment]
https://github.com/dart-lang/sdk/issues/38731

**Comment by mkustermann** [comment]
We do have support for stripping symbolic information of the Dart application in our AOT compiler:

```
% out/ReleaseX64/dart-sdk/bin/dart2native --save-debugging-info=hello.debug_info hello.dart
Generated: ...
% /bin/ls hello.exe
5567424 hello.exe

% out/ReleaseX64/dart-sdk/bin/dart2native hello.dart          
Generated: ...
% /bin/ls -l hello.exe
 5872552 hello.exe
```

Though since the symbolic information was split to a separate file, the symbols will be missing when running the application. This means that stack traces of the application will contain addresses (instead of symbolic information). The addresses can be translated via `package:native_stack_traces` and the `hello.debug_info` file.

**Comment by mkustermann** [comment]
We do not have a specific `-Os` flag for instructing our AOT compiler to try to produce smaller machine code. Though our AOT compiler is actually tuned for producing smaller code size by-default already (it's a big focus area for us).

Closing this issue since the original question got answered.
