### ISSUE TITLE
Equality operator overload

### ISSUE THREAD

**Issue by vaind** [dart-lang/sdk#39428]
Dart SDK Version: 2.6.1, Linux

We're creating a query condition builder and using some operator overloads in addition to standard calls. The thing is, with the equality operator, we have encountered an issue where it is reported by the linter as an error, though the code works just fine.

> https://github.com/objectbox/objectbox-dart/issues/43
 > Queries currently use some handy operator overloads, e.g. `box.query(Note_.text == "text")` in addition to the standard `box.query(Note_.text.equals("text"))`. 
> Equality seems to be a special case, causing a linter issue. Make sure it's really OK to use it the way we do, otherwise, we'll have to drop it.
> 
> Linter reports:
> ```
> error: 'QueryStringProperty.==' ('Condition Function(String)') isn't a valid override of 'Object.==' ('=='). (invalid_override at [objectbox] lib/src/query/query.dart:86)
> ```
> ```
> info: Equality operator `==` invocation with references of unrelated types. (unrelated_type_equality_checks at [objectbox] test/query_test.dart:52)
> ```
> 
> Also, we clearly break the requirements given here: https://api.dartlang.org/stable/2.5.2/dart-core/Object/operator_equals.html

The question is: is this a linter issue or is it **forbidden** to overload equality operator in this way (which means it shouldn't be allowed by the compiler then?).

**Comment by lrhn** [comment]
The `==` operator has the same override rules as any other function.

That means that the signature of `bool operator==(Object)` must be satisfied by the override as well. That does not leave much room to wiggle in, the only really different override that is allowed is `Null operator==(Object)`. (You can change the parameter type to `dynamic` or `void`, but that's not really a different signature for users).

So, the error is correct. If it "works just fine", you have found a bug in our compilers. It should be a *compile-time error*, and that is unrelated to lints.

Also not that even if you manage to fit into the type of `operator==`, code like `box.query(Note_.text == null)` would not call your `==` operator. The language's `==` operator first checks if either side is `null`, and only if not does it call the `operator==` method on the left operand. It's not *just* a method like any other.

**Comment by eernstg** [comment]
There is one more possibility, which is touching on a topic that may or may not be in line with your style guides: You could use a `covariant` parameter to force the typing that you indicate:

```dart
abstract class CheckedEquality {
  operator ==(covariant CheckedEquality other);
  factory CheckedEquality() = _Implementation;
}

class _Implementation implements CheckedEquality {
  operator ==(Object other) {
    if (other is! CheckedEquality) return false;
    return super == other; // Whatever is appropriate for this class.
  }
}

main() {
  int i = 42;
  String s = 'Hello';

  // In general, you don't get errors for `==` on differently typed objects.
  if (i != s) print("No type errors here.");
  
  // `CheckedEquality` is special in that its `==` is more strict.
  var ce1 = CheckedEquality(), ce2 = CheckedEquality();
  if (ce1 != ce2) print("No type errors for equality on its own type.");
  // But `ce1 == s` and `ce1 != s` is a compile-time error.

  // `==` invokes a method, though, so it is asymmetric: There is no
  // protection against comparing other types to `CheckedEquality`.
  if (s != ce1) print("Warning: Nothing stops us here.");
}
```

(Note that `!=` is defined in terms of `==`, so we can use one or the other.)

The point is that the parameter of `operator ==` in `CheckedEquality` is _covariant_. This allows you to make stronger requirements than the ones that are made by the overridden declaration. In general, any use of a `covariant` modifier on a formal parameter gives rise to dynamic checks (so your style guides might say "don't ever use `covariant`!"). But in this case it does _not_ give rise to any dynamic checks, because `CheckedEquality` is abstract and the actual implementation is an instance of `_Implementation` whose `operator ==` again has the safe parameter type `Object`.

This means that you'll get the static checks (such that `ce1 == s` and `c1 == true` etc. are compile-time errors), and the instances of `_Implementation` will still work correctly (and return false rather than throwing) when compared with other objects under a more general type.

That said, I still think that it is a questionable design to have an `operator ==` which is not modeling equality&mdash;if `QueryStringProperty.==` accepts a `Condition Function(String)` then it is definitely not testing equality. The resulting code might look nice, but I'd suggest that you use something other than `==` to express this "accept a function that will do something which yields an equality result

**Comment by vaind** [comment]
Thanks for the responses. I guess we will drop it then. It's a pity because it works nicely in swift...
