### ISSUE TITLE
Dart Analyzer error "return type 'Object' isn't a 'Future<bool>'" when it's getting Future<bool>

### ISSUE THREAD

**Issue by BeDaut** [dart-lang/sdk#39561]
This tracker is for issues related to:

* Analyzer

In your issue, please include:

* Dart SDK Version (`dart --version`)
Dart_ VM version: 2.5.0 (Fri Sep 6 20:39:27 2019 +0200) on "macos_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
macOS Catalina

------------------------------------------------------------------

Hi, I get the following error
```
error • The return type 'Object' isn't a 'Future<bool>', as defined by the method 'isCondition' • packages/native_condition/lib/conditions.dart:42:59 • return_of_invalid_type
```
when I do this:

```
static Future<bool> isCondition() async => Platform.isIOS ? _channel.invokeMethod(_isConditionMethod) : false;
```

if I'll do it like this there will be no error:

```
static Future<bool> isCondition() async {
    if (Platform.isIOS) {
      return _channel.invokeMethod(_isConditionMethod);
    } else {
      return false;
    }
  }
```

async already wraps result in Future, but analyzer marks it as an error

**Comment by bwilkerson** [comment]
The wording of the message is misleading, and it clearly needs to be improved. The problem is that the static type of the returned value isn't `bool`. Unfortunately, the declared return type of `Future<bool>` wasn't unwrapped when composing the message. So, the message is poor but there is an issue in your code.

What does `invokeMethod` return?

The most likely cause for this (though I can't say for sure without knowing the answer to the question above) is that the least upper bound (LUB) of the return type of `invokeMethod` and `bool` is `Object`. (The LUB matters because the type of `e1 ? e2 : e3` is the LUB of the types of `e2` and `e3`.)

If that's the case, then you could also remove the diagnostic by casting the result of `invokeMethod` to `bool`.

**Comment by BeDaut** [comment]
@bwilkerson yeah, sorry, I'll try to be more clear.

My problem is when I use this function alone like this:
```
static Future<bool> isCondition() async => _channel.invokeMethod(_isConditionMethod);
```

there're no errors, and also if I'll do this:

```
static Future<bool> isCondition() async => Platform.isIOS ? _channel.invokeMethod(_isConditionMethod) : Future.value(false);
```
there're no errors too. 
What's confusing is that if I do this:

```
static Future<bool> isCondition() async => Platform.isIOS ? _channel.invokeMethod(_isConditionMethod) as bool : false;
```
it will also work :/

**Comment by bwilkerson** [comment]
It all hinges on this question: What does `invokeMethod` return?

**Comment by BeDaut** [comment]
@bwilkerson Future<dynamic>, I see
