### ISSUE TITLE
Dart and analyzer produce different results for class "A<X extends A<X, Y>, Y extends A<dynamic, A<X, Y>>>"

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#39574]
* Dart VM version: 2.7.0-dev.1.0 (Wed Nov 20 12:57:54 2019 +0100) on "windows_x64"
* OS: Windows 10

The following code source:
``` dart
class A<X extends A<X, Y>, Y extends A<dynamic, A<X, Y>>> {}
```
produces different results with analyzer and dart.

Analyzer passes with this:
> $> dartanalyzer test.dart
> Analyzing test.dart...
> No issues found!

Whereas dart throws a compile error:

> $> dart test.dart
> test.dart:1:28: Error: Type argument 'A<X, Y>' doesn't conform to the bound 'A<dynamic, A<X, Y>>' of the type variable 'Y' on 'A'.
>  \- 'A' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
> class A<X extends A<X, Y>, Y extends A<dynamic, A<X, Y>>> {}
>                            ^
> test.dart:1:28: Context: This is the type variable whose bound isn't conformed to.
> class A<X extends A<X, Y>, Y extends A<dynamic, A<X, Y>>> {}
>                            ^

**Comment by eernstg** [comment]
We have the general rule that all types in a program must be well-bounded, that is: regular-bounded or correctly super-bounded. For a bound in a type parameter declaration we can use the declared subtype relationships during the proof of well-boundedness (because any instance that exists will have a type which is regular-bounded, such a type cannot be super-bounded).

So this means that `A<X, Y>` must be well-bounded assuming `X <: A<X, Y>` and `Y <: A<dynamic, A<X, Y>>`. But those requirements are exactly the assumed relationships, so that's OK.

`A<dynamic, A<X, Y>>` is not regular-bounded: It is required that `dynamic <: A<...>`, which could never be true (no matter the type arguments). To be super-bounded, it is required that `A<Null, A<X, Y>>` is regular-bounded (we would use `Never` rather than `Null` in an nnbd context, otherwise the same).

So we have the mapping `X --> Null`, `Y --> A<X, Y>`, so the bounds are satisfied iff `Null <: A<Null, A<X, Y>>` (which is true, and the variant with `Never` is true under nnbd) and `A<X, Y> <: A<dynamic, A<Null, A<X, Y>>>`. So we must have `Y <: A<Null, A<X, Y>>`. The only thing we know about `Y` is the assumed bound `Y <: A<dynamic, A<X, Y>`, so we must have `A<dynamic, A<X, Y>> <: A<Null, A<X, Y>>`. But that is not true, because it requires `dynamic <: Null`.

So it is correct for `dart` to report an error, and the analyzer should do it as well.

Another issue in the same topic area is that the analyzer rejects _some_ super-bounded types as bounds:

```dart
class A<X extends num> {}
class B<X extends A<Object>> {} // Error: "'Object' doesn't extend 'num'".
class C<X extends A<dynamic>> {} // No issues.
```

A type like `A<Object>` (nnbd: `A<Object?>`) is correctly super-bounded, and it is allowed to use it in a "descriptive" location (that is, when it is describing instances that are created elsewhere, e.g., as a type annotation on a parameter), but not in a "prescriptive" location (where it specifies how to create an instance, e.g., `new A<Object>()` is an error). In particular, a type used as a bound can be super-bounded.

**Comment by iarkh** [comment]
This bug is still reproducible with Dart SDK version: 2.11.0-180.0.dev (dev) (Tue Sep 29 19:40:19 2020 -0700) on "windows_x64"

Failing co19 test is: LanguageFeatures/Instantiate-to-bound/class/static/class_l2_t04.dart

**Comment by srawlins** [comment]
Analyzer now produces an error:

> '`A<X, Y>`' doesn't conform to the bound '`A<dynamic, A<Never, A<X, Y>>>`' of the type parameter 'Y'.
