### ISSUE TITLE
_WebSocketProtocolTransformer.add() doesn't properly handle Uint8List.view() args

### ISSUE THREAD

**Issue by GreenAppers** [dart-lang/sdk#39589]
Instead of `_payload.add(new Uint8List.view(buffer.buffer, index, payloadLength));`

in https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/websocket_impl.dart#L222

this should probably be `_payload.add(new Uint8List.view(buffer.buffer, buffer.offsetInBytes + index, payloadLength));`

Dart VM version: 2.7.0-edge.7707c2a84c85aadb08ff625d4c30486b5f078bd2 (Sat Nov 30 18:08:21 2019 +0000) on "macos_x64"

**Comment by GreenAppers** [comment]
To add a little more context, I implemented io.Socket to use a SSH tunnel: https://github.com/GreenAppers/dartssh/blob/master/lib/socket_io.dart#L73

It would be most optimal to call controller.add() with a Uint8List.view() but this is not currently possible.  (And results in strange failure behavior that took me awhile to debug)

I have also made the same mistake (took view of Uint8List failing to account for when the input is itself a view), and have a utility function to protect against it: https://github.com/GreenAppers/dartssh/blob/master/lib/serializable.dart#L15
A broader fix could be considered.

I tested the patch described in the initial report for several cases successfully.  I also signed the contributor release and attempted to upload a patch for review but it seems that I lack permissions to do so.  Thanks!

**Comment by sortie** [comment]
Hi @GreenAppers, thanks for reporting this issue and coming up with a fix! I can confirm that your analysis seems right and buffer.offsetInBytes should've been used.

I can make the change for you if you'd like? Alternative you can upload a pull request here on github, which will verify your CLA and automatically migrate the change to our Gerrit review tool. You can also upload the change changelist directly to https://dart-review.googlesource.com using the `git cl upload` command from depot\_tools as described in [CONTRIBUTING.md](https://github.com/dart-lang/sdk/blob/master/CONTRIBUTING.md). You should already have all the right permissions for that (you'll need to create an account first). If our procedure for contributing isn't working, I'll be happy to debug it, it'll be useful if you can say exactly what's going wrong. But again, I can make the change for you in the SDK if you prefer that?

You seem to have discovered a systemic issue. The `Uint8List.view` API doesn't lend itself well to nested use cases and it's easy to get it wrong. A quick search of our codebase flags lots of uses of the API without `offsetInBytes`. Many of them seem correct at a glance, but there's probably other mistakes like the one you encountered here. We'll probably want to review these cases and think about how to avoid this problem in the future since it seems like an easy mistake to make.

**Comment by GreenAppers** [comment]
Hi @sortie, thanks for looking into this issue!

Sure!  Thanks for taking over.  (Oops I think I missed creating the account when I tried uploading.  In the future I'll try sending a normal PR.)

I think adding a `Uint8List.viewUint8List()` would help.  Or if allowing breaking changes, rename `Uint8List.view` to `Uint8List.viewBuffer` and make `Uint8List.view` accept `Uint8List` arguments instead of `ByteBuffer`.  A breaking change would trigger/coerce a review of those tricky cases.

**Comment by sortie** [comment]
We have a [breaking change policy](https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md). I discussed some potential API improvements with @lrhn that could be done in a compatible fashion.

**Comment by sortie** [comment]
I gave it a try to fix all such instances in the SDK libraries at <https://dart-review.googlesource.com/c/sdk/+/127165>. Thanks for reporting this issue!

**Comment by sortie** [comment]
Alright, I landed the fix. It won't be in the upcoming 2.7 release, but it will be in the next full release after that. It'll appear in a future dev release towards the next full release, or you can build Dart from git to get the fix now. Thanks for reporting the issue!

We drafted up a proposal for a TypedData.sublistView() API at <https://dart-review.googlesource.com/c/sdk/+/127321> to avoid this kind of problem in the future.
