### ISSUE TITLE
Incorrect SDK types for `MediaQueryList.addListener`

### ISSUE THREAD

**Issue by peterjosling** [dart-lang/sdk#39584]
The SDK has the signature for `MediaQueryList.addListener` as `void Function(dynamic Function(Event))`, as it's expecting the parameter to be a `MediaQueryListEvent`. This is correct in Chrome and Firefox, but in Safari and Edge, the listener method is called with a `MediaQueryList`, and `MediaQueryListEvent` doesn't exist.

Both `MediaQueryList` and `MediaQueryListEvent` have a boolean `matches` property, but they don't share a common interface.

* Dart SDK Version (`dart --version`)
2.7.0-edge+google3-v2

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Safari, Edge

**Comment by vsmenon** [comment]
We probably need to type this as:
`void Function(dynamic Function(Object))`
then.

**Comment by sigmundch** [comment]
I'm closing this issue as likely now obsolete. That said, I'd like to share some general comments that are very applicable here.

In the last few years we have developed and improved the JS-interop solution for Dart so that it can be used to interact with browser APIs directly. Any API that is not exposed properly can be worked around with a direct JS-interop access instead. We also are moving away from `dart:html`, and have evolved `package:web` as a replacement. It is based on JS-interop, generated from the Web IDLs (rather than Chrome IDLs) so they are likely to have fewer browser incompatibilities, and it will be supported on Wasm (unlike dart:html).
