### ISSUE TITLE
Migration incorrectly assumes dynamic toString could return null

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39609]
The migration engine handles the following code incorrectly:
```dart
String f(dynamic x) => x.toString();
```
It reasons that since the receiver of the `toString` call is dynamic, the return value could be anything.  But this is not true, because all implementations of `toString` must be correct overrides of `Object.toString`, whose return type is non-nullable `String`.

The logic for handling dynamic invocations should understand that when invoking a method on `Object` *with a parameter list shape that fits the declaration in `Object`*, we can rely on the type guarantees made by the declaration in the `Object` class.

(Edit on Dec 3 2019: added italicized text, as recommended in https://github.com/dart-lang/sdk/issues/39609#issuecomment-561128617)

**Comment by lrhn** [comment]
We require the type inference to recognize this already, so `var x = (o as dynamic).toString();` should infer `String` for `x`.

**Comment by eernstg** [comment]
> since the receiver of the `toString` call is dynamic, the return value could be anything .. [but] ..
> all implementations of `toString` must be correct overrides of `Object.toString`,
> whose return type is non-nullable `String`.

We do actually cover this case in detail [in the spec](https://github.com/dart-lang/language/blob/b246aa44712fe73dd4fc8a074347b9cfbd61454a/specification/dartLangSpec.tex#L17815), since 30c5b39d4e0e7672d05df6aebba73254dd7ee770, Nov 2018.

The rule says that the static type of `x.toString()` in [the example](https://github.com/dart-lang/sdk/issues/39609#issue-531528406) is the return type of the method `toString` in the interface of `Object`, so with nnbd the type is the non-nullable type `String`. But this outcome is only guaranteed when the invocation fits the actual member provided by the receiver.

In the remaining cases (that is: when there are fewer positional parameters than required, or more than supported, or there is a named parameter whose name is not present in the member signature from `Object`, or, with nnbd, if a `required` named parameter is omitted), the type of the invocation is `dynamic`. For instance, `x.toString(foo: true)` has type `dynamic`. It could still work, though, and it would be unsound to assume that the type of the returned value is `String`:

```dart
class A {
  noSuchMethod(_) => 42;
}

main() {
  dynamic d = A();
  var x = d.toString(foo: true);
  print(x.isEven); // Prints 'true'.
}
```

There is nothing wrong in the execution of this program, `d.toString(foo: true)` must invoke `noSuchMethod`, and there should not be a dynamic check enforcing that the returned result is a `String`. So we have to go back to a top type as the return type, and `dynamic` is the natural choice in this very dynamic situation.

> when invoking a method on `Object`, we can rely on the type guarantees
> made by the declaration in the `Object` class.

So we need to twist that rule slightly: '.. invoking a method on `Object` with a parameter list shape that fits the declaration in `Object` ..'.

**Comment by stereotype441** [comment]
> So we need to twist that rule slightly: '.. invoking a method on `Object` with a parameter list shape that fits the declaration in `Object` ..'.

Thanks for the clarification!  I've updated the text of the bug.

**Comment by srawlins** [comment]
Related (possibly duplicate) bug: https://github.com/dart-lang/sdk/issues/39701
