### ISSUE TITLE
Type annotation check for parameter which is covariant-by-declaration fails

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39633]
Consider the following program:

```dart
abstract class S1 { void foo(covariant p); }
abstract class S2 { void foo(Object p); }
abstract class S3 { void foo(int p); }
abstract class B implements S1, S2 {}

class C extends B implements S3 {
  void foo(num p) {}
}

void main() {
  C().foo(1);
}
```

In `C.foo`, parameter `p` is covariant-by-declaration because the corresponding parameter is covariant-by-declaration in the member signature for `foo` in `B`, because the same property holds for `foo` in `S1`. So the check on `p` in `C.foo` for correctly typed covariant-by-declaration parameters amounts to checking `num` against `int`, `Object`, and `dynamic`: There is a subtype relationship (in one or the other direction) in all three cases, so the type annotation on `C.foo.p` is OK (that is, there is no error).

However, `dartanalyzer` from commit 2ea8ff5ae7a3602f0e931aaafadb978cd92993bb (of today) reports the following errors:

``` ERROR|COMPILE_TIME_ERROR|INVALID_OVERRIDE|/usr/local/google/home/eernst/lang/dart/scratch/201912/n009.dart|7|8|3|'C.foo' ('void Function(num)') isn't a valid override of 'S2.foo' ('void Function(Object)').
ERROR|COMPILE_TIME_ERROR|INVALID_OVERRIDE|/usr/local/google/home/eernst/lang/dart/scratch/201912/n009.dart|7|8|3|'C.foo' ('void Function(num)') isn't a valid override of 'S1.foo' ('void Function(dynamic)').
```

(Weird: There are two lines reporting one error each, but the github rendering algorithm for 'preview' and the actual github issue page only shows one of them. The invisible one is about `Object`.)

This means that the status of `p` of being covariant-by-declaration is somehow not noted when these checks are performed.

**Comment by scheglov** [comment]
It seems that the issue is related to the way we record `isCovariant` in analyzer, and the way we build interfaces.

When we build a class interface, for each member name we take the most specific signature. For `B` this is `S2.foo(Object)`. Note, that `covariant` was in `S1`, but because we exactly *take* the most specific signature, we don't use `S1.foo(covariant dynamic)` in any way.

And the fact that `p` in `C.foo` is not covariant is just because it is not covariant in `B`.

If `B` declared `foo` itself, we would see that `B.foo` overrides `S1.foo` and `S2.foo`, and record that `p` in `B.foo` is covariant.

It seems that we have to track `isCovariant` separately from most specific signatures, so that even if there is no override (so no parameter to pin this data to), we still carry this data.

**Comment by eernstg** [comment]
Yes. The language specification introduced (in commit 614ae7f362ac2df8500c050862e76c4fc66b8822) the notion of an interface as a set of member signatures (that is: a member signature is a new thing, not the same as a function type), specifically because I needed to define the concept of 'covariant-by-declaration' precisely.

A member signature explicitly carries the `covariant` flag on each parameter which is covariant-by-declaration, which means that the member signature is effectively "caching" the results of a search through the entire superinterface graph for a `covariant` modifier for the given parameter. If the analyzer maintains a representation of a class interface then this information could be cached there, in a similar fashion.

**Comment by srawlins** [comment]
Analyzer no longer reports any issues with this example.
