### ISSUE TITLE
Decide whether promoted type should be used as context of assignment

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39641]
Consider the following code:
```dart
f(Object x) {
  if (x is int) {
    x = g('oops'); // (1)
    print(x);
  }
}
T g<T>(T value) => value;
main() {
  f(1);
}
```
When run with the `non-nullable` experiment enabled, the analyzer rejects this code with the following error at (1):
```
error • The argument type 'String' can't be assigned to the parameter type 'int'. • .../test.dart:3:11 • argument_type_not_assignable
```
With the `non-nullable` experiment disabled, the analyzer accepts the code without complaint.

What's happening is that when there is an assignment to a local variable, the analyzer is using the promoted type of the local variable as the context for doing type inference on the RHS.  Since `x` is promoted to `int`, that means that `g('oops')` gets inferred as `g<int>('oops')`, which is an error because `g<int>` requires its argument to be an `int`.

What I believe should happen instead is that when there is an assignment to a local variable, the analyzer should use the declared type of the local variable as the context for doing type inference on the RHS.

(Note that the reason the code is accepted with `non-nullable` disabled is because with NNBD disabled, we don't have enhanced type promotion, and without enhanced type promotion, the presence of the assignment inside the `if` block prevents the promotion from happening at all).

**Comment by leafpetersen** [comment]
I don't think I agree that this is the right behavior.  I would expect the promoted type to be used for downwards inference.  Note that in the existing pre-nnbd code, a similar example does show up:

```dart
void test(void Function(int) f) {
  T g<T>() {
    print(T);
    return null;
  }
  if (f is void Function(num)) {
    f(g());
  }
}

void main() {
  test((num x) => null);
}
```

This code prints "num", indicating that downwards inference for `g()` is done using the promoted type of `f`, not the declared type.

cc @munificent @lrhn @eernstg for their thoughts.

**Comment by leafpetersen** [comment]
I have some notes in my draft flow analysis spec on related questions as follow:


> - The interaction between assignment based **promotion** and downwards inference is
   probably managable.  I think doing downwards inference using the current
   type, and then promoting the variable afterwards is fine for all reasonable
   cases.
 > - The interaction between assignment based **demotion** and downwards inference is
   a bit trickier.  In so far as it is manageable, I think it would need to be
   done as follows, given `x = E` where `x` has current type `S`.
     - Infer `E` in context `S`
     - if the inferred type of `E` is `T` and `S <: T` and the demotion policy
     applies, then instead of treating this as `x = (E as S)` (or an error),
     then instead treat `x` as promoted to `S` in the scope of the assigment.

**Comment by stereotype441** [comment]
@leafpetersen I think the question you've answered may be different from the one I was trying to ask.

You're saying that when `f` is promoted, and then subsequently called, the promoted type of `f` should be used to infer the type of its arguments.  I completely agree.

What I'm asking is, when `x` is promoted, and an assignment is made whose LHS is `x`, should the promoted type of `x` be used as the context for inferring the RHS of the assignment?

**Comment by stereotype441** [comment]
@leafpetersen Sorry, I did not read your answer carefully enough.  Ok, let me think about this some more.

**Comment by munificent** [comment]
I don't have much intuition one way or the other. It is a strange corner that may be confusing to users whichever way we pick. I lean somewhat towards preferring the promoted type. If we don't do that, then the assignment also needs to demote the variable, otherwise it may be assigned a value of the wrong type, as in the example here. And I think users generally dislike demotion and want it to be obvious when it occurs, which suggests it's better to use the promoted type.

**Comment by MichaelRFairhurst** [comment]
There's an interesting sort of contradiction here if we aren't careful (or perhaps that we just must accept).

If we define `a ??= b` as equivalent to `a == null ? a = b : a` then note:

```
int? x;
int? y;
print(x ??= y); // should be OK
print(x == null
  ? x = y // error, cannot assign int? to int
  : x); // but should be OK?
```

**Comment by eernstg** [comment]
I think it could make sense to consider demotion as a secondary behavior: Preserving the current promotion result for a variable is the desired and default behavior.

This could motivate a decision to use the current promoted type for a variable like `x` as the context type for any assignments to `x`, because it will preserve that type for `x` as far as possible. For instance:

```dart
f(Object x) {
  if (x is double) {
    x = g(3); // `3` is 'integer literal with static type double', evaluating to 3.0.
    print(x);
  }
}
T g<T>(T value) => value;
main() {
  f(1.0);
}
```

Could we use the following approach?:

- Assume we have `Td x` or `Td x = e0`, and that the type of `x` has been promoted to `Tp`.
- For the assignment `x = e1`, perform inference on `e1` with `Tp` as the context type; let `Sp` be the static type of `e1` after inference; if `Sp` is assignable to `Tp` then we're done.
- Otherwise, when `Sp` is not assignable to `Tp`, redo inference on `e1` with context type `Td`, let `Sd` be the resulting static type of `e1` after inference. Then for each type of interest `T1..Tk` in an order that visits subtypes before supertypes (so `Tk == Td`), and if `Sd` is assignable to `Tj` then `x` is demoted to have type `Tj`, for the smallest possible `j`. If assignability fails for all `Tj` then an error occurs.

This would not be optimized quite as much as we could (because we could infer `e1` with each type of interest as the context type, not just `Td`). But the simpler rule may be easier to explain: "If the current promoted type can't be used during inference, we use the declared type. Period.".

**Comment by leafpetersen** [comment]
> There's an interesting sort of contradiction here if we aren't careful (or perhaps that we just must accept).
> 
> If we define `a ??= b` as equivalent to `a == null ? a = b : a` then note:
> 
> ```dart
> int? x;
> int? y;
> print(x ??= y); // should be OK
> print(x == null
>   ? x = y // error, cannot assign int? to int
>   : x); // but should be OK?
> ```

I don't think there is a contradiction here.  `x == null` promotes `x` to `Null` in the `?` branch.  Assignment of `y` to `x` demotes `x` back to `int?` since `int?` is a type of interest.

The following comment from my draft spec is relevant:

```
 - The interaction between assignment based **demotion** and downwards inference is
   a bit trickier.  In so far as it is manageable, I think it would need to be
   done as follows, given `x = E` where `x` has current type `S`.
     - Infer `E` in context `S`
     - if the inferred type of `E` is `T` and `S <: T` and the demotion policy
     applies, then instead of treating this as `x = (E as S)` (or an error),
     then instead treat `x` as promoted to `S` in the scope of the assigment.
```

**Comment by eernstg** [comment]
@leafpetersen, I think my proposal [here](https://github.com/dart-lang/sdk/issues/39641#issuecomment-566499851) is quite similar to your draft spec text.

However, the part 'treat `x` as promoted to `S`' is different and surprising (I would expect 'promoted to `T`'). In fact, if `S` is a proper subtype of `T` (that is, we have `S <: T` and not `S == T`) then for soundness the assignment `x = E` would include a dynamic type check (so it would actually mean `x = (E as S)`).

Another difference is that I proposed that we should promote `x` to one of the existing types of interest, rather than the type of the assigned expression `E`. So the demoting assignment would not introduce a new type of interest, but all existing types of interest would be available for the demotion, with the declared type of `x` as the last choice.

The rationale is that types of interest are significant for developers who need to understand why a particular variable has a particular type (in practice the situation could be: "It's easy to see that `x` as type `U`, so why can't I call `x.foo()'?!").

Hence, I think it is useful from a code readability and comprehensibility point of view that _types of interest can be located_ in the source code: An expression of the form `x is U` will do that, but with `x = E` it is not always evident what the type of `E` is, and the type of `E` might change because of some subtle changes to the code (update the version of some library where some method returns a slightly different type; change the type of some other variable, promoted or not, such that type inference runs differently on `E`; etc.etc.)

**Comment by lrhn** [comment]
This is an interesting case because using the promoted type as context, but the un-promoted type for checking whether the assignment is allowed, would give us one (more) place where it's not an error if the expression type is not a subtype of the context type. 
In this place, the context type is a *hint* which is stronger than the actual *requirement*.

I does seem to be the best solution: Use the most specific type as the context hint, then see what comes out. If that code used the hint, then we don't need to demote. If not, we still allow the assignment if it can be stored in the variable, but have to demote the variable type afterwards.

**Comment by scheglov** [comment]
@leafpetersen @eernstg Is it decided what to do here? The flow analysis spec still has this under the "Questions:" section. I'm not sure what this issue is about, and what should be done.

I'm also puzzled with the wording in `The interaction between assignment based demotion and downwards inference`: "if the inferred type of `E` is `T` and `S <: T` and the demotion policy applies, then instead of treating this as `x = (E as S)` (or an error), then instead treat `x` as promoted to `S` in the scope of the assigment." Do you mean "as promoted to `T`"?

**Comment by stereotype441** [comment]
I've uploaded https://dart-review.googlesource.com/c/sdk/+/144883 for review with my understanding of the behavior I believe @lrhn is suggesting in https://github.com/dart-lang/sdk/issues/39641#issuecomment-573669413.  Note that the analyzer currently implements this behavior; the front end does not.

**Comment by leafpetersen** [comment]
> I'm also puzzled with the wording in `The interaction between assignment based demotion and downwards inference`: "if the inferred type of `E` is `T` and `S <: T` and the demotion policy applies, then instead of treating this as `x = (E as S)` (or an error), then instead treat `x` as promoted to `S` in the scope of the assigment." Do you mean "as promoted to `T`"?

@scheglov I believe that what I wrote should have been "demoted to T".  What I am proposing is to treat inference of `x = E` when `x` has static type `S` in the following way:
  - Perform downwards inference on `E`, using `S` as the context type, and typing all references to `x` within `E` as having type `S.
  - Let `T` be the resulting inferred type of `E` 
  - If `T` is assignable to `S` we are done.
  - Otherwise, treat this as an assignment of something of type `T` to a variable of type `S`, that is:
    - If the demotion policy applies, treat the assignment as a demoting assignment which demotes `x` to `T`
    - Otherwise, it is an error.

Does this make sense? 

cc @johnniwinther

**Comment by johnniwinther** [comment]
I believe this is the same as the second option of https://github.com/dart-lang/language/issues/867 - which I think is what we should do.

**Comment by scheglov** [comment]
@leafpetersen Looks good to me.

**Comment by lrhn** [comment]
Having seen the consequences, I think the rule is reasonable in general, but when I see it affecting implicit coercions, I worry that it might be taking things too far.

Example:
```dart
num x = ...;
if (x is double) x = 0;
// User assumes x is int, but context type for `0` is `double`, so it becomes 0.0
```
or 
```dart
Object o = ...;
if (o is Function) o = CallableObjectWrapper(o);  // make o not function
/// except the callable object wrapper has its `call` torn off because its context type is `Function`.
```
Both of those examples are somewhat spurious. They don't get promotion in any place where
it's actually useful, and needing to wrap a `Function` in a non-`Function` object isn't actually useful
(Functions are objects to begin with).


We have so far used the context type to do implicit coercions in places where we *need* to do them in order for the program to not have a compile-time error (using an `int` literal in a position where a `double` is *needed*, or a callable object where a function is *needed*).

In this situation, the context type is a *hint*, not a *requirement*. If possible, I think I'd prefer that we don't do coercions in that case unless necessary. Which is probably very tricky in practice.

So, we have context types which are requirements, and context types which are hints.
The former always causes a compile-time error if the expression's static type is not assignable to the context type.
The latter do not. If we distinguish the two context types formally, and say that the latter does not cause coercions ... then it's probably not enough. We do need coercions when the unpromoted type also needs the coercion.

So, maybe the context type should be a pair of min/max types - the hint and the actual requirement, where the requirement causes coercion, but the potentially more precise hint does not.

In this case, we'd have the context types "dynamic :> double". The integer literal checks the required type (dynamic) and does not coerce itself. A strict `double >: double` context type would cause coercions.

Maybe I'm over-complicating this, and it's not like we have time for a complete rewrite of inference, but introducing coercions is not something we can easily undo. Code will be written depending on that behavior, so we can't easily stop doing it again later.

Thoughts? Am I worrying too much?

**Comment by stereotype441** [comment]
In the analyzer team's meeting with @leafpetersen yesterday, we agreed that we would land https://dart-review.googlesource.com/c/sdk/+/144883 for now and consider the behavior we've been discussing to be the plan of record.  If the language team reaches a decision that we want some other behavior, we can always change things.  Until then, I'm re-titling this bug and classifying it as area-language.

**Comment by leafpetersen** [comment]
We discussed this in the language meeting today.  The consensus was that while the interaction between downwards inference, promotion/demotion, and implicit coercions is unsettling, on balance we think that the implicit coercion case is rare, and that the behavior I propose above (and what is in the test from @stereotype441) is what we want.
