### ISSUE TITLE
RawSynchronousSocket have secure version?

### ISSUE THREAD

**Issue by zfuke164345** [dart-lang/sdk#39703]
i will use RawSynchronousSocket  read sync,but i donot konw how to deal with ssl version,some one help me?

**Comment by sortie** [comment]
Hi @zfuke164345.

No, there is no TLS (Secure) version of RawSynchronousSocket. We don't have any plans to make one because the SecureSocket/RawSecureSocket versions are better.

RawSynchronousSocket should only really be used for rare cases. Normal code should be using the asynchronous Socket or RawSocket. These interfaces are asynchronous and requires you to write your code in asynchronous style, which is good and normal. You'll need to learn that.

SecureSocket and RawSecureSocket are built on top of Socket and RawSocket. You can read about them in the documentation at e.g. <https://api.dartlang.org/stable/dart-io/SecureSocket-class.html>. However that's not the best beginner documentation.

This is the Dart bug tracker. It's about bugs in Dart and is not the best place to ask questions. The new issue template says:

```
If you simply have a question, consider starting with Stack Overflow:

https://stackoverflow.com/questions/tagged/dart

For a real-time response, consider our Gitter channel:

https://gitter.im/dart-lang/sdk
```

Maybe those resources can help you? Searching stack overflow or using your preferred search engine can be useful. I would give you some sample code but I'm not sure it would help you because I don't know what you want to do with the secure socket.

If your goal is HTTPS, then you should use <https://api.dartlang.org/stable/dart-io/HttpClient-class.html>.

I hope that helps even though I couldn't give you exactly what you wanted.
