### ISSUE TITLE
NNBD type promotion issue

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#39735]
Code snippet:

```dart
int flow(Object value) {
  if (value is String) {
    value = int.parse(value);
  } else {
    throw 'foo';
  }
  return value;
}
```

I'd expect value to be promoted to int, but in this case on `2.7.0-edge.134e0e28cda1f8110a69bad34ae70e8123475a80`, value is not promoted to int. However, if I remove the `value = int.parse(value);` bit, value is correctly promoted to String (like I would expect) in the return position. This is a reduced version of the other snippet I tried:

```dart
int ensureInt(Object value) {
  if (value is int) {
    value = value;
  } else if (value is num) {
    value = value.toInt();
  } else if (value is String) {
    value = int.parse(value);
  } else {
    throw ArgumentError('value is not convertable into an int');
  }

  return value;
}
```

Where I would also expect value to be promoted to int, since all possible code paths either promote directly to int or assign to int using another promoted value.

**Comment by eernstg** [comment]
There are two likely reasons for the lack of promotion: (1) If you are not passing `--enable-experiment=non-nullable` to the tools then you won't get the enhanced kind of promotion where promotion is possible at all with a local variable which is not effectively final; and (2) even with `--enable-experiment=non-nullable` you can't promote `value` to `int` in the given position, because it has already been promoted to `String`, and promotions along a control flow path should be monotone (`T1`, then `T2`, then `T3` ..., such that `Tk <: Tk-1 <: ... <: T3 <: T2 <: T1`).

**Comment by vsmenon** [comment]
This appears to be working as intended (i.e., as spec'ed) in 2.7.0.

As @eernstg noted, there is work in progress to improve type promotion in the language.  I believe this is the latest:

https://github.com/dart-lang/language/blob/master/working/enhanced-type-promotion/feature-specification.md

You're welcome to file additional requests at https://github.com/dart-lang/language
