### ISSUE TITLE
No completion for "call" method on Function objects

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#39761]
At the current version of dart sdk (2.7.0) we don't have a completion for the "call" method for function types. This is leading to third party sollutions to fix this problem, as of: https://github.com/leisim/dartx/issues/16#issuecomment-565044402

![image](https://user-images.githubusercontent.com/1146982/70724329-2f950e00-1cd9-11ea-89f6-4ff8a00a650f.png)

**Comment by pq** [comment]
WIP (https://dart-review.googlesource.com/c/sdk/+/132920):

![image](https://user-images.githubusercontent.com/67586/72922138-5d6e6900-3d01-11ea-88cb-c0af9646ecdf.png)

Note that since `call` has no backing element (in the analyzer's element model) it is not rendered w/ the method icon (or return type displayed).  If this is significant, we'll want to accommodate this special case on the client(s) side(s) (e.g., IntelliJ and VS Code).

**Comment by pq** [comment]
Issue tracking IntelliJ cosmetics: https://youtrack.jetbrains.com/issue/WEB-43413.

/fyi @DanTup in case you want to track this for VS Code.

**Comment by DanTup** [comment]
@pq thanks! I'll try it out and see how it looks. If I understand that issue correctly, the reason it doesn't appear the same is that IntelliJ is using its own data structures for this? In VS Code everything comes from the server, so if this shows up like any other method, I'd expect it to just work. I'll give it a test to confirm though!

**Comment by pq** [comment]
Thanks @DanTup.  The issue is that ordinary method suggestions have a method element associated with them and that's how clients know it's a method invocation.  These do not (since `call` isn't part of the actual element model and is a kind of magic method).  To clients these will just look like invocations but the logic they use to decorate them as methods (vs. property accessors for example), won't "just work" and so we'll need to special case them I think.

Feel free to ping me if you hit any snags.

**Comment by bwilkerson** [comment]
Could we do the special casing on the server side (by sending the information we would have sent had there been an element for it)?

**Comment by pq** [comment]
Ah, OK.  @bwilkerson, yes.  I was being thick.  Looking at this again, I think we can.  Will follow-up...

**Comment by pq** [comment]
@DanTup: please ignore, I've got a fix in flight on the server side.  Everything should now "just work". Sorry for the noise!

**Comment by DanTup** [comment]
@pq np, and thanks! Is it https://dart-review.googlesource.com/c/sdk/+/133001? If so, is there anything special I need to do to see this? Using the most recent nightly (`2.8.0-edge.a4aaaf05eb34bc07686f7480a0da7f056f284b91 (Fri Jan 24 11:40:59 2020 +0000)`) I don't see the `call()` completion:

<img width="414" alt="Screenshot 2020-01-24 at 12 21 11" src="https://user-images.githubusercontent.com/1078012/73068794-06ed6000-3ea4-11ea-9857-be8ca50060b3.png">

**Comment by DanTup** [comment]
Oops, user error. I was using the a sample project that was pointing at running the analyzer from source (and my local folder wasn't up-to-date) 🙈

Looks as expected :-)

<img width="291" alt="Screenshot 2020-01-24 at 12 22 23" src="https://user-images.githubusercontent.com/1078012/73068893-3ef4a300-3ea4-11ea-93aa-c1a660fc8bde.png">

**Comment by pq** [comment]
Sweet!
