### ISSUE TITLE
Unhandled expression evaluation edge cases.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#39772]
Here's a grab bag of expression evaluation cases that fail today. Trying to evaluate these expressions typically causes a Flutter application to crash usually due to bugs saying a certain kernel id is not supported yet.

Calling some named factory constructors from dart:core
```dart
Set.identity()
```
This hard crashes your dart app.

Using list comprehensions.
```dart
[3, ..[4,5]]
```

Anything with const including using it as a default value for a named parameter.

```dart
(([foo = 3]) { print(foo); })()
```

**Comment by jacob314** [comment]
Fyi @rmacnak-google, @johnniwinther, @vsmenon

**Comment by annagrin** [comment]
Update looks like frontend no longer crashes on those, but we still  cannot evaluate the first two expressions due to Javascript generated by expression compiler being incomplete. Moving this bug to dev_compiler_eval and taking over it.
 
- Set.identity() compiled but fails to evaluate currently in chrome.
- [3, ..[4,5]] compiled but fails to evaluate currently in chrome.
- (([foo = 3]) { print(foo); })() compiles and evaluates correctly.

**Comment by annagrin** [comment]
All works after incremental DDC mode support:
https://github.com/dart-lang/sdk/issues/45303
