### ISSUE TITLE
Test coverage regression on mixins

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#39779]
Using Flutter's Dart SDK on flutter `stable` and `master` channels, there's a regression in test coverage reporting.

Consider this file in the `lib` folder:

```dart
// lib/main.dart

mixin A {
  void foo() {
    print('foo');
  }
}
```

Then tested using:

```dart
// test/my_test.dart
import 'package:flutter_test/flutter_test.dart';

import 'package:test_flutter/main.dart';

void main() {
  test('a', () {
    TestA().foo();
  });
}

class TestA with A {}
```

By running the command `flutter test --coverage`

This will report the method `foo` of `A` as being untested, when it is (the test correctly prints `foo`).

**Comment by mraleph** [comment]
@jensjoha could you take a look at this?

**Comment by vsmenon** [comment]
Do we know if this is a front end issue, a coverage tools issue, or something else?

**Comment by jensjoha** [comment]
Sort of a mix.
Considering what's happening (see below) I don't really see how this is a "regression" per say, either --- it has probably "always" been broken.

What's happening is this:
* When asking the VM for coverage you can do it in one of two ways
  * Ask the VM for coverage for everything; or
  * Ask the VM for coverage for a specific script
* Asking the VM for coverage for everything works perfectly fine. The VM goes through everything and reports coverage correctly (at least in this case).
* Asking the VM for coverage for a specific script (which is, at least now, what the flutter tools does) doesn't work in this case: The VM goes through the libraries, asking for the list of scripts they "know about", and checks for matches against what you asked for. In this case, when asking for 'master.dart', the library for 'lib.dart' says no when it shouldn't --- because of the way the mixin transformation works the content is actually in lib.dart.

I'm fixing it (or at least trying to) by basically updating 1555594 where I (for some reason that I don't recall) didn't include urls only from mixins in a libraries 'sourceReferences' index.
