### ISSUE TITLE
Lambda parameter type inferred as Object when should be Null

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39791]
If I analyze this with `--enable-experiment=non-nullable`:

```dart
void then(void Function(Null) callback) {}

main() {
  then((_) {});
}
```

Then I get:

```
error • The argument type 'Null Function(Object)' can't be assigned to the parameter type 'void Function(Null)'. • temp.dart:4:8 • argument_type_not_assignable
```

I would expect the closure's parameter type to be inferred as `Null`. This isn't an entirely contrived use case. As the name of the function above implies, if you call `.then()` on a `Future<Null>`, you will run into this.

**Comment by scheglov** [comment]
Using `Object` instead of `Null` was done intentionally, as requested in https://github.com/dart-lang/sdk/issues/31546. Do we change this decision now? For NNBD only, or for legacy as well? @eernstg

**Comment by munificent** [comment]
> Using `Object` instead of `Null` was done intentionally, as requested in #31546.

Ah, nice find.

> Do we change this decision now?

I think we should yes. If you look at the original rationale:

> Pros:
> 
> 1. The resulting inferred closure is strictly substitutable for the version inferred with `Null`
> 2. This makes using `Null ->  T` as the type of "any unary function returning T" much more usable, since the inferred function will no longer fail if dynamically applied to a non-null value.
> 3. No additional (and no fewer) method send errors and warnings will be emitted (`Null` and `Object` have the same method set.
> 
> Cons:
> 
> 4. With --no-implicit-casts, additional cast errors may show up
> 5. Less static and runtime checking if you actually intend the type to be Null
> 6. Implementation cost

1 is no longer true since Object is not nullable, this `Function(Object)` is not substitutable for `Function(Null)`.

For 2, we have Never now.

And 4 becomes the default so this con is much larger.

> For NNBD only, or for legacy as well?

I think we'd want to do it for NNBD only to not break existing code. @leafpetersen @lrhn

**Comment by leafpetersen** [comment]
At a minimum, this would need to be changed to use `Object?` instead of `Object`.  Arguably we should also change the conditions in which it kicks in either to when the argument type is `Never`, or when the argument type is `Never` or `Null`.  

It's definitely a bit ad hoc, so it's appealing to get rid of it.  It's possible that doing so would incur additional breakage though.

**Comment by eernstg** [comment]
I vaguely remember that the original reason for introducing this special rule was a situation where the inferred `Null` parameter type would create problems elsewhere, probably in an expression involving `Future.then(...)`, but I can't find the relevant issue right now. We certainly [agreed](https://github.com/dart-lang/sdk/issues/31546#issuecomment-349453547) that the special rule makes general function types (like the ones that have one or more near-bottom parameter types) more useful.

I think it's a useful approach to migrate this rule directly: Infer `Object?` as the parameter type and let the rule kick in when the argument type is `Never` or `Null`. The error described [initially](https://github.com/dart-lang/sdk/issues/39791#issue-537849434) then goes away, because `Null Function(Object?)` _can_ be assigned to `void Function(Null)`, and this resolves the problem at hand.

In contrast, if we eliminate this special rule (and infer the parameter type `Null` in the example, and `Never` with NNBD in a similar example) we might cause breakage in existing code. We should at least investigate the amount of breakage if we prefer to do that.

**Comment by munificent** [comment]
> In contrast, if we eliminate this special rule (and infer the parameter type `Null` in the example, and `Never` with NNBD in a similar example) we might cause breakage in existing code. We should at least investigate the amount of breakage if we prefer to do that.

Is that true if we only eliminate the rule in NNBD-opted-in code?

**Comment by eernstg** [comment]
If we only consider actual arguments which are function literals then the context type could be much less general, e.g., we could use `void Function(Object?)` in the first place, and there would be no need for a special rule in inference.

So the point is that the general function type allows us to use a pre-existing function whose parameter type is more special:

```dart
Map<Type, Object Function(Null)> builders = {};
T build<T>(arg) => (builders[T] as dynamic)(arg) as T;

class MyClass { MyClass(int _); }
MyClass myClassFactory(int arg) => new MyClass(arg);

void main() {
  // Setup.
  builders[MyClass] = myClassFactory;  // <--- Here.
  // Use.
  var myClass = build<MyClass>(3);
}
```

Now we could simply say that this is an inherently dynamic design, so we don't expect the type system to be particularly helpful anyway.

However, even though Dart cannot express the typing discipline here, it is similar to a dependent type (where `builders` maps a `Type` reifying the type `T` to a function of type `T Function(S)`, where we might be able to specify `S` in terms of some statically known type level mapping). So it is definitely possible for a careful team to maintain code where the necessary invariants are maintained manually

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/136461

**Comment by scheglov** [comment]
![image](https://user-images.githubusercontent.com/384794/74878867-e2f33200-531c-11ea-9a11-7fe4cd81142d.png)
