### ISSUE TITLE
Wrapped function causes runtime error.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#39818]
[dartpad](https://dartpad.dartlang.org/dd6dfce11cd8731157e04e0d8dd3fd69)

I'm not sure how to describe this issue.

```dart
abstract class Interface {}

class Model implements Interface {}

class Lens<A> {
  final A Function(A) get;
  const Lens(this.get);
}

void main() {
  Lens<Interface> a = Lens<Model>((a) => a);  
  print(a.get); /// Script error / type '(Model) => Model' is not a subtype of type '(Interface) => Interface'
}
```

I'm trying to chain lenses (functional references) and this problem comes up when I'm dealing with inheritance hierarchies.
Implicit-casts are set to false so I'm expecting some kind of safety there, but I'm not sure if this scenario is just something that I have to somehow be careful about?
I'd at least expect that that program would not compile, but instead, it crashes on the print call.

Is there a way to deal with this?

**Comment by eernstg** [comment]
The problem is that you are specifying that you want a `Lens<Model>`. The current Dart rules for variance only have one form: Covariance for every type parameter of a generic class, with dynamic checks at all occasions where there is no static guarantee that the requirement is satisfied.

We have [plans](https://github.com/dart-lang/language/issues/524) to add support for statically safe variance (covariance, contravariance, invariance) to Dart, so you will (if we proceed to do this, which is quite likely) be able to specify the variance on each type parameter, and then there will be static checks that the rules necessary for soundness are respected.

In particular, if you were to declare as covariant with `class Lens<out A> { ... }` then you would not be able to have the instance variable named `get`, because it has a non-covariant occurrence of the type variable `A`. So you would have to use the more strict _invariant_ mode, using `class Lens<inout A> {...}`, and this would imply that there is no subtype relationship between `Lens<Model>` and `Lens<Interface>`.

So you would still not be able to have `Lens<Interface> a = Lens<Model>(...);`, but now it would be a compile-time error rather than a run-time error.

So what you can do now is to treat `Lens` as if its type parameter were invariant; you won't get the static checks to _enforce_ that, yet, but you can do it manually.

**Comment by modulovalue** [comment]
Thank you very much for the workaround and the clear explanation.
