### ISSUE TITLE
Re-enable analyzer language_2 tests in the NNBD configuration once language versioning is implemented

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#39847]
See discussion at https://dart-review.googlesource.com/c/sdk/+/128804.

**Comment by scheglov** [comment]
I removed the whole `if` statement in the referenced CL, and [ran presubmit](https://dart-review.googlesource.com/c/sdk/+/132801) on try bots. It is green. I did nothing in analyzer, I don't see any `.dart_tool/package_config.json` files in `tests/` the repository, so there is no opt-out using language version if you enabled an experiment.

I don't fully understand the description of the hack though. "it implicitly opts the code into NNBD as well" Hm... Yes, and how otherwise could you enable `non-nullable` feature, any experimental feature?

**Comment by stereotype441** [comment]
As of this morning, we are testing all the `_2` tests with the NNBD SDK, so this issue is resolved.
