### ISSUE TITLE
compiler allows void values in lists

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#39846]
I think the following behavior is inconsistent.
```
  var foo=print(0); // void
  print([foo]); // prints [null]
  print({foo: 1}); // analyzer fails to detect the error, but dart2js complains about void  
```

I think it should be an error in both cases, which is supposed to be detected by the analyzer.

**Comment by lrhn** [comment]
The static type of `foo` ends up being `List<void>`. 

The specification has some specific restrictions on where a `void` typed expression may occur, it's disallowed in all but a specific list of syntactic constructs, and an element position of a list/set literal or key/value position of a map literal is not explicitly allowed, so it should be a compile-time error.

The analyzer fails to `void` expressions in list/set literals and map literals.
The common front-end only fails to detect them in list/set literals.

**Comment by eernstg** [comment]
This is actually working as intended, except the `dart2js` error: When the type of `foo` is `void`, `[foo]` can get the type `List<void>` based on bottom up inference (when there is no constraint to the contrary in the context type), and `print` is happy about printing a `List<void>`, as it should be. Similarly, `{foo: 1}` gets the inferred type `Map<void, int>` and `print` should print it.

However, the following is an error, because the `void` typed expression `foo` doesn't:

```dart
void main() {
  var foo = print('');
  Map<Object, int> map = {foo: 1};
}
```

**Comment by srawlins** [comment]
Moving to area-web as per @eernstg 's comment.

**Comment by sigmundch** [comment]
If this is a type inference bug, then we are likely looking at a corner case in the CFE.

Note that the VM behaves the same same way as dart2js on the example above.

**Comment by tatumizer** [comment]
Closing for the lack of interest.

**Comment by eernstg** [comment]
Closing this issue is fine, thanks! I can't see any evidence that any tool behavior is wrong (and the example I mentioned [here](https://github.com/dart-lang/sdk/issues/39846#issuecomment-567148855) _does_ get reported as an error), so there is nothing to do.
