### ISSUE TITLE
Migration: should point types to never recursively

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#39852]
Take type parameters:

```dart
f<T extends num/*1*/>(T/*2*/ t) {
  t + 1;
}
```

In this example, we draw `2 -> never`. However, we should also be drawing `1 -> never` and don't.

We may need to do similar things for future or?

**Comment by MichaelRFairhurst** [comment]
Added type bug.

If it were a matter of drawing a hard or soft edge, it would be a feature.

However, currently, it makes it possible for us to produce the following migration:

```
f<T extends num?>(T t) {
  t + 1; // need a ! on t for this to work!
}
```

**Comment by stereotype441** [comment]
I'm not sure whether you're suggesting we should draw a hard edge or a soft edge.  Let's consider both.  And I'd like to consider a slightly more complex example:
```dart
// Pre-migration
class C<T/*1*/ extends num> {
  f(T/*2*/ t) {
    return t + 1;
  }
  g(T t) {
    return t == null ? 0 : t + 1;
  }
}
main() {
  print(new C<int>().g(null));
}
```
IMHO there are two defensible migrations of this code:
```dart 
// Post-migration
class C<T extends num?> {
  f(T t) {
    return t! + 1;
  }
  g(T t) {
    return t == null ? 0 : t + 1;
  }
}
main() {
  print(new C<int?>().g(null));
}
```
And
```dart
// Post-migration
class C<T extends num> {
  f(T t) {
    return t + 1;
  }
  g(T? t) {
    return t == null ? 0 : t + 1;
  }
}
main() {
  print(new C<int>().g(null));
}
```
This is the typical situation with substitution nodes where we have to make a choice between making the "inner" or the "outer" type nullable; the first migration corresponds to making the inner type nullable; the second corresponds to making the outer type nullable.

Personally I think we should favor making the inner type nullable, and those are the heuristics that are currently programmed into the migration engine.  My rationale is that if you make the inner type nullable, you are adding nullability at the call site (the `?` in `new C<int?>().g(null)`)), and therefore the only the uses of class `C` that are connected to this call site lose out on null safety.  Other, unrelated uses of  class `C` retain null safety.  Whereas if you make the outer type nullable, you are adding nullability to the class `C` itself, in which case all uses of the class `C` lose null safety just because this one user passed in a null.

If we create an extra edge `1 -> never` and it's a hard edge, then that's going to prohibit the first migration, which I'm arguing is the preferable one.

If we create an extra edge `1 -> never` and it's a soft edge, then that's not going to have any effect on graph solving (since soft edges only propagate nullability forwards, and you can't make `never` nullable).  It will, however, have the effect of creating an unsatisfied edge that's associated with the use of `t` in `f`, and that's important, because unsatisfied edges are currently the way we decide when to insert `!`s.  Which I think is what you're getting at in your [comment](https://github.com/dart-lang/sdk/issues/39852#issuecomment-567205199).

But once we switch over to using the FixBuilder, that's not going to be necessary either.  Because the way FixBuilder decides where to add a `!` is to just do normal resolution using the post-migration types, and figure out where a potentially nullable value is used in a way that requires a null check.  Which means that it will figure out that `t + 1` needs a `!` even if there is no edge.

So I think we can actually just leave the graph as is and the FixBuilder will do the right thing.  But I'm glad you brought it up--I will make sure to capture this example in a test case to make sure we get it right.

**Comment by MichaelRFairhurst** [comment]
I think this is a third defensible migration:

```
// Post-migration
class C<T extends num> {
  f(T t) {
    return t + 1;
  }
  g(T t) {
    return t == null ? 0 : t + 1;
  }
}
main() {
  print(new C<int>().g(null!));
}
```

This is defensible if, for instance, `main` is in a test. Or if `f(T t)` is actually a constructor `C(T t) { print(t + 1); }`.

The inner/outer distinction here is not the problem though.

In the case that `g()` draws a hard edge to never:

```
  g(T t) {
   print(t + 1);
  }
```

In this case, the algorithm cannot mark the inner node nullable, and so it chooses to mark the outer node nullable.

Is that always the best behavior? I show here that the answer to that is no:

```
f<T extends num?>(T t) {
  t! + 1;
}
```

I don't think this is a good migration in this case, however, I wouldn't call it a _bug_ to produce it. I consider this a _feature_ to _not_ produce it.

> I'm not sure whether you're suggesting we should draw a hard edge or a soft edge

Both, like any other method call. However, clearly we would only draw hard edges when we're referring to a postdominated type parameter -- like a type parameter of a function declaration, or a type parameter in a constructor (assuming only one constructor parameter).

This is a good point to note, and makes this feature lower priority.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
