### ISSUE TITLE
NNBD: are 'dynamic?' and 'Null?' valid types?

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#39896]
current NNBD treats  'dynamic? x;' and 'Null? x;' as valid declarations. 
In contrast, 'void? x;' gets flagged. Was it intended?

**Comment by eernstg** [comment]
`dynamic?` and `Null?` are syntactically valid nnbd types (though hardly useful ones), and `void?` is a syntax error. So the behavior is as specified. You could say that this is inconsistent, and also that it is a consequence of the historic background (`void` used to be a syntactic exception, because it was an exception in so many other ways, but today `void` is much more like other types).

So we could improve on the consistency of the treatment of special types like `void` and `dynamic`, but it has only very little practical value to add support for `void?`.

**Comment by tatumizer** [comment]
I think `void?` is treated correctly. It's `dynamic?` that might be problematic. Some users might assume that there's a difference between `dynamic` and `dynamic?`. Especially if someone is coming from Kotlin where `Any` and `Any?` are different (in dart's terms, the former is `Object`, and the latter is `Object?`). Such user might assume that `dynamic` is similar to `Any`. I think `dynamic?` is asking for a warning (we have a number of warnings about redundancy, e.g. on `int? x = null`; this one might be similar). Sure, it's a kind of nitpick, nothing dramatic.

**Comment by lrhn** [comment]
We could disallow writing `dynamic?` (and `Null?`, and maybe `Never?`) without affecting expressibility. At least as long as it does not affect type *identity*.
If `dynamic` and `dynamic?` are identical as types, and similar for `Null` and `Null?` or `Null` and `Never?`, then removing the ability to write the overlong representation is not needed.

I'd be fine with disallowing it. We have to state it specially in the syntax rules, but I think it is probably worth it.

**Comment by eernstg** [comment]
I was basically noting that Dart isn't quite consistent in this area, but that it is not likely to be helpful for anyone if we add support for `void?`. So if we want to improve on the consistency we should instead outlaw `dynamic?` and `Null?` (because they are redundant and thus misleading for anyone who assumes that they are different from `dynamic` and `Null`, respectively).

If we want to do that then I believe that `dynamic?` and `Null?` should not be syntax errors, because the grammar machinery needed in order to encode various constraints like these is typically convoluted and not very readable. The flip side of that coin is that we could then make `void` an ordinary identifier, thus eliminating yet another snippet of special casing (the rule that `void?` is an error would then be added as a separate compile-time error, given that it is no longer a syntax error).

`Never?` is more delicate: The `?` is significant (that is, `Never?` is not the same thing as `Never`), so we can't argue that the question mark is redundant and thus misleading. Also, we have lots of other types that have more than one syntactic form; one example is `FutureOr<Object> == Object`, and there are many others.

We probably don't want to require developers to normalize their types in source code, even though the analyzer/compiler will do that for them, because normalization may take place after a type variable has been bound:

```dart
FutureOr<X> f<X>(X x) => x;

void main() {
  var x = f(Object()); // `x` has type `FutureOr<Object>`, i.e., `Object`.
}
```

This means that types like `FutureOr<Object>` will occur naturally in programs, at least as an intermediate result, so it could be seen as overly rigid to make it an error to write these types explicitly.

We could try out having a `types_must_be_normalized` lint, and see how much breakage it introduces, and how useful everybody thinks it is. ;-)

**Comment by tatumizer** [comment]
"types_must_be_normalized" is too broad for this specific case. I think linter can unconditionally complain about `dynamic?` used as a type literal, no matter what flags. This is a really *special* case.
And everybody is using linter anyway, so it doesn't matter much which tool produces this warning IMO. Maybe indeed, linter is a better choice for that.

**Comment by lrhn** [comment]
I would only disallow *literal* types written as `dynamic?` and `Null?`, not `X?` where `X` happens to be bound to `dynamic` or `Null`. The reasoning is that those types are confusing because the `?` doesn't actually *mean* anything, but it looks like it does.

I'll probably backtrack on `Never?`. I can see a coding style where you never write `Null`, and always use `Never?` instead of `Null`. It would be consistent and reasonable, even if it's not what we currently do.

It is slightly different with `FutureOr<dynamic>`. It may not have any *subtying* difference from `dynamic`, but it carries a strong signal to human readers that this thing is going to be a future that you should await.

We could argue that `dynamic?` suggests that it might contain a `null` value that you should handle, but you have to handle any type it might contain, so I'm not sure that's actually useful.

**Comment by srawlins** [comment]
I think the question has been satisfactorily answered.
