### ISSUE TITLE
dartfix easy issue solving feature addition

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/sdk#39904]
After upgrading Dart version I found in my code with more than ~800 INFOs about:
 + _Prefer single quotes where they won't require escape sequences. (prefer_single_quotes)_ [80%+ of the cases]
 + _Omit type annotations for local variables. (omit_local_variable_types)_ [~15% of the cases]

I guess that having dartfix applying automatically the _convert to single quoted string_ quickfix in those situations would be a 5 minutes-long commit. May someone do that or orient me where to begin to do it by myself and making a PR?

**Comment by bwilkerson** [comment]
The good news is that support for prefer_single_quotes is already implemented in dartfix on master (it was added a few days ago). I expect to have a CL out today to add support for omit_local_variable_types. However, I don't know when the next release of Dart will be built, so I don't know when they will become available from a dev or stable release.

You could use the first today by running dartfix from source. In order to do that, follow the instructions here: https://github.com/dart-lang/sdk/wiki/Building to get the sources downloaded (unfortunately, cloning the GitHub repo isn't sufficient).
