### ISSUE TITLE
Analyzer: Deprecation of TypeDefiningElement.type in 0.39.1

### ISSUE THREAD

**Issue by shyndman** [dart-lang/sdk#39943]
Hi there,

Quick question: What is the recommended replacement to `TypeDefiningElement.type`? The `instantiate` method?

I looked around to see if I could find some reasoning behind the change (CHANGELOG, the Gerrit CL description/discussion), but was unable to. Do you folks publish anything to help downstream users migrate?

**Comment by shyndman** [comment]
Oh, one more quick question: How long do deprecated methods stick around before being removed?

**Comment by bwilkerson** [comment]
> What is the recommended replacement to `TypeDefiningElement.type`?

Sorry, that should have been documented. Yes, the replacement is the `instantiate` method.

> Do you folks publish anything to help downstream users migrate?

We try to remember to add entries to the change log, but this change doesn't appear to have been added there.

The reason for the change was to support NNBD (Non-Nullable By Default) in which every type defining element defines both a nullable and a non-nullable type. In that future world it doesn't make sense to ask for the single type associated with such an element because there's more than one. (Most of the recent changes are in preparation for NNBD.)

> How long do deprecated methods stick around before being removed?

Only until we (a) publish a breaking change version of the package and (b) have time to remove them. In the past it took a long time to for us to remove them, but we're working to remove them much more quickly.

@stereotype441 @scheglov for visibility

**Comment by shyndman** [comment]
👍 Thanks
