### ISSUE TITLE
Avoid double registering more capabilities in LSP server

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#39949]
There was some discussion at https://github.com/microsoft/language-server-protocol/issues/829

The bug was fixed for text document syncing in https://github.com/dart-lang/sdk/commit/34bdcec87733df3fd2412ec0cf8e66098a5c231d, but wasn't fixed for other capabilities such as `hoverProvider` which causes bugs in some clients. See https://github.com/neoclide/coc.nvim/issues/978

**Comment by natebosch** [comment]
Related issue on our tracker: https://github.com/dart-lang/sdk/issues/38490

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
Yeah, this looks like an oversight (I had it in my head we only dynamically registered text sync, but [that's definitely not correct](https://github.com/dart-lang/sdk/blob/05e70d5b38cb1b4e005129a18002fb82ee289524/pkg/analysis_server/lib/src/lsp/handlers/handler_initialized.dart#L69)). VS Code de-dupes when things are registered both statically/dynamically so it's less obvious from the logs (though the spec clarification makes it clear servers shouldn't do this, so we shouldn't rely on clients doing this).

I'll fix it up this week. Thanks!

**Comment by nathanblair** [comment]
Excellent work, y'all. I forgot to mention the server didn't appear to have an issue in VS Code, which, I would presume, uses the same language server client program that is shipped with the dart sdk? So good to know there is a suspicion on how to fix it already!

**Comment by DanTup** [comment]
The Dart VS Code extension uses the same server, but a different interface/protocol (not LSP). This bug is in the LSP part (however, VS Code's LSP client de-dupes registrations, so even when using the LSP server this doesn't cause an issue).

The fix should be fairly simple - just applying the existing fix linked above (34bdcec87733df3fd2412ec0cf8e66098a5c231d) to the other static registrations in the initialize handler.

**Comment by DanTup** [comment]
I've got a change that should resolve this here:

https://dart-review.googlesource.com/c/sdk/+/129711/

There were more things dynamically registered than I remembered (we do this because it's the only way to tell the client to scope things only to specific file extensions). Once it lands in a nightly, please try it out and let me know if anything still isn't working right (and which editor/client you're using).
