### ISSUE TITLE
Compile entire package using DDC

### ISSUE THREAD

**Issue by leisim** [dart-lang/sdk#39990]
Is it somehow possible to compile an entire package?

I'm working on a Flutter web IDE and I can't find a way to compile dependency packages separately. I want to be able to reuse compiled packages.

I tried manually adding all the files of a package but if they contain imports to `dart:mirrors` or a number which can't be represented in js, it fails. Is it possible to ignore such files and throw a runtime error?

In your issue, please include:

`Dart VM version: 2.8.0-dev.0.0.flutter-aa6709974d (Thu Dec 19 02:14:59 2019 +0000) on "windows_x64"`

**Comment by keertip** [comment]
@leisim , you are more likely to get your question answered from the community at  https://flutter.dev/community or in the docs - https://flutter.dev/docs.

**Comment by leisim** [comment]
@keertip

Unfortunately, documentation for dartdevc is virtually non-existent. (At least I couldn't find it)

I doubt that the community can help because it is not something you typically work with.

Because I think DDC currently can't do what I ask for, this is more a feature request than a question.

**Comment by keertip** [comment]
@grouma , @natebosch , any pointers?

**Comment by grouma** [comment]
I'm not sure I follow the question entirely but I think what you are looking for is Dart conditional imports. A package can be designed to support multiple platforms through this feature. A canonical example is `package:http`.  See how the imports are structured here: https://github.com/dart-lang/http/blob/master/lib/src/client.dart#L12

Note there is an `io_client` and a `browser_client`. DDC will use the `browser_client` so you can safely have `dart:io` (or `dart:mirrors`) in `io_client.dart`.

**Comment by natebosch** [comment]
`build_web_compilers` and `build_modules` do a lot of work to avoid compiling libraries that aren't used. We don't support a per-package module system today.

> I can't find a way to compile dependency packages separately.

Building with `build_runner` and `build_web_compilers` will give you multiple modules, but not necessarily 1 per package. In many cases transitive deps with have ~1 per package, but it isn't guaranteed.

> I want to be able to reuse compiled packages.

This is _only_ possible if the places you are reusing the compiled results share:
- The exact same Dart SDK.
- The exact same set of _transitive_ dependency versions.

In general I wouldn't try to do this.

> Is it possible to ignore such files and throw a runtime error?

No. It is not feasible for use to compile such code, which is why we prune down modules by platform.

> Unfortunately, documentation for dartdevc is virtually non-existent. (At least I couldn't find it)

DDC isn't intended to be a public facing tool. `webdev` is the public facing tool.

> I think DDC currently can't do what I ask for, this is more a feature request than a question.

It can't, and we aren't likely to add support. If you want to elaborate on your use case we can maybe move this issue to the build repo and follow up with more discussion. We do use DDC for dartpad with a fixed set of allowed dependencies and I think that we use a precompiled version of those dependencies, but I don't know the details there. @jakemac53 may know more.

https://github.com/dart-lang/dart-services/blob/aec916c78aeb0c5a915ed48ded09d020cf33d0bd/lib/src/compiler.dart

**Comment by leisim** [comment]
Thanks for your answers :)
