### ISSUE TITLE
Migrate dart:io and its tests to NNBD

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40040]
This tracks the migration of dart:io and related tests.

**Comment by leafpetersen** [comment]
Migration instructions [here](https://docs.google.com/document/d/1rNUzoytzmlB17_53ITkPaMqYuqJyjy8RUMcNNfuND3Q/edit?usp=sharing).

**Comment by sortie** [comment]
So far I've migrated 11 of 30 files in `sdk_nnbd/lib/io`.

**Comment by sortie** [comment]
I've now migrated 88% (13619 of 15393) of the lines in dart:io and its VM patch files.

**Comment by sortie** [comment]
I've now completed a first pass of 100% of the lines in dart:io and its VM patch files. I'm taking a second look at my diff and discussed issues with the language team. I'll revise my changes and then upload them for review. I was not able to build the VM with it turned because the other core library patch files have not been migrated yet. The dart2js stub dart:io patch files also needs to be migrated, I might as well do that while here.

I'm yet to begin migrating the dart:io tests. The first pass will be to attempt fixing the compile time errors with the analyzer and the migration tool. The second pass will be running the tests, but that is blocked on the dart:io dependencies (such as core and others) having their patch files migrated, so the NNBD SDK can be built with dart:io NNBD turned on.

**Comment by leafpetersen** [comment]
Sounds great!  Are you planning to land the library code and then follow up with the tests, or do you plan to do them all in one?

**Comment by sortie** [comment]
I will land the library and patch file changes first since they are bundled and make sense on their own and does not need to wait for testing (which I don't think would work yet due to other missing patch files). The tests will be done in their own phase.

**Comment by leafpetersen** [comment]
👍

**Comment by sortie** [comment]
I've migrated dart:io to NNBD including the patch files and uploaded the changelist for review at <https://dart-review.googlesource.com/c/sdk/+/133060>.

**Comment by sortie** [comment]
I have addressed almost all of the review comments locally. There's a few more complicated cases I need to finish. I'll finish those tomorrow and do a final round of review.

**Comment by sortie** [comment]
I addressed the review comments and finished up the last complicated cases. I'm now waiting on a second round of reviewing and then we should be able to land the dart:io migration.

**Comment by sortie** [comment]
I've now migrated dart:io. It's not opted in by default yet, like most other VM libraries.

I'll start work on migrating the `standalone_2/io` tests.

**Comment by sortie** [comment]
I'm migrating the `standalone_2/io` tests to NNBD. 181 files were already valid under NNBD. I've now migrated 26 of 59 files (30%) that needed to be migrated.

**Comment by sortie** [comment]
cc @athomas

**Comment by sortie** [comment]
I've now migrated all the tests in `standalone_2/io` to NNBD. I'll submit a changelist for review tomorrow.

**Comment by sortie** [comment]
I've uploaded the `standalone/io` migration for review:

* [[nnbd] Copy standalone_2/io to standalone/io.](https://dart-review.googlesource.com/c/sdk/+/134332)
* [[nnbd] Migrate standalone/io to NNBD.](https://dart-review.googlesource.com/c/sdk/+/134338)

**Comment by sortie** [comment]
Some follow up CLs to fix the final analyzer errors left in dart:io and dart:_http:

* [[nnbd] Fix Process.stderr providing stdout instead in NNBD dart:io.
](https://dart-review.googlesource.com/c/sdk/+/134327)
* [[nnbd] Fix SecureServerSocket not allowing null SecurityContext.](https://dart-review.googlesource.com/c/sdk/+/134293)
* [[nnbd] Fix remaining NNBD errors in dart:_http and dart:io.](https://dart-review.googlesource.com/c/sdk/+/134722)
  * This change uncovered another Dart API bug that may require changing to the handling of invalid `HeaderValue`  parameters (not allowed by the specification) which might be a small breaking change in order to provide a reasonable API under NNBD. I'll attempt backport that change per the breaking change policy.
* Two final compile errors seem to be an analyzer bug (#40482).

I'm still waiting for the migrated standalone/io tests to be reviewed.

**Comment by sortie** [comment]
Breaking change #40483 needs to be made in order to nicely migrate `Process` to NNBD.

**Comment by sortie** [comment]
I've now landed all the CLs migrating dart:io to NNBD (including fixing the remaining errors in dart:_http).

I've also just landed the migration of the standalone/io tests to NNBD.

That's should be it all, barring actually getting the tests working later on. Closing.
