### ISSUE TITLE
Spread operator leaves much to be desired re: optimization

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#40065]
AngularDart currently uses a function called `flattenNodes` in some critical paths:

```dart
/// Flattens a `List<List<?>>` into a `List<?>`.
List<T> flattenNodes<T>(List<List<T>> nodes) {
  final result = <T>[];
  for (var i = 0, l = nodes.length; i < l; i++) {
    result.addAll(nodes[i]);
  }
  return result;
}
```

@leonsenft had the idea to try using the spread (`...`) operator instead. So for example:

```dart
// Before
void detectChangesInternal() {
  final _ctx = this.ctx;
  bool firstCheck = this.firstCheck;
  if (firstCheck) {
    (this._NgIf_2_9.ngIf = false);
  }
  this._appEl_2.detectChangesInNestedViews();
  if ((!import8.debugThrowIfChanged)) {
    if (this._viewQuery_Child_0_isDirty) {
      import5.View.queryChangeDetectorRefs[this._OnPushChild_0_5] =
          this._compView_0;
      _ctx.children = import14.flattenNodes([
        [this._OnPushChild_0_5],
        [this._Child_1_5],
        this._appEl_2.mapNestedViews((_ViewHasViewChildren1 nestedView) {
          import5.View.queryChangeDetectorRefs[nestedView._OnPushChild_0_5] =
              nestedView._compView_0;
          return [nestedView._OnPushChild_0_5];
        })
      ]);
      this._viewQuery_Child_0_isDirty = false;
    }
  }
  this._compView_0.detectChanges();
  this._compView_1.detectChanges();
}
```

```dart
// After
void detectChangesInternal() {
  final _ctx = this.ctx;
  bool firstCheck = this.firstCheck;
  if (firstCheck) {
    (this._NgIf_2_9.ngIf = false);
  }
  this._appEl_2.detectChangesInNestedViews();
  if ((!import8.debugThrowIfChanged)) {
    if (this._viewQuery_Child_0_isDirty) {
      import5.View.queryChangeDetectorRefs[this._OnPushChild_0_5] =
          this._compView_0;
      _ctx.children = [
        this._OnPushChild_0_5,
        this._Child_1_5,
        ...this._appEl_2.mapNestedViews((_ViewHasViewChildren1 nestedView) {
          import5.View.queryChangeDetectorRefs[nestedView._OnPushChild_0_5] =
              nestedView._compView_0;
          return [nestedView._OnPushChild_0_5];
        })
      ];
      this._viewQuery_Child_0_isDirty = false;
    }
  }
  this._compView_0.detectChanges();
  this._compView_1.detectChanges();
}
```

This changed the generated Dart2JS code from:

```js
// Before
detectChangesInternal$0: function() {
  var t1, t2, _this = this,
  _ctx = _this.ctx;
  if (_this._data._changeDetectorState === 0)
    _this._NgIf_2_9.set$ngIf(false);
  _this._appEl_2.detectChangesInNestedViews$0();
  if (_this._viewQuery_Child_0_isDirty) {
    $.$get$View_queryChangeDetectorRefs().$indexSet(0, _this._OnPushChild_0_5, _this._compView_0);
    t1 = type$.JSArray_Child;
    t2 = type$.Child;
    t2 = X.flattenNodes(H.setRuntimeTypeInfo([H.setRuntimeTypeInfo([_this._OnPushChild_0_5], t1), H.setRuntimeTypeInfo([_this._Child_1_5], t1), _this._appEl_2.mapNestedViews$2$1(new N.ViewHasViewChildren0_detectChangesInternal_closure(), t2, type$._ViewHasViewChildren1)], type$.JSArray_List_Child), t2);
    _ctx.toString;
    self.defeatDart2JsOptimizations(t2);
    _this._viewQuery_Child_0_isDirty = false;
  }
  _this._compView_0.detectChanges$0();
  _this._compView_1.detectChanges$0();
}
```

```js
// After
detectChangesInternal$0: function() {
  var t1, t2, t3, _i, _this = this,
  _ctx = _this.ctx;
  if (_this._data._changeDetectorState === 0)
    _this._NgIf_2_9.set$ngIf(false);
  _this._appEl_2.detectChangesInNestedViews$0();
  if (_this._viewQuery_Child_0_isDirty) {
    $.$get$View_queryChangeDetectorRefs().$indexSet(0, _this._OnPushChild_0_5, _this._compView_0);
    t1 = H.setRuntimeTypeInfo([], type$.JSArray_Child);
    t1.push(_this._OnPushChild_0_5);
    t1.push(_this._Child_1_5);
    for (t2 = _this._appEl_2.mapNestedViews$2$1(new N.ViewHasViewChildren0_detectChangesInternal_closure(), type$.Child, type$._ViewHasViewChildren1), t3 = t2.length, _i = 0; _i < t2.length; t2.length === t3 || (0, H.throwConcurrentModificationError)(t2), ++_i)
      t1.push(t2[_i]);
    _ctx.toString;
    self.defeatDart2JsOptimizations(t1);
    _this._viewQuery_Child_0_isDirty = false;
  }
  _this._compView_0.detectChanges$0();
  _this._compView_1.detectChanges$0();
}
```

As you can see, this took a place where we had a single re-used function, and starts embedding a fairly verbose `for`-loop across our applications/generated code. I was hoping that Dart2JS would be able to re-use code for spreads, especially in optimized mode, but it seems like at least right now it's worse than hand-rolling a "spread-like" function (`flattenNodes`).

Any thoughts?

**Comment by rakudrama** [comment]
Notes:

#### Smaller spread expansions
I would like spreads to compile to something smaller, like a call. It is complicated somewhat by the fact that Set and Map literals also have spreads, and there are spreads that are well-typed and spreads that need checks. To get the efficiency of the array loop in the code you quoted, there needs to be many spread methods, perhaps a spread method _for each class implementing get:iterator_ (otherwise you lose indexing - a single helper function must use general iterator code instead of indexing). This could be a lot of code (even if 90% just called a single shared method for the non-inlinable iterators), and a bad choice for code size unless there are many hundreds of spreads. The current scheme is at least pay-as-you-go.

#### Better code for current expansion
The code above could be a bit smaller. @sigmundch The concurrent modification error check could be eliminated with an effects system that incorporates some alias information. We know that `JSArray.add/push` changes _a length_, but what we need to know is that it changes _receiver.length_. Since the list being constructed has not escaped, it is has no aliases, we could tell that `push` does not change the length of the list being iterated. I have played with a special case handling for JSArray.add, in SsaLoadElimination. It works on this kind of code, but didn't have a big impact. Perhaps we should re-assess.

#### Try for-in instead of spread
@leonsenft @matanlurey You are doing something similar to `[... a.map((x) => f(x + 1))]`.  Perhaps for-in is better than spread: `[for(var x in a) f(x + 1)]`.

It might look a bit like this:

```dart
      _ctx.children = [
        this._OnPushChild_0_5,
        this._Child_1_5,
        for(_ViewHasViewChildren1 nestedView in this._appEl_2.nestedViews)
          _helper(nestedView)
      ];
...

  SomeType _helper(_ViewHasViewChildren nestedView) {
    import5.View.queryChangeDetectorRefs[nestedView._OnPushChild_0_5] =
        nestedView._compView_0;
    return nestedView._OnPushChild_0_5;
  }
}
```

#### Emit your own code similar to spreads
@leonsenft @matanlurey You could try to generate the code that you think spread should have generated.
You can thread-through the list you are building instead of building a list that gets copied, in effect flattening as-you-go:

```
      var a = <??>[];
      a.add(this._OnPushChild_0_5); // This and the next could be folded into the literal.
      a.add(this._Child_1_5);
      this._appEl_2.mapNestedViewsAccumulate(a, (_ViewHasViewChildren1 nestedView) {
          import5.View.queryChangeDetectorRefs[nestedView._OnPushChild_0_5] =
              nestedView._compView_0;
          return [nestedView._OnPushChild_0_5];
        });
      _ctx.children = a;

  void mapNestedViewsAccumulate<T, U extends DynamicView>(
    List<T> accumulator,
    List<T> Function(U) callback,
  ) {
    final nestedViews = this.nestedViews;
    if (nestedViews == null || nestedViews.isEmpty) {
      return;
    }
    for (var i = 0, l = nestedViews.length; i < l; i++) {
      accumulator.addAll(callback(unsafeCast<U>(nestedViews[i])));
    }
  }
```
You could try making the closure do `a.add` instead of `return`.
The downside is that the closure is now a full closure (with free variable `a`), and no longer something that could be moved to a static method. (We have some ideas for making static tearoffs smaller which would not apply to the full closure.)
```
      var a = <??>[];
      a.add(this._OnPushChild_0_5); // This and the next  could be folded into the literal.
      a.add(this._Child_1_5);
      this._appEl_2.walkNestedViews((_ViewHasViewChildren1 nestedView) {
          import5.View.queryChangeDetectorRefs[nestedView._OnPushChild_0_5] =
              nestedView._compView_0;
          a.add(nestedView._OnPushChild_0_5]);
        });
      _ctx.children = a;

  void walkNestedViews<T, U extends DynamicView>(
    List<T> Function(U) callback,
  ) {
    final nestedViews = this.nestedViews;
    if (nestedViews == null || nestedViews.isEmpty) {
      return;
    }
    for (var i = 0, l = nestedViews.length; i < l; i++) {
      callback(unsafeCast<U>(nestedViews[i]));
    }
  }
```

**Comment by rakudrama** [comment]
@matanlurey @leonsenft f7ae22a4c1996fa5b74de67b64956f8afe59df24 changed the code patterns generated for spreads to use `addAll` (or `List.of` at the beginning). `addAll` and `List.of` were further optimized to keep performance in-line with custom loops where the spread argument is already a `List`.

Does this address your concerns?

**Comment by leonsenft** [comment]
Thanks, @rakudrama! It looks like dart2js now produces code for `...` that's on par with our previous handwritten method. I've updated our code generator to use `...`.
