### ISSUE TITLE
Process.run on windows throws away empty arguments

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#40060]
test.dart:
```dart
import 'dart:io';

main() async {
    var result = await Process.run('dart', ['bin/print_args.dart', 'before', '', 'after']);
    print(result.stdout);
}
```
print_args.dart
```dart
main(List<String> args) {
    print('[${args.map((x) => '"$x"').join(', ')}]');
}
```

Prints:
```
>dart bin/test.dart
["before", "after"]
```

I would have expected `["before", "", "after"]`

**Comment by sortie** [comment]
Can you also test what happens if runInShell: true?

**Comment by sigurdm** [comment]
It seems to give the same result

**Comment by sigurdm** [comment]
https://github.com/bazelbuild/bazel/issues/4778 might be similar?

**Comment by ZichangG** [comment]
This is relative to how Windows parse `argc` and `argv`.

Our windows implementation is basically concatenating the arguments and pass into [CreateProcessW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw).

For an empty string, it will presented as two consecutive space. "before  after" in your example.  It will be swallowed by parsing.

**Comment by ZichangG** [comment]
I don't think we can do something in VM unless updating the doc for this specific corner case.

**Comment by sortie** [comment]
@ZichangG This is a bug in the Dart that is trivial to fix. You can see how Windows parses commands into arguments in ["Parsing C++ Command-Line Arguments"](https://docs.microsoft.com/en-us/previous-versions/17w5ykft(v=vs.85)) and [CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw). An empty argument can be represented by two double quote characters. The problem is that the `_windowsArgumentEscape` function in `sdk/lib/_internal/vm/bin/process_patch.dart` only checks for whitespace characters, but it forgot about the empty string case. The fix is simply to return "" if the string is empty.

**Comment by ZichangG** [comment]
`_windowsArgumentEscape` does return empty string if input is empty. I don't think this causes the problem.

Let's use the example above. Dart side will pass `arguments` (an array of `String`) to VM. `arguments` array will be ["before", "" and "after"]. Since `CreateProcessW` takes a single string instead of an array. VM will concatenate strings. The `argument` will become "before  after"(two spaces in between).

**Comment by sortie** [comment]
I didn't mean the empty string, I meant a pair of double quotes, `'""'`. CreateProcessW will then be provided with `'before "" after'`.
