### ISSUE TITLE
Uri.queryParameters expects `Map<String, String|Iterable<String>>` but takes `Map<String, Dynamic>`

### ISSUE THREAD

**Issue by exts** [dart-lang/sdk#40073]
* Dart SDK Version (`dart --version`) - 2.7.0
* Whether you are using Windows, MacOSX, or Linux (if applicable) - Windows

**Issue:**

When building a `Uri` and passing values to queryParameter, it's expecting a `String` or `Iterable<String>`, but takes Dynamic instead of the union type (which is commented out in the [source](https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/uri.dart#L131))

So when passing this type of path:

```dart
    Map<String, dynamic> queryOptions = {
      "limit": 5,
      "created[gte]": "1577836800",
    };

    var uri = Uri(scheme: "https", host: "api.stripe.com", path: "v1/balance_transactions", queryParameters: queryOptions);
```

You'll get this error: `type '_Smi' is not a subtype of type 'Iterable<dynamic>'`

So, [the code](https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/uri.dart#L2281) that I assume handles this would either need to be updated to support dynamic values and parsing toString() or force String|Iterable<String>. Not sure how you want to approach that. 

(ps: is there a guide on contributing to the sdk, and testing locally?)

**Comment by exts** [comment]
Wait is that comment a 'hint' ? I guess that makes sense if `Map<String, Iterable<String>>` isn't a thing in dart lang.

**Comment by tatumizer** [comment]
Try passing "limit": "5" (as a string, not int)

**Comment by exts** [comment]
@tatumizer  Yeah that's what I did so I wouldn't get the error. I was checking the source to see if there was something I was missing, and the correct syntax after testing _should_ be `Map<String, Iterable<String>>` - I can make a PR as it wouldn't break anything because it's the expected input.

**Comment by lrhn** [comment]
The `dynamic` type is the best we can do here. Dart does not have union types, so `String | Iterable<String>` is not something that can be expression in code. Instead the function accepts a supertype of the two `dynamic`, and fails at run-time if the value is neither a string nor an iterable of strings.

That is: This is expected behavior and not something we can change to anything better at the current time.
(Yes, the comment is a hint intended for people editing the code, users need to read the documentation instead).

**Comment by exts** [comment]
@lrhn why not throw a clear exception if the value isn't `Iterable<String>`

```dart
    queryParameters.forEach((key, value) {
      if (value == null || value is String) {
        writeParameter(key, value);
      } else {
        if(value !is Iterable<String>) {
            throw Exception("Value must be of type Iterable<String>");
        }
        
        Iterable values = value;
        for (String value in values) {
          writeParameter(key, value);
        }
      }
    });
```

So the error is at least clear on what's happening.

**Comment by lrhn** [comment]
We could be more strict with the errors, or at least more precise.

The current code accepts any `Iterable` which has string *values*, even if it's an `Iterable<Object>`. Adding a test like the above would therefore be a breaking change if anyone is using that feature. So, we can at most check that `value` is an `Iterable`, and if it is not, we should throw an `Error`. Then we check for each value whether it's a `String`, and if not, we should throw an `Error`.
That is actually what this code is doing. The only thing we can do differently is to do the check explicitly and create a more expressive error (perhaps an `ArgumentError` instead of a `CastError`/`TypeError`).
