### ISSUE TITLE
Enhanced type promotion with nnbd inconsistent on type variable

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#40089]
If I run the dartanalyzer (`--enable-experiment=non-nullable`) on the following, I get a null error on the return in the first function, but not the second:

```dart
T foo<T>(T? x, T f()) {
  T? y = x;
  if (y == null) {
    y = f();
  }
  return y; // error • A value of type 'T?' can't be returned from function 'foo' because it has a return type of 'T'
}

String bar(String? x, String f()) {
  String? y = x;
  if (y == null) {
    y = f();
  }
  return y; // No error
}
```

Is this correct behavior or a bug in the analyzer?  @leafpetersen @munificent @stereotype441

**Comment by leafpetersen** [comment]
I believe this is a bug.  There's some discussion about how to specify operator ==, but I think with either of the open proposals, the true continuation of `y == null` should promote `y` to **NonNull(`T?`)**, which is `T`.

cc @stereotype441 @scheglov  am I missing something?

**Comment by scheglov** [comment]
The default type of a type parameter is `Object?`. When we check `x == null` the type of interest becomes `T & Object`, and `f` return type of `T extends Object?`, which is not a subtype of `T & Object`.

**Comment by leafpetersen** [comment]
Ah, interesting.   I think this is related to https://github.com/dart-lang/sdk/issues/40011 , but I don't think the current spec handles this, and I wonder if we should find a way to do so.

Issue #40011 tracks the desire to make **NonNull(`T`)** a type of interest if `T` is a type of interest.  This isn't enough for this issue though:
  - Given `X extends Object?` this isn't enough to make `X` a type of interest if `X?` is a type of interest, since **NonNull(`X`)** is `X & Object`, not `X`.
  - Also, given `X extends Object?`, and a promotion history of `[X?, Null]`, we can't demote to `X`, since **NonNull(`X`)** is not in the promotion history.

This seems a little non-ideal.  It seems to me that in the example above, the declaration `T? y = x` and the comparison `y == null` suggest a potential interest in the types `T?`, `T` and `T & Object`.  I'll have to think about this a bit more.  It seems potentially feasible to extend the treatment in #40011 a bit further to include all of these types, but it needs a bit of thought.

@johnniwinther @stereotype441 any thoughts on this?

**Comment by leafpetersen** [comment]
This is not planned.
