### ISSUE TITLE
Fields of potentially non-nullable types without initializers should be a compile-time error

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#40081]
The following program compiles without errors currently:

```dart
int x;

class A<T extends Object?> {
  static int x;
  int lx;
  T lt;
}
```

<details>
<summary>Click to expand</summary>

```
$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/tool/_fasta/compile.dart --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
library;
import self as self;
import "dart:core" as core;

class A<T extends core::Object? = core::Object?> extends core::Object {
  static field core::int x = null;
  field core::int lx = null;
  generic-covariant-impl field self::A::T% lt = null;
  synthetic constructor •() → self::A<self::A::T%>
    : super core::Object::•()
    ;
}
static field core::int x;
```
</details>

**Comment by lrhn** [comment]
It should indeed be an error because the *default constructor* does not initialize these fields.
(It's an error if a generative constructor does not initialize a non-nullable field that does not have an initializer expression).

The static field `x` is an error by itself.

I guess it's safe to have *no* generative constructors:
```dart
class C {
  int x;
  factory C() = D; // which implements C.
}
```
I'm not sure there would be any errors for that class because there is no generative constructor which doesn't initialize `x` (vacuously). The class should probably be `abstract`, but again there is no problem that it isn't, you can't instantiate it anyway.
