### ISSUE TITLE
Migrator should remove (or at least understand) the null aware operator ?.

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40137]
found in package:collection.

```dart
T get current => _iterators.current?.current;
```

This migration should remove the `?`. `Iterator.current` is defined to return a non-nullable type, so it is dead code.

At the very least, if we do not remove the `?`, per spec behavior it results in a nullable type. So we should either understand that or mark the resulting nodes as nullable so that we later get a `!`. Preferably the former over the latter.

The former would be a change to FixBuilder, so + @stereotype441

**Comment by stereotype441** [comment]
There are two cases that I think we should consider treating differently:
- Removing a `?` that is rendered unnecessary by the addition of short-circuiting
- Removing a `?` that is rendered unnecessary by the fact that the target is non-nullable, but there's no short-circuiting involved.

In the former case, I think that having the migration tool automatically remove the `?` is a pretty clear win.  In the latter case, though, we have to ask ourselves, why did the programmer put the `?` there in the first place?  There are two possibilities:
- Maybe they were just being super-cautious, or they were lazy and didn't want to take the time to prove to themselves that it could never be null.
- Or, maybe the target actually *can* be null, and what's actually happening is that the migration tool has given it an incorrect type.

It's really important to distinguish between these two possibilities, because in the former case, removing the `?` is fine, but in the latter case, a human needs to intervene and fix the incorrect type.  Often these extra `?`s are the only indication we get that the migration tool has made a mistake, so I worry that having the migration tool automatically "fix" them would do more harm than good.

**Comment by stereotype441** [comment]
Unassigning myself because I'm not actively working on the migration tool right now.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
