### ISSUE TITLE
NNBD not working with analyzer in 2.8.0-dev.1.0 release?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#40135]
Sample program:

```dart
void main() {
  f();
}

void f([int? x]) => print(x ?? 0);
```

`analysis_options.yaml`:
```yaml
include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
```

yields: 

error: This requires the 'non-nullable' experiment to be enabled. (experiment_not_enabled at [nnbd] bin/main.dart:5)

I believe this would've worked fine for a while now, perhaps it's temporarily broken?

**Comment by mnordine** [comment]
Same result with 2.8.0-dev.2.0

**Comment by hongyiweiwu** [comment]
This is almost making the sdk unusable. Please fix.

**Comment by mnordine** [comment]
Still not fixed in 2.8.0-dev.3.0  

I'm testing on MacOS Catalina btw

**Comment by mnordine** [comment]
Same on Windows

**Comment by mnordine** [comment]
Still not fixed in 2.8.0-dev.4.0

**Comment by hongyiweiwu** [comment]
Still not fixed in 2.8.0-dev.5.0

**Comment by jakemac53** [comment]
> error: This requires the 'non-nullable' experiment to be enabled. (experiment_not_enabled at [nnbd] bin/main.dart:5)

What steps are you doing to see this error? 

Note that this only enables the experiment for the analyzer and not any backends (ddc, dart2js, vm, etc). None of those support it yet. This is a static analysis feature only at this time.

**Comment by hongyiweiwu** [comment]
@jakemac53 i was just running dartanalyzer —enable-experiment=non-billable lib where lib is the folder containing all dart source code for my project.

**Comment by jakemac53** [comment]
Hmm yes I see this behavior as well. See also https://github.com/dart-lang/sdk/issues/37913

**Comment by mnordine** [comment]
Yeah, I'm only attempting to do static analysis

**Comment by hongyiweiwu** [comment]
Doesn't work on dev 6.0

**Comment by kevmoo** [comment]
I'm SUPER excited to experiment with the *null safety* feature, too – we're just not there yet.

We'll send out an [announcement](https://groups.google.com/a/dartlang.org/forum/#!forum/announce) when it'll be interesting to try out!

**Comment by mnordine** [comment]
Yeah, I only reported this issue because:
- It previously worked
- May be an issue with enabled any experiment
- In case it was working in `master`, but not working in the public dev releases

**Comment by scheglov** [comment]
Yes, at some point analyzer started to ignore enabled experiments if your package targets *any* specific language version. We decide that we want to allow "current unreleased" version to include experiments.

With 81bc6295824036c52825769394ae515dd162c245 landed, the following is necessary to enable `non-nullable` experiment.

1. Edit `analysis_options.yaml` and add the experiment.
```yaml
analyzer:
  enable-experiment:
    - non-nullable
```
2. Edit `pubspec.yaml` and specify that your package targets the "current unreleased" version of Dart SDK.
```yaml
environment:
  sdk: '>=2.8.0-dev.0 <2.8.0'
```
3. Run pub.
4. Restart Dart Analysis Server so that it picks-up the updated `.dart_tool/package_config.json`.

**Comment by mnordine** [comment]
Thank you *very* much for this. Is there going to be a dev release soon so we can test this?

**Comment by scheglov** [comment]
I don't know about release schedule. @athomas might know.

**Comment by athomas** [comment]
dev releases go out on Tuesdays and Thursdays when there aren't any release
blockers. So it might be in tomorrow's release or in the one next Tuesday.

**Comment by mnordine** [comment]
@scheglov I've tried your steps with `2.8.0-dev.12.0`, same result, static analysis *does not* work:

`error: This requires the 'non-nullable' experiment to be enabled. (experiment_not_enabled at [untitled] bin\main.dart:5)`

**Comment by scheglov** [comment]
Hm... Don't know. Could you create a simple project, do the described steps, ensure that the experiment does not work, archive the whole directory (including `.dart_tool`) and attach it to the issue?

**Comment by mnordine** [comment]
Of course, here ya go:

[test.zip](https://github.com/dart-lang/sdk/files/4294203/test.zip)

**Comment by athomas** [comment]
https://github.com/dart-lang/sdk/commit/81bc6295824036c52825769394ae515dd162c245
is not in any release, yet (otherwise the commit page would show some
tags). We do not create dev releases from tip of tree, these are built from
a revision that has passed not only our own test suites but also those of
some of our customers/downstream projects.

**Comment by mnordine** [comment]
OK, will wait on it.

**Comment by mnordine** [comment]
Seems to work now, thx! This is awesome, :)
