### ISSUE TITLE
"Create missing overrides" will only create one overrides when there's "extends" and "with"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#40191]
Raised by @FaridAhamat at https://github.com/Dart-Code/Dart-Code/issues/2206.

I can repro - seems like the server only looks at one of the classes. If you remove the `with` then you get the `build` method. It should probably combine them all, or generate separate quick fixes for `Create 1 missing override for AutomaticKeepAliveClientMixin` and `Create 1 missing override for State<MyClass>`?

---

Steps to reproduce:
1. Create a class such as:

`class _MyClassState extends State<MyClass> with AutomaticKeepAliveClientMixin {}`

2. Click Ctrl + . , or hit the lightbulb for quick help.
3. Click "Create 1 missing override(s)".

Actual:
VS Code will generate the override for wantKeepAlive, but totally missing out on build function.

Expected:
VS Code should generate all the necessary overrides, both for State's build and Mixin's function.

**Comment by FaridAhamat** [comment]
I would prefer if it would just combine them all. 

I can't see a situation where anyone would purposely miss out on either one of those considering they are both required, and it'd also avoid cramming the light bulb with too much options.

**Comment by FMorschel** [comment]
I found this issue and I'm curious as to how should the quick-fix know that it must implement the build function in this case. Would it be mandatory for it to always add the build function on `State`s? 

I've looked at the `AutomaticKeepAliveClientMixin` and it does implement the build function already. I know the current behavior is not what we would want but I'm unsure what will be the rule here. 

Maybe we should think about another annotation? It is currently using the `@mustCallSuper` but so are `@initState` and related by default so that would probably not be something that we should rely on.

I think there could be some benefit for a rule that would allow you to implement something inside a method and be sure any class that extends it would call whatever you wrote _and also_ need to implement something else (even if that something else is simply adding the return to your function like `Widget build(BuildContext context) => super.build(context);`).

**Comment by bwilkerson** [comment]
> ... I'm curious as to how should the quick-fix know that it must implement the build function in this case.

Me too. The quick fix is currently designed to add (the stub for) a concrete implementation of every abstract method that's required to be implemented. The implementation of `build` in `AutomaticKeepAliveClientMixin` means that there's already a concrete implementation of `build`, so there's no need (from that perspective) for a stub to be added.

If it's the case that `build` must always be overridden, then we should ask the Flutter team to add `@mustBeOverridden` to the `build` method in the mixin.

@goderbauer

**Comment by goderbauer** [comment]
I didn't know `@mustBeOverridden` was a thing... Cool! Adding it to the `build` method of `AutomaticKeepAliveClientMixin` sounds like the right thing to do here.
