### ISSUE TITLE
Regression with <T extends num> in 2.8.0-dev.3.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40212]
Dart: 2.8.0-dev.3.0

https://travis-ci.org/kevmoo/qr.dart/jobs/638523576#L263-L269

Just started happening with the latest SDK. 

```dart
class Coordinate<T extends num> extends math.Point<T> {
  const Coordinate([T x, T y]) : super(x, y);

  bool get isValid => isValidNumber(x) && isValidNumber(y);

  @override
  Vector<T> operator -(math.Point<T> other) => difference(this, other);

  @override
  Coordinate<T> operator +(math.Point<T> other) =>
    // error: The argument type 'num' can't be assigned to the parameter type 'T'. (argument_type_not_assignable at [qr] example/src/affine_transform.dart:219)
      Coordinate<T>(x + other.x, y + other.y);

  Vector toVector() => Vector(x, y);

  Size toSize() => Size(x, y);

  static Vector<T> difference<T extends num>(
          math.Point<T> a, math.Point<T> b) =>
      Vector<T>(a.x - b.x, a.y - b.y);

  static bool valid(math.Point point) =>
      isValidNumber(point.x) && isValidNumber(point.y);
}
```

**Comment by lrhn** [comment]
The static type of `x + other.x` is `num` (`super.x` has type `T extends num` so its `+` operation has signature `num operator+(num value)`. 

What you have here should be an implicit downcast from `num` to `T`, which should be allowed because `T` is a subtype of `num`. 

Now, if you use `--no-implicit-casts`, then you *do* get exactly the error you see here, as you should. In that case, the analyzer is acting correctly.

**Comment by kevmoo** [comment]
So this is *not* a bug, @lrhn ?

**Comment by lrhn** [comment]
If you use `--no-implicit-casts` (or equivalent options), then I don't think it's a bug, no.
The error does not occur without that option, and it is an implicit downcast.

**Comment by kevmoo** [comment]
So it's actually showing a bug FIX on the part of analyzer – got it!
