### ISSUE TITLE
Dart tcp client does not recieve data which is sent fast 

### ISSUE THREAD

**Issue by ImanHz** [dart-lang/sdk#40228]
I have a simple TCP client in dart:
```
import 'dart:io';

void main() {
  const sendData = "\$I,Z,0.5,5,0*\r\n";

  final socket = Socket.connect("192.168.1.100", int.parse("8008"))
      .timeout(Duration(seconds: 5))
      .whenComplete(() {
    print("Connected!");
  }).catchError((_) {
    print("Error!");
  });
  socket.then((soc) {
    soc.write(sendData);
    soc.listen((data) {
      print(String.fromCharCodes(data).trim);
    });
  });
}
```

This program sends a special message to server and after that, the server sends back a bunch of data **every 10 ms**. The output is as follows:
```
$I,1,250,0,206*$I,1,248,0,192*$I,1,246,0,178*$I,1,245,0,165*
$I,1,244,0,153*$I,1,244,0,141*$I,1,244,0,131*$I,1,245,0,121*
$I,1,246,0,113*$I,1,248,0,105*$I,1,250,0,98*
$I,1,253,0,92*$I,2,0,0,86*$I,2,4,0,82*$I,2,8,0,79*$I,2,12,0,76*
$I,2,18,0,74*$I,2,23,0,74*$I,2,29,0,74*$I,2,36,0,75*$I,2,42,0,77*$I,2,50,0,80*$I,2,58,0,84*$I,2,66,0,89*$I,2,74,0,94*
$I,2,83,0,101*$I,2,93,0,109*$I,2,103,0,117*$I,2,113,0,126*$I,2,124,0,136*$I,2,134,0,147*
$I,2,146,0,159*$I,2,157,0,171*$I,2,169,0,185*$I,2,182,0,199*$I,2,194,0,214*$I,2,207,0,230*$I,2,220,0,246*$I,2,233,1,8*$I,2,247,1,26*$I,3,5,1,44*$I,3,19,1,64*$I,3,33,1,84*
$I,3,48,1,105*$I,3,63,1,126*$I,3,77,1,148*$I,3,93,1,171*$I,3,108,1,194*$I,3,123,1,217*
$I,3,138,1,242*$I,3,154,2,10*$I,3,169,2,35*$I,3,185,2,61*$I,3,201,2,87*$I,3,216,2,113*$I,3,232,2,140*$I,3,248,2,167*$I,4,7,2,195*
$I,4,23,2,223*$I,4,39,2,251*$I,4,54,3,23*$I,4,70,3,51*
```

The server sends data in **$I,1,250,0,206*** format, i.e. starts with $ and ends with *. 
As one may note, several consecutive data packages are concatenated incorrectly. Whenever I increase the interval, for example to 200 ms, everything is ok.

- Server is written in LabVIEW. I can provide the vi file if it helps.
- I use Dart version 2.7.0. Server and client are both on windows 10 64-bit.

**Comment by sortie** [comment]
TCP is a byte stream and applications do not have access to packet boundaries. If the one end has sent multiple packets, and the other end is not quick enough to process them, then the packets will be combined and read at once. That's what is happening here and why increasing the interval happens to work. It may even split packets and the other end may receive fragmented packet. Both cases are perfectly normal due to network conditions and you must handle them.

You will have to implement your own message/packet handling on top of the TCP byte stream. Your application protocol is delimited with $ and *, so you can simply keep reading until you have a full message (or multiple) and then process it.

Alternatively you can use a packet based network protocol. The only other one supported by Dart is UDP, which allows you to send small datagrams, though note there is no guarantee of deliver, and no guarantee the datagrams arrive in the right order, and no guarantee the datagrams are not delivered multiple times. TCP provides you with those guarantees but you need to implement any packet/message boundaries on top of it in your own protocol.
