### ISSUE TITLE
Wrong error message when final variable assigned second time

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40242]
Run the following code
```dart
class C {}
main() {
  final C c = new C();
  c = new C();
}
```
Analyzer produces correct error message
`error - 'c', a final variable, can only be set once.`
But VM produces
```
Error: Setter not found: 'c'.
  c = new C();
  ^
```
Expected result: on VM an error message should looks like analyzer's one

Tested on Dart VM version: 2.8.0-dev.3.0 (Thu Jan 16 14:59:50 2020 +0100) on "windows_x64"

**Comment by lrhn** [comment]
Both front-end and analyzer are being confusing, bordering on incorrect. The message can be better in both cases.

You cannot assign to a final non-late variable, so a correct error would be:
> Error: You cannot assign to the final variable 'c'.

The analyzer is being confusing here, or even incorrect. 
There is no "assigning twice" here because there is no assigning *once*. Initialization of a final variable is not an assignment.

The front end is also confusing because it talks about setters, but *local* variables do not introduce setters. When resolving `c = C();`, the lexical lookup finds the `final C c` declaration, and because that declaration is final and unassignable, it's an error to assign to `c`. No setters are involved.

So: The front end's message would be correct for an instance variable, but is not for a local variable. The analyzer's message is wrong for all final non-late variables.
