### ISSUE TITLE
Parser support for ?[

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40267]
Parser support for null aware index access without '.':

`e?[e]` and `e?[e] = e` in addition to `e?.[e]` and `e?.[e] = e`

**Comment by eernstg** [comment]
Actually, @mit-mit agreed that we do not have to support the variant with the `.`.

@lrhn, @munificent, @leafpetersen, do you agree that we can simply stop supporting `v?.[0]` and such?

**Comment by lrhn** [comment]
There are a few uses. A grep shows:
```
../sdk_nnbd/lib/_http/websocket.dart:    String? part = requested?.parameters?.[_serverMaxWindowBits];
../sdk_nnbd/lib/core/uri.dart:    String? charsetName = parameters?.["charset"];
```
(And then there are all the uses in the tests (pkg/analyzer, pkg/_fe_analyzer_shared, tests/language/nnbd).

If we change all of those at the same time that we land the `?[` syntax, we should be fine.

**Comment by jensjoha** [comment]
As I understand these are also new and has to be supported:
```
  // Method calls.
  a?<B>(c);
  a?(b);
```

**Comment by eernstg** [comment]
> As I understand these are also new and has to be supported

True. I was just making the point that there is no need to support the form that includes the period for the index operator, so we can eliminate the code that does this, or omit implementing it if there is no suchcode. I believe that `f?.()` was never implemented.

**Comment by munificent** [comment]
> As I understand these are also new and has to be supported:
> 
> ```
>   // Method calls.
>   a?<B>(c);
>   a?(b);
> ```

I could be wrong, but I don't believe we have decided to add null-aware call operators. Instead, for this case (at least for now), we're OK with users doing `a?.call<B>(c)` and `a?.call(b)`.

**Comment by jensjoha** [comment]
> > As I understand these are also new and has to be supported:
> > ```
> >   // Method calls.
> >   a?<B>(c);
> >   a?(b);
> > ```
> 
> I could be wrong, but I don't believe we have decided to add null-aware call operators. Instead, for this case (at least for now), we're OK with users doing `a?.call<B>(c)` and `a?.call(b)`.

I'll hold off that change then.

Generally I also think that these changes makes the parser slower.
When seeing a `?` (not `.?` or `.?[`) before this change, we immediately knew that it was a conditional expression and could parse away happily.
With the `e.?[e]` => `e?[e]` change we now have to skip the expression whenever seeing a `?` followed by a `[` to figure out whether it's a conditional or an index access.
If also adding the call change, when seeing a `?` followed by `<` or `(` we would have to try to parse and expression and an argument list at the same time in an attempt to figure or what case we're in.

**Comment by eernstg** [comment]
@munificent wrote:
> we're OK with users doing `a?.call<B>(c)` and `a?.call(b)`.

Right, checking again: the language team meeting document actually doesn't commit to the null-aware function calls. In any case, it's good that we get to assess the difficulties and parser performance issues in smaller bites. The ambiguity does introduce a need to have some kind of back-tracking, so we will surely be able to write a pathological program that causes a timeout or stack overflow during parsing, and that is something that we don't want to have too frequently.

**Comment by munificent** [comment]
> Generally I also think that these changes makes the parser slower.
> When seeing a `?` (not `.?` or `.?[`) before this change, we immediately knew that it was a conditional expression and could parse away happily.

Yeah, it was expected that this increases parsing complexity. However, users felt very strongly that `?[` was the better syntax.

**Comment by eernstg** [comment]
Summary of a discussion taken elsewhere:

The grammar rule for null-aware index operator invocations (plus invocations of the corresponding setter) like `var z = x?[y];` (respectively `x?[y] = z;`) specifies that the `?` and the `[` are separate tokens.

This means that it makes no difference if some whitespace is added between the '?' and the '['. In particular `var z = x? /* Some Comment */ [y];` works just as well as `var z = x?[y];`.

It may seem tempting to say "let's parse `?[` as a single token, that allows us to disambiguate immediately": When there is no space between '?' and '[' it must be a null-aware index, when there is a space it must be a conditional expression.

However, we did not specify it in this manner, because this would imply that we use whitespace as a source of _disambiguation_. So you have two syntactically correct Dart snippets, _P1_ and _P2_, that only differ in one spot: You can produce _P2_ by taking _P1_ and adding one space. If _P1_ and _P2_ have a different _meaning_ (actually: they would parse into different abstract syntax trees), then we would be using whitespace to distinguish two different pieces of code. We preferred to aim for a situation where adding a space makes no difference, or it turns the snippet into a syntax error, but it doesn't give the snippet a new meaning.

So that's the reason why those two characters are tokenized as `?` `[` and not as `?[`.

**Comment by lrhn** [comment]
For the record, I'm not opposed to making `?[` have to be consecutive characters when interpreted as a null-aware index, as long as `x?[1]:2` is still parsed as a conditional expression even without the space.

I'm not sure it makes a big difference in practice. Parsing may be faster for correctly formatted conditional expressions where the `?` and `[` are separated, but it won't be any faster when seeing `?[` together, so there is no change to the worst-case performance. If you think it is actually an advantage, the we can consider it.

**Comment by bwilkerson** [comment]
> It may seem tempting to say "let's parse ?[ as a single token, that allows us to disambiguate immediately": When there is no space between '?' and '[' it must be a null-aware index, when there is a space it must be a conditional expression.

For the record, that's not what I was proposing (apologies if that wasn't clear). I was proposing that `? [` is never a null-aware index but that `?[` could be either depending on lookahead. As Erik pointed out in the other thread, it's the same treatment that we give to `>>`, which can either be a single operator or two separate `>` tokens, such as in a type argument list.

Unlike the either-or scenario you outlined, I don't believe that my proposal uses whitespace to disambiguate. Given a valid conditional expression `c?[1]:[2]`, you get the same valid expression by adding whitespace `c? [1]:[2]`. Given a valid null-aware indexing expression `a?[b]` you get invalid code by adding whitespace `a? [b]`. Whitespace never changes how the code is interpreted, only whether it's valid.

> If you think it is actually an advantage, the we can consider it.

It seems inconsistent to me to allow a space in this operator when we don't allow spaces in any other operators (unless the operator requires non-whitespace tokens inside it, such as `[]` and `?:`). I think that inconsistency would be confusing to users. The comment concern illustrates the point. I expect that nobody would be surprised or confused to see `a?[ /* comment */ b]`, but that most users would be surprised and confused to see `a? /* comment */ [b]`. As a result, I think it would be better for users if we did not allow a space.

By the way, how are we handling an ambiguity like
```
var y = { x ? [1] : [2] };
```
Is that a set or a map? Or is that just illegal?

If it's illegal, I'll note that we could make it valid if we didn't allow spaces between the `?` and `[` for the null-aware index operator because then it could only be interpreted as a set containing a single value that is the result of a conditional operator. There is, of course, another way to disambiguate the expression (by adding type arguments to the collection), so it isn't necessary to allow another disambiguation technique, but it might be nice.

**Comment by lrhn** [comment]
OK, let's think about this at the language team meeting today. Seems reasonable to me.

For
```dart
  var y = { x ? [1] : [2] };
```
it is a set literal containing a conditional expression, and so is
```dart
  var y = { x?[1]:[2] };
```

Because `x?[1]:[2]` *can* be parsed as a conditional expression, it will not parse `x?[` as a null-aware index operator.

**Comment by eernstg** [comment]
@bwilkerson wrote:
> Given a valid conditional expression `c?[1]:[2]`, you get the same valid
> expression by adding whitespace `c? [1]:[2]`. Given a valid null-aware
> indexing expression `a?[b]` you get invalid code by adding whitespace `a? [b]`.

OK, I'd be fine with that as well. We could specify that as a special treatment in the lexer (and this may or may not be a useful strategy in the implementation as well): The lexer always creates two tokens (so the grammar remains the same), but in the case where we parse a null-aware index operator invocation it is a compile-time error for the two tokens `?` and `[` to have whitespace between them.

**Comment by bwilkerson** [comment]
> ... in the case where we parse a null-aware index operator invocation it is a compile-time error for the two tokens ? and [ to have whitespace between them.

Do we have a similar restriction elsewhere?

> ... this may or may not be a useful strategy in the implementation as well ...

It would be more consistent with the way other tokens are handled to create a single token and to split it when necessary. It would also simplify the implementation in the analyzer (because an index expression's left bracket would either be a `[` or `?[`, a single token in either case, which wouldn't require a change to the shape of the AST).

**Comment by lrhn** [comment]
We have talked about it, and decided to keep the currently specified grammar. That means that `?` and `[` are separate tokens and can be separated by whitespace or comments. The formatter will remove the whitespace. If it was a compile-time error, the formatter could not do that.

I'm not sure you need to change the *shape* of the AST (depending on what you mean by "shape").
There is still one "null aware index" expression, it might contain two literal tokens (or maybe only one if it's not null-aware).

**Comment by bwilkerson** [comment]
Our AST has a separate field for each token, so this will require us to store two tokens where we used to store one. Not ideal, but we can live with it.

**Comment by jensjoha** [comment]
Parser support has landed with cf4e044e07313e2c7f6d65202296c6adb1c5dc4d. Analyzer needs to be updated though. I'm hoping that @bwilkerson or someone on the analyzer team can do that?

**Comment by jensjoha** [comment]
Had to revert...

**Comment by jensjoha** [comment]
Landed as 3660b9ecc70e9e5ec3b5fce24485dff0687fb099.

**Comment by scheglov** [comment]
Do we have now both `?.[` and `?[`?
Or the first can be removed from tests and implementations?

**Comment by eernstg** [comment]
Only the form with no period is supported, so tests and implementations for that can be removed.

**Comment by jensjoha** [comment]
Unless we have tests for both versions, the tests should be rewritten, right?

**Comment by eernstg** [comment]
Certainly, tests for `?.[` would be an obvious source for corresponding `?[` tests, so 'rewrite to use `?[` unless the resulting test exists already' is a better rule than 'remove'. Thanks.

**Comment by leafpetersen** [comment]
https://dart-review.googlesource.com/c/sdk/+/138721 to update language tests, filed https://github.com/dart-lang/co19/issues/538 for co19 tests.

**Comment by scheglov** [comment]
@jensjoha I see a parser error in this code:
```dart
class A {
  int operator[](int index) => throw 0;
}

void f(A? a) {
  a?[0] + 1;
}
```
I get:
```
error: Expected an identifier. (missing_identifier at [test] bin/test2.dart:6)
error: Expected to find ';'. (expected_token at [test] bin/test2.dart:6)
```

**Comment by vsmenon** [comment]
If the SDK isn't using this ( @lrhn @leafpetersen ?) - I think we can push this past unfork.

**Comment by leafpetersen** [comment]
I'm also seeing parse errors on `x?[i]++` and `++x?[i]`.
