### ISSUE TITLE
Consider a hint for implementers of type Function

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#40284]
Open question.

Should we have a hint that A does not implement `call()`?

```dart
class A implements Function {
  
}
```

**Comment by lrhn** [comment]
How about a hint that it doesn't implement `Function` either? :smile:

Since Dart 2.0, you cannot implement `Function`. We allow you to write `implements Function`, but it is ignored.

Someone trying to do so should be hinted towards removing the `implements Function` and possibly add a `call` method.

**Comment by srawlins** [comment]
This is done.
