### ISSUE TITLE
Analyzer issues incorrect error when overriding a method with a default parameter in a legacy library

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40304]
The analyzer (bleeding edge) is issuing an error on the override of `foo` in the code below:

```  warning • Parameters can't override default values, this method overrides 'A.foo' where this positional parameter has a different value. • acx-2020-examples-opted-out.dart:6:13 • invalid_override_different_default_values_positional
```

opted_in.dart
```dart
// opted in
class A {
  void foo([int x = 3]) {}
}
```
```dart
// @dart = 2.7
import "opted_in.dart";

class B extends A {
  void foo([int x = 3]) {}
}
```

cc @scheglov @stereotype441

**Comment by scheglov** [comment]
This is probably caused by https://dart-review.googlesource.com/c/sdk/+/132802.

We don't implement [Runtime type equality operator](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-type-equality-operator) yet. The type of `3` in `A.foo()` is `int`, and the type of `3` in `B.foo()` is `int*`, which are not equal as is (and we don't implement the "ignoring * modifiers on types" rule).

**Comment by scheglov** [comment]
Does the [runtime type equality rule](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-type-equality-operator) replace the existing runtime type equality rule? I.e. no matter whether we compute the constant in a legacy or NNBD library, or compare constant values because we are checking that a default value in a legacy library is identical to the default value in the overridden member.

**Comment by leafpetersen** [comment]
> Does the [runtime type equality rule](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-type-equality-operator) replace the existing runtime type equality rule? I.e. no matter whether we compute the constant in a legacy or NNBD library, or compare constant values because we are checking that a default value in a legacy library is identical to the default value in the overridden member.

Yes.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/134221
