### ISSUE TITLE
Extension losing type information

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40302]
I don't know what is happening, but I jsut can't make this code work. Tried different things but the type `R` is always lost on the exampel below:

```dart
extension IterableX<L extends Iterable<R>, R> on Iterable<L> {
  Iterable<R> flat<L>() sync* {
    for (var current in this) {
      yield* current as Iterable<R>;
    }
  }
}

void main(List<String> arguments) async {
  var theList = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ];

  var shouldBeAListOfInts = theList.flat().toList();

  print(shouldBeAListOfInts.runtimeType); //prints List<dynamic>
}

```

Is this a bug or intended behavior?

**Comment by tatumizer** [comment]
Maybe this is what you are looking for?
```
extension IterableX<R> on Iterable<Iterable<R>> {
  Iterable<R> flat() sync* {
    for (var current in this) {
      yield* current;
    }
  }
}
```

**Comment by lrhn** [comment]
Yes, working as intended.

Your code does not mean what you probably expect it to mean.
```dart
extension IterableX<L extends Iterable<R>, R> on Iterable<L> {
  Iterable<R> flat<L>() sync* {
    for (var current in this) {
      yield* current as Iterable<R>;
    }
  }
}
```
There are two bindings of `L` here, one in `IterableX<L ....>` and one in `flat<L>`. Those two are completely unrelated, they just happen to have the same name. So, you can remove the `<L>` from `flat` without affecting anything, since there is nothing referring to the `L` anywhere (its scope is the function, and the function does not mention `L`).

So, when you try to use the extension `IterableX<L extends Iterable<R>, R> on Iterable<L>` on an `Iterable<Iterable<int>>`, the same type argument inference happens as would for:
```dart
class IterableX<L extends Iterable<R>, R> {
   Iterable<L> _this;
   IterableX(this._this);
}
....  
  Iterable<Iterable<int>> data = ...;
  var ext = IterableX(data); // <-- type inference here
```
That type inference has a lot of options, and it chooses `R` to be `dyamic` and `L` to be `Iterable<int>`.
That is a valid solution satisfying that `L` is a subtype of `Itearable<R>`.

What you want is likely what @tatumizer wrote above.

**Comment by shinayser** [comment]
> Yes, working as intended.
> 
> Your code does not mean what you probably expect it to mean.
> 
> ```dart
> extension IterableX<L extends Iterable<R>, R> on Iterable<L> {
>   Iterable<R> flat<L>() sync* {
>     for (var current in this) {
>       yield* current as Iterable<R>;
>     }
>   }
> }
> ```
> 
> There are two bindings of `L` here, one in `IterableX<L ....>` and one in `flat<L>`. Those two are completely unrelated, they just happen to have the same name. So, you can remove the `<L>` from `flat` without affecting anything, since there is nothing referring to the `L` anywhere (its scope is the function, and the function does not mention `L`).
> 
> So, when you try to use the extension `IterableX<L extends Iterable<R>, R> on Iterable<L>` on an `Iterable<Iterable<int>>`, the same type argument inference happens as would for:
> 
> ```dart
> class IterableX<L extends Iterable<R>, R> {
>    Iterable<L> _this;
>    IterableX(this._this);
> }
> ....  
>   Iterable<Iterable<int>> data = ...;
>   var ext = IterableX(data); // <-- type inference here
> ```
> 
> That type inference has a lot of options, and it chooses `R` to be `dyamic` and `L` to be `Iterable<int>`.
> That is a valid solution satisfying that `L` is a subtype of `Itearable<R>`.
> There is no upper bound on `R` and it does not appear in the `on` expression at all, so it becomes very hard to constrain it.
> 
> What you want is likely what @tatumizer wrote above.

Thank you for your comment Irhn, it was very clarifying :)
