### ISSUE TITLE
"textDocument/completion" answer items not alphabetically sorted

### ISSUE THREAD

**Issue by jonas-jonas** [dart-lang/sdk#40346]
In Dartboard we noticed that `textDocument/completion` items are not alphabetically sorted, which makes it hard to predict for the user. In VSCode these entries seem to be sorted on the client? What is this sorting based on? Is it just the default behavior, or is there some way to determine how a response's items should be sorted in the LSP?

**Comment by natebosch** [comment]
The spec does not require the server to send items in any particular order. The client can choose to sort in whatever way makes sense. Alpha sorting on `sortText` (if present), and falling back on alpha sorting the `label` is probably common. Clients may also choose to sort `deprecated` suggestions lower. Clients may also choose to allow some sorting based on either prefix or fuzzy matching of characters the user has already typed.

See the spec at https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

Closing this issue for now since I don't think we plan on adding server side sorting.

**Comment by bwilkerson** [comment]
> I don't think we plan on adding server side sorting.

We might want to re-think that. Server already computes relevance information, and it seems a shame to not share that with LSP clients.

**Comment by vogella** [comment]
Would be great to receive server sorted proposals so that clients don't
have to implement language specific sorting. At least lsp4e currently
assumes that the server proposals are ranked already based on relevance and
this seems the best place to do this decision.

Brian Wilkerson <notifications@github.com> schrieb am Mi., 29. Jan. 2020,
20:02:

**Comment by bwilkerson** [comment]
It seems like it would be fairly easy to sort before returning the items. It looks like LSP also defines a `sortText` to allow clients to sort items. I'm not sure what the best approach would be.

@DanTup In case you have ideas.

**Comment by DanTup** [comment]
We are already sorting (via `sortText`), but it's deliberately not alphabetical, it's based on the `relevance` calculated by the server (we have to convert the numeric value to a strong since LSP is text-based sorting):

https://github.com/dart-lang/sdk/blob/91d6e1a0a712a308521893784d858b322bb59e86/pkg/analysis_server/lib/src/lsp/mapping.dart#L241

I think this is the correct thing to do - it will put the most relevant things at the top (mostly - we do still have https://github.com/dart-lang/sdk/issues/38739).

I don't think we should spend resources sorting the collection though as the client *should* always be sorting based on `sortText` (if it's not set, it should fall back to `label` - so I don't think a client would/should ever *not* sort).

As for VS Code, it will use the order we provide it initially, but as soon as the user types any characters (such that the results are filtered client-side), it will take over sorting using its own relevance calculations (something I think is bad in some ways - it has no language context - but good in others - since the server only got to provide the order for the full unfiltered list).

@jonas-jonas does this seem to match what you're seeing?

**Comment by DanTup** [comment]
I believe there's nothing to do here - we provide `sortText` that's sorted by our relevance. Clients can use this, or implement their own sorting (VS Code uses our sort initially, but then does its own relevance ranking as the user types more characters, since it doesn't go back to the server for updated relevance).

Unless anyone thinks this is incorrect, I think we can probably close this? (I don't have permission to do so though).

**Comment by bwilkerson** [comment]
I agree. Happy to re-open if more discussion is needed.
