### ISSUE TITLE
addAll on Uint8List never returns

### ISSUE THREAD

**Issue by timosturm** [dart-lang/sdk#40401]
* Dart SDK Version 2.7.0 via flutter --version
* OS: Ubuntu

I try to concatenate two Uint8Lists (see example A), but the call does not seem to return at any point as the `print` method never shows on the console. If I change the lists `a` and `b` and `c` to `List<int>` the call works as expected (see example B). The [documentation](https://api.dart.dev/stable/2.7.1/dart-typed_data/Uint8List-class.html) states that `Uint8List` is 'a fixed-length list of 8-bit unsigned integers.' The documentation on `addAll` says 

```
/**
   * Appends all objects of [iterable] to the end of this list.
   *
   * Extends the length of the list by the number of objects in [iterable].
   * Throws an [UnsupportedError] if this list is fixed-length.
   */
```

So the expected behavior is that either `addAll` actually adds one list to another, or that it throws an exception.

Example A:

``` 
      Uint8List a = Uint8List.fromList([1, 2, 3, 4, 5, 6]);
      Uint8List b = Uint8List.fromList([7, 8, 9, 10, 11, 12]);

      Uint8List c = a + b;
      // Same with:
      // UintList c = Uint8List(0);
      // c.addAll(a); 
      // c.addAll(b);

      print('Added a + b');
```

Example B:

``` 
      List<int> a = [1, 2, 3, 4, 5, 6];
      List<int> b = [7, 8, 9, 10, 11, 12];

      List<int> c = a + b;

      print('Added a + b');
```

**Comment by lrhn** [comment]
I cannot reproduce this on the Dart bleeding edge repository.

Adding two `Uint8List`s creates a *normal* growable list, not a `Uint8List` again. That means that I get an error on the `Uint8List c = a + b;` line because the value is not a `Uint8List`. 

Adding to a `Uint8List` using `addAll` throws an `UnsupportedError` because it is a fixed length list.

That is, both examples *throw*. Maybe your code, or the way you run it, is swallowing the error being thrown here.

**Comment by timosturm** [comment]
It was indeed a problem with how I ran the code as the exception was catched by a library function.
