### ISSUE TITLE
Make `createSync` method from File class return the created file

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#40445]
The current implementation of `File.createSync` cannot be idiomatic. Currently it is like:

Current:
```dart
var file = File("photo.jpg");
  file.createSync(recursive: true);
  file.writeAsBytes(bytes);
```

My proposal:
```dart
await File("photo.jpg").createSync(recursive: true).writeAsBytes(bytes);
```

I know that we have the `create` async  method, but it requires a lambda passing, like:
```dart
  await File("photo.jpg")
      .create(recursive: true)
      .then((it) => it.writeAsBytes(bytes));
```
But it is also less idiomatic than the above proposal. 
Also, there is any true reason for the `createSync` method to return void?

**Comment by lrhn** [comment]
Dart libraries do not generally return the receiver object. That is usually done in other languages in order to allow "fluent" style code like what you are writing above.
Dart doesn't do that because we have cascade syntax instead.

Your code can be written as:
```dart
await (File("photo.jpg")..createSync(recursive: true))..writeAsBytes(bytes);
```
or 
```dart
var file = File("photo.jpg")..createSync(recursive: true);
await file.writeAsBytes(bytes);
```

The is nothing corresponding to that for the async `create`, sadly, which is probably why that call returns the file. We'd need a suffix `await`, maybe something like 
````dart
/// NOT VALID SYNTAX (yet?)
File("photo.jpg")..create(recursive: true).await..writeAsBytes(bytes).await;
```

**Comment by sortie** [comment]
Thanks your suggestion on how to improve the Dart APIs. Lasse has suggestions on how to use the cascade syntax for this purpose.

Changing the return type of `File.createSync` would be a [breaking change](https://github.com/dart-lang/sdk/blob/master/docs/process/breaking-changes.md). I don't think being consistent with `File.create` or a supposed increase in usability are worthwhile enough to justify a breaking change. For that reason, I don't intend to make this change and I'm closing the bug.

**Comment by shinayser** [comment]
Thank your explanation!
