### ISSUE TITLE
Failures on [tests] Create `null is T` tests in legacy and null safe libraries.

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#40451]
There are new test failures on [[tests] Create `null is T` tests in legacy and null safe libraries.](https://github.com/dart-lang/sdk/commit/703bc0086de16ab7d645c3ef0f080520dad07f99).

The tests
```
language/nnbd/is_type_test/null_is_type_in_legacy_lib_test RuntimeError (expected Pass)
language/nnbd/is_type_test/null_is_type_in_null_safe_lib_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```
-----

These are new tests, which were tested on NNBD dart2js and NNBD ddc but not NNBD dart VM before submitting to the queue. Approving temporarily to make the bot green again, but they should be fixed ASAP (or we should figure out why they can't be fixed if so).

**Comment by sstrickl** [comment]
Just a note, changing the `value is T` to `(value as T) is T` in 

`tests/language/nnbd/is_type_test/legacy_library.dart`:
```dart
bool legacyIs<T>(Object value) => value is T;
```
`tests/language/nnbd/is_type_test/null_safe_library.dart`:
```dart
bool nullSafeIs<T>(Object? value) => value is T;
```

does not result in a casting error, but still results in the `is` operator returning `false`.

**Comment by crelier** [comment]
Note that this test is outdated, because the spec has been changed and the opted-in or legacy mode of the library makes no difference in 'null is T' anymore.
However, this issue is real and the VM should not fail. It looks like a type argument is not properly instantiated to a nullable type and remains legacy.
I'll dig further.
/cc @alexmarkov

**Comment by alexmarkov** [comment]
I think the test is correct: in the case which fails on the VM it is testing `null is T*` where `T = int?`, so it should be true.

**Comment by crelier** [comment]
Yes, the test is correct. There is nothing wrong with checking that the result in opted-in and in legacy libraries is the same, as stated by the language spec. I wrongly assumed that the test predated the spec change (when the result was specified to differ) and was later updated, but that is apparently not the case.

Regarding the VM issue, it could be caused by an optimization that copies the type argument T to the generic function call, instead of performing a proper instantiation that sets the correct nullability on the instantiated type. In any case, we should double-check the implementation of generic function calls, especially how type arguments get instantiated prior to be pushed on the stack.
