### ISSUE TITLE
Error: The implementation of 'toString' in the non-abstract class 'TypeBuilder' does not conform to its interface.

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#40460]
Patching in this CL https://dart-review.googlesource.com/c/sdk/+/134112 and trying to build a full SDK produces errors:

```
Command failed: /b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/dart --depfile=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/gen/utils/pub/pub.dart.dill.d --depfile_output_filename=gen/utils/pub/pub.dart.dill --dfe=/b/s/w/ir/cache/builder/sdk/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /b/s/w/ir/cache/builder/sdk/pkg/vm/bin/gen_kernel.dart --packages=/b/s/w/ir/cache/builder/sdk/.packages --platform=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64NNBD/gen/utils/pub/pub.dart.dill /b/s/w/ir/cache/builder/sdk/third_party/pkg/pub/bin/pub.dart
output: ../../pkg/analyzer/lib/src/summary2/type_builder.dart:9:16: Error: The implementation of 'toString' in the non-abstract class 'TypeBuilder' does not conform to its interface.
abstract class TypeBuilder implements TypeImpl {
               ^^^^^^^^^^^
org-dartlang-sdk:///sdk_nnbd/lib/_internal/vm/lib/object_patch.dart:43:10: Context: The method 'Object.toString' has fewer named arguments than those of overridden method 'TypeImpl.toString'.
  String toString() native "Object_toString";
         ^
../../pkg/analyzer/lib/src/dart/element/type.dart:1959:10: Context: This is the overridden method ('toString').
  String toString({bool withNullability = false}) {
         ^
```
tools/build.py --nnbd create_sdk after patching that CL should produce the error.

**Comment by a-siva** [comment]
Made it a P0 as we are blocked from landing the CL which will help us make progress on getting legacy tests running on the NNBD sdk

**Comment by stereotype441** [comment]
After further inspection @scheglov and I realized this error is coming from the CFE while it's *compiling* the analyzer.  So I believe it's a CFE bug, not an analyzer bug.  Reclassifying.

**Comment by stereotype441** [comment]
Quoting Siva's email:
> The error is coming from CFE but I am wondering if it needs a fix in the analyzer source, the error seems valid to me.

The code in question looks like this:
```dart
abstract class TypeBuilder implements TypeImpl {
  DartType build();

  @override
  noSuchMethod(Invocation invocation) {
    return super.noSuchMethod(invocation);
  }
}
```
And the problematic method is this one:
```dart
abstract class TypeImpl implements DartType {
  @override
  String toString({bool withNullability = false}) {
    return getDisplayString(withNullability: withNullability);
  }
```

It seems to me that there should be no error here; a call to `toString` that passes in a value for `withNullability` should redirect to `TypeBuilder.noSuchMethod`.  Also, this code is currently considered valid by both the CFE and the analyzer.  And what's happening here doesn't have anything to do with NNBD, so I don't see a reason why enabling NNBD should have an effect on it.  That's why I'm inclined to suspect a CFE bug.

Can someone on the language team comment on whether or not a static error should be reported for the code above?  @leafpetersen @lrhn @eernstg 

(Note that if we determine that the CFE is correct in reporting a static error, then we should investigate why the CFE isn't reporting the error when NNBD is disabled.  And why the analyzer isn't reporting an error).

**Comment by bwilkerson** [comment]
It seems to me that the presence of a `noSuchMethod` method shouldn't make a difference in terms of whether a diagnostic is produced. So I tried an experiment with, I think, the same structure of classes, but one that uses `m` in place of `toString` and `A` in place of `Object`:
```
class A {
  void m() {}
}

class B extends A {
  void m({int x}) {}
}

class C extends A implements B {
  void m() {}

  @override
  noSuchMethod(Invocation invocation) {
    return super.noSuchMethod(invocation);
  }
}
```
Analyzer produces an invalid override diagnostic on the method `m` in `C` (without enabling NNBD). I think this is valid, and am wondering whether the fact that the method is defined in `Object` or is named `toString` is causing the special behavior here.

**Comment by scheglov** [comment]
One detail here is that the class with `noSuchMethod` is abstract, and concrete subclasses do have valid overrides.

**Comment by bwilkerson** [comment]
Good catch! I missed that. (The example I gave also should not have had a declaration of `m` in `C`, but removing it only changes where the error was reported.)

I agree that this means that there should be no diagnostic about invalid overrides because it's up to the subclasses to provide a valid override.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/134384 updates the analyzer so that it does not cause this `toString()` issue.

The build still fails though.
```
[2274/2316] ACTION //utils/compiler:dart2js(//build/toolchain/mac:clang_x64)
FAILED: gen/dart2js.dart.snapshot
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --snapshot=gen/dart2js.dart.snapshot --snapshot-depfile=/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/dart2js.dart.snapshot.d --snapshot-kind=app-jit /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart.dill --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --libraries-spec=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk_nnbd/lib/libraries.json --enable-experiment=non-nullable /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart
Command failed: ./dart --deterministic --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --snapshot=gen/dart2js.dart.snapshot --snapshot-depfile=/Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/dart2js.dart.snapshot.d --snapshot-kind=app-jit /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart.dill --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --libraries-spec=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk_nnbd/lib/libraries.json --enable-experiment=non-nullable /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseX64NNBD/gen/utils/compiler/dart2js.dart
output: The compiler crashed: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
#0      _BuildJsonListener.pushContainer (dart:convert-patch/convert_patch.dart:129:15)
#1      _BuildJsonListener.beginObject (dart:convert-patch/convert_patch.dart:156:5)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:860:20)
#3      _parseJson (dart:convert-patch/convert_patch.dart:30:10)
#4      JsonDecoder.convert (dart:convert/json.dart:498:36)
#5      JsonCodec.decode (dart:convert/json.dart:156:41)
#6      jsonDecode (dart:convert/json.dart:96:10)
#7      LibrariesSpecification.parse (package:front_end/src/base/libraries_specification.dart:126:22)
#8      getSupportedLibraryNames (package:front_end/src/api_unstable/dart2js.dart:223:33)
#9      CompilerImpl.setupSdk.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:74:36)
```

**Comment by a-siva** [comment]
The error you are seeing is a different problem, dart2js seems to fail with a compiler error when parsing the json file. I will create another issue for tracking this.

**Comment by a-siva** [comment]
Created https://github.com/dart-lang/sdk/issues/40463 to track the dart2js issue.

**Comment by a-siva** [comment]
With https://dart-review.googlesource.com/c/sdk/+/134384 landing bumping down to P1 as we now have a workaround.

**Comment by eernstg** [comment]
Cf. [this comment](https://github.com/dart-lang/sdk/issues/40460#issuecomment-582061703) from @stereotype441, we're looking at the following situation:

```dart
abstract class DartType {} // Does not declare a `toString`.
abstract class TypeImpl implements DartType {
  String toString({bool withNullability = false}) => getDisplayString(withNullability: withNullability);
}
abstract class TypeBuilder implements TypeImpl {
  DartType build();
  noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
```

There is no error here, but if `TypeBuilder` had been concrete then we would have [this error](https://github.com/dart-lang/language/blob/a8d0c9d9be0a0e8f2ad2ebd21952a596f3dbcac8/specification/dartLangSpec.tex#L2452).

The example in the language specification (immediately after the error text mentioned above) is quite similar in nature to the situation we have here, except that it uses a positional rather than a named optional argument.

We decided that a noSuchMethod forwarder should _not_ be generated when it would override a human-written method implementation, because that would silently turn a compile-time error about "inherited method does not correctly override the member signature from superinterfaces" into a run-time failure.

So just like any other abstract class, `TypeBuilder` is allowed to promise that it has a `String toString({bool withNullability})` even though it doesn't yet have it, but we won't fulfill that promise by generating a noSuchMethod forwarder in any concrete class, e.g., subclasses of `TypeBuilder`.
