### ISSUE TITLE
nnbd: Iterable.fold type deduction doesn't work

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#40470]
The type deduction for `Iterable.fold` doesn't work under NNBD for the following program:

```dart
main() {
  final buffer = ["a", "b", "c"]
      .fold(new StringBuffer(), (buffer, string) => buffer..write(string));
  buffer.write("d");
  print(buffer.toString());
}
```

It produces the following analyzer errors:

```
$ out/ReleaseX64/dart-sdk/bin/dartanalyzer --dart-sdk=out/ReleaseX64NNBD/dart-sdk --enable-experiment=non-nullable test.dart
Analyzing test.dart...
  error • The expression is nullable and must be null-checked before it can be used. • test.dart:3:54 • unchecked_use_of_nullable_value
  error • The method 'write' isn't defined for the type 'Object'. • test.dart:3:63 • undefined_method
  error • The expression is nullable and must be null-checked before it can be used. • test.dart:4:3 • unchecked_use_of_nullable_value
  error • The method 'write' isn't defined for the type 'Object'. • test.dart:4:11 • undefined_method
4 errors found.
```

However it works without NNBD:

```
$ out/ReleaseX64/dart-sdk/bin/dartanalyzer test.dart
Analyzing test.dart...
No issues found!
```

The issue occurs for me at 12b5e230847e791c2fc1987e4f49683edb0a5062.

This issue has come up a number of times when migrating the dart:io tests and also now appears in dart:io itself under NNBD, it seems to be a recent regression. Currently I work around it by providing the generic type manually:

```dart
main() {
  final buffer = ["a", "b", "c"].fold<StringBuffer>(
      new StringBuffer(), (buffer, string) => buffer..write(string));
  buffer.write("d");
  print(buffer.toString());
}
```

Therefore this issue is not blocking me but it is an annoyance I can work around reasonably.

**Comment by stereotype441** [comment]
This is, as I understand it, a deliberate decision on the part of the language team.  Prior to NNBD, the type parameter to `fold` was inferred as `dynamic`, which meant that `buffer..write(string)` was getting no type checking at all.  You can see this with the following sample program (which is accepted by both the analyzer and the CFE prior to NNBD):
```dart
test(bool b) {
  if (b) {
    final buffer = ["a", "b", "c"].fold(
      new StringBuffer(), (buffer, string) => buffer..oops(string));
  }
}
main() {
  test(false);
}
```
This is an unfortunate loophole in the typesystem that many users didn't realize existed.  As I understand it, the language team felt that since NNBD is a breaking change, it would be a good time to close this loophole.  So with NNBD enabled, the type argument gets inferred as `Object?`, and since `Object?` doesn't define a `write` method, you're seeing a static error.

Language team, please correct me if I'm wrong.  @leafpetersen @lrhn @eernstg 
Reassigning to area-language.

**Comment by sortie** [comment]
Thanks for the explanation. I confirmed it with the language team. I'll migrate the code by adding the types to the fold generic. Closing.
