### ISSUE TITLE
CFE inferring wrong type for constant list when nnbd=weak

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/sdk#40480]
Test:
co19_2/Language/Expressions/Lists/identical_t01

Repro:
```dart
 // @dart = 2.6
  
main() {
    var l1 = const [1 + 1, 2 * 2, 3 ~/ 3];
    var l2 = const [2, 4, 1];
    // Expect.isTrue(identical(l1, l2));
}
```

Dill(note core::int vs core:int*):
```
main = leg::main;
library from "file:///home/joshualitt/src/legacy.dart" as leg {

  static method main() → dynamic {
    core::List<core::int>* l1 = #C4;
    core::List<core::int*>* l2 = #C5;
    // ...
  }
}
```

**Comment by vsmenon** [comment]
Interesting example - are these lists supposed to be identical regardless of the difference in `*`s?  @sigmundch @fishythefish

**Comment by fishythefish** [comment]
Yeah, as far as I can tell. The spec says that two constant list literals are identical iff, after evaluating them, they are element-wise identical and their actual type arguments are equal (`==`). Since `*` is purely an internal notion, we erase all `*`s before comparing the types, so we're really checking `List<int> == List<int>`.

**Comment by vsmenon** [comment]
fyi - @johnniwinther @lrhn 

ddc is also returning false on `identical` in the commented out part of the original snippet because the object (and underlying reified type) are different. 

If these two lists were coming from different libraries with the above types, should they canonicalize to the same object?  And, if so, which type - legacy, no legacy?

**Comment by joshualitt** [comment]
Rerunning on TOT, I think this particular issue appears to be fixed. However, I think vsmenon's question may still apply.

**Comment by vsmenon** [comment]
@joshualitt - can you clarify?  is the dill now showing the same type?

**Comment by sigmundch** [comment]
I haven't verified this, but note that Johnni landed a change to implement weak semantics in constants in https://dart-review.googlesource.com/c/sdk/+/134284 earlier this morning. It's possible the change addressed most of these issues.

**Comment by johnniwinther** [comment]
This was fixed by https://dart-review.googlesource.com/c/sdk/+/134284.
