### ISSUE TITLE
the test to validate that the nnbd preview web tool has been rebuilt is failing

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#40505]
This is `pkg/analysis_server/tool/nnbd_migration/check_generated_test`.

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8889168900468379264/+/steps/test_results/0/logs/new_test_failures__logs_/0

Disabling the test for now and tracking re-enabling it in this bug.

**Comment by stereotype441** [comment]
I suspect this is happening because the code in `pkg/analysis_server/tool/nnbd_migration/generate_resources.dart` behaves differently depending on the order in which files are returned by Directory.listSync.  In particular, it forms an MD5 of the source files by concatenating the contents of Dart files in the directory `pkg/analysis_server/lib/src/edit/nnbd_migration/web`.  Directory listing order isn't even stable on a single OS (on Linux, it depends on the order in which files were created, IIRC), much less across OSes, so we need to do something smarter.

I'm exeperimenting with a fix in https://dart-review.googlesource.com/c/sdk/+/138060.

**Comment by devoncarew** [comment]
Ah, makes sense. I believe that macos lists files in lexical order, which is why I saw the order being stable locally.
