### ISSUE TITLE
NNBD: Dart allows named function argument of non-nullable type without default value

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40514]
Dart VM version: 2.8.0-edge.aadcb4418b1a7ccbb74a7cc925ad55020ce4a924 (Thu Feb 6 02:00:49 2020 +0000) on "linux_x64"

The following source code throws a compile error with analyzer and passes with dart:
```
class B {
  void test_nondefault({int i})     {}
}

main() {}
```
Seems like compile error should be thrown with dart too.

Sample output is:

> $  dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error • The parameter 'i' can't have a value of 'null' because of its type, so it must either be a required parameter or have a default value. • test.dart:2:29 • missing_default_value_for_parameter
> 1 error found.
> $  dart --enable-experiment=non-nullable test.dart
>$

**Comment by johnniwinther** [comment]
The CFE currently only produces nnbd-specific warnings and error behind a special `--force-nnbd-checks' flag.

To check `foo.dart` in weak mode run:
```
dart pkg/front_end/tool/fasta.dart compile --enable-experiment=non-nullable --force-nnbd-checks foo.dart
``` 
and to check `foo.dart` in strong mode run:
```
dart pkg/front_end/tool/fasta.dart compile --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong foo.dart
```
where `pkg/front_end/tool/fasta.dart` is in the Dart repo.

This generates a `foo.dart.dill` file next to `foo.dart` which can be run with the VM using
```
dart foo.dart.dill
```

The flag will be removed once it is not blocking development on the nnbd sdk due to false positives.

**Comment by stefantsov** [comment]
Closing the issue, as the check is implemented under `--force-nnbd-checks` flag.
