### ISSUE TITLE
About the assignment of private member variables 

### ISSUE THREAD

**Issue by toop** [dart-lang/sdk#40523]
I very like the Dart lang!
But the assignment of private member variables of the class is restricted  to the current file, it's strange. Strongly recommended to restrict it to the current class !!!

**Comment by lrhn** [comment]
Dart currently only has library-private declarations. The idea is that you can trust the current library because you are writing it yourself, and if you want a stricter access, you can create a library with just the one class, then only that class can see its own private variables. As such, it's *adequate* as a containment mechanism.

We are considering whether there are access patterns with stronger protections that we can allow in some situations, fx in https://github.com/dart-lang/language/issues/757.

**Comment by toop** [comment]
Thank you very much for your reply! Restrict to the current object, may be are access patterns with stronger protections  !!!

**Comment by vsmenon** [comment]
Thanks for the issue.  Closing this in favor of dart-lang/language#757

**Comment by toop** [comment]
Strongly recommended that private property assignments should be restrict to the current class by default！！！@vsmenon @irhn
