### ISSUE TITLE
Prevent reference cycles in RTI for objects passed to JS

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#40535]
See https://github.com/flutter/devtools/issues/1610#issuecomment-583636081

Some potential options:

- Use a non-iterated symbol/property on the object.
- Get rid of cycles in the representation.

Options that I think are unlikely to work:

- Strip the information at the boundary of JS. Too expensive and could impact behavior on the Dart side.

**Comment by fishythefish** [comment]
What kind of guarantees do we make when it comes to the properties we add to objects in order to implement the runtime? Clearly, we must not create cycles.

Is it sufficient to make the keys non-enumerable, or is `Object.getOwnPropertyNames()` a concern? We can't use `Symbol` keys until we deprecate IE11 and support ES6, so we could instead hide the cyclic references behind a `WeakMap`.

/cc @sigmundch

**Comment by natebosch** [comment]
> Is it sufficient to make the keys non-enumerable, or is Object.getOwnPropertyNames() a concern?

I _suspect_ it would be sufficient to be non-enumerable, but I'm not confident that there won't be a use case for `getOwnPropertyNames()`. We don't, generally, promise any specifics for what an Object instantiated in Dart looks like in JS so it's probably OK for it to be visible if you really hunt for it. The main thing is being able to pass things like a `List` into JS safely.

**Comment by fishythefish** [comment]
Actually, we probably shouldn't allocate a `WeakMap` for every `Rti`. We can continue storing `Rti`s as fields on `_Type`s, but the back-reference from the `Rti` to the `_Type` can be stored in a cache on the universe instead of on the `Rti` itself.

**Comment by sigmundch** [comment]
Was the old RTI also storing types as enumerable properties? If so, it seems OK to start with a quick fix that removes the cycles. If however this is a new problem because we the new-rti is using enumerable properties and we weren't before, then I'd be inclined to use non-enumerable properties instead. 

It might not be the case for that library used by devtools, but I wouldn't be surprised if other tools ran into issues because of the additional properties we inject, so after the quick fix, it might not be a bad idea to move towards non-enumerable properties in the end (or symbols once we can adopt them)

**Comment by fishythefish** [comment]
The old implementation wasn't storing types (that is, `TypeImpl`s) at all - we kept creating them on demand, even if we repeatedly passed the same `rti`. With the new implementation, `_Type` has an `Rti` field just as it did before, but the `Rti` also points back to the (cached) `_Type` so we don't recompute it unnecessarily.

**Comment by rakudrama** [comment]
`_Rti` and `_Type` are just two Dart classes that point at each other.
This is no different to double-linked-list nodes.
JavaScript code could also legitimately create objects with cycles.
`JSON.stringify(x)` will fail for all these legitimate cases.
I think this is a tooling issue and not something for dart2js to 'solve'.

**Comment by sigmundch** [comment]
The underlying issue was fixed with https://github.com/dart-lang/sdk/commit/8ae984c54ab36a05422af6f250dbaa7da70fc461

**Comment by DaveShuckerow** [comment]
@rakudrama Based on our discussion, it looks like the fix doesn't work for the case of js interop with plotly.js.  We were able to produce this issue in DevTools with the new fixed RTI.

**Comment by DaveShuckerow** [comment]
The plotly.js package is traversing symbols as well as object.keys.

**Comment by rakudrama** [comment]
@DaveShuckerow can you point me at the code where plotly.js does this?

**Comment by DaveShuckerow** [comment]
> @DaveShuckerow can you point me at the code where plotly.js does this?

As far as I know, the only object recursing logic in plotly that we're exercising is what's detailed here: https://github.com/flutter/devtools/issues/1610#issuecomment-588028260

**Comment by rakudrama** [comment]
It is fixed, there was an error in the js-interop code: https://github.com/flutter/devtools/pull/1791
