### ISSUE TITLE
`call` extension method passes analyzer but fails webdev compile with "Error: 'X' isn't a function or method and can't be invoked." when using call operator on field

### ISSUE THREAD

**Issue by alechenninger** [dart-lang/sdk#40596]
See dartpad gist: https://dartpad.dev/77e0390e003bf936c4ca0b82664ded0b
At time of writing, this is running on 2.7.1

```dart
import 'dart:async';

void main() {
  var ctl = StreamController<String>();
  ctl.stream((s) {
    print(s);
  });
}

extension TerseListen<T> on Stream<T> {
  StreamSubscription<T> call(Function onData) {
    return listen((d) {
      onData(d);
    });
  }
}
```

```
Error compiling to JavaScript:
main.dart:5:7:
Error: 'stream' isn't a function or method and can't be invoked.
  ctl.stream((s) {
      ^
Error: Compilation failed.
```

Interestingly, using `call` as an extension method does work on other simple cases. I haven't been able to figure out what makes Stream special. For example below works

```dart
void main() {
  var t = Test();
  t();
}

class Test {}

extension TestExt on Test {
  void call() {
    print('foo');
  }
}
```

---

EDIT:

Based on comments I think you guys probably already figured this out, but I tried another variant that does work:

```dart
import 'dart:async';

void main() {
  var ctl = StreamController<String>();
  var str = ctl.stream;
  str((s) {
    print(s);
  });
}

extension TerseListen<T> on Stream<T> {
  StreamSubscription<T> call(Function onData) {
    return listen((d) {
      onData(d);
    });
  }
}
```

...so looks like it's the field/getter that's confuses webdev?

**Comment by vsmenon** [comment]
@eernstg @lrhn - what's the right behavior here?

**Comment by eernstg** [comment]
Invocation syntax (like `o(f)`) on an object (here `o`) whose static type matches the `on` type of an extension that declares a `call` method [should invoke `call`](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#the-call-member).

But in this particular case we have the syntax `ctl.stream((s) {...})`, and that parses as `ctl` followed by two `<selector>`s, namely `stream` and `((s) {...})`.

The language specification [indicates](https://github.com/dart-lang/language/blob/52b92c3c71e80e5c17bc899dbedc18f5b3223ca9/specification/dartLangSpec.tex#L10736) that this syntax must be considered to be an instance method invocation, not a expression (`ctl.stream`) evaluating to a function object, which is then called with the given argument list.

So, to be safe, the desired invocation via `call` should be ensured by parenthesizing: `(ctl.stream)((s) {...})`.

However, the question remains whether there is some way to argue that the tools must discover the way over `call` even without the parentheses. It seems useful, since we'd replace an error by a meaningful behavior, so why shouldn't we just avoid reporting that error?

(...taking another look at the rules now... ;-)

**Comment by lrhn** [comment]
I would want this to work, and I think the specification says that it should.

More precisely, the design document for extension methods [says that it should work](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#the-call-member).

This is supported by the current language specification, under "unconditional ordinary method invocation" in the specification, which says:
```latex
If the getter lookup succeeded then invoke the getter $o.m$
and let $v_g$ be the returned object.
Then the value of $i$ is the value of

\code{$v_g$<$A_1, \ldots,\ A_r$>($a_1,\ \ldots,\ a_n,\ x_{n+1}$: $a_{n+1},\ \ldots,\ x_{n+k}$: $a_{n+k}$)}.
```
That is: The meaning of `ctl.stream(...)` is defined to be the value of `x(...)` where `x` is the value of `ctl.stream`, and the value of `x(...)` would invoke the extension method.

So, both sources agree, this is a bug in the implementation.

**Comment by eernstg** [comment]
As of https://github.com/dart-lang/language/commit/9c7279b5d78622adac91b34c9d43da33ce13a354, the language specification handles the case where `e.m(...)` finds that `e.m` is a getter that returns a callable object. This is already consistent with the specification of the dynamic semantics, and it is implemented by both the vm and dart2js and accepted as a valid construct by the analyzer, so there is no need to consider this to be a breaking change.

The ability to invoke an extension method named `call` based on the same syntax `e.m(...)` is then already covered by the [static extension method specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#the-call-member).
