### ISSUE TITLE
ListBase/ListMixin do not work well with null safety

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#40599]
The current implementation of `ListMxin` (and `ListBase`, which is just `ListMixin` as a class) allows a user to only implement get/set `length`, an the `[]` and `[]=` operators, and it then implements all other functionality in terms of these.

That means that it implements `add` by incrementing the length and then storing the value in the new slot.

That behavior does not work in general with the null-safe type system because you cannot increment the length of a list which has a non-nullable type.

That makes all existing uses of `ListMIxin` not implement that restriction. If they are trivially backed by a proper `List`, then the default implementation of `add` will throw, but such a class should be forwarding `add` and `addAll` to the underlying list anwyay.

It does mean that the current `ListMixin` is a *bad API*. It defines list operations in terms of operations that the list itself should not support.

The best solution would be to make `add` also abstract, and require all `List` implementations to implement `add` themselves in a way that doesn't rely on setting `length` directly.

Classes which are implemented using `ListMixin` and which cannot support non-nullable types may want to migrate by making everything explicitly nullable:
```dart
class MySillyList<T extends Object> extends ListMixin<T?> {
  int get length => ...;
  set length(int v) { ... }
  T? operator[](int index) => ...;
  operator[]=(int index, T? value) { ... }
}
```
That avoids anyone ever creating a `MySillyList` which is a list of non-nullable values.

**Comment by eernstg** [comment]
I guess nobody should rely on having the _type_ `ListMixin`? In that case it might be acceptable to handle this by adding a new `NonNullableListMixin` which doesn't implement `add` (and doesn't implement whatever else needed, due to nullability issues).

The users of `ListMixin` would then have the option to switch to the new `NonNullableListMixin`, and do the work to implement those extra methods.

If they don't switch then I suppose their custom lists will continue to work with nullable type arguments, and they will fail on invocations of `add` if instantiated with a non-nullable type argument, so they will behave similarly to a fixed-length list.

The breakage caused by this change is at least more _subtle_ than the breakage that would be caused by simply changing `ListMixin` to not implement those methods. ;-)
