### ISSUE TITLE
Multiply exported enum values are duplicated despite an import

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#40620]
Corresponding issue to https://github.com/Dart-Code/Dart-Code/issues/1835 for IDEA:

![image](https://user-images.githubusercontent.com/67586/74461370-470c8680-4e43-11ea-8c60-e19e6e44e443.png)

See also: https://github.com/dart-lang/sdk/issues/40216

**Comment by pq** [comment]
Hmmm, actually this is true for named constructors too:

![image](https://user-images.githubusercontent.com/67586/74461591-9c489800-4e43-11ea-8498-0a936dced25b.png)


/fyi @DanTup

**Comment by DanTup** [comment]
In VS Code, it seems the same fix for enum values handles this (since it only takes what is before the `.`): https://github.com/Dart-Code/Dart-Code/commit/ea7443dab3378a7a86b3bbe40db6843ab1d05ffd

**Comment by pq** [comment]
Yeah.  I was thinking it would.  The question is whether this should even be the client's responsibility.  On the surface, it feels like a server bug.

/cc @scheglov

**Comment by scheglov** [comment]
I think that the fix is the same as for top-level elements - if there is an import that provides this element, suggest only with this import. So, in this case - only with `a.dart`.

**Comment by pq** [comment]
I think that's right.  Thanks @scheglov!

**Comment by pq** [comment]
Incidentally, the client algorithm as implemented in `CompletionDriver` handles these cases correctly:

https://dart-review.googlesource.com/c/sdk/+/135721

@DanTup: you may be able to remove your work-around if you take a similar approach?

**Comment by DanTup** [comment]
Great! I'm trying to understand the difference in what we've done - I think it's that my list is built from `existingImports.elements.names` so I'm only getting the names (eg. of enums and classes), but you're building it from the completions (so you're getting the constructors and enum values individually). Does that sound corect?

**Comment by pq** [comment]
Sounds right @DanTup.

**Comment by DanTup** [comment]
Clearing out my inbox (!) and came to this. I re-read all this, but couldn't figure out how I could change VS Code. However, with the plan to move to LSP I don't think there's much value in removing the workaround, since that code will go away.

I checked LSP and we handle this slightly differently (no splitting strings on `.`, but instead we take the parent of the declaration if it's an enum constants or constructor):

https://github.com/dart-lang/sdk/blob/76d736e27b202160f54dedc01dad94e56b7a4862/pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart#L265-L272

If that logic seems sound, probably there's nothing to do here and we can close this. Otherwise, let me know and I'll fix LSP up and then we can close this.

**Comment by DanTup** [comment]
(@pq I think there's nothing to do here based on the above - we're close to switching VS Code to LSP by default.. I don't have close permissions though, so can you close this if you don't think there's anything outstanding? Thanks!)

**Comment by bwilkerson** [comment]
I'm going to assume that there's nothing left to do and close this.
