### ISSUE TITLE
[analysis_server] LSP test failing on adding extension with specific name

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#40636]
When I add an extension `DynamicLibraryExtension` to `dart:ffi` in the mock_sdk the test below starts failing. However, when the extension is named `LibraryExtension`, no issue at all.

Workaround: https://dart-review.googlesource.com/c/sdk/+/135463/8..9

Failure thrown in:

https://github.com/dart-lang/sdk/blob/edd64e6d5c7924a5fb1ef80c5226d24006e7977b/pkg/analysis_server/lib/src/lsp/lsp_analysis_server.dart#L288-L302

cc @DanTup 

Failure log:

```
/=========================================================================================================================================\
| analyzer-unittest-asserts-release-linux:pkg/analysis_server/test/lsp/workspace_symbols_test broke (Pass -> RuntimeError, expected Pass) |
\=========================================================================================================================================/

--- Command "vm" (took 33.000790s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/pkg/analysis_server/test/lsp/workspace_symbols_test.dart

exit code:
255

stdout:
[...]
00:02 [32m+3[0m[31m -1[0m: WorkspaceSymbolsTest | test_partialMatch [1m[31m[E][0m[0m
  {
      "code": -32001,
      "message": "An error occurred while handling workspace/symbol request"
  }
  pkg/analysis_server/test/lsp/server_abstract.dart 51:7        AbstractLspAnalysisServerTest.expectSuccessfulResponseTo
  ===== asynchronous gap ===========================

[...]

stderr:
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

--- Re-run this test:
python tools/test.py -n analyzer-unittest-asserts-release-linux pkg/analysis_server/test/lsp/workspace_symbols_test
```

Full log: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8888553385798619536/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by DanTup** [comment]
> However, when the extension is named `LibraryExtension`, no issue at all.

I was able to repro a crash where we could try to create SymbolInformation's without a Kind - however it happens in my testing for extensions *with* a name, since without a name the symbol is not included.

https://dart-review.googlesource.com/c/sdk/+/135902 fixes that, though I'm not sure if you're seeing something else.

**Comment by DanTup** [comment]
Sorry, I mis-read the original issue. This wasn't named vs unnamed, it was `DynamicLibraryExtension` vs `LibraryExtension`.

So it is the same issue (named extensions are causing issues). The reason it didn't show up without the word `Dynamic` is that the test was sending a query of `my` which matches `Dynamic` because we do a fuzzy match (`*m*y*`).

**Comment by dcharkes** [comment]
Thanks for the quick fix! =)

**Comment by DanTup** [comment]
There was another slight issue - there's an assert to catch when we don't map a kind, but it was firing on the bots (because they run with asserts enabled) when the underlying kind was `null`. I've tweaked the asserts (which are there to highlight when there's a kind that hasn't been mapped) to only fire for non-null kinds that aren't mapped too.

**Comment by DanTup** [comment]
@dcharkes the fix has been merged. Let me know if you hit any problems putting the name back as you had it (assuming you plan to).

Also, if the fix looks good please close this - I don't have the power here and forgot to include it in the commit message. Thanks!
