### ISSUE TITLE
possible inference issue in the CFE for closures under nnbd

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#40647]
Consider this program:

```dart
class A<T> {
  final T t;
  A(this.t);
  A<R> then<R>(R Function(T t) callback) => A(callback(t));
}

m1() {
  A<Null> a = A(null);
  a.then((_) => null);
}

m2() {
  A<int?> a = A(null);
  a.then((_) => null);
}

m3() {
  A<int> a = A(3);
  a.then((_) => null);
}

m4() {
  A<Never?> a = A(null);
  a.then((_) => null);
}
```

The output of fasta-compile shows that the type inferred for each of the closures is:
```
Null? Function(Object?)
Null? Function(int?)
Null? Function(int)
Null? Function(Never?)
```

I was curious, shouldn't all these be typed to return `Null` instead of `Null?`, also, should the first one be inferred to be `Null?` instead of `Object?`?

**Comment by stefantsov** [comment]
The answer for `Null` vs. `Null?` is that they are the same type for the CFE.  Currently `Null` is represented as an `InterfaceType`, and for all proper `InterfaceType`s their declared nullability is the same as the property having `null` as their element.  When printing out an `InterfaceType`, the textual printer simply puts the suffix of the nullability-as-property after the type.  That is why in the textual representation `Null` is always printed out as `Null?`: the same routine is used as for other `InterfaceType`s.  We have plans of introducing a specific representation for `Null`, so that it won't be encoded as `InterfaceType` anymore, and the textual output can be fixed with that.

**Comment by stefantsov** [comment]
As for having `Object?` vs. `Null?`, it's special-cased in the inference algorithm.  I was able to trace it back to the following issue: https://github.com/dart-lang/sdk/issues/31546.  It seems that the Analyzer and the CFE agree in that behavior.  I tried to run the following program through the Analyzer to test if it infers `Null`, and it seems to to be ok with the assignment, so it's definitely not `Null`.

```dart
class A<T> {
  final T t;
  A(this.t);
  A<R> then<R>(R Function(T t) callback) => A(callback(t));
}

m1() {
  A<Null> a = A(null);
  a.then((x) { x = 42; });
}
```
