### ISSUE TITLE
Dart analysis server should provide code completion to write method

### ISSUE THREAD

**Issue by vogella** [dart-lang/sdk#40680]
Would be nice to have the option to generate a method fitting to an attribute via code completion.

For example: in the screenshot placing the cursor after itemBuilder: and press Ctrl+Space only shows generic options.

Would be nice to allow to:

1.) Create a fitting method
2.) Generate a lambda expression with the expected parameters. 

![image](https://user-images.githubusercontent.com/139910/74831213-1467ff80-5315-11ea-86b5-bead7a7bfb4b.png)

I guess the sdk needs to do this so that @DanTup gets this in Dart code.

**Comment by bwilkerson** [comment]
Being able to complete with a closure of the appropriate form makes sense to me. I know that @pq was looking at this area recently, but I don't know whether this case has been fixed.

Creating a method seems outside the normal scope of code completion because it requires further user interaction (providing a name). That said, you could complete to a closure (when we have that) and then use the "Extract Method" refactoring to turn that closure into a method. You could also type the name of the method and use the "Create method" assist (although I just found a bug in the assist while making sure that was an option).

**Comment by vogella** [comment]
> Being able to complete with a closure of the appropriate form makes sense to me.

That would be the main request.

> Creating a method seems outside the normal scope of code completion

+1

**Comment by pq** [comment]
> Being able to complete with a closure of the appropriate form makes sense to me. 

In the latest SDK, we've got at least the start of that:

![image](https://user-images.githubusercontent.com/67586/74860345-571ddd80-52fd-11ea-89b9-ef607c42ac89.png)


@vogella: is this a step in the right direction?

**Comment by vogella** [comment]
@pq this is awesome. Which channel is this in? flutter channel dev?

**Comment by pq** [comment]
I believe it's in dev.  (It's definitely in tip of Flutter trunk.)

**Comment by vogella** [comment]
Don't see it after switching the channel

![image](https://user-images.githubusercontent.com/139910/74871504-e0fc9380-535b-11ea-8178-044207e9e12f.png)

**Comment by pq** [comment]
Ah, ok.  Sorry.  Looks like it's not there yet.  It should be in the next roll for sure.

**Comment by vogella** [comment]
Thanks. Looking forward to it

Phil Quitslund <notifications@github.com> schrieb am Mi., 19. Feb. 2020,
21:54:

**Comment by bwilkerson** [comment]
This appears to be working, so I'm going to close it.
