### ISSUE TITLE
Add InternetAddress.tryParse

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#40692]
The `InternetAddress` constructor will throw `ArgumentError` if the `String` argument is not a valid IPv4 or IPv6 address. I don't see an obvious utility to validate that a given String is in a valid format.

Similar to `int.tryParse` I think we should add `InternetAddress.tryParse(String)` which can return `null` instead of throwing on a bad format.

**Comment by lrhn** [comment]
The constructor throws `ArgumentError`, which causes people to try to catch `ArgumentError`, which is an anti-pattern.

A *proper* solution would be to add both a `parse` (throwing `FormatException` on error) and a `tryParse` (returning null on error), and then deprecate (and eventually remove) the constructor.

We probably can't just change the constructor to throw `FormatException` because there is code out there catching the `ArgumentError`. It would also be inconsistent to have constructor/`tryParse` instead of `parse`/`tryParse`.

So, a good long-term solution would be to add both `parse` and `tryParse`, and keeping the constructor, all sharing the same code with an abstracted error handling.

That is some work. Is it really *worth* it? I guess that depends on how many people actually need to parse internet addresses themselves, rather than just pass them to `lookup` as-is.

**Comment by natebosch** [comment]
> That is some work. Is it really _worth_ it? I guess that depends on how many people actually need to parse internet addresses themselves, rather than just pass them to `lookup` as-is.

I disagree that we necessarily need a `parse` in order to add a `tryParse`, however I don't believe it's too much work to have one or both added. https://dart-review.googlesource.com/c/sdk/+/136406

As I mention on the review, my focus isn't on how widespread the problem is, but how clear both the problem and the solution are. If the current API forces _any_ author to go against best practices so directly it makes sense to fix it. IMO changing the constructor to throw `FormatException` is both a less optimal solution, and a harder migration to make. Adding `tryParse` is clear, discoverable, a good practice, and non-breaking. It's _slightly_ odd to see a `tryParse` without a `parse`, but not so much to be blocking in my opinion.

The motivating example is https://github.com/dart-lang/pub/pull/2332#discussion_r381463780
