### ISSUE TITLE
dart2js now fails to compile dart:mirrors in Dart 2.8.0-dev.9.0

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#40698]
I'm not sure if this is a bug in `test` or in the Dart SDK, but I've only seen it when invoking `test` so I'm filing it here for now. That said, it only reproduces on Dart 2.8.0-dev.9.0, so it may be an SDK bug that test tickles.

When I run Node.js tests for Dart Sass on Dart 2.8.0-dev.9.0, I get a bunch of errors about `dart:mirrors` usages in `grinder` being unsupported ([example](https://travis-ci.org/sass/dart-sass/jobs/652675094)). Needless to say, I don't import `grinder` from my Node tests, and they compile fine on earlier Dart versions. This is blocking our support for the latest Dart.

**Comment by natebosch** [comment]
cc @sigmundch - did we intentionally break this support? I know we had looked recently at removing the partial `dart:mirrors` from DDC (instead of trying to migrate for null safety) and I imagine this change was triggered by that.

Our golden path for production builds already disallows the import, however the test packages and the `dart2js` binary both supported the import until now, and this is breaking to remove it.

Should we look at restoring the patch file where every API is implemented with a `throw`? Does that have code size implications?

**Comment by nex3** [comment]
Please don't break things like this without a breaking change announcement with enough time for downstream clients to migrate away from the old behavior. We have our own release schedules we need to keep to, and unexpected breakages like this make that difficult.

**Comment by sigmundch** [comment]
/cc @nshahan 

@natebosch  - you are correct, this is related to that change.

> Please don't break things like this without a breaking change announcement with enough time for downstream clients to migrate away from the old behavior. We have our own release schedules we need to keep to, and unexpected breakages like this make that difficult.

@nex3 our apologies here. Since we announced back in Dart 2.0.0 that isolates and mirrors were [no longer supported][1] on the web, our intent was to disallow imports to them as well. This was an honest mistake: we incorrectly thought this was not a breaking change visible to users because of how our main workflows (webdev/bazel) guard against it.

Next steps we should take:
* restore the import support in dart2js (both --server-mode and vanilla mode)
  * For dart2js, our patch files were already throwing unconditionally in dart2js, so it will entail a small amount of work. No code-size concerns here.

* restore the import support in DDC (unless we can quickly assess that it is not needed)
  * @natebosch - do the test packages expose ways to invoke DDC differently and thus allowing a `dart:mirrors` import? Or is build_runner/webdev guarding this scenario entirely?
  * if it is needed, we should restore to the original patches with the partial support we had before. Follow up with a breaking change announcement prior to unforking the null safe sdk, so the null-safe implementation can either be removed or made to throw at runtime (like the dart2js implementation does).


[1]: https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#200---2018-08-07

**Comment by natebosch** [comment]
> do the test packages expose ways to invoke DDC differently and thus allowing a `dart:mirrors` import? Or is build_runner/webdev guarding this scenario entirely?

`ddc` is a visible command from the SDK so _technically_ it could be used by someone, but we don't have any officially supported methods of using it other than `build_web_compilers` and the frontend server in flutter web. I don't know for sure whether flutter web was blocking the import, but since it's not supported in flutter mobile it was probably not used.

I do not expect anyone to be broken by removing support for mirrors from ddc.

**Comment by sigmundch** [comment]
Even though the chances of anyone else hitting this issue are pretty slim, we just landed 344e149a89bd2fc7dd73d538b6fbef8db8192a8d to revert the compile-time error, and continue to allow the import to an implementation that throws on all APIs.

Given that language versioning is becoming available as a delivery mechanism of breaking features, we are considering using that instead to get this out without accidentally breaking users when they upgrade their dart sdk.
