### ISSUE TITLE
Upload Dart SDK builds to CIPD for all revisions

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#40690]
Flutter currently builds a full Dart SDK in some scenarios.  We could avoid this if the Dart builders uploaded their builds to CIPD and we could just download them.

We would need:

JIT debug
JIT product
AOT non-product (profile)
AOT product (release)

/cc @jonahwilliams @athomas @godofredoc

**Comment by cbracken** [comment]
Related issues:
1. https://github.com/flutter/flutter/issues/94574
2. https://github.com/flutter/flutter/issues/94492

**Comment by athomas** [comment]
@chinmaygarde notes from our meeting:

We need:
* A name for the CIPD package somewhere under `https://chrome-infra-packages.appspot.com/p/flutter*`.
* The dart-luci-ci-builder@dart-ci.iam.gserviceaccount.com service account needs to be a `writer` on that that package (we'll likely have to change this account sometime in Q1).

The packages would be uploaded for each `dev`, `beta` and `stable` build (`main` isn't used in in Flutter DEPS). They would be uploaded tagged with `version:<full version string>` and `git_revision:<sha>` tags by the Dart SDK builders. We could add additionals refs and tags as well.

Uploads would done by the existing `dart-sdk-*` builders (probably using the build output dart-sdk folder rather than the actual zip files on GCS).

These are different from the checked-in SDKs used by Dart, because these binaries are unsigned (signing involves manual steps, we can't do it for every `dev` release right now).

**Comment by godofredoc** [comment]
`dart-luci-ci-builder@dart-ci.iam.gserviceaccount.com` was added to the flutter-cipd-writers group.

**Comment by chinmaygarde** [comment]
> A name for the CIPD package somewhere under https://chrome-infra-packages.appspot.com/p/flutter

I believe flutter/dart-sdk ought to be a good location. And the service account has been setup as well. @athomas Are there any other blockers?

**Comment by athomas** [comment]
No blockers, but we're in the process of moving these builders to another cloud project right now. I'd prefer to wait until that is complete (should be done end of next week).

**Comment by chinmaygarde** [comment]
Can you cross reference the issue tracking the movement to the cloud project so we can follow along please?

**Comment by athomas** [comment]
Whe can proceed when b/216086329 is done. /cc @sortie

**Comment by chinmaygarde** [comment]
The linked issue was fixed today!

**Comment by athomas** [comment]
There are no more issues blocking this (apart from changing the CIPD permissions above).

**Comment by sortie** [comment]
Yep. I believe you added it only recently per this task, so it shouldn't be used for anything, as the internal account is meant to be used for trusted actions like this. :)
