### ISSUE TITLE
Nullability of the Function type from typedef does not appear at the use site in kernel dump

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#40714]
Given the program:
```dart
typedef FnType = void Function(int)?;

main() {
  dynamic nullAsDynamic = null;
  FnType fn = nullAsDynamic;
}
```

I see the following snippet in the kernel dump
```
...
typedef fnType = (core::int) →? void;
static method main() → dynamic {
  dynamic nullAsDynamic = null;
  (core::int) → void fn = nullAsDynamic as{TypeError,ForDynamic,ForNonNullableByDefault} (core::int) → void;
}
...
```

The typedef includes the nullability but the location where the typedef is used does not. This is causing DDC to produce a runtime error when you try to dynamically assign `null` to a variable that has the typedef as a type.

@johnniwinther

**Comment by stefantsov** [comment]
If I remember it correctly, it should be forbidden to use the nullability suffix on the top-level type of the right-hand side of a typedef.  It implies that the use-site nullability should solely determine the nullability of the unaliased type.  The issue is that we don't complain about the marker being used in the typedef, so that the example program results in a compile-time error.

However, with non-function type aliases in sight it may be better to combine the nullabilities of the right-hand side of the typedef with the use-site nullability, but also report an error on the use of the nullability marker in the right-hand side.  When the non-function type alias feature is shipped, we can just remove the restriction.

@eernstg WDYT?

**Comment by eernstg** [comment]
I can't see any rules preventing the right hand side of a type alias (let's call it the 'body') from having a `?` to make it a nullable type. We'd certainly want to allow the `?` on types that are subterms of the body (to be able to have `typedef F<X> = void Function(X?);`). The nnbd spec does not mention 'alias' nor 'typedef', and the language specification says that the type alias creates an alias for a type (`$T$ is a type`).

Given that a type alias declares a (possibly parameterized) alias for a type, I don't see a reason why we should prevent it from aliasing an explicitly nullable type.

Is it a substantial extra effort to support type aliases where the body can be a nullable type, and combine the use-site nullability with the nullability of the typedef body? Presumably, the outcome should be like the outcome of passing an actual type argument (which may or may not have a `?`) to a generic class `C`, and then using the corresponding type variable `X` in a member signature (where it could occur as `X?`).

**Comment by stefantsov** [comment]
Sorry for the delay in the replies.  Proposed fix: https://dart-review.googlesource.com/c/sdk/+/138087

**Comment by stefantsov** [comment]
Some tests are failing with the fix: https://github.com/dart-lang/sdk/issues/40874.  I'm not sure what's the correct compiler behavior is in those cases, so I created https://github.com/dart-lang/language/issues/868 to clarify that.

**Comment by nshahan** [comment]
I initially found it confusing and assumed that the nullability would be captured in the typedef so I opened this issue. Thanks for opening the language issue to clarify what we really want the semantics to be.
