### ISSUE TITLE
Allow a package (pubspec) to override the language version [proposal]

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40718]
Imagine we unfork the SDK at ship dev release `2.8.0-dev.20.0`

We'd like to let a package/app author opt-in to null safety features to experiment, but setting their SDK constraint to

```yaml
environment:
  sdk: ">=2.10.0 <3.0.0"
```

Will fail because they are not running `2.10` – they are running `2.8.0-dev.20...`

Suggestion:

Add support for 
```yaml
language_version_override: 2.10
```

## Tooling change

* When `pub` generates `.dart_tool/package_config.json` it uses `language_version_override` (if it exists) instead of the SDK constraint.
  * This applies when depending on a package that has `language_version_override` set, too.
  * (This issue is being opened for discussion – implementation will happen in the pub repo.)

## Positive effects

* Eliminate use of `--experiment: non-nullable` CLI flags & analysis option config for analyzer
* Unblock validation of code paths described in https://github.com/dart-lang/language/pull/779 – RE inferring strong mode run state
* Eliminate need to hand-edit `.dart_tool/package_config.json`
* Easy to "lint"
  - Consider it only valid to use if the min SDK constraint is at the unfork point
  - Consider it invalid if the SDK lower bound is really `2.10` – once we're ready to ship
 
Can also be used as a gate to block publishing to `pub.dev` – except for (perhaps) packages that are whitelisted.

**Comment by kevmoo** [comment]
CC @mit-mit @vsmenon @leafpetersen

**Comment by mit-mit** [comment]
I'm not a big fan of adding a new field to pubspec. Could we not do what you list here, but as a special case of a lower SDK constraint being `>=2.10.0` ?

cc @lrhn

**Comment by lrhn** [comment]
Why would this eliminate the experiment flag for the analyzer? Would it treat a language_version_override in the pubspec as an implicit experiment flag?

I'd prefer to *not* have any way to enable experiments that avoids the experiment flag. It's cumbersome, but that's deliberate. You should not be running with an experiment without very explicitly asking for it.

The problem here is that the pub tool does not take `--enable-experiment` as a flag. If it did, then it could take *that* as an enabler for pretending to be an SDK of version up to 2.10. It should not be its default behavior &mdash; so don't special case `>=2.10.0` in the pub tool by default, only if you opt in to it. And since that opt-in should be explicit, it should not be based on a line in the pubspec which can be committed to a source repo and used by someone oblivious about it.

My recommendation: Add `--enable-experiment` as a flag to the pub tool. It might not need the experiment argument (but should accept them). With that flag, it allows SDK versions greater than the current one.

**Comment by mit-mit** [comment]
I agree that a combination of `--enable-experiment` and `>=2.10.0` is the best. It allows us to create the `pubspec.yaml`'s as we intend them to look once null safety goes stable, and to interpret those with 2.8-dev, 2.9-dev, and 2.10-dev builds.

**Comment by kevmoo** [comment]
> I agree that a combination of `--enable-experiment` and `>=2.10.0` is the best. It allows us to create the `pubspec.yaml`'s as we intend them to look once null safety goes stable, and to interpret those with 2.8-dev, 2.9-dev, and 2.10-dev builds.

So we are telling the pub client to allow `>=2.10.0` on `2.8-dev` SDKs?

What about 2.8 Stable SDKs? 2.9?

My goal was to eliminate "magic" behavior and make things a bit more explicit.

**Comment by franklinyow** [comment]
Any update on this issue?

**Comment by kevmoo** [comment]
We decided against going this route. Closing!
