### ISSUE TITLE
Failures on [tests] Add tests for function type equality with Null Safety

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#40733]
There are new test failures on [[tests] Add tests for function type equality with Null Safety](https://dart-review.googlesource.com/c/sdk/+/135533).

The tests
```
language/nnbd/type_equality/function_type_equality_test RuntimeError (expected Pass)
language/nnbd/type_equality/generic_function_type_equality_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

**Comment by crelier** [comment]
A CL is under review that is fixing 2 issues.
However, we will still need to implement proper handling of required named parameters for the tests to pass. liama@ is working on it.

**Comment by whesse** [comment]
There were also failures on two other configurations.  You may have missed them because they had a blamelist with 3 commits, so weren't in the block with just your commit.  Approving them, pasting this bug.  Log links :
https://dart-ci.appspot.com/log/analyzer-nnbd-linux-release/analyzer-asserts-strong-linux/1529/language/nnbd/type_equality/function_type_equality_test

https://dart-ci.appspot.com/log/analyzer-nnbd-linux-release/analyzer-asserts-strong-linux/1529/language/nnbd/type_equality/function_type_equality_test

**Comment by nshahan** [comment]
Thanks @whesse for catching these! 

@scheglov @stereotype441 Would you like to have a separate issue for the analyzer failures?

**Comment by scheglov** [comment]
@nshahan yes, please, assign it to me, or mention me. It will take me some time to get to these new tests, so tracking explicitly for analyzer would be useful.

**Comment by crelier** [comment]
Checking required named parameters (9e03c2c) fully fixed this issue.
