### ISSUE TITLE
Parser.parseDirectives crashes when two ';' after import.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#40755]
@jensjoha 

Patch https://dart-review.googlesource.com/c/sdk/+/137001 and run the `solo_` test.

It crashes.
Parsing the full unit is fine.

```
00:00 +0 -1: .: UtilitiesTest | solo_test_bug_131684167 [E]                                        
  Unsupported operation: AstBuilder.stack isn't empty:
    import
  package:analyzer/src/fasta/ast_builder.dart 85:5                   AstBuilder.internalProblem
  package:_fe_analyzer_shared/src/parser/stack_listener.dart 288:7   StackListener.checkEmpty
  package:analyzer/src/fasta/ast_builder.dart 959:5                  AstBuilder.endCompilationUnit
  package:_fe_analyzer_shared/src/parser/parser_impl.dart 431:14     Parser.parseDirectives
  package:analyzer/src/generated/parser_fasta.dart 185:32            ParserAdapter.parseDirectives2
  package:analyzer/src/generated/parser_fasta.dart 180:12            ParserAdapter.parseDirectives
  package:analyzer/analyzer.dart 133:21                              parseDirectives
  test/dart/analysis/utilities_test.dart 161:5                       UtilitiesTest.solo_test_bug_131684167

```

Context:  b/131684167

**Comment by davidmorgan** [comment]
Thanks Konstantin, thanks Johnni.

To add a bit of background: we've had multiple independent reports of this from users; the issue is that syntax errors in source now lead to unexpected / confusing exceptions in various tools. So, a quick fix would be appreciated, please :)

**Comment by jensjoha** [comment]
Technically it's the analyzer that's crashing, not `Parser.parseDirectives`.
That being said, the parser code probably isn't quite right. E.g., parsing `;` via `Parser.parseDirectives` crashes the analyzer in the same way.

The reason is that there's always a metadata object added to the stack, but when seeing a "single" `;` the parser doesn't fire any event that'll clear that out. I'll fix that (https://dart-review.googlesource.com/c/sdk/+/137790/).
