### ISSUE TITLE
language/nnbd/subtyping/function_type_required_params_test has analysis error

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#40781]
See [the log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8887435917704104384/+/steps/test_results/0/logs/new_test_failures__logs_/0).

```
--- Command "dart2analyzer" (took 73ms):
DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=machine --no-hints /b/s/w/ir/cache/builder/sdk/tests/language/nnbd/subtyping/function_type_required_params_test.dart

exit code:
1

stderr:
ERROR|COMPILE_TIME_ERROR|MISSING_DEFAULT_VALUE_FOR_PARAMETER|/b/s/w/ir/cache/builder/sdk/tests/language/nnbd/subtyping/function_type_required_params_test.dart|12|12|1|The parameter 'i' can't have a value of 'null' because of its type, so it must either be a required parameter or have a default value.

--- Re-run this test:
python tools/test.py -n analyzer-asserts-strong-linux language/nnbd/subtyping/function_type_required_params_test
```

The test was added in 9e03c2c506397002eda0d5a7432eaac0836091d9.
@liamappelbe

**Comment by whesse** [comment]
Since nobody will be working on fixing this except the analyzer team, I would suggest also adding area-analyzer.  There is no specific meaning for the area-test flag, or team responsible for issues with this flag.  The engprod team uses the area-infrastructure label for problems with the testing infrastructure, but problems with individual tests are solved by the team with the failure or the individual creating the test.  I would suggest not using the area-test label for a bug just because it is a failing test.

**Comment by liamappelbe** [comment]
I think I can just give the parameter a default value, without changing the behavior I'm trying to test.

**Comment by scheglov** [comment]
Sorry about this, @whesse.
I always used `area-test` for invalid shared tests, since 2011, I think :-)
Well, I will have to choose something better.
