### ISSUE TITLE
Consider integrating protobuf-aware treeshaking in TFA directly instead of running two rounds of TFA

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#40785]
We should consider integrating protobuf-aware treeshaking in TFA directly instead of running two rounds of TFA to reduce the AOT compilation time.

It would make TFA less self-contained, but it would probably save a lot in compile-time.

/cc @mraleph @alexmarkov

**Comment by mraleph** [comment]
There is another interesting thing about the integration: currently TFA does not track types through protobuf implementation well enough because of the reflective nature of the underlying GeneratedMessage implementation. This means we loose concrete type information about members that returns interface types like `List<...>`. We should consider finding a way to extend TFA with a concrete knowledge of `GeneratedMessage` implementation so that it could infer concrete type information in this cases.

**Comment by mraleph** [comment]
We should get the ball rolling on designing this integration, because it would help us to move the needle on compilation times internally.  

We had a brief chat with @alexmarkov on how this integration could look like few weeks ago - one idea that got brought up is that we could introduce some `@pragma(...)` or intrinsics that get transformed in a special way by TFA based on reachability of other members.

Then protobuf treeshaker just does a transformation of the Kernel which injects these constructs in the right place in the protobuf code and then TFA is run once afterwards.
