### ISSUE TITLE
Confusing promotion behavior with nullability

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40790]
```dart
void testFunction([math.Random? r]) {
  r ??= math.Random();
  print(r.nextBool());
  //    ^ no problem here!

  final generate = List.generate(5, (index) => r.nextBool());
  // Analyzer                                  ^ unchecked_use_of_nullable_value
  // VSM's DDC WIP fork                        ^ Warning: Method 'nextInt' is called on 'Random?' which is potentially null.
  print(generate);
}
```

@leafpetersen mentioned "we're not smart enough" – which, after discussion, I get.

I think folks will be confused by this.

**Comment by leafpetersen** [comment]
cc @johnniwinther @stereotype441 @scheglov just to be sure I'm diagnosing this right, but my read of this is that since `r` is assigned somewhere in the body of `testFunction`, we forget all promotion on it when we enter the closure body since we don't track that:
  - All assignments are executed before the closure is defined
  - No assignments invalidate the promotion

Both are true here, but not tracked.  

Tracking the first could in principle be done, but I presume we don't?

Tracking the second ("No assignments invalidate the promotion") is pretty much incompatible with the two pass algorithm that we use (compute the assigned variables, then do the flow analysis).  Maybe in principle we could queue up the closure bodies and only traverse them after we've traversed the outer method body?  

Whether or not we do better with this specific example, there will be similar cases where we can't promote inside the closure.  Is there any hope of giving a better error message to clue the user into the fact that we've had to discard the promotion?

**Comment by srawlins** [comment]
This is not currently tracked in any Null safety epic. Should it be?

**Comment by stereotype441** [comment]
> This is not currently tracked in any Null safety epic. Should it be?

@srawlins Probably.  Do we have an epic tracking usability issues with type promotion?  I remember @MichaelRFairhurst had been planning to do some work to generate "not promoted because..." error messages; probably this issue should be classified along with the work he was planning on doing.

**Comment by franklinyow** [comment]
@srawlins @stereotype441 @leafpetersen 
Please help assign a priority label for this one.

**Comment by srawlins** [comment]
@leafpetersen might be best to assign priority. The issue of messaging exists on both runtimes (VM) and analyzer:

```none
$ dartanalyzer a.dart 
Analyzing a.dart...
  error • An expression whose value can be 'null' must be null-checked before it can be dereferenced. • a.dart:8:48 • unchecked_use_of_nullable_value
1 error found.
$ dart a.dart 
a.dart:8:50: Error: Method 'nextBool' cannot be called on 'Random?' because it is potentially null.
 - 'Random' is from 'dart:math'.
Try calling using ?. instead.
  final generate = List.generate(5, (index) => r.nextBool());
                                                 ^^^^^^^^
```

**Comment by franklinyow** [comment]
ping @leafpetersen  for assigning priority
