### ISSUE TITLE
Add isCancelled to Timer class

### ISSUE THREAD

**Issue by fryette** [dart-lang/sdk#40804]
I would like to ask you to add `isCancelled` property to `Timer` class. 
For now if timer cancelled callback still alive and you have no chance to detect it. 

Code:

```
void someOneCanExecuteThisMethod(){
      //notify that we start loading
      stateNotifier.add(Loaded(model));
    _timer?.cancel();
    _timer = Timer(const Duration(milliseconds: 200), () async {
      final timerRef = _timer;
      //here we have looong request
      final model = await _loadModel();
      //here need to check, is timer was cancelled
      if (!timerRef.isCancelled) {
        stateNotifier.add(Loaded(model));
      }
    });
}
```

workaround:
```
class AdvancedTimer {
  AdvancedTimer(Duration duration, void Function() callback) {
    _timer = Timer(duration, callback);
  }

  Timer _timer;
  bool isCancelled = false;

  void cancel() {
    isCancelled = true;
    _timer.cancel();
  }
}
```

but it would be nice to have this feature in flutter SDK, because other languages also contain possibility to prevent execution of method(cancel Task, throw cancellation error during call and other)

**Comment by lrhn** [comment]
Not sure this usage is something we want to add support for.

A timer can be cancelled prior to it triggering, but cancelling it after should have no effect. 
The `cancel` stops the underlying platform timer from triggering and sets the timer as no longer active. That's all it needs to do.

Here the callback is doing something asynchronously and then wants to use a *later* cancel of the timer as a side-channel signal. That's not what cancelling is intended for. Adding support for that would mean retaining more state in all timers (not impossible, but currently not necessary). 

Adding a member to the `Timer` interface is a breaking change because there a significant number of classes implementing `Timer` in the larger Dart ecosystem. That means that the benefit of the change must outweigh

I'd recommend creating a helper class with a more elaborate cancel behavior,, rather than piggybacking on the `Timer`'s cancel. For example:

```dart
class CancelTimer implements Timer {
  final Timer _timer;
  bool _cancelled = false;
  CancelTimer(Timer timer) : _timer = time;
  bool get isCancelled => _cancelled;
  void cancel() {
    _cancelled = true;
    _timer.cancel();
  }
  bool get isActive => _timer.isActive;
  int get tick => _timer.tick;
}
```
If you wrap your timer in this class, and then pass that to whoever needs to perhaps cancel it, then you can check whether it was cancelled or not.


I can see a use in seeing whether a timer was cancelled *prior* to it triggering, so the owner can figure out whether the callback happened or not. That means that even if we were to add an `isCancelled`, I would probably not count cancels happening after the timer triggers, so it would not be usable for the current use-case.
