### ISSUE TITLE
Language version vs "enabled in"

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40806]
https://github.com/dart-lang/sdk/blob/60c86a400963cbf81ed68ba8444e78d5b1685fc2/tools/experimental_features.yaml#L94-L112

We have language features enabled in "dot" releases.

So which language version were these turned on?

Relates to @munificent new doc

If a feature was enabled in `2.2.2` I'd expect it's language version to be `2.3` – right?

CC @stereotype441

**Comment by lrhn** [comment]
All pre-language-versioning-feature releases are not under language-versioning control.

We do not distinguish between language levels below "release of language versioning", they are all considered to be equivalent to "release of language versioning" minus 0.1. That's where we start counting language versions from.

(Obviously tools with the knowledge to detect problems can still warn about them, but they might need, for reasons like this, to look at the actual SDK minimum requirement of a package rather than the language level).

That means that control flow collections are available in language versions 2.0 through 2.7 because these are all equivalent to 2.7 (which is so far the language-versioning - 0.1 version).

**Comment by parlough** [comment]
I'm going to close this since with language versioning all features are released in minor versions (3.x), and the pre-language versioning entries called out here were reduced to `2.0.0` in https://github.com/dart-lang/sdk/commit/01154855d1ea8ba460ce67ee06c8f1626547fa52, following the decision in https://github.com/dart-lang/language/issues/286#issuecomment-503614115.

Please reopen if you still have any concerns here :)
