### ISSUE TITLE
Identical : different results in DartPad and IntelliJ

### ISSUE THREAD

**Issue by shunjid** [dart-lang/sdk#40818]
This is a piece of code which uses identical function of **dart:core** library
```dart
void main() {
      print(identical(5, 5.0));
}
```

In the **[DartPad][1]**, this piece of code returns **true**.

But in my computer, it returns **false**.

**DartPad screenshot:**

[![enter image description here][2]][2]

**IntelliJ Idea** Side By Side Code and Output : 

[![enter image description here][3]][3]

> Is this expected? My current dart version:

```
$ dart --version
>> Dart VM version: 2.7.1 (Unknown timestamp) on "linux_x64"
```

  [1]: https://dartpad.dev/
  [2]: https://i.stack.imgur.com/gWdQX.png
  [3]: https://i.stack.imgur.com/RFzle.png

**Comment by lrhn** [comment]
This is expected behavior.

Dart has different number semantics when it's compiler to JavaScript than when it's running natively.
JavaScript does not have a separate integer type, only numbers (which are doubles) that happen to have no fractional part. 
Dart integers are represented by JavaScript numbers, which means that `5` is both an integer and a double at the same time. You can use it as both, and it's the exact same number as `5.0`.

Native Dart uses 64-bit integers for `int` and 64-bit floating point numbers for `double`, and it can tell the difference between the integer `5` and the double `5.0`.

DartPad compiles to JavaScript, your local computer runs programs natively.

See also #34105.
