### ISSUE TITLE
js interop inheritance works in DDC but not in Dart2JS

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#40840]
* dart2js
* Dart SDK Version (`dart --version`): 2.7.1

```
@JS()
class BaseClass { external factory BaseClass(); }

@JS()
class FooClass extends BaseClass { external factory FooClass(); }

@JS()
class BarClass extends BaseClass { external factory BarClass(); }

// ...
var a = FooClass();
var b = BarClass();

print(a is FooClass); // true in Dart2JS, true in DDC
print(a is BarClass); // true in Dart2JS, false in DDC
print(b is FooClass); // true in Dart2JS, false in DDC
print(b is BarClass); // true in Dart2JS, true in DDC

``` 

So it works correctly in DDC but not in Dart2JS

**Comment by natebosch** [comment]
I'm not sure which behavior was originally intended - in any case I would suggest structuring your code such that you can avoid needing `is` checks. There is a good chance we will remove support for `is` with JS interop objects in an upcoming new approach for JS interop.

cc @sigmundch

**Comment by sigmundch** [comment]
Correct - dart2js today cannot distinguish Js-interop types, they are all modeled in the same way, so if you have unrelated js-interop types A and B, dart2js will say true if you ask `o is A` or `o is B` for any js-interop instance `o`.

However, the two compilers are consistent when js-interop classes are also annotated with  `@anonymous`.

It's unfortunate, but being external to Dart, we can't quite model `is` checks as we do in Dart classes. As @natebosch suggested, we are making changes to clean up JS-interop further. Some changes are to make it more restrictive where our intuition as Dart developers doesn't match what we can do under the hood.

Personally, I'm hopeful that some proposals to the language around extension types get some traction, since they would enable us to have a model of js-interop types that is more intuitive.
