### ISSUE TITLE
Failures on [vm/compiler] Fix Mac builds and disassembler test.

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#40855]
There are new test failures on [[vm/compiler] Ensure we emit catch entry move for receiver when it is captured](https://github.com/dart-lang/sdk/commit/2cc824043d719ec1f6a17b7734fb432479597db9).

The tests
```
standalone_2/dwarf_stack_trace_obfuscate_test RuntimeError (expected Pass)
standalone_2/dwarf_stack_trace_test RuntimeError (expected Pass)
vm/dart/use_save_debugging_info_flag_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-x64
dartkp-linux-product-x64
dartkp-linux-release-simarm64
dartkp-linux-release-x64
dartkp-mac-release-simarm64
dartkp-no-bare-linux-release-simarm64
dartkp-no-bare-linux-release-x64
dartkp-obfuscate-linux-release-x64
dartkp-win-release-x64
```

**Comment by mraleph** [comment]
@sstrickl Teagan, could you look at these failures. I don't think my change should have affected these tests, so maybe there is a bug in the DWARF parser?

**Comment by sstrickl** [comment]
Am checking into it. Initial finding is that it looks like we're generating a DW_LNE_set_address opcode with size 5 (32-bit pointer following extended opcode) but writing a 64-bit pointer after it (so should be size 9). Given that, it's not the DWARF reader, but the DWARF writer that's at fault here.

... and looking at the DWARF writer, the problem is that we're writing sizeof(compiler::target::kWordSize), or sizeof(int), instead of just the _value_ of compiler::target::kWordSize. Adding a fix now.
