### ISSUE TITLE
[gardening] Many standalone_2/io tests broken on Windows after 0b819161d

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#40863]
See https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8886915568962103968/+/steps/test_results/0/logs/new_test_failures__logs_/0 for a list of failures on one configuration, but many Windows configurations are broken.

I've approved the failures.

/cc @mkustermann

**Comment by athomas** [comment]
This might be an infra issue.

**Comment by ZichangG** [comment]
Thanks to @athomas, the issue has been filed to dart_ci. https://github.com/dart-lang/dart_ci/issues/64

**Comment by athomas** [comment]
The redness was sticky because of this issue:
https://github.com/dart-lang/dart_ci/issues/64

I verified manually that all tests that @sjindel-google approved are now in fact fixed. These tests all got marked flaky for some reason and the result feed currently doesn't process fixes to flaky tests (hence it believes the tests are still broken and keeps the builds red).
