### ISSUE TITLE
Unhandled Exception: type '_Type' is not a subtype of type ...

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/sdk#40873]
This tracker is for issues related to:

* dart
* Dart SDK Version:: 2.7.0
* Mac os (10.15.3 Catalina)
* Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-KR)

I guess i found some bug in dart engine.

simply, this is my code.

```
@JsonSerializable()
class BaseResponse <T extends JsonObject>{
  BaseResponse();

  bool success;
  int code;
  @Converter()
  T data;

  factory BaseResponse.fromJson(Map<String, dynamic> json) => _$BaseResponseFromJson(json);
  Map<String, dynamic> toJson() => _$BaseResponseToJson(this);
}



@JsonSerializable()
class TermHolder implements JsonObject<TermHolder>{
  TermHolder();

  List<Term> termList;
  List<Term> termListService;


  factory TermHolder.fromJson(Map<String, dynamic> json) => _$TermHolderFromJson(json);
  Map<String, dynamic> toJson() => _$TermHolderToJson(this);

  @override
  deserialize(Map<String, dynamic> json) => TermHolder.fromJson(json);

  @override
  Map<String, dynamic> serialize(T) => toJson();

}


abstract class JsonObject<T>{
  T deserialize(Map<String, dynamic> json);
  Map<String, dynamic> serialize(T);
}
```

and when i run.

```
print("type of T: ${T.runtimeType.toString()}");
return (T as JsonObject<T>).deserialize(json); // -> does not work
// return TermHolder.fromJson(json) as T; // -> works
```

and the console will log as..

> I/flutter ( 6765): type of T: _Type
> E/flutter ( 6765): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_Type' is not a subtype of type 'JsonObject<TermHolder>' in type cast

this is weird cause. the `T`'s runtimeType is  `_Type` and it will not be able to cast as `JsonObject<TermHolder>` (which however i passed the correct format anyway. and it works with the commented out line on last code block i attached.) and the log will say ` '_Type' is not a subtype of type 'JsonObject<TermHolder>' in type cast` which `T` was typeof `JsonObject<T>` and it catches, but cannot convert type.

**Comment by mraleph** [comment]
```dart
return (T as JsonObject<T>).deserialize(json); // -> does not work
```

This does not make sense in Dart - when you write `T` in an expression you get a type object representing `T`. This type object is an instance of `Type` and not an instance of the type that it represents, e.g.

```dart
print(String is Type);  // true
print(String is String); // false
```

That is why `as JsonObject` fails.

This type object also does not have any methods, so you can't call `deserialiaze` on it. 

You might be under impression that `T` should have methods of the class that it refers to, but that's not how it works in Dart because classes are not first class values. 

In Dart when you write `SomeClass.staticMethod()` and `(SomeClass).staticMethod()` - this means two different things.

```dart
class SomeClass {
  static void staticMethod() { print('ok!'); }
}

void main() {
  SomeClass.staticMethod(); // ok
  (SomeClass).staticMethod();  // compile time error: 
  //  The method 'staticMethod' isn't defined for the class 'Type'       
}
```

**Comment by softmarshmallow** [comment]
@mraleph  ok. i understand. but than how can i accomplish above approach?
i cannot use some static method cause serialize/deserialize logic is unique by `some_model extends JsonObject`. i really need some smart way to do this. since dart does not support `(some as T).methodOfT()`.

**Comment by mraleph** [comment]
If you want to be able to write a function like this:

```dart
T deserialize<T extends JsonObject<T>>(Map json) {
  // call T.deserialize 
}
```

then you can't accomplish this in Dart right now, because there is no way to invoke methods on `T` (except through mirrors - which are not supported in Flutter or web).

So if you are writing some code that needs this sort of functionality then you need to rethink overall architecture.

What are you trying to achieve? 

(There are some quasi work-arounds, e.g. you can have a `Map<Type, Serializer>` kind of construct which you use to register all your types and then you can look things up in that map. But I would advice against that).
