### ISSUE TITLE
DDC nnbd sdk runtime type issue in setRange list method

### ISSUE THREAD

**Issue by rileyporter** [dart-lang/sdk#40884]
The check for subtype in the list `setRange` method is causing a failure for the corelib/list_test/none
test log: https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/2122/corelib/list_test/none

Shortest code to repro (with ddc and the sdk_nnbd in strong mode, chrome runtime):
```
import "dart:typed_data";

void main() {
  List<int?> list = new Uint8List(4);
  list.setRange(0, 4, [1, 2, 3, 4]);
}
```

Causes the following runtime error:
```
Uncaught Error: Type 'List<int?>' should be 'List<int>' to implement expected type 'Iterable<int>'.
    at Object.throw_ [as throw] (dart_sdk.js:3939)
    at Object.castError (dart_sdk.js:3897)
    at Object.cast [as as] (dart_sdk.js:4235)
    at Function.check_C [as _check] (dart_sdk.js:3862)
    at Uint8Array.setRange (dart_sdk.js:24981)
    at Object.main (test01.js:14)
    at test01.html:16
```

The error is being hit from the setRange method, when comparing the list type and the given `Iterable<E>` parameter type. The sdk seems to be treating the list type as the declared type of `List<int?>` and not the runtime type of `List<int>`, which is causing an error when trying to cast `List<int?>` to `Iterable<int>`.

When at a breakpoint for checking the cast inside of setRange:
 `if (dart.isSubtypeOf(actual, type))`, 
the type of `actual` is `List<int?>` and the type of `type` is `Iterable<int>`

**Comment by sigmundch** [comment]
Mmm.. I wonder if this was an unintended error in the test from the migration process.

@munificent, what are your thoughts?

It appears to me that the error is legit, and from a quick look I believe the other backends provide the same error.

`Uint8List` implements `List<int>`, the assignment to `List<int?>` is valid, but as a result the array `[1,2,3,4]` in the parameter to setRange gets an inferred type of `List<int?>`, which is what causes issues here. Eliding inference here and typing it as a `List<int>` avoids the issue:

```dart
import "dart:typed_data";

void main() {
  List<int?> list = new Uint8List(4);
  list.setRange(0, 4, <int>[1, 2, 3, 4]); // <<- added <int> here
}
```

**Comment by munificent** [comment]
Yeah, this is almost certainly an error in the test itself. That test was a pain to migrate. It was very cavalier about reusing the same code for lists that can and cannot contain nulls, so migrating it to be NNBD clean was... difficult. I'm not surprised I got something wrong.

In this case, it's a runtime failure that sneaks through the static type system because of unsound covariance, so I'm not surprised I didn't catch it during the migration. @rileyporter are you OK with fixing this test?

**Comment by rileyporter** [comment]
Yeah, I'm happy to fix it. Do you think the approach should be to clean up the code re-use for lists that can and cannot contain nulls, or are you thinking just add the stronger type <int> declaration where the unsound covariance applies?

Is there something else we want to explicitly enforce with these tests around this issue?

It sounds like we're not allowing:
```
  List<int?> list = new Uint8List(4);
  list.setRange(0, 4, [1, 2, 3, 4]);
```
But we would allow to explicitly add the stronger type declaration:
```
  List<int?> list = new Uint8List(4);
  list.setRange(0, 4, <int>[1, 2, 3, 4]); // added <int>
```
And I assume this is allowed if we change the declared type to be a list of non-nullable ints:
```
  List<int> list = new Uint8List(4);
  list.setRange(0, 4, [1, 2, 3, 4]);
```
Is it allowed to have nulls in the iterable for setRange? Something like this:
```
  List<int?> list = new List(4);
  list.setRange(0, 4, [1, 2, null, 4]);
```

**Comment by munificent** [comment]
> Do you think the approach should be to clean up the code re-use for lists that can and cannot contain nulls, or are you thinking just add the stronger type declaration where the unsound covariance applies?

I'm agnostic as to the solution. The tests don't get much love in general and not many people are familiar with them, so you are probably now already the resident expert for that particular test. :)

> But we would allow to explicitly add the stronger type declaration:
> 
> ```
>   List<int?> list = new Uint8List(4);
>   list.setRange(0, 4, <int>[1, 2, 3, 4]); // added <int>
> ```
> 
> And I assume this is allowed if we change the declared type to be a list of non-nullable ints:
> 
> ```
>   List<int> list = new Uint8List(4);
>   list.setRange(0, 4, [1, 2, 3, 4]);
> ```

Yeah, either of those changes seem reasonable to me. I think the question is mostly around whether you want to be able to reuse some of the utility functions in that test that do work with lists of nullable types.

Actually, now that I look at it, I think you may be able to just make all of the lists in that test use non-nullable types. I migrated it the way I did because I thought `new List(4)` was valid as long as the type argument was a nullable type. This test *does* intend to test the behavior you get from calling the List constructor.

But in a coincidental email yesterday, @lrhn said that the unnamed List constructor is always a compile-time error in null safe code. If that's correct, then you should be able to just delete all of the sections of that test that work test the unnamed List constructor and that coincidentally means all of the remaining lists have non-nullable types.
