### ISSUE TITLE
How do I pass a class as a function parameter?

### ISSUE THREAD

**Issue by Mrooze-zeng** [dart-lang/sdk#40923]
Hi guys, I am new to dart. Can you help me how to pass the class as a function parameter?
For example, the code in Javascript can be written like this:
```
class MyCls{
  hello(){}
}

function myFun(cls){
  return new cls();
}

myFun(MyCls);
```

but how do I pass a class as a function parameter in dart?

**Comment by mraleph** [comment]
You can't pass a class as a function in Dart, because classes are not functions. 

Right now you need to explicitly create a closure:

```dart
class MyCls {
}

myFun(maker){
  return maker();
}

myFun(() => MyCls());
```

Though there are some outstanding feature requests for some sort of constructor tear-off syntax (e.g. https://github.com/dart-lang/language/issues/216 and https://github.com/dart-lang/language/issues/691).
