### ISSUE TITLE
self-contained binary executables generated by dart2native is much slower.

### ISSUE THREAD

**Issue by yech1990** [dart-lang/sdk#40922]
### Dart vertion:

```bash
dart --version
```

** Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "linux_x64"**

```bash
uname -a
```
**Linux PC 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux**

### Test example:

```dart
// filename: fib.dart
int fib(int n) {
  if (n <= 1) return 1;
  return fib(n - 1) + fib(n - 2);
}

main() {
  print(fib(46));
}
```

### Run directly:

```bash
time dart fib.dart
```

**dart fib.dart  8.58s user 0.04s system 101% cpu 8.517 total**

### Run executable:

```bash
dart2native fib.dart -o ./fib
time ./fib
```
**./fib  17.22s user 0.01s system 99% cpu 17.238 total**

**Comment by mraleph** [comment]
AOT compiler is much less aggressive with inlining than JIT compiler because it prioritises code size, so in this particular case JIT would inline `fib` while AOT would not. You can put `@pragma('vm:prefer-inline')` on `fib` to force AOT to inline it as much as it can. That should equalise AOT/JIT performance. Actually on master AOT would be faster because it would use unboxed calling conventions.

I would like also to highlight that the algorithm you are using to compute `fib` is rather suboptimal - you can get much faster computation if you don't use recursive version. 

If you are worried about JIT vs AOT performance I suggest using more realistic code to benchmark.
