### ISSUE TITLE
Add @Since to pkg:meta

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#40963]
`@Since` exists, but it's SDK-internal.

Putting it in meta would let us 

- [ ] expose it in dartdoc
- [ ] use it to show warnings about using an API released in pkg 2.8 while having a constraint of `^2.7`

**Comment by kevmoo** [comment]
Related to https://github.com/dart-lang/dartdoc/issues/1513

**Comment by bwilkerson** [comment]
While I have no objection to defining it in `meta`, it is currently used in `dart:` libraries and the sdk maintainers have traditionally objected to using anything inside `dart:` libraries that is defined outside those libraries.

Unless that has changed, we can either export it from a public `dart:` library or we can have a second, public, annotation in `meta`. I'd prefer the former, but am happy to go with the second if making the sdk version public isn't viable.

**Comment by jcollins-g** [comment]
I don't think whether we put it in pkg:meta blocks dartdoc's use of it.  Dartdoc is capable of going out and finding it as long the symbol is findable in the import-export graph of the public libraries (which it is).    Dartdoc already has support for "special" SDK-internal-only objects like `Interceptor`, for example.  This seems no different.

**Comment by lrhn** [comment]
We don't merely *object* to using package declarations in the platform libraries. It's plain impossible.

We can move the platform declaration from `dart:_internal` to `dart:core`, so it becomes public. Then anyone can use the annotation for anything, but the analyzer can still trust that the SDK uses it for actual Dart releases. Since it is an annotation that the platform libraries use, like `deprecated`, there is precedence for having it exposed.

The biggest issue is that the documentation needs to be updated. It's currently documented for what it means in the platform libraries. It's not absolutely clear which "version" other code will be referring to. Most likely it's the version of the package that the code belongs to, but I would prefer to not hard-code the meaning into the platform library documentation.

So, maybe we can export the `Since` annotation, but `package:meta` can somehow add more documentation to it (not sure that's actually going to be possible prior to general type aliases).

**Comment by bwilkerson** [comment]
I'm going to close this as "will not implement".
