### ISSUE TITLE
Failures on [tests] Add tests for type object equality after FutrureOr normalization

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#41005]
There are new test failures on [[tests] Add tests for type object equality after FutrureOr normalization](https://dart-review.googlesource.com/c/sdk/+/138103).

The tests
```
language/nnbd/type_equality/futureOr_normalization_legacy_test RuntimeError (expected Pass)
language/nnbd/type_equality/futureOr_normalization_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
dartkp-strong-linux-release-x64
dartkp-weak-asserts-linux-release-x64
```

**Comment by crelier** [comment]
Thanks for the report. I am fixing the VM and I have questions about the test expectations:

1\) futureOr_normalization_test.dart line 22:
```
Expect.identical(extractType<Object?>(), extractType<FutureOr<Object?>>());
```
I do not find normalization rules that would normalize `FutureOr<Object?>`

2\) futureOr_normalization_test.dart line 38-39:
```
  Expect.identical(
      extractType<Embed<Object?>>(), extractFutureOrType<Object?>());
```
No normalization should apply here either.

3\) futureOr_normalization_legacy_test.dart line 28-29:
```
  Expect.identical(nullSafe.embeddedNullableFutureOfNull,
      extractType<nullSafe.Embed<FutureOr<Null>>>());
```
 Isn't that an issue in CFE? Shouldn't FutureOr<Null> be normalized immediately after parsing?

4\) futureOr_normalization_legacy_test.dart line 32 and following:
The expectations compare the result of `extractType`, which is the result of an instantiation in a legacy library, i.e. never non-nullable, with the result of `extractFutureOrType`, which returns a runtimeType, i.e. always non-nullable.
This cannot work with an implementation of `identical`, which distinguishes between legacy and non-nullable.  Using Expect.equals instead of Expect.identical works.

**Comment by eernstg** [comment]
Actually `FutureOr<Object?>` does normalize to `Object?`: `Object?` is a top type, so it's the first `if` bullet of the `FutureOr` section of [normalization](https://github.com/dart-lang/language/blob/master/resources/type-system/normalization.md). This makes sense intuitively as well: The union of a top type `T` and any other type (including `Future<T>`) is just `T` because that other type doesn't contribute any new values.

**Comment by nshahan** [comment]
From our discussion today, I will update the expectations in the tests from `Expect.identical()` to `Expect.equals()`. It wasn't my intention for these to be identical, it just fell out of the existing implementation in DDC.

**Comment by nshahan** [comment]
>  I agree that the normalization can be performed statically in this case, but in some cases it must be performed at run time (like `FutureOr<X>` where `X` is a type variable whose value happens to be `Object?`).

I tried to write both versions of all the test cases: Can be normalized at compile time vs must be normalized at runtime because of a type variable instantiation. If I missed some please feel free to add them or let me know.

**Comment by crelier** [comment]
I totally missed the fact that `Object?` is a top type. Of course. Thanks!

> I tried to write both versions of all the test cases: Can be normalized at compile time vs must be normalized at runtime because of a type variable instantiation.

Could it be that the snippet of question 3) detected a CFE issue? It seems to me that no instantiation at runtime results in a `FutureOr<...>` to be normalized in this example. The instantiation result is `Embed<...>` with a type argument that was not properly normalized to start with.
For performance reason, we do not traverse the type arguments of the resulting type of an instantiation, but only check if the top level is FutureOr class. 

> I will update the expectations in the tests from `Expect.identical()` to `Expect.equals()`

Great, thanks!

**Comment by nshahan** [comment]
> Could it be that the snippet of question 3) detected a CFE issue?

I agree that the normalization in that test should be handled at compile time and I added code to DDC to do so (actually for all of of these normalization cases). If we have a guarantee that the compile time normalization is already done in the CFE then I can remove the code paths in DDC since they would effectively be dead. I just didn't know if that was safe to rely on at this point.

**Comment by crelier** [comment]
/cc @johnniwinther
It looks like the CFE is performing normalization of `FutureOr<T>`, where T is a top type (as verified by this same test), but not if T is `Null` or if T is `Never`. So I think it is simply an omission. I do not think we should add code in the backends to normalize a type already instantiated at compiled time.

Note that the test is not verifying the normalization of `FutureOr<Never>`.

**Comment by johnniwinther** [comment]
@stefantsov Do you know the state of this? Do we have pending work on normalization wrt. `Null` and `Never`?

**Comment by stefantsov** [comment]
I'm only aware of normalization that we should perform during top-level type inference, and if in any other place the programmer writes something like `FutureOr<Null>` or `Future<Null>?` this is exactly what we'll produce on the output without normalizing those types.

**Comment by crelier** [comment]
My understanding was that normalization applies **immediately** to all types, whether written verbatim in the source, or obtained via inference or instantiation. I checked the normalization spec again and it tells a different story:

> It might also provide a more efficient implementation of type equality, since normal forms for types could be eagerly **or lazy** computed and cached.

I am wondering about the benefits of lazily computing the normal form. Preserving the verbatim form when printing runtime types in the VM would be too costly.
For performances reason, it makes sense to normalize eagerly in the VM, so I will add normalization of types when reading from the kernel file.
