### ISSUE TITLE
gen_snapshot performance regression

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#41022]
gen_snapshot runtime performance when used for android arm release builds regressed significantly(45s to ~30min) after https://dart-review.googlesource.com/c/sdk/+/138089.

**Comment by sstrickl** [comment]
Oof. If I reland this, I'll definitely merge the two CLs so that we don't have the work landing separately and causing that for any length of time in between.

It doesn't look, checking golem, that this was still the case after the second CL landed: do we have any numbers on that so we know if there was still a performance issue seen (though not nearly as severe) that needs to be investigated or if just relanding the merged CL should be okay?

**Comment by sstrickl** [comment]
Also given the graphs I see on golem, I'm surprised it didn't alert on this, even though it did alert on later performance changes. Are the compile time benchmarks not checked for performance changes? /cc @sortie

**Comment by sortie** [comment]
Only a single data point is gathered for the compilation time benchmarks per commit (because this is offloaded to the cloud when the .apk is built once), but the performance change detection requires at least two data points, so changes in compilation time are not detected.
