### ISSUE TITLE
Support Kernel files as input to dart2native

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#41046]
`dart2native` only supports Dart files as inputs, it can't create executables based on `.dill` files.

I'm currently working on a custom frontend generating Kernel from another language and I would like to create native executables for those Kernel files. It would be great if `dart2native` could apply AOT transformations and DCE on custom files Kernel files and then generate an executable from that.

**Comment by mraleph** [comment]
At this point we largely consider Kernel format an implementation detail of the SDK rather than an input format that SDK tools use internally. (contrast with Java class files which are a distribution format). `dart2native` is an end-user tool - so given this interpretation it does not really make sense for it to consume Kernel format.
