### ISSUE TITLE
dart + dartdev snapshot when run from a mac brew install

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#41057]
From an email from @devoncarew:

I noticed an issue w/ the dart VM + dartdev integration when run from a mac brew install:

[\~/projects/devoncarew/planets] dart --version
Dart VM version: 2.8.0-dev.14.0 (Thu Mar 12 11:00:10 2020 +0100) on "macos_x64"
[\~/projects/devoncarew/planets] dart analyze
**Could not find DartDev snapshot and 'analyze' is not a valid script.** [\~/projects/devoncarew/planets] 

some notes:
- this is for the most recent dart (dev channel) release
- I ran 'dart analyze'
- the dart VM could not locate the dartdev snapshot (brew does some hijinks with symlinks - I'm happy to investigate locally to give you more data, or, file an issue for this)
- the error message doesn't include a terminating newline :)

And:

Dart code, when trying to find the sdk dir that it's running in, pretty much always uses the 'Platform.resolvedExecutable' (https://api.dart.dev/stable/2.7.1/dart-io/Platform/resolvedExecutable.html) property. I believe that property was explicitly added for Dart command line tools to help them locate the SDK for some of these OS distros (brew, apt-get) which can do sophisticated things w/ symlinks.

**Comment by bkonyi** [comment]
So it looks like things worked as expected when using a single symlink, but using a symlink to a symlink was failing since the code we used in the VM to determine the directory of the `dart` executable was assuming that a path could only be a symlink to an absolute path. Changing the `if` to a `while` for the symlink evaluation code seems to fix the issue. Fix is uploaded [here](https://dart-review.googlesource.com/c/sdk/+/139781).

**Comment by devoncarew** [comment]
Related to #41329.

**Comment by insinfo** [comment]
am i getting this message when trying to run the dart in a container, any solution tips and what exactly does this error message mean?

Unable to find DartDev snapshot

https://github.com/subfuzion/dart-docker-slim/issues/8

**Comment by bkonyi** [comment]
@insinfo is this a container that's been configured by the Dart team or a custom container? If it's the former, please file an issue and cc me.

`dart` is looking for `../lib/_internal/dartdev.dill` relative to `$DART_SDK_ROOT/bin/dart` (this is the default location for the Dart executable). If you have a non-standard SDK folder structure, that's likely the issue here. You can bypass this by passing the `--disable-dart-dev` option, but I don't recommend using that as a long-term fix as it will impact functionality of developer tooling in the future.

**Comment by insinfo** [comment]
@bkonyi 
fantastic was just putting this "--disable-dart-dev" that solved the problem, I was getting beaten up with it all week, I used the image of Google Engineer Tony Pujals, because the goolge/dart image is very big, about 780MB , the error message could be better with more details on how to resolve the problem.

this is my Dockerfile

```Dockerfile
FROM google/dart:2.10 as jubarte2server
WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app
RUN pub get --offline
RUN cp .env.example.linux .env
#RUN dart compile kernel -o bin/prod.dill bin/prod.dart

FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
COPY --from=jubarte2server /root/.pub-cache /root/.pub-cache
COPY --from=jubarte2server /app /app
COPY --from=jubarte2server /app/.env /.env
COPY --from=jubarte2server /app/.env /app/bin/.env 
COPY --from=jubarte2server /app/.env /usr/lib/dart/bin/.env 
ENV dbhost=localhost
EXPOSE 3150
ENTRYPOINT ["/usr/lib/dart/bin/dart","--disable-dart-dev","/app/bin/prod.dart", "-p", "3150", "-a" ,"0.0.0.0","--dbhost=$dbhost"]
# docker build -f Dockerfile_jit -t jubarte2server-jit .
# executa a imagem
# docker run -e "dbhost=192.168.133.13" -d --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   
# docker run -e "dbhost=192.168.133.13" -i --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   

```
