### ISSUE TITLE
No compile time error for subtype checking

### ISSUE THREAD

**Issue by nguyenxndaidev** [dart-lang/sdk#41155]
* Dart SDK Version: Dart 2.7.0 on Windows (Flutter)

I have the code below:

```
class User {}

class Employee extends User {}

Employee createEmployee() {
  return User();
}

List<Employee> createEmployees() {
  return [User()];
}

List<Employee> createEmployees2() {
  var users = [User()];
  return users;
}

List<Employee> createEmployees3() {
  return [User()].where((e) => true);
}
```

In IntelliJ IDEA:
![image](https://user-images.githubusercontent.com/24372782/77354821-bbd8b780-6d43-11ea-8790-e39cb394e38f.png)

Errors on Line 6 and 10 are reported correctly at compile time.

However, no errors on line 15 and 19 at compile time. We only get error when run application at run time:
```
Unhandled exception:
type 'List<User>' is not a subtype of type 'List<Employee>'
```

It would be nice if we can get compile time error for line 15 and 19.

I tested the same thing with Kotlin and it shows the errors correctly for all places at compile time:
![image](https://user-images.githubusercontent.com/24372782/77355506-d8292400-6d44-11ea-8364-74c2f935f5a0.png)

**Comment by eernstg** [comment]
The reason why you don't get the static error for lines 15 and 19 is that Dart historically always allowed downcasts to occur in code implicitly: So when you return something of type `List<User>` in line 15 there is a downcast to `List<Employee>`, and that is checked at run time.

However, with the upcoming null-safety feature those implicit downcasts are no longer allowed, so you will get a compile-time error in the future, when you start using null-safety.

You can also choose to enable that error today using the `--no-implicit-casts` option.

So it is working as intended today, but the emphasis on flexibility rather than static type safety is a historical thing, and type safety will grow in several ways as we go ahead.
