### ISSUE TITLE
Analyzer: allowing a directory that starts with 'test' to satisfy the @visibleForTesting condition

### ISSUE THREAD

**Issue by guidezpl** [dart-lang/sdk#41151]
Relates to https://github.com/dart-lang/sdk/issues/31742

Right now 'test' and 'testing' are allowed. I'm working on a Flutter app with integration tests which are typically found in test_driver (per https://flutter.dev/docs/cookbook/testing/integration/introduction).

Easy fix would be to allow directories starting with 'test'.

If agreed, I can write up a PR for it.

**Comment by srawlins** [comment]
Thanks for filing a report! I would be much more comfortable with a short list of known by-convention test directory or file names. Since the directory you point out is a straight `test_driver`, I think we can add that to [the list](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/error/best_practices_verifier.dart#L1486).

I don't think we accept GitHub PRs. See our [CONTRIBUTING.md](https://github.com/dart-lang/sdk/blob/master/CONTRIBUTING.md). We use Gerrit for code review. Happy to accept a change request on Gerrit!

**Comment by guidezpl** [comment]
Sounds good, just added https://dart-review.googlesource.com/c/sdk/+/140867

**Comment by srawlins** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/140867
