### ISSUE TITLE
When having a List<Map>, Map method clear() clears out a Map, BUT also clears the Map out the List

### ISSUE THREAD

**Issue by tomasbaran** [dart-lang/sdk#41173]
Please RUN an example of the issue in dartpad: https://dartpad.dartlang.org/ca96c17dbdbb07a2c062ffc28d079a45 

When we use Map = {} instead of Map.clear(), everything works as it should. Take a look here:
https://dartpad.dartlang.org/cda9c5ccb8da4b7cdf69f3a1d8d9df5e 

* My Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "macos_x64"

**Comment by julemand101** [comment]
What "List<Map>" actually means is that you have a list of references to Map objects. When you then add your map object to the list with "list.add(map);" you are inserting the reference to you map object into the list.

So in the end, there are only one map instance in your code but you have multiple variables pointing into this same map object. Therefore, when you are calling "map.clear()" you are making this call on the only map instance in your code. Since your list are referring to the map you have cleared it will also be seen as empty.

When you are using "map = {}" you are actually creating a new empty map object and sets the map variable to point to this new instance. Since your list are still referring to the old instance it will be seen as it keep its elements.

If you want to put a copy of your map into the List you can use "list.add(Map.from(map));" when adding the map to the list. Then it will not be affected if you later makes modifications to the Map object which the map variable are referring to.

**Comment by mraleph** [comment]
@tomasbaran see @julemand101 answer. In future I recommend asking questions like this on Stack Overflow or other support channels (e.g. Discord, etc).
