### ISSUE TITLE
`NoSuchMethod error when using `await` in a function named `result`

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/sdk#41204]
Based on a thread from StackOverflow: https://stackoverflow.com/questions/60856139/is-result-a-reserved-function-or-keyword-in-dart

I'm not sure if this is an issue with DartPad or dart2js, but I am assuming it's the latter.  I tested with a version of DartPad using version 2.7.2 of the Dart SDK.

Steps to reproduce:

1. Paste the following code into DartPad:

```dart
void result() async => await Future.value(1);

void main() {
  result();
}
```

2. Click the Run button.

Result:
On Firefox 74.0 (64-bit), I get:
> Error: Error: NoSuchMethodError: this.bodyFunction is null

On Chrome  80.0.3987.149 (64-bit), I get:
> Uncaught Error: NoSuchMethodError: method not found: 'call$2' on null

**Comment by sigmundch** [comment]
Thanks for filing the issue and for the small repro!

This sounds very familiar and I thought we had fixed this, but turns out we haven't. I finally found a similar bug entry here: https://github.com/dart-lang/sdk/issues/30585

I'll merge the two. The other bug has more details so I'll mark this one as a duplicate entry.
