### ISSUE TITLE
DDC should determine null safe "strongness" based upon entrypoint language version

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41209]
Enabled #41203
Requires #41205

**Comment by sigmundch** [comment]
I posted a question in #41203 to clarify the overall goal and plan here.

Even if the goal is to make tools pick a default, I don't believe we can in DDC. When DDC runs on a module, it doesn't know what the entrypoint will be. We expected this would be determined by the tool that embeds DDC (whether that is build_runner, bazel, or flutter's frontend-server)

**Comment by kevmoo** [comment]
> I posted a question in #41203 to clarify the overall goal and plan here.
> 
> Even if the goal is to make tools pick a default, I don't believe we can in DDC. When DDC runs on a module, it doesn't know what the entrypoint will be. We expected this would be determined by the tool that embeds DDC (whether that is build_runner, bazel, or flutter's frontend-server)

@johnniwinther @natebosch @jakemac53 @leafpetersen ?

**Comment by natebosch** [comment]
@sigmundch - this issue only covers the case of `dartdevc` from the command line. I thought we had a set of flags that you could use to invoke `dartdevc` against a `main.dart` like you can with `dart2js`, but now I can't figure out what the exact command should be. We will indeed be handling this in the build system for modular builds.

**Comment by johnniwinther** [comment]
CFE now supports computing the language version for an entrypoint (https://dart-review.googlesource.com/c/sdk/+/141250) and .dill files now contain a `Component.mode` that matches the nnbd compilation mode for the entry-point when present (https://dart-review.googlesource.com/c/sdk/+/142149).

**Comment by franklinyow** [comment]
Moving this to tech preview 2 since this is no longer a requirement by dartpad

**Comment by nshahan** [comment]
Is this still a requirement? I'm not sure how DDC can know when it is compiling a file with the entry point.

If we still think this is needed maybe we could only detect the version iff we are given a single input file?

In cases where DDC is provided multiple inputs it requires a .packages to be provided. It looks like this should probably be updated to accept a packages.json instead and it can determine the mode for all the files from there.

I think the build system should provide the `--sound-null-safety` or `--no-sound-null-safety` flag. DDC should just use that mode when provided.

**Comment by jakemac53** [comment]
> Is this still a requirement? I'm not sure how DDC can know when it is compiling a file with the entry point.

It is a requirement that user-facing tools (compilers, build systems, etc) do this. DDC is in a grey area because the vast majority of the time it is compiling a single module and doesn't have access to the entrypoint, so it must be told the correct mode to compile in. Given that I don't think it can distinguish the modes and the relative low usage of it as a whole world compiler that users are directly invoking, I think it should not implement this.

> If we still think this is needed maybe we could only detect the version iff we are given a single input file?

This could still have false positives. If anything I would try to do defaulting when no mode is explicitly passed.

> In cases where DDC is provided multiple inputs it requires a .packages to be provided. It looks like this should probably be updated to accept a packages.json instead and it can determine the mode for all the files from there.

This should already be working properly, package_config.json files are passed using the same arguments as regular package files, and in fact will be loaded even if a `.packages` file is passed - if there is a `.dart_tool/package_config.json` directly next to it. The CFE implements this, as does `loadPackageConfigUri` from package:package_config.

> I think the build system should provide the `--sound-null-safety` or `--no-sound-null-safety` flag. DDC should just use that mode when provided.

Yes at least in the general case, this is how it has to work.

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/build/issues/2723
