### ISSUE TITLE
NNBD. Null can be passes to non-nullable function parameter at runtime

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#41217]
The following code produces no error at runtime (with the keys` --ignore-unrecognized-flags --enable-experiment=nonfunction-type-aliases,extension-methods,non-nullable`)

```dart
dynamic forgetType(dynamic x) => x;

class C {}

test(C c) {}

main() {
  test(forgetType(null));
}
```
Tested on Dart VM version: 2.8.0-dev.17.0 (dev) (Tue Mar 24 16:38:30 2020 +0100) on "windows_x64"

**Comment by alexmarkov** [comment]
By default _weak_ checking mode is used when non-nullable experiment is enabled. That mode still allows nulls in variables of non-nullable types. In order to enable _strong_ checking mode, specify `--null-safety` option in addition to `--enable-experiment=non-nullable`. In strong mode (if there are no opted-out (legacy) libraries) variables of non-nullable types cannot be null.

**Comment by alexmarkov** [comment]
On the tip of the tree, running with `--null-safety` produces the following error:

```
Unhandled exception:
type 'Null' is not a subtype of type 'C'
```

Tentatively closing this issue. @sgrekhov please comment if it still doesn't work for you.
