### ISSUE TITLE
Function<T> as generic type constraint

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/sdk#41218]
The following code throws this error while compiling:

>  Error: 'validationMessage' isn't a function or method and can't be invoked.
>     return validationMessage(value);

Are TypeConstrains on Functions allowed?
- If yes, is this a bug?
- If no, should the analyzer catch this?

``` dart
abstract class Validator<TypeOfValidatedValue, KeyType,
    ValidationMessageFuncType extends String Function(TypeOfValidatedValue)> {
  final ValidationMessageFuncType validationMessage;

  Validator(this.validationMessage);

  String createValidationMessage(TypeOfValidatedValue value) {
    return validationMessage(value);
  }
}

```

How can I solve this problem?

**Comment by eernstg** [comment]
The bound of a type variable must be a type, but there are no restrictions on which kind of type; in particular, it can be a function type.

The example program causes an error in dartpad.dev, but not with `dartanalyzer`, `dart`, or `dart2js` (2.8.0-dev.17.0).

However, for a work-around right now you may be able to just use that function type. Do you actually need to choose a proper subtype of that function type?

```dart
abstract class Validator<TypeOfValidatedValue, KeyType> {
  final String Function(TypeOfValidatedValue) validationMessage;
  Validator(this.validationMessage);
  String createValidationMessage(TypeOfValidatedValue value) {
    return validationMessage(value);
  }
}
```

In any case, what you need is actually declaration site variance, because there is a particularly nasty clash between the dynamically checked covariance that Dart currently adopts and the usage of a type variable of a class at a contravariant position in a member signature:

```dart
abstract class Validator<in TypeOfValidatedValue, KeyType> {
  final String Function(TypeOfValidatedValue) validationMessage;
  Validator(this.validationMessage);
  String createValidationMessage(TypeOfValidatedValue value) {
    return validationMessage(value);
  }
}
```

We plan to add support for declaration site variance, but nothing is certain yet (for timing, or even 100% commitment to do it).

**Comment by eernstg** [comment]
The tricky question remains: Should it be an error to invoke an expression of type `T` where `T <: F` where `F` is a function type?

We do in fact [specify](https://github.com/dart-lang/language/blob/35ce3873ec46480b318020828c0d9553e6e595ac/specification/dartLangSpec.tex#L10377) that it is a compile-time error to invoke an expression whose static type is not `dynamic`, not `Function`, and not a function type. So invoking an expression whose static type is a type parameter is an error, even in the case where the bound of that type parameter is a function type.

**Comment by HerrNiklasRaab** [comment]
FYI: This is what I wanted to achive:

```dart
class ShouldBeSmallerOrEqualThenValidator<KeyType>
    extends Validator<double, KeyType, String Function(double, {double max})> {
  final double max;
  ShouldBeSmallerOrEqualThenValidator(this.max,
      {String Function(double, {double max}) validationMessage, KeyType key})
      : super(validationMessage, key);

  @override
  String createValidationMessage(double value) {
    return validationMessage(value, max: max);
  }
}
```

Now I am doing your proposed solution, but I need to cast:

```
class ShouldBeSmallerOrEqualThenValidator<KeyType>
    extends Validator<double, KeyType, String Function(double, {double max})> {
  final double max;
  ShouldBeSmallerOrEqualThenValidator(this.max,
      {String Function(double, {double max}) validationMessage, KeyType key})
      : super(validationMessage, key);

  @override
  bool isValid(double value) {
    return value <= max;
  }

  @override
  String createValidationMessage(double value) {
    return (validationMessage as String Function(double, {double max}))(value, max: max);
  }
}
```

If there is a more elegant way to this right, now let me know.

**Comment by eernstg** [comment]
With a couple of small adjustments (adding a field `final KeyType key` and an initializing formal `this.key` in the constructor of `Validator`), the example without my workaround works. So I guess that's what you have been using, and it basically just works with most tools today.

However, if we make it an error to call an expression whose type is a type parameter (even when its bound is a function type), cf. dart-lang/language#896, then it won't work to do this. We may or may not decide that it is an error.

Otherwise you could choose to use `implements`, and then consider adding an `extends` or `with` clause to a class/mixin that provides whatever implemented methods that you need in order to avoid code duplication. 

```dart
abstract class Validator<TypeOfValidatedValue, KeyType> {
  final String Function(TypeOfValidatedValue) validationMessage;
  final KeyType key;
  Validator(this.validationMessage, this.key);
  String createValidationMessage(TypeOfValidatedValue value) =>
      validationMessage(value);
}

class ShouldBeSmallerOrEqualThanValidator<KeyType>
    implements Validator<double, KeyType> {
  final String Function(double, {double max}) validationMessage;
  final KeyType key;
  final double max;
  ShouldBeSmallerOrEqualThanValidator(
      this.max, {this.validationMessage, this.key});
  @override
  String createValidationMessage(double value) =>
      validationMessage(value, max: max);
}
```

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/pull/900, which aims to allow the original form of the example program.

**Comment by eernstg** [comment]
Said PR was landed as https://github.com/dart-lang/language/commit/1feae06ff82e55b380c3858a3b497faf8021f96b. So it is not an error to call an expression whose type is a type variable whose bound is a function type.

By the way, that's a nice and consistent outcome! &mdash; especially when we add the ability to make these kinds of designs statically safe by means of declaration-site variance.

Test in https://dart-review.googlesource.com/c/sdk/+/141249 shows that all the 'trybots' (that is, a selection of configurations of test runner platforms) run the new test that uses this feature without failure. So it's not obvious to me that there is any tool/configuration where the reported failure occurs.

However, the error does occur in a `dartpad.dev` which indicates that it's running version 2.7.2, and I can see it with `dart2js` version 2.7.0-dev.2.1.

So I'll close this issue, and note that any problems of this nature would be expected to disappear when tools are upgraded to version 2.8.anything.
