### ISSUE TITLE
Have better typed code in `dart:async`'s zone implementation

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#41253]
Right now completing a completer calls [_Future.handleValue](https://github.com/dart-lang/sdk/blob/56748006a1c/sdk/lib/async/future_impl.dart#L140)
```dart
  FutureOr<T> handleValue(S sourceResult) {
    return _zone.runUnary<FutureOr<T>, S>(_onValue, sourceResult);
  }
```
Which calls [_CustomZone.runUnary](https://github.com/dart-lang/sdk/blob/56748006a1cf1d7057c6ed7d0f61e95016d7c23f/sdk/lib/async/zone.dart#L1043):
```dart
  R runUnary<R, T>(R f(T arg), T arg) {
    var implementation = this._runUnary;
    assert(implementation != null);
    ZoneDelegate parentDelegate = _parentDelegate(implementation.zone);
    RunUnaryHandler handler = implementation.function;
    return handler(implementation.zone, parentDelegate, this, f, arg);
  }
```

Which accesses the [_CustomZone._runUnary](https://github.com/dart-lang/sdk/blob/56748006a1cf1d7057c6ed7d0f61e95016d7c23f/sdk/lib/async/zone.dart#L852) callback:
```dart
class _CustomZone {
  _ZoneFunction<Function> _runUnary;
  ...;
}

class _ZoneFunction<T extends Function> {
  final _Zone zone;
  final T function;
  const _ZoneFunction(this.zone, this.function);
}
```

Notice above that `RunUnaryHandler handler = implementation.function` will cause us to perform a runtime type cast against [RunUnaryHandler](https://github.com/dart-lang/sdk/blob/56748006a1cf1d7057c6ed7d0f61e95016d7c23f/sdk/lib/async/zone.dart#L17):
```dart
typedef RunUnaryHandler = R Function<R, T>(
    Zone self, ZoneDelegate parent, Zone zone, R Function(T arg) f, T arg);
```

@lrhn Can we avoid these **hot** runtime type checks in the async/zone implementation?

**Comment by lrhn** [comment]
Maybe!

The problem is that the correct type is `ZoneFunction<R Function<R, T>(T)>`, but *you cannot have generic function types as type arguments* (https://github.com/dart-lang/language/issues/496).
So, we cannot just correct the type.

Maybe we can make a specific class, `UnaryZoneFunction`, with the exact same signatures as `ZoneFunction<R Function<R, T>(T)>` and use that instead of `ZoneFunction`.
We'll need to do the same for `run`, `runBinary`, `bind`, `bindUnary`, `bindBinary`, etc. (maybe some can be reused, I'm guessing `runUnary` and `bindUnary` will have the same signatures).

**Comment by lrhn** [comment]
Proof-of-concept code: https://dart-review.googlesource.com/c/sdk/+/141884 (completely untested yet).
