### ISSUE TITLE
Analyzer and CFE disagree on accessibility of static declarations in extensions.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41268]
Consider the following code:
```dart
class C {
  static int fieldInC = 1;
  void methodInC() {
    print(fieldInC);
    print(fieldInE1); // CFE error
    print(fieldInE2); // CFE error
  }
}

extension E1 on C {
  static int fieldInE1 = 2;
  void methodInE1() {
    print(fieldInC); // Analyzer error, CFE error
    print(fieldInE1);
    print(fieldInE2); // CFE error
  }
}

extension E2 on C {
  static int fieldInE2 = 3;
  void methodInE2() {
    print(fieldInC); // Analyzer error, CFE error
    print(fieldInE1); // CFE error
    print(fieldInE2);
  }
}

main() {
  C().methodInC();
  C().methodInE1();
  C().methodInE2();
  print(C.fieldInC);
  print(C.fieldInE1); // Analyzer error, CFE error
  print(C.fieldInE2); // Analyzer error, CFE error
}
```
The analyzer issues errors on the lines marked `Analyzer error`, whereas the CFE issues errors on the lines marked `CFE error`.

I'm not sure whether this is an analyzer bug or a CFE bug since I'm not sure which behavior is correct.

@lrhn @eernstg @leafpetersen can you help classify this bug?

**Comment by eernstg** [comment]
The [main section](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md#static-members-and-member-resolution) on this topic as well as the [extension methods spec](https://github.com/dart-lang/language/blob/master/accepted/2.6/static-extension-members/feature-specification.md) as a whole gives no other way to access a `static` member of an extension than (1) access using the name (using `myStaticMember...` to access `E.myStaticMember`) inside `E`, because `E.myStaticMember` is declared in an enclosing scope; and (2) qualified access anywhere (using `E.myStaticMember` to access `E.myStaticMember`).

Looking over all cases mentioned [here](https://github.com/dart-lang/sdk/issues/41268#issue-590979643), my conclusion is that the CFE accepts/rejects all cases correctly, so I would mark this as an analyzer issue.

**Comment by leafpetersen** [comment]
> Looking over all cases mentioned [here](https://github.com/dart-lang/sdk/issues/41268#issue-590979643), my conclusion is that the CFE accepts/rejects all cases correctly, so I would mark this as an analyzer issue.

Agreed.  The lines with a CFE only error are accessing an identifier which is not in the static scope, and is not in the instance scope, so they should be errors.

**Comment by srawlins** [comment]
Analyzer's behavior is unchanged.
