### ISSUE TITLE
[Breaking change request] Align semantics of opted-out static fields with NNBD static fields

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#41285]
# Summary

The current semantics of lazy initialization of static fields causes a `CyclicInitializationError` to be thrown and the field value being initialized to `null` if the initializing expression of the field accesses the field (directly or indirectly). A subsequent access to the field will obtain `null`.

With NNBD any static field is implicitly late. Late fields would instead cause a `StackOverflowException` and the field value would stay uninitialized. A subsequent access to the field will continue to have the same behavior (since the field wasn't initialized yet).

# What is changing:

Static fields would get the same semantics as NNBD late fields.

# Why is this changing?

This aligns the semantics of static fields with NNBD static fields, thereby simplifies the language and make it more consistent for users.

It also simplifies the backend implementation as well as improves speed and reduces code size, since it's no longer necessary to distinguish the field states "uninitialized" from "currently-initializing" - it stays "uninitialized" until the value is available.

# Expected impact

No changes to the static type system. At runtime, programs currently not causing a `CyclicInitializationError` to be thrown should run unchanged. The expected impact is therefore minimal.

# Mitigation

Not available / Not required: Programs running without the mentioned error should continue to run the same way.

**Comment by mkustermann** [comment]
@vsmenon @leafpetersen @lrhn @eernstg Do you think it's worthwhile doing?

**Comment by eernstg** [comment]
Just to clarify: This breaking change is about a _backport_ of the NNBD treatment of top-level variables and class variables (known as 'static variables' in the spec) such that it is used without null-safety enabled, as well as with null-safety, right? (I would the change to be enabled in any execution with null-safety, so that's not a breaking change, or even a change at all.)

As I understand the situation, the trade-off would be that not-yet-migrated programs would benefit from the improved performance, but there may be some breakage. So maybe the next step would be a global presubmit?

**Comment by leafpetersen** [comment]
@mkustermann I'm hesitant to roll out more breaking changes, but this should be entirely non-breaking in practice.  Is it easy enough to run a google3 presubmit for this?  If so, and it's clean I'm fine with this.

**Comment by mkustermann** [comment]
> @mkustermann I'm hesitant to roll out more breaking changes, but this should be entirely 
> non-breaking in practice. Is it easy enough to run a google3 presubmit for this? If so, and it's 
> clean I'm fine with this.

Have run a presubmit check for cl/310406439 which changes the semantics in the Dart VM. See the results there. The only failures that show up seem to be flakes.

**Comment by leafpetersen** [comment]
My only remaining concern is whether the additional work for the three backends is worth moving up the arrival of the new semantics by a few months.  @sigmundch thoughts on how much effort it is to backport these semantics to the web backends?

cc @vsmenon

**Comment by sigmundch** [comment]
In terms of work for web backends: it's not much. For both DDC and dart2js this is a question of how the code is lowered, there are no dart2js optimizations that take advantage of the new semantics yet. So, we basically have a boolean to choose one implementation or the other depending on whether the enclosing library is opted-in or not. 

I'm not opposed to doing this, but I should note that this came up when we were discussing what breaking changes to ship early (see row 28 on the "pre-nnbd breaking changes" spreadsheet). 

Looking up the 'additional details' there, we wrote:

> ... we feel it's ok to continue as planned: delay this breaking change until users opt-in for the first time on their own libraries.

IIRC, I believe we were inclined not to do it because it was pretty local and guarded by language versioning. Whereas the other language changes we were evaluating at the time (like type normalization and mutual subtyping of bounds) affected code in and out of the opted-in libraries, so we were forced to do the breaking change upfront.

**Comment by eernstg** [comment]
So we have a (very mildly) breaking change, which is attractive because it improves the performance of legacy code. The argument that it simplifies the language is a bit less convincing, I think, because legacy code will go away. But it would still be useful to be able to simplify the implementation of the language.

@sigmundch wrote:
> IIRC, I believe we were inclined not to do it because ...

Those reasons pretty much amount to "we don't _have to_ introduce this breaking change", but the current argument is "we _want to_ introduce this breaking change" because of the simplification/performance.

This makes it tempting to say: Let's do it&mdash;especially if it is a small effort.

**Comment by franklinyow** [comment]
How are we doing on this discussion?

**Comment by rakudrama** [comment]
My feeling is that the user has access to the improved performance by opting into nnbd.
We should not potentially break existing code unless there is a substantial benefit.

I think that throwing the `CyclicInitializationError` is useful on the web. Only the top 10 frames of the stack are available, so all the user has to debug is the recursive call, and not the call where the initializer is first invoked. This is especially true in production where the stack trace is sent to a server and there is not possibility of attaching a debugger.

**Comment by mkustermann** [comment]
Will close this then.
