### ISSUE TITLE
DDC under NNBD instantiates raw types with "Object?" instead of "dynamic"

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#41301]
I'm [migrating language/closure/type_arguments_test.dart to NNBD](https://dart-review.googlesource.com/c/sdk/+/141702). It fails on line 40 of that CL because the instantiated type arguments are `Object?` instead of `dynamic`. Most real-world code won't care about the difference, but code that happens to check for very specific runtime types (like this test) can. I believe `dynamic` is the specified behavior and is what the VM does.

cc @eernstg

**Comment by nshahan** [comment]
Note: The original test language_2/closure/type_arguments_test is passing on the ddc-nnbd-linux-release-chrome configuration in weak mode.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/908, that I created in order to clarify the language definition part of this question. There's a bias in the direction of saying that DDC should infer `dynamic`, but I haven't got explicit buy-in for a conclusion either way yet.

**Comment by eernstg** [comment]
dart-lang/language#908 was concluded with the decision that I mentioned above: DDC should infer `dynamic` rather than `Object?` such that the failure in https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8884178758135030624/+/steps/test_results/0/logs/new_test_failures__logs_/0 doesn't occur.

I just checked, and it does fail with the same symptom in commit 01d9d1ca81b0a45b14364ac01ed4cdf664b7a595 (from today).
