### ISSUE TITLE
Style issue: `unnecessary cast` warning when specifying (an inferred) type via a cast

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#41331]
A recent change to an analyzer API meant I needed to add type information since inference was now finding an incompatible type.  (See: https://github.com/dart-lang/linter/pull/2053.)  In chatting w/ @bwilkerson, my understanding is that a cast is preferred, but then I get an `unnecessary cast` warning.

![image](https://user-images.githubusercontent.com/67586/78403936-327e7c00-75b2-11ea-97cf-831fad2c5577.png)

The rub is it **_is_** necessary since `preceedingComments` actually returns a `CommentToken`.

There's a work-around obviously:

![image](https://user-images.githubusercontent.com/67586/78404078-84270680-75b2-11ea-9930-d8477675e80f.png)

but my understanding is that this is not the preferred style.

In case this instance is useful Brian suggested I file an issue so here it is.  Feel free to close out or do with it as you please.

Cheers!

/cc @munificent @stereotype441

**Comment by bwilkerson** [comment]
If using an `as` _is_ the preferred style, then we should consider fixing the hint to not generate a diagnostic when the `as` is the top-level expression in an initializer.

**Comment by eernstg** [comment]
Please note that a type cast is not a safe replacement for a variable type annotation:

```dart
class SimpleToken implements Token {}
class StringToken implements SimpleToken {}
class CommentToken implements StringToken {}

class Token {
  CommentToken get precedingComments => CommentToken();
}

void main() {
  var t1 = Token();

  Token t2 = t1.precedingComments; // OK.
  Token t3 = "Hello, world!"; // Error.

  var t4 = t1.precedingComments as Token; // OK.
  var t5 = "Hello, world!" as Token; // OK, but of course only at compile-time.
}
```

A type annotation will directly associate the variable with a specific type, and we'll get a compile-time check that the initializing expression is actually of that type (or a subtype thereof). A type cast will yield an expression with the specified type by fiat, no matter which type of expression it is applied to. So this difference is not just a matter of style.

I think the relevant style preference would be that types must be specified inside the initializing expression, in safe ways (such as providing explicit type arguments to list literals and constructor invocations, but not by a cast), and I do agree that this simplifies certain things.

That's basically because it provides information at the source which would otherwise have been computed declaratively (that is, "backwards") by type inference, and type inference is a pretty complex mechanism. However, it is necessary for the reader of the code to perform that forward computation if the type of the variable is of any interest.

```dart
Map<X, List<X>> foo<X>(X x) => {x: []};

void main() {
  // Feed `int` forwards into the computation of the type of `x`.
  var x1 = foo<int>(2); // `x` has type `Map<int, List<int>>`.

  // Declare the type, then let inference work backwards.
  Map<int, List<int>> x2 = foo(2); // Infer the call as `foo<int>(2)`.
}
```

So the trade-off is whether we want to document the variable type (and trust inference to do the right thing), or we want to provide types directly to enable a simple forward computation (which, however, means that the type of the variable is implicit and must be found by a computation, or maybe it can be shown by some UI action).

**Comment by munificent** [comment]
Ah, this is an interesting case. There are two cases where inferred type of a variable may not match the initializer's type:

1. When you want the variable's type to be a *subtype* of the initializer's. In other words, you want to downcast the variable. For these cases, I have always preferred using `as` because it makes it clearer to the reader that a potentially failing cast is occurring:

    ```dart
    var input = querySelector('input') as InputElement;
    ```

    With NNBD, you will *have* to do this since implicit downcasts are going away. So that's good.

2. When you want the variable's type to be a *supertype* of the initializer's. You want to upcast. This happens because, like in the example here, you want to later assign a different type to the variable. The initializer's type was more precise than you wanted.

    Dart's C-like variable declaration syntax makes this one a little harder because the natural answer of just annotating the variable looks a little funny. It looks unclear to people who want to see `var` for every variable declaration. And for people used to annotating *every* local variable, it's not clear that the variable's type is not the same as the initializer's. So doing:

    ```dart
    Token comment = token.precedingComments;
    ```
    
    Sends kind of an unclear signal. A reader may not realize that `precedingComments` returns a different type. Using `as` sends a very clear signal that "hey, the types aren't the same".

    But I think it also sends the signal "this cast may fail", which is *not* the case at all here. And, like @eernstg notes, it can mask a mistake where you thought you were doing a safe upcast but actually weren't.

    Adding all that up, I think the better answer is to prefer annotating the local variable on an upcast. I wish we had types on the right. That would make this feel more natural.

This is in line with [what Effective Dart says](https://dart.dev/guides/language/effective-dart/design#do-annotate-when-dart-infers-the-wrong-type).

**Comment by srawlins** [comment]
Also, we now only report `unnecessary_cast` when the cast type is the exact same as the expression's static type.
