### ISSUE TITLE
Missing documentation for analysisServer - closingLabels

### ISSUE THREAD

**Issue by ericdallo** [dart-lang/sdk#41338]
I'm trying to implement the `closingLabels` notification for [emacs `lsp-mode`](https://github.com/emacs-lsp/lsp-mode) and I noticed that the documentation for the `closingLabels` notification is missing [here](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#notification_analysis.closingLabels).

**Comment by bwilkerson** [comment]
I think there's some confusion here. If you're using LSP to communicate with the server then the referenced specification is not the one you want. The analysis server was written before the LSP spec was first published and had a similar style of using a wire protocol. We have since added support for LSP, so now it supports two separate, though similar, protocols. The document you referenced specifies the original protocol.

I believe that what you're looking for is documentation for the extensions to LSP that the server supports. @DanTup Do we have any documentation for those extensions?

**Comment by DanTup** [comment]
The custom notifications in LSP are detailed here:

https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md

For closing labels specifically, there's a boolean you must pass `closingLabels: true` in the `InitializationOptions`. This will enable `dart/textDocument/publishClosingLabels` notifications which have the form `{ uri: string, labels: { label: string, range: Range }[] }`.

If anything in the docs aren't clear, let me know and I'll update them. Thanks!

**Comment by ericdallo** [comment]
Yeah I found this README and implemented [here](https://github.com/emacs-lsp/lsp-mode/pull/1573)
Thanks for the help @bwilkerson and @DanTup!
