### ISSUE TITLE
NNBD: the least and greatest closure of a type does not use Object? in runtime.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41386]
Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"

The following source code example throws a compile error with analyzer and passes printing `true` in runtime:
``` dart
bool Function(T) predicate<T>(bool Function(T) fn) => (T val) => fn(val);

void main() {
  print(predicate((v) => v % 2 == 1)(3));
}
```
According to the recent nnbd spec [update](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#least-and-greatest-closure) it should throw a compile error in both cases.

Sample output is:
> $> dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error - The expression is nullable and must be null-checked before it can be used. - test.dart:4:26 - use_of_nullable_value
> 1 error found.
> 
> $> dart --enable-experiment=non-nullable --null-safety test.dart
> true

**Comment by vsmenon** [comment]
@johnniwinther @leafpetersen - this appears to be a missing error in the cfe.  Please re-triage if I got that wrong.

**Comment by leafpetersen** [comment]
Yes, this is a missing error.  The downwards context for the parameter to `predicate` should be `bool Function(?)`, so the inferred parameter type of `v` should be the greatest closure of `?` which is `Object?` in nnbd.

**Comment by johnniwinther** [comment]
@leafpetersen Where is the specification for this?

**Comment by eernstg** [comment]
About the null-safety specific changes to the greatest/least closure operations, there is [this section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#least-and-greatest-closure).

For the locations where these operations are used, there is [inference.md](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md), but you may need to look at the large comment at the end.

**Comment by johnniwinther** [comment]
Wouldn't this mean that `map` in

```Dart
var map = {};
```

is now inferred to have type `Map<Object?, Object?>` ?

**Comment by eernstg** [comment]
There is a distinction between the greatest closure, which is used for [function literal type inference](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference), and instantiation to bound, which is used to select the type arguments passed to a generic function invocation when no constraints apply. The latter chooses `dynamic`, and that would also apply to instance creations and to collection literals.

@leapetersen, do you agree?

**Comment by johnniwinther** [comment]
And where is the definition of this distinction?

**Comment by johnniwinther** [comment]
For the code in the example, does it mean I should infer:

```Dart
bool Function(T) predicate<T>(bool Function(T) fn) => (T val) => fn(val);

void main() {
  print(predicate<dynamic>((Object? v) => v % 2 == 1)(3));
}
```
That is, `dynamic` for the type parameter and `Object?` for parameter even when these are linked by  `T` ?

**Comment by eernstg** [comment]
I would say "yes". However, cf. https://github.com/dart-lang/language/issues/908#issuecomment-607753083, I'm sure @leafpetersen can add detail and background.

**Comment by johnniwinther** [comment]
I can't see why and how we should have a disconnect between the value for `T` implied by the argument type (inferred or not). If we have

```Dart
class Class<T> {
  Class(void Function(T));
}
void function1(String o) {}
void function2(Object? o) {}
void function3(dynamic o) {}
main() {
 new Class(function1);
 new Class(function2);
 new Class(function3);
 new Class((o) {});
}
```
shouldn't we use the type of the argument to compute the type argument for `Class` in all cases:
```Dart
class Class<T> {
  Class(void Function(T));
}
void function1(String o) {}
void function2(Object? o) {}
void function3(dynamic o) {}
main() {
 new Class<String>(function1);
 new Class<Object?>(function2);
 new Class<dynamic>(function3);
 new Class<Object?>((Object? o) {});
}
```
?

**Comment by johnniwinther** [comment]
A CL is in progress: https://dart-review.googlesource.com/c/sdk/+/144940

**Comment by leafpetersen** [comment]
> That is, `dynamic` for the type parameter and `Object?` for parameter even when these are linked by `T` ?

No.  Sorry, I realize this part of the spec is in a tremendously bad state, and I'm not happy with where the language is either, but for path dependent reasons this is where we are.

The relevant distinction is between types which arise by "closing" a type schema, vs types which arise from choosing a final generic instantiation in an under-constrained inference problem.  There's no essential reason for doing a different thing here - it's just that for historic reasons we used `dynamic` everywhere, and for usability reasons we're trying to shave away uses of `dynamic` at the margins.

To elaborate.  There are certain points in inference when we have a type schema (by which I mean a type which may contain placeholders, which I usually write `?`), and need to reify it as a type.  For example, during downwards inference, the "context type" is really a "context type schema".  Greatest/least closure defines how we get from a "type schema" to a type, essentially by replacing all of the `?` by a top or bottom type depending on the variance of their position of occurrence. So in the original example, we have a downwards context of `bool Function(?)`, and  hence a parameter type schema of `?` which we need to turn into a type so that we can do inference on the body of the lambda.  Greatest closure used to produce `dynamic` here, the change for null safety is that it produces `Object?`.  As a result, inference fills in the lambda as `(Object? v) => ...` and then upwards inference fully constrains `T` to be `Object?` as you observe.

The instantiation to bound comes in when we've completed the inference process, and we have type variables which are still under-constrained.  Hence an example like `void foo<T>(int x) {print(T);};  foo(3);`.   After doing downwards inference on `3` in context `int`, we do upwards inference, and we end up with `T` being still totally unconstrained.  At this point, in a last minute desperation move, we use instantiation to bounds to try to produce *something* useful for `T`.  Instantiation to bound is still defined to substitute `dynamic` for unresolved things, and so... we end up producing `foo<dynamic>(3)` as the inference solution.

For generic functions, it's plausible that we could make this final instantiate to bounds step use `Object?` instead of `dynamic`, but... we haven't taken that step yet.  For types, it would be hugely breaking (but also, I think hugely beneficial).

> shouldn't we use the type of the argument to compute the type argument for `Class` in all cases:

Yes.  Your filled in types for `Class` are all what I expect here.
