### ISSUE TITLE
Analyzer: implement changes to TOP_MERGE.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41412]
This [pull request](https://github.com/dart-lang/language/pull/904) specifies a change in the definition of the NNBD_TOP_MERGE algorithm.  This is ready for implementations.  Tests for this change are landing here:
  - [TOP_MERGE member override tests.](https://dart-review.googlesource.com/c/sdk/+/142802).
  - [Test TOP_MERGE on super-interfaces.](https://dart-review.googlesource.com/c/sdk/+/141847).

The following tests are currently failing and should pass when the above change is implemented.

```
language/nnbd/top_merge/top_merge_interfaces_direct_error_test MissingCompileTimeError (expected Pass)
language/nnbd/top_merge/top_merge_interfaces_indirect_error_test MissingCompileTimeError (expected Pass)
language/nnbd/top_merge/top_merge_interfaces_mixin_error_test MissingCompileTimeError (expected Pass)
language/nnbd/top_merge/top_merge_members_direct_error_test MissingCompileTimeError (expected Pass)
language/nnbd/top_merge/top_merge_members_indirect_error_test MissingCompileTimeError (expected Pass)
language/nnbd/top_merge/top_merge_members_mixin_error_test MissingCompileTimeError (expected Pass)
```

cc @scheglov @stereotype441

**Comment by scheglov** [comment]
I have an issue with `language/nnbd/top_merge/top_merge_interfaces_indirect_error_test`.

The code:
```dart
class A<T> {}

class B<T> extends A<T> {}

class Merge<S, T> extends A<S> implements B<T> {}

class D0 extends Merge<dynamic, Object?> {}
```

We report an error on `class Merge`: `error: The class 'Merge' cannot implement both 'A<S>' and 'A<T>' because the type arguments are different. (conflicting_generic_interfaces at [test] bin/test.dart:13)`. And the list of implemented interfaces is fixed on the class level - once we determined that `Merge` implements `A<S>` - it does so for all uses.

At the point where we then use class `Merge`, it does not matter that in this specific case arguments for `T` and `S` are compatible.

@leafpetersen It looks to me that the spec speaks about classes as well: `a class C in an opted-in library implements the same generic class I more than once...`. So, is this a mistake in the test, or the spec means something else, or I don't understand something?

**Comment by leafpetersen** [comment]
@scheglov You are correct, the design of that test is broken.  I'll revisit it, thanks for catching.  cc @johnniwinther

**Comment by leafpetersen** [comment]
Proposed test fix [here](https://dart-review.googlesource.com/c/sdk/+/142887)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/143060 will fix `language/nnbd/top_merge/top_merge_members_mixin_error_test`.
