### ISSUE TITLE
Map class is generic, but not type-safe

### ISSUE THREAD

**Issue by chickenblood** [dart-lang/sdk#41427]
Dart-version 27.2.

Map [] access is not type-safe.

Example:

```
class Foo {
};
…
final map = <Foo, int>{}
…
final value = map["bad"]; // This should not compile. The key type is Foo, not String.
```

Docs confirm That it takes an Object and not a &lt;K&gt; (which is what one would expect).
https://api.dart.dev/stable/2.7.2/dart-core/Map/operator_get.html

These other methods on Map are also type-unsafe:
containsKey(), containsValue(), removeObject()

**Comment by lrhn** [comment]
This has been brought up before, and it is a deliberate choice. The choice matches what Java does as well.
See e.g. #22781.

**Comment by bobatsar** [comment]
I am stumbling on a similar problem but am not sure if it is the same.

When using an enum as a key for a map, the linter and compiler throw an expected error on the following case.

```dart
enum En { e1, e2 }

void main() {
  Map<En, String> myMap = {};
  myMap[En.e1] = "hello";
  myMap["123"] = "hello";
}
```

But with the following code, the code compiles and a runtime TypeError error is thrown:

```dart
enum En { e1, e2 }

void main() {
  Map<En, Map<String, String>> myMap = {};
  myMap[En.e1] = {"hello": "world"};
  myMap["123"]["123"] = "hello";
}
```

```
TTypeError: myMap.$index(...) is nullError: TypeError: myMap.$index(...) is null
```

Shouldn't this also be catched from the compiler/linter?

**Comment by eernstg** [comment]
This is the same issue: `myMap["123"]["123"] = "hello";` invokes `operator []` on `myMap`, which is the issue discussed here, and then `operator []=` is invoked on the resulting `Map<String, String>` which is fine. It turns out to be null, so you get the dynamic error you mention, but there is no type error in passing `"123"`, neither the first nor the second time.

The null error can be handled with the upcoming null-safety feature, so you'll need a `!` or something like that in order to deal with null explicitly, but that is a separate issue.

**Comment by lrhn** [comment]
The reason you are seeing a difference is that `operator[]` takes `Object` as argument and `operator[]=` takes a `K` as its key argument. So, you are hitting the same problem as the rest of this issue with the `operator[]` lookups, but seeing errors when using `operator[]=` writes.

**Comment by bobatsar** [comment]
Ok, thanks for the clarification.
