### ISSUE TITLE
dart2js unfork code size regression

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41433]
This issues track unfork dart2js code size metric

2020/04/20 criteria
Benchmarks below are currently blocking on the 'production' configuration.

AsyncStressTest benchmarks
Several members (Stream and Futures) at -50% which should be no worse that -10%

Iteration benchmarks:
Iteration.concat.manual2.typed -38%
Iteration.deeptree.syncstar -27%
Iteration.concat.syncstar -15%
These iteration benchmarks need to be understood and mitigated.

**Comment by rakudrama** [comment]
production CompileAcsGallery: +2.041%
spec mode CompileAcxGallery: +1.597%
CM main: +0.584%

**Comment by vsmenon** [comment]
We should get #s for Flutter Gallery as well.

Do you think we can bring the ACX overhead down soon?  Do you have a sense of why that's higher than CM?

**Comment by rakudrama** [comment]
My ancient copy of flutter gallery is 1.12% (production).

The size regression seems to reduce as the app grows larger. Several contributing factors:

- There are more types in the type pool - e.g. `int` and `int*`. This is mostly because the sdk is opt-in, but other code is opt-out. The effect is somewhat limited by the size of the sdk vs other code. CM is the only app where the sdk is insignificant.
- There are more type operations - 25%-50% more to dynamically 'star' a type since type the type variable access `T` is now `T*`.
- The type relationship `A<T> extends B<T>` is now `A<T> extends B<T*>` which takes extra space to encode.

**Comment by rakudrama** [comment]
No update

**Comment by rakudrama** [comment]
No update

**Comment by vsmenon** [comment]
Per my update here - https://github.com/dart-lang/sdk/issues/41431#issuecomment-615500143 - Flutter gallery appears well within 1%.

Is there anything still here we would block unforking on?

**Comment by rakudrama** [comment]
production CompileAcxGalleryMinify: +1.118%
production CM main: +0.591%

**Comment by franklinyow** [comment]
Synced with @sigurdm And @rakudrama , the code side is within range to unfork.  If require, new issues can be open in future milestone

**Comment by sigmundch** [comment]
@sigurdm you can ignore this, @franklinyow was referring to me :)
