### ISSUE TITLE
CFE: Incorrect inference for generic method with nullable parameter

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41447]
This program:

```dart
  void foo<T extends num>(T? x) {}

  void bar<S extends num>(S? y) {
    foo(y);
  }
```

when compiled with the CFE produces this error:

```
../../../tmp/test4.dart:44:5: Error: Inferred type argument 'S?' doesn't conform to the bound 'num' of the type variable 'T' on 'foo'.
Try specifying type arguments explicitly so that they conform to the bounds.
    foo(y);
    ^
../../../tmp/test4.dart:41:12: Context: This is the type variable whose bound isn't conformed to.
  void foo<T extends num>(T? x) {}
```

I believe that this error is because the CFE is incorrectly inferring `S?` for the type argument to `foo` instead of `S`.  This can be seen in the following variant of the program, which currently prints out "int?".

```dart
  void foo<T>(T? x) {
    print(T);
  }

  void bar<S extends num>(S? y) {
    foo(y);
  }

  void main() {
    bar<int>(3);
  }
```

I believe the correct solution to this should be `S`, since the subtype matching problem is checking `S? <: T?`, solving for `T`, which produces the constraint `S <: T <: ?`.

cc @johnniwinther @stefantsov

**Comment by johnniwinther** [comment]
In this context, should `Null` be taken as a `S?` (i.e. as a `Never?`) ?

It would pose a problem with the current port of the `Future.value` constructor:

```Dart
  factory Future.value([FutureOr<T>? value]) {
    return new _Future<T>.immediate(value as FutureOr<T>);
  }
```

For the expression `new Future.value(null)` we would have `Null <: FutureOr<T>?` which gives the constraint `Never <: FutureOr<T> <: ?`. We would therefore infer `new Future<Never>.value(null)` and fail at runtime in the `value as FutureOr<T>` expression.

See https://dart-review.googlesource.com/c/sdk/+/142986/4

/cc @lrhn @stefantsov

**Comment by lrhn** [comment]
For the `Future` constructor, it's one of those functions where the optional parameter can only really be omitted when the type parameter is nullable, but we can only detect that at run-time.

Those functions are bad. I want them to be gone. That'll have to be a later breaking library change, though.

I see the problem, though.

How do you solve for T when you have `foo<T extends num>(T? y)` with `foo(null)`. There is no hint what `T` is because *all* subtypes of `num` are allowed.
Do you pick the most specific or the least specific subtype. Do you recognize the case where the subtype is unconstrained specially?
I would probably solve that with `T` being `Never`. 
If we had passed an `int?` to `foo`, we would have inferred `T` as `int`. 
When we pass a `Null` to `foo`, we also pick the most specific.

That's not *precisely* the same as for `Future.value`. The difference is that the type variable for `Future` allows nullable types. That doesn't solve anything by itself, the most specific static solution to `Future.value(null)` is still `Future<Never>.value(null)`. It's just that `Future<Null>.value(null)` is also a possible solution. We don't *have* to remove the nullability from the parameter in the inferred type argument, and I think we shouldn't. (Always prefer the precise type the user provided over something we derive, if possible).

So, I'd say that for type inference of `foo(null)` we see that `T` is unspecified and bounded by `num` (non-nullable), the argument has type `Null` and must have type `T?`, so we solve that with `T` being `Never`.

For `Future.value(null)` we see that `T` is unspecified and bounded by `Object?`, the argument has type `Null` and must have type `T?`. Since `Null` itself is a solution, we can use that. That is, ignore that the parameter type is `T?` when `T` can be nullable.

Would that be possible?

**Comment by johnniwinther** [comment]
It's possible. I'll make a patch to the aforementioned CL to see the impact.

**Comment by johnniwinther** [comment]
I've added some tests in https://dart-review.googlesource.com/c/sdk/+/142986/4..5 and the new implementation in https://dart-review.googlesource.com/c/sdk/+/142986/5..8

The implementation special-cases `Null` so that for `Null <: T?` it generates the constraint `Null <: T <: ?` if the bound of `T` is potentially nullable and `Never <: T <: ?` otherwise.

@leafpetersen @lrhn Take a look. What should we go with?

**Comment by leafpetersen** [comment]
@johnniwinther The treatment of `T?` should basically follow that of `FutureOr<T>` - they're both union types.  The algorithm for `FutureOr` is basically as follows:

If matching `FutureOr<S>` against `FutureOr<T>`, match `S` against `T`.

If matching `FutureOr<S>` against `T`, match `Future<S>` against `T`, `S` against `T`, and union the constraints.

If matching `S` against `FutureOr<T>`:
  - If matching `S` against `Future<T>` succeeds and produces 1 or more constraints, then we're done.
  - If matching `S` against `Future<T>` failed, or produced no constraints, then we try matching `S` against `T`

The other relevant detail is that this matching is done **before** we check whether the left or right side being matched are top or bottom.  This means that matching `Null <# FutureOr<T>` solving for `T` will produce the constraint `Null <: T <: ?`, because we match `Null <# Future<T>` which succeeds but yields no constraints, and so we try `Null <# T` which produces the above constraint.

The `T?` union type is analogous.  The only question is, which arm of the union should be matched first?  That is, the algorithm looks like:

If matching `S?` against `T?`, match `S` against `T`.
Otherwise, if matching `S?` against `T`, match `S` against `T` and `Null` against `T` and union the constraints.
Otherwise, if matching `S` against `T?`:
  - match `S` against `T`.  If this succeeds, and yields at least one constraint, return that constraint set.
  - Otherwise match `S` against `Null` and return the result.

For your example (`Future.delayed`), we have:
  -  `Null <# FutureOr<T>?` solving for `T`
    -  Try `Null <# FutureOr<T>` solving for `T`
      - Try `Null <: Future<T>` solving for `T` fails
      - Try `Null <: T` solving for `T` succeeds with constraint `Null <: T <: ?`

Resolving the constraint set should end up choosing `Null` as the solution for `T`, which is what we want.

I believe that choosing to try match `S` against `T` here  before trying `S` against `Null` is the correct order here.  I don't have an example where it matters off the top of my head though.  In your example above, if we tried `Null <# Null` first, we would succeed but with no constraints, and so we would end up trying `Null <# Future<T>` anyway and get the same solution.  The only way that I can think of that you can have `S <# Null` succeed and generate a constraint is if `S` is a type variable which extends `Never` or `Null`.  But in that case, we would never fall through to this stage of matching in the first place, since the first thing we do is check if `S` or `T` are type variables.

Does that make sense?  

cc @scheglov @stereotype441

**Comment by lrhn** [comment]
Here we are matching `Null` against `T?` (aka `T|Null`) solving for `T`, where `T` has bound `Object?`.

So it doesn't matter whether we check `Null` against `Null` first because that doesn't provide any constraint on `T`, and we are back to solving `Null` against `T`, which is solved by `T == Null`.
(I'm not particularly happy about the asymmetry of testing one union type before the other, and I fear we might be seeing a symptom of that here).

It also matters whether we treat `Null` as just that, or as `Never?`. The latter matched against `T?` would (in parallel to the `FutureOr` rule) match `Never` against `T`.

If we compare that against the similar situation where `T`'s bound is `Object`, then. `Null` vs `Null` still provides no input, and `Null` against `T` has no solution.

What if the rules for union types were such that matching A|B against C|D would check all of:
A vs C
A vs D
B vs C
B vs D

If there is one of A or B which has *no* match, then the entire thing does not match.
Otherwise collect all the constraints and use the least upper bound of them. If there are no constraints, .... use `Never`?

In the case of matching `Null` vs `T|Null` with `T` having a nullable bound, 
we get `Null <: T` as a valid constraint.

In the case of matching `Never|Null` vs `T|Null`, we get the constraints `Null <: T` and `Never <: T`, so we use `Null` again.

If `T` has a non-nullable bound, then `Null` vs `T|Null` provides no constraints, but does have a match, so valid and `T` is `Never`
Matching `Never|Null` against `T|Null` provides the constraints `Never <: T`, and same result.

**Comment by leafpetersen** [comment]
@lrhn I think your algorithm does the following:
  - `FutureOr<T> <# FutureOr<int>` solving for `T`
    - `Future<T> <# Future<int>` produces `? <: T <: int`
    - `Future<T> <# int` fails and produces no constraint
    - `T <# Future<int>` produces `? <: T <: Future<int>`
    - `T <# int` produces `? <: T <: int`

Merging these constraints yields:  `? <: T <: Never`, which results in `T == Never` being chosen.

This is indeed a solution, but not a useful one.

**Comment by lrhn** [comment]
Ack, because `T <: FutureOr<int>` is one of the constraints that come out of the cross product.

I'm trying to figure out what we'd do if we had general union types. If we can't do anything useful there, and we are relying on ad-hoc fixes for specific unions, then I fear we're doing something that won't scale. (tl;dr: I worry we are ad-hoc'ing the rules because I can't find the underlying genralization).

The problem seems to come with `FutureOr`, not nullability.
We have a union of `T` with `Something<T>`. That is, both `T` and a further restriction on `T`.
The nullable case is `T|Null` where the `Null` does not contain `T`, making it different.

The current rules say:
> If matching `FutureOr<S>` against `FutureOr<T>`, match `S` against `T`.
>
>If matching `FutureOr<S>` against `T`, match `Future<S>` against `T`, `S` against `T`, and union the constraints.
>
>If matching `S` against `FutureOr<T>`:
>  - If matching `S` against `Future<T>` succeeds and produces 1 or more constraints, then we're >done.
>  - If matching `S` against `Future<T>` failed, or produced no constraints, then we try matching `S` against `T`

(Where "matching `A` against `B`" means solving  `A <: B`, as I read the following example).

Then matching `FutureOr<X>` against `Future<int>` will match `Future<X>` against `Future<int>` and find the constraint `X <: int`, and match `X` against `Future<int>` and find `X <: Future<int>`. Then union the constraints, which seems to give us `Never` ... which is correct. Yey.

The odd thing happens when the union is on the RHS.

Solving `Future<X> <: Future<T>|T` prefers checking `Future<X><:T` first. That seems reasonable, but what is the underlying generalizable reason for that?

Is it that we prefer exact structural matches first? Because `Future<X>` and `Future<T>` both start with `Future`, we prefer that over the one which doesn't?
Probably not, because it doesn't apply to `Future<X> <: Future<Future<int>>|Future<int>`. The rules above would solve that with `X <: Future<int>`.

For `X|Future<X> < T|Future<T>` we do structural matching to match `X` against `T` and `Future<X>` against `Future<T>`. That's only possible because `FutureOr` is so specific.
For more general unions like `Null|X|Future<X> <: Nul||int|Future<int|Null>`, it's not as clear-cut.
(Thats `FutureOr<X>? <: FutureOr<int?>` which can be solved by `X <: int`).

Is it that when one term of a union is a subterm of another, we prefer the other?
Seems more like a rationalization, not something I can find a good reason for.

(So, I'm obviously not a type theorist, just someone who prefers things general and orthogonal.)

**Comment by leafpetersen** [comment]
> (Where "matching `A` against `B`" means solving `A <: B`, as I read the following example).

More or less.  The matching algorithm `A <# B` parallels subtyping, but one side of the subtyping may have variables that we are solving for.  So whereas in subtyping, `int <: X` where `X` is a type variable will never be true, in the matching algorithm, we treat `T <: X` as generating a constraint on `X` iff `X` is in the set of variables that we are solving for.  

To your question - I thought about it a bit more over coffee the other day.  Here's some notes that might help?  Your cross-product algorithm is not really right from first principles.  If we think of it from first principles, we should start from subtyping.  If we have a union type on the right hand side of a subtyping query, it doesn't matter what's on the left (modulo some trivial axioms).   This is the point of lemma 1 [here](https://github.com/dart-lang/language/blob/master/resources/type-system/subtyping.md).  So from first principles, we would have:

  - `A | B <# C` yields constraint set `S1 U S2` if
     - `A <# C` yielding constraint set `S1`
     - `B <# C` yielding constraint set `S2`

In our implemented algorithm, this is *almost* what we do, except that when `A | B` is `FutureOr<S>` and `C` is `FutureOr<T>`, we go directly to `S <# T`.  This is probably not important, we could probably change our algorithm to just do the first principles thing.  I think the situations in which it matters are extremely rare - see the Note from @fishythefish in the subtyping document for an example where it probably is observable.

So the only remaining case is `A <# B | C` where `A` is **not** a union type.  In this case, the current algorithm does the thing that you don't like: it tries one of them, if it fails, tries the other, but if it succeeds heuristically decides whether to try the other too.  I don't know quite what to say about this.  The subtyping rule is disjunctive: it has a choice point where you may be able to succeed in multiple different ways.  We could choose to require that you collect all of the possible constraints.  That is, we could have the rule:
  - `A <# B | C` succeeds with constraint set S2 if 
       - `A <# B` succeeds with constraint set S2 and `A <# C` fails
       - `A <# C` succeeds with constraint set S2 and `A <# B` fails
       - `A <# B` succeeds with constraint set S0 and `A <# C` succeeds with constraint set S1 and `S2 = S1 U S0`.

I don't actually have a good example to hand as to why to prefer our current algorithm to this.  For our existing union types, it's either unlikely that both succeed unless `A` is a bottom type, or unlikely that `C` contributes anything interesting (if `C` is a bottom type).

So maybe we should use this algorithm instead?  I don't have good intuition here.

**Comment by leafpetersen** [comment]
Thinking about this in terms of general union types, if we use the "first principles" algorithm, we'd see this difference if we had a problem that looked like:  `int <# S | T` where we were solving for `S` and `T`.  The current algorithm would choose one side of the union (we'd have to decide the criteria for how it chose) and produce something like `S == int` and `T` unconstrained.  The "first principles" algorithm would produce `S == int` and `T == int` which is also a reasonable solution, but not necessarily a better one.  In an ideal world, you might generate a constraint that looks like `int <: S <: ? || int <: T <: ?` leaving yourself the ability to choose later on which constraint to use (e.g. if something else constrains `T` to be an incompatible type).  Basically, I don't know how inference would work with general union types.  

Here's an example of code that would run into the above, where I'm using `Or<S, T>` to be syntax for `S | T`:

```
void foo<S, T>(Or<S, T> x, Or<S, T> y) { ... }
void test() {
  foo(3, 3.0);
}
```
The first principles algorithm would choose `num` for both `S` and `T`, which doesn't seem what we want.  I don't know how to do better in general though.  There's probably some prior art we should look at if/when we get there.

**Comment by lrhn** [comment]
I can see the issue. If we try to be completely general, we may get into situations where there are multiple unrelated valid solutions. There are almost always multiple solutions (`int <# X` can be solved by many types for `X`), and we choose the *most specific* one.

With `int <# S|T`, both `S=int,T=Never` and `S=Never,T=int` are "most specific" solutions (there is no solution which is more specific than both).
For solving both `int <# S|T` and `double <# S|T`, both `S=int,T=double` and `S=double,T=int` are most specific solutions. And so are `S=num,T=Never` and `S=Never,T=num`, which are unrelated to each other and the prior ones.

Feels like nondeterminism, and we don't have an oracle, so we'll have to make do with some heuristics. The characteristics of that should be that it is predictable by users and useful in most common cases.

Since we only have two unions now, we can tune the heuristic to that, but that might hurt us in the long run, if we ever get real union types (so let's not do that!)

Fabulating, maybe we need some kind of "quality" score for each match. Something which discourages "trivial" matches, so that a structural match gets a higher score than something just matching a type variable directly.
And maybe matching both sides of a union gets a better score than something using only one (so `S=int,T=double` is better than `S=num,T=Never` above, but still need a tie-breaker with `S=double, T=int`).

If so, that might explain why we are checking `Future<X>` before `X`.

**Comment by johnniwinther** [comment]
Maybe it is lost in the text but I have no clue what it is that I should do for the case of `S? <: T?` and whether `Null <: T?` is the same as `Never? <: T?` in which case it matches `S? <: T?`.

**Comment by johnniwinther** [comment]
@leafpetersen: Could you clarify the question above?

**Comment by leafpetersen** [comment]
> @leafpetersen: Could you clarify the question above?

@johnniwinther 

This [comment](https://github.com/dart-lang/sdk/issues/41447#issuecomment-615510672)  is the current algorithm.  Specifically:

> If matching `S?` against `T?`, match `S` against `T`.
> Otherwise, if matching `S?` against `T`, match `S` against `T` and `Null` against `T` and union the constraints.
> Otherwise, if matching `S` against `T?`:
> 
> * match `S` against `T`.  If this succeeds, and yields at least one constraint, return that constraint set.
> * Otherwise match `S` against `Null` and return the result.

To your follow up:

> and whether `Null <: T?` is the same as `Never? <: T?` in which case it matches `S? <: T?`.

No they aren't the same, and it doesn't.  You know what - I'm going to just bang out a spec for this, there are too many corners.  I'll have it by end of (my) week.

**Comment by leafpetersen** [comment]
@johnniwinther specification proposal [here](https://github.com/dart-lang/language/pull/957) .
