### ISSUE TITLE
Code completion support for Flutter @macros

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#41444]
The code completion help for a symbol does not use the substituted `@macro` text for Flutter elements. Flutter defines `@macro` text in elements in their dartdoc and then references the text in the docs for other elements (a simple textual substitution).

There is support for `@macro` substitution in hover text, but not for code completion docs.

**Comment by devoncarew** [comment]
@bwilkerson - is this something you could take on?

Do you have a sense whether this would have any performance cost - something to be aware of, or likely a non-issue?

**Comment by bwilkerson** [comment]
Yes, I'll take a look at it.

I don't know what the cost is, but (if we haven't already done so) we should be able to write it such that if the data we need in order to perform the substitution isn't already available we will just degrade to not performing the substitution rather than wait for the data. The substitution itself is a simple string manipulation, so it shouldn't be expensive.

**Comment by bwilkerson** [comment]
https://dart-review.googlesource.com/c/sdk/+/143322

Let me know if you find any cases that were missed, but to the best of my knowledge macros should now be getting substituted correctly.
