### ISSUE TITLE
Code complete top-level declarations in not-yet-imported libraries

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#41516]
Given the following code (cursor marked with a caret):
```
var value = math.^
```
it would be nice for code completion to recognize that `math` might be the name of a library and to provide suggestions for top-level names within that library, adding the import for that library as part of the completion.

**Comment by bernaferrari** [comment]
I have the same issue with Vector3, I can't type `final Vector3 vector = ...`. I need to import dart 64 vector file first, which is very weird for those that never seen it before. When I needed a Quaternion I was like... where does that come from? Let me google it to find the correct import file.

**Comment by srawlins** [comment]
@bwilkerson did you have a notion of what would trigger this? E.g. just words that would be a valid `dart:*` library? Or even other packages, like `path.` would offer to auto-import `package:path/path.dart`?

**Comment by scheglov** [comment]
I believe this feature was implemented, the server suggests not yet imported libraries.
<img width="611" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/33b99475-b97e-4e36-b308-17125f41f4d0">

I will consider the original request, to infer `dart:math` import from `math.^`, not as a issue to solve, but as a proposal of a solution, where the actual problem is suggesting not yet imported elements.
