### ISSUE TITLE
Future.delayed rejects `null` computation in weak mode

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#41526]
The Null Safe ported sdk has the following error checking code:

```dart
  factory Future.delayed(Duration duration, [FutureOr<T> computation()?]) {
    if (computation == null && null is! T) {
      throw ArgumentError.value(
          null, "computation", "The type parameter is not nullable");
    }
```

This is reasonable code for the final null safe SDK, but for weak mode compatibility it's a breaking change since `null is T` will fail in weak mode in places where `null as T` will succeed.  This check should either be eliminated, or rewritten to only fire in strong mode.

cc @lrhn

**Comment by leafpetersen** [comment]
cc @vsmenon @sigmundch @a-siva @davidmorgan this is the cause of one of the presubmit failures.

**Comment by lrhn** [comment]
This is probably going to be happening a lot, so we should have some reusable way of testing "T is nullable or legacy", at least something simpler than assigning `null` and catching the error.

The simplest approach I can see is:
```dart
bool allowsNull<T>() => const <Null>[] is List<T>;
```
Any better suggestions?

In this situation, we could perhaps just do the throwing:
```dart
FutureOr<T> result;
if (computation == null) { 
  result = null as dynamic; // Throws a TypeError if not allowed.
} else {
  result = computation();
}
```
The user will not get as explanatory an error, and since the argument constraint is as complex as it  is, that's probably not good.
(I hope we can eventually get rid of all these "allows omitting parameter only when type parameter is nullable" cases, but that probably won't happen until we get overloading).

**Comment by crelier** [comment]
As a quick fix for now, I simply replaced
`null is! T
`
with
`const <Null>[] is! List<T>
`
which should be pretty efficient and which keeps the current explanatory error.
CL is here: https://dart-review.googlesource.com/c/sdk/+/143840

**Comment by leafpetersen** [comment]
@crelier Thanks for the fix.  I see the same pattern used in stream.dart as well, would you mind including the fix for that in your CL?

**Comment by crelier** [comment]
@leafpetersen good point! Done.
