### ISSUE TITLE
Add packages shipped with and depended on by the Flutter SDK to the null safety allow list

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41538]
Packages that ship in an SDK/framework need to be in an allow list so they can have null safe syntax and not crash users

Flutter:
- [x] dart:ui (assuming this is already handled?)
- [x] pkg:flutter
- [x] pkg:flutter_test

Used by pkg:flutter

- [x] pkg:meta
- [x] pkg:collection
- [x] pkg:typed_data
- [x] pkg:vector_math

**Comment by mit-mit** [comment]
I think we need to whitelist a few more (basically the primary deps of the output of `flutter create`)?

**Comment by kevmoo** [comment]
> I think we need to whitelist a few more (basically the primary deps of the output of `flutter create`)?

Yup, @mit-mit – I'll expand this

**Comment by jakemac53** [comment]
We need to make sure this is done in such a way that it works when _analyzer_ is used as a package as well, so we don't break all code generation again, see https://github.com/dart-lang/sdk/issues/41820 for context.

**Comment by johnniwinther** [comment]
I guess that this list will have to be baked into the snapshots so that it'll work without an sdk, right? We don't expect anyone to pass the path to this list in through the command-line, right?

**Comment by jakemac53** [comment]
Interesting point, does this matter past the point of the creation of the snapshot? For instance I don't think the `.packages`/`package_config.json` files are needed any longer after that point. All the required info could be baked into the snapshot itself.

**Comment by johnniwinther** [comment]
If we embed the allow list into the snapshot we will _always_ consider the mentioned packages as having the experiments enabled. This means that if you compile one of the mentioned packages from source, even older versions of the source, we will interpret them as being opted-in by default.

If we do _not_ embed the allow list into the snapshot we will only consider the mentioned packages as having the experiments enable if the allow list is passed directly from the tools. This means that if you compile one of the mentioned packages from source we will _not_ interpret them as being opted-in and flag errors if null safety syntax is used.

The `dart:` libraries are special because we only compile them from source when we build the sdk (and pass an explicit `--enable-experiment=non-nullable` in this step). For the other libraries (I guess) we always compile from source and therefore need to ensure that we enable experiments by default - either by hard-wiring this in the snapshot (i.e. in the CFE code) or by always passing the allow list to the CFE through our tools.

**Comment by jakemac53** [comment]
Ah, I misunderstood you I think. Are you referring to the snapshots that are shipped with the SDK for the tools themselves? Or user app snapshots?

**Comment by franklinyow** [comment]
@kevmoo What's the status?  Thx

**Comment by kevmoo** [comment]
Most of these were landed in https://github.com/dart-lang/sdk/commit/e7218354a877bb6696edb176454b035d900464d0

@jakemac53 – did we exclude `flutter_test` intentionally?
@yjbanov – is `flutter_test` needed for TP2?

**Comment by jakemac53** [comment]
If `flutter_test` is not included then that was definitely an oversight and it should be added

**Comment by jakemac53** [comment]
https://dart-review.googlesource.com/c/sdk/+/153061

**Comment by franklinyow** [comment]
Are we done with this one?

**Comment by kevmoo** [comment]
I believe so! CC @jakemac53

**Comment by jakemac53** [comment]
yes they should all be added
