### ISSUE TITLE
Analyzer should detect an unused public method of a private extension

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41592]
Take this code:

```dart
extension _F on List {
  int m() => 7;
}
```

Any way I figure it, no code outside this library can call `m`, right? It should be reported as `unused_member`. Ditto for an unused public method on an unnamed extension.

**Comment by lrhn** [comment]
> Any way I figure it, no code outside this library can call m, right? 

Correct.

In order to invoke a member on an extension, both the extension and  the member must be accessible at the invocation point. If either is library private, the extension method can only be used from inside the same library. Unnamed extensions are library private (they are effectively given a fresh private name).
