### ISSUE TITLE
provide information about the scripts that were reloaded during a hot reload

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#41668]
As part of the VM service's `IsolateReloaded` event, it would be nice to get information about the scripts there were reloaded during the reload. This will allow debuggers to invalidate cached data, and / or re-query for new data for those scripts.

Currently the `IsolateReloaded` event only contains a string 'status' field (`'The status (success or failure) related to the event'`).

With info about the new or reloaded scripts, a debugger could:
- update it's list of all the scripts in an app
- re-query for source report info for the script (all the breakable lines)
- re-query for the source for the script, to show the updated source to the user (instead of the previous source)

I'm assuming that the old scripts will still be valid, and that there would just be new scriptRefs, with new IDs, but that would share script uris with the older scripts.

cc @bkonyi

**Comment by bkonyi** [comment]
cc @kenzieschmoll now that @devoncarew isn't focusing on DevTools work these days.

I finally had a chance to look into this, and I'm not sure any information we can provide would improve our ability to cache script references in tooling. AFAIK, we don't differentiate between scripts with code structure changes vs whitespace / comment changes. Also, scripts that depend on modified scripts are also considered to be reloaded, further muddying the concept of what's actually been changed.

It might be worth revisiting this if we have actual performance issues when we make `getScriptList` requests to repopulate the cache, otherwise the simplest thing to do is just rebuild the cache when necessary.
