### ISSUE TITLE
"expression compilation error" when evaluating expression if it ends in semicolon

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#41671]
When debugging, if you highlight an expression in VS Code and run "Evaluate in Debug Console", the evaluation will fail if the code ended with a semicolon (which is very easy to do if you're just highlighting a bunch of lines):

<img width="600" alt="Screenshot 2020-04-27 at 12 46 53" src="https://user-images.githubusercontent.com/1078012/80368852-4baedb80-8885-11ea-8331-e05515104ca5.png">

We could trim this off in VS Code before evaluating, but the same is likely the case for other editors, DevTools etc. so it would probably be better if the VM handled it itself.

**Comment by mraleph** [comment]
I am a bit on the wall whether it is a front-end or service protocol issue. Front-end is rather faithful here - it expects to get an expression, but you give it a semicolon terminated statement.

Should front-end be more lenient or should service just strip trailing semicolon? 

Any opinion @jensjoha @bkonyi ?

**Comment by jensjoha** [comment]
From my perspective, the front-end is asked to compile an expression and does exactly that.
What likely happens is that we do compile the expresion, then check if there's more input content (which there is, the ';') and give an error on that. If we didn't report an error we'd arbitrarily swallow errors which is probably not a good idea.

My take would be that no one should remove the semicolon, but that the message in the client (VSCode in this case) should be improved (which would also improve the thing in general).

Instead of saying `113 expression compilation error` it should say something like
```
113 expression compilation error: Unexpected data at position y:
bla bla bla;
           ^
```

something that it already does if doing it via observatory btw:
```
$ p x;
{details: org-dartlang-debug:synthetic_debug_expression:1:2: Error: Expected one expression, but found additional input.
x;
 ^}
```

**Comment by DanTup** [comment]
> My take would be that no one should remove the semicolon, but that the message in the client (VSCode in this case) should be improved

VS Code is just showing the error from the VM, so if it was to be improved it needs to come from the VM (I can't assume "expression compilation error" always means an unexpected trailing semicolon).

However, showing an error for this feels like an awkward experience for the user - they can't just highlight or copy/paste a full line of code and evaluate it. Doing the same thing in other languages in VS Code (and also the Chrome DevTools) ignore trailing semicolons:

<img width="227" alt="Screenshot 2020-04-28 at 12 15 31" src="https://user-images.githubusercontent.com/1078012/80481272-07394380-894a-11ea-8e5d-3fcf240437fb.png">

If there's reason not to do it in the SDK, I'd probably prefer to trim it off in VS Code instead. Doing it here feels like it'd improve the other editors too though.

**Comment by mraleph** [comment]
@DanTup JavaScript devtools evaluate statements rather than expressions - hence the difference.

In JavaScript when you evaluate statements the result of that is usually the value of the last expression statement in a sequence (more or less, reality is complicated).

So you can't really compare JavaScript and Dart evaluation requirements here.

**Comment by jensjoha** [comment]
> > My take would be that no one should remove the semicolon, but that the message in the client (VSCode in this case) should be improved
> 
> VS Code is just showing the error from the VM, so if it was to be improved it needs to come from the VM (I can't assume "expression compilation error" always means an unexpected trailing semicolon).

The observatory prints the details. From listening in on the /ws:
```
(send) {"jsonrpc":"2.0","id":"51","method":"evaluateInFrame","params":{"frameIndex":0,"expression":"x;","disableBreakpoints":false,"isolateId":"isolates/2938419529673859"}}

(received) {"jsonrpc":"2.0","id":"51","error":{"code":113,"message":"Expression compilation error","data":{"details":"org-dartlang-debug:synthetic_debug_expression:1:2: Error: Expected one expression, but found additional input.\nx;\n ^"}}}
```

**Comment by DanTup** [comment]
> JavaScript devtools evaluate statements rather than expressions - hence the difference.

Sure, my comment was more about the user expectation. It feels like an unnecessary penalty for highlighting code ending with a semicolon (which is far easier than to trim it off).

If it doesn't make sense here, I'll trim it in VS Code though. I don't think there are any situations were removing a trailing semicolon would cause an otherwise valid request to be invalid.

> The observatory prints the details

Oops, my bad - I didn't realise there was extra info there. I'll look at exposing the more friendly error in other situations where we're normally just showing "Expression compilation error". Thanks!
