### ISSUE TITLE
Declaring and edit List and Map

### ISSUE THREAD

**Issue by yusukeinouehatchout** [dart-lang/sdk#41682]
```
  void test1() {
    List<int> emptyList1 = [];
    List<int> emptyList2 = [];

    emptyList2.add(0);

    print(emptyList1.length); //0
    print(emptyList2.length); //1
  }

  void test2() {
    List<int> emptyList1 = [];
    List<int> emptyList2 = emptyList1;

    emptyList2.add(0);

    print(emptyList1.length); //1
    print(emptyList2.length); //1
  }
```
Access to emptyList2 then access to emptyList1 in test2.
Is this a rule?
I was able to confirm the same phenomenon using Map.

**Comment by mraleph** [comment]
Variables contain _references_ to Dart objects, so two variables can point to the same object: in your example in `test2` both `emptyList1` and `emptyList2` point to the same object. 

In general I recommend asking such questions on Stack Overflow or other support channels instead of filling an isssue.
