### ISSUE TITLE
Get version or other info from pubspec.yaml after compile to native (AOT)

### ISSUE THREAD

**Issue by qholi** [dart-lang/sdk#41716]
Dart VM version: 2.7.2 (Unknown timestamp) on "linux_x64" (WSL)
Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "windows_x64"
Windows 10 , WSL Ubuntu 18.04
dart2native

Since "package:yaml::loadYaml" and "dart:io::File" is a runtime function that means I can load "pubspec.yaml" using those with "dart:io::Platform.script.path" and "package:path::dirname" in dart VM without any problem. But after I compile the program with "dart2native", the "pubspec.yaml" is not attached. So can I have another way to collect particular information? Or need to put the info as constants or variables manually at this moment to solve it?

Thanks.

**Comment by mkustermann** [comment]
@qholi Could you give a concrete example with the issue you're having?

Generally AOT compilation will compile from Dart sources that have package structure to a single file. The package structure is lost at this point. This is not specific to `dart2native` but AOT compilation in general.

The flutter framework (which calls our AOT compiler internally) has a build system (which bundles the AOT compiled app together with assets) and assets abstractions (which knows where the build bundling step put the assets) that take care of this.

When using our AOT compiler directly (e.g. via `dart2native`) it is the users responsibility to do bundling of AOT app + assets and making the code aware how assets can be located.

**Comment by mkustermann** [comment]
As explained above, the fact that package structure is lost after AOT compiling is intentional and we have right now no plans on changing that. Any kind of assets the AOT-compiled application needs it might need to bundle together with the AOT compiled application.

Making a build system (which compiles the Dart application to an AOT binary as well as finding all needed asset, bundling them and making them available to the AOT-compiled application at runtime) is out-of-scope for `dart2native`.

I hope it's all right if I close this issue.
