### ISSUE TITLE
Instantiate-to-bounds works in different ways in dart and analyzer with non-function typedefs

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41719]
Dart VM version: 2.9.0-4.0.dev (dev) (Tue Apr 28 09:41:22 2020 +0200) on "windows_x64"

Source code example below demonstrates the problem:
``` dart
class A<X extends A<X>> {}
typedef B<X extends A<A<X>>> = A<X>;

main() {}
```
Dart passes with this without any error or warning whereas analyzer throws a compile error.

Both tools should work in a similar way.

Sample output is:

> $> dartanalyzer --enable-experiment=nonfunction-type-aliases test.dart
> Analyzing test.dart...
>   error - 'A<X>' doesn't extend 'A<A<X>>'. - test.dart:2:23 - type_argument_not_matching_bounds
>   error - 'X' doesn't extend 'A<X>'. - test.dart:2:25 - type_argument_not_matching_bounds
>   error - Invalid generic function type. - test.dart:2:30 - invalid_generic_function_type
> 3 errors found.
> 
> $> dart --enable-experiment=nonfunction-type-aliases test.dart 
> $>
>

**Comment by iarkh** [comment]
Here is another similar example which produces `Invalid generic function type` error with analyzer and passes with dart:
``` dart
class M<X> {}
class N<X extends M<N<X>>> {}

typedef O<X extends M<O>> = M<N<X>>;

main() {}

```

**Comment by eernstg** [comment]
I think we shouldn't create issues about the behavior of the analyzer on programs using non-function type aliases at this point, because there is absolutely no support for this feature in the analyzer today. We'd just get a long list of "the analyzer doesn't handle X" for a bunch of "X" that rely on non-function type aliases, and it wouldn't help anybody.

**Comment by keertip** [comment]
Closing as there is nothing actionable here.
