### ISSUE TITLE
What dart defines are expected to be set for a kernel target?

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#41764]
Currently flutter relies on a bit of  hack to determine whether or not it is running on the web: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/constants.dart#L49

This has prompted multiple calls for rewrites. One of the suggestions was to use `bool.fromEnvironment('dart.library.html')` (setting aside the fact that the tool could set its own `dart.vm.web` constant for now).

As far as I can tell though, nothing in the language spec documents that each supported dart library will have a corresponding `dart.library.<libname>` define constant. In fact, the dartdevc kernel target does not set these, while the VM/Flutter targets do.

Should all kernel targets be setting these values? Are there tests that validate that they are set by each target?

More context:

- https://github.com/flutter/flutter/issues/50765
- https://www.reddit.com/r/programminghorror/comments/gcyiz6/how_flutter_knows_if_the_app_is_running_on_web_or/

**Comment by natebosch** [comment]
cc @leafpetersen @lrhn - should `bool.fromEnvironment('dart.library.*')` be put in the spec somewhere?

**Comment by rakudrama** [comment]
`bool.fromEnvironment('dart.library.html')` is also a hack and would go away if the flutter web bindings were written entirely with JS-interop. I expect that the number hack will be more stable.

The VM defines `bool.fromEnvironment('dart.isVM')`.
We could arrange that some other values are defined on other targets.

**Comment by leafpetersen** [comment]
The spec doesn't generally specify what things are made available to the fromEnvironment constructors.  Is there an argument for specifying these, instead of making them tool specific?

**Comment by natebosch** [comment]
> Is there an argument for specifying these, instead of making them tool specific?

I think mostly that if they are tool specific flutter is less likely to use them for fear of inconsistencies.

**Comment by jonahwilliams** [comment]
Another case is that if someone wrote a dart package against the dart vm or dart2js (without flutter) and relied on the existence of one of these values, they might end up filling an issue against the Flutter SDK if they find that it is unset when we compile their code.

To resolve that issue, we might look for recommendations or a specification on when these values should be set.

**Comment by jonahwilliams** [comment]
In this case the advise might need to be "you can't rely on those values they are tool specific" - which is completely fine too.

**Comment by leafpetersen** [comment]
> In this case the advise might need to be "you can't rely on those values they are tool specific" - which is completely fine too.

To be clear (which I wasn't), when I say "tool specific" I don't mean "different Dart team supported tools do different things", I mean "the language doesn't require a conformant implementation to do anything specific, but all Dart team supported tools will do one consistent, documented thing".

This is what we do with config specific imports, for example.  The language says that config specific imports exists, the tools and build system decide what set of configurations they will support.

**Comment by jonahwilliams** [comment]
Ahh, yes - In that case I would agree that doing a consistent, documented thing would ideal. It doesn't particularly matter to me where that documentation lives, provided that it is reasonably discoverable.

**Comment by sigmundch** [comment]
> `bool.fromEnvironment('dart.library.html')` is also a hack and would go away if the flutter web bindings were written entirely with JS-interop.

I should clarify here that this is not the case. Conditional imports and these fromEnvironment variables are consistent with each other. Which libraries are supported (and as a result which `fromEnvironment` values exist) is directly derived from the libraries.json file on CFE-based tools (vm, ddc, and dart2js). Even if the code doesn't use `dart:html`, `bool.fromEnvironment('dart.library.html')` will continue to be true on the web and false on the vm.

Also note that we also have `dart.library.js` which is preferred given that it is also defined for server-side JavaScript (like node.js).

**Comment by lrhn** [comment]
The only environment variables that are specified generally are the `dart.library.x` which correspond to the availability of `dart:x` in the current compilation.

The configurable imports are loosely defined in the specification so that particular implementations can restrict which environment variables they support switching on. 
The original design allowed *any* environment define to be used, but that didn't work out with modular shared compilation, like what we do inside Google. Our build system needed a fixed set of configurations in order to be able to share compilation artifacts.

We can add more (like `dart.numbers.int64` to signify that the target platform has 64-bit integers, so we can do conditional imports in the `fixnum` package). I've been arguing for `dart.runtime.debug` as well, as a way to check whether assertions are enabled (something you can check anyway, but not as a constant). These are all things that can be determined ahead of time for a particular Bazel compilation target.

The `dart.isVM` is not specified anywhere. It's just something the VM has added, and something I'd prefer removing again. Probably because I've experienced platform detection vs feature detection in JavaScript, and feature detection is generally the thing to go for. Deriving secondary properties from something being "the VM" is not sound since the VM can change, and other platforms can be created.

**Comment by joshualitt** [comment]
I'm going to close this discussion because it seems to have run its course. Please file bugs if there were any action items that slipped through the cracks.
