### ISSUE TITLE
language/extension_methods/static_extension_getter_setter_conflicts_test is failing

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#41778]
[The log](https://dart-ci.appspot.com/log/analyzer-nnbd-linux-release/analyzer-asserts-strong-linux/2640/language/extension_methods/static_extension_getter_setter_conflicts_test).

See the reduced test code.

```dart
class C<T> {}

extension E1<T> on C<T> {
  int get foo => 0;
}

extension E2 on C<Object?> {
  set foo(int x) {}
}

void test1() {
  var c1b = C<Object>(); // Neither extension is more specific.
  c1b.foo;
}
```

I think there is not error here. @munificent @eernstg 

According to [the spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#specificity) `C<Object>` is more specific than `C<Object?>` because `C<Object> <: C<Object?>` and not vice versa.

**Comment by eernstg** [comment]
I agree that `C<Object>` is the more specific instantiated `on` type, so the chosen extension member should be `E1<Object>.foo`, and there is no error.

I suspect that this test was migrated in such a way that the specificity changed (a quick check in `language_2` supports this), and it should simply have been `var c1b = C<Object?>();` in `main`.

With that, the extensions are equally specific (both when considering the instantiated `on` types, and when considering the instantiation to bound of the `on` types), so there is an ambiguity error.

That again is caused by the fact that applicability is determined using the basename of the member which is being accessed, that is, we strip the `=` off of the setter name and search for anything named `foo` in both `E1` and `E2`.

I think the best way to proceed is simply to add that missing `?`.

Of course, it could also be useful to test the case where we preserve the difference in specificity:

```dart
class C<T> {}

extension E1<T> on C<T> {
  int get foo => 0;
}

extension E2 on C<Object?> {
  set foo(int x) {}
}

void test1() {
  var c1b = C<Object>();
  c1b.foo = 1; // Error
}
```

Here, an error occurs because both `E1` and `E2` are applicable, but `E1` is more specific, and it doesn't have a setter.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/146963
