### ISSUE TITLE
NNBD: Analyzer throws unexpected error for CHECK_TOP_MERGE.f (Never Function(Never) Function()), A_OUT.f (Null* Function(Null*)* Function()*)

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41804]
Dart VM version: 2.9.0-5.0.dev (dev) (Thu Apr 30 13:02:02 2020 +0200) on "windows_x64"

The following source code example passes with dart and throws a compile error with analyzer:
**test_out_lib.dart:**
``` dart
// @dart=2.6
class A_OUT<T> { T Function(T) get f => throw "1"; }
class out_Never extends A_OUT<Never> {}
```
**test.dart:**
``` dart
import "test_out_lib.dart";

class CHECK_TOP_MERGE<T> { T Function(T) get f => throw "2"; }
class B extends CHECK_TOP_MERGE<Never> {}

class C1 extends B implements out_Never {}

main() {}
```
Sample output is:

> $> dartanalyzer --enable-experiment=non-nullable test.dart
> Analyzing test.dart...
>   error - Superinterfaces don't have a valid override for 'f': CHECK_TOP_MERGE.f (Never Function(Never) Function()), A_OUT.f (Null* Function(Null*)* Function()*). - test.dart:6:7 - inconsistent_inheritance
> 1 error found.
> 
> $> dart --enable-experiment=non-nullable test.dart
> $>

Seems like both tools should behave in the similar manner here.

**Comment by eernstg** [comment]
Note that the error arises because `Never` is treated as `Null` in the legacy library 'test_out_lib.dart'. This is consistent with the nnbd specification, but dart-lang/language#825 proposes to stop doing that (which means that `Never` in a legacy library just means `Never*`, which will make this error go away). That behavior seems meaningful to me, but the proposal to reconsider this may or may not get support from the rest of the language team.

**Comment by eernstg** [comment]
FYI: dart-lang/language#825 concluded that `Never` in a legacy library simply means `Null*`.

**Comment by scheglov** [comment]
I discussed this error with the language team, who decided that it WAI, as a result opened https://github.com/dart-lang/co19/issues/706, and the test was fixed.
