### ISSUE TITLE
armv7 SDK builds are missing analysis_server.dart.snapshot

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#41845]
This was raised by @igotyou at https://github.com/Dart-Code/Dart-Code/issues/2445

If you download the Linux SDKs from here:

https://dart.dev/tools/sdk/archive

The ARMv8/ARM64 one contains the `bin/snapshots/analysis_server.dart.snapshot` file, however the ARMv7 file does not. VS Code requires this file to run the language server (for example if you use VS Code's Remote support, you will SSH over to the Pi and all SDK code will run on the Pi).

**Comment by srawlins** [comment]
@whesse sorry this was not in the `area-build` bucket. Is `area-build` the correct bucket?

**Comment by mit-mit** [comment]
cc @athomas is this something we can fix?

**Comment by athomas** [comment]
@dcharkes this seems to be because of some historic limitation of FFI on 32bit ARM, do we still have that limitation (see https://dart-review.googlesource.com/c/sdk/+/111314)?

Also, I'm not sure if analysis server still has the FFI dependency (I think that might have been for TF lite).

The fix would be to remove some of these "not arm" conditions in the build files:
https://github.com/dart-lang/sdk/blob/e7644d9a4c6f400680206f6d03135f24d0480052/BUILD.gn#L36
https://github.com/dart-lang/sdk/blob/e7644d9a4c6f400680206f6d03135f24d0480052/sdk/BUILD.gn#L154

**Comment by dcharkes** [comment]
FFI works on all target architectures except for simulators (simarm simarm64 simarm_x64). So no limitation for arm32.

**Comment by lgLindstrom** [comment]
I'm unable to see if there is a solution or patch to solve this issue ??

**Comment by mit-mit** [comment]
@athomas

**Comment by athomas** [comment]
https://dart-review.googlesource.com/c/sdk/+/191922
