### ISSUE TITLE
Editor hovers no longer show default values for parameters

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#41844]
Raised by @miguelpruivo at https://github.com/Dart-Code/Dart-Code/issues/2442. In the most recent SDK, hovering over a function/method no longer shows default parameter values:

<img width="597" alt="Screenshot 2020-05-11 at 15 10 55" src="https://user-images.githubusercontent.com/1078012/81571536-fbae3980-9399-11ea-9075-ac630567cc75.png">

I think this may have happened in 39f14a000e50995711168a115a7af0c83d5f9542, with the default previously coming from here:

https://github.com/dart-lang/sdk/blob/af1ba835da91c88caa6b2ee67aebafe8f1053d48/pkg/analyzer/lib/src/dart/element/element.dart#L6929-L6932

**Comment by bwilkerson** [comment]
@scheglov Was this an intentional change, and if so, what was the motivation?

**Comment by DanTup** [comment]
I have a possible fix here (assuming it wasn't intentional):

https://dart-review.googlesource.com/c/sdk/+/147549/

However, I'm unsure about the changes it resulted in driver_resolution_test as those were not changed in the change above (but it might be that they were already using the new code that didn't include the defaults).

**Comment by scheglov** [comment]
The change was not intentional, most probably I copied the code for writing parameters from `FunctionType`, where we don't want default values (which also explains the change in `driver_resolution_test `). But for display strings on `ExecutableElement`s we do want them. So, `ElementDisplayStringBuilder` needs an additional flag, like others that are there already, e.g. `withParameterDefaultValueCode`. Then elements will pass it, and types - not.

**Comment by DanTup** [comment]
Makes sense - I've updated https://dart-review.googlesource.com/c/sdk/+/147549/ with a flag and reverted the changes to `driver_resolution_test`. Thanks!

**Comment by DanTup** [comment]
Fixed by 1a328bed36ac5e79a6c9bf6ad5ae73ea27d467c1.
