### ISSUE TITLE
VM: Rename null safety strong mode flag

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#41853]
Currently the null safety strong mode flag is controlled by the flag `--no-null-safety` / `--null-safety`.

From offline discussion, we find that this is suboptimal: When a developer opts out of sound/strong checking with `--no-null-safety` they will still get some null safety (e.g. static analysis), but the flag name makes it sound like they are loosing all of null safety.

We'd thus like to rename this flag to `--no-sound-null-safety` / `--sound-null-safety`.
[Source for --no-null-safety](https://github.com/search?q=org%3Adart-lang+--no-null-safety&type=Code)
[Source for --null-safety](https://github.com/search?q=org%3Adart-lang+--null-safety&type=Code)

**Comment by a-siva** [comment]
I still find the notion of having two flags
--enable-experiment=non-nullable --sound-null-safety
very unintuitive.
It would be a lot more ergonomic if we just had one flag
--enable-experiment=non-nullable
which would strive to run the code in sound null safety mode, if there are any opted out packages in the application it would print a warning stating that because of some opted out packages it will be running in unsound null safety mode.

**Comment by mit-mit** [comment]
The `--enable-experiment` flag is just temporary until we get to beta; then it will go away.

But still a good question to ask if we need that second flag. cc @leafpetersen

**Comment by leafpetersen** [comment]
I think we do need some way for users to override the auto-opt in behavior otherwise they can end up in the following state:
  - Their entry point is opted in
  - Some upstream is dependency is not migrated
  - The only way they can run is to unmigrate their main entry point

We could consider doing this via an annotation or comment in the file though - e.g. `// @nndb=weak`

@lrhn was advocating for the latter.

**Comment by mit-mit** [comment]
I suggest we move this work to beta. Then it will also be less confusing as there is no experiment flag then, so users will never have to use them together.

**Comment by mit-mit** [comment]
@a-siva can we move forward with this?

**Comment by alexmarkov** [comment]
@a-siva I can take a look at this if you don't mind.

**Comment by a-siva** [comment]
go ahead, I have changed the owner field.
