### ISSUE TITLE
No warnings in extension declarations, when there are member name collisions

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#41878]
See this code:

> extension FileSystemEntityExtension on FileSystemEntity {
>   // method name collision with the path field:
>   String path() {
>     return '';
>   }
> 
>   // name collision with the method:
>   bool get existsSync => false;
> }

What's also confusing here is that the analyzer navigation and completion ignores them:

```
f(FileSystemEntity entity) {
  entity.path; //  <-- completes and navigates to lib/io/file_system_entity.dart
  entity.existsSync(); // <-- here too
}
```

@bwilkerson @scheglov

**Comment by bwilkerson** [comment]
I think this is WAI.

When resolving a member `m` against a type `T`, we first look in the type `T` and its supertypes for a definition of `m`. If one is found, we stop. If no member with that name is found, then we look for an extension. So the fact that it's resolving to the members in the class is correct.

The reason there's no diagnostic when colliding is (IIRC) because those members are still accessible via an extension override such as `FileSystemEntityExtension(entity).path`.

**Comment by srawlins** [comment]
I've requested this lint at https://github.com/dart-lang/linter/issues/2130. I think this can be closed.
