### ISSUE TITLE
runtime/vm/compiler/backend/il.h: 999: error: unreachable code

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#41971]
I'm getting the following error when trying to aot compile a specific file:

```
../../runtime/vm/compiler/backend/il.h: 999: error: unreachable code

Failed to generate native files:
Generating AOT snapshot failed!
```

Steps to reproduce:

```
git clone https://github.com/simolus3/moor.git
cd moor/extras/integration_tests/vm/
pub get
dart2native test/vm_test.dart
```

This happens on Dart stable, Flutter stable and Flutter beta.

I know the repro is rather large, but I couldn't find anything smaller. Trying to aot-compile some other test files from the same repo works.

**Comment by alexmarkov** [comment]
FFI intrinsic code (`kFfiLoadPointer`) created `LoadIndexed` instruction which doesn't have deopt_id. That instruction takes unboxed input and flow graph construction ensures that it actually receives unboxed value by inserting explicit `UnboxInt64` instruction.

After some optimization passes `UnboxInt64` was removed by canonicalization as its argument was unboxed already. At that point `LoadIndexed` was taking result of `ShiftInt64Op`, which has unboxed representation. So far everything looks good.

After that, constant propagation replaced `ShiftInt64Op` which has unboxed representation with Smi `Constant` which has tagged representation.

Before:
```
    v18 <- Constant(#1) [1, 1] T{_Smi}
   ...
    v415 <- UnboxedConstant(#8) T{_Smi}
    v394 <- ShiftInt64Op(<< [tr], v415, v18) [-9223372036854775808, 9223372036854775807] T{int}
   ...
    v197 <- LoadIndexed(v193, v394 T{int}) [-9223372036854775808, 9223372036854775807] T{int}
```

After:
```
    v417 <- Constant(#16) T{_Smi}
    ...
    v197 <- LoadIndexed(v193, v417) [-9223372036854775808, 9223372036854775807] T{int}

```

After this transformation SelectRepresentation crashed while trying to obtain deopt_id from `LoadIndexed` in order to insert `Unbox` instruction to convert tagged `Constant` to an unboxed representation, required by `LoadIndexed`.

@mraleph @mkustermann @dcharkes Any ideas how to fix that?

We can probably insert `UnboxedConstant` instructions instead of `Constant` in constant propagation if replacing instructions with unboxed representation. However, `UnboxedConstant` supports only limited set of representations, so we might not be able to use to for unboxed constants in general. But it might be sufficient for this particular case. What do you think?

**Comment by mraleph** [comment]
I actually have this CL https://dart-review.googlesource.com/c/sdk/+/103139 - maybe I should finally land it.

**Comment by alexmarkov** [comment]
@mraleph Great, it looks like rebasing and landing that CL would fix this bug. Do you plan to do that?

In your CL you're inserting `Constant` and then `Unbox` instruction in constant propagation if replacing an instruction with unboxed representation. Why is it better than using `UnboxedConstant` instruction directly? Is this only because `UnboxedConstant` doesn't support all unboxed representations?

**Comment by mraleph** [comment]
I will land my CL.

**Comment by mraleph** [comment]
The reason for not inserting `UnboxedConstant` directly is indeed due to not supporing all representations in the unboxed constant instruction
