### ISSUE TITLE
[vm] out/ReleaseX64/dart --observe doesn't work

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#42004]
For some reason `dart --observe` tries to re-run `../bin/dart` instead of re-running itself. This doesn't work if `dart` is not in the Dart SDK `bin` directory. For example, `dart` is placed into `out/ReleaseX64` directory when building `runtime` target for x64:

```
$ tools/build.py -a x64 -m release runtime
$ out/ReleaseX64/dart test_hello.dart
Hello, Dart!

$ out/ReleaseX64/dart --observe test_hello.dart
ProcessException: No such file or directory
  Command: <skipped>/out/bin/dart --disable-dart-dev --observe=0 --write-service-info=file:///tmp/dart_serviceNVEKWN/service_info.json test_hello.dart
```

@bkonyi Could you please take a look?

**Comment by bkonyi** [comment]
Did you just recently pull @alexmarkov? If so, it might be related to [this CL](https://dart-review.googlesource.com/c/sdk/+/148660). cc/ @jwren

**Comment by alexmarkov** [comment]
@bkonyi No, I had a version from yesterday checked out when I noticed this behavior.

The problem is that dartdev might assume that `dart` is in `bin` directory, but this is not always the case:

https://github.com/dart-lang/sdk/blob/4c78bacd1d5420c768cdf02c0dbff1716757bb40/pkg/dartdev/lib/src/sdk.dart#L43

and before the recent change:

https://github.com/dart-lang/sdk/blob/8423423f850cd03345c68a573d53b087c5cebe03/pkg/dartdev/lib/src/sdk.dart#L42

**Comment by bkonyi** [comment]
Ah right. I'm surprised we didn't run into this sooner, especially since I typically run out of the root build directory as well. I'll take a look, but in the meantime, either run with `dart-sdk/bin/dart` (if you're worried about build times, just use the `create_platform_sdk` target which skips all the web tools) or pass `--disable-dart-dev` to bypass the issue for now.
