### ISSUE TITLE
Generate a .note.gnu.build-id section in the ELF file and DWARF file

### ISSUE THREAD

**Issue by chingjun** [dart-lang/sdk#42020]
(From the discussion in https://docs.google.com/document/d/1HjFIJJSo1pRKo6FH84yafKbeEoSjPOXtFwwZfIeQNM0/edit?disco=AAAAJXYigj8)

Existing tools use debug identifier in `.note.gnu.build-id` section to search for build symbols that corresponds to an existing binary. Dart gen_snapshot should generate this section as well.

The default behavior in breakpad, if this section is not found, is to "locate the .text section of an ELF binary and generate a simple hash by XORing the first page worth of bytes", but in the ELF file that Dart generates, "the first RX page might be often the same because it contains "vm-isolate" stub code which doesn't change very often."

Thanks.

cc @sstrickl @mkustermann

**Comment by chingjun** [comment]
On a related note, it would be beneficial too if there is `DT_SONAME` in the DWARF file.

**Comment by mkustermann** [comment]
@sstrickl Could you take a look at this?

It is probably enough to make a hash out of the contents of  `kDartVmSnapshotData`, `kDartVmSnapshotInstructions`, `kDartCoreIsolateSnapshotData`, `kDartCoreIsolateSnapshotInstructions`

**Comment by chingjun** [comment]
Just a note that the `build-id` should be placed in the `NOTE` segment. Crashpad (the successor of breakpad) is unable to find the `build-id` if it's placed in the wrong segment since it uses the program headers to find the notes.

**Comment by chingjun** [comment]
Hi @sstrickl and @mkustermann , any updates or timeline on this? This is currently the only blocking issue for us on the Dart side now. Thanks!

**Comment by sstrickl** [comment]
Sorry, I was OOO last week, which delayed this a little, but I've got most of this ready now and hope to have it up for review by EOD today, tomorrow at latest.

**Comment by chingjun** [comment]
Thanks for the update!

**Comment by sstrickl** [comment]
Okay, now ELF snapshots and their corresponding separate debug info have matching build IDs. This isn't done for separate debug info for assembly snapshots, because we can't know what the text section contents are for an assembly snapshot ahead of time, due to the BSS offset/relocations which are calculated at assembly time. (Similarly, we also don't add our own build ID to assembly snapshots directly, so the one that's there is still added by the assembler, not by us.)

So I'd try out the ELF snapshot side of things and see if it now fits the bill. As for DT_SONAME, I'm unsure what we'd even put there, since we don't have a standard naming for snapshots. I guess we could try something based on the basename of whatever path was provided for --elf, but oof.
