### ISSUE TITLE
Regular Expression matching methods are inferred as non-nullable even though they can return null.

### ISSUE THREAD

**Issue by Michael35699** [dart-lang/sdk#42035]
This tracker is for issues related to:

* Analyzer

* SDK Version ` Dart VM version: 2.9.0-8.2.beta (beta) `
* Desktop `macOS 10.15.4`

**Comment by lrhn** [comment]
Can you elaborate a little more on which methods are failing, and how you are using them?

**Comment by Michael35699** [comment]
Consider the following program:

```dart

void main() {
  const lines = [
    "Foo",
    "  Bar",
    "  Baz",
    "Quux"
  ];

  final pattern = RegExp(r"^\s{2,}");
  final matches = lines.map(pattern.firstMatch);  // matches is inferred as Iterable<RegExpMatch>

  for (final match in matches) {
    print(match);
  }
  // Output:
  // null
  // Instance of '_RegExpMatch'
  // Instance of '_RegExpMatch'
  // null
}
```

I would assume that RegExp methods such as `firstMatch`, `allMatches` would be inferred to `RegExpMatch?` and `Iterable<RegExpMatch?>` respectively.

**Comment by lrhn** [comment]
The `firstMatch` will return a `RegExpMatch?`, but `allMatches` will actually return `Iterable<RegExpMatch>`. If there is no match, the iterable will just be empty.

You are probably not seeing this yet because the Dart executable you are using is still using non-null safe platform libraries. If you switch to the newest dev-release (2.9.0-11.0.dev), then you can get the benefit of null safe platform libraries.

**Comment by lrhn** [comment]
The type of matches is now correctly inferred as `Iterable<RegExpMatch?>`, and printed as such.
