### ISSUE TITLE
[Analysis Server] Support for LSP semantic tokens 

### ISSUE THREAD

**Issue by ericdallo** [dart-lang/sdk#42036]
As discussed [here](https://github.com/emacs-lsp/lsp-mode/issues/1482#issuecomment-633214101) and [here](https://github.com/emacs-lsp/lsp-mode/pull/1721) there're some languages with support for the new semantic tokens protocol from LSP, which may come on LSP 3.16. 
[Here](https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.semanticTokens.proposed.ts) is the protocol definition.

Is it possible to add support for that?

Once implemented, we can start using on [lsp-dart](https://github.com/emacs-lsp/lsp-dart) for Emacs and in the future, on VScode (c/c @DanTup).

**Comment by DanTup** [comment]
This is something on my radar - the current syntax highlighting in VS Code (powered by a TextMate grammar) has some issues so I'd like to move over to server-supplied highlighting (and the plan is for VS Code to switch over to LSP).

I don't expect to start looking at it until after the spec is finalised and supported by the vscode language server client though (to avoid reworking things if the spec evolves).

**Comment by DanTup** [comment]
Semantic tokens are available in the latest Dart/Flutter code (probably nightlies/master right now, though probably in dev soon too) - anything after https://github.com/dart-lang/sdk/commit/28523a5e3160fddacd13965d3b49d065452af37e should have them (though there have continued to be some improvements since then).

If you find any issues, please do file bugs here and CC me.

(@ericdallo I can't close issues here, so if you're happy with this please do that for me too :-))

**Comment by ericdallo** [comment]
Thank you  @DanTup! I'll test it soon and let you know ;)
