### ISSUE TITLE
List<int>.fold not compiling to javascript because of operator not found

### ISSUE THREAD

**Issue by ravish-tech** [dart-lang/sdk#42042]
This can be replicated on dartpad.dev.
When trying to run the below code, I get error. I was expecting this to run and give me 2 as answer.

```
void main() {
  List<int> a = List<int>();
  a.add(2);
  print(a.fold(0, (prev, v) => prev + v));
}
```
```
Error compiling to JavaScript:
main.dart:4:37:
Error: The operator '+' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
  print(a.fold(0, (prev, v) => prev + v));
                                    ^
Error: Compilation failed.
```
Based on Dart SDK 2.8.2

**Comment by eernstg** [comment]
You need to give type inference some extra information:

```dart
void main() {
  List<int> a = List<int>();
  a.add(2);
  print(a.fold<int>(0, (prev, v) => prev + v));
}
```

With the original version, the inferred type argument to `fold` will be `Object`, which makes `prev` a parameter of type `Object`.

This issue arises because the Dart type inference does not transfer information between parameters in this situation, cf. https://github.com/dart-lang/language/issues/731. It rarely comes up except for `fold`.

**Comment by sigmundch** [comment]
(I believe Erik's comment should address your question, but feel free to reopen if we misunderstood)
