### ISSUE TITLE
Failures on [CFE] Use BlockExpression for encoding cascades

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#42051]
There are new test failures on [[CFE] Use BlockExpression for encoding cascades](https://github.com/dart-lang/sdk/commit/4dcf24ac7fe2dfd216b76a6a5fef96a71be93f76).

The tests
```
language_2/regress/regress41983_test Timeout (expected Pass)
```
are failing on configurations
```
dartk-reload-linux-debug-x64
```

Since this is a new test, not sure if this is expected or not, given running on a debug platform in reload. For now, approving. /cc @jensjoha

**Comment by jensjoha** [comment]
It's not expected, but looking at it I think it's a VM issue.

What the test is doing is adding a number of entries into a list via cascades. If I manually vary this number I can get different datapoints by running `time out/DebugX64/dart --hot-reload-test-mode tests/language_2/regress/regress41983_test.dart`.

For varying numbers I get these runtimes:

1000: ~2 seconds
2000: ~3 seconds
4000: ~6 seconds
8000: ~18 seconds
10000: ~33 seconds
12000: ~43 seconds
14000: ~58 seconds
16000: ~73 seconds
18000: ~91 seconds
20000: ~119 seconds

This is not exactly linear.

(If it helps anyone, doing a `perf record` of it shows that at 12000 `dart::VMHandles::IsZoneHandle` spends ~42% of the time and at 14000 it's ~49%...)

For good measure I also ran `out/DebugX64/dart -DDFE_VERBOSE=true --hot-reload-test-mode tests/language_2/regress/regress41983_test.dart` a few times for varying numbers to see how long (approximately) the compiler (CFE) spend on it:

at 4000 => ~.1 seconds per compile
at 10000 => ~.2 seconds per compile
at 20000 => ~.4 seconds per compile

so that's basically linear.

It seems to me that - probably in asserts in the VM - something doesn't scale all that well.

**Comment by mkustermann** [comment]
We do have non-linear behavior in DEBUG mode validating various invariants. Given Jens's instructions it should be easy to find out with a profiler where the time is spent.

I can see the test has a `main()` function with more than 20k calls inside it. This will probably generate gigantic unoptimized code.

If we think the work is justified: Can the test be marked as `Pass, Slow`?

**Comment by jensjoha** [comment]
A quick note about why I added the test:
With the previous encoding we had of cascades we could create a whole lot of nested lets meaning that on many cascades we could create a tree that we couldn't recurse into without crashing with stack overflows. The tests is large to "ensure" that if we (still) had that encoding we would crash.

**Comment by jensjoha** [comment]
Oh, and I'm not sure how to mark stuff slow nowadays.

**Comment by mkustermann** [comment]
> Oh, and I'm not sure how to mark stuff slow nowadays.

The status files still recognize `Skip` and `Slow`. So adding `foo_test: Pass, Slow` to the right status file works. That usually gives it 2x the normal time.

**Comment by a-siva** [comment]
I noticed that this new test was added to language_2/regress but not to language/regress.
Please be aware that directories like language_2, lib_2, co19_2 etc. are considered legacy and
are slotted for deprecation once we turn on non nullability by default.
Make sure to add the test to the language/regress directory too so that we don't lose it.
