### ISSUE TITLE
IntelliSense doesn't work

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/sdk#42064]
IntelliSense doesn't work when I write parameter in the add1().
Also, a forced autocomplete call does not work.

```
void main() {
   final int Function({int a}) add1 = ({a}) => a + 1;
   print(add1(a: 5));
}
```

**Comment by bwilkerson** [comment]
I'm guessing that you mean that it doesn't suggest the argument name when the argument list to the invocation of `add1` is empty (because that's the failure mode I was able to reproduce). If you meant something different, please let me know exactly what text is in the editor and where the cursor is when the failure occurs.
