### ISSUE TITLE
DartFuzz: Instruction SBCLE unimplemented in ARM simulator

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#42067]
Reproduction info:

```
DART SDK REVISION: Dart VM version: 2.9.0-edge.3fb5f27d055404e7027b3623a17b295c12837dd4 (be) (Fri May 22 18:50:06 2020 +0000) on "linux_x64"


dart runtime/tools/dartfuzz/dartfuzz.dart --fp --no-ffi --flat --seed 2439383860 fuzz.dart
out/ReleaseSIMARM/dart --old_gen_heap_size=128 fuzz.dart
```

Log output ([full logs here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8879454620954942496/+/steps/make_a_fuzz_shard_93/0/logs/task_stdout_stderr:_make_a_fuzz_shard_93/0)):

```
fail2:
-6

Simulator hit Unimplemented instruction: pc=0xf71bd5a4

0xf71bd5a4    eeb7cad0               unknown
sim> ../../runtime/vm/simulator_arm.cc: 391: error: ReadLine failed
version=2.9.0-edge.3fb5f27d055404e7027b3623a17b295c12837dd4 (be) (Fri May 22 18:50:06 2020 +0000) on "linux_simarm"
pid=10170, thread=10286, isolate=main(0x4763080)
isolate_instructions=1a7f6c0, vm_instructions=1a7f6c0
Stack dump aborted because GetAndValidateThreadStackBounds failed.
```

cc/ @alexmarkov @rmacnak-google

**Comment by alexmarkov** [comment]
The problem is that S-register operand for `VCVTDS` instruction was allocated to a high `Q` register, causing an overflow of register field when encoding the instruction. This results in an invalid instruction which crashed simulator and puzzled disassembler.

https://dart-review.googlesource.com/c/sdk/+/178162 should fix the issue.
