### ISSUE TITLE
Obfuscation : Support excluding certain classes and types from obfuscation

### ISSUE THREAD

**Issue by nateshmbhat** [dart-lang/sdk#42070]
There are many times where me might have used `toString` method on `enums` and many places where we might wanna keep the Type information after obfuscation.

There is a need to support excluding certain Types or classes from obfuscation.

**Comment by lucian1024** [comment]
I have similar problem. Have you found a solution?

> There are many times where me might have used `toString` method on `enums` and many places where we might wanna keep the Type information after obfuscation.
> 
> There is a need to support excluding certain Types or classes from obfuscation.

**Comment by rakudrama** [comment]
Minification (`--minify`) does not affect the result of calling `x.toString()` when `x` is an enum.

Minification _does_ affect the result of `x.toString()` when `x` is a `Type`, e.g. `print(a.runtimeType.toString())`.

The string representation of `Type` is not really usable except for debugging. Even without minification, it is not reliable. If you have three libraries, each with a class `Foo`, `x.runtimeType` with print as `Foo` for one of them and `Foo0` and `Foo1` for the others. Which one gets which version changes with small unrelated modifications of the app.

We made the decision to use the minified names in `Type.toString()` since it makes a large impact on application size. Adding the original source code name would bloat apps by 10-20%, possibly more. It is best to avoid using the string representation of `Type`.
