### ISSUE TITLE
[NNBD] No type promotion for a global variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42086]
The following code fails in both analyzer and CFE with `--enable-experiment=non-nullable` option
```dart
class A {}
class C extends A {}

foo(C c) {}

A aGlobal = new C();

main() {
  A aLocal = new C();
  if (aLocal is C) {
    foo(aLocal);  // Ok
  }
  if (aGlobal is C) {
    foo(aGlobal);  // The argument type 'A' can't be assigned to the parameter type 'C'.
  }
}
```
Without `--enable-experiment=non-nullable` there's no error and the code works. 

`Dart VM version: 2.9.0-11.0.dev (dev) (Tue May 26 12:14:57 2020 +0200) on "windows_x64"`

**Comment by eernstg** [comment]
I believe you're seeing the following: Pre-null-safety code will not promote (because global variables are never subject to promotions&mdash;any non-trivial computation could change it, so it's almost never sound to assume that it hasn't changed), and null-safety code also won't promote it. But with pre-null-safety downcasts, there is no error. So this is working as expected.
