### ISSUE TITLE
Analyzer? bug with inherited types/interfaces

### ISSUE THREAD

**Issue by huafu** [dart-lang/sdk#42091]
* Dart SDK Version (`dart --version`): `Dart VM version: 2.8.2 (stable) (Mon May 11 15:06:42 2020 +0200) on "macos_x64"`
* Whether you are using Windows, MacOSX, or Linux (if applicable): `NA`
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): `NA`

Example in the DartPad: https://dartpad.dev/8237ab5e8b4ca46add5bf5625693c5ec

This looks like a type system inheritance issue and is blocking us from building our app (`// ignore: xxx` is not a working option since the compiler then fails to build)

Tailored to the simplest code:
```dart
abstract class IQuery {}
abstract class IDocument {}
abstract class IModel {
  IQuery buildQuery({
    IDocument from, // putting dynamic here doesn't fix the issue
    // ...
  });
}

abstract class ModelBase<D extends IDocument> implements IModel {
  // invalid_override on `buildQuery` here:
  IQuery buildQuery({
    D from,
  });
}
```

Are we doing something wrong or is this an issue?

**Comment by mraleph** [comment]
Notice that your implementation of `buildQuery` is taking some specific subclass of an `IDocument` while an interface specifies that it should be taking an arbitrary `IDocument` - hence it is an invalid override because it has more specific parameter type.

You can solve this by declaring `D from` as `covariant D from`.

**Comment by huafu** [comment]
Wow, ok just discovered that `covariant` keyword in the doc before, thanks! and sorry for posting this (wrong) issue then!
