### ISSUE TITLE
[NNBD] co19 tests fail in dartk in a weak mode

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42109]
The following co19 tests fails in dartk in a weak mode. No error in dartk strong mode or CFE
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/right_object_fail_class_member_fail_A07_t02.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Subtyping/dynamic/generated/left_nullable_fail_local_variable_fail_A01_t01.dart

**Comment by alexmarkov** [comment]
These tests are not correct in weak mode, as they are testing that `null` cannot be assigned to `Object` or `T1`. However, weak mode uses legacy subtyping rules (`LEGACY_SUBTYPE`) and `null` is assignable to a variable of any type in legacy subtyping.

/cc @leafpetersen @eernstg

**Comment by crelier** [comment]
It looks like these 2 tests expect a `TypeError` when assigning null to a variable of type `Object`. Although it is correct in strong mode, this is the wrong expectation in weak mode, since the type `Object` becomes nullable in weak mode.

**Comment by eernstg** [comment]
I agree on the analyses, the null-safety spec [does use `LEGACY_SUBTYPE` for `as`](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-checks-and-weak-checking) so `null as Object` will not throw. It's somewhat confusing that the tests themselves say `// Requirements=nnbd-strong`, so they should never run with weak checking, but that might have happened since this issue was created.

**Comment by sgrekhov** [comment]
@eernstg `// Requirements=nnbd-strong` was just added by my to fix this issue. Before that there were no this flag and therefore tests were executed in a wesk mode as well. 

It's strange that there were no similar failures on cfe-weak-linux configuration. Shall I add a separate issue for CFE waek mode?

**Comment by eernstg** [comment]
I think there is no wrong behavior with the CFE: `cfe-weak-linux` presumably does not execute code, and the tests expect no compile-time errors. So "no error in CFE" would be as expected.
