### ISSUE TITLE
Clarify setup_build run_recipe

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#42113]
Build bots like `flutter-engine-linux-try` include a step called `setup_build` which records a log called `run_recipe` which looks something like:
```
To repro this locally, run the following line from the root of a 'dart' checkout:

./recipes.py run --properties-file - dart/flutter_engine <<EOF
...
```

This however seems a bit misleading since the Dart repo does in fact not contain any `recipes.py` and it's not at all clear how this is supposed to work.
As far as I can tell, `recipes.py` is some part of golem and/or skia infra, but the script alone does not appear to be enough to make the suggested command "repro locally".

Can we clarify if and how this is supposed to work for local repro?

**Comment by cskau-g** [comment]
Assigning athomas@ for triage.

**Comment by athomas** [comment]
This particular message is created by Luci infrastructure and in general you should not attempt to run recipes locally. Most of them will either not work or can potentially have harmful side-effects if run by users.

There are exceptions, and one of them is the reproduction instructions for the flutter-engine-linux bot specifically: https://docs.google.com/document/d/1KgeDDe8C-0EfpSnGA9R5flhRbyVGdP6wNSgeOoxFVQo/edit# (linked from the gardening log).

These were not updated when I moved the recipes to their repo on dart.googlesource.com/recipes (which also contains a copy of the recipes.py script). I updated the instructions now, if there is something that still doesn't work for you there, please comment on the doc.

Apart from exceptions like the above, users should reproduce issues by running either test.dart/test.py or using tryjobs. Documentation for recipe development is at go/recipe-docs.

**Comment by cskau-g** [comment]
Has the message in the `run_recipe` log been updated as well? I'm primarily concerned about the suggestion there being misleading.

**Comment by athomas** [comment]
No, I haven't done anything about it, neither do I plan to spend more time on it. I do not expect a lot of gains here. The message will probably have to be very generic and end up being only technically correct but not really helpful for people working on Dart because it will have to match many different Luci customers (the instructions today may be correct for some of them today, but not really useful for most end users).

This is the source code is here:
https://source.chromium.org/chromium/infra/infra/+/master:recipes-py/recipe_engine/internal/engine.py;l=456

https://crbug.com is the relevant bug tracker.
