### ISSUE TITLE
[CP] Please merge 10df757a491e3856dfc956d72a25f5863451a777 into beta/stable channe

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#42184]
**commit(s) to merge**: 10df757a491e3856dfc956d72a25f5863451a777

**merge instructions**: merges cleanly

**reason:** This fixes incorrect program behavior for `dart:ffi` users when 64-bit values are passed via FFI to C code on 32-bit ARM when building the app on Windows.

**impact**: We have seen flutter users hitting this, see https://github.com/flutter/flutter/issues/54948 and https://github.com/simolus3/moor/issues/446 . This affects [package:moor_ffi](https://pub.dev/packages/moor_ffi) users.

/cc @franklinyow

**Comment by franklinyow** [comment]
Copy from CL:
[vm/ffi] Fix issue due to unspecified argument evaluation order in C++

We already have tests that exercise this, namely:

  - ffi_2/regress_39044_test
  - ffi_2/vmspecific_send_port_id_test

Though the bug only appears if C++ compiler decides to evaluate arguments
in a different order. This happens to be only the case on Windows.

We don't have Windows hardware with Android phones on our CI, which is
why this was not caught earlier.

We have manually confirmed (via building app on windows with this fix
and running on android) that the issue is fixed by this change.

**Comment by Drkstr** [comment]
Is there some way I can use this before it is merged?

**Comment by mkustermann** [comment]
@Drkstr I believe the fix in dart-lang/sdk@10df757a491e3856dfc956d72a25f5863451a777 has fully rolled into upstream flutter. So using "master" channel (i.e. using [flutter/flutter](https://github.com/flutter/flutter) git repository checkout) should give you this change.

**Comment by franklinyow** [comment]
Didn't get joined approved from Flutter team base on not enough impact on the pick
