### ISSUE TITLE
Incorrect analyzer error under NNBD with covariant setter override

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42204]
I'm migrating `language_2/override` and ran into this analyzer error:

```dart
main() {
  C();
}

class A {
  void set setter7(num x) {}
}

class B extends A {
  covariant dynamic setter7;
}

class C extends B {
  void set setter7(int x) {}
}
```

Analyzer gives me:

```
  error • The return type of getter 'B.setter7' is 'dynamic' which isn't a subtype of the type 'int' of its setter 'setter7'. • temp.dart:14:12 • getter_not_subtype_setter_types
```

It runs fine in the VM. If I comment out class C, the error goes away, even though the error is in class B. My guess is that analyzer is inadvertently losing the `covariant` qualifier because of class C?

cc @stereotype441 @scheglov

**Comment by scheglov** [comment]
I think the spec requires that `C.setter7` is an error.

```
It is an error if a class has a setter and a getter with the same basename where the return
type of the getter is not a subtype of the argument type of the setter. Note that this error
specifically requires subtyping and not assignability and hence makes no exception
for dynamic.
```

Here, there is a setter `C.setter7` with type `void Function(int)`, and getter `C.setter7` with type `dynamic Function()`. And `dynamic` is not a subtype of `int`. So, the error.

We know that the parameter of `C.setter7=` is covariant, so we don't report that it is an invalid override of `B.setter7=`. But the issue is the conflict between this setter and the getter.

Class `B` is OK by itself because its setter and getter are `void Function(dynamic)` and `dynamic Function()`.

It used to work before null safety because of using assignability instead of subtyping.

**Comment by eernstg** [comment]
Agreed, it's an error for `C` to inherit the implementation of the `setter7` getter with return type `dynamic` (the setter/getter type constraint has no exceptions for covariant parameters).
