### ISSUE TITLE
Compile error in analyzer if mixin extends class other than 'Object' or references 'super'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42239]
The following code has no issues in VM but error in analyzer
```dart
class Sstatic {
}

class M extends Sstatic {
}

class SuperA {
}

class A = SuperA with M; //  error - The class 'M' can't be used as a mixin because it extends a class other than Object.

main() {
  A a = new A();
}
```
Similarly the program below has no issues in VM but error in analyzer
```dart
class M {
  String get s => super.toString();
}

class SuperA {
}

class A = SuperA with M;  // error - The class 'M' can't be used as a mixin because it references 'super'

main() {
  A a = new A();
}
```
Mixin class may extend class other that `Object` and have references to `super`. Analyzer shouldn't produce these errore here
`Dart VM version: 2.9.0-13.0.dev (dev) (Fri May 29 15:59:05 2020 +0200) on "windows_x64" `

**Comment by lrhn** [comment]
Mixins can only be extracted from classes with `Object` as their superclass. The analyzer is correct on the first one, but not on the second one. 
Such mixins may call `super` methods, but since they can only be calling `Object` methods, it's safe for any superclass.

The fact that the specifiaction isn't  stating this is a mistake (my bad). See https://github.com/dart-lang/language/issues/1015 for discussion.

The lines that were inadvertently removed said:
 
> It is a compile-time error to derive a mixin from a class which explicitly declares a generative constructor.
-It is a compile-time error to derive a mixin from a class which has a superclass other than `Object`.

There is no restriction on calling `super` members since we restricted super-invocations to those that were statically allowed by the superclass in Dart 2.0.

**Comment by sgrekhov** [comment]
@lrhn thank you for the clarification. I'll have to revisit co19 mixin tests. As for this issue we have 3 issues here
- Specification issue (dart-lang/language#1015)
- CFE issue (#42254)
- Analyzer issue (#42255)

As we have a separate issue for each of the above I'm closing this general one
