### ISSUE TITLE
Package dart2native in the SDK as part of the GN build

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#42230]
Today, a product mode dart2native is packaged in the Dart SDK alongside other binaries built in release mode. This is accomplished by spinning up two separate GN builds with different configurations, and copying files into the right places after the fact.

Instead, this could be simplified by creating the product mode binaries as part of one release build of the SDK following the example of e.g. the gen_snapshot_product target:

https://github.com/dart-lang/sdk/blob/master/runtime/bin/BUILD.gn#L239

(There is probably some additional work for the snapshots that dart2native and dartaotruntime use, but I'm confident that this can also be supported entirely in the GN build.)

@mkustermann @a-siva @mit-mit

**Comment by zanderso** [comment]
This will greatly simplify https://github.com/flutter/flutter/issues/43968 down to e.g.https://github.com/flutter/engine/pull/18848

**Comment by mkustermann** [comment]
Will try to clean this up

**Comment by mkustermann** [comment]
Doing this without many MB size regressions will require us to build specific targets with `-fvisibility=hidden` instead of relying on the global buildroot settings in `//build/config/BUILDCONFIG.gn` (which only enables hidden visibility in product mode).

I've made the following CLs for this:

  * BoringSSL repo: https://dart-review.googlesource.com/c/boringssl_gen/+/150482
  * Upstream ICU repo: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/2236407
  * Dart sdk: https://dart-review.googlesource.com/c/sdk/+/150524

If the upstream changes are approved we can do it like this.

**Comment by mkustermann** [comment]
Doing this without many MB size regressions will require us to build specific targets with `-fvisibility=hidden` instead of relying on the global buildroot settings in `//build/config/BUILDCONFIG.gn` (which only enables hidden visibility in product mode).

I've made the following CLs for this:

  * BoringSSL repo: https://dart-review.googlesource.com/c/boringssl_gen/+/150482
  * Upstream ICU repo: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/2236407
  * Dart sdk: https://dart-review.googlesource.com/c/sdk/+/150524

If the upstream changes get approved we can do it like this.

**Comment by zanderso** [comment]
Thanks!
