### ISSUE TITLE
Incorrect error on null-aware spread of Null

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#42304]
This works fine today:

```dart
main() {
  print(<int>[1, 2, ...?null, 3]);
}
```

But if I run:

```
$ dart --enable-experiment=non-nullable temp.dart
```

I get a compile-time error:

```
temp.dart:2:25: Error: Can't assign spread elements of type 'Null' to collection elements of type 'int'.
  print(<int>[1, 2, ...?null, 3]);
```

I think this CFE error is incorrect. If the spread element has type Null, then the null-aware spread will always insert no elements. It's a little pointless (most of the time, the element's type would be some nullable type, not Null), but there's no reason to disallow it. Analyzer is fine with it.

Note that CFE does the right thing if the element's type is just a nullable type:

```
main() {
  List<int>? n = null;
  print(<int>[1, 2, ...?n, 3]);
}
```

This works fine. It seems like it's the Null type that's the problem.

cc @leafpetersen @johnniwinther

**Comment by lrhn** [comment]
Is the issue that the type of `null` is `Null`, and therefore the *element type* introduced by `...?null` defaults to `dynamic` (because it's not a kind of iterable).

We might have to special case the static typing of `...? e` such that if `e` has static type `Null` then it does not an the element type (which can then also not fail to be correct).

The only spec I can find is the feature spec (https://github.com/dart-lang/language/blob/master/accepted/2.3/unified-collections/feature-specification.md#maps-and-sets) stating:
> If *S* is `Null` and the spread operator is `...?` then the element has set element type `Null`, map key type `Null` and map value type `Null`.

Those should probably be changed to `Never` with Null Safety because otherwise `<int>[...?null]` is invalid.

**Comment by munificent** [comment]
> So technically it's working as specified - in a document that hasn't been updated for null safety.
> Those `Null`s should probably be changed to `Never` with null safety, exactly because otherwise `<int>[...?null]` is invalid.

Ah right. This is actually in the spec now too:

> If S is Null and the spread operator is `...?`, the inferred element type of `l` is Null.

That should probably be Never like you say.
