### ISSUE TITLE
Null safety feedback: [Snippet 3 not working on nullsafety.dartpad.dev]

### ISSUE THREAD

**Issue by hparicha** [dart-lang/sdk#42313]
```
List<String>? aNullableListOfStrings;
List<String>? aListofNullableStrings = ['one', 'nile', 'three', null];
```

Declaring a nullable list of strings works, until a null assignment is attempted.
In other words, the compiler is happy with "aNullableListOfStrings" until later on if you try
`aNullableListOfStrings = ['hi', 'bye', null, 'try'];`

![Screen Shot 2020-06-12 at 9 35 26 AM](https://user-images.githubusercontent.com/6402097/84509508-cdba5e80-ac91-11ea-8cf1-69e29b033d1a.png)

**Comment by julemand101** [comment]
That is because the variable to the list itself can be null but the content of the list are not allowed to be null since it is declared as a List of Strins (List<String>). If you want to allow the content of the List to include null you need to declare it like:

```dart
List<String?>? aListofNullableStrings = ['one', 'nile', 'three', null];
```

Since this is at List of String? (List<String?>).

**Comment by mraleph** [comment]
Or better just 

```
List<String?> aListofNullableStrings = ['one', 'nile', 'three', null];
```

because you don't need `aListofNullableStrings` to be `null` themselves.
