### ISSUE TITLE
dartanalyzer: latest dev version ignores "ignore: implicit_dynamic_parameter"

### ISSUE THREAD

**Issue by hpoul** [dart-lang/sdk#42373]
The following code block produces no warnings/errors with dart(analyzer) 2.8.4:

```
  final foo = <dynamic>[];
  // ignore: implicit_dynamic_parameter
  foo.forEach((element) { });
```

```
$ flutter/bin/cache/dart-sdk/bin/dartanalyzer bin       
Analyzing bin...
No issues found!
```

but with more recent versions like: `2.9.0-15.0.dev (dev) (Thu Jun 11 10:03:39 2020 +0200)` it produces the same error as if I would have omitted the `ignore` statement:

```
$ dartanalyzer bin                                       
Analyzing bin...
  error • Missing parameter type for 'element'. • bin/main.dart:4:18 • implicit_dynamic_parameter
1 error found.
```

I couldn't find anything whether this is a deliberate change..

**Comment by srawlins** [comment]
This is intentional, or at least somewhat intentional. Recent versions of Dart analyzer will not ignore an _error_ (but will continue to ignore hints and lints), even if it sees `// ignore:`. `IMPLICIT_DYNAMIC_PARAMETER` is a CompileTimeError. You can still ignore in analysis_options.yaml by setting `implicit_dynamic_parameter` to `ignore`.

Now the fact that the IMPLICIT_DYNAMIC_* codes are CompileTimeErrors is perhaps a bug.

CC @bwilkerson Do you know the history of the `implicit-dynamic: false` Codes? Anything wrong with downgrading them to HintCodes, so that they can be ignored.

**Comment by bwilkerson** [comment]
They were added as part of the work to design Dart 2.0 as a way to experiment with varying degrees of soundness.

We've talked several times, as you know, about turning these into a full feature, but that work hasn't been completed yet.

I suppose I could accept making them hints, though it's a little odd to have hints that are disabled by default, since the current distinction between hints and lints is whether they are enabled by default (with hints being enabled by default and lints being disabled by default). Kind of muddies a distinction that many users don't fully understand making it harder for us to explain our tools.

I'd really rather just get a clean story for them.

**Comment by hpoul** [comment]
this is only a "problem" because it was my workaround for generated files (using `ignore_for_file` headers). But I guess if this is an intentional change to have this as a compile error, it might be enough reason/motivation to accept the verbosity added by fixing explicit `dynamic` @ https://github.com/dart-lang/json_serializable/issues/557 (also https://github.com/dart-lang/language/issues/993)

btw. it might be worth a changelog entry tough 😅️ (if i didn't just miss it)

**Comment by maks** [comment]
I feel like I'm going around in circles a bit as I just got bitten by this too just now, after thinking I had my problems solved once https://github.com/dart-lang/json_serializable/issues/557 had been fixed.

I'm using Flutter master at the moment, with which, I think due to the "new" `dart analyze` tool mentioned in: https://github.com/dart-lang/sdk/issues/25551 means that I can avoid hitting this by not relying on `json_serializable` and other code gen packages adding the `ignore:` comment and instead just the analyzers `exclude:`  in my `analysis_options.yaml` which seems to work for me with `flutter analyze` and `dart analyze`.
eg.
```yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
```

Also thats the approach that Remi, the author of the `freezed` package has taken, suggesting that users apply the `exclude:` option to freezed generated code that causes analyzer errors.

**Comment by hpoul** [comment]
@maks excludes are still very annoying, every time you open the ignored files in android studio the errors show up again.. it kind of makes sense, that analysis is ran when the file is opened in the IDE.. anyway, that's a problem besides this issue :)

imho generated code shouldn't have compile errors, even with the most restricted settings.. so if this sticks around, it's just a language change for the code generators..

**Comment by srawlins** [comment]
This behavior has been reverted; this code can be ignored now.
