### ISSUE TITLE
Getting NoSuchMethodError when using extension on dynamic

### ISSUE THREAD

**Issue by jlubeck** [dart-lang/sdk#42381]
Given this code:
```dart
void main() {
  dynamic timestamp = 1573653139;
  DateTime convertedTimestamp = timestamp.toDateTime();
}


extension DynamicExtension on dynamic {
  DateTime toDateTime() {
    if (this == null) return null;
    int milliseconds = this is int ? this : null;
    return milliseconds?.toDateTime();
  }
}

extension IntExtension on int {
  DateTime toDateTime() {
    return DateTime.fromMillisecondsSinceEpoch(1000 * this);
  }
}

```

I'm getting `Uncaught TypeError: 1573653139.toDateTime$0 is not a functionError: TypeError: 1573653139.toDateTime$0 is not a function`

Happens both locally with `Dart VM version: 2.9.0-14.1.beta (beta) (Tue Jun 9 10:52:57 2020 +0200) on "macos_x64"` and on https://dartpad.dartlang.org/ (not sure how to look which version they use)

Changing the first line from `dynamic` to `int` clears the error.

**Comment by mraleph** [comment]
You can't have extension on `dynamic` - this is by design. 

It's unclear to me why declaring extension on `dynamic` is not a compile time error though 

/cc @lrhn - Lasse is this working as intended? Given that we don't resolve extension methods on `dynamic`, should not we prohibit to declare them to begin with?

**Comment by jlubeck** [comment]
Should we reopen this and change it to throw an error on compile then? It's very frustrating not having any errors and then have it break at runtime... 

Thanks you!

**Comment by mraleph** [comment]
Based on https://github.com/dart-lang/language/issues/716 this was a conscious decision to permit `dynamic` there (it essentially behaves as declaring extension on `Object?`).

Lets wait for @lrhn to provide the judgement here.

**Comment by lrhn** [comment]
We could warn or err if you declare an extension on `dynamic`, but the `on` type of an extension is primarily used for super-type checks, and it allows all types, so disallowing `dynamic` would be an extra complication. It means exactly the same as `on Object?` or `on void` except that the type of `this` is also affected. 

In general, you should probably never have `on dynamic`, `on void`, or `on Never` as extension types, but that's a semantic reason, there is no technical problem with using them. It's not very useful, but it works consistently.

**Comment by jlubeck** [comment]
If there is no technical problem using them, how come I’m seeing that error?

**Comment by lrhn** [comment]
There is no technical problem writing 
```dart
extension X on dynamic {
  void foo() { this.bar(); }
}
```
It works exactly the same as 
```dart
extension X on Object? {
  void foo() { (this as dynamic).bar(); }
}
```
which means that you can do `42.foo();`. The `on dynamic` means that the extension applies to any receiver which has a static type which is a sub-type of `dynamic` and which does not have a `foo` member.

*Declaring* extensions on `dynamic` works perfectly fine and consistently.

What you can't do is *call* extension methods on a receiver of type `dynamic`:
```dart
dynamic x = 42;
x.foo();
```
This doesn't work because, for all we know, `x` could have a real method named `foo`, and this code should call it. Dart extension methods are *static* extension methods. Whether to call them is decided at compile-time, and what `x` is here is only determined at run-time.
So, a receiver of type `dynamic` is treated statically like it has all members, and then checked at run-time, and therefore extensions do not apply to it because instance members always take precedence over extensions.

You can't call static extension members on receivers with static type `dynamic`, no matter what type the object actually is, because we only know that type long after we decided whether to call some extension method.

**Comment by alan-knight** [comment]
It seems excessively strong to say "instance members always take precedence over extensions". Instance members that are statically visible always take precedence over extensions, but what's statically visible is not necessarily obvious. Consider

```
import 'dart:html';

extension Href on Element {
  String get href => 'http://www.example.com';
}

main() {
  document.body.appendHtml('<a href="https://www.google.com" class="foo">Foo</a>', treeSanitizer: NodeTreeSanitizer.trusted);
  var queried = document.querySelector('.foo');
  print(queried.href);
  var filtered = document.body.children.whereType<AnchorElement>();
  print(filtered.first.href);
  queried = document.body.children.whereType<AnchorElement>().first;
  print(queried.href);
}

which prints different values for what in the program text looks like the same invocation, and in 2 of the 3 cases the extension takes precedence over an instance member. So something that changes the type inference, or even assigning a value to a different variable, can change the program behavior in arbitrary ways.

```
http://www.example.com
https://www.google.com/
http://www.example.com
```
