### ISSUE TITLE
Constant list literals are not canonicalized if declated in different parts of the linrary

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42393]
Dart VM version: 2.9.0-16.0.dev (dev) (Tue Jun 16 10:35:10 2020 +0200) on "windows_x64"

Constant list literals are specified to be canonicalized: Identical elements and same type argument should make different expressions refer to the same object, no matter which part/library those expressions are located in.

However, currently this is not so.

Please run the source code example below:

**part.dart:**
``` dart
part of Parts_test_lib;

final List lst = const [0,1,2,3];
```
**test.dart:**
``` dart
library Parts_test_lib;
part "part.dart";

main() {
  print(const [0, 1, 2, 3] == const [0, 1, 2, 3]);
  print(const [0, 1, 2, 3] == lst);
}
```
It should print
> true
> true

but actually prints
> true
> false

**Comment by lrhn** [comment]
The behavior is actually correct.

You wrote `final List list = const [0, 1, 2, 3];` in `part.dart`.
This gives the expression a context type of `List<dynamic>`, which means that the constant is `const <dynamic>[0, 1, 2, 3];`.

The expressions in `test.dart` are `const [0, 1, 2, 3]` with no context type, which infers a type of `const <int>[0, 1, 2, 3]`. Since the two objects differ on the type argument, they cannot be the same object and are not canonicalized.
