### ISSUE TITLE
Migrate benchmarks to null safety

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#42394]
https://goto.google.com/benchmarking-null-safe-dart

**Comment by athomas** [comment]
@franklinyow @sortie FYI

**Comment by leafpetersen** [comment]
@sortie is this done?

**Comment by sortie** [comment]
All 100 benchmarks are migrated. 96 of 100 are sound, the remaining 4 pending the completion of #42395. package:csslib might just have rolled in, so it might be 97 right now. package:intl is about to roll in, so that'll get us to 98 sound. The soundness of the remaining 2 are blocked on package:compiler and package:vm_service which are handled by the appropriate teams and outside of the scope of this issue. As such, this issue is completed.
