### ISSUE TITLE
File.renameSync fails across linux partitions

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#42414]
I'm running Ubuntu 20.04 using ZFS.

```bash
df f -h
Filesystem                                        Size  Used Avail Use% Mounted on
rpool/ROOT/ubuntu_c520d1                          415G  4.6G  411G   2% /
rpool/USERDATA/bsutton_b4334o                     427G   17G  411G   4% /home/bsutton
```

When I call File.renameSync to move a file from /tmp to /home/bsutton I get the following error:
OS Error: Invalid cross-device link, errno = 18

I believe this is due to dart using a hardlink to do a rename and hardlinks are not allowed across partitions.

I'm uncertain as to whether this is a bug however the only work around that I can think of is to call rename, catch the exception and then do a copy/delete.

Ideally the dart rename would work regardless of the partition. Having said that I guess I wouldn't expect a rename across windows drives to work but then I can detect that the file paths are on different drives. 

dart --version
Dart VM version: 2.8.4 (stable) (Unknown timestamp) on "linux_x64"

**Comment by sortie** [comment]
Renames are not supported across filesystems on Unix-like operating systems. The underlying `rename(2)` system call will atomically make the destination directory entry point to the file and remove the original source directory entry. This atomicity is a very useful and strong property because no observer will ever see any inconsistent state while the renaming is happening. Dart exposes that functionality through the `File.rename` API.

Programs such as `mv(1)` rely on `rename(2)` whenever possible to provide users with atomic renames, but it also has fallback support for renaming across filesystems by doing a copy + a delete.

dart:io provides you with the low level API. If you want to move a file across filesystems, you will need to use a higher level API that copies the file and deletes the source. This could be of your own making or in a package. dart:io doesn't expose all the low level abilities though to get all and set all the file meta data such as file permissions. If you need to preserve meta information, your best bet is to use the `Process` API to manually invoke the `mv` program with the appropriate options, or petition for us to add the missing functionality to `dart:io` (which is tricky to do cross platform and can easily be a breaking change).

I hope that helps. I'm closing this issue because Dart is working as it should. Be sure to let us know if you have any further questions.
