### ISSUE TITLE
how can i clone a new object in dart?

### ISSUE THREAD

**Issue by SinoMiles** [dart-lang/sdk#42427]

**Comment by lrhn** [comment]
Dart does not have a simple way to clone objects. In general, if an object supports cloning, it should expose a `clone` method or copy constructor itself, so that it can do a proper cloning which preserves any underlying invariants, rather than a physical cloning which just copies the values of the fields.

If you have access to isolates, you *can* do deep cloning on some objects by sending them through a `SendPort`.
```dart
Futyre<T> clone<T>(T object) async {
  var port = ReceivePort();
  port.sendPort.send(object);
  return await port.first as T;
}
```
It's not a recommended way to do cloning, but it might work for some objects.
