### ISSUE TITLE
CFE support for nonfunction type aliases

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#42430]

**Comment by eernstg** [comment]
@johnniwinther, I think dart-lang/sdk#36870 should be removed from this epic, because it is concerned with an issue that arises without any use of non-function type aliases (so it shouldn't be blocked on experiment nonfunction-type-aliases).

I removed it from this epic. It is still a member of https://github.com/dart-lang/sdk/issues/41991 CFE dysfunctionalities. Please take a look if it needs to be added to some other epic.
