### ISSUE TITLE
Dart does not throw error if function type alias type parameter bound type is not instantiated

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42435]
Dart VM version: 2.9.0-17.0.dev (dev) (Thu Jun 18 10:22:39 2020 +0200) on "windows_x64"

The following source code example passes with dart and throws a compile error with analyzer:
``` dart
class A<X extends A<X>> {}
typedef AAlias = Function<X extends A>();
main() {}
```
Seems like dart should throw a compile error here too.

Sample output is:
> $> dart test.dart
> 
> $> dartanalyzer test.dart
> Analyzing test.dart...
>   error - Type parameter bound types must be instantiated. - test.dart:2:37 - not_instantiated_bound
> 1 error found.

**Comment by johnniwinther** [comment]
Likely related to #41684

**Comment by leafpetersen** [comment]
cc @eernstg

**Comment by eernstg** [comment]
The type `Function<X extends A>()` [is a compile-time error](https://github.com/dart-lang/language/blob/1ed6bab4cc5a826f1ed6a81fb70a4f23815e1a82/specification/dartLangSpec.tex#L5768), because it declares a type parameter (`X`) with a bound (`A`) which is raw and doesn't have simple bounds.

So there's a missing check in the CFE for having simple bounds.

The issue arises independently of the type alias:

```dart
class A<X extends A<X>> {}
Function<X extends A>() f = throw 1;
main() {}
```

This program is accepted by the CFE, even though `A` is raw, does not have simple bounds, and is used as a type parameter bound.

**Comment by eernstg** [comment]
Cf. our discussions earlier today: Reading the [error specification](https://github.com/dart-lang/language/blob/1ed6bab4cc5a826f1ed6a81fb70a4f23815e1a82/specification/dartLangSpec.tex#L5768) again, it does actually apply for formal type parameters declared by any kind of entity (in particular, it applies for formal type parameters of a function declaration and of a function type). So there is no need to change the specification after all.

**Comment by eernstg** [comment]
Re-checking: This issue should remain open at this point, `dart` still does not report the error (that the raw type `A` cannot be a bound, because it does not have simple bounds).

**Comment by stefantsov** [comment]
I'm working on a fix for that at https://dart-review.googlesource.com/c/sdk/+/193662.
