### ISSUE TITLE
Enforce Required, Named Parameters

### ISSUE THREAD

**Issue by felangel** [dart-lang/sdk#42438]
As a developer, when I define a class with a required, named parameter I would like all subclasses to have errors (or at least a warning) if the required parameter was not passed to the superclass.

```dart
class A {
  const A(this.x);

  final int x;
}

class B extends A {}
```

The above snippet currently won't compile (expected):
<img width="918" alt="Screen Shot 2020-06-22 at 12 35 08 PM" src="https://user-images.githubusercontent.com/8855632/85312451-d88ca480-b484-11ea-8b14-9642ada2bf68.png">

If I refactor class A to make `x` a required, named parameter, however, the code compiles just fine without any error/warning (not expected).

```dart
import 'package:meta/meta.dart';

class A {
  const A({@required this.x});

  final int x;
}

class B extends A {}
```

<img width="291" alt="Screen Shot 2020-06-22 at 12 36 58 PM" src="https://user-images.githubusercontent.com/8855632/85312647-1d184000-b485-11ea-9806-04dbe3958e47.png">

This will definitely not be an issue once NNBD lands in stable but for now it's seems there isn't a good way to safely support required, named parameters.

## Additional Info

This tracker is for issues related to:

* Analyzer
* Dart core libraries ("meta")

### Dart Version

```sh
Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "macos_x64"
```

### OS

MacOSX

**Comment by lrhn** [comment]
The analyzer does indeed fail to recognize that the implicit `super()` of the default constructors (or a user-written generative constructor with an omitted `super`-call) is not passing a `@required` parameter.

Compiling *should* work because Dart compilers mostly ignore metadata like `@required`. Only the Dart analyzer understand the meaning of `@required`, but it too fails to give a warning here, (dartanalyzer version 2.9.0-18.0.dev).

**Comment by srawlins** [comment]
This works now with the null-safety feature, `required`. No further work will be done to support the `@required` annotation.
