### ISSUE TITLE
Resolution for imported identifiers does not follow the specification wording

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#42493]
We have `Scope.lookup` that accepts `Identifier`, not just `SimpleIdentifier`, because we want to support `importPrefix.topLevelName`. But the specification instructs us to look on import prefixes as on objects:
![image](https://user-images.githubusercontent.com/384794/85758697-69ea5980-b6c5-11ea-877f-39916dda1c5b.png)
We don't have to follow this exactly and create such objects, but the idea is that it might be cleaner to do separate resolution for import prefixes, and then identifiers in the namespaces that correspond to these import prefixes.

**Comment by bwilkerson** [comment]
IIRC, `Scope` used to only handle `SimpleIdentifier`, but then the spec was changed to treat `<prefix>.<identifier>` as if it were a single identifier, so we changed `Scope` to correspond. If the spec no longer treats them as a single identifier, then I agree that `Scope` should stop doing so. (It was probably changed back when `deferred` was added.)

**Comment by eernstg** [comment]
This topic is somewhat in flux, because there is a not-yet-landed major [update](https://github.com/dart-lang/language/pull/534) of all the rules about library namespaces, imports, and prefixes.

One of the properties of the new text is that it explicitly says that there is no such thing as an object at run time which is denoted by an import prefix, the prefix is purely a device which is used to navigate namespaces at compile time.

Also, it is made explicit that any use of a prefix which gives rise to evaluation of the prefix to an object is a compile-time error, and the prefix does not have a static type.

I believe this should be sufficient support for the conclusion that implementations are free to consider terms of the form `prefix.id` as identifiers, as well as the conclusion that prefixes are subject to a separate step of resolution. Whatever is more convenient would be fine.

**Comment by scheglov** [comment]
We switched to resolving `importPrefix.topLevelName` by separately looking up `importPrefix`, and then `topLevelName` in the scope of the found `PrefixElement`.
