### ISSUE TITLE
VScode Dart plugin format problem

### ISSUE THREAD

**Issue by heroqin** [dart-lang/sdk#42523]
Hi,  it seems format is not correct if I use Shift+Alt+F when function using =>, as following:
![图片](https://user-images.githubusercontent.com/48232744/86082623-c89b4300-baca-11ea-9289-bf41289a679e.png)

**Comment by lrhn** [comment]
That looks correct to me. Can you say why you think it is not correct?

If you would prefer the `Column(` to go on the next line, I can understand that preference, but the formatter will fit things on the same line as `=>` if there is room for them. That's very nice for `foo() => 42;`.

**Comment by heroqin** [comment]
I mean the vertical lines under 'Column' are ugly and misguided. There are 3 vertical lines under 'Column',  the first line aligns '@' character, and the second line aligns nothing,  and the third line correctly aligns to ')'.

Maybe the following format is more reasonable？

![图片](https://user-images.githubusercontent.com/48232744/86116667-678e6200-bb00-11ea-8862-439e1f2f3a30.png)

**Comment by lrhn** [comment]
The general rule is to indent by four spaces if an expression is continued on/wrapper to the next line. There are some exceptions, but arguments are generally indented by four and things after `=>` are too. Since `Column(children: ...)` is wrapped to the next line, the remainder of that expression is indented by four spaces. That's the alignment of the `);` at the end.

The rest is an argument, so it's indented by a further two spaces relative to the `(` and `);` lines.
Then the inner `Icon` line is a list element, and multi-line list elements are indented by two spaces relative to the list brackets lines.

You are arguing that the four-space indent for wrapping arguments isn't necessary here (and I tend to agree), but it falls out of the general rules used by the formatter. The indent might look a little overkill here, but if the expression had been:
```dart
Colum _buildBottomColumn(Color color, IconData ico, String label) => Column(
  children: [
    Icon(icon, color: color),
  ],
).something.more.here(maybe);
```
then  the extra indent might look more reasonable. The important thing about indentation formatting is to make it clear where something ends and where something else starts. A `);` at the same level as the declaration is probably fine, but anything that can be mistaken for a new declaration is not OK. Always indenting ensures that you won't need to consider what the code is.

In any case, this issue should be filed in https://github.com/dart-lang/dart_style/issues if we want to change the behavior.

**Comment by heroqin** [comment]
I get it. You are right. Thank you.
