### ISSUE TITLE
Missing cast when returning await expressions

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42540]
In this example you can see the same await expression has an implicit cast from dynamic to Object in an assignment but not in a return.

```dart
dynamic getNull() => null;

Future<Object> fn() async {
  Object o = await getNull();
  return await getNull();
}
```

```
static method getNull() → dynamic
    return null;
static method fn() → asy::Future<core::Object> async {
    core::Object o = await tes::getNull() as{TypeError,ForDynamic,ForNonNullableByDefault} core::Object;
    return await tes::getNull();
}
```

cc @johnniwinther

**Comment by lrhn** [comment]
This is an async method, so the "return" might be a little special.

The return accepts either an `Object` or a `Future<Object>`, not just `Object`, and it checks whether it's a `Future` and should await the future if it's one. 

So, it's premature to cast to `Object` before the return. (It's safe because `Future<Object>` is a subtype of `Object`, but if the return type had been `int`, casting before the `return` would be obviously wrong).

If you change the example to:

``dart
dynamic getSomething() => Future<Object>.value("a");
Future<String> fn() async {
  Object o = await getSomething();
  return await getSomething();
}
```
then the code should run, but adding a cast to `String` for the `return` would make it fail.

**Comment by nshahan** [comment]
@lrhn Interesting point, thanks! 

So what type of implicit downcast from dynamic should we perform and where should it take place?

**Comment by johnniwinther** [comment]
I'm about to land https://dart-review.googlesource.com/c/sdk/+/152150 which should fix async return for nnbd. With this the implicit cast from `dynamic` to `FutureOr<Object>` should be inserted at the return.
