### ISSUE TITLE
"?.", null safety, static analysis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42554]
With null safety experiment on w/ analyzer

```dart
void main() {
  var json = <String, dynamic>{};
  final list = (json['bob'] as List?)?.map((e) => e as int).toList();
  //                                SHOULD get error here! ^
  print(list);
}
```

```dart
void main() {
  var json = <String, dynamic>{};
  final list = (json['bob'] as List?)?.map((e) => e as int)?.toList();
  //                            SHOULD NOT get error here! ^
  print(list);
}
```

But `warning: The target expression can't be null, so the null-aware operator '?.' can't be used. (invalid_null_aware_operator at [json_serializable] null_safety.dart:13)`

With 2.9.0-20.0.dev

**Comment by kevmoo** [comment]
Or, easier

```dart
List<int>? func(List? bob) => bob?.map((e) => e as int).toList();
//                              SHOULD get error here! ^
```

```dart
List<int>? func(List? bob) => bob?.map((e) => e as int)?.toList();
//                        SHOULD NOT get warning here! ^
```

**Comment by kevmoo** [comment]
CC @leafpetersen – I don't think I messed this up!

**Comment by lrhn** [comment]
The behavior is correct.

We changed the behavior of `?.` with null safety, so it extends to the rest of the selector list.

Since `map` returns a non-nullable iterable, `bob?.map(...).toList()` is correct. If `bob` is null, it all evaluates to `null`. if not, then it's equivalent to `bob.map(...).toList()`.

That is, it's equivalent to `bob == null ? null : bob.map(...).toList()` rather than (as in pre-null safety) `(bob == null ? null : bob.map(...)),toList()`

Because of that, you don't need a `?.` after `map`, and indeed, you must not use it on something which can never be `null` (if it is evaluated at all).

**Comment by kevmoo** [comment]
Perhaps we need to talk about the warning then.

`The target expression can't be null, so the null-aware operator '?.' can't be used.` Seems wrong in this case.

Isn't something like "This is already a nullable expression, so the `?` is not needed"

Seems like it should be more of a hint or something. `unnessesary_null_aware_operator` vs `invalid_null_aware_operator`

CC @devoncarew @scheglov @bwilkerson

**Comment by kevmoo** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/42599
