### ISSUE TITLE
invalid_null_aware_operator message is unclear for folks coming from pre null-safety

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42599]
```dart
List<int>? func(List? bob) => bob?.map((e) => e as int)?.toList();
//                                       warning here! ^
```
`warning: The target expression can't be null, so the null-aware operator '?.' can't be used. (invalid_null_aware_operator)`

In this case, (per @lrhn ) this is the new null safe behavior which makes follow-up `?` unnecessary.

The wording here is very wrong. Likely need a new error code + message here – `unnessesary_null_aware_operator` or similar

See closed https://github.com/dart-lang/sdk/issues/42554

**Comment by kevmoo** [comment]
CC @scheglov @bwilkerson

**Comment by bwilkerson** [comment]
> Analyzer should distinguish two cases both under `invalid_null_aware_operator` now

I'm not clear as to what the two cases are, so I might be misinterpreting the rest of what you said. If so, I apologize.

> In this case, ... this is the new null safe behavior which makes follow-up ? unnecessary.

In #42554 you also wrote:

> Isn't something like "This is already a nullable expression, so the ? is not needed"
>
> Seems like it should be more of a hint or something.

The problem I have with that is that the use of `?.` here isn't "unnecessary", it's explicitly disallowed by the spec. Saying that it "isn't needed" sounds like "it's allowed, but really doesn't add anything so we recommend not doing it", which is misleading. It isn't a recommendation, it's a requirement. I think the wording needs to be strong enough to convey that.

**Comment by kevmoo** [comment]
The **message** is unclear here. I talked to @munificent and I finally understood what was happening.

The first `.?` effectively short-circuits the expression. This was **very** confusing to me, coming from Dart 2.8.

I've opened all of these issues because the new behavior was unclear.

**Comment by bwilkerson** [comment]
Sorry, I should have tried harder to understand your point. I got caught up in evaluating your proposed solution rather than understanding the issue. But now I see what you mean, and I agree.

To paraphrase, analyzer should have a specialized message when the target is known to be non-null because it uses a null-aware operator, and the message should explain that the reason the target can't be null is because of the previous null-aware operator. The docs should explain the short-circuiting that happens.

**Comment by kevmoo** [comment]
> Sorry, I should have tried harder to understand your point. I got caught up in evaluating your proposed solution rather than understanding the issue. But now I see what you mean, and I agree.
> 
> To paraphrase, analyzer should have a specialized message when the target is known to be non-null because it uses a null-aware operator, and the message should explain that the reason the target can't be null is because of the previous null-aware operator. The docs should explain the short-circuiting that happens.

Something like that. 

Imagine coming from Dart 2.8 and seeing `The target expression can't be null, so the null-aware operator '?.' can't be used.` – If you don't know about the change to `?.` you'll be completely thrown off!

**Comment by munificent** [comment]
> To paraphrase, analyzer should have a specialized message when the target is known to be non-null because it uses a null-aware operator, and the message should explain that the reason the target can't be null is because of the previous null-aware operator.

Exactly right. The underlying error (warning, right?) is the same cause: you're using `?.` on an expression statically known to be non-nullable. The but reason you got there in one case is because of another language change users may not be aware of:

```dart
int x = 123;
x?.abs(); // Warning here.

x?.abs()?.abs(); // Also a warning on the second "?." here.
```

Before we made null-aware method chains short-circuit, you *would* need both `?.` on the second line, so it would be good if the warning clarified that you don't now because of short-circuiting.

>  The docs should explain the short-circuiting that happens.

I have docs in flight for that.

**Comment by bwilkerson** [comment]
> I have docs in flight for that.

Excellent! When those are publicly reachable, let me know where they live and I'll include a link in the documentation for the diagnostic.

**Comment by bwilkerson** [comment]
This has landed as https://dart-review.googlesource.com/c/sdk/+/154161. We can continue to iterate on the actual message if it still doesn't seem clear.
