### ISSUE TITLE
Analysis server's BazelWorkspace needs to support `dart_package` directives in BUILD files

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42594]
The way to opt packages into NNBD in a Bazel workspace will be to include this directive in a `BUILD` file:
```
dart_package(
    non_nullable = True,
)
```
The analysis server needs to recognize this pattern and use it to determine whether a package is opted in to NNBD.

Note that `BUILD` files are auto-formatted so it's not necessary to parse the whole file to find this directive; a simple regexp should suffice.

**Comment by scheglov** [comment]
See also https://buganizer.corp.google.com/issues/162609651

**Comment by davidmorgan** [comment]
Thanks! A few notes:

It's true that the file is auto formatted, but some variation is allowed. These are all valid:

```
dart_package(non_nullable = True)

dart_package(
    non_nullable = True,
)

dart_package(
    # Preceding comment.
    non_nullable = True,  # Trailing comment.
)  # Last comment.
```

And: it's desirable that the analyzer react to changes to the BUILD file, so that adding `non_nullable = True` changes the analysis mode for the package as soon as the file is saved.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/157474
