### ISSUE TITLE
Call to super.== should be type-checked in the ordinary way

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42592]
The following code generates a compile error with the front end but no error with the analyzer:
```dart
class C {
  bool operator==(Object other) => true;
}
class D extends C {
  bool operator==(Object? other) => super == other;
}
main() {
  print(D() == D());
}
```
The error is:
```
../../tmp/test.dart:5:46: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object'.
 - 'Object' is from 'dart:core'.
  bool operator==(Object? other) => super == other;
```
I believe the error is necessary for soundness.  @leafpetersen do you agree?

I'll add a language test that covers this.

**Comment by leafpetersen** [comment]
I don't think this error is correct.  Remember that `operator==` is never invoked directly.  The syntax `a == b` means "return true if a and b are null, otherwise false if a or b is null, otherwise invoke operator==", which means that `null` will never be passed as an argument to the method.  From the nnbd feature spec:

> Consider an expression `e` of the form `e1 == e2` where the static type of
`e1` is `T1` and the static type of `e2` is `T2`. Let `S` be the type of the
formal parameter of `operator ==` in the interface of **NonNull**(`T1`).
It is a compile-time error unless `T2` is assignable to `S?`.

**Comment by stereotype441** [comment]
Hmm, (reads spec carefully)...

Aha, you're right.  I thought that the special null-handling rules for `operator==` didn't apply to `super == other`, but I now see that they do.

I'll file a fresh bug against the CFE and close this one :)

**Comment by stereotype441** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/42603
