### ISSUE TITLE
"is" operator does not recognize Type variables, only Type literals

### ISSUE THREAD

**Issue by AKushWarrior** [dart-lang/sdk#42606]
* Dart SDK Version (`dart --version`): 2.8.4
* Whether you are using Windows, MacOSX, or Linux: Linux, Ubuntu 20.04

My issue is simple: the is operator does not recognize variables which are `Type`, only `Type` literals. This is what I mean:

```dart
// In an extension method or class...
extension Foo on Object {
       bool isType (Type t) => this is t; //This is a compile time error
}
```
If I were to do this manually, it is not a compile-time error:
```dart
var bar = Object();
bar.isType(String); // Can't do this, my extension didn't compile.
bar is String; // This is valid;
```
Given that you could only ever pass Type literals into a parameter of type `Type`, it doesn't make sense that the `is` operator fails to recognize that.

**Comment by eernstg** [comment]
This is working as intended: The `is` operator can only have a right hand operand that denotes a type, and an instance of type `Type` which is a reified representation of a type is a different kind of entity than a type. The former can be used to declare the type of a variable or parameter, it can be passed as a type argument in a parameterized type, and so on. The latter can only be used to identify the reified type, e.g., in order to compare the underlying types (say, `myObject.runtimeType == SomeClass`), which may again be used via a `Map<Type, U>` for some type `U`.

The main reason why the use of reified types (instances of `Type`) is not supported in many situations is that it is impossible to track the value of a variable `t` of type `Type`, and hence any support for constructs like `myObject is t` would imply that the subtype relationship must be supported for all types. In particular, even for a class `C<X>` that never creates a reified representation of its type parameter `X`, it will be impossible to compile `C` in a way that optimizes away the type arguments, because `myObject is t` could require that type argument to be looked up. In general, supporting an enhanced set of operations using reified types would be expensive in terms of performance and program size.

**Comment by AKushWarrior** [comment]
Thanks for the prompt reply, and detailed explanation. That makes sense to me. I have another, related question. I found a theoretical workaround, by using type arguments:

```dart
// In an extension method or class...
extension Foo on Object {
       bool isType<T> () => this is T; //This compiles!
}
```
Obviously with the caveat that this isn't exactly the correct usage of type arguments, how is this is optimized? It seems to me that it still uses a reified type, and `T.runtimeType == Type` is true.
