### ISSUE TITLE
Divide by Zero should throw an error instead of Infinity

### ISSUE THREAD

**Issue by Parkar99** [dart-lang/sdk#42618]
I just spent a good two hours because a third party library was throwing an error concerning a NaN value. Turns out on an edge case, I was passing Infinity to the class constructor of that library due to one variable in a division being 0. Dart, like other popular languages, should throw a DividebyZero error instead of returning Infinity and continuing execution of the program. Most of the time, a developer wouldn't even use the Infinity value anywhere. 

Hope you consider this

**Comment by AKushWarrior** [comment]
I agree with this. It seems hostile to continue the program, because 99% of the time zero division is not intended behavior. If it IS intended behavior, it would only take a simple try-catch block to work around the error.

**Comment by rakudrama** [comment]
Normal division `/` always produces a `double` in Dart. `double` arithmetic is determined by the IEEE 754 floating point standard, which specifies the result being infinity or NaN. Many popular languages also do not throw on division by zero of floating point numbers. [Java example](https://stackoverflow.com/questions/12954193/why-does-division-by-zero-with-floating-point-or-double-precision-numbers-not), [C# example](https://stackoverflow.com/questions/4262286/why-does-c-sharp-allow-dividing-a-non-zero-number-by-zero-in-floating-point-type).

Truncating division `~/` always produces and `int` and does throw an exception on division by zero. This corresponds to many cases of division in other languages, often the correct remedy is to use `a ~/ b` instead of `a / b`.

**Comment by lrhn** [comment]
What @rakudrama says is correct. Giving an infinite result is deliberate and expected behavior for `double` division by zero.

**Comment by Parkar99** [comment]
What would be the correct approach if I would want a `double` division but would want to avoid a `NaN` thrown?

**Comment by lrhn** [comment]
Compare the divisor to zero first.
```dart
double nonNanDivide(double divdend, double divisor) => divisor == null 
    ? throw ArgumentError.value(divisor, "divisor", "Must not be zero") 
    : dividend/divisor
```

**Comment by Parkar99** [comment]
I researched the maths behind divide by zero. Mathematically, dividing by zero should be impossible since it evaluates to both infinity and negative infinity [See this video](https://youtu.be/J2z5uzqxJNU). So, shouldn't Dart also model this behaviour?

**Comment by lrhn** [comment]
Dart uses 64-bit [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) floating points numbers for its double class. It's not math, it's engineering (one of the E's stands for "Engineers"). There is a well defined specification for those floating point numbers, and it's what the CPUs are implementing. Doing something different from that is very much a non-goal.

These floating point numbers are treated, in good engineering style, as being imprecise. They represent a range of real values. 
When you write 0.3, the mathematical value 3/10 is not precisely representable as a double. Instead it's represented by the actual double value which it is closest to, so all double values really represent the real numbers that are closer to them than to the neighboring doubles (with some caveats around infinity and a tie-breaker rule for values right between two doubles).

That also means that zero doesn't just mean zero. It represents a range of numbers which is (arbitrarily) *close to zero*.
In order to not get really confused about signs, doubles have *two zeros*, 0.0 and -0.0, where the former represents positive numbers close to zero, and  the latter represents negative numbers close to zero.
Similarly, infinity doesn't represent the actual infinite value, but just arbitrarily large values above the largest precise double value.

So, when you do `1.0 / 0.0`, you are dividing 1 by a "potentially very small positive number", which gives a "potentially very large positive number" (aka infinity). You can also do `1.0 / -0.0`, `-1.0 / 0.0` and `-1.0 / -0.0` and get the appropriate positive/negative "very large number".

The places where this approximation strategy breaks down is for things like `0.0 / 0.0` or `infinity - infinity` where it's not clear whether the result is small or large. You can pick a pair of real numbers in the range represented by the doubles which can make the expression either arbitrarily large or small. That's when the system gives up and yields `NaN`, "not a number". 

The number abstraction has both `infinity`as a value and a distinction between positive and negative zero, so it doesn't have to give up at `1.0/0.0`. The result is well-defined.

**Comment by Parkar99** [comment]
@irhn Thank you for that amazing explanation. I'm convinced that the Dart team made the right decision. You were a great help :)
