### ISSUE TITLE
json.decode bug? type 'int' is not a subtype of type 'double' in type cast

### ISSUE THREAD

**Issue by jrvidotti** [dart-lang/sdk#42622]
I am using Dart 2.8.4 in a Windows system.

My code is this:
```
import 'dart:convert';

void main() {
  final jsonStr = '{"floatValue": 217}';

  Map<String, dynamic> mapped = json.decode(jsonStr);

  print(mapped['floatValue']);

  double d = mapped['floatValue'] as double;
  print(d is double);
}
```

Using DartPad this code runs normally, but in my system it generates an error:

```
217
Unhandled exception:
type 'int' is not a subtype of type 'double' in type cast
#0      main (file:///C:/dev/src/test-double-json.dart:10:35)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

There is workarounds for this behavior? I need to consume a REST API that gives me float numbers but for round number it doesn't send decimal digits.

**Comment by lrhn** [comment]
The behavior is correct.

The JSON decoder decodes `217` as an `int`. If it had been `217.0`, it would have been parsed into a `double`.

When run on the web, all `int` objects are also `double` objects, because JavaScript doesn't have an efficient integer type. 
When run natively, the two types are distinct. 
That's why you can cast the value to `double` in DartPad, but not on the VM.

If you are not in control of the JSON source, you have to assume that any number literal can be either an `int` or `double`, so you only know it's a `num`. You are already assuming that the value is a number, so I'd just do:
```dart
double d = mapped['floatValue'].toDouble();
```
or if you prefer to avoid dynamic invocations:
```dart
double d = (mapped['floatValue'] as num).toDouble();
```

**Comment by jrvidotti** [comment]
My source is mine Node/TypeScript API. But Javascript's JSON.stringify() outputs 123.45 accordingly but 123.00 as 123.

[https://stackoverflow.com/questions/41399380/force-float-value-when-using-json-stringify](https://stackoverflow.com/questions/41399380/force-float-value-when-using-json-stringify)

[https://stackoverflow.com/questions/53005702/parse-float-with-decimals-to-json-in-javascript-also-for-1-as-1-00](https://stackoverflow.com/questions/53005702/parse-float-with-decimals-to-json-in-javascript-also-for-1-as-1-00)

I'll try harder to make my API outputs floats as floats but Node doesn't help.

**Comment by lrhn** [comment]
Indeed, JavaScript has it easier because it doesn't have a separate `int` type.

Dart has to choose (at least when not compiled to JavaScript), and it made more sense to make `123` decode as an integer than make *everything* a double. In most cases it's fine. In a few cases, it's not, and you have to treat your numbers as `num` and convert them to what you really want.

Other languages have even bigger problems. For example, Swift has both `double` and `decimal` types for non-integer values, and its JSON decoding picks ... `double` if the value fits in a `double`, and `decimal` if it doesn't. Java doesn't parse first and ask type questions later, instead you get a [`JsonNumber`](https://docs.oracle.com/javaee/7/api/javax/json/JsonNumber.html) which you can ask for the value of in various types.

Honestly, parsing JSON into an object structure and then interpreting the structure afterwards is wasteful and error-prone. It's better to ask for a specific type *before* parsing a JSON value, and then parse to that value.
