### ISSUE TITLE
Why does the Analyzer not infer non-null for Final Instance Fields?

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#42637]
As an extension of #42626, I was wondering why it does not work for final instance fields? Should analysis not be able to reason about that?

```dart
class Foo {
  const Foo({required this.bar});

  final void Function()? bar;

  void doSomething() {
    if (bar != null) {
       // Analyzer still complains that bar can be null.
      bar();
    }
  }
}
```

https://nullsafety.dartpad.dev/89a94765d6dba72ae652a5c911d4ccf6

**Comment by lrhn** [comment]
Instance fields can be overridden in subclasses. Even if you ca  see here that `bar` is final, you can't see that there isn't some class elsewhere doing:
```dart
class Bar extends Foo {
  void Function()? get bar => Random().nextBool() ? super.bar : null;
}
```
It would be silly, but again, the compiler needs guarantees, so it can't just assume that no-one is being silly.

So, Dart won't promote instance variables because it cannot guarantee that they won't change value between the check and the later read. It can't know that because someone might override the getter to do anything, even if the variable is final.

If you could make the field *sealed*, so it couldn't be overridden, then it might be possible to do something.

If you did `super.bar` to access the field, a non-virtual access, then it could also be possible to know exactly which getter is accessed, but that case is fairly rare. A top-level or static final field access is also non-virtual, and could be recognized as non-changing. In all three cases, that would lock that variable into being a final field. You couldn't change it to a getter returning the same value without breaking code depending on promoting it, and that might be code that you haven't written and is not even aware of existing. 
To keeps things simple, Dart has so far restricted type promotion to *local* variables. Not because there are no other specific cases which could work, but because making them work would have other side effects that are undesirable.

**Comment by creativecreatorormaybenot** [comment]
Good to know - it is a bit unintuitive, but I can understand the limitation 👍🏼
