### ISSUE TITLE
No error in CFE for not unique type alias

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42640]
The following code produces no error in CFE
```dart
// somelib.dart
library lib;

class A {}
typedef AAlias = A;

// test.dart
import "somelib.dart";
typedef AAlias = A;

main() {}
```
In `test.dart` alias AAlias is not unique and therefore it must be a compile error

**Comment by eernstg** [comment]
There is actually no conflict in this case, cf. [this paragraph](https://github.com/dart-lang/language/blob/dc1706a63788cb830b2114607be595b9cf90c749/specification/dartLangSpec.tex#L16340), because anything which is imported can be shadowed by a top-level declaration with the same name.

With the adjustment `A` --> `A Function()` (to avoid depending on a non-function type alias) both the analyzer and the front end correctly accept the program.

**Comment by lrhn** [comment]
Agree with Erik. The `typedef AAlias = A;` in `test.dart` shadows imports of the same name. You have to import both declarations in order to have a conflict.
