### ISSUE TITLE
Null safety feedback: overriding == requires to use dynamic

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/sdk#42687]
When testing NNBD in a small project, I soon realized that the linter was giving me the following error:

```
'Ace.==' ('bool Function(Object)') isn't a valid override of 'Object.==' ('bool* Function(dynamic)*').
```

The line is simply a override of the `==` operator:
```dart
@override
bool operator ==(Object other) => other is Ace;
```

If I replace `Object` with `dynamic` the code will work.

1. Why this change has been made and what it has to do with NNBD?
2. I avoid `dynamic` as much as I can, as it is very unsafe. Obviously, if there is no other way I will use `dynamic` in this case, but it this really necessary?

Thanks, in advance.

**Comment by lrhn** [comment]
This is because of Null Safety (nee NNBD).

When you implement `operator==`, you need to provide a valid override of the superclass `operator==`. If that class defined `operator==` to take `dynamic`, then you need to accept the same arguments that `dynamic` would allow.
Since `Object` does not allow `null` as a value, and `dynamic` does, using `Object` is not a valid override.

The superclass should probably be changing its type to `Object` too, but until then, you can use one of these alternatives:
```dart
 bool operator==(Object? o) => ...
 bool operator==(covariant Object o) => ...
```
Neither are particularly great, and it is a problem we are aware of.

**Comment by mateusfccp** [comment]
@lrhn I see. I did not realize that `dynamic` is a ever-nullable type, so this makes sense.

For now, I am going to use the `covariant` alternative and I am going to follow https://github.com/dart-lang/language/issues/1094 to be kept up-to-date with this question.

Thanks for your answer.
