### ISSUE TITLE
Type inference not working

### ISSUE THREAD

**Issue by nikitadol** [dart-lang/sdk#42766]
* Analyzer
* Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "macos_x64"

[I was advised to write this here](https://youtrack.jetbrains.com/issue/WEB-46251#focus=Comments-27-4278899.0-0)

```dart
void fun<E>(Iterable<E> iterable, Object Function(E element) idMapper) {
}
void main() {
  fun(<String>[], (element) => element);
}
```
Expected Result: element is String
Actual result: element is dynamic

![image](https://user-images.githubusercontent.com/16593680/87910516-d2351c80-ca72-11ea-85cc-cd0232a8b37f.png)
![image](https://user-images.githubusercontent.com/16593680/87910541-d95c2a80-ca72-11ea-84c5-31e29299ccc5.png)

**Comment by lrhn** [comment]
That's actually working as intended.

Dart does not make inference between arguments, so the type of one argument does not affect the other argument.

Here you write `fun(<String>[], (element) => element);` with 
```dart
void fun<E>(Iterable<E> iterable, Object Function(E element) idMapper) { ... }
```
There is no clue from the outside what `E` should be for this call, so both arguments are analyzed *independently*.
The type of the first one is `List<String>`, and the second is `Object Function(dynamic)` because there is nothing constraining the argument type of `(element) => element`. From that, `E` is inferred to be `dynamic` because that's the only type satisfying both arguments.

You'll have to either write the `fun<String>(...)` or make the function literal be `(String element) => element` to be able to infer that `E` should be `String`.

**Comment by nikitadol** [comment]
>so both arguments are analyzed independently.

But why?

Xcode and Swift
![Screen Shot 2020-07-20 at 12 12 55](https://user-images.githubusercontent.com/16593680/87920779-59d65780-ca82-11ea-806a-f490f291a3a7.png)

IntelliJ IDEA and Kotlin
![Screen Shot 2020-07-20 at 12 22 26](https://user-images.githubusercontent.com/16593680/87921752-b128f780-ca83-11ea-9c1c-bdfb7902c688.png)

**Comment by nikitadol** [comment]
@lrhn 
Can you reconsider this issue?

**Comment by lrhn** [comment]
We are aware of this particular short-coming of the current Dart type inference algorithm.
If we can find a way to make it better, and still solvable and mostly backwards compatible, we will do that. 
We don't currently have any such solution.
