### ISSUE TITLE
Ensure AOT apps for macOS ARM run correctly (dart compile exe)

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#42774]
Ensure dart2native apps generated for macOS ARM target work correctly on that platform.

**Comment by alexmarkley** [comment]
@a-siva I would like to propose that there are two separate issues here:

1. Future versions of dart2native should produce native code on Apple Silicon (and preferably "Universal" binaries) https://github.com/dart-lang/sdk/issues/43476

2. Current versions of dart2native should produce x86_64 binaries that work correctly under the Rosetta translation environment: https://github.com/dart-lang/sdk/issues/43477

**Comment by mit-mit** [comment]
@mkustermann you duped both of #43476 and #43477 into this, but as it seems reasonable to have a different timeline for Rosetta compatibility (most urgent) and full support for universal binaries? Or were you thinking we'd just got to universal binaries directly?

**Comment by mkustermann** [comment]
@mit-mit I'm going through unlabeled issues and was aware that @a-siva has open bug for dart2native regarding Apple Silicon already (which I assume covers both aspects), which is why I merged it into here.

Apologies if I misunderstood the intend here. @a-siva If you want to track those issues separately, please re-open #43476 and #43477

**Comment by alexmarkley** [comment]
@mkustermann I agree with the general principle of keeping the issue queue clean and organized.

FWIW I think Rosetta support for existing binaries is pretty different from Universal binary support. They probably have very different priorities and work efforts associated with them. But that's just my guess. 😄

**Comment by bdkjones** [comment]
Hi everyone. It's been a few months since this was opened. Has any progress occurred? The milestone is still ambiguous and Apple Silicon Macs are about 30-45 days from being in the wild (if Apple's "by the end of the year" statement holds true). Thanks!

**Comment by gkjpettet** [comment]
Where are we with this? Three new Apple Silicon Macs are shipping **next week** and the MacBook Air is Apple's most popular computer.

**Comment by bdkjones** [comment]
It’s been 5 months since anyone updated this issue and several projects are blocked on it. Apple Silicon is *here*. 

Development takes time, but surely someone at Google/Dart has a plan they can share? Just knowing an ETA and that someone is handling this would be very helpful—there are several tools blocked on this issue.

**Comment by mraleph** [comment]
(@a-siva assigning to you to reflect that you are driving this)

In general before we can fix `dart2native` we should be able to produce a `dart`/`dart_precompile_runtime` binary for Mac OS ARM64 target - and we currently can't because we are blocked on https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=67614

**Comment by bdkjones** [comment]
@a-siva It looks like Rosetta might be going away in some parts of the world with the next update to macOS: https://twitter.com/SteveMoser/status/1366904041243041794?s=20

It would be nice if Dart could get on board before that happens.

**Comment by franklinyow** [comment]
@a-siva Should this move out of April?  Which Milestone we're looking at?

**Comment by a-siva** [comment]
This works now when we do local builds, marking as fixed. We have https://github.com/dart-lang/sdk/issues/42773 tracking the broader issue of building/testing the new configuration on the bots.
