### ISSUE TITLE
No way to include "sourcesContent" field in source map generated by dart2js

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#42782]
Dart SDK 2.8.4. The `sourcesContent` field in source maps allows the files to be embedded, rather than have them on disk, which may not be possible. In my case, I don't have the source files in the same location as the source map. I believe [source_maps](https://pub.dev/packages/source_maps) has this capability.

**Comment by jakemac53** [comment]
Note that you could post-process source maps yourself to add this field. I don't know if this is something the dart2js team feels is worth adding but I moved it to the sdk repo where that is developed.

**Comment by sigmundch** [comment]
Thanks for your request!

I agree with @jakemac53 , I think this is a better fit for post-processing the source-map file. This post-processing may be superficial enough that you could amend the source-map file by processing the JSON directly, without necessarily having to depend on the source_maps internal logic.

We generally prefer post-processing this file because there are many variations on server-side configurations and adjustments are often needed. We have seen already several customizations in the wild: changes to fit a development server layout, changes to append revision hashes as query parameters to help triage issues in production, and changes to improve the development experience with chrome extensions.
