### ISSUE TITLE
missing readAsBinaryString in dart:html.FileReader

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#42834]
in ```dart:html``` you currently have:

```
  void readAsArrayBuffer(Blob blob) native;

  @JSName('readAsDataURL')
  void readAsDataUrl(Blob blob) native;

  void readAsText(Blob blob, [String? label]) native;
```

```readAsBinaryString``` is missing.

**Comment by srujzs** [comment]
Hi,

Thanks for filing this. `FileReader` and other `dart:html` APIs are generated off of old Chrome IDL files that we aren't planning to update currently due to the complexity involved. As such, they can be stale and be missing methods, getters/setters, etc. which you have seen firsthand. We're hoping to be able to provide external static extension methods to handle these missing members, but it's still WIP.

In the meantime, a workaround would be to use `js_util` to accomplish what you need e.g. `js_util.callMethod(reader, `readAsBinaryString`, ...)`.

**Comment by jodinathan** [comment]
closing because the package [js_bindings](https://pub.dev/packages/js_bindings/versions/0.0.4-dev) exposes it correctly.
