### ISSUE TITLE
Unnecessary cast of a function? (Null Safety migration tool)

### ISSUE THREAD

**Issue by michalt** [dart-lang/sdk#42871]
Consider the following code:

```dart
int foo(List<int> list) {
  return list.firstWhere((n) => n == 42,
      orElse: (() => throw StateError('error')));
}
```

The migration tool produces:

```dart
int  foo(List<int >  list) {
  return list.firstWhere((n) => n == 42,
      orElse: ((() => throw StateError('error')) as int Function()?));
}
```

It's ok wrt. nullability, but AFAICS the cast is redundant (and I even get warnings that it's unnecessary).

**Dart SDK version**: 2.10.323325861-edge+google3-v2

CC @stereotype441

**Comment by stereotype441** [comment]
Thanks, Michal.  I suspect what is happening is that the migration tool is incorrectly considering the migrated closure `() => throw StateError('error')` to have the type `Null Function()`, so it's trying to insert a cast because that type is not assignable to the expected type (`int Function()?`).  To fix this, we probably need some special logic to handle closures that always throw, or we need the migration tool's FixBuilder to hook better into the existing analyzer logic that inferres the return types of closures.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
