### ISSUE TITLE
Proxy direct access issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42870]
The following tests fails now
```dart
import "dart:io";
import 'dart:async';
import "dart:convert";

test() async {
  bool findProxyCalled = false;
  bool authenticateProxyCalled = false;
  int requestCounter = 0;

  HttpServer server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
  server.listen((HttpRequest request) {
    if (requestCounter++ == 0) {
      request.response.statusCode = HttpStatus.unauthorized;
      request.response.headers
          .set(HttpHeaders.proxyAuthenticateHeader, 'Basic, realm=realm');
      request.response.statusCode = HttpStatus.proxyAuthenticationRequired;
      request.response.close();
    } else {
      request.response.close();
      server.close();
    }
  });
  HttpClient client = new HttpClient();
  client.findProxy = (Uri uri) {
    findProxyCalled = true;
    return "DIRECT";
  };

  client.authenticateProxy =
      (String host, int port, String scheme, String realm) {
    authenticateProxyCalled = true;
    Completer<bool> completer = new Completer<bool>();
    completer.complete(true);
    return completer.future;
  };

  client
      .getUrl(Uri.parse(
      "http://${InternetAddress.loopbackIPv4.address}:${server.port}"))
      .then((HttpClientRequest request) => request.close())
      .then((HttpClientResponse response) {
    response.cast<List<int>>().transform(utf8.decoder).listen((content) {});
  });
}

main() {
  test();
}
```
The failure is
```
dart --enable-experiment=non-nullable,nonfunction-type-aliases findProxy_A01_t01.dart
Unhandled exception:
type 'Null' is not a subtype of type 'String' of 'host'
#0      test.<anonymous closure> (file:///co19/LibTest/io/HttpClient/findProxy_A01_t01.dart)                                         
#1      _HttpClientResponse._authenticate.requestAuthentication (dart:_http/http_impl.dart:477:33)
#2      _HttpClientResponse._authenticate (dart:_http/http_impl.dart:544:33)
#3      _HttpClientRequest._onIncoming (dart:_http/http_impl.dart:1180:25)
#4      _HttpClientConnection.send.<anonymous closure>.<anonymous closure> (dart:_http/http_impl.dart:1851:17)
#5      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
If to change 
```
    return "DIRECT";
->
    return "PROXY ${InternetAddress.loopbackIPv4.address}:${server.port}; DIRECT";
```
tests begin to work. But why direct connection doesn't work?

`Dart SDK version: 2.10.0-1.0.dev (dev) (Tue Jul 28 12:21:35 2020 +0200) on "windows_x64" `

**Comment by vsmenon** [comment]
fyi @zichangg @lrhn

**Comment by zichangg** [comment]
The bug was introduced during null safety migration. We need a breaking change to update two APIs.

[authenticate](https://api.dart.dev/stable/2.9.2/dart-io/HttpClient/authenticate.html) and [authenticateProxy](https://api.dart.dev/stable/2.9.2/dart-io/HttpClient/authenticateProxy.html) should have `realm` being `String?`. It can be nullable by definition.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authenticate

**Comment by lrhn** [comment]
Agree. Checking the code of `http_impl.dart`, the `_authenticate` function is internally typed as `Function`, and only called as:
```dart
        return authenticate(_httpRequest.uri, scheme.toString(), realm);
```
where `realm` is a `String?`.

Lesson: If we had typed the field, instead of falling back on `Function`, we would have noticed this discrepancy.

**Comment by munificent** [comment]
@lrhn, are you going to fix this? Do you want me to take a look?

**Comment by lrhn** [comment]
I'll fix it. Thanks for noticing.

**Comment by franklinyow** [comment]
@lrhn P2?

**Comment by lrhn** [comment]
See: https://dart-review.googlesource.com/c/sdk/+/170094

**Comment by sgrekhov** [comment]
@lrhn now, after the fix, test from this issue description timeouts.  What should be changed to make it working?

**Comment by lrhn** [comment]
If I run just the test (jsut the code cut-n-pasted into a file), I get a null-safety error:
```
badprox.dart:30:7: Error: A value of type 'Future<bool> Function(String, int, String, String)' can't be assigned to a variable of type 'Future<bool> Function(String, int, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
      (String host, int port, String scheme, String realm) {
      ^
```
Adding a `//@dart=2.10` line at the top, the code does indeed hang. I added some more `print` lines to see what's going on.

It seems the server only receives one request, and since it's written to close on the second request, that makes it stay listening and keep the program running. I only see one request being sent, so to me that looks like the correct behavior.
(I could be missing something, I'm not particularly well-versed in HTTP server code).

The `authenticateProxy` function isn't called either, probably because the `findProxy` function returns "DIRECT", so there is nothing to authenticate. (Again, I'm guessing.).

So, what would you expect the example code to do? Which functions should get called in which order, and why?

**Comment by sgrekhov** [comment]
@lrhn I was under impression that this test worked before NNBD and become timeouted after NNBD (and after the fix mentioned in this issue). But I retested it in co19_2 (which is pre-NNBD version od co19 tests) and found that it timeouts there as well. Seems this test is simply wrong and needs to be fixed. Sorry for bothering.

BTW I believe this issue can be closed so I'm closing it. Please reopen if there are any reasons to keep it open
