### ISSUE TITLE
Code completion doesn't suggest from dev_dependencies, but manually referencing classes does not generate errors/warnings

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#42873]
I had reports of code completion missing some classes that were valid in the current scope, for example `Provider` here:

<img width="549" alt="Screenshot 2020-07-29 at 14 51 10" src="https://user-images.githubusercontent.com/1078012/88808614-06af8380-d1ab-11ea-8551-62a97899102d.png">

It turned out that the `provider` package was listed in `dev_dependencies` and it seems like these should not be used in the `lib` folder:

https://github.com/dart-lang/sdk/blob/5b18fa0798d39a5a9fe379e104cd28b9d2983252/pkg/analyzer/lib/src/services/available_declarations.dart#L176-L178

However, typing these classes manually does not generate any warnings/errors, and as far as I can tell there is no lint for this.

If it's not valid to import `dev_dependencies` into `lib`, it seems like an error/warning should be generated? If it is, then it seems like they should be included in completion?

**Comment by bwilkerson** [comment]
This is a long standing issue (as old as `pub`). The problem is that when `pub` generates the `package_config.json` file it only generates one file that includes the transitive closure of both dev and non-dev dependencies. It really ought to be generating two files, one for use in `lib` and one for use outside `lib`.

Baring such a change, yes, it would be good for the analyzer to add
- a hint for imports of packages that are in the dev dependencies in libraries inside `lib` and
- a lint for imports of packages that are not listed in the `pubspec.yaml` file (indirect dependencies).

I think there's a separate issue for the second, so we can use this issue for the first.

**Comment by DanTup** [comment]
If I understand correctly, I think https://github.com/dart-lang/linter/pull/2659 / https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html addresses both of the descriptions above?

**Comment by DanTup** [comment]
@bwilkerson does the lint above cover everything desired here? If so, I think this can be closed.

**Comment by bwilkerson** [comment]
Yes, I think it does.
