### ISSUE TITLE
dartdevk throws RangeError instead of StackOverflowError

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42893]
The following test fails on dartdevk 
```dart
import "../../../Utils/expect.dart";

class C {
  static var x = f();
  static f() => x + 1;
}

main() {
  try {
    C.x;
    Expect.fail("StackOverflowError should be thrown");
  } on CyclicInitializationError catch (e) {
    Expect.fail("StackOverflowError should be thrown");
  } on StackOverflowError catch (e) {}
}
```
dartdevk produces
```
Runtime error:
RangeError: Maximum call stack size exceeded
...
```
There must be `StackOverflowError` or `CyclicInitializationError` but not `RangeError`

**Comment by lrhn** [comment]
I'm not sure the specification states what must happen on a stack overflow. The `StackOverflowError` class, and its constant instance, is there for convenience, so that a stack overflow can be reported without allocating a new object.

Throwing a `RangeError` with a message clearly mentioning the stack as a reason, is not *wrong*. It would be *convenient* if we could make it a `StackError` instead, but if that's too hard, I'm personally fine with keeping it as-is.

You are not expected to catch and handle an `Error`, so it doesn't really matter which `Error` is thrown. The different error classes exist to make the error messages more uniform, not because you are supposed to distinguish one kind of error from another.

It would be convenient

**Comment by eernstg** [comment]
The language specification [requires](https://github.com/dart-lang/language/blob/a9c5adf0dbf532a9e22617748817ac40d9496a0d/specification/dartLangSpec.tex#L10087) a dynamic error on stack overflow and out-of-memory events. It never mentions `StackOverflowError` and doesn't specify a specific exception to throw in these situations.

I agree with @lrhn that this is less informative for the person who gets the error message, but that it shouldn't matter during development because dynamic errors are not intended to be handled in any detail programmatically. So the test should just verify that a dynamic error occurs.

However, [a `CyclicInitializationError` should be thrown](https://github.com/dart-lang/language/blob/a9c5adf0dbf532a9e22617748817ac40d9496a0d/specification/dartLangSpec.tex#L1187) in legacy mode, long before the memory issue arises. So this issue should be used to report that.

However, that makes this issue a duplicate of #22141. So I'll close this one.
