### ISSUE TITLE
On the VM it is possible to get Type objects which are equal but have different hash codes

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#42954]
The doc comment for `hashCode` says "Hash codes must be the same for objects that are equal to each other according to `operator ==`.". This property is not followed on the VM by `Type` in some cases. Either the VM should follow this contract or we should add a clear indication of this behavior in the documentation for `Type`.

```dart
class A<T> {
  Type get type => T;
}

class B extends A<B> {}

void main() {
  var first = B;
  var second = B().type;

  print(first == second); // `true`
  print(second == first); // `true`
  print(first.hashCode == second.hashCode); // `false`, should be `true`
}
```

**Comment by natebosch** [comment]
This first came up in a gitter channel. https://gitter.im/dart-lang/sdk?at=5f2b126aa541217404e114d3

**Comment by crelier** [comment]
Interestingly, I can only reproduce this issue if I do not enable the nullable experiment:

```
$ dart --enable-experiment=non-nullable ~/bug.dart
true
true
true
```

```
$ dart ~/bug.dart
true
true
false
```

I'll have a closer look.

**Comment by natebosch** [comment]
> Interestingly, I can only reproduce this issue if I do not enable the nullable experiment:

This reproduces for me either with or without the experiment. I tried it at `2.10.0-3.0.dev (dev)` and `2.10.0-edge.9c774d796bec2deab38c1eb2155cdad9e6d24a84 (be)`

**Comment by crelier** [comment]
I understand what is going on. It is a bug in the VM related to computing hashes for recursive types and it has nothing to do with null safety. Note how the type argument of the base class in the example refers to the derived class. In the VM, this is represented by a TypeRef node in the graph of the recursive type in order to break the cycle. The location of TypeRefs in the type graph can vary (depending in the order the graph is built), which in turn affects the hash value. A CL is on its way. Thanks for the report!

**Comment by crelier** [comment]
This should now be fixed.

**Comment by crelier** [comment]
Reopening, until reverted CL is relanded.

**Comment by crelier** [comment]
This should now be fixed, really.
