### ISSUE TITLE
--package-root has disappeared from dart exe

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#42960]
I've just upgraded to dart 2.9 and found that the --package-root switch seems to have been removed from the dart command

I use the --package-root with my project dshell:

https://pub.dev/packages/dshell

I'm hoping this was a mistake or else there is an alternate method of doing this?

Dart 2.8 shows:

```
dart --help
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

Executes the Dart script <dart-script-file> with the given list of <script-arguments>.

Common VM flags:
--enable-asserts
  Enable assert statements.
--help or -h
  Display this message (add -v or --verbose for information about
  all VM options).
**--package-root=<path> or -p<path>**
  Where to find packages, that is, "package:..." imports.
--packages=<path>
  Where to find a package spec file.
```

Dart 2.9 shows
```
dart --help
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]

Executes the Dart script <dart-script-file> with the given list of <script-arguments>.

Common VM flags:
--enable-asserts
  Enable assert statements.
--help or -h
  Display this message (add -v or --verbose for information about
  all VM options).
--packages=<path>
  Where to find a package spec file.
--observe[=<port>[/<bind-address>]]

```

**Comment by lrhn** [comment]
The `--package-root` has effectively been deprecated since `.packages` was introduced, and was not supported by most of the Dart tools. 

We have now introduced another format for the package resolution file (the `.dart_tool/package_config.json` file, which is, as the name suggests, a JSON file). You *will* need to use that file in the future, it's the only way to get language versioning to work, which is needed to migrate to null safety. Because of that, we have now removed the last vestiges of package-root support.

The alternative is to create a [`package_config.json` file](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md). You can read and write it using the [`package:package_config` package](https://pub.dev/packages/package_config).

**Comment by bsutton** [comment]
Thanks for the response.

So I'm a little confused by the statement:

> The Pub tool automatically generates this file (just like it previously generated the .packages file, and actually still does for migration purposes, even though that file will stop working correctly when we release Dart 2.10).

Which file are you referring to?
If you are referring to the 'package_config.json' file then I'm doubly confused as you seem to be saying to use it but that it will be deprecated in 2.10.
Or do you mean that the .packages file will stop working in 2.10. That probably makes more sense.

I've been using the --package-root flag to tell dart to find the packages in a directory other than the standard locations.

A core concept behind dshell is to allow a user to create a 'single file' dart script.  Dshell does this by generating the pubspec.yaml and associated tooling in a different directory to the dart script and uses -package-root to tell dart where to find these files.

**Comment by bsutton** [comment]
OK, panic averted.

I though this changed had completely broken dshell :<

But i've just change to --package and all works as before.

Thanks for the prompt response.
