### ISSUE TITLE
Analyzer fails to recognize a function as callable

### ISSUE THREAD

**Issue by joebingham-wk** [dart-lang/sdk#42975]
Inside of a function, the analyzer fails to recognize a callable function when that function is the return value of a provided callback.

When invoking the return value of the callback, the analyzer shows an error with: `The expression doesn't evaluate to a function, so it can't be invoked`. This only happens when the type of the returned function is typed as a type parameter.

Reduced test case:
```dart
void test<F extends Function()>(F Function() getFunction) {
  final f = getFunction();
  f(); // no error
  getFunction()(); // error
  (getFunction() as F)(); // error
}
```

Dart SDK Version:
- 2.7.2
- 2.8.4
- 2.9.0

**Comment by eernstg** [comment]
An expression of type `F` with bound `Function()` should be callable (it is "function-type bounded"), so the program should be accepted. The following variant runs with no issues on `dart`, so it's an issue with the analyzer alone:

```dart
void test<F extends Function()>(F Function() getFunction) {
  final F f = getFunction();
  f();
  getFunction()();
  (getFunction() as F)();
  print("Done");
}

void main() {
  test(() => () {});
}
```

**Comment by greglittlefield-wf** [comment]
Related issue that this may or may not duplicate: https://github.com/dart-lang/sdk/issues/30104

**Comment by eernstg** [comment]
https://github.com/dart-lang/sdk/issues/30104 is actually different, so there is no duplication:

This issue is about invocations of an object whose type is a subtype of a function type (`F extends Function()`), and the problem is that the analyzer makes it an error (just tried it again: dartpad.dev contains an analyzer that still reports these errors).

#30104 is about a classes `Foo` and `MockFoo` with a method named `call`. Instances of such classes have a type which is not a function type (nor a subtype of a function type), so that's a different part of the static analysis.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/191181 fixes this.
