### ISSUE TITLE
CFE: Compiling with --no-sound-null-safety should print a warning

### ISSUE THREAD

**Issue by franklinyow** [dart-lang/sdk#43007]
Any dart tool that compiles code with the unsound null safety mode (i.e. under the flag `--no-sound-null-safety`) should print a warning:

```
Warning: Packages foo and bar are not null safe, so compiling in unsound mode.
```

**Comment by johnniwinther** [comment]
Is this only for using `--no-sound-null-safety` explicitly? What about when using `--enable-experiment=non-nullable` (which defaults to weak), should it be reported here?

**Comment by leafpetersen** [comment]
The experiment doesn't matter either way, I don't think, that's a temporary state.

**Comment by mit-mit** [comment]
Updating to reflect that we'll only do this for compilation

**Comment by johnniwinther** [comment]
When running `dart` there is no distinction between running and compiling (the VM internally calls the CFE before running the code), so if the CFE emits the warning the wording will not match the user experience; running `dart` and the message has "compiling" or running `dart2js`/`ddc` and the message has `running`.

It seems weird to warn about running in unsound mode if that was what the user explicitly asked for by using `--no-sound-null-safety` - and the wording shouldn't indicate that we chose to run in unsound mode due to some libraries being unsound - that is not why we are not running in unsound mode. And even more if all libraries are null safe we can still run in unsound mode by request.

I don't know the background for wanting this message but to me it makes must sense to warn if we (automagically) chose weak mode, but then again we don't do this based on the existence of null unsafe libraries but based on the opt-in state of the entry point library.

**Comment by mit-mit** [comment]
@johnniwinther let me discuss a bit with the language team and get back to you.

**Comment by mit-mit** [comment]
We discussed in language meeting, and agreed that we don't need to produce this warning anyway. Resolving as Won't fix.
