### ISSUE TITLE
Implement "experiment release versions" in the analyzer

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#43032]
See the meta issue https://github.com/dart-lang/sdk/issues/43031

**Comment by scheglov** [comment]
Implementation in the analyzer is landed, but `experimental_features.yaml` needs to be updated, so that we can fill `experimentalReleaseVersion` field for features.

@jakemac53 I don't see the corresponding item in https://github.com/dart-lang/sdk/issues/43031, should we give some version to `non-nullable`?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/159383 will update `experimental_features.yaml`.

**Comment by jakemac53** [comment]
2.10 is the expected version, I added a line item list to the meta issue but didn't create another github issue given that you already have a cl out
