### ISSUE TITLE
[nnbd] Flow analysis does not track non-null assignment to globals locally

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#43047]
I would expect non-null assignment to nullable globals to refine the type locally to non-null.

I would expect this to work:

```dart
int myFunction(int a) => a + 1;

int Function(int)? f;

doCachedF(int a) {
  f ??= myFunction;
  return f(a);
}
```

Error:

```
Error: Can't use an expression of type 'int Function(int)?' as a function because it's potentially null.
Try calling using ?.call instead.
  return f(a);
          ^
```

The work around works:

```dart
int myFunction(int a) => a + 1;

int Function(int)? f;

doCachedF(int a) {
  f ??= myFunction;
  return f!.call(a);
}
```

@leafpetersen 

source: https://dart-review.googlesource.com/c/sdk/+/158545/2/tests/ffi/regress_43016_test.dart

**Comment by eernstg** [comment]
This is actually working as intended: There is no support for promotion of non-local variables of any kind (top-level, static, instance), only for local variables. It wouldn't be sound to rely on `f` having a non-null type if any unknown code is executed (for instance, if any instance method is invoked on any object), because that code could assign null to `f`.
