### ISSUE TITLE
List runtimeType is not consistent with dart2native

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#43071]
var list = [1, 2, null];
print(list.runtimeType);
It will print List< int?>, but in native exec file it print _GrowableList< int>

**Comment by julemand101** [comment]
And the problem is? `runtimeType` returns the exact type of the object on runtime which will often be different for core types in Dart since they are implemented differently on different platforms.

This is just one of many reasons why you should almost never use `runtimeType` for anything other than debugging purposes since you very often don't really want the precise type of a given object but instead want to ask the question "what type is this object compatible with?" which you use the `is` operator for.

lrn have written a great answer on stackoverflow about the usage of `runtimeType` here:
https://stackoverflow.com/a/42802802/1953515

**Comment by lrhn** [comment]
As @julemand101 says, it's expected behavior.

There are no promises that `runtimeType` will return anything except a `Type` representing the type of the object.
The `List` classes are implemented differently on different platforms. In the VM, a growable list is implemented by a class named `_GrowableList`, and that's what its `runtimeType` shows. When compiling to JavaScript, the growable list is implemented using a JS `Array`, and the `runtimeType` is emulated, so there is no Dart class that it can return. That's why it returns a `Type` object for the `List` interface type. 
You can also override `runtimeType` to have it return any `Type` object. That's also what the VM does for integer types where it actually has multiple implementation classes internally, but they all return the `Type` object for the interface type `int`.

So, working as intended, no current plan to change it. With `runtimeType`, the only winning move is not to play.
