### ISSUE TITLE
decouple representation of function signatures from Function objects

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43088]
We currently use `Function` objects to represent two different things: 

* invocable entity (e.g. a member of a class)
* signature for function types

This is somewhat confusing but also leads to very surprising results when we perform tree shaking.

Consider for example a class declaration like this:

```dart
class C {
  void m() { }
}
```

if we decide to create an implicit closure for `m` this closure would have signature type `Function Type: (dynamic) => void` which will point back to `C.m_m` (implicit closure `Function`) as its `signature`.

If this type gets canonicalised ahead of any other `(dynamic) => void` type then suddenly we have class `C` being indirectly retained by a type that does not even mention it. Even if in the end tree shaker throws most of `C` implementation away `C` and `C.m` will linger behind retained by the signature.  

There might be some workarounds for this problem (e.g. we could create fresh signature functions to use as signatures for tear off extractors) but the real fix would be to decouple representation of _function signature_ from the notion of the function in its entirety.

**Comment by mraleph** [comment]
internal bug that lead to discovery of this b/165124315

**Comment by crelier** [comment]
The decision to use `Function` objects for both purposes was made many years ago, when we did not have a tree shaker yet. The idea was to save memory by sharing the existing `Function` object to hold the signature of a type, rather than allocate a new object and copying its parameter types and result type (type parameters came later).

So I would argue that the issue here (b/165124315) is with the tree shaker, which does not distinguish between both usages of a `Function` object and fails to ignore certain fields of the `Function` object when it is only used as a signature function. Obviously, that would be too difficult to address in the tree shaker and I totally agree that sharing the same object is confusing and should be cleaned up at this time.

As you suggest, it would be best to decouple usages and have 2 different VM objects for functions and signatures (rather than reallocate fresh `Function` objects for function types, which would definitely waste memory space). Maybe we could even maintain some form of sharing by having the `Function` object refer to a `Signature` object, which can be reused in the function type upon closurization. I can start working on this and see what's feasible.

As a side note, we also use the same `TypeParameter` object to represent both the declaration of a type parameter and also the uninstantiated type referring to a type argument. The list of type parameters declared by a class of a function is represented by a `TypeArguments` object, which is quite confusing. But that's for a different CL :-)

**Comment by mraleph** [comment]
> So I would argue that the issue here (b/165124315) is with the tree shaker, which does not distinguish between both usages of a Function object and fails to ignore certain fields of the Function object when it is only used as a signature function.

I actually agree with this - I have spent a bit more time looking at this and the problem seems to originate from `Precompiler::AttachOptimizedTypeTestingStub` which visits the whole heap searching for type objects and then stumbles over a type which refers to the function and causes it to be retained - such unstructured visiting is problematic in itself. 

I do understand that the original implementation was chosen for a reason. I guess I should have phrased myself a bit differently, instead of saying "but the real fix would be to decouple representation" - I should have said "decoupling representation would make it easier to reason about the code and consequently fix the problem".

> As you suggest, it would be best to decouple usages and have 2 different VM objects for functions and signatures (rather than reallocate fresh Function objects for function types, which would definitely waste memory space). Maybe we could even maintain some form of sharing by having the Function object refer to a Signature object, which can be reused in the function type upon closurization. I can start working on this and see what's feasible.

Yeah, I was thinking along the same lines - move signature parts of function into a separate class and reference this class from both `Function` and `Type`. I would appreciate if you could asses how feasible it is - if you have some cycles. You certainly are more familiar with this part of the code than me.

**Comment by crelier** [comment]
Sure, no problem. I'll look at it.

**Comment by a-siva** [comment]
would it be fine to mark this as a P2 issue and give it the October milestone ?

**Comment by crelier** [comment]
Sure.

**Comment by a-siva** [comment]
Work on this is progressing see (https://dart-review.googlesource.com/c/sdk/+/164684), this will however not be ready to land by end of this week, moving milestone to November.

**Comment by a-siva** [comment]
Work on this is progressing, this is not.a requirement for the null safety release, moving milestone accordingly.
