### ISSUE TITLE
Converting object to an encodable object failed: Instance of '_CompactLinkedHashSet<String>'

### ISSUE THREAD

**Issue by amitkhairnar44** [dart-lang/sdk#43107]
### Dart Version
```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (6 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```
### Issue
When I'm trying to encode a Set of strings it is giving an error.
`Converting object to an encodable object failed: Instance of '_CompactLinkedHashSet<String>'`

### Reproduce Error
Error reproduced in DartPad : https://dartpad.dev/c8a014b237d2bcbf8c08af1e5e9bf254

**Comment by devoncarew** [comment]
It looks like `Set` isn't supported by the json encoder, which is a bit surprising to me. Changing your example to `List<String>` worked.

I think this is working as intended, but will triage this to our dart:convert library area to confirm.

**Comment by lrhn** [comment]
Sets are not accepted by the JSON encoder. The only things accepted by default as JSON values are numbers, strings, booleans, null, lists of JSON values and maps from strings to JSON values. That's the basic structure of JSON, there is no set representation in JSON.
If you want to store anything else as JSON, you will need to find a way to encode it into JSON values, and you need to decode it yourself again, because JSON values are the only thing JSON can actually represent.
We could choose to serialize all iterables as sets, but then it won't roundtrip well.

**Comment by amitkhairnar44** [comment]
@lrhn You're right. 
Instead of Set<String> i should use List<String>.
