### ISSUE TITLE
vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test timeouts

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#43132]
The flaky test timeouts on precomp-linux-simarm bots.

The tests
```
vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test Timeout (expected Pass)
```
are failing on configurations
```
dartkp-linux-release-simarm
```

log: https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-simarm/dartkp-linux-release-simarm/9761/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test

https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-simarm64/dartkp-linux-release-simarm64/9636/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test

**Comment by zichangg** [comment]
Another failure: https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-simarm_x64/dartkp-linux-release-simarm-crossword/2306/vm/dart_2/causal_stacks/async_throws_stack_lazy_non_symbolic_test

**Comment by devoncarew** [comment]
@zichangg - when you open issues, can you assign an `area-` label to them (when you know what it should be)? Thanks!

**Comment by cskau-g** [comment]
/cc @sstrickl since these are all `--dwarf-stack-traces`.

At a cursory glance there's not much to go by though.
We need to do a deeper dive to figure out if it's one particular part that's hanging and why.

(A wild guess could be that since the CL that triggered it was updating the root certs, perhaps something using the certs like the service protocol could've run into cache issues and hung?? Does the simulator use certs?)

**Comment by askeksa-google** [comment]
The test seemingly went from flaky to always timing out.

**Comment by mkustermann** [comment]
This test doesn't seem to time out anymore. Assumed stale.
