### ISSUE TITLE
Map.castFrom does not work as advertised, causes runtime error

### ISSUE THREAD

**Issue by johngithubby** [dart-lang/sdk#43154]
```
//snapshot is a Firebase DataSnapshot
final dynamicMap = (event.snapshot.value as Map<dynamic, dynamic>); 
Map<String, Map<String, String>> map =
Map.castFrom<dynamic, dynamic, String, Map<String, String>>(dynamicMap);
for (var title in map.keys) {
        //line below causes Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>?' in type cast
        print(map[title]);
 }
```
Dart SDK version: 2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "macos_x64"

**Comment by lrhn** [comment]
This is working as intended.

The `cast` operation, and `castFrom` constructor backing it, wraps the `Map<dynamic, dynamic>` into a `Map<String, Map<String, String>>` by casting (using `as`, not `.cast`) all keys to strings and all values to `Map<String, String>`.
It works only if the keys and values actually have that type. Here, they don't. The values are not instances of `Map<String, String>`, rather they are `Map<String, dynamic>` which contains only `String` values (I assume).
So, when you try to read a value, you get an error because a `Map<String, dynamic>` fails with `as Map<String, String>`.

There is no recursive cast operation which will `.cast` the values. You really do need to make another map, perhaps by:
```dart
Map<String, Map<String, String>> map = {for (var k in dynamicMap.keys) k: (dynamicMap[k] as Map()).cast()};
```
