### ISSUE TITLE
Dart analyzer shows an old error after code generation.

### ISSUE THREAD

**Issue by KlausJokisuo** [dart-lang/sdk#43166]
I'm having issues with the analyzer showing old errors on IDE (IntelliJ) when using code generation. Below you can find more information about this issue and a sample project which you can use to reproduce the issue.

Related issue: https://youtrack.jetbrains.com/issue/WEB-45208
Sample project: https://github.com/KlausJokinen/Jetbrains_code_generation_fail
Comment with a video which shows how the error occurs: https://youtrack.jetbrains.com/issue/WEB-45208#focus=Comments-27-4300830.0-0

**Comment by devoncarew** [comment]
Where are you generating the generated dart files? If it's within the regular source, the analysis server should see the changes. If it's in the .dart_tool/ directory, I believe this is a known issue - we don't watch for changes in that directory, so won't see updates until the analysis server is restarted.

**Comment by KlausJokinen** [comment]
Files are generated next to source files (lib/models). The analyzer works correctly depending on what we are generating. The file in the example project triggers the failure (https://github.com/KlausJokinen/Jetbrains_code_generation_fail/blob/master/lib/models/application_state/application_state.dart).

**Comment by alexander-doroshko** [comment]
I can reproduce the problem using https://github.com/KlausJokinen/Jetbrains_code_generation_fail project and Flutter SDK 1.20.2 (Dart SDK 2.9.1). Steps:
- Run `flutter pub get` before opening the project
- Open the project in the IDE, configure Flutter SDK (if not yet), open Dart Analysis tool window, there will be 4 hints. So far so good.
- Delete `application_state.freezed.dart` file. **Problem:** corresponding errors do not appear in the Dart Analysis view.
- Restart Dart Analysis Server. Errors appear as expected.
- Restore `application_state.freezed.dart` (luckily it's in Git, use IntelliJ's Git tool window and its Rollback button). **Problem:** errors do not disappear in the Dart Analysis view.
- Restart Dart Analysis Server. No errors again as expected.

I looked through the Analysis Server instrumentation logs. I can confirm that server receives file deleted / file created creation events. But I can also confirm that it doesn't send updated errors to the IDE.

**Comment by KlausJokinen** [comment]
@alexander-doroshko Great to hear that you were able to pinpoint the issue. @devoncarew  @alexander-doroshko Let me know if I can be more of assist.

**Comment by KlausJokinen** [comment]
Is there any news on this? The development is quite painful because you don't know what error is "real" and what is not.

**Comment by KlausJokinen** [comment]
@devoncarew Is there something I could do to help fix this issue? I've now noticed that this is not just the Freezed package, but code generation in general.

**Comment by alexander-doroshko** [comment]
Сс @bwilkerson @scheglov. Steps to reproduce: https://github.com/dart-lang/sdk/issues/43166#issuecomment-682130478

**Comment by mzdm** [comment]
I have today followed @alexander-doroshko [comment](https://github.com/dart-lang/sdk/issues/43166#issuecomment-682130478) and it is still reproducible

**Comment by ksilz** [comment]
@KlausJokisuo I suffer from the same problem. See my [post at the IntelliJ forum](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010319179-Flutter-IntelliJ-doesn-t-update-after-flutter-pub-run-build-runner-build-). What helps me is to close the IntelliJ project and re-open it. Then IntelliJ recognizes all changes.

**Comment by scheglov** [comment]
I can reproduce the issue.

It seems that we get the remove file notification from the file system watcher, but fail to propagate it to the analysis driver.
I will continue debugging to find where we fail to continue.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/181280

**Comment by KlausJokisuo** [comment]
> @scheglov Is this supposed to be fixed? It still happens for me. It never stopped, for that matter.
> 
> * IntelliJ IDEA 2020.3.2 (Ultimate Edition), Build #IU-203.7148.57, built on January 26, 2021
> * Runtime version: 11.0.10+9-b1319.7 x86_64, VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> * Flutter plugin: 54.0.3
> * Dart plugin: 203.7759
> 
> ![Still not recognized](https://user-images.githubusercontent.com/1061209/110660311-56cbdb00-81bb-11eb-832d-007d090a3460.gif)

Not sure why this issue is closed. I had a little break from Flutter development and wasn't able to test this before. But yeah the issue is still valid and the fix is not working.

**Comment by scheglov** [comment]
It works for me now, with the latest Dart SDK.
```console
scheglov@scheglov-macbookpro2:~/Source/Dart/sdk.git/sdk (master)$ dart --version
Dart SDK version: 2.13.0-edge.97655f06b526a5ce1efb6bba7eadd6ebfd00e950 (be) (Tue Mar 9 23:40:02 2021 +0000) on "macos_x64"
```

I think you can get a very close SDK version by trying Flutter `master` channel.
```console
scheglov@scheglov-macbookpro2:~/Source/Dart/sdk.git/sdk (master)$ flutter upgrade
Flutter is already up to date on channel master
Flutter 1.27.0-9.0.pre.24 • channel master • git@github.com:scheglov/flutter.git
Framework • revision 9b6d267ea3 (2 weeks ago) • 2021-02-22 21:21:03 +0300
Engine • revision 07afcf7d0f
Tools • Dart 2.13.0 (build 2.13.0-52.0.dev)
```

I was not able to follow the exact steps from the repro [repository](https://github.com/KlausJokisuo/Jetbrains_code_generation_fail). 

<details>
  <summary>Console</summary>
scheglov@scheglov-macbookpro2:~/dart/Jetbrains_code_generation_fail (master)$ flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 380ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 10.8s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 645ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[WARNING] freezed:freezed on lib/main.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.10.0
SDK language version: 2.13.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.13.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[INFO] Generating SDK summary...
[SEVERE] freezed:freezed on lib/main.dart:

Bad state: Unexpected diagnostics:
/Users/scheglov/Source/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:166:25 - This requires the 'non-nullable' language feature to be enabled.
/Users/scheglov/Source/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:539:15 - This requires the 'non-nullable' language feature to be enabled.
/Users/scheglov/Source/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:390:19 - This requires the 'non-nullable' language feature to be enabled.
/Users/scheglov/Source/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:30:49 - This requires the 'non-nullable' language feature to be enabled.
</details>

However when I just open `application_state.freezed.dart` in an external text editor, and make changes like changing the name from `_$ApplicationState` to `_$ApplicationState2` and back, I see that DAS performs analysis, and a new error appears or disappears in `application_state.dart`.

Maybe [the change](https://github.com/dart-lang/sdk/commit/e9fe25003b108ea9e7f4079d1266d6edbc5bb449) is not in the Dart SDK version that you use with your Flutter version? We had more changes actually in this area, but we kept tests, and FWIW they still pass.

So, try the recent enough Flutter and Dart SDK.

**Comment by KlausJokisuo** [comment]
@scheglov Thanks for your reply, any ideas when this will be landing on  Flutter stable branch?

**Comment by ksilz** [comment]
> It works for me now, with the latest Dart SDK.

@scheglov If I understand you correctly, I need the very latest Flutter version first to get a shot at this working?

**Comment by scheglov** [comment]
You probably don't need the very latest Flutter version, but something more or less recent.
As an experiment, try to switch to a master channel to check that this issue is fixed.

**Comment by ksilz** [comment]
@scheglov I'm sorry, but not right now. I briefly upgraded to Flutter 2.0, and my app was a dumpster fire. Stuff broke even without null safety. And many of the plugins weren't ready for yet. I'll wait a couple of weeks for things to settle down.
