### ISSUE TITLE
No error in CFE for wrong closure context

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43174]
The following code produces an error in analyzer and no error in CFE
```dart
test(void Function() f) {
  f();
}

main() {
  test (() {
    return 42;
  });
}
```
In analyzer it produces
`error - The return type 'int' isn't a 'void', as required by the closure's context.`

There must be an error in CFE as well

`Dart SDK version: 2.10.0-45.0.dev (dev) (Wed Aug 19 06:32:03 2020 -0700) on "windows_x64"`

**Comment by lrhn** [comment]
That sounds like an odd error.
An `int Function()` is-a `void Function()`, so it should be a valid argument to `test`. 
Is there a reason this is not an error in the analyzer? @stereotype441 

I would have perhaps expected to infer `void Function()` for the function and then complaining about the `return 42;` returning a value to `void` (but I'm happy that we don't, because inferring something, and then immediately pointing out why it's wrong, is a bad user experience).

**Comment by stereotype441** [comment]
@lrhn I'm not sure precisely what information you're looking for, but here's the logic the analyzer is using.  (I'm assuming we're talking about code with null-safety enabled):
- Before performing type inference the body of the function expression, it looks at the inference context being passed down; if it's a function type, then it infers a preliminary return type for the body based on the return type, so in this case `void`: https://github.com/dart-lang/sdk/blob/f61cab8a279e4c9a1de05e49d479e3d4c2d5b29f/pkg/analyzer/lib/src/dart/resolver/function_expression_resolver.dart#L60-L63
- During type inference of the body of the function expression, it uses that preliminary return type to do inference on `return` statements inside the body, so this means that the context for inferring the `42` is `void`: https://github.com/dart-lang/sdk/blob/f61cab8a279e4c9a1de05e49d479e3d4c2d5b29f/pkg/analyzer/lib/src/generated/resolver.dart#L1564-L1567
- After type inference of the body of the function expression, it computes an "actual return type" by folding together all the actually returned types using LUB (with `Never` or `Null` as the starting point, depending whether the end of the function body is reachable).  This produces `int`: https://github.com/dart-lang/sdk/blob/f61cab8a279e4c9a1de05e49d479e3d4c2d5b29f/pkg/analyzer/lib/src/dart/resolver/body_inference_context.dart#L153-L156
- Then it computes the final return type for the function expression by "clamping" that type to make sure it is a subtype of the preliminary return type.  The clamping algorithm has several cases; in this example the case that triggers is that if the preliminary return type was `void`, then the final return type is also `void`: https://github.com/dart-lang/sdk/blob/f61cab8a279e4c9a1de05e49d479e3d4c2d5b29f/pkg/analyzer/lib/src/dart/resolver/body_inference_context.dart#L122-L132
- Later, when determining whether to report an error for the `return` statement, it checks the static type of the returned value (`int`) against the final return type of the function expression (`void`).  It reports an error because it's illegal to return a non-`void` value from a function with a `void` return type: https://github.com/dart-lang/sdk/blob/f61cab8a279e4c9a1de05e49d479e3d4c2d5b29f/pkg/analyzer/lib/src/error/return_type_verifier.dart#L287-L294

**Comment by lrhn** [comment]
That was what I was thinking could happen (but don't actually like, because *we* infer `void` as return type instead of `int`, and then complain about the `return 42` that we already knew about. Alas, that's probably for a reason, the main reason being that the context type always wins.)

What's confusing me here is the error message itself:
> `error - The return type 'int' isn't a 'void', as required by the closure's context.`

The type of the expression of a `return` statement is not a "return type". That phrase is (or should be) reserved for return types of functions. This text makes me think that the problem is that the function's return type is `int`, which it isn't. (If it was, there wouldn't be a problem).

What we have is a return statement returning a value of type `int` in a function which has return type `void` - due to the context type making it have type `void`.

It's also confusing to say that `int` isn't a `void`, because `int` is both a subtype of, and assignable to, `void`. It's just not a valid return value of a `void`-returning function because of restrictions on the `return` statement, not because of type relations.

So maybe change the message to:
> `error - The returned type 'int' isn't returnable from a 'void' function, as required by the closure's context.`

(or: `void` function &mapsto; function with return type `void`).

**Comment by stereotype441** [comment]
Ok, let's let this be the issue for the CFE missing error.  I've filed https://github.com/dart-lang/sdk/issues/43180 to track the request to clarify the analyzer error message.

**Comment by eernstg** [comment]
@lrhn wrote:
> That behavior was what I was thinking could happen (but don't actually like, because
> we infer `void` as return type instead of `int`, and then complain about the `return 42`
> that we already knew about. Alas, that's probably for a reason, the main reason being
> that the context type always wins.)

The reasoning behind this behavior was that it is error prone to ignore that the return type from the context is `void`, because we will otherwise raise an error when a seemingly meaningful value is discarded:

```dart
void g(void f()) {
  f();
}

void main() {
  void f() {
    return 42; // Error.
  }

  g(() {
    return 42; // Error, when the inferred return type is `void`.
  });
}
```

**Comment by johnniwinther** [comment]
@stefantsov can you take a look at this?
