### ISSUE TITLE
Missing compile-time error on this access in assert initializer

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#43175]
Both analyzer and CFE fails to report an error on the access to `property` in:

```Dart
class Super {
  bool get property => true;
}

class Class extends Super {
  Class() : assert(property);
}
```

**Comment by johnniwinther** [comment]
This is currently used in flutter in several places:

* [widgets/framework.dart#L1843](https://github.com/flutter/flutter/blob/be7c7faee6cb8bcabd3fefbbe8107c5b772ef9c3/packages/flutter/lib/src/widgets/framework.dart#L1843)
* [cupertino/route.dart#L352](https://github.com/flutter/flutter/blob/be7c7faee6cb8bcabd3fefbbe8107c5b772ef9c3/packages/flutter/lib/src/cupertino/route.dart#L352)
* [cupertino/route.dart#L376](https://github.com/flutter/flutter/blob/be7c7faee6cb8bcabd3fefbbe8107c5b772ef9c3/packages/flutter/lib/src/cupertino/route.dart#L376)
* [material/page.dart#L48](https://github.com/flutter/flutter/blob/be7c7faee6cb8bcabd3fefbbe8107c5b772ef9c3/packages/flutter/lib/src/material/page.dart#L48)
* [material/page.dart#L185](https://github.com/flutter/flutter/blob/be7c7faee6cb8bcabd3fefbbe8107c5b772ef9c3/packages/flutter/lib/src/material/page.dart#L185)

**Comment by lfkdsk** [comment]
@johnniwinther Could I try to do this task?

**Comment by johnniwinther** [comment]
I already have a fix for this. It is breaking flutter, though, so I have to coordinate the landing of the fix with the analyzer and flutter.

**Comment by leafpetersen** [comment]
@scheglov can you comment on the analyzer status of this?  Per the comment above, the analyzer also seems to be missing this error.  Does it only miss this in asserts?  Are there no checks at all on the code in initializer asserts or is this limited in some way?

**Comment by scheglov** [comment]
The analyzer only evaluates assert initializers when evaluating constants. These classes are don't have constant constructors, and `property` read is not a valid constant expression anyway.

Could you explain why the analyzer should report an error here?

**Comment by leafpetersen** [comment]
@scheglov Interesting question.  I would expect for the same reason that this code is an error:

```
class Super {
  bool get property => true;
}

class Class extends Super {
  final bool field;
  Class() : field = property;
}
```

Looking at the original informal spec, I see this text as the most relevant:

```
The initializer list assert works the same way as an assert statement in a function body (with special treatment for asserts in a const constructor's initializer list, see next section). The assert expressions are evaluated in the initializer list scope, which does not have access to `this`, exactly the same way that an assert statement would be evaluated in the same scope. The runtime behavior is effectively:
```

I see even less text in the formal spec, though perhaps it's considered as covered by something else?  Is this underspecified?

cc @eernstg

**Comment by scheglov** [comment]
Ah, right - we cannot access `this` in constructor initializers. I would expect that the same rule applies to any constructor initializer, including `assert`. So, I will start looking at fixing this, and drop it if you decide that `this` is allowed.

**Comment by eernstg** [comment]
> Is this underspecified?

The spec says that a location may have ['access to `this`'](https://github.com/dart-lang/language/blob/9cf19f6ffa203bc879fe33e69515969332e58946/specification/dartLangSpec.tex#L2038), and initializer lists are not among those locations.

[Lexical lookup](https://github.com/dart-lang/language/blob/9cf19f6ffa203bc879fe33e69515969332e58946/specification/dartLangSpec.tex#L13885) specifies that it is a compile-time error if there is no access to `this` when a name `n` is looked up and is not found in any enclosing scopes. (When there _is_ access to `this`, the next step is to check the interface of the enclosing class, which corresponds to the transformation of `n` into `this.n`.)

So I believe it is covered.

It would be a major redesign of the semantics of object creation if we were to allow access to `this` in an initializer list (in an assertion or anywhere else), because it would allow arbitrary code with access to `this` to run at a time where the initialization of instance fields of `this` object is incomplete.

**Comment by scheglov** [comment]
When running Flutter tests, I see new issues reported in the same files as described in https://github.com/dart-lang/sdk/issues/43175#issuecomment-679972599. What is the plan to fix these? Do we move these asserts into the constructor bodies? Does anyone has a PR for this in work? Or should I?
