### ISSUE TITLE
Analyzer and VM reports errors in different places for wrong explicit extension invocation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43214]
```dart
class C {
}

extension Ext on C {
  int foo() => 42;
  int bar() => 43;
}

main() {
  C c = C();
  Ext(c) // VM reports error here. "Error: Explicit extension application cannot be used as an expression"
    ..foo() // Analyzer reports error here
    ..bar(); // and here. "Extension overrides have no value so they can't be used as the receiver of a cascade expression."
}
```
`Dart SDK version: 2.10.0-56.0.dev (dev) (Mon Aug 24 09:17:19 2020 -0700) on "windows_x64"`

**Comment by eernstg** [comment]
We don't specify the precise location of an error message, so it would be fine to just expect the errors as they are actually reported.

However, if we were to make any changes then it would probably be for the analyzer (I don't think there is a need to change the location where the CFE reports the error), so I'll add the label for that.

@scheglov, do you wish to make any changes to the analyzer for this issue? It could be argued that it's helpful to report the error just once, rather than once for each cascade section.

**Comment by bwilkerson** [comment]
I agree: there's no reason to generate more than one diagnostic, so it would be better to use the extension override as the location of the diagnostic.

**Comment by scheglov** [comment]
Yes, reporting it once would be better.
I will take a look.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/160701
