### ISSUE TITLE
[NNBD] different results in VM and Analyzer for type argument bounds

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43211]
The following code produces an error in analyzer and no errors in VM
```dart
class A<X extends A<X>?> {}

extension ext1<X extends A<X>?> on A<X> {
  bool get checkme => false;
}

extension ext2<X extends A<Null>?> on A<X> { // analyzer error - 'X' doesn't extend 'A<X>?'.
  bool get checkme => true;
}

main() {
  var a = new A<Null>();
}
```
`Dart SDK version: 2.10.0-56.0.dev (dev) (Mon Aug 24 09:17:19 2020 -0700) on "windows_x64"`

@eernstg who is right here? Analyzer or VM?

**Comment by mraleph** [comment]
@eernstg please change the area to either front-end or analyzer once you make a decision how this error should be reported

**Comment by eernstg** [comment]
We need to consider whether we can prove that `X <: A<X>?` under the assumption that `X <: A<Null>?` The assumption allows `X` to have the value `A<Null>` (without the `?`), in which case we must have `A<Null> <: A<A<Null>>?`. But we don't have that:

We could have it because `A<Null> <: Null`, but that is not true (this relies on the `?` part of the supertype).

So we must use the other part of the supertype, and we have it because `A<Null> <: A<A<Null>>`, but that only holds if `Null <: A<Null>`, which is also not true.

So the CFE must have a missing check for this, or it must conclude, incorrectly, that the assumption `X <: A<Null>?` is sufficient to conclude `X <: A<X>?`. So the label is area-front-end.

**Comment by johnniwinther** [comment]
The problem is that bounds checks in extension on-clauses are missing.
