### ISSUE TITLE
Mirror github.com/google/dart-neats

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#43212]
I would like to have a [mirror](https://github.com/dart-lang/sdk/wiki/Adding-and-Updating-Dependencies) of:
 * https://github.com/google/dart-neats

So I can reference it from `DEPS` in the dart-sdk.

-----
Context: We are using [yaml_edit](https://github.com/google/dart-neats/tree/master/yaml_edit) to make the `pub add <package>` command.

**Comment by whesse** [comment]
I'd like to get some input from others on this, since it adds some edge cases to our DEPS packages we don't have already:
1) It adds many packages, which may not all be used (in fact, only one is used).
2) The used packages must be added to .dart_tool/package_config.json, and the tool to update package_config must work to update the versions from the version in DEPS.  It will have to look in subdirectories of the third_party/package/dart-neats directory, instead of just in that directory.
3) Downstream users like flutter and internal Google use need to handle these new dependencies correctly - Flutter has a tool to update the DEPS in its engine checkout depending on the packages and DEPS in SDK.

Some of our tools written in dart have a versioned_packages (or vendor_packages?) subdirectory with a particular version of the package in them - would that be better in this case?

@athom @sortie @kevmoo

**Comment by jonasfj** [comment]
> The used packages must be added to `.dart_tool/package_config.json`, and the tool to update package_config must work to update the versions from the version in `DEPS`. It will have to look in subdirectories of the third_party/package/dart-neats directory, instead of just in that directory.

From what I can see `tools/generate_package_config.dart` has special handling for `protobuf` which is also a mono-repository.

https://github.com/dart-lang/sdk/blob/85699cfa6b6e5d600e0381486d9f72784233617a/tools/generate_package_config.dart#L25


----------------------------
We could vendor it.. But it'll add overhead whenever we have bug fixes.

**Comment by sortie** [comment]
`dart-neats` seems to be designed to be a set of miscellaneous packages to reduce overhead and they are explicitly documented to not be supported Google products. It feels erroneous for the SDK to depend on this repository as an official dependency.

If `yaml_edit` is essential enough for to be a SDK dependency, it would make sense to move it to its own officially supported repository.

**Comment by jonasfj** [comment]
Yeah, we've had a few debates back and forth, about where to find a home for `yaml_edit`.

Options considered:
(A) Ship it in `github.com/google/dart-neats` and put in `DEPS`,
(B) Ship it as a `github.com/dart-lang/yaml_edit` repository and package,
(C) Vendor it in `github.com/dart-lang/pub`, and ship it as a package from a personal repository,

We initially played around with (C), this turned out to be very messy. We have a lot of tests, etc.
If we need to fix something, we'll want to work on the full package, not a vendored fork.

The main reason we just went in the direction of (B) over (A) was that we weren't sure if we were willing to promise to maintain it, beyond what bug fixes is necessary for `pub add <package>`, `pub remove <package>` and `pub upgrade --major-versions`.

We can ofcourse make that commitment, but reading [Adding-and-Updating-Dependencies](https://github.com/dart-lang/sdk/wiki/Adding-and-Updating-Dependencies) using a `https://github.com/google/` repository seemed like a way around making an officially supported Dart package.
I think I'm trying to avoid that because I see little value in making this support commitment.

**Comment by jonasfj** [comment]
Okay, playing with it, we've decided that we're going to vendor it for now.

Then we can always choose to pull it out of `github.com/google/dart-neats` into a `github.com/dart-lang/yaml_edit` repository.
