### ISSUE TITLE
Migrator: Add machine output for tools (eg IDEs)

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#43224]
From @DanTup :

> would it be reasonable to add a `--machine` mode that puts command line output into JSON (eg. for the URL to launch, and also an error if the pub check fails)? That way we could add a command to the IDEs that launches this automatically without dropping to a terminal. If the pub check fails, we could show a notification with an option to review the output, or "run anyway" (which just re-runs with the `--skip` flag).

> We could do it by parsing text, but JSON would be much better.

**Comment by srawlins** [comment]
To get more precise, @DanTup , what would you need in that output in order to make this useful from an IDE?

* URL to launch
* The `pub outdated` results: detailed? boolean pass/fail?
* Don't print progress
* Still wait for CTRL+C to kill web server

**Comment by DanTup** [comment]
> The `pub outdated` results: detailed? boolean pass/fail?

I guess a message to show to the user, and something that allows us to identify that it's this specific error (eg. passing the skip switch and running again is a reasonable thing to do, and this isn't some other failure).

> Don't print progress

Yeah, or put it in JSON (similar to Flutter does). Probably only worthwhile if it might take a long time.

> Still wait for CTRL+C to kill web server

We'd send SIGINT/SIGTERM to the process rather than Ctrl+C (though these might be the same thing from Dart's perspective - Ctrl+C might cause the terminal to send SIGINT?).

cc @devoncarew in case he has other ideas (I'm not sure if IDE integration may have already been discussed and there may be other ideas).

**Comment by devoncarew** [comment]
What information would we be passing back to the IDE? Nothing about the migration results, just some structured data about 
some possible initial failures (pub related?)?

I'd be a bit concerned about piping the migration results back to the IDE, just in terms of increasing scope for the migration tool, and then having to support that new feature.

**Comment by DanTup** [comment]
Yep, this is purely for launching from the IDE and opening the browser (for a little convenience - esp. as it'll use the SDK selected in the editor, which might not be the same as the one on `PATH`).

I don't know how necessary the pub thing is, but when I tried to run on some of my own projects I needed to pass `--skip-pub-outdated` for it to run (I was using some packages that I guess aren't nnbd ready yet), so if that's common it'd be nice to be able to detect it show the user the message and just have a button to re-run with that flag.

I agree we shouldn't handle the results in the editor - the web app works well and it'd just be a lot of duplicated effort.
