### ISSUE TITLE
Add a Target annotation in a library causes diagnostics to stop updating

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#43242]
`Dart SDK version: 2.10.0-59.0.dev (dev) (Tue Aug 25 18:05:44 2020 -0700) on "linux_x64"`

When I add an import to `package:meta/meta_meta.dart` and add a `@Target({TargetKind.library})` annotation on a `class` I suddenly stop getting any updates to diagnostics. The now erroneous diagnostic for an unused import of `meta_meta.dart` is still show, and changes to the file are not reflected at all in diagnostic positions. Other files are not impacted.

This is happening with the `--lsp` mode analysis server flag.

cc @bwilkerson

**Comment by bwilkerson** [comment]
Phil just saw an exception in a log from the bots that might explain what you're seeing (https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8870777269394039296/+/steps/analyze_pkg_meta/0/stdout). We're trying to figure out the underlying cause of the exception, but it sounds like an emergency patch might be in order to prevent the exception from stoping errors from being updated.

**Comment by pq** [comment]
With some help from Konstantin, I updated my change w/ a patch:

https://dart-review.googlesource.com/c/sdk/+/160740

It's looking green and when it lands this should be fixed.

**Comment by pq** [comment]
OK!  

With 8ae9842e12390e646b747046ae78e833c4b7a0f9 and eb30e43940f9f9c1a35761eece6e4291dd1fa7ee you should be good to go @natebosch. 👍

**Comment by natebosch** [comment]
I confirmed that when I build the SDK from HEAD this is working. I don't think it's dropped in a published dev release yet.
