### ISSUE TITLE
Bad values for cos and sin methods

### ISSUE THREAD

**Issue by juanmrivero** [dart-lang/sdk#43254]
I'm using `dart:math` package in flutter and the `cos` function returns bad results. Specifically the following code:

```dart
import 'dart:math';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('cos(π/2) is 0', () {
    expect(cos(pi * 0.5), 0);
  });

  test('cos(π * 1.5) is 0', () {
    expect(cos(pi * 1.5), 0);
  });

  test('sin(π) is 0', () {
    expect(sin(pi), 0);
  });

}
```

returns the following results:
```
cos(π/2) is 0 [E]                                                                                                                                                                              
  Expected: <0>
    Actual: <6.123233995736766e-17>
  
cos(π * 1.5) is 0 [E]                                                                                                                                                                          
  Expected: <0>
    Actual: <-1.8369701987210297e-16>
  
sin(π) is 0 [E]                                                                                                                                                                                
  Expected: <0>
    Actual: <1.2246467991473532e-16>  
```

$ dart --version
_Dart SDK version: 2.10.0-7.3.beta (beta) (Wed Aug 26 09:46:50 2020 +0200) on "macos_x64"_

Flutter info just in case you need it: 
_Flutter 1.21.0-9.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 81a45ec2e5 (3 days ago) • 2020-08-27 14:14:33 -0700
Engine • revision 20a9531835
Tools • Dart 2.10.0 (build 2.10.0-7.3.beta)_

I found this old related issue, maybe it helps: https://github.com/dart-lang/sdk/issues/12369

**Comment by lrhn** [comment]
It's not necessarily *wrong*.

The value `pi` from `dart:math` is an approximation of the actual &pi; value (because all doubles are approximations of transcendental values), so you are asking for *sin* of a value *close to &pi;*, and you are getting a result *close to zero*.

The computer's value of "pi" is actually:
```
3.141592653589793115997963468544185161590576171875
```
where the correct number is more like:
```
3.141592653589793238462643383279502884197169399375...
```
As you can see, it differs already on the 16th decimal, so getting a result which also differs at that point is not too surprising.

If I compute `Math.sin(Math.PI)` in a browser, I also get 1.2246467991473532e-16 as result, and I get the same results as you for `Math.cos` of .5 and 1.5 times `Math.PI`.

**Comment by nohli** [comment]
@lrhn @mraleph 

I've made a package for hue rotation...and to get the same color, the rotation degrees have to be ~376.991 (it is supposed to be exactly 360). You can see the difference in the gif: https://pub.dev/packages/hue_rotation (when the animated box jumps from 360 to 0 - this should actually be the same color).

It turns out that the cos() and sin() functions from dart:math are partly responsible...should these functions really be that imprecise? If so, are there any other built-in functions one can use to get more precise results?

Two examples from DartPad:

Input:
```
import 'dart:math';

void main() {
  const double i = 376.99089083;
  print(sin(i));
  print(cos(i));
}
```
Output:
```
-0.00022760077321148036
0.9999999740989437
```

Input:
```
import 'dart:math';

void main() {
  const double i = 360;
  print(sin(i));
  print(cos(i));
}
```
Output:
```
0.9589157234143065
-0.2836910914865273
```

**Comment by mraleph** [comment]
@nohli `sin` and `cos` take _radians_ not _degrees_ (which is stated in their docs quite clearly, see https://api.dart.dev/dev/2.12.0-146.0.dev/dart-math/sin.html for example). If you want to convert degrees to radians you need to divide by 180 and multiply by `pi`, e.g. `360` degrees corresponds to `2 * pi` radians.

**Comment by nohli** [comment]
> @nohli `sin` and `cos` take _radians_ not _degrees_ (which is stated in their docs quite clearly, see https://api.dart.dev/dev/2.12.0-146.0.dev/dart-math/sin.html for example). If you want to convert degrees to radians you need to divide by 180 and multiply by `pi`, e.g. `360` degrees corresponds to `2 * pi` radians.

Thanks a lot!

It's working now - next time I'll properly read the docs first, sorry.
