### ISSUE TITLE
Analyzer: alwaysThrow from meta package don't work with null-safety.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#43252]
`Dart SDK version: 2.10.0-45.0.dev (dev) (Wed Aug 19 06:32:03 2020 -0700) on "linux_x64"`

```dart
import 'package:meta/meta.dart';

void main() {
  print(toBool(-1));
}

bool toBool(int value) {
  if (value == 0) return false;
  if (value == 1) return true;
  // works
  // throw Exception(value);
  error(value);
}

@alwaysThrows
void error(dynamic value) {
  throw Exception(value);
}
```

**Comment by ykmnkmi** [comment]
Should i use `Never` for this?
```dart
Never error(dynamic value) {
  throw Exception(value);
}
```

**Comment by lrhn** [comment]
Yes, you should use `Never`.

The `@alwaysThrows` annotation is just an annotation. It doesn't change how the language works, all it can do is to make the analyzer not complain about something that it was *choosing* to complain about otherwise, as an extra check not required by the language.

With null safety, a function returning `bool` can no longer be allowed to not return a `bool` value. The *language* prohibits that, and all the language sees is a call to a function returning `void`, the annotation has no effect on that. So, to make the language happy,  you have to make the function return `Never`.
