### ISSUE TITLE
Bug: Activating from path issue with dart 2.9.x 

### ISSUE THREAD

**Issue by jascodes** [dart-lang/sdk#43250]
Summary: The issue causes repository https://github.com/leoafarias/fvm , not to be able to activate from path but hang the machine and cause it not to respond.

Please refer to thread https://github.com/leoafarias/fvm/issues/116 for details.

Let me know if you want any more logs etc aside from on the thread.

Stay Safe
Jas

/cc @leoafarias

**Comment by mraleph** [comment]
Can you provide a step by step reproduction? I can't reproduce it just by following instructions in the first comment in the issue you are linking to. It seems @leoafarias was unable to reproduce it as well, but then somehow managed(?). 

One observation I would make is that the whole precompilation process is extremely memory hungry because it spawns a lot of `dart` binaries in parallel, if you machine is low on memory things might get rather slow (/cc @jonasfj).

**Comment by jascodes** [comment]
@mraleph Thx for getting back.
Few of my observations 
1. It quickly links with ver 2.8.x and 2.7.x on the same machine.
2. Running latest mac
3. I tried cleaning pub cache aNd project cache. Is thr any additional build cache i might clean?
4. Have you made any changes to local linking process? 
5. It might be env related but even if i pull fresh fvm repo it happens, if I remember right other repos don't hve prob but might be dependancy in fvm causing it, i will further enquire and get back to you

**Comment by jonasfj** [comment]
We've recently fixed a precompilation bug in `pub` which caused `N` executables to be compiled `N*N` times.
This should just make things run slow... but if you have many executables it can get quite bad, and possibly run you out of memory.

This should be included as of `2.10.0-64.0.dev`.
