### ISSUE TITLE
Observatory: Flutter Observatory debugger and profiler not working in browser

### ISSUE THREAD

**Issue by uizentrum** [dart-lang/sdk#43262]
![image](https://user-images.githubusercontent.com/18261950/91719438-0e50b680-ebb5-11ea-9b9c-5d6a24a39791.png)

**Comment by mraleph** [comment]
In future when reporting Flutter issues please do it at https://github.com/flutter/flutter/issues and make sure to include output of `flutter doctor`, which contains version information of your flutter installation.

Do you see any error messages in the console of the browser?

There was a regression on `master` branch which has since been resolved. See https://github.com/flutter/flutter/issues/64333 - if you are on `master` please upgrade and try again.

**Comment by uizentrum** [comment]
Okay sure,
--Do you see any error messages in the console of the browser?--
No

--There was a regression on master branch which has since been resolved. See flutter/flutter#64333 - if you are on master please upgrade and try again.--
Okay

**Comment by mraleph** [comment]
Let us know if upgrading solves it. If it does not we need more information e.g. browser version, if you use any extensions (try disabling extensions to see if they interfere with the page) and Flutter version (output of `flutter doctor`).
