### ISSUE TITLE
 {} is treated in the different ways in constant and non-constant expressions

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#43260]
Dart SDK version: 2.10.0-59.0.dev (dev) (Tue Aug 25 18:05:44 2020 -0700) on "windows_x64"

Here is a source code example:
``` dart
Set res1 = {} as Set;
const Set res2 = {} as Set;
const Set res3 = {};

Map res3 = {} as Map;
const Map res4 = {} as Map;

main() {}
```

Both dart and analyzer throw a compile error for the line #2 (`const Set res2 = {} as Set;`) and do not throw error for the line #1 (`Set res1 = {} as Set;`).

Lines #3, #5 and #6 always pass.

Seems like constant and non-constant expressions should be analyzed in the similar way: both lines #1 and #2 should not throw a compile error or otherwise both should do it.

Sample output is:
> $> dart test.dart
> test.dart:2:21: Error: Constant evaluation error:
> const Set res2 = {} as Set;
>                     ^
> test.dart:2:21: Context: Expected constant '_ImmutableMap<dynamic, dynamic> {dart.core::_kvPairs: <dynamic>[]}' to be of type 'Set<dynamic>', but was of type '_ImmutableMap<dynamic, dynamic>'.
>  - '_ImmutableMap' is from 'dart:core'.
>  - 'Set' is from 'dart:core'.
> const Set res2 = {} as Set;
>                     ^
> test.dart:2:11: Context: While analyzing:
> const Set res2 = {} as Set;
>           ^
> 
> $> dartanalyzer test.dart
> Analyzing test.dart...
>   error - Evaluation of this constant expression throws an exception. - test.dart:2:18 - const_eval_throws_exception
>   hint - Unnecessary cast. - test.dart:4:12 - unnecessary_cast
>   hint - Unnecessary cast. - test.dart:5:18 - unnecessary_cast
> 1 error and 2 hints found.
>

**Comment by lrhn** [comment]
The code is behavior correctly.

The error in line 1 and 2 is that `{}` in `{} as Set` is evaluated without a context type, and therefore become a `Map`. The `{} as Set` throws a run-time error because a `Map` is not a `Set`, but it's not a compile-time error as such, which is why line 1 compiles.

When the expression is evaluated as `const`, it "throws" at compile-time, triggering the const expression evaluation clause saying that it's a compile-time error if evaluating the expression would throw at run-time.
You'll get the same effect from:
```dart
var x = 1 ~/ 0; // Run-time error.
const y = 1 ~/ 0; // Compile-time error because it would have been a run-time error.
```


I still think `e as T` should provide a type context of `T` to `e`. It's not a compile-time error if the type of `e` is not `T`, but at least an expression whose type depends on the context type will get a *chance* to do the right thing.
