### ISSUE TITLE
List[index] return null when index doesn't exist

### ISSUE THREAD

**Issue by hiwa-jalal** [dart-lang/sdk#43275]
shouldn't List[Index] when the index doesn't exist returns null instead of throwing an error to make it easier to deal with or give it a default value when the index doesn't exist like this 
`[1, 2, 3].elementAtOrElse(4, () => 0);` from this [package](pub.dev/packages/supercharged).

**Comment by mraleph** [comment]
In general you want "fail-early" collection APIs instead of returning `null` and then failing somewhere else when the null flows there by accident. It was especially relevant in Dart prior to null-safety. 

In any case these APIs are set in stone by now and changing them is impossible.

@lrhn can elaborate more if needed.

**Comment by lrhn** [comment]
We deliberately did not allow out-of-bound accesses on lists, for a number of reasons.

* It might hide errors. Why read something where you can easily check the length first and know what it will do.
* It doesn't type as well. If `List.[]` could return `null`, we would have to make the return type nullable when we introduce null safety. That makes the operator strictly less convenient when used inside the bounds.
* It's inconsistent. You might be able to read, but you can't write, so `list[i] ??= 42` will succeed in reading, then fail when writing.
* You can't really use as a sign that you are outside the list bounds because some lists can contain `null` anyway.

I think the first item is the most important one, and that alone is reason enough to enforce list bounds.
