### ISSUE TITLE
`dart analyze` doesn't support analyze a single file.

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#43271]
I ran into this a while ago. I forget my exact reason for doing this, but I personally would like for single-file analysis to be supported. Note that `dartanalyzer` supports this.

**Comment by bwilkerson** [comment]
+1

Note that `dart analyze`, unlike `dartanalyzer` is using the analysis server. The server, while documented as supporting analyzing a single file, has never supported this use case. The cleanest (though not necessarily fastest nor easiest) way to support this in server is to replace the use of `ContextManager` (or rewrite it) so that server is using the newer `analyzer` APIs. This is work that needs to be done at some point in order to fix several bugs in server and to pay down some technical debt.

**Comment by devoncarew** [comment]
Closing as a dup of https://github.com/dart-lang/sdk/issues/43891.
