### ISSUE TITLE
Embedding Dart (JIT) into Android Application without flutter

### ISSUE THREAD

**Issue by CheatBoss** [dart-lang/sdk#43283]
I want to embed Dart (JIT) into my android application to use it as a scripting language for modifications, I could not find any official documentation on embedding Dart in third party applications.
I found a couple of examples on github, but most of them are outdated or hard to figure out.

Where can I find information about this?

**Comment by mraleph** [comment]
This is not something very documented. You can try to use examples given here: https://dart-review.googlesource.com/c/sdk/+/146223 and ask questions on this issue if something is unclear.

**Comment by CheatBoss** [comment]
These examples show running the kernel binary, what is needed to run an uncompiled script? What should I use instead of Dart_LoadLibraryFromKernel?

**Comment by mraleph** [comment]
You need to start `kernel-service` isolate and ask it to compile Dart source into Kernel binary and then load the result. I would not _really_ recommend this in an Android application (it is resource heavy - that's why Flutter handles compilation on host rather than on the device), but if you really need this sort of functionality then you can try to untangle what `main.cc` does for a normal Dart binary. Alternatively I could make an embedding example which shows how to do it, but that probably would only happen tomorrow.

**Comment by CheatBoss** [comment]
Thanks, will try to do that. An example would be helpful though, if you have time ofc

**Comment by CheatBoss** [comment]
After a huge number of attempts, unfortunately, nothing worked for me...
Therefore, I would still like to see an example :/

**Comment by mraleph** [comment]
Sorry it took me some time to get to this but https://dart-review.googlesource.com/c/sdk/+/146223 now has an example which starts kernel service as well.

**Comment by CheatBoss** [comment]
Thank you, it helped me a lot
