### ISSUE TITLE
Element.dataset allows wrong names

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#43295]
According to the Element.dataset [documentation](https://api.dart.dev/stable/2.9.2/dart-html/Element/dataset.html)

> Allows access to all custom data attributes (data-*) set on this element.
> 
> The keys for the map must follow these rules:
> 
> **The name must not begin with 'xml'**.
> The name cannot contain a semi-colon (';').
> The name cannot contain any capital letters.
> Any keys from markup will be converted to camel-cased keys in the map.
> 
> For example, HTML specified as:
> 
> < div data-my-random-value='value' >< /div >
> Would be accessed in Dart as:
> 
> var value = element.dataset['myRandomValue'];

But, in fact, name `xml` is allowed

```dart
import "dart:html";

class NullTreeSanitizer implements NodeTreeSanitizer {
  void sanitizeTree(Node node) {}
}
main() {
  var x = new Element.html('<p data-xml="0"></p>',
      treeSanitizer: new NullTreeSanitizer());
  print(x.dataset); // {xml: 0}
}
```
Tested with
`Chrome 84.0.4147.135`
`Dart SDK version: 2.10.0-59.0.dev (dev) (Tue Aug 25 18:05:44 2020 -0700) on "windows_x64"`

**Comment by rileyporter** [comment]
Updated the documentation to match the MDN `Element.dataset` documentation, removing the strict requirement on disallowing `xml` in the name for the property keys. It's still probably recommended not to have `xml` in the name since that is a requirement for the HTML attributes, so I left a link to the MDN `data-*` documentation with those restrictions in the "See also" section.
