### ISSUE TITLE
[NNBD] Unclear how to migrate methods with dependent return types

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#43335]
I find it hard to meaningfully migrate code like the following to NNBD:

```dart
T attempt<T>(T Function() callback, [T otherwise]) {
  try {
    return callback();
  } catch (error) {
    return otherwise;
  }
}
```

The only workaround I could come up with is to introduce a second differently typed method:

```dart
T? attempt<T>(T Function() callback) => attemptOr(callback, null);

T attemptOr<T>(T Function() callback, T otherwise) {
  try {
    return callback();
  } catch (error) {
    return otherwise;
  }
}
```

However this breaks existing users, and quickly gets more complicated or leads to duplicated code in more elaborate examples such as the migration [here](https://github.com/petitparser/dart-petitparser/blob/master/petitparser/lib/src/parser/combinator/optional.dart#L14). Any advice would be appreciated!

```
$ dart --version
Dart SDK version: 2.10.0-92.0.dev (dev) (Wed Sep 2 22:28:32 2020 -0700) on "macos_x64"
```

**Comment by lrhn** [comment]
If you look at the original code, it would potentially return `null`. As such, the correct translation would be to make `otherwise` have type `T?` and also make the return type `T?`. That is what the existing code does.

The problem here is that you want the return type to be non-nullable, but that requires the optional parameter to be non-nullable, and then it can't be optional - because there is *no* possible default value of type `T` for any `T`.

You can "fix" this code by making the optional parameter nullable, but then you don't actually gave a `T` default value. That's where we usually do something like `otherwise as T` when we use it, so it throws if you chose a non-nullable type, provided no `otherwise`, and *needed it*.
Or you can make `otherwise` required, which is what we sometimes do.
Or you can make the result also nullable, which can be annoying. but the technically correct translation of the original code.
Or you can make the `otherwise` a function: `[T Function()? otherwise]` and always default to a function which throws. Then it throws if the `otherwise` value is needed and not provided, independently of whether `T` is nullable.

All of the fixes are either breaking (because they might throw where the non-null safe code didn't) or they introduces a nullable result type. That's not *wrong*, the existing code *would* return `null` in those cases, so it is a correct. There is no perfect non-nullable translation of the original code.

**Comment by renggli** [comment]
Thank you for the detailed breakdown of the options. I think I will go with the two separate methods: this seems to provide the cleanest API for my situation and will cause a compile time error at all places that need to be updated.
