### ISSUE TITLE
avoid_types_on_closure_parameters suggests removing required types

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#43345]
I'm not sure if this is an issue with the lint or the analyzer (or neither, and it's just a place the lint would have to be excluded).

```dart
/// groupBy signature from package:collection
Map<T, List<S>> groupBy<S, T>(Iterable<S> values, T Function(S) key) => null;

void foo() {
  List<String> _filters;
  groupBy(_filters, (String f) => f.startsWith(''));
}
```

In this code, the variable `f` is explicitly declare as `String` and everything works as expected, but it triggers the `avoid_types_on_closure_parameters` lint ("Avoid annotating types for function expression parameters."). However, if I remove `String` so the code is like this:

```dart
Map<T, List<S>> groupBy<S, T>(Iterable<S> values, T Function(S) key) => null;

void foo() {
  List<String> _filters;
  groupBy(_filters, (f) => f.startsWith(''));
}
```

The type of `f` is now shown in the editor as `dynamic`. This results in no code completion, and the return value of `groupBy` being a `Map<dynamic, ...` which means no help with the types for the keys either.

The best option right now seems to be to ignore the lint that for that line, but it seems like either the type could be inferred or the lint could know that removing the type has undesired effects (for the editor, at least).

**Comment by bwilkerson** [comment]
Thanks for catching this!

My understanding is that inference will push down bindings for type parameters from the surrounding context (and in this case there is no surrounding context for the invocation of `groupBy` and hence no bindings) and then pull up bindings from subexpressions. So, I believe that what's happening here is that `S` isn't bound to `String` until we're in the pulling up phase, by which time it's too late to push it down into the closure. Because there's no binding for `S` when inferring the closure, there isn't any way to infer `T`. Handling a case like this (in the general case) would require going up and down until we reach a steady state, which we decided not to do. @leafpetersen to confirm.

@scheglov Is there enough information in the AST for the linter to determine which types are necessary for inference? If not, could we add that information? If my understanding of inference is correct, then we'll need to update the lint, and I'd prefer to not need to re-run inference every time the lint finds a closure.

@pq for visibility

**Comment by leafpetersen** [comment]
@bwilkerson yes, that's essentially it.  We can actually do better with this in the average case by using heuristics.  It's on my list of small improvements to type inference to do at some point.

**Comment by srawlins** [comment]
CC @stereotype441 who is working on the language side of this. He has refactored a lot of how inference is performed in analyzer, and might be able to answer whether the nodes have enough info for the lint rule, without having to re-perform inference.

**Comment by srawlins** [comment]
Inference has been updated to handle this case. If I rewrite a bit to support null safety:

```dart
Map<T, List<S>> groupBy<S, T>(Iterable<S> values, T Function(S) key) => {};

void main() {
  List<String> filters = ['h'];
  print(groupBy(filters, (f) => f.startsWith('')));
}
```

then the code is valid. This may have been inference-update-1, 2, or 3.

So I'm going to close this example. If there are other inference issues with thie rule (not unlikely), we can track with other issues.
