### ISSUE TITLE
Generic Type Inheritance Checking

### ISSUE THREAD

**Issue by Peng-Qian** [dart-lang/sdk#43390]
#### Problem
It seems generic type inheritance checking is not easy in Dart.
Solution one will have a long checking code when subtypes amount increased.
Solution two had more creation cost at the runtime.

Is it possible to provide a handy way of checking generic type inheritance?
Such as new keyword(maybe?):
```dart
T inherits Parent
```
#### Functions and Type Inheritance
```dart
void main() {
  checkType<Child>();
}

class Parent {}

class Child extends Parent {}

void checkType<T extends Parent>() {
   ...
}
```
#### [==] check
```dart
  print('[==] check can only check the exact type: ');
  if (T == Parent) {
    print('Tpye == Parent');
  } else {
    print('Tpye != Parent');
  }

  if (T == Child) {
    print('Tpye == Child');
  } else {
    print('Tpye != Child');
  }
```
#### [is] check
```dart
  print('\n[is] check fail any tpye check: ');
  if (T is Parent) {
    print('Type is Parent');
  } else {
    print('Type is not Parent');
  }

  if (T is Child) {
    print('Type is Child');
  } else {
    print('Type is not Child');
  }

```
#### [switch] check
``` dart
  print('\n[switch] can only check the exact type: ');
  switch (T) {
    case Parent:
      print('Type match case Parent');
      break;
    default:
      print('Type is not matched case Parent');
  }

  switch (T) {
    case Child:
      print('Type match case Child');
      break;
    default:
      print('Type is not matched case Child');
  }
```
#### Solution one
```dart
  if (T == Parent || T == Child) {
    print('Type is either Parent or Child');
  } else {
    print('Type is neither Parent nor Child');
  }
```
#### Solution two
```dart
  if (<T>[] is List<Parent>) {
    print('Type is either Parent or Child');
  } else {
    print('Type is neither Parent nor Child');
  }
```
#### Results
```dart
[==] check can only check the exact type: 
Tpye != Parent
Tpye == Child

[is] check fails any type check: 
Type is not Parent
Type is not Child

[switch] can only check the exact type: 
Type is not matching case Parent
Type match case Child

solution one: 
Type is either Parent or Child

solution two: 
Type is either Parent or Child
```

**Comment by lrhn** [comment]
If you have a type variable `<T extends Parent>` and want to check whether the type bound to `T` is a subtype of `Child`, then you can't do it directly. There are not affordances for comparing type variables directly to other types, only for checking instances against the type.

There is a simple workaround, though, using a helper class or function.

The simplest approach is:
```dart
bool isSubtype<S, T>() => <S>[] is List<T>;
```
Then you can ask `isSubtype<T, Child>()` and get a `true` when `T` represents a subtype of `Child`, and a false when `T` is `Parent`.

A more generalized helper class could be:
```dart
class TypeHelper<T> {
  const TypeHelper();
  bool operator >=(TypeHelper other) => other is TypeHelper<T>;
  bool operator <=(TypeHelper other) => other >= this;
  bool operator >(TypeHelper other) => this >= other && !(other >= this);
  bool operator <(TypeHelper other) => other >= this && ! (this >= other);
}
```
Then you could do:
```dart
var tType = TypeHelper<T>();
if (tType <= const TypeHelper<Child>()) ... 
```

**Comment by lrhn** [comment]
I'll take the emojis as a sign we've answered the question. 🎉

**Comment by Peng-Qian** [comment]
Yes! Many thx!@lrhn

**Comment by Wheat2018** [comment]
nice!🎉

**Comment by escamoteur** [comment]
I got bitten by that just today again because I thought is was possible to just use `is` for that.
Why isn't it possible to compare types directly with is? doesn't the compiler now enough about types?

**Comment by eernstg** [comment]
I think it's helpful to think about this kind of question in terms of a metaphor:

It's a bit like having a picture of an elephant and asking "does this picture weigh more than one ton?". That's probably never going to be true, and it seems likely that you really wanted to ask "does the elephant which is depicted by this picture weigh more than one ton?", which might very well be true. However, we can't really know the answer to this improved question if we only have the picture, except if we happen to know that _every_ grown elephant weighs more than one ton, and we can see that the elephant isn't very young.

So `int is num` is (almost certainly) a wrong question because it puts a type in the position where the `is` operator expects to receive an object (so we're providing a "picture" where the real thing is expected). Yes, we _can_ obtain an object (of type `Type`) if we use a type as an expression (just like we _can_ weigh a picture), but it's very unlikely that `int is num` was written with the intention to test whether or not that object has the type `num`, because that's just a verbose way to write `false`.

The issue is like a type (or kind) error, plus a coercion: The `is` operator's left operand must be an object, and we`re passing a type (which can be coerced into an object when used as such, but in this particular case we probably don't want that).

We _could_ have a dynamic subtype operator (let's use the syntax `<:` for that operator, as in `int <: num`). This operator would have the syntax `<type> '<:' <type>` rather than `<bitwiseOrExpression> 'is' <type>`, and it would evaluate to true if and only if the left operand denotes a subtype of the right operand.

It is probably not a good idea to try to combine these two operators into one (that is, making `is` work like the current `is` in some cases and like `<:` in other cases, based on static or run-time information):

There is a syntactic mismatch (so we can't write all kinds of types on the left hand side of `is`), and there's a semantic ambiguity: If we encounter `o is T` where `o` has the static type `Object` (or any other type which is a proper supertype of `Type`) then it _could_ be a `Type` object, in which case we _might_ want to test whether `o` is a subtype of `T`, but it might also be a regular (non-`Type`) object where we'd want to test whether `o` is an instance of `T`.

So we do need a workaround for those (relatively rare?) cases where we want to test a subtype relationship dynamically, but we do have a standard way to express that: `<S>[] is List<T>` yields true if and only if `S` is a subtype of `T`.

I created this lint proposal to flag these usages of `is`:  https://github.com/dart-lang/linter/issues/4917.

**Comment by escamoteur** [comment]
But is the test if a generic type parameter is a subtype of some other type really a dynamic runtime check? Couldn't that be checked at compile time already?
Am 22. März 2024, 12:14 +0100 schrieb Erik Ernst ***@***.***>:

**Comment by eernstg** [comment]
How would you resolve this one at compile time?

```dart
import 'dart:math';

void f<X, Y>() {
  print(<X>[] is List<Y> ? 'Yes!' : 'No.');
}

void main() {
  if (Random().nextBool()) f<int, num>(); else f<num, int>();
}
```

**Comment by escamoteur** [comment]
ok, I guess I don't fully understand how generics are handled during compiling I still have the old C++ in mind.
Not sure that it would be really a problem to have an `is` operator that can be used on objects and types as the usage above feels very intuitive to do so and I'm not sure how it could be applied wrongly. However having a <: operator for that that could also deal with Type objects as well as with generic type parameters would be pretty handy.
I don't think that this is such a rare case especially if you develop libraries and want to check if the passed parameters are what they should be. Not always is it possible to limit the possible generic types to a certain subtype but hat to be checked when the function is called.

**Comment by busslina** [comment]
Was implemented the hypothetical `<:` operator?

**Comment by busslina** [comment]
Was implemented that hipothetical `<:'` operator?

**Comment by eernstg** [comment]
If you're interested in replacing the built-in `Type` class by something which is more powerful, you could take a look at the package https://pub.dev/packages/typer.

```dart
import 'package:typer/typer.dart';

abstract class MyIterable<E> {
  const MyIterable();

  E get first;

  Typer<E> get typerOfE => Typer();
}

class MyList<E> extends MyIterable<E> {
  final E e;

  const MyList(this.e);

  @override
  E get first => e;
}

class MySet<E> extends MyIterable<E> {
  final E e;

  const MySet(this.e);

  @override
  E get first => e;
}

void main() {
  // Assume that we do not know the precise type of `iterable`.
  MyIterable<Object?> iterable = MyList<int>(42);

  // Now we want to create a set with the same element type.
  MySet<Object?> set =
      iterable.typerOfE.callWith(<Y>() => MySet<Y>(iterable.first as Y));
  print(set.runtimeType); // 'MySet<int>'.
}
```

The point is that we add a getter that returns the `Typer` for each type variable of a class, and this basically allows us to "look into" the class of any given instance of that type and see the actual value of its type parameters.

Concretely, this is used to create a (mock) set from a given (mock) iterable, and the crucial part is that the set has a type argument with the same run-time value as the type argument of the iterable.

**Comment by busslina** [comment]
Cool package, but it matches object against type. I'm referring to a built-in operator that match type against type.

**Comment by eernstg** [comment]
> Cool package, but it matches object against type.

Thanks! Actually, it does support deciding subtype relationships among types:

```dart
import 'package:typer/typer.dart';

bool lessEqualType(Type t1, Type t2) {
  // Decide whether the type represented by `t1` is a subtype
  // of the type represented by `t2`.
  throw "Not possible (except 'dart:mirrors')";
}

bool lessEqualTyper(Typer t1, Typer t2) {
  return t1 <= t2;
}

void main() {
  lessEqualType(int, num);
  lessEqualTyper(Typer<int>(), Typer<num>());
}
```

> the `is` operator checks a tree of types ... [not] ... same members

Right, subtyping among types derived from classes and similar entities (mixins, enums, ...) in Dart is nominal, which means that it is not enough to have the same or similar members, there must be a connection which is created by `extends`, `implements`, etc.. We do have some structural rules as well. For example, covariance: `List<int>` is a subtype of `List<num>` because `int` is a subtype of `num`; another example is function types, and record types. So we have a mixture of nominal and structural subtype rules; but we never use subsetting of members of classes/mixins/... to conclude that there is a subtype relationship.
