### ISSUE TITLE
strong-mode implicit-casts demotes template classes to Object

### ISSUE THREAD

**Issue by dotdoom** [dart-lang/sdk#43410]
**Summary**:

With `implicit-casts: true`, `Klass<A>` and `KlassB extends Klass<B>` are demoted to `Object` when used in the same elvis operator expression.  Discovered when using `CircleAvatar` in Flutter:

```
backgroundImage: profile.photoUrl == null
                      ? const AssetImage('images/anonymous.jpg')
                      : NetworkImage(profile.photoUrl),
```

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)

```
$ dart --version
Dart SDK version: 2.10.0-7.3.beta (beta) (Wed Aug 26 09:46:50 2020 +0200) on "linux_x64"
```

**Code sample**:

```dart
import 'dart:math';

class Value<T> {
  final T x;
  const Value(this.x);
  String toString() => x.toString();
}

class StringValue extends Value<String> {
  StringValue(String x) : super(x);
}

void printValue(Value<dynamic> v) => print(v);

void main() {
  printValue(Random().nextBool() ? Value<int>(42) : Value<String>('test'));
  printValue(Random().nextBool() ? Value<int>(42) : StringValue('test'));
}
```

`analysis_options.yaml`:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

**Observed**:

`dartanalyzer`:

```
$ dartanalyzer test.dart
Analyzing test.dart...
  error • The argument type 'Object' can't be assigned to the parameter type 'Value<dynamic>'. • test.dart:17:14 • argument_type_not_assignable
1 error found.
```

**Expected**: either analyzer complains about both lines (requiring a cast) or none (since they both can be demoted to `Value<dynamic>`).

**Comment by eernstg** [comment]
This is working as intended, but it is a quirky corner of the language.

The point is that `?:` relies on the computation of a least upper bound (LUB) of two types, and that computation has several tricky properties. First, it isn't a least upper bound, because that doesn't exist (we can have two classes `C1` and `C2`, both implementing `B1` as well as `B2`, and then the least upper bound cannot be a nominal type: `B1` is not a subtype of `B2` and vice versa). Second, the Dart 1 rule for computing LUBs is still being used in the special case where we are computing the least upper bound of two interface types that aren't generic instantiations of the same class (so we're using that old rule for `Value<int>` and `StringValue`), but for two instantiations of the same interface type we use recursion (so with `Value<int>` and `Value<String>` we get `Value<LUB(int, String)>` which is `Value<Object>`).

```dart
void test(bool b) {
  var x1 = b ? Value<int>(42) : Value<String>('test');
  var x2 = b ? Value<int>(42) : StringValue('test');
  int i1 = x1; // Can't assign a `Value<Object>` to an `int`.
  int i2 = x2; // Can't assign an `Object` to an `int`.
}
```

The reason why that old rule is still being used in the "otherwise" case is that it would be too much of a breaking change to do anything else, but we are aware of the fact that it may seem confusing and inconsistent in cases like this one.

**Comment by dotdoom** [comment]
Got it, thanks Erik for the explanation and reference to the doc.  I've nothing to add here; unless you'd prefer me to rephrase it as an FR, we can close this issue.

To close on the thread, I appended `as ImageProvider<dynamic>` to the `AssetImage()` in my use case (that would be equivalent to `StringValue('test') as Value<dynamic>` in the example code).  Indeed, that required `ignore: avoid_as`, but it's honest work.

Expanding to `if ... else` assigning to a pre-declared variable of true LUB class (`ImageProvider<dynamic>` / `Value<dynamic>`) works as well in my case.

**Comment by eernstg** [comment]
Thanks, Artem! We have the need to think hard about least upper bound firmly on the agenda, so there is no need to create a feature request on that.
