### ISSUE TITLE
tests/dart2js/boolean_conversion_test fails with sound null safety

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#43471]
`tools/test.py -n dart2js-hostasserts-strong-linux-x64-d8 dart2js/boolean_conversion_test` fails.

/cc @rakudrama - we never quite wrapped our discussion about this one.

**Comment by rakudrama** [comment]
The test relies on making a specific decision when faced with an inconsistency.
I think we could parlay the inconsistency into any failure, for example  `a ? b : c` and `!a ? c : b` might simplify differently if we know `a` is ⊥.

In one part of the test we have `bool b = null as dynamic;` with an elided (trusted) always-failing check.
The HTypeKnown for the elided implicit `as bool` narrows to ⊥.

We should experiment with a _Halt-and-Catch-Fire_ (HCF) instruction which throws an Error if reached.
We would inject HCF after any HTypeKnown that strengthens to ⊥.
HCF would take the strengthened ⊥ value as an input and report it using the most concise code pattern possible.

Inserting a throwing instruction at the point of strengthening detects the inconsistency without inserting useless throws after calls to functions that always throw. If the function returns ⊥, either it always throws, or a return is an infeasible path due to a strengthening to ⊥, so the responsibility to HCF is pushed into the function.

Compiling without `--omit-implicit-checks` would give a better diagnostic by identifying the earliest failed check that cascaded into the detected inconsistency.

Dead code elimination would be modified to remove code dominated by HCF.
It is not necessary to extend dead code elimination test out how often this occurs, but I expect we well get some tree-shaking benefit from doing so. It would be interesting to see if inserting HCF and deleting code that it dominates might be a net win in code size.

See also #43456.
