### ISSUE TITLE
toStringAsPrecision not working as expected

### ISSUE THREAD

**Issue by khpiyak** [dart-lang/sdk#43523]
Hello dart team,

Dart SDK version: 2.9.2

I need to format double in significant figures.  I am expecting the toStringAsPrecision will perform round up.
e.g. 0.145 with precision 2 formats to 0.15.
but it formats to 0.14.

When I adding one more digi to value, e.g. 0.1451....to 0.1459, it can roundup correctly.  But not 0.1450.
Why rounding up the 2nd digi will depends on the 4th digi?

<img width="500" alt="Screenshot 2020-09-22 at 11 52 35 PM" src="https://user-images.githubusercontent.com/71587198/93906392-b67a1b00-fd2e-11ea-898e-fa7d44e9d055.png">

Thank you.

**Comment by lrhn** [comment]
My initial hunch is that it is *most likely* working as intended, because doubles just don't work like you expect them to!
Let's look at the numbers in question.

The real number 0.145 is indeed not precisely representable as a double. The closest double to 0.145 has the value
> 0.1449999999999999900079927783735911361873149871826171875

and that is the actual value your double literal `0.145` represents.
As you can see, that number is strictly below 0.145, so when rounded to two decimal digits, it chooses "0.14".

There is not a lot to do about that, it's just how doubles work. If you had written:
```dart
 print(0.14499999999999999.toStringAsPrecision(2));
```
you would probably have expected to print "0.14", but it's exactly the same number as `0.145`, and we have to do the same thing in both cases.
