### ISSUE TITLE
The RawSocket.write method exception could not be caught.

### ISSUE THREAD

**Issue by arcticfox1919** [dart-lang/sdk#43563]
I wrote the following code:

```
  void forward(RawSocket input, RawSocket output) {
    Uint8List bytes = input.read();

    try {
      output.write(bytes);
    } catch (e) {
      print("forward:$e");
      output.close();
      input.close();
    }
  }
```
But I'll get something wrong.

```
SocketException: Write failed (OS Error: An established connection was aborted by the software in your host machine. , errno = 10053), address = 0.0.0.0, port = 8081
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:944:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1619:15)
#2      Socks5Helper.forward (file:///D:/workspace/dart/socks5/socks5.dart:92:14)
......
```

`try-catch` didn't work.

I think the problem may be that the client connection is closed, but we can't handle the exception, which causes the server-side program to crash.

```
  serverSocket.listen(
      (socket) {
        handleRequest(socket);
      },
      onDone: () => print("onDone"),
      onError: (e) {
        print("serverSocket:$e");
      });
```

Perhaps the client connection was closed accidentally, so `onDone`, `onError` is not executed, there is no other way to determine if the socket is writable or not!

My Dart version: `Dart SDK version: 2.9.3 (stable)`

I don't know if there is another way to catch the exception generated by the `RawSocket.write` method, I was hoping someone could tell me, or is this really a bug that needs to be fixed?

**Comment by arcticfox1919** [comment]
@mkustermann 

Thank you for your reply. I did not write a client, the client is SwitchyOmega in Chrome, but I have found a solution, which is to use the zone in dart to catch exceptions

**Comment by sortie** [comment]
I'm not sure this issue is actionable for us. I don't know how we would reproduce the issue you're reporting. If you could provide a small standalone program demonstrating the problem, that would be very helpful.

Your stack trace seems to indicate that the exception can be caught at `#2      Socks5Helper.forward (file:///D:/workspace/dart/socks5/socks5.dart:92:14)`. Is that not the case?

Note that you cannot use the onDone and onError handlers to know for sure if a future write is going to succeed. Connections can fail asynchronously in the background for any operating system and network reason. You'll have to use a try/catch pattern around all writes.

It seems to me that the case here is either that there's some bug where an exception can't be caught, which seems a bit unlikely based on your stack trace, or you have a bug in your setup or maybe ran the wrong version of your code. We'll definitely want to fix it if the exception somehow can't be caught, but it'll be much easier if you help us figure how to reproduce it, or assuming the bug exists it might take a whole bunch of effort for us to figure it out.
