### ISSUE TITLE
HttpClient download too slow 12 Mbits on a  1 Gbs LAN.

### ISSUE THREAD

**Issue by brice-fromentin** [dart-lang/sdk#43580]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart core libraries : "dart:io"

* Dart SDK Version (`dart --version`)
Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "windows_x64"

I wrote the following code to download a file in my 1 Gb LAN :

```dart
  void _downloadRps(Session session, String rootUrl, String rpsName,
      File rpsFile, Function done) async {
    var rpsUrl = rootUrl + rpsName;
    var client = new HttpClient().getUrl(Uri.parse(rpsUrl));

    var progress = 0.0;
    var downloaded = 0;

    var sink = rpsFile.openWrite(mode: FileMode.write);

    client
        .then((HttpClientRequest request) => request.close())
        .then((HttpClientResponse response) => response.listen(
              (newBytes) {
                // update progress
                downloaded += newBytes.length;
                progress = 100 * downloaded / response.contentLength;
                session.progress = progress;

                // Save bytes
                session.status = "save bytes";
                sink.write(newBytes);

                session.status = "download bytes";
              },
              onDone: () {
                sink.close();
                done();
                session.status = "done";
              },
              onError: (error) {
                sink.close();
                session.status = "error :" + error;
              },
            ));
  }
```

**Comment by wanjm** [comment]
many issues report that httpclient in dart is slow, why there is no one take care of it for such long time for such a basic method;

**Comment by gustav3d** [comment]
Well, Dart as a language is designed in a way so that if you want
performance, you are pissing in the wind :(

**Comment by mraleph** [comment]
The reason you are getting such poor numbers is because your benchmark has a bug in it. You are calling [`IOSink.write`](https://api.dart.dev/dev/2.12.0-226.0.dev/dart-io/IOSink/write.html) but you actually need to be calling [`IOSink.add`](https://api.dart.dev/dev/2.12.0-226.0.dev/dart-io/IOSink/add.html). The former is writing out string representations of objects, while the later is writing out raw bytes `IOSink.write(newBytes)`. This bug causes benchmark to spend most of the time converting huge binary lists to strings. 

When I fix the code I get the same performance for Dart (both in JIT and AOT mode) and `wget`. Here is my code (I took a liberty to clean the code by using async syntax sugar and switched to use a public file provided by Tele2 for testing): 

```dart
// /tmp/test.dart
import 'dart:async';
import 'dart:io';

Future<void> _download(String uri) async {
  final client = HttpClient();
  final request =
      await client.getUrl(Uri.parse(uri));
  final response = await request.close();

  var progress = 0.0;
  var downloaded = 0;

  var sink = File('/dev/null').openWrite(mode: FileMode.write);

  final sw = Stopwatch()..start();

  try {
    await for (var bytes in response) {
      downloaded += bytes.length;
      progress = 100 * downloaded / response.contentLength;

      final elapsedSeconds = sw.elapsedMilliseconds / 1000;
      final mbPerSecond = (downloaded / (1024 * 1024)) / elapsedSeconds;
      stdout.write('\r${mbPerSecond.toStringAsFixed(2)} MB/s');

      sink.add(bytes);
    }
  } finally {
    sink.close();
    client.close();
  }
  print('\ndone');
}

void main(List<String> args) async {
  await _download(args.first);
}
```

```console
$ time wget -O /dev/null http://speedtest.tele2.net/1GB.zip
...
/dev/null                                                                                    100%[============================================================================================================================================================================================================================================>]   1.00G  40.0MB/s    in 27s

2021-01-15 10:01:05 (38.4 MB/s) - ‘/dev/null’ saved [1073741824/1073741824]

       26.67 real         0.36 user         1.44 sys
$ time dart /tmp/test.dart http://speedtest.tele2.net/1GB.zip
34.10 MB/s
done
       30.46 real        10.62 user         4.21 sys
$ dart compile exe /tmp/test.dart
Generated: /tmp/test.exe
$ time /tmp/test.exe http://speedtest.tele2.net/1GB.zip
43.74 MB/s
done
       23.54 real         9.09 user         4.61 sys
```

So you are getting within 10% of `wget` performance with JIT and same performance with AOT. 

(It's a pity though that `IOSink.write` accepts `Object` instead of `String`, which makes it easy to make such an error, but it is probably late to change that /cc @lrhn).

**Comment by lrhn** [comment]
It's definitely an API lesson (one we know already, but it bears reminding), and one which would be too breaking to fix now. 

We should have made `StringSink.write` take `String` as argument, not accept `Object?` and then immediately call `.toString()` anyway. The latter allows this kind of mistakes, the former would force the caller to do `.toString()` first on non-strings, which can be slightly less convenient - even though most of the time the argument is already string - but would also be much safer.

(The same lesson was what made us change `String.+` to accept only `String`, and has made us ask for a `List` or `Set` in some other methods where we *could* accept an `Iterable`, but would immediately convert to `List`/`Set` anyway because we need to know all the elements before starting the computation.)

**Comment by mraleph** [comment]
By the way @wanjm / @gustav3d if you have some other concrete issues with HttpClient slowness please point me to them, I will try to take a look at those as well.
