### ISSUE TITLE
dart2js regression when using `as` with types w/ non-default type-arguments

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#43609]
```dart
void main(List<String> arguments) {
  final emptyMap = <String, dynamic>{};
  // this is fine!
  print((emptyMap['not here'] as List)?.length);
  // this throws on `as`
  print((emptyMap['not here'] as List<int>)?.length);
}
```

Works fine w/ DDC
Fails with dart2js

Dart SDK version: 2.11.0-176.0.dev

**Comment by kevmoo** [comment]
Error `TypeError: null: type 'JSNull' is not a subtype of type 'List<int>'`

**Comment by fishythefish** [comment]
@kevmoo I'm having trouble reproducing this on master.
In weak mode (whether the experiment is explicitly enabled or not), we print out `null` twice.
In strong mode, the line that you've marked as fine actually throws `TypeError: null: type 'JSNull' is not a subtype of type 'List<dynamic>'`

Are you running with a particular set of flags?

**Comment by fishythefish** [comment]
I think this was broken here: https://dart-review.googlesource.com/c/sdk/+/157562
and fixed here: https://dart-review.googlesource.com/c/sdk/+/164941
(This was the same issue that broke a bunch of benchmarks, although we have no tests in the SDK that detect this.)

**Comment by fishythefish** [comment]
Going to close this issue. I'm not sure if there's a good way to write a regression test for this with our current infrastructure, but the issue was detected in multiple other places.

cc @joshualitt in case he has thoughts on how we can write [dart-lang/null_safety_sample_package](https://github.com/dart-lang/null_safety_sample_package/) as an SDK test.
