### ISSUE TITLE
Raspi install error

### ISSUE THREAD

**Issue by zmdk0913** [dart-lang/sdk#43634]
I want to install dart raspi 4, but I should build binary

but this is output message when I build command type

```
root@raspberrypi:~/sdk# ./tools/build.py --no-goma -m release -a arm create_sdk
Traceback (most recent call last):
  File "./tools/build.py", line 281, in <module>
    sys.exit(Main())
  File "./tools/build.py", line 246, in Main
    gn_py.RunGnOnConfiguredConfigurations(options)
  File "/root/sdk/tools/gn.py", line 560, in RunGnOnConfiguredConfigurations
    out_dir))
  File "/root/sdk/tools/gn.py", line 535, in BuildGnCommand
    raise Exception("Couldn't find the gn binary at path: " + gn)
```

How to fix this error?

**Comment by mit-mit** [comment]
Those steps are for building Dart from source. We have prebuilt SDKs here: https://dart.dev/tools/sdk/archive. I believe you need Linux ARMv7 for Raspberry.

**Comment by athomas** [comment]
Furthermore, the error message looks like you're missing some tooling (in case you can't just use our builds for some reason). Perhaps you just checked out the repo rather than installing depot_tools and running `fetch dart`? See https://github.com/dart-lang/sdk/wiki/Building which documents how to build the Dart SDK with all the needed steps.
