### ISSUE TITLE
Test failure implies missing promotion based on initialization

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#43647]
The test language/nnbd/inference/variable_initialization_promotion_test.dart currently fails
[in line 221](https://github.com/dart-lang/sdk/blob/8881446fea1e7d64a89f994d6ed90a791a9b4142/tests/language/nnbd/inference/variable_initialization_promotion_test.dart#L221) and [line 237](https://github.com/dart-lang/sdk/blob/8881446fea1e7d64a89f994d6ed90a791a9b4142/tests/language/nnbd/inference/variable_initialization_promotion_test.dart#L237) on all configurations.

In line 221, a local variable with declared type `int?` is initialized to `3`. Given that the non-null variant of a type of interest is of interest, and the declared type of a variable is of interest, and given that the initialization should be treated as an assignment for the purposes of promotion, I believe that the variable should be promoted to have type `num`. This is also what the test expects.

But all configurations fail to do that.

Line 237 is the same situation except that the local variable is late.

**Comment by franklinyow** [comment]
@leafpetersen. What's the right timeframe for this work?

**Comment by leafpetersen** [comment]
@stereotype441 I think you are/were working on this, what's the current status?

**Comment by stereotype441** [comment]
@leafpetersen Yes, this is the yak I have been shaving for the last few days.  The full story is:

This was fixed in 6a1c54ec302854a8b13d03ca5b9a6463b4a82df2 but then reverted in b4f49dc255475d0027369e654466b55dc304ecb0 because a VM optimization was assuming that if the promoted type of a variable is non-nullable, the variable's value could not be null (this is untrue in mixed mode, and 6a1c54ec302854a8b13d03ca5b9a6463b4a82df2 made it untrue more frequently, provoking the test failure).  We decided to fix this by removing the VM optimization (https://dart-review.googlesource.com/c/sdk/+/165625), but that in turn triggered trybot failures due to some unsound behavior in CFE legacy type promotion logic (https://github.com/dart-lang/sdk/issues/43640).  I have a fix for that unsound behavior out for review: https://dart-review.googlesource.com/c/sdk/+/166040.

So the sequence of events that has to happen to get these failures fixed is:
- @johnniwinther and @munificent review https://dart-review.googlesource.com/c/sdk/+/166040, then I land it, fixing https://github.com/dart-lang/sdk/issues/43640.  Hopefully this can happen tomorrow (Tuesday) morning US time.
- @alexmarkov lands https://dart-review.googlesource.com/c/sdk/+/165625, and then I re-land 6a1c54ec302854a8b13d03ca5b9a6463b4a82df2.  Hopefully this can happen tomorrow afternoon US time.

**Comment by leafpetersen** [comment]
> @leafpetersen Yes, this is the yak I have been shaving for the last few days.

Oh right, sorry, I should have remembered this.  Thanks for the update!

**Comment by stereotype441** [comment]
language/nnbd/inference/variable_initialization_promotion_test.dart is passing on all platforms except web as of e933e91aaa29531ccb32d5adec853270eedbedae.  I'm working on a fix for web (https://dart-review.googlesource.com/c/sdk/+/166702).

**Comment by stereotype441** [comment]
Hmm, my attempted fix for web didn't work, so I opened https://github.com/dart-lang/sdk/issues/43723 to get some help with it.  Since the only remaining difficulty is web-specific, I believe that type promotion is working properly, so I'm closing this issue.
