### ISSUE TITLE
Classes annotated `@sealed` report "subtype_of_sealed_class" in same library

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#43676]
```dart
@sealed
abstract class Result<R, E> {
  factory Result.success(R result) = _Success;
  factory Result.failure(E result) = _Failure;

  T map<T>(
    T Function(R) onSuccess,
    T Function(E) onFailure,
  );
}

// ignore: subtype_of_sealed_class
class _Success<R> implements Result<R, Null> {
  final R _value;

  const _Success(this._value);

  @override
  T map<T>(T Function(R) onSuccess, _) => onSuccess(_value);
}
```

AFAICT the `// ignore:` should not be necessary, right? @srawlins

**Comment by srawlins** [comment]
Yikes. Generics may be the cause.

**Comment by srawlins** [comment]
I cannot reproduce this in a unit test, nor in Blaze. In case it has to do with the file structure, can you post the file path of where you tried this? Generated file, perhaps? Non-lib file?

**Comment by matanlurey** [comment]
This is externally, with pub, with the latest (stable) version of Dart

**Comment by srawlins** [comment]
I cannot reproduce putting (approximately*) the example into a pub package, in the root, or in the lib folder. I used 2.9.1 stable, 2.10.0 stable... I'm on Mac. I tried in a pub package which uses builder (and generated files in .dart_tool), and a more basic pub package...

approximately*: I added an import of meta, and removed the _Failure factory, since there is no _Failure class.

**Comment by srawlins** [comment]
Closing as stale, and in favor of Dart 3 sealed classes.
