### ISSUE TITLE
Dart SDK behaves weirdly when import path contains double slashes.

### ISSUE THREAD

**Issue by themisir** [dart-lang/sdk#43710]
Today I mistakenly imported a file with two slashed in path.

```dart
import '..//checkout/checkout_page.dart';
```

I did not get any warnings from analyzer (IntelliSense). But I found out that builds and reload-restart requests failed due to weird import errors.

```
lib/presentation/pages//checkout/checkout_page.dart:3:8: Error: Error when reading 'lib/presentation/data/models/address.dart': The system cannot find the path specified.

import '../../../data/models/address.dart';
       ^
```

I think this might be caused by wrongly implemented path normalization in anywhere inside dart sdk or maybe `path` package (if dart-sdk uses this package).

**Expected behavior**
`lib/presentation/pages/checkout/checkout_page.dart` file imports `lib/data/models/address.dart`.

**Actual behavior** 
I'm not sure but I think instead of `lib/data/models/address.dart` file, it tries to import `lib/presentation/data/models/address.dart` might be caused by two slashes.

**Environment**
* Dart SDK Version (`dart --version`): Dart SDK version: 2.10.0 (stable) (Mon Sep 28 09:21:23 2020 +0200) on "windows_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable): Windows 10 Home Version 1909

**Comment by TheMisir** [comment]
I know this is low priority issue but I think this "minor" mistake might cause some failures in future if dart imports invalid file (with same name as expected file) and executes the code.

**Comment by lrhn** [comment]
It's not a mistake, but it is inconvenient.
Dart uses URIs for designating import files, and URI path normalization does *not* convert double slashes to single slashes, so `package:foo/bar/baz.dart` and `package:foo/bar//baz.dart` are two different URIs and are therefore treated as importing two different libraries.

The underlying file system, on the other hand, treat them as pointing to the same file, so you end up with two different libraries declaring classes with the same name, but which are otherwise completely incompatible.


It might be worth warning about in the analyzer (or maybe change the specification to allow different URIs to represent the same library, as long as they represent the same file, but adding a warning to the analyzer is the quicker solution).

**Comment by srawlins** [comment]
Duplucate of https://github.com/dart-lang/sdk/issues/36337
