### ISSUE TITLE
Make `enum` as successor of `Type` to use it as part of `is` comparison

### ISSUE THREAD

**Issue by bambinoua** [dart-lang/sdk#43718]
Hello!
Is it possible to create possibility to check if object is `enum`?

```dart
enum Status {opened, closed};

class Test with Serializable {
  Test({this.status, this.name, this.id});

  final int id;
  final String name;
  final Status status;

  Map<String, dynamic> toJson() {
    return ['id', 'name', 'status'].entries.map((k,v) {
      if (v is DateTime) {
        return MapEntry(k, v.toIso8601String());
      } else if (v is enum) { // <!--
        return MapEntry(k, v.index);
      } else {
        return MapEntry(k, v);
      }
    });
  }
}
```

**Comment by lrhn** [comment]
It's not currently possible. There is no shared supertype of `enum` classes. It's not unreasonable since they all share the `int get index` member, but it doesn't currently exist. There are many discussions about how to extend Dart `enums`, and some of them includes a shared supertype. I doubt we'll change anything about enums until we are sure which direction we want to improve them in.

In this situation, I'd probably just use `(v is Status)`. If it's a more general case where there is more than one enum, I'd test for all of them. If it's for a general framework which doesn't know the enums statically, then I don't have a good solution.

**Comment by bambinoua** [comment]
@Irhn, I see. Thank you for advise. Will test it.
