### ISSUE TITLE
Type inference missing with Set.from

### ISSUE THREAD

**Issue by nu8** [dart-lang/sdk#43727]
If I have a file like this:

~~~dart
void main() {
   var t = Set.of([10, 11]);
   print(t);
}
~~~

Everything works fine, even with `dartanalyzer --no-implicit-dynamic`. But if I
have a file like this:

~~~dart
void main() {
   var t = Set.from([10, 11]);
   print(t);
}
~~~

I get this result:

~~~
error - Missing type arguments for generic type 'Set<dynamic>'. - b.dart:2:12 -
   implicit_dynamic_type
error - Missing type argument for list literal. - b.dart:2:21 -
   implicit_dynamic_list_literal
~~~

and only passed check if I do this:

~~~dart
void main() {
   var t = Set<num>.from(<num>[10, 11]);
   print(t);
}
~~~

Why does one constructor exercise Type Inference, but not the other?

**Comment by znjameswu** [comment]
https://stackoverflow.com/questions/50320220/in-dart-whats-the-difference-between-list-from-and-of-and-between-map-from-a

**Comment by nu8** [comment]
I dont think that link is helpful. This issue isnt "what is the difference between `of` and `from`. The difference is demonstrated in my original post.

The issue is "why are these different in regards to type inference, and is that by design".

**Comment by srawlins** [comment]
It is by design. `from` is an older constructor which comes from before the language had more sound static typing ("Dart 1"). You can see from [the signature](https://api.dart.dev/stable/2.10.1/dart-core/Set/Set.from.html), `Set<E>.from(Iterable elements)`, that the type of E cannot be inferred from the type of `elements`, so E is implicitly `dynamic`. When using `Set.of` though, the type of the set is inferred by the type of `elements`.
