### ISSUE TITLE
Non null promotion fail in `if( a != null ){...}`

### ISSUE THREAD

**Issue by rxlabz** [dart-lang/sdk#43764]
I maybe miss something but shouldn't the `name` property be promoted to NonNull in this example ? https://nullsafety.dartpad.dev/dcb8f17148eb07b1b7c36442eb2d53d7

In DartPad (Dart SDK 2.10.0), the analyzer feedback is : ` A value of type 'String?' can't be assigned to a variable of type 'String'.`

```dart
class App {
  const App({this.name});

  final String? name;

  Map<String, dynamic> toJson() {
    final json = <String, String>{};

    if (name != null) {
      json['name'] = name;
    }
    return json;
  }
}

void main(){
  final app = App(name:'app');
  assert(app.toJson() == {"name":app});
}
```

**Comment by eernstg** [comment]
No, only local variables can be promoted. There are considerations about allowing instance variables to be promoted as well, but the current rules don't promote them. The main issue is that it is not sound to promote an instance variable, because it can be overridden by a getter running arbitrary code and that getter is not known to return the same object each time it is invoked.

**Comment by rxlabz** [comment]
Thanks, I'm closing it !

**Comment by eernstg** [comment]
Thanks! The topic is already covered by several existing issues, here's another one: https://github.com/dart-lang/language/issues/1187.
