### ISSUE TITLE
getUserMedia(mediaConstraints) does not consider deviceId and always open the default camera

### ISSUE THREAD

**Issue by wer-mathurin** [dart-lang/sdk#43802]
When you pass the constraint to the getUserMedia(mediaConstraints), it always open the default camera and do not considerer the deviceId pass in the constraints. To test this you can change the default camera in Chrome and you will see that It will open the default one.

```
var mediaConstraints = <String, dynamic>{
          'audio': true,
          'video': {'deviceId': [SOME_DEVICE_ID]}
        };
```

This tracker is for issues related to:
dart2js

Dart SDK Version (dart --version)
Dart SDK version: 2.10.1 (stable) (Tue Oct 6 10:54:20 2020 +0200) on "windows_x64"

Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

**Comment by wer-mathurin** [comment]
The problem come from constraints parameter is converted to JS object using convertDartToNative_Dictionary which does not work recursive as you can see in its implementation.

**Comment by romatroskin** [comment]
do you have some ETA for this fix?

**Comment by romatroskin** [comment]
same problem was noticed for MediaStreamTrack.applyConstraints() also

**Comment by srujzs** [comment]
Talked this over a bit. cc @sigmundch @rakudrama 

`convertDartToNative_Dictionary` is indeed non-recursive, which means if we support recursive maps like in the example, we need a separate method to copy recursively. As a workaround for your purposes, you can import `dart:html_common` and use `convertDartToNative_SerializedScriptValue` to convert the map before calling the API. Replacing `convertDartToNative_Dictionary` with this method wholesale isn't ideal since it overloads that method, and it may not handle types that are not clone-able properly. I think we would want a method that recursively copies a map while ignoring types that aren't a map and use that instead.

> I believe there is much more broken APIs

This is possible, can you point to the ones you're coming across? It would be very useful to understand where recursive maps can be expected but aren't. Thanks!

**Comment by wer-mathurin** [comment]
Hi @srujzs 

The only one I'm think about right now:
addStream

**Comment by srujzs** [comment]
`convertDartToNative_Dictionary` has been changed to be recursive, but only handles anything that doesn't need a conversion, maps, and lists. This should cover the above APIs.

**Comment by HidalgoIvan** [comment]
I am having the same problem, I'm defining the map itself explicitly without any methods or references and it still does not load the desired camera:

`{
      "video": {"deviceId": "0"},
      "audio": false
    }`

**Comment by srujzs** [comment]
That map is recursively copied as expected when I try it locally. Is the `deviceId` of the camera you're expecting `0` and is some other camera being loaded?
