### ISSUE TITLE
"int main" return value should set VM exit value

### ISSUE THREAD

**Issue by nu8** [dart-lang/sdk#43821]
If you have a Dart program like this:

~~~dart
int main() {
   return 1;
}
~~~

Some people might expect the Dart VM exit value to be `1`, but it will be in
fact `0`. I understand that `main` can return different types, but I think when
the type is `int`, it is reasonable to expect that the VM exit value will match
`main` return value. This is how it is done with many other languages, for
example C++:

~~~c
int main() {
   return 1;
}
~~~

C#:

~~~cs
using System;

class Program {
   static int Main() {
      return 1;
   }
}
~~~

Rust:

~~~rust
fn main() -> Result<(), u8> {
   return Err(1);
}
~~~

Zig:

~~~zig
pub fn main() u8 {
   return 1;
}
~~~

D:

~~~d
int main() {
   return 1;
}
~~~

**Comment by lrhn** [comment]
The VM can obviously check whether `main` returns an `int`, and then use that as exit value ... *if the programs ends when `main` returns*.

That won't work for asynchronous programs. For those, `main` returning is the start of the program, not the end. Even if `main` returns a `Future<int>`, that future completing doesn't have to be the end of the program, it can easily continue running for a long time after that.

Since most programs are actually asynchronous, even scripts, unless they are purely computational or only use synchronous file I/O, this feature won't actually help most programs. I think it's safer to just say that if you want to have a non-zero exit code, use the `exit` function or set it explicitly. Anything else is just setting people up to be disappointed when their asynchronous program doesn't do what they want it to.

**Comment by mkustermann** [comment]
@nu8 This is understandably very confusing when coming from a different programming language that is used to having a single `main` function which, on return, causes shutdown of the process.

Though, as @lrhn explains, we are in a different situation: Even if `main` has returned the program might continue running. In fact a Dart application compiled to JavaScript running in the browser will never really exit - the exit code would be meaningless. That's why our exit code mechanisms are encapsulated in the VM-specific `dart:io` library as `exit()` and `set exitCode(int value)`.

So I think this is working as intended - despite being confusing at times.
