### ISSUE TITLE
small optimization for getter isNotEmpty in collection/list.dart

### ISSUE THREAD

**Issue by bharatsingh100** [dart-lang/sdk#43849]
https://github.com/dart-lang/sdk/blob/5c1fe1b091dabaacb9d63870f087d177d5f6e756/sdk/lib/collection/list.dart#L96

in collection/list.dart line at 96  
bool get isNotEmpty => !isEmpty  can be changed to bool get isNotEmpty => lenght > 0;

**Comment by lrhn** [comment]
I think the behavior here is deliberate.
It allows you to override just `isEmpty` with whatever super-efficient (or otherwise smart) implementation you might have for your custom `List` implementation, and get a similarly efficient `isNotEmpty` implementation.

If we let `isNotEmpty` go directly to `length`, then if you want a non-`length` based `isEmpty`/`isNotEmpty`, you'd have to override both getters.

In practice, I'm not sure this optimization in worth the effort.

**Comment by rakudrama** [comment]
@bharatsingh100 Lasse's point is that `isEmpty` can have an override that does not use `length` and is more efficient than `length`. Consider this class from `dart:html`:
```dart
class _ChildrenElementList extends ListBase<Element>
    implements NodeListWrapper {
  // Raw Element.
  final Element _element;
  ...
  bool get isEmpty {
    return _element._firstElementChild == null;
  }
```
The effect of your change would be to make `_ChildrenElementList.isEmpty` and `_ChildrenElementList.isNotEmpty` (i.e. `ListMixin.isNotEmpty`) use completely different ways of checking if the list is empty.

**Comment by bharatsingh100** [comment]
thanks @lrhn and @rakudrama , i got the point, just want to know if isNotEmpty is not overriden then it would call isEmpty of parent class or the same class

**Comment by bharatsingh100** [comment]
i tried it on dartpad, i find that `isNotEmpty` will call the `isEmpty` of current class. It is better if don't have to override both the getters. I feel this issue is resolved

**Comment by lrhn** [comment]
Excellent :smile:
