### ISSUE TITLE
[test infra] test scripts ignore --dart2js-options ?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43881]
In [this failure log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865798738483684304/+/steps/test_results/0/logs/new_test_failures__logs_/0)

I see the following reproduction command:

```
python tools/test.py -n dart2js-linux-chrome --dart2js-batch --reset-browser-configuration --dart2js-options --no-sound-null-safety observatory_ui/app_test
```

This seems to correspond as expected to the entry in test_matrix.json:

```
        {
          "name": "dart2js observatory-ui tests",
          "arguments": [
            "-ndart2js-${system}-${runtime}",
            "--dart2js-batch",
            "--reset-browser-configuration",
            "--dart2js-options=--no-sound-null-safety",
            "observatory_ui"
          ]
        },
```

but running this command produces the same invocation that is shown in that builder log above:

```
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/cache/builder/sdk/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart2js --test-mode --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/observatory_ui/app_test.dart --out=/b/s/w/ir/cache/builder/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/runtime_observatory_tests_observatory_ui_app_test/app_test.js
```

Note that `--no-sound-null-safety` is not on that generated command line.  

@munificent @athomas it seems like either something is incorrectly configured here, or else the scripts are not passing this through correctly?

**Comment by sigmundch** [comment]
I wonder if there is an inconsistency with named configurations and extra options. We use dart2js-options in other cases, but for that we define a brand new configuration: https://github.com/dart-lang/sdk/blob/master/tools/bots/test_matrix.json#L570

If you decide to add a new configuration, you may be able to avoid using the `dart2js-options` altogether and let the test runner derive the flag by adding "-weak-" in the name:
```
 "dart2js-weak-(linux|mac|win)-chrome" : {
    "options": {
       "use-sdk": true
    }
  },
```

I believe that then using `-n dart2js-weak-linux-chrome` will introduce `--no-sound-null-safety` when invoking dart2js.

**Comment by munificent** [comment]
You're right, @sigmundch. This is a weird (i.e. broken) interaction between the old ad-hoc way of building a configuration on the command line for tests (`-c`, `-r`, `--dart2js-options`, etc.) and the newer named configuration support (`-n`). If you tell the test runner to run a named configuration, then it silently ignores some other arguments you pass to it on the command line.

So in:

```json
"arguments": [
  "-ndart2js-${system}-${runtime}",
  "--dart2js-batch",
  "--reset-browser-configuration",
  "--dart2js-options=--no-sound-null-safety",
  "observatory_ui"
]
```

Because that passes `-ndart2js-linux-chrome`, the `--dart2js-options=--no-sound-null-safety` option is never used. This entry in the test matrix just doesn't do what the author intended it to do.

This is definitely not a great user experience. We really need to integrate named configurations more completely into the test runner and tear out the old stuff if it's not the way things are supposed to be used any more.

I can think of two fixes:

### Add a new configurations to the test matrix

Add something like:

```json
"dart2js-(linux|mac|win)-chrome-unsound": { // Note "-unsound" suffix.
  "options": {
    "use-sdk": true,
    "dart2js-options": ["--no-sound-null-safety"]
  }
},
```

And then change the observatory step to:

```json
"arguments": [
  "-ndart2js-${system}-${runtime}-unsound", // Note "-unsound" suffix.
  "--dart2js-batch",
  "--reset-browser-configuration",
  "observatory_ui"
]
```

This wouldn't require any changes to the test runner.

### Merge test matrix and command line options

In the test runner, when running a named configuration, if there are options on the command line too, then add those to the configuration. This would make the way that step in the test matrix is currently authored do the right thing.

At the very least, the test runner should *tell you* if it's going to silently drop an option on the floor. It already tells you if you try to pass `-c`, `-r` etc. while also using a named configuration. I'll amend that to include the other options it ignores when you use a named configuration.

This second option is a little weird because it's not entirely clear which options should get merged and which shouldn't. I lean towards the first option to keep things simple.

@athom, what do you think? Would you be willing to make the test matrix changes?

**Comment by munificent** [comment]
> At the very least, the test runner should _tell you_ if it's going to silently drop an option on the floor. It already tells you if you try to pass `-c`, `-r` etc. while also using a named configuration. I'll amend that to include the other options it ignores when you use a named configuration.

CL for this: https://dart-review.googlesource.com/c/sdk/+/168766

**Comment by franklinyow** [comment]
Any status update?  Thanks
