### ISSUE TITLE
consider adding support for file analysis to `dart analyze`

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#43891]
Currently `dart analyze` only works on a directory which surprised me.

```dart
[~/src/repos/dart/sdk/pkg/_fe_analyzer_shared] (master) $ dart analyze lib/src/parser/identifier_context_impl.dart 
Directory doesn't exist: lib/src/parser/identifier_context_impl.dart

Usage: dart analyze [arguments] [<directory>]
-h, --help                   Print this usage information.
    --fatal-infos            Treat info level issues as fatal.
    --[no-]fatal-warnings    Treat warning level issues as fatal.
                             (defaults to on)

Run "dart help" to see global options.
```

I would expect this to work. 

(Note that in `dartanalyzer` it does.)

**Comment by bwilkerson** [comment]
That's because we never added support for that to the server despite it being specified in the protocol spec, and `dart analyze` uses the server (unlike `dartanalyzer`).

Fixing server was a large part of the motivation behind creating the `AnalysisContextCollection` interface, but server still needs to be updated to use that interface.

**Comment by johnniwinther** [comment]
This is the main reason I still use `dartanalyzer`; it isn't very useful run `dart analyze` on my temp folder full of garbage programs just to test the analyzer result for a single script.

**Comment by bwilkerson** [comment]
Konstantin recently landed in analysis server the first part of the support that's required to make this possible.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/190640
