### ISSUE TITLE
[dartanalyzer] Analyzer CLI language version depends on working directory

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43910]
See below for a reproduction transcript.  I set up a pub package with language version set to 2.9 (opted out), and with two dart files: foo.dart which should be an error if null safety is turned on, and bar.dart which should be an error if null safety is turned off (in other words I should get an error in either state, but in a different file).

Running the command line analyzer `dartanalyzer --enable-experiment=non-nullable` from the root directory of the package results in the expected error in `bar.dart`.  But running from outside of the root directory switches the error to `foo.dart`, indicating that the language version in .dart_tool/package_config.json is not being respected.  Per offline discussion with @bwilkerson this is not expected.  cc @devoncarew @scheglov 

I can also reproduce this with the flag flipped on by default, without passing the `--enable-experiment` flag.

```
leafp-macbookpro:pkgtest leafp$ cat lib1/pubspec.yaml
name: lib1
version: 0.1.1

environment:
  sdk: ">=2.9.0 <3.0.0"
leafp-macbookpro:pkgtest leafp$ cat lib1/lib/src/foo/foo.dart
import "../bar/bar.dart";

int x = f() + 1;

leafp-macbookpro:pkgtest leafp$ cat lib1/lib/src/bar/bar.dart
int? f() => 3;
leafp-macbookpro:pkgtest leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable lib1/
Analyzing lib1...
  error • An expression whose value can be 'null' must be null-checked before it can be dereferenced. • lib1/lib/src/foo/foo.dart:3:9 • unchecked_use_of_nullable_value
1 error found.
leafp-macbookpro:pkgtest leafp$ cd lib1
leafp-macbookpro:lib1 leafp$ ~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable .
Analyzing lib1...
  error • This requires the 'non-nullable' language feature to be enabled. • lib/src/bar/bar.dart:1:4 • experiment_not_enabled
1 error found.
```

**Comment by leafpetersen** [comment]
Confirmed that running as `dart analyze` with an appropriate analysis_options.yaml does not have this behavior - the error is in `bar.dart` consistently when run both from inside and outside the package root.

**Comment by leafpetersen** [comment]
cc @whesse

**Comment by scheglov** [comment]
FWIW, we have always (since at least 2016) used `cwd` to discover `.packages` for URI resolution.
Not sure if this was the rule in the past, but this is not correct now with `.dart_tool/package_config.json`.

**Comment by leafpetersen** [comment]
I'm actually not sure what the "correct" behavior is, or even if there is a specified correct behavior.  I just noticed the inconsistency. I think the CFE does respect the language version regardless of cwd though.

**Comment by lrhn** [comment]
The language version behavior for a compiler is specified as finding the `.dart_tool/package_config.json` relative to the entry-point library's location. That was always the rule, also for `.packages`. 
The CWD is only relevant if the entry point path is relative. Even then, the file path should be resolved first, then the corresponding package configuration should be found.

The analyzer has (and needs) more leeway since it doesn't have just a single entry-point. It should probably still do it's very best to find the package-config which is intended for a file:
* Any file with a `main` function should be considered an entry point, and use the package-config that would be found for that entry point.
* Any file in the `lib` directory of a Pub package structure should use the package's main `.dart_tool/package_config.json` file. For `bin` and `test`, files are most likely entry points.

There are probably other situations I haven't though of, and best-effort/whatever heuristic works would be fine there.

**Comment by mit-mit** [comment]
If this works with `dart analyze` but is failing with the (soon to be deprecated) `dartanalyzer`, perhaps we should spend the time simply making `dartanalyzer` bail out on older language versions?

**Comment by devoncarew** [comment]
I think we're unlikely to fix this for `dartanalyzer` (and it sounds like its WII for `dart analyze`).

Is this an issue for the sdk bots? If so, so workarounds would be to use the `--default-language-version` flag on dartanalyzer (or changing the cwd, or passing on an explicit package_config.json file).

I think for this and other reasons we'll want to accelerate deprecating the dartanalyzer command - have it start printing a deprecation message, ask people to move other to using it, along with a link to provide feedback for cases where `dart analyze` doesn't meet all their use cases.

**Comment by srawlins** [comment]
Closing as `dartanalyzer` is removed.
