### ISSUE TITLE
DDS flaky -> failure on [VM] Fixes yield* exception handling in sync*.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#43935]
There are new test failures on [[VM] Fixes yield* exception handling in sync*.](https://github.com/dart-lang/sdk/commit/c486a07b02d27559e8661b650bf4eebbd93cfa87).

```
app_jitk-linux-release-x64

flaky -> RuntimeError (expected Pass)

service_2/debugger_location_second_test/dds
service_2/debugger_location_second_test/service
```

@bkonyi This test was/is reported as flaky. What is the state of this test?
@cskau-g did your CL make it a predictable failure instead of flaky?

**Comment by cskau-g** [comment]
Daco, could you link the logs as well?

**Comment by cskau-g** [comment]
FWIW, I'm unable to reproduce this failure locally:

```bash
> python tools/test.py -n app_jitk-linux-release-x64 service_2/debugger_location_second_test
Test configuration:
    app_jitk-linux-release-x64(architecture: x64, compiler: app_jitk, mode: release, runtime: vm, system: linux)
Suites tested: service_2
[00:14 | 100% | +    2 | -    0]

=== All 2 tests passed ===
```

I also don't see why exactly this test and build mode (and nothing else) would fail for my CL.
I'm inclined to say it's flakiness and/or misclassification.

**Comment by dcharkes** [comment]
test failures:
- https://dart-ci.appspot.com/log/app-kernel-linux-release-x64/app_jitk-linux-release-x64/9898/service_2/debugger_location_second_test/dds
- https://dart-ci.appspot.com/log/app-kernel-linux-release-x64/app_jitk-linux-release-x64/9898/service_2/debugger_location_second_test/service

build: https://ci.chromium.org/p/dart/builders/ci.sandbox/app-kernel-linux-release-x64/9898

**Comment by bkonyi** [comment]
We're safe to skip this (it's twin in `service` is also [skipped](https://dart-ci.firebaseapp.com/#showLatestFailures=false&configurations=app_jitk-linux-release-x64&test=service/debugger_location_second_test/service)).


Also FYI, @rmacnak-google made a copy of the service tests in `observatory_2/tests/service_2/` before migrating `observatory/tests/service` for null safety. Unfortunately, the `service_2` tests don't have their test statuses automatically copied over as well which is why we're seeing lots of flaky failures pop up these days. If you compare the expected results for both `service` and `service_2` versions of a test, they should match. If they do, just approve the failures.
