### ISSUE TITLE
DST Transition brings to wrong DateTime manipulation

### ISSUE THREAD

**Issue by gregoriopalama** [dart-lang/sdk#44014]
I came up with a strange behaviour while using Jiffy Library, both on an Android smartphone and on an iOS one.
The behaviour is the following. 
I'm using some date transformations in order to calculate the starting and the ending moments of a time window. To get the ending moment, I start from the current time, go back to the start of the week, add a week and then go to the end of it. To get the starting moment I just go back to the start of the current week and then I add a week. Some days ago, the starting moment was kinda strange: it was not at midnight, but an one before. After some investigations, I've found that it was due to the DST transition. I'm in Europe/Rome timezone.

I investigated further and found out that the issue is in Dart language itself. Here's the code to replicate the issue:

```dart
//let's start with a date before the DST transition
DateTime dt = DateTime(2020, 10, 25, 16, 10, 00, 999);
print(dt);
//and let's go to the start of week. this code is the same used by Jiffy
DateTime newDate = dt.subtract(Duration(days: dt.weekday - 1));
DateTime dt2 = DateTime(newDate.year, newDate.month, newDate.day);
print(dt2);
//then, let's add a week. again, I'm using the same code that Jiffy uses
dt2 = dt2.add(Duration(days: 7));
print(dt2);
```

This is going to be 2020-10-25 23:00:00.000, but that's wrong, because I would expect it to go to the end of the day, so to 2020-10-26 00:00:00.000. If I try to change the starting date, assuming it to be, for example, 2020-11-25, I will get a correct behaviour.

My guess is there's some issue in https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/vm/lib/date_patch.dart.
I didn't have the time to test it yet, but it would be useful to have a SDT/DST table and adjust the time according to it.

**Comment by whesse** [comment]
Adding a Duration to a local DateTime in Dart is working as intended.  All Durations are time intervals encoded as (fractional) seconds, see https://api.dart.dev/stable/2.10.3/dart-core/Duration-class.html, without a separately represented day or week count.

To work with calendar days using DateTime objects, use UTC DateTime objects (DateTime.utc constructor).  Since a calendar day does not have a time of day associated with it, and is independent of time zone, it should not be represented by a local DateTime object.
