### ISSUE TITLE
--no-sound-null-safety is not required to run mixed null-safety code

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#44026]
Importing a file that does not opt-into null-safety from a file that does opt-into null-safety with Dart SDK version 2.12.0-0.0.dev, does not require passing `--no-sound-null-safety`.

<details><summary><b>Example</b></summary>

**File `talk.dart`:**
```dart
//@dart = 2.7

void sayHello(bool t) {
  String s;
  if (t) {
    s = 'hello';
  }
  print(s);
}
```

**File `main.dart`:**
```dart
//@dart=2.12

import 'talk.dart';

void main() {
  sayHello(true);
}
```

--------

</details>

```
$ dart main.dart
hello
```

```
$ dart --sound-null-safety main.dart
talk.dart:1:1: Error: A library can't opt out of null safety by default, when using sound null safety.
//@dart = 2.7
^^^^^^^^^^^^^
```

**Expected behavior**, `--sound-null-safety` is on by default when the _language version_ of the entry-point is `2.12`.

**Comment by johnniwinther** [comment]
This seems to be a VM issue. The VM should query the `uriUsesLegacyLanguageVersion` method in https://github.com/dart-lang/sdk/blob/6cfd46e177c1d62ed77e598d1468896919d3403f/pkg/front_end/lib/src/api_prototype/language_version.dart#L141 to determine whether the file should be run with sound or unsound null safety.

Dart2js correctly determines the null safety to be sound.

**Comment by athomas** [comment]
@franklinyow @pcsosinski This should be fixed before the beta branchout or CP'ed to beta after.

**Comment by pcsosinski** [comment]
@mit-mit fyi

**Comment by alexmarkov** [comment]
Kernel service is using `uriUsesLegacyLanguageVersion` API to auto-detect null-safety mode.
The problem is that VM issues compilation request with `kNullSafetyOptionWeak`.

This happens because `KernelIsolate::GetExperimentalFlag("non-nullable")` returns false. `KernelIsolate::GetExperimentalFlag` returns value according to the command-line options. It looks like we forgot to flip `non-nullable` experimental flag in the VM by default.

**Comment by alexmarkov** [comment]
Fix: https://dart-review.googlesource.com/c/sdk/+/170201
