### ISSUE TITLE
Analyzer does not throw a compile error when checks least and greatest closures for the function

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#44029]
Dart SDK version: 2.11.0-266.0.dev (dev) (Tue Oct 27 04:42:01 2020 -0700) on "windows_x64"

Here is a sample code which demonstrates the problem:
``` dart
Type _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  throw "It's OK";
}

typedef check = void Function() Function();

void main() {
  void f(check Function() g) => g();
  f(() => captureTypeArgument()..call.call('Hello'));
}
```

It passes with analyzer and throws a compile error with dart.

Seems like a compile error should be thrown in both cases.

Sample output is:
> $> dart test.dart
> test.dart:12:43: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
>   f(() => captureTypeArgument()..call.call('Hello'));
>                                           ^
> $> dartanalyzer test.dart
> Analyzing test.dart...
>   hint - The declaration '_capturedTypeArgument' isn't referenced. - test.dart:1:6 - unused_element
> 1 hint found.

This problem is reproducible with nnbd turned both on and off.

**Comment by devoncarew** [comment]
@scheglov - do you know what the right behavior here is (or who to cc for an opinion)? See also https://github.com/dart-lang/sdk/issues/44030 for the front end.

**Comment by scheglov** [comment]
It seems that this is a limitation of the analyzer. The type of `g.call` below is just `dynamic`:
```dart
void f(int Function() g) {
  var v = g.call;
}
```

@eernstg Could you help and point out at the place in the specification that says how `g.call` should be handled?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/170200

**Comment by eernstg** [comment]
> point out at the place in the specification that says how `g.call` should be handled?

We have https://github.com/dart-lang/language/blob/1df65fc0ed1ed60b520301b4e56336f2aadcecc2/specification/dartLangSpec.tex#L18370, which basically says that the `call` method of a function object has the signature which is the same as its function type.

The wording isn't particularly precise; I'd say that there is a most specific function type `F` which is the dynamic function type of the function object `o`, and then the dynamic type of `o` is a class `C` which implements `F` (and since `F` is most specific, `C` doesn't implement any other function type `G` such that `G <: F` and `G != F`).

I think this matches the description of the changes made in https://github.com/dart-lang/sdk/commit/c0c453f7f15a987c168a4e06903f62c6ce28bdaa.

The type `Function` is used for a tear-off of the `call` of a receiver of type `Function` or `X extends Function` (or `X extends Y extends Function`, etc).
