### ISSUE TITLE
VM should use tools/experimental_features.yaml instead of hand coded flag handling code

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#44053]
Bugs like https://github.com/dart-lang/sdk/issues/44026 happen because VM unlike CFE and Analyzer does not use this file and instead relies on manual flag flipping. 

This has been outstanding TODO which needs to be addressed.

/cc @alexmarkov @a-siva

**Comment by liamappelbe** [comment]
I'm looking into this now. Seems like it should be pretty simple. Most of the fields in experimental_features.yaml are not relevant to the VM's use case, since the only time the VM examines these directly from the command line are when we want the global experiment flag values. The CFE and Analyzer can enable/disable these flags on a per library basis, and when the VM needs per-library flags it gets them from the CFE (they're stored in the kernel).

So I'm ignoring the `experimentalReleaseVersion` field and `allowed_experiments.json`. I'm also ignoring the `expired` field, because experiment related errors are reported by the CFE. The only thing left is that we need to choose the default value for the experiment flag by comparing the `enabledIn` field to the `current-version`.

So, copying the approach used by the CFE and Analyzer, I'll write a little script to parse experimental_features.yaml, figure out which experiments are enabled in the current version, and spit out a C++ file containing a list of the enabled experiments.
