### ISSUE TITLE
Migration tool could understand manually lazily initialized fields

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#44109]
It would be great if the tool recognized a manually lazily initialized field:

```dart
class C {
  int _i;
  int get i {
    _i ??= ...;
    return _i;
  }
}
```

In this case , the tool makes `_i` nullable, and often makes `get i` nullable as well (depending on how the body is structured).

The big problems come when `get i` is considered nullable, when it should be non-nullable. I can generally force non-nullability by hinting `/*late final*/ int _i;`, but I think this would make illegal code (or just warnings) w.r.t. `_i ??= ...;`. The fix that I would do as a human are, perhaps strangely, to flip the field `_i` and the getter `i`, to use lazy initialization:

```dart
class C {
  late final int i = _i;
  int get _i {
    var i_ = ...;
    return i_;
  }
}
```

But I'm not sure that this is what we want the tool to do... sometimes the field and the getter are not adjacent class elements.

This all holds for top-level variables too.

**Comment by stereotype441** [comment]
Personally I think the first step in addressing this would be to have flow analysis's edge builder treat fields as promotable for purposes of understanding user intent (see https://github.com/dart-lang/sdk/issues/40566).  If we did this, then it would not try to mark the getter as nullable (because it would see that `_i` is intended to be non-null after the `??=`), so it would produce this:
```dart
class C {
  int? _i;
  int get i {
    _i ??= ...;
    return _i!;
  }
}
```
(Note that the fix builder would still use proper flow analysis, which doesn't promote fields, so the tool would see that a `!` is needed on the `return` statement).

I realize this is not the migration you're asking for, but it's still a lot better than what we do today.  In particular, since it doesn't mark the getter as nullable, it won't propagate nullability virally into other parts of the user's code.

Once we've done that I we could circle back and consider more sophisticated logic that would detect this pattern and replace it with a late variable.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
