### ISSUE TITLE
Could we generate valid subclass with `package:kernel` ?

### ISSUE THREAD

**Issue by lfkdsk** [dart-lang/sdk#44115]
I'd like to generate some subclasses for testcases.
Is there any easy way to generate them with `kernel` validly ?

some hard point for me:
1 . how to apply and substitute generic type for `generated subclass` ?
2 . how to find all abstract method need to be impl in inheritance chain, and how to apply these abstract method's generic typepremeter (these generic type may come from target class's supertype or supersupertype) ?

**Comment by lfkdsk** [comment]
@alexmarkov @mraleph

**Comment by mraleph** [comment]
I don't think we have any utilities for automatically generating subclasses. CFE might have some non-public code for that because it is capable of inserting noSuchMethod forwarders, which are more or less what you are looking for. I think your best bet is to read what CFE does and model your code after that.

**Comment by lfkdsk** [comment]
Thanks, i've done it
