### ISSUE TITLE
Least-and-greatest-closures test for generic function typedef fails with dart2js and passes with dart.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#44125]
[LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_dynamic_t21.dart](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_dynamic_t21.dart) test fails with dart2js and passes with dart.

Here is a log file with the failure: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8864396812126305440/+/steps/test_results/0/logs/new_test_failures__logs_/0

Sample output is:
```
--- Command "dart2js" (took 02.000533s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome sdk/bin/dart2js_developer --enable-experiment=non-nullable --enable-experiment=non-nullable --sound-null-safety --test-mode --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_dynamic_t21.dart --libraries-spec=sdk/lib/libraries.json --platform-binaries=out/ReleaseX64/ --sound-null-safety --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js

exit code:
0

stdout:
Compiled 8,255,156 characters Dart to 114,647 characters JavaScript in 2.53 seconds
Dart file /b/s/w/ir/tests/co19/src/LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_dynamic_t21.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js

--- Command "chrome" (took 108ms):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:34305/root_build/generated_tests/dart2js-chrome/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/test.html?crossOriginPort=42589

Runtime error:
Expect.equals(expected: <() => <T1>() => void>, actual: <() => <T1>() => void>) fails.
Expect.equals(expected: <() => <T1>() => void>, actual: <() => <T1>() => void>) fails.
    at Object.wrapException (http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:317:17)
    at Object._fail (http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:2447:15)
    at Object.Expect_equals (http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:2452:9)
    at main (http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:2483:9)
    at dartMainRunner (http://127.0.0.1:34305/root_dart/pkg/test_runner/lib/src/test_controller.js:315:5)
    at http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:3051:7
    at http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:3037:7
    at dartProgram (http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:3048:5)
    at http://127.0.0.1:34305/root_build/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js:3055:3

Deobfuscated error and stack:
Expect.equals(expected: <() => <T1>() => void>, actual: <() => <T1>() => void>) fails.
Expect.equals(expected: <() => <T1>() => void>, actual: <() => <T1>() => void>) fails.
    at wrapException        org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1130:37
    at _fail                ../../../../../tests/co19/src/Utils/expect.dart 20:5
    at Expect.equals        ../../../../../tests/co19/src/Utils/expect_common.dart 30:5
    at main                 ../../../../../tests/co19/src/LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_dynamic_t21.dart 29:10
    at dartMainRunner       pkg/test_runner/lib/src/test_controller.js 315:5
    at <fn>                 out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js 3051:7
    at <fn>                 out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js 3037:7
    at dartProgram          out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js 3048:5
    at <fn>                 out/ReleaseX64/generated_compilations/dart2js/tests_co19_src_LanguageFeatures_nnbd_Least-greatest-closure_typedef_typedef_dynamic_t21/typedef_dynamic_t21.js 3055:3


exit code:
0

```

**Comment by sigmundch** [comment]
/cc @fishythefish 

At a glance the error looks like if the actual and expected are the same. Is equals the wrong comparison here due to canonicalization of types? Or are we missing details in the string representation of the types?

**Comment by fishythefish** [comment]
There are potentially 2 separate issues here.

---

**Issue 1**: dart2js and the VM disagree on how `operator ==` works for generics.

Yes, the string representation is hiding some details. We don't print the bound on `T1` because the bound is a top type, but in the former, it's `Object?`, and in the latter, it's `dynamic`. (If we want types which print the same to be equal, we may need to revisit this decision, but that's another breaking change.)

Consider the following program:

```dart
typedef Foo = void Function<X extends dynamic>();
typedef Bar = void Function<X extends Object?>();

void main() {
  print(Foo);
  print(Bar);
  print(Foo == Bar);
}
```

Both dart2js and the VM print `<T1>() => void` (up to renaming of `T1`), but dart2js prints `false` while the VM prints `true`.

As far as I know, dart2js is doing the right thing. See the [null-safety specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-type-equality-operator) as well as the discussion at https://github.com/dart-lang/language/issues/821. Normalization and canonicalization do not equate (primitive) top types, so `dynamic` and `Object?` function as distinct bounds. If we were doing *subtyping* on `Foo` and `Bar`, then we would treat `dynamic` and `Object?` as equal bounds since they're mutual subtypes, but type equality is essentially just normalization + `identical`.

Filed https://github.com/dart-lang/sdk/issues/44136 for this.

---

**Issue 2** Is the test correct?

I'd have to do some language-lawyering to figure out if these expectations are valid, so it might be easiest to ask someone from the language team. In any case, I don't think there's anything for dart2js to do here since AFAIK we don't implement the least and greatest closure logic and instead get it from the CFE. I'm not sure if the VM is in the same boat.

Note that due to **issue 1**, the VM might not be a good validator for the test.

**Comment by eernstg** [comment]
I believe that the test needs to be adjusted, and I created https://github.com/dart-lang/co19/issues/963 for that.

I don't think this issue shows any wrong behavior from dart2js, and the vm issue is handled in #44136. This issue might still be re-purposed to deal with the the confusing error messages (`expected: <() => <T1>() => void>, actual: <() => <T1>() => void>`), but otherwise I think it can be closed.

**Comment by fishythefish** [comment]
Great, thanks for looking, Erik!
