### ISSUE TITLE
Can't pass type as annotation argument

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#44120]
Passing a function type as an argument to an annotation currently fails.
If instead the type is defined as a typedef, no errors are produced and the code works as expected.

This snippet:

```dart
class MyAnnotation {
  final type;
  const MyAnnotation(this.type);
}

// typedef MyType = String Function(int);
// @MyAnnotation(MyType)  // <- This works just fine.
@MyAnnotation(String Function(int))  // <- This fails.
random() => 7;

main() =>  random();
```

Gives me:

```
../../annotation_type.dart:10:22: Error: Expected ',' before this.
@MyAnnotation(String Function(int))  // <- This fails.
                     ^^^^^^^^
../../annotation_type.dart:10:22: Error: The class 'Function' is abstract and can't be instantiated.
@MyAnnotation(String Function(int))  // <- This fails.
                     ^^^^^^^^
../../annotation_type.dart:10:22: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
@MyAnnotation(String Function(int))  // <- This fails.
                     ^
../../annotation_type.dart:10:14: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
@MyAnnotation(String Function(int))  // <- This fails.
             ^
../../annotation_type.dart:5:9: Context: Found this candidate, but the arguments don't match.
  const MyAnnotation(this.type);
        ^^^^^^^^^^^^
```

**Comment by cskau-g** [comment]
+CC:@mkustermann

**Comment by lrhn** [comment]
This is working as intended.

The only types which can be written as an expression are those which can be expressed as a single or qualified identifier (so `TypeName` or `prefix.TypeName`).

That's why `MyAnnotation(MyType)` works, the type is expressed by a single identifier.
Something of the form `String Function(int)` is a type, but it is not an *expression*.

What you can do is to give the type a name:
```dart
typedef IntToString = String Function(int);
...
@MyAnnotation(IntToString)
```

(We should also consider allowing generic metadata annotations, so you could make `MyAnnotation` generic and write `@MyAnnotation<String Function(int)>()` instead. Alas, that's still not allowed).

**Comment by mkustermann** [comment]
@lrhn Though one could argue that if `print(List)` works, so should `print(List<int>)`.

**Comment by lrhn** [comment]
You can argue that, but the spec says otherwise.

It's a grammatical issue, not semantic. There is no problem actually getting `List<int>` there, and there are various workarounds which works outside of `const` settings (like `(<T>()=>T)<List<int>>()`).

I believe https://github.com/dart-lang/language/issues/123 is the request for allowing `List<int>` as syntax, which will both allow instantiated generic type literals and instantiated generic function tear-offs. It's convenient, but occasionally grammatically problematic. Say `foo(Function<int, int>(int))`, although we've survived that ambiguity for function invocations, so we can probably do the same thing here.
