### ISSUE TITLE
I-2-b: Dart does not throw a compile error if non-function type alias type argument does not conform to the bound.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#44223]
Dart SDK version: 2.12.0-33.0.dev (dev) (Wed Nov 11 17:34:11 2020 -0800) on "windows_x64"

Here is a sample code example:
``` dart
class C<X> {}
typedef A<X extends C<X>> = C<X>;

class C1<X extends C1<X>> {}

void main() {
  A();
  C1();
}
```
It seems like both `A()` and `C1()` calls should throw compile errors because type argument does not conform to the bound in both cases. 

However it does not happen for the non-function type alias, `A()` call just passes.

Sample output is:
```
$> dart --enable-experiment=nonfunction-type-aliases test.dart
test.dart:8:3: Error: Inferred type argument 'C1<Object?>' doesn't conform to the bound 'C1<X>' of the type variable 'X' on 'C1'.
 - 'C1' is from 'test.dart'.
 - 'Object' is from 'dart:core'.
Try specifying type arguments explicitly so that they conform to the bounds.
  C1();
  ^
test.dart:4:10: Context: This is the type variable whose bound isn't conformed to.
class C1<X extends C1<X>> {}
         ^
```

**Comment by leafpetersen** [comment]
@eernstg is this still an issue?

**Comment by eernstg** [comment]
Adjusting the labels: There is an error in the instance creation `C1()` because inference yields `C1<C1<Object?>>()`, and that is not a regular-bounded type. However, inference on `A()` yields `A<C<Object?>>()` which means `C<C<Object?>>()`, and that is not an error (`C` accepts any type argument whatsoever, so `C<Object?>` is OK, and so is `C<C<Object?>>`).

So there is no issue with the front end here.

However, there is a certain amount of confusion in the error messages emitted by the analyzer (931203b7020ee58f60db4b24f8a2fd34834ba7dc):

```
ERROR|COMPILE_TIME_ERROR|COULD_NOT_INFER|/usr/local/google/home/eernst/lang/dart/scratch/202102/n011.dart|8|3|2|Couldn't infer type parameter 'X'.\n\nTried to infer 'C1<Object?>' for 'X' which doesn't work:\n  Type parameter 'X' declared to extend 'C1<C1<Object?>>'.\n\nConsider passing explicit type argument(s) to the generic.\n\n
ERROR|COMPILE_TIME_ERROR|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/lang/dart/scratch/202102/n011.dart|8|3|2|'C1<Object?>' doesn't extend 'X extends C1<X>'.
```

```
Analyzing n011.dart...
  error • Couldn't infer type parameter 'X'.

Tried to infer 'C1<Object?>' for 'X' which doesn't work:
  Type parameter 'X' declared to extend 'C1<C1<Object?>>'.

Consider passing explicit type argument(s) to the generic.

 • n011.dart:8:3 • could_not_infer
  error • 'C1<Object?>' doesn't extend 'X extends C1<X>'. • n011.dart:8:3 • type_argument_not_matching_bounds
2 errors found.
```

I don't quite understand "'X' declared to extend 'C1<C1<Object?>>'", because `X` is actually declared to extend `C1<X>`, and in the current situation we require `C1<Object?> <: C1<C1<Object?>>`. Similarly, the wording "'C1<Object?>' doesn't extend 'X extends C1<X>'" is confusing.

**Comment by eernstg** [comment]
@scheglov, can you take the next step?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/184524
