### ISSUE TITLE
Augment output in dart compile to clarify null safety compilation mode

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#44234]
I got confused when retrying a migration.  I'd accidently left a `@dart = 2.10` in my entry point but migrated the rest of the app and the pubspec.

Might be worth emitting a warning that the mode disagrees with the pubspec.

Also not sure if this is best done in CFE or flutter tool - @mit-mit @johnniwinther @jonahwilliams

**Comment by johnniwinther** [comment]
The CFE never reads the pubspec.yaml. Only the package_config.json (through package:package_config).

**Comment by jonahwilliams** [comment]
Should this be a warning? Maybe the AI is to make it more obvious what mode we're running in?

**Comment by johnniwinther** [comment]
@mit-mit What are your thoughts on this?

**Comment by mit-mit** [comment]
From a discussion in the language team, we think this should *not* be a warning shown when running dart code (e.g. running `dart bin/main.dart`; that is potentially breaking. We also don't think it should be shown during analysis, as that could easily get annoying (the developer opts out, and is then immediately hit with warning).

But, we still think it's worth adjusting the output of commands that build *release-mode* artifacts to state which form of null safety was used. Concretely we'd like to suggest we adjust the output of `dart compile` and `flutter build`, so that when the SDK constraint is 2.12 or above, we add output like this:

```
$ dart compile exe bin/myapp.dart
Compiled exe with sound|sound null safety: /Users/mit/tmp/myapp/bin/myapp.exe

$ flutter build apk
Compiling Dart code with sound|unsound null safety.
Running Gradle task 'assembleRelease'... Done                     113.6s
✓ Built build/app/outputs/flutter-apk/app-release.apk (15.4MB).

```

WDYT @jonahwilliams @bkonyi @devoncarew ?

**Comment by devoncarew** [comment]
Consider highlighting the unsound version:

Compiling Dart code with sound null safety.

vs.

Compiling Dart code with __unsound null safety__.

**Comment by devoncarew** [comment]
Or even:

Compiling Dart code with __unsound null safety__ (see dart.dev/... for more information).

**Comment by bkonyi** [comment]
I'm fairly certain I saw `flutter run` output a message about running with unsound null safety last week. We should have a way for users to check whether or not they're running with sound/unsound null safety even when running against the JIT (maybe add a new flag or put it behind the `--verbose` option?). In general though, I'm supportive of adding this as output for commands that generate artifacts.

**Comment by zanderso** [comment]
The proposal in https://github.com/dart-lang/sdk/issues/44234#issuecomment-737841177 makes sense to me. Please file an issue in the Flutter issue tracker for the work needed on the Flutter tool. Thanks!

**Comment by mit-mit** [comment]
Thanks @zanderso, opened https://github.com/flutter/flutter/issues/72279

**Comment by mit-mit** [comment]
Updating the present issue to track the change in `dart compile`.

**Comment by bkonyi** [comment]
I'm uncertain as to which level in the stack should be outputting this information, but I'm thinking it needs to be done in each compilation pipeline. `dart compile` consists of 3 different compilation pipelines: `dart2js`, `dart2native`, and `gen_snapshot`, each of which should probably be responsible for detecting what type of null safety is being used and outputting the correct message. I can do this for `gen_snapshot`, but someone more familiar with `dart2js` and `dart2native` should look into adding this there.

cc/ @dcharkes for `dart2native` and @sigmundch for `dart2js`.

**Comment by sigmundch** [comment]
Agree this cannot be handled in dart-cli, but in each underlying compiler since the information necessary for this is available much later in time.

One alternative could be to share the logic in the CFE. To clarify on the earlier comments, this wouldn't require reading the pubspec.yaml, it would just mean to report a warning if the main entrypoint is in a library that is using legacy semantics. Doing this in the CFE may be nice since the CFE already reports errors that are similar in nature when the app is in sound mode (e.g. complaining if you import an opted-out library).

Currently we already have `Component.setMainMethodAndMode` - maybe introducing an indirection to calls to this method could be enough to always report a warning if main is from a legacy library? @johnniwinther what do you think?

**Comment by johnniwinther** [comment]
Generally the CFE doesn't know the context for its invocation, meaning that any messaging provided for one context will be misleading/wrong/confusing for another. Besides this case, we for instance mention updating `pubspec.yaml` in some error message and that doesn't make sense if the `package_config.json` (which is the file actually read by the CFE) is _not_ generated by pub.

For this reason I'd like to add support for passing an identification of this context to CFE and use this to guide its messaging.

**Comment by bkonyi** [comment]
@johnniwinther it sounds like you have a good handle on what needs to be done here. Can I get you to drive this work?

**Comment by johnniwinther** [comment]
I will.

**Comment by johnniwinther** [comment]
Should the message be reported as a warning (i.e. with colors and "Warning: " prefix) ?

**Comment by mit-mit** [comment]
No, I think I would classify this as an information message, not a warning.

**Comment by mit-mit** [comment]
Flutter work (https://github.com/flutter/flutter/issues/72279) is now complete.

**Comment by mit-mit** [comment]
Code review in https://dart-review.googlesource.com/c/sdk/+/178982

**Comment by askeksa-google** [comment]
Reopening due to revert.

**Comment by johnniwinther** [comment]
@bkonyi can you take a look at this? - the app-jit/simarm failures are bit out of my scope.

**Comment by vsmenon** [comment]
@bkonyi @a-siva - does this look fixable soon?  Trying to land this week.

**Comment by bkonyi** [comment]
Yes, I'll take a look.

**Comment by bkonyi** [comment]
@johnniwinther it looks like most of these failures can just be approved as the tests are failing due to stdout not matching the test expectations. However, the [app_jitk-linux-debug-x64 assertion failures](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8857777525685062496/+/steps/test_results/0/logs/new_test_failures__logs_/0) don't look good. @alexmarkov might be the right person to look at that since it's in the compiler.

**Comment by bkonyi** [comment]
Relanding the reverted change will be blocked until https://github.com/dart-lang/sdk/issues/44714 is resolved.

**Comment by mit-mit** [comment]
@johnniwinther as discussed yesterday, we should rephrase the 'unsound' message a bit, as it is shown both for projects with a 2.12 constraint & an entry-point opt-out, and for projects with a 2.9 constraint. I suggest:

1. - "Compiling with sound null safety" (everything is 2.12) or
3. - "Compiling without sound null safety" (something isn't 2.12)

**Comment by mit-mit** [comment]
"Compiling without sound null safety" UI string change landed in https://github.com/dart-lang/sdk/commit/134a43707f153fef26291c8a2a7947a814ac6f22

**Comment by franklinyow** [comment]
#44714 is closed

**Comment by johnniwinther** [comment]
The reverted CL is ready to reland: https://dart-review.googlesource.com/c/sdk/+/180187
