### ISSUE TITLE
CFE/Analyzer inconsistent error

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#44248]
In opted in code, optional and named method arguments that are typed as non-nullable without default values on `external` methods produce an error from the analyzer but not the CFE.

Example: 
```dart
external fn([String optionalArg]);
external gn({String namedArg});
```

The analyzer produces the following errors:
```
Analyzing test.dart...
  error • The parameter 'optionalArg' can't have a value of 'null' because of its type, and no non-null default value is provided. • test_09.dart:1:21 • missing_default_value_for_parameter
  error • The parameter 'namedArg' can't have a value of 'null' because of its type, and no non-null default value is provided. • test_09.dart:3:21 • missing_default_value_for_parameter
2 errors found.
```

**Comment by lrhn** [comment]
The CFE is correct(-ish).

External declarations are like abstract declarations and do not need to have a default value. That's considered an implementation detail, and external methods have external implementations.
If the external declaration is an instance method, then we may or may not want to allow you to write a default value anyway, since having one affects subclasses.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/172901
