### ISSUE TITLE
Dart autocomplete should be giving precedence of variables that are inside the context, like variables and parameters

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#44273]
Hey guys! Thanks for creating such a wonderful language. However, the completion area could get a little more love.
It should be giving precedence of variables that are inside the context, like variables and parameters.

Check this pictures of me trying to get some auto-complete for the functions's parameter **installation**:

![image](https://user-images.githubusercontent.com/1146982/99838051-48dc4680-2b47-11eb-950f-c65a9e513a8e.png)

![image](https://user-images.githubusercontent.com/1146982/99838068-50035480-2b47-11eb-9594-71889f5c15f8.png)

![image](https://user-images.githubusercontent.com/1146982/99838150-6c06f600-2b47-11eb-8cac-bd6e53d1384d.png)

![image](https://user-images.githubusercontent.com/1146982/99838180-788b4e80-2b47-11eb-9ff4-ea8af1afd75c.png)

![image](https://user-images.githubusercontent.com/1146982/99838603-2b5bac80-2b48-11eb-81ba-7571e5bd52d8.png)

Really, this is a real pain and happens all the time. Varaibles with long names always fall on this problem and I have to fully type its name all the time.
If you guys need any kind of reports of logs just let me know!

**Comment by devoncarew** [comment]
Thanks for the feedback; can you include the version of the dart sdk you're using?

**Comment by shinayser** [comment]
Sorry I am away of the computer right now to check the version but it is the latest of the Flutter's stable branch.

**Comment by devoncarew** [comment]
OK, if you could add the version when you're back at your computer that would be great. I'm assuming it'll be on or around Dart version `2.10.4`.

**Comment by shinayser** [comment]
> OK, if you could add the version when you're back at your computer that would be great. I'm assuming it'll be on or around Dart version `2.10.4`.

I just confirmed it is `2.10.4` . If you need anything else just ask.

**Comment by jodinathan** [comment]
I agree.
No matter if in VSCode or Intellij, autocomplete in Dart is not that good.

**Comment by esDotDev** [comment]
Another really annoying one is when I'm filling out params for a method, it never tells me what it's expecting like I would get in C#. It just returns some seemingly random list of methods: 
![image](https://user-images.githubusercontent.com/736973/99864904-60292d00-2b63-11eb-9118-07d229616152.png)

I always have to mouse over the function definition in order to see what params it takes. Main offender here is with builder() in flutter.

If we look at vscode, it very nicely shows me all the methods in the function, and also highlights the one I'm currently on:
![image](https://user-images.githubusercontent.com/736973/99864960-abdbd680-2b63-11eb-89fe-60c4e165ed8f.png)
This would be a great improvement to developer quality of life in dart.

**Comment by shinayser** [comment]
Seems that the label on this issue is wrong, it should be 'area-completion' since it is happening outside Intellij too (take a look on other issues like https://github.com/dart-lang/sdk/issues/43657) . Could you please take a look @franklinyow ?

**Comment by franklinyow** [comment]
@srawlins Should this go to "area-analyzer"?  Thanks!

**Comment by srawlins** [comment]
@bwilkerson to confirm, but I am pretty sure this enhancement has been implemented. In minimal repros, I always get a local variable (like a parameter) at the top of the suggestions.

**Comment by scheglov** [comment]
Or, for much smaller example:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/384794/162860037-1739b2cd-ab40-4637-b5a9-01166c9ccd72.png">
```dart
class StringLiteral {}

void f() {
  Str^
}
```

**Comment by srawlins** [comment]
For your minimal repro, in VS Code, I get StringLiteral as the top result. ☹️ . Annoying that we have to separate issues by IDE.

Since you reference the completion request/response, is VS Code probably re-ordering in my example, to the way we want? But if we re-order properly in analysis_server, maybe we will also get this good order in IntelliJ?

**Comment by DanTup** [comment]
> For your minimal repro, in VS Code, I get StringLiteral as the top result. ☹️

VS Code re-ranks completions whenever there is a prefix typed (see https://github.com/microsoft/vscode/issues/79516#issuecomment-523055743). The theory is that because it filters the results client-side (using a fuzzy match), the rankings provided by the server might be based on without filtering, so might not be as good as it can compute taking into account the prefix (including caps for camel case, etc.).

> is VS Code probably re-ordering in my example, to the way we want?

In this case it may be what you want, though it can often go the other way ☹️. It's ranking is based entirely on the text, since it doesn't have anything else (like typing information, whether a symbol is local or not, or even whether it's in-scope versus something that would add a new import). It doesn't seem like something that will change, though there is an issue the was kept open about allowing some kind of type hints (https://github.com/microsoft/vscode/issues/127516).

**Comment by jacob314** [comment]
Raising to P2 as this is a significant productivity hit when trying to complete variables in the context.

**Comment by scheglov** [comment]
Using the distance from the completion location to the local variable was fixed 444ad4daae858ea8ac07d50b4c29a4bc8b401915.
The fix was heavily based on the `localVariableDistance()` that @bwilkerson implemented a few years ago.

The distance to for formal parameters is not implemented yet.
I will take a look.

**Comment by scheglov** [comment]
Some refactoring before adding more nodes and tests.
https://dart-review.googlesource.com/c/sdk/+/355888

**Comment by scheglov** [comment]
Added more tests in 692624bd65bf8a8619214ee971fa051408056ee3.
Now I believe that it works.
