### ISSUE TITLE
[NNBD] Type inference regression

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#44284]
```dart
void main() {
  final SharedInterface a = 0 > 0 ? ConcreteA() : ConcreteB(); // A value of type 'Object' can't be assigned to a variable of type 'SharedInterface'.
}
abstract class SharedInterface {}
class ConcreteA with SharedInterface {}
class ConcreteB with SharedInterface {}
```

I expected line 2 to not lead to an error.

Can be reproduced on dartpad with nullsafety, works as expected on dartpad without nullsafety.
```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.296, on Mac OS X 10.15.7 19H15 darwin-x64, locale de-DE)
    • Flutter version 1.24.0-8.0.pre.296 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision 6fd13e6ef1 (4 days ago), 2020-11-19 00:29:28 +0100
    • Engine revision 35a0b9fe68
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)
```

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/174820

**Comment by scheglov** [comment]
The reason for this error is not that there is a *new* issue with null safety and type inference, but the fact that there was a bug in the analyzer and computing LUB (least upper bound) of two types. The analyzer did not consider mixins, so LUB was `Object`. Before null safety however we were able to assign because of implicit downcast. Implicit downcasts are not allowed in null safety, so the error was reported.
