### ISSUE TITLE
[NNBD] Confusing 'Never'-related dead code warning.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#44307]
```dart
void foo(Never arg) {
  print("hello there");
}

void bar(Never arg) {
  foo(arg);
  print("hello there"); // Marked as Dead code.
}

```

My understanding is that there's no type that can be instantiated that is a subtype of Never.

**A**: If no type can be instantiated to `Never`, shouldn't the whole body of foo and bar, be marked as dead code, and not just the print statement in bar? (false negative)

**B**: If there is a type that can be used to pass a Never on to foo via bar, shouldn't the print statement be not-dead code? (false positive)

**Comment by eernstg** [comment]
The [flow analysis](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md) is specified in terms of statements and expressions, and there is no notion of making a complete function body unreachable based on the types of parameters. So marking locations in the body as unreachable rather than the body as a whole is working as intended.

The reasoning behind `foo(arg)` is that this invocation cannot be executed without evaluating `arg`, and evaluating an expression of type `Never` will not complete normally (it will throw, or it will loop forever).

I don't think it creates any issues to ignore the fact that the body of `bar` and `foo` will never be executed in a sound null safety execution.

However, with `--no-sound-null-safety` (the execution mode which is used with programs that contain legacy code as well as code with null safety), an expression of type `Never` can evaluate to null (and it is not guaranteed that there will be a dynamic check that detects this at the earliest possible time), and in this case such function bodies can actually run. 

```dart
// Library 'n019lib.dart', opted in.
void foo(Never arg) {
  print("hello there");
}

void bar(Never arg) {
  print("Running `bar`");
  foo(arg);
  print("hello there"); // Marked as Dead code.
}

// Library 'n019.dart', legacy
// @dart=2.9
import 'n019lib.dart';

void main() {
  bar(null);
}
```

This program prints 'Running `bar`' before it throws an exception.

**Comment by modulovalue** [comment]
Thank you very much.
