### ISSUE TITLE
'as' operator on android

### ISSUE THREAD

**Issue by Goatmaster-Hub** [dart-lang/sdk#44316]
Hi, 
i am trying to cast an int into an double.
This works fine in the Browser but when compiling and running it on android i get the following exception:
type 'int' is not a subtype of type 'double' in type cast.

Codesample:
int test = 1;
double myDouble = test as double;

am i miss using/understanding the 'as' keyword here or is this a Bug ? 

dart --version output: 
Dart SDK version: 2.12.0-29.10.beta (beta) (Tue Nov 17 10:50:22 2020 +0100) on "windows_x64"

**Comment by lrhn** [comment]
This is working as intended. You should use `test.toDouble()` instead of `test as double` to convert the value to a `double`. 

The Dart `as` cast operator does not convert the object being cast, it just checks that it is already the type it's being cast to.
In this case it doesn't, and `int` is not a `double` ... except when compiled to JavaScript.

Dart `int` and `double` types are different types. In native programs, an `int` object is not a `double` object or vice-versa.
However, when compiled to JavaScript, Dart uses the JavaScript number type for both `int` and `double` values (because that's all JavaScript has built in, and doing anything else would be far too inefficient). Which means that Dart web code considers an integer value to be *both* an `int` *and* a `double`, there is only one `1` value, and it is used for both `1` and `1.0`. 
That's why you can do `int test = 1; test as double;` without throwing in a browser. It does *not* work when *not* compiled to JavaScript, because then `1` and `1.0` are different objects of different types, and `1 as double` throws.

**Comment by Goatmaster-Hub** [comment]
okay thank you for the detailed explanation.
But i have another question:
So i have a value of Type Object wich can either be an int or a double and i want it to cast in into a double. 
Do i understand that right that my best option here is todo a double.tryParse(value.toString()); ?

**Comment by mraleph** [comment]
@Goatmaster-Hub if you have an `int` or `double` (in other words `num`) you can use `num.toDouble` to convert it to `double`.

**Comment by lrhn** [comment]
What @mraleph said. If the value is not already a `num`, just an `Object`, you'll have to do `(value as num).toDouble();`.
