### ISSUE TITLE
Dart Native Executable improvement

### ISSUE THREAD

**Issue by halimpuckjava** [dart-lang/sdk#44326]
hi

1.  graalvm native image support for dart native exe (to make dart native exe faster)
2.  dart native exe cross platform (make only one native executable run in any platform)

thanks.

**Comment by mraleph** [comment]
I think there are some fundamental misunderstandings here.

> graalvm native image support for dart native exe (to make dart native exe faster)

Dart is not a JVM based language and Native Image is for JVM based languages. Also it is unclear why you think that going from Dart to Java Bytecode to Native Image would yield faster code than Dart's own AOT compilation (it will not).

> dart native exe cross platform (make only one native executable run in any platform)

Native executables are by definition not cross platform, because they are *native*. If you want to run on any platform distribute your code in Kernel snapshot and use JIT.
