### ISSUE TITLE
Null safety feedback: Null check should allow type promotion but doesn't

### ISSUE THREAD

**Issue by suragch** [dart-lang/sdk#44327]
I'm upgrading a personal package that is based on the Flutter framework. I noticed [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/text.dart#L558) in the Flutter Text widget source code that there is a null check:

```
if (textSpan != null) {
  properties.add(textSpan!.toDiagnosticsNode(name: 'textSpan', style: DiagnosticsTreeStyle.transition));
}
```

However, `textSpan!` is still using the ! operator. Shouldn't `textSpan` be promoted to a non-nullable type without having to use the ! operator? However, trying to remove the operator gives the following error:

> An expression whose value can be 'null' must be null-checked before it can be dereferenced.
> Try checking that the value isn't 'null' before dereferencing it.

**Comment by suragch** [comment]
Here is another example in my own code:

```dart
@override
RotatableString get current {
  if (_currentTextRun == null) {
    throw StateError(
        'Current is undefined before moveNext is called or after last element.');
  }
  return _currentTextRun!;
}
```

The ! operator is required even though `_currentTextRun` can't possibly be null.

**Comment by eernstg** [comment]
This is working as intended. Type promotion is only applicable to local variables. `_currentTextRun` is not local and `textSpan` may well be non-local as well (the example doesn't show that). Promotion of an instance variable is not sound, because it could be overridden by a getter that runs a computation and returns a different object each time it is invoked. Cf. https://github.com/dart-lang/language/issues/1188 for discussions about a mechanism which is similar to type promotion but based on dynamic checks, with some links to related discussions.

**Comment by suragch** [comment]
@eernstg Thank you for that explanation. I had misunderstood how it worked. That makes sense now.

**Comment by PlugFox** [comment]
Example.

https://dartpad.dev/8e1bb623664177623aae58df3c90f046?null_safety=true
