### ISSUE TITLE
Add a hint when a non-final field is initialized multiple times by field formal parameters

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#44334]
Given the following code
```
class C {
  int f;

  C(this.f, this.f) {}
}
```
it would be good to have a hint indicating that only one of the two argument values will be the value the field. There is a compilation error when the field is `final`, and while this isn't invalid according to the specification, it's useless and potentially misleading.

**Comment by eernstg** [comment]
Perhaps the example is a simplified version of a more complex example? Otherwise it's not obvious how the field could be initialized more than once: The example as stated has an error because the two occurrences of `this.f` would introduce the name `f` into the [formal parameter initializer scope](https://github.com/dart-lang/language/blob/487c4e047b546e943b4421304644152da42278ee/specification/dartLangSpec.tex#L3143) twice. I believe various other ways to get `f` initialized twice would also cause errors; e.g., we [can't have](https://github.com/dart-lang/language/blob/487c4e047b546e943b4421304644152da42278ee/specification/dartLangSpec.tex#L3351) two elements in the initializer list initializing the same instance variable (`C(): f = 1, f = 2 {}`).

But it looks like the analyzer does not report the name clash in the formal parameter initializer scope.

**Comment by bwilkerson** [comment]
> Perhaps the example is a simplified version of a more complex example? Otherwise it's not obvious how the field could be initialized more than once ...

The example, as entered, produces no diagnostics when analyzed, so I assumed that it was valid and constructed a semantic that seemed reasonable (that the value of the first argument would be assigned to `f` and then the value of the second argument would be assigned to `f`). This was partially in response to the fact that there _is_ a diagnostic if `f` is marked as being `final` because because "'f' is a final field and so can only be set once.".

It sounds like the real issue with the code is that there can't be more than one field formal parameter for the same field, whether the field is `final` or not, and that the analyzer needs to be changed to report that in both cases (and not that the field is being assigned a value multiple times.

@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/174486
