### ISSUE TITLE
If indexOf can return -1, the analyzer does not hint to potential crash (why not null?)

### ISSUE THREAD

**Issue by nohli** [dart-lang/sdk#44367]
```
void main() {
  final List<int> list = [0, 1, 2];
  final int searchItem = 3;
  final int index = list.indexOf(searchItem);
  final int foundItem = list[index];
  print(foundItem);
}
```

This code gives an error without the analyzer complaining beforehand.

While migrating to null safety, I thought:
Couldn't `indexOf` return `null` instead of `-1`, so it would be of type `int?`, so the analyzer would tell that the code could lead to an error?

**Comment by lrhn** [comment]
It could have returned `null` if we'd implemented it that way originally. Changing it now would be a breaking change, and not one that is likely to carry its own weight. Basically, all existing code using `indexOf` will need to change, either to check for `==null` instead of `<0`, or to add `!` when they know the value is in the list.

If we'd designed the API today, we might have used `null` as not-found-value *because* we now have null aware operators and null safety. At the time, returning an integer was advantageous because it kept the variable monomorphic (a variable always containing instances of a one class can be more efficient than one containing multiple different types, but JIT and AoT compiled).

Returning -1 has a few useful properties, for example: `list.sublist(list.indexOf(element) + 1)` is the sublist of all elements after `element`, or all elements if `element` is not in `list`. and `list.sublist(0, list.indexOf(element) + 1)` is all the elements up to and including `element`, or none if `element` is not in `list. Somewhat speculative, but occasionally useful. 
It's also what almost all other languages do for `indexOf`, so at least we're in ... plentiful company.

The use-case of looking up an element with an index just found using `indexOf` is not particularly common (you already had an object equal to the one in the list, otherwise you wouldn't have found it using `indexOf`).
