### ISSUE TITLE
Null safe exception when catchError fails to return a value should be more helpful

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#44386]
This program:

```dart
Future<void> main() async {
  final value = badFuture().catchError((e, s) {
    print('error occurred $e');
  });
}

Future<int> badFuture() async {
  throw Exception('boom');
}
```

Behaves differently when sound null safety is used or not. When not used (`dart --no-sound-null-safety main.dart`), the output is simply:

```
error ocurred Exception: boom
```

But when null saftey is enabled (`dart --sound-null-safety main.dart`):

```
error occurred Exception: boom
Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<int>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:164:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:715:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:736:24)
#3      Future._completeError (dart:async/future_impl.dart:544:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:600:7)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

The printed stack and error is pretty confusing. I have no use of `FutureOr<int>` in my program, and all of the frames point to internal Dart SDK code.  On web it's even worse:

```
error occurred Exception: boom
Uncaught Error: TypeError: null: type 'JSNull' is not a subtype of type 'FutureOr<int>'
```

And I've seen similar output in Flutter where default stack filtering logic removes the internal `Future` related stack frames and leaves you with just a frame that has no source line pointing to the function that called `badFuture`.

Ideally, the stack and/or the error message would point the user to the place in their code where they failed to return a non-null value from `catchError`.

**Comment by natebosch** [comment]
@lrhn I think we could check for this mistake instead of letting it surface as a type error. What do you think?

@dnfield would it help if the error was something along the lines of `ArgumentError: non-null return required from onError callback`?

I'm unsure of the best phrasing here, if `T` were nullable it wouldn't be an error so maybe the full error should be `non-null return required from onError callback for non-nullable Future types`?

**Comment by dnfield** [comment]
That might help but what I'd really like is for the stack to show where in my code I'm failing to return. In the real example this occurred in it was very difficult to figure that out.

**Comment by lrhn** [comment]
The "right" place to catch this is to throw a type error synchronously in the `catchError` invocation because the argument function does not return a `FutureOr<int>`.
However, that's also a breaking change because we used to allow functions with arbitrary return types and then just check the result *value*. Because the argument type is `dynamic`, you wouldn't get any type inference, making it very, very hard to write an argument at the correct type.

That's what we're still doing, and which you see "`null` is not a `FutureOr<int>`".

We're not *checking* the value, we're just downcasting it to its expected type, and that downcast fails.
We could introduce a check instead, something like `if (actualReturnValue is! FutureOr<T>) throw "more elaborate error";`
Shouldn't be too hard.

**Comment by dnfield** [comment]
So if there's any way the compiler (or even a lint) could catch this, it would be really nice.

Short of that, I'd really hope for the stack trace to point me to the line in my program that's going wrong. Otherwise, this ends up feeling like a bug in Dart (all the frames I can see are in the Dart SDK). This becomes especially probelmatic in larger codebases where catchError could be happening somewhere in the Flutter SDK, or somewhere in a third party package your application doesn't directly control.

**Comment by natebosch** [comment]
> Short of that, I'd really hope for the stack trace to point me to the line in my program that's going wrong.

I can't think of any way to do that. We can't tell that there is a problem until after the callback has returned and we have a value to check. As @lrhn mentioned we could require that the `Function` has the right runtime type, but it would be breaking for anyone that had a `dynamic Function(Object)` that returns a correct value.

The other thing to explore might be the ideas discussed in https://github.com/dart-lang/sdk/issues/34144 so that inference _can_ help us.

If we add an `onError` extension which takes a `FutureOr<T> Function(Object, StackTrace)` instead of a `Function` then inference and static checking should make it way easier to use.

**Comment by dnfield** [comment]
Would it be possible to capture the stack trace when you receive the callback, and if the typecast fails print the captured stack trace?

This could be done only in debug mode, or perhaps only in non-product mode.

**Comment by dnfield** [comment]
e.g. in the implementation of `catchError` something like:

```
FutureOr<T> catchError(Function onError, { bool test(Object error)? }) {
  if (!bool.fromEnvironment('dart.vm.product', false)) {
    _catchErrorImpl(onError, test, StackTrace.current);
  } else {
   _catchErrorImpl(onError, test);
  }
}
```

**Comment by lrhn** [comment]
Capturing a stack trace on entry, and keeping it alive over an asynchronous computation, is a significant overhead which is rarely going to be used.

I don't know what the `dart.vm.product` environment variable is, but it appears to be VM specific. I don't want to add that to the general platform libraries. The VM has a way to gather asynchronous stack traces, so you can perhaps just enable that when debugging.

If this wasn't the platform libraries, I'd recommend the analyzer add annotations for limited union types for parameters, so you could write:
```dart
catchError(@Union2<FutureOr<T> Function(Object), FutureOr<T> Function(Object, StacktTrace)>() Function onError, ...
```
and then the analyzer could check that arguments to that function was one of the two possible function types.
Not perfect, because it's not visible to type inference, but it could catch some errors.
(Or maybe just a single `@ErrorHandler<T>()` annotation, since that's the most common such problem).

That won't help us here since the platform library can't use third-party annotations, and we won't be adding annotations to the platform libraries.

Another option is for the analyzer to special case these particular functions and know that they are error handlers.

**Comment by dnfield** [comment]
What about guarding it with an assert rather than the VM specific constant?

**Comment by srawlins** [comment]
Just jumping in real quick to say we intend to catch this in static analysis by implementing https://github.com/dart-lang/sdk/issues/35825.

**Comment by dnfield** [comment]
Analysis for this would be great.

**Comment by srawlins** [comment]
This has landed.
