### ISSUE TITLE
Support operator overloading when convert to JavaScript

### ISSUE THREAD

**Issue by liudonghua123** [dart-lang/sdk#44390]
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* dart2js
* dev_compiler

Info:

* Dart SDK Version (`dart --version`) Dart SDK version: 2.10.1 (stable) (Tue Oct 6 10:54:20 2020 +0200) on "windows_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable) Windows
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) Chrome

I just want to transform some dart code that contains operator overloading to js code. I do not know whether the steps I tried is correct.

The example code is:

```dart
// operator_overload.dart

class Vector {
  int x, y;
  Vector(this.x, this.y);
  @override
  bool operator ==(covariant Vector v) => this.x == v.x && this.y == v.y;
  operator +(Vector v) => new Vector(this.x + v.x, this.y + v.y);
  operator -(Vector v) => new Vector(this.x - v.x, this.y - v.y);
  @override
  toString() => 'Vector(${this.x}, ${this.y})';
  sayHello() => 'hello, ${toString()}';
}

main() {
  var v1 = new Vector(5, 3);
  var v2 = new Vector(7, 2);

  Vector v3 = v1 + v2;
  print(v3);
}

```

Firstly, I tried to use `dart2js` (`dart2js -O4 -o operator_overload.js operator_overload.dart`), but it seems directly output the results instead of invoking it at runtime.

```shell
C:\Users\Liu.D.H\Desktop>dart2js -O4 -o operator_overload.js operator_overload.dart
Compiled 8,110,870 characters Dart to 6,031 characters JavaScript in 0.50 seconds
Dart file operator_overload.dart compiled to JavaScript: operator_overload.js

C:\Users\Liu.D.H\Desktop>node operator_overload.js
Vector(12, 5)

C:\Users\Liu.D.H\Desktop>node
Welcome to Node.js v14.8.0.
Type ".help" for more information.
> operator_overload=require('./operator_overload.js')
Vector(12, 5)
{}
> operator_overload.
operator_overload.__defineGetter__      operator_overload.__defineSetter__
operator_overload.__lookupGetter__      operator_overload.__lookupSetter__
operator_overload.__proto__             operator_overload.constructor
operator_overload.hasOwnProperty        operator_overload.isPrototypeOf
operator_overload.propertyIsEnumerable  operator_overload.toLocaleString
operator_overload.toString              operator_overload.valueOf

> operator_overload.
```

Then I tried to use `dartdevc` (`dartdevc --modules node -o operator_overload.js operator_overload.dart`), and when I require it, it show `Error: Cannot find module 'dart_sdk'`, I have to copy `dart-sdk\lib\dev_compiler\kernel\common\dart_sdk.js` to the location of `operator_overload.js` and changed `const dart_sdk = require('dart_sdk');` to `const dart_sdk = require('./dart_sdk');`.

```shell
C:\Users\Liu.D.H\Desktop>node
Welcome to Node.js v14.8.0.
Type ".help" for more information.
> operator_overload=require('./operator_overload.js')
{
  operator_overload: Object <[Object: null prototype] {}> {
    Vector: [class Vector extends Object] {
      new: [Function (anonymous)],
      is: [Function: is_C],
      as: [Function: as_C],
      [Symbol(cachedLegacy)]: undefined,
      [Symbol(cachedNullable)]: undefined,
      [Symbol(_subtypeCache)]: Map(0) {},
      [Symbol(sigMethod)]: [Function (anonymous)],
      [Symbol(libraryUri)]: 'org-dartlang-app:/operator_overload.dart',
      [Symbol(sigField)]: [Function (anonymous)]
    },
    main: [Function: main],
    [Symbol(_privateNames)]: Map(2) {
      'Vector.x' => Symbol(Vector.x),
      'Vector.y' => Symbol(Vector.y)
    }
  }
}
> aa=new operator_overload.operator_overload.Vector.new(1,2)
Vector { [Symbol(Vector.x)]: 1, [Symbol(Vector.y)]: 2 }
> bb=new operator_overload.operator_overload.Vector.new(2,3)
Vector { [Symbol(Vector.x)]: 2, [Symbol(Vector.y)]: 3 }
> cc=aa['+'](bb)
Vector { [Symbol(Vector.x)]: 3, [Symbol(Vector.y)]: 5 }
> aa+bb
'Vector(1, 2)Vector(2, 3)'
> aa.
aa.__defineGetter__      aa.__defineSetter__      aa.__lookupGetter__
aa.__lookupSetter__      aa.__proto__             aa.hasOwnProperty
aa.isPrototypeOf         aa.propertyIsEnumerable  aa.toLocaleString
aa.valueOf

aa.hashCode              aa.noSuchMethod          aa.runtimeType

aa._equals               aa.constructor           aa.sayHello
aa.toString              aa.x                     aa.y

> aa.
```

As you see, the usage of operator overloading is very tedious and not well readable.

**Comment by sigmundch** [comment]
Thanks @liudonghua123 for your question! Please also consider posting questions to stack overflow where other community members may be able to help and provide insights.

I may not be understanding what you are trying to achieve. I sense that you may be trying to use dart2js/ddc for a different purpose than its intended use.

Our compilers goal is to read Dart applications and make them execute properly on a JavaScript engine. However, it is not a goal of these compilers to produce idiomatic JavaScript that can be consumed as a regular JavaScript library. Both DDC and dart2js can change how they represent code in JavaScript, either due to performance or semantic reasons, so the output format is not considered stable and can break at any time. Because of that we strongly recommend against invoking directly the output generated by the compilers.

There is support to consume JavaScript and to export Dart to JavaScript, but we require that developers explicitly export the APIs that will be visible using our JS-interop layer (today that would be using `package:js`). The export layer is stable and you as a developer control it, so you wont be broken by changes to the compiler. Usually this layer consists of a few types in JavaScript that can be used to pass values and invoke functions between the two sides.

In your specific case with operators, unfortunately, I don't believe the exporting API has support for operators today (it mostly supports ES5-style JavaScript).

Hope this clarifies things a bit. Cheers!

**Comment by liudonghua123** [comment]
@sigmundch Thanks for your explanation, I will try to use `package:js` to do some experiments.

Another question, how does `dart-sass` create the JavaScript library? Doesn't it use the `dart2js`/`ddc` toolchain?

**Comment by sigmundch** [comment]
They do, indeed, and also with JS-interop, so they are a great example to follow.

A couple tips when exploring their approach:
* You can find their code at: https://github.com/sass/dart-sass. Their JS-interop APIs are defined here: https://github.com/sass/dart-sass/tree/master/lib/src/node. I believe they also use helper packages to declare common Node APIs (see [package:node_interop](https://pub.dev/packages/node_interop))
* Searching in their repo may give you more details on how they build and deploy their code. I believe they use a package called [cli_pkg](https://pub.dev/packages/cli_pkg) to automate the release process. Under all those layers, you'll probably find that:
  * they use dart2js -- we always recommend using dart2js to deploy since dart2js's output is optimized for production use and ddc's is not, and 
  * they use it in what we call "server-mode" -- dart2js has a mode that is better suited for node.js. If you provide a flag (`dart2js --server-mode`) the compiler makes it an error to depend on libraries like `dart:html` that are only meant to run in browsers.

**Comment by liudonghua123** [comment]
These are really help tips, thanks! 😄
