### ISSUE TITLE
staticElement is null on one of several references when running programmatic analysis

### ISSUE THREAD

**Issue by alanknight-wk** [dart-lang/sdk#44415]
* Dart SDK Version (`dart --version`)
Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"
But also happens on bleeding edge from about two weeks ago.

Context - I'm trying to write something that does some simple analysis of Dart files, cataloguing references. On a fairly simple sample file, implementing a Map that does linear search, there's a variable _keys that's referenced in 4 places. When I run over it 3 of those places have staticElement correctly set, but the 4th does not. Other mechanisms for analyzing the same code don't seem to exhibit this, so it's probably something in the way I'm running the analysis, but it's not obvious.

```
  @override
  void clear() {
    _keys = [];
    _values = [];
  }
```

What I'm doing is roughly

```
  packages = await findPackageConfig(packageDir);
    var allPackageRoots =
        packages.packages.map((each) => p.normalize(each.packageUriRoot.toFilePath())).toList();
    var collection = AnalysisContextCollection(includedPaths: allPackageRoots);
    context = collection.contextFor(libPath);
  }
...
    var resolved = await context.currentSession.getResolvedUnit(path);
...
    var visitor = ReferencesVisitor(document);
    resolved.unit.accept(visitor);
```

where ReferencesVisitor just does a visitSimpleIdentifier, and asks for the staticElement of each identifier. There are 3 other references to that variable within the file and they all have a reference, but for the fourth it's null.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by alanknight-wk** [comment]
[analysis_repro.zip](https://github.com/dart-lang/sdk/files/5653867/analysis_repro.zip)

**Comment by scheglov** [comment]
This is expected behavior. The reason is that for `myVar += 5` there are *two* elements for `myVar` - the getter and the setter (for local variables they are the same). So,  instead [CompoundAssignmentExpression](https://github.com/dart-lang/sdk/blob/dee85df64d183477be997ca5674a104231e4a4ed/pkg/analyzer/lib/dart/ast/ast.dart#L1289)(s) - `AssignmentExpression`, `PostfixExpression`, and `PrefixExpression` store explicit `readElement` and `writeElement`. This happens not only for `SimpleIdentifier`, but also for `PropertyAccess`.

**Comment by alanknight-wk** [comment]
Thanks!
