### ISSUE TITLE
Add optional orElse callback parameter in Iterable.indexWhere similar to Iterable.firstWhere

### ISSUE THREAD

**Issue by mbilalakmal** [dart-lang/sdk#44423]
`Iterable `class in dart:core has a method `firstWhere `which returns the first element which passes a given predicate test, optionally it accepts a callback `orElse `which returns an element if no element passes the test.
The method `indexWhere `however returns -1 if no element passes the given test. Adding a `orElse `callback will offer the caller choice of what to get if the test fails on all elements.

**Comment by lrhn** [comment]
We have no current plans to change the `Iterable` API. It's a hugely breaking change to all existing classes implementing `Iterable`, so the benefit would have to be equally big.

An `orElse` would have to return an integer or throw. I don't think checking the result against `-1` is a big enough hassle that it warrants a breaking change here.
What you can do is to have a helper function:
```dart
int indexWhereOrElse<T>(List<T> elements, bool Function(T) test, int orElse()) {
   var result = elements.indexWhere(test);
   if (result >= 0) return result;
   return orElse();
}
```
You could even make it an extension method.

I don't *personally* think it's worth it. If anything, I'd have one returning `null` on a non-match, then you can use `?? -1` to get the current behavior, or `?? orElse()` to get whichever other behavior you want. 
Using -1 was just copying what JavaScript (which was copying Java, what was copying C) was doing, and Java needed it because their integers weren't nullable.

**Comment by mbilalakmal** [comment]
Okay. Thank you for the suggestion.
