### ISSUE TITLE
[vm] ScopedIsolateStackLimits Thread::saved_shadow_call_stack_

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#44435]
When creating a stack with multiple Dart entries stacked on top of each other, every Dart entry saves its x18 in `Thread::saved_shadow_call_stack_` on entry and exit in `InvokeDartCodeStub`.

However, on exit, `Thread::saved_shadow_call_stack_` now contains the last seen x18 which is of a stack frame which is no longer there.

We should add `Thread::saved_shadow_call_stack_` to `ScopedIsolateStackLimits` such that the previous value gets restored when popping frames from the stack.

The current behavior might not be problematic though. I cannot construct an example which would make the shadow stack grow arbitrarily big.

cc @rmacnak-google 

background: https://dart-review.googlesource.com/c/sdk/+/119481

**Comment by mkustermann** [comment]
Right now we are assuming our generated code (as well as stubs) do not modify `x18` - it's not part of `kDartAvailableCpuRegs` and `CallToRuntimeStub()`s don't restore `x18` before calling C code ... Therefore the only purpose of saving `x18` when entering generated code is because we have special `JumpToFrameStub()` that will jump over some C frames (who would normally pop from `x18`) and land in the most recent `[enter-frame, dart-frame1, ..., exit-frame]` block.

The extra restore of `x18` which we currently have in `StubCode::InvokeDartCodeStub()` doesn't seem to be actually necessary (because a) if there were no exceptions, any call to C and return from C will leave `x18` unchanged b) we restore it in exceptional case c) stub code as well as generated code doesn't use `x18`).

Following this logic, it seems to me that the **only** thing we need to do to make shadow call stack work with FFI is this one change:
```diff
diff --git a/runtime/vm/compiler/backend/il_arm64.cc b/runtime/vm/compiler/backend/il_arm64.cc
index 50100ead94c..f01ebc19746 100644
--- a/runtime/vm/compiler/backend/il_arm64.cc
+++ b/runtime/vm/compiler/backend/il_arm64.cc
@@ -1310,6 +1310,12 @@ void NativeEntryInstr::EmitNativeCode(FlowGraphCompiler* compiler) {
   // Now that we have THR, we can set CSP.
   __ SetupCSPFromThread(THR);
 
+#if defined(TARGET_OS_FUCHSIA)
+  __ str(R18, Address(THR, target::Thread::saved_shadow_call_stack_offset()));
+#elif defined(USING_SHADOW_CALL_STACK)
+#error Unimplemented
+#endif
+
   // Refresh pinned registers values (inc. write barrier mask and null object).
   __ RestorePinnedRegisters();
```

**Comment by mkustermann** [comment]
As discussed above, `x18` needs to be restored in exceptional control flow - which we do. There's no other save/restore necessary since the C compiler will do that for us (even in case of `longjmp()`s).

So I don't think there's anything we need to do. Closing
