### ISSUE TITLE
Standardize Dart LSIF/LSP scheme for monikers

### ISSUE THREAD

**Issue by alanknight-wk** [dart-lang/sdk#44504]
Background: I did some work on an LSIF indexer - https://github.com/Workiva/lsif_indexer. We were using the one mentioned in #39878 but it had some issues, including being based on CrossDart, which hasn't been updated since 2016.

I would like to extend this to support cross-package (project in LSIF terms) references. I'm not especially familiar with LSIF, but as I understand it we can use a moniker, which has a scheme and an identifier within that scheme. So I think we can just make up a Dart scheme. I don't see any use of Moniker in the SDK so far, so I don't think a scheme exists. Since Dart references are reasonably well-structured anyway, I'm thinking something like

`package:foo/path/bar.dart:topLevelScope:otherScope:stillMoreScope:asDeepAsNecessary`

This treats package names as unambiguous, at least within the scope of a moniker, which I think is pretty close to true. Within a library at any level of scope a name is unique. So without needing to distinguish what the type of top-level entity is (class, typedef, extension, variable, function, whatever) we can just nest the names. We don't have to deal with anonymous things because we can't refer to them between packages. And I think colons can't occur within the package URL.

Does this seem reasonable before I go off and implement it? I'm guessing from the other comments I saw that @bwilkerson is the most likely to have thoughts on this.

**Comment by bwilkerson** [comment]
We have discussed adding support for LSIF, but it hasn't yet become a priority for us, so we don't have any existing support.

We do have something similar to a moniker, though. The class [`ElementLocationImpl`](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/element/element.dart#L3095) represents a unique way of identifying an element (our word for a thing that can be referenced). It's very similar to what you proposed, although we include the URI of both the library and the compilation unit in order to account for parts. That might not be necessary for LSIF.

We chose a semicolon as the separator because there's a colon between the scheme and the path in a URI. Given that all of the URIs used in the location are always absolute we could just ignore those colons, but we decided to choose a different character for implementation simplicity.

**Comment by alanknight-wk** [comment]
Ah, excellent. I'll use the toString of the element location. Thanks.

**Comment by bwilkerson** [comment]
In the analyzer code base we reserve `toString` for debugging use and we don't guarantee that it won't change over time. The public API you should use is `encoding`

**Comment by alanknight-wk** [comment]
Understood.
