### ISSUE TITLE
Inherit class assignment not allowed

### ISSUE THREAD

**Issue by salvaterra** [dart-lang/sdk#44535]
From the documentation, this should be allowed:

```
class Animal{
}
class Cat extends Animal{
}
void main() {
  List<Cat> myCats = List<Animal>() as List<Cat>;
  print(myCats.runtimeType);
}
```

Output of the code above
```
Unhandled exception:
type 'List<Animal>' is not a subtype of type 'List<Cat>' in type cast
#0      main (package:untitled3/untitled3.dart:6:37)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

From docs
"What about going in the other direction? Can you assign an Animal list to a List<Cat>? Success"
Source: https://dart.dev/guides/language/type-system#generic-type-assignment
Source doc code: https://github.com/dart-lang/site-www/blob/master/examples/strong/lib/strong_analysis.dart

Tested on beta and stable channels. Tested with both implicit-casts: true and false in analysis_options.yaml.

**Comment by leecommamichael** [comment]
If there's a bug here, I think the docs are trying to be ambiguous about the version of Dart being written. They say about the following line: 
```java
List<Cat> myCats = List<Animal>();
```
> The code may fail at runtime. You can disallow implicit casts by specifying implicit-casts: false in the analysis options file.

But in Dart 2 this will always fail and is nonsensical code. The important thing the docs are, I think, trying to clarify, is that this assignment generates a cast at runtime without the developer's consent. **The docs are, I think, trying to tell us why this crash is expected.**

The advice to change your `analysis_options.yaml` is suggesting that, because the code will never work at runtime, you should consider it a static error.

**Comment by salvaterra** [comment]
Got it. I think you are interpreting it right, thanks for clarifying. It is confusing how it's written. I will close the issue and suggest some rewording. Curious how this would ever run and work.
