### ISSUE TITLE
how does dartjs compile in android mobile environment

### ISSUE THREAD

**Issue by Earlonus** [dart-lang/sdk#44550]
I wanted to embedding the Dart2Js generated Web page into Android or iOS, but because the package generated was so large, I wanted to dart code dynamically, compile it locally on Android, and generate JS files that could be shared with the Web. This requires an environment that compiles Dart2JS locally. Is there a way to do it?

**Comment by sigmundch** [comment]
@Earlonus thanks for your question - please consider in the future posting your question in stack overflow, since the Dart community monitors questions there and you will be able to get more ideas and feedback.

The dart2js compiler is written in Dart, so it can run where Dart runs, this includes ARM and other architectures. That being said, the dart2js compiler is not designed for this purpose and I'm afraid it will likely not meet your requirements. The compiler is intended to optimize applications so that they work well when deployed and doing so is a lot of work and likely more work than it is to download code that is previously compiled to the device.

Teams that have a very large applications use the "deferred loading"  language feature to split their application in pieces, so only portions used for different user journeys are downloaded at a time.  Maybe that's a better fit for you?

I also wanted to note that dart2js is commonly used for developing web applications, but it is less commonly used to build mobile apps. For that, many developers instead use flutter, which doesn't compile Dart to JavaScript, but runs it as native code in the mobile device.

Hope you find this helpful.

Cheers!

**Comment by Earlonus** [comment]
> @Earlonus thanks for your question - please consider in the future posting your question in stack overflow, since the Dart community monitors questions there and you will be able to get more ideas and feedback.
> 
> The dart2js compiler is written in Dart, so it can run where Dart runs, this includes ARM and other architectures. That being said, the dart2js compiler is not designed for this purpose and I'm afraid it will likely not meet your requirements. The compiler is intended to optimize applications so that they work well when deployed and doing so is a lot of work and likely more work than it is to download code that is previously compiled to the device.
> 
> Teams that have a very large applications use the "deferred loading" language feature to split their application in pieces, so only portions used for different user journeys are downloaded at a time. Maybe that's a better fit for you?
> 
> I also wanted to note that dart2js is commonly used for developing web applications, but it is less commonly used to build mobile apps. For that, many developers instead use flutter, which doesn't compile Dart to JavaScript, but runs it as native code in the mobile device.
> 
> Hope you find this helpful.
> 
> Cheers!

thanks for your answer, and I readed this two discussion“#50196 #40576” before post this issue, the same problem with it by using "deferred". all split js file will change in every times. and it makes download file very huge. that is why i'm considering compile it in users mobile phone. it is an app with a large number of users and our team will considering very carefully about using this plan.there are a lot of questions/ideas about dart/dart2js and I am looking forward to more communication.

anyway, thanks for your answer.
