### ISSUE TITLE
Why kernel ast constructor call missing named parameters? Any details help to understand this feature ?

### ISSUE THREAD

**Issue by eeeeeson** [dart-lang/sdk#44559]
1. ref pkg/kernel 7c148d029de32590a8d0d332bf807d25929f080e 
2. writeComponentToText(app.dill), app.dill got by `flutter build aot --release --ios-arch=arm64 --target-platform=ios `  flutter 1.22.5 Dart 2.10.4 (stable)
3. the kernel text output is not expected.

```

class _NoticePageState extends State<NoticePage> {

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        home: new Scaffold(
          appBar: new AppBar(
            title: new Text('通知'),
          ),
          body: new Center(
              child: null
          ),
        ),
        theme: GlobalConfig.themeData
    );
  }

}

```

```
class _NoticePageState extends fra::State<not2::NoticePage*> {
    synthetic constructor •() → not2::_NoticePageState*
      : super fra::State::•()
      ;
    @#C9
    method build(fra::BuildContext* context) → fra::Widget* {
      return let sca::Scaffold* #t1357 = let app::AppBar* #t1358 = new app::AppBar::•(title: new text::Text::•("\u36890\u30693")) in let bas::Center* #t1359 = let core::Null? #t1360 = null in new bas::Center::•(#t1360) in new sca::Scaffold::•(#t1359, appBar: #t1358) in let the::ThemeData* #t1361 = glo::GlobalConfig::themeData in new app2::**MaterialApp::•(#t1357, theme: #t1361)**;
    }
  }
```

the ast node : *MaterialApp::•(#t1357, theme: #t1361) missing the named parameter name of '**home**'?  

Importantly, the printer result of Flutter v1.12.13+hotfix.9  Dart 2.7.2 ref pkg/kernel  1c9356d8990a2a8c90c66097e20cb2f22e5cc267  seems be OK. 

```
  class _NoticePageState extends fra::State<not::NoticePage*> {
    synthetic constructor •() → not::_NoticePageState*
      : super fra::State::•()
      ;
    @#C6
    method build(fra::BuildContext* context) → fra::Widget* {
      return new app::MaterialApp::•(home: new sca::Scaffold::•(appBar: new app2::AppBar::•(title: new text::Text::•("\u36890\u30693")), body: new bas::Center::•(child: null)), theme: glo::GlobalConfig::themeData);
    }
  }
```

**Comment by eeeeeson** [comment]
create issues in flutter project

**Comment by eeeeeson** [comment]
reopen

**Comment by johnniwinther** [comment]
It does look weird. Also the hoisting of the arguments (the adding of `let sca::Scaffold* #t1357 = ...`) is unusual and is not what is generated by the front end.

@alexmarkov Do you know if some transformations are performed specifically for the (flutter) AOT ?

**Comment by eeeeeson** [comment]
> It does look weird. Also the hoisting of the arguments (the adding of `let sca::Scaffold* #t1357 = ...`) is unusual and is not what is generated by the front end.
> 
> @alexmarkov Do you know if some transformations are performed specifically for the (flutter) AOT ?

Thanks for your focus. Can you give me some advice. How to **disable** hidden the constructor's named parameter (e.g. 'home' in app::MaterialApp::•(home:... )?

**Comment by johnniwinther** [comment]
What is the use-case where you need to access the AST directly (or at least depend upon its structure) ?

**Comment by eeeeeson** [comment]
> What is the use-case where you need to access the AST directly (or at least depend upon its structure) ?

We need to pick up all accurate named parameters when constructor called(e.g. for statistics usage). Unfortunately, then named parameter was transformed into positional mistakenly.

**Comment by alexmarkov** [comment]
AOT compiler can prune and transform kernel AST for optimization purposes unless members and classes are annotated with `@pragma("vm:entry-point")`.

In AOT mode there is a VM-specific kernel transformation which removes unused and constant parameters and converts optional parameters into required (and named into positional) if they are always passed. This optimization reduces code size and improves performance because it eliminates prologue code needed to handle optional parameters and removes pushing of arguments which are not used. @askeksa-google might be able to provide more details about this optimization.

This transformation is implemented as part of global type flow analysis and controlled by `treeShakeSignatures` parameter of `transformComponent` (from `pkg/vm/lib/transformations/type_flow/transformer.dart`). In order to disable this transformation you can set `treeShakeSignatures` parameter to `false` in 

https://github.com/dart-lang/sdk/blob/6143fb5668e6af6cea68ae48aa5e7402cb2d03c9/pkg/vm/lib/kernel_front_end.dart#L443-L446

**Comment by eeeeeson** [comment]
@alexmarkov  Thank you for your patient comment pointed the treeShakeSignatures parameter.It is worked!!!
