### ISSUE TITLE
Regarding incorrect Decimal Calculation using Dart.

### ISSUE THREAD

**Issue by SachinR90** [dart-lang/sdk#44571]
I was doing some basic calculation in my app, and I was getting wrong values. So, I tried same but simple basic calculation using [dartpad]( https://dartpad.dev/) and there seems to be some issue in the sdk. For example, Check below.

Example 1

```
void main() {
  var data = 5.1 * 100;
  print(data);
}
```
Current: 509.99999999999994
Expected : 510

<img width="1439" alt="103197450-0ce98d80-490c-11eb-8f43-49f70f4b703b" src="https://user-images.githubusercontent.com/22074472/103335051-c6c23480-4a99-11eb-933a-020f504d536a.png">

Example 2

```
void main() {
  var data = 5.2 * 100;
  print(data);
}
```

Current: 520
Expected: 520

<img width="1437" alt="103197832-cb0d1700-490c-11eb-8966-9be6056d800f" src="https://user-images.githubusercontent.com/22074472/103335105-f40ee280-4a99-11eb-8570-c4921719163e.png">

**Note:** 
Yes, I could use `round` or `toStringAsFixed` on the result of **example 1** to get expected output , but example 2 is not using any such methods, and it still giving expected output. 

Also, if you do `(5.1 * 100).toInt()`, it will return 509, which is incorrect.

Can anyone explain what is going wrong in 1st example?. Is it dart issue ? Please correct me if I am wrong.

**Comment by tatumizer** [comment]
To make sure it's not a dart's problem, you can try doing the same in java
```java
public class Code {
  public static void main(String[] args) {
    System.out.println(5.1*100); // prints 509.99999999999994
  }
}
```
Short explanation: that's how the conversion to floating-point numbers works. 
A longer explanation can be found here: https://docs.python.org/3/tutorial/floatingpoint.html. (It's taken from python documentation, but the underlying phenomenon is universal).
If you'd like to really get to the bottom of it, there's an even longer treatise on the subject: https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by ram231** [comment]
~~Don't worry. We'll get there once quantum computing is ported to dart. Jokes aside,~~  this also occur in different programming languages not just dart.

**Comment by lkrjangid1** [comment]
> ~Don't worry. We'll get there once quantum computing is ported to dart. Jokes aside,~ this also occur in different programming languages not just dart.

when we use cpp it does not happen.

![image](https://user-images.githubusercontent.com/64513385/103403584-a87e3680-4b76-11eb-9ffb-2409d3f1c4db.png)

**Comment by tatumizer** [comment]
Different languages use different *default* settings for number formatting. To compare apples to apples, you have to explicitly set a number format specification.  
```cpp
#include <iostream>
#include <iomanip>

using namespace std;

int main()
{
    cout<< std::setprecision(20) <<5.1*100; // 509.99999999999994316
}
```

**Comment by rakudrama** [comment]
Tatumizer is correct - this is working as intended.
`double` values are based on binary and cannot represent `0.1` or `5.1` without a error.
The closest possible `double` value to `5.1` is slightly smaller that the real value which leads to the behaviour described.

Dart and Java (and many other languages) made the design decision that the default conversion from `double` to `String` and back to `double` (a 'round trip') should not corrupt the data. Since the bit pattern for `5.1 * 100` is not the same as the bit pattern for `510.0`, they necessarily convert to different strings to retain the distinction.

How you display a number is a separate topic to the represented value.
[NumberFormat](https://pub.dev/documentation/intl/latest/intl/NumberFormat-class.html) is one way to control the appearance of the number.
