### ISSUE TITLE
Process.start detachedWithStdio stdout is buffered when not desired

### ISSUE THREAD

**Issue by Sidewinder1138** [dart-lang/sdk#44573]
I'm trying to use Process.start on Windows to just launch an app (I'm making a CLI tool), and then output that app's stdout/stderr to terminal. It works, but I noticed that the stdout is being buffered, it outputs in "real-time" at first, but then halts, and only when I kill the launched process does it dump all the remaining output.

Here's what I'm doing:
```
Process.start(exePath, [],
        workingDirectory: workingDir,
        mode: ProcessStartMode.detachedWithStdio)
    .then((process) {
  process.stdout.pipe(stdout);
  process.stderr.pipe(stderr);
});
```

I've looked at https://github.com/dart-lang/sdk/issues/5607, but it was just closed as if this isn't a problem, which I'm pretty sure it is, at least on Windows.

I'm running from cmd.exe, inside Windows Terminal.

**Comment by a-siva** [comment]
//cc @aam

**Comment by sortie** [comment]
Programs usually default to buffering stdout whenever stdout is not a terminal, such as a file or in a pipe in this case (`ProcessStartMode.detachedWithStdio`). That part is to be expected and has nothing to do with the Dart. Can you confirm that the program in question has switched stdout to be line buffered explicitly, or is correctly flushing stdout at key points? Otherwise it will get the fully buffered behavior in common programming languages whenever stdout is not a terminal.

If the program is in fact flushing its buffers on newlines, and Dart doesn't pipe it, then there is a bug in Dart. But we need to confirm that is the case before jumping to that conclusion.

If you just want to forward stdout and stderr and not capture them, and not input anything on stdin, then you can use `ProcessStartMode.detached` instead that lets the child process use the same input/output/error handles.

**Comment by Sidewinder1138** [comment]
So, my goal is to write a CLI tool in Dart that you can call from the terminal, and then it will in turn launch another program also in the terminal. I guess the problem is that, I don't know how to tell the process that I'm starting to behave as if it is being run from the terminal, that's what I actually want. Think of it like: I can write a BASH script and have that launch various programs, and their output goes to the terminal as expected... I'd like to do something similar but written in Dart (that way it can be smarter). It might also be helpful to have my Dart app watching stdout/stderr for various reasons, but in the end I need it to be the case that any output from the launched process shows up to the end user in the terminal... On linux there is a trick to force the process you are launching to behave as if it is being called from a terminal, but not sure how to do such a thing on Windows. Hope this makes at least some sense. :)

**Comment by aam** [comment]
@Sidewinder1138 how quickly does the buffering kick in for you?

I was trying to reproduce this effect and couldn't. Here is the sample program I used - it seems to be producing the output on the console as I ran it in Windows cmd window:

pipe.dart:
```
import 'dart:io';

main() {
	Process.start('counter.exe', [],
	              mode: ProcessStartMode.detachedWithStdio)
        .then((process) {
          process.stdout.pipe(stdout);
          process.stderr.pipe(stderr);
        }
     );
}```

counter.cc:
```
#include <stdio.h>

int main(int argc, char** argv) {
	for (int i = 0; i < 1000*1000*1000; i++) {
		printf("printing %d\n", i);
	}
}
```

```
c:> dart.exe pipe.dart
printing 1
...
```
