### ISSUE TITLE
HttpClient HEAD request fails with 502 BUT curl succeeds with 200

### ISSUE THREAD

**Issue by jjmutumi** [dart-lang/sdk#44583]
The equivalent to straightforward curl request fails using **HttpClient** from **dart:io** library:
```
curl -I -H "Tus-Resumable: 1.0.0" https://upload.videodelivery.net/tus/e64e5f71ddda9d789c30e62c57c80412?tusv2=true
```

**Sample test**
```dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

main() {
  test('cloudflare HEAD 502', () async {
    final url = Uri.parse(
      "https://upload.videodelivery.net/tus/e64e5f71ddda9d789c30e62c57c80412?tusv2=true",
    );
    final client = HttpClient();
    final request = await client.headUrl(url)
      ..headers.add("Tus-Resumable", "1.0.0")
      ..headers.add("Accept", "*/*");
    final response = await request.close();

    // this fails
    expect(response.statusCode, 200);
  });
}
```

**Successful curl response:**
```
HTTP/1.1 200 OK
Date: Mon, 04 Jan 2021 13:54:42 GMT
Connection: keep-alive
CF-Ray: 60c573f0ccbbd3d7-JIB
Access-Control-Allow-Origin: *
Cache-Control: private
Strict-Transport-Security: max-age=15552000
CF-Cache-Status: DYNAMIC
access-control-allow-headers: Origin, Tus-Resumable, Tus-Version, Location, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Max-Size, Tus-Extension, Tus-Resumable, Upload-Defer-Length, X-HTTP-Method-Override, Content-Type
access-control-allow-methods: GET, POST, PATCH, HEAD
access-control-expose-header: cf-ray
access-control-expose-headers: Tus-Resumable, Tus-Version, Location, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Max-Size, Tus-Extension, Content-Type
cf-request-id: 076f46ca800000d3d732b25000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Served-In-Seconds: 0.033
stream-dw-version: 2020.12.1
stream-media-id: e64e5f71ddda9d789c30e62c57c80412
tus-resumable: 1.0.0
upload-length: 3967382
upload-offset: 0
x-content-type-options: nosniff
Server: cloudflare
```

**Environment:**
```
dart --version
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"

flutter --version
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Comment by BboyKeen** [comment]
Hi @a-siva 
Any news on this one ?
We're facing the same issue

**Comment by BboyKeen** [comment]
For information, as we are Cloudflare Enterprise customers, we're trying to investigate with them to gather information to resolve this issue.

**Comment by zaidf** [comment]
I work on the Stream team at Clouflare. Have you tried using a tus client such as https://pub.dev/packages/tus_client to do the upload? We strongly recommend using a tus client.

**Comment by BboyKeen** [comment]
Hi Zaidf

This issue was first raised using this tus client actually.
If you take a look at the issue history, you'll see that an issue was opened here : https://github.com/jjmutumi/tus_client/issues/11

⁣Télécharger BlueMail pour Android ​

Le 27 juil. 2021 à 20:55, à 20:55, zaidf ***@***.***> a écrit:

**Comment by renandincer** [comment]
Good day folks! I also work at Cloudflare on Stream. We run the server side code that returns the HTTP 502 response code above.

I just looked at the logs for 502 responses for HEAD requests on this application and found >95% of such requests in the last 14 days come from Dart-related user agents.

It appears that these clients send `content-length: 0` when making HEAD requests while curl or some other clients mentioned in https://github.com/jjmutumi/tus_client/issues/11 does not.

You can replicate this issue by making a request like this:

`curl -I -H 'Content-length: 0' -H "Tus-Resumable: 1.0.0" https://upload.videodelivery.net/tus/e64e5f71ddda9d789c30e62c57c80412\?tusv2\=true`

This client behavior is against [RFC-7320, section 3.3.2](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2): 
>A user agent SHOULD NOT send a
   Content-Length header field when the request message does not contain
   a payload body and the method semantics do not anticipate such a
   body.
   
It appears that this issue has already been reported in https://github.com/dart-lang/sdk/issues/45139 and https://github.com/dart-lang/sdk/issues/45871; and fixed in https://github.com/dart-lang/sdk/commit/6c254fab89adbeebfb616cdec497260db4cb7cf7. There earliest release with this change is `2.14.0-181.0.dev`.

I suggest I suggest upgrading your version to resolve this issue.

**Comment by BboyKeen** [comment]
Hi Renan

Thank you for the followup.
We really appreciate your help on this as it's always difficult to understand what's wrong when something occurs server-side.

@jjmutumi Can we consider upgrading the dart HTTP client to the last version mentioned ?

@a-siva I think we can close this issue if a fix has already been pushed on your side for  similar issues.


Le 28 juil. 2021 à 22:35, à 22:35, Renan Dincer ***@***.***> a écrit:
