### ISSUE TITLE
 Is there a fatal rounding error

### ISSUE THREAD

**Issue by rhymelph** [dart-lang/sdk#44596]
version : Dart SDK version: 2.12.0-29.10.beta (beta) (Tue Nov 17 10:50:22 2020 +0100) on "macos_x64"

It is my code .
```dart
    double a = 5.885;
    String aS = a.toStringAsFixed(2);
    double b = double.parse(aS);
    print('a:$a , aS:$aS , b:$b');
```
out put 
```
a:5.885 , aS:5.88 , b:5.88
```
Why not `aS` is not 5.89?

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
Working as intended.

Doubles cannot represent all rational values, and the rational number 5.885 is not precisely representable as a double.
When you write the literal `5.885` it's taken to represent the closest actual double value, which happens to be 5.8849999999999997868371792719699442386627197265625.
Each double represents a *range* of rational/real numbers, those that are closer to that double's precise value than to any other double. That's why `5.8849999999999994 == 5.885` is true, both are in the range represented by the double value above.

When you do `toStringAsFixed(2)`, it rounds that precise value to the nearest two decimal digits, which is the rational number 5.88. It doesn't see the value `a` as being equally close to `5.88` and `5.89`, so it just picks the closer `5.88`.
The `toStringAsFIxed` does round away from zero when the rest of the number is precisely a `5` digit, which is why `0.125.toStringAsFixed(2)` gives `0.13`. That's just not applicable here.

When you *print* (or `toString()`) a double, it doesn't print the entire representation. Instead it chooses the *shortest* number which will end up being represented by the same double. So, printing `a` above prints `5.885` even though it's not the precise value. It's just the shortest numeral in the range of numbers represented by the actual value.

**Comment by rhymelph** [comment]
I know, but more people believe that as = 0.59, don't they?
And look at the example,`num.dart`
```dart
   / *
   *
   * Examples:
   *
   *     1.toStringAsFixed(3);  // 1.000
   *     (4321.12345678).toStringAsFixed(3);  // 4321.123
   *     (4321.12345678).toStringAsFixed(5);  // 4321.12346
   *     123456789012345.toStringAsFixed(3);  // 123456789012345.000
   *     10000000000000000.toStringAsFixed(4); // 10000000000000000.0000
   *     5.25.toStringAsFixed(0); // 5
   */
  String toStringAsFixed(int fractionDigits);
```
only found the `(4321.12345678).toStringAsFixed(5);  // 4321.12346` ,is not  `(0.588).toStringAsFixed(2); // 0.58`

**Comment by lrhn** [comment]
Not entirely sure what you're asking here.
The `4321.12345678).toStringAsFixed(5)` gives `"4321.12346"` because the *actual* value of the number is greater than or equal to `4321.123455`. 

If the example had been `4321.123455.toStringAsFixed(5)`, I would not be able to predict the outcome. 
(Just checked, that value is actually `4321.1234549999999217106960713863372802734375` so it becomes `"4321.12345"`).

It's not important what more people think here, we don't actually have any good choice.
Take:
```dart
var d1 = 5.8849999999999994;
var d1s = d.toStringAsFixed(2); // Expect 5.88?
var d2 = 5.885;
var d2s = d.toStringAsFixed(2); // Expect 5.89?
```
We *can't* give different results for `d1s` and `d2s` here because the number is exactly the same number in both cases.
```dart
print(identical(d1, d2)); // true
```
So, we have to choose one result. We have gone with the result based on the actual precise value of the double.
Again, it's not a place where we have a lot of choice because we want to compile `5.885.toStringAsFixed(2)` into `5.885.toFixed(2)` in the browser, and the result there is also `"5.88"`.

I guess it's technically possible to detect that the *range* represented by the double contains values on both sides of the midpoint that we round away from, and then choose a different number to represent that range than the double's precise value.
Perhaps by doing `.toString` to get the shortest representation, and using that, which would give 5.89. I don't actually know how simple that would be to do, but I know it's not as easy, or efficient, as calling the browser built-in `toFixed`.

**Comment by rhymelph** [comment]
So, when I use  `toStringAsFixed`  rounding to calculate the value, there is a high probability of calculation error. At present, I use the `decimal` package to solve this problem, which can be referred to

**Comment by lrhn** [comment]
The `decimal` package represents the numbers as powers of ten, not powers of two like doubles, which means that numbers like 5.885 are exactly representable as a decimal fractional number. Using that package is a good way to avoid the imprecision of doubles when dealing with decimal fractions.

It's really not a calculation error, it's a *representation* error. You never had the value 5.885 to begin with. Assuming that was where the problems started. The loss of precision is why you should always use `decimal`, or something similar, for counting money: Doubles cannot represent most two-digit decimal fractions correctly, the only ones that are actually precise are `.00`, `.25`, `.50`, and `.75`. The rest are off by a little.

**Comment by mit-mit** [comment]
@rhymelph please note that this representational behavior of doubles is not specific to Dart, it's the way doubles work generally. Here is a similar thread for Kotlin: https://discuss.kotlinlang.org/t/how-do-you-round-a-number-to-n-decimal-places/8843/17
