### ISSUE TITLE
Analyzer's UNCHECKED_USE_OF_NULLABLE_VALUE message should be made more friendly

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#44603]
If a nullable expression is "dereferenced" (e.g. `int? x; x.isEven;`), the analyzer reports the following error:

> An expression whose value can be 'null' must be null-checked before it can be dereferenced.

@leafpetersen notes that "dereferenced" is not the best word here, and perhaps we can improve the messaging for the various "dereferencing" which occurs. I think the error can be split into several. In each case, `foo` is a nullable expression:

* `foo.field`
  * message: "An expression whose value can be 'null' must be null-checked before a property on the expression can be accessed."
  * correction: "Try checking that the value isn't 'null' before accessing the property."
* `foo.method()`
  * message: "An expression whose value can be 'null' must be null-checked before a method on the expression can be called."
  * correction: "Try checking that the value isn't 'null' before calling the method."
* `if (foo)`, `foo ? x : y`, `while (foo)`, `foo && x`, `!foo`
  * message: "A nullable expression cannot be used as a bool value."
  * correction: "Try checking that the value isn't 'null' before using it as a bool value."
* `for (var e in foo)`
  * message: "A nullable expression cannot be used as an iterator."
  * correction: "Try checking that the value isn't 'null' before using it as an iterator."
* `[...foo]`
  * message: "A nullable expression cannot be used in a spread."
  * correction: "Try checking that the value isn't 'null' before using it in a spread, or use a null-aware spread."
* `yield* foo;`
  * message: "A nullable expression cannot be used in a yield-each statement."
  * correction: "Try checking that the value isn't 'null' before using it in a yield-each statement."

Perhaps also:
* `foo + x`, `foo++`, `foo += x`, `foo[x]`
  * message: "An expression whose value can be 'null' must be null-checked before an operator can be invoked."
  * correction: "Try checking that the value isn't 'null' before invoking the operator."
* `foo()`
  * message: "An expression whose value can be 'null' must be null-checked before being invoked."
  * correction: "Try checking that the value isn't 'null' before invoking it."

**Comment by srawlins** [comment]
Additional notes:

* "An expression whose value can be 'null'" is much longer than "A nullable expression". Is the latter kosher? We seem to use the word "nullable" in other errors.

* Is "... before using it as a bool value" correct, or should we use the word "boolean"?

* Is "... before using it as an iterator" good? Maybe "... as a for-each iterator"?

**Comment by srawlins** [comment]
cc @bwilkerson who had an interest, and @jwren who dug this case up.

**Comment by bwilkerson** [comment]
This is definitely moving in the right direction.

> "An expression whose value can be 'null' must be null-checked before a property on the expression can be accessed."
> "An expression whose value can be 'null' must be null-checked before a method on the expression can be called."

I'd like to keep the term "null check" to refer specifically to the postfix `!` operator and use "conditional access" or "conditional invocation" for the `?.` (and similar) operators. Given that, and given that these problems can both be solved in two ways, I'd prefer to see these messages generalized. Perhaps something like

message: "The property '{0}' can't be unconditionally accessed because the receiver can be 'null'."
correction: "Try making the access conditional (using '?.') or adding a null check to the target ('!')."

> "An expression whose value can be 'null'" is much longer than "A nullable expression". Is the latter kosher? We seem to use the word "nullable" in other errors.

Yes, "nullable" is fine, as is "non-nullable" and "potentially nullable".

> "A nullable expression cannot be used as a bool value."
> "Try checking that the value isn't 'null' before using it as a bool value."
> Is "... before using it as a bool value" correct, or should we use the word "boolean"?

We should only use "bool" when we're referring to the type; otherwise we should use "Boolean" (It's capitalized because it's named after George Boole. See https://en.wikipedia.org/wiki/Boolean_data_type for more details.) But in this case perhaps the better approach would be to refer to it as a "condition". Also, the messages should be written in a less formal style, so perhaps

message: "A nullable expression can't be used as a condition."
correction: "Try checking that the value isn't 'null' before using it as a condition."

> "A nullable expression cannot be used as an iterator."
> Is "... before using it as an iterator" good? Maybe "... as a for-each iterator"?

The word "iterator" is fine. We don't have specialized iterators for for-in loops (note the name change for consistency with other messages and documentation). But it wouldn't hurt to be more precise in the message, so perhaps

message: "A nullable expression can't be used as an iterator in a for-in loop."

> "An expression whose value can be 'null' must be null-checked before an operator can be invoked."

Similar comment as above. Perhaps

message: "The operator '{0}' can't be unconditionally invoked because the receiver can be 'null'."

> "An expression whose value can be 'null' must be null-checked before being invoked."

Similar comment as above. Perhaps

message: "The function can't be unconditionally invoked because it can be 'null'."

**Comment by srawlins** [comment]
Fixed
