### ISSUE TITLE
Does dart allow nested mixin?

### ISSUE THREAD

**Issue by LeoFavor1562** [dart-lang/sdk#44606]
**The code as follows:**
```
class A {
  void abcd() {
    print('abcd');
  }
}

class B with A  {}

class C with B {
  // @override
  // void abcd() {
  // }
}
```
**The error as follows:**
```
Error: The non-abstract class 'C' is missing implementations for these members:
 - A.abcd
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class C with B {
      ^
Context: 'A.abcd' is defined here.
  void abcd() {
       ^^^^
```
But when I override the function 'abcd' or make 'C' mixin A, it works well.
Why must I override the function 'abcd' ? How do i avoid overriding it?

**Comment by eernstg** [comment]
It looks like you are using a very old version of Dart; in current Dart it is a compile-time error to use a class `D` as a mixin unless the superclass of `D` is `Object`. In the example, the superclass of `B` is `Object with A`, so `B` can't be used as a mixin.

**Comment by a-siva** [comment]
@LeoFavor1562 does the comment above answer your question?

**Comment by LeoFavor1562** [comment]
@eernstg 
Thank you for your answer. But I'm still confused.
My dart version is 2.10.0, and I added file `analysis_options.yaml` in my project with code:
```
analyzer:
  strong-mode: true
  errors:
    mixin_inherits_from_not_object: ignore
```
to solve the compile-time error.

1. if `B` can't be used as a mixin, why when I override the method `abcd` in class `C`, the error is gone?
2. if I modify the example code:
```
class A {
  void abcd() {
    print('abcd');
  }
}

class B with A  {}

class C with A, B {//<--
  // @override
  // void abcd() {
  // }
}
```
the error is gone too, why does this happen?

**Comment by eernstg** [comment]
If you ignore a compile-time error there are no guarantees. This mechanism is rather controversial in the first place, and it's only supposed to be used to avoid seeing errors in a situation where a library does not exist because it's provided by code generation, and similar situations where the errors are temporary. There is no general mechanism which could make a program work if it has a compile-time error, but it may be justified to use this mechanism to avoid some temporary noise.

However, in this particular case you'll probably end up using an undocumented enhancement of the mixin mechanism where it was allowed to use a class `B` as a mixin even though the superclass `S` of `B` wasn't `Object`. In that case the superclass `S` isn't actually included, you still just get the declarations from the class `B` that you're using as a mixin, nothing that `B` inherits from `S`. Stop using that loophole, it will go away. ;-)

Anyway, in the [example](https://github.com/dart-lang/sdk/issues/44606#issue-781268573) this means that you don't get the implementation of `abcd` from `A`, you only get the promise (as in `implements A`) that there will be such an implementation, and then you need to write it yourself.

In the [second example](https://github.com/dart-lang/sdk/issues/44606#issuecomment-756510347) you are mixing in `A` and then mixing in `B`, and this means that you _do_ get the implementation of `abcd` (when `A` is mixed in).

The meaning of the class `B` when used as a mixin is expressed as follows in current Dart:

```dart
mixin B implements A  {}
```

This is not a particularly useful mixin, but it does show clearly what it delivers: It introduces the requirement that any class mixing in this mixin must have a method `void abcd()` implementation; but you won't get it from this mixin, so you may need to write that implementation yourself (or mix in some other mixin that does deliver the implementation).

I'll close this issue because the underlying feature request is covered by https://github.com/dart-lang/language/issues/540.

**Comment by LeoFavor1562** [comment]
@eernstg 
Thanks a lot!
