### ISSUE TITLE
DDC golden file update does not work on Windows.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44618]
Running
```
dart pkg/dev_compiler/tool/check_nnbd_sdk.dart  --update-golden
```
reports
```
Golden file does not support Windows.  Skipping.
```
Since I'm working on Windows and need to update the golden files, that's pretty annoying.

Consider either supporting Windows (or removing line numbers from the golden files - it's highly annoying to have to run this update tool *every* *time* I touch something in `dart:core`, even if it's just documentation).

(Maybe it does work on Windows, it ran and updated the file when I removed the check for whether it was running on Windows).

**Comment by sigmundch** [comment]
Thanks @lrhn for reaching out again, agree this is not fair on your end.

We are doing the change to remove the line numbers ASAP. I think we may be able to delete this check altogether soon too.

I'll close this issue since it is not worth adding support for windows to be honest. Let's continue the discussion in #44491 if that's OK with you.

**Comment by lrhn** [comment]
That's awesome! Thanks you!
