### ISSUE TITLE
Packaging for Debian and other distros: bootstrapping from source only without prebuilt binaries?

### ISSUE THREAD

**Issue by anthonyfok** [dart-lang/sdk#44625]
Hello,

There are growing interests in having Dart as an official Debian package.  For example, there are requests to have Flutter built for Debian, and as now Dart Sass has become the primary implementation of Sass, replacing the deprecated Ruby and C/C++ LibSass implementations.  These all require Dart to be packaged for Debian, similar to how Go (golang) has become an integral part of Debian, and as a reply to https://bugs.debian.org/931793 says:

> No dart in Debian, still a long way to go!

As a Debian Developer myself, I have started looking into packaging Dart for Debian, but quickly encountered a problem:  seems to be no way of building Dart from source code only, and instead the current build system requires prebuilt binaries?  From what I could guess from git commit logs, the build system *did* allow bootstrapping Dart from source before 2018, but now it seems the use of prebuilt dart binaries (for speed) is the only way left?

So, am I missing something?  Is there anyway to bootstrap Dart from source only without reliance on prebuilt binaries, so that we as Linux distribution maintainers can package Dart for Debian/Ubuntu, Fedora, etc., and to test and to try to get Dart to work on architectures other than X86 and ARM?

Many thanks!

Anthony

**Comment by mraleph** [comment]
In this particular case it is not really about the speed. In 2018 we moved from multiple Dart front-ends to a single Dart front-end (aka CFE) written in Dart itself, which created a circular dependency in the build graph: to be able to parse and run any Dart code you need to be able to parse and run Dart code implementing the CFE first. Similar to how building a GCC requires some C compiler to be available. The way we break this dependency is by using prebuilt binaries: you use a prebuilt Dart binary to run CFE to compile Dart code to its binary AST representation (aka Kernel) which then can be run on the VM. Another (more portable) way to break this dependency would be to store just an older version of CFE compiled to Kernel instead. But it is unclear if this portability yields anything meaningful: Dart supports a limited number of platforms and you can't just take it and build it say for Linux on MIPS. And for all platforms we support we have prebuilt binaries.

> to try to get Dart to work on architectures other than X86 and ARM?

Porting Dart to a new architecture is not just about compiling it. Running Dart natively requires writing a new backend for Dart VM, which is a significant investment of time. (There is a trick to bypass this by building and running one of our simulated builds, but it is hardly useful because performance would be too bad to run anything meaningful).

**Comment by mimi89999** [comment]
Hello,
Bootstraping Dart using itself should be allowed. It would be a 2 stage process. First Dart would be built using prebuilt binaries and then it would rebuild itself. The biggest problems are that the build still requires Python2 and that it's not possible to use system build tools to build Dart instead of using those downloaded by depot tools.
