### ISSUE TITLE
Add a hint away from `== double.nan`

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#44649]
I am pretty sure you guys are already familiar with this, but I want to suggest a modification.

I wanted to compare a double with NaN as in `myDouble == double.nan` and it doesn't work at all, contrary to what one might expect. After searching online I found we can use `double.isNaN`, but that's not the first thing that devs have in mind.

If by some performance reason you don't want to make that check on `==`, then could we have a warning from the Dart Analysis at least?

**Comment by natebosch** [comment]
Transferring to the SDK and rephrasing as a request to add a hint in the analyzer. I can't think of a valid reason to do `anything == double.nan` or `double.nan == anything`.

**Comment by feinstein** [comment]
Perfect Nate, thanks!

**Comment by lrhn** [comment]
Agree on the hint. It's *technically* possible to cook up a class with an `operator==` which returns `true` when given `double.nan`, but in any practical situation `== nan` is always going to be `false` (and `nan == ...` is *always* false, so that weird class would break symmetry for `==` instead of reflexivity).

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/269881
