### ISSUE TITLE
async* stream is not stopped after it was cancelled during await

### ISSUE THREAD

**Issue by MatrixDev** [dart-lang/sdk#44718]
Consider following code:
```dart
Stream<void> loop() async* {
  print('a1');
  await Future.delayed(Duration(seconds: 2));
  print('a2');
}

void main() async {
  final subscription = loop().listen(null);
  await Future.delayed(Duration(seconds: 1));
  subscription.cancel();
}
```

"a2" will be printed. I think `Stream` should be stopped at least during inner `await` operations.

As a workaround `loop` function can be modified to support proper "cancellation":
```dart
Stream<void> loop() async* {
  print('a1');
  await Future.delayed(Duration(seconds: 2));
  yield* Stream.empty(); // FIX IS HERE
  print('a2');
}
```

This way `Stream` will be properly stopped during `yield*` operation and "a2" will not be printed.

**Comment by lrhn** [comment]
Working as intended.

You can *only* cancel an `async*` function at a `yield` or `yield*` statement. 
This is a very deliberate choice. 
For example, an expression of the form `var resource = await allocate();` expects that either will the resource be successfully allocated, or the expression throws. And the `allocate` function expects that its return value will be received, so that it can be properly released. That allows you to write something like:
```dart
  var resource = await allocate();
  try {
    doStuff(resource);
  } finally {
    await resource.release();
  }
}
```
If this code is inside an `async*` code, and the `await allocate()` could just bail out because of a stream subscription cancel, then it's possible for the allocation to succeed, but the result to never be delivered. That would cause a resource leak.

So, in general, breaking an `await` is potentially bad and always unpredictable, so you can only break out of an `async*` function at a `yield` or `yield*` statement, the two statements which are unique to `async*`/`sync*` functions.
