### ISSUE TITLE
[dev_compiler] Constants not evaluated correctly in expression evaluation

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#44713]
**Repro:**

```
import 'dart:async';
import 'dart:convert';
import 'dart:developer';
import 'dart:html';

void main() {
  print('Initial Print');

  registerExtension('ext.print', (_, __) async {
    print('Hello World');
    return ServiceExtensionResponse.result(json.encode({'success': true}));
  });
  document.body.append(SpanElement()..text = 'Hello World!!');

  var count = 0;
  Timer.periodic(const Duration(seconds: 1), (_) {
    print('Counter is: ${++count}'); // breakpoint here
  });
}
```

- Put a breakpoint in the debugger on line printing the counter
- Try to evaluate `print` (shows JS body) 
- Try to evaluate `main` (shows JS body of `print` instead of `main`)

Dart SDK version: 2.12.0-237.0.dev (dev) (Sun Jan 17 17:49:12 2021 -0800) on "macos_x64"

**Comment by Markzipan** [comment]
V8 optimizations removing certain libraries from scope underly this issue. We end up reusing the same constant cache on an evaluation error, which makes this appear like a constant correctness problem. 

For example, try evaluating `foo` for both these cases:
```
import 'dart:async';
import 'dart:convert';
import 'dart:developer';
import 'dart:html';

class MyClass {
  const MyClass();
}

void main() {
  registerExtension('ext.print', (_, __) async {
    print('Hello World');
    return ServiceExtensionResponse.result(json.encode({'success': true}));
  });
  document.body.append(SpanElement()..text = 'Hello World!!');

  var count = 0; // Breakpoint here
}
```
and
```
import 'dart:async';
import 'dart:convert';
import 'dart:developer';
import 'dart:html';

void main() {
  registerExtension('ext.print', (_, __) async {
    print('Hello World');
    return ServiceExtensionResponse.result(json.encode({'success': true}));
  });
  document.body.append(SpanElement()..text = 'Hello World!!');

  var count = 0; // Breakpoint here
}
```
The latter works since it forces `main` into scope. The former gives this error. Additionally, removing the `registerExtension` portion removes `dart` from scope, which is the same underlying V8 issue. I've made a change that'll at least make it fail consistently. But fixing this underlying problem will take more time.
