### ISSUE TITLE
Dartdevk produces an error when null is returned from async function with return type dyncmic

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#44745]
The following co19 [test](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/future_value_type_A05_t01.dart) fails on dartdevc compiler with `Error: Expected a value of type 'Object', but got one of type 'Null'`
```dart
Object test1() async {
  Object? o = null;
  return o;
}

dynamic test2() async {
  Object? o = null;
  return o;
}

main() {
  test1();
  test2();
}
```
Error [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8857500030613070656/+/steps/test_results/0/logs/new_test_failures__logs_/0)
This test works well on all other platforms and must pass on derdevk as well

**Comment by eernstg** [comment]
Drive-by comment: I agree that there is no error in this example. However, the [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8857500030613070656/+/steps/test_results/0/logs/new_test_failures__logs_/0) looks like `dartdevk-strong-linux-release-chrome` is crashing rather than reporting a (spurious) type error in the program under compilation.

**Comment by nshahan** [comment]
Thanks for the report. From my investigation this looks more like it is an issue with the method statically typed to return `Object` when running in sound mode. DDC has some code that needs to be updated with the change in the spec in regard to the Future value type for returns in async methods. I have a fix in progress.
