### ISSUE TITLE
String concatenation taking too long in this particular case

### ISSUE THREAD

**Issue by GnRSlash** [dart-lang/sdk#44776]
Hi,

I am testing a small piece of code using Android Studio, in Windows 10, using flutter web in Chrome and dart version is:
Dart SDK version: 2.12.0-133.7.beta (beta) (Tue Jan 12 09:25:38 2021 +0100) on "windows_x64"

I am using excel package:  https://pub.dev/packages/excel

This is the result of time spent:
Generating executed in 0:07:22.328475

And this is the code that you need to reproduce:

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Stopwatch stopwatch = new Stopwatch()..start();

            Excel excel = Excel.createExcel();
            Sheet sh = excel['Sheet1'];
            for (int row = 1; row < 9000; row++) {
              for (int col = 0; col < 9; col++) {
                sh.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
                    .value = 'value ${row}_$col';
              }
            }
            print('Generating executed in ${stopwatch.elapsed}');
          },
          child: Text('Export'),
        ),
      ),
    );
  }
```

### BUT, if you change this piece of code:
```
                sh.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
                    .value = 'value ${row}_$col';
```

### to this:
```
                sh.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
                    .value = 'value ';
```

The time becomes almost zero!

So, I think that the problem isn't related with package, maybe memory allocation?

If my question is not related to dart-sdk, no problem, just close this and I'll find another way to do my job.
Thank you!

**Comment by lrhn** [comment]
I don't think the time comes from the memory allocation, at least not the string itself.

(Sidetrack: The difference between `'value '` and `'value ${row}_$col'` is that the former is a single constant value and the latter creates one (or more) new strings for each iteration of the loop. That's ~81000 new strings, where each does `row.toString()` first, which itself creates a new string. (I think `$row` will likely not create a new string each time, there are optimizations in place for `toString` of small integers, but not all the way up to 9000).
Converting integers to strings is actually not particularly fast. You're doing repeated division by 10 in order to find the digits, and integer division is one of the things even modern CPUs are fairly (relatively) slow at. Dart instead divides by 100, and handles two digit at a time to reduce the impact, but you still need two of those divisions for most of your numbers.
So yes, you are allocating ~81k new strings, each created by doing `toString` on two integers, at least one of which is probably not cached. That amount to *some* time, but *nowhere near* seven minutes!)

The more likely reason for the delay is that setting the `cell` content makes the Excel package try to *parse* the string you're setting. Maybe it's a formula? Maybe it's a date? Maybe it's just a string. There's only one way to be sure, and that's to check the string ... or, just maybe, keep a cache of already seen strings, which could be why using the *same string* every time is so blindingly efficient.

You can try to change the code to:
```dart
var tmp = 'value ${row}_$col';
sh.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
                    .value = tmp.substring(0, 6); // Always "value ".
```
Then you're doing both the same *computation* and the same *assignment*, and if that also takes almost no time, then the inefficiency is in the Excel package seeing many different strings, not in the string concatenation itself.

**Comment by mraleph** [comment]
Whenever you are facing a performance issue I suggest profiling see https://flutter.dev/docs/perf/rendering/ui-performance or more specifically https://flutter.dev/docs/development/tools/devtools/cpu-profiler.

In this particular case though a problem can be found just by quickly glancing through the code. 

When you do `.value = 'something'` the execution eventually ends up [in these lines of code](https://github.com/justkawal/excel/blob/master/lib/src/sheet/sheet.dart#L973-L976):

```dart
    if (value.runtimeType == String &&
        !_excel._sharedStrings.contains('$value')) {
      _excel._sharedStrings.add(value.toString());
    }
```

When you look at definition of `_sharedStrings` you can discover that it is actually a `List<String>`. 

So this code ends up putting `9000*9` unique strings into a list checking each time whether the list already contains this string. This of course is going to be quadratic in number of strings which is quite a large number here.

You should report this issue to the author of the excel package @justkawal.
