### ISSUE TITLE
Analyzer crashes when mistyped 'or' instead of ||

### ISSUE THREAD

**Issue by MichalTorma** [dart-lang/sdk#44785]
Hi everyone, thanks for creating an amazing tool that is Dart. Anyway, I stumbled upon this edge-case in the analyzer when I forgot to switch my head from Python to Dart...
Analyzer crashes when I mistyped 'or' instead of || operator in if statement. An error that the analyzer gives makes no sense to me and what is worse, the LSP server in VS Code crashes.
example code:
``` dart
foo(int a, int b){
  if (a == null or b == null){
    return null
  }
}
```

analyzer error: 
``` bash
Expected to find ')' at lib/tools/test.dart:1:36 • (expected_token)
```
LSP error in VS Code: 
``` bash
[Error - 12:15:43 AM] Request textDocument/codeAction failed.
  Message: Invalid line number
  Code: -32004 
28
```

**Comment by bwilkerson** [comment]
Ideally we would recognize `or` and `and` as misspellings of `||` and `&&` and report the correct spelling.

@DanTup For the LSP error

**Comment by johnniwinther** [comment]
@jensjoha Don't we already special-case `and` and `or`, or am I misremembering?

**Comment by jensjoha** [comment]
We special-case `and` and `or` (and `xor`, `shl`, and `shr`) for binary operations. I think that's what crashing here though. I'll take a look.

**Comment by DanTup** [comment]
I was able to reproduce this error with LSP, but it doesn't seem like the server crashes - it just rejects the request(s) and continues to work once the code is corrected such that the parser doesn't fail (although that bug is now fixed, so it's not reproducible on the latest code).

The parsing failure prevents mapping the `Position` from LSP to an `int offset` which results in this error. The cause is always either the result of a bad request from the client, or something went wrong parsing on the server, so I think it's correct to return an error (silently returning nothing could mask serious issues).

Whether there should be another error shown (the parse failure) though, I'm not sure. @bwilkerson I think the error is being handled [here](https://github.com/dart-lang/sdk/blob/b971bbd199633ed8a2ca9c8b17f131c45db7f888/pkg/analyzer/lib/src/dart/analysis/file_state.dart#L408-L412) (called from `AnalysisDriver._computeAnalysisResult`) and therefore not being seen by the server.

**Comment by bwilkerson** [comment]
> Whether there should be another error shown (the parse failure) though, I'm not sure.

I'm not sure either. The question in my mind is whether reporting the error is useful information for the user. On the one hand, there's nothing that a user can do to correct the situation other than to continue typing and hope that they arrive at code the parser is able to parse. On the other hand, some people think that the user would want to know that the results they're seeing are not accurate. We could certainly provide that information, but we'd also need to inform the user when the results are once again accurate, or they'd never know when to trust the tool.

> I think the error is being handled here ... and therefore not being seen by the server.

That code appears to be part of the serialization / deserialization support, which prevents the analyzer from building a resolved AST. But the parsing that happens when we're analyzing the file happens somewhere else. Note that we're passing in an error listener that discards diagnostics, yet somewhere else we're parsing with an error listener that retains the diagnostics, otherwise we wouldn't be able to report them to the user.
