### ISSUE TITLE
How to report memory leak?

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#44792]
After a few hours of working in Flutter, Dart process slows my computer and when I see, it is consuming 20 GB of RAM. This happens frequently (like daily/weekly). Is it possible to somehow report it? If I get the process information, will it be useful? I don't have any reproducible steps, but I wish there were a magical log file I could get for you to help you mitigate the issue.  

![image](https://user-images.githubusercontent.com/351125/106063298-b754fc00-60d6-11eb-95fa-046f376c0552.png)

**Comment by a-siva** [comment]
The growth in memory could be because of various reasons
- the Dart heap is growing because of a memory leak in the app
- the app is working with large data sets and requires the space which is causing the Dart heap to grow
- there is a leak in Flutter framework or the Dart runtime

Will you be able to use devtools on your app and capture the memory growth in order to be able to analyze the cause?
@jacob314  could provide you pointers on how to diagnose leaks in the app using devtools

**Comment by mraleph** [comment]
@bernaferrari fwiw, the first step would be to identify which process is leaking memory. It might be one of Flutter/Dart related tools (e.g. analyzer - based on the fact that you also have an IDE running). Next time you see a process like this in the terminal do `ps -p $PID` where `$PID` should be replaced with the pid of the leaking process (e.g. 8965 in your screenshot above) and then paste the output here.

**Comment by bernaferrari** [comment]
>   PID TTY           TIME CMD
10428 ??         6:47.03 /usr/local/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/usr/local/flutter/packages/flutter_tools/.packages /usr/local/flutter/bin/cache/flutter_tools.snapshot --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --web-port=1234 --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main_editor5.dart

**Comment by mraleph** [comment]
Seems like a flutter tools process responsible for communication between IDE and a running application (in this case a Flutter Web application). I suggest reporting this issue on Flutter issue tracker then.

/cc @jacob314 for visibility here.
