### ISSUE TITLE
Uri setters

### ISSUE THREAD

**Issue by 89z** [dart-lang/sdk#44819]
If I have code like this:

~~~dart
void main() {
   var u = Uri();
   u.host = 'dart.dev';
}
~~~

I get this result:

~~~
a.dart:8:6: Error: The setter 'host' isn't defined for the class 'Uri'.
 - 'Uri' is from 'dart:core'.
Try correcting the name to the name of an existing setter, or defining a setter
or field named 'host'.
   u.host = 'dart.dev';
     ^^^^
~~~

I think all the `Uri` properties should have setters, otherwise people are forced
to set them at time of object declaration.

**Comment by 89z** [comment]
Example here from another language:

https://developer.mozilla.org/docs/Web/API/URL/host

can get and set

**Comment by lrhn** [comment]
Dart URIs are immutable. That makes it safe to share them, instead of everybody who stores a URI needing to copy them defensively.
If you want to change the host, you can use the [replace](https://api.dart.dev/stable/2.10.5/dart-core/Uri/replace.html) function: `u = u.replace(host: 'dart.dev');`.

We have no plan to change the Uri class to be mutable.

**Comment by 89z** [comment]
It seems like the negatives would outweigh the positives of doing that. Ive never seen any programming language give back and object that you can even modify. Most languages leave that up to the user to do via `freeze` or similar. Giving back frozen objects by default would seem wasteful, as the user ends up having to create copies of the entire object, any time they want to make any change.

**Comment by lrhn** [comment]
Immutable objects are actually quite widespread in object oriented languages. Because objects have identity, any mutation will immediately affect all other code that has access to the same object. Almost any language which have a `String` class also makes it impossible to change the content of an existing string. That's not because `String` is a "primitive type" (it rarely is), but because strings are objects that you very often *share* with other code. If you use a string as a map key, and someone else is able to change its contents, they break your map.
When you have shared mutable objects, you need some strategy to defend yourself:
* Hopes and prayers. Just assume that nobody changes the object, and 99% of the time you're right. The last percent is going to be a bastard to debug.
* Defensive copying. If you want to keep an object longer than just a single synchronous call, you make your own copy of it. (If the language supports copy-on-write, that might make it less expensive, but most don't). If you pass an object to someone else, you may want to make defensive copy first, to protect your own object. (And if you're really lucky, both ends do defensive copying).
* Freezing. Isn't that just a JavaScript thing, and only because they provided it as a language feature? It's a bad API because that is *itself* a change to the object, one that might cause some other code to crash. Also, if half the the API stops working at some point, it's not particularly dependable. Do you need a way to check whether an object has been frozen, and then a way to get a thawed copy to work with?
* Extensive invariant documentation. Every method documents whether it changes an object or not, and whether it requires its arguments to be unchanging. Then users are expected to satisfy that. See also: The first item.

Immutable objects avoid that issue entirely. They can be freely shared. Since Dart has asynchronous functions, which means that unpredictable other code can run *during* a single function code, it's even more important that you can trust your objects to stay they same. 
Immutable objects are often *data* objects, entirely defined by the values you can extract from them.
The issue is then that if you need a *different* object, you need to create a new one. You have less *reuse*, but more security. Efficient generational garbage collection attempts to reduce the cost of creating new objects, but you still need a way to do it.
* Builders. The immutable type has an associated mutable builder type, and you create a builder from the original, mutate the builder, then create a new immutable result from the builder. This separates mutation for use, but costs an extra class.
* replace methods. Like `uri.replace(scheme: "https")`, a way to directly create a new object from the old one, but with some changes applied. This is more functional, less imperative, than the builders.
* No help. Just use a constructor with values extracted from the old object. More verbose, but you can do anything.

The Dart SDK has no real builders. We have plenty of immutable classes (`String`, `DateTime`, `Duration` and `Uri` are some of the most prevalent), and some of them have `update` methods. Well, it's really just `Uri`, but we've considered adding it on `DateTime` and `Duration` as well. It's just a breaking change to modify their API.
A class like `Future` also has an *immutable API*, the API has no way to modify the future. Because of that `Future`s can safely be shared with anybody. It's not a fully immutable class because it has state that changes, but that's not part of the API that you share along with the object.

So, all in all, I think making `DateTime` immutable is a prudent design choice for a language like Dart. We should add a `replace` function to it, though.

**Comment by 89z** [comment]
Thanks for the detailed response.

I dont really have the energy to respond to all those points, but I will add a
little more.

Dart is not the first, or the only language that has asynchronous support. Both
Go (via the `go` keyword), and JavaScript (via `async/await`) have that as well
for just two examples. And in both cases, they offer mutable URL objects.

Freezing isnt just with JavaScript. Python offers two sets of objects as one
approach (`set` and `frozenset`), and Ruby has the `freeze` instance method for
existing objects.
