### ISSUE TITLE
VM service protocol doesn't expose set "elements"

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#44843]
`pkg:vm_service` doesn't appear to treat `Set`s as collections.

For example, when inspecting an object of type `LinkedHashSet` over the VM service protocol, it doesn't have any `elements`. This leads to us treating it as a custom object type, exposing its fields instead of its element. To make matters worse, on the web, set is backed by opaque JavaScript objects which hide the actual contents of the set.

![Screen Shot 2021-02-02 at 17 32 03](https://user-images.githubusercontent.com/1916163/106685612-96305780-657d-11eb-9492-d6ea79a89287.png)

@grouma This was the issue I mentioned today – turns out its an issue with sets, not maps!

@bkonyi Is this intentional – are their any plans to treat sets as first-class collections (like lists and maps)?

**Comment by bkonyi** [comment]
I think this is intentional. `Set` is implemented using other primitives like `List`, so `Set` doesn't have a distinct representation within the VM itself. There's probably a way to check for `Set` when we're reporting instances over the protocol and we could send back a custom response, but I'm not sure how complicated that might be.

cc/ @rmacnak-google to confirm that this behavior is expected.

**Comment by rmacnak-google** [comment]
6ca6400cdc1dc64850a89503e92b99d46ab349fa
