### ISSUE TITLE
[CFE] Normalization is not applied with unsound null checking for constant type literal

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#44857]
Consider the following program:

```dart
typedef F = Never Function(void Function<T extends Never>(T));

void main() {
  const c = F;
  print("Are $c, $F identical?");
  print(identical(c, F));
}
```

With a fresh vm from c88171c8af52aaae166d2fcd0a4f7c75bf6a0a5b, this prints `true` at the end with sound null checking, but `false` with unsound null checking.

The previous statement shows that the difference is normalization. Here is the result with sound null checking followed by the one with unsound null checking:

```
Are (<X0 extends Never>(Never) => void) => Never, (<X0 extends Never>(Never) => void) => Never identical?
Are (<X0 extends Never>(Never) => void) => Never, (<X0 extends Never>(X0) => void) => Never identical?
```

The difference is that `X0` is normalized to `Never` in the value of the type literal `F` in the former case, but not in the latter case.

I believe that the normalization should take place with both kinds of null checking.

**Comment by stefantsov** [comment]
Interestingly enough, the normalization was applied in this case, but what happened is that after normalization in weak mode `CONST_CANONICAL_TYPE` was also applied, and the bug was in the implementation of that function.  It modified its input under certain conditions, so running it twice on the same object produced different results.  Removing the side effect solved the issue.

The proposed solution is here: https://dart-review.googlesource.com/c/sdk/+/182781.
