### ISSUE TITLE
[Feature request] Optionally accept capitalized versions of lowercase types for logical consistency (ex. Int,Double, and Bool)

### ISSUE THREAD

**Issue by ikeofkc** [dart-lang/sdk#44863]
It seems that Dart has made some types use lower case for familiarity for a few users, but at the cost of inconsistency for all users. Having lower case types for just a few makes it seem as if there are primitive types, which there are not.

Since types should be capitalized in Dart, I would propose that *in addition* to int, bool, and double, Dart would also accept Int, Bool, and Double (and any type examples not listed here). 

This would allow users who value consistency to enjoy using Dart, new users to quickly understand the type system, and more experienced users to find the syntax consistent instead of clunky.

**Comment by ikeofkc** [comment]
Thanks for pointing me to [dart-lang/language#65](https://github.com/dart-lang/language/issues/65). It's definitely not what I had in mind, and in my mind, doesn't have the benefits to helping new users being able to learn a type method with logic based consistency (the variances aren't based the qualities of the objects, but arbitrary exceptions). That being said, for projects that I don't expect others need to see, I may utilize this. So thank you.

**Comment by tatumizer** [comment]
From wikipedia:
In computer science, primitive data type is either of the following:[citation needed]

- a basic type is a data type provided by a programming language as a basic building block. Most languages allow more complicated composite types to be recursively constructed starting from basic types.
- a built-in type is a data type for which the programming language provides built-in support.

@ikeofkc: in your opinion, which of these definitions is NOT satisfied by dart's primitive types which you declare not-really-primitive?

**Comment by lrhn** [comment]
Both are valiant attempts to define *something*, neither use is what I (or [Java](https://en.wikibooks.org/wiki/Java_Programming/Primitive_Types)) mean by those words.

* For the "basic building block", that's ... a tricky definition. Is it any object which doesn't *contain* a reference to another object?
(And what does that even mean? Because `null.hashCode` is a getter returning an `int`, so does `null` contain that `int` or not? Isn't that an implementation detail?)
That *would* probably include the types `Null`, `int`, `double`, `String`, `Symbol`, and `Type`, which are what I'd call "platform types". It would also include `Object` because the `Object` class is instantiable and vacuously does not depend on other objects, but `Object` is not what you'd normally call a "primitive" type. The types `dynamic` and `void` can be counted or not, I'd probably not count them. They're not not "building blocks" for other types, they're tools for certain use-cases.

* With "the programming language provides built-in support", that would include any type where the language provides special "support" above what other types can define for themselves. For Dart, I'd say that's anything with special language rules (`dynamic`, `void`) or a literal syntax (`Null`, `int`, `double`, `num`, `bool`, `String`, `Symbol`, `Type`, `List`, `Set`, and `Map`), plus `Future` and `Stream` because of `async` programming. And maybe `Error` because throwing an error sets its stack trace. And maybe all enum types, because the language special-cases them in switch cases. Probably not enums - if every type is special, no type is.

With the Java definition, Dart doesn't have primitive (non-`Object`) types.
With either of these two Wikipedia definitions, Dart probably has some primitive types, but it's not restricted to lower-cased types, or necessarily include all lower-case types.

Personally, I prefer to use "platform type" for any type actually mentioned in the language specification, or which cannot be implemented in pure Dart (like `Uint8List`, at least not efficiently). Types which only works because of integration with the underlying platform. It's still a fluent concept, not a strict definition.

**Comment by tatumizer** [comment]
My intuition of primitive types suggests that primitive types are those natively supported by the typical processor. They are int (several bit sizes -  in dart we have only one size), double, bool (in a sense), and reference. The first 3 are all lower case in dart, and if we had a low-level concept of reference, it would also be a lower-case identifier (`ref` or something). There's also a 32-bit floating-point number, but dart doesn't support it either, or else I'm pretty sure it would be called `float`.
My intuition also tells me that String is not a primitive type, regardless of hardware support (I don't know if any processor today supports it, maybe IBM for historical reasons - it's difficult even to define a common format for Strings). Some processors used to support decimal numbers, and if such support was common, I'm pretty sure we would have a lowercase `decimal` type). 
I admit I spent most of my career (whatever that means) as a low-level programmer, hence may have personal bias.

**Comment by leafpetersen** [comment]
@lrhn do we plan to do anything here as part of the non-function type alias release?

**Comment by lrhn** [comment]
I personally don't want to add aliases for `int`, `double` and `bool`. I see no advantage in having two different ways to write the same plain type.
Yes, it's inconsistent. Adding `Int` won't remove `int` (we're not planning on removing the lower-cased types anyway), so we're just inviting code to be inconsistent in a different way.

I vote no to adding this to the platform libraries, even with non-function type aliases.

**Comment by lrhn** [comment]
Not planning on doing this. You can now make your own aliases using `typedef` if you really want to. I recommend not doing that if you want anyone else to help read or maintain your code, though.
