### ISSUE TITLE
Implement the Q1 2021 small features release in DDC

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44915]
Implementation issue for this [set of features](https://github.com/dart-lang/sdk/issues/44911).

cc @sigmundch @franklinyow

**Comment by leafpetersen** [comment]
See [also](https://github.com/dart-lang/sdk/issues/30891).

**Comment by sigmundch** [comment]
Like with dart2js, I expect that metadata support is CFE only and >>> will likely be CFE + runtime libraries only, so we may have no work on the DDC side. I expect we may need to do some backend work to adapt our type representation to accept generic types in new places as proposed by the feature.

@nshahan - do you know if that's supported by our current representation or if more work will be required to support this?

**Comment by nshahan** [comment]
AFAIK we don't have the explicit support yet in the web runtime libraries but talking with @rakudrama today made it sound like it would be a minor change to the patch files based on the existing implementations of the existing shift operators. Not expecting a large amount of work to reach a version that performs well but we need to be aware of performance.

**Comment by leafpetersen** [comment]
@nshahan any updates?

**Comment by nshahan** [comment]
Now that there is an implementation that throws an unimplemented message has landed and we have working tests @lrhn said that he was going to add a real implementation next week. I will followup and make sure we add an implementation soon.

**Comment by sigmundch** [comment]
Thanks for the update @nshahan. Do you know if there is anything left to do for "Generic function types as type arguments"?

**Comment by nshahan** [comment]
> Do you know if there is anything left to do for "Generic function types as type arguments"?
I'm not sure about that. My feeling is the systems might just work but there could be unexpected incompatibilities with the function type argument. 

I just found a set of test suites for the features mentioned in this comment https://github.com/dart-lang/sdk/issues/44926#issuecomment-785709113. I'll use those to validate.

**Comment by nshahan** [comment]
@leafpetersen Do you have an overview of all the tests for the various features? It would be nice to have a query for each of the features we could use to see the status.

I noticed some of the triple shift tests were being skipped because they have been around for so long https://dart-review.googlesource.com/c/sdk/+/191482. Do we have to watch out for this on the other features?

@athomas It looks like we need to roll the co19 tests again as they have been landing some updates (sorry for the noise if you are already aware).

Current DDC test status (that I'm aware of):

**Triple shift operator**
The language suite is passing
* `language/operator/operator_triple_shift_test`

The co19 suite has failures but it looks like there was an update that needs to be rolled into the SDK
* https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LanguageFeatures/nnbd/triple-shift,co19/Language/Expressions/Shift&showAll

**Generic Function Types in type arguments and bounds**
The language suite is failing in the frontend.
* https://dart-ci.firebaseapp.com/current_results/#/filter=language/generic/generic_function_type_argument_test&showAll

Some tests have landed in co19 but have not been rolled into the SDK yet.
* https://github.com/dart-lang/co19/issues/996

**Non-function type alias support in DDC**
I haven't found any runtime tests for the backends in the language suite.

I'm not aware of any failures from the co19 test suite that are on the DDC side, there are a lot of tests scattered in different directories. Some front end only tests are failing.

**Comment by leafpetersen** [comment]
@nshahan I have internal docs and spreadsheets tracking all known tests and failures, I will send you links.

**Comment by franklinyow** [comment]
Any update?

**Comment by leafpetersen** [comment]
I believe this is done.
