### ISSUE TITLE
Allow generic function types as type arguments

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#44930]
Allow generic function types as type arguments per https://github.com/dart-lang/language/issues/496 in the VM

**Comment by a-siva** [comment]
@crelier I presume you are still waiting for the CFE implementation to be completed before you can close this

**Comment by crelier** [comment]
Now that the CFE has provided an implementation behind a flag, I am able to test and I found 2 issues in the VM.
The first one relates to a wrong usage of the trail to avoid infinite recursion. It is easy to fix.
The second one is more complicated and relates to indices assigned by CFE in kernel files to reference declared type parameters. The VM and CFE are not agreeing on this assignment. Since this is not my code, I am still investigating to figure out who is correct and how to fix it. I suspect the issue is on the VM side. Stay tuned.
