### ISSUE TITLE
web eval fails on renamed symbols

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#44933]
@annagrin - I think this is a known issue with remapping, but didn't see an existing bug.

```
> 'hello'.substring(1)
ReferenceError: $substring is not defined
```

**Comment by sigmundch** [comment]
@annagrin - is this also covered by #40273?

**Comment by annagrin** [comment]
@vsmenon @sigmundch this issue seems to be due to a missing symbol definition in JavaScript for the evaluated function. I added a link (above) to the issue that should cover loading and redefining variables for all used libraries, symbols, types, uris, and constants in the synthetic evaluation function. This also will enable `evaluate()` implementation that is needed for flutter's widget inspector. I am working on it currently, for the amd module format only at the moment.

**Comment by sigmundch** [comment]
Thanks for the update, I'll comment on the other bug
