### ISSUE TITLE
Tests depend on experiment flag which is going to be disabled.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44937]
The tests
* `pkg/dartdev/test/commands/test_test.dart`
* `pkg/dartdev/test/analytics_test.dart`

both contains `--enable-experiment=non-nullable` in a test. That feature is now enabled by default, and the flag should not be passed.
However, removing the flag makes the test fail (because it checks something about the generated artifact which depends on the flag being passed).

These tests should either be changed to expect the non-flag behavior, or just be dropped if they are only testing behavior which doesn't happen any more.

Adding @sigurdm since you appear to have written the tests.

**Comment by sigurdm** [comment]
If the flag is removed I guess the test should be dropped.

Only we might want to use other experiments later.

Is there some kind of "dummy-experiment" we could use for testing this?

**Comment by lrhn** [comment]
There is no "example" experiment. Even if there was, it wouldn't change semantics, so it would be impossible to test whether it was enabled or not.

I guess we'll just have to rewrite a new test each time we introduce a new flag. Maybe auto-generate the test from `experimental_options.yaml`.

**Comment by sigurdm** [comment]
Hmm -I see no other choice than removing the tests for now then.

I think auto-generating will be hard when we don't know what semantics to look for.

**Comment by lrhn** [comment]
Maybe we can keep the test as a comment (but document that it's a *template* to use for later tests, because we don't keep *code* as comments!)

**Comment by sigurdm** [comment]
Keeping a TODO/template sounds good for now.

> I think auto-generating will be hard when we don't know what semantics to look for.

I retract that somewhat. If one was willing to put the effort we could include the source of an example program with each experiment in the `experimental_features.yaml`.

That program should have some fixed semantics (output "feature enabled" on stdout if the feature is enabled, fail static checking or output "feature not enabled" if the feature is not enabled).

That would make autogenerating these tests workable, and indeed do so for every active flag.

(I guess that was also what you had in mind - I just did not think that far.)

Now might however not be the time to implement that, since there would be no flags to test the autogenerated flags on.

**Comment by lrhn** [comment]
We're working on two active experiments right now, completion of the "triple-shift" feature and a new "generic-metadata" experiment.

Yes, I was thinking of including some example in the YAML file, one which should throw if the experiment is not enabled. It probably needs to be a complete program, to ensure we can cover all local features, and it still won't be able to test import based features easily.

**Comment by sigurdm** [comment]
> We're working on two active experiments right now,

Nice - then we could surely do it!

I think you are right - a single file program would be good enough for most features. We can always make something more advanced if we later.

**Comment by sigurdm** [comment]
This should be fixed by: https://dart-review.googlesource.com/c/sdk/+/184790
