### ISSUE TITLE
Tests requiring unsound null safety flag.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#44941]
I'm removing references to the "non-nullable" experiment flag from tests. See [CL](https://dart-review.googlesource.com/c/sdk/+/183688/1..4).
Two tests broke when I removed the flag. I made them pass again by using `--no-sound-null-safety` instead.
Those two tests are:
* `tests/lib_2/isolate/issue_6610_test.dart `
* `tests/standalone_2/io/named_pipe_script_test.dart `

Both tests are in `_2/` folders so they are testing legacy behavior. I'm guessing both are related to isolate spawning.

Please check whether the tests are OK as fixed, and that they still test the same thing as before.

**Comment by a-siva** [comment]
With the removal of the "non-nullable" flag the CFE will always sniff the file to automatically detect whether code is running in opted-in mode or opted-out mode. This means all tests that get input from non file sources (e.g: pipes or from a http server) will end up with errors because of the sniffing.

Your changes convert the tests to explicitly provide the 'no-sound-null-safety' option which means auto detection is not needed and hence the tests work. By passing the explicit null safety flag we make these tests identical to the versions in the corresponding 'lib' and 'standalone' directories and it might just be a duplication running them here in this manner, maybe we could just delete these tests when your change goes in.

**Comment by lrhn** [comment]
I'll remove the tests as part of my initial clean-up CL then. That CL doesn't remove the flag, but it removes or changes code that uses it.
