### ISSUE TITLE
Filter deprecated enum values

### ISSUE THREAD

**Issue by bambinoua** [dart-lang/sdk#44970]
I think this is not a bug but suggestion. Let's assume we have an `enum`.
```dart
enum OldEnum {
  none, 
  itemOneFirst
  itemOneSecond,
  itemTwoFirst,
  itemTwoSecond,
  itemThree,
}
```
So indexes are `0,1,2,3,4,5`.
Then they decided to combine items `itemOneX` and `itemsTwoX` to single ones.
```dart
enum NewEnum {
  none,
  itemOne,
  itemTwo,
  @deprecated
  itemOneFirst,
  @deprecated
  itemOneSecond,
  @deprecated
  itemTwoFirst,
  @deprecated
  itemTwoSecond,
  itemThree,
}
```
And indexes are only `0,1,2,5`. Moreover they are already in database.
The problem is when this `newEnum` is used as source for generation of `DropdownButtonFormField` as 
```dart
DropdownButtonFormField(
  items: NewEnum.values.map((item) => DropdownButtonItem(value: item. child: Text(describeEnum(item))));
)
```
it displays items which are should not be visible to user. It would be good to skip `@depreated` items from `values` collection or even create new annotation for this feature.
P.S. Of course, I can create an `extension` which will filter specific items but maybe this feature have a sense?

**Comment by lrhn** [comment]
The `@deprecated` annotation has no effect on the program at run-time, all it does is make the analyzer emit warnings if you use the deprecated feature. It's not wrong (yet) to use it, so you shouldn't be treating deprecated things differently. In general, annotations won't make a difference at run-time (unless you use `dart:mirrors`, which Flutter code can't, to read the annotations).

Your issue here is that you have an enum where not all values are equal. You want to filter `NewEnum.values` for a particular use-case. I don't see any good solution for that with the current `enum` design (where it's not possible to attach more information to a value). I'd simply introduce a function like:
```dart
bool isValueValid(NewEnum v) => v.index <= 2 || v.index >= 5;
```
and then just use `items: NewEnum.values.where(isValueValid).map( ... )`.

If we had the ability to attach more properties to enums, like a Java enum, then we'd have the opportunity to attach an `bool ignoreInDropdown` property that we could latch onto. 

Also, since indices must be consecutive, you won't be able to *remove* the deprecated enum values without changing the index of `itemThree`. Deprecating something that won't actually be removed is a non-standard use of `@deprecated` (but I guess they will be removed *as soon as possible*, which won't be until we provide a way to control the indices of enums.
(Maybe something like;
```dart
enum newEnum {
  none,  // Same as `= 0`
  itemOne, // Same as `= <previous>+ 1`
  itemTwo,
  itemThree = 5, // Go directly to 5.
}
```
That would give *some* amount of control over the one property enums have.)
