### ISSUE TITLE
Should the body of an async* method start synchronously on the call to `.listen`?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#44997]
The body of an `async*` method currently starts in a microtask following the call to `.listen` on the returned stream. This differs from calling `.listen` on the stream returned by a `StreamController` where the `onListen` callback is executed synchronously. I had hoped that the following two approaches to define this method would behave idendically:

```dart
import 'dart:async';

Stream<int> justOne() {
  final c = StreamController<int>();
  c.onListen = () {
    print('On listen');
    c.add(1);
  };
  return c.stream;
}
```

vs

```dart
Stream<int> justOne() async* {
  print('On listen');
  yield 1;
}
```

However they differ. Comparing the output of

```
void main() async {
  justOne().listen(print);
  print('Listened');
}
```

The former produces

```
On listen
Listened
1
```

While the latter produces

```
Listened
On listen
1
```

@lrhn - do you think this would be difficult to change? Do you anticipate it will be very breaking?

**Comment by lrhn** [comment]
Should it be synchronous: [Yes!](https://github.com/dart-lang/sdk/issues/33818)

Difficult to change: Yes. (Don't know how difficult, but it was a large task for @floitschG to make `async` functions start synchronously. The `sync*` functions are less common, and probably less timing bound because they often start out listening to other async code, but it won't be trivial. The current behavior is likely baked into the backend implementations).

Very breaking: Possibly, not certainly. The risk is that a few highly used functions depend on timing, not that the majority of code does so independently. If some core part of Flutter event propagation breaks, it's very breaking even if it only really breaks one function. It's really impossible to say without trying.

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/33818
