### ISSUE TITLE
[Breaking Change Request] [vm/ffi] Disallow WeakHandle and FinalizableHandle on Pointers and Structs

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#45072]
# Summary

Disallow invoking `Dart_NewWeakPersistentHandle` and `Dart_NewFinalizableHandle` in `dart_api.h` with `object` without identity.

This is already already true for integers, `true`, and `false`, but we'd like to extend it to `dart:ffi`'s `Pointer`, and subtypes of `dart:ffi`'s `Struct`.

We also disallow using `Pointer`, and subtypes of `dart:ffi`'s `Struct` in `Expando`s, similar to how numbers, booleans, and `null` are disallowed.

https://github.com/dart-lang/sdk/blob/8f0d5ef07674127151b1729642ea602814ee76eb/runtime/include/dart_api.h#L460-L494

https://github.com/dart-lang/sdk/blob/8f0d5ef07674127151b1729642ea602814ee76eb/runtime/include/dart_api.h#L512-L550

# Motivation

1. We want to be able to optimize `Pointer` and subtypes of `Struct` away completely at runtime.
2. We want to prevent use after free issues with the GC running finalizers on these objects when derived pointers or the pointer's addresses are still in use. (Example in https://github.com/dart-lang/sdk/issues/45071.)

# Impact

We're not aware of any uses of finalizers on `Pointer`s or structs. (If there are any, they might already suffer from use-after-free bugs due to premature finalization.)

# Migration

```dart
void myCode() {
  Pointer<Database> pointer = // ...
  // Pass `pointer` to native code with `dart:ffi` and call `Dart_NewFInalizableHandle` to attach finalizer.
  use(pointer);
}
```

becomes

```dart
class DatabaseResource implements NativeResource {
  final Pointer<Database> _database;

  DatabaseResource(this._database) {
    // Pass `this` and `_database` to native code with `dart:ffi` and call `Dart_NewFInalizableHandle`
    // with `this` as parameter to `object` and `_database` as `peer`.
  }

  void use();
}

void myCode() {
  DatabaseResource database;
  database.use();
}
```

https://dart-review.googlesource.com/c/sdk/+/143804

# Future work

Ensuring that classes implementing this this `NativeResource`/`WeakHandleable` interface are kept alive on all method calls is future work ([design discussion](http://go/dart-ffi-beyond-finalizers)).

**Comment by franklinyow** [comment]
CC: @mit-mit @vsmenon @kevmoo @Hixie @matanlurey

**Comment by matanlurey** [comment]
Not relevant to my work, so no opinion either way.

**Comment by jonasfj** [comment]
Hmm, attaching finalizers to the `Pointer<..>` object is very powerful when you have a C library with referencing.

**Example:** In `package:webcrypto` I create a [`Pointer<EVP_KEY>` then attach a finalizer](https://github.com/google/webcrypto.dart/blob/6dd34605b16097f2845742e04cce1aa4854b07d8/lib/src/impl_ffi/impl_ffi.utils.dart#L29-L37) with [Dart_NewFinalizableHandle_DL](https://github.com/google/webcrypto.dart/blob/6dd34605b16097f2845742e04cce1aa4854b07d8/src/webcrypto_dart_dl.c) and because every function that uses the `EVP_KEY` pointer takes it as an argument and either:
 1. Doesn't hold a reference to it, OR,
 2. Increases a reference count in the C library,

I do not need to insert artificial `use(pkey)` calls all over my code, nor do I need anything like `NativeResource`.

-------

I can certainly see the motivation for this, I just wanted to point out that finalizers on `Pointer` is attractive for use with C libraries that have reference counting. Whether feasible to allow that or not I don't know.

**Comment by Hixie** [comment]
no opinion

**Comment by dcharkes** [comment]
We've added rejecting `Pointer`s and `Struct`s in `Expando`s to this breaking change request.

Ping @mit-mit, @vsmenon, and @kevmoo for approval.

**Comment by franklinyow** [comment]
Ping @mit-mit, @vsmenon, and @kevmoo for approval.

**Comment by leafpetersen** [comment]
I believe this has slipped from this milestone.

**Comment by vsmenon** [comment]
lgtm

**Comment by franklinyow** [comment]
Approved.  Please land after branch cut

**Comment by dcharkes** [comment]
This has landed in https://github.com/dart-lang/sdk/commit/3f0ad61daaac68e591bf01d0a3096926c30c1d42 and will reach stable in 2.14.
