### ISSUE TITLE
NNBD inference problem

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/sdk#45095]
I am having these problems a lot because of the wrong inference:

    List<int?> d = [1, 2, 3].reversed.toList();
    print(d.runtimeType); // <int>, but I'd expect <int?>

Do I really have to write `List<int?> d = <int?>[1, 2, 3].reversed.toList();` ?

**Comment by eernstg** [comment]
Yes, type inference on the receiver (like `[1, 2, 3]`) of a member access (like `[1, 2, 3].reversed`) occurs in the empty context. That is, such receivers don't get to know about what is expected, based on expectations for the enclosing member access expression.

The reason for this is mainly that Dart combines subtyping and type inference, and this means that there are many solutions in many situations. For instance both `<int>[1, 2, 3]` and `<int?>[1, 2, 3]` will work in the given context.

You could use `var d = <int?>[1, 2, 3].reversed.toList();` in order to provide the information just once, where it is needed. In general, you get to control the outcome more tightly if you put the type information in an "earlier" location, that is, on the initializing expression rather than as a declared variable type, on a subexpression rather than at the top level.
