### ISSUE TITLE
Analyzer and VM don't respect generics.

### ISSUE THREAD

**Issue by spnda** [dart-lang/sdk#45096]
I just started porting https://github.com/spnda/dart_minecraft/ to null safety. I ported all of my code to null safety and it seems to work, except for one little culprit. 
Both the dart analyzer and dart compiler report the same issue
Running on `Dart SDK version: 2.13.0-30.0.dev (dev) (Fri Feb 12 04:33:47 2021 -0800) on "windows_x64"`.

This is my class tree:
```dart
abstract class NbtTag {}

abstract class NbtArray<T> extends NbtTag with ListMixin<T> {}

class NbtList<T extends NbtTag> extends NbtArray<T> {}
```
And inside of `NbtList` I have a function, specifically this:
```dart
@override
NbtList readTag(NbtFileReader fileReader, {bool withName = true}) {
  final name = withName ? fileReader.readString() : 'None'; // On the root node, this should be a empty string
  final tagType = fileReader.readByte();
  childrenTagType = NbtTagType.values[tagType];
  final length = fileReader.readInt(signed: true);
  for (var i = 0; i < length; i++) {
    add(NbtTag.readTagForType(fileReader, tagType, this, withName: false));
  }
  return this..name = name;
}
```
The `add` function is from `ListMixin<T>`, which in the tree gets `T` from `<T extends NbtTag>`.
Nevertheless, it still triggers the following error on the `add` invocation.
```
The argument type 'NbtTag' can't be assigned to the parameter type 'T'. dart(argument_type_not_assignable)
```
The previous version was run on Dart 2.10.5 and I suspect that this is a error in the analyzer or Dart VM, as the generics should still be valid.

The issue can be fixed by doing the following, which seems to indicate that it really is just an issue with the analyzer, as the `add` function gets called.
```dart
final tag = NbtTag.readTagForType(fileReader, tagType, this, withName: false);
if (tag != null && tag is T) add(tag);
 ```

**Comment by eernstg** [comment]
You don't show the declaration of `NbtTag.readTagForType`, but if that function returns an `NbtTag?` then `T extends NbtTag` does not help you: It cannot be proven that the returned object has type `T`, it is only known to have type `NbtTag?`.

With null safety, downcasts must be explicit. This means that an expression of type `NbtTag` cannot be used (without a cast) to initialize a variable of type `T`. However, the local variable `tag` is promoted to have a non-nullable type by the test `tag != null`, and it is promoted to have type `T` with `tag is T` (in the locations where those expressions are known to have evaluated to true).

**Comment by eernstg** [comment]
I'll close this issue. It looks like the issue arises because you're migrating the code to null safety (:+1:), but some of the explicit downcasts (or promotions) which are required for code with null safety haven't yet been added.

**Comment by spnda** [comment]
I can agree, though I would still argue that `NbtTag?` means `NbtTag` or `Null`. Meaning that `if (tag != null)` discards the possibility of it being `Null`. Therefore it *has to be* `NbtTag`, or am I wrong?

**Comment by eernstg** [comment]
`NbtTag?` does indeed include all instances of type `NbtTag` as well as null, and `tag` does get promoted to `NbtTag` in the true continuation of the expression `tag != null`. But it doesn't suffice to know that `tag` has type `NbtTag`, because the `add` method parameter has type `T`, and we only know `T <: NbtTag`.

But the reason why you need to have an explicit downcast or promotion from `NbtTag` to `T` is that a downcast can't be implicit any more, and that's a change from pre-null-safety Dart to null-safety Dart.

(You could require downcasts to be made explicit in older versions of Dart in several ways, including passing option `--no-implicit-casts` to the analyzer, but if you were using the Dart tools with no special options or configuration files to do this, implicit downcasts were allowed.)
