### ISSUE TITLE
Listening to a `stdin.asBroadcastStream()` causes the process to never terminate in the VM

### ISSUE THREAD

**Issue by jiahaog** [dart-lang/sdk#45098]
When `stdin` is used as a broadcast stream, the process never terminates even after `main` has completed. Repro (on the VM with `dart bin/$file`):

```dart
import 'dart:io';

void main(List<String> arguments) async {
  // Using an alternate stream source works fine.
  // final stream = Completer().future.asStream();
  final stream = stdin;

  // If [asBroadcastStream] is omitted the problem goes
  // away.
  final sub = stream.asBroadcastStream().listen(null);
  await sub.cancel();

  // This is printed but the process never terminates.
  print('done');
}
```

Dart version:

```
Dart SDK version: 2.13.0-38.0.dev (dev) (Mon Feb 15 10:21:50 2021 -0800) on "macos_x64"
```

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
Don't do that then. 😉 

This is expected behavior. By making `stdin` a broadcast stream, you listen to `stdin` (in order to forward the events to any broadcast stream listeners) *and you never stop listening again*.
Since stdin can potentially provide events forever, the program is not done, even if noone is currently listening to the broadcasts stream (the system cannot see that, they just see a code receiving stdin events and doing *something* with them, which here is putting them into a broadcasts stream controller with no listeners).

The only way to terminate an `asBroadcastStream()` call is to wait for the stream itself to end (stdin won't unless the user closes it) or pass an argument to `asBroadcastStream`:
```dart
bool keepAlive = true;
var broadcastStream = stream.asBroadcastStream();
final sub = broadcastStream.listen(onCancel: (c) {
  // Broadcast stream has no listeners.
  if (!keepAlive) c.cancel();
});
```
Then you can later do `keepAlive = false; broadcastStream.listen(null).cancel();` (the latter part to trigger a run of `onCancel` if there are no current listeners). That will cancel the broadcast stream's subscription on stdin, either there, or when the last real subscription goes away.
