### ISSUE TITLE
Analyzer does not cast auto nullable field to not nullable not working

### ISSUE THREAD

**Issue by bitsydarel** [dart-lang/sdk#45225]
Analyzer does not cast auto nullable field to not nullable even if that field is final and has a value assigned and is inside of a null check.

So the compiler should be confident that this value is not null.

the following code does not compile but should.

```dart
class Y {
  final X x;
  
  Y(this.x);
  
  String test() {
    if (x.x != null) {
      final Z z = Z(x.x);
      
      return z.z;
    } else {
      return '';
    }
  }
}


class X {
  final String? x;
  
  X(this.x);
}

class Z {
  final String z;
  
  Z(this.z);
}
```

This tracker is for issues related to:

* Analyzer

* Dart SDK Version (`dart --version`)
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (2 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by mraleph** [comment]
As explained [here](https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields) field types are not promoted because they can be override somewhere else in the program with a getter which returns a different value every time it is called, e.g.

```dart
class EvilX implements X {
  @override
  String? get x => random.nextBool() ? 'ok' : null;
}
```

There is a [number of issues](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion) on the language repo which explore possible solution for this issue in the future. 

Future versions of analyzer would also provide more explicit "why not promoted" information.
