### ISSUE TITLE
[analyzer] ignore: unsafe_html does not work

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#45230]
## Description

This screenshot should explain it :)

![image](https://user-images.githubusercontent.com/19204050/110221639-3a7f2400-7ec5-11eb-8fdb-43e35d209316.png)

Essentially, even though I am inserting an `ignore: unsafe_html` comment, the analyzer reports an `info`-level lint anyway:

```
Analyzing wakelock_web...

   info - Avoid unsafe HTML APIs (assigning "src" attribute) - lib\src\import_js_library.dart:35:5 - unsafe_html

1 issue found. (ran in 1.3s)
```

If the setup is important, check https://github.com/creativecreatorormaybenot/wakelock/blob/b8b2f13cfedc5544c0311bf5172712a97b7ce5fc/wakelock_web/lib/src/import_js_library.dart#L34 for the full source code.

---

```
Tools • Dart 2.12.0
```

**Comment by gmpassos** [comment]
Same problem here!

**Comment by srawlins** [comment]
Currently, analyzer does not allow ignoring any "security" codes, such as `unsafe_html`. As this fact is probably super surprising and undiscoverable, there should be a new diagnostic indicating this idea.

**Comment by creativecreatorormaybenot** [comment]
@srawlins More than that, I feel like there is no alternative in this case. That is I need to ignore it because there is no other way to achieve what I am trying to do.

Though I of course generally want to keep the analyzer rule (especially because it is super broad).

**Comment by srawlins** [comment]
@bwilkerson @pq What do you think about a new diagnostic for these un-ignorable codes? Something like:

```dart
// ignore: unsafe_html
div.innerHtml = 'x';
```

reports:

> "Security lints cannot be ignored inline with a comment."

> Correction: "Try ignoring the rule in analysis_options.yaml"

**Comment by bwilkerson** [comment]
I think that a better solution would be to make the security rules ignorable again and to introduce a more general solution for users that want to make a diagnostic un-ignorable (implemented in the opposite order). For example, I could imagine enhancing the analysis options file to allow a diagnostic to be marked as un-ignorable. Perhaps something like
```
analyzer:
  errors:
    unsafe_html: error, cannotIgnore
```
or
```
analyzer:
  cannotIgnore:
  - unsafe_html
```

**Comment by srawlins** [comment]
If a rule is un-ignorable, via `cannotIgnore`, how does the user know this while trying to ignore something with `// ignore:`? I would tear my hair out thinking I've misspelt my error code.

**Comment by gmpassos** [comment]
Any rule in the code (in the format `// ignore: xyz`) should be respected, since this exists for many situations.

The reported bug is for an analyzer warning that ignores its own `ignore` rule.

An extra feature to ignore some rule for the whole project could be interesting too, but is not a substitute.

**Comment by srawlins** [comment]
@gmpassos the issue to follow for that discussion is https://github.com/dart-lang/sdk/issues/44237.

**Comment by bwilkerson** [comment]
> If a rule is un-ignorable, via cannotIgnore, how does the user know this ...

I expect the situation will arise far less often because the user is more likely to know what is and isn't allowed in their own code base.

But I agree that a diagnostic would be good in that situation. I just think we should clean up the way un-ignorable diagnostics are implemented first as it will impact the messaging.

I'll just note that we already have support for this diagnostic, but it's currently disabled because of a conflict in Flutter. We have agreement to clean up the issues in Flutter, but haven't had time. (See the discussion on https://github.com/dart-lang/sdk/issues/35234.)

**Comment by gmpassos** [comment]
One question: Why we can't set an image `src`? Why this is a security issue, since this is a normal operation for any web development?

**Comment by insinfo** [comment]
I have this same doubt

> One question: Why we can't set an image src? Why this is a security issue, since this is a normal operation for any web development?
