### ISSUE TITLE
Migrate to null safety.

### ISSUE THREAD

**Issue by mrdemqn** [dart-lang/sdk#45264]
While performing the following command "dart pub outdated --mode=null-safety" the following message appears "Package doesn't exist (the Flutter SDK is not available)."

**Comment by srawlins** [comment]
I'm not certain of the root cause of this bug, but you should be able to skip the `dart pub outdated` step with: `dart migrate --skip-import-check`.

**Comment by KUMAR20001** [comment]
Check on your internet connection speed because the cammand "dart pub" is not recognised in the flutter SDK and try to reinstall the SDK with specifying correct path in SDK manager which will automatically run this "dart pub outdated --mode=null-safety" by downloading and installing  " pub get " from the excecuting terminal

**Comment by srawlins** [comment]
I was under the impression, from the original bug report, that you were running the `dart migrate` command. If you are instead just running `dart pub outdated`, I will send this bug over to the "pub" team.

**Comment by srawlins** [comment]
Ah, however, if you were running the `dart migrate` command, and that command instructed you to run `dart pub outdated`, then once again, this is a bug for the `dart migrate` command. :) very confusing.

**Comment by srawlins** [comment]
Closing as stale.
