### ISSUE TITLE
VM Service CpuSamples.timespan is documented as being integer, but returns decimal numbers

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#45276]
From here:

https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#cpusample

```
  // The timespan the set of returned samples covers, in microseconds.
  int timeSpan;
```

However when I call it, I see values like `0.843768`:

<img width="462" alt="Screenshot 2021-03-10 at 14 11 14" src="https://user-images.githubusercontent.com/1078012/110641993-7dcde100-81aa-11eb-9e9f-8ce24522a7ed.png">

I called it using `package:vm_service` and dumped the `.json` field from the result.

@bkonyi I'm not sure if it's the docs that are wrong here, although I also noticed the casing is different (spec has a capital `S` in `timeSpan`).

**Comment by bkonyi** [comment]
Oh, good catch! There's a lot wrong here actually... The spec also states that `timeSpan` should be in microseconds, but we're reporting in seconds instead. We also would have been always reporting `-1` for `timeSpan` from `package:vm_service` since `timeSpan` would never be present in the JSON response.
