### ISSUE TITLE
Code snippet in fold docs causes type issue in 2.12

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#45273]
The API docs for iterable has an example of using fold:

https://api.dart.dev/stable/2.12.0/dart-core/Iterable/fold.html

```dart
void main() {
  [1, 2, 3].fold(0, (prev, element) => prev + element);
}
```

=>

```
  error • The operator '+' can't be unconditionally invoked because the receiver can be 'null' at bin/foo.dart:2:40 • (unchecked_use_of_nullable_value)
          Try adding a null check to the target ('!').

```

A few issues

1. Is there something we can do to improve inference here?
1. It would be nice if the example was updated to not trigger this type issue
1. The error message is confusing, adding a bang operator just leads to a new issue:

```
  error • The operator '+' isn't defined for the type 'Object' at bin/foo.dart:2:46 • (undefined_operator)
          Try defining the operator '+'.
```

**Comment by lrhn** [comment]
Ad 1. - That's hard. The one thing that would help is to have cross-argument inference. The first argument (`0`) would suggest that the type argument should be `int`. The second argument, the function, provides no hint (but `int` will work for its body.

Ad 2. - We can use `reduce` instead of `fold`, it takes its types from the list, and doesn't have an extra unconstrained type.

Ad 3. - Agree, we should only recommend adding `!` if that will actually make the code valid, otherwise it should just be a case of "no `+` defined for the type". (Declaring an extension `+` operator makes the problem go away, even if the type is still nullable, so being nullable is not the real issue).

**Comment by leafpetersen** [comment]
[This](https://github.com/dart-lang/language/issues/731) is the language request.  I think we should consider doing a type inference improvement update release in the next year or two.

**Comment by mit-mit** [comment]
@lrhn can we get the sample code fixed to be code that works with null safety?

**Comment by lrhn** [comment]
The code has been fixed by the general example addition and update. Yey!
