### ISSUE TITLE
Add efficient .entries property to SplayTreeMap

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#45296]
The SplayTreeMap implementation at sdk/lib/collection/splay_tree.dart
has custom efficient implementations of the .keys and .values properties.

The similar efficient implementation of the .entries property should be added.
Then many algorithms and methods could be improved to avoid looking up a value from a key while scanning
the map.
Currently, the implementation of .entries comes from the MapMixin, which looks up each value from the key.

In fact, many methods in MapMixin could efficiently use .entries rather than .keys to avoid a lookup.

Also, the implementation of .keys does not have an efficient .contains method, which it should have - this can also be added.

**Comment by whesse** [comment]
On the other hand, because .entries constructs MapEntry objects, it won't be totally fast either, so MapMixin should not necessarily use it instead of iterating over keys.

**Comment by lrhn** [comment]
If we can use the internal nodes as `MapEntry` objects as well, then we don't need to create new ones while iterating.
If we don't want an expose visible entry to change later, we might need to replace the node on a value change, instead of just changing the value field of the node. It's going to be the root node at the time, so that's probably fine (possibly even preferable to avoid old-space objects pointing to new-space values).

**Comment by lrhn** [comment]
Fixed.
