### ISSUE TITLE
[dart migrate] Can't disable a directory with interactive html tool

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/sdk#45326]
I'm using dart migrate, and am inside the HTML suggestions page. According to the [docs](https://dart.dev/null-safety/migration-guide), you can disable a package with the checkbox, but it's not working.
_". To opt out a file or directory, click its green checkbox"_

I can disable individual files, but not an entire folder, I get this error:
```
Uncaught TypeError: Cannot read property 'querySelector' of null
    at Object.hl (flutter-app?authToken=GvgdqvwceKs%3D:3464)
    at Object.hl (flutter-app?authToken=GvgdqvwceKs%3D:3465)
    at TD.$1 (flutter-app?authToken=GvgdqvwceKs%3D:7015)
    at vN.$1 (flutter-app?authToken=GvgdqvwceKs%3D:6407)
    at ft (flutter-app?authToken=GvgdqvwceKs%3D:388)
    at HTMLSpanElement.<anonymous> (flutter-app?authToken=GvgdqvwceKs%3D:396)
 ```
 
![image](https://user-images.githubusercontent.com/736973/111202332-5b144180-8589-11eb-81f3-aa571c14b9a7.png)

**Comment by stereotype441** [comment]
I spent some time manually de-obfuscating the stack trace.  Here's the code in question, from `pkg/nnbd_migration/lib/src/front_end/web/migration.dart`:
```dart
void updateSubtreeIcons(Element element, NavigationTreeDirectoryNode entity) {
  for (var child in entity.subtree) {
    var childNode = element.querySelector('[data-name*="${child.path}"]'); // (1)
    if (child is NavigationTreeDirectoryNode) {
      updateSubtreeIcons(childNode, child); // (2)
      var childIcon = childNode.querySelector(':scope > .status-icon');
      updateIconsForNode(childIcon, entity);
    } else {
      var childIcon = (childNode.parentNode as Element)
          .querySelector(':scope > .status-icon');
      updateIconsForNode(childIcon, child);
    }
  }
}
```
The top stack entry is at (1) and the next stack entry is at (2).  The third stack entry is here (inside the method `writeNavigationSubtree`):
```dart
        statusIcon.onClick.listen((MouseEvent event) {
          toggleDirectoryMigrationStatus(entity);
          updateSubtreeIcons(li, entity); // (3)
          updateIconsForNode(statusIcon, entity);
          updateParentIcons(li, entity);
        });
```
So I think what has happened is that when the user clicked on the status icon, `updateSubtreeIcons` tried to use `element.querySelector('[data-name*="${child.path}"]')` to read the `childNode`, and got back `null`.  Since the child was a `NavigationTreeDirectoryNode`, it made a recursive call to itself (passing `null` for `element`), and that in turn caused the null reference exception at (1).

So why did the call to `element.querySelector` return `null`?  I'm guessing the problem is that since @esDotDev is using Windows (I can tell from the `C:` in their screenshot), the string passed to `querySelector` contained backslashes.  Backslashes passed to `querySelector` need to be escaped (see https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#escaping_special_characters).

I'm working on a fix now.
