### ISSUE TITLE
Bound checking errors in small features

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#45334]
These tests fail due to discrepancies wrt. bound checking:
```
language/generic/generic_function_type_argument_test
co19/Language/Generics/Superbounded_types/typedef3_A01_t06/01
co19/Language/Generics/Superbounded_types/typedef3_A01_t06/02
co19/Language/Generics/typedef_A06_t04
co19/Language/Generics/typedef_A06_t12
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l1_t03
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l1_t04
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l4_t01
co19/LanguageFeatures/regression/34560_t02
```

**Comment by leafpetersen** [comment]
Sorry, @stefantsov I'm not sure I totally parsed which of your examples were problems with tests and which were CFE issues.

**Comment by stefantsov** [comment]
@leafpetersen I think all four are issues with tests, and in the first one in the list a compile-time error is expected in the test, but I believe that it's not an error. Sorry for not being clear.

**Comment by stefantsov** [comment]
cc @eernstg

**Comment by stefantsov** [comment]
* Also, I think the test `co19/Language/Generics/typedef_A06_t04` should be corrected too. The right-hand side of the typedef there is a regular-bounded type (it's not even an application of a generic type to type arguments), and all parts of it are well-bounded.

**Comment by eernstg** [comment]
Taking a look, I can't verify two of the issues, but I agree on the remaining two:

- Agree: `co19/Language/Generics/Superbounded_types/typedef3_A01_t06/02` is not a compile-time error, `B<A<A<A<B<A<dynamic>>>>>>` is super-bounded.
- Can't verify the problem with `co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l1_t03`, it has no failures according to https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l1_t03&showAll
- Agree: `co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l4_t01` does look like it's just the location associated with the error message that differs for the CFE.
- Can't verify the problem with `co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l4_t01`.

So maybe the 2nd and 4th issue have been fixed in a roll already?

**Comment by stefantsov** [comment]
I filed a co19 issue for the three tests that we agree should be updated: https://github.com/dart-lang/co19/issues/1029.

**Comment by stefantsov** [comment]
Some of the remaining test failures are being worked on here: https://dart-review.googlesource.com/c/sdk/+/192146.

**Comment by eernstg** [comment]
About `co19/Language/Generics/typedef_A06_t04`: The front end does not report the error about the raw bound, but this is covered by https://github.com/dart-lang/sdk/issues/42435.

**Comment by stefantsov** [comment]
I have a status update for the remaining tests that are currently failing if run locally at the HEAD fo Dart SDK:

* co19/Language/Generics/Superbounded_types/typedef3_A01_t06/02 — still marked as compile-time error, but shouldn't be; the test should be updated;
* co19/Language/Generics/typedef_A06_t04 — the fix is in work at https://dart-review.googlesource.com/c/sdk/+/193662;
* co19/Language/Generics/typedef_A06_t12 — the fix is in work at https://dart-review.googlesource.com/c/sdk/+/193662;
* co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_l1_t04 — still a failure because of the error locations; the locations should be updated in the test.

So, after https://dart-review.googlesource.com/c/sdk/+/193662 lands, the issue for the CFE may be closed.

**Comment by stefantsov** [comment]
https://dart-review.googlesource.com/c/sdk/+/193662 landed. I'm closing the issue. Please reopen if needed.
