### ISSUE TITLE
Switch VM to use new encoding of invocations in kernel AST

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#45340]
CFE introduced a new encoding of invocations in https://dart-review.googlesource.com/c/sdk/+/175480.
We should support new nodes in the VM and flip `supportsNewMethodInvocationEncoding` in `VmTarget`.

@a-siva @askeksa-google @johnniwinther

**Comment by a-siva** [comment]
Is this something we want to get done for the March milestone ?

**Comment by johnniwinther** [comment]
There is no rush.

**Comment by askeksa-google** [comment]
Porting everything at once is a big lump of code; we should consider how we can do this somewhat incrementally.

We can at least split it up like this:
1. Add support in the VM kernel parser and in all transformations used in JIT. Flip the flag for JIT.
2. Add support in all AOT-specific transformations. Flip the flag for AOT.
3. Remove support for the old encoding in transformations and VM (can be subdivided arbitrarily).
4. Gradually take advantage of the extra (and more explicit) information in the new encoding to simplify the VM code and improve optimizations.

It would be good if we could subdivide the first two points more, especially since flipping the flag will affect all kernel transformations, not just the ones in the SDK. Some options could be:
- Add a separate testing mode for the new encoding, so we can incrementally work on supporting that while running the old one.
- Make a kernel transformer from the new to the old encoding and move that gradually through the pipeline as we port more and more transformations.

As for step 4 above, we should consider redesigning some of the flow graph nodes to match the new encoding better. Many of the distinctions that are implicit in the old encoding and explicit in the new one (dynamic vs. non-dynamic calls, getter calls vs. tearoffs, implicit null check on == etc.) are currently deeply implicit in the VM. To take full advantage of the new encoding, we should make these explicit in the VM's internal structures as well.

**Comment by alexmarkov** [comment]
Currently we cannot set front-end `Target` flags depending on the JIT/AOT mode, because we support 2-step kernel generation, where the first step is the front-end generating a kernel which could be used both in JIT and AOT. So distinguishing JIT from AOT and wiring this up is rather complex. It's much easier to do 1 and 2 in one step. Supporting incremental migration with a separate transformation from new to old encoding also looks like a lot of unnecessary extra work.

I think we should support new invocation encoding both in the VM kernel binary reader/flow graph builder and VM-specific kernel AST transformations (both AOT and modular) altogether and flip the flag in one go. That doesn't look too hard to me, and I would be happy to do this after I'm finished with my current tasks. We might need to enable/disable the flag multiple times if there are any problems with new encoding, so we'll keep support for old encoding for a while. Then, as a separate step we can cleanup support for the old encoding.
