### ISSUE TITLE
[vm/ffi] Point.fromFunction supports function type static field

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/sdk#45358]
# Background

When interacting with C APIs, we always construct a wrapper Dart class, which accepts some callback. But the compiler complains:

> Error: fromFunction expects a static function as parameter. dart:ffi only supports calling static Dart functions from native code.
> Pointer.fromFunction(SampleExecutor._executeFunc)) {
> --------------------------------------^
```dart
typedef Cronet_Executor_ExecuteFunc_Dart = void Function(
  Pointer<Cronet_Executor>,
  Pointer<Cronet_Runnable>,
);

class SampleExecutor {
  final Pointer<Cronet_Executor> executorPtr;

  SampleExecutor()
      : executorPtr = _croNet.Cronet_Executor_CreateWith(
            Pointer.fromFunction(SampleExecutor._executeFunc));

  static final Cronet_Executor_ExecuteFunc_Dart _executeFunc = (executorPtr, runnablePtr) {};
}
```

# Reproduce

```dart
import 'dart:ffi';

typedef VoidCallback_Native = Void Function();
typedef VoidCallback_Dart = void Function();

void foo() {}

final VoidCallback_Dart bar = () {};

void main() {
  Pointer<NativeFunction<VoidCallback_Native>> fooPtr = Pointer.fromFunction(foo);
  print('fooPtr $fooPtr');

  // Won't compile
  // Pointer<NativeFunction<VoidCallback_Native>> barPtr = Pointer.fromFunction(bar);
  // print('barPtr $barPtr');
}
```

**Comment by mraleph** [comment]
This is intentional, similar to how in C++ you can't take `std::function<>` and make a function pointer out of it. There are multiple reasons why this is complicated: a) closures can have captured context and b) we need to generate trampoline that jumps into the given closure. 

We could just throw a runtime error and have trampolines generated for all closures without state that are potentially callable through FFI - but this would certainly have a negative impact on the code size. 

So we opted for a simpler and more predictable approach for now - only allow compile time constants for `Pointer.fromFunction` argument.

**Comment by Sunbreak** [comment]
Got it. Should we close it or leave as it is?

**Comment by mraleph** [comment]
Maybe we should at least change an error message to make it clear _why_ it is an error.
