### ISSUE TITLE
Bug: Type inference of List parameter in method with restricted type parameter resulting in analysis error

### ISSUE THREAD

**Issue by Abion47** [dart-lang/sdk#45400]
I'm creating this issue in response to a [question that was asked today on StackOverflow](https://stackoverflow.com/q/66725731/1255873).

As of Dart 2.12.0, the following code results in a static type error:

```dart
void main() {
  final nums = [1, 2.0, 3.5];
  final ints = [1, 2, 3];
  final doubles = [1.1, 2.2, 3.3];
  
  sums(nums);
  sums(ints);
  sums(doubles);
}

void sums<T extends num>(List<T> list) {
  T res = list[0];

  for (var i = 1; i < list.length; i++) {
    res = res + list[i];
  }

  print(res);
}
```

```none
main.dart:15:15: Error: A value of type 'num' can't be assigned to a variable of type 'T'.
    res = res + list[i];
              ^
```

The same code when run in Dart 2.10.5 compiles successfully and prints the following:

```none
6.5
6
6.6
```

When the `sums` method is altered to include the suggested fix, the error goes away in Dart 2.12.0:

```dart
void sums<T extends num>(List<T> list) {
  T res = list[0];

  for (var i = 1; i < list.length; i++) {
    res = res + list[i] as T;
  }

  print(res);
}
```

But when it is changed to use an addition-assignment operator, the error persists regardless of the cast. However, the static analysis error is hidden in the IDE (VS Code, DartPad) by a warning that suggests the cast is unnecessary:

```dart
void sums<T extends num>(List<T> list) {
  T res = list[0];

  for (var i = 1; i < list.length; i++) {
    res += list[i] as T; // IDE warning, error on `dart analyze` or on compile
  }

  print(res);
}
```

Both of these amended versions run flawlessly in Dart 2.10.5, with or without the cast.

This behavior has been confirmed on Mac OS 11.2.3 in VS Code (Dart extension 3.20.1) as well as the null-safety version of DartPad in Chrome.

**Comment by lrhn** [comment]
The difference is that `res = res + list[i] as T;` means `res = (res + list[i]) as T;`, whereas `res += list[i] as T;` means `res = res + (list[i] as T);`. The latter cast is unnecessary since `list[i]` already has type `T`.

The error comes from `res` having type `T extends num`, so all we know about `res + something` is that it returns `num` (that's what `num.operator+` does, and all we know about `T` is that it implements `num`).
However, `num` is not assignable to `T extends num` without an implicit or explicit downcast, and Null Safety removed the implicit downcast. So, you need to cast the result.

Dart has added some *special cases* to the typing of `int.+`, and similar operators, to avoid errors like this in cases where you're just doing integer arithmetic. Those special cases do not extend to `T extends num`.
