### ISSUE TITLE
[List.from patch] wouldn't it make sense to handle lists differently here?

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#45402]
Hello,

https://github.com/dart-lang/sdk/blob/64a8d2a8b8b85a6e3221ebbc80f36a7746045b4e/sdk/lib/_internal/vm/lib/array_patch.dart#L32-L45

It is common to use List.from to clone lists. 
Wouldn't it make sense to also check if the incoming `elements` Iterable is a List, to then switch to something like what can be found in the List.filled body i.e.

```dart
final _elements = elements;
if (_elements is List) {
  final _length = _elements.length;
  final _result = growable ? new _GrowableList(_length) : new _List(_length);
  for (int i = 0; i < _length; i++) {
    _result[i] = _elements[i];
  }
  return _result;
}
```

**Comment by lrhn** [comment]
> It is common to use List.from to clone lists.

Sadly, yes. These days I'd recommend `list.toList()` or `[... list]`, or even `List.of` when the types match.

We *could* detect an incoming list as well, and add more code to handle that special case.
It would be one extra type check, which would sometimes be unnecessary, and in other cases might give a more efficient operation.
The tradeoff consideration is then whether the extra check is worth it *on average*. 

I'd currently recommend never using `List.from` unless you need to do a cast on each element. That should be rare, and even there you can do `list.cast<T>().toList()` or `[for (var v in list) v as T]`, or even `<T>[... list as List<dynamic>]`, instead.

Reading the length once would be slightly unsafe (if the list changes length while iterating, which no sound and sane list should), but no more than what we do in other places.

So, slight overhead and larger code size vs. a potentially faster copying in some cases, but for a function which has been superseded by more modern language features. 

The proposed code doesn't work with null safety. The result lists must be `_GrowableList<E>` or `_List<E>`, and we can't create those uninitialized if `E` is non-nullable. It would be something like;
```dart
if (elements is List<dynamic>) {
  var length = elements.length;
  if (length == 0) return List<E>.empty(growable: growable);
  var result = List<E>.filled(length, elements[0], growable: growable);
  for (var i = 1; i < length; i++) result[i] = elements[i];
  return result;
}
```

I'm not sure it's worth it (but can be convinced otherwise).

**Comment by rakudrama** [comment]
Do you have a scenario where you have measured poor performance for the `for`-loop you suggest improving?

`List.of` is preferred over `List.from` _if you can use it_ because it is nicer to use and is more efficient. It is nicer to use because the static types are more constrained so work better with type inference, and it is more efficient because the types ensure that the elements can be assigned into the new list without _checking the type of each element_. You can see that `List.from` has a test to call `List.of` if possible.

The `for (E e in elements)` is doing the per-element `as E` check. The code you suggest (and Lasse!) does not has an `as E` check.

`List.of` contains a fast path for copying from the system List implementations. See e.g. [here](https://github.com/dart-lang/sdk/blob/64a8d2a8b8b85a6e3221ebbc80f36a7746045b4e/sdk/lib/_internal/vm/lib/array_patch.dart#L50) and [here](https://github.com/dart-lang/sdk/blob/64a8d2a8b8b85a6e3221ebbc80f36a7746045b4e/sdk/lib/_internal/vm/lib/array.dart#L45). In total there are 5 loops to handle the different shapes of the inputs.

For `List.from`, where the input is _not_ handled by `List.of`, it is possible to do something like what was done for `List.of`.
The benefit would not be as great, since the per-element check is still necessary, and as Lasse mentions, there is a cost to having extra checks along the path, especially if you don't end up in the optimized code, or the lists are too small to accumulate a benefit.

Many uses of `List.from` can be replaced with `List.of`. For those that can't, an improvement might be something worth doing, but we try to avoid adding code to the core libraries that ship with every app unless the extra code pays its way. Except for the hottest ~5% of the code, it is usually a better bet to optimize for app size than run time.

**Comment by modulovalue** [comment]
> Do you have a scenario where you have measured poor performance for the for-loop you suggest improving?

I have not, I was just curious if my intuition is correct here.

Thank you to both of you. You have mentioned some implicit parts that I haven't considered before. An I see now why this suggestion is not worth the effort.
