### ISSUE TITLE
What is the Rationale behind Null Safety Since Dart already has Optionals

### ISSUE THREAD

**Issue by hashweather** [dart-lang/sdk#45409]
Dart already has this thing called Optionals. For example

```
void screenNavigator(BuildContext context, Screen screen,
      [StreamedResponse extraData]) {


}

```
From the above function, extraData is an Optional Argument.

Why then is the need of including nulls into the language?

**Comment by eernstg** [comment]
Big question. Here's a tiny answer: Null safety is the ability of the static analysis to make a distinction between null and other objects. Pre-null-safety code would allow a variable with type `String` to have the value null as well as any string; with null safety a variable of type `String` can refer to any string, but it can't be null. All the changes related to null safety were included because they helped keeping track of those nulls at compile-time, and thus ensuring that no null errors occur at run-time, except for those expressions which are created for that very purpose (`s!`).

Optional formal parameters is a completely different mechanism: They allow for calling a function with a different set of actual arguments, because it is allowed to omit an actual argument for a parameter which is optional. The optional parameter could be nullable or non-nullable, and a non-optional parameter can be nullable as well as non-nullable, those two properties are independent of each other.

They do interact in one or two ways, though: An optional formal parameter must have a default value; that value can be specified explicitly (`void foo({int i = 1})`), but when the type of the formal parameter is nullable, it will get null as its default value implicitly if we do not specify a default value (`void foo({int? iq})`).

**Comment by eernstg** [comment]
I think I can close this, because it doesn't give rise to any actionable issues. Also, questions like this are probably better positioned on StackOverflow or similar systems tailored for questions and discussions.
