### ISSUE TITLE
CFE failure in `co19/LanguageFeatures/nnbd/Least-greatest-closure/nonfunction_typedef/nonfunction_static_t05`

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#45464]
CFE fails to report an error in `co19/LanguageFeatures/nnbd/Least-greatest-closure/nonfunction_typedef/nonfunction_static_t05`

**Comment by eernstg** [comment]
I took a look at the following, which is the contents of `co19/LanguageFeatures/nnbd/Least-greatest-closure/nonfunction_typedef/nonfunction_static_t05`

```dart
Type? _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  print("X: $X");
  throw "Error";
}

abstract class A<X extends A<X>> {}
typedef C<X extends A<X>> = A<X>;

void main() {
  void f<X extends C<X>>(C<X> Function() g) => g();
  f(() => captureTypeArgument());
}
```

This program runs (and throws, as expected, because it reaches the `throw` expression) on `dart`, which matches the behavior reported for the test, according to https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LanguageFeatures/nnbd/Least-greatest-closure/nonfunction_typedef/nonfunction_static_t05.

I believe the test can be adjusted such that it does not expect a compile-time error, and the CFE behavior can be considered correct.

However, the analyzer reports

```
Analyzing n022.dart...
  error • Couldn't infer type parameter 'X'.

Tried to infer 'Object?' for 'X' which doesn't work:
  Type parameter 'X' is declared to extend 'A<X>' producing 'A<Object?>'.
The type 'Object?' was inferred from:
  Parameter 'g' declared as     'A<X> Function()'
                but argument is 'A<Object?> Function()'.

Consider passing explicit type argument(s) to the generic.

 • n022.dart:14:3 • could_not_infer
1 error found.
```

This shows that the analyzer and the CFE use different approaches to this inference task (or something else differs, e.g., the computation of the greatest closure of `C<X>`, or other parts of the treatment of the non-function type alias `C`).

So the question is whether one or the other (or both?) behaviors from type inference is an error.

@leafpetersen, @scheglov, @stereotype441, WDYT?

**Comment by johnniwinther** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/193660
