### ISSUE TITLE
Packing of nested structs is unduly restrictive

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#45499]
Take this pair of structs from the Win32 SDK: 
```dart
class GUID extends Struct {
  @Uint32()
  external int Data1;
  @Uint16()
  external int Data2;
  @Uint16()
  external int Data3;
  @Uint64()
  external int Data4;
}

class PROPERTYKEY extends Struct {
  external GUID fmtid;
  @Uint32()
  external int pid;
}
```

In C, `sizeOf(PROPERTYKEY)` is 20 bytes, and it doesn't appear as if any packing is enabled. Without any annotations, the Dart equivalent is 24 bytes, because of padding after `pid`. (I don't understand why this behavior is different, but whatever.)

I auto-generate these structs, so it's difficult for me to predict what the packing alignment should be of `GUID`, since I don't known what other structs nest it ahead of time. I tried adding a packing alignment (`@Packed(4)`) to `PROPERTYKEY`, but that failed with this error:

> Nesting the non-packed or less tightly packed struct 'GUID' in a packed struct 'PROPERTYKEY' is not supported.
> Try packing the nested struct or packing the nested struct more tightly.dart(packed_nesting_non_packed)

Adding `@Packed(4)` to both classes works, but it's unclear to me why this should be necessary in Dart when it is unnecessary in C. Curious on your thoughts, @dcharkes...

**Comment by dcharkes** [comment]
```c++
typedef struct _GUID {
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[ 8 ];
} GUID;

typedef struct _tagpropertykey
    {
    GUID fmtid;
    DWORD pid;  // uint32_t pid;
    } 	PROPERTYKEY;
```

Taken from [guiddef.h](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/shared/guiddef.h) and [wtypes.h](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/shared/wtypes.h#L892).

The MSVC compiler says 16 bytes for GUID and 20 bytes for both [64 bit](https://godbolt.org/z/EY9on5Wof) and [32 bit](https://godbolt.org/z/3qxhKrqb9).

However, the way you specified `GUID` does not match, because you're modeling it as `uint64_t` rather than `uint8_t [8]`. If I change the definition in C to what you did, the alignment rules indeed create PROPERTYKEY to be [24 bytes](https://godbolt.org/z/Pr65ohMzv).

Using inline arrays to match the actual definition from C should work:

```dart
class GUID extends Struct {
  @Uint32()
  external int Data1;
  @Uint16()
  external int Data2;
  @Uint16()
  external int Data3;
  @Array(8)
  external Array<Uint8> Data4;
}

class PROPERTYKEY extends Struct {
  external GUID fmtid;
  @Uint32()
  external int pid;
}
```

**Comment by timsneath** [comment]
Oh, that makes perfect sense. Sorry -- that was stupid of me. I was using the `Uint64` as a workaround during the lack of arrays, and I had become so blind to it that I wasn't factoring it into the differing alignment. My own code does some bit-twiddling here with properties that retrieve the GUID in a single block, but this should work when I've unwound that. Thank you!
