### ISSUE TITLE
Geolocation.getCurrentPosition from dart:html not working in release mode with NNBD enabled

### ISSUE THREAD

**Issue by mvanbeusekom** [dart-lang/sdk#45562]
When trying to access one of the members of the `Geoposition` instance received from the `Geolocation.getCurrentPosition()` or `Geolocation.watchPosition()` methods an "Uncaught TypeError" is throw when running in release mode with sound null safety enabled (`flutter run --release -d chrome`). 

```
Uncaught TypeError: n.grq is not a function
    at main.dart:39
    at WD.a (async_patch.dart:316)
    at WD.$2 (async_patch.dart:341)
    at VR.$1 (async_patch.dart:292)
    at UG.SB (zone.dart:1612)
    at UG.ug (zone.dart:1611)
    at Tf.$0 (future_impl.dart:118)
    at Object.n3 (future_impl.dart:733)
    at Y.ib (future_impl.dart:539)
    at T7.$0 (future_impl.dart:577)
```

Some other interesting observations are that the code runs without issues when:
- running in debug mode with sound null safety enabled (`flutter run -d chrome --debug`);
- running in release mode with sound null safety disabled ('flutter run -d chrome --release --no-sound-null-safety`).

A simple App that reproduces this behaviour looks like this (it's a slightly changed version of the default Flutter counter template) is listed below in the "Reproduction example" section. Note, I am using Flutter to reproduce this issue, since that is what I am most comfortable with. My assumption is that this however is an issue within dart:html, my apologies if this is not the case. Please let me know and I will move the issue to the correct repo.

<details>
<summary>Reproduction example</summary>

```dart
import 'dart:html' as html;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _position = "Unknown";

  Future<void> _currentPosition() async {
    final geolocation = html.window.navigator.geolocation;
    final position = await geolocation.getCurrentPosition();
    final latitude = position.coords?.latitude ?? 'n/a';
    final longitude = position.coords?.longitude ?? 'n/a';
    setState(() {
      _position =
          'Latitude: $latitude, Longitude: $longitude';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title!),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Your current position is:',
            ),
            Text(
              '$_position',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _currentPosition,
        tooltip: 'Current position',
        child: Icon(Icons.location_on),
      ),
    );
  }
}
```
</details>

I have been testing on the following environment:

* Dart SDK Version: 2.12.2 (stable)
* OS: macOS 11.2.3 20D91 darwin-x64
* Browser: Google Chrome 89.0.4389.114

<details>
  <summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/maurits/fvm/versions/stable
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/maurits/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Nexus 5X (mobile)          • 01043361c1b19568                     • android-arm64  • Android 8.1.0 (API 27)
    • iPhone 12 Pro Max (mobile) • A38E946F-C804-4A7C-B341-08CDE2CC40C3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
</details>

**Comment by srujzs** [comment]
Thanks for reporting and supplying a repro. This looks identical to the issue in #44324.

Debugging a bit, the symptom of this issue is that `position` is typed as `GeolocationPosition` with sound null safety whereas it's typed as a `GeopositionWrapper`. With the former, an interceptor is not found and therefore `coords` is not found on the resulting `JavaScriptObject` type. Looking at the source code, the callback provided to `getCurrentPosition` removes a type check with sound null safety:

```
  Geoposition _ensurePosition(domPosition) {
    try {
      // Firefox may throw on this.
      if (domPosition is Geoposition) {
        return domPosition;
      }
    } catch (e) {}
    return new _GeopositionWrapper(domPosition);
  }
```

Specifically, the `is` check is removed. In Chrome, `domPosition` is typed as a `GeolocationPosition` instead, so without sound null-safety, the check exists, and therefore the `position` is correctly wrapped.

With sound null-safety:

```
try {
   return domPosition;
} catch (exception) {
   H.unwrapException(exception);
}
```

and without:

```
try {
  if (type$.Geoposition._is(domPosition))
    return domPosition;
} catch (exception) {
  H.unwrapException(exception);
}
```

I'm not entirely sure what has changed with sound null-safety that dart2js considers that an unnecessary check, since I would assume that would still be a useful check since the parameter is `dynamic?`. I'll have to dig further and report back.

**Comment by srujzs** [comment]
Continuing a couple of thoughts:

dart2js is likely working correctly. `_ensurePosition` is being casted as a callback that accepts a `Geoposition`, so therefore it assumes that it can ignore the type check. Changing the callback definition to accept a `dynamic` fixes the missing type check. However, `Position` (the underlying native name of `Geoposition`) has been renamed to `GeolocationPosition` since Chrome 79 (and on other browsers), which also adds to the issue, since `domPosition` is not supposed to be wrapped except in the rare Firefox case, and should instead be properly intercepted.

What we really want then is:
`Geoposition` should be bound to both `Position` and `GeolocationPosition`.
The callback should accept a dynamic.

**Comment by srujzs** [comment]
cc @fishythefish 

I might need someone more familiar with the rti to take a look whenever you get a chance. It isn't clear why this `is` check fails when `domPosition` is a `GeolocationPosition` with the necessary bindings:

`if (type$.Geoposition._is(domPosition))`

You can apply the patch I'm working with:
<details>
  <summary>patch</summary>

  ```
  diff --git a/sdk/lib/html/dart2js/html_dart2js.dart b/sdk/lib/html/dart2js/html_dart2js.dart
  index bc7bdfbc053..42641867158 100644
  --- a/sdk/lib/html/dart2js/html_dart2js.dart
  +++ b/sdk/lib/html/dart2js/html_dart2js.dart
  @@ -17021,7 +17021,7 @@ class _GeopositionWrapper implements Geoposition {
   // for details. All rights reserved. Use of this source code is governed by a
   // BSD-style license that can be found in the LICENSE file.
  
  -@Native("Position")
  +@Native("Position,GeolocationPosition")
   class Geoposition extends Interceptor {
     // To suppress missing implicit constructor warnings.
     factory Geoposition._() {
  @@ -25723,7 +25723,7 @@ class PopStateEvent extends Event {
   // WARNING: Do not edit - generated code.
  
   @Unstable()
  -typedef void _PositionCallback(Geoposition position);
  +typedef void _PositionCallback(position);
   // Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
   // for details. All rights reserved. Use of this source code is governed by a
   // BSD-style license that can be found in the LICENSE file.
  ```

</details>

and a simpler repro on dart2js with sound null safety:

<details>
<summary>test</summary>

```
import 'dart:html';

void main() async {
  var geolocation = window.navigator.geolocation;
  var position = await geolocation.getCurrentPosition();
  print(position);
}
```

</details>

While the above patch fixes the initial problem, `position` is still typed as `_GeopositionWrapper` because that `is` check fails.

**Comment by fishythefish** [comment]
Talked with @rakudrama, and what seems to be happening is we're not aware that a `Geoposition` is ever created, so it gets tree-shaken out of the code along with the associated `$is` properties that we use to handle `is Geoposition` checks. We used to infer that a `Geoposition` was created because of the argument type of the callback, but now that it's `dynamic`, we can't do this anymore. (Of course, it would be too pessimistic to assume that *everything* is live just because we see a `dynamic` argument.)

The solution is to annotate the `native` member which originates the value with `@Creates('Geoposition')`. That's `_getCurrentPosition_3` for the example you gave, but you probably want to do the same for `_getCurrentPosition_1` and `_getCurrentPosition_2`.

**Comment by srujzs** [comment]
Ah, that makes sense. I saw that `Geoposition` wasn't included in `interceptorsByTag`, but didn't know what to make of it besides that there's some reachability issue. Adding the `@Creates` annotations resolves the issue, thanks!

I'll upload a CL modifying this in the codegen.

**Comment by artificerchris** [comment]
Sorry for the ping on a closed issue, @srujzs, but how can I tell which version of Dart this has went into? I couldn't find any docs on how to tell without just going through the branches and finding it... or is that the best way?

**Comment by srujzs** [comment]
No worries, I believe you can look at the tags of the CL that fixed this issue: https://github.com/dart-lang/sdk/commit/7abaa9549223d62602f18aa7abc3ca9aa5884939

The earliest tag is sdk version 2.14.0-64.0.dev. Right now, it doesn't seem like it's available in a beta or stable version yet (per https://dart.dev/get-dart#release-channels) if you don't want to use the dev channel.

**Comment by artificerchris** [comment]
Ah ok, thanks! And yeah, we'll wait on it to get to stable, but it's good to know what version it's in. We can live without the feature until then.
