### ISSUE TITLE
Evaluation of const expression with .length in assert of const constructor throws exception

### ISSUE THREAD

**Issue by Quijx** [dart-lang/sdk#45592]
The code segment
```dart
class Foo {
  const Foo({List<int> ints = const []}) : assert(ints.length == 0);

  static const Foo foo = Foo();
}
```
does not compile because the expression `Foo()` as the following error `Evaluation of this constant expression throws an exception.`.

This is unexpected because clearly `ints` is empty and `ints.length == 0` should therefore be fulfilled. However the error seems to come from the fact that `.length` is used at all, because when using `assert(ints.length != 0)`, an error is thrown too. The same also happens when using `.length` on `Set`s or `Map`s.

While searching for other issues on this, i found #35420.
From what I understand it should not be possible to use `.length` in a const expression.
Things like
```dart
const List<int> ints = [];
const b = ints.length == 0;
```
are correctly rejected by the compiler at the `ints.length` expression.
But then should `assert(ints.length == 0)` not also be rejected inside a const constructor at the `ints.length` expression?
Without the `static const Foo foo = Foo();`, the code compiles just fine. 

Dart SDK Version (`dart --version`): 
`Dart SDK version: 2.13.0-116.0.dev (dev) (Sun Mar 7 18:57:20 2021 -0800) on "linux_x64"`

**Comment by eernstg** [comment]
This is working as intended. The language specification [has the following](https://github.com/dart-lang/language/blob/e4d2abd074baed292f513aebb55320d895560933/specification/dartLangSpec.tex#L8098):

```
\item An expression of the form \code{$e$.length} is potentially constant
  if $e$ is a potentially constant expression.
  It is further constant if $e$ is a constant expression that
  evaluates to an instance of \code{String},
  such that \code{length} denotes an instance getter invocation.
```

So an expression of the form `e.length` is not a constant expression when `e` evaluates to a list or a set.

I'm getting the expected errors from the front end and from the analyzer:

```
> dart n002.dart
n002.dart:4:26: Error: Constant evaluation error:
  static const Foo foo = Foo();
                         ^
n002.dart:2:56: Context: The property 'length' can't be accessed on '<int>[]' in a constant expression.
  const Foo({List<int> ints = const []}) : assert(ints.length == 0);
                                                       ^
n002.dart:4:20: Context: While analyzing:
  static const Foo foo = Foo();
                   ^
> dartanalyzer n002.dart
Analyzing n002.dart...
  error • Evaluation of this constant expression throws an exception. • n002.dart:4:26 • const_eval_throws_exception
1 error found.
```

> Without the `static const Foo foo = Foo();`, the code compiles just fine.

That is indeed the case, and we get this behavior because the constant constructor is only required to contain expressions that are potentially constant (which allows `e.length` for any potentially constant `e`).

This is required, for instance, in order to handle the case where `e` is a variable of type `dynamic` where different invocations of the constant constructor could pass an argument of type `String` or an argument of some other type:

```dart
class C {
  final int i;
  const C(arg): i = arg.length;
}

void main() => const C('Hello'); // OK.
```
