### ISSUE TITLE
[core.regexp] it is possible for groupCount to be 1 and group(1) == null

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/sdk#45608]
I'm not entirely sure this is a bug, but the first pattern down there has a group count of 1 and group(1) returns a null value and I believe it shouldn't be the case especially since there is no capturing group.

 
```
void main () {
// sorry for the big pattern, this is the one giving me the issue
  final pattern = r'0?(?:(11|2(?:2(?:02?|[13]|2[13-79]|4[1-6]|5[2457]|6[124-8]|7[1-4]|8[13-6]|9[1267])|3(?:02?|1[467]|2[03-6]|3[13-8]|[49][2-6]|5[2-8]|[67])|4(?:7[3-578]|9)|6(?:[0136]|2[24-6]|4[6-8]?|5[15-8])|80|9(?:0[1-3]|[19]|2\\d|3[1-6]|4[02568]?|5[2-4]|6[2-46]|72?|8[23]?))|3(?:3(?:2[79]|6|8[2578])|4(?:0[0-24-9]|[12]|3[5-8]?|4[24-7]|5[4-68]?|6[02-9]|7[126]|8[2379]?|9[1-36-8])|5(?:1|2[1245]|3[237]?|4[1-46-9]|6[2-4]|7[1-6]|8[2-5]?)|6[24]|7(?:[069]|1[1568]|2[15]|3[145]|4[13]|5[14-8]|7[2-57]|8[126])|8(?:[01]|2[15-7]|3[2578]?|4[13-6]|5[4-8]?|6[1-357-9]|7[36-8]?|8[5-8]?|9[124])))15)?';
  final match = RegExp(pattern).matchAsPrefix('93435551212');
  print(match != null);
  print(match!.groupCount);
  print(match.group(0));
  print(match.group(1));
  
  print('');
  print('match 2');
  final pattern2 = r'..';
  final match2 = RegExp(pattern2).matchAsPrefix('22');
  print(match2!.groupCount);
  print(match2.group(0));
  print('end');
}


```

**Comment by lrhn** [comment]
Your pattern does have a capture group, declared starting with `(11|`, so that's working as intended.

In general, a capture group *can* have the value `null` if it didn't participate in the match.

The `groupCount` depends on the number of capturing groups in the the RegExp pattern. It's always the same, and doesn't depend on how the RegExp matched the input.
Not all captures need to be part of the *match*. A "non-participating group" has a value of `null` because it didn't match anything during matching.

Example:
```dart
var re = RegExp(r"(\d+)|(\w+)");
for (var wordOrNumber in re.allMatches(someString)) {  
  var digits = wordOrNumber[1];
  if (digits != null) {
    var number = int.parse(digits);
    doSomething(number);
  } else {
    var word = wordOrNumber[2]!;
    doSomethingElse(word);
  }
}
```
Here the RegExp `(\d+)|(\w+)` has two alternatives, both containing captures. If the RegExp matches, then precisely *one* of those captures has matched, and the other did no participate in the match.


(Also, your pattern contains `\\d` even though the string is raw. That would match the characters backslash + d, not digits. You might want to use `\d` with a single backslash.)

**Comment by cedvdb** [comment]
Thanks for the clarification
