### ISSUE TITLE
Uncaught TypeError: this.function._equals is not a function

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#45601]
Function equality throws a TypeError in `webdev serve --debug` mode: `Uncaught TypeError: this.function._equals is not a function`. The field is declared as `final Function function` and initialized with a tear-off function from an object.

The same code works as expected when run with `webdev serve --release`, `webdev build` or when exercising the JS code using `dart run test --platform=vm,nodejs,chrome,firefox`.

- Dart SDK version: 2.12.2 (stable)
- webdev 2.7.2

**Comment by nshahan** [comment]
I landed a fix in the SDK but it was not in time to make the branch for the Q2 stable release. I'd like to get a since of how blocking this issue is for you to determine if we need to cherry pick the change into the release branch. My understanding is that this issue appears to be much more likely when trying to run with sound null safety.

@drpond1 @renggli Can you comment on how you encountered the issue? Were you trying to migrate a package to null safety?

**Comment by renggli** [comment]
Thank you @nshahan for landing the fix.

I discovered the problem after migrating to null safety, but likely this is because I didn't test my [examples with webdev](https://github.com/petitparser/dart-petitparser/tree/main/petitparser_examples/example) at that time. I think the problem affects anybody that uses `webdev serve --debug` and that depends directly/indirectly on the [PetitParser package](https://pub.dev/packages/petitparser).

**Comment by drpond1** [comment]
I encountered the issue when I started to test the upgrade of my project to Null Safety.
One of things I needed to do was to retest my system with the Lilypond musicXML test suite.  
 renggli pointed out that I could still run the XML parser if  I did it with the build rather than the debug version of the code,  so that is what I did.   There is one problem from this testing that I probably will not address until I can use the debug version.   However,  I do not consider this a critical issue.
