### ISSUE TITLE
Dart and analyzer behaves in the different ways when call a raw non-function typedef constructor

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45658]
Dart SDK version: 2.13.0-216.0.dev (dev) (Wed Apr 7 15:12:05 2021 -0700) on "windows_x64"

Here is a source code example:
``` dart
class C<X> {}
typedef A<X extends C<X>> = C<X>;

main() {
  A();
}
```
Analyzer throws a compile error here whereas dart silently passes.

Sample output is:
```
$> dart test.dart

$ dartanalyzer test.dart
Analyzing test.dart...
  error - Couldn't infer type parameter 'X'.

Tried to infer 'C<Object?>' for 'X' which doesn't work:
  Type parameter 'X' is declared to extend 'C<X>' producing 'C<C<Object?>>'.

Consider passing explicit type argument(s) to the generic.

 - test.dart:5:3 - could_not_infer
1 error found.
```
Please also note that both analyzer and dart don't throws a compile error for the following code:
``` dart
class C<X> {}
typedef A<X extends C<X>> = C<X>;

main() {
  A a = throw "Error";
}
```

**Comment by eernstg** [comment]
The instance creation `A()` is an error because inference yields `A<C<Object?>>()`, and `A<C<Object?>>` is not a regular-bounded type (cf. [this rule](https://github.com/dart-lang/language/blob/9e144a1353a943949634880dd9e120a1234d184e/specification/dartLangSpec.tex#L11319)).

The analyzer reports the error correctly, but the front end does not report it.

**Comment by eernstg** [comment]
Thanks, @stefantsov!
