### ISSUE TITLE
Add support for angular in null-safety migration tool.

### ISSUE THREAD

**Issue by emmanuel-p** [dart-lang/sdk#45661]
Null-safety migration tool could be improved to better support code depending on Angular.

Example / first step:
In angular, injectable constructor parameters can be annotate with "@Optional()" to indicate nullable parameter.
This could hint the migration tool to make the corresponding type/field nullable.

**Comment by emmanuel-p** [comment]
Some more easy fixes:
@ViewChild() and @ContentChild() also require nullable types.

**Comment by stereotype441** [comment]
Ok, with 4d0dc2ea8a5da68d65252c68df1bd81a15ca2a5d, `@Optional()` implies nullability, and with f66037acce9222718a0158e3f61590f5608a39a2, `@ViewChild()` and `@ContentChild()` imply nullability.  I'm going to close this issue since everything that has been requested so far is complete.  @grouma please feel free to reopen (or open a separate issue) if something else comes up that is needed.
