### ISSUE TITLE
analyzer error when using cascade operator on an object inside the truth condition of ternary operator

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#45667]
I noticed the following today and I'm not sure if it's by design or it's a bug:

```dart
  // Analyzer errors:
  // Expected to find ':'.dart(expected_token) 
  // Expected an identifier.dart(missing_identifier)   
  final focusNode1 = autoFocus ? FocusNode()..requestFocus() : FocusNode();
  // fine
  final focusNode2 = !autoFocus ? FocusNode() : FocusNode()..requestFocus();
  // fine
  final focusNode3 = autoFocus ? (FocusNode()..requestFocus()) : FocusNode();
```

Given that case-2 and-3 work, one assumes case-1 would work too.  

* Dart SDK 2.12.2
*  MacOS

**Comment by lrhn** [comment]
It's by design. Not necessarily great design, but design nonetheless, so it is working as intended.

The surprise here is that `focusNode2` probably doesn't work the way you expect.
It really means:
```dart
  final focusNode2 = (!autoFocus ? FocusNode() : FocusNode())..requestFocus();
```
With that in mind, it's not as surprising that `focusNode1` is invalid. The grammar for the conditional expression is
```
<conditionalExpression> ::= <ifNullExpression>
   (‘?’ <expressionWithoutCascade> ‘:’ <expressionWithoutCascade>)?
```
which explains why you can't put a cascade on the "then" expression, and also can't on the "else" expression (which leaves it unambiguous to put a cascade on the entire conditional expression).

See also https://github.com/dart-lang/language/issues/608.
