### ISSUE TITLE
Debugger breaks on incorrect line on exception

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#45684]
When executing the following program with an attached debugger that's configured to break on exceptions I would expect the debugger to break on the line with `throw 'Hello';`. However, the debugger is breaking on the first line of `dart-sdk/lib/developer/timeline.dart`, which is not very helpful.

```dart
import 'dart:developer';

void main() {
  foo(timeline: true);
}

void foo({ required bool timeline }) {
  if (timeline) {
    Timeline.timeSync(
      'Foo',
      () {
        bar();
      },
    );
  } else {
    bar();
  }
}

void bar() {
  throw 'Hello'; // <-- debugger should break here
}
```

Calling `foo` with `timeline: false` causes the debugger to break on the correct and expected line.

I ran into this issue while working on https://github.com/flutter/flutter/pull/78649.

**Comment by devoncarew** [comment]
@DanTup - can you look at the the info returned for the stack trace for this repro? It would be good to know whether the VM is returning correct info or something else it going on.

**Comment by DanTup** [comment]
In VS Code, I end up here:

<img width="983" alt="Screenshot 2021-04-19 at 19 23 43" src="https://user-images.githubusercontent.com/1078012/115284595-c8952e00-a144-11eb-8432-9138e0d0b481.png">

However, it does temporarily jump to the location @goderbauer mentioned before moving here. If you look at the call stack, it doesn't show `bar` at all - which is why it focuses Timeline.timesync (although it doesn't get a location). In VS Code we detect this is framework code and walk up to the next frame (the first user code frame) which puts us at the location in the screenshot above (there's a short delay as we present the top frame immediately and asynchronously fetch the rest).

If I add a breakpoint in `bar` it works fine - it's on the top of the stack. So something seems wrong with the call stack when breaking on the error (I tried things like `@pragma("vm:never-inline")` on the method or adding more code to it, but nothing I tried changed the behaviour).

Here's the `PauseException` event with the unexpected `topFrame`. It has a `tokenPos` of `-1` and points at the `timeline.dart` script.

```js
{
	"jsonrpc": "2.0",
	"method": "streamNotify",
	"params": {
		"streamId": "Debug",
		"event": {
			"type": "Event",
			"kind": "PauseException",
			"isolate": {
				"type": "@Isolate",
				"id": "isolates/1658522312997111",
				"name": "main",
				"number": "1658522312997111",
				"isSystemIsolate": false
			},
			"timestamp": 1618856773700,
			"topFrame": {
				"type": "Frame",
				"kind": "Regular",
				"location": {
					"type": "SourceLocation",
					"script": {
						"type": "@Script",
						"fixedId": true,
						"id": "libraries/@5383715/scripts/dart%3Adeveloper%2Ftimeline.dart/0",
						"uri": "dart:developer/timeline.dart",
						"_kind": "kernel"
					},
					"tokenPos": -1
				},
				"function": {
					"type": "@Function",
					"fixedId": true,
					"id": "classes/555/functions/timeSync",
					"name": "timeSync",
					"owner": {
						"type": "@Class",
						"fixedId": true,
						"id": "classes/555",
						"name": "Timeline"
					},
					"_kind": "RegularFunction",
					"static": true,
					"const": false,
					"_intrinsic": false,
					"_native": false
				},
				"code": {
					"type": "@Code",
					"fixedId": true,
					"id": "code/92d0295ba-10ac25400",
					"name": "[Unoptimized] Timeline.timeSync",
					"_vmName": "[Unoptimized] timeSync",
					"kind": "Dart",
					"_optimized": false,
					"_intrinsic": false,
					"_native": false
				},
				"vars": [],
				"index": 0
			},
			"exception": {
				"type": "@Instance",
				"_vmType": "String",
				"class": {
					"type": "@Class",
					"fixedId": true,
					"id": "classes/78",
					"name": "_OneByteString",
					"_vmName": "_OneByteString@0150898"
				},
				"identityHashCode": 0,
				"kind": "String",
				"id": "objects/0",
				"length": 5,
				"valueAsString": "Hello"
			}
		}
	}
}
```

**Comment by devoncarew** [comment]
Hey - to ping this issue, Flutter will likely ship the use of the `@pragma('vm:notify-debugger-on-exception')` work (aka, 'treat some exceptions as unhandled when a debugger is attached') in the next stable that contains the current master code. That will raise the importance of fixing this.

**Comment by devoncarew** [comment]
@goderbauer - we're currently assuming that this issue isn't encountered often. It that correct from your local testing? We currently wouldn't address - if it wasn't frequently encountered - until an engineer was back from a leave.

**Comment by goderbauer** [comment]
There are two cases where this bug is exposed in Flutter:
* exceptions thrown in `State.dispose()`
* exceptions thrown in a Task scheduled via `SchedulerBinding.scheduleTask`

While the second one is an API that's not often used, the fist one is commonly used. How common it is to have an exception thrown there, though? I don't know...

**Comment by mraleph** [comment]
I just did a quick look at this. I think the fix is extremely straightforward, so I will just try to land that: https://dart-review.googlesource.com/c/sdk/+/196124

**Comment by goderbauer** [comment]
Awesome. I'll give that a try in Flutter when it has rolled in.
