### ISSUE TITLE
Which arguments to the `Symbol` constructor will cause it to throw?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#45727]
Should we just decide that implementations should make `symbol_reserved_word_{,error_}test.dart` succeed, cf. [this result](https://dart-ci.firebaseapp.com/cl/195503/1)?

Here is some background:

The test `corelib/symbol_reserved_word_test.dart` has been around since 2014. However, some logical errors in the test caused many of the test cases in this test to be ignored (comments said that certain compile-time errors were expected, but the test would succeed even if there were just one of a group of such errors, and all the rest were missing).

To fix this, the tests `corelib/symbol_reserved_word_{,error_}test.dart` were created by splitting this test in two, and changing them to use the new test expectation comments.

As a result, we are now testing more things, and we have inconsistencies among tools. So we need to decide on which behavior is correct.

Notes on this situation, where `s` denotes a constant string:

- Let `s` be a constant string. The test expects `new Symbol(s)` to throw if and only if `const Symbol(s)` is a compile-time error. This matches the specification, and should not be controversial. So I'll just use `Symbol(s)` below and say that it is an error or not an error.
- The test assumes that `Symbol(s)` is an error in each case where `#s` is an error. This seems reasonable, but it is a library property rather than a language property, so it should be decided whether we want that.
- The CFE does not report an error for `Symbol('void.foo')` or `Symbol('foo.void')`, but the analyzer does.
- The test expects `Symbol(s)` to be an error whenever `s` is a reserved word that is not `void`. The analyzer does this, but the CFE does not (but the CFE does flag `#s` as an error).
- `dartdevk-*-linux-release-chrome` do not report an error for `Symbol('void.foo')`.
- `dartk-*-linux-debug-x64` do not report an error for `Symbol('void.foo')`.
- `dart2js-hostasserts-*-linux-x64-d8` reject `#void`.

Here is the `dart2js` stack trace:

```
/b/s/w/ir/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: Invalid argument(s): "void" is not a valid (qualified) symbol name
          throw e;
          ^
Invalid argument(s): "void" is not a valid (qualified) symbol name
    at Object.wrapException (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-d8/tests_corelib_symbol_reserved_word_test/symbol_reserved_word_test.js:343:17)
    at Object.Symbol_validatePublicSymbol (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-d8/tests_corelib_symbol_reserved_word_test/symbol_reserved_word_test.js:270:15)
    at main (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-d8/tests_corelib_symbol_reserved_word_test/symbol_reserved_word_test.js:2546:9)
    at action (/b/s/w/ir/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (/b/s/w/ir/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (/b/s/w/ir/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-d8/tests_corelib_symbol_reserved_word_test/symbol_reserved_word_test.js:3164:7
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-d8/tests_corelib_symbol_reserved_word_test/symbol_reserved_word_test.js:3149:7
    at dartProgram (/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-d8/tests_corelib_symbol_reserved_word_test/symbol_reserved_word_test.js:3160:5)
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-hostasserts-strong-linux-x64-d8/tests_corelib_symbol_reserved_word_test/symbol_reserved_word_test.js:3168:3
```

**Comment by eernstg** [comment]
@lrhn, WDYT?

**Comment by lrhn** [comment]
Personal opinion: Make it simpler and stop validating entirely. Allow `Symbol(anyString)` to work for any string, with no validation. The values are equal if the strings are equal, and identical if `const` created.

The only thing we then promise is that `#something` is canonicalized and identical to any other `#something` (in the same library if "something" is a library private identifier) and is identical to `const Symbol("something")` whenever `#something` is valid and not a private identifier (and trimmed for internal whitespace in case of `id . id`).

The VM never validated the arguments to `const Symbol("something")` because const constructors can't do validation, and they haven't added a special case for `Symbol` in the compiler. That might have been superseded by the front-end constant evaluation.

(I also think we should allow `#id=` as a literal).

Then any string can be used with the constructor, and symbol literals are only limited by the grammar.

**Comment by eernstg** [comment]
That makes sense! I vaguely remember having heard that the motivation for restricting symbols to certain specific forms was that this would help avoiding some bugs (and it might even be extended such that a symbol with specifier `s` could only exist in the case where the current program contains a declaration named `s`). Anyway, that doesn't seem to help anybody today.

But should we then also allow `#assert`, `#this`, and all the other reserved words? Why not?

**Comment by lrhn** [comment]
We should not introduce any new literals, because we don't need to. (Caveat, I do want `#x=` as a literal.)

We have literals for the things that *mean* something in the program source: Member/variable names and library names. Those are the names that you *need* to be able to write in order to use `noSuchMethod`, `Function.apply` and `dart:mirrors` in general. Those symbols are produced by the language itself (`noSuchMethod` mainly). Everything else is just something the user does for themselves, and we don't need to support that.
The library names aren't really that needed, but `dart:mirrors` are also misusing them as "symbol paths", so we can't remove them. 

That is, anything else does not refer to a source name, and therefore doesn't need a literal that looks like a source name for anything. Just use `const Symbol("assert")` if you really want a `Symbol` representing the *string* "assert". It does *not* correspond to anything in the source, unlike `#foo` which does represent the source identifier `foo` (as proven by doing `.foo` on something with a `noSuchMethod`).

(I'd also be completely happy to drop symbol literals entirely, but we don't have a good alternative for library private names).

**Comment by eernstg** [comment]
Sounds like you'd be quite happy about changing https://dart-review.googlesource.com/195503 such that `symbol_reserved_word_test.dart` creates all the strings currently created, and expects all the creations to complete normally.

(We should also create some new ones, but that should probably be another test, such that we can have a separate discussion about emojis and other marginal cases.)

We do still expect `const Symbol('foo')` to canonicalize to the same object as `#foo`, right?

**Comment by eernstg** [comment]
Trying out a much more permissive approach in patchset 2 of https://dart-review.googlesource.com/c/sdk/+/195503.

**Comment by rakudrama** [comment]
dart2js enforces the old restrictions with the hack of replacing constructor calls to interface constructor `Symbol` with
calls to `Symbol.validated` from the `dart._internal` library.
This does something that cannot be expressed in the Dart language and adds a lot of complexity.
I'd like to remove this logic if possible.

How much of the implementation detains in sdk/lib/internal/symbol.dart can be retired at the same time?

**Comment by rakudrama** [comment]
@eernstg If you use [this change](https://dart-review.googlesource.com/c/sdk/+/195661) it will help make dart2js not care about non-const Symbols. If you use this approach, please assign some issue to me to clean up afterwards.

**Comment by eernstg** [comment]
Thanks for the info, @rakudrama! The language team supported the proposal to allow an arbitrary string as the argument to the `Symbol` constructor (both in a constant expression and dynamically), and I'm trying to land https://dart-review.googlesource.com/c/sdk/+/195503 with tests expecting that behavior. When that's done, does it help if I land [that change](https://dart-review.googlesource.com/c/sdk/+/195661)? If it is helpful then I'll of course be happy to do it, but if it doesn't matter then I could land https://dart-review.googlesource.com/c/sdk/+/195503 and create issues about the now-failing tests, and then you can land the change and do the clean up whenever that's convenient for you.

**Comment by rakudrama** [comment]
@eernstg We can do this in any order but you have my blessing to copy the three line deletion (my change) into your change if it makes your life easier.

**Comment by eernstg** [comment]
@rakudrama, very good, I'll do it and create that issue. Thanks!

**Comment by eernstg** [comment]
Done in https://github.com/dart-lang/sdk/issues/46207.
