### ISSUE TITLE
Test fail when I Throws a exception

### ISSUE THREAD

**Issue by toshiossada** [dart-lang/sdk#45720]
I Have a function that throws a Failure
```
  Future getAll() async {
      throw DioFailure(
        message: '',
        statusCode: 400,
      );
  }
```
And I writing a Test to verify if my function are throwing a exception

```
  test('should return a DioFalure from API', () async {
    //arrange
    when(() => dioMock.get(any()))
        .thenThrow(DioFailure(message: 'message', statusCode: 401));

    //act
    Future<List<PeopleModel>> result;

    result = datasource.getAll();
    expect(result, throwsA(isA<DioFailure>()));
  });
```
![image](https://user-images.githubusercontent.com/2637049/114916796-978ec380-9dfb-11eb-89bc-9868a4e49496.png)

thats works, but if I put a delay between act and expect the test go fail
```
  test('should return a DioFalure from API', () async {
    //arrange
    when(() => dioMock.get(any()))
        .thenThrow(DioFailure(message: 'message', statusCode: 401));

    //act
    Future<List<PeopleModel>> result;

    result = datasource.getAll();
    await Future.delayed(Duration(seconds: 2));
    expect(result, throwsA(isA<DioFailure>()));
  });
```

![image](https://user-images.githubusercontent.com/2637049/114916823-a2e1ef00-9dfb-11eb-8f72-271f35aa01c8.png)

![image](https://user-images.githubusercontent.com/2637049/114916854-abd2c080-9dfb-11eb-8f56-590772091348.png)

**Comment by lrhn** [comment]
This is working as intended (not sure about the mock part, but I don't think it's relevant).

Your function is an asynchronous function (`async`) which throws an error. That makes it complete the future returned by the call with an error.
When a Dart future completes with an error, and that future doesn't have any listeners which can receive that error, the error is considered *uncaught* and reported to the current zone's uncaught error handler.

Since you can't listen on a future immediately when it's created, you get up to *one microtask* to add an error handler.
When the `result = datasource.getAll();` is evaluated, it creates a future and delays one microtask before it completes it with that error. That's your window of opportunity to add an error handler on `result`.

In your second code sample, you wait two seconds before doing that. The future is long completed and considered uncaught, and the error has been reported to the root zone's uncaught error handler. That may or may not crash the program (depending on platform and isolate configuration).

What you can do, if you know you'll get back to the future later, is to add an error handler:
```dart
var result = datasource.getAll()..catchError((e, s){});
```
This immediately adds an error handler which "handles" any error by ignoring it.
When you later use the `result` future again, you get to see the error a second time, but there was never a point in time where the error was considered uncaught.

In general, always act on returned futures immediately when possible.
