### ISSUE TITLE
allow chained futures to be created immediately

### ISSUE THREAD

**Issue by Fnalsk** [dart-lang/sdk#45779]
Posted this issue in Flutter, was redirected here.

## Use case

I have:

```
List<Future> lst = [];
lst.add(
    somethingThatReturnsAFuture().then((){
        //do stuff here
    })
);
```

The intent of the above code snippet is to add the future corresponding to the `then` call to the list of futures.

However this future does not get added to the list until `somethingThatReturnsAFuture()` completes successfully. So if somewhere else in the code you have something like `await lst.first`, you may encounter an exception because lst doesn't actually have any futures in it.

## Proposal

I think it would make sense if the future that corresponds to `then` is added to lst right away, even though it itself cannot get started until `somethingThatReturnsAFuture()` completes. To do this would require "chained" futures to all be created immediately. The workaround that I see in the current state of flutter is for you to first ensure that `somethingThatReturnsAFuture()` has completed, and only then add the future you're actually interested in to the list, which isn't as clean.

Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"

**Comment by lrhn** [comment]
The `lst.add(somethingThatReturnsAFuture().then((_) { ... }));` should add a future to `lst` immediately when `somethingThatReturnsAFuture()` *returns*, which should happen *synchronously*. That's as fast as possible, it's not delayed by anything asynchronous happening. The future returned by `somethingThatReturnsAFuture()` doesn't need to *complete*, just be returned.

If anything else happens between calling `somethingThatReturnsAFuture()` and the future being added, it's because it's triggered *by* `somethingThatReturnsAFuture()` itself. That's a race condition in the code, and you'll need to address that in any case.

What you can do is:
```dart
var lst = <Future>[];
var c = Completer();
lst.add(c.future);
c.complete(somethingThatReturnsAFuture().then((_) { ... }));
```
This creates a future up-front, then completes it later. The future will be there when you start invoking `somethingThatReturnsAFuture()`, so if that call itself depends on the future, it will be there.
(Hint: Don't try returning `lst.first` from `somethingThatReturnsAFuture()`).

It's not *possible* to add the future returned by `then(...)` before actually *calling* `then`. The `then` method is a perfectly normal method and different `Future` implementations can return different `Future`s from `then`. And you can't call `then` before you have the object to call `then` *on*, which you have when `somethingThatReturnsAFuture()` returns.
So, not a lot of wiggling room here.

**Comment by Fnalsk** [comment]
very nice explanation. Thanks for letting me know about `Completer()` :)
