### ISSUE TITLE
@mustCallSuper confusing with mixins

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#45773]
In the example below, to ensure that all resources of the base class `Base` are freed up when it is disposed, I am annotating its method with `@mustCallSuper`.  Now while implementing `dispose` in the sub class `Sub`, the analyzer lint `must_call_super` helpfully tells me that I need to call `super.dispose()`, which I can easily do thinking that now the resources of Base will get disposed when Sub is disposed. However, that is not the case due to the `FooMixin`: `super.dispose()` will actually call `FooMixin.dispose()` and `Base.dispose()` is never called (even though I said it must be called).

This is of course the expected behavior for how Mixins work in Dart. However I find it confusing that there's no warning that the documented `@mustCallSuper` contract is not fulfilled since `Base.dispose()` is never invoked.

From the [mustCallSuper doc](https://master-api.flutter.dev/flutter/meta/mustCallSuper-constant.html):

> Indicates that every invocation of a method that overrides m must also invoke m.

```dart
import 'package:meta/meta.dart';

void main() {
  Sub().dispose();
}

class Base {
  @mustCallSuper
  void dispose() {
    print('Base dispose');
  }
}

class Sub extends Base with FooMixin {
  @override
  void dispose() {
    print('Sub dispose');
    super.dispose();
  }
}

mixin FooMixin {
  void dispose() {
    print('mixin dispose');
  }
}
```

**Comment by srawlins** [comment]
Before I try to grok your example, have you looked at existing issues regarding mustCallSuper? https://github.com/dart-lang/sdk/issues/36657 in particular deals with mixins.

**Comment by bwilkerson** [comment]
Yes, that's a known problem. (I think there's an issue for it somewhere already, but I haven't looked to confirm.) The fix, of course, is to define `mixin FooMixin on Base { ... }` so that we can tell the author of `FooMixin` to include a super invocation, but I don't know how to flag the absence of the `on` at the declaration of `FooMixin`.

We might be able to detect it at the declaration of `Sub` and tell the user that because `Base` has a member marked with `mustCallSuper` that any mixins that implement that member need to be marked as being `on Base`, but that might be more than was originally intended for the annotation. We could potentially also require any classes being used as mixins to implement `Base` in one way or another.

**Comment by goderbauer** [comment]
> Before I try to grok your example, have you looked at existing issues regarding mustCallSuper? #36657 in particular deals with mixins.

I looked at issues in the linter repository and didn't see anything similar. However, you're right: In the general dart SDK repository there's a duplicate issue for this: https://github.com/dart-lang/sdk/issues/36657

Closing this issue then.
