### ISSUE TITLE
Flex "gap" CSS property missing (HTML)

### ISSUE THREAD

**Issue by angelhdzdev** [dart-lang/sdk#45789]
## What happened?
Flex "gap" CSS property is missing from the style object of the HTML elements.

## Steps to reproduce problem
Typing "element.style." then "G" and not finding the "gap" property in the list of properties.

## Additional info
I solved this by using 
```dart 
setProperty("gap", "20px") ;
``` 

but still strange that this specific and very useful property is missing.
### Browser

Browser:

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by rileyporter** [comment]
Added `gap` and `row-gap` in [this recent CL](https://github.com/dart-lang/sdk/commit/fc8a65d4c8bed75a1f94889b4d04ac61dc38c20d). The `column-gap` property was already there from WebKit. We decided to not add the deprecated `grid-row-gap` or `grid-column-gap` names since the suggestion is to use the updated `row-gap` and `column-gap` names.
