### ISSUE TITLE
Dart on Apple M1 (arm64) doesn't call pthread_jit_write_protect_np when writing to executable memory

### ISSUE THREAD

**Issue by knopp** [dart-lang/sdk#45793]
This results in immediate segfault when running on Apple M1. Relevant documention from Apple:

https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon

Related to: https://github.com/dart-lang/sdk/issues/42773

This tracker is for issues related to:

* Dart VM

**Comment by knopp** [comment]
Some background: Flutter engine can now cross compile to darwin-arm64 and with [some changes](https://github.com/knopp/flutter/tree/tool_mac_arm64) flutter tool can assemble arm64 assets. Release (AOT) build works as expected on M1, JIT crashes when writing to executable memory.

**Comment by knopp** [comment]
Something to keep in mind when implementing this: [pthread_jit_write_protect_np does not have a sane initial value](https://github.com/dotnet/runtime/issues/41991).

**Comment by knopp** [comment]
My bad, I must have overlooked it. Never mind then.

**Comment by rmacnak-google** [comment]
FWIW, I have built the standalone VM for ARM64 and successfully run both JIT and AOT on an M1, so I suspect there is some Flutter-specific issue.

**Comment by knopp** [comment]
@rmacnak-google, weird - that shouldn't be possible according to Apple documentation. You shouldn't be able to write into `MAP_JIT` pages without calling `pthread_jit_write_protect_np(0)` first.  I don't suppose you have System Integrity Protection disabled? (not even sure that matters here)

**Comment by mraleph** [comment]
I think [this code in the engine](https://github.com/flutter/engine/blob/master/runtime/dart_vm.cc#L334-L339) which disables code write protection is to blame. Dart VM by default already flips code regions between RW and RX modes so that a memory region is never R and X at the same time (alternatively we use dual mapping to achieve the same on platforms where this is possible). That explains, why standalone VM works just fine. Flutter Engine disables this mode to avoid performance issues associated with it (unclear if this issues are relevant in development though), but as a result it uses VM in the mode where code pages are RWX and consequently we hit Mac OS X new protections.

**Comment by knopp** [comment]
@mraleph, your right! Thanks. It seems that `mprotect` with right flags does the job. So I guess this issue can be closed and it is indeed a flutter problem.

**Comment by eseidelGoogle** [comment]
Is there a link to the Flutter issue? :)

**Comment by knopp** [comment]
Here: https://github.com/flutter/flutter/issues/81208 (with a PR)
