### ISSUE TITLE
Help for `dart run` is incorrect

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#45837]
The help says args go before the entry point:

```
Usage: dart run [arguments] <dart file | package target>
-h, --help                                             Print this usage information.
```

However, they have to go after:

```
mit-macbookpro4:cons mit$ dart run foo :cons
Could not find package `foo` or file `foo`

mit-macbookpro4:cons mit$ dart run :cons foo
arg: foo
Hello world: 42!
```

**Comment by mit-mit** [comment]
cc @jonasfj @bkonyi

**Comment by kwalrath** [comment]
Weirdly, `--enable-asserts` didn't work for me unless I put it before the entry point:

```
dart run --enable-asserts myapp.dart  # WORKS! The assertion fails (correctly).
dart run myapp.dart --enable-asserts  # :( Assertion is ignored.
```

**Comment by kwalrath** [comment]
Is the arg order different between filename and package entrypoints? That would be really unfortunate.

**Comment by jonasfj** [comment]
Hmm, I guess the signature is:
`dart run [DART_OPTIONS] <file.dart> [args for file.dart]`

Arguments for `dart run` such as `--enable-asserts` goes before the entrypoint, arguments for the entrypoint go after the entrypoint.

**Comment by mit-mit** [comment]
So, there are three things we need to explain the sequence for:

1. Global `dart` flags (e.g. `--verbose`)
1. `dart run` flags (e.g. `--enable-asserts`)
1. Args that should be passed to the program being run

I think the general form is:

`dart run [flags] <file.dart>|<named entrypoint> [args]`

That doesn't work when using the default entrypoint; then you need seperator:

`dart run [flags] -- [args]`

**Comment by bkonyi** [comment]
The general format of the commands is roughly `dart [vm-options] <command> [command-options] [<file.dart>|<named entrypoint> [args]]`. In other words:

- Options used to modify the VM state / operating parameters go before CLI commands
- Command options go after the command
- Arguments to be passed to a target should appear after the target (e.g., script or entrypoint)

We'll need to modify the usage output of the commands to display `[vm-options]`, `[command-options]`, and `[arguments]` where necessary, which is slightly annoying but doable. `[vm-options]` should probably only be displayed when showing verbose help since these aren't flags a typical user will be playing with.

I'm not sure that adding support for arguments for default entrypoints is really worth it. AFAIK, we don't currently support this in existing tooling, there's no built-in support for separators in `package:args`, and this is such a narrow use case I'm not sure it's worth the extra logic. As always, I'm happy to be convinced otherwise :-)

**Comment by mit-mit** [comment]
What are some examples of `[vm-options]` that external developers actually need to care about?

**Comment by bkonyi** [comment]
Here's a few, but they're not exactly common:

```
--enable-service-port-fallback
  When the VM service is told to bind to a particular port, fallback to 0 if
  it fails to bind instead of failing to start.

--root-certs-file=<path>
  The path to a file containing the trusted root certificates to use for
  secure socket connections.

--root-certs-cache=<path>
  The path to a cache directory containing the trusted root certificates to
  use for secure socket connections.
```

Most common / useful VM options have special support built into the CLI (e.g., `--observe`, `--disable-service-auth-codes`, etc).
