### ISSUE TITLE
Completion to private classes: _MyClass, isn't completable from MyCl|

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#45868]
I define: `class _MyClass {}`

Then I start typing somewhere below:

`MyCla|`

I would expect to get _MyClass as an autocomplete suggestion, but it doesn't show up. Event after I type out MyClass, the autocompleter still does not offer _MyClass.

It works, however, for methods.

```
class X {
   void _foo() {}

   void test() {
     fo // autocompletes to _foo()
   }
}
```

**Comment by bwilkerson** [comment]
I get strange behavior when I attempt to reproduce this, and it makes me wonder whether it might have to do with IntelliJ's filtering algorithm.

If I type the following (where the '^' indicates the cursor position)
```
class _MyClass {}
M^
```
I get a list of suggestions. Scrolling through the list I don't see anything that starts with an underscore. If I then type one more character
```
class _MyClass {}
My^
```
the list of suggestions goes away. Requesting completions results in a "No suggestions" message. If I type one more character
```
class _MyClass {}
MyC^
```
and explicitly request suggestions, then the list of suggestions is once again shown and the top item is `_MyClass`.

**Comment by keertip** [comment]
I cannot reproduce this issue. Using VS Code, 

```
class _MyClass {}
M^

```

Code completion suggestions at the `^` does include `_MyClass`, one has to scroll down the list of suggestions to find it. Typing out a `y` next filters it to the top of the list.

The analysis server does have the private class in the list of suggestions.  This issue was opened a while back, so it could be the refactor fixed the bug.

**Comment by bwilkerson** [comment]
I suspect that the issue has been fixed.
