### ISSUE TITLE
LSP Semantic token modifier for constructor use

### ISSUE THREAD

**Issue by MooNag** [dart-lang/sdk#45861]
CC: @DanTup

I am attempting to make my vs code theme more like android studio. However I cannot customize constructor use of classes. VS Code highlights anything that is a class whereas android studio has different colors for class used as type definition and classes that are used as constructors (initialized).

Proposal: add a modifier to class for constructor use: "class.constructor"

Here is android studio:
![image](https://user-images.githubusercontent.com/5561795/116565152-37a01e80-a8cb-11eb-9753-b68f7d9b7eac.png)

Here is VS Code:
![image](https://user-images.githubusercontent.com/5561795/116565199-42f34a00-a8cb-11eb-9b16-ffb8646df76b.png)

Currently the interpreter is assigning any use of a class to the "class" semantic token type:
![image](https://user-images.githubusercontent.com/5561795/116565365-69b18080-a8cb-11eb-9e30-dea8f9aefcfd.png)

**Comment by DanTup** [comment]
With the change at https://dart-review.googlesource.com/c/sdk/+/197401/, a custom modifier is added to constructors which would enable customising the colour like this (in VS Code - I'm not familiar with customisations in other LSP clients):

```js
"editor.semanticTokenColorCustomizations": {
	"rules": {
		"class.constructor": "#ffff00", // yellow
	},
},
```

This results in constructors being coloured differently to other instances of the class name:

![Screenshot 2021-04-30 at 11 50 38](https://user-images.githubusercontent.com/1078012/116685480-52959000-a9aa-11eb-8d1c-6674008c9954.png)

Constructor might fit better as a "Type" rather than a "Modifier", but since tokens can only have a single type I'm a little hesitant to add more (except for types that definitely don't fit existing types - like annotations) as there's no way to "extend" other types so LSP clients would not know how to colour them by default (I can compensate for this in the VS Code extension, but not for other LSP clients). Modifiers don't take anything away, so there are no real drawbacks.

If in future LSP does gain the ability to extend existing types, it may make sense to tweak this so should your custom colour stop working in future, it's worth checking (the **Inspect Editor Tokens** command you're already familiar with should quickly confirm).

(@bwilkerson fyi - in case you have another opinion)
