### ISSUE TITLE
Grammar Dart.g "part of" new rule to recognize some files

### ISSUE THREAD

**Issue by pedro-mimoso** [dart-lang/sdk#45916]
Hello, I'm doing a Masters Thesis that involves using a Dart grammar, and i think this one is the best so far.

If you are interested i did a clone of various projects of dart and analyzed how the accuracy of the grammar was in those projects.

I started using it in version 0.4 with antlr4, but now i saw that it had some changes and i did the same tests again and i saw some really great improvements in accuracy.

However, i did need to add some rules to the grammar, because "part of" is not recognized.

`part of cobblestone;`

It accepts a uri instead of cobblestone for example.

**Comment by pedro-mimoso** [comment]
I have no permissions to do a push from a local branch i created to do the pull request unfortunately

**Comment by eernstg** [comment]
That's a missing update; it is handled in https://dart-review.googlesource.com/c/sdk/+/198400.

**Comment by eernstg** [comment]
@pedro-mimoso &mdash; The grammar rule `partHeader` is used in the grammar rule `partDeclaration`, so it would be used if we invoke `partDeclaration()` in a similar way as `libraryDefinition()` is invoked in `parseLibrary`. So `SpecParser.java` will not call it currently, and the spec parser cannot parse a part file.

However, the only thing which is not tested because of this fact is the `partHeader` rule itself, because `topLevelDefinition` is tested all the time from `libraryDefinition`. So I considered that to be a minor problem.

(`SpecParser.java` is indeed a very thin and not very capable wrapper around `Dart.g`. The main motivation for having the spec parser in the first place is that it can confirm or reject the assumption that the grammar rules in the specification will actually allow us to parse Dart code that the analyzer/compilers accept, so it just needs to be able to run on a lot of Dart source code. That is possible even though it won't parse any part files.)

Are you trying to use `SpecParser.java` to parse Dart code in order to achieve some other goal?

**Comment by pedro-mimoso** [comment]
@eernstg at this moment i'm using only the Grammar, Dart.g to test with ANTLR grun command if it parses projects extracted from github, so i can see the accuracy for each project. i Hva e a script in python that runs the command "grun" for each file of the project by passing the "libraryDefinition" rule as the first rule of the Grammar. So in this case since partHeader is never called in the Grammar itself, files who use "part of" will give an error. But since the main objective of this Grammar is not the same of mine there is no need to change :). I just made a quick adjustment and it parses those files

**Comment by eernstg** [comment]
Very good, thanks!
