### ISSUE TITLE
Explain the semantics of what late final x = foo() means in documentation

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/sdk#45948]
Currently the documentation for [late final](https://dart.dev/null-safety/understanding-null-safety#late-final-variables)variables explains that the developer can assign values to the field at a later point in time. 

It however doesn't specify when a function that's declared as late final x = foo() runs. https://github.com/dart-lang/language/issues/1518 suggests that the foo() only gets run when x gets accessed by the user and is not run when x is never accessed. This behavior is interesting to know for a developer and worth explaining in the documentation.

**Comment by esDotDev** [comment]
Doesn't it address this in the section above? 
https://dart.dev/null-safety/understanding-null-safety#lazy-initialization

_When you do this, the initializer becomes lazy. Instead of running it as soon as the instance is constructed, it is deferred and run lazily the first time the field is accessed._

**Comment by mit-mit** [comment]
cc @eernstg

**Comment by eernstg** [comment]
The precise treatment of a late variable with an initializer is described [here](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#late-fields-and-variables). I agree with @esDotDev that the description in https://dart.dev/null-safety/understanding-null-safety#lazy-initialization covers the topic quite well.

I'll close this issue because we do have a precise specification as well as a quite informative informal description.

@ChristianKleineidam, please create a new issue if you still see a need for improvements in this area.
