### ISSUE TITLE
Building Stable Version of Dart from Source (Perhaps w/ Tarball?)

### ISSUE THREAD

**Issue by GZGavinZhao** [dart-lang/sdk#45955]
I'm not sure whether I should put this here, but I don't know where else I can ask for help from a person from the Dart team. Sorry if this should not belong here!

I've been trying to creating a dart package for the linux distribution I'm using (Solus). The building docs explicitly said to not use a source tarball directly and to use `fetch dart`, but I've had 2 problems with this:

1. For Solus, when building, every package needs to start from a tarball or a git source. However, according to my observation/documentation, neither is possible. Hence, **is there any way possible to build the dart sdk from a source code tarball** (e.g. [2.12.4 from Github](https://github.com/dart-lang/sdk/releases/tag/2.12.4) or the one [on Google git](https://dart.googlesource.com/sdk/+/refs/heads/stable))? Perhaps using a bootstrap method like [what golang does](https://golang.org/doc/install/source#go14)?
2. Assume that I give up and go to the `fetch dart` method. It always gives me the latest dev branch. How can I make it provide me with the latest stable branch?

Thank you in advance for your help! Again, I'm sorry if I shouldn't be asking it here but there hasn't been helpful response on the Gitter channel, and nor do I think that StackOverflow is going to be helpful in this case since Dart team members probably don't have the time to scan through every post and no distribution has tried to build from source.

**Comment by sortie** [comment]
Hi,

No worries, this is the right place to ask. :)

Dart has a lot of dependencies of many kinds, such as other sub git trees that are checked out, CIPD packages, various commands that are run on checkout, and so on. Dart's infrastructure is unfortunately really _not_ set up to make a standalone tarball in the traditional format you request. It might work to do a full checkout and tar it up, though that would be really large and contain many git histories, and I think some files (like CIPD things) might be created outside of the source tree.

The supported method of checking out Dart is via the `gclient` program from `depot_tools`. The `fetch` command from `depot_tools` is meant to make an initial checkout. It essentially makes a `.gclient` file and runs `gclient sync` to check it out. To build a particular branch or commit, you can simply make an initial checkout and then git checkout want you want and run `gclient sync - D`. If you want to do the initial checkout of a particular commit, you can also simply make the `.gclient` file (you can use the one from a previous `fetch dart`) and run `gclient sync -r $commit`.

I hope that helps. Let us know if you need more information on how to use these commands properly? I realize it's not the way distributions might prefer to build Dart and things are largely set up the way they are because we need to solve dependencies at scale while keeping us productive and relying on the supported infrastructure available to us. I'm closing the issue since I think I answered your questions but feel free to follow up and reopen if there's anything more. :)

Jonas
