### ISSUE TITLE
floorToDouble() is rounding up for negative numbers

### ISSUE THREAD

**Issue by Brixto** [dart-lang/sdk#45963]
`-3.6.floorToDouble() ` 
I'd expect this to round to -4. But instead it rounds "up" to -3. Is this intended behaviour?
At least the documentation hints me, this is not correct: 
`Returns the greatest double integer value no greater than this.`

https://en.wikipedia.org/wiki/Floor_and_ceiling_functions according to here, a floor function would round a negative number down towards negative infinity. So -2.7 would become -3

**Comment by jamesderlin** [comment]
It's a bit confusing with a numeric literal, but if you used a variable, it'd be clearer:

```dart
var x = 3.6;
print(-x.floorToDouble());
```
Now it's clearer that `-x.floorToDouble()` could either be `(-x).floorToDouble()` (what you expect) or `-(x.floorToDouble())` (what actually happens).

In practice, most people either wouldn't be calling methods directly on numeric literals or should be using named constants/variables instead of magic numbers.

**Comment by lrhn** [comment]
Yes, it's indeed parsing. `-3.6.floor()` means `-(3.6.floor())`.
