### ISSUE TITLE
IEEE-754 operations behave wrong

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/sdk#45998]
IEEE-754 operations that should give 0.0 in both cases depend on the context and sometime can give me a very small error = 1.1368683772161603e-13

```dart
void main() {
   double b1 = 856.0;
   double b2 = 0.0;
   double b3 = 250.0;
   double b4 = 183.7981622869321;
   double p = b1 - b2 + b3;
   double e = b3 - b4;
   double c = b4 - p;

   double res1 = b1 - b2 + b3    // == 0 - just expanded `res2` expression
                 + b3 - b4
                 + b4 - p
                 - b3;
   double res2 = p + e + c - b3; // != 0, errors as 1.1368683772161603e-13 for some reason
   
   print(res1);
   print(res2);
}

```

`Dart version 2.14.0 (build 2.14.0-74.0.dev)` (bundled with Flutter)

Reproducible in https://dartpad.dev

**Comment by nt4f04uNd** [comment]
Hmm actually I'm not sure if this is a bug, tried with other languages, results are the same. Some insights on why this is happening thought would be helpful

**Comment by DeD1rk** [comment]
The `res1` expression will be simplified/optimized by the compiler to `b1 - b2 + b3 - p`, which becomes exactly `0` when evaluated with double precision (since `b1, b2, b3` are small enough to get full integer precision). `e` and `c` are both double precision approximations (not perfectly equal to their literal definition), so adding `p + e + c` (with both those crazy approximations) will not be exact `b3`, due to small errors in double precision floats. That's just the nature of how floating point numbers work. The difference that you see that is so strange, occurs because the `res1` is optimized away, while `res2` isn't, as the intermediate (non-precise) steps are saved. 

[https://en.wikipedia.org/wiki/Double-precision_floating-point_format](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)

This behaviour will indeed occur in effectively any language, and can not really be 'fixed', so this is not actually a bug. I suppose the issue can thus also be closed.

**Comment by nt4f04uNd** [comment]
Thanks
