### ISSUE TITLE
StreamController.broadcast().stream vs StreamController().stream.asBroadcastStream()

### ISSUE THREAD

**Issue by petercinibulk** [dart-lang/sdk#46001]
What is the difference between StreamController.broadcast().stream and StreamController().stream.asBroadcastStream()?

The following:
```
import 'dart:async';
import 'dart:io';

void main() {
  StreamController<int> streamController = StreamController();

  Stream<int> stream = streamController.stream.asBroadcastStream();

  add1(stream).listen((event) {
    print(event);
  });

  streamController.add(1);

  sleep(Duration(seconds: 3));
}

Stream<int> add1(Stream<int> stream) async* {
  await for (int i in stream) {
    yield i + 1;
  }
}
```
will print out 3 as the result, BUT if I make the change to this (Note where I instantiate the controller and stream):
```
import 'dart:async';
import 'dart:io';

void main() {
  StreamController<int> streamController = StreamController.broadcast();

  Stream<int> stream = streamController.stream;

  add1(stream).listen((event) {
    print(event);
  });

  streamController.add(1);

  sleep(Duration(seconds: 3));
}

Stream<int> add1(Stream<int> stream) async* {
  await for (int i in stream) {
    yield i + 1;
  }
}
```
it will exit without printing.

There has to be a reason for this, but I could not find any documentation online as to why the latter does not work.

**Comment by lrhn** [comment]
The reason is that `Stream.asBroadcastStream` creates a new stream *lazily*. It doesn't start listening on the original single-subscription stream before it gets the first listener on the broadcast stream.
That's documented [here](https://api.dart.dev/stable/2.13.0/dart-async/Stream/asBroadcastStream.html#:~:text=The%20returned%20stream%20will%20subscribe).
The effect of this is that events added to the single subscription stream are buffered until the first listener on the broadcast stream is added.

A broadcast stream controller does not buffer. If there are no listeners when an event is added, the value is just thrown away.
That's documented [here](https://api.dart.dev/stable/2.13.0/dart-async/Stream-class.html#:~:text=whether%20there%20are%20listeners%20or%20not).
