### ISSUE TITLE
Debugger pauses on wrong line with debugger() in catch block

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#46006]
Raised by @4amVim at https://github.com/Dart-Code/Dart-Code/issues/3337. I could repro using the supplied Flutter sample in Android Studio too, though was also able to reduce it to a standard CLI script using latest nightly build:

```dart
import 'dart:developer';

void main() {
  try {
    throw 'a';
  } catch (e) {
    debugger();
  }
  print('debugger pauses here');
}
```

<img width="431" alt="Screenshot 2021-05-13 at 11 10 28" src="https://user-images.githubusercontent.com/1078012/118111601-d7859e00-b3db-11eb-934f-e54fe6194285.png">

The pause event has `tokenPos: 101`, and the `tokenPosTable` looks like this:

```
[
	[3,26,1,31,6,35,10,38,13],
	[4,46,7],
	[5,52,5],
	[6,65,3,67,5,74,12,77,15],
	[7,83,5],
	[8,97,3],
	[9,101,3], // Token 101 is on line 9
	[10,132,1]
]
```

This prevents examining the `e` variable since it appears to have gone out of scope.

**Comment by aam** [comment]
This is due to the fact that `debugger()` gets dart program to stop after the call is completed (https://github.com/dart-lang/sdk/blob/55e71191833d8cabbbda47ca973a350925d140ed/sdk/lib/developer/developer.dart#L20), but there is no next available stopping point from vm perspective until program execution leaves the catch block and gets to `print` statement.
Potentially we could introduce such a stopping point - see https://dart-review.googlesource.com/c/sdk/+/310779

cc @a-siva
