### ISSUE TITLE
Missing error in analyzer (no diagnostic reported for 'class C implements Function {}')

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#46010]
The specification states that

> 20.6 The built-in class `Function` is a supertype of all function types (20.5). It is impossible to extend, implement, or mix in the class `Function`.

However, the analyzer only produces a hint (`HintCode DEPRECATED_EXTENDS_FUNCTION`) for these cases (and nothing in the case of `implements`). This hint needs to be converted to a full error and the `implements` case needs to be reported.

**Comment by eernstg** [comment]
It is a very meaningful future step to make it an error to have `extends Function`, `implements Function`, and `with Function`, but the wording in the language specification is actually softer than that: Immediately after the cited paragraph

> ... It is impossible to extend, implement, or mix in the class **Function**.

it specifies that those usages are actually allowed, but they have no effect. We chose to do it in this manner in order to avoid the associated breakage.

So the analyzer should allow all of these usages, but it should also give `Function` a special treatment such that, e.g., `class C implements Function {}` followed by `Function f = C();` is a compile-time error (because `C` is _not_ considered to have `Function` as a superinterface). A quick experiment seems to indicate that this is already implemented in that manner (in the analyzer as well as the CFE).

**Comment by eernstg** [comment]
@bwilkerson, I think we can close this, or we could move it to the language repository and re-word it to be a proposal to make `extends Function`, `implements ... Function, ...` and `with ... Function, ...` compile-time errors.

**Comment by bwilkerson** [comment]
I'm not advocating for changing the language; I just misunderstood the specification and wanted to make sure that the analyzer was implementing the specification correctly.

It is currently treating all three cases (`extends`, `implements`, and `with`) as if the class was not a subtype of `Function`, but there is no diagnostic reported for `class C implements Function {}`. So there's still a bug in the analyzer and I'd like to leave this issue open to track it.

@scheglov @srawlins

**Comment by srawlins** [comment]
This has been implemented at some point.
