### ISSUE TITLE
Operator[], Object , Function

### ISSUE THREAD

**Issue by nicscott254** [dart-lang/sdk#46028]
I have an error that has proven difficult to solve. everyone so far has failed to help me fix the issue

this is the error o a, getting

**The operator '[]' isn't defined for the type 'Object? Function()'.
Try defining the operator '[]'.**

this is my code

```
import 'package:cloud_firestore/cloud_firestore.dart';

class UserModel {
  static const NAME = 'name';
  static const EMAIL = 'email';
  static const ID = 'id';

  String _name = NAME;
  String _email = EMAIL;
  String _id = ID;

  //getters
  String? get name => _name;
  String? get email => _email;
  String? get id => _id;

  UserModel.fromSnapshot(DocumentSnapshot snapshot) {
    _name = snapshot.data[NAME] ?? "Predefined Name";
    _email = snapshot.data[EMAIL] ?? "Predefined email";
    _id = snapshot.data[ID] ?? "Predefined Data";
  }
}
```

**Comment by eernstg** [comment]
@nicscott254, there will still be some issues with your code. You may wish to use a parameter type like `DocumentSnapshot<Map<String, String>>` in order to indicate in static types that the operations you're performing are actually possible, and then you'll have to handle a possible null result from `data()`. If the situation doesn't admit static typing (e.g., because the actual objects will have various different types) you might have to use `DocumentSnapshot<dynamic>` in order to allow arbitrary operations at compile-time. It will then be checked at run time that the `data()` has an `operator []=` which will accept a `String`.
