### ISSUE TITLE
[Quick fixes] Add suggestion when abstract keyword error

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#46025]
I just got this message:

`Members of classes can't be declared to be 'abstract'.  Try removing the 'abstract' keyword. You can add the 'abstract' keyword before the class declaration.`

![image](https://user-images.githubusercontent.com/351125/116929346-aca98600-ac34-11eb-9a40-1aecd0700430.png)

How do I solve my issue? Well, I just need remove the abstract keyword, which is already highlighted and there is even a red lamp.

However... can't the IDE suggest this (i.e. let the IDE remove it)? It should be a veeery small implementation to make this possible, but would help a lot of people.

Suggestion 2:

```dart
abstract class MyClass {

abstract void method() {};

}
```

instead of just removing the "abstract", it could infer from the empty {} that the user wants a ; (since it is common in this scenario, when coming from other languages). Therefore, it could remove the abstract and add a ;.

Related: https://youtrack.jetbrains.com/issue/WEB-50845 (he told me I should file here under quick fixes).

**Comment by asashour** [comment]
I get a different message

![image](https://user-images.githubusercontent.com/2410127/129560423-d18e871d-404a-4c2b-89d7-bb34173baec2.png)

    IntelliJ IDEA 2021.2 (Community Edition)
    Dart SDK version: 2.15.0-6.0.dev (dev) (Wed Aug 11 14:48:30 2021 -0700) on "windows_x64"

**Comment by Levi-Lesches** [comment]
I can try taking this on, and I'll try to do your second suggestion as well (though I'll make it verify that the function body is empty before removing it). I think it could be enough to copy-and-paste a similar fix, like `remove_await`, and repurposing it to work with `abstract`.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/212574 for the first part.

Second part needs discussion, because this is a valid scenario, so it won't be a `fix`, rather an 'assist'.

```dart
abstract class A {
  void m() {}
}
```

**Comment by bernaferrari** [comment]
Awesome. Yeah, I'm not sure how the second part would behave, but the first part is already great.

**Comment by bwilkerson** [comment]
I have no objection to a fix that removes the `abstract` modifier from the method declaration. That seems like it will always be a valid fix as long as either the member has a body or the container is already implicitly or explicitly abstract.

I don't think we should have an assist to remove an empty body. First, it's unlikely to be a common change for users to want to make, and assists have to be evaluated on every cursor move so we need to be careful about adding assists that aren't high value. Second, making that change is potentially a breaking change and we can't check first to see whether making the change will, in fact, break existing code (because we don't have access to downstream dependencies).

We could potentially have two fixes: "Remove `abstract`" and "Remove both `abstract` and the body" in cases where the method body is an empty block, but again is seems like a fairly uncommon scenario, so it might not be worth adding the second.
