### ISSUE TITLE
Complete an async method synchronously if there are no await statements

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sdk#46060]
[Since Dart 2 was released](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#200---2018-08-07), functions marked async run synchronously until the first await statement. Previously, they would return to the event loop once at the top of the function body before any code runs ([issue 30345](https://github.com/dart-lang/sdk/issues/30345)).

It is still difficult to write an API that would like a synchronous value in the normal case, but allow users to an asynchronous Future. For example, Flutter defines a [`SynchronousFuture`](https://api.flutter.dev/flutter/foundation/SynchronousFuture-class.html) class that users are expected to return when they are overriding a method that returns a Future. (See [setNewRoutePath](https://master-api.flutter.dev/flutter/widgets/RouterDelegate/setNewRoutePath.html) for example)

[Here's a DartPad snippet](https://dartpad.dev/0999eac181958e74196f814e9566c6ef?null_safety=true) to show what I mean. I propose that`makeCoffee` would behave the same as and `makeCoffeeSync`, since it doesn't have any `await` statements.

**Comment by johnpryan** [comment]
Here's an example of how SynchronousFuture is used: https://github.com/flutter/samples/pull/796

**Comment by eernstg** [comment]
@johnpryan, I'm not quite sure about the purpose of this issue, but it could be relevant to compare the `SynchronousFuture` approach with a more explicitly typed approach:

```dart
import 'dart:async';

FutureOr<String> f(bool b, int i) {
  // Easy cases: Finish the job synchronously, return an `int`.
  if (b) return 'Fast $i';
  // Cases that require asynchrony are handled in `fAsync`.
  return fAsync(i);
}

Future<String> fAsync(int i) async {
  await null; // Work hard on something.
  return 'Slow $i';
}

void main() async {
  var i = f(true, 19);
  if (i is int) {
    print(i);
  } else {
    print(await i);
  }
}
```

In this example, `f` announces explicitly that it may return the result directly, or it may return a future which is completed with that result later on. `f` is not `async`, so it is actually possible to return a plain `String` (an async function _always_ returns a future), and it is then possible for the caller to handle the `FutureOr<String>` as needed. For instance, we can do case analysis to handle the `String` or the `Future<String>` in separate branches of an `if`, or we could just pass it on to some other piece of code that knows how to handle a `FutureOr<String>`.

I moved the asynchronous computation to a separate function `fAsync` such that it could be `async` and we can use `await`, but if it doesn't get too unwieldy it could of course be written in the pre-async style inside `f`.

So how do these approaches compare, is one of them just better or do we need to make the choice based on each concrete situation?

The approach using `SynchronousFuture` is more transparent in the sense that any code which is capable of handling a `Future` will also be able to handle a `SynchronousFuture`. The other side of the coin is that it can be difficult to track the synchronous processing in client code: You always have to write code that works on futures, and then it may or may not run synchronously at run time.

If the client code uses the type `SynchronousFuture` explicitly then we do have the guarantee that the code is synchronous, but in that case we could also use a `FutureOr<...>` because the synchronous case is already handled separately, and the approach using `FutureOr` would save some time and space at run time.

**Comment by johnpryan** [comment]
`FutureOr` is a much better type to use in this case. There are a handful of APIs in Flutter that require the user to implement a function that returns a Future, for example:

```dart
abstract class Barista {
  Future<String> makeCoffee();
}

class SlowBarista {
  Future<String> makeCoffee() async {
    return 'slow coffee';
  }
}
```

But often times the framework politely asks that you return a SynchronousFuture if you don't need to run any asynchronous operations:

```dart
class FastBarista {
  Future<String> makeCoffee() {
    return SynchronousFuture('fast coffee');
  }
}
```

Using FutureOr would look like this:

```dart
import 'dart:async';

abstract class Barista {
  FutureOr<String> makeCoffee();
}

class SlowBarista {
  FutureOr<String> makeCoffee() async {
    return 'slow coffee';
  }
}

class FastBarista {
  FutureOr<String> makeCoffee() {
    return 'fast coffee';
  }
}

```

The [docs for SynchronousFuture](https://api.flutter.dev/flutter/foundation/SynchronousFuture-class.html) warn that it should only be used when "you want to expose a single API, where you normally want to have everything execute synchronously, but where on rare occasions you want the ability to switch to an asynchronous model". This sounds like the framework should be using FutureOr instead.

The purpose of this issue, though was to propose that `SlowBarista` and `FastBarista` behave exactly the same, since there are no `await` statements anyway.

**Comment by eernstg** [comment]
By the way, here's a small twist that will improve the precision of the types when the receiver type is more precise:

```dart
import 'dart:async';

abstract class Barista {
  FutureOr<String> makeCoffee();
}

class SlowBarista {
  Future<String> makeCoffee() async => 'slow coffee';
}

class FastBarista {
  String makeCoffee() => 'fast coffee';
}
```

We can do this because `String <: FutureOr<String>` and `Future<String> <: FutureOr<String>`, so it's simply a covariant specialization of the return types, there's nothing specific to futures about it.

> The purpose of this issue, though was to propose that `SlowBarista` and
> `FastBarista` in the second example behave exactly the same, since there
> are no `await` statements anyway.

That's a rather deep change: The semantics of an `async` function like `SlowBarista` is that it returns a `Future`, no matter what, and the "actual result" is provided to the caller by using it to complete that returned future. In contrast, `FastBarista` just returns the `String` object directly, and we never spend the time/space needed to create that future and completing it.

We could consider changing the semantics of async functions to return the result directly when running synchronously, and returning a future if it needs to run asynchronously. An async function would then in general have a return type of the form `FutureOr<T>` for some `T`, rather than `Future<T>` (some other return types are possible, e.g., `dynamic`, but `Future<T>` is the most common kind). 

However, this would break all call sites where the returned value is used as a future, e.g., `myAsyncFunction().then(...)`, because a `FutureOr<...>` doesn't have a `then` method. So it's a rather massively breaking change.

**Comment by johnpryan** [comment]
Thanks for the explanation, I think https://github.com/flutter/flutter/issues/82827 is the best way to proceed for now, so I'll close this unless this comes up in the future.
