### ISSUE TITLE
`year` property to `Duration`

### ISSUE THREAD

**Issue by ZiyadF296** [dart-lang/sdk#46080]
Having `year` property in Duration will be very useful. Sometimes for example you would want to confirm the user is at least 13 years old, and the only option is to use days (365 * 13) and put that value as days. This comes in hard if we need to update the date or even know what 4745 for example represents.

Proposal
Support to `year` property in `Duration`. This isn't an important feature, but it's a proposal and is very useful. There is a workaround (days), but having to pull the calculator always is inconvenient and makes the code easier to understand later rather than reading 4745 days all the time.

**Comment by lrhn** [comment]
It's impossible using the current representation of `Duration` (a number of microseconds), because years don't have a fixed length. Nor do months. We can make some approximation (dividing by 365, or by 365.2425), but I'm certain I can find pairs of dates where that will round the wrong way. If you need to detect an age of 13 years for legal reason, you most certainly do not want to round the wrong way and allow someone who'll be 13 tomorrow to use a 13+ only service. (I'm sure your lawyers will agree).

If you want to ensure someone is 13 years old, you need to understand the *calendars* an use the birth date and the current date, and to check that either the years differ by more than 13, or they differ by 13 and the month and day now is later in the year than the birth day.
Something like:
```dart
/// The difference in full years between two calendar dates.
///
/// Returns the difference in entire years between [from] and [to].
/// Uses only the calendar date of the [DateTime] objects, not the time of day.
/// If [from] is after [to] the result is negative, equivalent to `-fullYearDifference(to, from)`.
int fullYearDifference(DateTime from, DateTime to) { 
  var yearDelta = to.year - from.year;
  if (yearDelta == 0) return 0;
  var monthDelta = to.month - from.month;
  if (yearDelta > 0) {
    if (monthDelta < 0 || monthDalta == 0 && to.day < from.day) yearDelta--;
  } else {
    if (monthDelta > 0 || monthDelta == 0 && to.day > from.day) yearDelta++;
  }
  return yearDelta;
}
```

So, you can get the *precise* result, but not if you go through `Duration`, because the correct result depends on the *dates*, not just the time between t hem. 

So, not going to add years or months to `Duration`. There is a reason the `Duration` constructor doesn't accept anything larger than `days` (and even those are iffy during daylight saving changes).

**Comment by ZiyadF296** [comment]
@lrhn Yes, I see what you mean. 
Thank you for explaining, understood much more now.
