### ISSUE TITLE
Declaration of List Issue, No equivalency between "var myList" & "List myList"

### ISSUE THREAD

**Issue by John235643** [dart-lang/sdk#46181]
`var myList_1 = <int>[1, 2, 3];`
`List myList_2 = <int>[1, 2, 3];`

 `print(myList_1 == myList_2);` //false

But the types are the same:
`print(myList_1.runtimeType);` //Output: `List<int>`
`print(myList_2.runtimeType);` //Output: `List<int>`

And it can lead to errors like this:

`print(myList_1.reduce((value, element) => value + element));` //Output: ` 6` 
`print(myList_2.reduce((value, element) => value + element));` //Output:
` Unhandled exception:` 
` type '(dynamic, dynamic) => dynamic' is not a subtype of type '(int, int) => int' of 'combine'`

**Comment by julemand101** [comment]
A `List` is only equal to itself:

> Whether this list is equal to `other`.
> 
> Lists are, by default, only equal to themselves. Even if `other` is also a list, the equality comparison does not compare the elements of the two lists.

https://api.dart.dev/stable/2.13.1/dart-core/List/operator_equals.html

Which explains why this returns `false`, `myList_1 == myList_2`, since you have two `List` objects. Also, `==` does not compare the runtime type so I am a little confused by "But the types are the same".

Your `reduce` example shows the problem of using `List` as a variable type, since it will remove the generic part of the type of the variable. So the variable `myList_2` is now defined as `List<dynamic>` instead of `List<int>` which are the automatically determined type defined of the variable `myList_1`.

`reduce` is defined as `reduce(E combine(E value, E element)) → E ` so the analyzer will in the first example make it: `reduce(int combine(int value, int element)) → int` and in your second example: `reduce(dynamic combine(dynamic value, dynamic element)) → E ` since this is based of the type information it can get from the variables.

But this is a problem in Dart since the type of objects is defined on the individual object and not determined by the type of variable pointing at the object. So what you really have is variable `myList_2` of the type `List<dynamic>` pointing at an object which are typed `List<int>`. The analyzer will not complain about that, since you are allowed to have a variable with a broader type than the object your are pointing at.

Where the problems begins is you are giving a `(dynamic, dynamic) => dynamic` (automatically determined based on the fact your variable is `List<dynamic>`) method as argument to `reduce<int>` (remember, the object itself remember its type, so this check will happens on runtime).

The problem is that `(dynamic, dynamic) => dynamic` allows any type of object to be returned, while `reduce<int>` restricts the type to be `int` which is now allowed since we cannot return a broader type from a method than what is defined.

So if you instead do this, it will work fine since we are making sure that we will always return a type of `int` which makes the method be typed as: ``(dynamic, dynamic) => int``:
```dart
print(myList_2.reduce((dynamic value, dynamic element) => value + element as int)); //Output: 6
```

**Comment by vsmenon** [comment]
The equality behavior is working as intended.  List is mutable, and structural equality would require an expensive check at runtime.  You can either use `const` lists or something like package:built_collections.

The runtime error is a different issue - and you are right this is an unfortunate sharp edge!   The problem is that Dart interprets `List` as `List<dynamic>`, which breaks inference and triggers that error.  You can avoid this by enabling `no-implicit-dynamic` as a lint - this is now a default in the latest, I think.  In general, you should either use `List<int>` or `var` (which infers `List<int>`) to avoid this.
