### ISSUE TITLE
Combine ByteBuffer and Uint8List

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#46197]
I think we could simplify the typed data interfaces if we merged ByteBuffer and Uint8List, and deprecated the ByteBuffer name.

That is, anything that currently returns a `ByteBuffer` _b_ would just return the equivalent of `b.asUint8List` instead, `Uint8List.buffer` would return `this`, all the members of `ByteBuffer` would be moved to `Uint8List`, and `ByteBuffer` would be made into a `typedef` for `Uint8List` and deprecated.

**Comment by Hixie** [comment]
(Similarly for `UnmodifiableByteBufferView` and `UnmodifiableUint8ListView`.)

**Comment by vsmenon** [comment]
Note, the current hierarchy was designed to map/compile reasonably well to what's in browsers.

**Comment by lrhn** [comment]
It's probably possible, also to compile to JavaScript (you'd just extract the `buffer` from the `Uint8Array` when using it as the current `ByteArray`).

One issue is that not all `Uint8List`s are `ByteBuffer`s. A `ByteBuffer` is a separate, sharable, self-contained piece of memory.
We can give that the `Uint8List` API as well, and allow direct access to the bytes (heck, the VM already does that, using non-view `Uint8List`s as the base type, we have to *wrap* a `Uint8List` to expose a `ByteBuffer`), but a `Uint8List` view is not directly treatable as a `ByteBuffer`, so we'd have two different kinds of `Uint8List`s.

We currently don't make a distinction between a directly allocated `Uint8List` and view. The user can't tell the difference (at least not if the view has `offsetInBytes` at 0 and `lengthInBytes` equal to the buffer's length).
If we added `asUint32List` (from the `ByteBuffer` interface) on `Uint8List`, we'd have it on views as well. We'd then have to say what it means. Should it use the entire underlying buffer or only the part exposed by the view? The latter is dangerous because `Int32List` must be 4-byte aligned.

(The JavaScript API dodges this issue, and some polymorphism issues too, because *all* their typed data arrays are views on the underlying buffer. The VM instead optimizes for lower allocation size of directly allocated lists, but then gets potential polymorphism when directly allocated lists and views reach the same position. I know @mkustermann has spent time optimizing to avoid that problem recently).
