### ISSUE TITLE
Implement constructor tearoffs support in syntax highlighters

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46235]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

- [x] https://github.com/dart-lang/dart-syntax-highlight @DanTup 
- [x] LSP semantic tokens @DanTup 
- [x] https://github.com/codemirror/CodeMirror @domesticmouse 
- [ ] https://github.com/highlightjs/highlight.js @srawlins

**Comment by devoncarew** [comment]
The three repos to update:
- https://github.com/dart-lang/dart-syntax-highlight/
- https://github.com/highlightjs/highlight.js
- https://github.com/codemirror/CodeMirror/

**Comment by devoncarew** [comment]
Note that this issue currently does not have an owner.

**Comment by eernstg** [comment]
@srawlins and @keertip, could you suggest an owner for this issue?

**Comment by DanTup** [comment]
@bwilkerson what's the correct way to enable this for (manual) testing? When I try to copy the sample code I get an error saying I need to use an SDK constraint of `>=2.15.0` for the feature to be enabled, but if I try that I get complaints running `pub get` because my SDK isn't high enough (it's 2.15.0-edge... which is semantically lower than 2.15.0). If I try using `2.15.0-0` as the constraint, I get the original error about needing `>=2.15.0`.

**Comment by bwilkerson** [comment]
Yep.

**Comment by DanTup** [comment]
For the textmate grammar, torn-off constructors are treated like fields, and then functions where they've invoked:

<img width="351" alt="Screenshot 2021-08-30 at 16 59 18" src="https://user-images.githubusercontent.com/1078012/131368591-95fc1fca-511c-4cb2-bfca-0c82fc977dbe.png">

I'm not sure if there's a way to improve this (since the colouring is basic and just uses the presence of the parens to colour the item).

With LSP semantic tokens enabled, they become coloured like constructors, and also have the custom `constructor` modifier:

<img width="732" alt="Screenshot 2021-08-30 at 17 07 27" src="https://user-images.githubusercontent.com/1078012/131369711-173bd757-02b7-4814-b987-ff3351638e3b.png">

Although I'm not certain whether I'd expect `aaa` and `bbb` here to be yellow where they've invoked (they're currently coloured as variables). What's shown here is consistent with other functions (eg. `eee` in `eee()` is also coloured as a variable and not a function/method) though I'm not sure whether that's also accidental or deliberate. @bwilkerson any thoughts?

**Comment by devoncarew** [comment]
Note that out timeframe is to have constructor tear-offs feature complete by early October.

**Comment by DanTup** [comment]
I've opened https://dart-review.googlesource.com/c/sdk/+/213263/ to map the new Highlight Kinds in LSP so the colouring still works. We're not doing anything special for tear-offs so they'll just be coloured as standard functions/methods/constructors (we can easily add a custom modifier to colour them differently, but I don't know if that's a current goal?).

I think that addresses the second item in the task list above (unless we do want to colour them differently?), and I don't think there's anything to do for the first since it doesn't use semantics for colouring (although I've verified things look by my expectations).

**Comment by domesticmouse** [comment]
Can I get clarity on what we want CodeMirror to do for constructor tearoffs? I've looked at what the above code does in DartPad and it looks sane to me (after ignoring the analysis errors):

<img width="557" alt="Screen Shot 2021-09-14 at 10 19 44 am" src="https://user-images.githubusercontent.com/30503/133173657-18fe7177-bee6-470c-9944-15b4bb6d084f.png">

**Comment by srawlins** [comment]
Personally I think that looks fine.

**Comment by bwilkerson** [comment]
> Can I get clarity on what we want CodeMirror to do for constructor tearoffs?

I don't have a definitive answer. The design principle I'd apply is that code should be highlighted differently if doing so aids the user's understanding of the code. In the case of tear-offs I think that means that they should be highlighted differently if
- it's important to the understanding of the code to know whether a constructor/method/function is being invoked vs being torn off (which I think it is) and
-  the syntactic difference (sometimes as little as `()`) and type errors aren't sufficient to make that distinction clear.

I don't know whether the syntactic difference and type errors are sufficient (I don't have any practical experience with it, nor have we done any user studies), but I suspect that they probably are.

My recommendation is to leave them highlighted as is for now and we can change it if it proves to be necessary.

**Comment by devoncarew** [comment]
@srawlins - I'm going to speculatively assume that we're good wrt highlight.js; I don't believe this is a real change to the grammar for what that highlighter is trying to do.
