### ISSUE TITLE
Unexpected type `List<Never>` from constructor default value

### ISSUE THREAD

**Issue by wangkaibule** [dart-lang/sdk#46295]
Dart sdk version:  2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "windows_x64"

There's a test that failed:

```dart
import 'package:test/test.dart';

class Base<T> {
  final T _value;

  T get value => _value;

  Base(this._value);
}

class Child<T> extends Base<List<T>> {
  Child({
    List<T> list = const [],
  }) : super(list);
}

class A {
  int value = 0;
}

void main() {
  test('The concrete instance should have a List<A>', () {
    final c = Child<A>();
    // print(c.value.runtimeType.toString()); // List<Never>
    // The expectation below fails in Dart sdk version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "windows_x64"
    expect(c.value.runtimeType.toString(), 'List<A>');
  });
}
```

As the code shows, I'm trying to instantiate class `Child<T>` with type parameter `T` set to `A`, and expecting to have a `List<A>`  type list from the property `value`. Instead, I'm stuck with a  `List<Never>` that won't do anything useful.

1. Is it an designed behavior to have a `List<Never>` list when the ctor default value is set to `const []` ?
2. How can I get an empty `List<A>` list by default ?

**Comment by eernstg** [comment]
This is working as intended: `const []` is inferred as `const <Never>[]` because a `List<Never>` is usable in this situation no matter which value of `T` you have (`List<Never> <: List<T>` for all `T`).

> I'm stuck with a `List<Never>` that won't do anything useful.

There wouldn't be anything wrong with a `List<Never>` in this situation: Given that the default value for a formal parameter is always a constant expression, you will _always_ get an unmodifiable list if you get it as a default value, and `const <Never>[]` works perfectly fine as an unmodifiable list of `T` for any `T`.

**Comment by wangkaibule** [comment]
Thanks for the explanation, and the walk-around is very helpful. But I still have to mention that, by letting `<Never>` as `runtimeType` seems to compromise the type inference system. Operations such as `(<Never>[]).followedBy(<int>[1,2,3])` simply won't work, even with verbosely type casting: `((<Never>[]) as List<int>).followedBy(<int>[1,2,3])`.

It looks like the meaning of a generalized type has been totally changed by give it a `const []` as default value.

**Comment by eernstg** [comment]
Right, the underlying issue here is that `List` uses the dynamically checked covariance rule that Dart has had from the very beginning, and this implies that every occurrence of a type variable in a contravariant position in the signature of a member is subject to a type check at run time. In particular, `(<int>[] as List<num>).add(3.4)` is accepted at compile-time (although it may hint about an unnecessary cast), and it may seem safe because `as List<num>` is an upcast. But it does throw at run time, because we can't add a `double` to a `List<int>`.

This is a trade-off: We're allowing covariant subtyping (which is very convenient in a lot of situations); in turn, we accept that type errors may occur at specific locations at run time. The same trade-off was made in Java and C# for arrays (where the run time error is `ArrayStoreException` respectively `ArrayTypeMismatchException).

For several years, Dart has been moving in the direction of using compile-time checks only, and getting rid of dynamically checked covariance would be perfectly in line with many other recent changes.

We may well add support for explicit and sound variance to Dart (e.g., dart-lang/language#524). 

In principle, we could then change the type parameter of `List` to be invariant, and then we wouldn't have those dynamic errors (they can occur at invocations of `add`, `addAll`, `followedBy`, `insertAll`, `replaceRange`, `setAll`, `setRange`, or `operator +`, so it's basically when the list is updated &mdash; plus the odd one out: `followedBy`). However, that would be a massively, massively breaking change, so there's no way we could just go ahead and do that.

So the potential type errors have nothing to do with the type `Never` per se, they are associated with _any_ use of covariant subtyping in classes that aren't soundly covariant.

In the case of `followedBy`, we could actually eliminate the contravariant occurrence of `E` by making it static:

```dart
abstract class List<E> ... {
  static Iterable<E1> followedBy<E1>(Iterable<E1> left, Iterable<E1> right);
}
```
