### ISSUE TITLE
Passing `--observe` to the VM causes massive slowdown of program

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#46320]
The example provided by @lrhn at [dartpad.dev/a16b85040](https://dartpad.dev/a16b850405f249408ff8cb877adadd0a?null_safety=true) will run massively slower when invoked via `--observe`.

The reason seems to be that the kernel file given to the VM doesn't have the right metadata attributes which causes it to treat a typed closure call as a dynamic closure call, which can inhibit inlining.

**Comment by mkustermann** [comment]
When `--observe` is passed it seems to cause the VM to tell the `kernel-isolate` to use use an IncrementalKernelCompiler (see [runtime/bin/main_options.cc](https://github.com/dart-lang/sdk/blob/aea28aba051a8e305c23aaeacb4f0394006c38b7/runtime/bin/main_options.cc#L365)) instead of a normal compiler.

Doing so might cause the call-site metadata not to be emitted.

There seems to be an untracked todo for adding the metadata, see [here](https://github.com/dart-lang/sdk/blob/aea28aba051a8e305c23aaeacb4f0394006c38b7/pkg/vm/lib/incremental_compiler.dart#L99):
```dart

  _combinePendingDeltas(bool includePlatform) {
    ...
    for (Component delta in _pendingDeltas) {
      ...
    }

    // TODO(vegorov) this needs to merge metadata repositories from deltas.
    return new Component(
        libraries: combined.values.toList(), uriToSource: uriToSource)
      ..setMainMethodAndMode(mainMethod?.reference, true, compilationMode);
  }
```

/cc @mraleph

**Comment by mkustermann** [comment]
For reference, the place in the VM where we would like to have the metadata is in [here](https://github.com/dart-lang/sdk/blob/aea28aba051a8e305c23aaeacb4f0394006c38b7/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#L3330)

**Comment by mraleph** [comment]
@jensjoha could you merge the metadata?

**Comment by jensjoha** [comment]
I have no insight into the metadata. I think someone on the VM team (with knowledge of metadata) would be a better match for this.

**Comment by mraleph** [comment]
I think you can just union all the metadata repositories (if there is a conflict the newest one wins) and that it.

**Comment by rmacnak-google** [comment]
Looks like another instance of https://github.com/dart-lang/sdk/issues/45421

**Comment by jensjoha** [comment]
I don't like metadata (or our implementation of it)... In this instance, merging correctly without potentially causing leaks is virtually impossible.

Metadata is (roughly) a number of maps mapping from `Node` to the actual metadata. If just blindly copying everything over into the new component when merging we'll (at some point at least) bring over references to otherwise unreferenced stuff (e.g. it should also be merged in the `accept` call in `pkg/vm/lib/incremental_compiler.dart` where when one library is replaced with another one metadata from the first will keep the replaced library alive). That's direct leaks, but they can also via parent pointers (or in the case of non-`TreeNode` `Node`s via `parent` on contained `TreeNode`s (e.g. `InterfaceType`)) bring over entire (old) compilations.

Other than combining and then visiting the entire tree to record which nodes we actually know and just keep those (which would be slow) I don't think we can solve this with the current design of metadata.

I initially thought we could break metadata up by mapping from `Library` to `Node` to metadata (i.e. an "indirection" on `Library`) (with maybe some special handling of adding metadata to the actual component), but we can also associate metadata to nodes only used in constants so that doesn't really work.

The only solution coming to (my) mind is letting every node have a (nullable) metadata field. What the performance and memory characteristics is of that I don't know.

If anyone else have other ideas please share.

**Comment by mraleph** [comment]
@jensjoha we could use `Expando` instead of `Map` to store metadata, though it is going to be slower. Could you try benchmarking that? We can change things to fallback to `Expando` only when merging.

**Comment by jensjoha** [comment]
We can't iterate the keys of an `Expando` so I don't think we'd be able to merge anything.

**Comment by mkustermann** [comment]
Our main use of metadata is in AOT where we would like to attach more information to the AST nodes than what the Kernel AST  format currently offers. For that incremental compilation is not much of an issue.

Though in JIT the Kernel AST should mostly be sufficient. So maybe the best strategy is to work with CFE to get all information in the Kernel AST that JIT needs.

In this case it actually seems the `FunctionInvocationNode` does have a `kind` which we can rely on. Not requiring us needing this metadata in the first place.

I've made [cl/203302](https://dart-review.googlesource.com/c/sdk/+/203302) which addresses the performance issue.

That being said, I don't know if there are other place where JIT relies on metadata.
