### ISSUE TITLE
The `end` in String.substring should be able to exceed the length.

### ISSUE THREAD

**Issue by johnwangwjq** [dart-lang/sdk#46327]
Currently(dart `v3.23.0`) if the `end` is beyond the string length, an exception thrown. I think it's reasonable to return the whole string instead in this case.

**Comment by lrhn** [comment]
Dart libraries generally try to *not* be overly permissive, since that can hide bugs.
If you don't know and don't care that your end index is valid, you can easily do `max(endIndex, list.length)`, but if you *thought* it was valid, and it wasn't, you might just get subtly incorrect results.

So, as a general design principle, we try to require your arguments to be within range unless there are very clear and common use-cases for overflowing arguments.

**Comment by johnwangwjq** [comment]
Make sense. Turning a python mindset to dart is not easy ;-b
