### ISSUE TITLE
could you support @noExtends and @noImplements for abstract class

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#46331]
such as
`class Base` is an abstract class, I just want people to `extends` not `implements`, so I can use `@noImplements(annotation in meta.dart)`:
```dart

@noImplements
abstract class Base {
...
}
```
if people use with `class Child implements Base {...}` will get a warning by analyzer

**Comment by lrhn** [comment]
This sounds like a request for "interface-less classes". We have other such requests in the language repository, and it might be part of any attempt to make sealed classes (it being a kind of "partially sealed").

It's definitely possible to add this to the analyzer as an annotation only.
There should be no need for `@implements` since you can prevent `extends` by not having any public generative constructor.

(I'd probably make it `@extendOnly` or `@noImplements`, to signal that it's a restriction. Also avoids any reserved word conflict. A class with `@extends @implements` looks like it should be able to do both, but if it really prohibits both, then it's confusing.)

**Comment by Silentdoer** [comment]
> This sounds like a request for "interface-less classes". We have other such requests in the language repository, and it might be part of any attempt to make sealed classes (it being a kind of "partially sealed").
> 
> It's definitely possible to add this to the analyzer as an annotation only.
> There should be no need for `@implements` since you can prevent `extends` by not having any public generative constructor.
> 
> (I'd probably make it `@extendOnly` or `@noImplements`, to signal that it's a restriction. Also avoids any reserved word conflict. A class with `@extends @implements` looks like it should be able to do both, but if it really prohibits both, then it's confusing.)


yes, it's my bad, @extends and @implements should be rename to @noImplements and @noExtends like you said.

**Comment by bparrishMines** [comment]
This would also be beneficial to [federated plugins](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit). Each platform implements a shared platform interface and we are [programmatically checking that any class is extended and not implemented](https://pub.dev/packages/plugin_platform_interface#sample-usage). But, there are still situations where a platform implementation can accidentally get around this. An analyzer warning would be easier to work with.

cc @stuartmorgan @pq

**Comment by pq** [comment]
See also @lrhn's proposal: https://github.com/dart-lang/language/issues/704

**Comment by jellynoone** [comment]
Also an added benefit with being able to force a client extending your class rather than implementing it is that you are also able to maintain some internal assertions.

For instance, defining a `PositiveDuration` class which essentially `extends Duration` and adds an assertion in the constructor so that the duration is indeed positive. _(Of course even extending it you could break that assumption but in that case it would really be intentional.)_

**Comment by srawlins** [comment]
These have all been implemented in the language.
