### ISSUE TITLE
Error message "Invalid constant value" doesn't signpost to potential cause

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#46355]
This error message could benefit from being expanded, particularly with some suggestions for root causes. For example, perhaps: 

"Invalid constant value. Consider removing the `const` declaration from the code that uses it, or replace it with a const value."

https://github.com/dart-lang/sdk/blob/dd1f384f2389004049c9e4b00a1068498ebdf28a/pkg/analyzer/lib/src/error/codes.dart#L6456-L6457

Take this small snippet of a beginner Flutter code project: 
```dart
        appBar: AppBar(
          title: const Text(
            'Fooderlich',
            style: GoogleFonts.openSans(),
          ),
        ),
```

Here, the error is unhelpful since it doesn't give any hints as to why the value may be invalid. If you know what you're looking for, you may infer that `GoogleFonts.openSans()` does not return a `const`, but the word 'invalid' is not the same as 'non-const'.  

By the by, this warning appears multiple times if the property is chained:
![image](https://user-images.githubusercontent.com/2319867/121938537-cabcd880-cd00-11eb-8a16-7a848d6d813d.png)

I bring it up because it appeared in a simple and highly-trafficked starter project that I'd ported forward, and I took ten minutes to figure out what was wrong. Dumb on my part, perhaps, but a good opportunity to remove some customer friction.

**Comment by bwilkerson** [comment]
I absolutely agree.

For anyone trying to solve the problem: the issue is that we have a single diagnostic code that is used for all possible errors in constant expressions. As a result the message is incredibly vague, because any attempt to be more specific would be wrong in all the other cases. The existing code needs to be broken up into multiple codes based on the reason why the constant is invalid, and those codes need messages that make that cause (and correction) clear.

Note that this arc of work is related to a proposal to enhance the set of constant expressions and the proposal to, as part of that work, re-write the constant evaluator so that it can be shared between the analyzer and the front-end.

**Comment by ChaserVasya** [comment]
Also it would be nice if error message will contain a desition beside the reason because this problem is very common among newbies. It would be user-friendly.

**Comment by zigzag312** [comment]
Underlining the related `const` keyword would help us see where the `const` is.

Related issue: #47532

**Comment by srawlins** [comment]
@kallentu worked on this a lot in 2023; this maybe can be closed? I can't check easily without a minimal reproduction of the issue.
