### ISSUE TITLE
My generate_package_config and CI's generate_package_config disagree.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#46369]
I've uploaded a CL (https://dart-review.googlesource.com/c/sdk/+/203641) which edits the SDK's package_config.json, and now [CI says the file is out of date](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8844355455072422544/+/u/validate_.dart_tool_package_config.json/stdout?format=raw):

    Package config out of date
    Run `gclient sync -D && dart tools/generate_package_config.dart` to update.

When I run the command locally, I only get a change in timestamp.

I do see `third_party/pkg/petitparser` and `third_party/pkg/utf` on my local disk.

**Comment by srawlins** [comment]
CC @leafpetersen

**Comment by srawlins** [comment]
If I remove the lines with petitparser and utf, I get a `git cl upload` presubmit error:

```
** Presubmit ERRORS **
File .dart_tool/package_config.json is out of date.
Fix these issues with:
gclient sync -D && /Users/srawlins/code/dart-sdk/sdk/tools/sdks/dart-sdk/bin/dart tools/generate_package_config.dart
```

**Comment by athomas** [comment]
Most commonly, this happens when `git` pulled in a change that modified the `package_config.json` but you haven't run a `gclient sync`. The presubmit then finds an outdated `pubspec.yaml` that doesn't match the `package_config.json` and suggest do run gclient and regenerate the package config. When you do that, the `gclient sync -D` alone already fixes the problem and then `generate_package_config.dart` script only changes the timestamp.

Either we enhance the `generate_package_config.dart` script to not touch the file when it's already current. The timestamp in the file is really a misfeature that makes the script non-idempotent, not sure if it's required. That's what git is for...

Or we suggest a slightly different command like `gclient sync -D && <re-validate> || <generate>`.

**Comment by srawlins** [comment]
Thanks @athomas ; I had been running `gclicent rebase-update` as well.

I was able to resolve by skipping presubmit hooks.

**Comment by srawlins** [comment]
I think the generated package_config.json stuff was refactored.
