### ISSUE TITLE
dart2js runtime errors with Symbol constructor accepts arbitrary string as argument

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#46397]
[https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8844279867381285616/+/u/test_results/new_test_failures__logs_](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8844279867381285616/+/u/test_results/new_test_failures__logs_)

/cc @fishythefish

**Comment by sigmundch** [comment]
odd, github removes the trailing _ from the URL, this [link][1] should work

[1]: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8844279867381285616/+/u/test_results/new_test_failures__logs_

**Comment by rakudrama** [comment]
Erik - I expect there is some spec change and related work items. Can you identify those, and perhaps close this if it is enough of a 'duplicate'?

**Comment by lrhn** [comment]
The `Symbol` constructor is not governed by the language specification as such. It's only mentioned in that non-private symbol literals are create values *equivalent* to const invocations of the `Symbol` constructor (and private symbols cannot be created by any constructor).
The documentation should be on the `Symbol` constructor itself, and we should remove the restriction on the string argument.
(So, any two objects created by `Symbol(s)` for the same string `s` are equal, not equal to symbols created from other strings, and canonicalized if constant.)

**Comment by fishythefish** [comment]
There's a `Symbol.validated` constructor which calls `validatePublicName`, and it looks like this exists specifically for `dart2js`. In SSA, we rewrite all `Symbol` constructor invocations to call `Symbol.validated` instead. I assume this means that there was historically an extra restriction in `dart2js` for a reason. Does anyone know what that is?

**Comment by lrhn** [comment]
The restriction was there for everybody, but not everybody actually implemented it.
Only some strings were accepted as arguments to the `Symbol` constructor (those corresponding to symbol literals). Since the constructor was `const` and therefore couldn't check those restrictions in Dart code, it was special cased by the compiler. In Dart2JS, that was done by checking the argument to `const` invocations in the compiler and deferring non-`const` invocations to a non-`const` constructor. The VM originally just ignored the specification and accepted any string.

The const computation is now shared in the CFE, but the VM still accepts any string with a `new` invocation.

That's what we are changing now by allowing any string as argument. The implementations will then finally agree in being permissive (and can drop special casing the constructor). (Probably still need some to special-case private-named symbols in some way, even if it's just having a `const Symbol._private(String name, Object libraryId)` constructor that you can call instead).

**Comment by fishythefish** [comment]
Attempt at a fix: https://dart-review.googlesource.com/c/sdk/+/204601

It looks like there are some existing tests that also need to be updated if we're making this change. It looks like they're already approved failures on the VM/DDC, so I think this should bring dart2js in line with them.

**Comment by eernstg** [comment]
Note that https://github.com/dart-lang/sdk/issues/46207 is the implementation issue for the work where the `Symbol` constructor is changed to accept any string as the argument.
