### ISSUE TITLE
the fix for the `directives_ordering` lint does not respect line comments

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#46404]
The bulk fix for the `directives_ordering` lint does not respect line comments. Specifically, running `dart fix --apply` on something like:

```
// @dart=2.10

import 'package:test/test.dart';

import 'package:pub/src/exit_codes.dart' as exit_codes;

import '../descriptor.dart' as d;
import '../test_pub.dart';
```

will produce:

```
import 'package:pub/src/exit_codes.dart' as exit_codes;
// @dart=2.10

import 'package:test/test.dart';

import '../descriptor.dart' as d;
import '../test_pub.dart';
```

This is particularly problematic as because we've moved the position of the language directive comment, the code is now interpreted as null safe code, when the file has not yet been migrated to use null safety; we immediately show analysis errors in the file.

**Comment by devoncarew** [comment]
This also occurs if you just choose the 'organize imports' quick fix for the lint issue.

**Comment by devoncarew** [comment]
This issue made https://github.com/dart-lang/pub/pull/3036 significantly harder - there were several dozens files to manually patch up after `dart fix` ran.

**Comment by vsmenon** [comment]
Any updates here?

**Comment by DanTup** [comment]
I do recall making some fixes to sorting, but the most recent one I can find is quite a while ago (d3b0979b04f594f93ad49990e51d06314c6ab816). It looks like the line comment here is being attached to the import and being moved with it, which I think is only supposed to happen when there's no blank line between them.

Although I wonder whether the language version should be treated specially, because even without a blank line it shouldn't be moved? For example:

```
// @dart=2.10
import 'bbb';
import 'aaa';
```

```
// some comment about bbb (or perhaps an //ignore)
import 'bbb';
import 'aaa';
```

Without special handling, both of these look the same, but I think the result of sorting should move the comment with `import bbb` in the second example, but not the first?

**Comment by bwilkerson** [comment]
Yes, the version comment has to come before any non-comment token in the file. But when I try the first example in IntelliJ it works as expected. The comment in the second case doesn't get moved, but that might have been intentional. If the example is
```
import 'bbb.dart';
// some comment
import 'aaa.dart';
```
then the comment does get moved, which is an improvement over what it used to be.

It's possible that the fix doesn't use the same underlying code to re-order directives, but I thought that had been fixed as well.

**Comment by DanTup** [comment]
I also don't seem to be able to reproduce the original issue described above either with a recent nightly or 2.13.4 (I tried Sort Members, Organise Imports and `dart fix` / Fix All).

However, looking at some of the files in the linked PR, I did find the language comment _going missing_ with this example:

```dart
// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// @dart=2.10
import 'dart:io' show File;

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import 'package:pub/src/exit_codes.dart' as exit_codes;

import '../../descriptor.dart' as d;
import '../../test_pub.dart';
```

If I use Organize Imports I get:

```dart
// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.


import 'package:path/path.dart' as p;
import 'package:pub/src/exit_codes.dart' as exit_codes;
import 'package:test/test.dart';

import '../../descriptor.dart' as d;
import '../../test_pub.dart';
```

But if I use Sort Members the language version does _not_ go missing (which is strange given my change linked above claims to make these use the same code). I'll take a look at what's going on there.

**Comment by DanTup** [comment]
I see what happened. Organize Imports removes the unused `dart:io` and the comment was "attached" to it so it was removed to. With some tweaks, I can repro Devon's original issue (both for sorting and organizing):

```dart
// Copyright

// @dart=2.10

import 'package:test/test.dart';
import 'dart:io' show File;

File f;
```

Results in:

```
// Copyright

import 'dart:io' show File;

// @dart=2.10

import 'package:test/test.dart';

File f;
```

It doesn't happen if the `// Copyright` comment isn't there as the language directive comment is treated as the "library comment", but otherwise it isn't (because there's a blank line). I guess if there's a language directive, it (and everything above it) should always be considered part of the library comment.

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/209100/ handles the cases I could come up with. When skipping over the library comment we'll also now skip over any language tokens.

> The comment in the second case doesn't get moved, but that might have been intentional.

I think you're right - looking at the code, it seems we assume the very first comment in the file is always a "library comment" and will only attach a line to the first import if there's a blank line before it.

**Comment by bwilkerson** [comment]
I think that assuming that the comment is a library comment is reasonable. I'd guess that it's uncommon to have comments (other than 'ignore') on a directive and relatively common to have a file header. We could consider special casing ignore comments, but it probably won't happen often in practice.
