### ISSUE TITLE
Casting and generic functions

### ISSUE THREAD

**Issue by d-markey** [dart-lang/sdk#46407]
Hello,

the piece of code below passes static analysis but fails at runtime with exception `type '(B) => Link<String, A>?' is not a subtype of type '(Data<dynamic>) => Link<dynamic, Data<dynamic>>?' in type cast`.

I don't understand why this would fail -- is it an issue with the analyzer missing the problem, or with the runtime failing to cast?

Also, I don't understand why the analyzer reports an unnecessary cast for `final ft = f as getter<T>;` on line 86.

Could anyone explain what's wrong in my code, or confirm there is a problem in Dart static analyzer or runtime?

```
void main() {
  final a = A("a");
  print('a = $a');
  final b = B(1);
  b.property = Link();
  print('b = $b');
  b.property = Link.withKey("x");
  print('b = $b');
  b.property = Link.withValue(a);
  print('b = $b');

  final w = Manager();

  w.register___strongly_typed___static_anaysis_ok___runtime_ko___<B>((x) => x.property); // crash

  // Unhandled exception:
  // type '(B) => Link<String, A>?' is not a subtype of type '(Data<dynamic>) => Link<dynamic, Data<dynamic>>?' in type cast
  // #0      Manager.register___strongly_typed___static_anaysis_ok___runtime_ko___ (file:///C:/%23Projects/debug/main.dart:67:23)
  // #1      main (file:///C:/%23Projects/debug/main.dart:14:5)
  // #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

  w.register___strongly_typed___static_anaysis_ok___runtime_ko___<B>((x) => x.property as Link); // crash

  // Unhandled exception:
  // type '(B) => Link<dynamic, Data<dynamic>>' is not a subtype of type '(Data<dynamic>) => Link<dynamic, Data<dynamic>>?' in type cast
  // #0      Manager.register___strongly_typed___static_anaysis_ok___runtime_ko___ (file:///C:/%23Projects/debug/main.dart:66:23)
  // #1      main (file:///C:/%23Projects/debug/main.dart:14:5)
  // #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
  // #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)  // Unhandled exception:

  w.register___dynamically_typed___static_anaysis_ok___runtime_ok___<B>((dynamic x) => x.property);

  final x = w.getLink(b);
  print('x = $x');
}

abstract class Data<K> {
  K get key;
}

class Link<K, T extends Data<K>> {

  Link({ T? value, K? key }) : _value = value, _key = key;
  Link.withValue(T value) : this(value: value);
  Link.withKey(K key) : this(key: key);

  final K? _key;
  final T? _value;
  K? get key => _value?.key ?? _key;

  String toString() => key == null ? '<NULL>' : '<$key>';
}

class A implements Data<String> {
  A(this.key);
  final String key;
  String toString() => '$key';
}

class B implements Data<int> {
  B(this.key);
  final int key;
  Link<String, A>? property;
  String toString() => '$key/$property';
}

typedef Link? getter<T extends Data>(T data);

class Manager {
  final _functions = Map<Type, getter>();

  void register___strongly_typed___static_anaysis_ok___runtime_ko___<T extends Data>(getter<T> f) {
    // guarantees that getter f registered for type T is effectively a getter<T>
    _functions[T] = f as getter; // casting required by static analysis: why?
  }

  void register___dynamically_typed___static_anaysis_ok___runtime_ok___<T>(getter f) {
    // works at runtime but a getter<A> could be registered for type B
    _functions[T] = f;
  }

  Link? getLink<T extends Data>(T data) {
    final f = _functions[T];
    if (f == null) return null;
    final ft = f as getter<T>;  // static analysis says cast is unnecessary? but getter<A> is different from getter<B>
    return ft(data);
  }
}
```

Dart version:

```
Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "windows_x64"
```

**Comment by lrhn** [comment]
The class `Manager` declares `final _functions = Map<Type, getter>();`. With the definition of `getter`, that's the same as
`final _functions = Map<Type, Link? Function(Data)>();`, and since `Link` is also generic and uninstantiated, that's the same as
`final _functions = Map<Type, Link<dynamic, Link<dynamic>>? Function(Data)>();`

Then you call
```dart
w.register___strongly_typed___static_anaysis_ok___runtime_ko___<B>((x) => x.property); // crash
```
It's declared as:
```dart
void register___strongly_typed___static_anaysis_ok___runtime_ko___<T extends Data>(getter<T> f) {
    // guarantees that getter f registered for type T is effectively a getter<T>
    _functions[T] = f as getter; // casting required by static analysis: why?
  }
```
so the context type for the argument is `getter<B>` aka `Link<dynamic, Data<dynamic>>? Function(B)`. That infers the `x` parameter to be `B`.

Then the function is called with `f` being bound to a `Link<dynamic, Data<dynamic>>? Function(B)` and `T` to `B`, and you try to do `_functions[T] = f`.

The compiler disallows that without the cast because a `Link? Function(T)` is-not-a `Link? Function(Data)`. Here `T` is a subtype of `Data` (it's a type variable which can be any subtype of `Data`), and type parameters are contravariant.

Then you add `as getter`, aka `as Link<dynamic, Data<dynamic>>? Function(Data)` (there is no type argument, so `getter` is instantiated to its bound).
That silences the compiler's otherwise completely valid warning, and instead you get a run-time error because a 
`Link? Function(B)` us not a `Link? Function(Data)`, and therefore can't be cast to that type.

The problem is the *parameter* type, so adding casts to the return value doesn't change anything.

So, it's working as intended. It's possible that it can be fixed to work, but it's going to require careful threading of the types through the system.

**Comment by d-markey** [comment]
Hello, thanks a lot for your explanations which helped me find a workaround (solution?).

Instead of trying to cast the getter<T> into a getter<dynamic>, I wrapped it in a function accepting a dynamic parameter. The wrapper is effectively a getter<dynamic> and can be registered in a List<getter>, but it's not a cast!

```
  void register___strongly_typed___static_anaysis_ok___runtime_fixed___<T extends Data>(getter<T> f) {
    // guarantees that getter f registered for type T is effectively a getter<T>
    _functions[T] = (dynamic x) => getter(x as T); // wrap instead of cast
  }
```

Then the wrapper will happily accept any T argument when it is used and pass it on to the getter<T>. Indeed the cast is not necessary.

**Comment by d-markey** [comment]
Hello, many thanks for your explanations.

It helped me find a solution, and to properly register the `getter<T>` in the `Map<Type, getter>`, I wrapped the initial function instead of trying to cast it. This makes it a `getter<Data>`.

`_functions[T] = (Data x) => f(x as T);`

This will work in my use case because values in the map are used in such a way that types will match at runtime, so downcasting x will not throw.
