### ISSUE TITLE
DateTime is error before 1989-9-17 2:00( beijing Time)

### ISSUE THREAD

**Issue by gaoxuefeng** [dart-lang/sdk#46414]
DateTime isError before 1989-9-17 2:00 beijing Time
when  ChinaTime:1989-09-17T02:00:00.000  timeStamp and Utctime is right
but when change time to 1989-09-17T01:59:00.000 time stamp is error
beijing time shound early than utc time 8 hours 

[+16209 ms] I/flutter ( 8948): ChinaTime:1989-09-17T02:00:00.000
[        ] I/flutter ( 8948): UTCTime:1989-09-16T18:00:00.000Z
[        ] I/flutter ( 8948): TimeStamp:621972000000
//
[+34668 ms] I/flutter ( 8948): ChinaTime:1989-09-17T01:59:00.000
[        ] I/flutter ( 8948): UTCTime:1989-09-16T16:59:00.000Z
[        ] I/flutter ( 8948): TimeStamp:621968340000

**Comment by gaoxuefeng** [comment]
the bad time period is (beijing time) from   DateTime(1989, 04, 16, 2, 0) to     DateTime(1989, 07, 17, 2, 0)

**Comment by lrhn** [comment]
I see the same results when running in a browser, whether I use Dart or the JavaScript `Date` object.
```javascript
new Date(1989, 08, 17, 2, 0)
// prints Date(1989-09-16T18:00:00.000Z)
new Date(1989, 08, 17, 1, 59)
// prints Date(1989-09-16T16:59:00.000Z)
```
So, if that's what the browser gives us, it's not something Dart can change when running in the browser. We rely on the browser's `Date` class for date-time computations.
Since the browser gets its time zone information from the international time-zone database, and so does native operating systems, it's not surprising if the native VM gives the same results.

Generally, Dart does not handle time zones itself, it relies on the operating system or browser.

According to https://en.wikipedia.org/wiki/Time_in_China, China has not observed daylight saving time since 1991, which suggests that they did before, and that's probably what you are seeing here.

The time-zone database lists:
```
# Rule	NAME	FROM	TO	-	IN	ON	AT	SAVE	LETTER/S
Rule	PRC	1986	only	-	May	 4	 2:00	1:00	D
Rule	PRC	1986	1991	-	Sep	Sun>=11	 2:00	0	S
Rule	PRC	1987	1991	-	Apr	Sun>=11	 2:00	1:00	D
```
which I read (tentatively) as daylight saving of one hour between the first Sunday of April after the 11th until the first Sunday of September after the 11th (both at 2:00 AM).

The 17th of September 1989 was a Sunday, and so was the 16th of April 1989. and both were the first Sunday after the 11th of the month, so what we see here precisely matches the expected daylight saving of one hour between 2:00 AM of those dates.

So, most likely working as intended according to the available time-zone data.
