### ISSUE TITLE
Failures on Add `unawaited` function and `ignore` extensions member....Sort declarations in dartdev.dart

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46451]
There are new test failures on [Add `unawaited` function and `ignore` extensions member....Sort declarations in dartdev.dart](https://github.com/dart-lang/sdk/compare/8aec705f6981f1279a2e2040c006a63d0d77f37d~...902f149e2c25926310b463a92891169f75024706).

The tests
```
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_sound_test RuntimeError (expected Pass)
pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_unsound_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
```

Log:
```
00:28 [32m+42[0m[31m -1[0m: (Sound null safety) (AMD module system) Expression compiler tests in global function: async method call [1m[31m[E][0m[0m

  Expected: <Instance of 'TestCompilationResult'> with `result`: match '_Future\.new[ ]*\{Symbol\(_state\):[ ]*1,[ ]*Symbol\(_resultOrListeners\):[ ]*null,[ ]*Symbol\(_zone\):[ ]*_RootZone[ ]*\{\}'
    Actual: <Instance of 'TestCompilationResult'>
     Which: has `result` with value '_Future.new {Symbol(_state): 2, Symbol(_resultOrListeners): null, Symbol(_zone): _RootZone {}}'
  

  package:test_api/src/expect/expect.dart 137:31                                       fail
  package:test_api/src/expect/expect.dart 132:3                                        _expect
  package:test_api/src/expect/expect.dart 46:3                                         expect
  pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_suite.dart 493:5   TestDriver.check
  ===== asynchronous gap ===========================
  pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_shared.dart 448:7  runSharedTests.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 199:9                                     Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 197:7                                     Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 257:7                                      Invoker._waitForOutstandingCallbacks.<fn>
  

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'pub run test --chain-stack-traces'.
```

https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/8/pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_sound_test
https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/8/pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_unsound_test

/cc @sigmundch @annagrin @stereotype441 @lrhn

**Comment by lrhn** [comment]
The test appears to be checking the state of private variables inside the `_Future` class against some "golden" state.
The state has changed because I changed the constant numbers used by the `int _state` variable.

The change was deliberate and not a bug, so the test failing suggests that the test is fragile against valid changes. It's checking that things don't change where we don't actually promise that they won't change. (That's the usual problem with "golden" tests including platform library internals, whether it's state or stack traces or class hierarchy structure.)

Please fix the test to not assume internals of platform classes.
Alternatively, and less convenient for everybody, have the test failure message provide a command line that can be run to update test-expectations.

**Comment by sigmundch** [comment]
Indeed we need to fix the test.

We are validating expression evaluation by inspecting the output of a JavaScript evaluation and it happens to leak implementation details at the moment.  So the intent in this case was not to have a golden test. For that reason, I would prefer making this test more flexible as opposed to having a process to auto update expectations.

Some options here:
* use a smaller match. For example, instead of matching the entire value `_Future.new {Symbol(_state): 2, Symbol(_resultOrListeners): null, Symbol(_zone): _RootZone {}}`, maybe we could match for a portion of the value, say looking for `_Future.new`?
* avoid inspecting internal object instances in the test entirely. For example, what if here we change the expression from `c.asyncMethod(2)` to `c.asyncMethod(2).runtimeType`?
* Later, once we have support for `await` in the expression compiler, then we can test the value of the awaited expression as opposed to the value of a future.

@Markzipan @annagrin - thoughts?

**Comment by Markzipan** [comment]
@sigmundch Agreed. The weird comparisons are due us not supporting await in eval. I can update the tests to check the runtime type since that's more reasonably stringified.
