### ISSUE TITLE
language/extension_methods/static_extension_internal_basename_shadowing_error_test

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46515]
```
static error failures:
- Unexpected error at line 212, column 5, length 15: COMPILE_TIME_ERROR.AMBIGUOUS_EXTENSION_MEMBER_ACCESS

- Unexpected error at line 216, column 5, length 15: COMPILE_TIME_ERROR.AMBIGUOUS_EXTENSION_MEMBER_ACCESS

- Unexpected error at line 220, column 5, length 15: COMPILE_TIME_ERROR.AMBIGUOUS_EXTENSION_MEMBER_ACCESS
```

It seems that we should not attempt to use extensions here, because there is a member with the requested basename in the extension.
![image](https://user-images.githubusercontent.com/384794/123887473-686df580-d906-11eb-883e-a144d66e86e2.png)

**Comment by eernstg** [comment]
> It seems that we should not attempt to use extensions here, because there 
> is a member with the requested basename in the extension

I think I would use slightly different words to describe the situation. At lines [212](https://github.com/dart-lang/sdk/blob/eb39128530e78898f6a7072dafce98c2d3de1de9/tests/language/extension_methods/static_extension_internal_basename_shadowing_error_test.dart#L212), 216, 220 in said test, the lexical lookup on the identifier `extensionSetter` yields `E6.extensionSetter`, which is a getter. The compile-time errors arise because that getter is used incorrectly (e.g., as a setter).

**Comment by scheglov** [comment]
My understanding is that we get `get extensionSetter`, which is an instance member, so we try to resolve `this.extensionSetter`.
![image](https://user-images.githubusercontent.com/384794/135676952-89e803e7-8e18-4d42-bf39-d4385628e0c7.png)

**Comment by eernstg** [comment]
We shouldn't need to talk about `this.extensionSetter`.

For the first occurrence of `extensionSetter` in line 212 the lexical lookup yields the `extensionSetter` declared in line 208 (that what I called `E6.extensionSetter`, and I believe that's the one you refer to as `get extensionSetter`), and then a compile-time error occurs because its name isn't `extensionSetter=`, and it isn't a local variable. (Intuitively, this means that we cannot use it as a setter, and that's what I meant by "is used incorrectly").

We're looking for `extensionSetter=` because that's how assignments work: https://github.com/dart-lang/language/blob/1696837c8010d1f9e9d21d8540e3535530306df3/specification/dartLangSpec.tex#L14924. The lookup for `extensionSetter=` will find any declaration named `extensionSetter=` as well as any declaration named `extensionSetter`; the latter is an error (except when the declaration is a local variable, because local variables can be the target of an assignment as well).

**Comment by scheglov** [comment]
Yes, I mean `E6.extensionSetter` that we get from the lexical lookup. The spec says "unless D is an instance member or...", so not only local variable. And `E6.extensionSetter` is an instance member.

**Comment by eernstg** [comment]
This is a tricky piece of terminology (maybe we could improve on it, but I haven't found a really good solution).

So we have 'extension instance members' and 'instance members'. We need to talk about 'extension instance members' because we also have `static` declarations in extensions. A phrase like 'instance member' may then seem to match a construct which is already known to be an 'X instance member' for any 'X'.

However, I believe that the language specification does have the word 'extension' at most a few words away from 'instance member' in all those cases where it should mean 'extension instance member', and this means that we should be able to trust a lone 'instance member' to mean an instance member of a class or mixin (that is, a member which is subject to object-oriented dispatch at run time).

The point is that we should _not_ prepend `this.` in the case where the lookup yields an extension instance member in an enclosing lexical scope, because this would imply that we ignore the extension instance member and attempt to invoke a member of the interface of `this` (that is, a class or mixin instance member), which may be an error (because there is no such member, or it has a different signature) or, worse, it may give rise to the wrong semantics.

As you can see [here](https://github.com/dart-lang/language/blob/1ecf6b7d6603c7db9b453feef4b6987ea2ffbb00/specification/dartLangSpec.tex#L16501), the intention is that the lexical lookup should yield the extension instance member when that's what we found when we searched the enclosing scopes.

**Comment by scheglov** [comment]
Thank you, now I understand.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/215581
