### ISSUE TITLE
language/generic/super_bounded_types_error_test

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46516]
I don't fully understand this area, but here is an issue to track this failing test.

**Comment by eernstg** [comment]
I looked at the failures: The behavior is underspecified in this case because it is an error-on-error situation (first we declare a parameter whose type is a compile-time error, and then we use that parameter in the body, and expect specific errors from that).

We don't generally test error-on-error situations. I'd expect a variable whose type is an error to get a "please ignore" type (perhaps some internal `ErrorType` or `dynamic`), and usages of that variable would then generally not give rise to further errors (that could very well be what we're seeing here). But we never specified this, so we could also get an error on _every_ usage of such variables, or some other behavior, and it wouldn't violate the specification.

So I simply deleted the code that gave rise to error-on-error, cf. https://dart-review.googlesource.com/c/sdk/+/205789.

**Comment by eernstg** [comment]
The test in the title now succeeds in all configurations.
