### ISSUE TITLE
Improvement for exceptions "Concurrent modification"

### ISSUE THREAD

**Issue by QiXi** [dart-lang/sdk#46554]
the following describes how the direction of collection iteration affects the writing of stable code

```
final Map<SocketId, GameClient> _clientById = {};
...
void disconnect() {
 for (var client in _clientById.values) {
  client.disconnect(false); // internal implementation calls _clientById.remove(element)  <-- Unhandled exception: Concurrent modification during iteration: _LinkedHashMap len:0.
 }
 ...
}
```

There are several ways to prevent the error "Concurrent modification".
I know the only way that does not use auxiliary collections. You need to go through the list in the opposite direction.

```
void disconnect() {
 for (var i = _clientById.length - 1; i >= 0; i--) {
 var client = _clientById.values.elementAt(i);
  client.disconnect(false); //<-- now the code is safe and has no errors
 }
}
```

we have to write a lot of code for a simple iteration in the opposite direction

I would like to be able to traverse in the same simple form as direct traversal and without generating additional collections
for example it could be like this
```
 forReverse (var client in _clientById.values) {
  ...
 }
```
or
```
 for (var client in _clientById.values.reverse) {
  ...
 }
```
or another 

this improvement is better viewed not from the point of view of convenience, but from the point of view of writing safe code

_special thanks for the "null safety" in the Dart_

**Comment by lrhn** [comment]
It's very easy to do wrong things if you remove from a collection while accessing it. You do need to be careful, there is no magic bullet to avoid that. The `ConcurrentModificationError` is there to help you, because the alternative is to just be in an inconsistent state.

You can also write `for (var i = 0; i < list.length; i++)  something(list[i]);`, and if `something` removes its argument from `list`, you're going to end up with a half-full list instead of an empty one. What the iterator does is to detect that something like that has likely happened, and stopping you before it gets worse.

The one thing Java does to make things slightly easier is to have a `remove()` method on the *iterator*. Not all iterables support it, but those which do can continue iterating if you remove through that iterator.
That won't help the example here where some other function does the remove, not the code doing the iteration.

Making iteration safe against removal (or addition!) on the side is practically impossible.
