### ISSUE TITLE
BigInt division results in NaN.

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/sdk#46578]
Try this:

```
var numerator = BigInt.parse("67982902423085023893660352721952935422197433021256315447220320013942048898802847423286428918430409980660007510060835815584499509086406011742556952113714718469172443301347888481483448534203116344634768517029137503367821031005284170881284354134977672012318226331475585450909214697062507388867816153941735593486739793794529696502248464518643199763431613003410764144118606712379714686852081");

var denominator = BigInt.parse("724792480468750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");

// This results in NaN.
var division = numerator / denominator;
```

The result should be `93.7963682779`.

**Comment by lrhn** [comment]
Give  NaN both on web and in the VM. That's deliberate, the behavior of `/` on Dart `BigInt` is to do `toDouble` on both operands, then divide the doubles (Same as `/` on `num`). 
Since both become positive infinity, you get the result of dividing infinity by infinity, which is NaN.
We should probably [*document*](https://api.flutter.dev/flutter/dart-core/BigInt/operator_divide.html) that behavior.

The JavaScript `BigInt` gives `93` when dividing, so does the Dart `~/` division. Integer division on big integers work. Double division on integers means converting to double.

**Comment by marcglasberg** [comment]
@lrhn Sorry, but could you please discuss this issue a little bit longer before closing it? 

1) If that's deemed correct behavior then, as you said, this issue must become documenting that behavior, which is very unexpected. Have you created a new issue for that? If not, I believe this issue should be reopened and changed to become a documentation fix. That's important.

2) Why is that deemed correct behavior? How you do the division is an **implementation detail**. The result fits a double, so it should be a valid double. Ideally when two `BigInt`s are divided it should result in a `BigFloat` class with infinite precision. But since that class doesn't exist, this division could be done some other way.

**Comment by lrhn** [comment]
Haven't filed anything yet, so it's a fine ide to reuse this issue for the documentation.

The behavior matches the behavior on "small" integers (`int`). When you do `0x7FFFFFFFFFFFFFFF / 2`, you don't get `0x3FFFFFFFFFFFFFFF` because the double division first converts the operands to doubles, then does the division on those. The result is the double with value 0x3FFFFFFFFFFFFE00.

Since Dart `BigInt` was the original implementation of `int` when Dart had arbitrary precision integers, it works exactly the same way.
It might be nice to get a precise (ish) double result, but it's not what how that has ever worked in Dart.

**Comment by marcglasberg** [comment]
It would be nice if one day Dart could have https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html and https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html equivalents.

Please note, the package https://pub.dev/packages/rational suffers from the fact the BigInts that form the numerator and denominator grow very large very fast, and then you can't even convert to double because of the limitation that BigInt division results in NaN.
