### ISSUE TITLE
remove unused code when building

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#46574]
* dart2js
Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"

I am making some tests and found out that unused code is still bundled in the JS.
In the example below the map ```{'some': 'test'}``` is still compiled and bundled in *main.dart.js* even thought it is not used within ```foo``` and is a simple constant.

```dart
void foo(Map<String, dynamic> bar) {
  print('foo called');
}

void main() {
  foo({'some': 'test'});
}
```

Is there any dart2js flag to make the map not be compiled?

My use case is that we have some conditional imports that when in HTML, some args are not used because we cache them in the server so they do not increase the JS file size.

**Comment by lrhn** [comment]
Should be possible, not necessarily trivial. 
It requires the compiler to recognize that the function you call definitely doesn't use its argument (which requires knowing the function at compile-time, so probably not instance methods), and that the argument expression definitely has no side effects, and that it's possible to find some smaller/simpler value that can be used as argument instead.

Here it looks simple, it's a static function call to a function not using its argument, and the argument is a map literal containing only literal strings. The big question is how many argument expressions can be *definitely* guaranteed to not be able to throw. My guess is that it's only expressions which could potentially be constant instead.

**Comment by alanknight-wk** [comment]
Intl does something similar with the examples parameter to e.g. `Intl.plural`, and I believe it does get optimized away. But perhaps only if it is const. And I think part of it is that the equivalent looks kind of like

```
void foo(Map<String, dynamic> bar) {
  _foo();
}
```

**Comment by jodinathan** [comment]
yes, it worked by adding const to the map on calling.
It also worked with our complex tests using futures by removing the ```async``` from the method.
so ```void foo(Map<String, dynamic> bar) async => _foo()``` does not remove the unused argument ```bar```.

is it possible for this to happen without having to add ```const``` to the calls?
or somehow make the method signature asks for a const map?

**Comment by sigmundch** [comment]
Unfortunately there is no way to request parameters to be marked as constant in the language, however, it may be possible for you to create a custom linter to serve that purpose.

Indeed, `Intl.plural` was given a constant map as argument.

I believe why your example and Intl.plural worked out was because a combination of method inlining and constnats. dart2js inlined the call to `foo` (which it can't do for async methods) then local optimizations removed the use of the constant (which we know has no side-effects).

To make things work `async`, you could try to add some indirection. For example, we can inline a non-async method that returns a future:

```dart
Future<X> foo(Map bar) => _foo(); // `foo` can be inlined, even though `_foo` cannot.
Future<X> _foo() async => ...
```

Note that dart2js does have an optimization to determine whether fields and parameters can be elided in the output, but those have not been at play here.

The optimization for fields is quite sophisticated. Fields get analyzed to see if their values are never read and their initializers are constant-like, and hence don't have side-effects. Something being constant-like is limited to some degree, for example we don't consider map literals today.

The optimization for parameters is much simpler. Parameters are only elided today if they were originally optional and a value was never provided at any call site in the entire program. This was done to reduce the cost of parameters, though.

In your case, since the calls can be inlined (hopefully with the suggested indirection), then maybe it is enough to improve the local optimizations to recognize and remove unused expressions that have no side-effects.
