### ISSUE TITLE
[dart2js] const maps do not respect non-terminating hashCodes

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#46580]
@lrhn came up with this example while discussing https://github.com/dart-lang/sdk/issues/45908.

```dart
class Nasty {
  final int n;

  const Nasty(this.n);

  int get hashCode {
    while (true) {}
  }
}

final map = const {1: 42, 'foo': 499, 2: 'bar', Nasty(1): 'baz'};

Expect.isNull(map[getValueNonOptimized(Nasty(1))]);
Expect.equals('baz', map[getValueNonOptimized(const Nasty(1))]);
```

I added a test case exercising is, which makes the tests not terminate on dart2js.

Map and Set constants should use `hashCode` for int, double, String, Symbol, and Type, but `identityHashCode` for Object.

See https://dart-review.googlesource.com/c/sdk/+/206085

**Comment by dcharkes** [comment]
cc @rakudrama

**Comment by lrhn** [comment]
The underlying rules here are that:
* You can use an object in a const set or map if it has primitive equality, which means being one of a handful of system classes or not overriding `Object.==`. No restriction on overriding `hashCode`. That's what the spec says.
* Creating a const set/map should not call any user code (so no calling user `hashCode`). That's what it means being `const`, no possible side effects.
* Constant map/set lookup should use equality (otherwise it doesn't work for `Symbol` and `Type` entries), and should definitely find the values themselves (so looking up `const Nasty(1)` should be successful).

Together that means that run-time lookup in a const map/set cannot depend on the object's hashCode (unless it's on of the system classes, then it's OK), and therefore should not call it.

**Comment by rakudrama** [comment]
The dart2js `GeneralConstantMap` should use a custom map as a backing map to implement a 'mostly-`identityHashCode`' lookup.

The constant maps in js_runtime could do with a bit of maintenance, so I'll take a look.
