### ISSUE TITLE
how to close periodic stream

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#46595]
```dart
var s3 = Stream.periodic(Duration(seconds: 1), (a) {
    return a;
  });
  s3.asBroadcastStream().listen((event) {print(event);});
```

s3 is always open for receive data.
receivePort can close, but stream has not the method.

**Comment by RatakondalaArun** [comment]
Hello @Silentdoer 

Basically, [`.listen`](https://api.dart.dev/stable/2.13.3/dart-async/Stream/listen.html) methods return a [`StreamSubscription`](https://api.dart.dev/stable/2.13.3/dart-async/StreamSubscription-class.html) which you can use to control [Stream]

```dart
var s3 = Stream.periodic(Duration(seconds: 1), (a) {
    return a;
  });
  /// .listen method returns StreamSubscription which you can use to control the stream
  StreamSubscription sub = s3.asBroadcastStream().listen((event) {
    print(event);
  });
  await sub.cancel(); //when your are done with stream cancel it

```

You can checkout docs for more

[Stream.listen](https://api.dart.dev/stable/2.13.3/dart-async/Stream/listen.html)
[StreamSubscriptison](https://api.dart.dev/stable/2.13.3/dart-async/StreamSubscription-class.html#instance-methods)

**Comment by Silentdoer** [comment]
> 
> 
> Hello @Silentdoer
> 
> Basically, [`.listen`](https://api.dart.dev/stable/2.13.3/dart-async/Stream/listen.html) methods return a [`StreamSubscription`](https://api.dart.dev/stable/2.13.3/dart-async/StreamSubscription-class.html) which you can use to control [Stream]
> 
> ```dart
> var s3 = Stream.periodic(Duration(seconds: 1), (a) {
>     return a;
>   });
>   /// .listen method returns StreamSubscription which you can use to control the stream
>   StreamSubscription sub = s3.asBroadcastStream().listen((event) {
>     print(event);
>   });
>   await sub.cancel(); //when your are done with stream cancel it
> ```
> 
> You can checkout docs for more
> 
> [Stream.listen](https://api.dart.dev/stable/2.13.3/dart-async/Stream/listen.html)
> [StreamSubscriptison](https://api.dart.dev/stable/2.13.3/dart-async/StreamSubscription-class.html#instance-methods)

if stream is broadcast, cancel sub will not close stream ..

**Comment by RatakondalaArun** [comment]
@Silentdoer Sorry got it wrong



I checked it on my machine with this code.

```dart
  final s3 = Stream.periodic(Duration(seconds: 1), (v) => v);
  final sub = s3.asBroadcastStream().listen((v) => print('v: $v'));
  await Future.delayed(Duration(seconds: 5));
  await sub.cancel();
  print('closed');
```

After Running this Dart VM is still running after canceling the subscription.

```bash
$ dart test.dart
v: 0
v: 1
v: 2
v: 3
v: 4
closed
```

**Comment by lrhn** [comment]
Don't use `asBroadcastStream` indiscriminately. It's dangerous *because* it doesn't give you an easy way to close the stream.
The problem here is not the periodic stream, but the `asBroadcastStream` wrapper.

It does give you a way to stop it, though. The [optional callback paramters](https://api.dart.dev/stable/2.13.4/dart-async/Stream/asBroadcastStream.html) you can pass to `asBroadcastStream` gets called when the broadcast stream gets its first listener, or when its last listener stops listening. The callbacks get a synthetic subscription that can be used to pause or cancel the original underlying single-stream subscription. If you want to cancel an `asBroadcastStream`, you need to do it in one of those callbacks.

**Comment by Silentdoer** [comment]
OK, thank you for your anwser
