### ISSUE TITLE
Mark classes as sendable through a SendPort on the Dart Native platform for analysis

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/sdk#46660]
According to the documentation in [`SendPort.send`](https://api.dart.dev/stable/dart-isolate/SendPort/send.html):

> The content of message can be: primitive values (null, num, bool, double, String), instances of SendPort, and lists and maps whose elements are any of these. List and maps are also allowed to contain cyclic references.
> 
> In the special circumstances when two isolates share the same code and are running in the same process (e.g. isolates created via Isolate.spawn), it is also possible to send object instances (which would be copied in the process). This is currently only supported by the Dart Native platform.

Objects can be sent on the Dart Native platform if they're made up of primitive values. If other things (like `Stream`s, `Future`s, and `File`s) are in the object, it will fail to send.

It'd be great if there was an annotation (perhaps in the meta package) to assert that a class contains only primitive values and other objects with the same requirements. This would also be useful for serialization as well, as formats like JSON usually have the same requirements.

For example:

```dart
@primitive
class MyClass {
  int myInt;
  String myString;
  File myFile; // Analysis would complain here because File is not a "primitive" class.
}
```

**Comment by mit-mit** [comment]
cc @mkustermann @lrhn

**Comment by lrhn** [comment]
The distinction is not between "primitive" and, ... well, "not primitive". The main restriction is that you can't send *closures*, and likely not something which contains native pointers, unless specifically handled.

Whether something contains closures is non-trivial to figure out (a `Future` seems fine until you listen to it, if it wasn't because it currently contains a `Zone`, and a zone contains zone callbacks which are closures. The `Future`'s zone is something I've tried to get rid of a few times, and might eventually succeed at, and then you can send the future - again, at least until you give it a listener).
A `Queue` can be sent, but probably not if it's a `Queue<Function>`, at least not unless it's empty. 

Stating, for each platform class, whether it can be sent, is non-trivial. We'd at least need some kind of annotation that accounts for type variables (a `Queue` can be sent if its elements can). It would be pessimistic (some objects might sometime be sendable, and not at other times, but the entire class must be marked non-sendable).

More importantly, being sendable/non-sendable is a property of the implementation of a class, not its interface, so even if we annotate `Foo` as sendable, a `SpecialFoo extends Foo` might not be, and vice versa. That makes it a property not very well suited to being annotated on the API.

**Comment by hacker1024** [comment]
> More importantly, being sendable/non-sendable is a property of the implementation of a class, not its interface, so even if we annotate Foo as sendable, a SpecialFoo extends Foo might not be, and vice versa. That makes it a property not very well suited to being annotated on the API.

I was thinking of something more similar to the way the immutable annotation works: If a superclass is annotated, subclasses/implementations should also be, and the linter will complain if they're not.

**Comment by lrhn** [comment]
The VM has improved their ability to send objects across isolates, so now very few values cannot be sent.
I don't think we need to worry about this as much any more.
(I believe there are still a few restrictions, but I'm entirely sure what they are).
