### ISSUE TITLE
Isolate.kill() doesn't kill inifinite loop in dart:ffi code

### ISSUE THREAD

**Issue by easeccy** [dart-lang/sdk#46680]
There is a blocking infinite loop ([`CFRunLoopRun()`](https://developer.apple.com/documentation/corefoundation/1542011-cfrunlooprun)) running in the C code. In order to keep main isolate from blocking, loop code is called from the second isolate. Instead of implementing a `stop()` in the native code and calling it through the ffi, I wanted to kill the second isolate directly but it doesn't work.

Is it a bug that calling `kill()` on the second isolate doesn't stop the loop and isolate keeps living?

**Comment by rmacnak-google** [comment]
`Isolate.kill` is not expected to work if the target isolate is blocked in foreign code. It can only interrupt Dart code.

Nesting another event loop such as a `CFRunLoop` on a Dart thread is a bad idea. If you want to run another event loop, either
 - it should run on its own thread and communicate with Dart via message passing (`Dart_PostCObject`), or
 - the Dart isolate should be set up to run under the foreign event loop (`Dart_SetMessageNotifyCallback`) instead of the VM's default event loop.

**Comment by easeccy** [comment]
What are the differences between communicating with `Dart_PostCObject` and callbacks (function pointers)?
