### ISSUE TITLE
Specification parser doesn't report error if default value is specified for an optional parameter of typedef

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46688]
Specification parser doesn't report error if default value is specified for an optional parameter of typedef. For example
```dart
typedef void F1(String s = "");               //# Spec parser reports syntax error here
typedef String F2(String s, int i = -1);      //# Spec parser reports syntax error here
typedef int F3(String s, [int i = -1]);       //# No error in spec parser, compile time error
typedef F4(String s, {int i = -1});           //# No error in spec parser, compile time error
```

cc @eernstg

**Comment by eernstg** [comment]
This is OK: It is a compile-time error which is [specified independently](https://github.com/dart-lang/language/blob/450634924aba1cc2d61e2d3e4051f9a99deb8f2b/specification/dartLangSpec.tex#L20311) of the grammar rules that we can't have a default value for those formal parameters, the grammar just says that a `<functionTypeAlias>` contains a `<formalParameterPart>`, which is the same non-terminal that we're using in function declarations. So the default value on a required positional parameter is a syntax error because the same thing is a syntax error in a function declaration, and the default value on the optional positional parameter is a compile-time error which is not a syntax error. I think we can then close this issue.
