### ISSUE TITLE
misleading (erroneous?) diagnostic message

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#46712]
**Describe the issue**
- lint message is misleading (erroneous?)

  ![image](https://user-images.githubusercontent.com/52100648/126873943-754479e1-e5bd-47db-85f2-47e13a7af95a.png)

**To Reproduce**
- any `typedef` statement with your dart SDK (`beta`) requirements set to
  ```
  environment:
    sdk: '>=2.12.0 <3.0.0'
  ```

**Expected behavior**
- mentioning that the required version is `>=1.13.0` and not `>=1.14.0` as noted on your [medium announcement](https://medium.com/dartlang/announcing-dart-2-13-c6d547b57067)

>The type alias feature is available starting with Dart 2.13. To enable it, set the lower Dart SDK constraint in your pubspec to at least 2.13:
>
>   ```
>   environment:
>     sdk: '>=2.13.0 <3.0.0'
>   ```

**Notes**
- It's not that much of an issue. It was super annoying that I had to mess around with the minversion for a couple of minutes since I'm on `2.14.0-301.2.beta` and was offline.
- I'm not sure if this is the correct repo to file this issue, if it isn't, I'm sorry, please direct me to the right place.

**Comment by srawlins** [comment]
> any typedef statement with your dart SDK requirements set to

Can you give an example? I cannot reproduce with a pubspec constraint as you say, and the following Dart file:

```dart
$ cat a.dart 
typedef Cb = void Function();
srawlins-macbookpro:dart-mockito srawlins$ dart analyze a.dart 
Analyzing a.dart...                    0.7s
No issues found!
```

**Comment by eernstg** [comment]
The error is probably reported because the type alias uses the `nonfunction-type-aliases` feature which was enabled in 2.13, which means that it is an error in a context where the language level is 2.12. (That is, the type alias has the form `typedef F = ...;` or `typedef F<...> = ...;` where the right hand side is a type which is not a function type.)

> **Expected behavior**
> - mentioning that the required version is >=1.13.0 and not >=1.14.0

I don't know why the error message suggests using an SDK lower bound of 2.14.0. It may be a bug (where this feature is assumed to be enabled in Dart 2.14 rather than Dart 2.13), or it may be a standard approach (suggesting that the lower bound is updated to the most recent language version supported by the tools).

**Comment by MikhailZex** [comment]
The issue occurs or the `beta` channel. Doesn't occur on `stable`

**Comment by srawlins** [comment]
The message I see now is:

> Try updating your pubspec.yaml to set the minimum SDK constraint to 2.13.0 or higher, and running 'pub get'.
