### ISSUE TITLE
pow(double, double) does not return a double, but a num

### ISSUE THREAD

**Issue by gemma-gaspa** [dart-lang/sdk#46744]
By doc (https://api.dart.dev/stable/2.13.4/dart-math/pow.html), pow function should return double, not num.

The following code does not compile:

```
import 'dart:math';

void main() {
  double a = 2.2;
  double b = 3.3;

  double c = pow(a, b);
}
```

Platforms:
$> dart --version
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "windows_x64"

Also on DartPad.dev

Thanks.

**Comment by lrhn** [comment]
It does return a `double`. 
The *static type* of the function is `num Function(num, num)`, which is why you can call it with both doubles and integers, and get both doubles and integers as results. Since a `double` is a `num`, the typing is correct, but you can no longer simply assing something with static type `num` to `double`.

Prior to null safety, you'd get a free implicit downcast from `num` to `double` here (and it would succeed). With null safety, you have to write `var c = pow(a, b) as double;` to make the downcast explicit.

We have a few special cases in the language specification to make operations on numbers statically have a better type, but those special cases are only on methods and operators of `int` and `double`, not the functions of `dart:math`.

So, all in all, working as intended.

**Comment by gemma-gaspa** [comment]
Thank you very much, @lrhn .
