### ISSUE TITLE
Dart fix applies ~1000 import statements

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#46791]
While writing a dart fix ([`fix_data.yaml`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/fix_data.yaml)) for flutter/flutter, I found that adding an import statement resulted in about 1000 when tested. 🙃 

There is an example in this PR: https://github.com/flutter/flutter/pull/86382
This is the output of running the fixes added in that PR:  [output.txt](https://github.com/dart-lang/sdk/files/6919941/output.txt)

It is strange because we have other fixes that add import statements, search `FloatingLabelBehavior` [here](https://github.com/flutter/flutter/blob/37c414dd8e6e9196a4a32a2e5af70a5cdede4660/packages/flutter/lib/fix_data.yaml#L1671). These other import related fixes do not appear to have this issue. 

cc @bwilkerson

**Comment by bwilkerson** [comment]
All of the other fixes that use `kind: 'import'` have the URL `material.dart`. My first guess is that `material.dart` is already imported (at least in all the test cases) and that it correctly skips adding an import if there's already one there, but that it's failing when it isn't yet imported because it doesn't recognize that the import has already been added by a previous fix.

**Comment by bwilkerson** [comment]
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/208920 and should roll into Flutter with the next roll.

For the record, I was wrong. The problem was that the code that generates the import statements is expected to be executed exactly once at the end, but it ended up being executed multiple times because of the way in which we were comparing to see whether a given fix had produced any edits.

**Comment by Piinks** [comment]
Thank you @bwilkerson! :)
