### ISSUE TITLE
[Analyzer] Classes in ignored files not picked up for import suggestions

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#46817]
Not sure if the following is an issue with the Dart Analyzer, an issue with the Dart IDE plugin or intended behavior. 

When defining your own `analysis_options.yaml` file,
including an `exclude` block prevents classes
in one of the excluded files from appearing in the import suggestions.

Example:

I have an excluded file `some_generated_file.dart` in `lib/generated/` which generates a given class, i.e. `SomeGeneratedClass`.
Due to unwanted linter warnings, I exclude this file from analysis:

```
analyzer:
  exclude:
    - lib/generated/some_generated_file.dart
```

Now, since this file is ignored, if I ever want to use `SomeGeneratedClass`,
I have to type the import manually, since the class is not 'found' by the IDE plugin's code suggestions.
(the classic lightbulb icon)

Is this intended? I'd assume that the code suggestions take their input from the analyzer,
hence the class is not found in this case (it ignores it).

However this behavior would be a (mild) inconvenience for developers that work with generated code
(and want a custom linter / analyzer setup).

Personally I used a workaround where another - not excluded - file, does an `export` of the file of the class I need.

Dart SDK version: 2.13.4, running on Mac.
Using VSCode version 1.58.2, with version 3.25.1 of the Dart plugin.

**Comment by bwilkerson** [comment]
I'd have to spend some time digging into it to be sure, but I suspect that completion suggestions are not found for the reason you proposed: the library isn't analyzed because of being excluded. However, that should only be true when the library isn't referenced from anywhere else. If you add an import for the library in at least one non-excluded file then the analyzer will still have analyzed it and completion should be able to see it.

I don't think that it was an intentional decision to not display elements from excluded libraries in the completion suggestions; I think it was an unfortunate side-effect of what 'excluded' means. There has been some internal discussions about providing greater control over what gets analyzed and for what purpose, and this is a definitely a use case that should be considered. @devoncarew @pq

**Comment by devoncarew** [comment]
Analyzer excludes are really a means to prevent some sources files from participating in analysis with the rest of the project. The behavior you're hitting above is likely a result of that.

Instead of excluding the files you might try adjusting the generator so that the generated source doesn't run afoul of the lints, or, generates the source with some appropriate 'ignore_for_file:' comments at the top.

As Brian says, we're also looking into ways you can configure lints for a subset of your project.

**Comment by bwilkerson** [comment]
> ... we're also looking into ways you can configure lints for a subset of your project.

I'm thinking that we might want to broaden the scope of those discussions. I think we originally added `exclude` to block reporting of (all) diagnostics, but we implemented it by not analyzing the files. I'm wondering whether we should implement that support differently so that analysis is still done and available to code completion and whether there are other side-effects of `exclude` that we'd need to have separate support for if we did that.

**Comment by navaronbracke** [comment]
@devoncarew Sadly I do not have control over the generation of said file (as it is done by a plugin). Therefore adding `ignore_for_file` for each lint that is not respected isn't really an option as each time that file changes I'd have to add the ignores again.

@bwilkerson I indeed used a simple `export 'package:mypackage/path/to/file.dart'` in another file that is not excluded from the analysis. Then it works as expected, although it is not ideal.

And yes, I think that separating the analysis and the code completion is a viable option.

**Comment by navaronbracke** [comment]
@bwilkerson Just noticed that it started to work today? We recently upgraded to Flutter 2.10.2 so that might have solved it. Imports are suggested for a file that is under the 
```
analyzer:
  exclude:
```
section

Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"

**Comment by bwilkerson** [comment]
Yes, it's likely that the upgrade included the fix. Glad it's working for you!
