### ISSUE TITLE
Bad error message when using @required in null safe code

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#46841]
When grabbing code snippets from the pre-null safety days and pasting them into a null safe app, there is often code that uses `@required`. That produces a very hard to read error:

```dart
class BooksListScreen extends StatelessWidget {
  final List<Book> books;
  final ValueChanged<Book> onTapped;

  BooksListScreen({
    @required this.books,
    @required this.onTapped,
  });
...
```

<img width="814" alt="Screenshot 2021-08-06 at 17 30 00" src="https://user-images.githubusercontent.com/13644170/128534944-4ca5c861-262a-4e15-a3a2-adcd58b452ad.png">

Could we not just say something like "Error: With null safety use the `required` keyword, not `@required`" ?

**Comment by bwilkerson** [comment]
Yes, we could look to see whether the `required` annotation is being used and adjust the message accordingly.

I'm not arguing against doing so, but I'll just note that the longer we wait to do this the less value there presumably is because it seems likely that the frequency with which users paste legacy code into a null safe library is likely to decrease over time. In fact, this could be seen as an argument for increasing the priority of making the change.

If we had a "smart paste" feature we could remove the `@` for the user and avoid the message altogether, but that's a much bigger arc of work and isn't likely to be scheduled anytime soon. (But I can dream.)

**Comment by devoncarew** [comment]
In terms of emitting a more targeted message for this (`With null safety use the required keyword, not @required`), would this be looking for the `@required` annotation on the param when we generating the message? Or would we want to customize the suggested fix message?

**Comment by bwilkerson** [comment]
I believe the request requires "looking for the `@required` annotation on the param when we generating the message".

> Or would we want to customize the suggested fix message?

I'm not sure what fix message you're referring to, so I don't know whether the message should be customized. If we don't have a fix to convert from the annotation to the keyword we should definitely consider adding one.

**Comment by devoncarew** [comment]
I mean the 'Try adding either an explicit non-null...' message.

**Comment by bwilkerson** [comment]
Ok, yes. (I call that the _correction_ message to disambiguate.) Yes, when we create a new error code for this case we'd want to fix the correction message as well (it's part of the definition of the error code).

**Comment by mit-mit** [comment]
I'd really like to see this fixed; is this a lot of work?
