### ISSUE TITLE
Template type has to be typecast to Object?

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/sdk#46854]
#  Why does `_delegate` have to be typecast to `Object`?

Sample code for https://dartpad.dev, based on Flutter 2.2.3 Dart SDK 2.13.4

```dart
import 'package:meta/meta.dart';
import 'package:js/js_util.dart' as js_util;

void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
  }
}

abstract class Delegate<T> {
  final T _delegate;

  T get delegate => _delegate;

  Delegate(this._delegate);

//   T getProperty<T>(dynamic name) => js_util.getProperty(_delegate, name);
  T getProperty<T>(dynamic name) => js_util.getProperty(_delegate as Object, name);

//   T callMethod<T>(String method, List args) => js_util.callMethod(_delegate, method, args);
  T callMethod<T>(String method, List args) => js_util.callMethod(_delegate as Object, method, args);
}
```

# Same code used to work

https://github.com/woodemi/notepad_core/blob/b0e329f3d6e02f14f8a0e5e48a6ddb48e026b658/notepad_core_web/lib/js_facade.dart#L23-L33

```dart
abstract class Delegate<T> {
  final T _delegate;

  T get delegate => _delegate;

  Delegate(this._delegate);

  T getProperty<T>(dynamic name) => js_util.getProperty(_delegate, name);

  T callMethod<T>(String method, List args) => js_util.callMethod(_delegate, method, args);
}
```

**Comment by lrhn** [comment]
You don't say what happens if you don't. I'm *guessing* you get an analyzer error for having an implicit downcast.

This is likely a result of migrating to null safety.
The argument type of `getProperty` is `Object`, so you can't pass `null` to it. 
Since `dynamic` can contain `null`, the call `js_util.getProperty(_delegate, name)` needs to insert a down-cast to `Object` on the `_delegate`. The compiler should automatically insert that down cast, making it `js_util.getProperty(_delegate as Object, name)`, because the language provides implicit downcasts from `dynamic` to any type.

If you have put `implicit-casts: false` in your `analysis_options.yaml` file, you'll get an error from that implicit downcast. 
With null safety, the only implicit down-casts are from `dynamic`, so you could consider removing the analysis options flag.

It used to work because before null safety, assignment from `dynamic` to (then nullable) `Object` was not a downcast. Assigning to the nullable `Object` is a downcast, and therefore hits the analyzer restriction on downcasts that you've added.

**Comment by Sunbreak** [comment]
> This is likely a result of migrating to null safety.
> The argument type of `getProperty` is `Object`, so you can't pass `null` to it.

I suppose so. So could we declare a non-nullable argument type?

> Since `dynamic` can contain `null`, the call `js_util.getProperty(_delegate, name)` needs to insert a down-cast to `Object` on the `_delegate`. The compiler should automatically insert that down cast, making it `js_util.getProperty(_delegate as Object, name)`, because the language provides implicit downcasts from `dynamic` to any type.

The parameter `name` is meant to be `dynamic`, but the `T` type of `_delegate` is not meant to be.

**Comment by lrhn** [comment]
You can declare `T` as `abstract class Delegate<T extends Object> {`, then it can't be nullable, and whatever its type is, it's assignable to `Object`.

**Comment by vsmenon** [comment]
Closing as I don't believe there is a bug report or feature request here.

You may want to use:
https://dart.dev/community#join-the-conversation

for general discussion / questions.

**Comment by Sunbreak** [comment]
I was implementing https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition with `Delegate` and found a related issue: https://github.com/dart-lang/sdk/issues/46868
