### ISSUE TITLE
optimize Double.toInt (and other similar functions) in AOT 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#46876]
There is currently no way to coach AOT compiler into producing good inlined fast path for double to integer conversion in AOT. In JIT we at least attempt to generate `DoubleToSmi`, but this instruction is not suitable for AOT because it has a deopt inside. IL has a more generic instruction (`DoubleToInteger`), but it calls Dart code on the slow path and requires boxed input. 

I think we should do the following: 

- introduce a `DoubleToInteger` stub (which handles corner cases and throwing) which takes unboxed input;
- change `DoubleToInteger` to call stub on the slow path instead of Dart code and change required input representation to be unboxed;
- change call specializer to emit `DoubleToInteger` in AOT when lowering `toInt`.

We should review other similar functions (e.g `truncate`) and make sure that AOT lowers them into something that does not require boxing and tries to avoid calls on the fast path.

**Comment by mraleph** [comment]
@alexmarkov tentatively assigned to you because you are already looking at this code right now.

**Comment by alexmarkov** [comment]
@mraleph Thank you for writing this up. I plan to do this while optimizing `double.floor()` in AOT mode (https://github.com/dart-lang/sdk/issues/46650). In addition to the list above, I think it also makes sense to do the following:

- Add kind of conversion to `DoubleToInteger` (similarly to `DoubleToDouble`) in order to support all double->int conversions with the same IL instruction.
- Replace call specializer code and intrinsics with a flow-graph generated in FlowGraphBuilder::BuildGraphOfRecognizedMethod.
- Check if `DoubleToSmi` instruction can be replaced with a new `DoubleToInteger` and maybe remove `DoubleToSmi`.

**Comment by alexmarkov** [comment]
Although code generated for `DoubleToInteger` instruction is now similar to `DoubleToSmi`, removing `DoubleToSmi` regresses `MicroMath.ToInt.Easy` benchmark. Kernel of the benchmark:

```dart
    for (int i = 0; i < a.length; i++) {
      intSink[0] = a[i].toInt();
    }
```
Regression happens because result of `DoubleToSmi` is guaranteed to be a Smi and `StoreIndexed` stores the result of `DoubleToSmi` can omit write barrier code:
```
        ;; StoreIndexed:38(v36, v16, v19, NoStoreBarrier)
0x88    4d894817               movq [r8+0x17],r9
```

`DoubleToInteger` can return Mint, so subsequent `StoreIndexed` is generated in a less efficient way:
```
        ;; StoreIndexed:38(v36, v16, v46 T{int})
0x8b    4c8d6a17               leaq r13,[rdx+0x17]
0x8f    49894500               movq [r13+0],rax
0x93    a801                   test al,1
0x95    7419                   jz +27
0x97    448a5aff               movb r11,[rdx-0x1]
0x9b    41c1eb02               shrl r11,2
0x9f    45235e48               andl r11,[thr+0x48]
0xa3    448458ff               testb r11,[rax-0x1]
0xa7    7407                   jz +9
0xa9    41ff9610020000         call [thr+0x210]
```

This micro-benchmark shows that in certain cases it might be more efficient to stay in the Smi range in JIT code, even if we have an equivalent non-speculative instruction which can return int. So I'm going to leave `DoubleToSmi` as is.
