### ISSUE TITLE
[CP][beta channel] Please merge 7ad9feb2d6dd3814d0e2bf738c1403e123e00135 into the 2.14 beta branch

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#46870]
commit(s) to merge: 7ad9feb2d6dd3814d0e2bf738c1403e123e00135

merge instructions: clean merge into the beta branch at Version 2.14.0-377.4.beta

What is the issue: After adding static methods hash, hasAll and hashAllUnordered to the Object class, the analyzer treats them as static members of dynamic when you try to tear something of that name off from dynamic. This results in errors from the Analyzer which are confusing.

What is the fix: The analyzer does not resolve to static Object members via dynamic. 

Why cherrypick: This is a regression from earlier behavior as static methods hash, hasAll and hashAllUnordered have been added to the Object class,

Risk: Once the change rolls into Google3 and is verified the risk should be low.

Link to original issue(s): #46472

This will be considered for cherry pick in the next cherry pick window for Flutter 2.5/Dart 2.14

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @devoncarew @scheglov

**Comment by vsmenon** [comment]
approved

**Comment by athomas** [comment]
Merged to beta in 9a1827339c8e4e55a9b214d033aeba7d30daa28f (2.14.0-377.7.beta).

**Comment by whesse** [comment]
This cherry pick was not clean, because the added tests depend on the rename of isNullSafetySdkAndLegacyLibrary in https://dart-review.googlesource.com/c/sdk/+/209520

The impact is that the test pkg/analyzer/test/src/dart/resolution/property_access_test fails, and the analyzer test that analyzes that directory also fails.

I suppose a fix for this should be added as a new CP request, but only landed if other CPs are necessary.

**Comment by a-siva** [comment]
//cc @scheglov regarding comment from @whesse above do we need a new CP or is the failing test ok ?

**Comment by scheglov** [comment]
I think it is OK to let this test to fail, because we test it in the master, but if we are to add any more changes to the functionality, we would have to patch tests as well.
