### ISSUE TITLE
firstWhere can not return nullable result?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/sdk#46901]
why this statement is not allowed:
```dart
TaskWrapper<dynamic>? taskWrapper =
              _tasks.firstWhere((element) => element.status == TaskStatus.idle, orElse: () => null);
```
E is `TaskWrapper<dynamic>?`
so, orElse should be able to return null

**Comment by lrhn** [comment]
Most likely because the type of `_tasks` is `Iterable<X>` where `X` is not nullable, and the type of `firstWhere`'s `orElse` parameter is then `X Function()`. (So, `E` is not `TaskWrapper<dynamic>?` for the iterable that `firstWhere` is being called on, it's probably just `TaskWrapper<dynamic>`).

The `firstWhere` has to return something which has the same type as the element type of the iterable it's called on, so you can't return `null` as an alternative.

Try using [`firstWhereOrNull`](https://pub.dev/documentation/collection/latest/collection/IterableExtension/firstWhereOrNull.html) from `package:collection` instead..

**Comment by Silentdoer** [comment]
oh, i got it, thanks.
