### ISSUE TITLE
Comparing nonnull types to null should be an error

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#46907]
**Code:**
```dart
void bar() {
  const int foo = 1234;
  if (foo == null) {
    print(foo);
  }
}
```

**Observed behavior:** Code compiles and runs fine.

**Expected behavior:** The comparison between a nonnull type and null should be a compilation error or a linter error.

**Notes:**
This not being an error can make transitioning to nullable types difficult, especially when transitioning collection datatypes.  I had to transition all `list == null` to `list.isEmpty` and got no help from the compiler.

**Comment by vsmenon** [comment]
@lrhn @eernstg @pq - should we consider this a language issue or a lint?

**Comment by Levi-Lesches** [comment]
> **Expected behavior:** The comparison between a nonnull type and null should be a compilation error or a linter error.

I _do_ get a lint: [`unnecessary_null_comparison`](https://dart.dev/tools/diagnostic-messages#unnecessary_null_comparison)

![image](https://user-images.githubusercontent.com/20747538/129468250-92954d68-9a34-44af-9fc3-2bfb09c6eedd.png)

**Comment by stuartmorgan** [comment]
Looks like Flutter has this lint turned off while we're still officially supporting mixed-mode code: https://github.com/flutter/flutter/blob/master/analysis_options.yaml#L39-L40

**Comment by lrhn** [comment]
The analyzer already gives an "info" for this:
```
line 3 • The operand can't be null, so the condition is always false. (view docs)
Try removing the condition, an enclosing condition, or the whole conditional statement.
```
(Checked on dartpad.dev).

We could consider a language feature. The language special-cases `null` in `==` operator evaluation, so doing something about it statically would be consistent.

We have warnings when you do `x?.foo` and `x` is not nullable, and that's effectively `let tmp = x in x == null ? null : x.foo`.
The only thing standing out in the expansion (other than the inline `let` that isn't valid Dart syntax) is the `x == null` comparison being unnecessary.
So, maybe we should also warn if you do `x == null` on a non-nullable expression directly. It *looks* like you're trying to do a promotion, and it .... looks like it succeeds, but one branch is going to be dead code.

It's probably still only going to be the analyzer giving the warning, so not sure how big a difference it makes.

**Comment by Levi-Lesches** [comment]
If the only added value is just bumping it from a lint to a warning, that can be done in `analysis_options.yaml`.

**Comment by eernstg** [comment]
I think it might be a _hint_. It is unlikely that we'd encounter a situation where `eWithNonnullableType == null` serves a useful purpose, the developer should just write `false` if that's what they want.

It doesn't fit as well as a lint if we really think there are no false positives: There is no good reason to make it optional, and that just causes more work for all those developers who need to remember to enable the lint.

It doesn't fit very well as a warning or as an error, because the construct doesn't incur a danger of failing at run time and doesn't prevent compilation of the program. There's nothing wrong with computing the value `false`, we just think this particular syntax is confusing for that purpose.

**Comment by lrhn** [comment]
I actually think that description fits what I'd use for warnings (if I wanted to have warnings at all, which I don't).
It's not *wrong*, but it's also *probably* not what you wanted to write. So, it's code which has an overwhelmingly high risk of being a mistake, while still having a defined semantics. That's what warnings are for, not just code that's likely to fail at run-time by throwing, code like `if (nonNullabelExpression == null) { ... }` is likely to fail by not doing what the author intended, which was to *occasionally* enter the `{ ... }` block (why else have it).

**Comment by eernstg** [comment]
You're right, we specify what it takes to be a warning as follows:

> [it is about situations that] do not preclude execution, but which are
> unlikely to be intended, and likely to cause bugs or inconveniences.

Checking again, I can see that we're using warnings for a couple of different purposes (we have two warnings, so we can't easily have more than two purposes ;-):

- Non-identical default values for parameters of methods related by overriding.
- Non-exhaustive switches on enums.

In the first case, a bug might arise because a caller of a method trusts the default value to be something specific, but the run-time method implementation uses a different default value. However, **this warning has been eliminated** from Dart recently.

In the second case, it is likely to be a bug that a switch statement has no effect because none of the given cases matched. This allows developers to think about switch-on-enum as a _selection of one action from a set of available actions_, not _... or skip_.

I tend to think that we shouldn't enlarge the set of warnings in order to cover `eWithNonnullableType == null`, and a hint would do the job just fine.

We could rename 'hint' to 'warning', though, if we changed the last warning to be an error. ;-)

**Comment by bwilkerson** [comment]
> We could rename 'hint' to 'warning', though, if we changed the last warning to be an error. ;-)

I've always thought of the analyzer's hints as warnings; I honestly can't see any difference, can you? The only reason they aren't called warnings is because of historical reasons that I won't go into here. I think it would serve our users well if we started calling them warnings and dropped the term "hint" from our vocabulary.

And we don't have to change the last spec warning to be an error, we just have to allow ourselves to support warnings in the analyzer that aren't in the specification.

But, I'll point out that this would have a bigger impact on users that just reducing the number of severity levels for diagnostics. It might well impact some CI systems if they allow hints but don't allow warnings. We'd probably want to create a breaking change notice for such a change to make users aware of the implications.

**Comment by gaaclarke** [comment]
I think it should be the same thing you get when you `!` a nonnull type or `?.` a nonnull type, like @lrhn said above.

I'll refrain from talking about what should be a hint, warning, or error since it's probably out of the scope for this issue.  I think it clearly falls under the category of whatever happens when the null safe operators are used incorrectly.

**Comment by Levi-Lesches** [comment]
> I think it should be the same thing you get when you `!` a nonnull type or `?.` a nonnull type

I'm with @gaaclarke, I get warnings on this by default, both in DartPad and in my projects, for every incorrect use of non-nullable values, except for `== null`: 

![image](https://user-images.githubusercontent.com/20747538/129606907-8d5c8ecd-c92a-4047-b9fa-3b692e0eb8b4.png)

Then again, you could say this is roughly equivalent to `invariant_booleans` or `dead_code`, which are both hints. I'd still vote for warning though.

**Comment by vsmenon** [comment]
Is there anything actionable at this point?  As @stuartmorgan points out, this check can actually be meaningful as long as we support mixed mode null safety.

Once we're sound mode only, the existing lint can be used more strictly.

**Comment by lrhn** [comment]
For mixed mode seemingly-unnecessary-but-not-really null checks, I highly recommend creating one specific helper method, like:
```dart
T checkNotNullable<T extends Object>(T value, String name) {
   // ignore: unnecessary_cast
   if ((value as dynamic) == null) throw ArgumentError.notNull(name);
   return value;
}
```
and use that everywhere in your project. When you stop supporting legacy code, just remove all calls to that one function. It's much easier to find than dozens of `x == null` normal looking checks. (Or use `(x as dynamic) == null` as the check consistently, then you can grep for that.

**Comment by mraleph** [comment]
I would like to either assign an area to this issue or close it (if we think no work needs to be done). 

@lrhn Lasse could you make a call?

**Comment by lrhn** [comment]
I think the analyzer should consider enabling this hint by default, but it's not something we need to add to the language specification. Language-specification warnings are really a gray zone between errors and "something everyone considers and error anyway". It's better to leave something like this to the analyzer which can do such hints heuristically, and avoid over/under-specifying it in the language specification.

It's heuristically just an unnecessary/dead code hint, or a "this test will always be true/false" hint, which we do in other cases too.

**Comment by scheglov** [comment]
AFAIK hints (vs. lints) are always enabled by default.

**Comment by pq** [comment]
> AFAIK hints (vs. lints) are always enabled by default.

This is correct.

**Comment by jcollins-g** [comment]
Since this is enabled by default, and enabling it by default was listed as the only action that might need to be done, closing.
