### ISSUE TITLE
[dev_compiler] Add hot reload ability to dartdevc

### ISSUE THREAD

**Issue by michaellee8** [dart-lang/sdk#46958]
Currently, it is not possible to perform hot reloading when development flutter web apps. My [idea](https://github.com/michaellee8/flutter_web_hot_reload/blob/feat/doc-wip/README.md#apppach) is to implement the Dart VM's method replacing based hot reload by modifying dartdevc to generate one-off javascript patches that will inject the new methods using the prototype chain. It has been discussed a litle bit in https://github.com/flutter/flutter/issues/53041#issuecomment-899883090. I plan to contribute it but currently I am not sure about the internals of dev_compiler so I will need some guidance.

**Comment by michaellee8** [comment]
@vsmenon I have opened an issue here.

**Comment by nshahan** [comment]
Off the top of my head, the current support for hot restart essentially:
* loads a new version of a Javascript module for all of the dart libraries that were rebuilt because of an edit in the IDE.
* resets some global state in various caches in the dart runtime module.
* calls an optional hook provided by the embedding bootstrap.
* calls the entry point main method to restart the app.

>My idea is to implement the Dart VM's method replacing based hot reload by modifying dartdevc to generate one-off javascript patches that will inject the new methods using the prototype chain.

I'd like to understand more about your idea. The code in to be replaced should already be part of the modules that get reloaded. Are you trying to reduce the amount of code that gets recompiled and loaded by the compiler when there during the hot reload? It's not clear to me that is an immediate issue. 

When I think about supporting hot reload in DDC I find the largest hurdle will be identifying the values in the dart runtime library that need to be reset or updated. These are the values used to provide the dart language semantics and performance improvements while running in Javascript (Dart type representations, values in caches, etc.) Some of these values are captured by closures so they are very hard to invalidate or update without restarting the application. We need to restructure the representation so it can easily be updated or invalidated for a hot restart. If stale values are lingering around after a hot restart could be incorrect and lead to very confusing errors. 
Some examples:
https://github.com/dart-lang/sdk/issues/37259
https://github.com/dart-lang/dart-pad/issues/1912

One of the first steps I'd like to take is to identify the cases we should be supporting. I believe there are some existing tests for hot reload already. We should build some infrastructure to start running them with an application compiled by DDC to help guide our work.

cc @Markzipan @sigmundch @annagrin

**Comment by michaellee8** [comment]
@nshahan My idea is to basicaly implement the way that hot reloading works in Dart VM (https://github.com/dart-lang/sdk/wiki/Hot-reload), by replacing the javascript functions in runtime. I believe variables do not have to be modified right?

**Comment by nshahan** [comment]
OK as I understand you would like to replace methods, either top level or attached to the prototypes of classes. If that is all we do I think it might be possible to avoid the problems that appear when we replace the entire classes.

To give you some background, there are two code paths in dev_compiler.
* [ProgramCompiler](https://github.com/dart-lang/sdk/blob/58416605e24b7f5617c29a7259bdf235137650e8/pkg/dev_compiler/lib/src/kernel/compiler.dart#L44) is used to compile an entire module (one or more Dart libraries) to Javascript. This gets used for the initial compile.
* [ExpressionCompiler](https://github.com/dart-lang/sdk/blob/48d8225b17f11c56dff129942ce044474a21db46/pkg/dev_compiler/lib/src/kernel/expression_compiler.dart#L262) is used to compile a single Dart expression to Javascript. This gets used to populate the values seen in the debugger and if you type an expression in the debug console. The ExpressionCompiler relies on a full compile by the ProgramCompiler already being done so that it can generate Javascript code that is compatible with the previously compiled Javascript program.

Both take a [Component](https://github.com/dart-lang/sdk/blob/48d8225b17f11c56dff129942ce044474a21db46/pkg/kernel/lib/ast.dart#L13207) from the Common Front End (CFE) as the input for compilation. This is Dart source code that has already been built into a tree where each node represents some part of the original Dart program.

I'd imagine that we would want to create something similar to the `ExpressionCompiler` that can compile entire methods compatible with a Javascript program that has already been compiled. Then we would also need some infrastructure to pick out all of the changed code, identify to what class/library/module it belongs to, and somehow add or replace the existing methods in the program running in the browser.

**Comment by annagrin** [comment]
Flutter request for stateful hot restart: https://github.com/flutter/flutter/issues/53041

**Comment by kaljitism** [comment]
@michaellee8 @nshahan any update or progress on this??

**Comment by sigmundch** [comment]
Sorry I missed this issue in the issue tracker.

It's part of the Dart web team plans to dive into hot reload support this year. It's a long road ahead and we are just getting started, so we don't have much to share at this time. We're be tracking our efforts in https://github.com/dart-lang/sdk/issues/54934.

Given the overlap, I'll close this issue as a duplicate
