### ISSUE TITLE
Tried to initialize from a previous compilation, but couldn't. Error message was 'null:5242880: indicated size does not match file size at 

### ISSUE THREAD

**Issue by Nagendra-nagy** [dart-lang/sdk#46962]
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/7026639/initialize_from.dill.gz)

* Dart SDK Version: 2.13.4 (stable)
* Using MacOSX
* Using Chrome

**Comment by jensjoha** [comment]
Thank you for reporting this.
Rest assured that the compilation itself was not hindered by this warning, although it may have taken a little more time.

The dill file is partial which is why it couldn't be loaded.
Most likely a process was killed at the wrong time (while serializing).

I don't assume this is something you see often and I'll close the issue.
