### ISSUE TITLE
js interop fragile with non-external factory constructor

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#46967]
This was discovered from a bug reported in DevTools: https://github.com/flutter/devtools/issues/3300. Workaround her: https://github.com/flutter/devtools/pull/3301.

The issue is with calling a non-external factory constructor from within a `@JS()` annotated class. 

Here is a simplified example:

```dart
@JS()
@anonymous
class MyClass {
  external factory MyClass({
    String a,
    String b,
  });

  // this factory can't be external because it has a body
  factory MyClass.otherFactoryWithABody({
    String a,
    String b,
  }) {
    return MyClass(
      a: a,
      b: b,
    );
  }
}
```

error from calling `MyClass.otherFactoryWithABody`:
TypeError: MyClass is not a function

**Comment by jacob314** [comment]
Note that the issue also reproduces if the factory constructor is replaced with a static method.
Fyi @nshahan, @srujzs. Did something recently change in DDC or JS interop? Static methods on @JS classes also fail to run. I suspect this case or at least the static method case works in Dart2Js.
It would be nice if this case failed at compile time.

**Comment by sigmundch** [comment]
/cc @rileyporter 

Thanks for sharing the nice and small example!

About a year ago we started looking at a large volume of discrepancies in terms of how constructors were handled by both compilers. For the most part we added checks to reject patterns that were not supported by either one of the compilers. I don't recall the details, but it's quite likely this case showed up and we decided not to add the check because our intend was to actually fix DDC instead and make it match dart2js semantics.
