### ISSUE TITLE
Constructor tear-off diagnostic conflicts with earlier diagnostic

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#47035]
Given the following code:
```
void g(void Function<T>(T) f) {
  f<int>;
}
```
The analyzer produces the following diagnostics:
```
error: This requires the 'constructor-tearoffs' language feature to be enabled. (experiment_not_enabled at [test_package] lib/test.dart:2)
error: Only a generic type, generic function, generic instance method, or generic constructor can be type instantiated. (disallowed_type_instantiation_expression at [test_package] lib/test.dart:2)
```
I'm not sure which it the better diagnostic, but having both is likely to be confusing to users.

**Comment by bwilkerson** [comment]
@srawlins

**Comment by bwilkerson** [comment]
The following code:
```
bar(dynamic a) {
  a.foo<int>;
}
```
has a similar issue. It produces a different second diagnostic, but still produces two where only one ought to be produced:
```
error: A method tearoff on a target whose type is 'dynamic' can't have type arguments. (generic_method_type_instantiation_on_dynamic at [nnbd_test_package] lib/test.dart:2)
error: This requires the 'constructor-tearoffs' language feature to be enabled. (experiment_not_enabled at [nnbd_test_package] lib/test.dart:2)
```

**Comment by srawlins** [comment]
Hmm interesting issue. If you try to fix the code so the second error goes away, you'll still be left with the first (constructor tearoffs are not enabled); if you try to fix the code so the first error goes away, you'll still be left with the second error.

I'm leaning towards only reporting the first. Since the second error is only applicable to code with constructor tearoffs enabled. In other words, I think any new errors related to constructor tearoffs should not be reported unless constructor tearoffs are enabled.

**Comment by bwilkerson** [comment]
I think that's a good general principle: if a feature is disabled then we should report one diagnostic to that effect and nothing else.
