### ISSUE TITLE
A value of type 'T & Future<int>' can't be returned from the function 'i' because it has a return type of 'Future<int>'.

### ISSUE THREAD

**Issue by Cyp** [dart-lang/sdk#47053]
[Edit by eernstg: [This comment](https://github.com/dart-lang/sdk/issues/47053#issuecomment-909165108) contains a brief summary of the situation, and about what we need to change. Subtasks: #47056, #47057]

Originally opened here: https://github.com/dart-lang/linter/issues/2894

**To Reproduce**
- No error.
```dart
Future<int> h<T>(T x, Future<int> y) async => x is Future<int> ? x : y;
```

----

- Spurious error, despite being logically identical to `h`!
  Since a value of type `T & Future<int>` does have the required type `int | Future<int>`, the error message is inconsistent.
  Doing `return x as Future<int>;` compiles, but (correctly) warns about an unneccesary cast.
```dart
Future<int> i<T>(T x, Future<int> y) async {
  if (x is Future<int>) {
    return x; // error: "A value of type 'T & Future<int>' can't be returned from the function 'i' because it has a return type of 'Future<int>'."
    return x as Future<int>; // warning: "Unnecessary cast."
  }
  return y;
}
```

----

- No error, despite being exactly identical to `i` except for `async`.
```dart
Future<int> j<T>(T x, Future<int> y) {
  if (x is Future<int>) {
    return x;
  }
  return y;
}
```

**Expected behavior**
No warnings or errors except for the valid warning: "Unnecessary cast.".

**Additional context**
Using dart 2.13.4.

**Comment by eernstg** [comment]
I transferred this issue to the SDK repository because it shows that there is a need to adjust the behavior of the CFE and the analyzer. Here is a summary of the situation:

The following example program shows that `return x;` where `x` has static type `T & Future<int>`, is rejected by current implementations (both `dart` and `dartanalyzer` from 8f9113d9f1cb11400c384a4ac68fc050636cf573):

```dart
Future<int> f<T>(T x, Future<int> y) async {
  if (x is Future<int>) return x;
  return y;
}

void main() => f(0, Future<int>.value(1));
```

with the following error messages:

```
> dartanalyzer n037.dart
ERROR|COMPILE_TIME_ERROR|RETURN_OF_INVALID_TYPE|/usr/local/google/home/eernst/lang/dart/scratch/202108/n037.dart|2|32|1|A value of type 'T & Future<int>' can't be returned from the function 'f' because it has a return type of 'Future<int>'.
> dart n037.dart
n037.dart:2:32: Error: A value of type 'T' can't be returned from an async function with return type 'Future<int>'.
 - 'Future' is from 'dart:async'.
  if (x is Future<int>) return x;
                               ^
```

The function `flatten` basically eliminates one layer of `Future` from a type, but in this case we need `flatten(T & Future<int>)`, and this [should yield](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#future-flattening) `int`.

The future value type of the enclosing function is `int` as well, and `int <: int`, so `return x;` is not an error, cf. [this section](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#return-statements).

**Comment by eernstg** [comment]
Closing: At this point the example is working and the subtasks (#47056, #47057) have been completed.
