### ISSUE TITLE
How to dynamically obtain the class attribute name? For example, the reflection function of java?

### ISSUE THREAD

**Issue by shaojiudada0321** [dart-lang/sdk#47064]
How to dynamically obtain the class attribute name? For example, the reflection function of java?

Why does it not support why, why both c# and java exist and why dart does not? Why is it so rubbish?

**Comment by mraleph** [comment]
If you want to ask _questions_ I suggest using other support channels (e.g. StackOverflow, discord, gitter, etc). Also I'd encourage you to be less confrontational in your questions.

The answer to your question is the following: `dart:mirrors` is the equivalent of reflection. It is disabled in Flutter applications because unbounded reflection would have a large negative effect on application's code size and performance. Solution is to use problem specific code generation solution or a package like [`reflectable`](https://pub.dev/packages/reflectable).
