### ISSUE TITLE
Analyzer does not report an error when `new` is used in a non-constructor position with constructor tearoffs enabled

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#47077]
With constructor tearoffs enabled, the analyzer correctly emits an error on the definition of the field in `C` in the code below, but issues no errors on the access of `new` on an instance of `C` and on `foo` in `main`.  I believe that all of those should be an error.  This should cause a failure in `co19/Language/Expressions/Instance_Creation/New/type_t05` (source  [here](https://github.com/dart-lang/co19/blob/cc4df792d0f02f15bfe04911c1f856b90cb7cbf4/Language/Reference/Lexical_Rules/Reserved_Words/new_t04.dart)) when constructor tearoffs are enabled.  See logs [here](https://dart-ci.firebaseapp.com/cl/212262/1) but note that the analyzer run failed with an infrastructure issue .  CL turning on the flag is [here](https://dart-review.googlesource.com/c/sdk/+/212262).

cc @eernstg @lrhn @srawlins @scheglov  @devoncarew 

```dart
class C {
  int new = 42;
}

main() {
  new C().new is int;
  dynamic foo;
  foo.new;
  foo.new();
}
```

**Comment by eernstg** [comment]
I believe the grammar in [Dart.g](https://github.com/dart-lang/sdk/blob/master/tools/spec_parser/Dart.g), in particular the updates in 6facd6dfdafa2953e8523348220d3129ea884678, can be considered to specify the new syntax added by the constructor-tearoffs feature bundle. With that, we have two syntax errors (`int new` and `new C().new`), but it is of course not required for an implementation to label any error as a syntax error. I believe the behavior of `dart` and `dartanalyzer` from commit a6cc772b670034f355c626e28ce11d1555f97e24 (a fresh one) is fine for `int new`, but they fail to report `new C().new` as an error (of any kind).

`foo.new` and `foo.new()` should be reported as compile-time errors, because `foo` fails to be a statically resolved reference to a class (it should be a class, and that class should have a constructor named `foo`, but we don't even get to step two).

Cf. https://github.com/dart-lang/language/pull/1837.

**Comment by leafpetersen** [comment]
Tests affected:
  - https://github.com/dart-lang/co19/blob/cc4df792d0f02f15bfe04911c1f856b90cb7cbf4/Language/Reference/Lexical_Rules/Reserved_Words/new_t04.dart
