### ISSUE TITLE
Dart - double datatype addition results in long decimal wrong value

### ISSUE THREAD

**Issue by sunilm316** [dart-lang/sdk#47081]
Added 44.584 and 179.83, the result should be 224.414.
But in dart we are getting as 224.41400000000002.

![Screenshot from 2021-09-02 13-10-55](https://user-images.githubusercontent.com/46790267/131803014-f112c0d9-3aae-4527-9156-a0aef106ff48.png)

**Comment by mraleph** [comment]
That's how floating point values work, see https://floating-point-gui.de/ for more information. 

If you want precise decimal computations use package `decimal`, or store your values as scaled integers and perform integer operations (e.g. if you want 2 digits of precision store `v * 100` instead of `v`).

**Comment by lrhn** [comment]
This is expected behavior for doubles. You'll get the same result in any other language which uses IEEE-754 64-bit floating point numbers (which they all do because that's what the CPUs implement).

The reason is that doubles have limited precision (at most 53 significant *binary* digits) and they can't represent all decimal fractions precisely. So, the decimal number literals you write really represent double values that are slightly different:
* `44.584`: 44.58400000000000318323145620524883270263671875
* `179.83`: 79.830000000000012505552149377763271331787109375

The double representing `44.584` is the double value which is *closer* to the real number 44.584 than any of the other possible double values.

As you can see, both of these numbers are slightly above the value you expect. When you add them together, the result is:
* 224.414000000000015688783605583012104034423828125

which is even more above the expected result 212.414. In fact, it is so much above it that it's not the double closes to 212.414.

The  double number represented by `224.414` is:
* `224.414`: 224.413999999999987267074175179004669189453125 

because it's closer to 212.414 than the value above.

When Dart *prints* a double, it prints as many decimals is needed to give a real number which is closer to the original double than to any other double value, to ensure that reading it back gives the same value. 
The result of the addition is different from the double for `224.414`, so it is printed as a different string.
