### ISSUE TITLE
Migrate `module_symbols.dart` to null-safety

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#47096]
Shouldn't [module_symbols.dart](https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/kernel/module_symbols.dart) be migrated to null safely?

**Comment by nshahan** [comment]
Yes, we still need to migrate many libraries to null safety. It hasn't been a high priority because of the known dependencies on these libraries is very low. I've been chipping away at the dependencies of the tests first. 

Closing this issue as a duplicate since I'm tracking the migration of dev_compiler libraries here https://github.com/dart-lang/sdk/issues/46617.
