### ISSUE TITLE
Broken Spread operator, it makes a shallow copy (new reference) instead of deep copy (whole new object).

### ISSUE THREAD

**Issue by MohaAmiry** [dart-lang/sdk#47137]
I was trying to make a deep copy of a list of lists using spread operator and it did not work, any explanations about reasons?
I tested it with ordinary lists and it worked perfectly, so what is happening?
![Untitled](https://user-images.githubusercontent.com/65380552/132410818-884275d0-c3d5-4e4a-a629-264024cbc693.png)

my dart SDK version is 2.13.4 (stable).
i'm using windows 10.

**Comment by lrhn** [comment]
Working as intended. The spread operator was never intended for creating deep copies.

The spread operator takes the elements of the list (or iterable) being spread and makes them elements of the new list. It works exactly the same, no matter what those elements are.
It's not *copying* anything. It is injecting the elements, whatever they are, of one collection into another collection.

It's generally impossible to make a deep copy of Dart objects because you can only create an object of a type that you know the constructor of at compile-time (and even then, some objects just can't be meaningfully copied). It's technically possible to recognize when the elements being spread are themselves list and create new lists for those, but it is very risky. If the list is a `Uint8List`, making a copy when spreading might not be what you want, and making a plain `List` is almost certainly not what you want.

Doing a deep copy by default, even if only when possible (which is rarely), is not something we *want*. It's too hard to control, and you'd need a way to turn it off when you do want a shallow copy.

If you do want a deep copy of a list of lists, you have to write it:
```dart
 var tmp = [for (var element in list) [...element]];
 // or, going old-style,
 var tmp = list.map((e) => e.toList()).toList();
```
