### ISSUE TITLE
Annotation that allows redundant `!` on call sites for a non-nullable member

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#47135]
It's common in practice to create APIs with nullable types that later become non-nullable (for example, I'm trying to do this with `binding.instance` in Flutter, see https://github.com/flutter/flutter/issues/64830).

Currently, rolling this out is a breaking change (because places that previously used `!` to use the member now fail at compile time because of redundant `!` use). For environments like google3, it can be a _massive_ breaking change, requiring synchronous fixes at the time of the API change on a scale beyond what our tooling can currently do.

@dnfield suggests that it would be useful to be able to mark a member so that it is exempt from these errors, causing the compiler and analyzer to just ignore the `!` (or at best emit a non-fatal informational message a bit like a deprecation message).

This would be really, really helpful. Especially given the trouble I'm currently having rolling the aforementioned change into google3, I would love to see this.

cc @leafpetersen

**Comment by jakemac53** [comment]
> Currently, rolling this out is a breaking change (because places that previously used `!` to use the member now fail at compile time because of redundant `!` use)

Note that this is not actually a compile time error, it is a warning. For instance https://dartpad.dartlang.org/?null_safety=true&id=f1a086f2ce55e895d41c7a3719fe45ca compiles and runs just fine.

So whether this is "breaking" is a choice made at the project level. Many apps/projects do choose to break their CI builds based on warnings, or even analyzer hints and lints and formatting. And I would argue in this case that is actually a _good_ thing, because it gives them a signal that they have some now outdated code, which they should go and update (remove the `!`). They opted into breaking on that type of thing for exactly that purpose.

Because of that it is my opinion that an annotation like this is actually not a good thing to have, as the likely result would be a bunch of unnecessary `!` that don't ever get cleaned up?

I would focus rather on making it easier to clean up the code (ie: make `dart fix` work internally at large scale).

**Comment by dnfield** [comment]
My thought on the new annotation is that it would be temporary, and allow for softer migrations.

If `dart fix` can work at scale (including for `google3` and the `pub` ecosystem?), it'd clearly be better. If that's something that can be done relatively quickly all the better. But if not, we'll continue to get blocked by this - and the alternatives available currently (manually adding ignores to a large number of targets before a roll and removing them after, adding a new property that might be weirdly named and deprecating the existing one) are not really all that great.

**Comment by jakemac53** [comment]
> My thought on the new annotation is that it would be temporary, and allow for softer migrations.

I understand making a nullable thing non-nullable feels like it should be non-breaking, but it does require some work on your users part to get rid of these diagnostics. 

And ultimately, all this is is a diagnostic - a very valid one with zero false positives. I really don't think giving library authors a way to remove valid (language specified) diagnostics from their _users_ code is a good thing.

> If `dart fix` can work at scale (including for `google3` and the `pub` ecosystem?), it'd clearly be better.

Fwiw I don't think `pub` is really a requirement here, although sending out preemptive prs would be nice, and for a lot more fixes than just this. But internal is where we really run into a blocker, because we aren't allowed to submit code with these diagnostics there, as we have chosen to make builds fail on diagnostics. 

> But if not, we'll continue to get blocked by this - and the alternatives available currently (manually adding ignores to a large number of targets before a roll and removing them after, adding a new property that might be weirdly named and deprecating the existing one) are not really all that great.

Ya I feel the pain for sure, it seems like a small change but it causes a lot of breakage. That basically just comes with the territory when it comes to internal code especially though. Having a single code base with all our apps on a single version of the framework is a general problem. And having tools to wide scale apply fixes there would solve this problem generally.

**Comment by lrhn** [comment]
I recommend *not* using `!` to handle unsound null safety `null` values. You're going to have to remove them again when your code become soundly null safe, and it's incredibly hard to search for `!`.

I'd use a project-wide helper function like:
```dart
T checkNonNullable<T extends Object>(T value, String name) {
  dynamic untypedValue = value;
  if (untypedValue == null) {
     throw ArgumentError.notNull(name);
  }
  return value;
}
```
Then when you have a null safe function where you want to make it unsound null-safety safe, you call that function:
```dart
Bar barTheFoo(Foo foo) {
   checkNonNullable(foo, "foo");
   ...
}
```
or
```dart
  MyConstructor(Foo foo) : foo = checkNonNullable(foo, "foo");
```
When you want to stop supporting unsound null safe mode, you can search for `checkNotNullable` and find all the places. And it's typed so you won't accidentally use it for a *real* null check.

(The SDK has its own function precisely for that. It's not shared, so we can remove it when we don't need it any more. You should make your own, for the same reason.)

I'm not opposed to allowing you to `// ignore: unnecessary_check` for language specified warnings. It's your program. I just don't think it's the *right* tool here.

**Comment by Hixie** [comment]
@lrhn was this the issue you meant to comment on? I'm not sure how your comment applies here...

**Comment by Hixie** [comment]
Yeah it'd be basically the same as "@deprecated" -- "here's a change you will want to make, but maybe not right away".

The reality is `dart fix` makes this particular change trivial to make, outside of contexts like google3, so maybe it's not that useful long run...

**Comment by jakemac53** [comment]
Fwiw `@deprecated` also causes this same problem (where people opt in to lints/hints being failures). I am not totally certain if we do fail on that internally or not.

But ultimately I would treat it the same. As @lrhn brought up we would need some totally new thing. Something that makes it obvious that you need to do something, but doesn't break your builds.

Externally, you could do this with say a chat bot that pings your channel if a lint/hint is violated instead of failing your builds. But I am not sure what equivalent we would have internally.

Ultimately I think it becomes a tooling problem though, and not a language problem. We fail builds on hints/lints/warnings because we don't have a better option set up to consistently let us know when things like that need action.

**Comment by dnfield** [comment]
I think I'm fine closing this - it sounds like dart fix will do the job for this, and is either close enough to working internally or close enough to working that this wouldn't help too much for too long.
