### ISSUE TITLE
[cp][stable] Bail out inlining on wrong optional arguments

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#47143]
**Commit to merge**: 015c4e604a43b52071532a73056895930eada07c.

**Merge instructions**: merges cleanly on 4c8a4f0d7ad055fa7dea5e80862cd2074f4454d3.

**What is the issue**: The inliner tried inlining functions within the then/else statement of `if`s with type promotions that could never occur (dead code), causing the inliner to fail subsequently.

**Why cherrypick:** This issue does _not_ affect many users. However, since we have another cherrypick request already, we could consider it.

**Risk:** Low. Adds an extra check in the inliner, and bails out from inlining in this specific case.

**Link to original issue:** https://github.com/flutter/flutter/issues/89482

/cc @mkustermann @mraleph @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow

**Comment by devoncarew** [comment]
After some discussion:
- we won't cherry pick this (generally due to low impact - the code pattern that triggers it is not at all common) 
- we do want to watch to see if there are any more instances of this happening in the wild (though note that this will be tough to know - it'll mean re-diagnosing reported issues)
- it does bring up a good question wrt cherry pick criteria for crashers like these - less common, but harder to diagnose when users hit them

**Comment by a-siva** [comment]
It probably makes sense to cherry pick into the beta channel
