### ISSUE TITLE
Crash when calling a virtual method that is not implemented in the mixin

### ISSUE THREAD

**Issue by axxop** [dart-lang/sdk#47148]
main.dart

```
import 'lib.dart';

mixin D {
  _test();
}

main() {
  P()._test();
}
```

lib.dart

```
import 'main.dart';

class P with D {}
```

The analyzer show no errors, but it crashed in running: 
```
Unhandled exception:
NoSuchMethodError: Class 'P' has no instance method '_test'.
Receiver: Instance of 'P'
Tried calling: _test()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
...
```

**Comment by lrhn** [comment]
This is working as intended.

The `P` class declaration cannot see the `_test` declaration because it's private to a different library.
The rule in that case is that since `P` is not abstract, so it must implement its interface, but it cannot possibly implement `_test` (or know that it should), you get a free "no such method" forwarding stub added to implement `_test`.

Basically, you get a `_test() => noSuchMethod(Invocation.method(#test, null));` method added automatically. That's what you're calling.
