### ISSUE TITLE
Add a quick fix for `unnecessary_raw_strings` lint

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#47144]
There is currently no quick fix for it.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/212743

**Comment by srawlins** [comment]
I've given this a low priority, initially, because this lint rule is not in either rule set in the **lints** package.

@pq and @bwilkerson may have thoughts on policies for such lint rules.

I think that most quick fixes have a very very low cost of maintenance, but a few are quite complex pieces of code.
