### ISSUE TITLE
The value of the field 'XXX' isn't used.

### ISSUE THREAD

**Issue by adrianvintu** [dart-lang/sdk#47157]
Hello,

I have the following piece of code:

```
import 'dart:io';

class UnusedVarTest {
  final String _folderName;
  final String _fileName;
  final String _filePath;

  UnusedVarTest(this._folderName, this._fileName) : _filePath = _getFilePath(_folderName, _fileName);

  static String _getFilePath(String folderName, String fileName) {
    return "$folderName/$fileName";
  }

  createFile() {
    new File(_filePath);
  }

  //Just to use the variables _folderName and _fileName
  //String toString() => "Folder: $_folderName file: $_fileName File path: $_filePath";
}
```
In Visual Studio Code, I get 2 variables underlined, with the warnings:
```
The value of the field '_folderName' isn't used.
Try removing the field, or using it.dart(unused_field)

The value of the field '_fileName' isn't used.
Try removing the field, or using it.dart(unused_field)
```

Is this behavior intended?

Should I assume that is almost(!) never read from, that means they are unused? The 2 variables are read in the constructor initialization.

For now, to get rid of the warnings, I created the commented out `toString` method to used the 2 variables.

Also, without the `createFile` method, there will be a warning saying that _filePath is not used.

Is this behavior intended?

**Comment by lrhn** [comment]
Yes, it's intended.

It's a warning the analyzer gives you when your class have private fields that are not used. You could remove the fields, and your program would still work exactly the same.
Because the fields are private, it's guaranteed that if there is no code reading them in the same library, there will be no code reading them anywhere.

The two variables here are *never* read from. They are written by the `this._folderName` and `this._fileName` initializing formal parameters, and never read again (unless you uncomment the `toString` method).
The `_getFilePath(_folderName, _fileName)` call doesn't read the *fields* (it can't, it's in the constructor initializer lists and the object doesn't exist yet at that time), it instead reads same the constructor parameters that were also written to the field's initial value.

Same if you remove `createFile`, then there is no code reading `_filePath` anywhere in the program, so the field can safely be removed.

**Comment by adrianvintu** [comment]
Thank you @Irhn.

This helped me so much.

> The _getFilePath(_folderName, _fileName) call doesn't read the fields (it can't, it's in the constructor initializer lists and the object doesn't exist yet at that time), it instead reads same the constructor parameters that were also written to the field's initial value.

I wish this example and your comment were added to the official documentation.
