### ISSUE TITLE
Invalid argument(s):: Unexpectedly not indexed:: Notifier extends StateNotifier

### ISSUE THREAD

**Issue by arnoutvandervorst** [dart-lang/sdk#47171]
After the upgrade to Flutter 2.5 and Dart 2.14, I get analysis errors on every file I open and errors when running the build_runner. The analysis server instrumentation log reveals this error on every single file:

1631182843704:Ex:Analysis failed:: /Users/arnoutvandervorst/Projects/newme_app/test/widget_test.dart context:: exception_20210909_122043_559
Invalid argument(s):: Unexpectedly not indexed:: Notifier extends StateNotifier
#0 _LocalElementIndexer.[] (package::analyzer/src/summary2/bundle_writer.dart::944::10)

Also, the output lists these errors when I open a file, for instance main.dart:

[Error - 8:45:12 AM] Request textDocument/documentSymbol failed.
Message: Invalid file path
Code: -32003
/Users/arnoutvandervorst/Projects/newme_app/lib/main.dart
[Error - 8:49:06 AM] Request textDocument/codeAction failed.
Message: Invalid file path
Code: -32003
/Users/arnoutvandervorst/Projects/newme_app/lib/main.dart

build_runner doesn't run, and the analyzer keeps going mental on every file I open.

**Comment by DanTup** [comment]
@bwilkerson @scheglov FYI - 4 separate users reported this at https://github.com/Dart-Code/Dart-Code/issues/3530 since yesterdays releases.

The second part of the error is what happens via LSP when we try to open a file where parsing failed (because it assumes if it can't get the result for a file it's because the path is invalid), but I think the first error is the issue.

(I don't know if clearing `.dartServer` might help, but I didn't want to suggest that until you'd seen this in case there's useful information in there that would be lost).

**Comment by scheglov** [comment]
I saw `Unexpectedly not indexed` happening when we had a bug in resolution that resulted in AST referencing type parameters that are not available in the result context. Here `Notifier extends StateNotifier` does not look like a typical type parameter name, but still might be. So, do you have such type parameter? Any place where you reference the declaration with such type parameter, especially where you try to use [constructor tear-off](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) feature (which is being implemented, incomplete yet) is a suspect. We [had](https://github.com/dart-lang/sdk/issues/46981) something like this recently.

Or it could be something other, which I don't know about. If it can be reproduced, I'd love to have this project, e-mail it to me.

**Comment by arnoutvandervorst** [comment]
No such type parameters, this is only used in class declarations, such as:

```dart
class UserNotifier extends StateNotifier<User> {
  User user = User();

  UserNotifier(this.user)
      : super(
          User(),
        ) {
    update(user);
  }

  void update(User user) {
    state = User.copyWith(user);
  }
}
```

Weird thing is, I have another flutter project which also uses StateNotifier classes, and that project builds and analyses just fine.

**Comment by scheglov** [comment]
If you still can reproduce it, look for `exception_20210909_122043_559` in your `. dartServer`, or similarly named files there.
It will include longer stack trace, but also a subset of source files of your project.
If you can share it, send it to `scheglov@google.com`.

**Comment by arnoutvandervorst** [comment]
Easy to reproduce for me, happens on every file, just sent you the log containing that specific exception.

**Comment by scheglov** [comment]
Yes, I see that you get this exception very often.
It still looks from the log that somehow `Notifier` was parsed as a type parameter, so we attempt to store it as a `TypeParameterElement`.

And indeed it looks that we are storing a class field initializer.
```
Invalid argument(s):: Unexpectedly not indexed:: Notifier extends StateNotifier<State>
#0      _LocalElementIndexer.[] (package::analyzer/src/summary2/bundle_writer.dart::944::10)
#1      ResolutionSink._indexOfElement (package::analyzer/src/summary2/bundle_writer.dart::620::27)
#2      ResolutionSink._writeElement (package::analyzer/src/summary2/bundle_writer.dart::655::24)
#3      ResolutionSink.writeElement (package::analyzer/src/summary2/bundle_writer.dart::543::7)
#4      ResolutionSink.writeType (package::analyzer/src/summary2/bundle_writer.dart::595::7)
#5      ResolutionSink._writeTypeList (package::analyzer/src/summary2/bundle_writer.dart::733::7)
#6      ResolutionSink._writeTypeAliasElementArguments (package::analyzer/src/summary2/bundle_writer.dart::726::7)
#7      ResolutionSink.writeType (package::analyzer/src/summary2/bundle_writer.dart::588::7)
#8      ResolutionSink._writeFormalParameters.<anonymous closure> (package::analyzer/src/summary2/bundle_writer.dart::669::9)
#9      ResolutionSink._writeTypeParameters (package::analyzer/src/summary2/bundle_writer.dart::755::8)
#10     ResolutionSink._writeFormalParameters (package::analyzer/src/summary2/bundle_writer.dart::668::7)
#11     ResolutionSink._writeFunctionType.<anonymous closure> (package::analyzer/src/summary2/bundle_writer.dart::689::7)
#12     ResolutionSink._writeTypeParameters (package::analyzer/src/summary2/bundle_writer.dart::755::8)
#13     ResolutionSink._writeFunctionType (package::analyzer/src/summary2/bundle_writer.dart::687::5)
#14     ResolutionSink.writeType (package::analyzer/src/summary2/bundle_writer.dart::563::7)
#15     ResolutionSink._writeFormalParameters.<anonymous closure> (package::analyzer/src/summary2/bundle_writer.dart::669::9)
#16     ResolutionSink._writeTypeParameters (package::analyzer/src/summary2/bundle_writer.dart::755::8)
#17     ResolutionSink._writeFormalParameters (package::analyzer/src/summary2/bundle_writer.dart::668::7)
#18     ResolutionSink._writeFunctionType.<anonymous closure> (package::analyzer/src/summary2/bundle_writer.dart::689::7)
#19     ResolutionSink._writeTypeParameters (package::analyzer/src/summary2/bundle_writer.dart::755::8)
#20     ResolutionSink._writeFunctionType (package::analyzer/src/summary2/bundle_writer.dart::687::5)
#21     ResolutionSink.writeType (package::analyzer/src/summary2/bundle_writer.dart::563::7)
#22     AstBinaryWriter._storeInvocationExpression (package::analyzer/src/summary2/ast_binary_writer.dart::801::11)
#23     AstBinaryWriter.visitFunctionExpressionInvocation (package::analyzer/src/summary2/ast_binary_writer.dart::305::5)
#24     FunctionExpressionInvocationImpl.accept (package::analyzer/src/dart/ast/ast.dart::4948::15)
#25     ResolutionSink._writeNode (package::analyzer/src/summary2/bundle_writer.dart::699::10)
#26     ResolutionSink._writeOptionalNode (package::analyzer/src/summary2/bundle_writer.dart::716::7)
#27     BundleWriter._writeFieldElement (package::analyzer/src/summary2/bundle_writer.dart::236::21)
```
One of the parameter types is an `InterfaceType` (a class instantiated) created via a type alias, and one of the type arguments turned out to be this type parameter named `Notifier`.

I attempted to re-create this in a smaller test case, but cannot reproduce the exception.
[my.zip](https://github.com/dart-lang/sdk/files/7138974/my.zip)

**Comment by arnoutvandervorst** [comment]
Sent the complete project, hope it helps in tracing the issue, have no idea where to look...

**Comment by scheglov** [comment]
Thank you! I can reproduce it locally now.

**Comment by scheglov** [comment]
A simplified test case is following:
```dart
class A {}

typedef A2<T> = A;

class B {
  U foo<U>(A2<U> create) {
    throw 0;
  }
}

class X {
  static final b = B();
  static final f = b.foo<int>();
  const X();
}
```

There are several issues.
1. We should not store initializers of static final fields, even if there is a const constructor.
2. When we convert the `FunctionType` of `foo` to synthetic, we missed processing `InstantiatedTypeAliasElement.typeArguments`, so instead of a fresh `TypeParameterElement` we still reference the original (not available in this scope) `U`.
3. And it might be interesting to investigate if it is right to have such `FunctionType` in the first place, maybe we should built synthetic `FunctionType` instances from the start.

Just fixing (1) seems to make `flutter pub run build_runner build` to work, and your project can be analyzed (there are still a handful of errors, mostly around assignment to `final`). So, I will first do such fix, and look further into other issues.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/212874

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/213022 for (2)

**Comment by arnoutvandervorst** [comment]
Thanks for the follow-up, can you point me to the offending code? I'm still not sure what exactly in my code triggers it when looking at your test scenario.

**Comment by rrousselGit** [comment]
Thanks for the fix @scheglov

Do you know if the fix will be cherry picked to be available on the stable channel of Flutter?
Since it seems like a common occurrence

**Comment by sandbox-apps** [comment]
Ohh remi has the same issue also. :(

**Comment by scheglov** [comment]
@arnoutvandervorst The code (that triggers this bug in the analyzer) is not in your project, but in the combination of the packages `riverpod` and `provider_something`, specifically because of using non-function type aliases.

I don't know about releasing. Maybe @devoncarew  will know.
