### ISSUE TITLE
bool.fromEnvironment('dart.library.html') not working in dev_compiler?

### ISSUE THREAD

**Issue by ditman** [dart-lang/sdk#47207]
While using some code that looks like this:

```dart
 const _forbiddenHeaders = bool.fromEnvironment('dart.library.html') 
     ? <String>{'user-agent', 'content-length'} 
     : <String>{};
```

I encountered the following bug: https://github.com/google/googleapis.dart/issues/298.

When using the above code in a Flutter app, in development mode in a browser, the `_forbiddenHeaders` are an empty set, but when running in `--release` mode, they're correctly set.

It seems that `bool.fromEnvironment('dart.library.html')` is not working in the dev_compiler?

Here's some more info about my system:

```
$ dart --version
Dart SDK version: 2.15.0-96.0.dev (dev) (Fri Sep 10 02:32:22 2021 -0700) on "linux_x64"

$ flutter --version
Flutter 2.6.0-6.0.pre.76 • channel master • git@github.com:ditman/flutter.git
Framework • revision fad5e4cf89 (4 hours ago) • 2021-09-13 13:37:07 -0700
Engine • revision abb1980f65
Tools • Dart 2.15.0 (build 2.15.0-96.0.dev)
```

OS: `gLinux`
Browser: Chrome `Version 93.0.4577.63 (Official Build) (64-bit)`

**Comment by lrhn** [comment]
Try using `const bool.fromEnvironment("dart.library.html")` and see if that helps.

The const computations should be handled by the front-end, but this is not `const`, and the dev-compiler might not support non-const environment checks.

**Comment by jakemac53** [comment]
One thing I noticed here is that during summary generation we don't appear to be adding in these defines.

When running DDC we go through this code path https://github.com/dart-lang/sdk/blob/b1491fc43ec037867f596c24b98aa6ad5fa8fd73/pkg/dev_compiler/lib/src/kernel/command.dart#L117 which adds all of these environment variables https://github.com/dart-lang/sdk/blob/b1491fc43ec037867f596c24b98aa6ad5fa8fd73/pkg/dev_compiler/lib/src/compiler/shared_command.dart#L28.

But when summarizing for DDC I see no equivalent code https://github.com/dart-lang/sdk/blob/main/pkg/frontend_server/lib/compute_kernel.dart#L200. It could be getting added somewhere else along there though... not sure.

**Comment by ditman** [comment]
> Try using const bool.fromEnvironment("dart.library.html") and see if that helps.

@lrhn I tried: `const _forbiddenHeaders = const bool.fromEnvironment('dart.library.html')...` but it did **not** help.

**Comment by nshahan** [comment]
An update on my investigation: it doesn't look like the issue is in the compiler directly but more in the integration of how the compiler is invoked. When running a command line DDC compile this code works fine. That is because we manually add these environment variables here:
https://github.com/dart-lang/sdk/blob/775df25714b8110539925f3d185655730c507744/pkg/dev_compiler/lib/src/kernel/command.dart#L821-L822

That code is called by the command line runner, as well as the expression compiler worker.

I don't see any sign that we have ever added these environment variables on the flutter web development builds. I'll continue to dig and find the right spot to make sure they get added to fix this issue. Long term we should centralize these to a single location that applies to all DDC compiles. The DevCompilerTarget perhaps.
