### ISSUE TITLE
[libs enhancement] Map class operator [] parameter type

### ISSUE THREAD

**Issue by KristianBalaj** [dart-lang/sdk#47201]
`Map<K, V>` type in the dart.core has type `Object?` on its [] operator parameter.

**Definition:**
`V? operator [](Object? key);`

## Enhancement
What is the reason behind the `Object?` parameter type? Why don't we have it the `V?`? 
It can lead to nasty bugs and makes the refactoring harder, too.

**Comment by lrhn** [comment]
The current type allows you to assign a `Map<String, X>` to `Map<Object, X>` and keep using it for lookups without issues.

**Comment by paulsump** [comment]
It's annoying when people close issues when they still exist.  Where are we supposed to mention it now?  "As designed" and "As intended" just ignore the problem.  The reason given isn't a good enough one because the number of use cases for assigning a map to another map are minimal compared with the number times people use operator[] and containsKey() with the incorrect key!

**Comment by KristianBalaj** [comment]
In my opinion it is a bad design decision for sure.
And to sacrifice static typing for a single simplification is like using a cart without wheels all year just because the winter will come and I could slide down the hill in the winter.
