### ISSUE TITLE
Dart Measurement of code portion runtime using Stopwatch is incorrect/illogical.

### ISSUE THREAD

**Issue by MohaAmiry** [dart-lang/sdk#47245]
my objective is To calculate the time required to execute a code portion.

the following code contains 3 different watches with the same test sample but every test result in different time (less time than previous test in most cases for reasons i'm eager to understand), can someone explain to me in details how does stopwatch work in dart, and why it behave like it does?
and I want an accurate way to test the runtime -time complexity- of multiple code portions.

Thanks!

```dart
void main(List<String> arguments) {
	Stopwatch watch1 = new Stopwatch();
	Stopwatch watch2 = new Stopwatch();
	Stopwatch watch3 = new Stopwatch();

	watch1.start();
	for (var i = 0; i < 30000; ++i) {}
	print('Watch1 runtime is : ${watch1.elapsed}');
	watch1.stop();

	watch2.start();
	for (var i = 0; i < 30000; ++i) {}
	print('Watch2 runtime is : ${watch2.elapsed}');
	watch2.stop();

	watch3.start();
	for(var i = 0; i < 30000; ++i) {}
	print('Watch3 runtime is : ${watch3.elapsed}');
	watch3.stop();
}
```

The code output for me is:

**Watch1 runtime is : 0:00:00.002375
Watch2 runtime is : 0:00:00.001545
Watch3 runtime is : 0:00:00.000054**

**Comment by lrhn** [comment]
Those results are quite possible. Whether you are running on the VM or compiled to JavaScript and running a browser, your code is being JIT compiled and optimized. That means, among other things, that the first time you call a function, it's slower than the next time, because it might even be compile on-demand the first time. It might also be optimized on later invocations, or even *while* being run, for long-running functions. And when optimizing, it might be clever enough recognize that a particular code pattern never does anything useful.

That makes it hard to create meaningful benchmarks. The rules of thumb for benchmarking JIT code includes:
* Warm up the code before measuring. Run it of at least a little time before you start measuring, to ensure the code is compiled and possibly optimized.
* Do real, measurable work. Your `for` loop should be completely eliminated by a decent optimizing compiler because it has no effect on anything after it. Optimizing it to no code at all is valid. At that point, all you test is `watch.start();watch.elapsed;`
* Avoid doing work you don't want to measure. If you want to test the speed of assignment, don't put the assignment into a function and call the function for each assignment. Calling a function is orders of magnitude more expensive than assignment.
* Run for a while. If your test *can* be done in 54 microseconds, you're probably measuring your measurement code at least as much as the code you want to test. 

You can try using the [benchmark harness](https://pub.dev/packages/benchmark_harness) package. Even there, make sure that the code of your `run` function does some amount of real work.

**Comment by MohaAmiry** [comment]
> make sure that the code of your `run` function does some amount of real work.

Thank you!
before i post this issue, i was trying to measure 2 real codes, i had 2 algorithims to the same function which i wanted to see which one is better without calculating the time complexity manually, although one work substantially different than the other, i had the same issue for reasons still not clear for me, **what every i run first, takes longer time than the second test**.


> Warm up the code before measuring. Run it of at least a little time before you start measuring, to ensure the code is compiled and possibly optimized.

but i think this advice could lead to incorrect results depending on my researches, from what i found, the smart compilers when they see a duplicated use of specific behavior (code) over and over, it saves the results in the memory so it doesn't calculate the results over and over.
this mean the first iteration trough code "x" could be much slower than iteration 5, and so on.
So, if someone ran the code once will get slower results than the one who ran it multiple time.

but in my case, i have 2 very different codes in the way they were wrote, this lead me very confused, i will try (benchmark harness) package and reply you with my results

**Comment by lrhn** [comment]
The first code taking longer than the second one is very much expected. You are likely JIT compiling parts of the runtime system as well, like, say, `int.operator+` or `List.add`, as well as your own code. Not to forget `Stopwatch.elapsed` itself. If the second code uses the same platform operations, those will already be warm. So, run *both* of them for a while before starting to measure. (You can run into situations where the second code is slower if you warm up the first code, then measure that code, then warm up the second code and then run that, because the first code might seem to be using a function "monomorphically", like only ever calling `ListBase.first` on one particular kind of list, and the JIT can optimize that very efficiently as a direct access to that list's `length`, and then the second code ends up calling it on a different kind of list, and then the JIT has to de-optimize again. So, warm up all the code before measuring.)

For smart compilers choosing to cache a result, that requires the compiler to be able to detect that the code has no side effects other than computing the result *and* that the result is not used. Side effects can include non-termination and throwing, which makes it highly unlikely that any even moderately complicated code can be completely eliminated, at least as long as you use the result of the computation in some way afterwards. So, generally, remember the result of the computation, then check it afterwards, in some trivial way (like `!= 0` when *you* know the result is not zero).

The [benchmark harness does](https://github.com/dart-lang/benchmark_harness/blob/master/lib/src/benchmark_base.dart#L53) what I usually also do myself: Warm up for ~100 ms then run the test for ~2 seconds and count how many iterations you manage. That warm-up is long enough to trigger most optimizations. As explained above, I'd actually make sure to call `warmUp` on *every* benchmark object that I want to measure in the same program before I start measuring any of them for real, to ensure that none of them get the benefit of being monomorphic jsut by being first. Alternatively have one program for each benchmark, so they all get to go first.
(You can still end up measuring monomorphic behavior that won't happen in a real program. No benchmark is guaranteed to match real-life behavior other than benchmarking your actual application. All it can do is to show an upper bound on actual performance.)
