### ISSUE TITLE
js-interop: JS$ encoding scheme isn't working for @anonymous object literals declaration

### ISSUE THREAD

**Issue by richexp** [dart-lang/sdk#47271]
I'm adopting Mongo Realm Web SDK in my Flutter Web app.
I've encountered problem with defining anonymous class for object literal in JS.
As far as Mongo Realm starts names for some fields with underscore ('_') and I cannot change this, I need to reflect this structure in Dart code.
So I have such declaration
```
@JS()
@anonymous
class CollectionFilter {
   external String? get _id;
   external String? get sessionId;
   
   external factory CollectionFilter({String? _id, String? sessionId});
}
```
Obviously, Dart doesn't except this with  "Error: An optional named parameter can't start with '_'."

In #26468 I have found a suggestion to use JS$ encoding scheme as a workaround for JS property names that are not public Dart names.

So, I changed my code to 
```
@JS()
@anonymous
class CollectionFilter {
   external String? get JS$_id;
   external String? get sessionId;
   
   external factory CollectionFilter({String? JS$_id, String? sessionId});
}
```
But that didn't help (reflected JS object had field with exact name JS$_id as in Dart declaration). 
So my question: is this behaviour expected? And if so, what is the right way to workaround JS property names with underscores in object literals?

I'm using Flutter 2.5.0 with Dart 2.14.0

**Comment by sigmundch** [comment]
Thanks for the question @richexp!

/cc @srujzs @rileyporter 

I too was expecting also your second example to work. It appears that dart2js, our deployment compiler, supports it (which is enabled in the `--release` and `--profile` modes in flutter run), but DDC, our development compiler, does not.

We are moving in a direction where JS-interop is more static, and in doing so we'll be able to allow things like exposing Dart names differently than JS names. We hope this will have a cleaner solution going forward. Because of that, I believe it's unlikely we'll add support for `JS$` in DDC at this time.

Today, one thing you can do is to use static extension methods to expose the name you want  and use `dart:js_util` to implement the underlying access. Unfortunately that means also using `js_util` to create an anonymous JavaScript object, instead of using the terse syntax of `package:js` for the constructor.

In your example this may look as follows:
```dart
@JS()
library foo;

import 'package:js/js.dart';
import 'dart:js_util' as js_util;

@JS()
@anonymous
class CollectionFilter {
}

// Note: ideally this would be a non-external factory constructor in CollectionFilter, but
// it appears DDC doesn't support that today either, so I had to move it to a top-level method.
CollectionFilter createCollectionFilter({String? id, String? sessionId}) =>
  js_util.jsify({'_id': id, 'sessionId': sessionId});


extension CollectionFilterExtension on CollectionFilter {
  // Note: external extension methods are not yet supported in 2.14, but starting in Dart 2.15, you
  // will be able to write this using package:js syntax, just like you do with static methods:
  //     @JS('_id')
  //     external String? get id;
  String? get id => js_util.getProperty(this, '_id');

  // this too, will just be:
  //     external String? get sessionId;
  String? get sessionId => js_util.getProperty(this, 'sessionId');
}

main() {
  var x = createCollectionFilter(id: '2');
  print(x.id);
}
```

Hope this helps get you unblocked!

**Comment by richexp** [comment]
Thanks for so fast and furious reply, @sigmundch @srujzs!

I will use suggested workaround while waiting for future js-interop enhancements
