### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [dart-lang/sdk#47336]
Hi , i try to make a hashtag text with using regex but i have this issue .
- when i try to match text with [a-z] it also match single quote (') and some symbol char 
- My code : 
```
final hashTagRegExp = RegExp(
    "#(?![0-9_]+\b)([a-zA-Z0-9_])+",
    multiLine: true,
  ); 
```
could u help me to resolve this issue ?

**Comment by lrhn** [comment]
I am guessing that you also want to move the last `+` inside the capturing parentheses:
```dart
final hashTagRegExp = RegExp(r"#(?![0-9_]+\b)([a-zA-Z0-9_]+)"); 
```
I removed the `multiLine: true` because it makes no difference for a RegExp that does not contain any `^` or `$` assertions.

Another way to write the same capture, but without needing lookahead, would be:
```dart
final hashTagRegExp = RegExp(r"#([\d_]*[a-z][a-z\d_]*)", caseSensitive: false); 
```
That matches a `#` followed by any sequence of digits, letters and underscores which contains at least one letter.
Used `\d` instead of `0-9` and made it not case-sensitive to not have to repeat `a-z` as `A-Z` too.

**Comment by lrhn** [comment]
###
