### ISSUE TITLE
dart2js not working if we import the dart:ui library

### ISSUE THREAD

**Issue by parthipanr** [dart-lang/sdk#47348]
I have created the simple hello world application and import the dart:ui library. Then try to build the dart file to using dart2js tool but facing below error.

![image](https://user-images.githubusercontent.com/15604974/135593365-3099a821-49bf-4eca-9224-c124a93d7f7e.png)

Please let me know whether I have to enable any other option for it.

**Comment by lrhn** [comment]
The `dart:ui` library comes from Flutter, it's not part of the core Dart platform.

You need to compile the program with the `flutter` command instead of `dart2js`. (I do not know precisley how to make `flutter` compile for the web, but [the Flutter for the Web page](https://flutter.dev/docs/get-started/web) might say so).

So, working as intended, `dart2js` does not know of any `dart:ui` library.
