### ISSUE TITLE
Document the `include` directory of the SDK

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#47376]
When you download a Dart SDK, the uncompressed `dart-sdk` directory contains an `include` directory. This directly isn't mentioned in the [README file](https://github.com/dart-lang/sdk/blob/main/README.dart-sdk), or on dart.dev. We should document that this is, and what it can be used for.

**Comment by jcollins-g** [comment]
Sort of a soft yes that it is required?  It's probable that SDK documentation is not generated directly except as a test that dartdoc works, or as part of the build system, which we do all the time.   It could be moved into `lib` easily in the bundled SDK.  It's a bit more work to move it somewhere else.

**Comment by jcollins-g** [comment]
There is a use case I forgot to mention.

If it was removed entirely, developers changing documentation in the SDK would have to either follow special instructions to build dartdoc for the SDK to check for errors rather than simply `dartdoc --sdk-docs` as they do now, or risk that dartdoc would not catch the same set of errors that the build system does in documentation comments.  I'd really rather not cause that.  Moving to `lib` is quite possible though.

**Comment by mit-mit** [comment]
Fixed in https://dart-review.googlesource.com/c/sdk/+/215840
