### ISSUE TITLE
Observatory/VM service/debugger messages are inconsistent

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#47427]
This started as a discussion in the docs update in https://github.com/dart-lang/site-www/pull/3610; migrating to the SDK to track from there.

### CLI

```
mit-macbookpro5:d1 mit$ dart run --observe
Observatory listening on http://127.0.0.1:8181/bsWKvM9gpgM=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/bsWKvM9gpgM=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2FbsWKvM9gpgM%3D%2Fws
Building package executable...
```

### VSCode

```
Connecting to VM Service at http://127.0.0.1:54736/Bnu49u4zzUs=/
```

### Android Studio

```
/Users/mit/dev/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts --pause_isolates_on_start --enable-vm-service:55500 /Users/mit/tmp/d4/bin/d4.dart
Observatory listening on http://127.0.0.1:55500/RJJVKUi_B44=/

The Dart DevTools debugger and profiler is available at: http://127.0.0.1:55500/RJJVKUi_B44=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A55500%2FRJJVKUi_B44%3D%2Fws

```

### CLI

```
mit-macbookpro5:f1 mit$ flutter run
...
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                            9.0s
Debug service listening on ws://127.0.0.1:55608/bE2YLrarz5I=/ws
Syncing files to device iPhone 13...
```

### VSCode

```
Launching lib/main.dart on iPhone 13 in debug mode...
lib/main.dart:1
Xcode build done.                                           21.2s
Connecting to VM Service at ws://127.0.0.1:54829/_ZBNGvqr4Nk=/ws
```

### Android Studio

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           22.0s
Debug service listening on ws://127.0.0.1:55327/c-7MM7V1wsk=/ws
Syncing files to device iPhone 13...
```

**Comment by mit-mit** [comment]
A general question for the three ones in Flutter: What is the point of the `ws://127.0.0.1:54829/_ZBNGvqr4Nk=/ws` style urls? cc @bkonyi @jacob314

**Comment by DanTup** [comment]
> @DanTup you mentioned in dart-lang/site-www#3610 that the VSCode status text comes from a debug adapter. But why is it that the message differs for Dart & Flutter projects?

Do you mean the URI? The text part of the messages printed by the debug adapter should be the same. From the examples above:

```
Connecting to VM Service at http://127.0.0.1:54736/Bnu49u4zzUs=/
Connecting to VM Service at ws://127.0.0.1:54829/_ZBNGvqr4Nk=/ws
```

(the other output in the Flutter VS Code example is just build progress written to flutter_tools stdout even in `--machine` mode that's passed through)

I'm not certain if the URLs are different because the tools output them differently, or the Dart/Flutter debug adapters are slightly inconsistent with where they clean the URLs up, but I think they should probably both by the second (`ws`) URL.

The first URL (`http`, without `/ws`) is the endpoint hosting the Observatory web app and the second is the endpoint of the VM Service WebSocket. Most tools (VS Code, DevTools, IntelliJ) are coded to understand how to map the first one onto the second (because when they were scraping it from the output, they had to). I think it's better for the tools _not_ to have to clean up the URIs and instead, flutter_tools and `--write-service-info` should always provide the _actual_ VM Service URL. This would avoid some niggles that came up in the past (for example someone launching a custom tool that emulated Dart's `--write-service-info` and we were unexpectedly appending `/ws` to their VM Service URI where it shouldn't have been).

**Comment by mit-mit** [comment]
This was addressed a while back; closing

```
mit-macbookpro6:testapp mit$ dart run --observe
The Dart VM service is listening on http://127.0.0.1:8181/Hy5FZd7bHDo=/
```
