### ISSUE TITLE
[Question] Dynamically set system environment variables at runtime

### ISSUE THREAD

**Issue by ggdream** [dart-lang/sdk#47423]
Hello, I'm sorry to ask questions here, because I Googled for a long time and there is no relevant discussion, only the way to pass parameters from the command line. Because it is very urgent, I am asking questions here. 

How can I achieve this effect? Thank you all.

**Comment by lrhn** [comment]
There are two "environments" available to Dart.
* The OS process environment available through [`Platform.environment`](https://api.dart.dev/stable/2.14.3/dart-io/Platform/environment.html). I believe it's immutable and cached on first access, so no luck there. (It's probably immutable because it's shared between all isolates, and we don't want the isolates to affect each other.)
* The Dart compilation environment available through [`String.fromEnvironment`](https://api.dart.dev/stable/2.13.4/dart-core/String/String.fromEnvironment.html). That environment is set at compile-time and cannot be changed.

If you need to run Dart with a different system or compilation environment, you most likely need to start a new Dart process, and you need to have the `dart` JIT-compiled runtime available for that.
Example: <code>[Process.run](https://api.dart.dev/stable/2.13.4/dart-io/Process/run.html)([Platform.resolvedExecutable](https://api.dart.dev/stable/2.13.4/dart-io/Platform/resolvedExecutable.html), ["-DmyEnv=myValue", "my_script.dart"])</code>.
