### ISSUE TITLE
Enums in Dart ffi

### ISSUE THREAD

**Issue by EhsanAramide** [dart-lang/sdk#47544]
How can we use enum and pass them to C functions from dart code
For example
```c
// c code
typedef enum my_enum {
  one, two, three
} my_enum_t;

void use_my_enum(my_enum_t instance);
```
Now in the dart side how can we pass the enum instances to `use_my_enum` function?

**Comment by dcharkes** [comment]
@EhsanAramide We've explored using enums in `package:ffigen`. But since C enums can have duplicate entries there's no clear way to do a mapping.

For more details see the discussion in https://github.com/dart-lang/ffigen/issues/114#issuecomment-715903493

If we are going to support (a subset of) enums, it is likely going to be in `package:ffigen` rather than `dart:ffi`. Feel free to chime in the discussion there.
