### ISSUE TITLE
dart2js does not execute code in a certain case

### ISSUE THREAD

**Issue by timothysteward-wk** [dart-lang/sdk#47566]
I think I found an issue with dart2js where it skips part of the code.

In the following example dart2js skips the print on line 30 (`  print('function exited');`).

```dart
import 'dart:async';

Future main() async {
  print('program started');

  final value = true;

  final value2 = value ?? false;

  await foo(value2);

  print('program exited');
}

Future<void> foo(bool value) async {
  print('function started');

  if (value) {
    final result = await bar();
    switch (result) {
      case 1:
        print('breaking');
        break;
      case 0:
        return;
    }
    print('switch complete');
  }

  print('function exited');
}

Future<int> bar() async => 1;
```

When I run using dart2js, the code above outputs the following (notice `function exited` is missing).
```
program started
function started
breaking
switch complete
program exited
```

When I run using ddc or dart vm, the code outputs the following:
```
program started
function started
breaking
switch complete
function exited
program exited
```

My software versions are as follows:
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "macos_x64"
Google Chrome: 96.0.4664.18 (Official Build) beta (x86_64)
macOS: 11.6

**Comment by rakudrama** [comment]
@sigmundch I think this is a different issue. In this case the generated JavaScript _seems_ ok before the js-to-js transform for generators. Afterwards the `A.print("function exited");` is in the wrong place. I say _seems_ because it is nearly impossible to print JavaScript before the deferred elements are finalized. I think my next step is to confirm this, perhaps improving the debugging JavaScript printing to work for non-finalized AST nodes.

**Comment by rakudrama** [comment]
Fix avail: https://dart-review.googlesource.com/c/sdk/+/219746
