### ISSUE TITLE
NPE in LSP refactoring

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#47647]
```
Thread 0 main threadNoSuchMethodError: NoSuchMethodError: The method '[]' was called on null.Receiver: nullTried calling: []("applied")
at Object.noSuchMethod(dart:core)
at ApplyWorkspaceEditResponse.fromJson(protocol_generated.dart:229)
at SimpleEditCommandHandler.sendWorkspaceEditToClient(simple_edit_handler.dart:81)
at <asynchronous gap>(async)
at PerformRefactorCommandHandler.handle.<fn>.<fn>(perform_refactor.dart:100)
at <asynchronous gap>(async)
at ServerStateMessageHandler.handleMessage(handlers.dart:189)
at <asynchronous gap>(async)
at LspAnalysisServer.handleMessage.<fn>(lsp_analysis_server.dart:330)
```

@DanTup 

Which looks strange, I would expected cast exception in `simple_edit_handler.dart:81` where we cast `editResponse.result as Map<String, Object?>`. Maybe we run LSP in google3 without null safety?

**Comment by scheglov** [comment]
It looks that the server is null safe, at least I see `dart_package(null_safety = True)` in the `BUILD` file.

I don't see anything about the client :-(

**Comment by DanTup** [comment]
> It looks that the server is null safe, at least I see `dart_package(null_safety = True)` in the `BUILD` file.

hmm, the error seems odd then. Although I don't think whether null safety was on or not changes the issue here (only the error message/location it failed). The real issue is that the server got a response from the client that seems invalid.

Was the exception reported by a user, or come from something logging the exceptions? If the former, is it possible to ask them about their client/editor? If the latter, is it possible to have the `--client-id` and `--client-version` flags recorded with the exceptions so if this comes up again it will be easier to track down?

My feeling is that this is a client bug (eg. whatever editor the user was using is not strictly following the spec - it returned a response to the server without an `error` or a `result`) rather than a Dart/server issue. It would be nice to confirm that though (and if required, file a bug with whatever that LSP client is).

**Comment by scheglov** [comment]
Was I wrong guessing that we should get the cast exception earlier in null safe mode?

It was logged, not reported. We configure the reporter [here](https://github.com/dart-lang/sdk/blob/dd3759d9ccb6b7f81dc7a407fc51e9f8596c80c7/pkg/analysis_server/lib/src/server/driver.dart#L210). I also see that we put some data about the client into the analytics session, but how it is used, I don't know.

**Comment by DanTup** [comment]
> Was I wrong guessing that we should get the cast exception earlier in null safe mode?

I don't think so, I would also have expected the error that you noted. I can't explain why that didn't happen though (unless it was not running with null safety, but I don't know about this environment so I don't know how that could have been the case).

It looks like the client ID is recorded in the "Application Installer ID" and the version in a custom dimension:

```
    // Record the client name as the application installer ID.
    analytics.setSessionValue('aiid', analysisServerOptions.clientId);
    if (analysisServerOptions.clientVersion != null) {
      analytics.setSessionValue('cd1', analysisServerOptions.clientVersion);
    }
```

I don't know if that's accessible from the exception reports though. It would be useful to know - for example if it's not VS Code, but Vim or Emacs or something, that might help track down the bug and file an issue the respective client.

**Comment by scheglov** [comment]
We could try to add the client id/version [here](https://github.com/dart-lang/sdk/blob/e916841bcc5687e5fea4221d9fdbee2ccc3e412e/pkg/analysis_server/lib/src/lsp/lsp_analysis_server.dart#L401). It would be nice to have them as fields, but in `CrashReportSender` it would be too specialized for DAS. Or we could make it possible to add new fields to it. @devoncarew do you see issues with this?

**Comment by DanTup** [comment]
@scheglov do you know if this has been seen recently?

**Comment by scheglov** [comment]
No, actually we have very few crashes internally these days.

**Comment by DanTup** [comment]
Ok, then I guess we should close this unless we see it occurring again. Thanks!
