### ISSUE TITLE
Problems around versioning of the DL API (dart_api_dl.h).

### ISSUE THREAD

**Issue by rustonaut** [dart-lang/sdk#47649]
`Dart_InitializeApiDL` only checks the major version to allow grater compatibility of plugins.

There is no good way to get the exact DL API version except accessing the "implementations details" here:

https://github.com/dart-lang/sdk/blob/217367abd1b674e425cdf9333f2d3aefa891f5b5/runtime/include/internal/dart_api_dl_impl.h#L16-L17

For newly added functions this isn't to big of a deal as you can just check if they have been set after `Dart_InitializeApiDL` was called.

But for newly added variants of `CObject` it's troublesome.

Especially with the update from 2.14 to 2.15 the DL api is dumped from 2.0 to 2.1, add a new variant `as_native_pointer` but don't add a new function.

I might be overlooking something but I'm not sure how bindings should be able to detect weather they can use `as_native_pointer` or not.

I think the easiest fix would be to introduce some accessor function(s) which allow you to access the major/minor function of the `initializeApiDLData `-pointer while still keeping the implementation details  (`DartApi`) hidden.  (Preferable functions and not macros as it makes it easier to auto-gen bindings for other languages, either two separate functions, or one function with two "out-parameters".)

**Comment by rustonaut** [comment]
Edit just to be clear the version *is* accessible in dart using `NativeApi`, it's just not (properly) accessible in code binding to `dart_api_dl.h`.

**Comment by rustonaut** [comment]
I also just realized that the [minor version](https://github.com/dart-lang/sdk/blob/f6a43e5eb71d0168b5db23bb4b31d3f58029981e/runtime/include/dart_version.h#L14) wasn't bumped. But should have been bumped IMHO as `Dart_CObject` has a new variant.

**Comment by dcharkes** [comment]
Thanks for reporting @rustonaut.

#### Bump major version for Dart_CObject change

> I also just realized that the [minor version](https://github.com/dart-lang/sdk/blob/f6a43e5eb71d0168b5db23bb4b31d3f58029981e/runtime/include/dart_version.h#L14) wasn't bumped. But should have been bumped IMHO as `Dart_CObject` has a new variant.
> 
> That bump probably still should go into 2.15 🤔

https://github.com/dart-lang/sdk/blob/1ade4ab96ff841cc847b6a043ceeb5063efc8591/runtime/include/dart_native_api.h#L91-L92

I think we should have bumped the major version even. Because receiving a `Dart_CObject` in native code which is built against an older implementation can lead to crashes.

FYI @a-siva on bc387837c4f1162d23a1434a8715ec4175fed9be

I'll create the bump and file a cherry pick for 2.15.

#### Make versioning accessible in native code

> Just to be clear the version _is_ accessible in dart using `NativeApi`, it's just not (properly) accessible in code binding to `dart_api_dl.h` and you can work around the problem by relaying on the dart side of you plugin passing it to the native side of your plugin.

That would indeed be a nice addition.

#### Version issues in general

In https://github.com/flutter/flutter/pull/94101 we had some more discussion around the versioning of `dart_api_dl.h`.

* Can we get a guarantee for ABI stability? We would break all flutter FFI plugins on bumping the major version (like we have to do now).
* Can we make `dart_api_dl.h` standalone to limit the API surface? This requires copying some definitions and macros from `dart_api.h` and `dart_native_api.h` ([gist](https://gist.github.com/dcharkes/6371a0088a6057d754d6a259c60e19f9)). It is probably cleaner to move them to a separate standalone file. In any case we need to add tests that the version number is bumped when these are changed to prevent future breakage.

**Comment by dcharkes** [comment]
> I think we should have bumped the major version even. Because receiving a `Dart_CObject` in native code which is built against an older implementation can lead to crashes.

Thinking about this a bit more, this can only crash if you have hand out a port created in native code to some Dart code that you don't own yourself that would send objects of the new type. So, maybe that is rather unlikely. (Though certainly possible.)

@rustonaut what is the use case where you ran in to this?
@mraleph @mkustermann what are your 2 cents on this? (I've added this to the next sync agenda as well.)

**Comment by rustonaut** [comment]
I'm writing dart bindings to (part of) `dart_api_dl.h`, as well as some library-bindings using it.

> So, maybe that is rather unlikely.

I agree, I haven't ran into that and if you ran into it you basically get a `Dart_CObject` with a tag you know nothing about, which is a case which should be handled anyway (I think). This is why I proposed a minor change (overlooking the doc comment). 

But as it's documented to lead to a major version change we probably should do that as people might do unexpected things where they rely on it.

Through we could update the comment with the major version change to allow minor braking changes for new variants, as long as the dart VM doesn't produce them for values where it previously produced something else (for sending supported data types). And as long as the size of the `Dart_CObject` doesn't change due to the new variants in the union.
