### ISSUE TITLE
DateTime add(Duration(days: 1)) does not consider DST, but difference() does

### ISSUE THREAD

**Issue by gottfired** [dart-lang/sdk#47666]
* Library: time
* Dart SDK Version: 2.14.3

Running the following code on a machine in Europe/Vienna

```
var a = DateTime(2021, 10, 31);
print("${a.add(Duration(days:1))}");
```

prints `2021-10-31 23:00:00.000`

I would expect `2021-11-01 00:00:00.000`

especially since the following code is correctly taking DST into account

```
final end = DateTime(2021, 11, 1);
final start = DateTime(2021, 10, 31);
final duration = end.difference(start);
print("Duration $duration");
```

correctly prints `Duration 25:00:00.000000` instead of 24:00

**Comment by gottfired** [comment]
Also consider, that other languages like e.g. golang do this correctly: https://play.golang.org/p/Mx0REwHQp-b

**Comment by DanTup** [comment]
I think this may be expected behaviour because these are local times and a 1-day Duration is always 24 hours - see https://github.com/dart-lang/sdk/issues/44014#issuecomment-720388984.

And in the [Duration](https://api.dart.dev/stable/2.10.3/dart-core/Duration-class.html) docs:

> Durations are context independent. For example, a duration of 2 days is always 48 hours, even when it is added to a `DateTime` just when the time zone is about to do a daylight-savings switch. (See [DateTime.add](https://api.dart.dev/stable/2.10.3/dart-core/DateTime/add.html)).

**Comment by gottfired** [comment]
Yes, I've read that. I just find it very inconsistent, that subtracting the two days yields 25h, which is correct, but adding doesn't take DST into account. Especially frustrating since golang does ist correctly and is also developed by Google ;)

**Comment by lrhn** [comment]
It would require a change to `Duration` to store calendar days separately from clock time. Not impossible, but different from what we are doing now, and therefore a breaking change.

It also requires some design.

If I have a duration of "one day and 20 hour", and I add it to noon the day before daylight saving starts/ends, are the hours added before or after the day? The result is going to differ by one hour depending on that choice.
If we introduce "months" and "years" as well, which are also not a fixed amount of the lower unit, we need to answer that question in general. And if we do, say, days before hours for addition, should we do it in the other direction for subtraction, because otherwise the two won't be inverses? Should adding a negative duration be taken as a subtraction then, so adding `duration` and then `-duration` gets you back to where you started (most of the time)?
Or should we just give you what `DateTime(dt.year + dur.years, dt.month + dur.months, dt.day + dur.days, dt.hour + dur.hours, etc)` would give you. (I'm not sure I can predict what that is in general, but it's definitely a consistent behavior).

We can definitely do *something*, but it's not clear that it's always going to be the thing that the user wants.
That's why we are a little wary about doing anything about this (that, and it being breaking).

**Comment by gottfired** [comment]
Ok, I see the problem. Those are all very valid points. Maybe a solution would be to go the golang Route and add a separate DateTime.addDate() function that only accepts years, months, days?

From the golang docs:

```
func (t Time) Add(d Duration) Time
func (t Time) AddDate(years int, months int, days int) Time
```

Add(d Duration) is equivalent to Dart's add(Duration) and ignores DST. AddDate() is DST/timezone aware.

This also wouldn't be breaking. It could be implemented already as an extension, but seems quite essential and might be worth considering for the standard library.

**Comment by lrhn** [comment]
Adding only calendar years/months/days does avoid some of the problems, but not all. You can still start with a date and time where that time doesn't exist at the resulting date (because of daylight saving starting), or where there are two (because of daylight saving ending) but it's less likely to be a problem.

The extension would be easy:
```dart
extension DateTimeAddDate on DateTime {
  DateTime addDate({int years = 0, int months = 0, int days = 0}) {
    if (years == 0 && months == 0 && days == 0) return this;
    return isUtc
        ? DateTime.utc(year + years, month + months, day + days, hour, minute,
            second, millisecond, microsecond)
        : DateTime(year + years, month + months, day + days, hour, minute,
            second, millisecond, microsecond);
  }
}
```
You can still run into quirky situations around, especially, daylight saving start:
```
void main() {
  {
    var t = DateTime(2021, 10, 30, 2, 30);
    print(t);
    var t2 = t.addDate(days: 1);
    print(t2);
    var t3 = t2.addDate(days: 1);
    print(t3);
  }
  {
    var t = DateTime(2021, 03, 27, 2, 30); // Assume DST starts March 28th.
    print(t);
    var t2 = t.addDate(days: 1);
    print(t2); // No 2:30, so becomes 3:30
    var t3 = t2.addDate(days: 1);
    print(t3);
    var t4 = t.addDate(days: 2);
    print(t4); // Skips the DST start day, so becomes 2:30
  }
}
```

We *could* add this to the platform. It's easier to add it as an extension method, because someone *might* implement `DateTime` (but, why?!), but it'd be better as an instance methods (because any of those implementations get to return their own type), ... but then it's breaking.

**Comment by gottfired** [comment]
Thanks. Yes, I guess the extension is the best fix for me now. Adding it as a member to DateTime would be ideal imo as it wouldn't breaking. It is also exactly the same behaviour as in golang (I've translated your sample here https://play.golang.org/p/FIRAuz22lJn)

I guess most of the confusion came from the fact that Duration() takes days as a constructor param. Only allowing hours would've been more explicit, because with `Duration(hours: 24)` is immediately clear, that it doesn't take DST into account. But removing days now would be breaking. Maybe you could consider deprecating it for future releases?
