### ISSUE TITLE
[Dart Analyzer] False negative with nullable types in ternary expressions

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#47684]
Dart SDK Version: `2.14.4`

Currently, the following two functions in the snippet of code does not compile:
```dart
class A {
  String? b;
}

String? foo1(A? a) => a?.b != null ? a.b : '';

String? foo2(A? a) => a?.b == null ? '' : a.b;
```

It throws the following errors:
```log
Error: Property 'b' cannot be accessed on 'A?' because it is potentially null.
 - 'A' is from 'scratch_1.dart'.
Try accessing using ?. instead.
String? foo1(A? a) => a?.b != null ? a.b : '';
                                       ^
scratch_1.dart:9:44: Error: Property 'b' cannot be accessed on 'A?' because it is potentially null.
 - 'A' is from 'scratch_1.dart'.
Try accessing using ?. instead.
String? foo2(A? a) => a?.b == null ? '' : a.b;
                                                                 ^
```

However, `a` in these two cases will never be null due to the ternary expression. It's a small issue since we can assign assign `a?.b` to a local variable and then checking the local variable in a ternary expression. Nevertheless, I still think it'll be neat if it was addressed.

**Comment by eernstg** [comment]
It would not be sound to assume that `a.b` is different from null just because `a?.b` turned out to be different from null at an earlier test. There are several reasons why we can't promote instance variables (not even final ones) unless we change the language, but the most immediate one is probably that `b` in the run-time type of the given value of `a` could be a getter that overrides the instance variable declaration:

```dart
class A {
  String? b;
}

String? foo1(A? a) => a?.b != null ? a.b : '';

String? foo2(A? a) => a?.b == null ? '' : a.b;

bool cond = true;

class B extends A {
  String? get b => cond? null : super.b;
}

void main() {
  foo1(B());
}
```

Check out https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+label%3Afield-promotion for more details about this topic.

**Comment by eernstg** [comment]
I'll close this one as a duplicate. @Pante, you might want to give https://github.com/dart-lang/language/issues/1224 a thumbs up in order to make that proposal more visible.

**Comment by Pante** [comment]
Thanks for the quick response!
