### ISSUE TITLE
Unable to manage List<Map<String, String>> using List.contains(Map<String, String>) and List.remove(Map<String, String>)

### ISSUE THREAD

**Issue by omatt** [dart-lang/sdk#47768]
`List.contains(Map<String, String>)` doesn't behave as I expect it to. I'd like to be able to check if `List<Map<String, String>>` contains the `Map<String, String>` that I'm looking for. However, it doesn't work and I have to either iterate on the who List to check or use `List.firstWhere()`

I have the same issue with `List.remove(Map<String, String>)` where I have to use `List.removeAt(index)` as a workaround.

Dart SDK 2.14.4

Minimal repro

```dart
void main() {
  var list = [
    {'name': 'myname'},
    {'name': 'yourname'}
  ];
  print('${list.contains({'name': 'myname'})}'); // not working
  print('${list.firstWhere((map) => map['name'] == 'myname', orElse: () => {}).isNotEmpty}'); // working

  check(list); // working
  list.remove({'name': 'myname'}); // not working
}

void check(List<Map> list) {
  for (var map in list) {
    if (map.containsKey('name') && map['name'] == 'myname') {
      print('myname instance');
    }
  }
}
```

**Comment by mraleph** [comment]
`contains` uses `operator ==` to compare values and `operator==` does not perform deep comparison of maps, so `{'name': 'myname'} ==  {'name': 'myname'}` evaluates to `false`. 

This should explain why `contains` does not do what you expect it to do. 

`remove` has the same behaviour. 

You can use `MapEquality` or `DeepCollectionEquality` to compare collection contents rather than identity. 

You can combine that with `LinkedHashSet` to get a collection which behaves like you want it too: 

```dart
import 'dart:collection';
import 'package:collection/collection.dart';

void main() {
  final set = LinkedHashSet<Map<String, String>>(
      equals: const MapEquality().equals, hashCode: const MapEquality().hash)
    ..addAll([
      {'name': 'myname'},
      {'name': 'yourname'}
    ]);

  print('${set.contains({'name': 'myname'})}');  // => true
  set.remove({'name': 'myname'});
  print(set);  // {{name: yourname}}
}
```
