### ISSUE TITLE
Unhandled exception awaiting Future<List<Future>> when a future completes with error

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#47771]
The following code stops its execution (Unhandled exception) when it await a `Future<List<Future>>` (with a list containing a future that completes with an error).

This looks really strange that `await` has interaction with the inner Future. Is it the expected behaviour?

```dart
import 'dart:async';

void main() async {
  await f();  // even with surrounding try-catch the Unhandled exception couldn't be avoid
  print('after');
}

Future<List<Future>> f() async {
  return [
    (Completer()..completeError('futureError')).future,
  ];
}
```

Running the above code I get the following output

```
$ dart --version
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "linux_x64"
$ dart file.dart 
Unhandled exception:
futureError
```

In my real code I face the same behaviour with a `Future<Map<String, Future>>`.

**Comment by lrhn** [comment]
Sounds like expected behavior. 

You await a future which contains a list.
That list contains another future which nobody ever waits for. That unawaited future completes with an uncaught error (and it does so *before* the future returned by `f` completes), which means it's reported as an uncaught async error to the current zone, which is the root zone, which in native code means that your program crashes.

The `await` does not have any interaction with the inner future, and that's a problem because *someone* needs to interact with an error future, otherwise it is uncaught and the error takes down your program.

The reason you don't see code after the `await` is that the program crashes before the `f()` future completes.

**Comment by a14n** [comment]
Thanks for the explanation. async is sometimes hard :grimacing:
