### ISSUE TITLE
[Analyzer] No quick fix for `Unnecessary type check`

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/sdk#47793]
I wish there were a quick fix for this:
```dart
final int a = 2;
if (a is int) { // Unnecessary type check; the result is always 'true'.
}
```
Suggestion:
In if/while/switch, remove the parameter. If there is nothing remaining, remove the whole expression (leave what is inside intact).

**Comment by bwilkerson** [comment]
That sounds more like an argument for changing the unnecessary_type_check hint to not flag in cases where it might be necessary because of side-effects. @srawlins In case you're interested.

But as for the fix, we don't actually require that fixes be semantics preserving. We assume that developers will use discretion when editing their code.

**Comment by srawlins** [comment]
I vote that we should cater checks like this to being useful in the typical case, and force users to write `// ignore: unnecessary_type_check` in the "getter with side effects" case.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/279351
