### ISSUE TITLE
Declarations tracker takes considerable time when a large number of files are modified

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#47804]
I was looking into https://github.com/Dart-Code/Dart-Code/issues/3692 where it's reported that modifying a large number of files (via a codegen script) causes significant CPU usage for a long time in the server.

The original generation scripts run on Windows, but I slightly simplified the problem and can trigger it on macOS:

- Clone https://github.com/timsneath/win32
- Switch to v3 branch (or specifically 5acb6600 commit)
- Create a file that just rewrites every file in the lib folder with the same content (for reasons I don't entirely understand, running `touch` is not enough to trigger the file watcher in my testing) - the paths assume this is in `tool/v3`:
  ```dart
  import 'dart:io';
  import 'package:path/path.dart' as path;
  
  void main() {
    final libDir = Directory(path.normalize(path.join(
        path.dirname(Platform.script.toFilePath()), '..', '..', 'lib')));
    final entries = libDir
        .listSync(recursive: true, followLinks: false)
        .whereType<File>()
        .where((file) => path.extension(file.path) == '.dart');
    for (final entry in entries) {
      print(entry.path);
      entry.writeAsStringSync(entry.readAsStringSync());
    }
  }
  ````
- Open the project in an IDE
- Wait for initial analysis to complete (this takes around 4 minutes for me the very first time, and only a few seconds once results are cached)
- Run the script pasted above
- Monitor how long re-analyzing the project takes (for me, it is around 15 minutes - over 3x as long as a clean initial analysis)

I've not been able to properly CPU profile this yet (hitting https://github.com/dart-lang/sdk/issues/46612), but I did discover that most of the time was spent in the declarations tracker. If I updated `CompletionLibrariesWorker` to always return `AnalysisDriverPriority.nothing` from `workPriority` and `performWork()` to do no work, then the previous 15 minutes analysis becomes only around 5-10 seconds.

@bwilkerson @scheglov I wonder if there's value in short-cutting this if the files weren't really modified (I think analysis results already do this?). I don't know if that will be a significant improvement in the real-world though (it's likely the files would actually be modified) - although it's still curious that this takes > 3x as long as a clean initial analysis.

**Comment by scheglov** [comment]
I can reproduce this. It looks so far that we continuously send notifications, probably with declarations. I suspect that this is caused by massive re-exports, most probably from `new_win32.dart`. When a single exported file changes, we have to compose the whole set of declarations from all exported libraries and send them. But this does not explain why it takes so long time, when changes have long been done.

**Comment by DanTup** [comment]
FWIW my original testing was with LSP, which shouldn't be sending notifications to the client (the completions are stitched into the list server-side by reading them from `declarationsTracker` in `handler_completion.dart`), so I suspect the notifications might not be the main issue (although, I wasn't able to get CPU profiling working either with LSP enabled/disabled to get any reliable numbers).

> When a single exported file changes, we have to compose the whole set of declarations from all exported libraries and send them.

Ah, interesting. I presume they should only be _computed_ once for each library (unless it is changed) and then the same computed results can be included in any libraries that export that library? (eg. if both `file_a` and `file_b` export `file_c`, they won't both cause `file_c`'s declarations to be recomputed?).

Is there a mechanism to tell if the file _really_ changed, so that the work can be skipped if it didn't? I don't know how common it is, but I suspect at least some code-gen scripts might overwrite files with the same contents, so there could be some benefit in avoiding the work there even if it doesn't solve the entire problem when lots of files really are modified.

**Comment by scheglov** [comment]
It looks that sending notification, specifically both JSON serialization, and outputting the line was expensive.
![image](https://user-images.githubusercontent.com/384794/143946233-186f53dc-08ca-433f-97f2-b7f88ad85a03.png)

But your testing is also correct, because when I disabled sending these notifications, and just output which libraries are changed (always a pair - individual library and `package::win32/new_win32.dart`), e.g. `[(458, package::win32/src/globalization/IOptionDescription.dart), (9135, package::win32/new_win32.dart)]`. And profiling shows that computing is still expensive.
![image](https://user-images.githubusercontent.com/384794/143946649-9e551f46-1688-498e-a537-39e3add7c9d2.png)

Yes, when `a` and `b` export `c`, then declarations of `c` are computed only once. But here we have the opposite - `c` exports both `a` and `b`. So, when both `a` and `b` change, we take each changed file individually - refresh and re-compute damaged data.  So, we take changed `a` and recompute `a` and `c`, send. Then we take `b` and recompute `b` and `c`, send. And `c` here is `package::win32/new_win32.dart` with *a lot* of declarations.

The solution that I'm working now on, is to process all changed files accumulating damage, and then re-compute all at once.

**Comment by DanTup** [comment]
> So, we take changed `a` and recompute `a` and `c`, send. Then we take `b` and recompute `b` and `c`, send.

Ah, gotcha!

> The solution that I'm working now on, is to process all changed files accumulating damage, and then re-compute all at once.

Sounds great, thanks!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/221564

**Comment by DanTup** [comment]
@scheglov thanks! This seems to have made a _huge_ difference. In my contrived script, it went from 15m to < 1 second, and running the real generation script on Windows (which takes around 14 minutes itself), I see analysis starting and completing quickly as the script writes files periodically, and when it completes, the final analysis also completes in < 1 second after the generation script.
