### ISSUE TITLE
[vm/ffi] Adds transition information to FFI leaf calls - product mode

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#47811]
Looks like we missed something in product mode. The test is timing out in product mode.

There are new test failures on [[vm/ffi] Adds transition information to FFI leaf calls.](https://github.com/dart-lang/sdk/commit/bd4a27ff812535cb8480aa1f14109e2c0361e89d).

The tests
```
ffi_2/regress_47594_test Timeout (expected Pass)
```
are failing on configurations
```
app_jitk-linux-product-x64
dartk-linux-product-x64
dartk-mac-product-x64
```

Logs:

* https://dart-ci.appspot.com/log/app-kernel-linux-product-x64/app_jitk-linux-product-x64/10596/ffi_2/regress_47594_test
* https://dart-ci.appspot.com/log/vm-kernel-linux-product-x64/dartk-linux-product-x64/10454/ffi_2/regress_47594_test
* https://dart-ci.appspot.com/log/vm-kernel-mac-product-x64/dartk-mac-product-x64/12360/ffi_2/regress_47594_test

Related issue:

* https://github.com/dart-lang/sdk/issues/47594

**Comment by cskau-g** [comment]
Ak! This is caused by the test itself having:
```dart
// VMOptions=[...] --profiler
```

And the testing framework running all tests with:
```bash
out/ProductX64/dart --ignore-unrecognized-flags [...]
```

Normally passing `--profiler` to a product build will give you the following error and make the process exit with an error code:
```
Setting VM flags failed: Unrecognized flags: profiler
```

But if you pass `--ignore-unrecognized-flags` the process just appears to hang indefinitely, hence the test timing out.

The fix should be to just skip this test in all product builds.

**Comment by cskau-g** [comment]
Correction; there are actually two issues interacting.

The first is the above mentioned `--profiler` failing silently because of `--ignore-unrecognized-flags`.
But unlike my assumption above, the hang is actually due to a second issue, which is that running a `product` build with `--enable-vm-service` makes the process hang.

I have a change on the way for the previously mentioned fix.
And I'll file a separate issue for the latter.
