### ISSUE TITLE
On web, Map.containsKey(key) returns true during Map.putIfAbsent(key, ...) in some conditions 

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#47852]
Hello!

In beta-master channels of Flutter, a weir bug is happening with `containsKey` and `putIfAbsent`, where `containsKey` return `true` when it would actually return `false`

Here is a reproduction code:

```dart
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/material.dart';

void main() {
  final map = <Object?, int>{};
  
  int value = map.putIfAbsent(provider, () {
    print(map.containsKey(provider)); // true, when it should actually be false

    return map.putIfAbsent(provider, () {
      print('never reached');
      return 0;
    });
  });
  
  print(value); // null, when "value" is supposed to be non-nullable
}

final provider = Provider<int>((_) => throw UnimplementedError());
```

Here's a dartpad link https://dartpad.dev/?null_safety=true&id=390dbf79cccb2934af50648dadc510b5&channel=beta

As you can see, this breaks all sorts of things. It even allows non-nullable variables to be `null`

This bug may be related to https://github.com/dart-lang/sdk/issues/47645.
Before, the reproduction code would fail to compile for some funky reasons. With that bug fixed, it seems like what makes the object that causes problem "unique" also breaks `Map.containsKey`

I'm not sure how to make the reproduction code independent from `riverpod`. It seems specific to this `Provider` object, like with https://github.com/dart-lang/sdk/issues/47645, but I failed to reproduce the issue without using the package

**Comment by rebaz94** [comment]
@rrousselGit as the documentation said ``` Calling [ifAbsent] must not add or remove keys from the map.``` but as you already said ```containKey``` should return ```false```

```dart
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/material.dart';

void main() {
  final map = <Object?, int>{};
  
  int value = map.putIfAbsent(provider, () {
    print(map.containsKey(provider)); // true, when it should actually be false

    return 0;
  });
  
  print(value); // 0
}

final provider = Provider<int>((_) => throw UnimplementedError());
```

**Comment by rrousselGit** [comment]
That's not the issue here.
The code given works if it's anything other than `Provider`:

```dart
  int value = map.putIfAbsent(0, () {
    print(map.containsKey(0)); // false, as expected

    return map.putIfAbsent(0, () {
      print('actually called');
      return 42;
    });
  });
  print(value); // 42, as expected
```

**Comment by rrousselGit** [comment]
Rather than being specific to `Provider`, it seems to happen for all classes overriding ==/hashCode.


```dart
void main() {
  final map = <Object?, int>{};
  
  int value = map.putIfAbsent(a, () {
    print(map.containsKey(a)); // true, when it should actually be false

    return map.putIfAbsent(a, () {
      print('never reached');
      return 0;
    });
  });
  
  print(value); // null, when "value" is supposed to be non-nullable
}

final a = Foo();

class Foo {
  operator ==(other) => true;
  get hashCode => 0;
}
``

**Comment by lrhn** [comment]
This doesn't reproduce for me on tip of tree VM/dart2js or in Dartpad. The `print(map.containsKey(a));` examples above all print `false`. How do you run the code? Is it DDC only?

It's tricky code. It really should return false during the call to the value function, because you can't add a key to a map without having a value, and you don't have the value while computing it.
I'm guessing it's an optimization, where we find the place where the key should be, and if it's not there, we immediately put in an entry, then compute the value and store that. That makes the map be in an inconsistent state during the `ifAbsent` call, but avoids having to re-find the position *or* check afterwards that the found slot is still valid.

In practice, we probably should just throw a `ConcurrentModificationErrror` if the map keys change during `ifAbsent`. Then it's safe to not add anything before calling `ifAbsent`. The location we found should still be valid after `ifAbsent` if nothing changed.

**Comment by rrousselGit** [comment]
> This doesn't reproduce for me on tip of tree dart2js (or VM) or in Dartpad.

Here's a dartpad link with the previous snippet that reproduce the issue
https://dartpad.dev/?null_safety=true&id=bae6fa8119f5e4275c0e892953e25ea0

As mentioned, importing flutter is necessary

**Comment by lrhn** [comment]
Ack, by bad. Couldn't read the different layout of the Flutter version of DartPad.

It seems DartPad has two modes, a Flutter mode and a pure Dart mode. The Flutter mode is triggered by having an import of a Flutter library. It's probably checked using a RegExp, because it triggers Flutter mode on a commented out line of `// import 'dart:ui';` too. That's sufficient to trigger the bug, you don't need to do the actual import.

In Flutter mode, the bug is there, independent of channel choice.
In Dart mode, the bug is absent, independent of channel choice.

So, being integrated into the Flutter SDK somehow breaks the web versions of `putIfAbsent` from the Dart SDK.
That *is* odd.

The platform Dart2JS [code for `putIfAbsent`](https://github.com/dart-lang/sdk/blob/b7d2dbe/sdk/lib/_internal/js_runtime/lib/linked_hash_map.dart#L156-L161) is:
```dart
V putIfAbsent(K key, V ifAbsent()) {
    if (containsKey(key)) return this[key] as V;
    V value = ifAbsent();
    this[key] = value;
    return value;
}
```
That looks foolproof. 

Maybe some compiler optimization triggers which replaces this safe code with something "more efficient", but wrong.
But why only in Flutter?

**Comment by rrousselGit** [comment]
Someone on Twitter mentioned that this happens only in debug mode.
Apparently in Flutter release mode, the issue doesn't occur

Not sure if that helps though

**Comment by sigmundch** [comment]
Thanks for all the details!

You are correct, for odd historical and architectural reasons - flutter-mode uses DDC and dart-mode uses dart2js, so this sounds likely like an inconsistency in the development javascript compiler.

**Comment by lrhn** [comment]
That makes sense. The DDC [`putIfAbsent`](https://github.com/dart-lang/sdk/blob/b7d2dbe9b5c7299cae3cf16a748ac476e30e8565/sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart#L171-L201) is quite a lot more complicated, and probably bugged (in particular, line 183 seems premature).

**Comment by nshahan** [comment]
@rrousselGit As always thanks for your issue report! 

I see how the DDC implementation can trigger the behavior that you are seeing but I don't fully agree that there is a bug here based on the example you provided. Calling `putIfAbsent()` in the `ifAbsent` function is unspecified behavior according to the documentation. Is that the pattern that appears in real world code as well?

**Comment by rrousselGit** [comment]
This issue stems from a real-world bug report: https://github.com/rrousselGit/river_pod/issues/980
So it's definitely something that can happen

In my case, the logic was slightly less direct. It was something among the lines of:

```dart
node.map.putIfAbsent(key, () {
  final anotherNode = tree.searchForSomeNode();
  ancestorNode.map.putIfAsbent(key, () => Class());
});
```

In this snippet, it's entirely possible for `node` and `anotherNode` to be different, in which case there's nothing wrong with the code.  
But they can be the same, in which case this issue happens.

I've changed it already to fix the bug. I now use:

```dart
if (!map.containsKey(key)) {
  map[key] = ...
}
```

But even if we don't want to allow such code, I don't think that the current behavior is OK. It's not consistent with how this code behaves on other targets, and this bug can break null safety.

IMO either the behavior should be aligned with other targets (preferably) or the code should throw. The fact that it currently allows assigning `null` to `Object` is problematic

**Comment by nshahan** [comment]
> IMO either the behavior should be aligned with other targets (preferably) or the code should throw. The fact that it currently allows assigning null to Object is problematic

@rrousselGit I agree that consistency between backends is better in most cases, but this sounds more like you are requesting that the API be changed so the behavior _**is**_ specified. I don't think it is a good long term fix to leave it unspecified but expect the unspecified behavior to be the same in different implementations since they can drift over time with updates or optimizations. 

> The DDC putIfAbsent is quite a lot more complicated, and probably bugged (in particular, line 183 seems premature).

@lrhn It looks like to me the code you pointed out is the causes the observed behavior but I can you elaborate on it being a bug?

In this case the DDC implementation has combined the logic of the contains lookup with the put operation to avoid a few extra checks that are not necessary given the expectation that contents of the map does not change when `ifAbsent()` is called. If we undo that without adding a test case then it has the possibility of drifting over time and generally we don't want to add test cases for unspecified behavior. 

It seems that there are a few options going forward. Here they are in the order of complexity as I see it:
1) Leave the DDC implementation as is. This is unspecified behavior so anything it does is considered "correct".
2) Update DDC to have the same behavior as dart2js and the VM. Nice for now, but no guarantee that it will always be consistent in the future.
3) Update DDC to throw an exception. This helps highlight the potential bug at development time, but only on the web.
4) Update the documentation and all backends to throw an exception. Best for consistency across implementations and hopefully catching possible bugs.

Anything I missed?

**Comment by rrousselGit** [comment]
I personally don't care that much about what the fix is, as long as it's not "keep the current behavior"

Albeit unspecified, the current behavior breaks the type system by allowing an unsound assignment.
Being able to assign null to a non-nullable variable sounds like heresy.

**Comment by lrhn** [comment]
It's a bug because `map.containsKey(a)` returns `true` while there isn't actually and entry in the map for that key.
For `containsKey`, that's really an "it had one job!" situation.

That's what causes the inconsistency: If `map.containsKey(a)` returns `true`, then `map[a]` and `map.putIfAbsent` must return a value that is an instance of the `V` type. Here it returns `null`, because there is no entry with that key. The latter has return type `V`, so it breaks type soundness to return `null`.

I'll fix this, and I'll add a test.

I'll also add a concurrent modification check, because missing a concurrent modification is acceptable only when the final result is a consistent state for the collection. If some modifications can make you end up with map with an internal state which doesn't satisfy its own invariants, then it should throw. (Also, it's just one number comparison in an otherwise complicated function).

**Comment by nshahan** [comment]
> It's a bug because map.containsKey(a) returns true while there isn't actually an entry in the map for that key.
For containsKey, that's really an "it had one job!" situation.

Thanks for pointing this out, I was focusing on the modification of the map and failing to consider that it is valid to check if the map contains the key in the `ifAbsent()` call.

> I'll fix this, and I'll add a test. (Done, well, if the tests run 😁).

Thanks for this too! It looks like there is a test that fails with the new modification check you added. 
https://github.com/dart-lang/sdk/blob/6de562dfdebbfbd24383823507a28f8d79cba98c/tests/corelib/hash_map2_test.dart#L139-L148
It appears to be testing that you can change a value for a key that is already present in the map. I suppose that as the method comment is written this should be allowed because it is not adding or removing keys.

**Comment by rakudrama** [comment]
My mental model for `m.putIfAbsent(k, () => e)` is that it behaves like `m[k] ??= e`, except that (1) it works properly for `null` values stored in the map and (2) might be be more efficient, including calling `hashCode` fewer times.

The VM implementation realizes this model and reused the lookup position unless there is an invalidating change, in which case the indexed setter is used. There is the comment "_ifAbsent is allowed to modify the map._"
```dart
  V putIfAbsent(K key, V ifAbsent()) {
    final int size = _index.length;
    final int fullHash = _hashCode(key);
    final int hashPattern = _HashBase._hashPattern(fullHash, _hashMask, size);
    final int d =
        _findValueOrInsertPoint(key, fullHash, hashPattern, size, _index);
    if (d > 0) {
      return _data[d];
    }
    // 'ifAbsent' is allowed to modify the map.
    List oldData = _data;
    int oldCheckSum = _checkSum;
    V value = ifAbsent();
    if (_isModifiedSince(oldData, oldCheckSum)) {
      this[key] = value;
    } else {
      final int i = -d;
      _insert(key, value, hashPattern, i);
    }
    return value;
  }
```

I think we should make all implementations consistent with the VM behaviour, which has the benefit of being consistent with `MapMixin.putIfAbsent`.

**Comment by lrhn** [comment]
@nshahan 
That test is wrong. It's adding the `4` key inside the `putIfAbsent` code, a key which does not exist in the map at that time. That's a concurrent modification, and may throw `ConcurrentModificationError`.

Changing the value of `[5]` is fine if `5` is already in the map, but `4` definitely isn't, since `ifAbsent` is called.

So, I'll have to fix that test too :)
