### ISSUE TITLE
_CastError (type 'List<String?>' is not a subtype of type 'List<String>' in type cast)

### ISSUE THREAD

**Issue by adnanjpg** [dart-lang/sdk#47854]
<details>
<summary>dart --version</summary>

`Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "windows_x64"`

</details>

I am having a problem in casting nullable `T?` to `T`

here is an example to explain my issue on a deeper level:

```dart
List<String> bar(List<String?> foo) {
  return foo.where(
    (e) {
      return e != null;
    },
  ).toList();
}
```
here we have the method `bar` which returns the non-null elements of a list that have nullable values.
 this method throws analyze error `A value of type 'List<String?>' can't be returned from the method 'bar' because it has a return type of 'List<String>'.`. 

as a solution, I tried to tell dart myself that my `where` clause will return only non-null `String`'s by casting the output to `List<String>`:

```dart

List<String> bar(List<String?> foo) {
  return foo.where(
    (e) {
      return e != null;
    },
  ).toList() as List<String>;
}

```

but now it throws the runtime error `_CastError (type 'List<String?>' is not a subtype of type 'List<String>' in type cast)`

**Comment by eernstg** [comment]
Try this one:

```dart
List<String> bar(List<String?> foo) => List.from(foo);
```

You can't use `where`, because it returns an `Iterable<E>` when called on a `List<E>` (so, as the analyzer says, the result is a `List<String?>`). Also, as you mentioned, the downcast `as List<String>` will simply delay the failure such that it occurs at run time (you're saying to the compiler: "Trust me, I know it will be a `List<String>`", but that isn't true).

In general, a type cast will _check_ whether a given object has a given type, it won't do anything to _change_ the object such that it has the desired type. So if your object has a wrong type then it will never help to insert a type cast.

The `List.from` constructor will create a new list, and it will get the type argument `String` because it's being returned and the return type is `List<String>` &mdash; but it will then be checked dynamically that each of the elements from `foo` are indeed of type `String`.

I'll close the issue because it doesn't report anything that needs fixing.

**Comment by eernstg** [comment]
By the way, I should mention one more thing: `List.from` is useful when we want to obtain a `List<T>` from an existing `Iterable<S>` where `S` is a supertype of `T` (so we're basically performing a dynamic type check and a downcast for each element). In the case where no such downcast is necessary it's better to use `List.of`: `List<T>.of` accepts an argument of type `Iterable<T>`, so there is no downcast, it's statically safe, and it's faster.

So the rule of thumb is "use `List.of` whenever possible, and fall back on `List.from` if the operation needs a per-element downcast".

**Comment by adnanjpg** [comment]
Thank you very much for this precious information
