### ISSUE TITLE
VM implementation for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47861]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by alexmarkov** [comment]
Currently there are only 2 failing tests for enhanced enums on the VM configurations:
- 1 `CompileTimeError` due to front-end bug https://github.com/dart-lang/sdk/issues/48297.
- 1 `CompileTimeError` due to incorrect test https://github.com/dart-lang/sdk/issues/48421.

The implementation in the VM is complete and there are no outstanding failures related to the VM.
