### ISSUE TITLE
core library updates for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47864]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

**Comment by lrhn** [comment]
The platform library `Enum` declaration needs to change in small ways. Those changes should not be a problem to add early, since users can't reach them anyway.

The implementations may also want to have an `_Enum` class which is updated as well. We'll have to lock down the implementation design first.

**Comment by lrhn** [comment]
I don't think any changes were necessary. Later iterations of the design made it an error to override `index`, so there was no need to change the existing implementation in order to move that to a superclass.

So, done.
