### ISSUE TITLE
Compile-time error is not reported for a non-abstract class with abstract members

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#47877]
Consider the following example:

```dart
abstract class A {
  void foo() => _foo();
  void _foo();
}

class B extends A {}

main() {
  B().foo();
}
```

It fails to compile with the following error:
```
foo.dart:6:7: Error: The non-abstract class 'B' is missing implementations for these members:
 - A._foo
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class B extends A {}
      ^
foo.dart:3:8: Context: 'A._foo' is defined here.
  void _foo();
       ^^^^
```

However, if I move declaration of class `A` to a separate library, class `B` is compiled successfully:

bar.dart:
```dart
abstract class A {
  void foo() => _foo();
  void _foo();
}
```
foo.dart
```dart
import 'bar.dart';

class B extends A {}

main() {
  B().foo();
}
```

It looks like CFE allows non-abstract classes with abstract members.
Expected behavior: compile-time error in both cases.

/cc @johnniwinther

**Comment by lrhn** [comment]
Actually, expected behavior is what you are seeing.

When a non-abstract class implements an interface, it only needs to implement the *accessible* members of the interface. An implementation will be provided for the inaccessible members (one which forwards directly to `noSuchMethod`).

When both classes are inside the same library, the private member is still accessible, and the subclass must implement it.
