### ISSUE TITLE
flutter-analyze bot is flaky in step "analyze flutter/flutter"

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#47881]
From @athomas, regarding pub scripts possibly clobbering each other or corrupting a pub cache:

> One thing we could try is to set the PUB_CACHE environment variable in the script that frequently fails. We could either set it to a temp directory or use the checkout directory (where the SDK root is). The latter is cached between builds (if these caches get corrupted it's a bad thing but otherwise it might speed up the builds considerably).

CC @stereotype441 @pq

**Comment by stereotype441** [comment]
Trying this now

**Comment by stereotype441** [comment]
3e6d9a5e5521bb8a0da9ad900e44b75eab3b3cd4 helped but did not entirely fix the problem.  I'm re-titling the bug to reflect the more general flakiness problem with the flutter bot.

**Comment by whesse** [comment]
The duplicate step can now be removed, since the flutter script dev/bots/analyze.dart now analyzes the snippets correctly.

The temporary directory is automatically deleted when the builder finishes, and the cleanup step in this script was in a signal trap, which seems to have been causing the instability.  So I am removing the cleanup step as well.

https://dart-review.googlesource.com/c/sdk/+/226685

**Comment by jason-simmons** [comment]
The Flutter `analyze_sample_code.dart` tool is starting multiple concurrent `pub global run snippets` processes.

This may be unsafe (see https://github.com/dart-lang/pub/issues/3165).

Flutter's analyzer CI script is running `pub global run snippets` once before launching `analyze_sample_code.dart` in order to configure the pub cache
(see https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh#L34)

Dart's flutter-analyze bot may also need to do that to reduce flakes.

**Comment by sigmundch** [comment]
I have not seen this failure come up in the last 200 runs of the flutter-analyze bot. https://github.com/dart-lang/pub/pull/3285 from @sigurdm[](https://teams.googleplex.com/sigurdm@google.com) landed in the main Dart branch in https://github.com/dart-lang/sdk/commit/bc7554107bf733687231981da6f7f1bc892999bd on Jan 27 and the last failure of this kind was two days prior to that on Jan 25! I'm cautiously optimistic that this is now fixed :tada: 

I'll close this issue at this time, but we can reopen if we encounter it again.
