### ISSUE TITLE
The quick-fix "Add package to dependencies" in Visual Studio code doesn't work with Dart 3.29.0 

### ISSUE THREAD

**Issue by leRayGorbella** [dart-lang/sdk#47906]
Hi ! I found that upgrading to the 3.29.0 version of Dart in my Visual Studio Code blocked the use of this quick-fix in visual Studio Code : Add package to dependencies.  

![Capture d’écran 2021-12-11 à 22 33 08](https://user-images.githubusercontent.com/93099788/145696136-8cbd39e5-27fe-4c17-956f-9e8c99446b0f.png)
![Capture d’écran 2021-12-11 à 22 33 21](https://user-images.githubusercontent.com/93099788/145696138-3d5d728a-ca95-4613-af7b-415d6680c1c3.png)

My actual workaround is to downgrade Dart to the previous version 3.28.0. 

Is it intentional or is it truly a bug ? 

Thanks for your time spent on this issue, 
Best regards, 
Adrien

**Comment by bwilkerson** [comment]
@DanTup Is this a VS Code specific feature? I can't find a `FixKind` with a label like this.

**Comment by DanTup** [comment]
Yep, this is currently a client-side feature (it would be nice to move to the server, but it means the server would have to call `pub add` which modifies pubspec on disk and gets complicated). Taking a look...

**Comment by DanTup** [comment]
Looks like changes to the **Dart: Add Dependency** command have broken this. The tests only cover ensuring the fix is in the list, and that running the command it calls works, but not that the two are in-sync correctly.

I've moved this to https://github.com/Dart-Code/Dart-Code/issues/3728 and will fix + improve the tests.

I'm planning on a pre-release of the Dart extension for VS Code this week (using [VS Code's new ability to have "insiders extensions"](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions)) so will ensure it includes a fix for this if you'd like to have the fix before the stable release (I'll ping on https://github.com/Dart-Code/Dart-Code/issues/3728 when that's available).
