### ISSUE TITLE
Migrator introduces conflicting changes

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#47913]
I ran the migrator tool and one method of the library I'm migrating received these 3 changes:
- return type made nullable: `Instantiator?`
- type argument bound made nullable: `Node?`
- "Condition will always be false in strong checking mode" `/* == false */`

```dart
Instantiator? visitNullable<T extends Node?>(T  node) {
  return node == null /* == false */ ? makeNull : visit(node);
}
```

The last two changes appear to be in conflict since the value passed as the argument `node` could be null depending on how the type argument is instantiated.

**Comment by stereotype441** [comment]
@nshahan and I just walked through this migration.  Here's a few more details:
- This happened when trying to migrate DDC.
- The reason the type argument bound was made nullable was because there was a call site of the form `visit(...)` (with no explicit type arguments) where the `...` was a nullable expression.  When this happens the migration tool has two choices: either assume that the implicit type argument is nullable (in which case `T extends Node` needs to change to `T extends Node?` to allow that), or assume that the argument type (`T node`) should be changed to `T? node`.  It has a heuristic that causes it to favor making the type argument nullable because in general that leads to less nullability in the overall migration.  But in this particular example, it looks like changing the argument to `T? node` would probably match the original intent better.
- The real bug here is the appearance of `/* == false */`.  That definitely shouldn't be there, because if `T` is allowed to be instantiated with a nullable type, and if it is, then `node == null` could be true.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
