### ISSUE TITLE
Provide a context location for the invalid_override diagnostic

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#47936]
Some diagnostics have additional "context messages" that contain a pointer to another source location. One error that appears not to, but I think would be useful is `invalid_override`. I often change a signature and get an error like this, but sometimes the fix is to update the base class - having an additional part to the diagnostic that includes the location of the mismatched signature would be very helpful.

<img width="1412" alt="Screenshot 2021-12-15 at 14 35 40" src="https://user-images.githubusercontent.com/1078012/146206001-cb10c39a-0843-4ed3-8823-d0f67fc792e7.png">

**Comment by DanTup** [comment]
@bwilkerson are there any conventions/guidelines for these messages? If this one seems worth doing, am I right in thinking it would be done by adding the extra messages here:

https://github.com/dart-lang/sdk/blob/0a39aa7cf6c6a8a74057c68f543bbadd20f7d815/pkg/analyzer/lib/src/error/correct_override.dart#L58-L68

(and perhaps adding a method to [DiagnosticFactory](https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/pkg/analyzer/lib/src/diagnostic/diagnostic_factory.dart)?)

**Comment by bwilkerson** [comment]
Yes, the easiest place to add a context message is generally in the place in which the diagnostic is being produced, so that's where I would put it.

And yes, we've mostly been putting support for this in `DiagnosticFactory`. I'm not sure how necessary that is, but it provides us a place to implement this code that can be re-used when a diagnostic can be produced in multiple places.
