### ISSUE TITLE
Uri.http(s) queryParams accept only Map<String, String> instead of Map<String, dynamic>

### ISSUE THREAD

**Issue by AndreyWV** [dart-lang/sdk#47932]
This example throws `_TypeError (type 'int' is not a subtype of type 'Iterable<dynamic>')`:
```dart
Uri.http(
  'test.domain',
  '/path',
  {
    'test': 1,
  },
);
```
while this works fine
```dart
Uri.http(
  'test.domain',
  '/path',
  {
    'test': '1',
  },
);
```

`Map<String, dynamic>` type given in documentation https://api.dart.dev/stable/2.15.1/dart-core/Uri/Uri.http.html

Used Dart version: `Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "windows_x64"`

**Comment by lrhn** [comment]
That is correct. The two accepted values types are strings and iterables of strings. Since we can't write that as a type, the static type of the parameter is `Map<Sting, dynamic>`, but it's an error if any value is neither a string nor an iterable of string.

An integer is neither. You need the `'1'`, or `1.toString()`.

We could be more lenient, and do `.toString()` on values that are not iterables (and `.toString()` on the values of iterables of `dynamic`), but that risks hiding errors. Say, someone thought `foo()` returned a string or iterable of string, but it's actually asynchronous and they forgot the `await`. We'd then do `.toString()` on the future, which is meaningless. It's better to get an early error in that situation.

So, I don't think we'll want to do this. You have to use strings as values.

**Comment by mqhamdam** [comment]
spent some times, for this...

please add more documentation to point where does this error appears.

**Comment by AndreyWV** [comment]
@mqhamdam 
https://dartpad.dev/?id=3a3fd0a115ebcbbc097e961435d2a17d

Error points to `Uri.dart` `_makeQueryFromParametersDefault` ` queryParameters.forEach`. Inside it iterates through parameter value. Still actual error. [But correct type commented now](https://github.com/dart-lang/sdk/blob/main/sdk/lib/core/uri.dart#L2367)

**Comment by mqhamdam** [comment]
@AndreyWV This is a common runtime error when there’s a type mismatch, often due to a developer's oversight. However, in the case of URI handling, this seems like a core Dart feature limitation. A more informative error message, similar to the clear guidance provided in the BLoC package, would be beneficial. Since dynamic is used here but only specific types are actually allowed, it can be misleading.

Would it be better to incorporate an assertion for clarity? For example:

```
queryParameters?.forEach((key, value) {
  assert(
    value is String || (value is Iterable && value.every((v) => v is String)),
    'Query parameter value for key "$key" must be a String or an Iterable of Strings. But found: ${value.runtimeType} with value: $value',
  );
});
```
This way, it becomes immediately clear when a type mismatch occurs and what needs to be fixed.
