### ISSUE TITLE
Add a fix for the cascade_invocations lint

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#47957]
It would be good to have a fix for the `cascade_invocations` lint.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/238581

Please note `bulk` wasn't added, because otherwise we would need to handle existing builder `edits`, to prevent the incorrect outcome of `...` from

```dart
  a.m();
  a.x = 1;
  a.m();
```
to
```dart
  a..m()
  ...x = 1
  ..m();
```
, and I am hesitant to handle `edits` for now.

Another point, if only the first occurrence is reported by the lint (as recently requested), we need to have the same logic in the fix, to detect the next occurrences.
