### ISSUE TITLE
Isolate ReceivePort enhancements.

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/sdk#47972]
In the dart 2.15 release there were a number of enhancements made to Isolates. There are a couple of things relating to `Isolate` particularly with `ReceivePort` that I think could be improved further.

<hr />

Firstly, it would be nice to be able to close a `ReceivePort` when calling `Isolate.exit`. Consider the following program.

```dart
import 'dart:isolate';

void main() async {
  final receivePort = ReceivePort();
  await Isolate.spawn((generateNumbers), receivePort.sendPort);
  await for (final message in receivePort) {
    print(message);
  }
}

void generateNumbers(SendPort port) {
  port.send(1);
  port.send(2);
  Isolate.exit(port, 3);
}
```

The above program prints
```
1
2
3
```
And then hangs, waiting for more messages on the `ReceivePort`. 

<hr />

Secondly, the dart 2.15 update added the ability to pass a closure to `Isolate.spawn`, but it doesn't interact nicely with `ReceivePort` objects.

Consider the following program.

```dart
import 'dart:isolate';

void main() async {
  final receivePort = ReceivePort();
  int three = 3;
  await Isolate.spawn(
    (SendPort port) => Isolate.exit(port, [1, 2, three]),
    receivePort.sendPort,
  );
  print(receivePort.first);
}
```

Which fails at runtime with the error message:
```
Unhandled exception:
Invalid argument(s): Illegal argument in isolate message: (object is aReceivePort)
```

**Comment by lrhn** [comment]
The model used by Dart isolate communication is that a receive port belongs to a single isolate, but it can have multiple paired send ports than can be sent to any number of other isolates.

You can't close a receive port from the send port's side because the send port doesn't, and cannot, know whether there are other open send ports sending to the same receive port. And you can always create *more* by reading `receivePort.sendPort` again.

Only the receive port can close itself, with its `close` method. The send ports, which can belong to other isolates (and, in the theoretical underlying model, could potentially be on a completely different computer, although that isn't currently being used) cannot know whether the receive port is closed. It's just the receive port which stops responding to messages.

So, you can't make `Isolate.exit` close the receive port, all you can do with a send port is to send a message. If the receive port is still listening, it will receive that message. (If `Isolate.exit` could close the receive port, would it do so before receiving the message being sent in `Isolate.exit`, or after? What, even, is "after" in an asynchronous language like Dart?)


As for the closure closing over the receive port, that *is* annoying. 
Sound like the VM should try to not close over unnecessary variables. (I'm sure there is already an issue for that, somewhere.)

**Comment by mmcdon20** [comment]
> The model used by Dart isolate communication is that a receive port belongs to a single isolate, but it can have multiple paired send ports than can be sent to any number of other isolates.

> You can't close a receive port from the send port's side because the send port doesn't, and cannot, know whether there are other open send ports sending to the same receive port. And you can always create more by reading receivePort.sendPort again.

I understand that you can have multiple `SendPort` associated with a single `ReceivePort`. What I was envisioning was something like an optional flag on `Isolate.exit`. Perhaps something like this:

```dart
import 'dart:isolate';

void main() async {
  final receivePort = ReceivePort();
  await Isolate.spawn((generateNumbers), receivePort.sendPort);
  await for (final message in receivePort) {
    print(message);
  }
}

void generateNumbers(SendPort port) {
  port.send(1);
  port.send(2);
  Isolate.exit(port, 3, closeReceivePort: true);
}
```

This way you would have to opt in to this behavior, because you wouldn't want this in every scenario. Would something like this be possible?

**Comment by mmcdon20** [comment]
After thinking about it some more, modifying `Isolate.exit` is probably not the best approach.

Basically, I wish there was a more convenient way to compute and consume a finite stream of data in an Isolate. 

Maybe something along the lines of the `compute` function in flutter, except it returns a stream of values rather than a future value. 

Something that works roughly like this.

```dart
import 'dart:isolate';
import 'dart:io';

void main() async {
  await for (String fileName in computeStream(listFileNames)) {
    print(fileName);
  }
}

Stream<String> listFileNames() async* {
  final directory = Directory('.');
  await for (final file in directory.list()) {
    await Future<void>.delayed(const Duration(seconds: 1));
    yield file.path;
  }
}

Stream<T> computeStream<T>(Stream<T> Function() stream) async* {
  final receivePort = ReceivePort();
  await Isolate.spawn(computeStreamHandler(stream), receivePort.sendPort);
  await for (final item in receivePort) {
    if (item == const Complete()) {
      receivePort.close();
      return;
    }
    yield item as T;
  }
}

Future<void> Function(SendPort port) computeStreamHandler<T>(
    Stream<T> Function() stream) {
  return (SendPort port) async {
    await for (final item in stream()) {
      port.send(item);
    }
    Isolate.exit(port, const Complete());
  };
}

class Complete {
  const Complete();
}
```

**Comment by mmcdon20** [comment]
Closing in favor of #47981.

**Comment by lrhn** [comment]
The chosen underlying model really does prevent that the send port can unilaterally close the receive port.
Being cross-isolate also makes it impossible to restrict a port communication to a specific type of objects, because the *type itself* might not exist in the other isolates.
Ports are really *very* low-level. So are isolates themselves.

That's why you usually build a *protocol* on top of port communication. My traditional go-to protocol is sending a single element list for a value, a two-element list for an error (the error and stack trace), and `null` as a "done" marker. That effectively allows me to send all stream events as port messages, and allows the receiver to recreate them at the other end (if sending between isolates which only allow JSON-like data, I'd send the `toString` of the error and stack traces).

You can create your own protocol that is tailored to your use-case, or you can use some helper library on top of the isolates and ports, to manage the protocol for you (we've discontinued `package:isolate`, but it did have a few useful abstractions, I'm sure there are other packages too).
