### ISSUE TITLE
Allow "unused" class members which are present to prevent mixing in, for the purpose of static analysis

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#48022]
I've encountered code like the following:

```dart
mixin M {
  void _(); // prevent mixin application outside of library
}

class C with M {
  @override
  void _() {}
}
```

The `_()` method is never called; it only exists to prevent the public mixin from being applied to other classes outside the library. Should the analyzer support this as a meta "use" of this otherwise unused method?

We support a similar case for constructors: If a class has a single, private, unused constructor, we understand that it may be present in order to prevent extension.

If we do support "unused" private class members for the purpose of preventing mixin application, what would be the signal? A name of `_`? A `@pragma` annotation? Any such private method which is abstract?

**Comment by bwilkerson** [comment]
It would probably be difficult to determine, but this begs the question of how often this case occurs (where the unused method shouldn't be removed).

But I will suggest that there are a couple of additional approaches to consider.

First, if the mixin shouldn't be applied outside the library, then it might be possible for the mixin to be private. I say possible because it might be necessary for `is` tests, though there might be ways around that as well, such as by adding an `isM` getter to the base class.

Second, users could always apply an `ignore` comment at the declaration site to indicate that this is an exception to the rule.

Third, add an annotation that can be applied to the mixin itself that will cause any application of the mixin outside the library to be flagged (name TBD). Seems like it would be better to annotate the mixin than to have a member that all subtypes need to needlessly implement.

If we do want to support this case (without using an `ignore` comment), then IMO the more explicit the case is the better, whether that's with a `pragma`, other annotation, or other explicit way of marking the member.

**Comment by eernstg** [comment]
> The `_()` method is never called; it only exists to prevent the public mixin
> from being applied to other classes outside the library

This would not actually work, because every concrete subtype of that mixin application would have a noSuchMethod forwarder which is ["forced by privacy"](https://github.com/dart-lang/language/blob/9daaad1d2103dcb7ad91f3ebf27a878c13fca985/specification/dartLangSpec.tex#L2998). The language team is currently having some discussions about what that generated method should do, but it would exist in any case, and given that it's never called, it would actually not make a difference at all what that `_` method is doing.

Would it be an acceptable workaround to declare an abstract class with the public name `M`, and then let the mixin have a private name `_M` and implement `M`?

**Comment by srawlins** [comment]
> Would it be an acceptable workaround to declare an abstract class with the public name M, and then let the mixin have a private name _M and implement M?

I think this is a great workaround.

**Comment by eernstg** [comment]
The upcoming class modifiers feature would allow us to specify that `M` cannot be mixed in outside the declaring library, and still preserve the ability for code in another library to use `M` as a type annotation, and in an `implements` clause:

```dart
interface mixin M {
  // Just the members you actually need, no need to have artificial ones.
}
```

We could also use `sealed`, but I don't think the exhaustiveness property of `sealed` is really useful in this context (`M` may or may not have any subtypes, but we probably don't have a specific need to enforce the constraint that the set of immediate subtypes of `M` is statically known). Also, we could use `final` if we want to allow `M` to be used by code in another library as a type annotation, but prevent `implements M`.

> If a class has a single, private, unused constructor, we understand that it may be present in order to prevent extension.

Again, we can specify this directly with class modifiers, there's no need for artificial constructors any more:

```dart
// In library 'a.dart'.

interface class A {}

// In another library.

class B extends A {} // Compile-time error.
class B2 implements A {} // OK.
```

@srawlins, surely we can find other ways to create code where certain constraints are enforced using "artificial members", but it does look like the existing examples here are covered quite well when we have class modifiers. So I'll close the issue now. Please reopen if you disagree!
