### ISSUE TITLE
Abstract static method.

### ISSUE THREAD

**Issue by hndrbrm** [dart-lang/sdk#48079]
Are there any way to make an abstract method with a static one, which will be implemented by the subclass.
The purpose is to give skeleton of the mandatory static method which must be implemented by the subclass.

```dart
abstract class Serializer {
  const Serializer();

  Uint8List serialize();

  static Serializer deserialize(Uint8List serialized);
}
```

**Comment by lrhn** [comment]
No.

Static methods are not part of any interface, so there is no way to ensure that a subclass implements the method too, and even if there was, there is no way to call a static method without knowing the exact class it's no at compile-time.

You cannot make static methods abstract, for the same reasons. Abstract methods are only part of the *interface* of the class they are declared in, but do not introduce an implementation. Static abstract methods would not do anything, since they are also not part of any interface.

**Comment by eernstg** [comment]
Closing: I think it's fair to say that this issue duplicates some of the discussions in https://github.com/dart-lang/language/issues/356. @hndrbrm, please check that issue and follow up there if needed.
