### ISSUE TITLE
Evaluation of this constant expression throws an exception

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#48138]
```dart
class A {
  const A(Type t): assert(t == int);
}

main() {
  const a=A(int); // Evaluation of this constant expression throws an exception
}
```
Why?
(If I change assert to `assert(identical(t,int))`, the error disappears)

**Comment by lrhn** [comment]
The `e1 == e2` expression is only a constant expression if the values have one of a limited number of types

> ```latex
> \item
>  An expression of the form \code{$e_1$\,==\,$e_2$} is potentially constant
>  if $e_1$ and $e_2$ are both potentially constant expressions.
>  It is further constant if both $e_1$ and $e_2$ are constant and
>  either $e_1$ evaluates to an object that is an instance of
>  \code{int}, \code{double}, \code{String}, \code{bool} or \code{Null},
>  or if $e_2$ evaluates to the null object (\ref{null}).
>  %TODO: Consider adding enum instances here.
> ```

So, the problem here is that the expression `t == int` is potentially constant, so it's allowed in a potentially constant context of a `const` constructor, but it won't be actually constant when actual values are inserted.

We can see that already from the original `int` operand, and with null safety, also from the type of `t`, so it's a little annoying that you don't get told at compile-time. That was a trade-off made when we expanded the `const` expressions, and didn't want the front-end (at the time) to have to know types before it could tell whether a program was grammatically valid.

That was a mistake, and we could fix it - by still saying that `e1 == e2` is a potentially constant, but also saying that it's a compile-time error if the operand expressions are not assignable to any of these types. That just adds extra errors later downstream in the compiler, the parser doesn't have to know.
The restricted type list that is allowed for `==` operands ensures that we *could* statically reject some code.

However, we also want to allow constant `==` on any values that have primitive equality (as defined for switch cases and const map/set literals). That would be counter to having a specific allowed type list.
Having primitive equality is a property of values, not types, so if we make the latter change, we probably won't be able to statically reject `==` expressions in `const` constructors, we have to see the actual values before we can make it fail.

So, we can either statically restrict the allowed `==` operations to types that are guaranteed to work (or `dynamic`), or make `==` more flexible in what it allows, but then we definitely won't be able to catch cases like this statically. (We'd allow `Type` literals, so this example would *work*, but another example, for objects with non-trivial equality, won't.)

All in all, a `const` constructor doing `==` on arguments means that there is a restriction on the allowed values, one which cannot be expression in the argument types. You'll still catch it at compile-time, because `const` evaluation happens at compile-time, but you can't see it until you get the actual error.
I don't see a good workaround for that, other than encouraging you to use `identical` if that is what you mean.

**Comment by tatumizer** [comment]
Thanks. I suspected that equality in const setting would be generally impossible to implement, but I found that for int constants, `assert (t == 0)` works, and it works also for Strings, so I thought it must work for types, too.
This is not important though, having `identical` is good enough.
Thanks. Closing.
