### ISSUE TITLE
add `lastIndex` to `List`

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/sdk#48150]
This is a small request to add `lastIndex` getter to `List`. Dart `List` has a bunch of utility getters that makes the code very much read like a sentence.

 - `list.isEmpty`
 - `list.isNotEmpty`
 - `list.first`
 - `list.last`
 
 I propose adding `list.lastIndex` because this is probably the next most used value after the ones cited above and is more readable than `list.length - 1`. It might also prevent some bugs were the - 1 was forgotten

**Comment by lrhn** [comment]
While I'm usually all for redundant redundancy duplication of features, changing the `List` interface is not something can do without serious consideration and a big value proposition.

We can definitely add an extension getter, say in `package:collection`, but I'm not sure this is actually *helping* people.
With that, you can use either `lastIndex` or `length` (or `length -1` as you are used to), and you can accidentally use the wrong one just as easily as you can forget a `- 1`. 
Remembering whether `lastIndex` is `length - 1` or the other way around is more complexity for users.

Since all our `*Range` operations has the `end` being exclusive, you are more likely to need `length` than `length - 1` for those, and iterating idiomatically uses `i < x.length`. I very rarely need `length - 1`, ... but I do need it occasionally, and it is slightly annoying to write `list.swap(i, list.length - 1)`.

I honestly think users are better off doing `var lastIndex = list.length - 1;` in their own function, rather than have two similar, but different, "end" getters on a list. Learn the idiomatic ways to use `length`, and if you really, really need `length - 1` a lot in a function, make a local variable for *that* function.

**Comment by cedvdb** [comment]
`length - 1` is used to know if an index is the last one (not in for loops). A more readable form is not using the index when possible.

`bool get isLastPage => currentPage == pages.last`

I'm closing this since you convinced me there is not enough value added here
