### ISSUE TITLE
Stream `.first` never returns when `async*` function has `yield` followed by neverending `await for`

### ISSUE THREAD

**Issue by idraper** [dart-lang/sdk#48165]
Dart version: `Dart SDK version: 2.15.1 (stable)`
OS: Windows 10

This issue is best seen by the following example:

```
Future<void> main(List<String> arguments) async {
  print('before');
  getValues().listen((i) => print('listener: $i'));
  print(await getValues().first);
  print('after');
}

@override
Stream<int> getValues() async* {
  yield 0;
  await for (final i in Stream.periodic(Duration(seconds: 1))) {  }
}
```

Actual output:
```
before
listener: 0
// hangs
```

Expected output:
```
before
listener: 0
0
after
```

Why is it that the listener works as expected (gets first `yield`) while `.first` does not? While this is a trivial example demonstrating the problem, I ran into this because if I have an `await for` loop, when I have a neverending function (like periodic) I have to do the following to get `.first` to return (listener prints twice):

```
@override
Stream<int> getValues() async* {
  await for (final i in Stream<int>.periodic(Duration(seconds: 1), (i) => i)) {
    yield i; // single call doesn't trigger .first
    yield i; // second call is returned to .first (.listen sees both)
  }
}
```

**Comment by lrhn** [comment]
The problem here is likely that `first` waits for the first value, *then* it waits for `streamSubscription.cancel()` which returns a future that completes when the `async*` function exits (and any `yield` after `cancel` has been called acts like a `return`).

Because of the never-ending `await for`, the `cancel` never completes, and therefore the `first` never completes because it waits for the `cancel` before returning itself.

So, most likely working as intended.
