### ISSUE TITLE
Incorrect linter reports all final vars need init when using static

### ISSUE THREAD

**Issue by moneer-muntazah** [dart-lang/sdk#48180]
If you try the dartplayground with 

```dart 
class Foo {
  Foo();
  static final String? _somevar;
}
```

You will net a lint on the constructor that says that all final variables need to be initialized but _somevar isn't. This should be on the class rather than the constructor. In Android Studio the fix even adds `this._somevar` in the constructor.

**Comment by bwilkerson** [comment]
The diagnostic is specific to the constructor against which it is being reported. If there is more than one constructor it is possible for one of them to be wrong when the rest are correct. That's why the diagnostic is reported against the constructor rather than the class.

However, in this case, because the field is a static field, the diagnostic should be reported against the field rather than a constructor because static fields can't be initialized by constructors.

The second bug here is that there is a fix to add an initializing formal parameter. Doing so is invalid because the field is a static field.

We might well want to have a different diagnostic for static fields than the one we have for instance fields.

**Comment by asashour** [comment]
- I guess the fix is ok, since it depends on the hint, which should be changed.
- Please find below to remove static from the current hints.

https://dart-review.googlesource.com/c/sdk/+/238358

- Another CL would be raised for having a diagnostic per static field.

**Comment by bwilkerson** [comment]
Thanks. That change looks good, but the bots will (likely) fail because there should be tests elsewhere (the language tests and the co19 tests) that ensure that a diagnostic is being reported for uninitialized static final fields. Those tests will start failing with this CL because the diagnostic will no longer be produced.

In other words, I don't think we can make these changes separately. We'll need a single CL that stops reporting the existing diagnostic in these cases and at the same time starts reporting a new diagnostic.

**Comment by asashour** [comment]
Actually, there is already `NOT_INITIALIZED_NON_NULLABLE_VARIABLE`, which reports for static fields, however its tests didn't include the constructor, which would trigger two hints with the current `main`.

There a question about `final` being checked elsewhere, but it can be discussed there.

Please take a look.

https://dart-review.googlesource.com/c/sdk/+/238358
