### ISSUE TITLE
Enhanced enums: dart throws unexpected compile error for the declaration of enum with factory.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#48181]
Dart SDK version: 2.17.0-28.0.dev (dev) (Tue Jan 18 12:05:00 2022 -0800) on "windows_x64"

Dart produces a compile time error for the following source code example:
```
// SharedOptions=--enable-experiment=enhanced-enums
enum E {
  e1,
  e2;
  factory E.f(int i) => E.values[i];
}

main() {}
```
Seems like there should not be an error here.

Sample output is:
```
$> dart --enable-experiment=enhanced-enums test.dart
test.dart:2:6: Error: Constant evaluation error:
enum E {
     ^
test.dart:2:6: Context: Expected constant 'null' to be of type 'E', but was of type 'Null'.
 - 'E' is from 'test.dart'.
enum E {
     ^
test.dart:2:6: Context: While analyzing:
enum E {
     ^
```

**Comment by eernstg** [comment]
@lrhn, is it intended that a constructor `const E();` will be generated in an enum declaration `E` in the case where `E` contains a factory constructor (redirecting or not)? This seems inconsistent with the treatment of a similar situation for classes:

```dart
class C {
  factory C.fac() = D;
}

class D implements C {
  D();
}

void main() {
  C(); // Error, there is no constructor named `C`.
}
```

So I would think that there should be an error in the original example, because it needs to invoke a constructor named `E`, and there is no such thing, but the [spec](https://github.com/dart-lang/language/blob/master/working/0158%20-%20Enhanced%20Enum/feature_specification.md#semantics) seems to disagree.

**Comment by chloestefantsova** [comment]
I'm working on a fix (https://dart-review.googlesource.com/c/sdk/+/229540) according to the current spec.

**Comment by lrhn** [comment]
The design document does indeed say:
> If no generative constructors were declared, and no unnamed factory constructor was added, a default generative constructor const Name._$(this.index, this._$name); is added.
