### ISSUE TITLE
Covariant return types for nullable defaults

### ISSUE THREAD

**Issue by giladwo** [dart-lang/sdk#48205]
Functions like [`E firstWhere(bool test(E element), {E orElse()?})`](https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/sdk/lib/core/iterable.dart#L526-L539) have an invariant `E` return type.

Considering the fact that `E` extends `E?`, and `orElse` can usefully return `null`, I suspect a covariant `T super E` may be a more useful return type. (I'm not sure how to express this in Dart though).

What do you think?

**Comment by mraleph** [comment]
You can't express this in Dart. 

See related discussions at https://github.com/dart-lang/sdk/issues/42947

**Comment by giladwo** [comment]
Sorry, I got mixed up and thought about this kind of variance:
https://github.com/Team1690/Scouting-Frontend/blob/master/lib/views/mobile/selector.dart#L24-L34
Could you please explain why a `T extends E` wouldn't work here?

**Comment by mraleph** [comment]
Because `T extends E` allows for a more specific type and not for a less specific type. 

You, on the other hand, would like to allow `T` to be `E?` if `E` is non-nullable - which is less specific. (`E extends E?` is satisfied, but `E? extends E` is not).

Unfortunately Dart does not support lower type bounds on type parameters, only upper type bounds, while languages like Java and Scala support both lower and upper type bounds.

**Comment by giladwo** [comment]
So how come the above `validate` works as if `E? extends E`?

**Comment by mraleph** [comment]
I am not sure I understand the question. Could you clarify which part of the code works as if `E? extends E`?

**Comment by giladwo** [comment]
I've understood the mistake while trying to explain it here.
Thanks for the helpful clarification :smile:

**Comment by eernstg** [comment]
Note the overlap with https://github.com/dart-lang/language/issues/1674.
