### ISSUE TITLE
Why dart don't forces to define type on generic class extension ?

### ISSUE THREAD

**Issue by visign3d** [dart-lang/sdk#48202]
Generic class example:
```
abstract class ComponentWidget<TController extends ComponentWidgetController,C extends Component>
    extends GetView<TController>
{...
```
Extension class:
```
class TextComponentEditor extends ComponentWidget       // no error warnings !

{
```

**Comment by julemand101** [comment]
Because implicit dynamic is enabled by default. You can disable that behavior if you want a more strict analyzer: https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks

It is something I am doing in all my projects since I am rather annoyed by these implicit dynamics but they can also be great if you are writing a lot of dynamic code in e.g. JSON parsing.

**Comment by lrhn** [comment]
You can write "raw" generic types, and type arguments are inferred for you. That's often convenient, and occasionally surprising.

It's not "implicit dynamic" as much as plain type inference with instantiate-to-bounds as the fallback when there is no context.
In particular, it doesn't infer `dynamic` for either type argument here.
