### ISSUE TITLE
[Enhanced enums] CFE reports on the whole enum

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#48293]
Please see the following co19 tests
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A06_t07.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A09_t02.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A09_t05.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Enhanced-Enum/semantics_A14_t01.dart

These test fail because CFE additionally reports an error on whole enum. It makes sense to report errors at the locations expected by these tests (as analyzer does)

cc @eernstg

**Comment by eernstg** [comment]
Yes, if there's an enum value declaration like `e1(x, "2")`, and it has an error because `x` is not a constant expression, then it would be nice if the error message could be directed at this `x`. I think the error message is currently reported on the `enum` declaration as a whole and saying 'Constant evaluation error', and that's not very informative.

**Comment by chloestefantsova** [comment]
I believe this issue can be closed. The behavior of the CFE was adjusted, so that in some cases the errors aren't reported on the enum itself, and for the rest of the tests it was agreed that reporting on the enum is ok. Please feel free to reopen the issue if needed.
