### ISSUE TITLE
[dart2js] issue with global inference and labels

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#48317]
(original issue at https://github.com/flutter/flutter/issues/96394)

Global type inference in dart2js seems to create invalid control flow conclusions in programs using labels. Here is a very simple example showing this problem:

```dart
helper(num c) => c * -1;

void main() {
  num a = 3;

  label:
  {
    break label;
  }

  print(a * -1);
  print(helper(a));
  return;
}
```

Locally this example fails unless you disable global type inference. The code fails with the following error:

```
/usr/local/google/home/sigmund/dart/git_all/sdk/sdk/lib/_internal/js_runtime/lib/preambles/d8.js:263: TypeError: c.$mul is not a function
          throw e;
          ^
TypeError: c.$mul is not a function
    at Object.helper (/tmp/out.js:2142:16)
    at main (/tmp/out.js:2147:17)
    at action (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:275:31)
    at eventLoop (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:258:9)
    at self.dartMainRunner (sdk/lib/_internal/js_runtime/lib/preambles/d8.js:276:5)
    at /tmp/out.js:2525:7
    at /tmp/out.js:2510:7
    at dartProgram (/tmp/out.js:2521:5)
    at /tmp/out.js:2529:3


```

**Comment by fishythefish** [comment]
Thanks, this is really helpful. I haven't spent much time looking at how global type inference handles simple control flow constructs (as opposed to things like function calls), so this gives me a place to start.

**Comment by fishythefish** [comment]
I was having some trouble debugging this - I couldn't observe us visiting the calls to `print` or `helper`. Turns out it's because we weren't visiting them at all during inference! The culprit is here: https://github.com/dart-lang/sdk/blob/ab84be0a888480ff4d05833fbbcfc3d99709968a/pkg/compiler/lib/src/inferrer/builder_kernel.dart#L478

Here is the definition of `aborts`: https://github.com/dart-lang/sdk/blob/ab84be0a888480ff4d05833fbbcfc3d99709968a/pkg/compiler/lib/src/inferrer/builder_kernel.dart#L2332-L2334

When we visit the labeled block, we hit the `break` statement and set `seenBreakOrContinue`, as expected. (If there were code after the `break`, this would save us from having to visit it since the `break` aborts the block.) The problem is, when we leave the block, `seenBreakOrContinue` is still set, so we abort inferring the rest of the body of `main` as well.

At the moment, we only remember that at least one `break`/`continue` was seen; we don't record where they occur or where they jump to. Two solutions I can think of:
1. Delete the first line of code above and don't stop inferring the rest of a block when `_state.aborts` is set. (Perhaps we can still abort the inference if `seenReturnOrThrow` is set.) This does mean that we may perform some unnecessary inference.
2. Handle this similar to `try`/`catch`. The present situation is similar to assuming that no exception is ever caught. Instead, we can treat a labeled statement like a `try`, a `break` like an exception, and consider the "exception" caught if the `break` matches the label.

Option 2 doesn't seem too bad to implement and a lot of the scaffolding is already in place, so I'm going to try and move forward with that.
