### ISSUE TITLE
Using dart:ui in plain dart application no flutter

### ISSUE THREAD

**Issue by felithium** [dart-lang/sdk#48325]
Is it possible to use the ```dart:ui``` package  in a non flutter (dart) application?

When I try to run my dart file with ```dart main.dart``` I get the following error:

```Error: Not found: 'dart:ui'```

**Comment by kevmoo** [comment]
You cannot! That library is only loaded when accessed via a flutter process.

**Comment by jellynoone** [comment]
I just wanted to chime in since I was asking myself the same question recently, and I think the problems stems from what we (regular consumers) generally think of as **Flutter**.

I think most people, myself included, when talking about flutter think about the **framework** not necessarily the **engine**.

So, I think this question might actually be asking how can I use the `dart:ui` package **without** the Flutter **framework** not necessarily the **engine**.  This is of course possible, following the bellow steps. Also, it helps to think of the `flutter` command line tool not as the *framework* tool but the *engine* tool, with just the templates having a preference for the framework.

Steps to an application without the framework:
```yaml
# pubspec.yaml

name: app
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  sky_engine:
    sdk: flutter
```

**Comment by jellynoone** [comment]
I just wanted to chime in since I was asking myself the same question recently, and I think the problems stems from what we (regular consumers) generally think of as **Flutter**.

I think most people, myself included, when talking about flutter think about the **framework** not necessarily the **engine**.

So, I think this question might actually be asking how can I use the `dart:ui` package **without** the Flutter **framework** not necessarily the **engine**.  This is of course possible, following the bellow steps. Also, it helps to think of the `flutter` command line tool not as the *framework* tool but the *engine* tool, with just the templates having a preference for the framework.

Steps to an application without the framework:
```yaml
# pubspec.yaml

name: app
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  sky_engine:
    sdk: flutter
```
```dart
// main.lib
import 'dart:async';
import 'dart:ui';

void main() {
  final pictures = createPictures().map((e) {
    final b = SceneBuilder()..addPicture(Offset.zero, e);
    return b.build();
  });

  var iterator = pictures.iterator;
  window.onBeginFrame = (_) {
    if (!iterator.moveNext()) {
      iterator = pictures.iterator;
      iterator.moveNext();
    }
    window.render(iterator.current);
  };
  Timer.periodic(Duration(milliseconds: 1000), (_) => window.scheduleFrame());
}

List<Picture> createPictures() {
  return [
    createPicture(Paint()..color = Color.fromARGB(255, 100, 100, 100)),
    createPicture(Paint()..color = Color.fromARGB(255, 30, 120, 120)),
    createPicture(Paint()..color = Color.fromARGB(255, 120, 30, 120)),
    createPicture(Paint()..color = Color.fromARGB(255, 120, 120, 30)),
  ];
}

Picture createPicture(Paint paint) {
  final recorder = PictureRecorder();
  draw(Canvas(recorder), paint);
  return recorder.endRecording();
}

void draw(Canvas canvas, Paint paint) {
  canvas.drawRect(Rect.largest, paint);
}
```
Then run `flutter create --platforms=web .`. _This adds the necessary files to support the web._

And then simply run: `flutter run lib/main.dart` or use the IDE of choice to start process.

Just a note, the `sky_engine` really is the low level engine now called `flutter_engine`. And as @kevmoo mentioned before running this through `flutter` is required because the native ui libraries are loaded through it. But the before described steps work for building an application without the **Flutter framework**.

Also probably the source of confusion is the naming `dart:ui` but  it helps to think of it as `flutter:ui` or `flutter:low_level_ui_tools`
