### ISSUE TITLE
[dart2js] Minified version with generics code is not working.

### ISSUE THREAD

**Issue by BirjuVachhani** [dart-lang/sdk#48337]
This actually happened while running Flutter app in release mode on web but since it has nothing to do with Flutter, I am filing this issue here. Please look at the sample code first.

## Steps to Reproduce

1. Compile provided code with `dart compile js code.dart` and run the generated output `out.js` file. You will get **Expected results** with no errors.
2. Compile the same code with `dart compile js -m code.dart` and run the generated output `out.js` file. This is minified version of the dart code in js. This throws exception, ends with error and gives **Actual results**.

> Note that I am using Nodejs to execute generated js file on the machine but It yields the same output if ran into a Flutter application in release mode on web. This also runs well in dartpad which I am assuming does not minify the code.

**Expected results:** 

```
CONVERSION KEY: RectangleNode-FrameNode
Frame
from: RectangleNode
```

**Actual results:** 

```
CONVERSION KEY: minified:x-minified:j
/Users/birjuvachhani/out.js:363
aX(a,b){throw A.a(A.aR(A.aN(a,A.b5(a,b),A.e(b,null))))},
        ^

TypeError: null: type 'minified:L' is not a subtype of type 'minified:q<minified:i, minified:j>'
    at Object.a (/Users/birjuvachhani/out.js:102:3)
    at Object.aX (/Users/birjuvachhani/out.js:363:17)
    at h.bF [as a] (/Users/birjuvachhani/out.js:358:3)
    at h.bJ (/Users/birjuvachhani/out.js:330:10)
    at c2 (/Users/birjuvachhani/out.js:980:7)
    at /Users/birjuvachhani/out.js:1208:6
    at /Users/birjuvachhani/out.js:1201:71
    at dartProgram (/Users/birjuvachhani/out.js:1205:84)
    at Object.<anonymous> (/Users/birjuvachhani/out.js:1208:15)
    at Module._compile (node:internal/modules/cjs/loader:1097:14) {
  dartException: R {
    a: "TypeError: null: type 'minified:L' is not a subtype of type 'minified:q<minified:i, minified:j>'"
  }
}
```

<details>
<summary>Code sample</summary>

```dart
void main() {
  final SceneNode node = RectangleNode();
  final FrameNode convertedNode =
      InterNodeTypeConverter().convertTo(from: node);
  print(convertedNode.name);
  print('from: ${convertedNode.from}');
}

abstract class NodeConversion<F extends SceneNode, T extends SceneNode> {
  const NodeConversion();

  T convert(F node);
}

abstract class SceneNode {
  String get name;

  final String from;

  SceneNode(this.from);
}

class RectangleNode extends SceneNode {
  @override
  String get name => 'Rectangle';

  RectangleNode([String from = 'RectangleNode']) : super(from);
}

class FrameNode extends SceneNode {
  @override
  String get name => 'Frame';

  FrameNode([String from = 'FrameNode']) : super(from);
}

class EllipseNode extends SceneNode {
  @override
  String get name => 'Ellipse';

  EllipseNode([String from = 'EllipseNode']) : super(from);
}

class RectangleToFrameNodeConversion
    extends NodeConversion<RectangleNode, FrameNode> {
  const RectangleToFrameNodeConversion();

  @override
  FrameNode convert(RectangleNode node) {
    return FrameNode(node.from);
  }
}

class EllipseToFrameNodeConversion
    extends NodeConversion<EllipseNode, FrameNode> {
  const EllipseToFrameNodeConversion();

  @override
  FrameNode convert(EllipseNode node) {
    return FrameNode(node.from);
  }
}

class InterNodeTypeConverter {
  static final InterNodeTypeConverter _instance = InterNodeTypeConverter._();

  const InterNodeTypeConverter._();

  factory InterNodeTypeConverter() => _instance;

  static const Map<String, NodeConversion> _converters = {
    'RectangleNode-FrameNode': RectangleToFrameNodeConversion(),
    'EllipseNode-FrameNode': EllipseToFrameNodeConversion(),
  };

  /// '$T' -> is the exact same type as receiver of the result of this function.
  /// However this trick does not work on [F} since [from] can be of parent
  /// type, '$F' would return type of the reference not the type of the object.
  T convertTo<T extends SceneNode, F extends SceneNode>({required F from}) {
    final String key = '${from.runtimeType}-$T';
    print('CONVERSION KEY: $key');
    assert(_converters.containsKey(key),
        'No converter found for ${from.runtimeType} to $T');
    final NodeConversion<F, T> converter =
        _converters[key] as NodeConversion<F, T>;

    return converter.convert(from);
  }
}

```

</details>

**Dart SDK Version**:

```
Dart SDK version: 2.16.0 (stable) (Mon Jan 31 15:28:59 2022 +0100) on "macos_x64"
```

**Comment by sigmundch** [comment]
Thanks @BirjuVachhani for filing this issue, and especially wanted to thank you for putting the time to create a small standalone program that reproduces the behavior you are seeing. This dramatically reduces the time for us to look into it and be able to respond. 

In this case, however, the behavior you are seeing is by design. Dart2js purposely doesn't preserve the name of the original types when running under minification. This is for two reasons - code size (removing the names helps a lot in keeping code-size low) and obfuscation (many apps don't want the name of the types to be visible in a production environment).

This is also why the [documentation of Type.toString][1] highlights that the String representation of types is consistent within the app, but it is not guaranteed to match any format and it is not guarenteed to contain the original name.

In your example, what happens is that the lookup of the key doesn't match the hand-written key. 

Good news is that there are many alternatives to get similar logic working. Some options include:
* Use a stable key that you control. In your case you can use `from.name` 
* Use type literals directly as keys, as opposed to the string representation of the type. Because in your example you are trying to compose two types, you may need to split this as two nested maps to achieve this:
```dart
Map _converters = {
  RectangleNode: { FrameNode: RectangleToFrameNodeConversion() },
  EllipseNode: { FrameNode: EllipseToFrameNodeConversion() },
}
```

* Use other patterns if you own the type hierarchy. Some ideas include: adding conversion methods on every member of the class hierarchy (e.g. `toFrameNode` added to SceneNode and overriden by every subclass), or use a visitor pattern on the SceneNodes hierarchy to implement such conversions.

Hope this information adds some clarity and you find it helpful.

[1]: https://api.dart.dev/stable/2.16.1/dart-core/Type/toString.html

**Comment by BirjuVachhani** [comment]
@sigmundch Thank you for this wonderful explanation and all the suggestions. I took approach of using Type literals and it works perfectly fine.

**Working code:**

```dart
static const Map<Type, Map<Type, NodeConversion>> _converters = {
    RectangleNode: {
      FrameNode: RectangleToFrameNodeConversion(),
    },
    EllipseNode: {
      FrameNode: EllipseToFrameNodeConversion(),
    },
  };

  /// '$T' -> is the exact same type as receiver of the result of this function.
  /// However this trick does not work on [F} since [from] can be of parent
  /// type, '$F' would return type of the reference not the type of the object.
  T convertTo<T extends SceneNode, F extends SceneNode>({required F from}) {
    print('CONVERSION KEY: ${from.runtimeType}');
    final NodeConversion? converter = _converters[from.runtimeType]?[T];
    assert(converter != null && converter is NodeConversion<F, T>, 'No converter found for $F to $T');
    final NodeConversion<F, T> typeConverter =
    converter as NodeConversion<F, T>;
    return typeConverter.convert(from);
  }
```
