### ISSUE TITLE
Type error when using int as query parameter

### ISSUE THREAD

**Issue by pacifi5t** [dart-lang/sdk#48351]
The type of `queryParameters` inside `Uri.https` is `Map<String, dynamic>?` but the code below will cause an exception (assuming the URL is correct):
> TypeError: 1: type 'int' is not a subtype of type 'Iterable\<dynamic\>'

```dart
import 'package:http/http.dart' as http;

void main() async {
 await http.get(Uri.https('example.org', '/path', {'q': 1}));
}
```

If the parameter type must be an `Iterable<dynamic>`, please make it so.

P.S.: I've browsed the source code and the problem lies deep down inside Dart's core. The `sky_engine` package (which is now obsolete) is responsible for making queries and it's devs have commented the type the `queryParameters` should be. It's `Map<String, String>?` or `Map<String, Iterable<String>>?`.

**Comment by natebosch** [comment]
There are a few APIs that have looser static types than what they accept at runtime because we don't have any way to express the type in Dart. The `queryParameters` argument to `Uri` constructors is one place where this happen.

The doc comment does call out this restriction.
https://api.dart.dev/stable/2.16.1/dart-core/Uri/Uri.html

> A value in the map must be either a string, or an [Iterable](https://api.dart.dev/stable/2.16.1/dart-core/Iterable-class.html) of strings, where the latter corresponds to multiple values for the same key.
