### ISSUE TITLE
Poor recovery when typing after enum name

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#48371]
```dart
enum E w^ {
  v
}
```
Here, `^` is the caret position, remove it when parsing.
The intension is to type `with`. But we break the enum declaration, and get separate function declaration instead.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/384794/153469723-bc9b5191-0413-40d8-9121-cbd9f2662600.png">

**Comment by bwilkerson** [comment]
I agree that the current situation is poor and that it would be better to produce a enum declaration, but I'm not sure what we want to do with the `w`. I'm guessing that we drop it because there isn't any place to store an identifier at that location in the AST. We'll probably end up suggesting both 'with' and 'implements', but then filtering should take care of the second suggestion.

**Comment by scheglov** [comment]
Yes, as long as the token is in the stream, we could still find it during completion. Speaking of which... Theoretically we could do it even now, without parser changes. But it seems that then we would be doing some portion of the recovery in completion logic, which is probably wrong place to do it.
