### ISSUE TITLE
Type inference stops working, if type gets inferred by extension.

### ISSUE THREAD

**Issue by AlexanderFarkas** [dart-lang/sdk#48448]
Example:
```
abstract class Field<TValue> {
  final TValue value;
  Field(this.value);

  ValidationPipeline<TValue, String> get pipeline;
}

class ValidationPipeline<TValue, TError> {
  final TValue _value;
  final TError? _error;
  ValidationPipeline(this._value, [this._error]);

  TError? call() {
    return _error;
  }
}


extension StringValidationPipelineX<TError> on ValidationPipeline<String, TError> {
  ValidationPipeline<String, TError> isEmail({required TError error}) {
    return this;
  }
}

class EmailField extends Field<String> {
  EmailField(String value) : super(value);

  @override
  ValidationPipeline<String, String> get pipeline => ValidationPipeline(value).isEmail(error: "Error"); // Fails to infer TError type
  // This works -> ValidationPipeline<String, String> get pipeline => ValidationPipeline(value);
}
```

Dart: 2.16.1

**Comment by lrhn** [comment]
I think this is working as intended.

A receiver never gets a context type. This means that for
```dart
@override
ValidationPipeline<String, String> get pipeline => 
    ValidationPipeline(value).isEmail(error: "Error"); // Fails to infer TError type
```
the `ValidationPipeline(value)` expression has *no* clues from the outside that can be used to determine the `TError` type.

You might think that the type inference can work backwards, seeing that `.isEmail(error: "Error")` requires an object with `TError` being `String`, but that's not how type inference works (it wouldn't work for an instance member either).

In order to know what `.isEmail(error: "Error")` even means, the compiler needs to *first* find the type of the receiver. 
Only when it has done that, without any clues to the type of `TError` which therefore defaults to `Object?`, can it start trying to see which members that type has. In this case it has none, because the extension method doesn't apply to a `ValidationPipeline<Object?, ...>`.

**Comment by AlexanderFarkas** [comment]
I don't get why `ValidationPipeline(value)` works in that case, if it "has no clues". 
If `ValidationPipeline(value)` could be inferred as `<String, String>`, why extension doesn't get this inference result and force `isEmail()` to have `error` parameter of type String?

**Comment by lrhn** [comment]
For
```dart
ValidationPipeline<String, String> get pipeline => ValidationPipeline(value);
```
the `ValidationPipeline(value)` has context type of `ValidationPipeline<String, String>` (because it's a returned expression it has the function's return type as context type), which is used to infer the type arguments.

In
```dart
ValidationPipeline<String, String> get pipeline => ValidationPipeline(value).isEmail(error: "Error");
```
the expression `ValidationPipeline(value).isEmail(error: "Error")` has that as context type too, but `ValidationPipeline(value)` itself is not the value of that expression, and there is no way to figure out how that type relates to `ValidationPipeline(value)` until we know what method `.isEmail` is, which we can't know before we know the type of `ValidationPipeline(value)`.
That's why `ValidationPipeline(value)` in *this* position has no context type to use when inferring type arguments.


The solution is to just write the types
```dart
ValidationPipeline<String, String> get pipeline => ValidationPipeline<String, String>(value).isEmail(error: "Error");
```

**Comment by AlexanderFarkas** [comment]
Thank you for such a detailed explanation.
Closing.
