### ISSUE TITLE
Why is over-riding field always considered "bad practice"?

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/sdk#48441]
The [lints](https://dart-lang.github.io/linter/lints/overridden_fields.html) claim:
_Overriding fields is almost always done unintentionally. **Regardless, it is a bad practice to do so.**_

I have a data structure like:
```dart
class DefaultColorTheme {
  final Color bg = Colors.white;
  final Color fg = Colors.black;
  final Color accent = Colors.orange;
  final bool isDark = false;
}

class GreenColorTheme extends DefaultColorTheme {
  @override
  final Color accent = Colors.green;
}
```

I don't see any bad practice here. I don't want to use methods as these are final fields so it would be a waste of cpu cycles. I just want to sub-class and change one default. 

I don't want to use constructor defaults because sub-classing constructor args is overly verbose, work to maintain, and error prone when defaults change. They also don't play well with non-consts.

**Comment by lrhn** [comment]
This all depends on how clever the compiler is.

The reason this particular approach is frowned upon is that it is potentially wasteful.

The class `GreenColorTheme` has all the fields of `DefaultColorTheme`, and one more. 
That means that an instance of `GreenColorTheme` has memory allocated to hold the `final Color accent = Color.orange;` value, and another memory slot to hold the `green` accent, even though everyone will only access the green one.

If you know that a `ColorTheme` will differ in accents, you'd instead define the class as 
```dart
class ColorTheme {
  final Color background;
  final Color foreground;
  final Color accent;
  final bool isDark;
  const ColorTheme({this.background = Colors.white, this.foreground = Colors,black,
      this.accent = Colors.orange, this.isDark = false);
}
```
Then you can declare `GreenColorScheme` as 
```dart
class GreenColorTheme extends ColorTheme {
   GreenColorTheme() : super(accent: Color.green);
```
or, more likely, not even introduce a new class:
```dart
const greenColorTheme = ColorTheme(accent: Color.green);
```

That is, if the `accent` varies, makes it a parameter, instead of introducing a *new* field which *shadows* the existing field.

(That said, a smart compiler could compile `final Color accent = Colors.orange;` into the same code as `Color get accent => Colors.orange;` if it thinks it can save space in that way. Most likely it won't, because it costs more code.)

**Comment by esDotDev** [comment]
Interesting, I didn't realize the compiler worked like that and the workarounds seem fine. Thx!

**Comment by eernstg** [comment]
Another comment on the initial example, I'd prefer this:

```dart
class DefaultColorTheme {
  Color get bg => Colors.white;
  Color get fg => Colors.black;
  Color get accent => Colors.orange;
  bool get isDark => false;
}

class GreenColorTheme extends DefaultColorTheme {
  @override
  Color get accent => Colors.green;
}
```

The point is that you don't use any affordances offered by instance variables, so you might as well just write the getter directly, and then you avoid storing any data that doesn't need to be stored per object anyway. Of course, you also avoid wasting storage by overriding an instance variable such that it is never used, because you don't introduce the instance variable in the first place.

If you aren't going to have many (say, millions) of instances of `ColorTheme`, then @lrhn's proposal may be preferable: You do pay for the per-object storage, but a compiler may be able to detect that the value of each instance variable can be obtained by a simple memory read (rather than by an invocation of a getter).

So it's a time/space trade-off, as usual.

**Comment by esDotDev** [comment]
Interesting, thanks for the info. I did think of that, but since ColorTheme would be accessed extremely frequently I thought there would be some extra cost to using a method vs a field, also it would prevent these instances from being final or const.

**Comment by eernstg** [comment]
Thanks! It is perfectly fine to have a getter in a class with a `const` constructor, and that getter can perform arbitrary computations. But it does matter whether you will call a getter or perform a raw memory read, if you want to obtain the value frequently.
