### ISSUE TITLE
Fractional value Error some time give rounded value and some time give double value   Dart SDK version: 2.16.0 (stable) (Mon Jan 31 15:28:59 2022 +0100) on "macos_x64"

### ISSUE THREAD

**Issue by sadaqatdev** [dart-lang/sdk#48446]
the following code give rounded value and some time give double value.

    var id1=45;
    var id2=47;

    var k1 = int.parse(id1.toString()).toDouble();

    var k2 = int.parse(id2.toString()).toDouble();

    var roomId = ((k1 + k2) * (k1 + k2 + 1) + (k1 * k2))/2;

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on Mac OS X 10.15.7 19H1715 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by lrhn** [comment]
The `int.parse(id1.toString()).toDouble()` is completely equivalent to `id1.toDouble()`. 

Not sure what you mean by showing a rounded value or a double value.

Since both `k1` and `k2` are double values, and the `/ 2` always creates a double value anyway, the result is *always* a double.
If you want an integer, you need to use `~/ 2` instead of `/ 2`.

In some cases the result is an integer value (a `double` with no fractional part) and somethings it has a `.5` fraction.
The latter happens when both `id1` and `id2` are odd numbers.

As far as I can see, everything works as intended.

What did you *expect*?
What did you see that did not match that expectation?
