### ISSUE TITLE
Grammar error for Paul 

### ISSUE THREAD

**Issue by IndieRobert** [dart-lang/sdk#48460]
Paul?
clientTable?["seat${seat}Pot"] += clientTable?["seat${seat}Front"] + (clientTable?["bettingRound"] == 1 ? (clientTable?["seat${seat}Dead"]) : 0);

compiles

clientTable?["seat${seat}Pot"] += clientTable?["seat${seat}Front"] + (clientTable?["bettingRound"] == 1 ? clientTable?["seat${seat}Dead"] : 0);

doesnt

From quadcore

**Comment by johnniwinther** [comment]
Rewritten example:
```
method(dynamic a, dynamic b) {
  a?[""] += a?[""] + (a?[""] == 1 ? a?[""] : 0);
  b?[""] += b?[""] + (b?[""] == 1 ? (b?[""]) : 0);
}
```
results in
```
temp/issue48460.dart:2:47: Error: Expected ':' before this.
  a?[""] += a?[""] + (a?[""] == 1 ? a?[""] : 0);
                                              ^
temp/issue48460.dart:2:47: Error: Expected an identifier, but got ')'.
Try inserting an identifier before ')'.
  a?[""] += a?[""] + (a?[""] == 1 ? a?[""] : 0);
                                              ^
```
meaning that the first line doesn't parser but the second does.

@IndieRobert Do that reflect you problem?

**Comment by IndieRobert** [comment]
Yup this is it

**Comment by jensjoha** [comment]
I haven't actually stepped through yet, but my guess is this:

When the `h?[0]` syntax was introduced instead of the `h.?[0]` we found that we had to disambiguate between a null-aware index operation and a conditional expression by trying if it _can_ parse as a conditional expression, and if it can that's what we do (https://github.com/dart-lang/sdk/issues/40267#issuecomment-588112082).

I think that's what's happening here: looking at `h?[0] : 0` it _can_ be parsed as a conditional expression, so it is.

**Comment by jensjoha** [comment]
Meaning that
```
true ? h ? [0] : 0;
```
is parsed as
```
true ? (h ? [0] : 0) /* missing stuff here */;
```

and

```
true ? h ? [0] : 0 : 1;
```

is parsed as

```
true ? (h ? [0] : 0) : 1;
```

**Comment by jensjoha** [comment]
> I think that's what's happening here: looking at `h?[0] : 0` it _can_ be parsed as a conditional expression, so it is.

Stepping through the parser confirms this:

For `true ? h?[0] : 0;` when it sees the first `?` it concludes it's a conditional expression. It continues to parse the expression before the colon. In doing that it sees `?` `[` and it checks if it can be parsed as a conditional expression. It can, so it does. Then we get back from the parsing of the (first) conditional expression (before the colon) and now we need there to be a colon. But there isn't, so it complains.

To the best of my knowledge this is what the language team wanted (e.g. [feature-specification](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#:~:text=Whenever%20there%20is%20a%20sequence%20of%20tokens%20which%20may%20be%20parsed%20either%20as%20a%20conditional%20expression%20or%20as%20two%20expressions%20separated%20by%20a%20colon%2C%20the%20first%20of%20which%20is%20a%20null%20aware%20subscript%2C%20parsers%20shall%20choose%20to%20parse%20as%20a%20conditional%20expression) and [comment](https://github.com/dart-lang/sdk/issues/40267#:~:text=Because%20x%3F%5B1%5D%3A%5B2%5D%20can%20be%20parsed%20as%20a%20conditional%20expression%2C%20it%20will%20not%20parse%20x%3F%5B%20as%20a%20null%2Daware%20index%20operator.)).

I'll remove my assignment and /cc @eernstg @lrhn @leafpetersen

**Comment by lrhn** [comment]
I concur, that's what I expect to happen too.
Yes, it's annoying that something that *can* be parsed correctly is instead disambiguated into something that doesn't parse, but that's the cost of doing local disambiguation. (The cost of doing non-local disambiguation is much higher parsing cost at less predictability.)

Wrap the entire thing in `{ ... : 0}`, and then both parsings become valid - `{true ? h ?[ 0 ] : 0 : 0 }`, and `h?[0]:0` being predictably always treated the same might just be better then.

**Comment by eernstg** [comment]
Of course, so it is actually working as intended.

**Comment by IndieRobert** [comment]
@eernstg wait, this is a mistake. You need to call on some other opinions eernstg imo you don't know what you are doing here. This is way too ugly. The intent of the case that doesn't parse is the one that will statistically always pop up, 1.000.000x more than a true actual mistake from the dev who is writing h ? [0] : 0

You can parse it, so parse it; as right now this is 3rd zone quality. You got to hack the thing so that ? ternary works with ? binary, no way around that, it's an order.
