### ISSUE TITLE
Compile size warnings are misleading

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#48495]
We should revisit both compile size warnings and the heuristics that rely on "token size" limits - in reality they rely on the source size including the comments and other constructs (like nested functions) which don't directly contribute to the size of the IL. 

These warnings are starting to pop up in the wild and [are confusing Flutter developers](https://twitter.com/gaetschwartz/status/1498931290543906816). For example [this method](https://github.com/rydmike/flex_color_scheme/blob/master/lib/src/flex_theme_data_extensions.dart#L46-L843) will trigger the warning - but in reality is not actually large in terms of IL. 

I think we should do the following:

- [x] move away from just looking at the source positions in the heuristics. This is a poor estimate for the size, in the presence of comments or many nested functions. Instead count AST nodes in the Kernel AST.
- [ ] Write some documentation explaining why large methods are bad and suggesting approaches to refactoring these methods
- [ ] Link to the documentation from the warning.

/cc @mkustermann @a-siva

**Comment by mraleph** [comment]
@alexmarkov could you drive this, given that you added the initial warning?

**Comment by alexmarkov** [comment]
The warning message I added in 76167c002d9503bea0e436058bc4fa60424dec8a doesn't change the compiler's behavior. It just shows it to users, as requested in https://github.com/flutter/flutter/issues/94461#issuecomment-1022384484. The actual heuristic for reducing optimizations was there for a long time, probably since Dart 1. The deficiencies of that heuristic were unnoticed until I started printing the warning.

The problem with large methods is that their compilation and optimization could be very slow and could take a lot of memory. So, when choosing between indefinite compilation / out of memory crash and lower optimization level, it makes sense to choose the latter. However, cut-off is somewhat arbitrary, _heuristical_: it's not like a method of 999 statements is compiled fine but a method of 1000 statements makes compiler hang forever. Compiler needs to decide that certain optimizations _might_ take too much time/memory and skip those optimizations as a preventive action.

So, it looks like we need to do the following:

1. Decide when to cut off the optimizations. I agree that current heuristic is broken and obviously causes too many false positives. I can take a look at improving the heuristic, but it would still be a heuristic with the possibilities of false positive. We can also remove the heuristic entirely and start collecting bug reports and examples where compilation time or compiler memory usage skyrocketed, in order to invent a better heuristic tuned to solve real cases. One such example is the recent bug report (https://github.com/flutter/flutter/issues/94461) about OOM which was not covered by the current heuristic (OOM happened during register allocation which cannot be disabled).

2. Decide when and how to better inform users about less optimizations performed and a possibility of OOM. I think it would be nice to have a better documentation about large methods and maybe a dartanalyzer lint. Also, front-end might be able to print a more detailed warning message pointing to the source code, as VM is not suited for that. I would need some help with all that.

Related issue: https://github.com/dart-lang/sdk/issues/48284

/cc @dnfield @Hixie @rakudrama @johnniwinther

**Comment by alexmarkov** [comment]
Does it make sense to revert the warning message for now (until we have a better documentation to point and a better heuristic) in order to avoid the confusion?

**Comment by a-siva** [comment]
> In general, when I'm seeing this warning it is for generated code that does not contain comments or nested functions - it's often something like a very large map initialization.
> 
> I think this warning is useful and actionable - for example, update your code generator to create smaller methods - as it currently stands. It's helping to identify false positives to the heuristics and creating some incentive to improve them. That said, I don't think we're getting tons of bug reports about OOM during compilation so I don't think it's critical that we keep it either.

It sounds like you would be fine making it an option if somebody wanted to check their app.

**Comment by Hixie** [comment]
We could just make it a lint, that's how we usually do these things.

In general I'm in favour of the compiler not warning about anything ever, and only having diagnostics in the analyzer.

**Comment by dnfield** [comment]
If it's to be a lint, it would have to somehow also apply to generated code, which people usually make the analyzer ignore.

**Comment by dnfield** [comment]
The idea being that generated code is the most common offender here.

**Comment by Hixie** [comment]
This would not be the only lint that was valuable for generated code.

**Comment by Hixie** [comment]
you can already put analysis_options.yaml files in subdirectories, i believe

**Comment by pq** [comment]
@dnfield: we've talked a lot about improving the configurablity of lints (to, for example, disable lints for tests or generated code but enabling would work the same way).   A few lints have test-awareness specifically baked in which is not ideal 😬.  I think some diagnostics get skipped for generated files but I can't recall off-hand.

But anyway, @Hixie is right:

> you can already put analysis_options.yaml files in subdirectories, i believe

nested options files are a thing and might be just the ticket for subdirectories of generated files.

**Comment by alexmarkov** [comment]
Filed https://github.com/dart-lang/sdk/issues/48518 for documentation and https://github.com/dart-lang/sdk/issues/48519 for the analyzer lint.
