### ISSUE TITLE
Load every api function from c library

### ISSUE THREAD

**Issue by Dampfwalze** [dart-lang/sdk#48497]
Currently you are able to load a subset of api function with `dart_api_dl.h` and `dart_api_dl.c`, as I described here: https://github.com/dart-lang/sdk/issues/47356
This is already quite useful. I am using it for async calls to a native library. But I find it quite hard, to convert all these complex data structures to dart code, especially, because with `Dart_PostCObject_DL` you can only send quite limited data structures. 

I would prefer to create Dart Objects directly from C, but the necessary functions are not provided by the dl loader. How can I load all the api functions?

**Comment by mraleph** [comment]
> I would prefer to create Dart Objects directly from C, but the necessary functions are not provided by the dl loader. 

We don't want to allow this because this implies reflective access to Dart objects - exactly what FFI is designed to avoid.

The appropriate design for the bindings layer is to send C objects to Dart and create Dart objects on the Dart side, not on the C side.

Another approach is to create helper functions in Dart for constructing the objects you need and call these helpers from C.

But the first approach is preferable, for a variety of reasons.
