### ISSUE TITLE
Is it possible to use signal handler to detect stack overflow and remove aot compiler's "CheckStackOverflow" instructions, just like Android ART VM?

### ISSUE THREAD

**Issue by eggfly** [dart-lang/sdk#48490]
As title, Android ART VM's aot compiler use a signal handler chain to detect Java's StackOverflowException and NullPointerException:

NullPointerException is this commit: 
* https://android.googlesource.com/platform/art/+/b373e09

I think with this, we can reduce the instructions binary size after `gen_snapshot` and also may speed up the runtime performance.

@mraleph How do you think?

Recently I made a experiment, removed these CheckStackOverflow instructions in `runtime/vm/compiler/frontend/base_flow_graph_builder.cc`:

```diff
diff --git a/runtime/vm/compiler/frontend/base_flow_graph_builder.cc b/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
index f510129c0ac..8832fe9d3b5 100644
--- a/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
+++ b/runtime/vm/compiler/frontend/base_flow_graph_builder.cc
@@ -229,20 +229,22 @@ Fragment BaseFlowGraphBuilder::Return(TokenPosition position,
 Fragment BaseFlowGraphBuilder::CheckStackOverflow(TokenPosition position,
                                                   intptr_t stack_depth,
                                                   intptr_t loop_depth) {
-  return Fragment(new (Z) CheckStackOverflowInstr(
-      InstructionSource(position), stack_depth, loop_depth, GetNextDeoptId(),
-      CheckStackOverflowInstr::kOsrAndPreemption));
+  return Fragment();
 }
 
 Fragment BaseFlowGraphBuilder::CheckStackOverflowInPrologue(
     TokenPosition position) {
-  if (IsInlining()) {
-    // If we are inlining don't actually attach the stack check.  We must still
-    // create the stack check in order to allocate a deopt id.
-    CheckStackOverflow(position, 0, 0);
-    return Fragment();
-  }
-  return CheckStackOverflow(position, 0, 0);
+  return Fragment();
 }

```

And compile a local flutter engine, build an Android flutter-gallery's release apk(https://github.com/flutter/gallery), before and after size(only armv7's app.so):

<img width="1183" alt="png" src="https://user-images.githubusercontent.com/922837/156156696-5abfb8a6-2920-4cbb-a5e5-b2eac5c1fcb9.png">

From 23428712 bytes to 23069264 bytes (reduced 1.5%, 359448 bytes).

**Comment by mraleph** [comment]
It's is possible, though you can't completely remove all them because they are used for more than just overflow checking - they also serve as a safepointing mechanism, so 1.5% saving is an overestimation. 

@mkustermann has previously (long ago) done this experiment - see https://codereview.chromium.org/2334243002/, we did not go forward with this implementation because we were worried about embeddability / portability of the VM. Signal based solution is also much more complicated and finicky - though does have better code size (and potentially performance). 

I have similarly prototyped a patch which turned `null` object into an actual `0` (or rather `1`) and used signal handler to implement implicit `null`-checks. It worked but again it was too complicated - so I iced it as well. 
 
As of today we don't have plans to move to signal handlers - because our concerns about portability and complexity remain. This might change in the future at some point.

**Comment by eggfly** [comment]
I see, thank you! @mraleph  😄
