### ISSUE TITLE
[vm] Support for MSVC builds on Windows?

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48544]
On Windows, we can build the sdk with `--no-clang` which will try to build with MSVC.

However, after 228c52ed4a8f8ea9e70bddb3ce8d29227edeaa77, this results in build errors.

```
C:\Users\dacoharkes\dart-sdk\sdk\runtime\vm\thread.h(272): error C7552: '_setjmp': purely intrinsic functions have no address
```

Do we want to keep the build working on MSVC? In that case we should probably add a nightly bot building on windows with `--no-clang` (similar to the GCC bot).

If not, we should maybe error out on that flag on Windows instead of trying to build.

Thoughts @mkustermann @mraleph @aam @alexmarkov @rmacnak-google?

**Comment by aam** [comment]
> Do we want to keep the build working on MSVC? In that case we should probably add a nightly bot building on windows with `--no-clang` (similar to the GCC bot).

I think we do, and I think we should

**Comment by aam** [comment]
Quick glance at what else MSVC highlighted: use of c++20 [designated initializers](https://github.com/dart-lang/sdk/blob/main/runtime/vm/message_snapshot.cc#L29), use of "gcc" [__attribute__(unused)](https://github.com/dart-lang/sdk/blob/main/runtime/bin/snapshot_utils.cc#L29) instead of `DART_UNUSED`
