### ISSUE TITLE
[sdk] Potential unnecessary factory constructor

### ISSUE THREAD

**Issue by albertodev01** [dart-lang/sdk#48614]
I am looking at some internals and I see that `MapEntry` is implemented as follows in Dart 2.16.1:

```dart
/// A key/value pair representing an entry in a [Map].
class MapEntry<K, V> {
  /// The key of the entry.
  final K key;

  /// The value associated to [key] in the map.
  final V value;

  /// Creates an entry with [key] and [value].
  const factory MapEntry(K key, V value) = MapEntry<K, V>._;

  const MapEntry._(this.key, this.value);

  String toString() => "MapEntry($key: $value)";
}
```

Why is there a factory? Couldn't it simply be a

```dart
/// A key/value pair representing an entry in a [Map].
class MapEntry<K, V> {
  /// The key of the entry.
  final K key;

  /// The value associated to [key] in the map.
  final V value;

  /// Creates an entry with [key] and [value].
  const MapEntry.(this.key, this.value);

  String toString() => "MapEntry($key: $value)";
}
```

with no factory?

**Comment by lrhn** [comment]
The one essential difference between a factory constructor and a generative constructor, as seebn from the outside of the class, is that you need a generative constructor in order to create a subclass.

Because `MapEntry` only exposes a factory constructor, you cannot do `class MyMapEntry<K, V> extends MapEntry<K, V> {...}`.
You can *implement` `MapEntry`.

This is an application of the Java rule ["Design for inheritance or else prohibit it"](https://books.google.dk/books?id=ka2VUBqHiWkC&pg=PA87&dq=%22Item+17:+Design+and+document+for+inheritance+or+else+prohibit+it%22+%22effective+java%22&hl=en&sa=X&ved=2ahUKEwjlyveZsND2AhVKiYsKHekSDSEQ6AF6BAgHEAI#v=onepage&q=%22Item%2017%3A%20Design%20and%20document%20for%20inheritance%20or%20else%20prohibit%20it%22%20%22effective%20java%22&f=false). It's prohibited, so we con't have to design for it.

One reason is that I hope, in some future version of Dart, to make `MapEntry` into a value-type (a record, or a tuple + view, or whichever other structural type we introduce). By not allowing people to extend, we avoid needing to keep the class an actual `class`. We can't prevent anyone from implementing the interface (if we could, we would have).

**Comment by albertodev01** [comment]
Makes sense, now I see why you decided to use a `factory`. No need to refactor the code then!
