### ISSUE TITLE
`analyzer.language` replacement for `analyzer.strong-mode.implicit-dynamic`

### ISSUE THREAD

**Issue by DetachHead** [dart-lang/sdk#48651]
the `strict-inference` and `strict-raw-types` rules don't replace `strong-mode.implicit-dynamic` as they don't complain about implicit dynamics in function arguments:

```dart
void foo(a) {}
```

when `implicit-dynamic` is enabled:
```
error • lib\a\a.dart:1:10 • Missing parameter type for 'a'. Try adding an explicit type, or remove implicit-dynamic from your analysis options file. • implicit_dynamic_parameter
```
see https://github.com/dart-lang/sdk/issues/48650#issuecomment-1076493359

**Comment by parlough** [comment]
It seems that it will work if you reference the parameter in the body, but the spec for the mode explicitly excludes parameters not referenced. @srawlins can perhaps provide more context around that decision.

> A parameter of a non-abstract function, which is declared without a type, and which is not referenced from inside the function body does not contain an inference failure.

**Comment by srawlins** [comment]
I think it's not an inference failure because there is no situation in which the parameter type is inferred. It just doesn't enter the equation. I definitely understand that it seems like if `var foo;` is reported, then so should `void f(foo) {}`.

Not sure if there is a lint rule which guards against untyped parameters, but [type_annotate_public_apis](https://dart-lang.github.io/linter/lints/type_annotate_public_apis.html) gets you part way.

**Comment by DetachHead** [comment]
ah i see, thanks! as long as the warning shows up when it's used i'm happy with that
