### ISSUE TITLE
`unnecessary_cast` when it's necessary, or it's a mistake

### ISSUE THREAD

**Issue by RafaRuiz** [dart-lang/sdk#48667]
Using:

* Dart 2.16.1 • DevTools 2.9.2
* MacOSX
* Android Studio for Flutter

I'm trying to create an extension that gives me the "first" on a `Stream` of a generic type `T`, so `.first` would return `Future<T>`.

Since I come from a Kotlin nature, I like to use the `firstOrNull` words, even though I shouldn't. Let's ignore the name of the extension, let's see the issue.

When I do:

```
Stream<T>()
  .timeout(const Duration(seconds: 1)
  .take(1)
  .first
  .then((_) => whatever());
```

since I don't have any values if timed out, I get a `Bad State: No Element`, which is understandable.

====================================

I want to create a `Future<T?>` that returns the first item or null if timed out, then I created:

```
extension StreamExtensions<T, E> on Stream<T> {
  Future<T?> firstOrNull([bool Function(T)? predicate]) {
    Future<T?> myFuture = first; 

    return myFuture.catchError((error) {
      if (error is StateError) {
        return null;
      } else {
        throw error;
      }
    });
  }
}
```

but if this happens, I get:

> Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type

But I'm typing `first` to `myFuture` which is `Future<T?>`.

Nonetheless, if I do:

```
extension StreamExtensions<T, E> on Stream<T> {
  Future<T?> firstOrNull([bool Function(T)? predicate]) {
    Future<T?> myFuture = first as Future<T>;  // This change

    return myFuture.catchError((error) {
      if (error is StateError) {
        return null;
      } else {
        throw error;
      }
    });
  }
}
```

that change suggests me on Android Studio an `unnecessary cast`.

Still I get the:

> Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type

The only way to solve this was:

```
extension StreamExtensions<T, E> on Stream<T> {
  Future<T?> firstOrNull([bool Function(T)? predicate]) {
    Future<T?> myFuture = first.then((value) => value as T?); // This change

    return myFuture.catchError((error) {
      if (error is StateError) {
        return null;
      } else {
        throw error;
      }
    });
  }
}
```

and that will work.
And still suggests me an `unnecessary_cast`, hence I have to ignore it through `// ignore: unnecessary_cast`.

Is this a mistake?

**Comment by lrhn** [comment]
For your original problem, your issue is that you are using `catchError`, which doesn't work that well with null safety.
You can do:
```dart
  return myFuture.then/*inferred <T?>*/((v) => v, (error) => error is StateError ? null : (throw error));
```
In general, if you want `catchError` to change the type, you should just switch to using `then` instead`.

Doing `first as Future<T?>` or `first as Future<T>` doesn't help with that problem. The `catchError` requires an argument that is returns a `FutureOr<T>`, and that is checked *at runtime* (because of covariant generics it's not statically safe). Doing static `as` casts won't help you.
 
Doing `Future<T?> myFuture = first.then((value) => value as T?);` works because it creates a real `Future<T?>`, not just a `Future<T>` unsafely cast to `Future<T?>`. An alternative would be `var myFuture = Future<T?>.value(first);`.

The warnings is correct, the cast is unnecessary. If you write `Future<T?> myFuture = first.then((value) => value);` instead, it still works because the type argument to the new future is inferred as `T?` and the return type of the function is therefore `FutureOr<T?>`. You're casting a value of type `T` to the supertype `T?` in a context that is already accepting `T?`, so the cast does nothing.
