### ISSUE TITLE
firstWhere orElse: () => null type error

### ISSUE THREAD

**Issue by OkilSaber** [dart-lang/sdk#48666]
Hello, I am working on a Flutter android application however I believe this is a Dart problem. Here is my configuration:
`Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"`
```Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2```

Now onto my problem:
I have a pretty simple class `Message`.
I call my backend to retrieve some messages so I receiver a `List<Message>`.
My code is the following:
```
      try {
        final List<Message?> latestMessages = await getLatestMessageOfChat();
        final List<Chat> chatsList = [];
        final parsedBody = json.decode(response.body);
        for (var i in parsedBody) {
          var test = latestMessages.firstWhere(
            (element) {
              return element.chatId == i["chat_id"];
            },
            orElse: () => null,
          );
          print(test);
          chatsList.add(
            // The factory constructor is as follow, so I am supposed to be able to receive null in the latest variable
            // factory Chat.fromJson(Map<String, dynamic> parsedJson, Message? latest)
            Chat.fromJson(
              i,
              latestMessages.firstWhere(
                (element) {
                  return element.chatId == i["chat_id"];
                },
                orElse: () => null,
              )
            ),
          );
        }
        return chatsList;
      } catch (e) {
       // The try catch is temporary it will be removed as it is just to better identify any thrown exceptions from this block of code.
        print("Error");
        print(e);
        print("///////////////////");
        return [];
      }```
Now the thing is that if I use `orElse: null` it throws the exception `Bad state no element`.
If I use `orElse: () => null` it throws this exception: `type '() => Null' is not a subtype of type '(() => Message)?' of 'orElse'`

Thank you for you time.

**Comment by eernstg** [comment]
Consider the situation where the predicate given to `firstWhere` does not return true for any element in the given list.

If you're passing `orElse: null` (or omitting the named argument entirely) then the invocation should throw a `StateError`. This matches the `Bad state no element` message.

If you're passing `orElse: () => null` then you will encounter a dynamic type error in the case where that function does not have the type `E Function()?`. So we need to know the element type `E` of the given list. Here is an example showing the most likely situation:

```dart
typedef Message = int; // We don't care about the contents of messages.

Future<List<Message>> getLatestMessageOfChat() async => [1, 2, 3];

void main() async {
  final List<Message?> latestMessages = await getLatestMessageOfChat();
  latestMessages.firstWhere((_) => true, orElse: () => null); // Throws.
}
```

In other words, I _think_ `getLatestMessageOfChat` returns a `List<Message>` (wrapped in a future because of the asynchrony, but essentially it's a `List<Message>`), and you are then assigning it to a variable of type `List<Message?>`.

So the reason why the invocation of `firstWhere` throws is that the provided `orElse` function does not have the correct type, it should have been a `Message Function()` but it was actually a `Null Function()`. The latter would have been OK if it should have been a `Message? Function()`, but the actual list doesn't admit null, so we don't have that `?` in the type.

This could have been a compile-time error (which it would have been in languages like Java, C#, Scala, and many others). However, Dart uses dynamically checked covariance for class type variables, and the consequence is that this particular situation is a run-time error rather than a compile-time error.

The mechanism you'd need in order to make it a compile-time error is statically checked variance, dart-lang/language#524.

**Comment by OkilSaber** [comment]
Thank you very much for your input. Your thought was in fact right, the function `getLatestMessageOfChat` returns a `List<Message>` but I thought that by manually typing the `latestMessages` variable as a `List<Message?>` would make it accept `Null`.
The workaround I found for this is to simply wrap the `firstWhere` in a `try` `catch` block and when catching I simply return `Null`.
```
  Message? getLatestChatMessage(int chatId, List<Message> latestMessages) {
    try {
      return latestMessages.firstWhere((message) => message.chatId == chatId);
    } catch (_) {
      return null;
    }
  }
```
Which I can call this way:
```        final Message? message = getLatestChatMessage(
          i["chat_id"],
          latestMessages,
        );```

**Comment by eernstg** [comment]
Consider this one as well: https://api.flutter.dev/flutter/package-collection_collection/IterableExtension/firstWhereOrNull.html.

**Comment by OkilSaber** [comment]
This is perfect, exactly what I was looking for! Thank you very much.
