### ISSUE TITLE
dartdevk failure co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t10

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#48700]
This test seems to be failing in the [dev compiler](https://dart-ci.appspot.com/log/any/dartdevk-strong-linux-release-chrome/10078/co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t10).  

cc @sigmundch @nshahan @lrhn

**Comment by nshahan** [comment]
cc @Markzipan

**Comment by Markzipan** [comment]
Fixed (see referenced commit above)

**Comment by leafpetersen** [comment]
Is this something we should consider for a cherry pick if required, or is it a fairly corner case issue?

**Comment by sigmundch** [comment]
@Markzipan filed https://github.com/dart-lang/sdk/issues/48731 to have the cherry pick discussion. We can go either way here. It's definitely only a corner case: the pattern that breaks is whether you can write a setter in an enum that has the same name as the enum value. A similar pattern could've been written by hand in the past without the enhanced-enum feature (like [this example][1]), so it's only related to the enum work because we have tests that are triggering that pattern.

[1]: https://github.com/dart-lang/sdk/issues/48710#issuecomment-1084526428
