### ISSUE TITLE
Diagnostics related to inheritance

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#48737]
The analyzer currently produces a diagnostic if a class declaration lists the same type in both the `extends` and `with` clauses:
```
class A {}
class B extends A with A {} // diagnostic on second `A`
```
It similarly produces a diagnostic if the same type is in both the `extends` and `implements` clauses:
```
class C extends A implements A {} // diagnostic on second `A`
```
But it doesn't produce a diagnostic if the same type is in both the `with` and `implements` clauses:
```
class D with A implements A {} // no diagnostic
```
This seems inconsistent. Should there be a diagnostic there?

@eernstg

**Comment by eernstg** [comment]
I think it's OK.

We do have a specified compile-time error for `class C extends A implements A {}`: https://github.com/dart-lang/language/blob/4a48c96956e36c1810734995c85917cda36d1b52/specification/dartLangSpec.tex#L4677.

You could argue that this error is unnecessarily harsh: The cause `implements A` ensures that the interface of `C` includes each member of the interface of `A`, with the same signature or some correct override thereof, but that's already ensured when `A` is the superclass of `C`. The rationale was that it is confusing to have this kind of redundancy, but the situation is benign and unambiguous, and we've used less stringent approaches in similar confusing-but-benign situations. Anyway, we've had this compile-time error for many years, and it's specified explicitly, so let's consider that error a given.

`class B extends A with A {}` is covered by the same rule, because the meaning of a mixin application is a class declaration where the mixin is implemented; here it's `class B extends AwithA {}`, where the class `AwithA` has superclass `A` and also has the clause `implements A`: https://github.com/dart-lang/language/blob/4a48c96956e36c1810734995c85917cda36d1b52/specification/dartLangSpec.tex#L5602.

In contrast, with `class D with A implements A {}` we have the `implements A` in the superclass (induced by the mixin application `Object with A`), and it is in general not an error to specify `implements A` on a class, even in the case where one or more (direct or indirect) superinterfaces also have `implements A`.

**Comment by bwilkerson** [comment]
That makes sense, thanks.
