### ISSUE TITLE
[CP] DDC support for static setters of const fields and enhanced num fields in 2.17 beta 3/stable cut

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#48731]
**commit(s) to merge**: a75656502a427eb3c42c8e5b1c06a4900fe126e9 and 471fcee0795acfa9c20b8e980ac7db9cd8d336bc

**merge instructions**: merge cherrypicks cleanly into the (tentative) 2.17 beta 3/stable cut.

**What is the issue**: DDC historically does not support static setters of const fields (these were stubbed and never actually executed by the runtime). Enhanced enum tests later tickled this pattern, as enum fields are lowered to const fields by the CFE.

**What is the fix**: DDC now no longer emits enum fields inline (which was an optimization). Additionally, DDC now lazily emits static accessors that shadow any lazily-emitted field (const, static, etc.), and its runtime was updated to execute lazy setters.

**Why cherrypick**: This is a rare edge case that's unlikely to be hit in most code patterns. However, the ensuing Javascript type error is difficult to mitigate without avoiding the pattern entirely and may reflect poorly if encountered.

**Risk**: Little

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/48700, https://github.com/dart-lang/sdk/issues/48717

/cc @mit-mit @whesse @athomas @vsmenon @devoncarew @sigmundch

**Comment by sigmundch** [comment]
/cc @leafpetersen

(copying the same comment from the original bug here) We can go either way on this cherry-pick. It's to address a rare corner case only. The pattern that breaks is whether you can write a setter in an enum that has the same name as the enum value.

Technically a similar pattern could've been written by hand in the past without the enhanced-enum feature (like https://github.com/dart-lang/sdk/issues/48710#issuecomment-1084526428), so it's only related to the enum work because we have tests that are triggering that pattern.

This early in the cherry-pick process I'm OK adding it in, but had we encountered this issue in 2 weeks I would have a different opinion and leaned against cherry-picking to avoid destabilizing the build.

**Comment by leafpetersen** [comment]
I'm fine not cherry picking this.

**Comment by Markzipan** [comment]
This is very low risk (and not a particular useful feature), so I'm fine with not cherry-picking this as well

**Comment by sigmundch** [comment]
@Markzipan Turns out that the likely candidate build for 2.17 is 2.17.0-266.0.dev. So the first commit above made it into the cut, but the second didn't.

We are inclined not to add the latter as a cherry pick, but we wanted to confirm: are there any problems in getting the first one without the second one? If so, we should reconsider cherry-picking it (or cherry-picking a change to undo the first change).

Let us know!

**Comment by Markzipan** [comment]
No worries - there aren't any issues with selecting either of those commits out-of-order. The former actually doesn't do anything until the latter is in, so it's safely masked.
