### ISSUE TITLE
Improve performance of type literals / instantiations

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#48757]
Currently the Dart VM compiles uses of uninstantiated type literals, such as
```dart
class X<T> {
  Type get getTypeLiteral => T;
}
```
into 
```
   v3 <- LoadField(v2 . :type_arguments {final}) T{TypeArguments}
   v5 <- InstantiateType:12(X0, instantiator_type_args(v3), function_type_args(v0)) T{*?}
   Return:16(v5)
```
This `InstantiateType` will always perform a runtime call.

We should optimize the implementation of `InstantiateType` in the VM to avoid runtime calls whenever possible.

/cc @gaaclarke

**Comment by mkustermann** [comment]
@gaaclarke Could you find out what the Dart code in flutter looks like that causes those runtime calls? It would help ensuring any optimizations cover that case.

**Comment by gaaclarke** [comment]
Here are the places I found it in the framework.  Some of them sound pretty fundamental.  I'll see if I can figure out who is the culprit but it's a bit difficult since the stacktrace is truncated  at `Precompiled_Stub_CallToRuntime` for some reason:
- https://github.com/flutter/flutter/blob/f5f9ad915e554283ccff109fed969d9ef255fb91/packages/flutter/lib/src/foundation/key.dart#L112:L112
- https://github.com/flutter/flutter/blob/f5f9ad915e554283ccff109fed969d9ef255fb91/packages/flutter/lib/src/widgets/localizations.dart#L132:L132
- https://github.com/flutter/flutter/blob/f5f9ad915e554283ccff109fed969d9ef255fb91/packages/flutter/lib/src/foundation/basic_types.dart#L237:L237
- https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/actions.dart#L213:L213
- https://github.com/flutter/flutter/blob/f5f9ad915e554283ccff109fed969d9ef255fb91/packages/flutter/lib/src/widgets/actions.dart#L767:L767
- https://github.com/flutter/flutter/blob/f5f9ad915e554283ccff109fed969d9ef255fb91/packages/flutter/lib/src/widgets/actions.dart#L796:L796
- https://github.com/flutter/flutter/blob/f5f9ad915e554283ccff109fed969d9ef255fb91/packages/flutter/lib/src/widgets/actions.dart#L727:L727
- https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/diagnostics.dart#L2836:L2836

**Comment by gaaclarke** [comment]
I put print statements around all the usages listed in https://github.com/dart-lang/sdk/issues/48757#issuecomment-1091962607 and none of those are the things that are getting called with each build.  There must be another construct that leads to `InstantiateType`  I tried putting print statements around things like `Type type = foo.runtimeType` as well.  I could not find it.

I briefly looked at `CallToRuntime` to figure out why it is truncating my stacktrace, that seems like a bug too.  I see that it's making a new frame, maybe that resetting it.  This quickly got beyond me.

**Comment by mkustermann** [comment]
This is really helpful, thanks @gaaclarke! It seems that all those usages are simply using `T` as the type literal, which we can add a fast case for rather easily. I may look into doing that.

**Comment by mkustermann** [comment]
Have sent out [cl/]241968](https://dart-review.googlesource.com/c/sdk/+/241968) for review, which should make the cases mentioned above in the links very fast (10x+ faster than currently)

**Comment by mraleph** [comment]
On startup of a large internal application we hit `DRT_InstantiateType` 1020 times has the following breakdown:

```
dart::DRT_InstantiateType (runtime_entry.cc)
1,020	100.00%	Stub_CallToRuntime
	1,020	100.00%	Stub_InstantiateType
		642	62.94%	Element.dependOnInheritedWidgetOfExactType_1483
		125	12.25%	Element.getElementForInheritedWidgetOfExactType_7011
		124	12.16%	AnnotatedRegionLayer.findAnnotations_39092 
		57	5.588%	Element.findAncestorWidgetOfExactType_40699 
```

there are few other call-sites with lower counts. I think these should all be hit by @mkustermann optimization.

**Comment by mkustermann** [comment]
The most common cases should be handled now and since there's no other immediate work in this area planned, I'll close this issue for now.

**Comment by gaaclarke** [comment]
This gave us a ~7% reduction in our build microbenchmarks: https://flutter-flutter-perf.skia.org/e/?end=1651129200&queries=sub_result%3Dstock_build_iteration%26sub_result%3Dstock_build_iteration_probability_5pct
