### ISSUE TITLE
[analyzer] opposite conditions

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#48756]
I guess it would be helpful to warn the user when a condition is always `true` or `false`, based on opposite/negated conditions.

E.g.

```dart
void f(bool b) {
  if (b && !b) {
    print('never');
  }
  if (b || !b) {
    print('always');
  }
}

void f2(int i) {
  if (i > 0 && i <= 0) {
    print('never');
  }
  if (i > 0 || i <= 0) {
    print('always');
  }
}
```

I guess it is the basis, for conditions simplification at a later stage, e.g.

```dart
void f(int i, List<String> list) {
  var result = i > 0 && list[i - 1] == 'a' || i <= 0;
}
```

to 

```dart
void f(int i, List<String> list) {
  var result = i <= 0 || list[i - 1] == 'a';
}
```

(because `i > 0` and `i <= 0` are the opposite of each other).

**Comment by lrhn** [comment]
That's a tricky thing to detect since it depends on the runtime semantics of the tests.

For local variables containing booleans, and written as `b || !b` (how Shakespearean!), it's simple, but the moment you start reading a field or global variable, you can't assume that the value is the same on both reads.

For integers `i < 0 || i >= 0` is always true. Not for doubles, though. 
And if the code isn't null safe, changing `i > 0 || b <= 0` to `true` might remove an error. (I guess the analyzer would just assume null safe libraries to run in null-safe mode. It's only static analysis, so it can ignore the dirty truths of run-time.)

**Comment by bwilkerson** [comment]
Yeah, we foolishly tried that once. The result is the lint `invariant_booleans`, which has had more issues raised against it than any other lint. We've talked several times about deprecating the lint, but haven't yet done so.

Given that we already have something approximating this, I'm going to close this issue.

@pq

**Comment by pq** [comment]
💯 

In practice `invariant_booleans` has been really fraught and records the highest number of lint false positives ***by far***.

https://github.com/dart-lang/linter/issues/3336
