### ISSUE TITLE
isNotOptional returns true for a named, required parameter

### ISSUE THREAD

**Issue by CicadaCinema** [dart-lang/sdk#48793]
Since the addition of the `required` keyword superseding the `@required` annotation, [this](https://github.com/dart-lang/sdk/blob/139385c6154d73236a94e2171190904ffbb32845/pkg/analyzer/lib/dart/element/element.dart#L1526) part of the docstring does not hold true any more.

I was working on https://github.com/dart-lang/sdk/issues/48206 and I added the following to [deprecated_member_use_verifier.dart](https://github.com/dart-lang/sdk/blob/f398c9f3c1b190d50b4ca91f3b81a48830940616/pkg/analyzer/lib/src/error/deprecated_member_use_verifier.dart#L182):
```dart
if (element is ParameterElement && element.isNotOptional) {
    print('${element.name} is both deprecated and required');
}
```

Running the static analyser on the test file:
```dart
void f({@deprecated required int deprecated_and_required_named_parameter}) {}

void g() {
  f(deprecated_and_required_named_parameter: 2);
}
```
I get `deprecated_and_required_named_parameter is both deprecated and required` which should not happen because the docstring says `element.isNotOptional` should evaluate to true.

**Comment by lrhn** [comment]
Maybe the linked documentation has always been wrong. I'd have thought it should return *true* for a `@required` parameter, not `false`. (But double-negations are always hard to grok, so I'm not even sure.)

**Comment by CicadaCinema** [comment]
> Maybe the linked documentation has always been wrong. I'd have thought it should return _true_ for a `@required` parameter, not `false`. (But double-negations are always hard to grok, so I'm not even sure.)

IIRC `required` replaced `@required` at some point, when Dart became null safe. The documentation is from April 2019.

Maybe it makes sense to require the documentation to say that it in fact evaluates to true even if the parameter is named and also marked as `required`?

**Comment by bwilkerson** [comment]
Assuming that we're talking about [`ParameterElement.isNotOptional`](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/dart/element/element.dart#L1530), that's working as intended. The documentation reads:

> Return `true` if this parameter is a required parameter. Required parameters are always positional, unless the experiment 'non-nullable' is enabled, in which case named parameters can also be required.
>
> Note: regardless of the state of the 'non-nullable' experiment, this will return `false` for a named parameter that is annotated with the `@required` annotation.

The reason for the distinction is because it's important for some of the tooling built on the analyzer to be able to independently determine whether the annotation and the keyword exist. There might be one, or the other, or neither, or both. To determine whether the element has the annotation, use [`Element.hasRequired`](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/dart/element/element.dart#L588).

There is also a TODO in the code saying that the getter should be renamed to `isRequired`.

**Comment by CicadaCinema** [comment]
Thank you!

**Comment by lrhn** [comment]
So the `isNotOptional` getter returns `false` for `({@required required int foo})`?
(That's what the documentation says. Should it say "return `false` for a *non-`required`* named parameter that is annotated with the `@required` annotation."?)

**Comment by bwilkerson** [comment]
It's trying to say that the presence or absence of the annotation is ignored: https://dart-review.googlesource.com/c/sdk/+/241052.
