### ISSUE TITLE
NoSuchMethodError when calling Enum extension methods against var

### ISSUE THREAD

**Issue by fleshgakker** [dart-lang/sdk#48821]
Dart 2.17.0

```
enum Test { test }

extension TestT on Test {
  get validator => validators[this];
  static final validators = {
     Test.test: '',
  }
}

TestClass(Test.test).body()

class TestClass {
  var param;
  TestClass(this.param)
  body(){
   print(param.runtimeType) // => Test
   print(param.validator)  // => NoSuchMethodError (NoSuchMethodError: Class 'Test' has no instance getter 'validator'.
  }
 }
```

```
class TestClass {
  final Test param;
  TestClass(this.param)
  body(){
   print(param.validator)  // => Works.
 }
```

But according to [Dart extensions static types](https://dart.dev/guides/language/extension-methods#static-types-and-dynamic) it should work in both cases? 

Perhaps any workarounds exists for the first scenario?

**Comment by lrhn** [comment]
This is working as intended.

Extension methods are dispatched based on the static type of the expression they're called on, not the dynamic type.
In this case, the static type of `param` is `dynamic`, not `Test`. The link specifically states that:
> You can’t invoke extension methods on variables of type dynamic.
(it's assumed to have all methods itself, and instance methods take precedence over extension methods.)

In the first scenario, you can explicitly cast the value to `Test`, so that the extension applies, or let it happen implicitly by using `param` in a context expecting a `Test` (like the `TestT` extension override syntax):
```dart
print((param as Test).validator);
print(TestT(param).validator);
```
