### ISSUE TITLE
Syntax for nullable type literals

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#48856]
Flutter uses type literals in some places that look like this:
```dart
Type foo<T>() => T;
```

While looking at adding some fast paths for the VM's implementation in this case, I noticed that the CFE's kernel AST node `TypeParameterType` has a `declaredNullability` (see [ast.dart](https://github.com/dart-lang/sdk/blob/e63cea6634a46b59f8c14f/pkg/kernel/lib/ast.dart#L11800)).

Yet it seems it's impossible to create a nullable type parameter literal: While `List<T?>` is a valid syntax, `T?` and `(T?)` are not. Is this intentional?

Does this imply that if a type literal of type `TypeParameterType` has never `declaredNullability=nullable`?

/cc @lrhn @johnniwinther

**Comment by johnniwinther** [comment]
cc @chloestefantsova

**Comment by mkustermann** [comment]
Actually talked with @chloestefantsova about this offline as well where we came to the conclusion that it isn't clear whether the syntax is supposed to work or not. Maybe @lrhn from language team knows?

**Comment by eernstg** [comment]
We did not introduce any new syntactic constructs to support the new type literals (like `List<int>`), we just took the opportunity to allow type literals whose syntactic form was already being added (in particular, because of the support for explicit generic instantiation of function tear-offs).

So the reason why we can have `List<int?>` is that this could also be a function tear-off where `List` denotes the function, and it is instantiated with the type argument list `<int?>` (and a type argument list allows for all syntactic forms for a type, so the `int?` in there is no problem). But `T?` is not an expression, it is only derivable from `<type>`, and hence `List<int>?` isn't an expression, and neither is `void Function()`.

The introduction of `<typeArguments>` as an alternative in the grammar rule for `<selector>` enabled the new syntactic forms, and it also created some difficulties with ambiguity, and I think it's likely to cause substantial ambiguity issues if we try to add support for `T?` as an expression. Just consider `{ o is int??1 : 2 }`, is that a set with one element `(o is int?) ? 1 : 2`, or is it a map with a key `o is int ?? 1` and a value `2`?

However, if anyone is using

```dart
Type foo<T>() => T;
```

with a type argument `S`, they could consider using `TypeToExpression<S>`:

```dart
typedef TypeToExpression<X> = X;
```

**Comment by mkustermann** [comment]
Thanks a lot, @eernstg ! You gave me the answer to my question, writing the following:
```dart
Type foo<T>() => MakeNullable<T>;
typedef MakeNullable<T> = T?;
```
will be turned into this Kernel
```dart
Type foo<T>() => T?;
```
which is precisely the case when the `TypeParameterType` will be marked as nullable.
=> So we do have to support that case.
