### ISSUE TITLE
Constant `List<T>` is not mutable after calling `.toList(growable: true)`

### ISSUE THREAD

**Issue by serverwentdown** [dart-lang/sdk#48859]
- Dart version: 2.18.0-29.0.dev
- Fails since 2.0.0
- Platform: Linux

I'm not sure if this behaviour is part of the language specification, but the empty constant generic list remains immutable after a call to `.toList(growable: true)`. As a user, I kinda expect that I get a growable `List` after that call as per documentation.

## Sample

```dart
List<String> create1() {
  return const [];
}

List<T> create2<T>() {
  return const [];
}

void main() {
  List<String> a = create1().toList(growable: true);
  // runtime: List<String>
  print(a.length);
  a.add("hello");
  List<String> b = create2<String>().toList(growable: true);
  // runtime: List<Never>
  print(b.length);
  b.add("hello");
}
```

## Output

```dart
0
0
Unhandled exception:
type 'String' is not a subtype of type 'Never' of 'value'
#0      List.add (dart:core-patch/growable_array.dart)
#1      main (file:///home/ambrose/const-list/main.dart:17:5)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

I had to work around this in my code with something like:

```dart
doSomething(List<String> inputList) {
  List<String> myList = inputList.where(...).toList(growable: true);
  if (myList.isEmpty) {
    myList = [];
  }
  // ...
}
```

Which is kinda not ideal...

**Comment by lrhn** [comment]
A compile-time constant expression cannot depend on a type argument, because those are only available at runtime.
```dart
List<T> create2<T>() {
  return const [];
}
```
This function creates a `const []`, which *cannot* be a `List<T>` because it doesn't know the `T` at compile-time.
So it creates a list of type `List<Never>`, which is the only type which is known to be assignable to the return type `List<T>` without actually knowing `T`.

So, working as intended.
