### ISSUE TITLE
I am beginner, can someone explain the syntax process for two dart functions how will the sequence for this dart snippet

### ISSUE THREAD

**Issue by kfal7** [dart-lang/sdk#48905]
List<int> forAll(Function f, List<int> intList){ 
    var newList = List<int>(); 
    for(var i = 0; i < intList.length; i ++){ 
      newList.add(f(intList[i]));
    } 
    return newList; 
} 

// Recursive factorial function 
int factorial(int x) { 
  if (x == 1) { 
    return 1; 
 } else { 
   return x*factorial(x-1); 
 } 
} 

main() { 
  var tester = [1,2,3]; 
  var result = forAll(factorial, tester); 
  print(tester); 
  print(result); 
}

**Comment by eernstg** [comment]
I transferred the issue to the SDK repository, because it does not give rise to any considerations about changing the language, it's about how to use the language that we already have.

I know, this repo is also not intended to handle "how to" questions, but many issues do have some of that anyway. So here's an attempt to help.

The only obvious problem with the code was the use of the constructor `List()`. That constructor isn't available any more because it is incompatible with sound null safety, so you should use `[]` to get an empty list. If the element type isn't specified somewhere around the `[]` you should use an explicit type argument, for instance, `<int>[]`.

It's a bad idea to use `List` as a type (this means `List<dynamic>` and that is almost always less type safe than a plain `var`), so I specified the appropriate type arguments in a few places. Similarly, the type `Function` is very vague, it's much better to use a real function type like `int Function(int)`.

Finally, you should probably use a for-in statement rather than the C-style for statement whenever possible, so I changed that as well.

The resulting code is here:

```dart
List<int> forAll(int Function(int) f, List<int> intList) {
  var newList = <int>[];
  for (var i in intList) {
    newList.add(f(i));
  }
  return newList;
}

int factorial(int x) {
  if (x == 1) {
    return 1;
  } else {
    return x * factorial(x - 1);
  }
}

main() {
  var tester = [1, 2, 3];
  var result = forAll(factorial, tester);
  print(tester);
  print(result);
}
```

Here is a version which uses a few additional features of the language:

```dart
List<X> forAll<X>(X Function(X) f, List<X> xs) => [for (var x in xs) f(x)];

int factorial(int x) => x == 1 ? 1 : x * factorial(x - 1);

main() {
  var tester = [1, 2, 3];
  var result = forAll(factorial, tester);
  print(tester);
  print(result);
}
```

In particular, `forAll` now works for any type `X` rather than just for `int`, as long as you have a list of `X` and a function from `X` to `X`.

Finally, I'll close this issue because it doesn't give rise to any changes to the Dart tools or systems.
