### ISSUE TITLE
New methods on DateTime (lastDayOfMonth, lastDayOfWeek, firstDayOfWeek)

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#48943]
Looking for `lastDayOfMonth` like feature, found [this StackOverflow question](https://stackoverflow.com/questions/14814941/how-to-find-last-day-of-month) and I really liked the way [Yogesh Parwani](https://stackoverflow.com/users/9988524/yogesh-parwani) mixed [Chris Buckett](https://stackoverflow.com/users/444738/chris-buckett) and [Kai Sellgren](https://stackoverflow.com/users/1364206/kai-sellgren) awnsers. As pointed by [Juniper Belmont](https://stackoverflow.com/users/1724321/juniper-belmont) on Buckett's answer, I do think this could be a new feature or at least pointed on the official documentation that these values could be obtained like this.

Code bellow:
```dart
extension DateTimeExtension on DateTime {

  DateTime get firstDayOfWeek => subtract(Duration(days: weekday - 1));

  DateTime get lastDayOfWeek => add(Duration(days: DateTime.daysPerWeek - weekday));

  DateTime get lastDayOfMonth => month < 12 ? DateTime(year, month + 1, 0) : DateTime(year + 1, 1, 0);
}
```

**Comment by natebosch** [comment]
cc @lrhn for thoughts

My initial reaction is we probably wouldn't put this in the SDK. I could imagine putting this into a utility package, but it's not a good fit for any of our existing core packages.

**Comment by lrhn** [comment]
We don't have a `package:core`, which is where it would fit.

I'm not *completely* opposed to putting DateTime extensions in `dart:core`, but I don't see this as features that will be widely used, which is one of the criteria for going into a `dart:` library (widely used by many users, or heavily used by some users, and something you'll only ever need one canonical version of, so we might as well provide it - or something which requires native interop with the runtime system).

The "firstDayOfWeek" is contentious, since some people (incorrectly :stuck_out_tongue:) consider Sunday the first day of the week, even though it is *obviously* Monday. That suggests having separate packages that you can choose between.

Maybe we should have a `package:calendar` (name currently taken by a 4-year-stale package.)

(Also, don't use `Duration` when calculating dates. Better implementation:
```dart
extension DateTimeFirstLast on DateTime {
  DateTime get firstDayOfWeek => DateTime.utc(year, month, day + 1 - weekday);
  DateTime get lastDayOfWeek => DateTime.utc(year, month, day + 7 - weekday);  
  DateTime get firstDayOfMonth => DateTime.utc(year, month, 1);
  DateTime get lastDayOfMonth => DateTime.utc(year, month + 1, 0);
  DateTime get firstDayOfYear => DateTime.utc(year, 1, 1);
  DateTime get lastDayOfYear => DateTime.utc(year, 12, 31);
}
```
which isn't affected by the time of the `DateTime` object it's called on, and uses UTC to represent time-less dates as recommended.)

**Comment by mnordine** [comment]
@FMorschel you should submit a PR to the time package: https://github.com/jogboms/time.dart

**Comment by FMorschel** [comment]
As this request is now on https://github.com/jogboms/time.dart as suggested, I'm closing this issue.
