### ISSUE TITLE
Add support for inlay hints

### ISSUE THREAD

**Issue by knopp** [dart-lang/sdk#48972]
It would be great if dart analyzer supported inlay hints for parameters and inferred types. As far as I can tell the [LSP spec ](https://github.com/microsoft/vscode/blob/778b74a2159983ba09568d069ef9c9ecd858f783/src/vscode-dts/vscode.d.ts#L4570-L4732)is finalised now.

**Comment by DanTup** [comment]
This was done in https://github.com/dart-lang/sdk/commit/15dfda917ae15ed40f6f9575625a5b0cf3ec4d0a / https://github.com/dart-lang/sdk/commit/8e2dbc1cdc05d5cbe134332dfcc8c7dc3c53eff2.

They're not in a stable release yet, but if you're on a pre-release build and using VS Code, you can hold down Ctrl+Option to see the hints (you can configure this behaviour in VS Code settings, but you'll need to configure it in the Dart-specific section since we override the default - which is to have them always visible).
