### ISSUE TITLE
Can't write nullable types in string interpolations

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#48999]
The following code is an error in the CFE and analyzer. It looks like the question mark is being misinterpreted as the beginning of a ternary expression.

```dart
void main() {
  dynamic i = 10;
  print('${i as int?}');
}
```

Analyzer errors:
```
Analyzing test_07.dart...              0.5s

  error • test_07.dart:35:12 • Conditions must have a static type of 'bool'. Try
          changing the condition. • non_bool_condition
  error • test_07.dart:35:21 • Expected an identifier. • missing_identifier
  error • test_07.dart:35:21 • Expected to find ':'. • expected_token
```

Compile time errors:
```
test_07.dart:35:21: Error: Expected an identifier, but got '}'.
Try inserting an identifier before '}'.
  print('${i as int?}');
                    ^
test_07.dart:35:21: Error: Expected ':' before this.
  print('${i as int?}');
                    ^
test_07.dart:35:14: Error: A value of type 'int' can't be assigned to a variable of type 'bool'.
  print('${i as int?}');
             ^
```

**Comment by asashour** [comment]
This can be fixed by adding `}` to the list in

https://github.com/dart-lang/sdk/blob/c50236ff9ca3a4ec91de870fe4f52d4492947756/pkg/_fe_analyzer_shared/lib/src/parser/parser_impl.dart#L6833


But I don't know how to write/execute similar tests as https://github.com/dart-lang/sdk/commit/01ac35b84460165b38b6b768c3a63048860497e3 for example, and running `front_end/test/parser_suite.dart` gives many `ExpectationFileMismatch` on Windows.

**Comment by bwilkerson** [comment]
The fix is in flight: https://dart-review.googlesource.com/c/sdk/+/249601.
