### ISSUE TITLE
Crash in dart2js triggered by new CL.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#49002]
I have a CL (https://dart-review.googlesource.com/c/sdk/+/244241/9) which causes a crash in dart2js (https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8814371261794806161/+/u/test_results/new_test_failures__logs_)

The error is
```
stdout:
 org-dartlang-sdk:///lib/async/future_impl.dart@42700+1:
 Internal Error: The compiler crashed when compiling this element.
 The compiler is broken.
 When compiling the above element, the compiler crashed. It is not
 possible to tell if this is caused by a problem in your program or
 not. Regardless, the compiler should not crash.
 The Dart team would greatly appreciate if you would take a moment to
 report this problem at http://dartbug.com/new.
 Please include the following information:
 * the name and version of your operating system,
 * the Dart SDK build number (build number could not be determined), and
 * the entire message you see here (including the full stack trace
   below as well as the source location above).
 The compiler crashed: 'package:compiler/src/ir/static_type.dart': Failed assertion: line 1034 pos 9: 'node.promotedType == null ||
             promotedType is ir.NullType ||
             promotedType is ir.FutureOrType ||
             typeEnvironment.isSubtypeOf(promotedType, node.promotedType,
                 ir.SubtypeCheckMode.ignoringNullabilities)': Unexpected promotion of VariableDeclaration(Object? source) in Arguments((source as _Future.T%, source{_Future.T%})). Expected TypeParameterType(_Future.T%), found InterfaceType(Object?)
 #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
 #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
 #2      StaticTypeVisitor.visitVariableGet (package:compiler/src/ir/static_type.dart:1034:9)
```

The code in question, if I interpret the offset correctly, is likely around the function:
```dart
_completeWithFutureOr(/* FutureOr<T> */ Object? source) {
    assert(identical(source as FutureOr<T>, source));
    if (source is Future<T>) {
      var nativeSource =
          source as Object; // Demote so we can promote to _Future.
      if (nativeSource is _Future) {
        var nativeFuture = nativeSource; // Prevent demotion from assignment.
        while (nativeFuture._isChained) {
          nativeFuture = nativeFuture._resultOrListeners;
        }
        assert(nativeFuture is _Future<T>);
        if (nativeFuture._isComplete) {
          return _setNativeFutureResult(nativeFuture);
        }
        assert(nativeFuture._mayAddListener);
        return _chainCoreFuture(nativeFuture);
      }
      _chainForeignFuture(source);
      return null;
    }
    assert(identical(source as T, source));
    return _setValue(source);
  }
```
(`@42700` is at this position, right after the return type, which is `_FutureListener?`).

I'll probably keep tweaking the code, and I'll say if it goes away. If not, it's blocking.

**Comment by fishythefish** [comment]
That particular assertion has been firing on a variety of programs for a while now. We probably need to revisit how our internal type promotion aligns with the CFE's, but since compilation works fine with assertions disabled, we haven't prioritized it.

**Comment by lrhn** [comment]
Since this code is intended to go into the SDK, it will likely mean completely disabling the assertion-enabled dart2js builders on the buildbot. (Either by marking everything as failing, or by disabling the builders entirely).

So, heads up, that may happen :)

**Comment by sigmundch** [comment]
@fishythefish I recall in the past we mentioned that we still needed it because it is more precise for unsound mode, but equally good for sound mode. Is there a hybrid that would make sense today? For example default to use the CFE promotion or bypass this check for null safe libraries?

/cc @johnniwinther

**Comment by fishythefish** [comment]
@sigmundch We've discussed this assertion in the past, but I don't have a great understanding of how our analysis compares to the CFE's. Our analysis was useful pre-null-safety, but some of the logic is now shared by the CFE, at least partly because the null safety spec mandated more type promotion. Our analysis may be able to produce narrower/more precise types than the CFE does (@rakudrama might know?), so whatever type we compute should be a subtype of what the CFE yields.

I think it makes sense to use the CFE's promoted type as the starting point for our analysis rather than the unpromoted type. However, I'm not sure whether the cases that trigger this assertion are situations where the CFE performs some type promotion that we could be performing but aren't, or simply bugs in our promotion logic. From discussion with @srujzs, I think there may be at least one bug related to JS interop.

**Comment by fishythefish** [comment]
Closing this since fffe5ce6ec59095ab632d7ab1c280b74cf9efd6c landed. We may still want to simplify static type computation in dart2js, but we can follow up on that separately.
