### ISSUE TITLE
Unexpected result of bitwise complement when compiled to JavaScript

### ISSUE THREAD

**Issue by renggli** [dart-lang/sdk#49019]
```dart 
import 'package:test/test.dart';

void main() {
  test('unary bitwise complement', () {
    expect(~42, -43);
  });
}
```

The above test passes in the Dart VM, but fails in JavaScript with the error `Expected: <-43> Actual: <4294967253>`. 

In the example above the compiler directly inlines `4294967253`, but when extracting the complement to variables it becomes visible that `~42` gets transformed to `-43 >>> 0` and then to `4294967253`.

Run with `dart test --platform chrome` in 
- Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "linux_x64"
- Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "linux_x64"
- Dart SDK version: 2.17.0 (stable) (Mon May 9 10:36:47 2022 +0200) on "macos_x64"

**Comment by lrhn** [comment]
Almost all web-compiled bitwise operations give 32-bit unsigned results.

The JavaScript operations give 32-bit signed results, except for `>>>`, and Dart chose, a long time ago, to give unsigned results instead. At the time, Dart did not have a `>>>` operator and integers were arbitrary-precision integers. As such, the web compiler had to make a choice between signed or unsigned, since there was no `>>>` operator to convert from signed to unsigned, and they chose unsigned results because it was a better default for the most common use of bitwise operation at the time, implementing crypto.

Now Dart has 64-bit integers instead, and a `>>>` operator, but changing existing web-compilation behavior will be breaking.

What you can do, also with functionality added after the original design choice, is `(~42).toSigned(32)`.

**Comment by sigmundch** [comment]
Thanks again for filing the issue! Besides @lrhn great summary for why this is our current design, you can find additional details on the topic in this article: https://dart.dev/guides/language/numbers.

**Comment by renggli** [comment]
Thank you for the explanation and link with additional details. The proposed solution of using `(~42).toSigned(32)` work perfectly. In my case, the intent of the JavaScript code I tried to port was to truncate the number, so I just replaced it with the intention revealing mathematical operation.
