### ISSUE TITLE
Analyzer: How to obtain nested generic-concrete type

### ISSUE THREAD

**Issue by petrnymsa** [dart-lang/sdk#49029]
This tracker is for issues related to:

* Analyzer
I am using analyzer together with source_gen  and i am trying to get concrete  type of generic arguments but can't a find a way to do it. Suppose I have something like

```
@DartMapper(mappers: [
  AutoMap<User, UserDto>(),
])
class AutoMapper {}
```
where

AutoMap is defined as 

```
class AutoMap<A, B> {
  const AutoMap();
}
```

I want to know types "User" and UserDto. Is it possible? Even more, is it possible to "visit" those types and get info about these types (fields,, etc).  

I am able to get to the point where I know mappers is list of AutoMap<A,B> 

![image](https://user-images.githubusercontent.com/21087414/168658629-af932581-1761-4c1e-9864-2e7824041ac6.png)

but no clue how to get exact type of 'A' and 'B'

**Comment by bwilkerson** [comment]
@natebosch @jakemac53

**Comment by natebosch** [comment]
As far as I know, you won't be able to get to `User` and `UserDto` from the `InterfaceTypeImpl` for `AutoMap`.

If I had to guess, was this `InterfaceTypeImpl` reached by going from the `DartObject` representing the metadata to the `DartType` for `DartMapper`, and then crawling down from there?

The specific instantiation values `User` and `UserDto` are not reachable from the `DartMapper` class. I think the only way to reach them is to crawl down the `DartObject` fields and the list value to pull out the specific instance represented by the `AutoMap<User, UserDto>()` const instantiation. Depending on what other generics and inference are involved you might be able to use the type of the list value instead of the element, but be careful that inference for a list literal in an argument position doesn't always use exactly the value types inside it.

The following code would do it, but it's not at all robust against differences in the annotation usage. You'll need to add more code around this to generalize, but it should show how to reach the right information through the analyzer APIs.

This also assumes that the named argument `mapper:` in `DartMapper` constructor corresponds to a field of the same name, otherwise the `getField('mappers')` call below would need to change.

```dart
      final autoMapperClass = library.getType('AutoMapper')!;
      final annotation = autoMapperClass.metadata.single;
      final constant = annotation.computeConstantValue()!;
      final field = constant.getField('mappers')!;
      final list = field.toListValue()!;
      final firstElement = list.first;
      final autoMapType = firstElement.type as ParameterizedType;
      final userType = autoMapType.typeArguments[0];
      final userDtoType = autoMapType.typeArguments[1];
```
