### ISSUE TITLE
Tests for quick fixes vs. parts without libraries

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#49046]
The test infrastructure for fixes expects the file can be analyzed.
But parts cannot be analyzed without their libraries.
Maybe we should use more integration like approach for these tests as well.

**Comment by bwilkerson** [comment]
> The test infrastructure for fixes expects the file can be analyzed.
> But parts cannot be analyzed without their libraries.

Do you mean that part files can't be analyzed without their library in the test framework, or that it can't be done in general? If it's the latter case, then it doesn't seem like an issue that we can't test it because users will never be offered fixes in unanalyzed files. If it's the former case, then we need to fix the test framework.

Using integration-like tests for this might be one way to fix the framework.

**Comment by srawlins** [comment]
@scheglov did you just land a fix for this?

**Comment by scheglov** [comment]
No, this issue states that there are tests that check what happens when quick fix is requested in a part file that does not know its library. But our test infrastructure expects that request for the resolved unit will always succeed. This is not true anymore - for parts we will return `PartWithoutLibraryResult`, and type cast will fail in the tests infrastructure.

We need to change the way we run these tests.

**Comment by scheglov** [comment]
Not an issue anymore.
