### ISSUE TITLE
Failures on [vm] Ensure transitive object copy allows low safepoint latencies

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#49060]
There are new test failures on [[vm] Ensure transitive object copy allows low safepoint latencies](https://github.com/dart-lang/sdk/commit/31ae00fb1386ff95eadb9e2bb3e8b86881ca579f).

The tests
```
vm/dart_2/isolates/fast_object_copy_test/0 Timeout (expected Pass)
vm/dart_2/isolates/fast_object_copy_test/1 Timeout (expected Pass)
vm/dart_2/isolates/fast_object_copy_test/2 Timeout (expected Pass)
vm/dart_2/isolates/fast_object_copy_test/3 Timeout (expected Pass)
vm/dart_2/isolates/fast_object_copy_test/4 Timeout (expected Pass)
vm/dart_2/isolates/fast_object_copy_test/5 Timeout (expected Pass)
```
are failing on configurations
```
dartk-linux-release-simarm
```

@mkustermann Could you please take a look?

**Comment by alexmarkov** [comment]
Jobs on the bots `vm-kernel-precomp-linux-release-simarm` and `vm-kernel-precomp-linux-release-simarm_x64` got cancelled after spending >2hr trying to deflake these tests.

**Comment by alexmarkov** [comment]
`vm-kernel-precomp-linux-release-simarm64` is also affected.

**Comment by mkustermann** [comment]
The test takes too long on the simulators. A CL was landed that was supposed to skip those tests on simulators (see https://github.com/dart-lang/sdk/commit/fb1210590b0835bc8570598fd87ab9a1ce299f62) - but it used `Slow` instead of the intended `SkipSlow`. Changed this now in https://github.com/dart-lang/sdk/commit/95360796c29d04575ccced5fe6105083c181fdb6
