### ISSUE TITLE
The argument type 'String' can't be assigned to the parameter type 'String'.

### ISSUE THREAD

**Issue by TheCarpetMerchant** [dart-lang/sdk#49076]
If this issue doesn't belong here, please point me in the right direction.

Here is the gist provoking the error "The argument type 'String' can't be assigned to the parameter type 'String'." :
https://dartpad.dev/?id=1e7a00dbebb913c30e23d6645a0a466e

This might be due to the way I'm writing the code, but the issue does seem weird.
It is for now easily solved by using `entry.value.toString()`.

**Comment by lrhn** [comment]
This place isn't wrong. You'll usually get faster responses for questions like this on stack overflow.

Your problem is the line:
```dart
extension MapToDropdown<K,String> on Map<K,String> {
```
The `<K, String>` means the extension has two type parameters, one called `K` and one called `String`.
That type parameter shadows the `String` type from `dart:core`. It's an unbounded type parameter, so it can have any typeat runtime, and therefore it's not assignable to `String` from `dart:core`.

Just remove the `, String`. You only need the one type parameter `<K>`.

**Comment by TheCarpetMerchant** [comment]
Thanks for the explanation :)
