### ISSUE TITLE
"Organize imports" quick fix doesn't account for `@TestOn` directive

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#49071]
Take the following code example:

```dart
@TestOn('windows')

import 'package:test/test.dart';
import 'package:winmd/winmd.dart';
import 'package:generator/generator.dart';

void main() {
...
}
```

The analyzer correctly flags that the last import is not alphabetically ordered. On using the VSCode quick fix ("Organize Imports"), this code is reordered thus:

```dart
import 'package:generator/generator.dart';
@TestOn('windows')

import 'package:test/test.dart';
import 'package:winmd/winmd.dart';

void main() {
...
}
```

which is of course incorrect (the `@TestOn` line should be first). 

Dart version:
```
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "windows_x64"
```

Flagging to @DanTup in case this is a DartCode issue (running v3.40.0).

**Comment by DanTup** [comment]
This looks like https://github.com/Dart-Code/Dart-Code/issues/3598 so I would've expected this to work. However looking at the definition of `TestOn`, it's not marked with `@Target({TargetKind.library})` so the server doesn't know that it should remain at the top.

@natebosch @jakemac53 is `@TestOn` _always_ library level? If so, I can send a change that adds `@Target({TargetKind.library})` which I believe will fix this.

**Comment by lrhn** [comment]
We should allow you to declare a name-less library as `library;`, so you'd have somewhere to put library-level annotations. The reordering is technically correct, because the original annotation belongs to the `test` library import, not the library, according to the language specification.

Tools which recognize annotations on the first import as being intended as annotations on the library are doing a hack, mainly because the "right thing" requires giving the library a name, which is annoying and verbose.

**Comment by DanTup** [comment]
> Tools which recognize annotations on the first import as being intended as annotations on the library are doing a hack,

It would definitely be nice if this was unambigious. The server has several places that have to add/re-order/remove imports that need to make assumptions about annotations.

But - it seems like quite a breaking (and perhaps annoying) change to say any use of `@TestOn` needs to have `library;` after it. If that's not to be enforced, then I think the server needs to handle this case better anyway (and I think we have a much less hacky way to do this using the [Target annotation](https://pub.dev/documentation/meta/latest/meta_meta/Target-class.html) noted above - assuming it could be applied to `TestOn`).

**Comment by timsneath** [comment]
I'm not as smart as you analyzer people, but [what you're saying](https://github.com/dart-lang/sdk/issues/49071#issuecomment-1133629369), @lrhn:

> "The reordering is technically correct, because the original annotation belongs to the test library import, not the library, according to the language specification."

doesn't match [what the documentation says](https://github.com/dart-lang/test/tree/master/pkgs/test#restricting-tests-to-certain-platforms):

> "The [@TestOn](https://pub.dev/documentation/test_api/latest/test_api.scaffolding/TestOn-class.html) annotation makes it easy to declare exactly which platforms a test file should run on. Just put it at the top of your file, **before any library or import declarations**" (emphasis mine)

I'm using `@TestOn` on certain tests only, by the way. I have a couple of `_test.dart` files that do not have this attribute, since they are intended to run on all platforms.

**Comment by lrhn** [comment]
From the language's perspective, annotations are put on declarations, and belong to the next following declaration.
As such, the `@TestOn` annotation is an annotation on the `import 'package:test/test.dart';` declaration.
(The grammar rule allowing the annotation is `<libraryImport> ::= <metadata> <importSpecification>`.)

From the perspective of a source rewrite tool which doesn't know what the `TestOn` annotation means, or how it's documented, moving the import declaration to somewhere else includes moving its annotations along. Or, equivalently, moving another import up before the `test` import will put it before the annotation too.

The `TestOn` annotation is documented and interpreted specially. When it's an annotation on the first import is treated as an annotation relating to the library, and the association to the import is ignored. That's not a general rule, not all annotations ar treated that way. Tools can obviously do that, but it requires special knowledge to know that the import annotation is really intended as a library annotation. Simply writing it in documentation doesn't make other tools know that (or even know that such annotations exist).

It's a hack, and the hackiness shows in situations like this, because it requires *every* tool to be in on the hack. 
If the analysis server adds an import for you, and it wants to put it first to keep things alphabetic, it could very well put it before the annotated import. It doesn't, which means it knows about the hack, and has added extra code to compensate.
The "organize imports" tool didn't know and hasn't added special casing, and therefore it treats `@TestOn` just as it would any other annotation on the import.

The *proper*, non-hackish solution, which doesn't require tools to treat this particular annotation specially, is to put the annotation on the library declaration. That's where metadata for the library goes. If you want DartDoc to document your library, you need to put the doc comment &mdash; a kind of metadata &mdash; on the library declaration. It can't just be on the first import (if you have imports, not every library does).

The problem with that solution is that to have a library declaration, you also have to give the library a name. That's *highly annoying* and potentially error-prone. If you give two libraries the same name, you can't import them into the same program.
So you have to give them *good* and *long* names. Nobody wants to do that, which is probably why the `@TestOn` annotation hack was introduced to begin with.

That's why I propose to fix that by allowing `library;` as a declaration to hang annotations and DartDoc on.
Then we can help people by having the tools which know the `TestOn` annotation introduce the `library;` declaration and move the annotation there (dart-fix, analyzer quick-fix, etc).

(If adding `Target({TargetKind.library})` doesn't cause a warning, that's another example of special casing, because the annotation here is not on a library, it is on an import declaration. Marking `TestOn` as a library annotation would make a good hook for a quick-fix to introduce a library declaration for the annotation, and then make it a warning to keep the annotation on the import.)

I don't blame our users for thinking `@TestOn` works as documented. I do blame almost every choice leading up to this failure, including not [introducing `library;`](https://github.com/dart-lang/language/issues/1073) much earlier, like at the same time as metadata.

(I've long been aware that *something* was treating metadata on the first import as library metadata, but I didn't actually know *what*. I used to think it was DartDoc, but found out it wasn't. At least I've found out now.)

**Comment by DanTup** [comment]
@natebosch

> Conceptually yes. But the test runner has always had a hack where it could be applied on an import instead.

My understanding is that analyzer also knows about this, so you could still have `Target({TargetKind.library})` on the annotation today without causing any warnings when it's on the first import:

https://github.com/dart-lang/sdk/blob/f2b5ba82ab156b11ad4d2467b72c09b0eac8fa8f/pkg/analyzer/lib/src/error/best_practices_verifier.dart#L1687-L1689

If that's accurate, I think we could add the `Target` annotation now (before any language change) and resolve this issue?

**Comment by natebosch** [comment]
> My understanding is that analyzer also knows about this

Hmm, apparently [I used to know that too...](https://github.com/dart-lang/test/pull/1345#issuecomment-694962508)

I don't see any comment in the PR about why `TestOn` was not changed, and the description looks like I intended to do this for all the annotations. I must have missed this one...


https://github.com/dart-lang/test/pull/1704

**Comment by natebosch** [comment]
FWIW I do think that an explicit `library;` is a better solution than this hack, but given that the hack already exists in both test runner and analyzer/meta I'm happy to use it.

**Comment by DanTup** [comment]
Yep, I agree - but it's nice to have this fixed with the current "behaviour" in the meantime :-)

> https://github.com/dart-lang/test/pull/1704

Awesome, thanks!

**Comment by DanTup** [comment]
I checked that with the change above, Tim's example now works:

![May-24-2022 10-08-18](https://user-images.githubusercontent.com/1078012/169995178-4ebc9086-8b1b-4ffd-b8a6-cab7fc2f25b4.gif)

@timsneath the fix won't show up until you're on a future version of `package:test` (1.21.2).

Presumably if `library;` is added (and required for library-level annotations) in future, we could have a `dart fix` that inserts `library;` after any existing library-level annotations that are on directives.
