### ISSUE TITLE
Weak `RawReceivePort`s

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/sdk#49083]
The following simple console app will hang:
```dart
import 'dart:isolate';

void main(List<String> arguments) {
  final r = ReceivePort();
  print('hang');
}
```
because I don't call `r.close()`.

If you are creating a library for others to consume this is annoying, that you need the user to do an explicit cleanup call.

I have tried using the new `WeakReference` and `Finalizers` from Dart 2.17 like this:
```dart
import 'dart:isolate';

final _resourceFinalizer = Finalizer<ReceivePort>((p) {
  print('close');
  p.close();
});

class Resource {
  final port = ReceivePort();
  Resource() {
    _resourceFinalizer.attach(this, port);
  }
}

final resource = WeakReference(Resource());

void main(List<String> arguments) {
  final r = resource.target;
  print('end of main');
}
```

This works fine if I run with `dart run`, but if I compile and run the exe it hangs.

Can I do something to avoid this?

I'm using dart 2.17.1.

**Comment by mraleph** [comment]
> Can I do something to avoid this?

I don't think you can. Currently the only way to reliably close a port is to call its `close` method.  

You can't rely on finalizers for this because there is no guarantee that a finaliser will ever run - GC needs to happen for that and there is no reliable way to trigger GC from user code. 

Also doing `WeakReference(Resource())` is not much different from just not storing it in the global variable at all. The reference will just get cleared on the first GC if nothing else refers to `Resource`.

Do you have some specific example of what you are trying to achieve with ports, maybe we can offer some alternative solution?

**Comment by nielsenko** [comment]
The port is used for handling async callbacks from native code. A slightly more realistic (and longer) example is this, where. There are no callback in this example, and it just calls malloc/free, but it shows the structure better. Note the use of `addOnExitListener`, but that doesn't fly either.
```dart
import 'dart:ffi';
import 'dart:isolate';

final lib = DynamicLibrary.process();

typedef MallocNative = Pointer Function(IntPtr);
typedef Malloc = Pointer Function(int);
final malloc = lib.lookupFunction<MallocNative, Malloc>('malloc');

typedef FreeNative = Void Function(Pointer<Void>);
final freeNative = lib.lookup<NativeFunction<FreeNative>>('free');

final _resourceFinalizer = Finalizer<ReceivePort>((p) {
  print('close');
  p.close();
});

final tombStone = 'die';

class Resource implements Finalizable {
  final _native = NativeFinalizer(freeNative);
  final _port = ReceivePort();
  late final Pointer<Int8> _pointer;

  Resource() {
    _resourceFinalizer.attach(this, _port, detach: this);
    final size = 1000;
    _pointer = malloc(size).cast<Int8>();
    _native.attach(this, _pointer.cast());

    _port.listen((message) {
      if (message == tombStone) stop();
      print(message);
    });

    Isolate.current.addOnExitListener(_port.sendPort, response: tombStone); // never raised
  }

  void stop() {
    print('stop ');
    _resourceFinalizer.detach(this);
    _port.close();
  }
}

final resource = WeakReference(Resource());

void main(List<String> arguments) {
  {
    final r = resource.target;
    print('end of main');
  }
}
```

**Comment by mraleph** [comment]
> The port is used for handling async callbacks from native code.

Thanks! I guess the best solution you could have currently is to only open a port if you are expecting some message from an asynchronous callback and close it when you have received the message. If you want to facilitate port reuse you can keep the port open for N ms between calls, if no calls are done in those N ms then you close it. 

But I agree that this might be suboptimal - maybe we can allow creating ports which don't keep an isolate alive if they are open, e.g. `ReceivePort(weak: true)` or something like that. 

/cc @dcharkes @lrhn @mkustermann for opinion.

**Comment by dcharkes** [comment]
> But I agree that this might be suboptimal - maybe we can allow creating ports which don't keep an isolate alive if they are open, e.g. `ReceivePort(weak: true)` or something like that.

This can be implemented with

```dart
  // Set this port as active or inactive in the VM. If inactive, this port
  // will not be considered live even if it hasn't been explicitly closed.
  // TODO(bkonyi): determine if we want to expose this as an option through
  // RawReceivePort.
  @pragma("vm:external-name", "RawReceivePortImpl_setActive")
  external _setActive(bool active);
```

https://github.com/dart-lang/sdk/blob/main/sdk/lib/_internal/vm/lib/isolate_patch.dart#L201-L206

cc @bkonyi looks like we have a use case now for your todo.

**Comment by lrhn** [comment]
The `setActive` approach is interesting. I'd probably name it differently (maybe `keepAlive`).

I've suggested it as a constructor parameter before, but there might be a use-case for changing your opinion later.

(Not absolutely sure, though. Either you expect someone to send you events, in which case you should stay alive, or you don't, in which case you might as well close the port. Having a port which *may or may not* go away does not have good usability for the code trying to send messages to it. Not sure what the use-case is for a port that doesn't know if someone will send it messages, and is willing to shut down before finding out. That only really works in the main isolate, which takes down the entire program when it dies anyway, but that's a tricky design too. We may want to allow other isolates to keep the program alive too.)

**Comment by dcharkes** [comment]
> but there might be a use-case for changing your opinion later.

The only place where this is used internally is for timers. For those, the port is set to active when when a timer is active, and inactive when there are no timers active. This is an optimization to prevent having to re-create the port every time a timer is created while no other timers are active. I'd imagine there are more use cases like this.

> That only really works in the main isolate, which takes down the entire program when it dies anyway, but that's a tricky design too. 

In an initial implementation of finalizers I also used inactive ports. But there the contract is explicitly that the finalizers did not run after isolate shutdown. This is a second kind of use case, which delegates the trickiness to the users by putting it in the contract. Note that this was on a per isolate-group basis.

>> If you are creating a library for others to consume this is annoying, that you need the user to do an explicit cleanup call.
>
> I guess the best solution you could have currently is to only open a port if you are expecting some message from an asynchronous callback and close it when you have received the message.

@nielsenko that would be the same use case as the first one with the timer, basically avoiding having to re-create ports as @mraleph suggested.

Is this your use case? Or is it unknown whether any callbacks will come in your use case?

**Comment by blagoev** [comment]
@lrhn 
The case can be generalized as this:
As library developers we need to open a port so native code can send streaming messages. It is the library user who decides about when to stop receiving messages by managing our objects and the program lifetime. 
* If they decide to drop the object but still keep the program running then GC will kick in and we currently have the possibility to close the port. To us this means the library user is no longer interested in receiving the messages from native code. 
* If they decide to exit the program by returning from the `main` method while still holding our objects alive. Then it means they are again not interested in receiving any messages. But unfortunately we don't have a way to comply and close the port. So the program hangs. 

Note: this should work for any isolate `main` or `"secondary"`. 
If you later decide that any active isolate will keep the program running then its fine cause it won't prevent other Isolates from being torn down by an open port.

**Comment by lrhn** [comment]
@blagoev 
This sounds like a problem that can be solved with the operations already on the table.

It should indeed be possible to use a finalizer to detect when some wrapper object is no longer retained, and close the wrapped port then. Just need to be careful that the port callback doesn't reference the wrapper object itself, because then the port itself will keep the wrapper alive.

The "exiting from `main`" is more problematic, because in an async program, exiting from `main` means nothing. That's when the program *starts*. 
More likely what you mean is that when the isolate is "spent": no scheduled events in the queues, no timers or open I/O which may trigger new events, and *no open receive ports*, and it'd usually to close down. You want that to happen even if this particular receive port is still open.
The `_setActive` operation above seems to do just that: Make the receive port not count towards keeping the isolate alive.

That also means that you get no chance to react to this, to tell the native code to stop sending events on the now defunct port. A native finalizer may be able to handle that.

**Comment by blagoev** [comment]
Yes indeed if the `_setActive` flags if exposed and available, it will work for us since we won't need to take any action in these cases. 

Cheers

**Comment by mraleph** [comment]
@lrhn 

> It should indeed be possible to use a finalizer to detect when some wrapper object is no longer retained, and close the wrapped port then. 

I don't think finalizers are really suitable for this for multiple reasons:

1. there is no guarantee that GC happens at a specific pace (or ever). So you can't really depend on it for termination.
2. If you keep a strong reference to a port it will never be collected, if you keep a weak reference to a port it will be prematurely be collected (and thus closed). 

I think we should move forward and expose some functionality on make non-"keep alive" ports.

**Comment by nielsenko** [comment]
@mraleph That would. be perfect for our use-case.

**Comment by mkustermann** [comment]
> This won't really work for us, since we don't know when the last callback from native will occur (we are basically streaming). If the user doesn't cleanup explicitly we will miss the opportunity to close the port(s), and hang.
For now we have an explicit function the user should call on exit to ensure we close the necessary port(s).

@nielsenko If the user doesn't explicitly cleanup, the C part isn't told to be done, so it keeps being active. Doesn't that create a leak (if the process stays alive) or unclean shutdown (if the process terminates)?

**Comment by dcharkes** [comment]
> The "don't keep isolate alive" option is for ports that people keep holding onto until the very end, even if nothing else is ever going to happen. That's the second item.

So, should we expose the non-"keep isolate alive" ports?

As for API design: Unfortunately we can't use an optional named argument for the default constructor, because it has an optional positional argument already:

```dart
abstract class ReceivePort implements Stream<dynamic> {
  /// Opens a long-lived port for receiving messages.
  ///
  /// A [ReceivePort] is a non-broadcast stream. This means that it buffers
  /// incoming messages until a listener is registered. Only one listener can
  /// receive messages. See [Stream.asBroadcastStream] for transforming the port
  /// to a broadcast stream.
  ///
  /// The optional `debugName` parameter can be set to associate a name with
  /// this port that can be displayed in tooling.
  ///
  /// A receive port is closed by canceling its subscription.
  external factory ReceivePort([String debugName = '']);
```

It would be a breaking change to change the `debugName` optional positional argument to an optional named argument.
(Or maybe it's a breaking change that we should consider?)

We could introduce a new constructor.

```dart
abstract class ReceivePort implements Stream<dynamic> {
  /// Opens a long-lived port for receiving messages.
  ///
  /// A [ReceivePort] is a non-broadcast stream. This means that it buffers
  /// incoming messages until a listener is registered. Only one listener can
  /// receive messages. See [Stream.asBroadcastStream] for transforming the port
  /// to a broadcast stream.
  ///
  /// The optional [debugName] parameter can be set to associate a name with
  /// this port that can be displayed in tooling.
  ///
  /// A receive port is closed by canceling its subscription.
  external factory ReceivePort([String debugName = '']);

  /// Opens a long-lived port for receiving messages.
  ///
  /// A [ReceivePort] is a non-broadcast stream. This means that it buffers
  /// incoming messages until a listener is registered. Only one listener can
  /// receive messages. See [Stream.asBroadcastStream] for transforming the port
  /// to a broadcast stream.
  ///
  /// The optional [debugName] parameter can be set to associate a name with
  /// this port that can be displayed in tooling.
  ///
  /// If [keepIsolateAlive] is true, this port will prevent the isolate it belongs to
  /// from exiting while the port is open.
  ///
  /// A receive port is closed by canceling its subscription.
  external factory ReceivePort.v2({String debugName = '', bool keepIsolateAlive = true});
}
```

And should we also consider adding a setter that can toggle between the two modes?

```dart
abstract class ReceivePort implements Stream<dynamic> {
  // ..

  /// If [keepIsolateAlive] is true, this port will prevent the isolate it belongs to
  /// from exiting while the port is open.
  external bool keepIsolateAlive;
}
```

Some API design questions:

* Should we introduce a constructor related to "isolate-keep-alive" such as `ReceivePort.dontKeepIsolateAlive(...)` or a new neutral one which we can add arbitrary named arguments to such as `v2`?
  * If `v2`, should we deprecate the old one?
* Do we want to expose a getter/setter?
* What should the property/constructor name be? `keepIsolateAlive`, `keepsIsolateAlive`, or phrased oppositely: `weak`? Any suggestions?

@lrhn @mraleph @mit-mit any input would be appreciated! 🙏 

Also cc @bkonyi. Any particular reason you wanted to expose this on `RawReceivePort` rather than `ReceivePort`?

https://github.com/dart-lang/sdk/blob/e45a1b362addddd5943d76d2f0281cacc7a3c123/sdk/lib/_internal/vm/lib/isolate_patch.dart#L203-L204

**Comment by dcharkes** [comment]
> > This won't really work for us, since we don't know when the last callback from native will occur (we are basically streaming). If the user doesn't cleanup explicitly we will miss the opportunity to close the port(s), and hang.
> > For now we have an explicit function the user should call on exit to ensure we close the necessary port(s).
> 
> @nielsenko If the user doesn't explicitly cleanup, the C part isn't told to be done, so it keeps being active. Doesn't that create a leak (if the process stays alive) or unclean shutdown (if the process terminates)?

Wouldn't that be done with a `NativeFinalizer` then?

**Comment by blagoev** [comment]
Yes the `NativeFinalizer` will help in this case.

**Comment by mkustermann** [comment]
> Wouldn't that be done with a NativeFinalizer then?

For process shutdown a native finalizer would be guaranteed to be run. But just because the isolate died doesn't mean that GC runs anytime soon (the object is most likely in old space and it can take a very long time until old space GC runs)

**Comment by mkustermann** [comment]
Maybe non-active ports may be ok in this situation, but one should be very cognizant of what it implies. In many cases such a mechanism may be misused and may lead to problems.

It's generally problematic to rely on GC freeing up resources, especially if the GC doesn't have context how important it is to do so. Here's an example: Opening a file or a socket in Dart creates only small objects, if they get moved to old space, many, many may need to accumulate before they are collected. But operating systems have limit on max number of open file descriptors (e.g. iirc macos has a default limit of 256). So by relying on the GC one may be unable to open new files / sockets (application will suddenly get exceptions) just because old space GC hasn't run yet.

Given that, it's generally much better to surface this issue somehow, so application developers are made aware of the problem and can free up resources eagerly at the point when they're not needed anymore.

One could argue if not calling `shutdown()` is as good as calling it, then maybe the method shouldn't even exist in the first place, and if they are not equally good, the developer should be made aware of issues where `shutdown()` isn't called?

**Comment by nielsenko** [comment]
@mkustermann `Realm.shutdown` exists only to call `close` on the port. It serves no other purpose. No realm specific cleanup hinges on this. All native realm resources a guaranteed to be released using `NativeFinalizer`s. To us the port can just go way when the isolates shuts down,.

**Comment by nielsenko** [comment]
@dcharkes For us it would be enough to just expose on `RawReceivePort`. Perhaps a new `RawReceivePort.weak` ctor?

**Comment by Joao-Peterson** [comment]
the dart sdk ffi functionality is great, but for async stuff its kinda raw, and since there is not much demand for pretty functionality right now, its simple and best just to expose `_setActive` as a setter in `RawReceivePort`, i think everyone should be happy with that

With this we should be able to create wrapper libraries for native code with async functionality just right, `NativeFinalizer` and `RawReceivePort` would suffice, in my opinion.

**Comment by dcharkes** [comment]
> The port is used for handling async callbacks from native code

We have just landed support for async callbacks (13ec07415b17e8d2da94d0fd7e6df7f216f40d0d). These should not keep the isolate alive (implementation detail: it uses raw receive ports). @liamappelbe could give more details. We'd prefer using async callbacks over ports going forward. You could give it a spin and see if it works for your use case.

**Comment by liamappelbe** [comment]
> These should not keep the isolate alive

Actually the async callback ports do keep the isolate alive, and the `NativeCallable.close()` method must be called to allow the isolate to shut down. They're basically just a nicer interface for what these users are already doing.

I think it makes sense to expose `_setActive` (with a better name) on both `RawReceivePort` and `NativeCallable`.

**Comment by liamappelbe** [comment]
I need this to make async callbacks ergonomic for ObjC use cases, so I'll start working on it.

**Comment by liamappelbe** [comment]
@lrhn I'm adding a `void set keepAlive(bool value)` method to `RawReceivePort`, and I want to use this for async callbacks too. Now that we're using the unified [`NativeCallable` API](https://github.com/dart-lang/sdk/blob/main/sdk/lib/ffi/ffi.dart#L165) for async callbacks, it might be weird to put the `keepAlive` setter on `NativeCallable`, since we'll be adding sync callbacks to this API soon, and the flag won't make sense for them. I see 2 options:

1. Make `NativeCallable` an interface, implemented by a `NativeListener` class that contains the `keepAlive` method.
2. Just add a `keepAlive` flag to the `NativeCallable.listener` constructor. The user won't be able to adjust this value after construction.

**Comment by lrhn** [comment]
I can see uses for this, including being able to set the bit at any time.

I'd consider only adding it to `RawReceivePort`, not `ReceivePort`, since it's such a low-level functionality (and `ReceivePort` already implements `Stream` so its API is cramped enough). 
If you need to make a `ReceivePort` not keep the isolate alive, you can create a `RawReceivePort`, keep it around for setting the flag, and create the `ReceivePort` using [`ReceivePort.fromRawReceivePort`](https://api.dart.dev/stable/3.0.5/dart-isolate/ReceivePort/ReceivePort.fromRawReceivePort.html).
Maybe that's just me thinking like that, because I never create a `ReceivePort` at all. `RawReceivePort` all the way!

We can add a parameter to the constructor, but `RawReceivePort([void Function(Object?) handler])` has the same problem as `ReceivePort([String? debugName])`, it would be an optional positional boolean parameter (already bad), stuffed in after another parameter that nobody uses.

I'd probably just go with a default of `true`, no constructor paramter, and have you do `RawReceivePort()..keepAlive = false` if you want that. Or finally implement https://github.com/dart-lang/language/issues/1076 :grin:.

Gor the name, `keepAlive` suggests it's the port being kept alive, not the isolate.
Can use `keepIsolateAlive` instead? (The type is in `dart:isolate`, so it's OK to mention isolates.)


Now, `NativeCallable` using the same API would get the benefit of familiarity. They won't have any common supertype, but if the `NativeCallable.keepIsolateAlive` forwards to a port's similar feature, it's easy to explain.

But putting it on a `NativeCallback` which doesn't actually *keep* the isolate alive, might be confusing.
At that point, the name should perhaps be loosened to `NativeCallback.allowKeepingIsolateAlive`. It's is long, but would suggest that it doesn't *force* keeping the isolate alive, whereas setting it to `false` would definitely state that the callback is not allowed to keep the isolate alive.
Having a different name than `RawReceivePort` makes sense, when not all `NativeCallback`s *can* keep the isolate alive, but a `RawReceivePort` always can.

Leaning towards the last idea, with no `NativeListener` to muddle the story.

**Comment by lrhn** [comment]
Here's a use-case:

I create a "task executer" class. Internally I spin up a worker isolate (or more), with bi-directional ports allowing communication in both directions. 
The remote isolates are set to track the main isolate exit, and close down if the main isolate exits. The executor also gets notified if a worker isolate dies unexpectedly, so it can create a new one.
The main isolate uses a finalizer to decide when the "task executer" object is no longer needed, and shuts down its isolates and ports when that happens.

I'd still want to set my ports to "don't keep isolate alive" while no tasks are running. When a task is started, I set my response port to "keep alive" until I get the result, then turn it off again afterwards.

That way, the local code cannot detect (and don't need to care) that my execution happens in another isolate. While a task is running, it's as if the current isolate is running code, and it won't die until the result comes back.
When the executor is not running any tasks, it is as if it is, well, not running, and the isolate can just die from lack of things to do.

I can obviously hack my way around this -- just use non-keep-alive ports for waiting for responses, then create a new keep-alive port while a task is running, and close it afterwards. Effectively I'll create a new port *just* to keep the isolate alive (not new, I've done that before). But it would be easier if I didn't need that.

Maybe we just need an `Isolate.keepAlive()` method returning an object with a `close()` method, which does nothing except keep the isolate alive until someone calls `close`. Or until there are *no* open ports left, and nothing to do.

**Comment by liamappelbe** [comment]
> At that point, the name should perhaps be loosened to `NativeCallback.allowKeepingIsolateAlive`. It's is long, but would suggest that it doesn't *force* keeping the isolate alive, whereas setting it to `false` would definitely state that the callback is not allowed to keep the isolate alive.

How about `NativeCallback.mayKeepIsolateAlive`? Same implications, but shorter.
