### ISSUE TITLE
Wrong imports in Stateless Widget snippet from analysis server

### ISSUE THREAD

**Issue by nickmeinhold** [dart-lang/sdk#49081]
In VS Code when using the `stlss` snippet:

![Screen Shot 2022-05-23 at 19 01 49](https://user-images.githubusercontent.com/1059276/169785136-9a8f4535-750d-480c-89a2-d57e5d4d4241.png)

The resulting code has the imports included:

![Screen Shot 2022-05-23 at 19 02 04](https://user-images.githubusercontent.com/1059276/169785173-c290ba1d-c1cd-437f-a95b-69feb756e6a2.png)

For me these are the wrong imports and I have to go up and delete them and then add the correct imports.

I discussed with @DanTup on the VS Code Discord and he thought this is a bug with how the server decides which imports to add. 

Thanks!

* Dart SDK Version 2.17.1 (stable) on "macos_arm64"

**Comment by bwilkerson** [comment]
The problem is that the analysis server doesn't currently have any support for keeping track of which public libraries export symbols declared in internal libraries. The `dartdoc` package has support for this, but the code isn't currently in a form that can efficiently be shared, nor does it deal with changes to the code (rightly so because it's a command-line tool rather than a long lived server).

Although we could special case this support for snippets, we need this information in lots of other places so I'd really prefer to just solve the problem once (most likely via `DartEditBuilder`) and share the solution across all of the features that need it.

It's possible that we could compute the information efficiently enough that we wouldn't need to cache anything (we should only need to look at the public libraries in a package, and there often aren't very many of those). That would be idea. Otherwise we'll need a cache and a reliable way of determining when the cache needs to be flushed.

**Comment by fahami** [comment]
any progress for this issue?

**Comment by bwilkerson** [comment]
Not that I'm aware of.

**Comment by Samleet** [comment]
@DanTup This is a  still a major issue. as it slows developing time. I'm really looking forward to this update.

**Comment by Blayneliu** [comment]
I'm new to Flutter, but I found this issue annoying as this pops up every time when creating widget in new file. One workaround I'm aware of right now is using some 3rd party snippet extension (more [details](https://stackoverflow.com/questions/73895414/how-to-automatically-add-material-dart-when-creating-new-stateless-or-stateful-c)), in case helpful.

**Comment by Technorocker** [comment]
This is still doing this in vscode, is there a way to manually go change the snippet file to change the imports to material, very annoying when its the first snippet to show up in the context menu all the time

**Comment by DanTup** [comment]
There's no file you can modify as the imports don't come from a file but are inserted automatically by the Dart analysis server when references to types are added by the snippet.

This issue has been fixed, but the fix has not yet shipped in a stable release of Flutter. It is available on the Flutter `beta` channel and will be included in the next stable release.
