### ISSUE TITLE
VSCode debugger not halting on the initialization/usage of late variables declared inside main()

### ISSUE THREAD

**Issue by th0rgall** [dart-lang/sdk#49120]
## Steps to reproduce

Reproduction repo: https://github.com/th0rgall/dart-test-issue

I used `dart create` to create a simple demo project, and [added a few lines to the default test file](https://github.com/th0rgall/dart-test-issue/commit/458ce654b2fbfaebcc0b1d97b3fb63721524338f).

Code execution doesn't seem to halt on breakpoints which are set on lines where a `late` variable is used.

These two videos illustrate the issue as it appears to me:

### Video 1, scenario 1
https://user-images.githubusercontent.com/11543641/170241764-cfe09cae-5581-4c3c-8eaa-2ef184bdede7.mov

In this video, the first breakpoints stops as expected.

However, the execution **doesn't** halt at the second breakpoint: unexpected.

### Video 2, scenario 2

https://user-images.githubusercontent.com/11543641/170241953-06a61a6d-b55c-42c3-94f9-98b29e418442.mov

Here the breakpoints are not placed inside the `test()` function, but inside a `setUp()` function.

The execution halts on the initialization of `a`, as expected.

However, when I set another breakpoint on the initialization of `result`, the execution **doesn't halt**: unexpected.

## Context

Some version info on my machine:
```
dart --version (SDK used by VSCode)
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "macos_x64"

flutter doctor -v excerpt:

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

```

~~I'm not sure if this is an issue with the dart language, with this library, with VSCode, or with the VSCode extensions.~~
See comments below, it is definitely not related to dart:test; and probably related to the dart vm.

**Comment by natebosch** [comment]
It's very unlikely anything in the test runner would cause this - the issue is likely somewhere in the VM.

Have you tried reproducing this behavior with a Dart script that doesn't use `pakage:test`?

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by th0rgall** [comment]
@natebosch I have now. The issue indeed does not seem to be related to `package:test`.

**It seems to occur only with `late` variables defined inside another function**: main().
- the debugger jumps over their initialization: `innerLate = a + b;`
- and over their usage: `assert(innerLate == 3)`

Compare the inner/outer code in this example that does not use `package:test`: https://github.com/th0rgall/dart-test-issue/blob/main/lib/dart_test_issue.dart (still confusingly called dart_test_issue, but I'm not running a test here).

https://user-images.githubusercontent.com/11543641/170827897-8dc7d36b-ad89-425a-8426-2037e1e52b16.mp4

**Comment by bkonyi** [comment]
@alexmarkov I'm guessing we're missing a DebugStepCheck here somewhere?

I've tried looking at the generated code for `calculateInnerLate` with the breakpoint set at `innerLate = a + b` and noticed that we do have a call into `[Stub] UnoptStaticCallBreakpoint` if `a` is not initialized (if I'm reading things correctly):

![image](https://user-images.githubusercontent.com/24210656/230120631-ed3859a1-3c69-46af-9547-063d821ab5b0.png)

When running without a breakpoint at that line, we don't have the same call to `[Stub] UnoptStaticCallBreakpoint`:

![image](https://user-images.githubusercontent.com/24210656/230121486-944e9352-f221-4e83-9f3b-be6c79fef29e.png)

**Comment by alexmarkov** [comment]
@bkonyi Flow graph builder generates `DebugStepCheck` for assignment to a local variable regardless of late (it only looks at the rhs expression):

https://github.com/dart-lang/sdk/blob/ab712b5fd3fa853a3b1a74586b6efce45cffd13a/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#L2146-L2149

Flow graph builder never generates `DebugStepCheck` for reading local variables (again, regardless of late). But it should be covered by a call to `operator ==` after reading the variable.

What you see in the code is a call to `_throwLocalNotInitialized`. It is called in order to throw exception, only if late variable is read before it is initialized, so we're probably not hitting it. When breakpoint is enabled, debugger patches call site to route it to a stub (see `CodeBreakpoint::PatchCode()`), so maybe debugger is confused by `_throwLocalNotInitialized` call and doesn't set breakpoint to the following "real" call to `operator.==` on the same line.

**Comment by derekxu16** [comment]
deduping to https://github.com/dart-lang/sdk/issues/53376
