### ISSUE TITLE
Monorepo suggestion: change the directory structure to follow Flutter recommendations

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#49163]
In order to run Flutter applications using the locally build engine, there are following options available:

`--local-engine-src-path` to specify the path to engine/src directory
`--local-engine` to select the engine mode.

With the current structure of the monorepo you need to specify both. However, Flutter has a nice default for `--local-engine-src-path`: it can be omitted if Flutter engine is checked out to a directory `engine` alongside Flutter framework checkout in `flutter` (also see https://github.com/flutter/flutter/wiki/The-flutter-tool#using-a-locally-built-engine-with-the-flutter-tool).

From https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment:
> Create an empty directory called engine for your copy of the repository and cd into it. (It is possible to use a different name, but some tools assume this name unless configured otherwise, so calling it engine will make thing easier.)

So, if following the steps from https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment, the directory structure would look in the following way:

`engine/src/flutter` - Flutter engine repository.
`flutter/` - Flutter framework repository.

It would be nice to follow this directory structure and avoid the need to specify `--local-engine-src-path`.

**Comment by whesse** [comment]
This can't be done because we use the flutter/engine DEPS as the basis for the monorepo DEPS, with only very few changes, and that DEPS checks out engine and Dart into src/flutter and src/third_party/dart relative to the base of the checkout.

All of the third-party dependencies are checked out into src/third_party, and these paths are hardcoded. They would all
have to be changed to engine/src/third_party.

It would require a significantly changed DEPS file to put them into engine/src/flutter instead of src/flutter. This would add
a lot of complexity to the system, and make the monorepo DEPS very different from the engine DEPS.

I would rather suggest that the default for the flutter tools could be changed from engine/src/flutter to src/flutter, or the tools allow either path.  There is no fundamental reason for the default to include the "engine" directory, and to put the engine checkout there.

**Comment by whesse** [comment]
An issue asking for a way to configure the default local-engine got the response that this should be added to the [HOME]/.flutter_settings created by `flutter config`. https://github.com/flutter/flutter/issues/37929

That would probably be the best way to set a sticky local-engine-src-path as well.
There is a LOCAL_ENGINE_SRC_PATH environment variable used by the integration tests, but they only affect the test scripts, not all the flutter commands.

**Comment by whesse** [comment]
Actually, the help for flutter, `flutter help -v' says that the FLUTTER_ENGINE environment variable can be used to set a default for --local-engine-search-path.  I will test this, and then add it to the instructions.

**Comment by alexmarkov** [comment]
You mentioned that monorepo DEPS is not the same as engine DEPS already. So maybe processing `deps` mapping and substituting `src` with `engine/src` is not so complex change after all.

Re: [HOME]/.flutter_settings and FLUTTER_ENGINE environment variable: these approaches assume that you only have one checkout of the Flutter engine. But it is likely for the developer to have another checkout of the Flutter engine already, or having multiple monorepo checkouts longer term.

**Comment by whesse** [comment]
There is a script that makes the changes, and it is a modified version of the script at
https://github.com/flutter/buildroot/blob/master/tools/dart/create_updated_flutter_deps.py

The modifications to the script are at:
https://dart-review.googlesource.com/c/monorepo/+/243501

It would be a much bigger script if it needs to go through and modify all the paths of dependencies, and we would probably make it a separate script: run the original unmodified script to create the engine DEPS with SDK deps changes rolled in, then process it by a separate monorepo script to make the existing changes and to change all the dependency paths.

I would first want to check if it wouldn't be better to change flutter/engine DEPS to also check everything out into an engine/src directory, since that is what all the flutter tools expect.  Then flutter/engine/DEPS and monorepo/DEPS would remain mostly identical, rather than being mostly different.  We could also add a path variable to engine/DEPS that would default to src/ but could be set to engine/src/ in the monorepo copy - that is what we have done in the past when we need a DEPS file to check out into different relative locations in different contexts.

**Comment by aam** [comment]
> `engine/src/flutter` - Flutter engine repository.
> `flutter/` - Flutter framework repository.

This has always been the standard recommended when working with flutter and engine repos.
I was always puzzled as to why we deviate from that when building hhh patches for example.

**Comment by Tru3boi** [comment]
Help me what I do next

**Comment by athomas** [comment]
@Tru3boi read https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md next. Please don't spam random issues.

@whesse We should stick to the documentation as much as possible: https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment

**Comment by whesse** [comment]
I will change the monorepo structure to put the engine at engine/src/flutter, as suggested here.

**Comment by whesse** [comment]
CLs to make this change to monorepo:
https://dart-review.googlesource.com/c/monorepo/+/247200
https://dart-review.googlesource.com/c/monorepo/+/247201

**Comment by whesse** [comment]
The structure of monorepo, and all documentation and rollers, has been changed to use the new layout with engine/src.
