### ISSUE TITLE
DateTime inconsistency between js and dart

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/sdk#49186]
the following snippet makes 2 dates equal on the web but not when run in a terminal, I assume the js has no micro second information.

```dart
void main() {
  final now = DateTime.now();
  final now2 = DateTime.fromMillisecondsSinceEpoch(now.millisecondsSinceEpoch);
  print(now == now2);
  print(now.isAtSameMomentAs(now2));
  print(now);
  print(now2);
}
```

**Comment by lrhn** [comment]
Correct. When compiled to JavaScript, Dart uses the JavaScript `Date` type to represent `DateTime`, and that does not have microseconds. 

If you want to create a new object with the same time (which you shouldn't need, you can just can use the same object, since it's immutable), use `DateTime.fromMicrosecondsSinceEpoch(now.microsecondsSinceEpoch)`.
Since the API has microseconds, your code should be prepared for them, even if they are sometimes always zero.

The code can also print true on native, but only with a 1:1000 chance (when the microseconds are a multiple of 1000), so being equal is not *wrong*. It's just (much!) more likely to happen on the web.

**Comment by cedvdb** [comment]
For future readers, It can make serialization tests fail 


This works in dartpad but not in terminal: 

```dart
import 'dart:convert';

void main() {
  final house = House(DateTime.now());
  final serialized = house.toJson();
  final deserialized = House.fromJson(serialized);
  print(house.creationDate == deserialized.creationDate);
}

class House {
  final DateTime creationDate;

  House(this.creationDate);

  Map<String, dynamic> toMap() {
    return {
      'creationDate': creationDate.millisecondsSinceEpoch,
    };
  }

  factory House.fromMap(Map<String, dynamic> map) {
    return House(
      DateTime.fromMillisecondsSinceEpoch(map['creationDate']),
    );
  }

  String toJson() => json.encode(toMap());

  factory House.fromJson(String source) => House.fromMap(json.decode(source));
}

```

**Comment by lrhn** [comment]
Agree. Always use `microsecondsSinceEpoch` to represent the precise value as an integer, not the potentially truncated milliseconds.
