### ISSUE TITLE
Uri.parse is not able to parse the string url with a parameter '###'

### ISSUE THREAD

**Issue by vilashraj** [dart-lang/sdk#49187]
String urlStr = 'https://abc.com/pqr?pageSize=20&searchQuery=###';

print(Uri.parse(urlStr)); // Result:  https://abc.com/pqr?pageSize=20&searchQuery=#%23%23

The first '#' is still not converted to %23.

For hands on please try the below link:
https://dartpad.dev/?id=b8cdade1c849680082b49132e5c91b72

**Comment by lrhn** [comment]
This is working as intended. The `#` means something else to `Uri.parse`.

The URI format allows a *fragment* to follow the query. The fragment separator is `#`, so your parsed URI has an empty `searchQuery` and a fragment containing `##`.

If you need your query to contain URI separator characters, you should use one of the constructors instead of `Uri.parse`:
```dart
var uri = Uri.https("abc.com", "pqr", {"pageSize": "20", "searchQuery": "###"});
print(uri);
```
