### ISSUE TITLE
Analyzer resolves elements for `part of` with `_test` and number in name in a strange way

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#49182]
Dart Code Metrics provides a command to check for unused top level declarations and we received pretty interesting report about false positives for part/part of usage https://github.com/dart-code-checker/dart-code-metrics/issues/855

It seems the analyzer resolves elements for the given cases not in the expected way:
<img width="508" alt="Screenshot 2022-06-05 at 21 24 36" src="https://user-images.githubusercontent.com/21116742/172063465-bc18540f-f6c3-4938-bf8b-0adf4bf34f85.png">

Somehow, the declared element and the used element are not equal (but they definitely should be). And I remember seeing that the analyzer considers the `_PartOfTestClassWithNumberInFileName` as an unused declaration too, but I don't remember where it was shown 😞 

The fun part comes next: if I remove `_test` from the file name, then everything works fine.
But then the author of the issue reports that the command starts falling on Linux.

You can find the reproduction here: https://github.com/dart-code-checker/dart-code-metrics/pull/882
If you run the test at `test/src/analyzers/unused_code_analyzer/unused_code_analyzer_test.dart:38` it will fail, but if you just remove `_test` from the `part of` file names, the test will pass.

* Dart SDK Version: 2.17.1
* MacOSX

I'm not sure what additional info could help, the overall behaviour is unexpected.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
Yes, I can reproduce this with the current published version of analyzer. The issue is that a part is considered to be a library, because we did not know the containing library (although with `part of URI` we should know it). So, references for 

This is the area where I'm working now, and with the current version of the analyzer it works, probably with this change: https://dart-review.googlesource.com/c/sdk/+/245225, or https://dart-review.googlesource.com/c/sdk/+/246042, maybe something else - there are a few related changes. Anyway, until is is progressed some more and published, there is not much you could do right now.

One possible work around is to ask `AnalysisSession.getFile()` for every file before doing any analysis, so that libraries linked to their parts.

**Comment by incendial** [comment]
> This is the area where I'm working now, and with the current version of the analyzer it works

Thank you, really happy that it's already been fixed. I think we can wait while the fix will be merged.

> Yes, I can reproduce this with the current published version of analyzer. The issue is that a part is considered to be a library, because we did not know the containing library (although with part of URI we should know it). So, references for

Looks like your answer is cut at the most interesting part for me 😄 . I'm just curious, why naming matters here? Or it's just a coincidence?

**Comment by scheglov** [comment]
I edited my reply.

**Comment by incendial** [comment]
Thank you for the fix, everything now works as expected.
