### ISSUE TITLE
dart analyze can't complete, and memory keeps increasing

### ISSUE THREAD

**Issue by joechan-cq** [dart-lang/sdk#49207]
* Flutter SDK Version 1.22.4
* Dart SDK Version 2.10.4
* MacOSX 11.5.2

I use 'dart analyze' to analyze flutter project, but it hungs：
![image](https://user-images.githubusercontent.com/9456005/172534088-7bfc62d0-0a80-410d-9bb8-5af0267ff45a.png)
and the memory of dart is increasing:
![image](https://user-images.githubusercontent.com/9456005/172534216-9228bdbc-a89c-4798-9866-59db40341e6f.png)

However, use 'dart analyze lib' works.

**Comment by bwilkerson** [comment]
If `dart analyze` hangs, but `dart analyze lib` completes normally, that suggests that there is something outside of `lib` that is exposing the problem. Is this code that you can share with us so that we can attempt to reproduce the problem you're seeing? If not, would you be able to try to narrow down the problem by analyzing other directories and files until you find one that causes this behavior, then look to see if there is some obvious difference between that file and others for which the tool completes?

Unless we can reproduce the behavior we are unlikely to be able to fix it.

**Comment by bwilkerson** [comment]
Assigning p3 until there's a reproduction case.

**Comment by joechan-cq** [comment]
@bwilkerson I have known the reason. It works after I deleted the ios folder.  I used 'fvm' to manager the different versions of flutter. I develop the project with different flutter version on the different branches of the project, so I need to switch the version of flutter occasionally. Maybe, in ios folder, the dependencies is based on flutter 2.5.3, but the whole project depends on 1.22.4, so it hangs while using dart('2.10.3') to analyze the code in ios folder which based on dart('2.14.4').
