### ISSUE TITLE
Add an API entrypoint to trigger a GC event 

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#49320]
While debugging memory leaks it is helpful to trigger GC in order to make sure everything that could be picked up is picked up. There are two cases when it is helpful:

1. We want to analyze only objects that are not picked up.
2. If an object without retaining path is still alive after number of GC events, it means there is a bug somewhere (garbage collector or heap snapshotter or retaining path extractor). 

If it is not possible to guarantee GC, the method should return if the GC actually happened.

See details in [go/request-for-dart-gc-api](https://goto.google.com/request-for-dart-gc-api).

cc @devoncarew

**Comment by osa1** [comment]
Another use case for such an API could be benchmarking.

Currently GC happens unpredictably during benchmark iterations. It might look like this shouldn't be a problem, because if you do N iterations and one did GC, you report total time / N and effectively distribute the GC time to each iteration and include GC pressure of the thing being benchmarked in your report.

But that's only true if you do GC at the end of your last iteration, which I suspect never happens. In other cases GC pressure of the iterations after the last iteration that did GC is ignored in the report.

Secondly, unless the GC is O(heap_size) (for example, it's O(live_size) like in a simple two-space copying, or O(live_size) + O(dead_size) with different constants for mark-sweep) running GC in the middle of a benchmark iteration will have a different cost then running in between two iterations, because the live heap size will be different.

I think the only only way to benchmark accurately in the presence of a GC is by avoiding GC entirely in iterations, and reporting allocation and residency numbers separately.

For that we need an API to trigger a GC so that we can do GC right before benchmark iterations and hope that it won't do GC during benchmark iterations.

We also need a large initial heap, and I don't know if the runtime system provides a way to specify initial heap size. If not, then this may be worked around by allocating a lot of garbage before benchmarking to grow the heap.

Ideally we would also need an API to check GC era (i.e. number of collections done) so that we can make sure we don't include GC costs in benchmarks.

**Comment by polina-c** [comment]
@rmacnak-google , I'd like to clarify that the request was to create separate VM service API, not to enable the application to trigger GC.

Is it something still not planned, taking into account issues mentioned in [go/request-for-dart-gc-api](https://goto.google.com/request-for-dart-gc-api)? I.e.:

[getAllocationProfile](https://pub.dev/documentation/vm_service/latest/vm_service/VmService/getAllocationProfile.html) has the parameter `gc`, however:
1. The documentation states that `if gc is provided and is set to true, a garbage collection will be attempted before collecting allocation information. There is no guarantee that garbage collection will actually be performed.` 
If it is not possible to guarantee GC, could the API method return the failure of the attempt?
2. It is expensive to collect memory profile if just GC event is needed.

The entrypoint is needed for:
1. Manual troubleshooting of the memory issues
2. Continuous memory regression testing

**Comment by kenzieschmoll** [comment]
+1 to this feature request. This would be very useful for tooling. We already do this in a hacky way, so adding an API for us to try to trigger a GC explicitly would just lessen the overhead of the existing workarounds we are using (which include calling `getAllocationProfile` with the parameter `gc` set to true, and another workaround Polina has implemented by aggressively allocating memory and checking that those objects have been GC'd after a delay).

What is the concern or pushback for adding this feature? We are okay with the fact that the GC cannot be guaranteed as long as the request to GC can send back whether or not the request succeeded.

**Comment by polina-c** [comment]
@devoncarew

**Comment by polina-c** [comment]
https://github.com/dart-lang/sdk/pull/49877

**Comment by polina-c** [comment]
It is possible that we might have a new algorithm for GC where it is not possible to force a GC. So, we do not want to make the contract tighter.
