### ISSUE TITLE
VM should use a uintptr_t for external_size

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#49332]
Setting the external size to a value larger than `std::numeric_limits<intptr_t>::max()` will cause an assert to fire in the VM that the value is not `>= 0`: https://github.com/dart-lang/sdk/blob/main/runtime/vm/dart_api_state.h#L227

**Comment by dnfield** [comment]
Alternative: if the VM has a cap on this, maybe it can just clamp internally between 0..max

**Comment by bkonyi** [comment]
IMO this sounds like it's working as intended from the VM's point of view. Do we really want to silently ignore overflow errors?

**Comment by dnfield** [comment]
Perhaps the vm could at least expose the max allowable external size then.

**Comment by bkonyi** [comment]
In this case it's `std::numeric_limits<intptr_t>::max()` which is communicated by the argument type, no?

**Comment by dnfield** [comment]
Ahh I forgot to update the bug. Even using that causes asserts later.

**Comment by dnfield** [comment]
But why accept a signed value if you don't want to accept negative values? :)

I think it would make sense to use:

- `uintptr_t` or `size_t` for this value.
- If `std::numeric_limits<T>::max()` is not acceptable for whatever type, expose a constant in `dart_api.h` that specifies the max allowable value.

**Comment by a-siva** [comment]
In the VM the external_size value for the heap is an intptr_t value and is tracked as external size in words (not bytes).
One option is to change the API to also have this parameter value be external size in words instead of external size in bytes (this could be a pretty intrusive change).

We should also probably report an error when an overflow occurs in the VM when this value is added to cummulative external size tracked by the VM,
