### ISSUE TITLE
Make DateTime parameters named & optional

### ISSUE THREAD

**Issue by M97Chahboun** [dart-lang/sdk#49341]
* Dart core libraries ("dart:async", "dart:io", etc.)

## Proposal
I suggest to make DateTime parameters named & optional and set now as default for use it easy
## Use case
I want use it for convert seconds to seconds, minutes and hours
**Actual**
```
DateTime now = DateTime.now();
DateTime currentDuration = DateTime(now.year, now.month, now.day, 0, 0, secondsForConvertToUnites);
seconds = currentDuration.second;
minutes = currentDuration.minute;
hours = currentDuration.hour;
```
**Suggest**
```
DateTime currentDuration = DateTime(seconds: secondsForConvertToUnites);
seconds = currentDuration.second;
minutes = currentDuration.minute;
hours = currentDuration.hour;
```

I will implement it if you accept this proposal.
Thank you/

**Comment by mraleph** [comment]
This is huge breaking change, so probably is unlikely to be accepted.

/cc @lrhn

**Comment by julemand101** [comment]
You could also say that, for the specified use case, you should not even use `DateTime` since it is used to represent a specific place in a calendar time where the user here is actually trying to convert a duration of time which `Duration` is more fitting for. And `Duration` does have named arguments.

**Comment by M97Chahboun** [comment]
@lrhn
@julemand101 
Thank you for your clarity.
