### ISSUE TITLE
Function annotations showing up in coverage

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#49349]
Dart SDK version: 2.18.0-216.0.dev (dev) (Tue Jun 21 21:30:43 2022 -0700) on "macos_arm64"

Reproduction steps

* Sync down https://github.com/dart-lang/test/ latest (https://github.com/dart-lang/test/commit/bc86a11c3044443406cb1e70dfb891743f900d3b)
* go to `pkgs/checks`
* Activate `package:coverage`
* `dart pub global run coverage:test_with_coverage -f && genhtml -o coverage/html coverage/lcov.info`

Look at the coverage for `src/checks.dart`

![image](https://user-images.githubusercontent.com/17034/176042027-75e27a21-46aa-44df-ba77-fa2a02ee1666.png)

A bunch of places `@override` is listed as a missing line 🤷

**Comment by kevmoo** [comment]
Ugh...deeply unfortunate, @liamappelbe – thanks for investigating!

**Comment by liamappelbe** [comment]
Yep, turns out the token positions are used for some real things, so I if we change where they point it might break something. You'll see the same issue if the return type is too long and ends up on a separate line to the function name. The proper fix would probably be to add an additional token position to the function, which points to the function name, but this would introduce overhead to the serialized functions, so I don't think it's worth it.

**Comment by kevmoo** [comment]
Annoying...but I get it...
