### ISSUE TITLE
Cascade call in first expression in ternary expression can't compile

### ISSUE THREAD

**Issue by julemand101** [dart-lang/sdk#49367]
Issue reproduced with:
```lang-none
DartPad - Based on Flutter 3.0.3 Dart SDK 2.17.5
Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "windows_x64"
Dart SDK version: 2.18.0-216.0.dev (dev) (Tue Jun 21 21:30:43 2022 -0700) on "windows_x64"
```

There seems to be some funky going on in the following example:
```dart
StringBuffer test(StringBuffer sb) {
  return (sb.length > 0) ? sb..write("A") : sb..write("B");
}
```

The program fails with the following:
```lang-none
bin/test4.dart:2:30: Error: Expected ':' before this.
  return (sb.length > 0) ? sb..write("A") : sb..write("B");      
                             ^^
bin/test4.dart:2:30: Error: Expected an identifier, but got '..'.
Try inserting an identifier before '..'.
  return (sb.length > 0) ? sb..write("A") : sb..write("B");      
                             ^^
bin/test4.dart:2:41: Error: Expected ';' after this.
  return (sb.length > 0) ? sb..write("A") : sb..write("B");
                                        ^
bin/test4.dart:2:43: Error: Expected an identifier, but got ':'.
Try inserting an identifier before ':'.
  return (sb.length > 0) ? sb..write("A") : sb..write("B");
                                          ^
bin/test4.dart:2:43: Error: Unexpected token ';'.
  return (sb.length > 0) ? sb..write("A") : sb..write("B");
                                          ^
```

If I instead do the following it works:
```dart
StringBuffer test(StringBuffer sb) {
  return (sb.length > 0) ? sb : sb..write("B");
}
```

But this fails:
```dart
StringBuffer test(StringBuffer sb) {
  return (sb.length > 0) ? sb..write("A") : sb;
}
```

I can also see in my IDE that there are no methods available if I write `..` after the `sb` in the first expression, in the ternary expression, besides what we can call on `dynamic`/`Object`.

**Comment by julemand101** [comment]
So one of my friends played around with this and we discovered that the problem goes away by adding parenthesis around the first expression in the ternary.

But that leads to some unintended runtime behavior:
```dart
StringBuffer test(StringBuffer sb) {
  return (sb.length > 0) ? (sb..write("A")) : sb..write("B");
}

void main() {
  print(test(StringBuffer('Example')));
}
```
Returns:
```lang-none
ExampleAB
```
So both parts of the ternary seems to be executed in the example.

**Comment by eernstg** [comment]
@jensjoha, perhaps you have an opinion about the following?:

The situation in focus here might be described as follows: `..` or `?..` is received as the next token during parsing, but such tokens are not expected at that point. This situation may be hard to detect, because we can write `..` or `?..` in the source code at any point in time whatsoever, and it may be inconvenient to view parsing as an activity where this kind of event can be detected and handled "at any time" (because there is no specific location in the parser where it may occur).

In any case, if it is feasible to detect that type of event, the associated diagnostic message could give a small amount of general advice about cascades. For instance, it could say that they are typically whole expressions rather than subexpressions of other expressions, and in case the latter is desired they should be parenthesized.

**Comment by bwilkerson** [comment]
I would love for recovery to be better in this case. It would be great if we could produce a single diagnostics rather than many because it would allow us to have a better message (though we might be able to improve the message without improving recovery), and possibly allow us to add a fix to add the parentheses in the right place.

**Comment by FMorschel** [comment]
> I would love for recovery to be better in this case. It would be great if we could produce a single diagnostics rather than many because it would allow us to have a better message (though we might be able to improve the message without improving recovery), and possibly allow us to add a fix to add the parentheses in the right place.

I would very much like this.
