### ISSUE TITLE
[analyzer] incorrect occurrences count of `edit.bulkFixes` for `prefer_const_constructors`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#49371]
The below case contains a single lint, however the `dart fix` sees it as two fixes.

```dart
class C {
  const C();
}
void f() {
  var c = C();
  print(c);
}
```

This is because `AddConst` and `ReplaceNewWithConst`, which are the potential fixes, are both configured for `bulk`, one of them is offering the fix, the other is not.

`details.fixes.occurrences` is 2 instead of expected 1.

<details>
<summary>failing test</summary>

```dart
  Future<void> test_count() async {
    newAnalysisOptionsYamlFile(testPackageRootPath, '''
linter:
  rules:
    - prefer_const_constructors
''');

    addTestFile('''
class C {
  const C();
}
void f() {
  var c = C();
  print(c);
}
''');

    var details = await _getBulkFixDetails();
    expect(details, hasLength(1));
    assertContains(details,
        path: testFile.path,
        code: LintNames.prefer_const_constructors,
        count: 1);
  }
```
</details>

**Comment by bwilkerson** [comment]
Thanks for tracking this down! I wasn't aware that `List.hashCode` isn't based on the hashes of the elements. And I'm probably not alone in that.

Sounds like we need to change the generator so that `hashCode` is stable. Basically, anywhere that we're passing a list into `Object.hash` we need to instead pass the elements of the list into `Object.hashAll`. That should make `hashCode` consistent with `==`.

It turns out that the same is true for `Map.hashCode`, so two maps with the same entries will not have the same hash code. It would be good to fix that at the same time.

**Comment by asashour** [comment]
`analyzer_plugin` and `analysis_server` were changed. Please note that LSP uses `lspHashCode` which handles the issue.

PTAL at [sdk/250380](https://dart-review.googlesource.com/c/sdk/+/250380)
