### ISSUE TITLE
Request for proper features for flutter (Issue #6255)

### ISSUE THREAD

**Issue by JulianHSC** [dart-lang/sdk#49425]
1 - No proper documentation to install flutter. I had to check the internet to get everything done.
2 - I sent email to your team and no one bothered answering. The internet solved all my problems. Your email and your team is plain useless.
3 - After removing it from my android studio, I still see android can detect traces of flutter in the plugin. This is bad design.
What did you remove from Android Studio? I do not understand what "I still see android can detect traces of flutter in the plugin" means. Can you elaborate?
4 - I was redirected here after logging a case with the android development team.

**Comment by asashour** [comment]
Please have a look at [code of conduct](https://dart.dev/code-of-conduct).

I assume you mean [IntelliJ Flutter plugin](https://github.com/flutter/flutter-intellij/), not [Flutter](https://github.com/flutter/flutter), both of which have a separate repository different from here.

**Comment by JulianHSC** [comment]
Apologies but I'm not sure if the differences.
________________________________

**Comment by mraleph** [comment]
> 1 - No proper documentation to install flutter. I had to check the internet to get everything done.

The documentation is here: https://docs.flutter.dev/get-started/install

> 2 - I sent email to your team and no one bothered answering. 

Where did you send your mail? It's great to hear that you have found answers by searching around. 

> 3 - After removing it from my android studio, I still see android can detect traces of flutter in the plugin.

What does it mean that "android can detect traces of flutter _in the plugin_"? When asking questions you need to provide as much information as you can, otherwise it is impossible to answer them. You seem to have copied text with someone's asking you the same question without providing the answer to this question. 

> 4 - I was redirected here after logging a case with the android development team.

This is the wrong place. @asashour has pointed you to the right place to file issues against Intellij plugin. But remember that you would need to provide as many details as possible. For example, just saying "X does not work" does not help. You need to describe what you did, what you saw and how it is different from what you have expected to see.

**Comment by JulianHSC** [comment]
Hello Vyacheslav,

I apologize if I sounded discourteous in any way but you can't expect me to stay calm when no one answered my e-mail. My e-mail are as follows so you know what happened. Then perhaps, you can understand what has happened and help improve it. And if you can't, at least get the correct team to do this. You can see the screenshot from android studio. I have already deleted the entire flutter project from my hard disk after installing the plugin but android cannot recognize the absence. So can you please tell me what's happening?


From: Julian Heng
Sent: 30 June 2022 15:50
To: ***@***.*** ***@***.***>
Subject: Request for help to install flutter

Hello team,

After checking the internet a few times, I am getting quite fed up with what I see. I am a completely new to flutter and I'm trying to install in on my Windows 11 system.

The following is the message I persistently receive after installing what I did reading your flutter message carefully. Android was quite easy to install because everything is clearly stated. As for Windows, I had to try both 10 and 11. As for Visual studio and C items, you are so unclear as to what to install. If your email is not available, I have to install a few Gigabytes of information as I don't know what is happening. Check what is showing and what I should have. Do I install both win 10 and 11 if I'm using Windows 11?



D:\androidflutter\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.22000.739], locale en-MY)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for
      the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.






________________________________

**Comment by julemand101** [comment]
@JulianHSC 
> You can see the screenshot from android studio.
It does not seem like your screenshot got correctly uploaded to the GitHub issue. Could you try answer using the GitHub web page instead of answering using E-Mail?

> Check what is showing and what I should have. 
Could you attach some screenshots where we can see what components you got installed from the Visual Studio installer? E.g. if you have installed "Desktop development with C++".

Also, I recommend getting in contact with the Flutter community on e.g. Discord or some of the other communities listed on: https://flutter.dev/community#community-grid . It might be faster to get over problems. Especially as a beginner.

**Comment by julemand101** [comment]
@JulianHSC
I have not closed your issue. It was mraleph that did that. I am just trying to get some clarification about your issue so we could maybe get it solved.

Also, please don't try answer using your E-Mail client. Go instead to the issue at: https://github.com/dart-lang/sdk/issues/49425

And then write your comment where you attach your screenshots. We cannot see the screenshots you are trying to attach to the E-Mails.

For more direct support from the community, I recommend joining r/FlutterDev's Discord server. The link are in the list of Flutter related communities I linked to before: https://flutter.dev/community#community-grid

You can also join "The Unofficial Dart Community" on Discord for more non-Flutter-but-still-Dart related discussions and help: https://discord.gg/Qt6DgfAWWx

I should say that I am only part of the second server since I am not doing any Flutter development. But I have some experience setting up development environments so that is why I asked for some details about your problem since there might be a chance I can help with the issue.
