### ISSUE TITLE
Fill the gap of quick fixes that users expect to have available

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#49446]
A recent survey of Flutter users indicated that many feel that "quick fixes are lacking" for Dart in their IDE.

We need to prioritize quick fixes we can add or improve, and add some and/or improve some.

**TODO**: It is very important to define an exit criteria for this issue (as for any issue). Adding quick fixes, improving existing ones, and evaluating quick fix gaps is an ongoing task. The goal of this issue is to define a sizable but finite set of quick fixes to add/improve in a short period of time before re-evaluating. So we have to define "sizable" and "short." :)

**Comment by jcollins-g** [comment]
https://github.com/dart-lang/sdk/projects/25 This might be a good starting point

**Comment by bwilkerson** [comment]
> ... decide what the correct way to prose a fix is, before start working on it.

My recommendation would be to open a separate issue for each quick fix (not diagnostic). That way the conversations are less likely to be conflated.

> Also, there is list of diagnostics which were evaluated which "needsFix".

I think you're referring to [error_fix_status.yaml](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/error_fix_status.yaml). It's a good place to get a list of diagnostics that don't have fixes, but I found it kind of limiting in that, once a diagnostic has a fix it doesn't really support recording other fixes that could also be written. I think we can re-shape the data to make that easier, but I haven't thought much about what a better format would look like.

> ... was based on the most reported diagnostics ...

As for priorities, frequency of a diagnostic being reported is an interesting signal, remembering that some fixes can be applied to multiple diagnostics.

I think another factor is how much work the fix saves the user. I've long held that a fix to add a semicolon probably is minimally impactful because (a) it's faster to type the character than to open a menu and select an item and (b) it's a parse error, which typically occurs while a user is typing new code and they'll probably type the semicolon before they stop to look at diagnostics anyway.

Yet another factor is the ability of a fix to educate users. Even if the fix is trivial, if it isn't obvious to many users that the fix applies, it still makes sense to display the fix just to teach users that it's a valid approach.

One of the tasks embodies by this task should be to identify and capture some of the factors we use (or should use) to prioritize the work of adding quick fixes.

**Comment by keertip** [comment]
We are tracking this work in a few different places. Closing this issue in preference to the docs that we have in place.

**Comment by srawlins** [comment]
That project is more-or-less defunct, right? I think it's fine to close.
