### ISSUE TITLE
[analyzer] No deprecation message when using named arguments

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#49443]
There are no deprecation warnings when using named arguments.

Consider this code:

```
class Foo {
  Foo({this.someAttribute = false});

  @Deprecated('This attribute is deprecated and should not be used')
  final bool someAttribute;

  void doFoo() {
    print(someAttribute); // lint
  }
}

void main(List<String> arguments) {
  final foo = Foo(someAttribute: false); // no lint here?
}
```

I'd expect `deprecated_member_use` / `deprecated_member_use_from_same_package` lint warnings,
but I get none.

Dart SDK version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "macos_x64"

**Comment by bwilkerson** [comment]
@lrhn What behavior would you expect to see here?

**Comment by lrhn** [comment]
The general rule about deprecation is to give a warning if the code would fail when the deprecated feature is removed.

Then there are some exceptions related to "code in the same \<unit\>" not triggering warnings because it's *probably* going to be removed at the same time as the deprecated thing.
I don't know what those heuristics are, but I trust they are reasonable.

The main thing is that deprecation is not *propagated*, so the variable `final bool someAttribute` being deprecated does *not* mean that the parameter `{this.someAttribute = false}` is deprecated. Only writing `@[dD]eprecated` on the parameter will actually do that. 
It's still quite possible to have a bool parameter after removing `someAttribute`, maybe the intended change is just to make `someAttribute` private, not remove it entirely.

So, we could choose give a warning for the `this.someAttribute` parameter itself, because it defers to the deprecated member, but it's not given that it's correct. If we currently don't, that's a very reasonable choice.

We should *not* give a warning at `Foo(someAttribute: false)` because it does not refer to anything deprecated. The public API does not require that the `someAttribute:` argument refers to the deprecated member, that's an implementation detail inside the class.

**Comment by navaronbracke** [comment]
> So, we could choose give a warning for the this.someAttribute parameter itself, because it defers to the deprecated member, but it's not given that it's correct.

This is probably where I got confused. In what situation would this be incorrect?

**Comment by lrhn** [comment]
The constructor is an "internal use" in the class containing the deprecated member. It's to be expected that there will be such until the member is actually removed. In this case, the deprecated member is a final field. It *must* be initialized.

Giving a warning about initializing the field is not going to be actionable, because you can't *stop* initializing it until the field is actually removed. I don't see any valid rewrite which won't also refer to the deprecated field.
On the other hand, the moment the field *is* removed, the initialized will become an error, so it definitely will be changed at that point. There is no risk of forgetting it.
The constructor reference is, in a way, *tightly coupled* with the deprecated API, so there is no need to warn about it, because there is no risk of forgetting it.
So, not *incorrect*, but still *useless*. Which might count as "incorrect" for a lint warning.

I don't actually know when we choose to warn for internal uses, and when we don't.
The `// lint` comment on the `print` line suggests that we do warn there (I'm assuming `deprecated_member_use_from_same_package`).
We can do the same for the constructor. The question is who we'll be helping, or will we just force the author to write
```dart
// ignore: deprecated_member_use_from_same_package
```

**Comment by navaronbracke** [comment]
I see, thanks for providing more context, now I finally understand the _why_. And yes, there isn't really much that can be done here.
