### ISSUE TITLE
the window onLoad event is not being fired in the DDC compiler only in the dart2Js compiler

### ISSUE THREAD

**Issue by insinfo** [dart-lang/sdk#49448]
the window onLoad event is not being fired in the DDC compiler only in the dart2Js compiler

This tracker is for issues related to:

* dev_compiler

* Dart SDK Version  2.12.4
*  Windows
*  Chrome

```dart
void main() {
  print('hello main');

  window.onLoad.listen((event) {
    print('hello onLoad');
  });
}

```

![image](https://user-images.githubusercontent.com/12227024/178807434-32c0b361-c4dd-4b61-8f14-fd2a8935cde3.png)

![image](https://user-images.githubusercontent.com/12227024/178807489-5a261edf-7082-4000-9f36-0c58e3c81935.png)

**Comment by sigmundch** [comment]
I may be wrong, but I believe this is by design.

The JavaScript code embedded by DDC and dart2js may run at slightly different times - DDC uses a module loader that first installs all code and then asynchronously launches your main, whereas dart2js runs main in the same script tag that installs the application code. The DDC approach likely means that the `load` event fired before we got to start the `main` method.

We can't make DDC start main more eagerly, and it's best not to add a delay to the dart2js generated code to run after the load event. Instead, I'd recommend making the logic more resilient by checking for both the load event and whether the event already happened (e.g. looking at `document.readyState == 'complete'`), which is similar to how one may approach this even when writing directly JavaScript as well.

**Comment by insinfo** [comment]
@sigmundch
does that mean i should do something like this then:

```dart
void main() async {
  var isLoading = true;
  while (isLoading) {
    if (document.readyState != 'loading') {
      print('${document.readyState}');
      isLoading = false;
      onLoad();
    }
  }

  await initializeDateFormatting();
  Intl.defaultLocale = 'pt_BR';
}

Future<void> onLoad() async {
  var rootElement = querySelector('#section');
 print(rootElement );
}

```

**Comment by sigmundch** [comment]
I wouldn't recommend using the busy wait loop, instead adapt to use the event only when the state is not loaded. For example, based on the second answer of this [stack overflow question for JavaScript][1], and example in Dart would be:

```dart

// Action runs when the window is loaded
void action() {
 print("hello is loaded");
}

void main() async {
  if (document.readyState === 'complete') {
    action();
  } else {
    await window.onLoad.first;
    action();
  }
}
```

[1]: https://stackoverflow.com/questions/13364613/how-to-know-if-window-load-event-was-fired-already
