### ISSUE TITLE
Insecure CSP value on any external script even if app builded with --csp flag

### ISSUE THREAD

**Issue by Xyzcancer** [dart-lang/sdk#49456]
* Dart SDK version: 2.17.5 (stable)
* MacOS Monterey 12.4
* Chrome Version 103.0.5060.53 (Official Build) (arm64)

Hello Dart Team

I'm trying to compile a project as Google Chrome Extension. I was able to compile it only from beta channel now and I faced new issue. When I'm trying to upload it in dev mode from build/web folder I see the error:

'content_security_policy.extension_pages': Insecure CSP value "https://*.google.com" in directive 'script-src'.
Could not load manifest.

The command was: flutter build web --web-renderer html --csp

After quick research I found out that any external sources for scripts are forbidden in Manifest V3.

I assume that flutter or dart sdk should download all scripts from project's dependencies to meet Chrome's security standart.

How do you see it?

**Comment by Xyzcancer** [comment]
<img width="690" alt="Screen Shot 2022-07-15 at 12 07 32" src="https://user-images.githubusercontent.com/9575262/179181094-d516c80d-6a65-4859-a9b9-ae3606376760.png">

**Comment by Xyzcancer** [comment]
Thank you, but I saw those article and main difference is they are built with manifest V2 where you can use external scripts. Those errors from main.dart.js file, that generated by dart. So as I understand you suggested to build web app and manually change main.dart.js external scripts on local and download those in web folder. Am I got you right?

**Comment by sigmundch** [comment]
Could you clarify which errors are coming from `main.dart.js`?

In your examples above, I only see errors about trying to load `platform.js` and `firebase-app.js`. Those requests are are not emitted by the dart2js compiler, but come form the logic in the application. For instance, it's possible that those are being requested by a flutter web plugin, in which case it may require fixing how such plugin operates. They would need to be changed so that they allow you to not automatically load JS resources, but instead expect those resources to exist already in the page (e.g. by packaging them together with the rest of the extension resources).

**Comment by Xyzcancer** [comment]
Yes, I get it. I need to file an issue to firebase web plugin or just remove firebase from my project. Thank you for clarification
