### ISSUE TITLE
Enumeration with private members cannot be switched on without ignoring analysis.

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#49485]
I don't know if this is WAI, and maybe the answer is to use enhanced enums, but when working with FFI I have an enum like this:

```dart

// Keep in sync with `enum Foo` from foo.h`
enum Foo {
  a,
  b,
  _c, // unsupported by this library
  _d, // unsupported by this library
  e,
}

void useFoo(Foo value) {
  _nativeUseFoo(value.index);
}
```

If I try to `switch` on that enum in another file, I will get analyzer issues about missing case clauses for `_c` and `_d`, but I cannot switch on those in another file. 

I expected this to work such that the private values would be ignored outside of my `foo.dart` file. I understand I can work around this by using enhanced enums and then ignoring the `index` property on the enum.

**Comment by lrhn** [comment]
That is correct and expected behavior.

The switch is not exhaustive, there exists enum values of that type which are not handled by it. 
That they *cannot* be handled doesn't change that.

I'd recommend using an enhanced enum with a custom field for the IDs, instead of relying on `index`.
That way, switches will be exhaustive for the values that are actually supported, and trying to go from native index to Dart enum won't accidentally do `Foo.values[nativeIndex]` and get `_c`.

**Comment by dnfield** [comment]
Ok. Even without enhanced enums, it's trivial to have a `const Map` that goes from the Dart enum to the native expected value.
