### ISSUE TITLE
Final variable can be assigned several times in a for-in loops

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#49495]
The following programs work in dart and have no issues in analyzer
```dart
main() {
  final i;
  for (i in [1, 2, 3]) {
    print(i);
  }
}
```
And the async version
```dart
main() async {
  final i;
  await for (i in Stream.fromIterable(['one', 'two', 'three'])) {
    print(i);
  }
}
```
Meanwhile Dart [specification](https://spec.dart.dev/DartLangSpecDraft.pdf) reads (18.6.3)

> Let `D` be derived from `< finalConstVarOrType >?`. Execution of a for-in statement, `f`, of the form `await for (D id in e) s` proceeds as follows:
> ... It is a compile-time error if `D` is empty and `id` is a final variable.

There should be a compile time error here.

There is an additional issue in CFE.
```dart
main() async {
  final i;
  for (i in [1, 2, 3]) {
    print(i);
  }
  await for (i in Stream.fromIterable(['one', 'two', 'three'])) { // Analizer error. The final variable 'i' can only be set once. Try making 'i' non-final. • assignment_to_final_local 
    print(i);
  }
}
```
The code above produces an error in analyzer but works well in CFE

Tested on `Dart SDK version: 2.19.0-5.0.dev (dev) (Sat Jul 16 03:26:30 2022 -0700) on "windows_x64"`

**Comment by lrhn** [comment]
With null safety we allowed code like
```dart
  final int i;
  i = 2;
```
That's assignment to a final variable, which is allowed, but only if the variable *definitely unassigned*.

It seems the loop analysis fails to recognize that the loop variable is not definitely unassigned if the loop can run more than once.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/280723 for the analyzer part, please note the error message is not 100% correct.

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/281020 for cfe.

**Comment by chloestefantsova** [comment]
Thanks for the CL, @asashour!

@lrhn, would that be ok if we report the error if a final variable is used as the for-in loop variable regardless of the flow analysis, or should we rather update the flow analysis and allow such variable usage if the loop is executed exactly once, for example?

**Comment by lrhn** [comment]
I think assuming that any loop can run more than once is reasonable.
Otherwise, why make a loop?

We might be able to determined, later, that the body always exits.

I'd personally be happy requiring any value assigned in the for/in-loop header (and plain `for` increment and test) to be be non-final, because we assume the step can be executed (one or multiple times (or even zero, for the increment).
Not sure how to write that requirement. @eernstg?

I guess it's technically possible to do:
```dart
final int x;
// x definitely unassigned here
for (x in [1, 2]) {
  break;
}
// x potentially assigned/unassigned here.
```
but a one-pass analysis must assume that the loop can happen more than once.
And again, why do such a thing?

**Comment by eernstg** [comment]
> I'd personally be happy requiring any value assigned in the for/in-loop header (and plain for increment and test) to be be non-final, 

I guess that would apply only to the "use an existing variable as the iteration variable" variant of a for-in statement. If the variable is _declared_ by the for-in statement itself then it certainly makes sense to let it be final:

```dart
void main() {
  var xs = [1, 2];
  for (final i in xs) print(i); // `final`: The body shouldn't assign to `i`.
}
```

It wouldn't make any difference if the for-in uses a pattern and initializes or assigns any number of variables rather than exactly one variable.

If the rule applies to the non-declaring variant only then I think it's already covered by the current specification: It specifies a particular desugaring which lowers the initialization of the iteration variable in each iteration using a regular assignment in a while loop, which is in turn a compile-time error (because the flow analysis will never make an attempt to prove that any given while loop runs exactly or at most one time).

I know that the use of a desugaring step in a specification is not popular (in the Dart team, some other languages use it all the time). However, we should simply preserve all properties including this one if we rewrite that particular part of the language specification.
