### ISSUE TITLE
Performing multiple HttpClient.getUrl calls to request a file consumes a lot of memory

### ISSUE THREAD

**Issue by cal-g** [dart-lang/sdk#49506]
* Dart SDK Version: 2.17.6
* Platform: MacOS 12.3.1

Doing a simple get request multiple times consumes a lot of memory.  The url points to a 60kB file. I believe this is the correct way to close the HttpClient , however the memory usage does not drop after closing.

```dart
import 'dart:async';
import 'dart:io';

final client = HttpClient();
void main(List<String> arguments) async {
  for (int j = 0; j < 100; j++) {
    await networkRequest();
  }

  Future.delayed(Duration(seconds: 3), () {
    client.close(force: true);
  });
}

Future<void> networkRequest() async {
  final req = await client.getUrl(
      Uri.parse('https://filesamples.com/samples/document/pdf/sample2.pdf'));
  final res = await req.close();
  await res.drain();
}

```
#### Memory before running the requests:

![Screen Shot 2022-07-22 at 10 00 16 AM](https://user-images.githubusercontent.com/98470469/180457854-3e40d146-bfe0-44ae-b191-fbb8330ea32c.png)

#### Memory after completing all the 100 requests:

![Screen Shot 2022-07-22 at 10 01 40 AM](https://user-images.githubusercontent.com/98470469/180457999-846a5226-362a-4400-a52b-29e237cd671a.png)

#### Dart DevTools memory Tab:

<img width="1855" alt="Screen Shot 2022-07-22 at 10 02 05 AM" src="https://user-images.githubusercontent.com/98470469/180458105-41065d9a-2718-4208-bfba-16568c430635.png">

**Comment by julemand101** [comment]
I did a quick memory analysis of the problem and a big chunk of the memory seems to be allocated to handle `_HttpProfileData`:

![image](https://user-images.githubusercontent.com/116227/180487029-a68f8e1e-e460-44f0-aad1-184c5fdda269.png)

Each of these `_HttpProfileData` contains the following, where `responseBody` are the biggest with 1 MB.:

![image](https://user-images.githubusercontent.com/116227/180487217-04a71fa8-4eab-4563-90a8-f5a91be03947.png)

These data are only being recorded because DevTools by defaults enables HTTP network profiling. You can clear the recorded data by going into DevTools and select this button:

![image](https://user-images.githubusercontent.com/116227/180487485-34b060bc-98a1-46b0-908f-af8f695ee439.png)

The button seems to only work if I make your application to now fully stop (which pauses the main isolate if using DevTools) so I added a `Timer` to keep the application alive:
```dart
Timer.periodic(const Duration(seconds: 5), (_) => print('Still Alive!'));
```

When clearing the data, I also forced as garbage collection. After this, I get this graph:

![image](https://user-images.githubusercontent.com/116227/180487971-927aa2f7-a174-4379-b7cf-31844f49c838.png)

After checking with the observatory, I can see that the main isolate is not anymore using the largest about of memory:

**Before:**
![image](https://user-images.githubusercontent.com/116227/180488398-49eb1f47-51cd-4626-a2d3-43d0012b7a14.png)

**After:**
![image](https://user-images.githubusercontent.com/116227/180488590-270e5926-005e-4985-8316-8a466a9d0b25.png)

**Comment by cal-g** [comment]
@julemand101 Thank you, that was helpful to know. I was  forcing garbage collection after the app stopped but now the Timer trick helped. 
Also, should I consider that all the objects (like `_HttpProfileData`) that belong to the **vm_service** are only created during profiling an app ?
 Because it would be difficult to know what is exactly causing a memory increase as I was incorrectly assuming that there was something wrong with dart but all this time it was just the devtools that was causing the memory increase.

**Comment by julemand101** [comment]
@cal-g 
> Also, should I consider that all the objects (like _HttpProfileData) that belong to the vm_service are only created during profiling an app ?

I am not part of the Dart team and cannot say for sure. But based on my own minimal research, I would say this "problem" should only happen if you have started DevTools since it is the part that calls the vm_service method `ext.dart.io.httpEnableTimelineLogging` as part of loading the DevTools. This method is the one which enables the logging and makes the events being kept inside the isolate until asked for cleaning.

> Because it would be difficult to know what is exactly causing a memory increase as I was incorrectly assuming that there was something wrong with dart but all this time it was just the devtools that was causing the memory increase.

Yeah. Not sure what is the best way to handle this. One could say that Network traffic should only be monitored if you are going inside the Network-tab and then enable it (and then have an information box in the memory tab about memory consumption includes network traffic). It does not seem "correct" that the memory consumption of your isolate contains HTTP profiling data since that makes it hard to use the memory analysis for network traffic heavy applications.

But again, I am not part of the Dart team so I am looking forward to hear from the actual developers what their point of view are here. :)

**Comment by bkonyi** [comment]
So this is less of a SDK issue and has more to do with DevTools making the decision to set `HttpClient.enableTimelineLogging = true` by default when connecting to a Dart application. In theory, we can change DevTools to not do this by default (you can always set `HttpClient.enableTimelineLogging = true` at the top of your `main()` if you want to track HTTP requests from the time your program starts) and require users to active opt-in to recording on the Network tab.

Reassigning to @kenzieschmoll as the network profiler is WAI.

**Comment by kenzieschmoll** [comment]
Filed https://github.com/flutter/devtools/issues/4353 to track. I will close this issue in favor of the DevTools issue.
