### ISSUE TITLE
"onDone" is not being called when "Connection reset by peer" on remote host with "cancelOnError: true"

### ISSUE THREAD

**Issue by eximius313** [dart-lang/sdk#49517]
This tracker is for issues related to:
* Dart core libraries ("dart:async", "dart:io", etc.) -> dart:io

In your issue, please include:
* Dart SDK Version (`dart --version`) -> 3.0.1
* Whether you are using Windows, MacOSX, or Linux (if applicable) -> Linux + Windows
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) -> N/A

Having a ServerSocket (`server.dart`):
```server.dart
import 'dart:async';
import 'dart:io';

main() async {
  ServerSocket serverSocket = await ServerSocket.bind(InternetAddress.anyIPv4, 5555);

  // Setup listening.
  serverSocket.listen((Socket socket) async {

    Timer hb = Timer.periodic(Duration(seconds: 5), (_) => socket.add([1]));
    late final StreamSubscription<dynamic> sub;
    sub = socket.listen(
      (message) {
        print('message: $message');
      }, 
      onError: (err) {
        print("socket error: $err");
      },
      onDone: () {
        print("socket done");
        hb.cancel();
        sub.cancel();
      },
      cancelOnError: true,
    ); 
  }, onError: (error) {
    print('server socket error: $error');
  }, onDone: () {
    print('server socket done.');
  }, cancelOnError: true);
}
```

And a client (`client.dart`):
```clint.dart
import 'dart:io';

main() async {
  Socket socket = await Socket.connect("127.0.0.1", 5555);
  socket.listen(
    (event) { 
      print("from server");
    },
    onError: (err) => print("socket err $err"),
    onDone: () {
      print("Socket done!");
      socket.close();
    },
    cancelOnError: true,
  );
}
```

When I run `server.dart` in one Windows' powershell, `client.dart` in another Windows' powersell, and then I hit `Ctrl+C` on the client - then `socket done` is being displayed as expected.

**but**

when I run the `server.dart` on the remote Linux machine, and I run `client.dart` in Windows' powershell (of course IP is no longer `127.0.0.1` but `192.168.X.X`) and I hit Ctrl+C on the client - then:
1. `socket error` is being displayed with `socket error: SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = 0.0.0.0, port = 5555` which is a little bit unexpected (why error instead of `done`?) but let's say we can live with it.
2. But what is even worse - despite `cancelOnError` being `true` and despite the fact that **we caught** the error - onDone is not being called - which I consider as a bug

**Comment by lrhn** [comment]
That's correct and expected behavior. (The "done" event part, at least, I have no opinion on how sockets report exceptional occurrences.)

When you cancel a stream subscription, you won't get any further events, **including "done" events**.
Cancelling is telling the subscription, and the underlying event provider, that you no longer care about events. It can stop processing.
You only get a "done" event when the stream has run to its completion, when the event provider explicitly reports that it's done and can guarantee that it has no further events (typically by calling `StreamController.close`), which it won't do if you cancel it first. (And even if it did, perhaps if it's a broadcasts tream, you already stopped listening for events, so you won't know.)

The `cancelOnError` does just what it says: It automatically calls `cancel` on the subscription when the subscription receives an error event. So, you will not get a "done" event after an error event if you have `cancelOnError` set to true.

**Comment by eximius313** [comment]
Ok, thank you.
