### ISSUE TITLE
[vm] use_dwarf_stack_traces_flag_test failing on simriscv64

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#49519]
There are new test failures on [[dart2wasm] Enable RTI tests for oddball and interface types....Reland "[pkg/native_stack_traces] Support Mach-O dSYM debugging information."](https://github.com/dart-lang/sdk/compare/27f6c6d660ee5115e9ec0975bd3fbacc3d7cf254~...f6f29df4b56cdeae756eb9ddd34df91b72c74ed0).

The tests
```
vm/dart_2/use_dwarf_stack_traces_flag_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-simriscv64
```

log: https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-debug-simriscv64/dartkp-linux-debug-simriscv64/165/vm/dart_2/use_dwarf_stack_traces_flag_test

This is most likely caused by 27f6c6d660ee5115e9ec0975bd3fbacc3d7cf254. cc @sstrickl 

cc @rmacnak-google for if we would need something special for simriscv64.

**Comment by sstrickl** [comment]
Creating https://dart-review.googlesource.com/c/sdk/+/252604 to disable the added assembly part of this test on `SIMRISCV64` the same way it's disabled on `SIMARM`/`SIMARM64`/`SIMARM_X64`, since the trybots are configured to
generate ELF directly instead of through an assembler and so `buildtools` doesn't get downloaded there.

The test does work locally for `SIMARM`/`SIMARM64`/`SIMARM_X64` if the check in `use_dwarf_stack_traces_flag_test.dart` is removed, since`use_flag_test_helper.dart` currently has cases for the ARM simulator architectures that depends on `buildtools`. Thus, I've also adjusted `use_flag_test_helper.dart` for the cases where all the simulator architectures should be the same, but there are more adjustments needed for `SIMRISCV64` where noted by a `TODO`.
