### ISSUE TITLE
Type inference issue.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#49528]
Consider the following example:
```dart
void main() {}

bool any_bool = true;

final foo = () {
  if (any_bool) {
    return 0;
  } else {
    throw Exception();
  }
}();

final int bar = foo;

```

The dart analyzer emits no errors, but the compiler emits the following error:

```
Error: A value of type 'int?' can't be assigned to a variable of type 'int' because 'int?' is nullable and 'int' isn't.
final int bar = foo;
```

It seems to me that either the analyzer should emit an error that says that foo is not an `int` to match the compilers behavior, or this should compile successfully to match the analyzers behavior.

**Comment by eernstg** [comment]
Cf. [this section](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference), I believe the inferred return type of the function literal should be `int`, because the actual return type is `int`, and there is no context type.

Removing the `else` and the block around `throw` does not make a difference, so the issue does not seem to be that the flow analysis thinks the end of the function body can be reached.

@chloestefantsova, WDYT?

**Comment by johnniwinther** [comment]
This has to do with how top level inference is/should be performed (root issue https://github.com/dart-lang/language/issues/1650). If you put `foo` and `bar` inside a method body, then there is no error.

The CFE currently doesn't perform statement level inference during top-level inference. I would have assumed it to infer `dynamic` for `foo`, though.

**Comment by eernstg** [comment]
OK, thanks! It sounds like this issue could be marked as blocked on dart-lang/language#1650 or closed as a duplicate. WDYT, @johnniwinther?

**Comment by johnniwinther** [comment]
Mark it as blocked.
