### ISSUE TITLE
False positive unnecessary cast in firstWhere with orElse

### ISSUE THREAD

**Issue by TadashiCZ** [dart-lang/sdk#49565]
Dart version: Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"

The problem is that this code creates unnecessary cast warning:

```
final RxList<XFile> selectedFiles = <XFile>[].obs;
final XFile? xFile = (selectedFiles as RxList<XFile?>).firstWhere((element) => file.name == element?.name, orElse: () => null);
```

but when using the suggestion it changes code below which is wrong because it cannot return null from the orElse clause.
```
final XFile xFile = (selectedFiles).firstWhere((element) => file.name == element?.name, orElse: () => null);
```

**Comment by lrhn** [comment]
The warning seems unnecessary, but the cast isn't actually *working*, so some warning is warranted.

You have an `RxList<XFile>`, which I assume is *not* an `RxList<XFile?>` (because then you could have written that as the type in the first line.)

The `(selectedFiles as RxList<XFile?>)` cast up-casts to the supertype, relying on unsafe covariance to be valid.
However, the `firstWhere` method is precisely one which is not safe to use covariantly.

When you do:
```dart
final XFile? xFile = (selectedFiles as RxList<XFile?>).firstWhere((element) => file.name == element?.name, orElse: () => null);
```
you pass a `() => null` method as the `orElse` argument to an `RxList<XFile>`, which is going to cause a run-time error. The function passed as `orElse` must return an `XFile`, because that's what `RxList<XFile>` requires (because it's a `List<XFile>`).

The warning you get is not correct (the cast is not unnecessary), but it's correct to give *a* warning here (the use of the cast value is not safe).

**Comment by srawlins** [comment]
`unnecessary_cast` was changed in the last year to only report when an expression is being cast to the _exact same_ type as it's static type.
