### ISSUE TITLE
Provide index to List.map, .where etc.

### ISSUE THREAD

**Issue by Leffe108** [dart-lang/sdk#49589]
# Proposal
I propose that methods like List.map(), List.where() etc. can pass the index to the callback in addition to the value.

Since Dart does not support function overload, I guess it means more methods like
* mapByIndex
* whereByIndex
* ...

# Motivation
In some cases you have supplementary data in a different List that you need to lookup to make your decision. In some cases it is possible to use list.indexOf() inside map/where etc., but only if the list always have unique values. If values are not unique, one can go via asMap(), as demonstrated below, but it becomes quite clunky.

## Today - Dart 2.17.6
```dart
// Data defined somewhere
final list = List<int>.unmodifiable([5, 2, 3]);
final otherData = ['some', 'other', 'data']

// Later we want to get all list entries where their corresponding 
// otherData is 4 letters or shorter.
final newList = list.asMap().entries.where((entry) {
  final i = entry.key;
  return otherData[i].length < 5;
}).map((entry) => entry.value).toList();
```

## If we had `whereByIndex` it could work like this:
```dart
// Data defined somewhere
final list = List<int>.unmodifiable([5, 2, 3]);
final otherData = ['some', 'other', 'data']

// Later we want to get all list entries where their corresponding 
// otherData is 4 letters or shorter.
final newList = list.whereByIndex((index) {
  return otherData[index].length < 5;
}).toList();
```

# Discussion
I am not opposed that `whereByIndex` also supplies the value to the callback although then `byIndex` might not be the correct suffix and but maybe someone has a better idea so both index and value can be included to the callback?

**Comment by julemand101** [comment]
The `package:collection` (maintained by the Dart team) provides a lot of `*Indexed` version of these methods including [`mapIndexed`](https://pub.dev/documentation/collection/latest/collection/IterableExtension/mapIndexed.html) and [`whereIndexed`](https://pub.dev/documentation/collection/latest/collection/IterableExtension/whereIndexed.html). 

I don't personally really see a need for including these in the Dart SDK since `package:collection` are included by default with Flutter and for Dart-only projects, it is easy to include this package if you need this extra functionality on top of existing `Iterable`.

**Comment by Leffe108** [comment]
Oh if that is the case, then I agree that it doesn't really need to be in the language itself. I stand corrected and thank you for pointing out the collection package.

For anyone finding this issue:
1. add `collection` as dependency in pubspec.yaml
2. `import 'package:collection/collection.dart';`

Then you can write

```dart
final list = List<int>.unmodifiable([5, 2, 3]);
final otherData = ['some', 'other', 'data']

final newList = list.whereIndexed((index, element) {
  return otherData[index].length < 5;
}).toList();
```
