### ISSUE TITLE
Question regarding GC behaviour change between Dart 2.17.6 and 2.18

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/sdk#49618]
Assuming you have:
```dart
class A {}

class B {
  final _foo = A();
  final _bar = A();

  void foo() {
    // do something with _foo..
    print(_foo);
  }

  void bar() {
    // do something with _bar..
    print(_bar);
  }
}

void main() {
  final b = B();
  // How early can b._bar be reaped?
  // In 2.18 it seems to be as early as here. Is that correct?
  b.foo(); // <-- touches b._foo, but not b._bar
  // whereas 2.17.6 reaps b._bar together with "the rest of" b here
}
```
Is it correct that 2.17.6 and 2.18 differs in how _aggressive_ they are at reaping `b._bar`?

This is of course just a theoretical example as the GC would probably never run before the call `b.foo()`. The behaviour is not even observable before you start adding native finalizers to the mix.

**Comment by mraleph** [comment]
I think what you are trying to ask when the value of `A._bar` becomes unreachable, because there is no immediate reaping in Dart. In general this depends a lot on which execution mode you are running in and which optimisations happen. 

e.g. in JIT mode `main` will end up running unoptimized and the value of `foo` will be reachable through the whole `main` and consequently so will `_bar`.

If this code is optimised `B()` and `foo` are likely to be inlined and `B()` will disappear and only an object allocated for `_foo` will remain because it leaks into `print`.

In AOT even if `B()` is not-inlined the field `_bar` is eliminated because it is never read consequently the object referenced by `_bar` becomes unreachable immediately after the allocation (and in the code written like presented --- the allocation itself is likely eliminated as well). 

I think what you are asking about is actually this last optimisation which has been there since 2020 (12c8b02c848aeb5fe5731533649319ba43a2e9b4), though it was improved in 2021 (9c190c5e001640238e61ae9511a0dd4b2d94228b).

**Comment by nielsenko** [comment]
@mraleph  Thank you for your clarification.

You are right, I'm asking about unreachability, since reaping is not immediate.

What I also hear you say is, that the behaviour hasn't changed between 2.17.6 and 2.18 in a way that should impact this behaviour, since 2.17.6 was released long after https://github.com/dart-lang/sdk/commit/9c190c5e001640238e61ae9511a0dd4b2d94228b.

The code above is my attempt at distilling an actual issue (/ change in behaviour) I see running https://github.com/realm/realm-dart-samples/tree/kn/time_track_synchronization/time_track under dart 2.18 (from flutter beta) vs 2.17.6 (from flutter stable).

The actual code is in question is not so long, so I'll try to explain it here:
```dart
  Future<void> runWithRealm(Realm realm) async {
    // Get user (should already be logged in)
    final appId = Settings.appId.value;
    final baseUrl = Uri.parse(Settings.baseUrl.value);
    final app = App(AppConfiguration(appId, baseUrl: baseUrl, baseFilePath: basePath));
    final user = app.currentUser!;

    // Swizzle realm
    realm.close();
    final config = Configuration.flexibleSync(user, _schemaObjects, path: path);
    realm = Realm(config); // <-- the realm variable has an implicit ref to the App instance in app via realm.config.user.app

    // Initiate subscriptions
    final subs = realm.subscriptions;
    subs.update((mutableSubscriptions) {
      mutableSubscriptions.add(realm.all<Category>());
      mutableSubscriptions.add(realm.all<Now>());
    });
    await subs.waitForSynchronization();

    // Monitor progress
    final session = realm.syncSession;
    final up = session.getProgressStream(ProgressDirection.upload, ProgressMode.reportIndefinitely);
    final down = session.getProgressStream(ProgressDirection.download, ProgressMode.reportIndefinitely);

    console.clearScreen();

    void trace(String header, SyncProgress progress, int row) {
      if (!verbose) {
        console.cursorPosition = Coordinate(row, 0);
        console.writeAligned('$header: ', 10, TextAlignment.right);
        console.writeAligned('${progress.transferredBytes} / ', 10, TextAlignment.right);
        console.write('${progress.transferableBytes}');
      }
    }

    up.listen((p) => trace('Upload', p, 0));
    down.listen((p) => trace('Download', p, 1));

    // Wait for cancellation
    await ProcessSignal.sigint.watch().first; // Runs until Ctrl-C 
    console.writeLine('Synchronization stopped!');
    realm.close(); // <-- in 2.17.6 this is enough to keep the App instance alive until here, but not in 2.18
```
Note the 3 last lines in particular and the assignment of the `realm` variable.

Despite the fact you can reach the `App` instance via `realm.config.user.app` and the realm instance is kept alive until the `realm.close()` call, then (in dart 2.18) we see the `App` instance being reaped before the close call. `App` is basically a native handle, and we see the native destructor called.

My guess is this happens, because Dart is smart enough to realise that `realm.close` doesn't use the `App` instance, and hence it can be released earlier.

However, in my experience/tests, this changes between 2.17.6 and 2.18.

I guess, what I ultimately is asking, is if this is expected behaviour?

**Comment by mraleph** [comment]
Thanks for the provided code - `async` is the key here. In 2.18 `async` implementation has been redone entirely in a way that changes the liveness of the variables in async functions. Previously most local variables in an `async` function would live for as long as `async` function is active, in the new implementation their liveness follows the liveness of local variables in normal functions - they are considered dead after their last use. (The new implementation is described here: https://github.com/dart-lang/sdk/blob/main/runtime/docs/async.md). 

I think this is ultimately a combination of things: it is likely that `realm.config.user.app` was not keeping the `App` alive to begin with (as fields which are never read are removed by the AOT compiler), but it was kept alive because it was referenced by a local variable in an `async` function.

> I guess, what I ultimately is asking is, if this is expected behaviour?

Yes the behaviour is expected. In general if you need more predictable finalisation behaviour where liveness is syntactical (i.e. an object is kept alive for the duration of the block which declares the variable), then you should mark such class (e.g. `App`) with `Finalizable` interface. See https://api.dart.dev/dev/2.19.0-78.0.dev/dart-ffi/Finalizable-class.html

**Comment by nielsenko** [comment]
@mraleph Thank you so much 🙏 . This answer should help me convince people we **really** need to start using the `Finalizer` interface from 2.17.
