### ISSUE TITLE
Too many extension functions, how much will it affect performance?

### ISSUE THREAD

**Issue by ddxl123** [dart-lang/sdk#49631]

**Comment by eernstg** [comment]
Performance of what? Compilation time, executable size, ...?

**Comment by ddxl123** [comment]
> Performance of what? Compilation time, executable size, ...?

About the apk size and app performance after flutter is packaged into an app.

**Comment by eernstg** [comment]
More code means bigger executable, but it should definitely be possible to eliminate ('tree shake') extension methods from any executable if they are not called (and extension methods are resolved statically, which means that it is one of the easiest kinds of declarations to tree shake).

All other things equal, app performance should be better if much of the work is done in extension methods rather than regular methods, because there is no dispatch step. However, all other things are not equal, because an app which is written in a style that uses a lot of extension methods may (or may not!) have globally worse properties than an app which is written in an OO style. I'd recommend writing code based on software engineering properties (readability, maintainability, evolvability, etc), and then worrying about size/space along the way as needed.

@mkustermann, @sigmundch, perhaps you have a comment on this, too? Is there any reason to be worried about the performance of programs with many extension methods?

**Comment by sigmundch** [comment]
I share your perspective @eernstg - extension methods are like static methods in terms of our ability to analyze them, inline them, tree-shake them, etc. Which gives us opportunities to do a better job for code-size and performance compared to instance methods. That said, I wouldn't simply start using them everywhere just because of that. As you suggest, I'd recommend to design to have the right architecture for the app, and then pay attention to size/space as needed and introduce extension methods as they fit the situation.

**Comment by mkustermann** [comment]
Agree with @eernstg & @sigmundch regarding tree shakability and runtime performance.

Though it may (or may not) affect compile times since a method call target cannot be simply looked up based on the static type, but one needs to know "all available extensions that apply to that static type in that point of the program". @johnniwinther may be able to comment on whether it affects CFE compile-times a lot.

**Comment by johnniwinther** [comment]
We always compute the full export scope, including exported extensions, so there is no specific cost to declaring many extensions. On the call sites, we _do_ have to look up into all extension in scope, but you'd probably have to have thousands of extensions available to make a measurable compile-time impact.

**Comment by eernstg** [comment]
Thanks a lot for all the info! I'll close this issue because no particular action is needed.
