### ISSUE TITLE
Javascripts `JSON.stringify` != `jsonEncode` when running on the VM

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#49686]
Consider the following program compiled for JS:

```dart
import 'dart:convert';

import 'package:js/js.dart';

void main() {
  print(jsonEncode(1.0));
  print(stringify(1.0));
}

@JS('JSON.stringify')
external String stringify(Object obj);
```

Both statements will output a String with a value of `1`.

Now consider the following program compiled for the VM:

```dart
import 'dart:convert';

void main() {
  print(jsonEncode(1.0));
}
```

The statement will output a String with a value of `1.0`.

As you can see, jsonEncode will produce different outputs when targeting JS vs the VM.

I understand that there are differences between how JS and the VM represent numbers, but this still seems very surprising to me. The jsonEncode docs do not mention these differences.

Would it be reasonable for `jsonEncode` to have a way to normalize its output so that it matches the behavior of JS when compiled for the VM?

I've encountered this issue while testing Dart code by comparing its output with output produced by JS code.

**Comment by modulovalue** [comment]
The case where a dart `double` should be serialized to a json value that looks like an integer can be resolved with this:

```dart
  /// JavaScripts JSON.stringify and Darts jsonEncode produce
  /// different results for doubles that can be represented as
  /// integers. You can use this function to transform Dart [double]s
  /// to make jsonEncode act more like JSON.stringify.
  num jsonEncode_doubles_as_integers_fix(
    final double value,
  ) {
    if (value % 1 == 0.0) {
      return value.toInt();
    } else {
      return value;
    }
  }
```

(There are other issues related to truncation that this does not address.)

**Comment by lrhn** [comment]
Working as intended, the behavior is deliberate.

The issue here is that on the web, `1` and `1.0` is the same object. It can only be serialized to one string, and JS `JSON.encode` chose `1`.

The VM can distinguish the integer `1` and double `1.0`, and it chooses (deliberately) to encode them as `1` and `1.0`, because then the *decoder* can parse them back into an `int` and a `double` respectively.
This ensures that Dart JSON-like structures can be round-tripped through JSON text and preserve the type of numbers.

Code which doesn't care about the type of `num` being used can just use `num`, and everything will still work.
