### ISSUE TITLE
[Patterns] VM implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#49755]

**Comment by itsjustkevin** [comment]
Friendly ping @alexmarkov

**Comment by alexmarkov** [comment]
@itsjustkevin We don't have any planned work to do, and currently we don't have any open bugs in the VM related to patterns. However, there is still a significant number of failing tests, seemingly because tests were not updated after the recent spec change (https://github.com/dart-lang/co19/issues/1976). So we're waiting for co19 roll to land in Dart SDK and all VM bots to cycle in order to confirm that all tests now pass (or discover more bugs which could be hidden beyond the existing failures).

**Comment by a-siva** [comment]
Marking this as closed, if we find issues with the new set of co19 tests we can create new issues specific to the failures.
