### ISSUE TITLE
.add ing a list yields a pointer

### ISSUE THREAD

**Issue by vk2o** [dart-lang/sdk#49771]
e.g.
```
void main() {
    var x = [1, 2, 3, 4, 5];
    var i = [];
    var result = [];
    for(var t in x) {
        i.add(t);
        result.add(i);
    }
    print(result);
}
```
yields
```
[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
```
However, integers don't have this problem. e.g.
```
void main() {
    var x = [1,1,1,1,1];
    var i = 0;
    var result = [];
    for(var t in x) {
        i++;
        result.add(i);
    }
    print(result);
}
```
yields
```
[1, 2, 3, 4, 5]
```

**Comment by julemand101** [comment]
You are reusing the same `List` instance.

A variable in Dart is always a reference to an object and everything is really just objects. Some objects might be immutable like `int`  and is designed to always returns a new instance when we do manipulations.

`List`, however, does not return a new `List` instance when we do manipulations to the `List`. So if you are reusing the reference to the same `List` object and then manipulate the `List`, you will observe that all the other lists also changes since they are really just the same `List`.

So you should make sure you are creating a new `List` object as part of your loop if you to prevent this issue: 

```dart
void main() {
  var x = [1, 2, 3, 4, 5];
  var result = <List<int>>[];
  for (var t in x) {
    var i = <int>[];
    i.add(t);
    result.add(i);
  }
  print(result); // [[1], [2], [3], [4], [5]]
}
```

Or make sure you create a copy of your `List` before reusing it. Be aware that if you have objects that is not immutable, you should also consider if you need to make copies of these (e.g. implement some copy constructor).
```dart
void main() {
  var x = [1, 2, 3, 4, 5];
  var i = <int>[];
  var result = <List<int>>[];
  for (var t in x) {
    i.add(t);
    result.add(i.toList());
  }
  print(result); // [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
}
```
