### ISSUE TITLE
Closing the stream controller closes the program

### ISSUE THREAD

**Issue by PlugFox** [dart-lang/sdk#49773]
I got very strange dart behavior with a non-broadcast stream controller.

When I close the non-broadcast controller without subscribing, it closes the program without errors.

I can't even handle any exception in try-catch-finally or zone.

[DartPad example](https://dartpad.dev/?id=26279c2f2e70e9acab7899cd852dc2a6)

```dart
import 'dart:async';

void main() => runZonedGuarded<void>(() async {
      try {
        print('1');
        final controller = StreamController<void>();
        print('2');
        await controller.close();
        print('3'); // ???
      } on Object {
        print('Should be unreachable');
      } finally {
        print('4'); // ???
      }
    }, (error, stackTrace) {
      print('Should be unreacheble');
    });
```

As I understand it, this is due to the fact that while waiting for completion, we have an empty event loop.
And with an empty event loop, the program closes.

Similar behavior:
```dart
await Completer<void>().future;
print('Unreacheble');
```

But with the broadcast stream controller, it works perfectly.

**Comment by PlugFox** [comment]
As I understand it, this is due to the fact that while waiting for completion, we have an empty event loop.
And with an empty event loop, the program closes.

Similar behavior:
```dart
await Completer<void>().future;
print('Unreacheble');
```

**Comment by julemand101** [comment]
Might be the following documented "feature":

> If no one listens to a non-broadcast stream, or the listener pauses and never resumes, the done event will not be sent and this future will never complete.

https://api.dart.dev/stable/2.17.6/dart-async/StreamController/close.html

So in your case, the `Future` returned from `controller.close()` never completes and the `await` will therefore in theory wait "forever". The program closes since there is nothing more to do and there is nothing else in the system (e.g. open RecievePort or Timers) which would be able to solve the "await forever".

**Comment by lrhn** [comment]
Correct. The `done` event completes when the done event has been *delivered*.

Calling `add` ten times and then `close` means that you'll have to wait for all ten data events to be delivered before the done event, and only then is the stream "done".
If the listener pauses before the done event is delivered, you'll have to wait for that. If it never resumes, you'll have to wait forever. There is no other alternative, since the stream controller cannot know whether the user will resume at some point in the future or not. Not until the program has terminated, then it's safe to say that they won't.

Same for a stream which has never been listened to, which is treated as a stream which is paused (events are buffered until a listener wants them).

So, working as intended.
