### ISSUE TITLE
[dart:js] Internal Error: The compiler crashed when compiling this element.

### ISSUE THREAD

**Issue by iapicca** [dart-lang/sdk#49867]
```dart
final notDouble = .2.clamp(0, .1);
void main() => print(notDouble.runtimeType);
```
[dartpad example](https://dartpad.dartlang.org/?id=eb99119e24bf9828d2d4c699bfb61737)

I think it's only with `dart:js` otherwise `notDouble` is a `num` 
#
almost OT
`notDouble` being a `num` is also kinda weird, 
I was expecting `double`, to fix that I just add a dot like... still
```dart
someDouble.clamp(.0, .1);
``` 

```console
Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"
```

**Comment by lrhn** [comment]
On the web, `.0` and `0` is the same value (the JS number `0`). That value implements both `int` and `double` (all integer values do), so its `runtimeType` has to choose, and it chooses `int`.

I expect the dev-compiler will give the same result, whereas the native VM has separate objects for `0` and `0.0`.

That is working as intended.

The `clamp` method is defined on `num`, and it returns `num`. There are special cases in the type inference algorithm for when all three numbers have the same static type (`int` or `double`), then the result also has that static type.
Since you can validly call `someDouble.clamp(0 as int, 1 as int)`, which must have type `num`, there is nothing forcing the `0` to be converted to `0.0`. It is not in a double context, unless you require the output to be a double:
```dart
double d = .2.clamp(0, .1);
```
In this case, the `0` gets put into a context expecting a `double` and is converted to `0.0` (which, on the web, has absolutely no effect).
