### ISSUE TITLE
[Records] Wrong `invalid_field_name ` in analyzer in case when there is no field name collidion

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#49883]
Consider the following code:
```dart
main() {
  (int $0, String) r1 = (42, "x");
  (int, {String $100}) r2 = (0, $100: "y");
  var r3 = ($100: "z");
}
```
`dart analyze --enable-experiment=records test.dart` produces `Record field names can't be a dollar sign followed by digits because those are used to access positional  fields. Try using a different name for the field. • invalid_field_name` for every use of `$0` and `$100`.

But according to the [feature specification](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md#record-type-annotations) it is a compile-time errorr if a record type has:

> A field name that collides with the synthesized getter name of a positional field. For example: `(int, $0: int)` since the named field `$0` collides with the getter for the first positional field.

But the code above has no any collidions. `$0` is an optional name of a positional field which doesn't have any effect. `$100` also have no collision because this record has no positional field with access getter named `$100`. So, there should not be any errors.

cc @eernstg to confirm

`Dart SDK version: 2.19.0-146.0.dev (dev) (Fri Aug 26 18:55:25 2022 -0700) on "windows_x64" `

**Comment by eernstg** [comment]
Yes, this sounds reasonable: I'm thinking that positional fields are by default considered to have the names that are used to get them (`$0`, `$1` and so on). This may give rise to some conflicts, because names like `$0` are specified explicitly and also implicitly induced on nameless positional fields.

If we consider `(int namedExplicitly, {String $0})` then there's no name clash according to the above rule, but it is impossible to distinguish between `myRecord.$0` meaning "get the first positional field" and "get the named field whose name is `$0`". So we will have to declare a conflict in this case as well.

This means that every positional field would count as having both a given name (like `namedExplicitly`) and the getter name (like `$0`), and then we compute conflicts based on this larger set of names.

However, I don't see any conflicts in `(int, {String $100})`, nor in `(int named, {String $100})`.

@munificent, do you agree?

**Comment by lrhn** [comment]
For types, I agree that a given name to a positional, even if it's otherwise entirely decorative, should not be allowed to conflict with another field's given name (positional or named).

For named field's, the name affects the shape/type. For positional fields, the name is documentation only, and we could completely ignore them and any conflict with other names. But we can also tell people that their name, which is there for documentation purposes, is not good documentation, and I think we should.

It's a separate problem whether the name of a field collides with the implicit name of positional fields.
As Erik says, `(int namedExplicitly, {String $0})` does not have a conflict between declared names. It does have a conflict between the implicit getter names associated to the two fields. 
That's declared as a compile-time error because it would otherwise require us to omit one or both of the implicit getters that the type would be expected to have.

That leaves `(int, int $0)`, which has no declared name conflict, and no implementation name conflict, but which is still confusing.

So, maybe we should phrase it as:
> It's a compile-time error if a record type *R* names a field *f* as <code>$*N*</code> where *N* is a decimal numeral with no leading zeros representing the integer value *n*, *R* has a positional field with (zero-based) position *n*, and *f* is not the field with position *n*.
> It's a compile-time error if a record expression *e* contains a named field entry with name <code>$*N*</code> where *N* is a decimal numeral with no leading zeros representing the value *n*, and *e* has a positional field entry with (zero-based) position *n*.

That is: You can't have a named field with name `$x` in a record type or record value with an `x`th positional field. You cannot have a positional field named `$x` in a record type if it's not the `x`th positional field.
```dart
(int, int $0) p1;    // invalid
(int, {int $0}) p2;  // invalid
(int $0, int) p3;    // valid
var r1 = (1, $0: 1); // invalid
```

**Comment by eernstg** [comment]
Then how about `(int, int $100)` and `(int, {String $100})`? I tend to think that we should allow the use of as many names as possible (including `$100`) as long as there are no conflicts (for declared names and for getter names).

**Comment by devoncarew** [comment]
If after discussion it turns out there is any follow-up work for this item, can you triage this issue to the correct sub-team?

**Comment by sgrekhov** [comment]
> Then how about (int, int $100) and (int, {String $100})? I tend to think that we should allow the use of as many names as possible (including $100) as long as there are no conflicts (for declared names and for getter names).

@lrhn what about the case above? Should it be an error or not?

**Comment by eernstg** [comment]
Let's rely on @lrhn's wording [here](https://github.com/dart-lang/sdk/issues/49883#issuecomment-1233941932):

> It's a compile-time error if a record type _R_ names a field _f_ as `$N` where `N` is a
> decimal numeral with no leading zeros representing the integer value _n_, _R_ has
> a positional field with (zero-based) position _n_, and _f_ is not the field with position _n_.
>
> It's a compile-time error if a record expression `e` contains a named field entry with
> name `$N` where `N` is a decimal numeral with no leading zeros representing the value
> _n_, and `e` has a positional field entry with (zero-based) position _n_.

This means that `(int $0, int someName, {String $100})` is OK, but `(int, int $0)` is an error. And it means that `(42, $0: 43)` is an error.

@munificent (when you're back from traveling next week), do you have any worries about this outcome?

**Comment by eernstg** [comment]
I think this topic has been resolved: Every name counts, implicitly induced getters as well as explicitly given names (even though `x` and `y` in the type `(int x, int y)` are just comments), no name counts if it isn't present (so `(int, int, int $0, {String $2})` has two errors, but `(int, {String $1})` is OK).

@sgrekhov and @lrhn, please comment and reopen if you disagree.
