### ISSUE TITLE
valgrind check which succeeds in 2.17 fails in 2.18

### ISSUE THREAD

**Issue by jerel** [dart-lang/sdk#49880]
In an FFI project's CI we have an automated valgrind job which checks our application for memory leaks, when 2.18.0 was released it began failing stating that there are 8 bytes lost. It seems to remain the same (8 bytes) whether the project is large or small.

Using a standard "hello world" Dart project (no FFI) I've narrowed the behavior down to starting somewhere between 2.18.0-256.0.dev and 2.18.0-263.0.dev.

Using Dart version 2.18.0-256.0.dev there is no leakage:
![Screenshot from 2022-08-31 16-00-44](https://user-images.githubusercontent.com/322706/187784682-40fcd91b-f522-4791-bc0b-571695d2e65a.png)

In Dart 2.18.0-263.0.dev (and 2.18.0) there is 8 bytes consistently leaked:
![Screenshot from 2022-08-31 16-01-22](https://user-images.githubusercontent.com/322706/187784714-c50c95fc-75ad-4fa8-91e0-915a899abaa0.png)

Environment:
* No leak: `Dart 2.18.0-256.0.dev`
* Memory leak: `Dart 2.18.0-263.0.dev`
* OS: Linux

To reproduce:
1. `dart create mem_leak`
2. `cd mem_leak`
3. `dart compile exe bin/mem_leak.dart`
4. `valgrind bin/mem_leak.exe`

**Comment by dcharkes** [comment]
https://github.com/dart-lang/sdk/releases/tag/2.18.0-263.0.dev -> https://github.com/dart-lang/sdk/commit/098d3d375acec815c006a0f7b2cd2fe8d55683f4
https://github.com/dart-lang/sdk/releases/tag/2.18.0-256.0.dev -> https://github.com/dart-lang/sdk/commit/ed7360c3b35fb4babcdffbc53f5f0ebd4eefac8c

Commit range: https://github.com/dart-lang/sdk/compare/ed7360c3b35fb4babcdffbc53f5f0ebd4eefac8c~...098d3d375acec815c006a0f7b2cd2fe8d55683f4

I do not see any `malloc` or `calloc` in the changed files.

Maybe https://github.com/dart-lang/sdk/commit/6e3ef8b9e6c155750a50a217bc8a80ca6513af29 ? cc @rmacnak-google 

> Using a standard "hello world" Dart project (no FFI) I've narrowed the behavior down to starting somewhere between 2.18.0-256.0.dev and 2.18.0-263.0.dev.

Removing ffi label as this reproduces _without_ any FFI.

**Comment by rmacnak-google** [comment]
We test the VM with LeakSanitizer/LSAN (which is enabled on Linux as part of AddressSanitizer/ASAN). This includes additional LSAN-specific code to register additional root regions that are directly allocated by the VM via mmap instead of being allocated through malloc. We do not test the VM with Valgrind, but I expect Valgrind needs similar information to function correctly, so false positives from Valgrind would not be surprising.

The particular stack you give might be due to https://github.com/gperftools/gperftools/commit/419c85814de497d6dfaf6f9a19d153138a7dec08 affecting RunningOnValgrind.
But more generally I would not expect Valgrind to work. If I try to run hello world with Valgrind (3.19.0), I get a bunch of bogus errors about mismatched free/delete/delete[] and the Dart heap fails to allocate the first executable memory for stub code.

Some things you might try:
 - Ensure tcmalloc [knows it is running under Valgrind with RUNNING_ON_VALGRIND=1](https://github.com/gperftools/gperftools/blob/gperftools-2.10/src/base/dynamic_annotations.h#L76)
  - Build the Dart VM without tcmalloc (`./tools/build.py --gn-args dart_use_tcmalloc=false`)
  - Build the Dart VM and whatever library you're accessing with FFI with ASAN instead of using Valgrind (`./tools/build.py --sanitizer=asan`)

**Comment by fzyzcjy** [comment]
@jerel Hi I am facing similar cases (a bunch of bogus errors about mismatched free/delete/delete[]), so cross-link here: #47346
