### ISSUE TITLE
[ddc] missing error for null-assertions on field assigments

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#49918]
DDC today is emitting a warning instead of throwing an error when assigning a null value on a field dynamically. An assignment on a setter does throw as expected.

Here is a minimal repro:

```dart
class A {
  bool x = false;

  set g (bool v) { x = v; }
  bool get g => x;
}


main() {
 dynamic a = A();
 a.x = null; // emits warning, both in sound and unsound mode
 a.g = null; // emits warning in unsound mode, throws error in sound mode
}
```

**Comment by nshahan** [comment]
I think the comments in the example are slightly misleading. I see that both assignments fail in sound mode (no soundness violations). The missing failure is in unsound mode with the null-assertions mode enabled when setting a field.

This example isn't ideal since the warnings that appear are a little bit of a red herring. They come from the type checking of the arguments on the dynamic calls, not from any extra checking done on values passed as parameters typed as non-nullable. Another good example would simply assign a null value to the field/setter from an opted out file without the use of dynamic. Since the file is opted out that would pass the static type checking in legacy mode.
