### ISSUE TITLE
Dart 3 core library additions

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#49928]
Generally it's hard to evolve the Dart core libraries, as most changes tend to be potentially widely breaking. For example, adding a new member to a class in the core libraries can be breaking to any code that that implements that class, given all Dart classes are implicit interfaces.

While we still don't want major breaking changes in Dart 3 outside of the non-null discontinuation, we have an opportunity to be *mildly breaking*. 

The concrete list of discussions is still under discussion.

- [ ] Add `Iterable.whereNotNull()` as an extension to Iterable in `dart:core` (currently in `package:collection` as [an extension](https://pub.dev/documentation/collection/latest/collection/IterableNullableExtension/whereNotNull.html))

- [ ] Add `Iterable.firstOrNull()` / `Iterable.lastOrNull()` / `Iterable.elementAtOrNull()`as extension methods to Iterable in `dart:core` (some currently in `package:collection` as [an extension](https://pub.dev/documentation/dartlin/latest/collections/FirstOrNull.html))

- [x] Add `DateTime.copyWith()`. Long standing [request](https://github.com/dart-lang/sdk/issues/24644). As an extension method, to avoid breakage.
https://dart-review.googlesource.com/c/sdk/+/258541

- [ ] records related changes: https://github.com/dart-lang/sdk/issues/49727
https://dart-review.googlesource.com/c/sdk/+/288903

**Comment by Wdestroier** [comment]
Maybe add a `name` property to `FileSystemEntity` and change the `firstWhere()` method from `Iterable` to return a nullable value...

**Comment by lrhn** [comment]
With *records* being a thing, we may want to embrace them.

We have a number of "indexed" iterable extensions in [`package:collection`](https://pub.dev/documentation/collection/latest/collection/IterableExtension.html) that would otherwise be worthy candidates for inclusion in `dart:core`, but with records, we can instead introduce a single "add index to iterable" operation:
```dart
extension IterableExtension<T> on Iterable<T> {
  Iterable<(int, T)> get indexed sync* {
    var index = 0;
    for (var element in this) yield (index++, element);
  }
}
```

Then you would be able to do:
```dart
for (var (i, e) in something.indexed) {
  print("#$i: $e");
}
```

(We'll be missing some affordances in the first release, for example we probably won't have patterns in parameters, so not everything will be as smooth as the `for`-`in`.)


We should consider whether there are other uses of records that afford a similar big result for a small effort.

**Comment by eernstg** [comment]
Usually this one is mentioned as well:
```dart
extension MapExtension<K, V> on Map<K, V> {
  Iterable<(K, V)> get keyed sync* {    
    for (var element in this.entries) yield (element.key, element.value);
  }
}

// Example usage.

void main() {
  var map = {1: "one", 2: "two"};
  for (var (key, value) in map.keyed) {
    print('$key: $value');
  }
}
```

**Comment by lrhn** [comment]
The `Map.keyed` here is mostly redundant with the existing `Iterable<MapEntry<K,V>> get entries`.

You can do `for (var MapEntry(:key, :value) in map.entries) ...` with pattern matching. If we can get rid of the redundant `MapEntry` too, it would be even better.

**Comment by spydon** [comment]
The `DateTime.copyWith` extension is now merged:
https://dart-review.googlesource.com/c/sdk/+/258541

**Comment by iapicca** [comment]
impopular opinion: dart should stop using `Map<String,dynamic>` for json and put somewhere
```dart
typedef Json = Map<String,Object?>;
```

**Comment by bernaferrari** [comment]
My personal request (might be too much): Flutter had `describeEnum`, Dart made Enum a type and `describeEnum` is not needed anymore. Flutter has `compute` to make isolates less painful, maaaaybe Dart could have them too (or at least some simpler API) and help deprecate the one from Flutter.

What I wish Flutter's compute did the most was allowing to be cancellable/killable. Maybe Dart's version could do that.

Regarding the collection additions, they sound great to me. I use `firstWhereOrNull` a lot, I even wish `firstWhere` were discouraged, but it would be too radical.

**Comment by bernaferrari** [comment]
If I could ask for anything crazy in Dart 3, I would go with print("value is", a). I alwaaays struggle with Dart syntax, and it is possible to implement that without varargs. Since print is not supposed to run in release mode, the minimal performance impact is negligible.

https://github.com/dart-lang/sdk/issues/49084

**Comment by mit-mit** [comment]
Hey @lrhn can you please check the list at the top (which I updated) to see if it's complete for 3?
