### ISSUE TITLE
Dynamic and extension

### ISSUE THREAD

**Issue by Andrflor** [dart-lang/sdk#49927]
Should not dynamic be able to pick extensions ?

```dart
extension Simple on List<String> {
   bool get someGetter => true;
}

main() {
    final data = ["val"];
    data.first // "val"
    (data as dynamic).first //  "val"
    data.someGetter; // true
    (data as dynamic).someGetter; // Runtime Error
}
```

**Comment by julemand101** [comment]
No. The extensions are done statically and require the analyzer to know what type you have since the extension methods does not do any changes to the object itself. It is instead a trick where the static method calls are replaced, as part of compiling, with generated static methods.

See also: https://dart.dev/guides/language/extension-methods#static-types-and-dynamic

**Comment by mraleph** [comment]
As @julemand101 explains extensions are resolved statically in compile time so they don't resolve on `dynamic`.
