### ISSUE TITLE
Memory Usage documentation

### ISSUE THREAD

**Issue by Andrflor** [dart-lang/sdk#49945]
Is there any documentation on memory used by the different types?
I cannot find any

https://dart.dev/guides/language/language-tour
Is a bit talking about memory representations but not that much.

For example it says:
> true and false, which are both compile-time constants.

So if I do:
```dart
final boolean = true;
final boolean2 = true;
```
Does it mean that I allocate 1 byte for the boolean (I suppose, I can't find anything).
And that I also allocate 128 bit for the two references?

Since dart if I'm correct is a references passed by value kind of language, if I do:
```dart
final integer = 1;
```
Does it means that I allocate 64 bit for the reference and 64 bit for the int value?

### In brief is that true to say that it cost 64bit to store a boolean in a variable and 128 bit to store an Integer?

What about null values?
If i do:
```dart
Class Foo {
    final int? integer = null;
}
Foo();
```
What happens? Do i allocate the 64 bit reference to the integer?
Or is it allocated only if i use it? How is it handled memory-wise?

**Comment by mraleph** [comment]
There is no detailed documentation on this beyond source code. Dart has a lot of different execution modes (native AOT and JIT, 2 different JS backend,  WASM backend, etc) and runs on many different platforms (ARM, ARM64, X64, IA32, RISC-V) so it is pretty hard to give a single answer to a question "how many bytes a specific object takes".

Lets assume that you are asking about the native implementation.  

```
final boolean = true;
final boolean2 = true;
```

The `true` object itself exists as a single canonical instance, it takes 2 pointer size words on all platforms - because that's the smallest instance size as all allocation sizes are aligned to 2 pointer size words boundary. (e.g. 16 bytes on 64-bit platforms and 8-bytes on 32-bit platforms).  

The reference to a boolean object, assuming that it actually needs to exist - e.g. that this is a global field, which was not eliminated by some optimisation, takes either a pointer size word or half of it - depending on whether this is a compressed pointer configuration or not. (e.g. on 32-bit platform it will be 4 bytes, on 64-bit platform - 8 bytes, but on 64-bit platform with compressed pointers it is going to be 4 bytes again).

```
final integer = 1;
```

Here things start getting complicated. Integer variables might or might not be unboxed. If they are unboxed - then they are passed around as 64-bit integer values, no references involved. If integer variable is not-unboxed then things depend on whether particular integer value is small enough to use a _tagged small integer (smi)_ representation. This representation puts integers directly inside the reference variables using the least significant bit to distinguish between a tagged integer and a reference. If integer does not fit then it is put into a box which would take 16 bytes. To put it all together:

* If unboxed - 8 bytes on all platforms.
* If boxed:
  * if small enough (e.g. representable as a reference-size-in-bits-minus-1-bit signed integer)  directly in the reference variable (pointer size - 4 bytes on 32-bit and compressed 64-bit, 8 bytes on 64-bit).
  * otherwise reference size plus box size is needed (box is 16 bytes on all platforms)

(Again this assumes that this variable or field is not eliminated by some optimisation).

Whether `int` variables are unboxed or not depends on few factors, execution mode needs to be AOT, the variable needs to be provable non-null integer and it should not be a parameter in a position where somewhere in the hierarchy there is a signature override which requires boxing (e.g. parameter of `Object` type).

When we start talking about object allocation things get yet more complicated, e.g. if you write:

```dart
class Foo {
    final int? integer = null;
}

void main() {
  Foo();
}
```

Then in AOT you will not allocate anything at all (not `Foo` nor `Foo.integer`). Optimizations will eat the whole thing. 

If you use result of allocation of `Foo` then whether space for `integer` is allocated or not depends on whether it is ever read or not. 

If it is read then there will be a reference sized field in `Foo` for it.

Hope this sheds some background on this.

**Comment by Andrflor** [comment]
Thank you very much for those insights.
