### ISSUE TITLE
Type is not cast

### ISSUE THREAD

**Issue by AlexanderFarkas** [dart-lang/sdk#49955]
<img width="431" alt="Screenshot 2022-09-12 at 23 14 19" src="https://user-images.githubusercontent.com/35890159/189749837-4dba75a7-a8b8-4fd0-8548-bf0b1a5b3a1e.png">

Same without `<dynamic,dynamic>`
<img width="297" alt="Screenshot 2022-09-12 at 23 14 34" src="https://user-images.githubusercontent.com/35890159/189749928-79f1ca1f-302c-44cb-9f8e-f82c7bac2702.png">

But in that case it starts working
<img width="430" alt="Screenshot 2022-09-12 at 23 15 04" src="https://user-images.githubusercontent.com/35890159/189750107-900be28e-e3ec-45c7-a0ee-294a08ec5175.png">

* Dart SDK version: 2.17.6 (stable)
* Mac OS arm64

**Comment by lrhn** [comment]
You're not showing us the original declaration of `origin`. 
If the third example allows promotion to work, most likely the `origin` variable is a local variable declared as something like `Provider<T, dynamic>`, some type where `FactoryProvider<T, dynamic>` is a subtype, but `FactoryProvider<dynamic, dynamic>` (or the equivalent `FactoryProvider`) is not, because the `dynamic` type argument is not a subtype of `T`.

Dart promotion requires the new type to be a subtype of the current type, otherwise it wouldn't be *promotion*.

Now, it would be *nice* if we could infer type arguments for `is FactoryProvider` which allows promotion, but we [currently don't](https://github.com/dart-lang/language/issues/2047).

**Comment by AlexanderFarkas** [comment]
Great explanation. Thanks
