### ISSUE TITLE
Multiple await keyword can be used in some methods of Future class

### ISSUE THREAD

**Issue by GabrielCR99** [dart-lang/sdk#49965]
* Dart SDK Version 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "windows_x64"

I've tested some methods of the Future class in Dart, and some of them seems to work when I add multiple `await` keyword. 
Analyzer also complains when there are multiple keywords of it. But, in some other methods, it doesn't seem to recognize. The following image shows them

![image](https://user-images.githubusercontent.com/42328188/190168802-ea44d7c3-105c-4565-85dc-7d3612520a21.png)

And then, when fixing those 5 methods that analyzer complains
![image](https://user-images.githubusercontent.com/42328188/190168938-7077ecf8-ef89-43ee-861a-f8965c026ec3.png)

**Comment by asashour** [comment]
Thanks, would you mind writing the code as text in the description instead of images.

**Comment by lrhn** [comment]
The Dart language allows you to await a non-future. You can write `await 0`. It evaluates to `0` after an asynchronous delay.
If you write `await await Future<int>.value(0)`, that is effectively what the outer `await` does.

You have enabled the [`await_only_futures`](https://dart-lang.github.io/linter/lints/await_only_futures.html) lint to get a warning when you have unnecessary `await`s. That's why you get a warning for the last five cases.

The earlier cases have type `Future<dynamic>`, which means you have an `await` on something with static type `dynamic`. That thing could be a future. It probably isn't, but it *could* be.
Take:
```dart
var f = Future<Future<int>>.value(Future<int>.value(1)) as dynamic;
var x = await await f; // Correct number of awaits
print(x); // 1
```
You won't get type-related errors or warnings from something typed as `dynamic`.

**Comment by GabrielCR99** [comment]
> The Dart language allows you to await a non-future. You can write `await 0`. It evaluates to `0` after an asynchronous delay. If you write `await await Future<int>.value(0)`, that is effectively what the outer `await` does.
> 
> You have enabled the [`await_only_futures`](https://dart-lang.github.io/linter/lints/await_only_futures.html) lint to get a warning when you have unnecessary `await`s. That's why you get a warning for the last five cases.
> 
> The earlier cases have type `Future<dynamic>`, which means you have an `await` on something with static type `dynamic`. That thing could be a future. It probably isn't, but it _could_ be. Take:
> 
> ```dart
> var f = Future<Future<int>>.value(Future<int>.value(1)) as dynamic;
> var x = await await f; // Correct number of awaits
> print(x); // 1
> ```
> 
> You won't get type-related errors or warnings from something typed as `dynamic`.

Oh, I see. So this is basically not a bug related to Dart or linter itself, but actually a lack of attention on my part. Glad that you spent some of your precious time to explain this to me. Many thanks! I'll close this issue with my comment, since you've clarified things. See ya!
