### ISSUE TITLE
[coverage] regression Dart 2.18.0 breaks test coverage

### ISSUE THREAD

**Issue by felangel** [dart-lang/sdk#49962]
On Dart 2.17.6 the following commit was reporting 100% code coverage as expected: https://github.com/felangel/bloc/actions/runs/2857181718/jobs/4527629976

Using Dart 2.18.0, [the coverage is now reported to be 96%](https://github.com/felangel/bloc/actions/runs/3049903865/jobs/4916449371) with the following line uncovered:

![Screen Shot 2022-09-13 at 10 26 25 PM](https://user-images.githubusercontent.com/8855632/190052813-cbe4a4c4-a904-4940-abd9-a6b3b921622d.png)

That line is definitely being executed and the following line is marked as covered.

This tracker is for issues related to:

* Dart core libraries ("coverage")
* Dart VM

* Dart SDK Version (`dart --version`): Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "macos_arm64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)": MacOS
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): N/A

**Comment by liamappelbe** [comment]
@felangel Is `mappedSubscription` null? Because that's the only way I'm able to repro the missing coverage. This does indeed seem to be a change in behavior from Dart 2.17, as this line appears covered even when `mappedSubscription` is null in that version, but I think that's a bug, and the new behavior is correct. So if `mappedSubscription` is null, this is working as intended imo, and you should add a test for the case where it's non-null.

If it's non-null, and still reported as uncovered, that's definitely a coverage bug. But if that's the case, I'll need your help in figuring out a minimal reproduction of the bug. I've tried a few variations of awaiting an async method on a nullable object invoked using `?.`, but if the object isn't null then I can't repro the bug.

Something else you can try, that I noticed on [another coverage bug](https://github.com/dart-lang/sdk/issues/49887), is that it might only be reproducible if you do call it through `dart test`. So you could try running the test script directly, and see if coverage is still missing. That would tell me if it's another instance of that same bug.

**Comment by felangel** [comment]
@liamappelbe just verified and you're right -- technically the new behavior is correct and this was just previously a bug.

**Comment by mraleph** [comment]
Thanks for taking a look @liamappelbe!

Closing as WAI based on @felangel comment.
