### ISSUE TITLE
How can I modify functions that exposed in dart_api_dl.h?

### ISSUE THREAD

**Issue by Frost819** [dart-lang/sdk#50012]
Hello. I know that functions in `dart_api_dl.h` is a subset of `dart_api.h` and are postfixed with `_DL`. So as I intended to do some modification on some functions exposed in `dart_api_dl.h`, I went to the `dart-sdk/runtime/vm` to modify the corresponding functions without _DL. Then I followed [https://github.com/dart-lang/sdk/wiki/Building](url) to build my own dart-sdk to replace the one in flutter engine.
After my Flutter app started running, I see my additional debug info printed out in the background. But my own calls to the modified functions didn't seem to work the way it was supposed to. 
So my question is that aren't functions with and without `_DL` built from the same code? If not, how can I get it done the right way?
Thank you.

**Comment by mraleph** [comment]
If you want to replace Dart VM inside Flutter engine then you need to build and use a custom engine, rather than build a custom Dart SDK. Follow https://github.com/flutter/flutter/wiki/Compiling-the-engine instead and then use `--local-engine` flag for `flutter` tool to instruct it to use your custom engine build.
