### ISSUE TITLE
[Records] Wasm implementation

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#50014]
Records support in the dart2wasm compiler.

**Comment by chloestefantsova** [comment]
Unsupported RecordType in `co19/LanguageFeatures/Records/interaction_with_legacy_A04_t01` discovered by dart2wasm bot: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8798608646316632353/+/u/test_results/new_test_failures__logs_

**Comment by askeksa-google** [comment]
Some thoughts, based on the [records specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md).

In dart2wasm, we'll likely want to have two representations for records:
- boxed (the record is a Wasm struct with its fields stored in the fields of the struct)
- unboxed (the fields of the record are individual Wasm values stored in separate locals/fields/inputs/outputs depending on context.

Since boxed records can implement all features of records, and unboxed records can't, unboxed records can be regarded as an optimization. Since unboxed records furthermore require some changes to fundamental assumptions in the compiler (such as a one-to-one correspondence between Dart values and Wasm values), I suggest we implement only boxed records to begin with and consider unboxed records later.

Like function types, record types have structural subtyping, which means a record type can have multiple supertypes. This means that the representation of boxed records must be such that for any two record types `t1` and `t2`, if `t2` is a subtype of `t1`, then the Wasm representation for `t2` must be a subtype of the Wasm representation for `t1`. Since a Wasm struct can only declare a single supertype, some sort of collapsing of types needs to take place, i.e. the representation for a boxed record can't be just a struct with field types corresponding to the record field types.

The representation for closures achieves this by two means:
- Use `ref null #Top` for all parameters and returns
- Use an elaborate hierarchy of structs to handle subtyping on the _shape_ of the function, i.e. the valid range of number of positional parameters and the names of named parameters

Records are simpler than functions in that if `t2` is a subtype of `t1`, then `t1` and `t2` have exactly the same shape (number of positional fields and names of named fields). Thus, we can just have one Wasm struct per shape, using `ref null #Top` for all fields. This will fulfill the subtyping property.

To implement the members of record types (`runtimeType`, `toString`, `==`, `hashCode`), we can assign a class ID to each shape that occurs in the program and generate specific implementations for each shape. To implement `runtimeType` on top of such a representation with erased types, the record structs will additionally need a field which is a list of the types of its fields. This list will usually be a constant.

**Comment by osa1** [comment]
I started looking into implementing this. I'm not writing any code yet, just trying to figure out the design.

Relevant kernel nodes:

- `RecordIndexGet { Expression receiver; RecordType receiverType; int index; }`
- `RecordNameGet { Expression receiver; RecordType receiverType; String name; }`
- `RecordLiteral { bool isConst; List<Expression> positional; List<NamedExpression> named; RecordType recordType; }`
- `RecordConstant { List<Constant> positional; Map<String, Constant> named; RecordType recordType; }`

and kernel type:

- `RecordType { List<DartType> positional; List<NamedType> named; }`

# Notes

- Records cannot be updated, do not have setters.
- Positional fields generate getters `$0`, `$1`, .... No `operator []`.
- Field names cannot start with underscore.
- Field names can start with `$`, but the name should not collide with a positional field. E.g. `$123` is fine assuming `$123` isn't already a positional field.
- Implementations can re-order fields. Order of field iteration in `operator ==` is left implementation-specific.

Records are objects and have have `toString`, `runtimeType`, `operator ==`, and `hashCode` implemented structurally. Also `noSuchMethod`.

No width-subtyping, only depth-subtyping. I.e. cannot pass record with more fields when a smaller record is expected, but passed record can have fields that are subtypes of expected fields.

- `({num a, num b, num c})` is not subtype of `({num a, num b})`
- `({int a, num b})` is subtype of `({num a, num b})`

# Implementation

Records are objects, need to be boxed the same way, with a class ID and a hash code field.

Implementations of `Object` members:

- **toString:** Positional fields, followed by sorted named fields: `(1, 2, a: test, b: x)`
- **runtimeType:** Same as `toString`: `(int, int, {String a, String b})`
- **operator ==:** List of positional argument types and set of named fields should be equal. `operator ==` called on corresponding fields.
- **hashCode:** As expected. Equals should have same hash code.
- **noSuchMethod:** can be inherited from `Object`?

"Shapes" of records in the program are known in compile time and shape data can be allocated statically.

Shape is: Number of positional fields + set of names of the named fields.

If we generate a class ID per shape, and make sure record class IDs are consecutive, then we can easily map a record object to its shape object without any extra fields in records: `RECORD_SHAPES[classID - minRecordClassID]`.

This will mean one dispatch table entry per record shape in the program for `Object` members. Alternatively we could have a single class ID for all records, and store a pointer to (or an index of) record shape descriptor in the records. This would mean single dispatch table entry for each `Object` member, but one field (word?) memory overhead.

In both cases, implementations of `Object` members will be the same. The only difference is the code that gets shape of a record.

## Dynamically invoking getters

It's easily possible to dynamically call the getters, with a single class ID, or per-shape class ID.

I think we don't really need to generate any getter functions, forwarders can directly read the fields.

Generated code size will be about the same with both per-shape and single class IDs:

- **With single class ID:** Forwarder will compare the shape pointer with known shape pointers, and directly get the field.
- **With per-shape class ID:** Forwarder will compare the class ID with the shape class IDs, and directly get the field.

## Wasm types of record fields

I don't understand Wasm GC types in detail so I'm not sure about this part. Some thoughts below.

We can use a few different Wasm types for records:

- We can store record fields in an array, but that would mean a layer of indirection and downcasting when accessing.

  The advantage is there will be a single Wasm type for all records, and fields can be passed to Dart functions (maybe to implement `toString` etc.) without allocation. (we may need some more `_WasmBase` classes to deal with Wasm arrays in Dart)

- We can define a struct per shape. Compared to the array approach above, this won't need a layer of indirection when accessing, but it will need downcasting as field types need to be top types.

- We can define a struct per static type. This will perform best as we can access fields directly (no indirection or downcasting), but there can be large number of struct types.

So we have a spectrum from slower access and good code size to faster access and worse code size.

---

@askeksa-google 

> To implement runtimeType on top of such a representation with erased types, the record structs will additionally need a field which is a list of the types of its fields. This list will usually be a constant

We can get the runtime type from the shape alone, no? Shape will give us the fields (with names), which we can use the compute the runtime type, by getting `runtimeType` of each field. I don't think an additional field is necessary.

**Comment by askeksa-google** [comment]
As for the representation of records:
- Using an array would be inefficient, not just because of the indirection, but also due to the bounds check.
- One struct per shape will work well.
- One struct per static type will not work due to subtyping. If you have `(Object, Object)`, `(int, Object)`, `(Object, int)` and `(int, int)`, then the subtyping relationship between them forms a diamond. Since a WasmGC struct has a single supertype, there is no way to define the types that is consistent with the original subtyping. Furthermore, the runtime type might be a subtype of the static type, so basing the representation on the static type will not enable it to be downcast to its actual type.

> We can get the runtime type from the shape alone, no? Shape will give us the fields (with names), which we can use the compute the runtime type, by getting runtimeType of each field. I don't think an additional field is necessary.

Yes, that's correct. The runtime type depends only on the shape and the runtime types of the field values.

**Comment by osa1** [comment]
This is being implemented in https://dart-review.googlesource.com/c/sdk/+/279398.

I'm thinking leaving dynamic gets and sets of records to another CL and only implementing static cases in this CL.

**Comment by osa1** [comment]
Current iteration of records is in https://dart-review.googlesource.com/c/sdk/+/280461. I will summarize the designs here.

**Comment by osa1** [comment]
Here's the summary of two designs we tried, with problems in each:

## One record class: CL 279398

- One record class, all records share the same class ID

- Requires a "shape ID" field in each record, to be able to distinguish records with different shapes in `==`, and generate different hash codes for records with different shapes but same field values. (e.g. `(null, null)` and `(a: null, b: null)`).

- `toString`, `==`, `runtimeType`, `hashCode` need to know number of positionals and set of names. This can be done in two ways:
  - Map shape IDs to field info in an array
  - Instead of shape IDs, have two fields:

    - An int field for number of positionals
    - A pointer to the array of names

    Either way we add more fields to records (memory overhead)

- **Problem:** We need to know all field names in the program, to be able to handle records in dynamic forwarders. Currently the dispatch table builder (which also generates members lists used in dynamic forwarders) can only generate entries for class members, so it won't readily handle records. We need to annotate .dill files with record names in the compilation unit, and refactor dispatch table builder.

## One class per shape: CL 280461

- One class per shape, see [CL description][1] for an example class.

- Gives us dynamic get support for free

- Faster methods: we know the set of fields when generating method code so we generate efficient code that doesn't need to check class or shape ID.

- **Problem:** Does not readily work with modular compilation (.dill files).

  - With modular compilation, the same record in two different libraries will have the same class in different libraries, which will break `==`.

  - Even if we somehow make `==` work, there will be duplicate code for records with same shapes in different libraries.

  - When generating record shape classes outside of `dart:core` we can't override `_runtimeType`, which causes runtime type checks to fail.

    - We can do this trick:
      ```dart
      abstract class _Record extends Record {
        @override
        _Type get _runtimeType => recordRuntimeType;

        // To be implemented in generated classes
        _Type get recordRuntimeType;
      }
      ```
      But that makes `recordRuntimeType` publicly visible.

      We could name it `$$$DONT_USE_recordRuntimeTypeDONT_USE$$$`, but it seems hacky.

    - This is another manifestation of #51134.

  - We can delay generating classes and annotate .dill files with record shape information, but

    - The problem with overriding `_runtimeType` persists
    - Depending on when we generate the classes, TFA metadata and/or type class hierarchy may not be correct. These analyses need to run *after* record shape class generation.

---

Both CLs have smaller issues that I omit above as I think those could be easily solved (like the incorrect TFA metadata in one-class-per-shape CL).

I like the one-class-per-shape approach more as member implementations will be faster, and I don't know how to implement dynamic gets with the single-class approach.

I'll be working on making the one-class-per-shape approach work with modular compilation. I don't know how to best solve the problem with runtime types, but in the worst case we can use the trick I show above, maybe with name like `$$recordRuntimeType`.

[1]: https://dart-review.googlesource.com/c/sdk/+/280461

**Comment by osa1** [comment]
> Problem: Does not readily work with modular compilation (.dill files).

The problems with modular compilation are easily fixed by generating the classes right before TFA when we have the whole program. The only remaining problem is incorrect direct and dynamic call metadata.
