### ISSUE TITLE
Support extension method call site as creation location of widgets

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#50067]
Original issue: https://github.com/flutter/flutter/issues/112468

Extensions on `Widget` allow for a code style where, instead of nesting widgets by passing them as arguments to constructor calls of other widgets, we call extension methods. This style has the advantage of avoiding the left to right drift of nesting, requires fewer lines and is, in general, more readable, IMHO.

```dart
// Traditional style
Center(
  child: Padding(
    padding: EdgeInsets.all(8),
    child: Text('Hello World'),
  ),
);

// Extension method style
Text('Hello World')
  .padding(EdgeInsets.all(8))
  .center();

extension WidgetExtensions on Widget {
  Widget center() => Center(child: this);
  Widget padding(EdgeInsetsGeometry padding) =>
      Padding(padding: padding, child: this);
}
```

The reason why I don't currently use this style is that it leads to a bad debugging experience. Widget instances record the location in source code where they are constructed, and dev tools use this information. When using the described extension methods to build widget trees, the extension method is recorded as the creation location for returned widget instances, which is not helpful to developers.

I would prefer that the call site of the extension method is recorded as the creation location for widgets returned from these types of extension methods.

One way this could be solved is by allowing extension authors to annotate methods:

```dart
  @widgetFactory
  Widget center() => Center(child: this);
```

**Comment by lrhn** [comment]
I'm no sure which code records the location of `Widget` creations. If it's Flutter code, the request should be in the Flutter repository.
If it's general code in the Dart VM which records object creations, the annotation should not mention `widget`. It's just a "@factoryMethod" in general, and the location of the call to a factory method can be recorded instead of the allocation being done inside it (a `factory` constructor would perhaps count as a factory method by default).

If that is at all possible, It's *very* likely that the source location of the constructor invocation is baked into the compiled program, and not found at runtime, which means it's not trivial to start runtime traversing the stack to find the nearest non-factory method's location. Not impossible, since you can statically see when you call a (static) factory method.

**Comment by blaugold** [comment]
Widget location tracking is implemented as a [kernel transformation](https://github.com/dart-lang/sdk/blob/main/pkg/kernel/lib/transformations/track_widget_constructor_locations.dart) and Flutter accesses the location through an [interface](https://github.com/flutter/flutter/blob/c07af53b3cb2182d7735f022969efb00f2ddbd27/packages/flutter/lib/src/widgets/widget_inspector.dart#L2985) that is implemented by the transformation.

**Comment by iapicca** [comment]
possibly related to 
https://github.com/dart-lang/language/issues/2444
https://github.com/dart-lang/language/issues/723

**Comment by johnniwinther** [comment]
cc @jonahwilliams @jacob314

**Comment by blaugold** [comment]
I have implemented support for the proposed annotation here: https://dart-review.googlesource.com/c/sdk/+/263380

The result of annotating an extension method with `widgetFactory` is that widgets created in the method are regarded as local and show up in the inspector summary tree. Navigating to the creation location of such a widget places the focus of the editor on the extension method that created the widget:

https://user-images.githubusercontent.com/5929595/194835539-1248537a-6285-43c1-ab95-936ca39370f6.mov

**Comment by johnniwinther** [comment]
@blaugold Thanks for the CL. I'll look into it.

**Comment by Hixie** [comment]
I strongly support making the kernel transformation be something people can reuse without having to change Dart. It's against our philosophy for Dart to be special-casing Flutter.

I don't have a particular opinion on the proposal in this issue specifically.
