### ISSUE TITLE
Null Safety migration tool ads casts that will fail at runtime for some collection spread operations

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#50088]
I've seen this pattern appear in real world code and the inserted cast is incorrect because it might not always be safe and I believe the implicit downcast from dynamic in the spread operation is sufficient.

The original code looks like:

```dart
class C {
  List<Set<int>> _listField;
  
  C(List<dynamic> myList) : _listField = [...myList];
}
```

The migration tool changes the type of the field and adds a cast in the spread operation:
```dart
class C {
  List<Set<int>?> _listField;
  
  C(List<dynamic> myList) : _listField = [...myList as Iterable<Set<int>?>];
}
```

That appears valid at compile time but the cast fails at runtime when the argument has a reified type of `List<dynamic>`, even if it contains only elements of the correct type. Specifically there was no cast failure before because the implicit downcast in the spread happens on the elements instead of the collection.

cc @stereotype441

**Comment by markegli** [comment]
Seen in places besides spread operations, as well. More generally, this could be: Null Safety migration tool casts collections instead of collection values.

**Comment by yanok** [comment]
May I ask you how do you call `C`? And what do you think the desired migration tool behavior must be? Skip the cast at all?

I played with it a bit and it fails for me both with **and** without cast if I call it with a list literal, but that's exactly because list literal's runtime type is `List<dynamic>` (or `List<Object?>` in VM). If I give the list the right type (can be both `List<Set<int>>` and `List<Set<int>?>`), it works fine both with and without cast.

So I wonder why the list literal type is so generous? Is it because we want to support code like

```dart
final l = [];
for (...) {
  // add elements to the list
}
```
?

@markegli Could you provide some examples, please?

**Comment by nshahan** [comment]
@yanok 
> May I ask you how do you call C? 

The situation appears when the C constructor is called with a List that has a type at runtime of `List<dynamic>` for example:

```dart
class C {
  List<Set<int>> _listField;

  C(List<dynamic> myList) : _listField = [...myList];
}

main() {
  List foo = [
    {1, 2, 3},
    {4, 5, 6}
  ];
  var c = C(foo);
  print(c._listField);
}
```

> And what do you think the desired migration tool behavior must be? Skip the cast at all?

This code runs safely before and after migration without the cast that the migration tool added. 

If the value of the collection being spread doesn't match the collection it is being spread into then casts should already be performed on each of the elements when the spread operation occurs.

```dart
main() {
  List foo = [
    {'one', 'two', 'three'},
    {4, 5, 6}
  ];
  var c = C(foo); // Still throws without the cast inserted by the migration tool
  print(c._listField);
}
```

**Comment by yanok** [comment]
Thanks for the example! I would try to look into that but can't promise I will get to it. The general thought is we should try to get rid of `dynamic` in type safe code as much as possible, so I won't prioritize migration tool issues related to `dynamic`. In your example, the right fix would probably be to just omit `foo` type and let the inference do its job (`final foo = ...`) instead of doing explicit `List<dynamic>`. Then you could probably also tighten the `C` constructor argument type. Of course I understand that real code is likely more complicated than this distilled example and it can be less trivial.

**Comment by nshahan** [comment]
> In your example, the right fix would probably be to just omit foo type and let the inference do its job (final foo = ...) instead of doing explicit List<dynamic>. 

Prioritization makes sense, and I don't know how common it is but I have run into it in real code.

I just think the dangerous part here is that the migration tool will add code that will fail at runtime for no reason at all. There are no compile time errors with or without it. The person migrating must simply notice and remove the cast somehow.

**Comment by stereotype441** [comment]
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.
