### ISSUE TITLE
[Question] Are Generators More Performant than Loops

### ISSUE THREAD

**Issue by moneer-muntazah** [dart-lang/sdk#50086]
Hi

In the documentation generator functions are described as lazy. Does that mean they are more performant than loops.

in the example below what is the difference between example1 and example2? Is there any benefit of lazy execution. Is it correct to say that example1 is O(2n) and example2 is O(n)

```
  
void main() {
  
  
  var e1 = example1( [
    {'number': 1},
    {'number': 2},
  ]); 
  
  print(e1[0].number);
  print(e1[1].number);
  
  var e2 = example2( [
    {'number': 1},
    {'number': 2},
  ]); 
  
  print(e2[0].number);
  print(e2[1].number);
}

List<Dto> example1(List<Map<String, dynamic>> json) {
  List<Dto> list = [];
  for (var j in json) {
    list.add(Dto.fromJson(j));
  }
  
  for (var l in list) {
    l.number += 42;
  }
  
  return list;
}

List<Dto> example2(List<Map<String, dynamic>> json) {
  List<Dto> list = [];
  
  Iterable<Dto> g() sync* {
    for (var j in json) {
      var dto = Dto.fromJson(j);
      list.add(dto);
      yield dto;
    }
  }
  
  for (var l in g()) {
    l.number += 42;
  }
  
  return list;
}


class Dto {
  Dto(this.number);
  
  factory Dto.fromJson(Map<String, dynamic> json) => 
    Dto(json['number']);
  
  int number;
}
```

Thank you

**Comment by eernstg** [comment]
A lazy approach to computation can be significantly more performant than an eager one if we consider cases like "from this infinite sequence, take the first 3 elements". ;-)

However, it's not faster when the two approaches are doing the same job. In particular, a method with a `sync*` body is known to incur some extra costs, compared to plain iteration, e.g., using a `for` statement. So it's definitely not a good idea to use `sync*` in order to improve the performance&mdash;you would use `sync*` because performance isn't critical, and the resulting code is more readable and more maintainable etc.

With respect to the concrete example, it looks like you could simplify a number of things and end up with the following:

```dart
void main() {
  var e1 = example1([
    {'number': 1},
    {'number': 2},
  ]);

  print(e1[0].number);
  print(e1[1].number);

  var e2 = example2([
    {'number': 1},
    {'number': 2},
  ]);

  print(e2[0].number);
  print(e2[1].number);
}

List<Dto> example1(List<Map<String, dynamic>> json) =>
    [for (var j in json) Dto.fromJson(j)..number += 42];

List<Dto> example2(List<Map<String, dynamic>> json) =>
    [for (var j in json) Dto.fromJson(j)..number += 42];

class Dto {
  Dto(this.number);
  factory Dto.fromJson(Map<String, dynamic> json) => Dto(json['number']);
  int number;
}
```

In this approach we're using a list literal with a `<forElement>`. This construct is similar to a for statement, except that it delivers elements that are inserted into list. You may have code which is a lot more complex, and hence you might not want to perform all these simplifications, but it is surely more performant if you avoid creating multiple iterables (lists) and avoid iterating over them multiple times, unless that is actually required.
