### ISSUE TITLE
Var shadowing not hinted/warned by analyzer

### ISSUE THREAD

**Issue by Zazo032** [dart-lang/sdk#50142]
Hi, I did perform a "fix all" for the lint `no_leading_underscores_for_local_identifiers` and came accross this issue that was not hinted/warned by the analyzer:

<details>
<summary>Old code</summary>

```dart
void foo({bool? bar}) {
  bool? _bar = false;
  print(bar);
  print(_bar);
}
```
</details>

<details>
<summary>After automatic fix</summary>

```dart
void foo({bool? bar}) {
  bool? bar = false;
  print(bar);
  print(bar);
}
```
</details>

Even though after fixing the lint there was a variable being declared with the same name as one parameter, there was no hint/warning about it, and the function required some extra changes to make it work again.

## Dart version
```
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "windows_x64"
```

**Comment by asashour** [comment]
There are two separate things I guess:

1. The analyzer fix should not be offered for that case.
2. Both the analyzer and CFE don't complain for a duplicate declaration in:
```dart
void foo({bool? bar}) {
  bool? bar = false;
}
```

**Comment by asashour** [comment]
https://dart-review.googlesource.com/c/sdk/+/262606

for the first point

**Comment by bwilkerson** [comment]
The first point you raise is a bug, though I would phrase it slightly differently than you did: the fix should not change the name to something that shadows an existing name. I'm not sure what name it should suggest, but the most consistent approach I can think of is to drop the underscore and add to the end of the name the smallest numeric index that will prevent shadowing.

The second isn't a bug. Block structured languages like Dart intentionally allow name shadowing. While it's true that shadowing can often be a cause of bugs, there are times when it's very convenient to allow shadowing. Because it's explicitly allowed by the language, there is no diagnostic produced.

I will note, however, that we have at least one lint that addresses one aspect of this issue: `avoid_shadowing_type_parameters` prevents one type parameter from shadowing another. It is, however, very narrow in that it doesn't prevent other names from shadowing a type parameter. It might make sense to have a lint to prevent local variables from shadowing other local variables, which would cover the case above. I opened an issue against the linter to discuss the question (https://github.com/dart-lang/linter/issues/3755).

**Comment by asashour** [comment]
Thanks for the feedback, that's a better approach.

CL was updated accordingly.
