### ISSUE TITLE
Use of `{` as a trigger character under LSP

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#50174]
The Dart language server [uses `{` as a trigger character for code completion](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/lsp/constants.dart#L27). We have a report that this leads to the unfortunate situation where typing the following:
```
void f() {
```

can automatically insert `}` and trigger code completion between the two braces. Pressing the return key at this point causes the top suggestion to be inserted.

I wasn't able to reproduce the behavior, but wanted to ask whether this is expected, and if so what the rationale was for using `{` as a trigger character.

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
The reason for using `{` as a trigger character is to open completion when typing expressions in string interpolation:

```dart
var s = '${
```

This was originally requested in https://github.com/Dart-Code/Dart-Code/issues/476.

However, it's not intended to cause issues as you described, because we "filter" the trigger characters on the server. In the case of `{`, we specifically check we're at the offset of an interpolated string expression here:

https://github.com/dart-lang/sdk/blob/daa733ef432e9d694f4081697426c32eeb73325e/pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart#L681-L683

So I'd be interested in more info about the instances where this is happening. Is it possible it's an LSP client other than VS Code (in which case perhaps it's not passing the trigger character over for us to validate?).

**Comment by DanTup** [comment]
> Is it possible it's an LSP client other than VS Code (in which case perhaps it's not passing the trigger character over for us to validate?).

It this does turn out to be the case, we could perhaps reduce the set of commit characters, since the client likely advertises (or does not) that it supports `CompletionContext` in its capabilities (`completion.contextSupport`). Unfortunately without this context the automatic triggering might be much more unreliable (either not triggering when expected, or unexpectedly triggering on characters out of context) but it might be better to trigger too little than too much.

**Comment by DanTup** [comment]
@bwilkerson just reviewing some LSP issues.. did the response above make sense? Do you have(/can you get) any more info or have you had any more reports of this?

**Comment by bwilkerson** [comment]
Yes, your response made sense. No, I haven't heard any other reports of this. I'll close this issue as WAI and we'll open a new issue if we get new reports.
