### ISSUE TITLE
has not null check on Map to List

### ISSUE THREAD

**Issue by normidar** [dart-lang/sdk#50211]
* Dart SDK Version (`dart --version`).   -> [Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64"]
* Whether you are using Windows, MacOSX, or Linux (if applicable)   -> [macos  12.6（21G115）MacBook Pro (13-inch, M1, 2020)]
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable).  -> [Chrome]

<img width="439" alt="sss" src="https://user-images.githubusercontent.com/36730656/195970141-da905b91-3422-4cd3-b027-c1d2a0494be1.png">

`List detectionResult = result?['detectionResult'];`

when I write this IDE (VSCode)  did not show an error to me it is build succeeded.

but `result` is nullable, when the result is null List should be null, but now it is not.

**Comment by asashour** [comment]
Possibly related to https://stackoverflow.com/a/67652647/184201

**Comment by lrhn** [comment]
The type of `result?['detectionResult']` is indeed `dynamic`. It's nullable, but it's also possibly a `String`.
You get no warnings when assigning `dynamic` to any other type, that's the entire point of the type - it's type checked dynamically (at runtime) instead of statically (at compile time).

So this is working as intended. Try casting your `result` to `Map<Object?, Object?>`. Then you'll avoid having `dynamic` as a type.

**Comment by normidar** [comment]
@lrhn 
but, but when `result` is null the return should be null. I think.

also like this:

```
  Map<Object?, Object?>? m = {};
  List a = m[''] as List;
```

it had no error on compile time, but when `m` is null it is not a null safety.

**Comment by asashour** [comment]
I understand this as a request that unassigned variable should be evaluated to `null` by the analyzer, and so it shouldn't be cast to anything else.

The below doesn't give an analysis error, but there is a run time error:

```dart
void f() {
  int? a;
  int b = a as int;
}
```

**Comment by lrhn** [comment]
Dart's *static* null safety prevents you from accidentally passing a `null` value into a context expecting a non-`null` value.
It does that by making `T?` not assignable to `T`. There is nothing magical about it otherwise, it's just a normal subtyping check.

Dart allows you to *override* the static type system in a number of ways. When you do so, the compiler inserts runtime checks to ensure that the code is still *sound* (a non-nullable variable won't contain `null`), even if it's not *safe* (it might throw).

You're using a number of those overrides here:
* The type `dynamic`. Anything expression with static type `dynamic` is ignored by static type checks. Anything you do is assumed to work. You can call any method and assign it to any type. If you do, a runtime check is inserted, which may throw at runtime. You'll never get a static warning about it, even if a smart compiler could potentially figure out that it'll *never* work.
* A type cast, `as int`. When you do `e as int`, you're saying to the compiler that it should ignore the type of `e` and pretend it has type `int`. At runtime, it'll check that the value actually does have type `int`, and throw if not. Again, the compiler won't interfere with that, even if it can see that the value will never have type `int`. 

In both cases, you are turning off the static type checking, and introducing runtime checking instead, which means no compiler warnings and potential errors at runtime, That's how the language is specified.

In both cases, the _analyzer_ could potentially tell you that something is wrong, even if the language itself doesn't help you. Like knowing that a variable like `m` is definitely `null`, so `m?[''] as List` will be equivalent to `null as List`, and that's never going to work.
That all depends on how smart the analyzer really is, and what it spends it smarts on.

**Comment by normidar** [comment]
@asashour @lrhn 
Thanks for answering me again.

```
void f() {
  int? a;
  int b = a as int;
}
```

I don't think it's a good decision, It should not error on runtime.
we can tell the editors they should pay attention to this issue, so why not we do?

or we can add a problem with dart_lint.
