### ISSUE TITLE
[dart2js] global analysis performance: polymorphic calls to moveNext

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#50259]
The CPU profiles shows that calls to moveNext from FunctionSet.query are highly polymorphic.

This could probably be fixed by using specialized loops for each kind of FunctionSet (List or Set) before iterating.

**Comment by fishythefish** [comment]
The loop in question is here: https://github.com/dart-lang/sdk/blob/dbb793a33010b9d189fe158c8be6ca460241592c/pkg/compiler/lib/src/universe/function_set.dart#L209

`elements` is a `List<MemberEntity>` when it contains a small number of values (currently `MAX_ELEMENTS_IN_LIST = 8`) and a `Set<MemberEntity>` otherwise.

I tried a few different patterns, but checking whether we have a list or set and then casting before performing the iteration does not appear to make a noticeable difference in my testing.

**Comment by sigmundch** [comment]
@fishythefish @natebiggs - was it also the case that this code was no longer in the critical path after we did some other fixes in global inference?

I'm tentatively marking this as obsolete, but just wanted to double check whether there was anything else pending here.

**Comment by fishythefish** [comment]
Yes, I think that's correct.
