### ISSUE TITLE
Can't add Tested tag to active review to satisty Commit-Message-Has-TEST

### ISSUE THREAD

**Issue by tarobins** [dart-lang/sdk#50250]
I have an active review that I'm trying to submit.  https://dart-review.googlesource.com/c/sdk/+/264640

I created the review by creating a PR and letting copybara create the review (first dart review and didn't know if this was the proper method).

I need to satisfy the Commit-Message-Has-TEST submit requirement, but when I try to add a TEST or Tested: to the gerrit commit message, I get an error 

```
Error 403: modifying commit message not permitted

Endpoint: /changes/*~*/message
```

I do have a Tested line on the original PR https://github.com/dart-lang/sdk/pull/50240, but that doesn't seem to be pulled in to gerrit.  How do I add a TEST or Tested to the gerrit review?

**Comment by alexmarkov** [comment]
Could be related to the user permissions as I was able to modify commit message of that change.
But it would be nice to inherit that line from github PR automatically.
/cc @athomas

**Comment by athomas** [comment]
We've had issues with importing the PR descriptions so we had to disable that. That's why it's no longer possible to pass through a `Tested:` footer.

If the CLs are created through copybara imports, the author is not the owner of the change (not sure if that can be changed) and therefore doesn't have the usual rights. We would have to allow all registered users to add patch sets to any change (this may cause spam).

**Comment by athomas** [comment]
Workaround is to create the CL directly in Gerrit.

**Comment by alexmarkov** [comment]
It looks like we now need at least 2 maintainers to accept contributions from Github to the VM. If one person modifies commit message to include `TEST=` marker, then their Code-Review+1 no longer counts and another reviewer is needed. 

For example: https://dart-review.googlesource.com/c/sdk/+/276622.

**Comment by athomas** [comment]
Bot owned CLs are now exempt from Commit-Message-Has-TEST, so copybara imports no longer require these footers.
