### ISSUE TITLE
`dart fix --compare-to-golden` takes significantly longer than expected

### ISSUE THREAD

**Issue by pdblasi-google** [dart-lang/sdk#50252]
Sometime [between commit d9d4c2c and commit f125805](https://github.com/dart-lang/sdk/compare/d9d4c2c..f125805), `dart fix --compare-to-golden` began taking significantly longer.

See [this flutter flakiness issue](https://github.com/flutter/flutter/issues/113705) for instigating issue.

## Expected
`dart fix --compare-to-golden` would run for ~1-2mins for `packages\flutter\test_fixes`

[Luci logs with expected behavior](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800583850193715857/+/u/run_test.dart_for_framework_tests_shard_and_subshard_misc/test_stdout), search for "packages/flutter/test_fixes", which will be towards the bottom of the output.

## Actual
After an [engine roll](https://github.com/flutter/flutter/commit/e1f3cff2e13d627c30e8ca03d285559236864df5) that did a [dart SDK roll](https://github.com/flutter/engine/pull/36715/files), the same `dart fix --compare-to-golden` call now takes between 6-10 minutes.

[LUCI logs with new behavior](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800576328145765361/+/u/run_test.dart_for_framework_tests_shard_and_subshard_misc/test_stdout), search for "packages/flutter/test_fixes", which will be towards the bottom of the output.

**Comment by pdblasi-google** [comment]
@jason-simmons further narrowed this down to [this commit](https://github.com/dart-lang/sdk/commit/20218dfe15c08091afb50cb8a67dd00f5f8f78ef).

That commit was to fix #45475.

**Comment by asashour** [comment]
Thanks for hinting. I guess that the code tested doesn’t have an error (`missing_required_argument`).

For further investigations

**Comment by asashour** [comment]
The reason is actually due to many invocations of `TransformSetManager` [here](https://github.com/dart-lang/sdk/blob/6e4e12922a3d4d90357839847b9275a04c829ab7/pkg/analysis_server/lib/src/services/correction/dart/data_driven.dart#L61).

The commit in question triggered many new potential fixes for the multiple `MISSING_REQUIRED_ARGUMENT` found in `test_fixes`, e.g. in [ThemeData.raw](https://github.com/flutter/flutter/blob/637e5bce662fb43459d409e13ba5a7fb2c3fa930/packages/flutter/test_fixes/material.dart#L285-L288), each one re-requesting the same `TransformSet`s.

The humble proposal in [sdk/264983](https://dart-review.googlesource.com/c/sdk/+/264983) shrinks the time from the pre-commit of ~2min to around 55 seconds locally.

**Comment by bwilkerson** [comment]
Thanks for looking into this! I'll add feedback to the CL.
