### ISSUE TITLE
No warning for conditional function when functions have unmatched arguments or arguments are incorrect

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#50261]
Given the following:
```dart
void func(int n) {}

void func2(int n, int a) {}

void main() {
  final b = 0 > 1;
  (b ? func : func2)(1); // <~~ expected a warning/error 
}
```

Running the program above throws the following runtime error:

```
Uncaught TypeError: A.main__func2$closure(...).call$1 is not a functionError: TypeError: A.main__func2$closure(...).call$1 is not a function
```

I also discovered even if both functions have the same argument definition, there's no warning if the assignment is incorrect (e.g. `(b ? func : func)(1,2,3,4,5,5,6,7);`.   

**Dart Version:**
I tested this on DartPad with `Dart SDK 2.18.2`

**Additional Context:**
I don't have any issue here as I was just playing around after learning about the possibility of using conditional constructor such in:

https://github.com/dart-lang/sdk/blob/de55cba4d00cc4ea86e59b0b539467fb54240fe3/sdk/lib/core/date_time.dart#L919-L919

Though I think a warning or an error from the analyzer would be helpful.

**Comment by eernstg** [comment]
The type of `b ? func : func2` is `Function` because that's the least upper bound of `void Function(int)` and `void Function(int, int)` (btw, it's called the 'standard upper bound' because it actually isn't least in many cases, but I'll call it the least upper bound anyway, because that's so common).

Those two function types are unrelated (neither is a subtype of the other), and there is no function type which is a common supertype thereof, so the least upper bound is instead `Function`. This is basically `dynamic` for functions, and invocations of an object of type `Function` is allowed for arbitrary parameter lists, and the result is given the static type `dynamic`. The invocation may or may not succeed at run time, just like operations on a receiver of type `dynamic`.

So that's the reason why there are no errors and no warnings.

On the other hand, `(b ? func : func)(1,2,3,4,5,5,6,7)` should definitely give rise to a compile-time error, and I do also get such errors with 

```dart
void func(int i) {}

void main() {
  (b ? func : func)(1,2,3,4,5,5,6,7);
}
```

As far as I can see, you should be able to get a lint about invocations of functions of type `Function` if you enable the lint `avoid_dynamic_calls`.

**Comment by osaxma** [comment]
Thank you @eernstg for the explanation. It makes sense now.
