### ISSUE TITLE
discontinue publishing package:analysis_server_client

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#50262]
This is an issue to notify people that we may discontinue publishing `package:analysis_server_client`.

For background, `package:analysis_server_client` is a generated package which allows clients to start and speak to an analysis server instance. A bit more info:

- the package doesn't have usage from other pub.dev packages; https://pub.dev/packages?q=dependency%3Aanalysis_server_client
- until very recently, we'd gone perhaps 2 1/2 years without publishing it
- we generally want to switch our investment to the LSP protocol, as that's more widely used (investments there will leverage other work in the ecosystem and on other tools)

For recourse, once we discontinue the package, people who are currently using it could:
- continue to use the last published version
- fork the package and maintain that fork (it's not likely that the analysis server protocol will evolve radically)
- see if their use case could instead be satisfied with talking to the analysis server over the LSP protocol

**Comment by devoncarew** [comment]
If people are using `package:analysis_server_client` currently, we'd appreciate hearing about the specific use cases.

**Comment by modulovalue** [comment]
Thank you for the warning!

Are you implying that you are considering to eventually remove the Dart bindings to the analysis server api completely i.e. from pub and the sdk repo or is this just about removing them from pub? If the former, are there plans to replace the analysis server api completely with LSP? (i.e. should we expect that eventually new features will be made available only/first on LSP?)

**Comment by devoncarew** [comment]
> Are you implying that you are considering to eventually remove the Dart bindings to the analysis server api completely i.e. from pub and the sdk repo or is this just about removing them from pub? If the former, are there plans to replace the analysis server api completely with LSP?

This is just tracking publishing the `package:analysis_server_client` package; it's entirely independent of supporting the analysis server protocol in the analysis server. There's no change to the support there; about half the IDE clients use the analysis server protocol, and half use LSP; there's no change in support there.

> (i.e. should we expect that eventually new features will be made available only/first on LSP?)

Generally, the analysis server protocol is more feature complete then LSP, in terms of exposing what the analysis server can do. If you do have use cases you're using the analysis server protocol for, that you can't yet do with LSP, it would be interesting to hear them.

**Comment by modulovalue** [comment]
I had planned to expose the analysis server api (i.e. https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/api.html) in an editor that I'm working on, but technical challenges (unrelated to the api) have delayed that. 

I didn't consider the LSP implementation because it seemed to be less complete than the analysis server api, and because I didn't want the layer of indirection through Microsoft where any requested changes to the API seemed to be highly unlikely to be accepted.

I was hoping to be able to reliably depend on officially maintained bindings to the analysis server api through analysis_server_client, but because of https://github.com/dart-lang/sdk/issues/45311 I decided to focus on the aforementioned technical challenges first.

Now I see that you've been maintaining bindings under your name at https://pub.dev/packages/analysis_server_lib and it seems to me like both, analysis_server_lib and analysis_server_client are bindings to the same analysis server api (https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/api.html), is that correct? Why?

**Comment by devoncarew** [comment]
> Now I see that you've been maintaining bindings under your name at https://pub.dev/packages/analysis_server_lib and it seems to me like both, analysis_server_lib and analysis_server_client are bindings to the same analysis server api (https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/doc/api.html), is that correct? Why?

That's correct; `package:analysis_server_lib` predates analysis_server_client; I've maintained it as it's low cost, and has a more ergonomic API. I was originally using it to power some analyzer based CLI utilities (since supplanted by when we combined several tools into the dart CLI).

> I didn't consider the LSP implementation because it seemed to be less complete than the analysis server api, and because I didn't want the layer of indirection through Microsoft where any requested changes to the API seemed to be highly unlikely to be accepted.

LSP has the ability to escape custom commands - commands that both a client and a server understand, but that aren't part of any LSP standard.  This is how we integrate the functionality in the analysis server that goes above the base LSP support.

**Comment by devoncarew** [comment]
To update this issue: we've re-published `package:analysis_server_client` as `2.0.1` with messaging to indicate the package has been discontinued (https://pub.dev/packages/analysis_server_client).
