### ISSUE TITLE
[analyzer] extend conditional usage and `as`, for `definitely null`

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50275]
Updated based on the comment:

1. If the variable is conditionally used, then we should have `dead code`. This should apply for method/field/getter, etc.
```dart
void method() {
  int? b;
  b?.toRadixString(1);
}
```
2. If the variable is promoted with `as`, then we should have a hint, similar to [not_assigned_potentially_non_nullable_local_variable](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=not_assigned_potentially_non_nullable_local_variable#not_assigned_potentially_non_nullable_local_variable)
```dart
void as() {
  int? b;
  b as double;
}
```

<hr>
Original post:

~~When a nullable variable is used, it seems that `method invocation` and `as` are not verified for unconditional access.~~

E.g.
```dart
//void method() {
//  int? b;
//  b.toString();
//}
//void as() {
//  int? b;
//  b as double;
//}
```

In `getter` and `field`, there is [unchecked_use_of_nullable_value](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=unchecked_use_of_nullable_value#unchecked_use_of_nullable_value) as shown in the far below complete case.

I guess there are ~~three~~ two scenarios:

1. ~~Usage of the variable should be guarded, even if the variable is potentially initialized, so for the example, we should have `unchecked_use_of_nullable_value` for~~
```dart
//void method(int? b) {
//  b.toString();
//}
```
2. If the variable is ~~not initialized, and~~ conditionally used, then we should have `dead code`. This should apply for method/field/getter, etc.
```dart
void method() {
  int? b;
//  b?.toString();
  b?.toRadixString(1);
}
```
3. If the variable is ~~not initialized, and~~ unconditionally used, then we should have a hint, similar to [not_assigned_potentially_non_nullable_local_variable](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=not_assigned_potentially_non_nullable_local_variable#not_assigned_potentially_non_nullable_local_variable)
```dart
//void method() {
//  int? b;
//  b.toString();
//}
void as() {
  int? b;
  b as double;
}
```

This is related to https://github.com/dart-lang/sdk/issues/50211#issuecomment-1285235105

<details>
<summary>detailed case</summary>

```dart
void method() {
  int a;
  int? b;
  a.toString(); // not_assigned_potentially_non_nullable_local_variable
  b.toString();
}

void as() {
  int a;
  int? b;
  a as double; // not_assigned_potentially_non_nullable_local_variable
  b as double;
}

void getter() {
  int a;
  int? b;
  a.bitLength; // not_assigned_potentially_non_nullable_local_variable
  b.bitLength; // unchecked_use_of_nullable_value
}

class C {
  int field = 0;
}

void field() {
  C a;
  C? b;
  a.field; // not_assigned_potentially_non_nullable_local_variable
  b.field; // unchecked_use_of_nullable_value
}

void operator() {
  int a;
  int? b;
  a >> 1; // not_assigned_potentially_non_nullable_local_variable
  b >> 1; // unchecked_use_of_nullable_value
}
```
</details>

**Comment by lrhn** [comment]
The `int? b;` variable *is* initialized. Nullable local variables are automatically initialized to `null` if there is no initializer expression. So, being uninitialized does not apply here.

Further, the `b.toString()` method call is not prevented because `toString` is a valid method on both `int` and `Null`. It's safe. It returns `"null"` if called on `null`. If you try `b.toRadixString(16);`, you will get an error.
That is `b.toString();` is *valid*, so there should be no warning for it.

It's correct that the `as` cast is not checked. The language does not attempt to predict the value of a variable (or expression) in general, and the meaning of the `as` operator is to do a runtime check of the type of the value, independent of its static type.
From the language's perspective, there is nothing wrong with `b as double`. 

The analyzer could potentially be smarter than the language requires here, and warn you that the *value* of the variable will definitely be `null` at runtime, by doing extra value flow analysis, and therefore the cast will definitely fail at runtime. That's a different warning than the error messages reporting invalid use of a nullable expression in a scope expecting a non-nullable value. 
I'm not sure we should warn against `nullable as SomeType` in general, but if we can definitely see that the value won't be a `SomeType`, which we can if we know the value is one of a number of sealed system types, including `Null`, the we can say that the cast will definitely fail.
We track promotion from non-nullable to nullable, but apparently not being "definitely null".

**Comment by srawlins** [comment]
I think the struck through text has made this issue extremely hard to read. The first sentence in the issue summary above reads, "If the variable is conditionally used", but "the variable" has not been introduced yet.

If this is a request for multiple unrelated Hints or Lints or something, I think they should each be their own issue, so that we can have a straightforward discussion.

I'm guessing these proposals have something to do with variables which may be "definitely assigned" (or if we consider `int? a;` to be an assignment, then "definitely re-assigned"), "possibly assigned," and "definitely not assigned," so the text on what should be reported should include these possible states of a variable.

**Comment by asashour** [comment]
Thanks, and sorry for the confusion. #50308 and #50309 were raised. Please don't hesitate to change the title of them, as needed.
