### ISSUE TITLE
(Willing to PR) `for(final i in range(0, 10))` seems slower than `for(var i=0;i<10;++i)`, while Rust can make the former fast

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#50280]
From the following, it seems that, `for(var i = 0; i < 10; ++i)` generates simple assembly, while `for(final i in range(0, 10))` generates much longer (thus I expect slower) assembly.

On the other hand, the Rust equivalent, `for i in 0..n`, does generate quite minimal code.

https://godbolt.org/z/9v4c9KMEr

![image](https://user-images.githubusercontent.com/5236035/197422651-9cbb6be6-0c38-4ade-b81a-a0e56257259d.png)

**Comment by lrhn** [comment]
Dart does not have a `..` operator, or a platform provided `range` method.

That makes it harder to optimize the iteration of the `range` `Iterable`. Not completely impossible, it might be possible to inline both the iterable and its iterator, but it depends very much on the actual `range` function and the class definitions of the involved iterable and iterator classes.

Would it make sense to introduce a `..` operator which automatically introduces a *known* iterable and iterator? 
If it only works for numbers, then it's easy. Otherwise it requires a way to move to the next element, a way to support `+1`, which we don't have in general (using `operator+` may look weird, and it's not clear what it should do for arguments other than `1`).

**Comment by fzyzcjy** [comment]
@lrhn Hi thanks for the reply.

Looks like there are two separate things:

### 1. Introducing `..` operator

This looks like a syntax sugar. For example, kotlin (https://medium.com/kotlin-arsenal/kotlin-explained-custom-range-expressions-41537563f567) implements `a..b` as sugar of `a.rangeTo(b)` if I understand correctly.

### 2. Introducing built-in range for numbers and optimize it

If introducing `..` looks too hard, maybe firstly introducing a built-in `range` method for numbers and optimize it? Because it is used so frequently that it may deserve an optimization - everyone is writing a ton of `for(var i=0;i<N;++i)` (or `range` or `..`) everyday ;)

I totally agree it is hard to optimize arbitrary user-provided range function. So making a built-in one looks promising.

P.S. Many lang have support for this instead of `for(var i=0;i<N;++i)`-style as well:

* Rust: `1..N`
* Python: `range(1, N)` or `range(N)` etc
* Kolin: `1..N`

**Comment by fzyzcjy** [comment]
@lrhn So... what is the next step for me to do?

**Comment by lrhn** [comment]
I just tested, and I think simply adding "inline" pragma annotations should be sufficient.
Check: https://dartpad.dev/?id=8e11692f3f2a0d005b01e1c97044168c

When running this on the VM, it seems to get performance for the inline-annotated iterable that is equivalent to the plain `var i = 1; i < n; i++` loop (actually ~10% faster on JIT, equivalent when compiled to exe!)

That means that the problem here is not the VM's loop implementation, but its inlining algorithm.

(And either I'm using the wrong dart2js pragmas, or it doesn't work as well on the web.)

**Comment by fzyzcjy** [comment]
@lrhn Wow great job, you are so expert in Dart!

P.S. Numbers on my machine:

<details>

dartpad

```
non-inline :   528090.250 ops/ms @1310720000 ops
inline     :   528516.129 ops/ms @1310720000 ops
baseline   :  1045231.260 ops/ms @2621440000 ops
non-inline :   528090.250 ops/ms @1310720000 ops
inline     :   527665.056 ops/ms @1310720000 ops
baseline   :  1043566.879 ops/ms @2621440000 ops
non-inline :   528516.129 ops/ms @1310720000 ops
inline     :   530655.870 ops/ms @1310720000 ops
baseline   :  1046065.443 ops/ms @2621440000 ops
```

vm(mac)

```
non-inline :   738850.056 ops/ms @2621440000 ops
inline     :  1402589.620 ops/ms @5242880000 ops
baseline   :  1403340.471 ops/ms @5242880000 ops
non-inline :   728987.764 ops/ms @2621440000 ops
inline     :  1301608.739 ops/ms @2621440000 ops
baseline   :  1397356.077 ops/ms @5242880000 ops
non-inline :   735120.583 ops/ms @2621440000 ops
inline     :  1368898.172 ops/ms @5242880000 ops
baseline   :  1378254.469 ops/ms @5242880000 ops
```
