### ISSUE TITLE
Dart analysis server reports too many diagnostics

### ISSUE THREAD

**Issue by Waqar144** [dart-lang/sdk#50311]
I am using the [Kate text editor](https://kate-editor.org/). 

- Create a simple flutter app using `flutter create blah`
- Open `lib/main.dart`
- "Go to Defintion" on `Appbar`
- Thousands of diagnostics resulting in a massive slow down.... (Not expected)

How I have setup the server:

```json
"dart": {
   "command": ["dart", "$HOME/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot", "--lsp"],
   "url": "https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool",
   "rootIndicationFileNames": ["pubspec.yaml"],
   "highlightingModeRegex": "^Dart$"
}
```

Maybe I am missing some config that is needed to prevent this.

**Comment by bwilkerson** [comment]
I'm not familiar with Kate, but the language server should not be producing diagnostics when you navigate to `Appbar`.

What we will likely need in order to figure out why that's happening is a log of the traffic between the client (Kate) and the server. In other editors you can enable the creation of this log file by setting `dart.analyzerLogFile` to the path of the file. If that works for you, then close all of the files, open `lib/main.dart`, navigate to `Appbar`, copy the content of the log file, review the content and __remove any confidential information__, then send us the log.

@DanTup

**Comment by Waqar144** [comment]
After a bit of debugging in Kate, here's what I found. 

Kate manages servers like this: `Map[rootPath, Map[ServerLanguage(Dart), ServerHandle]]`. This is basically a hashmap inside a hashmap. servers are stored by rootPath and then by language.

So when I open `lib/main.dart` of the my project a new server is started with the rootPath `/path/to/project/`. So far everything is good. When I jump to `Appbar`, Kate tries to find the "rootPath" for appbar.dart. For rootPath identification we use the `pubspec.yaml` file so, wherever this file is, that becomes the `rootPath`. For AppBar this path is `"rootPath": "/home/waqar/flutter/packages/flutter"`. Since there is no server against this rootPath, it starts a new server with the said rootPath. The working directory of the process is also set to this path.

I have attached the reduced log file as the original was too big.

[dart_log.txt](https://github.com/dart-lang/sdk/files/9877156/dart_log.txt)

**Comment by Waqar144** [comment]
Hi. I ran `flutter update-packages` and yes, that fixes the diagnostics issue. 

However it's a bit weird since I thought `flutter upgrade` would take care of this and I upgraded just a couple of days ago.

**Comment by bwilkerson** [comment]
@goderbauer 

This seems like a friction point. I'm not sure why `flutter update-packages` is required by the Kate editor but isn't (as far as I know) required by other editors, but I thought I'd make you aware. It's possible that Kate isn't using LSP correctly, or that we have some work to do on the analysis server side. Investigations ongoing.

**Comment by srawlins** [comment]
> Since there is no server against this rootPath, it starts a new server with the said rootPath. The working directory of the process is also set to this path.

This is wrong. I don't believe any other clients do this, and Kate shouldn't either. I forget the correct terminology, but one analysis server can be analyzing multiple "context roots," right @bwilkerson ?

**Comment by bwilkerson** [comment]
I'm not entirely certain what the rules are for how clients are suppose to use LSP, but according to https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders, it appears that clients aren't required to support workspace folders. If that's the case, then it isn't clear to me what a client that doesn't support workspace folders is suppose to do when the user navigates to a referenced file.

But starting up a new language server definitely seems to me like the wrong approach.

Danny might have a more authoritative answer when he's back next week.

**Comment by Waqar144** [comment]
> This seems like a friction point. I'm not sure why flutter update-packages is required by the Kate editor.

I don't think it is required (unless I misunderstand something). Kate is using the server "as-is", there are no special config options or anything except for specifying the root.

If I don't specify any root i.e., just run the server it is working now. But the reason for specifying this root in the first place was that there were too many diagnostics which froze the editor. At that time (a few months ago), I thought this was because the server tried to scan everything and for some reason wasn't able to parse the files correctly due to being unable to find the necessary dependencies for a file. Coming from the c++ land, this is a very normal thing, compiler may fail to find an include and thus report errors and we are constantly helping the compiler/lsp with such stuff. Thus I settled on specifying a root and the option onlyAnalyzeProjectsWithOpenFiles. At that time, this worked. It worked even now except for the thing I reported above.

After updating the packages, it now works without specifying anything at all. So, could it be that my initial install of flutter somehow didn't go well and there was something broken in there which got fixed after running the `flutter update-packages` command? To me, it seems like that maybe the reason. The sad thing is that I may have made things worse for a lot of people if the initial config was incorrect (too many servers running) :(

**Comment by bwilkerson** [comment]
I should have been more clear.

What I was confused about is why the language server could correctly analyze the flutter packages while analyzing the class from the sample app, but couldn't correctly analyze them when one of them was opened via navigation.

I believe that the answer is that the language server that was analyzing the class from the sample app was correctly configured for development, but the (different) language server that was analyzing the class from the `flutter` package wasn't correctly configured because the Flutter packages were only configured to be used by apps and not for someone trying to develop the Flutter packages.

> ... unable to find the necessary dependencies for a file.

That can definitely happen in Dart as well. You have to run `flutter pub` to create a `package_config.json` file, which is how Dart tools find the dependencies used to compile code. In addition, some applications make use of code generators, and if those aren't run then required code might not exist.

> The sad thing is that I may have made things worse for a lot of people if the initial config was incorrect (too many servers running)

I don't know what "correct" means for Kate, but it would probably be more efficient if there were only one language server running.

In any case, it sounds like you're able to open the files you need to open without having incorrect diagnostics being reported, so I'm guessing that we can close this issue. Let me know if there's still something we can do to help here.

**Comment by DanTup** [comment]
Sorry for the delay. I believe Brian's explanation in the last comment above is accurate. The issue here is that when you're running a server that is analyzing your own package, there's a `package_config.json` that allows the analysis server to resolve `package:flutter` and co. However if you start up a new server that _only_ points at projects in the Flutter repository and and you have not run `flutter update-packages`, then there's is no available `package_config.json` to resolve those packages.

This is not actually unique to Kate, you can see the see thing in VS Code if you clone the Flutter repository and open up some of its packages without running `flutter update-packages`. For a server to analyze the Flutter repo _directly_ (which is what's happening when you're starting a new server for it), it's a requirement to have run `flutter update-packages`.

That said, I don't believe Kate should be spawning multiple servers here and it's not necessary for Kate to support multi-root folders to handle this properly. In VS Code if you perform the same steps (Go-to-Definition into a Flutter package from your own app), VS Code _will not_ add the Flutter project as an additional root, it will simply use the existing server and send requests for those referenced libraries without them ever being analysis roots. The server handles this fine (and this is the expected way to handle it - I wouldn't suggest adding new workspace roots for referenced files that are just being navigated to for code exploration - they should be added as roots only if the user adds those folders explicitly to their workspace).

So, if you can prevent Kate from starting a second analysis server when you jump to a file outside of the project and instead just have it use the existing server it already has, I think everything will work as you expected. The Dart server is capable of responding to all requests for files in referenced projects, without them being part of the workspace folders/workspace root.

**Comment by bwilkerson** [comment]
> So, if you can prevent Kate from starting a second analysis server ...

And if you can't, consider contacting the developers of Kate and make them aware of the issue.

**Comment by Waqar144** [comment]
> And if you can't, consider contacting the developers of Kate and make them aware of the issue

I can cause I am the developer of Kate ;p

Thank you everyone for clarifying.
