### ISSUE TITLE
[dart2js] why `Uint64List` does NOT use js' `BigUint64Array`, instead of throwing "`Uint64List not supported on the web`"

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#50332]
Hello,

I use Typed-data classes, a lot, but due to un-availability of `Uint64List` on the web platform, im forced to have, extra boilerplate,

JavaScript has [`BigUint64Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array), which seems like an equivalent of dart's [`Uint64List`](https://api.dart.dev/stable/2.18.3/dart-typed_data/Uint64List-class.html),

So, may i ask, is it possible to instruct the dart transpiler, to use `BigUint64Array`, instead of throwing the error "`Uint64List not supported on the web`"

Thanking you...

**Comment by rakudrama** [comment]
`BigUint64Array` is not suitable for `Uint64List`.
Accessing an element returns a JavaScript `BigInt`, and not an `int` as required by the `List<int>` interface of `Uint64List`.

`Uint64List` is not supported on the web because on the web, Dart `int` values are represented by JavaScript Numbers, which cannot represent all 64-bit int values. This is described in more detail at: https://dart.dev/guides/language/numbers.

If you wish to write code that is portable between native and web applications I would suggest avoiding `Uint64List` and use `Uint32List` instead.
