### ISSUE TITLE
[ddc] hide unsound flag if build requires it

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#50346]
Starting in Dart3.beta, the SDK will have a new build flag to determine whether an SDK supports unsound null safety on any of its commands. When the flag indicates that unsound mode is not supported, then DDC needs to provide an error if a user provides the `--no-sound-null-safety` flag.

**Comment by a-siva** [comment]
I have created https://github.com/dart-lang/sdk/issues/50348 for the VM which would have the build rule changes etc. Would this be the issue that you are referring to above ?

**Comment by nshahan** [comment]
I'm not sure. If I'm understanding correctly it seems like the DDC binary script will need to know if it is running as part of a Dart SDK that was built with a special build flag enabled. My expectation is that flag would be outside of the VM if it is passed as part of the SDK build.

**Comment by itsjustkevin** [comment]
@nshahan are we planning this work still as we have changed how we are approaching the `no-sound-null-safety` flag?

**Comment by sigmundch** [comment]
@nshahan - since we no longer include the unsound .dill files (since https://dart-review.googlesource.com/c/sdk/+/278999), is it fair to mark this one as complete?

**Comment by nshahan** [comment]
I'm closing the issue because at the moment I'm not planning any more work here but with the caveat that there is still work in progress in the Flutter repo.

Running DDC is only supported via running builds with the Flutter Tool or build_web_compilers. 

* Flutter Tools is close to removing support for `--no-sound-null-safety`. It landed but needed to be reverted.
  https://github.com/flutter/flutter/issues/118810

* build_web_compilers has removed support for `` in the version that works with Dart 3.0
  https://github.com/dart-lang/build/pull/3424

The unsound .dill files used by DDC have been removed from the packaged SDK.
