### ISSUE TITLE
analytics enabled in dartdev makes tool exit slower

### ISSUE THREAD

**Issue by Waqar144** [dart-lang/sdk#50360]
The title says it all.

```
$ time dart --help
[.... help output]

real    0m0.682s
user    0m0.369s
sys     0m0.105s

```

**Dart SDK Version:** Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"

**System**: AMD 4700U with 16G Ram and Samsung 980 SSD

**Comment by mraleph** [comment]
I'd say anything below a second is a reasonable time. 

Core issue here is that, unfortunately, these days it needs to run a bunch of Dart code to print help message and that takes time. Speeding this thing up is possible, but complicated - and likely not worth the effort.

**Comment by Waqar144** [comment]
> these days it needs to run a bunch of Dart code to print help message and that takes time

Dont know all the details, but that doesn't sound like a problem which should take that much time.

**Comment by Waqar144** [comment]
For anyone else who gets here, running `dart --disable-analytics` makes it much faster.

**Comment by mraleph** [comment]
@mit-mit is this intentional? should analytics maybe be batch uploaded instead of making every single CLI command slower? This might be especially relevant if users are sitting on slower networks.

**Comment by bkonyi** [comment]
I haven't looked at the analytics code in awhile, but I would assume it's all asynchronous. Maybe we're blocking waiting for the analytics network request to finish? I'll take a look once I have some spare time.

**Comment by devoncarew** [comment]
> For anyone else who gets here, running `dart --disable-analytics` makes it much faster. Also speeds up all other tools such as `dart format` and what not. Really sucks to have analytics if it's going to slow things down this much :/

What time differences are you seeing? I suspect you mean that theres a small fixed cost per command (and not a general slowdown)?

From here:

https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/lib/dartdev.dart#L300

We'll wait <= 200ms after a command finishes, in case there a is any analytics pings that haven't completed (and for FYI for other people seeing this issue, you can disable analytics generally via `dart --disable-analytics`).

**Comment by Waqar144** [comment]
> What time differences are you seeing? I suspect you mean that theres a small fixed cost per command (and not a general slowdown)?

with analytics disabled, it's taking 150 - 200 ms. When I enable it, its + 300 - 600 ms

**Comment by devoncarew** [comment]
Analytics should never delay the command exit by more than 200ms (hopefully frequently less than that). This is intentional but could definitely be improved - that analytics call isn't adding any user value for that specific command (though hopefully, value in aggregate for broad tool improvements). 

We can use this issue to track improvements here. As Slava says, that could be an un-sent queue on disk, reducing the explicit delay value, ...

**Comment by jcollins-g** [comment]
The new unified_analytics may have similar problems, I'll try looking at this after the cut.

**Comment by jcollins-g** [comment]
This can be reproduced at head.   unified_analytics doesn't make things worse, but doesn't make them better either.

**Comment by jcollins-g** [comment]
Closing as fixed, with the caveat that the "fix" biases us toward dropping analytics on the floor rather than impacting the interactive performance of the command for our users.    Without writing to disk, the legacy analytics does a pretty good job of avoiding I/O blocking and other common reasons for delays.
