### ISSUE TITLE
Find usages is very slow on methods in base classes with lots of subclasses 

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#50365]
To reproduce using the analysis server codebase:

1. Open `AbstractSingleUnitTest`
2. Invoke "Find Usages..." on the `newFile` method declaration

It takes a _loooonnnng_ time to return results.

/fyi @scheglov

**Comment by DanTup** [comment]
I noticed this too, s I had a quick poke around. Looks like this in DevTools CPU profiler:

![Screenshot 2022-11-16 at 17 50 29](https://user-images.githubusercontent.com/1078012/202257212-9239cfd2-b49e-4a42-a210-60572b268102.png)

[dart_devtools_2022-11-16_17_50_38.749.json.txt](https://github.com/dart-lang/sdk/files/10024496/dart_devtools_2022-11-16_17_50_38.749.json.txt)

I thought this might be similar to an issue we fixed elsewhere, where we'd search the same files in each driver unnecessarily. I think that is the case, but there's much more than that. I created an empty project with this:

```dart
class A {
  void dannyTestMethod() {}
}

class B extends A {
  @override
  void dannyTestMethod() {}
}

class C extends A {
  @override
  void dannyTestMethod() {}
}

class D extends A {
  @override
  void dannyTestMethod() {}
}

class E extends A {
  @override
  void dannyTestMethod() {}
}

class F extends A {
  @override
  void dannyTestMethod() {}
}

class G extends A {}
class H extends A {}
class I extends A {}
class J extends A {}
```

I then did Find References on `dannyTestMethod` in `class A`. I added some logging, and the log file is here:

[instrum copy.txt](https://github.com/dart-lang/sdk/files/10024657/instrum.copy.txt)

If I grep for "Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for " I see:

```
1668622855450:Info:379196685 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for A
1668622855510:Info:206824015 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for C
1668622855563:Info:961095418 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for G
1668622855569:Info:22450448 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for B
1668622855581:Info:562935199 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for J
1668622855587:Info:789755213 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for I
1668622855589:Info:817556342 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for D
1668622855595:Info:653416624 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for F
1668622855597:Info:962874413 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for E
1668622855601:Info:44330804 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for H
1668622855605:Info:288395835 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for dannyTestMethod
1668622855611:Info:274140100 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for dannyTestMethod
1668622855613:Info:376230081 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for dannyTestMethod
1668622855617:Info:680882967 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for dannyTestMethod
1668622855620:Info:133690820 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for dannyTestMethod
1668622855631:Info:521033773 Searching /Users/danny/Dev/Dart SDKs/nightly/lib/core/core.dart for dannyTestMethod
```

So we're opening every known file to search for the name of every class in the hierarchy, collecting an `Element` for each of those classes that has a definition for the method, and then searching through every file for each of those elements (if I understand correctly, each of those will return the same results, since they're searching for the same name by text?). This is then duplicated for each driver (in my test here I only had one, but when working on the analyzer I have around 7 projects open).

When searching for `newFile` in @pq's sample above, I saw over 100 instance of each file being searched (up till the point I terminated, when the log file was about 70MB).

I'm curious why the search for the names of the subclasses (we found the original list of subclasses from an index, I'm not sure what this search is doing), and I think we could avoid the duplicates of searching for the same name multiple times for each file, and then also searching the same referenced files in each driver (similar to we fixed elsewhere).

If nobody else is actively looking at this, I can try and do a little more digging soon.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
I think it is after to find files that reference a name first, and look into indexes for files.
First, to check that a file contains a name is a hash map check `O(1)`, and in index it is binary search `O(log(N))` (a few of them).
Second, name sets for files are in memory, and indexes have to be read (cached, some number of them), and at least partially decoded.
That is not to say that there are no performance issues, obviously there are, and I see it myself, but it might be on a different level, e.g. when we search to subtypes we have a cascade of searches, and even though each of them is fast, we have too many of them.

**Comment by DanTup** [comment]
> Second, name sets for files are in memory

Ah, I wondered about that, there's probably less duplication than I though there then. Although, in the screenshot above the `contains()` call on the hash set seems like a reasonably significant portion of the total time (maybe 1/4?). I'm not sure what `_getKeyOrData` is doing though.


> e.g. when we search to subtypes we have a cascade of searches, and even though each of them is fast, we have too many of them.

Yeah, I think there's a lot of duplication in the searching of files there. Eg. if we get 30 subtypes and need to search for 30 elements, each one of those will do the same _name_ search across every file first (since it's searching for the method name which is the same in each override) before going to the index looking for the specific element. It would probably require some refactoring, but for cases where there are lots of subtypes there may be decent gains to be had by sharing the "files with this name" across each of those.

I didn't get chance to dig too deeply today (I was brain-dumping here as a reminder of what I was doing), but I'll try and get some better timings and will ping back here for input if/when I do.

**Comment by DanTup** [comment]
It turns out the time spent searching isn't looking for the method, it's in searching for the subtypes. There are a lot of subtypes of `AbstractSingleUnitTest` and for each "leaf" subtype it still has to do a search to see that it doesn't have its own subtypes. It's possible making these private or `@sealed` would allow us to shortcut a lot of work there, although that doesn't improve the general case.

So all the time spent in the `Set.contains()` was not repeated searching for `newFile`, it's mostly searches for each subtype name (of which there are several thousand, which is done for each file).

In my testing (finding references via LSP for `AbstractSingleUnitTest.newFile` in a workspace containing `analysis_server`, `analyzer`, `analyzer_plugin`, `analysis_server_client`, `analyzer_cli`, `analyzer_utilities` and `dartdev`, running from latest source/bleeding edge SDK on a MacBook) the whole operation is around 42s, and about 41s of that is just getting the list of all subtypes (specifically, the execution of `SearchEngine.searchAllSubtypes(InterfaceElement)`).

```
(name: request, elapsed: 0:00:42.040102, elapsedSelf: 0:00:00.085876)
  (name: computeSuggestions, elapsed: 0:00:41.954226, elapsedSelf: 0:00:00.001418)
    (name: _getRefElements, elapsed: 0:00:41.690776, elapsedSelf: 0:00:00.004823)
      (name: Searching all subtypes, elapsed: 0:00:41.673863, elapsedSelf: 0:00:00.000762)
        (name: Searching for subtypes of AbstractContextTest, elapsed: 0:00:11.388808, elapsedSelf: 0:00:03.586557)
          (name: Searching for subtypes of AbstractSingleUnitTest, elapsed: 0:00:07.313394, elapsedSelf: 0:00:00.047741)
// ...
```

Full log is here: [perflog.txt](https://github.com/dart-lang/sdk/files/10032363/perflog.txt)


> in index it is binary search `O(log(N))`

I think I had originally misunderstood what indexes we have. I thought we had a single index that could tell us the subtypes of a given type, but from reading this code I think that was incorrect and the indexes are per-file (and so we need to figure out why indexes to check).


So I'm less sure there's low-hanging fruit here (perhaps unsurprisingly because it likely would've been picked).

**Comment by bwilkerson** [comment]
> I thought we had a single index ...

Well, that's kind of a question of optics. In one sense we _do_ have a single index. We just keep the portion of the index contributed by one library, `L`, separate from the portions of the index contributed by other libraries. The reason for this architecture is to make it faster to incrementally update the index. When `L` changes, all we need to do is replace the portion of the index associated with `L`.

The alternative is to have the information contributed by `L` distributed across a single monolithic data structure, but that means we'd need to first remove all of the information contributed by the older version of `L` and then add the information from the modified version of `L`. Given that we re-analyze `L` after every few keystrokes, that's a fairly inefficient approach.

> So I'm less sure there's low-hanging fruit here ...

Well, there might be. The index stores relationships, so if we have a class `B extends A` defined in `L`, in the file for `L` we'll record the relationship `<B extends A>`. When we want the immediate subtypes of `A` we search for relationships of kind `extends` with `A` as the right-hand operand.

But we _could_ instead record a relationship of the form `<B isSubtypeOf A>` for every supertype of `B`. It would make the file bigger, but if we then search for relationships of kind `isSubtypeOf` for a given type we'll get all of the subtypes in a single pass. I don't know what the size difference would be, but it might be worth exploring.

**Comment by DanTup** [comment]
> But we could instead record a relationship of the form `<B isSubtypeOf A>` for every supertype of B. 

I'm not sure I understand the difference between recording `<B extends A>` and `<B isSubtypeOf A>` - do you mean that this would be recorded in `A`'s index file (whereas `<B extends A>` is recorded in `B`'s index file)?

If so, does this mean modifying `B`'s source file would potentially now invalidate `A`'s index file?

**Comment by bwilkerson** [comment]
If we have the following files (with imports omitted for brevity):

`a.dart`
```
class A {}
```
`b.dart`
```
class B extends A {}
```
`c.dart`
```
class C extends B {}
```
we would currently produce the following relationships for `b.dart`:
```
<B extends A>
```
and for `c.dart`:
```
<C extends B>
```
What I'm proposing is that we add relationships so that we have for `b.dart`:
```
<B extends A>
<B isSubtypeOf A>
```
and for `c.dart`:
```
<C extends B>
<C isSubtypeOf A>
<C isSubtypeOf B>
```
If we then search for subtypes of `A` we find both relationships in a single pass.

**Comment by DanTup** [comment]
> and for `c.dart`:
>
> ```
> <C isSubtypeOf A>
> ```

Doesn't this add a dependency on `b.dart` now? (eg. I can change the class that `B` extends and this would be wrong?)

I also think this would require that we search the index for `c.dart` when looking for `A` (to pick up `C`), but (IIUC) right now we first scan for "files that contain references to `A`" before looking in the index, and `c.dart` does not contain `A`? (as far as I can tell, the name list is built from the AST in `_ReferencedNamesComputer`).

(I may be misunderstanding, I'm not too familiar with this area of the code, although that's something I'd like to fix!)

**Comment by bwilkerson** [comment]
I knew it sounded too good to be true, I just hadn't figured out why. You're right, it adds a dependency that we can't deal with in a performant way when it comes to incrementally updating the index. Ok, back to the drawing board...

**Comment by DanTup** [comment]
Here's two other thoughts I had but haven't tested and not sure if sound:

## 1. Do we need to search _all_ known files for subtypes?

We're currently searching 36,000 files for each class name in the hierarchy when searching for subtypes. I believe these are "all known files" which include packages that analyzer/server depend on. Is it possible for anything in a projects dependencies to have subtypes (this suggests the packages depend on each other?). Would it be correct if we only searched things that depended on (directly or indirectly) the packages that contain the class we're looking for subtypes for? (and if so, do we have - or can we compute - that without throwing away any savings)?


## 2. Could we do the member name search before the subtypes search?

Currently we're searching (by searching, I mean "checking the `referencedNames` hashset") all (36,000) files for each class in the hierarchy (to check if it has subtypes). Although each file search is ~`O(1)` we're doing it `num_drivers * total_known_files * num_classes_in_hierarchy` times. At the end, we have a list of files that contain classes in the hierarchy (let's say 150) and then we search for the member name (`newFile`) in each of those files (and then check their indexes).

If we instead did the name search first `newFile`, in a single search of the 36k files, we would _probably_ reduce the number of possibilities to a much smaller number than 36k, and then if we searched only those for the hierarchy, it could be much faster. Even if 50% of all files contained `newFile` (seems very unlikely), it could cut that part of the search in half.

Even in the very worst possible case for doing this (every single file contains the method name - perhaps `toString()`) it seems like this may only add approximately one full search (a check of the `referencedNames` hashset for every known files).

**Comment by bwilkerson** [comment]
> We're currently searching 36,000 files for each class name in the hierarchy when searching for subtypes.

I think we're also searching for supertypes because I think we look for references where the type of the reference is a supertype of the starting type. I might be mistaken about that though.

> Is it possible for anything in a projects dependencies to have subtypes (this suggests the packages depend on each other?).

I haven't tested this in terms of normal dependencies, but I know that if P1 has a normal dependency on P2 it's allowed for P2 to have a dev dependency on P1, so I believe that the answer is yes.

> 2. Could we do the member name search before the subtypes search?

I think that's a great idea. I agree that it might be worse in the worst case scenario, but I suspect that most of the time it will reduce the number of libraries we need to search.

The other thought I had was that we need to make sure that we're caching the index files so that if we need to look in the same file multiple times as we're traversing the type hierarchy we only need to load it once.

**Comment by DanTup** [comment]
> I think we're also searching for supertypes because I think we look for references where the type of the reference is a supertype of the starting type. I might be mistaken about that though.

Yep, this is correct. We search the entire hierarchy regardless of the starting type. I think collecting the supertypes is very fast (because it can be traversed from the elements), but ofc it may introduce additional types we need to find subtypes for.

> I haven't tested this in terms of normal dependencies, but I know that if P1 has a normal dependency on P2 it's allowed for P2 to have a dev dependency on P1, so I believe that the answer is yes.

Oh, I see. That might make it more complicated to prune packages, although perhaps there's still some gains here. We could revisit this depending on the impact the other change has.

> I think that's a great idea. I agree that it might be worse in the worst case scenario, but I suspect that most of the time it will reduce the number of libraries we need to search.

Cool, I'll do some testing of this to get some numbers then to see what sort of impact it has for the example above.


> The other thought I had was that we need to make sure that we're caching the index files so that if we need to look in the same file multiple times as we're traversing the type hierarchy we only need to load it once.

I'll check this too - although right now I think the index loading is a very small portion of the overall time (because after the `referencedNames` check there aren't a huge number of files left to look in.

**Comment by scheglov** [comment]
Look at `FileSystemState.collectAffected(String path, Set<FileState> affected)`. We use it for invalidation right now, but it could potentially be used also to find files that could potentially reference anything in some file; and then continue using only this set of files to search for transitive subtypes. We will still filter this set by presence of a name, because I still believe that check in a set is faster than looking into a potentially on-disk index, and the cost of unpacking this index.

Then, there is a cost of unpacking indexes again and again. Search is done right now as one-off operation, even though some searches cause a cascade of `Search` class operations, and sometimes the same files and indexes are consulted, we don't cache anything between searches. Theoretically this could be done, but it has to be done carefully.

**Comment by DanTup** [comment]
> 2. Could we do the member name search before the subtypes search?

I'm not long sure this is sound. Given:

- `class A { void foo() {} }` in `a.dart`
- `class B extends A {}` in `b.dart`
- `class C extends B { void foo() {} }` in `c.dart`

I think if we filter by the member name (`foo`) we will never look in `b.dart` when searching for subtypes, and never discover `B` or `C`, so then fail to find the reference in `c.dart`. It's possible there are ways around this (when searching `c.dart`, realise that it has `A` in the supertype chain) but I'm not sure that will be good for performance.

However, ...

> Look at `FileSystemState.collectAffected(String path, Set<FileState> affected)`.

This seems promising. I had a go at using this at https://dart-review.googlesource.com/c/sdk/+/271460 and it reduces the time for this search from ~40s to ~20s and there's only one test failure (see comments on the review). However, I do think it may have added a few seconds of overheard to the faster searches too. I'll do some more testing/profiling once I've got the test passing (to ensure the behaviour is exactly correct).

**Comment by jensjoha** [comment]
In VSCode I don't have (I think) anything called "Find usages", but asking to “Find all references” on method `newFile` in the specified files in my workspace with 8 folders (`pkg/analysis_server`, `pkg/analysis_server`, `pkg/analysis_server`, `pkg/analysis_server_client`, `pkg/analyzer`, `pkg/analyzer_cli`, `pkg/analyzer_plugin`, `pkg/analyzer_utilities`, `pkg/_fe_analyzer_shared`, `pkg/front_end`) takes 47+ seconds (48305 ms, 47781 ms, 47777 ms from the “Analysis Server Diagnostics” page).
Asking for “show call hierarchy” for the same thing in the same scenario also takes 47+ seconds (48024 ms, 48244 ms, 47916 ms).

With a stack of 4 CLs (i.e. measured on https://dart-review.googlesource.com/c/sdk/+/271901) this instead becomes:
“Find all references”: ~3.6 seconds (3653 ms, 3582 ms, 3460 ms).
“Show call hierarchy”: ~4 seconds (4086 ms, 3911 ms, 3954 ms).

**Comment by DanTup** [comment]
Nice! I had originally looked and concluded there was no work duplicated across drivers, but I was apparently looking at the final member search (which allocates each file to a driver) and overlooked the subtype part.

Those gains are _far_ bigger than the change I had started, so I'll wait until these are reviewed and landed before figuring out if it's still worth trying to do what that change was doing (which was to try and compute a smaller set of files to search up-front rather than searching them all).

**Comment by bwilkerson** [comment]
I'm proactively closing this. It can be reopened if someone knows of additional work that needs to be done.
