### ISSUE TITLE
Possible regression with async* generator with dart 2.18.0 changes. Not yielding all events with yield*.

### ISSUE THREAD

**Issue by Pacane** [dart-lang/sdk#50379]
## Environment details:

Before we were using Dart 2.17.6 with Flutter 3.0.5
Now we're using Dart 2.18.2 with Flutter 3.3.4.

Got this issue running tests using the dartvm. I haven't ran the test cases against web at that time.

## Problem

Before [dart 2.18.0 async* changes](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dart-vm) We were using this implementation to create a stream seeded with an initial value:
```dart
Stream<T> createSeededStream<T>(T initialValue, Stream<T> stream) async* {
  yield initialValue;
  yield* stream;
}
```

Which used to work fine for us. I believe we could get this to work fine for both Streams and BroadcastStreams. However since the 2.18.0 change, this implementation didn't work anymore. Our test cases started failing, dropping sometimes the initial value, sometimes the first values of the yielded stream.

We found that using this implementation fixes the issue, but I'm not quite sure why it's not working all the time anymore.

```dart
Stream<T> createSeededStream<T>(T initialValue, Stream<T> stream) =>
    Stream.value(initialValue).mergeWith([stream]);
```

I believe the issue might lie in the fact that `stream` could be a broadcast stream, and that sometimes in a test environment the initial elements emitted in the stream are emitted too fast perhaps?

I'm not sure how/where to go from here to help you figure out if there is a regression for real, but these were our observations.

cc: @kevmoo

**Comment by kevmoo** [comment]
In what environments are you hitting this? web? native?

CC @lrhn – who likely has some context here!

**Comment by lrhn** [comment]
It shouldn't be possible to drop values. If there is a `yield` in the `async*` method, then it will definitely yield a value.

What might happen here is that the initial `yield` now waits until the value has been *delivered* before it continues, where before it would fire-and-forget the event and immediately start listening on `stream` afterwards. (That behavior was a [bug](https://github.com/dart-lang/sdk/issues/34775)).

If `stream` is a broadcast stream, then any events emitted by `stream` during that delay will not be part of the `async*` stream, because they happen before reaching the `yield* stream;`.


There may also be other delays involved. Calling `listen` on an `async*` stream doesn't start the body running immediately, so even doing `createSeededStream(seed, stream).forEach(print)` may drop events emitted by `stream` between the call to `forEach` and the body starting to run.


A possible workaround might be:
```dart
Stream<T> createSeededStream<T>(T initialValue, Stream<T> stream) async* {
  var c = StreamController<T>(sync: true);
  stream.pipe(c).ignore(); // Buffer events happening until yield*
  yield initialValue;
  yield* c.stream; // Emit events of `stream`, buffered ones first.
}
```

**Comment by mraleph** [comment]
I am going ahead and close this issue given that it seems to have been answered.
