### ISSUE TITLE
Dynamic values initialized to null can't be reassigned a non-null value (sometimes)

### ISSUE THREAD

**Issue by oravecz** [dart-lang/sdk#50371]
### Problem Statement

When using a map of `<String, dynamic>`, the dynamic values are initialized to `null`.

If the `dynamic` value is a top-level property in the map, it's value can be reassigned to an `int`, however
if the `dynamic` value is nested in the map and initialized with an `int` value, its value can be reassigned to an `int` value, however
if the `dynamic` value is nested in the map and initialized with a `null` value, its value cannot be reassigned to an `int` value.

The following exception is raised
```
type 'int' is not a subtype of type 'Null' of 'value'
```

### Example code

https://dartpad.dev/?id=b7b4358a0c15fc929afdab0cda0cc794

```dart
void main() {
  try {
    var foo1 = <String, dynamic>{'bar': null};
    foo1['bar'] = 1;
    print('foo1 succeeded');
  } catch (e) {
    print('foo1 failed');
  }

  try {
    var foo2 = <String, dynamic>{
      'bar': {'baz': 0}
    };
    foo2['bar']['baz'] = 1;
    print('foo2 succeeded');
  } catch (e) {
    print('foo2 failed');
  }


  try {
    var foo3 = <String, dynamic>{
      'bar': {'baz': null}
    };
    foo3['bar']['baz'] = 1;
    print('foo3 succeeded');
  } catch (e) {
    print('foo3 failed, $e');
  }
}
```

**Comment by oravecz** [comment]
There is a workaround

```dart
    var foo3 = <String, dynamic>{
      'bar': {'baz': null as int?}
    };
    foo3['bar']['baz'] = 1;
```

The `null as int?` type declaration is flagged as an unnecessary cast by the analyzer

**Comment by julemand101** [comment]
If you look at the runtime for the nested map in third example, you can see it gets assigned the type `_InternalLinkedHashMap<String, Null>` which is the reason why it does allow you to put `1` inside it.

Just because the main map is defined to contain `dynamic` does not make Dart automatically assume all maps inside this map should be defined as `Map<dynamic, dynamic>`. Instead, the nested maps is seen as separate created maps which tries to determine the type based on the provided input values.

As you have observed, the problem is fixed if you tell Dart what type you really mean when creating the map with input values. Another way to do this is the following
```dart
    var foo3 = <String, dynamic>{
      'bar': <String, int?>{'baz': null}
    };
```
