### ISSUE TITLE
functional programming support 

### ISSUE THREAD

**Issue by sanba-anass** [dart-lang/sdk#50467]
it will be very useful to extend dart to support functional programming features like function composition and Monads and more :)

**Comment by lrhn** [comment]
Dart has first class functions, so *to some extent* you can do functional programming.

What Dart doesn't have is the ability to abstract over parameter lists. That's mainly a symptom of Dart actually having functions taking multiple parameters, instead of unary functions taking records as argument. Dart does not (yet) have records, so that wouldn't work.

Also, for monads, it's not possible to abstract over function type constructors.

If you limit yourself to unary functions, you can do all the usual functional programming compositions:
```dart
extension UnaryFunctions<R, P> on R Function(P) {
  R Function(T) compose<T>(P Function(T) other) => (T value) => this(other(value));
}
// ...
int increment(int value) => value + 1;
var add2 = increment.compose(increment);  
```

Monads in the *abstract* are not really on the table, but you can define your own monads if you want to. Some would say that the `Future` type is one.

**Comment by vsmenon** [comment]
Closing as I don't see anything actionable here.  You can open specific language feature requests at https://github.com/dart-lang/language/issues/new/choose
