### ISSUE TITLE
[dart2wasm] Incorrect extension method tear-off equality

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#50475]
With https://dart-review.googlesource.com/c/sdk/+/269882 (#50429) method tear-off equality works as expected.

However the spec for static extension methods specifies [extension method tear-offs differently][1]: (emphasis mine)

> Torn off extension methods are never equal unless they are identical. Unlike instance methods, which are equal if it's the same method torn off from the same object (unless it's an instantiated tear-off of a generic function), torn off extension methods may close over the type variables of the extension as well. To avoid distinction between generic and non-generic extensions, **no two torn off extension methods are equal, even if they are torn off from the same extension on the same object at the same static type**.

Currently this doesn't hold in dart2wasm. Example: (with the CL linked above, should be submitted soon)

```dart
class A {
  void f() {}
}

extension X on A {
  void g() {}
}

void main() {
  final a = A();
  print(a.f == a.f); // true as expected
  print(a.g == a.g); // true, should be false
}
```

The tricky part with fixing this is that we don't have extension methods in kernel, they're desugared away. Assuming we got everything else right in dart2wasm (equalities of functions, closures, and tear-offs), then it's possible that the specified part quoted above works with AOT and JS because those targets never consider two functions equal. This was previously documented in `Function` class documentation as:

> Different evaluations of function literals never give rise to equal function objects. Each time a function literal is evaluated, it creates a new function value that is not equal to any other function value, not even ones created by the same expression.

Which, as discussed in #50429, not part of the language specification, and we actually want to allow a compiler to lift a closure to the top-level. (#50126)

I will check:

- How extension methods are compiled to kernel. (I'm guessing as static methods or functions)
- How equalities on those kernel constructs should work according to the spec
- Whether the specified extension method equality is consistent with the equalities of those kernel constructs

[1]: https://github.com/dart-lang/language/blob/master/accepted/2.7/static-extension-methods/feature-specification.md#tearoffs

**Comment by eernstg** [comment]
> The tricky part with fixing this is that we don't have extension methods in kernel, they're desugared away

So the declaration of an extension method `E.m` in the surface language is transformed into a top-level function declaration, say, `extension_E_m`, and presumably `extension_E_m` accepts an extra argument which is the object that is accessed using `this` in the body.

However, I would expect that desugaring step to be unimportant, relative to the behavior of operator `==` on extension method tear-offs: An extension method tear-off is specified to be the value of a function literal, it is not just the value of the constant expression `extension_E_m`.

The reason why it can't be the top-level function is that it needs to close over the receiver. So the actual tear-off would be something like `<...>(args) => extension_E_m<...>(_this, args)` rather than simply `extension_E_m` (and this function literal also needs to take various type arguments into account, because the given tear-off of `E.m` could receive some actual type arguments, as in `E<T1..Tk>(myReceiver).m()`).

Anyway, there are no special rules about the equality properties of these function literals.

I would expect that if `f1` and `f2` are function objects obtained by evaluating two function literals (could be the same syntax or different syntax), with no special rules about `operator ==`, then `identical(f1, f2)` is true if and only if `f1 == f2` is true. In other words, I'd expect function objects obtained from function literals to have the behavior of `operator ==` from `Object`, just testing identity. (It's only instance method tear-offs that have a special `operator ==`.)

I would hope that there is no need to do anything "extra" in order to get that behavior.

**Comment by askeksa-google** [comment]
> I would expect that if `f1` and `f2` are function objects obtained by evaluating two function literals (could be the same syntax or different syntax), with no special rules about `operator ==`, then `identical(f1, f2)` is true if and only if `f1 == f2` is true. In other words, I'd expect function objects obtained from function literals to have the behavior of `operator ==` from `Object`, just testing identity. (It's only instance method tear-offs that have a special `operator ==`.)

This is currently not the case in dart2wasm as implemented in https://dart-review.googlesource.com/c/sdk/+/269882, which handles all of the non-extension cases (after https://dart-review.googlesource.com/c/sdk/+/269721).

We consider two closures equal if they have the same vtable and the same context (for tear-offs, the context is the receiver). This is consistent with the general rule that if function objects compare equal, they must have the same behavior.

The vtable is the same if the closures originate from the same function literal or local function, or if they are tear-offs of the same method.

Contexts are aggressively shared, so two functions that capture the same variables can easily end up having the same context.

To achieve the desired non-equality for extension method tear-offs through desugaring, the desugaring would have to transform the tear-offs into some other language construct that guarantees non-equality. But since apparently no such non-equality requirement exists outside of extensions, this seems like a difficult task.

To achieve the "`identical(f1, f2)` is true if and only if `f1 == f2` is true" property in dart2wasm, it seems we would either have to cut down on the sharing of contexts, or to add some extra dummy value to closures just to be able to tell them apart. Both of these scenarios would impact performance. Alternatively, we could have a different implementation class for tear-offs than for other closures and only override `operator ==` for tear-offs. This would likely not have severe performance implications, but it would be a messy change, since many parts of the compiler and runtime assume that there's only one kind of closure.

**Comment by eernstg** [comment]
@askeksa-google wrote:
> To achieve the "identical(f1, f2) is true if and only if f1 == f2 is true" property in dart2wasm ...

We just discussed this over lunch. IIUC, it would be doable to change operator `==` of function objects such that it (1) returns true if the two function objects are identical (`identical(f1, f2)`), and otherwise (2) return false if the two function objects have different code (pseudo code: `f1.vtable != f2.vtable`), and (3) returns false if they have different context (pseudo code: `f1.context != f2.context`), and finally returns (pseudo code) `f1.context is an object` (that is, return true if `f1` and `f2` are both instance method tear-offs, otherwise return false).

@askeksa-google, does this match the approach that you considered?

**Comment by askeksa-google** [comment]
Yes. A sequence like that would be a good way to implement it, I think.

**Comment by osa1** [comment]
> IIUC, it would be doable to change operator == of function objects such that it (1) returns true if the two function objects are identical (identical(f1, f2)), and otherwise (2) returns false if the two function objects have different code (pseudo code: f1.vtable != f2.vtable), and (3) returns false if they have different context (pseudo code: f1.context != f2.context), and finally returns (pseudo code) f1.context is an object (that is, returns true if f1 and f2 are both instance method tear-offs, otherwise returns false).

I implemented this in https://dart-review.googlesource.com/c/sdk/+/270380.

**Comment by osa1** [comment]
Another idea that we discussed was to have different classes based on how many different comparisons we need:

1. One class for top-level functions, static methods, and closures we want functions to be identical to be equal
2. Another class for instance tear-offs we check context (`this`) and vtable

So we could have two classes and implement `operator ==` differently, instead of having one that handles all cases. That would probably make `operator ==` a bit faster (we don't need to check if context is an object, i.e. function is an instance tear-off), but it would require some refactoring in the code generator.

For now it should be OK to have one function class and one `operator ==` implementation that handles all cases. We can optimize later if needed.
