### ISSUE TITLE
[analyzer] incorrect caching of diagnostics

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50496]
It seems that the analyzer result is not matching the code.

Based on this [test](https://github.com/dart-lang/sdk/blob/eaa2ea9aab4ca24eccdbd62bec8ce86f902233ab/pkg/analyzer/test/src/diagnostics/mixin_application_no_concrete_super_invoked_member_test.dart#L229-L249), let's agree that:

```dart
abstract class A {
  void set foo(_);
}
mixin M on A {
  void bar() {
    super.foo = 0;
  }
}
abstract class X extends A with M {}
```
gives a diagnostic.

But commenting `super.foo = 0;` would not trigger it.

And the `void` before the setter has no effect.

(Those results are taken from the test case after modification).

Now, on the below video, there are many cases where the above situations are not correctly handled.

`Dart SDK version: 2.19.0-406.0.dev (dev) (Tue Nov 15 20:25:04 2022 -0800) on "windows_x64"` and on [master](https://github.com/dart-lang/sdk/commits/eaa2ea9aab4ca24eccdbd62bec8ce86f902233ab).

(you may not have exact scenario, because for example, I tested `xoo` before taking the recording, so its diagnostic seems to be saved and shown in the recording).

https://user-images.githubusercontent.com/2410127/202467403-403e25b5-8061-4807-a72f-d1092d932ef5.mp4

**Comment by bwilkerson** [comment]
There are a couple of possibilities that I can think of for this behavior.

One is what the title suggests, which is that we don't correctly cache the summary so that server sometimes gets a mismatched result causing it to send invalid results to the client.

Another is that server has some non-determinism around when it applies an override and when it performs analysis that causes the cache key to get out of sync with the file content being analyzed.

Or similarly, but slightly different, your IntelliJ might be saving periodically and the problem might be related to watch events.

Do you have auto save enabled? If so, is the behavior reproducible if you disable it?

Is the behavior reproducible if you slow down the changes? That might help us see whether it's a timing issue.

If you haven't yet done so, can you enable the instrumentation log and see what the communication between the client and server looks like? That might give us some clues as to where the bug is likely to be. (If you decide to post some portion of the instrumentation log, please be aware that it might contain PII that you'll need to remove before posting.)

It is possible in our test framework to create a file, analyze it, modify it, and then re-analyze it. If the behavior isn't time-dependent and is entirely within the server, this should reproduce what you're seeing in a way that would allow us to track it down in the debugger.

**Comment by asashour** [comment]
Thanks for the hints. From what I see:

- It is always reproducible.
- It is not related to the timing. Even after waiting for some time, there is no change of the result.
- It is not related to IntelliJ. It is also happening with VS Code.
- Autosave in IntelliJ can not be disabled completely, please see
<img src=https://user-images.githubusercontent.com/2410127/202754985-f56aa914-0ea3-4a28-a6d2-cabf2c9eec77.png width=400>

- It seems that the server is always sending the 'previous' error.

- Simple reproducibility steps, is just to change `foo` in both places (one after the other) to `goo`, `hoo`, `ioo`, etc.

A sample server log (starting from `aoo`) is in [50496.txt](https://github.com/dart-lang/sdk/files/10043052/50496.txt)

**Comment by asashour** [comment]
A failing test was added in [sdk/271201](https://dart-review.googlesource.com/c/sdk/+/271201) (thanks for the review), however I am not sure if this actually simulates the client/server scenario.

There is [getCachedResult](https://github.com/dart-lang/sdk/blob/4ba2fdc0fe7f873e1fcc32713c6d1d565062a768/pkg/analyzer/lib/src/dart/analysis/driver.dart#L645), but even if this is changed to always return `null`, the behavior is not changed (with the test case or with Intellij).

**Comment by asashour** [comment]
Update: the issue is in the analyzer, on constructing the compilation unit the third time. It seems that the old `MixinElementImpl.superInvokedNames` are being re-used. Even if their class is replaced.

An updated test case is in [sdk/271520](https://dart-review.googlesource.com/c/sdk/+/271520), to base the investigations on.

So far, this is reproducible by having three "codes", and it seems on constructing the third one, initial class from the first "code" is being used.

**Comment by bwilkerson** [comment]
@scheglov In case you have any ideas.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/273831
