### ISSUE TITLE
Map.updateAll() fails with runtime type error when it should not

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#50501]
Running this code, which as far as I can tell is 100% typesafe:

```dart
main() {
  print(_resolveMap({'foo': 'bar', 'other': {'a': 'b'}}));
}

Map<String, Object?> _resolveMap(Map<String, Object?> map) {
  map.updateAll((key, value) => (value is Map<String, Object?>) ? _resolveMap(value) : value);
  return map;
}
```

Results in a type error at runtime:

```
Error: TypeError: Closure '_resolveMap_closure': type '(String, Object?) => Object?' is not a subtype of type '(String, String) => String'
```

**Comment by renatoathaydes** [comment]
This happens even when I generify the function:

```dart
Map<String, T> _resolveMap<T>(
    Map<String, T> map, Map<String, dynamic> properties) {
  map.updateAll((key, value) => _resolveValue(value, properties));
  return map;
}
```

Which makes it impossible to implement this.

**Comment by renatoathaydes** [comment]
The problem is the nullable value on the Map. My generic function was checking for `Map<String, Object?>` and recursing in that case, but if I check for only `Map<String, Object>`, it does work... that's ok in my case, but feels like this is a bug because we do a check that passes (i.e. `is Map<String, Object?>` , which passes for any `Map<String, Object>`), but then it errors when the function with that type that was already checked is called.

**Comment by kevmoo** [comment]
@lrhn ?

**Comment by lrhn** [comment]
The problem is that your sub-map `{'a': 'b'}` has type `Map<String, String>`. Its `updateAll` method expects a function of type `String Function(String, String)`. You give it a function of type `Object? Function(String, Object?)`, which is not a subtype of `String Function(String, String)`, because the return type is not a subtype of `String`.

At *runtime*, it will probably only return existing values of the map, which are all strings, but you can't see that from the function type. It could return `new Object()` or `null` instead, for all the type checking knows.

In your test, you check whether `value is Map<String, Object?>`, which it is, even if it's really a `Map<String, String>`, because Dart generics are (unsafely) covariant. You are allowed to up-cast type parameters to a supertype, but you can't necessarily use all the members safely then.
The unsafety comes from the type parameter being allowed to occur contravariantly in member signatures, and that happens here.
The classical example is `List<Object> list = <int>[1]; list.add("not an int");`. The static type allows this because the signature of `add` is `void add(E value)`, and statically we think it's a `List<Object>`. If we try to add a string to a `List<int>`, it needs to throw at runtime to prevent being unsound.

For maps, consider:
```dart
Map<String, Object?> map = <String, String>{"a": "b"};
map.updateAll((key, value) => value);
```
The function `(key, value) => value` occurs in a static context expecting an `Object? Function(String, Object?)`, so the types are inferred as `(String key, Object? value) => value`. That's a valid argument to `Map<String, Object?>.updateAll`, so the compiler allows it.
It's not *actually* a valid argument to `Map<String, String>.updateAll`, because it doesn't return a `String`. Our contravariant-type parameter check in `updateAll` throws seeing the `Object? Function(String, Object?)`.

There is no good way to achieve what you want without *knowing* the value type of the map, because the function type `V Function(K, V)` uses `V` both covariantly and contravariantly. You have to hit it exactly.
You can widen the accepted values to `V Function(K, Object?)`, but you still need to return a `V`, and provide a function *typed* as returning a `V`. Which you only can if you know the precise type, or you return `Never`, which isn't useful.

Generics don't work because they get their parameters from the static type anyway.
The change to nullability looks like a red herring. It shouldn't change anything.

I don't have a good solution, other than not using `updateAll`. If you use `Map.map` instead, to create a new map, you don't have to satisfy the runtime type of the old map, just the static type of it.
