### ISSUE TITLE
[analysis_server] Server dynamic registration capability for CodeAction is calculated based on folding and not code action

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#50531]
Hi, I was going through analysis server code and occasionally noticed that `codeActions` getter for `ClientDynamicRegistrations` is calculated based on `_capabilities.textDocument?.foldingRange`, but should probably be calculated on `_capabilities.textDocument?.codeAction` instead.

https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/lsp/server_capabilities_computer.dart#L60

I can make a PR if the issue is confirmed.

**Comment by asashour** [comment]
I guess this is not tested. A CL could be proposed with a test case for the change.

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
@incendial you're right, this is definitely a bug. If a client supported dynamic registration for folding but not code actions, we would still try to dynamically register code actions.

There are some tests related to this here:

https://github.com/dart-lang/sdk/blob/95c6795d2f9b1b3f4bcbcc7ab40c70805700e638/pkg/analysis_server/test/lsp/initialization_test.dart

In particular, this test sets dynamic registration for hovers and checks that it is dynamically registered:

https://github.com/dart-lang/sdk/blob/95c6795d2f9b1b3f4bcbcc7ab40c70805700e638/pkg/analysis_server/test/lsp/initialization_test.dart#L358

If that same test existed for code actions (and others), I expect this would've been caught. Let me know if you're planning to send a fix for this, otherwise I'll take a look. Thanks!

**Comment by incendial** [comment]
@DanTup thanks for additional links, I'll send the fix in a few days (also try to add more tests)

**Comment by incendial** [comment]
@DanTup I'm a bit stuck with the tests: my idea is to have one method to test all the capabilities separately https://dartpad.dev/?id=1b704ac1f8559043fb5bddea39566430, but as I go through the other tests code, I don't see a working way to call `initialize` in a loop.

Maybe you could give a hint, if this possible? If not, I'll rewrite to separate methods then, where each will call initialize with its own capability.

**Comment by DanTup** [comment]
@incendial it's not currently possible to call initialize multiple times, as the base test class expects only a single server to be used per test (and it's not valid to initialize the server twice).

I would suggest using multiple tests, but they could call a function that has all the test logic, just passing whichever bits of data required:

```dart
test_dynamicRegistration_signatureHelp() => assertDynamicRegistration('signatureHelp', Method.textDocument_signatureHelp);
```

**Comment by incendial** [comment]
@DanTup Thank you for the guidance! Should be it https://dart-review.googlesource.com/c/sdk/+/272260

**Comment by DanTup** [comment]
@incendial I made two minor comments on the change there, but otherwise looks good. Thanks! 😄

**Comment by DanTup** [comment]
The fix for this landed in https://github.com/dart-lang/sdk/commit/2b7b4dc777284f10398cd75813cbdec89fea8da9 and should be included in a future SDK release.
