### ISSUE TITLE
Allow getting address of native symbols when using static ffi binding

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#50552]
We're moving towards a direction where all native symbols will be declaratively specified. We have support for declaratively specifying native C functions (see https://github.com/dart-lang/sdk/issues/43889). https://github.com/dart-lang/sdk/issues/50551 is tracking the same for global variables.

Though we'd also want a way to obtain the address of those declaratively specified external functions (and global variables). Something equivalent to the `&` address-of operator in C.

Possibly we could have an `Pointer<T> addressOf<T>(value)` and only allow calling `addressOf` on `value`s that are external C symbols (functions or global variables).

**Comment by mkustermann** [comment]
As a concrete use case, see dart2js usage of memory mapped files [here](https://github.com/dart-lang/sdk/blob/7759f7fe032f/pkg/compiler/lib/src/io/mapped_file.dart#L33): It can use declarative syntax for functions it calls, but not for functions it needs the address of.

**Comment by simolus3** [comment]
This depends on the `@Native` optimization relanding, but I've implemented this in https://dart-review.googlesource.com/c/sdk/+/333920.

**Comment by dcharkes** [comment]
Proposed API from the PR, copied to here for easy discussion:

```dart
// ...
@Since('2.19')
final class Native<T> {
  // ...

  /// Resolves the native address of [native].
  ///
  /// [native] must be a reference to a method annotated with `@Native` and
  /// [T] must be a [NativeFunction] compatible to the [native]s signature.
  ///
  /// Example:
  /// ```dart
  /// import 'dart:ffi';
  ///
  /// @Native<Int64 Function(Int64, Int64)>()
  /// external int sum(int a, int b);
  ///
  /// void main() {
  ///   final address =
  ///       Native.addressOf<NativeFunction<Int64 Function(Int64, Int64)>>(sum);
  /// }
  /// ```
  @Since('3.3')
  external static Pointer<T> addressOf<T extends NativeType>(
      @DartRepresentationOf('T') Object native);
```

Usage:

```dart
@Native<Void Function(Pointer)>()
external void free(Pointer pointer);

final freeFinalizer = NativeFinalizer(Native.addressOf(free));
```

@lrhn @mkustermann @mraleph

**Comment by lrhn** [comment]
Seems reasonable.

Could `native` be typed as `Function`?

I assume you can't define a `@Native` variable, or if you can, you can't refer to it by its name (because it's value is not linked to the declaration), so this is only for functions.

Docs can be tweaked (fx. remove "Resolves"), but that can always be done later.

**Comment by simolus3** [comment]
> Could `native` be typed as `Function`?

I'd like to see `@Native` variables as well (https://github.com/dart-lang/sdk/issues/50551), they'd likely be written as external static fields and I think we should support `addressOf(nativeField)` as well.

> because it's value is not linked to the declaration

We can still get the address of the declaration by looking up the symbol though, right? `addressOf` is implemented as a CFE transformation which detects valid targets.

**Comment by dcharkes** [comment]
> Could `native` be typed as `Function`?
> 
> I assume you can't define a `@Native` variable, or if you can, you can't refer to it by its name (because it's value is not linked to the declaration), so this is only for functions.

No, we can have global variables as well (after addressing #50551), so that's why it's typed object. (The same way `DynamicLibrary.lookup` can be used to look up symbols of functions and global variables.)

**Comment by lrhn** [comment]
If `addressOf(nativeField)` can work, then `addressOf` is not a function, but a compiler macro of some sort. That's fine, but should probably be documented.

The argument is not really a function value, it's really an unevaluated function _name_, that the compiler resolves to a function declaration.

**Comment by dcharkes** [comment]
FYI @askeksa @eyebrowsoffire @osa1  Any API concerns from a dart2wasm point of view?

**Comment by eyebrowsoffire** [comment]
I think the proposal should work fine as stated above in wasm. A little background here: in wasm MVP (not WasmGC), there is a `funcref` type, which is an opaque reference to a function (with no specific signature). This is sometimes called a "vanilla" function reference, to differentiate it from typed function references, which are a proposal that usually goes along with WasmGC. Vanilla `funcref`s can only be invoked if they are in a table of function references, so as far as the wasm C ABI is concerned, function pointers are treated as indices into the indirect function table. As such, I believe we should treat FFI pointers the same way, they are a numeric value that can be passed around as an integer.

Floating vanilla `funcref`s themselves don't actually have a language representation in C/C++ right now so I don't think there's a need to represent them with FFI types. Typed function references are a little different though. They actually can be invoked outside of a table, and clang/llvm has added some early support for representing these values in C/C++ code. As such, we eventually may want to represent these as FFI types, since theoretically one could construct a C/C++ wasm module which has exports which have typed function references for parameters or return values. Probably not an immediate concern, but may eventually be something necessary to implement.

**Comment by eyebrowsoffire** [comment]
Oh and maybe I should have clarified: typed function references (and externrefs, which also we may want to add as FFI types at some point) are not actually addressable in C/C++ code. When used in C/C++ code, the compiler will error if you attempt to take the address of them. It will also error if you attempt to store them as a member of a struct or class since structs and classes exist in linear memory, and because these references are opaque and not numeric, there is no way to store them in linear memory itself. As such, these objects are pretty exotic when coding with them in C/C++. FFI is a representation of the C ABI in dart, and because compiler implementers in the C/C++ world are starting to create these types of "unaddressable" entities, we may want to keep that in mind when implementing things like this and leave the door open to unaddressable FFI types.

**Comment by askeksa** [comment]
One issue I see here is that the C/C++ compiler will populate the global function table with every function whose address is taken. But it doesn't see the `addressOf` call in Dart code, so it doesn't know to put the function in the table. If the function isn't in the table, it doesn't have an "address".

**Comment by dcharkes** [comment]
> One issue I see here is that the C/C++ compiler will populate the global function table with every function whose address is taken. But it doesn't see the `addressOf` call in Dart code, so it doesn't know to put the function in the table. If the function isn't in the table, it doesn't have an "address".

With static linking, we can tell the C/C++ compiler which symbols are used or not. `Native.addressOf` only accepts const arguments, so we can rely on TFA/const-finder to give us a list of used symbols.
(Currently, we only support dynamic libraries, so the symbols are necessarily exported.)

Is there something different about that in the context of WasmGC?

**Comment by eyebrowsoffire** [comment]
I think this is a non-issue though. I believe the C/C++ compiler will add any exported functions to the global function table too. There are only two ways I can think of that a C/C++ function would be actually visible to dart:
* It is exported
* The address of the function is taken in C/C++ and passed back to dart via a return value or parameter or something
In both cases it seems like the function will be in the global table. Any other functions I don't see that dart would have any way of calling `addressOf` in the first place.
