### ISSUE TITLE
Analysis server plugins fail due to sending HashMaps between Isolates

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#50594]
This came up in https://github.com/Dart-Code/Dart-Code/issues/4295. Analyzer plugins are not working correctly on latest (unreleased) versions of the SDK (FYI @bwilkerson):

```
Invalid argument:: is a regular instance:: Instance of '_HashMap<dynamic, dynamic>'
#0      _SendPort._sendInternal (dart::isolate-patch/isolate_patch.dart::249::43)
#1      _SendPort.send (dart::isolate-patch/isolate_patch.dart::230::5)
#2      ServerIsolateChannel.sendRequest (package::analyzer_plugin/src/channel/isolate_channel.dart::249::16)
#3      PluginSession.sendRequest (package::analysis_server/src/plugin/plugin_manager.dart::948::13)
```

I managed to track this down to `HashMap`s being included in the payloads that go over the `SendPort`. In v2.18 this works fine, but on latest builds it seems to fail. I'm not sure if there's a smaller repro, but here's what works for me in v2.18 and fails on latest:

## isolate.dart

```dart
import 'dart:async';
import 'dart:collection';
import 'dart:isolate';

Future<void> main() async {
  final receivePort = ReceivePort();
  Isolate.spawnUri(Uri.parse('isolate_echo.dart'), [], receivePort.sendPort);

  final sendPort = (await receivePort.first) as SendPort;

  // Works in v2.18, broken in latest.
  sendPort.send({'a': HashMap<String, String>()});
}
```

## isolate_echo.dart

```dart
import 'dart:isolate';

void main(List<String> args, SendPort sendPort) {
  final receivePort = ReceivePort();
  sendPort.send(receivePort.sendPort);

  receivePort.listen((msg) {
    sendPort.send('ECHO: $msg');
  });
}
```

## Error

```
Unhandled exception:
Invalid argument: is a regular instance: Instance of '_HashMap<String, String>'
#0      _SendPort._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
#1      _SendPort.send (dart:isolate-patch/isolate_patch.dart:230:5)
#2      main (file:///Users/danny/Desktop/dart_sample/bin/isolate_testing.dart:12:12)
bin/isolate_testing.dart:12
<asynchronous suspension>
```

It looks like a similar issue has come up before at https://github.com/dart-lang/sdk/issues/24243 (@a-siva looks like you fixed that, so perhaps you have an understanding of what might be wrong).

**Comment by DanTup** [comment]
For reference, the sources of the `HashMap` in the server that's triggering this is here (although my guess is that this is a regression that needs fixing and we shouldn't try to fix only the server).

https://github.com/dart-lang/sdk/blob/e7bd696ce0983f9c38087f1bae026f8e550b1942/pkg/analysis_server/lib/src/protocol/protocol_internal.dart#L79

**Comment by mraleph** [comment]
This is intentional change which reinstates strict checks. It was a mistake when those checks were removed. 

You can only send a well-defined list of objects through `SendPort` to an `Isolate` spawned with `spawnUri`. See documentation for [`SendPort.send`](https://api.dart.dev/stable/2.18.5/dart-isolate/SendPort/send.html). `HashMap` is not on the list. You can only send default implementation of `List` and `Map`. (Doc comment is missing the word "default" - I am going to fix it).

**Comment by DanTup** [comment]
@mraleph thanks for the quick response. In that case I'll take a look at changing the server and tweak this issue to reflect that this is a server bug.

Should this change be called out in https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md as a breaking change?

**Comment by mraleph** [comment]
Yep, it should be. It's a mistake it was not included. I will include it. I am not sure it's a breaking change by our classification - it essentially fixes a bug. It did not go through official breaking change process.  /cc @mit-mit @lrhn

**Comment by rrousselGit** [comment]
Out of curiosity, what's the benefit of preventing `SendPort.send(HashMap(...))`?
I don't see the reasoning. 

Supporting HashMap sounds useful

**Comment by DanTup** [comment]
> I am not sure it's a breaking change by our classification - it essentially fixes a bug

That's fair, but if code in the SDK itself was affected, I suspect other projects could be too, and having it listed somewhere to make it clear it's not a bug may avoid some confusion and additional issues :-)

**Comment by mraleph** [comment]
Uploaded https://dart-review.googlesource.com/c/sdk/+/273185 trying to fix CHANGELOG.md and make documentation of SendPort.send a bit more clear. 

> Out of curiosity, what's the benefit of preventing `SendPort.send(HashMap(...))`?

When you have two isolates that don't share the source we can't really guarantee that the receiving end has `HashMap` class to begin with. It happens to be there in JIT mode, but in AOT, for example, it can be shaken away.

**Comment by rrousselGit** [comment]
That's quite the funny edge-case. Thanks for the info!

**Comment by lrhn** [comment]
Historically, the design allowed any JSON-like structure, so any `List` or `Map<String,...>`, and effectively rebuilt them as the default growable list/linked hash map on the other side. As if there had been a JSON-serialization+deserialization. It wouldn't necessarily preserve constant canonicalization of strings either (because the string object might not be constant on the other side).

I think that was what the JS implementation of isolates did, back when it existed.
I also think the VM implementation did something similar at the time.

I can see how that can get in the VM's way if the sending isolate doesn't know which isolate will receive the value.
Then you just want to serialize using the native serialization, and require that the types come only from core platform libraries, so they are guaranteed to exist, with the same identity, in the receiver.

If you know, ahead of sending, whether the other isolate belongs to the same isolate group or not, it should be possible to have separate code paths, but if that does not appear to be necessary, I'm also fine with that.
(Also, it might require calling user code to serialize the maps and lists, but that's the cost of sending your own objects. Still simpler to not let the sender worry about it.)

**Comment by DanTup** [comment]
On a slight tangent, it would be quite useful if there was an API to check whether an object is valid to be sent over an isolate spawned with `spawnUri`. The analysis server has a lot of generated code for the protocol classes which have `toJson()` implementations and testing that they produce objects that can be sent without spawning real isolates would be helpful. As far as I can tell, it's not a trivial thing to do otherwise, because `is` will incorrectly include subtypes, and checking `runtimeType` for something like `List` seems like it would rely on hard-coding private type names?

A lot of the server plugin testing is unit tests that bypass the isolates. It would be nice if that implementation could verify every instance going through it would be valid to send without having to make all those tests spawn real isolates.

**Comment by mraleph** [comment]
> As if there had been a JSON-serialization+deserialization.

I must admit that this intent was never clear from the documentation. 

> I also think the VM implementation did something similar at the time.

I don't think VM ever did anything like that. I don't think it ever attempted to convert objects during sending - instead it always serialised objects AS-IS, preserving their runtime types. 

> If you know, ahead of sending, whether the other isolate belongs to the same isolate group or not, it should be possible to have separate code paths

We have two different code paths for messages sent within isolate group and messages sent between isolate groups. `SendPort.send` documentation reflects this. 

@DanTup please file a separate issue for this. I think it makes sense to provide such API.

**Comment by DanTup** [comment]
I've filed #50690 requesting this.
