### ISSUE TITLE
Is `late` keyword possible in `List<Object>.filled(5, late)` definiton, not null

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#50596]
Because, first calling `filled`, then manually filling is just very slow, :-(

**Comment by mraleph** [comment]
That does not work because users of such list expect to be able to load a value without any checking. 

Did you actually measure or are you trying to micro-optimise things without measuring? 

If you measured - provide the benchmark that captures your use case and describe why you think it is not fast enough for your case.
