### ISSUE TITLE
[vm] Remove `FallThroughError` code in the VM

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50595]
We're still constructing `FallThroughError`s in the VM:

https://github.com/dart-lang/sdk/blob/55b4542dab8c814ecb3d84d0733ba8bf999b3bb0/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#L4950-L4988

Dart doesn't have `FallThroughError`s anymore since Dart 2.0.
The oldest language version we support with dart language versioning is Dart 2.7.
So we should never exercise this code.
However, removing it or changing it into an assert leads to the compiler choking.
This is technical debt that needs to be cleaned up.

For context: https://dart-review.googlesource.com/c/sdk/+/259041/13/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#4952

**Comment by dcharkes** [comment]
https://github.com/dart-lang/sdk/blob/999c9b5e193d3f34624f8d29b6392fc1de81b69a/pkg/_fe_analyzer_shared/lib/src/type_inference/type_analyzer.dart#L1198-L1204

Turns out, with language version <= 2.11, these were not compiler errors, as we were checking for null-safety (which is 2.12)!

https://github.com/dart-lang/sdk/commit/466494f5be8f564758499f98420f1a85f5e8df8d introduces `!options.patternsEnabled`. @stereotype441 The VM was generating a throw at runtime, so your implementation could not have depended on the runtime behavior of unterminated cases in switch statements. Is this a spurious change that can be removed again?

I'm going to remove the VM support for unterminated switch statements, so we rely on the CFE for gating these as compiler errors.

**Comment by dcharkes** [comment]
@stereotype441 I'm a bit in over my head with `SwitchStatementTypeAnalysisResult<Type> analyzeSwitchStatement(`, could you please take a look why this switch case is being reported as fall through? It is ending with a `break;` so it should not be reported.

You can repro this by removing `options.nullSafetyEnabled &&` and trying to build the SDK or invoking `gen_kernel.dart` directly with `pkg/compiler/lib/src/dart2js.dart`.

**Comment by stereotype441** [comment]
Hi Daco!  I'm happy to help.  Let me try to clarify what's going on here:

> https://github.com/dart-lang/sdk/blob/999c9b5e193d3f34624f8d29b6392fc1de81b69a/pkg/_fe_analyzer_shared/lib/src/type_inference/type_analyzer.dart#L1198-L1204
> 
> Turns out, with language version <= 2.11, these were not compiler errors, as we were checking for null-safety (which is 2.12)!

Actually that's not quite true.  They've always been compile errors, but before null safety, the check was performed in a completely different way.  So this check here only happens when null safety is enabled, and there's a corresponding check in `body_builder.dart` that only happens when null safety is disabled:

https://github.com/dart-lang/sdk/blob/999c9b5e193d3f34624f8d29b6392fc1de81b69a/pkg/front_end/lib/src/fasta/kernel/body_builder.dart#L7457-L7471

> [466494f](https://github.com/dart-lang/sdk/commit/466494f5be8f564758499f98420f1a85f5e8df8d) introduces `!options.patternsEnabled`. @stereotype441 The VM was generating a throw at runtime, so your implementation could not have depended on the runtime behavior of unterminated cases in switch statements. Is this a spurious change that can be removed again?

The reason for `!options.patternsEnabled` is because of this spec text from the [patterns proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#implicit-break):

> A long-running annoyance with switch statements is the mandatory `break` statements at the end of each case body. Dart does not allow fallthrough, so these `break` statements have no real effect. They exist so that Dart code does not *appear* to be doing fallthrough to users coming from languages like C that do allow it. That is a high syntactic tax for limited benefit.
>
> ...
>
> Therefore, this proposal removes the requirement that each non-empty case body definitely exit. Instead, a non-empty case body implicitly jumps to the end of the switch after completion.
 
So we need two behavioural changes to the compiler when pattern support is enabled:
1. Stop reporting an error if a switch case is unterminated.
2. During code generation, ensure that any switch case that's otherwise unterminated ends with an unconditional jump to the end of the switch statement.  This could be accomplished either by the common front end inserting a synthetic `break` into the generated kernel representation, or by the back ends generating the jump.  Personally I would probably do this as a front end change, so that the back-ends can continue to assume that in the lowered kernel representation, all switch cases are terminated.

The `!options.patternsEnabled` check in `type_analyzer.dart` takes care of the first behavioural change.  It's definitely not a spurious change.

As for the second behavioural change, I assumed either the front end or back end teams would do it.  @johnniwinther do you know the status of this?  If it hasn't been done yet, can you tell us whether you expect it to be done in the CFE or the back ends?

(Side note: if it would be helpful, I wouldn't mind adding logic to `type_analyzer.dart` such that if patterns are enabled, and an unterminated case is detected, it reports that situation to the CFE, so that the CFE knows it needs to insert a synthetic `break`.  @johnniwinther let me know if you want me to do that, or feel free to do it yourself and I'll be happy to review it.)

> 
> I'm going to remove the VM support for unterminated switch statements, so we rely on the CFE for gating these as compiler errors.
> 
> Spicy, dart2js is Dart 2.10.
> 
> ```
> ../../pkg/compiler/lib/src/dart2js.dart:510:9: Error: Switch case may fall through to the next case.
>         case 'v':
>         ^
> ```
> 
> Nothing wrong with that switch:
> 
> https://github.com/dart-lang/sdk/blob/999c9b5e193d3f34624f8d29b6392fc1de81b69a/pkg/compiler/lib/src/dart2js.dart#L509-L525

This gets back to what I said earlier about how before null safety, the check for a switch case fall through was performed in a completely different way.  What happened is that when you removed `options.nullSafetyEnabled &&` from `type_analyzer.dart`, you were causing the new check to be performed even when null safety is not enabled.  Since the new check is based on flow analysis, and flow analysis isn't performed on pre-null-safe code, the new check got confused and reported a bogus error.

So the TL/DR is, I believe the code in `type_analyzer.dart` is correct and doesn't need to be changed.  It should still be safe for you to remove the VM support for unterminated switch statements, because you can rely on the CFE's two mechanisms to emit the proper error for language versions < 3.0.  For language versions 3.0 and above, either the CFE needs to insert a synthetic `break`, or the VM needs to do it; I'll leave it up to you and the CFE folks to work out where to do that.

I hope this helps.  If you have follow-up questions, I'm happy to discuss more here.  I would also be happy to do a video conference if that would be easier.

**Comment by dcharkes** [comment]
Thanks for the lengthy explanation @stereotype441! (Who would have thought that the code path would be different. 🙃)

> It should still be safe for you to remove the VM support for unterminated switch statements, because you can rely on the CFE's two mechanisms to emit the proper error for language versions < 3.0.

Hm, trying to remove the old logic from the VM and putting an assert in its place makes the VM hit that assert:

```
Command failed: /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/dart --deterministic --packages=/usr/local/google/home/dacoharkes/dart-sdk/sdk/.dart_tool/package_config.json --snapshot=/usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/gen/kernel-service.dart.snapshot --snapshot-depfile=/usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/gen/kernel-service.dart.snapshot.d --depfile-output-filename=gen/kernel-service.dart.snapshot --snapshot-kind=app-jit --dfe=/usr/local/google/home/dacoharkes/dart-sdk/sdk/utils/kernel-service/NEVER_LOADED /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/gen/utils/kernel-service/kernel-service_snapshot.dart.dill --train file:///usr/local/google/home/dacoharkes/dart-sdk/sdk/pkg/compiler/lib/src/dart2js.dart

output: is_default 0 body_fragment.is_open() 1 case_index 0 helper->case_count() 7

output: ../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc: 4953: error: expected: is_default || !body_fragment.is_open() || (case_index == (helper->case_count() - 1))
```

So for pre-nullability code the CFE emits something else than post nullability? (I have not been able to hit this assert with Dart 2.12 or later.) I'll take a look what kernel exactly we're getting to consume.

cc @johnniwinther @jensjoha (if different kernel rings a bell)

**Comment by johnniwinther** [comment]
@dcharkes Given how weird this part of the language is and has been, I'd not be surprised if we generated different code for different language versions. The only thing that comes to mind is that we insert a throwing default case for exhaustive switch cases in weak mode (to handle `null` occurring as the switch value) but that is not the case you encountered.

We probably need a smaller repro than dart2js - or at least information about where the faulty switch occurs.

For the 3.0 semantics: We haven't yet started adding the synthesized breaks but it is the plan to do so. @stereotype441 we probably when some info from the type analyzer about when this is needed.

**Comment by dcharkes** [comment]
I've found a couple of cases where we're guaranteed to never hit the end of a case, but the flow with statements doesn't make that obvious:

* Calling something that returns `Never`.
* Nested switches which always return in a case in the outer switch.

Apparently the analysis in the CFE is smart enough to figure out we never hit the end of the control flow in a not-explicitly-terminated case, but the VMs representation (fragments + stack height) is not.

### Calling something that returns Never

The CFE does not insert a `break;` on calls to functions that return `Never`.

https://github.com/dart-lang/sdk/blob/a392d30e1d4359058ebb924d9f3541c2a89d6f0b/pkg/front_end/lib/src/fasta/source/source_extension_builder.dart#L130-L133

https://github.com/dart-lang/sdk/blob/a392d30e1d4359058ebb924d9f3541c2a89d6f0b/pkg/front_end/lib/src/fasta/problems.dart#L70-L75

Adding a `break;` stops the VM generating the `FallThroughError` (which is _never_ hit), or alternatively stops us from needing to generate a `Push(null);Return();` in the VM.

```dart
 case BuiltMemberKind.ViewFactory: 
   unhandled("${member.runtimeType}:${memberKind}", "buildMembers", 
       memberBuilder.charOffset, memberBuilder.fileUri); 
   break;
 case BuiltMemberKind.ExtensionField: 
```

### Nested always returning code

Another case is when in a case all paths lead to a return, but the CFE cannot prove that:

https://github.com/dart-lang/sdk/blob/a392d30e1d4359058ebb924d9f3541c2a89d6f0b/pkg/front_end/lib/src/api_prototype/compiler_options.dart#L563-L604

### Solution

The question is whether not-obviously-terminated-cases are valid kernel (current situation) and the backends need to insert control flow internally to make a valid CFG, or whether the CFE should emit obviously-terminated-cases.

I'm entirely sure how synthesized breaks would work. A synthesized break would fix the control flow but would be dead code and would probably not satisfy the types (e.g. a return from all branches and no return after a switch would make it look like the synthesized break introduces a code path where we return void). @johnniwinther what are your thoughts around synthesized breaks?

Alternatively, we can keep inserting control flow in the backends (but it would be kind of hard to assert it's dead code).

**Comment by johnniwinther** [comment]
@daco Would it be adequate to add an `isCompleting` property to `SwitchStatement` that would be set to true if the switch statement can complete normally, i.e. doesn't return or throw?

**Comment by stereotype441** [comment]
@johnniwinther 
> For the 3.0 semantics: We haven't yet started adding the synthesized breaks but it is the plan to do so. @stereotype441 we probably when some info from the type analyzer about when this is needed.

Ok, I've filed https://github.com/dart-lang/sdk/issues/50624 to track this work.  I'll start by adding the necessary shared analysis logic to report when synthetic breaks are needed.

**Comment by dcharkes** [comment]
Loosely: whether the fragment is hooked up fully in the flow graph or not.

**Comment by dcharkes** [comment]
Actually it turns out it's not that simple to add control flow in the backend either.

The previous control flow (a throw of a FallThroughError) was context free. However, to insert the proper control flow edges, we need to know the break targets as well (which are part of the kernel format, but without synthetic break statements we need to reverse engineer those in the VM).

**Comment by dcharkes** [comment]
Blocked by https://github.com/dart-lang/sdk/issues/50624.

**Comment by dcharkes** [comment]
I've landed a workaround with a TODO that we should fix this in the CFE instead.

That work is tracked in:

* https://github.com/dart-lang/sdk/issues/50624
