### ISSUE TITLE
[vm/ffi] `Pointer.fromFunction` should reuse trampolines in JIT

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50611]
In AOT, we don't know how many invocations of `fromFunction` we'll get at runtime, so we compile the machine code exactly once and all invocations connect to that.

In JIT, we currently compile for every invocation. These compilations should be cached and the same function pointer should be given out for the same callback within an isolate group.

As @liamappelbe pointed out, the checks in runtime_entry.cc aren't sufficient AOT. They work in JIT currently because of not caching the trampolines, and they don't work in AOT.

>  This means that the status quo is that today there's a bug where it's possible that your callback runs successfully, but you're on a different isolate than you expect (so eg global variables could have unexpected values, which is confusing and hard to debug)

We should unify the behavior in JIT and AOT.

One way: we could do the caching and introduce the AOT status quo in JIT, losing some of our sanity checks in JIT.

Otherwise, we're going to need to introduce an abstraction for declaring that we want a callback to work on N isolates as suggested by @mkustermann:

> We could make each top-level function used as FFI callback lead to generation of N callback functions: Each of them will have (app-uuid, function-callback-id, isolate-i) for i=0…N-1 embedded in them. When an isolate creates a callback from the top-level function, we will register in VM-global data structure a mapping from (app-uuid, function-callback-id, isolate-i) to the isolate (if there’s already N usages of the callback in N different isolates, we throw). When callbacks are involved they pass the triplet to VM, which finds the right isolate to enter, …

([internal doc with more background](http://go/dart-interop-native-threading))

Having such feature, means we also want to start supporting freeing callbacks:

* https://github.com/dart-lang/sdk/issues/50610

**Comment by dcharkes** [comment]
One thing that is unclear to me is how we should determine the `N` for callback functions.

Let's say we have 

* a `package:my_database` that uses a callback,
* a `package:my_storage` that uses `package:my_database` in a separate isolate,
* an `app1` that uses some packages that use `my_database` and `my_storage`, and
* an `app2` that uses some packages that use `my_database` and `my_storage`.

We need to know when AOT compiling `app1` and `app2` what `N` to use for every `fromFunction`. However, who declares this?

* `package:my_database` doesn't know on how many isolates it will be run. It could force itself to run on a helper isolate and be some kind of singleton that always runs on this helper isolate, but that would block users from running multiple databases at the same time.
* `package:my_storage` knows it is creating an isolate, but it might not be aware that `package:my_database` uses callbacks. Moreover, it might be instantiated itself on multiple isolates.
* `app1` and `app2` don't know about the implementation details of `package:my_database` and `package:my_storage`.

Also, it might depend on an app is deployed. So should the `N` be configured during AOT compilation instead of be part of the source code? If that's the case, we probably want `N` to be unbounded in JIT mode (which would mean different behavior in JIT and AOT).

**Comment by liamappelbe** [comment]
> Having such feature, means we also want to start supporting freeing callbacks

This would be nice to have, but I think just automatically freeing the callbacks associated with an isolate when the isolate is destroyed would be sufficient in most use cases. I don't think it's a blocking requirement.

**Comment by liamappelbe** [comment]
> One thing that is unclear to me is how we should determine the N for callback functions.

The design I mentioned in mind on my prototype CL (though didn't explain clearly enough) was that rather than having a pool of N callbacks for each function, and having to choose N per-function, we could instead have a single global pool.

The implementation would look a lot like how the JIT trampoline pages work at the moment, except there would only be one trampoline page for the whole app, and that page is constructed at compile time. Like the JIT trampolines today, these trampolines wouldn't need to know about the function's signature. Each slot in the page just sticks a unique function ID in a register and then jumps to the shared section that looks up the FFI trampoline and metadata associated with that ID.

Pointer.fromFunction would just choose the next unused function ID, and stick the FFI trampoline and metadata the corresponding slot in a global array/map. To free the callback we just remove the element from the array/map.

Then there'd only be one N to configure. We would choose a reasonable default (could be pretty large, eg 1000, since we only need a few bytes per function in the trampoline page), and users could override that with a compiler flag. I think it would also decrease the amount of wasted function pointers.

**Comment by dcharkes** [comment]
That's much better indeed. 👌 

> (could be pretty large, eg 1000, since we only need a few bytes per function in the trampoline page)

We could always round up to the nearest N-per-trampoline-page.

**Comment by mkustermann** [comment]
I think we can close this issue now.
