### ISSUE TITLE
[vm] Incorrect subtype test result for generic function type with substitution

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#50614]
In the [test](https://dart-review.googlesource.com/c/sdk/+/272361/8/tests/language/function_subtype/generic_function_type_substitution_test.dart) added to test a change to the representation of function type parameter types in dart2wasm, some of the cases fail on the VM.

A reduced test containing only the cases failing on the VM is:
```dart
import "package:expect/expect.dart";

class A {}

class B {}

class C<T> {
  void y<X extends A>(void Function<Y extends B>(Y) p) {}
  void yr<X extends A>(Y Function<Y extends B>() p) {}

  bool testY() => y is void Function<X extends A>(T);
  bool testYR() => yr is void Function<X extends A>(T);
}

typedef YF = void Function<Y extends B>(Y);
typedef YRF = Y Function<Y extends B>();

main() {
  Expect.isTrue(C<YF>().testY());
  Expect.isTrue(C<YRF>().testYR());
}
```
All cases give the expected result in dart2js.

**Comment by alexmarkov** [comment]
Type of `y` is `<Y0 extends A>(dynamic, <F1Y0 extends B>(dynamic, F1Y0) => void) => void`. It is tested against `<Y0 extends A>(dynamic, <Y0 extends B>(dynamic, Y0) => void) => void`.

When testing type of its parameter, an inner function type `<F1Y0 extends B>(dynamic, F1Y0) => void` against `<Y0 extends B>(dynamic, Y0) => void`, VM fails to correctly compare type parameter type `F1Y0` against `Y0`. The problem is that type `<F1Y0 extends B>(dynamic, F1Y0) => void` is created with a parent of the whole function type `<Y0 extends A>(dynamic, <F1Y0 extends B>(dynamic, F1Y0) => void) => void`. Although it doesn't reference any type parameters of the parent (outer) type, its `num_parent_type_arguments` is set to 1, so type parameter `F1Y0` has `base()` == `index()` == 1, while `base()` and `index()` of `Y0` is 0.

In order to fix this, we may need to check if the inner function type references type parameters of the outer type(s) and adjust/set its `num_parent_type_arguments` accordingly. We would also need to change all `TypeParameter` objects created for the inner function type to have correct `base()`/`index()`.
