### ISSUE TITLE
[CFE] Evaluate constants inside patterns

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#50629]
Part of https://github.com/dart-lang/sdk/issues/49749.

```dart
main() {
  List value = const [42];
  if (value case const [42]) {
    print('OK');
  } else {
    print('FAIL');
  }
}
```

Kernel:
```
   core::List<dynamic> value = #C2;
    final core::List<dynamic> #t1 = value;
    final core::bool #t2 = true;
    if(#t1 =={core::List::==}{(core::Object) → core::bool} core::_GrowableList::_literal1<dynamic>(42)) {
      #t2 = false;
      {
        core::print("OK");
      }
    }
    if(#t2) {
      core::print("FAIL");
    }
```

The first `const [42]` was evaluated to a constant `#C2`, but the 2nd `const [42]` (in the pattern `if (value case const [42])`) was not evaluated. This results in runtime failures in certain tests (such as `co19/LanguageFeatures/Patterns/constant_A03_t02`, `co19/LanguageFeatures/Patterns/constant_A03_t04` etc).

/cc @johnniwinther

**Comment by johnniwinther** [comment]
@stereotype441 This happens because the `handleLiteralList` call for the `const [42]` in `value case const [42]` doesn't have a `constKeyword`. The const keyword is instead provided to the `handleConstantPattern` method.

I've created https://dart-review.googlesource.com/c/sdk/+/273960 which instead includes the `const` keyword as part of the subexpression, thereby normalizing the handling of expression that can be prefixed by `const`.

**Comment by stereotype441** [comment]
@bwilkerson what do you think of Johnni's AST changes in https://dart-review.googlesource.com/c/sdk/+/273960?  They seem reasonable to me, but since you designed the analyzer's AST representation for patterns I want to get your input.
