### ISSUE TITLE
Make StreamSubscription FutureOr<void>

### ISSUE THREAD

**Issue by Andrflor** [dart-lang/sdk#50651]
When we are working with sync streams having cancel always a future is a waste of resources.
So, the proposal is to change
```dart
abstract class StreamSubscription<T> {
    Future<void> cancel();
}
```
Into
```dart
abstract class StreamSubscription<T> {
    FutureOr<void> cancel();
}
```

This could allow to write
```dart
class MySubscription<T> implements StreamSubscription<T> {
  @override
  void cancel() {}
}
```
It reduces cancel time by 10 with my sync stream....

**Comment by lrhn** [comment]
We're not going to change the type at this time. It's a breaking change (people currently doing `subscription.cancel().then(...)` would no longer compile), so it's not easy to do.

I don't (personally) think the benefits of the change would outweigh worth the cost.
Even if they did, it would still be potentially costly.

(We chose to make the return type `Future<void>` instead of `Future<void>?` in the null safety migration, because forcing users to have two different code paths would be expensive complication, and they'd still have to have a path handling a future anyway. If they just use `await` on the value anyway, there is no benefit to returning a non-future.)
