### ISSUE TITLE
[analyzer] `DeadCodeVerifier` doesn't correctly detect dead code

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50655]
There is a [test case](https://github.com/dart-lang/sdk/blob/66990edcf534ff07d4fa55a8113f9cf0f23e1ff8/pkg/analyzer/test/src/diagnostics/dead_code_test.dart#L435) of

```dart
void f() {
  for (var v in [0, 1, 2]) {
    v;
    return;
    1;
  }
  2;
}
```

which currently expects only `1;` to be dead code, however I think that `2;` should also be marked as dead code.

The reason seems to be that `_firstDeadNode` is set to `null` after the first invocation of `flowEnd()` with the `BlockStatement` of the `for`, and when the `flowEnd()` with the `FunctionDeclaration` is called, `_firstDeadNode` is null, so the second statement is not marked.

**Comment by bwilkerson** [comment]
@stereotype441

**Comment by lrhn** [comment]
The `2` cannot be dead code because we don't know (not without cheating a little) that the iterator of `[0, 1, 2]` will contain at least one element.
It's possible to create an object of type `List<int>` which doesn't.
In general, a `for (var v in ... )` loop is always assumed to be able to run zero times.

It's "obvious" that the iterable is a platform list with more than zero elements, and which is not leaked in any way between being created and being iterated (or ever), and we could technically special-case that in the flow-analysis rules. 
But we don't, mainly because there are so many conditions on that rule actually applying, so it really only applies to a `for(..in..)` on a collection literal. That it doesn't generalize well, and is likely not worth the effort by itself. It would be an exception to remember, to a much simpler rule: `for` and `while` loops should always assume that the body can run zero times, `do`-loops are guaranteed at least one iteration.

**Comment by bwilkerson** [comment]
I'm going to close this as WAI.
