### ISSUE TITLE
Add ability to have const function values

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#50652]
I'd like my `read` function to use the identity function as a default value so that the return value of `read` can be inferred correctly when no parameter is specified.

```dart

T _identity<T>(T x) => x;

class Agent<T> {
  Future<U> read<U>({U Function(T state)? query = _identity}) async {
  ...
  }
}
```

2 errors stop this from working:
1) `_identity` isn't considered `const`
1) Dart can't cast `T Function<T>(T)` to `U Function<U, T>(T)`

cc @lrhn

**Comment by lrhn** [comment]
This cannot work. You cannot have a default value which doesn't work for all combinations of type arguments.

The `_identity` function *is* constant, but it's a generic function assigned to a non-generic function type, so it has to be specialized to a specific type for `T`, like `_identity<int>`.

The type `U Function(T)` depends on two runtime-types (type parameters, with no bounds, whose types will only be known at runtime). 
The only constant function type satisfying that is `Never Function(Object?)`. There is no constant instantiation of `_identity` which can possibly satisfy that type (or any instantiation at all with a single type, for that matter).

Likely the inference *tries* by instantiating `_identity` with `T` or `U`, neither of which are constant, which is why you get the "default value is not constant" error.

There is no type safe solution to such a method. If there were, I'd have used it in several places. 
What you can do, unsafely, instead is:
```dart
class Agent<T> {
  Future<U> read<U>({U Function(T state)? query}) async {
    query ??= _identity<U> as U Function(T);
    // or: query ??= (T value) => value as U;
    ...
  }
}
```
The cast can fail if `T` is not a subtype of `U` (for the function cast), or if the value of type `T` is not a subtype of `U`.

I'd just have two functions (or one function and one getter).

(I've proposed things like allowing default values which are *not* valid for all type arguments to a function. If you omit the argument, then the call acts as if you had specified something of the default value's type. It's an error if that doesn't work, so the parameter is only really optional for some type arguments, and you can also infer type arguments from the default value if none are specified. It might've helped here, but it's not close to being on our short list of features.)

**Comment by gaaclarke** [comment]
Thanks for the explanation.

> whose types will only be known at runtime

But I can read the code and infer the types at build time.  I can tell you that `Agent<int>().read()` should return an `int` and `Agent<int>().read((_) => 'hi')` returns a String.  Considering the whole file I know it returns an int or a String depending on the callsite.

Maybe this is a difference with C++ generics versus Dart generics where the generic is compiled without knowing all of its usages versus compiling whatever is needed when it is used?  I guess that makes sense.

**Comment by lrhn** [comment]
You can (possibly) infer all the types that will ever be bound to `T` or `U`, but the constant default value must satisfy *all* of them. And all the ones you could add later, without changing the `Agent` class.

It is indeed a difference between Dart and C++. In Dart, the one class must run the same code, only parameterized by type variables which can only really be used for `is` tests and passing to other generic things.
The default value if the method is global. There is only one value, and it must work for any valid type assignment for `U` and `T` (which is pretty much impossible in practice).

**Comment by gaaclarke** [comment]
@kevmoo we can close it.  It is a language request but addressing it would require some massive change in compilation, possibly withholding compilation of generics until linking time.  I'm fine if we want to say that addressing it is infeasible.

**Comment by lrhn** [comment]
Agree. We don't have any current plans to allow a non-constant default value, or the subtying of type variables, which means that this approach cannot be made to work.
