### ISSUE TITLE
Analyzer creates incorrect type when combining promoted type variable and `null`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#50676]
Example:
```dart
S foo<S extends Object>(S x, bool b) {
  if (x is int) {
    x.toRadixString(16);  // Valid
    S v = x; // Valid, so x has type S&int
    v = (b ? x : null); // Error, (S?&int) not assignable to S.
    (b ? x : null).isEven; // No warning.
    return v;
  }
  return x;
}

void main() {
  foo<Object>(1, false);
}
```
The analyzer (using DartPad) gives:

> line 5 • A value of type 'S? & int' can't be assigned to a variable of type 'S'. [(view docs)](https://dart.dev/diagnostics/invalid_assignment)
> Try changing the type of the variable, or casting the right-hand type to 'S'.

I do not believe `S? & int` is a valid type in the Dart null-safety type system. You can only promote type variables, not arbitrary types.
The result of doing `(b ? x : null)` should probably be `(S & int)?`. It's the type which would be correct and sound.
(It cannot be `S & (int?)` because `int?` is not a subtype of the bound of `S`. I added `extends Object` just to make that point, it doesn't affect the error otherwise.)
Another alternative is to drop the promotion and get `S?`, which should still not be assignable to `v`.

The `(b ? x: null).isEven` has no error, showing conclusively that the `& int` takes precedence over the added `?`.
And it's unsound, because the value *is* actually `null`.

(Front-end has same problem, will file separately.)

**Comment by bwilkerson** [comment]
@stereotype441 Do you know whether this in shared code or in the `TypeSystem`?

**Comment by stereotype441** [comment]
@bwilkerson I believe it's in the `TypeSystem`.

Note that information around this issue is currently in several places:
- Here
- The corresponding [CFE bug](https://github.com/dart-lang/sdk/issues/50677)
- https://github.com/dart-lang/sdk/issues/49691, which I reported in August (and which I believe is probably the same issue, but I would love for someone to confirm my thinking about that before I mark one of these issues as a duplicate)
- [Erik's PR to address the issue I reported in August](https://github.com/dart-lang/language/pull/2427) (currently awaiting review)

I suspect that before we can fix the analyzer, the language team needs to make a decision about whether to move forward with Erik's PR or some other approach.  We have a language team meeting this morning, so I'm going to add this to the agenda.  I'll follow up here afterwards with an update.

**Comment by eernstg** [comment]
This has been resolved by the [spec change](https://github.com/dart-lang/language/pull/3435) that moved the 'UP' type function to handle intersection types earlier. The implementation issue is https://github.com/dart-lang/sdk/issues/54002.

The currently implemented behavior confirms that it is now working correctly:

```dart
S foo<S extends Object>(S x, bool b) {
  if (x is int) {
    x.toRadixString(16);  // Valid
    S v = x; // Valid, so x has type S&int
    v = (b ? x : null); // Compile-time error.
    Never z = (b ? x : null); // Type `int?`, error.
    (b ? x : null).isEven; // Compile-time error.
    return v;
  }
  return x;
}

void main() {
  foo<Object>(1, false);
}
```
