### ISSUE TITLE
[analyzer] `convert to async body` with a non-void return type

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50686]
```dart
void a(int Function() fun) {}
void b(void Function() fun) {}

void f() {
  a(() => 1);
  b(() {});
}
```
is offered an assist to be:
```dart
a(() async => 1);
```

which gives a compiler error.

I think it should not be offered when the return type is non-void. On the other hand, the assist for `b()` is fine.

**Comment by bwilkerson** [comment]
It isn't clear to me that `void` is the issue here. It seems like it's bad to convert a closure to be `async` any time the expected return type is not `Future` or `FutureOr`. That is, we shouldn't offer the assist if it will result in the type of the closure becoming incompatible with the context type.

**Comment by eernstg** [comment]
It's a tricky situation because the addition of an `async` modifier on a function literal body will in some cases pass the type checker without errors, and it will change the semantics of the function:

```dart
void f(dynamic Function() g) {
  print(g().runtimeType);
}

void main() {  
  f(() => 1); // 'int'.
  f(() async => 1); // '_Future<int>'.
}
```

We can have a similar situation with a context type that seems much more statically safe:

```dart
import 'dart:async';

void f(FutureOr<int> Function() g) {
  print(g().runtimeType);
}

void main() {  
  f(() => 1); // 'int'.
  f(() async => 1); // '_Future<int>'.
}
```

Is the analyzer assist action intended to be semantics preserving?

**Comment by bwilkerson** [comment]
Assists aren't required to be semantics preserving, but they probably shouldn't be changing the semantics in ways that aren't reasonably obvious to users.

Perhaps we shouldn't offer the assist at all for closures (but there should be a fix if the context type requires a `Future`).

**Comment by asashour** [comment]
[sdk/279519](https://dart-review.googlesource.com/c/sdk/+/279519)

The proposed CL, doesn't offer the assist for closures, except when the return type is `void`, `Future` or `FutureOf`.
