### ISSUE TITLE
[Class modifiers] Angular compiler implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#50740]

**Comment by sigmundch** [comment]
@itsjustkevin @leafpetersen - do we actually expect this to affect internal frameworks?

More generally, would it make more sense to track internal framework efforts in the internal bug tracker instead?

**Comment by grouma** [comment]
> @itsjustkevin @leafpetersen - do we actually expect this to affect internal frameworks?

+1.  From a quick glance I don't think there is much work to do on our end. It's possible we need to modify the compiler to improve error handling when the new features are used improperly. We also can take advantage of some of the new features, e.g. sealed types.

cc @leonsenft for additional thoughts.

**Comment by leonsenft** [comment]
Agreed. It seems like most of the errors produced by these features would be raised as errors in user authored code before Angular-generated code.

**Comment by itsjustkevin** [comment]
> @itsjustkevin @leafpetersen - do we actually expect this to affect internal frameworks?
> 
> More generally, would it make more sense to track internal framework efforts in the internal bug tracker instead?

We should still have some way of tracking this here.  @grouma are these already tracked through internal bugs?

**Comment by leafpetersen** [comment]
For historical context: we added this meta-issue after one feature we added turned out to break the angular compiler when it was used in code that angular consumed (perhaps extension methods?).  The issue is intended to track validating that everything works as intended (or is documented as not working, don't use with angular).  We have historically often opened an internal bug to track any actual work, but since there is no way to link internal bugs into external milestones/projects/etc, we added these issues as part of our release checklist.  I'm fine with any way of tracking this, so long as we have "validate that angular works" on some checklist somewhere.

**Comment by srawlins** [comment]
I added this to the "Dart 3 stable" milestone.

I agree with the sentiments above that I can't think of any way that a user could use Class Modifiers that would crash the Angular compiler, or that would result in UB or something. Any static errors that arise from mis-use of the modifiers should continue to be reported as normal.

**Comment by grouma** [comment]
Internal tracking id: b/279910423

**Comment by eernstg** [comment]
@grouma, just wondering, can we close this now? ('status: fixed')

**Comment by grouma** [comment]
Yes this can be closed.

**Comment by eernstg** [comment]
Thanks!
