### ISSUE TITLE
Map and set literal in unnecessary statement are not parsed

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50815]
```dart
void f() {
  const [''];
        [''];
  const {''};
        {''}; // not ok
  <Object?>{''};
  
  const {1: null}; // this is fine
        {1: null}; // but not this
        <Object?, Object?>{1: null};
}
```

Map and set literals without `const` are not ok for both analyzer and CFE, I wonder what `const` adds to them to be recognized.

Is this intentional?

**Comment by bwilkerson** [comment]
Yes, this is intentional. The language spec reads:

> An _expression statement_ consists of an expression that does not begin with a `{` character.

The reason for this seemingly odd restriction is that an expression beginning with a `{` can be identical to a block, which would make the language ambiguous. It was decided that the ambiguity would be resolved by disallowing expression statements to start with a `{`.
