### ISSUE TITLE
Completer.complete() pass Future type, immediately isCompleted = true. 

### ISSUE THREAD

**Issue by takapiroid88** [dart-lang/sdk#50875]
i expected that Completer#isCompleted is changed when Future will solve.

for example,
```
final future = Future.delayed(const Duration(seconds: 3));
final completer = Completer()..complete(future);
print(completer.isCompleted);    // actual: true / expected: false
completer.future.then((_) {
  print(completer.isCompleted);  // actual: true / expected: true
});

```

and i want to know, future status is resolved at synchronous.
but there is no way.
async way like this.
```
final future = Future.value();
final completer = Completer();
future.then((_) {
 completer.complete();
 print(completer.isCompleted);  // true
});

// i want to asynchronous like this.

// something to know future state.
if (completer.isCompleted) {
  // something process
}
```

is there a way, solve my problem.

thank you.

**Comment by lrhn** [comment]
The `Completer.isCompleted` getter exists to tell you whether it's safe to call `Completer.complete` etc.
If `isCompleted` is true, calling `complete` will throw a `StateError`. That's why it's set immediately when you call `complete` the first time.

There is currently no way to check whether the future is actually completed, if you complete the completer with another future. That's consistent with there being no way to ask a future whether it's completed. The future doesn't tell, all you can do is to wait for its result.
If you really need to know when the future is completed, you have to wait for it, as @Michael35699 says.

@rrousselGit The `add` function you describe is precisely what `complete` does, except it accepts `FutureOr<T>?`.

There are no plans to change the current behavior, or add a way for the completer to know when the future has completed.

**Comment by rrousselGit** [comment]
@lrhn 

> @rrousselGit The add function you describe is precisely what complete does, except it accepts FutureOr<T>?.

Yes. But that means it'd accepts a `Future.error`

Kind of like `StreamController.add` vs `addError` vs `addStream` but for `Completer`.

I've had to do the following a few times:

```dart
Completer<T> completer;

void fn() {
  Future<T> someFuture;
  someFuture.then(completer.complete, onError: completer.completeError);
}
```

An extension works fine though

**Comment by lrhn** [comment]
@rrousselGit 
There should be no difference between `someFuture.then(completer.complete, onError: completer.completeError)` and just `completer.complete(someFuture)`. Both will let an error future pass its error into the completer's future.
(The internals of `_Completer._completeWithForeignFuture`, which `_Completer.complet` ends up calling for some future arguments, does something very close to that expansion, because that's all it *can* do to a `Future` it doesn't know.)

So, `Completer.complete` does pipe the result of its future argument into the completers future, and it sets the `isCompleted` immediately, which is what you wanted `add` to do.

**Comment by rrousselGit** [comment]
The difference is in how error-prone it is. It's easy to forget to pass `onError`. Nothing major, but it counts :)

**Comment by rrousselGit** [comment]
Also technically there is a race condition.  
If we do the `future.then(completer.complete)` twice on two different future, there's a possible problem

A `completeFuture` could assert that a future was already "added".
