### ISSUE TITLE
Are names 'Null', 'Never', 'dynamic', and 'FutureOr' allowed in object patterns

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50872]
The types `Null`, `Never`, `dynamic`, and `FutureOr` have names. Are those names allowed in object pattens, for example, as `Null()`?

**Comment by lrhn** [comment]
Probably. We allow any type in `is` checks, so there is no reason to not allow them in type checks + destructuring, unless the destructuring itself should be disallowed.

Which means we might want to disallow any sub-patterns on a `void`-typed object pattern, so that `case void(hashCode: >4):` would be disallowed, because you are "using" the value. It's not the type, just the use of the value after matching the type.

A `Never` is harmless, it can never match. Analyzer can choose to warn about unreachable code as usual.

A `FutureOr` is not a problem, it's just not particularly useful. Matching `T` or `Future<T>` individually allows you to use `T` methods or `Future` methods on the result, whereas `FutureOr` has only the `Object` methods.

Using `dynamic` should allow any getter, with types only on the `Object` getters, so, `case dynamic(:int foo, :var bar, :1var hashCode)` would be valid, and `hashCode` and `foo` would both have type `int`, while `bar` would have type `dynamic`.

I see no problem with allowing all of them.

**Comment by eernstg** [comment]
Agreed. We usually don't make a construct an error just because it seems to provide too little value&mdash;someone might come up with a good use case. However, we would need to adjust the grammar in order to allow an `<objectPattern>` of the form `void(...)`.

**Comment by lrhn** [comment]
I'm fine with not allowing `void(..)`. Nothing good would come from writing that.

**Comment by munificent** [comment]
Agreed to everything @eernstg and @lrhn said. Let me know if you want the proposal to explicitly call this out.
