### ISSUE TITLE
Adjust language and co19 tests for removal of analyzer Hints.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#50887]
### Background

Today the language tests and co19 tests are "executed" by the analyzer by building an internal-only binary called `dartanalyzer`, which has a `--no-hints` flag. Then the tests are executed with `dartanalyzer --no-hints`. In this way, tests do not have to specify every "unused variable" or "dead code" violation which will be reported by the analyzer; they only need to specify the compile-time errors and static warnings (like unnecessary null-aware in `a?.b?.c;`).

But we're removing "hints." https://github.com/dart-lang/sdk/issues/50796. Each individual "hint" is being recategorized as a warning (and some small list as lints). So we need to address how to update the language and co19 test running. I see 3 options:

### Option 1 - ignore all warnings

We can just rename the `--no-hints` flag to `--no-warnings`, and carry on. This sounds like a simple no-op, but we do have a tiny set of warnings which we do check (like unnecessary null-aware in `a?.b?.c;`). Would it be bad to stop specifying those in tests? Should we special-case them in the `dartanalyzer` tool ("warnings-specified-in-the-spec" and "warnings")?

### Option 2 - use `analysis_options.yaml` files

In this option, we remove the `--no-hints` flag, and instead suppress diagnostics one-by-one in one (or a few) `analysis_options.yaml` file(s). These can live in `tests/language`, `tests/co19`, etc. One nice thing about this option is you have to be specific about which diagnostics you don't want specified in the tests. You don't have to look up whether something will be reported or not. A downside is this feels like it removes some of the hermeticism of the tests... but you could argue that the use of `--no-hints` already removes that same hermeticism. 🤷 

### Option 3 - specify more warnings etc in the tests themselves

This is an option, but I'm not a fan. In analyzer we go to lengths to avoid little hints like "unused local variable" (all locals should be declared as a parameter; then they won't be reported as unused). And it would mean that every new hint/warning we introduce may need a long sync from dart-lang/co19, which is really undesirable. I don't think there is a lot of win using this option, except that the tests are really much more precise and hermetic.

CC @eernstg @leafpetersen @bwilkerson

**Comment by srawlins** [comment]
I am pretty split between Option 1 and Option 2. I don't think there is too much at stake; it's mostly about personal preference and what will lead to easy development. Maybe someone has a strong preference between those two.

**Comment by bwilkerson** [comment]
We also have a goal of moving the test framework off of `dartanalyzer` and onto `dart analyze`, or if we don't I think we should because (a) it's a maintenance burden for the analyzer team and (b) we're not really testing the user experience (it's close, but not exact).

Given such a goal, one question is whether we want a `--no-hints` flag in `dart analyze`. I'm inclined to say 'no' unless there's a valid use case for our users, which I don't think there is given that we don't currently have any requests to add it.

**Comment by asashour** [comment]
I would tackle this from the author perspective, who writes language/co19 tests, and which diagnostics are expected to be verified.

Since language/co19 tests are meant to ensure the specs are correctly handled by the analyzer/cfe, whatever the specs specifies it should be verified. The individual diagnostics tests won't help much, because they are outside the radar of the language/co19 authors as far as I humbly understand.

The analyzer has taken more steps beyond the specs by providing user-friendly diagnostics, these are great, but are still outside the focus of the language tests authors.

Option 1 would make the authors lose the track of whether the diagnostics specified in the specs are implemented or not.

Option 2 would verify the specs diagnostics, and ignore the user-friendly ones. All in a global configuration, which can vary from none to all.

Option 3 would ensure even user-friendly ones are also handled, and it is a question to the authors' team if they would like to also see all diagnostics, and maintain them as well (which I don't think).

So, I think option 2 is a better option.

**Comment by leafpetersen** [comment]
I think there might be an option 4 which is to have the test runner not report failures/compare expectations for anything other than errors.  

cc @munificent

**Comment by srawlins** [comment]
> I think there might be an option 4 which is to have the test runner not report failures/compare expectations for anything other than errors.

I would be fine with that. The "test runner" in this case is basically `dartanalyzer`, which sends its results to some parent process (`test.py` or something) as JSON. So the logic to "only report compare expectations for errors" is then encoded in `dartanalyzer` (via `--no-warnings`, `--no-hints`, or just as the base mode), or encoded in `analysis_options.yaml` and interpreted by `dartanalyzer`. I think all of these solutions can lead to @bwilkerson 's comment about removing `dartanalyzer` and relying only on `dart analyze`.

**Comment by leafpetersen** [comment]
> I would be fine with that. The "test runner" in this case is basically `dartanalyzer`, which sends its results to some parent process (`test.py` or something) as JSON. So the logic to "only report compare expectations for errors" is then encoded in `dartanalyzer` (via `--no-warnings`, `--no-hints`, or just as the base mode)

I don't think we're talking about the same thing, are we?  I think what I'm talking about is the logic encoded in [this file](https://github.com/dart-lang/sdk/blob/main/pkg/test_runner/lib/src/static_error.dart).

**Comment by srawlins** [comment]
Ah interesting. I had not seen that list of codes that the analyzer may emit which should be considered "warnings." I'll investigate whether this is what we want, as this is only used in `isWarning` which is only used in [test_file.dart](https://github.com/dart-lang/sdk/blob/main/pkg/test_runner/lib/src/test_file.dart#L82) in... an unexpected way, `isRuntimeTest`.

But I think I see now where you're going: we could encode all of the logic about whether a reported diagnostic needs to be expected, in this code. `dartanalyzer` or `dart analyze` could happily report unused variables or dead code, and this file would have the list of uninteresting warnings to drop on the floor.

**Comment by leafpetersen** [comment]
> and this file would have the list of uninteresting warnings to drop on the floor.

Yes, that would work.  Or more generally, if we can resolve the issue mentioned in comments about not being able to distinguish warnings and errors, we could just have it ignore all warnings programatically.

**Comment by bwilkerson** [comment]
> ... being able to distinguish warnings and errors ...

I believe that the JSON output format from `dart analyze` has that information.

**Comment by eernstg** [comment]
I think it could be useful to look at the underlying assumptions associated with the options.

We have an implied classification of diagnostic messages: We're testing compile-time errors in language tests because they are part of the language, and we are not testing hints in the same way. (Presumably there are some analyzer specific tests for them). Similarly, compile-time errors are reported by all tools, but hints are only reported by analyzer based tools.

The traditional classification of a warning is that it is part of the language, but it doesn't prevent compilation. So we're testing it in language tests, for the CFE as well as the analyzer.

The language team has all but decided that warnings should not be part of the language (discussed, e.g., at the meeting April 20, 2022, but I can't see any explicit decisions). The effort managed via this issue would be based on the assumption that this decision has been made, or will be made.

With that in mind, I think we have the following properties:

- Option 1, ignore all warnings: Stop testing non-errors.
- Option 2, use `analysis_options.yaml` files: Test the same diagnostic messages as today, based on a specific listing in the options file. Of course, this approach could also be used to test any subset of non-errors that we would want to test.
- Option 3, specify more warnings etc in the tests themselves: Presumably, tools would then report all diagnostic messages, and the test runner would process them, and tests would be rewritten to expect all of them (or some of them, e.g., using `analysis_options.yaml`).
- Option 4, make the test runner tolerate and ignore all warnings from tools: Stop testing all non-errors and ignore all non-error expectations in tests.

Option 3 could be done at many different levels, but it is potentially a major rewrite of a very large number of tests. Also, it would presumably cause many tests to have testing code for "unused local variable" and such, in spite of the fact that this is not at all the intended purpose of that test (or the test would be rewritten such that the "unused local variable" message isn't emitted any more). I agree that this option is not very attractive.

Option 1 and 4 imply that we simply stop testing non-errors. In order to maintain the test coverage we could migrate the approx. 771 tests (`co19`, `language`, and more) where the test expectation is a `STATIC_WARNING` (and there might be additional tests where a warning is tested using some other approach). So they (at least the test _cases_ testing warnings) would be deleted from `language`, `co19`, etc., and they would presumably be migrated as needed and made part of the analyzer test suite.

If we wish to take all warnings out of the language then it seems likely that we would ask for changes in the CFE such that it only reports errors. This means that we would need to change those approx. 771 tests in _any_ option, because they shouldn't expect any diagnostics from the CFE any more.

Option 2 would allow us to keep testing essentially the same diagnostic messages that we're testing today (in the analyzer, at least). So we wouldn't need to worry about the loss of testing coverage. On the other hand, these approaches would introduce a new classification that basically reproduces the old one ("hint" vs. "serious hint" ;-). We might then have the same thing, just wearing new clothes, and that might not be a good foundation for the future evolution of the Dart test suite (.. did we draw the line between hints and serious hints correctly? .. do we want to have more lines in the future?).

Finally, we have a number of errors which are opinionated in the sense that they do not have to stop the compilation. In other words, they might as well have been warnings. So why would they be allowed to escape this clean-up operation? For example (just mentioning a few):

- A return statement returns a non-voidy expression in a function whose declared return type is `void`.
- A class `C<... X extends B ...>` declares a member named `C` or a member named `X`.
- A setter must have return type `void`.
- A getter return type must be assignable to the corresponding setter parameter type.
- A final variable with a nullable type and no initialization is not initialized to null, those cases are errors.
- A static method could shadow an inherited instance member (call sites can always be disambiguated), but it is an error.
- Mixin declarations could have factory constructors, but it is currently an error.
- An extension method named `toString`, `operator ==` etc. is an error.

I'm tempted to recommend a rather strict approach: Use option 1 or 4 to ignore all non-error diagnostics in language tests and clean up the tests such that they don't expect any non-errors. (With option 4 we could presumably keep all the non-error expectations because they can be ignored by the test runner, but it would be rather confusing for a reader of the test).
