### ISSUE TITLE
Function.toString() does not work as expected with @Annotation

### ISSUE THREAD

**Issue by jacobaraujo7** [dart-lang/sdk#50939]
Function.toString() seems to ignore the annotations added to the parameters.
Example:
```dart
void main() {
  print((@MyAnnotation() String data ) {});
}

class MyAnnotation {
    const MyAnnotation();
}

```

Dart VM print:
```
Closure: (String) => Null
```

Perhaps the correct behavior should be:
```
Closure: (@MyAnnotation() String) => Null
```

Is there any reason to omit this or is this a bug?

**Comment by lrhn** [comment]
I'm pretty sure this is working as intended.

The string being printed is the *type* of the closure. The annotation is not part of that, it's just something which exists in the source code (and might be accessible using `dart:mirrors`).

While it's probably *possible* to make the closure `toString` include the source text of annotations, it will certainly have some runtime-cost. (Also, on the web there is no need to retain annotations at all, since there is no `dart:mirrors`. Don't know if the VM can exclude them when compiling for Flutter too.)

**Comment by jacobaraujo7** [comment]
Thanks for the quick response @irhn.
I understand that the main use of annotations is in reflection, but I feel this is not expected behavior as annotations have been declared.
That's why it looks like a bug to me.

Would it be too expensive to do this?

**Comment by mraleph** [comment]
This is working as intended. We don't include annotations into AOT snapshots to save space and neither does `dart2js`. We could change this in JIT - but that would introduce a discrepancy between JIT and AOT. 

Also note that the annotation is attached to the parameter not the parameter's type - so it is actually strange to include it when parameter name itself is not included into the `toString` output.
