### ISSUE TITLE
Breaking changes in dart 2.19

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#50953]
This might be a bit late to the party, but I"m concerned about a number of breaking changes in dart 2.19

File.create
CastError
path change from pub.dartlang.org to pub.dev

When I first became aware of the above changes (well the last one I only encountered today) I didn't realise the impact nor how close to a 3.0 release we are.

I primarily build CLI apps (and maintain the DCli package). I've now encountered problems (in the wild) with the above changes breaking apps.
I do wonder, given how close we are to a 3.x release, whether these breaking changes should have been left to the 3.x release.

I've largely worked around the issues but worry it might have an extensive impact on the other CLI apps published via pub.dev.

**Comment by mraleph** [comment]
I think there is no way we can unroll any of these changes. The release process for 2.19 and corresponding Flutter release is basically almost done. 

`File.create` change is in 2.19 since August and had been propagated into Flutter's beta. Removing it now would require breaking change again. It's a non-starter. 

> CastError

I am not sure about `CastError` removal. This is supposed to be 3.0 specific change and should not be 2.19 AFAIK. Can you clarify? 

> path change from pub.dartlang.org to pub.dev

Can you clarify what this refers to? I would assume that the hostname `pub` talks too is an implementation detail. Similarly anything in `.pub_cache` is an implementation detail. So if `pub` changes `pub.dartlang.org` to `pub.dev` somewhere it is not a breaking change per se.

/cc @mit-mit

**Comment by lrhn** [comment]
`CastError` was changed a little in 2.19. Changelog says:

> * The class `CastError` is deprecated, and all implementation specific classes implementing `TypeError` or `CastError` now implement both. In a future release, `CastError` will be removed. See issue https://github.com/dart-lang/sdk/issues/40763 for details.

The deprecation is not breaking, and the type change *shouldn't* be. 
If code depends on a `CastError` or `TypeError` being thrown, they still will. If code depends on a `CastError` or `TypeError` *not* being thrown where the other one is, it might become confused, but we do not consider it a breaking change to change the behavior of code which throw an error.

(We still have a problem with the text message of cast errors, but that's cosmetic.)

**Comment by mit-mit** [comment]
> I've now encountered problems (in the wild) with the above changes breaking apps.

More concrete details about these would be appreciated.

**Comment by mit-mit** [comment]
@bsutton can you please respond with further information? If not, we'll have to close this issue as not actionable...

**Comment by bsutton** [comment]
Close it out.

I do think File.create is going to be somewhat disruptive but it is what it
is.

My statement about CastError was incorrect - I"ve been playing with dart
2.12, 2.18, 2.19 and 3.x this week and got my wires crossed.

> path change from pub.dartlang.org to pub.dev

I was referring to the directory structure of the .pub-cache
I have code that compiles a cli package directly from .pub-cache and the
dcli library has apis that let users ask questions like 'is package X
installed' 'is package x globally activated'. To implement this I scan the
.pub-cache directory structure.
This change will probably only affect fairly specialised packages like dcli.

**Comment by lrhn** [comment]
Thanks. 😄 
The `CastError` removal will probably be disruptive when 3.0 lands, but probably also not the biggest change.
