### ISSUE TITLE
[Changelog] Pub `funding` in 2.19 or 2.18?

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/sdk#50988]
@sigmundch was `funding` added in 2.19 or 2.18? It's in the [2.19 section of the changelog](https://github.com/dart-lang/sdk/blob/eba218805330eeaf59e49013acfe8b9a1314cc6c/CHANGELOG.md?plain=1#L441), but mentioned in the [2.18 release blog post](https://medium.com/dartlang/dart-2-18-f4b3101f146c#:~:text=we%20now%20support%20a%20new%20funding%20tag%20in%20the%20pubspec). 

Prepping the 2.19 blog post now so if you could confirm that'd be great!

**Comment by sigmundch** [comment]
I think you probably meant to ask @sigurdm :smiley:

**Comment by MaryaBelanger** [comment]
Yes, thanks Siggi! 😅

**Comment by sigurdm** [comment]
Well spotted! Here is a summary of my understanding here:

The **funding** feature is mainly server-side, so it can basically be used from any version of dart.
I think that support on the server was landed prior to the release of 2.18 - hence the blog post.

What the line in the CHANGELOG refers to is that we added support in the client for our **spell-checking** to allow 'funding' as a top-level entry in pubspec.yaml: https://dart.googlesource.com/pub.git/+/7d30cf0b%5E%21/

Seems like this was landed in the client after 2.18: https://github.com/dart-lang/sdk/commit/c02c9753c34874e12df9cf787cf34c4211d5dfaf#

This has relatively minor implications, since the word 'funding' isn't similar to any of the other recognized words, and we only warn if an unrecognized word is close to a recognized one - so the only difference is that if you write something like 'fumding' you will not get a warning with a 2.18 sdk.

Maybe we can remove it from the changelog notes if it creates too much confusion.

**Comment by MaryaBelanger** [comment]
Oh ok well then the changelog entry makes sense given that context. I don't think we need to remove it; I'm probably the only person examining it that closely 😅 _and_ I only noticed it by chance anyway.

Thanks @sigurdm!
