### ISSUE TITLE
[CFE] Implicit 'break' is not generated in a switch

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#50994]
Part of https://github.com/dart-lang/sdk/issues/49749.

```dart
String test(int value) {
  String x = "";
  switch (value) {
    case == 1:
      x = "matched 1";
    case == 2:
      x = "matched 2";
    default:
      x = "default";
  }
  return x;
}

main() {
  print(test(2));
}
```

Kernel:
```
 static method test(core::int value) → core::String {
    core::String x = "";
    #L1:
    {
      final core::int #t1 = value;
      final core::int #t2 = -1;
      final core::bool #t3 = false;
      if(!#t3 && #t1 =={core::num::==}{(core::Object) → core::bool} 1) {
        #t2 = 0;
        #t3 = true;
      }
      if(!#t3 && #t1 =={core::num::==}{(core::Object) → core::bool} 2) {
        #t2 = 1;
        #t3 = true;
      }
      switch(#t2) {
        #L2:
        case #C1:
          {
            {
              x = "matched 1";
              break #L1;
            }
          }
        #L3:
        case #C2:
          {
            {
              x = "matched 2";
            }
          }
        #L4:
        default:
          {
            x = "default";
          }
      }
    }
    return x;
  }
```

Note that there is no `break` after `x = "matched 2";`. We currently do not allow fall-through in switch statements, so exception is thrown.

/cc @chloestefantsova @johnniwinther 

`co19/LanguageFeatures/Patterns/switch_statement_A07_t01` test fails with RuntimeError because of this bug.

**Comment by johnniwinther** [comment]
@stereotype441 The `isTerminating` argument passed to `handleMergedStatementCase` is `true` for the `case == 2` case. It looks like the whole case is considered unreachable already after the call to `switchStatement_beginAlternative` for `case == 2`, but I'm not sure if I'm reading the model data correctly.

**Comment by stereotype441** [comment]
I think I know what the problem is.  I'll try to get a fix out for review today.

**Comment by stereotype441** [comment]
This is happening because of a combination of two things:
1. Flow analysis doesn't understand `==` patterns yet; as a result, `case == 1:` is incorrectly considered to match everything.
2. Since `case == 1:` is considered to match everything, the remaining cases are considered unreachable; we only add a synthetic break if the bottom of a case body is reachable, so we're not adding any synthetic breaks.

Obviously issue 1 needs to be fixed, and it will be, once I've fully implemented flow analysis for patterns.

Technically that would be sufficient to address this issue, however I think that to avoid future confusion for CFE and back-end developers (and to make the system more robust in the event of flow analysis bugs), it would be better to go ahead and insert synthetic breaks even for case blocks that are considered reachable.

Flow analysis already has a notion of "local reachability" (i.e. the ability to figure out whether a given point in the code control is reachable from some previous point, rather than reachable globally).  So it should be straightforward to change things so that we insert a synthetic break whenever the bottom of the case block is locally reachable from its top.  I'll send out a CL to do that shortly.

**Comment by stereotype441** [comment]
Will be addresed by https://dart-review.googlesource.com/c/sdk/+/278897.
