### ISSUE TITLE
Analyzer doesn't error on apps with a 2.9 entry point

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#51007]
The analyzer now correctly errors when a file chooses an old language version (e.g. `// @dart=2.9` marker in a file). However, it looks like it doesn't validate if the default language version for the main entry point is below 2.12:

1. `dart create reproapp`
2. Edit the `pubspec.yaml` to have an SDK constraint of `>=2.9.0 <4.0.0`
3. run `dart pub get`
4. run `dart analyze .`

Expected result: error that `bin/main.dart` doesn't have null safety
Actual result: no errors or warnings

See https://github.com/dart-lang/pub/issues/3730 for a discussion of the `pub get` part of this behavoir.

**Comment by scheglov** [comment]
@bwilkerson

**Comment by bwilkerson** [comment]
> Edit the `pubspec.yaml` to have an SDK constraint of `>=2.9.0 <4.0.0`
> ...
> Expected result: error that `bin/main.dart` doesn't have null safety

I can see two possibilities here.

The first is that we say that any library without a language override comment is implicitly analyzed at the lower bound of the SDK constraint, in which case we need an error in every library without a language override comment.

The second is that we say that it's invalid to specify a lower bound for the SDK constraint that's less than 2.12 and we have a single error in the `pubspec.yaml` file indicating that the lower bound needs to be updated to `>=2.12`.

I would far prefer the second because it isn't helpful to the user to have multiple diagnostics for the same issue, let alone to have them in places other than where the issue can be fixed.

Assuming you agree, the next question is where to produce the diagnostic. I'd like to propose that it makes more sense for `dart pub` to produce the message. It's earlier in the development cycle, and it's a required step, whereas running `dart analyze` is an optional step. Also, it makes sense to me that if we're not supporting pre-2.12 code that `pub` should also produce an error when being asked to run on pre 2.12 code.

**Comment by lrhn** [comment]
> The first is that we say that any library without a language override comment is implicitly analyzed at the lower bound of the SDK constraint, in which case we need an error in every library without a language override comment.

That's what *must* happen. That will be the default language version for the package, as configured in `package_config.json`, and it is language version of the file.
The analyzer (and every other tool in the 3.0.0 SDK) should refuse to *parse* such a file, since it's not in any recognized language. The past is a foreign country.

If that feels too strict, remember you can always add `//@dart=2.12` and see what fails. Or migrate, which we should help you doing.

I'd also report every import of a library which is language version below 2.12, from a library with a recognized language version (>= 2.12) as a separate error. This is the boundary of your valid program, where you need to do something to make the entire program valid. You need to know about each of these.

If you have invalid files in your own package, ones which might not even be imported by anyone (like unmigrated tests), then I'd also be fine with giving individual errors for each `.dart` file which has language version \<2.12.

If that feels like too many errors, it's probably because the entire package is below the water level.
That likely means that its own SDK min-constraint is below 2.12. The alternative is that it has many files with override markers, which is going to be rare.

How about giving a warning if the current package has a min-SDK constraint below 2.12, and it contains at least on `.dart` file. Report that directly on the `pubspec.yaml` file.

That would still allow a package with no Dart files to not have any errors.

If there is at least on Dart file, that file will have an error too. If the error is that it has no language marker and a language version below 2.12, you can choose to not issue an extra warning, but it might be confusing to open the file in an editor and see nothing. An individual error per file, like "This Dart file has language version 2.8, which is not supported by the current SDK."
If it has a language marker, then either it too is below 2.12, and there should be an individual warning that this file's version is no longer supported, at the `//@dart=2.8` line. "Dart language version 2.8 is not supported by your current SDK.", or it's above 2.12, and then there is also a warning for having a marker above the min-SDK level.

**Comment by mit-mit** [comment]
> I'd like to propose that it makes more sense for dart pub to produce the message

That was already discussed here: https://github.com/dart-lang/pub/issues/3730

**Comment by mit-mit** [comment]
> The first is that we say that any library without a language override comment is implicitly analyzed at the lower bound of the SDK constraint

Slight tweak: libraries should be analyzed against the language version that is in the `package_config.yaml`. For the repro I mentioned at the top, that has:

```
...
    {
      "name": "yaml",
      "rootUri": "file:///Users/mit/.pub-cache/hosted/pub.dev/yaml-3.1.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "reproapp",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.9"
    }
```

**Comment by srawlins** [comment]
> The analyzer (and every other tool in the 3.0.0 SDK) should refuse to parse such a file, since it's not in any recognized language.

I think this would be quite a departure from our current policy (really, every editor's language tooling's policy) of doing our best to help the user hone in on what errors they need to fix in order to fix their program. We do error recovery etc. When a library contains `int i = ;`, we don't abandon the entire library and then produce many follow-on errors that stem from an entire library being un-parsable. I think this would be a real disservice to our users, letting one `// @dart=2.9` comment generate hundreds of errors across their package, with no ordering or sense of what file has a bad version.

> How about giving a warning if the current package has a min-SDK constraint below 2.12, and it contains at least on .dart file. Report that directly on the pubspec.yaml file.

This is probably doable and is essentially what @bwilkerson suggested. We may not have a good (or performant) mechanism for the "and it contains at least one .dart file" part. But I think we could report any time we analyze a pubspec.yaml with a too-low SDK version constraint and call it a day.

**Comment by mit-mit** [comment]
> But I think we could report any time we analyze a pubspec.yaml with a too-low SDK version constraint and call it a day.

I think that wouldn't work for non-code packages (e.g. packages containing just assets) though? For example something like https://pub.dev/packages/cupertino_icons, which is still using a lower bound of 2.17, but since it has no Dart code I think is still compatible with Dart 3?

**Comment by bwilkerson** [comment]
> I think that wouldn't work for non-code packages (e.g. packages containing just assets) though?

I don't understand why not. Do we want to allow non-code packages whose lower bound is below 2.12, or do we want to report such a package?

> ... which is still using a lower bound of 2.17 ...

Which wouldn't be reported because the lower bound is greater than or equal to 2.12.

**Comment by mit-mit** [comment]
> Do we want to allow non-code packages whose lower bound is below 2.12, or do we want to report such a package?

Language versioning only applies to the language, so why not for a package that contains no Dart code?

However, from discussion with @jonasfj and @sigurdm it sounds like they are willing to re-consider doing the `pub get` change discussed in https://github.com/dart-lang/pub/issues/3730 if the present change in the analyzer is too complicated to get done.

**Comment by bwilkerson** [comment]
> Forbid this kind of SDK constraints in the root `pubspec.yaml` ...

Out of curiosity, will we allow `>=2.12.0 < 4.0.0`? It seems like a reasonable constraint to me, but I haven't really thought about it much.

> I see how the analyze doesn't necessarily have a good place to hang this error, if the file in question is an entrypoint.

I'm guessing that by "entrypoint" you mean that the library has a `main` method. In which case, one logical place to hang such an error is on the `main` method.

My concern is with packages that use a test framework in which every test file contains a `main`. Producing an error for every `main` method would be noisy.

The design principle we should follow here is that every error in the code should be reported exactly once. There's one error here: the minimum language level for the package is below 2.12. The ideal is to report this error in exactly one place: the location where the user needs to make a change in order to fix the problem. While the default language version comes from the `package_config.json`, we generally don't suggest that users edit that file, hence the suggestion that the error should be reported against the `pubspec.yaml` file.

**Comment by sigurdm** [comment]
> Out of curiosity, will we allow >=2.12.0 < 4.0.0? It seems like a reasonable constraint to me, but I haven't really thought about it much.

Yes, I believe we will - pub is already treating `>=2.12.0 <3.0.0` and `>=2.12.0 <4.0.0` as synonyms (to allow for backwards compatibility).

**Comment by vsmenon** [comment]
Did we agree on action items here?

**Comment by sigurdm** [comment]
My understanding is that we forbid a root pubspec with a `>=2.9.0 <4.0.0` from resolving in pub.
And we also forbid those packages from being uploaded with a server-side check on pub.dev.

So the analyzer doesn't have to update.
