### ISSUE TITLE
[CFE] Object pattern should invoke getter even if its value is unused.

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51012]
```dart
class A {
  int get bar {
    print('OK');
    return 42;
  }
}

main() {
  var A(bar: _) = A();
}
```

Kernel:
```
    final dynamic #t1 = new foo::A::•();
    final core::bool #t2 = true;
    final dynamic #t3 = #t1;
    if(#t3 is foo::A) {
      #t2 = false;
    }
    if(#t2)
      throw new _in::ReachabilityError::•();
```

Getter `A.bar` is not called although the matching procedure for object pattern requires us to call getter and then match its value against a subpattern.

`co19/LanguageFeatures/Patterns/object_A07_t06` test fails with RuntimeError due to this bug.

/cc @chloestefantsova @johnniwinther

**Comment by lrhn** [comment]
(As a drive-by comment, we don't want to avoid reading the getter here because then `bar: _` does absolutely nothing. The pattern is only allowed if `A` is known to have an `x` getter (or is `dynamic`). In the former case, the pattern does nothing if you don't read, in the latter there is no way to check whether the value has an `x` getter other than reading it. So `bar: _`'s only useful effect is to check that `.bar` doesn't throw. This differs from a map pattern like `{"x": _}` which actually provides the useful information that the map has `"x"` as a key, even if it doesn't need to read the value.)
