### ISSUE TITLE
[Patterns] Getter is not invoked in case of Object pattern and wildcard

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#51029]
The following [test](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Patterns/object_A07_t06.dart) fails now on `dart2js`, `dart2wasm-hostasserts-linux-x64-d8`, `dartdevk`, and `dartk` configurations. The code is
```dart
String log = "";

void logger(String s) {
  log += s;
}

main() {
  var Square(area: _) = Square(2, logger);
  Expect.equals("Square.area", log);
}
```
Getter `Square.area` adds `"Square.area"` to log when called. Test fails with
`Expect.equals(expected: <Square.area>, actual: <>) fails.`

It means that getter `area` is not called at all. According to the [spec](https://github.com/dart-lang/language/blob/c47220f82fcde96d171bc7fd387392ef70e2bbb0/accepted/future-releases/0546-patterns/feature-specification.md?plain=1#L2877) it should be called but its value should be ignored.

>     2.  Otherwise, for each field `f` in `p`, in source order:
> 
>         1.  Call the getter with the same name as `f` on `v`, and let the result
>             be `r`. The getter may be an in-scope extension member.

cc @eernstg

**Comment by eernstg** [comment]
Yes, my expectation is also that the relevant rule is 'the getter is called, but its value is ignored'.

**Comment by eernstg** [comment]
Perhaps there is a source of confusion here: I seem to remember that there was some debate about not invoking operator `[]` in cases like a map pattern containing a `someKey: _`, because it's sufficient to call `containsKey`. However, we don't have anything like `containsKey` with an object (we can tear off a non-operator method in order to see whether it exists, but for a getter we can't check that it's there without invoking it).

Found https://github.com/dart-lang/language/issues/2671: Contains discussion about this topic, has not been settled.

Found https://github.com/dart-lang/language/issues/2634: Same topic comes up, not settled.

This means that we haven't settled whether the wildcard pattern will actually retrieve the value (and then immediately discard it) when the enclosing pattern is a listPattern or mapPattern.

For the objectPattern I think it has been settled: The getter must be invoked.

**Comment by munificent** [comment]
Yes, I think the getter should be invoked. If you don't want to call the getter... don't write it in the object pattern. :)
