### ISSUE TITLE
Output differs on dartpad from natively compiled

### ISSUE THREAD

**Issue by AlexGalitsky** [dart-lang/sdk#51036]
**Hi**
On [dartpad](https://dartpad.dev/) , this code will display: **A C G B W Z D E F**
```dart
Future<void> main() async {
  print('A');

  await Future(
    () {
      print('C');
      Future(() => print('D'));
      Future(() => print('E')).then((value) => print('F'));
      Future.microtask(() => print('W'));
      Future.microtask(() => print('Z'));
      print('G');
    },
  );

  print('B');
}
```

but this code with **async** keyword will display: **A C G W Z B D E F**

```dart
Future<void> main() async {
 print('A');

  await Future(
    () async {
      print('C');
      Future(() => print('D'));
      Future(() => print('E')).then((value) => print('F'));
      Future.microtask(() => print('W'));
      Future.microtask(() => print('Z'));
      print('G');
    },
  );

  print('B');
}
```

After compiling this code on Windows, the output will be:  **A C G B W Z D E F**
Why?

> dart --version
Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"

> Windows 11 Pro, version 22H2, os build 22621.169

Thanks

**Comment by lrhn** [comment]
Because the `async` makes the the function return a future, which the `await` will wait for. 
That future will be completed at a later point depending on the implementation of `async` methods on the platform.

Apparently native and web behaves slightly differently on an `async` function containing no `await`s. That's OK, we promise nothing except "in a later microtask".

**Comment by a-siva** [comment]
based on the above comment I am going to close this as 'closed-as-intended'
