### ISSUE TITLE
Inheritance and compilation

### ISSUE THREAD

**Issue by LVBiomas** [dart-lang/sdk#51048]
I can't understand why this oversimplified snippet doesn't compile, while IMO it should:
```
abstract class BaseGenericClass<T> {
  final T _arg;
 
  BaseGenericClass(this._arg);
}

class GenericClass<T extends AbstractArgClass> extends BaseGenericClass<T> {
  GenericClass() : super(ArgClass());
}

abstract class AbstractArgClass {}

class ArgClass extends AbstractArgClass {}
```

Introducing an otherwise useless class between GenericClass and BaseGenericClass solves the problem:
```
abstract class BaseGenericClass<T> {
  final T _arg;
  
  BaseGenericClass(this._arg);
}

class IntermediateClass<T extends AbstractArgClass> extends BaseGenericClass<T> {
  IntermediateClass(T arg) : super(arg);
}

class GenericClass extends IntermediateClass {
  GenericClass() : super(ArgClass());  
}

abstract class AbstractArgClass {}

class ArgClass extends AbstractArgClass {}
```

**Comment by julemand101** [comment]
Your problem is that you cannot guarantee the following is valid for all kinds of `T` which extends `AbstractArgClass`:
```dart
class GenericClass<T extends AbstractArgClass> extends BaseGenericClass<T> {
  GenericClass() : super(ArgClass());
}
```
E.g. if we have another class that extends `AbstractArgClass` like:
```dart
class AlternativeArgClass extends AbstractArgClass {}
```

And then we try use `GenericClass` with our own provided generic argument:
```dart
GenericClass<AlternativeArgClass>()
```

It would not be valid since `GenericClass` would then need to extend from `BaseGenericClass<AlternativeArgClass>` which require its parameter to be of the type `AlternativeArgClass`. But the default constructor for `GenericClass` will try do `super(ArgClass())` which fails since `ArgClass` is not compatible with `AlternativeArgClass`.

**Comment by LVBiomas** [comment]
Thank you, didn't think of that!
