### ISSUE TITLE
Need null check after ??=

### ISSUE THREAD

**Issue by Lysmi** [dart-lang/sdk#51092]
If I use "??=" dart analyzer don't understand that variable can not be null. 
Example:
```dart
static void regCommand(String command, Function action, {bool? isMustRemove}) {
      teleDart.onCommand(command).listen((message) {
          isMustRemove ??= false;
          if (isMustRemove) {
              teleDart.deleteMessage(message.chat.id, message.message_id);
          }
    });
  }
```
This code have error: 
![image](https://user-images.githubusercontent.com/40596918/213900806-f9690580-666f-43a4-aece-d19730792c71.png)

But in reality isMustRemove can not be null. Of course, if I use {bool isMustRemove = false} is solve this case, but we have more cases with analyze null. 
And if I write:
```dart
static void regCommand(String command, Function action, {bool? isMustRemove}) {
      teleDart.onCommand(command).listen((message) {
          isMustRemove ??= false;
          if(isMustRemove != null) {
              if (isMustRemove) {
                  teleDart.deleteMessage(message.chat.id, message.message_id);
              }
          }
    });
  }
```
or 
```dart
static void regCommand(String command, Function action, {bool? isMustRemove}) {
      teleDart.onCommand(command).listen((message) {
          isMustRemove ??= false;
          if (isMustRemove as bool) {
              teleDart.deleteMessage(message.chat.id, message.message_id);
          }
    });
  }
```
all work.

**Comment by lrhn** [comment]
This is a limit of the Dart type inference algorithm.

The variable is declared in another function than where it's assigned. That's bad for inference because the function doing the assignment can escape, and that means that any other computation can potentially perform an assignment.

In this particular case, that can't happen because there is only one assignment, ever, but the inference algorithm is one-pass, so it doesn't go back and report that nothing bad can happen, it just gives up when it sees the captured assignment.

What you can do here is:
```dart
static void regCommand(String command, Function action, {bool? isMustRemove}) {
      teleDart.onCommand(command).listen((message) {
          if (isMustRemove ??= false) {
              teleDart.deleteMessage(message.chat.id, message.message_id);
          }
    });
  }
```
instead of splitting the assignment and the reading.

**Comment by asashour** [comment]
This was requested in https://github.com/dart-lang/language/issues/1536

**Comment by lrhn** [comment]
Good find. Closing this as duplicate.
