### ISSUE TITLE
[analyzer] `unnecessary_null_comparison` when comparing two `null`s

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#51122]
Yes, this is strange code, but:

```dart
void f() {
  if (null == null) {
    print('');
  }
}
```

should trigger `unnecessary_null_comparison`.

Or I guess it could be part of a new diagnostic `unnecessary_comparison`, for comparing literals, e.g. `1 == 2`, `'' == ''`, etc.

**Comment by bwilkerson** [comment]
There's no conflict between diagnostics (ever). It's because the hint was designed to flag an explicit comparison of `null` with something that's non-nullable, which `null` isn't.

I don't think it's worth checking to catch cases where we're comparing a known `null` value to another known `null` value.

**Comment by asashour** [comment]
Clear, thanks.
