### ISSUE TITLE
noSuchMethod on property Visual Studio Code, compile-time error

### ISSUE THREAD

**Issue by brilliapps** [dart-lang/sdk#51133]
Flutter 3.7
noSuchMethod can be used on properties. I did a simple test.
```dart

class abcdefghijk {
  noSuchMethod(Invocation invocation) =>
      'Got the ${invocation.memberName} with arguments ${invocation.positionalArguments}';
}

void main(List<String> args) async {
  var ewqer=abcdefghijk();
  ewqer.id=10;
...

```
In Visual Express and in the console (i recognize this as a compile time error) i get information of an error.

Did i do something wrong or as it wrongly seems to me dart shouldn't throw any error?

**Comment by julemand101** [comment]
What you are doing is giving you a static error from the analyzer since Dart can see the method/property does not exist for your class.

The `noSuchMethod` is meant to be called if we end up calling the method at runtime which means the analyzer would need to accept our code in the first place. You can do that by enforcing the type of `ewqer` to `dynamic` which disables the static analysis for this variable and allow us to call whatever we want on it:

```dart
class A {
  @override
  noSuchMethod(Invocation invocation) => print(
      'Got the ${invocation.memberName} with arguments ${invocation.positionalArguments}');
}

void main(List<String> args) async {
  dynamic ewqer = A();
  ewqer.id = 10;
}
```

Another way this could happen is if `A` promise to implement some interface but does not actually implement all methods/properties of that interface:
```dart
abstract class AInterface {
  set id(int id);
}

class A implements AInterface {
  @override
  noSuchMethod(Invocation invocation) => print(
      'Got the ${invocation.memberName} with arguments ${invocation.positionalArguments}');
}

void main(List<String> args) async {
  var ewqer = A();
  ewqer.id = 10;
}
```

**Comment by brilliapps** [comment]
Wanting to answer immediately, thank you julemand101, the first example did the job. I need to process your answer better, but it just works! May i just suggest that a documentation page like https://api.flutter.dev/flutter/dart-core/Object/noSuchMethod.html is clear about it - maybe one or two sentences more, that a given variable should be declared dynamic or whatever? Maybe, i would never figure it out on my own :) . Thank you again.

**Comment by julemand101** [comment]
See the section called "noSuchMethod()" in: https://dart.dev/guides/language/language-tour#extending-a-class

I think it is described in fairly good details. But a link to that description could be added to the description on api.dart.dev.

**Comment by brilliapps** [comment]
Yeah. It's there, and clearly explained on language tour. Great! Have a nice day.

**Comment by brilliapps** [comment]
Excuse me. If you are still around here :). Just did some quick tests not thinking if a way of doing something is good or not, just to know what options do i have and accidently noticed this (error in Visual Studio code - sorry i've just noticed i mistakenly said VisualExpress before).
Having this:
 
`dart
abcdefghijk ewqer = abcdefghijk();
` 
This doesn't work:

```dart
ewqer = ewqer as dynamic;
ewqer.id = 10;

```
But this does work:

```
 ewqer = ewqer as dynamic;
 (ewqer as dynamic).id = 10;

``` 
Is it ok? Shouldn't both examples work equally?

**Comment by eernstg** [comment]
In this example ..

```dart
ewqer = ewqer as dynamic;
ewqer.id = 10;
```

.. the variable `ewqer` has already been declared and it has type `abcdefghijk`. You're allowed to assign `ewqer as dynamic` to it, because you are always allowed to assign an expression of type `dynamic` to any non-final variable. This doesn't change the fact that `ewqer` has the declared type `abcdefghijk`. Hence, `ewqer.id` is a compile-time error, because `abcdefghijk` does not have an `id` in its interface.

Evaluation of `(ewqer as dynamic).id = 10` is accepted because it invokes a getter `id` (or tears off a method named `id`, who knows) on an expression of type `dynamic`, and you are always allowed to access whatever member you want on a receiver of type `dynamic`. It will then be checked at run time that you actually have the given member, and it actually permits this kind of invocation.

**Comment by brilliapps** [comment]
Now i got it :) . Thank you for your reply.
