### ISSUE TITLE
[vm_service] BoundField.toJson() exception

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#51141]
`BoundField.toJson` is currently trying to call `String.toJson` (which does not exist) in, which results in exception. Here is the code that throws:

https://github.com/dart-lang/sdk/blob/8766952c138171ebf9486f2728b956303f97a726/pkg/vm_service/lib/src/vm_service.dart#L2945

Related: https://github.com/dart-lang/sdk/issues/49728

**Comment by annagrin** [comment]
@bkonyi @derekxu16 FYI, I encountered this while implementing records in dwds. I suspect we encounter the problem (and others don't) because we use `VmServiceConnection`, but not 100% sure.

**Comment by derekxu16** [comment]
`package:vm_service v10.1.1` has been published, which should fix the `toJson()` problem.

https://pub.dev/packages/vm_service/versions/10.1.1

The SDK changes themselves are blocked from landing, because the SDK changes related to `package:vm_service v10.1.0` are still blocked from landing (https://github.com/dart-lang/sdk/issues/51003#issuecomment-1406787143). I will wait until these CLs land to close this issue.
