### ISSUE TITLE
Add lengthWhere method on Iterable

### ISSUE THREAD

**Issue by dbspoudel** [dart-lang/sdk#51151]
A new method on Iterable to find the length that satisfies the test.

`  int lengthWhere(bool test(E element)) {
    assert(this is! EfficientLengthIterable);
    Iterable<E> itle = WhereIterable<E>(this, test);
    int count = 0;
    Iterator itor = itle.iterator;
    while (itor.moveNext()) {
      count++;
    }
    return count;
  }`

**Comment by lrhn** [comment]
Sounds like it should be named `countWhere`. 

I see no reason to not just use `.where(test).length` for that computation. While you could a small overhead, by avoiding the intermediate iterable, the implementation above doesn't.
We provide cheap composable iterable operations rather than trying to have specialized versions for each possible combination.

(The cheaper implementation would avoid allocating the `WhereIterable`, and be something like:
```dart
  int countWhere(bool test(E element)) {
    int count = 0;
    for (var element in this) if (test(element)) count++;
    return count;
  }
```
The saving isn't going to be big.)
