### ISSUE TITLE
Failed to deserialize the passed arguments to the new isolate. (LinkedHashMap)

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#51226]
This is separated from #50082.
See https://github.com/Dart-Code/Dart-Code/issues/4371, as well.

Dart SDK version: 3.0.0-179.0.dev (dev) (Unknown timestamp) on "linux_x64"

```
Connecting to VM Service at http://127.0.0.1:33823/qkrWrcyjLfs=/
IDb.read : 3781
Db.fromIDb : 373
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Failed to deserialize the passed arguments to the new isolate.
Exited (255)
```

```
_AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51)
_AssertionError._throwNew (dart:core-patch/errors_patch.dart:40)
_LinkedHashMapMixin._regenerateIndex (dart:collection-patch/compact_hash.dart:449)
_rehashObjects (dart:collection-patch/compact_hash.dart:21)
```

 VS Code User Settings JSON:
```
// Disable new SDK DAPs - https://github.com/Dart-Code/Dart-Code/issues/4368
"dart.previewSdkDaps": false,
```

The application is here
https://github.com/Cat-sushi/fmatch

Don't mind the AGPLv3 license.
You can use the code freely for reproduction of this issue.
This message is the second license.

`wserver.dart` is the entry point.
The number of isolate of `Client.serverMain` is depend on the number of cpu cores.
If you want fixed number of isolates, run `dart bin/wserver.dart -s4`, for example.

**Comment by mkustermann** [comment]
Small reproduction is
```dart
import 'dart:isolate';

main() async {
  final map = <dynamic>{};
  for (int i = 0; i < 1024 * 1024; ++i) {
    map.add(i);
  }
  map.add(Object()); // will cause requirement for re-hash

  final rp = ReceivePort();
  final sp = rp.sendPort;
  sp.send(map);
  print(await rp.first);
}
```
launched via
```
% dart --enable-asserts test.dart 
```

This happens when the fast object copy allocated the `UntaggedMap`, invoked `CopyMap` that initialized it, which adds it to the array of objects to rehash. It then forwards the `data_` array (backing store of map) which is too large and bails to slow version of object copy.

The slow version will re-do the `CopyMap` and re-add it to the set of objects to hash.

That means we have it twice in the array, which causes us to hit the assertion in `--enable-asserts` mode.
