### ISSUE TITLE
API references of packages have emblems of (Null safety) instead of (Dart 3 ready)

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#51255]
Packages in pub.dev have emblems of (Dart 3 ready), but API references of them have emblems of (Null safety), yet.

**Comment by devoncarew** [comment]
Thanks for the feedback! To help us better understand the issue, can you provide links for both?

**Comment by Cat-sushi** [comment]
[simple_mutex | Dart Package](https://pub.dev/packages/simple_mutex "simple_mutex | Dart Package") (Dart 3 ready)
[simple_mutex library - Dart API](https://pub.dev/documentation/simple_mutex/latest/simple_mutex/simple_mutex-library.html "simple_mutex library - Dart API") (Null safety)
[Mutex class - simple_mutex library - Dart API](https://pub.dev/documentation/simple_mutex/latest/simple_mutex/Mutex-class.html "Mutex class - simple_mutex library - Dart API") (Null safety)

**Comment by devoncarew** [comment]
@parlough - would this be addressed by https://github.com/dart-lang/dartdoc/pull/3295? If so, I imagine that we haven't yet rolled that version of dartdoc through to pub.dev yet.

**Comment by parlough** [comment]
Yep, that change removes the null safety badge mentioned here and isn't rolled into pub yet. 

It doesn't introduce anything like "Dart 3 ready", but I feel that's okay. I'm not sure I see a value in a "Dart 3 ready" badge for generated docs since being "Dart 3 ready" doesn't affect how you would use a package's libraries, unlike null safety. If others see value in it, that likely should be handled by pub since it completes the necessary Dart 3 alpha analysis.

**Comment by devoncarew** [comment]
Gotcha, thanks for the update.

@Cat-sushi, I'll close this as it looks like the remaining differences - after the next dartdoc roll - are expected.
