### ISSUE TITLE
Add `List<E>.generateReversed`, as some encode/decode ops are efficient in reverse

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#51262]
hello,

Dart currently has [`List<E>.generate`](https://api.dart.dev/dev/3.0.0-208.0.dev/dart-core/List/List.generate.html), which iterates from 0 to `length`,

We also have a `List<E>.filled`, which takes 827 micro-seconds, to create an instance, for 100_000 as `length`, definitely not bad, but inefficient, as the `filled` first fill from 0 to `length`, then i refill from `length` to 0, just use less,

We needed this, because we have an encoder, and a decoder, which operates much faster, in reverse, and slightly inefficient, otherwise,

thanks

**Comment by gintominto5329** [comment]
Please have a look at this code:

#### `_List.generateReversed`(NEW) in dart's style:
```dart
/// for `sdk/lib/_internal/vm/lib/array.dart`
@pragma("vm:prefer-inline")
factory _List.generateReversed(int length, E generator(int index)) {
  final result = _List<E>(length);
  for (int i = (result.length - 1); i >= 0; --i) {
    result[i] = generator(i);
  }
  return result;
}
```

#### `_List.generate`: existing sdk code, for example :
```dart
  @pragma("vm:prefer-inline")
  factory _List.generate(int length, E generator(int index)) {
    final result = _List<E>(length);
    for (int i = 0; i < result.length; ++i) {
      result[i] = generator(i);
    }
    return result;
  }
```

#### `_List.generateReversed`(NEW) in my style (C-like):
```dart
/// for `sdk/lib/_internal/vm/lib/array.dart`
@pragma("vm:prefer-inline")
factory _List.generateReversed(
  final int length,
  final E Function(int) generator,
) {
  final _List<E> result = _List<E>(length);

  int i = (result.length - 1);
  while (i > -1) {
    result[i] = generator(i--);
  }

  return result;
}
```

**Comment by lrhn** [comment]
The obvious workaround is to generate in inverse order and reverse the list afterwards. Not efficient either, but it's all going to be O(N).

I have no problem with the idea, but I'm worried about whether it's actually a common enough issue that it's something we want to bake into the platform libraries. 
After all, it's calling `generator` with all the same values, and generator *looks* like it's a pure function from index to value, so the ordering shouldn't really matter.

If it put the result of `generator(0)` at the end and `generater(length - 1)` at the front, it would feel much more like an actually reversed operation. (And if your generator ignores the index and runs from an external state, it shouldn't care).


(It's also clear that if performance is the reason for the request, no other solution will actually solve it, because any other solution will be at most as efficient as generating the values and copying them at least once, which is precisely what `List.generated(length, generator)..reverse()` will do.)

We could also add a `{bool reversed = false}` to the constructor, rather than add a second constructor.

**Comment by gintominto5329** [comment]
> List.generated(length, generator)..reverse()

Thanks

> an optimized platform library implementation

Any plans for this, actually just optimizing `List`, would be enough for us,

Or, you could let us optimize it ourselves, by public-izing the required API, 

thanks
