### ISSUE TITLE
Failures on Test legacy flow analysis behaviour of `case null`.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51276]
There are new test failures on [Test legacy flow analysis behaviour of `case null`.](https://dart-review.googlesource.com/c/sdk/+/281282).

The tests
```
language/switch/case_null_legacy_flow_analysis_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-hostasserts-linux-x64-d8
```

CC @askeksa-google

**Comment by osa1** [comment]
Smaller repro:

```dart
void test2(int? x) {
  switch (x) {
    case null:
      print(1);
      break;
    default:
      print(2);
      break;
  }
}

main() {
  test2(1);
}
```

The problem is this check in `switch` compiler: https://github.com/dart-lang/sdk/blob/20fb4593e3c487e4c81d68ed38e0a2acc9437bc2/pkg/dart2wasm/lib/code_generator.dart#L1274-L1315

When the switch has one `null` and one `default` we don't see any literals in the branches, so the first check which is `check<BoolLiteral, BoolConstant>()` passes and we consider it as a bool switch.

I don't understand why we look at the branches and not to the static type of the scrutinee. @askeksa-google do you know?

**Comment by osa1** [comment]
> I don't understand why we look at the branches and not to the static type of the scrutinee. @askeksa-google do you know?

I'm trying this change in https://dart-review.googlesource.com/c/sdk/+/282020, which fixes this bug.

**Comment by askeksa-google** [comment]
> I don't understand why we look at the branches and not to the static type of the scrutinee. @askeksa-google do you know?

Because that's what the language spec says.

**Comment by osa1** [comment]
> Because that's what the language spec says

Where? Section 18.9 ("Switch") says left-hand sides of `case`s need to be all instances of the same class `C`, `int`, or `String` (interestingly it doesn't say `bool`). I don't see any rules in this section that requires looking at left-hand sides of `case`s instead of the scrutinee type.

**Comment by osa1** [comment]
> Where? Section 18.9 ("Switch") says left-hand sides of cases need to be all instances of the same class C, int, or String (interestingly it doesn't say bool). I don't see any rules in this section that requires looking at left-hand sides of cases instead of the scrutinee type.

The problem is when the static type of the scrutinee is `dynamic`. In that case we need to look at `case`s because static type doesn't tell us what kind of comparison to use.

In other cases we could use the static type of the scrutinee, but always looking at `case`s should also work. So instead of having special case for `dynamic` scrutinees we always always look at `case`s.
