### ISSUE TITLE
[cfe] Add a flag to targets to preserve typedefs

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/sdk#51274]
In order to better support Dart2Wasm, the Dart Web team is developing a new model of JS interop based on explicit types for JS objects. This new model will require users to explicitly coerce between Dart types and JS types on the Dart2Wasm backend. However, because the existing model for JS interop is based on conflating Dart types and JS types, and in order to give our users a straightforward path to migrate to JS types, we are preserving the existing conflationary semantics of JS interop on JS backends for JS types using typedefs.

This approach 'works' in the sense that we can share JS interop APIs, i.e. DOM bindings, between all web backends, and users who don't care about Dart2Wasm can ignore the JS types. However, it also introduces semantic differences between the APIs, and when users care about writing code that will work on all web backends, they have to be careful to always test their code on the strictest backend. Furthermore, some users on JS backends may welcome stricter type checking of JS objects, especially for function types.

As a step in the transition to JS types, the Dart Web team would like to add a `strict-mode` to JS backends. In `strict-mode`, JS types will be decoupled from Dart types. However, because JS types on JS backends are typedefs, and typedefs are currently erased by the CFE, our only option is to build the JS types library separately from the rest of the SDK, and to choose the appropriate version of the JS types library based on a compile time flag. While this will work, it will also incur a significant maintenance cost.

Would it be possible to add a flag to CFE targets to support preserving typedefs? With such a flag, we could implement a `strict-mode` flag by writing a simple visitor to 'check' for implicit coercions between Dart types and JS types, and to fail compilation with a helpful error should such coercions exist in a user's code.

Because the set of typedefs could be quite large, it might be helpful to restrict the set of typedefs the CFE should preserve to a set specified by the target, instead of having a global flag.

@johnniwinther thoughts? Please see https://github.com/dart-lang/sdk/issues/51208 for more details.

**Comment by johnniwinther** [comment]
@dcharkes

**Comment by eernstg** [comment]
@joshualitt, I don't know enough about the constraints you're working with to know whether this would work, but did you consider using inline classes rather than type aliases? (Inline classes will be added to Dart, and they are currently being implemented.)

For any given expression `e` of type `T`, the run-time type of the value of `e` will be some subtype `S` of `T`. With the current types in Dart, that object could only ever have a type which is a supertype of `S`, which is typically also a subtype or supertype of `T`.

An inline class makes it possible to give an object a type which is completely unrelated to its "normal type" (like `T` in the previous paragraph), and this means that there is no need to take extra steps to preserve an inline type during static analysis.

**Comment by lrhn** [comment]
It sounds like type aliases are being used to introduce types. That's inconsistent with how Dart actually works, where a typedef does not introduce a new type, only a syntax for referring to an existing type. "Retaining typedefs" isn't well-defined, because a type alias cannot occur where a _type_ is needed, because they are not type entities by themselves.

@eernstg proposed inline classes, which is a way to introduce new Dart types.
An inline class with an `external` constructor and `Object? _jsValue;` representation value field would be one way to introduce a new Dart type with very little actual meaning.

Another option could be to introduce *external types*, say `external class Foo;`.
Maybe allow member signatures, `external class Foo { int banana(); }`, but those will all be abstract, or if not, work like extension or inline-class members.
We can evenal allow the type to define super-type relations to other external types, like `external class Foo implements OtherExternalFoo`. 
It would still mean that the compiler needs to introduce an actual representation for each such type, which satisfies what the declaration promises, and which is at least assignable to `Object?`.

**Comment by joshualitt** [comment]
@eernstg we did consider inline classes. However, IIUC they may not work for our use case:

For a concrete use case, in non-strict mode developers can write code like
```
JSNumber foo = 4.0;
double bar = foo;
```

While in strict-mode the above code would fail to compile. Instead, we'd require users to explicitly coerce these types:
```
JSNumber foo = 4.0.toJS;
double bar = foo.toDart;
```

Please correct me if I'm wrong, but I don't think we'd have this kind of flexibility with inline classes? We could use inline classes if we're willing to have two different dill files, but ideally we would be able to find an approach that would work with a single dill file.

@lrhn I think the challenge here is that I think in non-strict mode we'd need a cycle in the type system to get the behavior we want(i.e. implicit conversions between Dart types and JS types), whereas we'd want the types to be only indirectly related in strict mode(i.e. implemented by the same concrete type, but with no direct subtype / supertype relationship). We basically want to change the way these types are related at compile time, which seems challenging if the CFE has to be aware of the relationship between Dart types / JS types a priori.

It is unfortunate that we might need a language change to get the behavior we want here. Why is introducing an `AliasedType` to the CFE problematic? It seems like it wouldn't be observable, assuming for subtyping checks it strictly defers to the aliased type. Is the issue here that this would introduce a discrepancy between the behavior of the analyzer and the CFE? Or is simply introducing `AliasedType` into the CFE's subtyping algorithm the problem?

Another possible approach might be to add user defined implicit conversions functions to the language.  Something like:
```
class JSNumber {
  external operator double();
}
...
class double {
  external operator JSNumber();
}
```

With user defined implicit conversion functions, we could either:
1. Simply allow implicit conversions between Dart types / JS types on all backends. However, because conversions on some backends may be expensive, we might want to disallow this.
2. Allow implicit conversions between Dart types / JS types on JS backends in non-strict mode, but disallow them at compile time in strict-mode.

I'm sure there could be other approaches, and in the worst case we could use two different dill files, but as mentioned in the feature request, this will incur a significant maintenance cost.

**Comment by eernstg** [comment]
@joshualitt, there is nothing in inline classes that allows us to introduce a strict and a non-strict mode of analysis/compilation and then get different static analysis in each mode. So that would be an extra feature, somehow.

It sounds like this feature would be web-specific (say, it could be an option on `dart compile js` and on DDC). Let's assume that the analyzer would support this kind of analysis as well.

Another possibility would be that a strict-mode library would import one version of 'dartjsengine' and non-strict mode would import another version.

You mention implicit conversions. They have been considered in connection with several different kinds of mechanism, including inline classes, so that would certainly be an approach which could be explored. It's not part of the inline class proposal which is currently being implemented.

```dart
JsNumber foo = 4.0;
double bar = foo;
```

Presumably, these declarations would rely on implicit conversion (because a Dart `double` is simply not the same kind of entity as a `JsNumber`, so `double bar = foo;` could not possibly be a plain assignment).

The availability of implicit conversion operators would allow the compiler/analyzer to transform the above code to something which could be identical to the example below.

> While in strict-mode the above code would fail to compile. Instead, we'd require users to explicitly coerce these types:

So the implicit conversion operators would not be declared in the library which is imported by the strict mode library, or the special 'strict-mode' option on the analyzer/compiler would somehow disable it. That should be doable.

```dart
JsNumber foo = 4.0.toJS;
double bar = foo.toDart;
```

The `toJS` and `toDart` getters could be declared as extension methods on `double` respectively on `JsNumber` (and `toDart` might just call `valueOf`).

However, if you actually need to perform conversions at run time then I don't see how the description so far can be taken (or generalized) to handle higher order cases.

For instance, what will you do with this example?:

```dart
List<JsNumber> foos = [4.0, 5,0];
List<double> bars = foos;
```

> I don't think we'd have this kind of flexibility with inline classes?

So far there's no obvious reason why we would want more than implicit conversions, and some kind of support for turning them on and off (or: just import them or don't import them).

The use case for inline classes would be a situation where a `JsObject` is obtained in such a way that it is statically known that it implements a particular interface (but as a `JsObject`, not in the usual way which is expected from a Dart object). That object would support invocations of `js_util.getProperty`, `js_util.callMethod`, etc., but only with specific actual arguments (because we know that the object has certain properties and methods). The inline class would make it easy and safe to use that interface.

However, if your use case as that there will be a bunch of objects of types like `JsArguments`, `JsArray`, `JsBoolean`, `JsBuiltinObject`, `JsEmptyItem`, `JsFunction`, `JsNull`, `JsNumber`, `JsPrototype`, and `JsString`, and they are all used according to their Dart-aware interfaces (like [this one](https://pub.dev/documentation/dartjsengine/latest/dartjsengine/JsNumber-class.html)), then it's perfectly possible that inline classes aren't a good fit. Those objects already have a pretty nice interface at the Dart level.

**Comment by joshualitt** [comment]
@eernstg 

Thanks for explaining! I do think implicit conversions, especially opt-in implicit conversions, could be a nice addition to inline classes. I'm sure there are cases where users really do want to keep the inline class statically distinct from the on-type, and cases where this behavior is not useful. This behavior, assuming these implicit conversions persist in the AST, would be enough to ensure we can implement `strict-mode` with a kernel visitor.

Sorry for the confusion, but one issue bears clarification:
> However, if you actually need to perform conversions at run time then I don't see how the description so far can be taken (or generalized) to handle higher order cases.

The example you shared is not something we intend to support in `strict-mode`. 

So while this will work in `non-strict-mode`:
```
List<JSNumber> foos = [4.0, 5,0];
List<double> bars = foos;
```
A user would have to write this in `strict-mode`:
```
List<JSNumber> foos = [4.0.toJS, 5.0.toJS];
List<double> bars = foos.map((d) => toDart);
```
Or perhaps the tearoff of `toDart` should also work, but I think you get the point.

That said, we actually do want to talk with the language team about extending the rules for contextually typing literals. Something like:
```
JSNumber bar = 4.0;
```
Seems reasonable to support in `strict-mode`, even if we disallow implicit conversion from `double` to `JSNumber`.

**Comment by joshualitt** [comment]
@sigmundch @srujzs

**Comment by lrhn** [comment]
My main concern is that this is introducing new *types* (distinct entities in the Dart type system).
Those are the entities that subtyping relates. We can assign other properties to types (like an interface), but fundamentally they have to *exist* first.

Introducing new types is not trivial. Currently the declarations `class`, `mixin` and `enum` are the only ones which introduce new user types (all what we call "interface types", and if generic, it's a type per instantiation). 
The platform provides ways to define function, nullable and future-or types, and it provides the base types `void`, `dynamic`, and `Never`. (`Null` and `Object` are classes, with some special casing.)
Records and `inline class`es will also introduce new types, which are non-interface types.
 
Notably, a `typedef` declaration does *not* introduce a new type. It introduces a new name which can be used to refer to existing types, but the type alias name itself does not introduce any new entities into the type system.

If you want to introduce `JSNumber`, *what kind of type is it*?

If it's a class type, then we know what it means, but that prevents mutual subtyping with `double`. (Everything prevents mutual subtyping with double, it's a `final` type!)

Making `JSNumber` a type alias for `double` gives you assignability in both directions, because there are no directions, it's just one type. That also means that the language cannot distinguish `JSNumber` from `double` for anything, because they are just two names for the same thing.
It also means that if you write `JSNumber x;` it will take real effort to make the compiler remember that the `double` type came from a `JSNumber` identifier. There is only one entity in the type system, and you somehow need two values to represent it, and ensure they are not swapped at any point.
It's the same reason it makes no sense to put metadata annotations on a function type alias's parameters. It's a structural type, there is only one function type entity in the type system for it, it makes no sense to ask whether it's the version of that one type that came from that particular type alias declaration.

Making `JSNumber` an inline class introduces a new type. We may or may not be able to define subtyping or assignability in one or both directions. It will have to have a representation type (if that's the corresponding Dart type, great, or if it's some anonymous `JSObject` class, then that's probably also fine).
It's still also a Dart type, not a native type.

What it sounds like you need is more towards what `dart:ffi` has done.

You declare the types, I don't care how, probably just `class` declarations, then you special case those declarations in the compiler and treat them like something different from how they are declared. Like how we do with `FutureOr`, it's declared as `class FutureOr<T> { ... }`, but it isn't a class type. It's not even close.

(Or maybe have no physical declarations at all, as long as your compiler treats a specific library as exporting the necessary names, like we do with `dynamic` and `Never` from `dart:core`).

Special-case it all the way down. Do it in the subtyping/assignability relation. Do it in member-invocability checks (this method can be called with a `String` or `Uri`, and nothing else!). Disallow method tear-off if it gets in the way. 
Basically, don't bother pretending that it's real classes. It's an entirely new kind of type that the Dart language has no knowledge about, but as long as you don't break soundness (more than usual for web compilers), everybody can squint and pretend that it's valid dart. If `JSNumber` needs to be assignable to `double`, then it is, with an implicit cast just like `dynamic`.
Maybe add `implements` clauses where it makes sense, or member signatures where they can be typed, but have no compunctions about just hard-wiring members into the compiler _and_ the class documentation, if that's what it takes to make it work correctly.

(That's the highly invasive approach, trying to stay within some semblance of Dart behavior probably makes things easier, so pick your battles wisely.)

In other words, don't use type aliases when you need a real type. Type aliases are not real types.

**Comment by joshualitt** [comment]
@lrhn I'm totally okay not using typedefs, and I'm 100% on board with us managing the type checking rules.

The problem is I need to get the Dart code past the CFE first. I'm all for any approach, no matter how much hacking it involves. The three criteria here for an 'optimal' solution:
1. In `non-strict-mode`, Dart types can implicitly convert between JS types and back.
2. In `strict-mode`, Dart types require explicit conversion to JS types and back.
3. We only need a single SDK dill.

1 is trivial with typedefs. 2 is trivial with actual classes. If I'm willing to have multiple dills, I can have both 1 and 2. Is there a way to have 1, 2, and 3?

Unless I'm misunderstanding something, it sounds like 'no, not without changing the language'. However, I think the ask here isn't totally unreasonable. I want some way to embed a backend dependent foreign type system in Dart. I'm willing to handle the type checking aspect, but I need help from the language / CFE team to make this possible.

If typedefs aren't the way forward, then what might be some alternative approaches? Some possible approaches I can think of:
- Opt-in implicit conversions on inline classes might solve some of our issues.
- A backend hook into the subtyping algorithm would give us complete flexibility.

I'm sure there are other approaches. Thoughts?

**Comment by lrhn** [comment]
For getting 1, 2 _and_ 3, you definitely need CFE cooperation. You can't have different behavior from the same Dart code depending on a switch unless the CFE understands the switch and what it means. 
Which cooperation you need depends on the solution you choose, and what they can do. 

Some kind of hook for handling "custom types" that aren't really Dart types, allowing you to define custom subtyping and assignability/coercion rules might work, but I can't say how invasive that would be for the CFE implementation.

**Comment by johnniwinther** [comment]
cc @chloestefantsova

**Comment by chloestefantsova** [comment]
Speaking of the cooperation with the CFE, @joshualitt, do you have a timeline for the required changes, so we can prioritize our work accordingly?

**Comment by joshualitt** [comment]
This turned out to be unnecessary, closing.
