### ISSUE TITLE
[Sealed class] Kythe implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#51293]

**Comment by leafpetersen** [comment]
Anything to do here?  @srawlins ?

**Comment by srawlins** [comment]
There probably is. I believe @davidmorgan 's team has handled this in the past.

**Comment by davidmorgan** [comment]
I think @yanok plans to do this one.

**Comment by yanok** [comment]
Sure, it's on my list.

**Comment by yanok** [comment]
It turned out there was nothing to do for the "sealed class" feature specifically.

Kythe supports `sum` node kind, but as sealed classes in Dart can contain fields, it seems to be correct to keep using `record` node kind for them.
I don't see a way to express the fact that "these are the variants of this sum type" in Kythe. But that won't be very useful for Dart anyway, since in Dart we do variants via subclassing and subclasses are already supported in Kythe.

So I think we can just close this.
