### ISSUE TITLE
patterns, incorrect type analysis of a function in a when clause

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51354]
The analyzer claims:
error: Conditions must have a static type of 'bool'. (non_bool_condition at [experiments] lib/patterns.dart:330)

The function `((a) => b)` is highlighted. The function type looks like `bool` to me.
```dart
void functionInWhen(Object obj, bool b, int c) {
  var x = switch (obj) {
    _ when ((a) => b) => c
  };
  print(x);
}
```
cc @scheglov

**Comment by scheglov** [comment]
No, I think the error is correct.
The type of `((a) => b)` is `bool Function(Object?)`, not `bool`.

You need to invoke it with some argument, e.g.
```dart
void functionInWhen(Object obj, bool b, int c) {
  var x = switch (obj) {
    _ when ((a) => b)(null) => c
  };
  print(x);
}
```

**Comment by stevemessick** [comment]
@munificent The switch in this example comes from the patterns spec.

**Comment by munificent** [comment]
Yeah, that's a weird corner of the proposal and a weird example. In the proposal it's:

```dart
var x = switch (obj) {
  _ when ((a) => b) => c
};
```

And the section where that's shown is about how we deal with the syntactic ambiguity of a `=>` inside a guard expression, since that's also used to separate the guard from the body. We have to resolve that ambiguity so we can parse it, even before we type check it. So this example will end up having a type error, but the point was just to show how it's resolved syntactically.

It's hard to come up with an example of this syntactic ambiguity which *doesn't* have a type error, but I suspect you could with some combination of weird overloaded operators that accept functions as arguments. Either way, it's a dark corner of the proposal that hopefully no regular users will stumble into.
