### ISSUE TITLE
Async void ffi callbacks API

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#51350]
We're adding a variant of `Pointer.fromFunction` that can be used for async void functions (by dispatching a message to the target isolate). We might also add more variants in future.

We could add an enum, as an optional parameter to `Pointer.fromFunction` that controls the variant.

```dart
enum FunctionPointerKind {
  sync,
  asyncVoid,
}

external static Pointer<NativeFunction<T>> fromFunction<T extends Function>(
    @DartRepresentationOf('T') Function f,
    [Object? exceptionalReturn,
    FunctionPointerKind kind = FunctionPointerKind.sync]);
```

This is nice because we can document all the different kinds of callback on this enum. The downside is that asyncVoid functions will always pass null as the `exceptionalReturn`, so until we add more variants, if you want to pass a non-default value to the third param you have to pass null to the second.

Another option is to add a new method for each variant:

```dart
external static Pointer<NativeFunction<T>> fromFunctionAsyncVoid<T extends Function>(
    @DartRepresentationOf('T') Function f);
```

A final option is to do a breaking change to switch `Pointer.fromFunction` to use _named_ optional args.

```dart
enum FunctionPointerKind {
  sync,
  asyncVoid,
}

external static Pointer<NativeFunction<T>> fromFunction<T extends Function>(
    @DartRepresentationOf('T') Function f,
    {Object? exceptionalReturn,
    FunctionPointerKind kind = FunctionPointerKind.sync});
```

@dcharkes @lrhn any opinions?

**Comment by dcharkes** [comment]
I really prefer the last option, but we can't just break the API I'm afraid.

The best we can do is to deprecate fromFunction and introduce a new one:

```dart
class CallbackSemantics {
  CallbackSemantics._();

  /// documentation
  static const CallbackSemantics sync = ...;

  /// documentation
  static const CallbackSemantics asyncVoid = ...;
}

external static Pointer<NativeFunction<T>> fromFunctionV2<T extends Function>(
    @DartRepresentationOf('T') Function f,
    {Object? exceptionalReturn,
    CallbackSemantics kind = CallbackSemantics.sync});
```

`fromFunctionV2` is a horrible name. Suggestions are welcome.

Please note we can't use an `enum`, as users might write a switch on it so adding a value later would break their code. Instead we should use a class with a private constructor and predefined const objects.

**Comment by blaugold** [comment]
Maybe from `fromCallback` or `fromCallbackFunction`?

**Comment by lrhn** [comment]
I'll admit I don't understand what problem we are trying to solve.

This will be a pointer to a native function.
How is a native function "async" in the Dart sense (which is defined in terms of a Dart isolate's event loop)?

Being "async" should presumably mean that calling the native function will not block the current isolate, and it will provide a result "later".

Or is it not the function which is async, it's just run that way?

Does *calling* the native function through this pointer return a `Future`, run the native function in a separate thread, report the result to a port, and complete the future when the result is ready?
(Seems reasonable, that explains what "target isolate" is: The current one where you called the native function from.)

If so, it sounds to me like it's not the native function which is async, but the calling convention used to call it.
It's a different kind of function pointer than the synchronous function pointer.

Using enums (or any mode flags on methods) is ugly, verbose and forces multiple operations to have to share the same API. Here it doesn't look like the APIs differ, but are we sure they won't diverge in the future (say, adding an optional timeout to the async variant).

Consider having a separate function for async functions:
```dart
Pointer<NativeFunction<T>> fromAsyncFunction<T extends Function>(
    @DartRepresentationOf('T') Function f,
    {Object? exceptionalReturn});
```
Moving to a named parameter is fine, it allows you to add extra parameters in the future (https://github.com/dart-lang/language/issues/1076 is still not on the horizon, and it's 10 year running now).

Making it a separate function allows you to (more easily) require that `f` returns a `Future` type corresponding to the native return type.

(Or, if I'm completely missing what's going on, which is clearly possible since I have no idea what `f` is used for, then please provide a little more context :wink: )

**Comment by dcharkes** [comment]
> Using enums (or any mode flags on methods) is ugly, verbose and forces multiple operations to have to share the same API. Here it doesn't look like the APIs differ, but are we sure they won't diverge in the future (say, adding an optional timeout to the async variant).

That's a good question, will the APIs ever diverge? If they don't diverge, having two identical parameter-lists is suboptimal. If they do diverge, only being able to throw `ArgumentError`s at runtime is suboptimal. (This is why I keep tagging Lasse on these questions 😄 ! Thanks @lrhn!)

I can't come up with an idea why they would diverge just yet.

> Mode flags on functions that fundamentally change what the function does, is a design pitfall.

Fundamentally it will always turn a Dart function into an address that a C function can call.
The thing that changes here is the threading logic: either the caller must be entered into the isolate already, or not.
I am not sure that qualifies as a different mode.

Thoughts @liamappelbe @mkustermann @mraleph ?

> How is a native function "async" in the Dart sense (which is defined in terms of a Dart isolate's event loop)?

It is async in the sense that an arbitrary thread that doesn't respect (or know of) the Dart isolate's event loop can call it at an arbitrary point in time. Maybe "async" isn't the right term to use.

A try for better naming: `runImmediate` and `scheduleEvent`?

```dart
class CallbackSemantics {
  CallbackSemantics._();

  /// The calling thread must have already entered the correct isolate.
  ///
  /// By entering the Dart isolate in which this callback lives, the caller
  /// guarantees that no Dart code is currently executing.
  ///
  /// FFI callbacks with [runImmediately] semantics run synchronously and can return a value.
  static const CallbackSemantics runImmediately = ...;

  /// An FFI callback with [scheduleEvent] semantics can be invoked from any thread.
  ///
  /// FFI callbacks with [scheduleEvent] semantics are scheduled on the event loop.
  ///
  /// FFI callbacks with [scheduleEvent] semantics do _not_ deep copy their native arguments.
  /// The caller must only pass arguments by value, or pass ownership of memory referenced by [Pointer]s to the callee.
  ///
  /// FFI callbacks with [scheduleEvent] can only return `void` or `Future`s (which are exposed as `Dart_Handle`s).
  /// Callers with functions returning a `Future` in a `Dart_Handle` must have a handle scope.
  static const CallbackSemantics scheduleEvent = ...;

  /// Blocks the thread until the Dart code in the target isolate has yielded to the event loop.
  ///
  /// **Warning: using this can create deadlocks.**
  static const CallbackSemantics waitToEnter = ...;
}
```

> `Future<R>`

@liamappelbe should we consider supporting functions that return a `Dart_(Persistent)Handle` with async callbacks? Those would be "async object" instead of "async void". For a `Dart_Handle`, the caller would need a handle scope.

**Comment by liamappelbe** [comment]
> should we consider supporting functions that return a Dart_(Persistent)Handle with async callbacks?

That would be cool to have, but we should wait for a use case.

Lasse has convinced me that we should just add a separate function for this. Let's go with `Pointer.fromAsyncFunction` rather than AsyncVoid, so we can add support for returning Futures later. (I was saving that name for the wait-to-enter version, but on second thought that's probably a misnomer).

**Comment by dcharkes** [comment]
`Pointer.fromAsyncFunction` this is a misnomer if the Dart function we're making a native-function-pointer from is not async. It's the FFI trampoline that's async, not the Dart function. Or maybe one could say the native-function-pointer supports async calls. Maybe `Pointer.asyncFromFunction` then?

The `CallbackSemantics` argument would be easier with naming. (But we can restart that discussion for https://github.com/dart-lang/sdk/issues/51383 later.)

**Comment by liamappelbe** [comment]
Settled on `NativeCallable.listener`.
