### ISSUE TITLE
patterns, type variable analysis is too strict

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51355]
This example is in the patterns spec. The analyzer claims:
error: The matched value of type 'T Function<T>(T)' isn't assignable to the required type 'int Function(int)'. (pattern_type_mismatch_in_irrefutable_context at [experiments] lib/patterns.dart:355)
```dart
void f18() {
  T id<T>(T t) => t;
  (T Function<T>(T), dynamic) record = (id, 'str');
  var (int Function(int) f, String s) = record;
}
```
Adding `<int>` makes the problem go away. `int Function<int>(int) f`
cc @scheglov

**Comment by scheglov** [comment]
Adding `<int>` makes it work only because `int` is a type parameter now, not a type from `dart:core`.

This works for function references, where we infer `T` to be `int`, e.g.
```dart
  solo_test_X() async {
    await resolveTestCode(r'''
void f(int Function(int) a, T Function<T>(T) b) {
  a = b;
}
''');
    final node = findNode.assignment('a =');
    assertResolvedNodeText(node, r'''
AssignmentExpression
  leftHandSide: SimpleIdentifier
    token: a
    staticElement: self::@function::f::@parameter::a
    staticType: null
  operator: =
  rightHandSide: FunctionReference
    function: SimpleIdentifier
      token: b
      staticElement: self::@function::f::@parameter::b
      staticType: T Function<T>(T)
    parameter: <null>
    staticType: int Function(int)
    typeArgumentTypes
      int
  readElement: <null>
  readType: null
  writeElement: self::@function::f::@parameter::a
  writeType: int Function(int)
  staticElement: <null>
  staticType: int Function(int)
''');
  }
```

However it does not look that we do similar inference for record types.

**Comment by scheglov** [comment]
This was discussed with the language team, and they decided that this WAI.
We don't de-compose and re-compose structures and types to perform function type instantiations.

**Comment by eernstg** [comment]
We might want to consider this issue one more time, cf. https://github.com/dart-lang/sdk/issues/51403 and https://github.com/dart-lang/sdk/issues/51404: Apparently, the analyzer does not apply generic function instantiation to record getter invocations, and the CFE does not fully handle a cast from `dynamic` in a similar situation. That makes it a record issue rather than a pattern issue (or maybe it's a records &amp; patterns issue ;-).

The original example might just work when those other issues have been addressed (in which case there is no reason to say "we don't support that"):

```dart
void f18() {
  T id<T>(T t) => t;
  (T Function<T>(T), dynamic) record = (id, 'str');
  var (int Function(int) f, String s) = record; // OK, includes a generic function instantiation.
}
```

On the other hand, if we really do not want to support coercions during the initialization of pattern declared local variables then we'd need to make a small adjustment to the feature specification, [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=in%20the%20pattern.-,This%20process%20may%20also%20insert%20implicit%20coercions,-and%20casts%20from).

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/2845.
