### ISSUE TITLE
Pattern resolution broken in top-level declaration

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#51412]
Create a file containing the following:

```dart
var v = [ if (o case var x) ];
var o = 0;
```

There are at least two problems.

The first is that if completion is requested in this file the server will incorrectly report that the file isn't being analyzed. That's a result of an exception being thrown, a catch turning that into a return of `null`, and the `null` return value being interpreted to mean that the file didn't exist, even though it does exist.

The second is the exception that's thrown. The exception is in `sdk/pkg/analyzer/lib/src/dart/resolver/resolution_visitor.dart` at line 1443:

```dart
  void _define(Element element) {
    (_nameScope as LocalScope).add(element);
  }
```

It occurs because `_nameScope` is a `LibraryOrAugmentationScope`, not a `LocalScope`. I don't know whether the code above is valid, but even if it isn't we shouldn't just throw an exception there, we should catch the problem and report it to the user in a meaningful way.

If the second bug is solved first it will mask the first.

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/283122

We don't have yet any special handling for resolution that throws an exception. We could catch this exception, and return a special analysis result, so that `Future<SomeResolvedUnitResult> AnalysisSession.getResolvedUnit()` will return not `ResolvedUnitResult`, but `ExceptionResult`, just like it can currently return `InvalidPathResult`.

Not sure how this would help to the server though, because `AnalysisServer.getResolvedUnit()` filters out everything but `ResolvedUnitResult`, and returns `null` otherwise. So, any code from there will get `null` anyway. Completion probably goes not this code path, but the result would be still the same - at some point we have to check whether we have a valid result, and recover otherwise.

**Comment by bwilkerson** [comment]
Yes, but it's how we report the invalid result. I spent more time that I should have figuring out that my test wasn't broken but that something else happened. Instead of being told that the file wasn't being analyzed it would have been nice if I'd gotten an error that indicated that an exception had been thrown (and what that exception was). Just trying to make it easier to debug this kind of failure in a world in which we're writing more end-to-end tests.

**Comment by scheglov** [comment]
OK, I looked some more, and see that `CompletionGetSuggestions2Handler` invokes `AnalysisServer.resolveForCompletion()` that should return `ResolvedForCompletionResultImpl?`. So, when there is an exception, it returns `null`. I guess we could avoid throwing an exception here, and let the handler to catch it instead, and report as a different `Response.xyz` instead of `Response.fileNotAnalyzed`.

But this is unrelated to the patterns feature.
