### ISSUE TITLE
(-1).hashCode returns 0 on >=2.19

### ISSUE THREAD

**Issue by jonaslundquist** [dart-lang/sdk#51420]
Hi, noticed this when trying to upgrade to Dart SDK 2.19.0 as one of our tests failed due to this. 
`(-1).hashCode` returns 0, and `0.hashCode == (-1).hashCode` returns `true`.
In Dart 2.18.7, `(-1 ).hashCode` returns `-1` and `0.hashCode == (-1).hashCode` returns `false`.

* Dart SDK Version (`dart --version`)
`Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "macos_arm64"`

Expected behavior: `-1` and `0` should not have equal hashCode
Actual outcome: `-1` and `0` have equal hashCode

Reproduction steps:
1. Install Dart SDK 2.19 or higher
2. Create a test.dart file
3. Paste the following: 
```
void main() {
  print((0).hashCode);
  print((-1).hashCode);
  print((-1).hashCode == 0.hashCode);
}
```
4. run `dart test.dart`

It yields

```
0
0
true
```
I'm seeing these issues on MacOSX Ventura 13.2.1 (Apple M1 Max).

Running on DartPad does not yield the same results so I wonder if it could be a MacOS specific issue. 

Let me know if there's any other information I can give that would help!

**Comment by rakudrama** [comment]
There is no guarantee that two different `int` values have different `hashCode` values.

The documentation for `Object.hashCode` makes that point:

https://api.dart.dev/stable/2.19.2/dart-core/Object/hashCode.html

> Objects that are not equal are allowed to have the same hash code. It is even technically allowed that all instances have the same hash code, but if clashes happen too often, it may reduce the efficiency of hash-based data structures like [HashSet](https://api.dart.dev/stable/2.19.2/dart-collection/HashSet-class.html) or [HashMap](https://api.dart.dev/stable/2.19.2/dart-collection/HashMap-class.html).

That documentation also points out that you should not rely on `hashCode` being the same as it was in a previous run:

> They need not be consistent between executions of the same program and there are no distribution guarantees.

`int.hashCode` is working as intended and if your program begins to fail because of changes in `hashCode` then your program is relying on undocumented behavior that is likely to change over time.

I suggest you use `hashCode` _in combination with_ `==`, and not by itself.

**Comment by jonaslundquist** [comment]
Aha I see! Sorry, I didn't see that in the documentation. Thank you!
