### ISSUE TITLE
Quick fixes for record positional record types

### ISSUE THREAD

**Issue by CoderDake** [dart-lang/sdk#51446]
## Tasks

- [x] Implement new diagnostic `RECORD_LITERAL_ONE_POSITIONAL_NO_TRAILING_COMMA` [b0078ad](https://github.com/dart-lang/sdk/commit/b0078ad057700f7202c28a3591ac0a7f036680f9)
- [x] Add a quick fix for `RECORD_LITERAL_ONE_POSITIONAL_NO_TRAILING_COMMA` 43fbb1db5e2da5216a655fd5f423702c42987cd9

---

## Context

While testing records I found that the following gives an error:
```
(int,) intRecord1 = (1);
```
The error is:
> A value of type 'int' can't be assigned to a variable of type '(int)'.
> Try changing the type of the variable, or casting the right-hand type to '(int)'.

After doing some reserearch into the spec I found out that records that look like this must have a trailing comma to show that they are a record. This was not immediately apparent when reading the errors or looking at the quick fixes though.

So the proper way to write this would have been:
```
(int,) intRecord1 = (1,);
```

It would be helpful if the error mentioned that records must end in a comma, or perhaps there was a quick fix that offered to add the trailing comma.

**Comment by CoderDake** [comment]
@bwilkerson I heard you might be interested in this

**Comment by bwilkerson** [comment]
Yes, I'm definitely interested. @keertip @pq might also be interested.

I think the right solution here is to define a new diagnostic for this case (because that's how we can have a better message here). We might even be able to re-use `ParserErrorCode.RECORD_LITERAL_ONE_POSITIONAL_NO_TRAILING_COMMA`, though we don't normally produce parse errors outside the parser, so that might be too odd.

Then we can create a fix that will add the comma. (That fix could be applied to a couple of other diagnostics as well.)

**Comment by bwilkerson** [comment]
I gave this a P2, but I'd really like to see it ship with the feature because I think it will help keep users on the rails.

**Comment by pq** [comment]
I agree.  This feels like a significant foot-gun.  I'l take a look.

**Comment by pq** [comment]
Completed w/ 43fbb1db5e2da5216a655fd5f423702c42987cd9.

Thanks again for the report @CoderDake!
