### ISSUE TITLE
Fix size regression from using package:web

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#51441]
There is a BIG code size increase moving from `dart:html` to `pkg:web` with just `console.log('hello');`

We should fix this.

It's a bit better with `--server-mode` but still ~9x bigger. (And `--server-mode` should not be required.)

**Comment by kevmoo** [comment]
CC @joshualitt @sigmundch

**Comment by srujzs** [comment]
Documenting some thoughts I had:

`package:js` classes in general add at least a constructor and prototype for each type, which then gets added to our runtime inheritance hierarchy through functions like `_inheritMany`. This was needed for the non-`@staticInterop` types, since those types had a runtime type associated with them. For `@staticInterop`, this is unnecessary as the type is completely erased, but dart2js doesn't *know* this. We keep the class around for example, so we'd have to tell dart2js to ignore these types and don't emit them. I'm also not sure under what conditions these types are tree-shaken if at all.

Looking at the output, it seems like we emit a constructor and prototype for each `@staticInterop` type, and considering `package:web` contains many such classes, this adds a bunch of code.

Inline classes won't have this issue (at least, testing locally that isn't the case). They don't have a runtime type besides their representation type, so there's nothing to emit for such a type. It's likely this is fixed once we migrate to inline classes, but it might still be worth addressing the code increase with `@staticInterop` if I find cycles.

**Comment by sigmundch** [comment]
@srujzs just cleaning up a few issues on the database. Should we mark this as complete now?

**Comment by srujzs** [comment]
Yes the work here is done. For posterity:

- We've removed unneeded @staticInterop declarations in dart2js. The remaining code that is pulled in is the RTI + friends and we can't remove those. Any code that uses `is` checks will likely pull those libraries in anyways.
- We removed all the (now unneeded) tear-off code in DDC so there should be little size increase when using package:web.
