### ISSUE TITLE
Type promotion for joined variables in switch

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#51464]
Similar to https://github.com/dart-lang/sdk/issues/51399

This code does not promote `a` in `a; // here` to `num`.

```dart
void f(num? x) {
  switch (x) {
    case final a when a is int:
    case final a when a is num:
      a; // here
  }
}
```

However without joining, when only one case is present, it does promote to `int` or `num`.
Is this a known limitation?

**Comment by lrhn** [comment]
I'd say yes. (But leave Paul to have the final say.)

There are two two environments being join, one with an `a` with the promotion chain `num?` :\> `int`, and one with an `a` with the promotion chain `num?` :\> `num`.

Joining those, the only overlap is the unpromoted `num?`.

**Comment by stereotype441** [comment]
I agree with Lasse--this is "working as intended"; the way flow analysis has always handled joins is to keep just those promotions that are present in both promotion chains, and since `int` and `num` are distinct types, there's no promoted type that is common to both code paths.  This is consistent with how promotions are handled elsewhere in the language, e.g.:

```dart
void f(num? x) {
  if (x is int || x is num) {
    num y = x; // ERROR: `num?` not assignable to `num`
  }
}
```

I put "working as intended" in quotes because although this *is* what we designed, and the language is behaving consistently, I think you could make a good case that we ought to do better here.  When joining control flow paths that promote to `A` and `B`, and `A <: B`, it would be perfectly sound for us to keep the promotion to `B`.  We didn't design it that way, but we could conceivably do that as a future improvement.

I'll open up a language issue to track this possible future improvement.

**Comment by scheglov** [comment]
Thank you, I opened a `co19/` issue instead.

**Comment by stereotype441** [comment]
FYI, here's the language issue I opened up to discuss the possibility of changing this behaviour as a future improvement: https://github.com/dart-lang/language/issues/2856.  Please feel free to comment there if you have opinions about this.
