### ISSUE TITLE
Unintended shadowing in lowering of destructuring a for loop variable

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#51485]
There is some variable shadowing being introduced by the lowering for the `DevCompilerTarget`. It is causing the test failure:

```
co19/LanguageFeatures/Patterns/scope_A02_t03
```

When compiling the following code:

```dart
main() {
  for (var [c] = [1]; c < 2; print(c)) {
    print(c);
    c++;
  }
}
```

The lowering creates two variables with the name `c` and tries to assign one to the other. This doesn't look like it should be valid since we can't make an assignment like that in regular dart code. Was it intended?

```
static method main() → dynamic {
  {
    core::int c;
    {
      final dynamic #0#0 = <core::int>[1];
      if(!(#0#0{core::List<core::int>}.{core::List::length}{core::int} =={core::num::==}{(core::Object) → core::bool} #C1 && (let final dynamic #t1 = c = #0#0{core::List<core::int>}.{core::List::[]}(0){(core::int) → core::int} in true)))
        throw new _in::ReachabilityError::•();
    }
    for (dynamic c = c; c{dynamic}.<(2) as{TypeError,ForDynamic,ForNonNullableByDefault} core::bool; core::print(c)) {
      core::print(c);
      c = c{dynamic}.+(1);
    }
  }
}
```

cc @johnniwinther

**Comment by chloestefantsova** [comment]
Thanks for reporting that issue! The complication with the variables is that it's hard to rename them in that lowering. The other backends seem to accept two variables with the same name. I guess it's possible given that they are two different `VariableDeclaration` objects that have the same value of the name property, which may be treated as decorative.

But in an attempt to avoid duplicated variable names, I created the following PoC CL: https://dart-review.googlesource.com/c/sdk/+/284700. It uses an intermediate variable to pass the value from one `c` to the other `c` and wraps the for loop into a block, so that the `c` declared in the loop is declared in its own scope.

Here's how the compiled fragment of the program looks like with that CL patched in. `#t2` is the intermediate variable.

```
  {
    core::int c;
    {
      final dynamic #0#0 = core::_GrowableList::_literal1<core::int>(1);
      if(!(#0#0{core::List<core::int>}.{core::List::length}{core::int} =={core::num::==}{(core::Object) → core::bool} #C1 && (let final dynamic #t1 = c = #0#0{core::List<core::int>}.{core::List::[]}(0){(core::int) → core::int} in true)))
        throw new _in::ReachabilityError::•();
    }
    final core::int #t2 = c;
    {
      for (dynamic c = #t2; c{dynamic}.<(2) as{TypeError,ForDynamic,ForNonNullableByDefault} core::bool; self::Expect::equals(2, c)) {
        self::Expect::equals(1, c);
        c = c{dynamic}.+(1);
      }
    }
  }
```

However, it seems that the test still fails with my changes patched in.

@nshahan Can you tell why the workaround with the intermediate variables doesn't work?

**Comment by nshahan** [comment]
As long as there isn't an assignment of the form `var c = c;` we should be OK.

I tried patching your change and found that the test does pass for me. If you are using test.py to run the test it does require a rebuild of the `dartdevc_test` target and maybe you missed that step when you were experimenting. 

That said, looking at the compiled output I am concerned about the performance we will see with this feature. We now create three variables `c, #t2, c` when I think only one is needed.

It looks like all the lowered code is wrapped in a block to limit the scope of the first `c`. Could we just use that original definition throughout and not create a temp and the shadowing `c` in the for loop initialization at all? 

Worse than that, we lost the benefits of static typing. The `c` variable introduced in the for loop is typed as dynamic and that is the version of the value that we actually use. If we have to use the temporaries, would it be possible to push more static types into the lowering so that we don't end up with so many dynamic calls and casts?

With the dynamic value the `operator <()` call in the condition will be a dynamic call which is slow for DDC because it has to verify that the callee has the method of the expected name, and the arguments shape must be validated and the arguments themselves cast as the correct types. Then it can call the method. Since the call is dynamic we don't know what the return value will be so then it gets cast as to a bool to be acceptable in the condition. Then in the body there is another slow dynamic call for the `operator +()`.

**Comment by chloestefantsova** [comment]
Thanks for taking a look!

> As long as there isn't an assignment of the form `var c = c;` we should be OK.
> 
> I tried patching your change and found that the test does pass for me. If you are using test.py to run the test it does require a rebuild of the `dartdevc_test` target and maybe you missed that step when you were experimenting.
> 

Thanks for verifying that! I'll try it once again and attempt to land the CL because it at least fixes the breakage.

> That said, looking at the compiled output I am concerned about the performance we will see with this feature. We now create three variables `c, #t2, c` when I think only one is needed.
> 

At least two of them is needed: the `c` from the pattern and the `c` for the cycle. The reason for that is the cycle variables are treated specially. Basically, every iteration of the loop has its own loop variable, so if you capture it in the closure and then invoke the closure after the loop, the closure will continue using the value from the iteration when it was captured.

For that reason, we can't avoid having a loop variable, declared in the header of the loop. We also can't squeeze the mattern-matching logic into the initializer of the loop variable because the pattern can introduce multiple such variables.

So, having at least two variables here seems unavoidable. The intermediate variable, `#t2`, will go away eventually, when we'll adjust the part of the CFE pipeline that prevents renaming the first of the `c` into something that doesn't conflict with the name of the loop variable.

> It looks like all the lowered code is wrapped in a block to limit the scope of the first `c`. Could we just use that original definition throughout and not create a temp and the shadowing `c` in the for loop initialization at all?
> 

Like I wrote above, we can't avoid the shadowing `c`. But now that I think about it, the block that wraps the loop is unnecessary. A variable scope for the loop variables that spans the entire loop is created anyways, and the loop variables are allowed to shadow the variables from the enclosing scope. The only issue that needed to be fixed is avoid referring to different variables with the same name in the same scope.

> Worse than that, we lost the benefits of static typing. The `c` variable introduced in the for loop is typed as dynamic and that is the version of the value that we actually use. If we have to use the temporaries, would it be possible to push more static types into the lowering so that we don't end up with so many dynamic calls and casts?
> 
> With the dynamic value the `operator <()` call in the condition will be a dynamic call which is slow for DDC because it has to verify that the callee has the method of the expected name, and the arguments shape must be validated and the arguments themselves cast as the correct types. Then it can call the method. Since the call is dynamic we don't know what the return value will be so then it gets cast as to a bool to be acceptable in the condition. Then in the body there is another slow dynamic call for the `operator +()`.

That will be fixed at the CFE side in one of a follow-up CL. The feature is under construction, and fixing some issues introduce some other smaller issues that will eventually be fixed.

**Comment by chloestefantsova** [comment]
I've just landed https://dart-review.googlesource.com/c/sdk/+/284700. I also looked into the static typing issue, and it seems I was able to find a solution that I included in the same CL. Additionally, I removed the unnecessary wrapping of the for-loop into a block. The intermediate variables are still there, and after we resolve some more apparent issues, we can return to eliminating them. @nshahan Can you check that the landed CL solves the issue?

**Comment by nshahan** [comment]
@chloestefantsova 
Test are passing and the static type for the loop variable made a wonderful improvement in the code DDC compiles. Thanks so much for the quick fix!

> At least two of them is needed: the c from the pattern and the c for the cycle. The reason for that is the cycle variables are treated specially. Basically, every iteration of the loop has its own loop variable, so if you capture it in the closure and then invoke the closure after the loop, the closure will continue using the value from the iteration when it was captured.

Yep, there it is. I had a hunch there was a reason I just wasn't thinking of and that makes perfect sense. Thanks!
