### ISSUE TITLE
Positional field names should begin with '$'

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51499]
I can fix this in the Flutter plugin, but it should probably be done in the VM.

<img width="212" alt="Screenshot 2023-02-22 at 3 29 40 PM" src="https://user-images.githubusercontent.com/8518285/220787039-9c0ae58b-bc1f-4dfa-af09-6afc80774886.png">

See also #51451

Edit: I think this change would allow the VM service protocol to be slightly simplified. Currently, `BoundField` has a `name` property that can be either `int` or `String`. After this change, it would only be `String`.

**Comment by derekxu16** [comment]
It says [in the spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#static-semantics) that "Positional fields are not merely syntactic sugar for fields named `$1`, `$2`, etc. The records `('a', 'b')` and `($1: 'a', $2: 'b')` expose the same members, but have different shapes according to the type system."

While it is highly unlikely for someone to use named fields with names like `'$1'` and `'$2'`, they are still permitted to do so by the spec. Therefore, I think the response should be kept the way it is, because the type of a `BoundField`'s `name` property can indicate whether a field is positional or named, for any field that is permitted by the spec.
