### ISSUE TITLE
Analyzer does not allow named fields to override positional fields

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51507]
The analyzer reports an error for:`var t = ($1: 'a', $2: 'b', 5, 7);` 
>error: Record field names can't be a dollar sign followed by an integer when the integer is the index of a positional field. (invalid_field_name at [experiments] lib/records.dart:20)

According to [this comment](https://github.com/dart-lang/sdk/issues/51499#issuecomment-1441924973), it should be allowed. That comment includes a quote from the spec, which, in the spec, is emphasized.

**Comment by stevemessick** [comment]
cc @jacob314 @DanTup @alexander-doroshko
We will have to implement this in all the plugins/extensions. The issue is that `BoundField` has `name`, which can be `int` or `String`. We need to detect the `int` and prepend a `$` after converting to a string. Not a huge effort, but something to be aware of.

**Comment by bwilkerson** [comment]
> The analyzer reports an error for: `var t = ($1: 'a', $2: 'b', 5, 7);`

The record has two positional fields. Even though they're written after the named fields, the indexes of the two fields are still 1 and 2. This looks like a valid diagnostic to me. Am I missing something?

**Comment by DanTup** [comment]
@stevemessick I presume the second comment relates to the debugger views? If so, I believe both the new and old VS Code debug adapters are handling this in the way you described (I updated both, because `BoundField.decl.name` becoming nullable was a breaking change that broke the legacy debug adapter and it needed updates anyway).

New SDK DAP:

https://github.com/dart-lang/sdk/blob/4435e1564973b82bc255e99481254a18dd7d66d9/pkg/dds/lib/src/dap/protocol_converter.dart#L233-L239

Legacy Dart-Code DAP:

https://github.com/Dart-Code/Dart-Code/blob/1b0b37defa68f5ba9a44b7cf3ad4eb33fc6240b4/src/debug/dart_debug_impl.ts#L1343

This doesn't indicate to the user whether `$1` is a positional or named field, but I'm not sure that's an important distinction here, and it'd better to show the field as the user would access it in code.

(FWIW, my reading of the linked comment was just that a records with a field _named_ `$1` are not _the same type_ as the equiv with a positional field, rather than that a single record could have both - not sure if that's correct though)

**Comment by stevemessick** [comment]
Got it. I misinterpreted a line in the records spec.
