### ISSUE TITLE
object pattern with extension getter is having issues with exhaustivity checking

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/sdk#51500]
`Dart SDK version: 3.0.0-266.0.dev (dev) (Wed Feb 22 10:18:50 2023 -0800) on "windows_x64"`

Consider the following program:

```dart
void main() {
  print(equals([], []));
  print(equals([1, 2, 3], []));
  print(equals([], [1, 2, 3]));
  print(equals([1, 2, 3], [1, 2, 3]));
}

bool equals<A>(Iterable<A> a, Iterable<A> b) => switch ((a, b)) {
  (Iterable(isEmpty: true), Iterable(isEmpty: true)) => true,
  (Iterable(isEmpty: false), Iterable(isEmpty: true)) => false,
  (Iterable(isEmpty: true), Iterable(isEmpty: false)) => false,
  (Iterable(first: var l, rest: var ls), Iterable(first: var r, rest: var rs)) => 
      l == r && equals(ls, rs),
};

extension<A> on Iterable<A> {
  Iterable<A> get rest => skip(1);
}
```

This produces the error:

```
Error: The type '(Iterable<A>, Iterable<A>)' is not exhaustively matched by the switch cases.
 - 'Iterable' is from 'dart:core'.
Try adding a default case or cases that match (Iterable<A%>, Iterable<A%>)($1: Iterable<A%>(first: (A% & Object), isEmpty: false, rest: Object), $2: Iterable<A%>(isEmpty: false)).
bool equals<A>(Iterable<A> a, Iterable<A> b) => switch ((a, b)) {
                                                        ^
```

The exhaustivity checking passes if you rewrite the program to not use the extension getter:

```dart
void main() {
  print(equals([], []));
  print(equals([1, 2, 3], []));
  print(equals([], [1, 2, 3]));
  print(equals([1, 2, 3], [1, 2, 3]));
}

bool equals<A>(Iterable<A> a, Iterable<A> b) => switch ((a, b)) {
  (Iterable(isEmpty: true), Iterable(isEmpty: true)) => true,
  (Iterable(isEmpty: false), Iterable(isEmpty: true)) => false,
  (Iterable(isEmpty: true), Iterable(isEmpty: false)) => false,
  (Iterable(first: var l), Iterable(first: var r)) => 
      l == r && equals(a.skip(1), b.skip(1)),
};
```

**Comment by lrhn** [comment]
Looks like we think the return type of `rest` is `Object?` in the exhaustion algorithm, but not in type inference. 
If I change the bindings to `rest: Object? ls`, or `rest: _`, the switch is considered exhaustive. If I change it to `rest: Object ls`, it asks me to cover the value `Null`.
(If I use `rest: dynamic ls`, it doesn't work, and asks me to match `rest: Object`, which is weird.)

I was guessing that type inference keow the return type, otherwise the `rest: var ls` should have been inferred to be `rest: Object? ls`, and then it should have worked anyway.
But apparently it doesn't, and it infers `dynamic`. Proof:
```dart
void main() {
  Iterable<int> a = [1] as dynamic;
  a.rest.log; // Sanity check.

  print(equals([], []));
  print(equals([1, 2, 3], []));
  print(equals([], [1, 2, 3]));
  print(equals([1, 2, 3], [1, 2, 3]));
}

bool equals<A>(Iterable<A> a, Iterable<A> b) => switch ((a, b)) {
  (Iterable<A>(isEmpty: true), Iterable<A>(isEmpty: true)) => true,
  (_, Iterable<A>(isEmpty: true)) => false,
  (Iterable<A>(isEmpty: true), _) => false,
  (Iterable<A>(first: A l, rest: var ls), Iterable<A>(first: A r, rest: var rs)) => 
      ls.log && l == r && equals(a.rest, b.rest),
  _ => throw "Unreachable" // Force exhaustive
};

extension<A> on Iterable<A> {
  Iterable<A> get rest => skip(1);
}

extension <T> on T {
  bool get log {
    print("$this:$runtimeType @ $T");
    return true;
  }
}
```
This code should have shown the static and runtime type of `ls`, but it won't compile because `log` is turned into a dynamic runtime call. That can only happen for the static types `dynamic` and `Never`.

If I change `equals(a.rest, b.rest)` to `equals(ls, rs)` (need to change both arguments), then I get the error that `rs` can't be downcast from `Object?` to `Iterable<dynamic>`. Which means that at *that* point `ls` and `rs` have type `Object?` instead of `dynamic`.

It's heisentyping. Referencing `ls` and `rs` changes its type between `Object?` and `dynamic`, neither of which are correct.

**Comment by mmcdon20** [comment]
@lrhn there is already a known issue with the type inference #51437, but I would have thought this would be exhaustive regardless of what type `ls` or `rs` are.

**Comment by mmcdon20** [comment]
I tried this again with the following version.
`Dart SDK version: 3.0.0-277.0.dev (dev) (Mon Feb 27 04:52:05 2023 -0800) on "windows_x64"`

It appears to be working as expected with this version.
