### ISSUE TITLE
new comment style

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51581]
I propose to change the type of comments used in the code style guide for documentation.

For single-line comments, the syntax "///" will be used.

For comments with more than or equal to 2 lines, the following syntax will apply.

```dart
/**
An example of a class with documentation in the new proposed style. I
think it will be more convenient. But I may not know something. And if
there is a reason to always use ///, please report it.
*/
void example() {}
```

The alignment will be performed in the same way as the alignment of the element for which the comment is specified.

What will it give?
* A single line comment will be one line long, just like before.
* A multi-line comment is only one line longer.
* It will not be necessary to insert /// or * (javadoc style) on each line of code, there is no need to make extra indents from the beginning of the line.
* It's easier to read the comment, because no extra characters and indents.

Among the possible shortcomings, one case can be distinguished when the code needs to be printed on a sheet of paper, then it may not be clear to everyone that there is a comment in front of them on a sheet of paper, if it is long enough, there are code examples in it.

The result will be the following. Simple comments without extra characters, but a multi-line comment will only be 1 line longer.

For simple comments, it is suggested to apply the same style.

**Comment by lrhn** [comment]
While I'd always love to save four characters per line (at the cost of *two* extra lines, not one), I think this will be a hard sell.

The main issues are:
* It's not visible by looking at the individual line whether it's a comment or not. Without syntax coloring (as you say: printed on paper), it will be *very hard* to quickly scan a file and see what's code and what's comments. Especially since comments often contain code examples. Example:
    ````
    /**
    Does something
 
    Example:
    ```
    for (var i = 0; i < 10; i++) {
      print(example[i]);
    }
    ```
    */
    void banana(List<int> example) {
      for (var i = 0; i < 10; i++) {
        print(example[i]);
      }
    }
    ````  
    It also increases the risk of confusing comments and multi-line string contents.

* People prefer `//` and `///` over `/*` and `/**` for a reason. You don't have to *match* start/end markers. You comment out a range by selecting the lines and having your IDE insert `//` on every line. Removing it again is equally simple.
    To uncomment a *part* of a commented out region, you just need to select the range and uncomment it. No need to find and move delimiters.
    I'll happily argue that EOL-comments have won the usability-war, and delimited comments is something new languages won't even consider adding in the future. They've gone the way of Java's checked exceptions - nice idea, shame about the usability in practice.

The arguments for are:
* More characters available per line (4).
* No leading noise on lines, making comments easier to read (in source).

I'm also not seeing those as very convincing.

If we really think lines are too short, we can up the line length to 84. Or 100 or 120, which people often ask for.
For comments I don't even think it's a good idea to make them longer. 
I routinely break my lines early, at semantic break points, instead of trying to fill out the lines. That makes editing easier,
reading in source is fine, and when formatted by DartDoc, it's all reflowed as HTML anyway.

The only place where the longer line helps is if you always try to keep the first DartDoc paragraph on a single line,
but the "single line" is just a guideline (pun not intended), and having a word or tow on the next line is not a problem.

I also don't find the "margin characters" to impede reading comments in source. It's just a fixed margin, something we're trained to work with anyway. If anything, it gives you a fixed left margin to follow when reading. I'm not sure how well
a deeply indented comment would work out without that. Example:
```dart 
                                    /*
                                    Comment deep in my inner loop.
                                    This is an important loop, so I'm commenting it very extensively.
                                    Here is an example of why this is a good idea:

                                       banana(["watermelon", "cantaloupe"]);
                                       // See how bad that would be!

                                   I hope this is convincing.
                                    
                                    */
 ```
vs
```dart 
                                    // Comment deep in my inner loop.
                                    // This is an important loop, so I'm commenting it very extensively.
                                    // Here is an example of why this is a good idea:
                                    // 
                                    //   banana(["watermelon", "cantaloupe"]);
                                    //   // See how bad that would be!
                                    //
                                    //  I hope this is convincing.
```

So, all-in-all, I don't see it as solving something I see as a significant problem, and everything so far suggests that people strongly prefer EOL-comments over delimited comments.

**Comment by gmb119943** [comment]
I can assume that any modern IDE can highlight comments with color. I think the probability that someone will study complex code on a piece of paper is small. And in simple code it will be seen that a comment is a comment. As a last resort, the IDE could have a print function that would change the comment style when printed in black and white. The strong preference may be related to the guidelines that apply in the dart manual.

**Comment by lrhn** [comment]
We have no current, or expected, plan to change the comment syntax to something like what is suggested here.
I don't see that happening.
If we ever change the syntax, I'd expect it to be to something radically different then `/*` or `//` based comments.
(Or just removing `/*..*/` comments entirely, I can actually see that possibly happening, but it's probably never going to become a priority unless we start needing the syntax for something else.)
