### ISSUE TITLE
[dart2wasm] Incorrect async task scheduling

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#51599]
Minimal version of the test language/async/call_test:

```dart
var result = "";

void bar() async {
  result += "1";
  await null;
  result += "2";
}

void main() async {
  bar();
  print(result);
}
```

The test expects this to print "1", but with dart2wasm it prints "12".

I can't find where in the language spec we describe async task scheduling so I'm not sure if this scheduling is part of the language or just how AOT and dart2js implement it. If we can accept "12" as a valid output for this program we should probably check the failing async tests and skip those that rely on implementation-specific task scheduling.

**Comment by askeksa-google** [comment]
We currently don't suspend an `async` function when the `await`ed value is not a `Future`. This is apparently not how `await` is supposed to work.

This in itself is easy to fix. In `_awaitHelper`, just replace
```dart
  if (operand is! Future) return operand;
```
by
```dart
  if (operand is! Future) {
    operand = Future.value(operand);
  }
```
This fixes your reduced example, but `language/async/call_test` still fails with
```
Expect.equals(expected: <barbar2microfoo>, actual: <barfoomicrobar2>) fails.
```
I wonder what the logic is behind the ordering expectation here. @munificent ?

**Comment by osa1** [comment]
I asked this to @lrhn who helpfully sent me this annotated version of the test `async/call_test`: https://dartpad.dev/?id=9477ee16961d25fbe2511882923a477a

The key point is that the microtasks are scheduled in FIFO order, and when you return to the event loop in an `await` you run microtasks in FIFO order. As far as I understand, it doesn't matter which task needs to be run in an `await` (e.g. the task for the awaited future may be the 10th task in the queue, or the first, it doesn't matter), you return to the event loop, which runs the next microtask in the queue, until the awaited future is evaluted.

In the smaller repro above, `bar()` runs the first statement and then returns a future. A microtask for evaluating the future is added to the queue. Since we don't return to the event loop again (at least not before `main` finishes) the print should just print `1`, not `12`, because the task that evaluates `null` and continues with the rest of `bar` is never scheduled.

**Comment by lrhn** [comment]
Precisely.

An `await` always causes a wait. That's done by turning `await v` where `v` is not a future into `await Future.value(v)`.
So changing to `if (operand is! Future) operand = Future.value(operand);` is correct and necessary.
Or something sufficiently indistinguishable, like scheduling a microtask yourself and completing the `await` with the value at that point, to avoid allocating a `Future`.

(Well, actually ... you need to do a *typed* `is` check: `if (operand is! Future<T>) operand = Future<T>.value(operand);` where `T` is the static type of the `await` expression. Otherwise the code `FutureOr<Object> f = Future<Object?>.value(null); Object o = await f;` will be unsound. It needs to wrap the `Future<Object?>` in a `Future<Object>.value(f)` and await that, not unpack it and release the `null`.)

Awaiting a future always introduces at least some delay, because awaiting a future means adding a callback/listener to that future, and such a callback is never invoked immediately. Precisely how much delay depends on ... stuff, lots of stuff, including when and how the future is completed. 
But it's always at least one microtask later. 

Microtasks are scheduled FIFO. We effectively promise that, and not doing so will make a lot of tests fail. 
(We don't, however, promise that future completion uses microtasks for everything.)

And precisely correct for the smaller example. There are really only two events in that program: A top level "Start" event which runs `main`, and a microtask scheduled by `await null` to complete the implicit `Future.value(null)`.
The entire `main` runs in the first event, along with the initial part of `bar`. The rest of `bar` runs in the microtask event.
(There are two other futures, returned by `bar` and `main`, but they have no listeners, so we can ignore any microtasks used to complete them.)

**Comment by eernstg** [comment]
Why don't we just replace the current version of the test by the annotated version? Seems helpful. ;-)

**Comment by osa1** [comment]
With @askeksa-google's fix merged in fa90dcc640bbd4d5d8ade433ab5f575c865278ca the original example now works as expected, but the test still fails. New minimal repro:

```dart
var result = "";

foo() {
  result += "2";
}

bar() async {
  await null;
  result += "1";
}

main() async {
  var f = new Future(foo);
  var b = bar();
  await b;
  await f;
  print(result);
}
```

This prints "21", but it should print "12".

**Comment by osa1** [comment]
I wonder if this is a bug in the `Timer` implementation. The new async implementation in https://dart-review.googlesource.com/c/sdk/+/301020 is almost complete (in terms of bugs and features, code is not ready for merging yet) but this bug persists in that branch as well.

**Comment by osa1** [comment]
I did some more debugging, AFAIU we currently don't have a micro-task queue, both micro-tasks and events are added to the same queue.

`Future` constructor calls `Timer.run`, which in dart2wasm just creates a `Timer` with 0 as duration and schedules it, and `_schedule` just calls `scheduleCallback`: https://github.com/dart-lang/sdk/blob/4c20cedd3031979f8eed536d9c1ebeb76521d5c5/sdk/lib/_internal/wasm/lib/timer_patch.dart#L28-L42

Which is the same function used for scheduling micro-tasks: https://github.com/dart-lang/sdk/blob/4c20cedd3031979f8eed536d9c1ebeb76521d5c5/sdk/lib/_internal/wasm/lib/timer_patch.dart#L74-L80

So it seems like we have one FIFO event queue and micro-task scheduling is not supported.

**Comment by osa1** [comment]
I'm implementing this in https://dart-review.googlesource.com/c/sdk/+/305201.
