### ISSUE TITLE
Color swatches not rendering for new switch expressions

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#51613]
```dart
enum Color {
  red, orange, yellow
}

String name(Color color) {
  return switch (color) {
    // Uh-oh.
    Color.red => throw 'red!',
    Color.orange
      // Tangerine?
      => 'orange',
    Color.yellow => 'yellow'
  };
}
```

Produces:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/67586/222572413-f9b25e3a-09df-4e2b-b1ee-f3165d62f5b1.png">

Contrast w/ old switch statements:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/67586/222572668-02fcd991-ec3e-4f9b-b914-624453aec7f8.png">

(Tested in IntelliJ; may be an issue in VS Code too 🤔 )

/fyi @bwilkerson

**Comment by bwilkerson** [comment]
@DanTup I might be doing something wrong, but I'm not seeing any swatches in VS Code. But then, these aren't Flutter colors, so that's probably the expected behavior.

**Comment by DanTup** [comment]
Yep, IIRC in server we only support `dart:ui` Colors (or users custom colours that map onto them), because we evaluate the constants and read the RGB values from the class (server doesn't know what colour the string "red" is). 

I don't think IntelliJ uses colours from the server (they're only exposed for LSP), so it's probably doing its own thing (possibly using colour names from https://github.com/flutter/tools_metadata) and maybe can handle custom enums with the same names like this? (@stevemessick ?)

**Comment by stevemessick** [comment]
I expect colors will show up once the Dart plugin fully supports patterns and records. The IntelliJ color display depends on the Dart parser in the Dart plugin, and I believe that update is in progress now.

**Comment by jacob314** [comment]
This is an IntelliJ issue only. Would be good to test that VSCode works fine with properly defined colors. It is a bit of a misfeature that this work in Flutter IntelliJ using an enum rather than proper `dart:ui`. colors.

Moved to the intellij plugin
https://github.com/flutter/flutter-intellij/issues/6661

**Comment by DanTup** [comment]
Tweaking the code to use dart:ui colours, the previews and swatches do show up inside switch expressions in VS Code:

<img width="594" alt="Screenshot 2023-03-08 at 10 54 54" src="https://user-images.githubusercontent.com/1078012/223694820-4a8fe420-484c-4808-abf6-7f0da9912880.png">

However, using the colour picker to change the color doesn't add `const` so can introduce an error. I'll open a change to fix that (it's not likely people will use the colour picker in this context, but probably this issue shows up in other `const` contexts).

**Comment by pq** [comment]
Awesome. Thanks Danny!
