### ISSUE TITLE
[Class Modifiers] Possible over-reporting of diagnostics for class modifiers

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#51611]
If I'm understanding the semantics of class modifiers correctly, I think we're reporting a diagnostic that we shouldn't be in some cases.

Given a file named `a.dart` containing:

```dart
base class A {}
```

The following code:

```dart
import 'a.dart';

class B implements A {}
```

produces two diagnostics:

```
CompileTimeErrorCode.SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED (24, 1) The type 'B' must be 'base', 'final' or 'sealed' because the supertype 'A' is 'base'.

CompileTimeErrorCode.BASE_CLASS_IMPLEMENTED_OUTSIDE_OF_LIBRARY (37, 1) The class 'A' can't be implemented outside of its library because it's a base class.
```

I think we should only produce the second of these diagnostics, because I think that adding modifiers to `B` won't fix the second diagnostic.

@kallentu @pq

**Comment by kallentu** [comment]
If I'm understanding you correctly, I feel like they are both useful. The fix for the first one won't fix the second, but the same is true the other way around.

I can see a use case where if a user only gets the second error and then fixes it (say they meant to extend instead) and then they need to refresh/rebuild only to find a new `CompileTimeErrorCode.SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` they didn't see before because it was hidden by the `CompileTimeErrorCode.BASE_CLASS_IMPLEMENTED_OUTSIDE_OF_LIBRARY` error.

Well, okay, I guess that's also fine, but I thought it'd be good to show both so users can be aware of both simultaneously? Do we want to only show the user one error at a time?

**Comment by bwilkerson** [comment]
> Do prefer to show the user one error at a time in this scenario?

I thinks so, but please check my reasoning. I think it's the case that in the event that the user can't modify the imported library, the only way for the user to fix the `CompileTimeErrorCode.BASE_CLASS_IMPLEMENTED_OUTSIDE_OF_LIBRARY` is to stop implementing the base class.

If that's true, then it seems like there's no point in telling the user to add a modifier because they still won't be able to implement the class. It seems like there's an order in which the diagnostics need to be addressed, and by only showing the user the diagnostic that needs to be addressed first we can help guide the user to a valid solution. By showing both diagnostics we risk wasting the user's time as they attempt to fix the wrong diagnostic first.

**Comment by eernstg** [comment]
I also think it's fine to report both errors: The change from `implements` to `extends` is required because class `B` must inherit member implementations from `A` (in particular, if `A` has some private instance members then `B` will have them, too), and the change from `class` to `base class` (`final` will do, too, and `sealed`) is required because this guarantee must be propagated to subtypes of `B` as well. So each error is referring to a separate required source code change, and that seems to justify having two error messages.

**Comment by bwilkerson** [comment]
Given that information, I agree. Thanks.

**Comment by scheglov** [comment]
We should also discuss:

1. What to do for `final` superclass. I think we should report an error that says that you cannot extend / implement / mixin it. And should not report `SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED`.

2. Whether we want a specific error code for `base`, to exclude `FINAL_`  from it, because outside of the defining library nothing could be done for `final`.

**Comment by kallentu** [comment]
1. It makes sense to me to not report `SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` for `final`.
2. Can separate the errors to `SUBTYPE_OF_BASE_IS_NOT_BASE_FINAL_OR_SEALED` and `SUBTYPE_OF_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` and use them based on the modifier we find. And avoid using `SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` for outside of library subtypes.

**Comment by scheglov** [comment]
1. OK
2. I understand using `SUBTYPE_OF_BASE_IS_NOT_BASE_FINAL_OR_SEALED` outside of the library.
3. I don't understand where we can use `SUBTYPE_OF_FINAL_IS_NOT_BASE_FINAL_OR_SEALED`. Inside the library? We cannot subtype a final class outside, right?

**Comment by kallentu** [comment]
`SUBTYPE_OF_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` would be reported only inside the library, yes.
Outside, you can't do anything about this, so we don't report this error.

**Comment by scheglov** [comment]
Would we use `SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` then?
Or is it completely covered by `SUBTYPE_OF_BASE_IS_NOT_BASE_FINAL_OR_SEALED` and `SUBTYPE_OF_FINAL_IS_NOT_BASE_FINAL_OR_SEALED`?

**Comment by kallentu** [comment]
Nope! I would then remove `SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` and replace it with `SUBTYPE_OF_BASE_IS_NOT_BASE_FINAL_OR_SEALED` and `SUBTYPE_OF_FINAL_IS_NOT_BASE_FINAL_OR_SEALED` where we specified before.

These two errors would replace and completely cover `SUBTYPE_OF_BASE_OR_FINAL_IS_NOT_BASE_FINAL_OR_SEALED`.
