### ISSUE TITLE
Do guard expressions promote types of shared variables in switch statements?

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#51644]
Consider the following program.

```dart
test(dynamic x) {
  switch (x) {
    case String? a? when a is Never:
    case String? a when a != null:
    case String? a! when a == 1:
      return a.startsWith("foo"); // The static type of 'a' is expected to be the non-nullable 'String'.
    default:
      return null;
  }
}
```

Should the type of the variable `a` be promoted to non-nullable because of the checks done in the guard expression? Neither the Analyzer nor the CFE promote the type at the moment.

```
  error • The method 'startsWith' can't be unconditionally invoked because the receiver can be 'null'. • /tmp/asdf.dart:6:16 • unchecked_use_of_nullable_value
```

```
// /tmp/asdf.dart:6:16: Error: Method 'startsWith' cannot be called on 'String?' because it is potentially null.
// Try calling using ?. instead.
//       return a.startsWith("foo"); // The static type of 'a' is expected to be the non-nullable 'String'.
//                ^^^^^^^^^^
```

One of the affected tests: https://github.com/dart-lang/co19/blob/45f802f212a9f5fe684f849ec49eb177c2b274ec/LanguageFeatures/Patterns/shared_case_scope_A02_t01.dart#L93-L96.

**Comment by johnniwinther** [comment]
cc @stereotype441

**Comment by stereotype441** [comment]
What's happening here is that the pattern `String? a!` isn't promoting `a` to `String`.  Here's why.   The pattern `String? a!` is modelled as performing these actions:
1. Null-check the scrutinee.  This promotes the scrutinee's type to its non-nullable counterpart.  However, since there is no non-nullable version of `dynamic`, the scrutinee type stays as `dynamic`.
2. Check if the scrutinee is of type `String?`.  If `String?` is a subtype of the scrutinee type, this ought to promote the scrutinee.  And it does.  But unfortunately, due to a bug, this promotion happens a little too late, so the effect of the promotion isn't seen by step 3 (oops!).
3. Declare a variable `a` of type `String?` and initialize it with a value of the scrutinee type.  This initialization considers `String` to be a type of interest, so it will promote `a` to `String` *if* the scrutinee type is a subtype of `String`.  Unfortunately, the scrutinee type is `dynamic`, so no promotion occurs.

Ok, so the first obvious thing we should do is fix the bug that's preventing step 2 from promoting.  I'm happy to do that, and I'll send out a CL for that soon.  Unfortunately, that won't fix the example, because then step 2 will promote the scrutinee to `String?`, which is still nullable, so no promotion will occur in step 3.

Another fix we could do is to change step 1 so that when we null-check `dynamic`, it promotes to `Object`.  If we do that, the example *still* doesn't work, because now that step 1 has promoted to `Object`, step 2 no longer promotes (because `String?` is not a subtype of `Object`), and thus the initializer type seen in step 3 is `Object`; this is not a subtype of `String`, so step 3 doesn't promote.

A further fix we could do is to change the promotion logic for required types so that if the matched value type is non-nullable, then rather than promote to the required type, we promote to its non-nullable counterpart.  That would bean that in step 2, since the matched value type is `Object`, the required type of `String?` is sufficient to cause promotion to `String`.  Therefore in step 3, the initializer type would be `String`, and the variable `a` would be promoted to `String`.  I'm happy to do this fix as well.

But I'm not really comfortable with the change where we allow a null check to promote `dynamic` to `Object`.  We don't do this elsewhere in flow analysis, because we don't want to lose the dynamic nature of `dynamic`.  For example, this code is allowed:
```dart
f(dynamic x) {
  if (x != null) {
    print(x > 0); // ok, because `x` is still `dynamic`
  }
}
```
Similarly, I think this should be allowed:
```dart
f(dynamic x) {
  switch (x) {
    case (> 0)?: // ok, because in the relational pattern `> 0`, the scrutinee is still dynamic
      ...
  }
}
```
So unless we're going to implement a "non-nullable dynamic" type, or add logic to flow analysis to track nullability separately from type, @chloestefantsova's example is never going to work as written.  But once I make my bug fixes, changing the type from `dynamic` to `Object?` should be sufficient to make it work.

I'll go ahead and assign the issue to myself as a reminder to make the two fixes I outlined above.

(Side note: you may be wondering why `when a == 1` is not sufficient to promote `a` to non-nullable.  The reason is because the only thing that flow analysis knows about the integer literal `1` is that it's an expression whose static type is `int`, and due to mixed mode unsoundness, an expression whose static type is `int` *might* be null.  In the future, once we've fully removed support for mixed mode unsoundness from Dart, we could consider improving this.)

**Comment by chloestefantsova** [comment]
Thank you for the detailed analysis, Paul! Both the `dynamic` type of the scrutinee and the comparison with `1` are byproducts of my playing around with the example from the test and adding some unintended side effects. Making this particular code example to pass through both of the tools doesn't seem important. I agree that using `Object` as a non-nullable version of `dynamic` after a promotion doesn't work well with the dynamic nature of `dynamic`, and I think we should leave it as it is.

If I change the type of `x` to `String?` and the target of the equality comparison to `"foo"`, the Analyzer accepts the program, but the CFE does not. So it's something I can start working on.

```dart
test(String? x) {
  switch (x) {
    case String? a? when a is Never:
    case String? a when a != null:
    case String? a! when a == "foobar":
      return a.startsWith("foo"); // The static type of 'a' is expected to be the non-nullable 'String'.
    default:
      return null;
  }
}
```

However, if I change the type of `x` to `Object?`, the Analyzer reports the following error.

```
  error • The method 'startsWith' can't be unconditionally invoked because the receiver can be 'null'. • /tmp/asdf.dart:6:16 • unchecked_use_of_nullable_value
```

Is it something that will be fixed by adjusting step 2 in your analysis?

**Comment by stereotype441** [comment]
@chloestefantsova wrote:
> Thank you for the detailed analysis, Paul! Both the `dynamic` type of the scrutinee and the comparison with `1` are byproducts of my playing around with the example from the test and adding some unintended side effects. Making this particular code example to pass through both of the tools doesn't seem important. I agree that using `Object` as a non-nullable version of `dynamic` after a promotion doesn't work well with the dynamic nature of `dynamic`, and I think we should leave it as it is.

Great, sounds good!

> If I change the type of `x` to `String?` and the target of the equality comparison to `"foo"`, the Analyzer accepts the program, but the CFE does not. So it's something I can start working on.

Thanks!  You're definitely in a better position to make CFE fixes to this integration logic than I am.

> ```dart
> test(String? x) {
>   switch (x) {
>     case String? a? when a is Never:
>     case String? a when a != null:
>     case String? a! when a == "foobar":
>       return a.startsWith("foo"); // The static type of 'a' is expected to be the non-nullable 'String'.
>     default:
>       return null;
>   }
> }
> ```
> 
> However, if I change the type of `x` to `Object?`, the Analyzer reports the following error.
> 
> ```
>   error • The method 'startsWith' can't be unconditionally invoked because the receiver can be 'null'. • /tmp/asdf.dart:6:16 • unchecked_use_of_nullable_value
> ```
> 
> Is it something that will be fixed by adjusting step 2 in your analysis?

Hmm, that is likely an analyzer bug.  I will investigate.

**Comment by eernstg** [comment]
I tried to extract a proposal for a lint, flagging those locations where a variable of type `dynamic` is tested for being non-null and is subject to promotion, but it has no effect because **NonNull**(`dynamic`) is again `dynamic`.

However, I don't think it makes sense: It looks like there are no good examples of code where the promotion could actually be enabled. We could try something like the following:

```dart
dynamic someFunction() => ...;

void main() {
  var v = someFunction(); // `v` has type `dynamic`, but it might not be obvious.
  if (v == null) return;
  if (v is! int?) return;
  v.isEven; // Error because `v` might be null?!
}
```

It is indeed confusing that we have `if (v == null) return;` right there, and yet we're getting an error because "`v` might be null". However, nobody would actually test for `int?` in that situation, the real problem is that they should test for `int` rather than `int?`, and then the issue goes away.

The example in this issue is similar: Real-life code would not use these slightly redundant kinds of test, they would be more like this:

```dart
test(dynamic x) {
  switch (x) {
    case String a: // Test for `String`, rather than for `String?` followed by a null test.
    case String a! when a == 1: // Don't declare `String? a` when we know it isn't null.
      return a.startsWith("foo"); // OK!
    default:
      return null;
  }
}
```

**Comment by stereotype441** [comment]
As of https://github.com/dart-lang/sdk/commit/5f8c28e2265a01c2af327911d832b6b3c8361387, I've fixed the two issues I promised to address in https://github.com/dart-lang/sdk/issues/51644#issuecomment-1456737022.  Although @chloestefantsova's initial example still won't work, it sounds like we have reached a consensus opinion that that's ok, because we don't want a null check to promote `dynamic` to `Object`.

So I'm marking this as fixed.
