### ISSUE TITLE
[Patterns] The compiler thinks that matching in switch is not exhaustive. But why?

### ISSUE THREAD

**Issue by el-leonya** [dart-lang/sdk#51649]
I decided to try Dart 3 with the following code example:
```dart
sealed class Animal {}
class Cat extends Animal {
}
class Dog extends Animal {
}

void main() {
  var animal = Dog();
  print(animalSays(animal));
}
String animalSays(Animal animal) {
   return switch(animal) {
    Dog()=> "woof",
    Cat()=> "meow",
 };
}
```
compiler output: 
```
Launching lib/main.dart on Linux in debug mode...
main.dart:1
ERROR: lib/main.dart:14:18: Error: The type 'Animal' is not exhaustively matched by the switch cases.
main.dart:14
ERROR:  - 'Animal' is from 'package:exhaustiveness_issue/main.dart' ('lib/main.dart').
main.dart:1
ERROR: Try adding a default case or cases that match Animal.
ERROR:    return switch(animal) {

ERROR:                  ^
ERROR: Target kernel_snapshot failed: Exception
Exception: Build process failed
Exited
```
But why so?
Dart version 3.0.0 (build 3.0.0-290.0.dev)

**Comment by johnniwinther** [comment]
Currently the exhaustiveness is only checked using flow analysis that doesn't handle sealed class, which is why the first example doesn't work; it doesn't know how to go from a value of type `Animal` to its only subtypes `Cat` and `Dog`. For the second, the type inference know that the type of `animal` is `Dog`, which is fully covered by the first case.

**Comment by el-leonya** [comment]
@johnniwinther Thank you! Then I'll wait for it to be implemented. Sorry for the bother!
