### ISSUE TITLE
Question about type inference in pattern variable declarations

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#51640]
In the program below the variable pattern for `x` specifies the type as `C`, omitting the type argument. Should `String` or `dynamic` be inferred for it? In the former case, the last line in `test` should be a compile-time error, but neither the CFE, nor the Analyzer report errors for the program.

```dart
class C<X> {
  const C();

  foo(X x) {}
}

test(int n) {
  var [C x] = <C<String>>[const C<String>()];
  x.foo(n); // Should it be an error?
}
```

**Comment by lrhn** [comment]
This looks like the normal raw-type + covariance problem. 
So it depends on whether the variable pattern `C x` infers a type argument for `C` or not.
I think it [does not](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=If%20the%20variable%20has%20a%20type%20annotation%2C%20the%20required%20type%20of%20p%20is%20that%20type). Nothing say so, it's just talking about the type of the declaration as normal, so the type of `x` is the )(raw) type `C` which means `C` instantiated to bounds.

It's safe and sound to assign `C<String>` to `C<dynamic>`. It's sound to call `x.foo(anInt)` on a `C<dynamic>`. It fails at runtime due to unsafe covariance.

**Comment by eernstg** [comment]
I agree. Raw types used as types (not instance creations) are completed using instantiation to bound.

We did have discussions about inferring type arguments in cases like `Iterable<T> it;`, `if (it is List) ...`, which would then mean `if (it is List<T>) ...`, but none of these things have happened so far.

There is one exception: An object pattern `C(...)` can be transformed into `C<T1 .. Tk>(...)` during type checking &amp; finalization of patterns, based on the matched value type. That particular position is working very much like an `is` check in a matching context (plus other things, like providing the receiver type for some getter invocations), but I think that this is a special case and the general rule about using i2b still stands.

**Comment by chloestefantsova** [comment]
Thank you, Lasse and Erik, for clarification!
