### ISSUE TITLE
No `strict_raw_type` error reported in casts

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#51672]
I would expect that when `strict-raw-types` is enabled, the following cast leads to an analysis error:

```dart
final foo = null as List;
```

The type argument for `List` is omitted, so it is inferred to be `dynamic`, but without reporting a `strict_raw_type` error.

**Comment by srawlins** [comment]
This is intentional. The rule does not protect against raw types in `as` or `is` checks, as it was deemed too onerous to comply with and too noisy. I'm not sure we have a linter rule which would enforce explicit type arguments in those positions, but it's something we could do. If you'd like such a rule, please file a request at https://github.com/dart-lang/linter/issues.

**Comment by incendial** [comment]
<img width="636" alt="Screenshot 2023-03-20 at 00 28 50" src="https://user-images.githubusercontent.com/21116742/226207110-2d351d6f-7fe6-4cfc-9eca-a4fd0a6a6944.png">

Shouldn't this warning be enough?

**Comment by srawlins** [comment]
That might be a red herring. I think a more complete example would be:

```dart
void m(dynamic d) {
  d as List;
}
```
