### ISSUE TITLE
pkg/vm/test/transformations/type_flow/summary_collector_test fails with records and patterns enabled

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51692]
I'm working to enable the experiment flags for "records" and "patterns" and this test is failing. I don't want to just update the expectations to get it to pass because I don't know what this test actually does. But it also doesn't look like a critical failure. So I'm just going to approve this failure for now and leave this bug to track it.

**Comment by alexmarkov** [comment]
This is a unit test for building data flow representation (summary) which is used by global type flow analysis (TFA), a part of native AOT compiler and dart2wasm.

The expectations changed because CFE started generating sequences of `if` statements with extra `operator==` calls for old-style switch statements. Addressing https://github.com/dart-lang/sdk/issues/51391 should restore kernel AST for old-style switch statements which should fix the unit test.

I think it is fine to update the test expectations for now, as this is already tracked in https://github.com/dart-lang/sdk/issues/51391.
