### ISSUE TITLE
co19/Language/Statements/Labels/scope_t04 times out in dart2js when records and patterns are enabled

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51696]
I'm working on the CL to enable the "records" and "patterns" experiments. This test is timing out on dart2js. I briefly tried debugging it, but the opened browser just locks up, so I'm not sure what's going on.

I'll approve the test for now because labels are a very rarely used language feature anyway, so this is likely not critical.

**Comment by rakudrama** [comment]
Repro:
```dart
main() {
  bool flag = false;
  L: for (num i in [1, 2.3]) {
    switch (i) {
      L:
      case int _:
        print('A');
        flag = true;
        break;
      case double _:
        print('B');
        continue L;
    }
  };
  if (flag == false) throw 'flag = $flag';
}
```
The switch has an internal label that is reached by `continue L;`

The CFE breaks this into an if-then-else dispatch to set a target `#t1` and then switches on the target. The switch still has label `L`:
<details>

```
library /*isNonNullableByDefault*/;
import self as self;
import "dart:core" as core;

static method main() → dynamic {
  core::bool flag = false;
  for (core::num i in <core::num>[1, 2]) {
    #L1:
    {
      core::int #t1 = -1;
      final synthesized core::num #0#0 = i;
      if(#0#0 is{ForNonNullableByDefault} core::int)
        #t1 = 0;
      else
        if(#0#0 is{ForNonNullableByDefault} core::double)
          #t1 = 1;
      switch(#t1) {
        #L2:
        case #C1:
          {
            {
              core::print("A");
              flag = true;
              break #L1;
            }
          }
        #L3:
        case #C2:
          {
            {
              core::print("B");
              continue #L2;
            }
          }
      }
    }
  }
  ;
  if(flag =={core::Object::==}{(core::Object) → core::bool} false)
    throw "flag = ${flag}";
}
constants  {
  #C1 = 0.0
  #C2 = 1.0
}
```

</details>

dart2js sees the switch with a label and applies a similar trick, using the variable `target`, and wrapping the switch on `target` in a loop:

<details>

```js
    main() {
      var t1, flag, _i, t2, target;
      for (t1 = [1, 2.3], flag = false, _i = 0; _i < 2; ++_i) {
        if (A._isInt(t1[_i]))
          t2 = 0;
        else
          t2 = 1;
        switch (t2) {
          case 0:
            target = 1;
            break;
          case 1:
            target = 2;
            break;
        }
        if (target)
          c$0:
            for (; true;)
              switch (target) {
                case 1:
                  A.printString("A");
                  flag = true;
                  continue;
                case 2:
                  A.printString("B");
                  target = 1;
                  continue c$0;
              }
      }
      if (!flag)
        throw A.wrapException("flag = false");
    }
  },
```

</details>

The bug is that `break #L1;` in the lowered kernel is compiled to `continue;`, which causes the program to get stuck in the `for(; true; )` loop.
This is a bizarre choice is probably trying to `continue` the outer loop for the for-in loop of the original source, but that loop does not have a label. This points to the wrapping `for(;;)` loop not being constructed with a full label scope model.


A side note: dart2wasm places a switch in a loop, but assigns one of the switch constants to the discriminant rather than having two dispatches. This seems like a superior strategy.

**Comment by rakudrama** [comment]
Version showing bug exists before patterns feature:
```
// @dart=2.19
main() {
  bool flag = false;
  L1: for (int i in [1, 2]) {
    switch (i) {
      L2:
      case 1:
        flag = true;
        continue L1;
      case 2:
        continue L2;
    }
  };
  if (flag == false) throw 'flag = $flag';
}
```

**Comment by rakudrama** [comment]
This is now fixed
