### ISSUE TITLE
[Feature Request] allow `throw Error(text);` like `Exception`, instead of `Error.throw(text, StackTrace.current)`

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#51709]
Please guide, how may I `throw` an error, without going through the lengthy process of calling 
`Error.throwWithStackTrace(message, StackTrace.current)`, while 
`throw Exception(message);` for exception,

Also, `throwWithStackTrace` has a null-check, is it here to stay, or yet to be removed with some future release,

thanks

**Comment by lrhn** [comment]
You're asking for a constructor on `Error` which creates an error object, but is not one of the existing subclasses of `Error`:
* `StateError`
* `ArgumentError`
* `UnsupportedError`
* `UnimplementedError`

Can you describe what kind of error you have where none of those subclasses are suitable?

You throw an error by doing `throw UnsupportedError("Can't do that!")`.
Or you can do `throw "message";` to throw a string object. In Dart, every object except `null` is throwable.

Doing `Error.throwWithStackTrace(message, StackTrace.current)` is just the same as `throw message`. It doesn't throw an object implementing `Error`.

Pointing to the `Exception` constructor is not convincing, since you should never use that constructor in real code.
It will probably be deprecated soon, possibly eventually removed. You should throw an exception when you want to receiver to catch and recognize it, and understand what exceptional occurrence it represents. Using a plain `Exception` doesn't do that.

The `throwWithStackTrace` has a null check only until Dart 3.0. Then it becomes completely impossible to pass `null` to it.
There are not plans to change that.
