### ISSUE TITLE
Program exits despite isolates remaining alive

### ISSUE THREAD

**Issue by abitofevrything** [dart-lang/sdk#51713]
It seems that the dart process exits after the main isolate exits, which causes the following program to terminate despite the other isolate still being alive:
```dart
import 'dart:isolate';

void isoMain(Object? message) {
  while (true) {
    print('I am alive');
  }
}

void main() {
  Isolate.spawn(isoMain, null);
}
```

I would expect this to print `I am alive` forever (or until interrupted by the user). Instead, it's printed a few times, then stops and the program exits without an error.

Dart SDK Version (`dart --version`): `3.0.0-290.0.dev (dev) (Thu Mar 2 14:58:47 2023 -0800) on "linux_x64"`

**Comment by abitofevrything** [comment]
Interestingly, passing `--observe` fixes the issue and the program runs normally.

**Comment by julemand101** [comment]
Dart programs stop when the main isolate have nothing more to do and does not subscribe to any kind of events which would result in new work to be available in the future (e.g. Timer's and ReceivePort's).

In your example, you are just spawning an `Isolate` and hereafter the main-isolate is left without more to do. So the program stops.

I guess with `--observe`, we have a situation where the supporting logic for observatory are left running so we can visit the observatory even after the program are done running. Since this is running, it will not mean the Dart process are being killed after the main-isolate are done running.

**Comment by lrhn** [comment]
What @julemand101 says.

The VM exits when the main isolate is done, unless the something keeps the process alive. Apparently the observatory count as keeping it alive.
So working as intended.

**Comment by julemand101** [comment]
@lrhn Should this behavior be documented somewhere officially? I could not find anything in the Tour, the page about concurrency or API doc for Isolate.

**Comment by abitofevrything** [comment]
This should definitely be documented, as it means async tasks in other isolates may not be executed. `Isolate.spawn` might be a good place to put it.

Something along the lines of "Isolates created with `Isolate.spawn` or `Isolate.spawnUri` will not prevent the program from exiting. If the main isolate exits and other isolates are left running, those isolates will be killed and the program will exit."
