### ISSUE TITLE
incomprehensible classification of keywords

### ISSUE THREAD

**Issue by e1b916a3** [dart-lang/sdk#51729]
The keywords page https://dart.dev/language/keywords lists the types of keywords indexed 1, 2 and 3. Each of these types has a name. But personally, these names confuse me a little. For example, "built-in identifiers" means that the keyword is reserved for some use as an identifier. But for example, in this category there is the word implements, which is somehow not very similar to an identifier.

I propose to replace the paragraph about the types of keywords in the documentation. Say that there are keywords and there are contextual keywords. Contextual keywords are keywords in a specific context. If necessary, you can specify using the numbers 1, 2, 3 the context in which they are key.

**Comment by eernstg** [comment]
A built-in identifier is an identifier which is not allowed to be the declared name of a type or an import prefix. This concept is needed in order to disambiguate the syntax in certain situations. It is a "softer" constraint than being a reserved word. For example, a built-in identifier can be the name of a local variable or function parameter:

```dart
void main() {
  int implements = 1;
  print(implements);
}
```

I'd suggest that you use the 'bug' button on the 'Keywords' page to report your ideas about how this page could be made more readable. Thanks!

**Comment by e1b916a3** [comment]
https://github.com/dart-lang/site-www/issues/4663
