### ISSUE TITLE
[spec] extension names are typeIdentifiers?

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#51751]
The ANTLR-based grammar spec declares extension names to be identifiers:

https://github.com/dart-lang/sdk/blob/1f598154a0bf04dfa220ef1b4b5f110e87270a85/tools/spec_parser/Dart.g#L429-L432

and 

https://github.com/dart-lang/language/blob/abca38c39e9bea0af2ff47fce55d6686207178e7/specification/dartLangSpec.tex#L5740-L5744

Class names, for example, are typeIdentifiers:

https://github.com/dart-lang/sdk/blob/1f598154a0bf04dfa220ef1b4b5f110e87270a85/tools/spec_parser/Dart.g#L369-L378

identifiers are builtInIdentifiers so if extensions had identifiers as names, then I should be able to name an extension `abstract` which is a builtInIdentifier, but:

```dart
// The built-in identifier 'abstract' can't be used as an extension name.
//        vvvvvvvv
extension abstract on int {}
```

It looks like the name of an extension is meant to be a typeIdentifier. Is that correct?

**Comment by eernstg** [comment]
How lucky that it's implemented such that an extension name can't be a built-in identifier! ;-)

I don't actually remember. It might be a plain mistake, or it might have been specified as an `<identifier>` because the name of an extension can't occur in the same syntactic positions as type names, it can only be used in an explicit extension method invocation (like `MyExtension<Some, Types>(receiver).method(...)`) and in a show/hide clause in an import.

Nevertheless, I'd prefer to change it to `<typeIdentifier>` because it is already implemented, and it's more consistent, and it yields more readable code.

**Comment by modulovalue** [comment]
builtInIdentifier extension names are a compile-time error:

https://github.com/dart-lang/language/blob/abca38c39e9bea0af2ff47fce55d6686207178e7/specification/dartLangSpec.tex#L5845-L5846

**Comment by modulovalue** [comment]
> Nevertheless, I'd prefer to change it to <typeIdentifier> because it is already implemented, and it's more consistent, and it yields more readable code.

I agree.

https://github.com/dart-lang/sdk/issues/51755 is related and it might make sense to resolve it first.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/pull/2923.

**Comment by modulovalue** [comment]
This appears to have been fixed via https://github.com/dart-lang/language/issues/3258 in https://github.com/dart-lang/sdk/commit/5cebb0f98015d4a9835b105e0295d74ee5723609

Thank you @eernst!
