### ISSUE TITLE
a compilation detection problem

### ISSUE THREAD

**Issue by hcanyz** [dart-lang/sdk#51775]
I found an interesting phenomenon, but I'm not sure which piece of the problem it is.

- unusual
```dart
int test(Iterable<int> some) {
  int? x;
  some.forEach((element) {
    x = 0;
  });
  if (x == null) {
    return 0;
  }
  return x;
}
```
![image](https://user-images.githubusercontent.com/8407922/226085335-512a0dcd-d3c8-4309-a0ad-bc5738f496d2.png)

- It's normal to change it to this
```dart
int test(Iterable<int> some) {
  int? x;
  for (var _ in some) {
    x = 0;
  }
  if (x == null) {
    return 0;
  }
  return x;
}
```
![image](https://user-images.githubusercontent.com/8407922/226085368-37599592-904d-4db2-a5e1-9175b290b25d.png)

* Dart SDK Version (`dart --version`) 
![image](https://user-images.githubusercontent.com/8407922/226085431-958fbc18-acb3-48a2-8686-13a0c1d9e6d9.png)
![image](https://user-images.githubusercontent.com/8407922/226085472-8ef15eac-8f4c-4d1e-b262-6a61c3214f1a.png)
* Whether you are using Windows, MacOSX, or Linux (if applicable) 
![image](https://user-images.githubusercontent.com/8407922/226085490-82a6dbaf-0f19-44c0-855a-44de95b48ad2.png)

thx.

**Comment by lrhn** [comment]
This is expected behavior. There is an assignment to `x` inside a closure. That disables all promotion for `x`.

In this case, the assignment would preserve `x` being promoted to `int`, but the inference algorithm isn't being that clever.

In general, avoid assigning to local variables inside closures, if you also want to promote them.

**Comment by hcanyz** [comment]
I understand, thx.
