### ISSUE TITLE
compiling dart vm to wasi/wasm as bootstrap

### ISSUE THREAD

**Issue by selfisekai** [dart-lang/sdk#51782]
this is just an idea, not sure how hard it would get to implement. inspired by zig: https://ziglang.org/news/goodbye-cpp/

- [ ] add vm compilation targets for wasi
- [ ] allow building sdk using these wasi builds as an alternative bootstrap method (running through wasmtime or other wasi runtime)
- [ ] distribute official wasi builds

bootstrapping is a major point of pain from alpine linux perspective - we currently rely on a windows build via wine, which greatly limits available architectures

**Comment by mraleph** [comment]
Compiling to WASI would:

a) require rewriting parts of the runtime that rely on things like `mmap`
b) using simulated build (e.g. simarm or simarm64) because Dart VM does not currently have an interpreter.

This is feasible, but hardly optimal. There is a much simpler path towards enabling bootstrap on alpine, outlined in this [comment](https://github.com/dart-lang/sdk/issues/40906#issuecomment-1385299534). 

I am going to file an issue to track this work, though we are not committing at any concrete timeline yet.

**Comment by mraleph** [comment]
Filed https://github.com/dart-lang/sdk/issues/51788
