### ISSUE TITLE
Plus operation on inline classes seems expensive

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#51790]
Is it expected that an operation like `+=` is much more espensive on an inline class with a representation type of int, then on plain ints?

Consider these results; especially the AOT ones:
```
$ dart run --enable-experiment=inline-class test.dart
Measure `IdNumberC`:
  3401: Allocate
  2555: Compute sum
Measure `IdNumberI`:
  1000: Allocate
  1784: Compute sum
Measure `int`:
  970: Allocate
  1560: Compute sum

$ dart compile exe --enable-experiment=inline-class test.dart
Info: Compiling with sound null safety.
Generated: /Users/mit/tmp/test.exe

$ ./test.exe
Measure `IdNumberC`:
  3056: Allocate
  96: Compute sum
Measure `IdNumberI`:
  1029: Allocate
  295: Compute sum
Measure `int`:
  1103: Allocate
  96: Compute sum
```

test.dart program:
```dart
// Timing and infra.

const count = 100000000;
int _now() => DateTime.now().millisecondsSinceEpoch;
late Timer timer;

class Timer {
  int start;
  Timer(): start = _now();
  int get time => _now() - start;
  void clear() => start = _now();
}

void speak(String message) {
  print('  ${timer.time}: $message');
  timer.clear();
}

// Targets.

class IdNumberC {
  final int value;
  IdNumberC(this.value);
  IdNumberC operator +(IdNumberC other) => IdNumberC(value + other.value);
}

inline class IdNumberI {
  final int value;
  IdNumberI(this.value);
  IdNumberI operator +(IdNumberI other) => IdNumberI(value + other.value);
}

// Test

void testC() {
  var idNumbers = <IdNumberC>[];
  print('Measure `IdNumberC`:');
  for (int i = 0; i < count; ++i) {
    idNumbers.add(IdNumberC(i));
  }
  speak("Allocate");
  var sum = IdNumberC(0);
  for (var id in idNumbers) {
    sum += id;
  }
  speak("Compute sum");
}

void testI() {
  var idNumbers = <IdNumberI>[];
  print('Measure `IdNumberI`:');
  for (int i = 0; i < count; ++i) {
    idNumbers.add(IdNumberI(i));
  }
  speak("Allocate");
  var sum = IdNumberI(0);
  for (var id in idNumbers) {
    sum += id;
  }
  speak("Compute sum");
}

void testInt() {
  var idNumbers = <int>[];
  print('Measure `int`:');
  for (int i = 0; i < count; ++i) {
    idNumbers.add(i);
  }
  speak("Allocate");
  var sum = 0;
  for (var id in idNumbers) {
    sum += id;
  }
  speak("Compute sum");
}

void main() {
  timer = Timer();
  testC();
  testI();
  testInt();
}
```

**Comment by mit-mit** [comment]
cc @eernstg who found this in https://github.com/dart-lang/language/issues/2727#issuecomment-1474378505

**Comment by lrhn** [comment]
You are calling a static function to perform the addition.
If that static function can be inlined, there should be no overhead. If not, it's like calling:
```dart
int $add(int self, int other) => self + other;
```
everywhere you invoke `IdNumber.+`.

Inline class members are not inherently overhead-free, but they should be equivalent to calling a static function, and any optimizations should apply equally.

**Comment by alexmarkov** [comment]
Without inline class `int.operator+` is recognized and eagerly replaced with optimized `BinaryInt64Op` instruction during `ApplyClassIds` pass.

With inline class this should happen during inlining of `IdNumberI|+` (static method corresponding to `IdNumberI.operator+`). However, this doesn't happen because `ListIterator.current` is inlined to `testI` before `IdNumberI|+` and parameter of `IdNumberI|+` gets a generic type `X0?` from 

```
    v24 <- LoadField(v23 . _current@9040228) T{X0??}
```

As `int.operator+` is not recognized, it remains represented with a static call and `Compute sum` ends up being slower for inline class in AOT.

There are a few things we can improve to make inline class as fast as int here:
- We can recognize int and double operations regardless of operand types if they were devirtualized.
- We can try to merge argument type from the caller and static/inferred type of the parameter during inlining, instead of always using the argument type from the caller.
- We can try to instantiate types during inlining / local type propagation, converting generic `X0?` type to `int?` for load from `ListIterator._current`.

**Comment by mraleph** [comment]
> * We can recognize int and double operations regardless of operand types if they were devirtualized.
> * We can try to merge argument type from the caller and static/inferred type of the parameter during inlining, instead of always using the argument type from the caller.

I'd say we should probably do both of these things.

**Comment by alexmarkov** [comment]
> We can recognize int and double operations regardless of operand types if they were devirtualized.

It turns out we cannot avoid checking the operand type, as `int.operator+` takes `num` as an argument.

> We can try to merge argument type from the caller and static/inferred type of the parameter during inlining, instead of always using the argument type from the caller.

https://dart-review.googlesource.com/c/sdk/+/290602
