### ISSUE TITLE
Failures on [cfe] Improve switch encoding

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#51793]
There are new test failures on [[cfe] Improve switch encoding](https://dart-review.googlesource.com/c/sdk/+/289224).

The tests
```
co19/Language/Statements/Switch/execution_t01 RuntimeError (expected Pass)
co19/Language/Statements/Switch/type_t01 RuntimeError (expected Pass)
co19/Language/Statements/Switch/type_t02 RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-hostasserts-linux-x64-d8
```

**Comment by johnniwinther** [comment]
@askeksa-google The CL changed the lowering to use `SwitchStatement` and I suspect that the failures has to do with that. I checked we set `isExplicitlyExhaustive` to `false`, but the failures indicate that it is `true`, so I'm not sure what is going on.

**Comment by askeksa-google** [comment]
@osa1

**Comment by osa1** [comment]
https://dart-review.googlesource.com/c/sdk/+/290064 fixes compilation of these tests, but as I try more cases I discovered that switches of a case statement can also have different types now (see below). As far as I understand in the general case we need to check the cases with `Object.==`. We can still have special cases when all of the cases and the switch expression have the same type and the type is one of `int`, `String`, or `bool`.

Test case for switch with differently typed cases:

```dart
bool runtimeTrue = int.parse('1') == 1;

int getInt() => runtimeTrue ? 2 : 10;

void main() {
  switch (getInt()) {
    case '1':
      print('1');
      break;
    case '2':
      print('2');
      break;
    case 3:
      print('3');
      break;
    case 4:
      print('4');
      break;
    default:
      print('default');
  }
}
```

I don't know if we have a test for this in the SDK or co19. Given that this change is not part of the spec yet (which still says cases should have the same class) I suspect we probably don't.

**Comment by osa1** [comment]
I talked to @johnniwinther about these tests and the new kernel switch-case semantics in https://dart-review.googlesource.com/c/sdk/+/289224. That CL made two changes in lowering of Dart switch-cases to kernel:

1. It allowed `case`s with differently typed expressions.
2. It allowed differently typed `switch` and `case`s.

As far as I understand (1) was not intentional and we don't have any tests about this. We can support this semantics in dart2wasm if/when we decide to keep this semantics and add tests.

(2) is what broke these tests. Previously when type of `switch` and `case`s are different the front-end would eliminate the switch-case. Example:

```dart
main() {
  switch (1) {
    case '1':
      break;
    case '2':
      break;
    default:
  }
}
```

Previously front-end would generate:

```
label0:
{
  final int #0#0 = 1;
  {}
}
```

With the CL it now generates:

```
label0:
switch (1) {
  case "1":
    break label0;
  case "2":
    break label0;
  default:
}
```

So it's now on backends to simplify/eliminate these switch-case expressions.

I also don't know if this change was intentional and whether we want to keep it, but https://dart-review.googlesource.com/c/sdk/+/290063 correctly handles it. It's not as efficient as before as we don't eliminate the switch-case, but I don't know if it's important to optimize this case as no correct code will have code like this (I hope?). If this change that allows differently typed switch and cases (but uniformly types cases) is intentional we should merge that CL, and deal with the switch-case with differently typed cases if/when we decide that that's the semantics we want for kernel's switch-case.
