### ISSUE TITLE
[analyzer] resulting type of `Set.of` is not inferred

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#51817]
Consider the following example:

```dart
void main() {
  final dogs = [DogImplementsAnimal()];
  final animals = [Animal()];

  final result = Set.of(dogs).difference(Set.of(animals));
}

class Animal {}

class DogImplementsAnimal implements Animal {}
```

If you hover over the first `Set.of`, the type will be correctly displayed as `Set<DogImplementsAnimal>`, but the second one is displayed as `Set<Object?>`.
<img width="1057" alt="Screenshot 2023-03-22 at 18 40 16" src="https://user-images.githubusercontent.com/21116742/226939676-5a34bfe7-e2f2-4053-a492-7eeabeb45990.png">

Not sure whether it works as expected, but the problems for me as that the internal analyzer API also marks the second Set type as `InterfaceTypeImpl (Object?)` which is kinda unexpected.

Have this issue both locally (Dart SDK version: 2.19.4) and on the DartPad.

**Comment by eernstg** [comment]
I'll leave it to the analyzer team to comment on the internal representation, but from a language point of view it is working as intended: Type inference in Dart gives priority to the context type, so based on the fact that the formal parameter type of `difference` is `Set<Object?>`, `Set.of(animals)` is inferred as `Set<Object?>.of(animals)`.

This treatment is one of the many possible approaches, we can indeed have `Animal`s in a `Set<Object?>`. In some situations, this does give rise to a choice of actual type arguments that are more general than expected/desired, but it is not done by accident.

The main reason why Dart type inference gives priority to the context type is that it supports mutability and uses dynamically checked covariance. Those two things give rise to the following interaction between type inference and dynamic checks:

```dart
void main() {
  List<num> xs = [1]; // Inferred as `<num>[1]`: The context rules.
  xs.add(1.5); // OK, `1.5` does have type `num`.

  List<num> ys = <int>[1]; // Let's override type inference and choose the type argument bottom-up.
  ys.add(1.5); // Throws!
}
```

You could say that the Dart type inference algorithm takes the opportunity to eliminate covariance whenever possible, in the sense that the subtyping relation between the static type and the dynamic type of an expression doesn't use the covariance rule (e.g., a variable with declared type `Iterable<num>` will have a value which could be `List<num>`, but not `List<int>` or `List<Never>`).

In particular, type inference does this when new objects are created, either because a constructor call or a list/map/set literal gets the actual type arguments from the context, or with an invocation of a generic function, by passing actual type arguments where the context type is used if possible.

This is a very pragmatic behavior, because it allows newly created lists (and other objects) to be used safely, even in the situation where they have members whose signature uses those type arguments in a non-covariant manner (e.g., `List.add`).

Nevertheless, it is still possible to introduce a covariant subtype relationship simply by overriding type inference as shown in the example, and in many other ways. So you can still have programs with no compile-time errors which will throw at run time because of a failing subtype check.

I would like to have statically checked variance in Dart, dart-lang/language#524, such that everybody who is designing a class can make this trade-off explicitly. However, the current approach has given rise to amazingly few complaints, so I'm sure that will stay around even in the case where we do have statically checked variance.

**Comment by incendial** [comment]
Thanks for sharing the details! That's quite an interesting problem.

From the tooling perspective I provide a lint rule that checks if collection methods are used with related types. When the type of the second set has `Object?` it kinda breaks the check.
But now as I'm typing this I'm starting to understand that despite the type being `Object?` it should be a valid case. Because `Object` is the top supertype and it's impossible to tell what's inside. 

Thank you!

> However, the current approach has given rise to amazingly few complaints

It would be nice to have all the tricky approaches listed somewhere just be aware of them 😁
