### ISSUE TITLE
[DDC] Failures in end-to-end expression compiler tests

### ISSUE THREAD

**Issue by fishythefish** [dart-lang/sdk#51825]
`pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_ddc_unsound_test` is failing on `unittest-asserts-debug-linux` and `unittest-asserts-release-mac-arm64`. (It went from flaky to timeout on the former rather than failing with a runtime error.)

`pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_amd_sound_test`, `pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_amd_unsound_test`, and `pkg/dev_compiler/test/expression_compiler/expression_compiler_e2e_ddc_sound_test` are all failing on `unittest-asserts-release-mac` and `unittest-asserts-release-mac-arm64`.

**Comment by annagrin** [comment]
There are couple of issues causing the failures:
- CFE change to improve the switch statements for patterns breaks incorrect test expectations:
  https://github.com/dart-lang/sdk/commit/04e6f4c28259f13d11b497bc1f4201301ead8309

- There seems to be an issue detecting the end of a scope for switch statements due to synthesized variables that appear before user block but have file offsets from later code. 

Fix: https://dart-review.googlesource.com/c/sdk/+/290706
