### ISSUE TITLE
Syntax error in for-in element for maps and sets

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#51842]
Now we have the following errors in both VM and analyzer:
```dart
  // List
  [
    for (var v1 in [1, 2, 3]) v1 // Ok
  ]
  // Set
  {
    for (var v2 in [1, 2, 3]) v2 // SYNTACTIC_ERROR.EXPECTED_TOKEN Expected to find ';'.
  };
  // Map
  {
    for (var v3 in [1, 2, 3]) "k$v3": v3 // SYNTACTIC_ERROR.EXPECTED_TOKEN Expected to find ';'.
  };
```
Am I missing anything? Why what works for `List` doesn't work for `Map` and `Set`?

CC @eernstg 

Tested on the edge SDK on Linux (March 24, 2023)

**Comment by lrhn** [comment]
This is working as intended.

Because a code block can also start with `{`, an expression statement must not start with the `{` of a map or set literal.

That makes it possible to known, seeing the first `{`, that it's a code block, and not having to parse arbitrarily far ahead to see if there is a `;`, or some other distinguishing syntax
