### ISSUE TITLE
Analyzer uses unpromoted static type for promoted variable when it is the target of a tear-off.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51853]
Tested in Dartpad.dev, master channel (Dart version 3.0.0-366.0.dev):
```dart
void main() {
  num x = 4;
  if (x is int) {
    x.expectStaticType<Exactly<int>>;
  }
}

extension StaticType<T> on T {
  void expectStaticType<X extends Exactly<T>>() {}
}

typedef Exactly<T> = T Function(T);
```
The analyzer gives the error:

> error
> line 4 • 'int Function(int)' doesn't conform to the bound 'num Function(num)' of the type parameter 'X'. [(view docs)](https://dart.dev/diagnostics/type_argument_not_matching_bounds)
> Try using a type that is or is a subclass of 'num Function(num)'.

This proves that the static type of `x`, as receiver type for the extension method `expectStaticType`, is `num`, and not promoted to `int` as it should be.
If changing the expectation to `<Exactly<num>>`, the analyzer error goes away.

If I change the line to:
```dart
    (x).expectStaticType<Exactly<int>>;
```
the error goes away!
Same if I change it to:
```dart
    x.expectStaticType<Exactly<int>>();
```
so the error is only in the instantiated tear-off analysis.

And it's not just extension methods. Same error occurs for:
```dart
void main() {
  C<num> c = C<int>() as dynamic;
  if (c is C<int>) {
    c.func<Exactly<int>>;
  }
}

class C<T> {
  void func<X extends Exactly<T>>() {}
}
```

Dart2js accepts the program, and complains if changing to `<Exactly<num>>`.

**Comment by bwilkerson** [comment]
@stereotype441 Am I remembering correctly that type promotion is now all done in shared code?

**Comment by stereotype441** [comment]
> @stereotype441 Am I remembering correctly that type promotion is now all done in shared code?

Yes, but it is critically dependent on analyzer-specific and CFE-specific logic driving the shared logic correctly.  I suspect that in the case of this particular bug it's an issue with how the analyzer is driving the shared logic, because:
- this bug only occurs in the analyzer, and
- it only occurs when doing tear-offs (which are implemented in the analyzer and CFE, rather than the shared logic)

Still, it's in an area I have a lot of familiarity with, so I'm happy to have a look.
