### ISSUE TITLE
analysis of the initialization of a local variable

### ISSUE THREAD

**Issue by 47b7b0** [dart-lang/sdk#51856]
The analysis of initialization of local variables does not take into account try-catch without a finally block. Also, conditions that will always work are not taken into account.

```dart
void main() {
  int x;

  // this condition is not taken into account when evaluating the initialization of x
  if (1 == 1) {
    x = 10;
  }

  try {
    // this initialization is not taken into account when evaluating the initialization of x
    x = 1;
  } catch (e) {}

  print(x); // static error

  int y;

  try {
    y = 2;
  } finally {}

  print(y); // no errors
}
```

**Comment by lrhn** [comment]
I think the behavior is intended and not incorrect.

A `catch` block means that an error inside the `try` block prior to the assignment could be caught, so you can exit the `try`/`catch` normally without initializing the variable.

A `finally` block *by itself* does not allow you to exit the `try`/`catch` normally if the body throws.

The means that either the `try` body threw, but then so does the `try`/`finally`, 
or the `try` body completed normally, and then so does the `try`/`finally`, but then the initialization was definitely performed.

The flow analysis does not try to predict which conditions are always true. It assumes that if there is a condition and branch in the code, it's probably because the author intended it to branch. Even if the flow analysis cannot see a way into a block, it will still assume there is one, and consider flow out of that block.
Also, it's not always clear which expressions are definitely true. An `a == a` expression *should* be true, but if it's user-written class, it might not. Or if it's `double` and the value is NaN.
