### ISSUE TITLE
[Patterns] Null-assert pattern is not exaustive in a switch statement

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#51878]
Accodrding to the https://github.com/dart-lang/language/pull/2948 

> - Null-assert pattern: A union of the lifted space union of the subpattern and a space with type Null.
> 
> _As with cast patterns, a null-assert pattern "matches" null by throwing an exception, which is sufficient for exhaustiveness._

According to the above a switch statement from `test1()` below should be exhastive and there sholud not be an arror

```dart
String test1(Object? o) { //  COMPILE_TIME_ERROR.BODY_MIGHT_COMPLETE_NORMALLY
                          // The body might complete normally, causing 'null' to be returned, but the return type, 'String', is a potentially non-nullable type.
  switch (o) {
    case Object _!:
      return "exhaustive";
  }
}

String test2(Object? o) => switch (o) { // Ok
      Object _! => "exhaustive"
    };

main() {
  print(test1(42));
  print(test2(42));
}
```
Testead on the edge SDK (March 28, 2023) on linux64

**Comment by johnniwinther** [comment]
The problem here isn't that the switch statement isn't exhaustive but that it doesn't need to be. As can be seen by `test2` where a switch expression is used, the switch is exhaustive. In `test1` the type of the switch scrutinee  `o` is not an ["always-exhaustive type"](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#exhaustiveness-and-reachability) so the flow analysis expects that the flow can continue through the switch, thus requiring an explicit return at the end of the method.
