### ISSUE TITLE
Missing documentation: '@Native' and 'external' (Question)

### ISSUE THREAD

**Issue by renlite** [dart-lang/sdk#51879]
For example https://github.com/flutter/engine/blob/6c2dafed50770fed72d12d740cce27673d9172a7/lib/ui/painting.dart uses a lot of interoperability with C/C++ Flutter engine (Impeller). I didn't find any documentation for the annotation and key word:

```Dart
  @Native<Int32 Function(Pointer<Void>)>(symbol: 'Canvas::getSaveCount', isLeaf: true)
  external int getSaveCount();

  @Native<Void Function(Pointer<Void>, Double, Double)>(symbol: 'Canvas::translate', isLeaf: true)
  external void translate(double dx, double dy);
````

This seems not to be the current ffi interop. (https://dart.dev/guides/libraries/c-interop) Compared to FFI the code above is more compact and clearer.

What I found: https://github.com/dart-lang/sdk/issues/45451

Could you please link to a documentation or inform about the usage.

**Comment by lrhn** [comment]
The `external` marker is something you can apply to a Dart function/getter/setter/constructor, similar to `abstract` in that it allows the declaration to not have a body. Unlike `abstract` the method can still be called, so the *compiler* has to provide an implementation for it.
So it's basically a way to say "compiler-supplied method body". How to attach a body to an `external` method depends on the compiler.

The annotation appears to be a `dart:ffi` feature, [declared here](https://github.com/dart-lang/sdk/blob/main/sdk/lib/ffi/ffi.dart#L971), but it was released in the most recent version of the Dart SDK, so the guides may not be describing it yet.

**Comment by renlite** [comment]
Thanks for the information.
So the compiler needs in addition to the `external` marker the `@Native` annotation to know where/how to find the implementation (body) of C/C++/Objc (external) code. Is  the `@Native` annotation an optional syntax for `ffi.lookupFunction`?

Would it be possible to replace the following binding?
```Dart
int closesocket(int s) => _closesocket(s);
final _closesocket = _ws2_32.lookupFunction<Int32 Function(IntPtr s), int Function(int s)>(
        'closesocket');

// replaced by
// (symbol: 'closesocket') = Default from external func name='closesocket'
@Native<Int32 Function(IntPtr s)>( )
external int closesocket(int s);
```

**Comment by lrhn** [comment]
I can't actually find `Native` in the new docs, so maybe it's called `FfiNative` (https://api.dart.dev/stable/2.19.6/dart-ffi/FfiNative-class.html).

Overall, let's ask someone who actually knows `dart:ffi`. @dcharkes?

**Comment by dcharkes** [comment]
That new syntax is in 3.0, not 2.19. The 3.0 beta documentation is here: https://api.dart.dev/beta/3.0.0-290.3.beta/dart-ffi/Native-class.html

**Comment by dcharkes** [comment]
> This seems not to be the current ffi interop. (https://dart.dev/guides/libraries/c-interop) Compared to FFI the code above is more compact and clearer.

Yes, this is the new shiny future. :)

The resolution from "native" to dynamic library is done in three ways.

1. Providing a mapping from asset-id to dynamic library. This is the intended use. However, this hasn't shipped yet. Please follow the following bug for updates.
    * https://github.com/dart-lang/sdk/issues/50565
2. Setting a resolver with `Dart_SetNativeResolver` from `dart_api.h`. This is only available in Dart, not in Flutter. Flutter doesn't export the `dart_api.h` symbols. This is how the Flutter code that you linked to uses `@Native`.
3. Lookup in the process. If the above two lookup methods fail, the symbol is resolved in the current process. Note that `DynamicLibrary.open()` does _not_ load symbols into the process because the `RLTD_GLOBAL` flag isn't passed. If you want to use this approach, take a look at https://github.com/dart-lang/sdk/blob/main/tests/ffi/dylib_utils.dart#L49

For now, I suggest using `DynamicLibrary` and `lookupFunction`, until we have landed https://github.com/dart-lang/sdk/issues/50565.

**Comment by renlite** [comment]
Thanks @dcharkes and @lrhn for your answers.
This issue can be closed.

**Comment by renlite** [comment]
Questions answered.
