### ISSUE TITLE
[Patterns] different errors in case of non-exhaustive switch

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#51877]
The following code produce different errors
```dart
int test1(Object obj) { // COMPILE_TIME_ERROR.BODY_MIGHT_COMPLETE_NORMALLY
                        // The body might complete normally, causing 'null' to be returned, but the return type, 'int', is a potentially non-nullable type.
  switch (obj) {
    case int(isEven: true) as int:
      return 1;
    case int _:
      return 2;
  }
}

int test2(Object obj) => switch (obj) { // COMPILE_TIME_ERROR.NON_EXHAUSTIVE_SWITCH
                                        // The type 'Object' is not exhaustively matched by the switch cases.
  int(isEven: true) as int => 1,
  int _ => 2
};

String test3(bool b) {
  switch (b) {  // COMPILE_TIME_ERROR.NON_EXHAUSTIVE_SWITCH
                // The type 'bool' is not exhaustively matched by the switch cases.
    case true:
      return "true";
    case false when b == false:
      return "false";
  }
}

main() {
  test1(1);
  test2(2);
  test3(true);
}
```
Why in the first case we have an error that differs from cases 2 and 3?

Tested on the Edge SDK on Linux (March 28, 2023)

**Comment by eernstg** [comment]
I think the error in `test1` is OK, cf. [this in-depth explanation](https://github.com/dart-lang/language/issues/2801#issuecomment-1419397350) and [this issue summary](https://github.com/dart-lang/language/issues/2801#issuecomment-1420985883):

The static type of `obj` is `Object` at the beginning of the switch statement. The fact that `as int` did not throw promotes the matched value type to `int` _in that case_, but not in subsequent cases. So `obj` may still be a `String` or something else according to the exhaustiveness analysis when we consider `case int _:`, and the switch statement will then complete normally, and so will the function body. It is not an error for the switch statement to complete, but it is an error for the function body to return null, which is the semantics of reaching the end of the body.

In `test2` and `test3` it is an error for the switch to be non-exhaustive, because it is a switch expression.
