### ISSUE TITLE
Analyzer reports no warnings when a new-class-modifier'd class is private

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#51889]
Today I see no warnings ([in DartPad master branch](https://dartpad.dev/?channel=master)) when a private class is modified to be `sealed`, `base`, `interface`, `final`, or `mixin`. Such modifiers are unnecessary on a private class, provide no value, and may indicate a misunderstanding of the language feature.

Reporting a warning for such code can point out a misunderstanding, and can reduce confusion, by preventing the confusion of a developer coming across such code.

---

There is one exception that I can see to all of my logic above: a private class being "exported" by a public typedef. For example, this code is legal today:

```dart
// a.dart:
class _C {}
typedef T = _C;

// b.dart:
import 'a.dart';
class D extends T {}
void main() => print(D());
```

(It's interesting that `D.new` is allowed to (implicitly) call the default constructor of `_C`, a private class in another library...)

In this code, any of the modifiers on `_C` _would_ have an effect on how/whether classes in `b.dart` can subtype `_C`. I don't think such typedefs are common (what value does the typedef provide over just renaming the class to be public?), but we could also detect them in deciding whether to report an "unnecessary" modifier.

CC @bwilkerson @kallentu @leafpetersen @lrhn @munificent

**Comment by leafpetersen** [comment]
Using `sealed` on a private class is 100% valid and useful.  There's no reason I might not want to have a private non-exported sealed family (I have used many abstract data types in other languages that weren't part of the API).

Using `mixin` is also definitely useful - it's the only way to port a legacy class that is used as a mixin internally.

I think `base` could be necessary, if not useful.  If you have a private class extending a public `base` class, you will be required to mark it as `base`.

I don't have strong feelings about `final` or `interface`.  You could certainly choose to mark your private classes that way as documentation (and if you're using the `@reopen` lint, you might get nagged to.

**Comment by srawlins** [comment]
Sounds like for documentation purposes, any of these could provide value. We don't have to implement this.

> Using sealed on a private class is 100% valid and useful. There's no reason I might not want to have a private non-exported sealed family (I have used many abstract data types in other languages that weren't part of the API).

I'm a little confused on this. Doesn't any abstract private class declare a sealed family? Or no, because of my typedef case?

**Comment by lrhn** [comment]
A modifier on a private class is not necessarily unnecessary.

A `sealed` modifier can be important if you want to switch over the subclasses locally. Possibly the class can be a sealed subclass of a public sealed class, used to share code between other public subclasses, while preserving exhaustiveness.

If the class has a (public or not) `base` or `final` superclass, it *must* be marked `base`, `final` or `sealed`.

Then there is the "re-export through type alias" use-case. It's not obvious people will do that, but we'd have to detect whether they do before giving warnings.

Some people might *want* to add `abstract interface` to their internal-only interface classes, for documentation purposes. Or `base` or `final` for that matter.

Since adding the modifiers is also completely safe (it has no effect, but can express intent), and detecting whether they really are useless is non-trivial, there has been no urge to prevent it.

**Comment by eernstg** [comment]
It looks like nobody mentioned non-private subtypes so far (except possibly with `sealed`). But it is just as leaky as `typedef`:

```dart
// a.dart:
base class _C {}
base class C1 implements _C {}
...
base class Ck implements _C {}
```

You could say that we could just remove `base` from `_C` (because `_C` doesn't have any `base` superinterfaces).

However, if the intention is that all of `C1 .. Ck` should be `base` (for whatever reason), it seems reasonable that we can express this intention in `_C`, thus enforcing it in `C1 .. Ck` rather than just hoping that we don't forget any of them.

For example, if we wish to ensure that certain private members inherited from `_C` will be available on every instance of type `Cj` for all `j` then it seems safer and more direct to specify the associated modifier on `_C`, as opposed to specifying it on each of `C1 .. Ck`.

I believe this shows that those modifiers _do_ have an effect in some cases.

**Comment by srawlins** [comment]
This is all very cool. Thanks for the explanations. Nothing to report here :)

**Comment by leafpetersen** [comment]
What everyone else said, but just to be clear:

> I'm a little confused on this. Doesn't any abstract private class declare a sealed family? Or no, because of my typedef case?

The only way to get exhaustiveness for switches over a type (other than for a small set of primitive types) is by declaring the type as a `sealed` class.
