### ISSUE TITLE
report unreachable cases

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#51893]
When switching (or if-casing) on a type who's subclasses are known, we can determine statically that some cases are unreachable.

For example:

```dart
if ('foo' case []) print('never');
if (1 case Map()) print('nope');
```

Chatting with @stereotype441 this doesn't seem like the province of flow analysis.

Any reason not to put such a diagnostic in the analyzer?

/cc @munificent @bwilkerson @lrhn @eernstg @leafpetersen

**Comment by stereotype441** [comment]
Related: even if the type's subclasses aren't known, we may still want to issue a lint (or hint) since it's very likely that the user made a mistake, e.g.:

```dart
class C {}
f(C c) {
  switch (c) {
    ...
    case []:
      print('oops');
  }
}
```
Technically speaking it's *possible* that somewhere in their program there's a class that's a subtype of both `C` and `List`, so maybe a user who writes code like this is being super clever.  But I think it's far more likely that they just made a mistake, and it would be nice for a lint or something to help steer them onto a better track.  But flagging the code as unreachable seems wrong because technically the code is reachable, it's just not very likely to be reached.

So maybe rather than flag the code as unreachable, we should do something like:
- Have a lint that fires if a list pattern's matched value type isn't a supertype of `List<Never>`
- Have a lint that fires if a map pattern's matched value type isn't a supertype of `Map<Never, Never>`

These lints would catch the `if ('foo' case [])` example above.

I suspect these two lints would cover a lot of the possibilities that could trip a user up, without too many false positives.

We could also consider generalizing to:
- Have a lint that fires if a pattern's matched value type is neither a subtype nor a supertype of its required type

This would catch the `if (1 case Map())` example, but I worry it might have a lot more false positives.

**Comment by lrhn** [comment]
There are a few cases where it's possible to know that there can be no subclass/instance implementing both of two interfaces:
* One is an enum (and not already a subtype of the other).
* One is a core platform type that we know everything about.
* They implement/are different instantiations of the same generic interface.

Other than that, it's a matter of tracking whether some class, somewhere, can possibly implement both. Probably checking every conditional import or augmentation file too, before saying that the code is *definitely* wrong.

Not something we'd want to formally specify, but giving a good heuristic warning seems like a job for the analyzer, as a warning or lint depending on the false-positive risk. (The lint could be related to the "unrelated_type_..." lints.)

**Comment by bwilkerson** [comment]
If we think there will be few false positives, then it's fine to have a lint for the cases where the pattern is unlikely to match.

But in the cases where the pattern is known to not be able to match I think we should have a warning. If we do have a warning, I have to ask how much value the lint would have.

**Comment by scheglov** [comment]
I can understand `final`, but `base` can be implemented anywhere, adding any (non-conflicting) interfaces.
Similarly for `sealed`, you still can extend its subclasses, and we don't know all of them (in contrast to `final`).

But we could do this:
```dart
    await assertErrorsInCode('''
void f(A x) {
  if (x case R _) {}
}

final class A {}
final class A2 extends A {}
final class A3 implements A {}
class R {}
''', [
      error(WarningCode.PATTERN_NEVER_MATCHES_VALUE_TYPE, 27, 3),
    ]);
```

**Comment by scheglov** [comment]
> They implement/are different instantiations of the same generic interface.

It might be more nuanced than that.

In this example both are instances of the same interface, with different type arguments.
But it matches.
```dart
void f(A<num> x) {
  if (x case A<int> _) {
    print('matches');
  } else {
    print('not matches');
  }
}

class A<T> {}

main() {
  f(A<int>());
}
```

OTOH, if the matched type implements `A` with different type arguments, then we can never match.
```dart
void f(B x) {
  if (x case A<int> _) {
    print('matches');
  } else {
    print('not matches');
  }
}

class A<T> {}

class B extends A<num> {}

main() {
  f(B());
}
```

However "different" is probably better to replace with "that never could be the same", because here `T` is different than `int`, but it could be `int`.
```dart
void f<T>(B<T> x) {
  if (x case A<int> _) {
    print('matches');
  } else {
    print('not matches');
  }
}

class A<T> {}

class B<T> extends A<T> {}

main() {
  f(B<int>());
}
```

**Comment by munificent** [comment]
> I can understand `final`, but `base` can be implemented anywhere, adding any (non-conflicting) interfaces.
> Similarly for `sealed`, you still can extend its subclasses, and we don't know all of them (in contrast to `final`).

Ah, you're right, of course.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/292420
