### ISSUE TITLE
Incomplete error reporting for function expressions in guards

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51905]
The patterns proposal says it's an error to have a bare (i.e. not enclosed in some kind of brackets) function expression in a guard clause. It specifically says this error applies to all combinations:

1. Function expressions with `=>` bodies.
2. Function expressions with `{}` bodies.
3. Guards in switch expressions.
4. Guards in switch statements.
5. Guards in if-case statements.
6. Guards in if-case elements.

It appears that the parser implementation currently only reports an error for (a) function expressions with `=>` bodies inside switch expressions, and (b) function expressions with `{}` bodies inside switch expressions. (a) is the place where the actual ambiguity occurs, so that's good. But the implementation is still out of sync with the spec for guards in other contexts.

I think we probably should stick with the current spec for `{}` bodies because that same restriction applies to constructor initializers and we definitely want to prohibit `{}`-bodied function expressions there.

I'm agnostic as to whether we should keep the spec about disallowing bare function expressions in switch statements and if-case, or whether we should tweak the spec to follow the implementation. I could go either way, and I'm happy to defer to @stereotype441 based on the implementation effort.

**Comment by eernstg** [comment]
I'd recommend that we use a narrow scope and only report the situations where it is actually needed (and perhaps a few others, if this has already been implemented and is inconvenient to remove again).

The situation where the error is justified is when an `=>` function literal occurs in a guard of a switch expression. All the other cases would be included for some other reason, e.g., consistency.

However, there is no particular need for consistency. Nobody will think "Oh dear, I wish I could have that error here!" when they're writing one of those other cases. They only need to know about this rule when they get the error, so they won't need to remember anything, they'll just add those parentheses and go on with their life.

A construct like `case p when () {.../*I need a whole function body here*/...} (): ...` might even be useful. ;-)

**Comment by stereotype441** [comment]
> I'd recommend that we use a narrow scope and only report the situations where it is actually needed (and perhaps a few others, if this has already been implemented and is inconvenient to remove again).

I'm on board with this.

> A construct like `case p when () {.../*I need a whole function body here*/...} (): ...` might even be useful. ;-)

Yeah, I'm sad that this isn't supported right now.  But supporting it would require a non-trivial amount of parser re-work:
- We would have to replace the parser's `mayParseFunctionExpressions` with something that can track three possible states (allow all function expressions, allow only block-bodied function expressions, allow no function expressions); this involves touching a lot of code that's not related to patterns, so it carries risk of breaking pre-existing functionality.
- Some of the parser's disambiguation rules decide whether they are looking at a function expression or not without looking ahead to find the `=>` or `{` token.  For example, in `var x = () async { ... }`, the parser knows it's looking at a function expression as soon as it hits the `async` keyword.  These rules would have to be re-worked to distinguish between the two types of function expressions.

Given that the beta cut is less than a week away, I think we should stick with what's currently implemented: function expressions are prohibited inside the guards of switch expressions.

**Comment by Khushipatil13** [comment]
The issue with incomplete error reporting for function expressions in guards can be addressed by modifying the parser to more accurately identify the source of errors in such expressions. Specifically, the parser can be updated to more precisely pinpoint the location of errors within the function expression, rather than simply reporting an error at the point where the function expression appears in the guard.

To achieve this, the parser can be updated to more thoroughly analyze the structure of function expressions and their components, such as parameter lists, return types, and body expressions. By doing so, the parser can identify the specific location of errors within a function expression and report those errors with greater accuracy.

Additionally, the parser can be enhanced with better error recovery mechanisms, such as backtracking or lookahead parsing, to more effectively handle errors and prevent them from causing subsequent parsing errors or issues.

Overall, by improving error reporting and recovery for function expressions in guards, developers can more easily identify and fix issues in their code, leading to more efficient and effective development.
