### ISSUE TITLE
FileSystemEvent should be `sealed`

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#51912]
This will allow developers to exhaustively pattern match on the `Stream` returned by [`FileSystemEntity.watch`](https://api.flutter.dev/flutter/dart-io/FileSystemEntity/watch.html).

Unfortunately, none of the [`FileSystemEvent`](https://api.flutter.dev/flutter/dart-io/FileSystemEvent-class.html) subclasses have public constructors so at least one package, [`package:watcher` created it's own implementation](https://github.com/dart-lang/watcher/blob/master/lib/src/constructable_file_system_event.dart)  to work around that.

So I think that we can solve this in 3 steps:

- [x] Make the `FileSystemEvent` subclasses `final` and provide public constructors.
- [x] Modify `package:watcher` (and possibly others) to use the public constructors instead of custom subclasses.
- [x] Make `FileSystemEvent` sealed

**Comment by faizan003** [comment]
The suggestion to make the FileSystemEvent subclasses final and provide public constructors, then modify the affected packages to use the public constructors instead of custom subclasses, is a good step towards a better API design.

However, making the FileSystemEvent class sealed might not be necessary or beneficial. Sealing a class means that all its subclasses must be declared in the same file as the sealed class, which can limit extensibility and make the API more difficult to maintain. Instead, you can consider making the constructors of the FileSystemEvent subclasses public, final, and immutable.

This would allow developers to create instances of these subclasses and exhaustively pattern match on them. Additionally, you could document the fact that these subclasses are not meant to be extended, and that any further event types should be implemented as separate classes.

Overall, this approach would provide a more flexible and extensible API, while still allowing for exhaustively pattern matching on the event types.

**Comment by lrhn** [comment]
Making `FileSystemEvent` sealed is breaking, now and in the future, but making it `final` today is non-breaking because there is no 3.0 code out there yet. So we should make `FileSystemEvent` itself `final` now, not just its subclasses. 
That won't break `watcher` until it upgrades to 3.0, and there should be time enough to fix it before that. 
And provide the public constructors now too, so people have a place to go when migrating.

(The alternative is to seal the `FileSystemEvent` class itself, but keep the subclasses implementable. Not sure there is any long-term benefit to that, but it's a possibility. But that still breaks `watcher` because it actually does `implement FileSystemEvent` on its abstract superclass, even if it doesn't need to.)

**Comment by brianquinlan** [comment]
I made `FileSystemEvent` and its subclasses `final`.
