### ISSUE TITLE
[Patterns] Switch statement with exhaustive list pattern is not recognised as exhaustive

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#51926]
The following code produces an error in both CFE and analyzer

```dart
String test1(List<bool> l) { // Error: A non-null value must be returned since the return type 'String' doesn't allow null
  switch (l) {
    case <bool>[]:
    case <bool>[_]:
    case <bool>[_, _]:
    case <bool>[_, _, ...]:
      return "ok";
  }
}

String test2(List<bool> l) => // Ok, no error
  switch (l) {
    <bool>[] => "0",
    <bool>[_] => "1",
    <bool>[_, _] => "2",
    <bool>[_, _, ...] => "2+"
  };

main() {
  print(test1([true, false]));
  print(test2([true, false]));
}
```

Tested on the Edge SDK (April 3, 2023) on Linux x64

**Comment by srawlins** [comment]
CC @johnniwinther @stereotype441

**Comment by johnniwinther** [comment]
The problem is that `List<bool>` is not an _always-exhaustive_ type so the flow analysis of the switch statement in `test1` does not consider it exhaustive.

**Comment by stereotype441** [comment]
> The problem is that `List<bool>` is not an _always-exhaustive_ type so the flow analysis of the switch statement in `test1` does not consider it exhaustive.

Yeah, this is working as intended.  The reason for this design choice is that the check for whether `test1` properly returns a value happents during flow analysis, which is before the compiler/analyzer has all the information necessary to run the exhaustiveness checker.  So what we do is, if the type of the switch scrutinee is an "always exhaustive" type, flow analysis assumes that the switch is exhaustive, and leaves a note for the exhaustiveness checker to let it know that if that assumption is wrong, it should issue an error (to ensure soundness).  Whereas if the type of the switch scrutinee is not an "always exhaustive" type, flow analysis assumes that the switch is not exhaustive; if it later turns out to be exhaustive, then that's unfortunate, but it's not unsound, so we just let the error from flow analysis stand.

The practical upshot of this is that for a switch *statement*, if the type of the scrutinee is not an "always exhaustive" type, then you may sometimes need add an extra `default` case that isn't actually reachable, e.g.:
```dart
String test1(List<bool> l) {
  switch (l) {
    case <bool>[]:
    case <bool>[_]:
    case <bool>[_, _]:
    case <bool>[_, _, ...]:
      return "ok";
    default:
      throw 'unreachable';
  }
}
```
It's an unfortunate situation but we are kind of hemmed in by other design choices.

CC @munificent who may have more to say about why we chose this particular set of trade-offs.

**Comment by munificent** [comment]
I think @stereotype441 said it all. In a perfect world, type promotion would use whether or not a switch statement is *actually* exhaustive to determine a variable's promoted type, but due to how the analyses are phased, that information isn't available yet.
