### ISSUE TITLE
List type parameter subtype error at runtime going undetected by compiler

### ISSUE THREAD

**Issue by YouRik** [dart-lang/sdk#51921]
I found a weird typing situation while working with lists and subtypes that I know how to get around but still feel it should be addressed as it was unexpected to me.

**Code example** https://dartpad.dev/?id=d9f1eda654c95b6a00d8d4470532886a
```Dart
class Bar {
  final bool barish;
  const Bar(this.barish);
}

class Foo extends Bar {
  final bool foolish;
  const Foo(this.foolish, super.barish);
}

void main() {
  final numbers = [1, 2, 3, 4];
  final List<Bar> bars = numbers.map((number) => Foo(number.isNegative, number.isEven))
    .toList();
  bars.insert(0, Bar(false));

  for (var bar in bars) {
    print('$bar is barish: ${bar.barish}');
  }
}
```
In line 15, we add an object of type `Bar` to a `List<Bar>` which should work.  
The linter, compiler, and my naked eye see no problem with it but as it turns out, at runtime, `bars` is actually a `List<Foo>`, even though it was explicitly stated in line 13 to be `List<Bar>`.

Changing line 13 to cast the `Foo` to a `Bar` fixes the issue, however it shows an 'Unnecessary cast' warning which is not true, as it apparently is necessary.
```Dart
  final List<Bar> bars = numbers.map((number) => Foo(number.isNegative, number.isEven) as Bar)
```
The actual fix without false warnings would be to change the line to:
```Dart
  final List<Bar> bars = numbers.map<Bar>((number) => Foo(number.isNegative, number.isEven))
```
However I would expect the change before to show no warning and actually would've expected the initial code to work, or get a linter / compiler error.

I would like to make an additional note that the mismatching type is detected when replacing lines 13-15 with:
```Dart
  final List<Bar> bars = numbers.map((number) => Foo(number.isNegative, number.isEven))
      .toList()..insert(0, Bar(false));
 ```

**Observed on:**
- macOS Dart SDK version with 2.19.6 (stable)
- DartPad in Firefox

Seems related to:
https://github.com/dart-lang/language/issues/222

**Comment by lrhn** [comment]
Dart generics are unsafely covariant, which means you can get runtime errors from code with no static errors.
```dart
List<int> il = [1, 2, 3];
List<num> nl = il; // Valid upcast, but unsafe.
nl.add(1.5); // Valid by static type, throws at runtime.
```
This is a known property of Dart generics, and is working as intended here.

It would be *nice* if we could infer `<Bar>` on the `map` call here
```dart
final List<Bar> bars = numbers.map((number) => Foo(number.isNegative, number.isEven))
    .toList();
```
But we can't, because of the `.toList()`, which puts `numbers.map(...)` into a receiver position, and we never propagate a context type into receiver positions. (Mainly because Dart type inference is one-pass, and we need to infer the type of `numbers.map(...)` before we can know what `.toList()` is, and how it relates to the context type. At that point, we don't go back and try again knowing that `toList()` should return a `List<Bar>`.

So, all in all this is working as intended, within the limits of type inference.

My recommended rewrite is:
```dart
final List<Bar> bars = [for (var n in numbers) Foo(n.isNegative, n.isEven)];
```
Second alternative would be:
```dart
final bars = numbers.map<Bar>((number) => Foo(number.isNegative, number.isEven))
    .toList();
```

**Comment by YouRik** [comment]
Thank you for the explanation and context!
Then it seems this is just something one has to stay aware of.
