### ISSUE TITLE
CFE missing errors when using a local pattern variable as a constant

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#51971]
The test language/patterns/pattern_variable_constant_scope_test is failing on the CFE with missing errors.  An example of where an error is missing is the following code:

```dart
  const a = 'outer';
  const b = 'outer';

  return switch (x) {
    var a && == a => 'error',
    //          ^
    // [analyzer] unspecified
    // [cfe] unspecified
  ```

which expects that using `== a` should be an error since the `a` referenced there should point back to the `var a` rather than the `const a`.

cc @munificent @johnniwinther 

Marking this as Dart 3 stable so that we consider it for cherry picking if needed (I'm somewhat inclined against).

**Comment by eernstg** [comment]
Are we quite sure that we want to add the pattern variables to the current scope in the pattern itself? We do have a different approach with names introduced in a formal parameter declaration list:

```dart
int f (int i, int int) {
  return i + int;
}
```

No errors here, because there is no new scope which is the current scope for the formal parameter list itself, we're just gathering new variables as we analyse the formal parameter list, and they are added into the parameter list scope, which is the enclosing scope for the body scope of the function.

So there's no error if we're looking up something in the enclosing scopes in the formal parameter list itself, even in the case where that parameter list introduces a new variable with the same name.

**Comment by chloestefantsova** [comment]
> we're just gathering new variables as we analyse the formal parameter list

This is similar to the current implementation of variable declarations in patterns in the CFE: we gather information about the variables and their initializers from the pattern and then we declare the pattern variables, all at the same time in a new scope.

**Comment by leafpetersen** [comment]
This is currently inconsistent behavior between the CFE and analyzer.  Once the CFE is consistent with the analyzer, we can discuss whether this warrants a cherry pick or whether we should just ship the fix in 3.1 (given that the analyzer currently makes this an error, it should be a reasonable change).

**Comment by vsmenon** [comment]
Any update here?

**Comment by munificent** [comment]
> We do have a different approach with names introduced in a formal parameter declaration list:
> 
> ```
> int f (int i, int int) {
>   return i + int;
> }
> ```
> 
> No errors here, because there is no new scope which is the current scope for the formal parameter list itself, we're just gathering new variables as we analyse the formal parameter list, and they are added into the parameter list scope, which is the enclosing scope for the body scope of the function.

1. That is super weird and I can't see any practical use for it.
2. Since pattern variables are always declared as locals in the context of surrounding imperative think a better analogy is to local variable declarations:

```dart
f() {
  int i = 0;
  int int = 2;
  print('$i $int');
}
```

This program does generate an error:

```dart
temp.dart:3:7: Error: Can't declare 'int' because it was already used in this scope.
  int int = 2;
      ^^^
```

I think I'm OK with the currently specified scoping behavior for patterns. I think it's more useful to make the scoping "aggressive" in that we give a pattern variable as wide a scope as possible and then report errors from collisions. That minimizes the amount of times that shadowing can occur. While shadowing top-level declarations is practically useful to ensure that adding a new top-level name doesn't break existing code, I think most other uses of shadowing are just confusing and should be discouraged.

**Comment by eernstg** [comment]
@vsmenon wrote:
> Any update here?

The feature specification [says](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=Each%20guardedPattern%20introduces%20a%20new%20case%20scope) that pattern variables in a switch/if-case statement/element are introduced into the corresponding case scope, and there is [a remark plus an example](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=However%2C%20all%20pattern%20variables%20are%20in%20scope%20in%20the%20entire%20pattern) to the effect that said case scope is the current scope for the entire pattern.

So the current status is that the CFE needs to be adjusted such that the scoping is handled in this manner. I added the 'type-bug' label to indicate that the remaining work here is to perform that change.

**Comment by eernstg** [comment]
@munificent wrote:
> That is super weird

Certainly! :smile:

I just mentioned it in order to have that piece of prior art on the table when we're discussing these scope rules. I think it makes sense in general to try to handle new situations in the same way as existing situations that are similar.

But we might actually want to reverse the direction of the design forces in this case, and change the rules about the scoping of formal parameters. In particular, if we _do_ include the formal parameters in the current scope of the parameter declaration list itself then we can use parameters in a (hypothetical, generalized kind of) default values:

```dart
void foo([int i = 0, int j = i + 1]) {...}
```

It would be a breaking change, in principle, but I doubt that any code which is an error after that change is worth fighting for: Just stop using a parameter name which is also a type that is used somewhere else in this parameter list!

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/296581.

**Comment by munificent** [comment]
> But we might actually want to reverse the direction of the design forces in this case, and change the rules about the scoping of formal parameters.

That's tangential to this issue, but, yes, I would be 100% in favor of this. I actually didn't know until this issue that parameters were not in scope in their own parameter list.
