### ISSUE TITLE
Question about "vm:prefer-inline"

### ISSUE THREAD

**Issue by antonbashir** [dart-lang/sdk#51977]
Hello! 

I want ask about pragma "vm:prefer-inline". 
I have three questions. 

First: What conditions and requirements for method to be inlined ? For example count of lines or something else
Second:  Could this pragma be useful for public methods which called from other classes and using private fields like in the example below ? 
``` 
@pragma(preferInlinePragma)
  void removeClient(int fd) => _serversByClients.remove(fd);
```
Last: Inlining is possible in JIT and AOT modes or only JIT ?

**Comment by alexmarkov** [comment]
> What conditions and requirements for method to be inlined ?

First, compiler needs to figure out that a particular call in the caller leads to a particular callee. For static methods and constructors this is always the case. For instance methods it depends on the class hierarchy, whether the method is overridden and whether compiler can determine (or speculate on) the actual type of the receiver. Method is less likely to be inlined if call site is polymorphic (can call multiple different methods).

After figuring out the target of the call, compiler uses a very complex heuristic to decide whether to inline a method or not. The heuristic is based on the size of the caller and the callee, number of call sites in the callee, loop nesting in the caller etc. `@pragma("vm:prefer-inline")` on the callee bypasses those heuristics and tells compiler to inline annotated method if it is possible.

Currently compiler cannot inline certain methods, even if they are annotated with `@pragma("vm:prefer-inline")`. Those include methods with a `try` block, methods declared `async`, `async*`, `sync*` and certain core library methods.

> Could this pragma be useful for public methods which called from other classes and using private fields like in the example below ?

Absolutely. However, unless the method is critical for performance and you can measure that inlining of this method improves performance, consider relying on the compiler heuristic. Excessive inlining causes larger code size, and in certain cases inlining may regress performance instead of improving it.

> Inlining is possible in JIT and AOT modes or only JIT ?

Both JIT and AOT compilers do the method inlining. However, the heuristic for choosing whether to inline is slightly different and based on different information. JIT can inline speculatively, based on the collected feedback from executing program. AOT compiler uses whole-program analysis to determine possible call targets which can be inlined. Both JIT and AOT respect `@pragma("vm:prefer-inline")` annotation.

**Comment by incendial** [comment]
> Currently compiler cannot inline certain methods, even if they are annotated with @pragma("vm:prefer-inline"). Those include methods with a try block, methods declared async, async*, sync* and certain core library methods.

@alexmarkov hey, I'd like to add a lint rule to highlight usages of `@pragma("vm:prefer-inline")` that compiler can't inline. Could you please tell, is this a complete list of cases or are there any more? Also, if a function doesn't have the async keyword but still returns a `Future`, will the compiler be able to inline it?

**Comment by incendial** [comment]
@alexmarkov thanks for the heads up, but it looks like a useful hint to people trying to use pragmas and as you mentioned this is the internal behavior that is rather implicit and people might be not aware that their actions (setting the annotation) actually make zero impact. 

Can you share how often do you change this part of the compiler? Or maybe there are some upcoming changes?
