### ISSUE TITLE
[Patterns] Custom implementation of the List cannot be exhaustive?

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#51973]
I'm not sure if this is an issue or not, but the custom implementation of `List` is never exhaustive. Is this expected?

```dart
import "dart:collection";

class MyList<T> extends ListBase<T> {
  List<T> _inner = [];

  MyList(this._inner);

  @override
  int get length {
    return  _inner.length;
  }

  @override
  void set length(int newLength) {
    _inner.length = newLength;
  }

  @override
  T operator [](int index) {
    return _inner[index];
  }

  @override
  void operator []=(int index, T value) {
    _inner[index] = value;
  }
}

String test1(List<int> l) =>
  switch (l) { // Ok. No error, exhaustive
    [] => "0",
    [_] => "1",
    [_, _] => "2",
    [_, _, ...] => "2+"
  };

String test2(MyList<int> ml) =>
  switch (ml) { //  COMPILE_TIME_ERROR.NON_EXHAUSTIVE_SWITCH_EXPRESSION
                //  The type 'MyList<int>' is not exhaustively matched by the switch cases since it doesn't match 'MyList<int>()'.
    [] => "0",
    [_] => "1",
    [_, _] => "2",
    [_, _, ...] => "2+"
  };

main() {
  test1(MyList([]));
  test2(MyList([]));
}

```

cc @johnniwinther @munificent 
Tested on the edge SDK (April 6, 2023)

**Comment by munificent** [comment]
I do intend for list patterns to work with user-defined subtypes of `List`. As far as I can tell, there's nothing in the patterns spec or exhaustiveness spec that would cause this to not be allowed, so I think it's just a missing feature in the implementation. (Which isn't too surprising since @johnniwinther was flying blind without a spec at all the entire time. Sorry!)

Interestingly, the implementation *does* understand that this is exhaustive:

```dart
String test2(MyList<int> ml) =>
  switch (ml) {
    [...] => "any",
  };
```

So something to do with a list pattern having non-rest patterns seems to confuse it when the matched value type is a subtype of `List`.

**Comment by johnniwinther** [comment]
This is an error of the implementation. I'll look into it.
