### ISSUE TITLE
Analyzer suggests break as the first suggested completion in a switch.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#51980]
I noticed in while working with the new pattern switches that if I'm editing a switch, and I type `case something:` then a completion dialog pops up, and the first (default) suggested completion is `break` (this in VSCode, using relatively recent bleeding edge Dart).  This is probably no longer ever what the user wants.  Not sure what the right default suggestion is, but probably not break?

**Comment by bwilkerson** [comment]
Interesting.

The analysis server sends a suggested order back to the client, but the client can (and often does) ignore those suggestions if the client believes that it knows better. We can look to see whether server is suggesting that `break` be first, but changing that won't necessarily change the order in the client. We don't have complete control in that area.

If that doesn't work, we could potentially remove `break` from the list of suggestions, but I'm hesitant to do that. Our general approach thus far has been to suggest anything that's valid, and I still think that's the right approach. While `break` might not often be what's wanted, it's still valid.

**Comment by leafpetersen** [comment]
Worth mentioning that the experience here was especially bad (for me) since I kept repeatedly typing `case foo:` followed by hitting return to go to the next line, which instead got interpreted as "insert a break statement" which I then had to delete.    I guess the expected model is maybe that I should learn not to manually break lines and instead rely on the formatter to fix things up, but the muscle memory is definitely hard to get rid of.

**Comment by leafpetersen** [comment]
Also, none of the suggestions except maybe "return" are really all that relevant here.  Is the `:` really the right place to be offering a completion?

<img width="649" alt="Screenshot 2023-04-07 at 1 58 27 PM" src="https://user-images.githubusercontent.com/8484504/230678391-62f10811-1a80-4c9f-a785-d01666c190f7.png">

**Comment by bwilkerson** [comment]
> I guess the expected model is maybe that I should learn not to manually break lines ...

I don't think that's a reasonable expectation. Users should be allowed to type however they want.

> Is the : really the right place to be offering a completion?

I don't know why the colon was added as a completion trigger. @DanTup might remember. Also, there might be a preference setting for that (I haven't looked).

**Comment by leafpetersen** [comment]
> I don't know why the colon was added as a completion trigger.

I wonder if it's connected to #51961 ?

**Comment by DanTup** [comment]
I think the reason for `:` as a trigger character was for things like:

- typing `package:` in an `import`
- typing `:` after an argument name

There was a comment about treating colons in cases specially:

https://github.com/dart-lang/sdk/blob/32e3f78ba4a7401f6067bba112e82ff46b108a1d/pkg/analysis_server/lib/src/lsp/constants.dart#L36

But apparently when I implemented the conditional logic, I didn't add anything for colons:

https://github.com/dart-lang/sdk/blob/8a9188aae5f1a37c58fdd917229826d61d3d8da0/pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart#L697-L703

So, I should add handling here so colon only triggers for specific places. That doesn't address the issue that `break` may be top if the user manually invokes completion and perhaps it's not the item that should rank the highest, but it should at least stop the completion popping open where you're probably going to press `<enter>` expecting a newline, not to complete on whatever the top item is.


> Also, there might be a preference setting for that (I haven't looked).

We don't allow you to choose indivdual trigger characters, but you can enable/disable language-supplied trigger characters entirely in VS Code. We probably could make this configurable, though I feel like we should be able to improve this where it's bad for everyone, rather than require users to customise it (I don't think there should be much variance in what users consider right/wrong, I think the case above is just wrong).

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/294300 will prevent automatic triggering of completion in switch statements like this.

I'm surprised this hadn't come up before, it feels rather broken if you pause after typing the `:` before hitting `<enter>` (I suspect I've always done it fast enough that it didn't have time to pop up, so I hadn't noticed it).

With the fix, we won't _automatically_ trigger completion here, but you can still trigger it manually. If there are other cases where colons _shouldn't_ automatically trigger it, let me know and I can add them to (or we can invert it to a whitelist and default to not).

Generally triggering completion more often isn't terrible (in fact VS Code does it a lot when you just type any letter, regardless of our trigger characters), but triggering it in a place where the user is likely to want to press `<enter>` to get a newline is definitely bad.

**Comment by scheglov** [comment]
While it is true that IDEs reorder  completion suggestions, in this case it looks that the server gives `break` the highest relevance score.
```dart
void f(int x) {
  switch (x) {
    case 0:
      ^
  }
}
```
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/384794/232117053-3c9cf03f-7fab-4a70-9da6-a02d24576f16.png">

We probably want to give it a very low score when `patterns` is enabled.
It is allowed, but it is useless.
And if `unnecessary_breaks` is enabled, maybe we should not suggest it at all :-)

**Comment by bwilkerson** [comment]
> ... server gives break the highest relevance score.

That's probably a result of the relevance tables, which were built using pre-3.0 code.

I suppose we could hand edit the tables, but that won't help when we regenerate them. Still, it would be a short term solution.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/295387

This might be a sign that relevance tables need another dimension - the language version. Or maybe we actually should not care too much about older versions, and expect that users will mostly use the latest version, so any older versions support on this level is wasteful.

Although we might still have to provide an initial version of tables for a new language version with manual changes like this, just because there is no yet representative corpus of code when we release a new language version.
