### ISSUE TITLE
records feature seems to cause unexpected parsing error

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#51988]
this
```dart
class A {
  final int x;
  
  A() : x = () {
    return 1;
  })();
}
```
yields
```
Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
  A() : x = () {
            ^
```
but if i add seemingly copious parentheses, it works:
```dart
class A {
  final int x;
  
  A() : x = (() {
    return 1;
  })());
}
```
shouldn't the first version work?

* Dart SDK version: 2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "macos_x64"
* MacOSX

**Comment by lrhn** [comment]
No. The first version also didn't work before records, it just gave a different error.
You're not allowed to have function expressions at the top-level of an initializer list.

Neither example here is syntactically correct.
Even if you make the function argument explicit:
```dart
class A {
  final int x;
  
  A() : x = (var z) {
    return 1;
  }(1);
}

void main(){}
```
you still get an error because the function expression is not allowed at that point.
The parentheses you add are actually required.
