### ISSUE TITLE
[Class modifiers] No error if mixin extends Object

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52062]
The following code produces no expected error in both analyzer and CFE
```dart
mixin class MixinClassExtendsObject extends Object {}
//                                  ^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified

base mixin class BaseMixinClassExtendsObject extends Object {}
//                                           ^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified

abstract mixin class AbstractMixinClassExtendsObject extends Object {}
//                                                   ^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified

abstract base mixin class AbstractBaseMixinClassExtendsObject extends Object {}
//                                                            ^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
```

According to the [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md#mixin-restrictions)

> It's a compile-time error if a mixin class declaration:
> ...
> - has an `extends` clause,

Tested on the edge SDK (April 17, 2023) on Linux X64

**Comment by lrhn** [comment]
The specification of `mixin class` restrictions says "no `extends` clause", not "has `Object` as superclass" like the pre-3.0 mixin classes, so these should indeed be errors.
(Also no `with` clauses.)

**Comment by johnniwinther** [comment]
cc @kallentu @stereotype441

**Comment by lrhn** [comment]
Also:
```dart
 // Must be error, mixin application class declarations cannot be marked `mixin`
mixin class C = Object with M; // No error in CFE or analyzer

mixin M {}
```

**Comment by leafpetersen** [comment]
I think we may end up "fixing" one or both of these by just relaxing the spec to accept them.  They are, as far as I can tell, harmless?

**Comment by lrhn** [comment]
The `mixin class C = Object with M;` has worked so far, and it can probably keep working. Mixing it in is the same as mixin in `M`. (Maybe, it's not tested, but if it works like it used to, it's probably fine.)
It doesn't allow `mixin class C = Object with M, N;` or `mixin class C = S with M;`, so it is really only one mixin getting renamed, and possibly a way to do so with other class modifiers.

And allowing `mixin class C extends Object` is harmless. Useless too, which is why I disallowed it, but harmless.

I was worried there might be too few checks on non-trivial constructors, from looking at the code, but it looks fine in DartPad.

So, maybe we can just do this. Otherwise I have a CL to start from 
(The error messages still need work, though.)

**Comment by lrhn** [comment]
I now have a CL which fixes the problems: https://dart-review.googlesource.com/c/sdk/+/298880

We have a bunch of tests which assume that `mixin class C extends Object {}` and `mixin class C = Object with N` are valid. We have a few tests which assume they are not (my own from that CL and co19 tests).

I'd prefer to land, but can understand that it's late and slightly dangerous (front-end code being written by me, who had to guess what APIs really mean).

**Comment by lrhn** [comment]
It's decided - current implemented behavior is allowed, and specification has been updated to match.
