### ISSUE TITLE
Do a runtime check whether RtlAdd/DeleteGrowableFunctionTable are available, fixing failure to run on Win7

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#52071]
https://dart.googlesource.com/sdk/+/386a87a8905c48342e1bb9dcbe0ff693690468a7 introduced use of RtlAdd/DeleteGrowableFunctionTable which were not available in Windows 7, causing failures on that platform.

It should be possible to confirm whether those functions are available at runtime and only use them if they are.

**Comment by loic-sharma** [comment]
This breaks Flutter apps on Windows 7 and causes them to crash immediately on launch.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/295741 with the proposed fix

**Comment by a-siva** [comment]
> This breaks Flutter apps on Windows 7 and causes them to crash immediately on launch.
> 

Dart only supports Windows 10 and Windows 11, please see [https://dart.dev/get-dart](https://dart.dev/get-dart)
We do not do any testing on other versions of Windows.
Similarly I think Flutter only claims best effort support for Windows 7, 8 and 11 as deployment platforms.

I don't understand why we need to keep complicating our codebase with this pattern of LoadLibrary/GetProcAddress
in order to support Windows7, here is another case of this pattern
https://dart-review.googlesource.com/c/sdk/+/320060/4/runtime/bin/platform_win.cc

@mit-mit can you please comment on whether we want to continue this model of support.
