### ISSUE TITLE
Question: AOT min program size

### ISSUE THREAD

**Issue by renlite** [dart-lang/sdk#52088]
Dart SDK version: 3.1.0-12.0.dev:
```dart compile exe .\hello.dart```
produces a ```hello.exe``` of 4_776_448 bytes
``` Dart
void main() {
  var a, b = 10;
  a = b + a;
}
```

Go version go1.19.3:
```go build .\hello.go```
produces a ```hello.exe``` of 1_217_024 bytes
```Go
package main

func main() {
	a, b := 10, 1
	a = a + b
}
```

C# 8.0.100-preview.1.23115.2:
```dotnet publish -r win-x64 -c Release```
produces a ```hello.exe``` of 1_782_272 bytes
```C#
var a = 1;
var b = a + 1;
```

Why is the AOT file (runtime) of a Dart min app so much bigger copared to other GC languages?
Are there plans for version 3.0 to reduce the base size? (Eg. for desktop apps or microservices (wasm on server)).

**Comment by julemand101** [comment]
When you do `dart compile exe` what you really are doing is `dart compile aot-snapshot` and then glue this output together with `dartaotruntime.exe`.

That means the minimum size of a Dart program compiled to an self-running executable will always at least be the size of `dartaotruntime.exe` which contains all the native code which Dart makes use of (garbage collection, system calls and so on).

The good thing is that `dartaotruntime.exe` is a constant size so the size of a "hello world" program is not really a symbol that Dart programs are going to increase a lot in size with more code.

I remember there have been some discussions about the possibility of Dart compiler to selective choose which parts of `dartaotruntime.exe` that should be included but I seem to remember that the conclusion have been the extra complexity are not really worth it since it does not really make sense to optimize Dart for very small simple programs.

If you are going to make multiple small utility programs, it is going to be a lot of overhead to include `dartaotruntime.exe` in every executable. You can here instead just take `dartaotruntime.exe` from Dart SDK and include with your programs. Instead of `dart compile exe`, you will then use `dart compile aot-snapshot` and then add some scripts together with your programs that calls: `dartaotruntime.exe yourProgram.aot`. You will then only pay the overhead of `dartaotruntime.exe` once in your program distribution.

**Comment by mraleph** [comment]
What @julemand101 says is correct. TLDR story here is that for various reasons we end up including a bunch of stuff into the resulting binary which is not going to be used by a trivial small program, e.g.

- `dart:io` implementation including native implementations of file system, networking, BoringSSL and zip.
- regexp engine
- portions of ICU, pulled in by regexp engine
- various pieces of async machinery (e.g. `Future`)
- `Uri`
- pieces of `dart:typed_data` library

It should be possible to reduce this considerably - but so far we have not prioritised this highly mostly because any real large app will use need most of this machinery included anyway. 

That being said we will gradually chip away some of these things: e.g. since we want to encourage people to move away from `dart:io` HTTP stack to `package:http` which provides access to platform specific HTTP stacks we also want to make sure that `dart:io` stack can be removed when it is not needed.

**Comment by renlite** [comment]
> That being said we will gradually chip away some of these things: e.g. since we want to encourage people to move away from `dart:io` HTTP stack to `package:http` which provides access to platform specific HTTP stacks we also want to make sure that `dart:io` stack can be removed when it is not needed.

Good to hear there are plans to reduce the included libs. 
IMO
- regex
- ICU
- zip
- and maybe others
are not needed in the standard runtime.

I asume the new compiler target WASM would not include the current desktop runtime because the runtime "Wasmer" or "Wasmtime" will offers APIs for some libs included in the Dart runtime.

How does Flutter handle the Dart runtime? Is the complete Dart runtime included in the Flutter-runtime on desktop?

**Comment by mraleph** [comment]
> I asume the new compiler target WASM would not include the current desktop runtime because the runtime "Wasmer" or "Wasmtime" will offers APIs for some libs included in the Dart runtime.

Yes, Wasm target is different from the native target and it would rely on the underlying Wasm engine, e.g. we assume that underlying engine has regexp engine, etc.

> Is the complete Dart runtime included in the Flutter-runtime on desktop? 

Flutter includes basically the same runtime as the desktop version.

**Comment by renlite** [comment]
Thank you for the explanations.
