### ISSUE TITLE
[CP] analytics not reporting context_result information as intended

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#52091]
### Commit(s) to merge

7c1e2fee7006ae4552c9081ca3ea946fb7af72ce

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/296065

### Issue Description

When analytics are enabled for a user, on shutdown there is a set of data that is supposed to be sent.   One important piece of this data was missing because an old bug in the LSP analysis server prevented that data structure from being populated.

### What is the fix

Fix the bug in the LSP analysis server so it can properly recognize when analysis is complete, and populate the data structure.

### Why cherry-pick

It will be challenging to determine the full meaning and impact of potential problems identified in analytics without this data.  The data includes things like the number of files and lines of code that can help determine correlations in the data.

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/52089

**Comment by mit-mit** [comment]
SGTM

**Comment by mraleph** [comment]
I am looking at the original commit and it has no tests. How are we making sure that we are not regressing this? 

/cc @jacob314

**Comment by jcollins-g** [comment]
The original commit was tested end to end manually.

**Comment by mraleph** [comment]
@jcollins-g My point was not about the cherry-pick request itself. I agree with your assessment that the risk of cherry-picking is close to zero and I am in favour of approving it.

My point was that the CL which we are cherry-picking is a fix _which does not contain any tests_. What prevents us from regressing back to the unfixed behaviour? (e.g. somebody accidentally removes these lines in some refactoring on `main`). Unless absolutely impossible we should make sure that we have some CI coverage for the desired analytics behaviour. I probably should have flagged this concern on the original issue/CL rather than here. Sorry, for the confusion.

**Comment by bwilkerson** [comment]
We might also be able to test at the `AnalyticsManager` level, with a mock `Analytics` object that would record when given events are requested to be sent. Then we'd at least be able to test to the point where `Analytics` takes over.

**Comment by jcollins-g** [comment]
> We might also be able to test at the `AnalyticsManager` level, with a mock `Analytics` object that would record when given events are requested to be sent. Then we'd at least be able to test to the point where `Analytics` takes over.

Yes, that's reasonable.
