### ISSUE TITLE
FFI main thread blocking call

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/sdk#52106]
I'm trying to make an utility for OSX using Dart, that requires native code (I use objective-c to compile FFI compatible dylib).
Functions that I need (namely working with `NSAppleEventManager`) must execute on main OS thread, but it looks like Dart's event loop is blocking it permanently, so I cannot use `dispatch_async(dispatch_get_main_queue(),^{})` or `dispatch_sync` (which will cause deadlock).
It's likely related to #37022, but I couldn't found an example or post that mentions main thread, only cross threading.
So is there any way to temporary pause Dart VM, execute native code and return to execution, in other words native interruption mechanism?

**Comment by liamappelbe** [comment]
As I said on dart-lang/ffigen#551, if you're writing a pure Dart command line tool, I don't think the "main thread" exists, as Apple APIs define it. There's no main thread DispatchQueue listening for the call. If you write your app as a command line flutter app, that infrastructure might exist (I haven't tested this), but you still won't be able to run Dart code on the main thread.

Depending on your use case, there are 2 upcoming features that could help:
1. Async void FFI callbacks. We're adding a function like [`Pointer.fromFunction`](https://api.dart.dev/stable/2.19.6/dart-ffi/Pointer/fromFunction.html) that returns a native function pointer that can be invoked from any thread (but only for functions that return void). That native function pointer essentially dispatches a message back to the original Dart isolate that created the function asking it to run the function. Once this lands I'll integrate into ffigen so that ObjC blocks generated from Dart functions can be called from any thread.
2. There's a proposal to allow Dart code to run on the main thread, but this is in the early design stage. The way it will probably work is that there's a separate Isolate that is always pinned to the main thread. So you could send messages to that Isolate and have it invoke your Apple API functions.

**Comment by liamappelbe** [comment]
We're working on solving this in flutter (https://github.com/flutter/flutter/issues/136314), but for dart command line programs this isn't something we can solve in the VM. As far as macOS is concerned, the "main thread" doesn't exist in pure dart apps, because there is no thread running the OS event loop (there's no `DispatchQueue`). So even if we did provide something like PlatformIsolates or thread pinning in the Dart VM, it wouldn't help with this use case.

A 3rd party package could solve this problem by writing some native code that initialises all the required OS event loop infrastructure on some thread (which would then become the "main thread" by definition), and they could interact with that native code through FFI. Such a package could also use the Dart C API to spawn an isolate on that thread, and provide a way for users to run code on that isolate, if necessary. This is outside of the scope of what we can do from within the VM though.
