### ISSUE TITLE
[Patterns] No error if async for-in loop is used in non-async function

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52228]
The following code produces no error in both analyzer and CFE

```dart
main() {
  await for (var [v1] in Stream.fromIterable([[1], [2], [3]])) {
    print(v1);
  }
}
```
Expected result:
Error `The async for-in loop can only be used in an async function.` should occur

Tested on the edge SDK (May 1, 2023) on Linux x64

**Comment by lrhn** [comment]
Yeah, that's ... not great.
Only seems to apply when the binding is a pattern declaration or pattern assignment).

When compiled to JS, running the generated JS gives me an error of:
```
wfor.js:3050: SyntaxError: missing ) after argument list
        for (; A.boolConversionCheck(await t2.moveNext$0());) {
                                     ^^^^^
SyntaxError: missing ) after argument list
```
Suggests we compile Dart `await` to JavaScript `await`, and now the JavaScript function is also not `async`.
At least it won't run.


When run in the VM, the `await` is ignored at runtime, and we get an error that the stream doesn't have an `iterator` getter.

It's still problematic that the static checking doesn't catch it, because it suggests we can get unsoundness if we have an object implementing both `Stream` and having an `iterator`.
And indeed:

```dart
void main() {
  print("before");
  await for (var [v1] in X()) {
    int i = v1;
    print(i.runtimeType); // Prints `String`. Soundness malfunction, world collapsing!
  }
  print("after");
}
class X extends Stream<List<int>> {
  listen(_, {onError, onDone, cancelOnError = false}) {
    throw "not here";
  }
  Iterator<List<String>> get iterator {
    print("but here");  // Prints.
    return [["got"], ["cha"]].iterator;
  }
}
```

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/300620.
