### ISSUE TITLE
Dart complains about "unnecessary cast" that is necessary (when combining `enum` values)

### ISSUE THREAD

**Issue by skylon07** [dart-lang/sdk#52230]
### Problem/Repro

I am using VSCode 1.77.3, on MacOS 12.6.5, with the Dart/Flutter extension pack (my `dart --version` is 2.19.6). With that said, let's say I have three classes, defined as such:
```dart
class Namable {
    final String name;

    const Namable(this.name);
}

enum Colors implements Namable {
    red("red"),
    yellow("yellow"),
    blue("blue");

    final String name;

    const Colors(this.name);
}

enum Shapes implements Namable {
    square("square"),
    triangle("triangle"),
    circle("circle");

    final String name;

    const Shapes(this.name);
}
```

Now, let's say I wish to store a list of all the `Namable`s I've created:

```dart
final List<Namable> allNamables = Colors.values + Shapes.values;
```

The compiler complains that "The argument type 'List\<Shapes>' can't be assigned to the parameter type 'List\<Colors>'" for `Shapes.values`. So I specify a cast for `Colors.values`:

```dart
final List<Namable> allNamables = (Colors.values as List<Namable>) + Shapes.values;
```

Except now the compiler warns me that I'm performing an unnecessary cast. As far as I'm aware, this *is* a necessary cast to write two `enum` value lists together like this (although I am somewhat new to the dart language, so this might be a false assumption).

### Solution (I think)

I believe the problem here is that the warning about an "unnecessary cast" pops up when it shouldn't. I know there are other ways to express `allNamables` the way I want, I just happened to find this strange scenario that I think is just an edge case that needs to be addressed.

It's also possible I'm misunderstanding the warnings/errors, so the solution in this case might be a change of wording. But in either case, something feels off to me here.

I appreciate the hard work from you guys! Dart is an awesome language, and I dare say it's my most favorite to work with in all the languages I've written code in (and that's a decent list).

**Comment by lrhn** [comment]
The "unnecessary cast" is a warning from the analyzer. You get that for almost all up-casts, and it can be annoying, because there are a lot of places where an up-cast does change the behavior of the program.

It's just not particularly easy for the analyzer to know that, because it doesn't try to remove the cast and analyze the entire program again, to see if it makes a difference. So it guesses. Sometimes (fairly often) it guesses incorrectly.

The cast isn't as much unnecessary here, as it is wrong. You can cast `Colors.values` to `List<Namable>`, but it will still fail at runtime if you try to add a `List<Shapes>` to it, because the argument to `List<Colors>.operator+` has type `List<Colors>`. The cast just hides the incompatibility behind the unsafe covariance of generics.

You can do instead do `Colors.values.cast<Namable>() + Shapes.values`, or what I'd recommend:
```dart
  final List<Namable> allNamables = [...Colors.values, ...Shapes.values];
```

**Comment by skylon07** [comment]
Oh perfect, I didn't even realize dart had a spread operator. That's definitely more sensible than casting and `+`ing lists together. Thanks for the thorough explanations guys!
