### ISSUE TITLE
Mirror leak_tracker at dart.googlesource.com

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#52246]
Created this issue per instruction here: https://github.com/dart-lang/sdk/blob/f9ccf90c975ec9f635c9beefcfcb9b40f6184c97/DEPS#LL37C1-L37C1

I need to add dependency on [leak_tacker](https://github.com/dart-lang/leak_tracker) for dart-lang/sdk/pkg/analysis_server.
Issue: https://github.com/flutter/devtools/issues/5606

**Comment by whesse** [comment]
To add a package to DEPS, it must be in the  Dart Tools package group, according to https://goto.google.com/raising-the-quality-of-dart-packages-2020.

If it is accepted as a new Dart Tools package, then it can be added to DEPS if all its dependencies are in DEPS already.  I don't know if that applies to the dev dependencies.

I don't see any comments on the design document, which is in the review stage.  For example, could this code go into the analyzer package directly, rather than creating a new package?

Sorry this link is not mentioned in the DEPS instructions for adding dependencies - it should be.  It is also unclear what process is being followed for approving new dependencies and adding them.

For example, here is another discussion going on about adding packages to DEPS: https://groups.google.com/a/google.com/g/dart-engprod/c/hfyqZQoM4xE/m/u5NiUax7AgAJ

I'l start a thread on dart-core-libraries about adding this package, citing this issue.

**Comment by polina-c** [comment]
Reopening after discussing with team.

**Comment by whesse** [comment]
Yes, I will mirror the repo to dart.googlesource.com.

**Comment by whesse** [comment]
Done. https://dart.googlesource.com/leak_tracker

**Comment by polina-c** [comment]
Thank you! 
Will mirror be updated automatically or some actions are needed?

**Comment by whesse** [comment]
Yes, the mirrors automatically track GitHub.

**Comment by polina-c** [comment]
I am getting error, when I run `gclient sync` for update DEP.

CL: https://dart-review.googlesource.com/c/sdk/+/301721

```
Updating depot_tools...
using /var/folders/n1/zk6h3gk108n06st25r4pkmdm00nn0z/T/goma_polinach as tmpdir
update 41b3bcb64014144a844153fd5588c36411fffb56@1677729955@/Users/polinach/_/platform/depot_tools/.cipd_bin/compiler_proxy -> 41b3bcb64014144a844153fd5588c36411fffb56@1677729955@/Users/polinach/_/platform/depot_tools/.cipd_bin/compiler_proxy, skip restart
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "b711e5865292b03745fc354c8dd091740b2ddd05" "--no-tags"' in /Users/polinach/_/dart-sdk/sdk/third_party/pkg/leak_tracker failed; will retry after a short nap...

sdk/third_party/pkg/leak_tracker (ERROR)
----------------------------------------
[0:00:05] Started.
[0:00:05] Finished running: git config remote.origin.url
[0:00:05] Finished running: git rev-list -n 1 HEAD
[0:00:05] Finished running: git rev-parse --abbrev-ref=strict HEAD
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:07] fatal: expected 'acknowledgments'
[0:00:10] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:00:10] fatal: expected 'acknowledgments'
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin b711e5865292b03745fc354c8dd091740b2ddd05 --no-tags' returned non-zero exit status 128 in /Users/polinach/_/dart-sdk/sdk/third_party/pkg/leak_tracker
+===================================================+
|      METRICS COLLECTION IS TAKING PLACE           |
|                                                   |
| To suppress this message opt in or out using:     |
| $ gclient metrics [--opt-in] [--opt-out]          |
| For more information please see metrics.README.md |
| in your depot_tools checkout or visit             |
| https://bit.ly/3MpLAYM.                           |
+===================================================+
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "b711e5865292b03745fc354c8dd091740b2ddd05" "--no-tags"' in /Users/polinach/_/dart-sdk/sdk/third_party/pkg/leak_tracker failed; will retry after a short nap...
```

**Comment by sortie** [comment]
You pinned a bad commit that doesn't belong to any branch in the repository. Use a commit from the main branch :)

https://github.com/dart-lang/leak_tracker/commit/b711e5865292b03745fc354c8dd091740b2ddd05

Note how tags cannot be used if the commit is not on any branch.

**Comment by polina-c** [comment]
@sortie , thank you! it worked
