### ISSUE TITLE
Better standard types (typealiases + number types)

### ISSUE THREAD

**Issue by CXCubeHD** [dart-lang/sdk#52250]
In C# I like that I can write standard types in lowercase like `object` or `string`. I think that Dart should also consider adding this.
```cs
object o = ...;
string s = "string better than String";
```
This also makes for the programmer clear which Types are standard and which not. 

The second suggestion is that Dart should add more specific number types like `short`, `long`, `byte` and ect. These also should have the more specific version like `Int8`, `Int32`, `UInt64`, and ect.
```cs
short s = 110;
long l = -38264738463;
unsigned long ul = 10000000;
ulong ul2 = 57383747;
sbyte s = -25;

UInt16 u = 999;

float f = 1000f;
double d = 1000.0;

Float32 f2 = 193f32;
Float64 f3 = 1038f64;
```

This would allow for better interoperability and better readability. Also some developers may use this to write better performing code.

**Comment by Cryvage** [comment]
What I was thinking about is a more general approach. Instead of adding a bunch of numeric types, why wouldn't add a way to implement ANY numeric and other similar type? I'm talking about C# structs analog. For now, the main problem of implementing types like decimal, complex or vector3d is that non primitive types are allocated on heap and not on stack, which means you can implement them but their performance will suck big time. Seriously, if we are talking about performance, then the main problem for performance is not the size of number, it's GARBAGE COLLECTOR. The only way to make garbage collection performant is to avoid garbage collection anywhere possible. Following this approach is what makes Go so performant. Having structs is what makes C# a thing in gaming development. And of course, with this feature you can implement a number type of any size and any specific logic.

**Comment by insinfo** [comment]
@Cryvage I agree with you, this would be very good, it would greatly improve the power and flexibility of the dart.

**Comment by insinfo** [comment]
@CXCubeHD  why did you close this?
