### ISSUE TITLE
Analyzer wrongly says that `int case double` is impossible.

### ISSUE THREAD

**Issue by frmrgr** [dart-lang/sdk#52258]
Dart version 3.0.0-417.4.beta (dartpad beta channel) and version 3.1.0-63.0.dev (dartpad master channel).

```dart
void main() {
  final foo = 1;
  if (foo case double x) {
    print(['case double', x]);
  }
}
```

Analyzer warns that type int cannot match type double, but it's not true on web, and the print is invoked.

**Comment by lrhn** [comment]
Not language as much as implementation.

The specification doesn't say that a `double x` pattern cannot match something which doesn't have type `double`, or that has type `int`. (It can't on the VM, but we only know that because we know that there are no subtypes of `int` which also implement `double`. That information is not in the library declarations, so it is not available to the semantics.)

This is probably more like an analyzer "incompatible type" warning. We don't give similar warnings for other unrelated types, so it's probably specific to the `int`/`double`/`num` types. And it's wrong on the web.

**Comment by scheglov** [comment]
`abstract final class int extends num {}` is not a supertype of `abstract final class double extends num {}`, so it should not be possible to get `double` that is also `int`.

**Comment by bwilkerson** [comment]
Except when compiled by dart2js, where ints and doubles both turn into doubles in the JavaScript VM.

**Comment by leafpetersen** [comment]
> `abstract final class int extends num {}` is not a supertype of `abstract final class double extends num {}`, so it should not be possible to get double that is also int.

Within the same library, you can declare `final class _jsInt implements int, double {...}`.

**Comment by scheglov** [comment]
OK, I understand that in JavaScript any `int` could be a `double` as well.
So, we should special case this.

But `_jsInt` is wider than the special case I added.

I was going to make this code warning-free:
```dart
void f(int x) {
  if (x case double _) {}
}
```

But this is still a warning:
```dart
void f(double x) {
  if (x case int _) {}
}
```

Because I don't know if a `double` can be `int` in JavaScript. Can it?

**Comment by incendial** [comment]
> Because I don't know if a double can be int in JavaScript. Can it?

JS has only one type representing numbers, so yes.
<img width="275" alt="Screenshot 2023-05-06 at 11 19 40" src="https://user-images.githubusercontent.com/21116742/236609470-a7894ce3-6aa0-45fd-a739-3d99eb36ead6.png">
Unless the compiler does something like 
<img width="218" alt="Screenshot 2023-05-06 at 11 22 48" src="https://user-images.githubusercontent.com/21116742/236609611-e2f5fe1a-3238-4f00-8642-d876b2876a3b.png">
to actually get the difference.

**Comment by lrhn** [comment]
I can see that this *is* something we do for other types too:
```dart
sealed class Num {}
final class Int {}
final class Double {}

void main() {
  Int integer = Int();
  switch (integer) {
    case Double x: print(x); 
  }
}
```
gives
```
The matched value type 'Int' can never match the required type 'Double'.
Try using a different pattern.
```

It's a reasonable warning in general, and correct for libraries where you can trust the source to be the whole truth. 
Even if it is leaking information that there is no private subclass implementing both interfaces inside the library, which is not something you should ever *depend* on. It's just a warning, it doesn't change inference, so reasonable.

The "source is the whole truth" is what fails for platform libraries, where patch files and helper-libraries on the side (some of which can ignore privacy and class modifiers) can introduce classes not in the original library source.
Like JS-numbers which can be both an `int` and a `double` at the same time.

(I'm not aware of other cases which are as divergent between platforms, or where the internal type is as recognizable. We can see that a VM `_GrowableList` is such, by printing its `runtimeType`, but we don't have access to the type statically, so it's limited what we can do with it.)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/301725
