### ISSUE TITLE
[Patterns] No error on web platforms if runtime type of the Stream is not assignable to pattern's type in async for-in

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52267]
The following code produces no expected runtime error on `dart2js`, `dart2wasm-hostasserts-linux-x64-d8` and `ddc`
```dart
main() async {
  String log = "";
  Expect.throws(() async {
    await for (var (int v1)
        in Stream<num>.fromIterable([1, 2, 3.14]) as dynamic) {
      log += "$v1;";
    }
  });
  Expect.equals("", log);
```
The test that fails is [co19/LanguageFeatures/Patterns/execution_pattern_await_for_in_statement_A02_t03](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Patterns/execution_pattern_await_for_in_statement_A02_t03.dart)
Error logs https://dart-ci.firebaseapp.com/cl/301440/1

**Comment by lrhn** [comment]
Could be related to the other `await for` with pattern declaration issues.

**Comment by chloestefantsova** [comment]
Thanks for reporting! Btw, should the closure passed into `Expect.throws` be marked as `async` since it contains an `await`?

**Comment by sgrekhov** [comment]
Yes, of course it should. Test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Patterns/execution_pattern_await_for_in_statement_A02_t03.dart was updated to have it. I've just updated the example in this issue as well

**Comment by chloestefantsova** [comment]
Ok, so it seems that it's a non-issue. The exception isn't thrown because the closure passed down to `Expect.throws` is `async`, but `Except.throws` invokes it without an `await` (https://github.com/dart-lang/co19/blob/742378dde137d8d35e726640acf93164e0be59f8/Utils/expect_common.dart#L186). It means that a `Future` object is created, but the code inside of the closure isn't run. That explains the absence of the exception.

I rewrite the test so that it doesn't use `Expect.throws`, but runs the code inside of the body instead. And it throws the exception, as expected.

```dart
main() async {
  String log = "";
  await for (var (int v1)
      in Stream<num>.fromIterable([1, 2, 3.14]) as dynamic) {
    log += "$v1;";
  }
}
```

```
$ xcodebuild/ReleaseX64/dart /tmp/asdf.dart
Unhandled exception:
Bad state: Pattern matching error
#0      main (file:///tmp/asdf.dart:4:7)
<asynchronous suspension>
```

The generated Kernel code does seem to contain the cast of the elements of the stream to `int`.

```
library /*isNonNullableByDefault*/;
import self as self;
import "dart:core" as core;
import "dart:async" as asy;

static method main() → dynamic async /* futureValueType= dynamic */ {
  core::String log = "";
  {
    synthesized asy::Stream<dynamic> :stream = (asy::Stream::fromIterable<core::num>(core::_GrowableList::_literal3<core::num>(1, 2, 3.14)) as{ForNonNullableByDefault} dynamic) as{TypeError,ForDynamic,ForNonNullableByDefault} asy::Stream<dynamic>;
    synthesized asy::_StreamIterator<dynamic>? :for-iterator = new asy::_StreamIterator::•<dynamic>(:stream);
    try
      while (let dynamic #t1 = asy::_asyncStarMoveNextHelper(:stream) in await :for-iterator.{asy::_StreamIterator::moveNext}(){() → asy::Future<core::bool>}) {
        final dynamic #t2 = :for-iterator.{asy::_StreamIterator::current}{dynamic};
        {
          hoisted core::int v1;
          {
            final synthesized dynamic #0#0 = #t2;
            if(!(#0#0 is{ForNonNullableByDefault} core::int && (let final dynamic #t3 = v1 = #0#0{core::int} in true)))
              throw new core::StateError::•("Pattern matching error");
          }
          log = log.{core::String::+}("${v1};"){(core::String) → core::String};
        }
      }
    finally
      if(!(:for-iterator.{asy::_StreamIterator::_subscription}{asy::StreamSubscription<dynamic>?} == null))
        await :for-iterator.{asy::_StreamIterator::cancel}(){() → asy::Future<dynamic>};
  }
}
```

So, I'm closing the issue. Please reopen if needed.

**Comment by sgrekhov** [comment]
I figured out the problem. `Expect.throws(...);` doesn't catch exceptions thrown by `async` functions. So, the test should be rewritten

**Comment by eernstg** [comment]
There is no `Expect.throwsAsynchronously`. A test like [`tests/language/await/exceptions_test.dart`](https://github.com/dart-lang/sdk/blob/main/tests/language/await/exceptions_test.dart) uses a plain `await` in a try/catch statement in the top level `test_something` functions in order to test that a certain asynchronous function invocation returns a future which has been completed with an error. So it's probably necessary to do something like that, and certainly possible.

**Comment by lrhn** [comment]
The `asyncThrows` to use in SKD tests is [`asyncExpectThrows` in `package:async_helper/async_helper.dart`](https://github.com/dart-lang/sdk/blob/3fb13058ced2b63f99248a34c08f3fed92be4a85/pkg/async_helper/lib/async_helper.dart#L102).
