### ISSUE TITLE
Bug: Type checking is broken for enums

### ISSUE THREAD

**Issue by MichaelTamm** [dart-lang/sdk#52269]
I think, the following code should not compile:
```
enum A { foo, bar }

enum B { foo, bar, baz }

void main() {
  final x = A.foo;
  print(x == B.foo ? '$x == B.foo' : '$x != B.foo');
}
```
... because it makes no sense to compare `x` (an instance of `enum A`) with an instance of  `enum B`.

[Link to the example in DartPad](https://dartpad.dev/799918fbd3fedff5960511ab12692fb3)

* Dart SDK 2.19.6

**Comment by lrhn** [comment]
It is indeed statically detectable that the an instance of type `A` will not be equal to an instance of type `B`.
Because both are `enum` classes, which means nothing else can implement the types, and enums cannot override `==`.

It's not something the language tries to prevent you from doing. After all, it works (it returns `false` as it should) and the `==` operator has parameter type `Object`, so it's perfectly fine to ask.
It's a little weird to make this example code not compile, but allow it if you wrote `Object x = A.foo;`.

The analyzer could choose to tell you that the comparison is useless. And it does, you just have to ask for it by enabling the
[`unrelated_type_equality_checks`](https://dart-lang.github.io/linter/lints/unrelated_type_equality_checks.html) lint.

**Comment by MichaelTamm** [comment]
Just for reference: The Linter [unrelated_type_equality_checks](https://dart-lang.github.io/linter/lints/unrelated_type_equality_checks.html) does not work for this example: https://github.com/dart-lang/linter/issues/3220
