### ISSUE TITLE
assert throws off null promotion

### ISSUE THREAD

**Issue by mdebbar** [dart-lang/sdk#52281]
In the presence of a callback that touches a variable, makes the type promotion for that variable fail to work properly.

One good example of this is when using the assert-with-iife pattern.

```dart
void main() {
  print(getBool());
}

bool _boolean = true;

bool getBool() {
  bool? result;

  // Comment out the following assert to make the analyzer happy.
  assert(() {
    result = _boolean;
    return true;
  }());
  
  // The following "if" fails to promote `result` to a `bool` when the
  // above assert is present.
  if (result != null) {
    return result; // Analyzer: A value of type 'bool?' can't be returned ...
  }
  throw Error();
}
```

**Comment by bwilkerson** [comment]
I believe that this is working as intended.

Type promotion currently assumes that any closure could be executed at any time (including between the `if (result != null)` and the `return result;`). As a result, it won't make any assumptions about the type of any variables that are assigned within a closure.

We could potentially special case `assert` (because we know exactly when the closure will be executed), but I don't believe that we have any plans to do so.

@stereotype441

**Comment by mdebbar** [comment]
Oh I see. That makes sense. The local closure has access to the local variable, so it's not safe to assume anything about it.

I would like to suggest a few improvements that would make type promotion more helpful in these cases:

1. Check if a reference to the closure is assigned to or passed anywhere. In the example above, the closure isn't referenced by anything, it's just immediately invoked. So we can guarantee that it won't be invoked again (there's no reference to it, so how can it be invoked?).

2. Analyze the closure body to make a more informed type promotion decision. In the example above, the `result` is assigned a non-null value inside the closure, so we can guarantee that the closure will never cause `result` to be null.
