### ISSUE TITLE
js-interop: @JSExport works in webdev-serve but fails in webdev-build

### ISSUE THREAD

**Issue by linuxerwang** [dart-lang/sdk#52291]
**Describe the issue you're seeing**

@JSExport works in "webdev serve" but fails in "webdev build".

**Does it happen in Dartium or when compiled to JavaScript?**

It happens when compiled to JavaScript.

* Dart SDK version: *use `dart --version`*

2.19.6 (stable)

* pkg/js version: *look at `pubspec.lock`*

0.6.7

Failing code:

https://github.com/linuxerwang/js-interop

Dart:

```dart
@JS('runIt')
external void runIt(api);

@JSExport()
class Api {
  void callback() {
    print('@api.callback()');
  }
}

void main() {
  var api = Api();
  runIt(api);
}
```

HTML:

```html
<script>
        function runIt(api) {
            api.callback();
        }
</script>
```

When run with "webdev serve", in web console it has correct output:

```
@api.callback()
```

but when run with "webdev build" and serve from any web server, in web console it throws exception:

```
Uncaught TypeError: api.callback is not a function
    at runIt ((index):14:17)
    at cu (main.dart.js:1050:6)
    at main.dart.js:1464:6
    at main.dart.js:1458:55
    at dartProgram (main.dart.js:1461:84)
    at main.dart.js:1464:15
```

Thanks.

**Comment by Markzipan** [comment]
@srujzs Can you add some comments? 

Somewhat unrelated, but it's odd we have references to Dartium floating out there in our error submission suggestions.

**Comment by srujzs** [comment]
```
void main() {
  var api = Api();
  runIt(api);
}
```

@JSExport is meant to be used with `createDartExport` from 'dart:js_util'. This function actually creates the JS wrapper object for the Dart object (`Api` in this case) e.g. `createDartExport(Api())`. The wrapper then has the needed members to forward to the Dart object. It's the result of this function that you should pass to `runIt`.

Without it, you're passing the Dart object directly to JS, and calling members of the Dart object in JS is undefined behavior. In the Dart Dev Compiler, this just happens to work due to the calling convention. Dart2JS has a different calling convention, so it fails.

**Comment by linuxerwang** [comment]
Thanks! Turned out createDartExport() has to be called for every returned objects (think about chained method calls).
