### ISSUE TITLE
Request mirror of harfbuzz repo from GitHub

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#52307]
I'm working on a change to the analysis server that will create previews for icons in IDEs. I need harfbuzz to draw the images. 

The harfbuzz library is already mirrored at https://skia.googlesource.com/third_party/harfbuzz/.
Perhaps all that's needed is to add `skia.googlesource.com` to `allowed_hosts` in `sdk/DEPS`.

Harfbuzz is here:
https://github.com/harfbuzz/harfbuzz

**Comment by stevemessick** [comment]
I'll also need `Freetype` and `Cairo`. I saw that skia has freetype2, but I don't know how related that is to freetype. I didn't see cairo in skia.

https://cairographics.org/download

https://sourceforge.net/projects/freetype/files/
 - mirror: https://github.com/freetype/freetype

**Comment by athomas** [comment]
This is something you'd need to raise with folks familiar with licensing first. What will we do with those dependencies? Will they be shipped with the Dart SDK?

License used here:
* harfbuzz: "Old MIT"
* cairo: MPL or LGPL
* freetype: GPL or a modified BSD license (with advertising clause)

**Comment by mraleph** [comment]
Is there a design doc which explains why these dependencies need to be part of Dart SDK? Can't IDE itself handle the rendering? Seems a bit strange we want to  balloon ourselves with these deps.

**Comment by jacob314** [comment]
Here is a link to the design doc:
https://docs.google.com/document/d/1h4vfkpamhJ-SN-jUESdmOp9MM0MjxMm00rpSeZ3gqZ0/edit?resourcekey=0-fBSEkPI1N0XcCr-S-qxAfw

**Comment by stevemessick** [comment]
> What will we do with those dependencies? Will they be shipped with the Dart SDK?

They are used to build a C program I call `icon_gen`. The unoptimized version is about 135KB in size. That will be added to the SDK. None of the libraries I mentioned will be added to the SDK. They are only needed to build `icon_gen`.

> This is something you'd need to raise with folks familiar with licensing first.

Is that still an issue, since we're only using them to build a C program?

> Can't IDE itself handle the rendering?

I'm not sure if VS Code can, but probably. The thing is, if we make VS Code do it then every other IDE that wants to use this feature also has to duplicate that code. If we do it in the analysis server then it is done for all.

> Seems a bit strange we want to balloon ourselves with these deps.

We're not; these are only used to build the C program.

> Can some helper binary/library live in a Flutter SDK for this?

Sure, but that seems odd, since Flutter wouldn't actually have any use for it.

**Comment by athomas** [comment]
>> This is something you'd need to raise with folks familiar with licensing first.
>
> Is that still an issue, since we're only using them to build a C program?

Yes, harfbuzz is probably fine, cairo is listed as a "restricted" license and freetype (note freetype2 might be easier) would mean we take on ownership for internal maintenance. However, we need to ensure that our use case is compatible and the only way to know for sure is to ask the experts.

**Comment by stevemessick** [comment]
@athomas I sent you email confirming that all three have acceptable licenses. We can use harfbuzz and freetype2 from skia.googlesource.com. We'll just need to create a mirror for cairo.

**Comment by athomas** [comment]
@whesse please create the mirror.

@stevemessick we should be discussing how to comply with the license terms when we release this as well. So please include me as a reviewer when we're starting to use these dependencies as well.

**Comment by whesse** [comment]
The cairo repository is not on GitHub, but at https://gitlab.freedesktop.org/cairo/cairo

We can only set up mirroring for repositories that are on GitHub, because they are already mirrored to GoB's github mirror.

The cairo repository also does not seem to be sufficient, since cairo itself has dependencies.
Specifically, the pixman dependency.  Pixman could be used from an installed version on Linux, it seems,
but otherwise we would need also its source, at
https://gitlab.freedesktop.org/pixman/pixman

I don't know of a solution for mirroring from those repositories.  It may be that we are better off with a clone of these repositories, in third_party on the dart GoB host, updated manually.

I'm not clear how this will affect google3 builds of Dart - will google3 also need copies of these repositories to be added to third_party?

I see in the design document that the existing Flutter plugin can be used instead to do this, but it is not as fast as the C program you are building using these dependencies. @devoncarew suggested taking another look at that option.

**Comment by stevemessick** [comment]
Closing this since I should have used skia instead of cairo, and it does make more sense to add something to the Flutter SDK.
