### ISSUE TITLE
`analyze_snapshot` don't list function offsets

### ISSUE THREAD

**Issue by 3asm** [dart-lang/sdk#52310]
Hi,

The utility `analyze_snapshot` allows to dump the list functions in a class with their offset, however, in the last release, the functions are no longer shown, even though I can see them present by doing a strings call on the `libapp.so` file.

Some functions do still show, but external 3rd party dependencies are not.

Maybe @rmacnak-google has some insights on changes to the VM which is causing the analyzer to miss some information?

**Comment by mraleph** [comment]
@3asm how do you produce `libapp.so`?

**Comment by 3asm** [comment]
With `flutter build linux`.

**Comment by mraleph** [comment]
My guess would be that this is due to dart-lang/sdk@4c82eb58364335356d56dd377ab0fd2785dc8f11, which pruned class and library dictionaries. Function objects are still floating around but they are not used for dispatch purposes so keeping them in the dictionaries is not really needed. 

If this was DWARF stack traces mode then most function objects would be completely gone... You could update `analyze_snapshot` to iterate the heap to recover function objects - but that would be just a temporary solution because eventually these useless function objects will be gone one way or another.

**Comment by 3asm** [comment]
Got it, thanks @mraleph . 

Do you think it would make sense if Dart supported an official utility or API to introspect a Snapshot? 

The common use case of security analysis for either finding vulnerabilities or detecting malicious behavior requires patching the runtime to collect that information.

**Comment by mraleph** [comment]
> Do you think it would make sense if Dart supported an official utility or API to introspect a Snapshot?

`analyze_snapshot` is that official utility. We will be happy to accept PR that expose additional information from it that you might find useful. 

But as I said: you should not expect (especially for the purpose of detecting malicious behaviour) that usable symbolic information (e.g. function objects) remains in the snapshot. It's extremely easy to remove it by passing `--split-debug-info=...` to Flutter CLI when building release binaries and we want to eventually make this default.

**Comment by 3asm** [comment]
Got it, thanks @mraleph .
