### ISSUE TITLE
http requests throw when called from Isolate.run() but work when called from compute()

### ISSUE THREAD

**Issue by Wizzel1** [dart-lang/sdk#52336]
* Dart v2.19.6 
* MacOS

I am trying to execute a http request from an Isolate. 

```dart
Future<String> myRequest(String argument) async {
  final response = await http.get(
   ///request Code
  );
  return response.body;
}
```

when I try to run it with Isolate.run() like this 

```dart
 final test = await Isolate.run(
        () => myRequest(argument),
      );
```
 I am getting an error : 
 ```ArgumentError (Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:ui' Class: Paragraph))```
 but when I run it with compute
 
```dart
 final test = await compute(myRequest, argument);
```

it works. Is this intended?

**Comment by julemand101** [comment]
Are you running your code in a browser?
Also, it seems you forgot to paste the error message into your issue. Can you please add it?

**Comment by Wizzel1** [comment]
@julemand101 
No, it is running on a mac. Sorry, I have edited the error message.

**Comment by lrhn** [comment]
Definitely not running in a browser, since `dart:isolate` is not available on the web.

My best guess is that the closure `() => myRequest(argument)` closes over more state than necessary, and some of that state cannot be sent. (And the error message supports that.)

Try adding a top-level helper like:
```dart
R Function() curryFunction<R, T>(R Function(T) function, T argument) => () => function(argument);
```
and do:
```dart
final test = await Isolate.run(curryFunction(myRequest, argument));`
```
That should ensure that the `()=>myRequest(argument)` closure is created in a scope with no extra variables to over-capture.

Q.v. #50462

**Comment by Wizzel1** [comment]
Yes, now it works. However, I don't quite understand the problem. Is this a mistake I made or a bug in dart?

**Comment by Wizzel1** [comment]
I see. Thanks for your quick help!
