### ISSUE TITLE
Expose name as property in Enum class

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#52353]
Today the `name` getter in the `Enum` class is provided by an extension.  
This is a problem with `AngularDart` templates because it can't see the extension easily.  
Also you can't override it.  

Can't it be a real property in `Enum`?

**Comment by lrhn** [comment]
It's an extension, because then it cannot conflict with an enum element named `name`.

Not sure why Angular has problems with extensions methods. More and more things in Dart are added using extension methods, so I'd recommend become compatible with those.

If an actual enum wants to have a `name` getter, it can easily do so:
```dart
enum MyEnum { 
  foo, bar, baz;
  String get name => EnumName(this).name;
}
```
