### ISSUE TITLE
Create a Platform.lineEnding constant

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/sdk#52379]
The implementation would be:

```dart
class Platform {
  ...
  static String get lineEnding => isWindows ? '\r\n' : '\n';
}
```

**Comment by lrhn** [comment]
I'd probably call it `lineTerminator`, because that's the phrase we use elsewhere (see, e.g., `LineSplitter` documentation).

Are we *sure* there are no other line terminator variants in use on supported systems? We don't support Mac OS 9 any more, nobody does, but I believe it used `\r`. 
If all we support are Unixes, MacOS X+/iOS and Windows, I think we're good. 

We could make it possible to override this line ending, either by en embedder - in case anyone want Dart on OS/390 - or even using `IOOverrides` if someone wants to run some code "cross platform".

**Comment by mit-mit** [comment]
`lineTerminator` and Unixes, MacOS X+/iOS and Windows SGTM

**Comment by aam** [comment]
My view is that there is no _correct_ line ending for a platform.
Line ending is a property of a text stream, similar to encoding, for example.

**Comment by brianquinlan** [comment]
If you are producing a text stream then you need to pick a line ending. And, unlike encodings, line endings *are* standardized by the platform.

On Windows, if you `fopen` a file with `O_TEXT` then `\n` written to the file will be translated into `\r\n`.

**Comment by brianquinlan** [comment]
BTW, there is a lot of precident for providing this value in other programming languages:
Python: `os.linesep`
Java: `System.lineSeparator()`
NodeJS: `os.EOL`
C#: `Environment.NewLine`
PHP: `PHP_EOL`

**Comment by aam** [comment]
I guess what I'm saying is that nowadays it feels like on Windows the lines between unix and dos line-ending content are being blurred, you are expected to work with LF-delimited content on Windows.
It feels like branding CRLF as Windows _platform_ standard for line ending is the thing of a past. Outside of internal implementations(`O_TEXT` conversion and some such), it should not cloud the picture for a Dart developer.

Consider that even '/' as path separator works in Windows Powershell terminal nowadays.

**Comment by brianquinlan** [comment]
We do have [`Platform.pathSeperator`](https://api.dart.dev/stable/3.0.0/dart-io/Platform/pathSeparator.html) and you should still use it when rendering paths on Windows.
