### ISSUE TITLE
type checking issue with record fields

### ISSUE THREAD

**Issue by weighton** [dart-lang/sdk#52392]
Simple code as following. The type of g is double but recognized as int.

(int x, int y, int z) point = (1, 2, 3);
(int r, double g, int b) color = (1, 2.0, 3);
print(point == color); // true
print(color.$2.runtimeType); // int

**Comment by julemand101** [comment]
What platform are you testing with? If web (includes dartpad.dev) then this is expected behavior since JavaScript does not have any `int` type. You can read about how Dart deals with that here: https://dart.dev/guides/language/numbers#differences-in-behavior

But in short, Dart can't see the difference between `1.0` and `1` on the JavaScript platform. So when asking `runtimeType` on numbers, it will return different types depending on the value. E.g. this program:

```dart
void main() {
  double a = 1.0;
  double b = 1.1;

  print(a.runtimeType); // double on native, int on web
  print(b.runtimeType); // double on all platforms
}
```

**Comment by lrhn** [comment]
This is indeed working as intended on the web. 

The value `2.0`, aka. `2`, has a type whose `runtimeType` returns the `int` `Type` and which implements both `int` and `double`.
