### ISSUE TITLE
Dart2js-compiled app runs with -01 and fails with -O0, -O2, -O3, -O4

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#52415]
App also works in debug mode.

See details in https://github.com/flutter/flutter/issues/120787

**Comment by sigmundch** [comment]
I looked at this last week and I do not believe at the moment that this is a Dart issue - I pointed at my suspicion in https://github.com/flutter/flutter/issues/120787#issuecomment-1544390907

The fact that this fails with `-O2` leads me to believe there is an issue with minfication (e.g. somewhere in the framework there may be an invalid use of a runtimeType name assuming that it is preserved in production builds), but the error points at the bindings with canvaskit, so we are block on the flutter web team from investigating first.

I'm inclined to close this issue for now since there is nothing actionable for us to do until the investigation progresses on the flutter side.
