### ISSUE TITLE
Composite `TypedData` views

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/sdk#52428]
There are currently no way to make a composite data view without copying data into new buffer and managing on-change-write-back manually and you can't make custom `TypedData` provider for a good reasons.

I'd like to request a new `TypedData` implementer `CompositeTypedDataView` (name subject to change) that will make it possible to combine multiple `TypedData` into single **view** that will forward access (read and write, if not unmodifiable) to underlying `TypedData` **objects**.

Main use case for this is chunked data buffers: having such capability will make it easier to work with data boundaries or making views on multiple chunks. Also views are more memory efficient, because we don't need to copy large amount of data.

**Comment by lrhn** [comment]
Can you give a more specific example of what you want to do?

If you want to have, say, a list of `Uint8List`s, and treat them as a single `ByteBuffer`-like backing storage for multiple views, you can definitely write code that behaves that way, it just cannot implement `Uint8List` itself, since that's a `final` interface.

The `Uint8Buffer` from `dart:typed_data` is an example of a class which mimics the `Uint8List` API without implementing the interface. It uses the "double when full" approach to amortized efficient allocation, but there are definitely other valid strategies.

If you combine multiple chunks with varying sizes, it'll probably never be very efficient, so it's fairly limited what you can do if you provide all the chunks. It's more likely that you can create an efficient growable typed-data like class if you let itself control the underlying chunks and their sizes (something like Java's `ArrayList` based on `TypeData` lists).

**Comment by blaugold** [comment]
In case anyone else could not find `Uint8Buffer`, it's in package [`typed_data`](https://pub.dev/packages/typed_data).

**Comment by Zekfad** [comment]
Thanks for replies.

In my case I'm dealing with large binary files (over 1-2GB, that I parse into corresponding data classes and have hot-patch capability, e.g. editing 64 bit floats in-place), the case is that I read files by chunks and would like to have a full view over all of them (meaning i need `Uint8List` interface, because of some dependencies) and views to parts of it, that could be on the boundary of chunks.

While I can agree that multiple variable size chunks can be tricky and not always maximum performance, but it will be more memory efficient, given that you need to have full file in memory (in-data pointers and other things requires that).

On user land it's possible to emulate such behavior, but it would not be compatible with modules aimed to `TypedData`, because as you said interfaces are final.

**Comment by lrhn** [comment]
I think it's very unlikely that we'll allow simply combining arbitrary `ByteBuffer`s into, effectively, a single one.

The point of typed-data is to have efficient access to the underlying data, which is achieved by having a uniform access mechanism.

If a version of typed data exists which requires a complicated computation to find the byte, not just adding some indices, then that uniform access no longer applies, and all other typed data may become slower as well.

**Comment by Zekfad** [comment]
Thank you for your reply!

That's unfortunate for me, but you have a point.

I'll try to find workaround solution for my case (I'm thinking of manual chunk flush after update, or something like that).
