### ISSUE TITLE
ffi/invoke_callback_after_suspension_test is flaky

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#52441]
The test was marked as flaky on vm-reload-linux-debug-x64, vm-reload-linux-release-x64, vm-reload-rollback-linux-debug-x64, and vm-reload-rollback-linux-release-x64.

The test was marked as crashing on vm-msan-linux-release-x64: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-msan-linux-release-x64/100/overview

@liamappelbe @mkustermann

**Comment by mkustermann** [comment]
The test is a newly added regression test for a bug that was fixed in the same CL.

The msan test failure is unrelated: It has to do with the fact that our libc++ isn't msan instrumented, see https://github.com/dart-lang/sdk/issues/44377

The test uses 50 isolates. That means the ``--hot-reload-test-mode` will cause this test to do 50x the number of reloads as a normal single-isolate test. Though I'll investigate a bit more.

**Comment by mkustermann** [comment]
Regarding the flaky timeouts: There's a deadlock that can happen in our artificial `--hot-reload-test-mode`. Will fix in [cl/304682](https://dart-review.googlesource.com/c/sdk/+/304682)
