### ISSUE TITLE
VM error in runtime subtype checking of nullable `FutureOr`

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#52536]
```dart
import 'dart:async';

void main() {
  final c = C<int?, int?>(compute);
  c.fn(42);
}

class C<D, T> {
  final FutureOr<T> Function(D) fn;

  C(this.fn);
}

FutureOr<T>? compute<T extends Object>(int? a) => null;
```

yields

```
Unhandled exception:
type '(int?) => FutureOr<int>?' is not a subtype of type '(int?) => FutureOr<int?>'
#0      main (package:bug/hi.dart:5:5)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

Process finished with exit code 255
```

I agree this is an error, but hope this can be caught at compile time - since Dart is a statically strongly typed language and it is helpful that Dart have caught so many type errors at compile time!

**Comment by lrhn** [comment]
This appears to be a bug in the VM's runtime implementation of subtype checking. 
Doesn't reproduce in dartpad.dev, so I'm assuming VM only.

The type `FutureOr<int>? Function(int?)` *is* a subtype of `FutureOr<int?> Function(int?)`, because `FutureOr<int>?` is a subtype of `FutureOr<int?>`.

A simpler example is:
```dart
  print(<FutureOr<int>?>[] is List<FutureOr<int?>>);
```
which prints `false` on the VM, `true` on dart2js in DartPad, and has the analyzer warn that the check is unnecessary because it's always true.

Seems related to `FutureOr`, so I'd check the implementation of the `Left FutureOr` and `Right FutureOr` rules of 
https://github.com/dart-lang/language/blob/main/resources/type-system/subtyping.md#algorithmic-subtyping

**Comment by fzyzcjy** [comment]
@lrhn Thanks for the insights!
