### ISSUE TITLE
[convert:utf8] `decode(encode(org))` is different than original input

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/sdk#52539]
hi,

i was testing dart's utf8 functionality,
comparing the utf8 "encoded, then decoded, output", with the original input,
with the following (working, even on dartpad.dev) code:
```dart
import "dart:convert";

void main() {
  final //
      original = List<int>.generate(
        0x10ffff,
        (final int charCode) => //
            (1 /* to eliminate the value 0(null/delimiter) */ + charCode),
        growable: false,
      ),
      bytes = Utf8Encoder().convert(String.fromCharCodes(original)),
      utf8 = Utf8Decoder().convert(bytes).runes.toList();

  for (int i = 0, limit = original.length; i < limit; i += 1) {
    print("$i: " +
        ((original[i] == utf8[i]) //
            ? "OK        "
            : "***WARN***") +
        "  ${original[i]}  vs  ${utf8[i]}");
  }
}
```
Above code produces `0x10ffff` lines, 
But the relevant part is copied below,
Where,
```
/**
  1st column is iteration,
  2nd is:
    OK(utf8 output matches with original input), or
    WARN(mis-match),
  3rd is original input
  4th is utf8 output

  i    match?      org        utf8   */
55273: OK          55274  vs  55274
55274: OK          55275  vs  55275
55275: OK          55276  vs  55276
55276: OK          55277  vs  55277
55277: OK          55278  vs  55278
55278: OK          55279  vs  55279
55279: OK          55280  vs  55280
55280: OK          55281  vs  55281
55281: OK          55282  vs  55282
55282: OK          55283  vs  55283
55283: OK          55284  vs  55284
55284: OK          55285  vs  55285
55285: OK          55286  vs  55286
55286: OK          55287  vs  55287
55287: OK          55288  vs  55288
55288: OK          55289  vs  55289
55289: OK          55290  vs  55290
55290: OK          55291  vs  55291
55291: OK          55292  vs  55292
55292: OK          55293  vs  55293
55293: OK          55294  vs  55294
55294: OK          55295  vs  55295
55295: ***WARN***  55296  vs  65533
55296: ***WARN***  55297  vs  65533
55297: ***WARN***  55298  vs  65533
55298: ***WARN***  55299  vs  65533
55299: ***WARN***  55300  vs  65533
55300: ***WARN***  55301  vs  65533
55301: ***WARN***  55302  vs  65533
55302: ***WARN***  55303  vs  65533
55303: ***WARN***  55304  vs  65533
55304: ***WARN***  55305  vs  65533
55305: ***WARN***  55306  vs  65533
55306: ***WARN***  55307  vs  65533
55307: ***WARN***  55308  vs  65533
55308: ***WARN***  55309  vs  65533
55309: ***WARN***  55310  vs  65533
55310: ***WARN***  55311  vs  65533
55311: ***WARN***  55312  vs  65533
55312: ***WARN***  55313  vs  65533
55313: ***WARN***  55314  vs  65533
55314: ***WARN***  55315  vs  65533
55315: ***WARN***  55316  vs  65533
55316: ***WARN***  55317  vs  65533
```

**Comment by lrhn** [comment]
This is working as intended.

That code points being warned about here are unpaired surrogates, in the range U+D800 through U+DFFF, which are not allowed as part of valid UTF-8 encodings.

The code point you get instead, is U+FFFD, the "replacement character" used to replace invalid characters. That's not avoidable, you simply cannot encode an unpaired surrogate as UTF-8. (The extension to UTF-8 which allows that is often called WTF-8. That's not what Dart's `Utf8Encoder` allows.)

You should only test with *scalar values*, not code points ("scalar values" are all code points except surrogates), because only scalar values can be encoded as UTF-8:
```dart
var original = [for (var i = 0; i <= 0x10FFFF; i++) if (i < 0xD800 || i >= 0xE000) i];
// ...
```
The `String.fromCharCodes` accept both code units and code points, and Dart strings allow unpaired surrogates, so it only becomes a problem when you try to convert. 
And `String.fromCharCodes` is not unique, you can have two different arguments that create the same string, like `[0xD800, 0xDC00]` and `[0x10000]`. So it's not entirely surprising that what you get out of `.runes.toList()` isn't necessarily the same list you put into `String.fromCharCodes`, even if there were no unpaired surrogaes.

There is one other issue with the test, also related to the unpaired surrogates.
If you insert:
```dart
  print(original.length.toRadixString(16)); // 10ffff
  print(utf8.length.toRadixString(16)); // 10fffe
```
you can see that the two lists are not even the same length. 
That's because the input contains the char code sequence `... 0xDBFE, 0xDBFF, 0xDC00, 0xDC01, ...`, and the middle two "character codes" is actually a *surrogate pair*, which are encoded and decoded correctly as a single code point ("rune") in the result. Which is why everything is off-by-one after that.

Consider this test instead:
```dart
import "dart:convert";

void main() async {
  var codec = Utf8Codec(allowMalformed: true);

  var charCodes = [
    for (var i = 0; i <= 0x10FFFF; i++)
      if (i < 0xD800 || i >= 0xE000) i
  ];
  var original = String.fromCharCodes(charCodes);

  var roundtrip = codec.decoder.convert(codec.encoder.convert(original));

  print(original.length == roundtrip.length); // True
  print(original == roundtrip); // True
  for (var i = 0, ito = original.runes.iterator, itr = roundtrip.runes.iterator;
      ito.moveNext() && itr.moveNext();
      i++) {
    var or = ito.current;
    var rr = itr.current;
    if (or != rr) {
      print("$i: ${or.toRadixString(16)} vs ${rr.toRadixString(16)}");
    }
  }
}
```
If you remove the `if (i < 0xD800 || i >= 0xE000)`, you will see that it reports only the unpaired surrogates as differing.
