### ISSUE TITLE
pkg/dds/test/devtools_server/ tests on unittest-asserts-release-mac-arm64 meta-flaking

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52599]
https://dart-ci.firebaseapp.com/#showLatestFailures=false&configurations=unittest-asserts-release-mac-arm64

unittest-asserts-release-mac-arm64
Pass -> RuntimeError (expected Pass)
pkg/dartdev/test/commands/info_macos_test
Pass -> Timeout (expected Pass)
pkg/dds/test/devtools_server/bind_test
pkg/dds/test/devtools_server/devtools_server_path_strategy_test
pkg/dds/test/devtools_server/embedding_test
pkg/dds/test/devtools_server/remote_control_test
pkg/dds/test/devtools_server/server_connection_api_test
pkg/dds/test/devtools_server/service_registration_test

These tests have been flipping back and forth the last couple of days creating work for gardeners.

@bkonyi could you please take a look what is going on here?

**Comment by bkonyi** [comment]
These all seem to have failures associated with `package:dap`:

`pkg/dds/lib/src/dap/progress_reporter.dart:5:8: Error: Not found: 'package:dap/dap.dart'`

**Comment by bkonyi** [comment]
FYI @helin24

**Comment by helin24** [comment]
I ran these tests locally on Mac to try to debug, but they consistently pass for me.

This is an example of what I ran:
```
~/Documents/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-mac-arm64 --ignore-unrecognized-flags --packages=.dart_tool/package_config.json pkg/dds/test/devtools_server/devtools_server_path_strategy_test.dart
```

@athomas Ben mentioned you may be able to help. The errors coming up during automated testing are related to the new package dap not being found (e.g. [a bind_test.dart result](https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/8294/pkg/dds/test/devtools_server/bind_test)). Could there be something different about how/when the automated system is resolving packages? Anything else you notice that could be a problem?

**Comment by alexmarkov** [comment]
`pkg/dds/test/dap/integration/debug_breakpoints_test` also failed with `Timeout` on `pkg-win-release` bot:

https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/25061/pkg/dds/test/dap/integration/debug_breakpoints_test

**Comment by helin24** [comment]
@alexmarkov @sstrickl I'm not sure if this is related to the original issue here if this is happening on windows. The original issue was due to a reverted commit that generated a new `package_config.json` file + our test not specifying a file + the mac test running machines not refreshing as often as other machines.

If I'm reading the log correctly, the test is hanging because it's expecting breakpoints but didn't receive them?

**Comment by sstrickl** [comment]
Reapproving the `pkg/dds/test/dap/integration/debug_breakpoints_test` Timeout on `unittest-asserts-release-win`.

**Comment by helin24** [comment]
@DanTup I wonder you might be able to help with this issue since you wrote the `debug_breakpoints_test.dart` initially. The latest test flakes on windows seemed to start on May 19 but more rapidly after June 7. They could be related to the addition of the `dap` package but timing doesn't quite line up.

**Comment by dcharkes** [comment]
Reapproved with log https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/25115/pkg/dds/test/dap/integration/debug_breakpoints_test.

**Comment by derekxu16** [comment]
reapproving again: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8777663565789760801/+/u/test_results/new_test_failures__logs_
