### ISSUE TITLE
[Process] Should check that changes to stable include a changelog update. 

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#52626]
When submitting cherry-pick request to the stable channel, CL authors should include an update to CHANGELOG.md. 

There should be a presubmit check that ensures that there is an update to CHANGELOG.md before the change is mergable.  

CC: @athomas

**Comment by sortie** [comment]
This is feasible with the tech we have, I believe. At least I think the submit requirements might be able to do it. We can add a trailer to opt out of it for any special infrastructure changes. Even the tools/VERSION commit itself also usually changes CHANGELOG.md, except on release retriggering (but we could touch it too).

Do we want to require our developers to write these changelist entries? That's a question for you or leads. I think we should because they have the most context to explain the changes, which release people like us simply don't have. The developers will likely need some guidance on how to write them.

I'll just cook up a submit requirement to test this out :)

**Comment by sortie** [comment]
I implemented this logic in https://dart-review.googlesource.com/c/sdk/+/307920 although only EngProd is able to perceive the refs/meta/config branch and I'm slightly unclear if the path: proposition works in submittableIf.

```
[submit-requirement "Changelog"]
	description = "Stable cherry-picks must explain the changes in CHANGELOG.md"
	applicableIf = branch:stable
	submittableIf = path:CHANGELOG.md OR hasfooter:ChangelogExempt
```

**Comment by sortie** [comment]
https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel will also need to be updated to tell our developers that they must write CHANGELOG entries for stable.
