### ISSUE TITLE
JS Interop external function types and allowInterop

### ISSUE THREAD

**Issue by KealJones** [dart-lang/sdk#52628]
`@staticInterop` fields declared using `external` are automatically converted to the equivalent of a getter using `js_util.getProperty` and setter using `js_util.setProperty` which is a great help and simplifies interop alot but one thing that makes it less awesome is when using a `Function` typed `external` field, ddc will throw a runtime error when setting it with an Dart Function that is not wrapped in `allowInterop`: `"Dart function requires allowInterop to be passed to JavaScript."`. 

I was curious if it was or ever would be considered to automatically do `allowInterop` wrapping for `external` fields typed as a `Function` type or maybe even as an opt in via an annotation on the field or something? also not just for `@staticInterop` but the upcoming inline class as well?

**Comment by srujzs** [comment]
We're thinking about similar things here. :) One current idea going forwards is to disallow `Function` (and even `Object` and `dynamic`) on `external` signatures when using `dart:js_interop`, so that users have to use `dart:js_interop`'s `JSFunction` in the future. This gives you a static signal that the Dart function you are passing to JS needs to be wrapped so that it can be used in JS.

The other alternative, like you mentioned, is allowing `Function`, and then doing a runtime conversion as needed. The downsides to that is 1) you don't have control over whether you want to wrap the Dart function or export it as a Dart reference, since we'll always wrap and 2) a slight performance overhead to check every object.

And yes, we plan on applying these changes to both `@staticInterop` and inline classes. We'll gate the semantics based on whether you use `dart:js_interop` or `package:js` to avoid a breaking change.
