### ISSUE TITLE
Equality using records with list components.

### ISSUE THREAD

**Issue by ryosoul** [dart-lang/sdk#52630]
Hello guys,

I maybe find a issue using records with list components like bellow code:

 ```dart
void main() {
  final a = (1,2,[1]);
  final b = (1,2,[1]);
  print(a == b);  // print's false
}
```

Based on the [documentation](https://dart.dev/language/records#record-equality) I was expecting  the result to be true.
There's some thing I missed or is it a bug?

Best regards.

**Comment by eernstg** [comment]
There is a library, [DeepCollectionEquality](https://api.flutter.dev/flutter/package-collection_collection/DeepCollectionEquality-class.html), which will compute the equality of collections based on some base equality relation. You could use a wrapper class in order to change the meaning of `==` for the lists (and you could use DeepCollectionEquality to implement that operator `==`):

```dart
class DeepEqualityOnList<X> {
  final List<X> list;
  DeepEqualityOnList(this.list);

  // Implement structural equality.
  operator ==(other) => ...;
  get hashCode => ...;
}

void main() {
 final a = (1,2,DeepEqualityOnList([1]));
 final b = (1,2,DeepEqualityOnList([1]));
 print(a == b);  // Prints 'true'.
}
```

If you do this then you'd need to use `myRecord.$3.list` rather than `myRecord.$3` in order to get hold of the actual list.

Alternatively, you could use a [`BuiltList`](https://pub.dev/documentation/built_collection/latest/built_collection/BuiltList-class.html) rather than a plain `List`. A `BuiltList` is immutable and it has structural equality.
