### ISSUE TITLE
[analyzer/inline-classes] Missing warning.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#52674]
As expected, the following code does not compile successfully, but the analyzer does not report any errors:

```dart
void main() {
  print(BadInt(0).j);
}

inline class BadInt {
  int i;
  
  BadInt(this.i);
  
  int j = 0;
}
```

```
Error compiling to JavaScript:
lib/main.dart:2:19:
Error: The getter 'j' isn't defined for the class 'BadInt'.
  print(BadInt(0).j);
                  ^
Error: Compilation failed.
```

Reproducible on DartPad

```
master channel
Use Flutter version 3.12.0-2.0.pre and Dart version 3.1.0-169.0.dev
+ Dart experiments: --enable-experiment=inline-class
```

[Edit, eernstg: Add subtask list]

- https://github.com/dart-lang/sdk/issues/52675
- https://github.com/dart-lang/sdk/issues/52676

**Comment by eernstg** [comment]
We should get a compile-time error for `i` and for `j` because they are not final, and we should get a compile-time error because there is more than one instance variable in an inline class.

The analyzer does not report any errors, and the common front end reports one error which isn't any of the expected ones.

@scheglov, @johnniwinther, is this covered by existing issues or ongoing work? Is there a need to create two issues, one for the analyzer and one for the CFE?

**Comment by scheglov** [comment]
I don't work on inline classes.
@bwilkerson, @srawlins for planning.

**Comment by johnniwinther** [comment]
The work is not shared so it's probably best to have two issues.

**Comment by eernstg** [comment]
Thanks, @scheglov and @johnniwinther, I created https://github.com/dart-lang/sdk/issues/52675 and https://github.com/dart-lang/sdk/issues/52676 to cover the analyzer and the CFE, respectively.

@bwilkerson, @srawlins: Planning should then occur in https://github.com/dart-lang/sdk/issues/52675.

**Comment by modulovalue** [comment]
The inline class experiment has been replaced with extension types.
