### ISSUE TITLE
[ffi] isLeaf changes the value returned by calling lookupFunction.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#52696]
For context see: https://github.com/dart-lang/sdk/issues/52692

@dcharkes setting isLeaf to true improves the performance by almost 50%. However, calling the result of lookupFunction appears to return a different value when isLeaf is set to true. Is that expected?

```asm
.p2align 2
.global _popcount
_popcount:
    // TODO
    mov x0, x1
    ret
```

```
 * Writing file to: /Users/modulovalue/Desktop/hello_assembly/hello_assembly/bin/popcount/output/hello_dylib.s'
 * Running command: 'as -arch arm64 /Users/modulovalue/Desktop/hello_assembly/hello_assembly/bin/popcount/output/hello_dylib.s -o /Users/modulovalue/Desktop/hello_assembly/hello_assembly/bin/popcount/output/hello_dylib.o'
 * Running command: 'clang -current_version 1.0 -compatibility_version 1.0 -dynamiclib -o /Users/modulovalue/Desktop/hello_assembly/hello_assembly/bin/popcount/output/hello_dylib.dylib /Users/modulovalue/Desktop/hello_assembly/hello_assembly/bin/popcount/output/hello_dylib.o'
```

```dart
void run(
  final DynamicLibrary dylib,
) {
  final popcount_leaf =
      dylib.lookupFunction<Uint32 Function(Uint32), int Function(int)>(
    'popcount',
    isLeaf: true,
  );
  final popcount_notleaf =
      dylib.lookupFunction<Uint32 Function(Uint32), int Function(int)>(
    'popcount',
    isLeaf: false,
  );
  print(popcount_notleaf(100000));
  print(popcount_leaf   (100000));
}
```

outputs: 
```
100000
43032064
```

on: `Dart SDK version: 3.1.0-163.1.beta (beta) (Wed Jun 7 05:06:41 2023 -0700) on "macos_arm64"`

**Comment by dcharkes** [comment]
> However, calling the result of lookupFunction appears to return a different value when isLeaf is set to true. Is that expected?

Your function signature takes one integer and returns one integer.

The calling convention in C on MacOS is to pass the argument in x0 and return the value in x0.

https://github.com/dart-lang/sdk/blob/0f6e13a220b8e8e1f06d439250ef473d0caf78d6/runtime/vm/constants_arm64.cc#L33

https://github.com/dart-lang/sdk/blob/0f6e13a220b8e8e1f06d439250ef473d0caf78d6/runtime/vm/constants_arm.h#L730

Therefore, x1 is undefined.

You can explore calling conventions with https://github.com/dart-lang/sdk/blob/0f6e13a220b8e8e1f06d439250ef473d0caf78d6/runtime/vm/constants_arm64.cc#L33

The fact that it works without isLeaf is likely due to somehow the x1 register also being populated with the first argument (maybe the Dart compiler shuffles some values around right before the FFI call).

If you're going to write assembly by hand, it needs to follow the C ABI.

Nit: you're using int32_t while using x registers, w registers are 32 bits wide. So your move is copying the upper 4 bytes as well.

**Comment by modulovalue** [comment]
So everything that violates the established calling conventions is undefined behavior and not a bug, got it. Thank you for your help.
