### ISSUE TITLE
Analyzer does not detect usage of void in record

### ISSUE THREAD

**Issue by julemand101** [dart-lang/sdk#52759]
After seeing https://github.com/dart-lang/language/issues/3157 it looks like the analyzer currently fails to report the usage of `void` in a Record while the compiler is not quite happy about such a thing.

The following piece of code is allowed by the analyzer but fails when trying to run with VM or compile to an exe:
```dart
void main() {
  void test;
  print((test,));
  processLifecycle();
}

void processLifecycle() => (create(), update(), dispose());

void create() {}
void update() {}
void dispose() {}
```

Error from compile (nearly the same output when running with `dart`):
```
> dart compile exe .\stack1.dart
stack1.dart:3:10: Error: This expression has type 'void' and can't be used.
  print((test,));
         ^
stack1.dart:7:29: Error: This expression has type 'void' and can't be used.
void processLifecycle() => (create(), update(), dispose());
                            ^
stack1.dart:7:39: Error: This expression has type 'void' and can't be used.
void processLifecycle() => (create(), update(), dispose());
                                      ^
stack1.dart:7:49: Error: This expression has type 'void' and can't be used.
void processLifecycle() => (create(), update(), dispose());
                                                ^
Error: AOT compilation failed
Generating AOT kernel dill failed!
```

Dart SDK Version:
```
Dart SDK version: 3.1.0-227.0.dev (dev) (Sun Jun 18 18:21:21 2023 -0700) on "windows_x64"
```

**Comment by lrhn** [comment]
As specified, a `void` expression can only occur in a selected few syntactic positions. The records feature did not add any new positions, so the "record field value expression" position should not allow a `void` expression.

(The record specification should probably have said so explicitly, because it's so easy for an implementor to forget otherwise, they actually have to write a check for every position where `void` is disallowed, and do nothing where it's allowed. Let's remember that for future new syntactic positions.)

**Comment by bwilkerson** [comment]
@scheglov
