### ISSUE TITLE
Inline class instances can be erroneously assigned to the representation type variable

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#52786]
Is following an intended behavior?

```dart
inline class Id /* do not implement int */ {
  final int value;
  Id(this.value) : assert(value > 0);
}

Id id = -1 as Id; // No compile-time/ runtime error
```

DartPad Based on Flutter 3.12.0-3.0.pre Dart SDK 3.1.0-171.0.dev

**Comment by a-siva** [comment]
Appears to be a problem in the const expression evaluation in CFE.
The following code asserts correctly
```
inline class Id /* do not implement int */ {
  final int value;
  Id(this.value) : assert(value > 0);
}

Id id = Id(-1);

main() {
  print(id);
}
```

**Comment by lrhn** [comment]
This is working as intended.

The current proposal spec for inline classes erases the inline class types at runtime, making them effectively be aliases for the representation type.
That means that the line `Id id = -1 as id;`, which is type valid since an `as` can never fail statically, will at runtime behave exactly as `int id = -1 as int;`, which obviosuly succeeds.

You can always cast any member of the representation type to the inline class type, and casts do not invoke constructors.

An inline class type *cannot* prevent some values of the representation type from becoming the representation value, it can only guide users through providing constructors, but it's no guarantee. 
Nothing will stop `List<Id> ids = [-1] as List<Id>; Id id = ids.first;` from running either.
