### ISSUE TITLE
Flow analysis in "if case" does not recognize exhaustive matching of sealed classes

### ISSUE THREAD

**Issue by Quijx** [dart-lang/sdk#52830]
The flow analysis does not recognize that an if case statement is always matched by a pattern exhausting sealed classes. For example:

```dart
sealed class Foo {}

class Bar extends Foo {}

int ifCase(Foo f) {
 // ^ The body might complete normally, causing 'null' to be returned, but the return type, 'int', is a potentially non-nullable type.
  if (f case Bar()) {
    return 1;
  }
}

// Works fine.
int switchStatement(Foo f) {
  switch (f) {
    case Bar():
      return 1;
  }
}
```
Here the switch statement sees that every path leads to the return, but the if statement does not.

While it seems pointless to write an if statement that is always fulfilled, i was considering to use this to promote the type without a cast, that could fail at runtime when another subclass of `Foo` is added eventually.

**Comment by lrhn** [comment]
Flow analysis doesn't detect exhaustiveness at all, it defers to the (slightly later) exhaustiveness analysis in cases where exhaustiveness is required. Which means that the flow analysis cannot determine exhaustiveness except in very trivial cases.
Exhaustiveness analysis is only applied to switches, so the `if` wouldn't be tested with that.

Because of that,  you do indeed need to use a `switch` to get exhaustiveness checking, even if it's a one-case switch.
