### ISSUE TITLE
No error if inline class implements another class with private instance variable from another library

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#52842]
The following code produces no issues in both CFE and analyzer
```dart
// inline_class_lib.dart
library inline_class_lib;

inline class LibraryInlineClass {
  final int _x = 0;

  int get val => _x;
}

// test.dart
import "inline_class_lib.dart";

inline class IC implements LibraryInlineClass {
  final int id;
  IC(this.id);
}

main() {
  var ic = IC(1);
  print(ic.val); // prints 1. 
}
```

According to the inline classes [specification](https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md)

> A compile-time error occurs if the inline class does not declare any instance variables, and if it declares two or more instance variables

There are no exceptions for classes with private variables from another library. So, I believe, there should be a compile-time error

cc @eernstg to confirm

Tested on the edge SDK (July 4-th 2023) on Linux x64

**Comment by eernstg** [comment]
I can't see any reason why we should have an error here: The two inline class declarations are connected by `implements`, which arguably does have a non-standard meaning for inline classes, but it is still so similar to `implements` for classes that we can safely say: `LibraryInlineClass` declares exactly one instance variable `_x`, and `IC` declares exactly one instance variable `id`, and `IC` does not inherit an instance variable because the connection is `implements`. So each of them has exactly one instance variable.

It is true that we have some subtle rules about the management of interfaces of classes and mixin when they contain private names. So maybe we have an issue with the fact that `_x` is private?

This implies that `LibraryInlineClass` has an implicitly induced getter named `_x`, and that getter is usable with a receiver whose type is `IC`, but only in the library that declares `_x`.

We don't require that a concrete class must implement private members from other libraries (because there's no way they could do that anyway). With inline classes it's even more extreme: We never require that an inline class must implement any members because they are "abstract": If any super-interface has a member signature then they also have an implementation. So we just require that conflicts are resolved, and if there's no conflict then we inherit the implementation. In this particular case we can't _denote_ the member `_x`, but that's not an error.

So did I forget something?

**Comment by sgrekhov** [comment]
The value of `_x` is `0`, but `val` getter returns `1`. Let's change the example frome the above a bit
```dart
// inline_class_lib.dart
library inline_class_lib;

inline class LibraryInlineClass {
  final String _x = "X";

  String get val => _x;
}

// test.dart
import "inline_class_lib.dart";

inline class IC implements LibraryInlineClass {
  final int id;
  IC(this.id);
}

main() {
  var ic = IC(1);
  ic.val.substring(0); // NoSuchMethodError: Class 'int' has no instance method 'substring'.
}
```
This code produce a runtime error in VM. In analyzer it has only
```
  error • syntax_A03_t06.dart:32:14 • Missing concrete implementation of 'getter LibraryInlineClass.val'. Try implementing the missing method, or make the
          class abstract. • non_abstract_class_inherits_abstract_member
```
I guess that the analyzer error is simply non-fully implemented `inline class` feature. But VM behaviour looks odd

**Comment by eernstg** [comment]
> The value of `_x` is `0`, but `val` getter returns `1`

You can't trust that even though `_x` is declared to be initialized to 0. When we have an expression of type `LibraryInlineClass` we could have obtained it from `myInt as LibraryInlineClass`, and in that case the representation object is going to be the value of `myInt`. In this particular case the reason is different, but still somewhat similar:

The unique instance variable of an inline class will provide access to the representation object, and the representation object does not change when we're executing an inline class instance member which is declared by an inline type superinterface. So we're running the body of `val` in a situation where the representation object is 1, and hence the getter of `_x` returns 1.

The `String`/`int` example is an error: An inline class `V` cannot have an `implements V2` relation where `V2` is an inline class unless the representation type of `V` is a subtype of the representation type of `V2`.

This is exactly the requirement that we have to have in order to ensure that it is type correct for the members of `V2` to run in a situation where the representation object `o` is the representation object for `V`: When `o is R` and `R <: R2` then we also have `o is R2` (where `R` is the representation type for `V` and `R2` is the representation type for `V2`).

**Comment by lrhn** [comment]
Agree with Erik. This is because inline classes are not _actually_ classes.

> The value of `_x` is 0,

As you show, it's not. 
Or rather, there is no field. (Insert Matrix meme.)

The `final int _x = 0;` declaration doesn't *really* declare a field, it cannot since there is no memory allocated for it. It's actually just a getter of the form `int get _x => this as int;`.

The ` = 0` "works" in that it allows a default constructor looking like `LibraryInlineClass();`, but actually working as `factory LibraryInlineClass() => 0 as LibraryInlineClass;`.

Calling `IC(1)` effectively does `1 as IC`, then you get to call `ic.val` on it, which does `1 as int`, and you got exactly what you should.

(And at runtime, after erasing all the inline classes, what happens is just `int ic = 1; print(ic);`.)
