### ISSUE TITLE
Failures on [vm] Attempt to avoid allocating non-Ptr fields with Object::null().

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52910]
There are new test failures on [Bump linter to 655de5d0dc30cdd1df9ce4cd16bd7489106d987f...Remove duplicate getters from ClassDeclaration and MixinDeclaration.](https://github.com/dart-lang/sdk/compare/2c97bd7801724dc9b95f39f3a88a9112f0287e5a~...23f414520647df3719da1a94f19237955a0f5fc2).

The tests
```
corelib/list_removeat_test RuntimeError (expected Pass)
corelib_2/list_removeat_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-debug-x64
dartkp-linux-release-x64
dartkp-weak-asserts-linux-release-x64
```

https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-x64/dartkp-weak-asserts-linux-release-x64/15730/corelib/list_removeat_test

Bisected locally:

Bisecting 23f41452064...e1c12b3ab2e (25 commits). Trying 453fce9e77f.
Commit 453fce9e77f, reproduces failure.
Bisecting 453fce9e77f...e1c12b3ab2e (13 commits). Trying 0d47ba68902.
Commit 0d47ba68902, reproduces failure.
Bisecting 0d47ba68902...e1c12b3ab2e (7 commits). Trying 2f63acea22a.
Commit 2f63acea22a, reproduces failure.
Bisecting 2f63acea22a...e1c12b3ab2e (4 commits). Trying 81df36216fe.
Commit 81df36216fe, does not reproduce failure.
Bisecting 2f63acea22a...a0392698bf7 (2 commits). Trying a0392698bf7.
Commit a0392698bf7, does not reproduce failure.
Bisected to 2f63acea22a.

**Comment by sstrickl** [comment]
Oh wait, this is with `--no-sound-null-safety` enabled, which means that the dynamic invocation forwarders generated for `removeAt` won't disallow `null` as an `int`, and so of course `null` will make it through to the body.

... so I need to figure out why the bad call to `<` is throwing a `NoSuchMethod` error instead of a `ArgumentError`.

**Comment by sstrickl** [comment]
Just to note, the original exception thrown before that CL by the same code is:
```
Unhandled exception:
RangeError (length): Invalid value: Not in inclusive range 0..4: 139679986385025
#0      List.removeAt (dart:core-patch/growable_array.dart)
#1      testModifiableList (file:///usr/local/google/home/sstrickl/dart/sdk/bar.dart:31)
#2      main (file:///usr/local/google/home/sstrickl/dart/sdk/bar.dart:36)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

**Comment by sstrickl** [comment]
Okay, got it, and it's kinda ridiculous.

What's happening is that we're non-speculatively unboxing the argument as an Int64 first thing in the function, so either it's a `Smi` or it's a boxed value in which case we retrieve the `value` field offset assuming it's a `Mint` and continue... but it's not a `Mint`, it's `null`.

Before, the contents of `null` after the header tags would have been initialized with its own address.  Now it's instead initialized with `0`. Which in theory wouldn't make a difference since nothing should be looking at the contents of the `null` object... but that `UnboxInt64` instruction? It thinks it has a `Mint(0)`. 🤦‍♀️ 

And so what's happening is the inlined `<` call in the optimized method first checks that the unboxed argument is smaller than the length of the array, and _then_ it checks the parameter for `null`, which will throw `NoSuchMethod` if found. So before, we'd get a range error because the address of `null` as an 64-bit integer is definitely larger than the length of the five element array in the test, but now it's not, so it then falls through to the null check before continuing which then goes "Oh, wait a minute, this is `null`, and `null` doesn't know how to `<`, so ignore that value I just got and throw `NoSuchMethod`."

I can make a quick CL to reinitialize the contents of `null` with its own address (easy enough to do) for now, but I think the current expected behavior in that test is wrong, especially since the address of `null` is a valid 64-bit integer (the `139679986385025` in the error above), which means the behavior after the CL is _more_ correct than the one before it (throwing a range error by happenstance).

/cc @mkustermann what's your thoughts about this?

**Comment by sstrickl** [comment]
#52912 is the same issue, but even worse because there's no null check that happens to catch the mistake before the `null` value is used as if it was a `0` boxed as a `Mint`.

**Comment by sstrickl** [comment]
Alternatively, all these issues only happen when you turn off null safety... so we could just say "yep, that's what you get for turning off that protection nowadays".

**Comment by sstrickl** [comment]
So after discussion, we should fix whatever isn't checking for `--no-sound-null-safety` to either insert or not remove null checks.

So what I'm going to do is make it so that the `null` object gets its post-header body initialized with `null` like before as a special case as a stop-gap, and then I'll look into finding where we're losing the chance to check it appropriately.
