### ISSUE TITLE
VSCode Liveshare causes dartanalyzer process to spin at 100%+ CPU

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#52952]
STEPS TO REPRODUCE

0. Install the [VSCode Live Share extension](https://code.visualstudio.com/learn/collaboration/live-share) on machines A and B (in our case, a Windows 10 machine and a macOS machine respectively).
1. Create a Dart project in VSCode on machine A.
2. Open a Live Share connection.
3. Connect to it from machine B.

EXPECTED RESULTS

Machine B should be idle.

ACTUAL RESULTS

Machine B has dartanalyzer spinning at 100%+ CPU. It seems (based on looking at what files it has open) like it might be reading every file on the disk?

**Comment by bwilkerson** [comment]
@DanTup

**Comment by DanTup** [comment]
@Hixie I haven't been able to repro this with my MacBook as the host (Windows as guest). I haven't been able to get a connection the other way around (I've filed https://github.com/MicrosoftDocs/live-share/issues/4953).

A few questions:

- which direction was your connection? (or does it happen in both directions?)
- does it repro with a new project created with **Flutter: New Project**
- were you using the same MS/GitHub account for Live Share on both machines? (I was)
- which SDK versions are you using (I'm guessing a relative up-to-date Flutter master?)
- if you open your VS Code user settings (**Preferences: Open User Settings Json**), are there any Dart settings you have that might affect how the LSP server works (for example `onlyAnalyzeProjectsWithOpenFiles`?)

What should happen, is that any workspace folder or open files that come via live-share have their own (non-file://) scheme, and the server should just ignore them.

> It seems (based on looking at what files it has open) like it might be reading every file on the disk?

Just to clarify - this high CPU is on the guest? If so, what files is it reading? In a remote session, I would expect the files to only exist on the host (except in any caching live share is doing), so if it's reading files on the guest, what do these paths look like?

**Comment by DanTup** [comment]
I did trigger an exception while trying to repro this - but I'm not sure if it's related (I don't see high CPU). I've filed https://github.com/dart-lang/sdk/issues/52986 to investigate (assuming it's a different issue for now).

**Comment by DanTup** [comment]
It turns out the two issues were related. The issue is that the Live Share root `vsls:/` was being mapped to `file:///` so it was indeed scanning the whole disk. The reason I didn't see high CPU and hit an exception was because I had a test project I'd been using to test a server crash and that prevented it going further.

I've pushed a fix to the pre-release channel of the VS Code extension (v3.69.20230719) which should show up in the next 20 mins or so. Please test that the issue no longer exists with this version (specifically, you need this version on the guest machine, and to have reloaded after installing it).

<img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">

Please let me know if you hit any issues. Thanks!

**Comment by Hixie** [comment]
Wow that's awesome! Such a quick turnaround on what I was assuming was an impenetrable bug! Thanks!

**Comment by DanTup** [comment]
np! Where you able to confirm that it did solve the issue for you?

**Comment by Hixie** [comment]
I have not seen the problem since!

**Comment by DanTup** [comment]
Great, thanks for confirming! The fix should go into the stable release approximately tomorrow, although I generally recommend Dart/Flutter team members stick on the pre-release version for some extra testing/bug reporting before stable releases. It's still a manual release I push (not just automated from latest code) so it should be pretty stable :-)
