### ISSUE TITLE
IncrementalMarkWithSizeBudget and Dart_NotifyDestroyed may trigger GC, leading to UI thread freeze

### ISSUE THREAD

**Issue by yeran1212** [dart-lang/sdk#52978]
Dart SDK version: 3.1.0-322.0.dev (dev) (Mon Jul 17 21:03:12 2023 -0700) on "macos_x64"

1.For low level machine，IncrementalMarkWithSizeBudget will be triggered frequently ,  which can result in jank.
![image](https://github.com/dart-lang/sdk/assets/77652483/8147f536-5b9f-41e8-b431-281e8292fcd7)

2. Dart_NotifyDestroyed will trigger GC which delay first frame when application frequently switch between flutter view and android view. I am curious whether Dart_NotifyDestroyed is suitable for hybrid development scenarios
Similarly issue has been mentioned here https://github.com/flutter/engine/pull/43587

The test device: Xiaomi 6

**Comment by a-siva** [comment]
//cc @rmacnak-google

**Comment by a-siva** [comment]
With regards to 1 is it possible to provide some reproduction scenarios so we can evaluate if there is an accounting bug resulting in frequent GCs

For the second issue we do trigger a GC when switching between the Flutter view to Android view because the assumption is that the flutter view is going to the background and the app does not need to hold on to memory. Maybe as suggested in the other issue the engine could have a mode to not invoke Dart_NotifyDestroyed in these scenarios.
