### ISSUE TITLE
Issue with Ternary Expression and Generic Return Types

### ISSUE THREAD

**Issue by maRci002** [dart-lang/sdk#52984]
```dart
abstract class A<T extends Object> {}

class B extends A<B> {}

class C extends A<C> {}

// A value of type 'Object' can't be returned from the function 'foo' because it has a return type of 'A<Object>'.
A get foo => true ? B() : C();

// ok
A get bar {
  if (true) {
    return B();
  }

  return C();
}
```

**Comment by lrhn** [comment]
This is a well known property of the upper-bound calculation used to find the type of `true ? B() : C()`.
The types `B` and `C` share no interface other than `Object`, so that's the solution.
The algorithm only looks in declared superinterfaces, not among any supertypes, so the only types it can try to find the upper bound amongst are `B`, `C`, `A<B>`, `A<C>` and `Object`. The only one which is a supertype of both `B` and `C` is `Object`.

It's a common issue, already traced elsewhere (probably in many places, mostly in the language repository).
Safe to say, we're aware of it.
