### ISSUE TITLE
Should tags on beta/stable cherry-picks be visible on the commit in github?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#52999]
Not sure if this is possible to do or if this is a github issue directly. In a recent discussion in https://github.com/dart-lang/sdk/issues/52869#issuecomment-1642891707 we noticed that a commit was not visibly marked as part of a release in the github commit. In particular, take for example the most recent beta release here: https://github.com/dart-lang/sdk/commits/3.1.0-262.2.beta

You can find the cherry-pick https://github.com/dart-lang/sdk/commit/1b6421ac0ba6e5196b58bce150495d872433151d which indicates it landed in the beta branch, but it doesn't show the git tag 3.1.0-262.2.beta. Compare that to a commit from the main branch that didn't get cherry-picked, like: https://github.com/dart-lang/sdk/commit/63b567add21a9c6a74dae44a13f0588f2fd50e78, where the tag is present in the UI.

cc @athomas @itsjustkevin @nshahan

**Comment by athomas** [comment]
Looks like a GH UI issue, because in a local checkout the tag is listed for 617922293bd00069307a417b621885e72d3b3e71
```
$ git tag --contains 617922293bd00069307a417b621885e72d3b3e71
3.1.0-262.2.beta
```

But [3.1.0-262.2.beta ](https://github.com/dart-lang/sdk/releases/tag/3.1.0-262.2.beta) is known to GH. So they've likely decided to only show tags that are reachable from main for some reason.

https://github.com/refined-github/refined-github might be another workaround.

Looking at https://dart.googlesource.com/sdk/+log/beta is also a good way to see this for recent commits at a glance.

I'm going to close this, because I don't see a good way for us to do this. It's more of a GH feature request.

**Comment by sigmundch** [comment]
Makes sense. Thanks so much for digging into it!
