### ISSUE TITLE
Why record index origin is $1 and not $0 ?

### ISSUE THREAD

**Issue by pomid** [dart-lang/sdk#53006]
* Common Front End (CFE) and kernel
* Dart SDK Version (`dart ^3.0.0`)

**Comment by lrhn** [comment]
Because it's not an index.

Why do list indexing start at zero instead of one?
Because the C language implemented array indexing as pointer addition, and adding zero gives you the first element from where the pointer points.
And every major language since had been inspired by C. 
Otherwise it's a completely arbitrary choice. I believe some Pascal versions allowed you to define the indices of an array type to start from anywhere.

But array indexes has the property that you can access then with a computed index. They are numbers.

Record fields are not indexable, they are just names. Even the positional ones.

So we looked at how other similar features in Dart behaved, and how other record-like features in other languages worked, and the common theme was that if you had, say, give similarly named parameters or type parameters, you'd make them something's like `o1`, …,`o5`.
And other languages with record like structural types, which are embedded in an object like system, would name the elements something like `item1`,…,`item5`.
And we tried writing code with Dart records, where it felt more natural to stay from 1 than from 0. Things like an extension on a record of 3 elements, where you'd write code like:
```dart
extension E<T1, T2, T3> on (Future<T1>, Future<T2>, Future<T3>) {
   Future<(T1, T2, T3)> get wait async {
      var tmp1 = collectResult($1);
      var tmp2 = collectResult($2);
      var tmp3 = collectResult($3);
      await Future.wait([tmp1.done, tmp2.done, tmp3.done]);
      return (tmp1.value, tmp2.value, tmp3.value);
   }
}
```
Here it felt out of place if the record fields were named `$0`…`$2`, it wouldn't fit the test of the code which naturally used 1…3 to enumerate the types and local variables.

(It's also called `List.first`, not `List.zeroth`.)
