### ISSUE TITLE
How to solve this "Error on line 40, column 3: Duplicate mapping key."

### ISSUE THREAD

**Issue by princeSunil** [dart-lang/sdk#53038]
![Screenshot 2023-07-26 121700](https://github.com/dart-lang/sdk/assets/132480359/4a2ffc1c-af8d-4ae8-8b9f-868b4b78326c)

**Comment by julemand101** [comment]
By not having `speech_to_text` twice in your `dependencies` section? You have it in both places here:
![image](https://github.com/dart-lang/sdk/assets/116227/5e3739f1-1fd5-4198-a681-2438ec840ddd)

If you have it as a path, you don't need to have it with a specific version since the version comes from the path. And if you want to fetch the dependency from pub.dev, you should not specify a path.

**Comment by princeSunil** [comment]
Thanks bro
