### ISSUE TITLE
pkg/modular_test/test/* flaky -> RuntimeError

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#53059]
The tests
```
pkg/modular_test/test/find_sdk_root1_test RuntimeError (expected Pass)
pkg/modular_test/test/find_sdk_root2_test RuntimeError (expected Pass)
pkg/modular_test/test/loader/loader_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac
unittest-asserts-release-win
unittest-asserts-release-linux
```

Example log:
```
--- Command "vm" (took 760ms):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH="/opt/s/w/ir/third_party/browsers/chrome/Google Chrome.app/Contents/MacOS/Google Chrome" xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-mac --ignore-unrecognized-flags --packages=/opt/s/w/ir/.dart_tool/package_config.json /opt/s/w/ir/pkg/modular_test/test/find_sdk_root1_test.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
error: cannot find the root of the Dart SDK
#0      findRoot (package:modular_test/src/find_sdk_root.dart:19:7)
#1      main.<anonymous closure> (file:///opt/s/w/ir/pkg/modular_test/test/find_sdk_root1_test.dart:13:63)
#2      asyncTest (package:async_helper/async_helper.dart:85:11)
#3      main (file:///opt/s/w/ir/pkg/modular_test/test/find_sdk_root1_test.dart:12:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:291:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-mac pkg/modular_test/test/find_sdk_root1_test
```

/cc @sigmundch

**Comment by srujzs** [comment]
Is web-infrastructure the right tag for issues like these?

**Comment by sigmundch** [comment]
Could be web-dev-compiler? We wrote the modular_test framework just to have coverage of modular builds that are so important for DDC. We then leveraged it to start testing modular and sequential dart2js builds as well. So, thus far, only the web backend teams are making use of this framework.

**Comment by sigmundch** [comment]
Seems this is failing due to a change to infrastructure. The test are extremely simple: they are looking at the directory that contains the test file, and they expected to be of the form `some/path/to/sdk/pkg/modular_test/test/...`

Then they look up the `sdk` segment. It seems these bots checked-out the sdk without the sdk folder for some reason

@athomas @whesse is that expected? It is possible to preserve the SDK structure in these runners, or do we need to amend the logic used by these tests somehow?

**Comment by sigmundch** [comment]
Looking at the history: https://dart-ci.web.app/#showLatestFailures=false&test=pkg/modular_test/test/find_sdk_root1_test&configurations=unittest-asserts-release-mac

It appears the flakes/failures started occurring as we started running these tests in shards. Seems the main runner has the right folder name, but that the shards copy the contents of the sdk into a folder that is not named "sdk". I can imagine this being labeled as flaky depending on how the sharding split the tests: if the test was picked up by the main test runner (since it acts as one of the shards) the test would pass, if it was picked up by a shard, it would fail.

**Comment by sigmundch** [comment]
Fix underway: https://dart-review.googlesource.com/c/sdk/+/316642
