### ISSUE TITLE
[analyzer] switch expression isn't exhaustive on a boolean literal

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#53055]
Dart SDK Version: 3.0.4

The following code snippet:
```dart
final foo = switch (true) {
  true => Foo(),
};
```

Produces the following error: `The type 'bool' is not exhaustively matched by the switch cases since it doesn't match 'false'.` I understand this kind of error is exceeding rare in the wild, but still strange nevertheless.

**Comment by laskawiecdenis** [comment]
The error that is displayed is correct, you are using switch on **bool** value so it is expecting to handle both instances of bool.
You can fix it like that.
```dart
final foo = switch (true) {
  true => Foo(),
  false => null,
};
```

**Comment by lrhn** [comment]
Yes, working as intended.

There is no special case for switching on a constant.
There could be, if the constant has primitive equality, then we can allow a constant pattern with the same constant to exhaust it.

It's just not worth the implementation effort. If you do a switch, we'll assume that it's because the value can vary.
Even a compile time constant, it might have a different value in the next compilation
