### ISSUE TITLE
Fail to infer type in multiple conditions

### ISSUE THREAD

**Issue by luisgurmendez** [dart-lang/sdk#53088]
When having multiple conditions in an if statement the analyzer is not able to infer the type even if it is logically correct,
Example: 

```dart
abstract class A{
  String get a;
}

abstract class Base{}

class DoesntImplementsA extends Base{}

class A1 extends Base implements A{
  get a => '';
}


class A2 extends Base implements A{
  get a =>  '';
}

main(){
  Base a = new DoesntImplementsA();
  
  if (a is A1) {
    /// doesnt complains
    a.a;
  }
  
  if ((a is A1) || (a is A2)) {
    /// complains
    a.a;
  }
}

```

https://gist.github.com/luisgurmendez/c5f73b6a3b7dc6cb7425a7e8ae519bfe

In this example both A1 and A2 implements A. So both instances have a `.a` getter. But the analyzer is not being able to infer that.
NOTE: that when checking just for 1 of the instances `if(a is A1)` it does infer the type properly

**Comment by luisgurmendez** [comment]
https://dartpad.dev/?id=c5f73b6a3b7dc6cb7425a7e8ae519bfe

**Comment by lrhn** [comment]
This is working as intended.

The reason `a is A1` allows you to use `a.a` is that the test promotes `a` to the type `A1`.

Promotion is limited to promoting to a subtype, and it requires the test to dominate any code which relies on the promotion.

The test `a is A1 || a is A2` doesn't work like that.
Most importantly, the code in the body is not dominated by either `is` test, because it's possible to reach the body with either test being false.

Now, if both tests would individually promote to the same thing, then maybe we'd be able to combine those into an unconditional promotion. Or maybe not, it's not a common use-case to have two tests with the same result.
In any case, they do not.
After the tests, all we know is that `a` is either `A1` or `A2`, but we cannot promote to a union type, there is no single type that we can use instead, and even if we had tried to promote to the least your bound of `A1` and `A2`, we wouldn't have been able to choose between `A` and `Base`.

So `a` stays unpromoted.
