### ISSUE TITLE
No StateError when adding event/s to unclosed non-broadcast stream controller whose stream is cancelled.

### ISSUE THREAD

**Issue by LewisHolliday** [dart-lang/sdk#53132]
Consider:
```dart
void main() {
  final c = StreamController();
  c.close();

  c.add(0); //throws StateError
}
```

I think the motiviation for this Error is to alert the developer that they are potentially leaking resources, e.g. a timer was not cancelled.

However, consider:
```dart
void main() {
  final c = StreamController();
  c.stream.listen((event) {}).cancel();

  c.add(1);
}
```
In this example, after `.cancel`, the stream cannot receive events, yet the call to add doesn't throw an error.

I propose that the add methods on a non-broadcast stream controller whose stream is cancelled throw a StateError. 
`new StreamController()`'s add methods have one purpose: add events to `.stream`. 

Bonus question: should the call to cancel close the sink?
The factory constructor of StreamController could document this.

**Comment by lrhn** [comment]
The current behavior is intentional.

The owner of the controller should know whether they have called `close` or not. As such, camping `add` after `close` is considered a bug.

The listener is likely not written as part of the same code that creates the events, so while it cancelling _can_ be noticed immediately using an `onCancel` callback, it's too cumbersome in practice to have to check for cancellation all the time. Therefore the event producer is allowed to add events after `cancel`, and to check `StreamController.hasListener` only when it's convenient. The events will be discarded.
