### ISSUE TITLE
Type information lost inside ternary expression

### ISSUE THREAD

**Issue by mdebbar** [dart-lang/sdk#53144]
The following code snippet shows 2 factories that "should be" identical, yet one of them passes analysis while the other one fails:

```dart
bool use1 = true;

abstract class Foo {
  factory Foo() {
    // This works fine!
    if (use1) {
      return FooBar1();
    }
    return FooBar2();
  }
}

abstract class Bar {
  factory Bar() {
    // But this doesn't!
    // Error: A value of type 'Object' can't be returned from the constructor 'Bar' because it has a return type of 'Bar'.
    return use1 ? FooBar1() : FooBar2();
  }
}

class FooBar1 implements Foo, Bar {}

class FooBar2 implements Foo, Bar {}
```
My assumption is that type information is lost inside the ternary expression because `FooBar1` is basically a union of 2 distinct types: `Foo` and `Bar`. So they flow up as the type `Object`.
```
           [Object]
              |
           Ternary
         /         \
  [Object]          [Object]
      |                |
  FooBar1()         FooBar2()
   /     \          /     \
[Foo]   [Bar]     [Foo]   [Bar]
```

**Comment by lrhn** [comment]
This is working as specified.

Each Dart expression has a single static type, and the type of `use1 ? FooBar1() : FooBar2()` is `Object`.

It's not because `FooBar1` is a *union* of `Foo` and `Bar` (it's actually an intersection), but because the algorithm for finding the type of `use1 ? FooBar1() : FooBar2()` tries to find a unique shared supertype of `FooBar1` and `FooBar2`.
It's the "unique" that makes it give up here.

The type hierarchy is:
```
       Object
        /   \
      Foo   Bar
       |  X  |
  FooBar1   FooBar2
```
Because `Foo` and `Bar` are both supertypes, but neither is more important than the other in any way, picking either would be arbitrary. So the algorithm ignores both and goes to `Object`.

**Comment by mdebbar** [comment]
Thanks @lrhn for the explanation!

**Comment by incendial** [comment]
> Because Foo and Bar are both supertypes, but neither is more important than the other in any way, picking either would be arbitrary. So the algorithm ignores both and goes to Object.

But why not to pick `Bar` in this context? Considering that `Bar` is expected to be returned, can this condition mark it as more important?

**Comment by lrhn** [comment]
Yeah, that's a really good question, which was also asked here: https://github.com/dart-lang/language/issues/1618
We're aware of it, but also a little wary about chaning type inference for existing code. 
(But if we know the result will be an error otherwise, ... maybe can do something. It's just a matter of knowing when that is.)
