### ISSUE TITLE
 `Platform.environment` is an unmodifiable map 

### ISSUE THREAD

**Issue by WorikQCI** [dart-lang/sdk#53152]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

* Dart code that depends on, say,  `bool.hasEnvironment("QQQ")` in production
* It cannot be tested because `Platform.environment['QQQ'] = 1; // or whatever value` throws an exception

### Expected results

Set environment variables at test time

### Actual results

Exception is thrown

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:test/scaffolding.dart';
void main() async {
  test("Cannot set environment in a test", () async {
    Platform.environment['QQQ'] = 'foo';

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by mraleph** [comment]
`{bool,String,int}.fromEnvironment` and `bool.hasEnvironment` have nothing to do with `Platform.enviroment`. 

The `fromEnvironment` and `hasEnvironment` methods access _compile time environment_ i.e. values passed to the compiler via `-D` / `--dart-define` flags. Because they are compile time values they can't be configured in runtime. If you want to define these values you need to set them when you invoke tests in your CLI. 

`Platform.environment` accesses OS environment variables - a different thing altogether.

**Comment by WorikQCI** [comment]
The bug is being unable to set those compile time flags at test time

**Comment by mraleph** [comment]
You can't set _compile_ time values in _runtime_ - that is by design. If you want to write tests against the code that heavily depends on compile time constants - you will need to use helper scripts which pass values that you want to `flutter test`.
