### ISSUE TITLE
stdout.writeln should use the current platform new line symbols

### ISSUE THREAD

**Issue by azchohfi** [dart-lang/sdk#53161]
Dart's "Write Line" methods should follow the new-line standard of the platform where it is running.

For example:
```dart
stdout.writeln("abc")
```
Should write 'abc\n' on Linux + MacOS, but 'abc\r\n' on Windows.

This breaks the expectation of other command line tools that expect tools on Windows to return '\r\n' for new lines.
It also makes writing cross-platform console apps with Dart harder, since we can't use the *.writeln helper methods without creating a wrapper helper method ourselves.

Env:
* Dart SDK Version: Dart SDK version: 3.2.0-42.0.dev (dev) (Mon Aug 7 10:46:38 2023 -0700) on "windows_x64"
* Windows

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/320280 should do it but there is some concerns being expressed that this could be a breaking change.

**Comment by azchohfi** [comment]
I agree. It most definitely is a breaking change. Does it mean it will no be approved, or only that it will be batched to a major release?

**Comment by brianquinlan** [comment]
I disagree that, in general, all `IOSink`s should use the platform line ending. `StringBuffer`, for example, should not do line ending translation.

But `stdout.writeln` seems like a case where not using the platform line ending is making `writeln` nearly useless on Windows. I would expect that fixing this on Windows would be minimally breaking.

**Comment by brianquinlan** [comment]
I confirmed the behavior:

```dart
# out.dart
import 'dart:io';

void main() {
  stdout.writeln('This is a test');
}
```

```
> dart .\out.dart >cmdout.txt
> Format-Hex .\cmdout.txt
           Path: C:\Users\brian\Dart\dart-win\samples\stdouteol\cmdout.txt

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   54 68 69 73 20 69 73 20 61 20 74 65 73 74 0A     This is a test.
```

**NOTE:** for those who try to reproduce this, use `cmd.exe` - PowerShell does line ending normalization by default - see [PSNativeCommandPreserveBytePipe](https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommandpreservebytepipe).

**Comment by brianquinlan** [comment]
We are opening stdout/stderr in [binary mode](https://github.com/dart-lang/sdk/blob/554cc8c0027a97670dd3f9f8b3bb9ebe9a37cc8d/runtime/bin/file_win.cc#L517)...

...but changing that to open stdout in text mode doesn't change the output - which is surprising.

**Comment by brianquinlan** [comment]
Change `_StdSink.writeln` to:

```dart
  void writeln([Object? object = ""]) {
    _sink.write(object);
    _sink.write('\r\n');
  }
```
 
Changes the output as expected.

**Comment by brianquinlan** [comment]
I can think of a few approaches to fixing this issue:
1. We change the `stdout` to always do `'\n'` to `'\r\n'` on Windows:
    - this would be breaking
    - there would be no way of working with binary mode stdout
2. We could add a new `bool` property to `Stdout` called `binaryMode` that would enable/disable `'\n'` to `'\r\n'` translation on Windows - it would be `true` by default for backwards compatibility:
   - this would be theoretically breaking - there are [100s of files on github that `implement Stdout`](https://github.com/search?q=%22implements+Stdout%22+lang%3Adart&type=code&p=2) but all them that I looked at use `Fake`/`Mock` or override `noSuchMethod`.
   - this would be somewhat symmetrical with the settable properties of `Stdin` (e.g. `echoMode`, `lineMode`)
3. We could add a new property to `Stdout` called `text` that returns a `IOSink` (or `Stdout`) that does `'\n'` to `'\r\n'` translation on Windows:
   - this would be theoretically breaking - there are [100s of files on github that `implement Stdout`](https://github.com/search?q=%22implements+Stdout%22+lang%3Adart&type=code&p=2) but all them that I looked at use `Fake`/`Mock` or override `noSuchMethod`.
   - this would be somewhat symmetrical with [`Stdout.nonBlocking`](https://api.dart.dev/stable/3.1.0/dart-io/Stdout/nonBlocking.html)
4.  We could leave `Stdout` alone (except for documentation) and add a new class that does line ending conversions like:

```dart
class TextIOWrapper implements StringSink { // Name stolen from Python
   IOSink sink;
   String? lineEnding;

  TextIOWrapper(this.sink, {this.lineEnding));

  void writeln([Object? object = ""]) {
    _sink.write(object);
    _sink.write(lineEnding ?? Platform.lineEnding);
  }  
```

I'd vote for (2).

**Comment by a-siva** [comment]
//cc @lrhn for opinions here

**Comment by lrhn** [comment]
It's tricky. (And I'm not an expert on standard Posix stdout.)

My first idea is to just change `writeln` of `Stdout`, and nothing else.

If you write `"\n"`, or `"\r\n"` with `Stdout.write`, or `Stdout.writeCharCode`, it just does what you ask for, the only change is that the default newline added by `writeln` is the platform line terminator.
And, possibly, only do it if connected to a terminal, and the termcap says to do so. (Can a termcap say that? And if so, we should follow it everywhere, not just on Windows!)

That would potentially be breaking, if someone is piping to a connected terminal and expects plain newlines.


I wouldn't start touching *any other class*. That would risk double-dipping on the `\r`s, or applying it to a class that ends up not writing to stdout.

So: Follow termcap if applicable and possible. If not available, and connected to a terminal, assume platform default line terminator for `writeln`, which is the only place _we_ add newlines, rather than the user providing the text content.
(Check whether `print` uses `Stdout.writeln`, and probably ensure that it doesn't.)

That might just be very naive and simplistic. But I would like to keep complexity low.

**Comment by brianquinlan** [comment]
@azchohfi can probably clarify where he saw the problem.

Since the various Windows terminals correctly render `'\n'`, regardless of whether it was proceeded by a `'\r'` or not, not emitting the platform line ending should only be a problem when the program's output is being sent to a non-terminal.

e.g.

```
> dart .\out.dart >cmdout.txt
> Format-Hex .\cmdout.txt
           Path: C:\Users\brian\Dart\dart-win\samples\stdouteol\cmdout.txt

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   54 68 69 73 20 69 73 20 61 20 74 65 73 74 0A     This is a test.
```

Print is implemented like this:
[Builtin_PrintString](https://github.com/dart-lang/sdk/blob/7f9362fb42bf6fb85f22add0dc1a91bd864f6f21/runtime/bin/builtin_natives.cc#L85). I'll verify later this week but, since we open stdout in binary mode, I can't imagine that it outputs `'\r\n'`.

Pending @azchohfi 's feedback, I'd suggest that, on Windows:
1. we unconditionally output `'\r\n'` on `Stdout.writeln`
2. we unconditionally output `'\r\n'` in `print` on Windows
3. we write documentation explaining this
4. we do nothing else

Obviously this will have to go through the breaking change process.

We can add `lineTerminator` later if people ask for it.

**Comment by azchohfi** [comment]
It was not on a terminal scenario, but on a background agent (a self contained EXE) that manages a REPL of stdin/stdout:
```dart
while ((line = stdin.readLineSync(encoding: utf8)) != null) {
  final response = handleRequest(line);
  // This is the issue
  //stdout.writeln(response);

  // Simple workaround, but Windows specific.
  stdout.write(response);
  stdout.write('\r\n');
}
```

The Windows process that called this agent is expecting for \r\n to split the responses, but it was sending only \n, so this was failing (took me a while to find out why).

**Comment by brianquinlan** [comment]
OK, more nuance here. Not only does `print` output a trailing `\r\n` on Windows, it also interprets **internal** `\n`s as `\r\n`.

```dart
void main() {
  print('This\nis a\ntest');
}
// Format-Hex
//            00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
//
// 00000000   54 68 69 73 0D 0A 69 73 20 61 0D 0A 74 65 73 74  This..is a..test
// 00000010   0D 0A                                            ..
```

**Comment by brianquinlan** [comment]
OK, here is another idea that would make `Stdout` consistent with `print`:
1. add a new `_StdSink` property `String lineTerminator` that defaults to `'\n'`
2. when doing any output from a `write` function substitute all `'\n'` with `lineTerminator`
3. no substitutions are done for methods working with `List<int>` (e.g. `add`, `addStream`, etc.)

This change is breaking for users that `implement Stdout` but is not otherwise breaking (because the default substitution is the current behavior).

This change is consistent with `print` in that internal `\n`s are also substituted.

Thoughts? @lrhn

**Comment by lrhn** [comment]
A behavior which is specific to `stdout`/`stderr`, which is user-configurable, and which only applies to text. That is probably fine.

Should/could the property be global? (E.g., a static on `StdOut`, used by both `stdout` and `stderr`.)

The instance `stdout.lineTerminator` is effectively global when there is only one `StdOut` instance, so making it really global isn't that big of a difference. (Both `stdout.encoding` and `stdout.close` are globally accessible, so it's not like you can't mess  with someone else's output anyway. I don't think it'd be worth it to make the line terminator behavior scoped using IO-overrides or similar.)

We can provide an extension setter on `_StdSink` (ugly, but probably works, or on both `StdOut` and `StdErr`), which would set the global variable, which would look the same as an instance setter, but would apply to both stderr and stdout at the same time, and not be breaking for subclasses. Would also be slightly confusing.

You make the default be `"\n"` to avoid breaking existing code. If possible, it would be nice to default it to `Platform.lineTerminator`. Do we have any idea how breaking that could be? 
Because without that, we still require every Windows user to know that they have to set `StdOut.lineTerminator = Platform.lineTerminator;`, and every other programmer in the world might as well start their program with that line, because it gives you what you want on Windows, and is completely safe everywhere else.

If everybody would want to do that, maybe it should be the default. And take the breaking change face on, because it's going to come anyway.
Say "BREAKING CHANGE: From Dart 3.3, `stdout` and `stderr` emits Windows line terminators by default on Windows, like this ..... If that breaks your code, the workaround is to add a `StdOut.lineTerminator = '\n';`." 
That's all. 

Does it make sense to check whether we're connected to a terminal or not? (Probably not, if users expect stdout piped into a file to have CR+LF line endings too.)


I'd still worry about changing `\r\n` to `\r\r\n`, and think it's worth fixing if we do that today. I think it's more likely that we'll break someone by introducing `\r\r\n` where they're current deliberately emitting `Platform.lineTerminator`, than that it will break someone to go from printing `\r\r\n` to `\r\n` on Windows.

**Comment by brianquinlan** [comment]
> I still worry about changing `\r\n` to `\r\r\n`, and think it's worth fixing if we do that today.
> I think it's _more likely_ that we'll break someone by introducing `\r\r\n` where they're current deliberately emitting `Platform.lineTerminator` on Windows, than that it will break someone to go from printing `\r\r\n` to `\r\n`, which either isn't happening, or nobody has noticed - because it's `print` and the Windows console displays `\r\r\n` as a single newline. But `notepad.exe` does not.

I don't find the '\r\n' => \r\r\n' behavior surprising because it is common in other languages (e.g. Python and C).

(Right now) I find your argument convincing though. Let me prototype what it looks like and see what it would break.

**Comment by lrhn** [comment]
> I don't find the '\\r\\n' => \\r\\r\\n' behavior surprising because it is common in other languages (e.g. Python and C).

If we'd had it from the start, it would probably be OK.
Adding it now risks someone having already manually added `\r\n` on Windows. That's my main worry.

**Comment by brianquinlan** [comment]
The approach of automatically setting the Stdout line ending to the platform line ending results in a lot of test breakage:
https://dart-review.googlesource.com/c/sdk/+/326761?checksRunsSelected=vm-win-debug-x64c-try&tab=checks

I'm not really worried about our tests - those are easy to fix - but we might end up breaking a lot of our users.

I'm propose making the default line ending "\n" in all cases with docs explaining that users should change it.

**Comment by brianquinlan** [comment]
In progress PR: https://dart-review.googlesource.com/c/sdk/+/326761

**Comment by a-siva** [comment]
Any updates on your CL ?

**Comment by osa1** [comment]
> It also makes writing cross-platform console apps with Dart harder, since we can't use the *.writeln helper methods without creating a wrapper helper method ourselves.

Does the CL solve this problem? Since it doesn't make the default line ending `\r\n` by default on Windows (as that would be breaking), cross-platform apps will still have to at least set the line ending manually.

I feel like leaving this as-is should be an option, because it can't be done consistently. We can't convert `\r\n`s to `\n`s.
