### ISSUE TITLE
Failures on [cfe] Implement subtyping for ExtensionType

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#53204]
There are new test failures on [[cfe] Implement subtyping for ExtensionType](https://dart-review.googlesource.com/c/sdk/+/319482).

The tests
```
lib/js/static_interop_test/inline_class/external_static_member_test Crash (expected Pass)
lib/js/static_interop_test/inline_class/external_static_member_with_namespaces_test Crash (expected Pass)
lib/js/static_interop_test/inline_class/object_literal_constructor_test Crash (expected Pass)
```
are failing on configurations
```
dart2wasm-linux-chrome
dart2wasm-linux-d8
```

**Comment by johnniwinther** [comment]
No `ClassInfo` has been computed for `JSObject`.

**Comment by askeksa** [comment]
It seems the `JSObject` class is not present anywhere in `component.libraries`, but it's referenced from the code. Is this intentional?

**Comment by askeksa** [comment]
Actually, it looks like it's present before TFA but not after. @alexmarkov can you take a look?

**Comment by alexmarkov** [comment]
1) Since https://dart-review.googlesource.com/c/sdk/+/319482, front-end started calling `instantiatedRepresentationType`. As a result, it was calculated eagerly and cached in the `ExtensionType._instantiatedRepresentationType` field.

2) JS interop transformation (`_TypeSubstitutor` from `pkg/_js_interop_checks/lib/src/transformations/static_interop_class_eraser.dart`, which is based on `ReplacementVisitor`) was replacing declared representation type, but cached `ExtensionType._instantiatedRepresentationType` was not updated. This results in the incorrectly typed AST and stale references to the types which should have been erased.

3) In addition,  `ExtensionType.visitChildren` didn't visit cached `_instantiatedRepresentationType`, so TFA tree-shaked types which were only mentioned in `_instantiatedRepresentationType` (types such as JSObject which should be replaced by JS interop transformation).

4) After that, dart2wasm code generation crashed when it saw `instantiatedRepresentationType` which referenced class which was removed from the program.

Fix for `ReplacementVisitor` and `ExtensionType.visitChildren` to clear and visit `_instantiatedRepresentationType`: https://dart-review.googlesource.com/c/sdk/+/321201.

Alternatively, we can remove caching of instantiatedRepresentationType altogether (as it could become outdated during AST transformations) and always recalculate it when it is queried. @johnniwinther WDYT?

**Comment by johnniwinther** [comment]
@srujzs Do we want to continue to replace interface types like in `static_interop_class_eraser.dart` ? I'm not sure we should support modifying the declared representation type of an extension type declaration in transformations.

**Comment by srujzs** [comment]
Sorry for the complication, but yes, we want to continue supporting this. Users will write extension types using these types as their representation type for interop. We can't remove `@staticInterop` types for the foreseeable future as it'll be a fairly large breaking change.

**Comment by johnniwinther** [comment]
Then I think we should remove the caching. I'll create a CL.
