### ISSUE TITLE
Is DateTime.now constructor result unique?

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#53200]
(1) I suppose that executing only one Isolate, every time this constructor is executed would create a different DateTime value (maybe close, but with different microseconds). But I have this doubt.

(2) Another doubt would be if my Dart Server is using only one isolate or multiple, because I'm using Http Shelf library and maybe is creating multiple isolates to handle requests.
UPDATE: By default it is run only in one isolate
https://pub.dev/documentation/shelf/latest/shelf_io/serve.html
https://api.flutter.dev/flutter/dart-io/HttpServer/bind.html

Thank you

**Comment by julemand101** [comment]
> (1) I suppose that executing only one Isolate, every time this constructor is executed would create a different DateTime value (maybe close, but with different microseconds). But I have this doubt.

Nothing ensures they are unique. It depends on multiple factors including how often the time is set to "ticking" on your running platform since no platform have infinite precision when it comes to definition of time (even if your OS have microseconds it does not mean the value is updated for each microsecond ongoing).

E.g. this program returns true on my Windows 11 machine running with a i9-12900K:
```dart
void main() {
  final d1 = DateTime.timestamp();
  final d2 = DateTime.timestamp();

  print(d1 == d2);
  print(d1.microsecondsSinceEpoch);
  print(d2.microsecondsSinceEpoch);
}
```
But returns false on my Linux server running with a i7-4770.

**Comment by busslina** [comment]
@julemand101 There is the [Uuid](https://pub.dev/packages/uuid) Dart package which is supposed to generate unique identifiers:

```
// Generate a v1 (time-based) id
uuid.v1(); // -> '6c84fb90-12c4-11e1-840d-7b25c5ee775a'

// Generate a v4 (random) id
uuid.v4(); // -> '110ec58a-a0f2-4ac4-8393-c866d813b8d1'

// Generate a v5 (namespace-name-sha1-based) id
uuid.v5(Uuid.NAMESPACE_URL, 'www.google.com'); // -> 'c74a196f-f19d-5ea9-bffd-a2742432fc9c'
```

V1 says it is time based, so  will I have the same problem that you mentioned?

**Comment by julemand101** [comment]
@busslina 
Need to look into the actual implementation of UUIDv1 in that package but based on the wiki article, the UUIDv1 algorithm are suppose to handle the cases where multiple UUID's ends up being generated before the clock have yet to advance:
https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address)

**Comment by julemand101** [comment]
@busslina Ok, based on the code in the `uuid` package, it does look like they attempt taking care of this scenario:
https://github.com/daegalus/dart-uuid/blob/main/lib/v1.dart

They even make sure to throw an error in case of too many UUID's is generated at a given time before the clock is advanced. So I think it handles the "issue" of the clock not being guarantee to be unique every time being asked.

**Comment by busslina** [comment]
@julemand101 Thank you very much.

For now I resolved it by adding a few lines of code:

```
static DateTime generateUniqueTimestamp() {
    var ret = now();

    while (ret == _timestampIndex) {
      ret = now();
    }

    return _timestampIndex = ret;
  }
```

Not using async delays (sleep) because it is needed in class constructor.

**Comment by julemand101** [comment]
@busslina Maybe a bit weird to call it `generateUniqueTimestamp` since nothing prevents a computer from changing the clock to a previous point in time (e.g. network sync of clock).

Timestamps are just really bad for unique ID's.... I would recommend allowing duplicate timestamps in your design and use something else as the ID.

**Comment by busslina** [comment]
Well, I need some logic to discard previous versions of objects. Until today I was using an integrity index (incremented int value). It was working okay, but as I introduced a timestamp field for other purpose I thought I could use also for version controlling, so I removed the integrity index mechanism... I will think next move... haha

**Comment by lrhn** [comment]
Agree that there are no guarantees that `DateTime.now` or `DateTime.timestamp` are unique. In fact, it's a requirement that they are not all distinct if you call them multiple times within a single microsecond. That might not be physically possible, but web code only has millisecond granularity, so there it's within the same millisecond, which is much more likely. And while native code might have microsecond _precision_, but it might not have microsecond granularity.

So the answer is, officially, "no".
(And if you run in different isolates, it's even more "no", since it's technically possible to run both isolates at the exact same time.)
