### ISSUE TITLE
Accessing @visibleForTesting outside my library, but in tests. How to proceed?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#53216]
For example [`flutter_tools`'s `Artifact` class](https://github.com/flutter/flutter/blob/0a10359f6a20a1807d0299080d1960ad2097d370/packages/flutter_tools/lib/src/artifacts.dart#L305-L311):

```dart
factory Artifacts.test({String? localEngine, FileSystem? fileSystem})
```

... is also used by [`IMobileDevice`](https://github.com/flutter/flutter/blob/0a10359f6a20a1807d0299080d1960ad2097d370/packages/flutter_tools/lib/src/ios/mac.dart#L73-L80):

```dart
factory IMobileDevice.test({ required ProcessManager processManager }) {
  return IMobileDevice(
    artifacts: Artifacts.test(),
    cache: Cache.test(processManager: processManager),
    processManager: processManager,
    logger: BufferLogger.test(),
  );
}
```

At first glance, it seems like `Artifacts.test` is the perfect candidate for `@visibleForTesting`, but doing so triggers a violation in `IMobileDevice.test`. They are in separate libraries (`src/artifacts.dart` versus `src/ios/mac.dart`), but appear to be used as functionally intended.

---

## Proposal

1. The "easiest" fix, albeit not necessarily correct, is to allow `@visibleForTesting` to access `@visibleForTesting`

    One downside here is that I _think_ `@visibleForTesting` is intended to mean `@visibleForMyOwnTests`, where "my own"
    is narrowly defined as "my package's `test/` folder". I can't remember if there was extra allowances for folders named
    `testing` or not (if there is, then maybe there is an out).

2. The next would be to introduce a variant, i.e.

    `@VisibleForTesting.withinPackage()`

/cc @christopherfujino @srawlins

**Comment by srawlins** [comment]
> The "easiest" fix, albeit not necessarily correct, is to allow `@visibleForTesting` to access `@visibleForTesting`

I think this was proposed years ago, but I don't think it panned out. If a constructor declared in one library is to be accessed by a constructor declared in another library, then the first must be public.

I don't really follow what "allow `@visibleForTesting` to access `@visibleForTesting`" means. "This constructor is essentially private, but is public for other code which itself should be private but is actually public so that it can be accessed from tests." Why does the privacy/publicity of the code which contains a reference to `Artifacts.test` change whether it can access `Artifacts.test`?

> One downside here is that I think `@visibleForTesting` is intended to mean `@visibleForMyOwnTests`

I don't think that's true. This interpretation has never been enforced. I think the accessor literally just needs `/test/` or `/testing/` in its path.

> The next would be to introduce a variant, i.e. `@VisibleForTesting.withinPackage()`

What would this do? Or what would be enforced on elements annotated with this?

**Comment by matanlurey** [comment]
> I don't think that's true. This interpretation has never been enforced. I think the accessor literally just needs `/test/` or `/testing/` in its path.

Interesting! Maybe that means there is room for uh, _more_ flexibility.

How do you imagine that working for [`IMobileDevice.test`](https://github.com/flutter/flutter/blob/0a10359f6a20a1807d0299080d1960ad2097d370/packages/flutter_tools/lib/src/ios/mac.dart#L73-L80), though?

> What would this do? Or what would be enforced on elements annotated with this?

Allow `@visibleForTesting` elements in the same package to access it (i.e. sort of an explicit workaround to proposal 1)

**Comment by srawlins** [comment]
The issue is that `@visibleForTesting` doesn't mean, "I am test code but I have to live in this impl library." It means "I wish I could be private, but it is required that I be accessible from within tests." So back to my ["I don't really follow" comment above](https://github.com/dart-lang/sdk/issues/53216#issuecomment-1678247481).

If there is a private-but-accessible-to-tests constructor which must be accessible in another library, then it's just a public constructor. A public constructor which must be accessible from other libraries. I think it's pretty orthogonal that the other code, `IMobileDevice.test` happens to also be `@visibleForTesting`.

Judging by the names, `IMobileDevice.test` and `Artifacts.test`, it sounds like `@visibleForTesting` isn't being used so that they can be used privately _and_ in tests; rather, the intent sounds like it is that these constructors "only" be visible in tests.

(I always hate answers like "Instead of answering the question you asked, why don't we do something else entirely", but, anyhow) I see that `Artifacts.test` instantiates a `_TestArtifacts` and uses a `_TestLocalEngine` which all sounds like code that should not just be private to this impl (non-test) library, but should actually live outside of `lib/`. WDYT? I think all of that code can be moved to `test/` (near wherever it is needed, perhaps), and instead of a factory method, `Artifacts.test` is just a top-level function, `gimmeATestArtifactsObject()`. This is aside from the `visibleForTesting` question; it just seems like this code really shouldn't live in `lib/`...

**Comment by matanlurey** [comment]
That's totally fair!

I guess also a follow-up fair question is, if someone marks a class as sealed or final (not in this case, but imagine), the "just put it in `test/`" no longer works, right?

**Comment by srawlins** [comment]
Yeah that's true.

**Comment by matanlurey** [comment]
Cool. Let me follow-up with the `flutter_tools` owners and see if I am misunderstanding intent here.

Maybe we need "friend" libraries after all :)

**Comment by srawlins** [comment]
> Maybe we need "friend" libraries after all :)

Haha yeah I almost went to the same place.

It's actually interesting that we don't have an annotation like `@visibleONLYToTesting`. Like you could imagine Artifacts is like:

```dart
class Artifacts {
  _PrivateType _privateField;
  Artifacts() : _privateField = _PrivateType();
  Artifacts.forTest() : _privateFIeld = _PrivateType(fileSystem: false);
}
```

In this case, you maybe _never want to make _privateField public (even `@visibleForTesting`), nor the `_PrivateType`. So then you could not just move this constructor to `test/`. And it remains to be seen whether my suggestion will work.

In that case, `Artifacts.forTest` could be annotated with something like `visibleONLYToTesting`. You could imagine the same for field setters or "reset state" methods that should never be called by impl code (within the library or without), and is only available to touch private fields from a test.

A case could maybe be made for such an annotation.

**Comment by Hixie** [comment]
FWIW, in code that's exposed to other users (e.g. the Flutter framework itself), code annotated `@visibleForTesting` is basically considered to just be public API.

**Comment by matanlurey** [comment]
Is that true of other "visibility" annotations like protected, or is visibleForTesting unique because of its implementation?

**Comment by Hixie** [comment]
Well `@protected` is not even trying to not be a public API, so that's definitely considered a public API surface, sure. I'm not sure what other visibility protections exist. Leading underscore is considered private, that's not public. That's also enforced. Not exporting something that could be imported by directly giving the path to the file is one way some people try to make private APIs, but those are also public in practice, so we export everything. `@deprecated` is also considered public.

To clarify, by "public API" here I mean "must be fully documented and is not exempt from the breaking change policy".

**Comment by christopherfujino** [comment]
> (I always hate answers like "Instead of answering the question you asked, why don't we do something else entirely", but, anyhow) I see that Artifacts.test instantiates a _TestArtifacts and uses a _TestLocalEngine which all sounds like code that should not just be private to this impl (non-test) library, but should actually live outside of lib/.

No, I agree with this :).

**Comment by jonahwilliams** [comment]
At least in the flutter_tool, nothing is a public API, so it doesn't really matter if something is private, visiblefortesting, or public. There are pratical reasons to leave test code public, so that we can actually unit test it. Adding the visible for testing was mostly just for documentation. I would just as soon as `// visible for testing` as a comment to the constructor and move on.

**Comment by matanlurey** [comment]
I'm closing this as I think, in so-far that `@visibleForTesting` is supported, it appears to "do the right thing".

Thanks all!
