### ISSUE TITLE
"Type variable bounds"-related termination issues.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#53254]
The following code crashes during compilation on DartPad:

```dart
void foo<T extends List<S>, S extends List<T>>(T x, S y) {
  var a = (x == y) ? x : y;
}
```

That example code was sourced from: https://github.com/dart-lang/language/blob/main/resources/type-system/upper-lower-bounds.md#type-variable-bounds

```
Error compiling to JavaScript:
lib/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (3.1.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Crash when compiling file:///tmp/dartpadYPHDRW/lib/main.dart at character offset 55:
Stack Overflow

#0      Types.performNullabilityAwareSubtypeCheck (package:kernel/src/types.dart:73:3)
#1      TypeSchemaEnvironment.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/type_inference/type_schema_environment.dart:348:18)
#2      IsTypeParameterSubtypeOf.isTypeParameterRelated (package:kernel/src/types.dart:856:22)
#3      Types.performNullabilityAwareSubtypeCheck (package:kernel/src/types.dart:160:25)
#4      Types.isSubtypeOf (package:kernel/src/types.dart:52:26)
#5      StandardBounds._getNullabilityAwareTypeParameterStandardUpperBound (package:kernel/src/standard_bounds.dart:1497:9)
#6      StandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:kernel/src/standard_bounds.dart:753:14)
#7      TypeSchemaStandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:front_end/src/fasta/type_inference/standard_bounds.dart:59:18)
#8      StandardBounds._getNullabilityAwareStandardUpperBound (package:kernel/src/standard_bounds.dart:642:12)
#9      StandardBounds.getNullabilityAwareStandardUpperBoundInternal
[...]
```

The analyzer appears to also have issues with it. It looks like it gets stuck and stops analyzing anything that comes after the example given above.

**Comment by mit-mit** [comment]
cc @eernstg

**Comment by eernstg** [comment]
This is a known issue, it's mentioned [here](https://github.com/dart-lang/language/blob/main/resources/type-system/upper-lower-bounds.md#type-variable-bounds). However, it does probably make sense to have an issue like this one as well. We don't have a solution at this time.

**Comment by modulovalue** [comment]
Cycles like:

```dart
void foo<T extends S, S extends T>(T x, S y) {
  var a = (x == y) ? x : y;
}
```

are already reported as `CycleInTypeVariables` errors.

https://github.com/dart-lang/sdk/blob/851e696270a25a66e210fe974f6500ea123a8fd8/pkg/front_end/messages.yaml#L4490-L4495

Couldn't this issue be solved by making it a similar error, or are there ways in which the `<T extends List<S>, S extends List<T>>` example could be useful, and is therefore expected not to become an error, but valid Dart code that terminates during compilation and compiles successfully?

**Comment by lrhn** [comment]
The problem is that you sometimes want self-references in types, like:
```dart
void sort<T extends Comparable<T>>(List<T> values) { 
  // Sort using `.compareTo`.
}

var strings = ["Bonobo", "Gorilla", "Chimpansee"];
sort(strings); // Works, because `String` implements `Comparable<String>`.
```

Disallowing self-references in general would prevent that from being expressible.

The problem is when the self reference gets unfolding in a recursive algorithm, and we don't notice.

I'm a little surprised that this example here works:
```
Comparable processBoth<T extends Comparable<T>, S extends Comparable<S>>(List<T> ts, List<S> ss) {  
  // Sort and stuff.
  return ts.length < ss.length ? ss.first : ts.first;
}
```
but fails if you switch the `S` and `T` of `Comparable.

**Comment by modulovalue** [comment]
> The problem is that you sometimes want self-references in types, like:

@lrhn thank you, I failed to consider that in my comment, I agree.

What if we do not consider cycles, but strongly connected components that contain more than one type parameter and make them an error? Your examples should still pass, while the example in the issue description would not, because there's an SCC with multiple type parameters (that is, `T` depends on `S` via `extends` and `List` and `S` depends on `T` via `extends` and `List`).

Could that be enough to at least recognize what leads to the termination issue here, or can you think of any other cases where this could be too restrictive?

---

I'm also wondering, is there even a way to invoke a `foo` that contains such an SCC? If not, does it even make sense to support them?

```dart
void foo<T extends List<S>, S extends List<T>>(T x, S y) {}

void main() {
 // 'List<int>' doesn't conform to the bound 'List<List<List<int>>>' of the type parameter 'T'.
 //   vvvvvvvvv
 foo<List<int>, List<List<int>>>([], []);
 // 'List<List<int>>' doesn't conform to the bound 'List<List<List<List<int>>>>' of the type parameter 'S'.
 //                         vvvvvvvvvvvvvvv
 foo<List<List<List<int>>>, List<List<int>>>([], []);
 // ... are there even two types that would make an invocation of foo type-check?
}
```

**Comment by eernstg** [comment]
As far as I can see, the analyzer does not crash, but the common front end does.

It is hardly useful no insist that the analyzer must crash on this example (based on the fact that the infinite loop is part of the specification and hence every implementation should have it).

On the other hand, the loop is documented [here](https://github.com/dart-lang/language/blob/main/resources/type-system/upper-lower-bounds.md#type-variable-bounds) as I mentioned, which means that this issue does not provide information about any new faults (with the language or any tools), it just repeats the fact that the loop in the specification exists.

I'll close this issue because the loop is already mentioned in upper-lower-bounds.md.

**Comment by eernstg** [comment]
> is there even a way to invoke a `foo` that contains such an SCC?

It usually suffices to put `Never` in a few places, e.g.:

```dart
void foo<T extends List<S>, S extends List<T>>(T x, S y) {}

void main() {
  var func = foo<Never, Never>;
  foo<List<Never>, List<Never>>([], []);
}
```

About self-references in types (also known as F-bounded types): They are often used as "subtype relationship factories", enabling type safe families of classes:

```dart
class Vehicle<V extends Vehicle<V, O>, O extends Operator<V, O>> {
  O operator;
  Vehicle(this.operator);
}

class Operator<V extends Vehicle<V, O>, O extends Operator<V, O>> {
  late V vehicle;
  void init(V vehicle) => this.vehicle = vehicle;
}

class Car extends Vehicle<Car, Driver> { Car(super.operator); }
class Driver extends Operator<Car, Driver> {}

class Aeroplane extends Vehicle<Aeroplane, Pilot> { Aeroplane(super.operator); }
class Pilot extends Operator<Aeroplane, Pilot> {}
```

As you can see, `Car` and `Driver` depend on each other and `Aeroplane` and `Pilot` depend on each other in the same way, structurally, but the classes `Car` and `Aeroplane` are unrelated. You can write generic code in terms of `Vehicle` and `Operator`, and it will work on `Car`/`Driver` objects or on `Aeroplane`/`Pilot` objects, with full type safety.

This perhaps more obvious alternative is not safe:

```dart
class Vehicle {
  Operator operator;
  Vehicle(this.operator);
}

class Operator {
  late Vehicle vehicle;
  void init(Vehicle vehicle) => this.vehicle = vehicle;
}

class Car implements Vehicle {
  Driver driver;
  Operator get operator => driver;
  set operator(Operator operator) => driver = operator as Driver;
  Car(this.driver);
}

class Driver implements Operator {
  Car car;
  Vehicle get vehicle => car;
  set vehicle(Vehicle vehicle) => car = vehicle as Car;
  Driver(this.car);
  void init(covariant Car car) => this.car = car;
}

// Similarly for `Aeroplane` and `Pilot`.
```

With the former design, it is a compile-time error to work with a `Car` and a `Pilot` together using the types `Vehicle` and `Operator` (because there are no actual type arguments that will make everything type check), but with the latter design you would always be able to put a `Car` where a `Vehicle` is expected, and a `Pilot` where an `Operator` is expected, and then your generic code working on `Vehicle` and `Operator` could bring a `Car` and a `Pilot` together, and you'd have run-time type errors. For instance, `myVehicle.init(myOperator)` would throw.

So, yes, F-bounded type parameters can be useful!

**Comment by modulovalue** [comment]
@modulovalue wrote
> This no longer crashes and it appears to have been resolved?

@eernst wrote:
> As far as I can see, the analyzer does not crash, but the common front end does.



It turns out that the program from the issue description:

```dart
void foo<T extends List<S>, S extends List<T>>(T x, S y) {
  var a = (x == y) ? x : y;
}
```

only crashes during compilation with DartPad on `beta (Use Flutter version 3.18.0-0.2.pre and Dart version 3.3.0-174.3.beta)` and `master`, but not on `stable (Use Flutter version 3.16.5 and Dart version 3.2.3)`. @eernstg is that expected?

**Comment by eernstg** [comment]
I can see CFE crashes (using `dart theProgram.dart` where `theProgram.dart` is `foo` and an empty `main`) in recent versions as well as older ones (include some that are older than the current stable version on DartPad, including 3.2.0, 2.19.0, 2.8.0, 2.0.0).

This might just indicate that internal errors aren't shown when DartPad uses the stable channel (possibly based on the assumption that internal errors are not very useful for anyone who isn't interested in developing the language and/or its tools). I don't know.

But as far as I can see we've had the crashes all the time, which is also what I'd expect (given that the circularity is a property of the spec).

Of course, it is always possible to avoid infinite loops by adding a counter and saying "No" to questions like "is this type a subtype of that type?" whenever that kind of query loops, or saying "Object?" when the standard upper bound of two types is requested and it loops. That would probably be the most civilized thing to do (but it just looks better, it doesn't solve any actual problems).
