### ISSUE TITLE
[analyzer] Wrong error in case of an extension type with superinterfaces

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53314]
The following code produces an error in analyzer (no error in CFE)
```dart
extension type ET1<T>(T id) {}

extension type ET2<T extends String>(T id) implements ET1<T>, String {}

main() {}
```
Error is
```
• The extension type 'ET2' can't implement both 'Object?' and 'Object' because the type arguments are different. •
          conflicting_generic_interfaces
```
Tested on `Dart SDK version: 3.2.0-90.0.dev (dev) (Fri Aug 18 21:03:21 2023 -0700) on "windows_x64"` and on the edge SDK (Aug 23, 2023) on Linux x64

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
So, let me rename it a bit.
```
extension type A(int? it) {}
extension type B(int it) implements A, num {}
```

`A` has `Object?` as the superinterface.
`B` has Object an a superinterface.

As, probably, required in https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md with "If a class C in an opted-in library implements the same generic class I more than once as I0, .., In, and at least one of the Ii is not syntactically equal to the others, then it is an error if NNBD_TOP_MERGE(S0, ..., Sn) is not defined where Si is NORM(Ii)."

On one hand, `Object` is not generic, so strongly speaking, the rule is not applicable?
OTOH, we still need to chose, what is the result of merging `Object?` and `Object` in the extension type `B`.

I can special case `Object?` and `Object` for extension types.
It might be not surprising that we need this, because nullable types were not allowed as superinterfaces before.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/323081

**Comment by eernstg** [comment]
I think the most useful way to think about this is that we (really, honestly, though not visibly) have a top type, which is an interface type (that is, it can be a superinterface). Let's call it `Any`.

So we have `class Object extends Any {}`, `class Null extends Any {}`, and `Any` declares the five "big members" (`toString`, `==`, `hashCode`, `runtimeType`, `noSuchMethod`).

This implies that there is nothing special about an extension type that has `Any` as a superinterface and a class like `class MyClass {}` that has `Object` as a superinterface.

None of these types have any type arguments, so the rule about errors for having both `C<int>` and `C<num>` as a superinterface do not apply.

We also have the notation `Object?` which is a nullable type based on `Object` (no special treatment should be necessary for that, and we have things like `Null <: Object?` and `Object <: Object?` because of this standard treatment).

However, we have one extra rule which is `Any <: Object?`.

This is basically the same thing as promising that _every object you can ever encounter_ will be null, or it will have a run-time type which is a subtype of `Object`.

This remains sound even when we add extension types which have `Any` as a direct superinterface, because we know that any expression whose static type is an extension type will evaluate to an object which is null or an `Object`.

This also means that we don't have to distinguish between `Object?` and `Any`, they are just top types.

I suppose this should suffice to motivate conceptually why it isn't a problem for a type to have both `Object` and `Object?` as superinterfaces, because it's really `Object` and `Any`, and we don't need any special rules to allow that.

NB: The other members of the language team do _not_ all subscribe to this perspective. This is not because it's inconsistent or wrong in any way (that I know of), it's simply because we already have a very large number of ways in which top types are taken into account as special cases, and most members of the language team don't want to rock the boat. However, I still think it's the meaningful way to think about the top types, so I just wanted to mention it. ;-)
