### ISSUE TITLE
`doc_test` is failing on windows

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#53328]
The tests
```
pkg/linter/test/doc_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

**Comment by pq** [comment]
Actually, there are a host of tests being skipped on windows, all failing with similar path-related issues.

See: https://dart-current-results.web.app/#/filter=pkg/linter

See, for example:

```
stderr:
Unhandled exception:
FileSystemException: Directory listing failed, path = '/C:\b\s\w\ir\cache\builder\sdk\pkg\linter\test_data\rules\experiments\*' (OS Error: The filename, directory name, or volume label syntax is incorrect.

, errno = 123)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      main.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/linter/test/experiments_test.dart:19:62)
#3      Declarer.group.<anonymous closure> (package:test_api/src/backend/declarer.dart:267:37)
#4      _rootRun (dart:async/zone.dart:1399:13)
#5      _CustomZone.run (dart:async/zone.dart:1301:19)
#6      _runZoned (dart:async/zone.dart:1804:10)
#7      runZoned (dart:async/zone.dart:1747:10)
#8      Declarer.declare (package:test_api/src/backend/declarer.dart:169:7)
#9      Declarer.group (package:test_api/src/backend/declarer.dart:264:14)
#10     group (package:test_core/scaffolding.dart:222:13)
#11     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/linter/test/experiments_test.dart:15:3)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

(The way I'm composing the path is clearly not platform safe despite using `path.join`.)

@srawlins, @bwilkerson: curious if you all have tackled anything similar in analyzer tests? Perhaps I should be calling `toFilePath` on `Platform.script`? (Conversion is happening in `pathRelativeToPkgDir`.)

**Comment by bwilkerson** [comment]
Yes, we've seen similar issues. The solution used in the `analyzer` package is to use `ResourceProvider`, typically through the `ResourceProviderMixin`. It has methods that allow us to convert a posix path to the correct path for the platform. Most of the time when we run into this kind of problem it's because someone forgot to convert the string.

If we don't want to use `ResourceProviderMixin`, then at least we ought to be able to look at it to figure out how it's handling the differences (I don't remember the details off the top of my head).
