### ISSUE TITLE
String.hashCode returns different on mobile and web

### ISSUE THREAD

**Issue by uua-kirkcharlesniv** [dart-lang/sdk#53326]
This tracker is for issues related to:

* Dart native and web compilers

Is there any way at least to emulate the hash code being returned from the mobile?

Hash code of "996BDDA6832B"
- in mobile: 793389451
- in web: 188660191

Filed a similar issue at https://github.com/flutter/flutter/issues/132815 but was redirected here.

**Comment by julemand101** [comment]
You already got an answer? As mentioned in https://github.com/flutter/flutter/issues/132815#issuecomment-1683265813, the `hashCode` is not meant to be something you can use across different platforms or even between program executions.

If you have some specific need for having stable `hashCode` value, you need to make your own logic and call that.

**Comment by lrhn** [comment]
That's correct. There is no promise that a hash has the same value between platforms, or even between different runs of the same platform. 

Some hash code computations deliberately change the value between runs, just to avoid someone depending on a particular implementation. String hash code doesn't, it just depends on the specific implementation, but it could. And that could change in a later release, and the implementation for a specific platform can also change between releases, even in patch releases, since its value is not guaranteed to be stable.
