### ISSUE TITLE
Working with `FutureOr` produces unnecessary cast.

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/sdk#53353]
In the following example, analyzer reports `Unnecessary cast`, but without cast it's impossible to compile the program.
It seems that analyzer aware of internal `FutureOr` union, but compiler inference isn't.

```dart
import 'dart:async';

extension ToFuture<T> on T {
  Future<T> get toFuture async => this;  
}

int sumSync(int a, int b) => a + b;
Future<int> sumAsync(FutureOr<int> a, FutureOr<int> b) async =>
  await a + await b;

FutureOr<int> sumGeneric(FutureOr<int> a, FutureOr<int> b) =>
  switch((a, b)) {
    (int a, int b) => sumSync(a, b) as FutureOr<int>, // Unnecessary cast
    (final a, final b) => sumAsync(a, b),
  };

FutureOr<void> printFuturOr<T>(FutureOr<T> v) async =>
  switch(v) {
    Future<T> v => print('Future<$T> ${await v}'),
    T v => print('$T $v'),
  };

void main() {
  final (a, b) = (1, 2);
  
  printFuturOr(sumGeneric(a, b)); // int 3
  printFuturOr(sumGeneric(a.toFuture, b)); // Future<int> 3
}
```

**Comment by lrhn** [comment]
The reason you need the cast is that the upper bound algorithm used to combine `Future<int>` (from `sumAsync`) and `int` (from `sumSync`) doesn't want (or know) to create a `FutureOr` type.
That's mostly as safety measure, because introducing a union type can be *too easy*, while also giving a type which doesn't have any useful methods of its own.
So the upper bound it uses for `int` and `Future<int>` is `Object` (which also doesn't have a any useful methods, so maybe choosing `FutureOr<int>` would't be that bad).

Then you get an "unneccessary cast" warning because that warning is given for any up-cast, whether it's necessary or not for any other reason. You should just ignore that warning.

**Comment by bwilkerson** [comment]
Ideally, if the cast is necessary for some reason, then we shouldn't be producing the warning.

The question is, can the analyzer reasonably determine that removing the cast would produce an error (or maybe just that it changes the type of the surrounding expression)? If the reason is the upper bound algorithm, then it seems like we could recognize switch expressions (and conditional expressions I assume) and run the algorithm with the types that would be used if the cast weren't there, and look for a difference.

**Comment by iapicca** [comment]
is this still the case in dart 3.4.4?

<img width="723" alt="Screenshot 2024-08-01 at 14 32 49" src="https://github.com/user-attachments/assets/4483ebd0-3d72-47c8-b5eb-0dc56cfb5352">

**Comment by srawlins** [comment]
Analyzer no longer produces a diagnostic for this code. Thanks for catching, @iapicca
