### ISSUE TITLE
Records in analyzer do not work

### ISSUE THREAD

**Issue by tenhobi** [dart-lang/sdk#53375]
Related to `package:analyzer 6.2.0`.
Using `Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"`.

Hello, while trying to update our generator package to support Dart 3 records, we found out that analyzer package does not work properly for records. Specifically `isDartCoreRecord` on `DartType` is always false, type's element is `null` and therefore cannot check for library etc. which is used by `isDartCoreRecord`.

I did create a small repro https://github.com/tenhobi/repro-analyzer-records that compares List and String vs Record.

Run on an example:

```
@Abc(
  const [1, 2, 3],
)
class Xxx {}

@Abc(
  'test string',
)
class Zzz {}

@Abc(
  const (1, 2, 3),
)
class Yyy {}
```

produces this output (logs here: https://github.com/tenhobi/repro-analyzer-records/blob/main/lib/generator.dart#L30-L37).

```shell
// LIST
[WARNING] abc on example/main.dart:
type.getDisplayString: List<int>
type.isDartCoreList: true
type.isDartCoreRecord: false
type.element.library: library dart:core
type.element.library.isDartCore: true

// STRING
[WARNING] abc on example/main.dart:
type.getDisplayString: String
type.isDartCoreList: false
type.isDartCoreRecord: false
type.element.library: library dart:core
type.element.library.isDartCore: true

// RECORD
[WARNING] abc on example/main.dart:
type.getDisplayString: (int, int, int)
type.isDartCoreList: false
type.isDartCoreRecord: false // should be TRUE
type.element.library: null // should not be NULL
type.element.library.isDartCore: null // shoud not be NULL
```

This method works for any other type other that records, so I suppose I use the API correctly.

**Comment by bwilkerson** [comment]
This is working as intended, so let me try to explain why this is the intended behavior.

First, some background.

Dart supports both [nominal types](https://en.wikipedia.org/wiki/Nominal_type_system) and [structural types](https://en.wikipedia.org/wiki/Structural_type_system). Types like `String` and `List` are nominal types, while record types and function types are structural types.

Next, the behavior of `isDartCoreRecord`.

With both record types and function types there is a nominal supertype (`Record` and `Function` respectively). The record type `(int, int, int)` is a subtype of `Record`, but is not itself `Record`. If you were to test the type of a function (such as `int Function(int)`) I believe that `isDartCoreFunction` would also return `false` for the same reason. The same would also be true if you were using a subtype of `List` rather than `List` itself. In other words, the `isDartCoreX` getters return `true` only for the type itself, not for subtypes.

It is possible to use the nominal type `Record` in code, and the type the analyzer would create to represent that type would return `true` from `isDartCoreRecord`, but subtypes like `(int, int, int)` will return `false`.

If what you're really trying to ask is whether the type is a subtype of `Record`, then you're probably looking for `TypeSystem.isSubtypeOf`.

Finally, the question of elements.

The analyzer's model of Dart code uses an instance of `DartType` to represent types in the type system. It also uses instances of `Element` to represent declarations within the code. Declarations are assumed to occur in a single location. For every nominal type there is an element used represent the declaration of the type (including it's name). But for structural types there is no declaration site, so there is no element. That's why asking for the `element` of a record type returns `null`. The same is true for function types.

If you had an instance of `DartType` representing the type `Record` (one for which `isDartCoreRecord` returned `true`, then, being a nominal type, it would have a non-`null` element.

Not knowing why you want an element for a structural type I can't suggest an alternative.

**Comment by tenhobi** [comment]
@bwilkerson Thanks a lot for the detailed answer! You are indeed correct, and it makes a lot of sense now.

I tried your suggested approach with `TypeSystem.isSubtypeOf` but it didn't work, as I am supposed to put an instance of `DartType` inside. The only thing that worked was creating an instance with default values like `RecordType(positional: [], named: {}, nullabilitySuffix: NullabilitySuffix.none)`, which is not Record itself, as you state. Not sure if I can put some other `DartType` instance that would work as expected?

However I was able to make it using `TypeSystem.leastUpperBound` which gives me a `Record` if my type is some record and that I can test with `isDartCoreRecord`. In the end, I can test it, which is excellent.

```shell
TypeSystem.isSubtypeOf(valueType, Record): false
TypeSystem.isSubtypeOf(Record, value.type): false
TypeSystem.leastUpperBound(value.type, Record): Record
TypeSystem.leastUpperBound(Record, value.type): Record
TypeSystem.leastUpperBound(Record, value.type).isDartCoreRecord: true
```

**Comment by tenhobi** [comment]
AND I can also just simply do `value.type is RecordType`. 🤦 

Before, I must have combine analyzer and code_builder which both have `RecordType` and therefore it did not work.

**Comment by bwilkerson** [comment]
I'm glad it's working for you. In case it's useful information, the class `TypeProvider` provides access to the types defined in the `dart:` libraries that are explicitly referenced by the language specification, which includes `Record`.
