### ISSUE TITLE
[vm service]: Offer a way to synchronously inspect objects

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#53409]
Hello!

Would it be possible to add an `evaluateSync` (& likely similar for other methods), similar to `evaluate` but which blocks the application until the evaluation has completed?

Some background:
For a custom devtool tab, I would like to implement a view which shows the history of all states an object has been in (with ways to undo changes) – commonly referred as "time travel".
While VM-service enables me to take a snapshot of an object at a given time, the problem is that at the moment, taking this snapshot is asynchronous.
Meaning that in the meantime, the object may receive other changes.

This is problematic if an object changes in quick succession, such as if users did:

```dart
class Counter with ChangeNotifier {
  var count = 0;
  void incrementTwice() {
    count++;
    notifyListeners();
    count++;
    notifyListeners();
  }
}
```

With such code, although the devtool would correctly take two snapshots of the counter, chances are both snapshots would show the same value.

If an `evaluateSync` could be implemented, then the debugged application itself could use vm-service to take a snapshot of the object.
This `evaluateSync` would be invoked on `notifyListeners` and evaluate the content of the `Counter` instance. And this would block the isolate until the evaluation is completed.  It would ensure that the snapshot of the object is taken immediately on change, which would resolve this problem.

**Comment by rrousselGit** [comment]
If we want to do this, it may be logical to make it easier for applications to listen to themselves.

We should ideally be able to spawn a VM-service instance in debugged application, no-matter if it's a desktop app or if it's running on a physical Android device (as long as it's plugged and in debug mode).

Otherwise this solution would likely work only on desktop apps and emulators.

**Comment by rmacnak-google** [comment]
I'm not sure what this is asking for. The VM service's `evaluate` is already synchronous: the Dart program runs the expression at whatever interrupt point happens to pick up the `evaluate`, running the expression to synchronous completion, then resumes the Dart program. A service client might control where in the Dart program this happens by using breakpoints or other means of pausing. The Dart program itself might yield at interesting places using `debugger()`. Likewise the state of multiple objects can be queried over the service when the program is paused. The program can also query its own state using mirrors.

**Comment by rrousselGit** [comment]
Won't repeatedly calling `debugger` and have the devtool resume the isolate degrade the user experience?
I would assume that if the app is connected to an IDE, it'd cause the debugger to flash "paused"/"running" repeatedly whenever there's a change – maybe even opening the file where the program was paused.

**Comment by bkonyi** [comment]
> And while the program executed by `evaluate` is synchronous, we do not get the result synchronously. `evaluate` returns a `Future` no matter what. Therefore there is always a delay in obtaining the result.

There's no way around this since requests to the VM service are made over a websocket, so all requests to the VM service are asynchronous by nature due to the round trip over the network.

If you're looking to track the history of state changes, your best bet is probably to track these changes in package:provider / package:riverpod and expose them to your DevTools extension via a service extension. That way you don't need to rely on `evaluate` to try and capture state, which won't ever provide deterministic results unless you've already paused at a breakpoint / `debugger()` call.

I'm going to close this issue as we don't plan on adding synchronous `evaluate` support to `dart:developer`, but please reach out on the [DevTools discord](https://discord.com/channels/608014603317936148/1106667330093723668) if you want to discuss how you might be able to move forward with this feature.
