### ISSUE TITLE
No private field promotion on an enum instance

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53437]
The following tests fails in both analyzer and CFE
```dart
enum E {
  e1, e2;

  final int? _x = 42;

  void test() {
    if (_x != null) {
      _x.isOdd; // Ok
    }
  }
}

main() {
  if (E.e1._x != null) {
    E.e1._x.isEven; // CFE  Error: Property 'isEven' cannot be accessed on 'int?' because it is potentially null.
                    // Analyzer COMPILE_TIME_ERROR.UNCHECKED_USE_OF_NULLABLE_VALUE
  }
  E.e1.test();
}
```
cc @stereotype441 

Tested on the edge SDK (Sept 6, 2023) on Linux x64

**Comment by stereotype441** [comment]
Interesting edge case!

The reason this is happening is because `E.e1` is implicitly defined as a static field of the class `E`. Flow analysis doesn't track anything about the behaviour of static fields, only instance fields. So it doesn't recognize that the two `E.e1._x` expressions refer to the same value, therefore it doesn't promote. But it _does_ promote in this situation:
```dart
main() {
  var e1 = E.e1;
  if (e1._x != null) {
    e1._x.isEven;
  }
  E.e1.test();
}
```

I can definitely understand why you came to the conclusion that the expression `E.e1._x` ought to be promotable. After all, the feature is called "field promotion", and both `E.e1` and `E._x` _are_ fields. @dart-lang/language-team, any opinions about whether we should make this work (either in Dart 3.2 or in a later release)?

**Comment by eernstg** [comment]
I can't see precisely how the current approach to instance variable promotion deals with the stability of paths, but otherwise I'd say that `E.e1` is a constant expression, hence stable.

**Comment by lrhn** [comment]
The full generality of field promotion would be:

The instance property access `expr.field` should be promotable if it's stable, and it's stabile if `expr` is (recursively) stable and `.field` on the static type of `expr` denotes a never-overridden final instance variable.

For that to work, we need a bottom for the recursion which is a stable non-instance-field expression.

I assume the roots are expressions which are currently promotable between the two uses, whichare local variables that are not potentially assigned between the two promoting check and the promoted use.
(It's not really the same as being promotable, because assignment promotion allows us to assign a new value to a local variable, without changing its type. That assignment would make it non-stable, and therefore not guarantee the same *value* when reading the field again, even if it's on the same type.)

We could, and probably should, allow the getters of static final/const variables declared in the same library to be both locally promotable, and considered as stable roots for field access promotion. They're definitely never overridden.

As Erik says, we can treat any constant expression as stable, because changing it to a non-constant getter would be breaking in itself, but we can only trust its final fields to be, well, fields at all inside the declaring library.

**Comment by devoncarew** [comment]
@stereotype441 - what would be the best `area-` label for this issue?

**Comment by stereotype441** [comment]
> @stereotype441 - what would be the best `area-` label for this issue?

I classified it as `area-language`. I know that's deprecated, but the reason it's deprecated is because language discussions should be moved to the `language` github repo. And that's precisely what I'm planning to do. I'm going to capture the comments above in some language issues, link them here, and then I'll close this issue.

**Comment by stereotype441** [comment]
I believe I've adequately captured the discussion above in two language issues: https://github.com/dart-lang/language/issues/3325 and https://github.com/dart-lang/language/issues/3326, so I'm closing this issue.

@lrhn and @eernstg, if you feel like there's anything important from this discussion that's not adequately captured in those issues, feel free to comment there, or let me know!
