### ISSUE TITLE
Type inference issue when a method returns a generic type.

### ISSUE THREAD

**Issue by AoEiuV020** [dart-lang/sdk#53448]
When the return type of a method is 'T?' and the variable receiving the return value is of type 'T,' it is not possible to determine the actual type of 'T' within the method.

The complete code is as follows:
```dart
import 'package:test/test.dart';

T? read<T>() {
  if (T == String) {
    return 'String' as T;
  }
  return null;
}

void main() {
  test('type', () async {
    var a = read();
    expect(a, null);
    try {
      String b = read(); // <-- Incorrect here,
      throw StateError('unreachable');
    } catch (e) {
      expect(e.toString(), "type 'Null' is not a subtype of type 'String'");
    }
    String? c = read();
    expect(c, 'String');
    String? d = '';
    d = read();
    expect(d, null); // <-- Incorrect here,
    d = read();
    expect(d, 'String');
    String? e = '';
    e = read<String>();
    expect(e, 'String');
    String? f;
    f = read();
    expect(f, 'String');
  });
}

```

**Comment by eernstg** [comment]
@AoEiuV020, you would probably benefit from using a more strict analysis. Something like this would be in your 'analysis_options.yaml':

```
analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true

linter:
  rules:
    - avoid_dynamic_calls
```

The point is that type analysis has chosen the actual type argument `dynamic` for the invocation of `read` where the context type is `String` (because there is no type `T` such that `T?` is assignable to `String`, but `dynamic` will work because it allows for a dynamic check).

And then you get the type check at run time, and it fails.

I think it is all working as specified, but you may still want to get a different behavior (where `dynamic` is not inferred, but you get an error message instead).
