### ISSUE TITLE
Ternary operator analyzes incorrectly for classes with multiple mixins

### ISSUE THREAD

**Issue by AngryVelociraptor** [dart-lang/sdk#53474]
Consider the following code: 
```dart
mixin A {}

mixin B {}

class C with A, B{}

class D with A, B{}
```
The following is valid dart.
```dart
f(bool cond){
  A a;
  if(cond){
    a = C();
  }
  else{
    a = D();
  }
}
```
The following is equivalent and should therefore also be valid, but is considered an error by the analyzer and compiler.
```dart
f(bool cond){
  A a = cond ? C() : D();
}
```
`Error: A value of type 'Object' can't be assigned to a variable of type 'A'.`

**Comment by eernstg** [comment]
@AngryVelociraptor, please take a look at https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aleast-upper-bound where this exact question has been debated for a while.

The basic problem is that both `A` and `B` are superinterfaces of `C` and of `D`, and they are equally "derived" (they are the same number of superinterface steps away from `Object`), so there is no obvious way for the step that computes the type of the expression `cond ? C() : D()` to make a choice.

There is one idea on the table, though: Check out https://github.com/dart-lang/language/issues/1618 where it is proposed that the context type (in this case `A`) should be allowed to influence the result of the "least upper bound" computation.

I'll close this issue because it reports the problem which is already the topic of that whole set of issues in the language repository. You might want to vote for https://github.com/dart-lang/language/issues/1618 and/or comment on it.
