### ISSUE TITLE
[stable] [CP] Please cherry pick fix for "Superslow access to variables"

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#53541]
### Commit(s) to merge

8a85dac79214d42493eb22e503cbc8739728f110

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/326242

### Issue Description

Please see https://github.com/flutter/flutter/issues/133195
Users are running into super slow cycles while debugging their Flutter apps

### What is the fix

Avoid searching static functions in the imported libraries, Searching in the imported libraries could be very slow as they can be huge (e.g. the whole Flutter framework)

References to members are fully resolved in kernel. So, when
looking for a static function in the library scope, there is no need to
search in the imported libraries.

### Why cherry-pick

Flutter developers are running into this issue while debugging their apps and is hurting their productivity

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/133195

**Comment by a-siva** [comment]
//cc @alexmarkov

**Comment by itsjustkevin** [comment]
Well, this should have gone to @dcharkes sorry @jakemac53!

**Comment by dcharkes** [comment]
lgtm!

**Comment by sjcons** [comment]
I downgraded from Flutter 3.14 Master with this fix to 3.13.6 Stable to debug and create production builds for API level 33 and this is now working fine. This was not just super-slow access to variables. I could NOT build at API level 33 due to SCUDO memory issues as it would always fail. Much appreciated for getting this done.
