### ISSUE TITLE
Issue on analyzing the compiled app

### ISSUE THREAD

**Issue by wgladforever** [dart-lang/sdk#53556]
So here is wrapdown of the issue. I'm malware analyst and recently I stumbled upon Android application that is based off Flutter. The Flutter as you guys know is built upon Dart. I have application's .apk and .so files and Dart's snapshot (libapp.so - part of this). The app itself seems to be malware oriented and I want to research on how these guys are exploiting some Android's mechanics. My goal is to run sdk's `analyze_snapshot` binary which dumps useful informations in from of .json of the snapshot itself but the issue im having is that the application is built with `debug` flags instead `product` and i get this error when starting this analyzer.
`VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety' but the VM has 'debug no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android no-compressed-pointers null-safety'`

I have 2 questions for this:

1. Can I abuse the fact that malware developers of this app built it under `debug` flags and somehow prompt devtools inside of the app itself or use it in any advantage?
2. Is there any way to reconfigure my sdk so it can actually run `analyze_snapshot` considering that this app has `debug` and `compressed-pointers` flags?

Best regards

**Comment by a-siva** [comment]
The error string you have does not seem to match the description you provided.

You state the app was built with `debug` flags instead of `product` and you are trying to analyze that snapshot with the `analyze_snapshot` binary you have in a release build of the Dart SDK. If that is the case you should get the following error message

`VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'debug no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers no-dedup_instructions no-tsan no-asserts x64 linux no-compressed-pointers null-safety' but the VM has 'release no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers no-dedup_instructions no-tsan no-asserts x64 linux no-compressed-pointers null-safety'`

It appears that you are running the `analyze_snapshot` binary you have in a debug build of the Dart SDK against the application which is built with `product` flags, in that case you will get the error

`VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan no-asserts x64 linux no-compressed-pointers null-safety' but the VM has 'debug no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan no-asserts x64 linux no-compressed-pointers null-safety'`

**Comment by wgladforever** [comment]
@a-siva 

That's correct, you are right. I have built the SDK again in product mode and now I get this error 

`VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety' but the VM has 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android no-compressed-pointers null-safety'`


It seems like the SDK I built has `no-compressed-pointers` where the snapshot I'm analyzing has `compressed-pointers` instead. How do I build the SDK so it has `compressed-pointers`?

Best regards

**Comment by wgladforever** [comment]
@a-siva 

That's correct, you are right. I have built the SDK again in product mode and now I get this error

VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety' but the VM has 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android no-compressed-pointers null-safety'

It seems like the SDK I built has no-compressed-pointers where the snapshot I'm analyzing has compressed-pointers instead. How do I build the SDK so it has compressed-pointers?

Best regards

**Comment by perks** [comment]
hey @wgladforever I'll try to answer some of the outstanding questions you might have.

First off what is provided re: metadata recoverable from a snapshot can be incredibly varied. Due to compiler optimizations, a lot of reverse engineering stuff that would be immediately useful (i.e offsets in the binary to user-defined functions) might not be recoverable. What the tool mostly recovers is various metadata surrounding the snapshot as it related to objects found in the GlobalObject pool, i.e right now it mostly associates constant string objects with references to classes, instances of certain types of objects, etc.

The second issue that can arise (that you ran into) is matching SDK versions to the snapshot you have in question.  Not only do configurations have to match, but you must also be building the SDK version that targets your particular snapshot.

The way to do this is a bit convoluted but basically in your `libapp.so` in the header there should be a snapshot hash associated with the file that is prepended to the configuration string. You have to match this snapshot header with the Dart SDK version you want to check out with. You can see https://github.com/mildsunrise/darter/blob/master/info/versions.md for information on how to do this.

If you are lucky, it is a recent version that has this tool in the source tree. After you `git checkout <sdk_commit>` into the proper version, run `gclient sync -D` to refresh your build  and then build the tool with the following invocation:

`./tools/build.py -mrelease --arch=arm64 --os==android clang_x64/analyze_snapshot`

and a x64 binary that is able to analyze arm64 snapshots should be produced somewhere in the OUT folder under `clang_x64` folder. Prepending clang_x64 to the build target means to produce a cross compiled version, rather than an arm64 analyze_snapshot binary.

Notice when we define the `--arch` flag we pass `arm64`. In modern versions of Dart this is what generates the "no-compressed-pointers". By default most APKs on android will have compressed pointers and that configuration is passed using the arch flag `arm64c`, the `c `at the end being for compressed pointers.

Now if you are in an older version of the tree this is where things get tricky. You will have to backport/cherry-pick changes to the Dart SDK you want and then fix up the source tree to compile correctly. The farther you go back the more difficult it becomes. 

To help you start off this way here are the patches you have to have to use the current version of the analyzer.

```
git fetch https://dart.googlesource.com/sdk refs/changes/00/234500/16 && git cherry-pick -X theirs FETCH_HEAD
git fetch https://dart.googlesource.com/sdk refs/changes/61/252661/20 && git cherry-pick -X theirs FETCH_HEAD
git fetch https://dart.googlesource.com/sdk refs/changes/91/279391/12 && git cherry-pick -X theirs FETCH_HEAD
git fetch https://dart.googlesource.com/sdk refs/changes/70/279970/4 && git cherry-pick -X theirs FETCH_HEAD
git fetch https://dart.googlesource.com/sdk refs/changes/03/308303/12 && git cherry-pick -X theirs FETCH_HEAD
```

Note that at some point this will just stop working. If you end up with a version before September 2021 the chances of you backporting are very slim. 

Once you have it working, take a look at the `analyze_snapshot_api_impl.cc` for how the VM runtime is instrumented. While changes to the JSON format are pretty hard to upstream, if you end up instrumenting additional metadata that you find is useful for you I would particularly be interested in seeing how the tool ends up being used for this purpose.

**Comment by wgladforever** [comment]
Hello, thanks for amazing answer. I have already covered everything you said pretty much including of downloading specific SDK version that has VM that would match my engine in the app Im' reverse engineering. I have updated the config files to support `compressed-pointers` and have started the `analyze_snapshot` binary (which is analyze_snapshot_api_impl.cc related). 
I ran the binary on my `libapp.so` file and it executes successfully but i cant see any output. Shouldn't there be some .json output file in current directory from where I started it?
@perks

**Comment by wgladforever** [comment]
Thanks for answer @perks i finally dumped the json!


My goal is to find bas address of object pool and to find some crucial variable names i know i need to search for and their offsets in object pool so i can later fix cross references in my dissasembled file and search via statical analysis all occurences of it and basically read the compiled (assembly code). On top of that, I got very interesting thing for this analyzer tool and that is function of my suspicious interest and that is the following

```
{
				"id": 4415,
				"name": "PostLoginCodeApi",
				"super_class": "BaseApi",
				"functions": [
					{
						"name": "Function 'get:code': getter.",
						"signature": "(PostLoginCodeApi) => String",
						"offset": 4460720,
						"section": "_kDartIsolateSnapshotInstructions",
						"size": 40
					}
				],
				"lib": "package:otp\/api\/post_login_code.dart"
			}
```

I got amazed thinking this is exact offset of the function (_kDartIsolateSnapshotInstructions + 4460720) but then i saw that this offset is being mentioned in 50 other places such as this one for example 

```
{
				"id": 5169,
				"name": "_Array@0150898",
				"super_class": "FixedLengthListBase<X0>",
				"functions": [
					{
						"name": "Function 'get:length':.",
						"signature": "(_Array@0150898<X0>) => int",
						"offset": 4460720,
						"section": "_kDartIsolateSnapshotInstructions",
						"size": 40
					}
				],
				"lib": "dart:core"
			}
```

and on 50 other places. Could it be that this tool didn't properly extract function offsets and that offsets im seeing here which are shared with other functions might be due to specific compiler optimization settings that my analyzer tool cant see?

**Comment by perks** [comment]
Glad to see it got working. 

That is correct, when you see that same offset reappear in many places it's likely some dummy value that is obtained that resolves to the same value for all function objects in the pool for some reason (my understanding of Dart VM internals is not as deep as others so may be incorrect here). 

Regardless it means that bit of metadata cannot be recovered reliably. In fact a lot of metadata referencing functions in particular is hard if not impossible to recover, see and the related PRs: https://github.com/dart-lang/sdk/issues/52310

Again playing around with exactly what types of things are recoverable can be done in the api implementation layer, and if something ends up helping you out with your task definitely let us know if you can :)

**Comment by wgladforever** [comment]
@perks  Thank you a lot

So the offsets generated by analyzer_snapshot are indeed not reliable. It all goes down the hill because functions that i see in there can't be resolved and I can't find them in my dissasembler and their offsets relative to `_kDartIsolateSnapshotInstructions`.

I'm really wondering, how would people like me approach this type of problems when official SDK tooling can't provide reliable way of examining snapshot and searching some crucial functions that are malicious? My goal is to find functions that are executing when some button is clicked on the screen. I would like to dump all functions that are executing in that moment and filter the most crucial ones. The functions in this case have something to do with encryption. So far, just looking at the `libapp.so` itself after dissasembling it doesn't give me much hope as there are no exported functions but rather its all closed up.

**Comment by perks** [comment]
From this issue it seems you are using an older version of the analyze_snapshot binary as we reworked how functions and code objects are linked in the output. Regardless as this issue was relevant to building the tool which as been resolved we can maybe close this issue as going further may be out of scope.

Without having access to the full output/application in question it would be hard to debug. But realistically even if you were to have offsets of functions, the disassembly would be very difficult to follow even with annotations. Your best bet would be dynamic instrumentation if possible.
