### ISSUE TITLE
[analyzer-lsp] Diagnostics reported in Flutter source files after navigating to files in the Flutter SDK

### ISSUE THREAD

**Issue by mkohlhaas** [dart-lang/sdk#53582]
![Screenshot_20230921_065541](https://github.com/dart-lang/sdk/assets/62170092/f3b15f6b-735e-4af7-ae3d-80abbc84f0cb)

**Is this on purpose? Or did I misconfigure the LSP server?**

Kind regards!

**Comment by lrhn** [comment]
All the missing libraries seem to be Flutter-related. 
Could you be using a Dart SDK analyzer, which doesn't have the Flutter SDK packages and libraries available?

**Comment by mkohlhaas** [comment]
Hi Lasse,

thanks a lot for responding so quickly!

I am not sure what you really mean. I have installed Flutter with `asdf` and it seems to be ok. Installation directory is `.asdf/installs/flutter/3.13.5-stable/packages/flutter/` and looks fine. Under the `lib` directory is e.g `foundation.dart` to be found:

Screenshot is taken from this command:
```shell
ll .asdf/installs/flutter/3.13.5-stable/packages/flutter/lib/;\
ll .asdf/installs/flutter/3.13.5-stable/packages/flutter/lib/src/;\
ll .asdf/installs/flutter/3.13.5-stable/packages/flutter/lib/src/foundation/
```

![Screenshot_20230921_145857](https://github.com/dart-lang/sdk/assets/62170092/80bf3e1a-4f81-492b-b2a4-83d6044efa1c)

When I open a file from a freshly created  Flutter project like `lib/main.dart` I can `goto definition` of e.g. `MaterialApp` - no problemo whatsoever:

![Screenshot_20230921_151131](https://github.com/dart-lang/sdk/assets/62170092/aea92d3d-3d0e-48a5-80b6-38304142fb9c)

But then it stops somehow for some stuff which it cannot find. (All the red wiggly stuff in the screenshot.)

![Screenshot_20230921_151200](https://github.com/dart-lang/sdk/assets/62170092/027e0804-ca88-41cc-9c68-373b6199eaca)

The first screenshot from my initial post is actually from this file (`material/app.dart`).

This is my configuration for the LSP in neovim:

```lua
require("lspconfig").dartls.setup({
            -- cmd = { "dart", "language-server", "--protocol=lsp" },
            cmd = { "/home/schmidh/.asdf/installs/flutter/3.13.5-stable/bin/dart", "language-server", "--protocol=lsp" },
            filetypes = { "dart" },
            init_options = {
                closingLabels = true,
                flutterOutline = true,
                onlyAnalyzeProjectsWithOpenFiles = true,
                outline = true,
                suggestFromUnimportedLibraries = true,
            },
            -- root_dir = root_pattern("pubspec.yaml"),
            settings = {
                dart = {
                    completeFunctionCalls = true,
                    showTodos = true,
                },
            },
            on_attach = on_attach,
        })
```
`cmd` entry doesn't make a change if I use `dart` or `/home/schmidh/.asdf/installs/flutter/3.13.5-stable/bin/dart`.

**Comment by mkohlhaas** [comment]
My guess: When I `goto definition` in my flutter source code file, analyzer uses the package information from `.dart_tool/package_config.json` and jumps to the target without any issues. But being in that target file it has forgotten about all the packages in `.dart_tool/package_config.json` and can't resolve the `import 'package:...;` any more.

I think this is definitely a bug.

**Comment by mkohlhaas** [comment]
Workaround: Using `--packages` option when configuring the language server.

```lua
require("lspconfig").dartls.setup({
            cmd = { "dart", "language-server", "--protocol=lsp", string.format('--packages=%s/.dart_tool/package_config.json', vim.fn.getcwd()) },
            filetypes = { "dart" },
            init_options = {
                closingLabels = true,
                flutterOutline = true,
                onlyAnalyzeProjectsWithOpenFiles = true,
                outline = true,
                suggestFromUnimportedLibraries = true,
            },
            -- root_dir = root_pattern("pubspec.yaml"),
            settings = {
                dart = {
                    completeFunctionCalls = true,
                    showTodos = true,
                },
            },
            on_attach = on_attach,
        })
```

I think this should be done automatically for Dart projects.

**Comment by pq** [comment]
@DanTup: any thoughts?

**Comment by DanTup** [comment]
@mkohlhaas does this reproduce starting from a newly-created `flutter create` project? And does it only occur when using `onlyAnalyzeProjectsWithOpenFiles: true`?

If you can repro on a fresh project, a log file captured by adding the argument `--instrumentation-log-file=/path/to/log.txt` to the server may be helpful. Thanks!

**Comment by mkohlhaas** [comment]
You are too kind. Thank you very much for you support!

---

> @mkohlhaas does this reproduce starting from a newly-created flutter create project?

Yes.

> And does it only occur when using onlyAnalyzeProjectsWithOpenFiles: true?

No.

---

Fresh flutter project:
```shell
flutter create fluttertst
```
LSP start:
```shell
cmd = { "dart", "language-server", "--protocol=lsp", "--instrumentation-log-file=/tmp/instrumentation.log" },
```
What did I do?
- open editor (nvim)
- open file `lib/main.dart`
- `goto definition` `MaterialApp` (line 13 in `lib/main.dart`)
- being in `material/app.dart` I wait for the red squiggly lines to show up and close editor

Two separate runs.
- `onlyAnalyzeProjectsWithOpenFiles = true`
Log file in [instrumentation_01.log](https://github.com/dart-lang/sdk/files/12721110/instrumentation_01.log)
- `onlyAnalyzeProjectsWithOpenFiles = false` in `instrumentation_02.log`.
Uploaded it to [Google Drive](https://drive.google.com/drive/folders/10BzhYtV8GuPNVopktjhxFPQxTFvYVpY5?usp=drive_link) because it was too big for Github.

**Comment by DanTup** [comment]
Ok, so I think this is a similar issue to described in https://github.com/dart-lang/sdk/issues/50311#issuecomment-1295800131

What's happening here, is when you navigate to a file in the Flutter SDK, your editor is adding that project to the current workspace:

```js
{
	"params": {
		"event": {
			"removed": [],
			"added": [
				{
					"uri": "file:\/\/\/home\/schmidh\/.asdf\/installs\/flutter\/3.13.5-stable\/packages\/flutter",
					"name": "\/home\/schmidh\/.asdf\/installs\/flutter\/3.13.5-stable\/packages\/flutter"
				}
			]
		}
	},
	"method": "workspace\/didChangeWorkspaceFolders",
	"jsonrpc": "2.0"
}
```

This creates a new analysis context to try and analyze `package:flutter`, however because there's no `.dart_tool/package_config.json` in your Flutter SDK, the URIs cannot be resolved.

There are two possible solutions:

1. Your editor should not add the Flutter SDK to the workspace when you navigate to it (it's unnecessary and makes the server think it's a project you're working on, rather than just a dependency).
2. Run `flutter update-packages` which will fetch dependencies (and create `.dart_tool/package_config.json` files) for all of the Flutter packages (this is what contributors to Flutter will do so that they can open the project without seeing the same errors you're seeing).

IMO the first option is best - because the behaviour of your editor seems odd to me - jumping to the code file of a dependency should not be a signal that you want to add that project to your workspace and analyze it. I suspect you'll see the same kinds of errors if you jump to something in the Pub cache, because those also don't have `.dart_tool/package_config.json` files. Whether your editor has the ability to control this, I don't know.

The second option is simple and requires no options in your editor, but it will only solve the problem for the Flutter framework (not Pub packages).
