### ISSUE TITLE
[Bug] Static check error

### ISSUE THREAD

**Issue by sun-jiao** [dart-lang/sdk#53597]
```dart
const List<String> sizeUnits = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB'];

String formatFileSize(int bytes) {
  if (bytes < 0) {
    throw ArgumentError('A file could never have a negative size.');
  }

  double size = bytes.toDouble();
  for (String unit in sizeUnits) {
    if (size < 1024 || unit == sizeUnits.last) {
      return size.toStringAsFixed(2) + unit;
    } else {
      size = size / 1024;
    }
  }
}

main() {
  print(formatFileSize(1234));
}
```

I think the following error should not be reported here, because this method always returns a non-null value.

```log
bin/test3.dart:3:8: Error: A non-null value must be returned since the return type 'String' doesn't allow null.
String formatFileSize(int bytes) {
       ^
```

**Comment by lrhn** [comment]
The type system cannot figure out that `unit == sizeUnits.last` guarantees that the `for`-`in` loop cannot complete normally.
You have to have something after the loop, whether `return "unreachable"; or `throw AssertionError("unreachable")`.

Or maybe remove `"PB"` from the list, remove the check inside the loop, and have `return "${size}PB";` after the loop.

**Comment by sun-jiao** [comment]
I have added `return '';`, while I'm wondering if this is fixable?

**Comment by eernstg** [comment]
I don't think it's fixable (in the sense that any fix would be a very special corner case, and we wouldn't want to have a whole zoo of those).

The point is that we may reach the end of the function without returning anything, in which case the specified behavior is to return null, and that's in turn a compile-time error because the return type is `String`.

The reason why the control flow analysis concludes that we can reach the end of the function is that we can't (in general) know that an iterable has any elements, and if `sizeUnits` were empty then you'd reach the end of the function without returning anything,

The flow analysis could give special treatment to the case where the iterable of a `for` loop is a constant expression (so in the given example we would then be able to conclude that the `for` loop body will run at least once). However, this situation is probably so rare that it isn't worthwhile to have a special case for it. Also, we'd immediately hit the other difficulty that @lrhn mentioned:

> The type system cannot figure out that `unit == sizeUnits.last` guarantees [... anything]

You might actually want to go a somewhat different way entirely, by unrolling the loop and expressing everything in terms of the simplest possible (and fastest) tests available:

```dart
const cBytes = 1;
const cKB = 1024 * cBytes;
const cMB = 1024 * cKB;
const cGB = 1024 * cMB;
const cTB = 1024 * cGB;
const cPB = 1024 * cTB;

String _f(double size, String unit) => '${size.toStringAsFixed(2)}$unit';

String formatFileSize(int bytes) => switch (bytes) {
      > cPB => _f(bytes / cPB, 'PB'),
      > cTB => _f(bytes / cTB, 'TB'),
      > cGB => _f(bytes / cGB, 'GB'),
      > cMB => _f(bytes / cMB, 'MB'),
      > cKB => _f(bytes / cKB, 'KB'),
      >= 0 => '${bytes}Bytes',
      _ => throw ArgumentError('A file could never have a negative size.')
    };

// Example usage.
main() {
  print(formatFileSize(1234));
}
```

**Comment by eernstg** [comment]
I'll close this issue because I do not think there is anything we can realistically do about the flow analysis to handle the given situation differently (and it is possible to use a different approach where no such 'artificial' may-return-null situation arises).
