### ISSUE TITLE
There is no way to check if a potentially constant double is `NaN`

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/sdk#53614]
According to the the IEEE-754 specification, `NaN` is never equal to any double, even to `NaN` (!!). Because of this, if one wants to know if a given double is `NaN`, they should use `.isNaN` instead.

See also #44649 and #50481, which are related to a lint to prevent comparison with `NaN` (like `myDouble == double.nan`).

The problem is that we have no way to check if a potentially constant value is `NaN`.

Example:
```dart
// Tentative 1: won't work, as the comparison will always return false
final class NonNanDouble {
  const NonNanDouble(this.value) : assert(value != double.nan); // A double can't equal 'double.nan', so the condition is always 'true'. Try using `double.isNaN', or removing the condition.

  final double value;
}

// Tentative 2: won't even compile, as `value.isNaN` is not a constant value
final class NonNanDouble {
  const NonNanDouble(this.value) : assert(value.isNaN); // Invalid constant value

  final double value;
}
```

If we want to do this check we have to resign the constant constructor.

```dart
// Workaround: now we can't have constant values for the class
final class NonNanDouble {
  NonNanDouble(this.value) : assert(value.isNaN);

  final double value;
}
```

**Comment by lrhn** [comment]
If you know it's a number, you can do `value != value`. That should only be true for NaN.

**Comment by lrhn** [comment]
It is, however, not trivial to match `NaN` in patterns. You have to do `double(isNaN: true)`.

We could *consider* special-casing a constant pattern with the value of `double.nan`, or any NaN value, to _mean_ `double(isNaN: true)`, instead of just being completely useless. 
(A `case double.nan:` can never match. A `case == double.nan:` can, technically, if the matched object has a weird `operator==` which definitely won't be symmetric. That's why I'd only special case the constant pattern, not `== double.nan`.)

It's special-casing, which is icky, but NaN already has special-cased itself when it comes to equality, so this would just be helping the user deal with that.

**Comment by eernstg** [comment]
If we introduce some additional primitive members, cf. https://github.com/dart-lang/language/issues/2219, then `isNaN` is already lined up as a candidate.

**Comment by mateusfccp** [comment]
> If we introduce some additional primitive members, cf. [dart-lang/language#2219](https://github.com/dart-lang/language/issues/2219), then `isNaN` is already lined up as a candidate.

I had completely forgotten about this issue, thanks for bringing it up!

**Comment by mraleph** [comment]
Closed in favor of the existing language issue.
