### ISSUE TITLE
No runtime error if `noSuchMethod` forwarder of a mixin application returns wrong type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53640]
Please see the following program.
```dart
class C {
  int m();
  dynamic noSuchMethod(Invocation i) => "C";
}

mixin M {
  int m();
  dynamic noSuchMethod(Invocation i) => "M";
}

class MA = Object with M;

main() {
  print(C().m()); // Unhandled exception: type 'String' is not a subtype of type 'int'
  print(MA().m()); // prints M
}
```
For `MA().m()` we should have the same runtime error as for `C().m()`
Tested on `Dart SDK version: 3.2.0-191.0.dev (dev) (Fri Sep 22 13:04:22 2023 -0700) on "windows_x64"` and on `Dart SDK version: 3.2.0-edge.09f7f356db63e99a43602e0d2e7061088b31991e (be) (Thu Sep 28 04:02:06 2023 +0000) on "linux_x64"`

**Comment by eernstg** [comment]
@johnniwinther, @chloestefantsova, this is a soundness issue so something needs to be fixed. I labeled the issue as 'area-front-end' at first, because that seemed rather likely. However, the run-time error _does_ occur in DartPad, so it seems to be a VM issue. Do you think there's a front end element of this issue as well?

**Comment by alexmarkov** [comment]
The incorrect behavior is caused by the missing forwarding stub in the mixin application class. Duplicate to https://github.com/dart-lang/sdk/issues/53677.
