### ISSUE TITLE
co19/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A02_t01 failure on dart2js and dart2wasm

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53648]
Tests 
[co19/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A02_t01](https://github.com/dart-lang/co19/blob/master/Language/Classes/Instance_Methods/Method_noSuchMethod/forwarder_A02_t01.dart)
[co19/Language/Classes/Instance_Methods/Method_noSuchMethod/override_A01_t01](https://github.com/dart-lang/co19/blob/master/Language/Classes/Instance_Methods/Method_noSuchMethod/override_A01_t01.dart)

fail at run time on dart2js and dart2wasm. Works on other platforms. Failure logs: [dart2js](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8768717568051087233/+/u/test_results/new_test_failures__logs_) [dart2wasm](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8768717568051087185/+/u/test_results/new_test_failures__logs_)

**Comment by biggs0125** [comment]
I've looked into this a bit and have found the root cause for Dart2JS. The CFE creates a forwarding method to forward calls to noSuchMethod. Dart2JS is treating this forwarder like a real function and adding an implicit type check to the front of the method body. For this specific case, when the function is only meant to forward to noSuchMethod, we can (and should) skip the implicit check.

**Comment by osa1** [comment]
It looks like these tests were somehow fixed, they now pass on all platforms: https://dart-current-results.web.app/#/filter=co19/Language/Classes/Instance_Methods/Method_noSuchMethod.
