### ISSUE TITLE
Is it expected that if case provides different promotion than a type test?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#53652]
I'm just curious if this difference I noticed is expected? Using an if case results in a different inferred type than the is test:

```dart
class A<T> {}

class B<T> implements A<T> {}

main() {
  fn(B<int>());
}

fn(A<int> a) {
  if (a case B()) {
    gn(a); // This works!
  }

  if (a is B) {
    gn(a); // Error: The argument type 'A<int>' can't be assigned to the parameter type 'B<int>'
  }
}

gn(B<int> b) => null;
```

cc @jakemac53

**Comment by lrhn** [comment]
Yes, but only because of raw types being different from object patterns.

When you write a raw type, like `B`, for a generic type, it's instantiated to bounds, so it really means `B<dynamic>`.

The test `a is B` where the current type of `a` is `A<int>` is not checking with a subtype of the current type, so it doesn't promote. 
The same thing applies to the pattern `case B _:`.

What is different is the object pattern `case B():`, which tries to infer the type argument to `B` from the matched value # type, in this case it infers `B<int>`, which _is_ a subtype of `A<int>`, so you can promote to it.

The treatment of raw types is a known stumbling block. It would be nice to do something less obtuse, for example trying to infer the type argument when possible. That's also breaking, so not something we can just do.

Which is an argument for making the `strict raw types` lint recommended.

**Comment by nshahan** [comment]
@lrhn Thanks for the explanation!
