### ISSUE TITLE
create `DateTime` before epoch will cause bug. (Windows)

### ISSUE THREAD

**Issue by h1542462994** [dart-lang/sdk#53699]
Create a `DateTime` instance before epoch will cause bug.

There is the smallest testcase.

```dart
void main() {
  // assign a dateTime before 08:00:00 (+8)

  // now i'm at +8 timeZone in my country.

  // it is before epochTime.
  var dateTime1 = DateTime(1970, 1, 1, 7, 24, 39);

  // it will print `1970-01-01 15:24:39.000 (8:00:00.000000)`
  _printWithTimeZone(dateTime1);

  // it is equal to epochTime.
  var dateTime2 = DateTime(1970, 1, 1, 8, 0, 0);
  _printWithTimeZone(dateTime2);

  // it is after epochTime.
  var dateTime3 = DateTime(1970, 1, 1, 8, 24, 39);
  _printWithTimeZone(dateTime3);
}

void _printWithTimeZone(DateTime dateTime) {
  print("$dateTime (+${dateTime.timeZoneOffset})");
}
```

The print result is:

```
1970-01-01 15:24:39.000 (+8:00:00.000000)
1970-01-01 08:00:00.000 (+8:00:00.000000)
1970-01-01 08:24:39.000 (+8:00:00.000000)
```

It seems that creates the dateTime before epoch will cause a bug, the result is not expected(`1970-01-01 07:24:39.000 (+8:00:00.000000)`), It happens when I want to express the timeOfDay by dateTime with epochDate.

os version: `Windows11 22H2 22621.2283` 

dart version: `3.0.5`

dart info:

```
If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info
|  Memory | CPU | Elapsed time | Command line |
| ------: | --: | -----------: | ------------ |
| 1655 MB |  -- |              | dart.exe     |
|  113 MB |  -- |              | dart.exe     |
|   15 MB |  -- |              | dart.exe     |
|  281 MB |  -- |              | dart.exe     |
|  542 MB |  -- |              | dart.exe     |
|   11 MB |  -- |              | dart.exe     |
|   78 MB |  -- |              | dart.exe     |
```

**Comment by lrhn** [comment]
Doesn't reproduce in UTC+1 on Linux, so I'll have to check it on Windows.

I seem to remember something about Windows not providing time-zones before the epoch.
Since the error is exactly 8 hours, so maybe that is it.

And there is an assumption in the code that deduces the timezone offset for a local-date input, that no time-zone change is ever more than two hours.
Which is correct according to the timezone database, but if Windows sets everywhere to UTC before the epoch, there will be larger jumps at that point. That could be the issue.

(It's non-trivial to go from local-time year/month/etc to a `DateTime`, which contains a msSinceEpoch (UTC) and timezone offset, because you can only ask the OS for the local time-zone offset using an UTC msSinceEpoch, which is what we're trying to find. So it tries to solve for `tzOffsetAt(timeSinceLocalEpoch - tzOffset) == tzOffset`. That includes some guessing and assumptions to find not only *a* solution, but the *desired* solution when there is more than one, and a reasonable answer when there is no solution, both of which can happen around time-zone changes.)

**Comment by lrhn** [comment]
Summary: This is **working as intended** with the available data.

Windows claims all time zone offsets before 1970 is +0:00, which means that 1970-01-01T07:24:39 does not exist as a local time in a location with a UTC+8 time zone, not with either of the surrounding time zones at the time, +0:00 or +8:00. 
Using either would put the resulting time in the range where the other was the correct offset.

So the solution is to use the the point in (UTC) time for `1970-01-01T07:24:39+0:00`, assuming that was what was intended,
and apply the +8:00 time zone offset to that UTC time, yielding the `1970-01-01T15:24:39+8:00` seen here.

_This does not occur on the web (at least not in Chrome, didn't test others), likely because it uses ICU time-zone data instead of asking the operating system. That ensures consistent cross-operating system behavior._
