### ISSUE TITLE
Mixing asynchronous and synchronous io operations?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#53709]
Just wondering: Is it safe to mix synchronous and asynchronous 'dart:io' operations?

For example, a test like https://github.com/dart-lang/co19/blob/master/LibTest/io/Link/create_A02_t03.dart uses both together. As far as I understand (@sgrekhov might have further comments), this does not give rise to any known progress issues (deadlocks), but I still think it would be nice to hear if this mixture gives rise to any special constraints that we'd need to be aware of.

@brianquinlan, WDYT?

**Comment by navaronbracke** [comment]
@eernstg According to the https://dart.dev/tools/linter-rules/avoid_slow_async_io lint, for some operations the sync counterpart is preferred, because it is faster.

So things like this

```
import 'dart:io';

void main() async {
  final File f = File('foo.txt');
  
  if (!f.existsSync()) {
    await f.writeAsString('some content');
  }
}
```

are very common, according to what the lint tells you to do.

**Comment by lrhn** [comment]
I don't see a reason mixing sync and async operations should be more unsafe than just mixing async operations.

The one worry could be that a sync write operation could be blocked on an asynchronous read, and the async read won't complete because the sync operation blocks the isolate.

I don't think that's a problem, because the lock would be in I/O isolate/background priced, where the read will complete, even if the port message with the result won't be received by the original isolate until the sync operation's result had been processed.

As I understand it, I/O happens outside of the isolate, each actual OS call being synchronous and sequential, and results are communicated back to the original isolate using (inherently synchronous) ports afterwards.
(Probably with some optimizations to avoid copying.)

**Comment by eernstg** [comment]
Very good, thanks for the input! Then we won't worry about this.

> each actual OS call being synchronous and sequential

This could be true today, and it would still be possible to start using some OS level asynchrony (e.g., https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/aio_read.2.html), but I would actually expect that change to be benign because it just increases the support offered to the schedulers to avoid deadlocks.

**Comment by brianquinlan** [comment]
> As I understand it, I/O happens outside of the isolate, each actual OS call being synchronous and sequential, and results are communicated back to the original isolate using (inherently asynchronous) ports afterwards.

*async* I/O happens outside of the isolate but synchronous I/O happens in the same isolate.

> (Probably with some optimizations to avoid copying.)

That isn't always possible in the current architecture. `RandomAccessFile.readInto`, for example, is much slower than `RandomAccessFile.readIntoSync` because the buffer being read-into cannot be shared across isolates.

**Comment by brianquinlan** [comment]
Can I close this or do you think that we should take some action in terms of documentation?
