### ISSUE TITLE
`@staticInterop` and generics

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/sdk#53708]
If there any good way to make a `@staticInterop` class generic until extension types lands in stable?

I see only 2 methods with current dart:
1. Give up on `@staticInterop`, making class via dynamic interop would make it possible to add generics.
  But this gives following disadvantages:
   - Possible collision with existing classes of `dart:html` with `@Native` annotation will crash the thing: #53532
   - Opting out of future `wasm` support.
2. Make a wrapper object which would enforce type:
   - You have to make wrapper methods/getters to substitute class, and such wrapper will likely be instantiated on every call. Extension types (#52684) will likely make this a less hustle.
   - Error prone due to `dynamic` going everywhere in underlying layer.

In my actual use case (I'm developing `fetch_client` and `fetch_api`) both methods is inconvenient:
With first we have still not fixed #53532 (which I presume requires a single line change in `@Native` annotation), this causing https://github.com/Zekfad/fetch_client/issues/9
With second it's requires a workaround for generics: https://github.com/Zekfad/fetch_api/issues/3

Also as a related question, will views/extension types be able to passed as `@staticInterop` `external` members, or we would still be required to make a wrapper methods?

**Comment by srujzs** [comment]
You should be able to use generics in `@staticInterop` in 3.2 now that we've re-enabled external extension instance members to be able to use type parameters. We've previously disallowed this due to some worries with dart2wasm JS interop lowerings, but that's not an issue.

Once extension types comes along, that should be even easier to write as you note. I'd avoid creating an expensive wrapper type and either use `@staticInterop` or an extension type for JS interop objects.

Extension types will be allowed to use `external` extension members just like `@staticInterop`. With `dart:js_interop` the erasure will be more obvious, where you can declare the representation type using one of the JS types declared in that library.

**Comment by srujzs** [comment]
I'm going to go ahead and close this issue as the original question is resolved (I believe).
