### ISSUE TITLE
Unexpected `FormatException` for `Process.runSync`

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#53716]
Hello,

Use-case: when I run a command (in my case it's 'ioreg') on macOS and the output of this command contains a broken UTF symbol (�), the terminal is still able to show the output and mark the broken symbol as �.
When the same command is run via `Process.runSync`, the code throws a `FormatException` (because of the decoding error). 

Considering that the output of the 'ioreg' command depends on the end user's system configuration and therefore can contain broken symbols, is there a way to prevent this behaviour (throwing an exception) and get the output anyway (as the standard macOS terminal does)? I tried to look for some way to configure the `runSync`, but didn't find any.

I'm also not sure whether it's a desired behaviour for `runSync` in general.

**Comment by lrhn** [comment]
If the output contains "broken UTF-8", then it's like just *not* UTF-8 encoded. 
The best would be deducing what the actual encoding is, and using that.

Given that the possible encodings are plentiful, and hints are few, it's probably better to do one of two things:
* Pass an error-tolerant encoding to `runSync`.
* Pass an encoding to `runSync` which cannot fail. (If such a thing exists)
* Don't decode the stdout/stderr at all, and work on the lists of bytes.

An error tolerant encoding could be:
```dart
final utf8AllowErrors = Utf8Codec(allowMalformed: true);
var result = Process.runSync(...., stdoutEncoding: utf8AllowErrors, stderrEncoding: utf8AllowErrors);
```
That should convert malformed UTF-8 code units to U+FFFE characters, but shouldn't throw.

A decoding which cannot fail could be `latin1`. It converts every incoming byte to a character, without fail. 
It might not be the character you want, but you can always convert back to bytes and try again later, since the decoding is lossless.

And you can pass *no* encoding to `runSync`:
```dart
final utf8AllowErrors = Utf8Codec(allowMalformed: true);
var result = Process.runSync(...., stdoutEncoding: null, stderrEncoding: null);
```
then [`result.stdout`](https://api.dart.dev/stable/3.1.3/dart-io/ProcessResult/stdout.html) will be a `List<int>` instead of a `String`, and you can try to figure out how it's encoded by looking at the bytes first.
(Notice: An optional parameter which accepts `null`, and makes it mean something *other* than passing no argument, is a bad design. Don't copy that.)

**Comment by incendial** [comment]
Thank you again, `allowMalformed: true` works for me just fine, closing this.
