### ISSUE TITLE
[cfe] [extension types] Implement 'precludes' rule to eliminate method/setter conflicts

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#53720]
This is the CFE specific issue for https://github.com/dart-lang/sdk/issues/53717. Consider the following example (which was taken from #53717):

```dart
extension type E1(int i) {
  set m(_) {}
}

extension type E2(int i) implements E1 {
  void m() {}
}

void main() {
  E2(1).m = 10;
}
```

The common front end does not report any errors for this program, but it should report a compile-time error at the declaration of  `void m() {}` (or nearby), because `E2` has a setter named `m=` and an instance method named `m`, cf. [[1]](https://github.com/dart-lang/language/blob/b17afbd06a63d945636f78b16a7125107c0ccd26/specification/dartLangSpec.tex#L5140) and [[2]](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md#:~:text=All%20name%20conflicts,-specified%20in%20the)).

**Comment by lrhn** [comment]
There are two possible behaviors here, both make sense:
* The one you describe, and currently specified, makes `E2` nvalid because its member signatures contain both an `m=` setter and an `m()` method.
* Alternatively, we could let the `m()` method shadow both an `m` and an `m=` member from the super-extension-type, instead of just the `m` name. 

I think we should go for that latter. We allow completely unrelated declarations to shadow super-interface members, so it seems a little off to not allow you to explicitly add a completely unrelated `m` method when it would *conflict* with an inherited `m=` setter. When a declared method conflicts with another method or getter, it just *wins*, so maybe it should also win in the conflict with an inherited `m=`.

(In which case the example program still has an error, at the `E2(1).m = 10;`, because `E2` doesn't have an `m=` setter.

**Comment by eernstg** [comment]
dart-lang/language#3470 has been accepted by the language team, so we do indeed need to revisit this topic and get the 'precludes' behavior implemented.

I'll reopen this issue for that purpose. @johnniwinther, if you wish to handle this in a different issue then it would be great if you could change the subtask like in https://github.com/dart-lang/sdk/issues/53717 that currently points to this issue such that it points to the new issue that you will create.
