### ISSUE TITLE
[cfe][extension types] overridden method is choosen depending on order in `implements` clause

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53740]
The following test works in analyzer but produces an error in CFE
```dart
// SharedOptions=--enable-experiment=inline-class

class A {
  void foo() {}
}

class B implements A {
  @override
  void foo([int i = 0]) {}
}

extension type ET1(B b) implements A {}

extension type ET2(B b) implements ET1, B {}

void main() {
  var et2 = ET2(B());
  et2.foo(42); // CFE: Error: Too many positional arguments: 0 allowed, but 1 found.
}
```
Expected signature here is `void foo([int])` so there should be no error. But if we change the order of interfaces in `implements` clause  the issue disappears.
```dart
...
extension type ET2(B b) implements B, ET1 {} 
...
 et2.foo(42); // no error
```

cc @eernstg to confirm that an order in `implements` shouldn't make any difference

Tested on `Dart SDK version: 3.3.0-edge.0493c44a87ad9b3471ca3bc68ddfcef81cc9efb5 (be) (Thu Oct 12 00:52:28 2023 +0000) on "linux_x64"`

**Comment by eernstg** [comment]
The signature of `foo` in the interface of `ET2` should be computed as the combined member signature of the member signature of `foo` in `ET1` and in `B`. The order should not matter.

In particular, when the member signatures are such that one has a function type which is a subtype of the function type of the other, then the former is used. In this case, we use the member signature of `B.foo` as the combined member signature of `foo` in `ET2`, because the function type of this member signature is a subtype of the function type of the member signature of `A.foo`.
