### ISSUE TITLE
Implement DTD daemon

### ISSUE THREAD

**Issue by CoderDake** [dart-lang/sdk#53847]

**Comment by a-siva** [comment]
@CoderDake ditto question, why is this listed under area-vm

**Comment by CoderDake** [comment]
I'm unsure why it got the label unfortunately.

**Comment by lrhn** [comment]
Because I had to guess. 😉
The title was uninformative, and the issue has no text, so not a lot to go by if over doesn't know what the words mean. A cursory search suggested it looked like a replacement for the VM-service.

Please always add an area label when filling an issue. Otherwise someone else has to, and they may not know what you know.
