### ISSUE TITLE
Can't extend enums

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#53853]
Currently there is no way to extend enums in Dart. I want to extend an enum (which I can't directly modify) by adding a custom `toString` method. Neither of these work:

```dart
enum Attempt1 extends SomeEnum { ... }

class Attempt2 extends SomeEnum { ... }
```

I want to be able to do something like:

```dart
enum Letter {
  a, b, c
}

enum GroceryItem extends Letter {
  @override
  String toString() => switch (this) {
    Letter.a => 'Apple',
    Letter.b => 'Banana',
    Letter.c => 'Carrot',
  };
}
```

It would be great to also require that all enum constants be re-defined (almost as an override), if the subclass has a custom constructor, e.g.:

```dart
enum Letter {
  a, b, c
}

enum GroceryItem extends Letter {
  // There would be an error if any of these is not defined, since there is a custom constructor
  a('Apple'),
  b('Banana'),
  c('Carrot');

  final String _text;

  const Fruit(this._text);

  @override
  String toString() => _text;
}
```

I think this raises the issue though that a subclass of an enum should not be able to add additional enum constants, because that would break casting an object of the subclass type to the superclass type.

**Comment by lrhn** [comment]
That is just not possible.

You cannot change the `toString` of the existing insurances of the enum type, if you don't have access to modifying the declaration.

If you could create a subclass with another `toString`, and an instance of that subclass which would have that `toString` method, then you have created a _new insurance_ of the enum, different from all existing instances.
It's not the same enum element as the superclass instance that has the same name, or same index, because even element identity is object identity.
It will break exhaustiveness checking of switches.

To make that work, we'd have to completely change how enums work, with them not simply a known finite number of canonicalized instances of a final class.
We'd have to introduce some kind of logical identity, which more objects could share, and the enum type would not be an interface type, more like a logical, structural type containing a specific set of object enum element identities.

Not impossible, I think (after all of 5 minutes of contemplation), but a major change to the language.
It better be worth it.

(It might, if it can allow an enumeration to declare itself as containing a union of other, existing, enumerated values from other enums, which is a common request.)

**Comment by lukehutch** [comment]
I see. OK, so if we forget about overriding `toString` or other methods, what about simply being able to add methods or fields?

```dart
enum GroceryItem extends Letter {
  // There would be an error if any of these is not defined, since there is a custom constructor
  a('Apple'),
  b('Banana'),
  c('Carrot');

  final String text;

  const Fruit(this.text);
}
```

> It will break exhaustiveness checking of switches.

Right, that's why I suggested that probably enum constants should not be able to be added in a subclass. 

Basically I'm looking to extend the functionality of enums by adding properties and/or methods.

What about if this could be done as an extension or mixin?

**Comment by parlough** [comment]
Would an [extension type](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md) work for your use case? These additions would only be resolved statically though.

```dart
enum Letter {
  a, b, c;
}

extension type GroceryItem(Letter l) {
  String get text => switch (l) {
    Letter.a => 'Apple',
    Letter.b => 'Banana',
    Letter.c => 'Carrot',
  };
}

void main() {
  final a = GroceryItem(Letter.a);
  print(a.text); // Prints 'Apple'
}
```

**Comment by lukehutch** [comment]
@parlough Yes, I think that solves my problem, although I can't test it, because I can't seem to figure out how to enable this (brand new) feature (I get an error in VS Code even after upgrading to the latest Dart >3.2.0 and Flutter beta versions).

I'll close this, since it looks like this is intended to work. Thanks!

**Comment by parlough** [comment]
@lukehutch Extension types are still experimental and in-progress. You'll have the best experience on 3.3.0 `main` or `dev` builds and you'll need to [enable](https://dart.dev/tools/experiment-flags) the `inline-class` experiment.

You should also be able to try them out on the [DartPad `main` channel](https://dartpad.dev/?channel=master).
