### ISSUE TITLE
Support `package:js` on the Dart VM

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#53892]
`package:js` allows Dart code that is compiled to JS to interop with JS objects, by providing a way to specify a Dart API for JS objects. This allows Dart code to leverage the enormous amount of existing JS code/packages, but only when targeting the web. Dart apps that run on other platforms might also want to benefit from the packages available in the JS ecosystem, instead of reimplementing the functionality in Dart.

It is already possible to accomplish this, by bundling a JS engine with an app and writing (or maybe rather generating) wrappers that provide a Dart API for JS objects through calling into the JS engine using `dart:ffi`. At least one issue with this approach is that there would have to be two different interop APIs for the same JS object when the same functionality is required on web and native.

Since `package:js` already provides a way to define Dart/JS interop APIs, I'm wondering if it would be possible to extend JS interop support to the Dart VM. The rough idea is that there would be a `JsVm` Dart interface that defines the necessary APIs that the Dart VM would require to implement the `external` elements of a Dart/JS interop class. Users would have to provide a `JsVm` when they want to run JS code:

```dart
@JS()
@staticInterop
class Foo {
  external factory Foo();
}

extension on Foo {
  external String get bar;
}

void main() {
  final jsVm = V8Vm()
  jsVm.start();
  jsVm.load('foo.js');

  runWithJsVm(jsVm, () {
    final foo = Foo();
    print(foo.bar);
  });

  jsVm.close();
}
```

**Comment by mraleph** [comment]
There are two big open questions when we talk about this type of interop:

* Issues with GC around circular data structures;
* Cost of crossing the boundary and wrapping foreign objects (i.e. representing Dart objects on JS side and vice versa);

The first problem is extremely unpleasant to deal with: you easily risk creating non-collectable cycles just by using closures across the boundaries (e.g. attaching listeners to some JS objects).  

`package:js` does not really have to concern itself with either of these two problems because it only needs to support an environment where Dart is running on top of JS. 

While I think it is possible to make `package:js` _kinda_ work on the VM - I am not sure we have any bandwidth to do it.

That being said I think it could be an interesting exercise to consider platform changes that could allow Dart developers to implement this... Maybe macros are the answer here though.

**Comment by blaugold** [comment]
Regarding the circular data structure problem, it seems that at least `JavaScriptCore` has a solution through [`JSManagedValue`](https://developer.apple.com/documentation/javascriptcore/jsmanagedvalue). I haven't looked at other JS VMs.

**Comment by mraleph** [comment]
It don't see how `JSManagedValue` helps to solve reference cycle problems with another GC managed language. 
 
For that you need a fix point marking API which allow two runtimes to perform synchronous marking and `JSManagedValue` is not it.

**Comment by erwamartin** [comment]
I'm developing a web application using Dart and it relies on some external JS libraries imported through JS interop. This setup works fine when the app is run as a web app. However, I also compile this app into an executable to run it on a server for tasks like creating screenshots and PDFs of user content.

Currently, when running the app as an executable, I skip these external JS components, but this is starting to block me.

Does anyone know of an alternative way to handle this situation?

**Comment by mraleph** [comment]
> Does anyone know of an alternative way to handle this situation?

There are two solutions:

- Use JS runtime to run JS code, either by running it in the same process (e.g. loading it as dynamic library via `dart:ffi`) or in a separate process.
- Run the whole application on a JS runtime by compiling Dart code to JS instead of compiling it natively.

**Comment by erwamartin** [comment]
Ah, I see, good points. Thanks for getting back to me.
I'll need to experiment but I assume it will be way slower than running the exe.
