### ISSUE TITLE
Exhaustivness fail for generic constrainted type

### ISSUE THREAD

**Issue by Andrflor** [dart-lang/sdk#53896]
That code should be exhaustive and compile porperly since func type cases are properly matched

```dart
sealed class Action {}

class CreateAction extends Action {}
class ModifyAction extends Action {}

String func<T extends Action>() => switch(T) {
     CreateAction => 'create',
     ModifyAction => 'modify',
     Action => 'action',
  };
  ```
  
  It does not want to compile
  ```
  The type 'Type' is not exhaustively matched by the switch cases since it doesn't match 'Type()'.
  ```
  
  It seems that the exhaustiveness check when used on Type objects does not take into account type constraints.

**Comment by mraleph** [comment]
Comparing runtime types is not part of exhaustiveness checking so this is working as intended. Also note that your switch is not actually exhaustive because it does not match `Never`.

That being said: Runtime types in general are *not* supposed to be used for anything but printing them during debugging. They are not intended for dispatching on them (e.g. comparing them, putting them in maps as keys, etc). It's bad for performance and bad for tree-shaking.

**Comment by Andrflor** [comment]
I forgot Never but it's the same with Never.
This will not compile
```dart
String func<T extends Action>() => switch(T) {
     CreateAction => 'create',
     ModifyAction => 'modify',
     Action => 'action',
     Never => 'nope',
  };
  ```
  
  What's the problem about dispatching runtime types?
  
  Isn't it how bloc register their event handlers?
  Isn't it how flutter dispatch notifications?
  Isn't how inherited widgets/provider works?
  Isn't it how Service locator / DI works?

**Comment by mraleph** [comment]
> I forgot Never but it's the same with Never.

As I said: exhaustiveness does not apply to type objects like this. 

> What's the problem about dispatching runtime types?

The problem is that runtime types are not intended for this. When new language features are designed language team, most likely, does not even consider use of `Type` objects, because they are not supposed to be used. The documentation is quite clear on this: 

> A type object is intended as an entry point for using dart:mirrors.

> Isn't it how bloc register their event handlers?
> Isn't it how flutter dispatch notifications?
> Isn't it how inherited widgets/provider works?
> Isn't it how Service locator / DI works?

That does not mean this are all _good_ uses of `Type` objects from the perspective of how language designers and implementors intended these objects to be used. And you end up paying for that with code size and performance. Virtual dispatch (e.g. overriden methods) and type checks (`is` and `as` operators) are two mechanisms that are intended to be used for dispatch. Using `Type` literals is not. 

```dart
String func<T extends Action>() => switch(T) { /* ... */ }
``` 

I can't stop but think that this code could be written in a different, more Dart-y way. 

If you want you could outline what you are trying to achieve and we can see if it can be written in a different way.

**Comment by lrhn** [comment]
As @mraleph says, it doesn't work because exhaustiveness doesn't work for `Type` objects.

Knowing that *values* exhaust a type is only possible for `enum`s and enum-like platform types like `Null` and `bool`.
All other types can only be exhausted by exhaustive *type* checks.

From the static type system's perspective, there is no difference between `Type t= String;` and `Type t = int;`, it's a *value* with a static type of `Type`, but it could be *any* value of that type, including user created classes like `class NotAType implements Type {} /*...*/ Type t = NotAType();`. 
Exhaustively switching over a `Type` value requires matching *all possible* values of type `Type`.

Just like it cannot know that:
```dart
int i = ...
if (i >= 0 && i < 3) {
  var v = switch (i) {
    0 => "a",
    1 => "b",
    2 => "c",
  };
```
is an exhaustive switch. It's just not *knowable* at the static type level, which is all that is available.

(Not saying it cannot be *done*, but it requires adding more complexity to the static type inference, more *value tracking* and subset analysis, to tell it that the only possible *values* of type `Type` that `T` can evaluate to are `Type` objects for subtypes of `Action`. It'll likely be somewhat fragile - it can only really work when switching on type literals.)

What you *can* do instead is to keep the type variable as a type:
```dart
// Sealed type hierarchy
sealed class Action {}
final class CreateAction implements Action {}
final class ModifyAction implements Action {}

final class _Helper<T> {}
// ...
   String func<T extends Action>() => switch(_Helper<T>()) {
     _Helper<CreateAction>() => 'create',
     _Helper<ModifyAction>() => 'modify',
     _Helper<Action>() => throw "Don't do that",
  };
```
This switch is detected as exhaustive, because the exhaustiveness-algorithm has the types to work with.
It needs to cover `Action` itself, because that is a valid type argument to the function, but doesn't need to cover `Never`.
