### ISSUE TITLE
VM initialization failed: Snapshot not compatible with the current VM configuration

### ISSUE THREAD

**Issue by mgp25** [dart-lang/sdk#53893]
Hello,

**OS:** Windows 10

I am performing a test compiling flutter engine and I am having some troubles with the Dart VM configuration. While the solution is clear enough I am not able to correctly configure it so the Dart VM matches the snapshot. Debug console output:

`[FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Snapshot not compatible with th current VM configuration: the snapshot requires 'product no-code_comments dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts x64 windows no-compressed-pointers null-safety' but the VM has 'product no-code_comments dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-tsan no-asserts ×64 windows no-compressed-pointers null-safety'`

The only difference between the Snapshot and DartVM configuration is the fact `no-tsan` is present. How can I compile it so it matches the snapshot config (so  `no-tsan` don't longer appears).

I have tried to compile it with this:

```
python .\flutter\tools\gn --unoptimized --runtime-mode=release --no-prebuilt-dart-sdk --tsan
```

Trying to add it as an environment variable:

```
GYP_DEFINES="clang=0 target_arch=x64 build_for_tool=tsan"
```

Editing `.gclient` with:

```
gn args out/host_release_unopt
```

And adding:

`is_tsan: true`

even setting the environment variable (which should be the same): `DART_USE_TSAN`

Compilation is done with `ninja`:

```
ninja -C out\host_release_unopt
```

And none of these changes makes no difference in the `flutter_windows.dll` to match the snapshot config. I have been trying to find documentation about this however I haven't found anything apart from what I mentioned above.

I am not sure if this is the best place to ask this but any help is appreciated.

Thanks!

**Comment by mraleph** [comment]
Seems like this is a Flutter Engine build question, not Dart. 

How did you get this snapshot to begin with? You can see in the [code](https://github.com/dart-lang/sdk/blob/5403dc49273dec83d2f22fa3035acf5debc564b3/runtime/vm/dart.cc#L1074) that the feature string should contain either `no-tsan` or `tsan`. It can only be missing if snapshot was created before https://github.com/dart-lang/sdk/commit/9d876d12b2ae77effe65946cdf72f95949293148 (which included `no-tsan` / `tsan` marker into the features string). So my guess would be you are trying to load older snapshot into the new runtime - this is not guaranteed to work. I would expected that you get snapshot format version mismatch before you get to features mismatch. Did you disable any checks? 

> How can I compile it so it matches the snapshot config (so no-tsan don't longer appears).

You need to compile Flutter engine at the version which matches the version which produced the snapshot. 

TSAN is not supported on Windows so no matter what you do you are not going to be able to enable it. Even if you could - you would simply get `tsan` string in the features list, rather than `no-tsan` so feature strings would not match anyway.

**Comment by zr6328** [comment]
In linux-x64 , i received a error that calls Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers no-dedup_instructions no-asserts use_field_guards use_osr no-branch_coverage x64 linux no-compressed-pointers null-safety' but the VM has 'product no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers dedup_instructions no-asserts use_field_guards use_osr no-branch_coverage x64 linux no-compressed-pointers null-safety'. How shoud i do?

**Comment by mraleph** [comment]
There is something wrong with your build @HaskellZhangSong, e.g. you are trying to use snapshot from flutter release build with flutter profile engine, or something like that. Please review your build integration.
