### ISSUE TITLE
Failures on [cfe] Add ClassMember.memberKind and .getTearOff

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#53901]
There are new test failures on [[cfe] Add ClassMember.memberKind and .getTearOff](https://dart-review.googlesource.com/c/sdk/+/332427).

The tests
```
co19/LanguageFeatures/Extension-types/superinterfaces_of_extension_type_A05_t07 CompileTimeError (expected Pass)
```
are failing on configurations
```
cfe-strong-linux
cfe-weak-linux
dart2wasm-linux-chrome
dart2wasm-linux-d8
vm-mac-debug-arm64
vm-mac-release-arm64
```

**Comment by johnniwinther** [comment]
@eernstg Do we have any specification on whether/when we should report errors on property/method and getter/setter conflicts in extension types? I can't seem to guess what co19 expects.

**Comment by eernstg** [comment]
The test co19/LanguageFeatures/Extension-types/superinterfaces_of_extension_type_A05_t07 should be updated, because it expects no errors in a situation where there is a setter/getter signature conflict (and they should be reported here, just as they are reported for classes etc.).

This test is presumably intended to verify that there is no constraint like the override correctness that we enforce with class member override relations. In particular, it's OK to redeclare a getter (in this case: an implicitly induced external getter) as a method.

It looks like the setter/getter signature conflict is an accident, and in that case the test could just use `external final int id2;` to avoid introducing the setter in the first place.

**Comment by eernstg** [comment]
I created a co19 issue here: https://github.com/dart-lang/co19/issues/2335.

**Comment by johnniwinther** [comment]
The test has now been updated and matches our expectations.
