### ISSUE TITLE
[analyzer][Extension types] No error when extension type has a member conflict

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53920]
Test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/superinterfaces_of_extension_type_A05_t08.dart works in CFE but fails in analyzer. The code is
```dart
// SharedOptions=--enable-experiment=inline-class

extension type V(int id) {
  external int id2;
}

extension type ET(int id) implements V {
  int id2() => id; // No expected error in analyzer
//    ^^^
// [analyzer] unspecified
// [cfe] unspecified
}

main() {
  print(ET);
}
```

Tested on `Dart SDK version: 3.3.0-edge.e2aa60ddf362967e17e06ec08871d634a32832c1 (be) (Wed Nov 1 04:17:41 2023 +0000) on "macos_x64"`

**Comment by scheglov** [comment]
Ah, I opened https://github.com/dart-lang/co19/issues/2354
I don't understand why this is a compile-time error.
@eernstg

**Comment by eernstg** [comment]
Actually, I also can't see any conflicts: `ET` has a declaration that induces a getter `int get id` and a method `int id2()`, and it inherits nothing (because `V` has a member named `id` and a member named `id2`, and they are both redeclared by `ET`).

The failure I can see (but I haven't looked into running the test on many configurations) is that the DartPad compiler reports an error on `external int id;`. But that's simply because this is an external getter which is not marked `@JS(...)`, and hence it is rejected by the compiler.

@sgrekhov, what would be conflict be?

**Comment by sgrekhov** [comment]
Please see https://github.com/dart-lang/sdk/issues/53901#issuecomment-1784868636
As far as I understand the key point here is that `external int id2;` is not `final` here and therefore introduces a setter as well. According to dart spec

> It is a compile-time error if the interface of C has an instance method named n and an instance setter with basename n.

**Comment by eernstg** [comment]
Ah, of course, `external int id2` does introduce a setter named `id2=`, and we can't have that in the interface of `ET` together with a method named `id2`. Thanks!

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/334640
