### ISSUE TITLE
VM typed-data lists' `setRange` can mem-copy any typed-data list with the same element size.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#53945]
The VM's internal `_TypedListBase` class has a method with signature
```dart
void setRange(int, int, Iterable, [int = 0]);
```
The `Iterable` is untyped, and the same method is used on every typed-data list.
It checks if the iterable is another `_TypedListBase` with the same `elementSizeInBytes`, and if so, it mem-copies the elements from one list to the other.

This is the _implementation_ class, so the interface member signature
a user sees on, for example, an `Uint8List` is
`void setRange(int, int, Iterable<int>, [int = 0])`.

That means no user is likely to fall into this usage directly when using the typed-data types.

However, if one up-casts, probably to `List<num>`, it might not be as clear:
```dart
import "dart:typed_data";
extension ListCopy<T> on List<T> {
  void copyTo(int start, int end, List<T> to, [int offset = 0]) {
    to.setRange(offset, offset + (end - start), this, start);
  }
}
void main() {
  List<num> ints = Uint32List.fromList([1, 2, 3, 4]);
  Float32List floats = Float32List(4);
  ints.copyTo(0, 4, floats);
  print(floats);
}
```
prints
```
[1.401298464324817e-45, 2.802596928649634e-45, 4.203895392974451e-45, 5.605193857299268e-45]
```
instead of throwing a type error because the source `Iterable` of `setRange` is not an `Iterable<double>`.

It is *probably* not a real problem, just something to be aware of and wary of. 

Code that assumes a `List<num>` and writes to it, and then gets a typed-data `List<int>` or `List<double>` instead,
and then happens to get a typed-data list with the same bit-size as the source as well, that's either a perfect storm of things that should otherwise have broken sooner, or very deliberate.

I don't see users actually wanting to depend on this behavior. It's not necessary for doing a reinterpret-cast, you can just have another view on the same bytes without copying.

But that's also why, if it ever happens, being silently accepted is likely hiding an error.

(But doing nothing is likely fine, if doing something costs performance. And having to check the type of the incoming iterable will almost certainly have to cost something, unless we can determine statically that it's only ever called with something satisfying that type.)

**Comment by dcharkes** [comment]
@eernstg Maybe the co19 tests of TypedData can be beefed up on corner cases. Apparently this wasn't covered.

**Comment by eernstg** [comment]
OK, as I understand this:
- `_TypedListBase.setRange` allows for reinterpret-cast between a narrow set of types with values stored in `typed_data`.
- Those types are `Float32`, `Float64`, `Float32x4`, `Int8`, `Int16`, `Int32`, `Int64`, `Int32x4`, `Uint8`, `Uint16`, `Uint32`, and `Uint64`, but only with a pair of types whose bit length is the same.
- This is not a soundness (or a SEGV!) issue because every bit vector of the relevant length is a valid value of each of these types.

So we could consider this behavior to be similar to a sort-of-arbitrary function applied to each of those types and returning another one of these types with the same bit length.

@sgrekhov, it seems reasonable that we should cover these cases in some co19 tests (`LibTest/typed_data`), such that we will maintain the knowledge that this behavior exists, and also to have some failing tests if it suddenly changes. We shouldn't need more than a couple of cases (e.g., turning 1 into 1.401298464324817e-45 and 0 and -1 into something similarly surprising). It would be great if some comments (e.g., using information from this page) could be included in those tests, such that a future reader won't be completely puzzled about what's going on.

**Comment by sstrickl** [comment]
I'm currently working on [CL 334201](https://dart-review.googlesource.com/c/sdk/+/334201), which makes it so that the example Lasse came up with _doesn't_ work (e.g., fixes the issue seen here). Currently working on tracking down a possible bug in the AOT call specializer which is causing us not to catch it, even after I make the changes to `typed_data_patch.dart` seen there, but you can see the regression test I've added alongside the code changes (which fails on `main`, passes on the branch in JIT, and, as I said, currently fails in AOT on that branch but shouldn't).

**Comment by sstrickl** [comment]
Actually, slightly mistaken, looks like it's in the inliner. At least, if I forcibly tell it to never inline the `copyTo` method, the test passes, but if I allow it to inline it, then it fails, which means the needed check is being dropped in doing so.

**Comment by eernstg** [comment]
@sstrickl, it would be great if you could give some advice on what's the appropriate kind of testing when this topic has been settled!

**Comment by sstrickl** [comment]
Will do!

**Comment by sstrickl** [comment]
So we start with:
```
==== file://.../dart/sdk/runtime/tests/vm/dart/regress_53945_test.dart_::_main_<anonymous closure> (ClosureFunction)
B0[graph]:0 {
      v0 <- Constant(#null)
      v4 <- Constant(#TypeArguments: (Hdad97db) [Type: num]) T{TypeArguments}
}
B1[function entry]:2 {
      v2 <- Parameter(0) T{*?}
}
    v3 <- LoadField(v2 . Closure.context {final}) T{Context}
    goto:6 B2
B2[join]:4 pred(B1)
    v5 <- LoadField(v3 . numList) T{_Uint32List}
    v6 <- LoadField(v3 . float32List) T{_Float32List}
    v7 <- StaticCall:12( ListCopy|copyTo<1> v4, v5, v6) T{void?}
    Return:16(v7)
```

While inlining `ListCopy<num>|copyTo`, we start with:

```
==== file:///.../dart/sdk/runtime/tests/vm/dart/regress_53945_test.dart_::_ListCopy|copyTo (RegularFunction)
B0[graph]:0 {
      v8 <- Constant(#TypeArguments: (Hdad97db) [Type: num])
      v9 <- Constant(#null)
      v16 <- Constant(#0)
}
B3[function entry]:2 {
      v13 <- Parameter(0) T{_Uint32List}
      v14 <- Parameter(1) T{_Float32List}
}
    v17 <- StaticCall:26( get:length<0> v13, recognized_kind = TypedListBaseLength, result_type = T{_Smi})
    InstanceCall:28( setRange<0>, v14, v16, v17, v13 IC[0: ] using unchecked entrypoint)
    Return:32(v9)
```

And the `ApplyClassIds` compiler pass turns that `InstanceCall` into a `StaticCall` to `_Float32List.setRange`, still using the unchecked entrypoint:

```
==== file:///.../dart/sdk/runtime/tests/vm/dart/regress_53945_test.dart_::_ListCopy|copyTo (RegularFunction)
B0[graph]:0 {
      v8 <- Constant(#TypeArguments: (Hdad97db) [Type: num])
      v9 <- Constant(#null) T{Null?}
      v16 <- Constant(#0) T{_Smi}
}
B3[function entry]:2 {
      v13 <- Parameter(0) T{_Uint32List}
      v14 <- Parameter(1) T{_Float32List}
      v15 <- SpecialParameter(ArgDescriptor)
}
    v17 <- StaticCall:26( get:length<0> v13, recognized_kind = TypedListBaseLength, result_type = T{_Smi}) T{_Smi}
    StaticCall:28( setRange<0> v14, v16, v17, v13, using unchecked entrypoint)
    Return:32(v9)
```

However, we're replacing an `InstanceCall` to a interface target of type `void Function(int, int, Iterable<num>, [int?])` to a `StaticCall` to a function of type `void Function(int, int, Iterable<double>, [int?])`, which is not a subtype, and thus the `StaticCall` shouldn't be using the unchecked entry point just because the original `InstanceCall` did.

**Comment by sgrekhov** [comment]
@sstrickl is this issue ready for testing? What outcome should tests expect?

**Comment by sstrickl** [comment]
You can look at `runtime/tests/vm/dart/regress_53945_test.dart` after the submitted CL above to see that Lasse's example now throws an error. That is, upcasting and then attempting to call `setRange` with an `Iterable` that has an incompatible element type (compared to the original upcasted typed data object's element type) now should properly cause a type error to be thrown.

**Comment by sgrekhov** [comment]
@sstrickl thank you! It's what I'm doing right now :)

**Comment by sgrekhov** [comment]
[co19/LibTest/typed_data/Float32List/setRange_A06_t01](https://github.com/dart-lang/co19/blob/master/LibTest/typed_data/Float32List/setRange_A06_t01.dart) is still failing on on AOT (see https://dart-current-results.web.app/#/filter=co19/LibTest/typed_data/Float32List/setRange_A06_t01)

**Comment by mkustermann** [comment]
@sstrickl could you have a look?

**Comment by sstrickl** [comment]
Taking a look now.

**Comment by sstrickl** [comment]
```
*** BEGIN CFG
Before Inlining
==== file:///usr/local/google/home/sstrickl/dart/sdk/tests/co19/src/LibTest/typed_data/Float32List/setRange_A06_t01.dart_::_main_<anonymous closure> (ClosureFunction)
B0[graph]:0 {
      v0 <- Constant(#null) T{Null?}
      v1 <- Constant(#<optimized out>)
      v5 <- Constant(#0) T{_Smi}
      v6 <- Constant(#4) T{_Smi}
}
B1[function entry]:2 {
      v2 <- Parameter(0) T{*?}
}     
    v3 <- LoadField(v2 . Closure.context {final}) T{Context}
    goto:6 B2
B2[join]:4 pred(B1)
    CheckStackOverflow:8(stack=0, loop=0)
    DebugStepCheck:10()
    v4 <- LoadField(v3 . floats) T{_Float32List}
    v7 <- LoadField(v3 . ints) T{_Uint32List}
    StaticCall:12( setRange<0> v4, v5, v6, v7, using unchecked entrypoint)
    DebugStepCheck:14() 
    Return:16(v0)
*** END CFG 
```

So it looks like we're getting the unchecked entrypoint version of this, which will bypass the checking. #54163 fixed this in some cases when the callsite became polymorphic (e.g., `copyTo` in [vm/dart/regress_53945](https://github.com/dart-lang/sdk/blob/main/runtime/tests/vm/dart/regress_53945_test.dart)), but here we don't have a polymorphic call site.

The kernel generated by TFA:
```
  import "dart:typed_data";
  import "file:///usr/local/google/home/sstrickl/dart/sdk/tests/co19/src/Utils/expect.dart";

[@vm.closure-id=1]  static method main() → void {
    [@vm.inferred-type.metadata=dart.typed_data::_Uint32List] core::List<core::num> ints = [@vm.inferred-type.metadata=dart.typed_data::_Uint32List] typ::Uint32List::fromList([@vm.inferred-type.metadata=dart.core::_GrowableList] core::_GrowableList::_literal4<core::int>(1, 2, 3, 4));
    [@vm.inferred-type.metadata=dart.typed_data::_Float32List] typ::Float32List floats = [@vm.inferred-type.metadata=dart.typed_data::_Float32List] typ::Float32List::•(4);
    exp::Expect::throws([@vm.closure-id=1]() → void {
      [@vm.direct-call.metadata=dart.typed_data::__Float32List&_TypedList&_DoubleListMixin.setRange] [@vm.call-site-attributes.metadata=receiverType:dart.typed_data::Float32List] floats.{core::List::setRange}(0, 4, ints){(core::int, core::int, core::Iterable<core::num>, [core::int]) → void};
    });
  }
```

(Note that I don't see any skipped checks above like we did in #54163, so this doesn't look like an issue in TFA, but ccing @alexmarkov in case he sees something I don't.)

So we know that `setRange` here is being called on a `Float32List`, which means it's specifically the `setRange` from `_DoubleListMixin` that has type `(int, int, Iterable<double>, [int]) -> void`, and we're passing in a `List<num>` (that TFA also knows is actually a `_Uint32List`). That check that `ints is Iterable<double>` happens on the checked entry, but since we're using the unchecked entry here, it gets skipped.

So the main question here is why, for a call that TFA did not mark as unchecked, did the VM decide it should be unchecked anyway? Looking into that now.

**Comment by sstrickl** [comment]
```c++
Fragment StreamingFlowGraphBuilder::BuildMethodInvocation(TokenPosition* p,
                                                          bool is_dynamic) {
  ...
  if (!is_dynamic && (call_site_attributes.receiver_type != nullptr) &&
      call_site_attributes.receiver_type->HasTypeClass() &&
      !call_site_attributes.receiver_type->IsDynamicType() &&
      !Class::Handle(call_site_attributes.receiver_type->type_class())
           .IsGeneric()) {
    is_unchecked_call = true;
  }
  ...
}
```

There's the problem, I think. `Float32List` itself is not generic. However, via`_DoubleListMixin`, it implements `List<double>`, and the method being statically called is an implementation of a `List<E>` method. Hmm.

**Comment by sstrickl** [comment]
A quick fix that might be correct would be to also check whether the type of the receiver from the direct called method (here, `List<double>`) is generic as well before assuming we can use the unchecked entry. The direct called method should be available since this isn't a dynamic call, if I'm reading this correctly. Need to think about it a little bit more.

**Comment by sstrickl** [comment]
The other option is for TFA to report the receiver type based on its relation to the type of the receiver in the direct called method, not the concrete type (that is, report it as `List<double>`, not as `Float32List`), which would make the check here enough.

**Comment by sstrickl** [comment]
Looking at the kernel some more, the front end tells the VM what the types of the arguments are, specifically that the third (non-receiver) argument has type `Iterable<num>`, which is not a subtype of the `Iterable<double>` parameter the direct call method has. That's enough information to help us realize that we can't do the unchecked version here, the VM just isn't noticing it, assuming that a non-generic receiver is enough (forgetting that there can a non-generic receiver can implement a specific instantiation of a generic class with generic method parameters, which is the problem here).

**Comment by alexmarkov** [comment]
VM omits parameter type checks if _static type_ of the receiver is not generic. It relies on the fact that parameter types should be fully checked by the front-end in this case. This assumption is valid and we should not remove it. The bug here is that VM-specific kernel transformation adjusts AST and changes static type of the receiver _after_ CFE already checked everything.

Source:
```
  List<num> ints = Uint32List.fromList([1, 2, 3, 4]);
  Float32List floats = Float32List(4);
  (floats as List<num>).setRange(0, 4, ints);
```

Kernel before VM-specific lowering transformation:
```
    core::List<core::num> ints = typ::Uint32List::fromList(<core::int>[1, 2, 3, 4]);
    typ::Float32List floats = typ::Float32List::•(4);
    (floats as core::List<core::num>).{core::List::setRange}(0, 4, ints){(core::int, core::int, core::Iterable<core::num>, [core::int]) → void};
```
Kernel after VM-specific lowering transformation which removes redundant cast:
```
    core::List<core::num> ints = typ::Uint32List::fromList(core::_GrowableList::_literal4<core::int>(1, 2, 3, 4));
    typ::Float32List floats = typ::Float32List::•(4);
    floats.{core::List::setRange}(0, 4, ints){(core::int, core::int, core::Iterable<core::num>, [core::int]) → void};
```

The undesired side-effect of removal of the redundant cast is that it changes the static type of the receiver in the AST.

Fix for the removal of redundant type casts: https://dart-review.googlesource.com/c/sdk/+/351621.

**Comment by sstrickl** [comment]
Got it. Thanks for explaining this and for creating the appropriate fix!
