### ISSUE TITLE
Breakpoint tests failing on path case difference

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#53949]
The tests
```
pkg/dds/test/dap/integration/dart_test_test RuntimeError (expected Pass)
pkg/dds/test/dap/integration/debug_breakpoints_test RuntimeError (expected Pass)
pkg/dds/test/dap/integration/debug_eval_test RuntimeError (expected Pass)
pkg/dds/test/dap/integration/debug_services_test RuntimeError (expected Pass)
pkg/dds/test/dap/integration/debug_stack_test RuntimeError (expected Pass)
pkg/dds/test/dap/integration/debug_test RuntimeError (expected Pass)
pkg/dds/test/dap/integration/debug_variables_test RuntimeError (expected Pass)
pkg/dds/test/dap/integration/no_debug_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win-arm64
```

@bkonyi Possibly the logic from a62bfec074e6ac782928c2e5dd4a5429da668191 needs to applied in more places?

**Comment by bkonyi** [comment]
FYI @DanTup

**Comment by DanTup** [comment]
Where can I find logs of these failures?

We do have existing issues around case-sensitivity of paths (for ex https://github.com/dart-lang/sdk/issues/32222). There are a lot of places in Dart that assume paths are case sensitive.

I'm curious whether these failures are due to drive letters only (it's pot luck what casing we get drive letters in, based on various factors), or other parts of the path.

**Comment by DanTup** [comment]
Think I found them at https://dart-ci.firebaseapp.com/#configurations=unittest-asserts-release-win-arm64

Example failure: https://dart-ci.appspot.com/log/pkg-win-release-arm64/unittest-asserts-release-win-arm64/13/pkg/dds/test/dap/integration/dart_test_test

```
01:44 [32m+3[0m[31m -1[0m: dart test can hit and resume from a breakpoint [1m[31m[E][0m[0m

  Expected: 'c:\\opt\\s\\w\\ir\\x\\t\\dart-sdk-dap-test45334424\\app9f8f10bc\\test_file.dart'
    Actual: 'C:\\opt\\s\\w\\ir\\x\\t\\dart-sdk-dap-test45334424\\app9f8f10bc\\test_file.dart'
     Which: is different.
            Expected: c:\\opt\\s ...
              Actual: C:\\opt\\s ...
                      ^
             Differ at offset 0
```

So it is the drive letter. In the DAP changelog we have:

- [DAP] Paths provided to DAP now always have Windows drive letters normalized to uppercase to avoid some issues where paths may be treated case sensitively.

So it seems like the `expected` is wrong, and `actual` is correct. The expectations are probably coming from here:

https://github.com/dart-lang/sdk/blob/6137e932417faa83e93719a7a7fb3bc4e2189ffa/pkg/dds/test/dap/integration/test_support.dart#L136-L144


If `Directory.systemTemp` has a lowercase drive letter, then the expectations will be the same. The fix is likely to just normalise this directory in the tests so expectations are always uppercase. I can take a look next week.

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/334160

I fixed it by changing the expectations rather than changing the source path - this gives some extra validation that on a system where the drive letter of the open workspace is lowercase, we still get what we expect (which is always uppercase drive letters on paths outbound from DAP).
