### ISSUE TITLE
FFI: NativeCallable return value

### ISSUE THREAD

**Issue by NiallBunting** [dart-lang/sdk#53965]
Is there any way to use NativeCallable with functions that don't just return void? I'm trying to handle a callback from C.

For example this is my dart code. I expect the C to call `myFunc` at anytime in the future with updates.
```
// My dart function that will get called
int myFunc(int handle, int method, Pointer<Uint8> args_data) {
  return 0;
}

// Create the listener
static final listener = NativeCallable<Typedef>.listener(myFunc);

// Call the C program with a pointer to the listener
lib.register_callback(listener.nativeFunction);
```

I'm also interested in why only void functions were considered?

I also found this test, which seems suggest that's its possible: https://github.com/dart-lang/sdk/blob/f6fad5424099ada338f4c040d7268b231c34d0cf/pkg/vm/testcases/transformations/ffi/native_callable.dart.expect#L79

**Comment by a-siva** [comment]
//cc @dcharkes @liamappelbe

**Comment by liamappelbe** [comment]
There are 2 kinds of `NativeCallable`: `NativeCallable.listener` and `NativeCallable.isolateLocal`. Listeners are asynchronous callbacks (and can be called from any thread), and isolateLocals are synchronous (and must be called from the correct thread). IsolateLocals can return a result, but listeners can't.

`NativeCallable.isolateLocal` is coming soon in Dart 3.2. If you need a synchronous callback now, you can use [`Pointer.fromFunction`](https://api.dart.dev/stable/3.1.0/dart-ffi/Pointer/fromFunction.html). `NativeCallable.isolateLocal` is essentially just a more convenient API for `Pointer.fromFunction`.

As for why `NativeCallable.listener` is not allowed to return a result, that's because it's an async callback. It's designed for the case where the callback is being invoked from a different thread than the isolate that owns the callback. So when the callback is invoked, it sends a message to that isolate to tell it to run the callback. Once the message is sent, the native code doesn't wait for a response (it's a fire-and-forget style call). Since the native code doesn't wait for a response, the callback can't return a value to the native code.

It would be possible to add a third variant of `NativeCallable`, which blocks the native code until it can receive a response from the callback. But this is a bit of a foot-gun, so we wanted the default behaviour to be fire-and-forget. If someone has a very compelling use case for this kind of blocking callback, we'll add it.

> I'm trying to handle a callback from C.

Can you tell me more about your use case? Do you need async callbacks or sync callbacks? What thread is your callback being invoked from?

> I also found this test, which seems suggest that's its possible

This test is testing `NativeCallable.isolateLocal`.
