### ISSUE TITLE
Bad completion/recovery when typing before `await`

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#53964]
This seems similar to #49477 except it's with `await` instead of a nested function. The ASTs are a little different so I'm raising a new issue, but feel free to close if it seems like they're the same. It was raised at https://github.com/Dart-Code/Dart-Code/issues/4825 by @JCKodel.

```dart
Future<void> main() async {
  a. // Trying to type a new line of code here before an `await`
  await a.mAsync();
}

final a = A();

class A {
  void m() {}
  Future<void> mAsync() async {}
}
```

You'd expect to see `m()` listed in the completion because it's valid to call here.

![image](https://github.com/dart-lang/sdk/assets/1078012/a4798dea-099a-4fa8-a9b6-1c9fee8f54d3)

The AST has `a.await` joined together as a type:

```
┊   ┊   ┊   ┊   BlockImpl [26..56]
┊   ┊   ┊   ┊   ┊   VariableDeclarationStatementImpl [31..43]
┊   ┊   ┊   ┊   ┊   ┊   VariableDeclarationListImpl [31..43]
┊   ┊   ┊   ┊   ┊   ┊   ┊   NamedTypeImpl [31..41]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name = a.await
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        type = InvalidType
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊   ImportPrefixReferenceImpl [31..32]
┊   ┊   ┊   ┊   ┊   ┊   ┊   VariableDeclarationImpl [43..43]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        declaredElement = InvalidType a
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name = a
┊   ┊   ┊   ┊   ┊   ExpressionStatementImpl [44..53]
┊   ┊   ┊   ┊   ┊   ┊   MethodInvocationImpl [44..52]
┊   ┊   ┊   ┊   ┊   ┊   ┊        static invoke type = InvalidType
┊   ┊   ┊   ┊   ┊   ┊   ┊        static type = InvalidType
┊   ┊   ┊   ┊   ┊   ┊   ┊   SimpleIdentifierImpl [44..43] (synthetic)
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name =
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        static type = InvalidType
┊   ┊   ┊   ┊   ┊   ┊   ┊   SimpleIdentifierImpl [45..50]
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        name = mAsync
┊   ┊   ┊   ┊   ┊   ┊   ┊   ┊        static type = InvalidType
┊   ┊   ┊   ┊   ┊   ┊   ┊   ArgumentListImpl [51..52]
```

I'm not sure whether this is something completion should work around, or whether the AST could be improved.

**Comment by bwilkerson** [comment]
The Dart parser doesn't have support for backing up during recovery, which would make it very hard to do a better job of recovering from this situation. Hence, at least for the time being, we need to work around such structures during recovery.

That said, recovering in this case might be difficult because it might effectively require re-parsing the input to see whether it is, in fact, reasonable to complete in that location. (Though there might be some heuristics we could use to simplify the fix. Specifically, noting that the cursor is after the period but not touching the following identifier.)

**Comment by scheglov** [comment]
It turned out that *detective* the location is relatively easy.
But it is parsed as `a.await a;`.
Which mean that the `a` before `.await` is considered to be hidden by this local variable declaration.
And its type is `InvalidType`.

So, it looks that recovery during completion is too late.
We need to parse and resolve correctly.

**Comment by scheglov** [comment]
I ended up removing the detecting code, and patching AST during parsing.
This way we don't need anything special from the completion implementation.
We just get normal `PrefixedIdentifier`.
https://dart-review.googlesource.com/c/sdk/+/357520
