### ISSUE TITLE
It is not possible to test if StreamSink is closed

### ISSUE THREAD

**Issue by moham96** [dart-lang/sdk#54015]
Hi,
Using `StreamController` you can test if the sink is closed by checking the `isClosed` property:

```dart
if (StreamController.isClosed) return;

// we push data to the controller
```
but if we pass `StreamSink` we can't test if it is closed or not to decide whether to add data or not, there is no `StreamSink.isClosed` !

regards

**Comment by lrhn** [comment]
Correct.

A `StreamSink` is a very primitive interface, all push, no obvious state, because it could be a wrapper around something else, and we don't want to force it to maintain its own state.

So no state inspection either.

We're unlikely to change the `StreamSink` interface without very good reason, since it would break every implementation of it.

So, no plan to change.
