### ISSUE TITLE
`unawaited_futures` auto-fix changes program behaviour

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/sdk#54022]
Area  `Dart analyzer and linter`

# Reproduce
1) `dart create unawaited_lint_bug`
2) put the following in `bin/unawaited_lint_bug.dart`
```dart
import 'dart:async';

void main(List<String> arguments) async {
  Completer completer = Completer();

  completer.future; // <----------- this will be linted as missing await / unawaited()

  completer.complete();

  print("End");
}
```
3) put the following in `analysis_options.yaml`
```yaml
include: package:lints/recommended.yaml

linter:
  rules:
    - unawaited_futures
```
4) If you are on vscode, a typical setup may further include in `.vscode/settings.json`
```json
{
    "editor.codeActionsOnSave": {
        "source.fixAll": true  // <--------- Will auto apply fixes suggested by the linter
    }
}
```

# The issue

The automatic fix for the lint will change the program to the following:
```dart
import 'dart:async';

void main(List<String> arguments) async {
  Completer completer = Completer();

  await completer.future; // <-------------------- We will now forever wait here, which we did not do before

  completer.complete();

  print("End");
}
```

This can introduce bugs that may be overlooked and hard to find afterwards.

This means the `unawaited_futures` is unusable in an environment where lint fixes are automatically applied.
(Which may be a desired workflow for auto-fixing `const` and ordering imports etc)

# Suggested fix

The fix for the lint should instead add `unawaited` or include no automatic fix

**Comment by bwilkerson** [comment]
@DanTup Another place where `fixAll` might be too aggressive.

I'm not sure why we're getting this fix applied, though. There are two fixes for `unawaited_futures`, and I thought that we didn't automatically apply fixes when there was more than one fix to choose between.

**Comment by DanTup** [comment]
The reason we auto-fix this is that we only find one fix. The reason we only find one fix is that `AddAwait` is marked as `canBeAppliedInBulk=true` but `WrapInUnawaited` is not.

We could exclude `AddAwait` from fix-on-save, although it would still leave `dart fix` making the same fix and it's not clear to me if that's desired. Should we instead mark neither of them as bulk-fixable (or both, which I think would essentially be the same thing)? I don't think we should apply `unawaited` automatically just because it preserves the current program behaviour here, as I think the reason for having the lint enabled is to catch places where you might have accidentally missed an `await` and auto-fixing to `unawaited()` seems worse than just turning off the lint (because it makes missing awaits seem deliberate where they might be accidental).
