### ISSUE TITLE
every() method in List<T> should return true for empty list?

### ISSUE THREAD

**Issue by joaoantoniomartinsfilho** [dart-lang/sdk#54044]
Oi, guys! How are you doing?

I'm new around here, so I'm sorry for anything...

During my coding time, I faced a behavior that I didn't know had to be that way, but then when I did some research and read the [list.dart](https://github.com/dart-lang/sdk/blob/5e423052aec155fdb958124f8370838d522e6aa0/sdk/lib/collection/list.dart#L100) file from the SDK I realized that according to the implementation that was an expected behavior. Well, my point is: should the Every method return true for an empty list? In my opinion, It shouldn't be because there are no elements to execute the predicate, we can think like students in a classroom, are all students over 18 years old? if there are no students inside the room we couldn't know so we should respond with "No" in this case.

**Original Implementation:**
```dart
bool every(bool test(E element)) {
    int length = this.length;
    for (int i = 0; i < length; i++) {
      if (!test(this[i])) return false;
      if (length != this.length) {
        throw ConcurrentModificationError(this);
      }
    }
    return true;
}
```

Does anyone have another point of view related to this? 

Kind regards.

**Dart Info:**
- Dart 3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Enterprise" 10.0 (Build 22621)
- locale is en-US

**Comment by joaoantoniomartinsfilho** [comment]
Hi @julemand101, thanks for the answer. After reading your example actually makes sense thanks!  I will close the issue!

Have a nice week.

**Comment by mraleph** [comment]
I suggest considering the duality between `every` and `any`, e.g. "are all students > 18 years old?" is equivalent to "it is not true that there is a student which is <= 18 years old":

```
list.every((s) => s.age > 18) == !list.any((s) => s.age <= 18)
```

`any` is obviously never true for an empty list, this means that for the duality to hold `every` has to be `true` for every list.

**Comment by lrhn** [comment]
What @mraleph says.

The `every` method is modelled on the mathematical &forall; quantifier, which is true (often explicitly called "trivially true") when applied to an empty set: "&forall;_x_&in;_S_&puncsp;_x_\>18" is true if _S_ is empty.
One reason is because that makes it the dual of the "exists" quantifier, "&exist;_x_&in;_S_&puncsp;_x_&le;18", which is what the Dart `any` method is modelled on.

But, equally important, it's because the &forall;/`every` applies to a _combined_ collections/iterable as the "and" of the same test applied to each part:
`(values1.followedBy(values2)).every(test)` is true if and only if `values1.every(test) && values2.every(test)` is true.

In math: &forall;_x_&in;_S<sub>1</sub>_&cup;_S<sub>2</sub>_&puncsp;*P*(_x_)  &iff; (&forall;_x_&in;_S<sub>1</sub>_&puncsp;*P*(_x_) &wedge; &forall;_x_&in;_S<sub>2</sub>_&puncsp;*P*(_x_))

That looks somewhat obvious, but for it to actually hold, doing `.every(test)` on the empty iterable _must_ give true, because `values1.followedBy(Iterable.empty())` is extensionally the same iterable as `values1` (it has the same elements in the same order), and therefore `values1.every(test) && Iterable.empty().every(test)` should therefore have the same value as just `values1.every(test)`. And `true` is the neutral element for `&&`, so it must be true.

That is: `empty.every(test)` is true for good historical reasons, which come from good equational reasons about how a &forall;-predicate distributes over a union.

**Comment by joaoantoniomartinsfilho** [comment]
Thanks for the answers guys, after the @lrhn comment I did some research on mathematical logic about the theory behind the universal quantifier and existential quantifier, basically one is the opposed of the other, that why in an empty Set (_S_) the ∃ quantifier returns false and the ∀ quantifier returns true. Well at least this is what I understood 🤣
