### ISSUE TITLE
SDK builders should preserve symbols for binaries (at least for stable and beta).

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#54054]
Currently we don't preserve symbols for binaries like `dart` released in Dart SDK, this makes it hard to do any sort of postmortem debugging. 

Our builds are mostly reproducible so it should be possible to build unstripped binary for debugging purposes - but this does not always work (e.g. I am struggling right now to build a 2.18.7 Linux X64 `dart` binary which matches released version).

/cc @athomas @sortie

**Comment by sortie** [comment]
The official Dart SDK builders upload the unstripped final release binaries to cloud storage, e.g.:

gs://dart-archive/channels/stable/raw/2.18.7/unstripped/linux/x64/dart

Does that solve your need?

**Comment by mraleph** [comment]
That's fantastic! Thanks @sortie. We should document that somewhere.

**Comment by sortie** [comment]
The layout and existence of these unofficial cloud storage artifacts are subject to change. In fact I have one or two proposals in mind that would affect these. E.g. when I renamed the be channel to main, I was able to bypass the breaking change policy because these artifacts were not documented as official products and people could not rely on them. :)

I'm fine with documenting this layout in public as long as it's with that caveat attached, although well intentioned people could still accidentally start relying on artifacts that aren't official. We could make those unstripped binaries official tho :)
