### ISSUE TITLE
What can go wrong with using records for equality and hashing?

### ISSUE THREAD

**Issue by water-mizuu** [dart-lang/sdk#54096]
In some of my model classes, I have the following pattern:

```dart
@immutable
class Tag {
    final Color color;
    final String name;

    const Tag({required this.color, required this.name});

    (Color, String) get _rec => (color, name);
    
    @override bool operator ==(Object other) => other is Tag && _rec == other._rec;
    @override int get hashCode => _rec.hashCode;
}
```

While this is working, I know that this is not good practice. However, I wonder what are all the possible downfalls with this? (Apart from self-reference.)

**Comment by lrhn** [comment]
As you mentioned, cyclic dependencies is a problem, but it would be for a direct implementation that calls `==` on field values blindly, it's not new to using records.

If the compiler can always inline the `==` and `hashCode` invocations, and the `_rec` calls, and then allocation-sink the records, the I think this should work just the same as:
```dart
@immutable
class Tag {
    final Color color;
    final String name;

    const Tag({required this.color, required this.name});
    
    @override bool operator ==(Object other) => other is Tag && color == other.color && name == othername;
    @override int get hashCode => Object.hash(color, name);
}
```
Because that's pretty much what `(Color, String)` does for its `hashCode` and `operator==`. (Maybe adds some extra integer to the hashCode, something to represent the shape, to avoid `(Color, String)`, `({Color hue, String htmlText})` and `({Color color, String name})` from all hashing the same values to the same hash code.)

The only real risk is that not everything gets inlined, and then you have an unnecessary overhead.

(Heck, you can even store the values directly in a record, from the start:
```dart
@immutable
class Tag {
    final ({Color color, String name}) _rec;
    Color get color => _rec.color;
    String ge name => _rec.name;

    const Tag({required this.color, required this.name}) : _rec = (color: color, name: name);
    
    @override bool operator ==(Object other) => other is Tag && _rec == other._rec;
    @override int get hashCode => _rec.hashCode;
}
```
I have no idea whether that's a good idea or not. It probably isn't. OK, it isn't. (Until `Tag` becomes an extension type.)

**Comment by water-mizuu** [comment]
Thank you for the short discussion and opinions! Closing this now to make way for more relevant issues.
