### ISSUE TITLE
[Extension types] Extension type is stripped if variable type is `dynamic`

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54110]
We have the following.
```dart
// SharedOptions=--enable-experiment=inline-class

extension type V1(int id) {
  int foo(int other) => id + other;
}

main() {
  var d1 = V1(1);
  d1.foo(2);
  dynamic d2 = V1(2);
  d2.foo(3); // NoSuchMethodError: Class 'int' has no instance method 'foo'.
}
```
Is this expected?

Tested on `Dart SDK version: 3.3.0-edge.99a62dfb646e760b06113a2143d103820ca3b248 (main) (Tue Nov 21 07:54:40 2023 +0000) on "linux_x64"`

**Comment by lrhn** [comment]
Absolutely expected and intended.

The ability to invoke extension type members depends on the receiver's *static type* being the extension type.
Which it definitely isn't if the type is `dynamic`.
In that way, it works exactly the same as if the extension type was an empty type with separate extension (not extensiont-type) methods on it.

The extension type is erased at runtime. There is nothing the dynamic invocation can do to figure out which extension type the value might have had at compile-time, because that information, and that *type*, doesn't exist at all at runtime.


The general principle behind dynamic invocations is that they should work, as close as reasonably possible, to how a typed invocation of the same member would work, if the actual runtime type had been the static type. Except that no (static) extensions are in scope at the (run-)time of checking, and that errors are runtime errors instead of compile-time errors, necessarily.
Which means that `d2.foo(3)` should work like `(d2 as int).foo(3)` would, which is an error.
