### ISSUE TITLE
A switch expression with a cast pattern on a variable pattern is incorrectly said to not be exhaustive

### ISSUE THREAD

**Issue by Clavum** [dart-lang/sdk#54125]
Example:

```dart
void main() {
  // The expectation is that 'someKey' will only ever be a bool or a String.
  final model = switch (json['someKey']) {
    final bool value => MyModelExpectingABoolean(value),
    final value as String => MyModelExpectingAString(value),
  };
}

final Map<String, dynamic> json = {
  'someKey': 'In some cases, this field could also be a boolean',
};

```

This gives the warning on the switch declaration that "The type 'dynamic' is not exhaustively matched by the switch cases since it doesn't match 'Object()'." However, to my understanding, all possible values are matched because the pattern `final value as String` will accept any input but throw if it is not a String.

Additionally, if I add a wildcard, `Object()`, or any other third case, it is said to be dead code. I can't find a way to use a cast pattern with a variable pattern that doesn't cause an analysis issue, *except* if I use `final _ as String`. Using this, the switch will no longer complain about exhaustiveness, but of course I don't have access to the variable within the case body.

It works if I don't use variable patterns, as in the following:
```dart
final _ = switch (json['someKey']) {
    bool() => print('Got a bool'),
    _ as String => print('Got a String'),
  };
```

**Environment**:
I was running this code on DartPad on Dart 3.2.0

**Comment by mraleph** [comment]
@eernstg is this a specification issue or implementation?

**Comment by eernstg** [comment]
I believe this is an implementation issue: It is specified that a switch expression must be exhaustive. Next, `final value as String` is irrefutable (because `<pattern> as String` is irrefutable when `<pattern>` is irrefutable, and `final value` is irrefutable), and any switch expression that has an irrefutable case is exhaustive.

The pattern feature specification doesn't spell out in detail which patterns are refutable and which ones are irrefutable, but I think it's reasonably clear anyway: We can conclude that a pattern is irrefutable whenever we have an argument why the pattern match cannot fail for any possible matched value (e.g., `final value` will match and bind `value` with any matched value, and `<pattern> as String` will match or throw for any matched value that matches `<pattern>`). We would also note the general rule that a pattern is only required to match _or throw_ for every matched value in order to be characterized as irrefutable, because throwing is enough to ensure that the value of the enclosing expression (here: switch expression) is well-defined in all cases where it is needed.

Perhaps the implementation classifies the variable pattern `final value` as refutable, even though there is no type constraint?

**Comment by mraleph** [comment]
Labeled as an implementation issue (cc @stereotype441 @johnniwinther )

**Comment by lrhn** [comment]
Occurs in both analyzer and CFE.

The specification of exhaustion of cast patterns is:
> Formally, the space union spaces for a cast pattern with cast type `C` is a union of:
> 
> 1. The lifted space union of the cast's subpattern in context `C`.
> 
> 2. For each space `E` in the expanded spaces (see below) of `M`:
> 
>     1. If `E` is not a subset (see below) of `C` and `C` is not a subset of `M`, then the lifted space union of `E`.


If `M` is `dynamic`, the previous `bool()` has not made a dent in that.

The lifted space union of the cast's subpattern (`_`) in context `C` is ... hard to find. 
The `_` pattern categorized as an *identifier pattern*, but it has no declaration and therefore no declared type.
In type inference of an identifier pattern in a matching context, the only rule which could apply is:

> In a matching context, the name refers to a constant. Type check the constant identifier expression in context type `M`.

but it doesn't refer to a constant.
So it's not *really* an identifier patter, it acts more like a "freshly named variable pattern".

If that's how it's treated, then the applicable rules are:
> 1. If the variable has a type annotation, the required type of `p` is that type, as is the static type of the variable introduced by `p`.
>
> 2. Else the required type of `p` is `M`, as is the static type of the variable introduced by `p`. 

Here we'll have to fall into the second item, which means that the static type of the pattern `_` is `M`, not `Object?`.
(This also matches the description of what happens to `_?` in the ["null check" pattern below](https://github.com/dart-lang/language/blob/main/accepted/3.0/patterns/exhaustiveness.md#:~:text=of%20E.-,Null%2Dcheck%20pattern%3A,-Let%20S%20be) where the static type of `_` in `_?` becomes `Object`.)

If so:
>  1. The lifted space union of the cast's subpattern in context `C`.

is `String`, when that's considered the static type of `_` with matched value type `String`.

> 2. For each space `E` in the expanded spaces (see below) of `M`:

The expanded spaces of `dynamic` is `dynamic`.

>     1. If `E` is not a subset (see below) of `C` and `C` is not a subset of `M`, then the lifted space union of `E`.

`dynamic` is not a subset of `String`, but `String` is a subset of `dynamic`, so not adding `dynamic`.
(Actually, the "lifted space union of `E`" is meaningless, since "lifted space union" applies to patterns, turning them into spaces, and `E` is already a space.)

Which means that the spaces of `_ as String` with context `dynamic` is the set `String`, which doesn't exhaust `dynamic`.

So this *is* working as (somewhat) specified. It's just not working as intended. We should fix the specification too.


We lose out because the algorithm:
* Cannot subtract `String` from `dynamic`, so it cannot represent that `as String` matches `dynamic`-except-`String`,
  (to quote the spec: _But the exhaustiveness algorithm doesn't model "all objects that are not `int`"_,)
* and (guessing, since specification is under-specified) `_` with matched value type `String` only matches `String`.


The one change we *should* make, is to fix the handling of `_`. 
Maybe to make `_` a pattern type by itself, instead of being an identifier pattern. 
It's really neither a variable pattern, nor an identifier pattern, the way it's used. It's the "dynamic of patterns", which is exactly what it needs to be to be allowed everywhere, it can be used in matching patterns where the only allowed identifier patterns are constants, in assignments, where no variable pattern is allowed, and in declaration patterns where no identifier pattern is allowed.
So maybe just introduce "wildcard pattern", `_`, which is allowed everywhere, which has a context type scheme of `_`, the matched value type as static type, and whose lifted space union is that static type. 
(Or special-case that a non-constant identifier pattern is allowed in declaration and matching patterns if it's `_`, but might as well move the special-casing to top-level, instead of risking to forget it in some cases.)


That doesn't help with with the inference here.
So we can try changing the rules for the lifted space union of `p as C` to (additions and moves _italicized_.):

> Formally, the space union spaces for a cast pattern with subpattern `p` and cast type `C` is a union of:
> 
> 1. The lifted space union of the cast's subpattern in context `C` _(call this `S`)._
> 2. _If `C` is a subset of `S`, then `M`._
> 3. _If `C` is not a subset of `M`, then_ for each space `E` in the expanded spaces (see below) of `M`:
>     1. If E is not a subset (see below) of `C`, then the lifted space union of `E`.

It basically (tries to) add a "this matches everything trivially" clause, even if we don't know how to prove it by 
creating an `M`-minus-`C` set. If the sub-pattern matches everything that gets past the `as` cast, then the pattern matches everything thrown at it. 
(Hoisted the "if `C` is not a subset of `M`" clause out of the loop, since it's invariant.)
I'm blindly keeping the third clause here, because I don't understand what it's doing.
So let'stry to sanity-check the
> 1. If E is not a subset (see below) of `C` and `C` is not a subset of `M`, then the lifted space union of `E`.

clause. Read: Let me try to understand it. ... some time later ... Nope, I don't. 
And I don't think it's what's actually implemented, or that it's even correct. As I read it, the following should work:
```dart
void main() {
  M e = V();
  switch (e) {
    case == 0 as C: print(e);   
  }
}

sealed class M {}
class E extends M {} // Sole subclass of sealed class M
interface class C {} // Completely unrelated type.
class V extends E implements C {} // Subtype disproving assumptions.
```
The case `==0 as C` has a sub-pattern which exhausts nothing. Then:
* `E` is in the expanded subsets of `M` (it's the sealed class subtype).
* `E` is not a subset of `C`, and `C` is not a subset of `M`,

so we should add `E` to the spaces union spaces of `==0 as C`.
Which should mean that the clause exhausts `E`, which exhausts `M`.

And yet our implementations tell me that the switch is not exhaustive, so the spec is wrong, and the implementation is ... different. 
@munificent what's the real behavior here?

(And given that, the analysis above might not be relevant.)

**Comment by eernstg** [comment]
I think that the rule about the space produced by a cast pattern needs to be reconsidered.

> Formally, the space union spaces for a cast pattern with cast type `C` is a union of:
>
> 1. The lifted space union of the cast's subpattern in context `C`.
>
> 2. For each space `E` in the expanded spaces (see below) of `M`:
>
>     1. If `E` is not a subset (see below) of `C` and `C` is not a subset of `M`, then the lifted space union of `E`.

One situation is where every object of type `C` is guaranteed to be matched by the subpattern. We could describe this as "`C` is a subset of `E`". In this case the space being matched is `M`: Every instance of type `C` (including subtypes) will allow the dynamic type check to complete normally, and the subpattern will then match the object; every instance which does not have type `C` will cause the dynamic type check to throw. In other words, this pattern covers "everything", and `M` describes everything that we can encounter.

Another situation of interest is where `M` is a subset of `C`. In this case we can ignore the cast pattern and just use the subpattern. This means that the matched set of objects is modeled by `E`.



One situation is where `M` has been expanded (so `M` is a sealed type, and it has been split into the immediate subtypes that are known to exhaust `M` because it is sealed). In this case

**Comment by johnniwinther** [comment]
I've created https://dart-review.googlesource.com/c/sdk/+/338760 which adds a new rule to exhaustiveness handling of the as-pattern:

The new rule checks whether the cast type is fully contained in the space of the subpattern. If so, we can assume that the whole context type has been matched because there is no value that passes the as-test that would be rejected by the subpattern.

This change, if accepted, should be spec'd. And we should also consider whether this change should be versioned.

**Comment by munificent** [comment]
> And yet our implementations tell me that the switch is not exhaustive, so the spec is wrong, and the implementation is ... different.
> @munificent what's the real behavior here? Or what am I missing?

I think the spec is bad and I just designed something that isn't actually sound. I'll follow up on Erik's PR.

**Comment by stereotype441** [comment]
I'm a little late to the party here, but I just wanted to add my two cents:

I feel like part of what's tricky about `as` expressions and exhaustiveness checking is that in principle, if we want to do it with maximum fidelity, the analysis depends on the order of operations during a pattern match, in a way that I believe doesn't apply to other kinds of patterns. Consider:

```dart
f((Object, Object) x) => switch (x) {
      (var a as int, 0) => a,
      (int a, _) => a,
    };
```

The first thing this switch does is throw if `x.$1` is not an `int`, therefore if `(var a as int, 0)` doesn't match `x`, then `(int a, _)` is guaranteed to match. So in principle the switch is exhaustive. But the exhaustiveness checker doesn't (currently) understand that it is.

But now if we just swap the left and right sides of the pair, we get this:
```dart
f((Object, Object) x) => switch (x) {
      (0, var a as int) => a,
      (_, int a) => a,
    };
```

Which is definitely _not_ exhaustive. For example, if you call `f((1, 'foo'))`, then:
- `(0, var a as int)` doesn't match, because `x.$1` isn't `0`.
- `(_, int a)` doesn't match, because `x.$2` isn't an `int`.

I don't know if we want the exhaustiveness checker to be smart enough to be able to understand the difference between these two examples. On the one hand, I feel like a principle we've learned through flow analysis is that the user's mental model of data flow is extremely sophisticated, so making the compiler's data flow analysis smarter _doesn't_ lead to user confusion the way other "smart" compiler features might; it seems like a similar principle probably applies to exhaustiveness analysis. On the other hand, it might be really difficult or bug prone to make the exhaustiveness checker understand the order of operations in a pattern match, so I don't know if it's worth it.
