### ISSUE TITLE
Dart closures over capture labels

### ISSUE THREAD

**Issue by cgrand** [dart-lang/sdk#54158]
Tested with both 3.1.5, 3.2.0 and whatever is current on dartpad.

It looks like closures capture labels -- or something in the compiler tries to prevent code in closures to jump to an external label but fail to recognize there's a valid homonymous label in scope.

The following code with nested switch statements with identically labelled defaults work:
```dart
nestedSwitches(x) {
  switch(x) {
    _default: default:
        switch(x) {
            case 42: continue _default;
            _default: return true;
        }
  }
  return false;
}
```

Same code but intoducing an IIFE around the inner switch fail with `Error: Can't continue at '_default'.`
```dart
overcapturedLabel(x) {
  switch(x) {
    _default:
    default:
      (() {
        switch(x) {
            case 42: continue _default;
            _default: default: return true;
        }
      })();
  }
  return false;
}
```

Using distinct labels or extracting the IIFE outside of the outer switch work.

**Comment by devoncarew** [comment]
cc @lrhn to verify whether this is working as intended

**Comment by lrhn** [comment]
That does look like a bug, and a particularly weird one, since closures should not close over labels at all. There are two reasons the inner continue cannot target the outer label: is not in scope at all, and if it was. It would be shadowed by the inner label.

Maybe two wrongs do make a right.

**Comment by cgrand** [comment]
thanks for reopening, maybe you should remove the closed-as-intended tag too?

**Comment by lrhn** [comment]
Have checked the scope of the issue. It seems to be both Dart2JS and VM, so it's the front-end. The analyzer correctly marks the outer label as unused.

So, reproduction:
```dart
void main() {
  var x = DateTime.now().millisecondsSinceEpoch > 0 ? 42 : 0;
  var ctr = 0;
  switch (x) {
    otherLabel:
    case 0:
      print("outer 0");
    label: // Comment out to make work correctly
    case 42:
      print("outer 42");
      if (++ctr == 5) break;
      // (() { // Comment in this
        switch (x) {
          case 42:
            print("inner 42");
            continue label;
          label:
          case 0:
            print("inner 0, done");
        }
      // })(); // and this.
  }
  print("done");
}
```
This code has the `continue label` jump to the *outer* label from the inner switch.

That's a bug, the inner `label:` label is in the scope of the entire inner switch, and should be what `continue label;` refers to.

If we comment out the outer `label:`, then the inner `continue` will find the following inner label correctly.

If we comment in the IIFE lines, compilation fails stating that you cannot continue to `label`, presumably (correctly) because it's not in the same function. But also, it should not even be in scope, so it *still* somehow shadowing the inner label is probably error correction gone wrong. (Trying to tell people that they can't continue to a label which is not in scope requires the scope knowing the label which *could* have been in scope, and here it wasn't replaced by the correct label.)

If moving the `label: case 0:` before the `case 42:`, then code works correctly, so it is related to not having seen the label of the current switch yet.
It's not possible to resolve labels in switch case bodies before having seen all the labels of the current switch. (This is perhaps the only case where function body code can have forward references. But that's necessary to support arbitrary state machines like what `switch` can do.)
