### ISSUE TITLE
New API similar to dartDeferredLibraryLoader

### ISSUE THREAD

**Issue by justtonytone** [dart-lang/sdk#54202]
The ACX team is interested in a new API that is similar to dartDeferredLibraryLoader, except instead of a single URI being passed to the handler, a set of URIs is passed. This is useful in our MSS serving mode where we can batch part file loads. If it's easy to pass in a set of part file ids (as opposed to URIs), that would be beneficial as well.

**Comment by biggs0125** [comment]
The goal here would be to add a hook like `dartDeferredLibraryMultiLoader` with the following interface:
`(Array<String> uris, Function successCallback, Function errorCallback, int loadId, int loadPriority) -> void`

The user would be responsible for ensuring the `successCallback` is only invoked after *all* of the provided URIs are loaded (or invoking `errorCallback` is invoked if any one of the part files fails to load.

Otherwise this would act exactly as `dartDeferredLibraryLoader` does today. We want both these APIs so live alongside each other.

Longer term we want to allow users to implement custom library loading via a special Dart API but in the meantime this should be a reasonable solution.

This will expand the size of main bundles a small amount but I don't think it should be too significant.

**Comment by justtonytone** [comment]
Thanks for the new API!
