### ISSUE TITLE
Bleeding-edge Dart SDKs at gsdview.appspot.com/dart-archive haven't updated since 13th Nov

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#54242]
For working on the analysis server, I usually grab bleeding-edge SDK builds from here to avoid building the SDK myself:

https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/

Today I noticed some recent changes weren't included, and that the timestamps show 13th Nov. I'm not sure if this is deliberate/known or not but I figured I should ask :-)

(cc @athomas?)

**Comment by DanTup** [comment]
Oh, the URL on the dart.dev website is actually serving an up-to-date SDK:

https://storage.googleapis.com/dart-archive/channels/main/raw/latest/sdk/dartsdk-windows-x64-release.zip

I thought these folders were both the same, but I used the other one because it had directory listing enabled and I could easily right-click to save (whereas the dart.dev one requires you build the link yourself!).

Maybe if the URL I posted at the top is not valid, it could be deleted/emptied/redirected or something? :)

**Comment by DanTup** [comment]
Aaah! :) Seems like a good change then. I updated my bookmark to `main`.

I've probably pasted that URL into GitHub issues before, so removing any stale SDKs would be worthwhile IMO even if it can't be redirected.

Thanks!

**Comment by sortie** [comment]
What is <https://gsdview.appspot.com>? That's not part of our infrastructure as far as I know. Do you consider that to be a first party site? How did you learn about it?

The be channel has been renamed to main like Alex said, yeah, so <https://storage.googleapis.com/dart-archive/channels/main/raw/> is the correct place to use.

It's intentional that the be directory is frozen. Some older things may still grab things from /be/latest/ and rather than break them, the intention is just to let them be frozen on an old version until they notice and migrate, like today :)

**Comment by DanTup** [comment]
Closing this as I think this is working as intended, but feel free to re-open if you think it's worth tracking (for ex. to clean up and remove them at some point in the more-distant future).
