### ISSUE TITLE
CFE crashes during representation type dependency check

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#54241]
The following program makes the CFE to go into infinite recursion and crash.

```
class A<X extends E> {}
extension type E(Function<Y extends A>() it) {}
```

**Comment by eernstg** [comment]
Perhaps there's a missing step in this computation? The raw type `A` which is used as the bound of `Y` needs to be computed by instantiation to bound. This yields `A<E>`:

```dart
class A<X extends E> {}
extension type E(Function<Y extends A<E>>() it) {}
```

With this in place we can report a cyclic dependency, because `E` has a representation-dependency on itself.

If we allow this cycle to exist and then proceed to compute the extension type erasure of `E` then we'll get the following:

```dart
E -->
Function<Y extends A<E>>() -->
Function<Y extends A<Function<Y extends A<E>>()>>() -->
Function<Y extends A<Function<Y extends A<Function<Y extends A<E>>()>>()>>() -->
...
```

Perhaps that's the infinite loop?
