### ISSUE TITLE
Bug in the Uri class

### ISSUE THREAD

**Issue by matinzd** [dart-lang/sdk#54258]
There is a bug in the Uri class that hinders the proper construction of a URL in a specific edge case:

```dart
final uri = Uri(
  scheme: 'bankid',
  path: '/',
  queryParameters: {
    'autostarttoken': autostartToken,
    'redirect': encodeURIComponent(redirect),
  },
);
```

P.S: Not sure if I need to report this here or in the flutter engine ... I am a bit confused.

### UPDATE

If I provide an empty host it works properly.

## Expected result

```
bankid:///?autostarttoken=[TOKEN]&redirect=[RETURNURL]
```

## Actual result

```
bankid:/?autostarttoken=[TOKEN]&redirect=[RETURNURL]
```

The issue arises as the first two forward slashes are omitted in the final constructed URL. Interestingly, adding more forward slashes does not result in the omission of the initial two slashes for the scheme.

## Ref

dart:core lib: https://api.dart.dev/stable/3.2.3/dart-core/Uri-class.html

## Dart version

Dart SDK version: 3.1.4 (stable) (Tue Oct 17 14:55:53 2023 +0000) on "macos_arm64"

**Comment by Markzipan** [comment]
@lrhn may have more context. I can confirm that this replicates across VM, Dart2JS, and DDC.

**Comment by lrhn** [comment]
That is probably working as intended.

The `bankid` scheme is not known, so the `Uri` class doesn't know whether the URI needs an authority part or not (it knows that `http` needs one, and fx `email` does not).

So rather than guess, it does what you ask for, which is no authority part, unless you actively pass in some part of it. Like an empty host.

The solution is to pass in an empty host.

**Comment by matinzd** [comment]
Yes that makes sense. I figured it out when I passed an empty host. I was also testing this in different languages and it seems to be the same story. I am closing this now and thanks for your help.
