### ISSUE TITLE
Specify what happens if a macro tries to introspect on a type alias

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#54270]
Per comment https://dart-review.googlesource.com/c/sdk/+/339620/2/pkg/_fe_analyzer_shared/lib/src/macros/api/builders.dart#b117

**Comment by lrhn** [comment]
Type aliases are declarations, they can be annotated with metadata, and have a name and type parameter structure different from what they alias.

So you should be able to introspect them, as type aliases, not as the type they alias (but you should be able to ask for that too). Maybe introspection should have a flag, `followAliases`, like file system operations with `followLinks`, so you can choose whether to see the intermediate alias decorations or not.

You should also be allowed to augment type alias decorations, which is probably only meaningful if they're allowed to start out incomplete (`typedef ToCome;`).
If you can augment that note than once depends on how you can augment an existing type otherwise. You can always add more metadata.

(Congress back to the fundamental question of: is introspection on the source or on the semantic entities defined by the source, and if the latter, which ones.)

**Comment by jakemac53** [comment]
We do have a representation for type aliases now (TypeAliasDeclaration) which implements ParameterizedTypeDeclaration. That all seems pretty obviously the right solution, so I am going to close this. I don't think there is any open question here.
