### ISSUE TITLE
Uses of List.from in future.dart leads to more type checks in sound null safety

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#54313]
Both the VM and DDC patch files include checks that help avoid an unnecessary cast of every element in the implementation of `List.from()`.
https://github.com/dart-lang/sdk/blob/6fcd15c1aa024bd42056487374a146be492277a2/sdk/lib/_internal/vm_shared/lib/array_patch.dart#L25

https://github.com/dart-lang/sdk/blob/6fcd15c1aa024bd42056487374a146be492277a2/sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart#L535

The pattern used here to return a correctly typed list interacts poorly with these patches in sound null safety.
https://github.com/dart-lang/sdk/blob/6fcd15c1aa024bd42056487374a146be492277a2/sdk/lib/async/future.dart#L524

In unsound null safety the the fast path without element casts gets executed but after migrating to sound null safety the `is Iterable<E>` no longer returns true even though all the casts pass.

Could this code be restructured to avoid the need to fill the list with nulls before all the futures complete?

cc @natebosch @lrhn @fishythefish

**Comment by lrhn** [comment]
> the is `Iterable<E>` no longer returns true 

It can, if `E` is itself nullable.

It's not possible to avoid filling some list with something.
It's not possible to make the accumulator a `List<T>`, because we don't have any instances of `T` available.

It's internal code, so what we can maybe do is to cheat, using `unsafeCast`, for example if we can see that the input is an `Iterable<Future<T>>`.

Or we could deprecate `Future.wait` and punch to the extension getter `wait` on `Future`.
I don't know if that's more efficient, but likely not. It also has to keep a nullable variable until it gets a value

**Comment by natebosch** [comment]
> It's not possible to make the accumulator a `List<T>`, because we don't have any instances of `T` available.

I started on a change that delays allocation of the list until we have the first `T` available so we can fill it with that value. For the happy case I think it should work.

That change doesn't allow us to keep the behavior of the `cleanup` argument which needs to recall all the non-null (regardless of whether `T` is nullable) values after a failure. Currently it also runs in the same order as the input iterable for any values that have completed, though I don't think we make it a guarantee, and later futures that complete can call `cleanup` in whatever order they complete. If we can safely change the ordering we could maybe have a second list of just the values we need to clean up.

**Comment by fishythefish** [comment]
For some added context, we have a flag in google3 which can be enabled on unsound programs to provide some additional consistency checks prior to enabling sound null safety. If a runtime type operation (e.g. subtype check, `is`, `as`) produces a different result with sound semantics than with unsound semantics, we produce a diagnostic. For DDC in particular, we throw.

We currently have no method of opting some code out of these checks (and I'd like to avoid adding one if possible), so a lot of code that calls `Future.wait` may trigger this (with little recourse for the user). There are other ways we could work around this, but it would definitely be easiest if SDK simply avoided the issue.

I think using `unsafeCast` or similar to cheat here seems reasonable; presumably, we have already proved to ourselves that `valueList` has been fully populated with values of type `T` by the time we get to the `List.from` call, or else it would throw.

**Comment by nshahan** [comment]
After discussing various options I'm in favor of changing the implementation of `Future.wait` to avoid using `List.from()` as an operation to change the reified type of the value returned. It seems reasonable that we should avoid the runtime cost of casting every element when are confident the cast will always pass. If there is no reasonable refactor that can avoid it then I'm comfortable using `unsafeCast` to avoid the performance penalty incurred when switching to sound null safety. That will also unblock the users that are tripping on this code path when trying to asses the implications of running their app in sound null safety.

**Comment by lrhn** [comment]
There is a possible way to trigger running the finalization code when there is still a `null` value in the value list.
It requires a future which calls it's `then` value callback more than once, which is far outside of allowed `Future` behavior, but it's possible to implement (and impossible to prevent).

We could guard against that, but that costs too. the current behavior allows us to just let `List.from` throw if it happens, or return an invalid result of `E` is nullable, which is allowed for completely unspecified behavior.

Using `unsafeCast` instead would move this from unspecified to unsound behavior, which can potentially be a security issue on native platforms.

Instead of `unsafeCast<E>(value)`, we can use `value ?? (value as E)`, which only does a type check for `null` values.

**Comment by lrhn** [comment]
If we delay allocation of the list until the first value, then we can no longer use the presence or absence of the list as a signal for the being an error.
Shouldn't be a problem, we can check whether `error` is non-`null`, it's currently `late`, but it really shouldn't be.

I think it's fair to change the behavior of clean-up to check identity of the results, and not clean up the same result more than once. It might even be desirable, but mostly it's probably irrelevant, because the kind of values that you might get from two different futures, is also the kind of objects that don't require cleanup.

**Comment by natebosch** [comment]
We have two options to move forward - I think we can probably choose either one based on the preferences of the web compiler team.

https://dart-review.googlesource.com/c/sdk/+/341504 - switch to a list literal with a null check (to optimize non-null `T` uses) and an `as` cast.
https://dart-review.googlesource.com/c/sdk/+/341327 - Delay list instantiation until the first `T` value is available and avoid list copy.

**Comment by nshahan** [comment]
After chatting with @rakudrama it seems like https://dart-review.googlesource.com/c/sdk/+/341504 would be most preferable for the JavaScript compilers.

`List<E>.from(l)` -> `[for (var v in l) v as E]` should only produce different results in sound vs unsound null safety when `v` is `null` and `E` is non-nullable. IIUC that would mean there is either some confusing misuse (like the mentioned `.then()` being called twice) or there is a bad migration for the type of `E` in user code and that we actually want to report about if we discover through this test. In the later case it is difficult to imagine how this wouldn't already be caught elsewhere.

**Comment by rakudrama** [comment]
I just chatted with @nshahan about this issue.

I'm strongly in favor of the simple fix of replacing
```
List<T>.from(valueList)
```
with
```
[for (final value in valueList) value ?? value as T]
```

You can use just `value as T`, but DDC currently benefits from spelling it out, and the optimizing compilers will still generate good code even if they recognize the nullable-removal pattern ([like dart2js](https://github.com/dart-lang/sdk/blob/99ccb83e5d968c8a2fc1cacd6eb0246a080315e2/pkg/compiler/lib/src/ssa/builder.dart#L2665))

**Comment by natebosch** [comment]
After the new year I think we'll try to land https://dart-review.googlesource.com/c/sdk/+/341504 to change `List.from` to a list literal.

Separately I may also look to see if there any other ways we can write this function that might be easier to read - the current shared variables between closures is confusing. Another potential way we can more eagerly initialize the list is to use a `List<FutureOr<T>>` in place of a `List<T?>` and store the original futures initially.

**Comment by lrhn** [comment]
There is the option of optimizing the "no `cleanUp` case separately, or just making it use `.wait`.

Generally it's love to deprecate `Future.wait` and move people to `.wait`, but then that likely needs optimizing too.

**Comment by nshahan** [comment]
I just want to check in on the status here, are there still plans to land https://dart-review.googlesource.com/c/sdk/+/341504?

**Comment by iinozemtsev** [comment]
Any updates on this issue? We're going to use  sound null safety checks mode intensively soon and this is going to be a real blocker.

**Comment by parlough** [comment]
> Any updates on this issue?

The referenced CL to reduce type checks in `Future.wait` landed earlier today - https://github.com/dart-lang/sdk/commit/712df96202af372a9ad473d6a218822403d824a6.
