### ISSUE TITLE
how can i load elf file use `Dart_LoadELF` function？

### ISSUE THREAD

**Issue by fei1990** [dart-lang/sdk#54330]
when i user `Dart_LoadELF` function load a aot file, i can launch my app from xcode, but can't launch without xcode. when i click my app icon, my app crashed directly. How can i do?
<img width="1209" alt="image" src="https://github.com/dart-lang/sdk/assets/20367597/55a18106-cd0f-4aad-957c-a3459585056c">

**Comment by mraleph** [comment]
You are going to hit all kinds of issues with `Dart_LoadELF` on Mac OS due to codesigning requirements and it is never going to work on iOS.  

Things work when you run from XCode because that attaches debugger to your process, which in turn disables codesigning protection. 

Packaging AOT snapshot into ELF files on Mac / iOS is not supported - instead compile it to Mach-O and use native library loading mechanisms.
