### ISSUE TITLE
[ffi] `@Native` for global fixed-size arrays

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54337]
https://dart-review.googlesource.com/c/sdk/+/338020 adds support for https://github.com/dart-lang/sdk/issues/50551, but does not add support for global fixed size arrays.

```c++
double foo[4];

double return_double() {
  return foo[1];
}

void set_double(double value) {
  foo[2] = value;
}
```

Could theoretically be bound to.

```dart
@Array(4)
@Native()
external Array<Double> foo;
```

It just so happens to be that currently the following works because the memory layout is identical.

```dart
@Native()
external Pointer<Double> foo;
```

The advantage of supporting the latter is that we can do bound checks on use.

@simolus3 Thanks for making the `Array` limitation explicit in https://dart-review.googlesource.com/c/sdk/+/338020. Here are some of my thoughts about it.

Re https://github.com/dart-lang/native/pull/860, should we temporarily support generating `Pointer`s for fixed-size global arrays? That would make it a breaking change later to make it Arrays, though. On the other hand, if users would like to use those fields than without generating `Pointer`s, users can't use FFIgen at all.

**Comment by simolus3** [comment]
> That would make it a breaking change later to make it Arrays, though.

Technically yes, but thanks to all the extensions in `dart:ffi`  which provide `operator[]` and `operator[]=` on pointers too, migrating between pointers and arrays is unlikely to require users to change their code.

**Comment by simolus3** [comment]
> Re https://github.com/dart-lang/native/pull/860, should we temporarily support generating `Pointers` for fixed-size global arrays?

As it turns out, we're already generating pointers for global arrays in `ffigen`. That's understandable, since there is no public mechanism for getting from a pointer to an array instance, and so the generated code based on looking up bindings manually can't do any better.

This gives us a good opportunity to get this right with native fields though. I have opened https://dart-review.googlesource.com/c/sdk/+/341860 to support array fields in the SDK, and I've updated the ffigen PR to make use of that.
