### ISSUE TITLE
Proposal to improve error message for Bad state: No element error by providing missing element details

### ISSUE THREAD

**Issue by LauDijksterhuis** [dart-lang/sdk#54331]
> 
> When requesting a field that does not exist from a Map, for example FirebaseDocument.data(). The error throws de following:
> 
> ```
> The following StateError was thrown building
> InsuranceInOutPrivateCard-[<'HXuXEZJ6P6Bptn1Ju47a'>](dirty, state:
> _InsuranceInOutPrivateCardState#48be0):
> Bad state: No element
> ```
> 
> Which is good.
> 
> ### Proposal
> 
> However, it would be greater if the error message showed which "element" is requested. For example:
> Bad state: no element at ....  and then the field that was requested.

Hi there,

Above is the issue I created in the flutter repo, they kindly suggested me to move this issue to the dart team.
After some debugging which took way longer then I hoped. 
I found out the no element error came from an ENUM.

#### Some context:
When I started out learning Flutter and Dart I didn't create any Data Models. (My mistake)
Now I am currently trying to create all Data Models required in an old project.

So when I saved data to Firebase I used to convert enums to a String and then when reading the data I would reverse lookup the right enum.
So after some coding I accidentally made the mistake to save the enum index instead of the value. So when reading the element the `Bad state: No element`

#### Proposal
If I remember correctly this error is also thrown when reading data from a map key that does not exist.
It would be nice if the error message also said which element causes the error. Like in my case I have been searching for a bug in the data Map<String, dynamic> but it was in the enum.

So it would be nice if it said: Bad state, no element in `ENUMNAME`

**Comment by lrhn** [comment]
Dart maps do not throw when accessing a non-existing key, so this is not coming from a standard `Map`.

Generally, when we throw the `StateError("No element")`, its _usually_ because someone is asking for an element from an effectively empty collection (whether `[].first` or `someList.where((_) => alwaysFalse).first`, or the equivalent `someList.firstWhere((_) => alwaysFalse)`, where the receiver isn't empty, but we can't really say which elements *isn't* there.
That makes it hard to say something useful. Also, we don't really *want* to have too many, or too complex, error strings in the compiled program (they take up space whether they're used or not.)

So it would be useful to figure out *which* code threw this particular error, and check whether that code has more context that it can, and want to, provide, and possibly whether another `Error` type would be more appropriate.
(Is it an argument error that the input value was not a key in the map, rather than a state error of the map that it doesn't have the key?)

**Comment by LauDijksterhuis** [comment]
Hi @lrhn 

Thank you for your response, I am not able to reproduce the error at this moment.
