### ISSUE TITLE
Dart experiment to remove (or hide) `dart:html` and friends from included libraries

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#54347]
It would be **super cool** to have an experiment (that can be used with `--enable-experiment`) or some other mode/common flag that removes (or hides) `dart:html`, `dart:svg`, `dart:js`, `dart:js_util`, etc. from the supported/surfaced SDK libraries. So I suppose it would load a different SDK overview file?

This would allow the analyzer and compilers to catch usages of the old libraries in your package and dependencies _(sure, can be partially done by compiling with `dart2wasm`)_.

Perhaps more importantly though, the analyzer could avoid surfacing those libraries in completion suggestions, greatly improving the developer experience of those using modern interop functionality. 

It would be a useful step towards migration that could be enabled relatively soon due to the lack of guarantees around experiments.

**Comment by sigmundch** [comment]
For what it's worth, we have a dart2js flag `--server-mode`  that does this for dart2js. 

I'll start the triage here first by asking a few questions:

For the @dart-lang/language-team: is it possible to use experiment flags and language versioning to hide a library?

For the analyzer team: if not, are there mechanisms to enable/disable an SDK library from being available in the analysis server?

**Comment by parlough** [comment]
I didn't think about `--server-mode`, thanks for calling that out as another option! Yeah I think standard support for this from the web compilers is nice to have, but I feel that's less important since it can be surfaced with `dart2wasm` and the server mode.

The big win I see for developers is mostly in analysis errors and less noisy completion suggestions :)

**Comment by jakemac53** [comment]
You can also use the import_path package to check for imports to any library (such as `dart:html`):

```
pub global activate import_path
import_path web/main.dart dart:html
```

**Comment by DanTup** [comment]
>  that removes (or hides) `dart:html` and its friends from the supported/surfaced SDK libraries.

It might be nice to make it more general than this - why can't I pick which specific `dart:` libraries I do/don't want (like I can with other dependencies)? There are quite a few libraries you get "for free" from the SDK and even some non-web ones you might just never want to use.

![Screenshot 2023-12-14 184345](https://github.com/dart-lang/sdk/assets/1078012/b31e5667-a08f-482b-be72-d83b668f6eed)


I've previously also wondered whether the Dart SDK could include `package:` libraries rather than them having to be `dart:` so that they are opt-in, similar to how you can reference packages from the Flutter SDK:

```
dependencyes:
  flutter:
    sdk: flutter
  mirrors:
    sdk: dart // package:mirrors but comes from the SDK
```

That could allow things to be shipped in the Dart SDK without being automatically available to projects (for example allowing other packages to use the same names without completion lists being full of duplicates). For example IIRC in flutter_tools it's forbidden to use `dart:io` instead of going through an abstraction - but it's very easy to accidentally get all the types from `dart:io` with fixes/completion.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/54610 which implemented not surfacing `dart:html` and friends when not already used.

For determining outdated usages during compile, you can use `dart compile wasm`.

Thanks all.
