### ISSUE TITLE
Can't import enums when first char of enum is lower case.

### ISSUE THREAD

**Issue by atreeon** [dart-lang/sdk#54362]
1. create new Flutter app
2. open in Intellij Idea
3. create new folder `enumsXyz`
4. create eBlop.dart file
`enum eBlop { blop, bloppy }`
5. inside main.dart, without using autocomplete, write:
```
Widget build(BuildContext context) {
    var blop = eBlop.blop;

    return MaterialApp(

```
6. opt + enter key (mac) to get the quick fix options and nothing happens (works on classes, global variables etc)

Autocomplete auto adds the import statement, context menu doesn't work.  Possibly Intellij Idea bug?

**Comment by atreeon** [comment]
Hi @keertip and @bwilkerson, would it be possible to increase the priority level of this bug.  It is a bit of a nasty one.  Can't import a reference, sometimes difficult to find out the reason for the lack of import.
Thanks!

**Comment by bwilkerson** [comment]
I'm sorry for the difficulty this is causing. The bug was given a P3 because it is considered to be an edge case, meaning that we don't expect very many users to be impacted by it because we expect most users are capitalizing the names of enums. We would very much like to have this fixed, but unfortunately I can't give you a time frame.

I have confirmed that (a) this is also broken in VS Code, and (b) this does not depend on flutter.

**Comment by atreeon** [comment]
ok, thanks. I appreciate your efforts.  I'll rename my enums, I guess that is the standard now (I'm still working to year 2000 naming convensions!)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/356661
