### ISSUE TITLE
[analyzer] No error if external constructor initializes fields

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54371]
The following code produces an error in CFE but no error in the analyzer
```dart
class C {
  num x;
  external C(this.x); // CFE: Error: An external constructor can't initialize fields.
}

main() {
  print(C);
}
```
I can't find the exact statement in the spec that makes this constructor to be an error therefore cc @eernstg to confirm that this is an analyzer issue

**Comment by lrhn** [comment]
I'll confirm that I intend it to be an error.

External methods and constructors have no *implementation* in the declaration, and assigning a parameter to a field is very much implementation.
External constructors are not allowed to have intializing formals or super-parameters, or any initializer list or body. They are neither redirecting nor non-redirecting (that's an implementation detail), but they can be `factory` or not, and `const` or not, because that's public API.

I'd even expect that their optional parameters cannot have default values, like a forwarding factory constructor, but we could have chosen to allow that as "documentation". So, not sure about that one. But the actual implementation can differ, it's not bound to documentation, or the names of positional parameters. (Our `@patch` implementation might check that we don't change names or default values, but in general that's not something the language cares, or knows, about).

**Comment by bwilkerson** [comment]
@scheglov I assume we'll get the spec updated at some point, but just FYI.

**Comment by srawlins** [comment]
Analyzer now reports the same error as the CFE.
