### ISSUE TITLE
Unexpected type resolution for `List<T>` with elements of the same super type but different type parameters

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#54387]
In the following code snippet, I came across what I think is an unexpected behavior that I would like to report.

In short, I expected `list3` to resolve to: `List<A<Object>>` but it resolves to `List<Object>` instead. 

```dart
class A<T extends Object> {
  const A();
}

class B<T extends Object> extends A<T> {
  const B();
}

class C<T extends Object> extends B<T> {
  const C();
}

void main() {
  var list1 = /* resolved List<A<Object>> (expected) */ [
    A(),
    B<String>(),
    C<bool>(),
  ];

  var list2 = /* resolved List<A<Object>> (expected) */ [
    B<int>(),
    A(),
    C<String>(),
  ];

  var list3 = /* resolved List<Object>  (unexpected) */ [
    B<int>(),
    C<String>(),
    A(),
  ];

  var list4 = /* resolved List<A<Object>> (expected) */ [
    C<String>(),
    B<String>(),
    A(),
  ];

  [list1, list2, list3, list4].forEach((e) => print(e.runtimeType));
  /* prints:
      List<A<Object>>
      List<A<Object>>
      List<Object>
      List<A<Object>>
   */
}

```

I ended up specifying the type of the list explicitly, but I was actually surprised how changing the items order would change the type resolution. 

>  Dart SDK version: 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "macos_x64"

**Comment by lrhn** [comment]
This is most likely working as specified.

The type of the list is inferred as an upper bound of the types of the element expressions using the **Up** function.

The **Up** function only takes two arguments, so the upper bound of three types is found as **Up**(**Up**(T1, T2), T3).
The thing is that **Up** is not associative, so the order matters.
(It might be symmetric.)

And **Up**(`B<int>`, `C<String>`) is `Object`, because that's the only shared super-interface, and neither of a supertype of the other.

If `A`, aka `A<Object>`, is combined with one of the other, then the result is `A<Object>`, because that is a supertype of any `B` or `C`.

So the order matters, and in the one case where `A` is not one of the first two elements, the result ends up as `Object` because of how things are defined.

**Comment by osaxma** [comment]
> And **Up**(`B<int>`, `C<String>`) is `Object`, because that's the only shared super-interface, and neither of a supertype of the other.
 
I was confused because I thought `A<Object>` would be the upper bound in here. My thinking was that since both `B` and `C` are `A` and both `int` and `String` are `Object`, then the type would be resolved as `A<Object>` (which apparently was incorrect).

Thank you @lrhn for always taking the time to provide detailed explanations 🙏🏽

**Comment by eernstg** [comment]
It is indeed working as specified. There is one more thing to be aware of here, though. Try to delete the declaration of `B` and put in this one:

```dart
typedef B<X> = C<X>;
```

With this declaration of `B`, we're computing the standard upper bound of `C<String>` and `C<bool>` rather than `B<String>` and `C<bool>` (because `B` now means `C`). This is a very similar situation, but it differs in one crucial way: We do not compute the standard upper bound of two different classes with different type arguments.

(It's "standard upper bound" rather than "least upper bound" because it isn't least.)

When we perform this computation with the _same_ class and different type arguments, we will get the recursive invocation of the algorithm that you might expect:

```dart
UP(C<String>, C<bool>) ==
C<UP(String, bool)> ==
C<Object>
```

The reason why there is no recursive invocation of the `UP` algorithm when we have different classes _and_ different type arguments is that this case may give rise to an infinite loop. Hence, the relevant clause it the definition of `UP` uses a rather simplistic algorithm that avoids all infinite loops by avoiding recursive invocations.

We have [a proposal](https://github.com/dart-lang/language/issues/3282) which will allow `UP` to produce better results in cases like this one, and still avoid the infinite loops.

But for now the best advice is probably to keep an eye out for disappointing results from this standard upper bound computation, and then offer a bit of help when it occurs. For instance, you could pass the actual type argument to the list literal explicitly if the types of the elements do not have a sufficiently useful standard upper bound:

```dart
void main() {
  var list = <A<Object>>[
    B<int>(),
    C<String>(),
    A(),
  ];
}
```

**Comment by osaxma** [comment]
Thank you @eernstg for the further clarification which cleared the rest of my confusion.
