### ISSUE TITLE
Clipboard.write() API is outdated

### ISSUE THREAD

**Issue by nirh0** [dart-lang/sdk#54391]
The parameter of Clipboard.write is "An array of ClipboardItem objects"

https://w3c.github.io/clipboard-apis/#clipboard-interface
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write

but in https://github.com/dart-lang/sdk/blob/main/sdk/lib/html/dart2js/html_dart2js.dart it's a "DataTransfer" object.
Using this in a modern Chrome gives `The object must have a callable @@iterator property.`

(and similarly with Clipboard.read())

**Comment by biggs0125** [comment]
It does appear that the typing in `dart:html` is wrong for this API. However, we’re working on putting `dart:html` into deprecation mode which means we’re stopping fixes for these sorts of type errors.

We recommend switching over to `package:web` if it contains the API you need, or using `dart:js_interop` otherwise. In this case [`Clipboard.write`](https://pub.dev/documentation/web/latest/web/Clipboard/write.html) and [`Clipboard.read`](https://pub.dev/documentation/web/latest/web/Clipboard/read.html) are stable APIs so they are included in `package:web`.

For more information on the new JS interop, see our [docs](https://dart.dev/interop/js-interop).
