### ISSUE TITLE
Failures on [analyzer,cfe] Support contained types is as-pattern

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#54419]
There is a new test failure on [[analyzer,cfe] Support contained types is as-pattern](https://dart-review.googlesource.com/c/sdk/+/338760).

The test
```
language/patterns/exhaustiveness/nullable_cast_test RuntimeError (expected Pass)
```
is failing on configuration
```
dart2js-production-linux-d8
```

It doesn't throw as expected in line 88
```
Expect.throws(() => exhaustiveNonNullableFutureOrTypeVariable2<int>(
        Future<int?>.value(null)));
```
where `exhaustiveNonNullableFutureOrTypeVariable2` is defined as
```
exhaustiveNonNullableFutureOrTypeVariable2<T extends Object>(FutureOr<T?> o) =>
    switch (o) {
      FutureOr<T>() as FutureOr<T> => 0,
    };
```

**Comment by biggs0125** [comment]
This is a bug in Dart2js's handling of nullability in as-checks.
A more minimal reproduction of this can be seen with this program:
```
void f<T>(T? x) {
  print(x as T);
}

void main() {
  f<int>(null);
}
```

We would expect this to throw for production mode because there is an explicit cast that will always fail.

Instead when this program is compiled with `--omit-implicit-check`, the resulting program prints "null". When `--omit-implicit-check` is not passed we, somewhat inadvertently, compile to the correct program with the failing cast.

The bug arises from a subtype check we do early on during type use analysis. The subtype check is done ignoring nullability which means we're deeming `x as T` unnecessary. Therefore we don't register the usage of `f.T`. 

Without `--omit-implicit-check` an implicit parameter check on `x` forces `f.T` to be included in the type environment and so we correctly perform the as check. But with `--omit-implicit-check` we omit that implicit check and so `f.T` is completely dropped from the type environment and so we hit some undefined behavior (i.e. we print null).

Fix here:  https://dart-review.googlesource.com/c/sdk/+/343821
