### ISSUE TITLE
DateTime UTC/local issue

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#54422]
https://api.dart.dev/stable/3.2.3/dart-core/DateTime/toIso8601String.html
`DateTime.toIso8601String` output is
- `UTC`: `2023-12-19T23:03:49.582308Z`
- `Local time / no UTC`: `2023-12-20T11:43:26.708`

https://api.dart.dev/stable/3.2.3/dart-core/DateTime/parse.html
`DateTime.parse` doc says:
> The result is always in either local time or UTC. If a time zone offset other than UTC is specified, the time is converted to the equivalent UTC time.

So my question is how it will parse a local time if no offset is specified?

\* No `Z` indicates it's not UTC, but no offset comes with it

Thanks

**Comment by lrhn** [comment]
Dart `DateTime`, like JavaScript `Date`, supports precisely two time zones: UTC and "local time", which is whatever the operating system says it is. 

You can't specify a specific time zone other than UTC. The only way to get local time is to not specify a time zone at all, in which case it's the local time zone, whatever that is.

So if you specify no time zone at all, you get local time. The actual time zone is then supplied by the OS or browser.

**Comment by busslina** [comment]
I understand, but this is confusing:
> An optional time-zone offset part, possibly separated from the previous by a space. The time zone is either 'z' or 'Z', or it is a signed two digit hour part and an optional two digit minute part. The sign must be either "+" or "-", and cannot be omitted. The minutes may be separated from the hours by a ':'. Examples: "Z", "-10", "+01:30", "+1130".

If `DateTime.parse` allows to parse any TZ datetime, why `DateTime.toIso8601String` does not include the current TZ offset?

An example of use case would be to have serveral servers with different TZ which store a log. If anything goes wrong and I'm not able to know what TZ uses some server, that log info would be dead.


I try to use always UTC but I see here a problem. Also local time is the default for `DateTime`. Isn't it?

**Comment by busslina** [comment]
@lrhn

**Comment by lrhn** [comment]
Thinking of local time as having a time zone is probably not the best explanation.

Instead think of a `DateTime` as either being an "absolute time", a universally usable time stamp, or as a time zone unaware "calendar date plus wall clock time".

Any input with a time zone is an absolute time stamp. It's converted to UTC, instead of remembering the original time zone, but that only matters if you want to show it again. For comparisons, it's the same point in time either way.

An input without a time stamp is not a point in time. It's a calendar date and a clock time, which may mean different things when interpreted in different locations. It's a _relative_ time.

When you convert such a relative local time to string, it doesn't add a time zone, just because that happens to be the current time zone, because that would change the meaning when it's parsed back.

Similarly, parsing an input with a time zone didn't convert that absolute time to local time, even if the time zone happens to be the same as the current local time.

They are fundamentally different ways to represent a point in time, and covering to string and praying back preserves the difference.

The time zone aware value is always represented as the UTC time

**Comment by busslina** [comment]
Okay, anyway I will save logs using UTC to bypass any problem.

I still think that would make sense to have the TZ inside the DateTime object, and to be possible to have/convert to any TZ. Also to print out the TZ offset. Would make it much more flexible
