### ISSUE TITLE
MethodDeclaration doesn't have its typeParameters in the childEntities

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#54457]
The `T extends String` of the snippet bellow is not within the `childEntities` of the `MethodDeclaration` AstNode:

```dart
void methoddd<T extends String>(T arg, {bool boolean = false}) => print(arg);
```

Dart SDK version: 3.2.2 (stable) (Tue Nov 28 11:22:54 2023 +0000) on "macos_x64"

analyzer 6.3.0

**Comment by bwilkerson** [comment]
The `T extends String` should be represented by a `TypeParameter` node, which should be a child of the `TypeParameterList` that is the child of the `MethodDeclaration`. Using an SDK build from HEAD, that's what I'm seeing. It's possible that the bug was fixed after 6.3.0 and hasn't been published yet.

**Comment by scheglov** [comment]
It was fixed in https://github.com/dart-lang/sdk/commit/d86a114d49af1ce65d3d40814bb76cf371d381a7#diff-410d51f7289a5a3e0961fd4a676bc0216b829a60e752b66ae2dabc428fd3392b
Relatively recently, not published.

**Comment by jodinathan** [comment]
@scheglov is it in the beta?
I don't know from the link you mentioned

**Comment by scheglov** [comment]
No, it is not published yet.
Not sure what you can do.
Maybe using `git` dependency.
