### ISSUE TITLE
UTC time can't be converted to MillisecondsSinceEpoch

### ISSUE THREAD

**Issue by Zaherkorechi** [dart-lang/sdk#54469]
I have an issue where I am getting UTC time from the server, and I want to compare it to the mobile time. To ignore the difference of the time zone, the server is sending time in millisecondsSinceEpoch UTC time. However, what I found is that the DateTime library always returns the millisecondsSinceEpoch for local time, not the UTC time zone.

> I ran this code on the Dart.dev website, so I believe it is using Dart v3.2.4.

As you can see by running this code:

```
void main() {
  DateTime now_ = DateTime.now();
  DateTime nowUtc = now_.toUtc();
  
  print("Current UTC  : ${now_.toUtc()} / ${now_.toUtc().millisecondsSinceEpoch} ${now_.toUtc().isUtc}");
  
  print("Current UTC2 : ${nowUtc} / ${nowUtc.millisecondsSinceEpoch} ${nowUtc.isUtc}");
  
  print("Current Zone : ${now_} / ${now_.millisecondsSinceEpoch} ${now_.isUtc}");
}
```

This is the output of it:

```
Current UTC  : 2023-12-28 14:54:43.773Z / 1703775283773 true
Current UTC2 : 2023-12-28 14:54:43.773Z / 1703775283773 true
Current Zone : 2023-12-28 09:54:43.773 / 1703775283773 false
```

**Comment by julemand101** [comment]
> always returns the millisecondsSinceEpoch for local time, not the UTC time zone.

How do you conclude that? If you look at the documentation for `millisecondsSinceEpoch`:
> The number of milliseconds since the "Unix epoch" 1970-01-01T00:00:00Z (UTC).
>
> This value is independent of the time zone.

You can see the returned value does not care about time zones and you will therefore always get the same returned UTC value regardless of your  `DateTime` being localtime or UTC.

**Comment by lrhn** [comment]
What @julemand101 says.

The milliseconds since epoch are milliseconds since 1970-01-01 UTC.

The times you are printing are the same point in time, in different time zones.

Local time seems to be UTC-5, so the local time at the epoch was (assuming the same time zone back then) 1969-12-31T19:00:00.000 with time zone -05:00.

It's working as intended. Comparing the current local time's milliseconds since epoch to the server's value is correct and safe.
