### ISSUE TITLE
How Dart is exactly work?!

### ISSUE THREAD

**Issue by mojtabana** [dart-lang/sdk#54524]
How dart exactly work?!

Please look at this code in dart sdk (process.dart)👇

abstract interface class Process {
  external static Future<Process> start(
      String executable, List<String> arguments,
      {String? workingDirectory,
      Map<String, String>? environment,
      bool includeParentEnvironment = true,
      bool runInShell = false,
      ProcessStartMode mode =   ProcessStartMode.normal});
}

This is just simple abstract method definition!
 
When we call it in our project we do like this👇

    var shell = await Process.start("cat", ["largfile.txt"],runInShell: true);
    if (stdin.hasTerminal){
      stdin.lineMode = false;
      unawaited(stdin.pipe(shell.stdin));
    }
    unawaited(shell.stdout.pipe(stdout));
    unawaited(shell.stderr.pipe(stderr));

Ok!
But I'm curious what exactley VM tell to underlying platform to run this command?!

In SDK as you see in above, we just have abstract class!! Not any implementation!!!

How is it possible?!

**Comment by julemand101** [comment]
Please don't ask your question multiple places right away since it makes it difficult for others to know if you have already gotten an answer. I can at least see you have also asked here:

https://www.reddit.com/r/dartlang/comments/18z05yh/how_dart_exactly_work/

Also, this is an issue tracker for the Dart project and is not the proper place to ask a question like this.

**Comment by eernstg** [comment]
Agreeing with @julemand101, here's one quick way to get some information beyond what you can find in documentation comments and looking into the source code:

```bash
> strace dart format yourprogram.dart |& grep largfile.txt
```

This will work on many Linux distributions, showing the result of all processing done by the layers above the operating system (be it dart or C++ or whatever). Other platforms have slightly different ways to do the same thing.

I'll close the issue because it doesn't suggest a need for any change which is managed in this repository.

**Comment by mojtabana** [comment]
Excuse me
And thanks for your reply🙏🌹

Regards
