### ISSUE TITLE
Future.error(...) : Unhandled exception even in a try/catch block

### ISSUE THREAD

**Issue by d-plaindoux** [dart-lang/sdk#54521]
### Steps to reproduce

Execute the dart code above and check the result with the `dart` command line.

```dart
Future<void> main() async {
  try {
    await Future(() => (int i) => i + 1).then(Future<int>.error(Error()).then);
  } catch (e) {
    print("caught [$e]");
  }
}
```

### Expected results

caught [Instance of 'Error']

### Actual results

Unhandled exception:
Instance of 'Error'

### Logs

```console
> dart main.dart                                                                                                                                                         
Unhandled exception:
Instance of 'Error'
```

### Dart version

```console
➤ dart --version
Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_arm64"
```

### Additional note

If we apply one **eta-expansion** replacing
```dart
await Future(() => (int i) => i + 1).then(Future<int>.error(Error()).then)
```
with 
```dart
await Future(() => (int i) => i + 1).then((vf) => Future<int>.error(Error()).then(vf));
```
we have the expected result.

**Comment by mit-mit** [comment]
cc @lrhn, is this expected?

**Comment by lrhn** [comment]
The code is equivalent to:
```dart
Future<void> main() async {
  try {
    var f1 = Future<int Function(int)>.delayed(Duration.zero, (() {
      return (int i) => i + 1;
    });
    var f2 = Future<int>.error(Error());
    var f3 = f1.then(f2.then);
    await f3;
  } catch (e) {
    print("caught [$e]");
  }
}
```

The `Future(...)` constructor inserts a timer delay with a zero-duration timer, like `Future.delayed(Duration.zero, ...)`.

The `f2` future is an already completed error future, which will report the error in a later *microtask*.

The call to `f2.then` won't happen until `f1` completes, which is long past when the error is reported.
At the time of the error, `f2` has no listeners, so its error is reported as an unhandled asynchronous error.

So, that's working as intended. The `f2` future completes with an error before it has any listeners.


If you ete-expand `Furture<int>.error(Error()).then`, then that changes the behavior.
That's expected. Eta-expansion is not a no-op in a language with side-effects. Here it delays the execution of `Future<int>.error(Error())` until after `f1` has completed, so that `.then` is called on that future *immediately* after it has been created. That prevents the error from being unhandled.


The code is mixing `await` and `.then`, which is allowed, but comes with some risks. When you use `.then` to handle future completion, *you* need to make sure that you do so in time. If you *also* use `await`, you might lose track of where a delay is introduced, and how long it is.

If you only use `await`, and always awaiting a future immediately after it becomes available, then you should be fairly safe.

**Comment by d-plaindoux** [comment]
Worst ...

```dart
Future<void> main() async {
  try {
    var f1 = Future(() => (int i) => i + 1);
    var f2 = await Future<int>.error(Error());
    (await f1)(f2);
  } catch (e) {
    print("caught [$e]");
  }
}
```

works fine when the following one fails

```dart
Future<void> main() async {
  try {
    var f1 = Future(() => (int i) => i + 1);
    var f2 = Future<int>.error(Error());
    (await f1)(await f2);
  } catch (e) {
    print("caught [$e]");
  }
}
```

Since this code has no side effects, it breaks the referential transparency principle.

In addition, the following code works fine:
```dart
Future<void> main() async {
  try {
    var f1 = (int i) => i + 1;
    var f2 = Future<int>.error(Error());
    f1(await f2);
  } catch (e) {
    print("caught [$e]");
  }
}
```

The semantics behind the Future are unclear ...

**Comment by lrhn** [comment]
> Since this code has no side effects

It does have a side-effect. Creating a `Future.error` schedules a microtask to deliver that error. Since `await f1` has to complete before `await f2` is evaluated, the error future will not have a listener when that scheduled microtask triggers, which makes the error be reported as unhandled.

The semantics of futures is actually well-defined. Whether it's sufficiently well *documented* can be discussed, but generally:
* `Future(f)` schedules a zero-duration timer to execute `f` and complete the created future with the result.
* `Future.delayed(duration, f)` schedules a `duration` timer to execute `f` and complete the created future with the result.
* `Future.microtask(f)` schedules a microtask to execute `f` and complete the created future with the result.
* `Future.error(e, s)` schedules a microtask to complete the created future with the error.
* `Future.value(v)` schedules a microtask to completes it with `v` . Except that if `v` is a future, it instead waits for that future to complete, and then completes with the same result. 
* `Future.sync(f)` immediately runs `f`, then schedules a microtask to complete the future with the same result (or if f` returns a future, waits for that future.)

All the `Future` constructors have different behaviors, depending on *when* you want the computation, or the result of a computation.  That's why there is more than one.
If a computation yields a suitable future, they all wait for that future's result. before completing.
But for all of the constructors, if the future completes with an error, the created future must have a listener when it completes, otherwise the error is reported as unhandled.

The solution is to *never* leave a future unawaited across another `await` or other asynchronous gap.
The `f2` future here is created before `await f1`, and not handled until after, and that's why the code is too late to handle the error.
If you want to delay handling of a future until later, at least call `f2.ignore();` to tell the future that an unhandled error is *not* to be reported. (Do remember to handle it later, though, unless you really don't care about an error.)

**Comment by d-plaindoux** [comment]
Thanks for the response even if I think that such semantics are weird, confusing and finally **unsafe** (compared to Kotlin, Rust etc.).

I try to implement a library based on category theory and incarnations for Future algebra is definitively a nightmare (cf. https://github.com/Smallibs/feng)

Anyway, thanks for your time 🙏

**Comment by lrhn** [comment]
If you want to treat futures as inert and storable values, you can call `..ignore()` on every future you create.
Then if it becomes an error, it won't report itself as unhandled, and will wait for you to do something with it.
(Or not, which is also an option.)

The Dart future error behavior is very much a choice, with the goal of not letting an error go unnoticed, since an error suggests that your program might be in an inconsistent state, and continuing blindly can cause bigger problems.
So, it's a design based on a software engineering perspecitive, not mathetmatics. Not handling an error, and continuing running, is considered *more* hazardous than your program being terminated by an unhandled error.
