### ISSUE TITLE
[js_interop] external set no longer compiling on `3.2.0`

### ISSUE THREAD

**Issue by Matthiee** [dart-lang/sdk#54547]
I'm having an issue upgrading to the latest Dart version (3.2.0) when compiling to JS.

We have a simple dart file that needs to make a Dart function callable as a global JS function. 

This was working before on an older Dart version (3.1.4). 

```dart
import 'dart:js';
import 'dart:js_interop';

@JS('cmykToRGB')
external set _cmykToRGB(
    List<int> Function(double c, double m, double y, double k) f);

void main() {
  _cmykToRGB = allowInterop(_cmykToRGBDart);
}

List<int> _cmykToRGBDart(double c, double m, double y, double k) {
  // some conversion
  return [1, 2, 3];
}
```

However, when trying to compile it to JS: 

`dart compile js main.dart`

The following error appears: 

```
Error: Type 'List<int> Function(double, double, double, double)' is not a valid type for external `dart:js_interop` APIs. The only valid types are: @staticInterop types, JS types from `dart:js_interop`, void, bool, num, double, int, String, and any extension type that erases to one of these types.
```

What would be the [correct way](https://pub.dev/documentation/js/latest/) to make a static Dart function callable in JS and add it to the global scope?

We currently have the following workaround, however, I don't think it is the best approach: 

```dart
import 'dart:html';

// ....

setProperty(window, 'cmykToRGB', allowInterop(_cmykToRGBDart));
```

**Comment by navaronbracke** [comment]
You'll have to use the `JSFunction` type, which can be called using the `callAsFunction()` method (is defined on the JSFunction extension in the SDK)

This should get you started at least:

```dart
import 'dart:js_interop';

@JS('cmykToRGB')
external set _cmykToRGB(JSFunction f);

void setCmykToRGB(List<int> Function(double c, double m, double y, double k) f) {
  _cmykToRGB = f.toJS;
}
```

**Comment by srujzs** [comment]
@navaronbracke is right here - we need to convert to make this work.

The reasoning for this change in errors was to separate the two type domains (Dart/JS) and make sure JS values flow into and out of interop so that we have consistent code across all platforms.

In your particular use case, the error is referring to the fact that you're trying to allow a Dart function type `List<int> Function(double, double, double, double)` to flow into JS.

The correct way to provide Dart functions to JS interop is to *convert* them to a type that can flow into JS. In order to do that, we can call `dart:js_interop`'s `toJS` on a `Function`, which will result in a `JSFunction`.

This works when the function you're converting *also* takes in and returns types that can flow into and out of JS. This isn't the case here, as @navaronbracke and the error noted, as you return a `List<int>`. Instead, you want this to be a `JSArray`. There are a number of different ways to produce a `List<T extends JSAny?>` so you can call `toJS`, but @navaronbracke's way works. Another way to do it is to initialize the list with `JSNumber`s in the first place so that you can do avoid an excessive iteration (I have no idea if the calculation is correct, this is just an example) e.g.

```dart
JSArray _cmykToRGBDart(int c, int m, int y, int k) {
  return <JSNumber>[
    (((255-c) * (255-k)) / 255).toJS, // R
    (((255-m) * (255-k)) / 255).toJS, // G
    (((255-y) * (255-k)) / 255).toJS, // B
  ].toJS;
}
```

I'd only add one nit to @navaronbracke's solution, which is to not use `allowInterop` (and remove the import to `dart:js`), as `Function.toJS` is essentially `allowInterop` under the hood on the JS compilers.

**Comment by navaronbracke** [comment]
TIL about that last bit

**Comment by Matthiee** [comment]
@navaronbracke, @srujzs thank you both for the clear explanation. 

Indeed converting it to a `JSArray` was the missing piece. 

The final solution is:

```dart
import 'dart:js_interop';

@JS('cmykToRGB')
external set _cmykToRGB(JSFunction f);

void main() {
  _cmykToRGB = _cmykToRGBJS.toJS;
}

JSArray _cmykToRGBJS(double c, double m, double y, double k) {
  return _cmykToRGBDart(c, m, y, k).map((e) => e.toJS).toList().toJS;
}

List<int> _cmykToRGBDart(double c, double m, double y, double k) {
  // some conversion
  return [1, 2, 3];
}
```
