### ISSUE TITLE
Wrong reading of environment variable.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#54568]
Code in flutter_test_config.dart:

```
import 'dart:io';
...
const String _myVarConst = String.fromEnvironment('LEAK_TRACKING');
String _myVarFromPlatform = Platform.environment['LEAK_TRACKING'] ?? '';

debugPrint('!!! _myVarConst: [$_myVarConst]');
debugPrint('!!! _myVarFromPlatform: [$_myVarFromPlatform]');
```

With command `flutter test --dart-define LEAK_TRACKING=true` on mac: 
```
!!! _myVarConst: [true]
!!! _myVarFromPlatform: []
```

When running on windows bots on github:
```
!!! _myVarConst: []
!!! _myVarFromPlatform: [true]
```

**Comment by lrhn** [comment]
Sounds like it should be an issue for `flutter test`, or the `flutter` command, depending on which one parses and handles the `--dart-define` command line flag.
Are these based on the `dart` CLI tool?

**Comment by polina-c** [comment]
String.fromEnvironment and Platform.environment  are both from pure dart libraries, not flutter, right? 
Are not they expected to provide the same value independently on the way how the values are populated?

**Comment by polina-c** [comment]
> Are these based on the dart CLI tool?

Can you clarify the question?

**Comment by lrhn** [comment]
Both `String.fromEnvironment` and `Platform.environment` reads information that is provided by the runtime or build-time system. The `Platform.environment` reads from the Posix process environment, and `String.fromEnvironment` reads from the Dart compilation environment, which must be set through the compilers. 

The runtime itself should not be able to swap those two, since they're completely different sources of data.
(Unless there is a weird bug, which is always an option, but my guess is that we'd have seen it sooner then.)

So, more likely, something in the system that build and run the program has mixed up the environments, which means the `flutter` tool.

I ask whether the `flutter` tool is based on the `dart` command-line tool, because if it is, the bug could be in there.
If not, it's most likely in the `flutter` tool itself. Seems to be on the Windows path, so that's where I'd start looking.

**Comment by polina-c** [comment]
To clarify: bool.fromEnvironment reads in compile time and Platform.environment reads in run time. Correct?

Then, yes, something wrong with tool.

On mac `print('LEAK_TRACKING = ${Platform.environment['LEAK_TRACKING']}')` gives this output:

```
polinach-macbookpro3:flutter polinach$ echo $LEAK_TRACKING
true
polinach-macbookpro3:flutter polinach$  flutter test --dart-define LEAK_TRACKING=true /Users/polinach/_/flutter_dev/packages/flutter/test/widgets/page_view_test.dart
00:01 +0: loading /Users/polinach/_/flutter_dev/packages/flutter/test/widgets/page_view_test.dart                                                                              
LEAK_TRACKING = null
```

**Comment by polina-c** [comment]
Filed issue: https://github.com/flutter/flutter/issues/141299
