### ISSUE TITLE
[analyzer] Not quite correct error message in case of constant evaluation and operator `+`

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54578]
Now we have the following error
```dart
class C {
  final String value;
  const C(this.value);

  String operator+(String other) => value + other;
}

void main() {
  const c1 = "a" + "b";

  const c2 = C("a") + "b"; // Error. In constant expressions, operands of this operator must be of type 'num'.
}
```
In case of `+` operator the error message should be like `In constant expressions, operands of this operator must be of type 'num' or 'String'.`

Tested on `Dart SDK version: 3.4.0-edge.89bd370e95c0695250a4f0111be3134b9936eadd (main) (Thu Jan 11 03:53:48 2024 +0000) on "linux_x64"`

**Comment by eernstg** [comment]
Right. One more thing, though: the receiver could also be an expression whose static type is an extension type that implements `num`, `String`, or a subtype thereof.

```dart
extension type const E(int it) implements int {
  String operator -(int other) => (it - 2*other).toString();
}

void main() {
  const int c1 = E(2) + 1; // OK.
  const String c2 = E(2) - 1; // Error, not an instance operator.
  String v = const E(2) - 1; // OK.
}
```

We should get an error for `c2` because it will invoke the extension type operator `E.-` (and constant expression evaluation cannot invoke user-written code), but `v` is OK.

It might still be fine to talk about `num` (and `String`) because `E` is actually a subtype of `num`, but I'd recommend that the error message does mention the fact that `E(2) - 1` will invoke an _extension type instance operator_, not an _instance operator_ (that is, the kind that a class/mixin/etc declares, which is subject to late binding at run time).

**Comment by bwilkerson** [comment]
@kallentu Just FYI

**Comment by srawlins** [comment]
Good catch, @eernstg . Your issue(s) are resolved currently; I believe fixed with https://github.com/dart-lang/sdk/commit/7965219df26fec9cab4c79d0659a4a30f74b2f20. The main issue at top is still an issue.
