### ISSUE TITLE
Vague error message with no corresponding documentation.

### ISSUE THREAD

**Issue by dumpster-of-things** [dart-lang/sdk#54579]
Code:
```
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Pick a color'),
          content: SingleChildScrollView(
            child: ColorPicker(
              pickerColor: AppColors.primary,
              onColorChanged: (change) {
              model.selectedColorValue = change.value.toString();
              model.notifyListeners();
              showLabel: true,
              pickerAreaHeightPercent: 0.8,
            ),
          ),
    ...
```

Error:
```
'showLabel' is deprecated and shouldn't be used. Use empty list in [labelTypes] to disable label.
Try replacing the use of the deprecated member with the replacement.dart[deprecated_member_use](https://dart.dev/diagnostics/deprecated_member_use)
```

* Searches on neither the dart, nor flutter docs pages finds anything; nor does googling.
* GPT is also stumped by it and suggested a bunch of hallucinatory nonsense.
[ editor: Cursor (vscode) ]
[       os:  Ubuntu (22.04)  ]

**Comment by mraleph** [comment]
The error message seems pretty clear: it tells you that `showLabel` is deprecated and instead you should use `labelTypes`. 

the error comes from `@Deprecated("...")` put on the `showLabel` parameter of the `ColorPicker` widget. 

https://pub.dev/documentation/flutter_colorpicker/latest/flutter_colorpicker/ColorPicker/ColorPicker.html

**Comment by bwilkerson** [comment]
@Piinks @goderbauer 

Thought you might find this user feedback interesting.

One thought it sparked is whether it might be helpful to support some way of linking from the error message to the documentation for the (in this case) constructor on which the deprecated parameter is defined. This would only help until the parameter is removed, of course, but if there were more detailed docs about how to migrate the code it might be useful.

The link could be done as simply as by inserting a URL in the message (though it wouldn't be clickable in most contexts). We could also look into adding a 'moreInfo' parameter to the `Deprecated` constructor, which the analysis server could then use to provide a clickable link. Or, we could special case deprecations within the flutter package to point to the docs. I like the last idea the least because (a) is wouldn't work for all packages and (b) it assumes that the best documentation is the dartdoc when there might be more useful docs in some cases, such as a breaking change proposal.

Anyway, something to think about. Maybe the message is good enough as-is and we don't need more tooling around this, but if you think we might we can talk about it.

**Comment by goderbauer** [comment]
> One thought it sparked is whether it might be helpful to support some way of linking from the error message to the documentation for the (in this case) constructor on which the deprecated parameter is defined. This would only help until the parameter is removed, of course, but if there were more detailed docs about how to migrate the code it might be useful.

Providing more context (e.g. a link to the docs or to a migration guide) is a great idea and I would love to see that. I wonder how we can do that while keeping the message readable since some of the link are kinda wild (e.g. https://pub.dev/documentation/flutter_colorpicker/latest/flutter_colorpicker/ColorPicker/ColorPicker.html).

**Comment by bwilkerson** [comment]
Yeah, that's why I was thinking of maybe adding a parameter to the annotation constructor. The docs would then look something like
```dart
@Deprecated('Use empty list in [labelTypes] to disable label.', moreInfo: 'https://pub.dev/documentation/flutter_colorpicker/latest/flutter_colorpicker/ColorPicker/ColorPicker.html') bool showLabel = true,
```
and the tooling could use this link instead of the default (https://dart.dev/tools/diagnostic-messages#super_in_extension) when providing a link to docs. The message would then be unchanged. It isn't a perfect solution, but it's the best I've thought of so far.

Of course, without special handling it would be really ugly (and pointless) to include this in the generated docs.

**Comment by Piinks** [comment]
I recall chatting with folks about this in the past, linking to docs in a deprecation message. The trouble with the framework is that a migration guide is often not created by authors anymore if dart fix can handle the move. Further, migration guides are made after a change lands, so the author would have to come back and file another PR to add the link to the message.

Another thought too, this would require folks to use it to make it helpful. The ColorPicker package above is not maintained by the Flutter team. We usually include whatever API folks should move to in the deprecation message. Unfortunately this deprecation message did not provide much help, but we don't have control over what the maintainer puts in that String. What if the `Deprecation` just had a `String replacement` that nudged folks to include this type of info?
