### ISSUE TITLE
JIT snapshot has no documentation on training data

### ISSUE THREAD

**Issue by tomgilder** [dart-lang/sdk#54600]
I can't find any documentation on how training data works with JIT snapshots.

On the [dart compile docs](https://dart.dev/tools/dart-compile#subcommands) it states "JIT-compiled code can have faster peak performance than AOT code if the training data is good".

That sounds great, but I can't find any information on:

- How to provide training data
- At what stage do I provide training data
- What makes better or worse training data

I'm wanting to distribute a Dart app for the first time, and I'm finding it hard to understand the tradeoffs between the different options. I'd love to help improve the docs, but I just don't have the knowledge to do so 😁

**Comment by mraleph** [comment]
https://dart.dev/tools/dart-compile#jit-snapshot explains how JIT snapshots are created. "Training data" here refers to the data you give your program during the training run. What that data is depends on the program of course, e.g. if you made a data processing application you should train it by giving large enough input file (or a number of files). The whole idea behind JIT snapshots is that you run your program and then you save machine code that JIT generated while your program was running. This means that the training run should be long enough and "stressful" enough that JIT actually triggers and optimizes hot part of your program. 

That being said I would recommend to use AOT snapshots instead of JIT snapshots, unless there is a strong reason to want to use JIT. Meaning that you have benchmarked your application and discovered that AOT is doing really poorly (but in this case it is better to report a bug and we try to figure out a way to fix it).
