### ISSUE TITLE
Stream timeout exception thrown too late

### ISSUE THREAD

**Issue by Colman** [dart-lang/sdk#54629]
Hi, I'm having an issue with adding a timeout to a stream created using the `await for` syntax. Here is my code:

```dart
import 'dart:async';

Stream<int> _create(Stream<bool> boolStream) async* {
  await for (final _ in boolStream) {
    yield 8;
  }
}

Future<void> test() async {
  final boolStream = Stream.periodic(
    const Duration(seconds: 10),
    (_) => true,
  );

  final intStream = _create(boolStream);
  final timeoutStream = intStream.timeout(const Duration(seconds: 2));

  try {
    await timeoutStream.first;
    print('No timeout');
  } on TimeoutException {
    print('Timeout');
  }
}

void main() {
  test();
}
```

**Expected behavior**
Prints "Timeout" after 2 seconds

**Actual behavior**
Prints "Timeout" after 10 seconds

This behavior seems odd to me. The `_create` method uses `await` so why is it blocking the print statement from running? If this is expected behavior, is there a way to use the timeout method on a stream returned by an async* function that will behave the way I want?

**Note:** I understand that I could just use `stream.map` instead of my `_create` method to map every value to `8`. However, in my actual code, this cannot be done. I'm leaving it like this to keep the example minimal.

**Dart info**
Dart 3.2.2 (stable) (Tue Nov 28 11:22:54 2023 +0000) on "windows_x64"
on windows / "Windows 10 Pro" 10.0 (Build 19045)
locale is en-CA

**Comment by lrhn** [comment]
Seems odd to me too.
The `.timeout` should create a stream which emits an error if it doesn't get an event from the source stream within the given duration, starting when it's listened to.
It shouldn't matter what kind of stream the source is, only whether and when it emits events.

So, probably a bug, unless I'm missing something.

**Comment by lrhn** [comment]
I was missing something, which is very easy to miss. This is actually working as intended, no matter how annoying that is.

The delay comes from waiting for the cancellation of stream subscriptions, before reporting the error event, and that `async*` functions can be slow to cancel.

The timeout _works_. The `timeoutStream` sends an error event after two seconds.
The `first` code listened to the `timeoutStream` using `cancelOnError: true`, so the subscription cancels itself before delivering the `onError` event. Cancelling a stream subscription returns a future, which is completed when the stream is done cleaning up, and so the error event, sent after two seconds, isn't *delivered* until that cancel-future completes.
(Even if `first` hadn't used `cancelOnError`, it would still have done and waited for the cancel before continuing, because that's the proper way to processing on a stream.)


Cancelling the `timeoutStream` subscription means cancelling its `intStream` subscription. 
Cancelling the `intStream` subscription is cancelling an `async*` function, which can *only happen at `yield` statements*.
At the time of cancelling, the `_create` function execution is waiting at the `await for`, and it'll wait there until the `boolStream`'s first event, at 10 seconds. Then the `_create` execution continues into the loop body, reaches `yield 8;`, notices that it has been cancelled, and *begin* exiting. (Which exits the `await for` loop, which itself waits for cancelling the `boolStream` subscription, which is at least quick.)
That completion ripples up until `first` finally has the error event delivered, and the user sees that the 2-second timeout has happened, after eight seconds of cancelling stream subscriptions.


That's not awesome.
It's also not easy to fix.

We could have an `eagerFirst` which doesn't wait for cancellation. That's bad stream-behavior, and if people start thinking "must use `eagerFirst` instead of `first`, for speed!", we have a problem. So I'd prefer not to.

And we can't really interrupt an `async*` function which doesn't want to be interrupted. That's just rude (and not allowed by language semantics, which are there for your protection).

The one semi-obvious idea is to allow `async*` functions to be cancelled while blocked at an `await for`.
If we did that, it would mean that any `await for` in an `async*` function could be interrupted, whether the author wants it or not. There'd be no way to prevent it. Arguably, if the user of the `async*` function's stream has cancelled, there isn't much the author should *want* to do, other than clean-up, and the stream being `await for`'ed would be cancelled and cleaned up automatically when the `await for` is exited.
Streams are *built* to be cancelled, and to be able to stop at any point, so it's not the *worst* place we could add another interrupt.

It might actually be viable. At least worth considering. It's also quite possible that it's not a good idea, and I have just forgotten why.

(It's often suggested to allow canceling an `async*` function at a normal `await` of a future. That's *not* a viable approach, because it leaves the result of the future without an owner, and there would be no way to protect against that. It makes defensive programming useless when you can't even assume that `var resource = await allocate(); try { .... } finally { resource.dispose(); }` is enough, because the `await` might exit after being handed the resource, but before being able to protect it. Which also means that even if it's possible to interrupt an `async*` function at an `await for`, it can still block cancellation for seconds doing plain `await`s.)
