### ISSUE TITLE
Function with type argument specified cannot be parsed in `as` cast

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#54636]
The following code is rejected by both CFE and analyzer
```dart
int foo<T>(T t) => 42;

main() {
  var v1 = foo; // Ok
  var v2 = foo<int>; // Ok
  var v3 = foo as int Function(int); // throws, I know, but statically Ok
  var v4 = foo<int> as int Function(int); // Error. The operator '<' isn't defined for the type 'int Function<T>(T)'
}
```

Tested on `Dart SDK version: 3.4.0-edge.3f91beb64f8af4705e8e2e6aec1bd78f947b8a31 (main) (Mon Jan 15 23:41:29 2024 +0000) on "linux_x64"`

**Comment by eernstg** [comment]
This would be a parser issue, so I'll use 'area-fe-analyzer-shared'. Note that `foo<int> as Object` fails, too.

**Comment by johnniwinther** [comment]
cc @jensjoha

**Comment by sgrekhov** [comment]
The issue exists for ` var v5 = bar<int> is Object;` as well

**Comment by lrhn** [comment]
IIRC, parsing of recordings of the form `expr<...>` is disambiguated based on the following token. If the token is on a list of specific tokens, the `<...>` is parsed as s type argument, otherwise it's parsed as less-than, ..., greater-than.

Most likely `is` and `as` are not on that list. The main reason is that the syntax was originally for types, and there is no need to years year the type of a `Type` object. It's also usable for instantiating a generic function. Again, if you can do that, it's very likely that you'll also know the type of the result already. So not a big loss.

The reason the words are not included anyway, is that `as` is a built in identifier, not a reserved word, so
```dart
foo(a < b , c > as(d, e))
```
is a valid invocation of a function with two arguments, and a case which requires the disambiguation. (I'm sure there is a version without something looking like a record type too.)

**Comment by eernstg** [comment]
@lrhn, I can't spot any disambiguation rules about terms of the form `<primary> <typeArguments>`. I don't see any ambiguities that aren't resolved by the basic priority rule that Dart always uses: An alternative that occurs earlier in a derivation rule is used if the parse according to that derivation rule succeeds. This corresponds to the situation where alternatives can be given a priority, and then we give every alternative a priority such that textually earlier ones have higher priority than later ones. For example:

```ebnf
<selector> ::=
  '!' |
  <assignableSelector> |
  <argumentPart> |
  <typeArguments>;
```

In the particular case of `foo(a < b , c > as(d, e))`, `< b , c > as` does not parse as any of the earlier alternatives, and hence the parser will consume `< b , c >` as a `<selector>` which is derived via `<typeArguments>`.

The generic-function-call disambiguation rule does not kick in at `<` because the matching `>` isn't followed by `(`.

To me it looks likely that we don't have any special disambiguation rules about this construct (by the way, the fewer special rules the better ;-), but I'd need to take it into account in the spec parser if we do have it.

**Comment by lrhn** [comment]
I'm referring to the "Grammar Ambiguities" section of the [constructor tear-off specification ](https://github.com/dart-lang/language/blob/main/accepted%2F2.15%2Fconstructor-tearoffs%2Ffeature-specification.md).

We decide whether "primary\<identifier, identifier \>" is a type literal/function-instantiation based on the next token, and `is` and `as` e not on the list that allows the text to be type arguments.

The spec states that the grammar is effectively written as having positive/negative lookaheads, which I believe means it also applies when there is no ambiguity possibly, fx because there is only one possible type argument ("primary \< identifier \>", each precludes it being successfully parsed as less-than/greater-than, but if suggest going so for constancy.
We do use the rule eagerly, without checking if a later token would disambiguate.

**Comment by eernstg** [comment]
> I'm referring to the "Grammar Ambiguities" section

Ah, I forgot that this kind of generic function instantiation was included as part of the constructor tear-off feature. Thanks!

> I notice that the spec grammar [didn't actually include](https://dart-review.googlesource.com/c/sdk/+/197161) these lookaheads

That's true, they are not needed in order to handle any ambiguities, because they are already handled by the built-in priorities of _every_ grammar rule of Dart. Also note that the actual parser implementation will naturally implement this kind of prioritization because the basic structure of the parser is recursive descent parsing.

We could add disambiguation rules in, probably, dozens of places in the grammar, but we do also have that overall disambiguation mechanism, so the question is whether or not we should have such rules

Anyway, it's specified like that so we should look into it: https://github.com/dart-lang/language/issues/3588.

**Comment by eernstg** [comment]
Closing: The [specification](https://github.com/dart-lang/language/blob/main/accepted%2F2.15%2Fconstructor-tearoffs%2Ffeature-specification.md#grammar-ambiguities) says that the `<typeArguments>` alternative of the `<selector>` derivation rule is only applicable in the case where the following token belongs to a set that does not include `as` or `is`.

This means that the text `foo<int> as int Function(int)` (or `foo<int> as Object`, it doesn't matter which type is the target of the cast) is not a Dart expression, it is a syntax error. Hence, there is no implementation effort: it is already treated as an error at compile time.

If we want to generalize the grammar to derive this kind of expression then we can handle it in a different issue (in particular, it would be in the language repo, not the sdk repo).
