### ISSUE TITLE
Implement error about awaiting a type that is incompatible with await

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#54647]
The PR https://github.com/dart-lang/language/pull/3560 introduces the notion that a type can be _incompatible with await_. This concept is used to specify a new and broader error about expressions of the form `await e` where the static type of `e` has associations with an extension type that does not implement `Future`.

The previous rules just made it an error when the type was such an extension type, now it is also an error when it is `T?` where `T` is incompatible with await, or a type variable that extends such a type, etc. Details in https://github.com/dart-lang/language/pull/3560. Example:

```dart
extension type N(Future<int> _) {}
extension type F(Future<int> _) implements Future<int> {}

void test<X, XN extends N, XF extends F>(
    N n, F f, X x, XN xn, XF xf, N? nq, F? fq, XN? xnq, XF? xfq) async {
  await n; // Error.
  await f; // OK, type `int`.
  await x; // OK, type `X`.
  await xn; // Error.
  await xf; // OK, type `int`.
  await nq; // Error.
  await fq; // OK, type `int?`.
  await xnq; // Error.
  await xfq; // OK, type `int?`.
  if (x is N) await x; // Error.
  if (x is N?) await x; // Error.
  if (x is XN) await x; // Error.
  if (x is XN?) await x; // Error.
  if (x is F) await x; // OK, type `int`.
  if (x is F?) await x; // OK, type `int?`.
  if (x is XF) await x; // OK, type `int`.
  if (x is XF?) await x; // OK, type `int?`.
}
```

Subtasks:

- https://github.com/dart-lang/sdk/issues/54648
- https://github.com/dart-lang/sdk/issues/54649

**Comment by eernstg** [comment]
Associated test: https://github.com/dart-lang/sdk/blob/main/tests/language/async/await_incompatible_test.dart.

**Comment by stereotype441** [comment]
Here's the current state of things:
- Specification: The initial specification for this error was made in https://github.com/dart-lang/language/pull/3560 on Jan 17. The specification was updated in https://github.com/dart-lang/language/pull/3598 on Jan 31.
- CFE implementation: The CFE implemented the initial specification in 1672177c2023350aeb3e04794a0809cf3310185d on Jan 29, and the update in a5bbbe814fca8856416361ec884482c18c08e470 on Feb 2.
- Analyzer implementation: the analyzer implemented the initial specification in adee0a23999661d7e3c9d25ea44e3fbd399252aa on Feb 9. It has not implemented the update yet.

The branch cut for Dart 3.3 stable was made on Jan 3, so neither the CFE implementation nor the partial analyzer implementation has shipped in any stable release yet.

We (the language team) would like to cherry-pick this new error to a point release of Dart 3.3 stable as soon as possible, to help keep users of extension types from awaiting them in problematic ways. Although this new error is technically a breaking change, it concerns a minor corner case of a brand new language feature; we believe adoption of the new language feature is still low enough that if we act fast, it will be ok to make the cherry-pick without going through the breaking change process.

In order to do that, we need to first complete the analyzer implementation, then do a coordinated cherry-pick of 1672177c2023350aeb3e04794a0809cf3310185d, a5bbbe814fca8856416361ec884482c18c08e470, adee0a23999661d7e3c9d25ea44e3fbd399252aa, and the remaining analyzer work, so that they all land in the same point release of Dart 3.3 stable.

I will coordinate with the analyzer team to get the remaining analyzer work done, and then I'll file the cherry-pick request and coordinate with the scrum team to get it landed.

**Comment by stereotype441** [comment]
As of 690d49c1530d7acf621c285835608c7524eaab85, this is now fully supported in the main branch by the analyzer and front end.

**Comment by stereotype441** [comment]
The fix has been cherry-picked to the stable branch and should go out in the next hotfix release. See https://github.com/dart-lang/sdk/issues/55095 for cherry-pick details.
