### ISSUE TITLE
Unhandled exception when parsing pkcs12 data

### ISSUE THREAD

**Issue by pkuzco** [dart-lang/sdk#54719]
## Details
PKCS12 structures include PKCS7 ContentInfo fields, which, despite having a valid "type," are optional and can be NULL. By creating such PKCS12, it is possible to crash the Dart SDK with an unhandled exception. (this might be classified as a denial of service vulnerability depending on your assessment of this issue)

The issue is in the `usePrivateKeyBytes` method of `SecurityContext`.

## Steps
Use the attached files `poc.dart` and `poc.p12` in [poc.zip](https://github.com/dart-lang/sdk/files/14042184/poc.zip) to reproduce the issue:
`dart poc.dart poc.p12`

## Crash
```
C:\tools\dart-sdk\bin>dart --version
Dart SDK version: 3.2.5 (stable) (Tue Jan 16 15:02:13 2024 +0000) on "windows_x64"

C:\tools\dart-sdk\bin>dart run c:\poc\poc.dart c:\poc\poc.p12
Unhandled exception:
TlsException: Failure in usePrivateKeyBytes (OS Error:
        BAD_PKCS12_DATA(../../third_party/boringssl/src/crypto/pkcs8/pkcs8_x509.c:638)
        passed a null parameter(../../third_party/boringssl/src/ssl/ssl_privkey.cc:448), errno = 318767204)
#0      _SecurityContext.usePrivateKeyBytes (dart:io-patch/secure_socket_patch.dart:241:75)
#1      main (file:///C:/poc/poc.dart:14:19)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by aam** [comment]
Can you confirm contents of `poc.p12` file is valid and parseable with `openssl` for example: ` openssl pkcs12 -in ./poc.p12 -nodes` ?

**Comment by pkuzco** [comment]
I have reported this to the OpenSSL project, as it was crashing on this file as well. The issue will be fixed in the next release:
https://github.com/openssl/openssl/pull/23362

**Comment by pkuzco** [comment]
I have reported this to the OpenSSL project, as it was crashing on this file as well. The issue will be fixed in the next release:
https://github.com/openssl/openssl/pull/23362

**Comment by aam** [comment]
I see, thanks. dart depends on [boringssl](https://boringssl.googlesource.com/boringssl), so the fix has to be picked up by that project.

Also wanted to confirm what the `openssl` fix will do - will it provide better error handling or will it make it such p12 acceptable. The caption of the  suggests the former, where `openssl` was crashing with such files due to null pointer dereferencing. Note that `boringssl` implementation doesn't crash, simply rejects such certificates (https://github.com/google/boringssl/blob/7f45053d42ae0b5f4d5d96fa471d671c6d1462e9/ssl/ssl_privkey.cc#L448)

https://github.com/google/boringssl/blob/7f45053d42ae0b5f4d5d96fa471d671c6d1462e9/crypto/pkcs8/pkcs8_x509.c#L637 is the code which triggers rejection of this sample p12.
How did you create this p12? Knowing this should help with filing a bug against boringssl.

**Comment by davidben** [comment]
Rejecting bad PKCS#12 inputs is indeed the correct behavior. BoringSSL isn't affected by the OpenSSL bug. I think it was just a coincidence that, in the course of diagnosing the Dart + BoringSSL behavior, you found an unrelated bug in OpenSSL that happened to be triggered by the same behavior. :-)

As for what's going on here, I'll defer to Dart folks, but at a glance, Dart seems to be missing a null check here:
https://github.com/dart-lang/sdk/blob/30b7a2f36439da761cb4238d9b82953252a5d67a/runtime/bin/security_context.cc#L805

`SSL_CTX_use_PrivateKey` happens to check for NULL so that's also cleanly returning an error, but that's why you're getting a stray "passed a null parameter". Instead, Dart should not be passing a null parameter in the first place.

Beyond that, I'm not familiar with Dart's APIs but if you try to configure a byte string as a private key, and that byte string cannot be decoded as a private key, throwing an exception seems the correct behavior, no?

**Comment by pkuzco** [comment]
Just some clarifications:
1. I initially found the issue with OpenSSL and not the other way around. The issue in Dart was a byproduct of a broader research I did after identifying the issue with OpenSSL.
2. I am well aware that BoringSSL is not affected, as I have tested it along with other SSL libraries for the issue identified in OpenSSL.
3. I decided to expand my research to investigate whether programming language SDKs/Standard Libraries that parse PKCS12 (and some other formats I was interested in) were also affected. This led me to identify the issue in Dart.
4. As David explained, the issue seems to arise from passing NULL as a private key. This problem would have pertained regardless of the issue I described in my report (Content being NULL in PKCS7 that is part of PKCS12), so this might have added some confusion. So a simple call to `usePrivateKeyBytes` with a wrong password argument, for example, will likely also generate the same outcome.

**Comment by davidben** [comment]
The "issue" with passing NULL as a private key is purely cosmetic. It should be fixed, but once fixed, Dart will still throw an exception. The only change it makes is in the error string. There is no crash and no denial of service.

**Comment by pkuzco** [comment]
I see, I should have actually reviewed the code. I reported this case based on the mere assumption that the API documentation of `usePrivateKeyBytes` would have indicated that it throws an exception if it fails, and since I encountered an "unhandled exception" I assumed that such an exception was supposed to be captured internally by the SDK but it wasn't. So I guess Dart developers may already be aware that they should wrap this in a try-catch block. (just for the record, I'm not a Dart developer :))

https://api.dart.dev/stable/3.2.6/dart-io/SecurityContext/usePrivateKeyBytes.html

**Comment by davidben** [comment]
I also don't know Dart, but given that it's the POC which calls `usePrivateBytes`, I'm pretty sure that error message simply means that the POC should wrap in a try-catch block. That's how every other exception-based language works.

**Comment by aam** [comment]
Thank you for your input @davidben , much appreciated! thanks for additional details @pkuzco .

Yes, exceptions is how the errors are reported, so this is as expected. I went ahead and created CL https://dart-review.googlesource.com/c/sdk/+/348720 that makes exception message in case when private key is missing more clear.

There is also https://github.com/dart-lang/sdk/issues/24184 already which talks about providing more detailed exception messaging produced by `UsePrivateKeyBytes` method.
