### ISSUE TITLE
VM Service getIsolate() does not return when using --pause_isolates_on_start with macro experiment

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#54729]
I'm using SDK version as of 0da8f7a7b48 and the observable_main example from https://github.com/dart-lang/language/tree/main/working/macros/example (at https://github.com/dart-lang/language/commit/b1e958447c811df00e521dfcf47d71005674cb06).

I modified the script to run in a loop:

```dart
Future<void> main() async {
  while (true) {
    var jack = ObservableUser(age: 10, name: 'jack');
    jack.age = 12;
    jack.name = 'john';
    await Future.delayed(const Duration(seconds: 10));
  }
}
```

If I run the application with:

```
C:\Dev\Tools\Dart\Nightly\bin\dart.exe --enable-experiment=macros --observe=0 .\bin\observable_main.dart
```

Everything works fine. I can click the DevTools link, open DevTools, and see the isolates:

![image](https://github.com/dart-lang/sdk/assets/1078012/0da8553c-409e-4280-80c0-df76925142fe)

However, if I add the `--pause_isolates_on_start` flag then DevTools no longer starts up, it just shows a spinner:

![image](https://github.com/dart-lang/sdk/assets/1078012/4b38abce-4833-4b53-8130-b644513033da)

Terminating the app shows that `getIsolate()` was pending when the app shut down:

![image](https://github.com/dart-lang/sdk/assets/1078012/a67866f8-d8aa-4040-804f-8f8e9d7a8bd3)

Trying to use the VS Code debugger shows the same thing - during startup the debug adapter calls `getIsolates()` and that request never appears to complete (although as far as I can tell, there is no error or crash, it just never returns).

#### General info

- Dart 3.4.0-edge.0da8f7a7b480210811514b33067a90485135f580 (main) (Thu Jan 25 11:07:28 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22621)
- locale is en-GB

#### Project info

- sdk constraint: '>=3.3.0-0 <4.0.0'
- dependencies:
- dev_dependencies: _fe_analyzer_shared, args, benchmark_harness, checks, dart_style, frontend_server, test

**Comment by jakemac53** [comment]
cc @bkonyi is this something you could help looking into?

**Comment by bkonyi** [comment]
Sure, I'll take a look.

**Comment by bkonyi** [comment]
Looking at Observatory, it looks like we're spawning two isolates:

- One for `dart-kernel-blob://blob1`
- One for `bin/observable_main.dart`

![image](https://github.com/dart-lang/sdk/assets/24210656/f5eba0ad-87d6-4c5e-9b9c-bb49e30d50bb)

I'm guessing the isolate for `bin/observable_main.dart` relies on some result from `dart-kernel-blob://blob1` before it can actually start running. Where is `dart-kernel-blob://blob1` started? It probably should be marked as a system isolate so it can't be paused on start or exit.

**Comment by alexmarkov** [comment]
`dart-kernel-blob://blob1` is likely an isolate for running a macro. It probably runs before `main` is compiled.

**Comment by bkonyi** [comment]
> `dart-kernel-blob://blob1` is likely an isolate for running a macro. It probably runs before `main` is compiled.

Yeah, the main isolate is blocked on a compilation request. Where is the macro isolate being spawned? The CFE? If so, we should consider making isolates spawned from system isolates inherit the system isolate property.

**Comment by alexmarkov** [comment]
@bkonyi This isolate is created here:

https://github.com/dart-lang/sdk/blob/43fb59f4dc1991863982d5805d2551ed9fb3a28d/pkg/_fe_analyzer_shared/lib/src/macros/executor/isolated_executor.dart#L51

This code is called from CFE (kernel isolate in case of standalone VM).
Do we have a Dart API to mark isolate as "system"?  If not, maybe inheriting "system" property makes sense when an isolate is spawned.

**Comment by bkonyi** [comment]
Updating this line to `api_flags.is_system_isolate = parent_isolate_->is_system_isolate()` resolves the issue:

https://github.com/dart-lang/sdk/blob/43fb59f4dc1991863982d5805d2551ed9fb3a28d/runtime/lib/isolate.cc#L598

However, there may be situations in dartdev (which runs in a system isolate) where we don't want this property to be inherited. @a-siva is working on changes to make dartdev an AOT snapshot, which currently involves starting isolates using `spawnUri` from the dartdev isolate. Inheriting the system isolate property is probably fine for most cases where we do this (e.g., starting `dart2js` or the analysis server), but we wouldn't want to mark an isolate running user code as a system isolate (e.g., `dart run foo.aot`).

**Comment by jakemac53** [comment]
Do we need to add an API to specify that it is a system isolate then?

**Comment by jakemac53** [comment]
Note also that we eventually want to allow debugging of macros at compile time, which sounds like it would interact with this in interesting ways.

**Comment by jakemac53** [comment]
Yes, this is exactly why I brought it up. It is possible we need another category of isolate for these? With its own flag for whether they start paused or not?

**Comment by bkonyi** [comment]
> Do we need to add an API to specify that it is a system isolate then?

We might. It's something I had decided against doing when I added system isolates since there's not many reasons for the average developer to mark an isolate as a system isolate.

> Note also that we eventually want to allow debugging of macros at compile time, which sounds like it would interact with this in interesting ways.

This could be problematic. If we don't mark these isolates as system isolates, we'll end up pausing execution each time we execute a macro. If a user is using lots of macros, this will make the debugging experience _really_ annoying. At the very least, we'd need to provide a way to differentiate between isolates running macro code and regular isolates so we can provide options to not pause macro isolates on start.

Also, there's talks on the VM team about potentially moving the CFE out of the VM into a separate process, which would also have an impact on debuggability of macro generation.

I think that, at least for now, we should not support debugging macro generation and just mark these isolates as system isolates with the fix I proposed above to unblock regular debugging workflows. This is something we'll need to figure out before we ship macros to general users, but is probably isn't critical for shipping JsonSerializable.

**Comment by jakemac53** [comment]
> I think that, at least for now, we should not support debugging macro generation and just mark these isolates as system isolates with the fix I proposed above to unblock regular debugging workflows

I think this is fine for now for sure, as long as we aren't painting ourselves into a corner that we can't get back out of later on 👍

**Comment by a-siva** [comment]
@jakemac53 we have a plan of pulling the kernel isolate out of the VM and running a frontend server for compilation. This model of running macro generation using isolates and debugging it along with the user code may not work in that scenario. Do you think this will be an issue ?

**Comment by jakemac53** [comment]
I do think that the ability to debug macros running inside the compiler itself would be a very useful and appreciated feature for macro authors. But, I wouldn't want to compromise the experience for _all_ developers in the name of that either.

Another possible option here, is we could require some special setup in order for it to work? Maybe you can't debug macros when running through `dart run`, but you can through `dart compile`, etc.

**Comment by a-siva** [comment]
> Another possible option here, is we could require some special setup in order for it to work? Maybe you can't debug macros when running through `dart run`, but you can through `dart compile`, etc.

We would have to account for the flutter developer scenario too, in that case the front end is already out of process and we probably have to wire up a way for debugging macros in that process.

**Comment by bkonyi** [comment]
So unfortunately I don't think we'll just be able to inherit the system isolate property when spawning isolates since there's situations where system isolates expect their children to _not_ be system isolates (see [this example](https://github.com/dart-lang/sdk/blob/main/pkg/vm_service/test/mark_main_isolate_as_system_isolate_test.dart) added in [this CL](https://dart-review.googlesource.com/c/sdk/+/207203)). This behavior is used by the google3 test configuration rules to hide the main isolate which isn't running user code.

We're going to need to figure out another solution to avoid these having this macro compilation isolates constantly blocking execution of the user program when `--pause-isolates-on-start` or `--pause-isolates-on-exit` are provided, but maybe it's sufficient to work around this in DevTools for now so it's at least usable. Until then, you'll have to use Observatory to resume at least the initial macro isolate so the main isolate can become runnable.

**Comment by jakemac53** [comment]
> Until then, you'll have to use Observatory to resume at least the initial macro isolate so the main isolate can become runnable.

Note that there can be any number of these isolates so you probably would want to generally handle resuming anything that looks like a macro isolate.

**Comment by bkonyi** [comment]
> > Until then, you'll have to use Observatory to resume at least the initial macro isolate so the main isolate can become runnable.
> 
> Note that there can be any number of these isolates so you probably would want to generally handle resuming anything that looks like a macro isolate.

Sure, and this should be possible. I think that the DevTools bug that's preventing anything from even loading is only visible if the main isolate is blocked on macro compilation requests. Assuming the main isolate is able to start executing, I think DevTools should work for resuming  any subsequent macro compilation isolates. If hundreds of macro compilation isolates are running before the main isolate is able to start executing, this is going to be painful regardless of which tool you're using.

**Comment by DanTup** [comment]
FWIW, I only used DevTools here as an example for simplicity.. the place I really hit this was VS Code - we fetch all isolates as part of connecting the debugger (so if you press `F5` to try and run any app with macros, it just hangs launching).

I can manually resume things for now to allow me to do some more testing/dev on the debugger, but we'll need a better fix before we expect others might be trying to run code using Macros through VS Code.

**Comment by jakemac53** [comment]
> If hundreds of macro compilation isolates ...

I hope not 🤣 (actually, I think the CFE does do a pretty good job of grouping macros into a small # of isolates, as long as they don't depend on each other).

**Comment by bkonyi** [comment]
> > If hundreds of macro compilation isolates ...
> 
> I hope not 🤣 (actually, I think the CFE does do a pretty good job of grouping macros into a small # of isolates, as long as they don't depend on each other).

I'd really hope not too! 🤣

> Another possible option here, is we could require some special setup in order for it to work? Maybe you can't debug macros when running through dart run, but you can through dart compile, etc.

I was thinking the same thing. I think it's safe to assume most users won't be writing their own macros, so I don't think there's much benefit in supporting debugging macro code generation for general programs. Ideally macro authors would debug their macros in an environment with relatively simple, self-contained code samples. Otherwise, we'd have to provide a way to only debug macro code generation for macros specified by the developer to avoid noise from processing unrelated macros.

Anyway, back to the actual issue. We're going to want to figure out this issue sooner than later since it's going to block debugging workflows in any standalone Dart project using the JIT (I don't think this is going to impact Flutter or the standalone Dart AOT runtime since we won't be spawning macro compilation isolates in-process). This may not be a problem in the long run if we end up moving the kernel service out of process for the JIT VM, but I assume that won't happen until after macros have already shipped.

Some options I can think of off the top of my head:

- We inherit the system isolate flag when spawning isolates from a system isolate, but check for the `--mark-main-isolate-as-system-isolate` flag and add a special case when spawning isolates from the main isolate so that the system isolate property is _not_ inherited.
- We only inherit the system isolate flag for isolates spawned from the kernel isolate.
- We provide a way to specify whether or not an isolate spawned from `dart:isolate` should be a system isolate. I'd like to avoid exposing this concept of system isolates to the average developer unless we absolutely have to.
- We provide `pauseIsolateOnStart`, `pauseIsolateOnExit`, and `pauseIsolateOnUnhandledException` through the `dart:isolate` APIs that allow for overriding the global VM settings for pause behavior for the spawned isolate. This might actually be a nice API to have in general if users are only interested in pausing individual isolates on start / exit / unhandled exception.

The first two options are kind of hacky but are simple, won't require any API changes, and can easily be reverted when we get a better idea about what the macro code generation debugging story is going to look like. The last option may be a generally useful feature, but will take some time to properly implement, so I'm thinking we should move forward with one of the hackier approaches. Any thoughts?

**Comment by jakemac53** [comment]
> (I don't think this is going to impact Flutter or the standalone Dart AOT runtime since we won't be spawning macro compilation isolates in-process)

Just to confirm, this is because it does compilation outside of the flutter tool itself? So, presumably when debugging a flutter app some flag is passed to the VM at some point, but that VM was actually spawned with precompiled kernel code, so no macros are running?

**Comment by bkonyi** [comment]
> > (I don't think this is going to impact Flutter or the standalone Dart AOT runtime since we won't be spawning macro compilation isolates in-process)
> 
> Just to confirm, this is because it does compilation outside of the flutter tool itself? So, presumably when debugging a flutter app some flag is passed to the VM at some point, but that VM was actually spawned with precompiled kernel code, so no macros are running?

Yes, because compilation won't be happening directly within the running Flutter app. This means that the `--pause-isolates-on-start` and related flags won't result in the macro isolates being paused on start, blocking execution in the main process.
