### ISSUE TITLE
[dart2js] Adding hashCode to basic sample reduces code size?

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#54743]
**Edit:** See [below comment](https://github.com/dart-lang/sdk/issues/54743#issuecomment-1912893028) for explanation and more concise reproduction.

This isn't an issue really and it's likely not important as it's not a realistic application, so maybe it's a question. Either way, I found the following surprising:

If I run the following code snippet with `-O4`, **33KB** of JS is generated:

```dart
import 'dart:math' as math;

void main() {
  print(math.pow(5, 5));
}
```

But if I instead print out the hash code of the result, **8KB** of JS is generated:

```dart
import 'dart:math' as math;

void main() {
  print(math.pow(5, 5).hashCode);
}
```

If anything, I'd expect code size to increase size due to JSNumber's `hashCode` implementation and a number being printed out in both cases. Perhaps the `hashCode` has some special guarantees added that `math.pow` doesn't, or a guaranteed return type of `int` enables some optimization? 

Commit tested at: https://github.com/dart-lang/sdk/commit/97edad1568015a3b556d5365fde83d2cf8ca7d81

**Comment by fishythefish** [comment]
I only had a little time to look at this today, but the bulk of the diff is that all of our RTI infrastructure is being pulled in. (Of course, part of that is because there's essentially a single impact for the whole RTI library, so it's all or nothing.)

With `--no-minify`, here's what we compile to:

```js
main() {
  A.printString("" + B.JSNumber_methods.get$hashCode(Math.pow(5, 5)));
}
```

vs.

```js
main() {
  A.printString(A.S(Math.pow(5, 5)));
}
```

The latter uses the `S` string interpolation utility from `js_helper`, and I'm guessing the type tests are pulling in the RTI: https://github.com/dart-lang/sdk/blob/e2f76a18f61d03774c6516c0141b1f653013f555/sdk/lib/_internal/js_runtime/lib/js_helper.dart#L136-L156

---

Smaller repro:

```dart
void main() {
  print(1);
  // print(1.2);
}
```

Uncomment the second `print` and you'll see the output size blow up. Note that if the first `print` is commented out, it goes back down. Ditto if the `1.2` is changed to another `int`, like `2`. When `print` is only passed `int`s or only passed `double`s, it's able to use `printString` directly by using `"" + object` to convert to string. As soon as it's passed both, it starts using `S` to do the conversion, leading to the same issue.

Presumably this is the same thing that happens in the original example due to `Math.pow` returning `num`. I'm not sure why we fall back to `S` so easily; `int`s and `double`s can both be printed the same way, and `S` itself only checks for `is num`.

/cc @rakudrama

**Comment by rakudrama** [comment]
We have a [bug here](https://github.com/dart-lang/sdk/issues/49870#issuecomment-1837243957) which would be fixed by either (1) always calling `JSNumber.toString` (or `S`), or by (2) making a [breaking change](https://dart-review.googlesource.com/c/sdk/+/339520) to always print `-0.0` as `0` on the web.

Fixing the bug via (1) would likely make both programs be 33K. Fixing the bug via (2) would likely make both programs be 8K. Calling `print` a second time prevents the inlining necessary for the optimizer to see that `S` is used on a value of a single type and apply a special reduction, so will get you code like the 33K version.

**Comment by rakudrama** [comment]
I'm going to close this issue as there is nothing we intend to do _directly_ to address the difference.
Sometimes dart2js can remove code!
Sometimes it can't!
We might, over time, make changes that indirectly affect what can and cannot be removed. Generally we want to make changes that are improvements, but sometimes we have to regress code size to fix correctness.
The main thing is that neither program pulls in all but a tiny piece of `dart:core`.
