### ISSUE TITLE
Generic type can't identify the type from dynamic variable while if we used the .runtimeType it get the type correctly

### ISSUE THREAD

**Issue by Abdelazeem777** [dart-lang/sdk#54782]
If we run this code we will get two different outputs:

```dart
 void main() {
  var list1 = ['test1', 'test2'];
  dynamic list2 = ['test1', 'test2'];

  printType(list1);
  print('=============');
  printType(list2);
}

void printType<T>(T responseData) {
  print(responseData.runtimeType); 
  print(T);
}
```

Expected results:
```
List<String>
List<String>
=============
List<String>
List<String>
```
Actual results:
```
List<String>
List<String>
=============
List<String>
dynamic
```

What I need to achieve is to get the type from the "Type" itself so how can we do it?

**Comment by eernstg** [comment]
> What I need to achieve is to get the type from the "Type" itself so how can we do it?

This is not supported in Dart. When you have obtained a reified type (that is, an instance of the class `Type`) from any given Dart type, there is no way back. This is by design: we don't want that kind of "re-discovery" of a type to cause programs to have to retain a lot of otherwise-unused elements. In other words: this could basically destroy the tree-shaking feature of Dart, and that's not acceptable.

**Comment by devoncarew** [comment]
Sounds like this is working as intended.

**Comment by Abdelazeem777** [comment]
@eernstg 

So, in brief 

you mean that the Genrics can only Identify DataTypes that come from the compile-time not from runtime (like what dynamic holds)

Right?

**Comment by eernstg** [comment]
> you mean that the Genrics can only Identify DataTypes that come from the compile-time not from runtime

No, this sounds like type parameter erasure (like in Java), and that's very different from what we do in Dart. Type arguments are represented at run time, and they are used to preserve the soundness of the heap (that is, no variable of type `T` has a value whose type isn't `T` or a subtype thereof; hence, an expression of type `T` evaluates to a value of type `T`, unless it throws). For example:

```dart
void main() {
  var xs = <num>[1]; // `xs` has a run-time type that implements `List<num>`.
  List<Object> ys = xs; // Allowed because of covariance. But `ys` is still a `List<num>`.
  ys.add(1.5); // OK statically, succeeds at run time (`1.5` is a `num`).
  ys.add('Hello!'); // OK statically, throws at run time (`'Hello'` is not a `num`).
}
```

So we certainly do make a distinction at run time between a list with actual type argument `num` and a list with actual type argument `Object`. I think this serves as a counterexample to the statement 'can only Identify DataTypes that come from the compile-time not from runtime'.

Another example is that some types do not even exist at compile time (so we cannot possibly be limited to compile-time types at run time):

```dart
List<Object?> nest<X>(X xs, int k) {
  if (k == 0) return <X>[xs];
  return nest<List<X>>([xs], k - 1);
}

void main() {
  print(nest(0,3).runtimeType); // 'List<List<List<List<int>>>>'.
}
```

This program produces an object whose type is `List<List<... List<int> ...>>`, nested to a depth which is not known at compile time (at least, it is undecidable in general which value an argument like `k` will have at run time, and the type of the returned list depends on the value of `k`).

However, the thing that you cannot do is to go from a Dart type (like `List<int>`, e.g., as a type argument or as the declared return type of a function, etc) to a reified type (that is, an instance of `Type` --- that's an object that represents the type `List<int>`, or the type `String`, or whatever it is), and then go back to a Dart type. The reified type _is not a Dart type,_ it is a _representation_ of a Dart type. This means that you can store it in a list (and do other things that you can do to objects), but you cannot use it to specify the declared type of a variable, and you cannot use it as a type argument in a type, or in an instance creation.

In short, you cannot do this:

```dart
import 'dart:math';

class C<X> {}

void main() {
  Type t = Random().nextBool() ? int : String; // Obtain a reified type `t`.
  t x; // Use it as the declared type of a local variable (error).
  if (t == int) { // Test equality (this works! this is ok! ;-).
    x = 10; // `x` does not have a valid type. Who knows what this would do.
  } else {
    x = 'Hello!'; // Ditto.
  }
  var myList = <t>[]; // Use `t` as a type argument in a list literal (error).
  myList.add(x);
  var z = C<t>(); // Use `t` as a type argument in a constructor invocation (error).
  var w = t(); // Use `t` as a class and try to create an instance (error).
}
```

This program has various compile-time errors, because it makes several attempts to use a reified type as a type. This will not work today, and it is not going to work in the future (because it would be a huge change to the language, and nobody in the language team is likely to want anything of the sort).

> ... get the type from the "Type" itself ...

I'm not quite sure what you're trying to do, but "getting the type from the `Type` itself" sounds a lot like creating a declaration like `t x` or an expression like `C<t>()` above, and that won't work.
