### ISSUE TITLE
@Deprecated in a super class contructor should show in the child

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#54795]
I am extending class `A`, which has a property in it's constructor annotated with `@Deprecated`. Class `B`, which extends class `A` has all of class `A` properties forwarded in it's constructor using the `super.` notation. I need to copy the `@Deprecated` annotation from class `A` to `B`, because the `super.` doesn't shows the field is deprecated in the super class `A`.

Example

```dart
class A {
  A(@Deprecated('deprecated') this.name);

  String name;
}


class B {
  B(@Deprecated('deprecated') super.name); // I need to copy the deprecated annotation here.
}
```

**Comment by lrhn** [comment]
This is working as intended.

You are deprecating API, not implementation. What the `@Deprecated` annotation on the `name` parameter of the `A` constructor means is that *at some poiint in the future*, this parameter will be removed.

Since the parameter is non-optional, there's not much user can do about that, other than switch to another constructor, but it's still information.

It does not imply that:
* The `name` getter of `A` will be removed. (It might get its value from somewhere else.)
* The `name` parameter of the `B` constructor will be removed. (It might be used for something else.)
* Or anything else, at all. Just that that one parameter will, at some point, be removed.

The fact that the `B(name)` parameter is *implemented* using `super.name` is an implementation detail. It's possible to remove the entire `A` class and retain the `name` parameter of the `B` constructor, it just requires changing the implementation, but changing implementation is *not* a breaking change, so it doesn't have to heralded by a deprecation.

Implementation connections between different API elements are implementation details. Each one needs to be deprecated individually, because at the API level, which is what other users see, that implementation connection is, and should be, invisible. And you canchange the implementation without telling them.

If you want to remove `B`'s `name` parameter, you should deprecate it separately. 
And same for the `A.name` getter.

**Comment by feinstein** [comment]
Thank you for the clarification @lrhn, I had a feeling that might be reason, it makes sense.
