### ISSUE TITLE
ReversePc::FindCodeInGroup is_return_address makes invalid PC

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#54817]
https://github.com/dart-lang/sdk/blob/24162bd03f5cd3c0b932a579d378ad2db4889271/runtime/vm/reverse_pc_lookup_cache.cc#L21-L23

Also:
https://github.com/dart-lang/sdk/blob/24162bd03f5cd3c0b932a579d378ad2db4889271/runtime/vm/reverse_pc_lookup_cache.cc#L52-L54

I think these mean to be doing:

```cc
if (is_return_pc) {
   pc -= Instr::kInstrSize;
}
```

Maybe the callee's don't care that they're passed an invalid PC just that it's in the range of "before this one, ignoring whatever instruction alignment this target happens to use"?

Looks like @rmacnak-google added this in https://github.com/dart-lang/sdk/commit/91ed53413990eab8a0410e8c88f00f7a4007330c. 🤷

**Comment by mraleph** [comment]
I have explained on Discord that this is WAI: subtracting 1 from the return address to get address within a (call) instruction is a fairly standard practice and it is not unique to the Dart VM. Subtracting instruction size makes sense (it would give you precisely the call instruction) but X64 does not actually have "instruction size" because all instructions are variable length. So -1 it is.
