### ISSUE TITLE
Auto Complete issue for "tr" and Element.tr()

### ISSUE THREAD

**Issue by BadaySoftware** [dart-lang/sdk#54832]
# **Steps to Reproduce**
Unrelated Element.tr() suggestion after typing **"tr"**;

**in this case expected suggestion with bool type is `true`**
![Ekran Görüntüsü (199)](https://github.com/dart-lang/sdk/assets/143794438/41cf6d04-a1f7-4732-937e-b42f6e8e0b97)

**in this case expected suggestion with color type is `Colors.transparent`**
![Ekran Görüntüsü (198)](https://github.com/dart-lang/sdk/assets/143794438/b057fe9f-c2eb-4787-9af0-c1338318529d)

It may seem like a small problem, but selecting it manually instead of typing tr and continuing with enter can really cause a waste of time even though project has nothing to do with dart:html.

**Comment by lavish123409** [comment]
As no has commented anything yet, I would like to work on this issue.

**Comment by parlough** [comment]
> We should suppress all completions for the dart:html and similar web libraries unless they are already imported.

@scheglov landed that change in https://github.com/dart-lang/sdk/commit/079e433e15281fa52e4cc7ebab1620788a0223a8.

Perhaps that's sufficient for this issue?

**Comment by lavish123409** [comment]
I am unable to find the lsp server file which is handling the completion functionality. Can anyone help me in this?

**Comment by bwilkerson** [comment]
The place where these changes most likely need to be made is in https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/completion/dart/in_scope_completion_pass.dart.

The easiest way to figure out where in that file to start looking is to write a test (typically in https://github.com/dart-lang/sdk/tree/main/pkg/analysis_server/test/services/completion/dart/location) that reproduces the invalid behavior, then set a breakpoint on line 125 of that file (https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/completion/dart/in_scope_completion_pass.dart#L125) so that you can see which `visit` method will be invoked and set another breakpoint in the visit method. From there you can step through to see where the suggestions are being added.

**Comment by jacob314** [comment]
I believe https://github.com/dart-lang/sdk/commit/079e433e15281fa52e4cc7ebab1620788a0223a8 landed by @scheglov resolves this issue as Flutter users should almost never have `dart:html` imported directly and if they do then it is a `p4` not a `p2` issue that they get suggestions from `dart:html`.
