### ISSUE TITLE
[ddc] runtime_debuger_api_test is slow on windows

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#54894]
Since the change to roll a new version of chrome, we are seeing the runtime_debugger_api_test timing out consistently.

This test is large, and could be split into smaller chunks.

Below the autogenerated data from the result feed:
-------------

There are new test failures on [[deps] Bump Chrome to 121.0.6167.85.](https://github.com/dart-lang/sdk/commit/45a0e4d9f3c755f7fdf2dacbbb191192f4404713).

The tests
```
pkg/dev_compiler/test/expression_compiler/runtime_debugger_api_test Timeout (expected Pass)
```
are failing on configurations
```
web-dev-unittest-asserts-win
```

**Comment by nshahan** [comment]
If we believe the test is actually running correctly and timing out because all of the expectations take too long to compile and evaluate then the easiest form of manual shading we could do is to split it in half by null safety mode. The suite already shares all the tests and just duplicates them in each mode.
https://github.com/dart-lang/sdk/blob/3421f48d50afac6fd5912ff657715b655a41a14f/pkg/dev_compiler/test/expression_compiler/runtime_debugger_api_test.dart#L18-L41
