### ISSUE TITLE
VM Tree-shaking worse with extension methods.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#54906]
I have (yet another) attempt at an abstraction over "platforms": https://github.com/lrhn/platform.dart/tree/platforms-opt

It's trying to get both tree-shaking *and* mockability for testing by relying on the compiler recognizing that there is only one concrete subclass of an interface in the program when not testing. It works. Yey.

My problem is that I've added some getters as [*extension* members](https://github.com/lrhn/platform.dart/blob/8975a73bb6113e0135ff088da2bae973824912f6/lib/src/platform_apis.dart#L77).

The example, [`example/tree_shake_shorthand.dart`](https://github.com/lrhn/platform.dart/blob/platforms-opt/example/tree_shake_shorthand.dart), which uses those extension members does not have the same success at tree-shaking as the remaining examples.
Another example is basically the [inlining of those extension methods](https://github.com/lrhn/platform.dart/blob/platforms-opt/example/tree_shake_nullaware.dart). 

If I move the extension members to become instance members of the (`final`, never subclassed) class they are on, the tree-shaking start working.

(There is a script in `tool/` to test how well the compiler tree-shakes all the examples.)

Is there something the VM does for instance methods, that it should also be able to do for extension methods in this example? (Or will I need to move away from extension members.)

**Comment by alexmarkov** [comment]
AFAIK we don't do anything specific for extension methods during tree-shaking. They are essentially just static methods. But you need to be really careful when adding an extra layer on top of existing platform-specific getters in order to make sure compiler can still evaluate them to constants.

@lrhn Could you try annotating those extension methods with `@pragma("vm:platform-const")` pragmas and see if it helps? Without this pragma, compiler would not try to constant-evaluate them for early tree-shaking. It is also possible that constant evaluator fails to handle expressions like `nativePlatform?.isAndroid ?? false` as it doesn't know if `nativePlatform` is `null` or not.

Also note that pragma to control inlining is `@pragma('vm:prefer-inline')` and not `@pragma('vm:prefer_inline')`. Always inlining those extension methods could be sufficient to remove code guarded by those methods.

**Comment by lrhn** [comment]
Using the correct spelling of `prefer-inline` *does* make a difference. (So, well, Doh!)

Can't use `platform-const` on instance members, not even if there are no other implementations of that interface in the program, and the body is platform-const, but `prefer-inline` seems to extract the platform-constant value to where it matters.
