### ISSUE TITLE
[dds] Start DTD from the DevTools server

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#54937]
When the DevTools server is started from an IDE, the IDE starts DTD and then passes the dtd uri to DevTools server. However, when the DevTools server is started from a CLI environment (i.e. if a user runs `dart run` or `flutter run`, then DevTools server will be spawned without a DTD uri being passed from an IDE.

In this case, we want to start DTD from DevTools server and manage the lifecycle.
CC @CoderDake @bkonyi

**Comment by bkonyi** [comment]
It makes sense to do something like this to get DTD support for the CLI use cases.

However, I think we should sit down at some point and collect all the details about how we're launching our various services and daemons to see if we can simplify things a bit. For example, DDS and DevTools are both served in at least 3-4 different ways. It'd be great if we could create a single way to start each of these services (preferably together) rather than having them launched differently based on the context.
