### ISSUE TITLE
Dart aot compilation time

### ISSUE THREAD

**Issue by yhbsh** [dart-lang/sdk#54953]
For some reason.

```dart
void main() {
	print("Hello World");
}
```

```bash
hyperfine 'dart compile exe -o main main.dart'
```

```bash
Benchmark 1: dart compile exe -o main main.dart
  Time (mean ± σ):      1.219 s ±  0.022 s    [User: 1.155 s, System: 0.118 s]
  Range (min … max):    1.203 s …  1.282 s    10 runs
```

can anybody explain why is it taking 1.15 seconds to compile a hello world? this is a big problem i guess, is there any work in progress to improve this?

**Comment by mraleph** [comment]
> can anybody explain why is it taking 1.15 seconds to compile a hello world?

It needs to do global analysis of all Dart code involved (it is more than you see - because Dart core library is written in Dart), then it needs to compile it. Some compiled code is not strictly necessary for hello-world style program, but is still compiled because of how our runtime system and core libraries are entangled. Some passes are implemented in Dart and there is some serialization - deserialization as well as process spawning overheads involved. So baseline costs might be higher than necessary. 

For comparison compiling a program which has 5KLOC takes ~2s and compiling program which has ~150KLOC takes around ~20s.

>  is there any work in progress to improve this?

Yes and no. First of all we don't really care about how fast "hello world" can be compiled. 

For real world compilations we are always looking for low hanging fruits to cut here and there - but I think by now we have collected most of them. 

We have looked at how to parallelize some of the phases of compilation - but this work is going with low priority right now. 

I am also fairly certain that we can get certain amount of improvements when compiling in a single thread - but these improvements would require significant changes, and we don't have capacity for that right now. 

If you have some concrete issues - please file them, we are happy to take a look.
