### ISSUE TITLE
[dart2wasm] language/async_star/async_star_invalid_test/03 passes but expected RTE

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#54973]
The tests
```
language/async_star/async_star_invalid_test/03 Pass (expected RuntimeError)
```
are failing on configurations
```
dart2wasm-linux-chrome
```

Went from flaky to pass.

Test history: https://dart-ci.web.app/#showLatestFailures=false&test=language/async_star/async_star_invalid_test/03&configurations=dart2wasm-linux-chrome

cc @mkustermann

**Comment by mkustermann** [comment]
It turns out that our test infrastructure didn't recognize async tests as being asynchronous when running on browsers.

This is going to be fixed by [cl/354100](https://dart-review.googlesource.com/c/sdk/+/354100).

Apart from that we do have a some bugs for async star, those are already tracked elsewhere.

**Comment by mkustermann** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/54973
