### ISSUE TITLE
[dart:html]: Make SecurityContext + SecureSocket Web capable

### ISSUE THREAD

**Issue by Ahmadre** [dart-lang/sdk#54981]
## Context (Feature Request)

I am contributing to the `mongo_dart` library (https://pub.dev/packages/mongo_dart) and just integrated the X.509 Authentication and it works for all platforms now (except for Web!).

But my problem is, that there's no web capable version of `SecurityContext` to use TLS Certificates like X.509 to authenticate against the Mongo Atlas Cloud.

I found this package that might help with the Socket connection: https://pub.dev/packages/web_socket_channel

But I need the same TLS/SSL implementation like `SecureSocket` / `SecureSocket.connect()` with the use of `SecurityContext` to set the certificate bytes of my X.509 file.

Would it be possible to port  `SecurityContext` and `SecureSocket` to `dart:html`?

## Dart Info

```sh
#### General info

- Dart 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is de-DE

#### Project info

- sdk constraint: '>=3.3.0 <4.0.0'
- dependencies: basic_utils, bson, collection, cross_file, crypto, decimal, fixnum, logging, mongo_dart_query, path, pool, sasl_scram, universal_io, uuid, vy_string_utils
- dev_dependencies: lints, test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
```

## Platforms
- iOS
- Android
- Web (Chrome)
- macOS
- Windows
- Linux

**Comment by mraleph** [comment]
Underlying Web APIs do not allow to supply certificates explicitly, which _kinda_ makes sense. Ask yourself a question: how does certificate get to the client? If it is sent together with other assets of the page then using that certificate for authentication does not really add any security. 

When server requests client to provide a client certificate as part of TLS handshake browser will usually[^1] pop up a window asking user to pick a certificate from an OS specific global certificate store (see screenshots [here](https://jpassing.com/2021/09/27/do-browsers-use-client-certificates-to-authenticate-the-user-the-device-or-both/)).

[^1]: If request is made from context which is not associated with any window then browser will just throw an error instead of showing certificate dialog.

**Comment by Ahmadre** [comment]
> Underlying Web APIs do not allow to supply certificates explicitly, which _kinda_ makes sense. Ask yourself a question: how does certificate get to the client? If it is sent together with other assets of the page then using that certificate for authentication does not really add any security. 
> 
> 
> 
> When server requests client to provide a client certificate as part of TLS handshake browser will usually[^1] pop up a window asking user to pick a certificate from an OS specific global certificate store (see screenshots [here](https://jpassing.com/2021/09/27/do-browsers-use-client-certificates-to-authenticate-the-user-the-device-or-both/)).
> 
> 
> 
> [^1]: If request is made from context which is not associated with any window then browser will just throw an error instead of showing certificate dialog. 

Thanks for the answer.
