### ISSUE TITLE
[analyzer] 'ET' can never match the required type 'ET'

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#54999]
Consider the following example:

```dart
extension type ET(String value) {}

void fn(ET value) {
  switch (value) {
    case ET():  // <-- getting this warning here
  }
}
```

Analyzer gives a warning for `ET` being used in pattern matching (which is expected), but the message is confusing.
`The matched value type 'ET' can never match the required type 'ET'.`

It even tries to provide locations for ET twice (both paths are the same):
<img width="494" alt="Screenshot 2024-02-23 at 18 23 36" src="https://github.com/dart-lang/sdk/assets/21116742/5d3a420c-60eb-435e-bd4a-91f047a8848c">

Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"

**Comment by eernstg** [comment]
Thanks for reporting this, @incendial! This is a known bug, https://github.com/dart-lang/sdk/issues/54561, and it doesn't exist in the 'main' channel of DartPad. It should disappear when the fix has been carried through the pipeline and into a stable release.

(I'm surprised that it wasn't cherrypicked into 3.3.0, but surely it will be included soon.)

I'll close the issue because the fix will be included in a release soon, and there's no need to do anything extra.
