### ISSUE TITLE
extension type nullability is not report by the static type check in VS Code but fail to compile

### ISSUE THREAD

**Issue by wer-mathurin** [dart-lang/sdk#55006]
```dart
extension type I(int i) {
  int get() => i;
}


void main(List<String> args) {
    const I? prop = null;
    prop.get();
}
```
When you compile this give this error:
```
 Error: Method 'get' cannot be called on 'I?' because it is potentially null.
    prop.get();
```

**Comment by scheglov** [comment]
This looks as a bug to me.

However there is a related issue, that I'd like to get help from the language team.
@eernstg 

https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md#errors-and-warnings says "It is an error to call a method, setter, getter or operator on an expression whose type is potentially nullable and not dynamic, except for the methods, setters, getters, and operators on Object.".

Also https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md#nullability-definitions says "We say that a type T is potentially nullable if T is not non-nullable." and "We say that a type T is non-nullable if T <: Object."

What does this mean for this example? Do we report an error here?
```dart
extension type A(int? it) {
  void foo() {}
}

void f(A a) {
  a.foo();
}
```

The [specification](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md) only says "An extension type V is a proper subtype of Object?. It is potentially non-nullable, unless it implements Object".

Here `A` does not implement `Object`.
So, it is potentially nullable, right?
And we do report an error, right?

It does not make much sense to me, because `foo()` seems to be ready to work with `int? it`.
But this what I get from the specifications.
What do I miss?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/354180

**Comment by eernstg** [comment]
> https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md#errors-and-warnings says "It is an error to call a method, setter, getter or operator on an expression whose type is potentially nullable and not dynamic, except for the methods, setters, getters, and operators on Object.".

Right, but that error needs to be specified in a slightly more detailed manner: It is only applicable to instance members declared by a class, mixin, mixin class, or enum declaration. (We don't have an established terminology for this, but you could say that they are 'dispatched instance members', as opposed to the remaining instance members which are statically resolved.)

We already have a well-established (implemented, working) semantics for extension members:

```dart
extension on int? {
  int operator +(int other) => 42;
}

void main() {
  null + 10; // OK.
}
```

Extension type members are treated in the same way: If `E` is an extension type whose interface includes an extension type instance member `m` with signature `T m()` then a member access like `e.m()` where `e` has static type `E` has type `T` and is executed by running the code in the denoted declaration of `m`. No error.

(We can't actually have the case where `E` is an extension type whose interface  includes a non-extension type instance member outside of the 5 `Object` members, and `E` is a potentially nullable type: `E` must then have `Object` as an indirect superinterface, so it's non-nullable.)

However, if the static type of `e` is `E?` where `E` is an extension type (potentially nullable or non-nullable, that doesn't matter) then `e.m()` is an error (so we must make it `e?.m()`).

The proposed updates to the language specification in dart-lang/language#2605 use a different approach, which would eliminate this difficulty: It is specified that the interface of a type of the form `T?` for any `T` is the interface of `Object`. This means that every (non-dynamic) member access to a member which isn't one of the 5 `Object` members will be a compile-time error because that member simply isn't in the interface. This is true for `T?` where `T` is any kind of type, including a `class` type and an `extension type` type.

With that rule in place we will just omit "It is an error to call a method, setter, getter or operator on an expression whose type is potentially nullable and not dynamic, ..." and then there's no need to pay special attention to `extension` and `extension type` instance members: Just compute the interface of the receiver and check that we're accessing something that exists.

```dart
extension type I(int i) {
  int get() => i;
}

void main() {
  const I? prop = null;
  prop.get(); // Compile-time error.
  prop?.get(); // OK.
}
```

**Comment by scheglov** [comment]
Thanks you for the explanation.

**Comment by lrhn** [comment]
Agree. It's really more of a consequence of `T?` not having any members other than those of `Object?`/`Null`.
It's not an error to call `foo` on `T?` because `T?` is potentially nullable, but because that type doesn't have a `foo` member.
(And then only if there is no extension `foo` member that applies.)

An extension type has the member it has, whether it's potentially non-nullable or not, and `I?` here has no members other than those of `Object`, no matter what the extension type `I` has.

**Comment by wer-mathurin** [comment]
@scheglov  very impressive response time to fix it.

It is something that qualifies for a hot fixes that will be cherry picked? And introduce I. The 3.3.x branches.
