### ISSUE TITLE
Why negative indexing in dart list is not present

### ISSUE THREAD

**Issue by DhruvSethi7** [dart-lang/sdk#55026]

**Comment by lrhn** [comment]
Because it can hide errors.

Allowing a negative index to index from the end of the list can be convenient, but it's something you can do as `list[list.length - index]` instead of `list[-index]`, so it's only a convenience.

On the other hand, if you make a mistake like subtracting in the wrong order, `list[min - max]` instead of `list[max - min]`, then allowing negative indices means you don't get an immediate error, instead you get a different value than expected. (Maybe.)

Dart chose to make things like that errors, unlike fx JavaScript which allows *any* index, positive or negative, or any type, and just returns `undefined` if it's not in the 0..length-1 range.
