### ISSUE TITLE
[analysis_server] An error occurred while handling workspace/executeCommand request

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#55092]
Saving a file in VS Code (with the "fix on save" enabled) with the following code results in `An error occurred while handling workspace/executeCommand request`

```dart
void main() {
  // ignore: unnecessary_string_escapes
  const somePath = 'C:\some\path.dart';

  final regexp2 = RegExp('(.pub-cache/|\Pub\Cache\)');
  final regexp4 = RegExp('(.pub-cache/||\\Pub\\Cache\\))');  // <-- removing this line removes the exception
}
```

Full stacktrace
```text
[Error - 16:09:15] Request workspace/executeCommand failed.
  Message: An error occurred while handling workspace/executeCommand request
  Code: -32001 
[Error - 16:09:15] An error occurred while handling workspace/executeCommand request: Bad state: Can't create both a generic file edit and a dart file edit for the same file
#0      BulkFixProcessor._fixSingleError (package:analysis_server/src/services/correction/bulk_fix_processor.dart:743:7)
<asynchronous suspension>
#1      BulkFixProcessor._fixErrorsInLibraryUnit (package:analysis_server/src/services/correction/bulk_fix_processor.dart:612:7)
<asynchronous suspension>
#2      BulkFixProcessor.fixErrorsForFile (package:analysis_server/src/services/correction/bulk_fix_processor.dart:262:9)
<asynchronous suspension>
#3      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#4      IterativeBulkFixProcessor.fixErrorsForFile.<anonymous closure> (package:analysis_server/src/services/correction/bulk_fix_processor.dart:995:23)
<asynchronous suspension>
#5      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#6      _FixAllOperation._computeEditsImpl (package:analysis_server/src/lsp/handlers/commands/fix_all.dart:128:19)
<asynchronous suspension>
#7      TemporaryOverlayOperation.lockRequestsWithTemporaryOverlays.<anonymous closure> (package:analysis_server/src/lsp/temporary_overlay_operation.dart:94:16)
<asynchronous suspension>
#8      LspAnalysisServer.lockRequestsWhile (package:analysis_server/src/lsp/lsp_analysis_server.dart:521:14)
<asynchronous suspension>
#9      _FixAllOperation.computeEdits (package:analysis_server/src/lsp/handlers/commands/fix_all.dart:103:12)
<asynchronous suspension>
#10     FixAllCommandHandler.handle (package:analysis_server/src/lsp/handlers/commands/fix_all.dart:54:18)
<asynchronous suspension>
#11     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:357:11)
<asynchronous suspension>
#12     LspAnalysisServer._handleRequestMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:997:20)
<asynchronous suspension>
#13     LspAnalysisServer.handleMessage.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:452:15)
<asynchronous suspension>
#14     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
<asynchronous suspension>
#15     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:435:11)
<asynchronous suspension>
```

Reproduces stably, Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_x64"

**Comment by incendial** [comment]
@DanTup fyi

**Comment by DanTup** [comment]
@incendial I don't seem to be able to reproduce. The fixes run (the backslashes are removed), but no errors:

https://github.com/dart-lang/sdk/assets/1078012/788d3fdc-cbdc-4cf0-b655-5d0a38d5fc12

Can you reproduce in a new project, or only a specific one? Could you show a list of all the diagnostics you see for this file (and which fixes appear for each of the diagnostics)? It seems like we're trying to use both a `FileEditBuilder` and `DartFileEditBuilder` on the same file but I'm not sure which fix the `FileEditBuilder` is coming from.

**Comment by DanTup** [comment]
btw, looks like I don't have any diagnostics on the last line which might be why I'm not triggering it - I presume if removing that line fixes it, you might have a diagnostic/fix showing up for it?

**Comment by incendial** [comment]
<img width="391" alt="Screenshot 2024-03-04 at 18 41 48" src="https://github.com/dart-lang/sdk/assets/21116742/00ddf367-78ad-49bc-8554-13bd9c167c1e">

Can you try enabling "use-raw-strings"?

**Comment by DanTup** [comment]
@bwilkerson this is happening because the fixes use a mix of generic and Dart file builders. If there is a fix using each in the same file it results in this error when trying to fix both (both for the LSP server's "fix all" and `dart fix`).

For example `remove_unnecessary_string_escapes` uses the generic builder:

https://github.com/dart-lang/sdk/blob/22d75929bd30f7d9246f7ec31a70f834113f7464/pkg/analysis_server/lib/src/services/correction/dart/remove_unnecessary_string_escape.dart#L32

But `convert_to_raw_string` uses a Dart builder:

https://github.com/dart-lang/sdk/blob/22d75929bd30f7d9246f7ec31a70f834113f7464/pkg/analysis_server/lib/src/services/correction/dart/convert_to_raw_string.dart#L44

I thought the right fix would be for the fixes to always use Dart edit builders and we should change the interface so they can't accidentally create other kinds of edit builders. However, we have a fix "Ignore diagnostic in analysis_options.yaml" which is a Dart fix but edits a non-Dart file and I realise that's not quite right.

One possibility would be to have `addGenericFileEdit()` return a Dart edit builder if called for a Dart file - however a Dart edit builder is not currently a superclass of a generic edit builder. So another option could be to just remove `addGenericFileEdit` entirely and force all code through a specific edit builder (Dart or YAML, and if we have other file types, make more specifically-named methods for each of them).

Any thoughts/opinions?

**Comment by DanTup** [comment]
Maybe a slightly simpler idea: add an assert  to `addGenericFileEdit` to ensure it's not called for Dart or YAML files. As long as all callers have _some_ test it should avoid this happening accidentally (but avoids having to make a breaking API change).

**Comment by bwilkerson** [comment]
> For example `remove_unnecessary_string_escapes` uses the generic builder

That's definitely a bug. The fix clearly only applies to Dart files.

> Maybe a slightly simpler idea: add an assert to `addGenericFileEdit` to ensure it's not called for Dart or YAML files.

I like that idea.
