### ISSUE TITLE
External getters/setters/properties on static interop types trigger `Type argument has an object literal constructor` error

### ISSUE THREAD

**Issue by CEksal** [dart-lang/sdk#55107]
#### General info

- Dart 3.4.0-194.0.dev (dev) (Sat Mar 2 00:04:28 2024 -0800) on "linux_x64"
- on linux
- locale is en_CA.UTF-8

#### MRE
```dart
extension type Test._(JSObject _) implements JSObject {
  external set test(bool t); // this also occurs with `external bool get test` and `external bool test`
}

bool test(JSAny v) => v.isA<Test>();
```

#### Expected behavior
This should compile, as `Test` doesn't have an object literal constructor, and so `isA<Test>` should be valid in this case.

#### Actual behavior
Compilation fails with the following error:
```
Error: Type argument 'Test' has an object literal constructor. Because 'isA' uses the type's name or '@JS()' rename, this may result in an incorrect type check.
bool test(JSAny v) => v.isA<Test>();
                        ^
```

#### Additional notes
Ran into this when attempting to use `isA` on `package:web` types like `HTMLDivElement`.

**Comment by kevmoo** [comment]
@srujzs – `is` and `as` with `JSObject` strikes again!

**Comment by srujzs** [comment]
Thanks for filing and the simple repro!

> @srujzs – `is` and `as` with `JSObject` strikes again!

In this case, they're correctly using `isA` and avoiding runtime type checks. :) This is a bug in our lowering due to operator precedence. It specifically occurs when there's a non-constructor `external` member in the type. I have a fix here that just adds parentheses: https://dart-review.googlesource.com/c/sdk/+/355883
