### ISSUE TITLE
Augmentation library issue in case of export

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#55112]
According to the [Augmentation library specification](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md#defining-an-augmentation)

> However, augmentations do not share an import scope with the main library or each other. The libraries one augmentation imports are visible only to that file.

But what about the case whe augmentation library does an export? The current tools behavior differs
```dart
// some_lib.dart
class C {}

// aug_lib.dart
library augment 'main_lib.dart';

import 'some_lib.dart';
export 'some_lib.dart';

// main_lib.dart
import augment 'aug_lib.dart';

main() {
  print(C); // Analyzer error: Undefined name 'C'; VM: No error, prints 'C'
}
```
What is an expected behavior here and which tool wins?

Tested using `Dart SDK version: 3.4.0-194.0.dev (dev) (Sat Mar 2 00:04:28 2024 -0800) on "windows_x64"`

**Comment by eernstg** [comment]
It is tempting to rely on the concept of 'the exported namespace' in order to determine which declarations of the augmentation library are used to augment declarations in the augmented library (if they are `augment` declarations) respectively added directly to the augmented library (if they aren't `augment` declarations).

However, that won't work: The exported namespace doesn't include privately named declarations, but we do want privately named declarations in an augmentation library to be able to have an effect on the resulting augmented library.

Also, we may or may not want to give an augmentation library the ability to re-export declarations from other libraries (augmentation libraries or not): The augmented library might as well `import` or `import augment` those other libraries directly.

Here is one possible rule:

> Every declaration (private or public) in an augmentation library will have an effect on the corresponding augmented library (be added, or be used to augment an existing declaration). An `export` directive in an augmentation library is a compile-time error. Also, it is a compile-time error for a regular (non-augment) import directive to import an augmentation library.

This means that we will avoid the complexity associated with augmentations that are gathered from a DAG of augmentation libraries exporting each other (possibly including some `show` or `hide` clauses).

Another source of complexity is that if we say that we use the exported namespace (with privates, somehow) of the augmentation library to augment the augmented library then, presumably, the augmentation library would be able to turn a regular declaration into something that is added to the augmented library (because we would, presumably, treat all declarations in the exported namespace of the augmentation library the same). For example:

```dart
// ----- 'lib.dart', a regular library.
var x;

// ----- 'augmentation_lib.dart', an augmentation library.
library augment 'main.dart';
export 'lib.dart';

var y;

// ----- 'main.dart'.
import augment 'augmentation_lib.dart';
import 'lib.dart' as lib;

void main() {
  y = 1; // `var y;` is added to this library by augmentation.
  x = 1; // `var x;` also added because it is exported from the augmentation library?
  print(lib.x); // `lib.x` is not the same variable as `x`, right?
}
```

**Comment by lrhn** [comment]
I'll agree that members exported by `export` declarations of an augmentation file should not become visible in the parent file. That allows collapsing multiple augmentations into a single augmentation without changing behavior (at least if all imports are prefixed), which is what macros plan to do if macro-generated augmentation files include further macros.

**Comment by jakemac53** [comment]
> I'd say this implies that the analyzer is right, and the CFE should report that `C` is undefined (but a library that imports `main_lib.dart` will be able to use `C` because that declaration is exported by `main_lib.dart`).

Yes, I agree with this

**Comment by davidmorgan** [comment]
I'm assuming this same issue and resolution applies to unified parts.

Then, exports should not escape part files.

**Comment by davidmorgan** [comment]
I'm assuming this issue and the resolution (exports have no effect in the parent) also applies to unified part files.

**Comment by jakemac53** [comment]
Yes, and the WIP new spec says:

```
Any Dart file can contain an `export` directive. It makes no difference which
file an `export` is in, its declarations (filtered by any `hide` or `show`
modifiers) are added to the library’s single export scope, along with those of
any other  `export`s in the library and the non-private declarations of the
library itself. Conflicts are handled as usual (as an error if it’s not the
*same* declaration).
```

Which should cover this, I am going to close it
