### ISSUE TITLE
flaky->timeout co19/Language/Types/Interface_Types/subtype_t28 fails on dart2wasm-linux-optimized-jsc

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#55123]
[log ](https://dart-ci.appspot.com/log/dart2wasm-linux-optimized-jsc/dart2wasm-linux-optimized-jsc/247/co19/Language/Types/Interface_Types/subtype_t28)

**Comment by osa1** [comment]
Looks like a jsc bug. Should we skip the test and try enabling again when we update jsc @mkustermann?

**Comment by mkustermann** [comment]
@osa1 Looking at the log above, it seems it timed out while compiling with binaryen, not while running with JSC.

For me this test runs in about 30 seconds. It may be that our CI is 2x-4x slower, so that may push it over the 60 second timeout limit.

Looking at the particular test `tests/co19/src/Language/Types/Interface_Types/subtype_t28.dart` it seems to have very deep class hierarchies, it may be that this triggers some non-linear (maybe quadratic or worse) behavior in binaryen. We could consider reporting it to binaryen team.

**Comment by mkustermann** [comment]
Let's close this issue, we'll have to eventually triage all JSC approved failures (but even today the JSC WasmGC implementation has bugs in it, so we're not in a hurry)
