### ISSUE TITLE
Nullable extension types are wonky

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#55149]
(Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64")

Consider the following:

```dart
extension type const Money(double _value) implements double {}

void main() {
  Money? a = Money(5);
  print(a.toInt());
}
```

1. The analyzer indicates no problem
2. On the VM, it fails to compile: `Error: Method 'toInt' cannot be called on 'Money?' because it is potentially null`
3. In Dart2JS it both runs and prints `5`

**Comment by lrhn** [comment]
That's an analyzer bug. It's probably #54664.

**Comment by matanlurey** [comment]
Well on Dart2JS it just runs so 😅

**Comment by eernstg** [comment]
I think it is a non-error because `a` is promoted at initialization (because `Money` is a type of interest when `Money?` is, and the initializing expression is non-nullable). If you add `as dynamic` to the initializing expression there is no promotion, and the analyzer reports the error as expected (and so does the CFE).

```dart
extension type const Money(double _value) implements double {}

void main() {
  Money? a = Money(5) as dynamic;
  print(a.toInt()); // Error.
}
```

So I'd say it is all working as intended.

**Comment by matanlurey** [comment]
Ok, you're right that the following also fails in Dartpad:

```dart
extension type const Money(double _value) implements double {}

void main() {
  print(Money(5));
}

void useMoney(Money? a) {
  print(a.toInt());
}
```

```txt
compileDDC
main.dart:8:11: Error: Method 'toInt' cannot be called on 'Money?' because it is potentially null.
Try calling using ?. instead.
  print(a.toInt());
          ^^^^^
```

Still of course no analysis warnings/errors, but I can track https://github.com/dart-lang/sdk/issues/54664, thanks!
