### ISSUE TITLE
Using `typedef`s with named factory constructors in enhanced enums produces a compiler error

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#55152]
Consider the following example:
```dart
// main.dart
void main(List<String> args) {
  print(Actions.wave.name);
}

typedef _A = Action;

enum Actions {
  smile(_A('smile')),
  wave(_A.named('wave')), // compiler fails
  ;

  const Actions(this.data);

  final Action data;
}

abstract interface class Action {
  String get name;

  const factory Action(String name) = _Named;
  const factory Action.named(String name) = _Named;
}

class _Named implements Action {
  final String name;

  const _Named(this.name);
}
```

Running: `dart run main.dart` produced:
```txt
main.dart:9:11: Error: Non-redirecting const factory invocation is not a constant expression.
  wave(_A.named('wave')), // compiler fails
          ^
```
However, changing: `wave(_A.named('wave')),` to a fully qualified name `wave(Action.named('wave')),` fixes the issue.

`dart --version`
`Dart SDK version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"`

**Comment by shivansh00011** [comment]
In Dart, const constructors must create a constant value, which means that all the arguments passed to them must be known at compile-time. When you use a named constructor within an enum, like Action.named('wave'), it creates a non-constant value because the value 'wave' is not known at compile-time.

However, when you use the fully qualified name wave(Action.named('wave')), the value 'wave' is now resolved at runtime, not compile-time. So, this doesn't raise an error.

To fix the issue, you can use a constant value for the enum constructor. In your case, you could define a constant for the string 'wave' and use it to pass to the named constructor, ensuring that the value is known at compile-time:

// main.dart
void main(List<String> args) {
  print(Actions.wave.name);
}

typedef _A = Action;

enum Actions {
  smile(_A('smile')),
  wave(_A.named(_wave)), // Using a constant value
}

const String _wave = 'wave'; // Define a constant for 'wave'

class Action {
  String get name => throw UnimplementedError();

  const factory Action(String name) = _Named;
  const factory Action.named(String name) = _Named;
}

class _Named implements Action {
  final String name;

  const _Named(this.name);
}

**Comment by eernstg** [comment]
@shivansh00011, you've got a lot of elements of this story right, but one thing isn't true: `'wave'` _is_ actually a constant expression, and it should be fine to pass it to a constant invocation of a constant constructor.

So the problem must be that the CFE does not handle the case where an argument to an enum value declaration is an instance creation where the constructor is denoted by a type alias.
