### ISSUE TITLE
[dart2js] Unexpected type error when compiling with `--dart2js-optimization=O1`

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#55234]
See https://github.com/flutter/devtools/pull/7335 for context

When Dart DevTools is compiled with the `O1` dart2js optimization level, we are getting an unexpected type error (which we don't get when compiling with the default optimization level.)

```
main.dart.js:16366 Failed to handle API message from server:

{"jsonrpc":"2.0","result":null,"id":"4"}

TypeError: null: type 'JSNull' is not a subtype of type 'FutureOr<String>'
```

This happens when:
1. the [`handleMessage`](https://github.com/flutter/devtools/blob/5d1665d751f440c370d7ba259315dd27f2832a04/packages/devtools_app/lib/src/shared/server/server_api_client.dart#L133) method here gets this JSON message: `{"jsonrpc":"2.0","result":null,"id":"4"}`
2. It calls [`_handleResponse`](https://github.com/flutter/devtools/blob/5d1665d751f440c370d7ba259315dd27f2832a04/packages/devtools_app/lib/src/shared/server/server_api_client.dart#L142) with the ID and result (in this case, `"4"` and `null`)
3. [`_handleResponse`](https://github.com/flutter/devtools/blob/5d1665d751f440c370d7ba259315dd27f2832a04/packages/devtools_app/lib/src/shared/server/server_api_client.dart#L181) completes a completer of type `Completer<Object?>` (declared [here](https://github.com/flutter/devtools/blob/5d1665d751f440c370d7ba259315dd27f2832a04/packages/devtools_app/lib/src/shared/server/server_api_client.dart#L79)) with  the `null` result
4. The call to `complete` is failing with the type error: `TypeError: null: type 'JSNull' is not a subtype of type 'FutureOr<String>'`

It seems like dart2js thinks the completer is type `Completer<String>` instead of `Completer<Object?>`

**Comment by elliette** [comment]
This is no longer occurring, therefore closing: https://github.com/flutter/devtools/pull/7382

**Comment by sigmundch** [comment]
Thanks @elliette - I was in the process of replying when I saw your update. Indeed, `flutter web build` uses by default `-O4` which includes some unsafe optimizations. Among those, it removes type checks in places where it could be unsafe. So my first hunch here was that it was likely one such issue.

Looking at [Ben's fix](https://github.com/flutter/devtools/pull/7374/files), it seems to confirm that was the case. Since the completer is created in `_callMethod<T>` using type `T` in `Completer<T>`. The call where `T` is `String` was invalid, but not noticed under `-O4`. 

That aside, I would recommend a slightly different approach to make DevTools reports more intelligible, I'll comment on https://github.com/flutter/devtools/pull/7335 with more details.
