### ISSUE TITLE
Extension type implementing Stream can't be used as a  return types of a async* function

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/sdk#55285]
```dart
extension type CsvStream(Stream<List<String?>> _)
    implements Stream<List<String?>> {}

CsvStream readCsvLines(String filepath) async* {
///
}
```

```
Functions marked 'async*' must have a return type that is a supertype of 'Stream<T>' for some type 'T'.
Try fixing the return type of the function, or removing the modifier 'async*' from the function body.dart[illegal_async_generator_return_type](https://dart.dev/diagnostics/illegal_async_generator_return_type)
```

Dart SDK version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "linux_x64"

**Comment by Cat-sushi** [comment]
Following example is fine,

```dart
extension type Csv(List<List<String?>> _) implements List<List<String?>> {}

Csv parseCsvLines(String string) {
///
}
```

**Comment by eernstg** [comment]
An `async*` function _will_ return an instance of `Stream<T>` for some `T`, no matter what, so your declared return type can't promise a proper subtype of that (you can't expect that function to return a `MySpecialStream<OfAnything>`, because the code that creates the object which is returned isn't written by you, it's generated by the compiler).

However, it would actually be sound to allow this return type to be an extension type whose representation type is an acceptable return type for the `async*` function: If it has representation type `Stream<int>` and we're actually returning a `Stream<int>` then it doesn't hurt (from a soundness perspective) that it is typed as a `MyExtensionType`, where

```dart
extension type MyExtensionType(Stream<int> it) implements Stream<int> {...}
```

See https://github.com/dart-lang/language/issues/3607 for a proposal to do this. You can vote for this proposal if you wish to support the introduction of this kind of relaxation of the rules about the return type of `async*` and similar functions.

**Comment by lrhn** [comment]
Which is also to say that this is working as currently intended, and it's a language change to make it work differently.
The issue belongs in the language repo, not here, but drive there is already an issue there, I'll just close this as a duplicate.
