### ISSUE TITLE
Incorrect error messages while parsing (non-existent) logical operators `or`, `and`, and `xor`

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/sdk#55292]
Tested on dartpad.dev, but the issue is probably very old.
```dart
  int x=0, y=0;
  x = x or y;
  if (x==0 or y==0) {
    
  }
```
Error messages:
Binary operator 'or' is written as '|' instead of the written out word.  
Try replacing 'or' with '|'
Binary operator 'or' is written as '||' instead of the written out word.
Try replacing 'or' with '||'

There's some confusion about what is written how and instead of what.

**Comment by eernstg** [comment]
Looks like this is working as intended: The first occurrence of `or` has operands of type `int`, hence `|` could be used; the second occurrence has operands of type `bool`, hence `||` could be used. It is true that `|` is defined for the type `bool` today, but the vastly most common case is probably that a developer who writes `or` between two boolean expressions would want to use `||` rather than `|`.

**Comment by tatumizer** [comment]
"is written" should be written as "should be written" or "must be written".
"Is written", as written in the dart error message, doesn't have the intended modality.
The issue is small and rare, and I might have been the only user who has ever seen this message though :-)
