### ISSUE TITLE
`uri_does_not_exist` on right click -> new file in VSCode

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#55318]
I have the following file structure in a monorepo:

```txt
/.
  /packages
    /unlimited
      /lib
        engine.dart
        /src
          /engine
            zone.dart
```

Consistently when I add a _new_ file thrugh VSCode, I get `uri_does_not_exist`:

<img width="224" alt="Screenshot 2024-03-27 at 8 14 26 PM" src="https://github.com/dart-lang/sdk/assets/168174/445f8547-c493-4d93-a995-fe64e0e29a5f">

Auto complete even shows the file does exist and helps me select it:

<img width="370" alt="Screenshot 2024-03-27 at 8 12 33 PM" src="https://github.com/dart-lang/sdk/assets/168174/53f3f73f-33c6-4d9f-8c36-d6e054d25c75">

... but I get `uri_does_not_exist` upon doing so:

<img width="529" alt="Screenshot 2024-03-27 at 8 13 05 PM" src="https://github.com/dart-lang/sdk/assets/168174/ff0243af-27ba-4568-875b-676bcbc3625d">

Some other interesting bits:

- Ctrl-click works, I can navigate to the file that doesn't exist (?)
- If I make an edit in the file, everything goes back to normal (as expected)

---

#### General info

- Dart 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
- on macos / Version 14.3 (Build 23D56)
- locale is en-US

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                    |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------- |
|   29 MB | 0.0% |  01-23:21:13 | dart devtools --machine --allow-embedding --port 9100                           |
| 1798 MB | 0.0% |  01-23:21:13 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.84.0 |
|   72 MB | 0.2% |  01-23:21:13 | flutter_tools.snapshot daemon                                                   |

**Comment by a-siva** [comment]
@DanTup

**Comment by bwilkerson** [comment]
@scheglov

**Comment by DanTup** [comment]
@matanlurey do you have exact steps to reproduce this? I tried what I think you're doing, but wasn't able to repro (the red squiggle is just missing semicolon).

https://github.com/dart-lang/sdk/assets/1078012/04850bb0-00c8-47db-a731-87d37a4ccaa3

Capturing a [server log](https://dartcode.org/docs/logging/#analyzer-instrumentation) might be useful too.

**Comment by matanlurey** [comment]
> @matanlurey do you have exact steps to reproduce this? I tried what I think you're doing, but wasn't able to repro (the red squiggle is just missing semicolon).
> 
>  uri.mp4 
> Capturing a [server log](https://dartcode.org/docs/logging/#analyzer-instrumentation) might be useful too.

Other way around, create the `zone.dart` from the menu.

**Comment by DanTup** [comment]
Ah, thanks - I managed to repro it a few times intermittently, but each time was after I deleted and re-used the same filename. I'm not sure if that's coincidence or not - do you know if this is the same for you (did you delete the file once before it happened)?

(I suspect it's coincidence, but since it's intermittent for me and only happened after that, it'd be good to know if that might be a requirement)

**Comment by matanlurey** [comment]
It was consistent for me, but I think I could imagine it being intermittent.

**Comment by DanTup** [comment]
Ok, I think I might be seeing the error only when I've been in that state previously before. It might be coincidence, but I can reliably reproduce it by:

- create the file (`foo.dart`) with an export for `bar.dart` that produces this error (because the file `bar.dart` doesn't exist)
- delete the export from `foo.dart`
- create the file `bar.dart`
- add the export of `bar.dart` back into `foo.dart` (specifically so that the file `foo.dart` is _exactly_ as it was before when it had the error)

@scheglov @bwilkerson do we cache the diagnostics in any way? Could it be that restoring the file to how it was before is getting the old diagnostics (eg. something isn't being flushed correctly when a file is created?). This sounds a little familiar like we may have discussed this before..!

**Comment by DanTup** [comment]
https://github.com/dart-lang/sdk/issues/53683 is the issue I was thinking of which was believed to be fixed (maybe @scheglov has ideas).

**Comment by matanlurey** [comment]
Thanks! If there is anything I can do to help please LMK

**Comment by DanTup** [comment]
I tracked this down why @scheglov's fix didn't handle this. There's an optimisation in the LSP handler that avoids triggering analysis when files don't change, but it mistakenly assumed we would never have a `FileState` for a file that doesn't exist (but we do here, we have one with `exists=false`, but `content` is still an empty string so we treated it as not changing if the new file was also empty).

Working on a fix.
