### ISSUE TITLE
Specify dart line length in lsp configurations

### ISSUE THREAD

**Issue by yhbsh** [dart-lang/sdk#55325]
Hello, this is not an issue rather a question to find a solution

from what i understand, the lsp server uses dart format for formatting, is there a way to override the default 80 character line length? i am using neovim with dartls configuration for nvim-lspconfig.

Thank you!

**Comment by DanTup** [comment]
As long as your client allows you to specify the config, you can use `dart.lineLength` to control the line length for formatting.

In VS Code, you'd do this by adding the following to your user/workspace settings:

```js
"dart.lineLength": 120,
```

The LSP server sends the client a request for the "dart" configuration and then reads the "lineLength" setting. I'm not familiar with nvim-lspconfig so I can't advise how you'd do this specifically. If it doesn't seem to work, please post back with a log of the LSP traffic (if you can't capture this from your client, you can pass `--instrumentation-log-file=/foo/bar.txt` when starting the LSP server).

(I'll close this in the meantime since I think it answers the question, but we can re-open if if not).
