### ISSUE TITLE
[dart2wasm] Compiler ignores library annotation for unwrapped functions

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#55359]
```dart
@JS('__test__')
library;

import 'dart:js_interop';

@JS('__log__')
external T log1<T extends JSObject>(T object);

@JS('__log__')
external T _log<T extends JSObject>(T object);

T log2<T extends JSObject>(T object) {
  return _log<T>(object);
}
```
```js
const dart2wasm = {
  // log1(), incorect
  _123: x0 => globalThis.__log__(x0),
  // log2(), correct
  _13050: x0 => globalThis.__test__.__log__(x0)
};
```

Dart SDK version: 3.5.0-edge.8ca97716cc5f1be89eebd5a79a8f0daa541fd55c (main) on "windows_x64".

**Comment by osa1** [comment]
I don't think the repro is right, could you provide a full example with repro commands?

In your example `_log` and `log1` are identical other than the function name so they can't generate different imports in the .mjs file.

`log2` won't generate an import as it's not annotated with `@JS`, so the comments in your .mjs snippet are not right.

**Comment by ykmnkmi** [comment]
@osa1 I still don't know when it happens, this repro works right now:

```dart
// web/main.dart
import 'dart:js_interop';

import 'package:app/a.dart';

import 'test.dart';

void main() {
  print(log1(JSObject()));
  print(log2(JSObject()));
}
```
```dart
// lib/a.dart
export 'package:app/src/a.dart';
```
```dart
// lib/src/a.dart
@JS()
library;

import 'dart:js_interop';
```

For bigger example try to remove wrappers [here](https://github.com/ykmnkmi/svelte_js.dart/blob/main/lib/src/dom/template.dart#L47):
https://github.com/dart-lang/sdk/assets/53435297/f3990732-bc2f-4955-a6a0-cfe6941591cd

**Comment by srujzs** [comment]
I think this is related to how we cache method calls in our interop specializers, which might be why you see the issue appear when you remove a call, because that may lead to slightly different interop generation. I also think [this code](https://github.com/dart-lang/sdk/blob/eda91b407da71a6ab561c639ce938a0f4a51d146/pkg/dart2wasm/lib/js/interop_specializer.dart#L350) might be contributing to why you're seeing the missing prefix: we use the current library's annotation prefix instead of the interop member's enclosing library's annotation prefix. This shouldn't be an issue due to how we generate procedures, but there's probably a bug somewhere. I'll do some more digging but please share a full repro if you end up finding one.

**Comment by ykmnkmi** [comment]
@srujzs yes, first example.

**Comment by srujzs** [comment]
https://dart-review.googlesource.com/c/sdk/+/361241 should fix this:

```js
const dart2wasm = {
_261: x0 => globalThis.__test__.__log__(x0),
_262: x0 => globalThis.__test__.__log__(x0)
}
```

**Comment by ykmnkmi** [comment]
@srujzs thanks.
