### ISSUE TITLE
Failures on meta: Introduce TargetKind.directive...[web] Add static js interop `.call()` tests

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#55355]
There are new test failures on [meta: Introduce TargetKind.directive...[web] Add static js interop `.call()` tests](https://github.com/dart-lang/sdk/compare/add2f411e68319be2c0abc7ac0bd93b5cd2836fc~...c9474ebaaaa2f263eddcb2ca89dfad205f684cc6).

The test changed from flaky -> RuntimeError (expected Pass) 
```
pkg/frontend_server/test/macros_test RuntimeError (expected Pass)
```

On the configuration:
```
cfe-unittest-asserts-release-linux
```

cc @johnniwinther @davidmorgan

**Comment by davidmorgan** [comment]
Thanks Nick! @jakemac53 FYI

Turns out that this was already broken due to the move from using `package:_fe_analyzer_shared` to `package:_macros`, but that was missed because it was flaky.

Fix to the dep is easy, and I also increase the timeout which should address the flakiness: https://dart-review.googlesource.com/c/sdk/+/360821
