### ISSUE TITLE
[dart2js] Inconsistent `.call` results with dart2js-production-linux-d8 configuration

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#55353]
Mixing static interop with `.call` gives some results on `dart2js-production-linux-d8` that are different from all the other dart2js configurations.

I only noticed because I added tests with expectations for the the current behavior and this is the one configuration that differs.

```
tests/lib/js/static_interop_test/call_getter_test.dart
tests/lib/js/static_interop_test/call_method_test.dart
```

**Comment by fishythefish** [comment]
This seems to be as expected. A test failing only on production dart2js, especially on a line expecting a `TypeError`, usually means the test is affected by `--omit-implicit-checks`. Local testing shows that flag is affecting these two tests.

I'd have to take a look at the static interop kernel transformations to be sure, but presumably it's using implicit rather than explicit checks to ensure type soundness. I don't know if it was intentionally designed like this or not, but this has the advantage that we don't have to pay for those checks in production mode, though with the usual tradeoff of needing to first test in DDC/non-production mode.

/cc @srujzs

**Comment by srujzs** [comment]
The transformations on the JS backends lower to the `js_util` calls which do indeed use an implicit cast from `dynamic` e.g. https://github.com/dart-lang/sdk/blob/ac06b9e00685976c5e41bc9d2162abdf8fb432b3/sdk/lib/_internal/js_shared/lib/js_util_patch.dart#L108.

I presume we can make this work by just adding `/// Requirements=checked-implicit-downcasts` to the tests.
