### ISSUE TITLE
`UP` computes a malbounded type

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#55376]
See also https://github.com/dart-lang/sdk/issues/53685 where this issue occurred as part of a bigger example. Thanks to @dgreensp for catching this!

Consider the following program:

```dart
abstract class A {}
abstract class I {}
class B1 extends A implements I {}
class B2 extends A implements I {}
class C<T extends A> { C(T t); }

void main() {
  // Compile-time error shows that the list has type
  // `List<C<Object>>`, which is malbounded.
  int i = [C(B1()), C(B2())];  
}
```

The program has a compile-time error at the initialization of `i`, and the error message (from the analyzer as well as from the CFE) indicates that the static type of the list literal is `List<C<Object>>`.

This could be expected, based on the fact that `UP(B1, B2) == Object`. However, `List<C<Object>>` is a malbounded type and it should be reported as a compile-time error that this type occurs anywhere (written or inferred) in a program. Alternatively, the type inference step should be considered to have failed, which would then be reported as a compile-time error.

**Comment by lrhn** [comment]
(Is this an opportunity to use a "context guided UP", where if we do **UP**(`C<T1>`, `C<T2>`) and both `T1` and `T2` are subtypes of the bound of `C`'s type parameter, but **UP**(`T1`, `T2`) is not, we could use the bound?)

**Comment by eernstg** [comment]
(Interesting! However, wouldn't #1618 already ensure that we will use the context type `T` as the type of the enclosing branching construct, and then we'd never use the result of `UP(C<T1>, C<T2>)` anyway, we would just check that `C<T1> <: T` and `C<T2> <: T`?)

**Comment by lrhn** [comment]
(Maybe. But only if there is a context type. If **UP**(`C<T1>`, `C<T2>`) is always <code>C\<**UP**(T1, T2)\></code>, and the context type is a well-bounded `C<X>`, `X` a supertype of both `T1` and `T2`, then we'll use `C<X>` as the result. The question is how eagerly we reject <code>C\<**UP**(T1, T2)\></code> as mal-bounded. If we do that *before* checking whether it's assignable to the context type, simply because there should never be an invalid type, then we wouldn't reach the step where we choose the context type instead. And if there is no context type, then we can only use the bound to save us from the malbounded result.)

**Comment by leafpetersen** [comment]
This is a known issue.  See https://github.com/dart-lang/language/issues/651 .  I'd suggest continuing the specification discussion there, and any discussion of unrelated changes to upper bound in a new issue.

Per offline discussion with @eernstg , I'm open to fixing this in various ways.  Whatever path we take, we will need to run some preliminary tests to see how breaking the fix is, and then decide based on that whether to ask for a breaking change, or do a language versioned change.

**Comment by eernstg** [comment]
Right, this issue is a duplicate of https://github.com/dart-lang/language/issues/651 and the most likely outcome is that **UP** will be adjusted to return some other type than the malbounded one, not that **UP** will raise an error.

So I'll close this issue and push on a resolution of dart-lang/language#651. Sorry about the unnecessary noise here.
