### ISSUE TITLE
Enable RBE by default

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#55400]
Is there any reason why RBE is not enabled by default when available?

I appreciate the "This build could be faster" message, but if we already detect that it could be faster, why not just make it so?

**Comment by sigurdm** [comment]
After discussing with @sortie this is not that easy, and would incur an overhead. We have a warning - I guess that is good enough

**Comment by sortie** [comment]
Thanks for asking, I put a lot of thought into the choice of defaults to keep the experience useful, simple, and fast. :)

The problem is that RBE needs two things:

1. You must be a googler on an appropriate team.
2. You must have gcloud application default credentials.

I can appropriate the Googler check fairly well if inexactly, which is what we use to produce the warning if no RBE choice is detected.

However, the credentials cannot be obtained automatically. The command would have to spawn an oauth workflow where you have to enter your password and it's a security anti-pattern to just launch a browser that asks you to enter your password for vague reasons you did not personally intend. Additionally running the gcloud command to check if the credentials already exists takes about 900 ms on my machine and I don't want to add that overhead to all build.py invocations, plus complicate the script even more when it could be really simple. This check would disproportionally slow down small incremental builds which need to be the fastest.

The question then is, should the build fail if an internal developer runs a build without credentials and no explicit opinion on RBE? I say no, because rudely failing it feels inconvenient and non-useful, because the developer expressed intent for what they want and we can give it to them (by building locally). A warning that it could be faster feels appropriate for this situation since there is no error blocking a local build.

Additionally RBE does not work for external developers. Goma was on by default which gave a much worse experience for our friends in the open source community where every guide had to mention --no-goma and they had to remember to use it. Now, everyone can use the same commands to get the same builds.
