### ISSUE TITLE
[WEIRD]: Inconsistency between lambda/ternary and normal if/else.

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#55437]
Using `json_serializable` I have this weird issue. I share the code + video demo.

### Normal (works okay):
```dart
@override
  MaybeInaccessibleMessage fromJson(JsonMap json) {
    if (json['date'] == 0) {
      return TInaccesibleMessage.fromJson(json);
    }

    return TMessage.fromJson(json);
  }
```

### Lambda function + ternary operator (fails):
```dart
@override
  MaybeInaccessibleMessage fromJson(JsonMap json) => json['date'] == 0
      ? TInaccesibleMessage.fromJson(json)
      : TMessage.fromJson(json);
```

Video demo:
[Video_2024_04_11-2.webm](https://github.com/dart-lang/sdk/assets/73592852/ac6ce421-5fc2-46ff-a8dd-a5c403c92dcc)

UPDATE (Class definitions):
![imagen](https://github.com/dart-lang/sdk/assets/73592852/01778e08-ad3a-4200-9ab8-31b78778fb00)
![imagen](https://github.com/dart-lang/sdk/assets/73592852/98e3b810-a073-4f1c-ab7c-c17bc5429186)

**Comment by lrhn** [comment]
The conditional operator, `?`/`:`, is an expression so it needs to have a static type. Its type is found as an upper bound of the static types of the two branches.

Here that's `TInacccessibleMessage` and `TMessage`.
Those two types have multiple common superinterfaes, `Indexable`, `Versionable`, `Cacheable`, `EquatableMixin` and `maybeInaccessbileMessage`. Each of those can be an upper bound of the two types, and the upper bound algorithm chooses `Cacheable` because it's "most specific" in some particular metric.
Not what you wan't, but not *wrong*.

Then you get an error because the context wants a `MaybeInaccessibleMessage`.

Luck has it that @stereotype441 has already implemented a better upper bound for cases precisely like this, where the result wouldn't match the context, but each branch's type would. It will then use the context type instead.
You'll have to wait for the next Dart release to get that behavior. Until then, either just stick with the `if` statements. (I personally find them *more* readable than the conditional expression), or add an `as MaybeInaccessibleMessage` cast on one of the branches (might have to silence an "unnecessary cast" warning, though).

So "fixed", just not released yet.

**Comment by busslina** [comment]
Thank you very much :) @lrhn
