### ISSUE TITLE
extension type auto import

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/sdk#55443]
Related https://github.com/dart-lang/sdk/issues/38894

```dart
extension type UserId(String _value) implements String {}
```

I'd expect the above to be discoverable and not have to manually type the import each time.

**Comment by lrhn** [comment]
It should be as discoverable as a class. If it isn't, that is probably a mistake.

**Comment by Tienisto** [comment]
The extension is visible while writing (autocomplete) but there is no "Quick Fix" after the extension type has been already written.

**Comment by denniskaselow** [comment]
The quick fix is available on the constructor:
![image](https://github.com/user-attachments/assets/5c861a6e-91d4-4012-b4f9-6847c49dea80)

But not on the type:
![image](https://github.com/user-attachments/assets/0260a230-bb14-4dcb-a228-59ecd1ccd996)

**Comment by cedvdb** [comment]
This was closed but the PR was not merged ?

**Comment by FMorschel** [comment]
@cedvdb
Yes, it was a little weird the first time I saw this. The issue was closed on Gerrit. If you take a look at the PR there is a bot telling you about a new link:

https://dart-review.googlesource.com/c/sdk/+/386701

This is where the code got merged. They usually don't use PRs I was starting to help when I opened it. They use CLs directly at Gerrit. Since the code was already committed in Gerrit, the PR can't be merged, so it looks like it got closed.
