### ISSUE TITLE
Semantics of `dart:js_interop`s `Function.toJS` extension

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#55515]
The `toJS` extension method on `Function` from `dart:js_interop` seems to behave differently across backends:

* In wasm we simply make a JS function that will call the wasm function - handled via kernel transformer on callsites
  => See [here](https://github.com/dart-lang/sdk/blob/b1b3e34b88dec3744f15da122ffb0c5e204f7bb5/pkg/dart2wasm/lib/js/interop_transformer.dart#L80) & [here](https://github.com/dart-lang/sdk/blob/b1b3e34b88dec3744f15da122ffb0c5e204f7bb5/pkg/dart2wasm/lib/js/callback_specializer.dart#L246)
* In ddc it seems to use `allowInterop()` and therefore maintain identity (`allowInterop` uses `Expando`s in ddc)
  => See [here](https://github.com/dart-lang/sdk/blob/b1b3e34b88dec3744f15da122ffb0c5e204f7bb5/sdk/lib/_internal/js_shared/lib/js_interop_patch.dart#L79) & [here](https://github.com/dart-lang/sdk/blob/b1b3e34b88dec3744f15da122ffb0c5e204f7bb5/sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart#L13)
* In dart2js it seems to also use `allowInterop()` and therefore maintain identity (`allowInterop` uses different mechanism, not `Expando`s here)
  => See [here](https://github.com/dart-lang/sdk/blob/b1b3e34b88dec3744f15da122ffb0c5e204f7bb5/sdk/lib/_internal/js_shared/lib/js_interop_patch.dart#L79) and [here](https://github.com/dart-lang/sdk/blob/b1b3e34b88dec3744f15da122ffb0c5e204f7bb5/sdk/lib/_internal/js_runtime/lib/js_allow_interop_patch.dart#L16)

From the discussion at https://github.com/flutter/flutter/issues/143396 I infer that `allowInterop` shouldn't be needed in the new static interop world. Meaning we don't want to maintain identities when things flow back into dart.

For performance reasons it's also much better not to use `Expando`s etc when making a callback.

So
* either dart2js/ddc can avoid maintaining identity for `dart:js_interop`s `Function.toJS` extension method implementation
* or we we need to make dart2wasm maintain identities, in which case I'm going to ask for a new API that does not require maintaining identities

/cc @srujzs @sigmundch

**Comment by sigmundch** [comment]
Sounds great to me to use an alternative to allowinterop.

@srujzs and I were discussing this also for a separate reason: the default implementation of allowInterop uses `Function.apply` when the [callback is invoked](https://github.com/dart-lang/sdk/blob/b1b3e34b88dec3744f15da122ffb0c5e204f7bb5/sdk/lib/_internal/js_runtime/lib/js_allow_interop_patch.dart#L54) from JS. This is expensive and we can clearly do better here. We'd like to have specialized conversions for very common callbacks (e.g. callbacks of 0, 1, and 2 args), which can then avoid using the dynamic Function.apply dispatch mechanism.

Small piece of context: for the old `package:js` interop, allowInterop needed the expando to provide consistent semantics between DDC and dart2js. Without it, DDC was being more permissive than dart2js, which is a bad recipe: we want to detect any issues early during development. Dart2js uses a different representation of closures and needed allowInterop to convert the representation. However, because in DDC Dart closures are JavaScript closures, missing the allowInterop on an API call used to go undetected. We added the expando to properly check that allowInterop was used.

The new interop can make this distinction statically, so it shouldn't need that mechanism anymore.

**Comment by srujzs** [comment]
Agreed that we should be consistent here with identity. A potentially common instance where this might come up that might be an issue is event listeners. `addEventListener(f.toJS); removeEventListener(f.toJS);` will do different things depending on the platform.
