### ISSUE TITLE
Document @mustBeOverridden contract to make more clear

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#55550]
```dart
import 'package:meta/meta.dart';

class A {
  @mustBeOverridden
  void a() {}
}

class B {
  @override
  void a() => super.a();
}
```

I can't win in this scenario, either I get a unnecessary_overrides lint or a must_be_overridden hint.

**Comment by matanlurey** [comment]
CL out: https://dart-review.googlesource.com/c/sdk/+/364206.

**Comment by lrhn** [comment]
Can you write: 
```dart
class B {
  @override
  void a();
}
```
and satisfy the `@mustBeOverridden` requirement?

It's better than adding `=> super.a()`, and it still shows an intentional "keep the same behavior" choice. You haven't just forgotten that the member exists. 

I'd say it should be valid, of writing nothing isn't. 

And if not, it would be a declaration you could hang an ignore of the `mustBeOverridden` on.

(Never override just to call super, workout changing any type. At least not unless the method is `noSuchMethod`. )

**Comment by matanlurey** [comment]
Closed in https://dart-review.googlesource.com/c/sdk/+/364206.
