### ISSUE TITLE
analyzer throws "type_argument_not_matching_bounds" on extension type

### ISSUE THREAD

**Issue by iapicca** [dart-lang/sdk#55583]
if we wrap a `class` in a `extension type` it stops being considered an `Object`
as the linter starts yelling [type_argument_not_matching_bounds]( https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=type_argument_not_matching_bounds#type_argument_not_matching_bounds)

```dart
import 'dart:ui';

typedef SomethingToString<T extends Object> = void Function(T);

class Foo extends Object {
  const Foo();
}

extension type Bar(Foo foo) {}

class Baz {
  const Baz();
}

extension type MyOffset(Offset offset) {}

SomethingToString<Foo> get fooHello => (i) => 'hello';

SomethingToString<Bar> get barHello => (i) => 'hello';

SomethingToString<Baz> get bazHello => (i) => 'hello';

SomethingToString<Offset> get offsetHello => (i) => 'hello';

SomethingToString<MyOffset> get myOffsetHello => (i) => 'hello';

```

dartpad [link](https://dartpad.dev/?id=ca267d0aa7c167c05d12e04b84a9655a)

not sure if it's intended, if so may I ask why

the code below fix the issue, but it feels weird
```dart
extension type Bar(Foo foo) implements Object {}
```

possibly related to https://github.com/dart-lang/sdk/issues/54813

**Comment by lrhn** [comment]
It's intended. 
The only reason `implements Object` looks weird is that you're not used to *needing* to implement `Object`, because all classes (other than `Null`) are automatically subtypes of `Object`, and all record and function types are subtypes of `Object.

There are very few types in the pre-extension-type type system that don't automatically implement `Object`.
The one exception is type variables, a `foo<T>() { ... T ...}` introduces a type which is *not* a subtype of `Object`. To make sure that it is, you have to write `<T extends Object>`.
You can sometimes think of extension types in the same way. Extension types don't automatically become subtypes of `Object`, because they are *types*, not *classes*. And if you want them to, you have to add `implements Object`.

**Comment by iapicca** [comment]
> An extension type like:
> 
> ```dart
> extension type const Opt<T>._(({T value})? _) {
>   const Opt.value(T value) : this._((value: value));
>   const Opt.none() : this._(null);
> }
> ```
> 
> has a nullable representation type, and _cannot_ implement `Object`.

yeah, makes sense thank you for your answer @lrhn
