### ISSUE TITLE
Extensions on Object? are not working

### ISSUE THREAD

**Issue by BirjuVachhani** [dart-lang/sdk#55620]
## Example code

```dart
void main() {
  final Map map = {
    'isLoading': true,
    'isError': false,
    'name': 'John',
    'age': 25,
    'stars': 4.5,
    'aliases': [],
  };
  
  
  String? str;
  
  print('gfd'.isBlank); // false
  print(''.isBlank); // true
  print(str.isBlank); // true
  print(map['hello']?.toBool()); // null
  print(map['name']?.toBool()); // Error, Expected: null
  print(map['aliases']?.toBool()); // Error, Expected: null
  print(map['stars']?.toBool()); // Error, Expected: null
  print(map['age']?.toBool()); // Error, Expected: null
  print(map['isLoading']?.toBool()); // Error, Expected: null
}


extension ObjectExt on Object? {
  
  bool? toBool() {
    final value = this;
    if (value == null) return null;
    if (value is bool) return value;
    if (value is int) return value != 0;
    if (value is double) return value != 0;
    if (value is num) return value != 0;
    if (value is String) {
      final parsedBool = bool.tryParse(value, caseSensitive: false);
      if (parsedBool != null) return parsedBool;
      final parsedNum = num.tryParse(value);
      if (parsedNum != null) return parsedNum != 0;
    }
    return null;
  }
}

extension NullStringExt on String? {
  bool get isBlank => this == null || this!.isEmpty;
}
```

### Output

```
false
true
true
null
Class 'String' has no instance method 'toBool'.
Receiver: "John"
Tried calling: toBool()
```

This throws `Class 'String' has no instance method 'toBool'` error. This code seemed to be working before on older versions of Dart SDK.

Extension on `String?` seems to be working just fine but extension on `Object?` doesn't work. I have tried the following too but it also doesn't work!

```dart
extension ObjectExt<T extends Object> on T? {
...
}
```
and

```dart
extension ObjectExt<T extends Object?> on T {
...
}
```

However, if I assign it to a variable of type `Object?` and then try to call `toBool()` on it then it works! Doing the following works!

```dart
Object? obj = map['isLoading'];
  
print(obj.toBool()); // prints true
```

Am I doing something wrong? I could almost swear this was working before! Is this a recent change? If it is, how do I make it work again?

### Environment
Channel: Stable
SDK Version: 3.3.4

**Comment by eernstg** [comment]
You probably just want to avoid using a raw type like `Map`. Make it `final Map<String, Object?> map`, and there is no run-time error.

**Comment by SaadArdati** [comment]
@eernstg In some large codebases like ours, we can't enable these analyzer hints because we rely on raw types in a few areas. This includes raw-types on a modified implementation of json_serializable factory functions.

The root of this issue is that the base type of a map retrieval operation is Object?, and yet the dart SDK seems to be ignoring it in this specific scenario. Your solution is offering a workaround on a potentially bigger problem.

**Comment by BirjuVachhani** [comment]
Yeah explicitly casting it to `Object?` works and doesn't throw but if it can cast it to `Object?` than it should be able to call an extension on `Object?` too since it would be its super type, unless I am misunderstanding something! Can you confirm whether this would've worked before? We had this code in our codebase and it was working fine until now. I can't confirm the last working version of Dart SDK though.

My reference: 
https://dart.dev/null-safety/understanding-null-safety#top-and-bottom
<img width="936" alt="image" src="https://github.com/dart-lang/sdk/assets/20423471/d2e60e24-cc60-48e7-861d-79c50947bb3e">

**Comment by lrhn** [comment]
The raw type instantiates to bounds, which means `dynamic`, and extension methods do not work on `dynamic`.
Instantiate to bounds works like that for historical reasons (it was a way to make the Dart 2.0 type system viable, without breaking too much existing code that relied on things being `dynamic`.)

If you do:
```dart
final Map foo = { ... };
```
you are effectively writing 
```dart
final Map<dynamic, dynamic> foo = { ... };
```
which means that `foo['hello']` has type `dynamic`, and you can't call extension methods on it.

Changing it to `final Map<String, Object?> foo = {...};` or just `final foo = {...};` will avoid the raw type that gets instantiated to bounds, which makes `foo['hello']` have type `Object?`, and then the extension method works.


I'm all for changing what instantiate to bounds do, but that's a larger breaking change, and won't help you any time soon.

**Comment by eernstg** [comment]
> we rely on raw types in a few areas

You can turn off `strict-raw-types` by having some `exclude` clauses in your `analysis_options.yaml` or by putting `// ignore: strict_raw_type` just before the affected lines, or `// ignore_for_file: strict_raw_type` in the affected libraries. You could also pass `dynamic` as an actual type argument explicitly. So you do have a number of ways to enable this warning and still disable it in some locations.

> base type of a map retrieval operation is `Object?`, and yet the dart SDK seems to be ignoring it in this specific scenario. 

The return type of operator `[]` on `Map<K, V>` is `V?`. It will be `dynamic?` (which is immediately normalized to `dynamic`, which doesn't matter) when the actual type argument passed to `V` is `dynamic`.

So there's nothing exceptional about the type of `map['hello']` in this case.

**Comment by lrhn** [comment]
It's not documented in the language tour, but it is mentioned in other places, for example the style guide:
 [Avoid writing incomplete generic types](https://dart.dev/effective-dart/design#avoid-writing-incomplete-generic-types).

It *is* surprising and annoying, and if it wasn't for the historical reasons, it probably wouldn't be like that.
The fact that writing:
```dart
final foo = {"a": 1};
final Map foo = {"a": 1};
final Map<String, int> foo = {"a": 1};
final foo = <String, int>{"a": 1};
final Map foo = <String, int>{"a": 1};
final Map<String, int> foo = <String, int>{"a": 1};
```
gives different results for just the `Map`-typed ones is annoying, it looks like a place where inference *could* supply the type arguments. It isn't, for numerous reasons (Dart only infers type arguments in invocations ... and now patterns, but not in types).
And then it's doubly annoying that it defaults to `dynamic` instead of `Object?`, for said historical reasons.

But until we manage to change that, it is what you have to work with.
The `strict-raw-types` is a good suggestion. There shouldn't be any situation where you *need* to write a raw type. If you want `Map<dynamic, dynamic>` you can still write it explicitly.

**Comment by eernstg** [comment]
> if it can cast it to `Object?` than it should be able to call an extension on `Object?` too

As I mentioned [here](https://github.com/dart-lang/sdk/issues/55620#issuecomment-2090254864), `dynamic` is assumed to have all instance members, with all possible signatures, and (assumed) instance members have a higher priority than extension members. This is not a subtype based property, this is a special affordance which is given to the type `dynamic`, such that developers can choose (by having a receiver of type `dynamic`) to perform member invocations that are not statically type safe, and only check at run time that the given member actually exists and that it accepts the given kind of invocation (e.g., that it accepts that many parameters, of those types, etc.).

The consequence, as @lrhn mentioned [here](https://github.com/dart-lang/sdk/issues/55620#issuecomment-2090294473) is that

>  extension methods do not work on `dynamic`.

You will simply _never_ be able to execute any extension methods when the static type of the receiver is `dynamic`.

It is true that `dynamic` is a subtype of `Object?` (and vice versa), but because of this special "it has all members" assumption it is not true that "it should be able to call an extension on `Object?`".

**Comment by eernstg** [comment]
> This is not documented behavior even.

If you want the gory details then check out the section 'The instantiation to bound algorithm' in [the language specification](https://spec.dart.dev/DartLangSpecDraft.pdf). The choice of `dynamic` when there is no bound is found at the end of the first paragraph in that section.

**Comment by eernstg** [comment]
> We had this code in our codebase and it was working fine until now.

Nothing has changed about the fact that raw type annotations use instantiation to bound, and instantiation to bound uses `dynamic` when no bound is declared for the corresponding type variable. I cannot see how it could be possible that a receiver of type `dynamic` has an extension member invoked on it, nor how `map[...]` could have any other type than `dynamic` when `map` has type `Map<dynamic, dynamic>`. So I really don't know how that could work, with _any_ version of Dart...

**Comment by lrhn** [comment]
Agree. This seems to be working exactly as intended (or at least as currently specified).
Until we get rid of the currently specified behavior, there is no bug, and the only surprising thing here is that it used to work.
