### ISSUE TITLE
Frontend type checking error with differing flow control

### ISSUE THREAD

**Issue by tdenniston** [dart-lang/sdk#55678]
The following two methods seem to me to be semantically equivalent, but one compiles and one fails to compile:

```dart
// This fails to compile with the error:
// A value of type 'Listenable' can't be returned from the function 'getListenableBug' because it has a return type of 'ValueListenable<T>'.
ValueListenable<T> getListenableBug<T>(HasA<T>? a, HasB<T> b) => a == null ? b.b : a.a;

// This compiles just fine.
ValueListenable<T> getListenableNoBug<T>(HasA<T>? a, HasB<T> b) {
  if (a == null) {
    return b.b;
  }
  return a.a;
}
```

Here is the full snippet, the bug should reproduce just by pasting this directly into [dartpad.dev](https://dartpad.dev) (Dart version 3.3.4 / Flutter 3.19.6):

```dart
import 'package:flutter/foundation.dart';

class A<S, T> with ChangeNotifier implements ValueListenable<T> {
  @override
  T get value => throw Error;
}

class B<T> with ChangeNotifier implements ValueListenable<T> {
  @override
  T get value => throw Error;
}

class HasA<T> {
  final a = A<int, T>();
}

class HasB<T> {
  final b = B<T>();
}

ValueListenable<T> getListenableBug<T>(HasA<T>? a, HasB<T> b) => a == null ? b.b : a.a;

ValueListenable<T> getListenableNoBug<T>(HasA<T>? a, HasB<T> b) {
  if (a == null) {
    return b.b;
  }
  return a.a;
}
```

**Comment by eernstg** [comment]
The function `getListenableBug` returns a conditional expression (`?:`) whose type is computed based on both branches. The function `getListenableNoBug` returns each of the two branches separately. This implies that they are non-equivalent because they are subject to different steps during type checking. With the stable release, this causes a type error.

However, we have just recently introduced an improvement in the computation of the type of conditional expressions, and this makes both versions of `getListenable` type correct. Choose the 'main' channel in DartPad and you'll see that there are no type errors.

This means that the issue will go away soon.

I'll close this issue because there's nothing to do, we just need to wait for the improvement to reach the stable release.

**Comment by tdenniston** [comment]
Ok - thank you for the explanation and quick response.
