### ISSUE TITLE
[Wildcard Variables] VS Code Support

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#55726]
This issue tracks the wildcard variables work needed for VS Code.
If no work needs to be done, feel free to close it.

cc @jwren

**Comment by DanTup** [comment]
I don't think there's any work for either VS Code of the textmate grammar, unless we perhaps want to color `_` differently to normal variables (for semantic tokens this would be done in the analysis servers highlights, but for the textmate grammar we don't currently colour variables at all because it's not a complete grammar).

cc @bwilkerson in case he can think of anything else I've overlooked.

**Comment by bwilkerson** [comment]
No, I can't think of anything. The grammar hasn't changed, so most other tooling ought to not be impacted.

> ... unless we perhaps want to color _ differently to normal variables ...

I don't think we're currently coloring wildcard patterns differently, and I would expect that we'd want to color all wildcards the same way.

**Comment by DanTup** [comment]
Makes sense, closing this as nothing to do then. Thanks!
