### ISSUE TITLE
Analysis server doesn't run macros correctly when they're provided through an "export"

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#55746]
Hello!

It appears that using `export 'macro.dart'` breaks the "Go to augmentation" codelenses.

You could define any macro:

```dart
// macro.dart
macro class Example {
...
}
```

Then re-export it in a different file:

```dart
// foo.dart
export 'macro.dart';
```

And finally import the macro through the export:

```dart
import 'foo.dart';

@Example()
// No "Go to augmentation" shows up here
class MyClass {}
```

cc @DanTup

**Comment by DanTup** [comment]
@rrousselGit are you sure the macro is running? While I can reproduce the CodeLens not appearing, it also seems like the macro is not running (because here, "hello" becomes an error):

https://github.com/dart-lang/sdk/assets/1078012/f099ae02-db25-42f0-bf91-55f1af9cf3e0

The behaviour I'm seeing doesn't seem like just a CodeLens issue, but I don't know if it's the same as what you're seeing.

**Comment by rrousselGit** [comment]
This is more than a codelense issue yes.

But if you run the code, it works:

You can `dart --enable-experiment macros lib/foo.dart` just fine. So the error is purely on the analyzer side

**Comment by DanTup** [comment]
Ah, gotcha. I've updated the title then - seems to be something wrong with the analysis server running the macro and not as I first suspected with the generation of LSP CodeLenses.

(cc @scheglov)

**Comment by scheglov** [comment]
I can reproduce it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/366901
