### ISSUE TITLE
`Thread 1 is not paused` error at the end of a web test 

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#55789]
In google3, we are adding support for debugging for web tests. This process opens a connection to DWDS. 

When the test terminates, we are getting a "Thread 1 is not paused" error (see screenshot below), which is being triggered in response to a `StackTrace` response: https://github.com/dart-lang/sdk/blob/5679c4d2370bde5ab5abc7375e65b83599091858/pkg/dds/lib/src/dap/adapters/dart.dart#L1861

I'm still trying to figure out why a `StackTrace` request is being sent here. This happens directly after the test runner completes with:

`+1: All tests passed! `

@DanTup Do we need to show the `Thread 1 is not paused` error to the user? I'm not familiar with the cases where this error would be expected, and would be helpful to the user.

![Screenshot 2024-05-20 at 12 30 19 PM](https://github.com/dart-lang/sdk/assets/21270878/ee14c080-6120-4c5a-8f1f-918d7c146f35)

**Comment by DanTup** [comment]
> I'm still trying to figure out why a StackTrace request is being sent here. 

Are you able to capture the protocol traffic? A wild guess - are the isolates pausing-on-exit which causes us to send a "Stopped" event to the client (which will cause it to ask for the stack trace), but then we're immediately resuming because we did everything we needed to?

> Do we need to show the Thread 1 is not paused error to the user?

I would not expect these kinds of errors to usually be shown to the user (because it's quite common for these kinds of races). Are you seeing this in VS Code/Dart-Code, or another editor?

In Dart-Code we have some middleware that intercepts errors and clears the `error.showUser` flag:

- https://github.com/Dart-Code/Dart-Code/commit/491fb0233022029cc268c8cb6c46f068a1c79381
- https://github.com/Dart-Code/Dart-Code/issues/4930

The `showUser` flag is not very well defined in the spec and VS Code seems to treat the flag not being set (`undefined`) differently in different places - see https://github.com/google/go-dap/issues/87#issuecomment-1887744046. DAP is currently setting it to `true` (see https://dart-review.googlesource.com/c/sdk/+/339741) which was an attempt to be consistent with the behaviour when the flag was not set explicitly, however I'm less sure now that `true` was the right default. Probably we should be setting it on a case-by-case basis, but without some clarification in the spec I don't know if we should keep changing it (hence just clearing it in the VS Code extension for now).

**Comment by elliette** [comment]
Thank you! That's good to know. This is Cider, so we aren't using the Dart-Code extension. Sounds like adding middleware to our extension is the right path forward here. FYI @helin24

**Comment by elliette** [comment]
Did a bit more investigation here, and it looks like the error is actually getting displayed in the second place called out in https://github.com/Dart-Code/Dart-Code/issues/4930#issuecomment-1885042498, so the middleware added in https://github.com/Dart-Code/Dart-Code/commit/491fb0233022029cc268c8cb6c46f068a1c79381 won't prevent it.

**Comment by DanTup** [comment]
> it looks like the error is actually getting displayed in the second place called out in https://github.com/Dart-Code/Dart-Code/issues/4930#issuecomment-1885042498, so the middleware added in https://github.com/Dart-Code/Dart-Code/commit/491fb0233022029cc268c8cb6c46f068a1c79381 won't prevent it.

The second link in that comment should be the one where it does work because it has the condition `showErrors && error && error.format && error.showUser`. It's the first link (which does `error.showUser !== false`) that doesn't.

If I understand the linked issues correctly, the one that defaults to true is for errors during launch, and everything else is the second one.

(that said, if it doesn't seem to work right, the middleware could equally set the flag to `false` explicitly.. though it might prevent launch errors showing up anywhere)

**Comment by elliette** [comment]
Oh got it! The middleware I added isn't intercepting the error (it doesn't seem to be intercepting anything) which is why it's not hiding the error. Need to do more investigation to figure out why.

**Comment by DanTup** [comment]
Are you copying the middleware used at https://github.com/Dart-Code/Dart-Code/commit/491fb0233022029cc268c8cb6c46f068a1c79381?

Does Cider support `registerDebugAdapterTrackerFactory`? And does the first argument you're passing to it match the type of the debugger (in my CL it's "dart" which is the same `"type"` registered as the debugger that would appear in `launch.json`, but I don't know if that's the same for you here).

**Comment by elliette** [comment]
> Are you copying the middleware used at [Dart-Code/Dart-Code@491fb02](https://github.com/Dart-Code/Dart-Code/commit/491fb0233022029cc268c8cb6c46f068a1c79381)?
> 
> Does Cider support `registerDebugAdapterTrackerFactory`? And does the first argument you're passing to it match the type of the debugger (in my CL it's "dart" which is the same `"type"` registered as the debugger that would appear in `launch.json`, but I don't know if that's the same for you here).

I am copying the middleware. I changed "dart" to "*" based on the docs: "The debug type for which the factory is registered or '*' for matching all debug types". I'm not sure if Cider supports `registerDebugAdapterTrackerFactory` so that could explain why it's not getting hit.
