### ISSUE TITLE
dart2wasm fails inside sync* functions with a switch statement

### ISSUE THREAD

**Issue by jthlim** [dart-lang/sdk#55839]
Using: Dart SDK version: 3.4.1 (stable) (Tue May 21 15:46:25 2024 +0000) on "macos_arm64"

Having a sync* function with a switch in it causes dart2wasm to fail:

`Not implemented: switch in sync* at <file location>`'

Changing the switch to a series of if/else avoids this issue.

Simple repro:

```
Iterable<int> test(int n) sync* {
  switch (n) {
    case 0:
    case 1:
      yield n;
  }
}

void main() {
  test(0);
}

```

flutter build web --wasm

Gives:
Not implemented: switch in sync* at file:///<path>/main.dart:9:3

**Comment by lrhn** [comment]
I believe this is a known missing feature: #51342

**Comment by mkustermann** [comment]
This has since been implemented. I believe this has also rolled up to flutter/flutter main channel.

The changes are somewhat big and `sync*` is a infrequently used feature, so I'm slightly hestitant whether we should cherry pick it. But if the changes cherry-pick cleanly without merge conflicts, I'd be inclined to pick them.

@osa1 Could you see if they cherry-pick cleanly on the stable branch? If so, follow https://github.com/dart-lang/sdk/blob/main/docs/Cherry-picks-to-a-release-channel.md to file a CP request.

**Comment by osa1** [comment]
@mkustermann we can't cherry pick just the `sync*` features, we need to cherry pick 8ccb41284ae2e1063fa9137b6225314284aa45d7 and maybe 350954ae9d26ae7b8055df0e18ee2e6875aede8d as well.

**Comment by mkustermann** [comment]
> @mkustermann we can't cherry pick just the sync* features, we need to cherry pick https://github.com/dart-lang/sdk/commit/8ccb41284ae2e1063fa9137b6225314284aa45d7 and maybe https://github.com/dart-lang/sdk/commit/350954ae9d26ae7b8055df0e18ee2e6875aede8d as well.

Yes. If all 3 on top of each other merge without conflicts, we may consider picking it.

**Comment by jthlim** [comment]
Appreciate the activity/urgency!

I'm happy to wait for stable. It switch to master to test the feature; rather than cause trouble with an out of band release/cherry pick

**Comment by osa1** [comment]
@mkustermann PTAL: https://github.com/dart-lang/sdk/issues/55847
