### ISSUE TITLE
[CP] dart2wasm async and sync* fixes to stable

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#55847]
### Commit(s) to merge

6de879e0f55, 7e237a12aa9, eabb2b3acaa, e44bc22ca3a, 350954ae9d2, 8ccb41284ae, e7dde8377ed, 3863e78e80d, 829261e2ba3, fab56db71b3

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/368300

### Issue Description

Users are currently missing a lot of `async` and `sync*` bug fixes, and unable to use exception handling (try/catch) or switch statements (when the statement has a `yield` in the body).

### What is the fix

Cherry pick the fixes and implementations.

### Why cherry-pick

Users are missing bug fixes and some of the `sync*` features are simply unimplemented in the latest release.

### Risk

Medium. While these changes include a lot of refactoring, no new features were added and a lot of bugs were fixed.

### Issue link(s)

#55347, #55457, #51343, #51342 and probably more. (some of the fix commits didn't link to issues)

**Comment by mkustermann** [comment]
LGTM

Since CI is green on this CP, I have no worries about it being risky. It CL looks big but
* it's mostly moving code from one place to another (i.e. includes a refactoring)
* fixes a number of issues (i.e. makes our stable branch more stable - which is it's purpose)
* it makes the code on stable branch closer to main, so any future CPs, will get easier to merge if need be (**)

(**) The alternative is to hand-craft a fix for stable channel, which could make the CL a bit smaller, but will cause diverging of the main & stable branches.

**Comment by osa1** [comment]
Cherry-pick merged as fbbb836a023556b9ea3786f499892d4f72539b4d.

**Comment by mkustermann** [comment]
I think the issue stays open until it was released on stable (see https://github.com/dart-lang/sdk/blob/main/docs/Cherry-picks-to-a-release-channel.md#submitting-the-cherry-pick)
