### ISSUE TITLE
fromEnvironment broken when compiling to javascript

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/sdk#55901]
`Dart SDK version: 3.5.0-177.0.dev (dev) (Tue May 21 09:05:26 2024 -0700) on "windows_x64"`

The following program crashes when compiled and run as javascript, but works fine when run on dart vm or compiled to exe.

```dart
void main() {
  print(String.fromEnvironment('HELLO', defaultValue: '...'));
}
```

```none
dart compile js --define=HELLO=WORLD bin/define.dart
```

```
VM62:409 Uncaught 
    at Object.wrapException (<anonymous>:384:43)
    at Object.throwUnsupportedError (<anonymous>:409:15)
    at main (<anonymous>:2320:9)
    at <anonymous>:2681:7
    at <anonymous>:2662:7
    at dartProgram (<anonymous>:2675:5)
    at <anonymous>:2684:3
```

It does work in javascript if you add a `const`.

```dart
void main() {
  print(const String.fromEnvironment('HELLO', defaultValue: '...'));
}
```

```none
dart compile js --define=HELLO=WORLD bin/define.dart
```

```
WORLD
```

**Comment by AkashKeote** [comment]
void main() {
  print(const String.fromEnvironment('HELLO', defaultValue: '...'));
}

**Comment by AkashKeote** [comment]
const keyword improve memory efficiency

**Comment by lrhn** [comment]
That's working as intended. 

The `String.fromEnvironment` constructor accesses the *compilation environment*. When compiled for the web, it must be used with `const` to get its value while compiling, because the compilation environment is not available at runtime. The VM JIT compiler can use `String.fromEnvironment` without `const` because it runs directly from source and has access to the compiler options.

From the documentation:
> This constructor is only guaranteed to work when invoked as `const`. It may work as a non-constant invocation on some platforms which have access to compiler options at run-time, but most ahead-of-time compiled platforms will not have this information.
