### ISSUE TITLE
The return type 'String' isn't a 'String', as required by the closure's context

### ISSUE THREAD

**Issue by Jordan-Nelson** [dart-lang/sdk#55958]
In the code below, the first assignment of `method` results in `The return type 'String' isn't a 'String', as required by the closure's context`. The next two work as expected. I would expect all three assignments to be valid.

```dart
void main() {
  String Function<T>(T data) method;

  method = <String>(String data) {
    return data; // Results in: The return type 'String' isn't a 'String', as required by the closure's context
  };
  
  method = <String>(String data) {
    return 'data'; // this works
  };
  
  method = <String>(String data) {
    return data.toString(); // this works
  };
}
```

**Comment by julemand101** [comment]
You got kinda fooled here since you thought `<String>`, in your example, was the type `String` and not a generic called `String`. I was rather confused for a second since this program ended up being valid:

```dart
void main() {
  String Function<T>(T data) method;

  method = <String>(String data) {
    return 'value: $data runtimeType: ${data.runtimeType}';
  };

  print(method(2)); // value: 2 runtimeType: int
}
```
But then, after closer inspection, you can replace it with `method = <X>(X data) {` and it starts to make more sense what is going on.

Don't know if there should be some kind of lint warning if you are using a named generic with the same name as a type since it can make it hard to understand what is going on.

**Comment by lrhn** [comment]
What @julemand101 says.
You have two types named `String`, one from `dart:core`, one a type variable from your own function. None of them are assignable to the other.
