### ISSUE TITLE
bug: FutureOr<FutureOr<Object>> does not resolve to FutureOr<Object>

### ISSUE THREAD

**Issue by Diaga** [dart-lang/sdk#55968]
As per: https://api.flutter.dev/flutter/dart-async/FutureOr-class.html
> As a corollary, `FutureOr<Object>` is equivalent to `FutureOr<FutureOr<Object>>`, `FutureOr<Future<Object>>` is equivalent to `Future<Object>`.

However, `FutureOr<FutureOr<Object>>` does not resolve to `FutureOr<Object>`. The following is a compile time error:
```dart
import 'dart:async';

FutureOr<FutureOr<int>> returnFutureOrNested() {
  return 1;
}

void main() {
   FutureOr<int> a = returnFutureOrNested();
}
```

Although, this still works:
```dart
import 'dart:async';

FutureOr<int> returnFutureOr() {
  return 1;
}

void main() {
  FutureOr<FutureOr<int>> a = returnFutureOr(); 
}
```

### Additional Info
The above is true for the current stable channel (Dart SDK 3.4.1) on dartpad.dev.

**Comment by mraleph** [comment]
Note that the comment is speaking specifically about `FutureOr<FutureOr<Object>>` not about `FutureOr<FutureOr<T>>` for arbitrary `T`. 

`FutureOr<FutureOr<int>>` is not equivalent to `FutureOr<int>`, because `Future<Future<int>>` belongs to (is a subtype of) `FutureOr<FutureOr<int>>`, but not to `FutureOr<int>`.
