### ISSUE TITLE
Failures on [vm/shared] Introduce 'vm:shared' pragma.

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#56016]
There are new test failures on [[vm/shared] Introduce 'vm:shared' pragma.](https://github.com/dart-lang/sdk/commit/4138277ee66743162902d406b0785f5eeaf6e297).

The tests
```
vm/dart/isolates/shared_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-appjit-linux-debug-x64
vm-appjit-linux-release-x64
```

**Comment by aam** [comment]
The culprit seems to be presence of `Pointer` value in the snapshotted object https://github.com/dart-lang/sdk/blob/627cd3047d2b52e23ba0cd3e31782c0f5ac97e85/runtime/tests/vm/dart/isolates/shared_test_body.dart#L80

@dcharkes is this something that should be working, do you know?

**Comment by dcharkes** [comment]
Pointers are not allowed to be in snapshots, due to the fact that when loading a snapshot it will be in a new process. So all pointers to memory regions or to symbols would be bogus.

The code should be written in a way such that all pointers are re-resolved when a snapshot is loaded. (E.g. `@Native`s for functions are reresolved.)

Having any `PosixMutex` objects available during appjit snapshotting is an error.

If we would have `PosixMutex` in the VM instead of user-defined, we could have custom serialization logic that snapshots the current mutex state, so that when deserializing we can allocate a mutex again and set it in the right state.

This is going to be an issue with any kind of native state being held on to from user-defined classes using FFI.

Maybe we should consider having some kind of user-defined serialization/deserialization for snapshotting Dart objects backed by native state where the native state cannot be reset when reading the snapshot.

Interestingly, our `dart:io` APIs such as `File` are structured in a way that state can be reset instead of reconstructed. E.g. a `File` is just a wrapper around a file path, and our API doesn't require a `File.open` - `File.readAsString` - `File.close` sequence, all those three calls are just `readAsString`. cc @brianquinlan You're prototype for `dart:io` as a package will likely run into the issue that you have `Pointer` objects as well when making an appjit snapshot.

For Dart objects backed by native state that must be reset on serialization/deserialization (such as `File` in a `package:io`), a custom serializer/deserializer would also do the trick.

**Comment by mkustermann** [comment]
@aam Our snapshots are snapshots of the application program/code, **not application state**. We never serialize the state of global fields into the snapshot (instead running from a snapshot gets fresh/uninitialized state of global fields). We should do the same for *shared* global fields.

The way this works is that the snapshot writing code (in `ProgramSerializationRoots`) puts the "uninitialized" value of all global fields (`isolate_group->initial_field_table_`) into the snapshot. Any newly created isolate will get a copy of those initial fields (which can e.g. be sentinel markers that field hasn't been initialized yet) on isolate creation.

@aam So I guess the issue here is that [cl/370064](https://dart-review.googlesource.com/c/sdk/+/370064) puts the **values** of global fields into the snapshot instead of their uninitialized (e.g. sentinel) values like we do with normal field table?

**Comment by aam** [comment]
> @aam So I guess the issue here is that [cl/370064](https://dart-review.googlesource.com/c/sdk/+/370064) puts the **values** of global fields into the snapshot instead of their uninitialized (e.g. sentinel) values like we do with normal field table?

Thanks Martin, yes, I think that's the culprit. I guess I have to keep separately and put into snapshot shared fields initial values, rather than their current values.
