### ISSUE TITLE
Optimize the ` dart:isolate ` API to use functional programming

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [dart-lang/sdk#56022]
Greetings, I wanted to continue now with the isolate API to use functional programming, now we must understand that the management of concurrency and the management of multiple threads of execution is fundamental to perform a lot of parallel computing in a simple way. To achieve this we are going to be inspired by the [java.util.concurrent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/package-summary.html) API. We are exactly interested in the [Executors](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html) class that allows us to create a Pool of threads.

In Dart the concept of thread is represented through what we call `Isolate`, if we talk in these terms, what we want is an `Isolate Pool` to implement this demo create the following

# The System class

The System class allows us to represent the processor of the hardware where our program is running, the idea is to have the ability to obtain information from our hardware to use it to parameterize our algorithm, the System class could be seen this way

```dart

abstract class ChipInformation {
//you code
}

final class CpuInformation extends ChipInformation {
//you code
}

final class GpuInformation extends ChipInformation {
//you code
}

final class IntegratedGpuInformation extends ChipInformation {
//you code
}

final class NpuInformation extends ChipInformation {
//you code
}

class System {
 static CpuInformation getCpu();
 static GpuInformation getGpu();
 static IntegratedGpuInformation getIntegratedGpu();
 static NpuInformation getNpu();
}

```
To call the System class we could represent it as follows:

```dart
void main() {
 CpuInformation info = System.getCpu();

 print(info.name); //print: Intel 14900k
 print(info.numberOfCore); //print: 24
 print(info.numberOfCorePerformance); //print: 8
 print(info.numberOfCoreEfficient); //print: 16
 print(info.cache); //print: 36 MB Intel® Smart Cache 
 print(info.numberOfCache); //print: 32
}
```

# The IsolatePoolExecutor class

The IsolatePoolExecutor class allows you to implement an Isolate Pool to execute multiple Isolates in parallel in an efficient and standard way. To understand what this concept would be, we will see an example

```dart
import "dart:function";
import "dart:isolate";

class Example implements Callable<int> {
  int _count;
  Example(this._count);

  @override
  int run() {
    int sum = 0;
    final random = new Random();
    for (int i = 0; i < _count; i++) {
      sum += random.nextInt(10000);
    }
    return sum;
  }

}

Callable<int> fn = () {
  int sum = 0;
  final random = new Random();
  for (int i = 0; i < _count; i++) {
    sum += random.nextInt(10000);
  }
  return sum;
};

void main() {
 late pool1;

 if (System.isGpuAvailable) {
   final GpuInformation info = System.getGpu();

   pool1 = IsolatePoolExecutor.newGpuIsolatePool(info.numberOfCore);
 } else {
   final CpuInformation info = System.getCpu();

   pool1 = IsolatePoolExecutor.newFixedIsolatePool(info.numberOfCorePerformance, onlyPerformance: true);
 }

 final result = await pool1.compute(Example(10), 100000000);

 print(result);

 final result2 = await pool1.compute(() => fn(10), 100000000);

 print(result2);
}
```
The `dart:isolate` API will be able to provide some interfaces so that developers can implement their own version of an Isolate Pool, an existing library for this is [isolate_pool_executor](https://pub.dev/packages/isolate_pool_executor), the creators will be able to implement in the future the new interfaces provided to standardize some APIs.

More information [here](https://www.baeldung.com/thread-pool-java-and-guava)

**Comment by julemand101** [comment]
> The System class

I don't see the need for many of those properties and if a project need this information, it is going to have such specific needs that it is better that the application fetches the information itself using native API's. E.g. this is nonsense for most projects:

```dart
print(info.cache); //print: 36 MB Intel® Smart Cache 
```

Having `cache` to output a String which you then need to manually parse is not developer friendly. It also question what should be considered "cache" since some CPU's have a very complicated relationship what is cache and what is memory.

We need then some platform specific way to get this information but in such way it is also the same across OS'es. That does not sound like something worth doing compared to how few programs needs this kind of information.

> The IsolatePoolExecutor class

Should be implemented in a package which have already been done multiple times. There are many ways to do this kind of implementation and it depends on the project which are best fitting. Therefore, it is not something that should be in the Dart SDK. I don't see much value of making a standard way of pooling jobs since it would always be rather project specific.

I think you are looking a bit too much into how Java does things and have the opinion that Dart SDK should contain the same amount/types of features as Java's JDK. Instead, I think JDK contains too much and are rather noisy in containing stuff that is actually not needed to be in JDK but could easily be in dependencies. Therefore I don't think it is best for the Dart SDK to get as filled with stuff that could easily be packages.

**Comment by Ing-Brayan-Martinez** [comment]
@julemand101 Honestly, I am not going to take your opinion into account, because you are a "Hater", you are only criticizing my proposals without any basis, behaving like a 13-year-old teenager, that is unprofessional behavior.

You reflect an irrational hatred for languages ​​like Java or C# which seems stupid to me, my proposals being inspired by the JDK, you are trying to prevent them from being approved due to your irrational hatred, you explicitly demonstrated your hatred in the official Discord

For you it is more important to obstruct my proposals than to contribute positively to the platform, all my proposals are founded and tested by the industry, every Senior programmer who uses reactive and functional programming will appreciate this news

If you on a personal level do not like these new features, do not use them, that does not mean that they should not exist, because on a personal level you do not like them, in your case you can use the usual Object Oriented programming and the world will continue. Going forward, the Dart language must satisfy all paradigms and it will depend on the programmers which paradigm to use.

Stop putting your personal desires above the interests of the platform. The Dart language is an open platform used by thousands of people and companies and must satisfy all needs.

**Comment by julemand101** [comment]
@Ing-Brayan-Martinez Please read: https://dart.dev/community/code-of-conduct

If you have any issue with my behavior here, then report it to the E-Mail on that page instead of making such comments.

> you explicitly demonstrated your hatred in the official Discord

The FlutterDev Discord server are not the official Flutter (or Dart) Discord but are fully community driven. If you have a problem with my behavior in that server, please get in contact with the moderators / administrators on that server.
