### ISSUE TITLE
Contradictory behavior from `body_might_complete_normally`

### ISSUE THREAD

**Issue by nate-thegrate** [dart-lang/sdk#56067]
**Describe the issue**
the following snippet triggers [`body_might_complete_normally`](https://dart.dev/diagnostics/body_might_complete_normally):
```dart
int add(int? a, int? b) {
  switch ((a, b)) {
    case (_, null): return a!;
    case (null, _): return b!;
    case (final int a, final int b): return a + b;
  }
}
```

What's really funny is that adding another case to the bottom will trigger the [`unreachable_switch_case`](https://dart.dev/diagnostics/unreachable_switch_case) lint as expected.

<details open> <summary><b>Demo</b> (click to collapse)</summary>

![linter bug](https://github.com/dart-lang/linter/assets/10457200/5cff5e49-3c61-4925-a7e3-32fbf2df223f)

</details>

**Comment by nate-thegrate** [comment]
It could have something to do with how records are analyzed, since having just 1 parameter works fine:

```dart
// no linter issues!
int increment(int? a) {
  switch (a) {
    case null: return 0;
    case final int a: return a + 1;
  }
}
```

**Comment by eernstg** [comment]
This is a known issue. A similar situation was discussed in https://github.com/dart-lang/language/issues/2977.

Every switch _expression_ is subject to exhaustiveness checking, and the exhaustiveness analysis _does_ recognize this case, so the following version of the code is accepted:

```dart
int add(int? a, int? b) => switch ((a, b)) {
      (_, null) => a!,
      (null, _) => b!,
      (final int a, final int b) => a + b
    };
```

However, exhaustiveness analysis is different from the flow analysis which is also performed, and the exhaustiveness analysis is stronger in some instances. So the declaration is accepted because it is subject to both kinds of analysis.

A switch _statement_ is different: It is only subject to exhaustiveness analysis in the case where the static type of the scrutinee is an ['always-exhaustive type'](https://github.com/dart-lang/language/blob/main/accepted/3.0/patterns/feature-specification.md#exhaustiveness-and-reachability), and that doesn't include the record type `(int?, int?)`, because it doesn't include `int?`.

This means that the switch statement is subject to flow analysis (that one is always enabled), but not to exhaustiveness analysis. And the flow analysis isn't smart enough to detect that this particular switch statement is exhaustive.

The issue https://github.com/dart-lang/language/issues/2977 explicitly mentions this catch-22: If the `default` case is included then it is flagged as unreachable, but if it is omitted then the switch statement isn't recognized as being exhaustive.

There is no beautiful solution, but you might use something like the following:

```dart
int add(int? a, int? b) {
  switch ((a, b)) {
    case (_, null): return a!;
    case (null, _): return b!;
    case (final int a, final int b): return a + b;
  }
  // Flow analysis cannot see that the switch is exhaustive.
  throw "Unreachable";
}
```

**Comment by nate-thegrate** [comment]
Thank you @eernstg!

I think it makes sense to close this one as a duplicate of https://github.com/dart-lang/language/issues/2977.
