### ISSUE TITLE
[dart:js_interop] Add JSArray.from static method.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#56069]
[Array.from (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from).

**Comment by srujzs** [comment]
It depends. :)

Creating an array using `Array.from` will be faster than iterating the original object and placing in each value in a Dart list. `toDart` should also be quite fast since it's either a cast or a wrap operation.

On the other hand, accesses on the `toDart`'d array may be slower than accesses on the Dart list you created. When compiling to JS, they will likely be the same performance, but when compiling to Wasm, you'll need to use interop for every access, so it'll be slower.
