### ISSUE TITLE
Dart analyzer does not infer the correct type for generic record 

### ISSUE THREAD

**Issue by paulmwk** [dart-lang/sdk#56094]
```dart
import 'dart:math';

typedef Setter<T extends num> = void Function(T value);
typedef Getter<T extends num> = T Function();

typedef TestRecord<T extends num> = ({Setter<T> set, Getter<T> get});

class TestClass<T extends num> {
  Setter<T> set = (T value) {};

  Getter<T> get = () => 0 as T;
}

TestRecord<T> getRecord<T extends num>(Type t) {
  return (set: (T value) {}, get: () => 0 as T);
}

TestClass<T> getClass<T extends num>(Type t) {
  return TestClass<T>();
}

void main() {
  final rng = Random();
  TestRecord<int> testRecord = getRecord<int>(int);
  TestRecord<double> testRecord2 = getRecord<double>(double);
  final res = rng.nextDouble() > 0.5 ? testRecord : testRecord2;
  res.set(res.get());

  TestClass<int> testClass = getClass<int>(int);
  TestClass<double> testClass2 = getClass<double>(double);
  final res2 = rng.nextDouble() > 0.5 ? testClass : testClass2;
  res2.set(res2.get());
}

```

The type of res.set is `void Function(Never)` instead of `void Function(num)`

**Comment by mraleph** [comment]
Functions are _contravariant_ with respect to their parameter types. `void Function(int)` it *not* a subtype of `void Function(num)`. Consider Liskov's substitution principle: can a `void Function(int)` be used where `void Function(num)` is expected? The answer to this question is **no**: you can't invoke `void Function(int)` with `double` value as an argument, but you can invoke `void Function(num)` with a `double` value as an argument. 

On the other hand `void Function(int)` and `void Function(double)` are both subtypes of `void Function(Never)` - because they can be used anywhere where an instance of `void Function(Never)` is expected.
