### ISSUE TITLE
introduce SortedMap interface that SplayTreeMap implements?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#5611]
It would be really nice to have &quot;SortedSet&quot; and &quot;SortedMap&quot;. SplayTreeMap works great, but the name contains implementation details. It we decide at some time down the road that we want to implement it with some other kind of binary search tree, it won't be very good.

Also as a user, I find myself frequently adding comments like &quot;using SplayTreeMap to keep this sorted so we iterate in a stable order&quot;. Whereas &quot;SortedMap&quot; would be a self documenting name.

**Comment by jmesserly** [comment]
updated subject based on https://github.com/dart-lang/sdk/issues/5611#issuecomment-108333802 ... since renaming it won't happen at this point :)

**Comment by andreilg** [comment]
I feel that introducing `OrderedMap`, `SortedMap`, `OrderedSet`, and `SortedSet` would benefit the language since they allow developers to be more expressive with their code by using abstract data types as opposed to using data structures like `SplayTreeMap` to express the usage of a Sorted Map, or even worse, using `Map` as a catch-all.

Also, this would allow `Map` and `Set` to use `HashMap` and `Hashset` data structures, respectively, by default instead of their current default `LinkedHashMap` and `LinkedHashSet` implementations which are less efficient and unnecessarily ordered (since a Map is an unordered abstract data type).
