### ISSUE TITLE
Regex with unicode and curly braces does not match correctly

### ISSUE THREAD

**Issue by ernestrlee** [dart-lang/sdk#56235]
Steps to reproduce
Run the following code:
String clearBullets(String s) => s.replaceAll(RegExp(r"[\u{2022}\u2023\u25E6\u2043\u2218\u2219▢]"), "");
print(clearBullets("multiple •‣◦⁃∘∙▢ again •‣◦⁃∘∙▢"));

Note the curly braces around 2022.

Expected results
According to some documentation, it should not matter if curly braces are used or not.

Actual results
output is: "mltiple • again •" For some reason the letter "u" is removed.

Code sample
Code sample
String clearBullets(String s) => s.replaceAll(RegExp(r"[\u{2022}\u2023\u25E6\u2043\u2218\u2219▢]"), "");
print(clearBullets("multiple •‣◦⁃∘∙▢ again •‣◦⁃∘∙▢"));

**Comment by lrhn** [comment]
This is working as intended. 

The `r` in front of the string literal means that it's a raw string, so `\` is not interpreted as a Dart string escape.
Instead it's passed to the `RegExp` parser. The `RegExp` grammar allows `\u2200` as a Unicode code point escape, but it does not allow `\u{2200}`, so that's interpreted as a just `u{2200}` inside a character class.
