### ISSUE TITLE
bug: Dart does not narrow the type properly across more than one level of inheritance in a collection type

### ISSUE THREAD

**Issue by Diaga** [dart-lang/sdk#56253]
Dart does not narrow the type properly across more than one level of inheritance in a collection type. Consider the following:
```dart
class Base<T> {}

class Child<T> extends Base<T> {}

class GrandChild<T> extends Child<T> {}

class Test<T> {
  final List<Base<T>> list;
  
  Test(this.list);
}

void main() {
  final firstTest = Test([Child<String>(), Child<bool>()]); // No error
  
  final secondTest = Test([Child<String>(), GrandChild<bool>()]); // Errors


  // Other observations
  final thirdTest = Test(<Base<dynamic>>[Child<String>(), GrandChild<bool>()]); // No error

  final fourthTest = Test([Child<String>(), GrandChild<String>()]); // No error
}
```

- There is no error for `firstTest` class instantiation. The argument narrows successfully.
- Dart is not able to narrow type to `List<Base<dynamic>>` for `secondTest` but instead errors with the message:
```
The argument type 'List<Object>' can't be assigned to the parameter type 'List<Base<dynamic>>'. 
```

Environment:
- The above error exists on current main (Dart SDK 3.5.0-315.0.dev) and stable (Dart SDK 3.4.3) channels of dartpad.

Expected Behaviour:
- There should be no error for `secondTest` and dart should narrow the type to `Base<dynamic>`.

**Comment by eernstg** [comment]
If you encounter this issue then the best workaround is probably to provide a minimal amount of type information somewhere in the affected expression. For example, `Test<Object>([Child<String>(), GrandChild<bool>()])` would suffice in this case: That's enough to turn the list into a `List<Base<Object>>`, and such a list can contain a `Child<String>` and a `GrandChild<bool>` just fine.

This is inconvenient, but in a language with subtyping it is a fact of life that type inference isn't complete, so there will always be situations where some type arguments must be specified explicitly.

I'll close the issue because all the behaviors discussed here are well known, and discussions about improvements are already in the language repository at https://github.com/dart-lang/language/blob/main/resources/type-system/upper-lower-bounds.md#upper-bounds.

**Comment by eernstg** [comment]
PS: @Diaga, the label 'area-language' is deprecated, please create an issue in the [language repository](https://github.com/dart-lang/language/issues) if you wish to report something about the language as such.
