### ISSUE TITLE
Nullable `VoidCallback` call function can't see nullable return

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56257]
Take the following function:

```dart
void fn2(String Function()? fn) {
  final a = fn?.call() ?? '';
}
```

It works just fine as you would expect. Now, if the return type of the `Function` is a `void`, we encounter some weird behaviour with `??` operator.

```dart
typedef VoidCallback = void Function();
typedef ValueChanged<T> = void Function(T value);

void fn(VoidCallback? callback1, ValueChanged<String>? callback2) {
  return callback1?.call() ?? callback2?.call('');
}
```

The first `call` method on `callback1` reports the following:

```
This expression has a type of 'void' so its value can't be used.
Try checking to see if you're using the correct API; there might be a function or call that returns void you didn't expect. Also check type parameters and variables which might also be void.dart[use_of_void_result](https://dart.dev/diagnostics/use_of_void_result)
```

To solve this I had to test if the function wasn't null first, then call it and else call the second one.

**Comment by lrhn** [comment]
Definitely working as intended. Don't check what value a `void` function returns, even if the actual value is that value or `null`.

Here you are calling `callback1?.call()` which has type `void?`, aka `void`.

It's also unlikely to work as intended, even if allowed, because a `void`-returning function most likely returns the `null` value,
so `voidFunction?.call() ?? alternative()` would end up calling `alternative` whether `voidFunction` was `null` or not.
You'll have the same problem with any nullable return type:
```dart
void foo(String? Function()? f1, String? Function() f2) {
  var v = f1?.call() ?? f2();
}
```
This will call `f2` even if `f1` is *not* `null`, but it returns `null`.
