### ISSUE TITLE
bug: dart analyzer does not catch the error `FutureOr<Object>? Function()' can't be assigned to the parameter type 'FutureOr<Object> Function()`

### ISSUE THREAD

**Issue by Diaga** [dart-lang/sdk#56256]
Consider the following code:
```dart
import 'dart:async';

FutureOr<bool> returnFutureOrBool() {
  return true;
}

class Test {
  void then<T2>(FutureOr<T2> Function() fn) {
  }
}

void main() {  
  Test().then(() {
    final futureOrBool = returnFutureOrBool();
    if (futureOrBool is Future) {
      return futureOrBool;
    }
    
     return null;
  });  
}
```

There is no error by the analyzer, however, on running the code, there is an error:
```dart
compileDDC
main.dart:13:15: Error: The argument type 'FutureOr<bool>? Function()' can't be assigned to the parameter type 'FutureOr<bool> Function()' because 'FutureOr<bool>?' is nullable and 'FutureOr<bool>' isn't.
  Test().then(() {
              ^
```

Environment:
The above error exists on current main (Dart SDK 3.5.0-315.0.dev) and stable (Dart SDK 3.4.3) channels of dartpad.

Expected behaviour:
The analyzer should be consistent with the compiler at least. Not sure if the error is as intended.

**Comment by eernstg** [comment]
Good catch! The analyzer and the common front end should not disagree on the inferred types here.

However, if a tool infers the actual type argument `FutureOr<bool>?` for the invocation of `then` then an actual argument of type `FutureOr<bool>? Function()` is perfectly fine.

So we'd need to consider both (1) what is the inferred type of the function literal which is given as an argument to `then`? .. and (2) what's the inferred type argument which is passed to `then`?

The type of the function literal is pretty much evident because it takes no arguments and returns an expression of type `FutureOr<bool>` as well as an expression of type `Null`. So there's basically no way a tool could assign any other type than `FutureOr<bool>? Function()` to that function literal.

**Comment by chloestefantsova** [comment]
It is a known discrepancy in the behavior between the CFE and the Analyzer. More can be found [here](https://github.com/dart-lang/sdk/issues/55344) and [here](https://github.com/dart-lang/sdk/issues/51156#issuecomment-2158825417). We even have a [flag](https://github.com/dart-lang/sdk/blob/bb59b5c72c52369e1b0d21940008c4be7e6d43b3/pkg/_fe_analyzer_shared/lib/src/type_inference/type_analyzer_operations.dart#L1076) to enable or disable the discrepant behavior to be less breaking until we decide which way we want to go.

I'm closing this one as a duplicate, but it's good to have another report on the issue.
