### ISSUE TITLE
Poor error message for ambiguous_extension_member_access when two extensions exist with the same name.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#56269]
**Describe the issue**
In my local project I have an extension:

```dart
extension StringAsProcess on String {
  /// run
  Future<void> get run async {
    await HalfPipe().commandAndArgs(this).print();
  }
```
My project also imports the dcli project which has a similar extension
```dart
extension StringAsProcess on String {
  void get run {
    cmd.start(
      this,
      terminal: true,
      progress: Progress(print, stderr: printerr),
    );
  }
```

When I tried to use the 'run' method in a unit test:
```dart
import 'package:dcli/dcli.dart' as dcli;
import '../../../lib/src/shorthand.dart';
import 'package:test/test.dart';

void main() {
  test('stderr stream ...', () async {
    'dart /path/to/exc -e 10'.run;
  });
}

```

The linter reported the error:
```
ambiguous_extension_member_access
 "A member named 'run' is defined in extension 'StringAsProcess' and extension 'StringAsProcess', and none are more specific.\nTry using an extension override to specify the extension you want to be chosen.",
```

**Expected behavior**
The linter should provide details on what library each of the extensions was included from.

```
 "A member named 'run' is defined in extension 'StringAsProcess' from package dcli/src/string_as_process.dart and local extension 'StringAsProcess'  from lib/src/shorthand.dart, and none are more specific.\nTry using an extension override to specify the extension you want to be chosen.",
```

**additional context**
This error was particularly confusing as I had forgotten about the packages local extension and when I aliased the dcli import (as dcli) I expect that to remove the error but I guess extensions bypass the alias?

**Comment by FMorschel** [comment]
About extension bypassing aliases, you're right and today there is an error using the expression evaluation: https://github.com/dart-lang/sdk/issues/56555

**Comment by Vinay-Khanagavi** [comment]
I'd like to work on improving the error message for ambiguous extension member access, as described in this issue. 

_Proposed Enhancement:_

When the analyzer encounters multiple extensions with the same member name, the error message should clearly indicate:

1. Full extension names: Including the package or file path where each extension is defined. 
2. Type being extended:  Reaffirm the type the extensions are applied to (e.g., `String` in this case).

_Example:_

Instead of: 
> "A member named 'run' is defined in extension 'StringAsProcess' and extension 'StringAsProcess', and none are more specific."

The error could be:
> "A member named 'run' is defined in extension 'package:dcli/src/string_as_process.dart'.StringAsProcess and extension 'lib/src/shorthand.dart'.StringAsProcess (both extending 'String'), and none are more specific."

_Benefits_:

Faster Debugging: Developers can immediately identify the conflicting extensions without manually searching through imports.
Clearer Context: The error message explicitly shows that the conflict arises from extensions operating on the same type.

I'm happy to submit a pull request with this improvement if the approach aligns with the project's goals. Please advise on the preferred implementation details.

**Comment by srawlins** [comment]
Sorry @Vinay-Khanagavi I only just saw your comment after I landed mine! ☹️  Didn't mean to step on toes.

We have [over 150 open issues with the label "analyzer-ux"](https://github.com/dart-lang/sdk/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-analyzer+label%3Aanalyzer-ux) which are "user experience" issues, which might be similar to this one. I've found there are often low-hanging fruit in there.

**Comment by Vinay-Khanagavi** [comment]
@srawlins  No worries at all! 😊 Thanks for letting me know. I’ll definitely check out the "analyzer-ux" label and explore those user experience issues. 

Thanks for the tip!
