### ISSUE TITLE
Isolate.run error run with closure

### ISSUE THREAD

**Issue by hgraceb** [dart-lang/sdk#56295]
- Dart 3.1.5 and 3.6.0-36.0.dev
- Windows

The program receives an error when run with `Isolate.run`. However, converting the map to a list was a success. I guess it was caused by closure's over-capturing but I don't know how to resolve it in most normal cases excluding calls by `toList`.

```dart
import 'dart:async';
import 'dart:isolate';

class VM {
  final completer = Completer();

  dynamic execute(parameter) {
    return parameter;
  }

  dynamic delegate() {
    return ([$0]) {
      return execute($0);
    };
  }

  dynamic interpret() {
    return Function.apply(['element'].map, [delegate()]);
  }
}

void main() async {
  try {
    await Isolate.run(() => VM().interpret());
  } catch (e) {
    print(e); // is unsendable object: Instance of '_AsyncCompleter<dynamic>'
  }
  print(await Isolate.run(() => VM().interpret().toList())); // ['element']
}
```

```
Invalid argument:  <- Instance of 'VM'
 <- Context num_variables: 1
 <- Closure: ([dynamic]) => dynamic (from dart:core)
 <- Instance of 'MappedListIterable<String, dynamic>' (from dart:_internal)
 <- _List len:1 (from dart:core)
is unsendable object (see restrictions listed at`SendPort.send()` documentation for more information): Instance of '_AsyncCompleter<dynamic>'

[element]
```

**Comment by a-siva** [comment]
//cc @aam

**Comment by lrhn** [comment]
Does look like expected behavior.
You can't send a `VM` instance to another isolate because it contains a `Completer`, and therefore a `Future`.
The `VM` instance causing the error is in the returned value.

The value you return in the first example is an iterable which is basically `['element'].map(([$0]) => vm.execute($0))` for some `VM` instance `vm`. That does contain the `VM` object, because otherwise it wouldn't be able to call `execute` on it when the iterable is iterated.

Calling `.toList()` on the iterable converts it, eagerly, to a list which doesn't need to keep a closure around.

**Comment by hgraceb** [comment]
Got it, thanks.
