### ISSUE TITLE
`String.fromCharCode[s]` should be deprecated and renamed to `String.fromRune[s]`

### ISSUE THREAD

**Issue by robertbastian** [dart-lang/sdk#56304]
[`String.fromCharCode`](https://api.dart.dev/stable/3.4.4/dart-core/String/String.fromCharCode.html) operates on an input which in the Unicode specification is called a ["code point"](https://www.unicode.org/glossary/#code_point)[^1]. The term "char code" or "character code" doesn't appear in Unicode.

What makes this worse, is that Dart *already has another name* for Unicode code points: "rune", as in [`String.runes`](https://api.dart.dev/stable/3.4.4/dart-core/String/runes.html), and the [`Runes`](https://api.dart.dev/stable/3.4.4/dart-core/Runes-class.html) class. While "rune" is not used by the Unicode spec, it is also the name for Unicode code points in Go, .Net, and Zig afaict.

The current documentation also doesn't really define what it means by "char code", just [saying it's a "rune"](https://api.dart.dev/stable/3.4.4/dart-core/String/String.fromCharCodes.html#:~:text=The%20charCodes%20can%20be%20both%20UTF%2D16%20code%20units%20and%20runes). The [`String.runes`](https://api.dart.dev/stable/3.4.4/dart-core/String/runes.html) and [`Runes`](https://api.dart.dev/stable/3.4.4/dart-core/Runes-class.html) documentation is much better, explicitly saying they operate on Unicode code points.

[^1]: The fact that it accepts both code points and UTF-16 code units is irrelevant, as every UTF-16 code unit (0x0000-0xFFFF) represents the Unicode code point of the same value under Dart's unpaired-surrogates-are-fine encoding.

**Comment by lrhn** [comment]
This change is not going to happen for a number of reasons.
Primarily, it's won't bring any benefit. The `fromCharCode`/`fromCharCodes` constructors are used *vastly* more than the `runes` getter, so if we were to rename anything, it's the `runes` getter which should be renamed `CodePoints`, since that would affect fewer people. (And not introduce a new name for code point, with no benefit. It makes sense in Go to have `Runes` because it's an actual type there. In Dart, it's just a name for an `int` which is a code point.)

The `String.fromCharCode` constructor's name matches `String.fromCharCodes`, and should keep doing that.
Changing the latter to `fromRunes` is not precise, since the values accepted by `fromCharCodes` is intended to be both code units and code points. Even renaming it to `fromCodePoints` would be misleading, because it's *intended* to accept code units as input. That's why it's called "char codes", to encompass both code units and code points, as opposed to fx `.codeUnitAt`, which is precise about what it gives.


If anything,

**Comment by robertbastian** [comment]
> Primarily, it's won't bring any benefit.

Debatable. Char code is not a term that the average programmer is familiar with (i.e. from JavaScript, Java, or other languages), and coupled with the sparse documentation it's really not a very ergonomic method.

> The String.fromCharCode constructor's name matches String.fromCharCodes, and should keep doing that.

I wrote `String.fromCharCode[s]` in the issue title to refer to both `String.fromCharCode` and `String.fromCharCodes`. I'm not proposing renaming one but not the other.

> Changing the latter to fromRunes is not precise, since the values accepted by fromCharCodes is intended to be both code units and code points.

Well, with a single `int` type and strings that allow unpaired surrogates, this distinction doesn't really exist in Dart, every UTF-16 code unit is a code point as well.

**Comment by lrhn** [comment]
I admit that the distinction between code points and UTF-16 code units is mostly philosophical. All the UTF-16 code units are also code points, but not all are scalar values. 
The method names actually come from a time when Dart strings could not be created from unpaired surrogates, so the "char codes" were *either* valid UTF-16 *or* scalar values, and "runes" were intended to be scalar values only. That changed when the overhead of having a string type that was different from JavaScript strings became too big.

I'd be willing to consider renaming `Runes`, because it's a word that is *not* used anywhere else. In `dart:convert`, they're called code points. In `package:characters` they're also called code points. The name "Runes" just didn't catch on. The `String.runes` getter isn't being used much, if at all (which is understandable, because code points is not a better abstraction level than code units for actually *working* with strings, for that you want grapheme clusters anyway).

I see no benefit gained from changing `String.fromCharCode[s]`, *especially* not to `fromRunes`.
To `fromCodePoints`, but the benefit is minuscule, and it might confuse people to think they *can't* use `String.fromCharCodes(otherString.codeUnits)`.
