### ISSUE TITLE
Maybe ZoneSpecification's fork behavior is broken?

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/sdk#56323]
On the last version of Dart I can't accomplish the task of overriding a ZoneSpecification's fork without getting StackOverflows...  
I also found no example and just one test that doesn't work with runZoned().

Maybe @lrhn can give me some help?

StackOverflow question: [https://stackoverflow.com/questions/78796566/how-to-properly-implement-a-zonespecificationfork-handler-in-dart](https://stackoverflow.com/questions/78796566/how-to-properly-implement-a-zonespecificationfork-handler-in-dart)

**Comment by lrhn** [comment]
You should call `parent.fork`, not `zone.fork`, to access the parent zone's implementation, which will eventually reach the root zone. 

Calling `zone.fork` is exactly calling the same fork that triggered this callback again, so the stack overflow is expected. 

This is not new behavior, it's been like this since the start.

**Comment by Rodsevich** [comment]
LOL I was drowning in a glass of water like we say in Arg 😅

Thank you so much, Lasse
