### ISSUE TITLE
Issue with Uri.encodeComponent not encoding correctly.

### ISSUE THREAD

**Issue by AnkitKh095** [dart-lang/sdk#56339]
I am encountering an issue with the Uri.encodeComponent method in Dart when encoding filenames containing parentheses. The method does not encode parentheses as expected, leading to issues when using these encoded filenames in requests to Amazon S3.

String fileName = 'doc (1).doc';
String encodedFileName = Uri.encodeComponent(fileName);
print('Encoded Filename: $encodedFileName');

The expected output should be doc%20%281%29.doc, but the actual output is doc%20(1).doc.

**Comment by lrhn** [comment]
This is working as intended. Parentheses are allowed unescaped in all URI components where escapes are allowed in [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A). There is no *need* to escape them in order to be a valid URI.

If the decoder is not allowing parentheses, then it's using a different URI format, or the escaped text is not used as part of a URI.
