### ISSUE TITLE
[Augmentations] Analyzer error when augmenting representation variable

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#56341]
It is an error in the analyzer to augment extension type representation variable with a variable.
```dart
extension type ET(int v) {}

augment extension type ET(int v) {
  augment final int v = 42; // COMPILE_TIME_ERROR.EXTENSION_TYPE_DECLARES_INSTANCE_FIELD
}
```
I didn't find in the [spec](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md) any statement that makes augmenting of the representation variable an error. So, I guess, it is allowed and there should be no such error.

See, for example, https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Augmentation-libraries/augmenting_getters_setters_with_variable_A02_t01.dart

@jakemac53 @munificent to confirm.

**Comment by jakemac53** [comment]
These are not variables, they are the representation type, which is a different thing (even though they look like variables somewhat). This definitely should be an error (I have no idea what it would mean otherwise).

Similarly I think you should not be allowed to augment it with a getter (or setter, but there is no setter).
