### ISSUE TITLE
The native compiler doesn't infer some extension type expressions correctly

### ISSUE THREAD

**Issue by LongCatIsLooong** [dart-lang/sdk#56351]
The following code (**no analyzer warnings**) works fine in dartpad but does not compile using the native compiler. :

```dart
RBTree create(bool red) => red ? RedNode(RBTree()) : BlackNode(RBTree());

class RBTree {}

extension type _UnsafeNode(RBTree node) { }
extension type RedNode(RBTree node) implements _UnsafeNode, RBTree {}
extension type BlackNode(RBTree node) implements _UnsafeNode, RBTree {}
```
 
Error message:
```
lib/main.dart:14:32: Error: A value of type '_UnsafeNode' can't be returned from a function with return type 'RBTree'.
- 'RBTree' is from 'package:p1/main.dart' ('lib/main.dart').
RBTree create(bool red) => red ? RedNode(RBTree()) : BlackNode(RBTree());
                               ^
Target kernel_snapshot_program failed: Exception
```

workaround:
```dart
// If I cast the expression, the code compiles but the analyzer doesn't like it (`unnecessary_cast`).
RBTree create(bool red) => (red ? RedNode(RBTree()) : BlackNode(RBTree())) as RBTree;

// This works.
RBTree create(bool red) {
  final RBTree x = RedNode(RBTree());
  final RBTree y = BlackNode(RBTree());
  return red ? x : y;
}
```
Everything seems to work correctly if I change those extension types into regular classes.

`dart info` output:

#### General info

- Dart 3.6.0-83.0.dev (dev) (Thu Jul 25 13:05:40 2024 -0700) on "linux_x64"
- locale is en_US.UTF-8

#### Project info

- sdk constraint: '>=3.3.0-0 <4.0.0'
- dependencies: flutter

**Comment by mkustermann** [comment]
Doesn't look like a VM issue, removing `area-vm`. It may rather be a difference in type inference.

/cc @chloestefantsova Is it analyzer or CFE issue?

**Comment by chloestefantsova** [comment]
I can't reproduce it at the current tip of the main branch.

**Comment by LongCatIsLooong** [comment]
The problem appears to have to do with my flutter installation. The code compiles in dart just file, but it refuses to compile using flutter even after nuking all the build artifacts.

**Comment by eernstg** [comment]
Hi @LongCatIsLooong, I'd like to comment on the code as such, even though we know that no bugs were detected. So this is a bit of advice about how to use extension types.

Here is the code again, with a couple of renames just so we don't have name clashes, and with a `main` such that we can experiment with the code in DartPad and such:

```dart
RBTree create(bool red) => red ? RedNode(RBTree()) : BlackNode(RBTree());

class RBTree {}

extension type _UnsafeNode(RBTree node) {}
extension type RedNode(RBTree node) implements _UnsafeNode, RBTree {}
extension type BlackNode(RBTree node) implements _UnsafeNode, RBTree {}

// If I cast the expression, the code compiles but the analyzer
// doesn't like it (`unnecessary_cast`).
RBTree create2(bool red) =>
    (red ? RedNode(RBTree()) : BlackNode(RBTree())) as RBTree;

// This works.
RBTree create3(bool red) {
  final RBTree x = RedNode(RBTree());
  final RBTree y = BlackNode(RBTree());
  return red ? x : y;
}

void main() {}
```

The most basic property of an extension type is that it is a compile-time concept. In other words, this mechanism is able to have an effect if and only if the static type of the receiver is the given extension type, and it has no effect whatsoever when this is not the case.

In particular there is _no observable difference_ between the code above and the following code:

```dart
RBTree create(bool red) => RBTree();

class RBTree {}

RBTree create2(bool red) => RBTree();

RBTree create3(bool red) {
  final RBTree x = RBTree();
  final RBTree y = RBTree();
  return red ? x : y;
}

void main() {}
```

The point is that (1) the run-time value of an expression like `RedNode(RBTree())` is exactly the same as the value of `RBTree()`, and the extension type constructor that we're invoking doesn't have any side effects. Moreover (2), no members of the extension types are invoked anywhere (they don't even declare any members, but I guess the example would be a simplified version of something where some members are declared). So all those extension types are simply noise, they don't do anything. (The can have an effect in many ways if we extend the program, but in the program as given they do not have an effect.)

Another way to describe the situation is that the extension type is a property of the reference to an object, it is not a property of the object itself (that's the reason why we can avoid allocating anything at all in order to have a run-time representation of the extension typed "thing"&mdash;there is no such representation, and that's the whole point). Given that it is not a property of the object itself, there is no way we can confirm (or refute) the assumption that any particular object was ever the value of an expression whose static type was an extension type.

In other words, if we cast `RedNode(RBTree())` to `RBTree` then there's no way we can ever know that it used to be considered as a `RedNode`. It could have been a `BlackNode`, or it might never have had any of those two types. We've simply "forgotten" everything about that.

So if you want to use extension types then it's important to be aware of the situations where we "forget" the extension type, because you can't know whether it was there or not (so it's a really bad choice to be in trouble if you don't know ;-).

One example of a good way to use an extension type is as a return type in a member signature in a class or similar abstraction.

```dart
extension type FancyString(String value) implements String {
  FancyString fancify() => '**$this**';
}

class A {
  FancyString fs;
  A(this.fs);
}
```

In this case the extension type is the return type of the implicitly induced getter of the instance variable `fs`. Whenever we have an expression `e` of type `A` (or a subtype that doesn't override `fs`), `e.fs` will have the extension type, and we can use members like `fancify`.

We aren't easily going to perform an upcast on a member return type, so that's a good way to ensure that everybody will access that `String` using the type `FancyString`. We can pass the string along to other clients that don't care about the fancy part, like `aFunctionThatAcceptsAString(e.fs)`, but we still have access to `e.fs` using the extension type, because it's a member access and the receiver type is `A`. If we perform an upcast on the receiver (`Object o = e;`) then we won't have access to that member at all (`o.fs` is an error), which is what I mean by "we aren't easily going to perform an upcast".

If we have a bunch of APIs where extension types are used as return types here and there then we can use expressions whose static type is an extension type without thinking much about it, and we can have local variables with the extension types (as in `var v = e.fs;`, where `v` will have type `FancyString`).

The thing that _won't_ work is to write an expression whose type is an extension type, and expecting the object which is the actual value of that expression to have even the faintest idea about the fact that it has (or has had) that extension type as its static type. For example: `assert(RedNode(RBTree()) is BlackNode); // Sure, if you say so! ;-)`.

**Comment by LongCatIsLooong** [comment]
Sorry I didn't include more context (and `RBTree create(bool red) => red ? RedNode(RBTree()) : BlackNode(RBTree());` does look dubious) but yeah those extension types are strictly a compile-time thing in my API. For example, they prevent callers from creating red nodes with red children at compile time: `static RedNode<Value> red<Value>(int key, Value value, { BlackNode<Value>? left, BlackNode<Value>? right })`. 

In a different note, someone ran into the same issue could have a difficult time debugging the problem (I myself had to nuke everything that looks like cache), since CFE and the analyzer don't agree on whether the code is valid. Also currently flutter/flutter has `sdk: '>=3.3.0-0 <4.0.0'`.

**Comment by eernstg** [comment]
Sorry about sounding a little bit sceptical here, but I wonder if it is actually possible to maintain the red-black invariants in a tree where there is no information in each node about whether it's red or black. Do you actually have a working solution? In general, rotations need to be performed according to the colors of the nodes near the top of the subtree of a given node, and I don't think it's possible to choose the correct rotation to perform if we've forgotten which nodes are red and which ones are black. ;-)

(Of course, it is always possible to iterate over the entire tree and find an assignment of colors to nodes that satisfies the invariant, if the tree is balanced so well that such a coloring exists, but that defeats the purpose because it's O(size-of-tree) to even get started doing a single rotation).

**Comment by LongCatIsLooong** [comment]
> I wonder if it is actually possible to maintain the red-black invariants in a tree where there is no information in each node about whether it's red or black

Ah the example was distilled for bug reporting, my `RBTree` class does have an `isBlack` field.
