### ISSUE TITLE
Is Uri.tryParse('sfgdfs') supposed to return a non-null value?

### ISSUE THREAD

**Issue by BirjuVachhani** [dart-lang/sdk#56360]
Following code is not returning null URI when it is supposed to!

```dart
final uri = Uri.tryParse('hello');
print(uri);
```

Actual:
```dart
print(uri); // hello
print(uri == null); // false
```
Expected: 
```dart
print(uri); // null
print(uri == null); // true
```

I tested this on
```
Dart SDK version: 3.4.4 (stable) (Wed Jun 12 15:54:31 2024 +0000) on "macos_arm64"
```
and Dartpad too!

**Comment by lrhn** [comment]
`Uri.tryParse` returns `null` where `Uri.parse` throws. `Uri.parse("hello")` works and parses the same as `Uri(path: "hello")`, as intended.

Everything is working as intended here.

**Comment by BirjuVachhani** [comment]
Shouldn't `Uri.parse` throw then? `Hello` is clearly not a `Uri`, right?

**Comment by lrhn** [comment]
The `Uri` class allows both URIs and URI References, which include "relative" URIs that can then be resolved against full URIs.

That's what allows you to do `someUri.resolveUri(Uri.parse("../sibling/file.dart"))`, the URI reference `../sibling/file.dart` is a relative path reference, and it parses as a URI reference. 
The `Uri.resolve(String reference)` method is really just doing `this.resolveUri(Uri.parse(reference))`, so that's used a lot.

The relative path `hello` parses as a path too, which is why the following works:
```dart
var home = Uri.parse("file:///home/me/dirname/");
var helloFile = home.resolve("hello");
print(helloFile); // file:///home/me/dirname/hello
```
