### ISSUE TITLE
[Extension types] await compatibility issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#56405]
The test [co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A08_t11](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/static_analysis_extension_types_A08_t11.dart) fails on all platforms.
```dart
import 'dart:async';

extension type ObjectET(Object _) implements Object {}
extension type FutureIntET(Future<int> _) implements Future<int>, ObjectET {}

test<X extends ObjectET>(X x) async {
  if (x is FutureIntET) {
    await x;
  }
  if (x is FutureIntET?) {
    await x; // Error: The 'await' expression can't be used for an expression with an extension type that is not a subtype of 'Future'.
  }
}

main() {
  test(FutureIntET(Future<int>.value(42)));
}
```
But according to @eernstg `FutureIntET?` is not actually an extension type and is not incompatible with await. So, there should be no error in both analyzer and CFE.

**Comment by lrhn** [comment]
(Agree. The type `FutureIntET?` does imply a future type of `Future<int>?`, and should be awaitable as such.)

**Comment by chloestefantsova** [comment]
I think both tools behave correctly here: the promotion in the second if-statement doesn't happen. `FutureIntET?` isn't a subtype of the static type of `x`, which is `X`. So, the static type of `x` in the line in question is still `X`, which is incompatible with `await`.

@lrhn correct me if I'm wrong and reopen the issue if needed.

**Comment by lrhn** [comment]
ACK, my bad.

You are allowed to await `FutureIntET?`, but that's not what's happening here.

Since the varable's type is a type variable, promotion can happen either if the tested type is a type that is a subtype of the first variable (so a type variable or a bottom type), or if it's a type that is a subtype of the bound, in which case it promotes to an intersection type.

In this case, `<X extends ObjectET>` so `X x` can't be promoted to `FutureIntET?` since it's not a subtype of either.

Doing `await (x as FutureIntET?);` does not cause any error.
