### ISSUE TITLE
Dart type inference error with ternary operator in case of generyc types

### ISSUE THREAD

**Issue by petro-i** [dart-lang/sdk#56414]
See code below 

there is error reported on string `aFunction(boolValue ? stringExample : intExample);`
_error: The argument type 'Object' can't be assigned to the parameter type 'BaseExample<dynamic>'. (argument_type_not_assignable at [errorexample] bin/errorexample.dart:7)_

but strings 
`aFunction(stringExample);`
and 
`aFunction(intExample);`
work just fine

```void main(List<String> arguments) {
  final boolValue = true;

  final stringExample = StringExample('a string');
  final intExample = IntExample(1);

  aFunction(boolValue ? stringExample : intExample);

  aFunction(stringExample);
  aFunction(intExample);
}

class BaseExample<T> {
  BaseExample(this.value);

  final T? value;
}

class StringExample extends BaseExample<String> {
  StringExample(String value) : super(value);
}

class IntExample extends BaseExample<int> {
  IntExample(int value) : super(value);
}

void aFunction(BaseExample example) {
  // some stuff here
}```

**Comment by eernstg** [comment]
Perhaps you're running an older version of the Dart tool chain? We used to have this behavior (because the upper bound computation would choose `Object` rather than `BaseExample<OfSomething>` as the type of the conditional expression `boolValue ? stringExample : intExample`.

However, the typing of conditional expressions in recent versions of the language and tool chain has been improved, and there is no compile-time error.

See [this item](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#language-2) for details.

**Comment by eernstg** [comment]
I'll close this issue because it reports on a behavior which is not present in recent versions.

**Comment by eernstg** [comment]
PS: The triple-backquotes must be on a separate line. ;-)
