### ISSUE TITLE
Unexpected end of program when closing a StreamController

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#56424]
Consider the following:

```dart
import 'dart:async';

Future<void> main() async {
  try {
    final c = StreamController<int>();
    print('a');
    await c.close();
  } finally {
    print('b');
  }
}
```

This will somehow print `a`. Then the program will stop, and the `b` print is never reached.
This feels wildly unexpected. It is as if `c.close()` behave like an `exit()`

---

Dart SDK version: 3.5.0-323.0.dev (dev) (Tue Jul 2 06:25:57 2024 -0700) on "macos_arm64"

**Comment by jellynoone** [comment]
If you do:
```dart
import 'dart:async';

Future<void> main() async {
  try {
    final c = StreamController<int>();
    print('a');
    await c.close();
    print('c');
  } finally {
    print('b');
  }
}
```
`c` is never printed either. I think this is because the `Future` never completes, since the `StreamController` doesn't have a listener as is documented by `close()`.

However, if you put a listener on `StreamController.stream`:
```dart
import 'dart:async';

Future<void> main() async {
  try {
    final c = StreamController<int>();
    print('a');
    c.stream.listen(print);
    await c.close();
  } finally {
    print('b');
  }
}
```
The program behaves as expected.

**Comment by rrousselGit** [comment]
>  I think this is because the Future never completes, since the StreamController doesn't have a listener I think the documentation of close() implies a single listener stream actually needs a listener in order for close() to complete.

That's likely the case.  
The thing is, the program does complete!

If we assume that `close()` never completes, I'd expect that the program would hang, forever waiting for the future to resolve.
But that's not the case. The program somehow quits anyway

**Comment by jellynoone** [comment]
If I'm not mistaking, Dart terminates the program when no work needs to be done or when it reaches the end.

In this case the program stops at the future and waits for a result. Because the system is a closed one i.e. we aren't listening for outside events like `ReceivePort`s from another Isolate and there are no additional events / tasks scheduled i.e. no other future is doing any work. The program knows it will never complete the future, thus terminates the program.

You can observe the same behaviour when doing this:
```dart
import 'dart:async';

Future<void> main() async {
  try {
    final c = Completer();
    print('a');
    await c.future;
  } finally {
    print('b');
  }
}
```

The future is known to never complete. We will never call `c.complete`. The program knows this because when it reaches `await c.future`, it has no other synchronous work to do and it also isn't listening to an external source so it terminates.

**Comment by lrhn** [comment]
Looks like it's working as designed.

The `close` method is specified as returning a future that completes when the _done_ event has been delivered.
A single-subscription stream buffers events until it has a listener.
So the done event is never delivered, the future never completes, and the program  has nothing more to do.

That's why it makes a difference to add a listener, it makes the done event be delivered, which then completes the future.
