### ISSUE TITLE
Missing unnecessary `!` warning with nested extension types

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#56472]
As I understand it, the program below should produce a warning for `a.b!`, saying the `!` is not necessary, but it doesn't. This only happens for extension types.

Neither the CFE or analyzer warn today.

```dart
void main() {
  var a = A({'b': {}, 'c': 'hello'});
  a.b!; // Should get a warning, but none is produced
  a.c!; // Does produce a warning
}

extension type A(Map json) {
  B get b => json['b'] as B;
  String get c => json['c'] as String;
}
extension type B(Map json) {}
```

**Comment by eernstg** [comment]
I think it's OK: `a` gets the inferred type `A`, `A` has a member named `b` with return type `B`, `B` is a potentially nullable type (because `B` doesn't have `implements Object`, or indeed `implements T` where `T` is any non-nullable type that is a supertype of `Map`)

**Comment by jakemac53** [comment]
The representation type is non-nullable though? We know for certain it is not null right? This is unambiguously not necessary.

**Comment by eernstg** [comment]
We had a rule for quite some time where each extension type would have a nullability which was computed based on the nullability of the representation type.

However, that's really inconvenient in several ways. For example, the number of steps in the superinterface graph up to `Object?` depends on whether or not `Object` is included, which could depend on the type argument. Every other type in Dart has a supertype structure which is independent of any type arguments (`List<String>` and `List<int?>` have different superinterfaces, but the _structure_ of the superinterface graph is the same, e.g., both have a parent node in the superinterface graph of the form `Iterable<S>` for some `S`).

But with that old approach for extension types, `E<int?>` would have `Object?` as its parent, and `E<String>` would have `Object` as its parent. This creates a lot of entertainment when considering **UP** and other typing operations.

I don't think we should revisit that approach. We tried it really hard for a long time.

In the current approach, an extension type is potentially nullable when it does not have a path in the superinterface graph going to `Object`, and it is non-nullable when there is such a path. The only way we can make that choice is by declaring it explicitly:

```dart
extension type E1(int i) implements Object {} // Non-nullable.
extension type E2(int i) {} // Potentially nullable and potentially non-nullable.
```

Being non-nullable means being a subtype of `Object`, which is clearly true for `E1`. On the other hand, `E2` is not a subtype of `Object`, so it is not non-nullable, which is the same thing as being potentially nullable.

Note that `E2` is also not nullable (because `Null` is not a subtype of `E2`), which is the same thing as being potentially non-nullable.

This basically means that the nullability status of an extension type is by default encapsulated ("you can't know"), and also that it is an error to assign null to a variable whose type is an extension type, no matter whether its representation type contains null or not. I think this encapsulation property is a good property.

One of the consequences of this is that we must treat an extension type a little bit like a type variable: If `e` has a type which is a type variable `X` that has no bound then we cannot assume that it isn't nullable (so maybe a value of type `X` turns out to be null and hence `Object o = e;` is an error), but we also cannot assume that it is allowed to be null, so `X x = null;` is also an error.

Similarly, with `e` of type `E2`, both `Object o = e;` and `E2 e2 = null;` are errors.

With reference to the original example, ...

```dart
void main() {
  var a = A({'b': {}, 'c': 'hello'});
  a.b!; // Should get a warning, but none is produced
  a.c!; // Does produce a warning
}

extension type A(Map json) {
  B get b => json['b'] as B;
  String get c => json['c'] as String;
}
extension type B(Map json) {}
```

... we can say that `a.b!` admits the `!` because it is unknown (by design) that `a.b` couldn't possibly be null because it has type `B`, and `B` doesn't reveal whether or not it might be null.

I'm trying to understand why this would make it harder to use nested extension types (I guess that would mean extension types whose members have other extension types as return types, or something like that), but I can't immediately see the problem.

Would it suffice for you to add an `implements Object` in order to specify just the non-nullability explicitly? Or would it perhaps even be OK to specify `implements Map` or `implements Map<string, Object?>`? It's all about encapsulation.

**Comment by jakemac53** [comment]
If we can't understand whether something is nullable or not, then why are we not _requiring_ the `!`s or `?`s where appropriate? Are we falling back on dynamic? I can't help but feel that something is very fundamentally wrong here. Ignoring dynamic, you should either _definitely_ need a `!` or `?`, or not. These seem to be in a weird middle zone where the compiler allows both, which indicates the code is unsafe to me? But I don't expect it to be.

> I'm trying to understand why this would make it harder to use nested extension types (I guess that would mean extension types whose members have other extension types as return types, or something like that), but I can't immediately see the problem.

It makes it hard to write _good_ code (that doesn't do unnecessary null checks or assertions). Because there is nothing helping you to remove them.

In my case, I was refactoring code which used to return a nullable extension type, to return a non-nullable extension type. I expected to get a bunch of nice dart fixes automatically provided for me, to remove the unnecessary `?`s and `!`s from my code, but I got nothing :/. I instead had to track down all the uses manually and try to fix them up.

> Would it suffice for you to add an implements Object in order to specify just the non-nullability explicitly? 

I certainly could do that, and maybe I will, but it seems wrong to have to do that in the "obvious" (to a user) situations.

**Comment by lrhn** [comment]
Extension types are unique in that they can be neither nullable, nor non-nullable, *and* have members other than those of `Object`. (Well, semi-unique, an extension on a nullable or potentially type can effectively do the same.)

That's why `A a = ...; a.b; a?.b; a!.b;` are all allowed and meaningful. They really do mean: `a.b; if (a != null) a.b; if (a != null) throw ...; else a.b;`.
We know that for the *current* definition of `A` the value can never be `null` at runtime, but that is a property of the current representation type.

If you chose to change `A` to 
```dart
extension type A(Map? json) {
  B get b => json?['b'] as B;
  String get c => json?['c'] as String;
}
```
or
```dart
extension type A(Object? json) {
  B get b => (json as Map)['b'] as B;
  String get c => (json as Map)['c'] as String;
  String get s => json as String;
}
```
in the future, then *most likely* all existing code would keep working. 
Even other extension types implementing `A` would stay valid.
As long as nobody does `case A a => a.b;`, at least.

(If you actually put `null` into an `A` wrapper, then existing code may start breaking, but it's a backwards compatible *type* change.)

That's another reason we don't want to infer that `extension type A(T _)` is a subtype of `Object` if `T` is inherently a subtype of `Object` (where "inherently" means using the bounds of type variables instead of their current type, which would avoid the nullability of the type depending on the type of type parameters). If we do that, just like *every other place* we implicitly derive something that the author didn't say from "circumstantial evidence", providing *users* of the API with more capabilities, it makes the author need a way to *opt out* of that derivation if they don't want it for some reason. For example compatibility with later changes.
Anything we derive that way locks the author into the shape of the information we derived it from.

If you want your extension type to be non-nullable, add `implements Object`. It's that easy. If you don't, we assume you *don't want to promise* that the value will stay non-nullable.

**Comment by jakemac53** [comment]
Ah ok, if the reason is to allow an extension type to _change_ it's representation type (specifically, its nullability), and have that not be breaking, then I can understand that. That is the missing piece I wasn't understanding before.

That also explains why adding `implements Object` is required, because I am now explicitly opting into never being nullable (or at least opting into that being a breaking change if I do).

It would be nicer if that was the default, and there was an opt out instead, but I don't know what the opt out would look like so this makes sense.

Thanks
