### ISSUE TITLE
Missing `continue_without_label_in_case` error when switch statement is in a for loop.

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#56578]
```dart
enum _A { b, c }

void main() {
  switch (_A.b) {
    case _A.b:
      continue; // error
    case _A.c:
  }

  for (var value in _A.values) {
    switch (value) {
      case _A.b:
        continue;  // no error
      case _A.c:
    }
  }
}
```

This example produces a `continue_without_label_in_case` error for the first switch statement. However, the second receives no such error. I'm not sure if this is a deliberate choice or not.
At least to me, requiring a label in the second example seems much more useful.

**Comment by jellynoone** [comment]
Since the behaviour is probably intended as is. Could this be turned into a request for a lint rule that requires an explicit label for switches inside loop constructs?

**Comment by lrhn** [comment]
This looks like it's behaving as intended.

A `continue` with no label continues the nearest enclosing *loop*. If there is none, the error message suggests that you have forgotten to add a label, because that's the *only* possible `continue` you can write inside a `switch` that is not inside a loop.

If the `continue` is inside a loop, it continues that loop.
