### ISSUE TITLE
[wildcards] Consider quick fix: convert `UNUSED_CATCH_STACK` to wildcard

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#56582]
Given:

```dart
f() {
  try {
  } on String catch (e, stackTrace) {
    print(e);
  }
}
```

we _might_ consider a fix that produces:

```dart
f() {
  try {
  } on String catch (e, _) {
    print(e);
  }
}
```

in addition to the one that currently removes the unused clause:

```dart
f() {
  try {
  } on String catch (e) {
    print(e);
  }
}
```

**Question:** is there value in adding a convert UNUSED_CATCH_STACK to a wildcard fix?

@kallentu @bwilkerson

**Comment by bwilkerson** [comment]
I don't see any value in having a wildcard in a non-required location. While the language makes it valid (presumably for consistency), I wouldn't want to see it in my code. (I'd actually want an `unnecessary_stack_trace_parameter` (or some such) warning.

The only time I'd allow a wildcard is for something like
```dart
f() {
  try {
  } on String catch (_, stackTrace) {
    print(stackTrace);
  }
}
```
where the exception isn't used but has to be provided in order to capture the stack trace.

If we had a warning when the exception parameter isn't referenced (which we don't have but might consider adding now) we could have a fix to convert it to a wildcard.

**Comment by pq** [comment]
Great. Agreed. Thanks!
