### ISSUE TITLE
Bitwise shifting broken in the browser -10000 << 1

### ISSUE THREAD

**Issue by Meai** [dart-lang/sdk#56615]
```
void main() {
  // must be -20000 but it isn't in the browser
  print(-10000 << 1);
}
```

Check in dartpad:

https://dartpad.dev/?id=c25d2f3fae3469e67de7707d5035a769

**Comment by lrhn** [comment]
This is the documented behavior for web numbers compiled to JavaScript.
It's working as designed.

**Comment by Meai** [comment]
> This is the documented behavior for web numbers compiled to JavaScript. It's working as designed.

how can that be desired given that this behavior results in totally different runtime behavior from what both javascript and dart natively do? You can try this in the browser console or in nodejs or even in any other language including the Dart VM and `-10000 << 1` will correctly produce `-20000` instead of some kind of integer underflow such as `4294947296`

**Comment by lrhn** [comment]
The documentation for [web numbers] don't say *why* the current behavior was chosen.

Historically, web number behavior was decided at a time when Dart did not have a `>>>` operator.
JS bit operations create 32-bit results. The choice was between interpreting those bits as an unsigned or signed Dart number. At the time (long, long ago, before Dart 1.0) the most important use-case was implementation of crytography, and it was decided that unsigned results would work better for that. 

The behavior hasn't changed since then, likely because changing things would be breaking.

**Comment by nshahan** [comment]
@Meai 
What utf8codec parsing code are you referring to, is this a published package? It's possible this should be updated to be resilient to the platform number differences.

**Comment by rakudrama** [comment]
We chose to have all bit-operations (bitwise and/or/xor, shifts) produce unsigned results when compiled to JavaScript for the reason of _compatibility_. _More_ code works the same on Dart VM and Dart on the web with that choice than other choices.

As Lasse said, crypto code (e.g. MD5 or SHAxxx digests) works with that choice. It did not work if we allowed the high-bit to be interpreted as a sign bit. Other kinds of code that tend to work better with unsigned results include bit-masks and bit-strings (especially with concatenation and substrings), multiple precision arithmetic (e.g. an implementation of BigInt), and anything similar copied from C/C++ code that uses `uint32_t` variables.

We could have made a different choice, for example, to be just like JavaScript. That too has surprises (consider `0xFFFFFFFF | 1 == -1` and `1 << 31 == -2147483648`). No matter what choice we made, _something_ would be uncomfortable. Treating results as unsigned is the most simple option when thinking of the value as a collection of bits, since each bit is the same.

If you need a signed result, use `(a << b).toSigned(32)`.

For UTF8 conversion I recommend using `dart:convert`. Not only are the provided conversions well tested and used extensively, they are optimized to make use of special characteristics of the platform (native, web, etc).

**Comment by fishythefish** [comment]
Closing as WAI, but feel free to continue discussing.
