### ISSUE TITLE
We need some way to know what Exceptions are thrown by a function. It's like the type safety doesn't apply to exceptions, it drives me mad.  Or ditch try/catch entirely, I don't know. I use Either in my code, but I can't force third party packages or even the official Flutter SDK to use it.  There has to be a better solution

### ISSUE THREAD

**Issue by 1999ali1999** [dart-lang/sdk#56622]
### Commit(s) to merge

unknown

### Target

unknown

### Prepared changelist for beta/stable

unknown

### Issue Description

We need some way to know what Exceptions are thrown by a function. It's like the type safety doesn't apply to exceptions, it drives me mad.

Or ditch try/catch entirely, I don't know. I use Either in my code, but I can't force third party packages or even the official Flutter SDK to use it.

There has to be a better solution)

### What is the fix

unknown

### Why cherry-pick

unknown

### Risk

unknown

### Issue link(s)

Not found

### Extra Info

Not found

**Comment by vsmenon** [comment]
Closing as not actionable.

We constantly work toward improving the ergonomics of Dart.

Please feel free to engage on potential language issues at https://github.com/dart-lang/language/issues.  But, if you choose to do so, please search the repo for existing issues and try to engage on specific features that would help instead of general comments.

**Comment by natebosch** [comment]
See also the existing discussion in https://github.com/dart-lang/language/issues/984 and https://github.com/dart-lang/language/issues/3165
