### ISSUE TITLE
The only thing I don't like about dart is that it is very easy to write deeply nested widgets at the return of build function.

### ISSUE THREAD

**Issue by 1999ali1999** [dart-lang/sdk#56621]
### Commit(s) to merge

unknown

### Target

unknown

### Prepared changelist for beta/stable

unknown

### Issue Description

The only thing I don't like about dart is that it is very easy to write deeply nested widgets at the return of build function...

### What is the fix

unknown

### Why cherry-pick

unknown

### Risk

unknown

### Issue link(s)

Not found

### Extra Info

Not found

**Comment by vsmenon** [comment]
Closing as not actionable.

We constantly work toward improving the ergonomics of Dart, and often in the context of Flutter.

Please feel free to engage on potential language issues at https://github.com/dart-lang/language/issues.  But, if you choose to do so, please search the repo for existing issues and try to engage on specific features that would help instead of general comments.
