### ISSUE TITLE
Weird: The analyzer infers the exact type but the compiler infers Object.

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#56666]
The analyser infers the exact type but the compiler infers `Object`.

```dart
BeamerDelegate Function() _routerDelegateBuilderCapsule(
  CapsuleHandle use,
) {
  var routes = <Pattern, dynamic Function(BuildContext, BeamState, Object?)>{};

  var guards = <BeamGuard>[];

  // Silent data
  final currentPath = use(currentPathCapsule);

  final routeManagers = [
    // Old
    // ...use(_routeManagersCapsule),

    // New
    ...(use(routeManagersCapsule).getAll()).map(use).nonNulls,
  ];

  // Route managers
  for (final routeManager in routeManagers) {
    // Builder
    routes[routeManager.route] = routeManager.builder;

    // Guard
    final routeGuards = routeManager.guards;
    if (routeGuards != null) guards.addAll(routeGuards);
  }

  final initialPath = use.initialPath;

  return () => BeamerDelegate(
        initialPath: currentPath.value ?? initialPath,
        notFoundRedirectNamed: initialPath,
        locationBuilder: RoutesLocationBuilder(
          routes: routes,
        ).call,
        setBrowserTabTitle: true,
        guards: guards,
      );
}
```

Error:
```
../../../../FLUTTER/LIBS/busslina-flutter-lightweight-lib/lib/v2/routing/routing.capsules.dart:29:25: Error: The getter
'route' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'route'.
    routes[routeManager.route] = routeManager.builder;
                        ^^^^^
../../../../FLUTTER/LIBS/busslina-flutter-lightweight-lib/lib/v2/routing/routing.capsules.dart:29:47: Error: The getter
'builder' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'builder'.
    routes[routeManager.route] = routeManager.builder;
                                              ^^^^^^^
../../../../FLUTTER/LIBS/busslina-flutter-lightweight-lib/lib/v2/routing/routing.capsules.dart:32:38: Error: The getter
'guards' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'guards'.
    final routeGuards = routeManager.guards;
```

Video demo:
https://streamable.com/v1fgx6

I suspect it has relation with `...(use(routeManagersCapsule).getAll()).map(use).nonNulls,`.

**Comment by busslina** [comment]
This modification works on analyzer but failes on compiler:

![imagen](https://github.com/user-attachments/assets/6531c868-1f1a-4d49-82a2-dc048c23faca)


Error:

```
../../../../FLUTTER/LIBS/busslina-flutter-lightweight-lib/lib/v2/routing/routing.capsules.dart:23:54: Error: Can't assign
spread elements of type 'Object' to collection elements of type 'RouteManager'.
 - 'Object' is from 'dart:core'.
 - 'RouteManager' is from 'package:busslina_flutter_lightweight_lib/v2/routing/routing.capsules.dart'
 ('../../../../FLUTTER/LIBS/busslina-flutter-lightweight-lib/lib/v2/routing/routing.capsules.dart').
    ...(use(routeManagersCapsule).getAll()).map(use).nonNulls,
```

**Comment by busslina** [comment]
This modification works on both analyzer and compiler, but shows `unnecessary cast` warning on analyzer:

![imagen](https://github.com/user-attachments/assets/8d3cfc61-818e-400b-94eb-a22858e8382c)

**Comment by lrhn** [comment]
The type of `use` is `CapsuleHandle`, which I assume is from `package:rearch`.
If so, the type of its [`call`](https://pub.dev/documentation/rearch/latest/rearch/CapsuleReader/call.html) method is `T Function<T>(Capsule<T>)`.
The type of `[...use(_routeManagersCapsule)]` will then depend on the type of `_routeManagerCapsule`, which I don't know the type of.

Does the static type of `_routeManagersCapsule` implement `Capsule` (likely given the name), and if so, how?

**Comment by busslina** [comment]
@lrhn Since I changed some names, to make it more clear I created a simple project reproducing the bug:

https://github.com/busslina/inferring_type_issue/blob/master/bin/inferring_type_issue.dart

![imagen](https://github.com/user-attachments/assets/4f7f1ea8-50cc-4156-a93e-faa3bb33219e)

**Comment by lrhn** [comment]
Does fasting like a type inference error around implicit `call` insertion.

**Comment by eernstg** [comment]
I've taken a look at the [stand-alone example repo](https://github.com/busslina/inferring_type_issue/blob/master/bin/inferring_type_issue.dart). By the way, thanks for providing a stand-alone example, @busslina, that is very helpful!

Consider the [location](https://github.com/busslina/inferring_type_issue/blob/1caafbf5977bab26e8f6a6a294319dedf88b653e/bin/inferring_type_issue.dart#L13) where the issue arises:

```dart
List<String> namesCapsule(CapsuleHandle use) => [
      ...use(rawNamesCapsule).map(use).nonNulls,  // Here!
  ];
```

In this expression, `use` has static type `CapsuleHandle`, whose superinterface `CapsuleReader` declares the member `T call<T>(Capsule<T> capsule)`. It is invoked, and hence it is transformed into `use.call(rawNamesCapsule)`.

`rawNamesCapsule` has type `Iterable<Capsule<String?>>` and there's no context (the invocation of `use.call` is a receiver), so `T` is inferred as `Iterable<Capsule<String?>>` and hence `use` as an argument to `map` has context type `_ Function(Capsule<String?>)`, that is `_ Function(String? Function(CapsuleHandle))`.

This is where the analyzer and the common front end diverge. Here is a simpler example showing the same discrepancy:

```dart
class C {
  T call<T>(T t) => t;
}

X Function(String) f<X>(X Function(String) g) => g;

void main() {
  // ignore: implicit_call_tearoffs
  var g = f((C()));
  g.expectStaticType<Exactly<String Function(String)>>; // CFE Error.
  print(g.runtimeType);
}

typedef Exactly<X> = X Function(X);

extension<X> on X {
  X expectStaticType<Y extends Exactly<X>>() => this;
}
```

The CFE complains at the comment that `g` doesn't have type `String Function(String)`, it has type `dynamic Function(String)`, which means that the type argument to `f` has been inferred as `dynamic` (whereas the analyzer infers `String`).

This could again be caused by using two different approaches: The analyzer detects that `C()` has a method named `call` and occurs in a context where a function is expected, and it then proceeds to infer `C()` as `C().call<String>`, which is then used during upwards inference such that `f(...)` is inferred as `f<String>(...)`.

Presumably, the CFE does not use the result from inferring a type argument to `C().call` during upwards inference. Should it?

@stereotype441 and @leafpetersen, it looks like your input would be helpful here. ;-)

**Comment by eernstg** [comment]
@johnniwinther, are you convinced that this is a CFE issue? Otherwise I still think it's uncertain which tool to blame.

**Comment by lrhn** [comment]
It would be nice if `C()` and `C().call` has the same behavior in a place where `.call` is added to `C()`, *if possible*. Or reasonable. Or useful.

The issue is that the type of `C()` in `C().call` occurs in a position with no context type, but `C()` by itself may have a context type.
If `.call` insertion is applied, that context type is a function type, which can't constrain `C()`.
On the other hand, it can constrain the parameter types of `call`, which can in turn suggest a type argument to `C()`.

**Comment by johnniwinther** [comment]
This does should like a CFE problem.

**Comment by busslina** [comment]
Can I know in which Dart version this is solved?

**Comment by johnniwinther** [comment]
This will be part of 3.6.
