### ISSUE TITLE
Configurable URI doesn't work in VM

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#56727]
Please see the code below. 
```dart
// main.dart
//import 'dart:collection';

import 'lib1.dart' if (dart.library.collection) 'lib2.dart';

main() {
  print(lib1_var); // VM. Error: Undefined name 'lib1_var'.
  print(lib2_var); 
}

// lib1.dart
String lib1_var = "lib1";

// lib2.dart
String lib2_var = "lib2";
```
Depending on if `dart:collestion` is imported or nor the analyzer shows the correct error. If `dart: collection` presents, then `lib1_var` is undefined, otherwise `lib2_var`. VM shows an error that `lib1_var` is undefined in any case. Seems that VM imports `lib2.dart` despite of the condition.

Tested on `Dart SDK version: 3.6.0-232.0.dev (dev) (Mon Sep 9 17:02:22 2024 -0700) on "windows_x64"`

**Comment by lrhn** [comment]
This is working as intended. The VM should import `lib2.dart` if `dart:collection` *can* be imported when compiled by the current compiler., which it can.

The condition `if (dart.library.collection)` doesn't ask whether `dart:collection` is imported, but whether it can be imported, whether it exists on the current target platform.
The `dart:collection` library can be imported on all platforms, and since it can be imported when run by the VM, the VM is correct to use the second import.

The way to use conditional imports is something like:
```dart
import "generic_library.dart" 
    if (dart.library.io) "library_using_io.dart";
```
where the `library_using_io.dart` is used if *it* can import `dart:io`, which it presumably then does.
The two libraries, `generic_library.dart` and `library_using_io.dart` should expose the same API signature, so that the importing code can treat them as interchangeable.

The analyzer is not platform-aware. It doens't know which platforms a program will be compiled for, it's only checking static semantics, so the analyzer consistently chooses the original URI and ignores conditional imports, given that those *presumably* are unavailable on some platforms.
Here `dart:collection` is actually available on all *current* platforms, but since someone asked, the analyzer assumes that it's possible for it to not be there.

**Comment by sgrekhov** [comment]
Ok, thank you for explanation. Closing this issue.
