### ISSUE TITLE
`--enable-vm-service` flag behaviors are inconsistent between debugger and cli

### ISSUE THREAD

**Issue by pattobrien** [dart-lang/sdk#56733]
CC @DanTup (re conversation: https://discord.com/channels/608014603317936148/1282837915847757964)

Given the following Dart script:

```dart
import 'dart:developer';

Future<void> main(List<String> args) async {
  print('Starting server code...');

  final vmServiceInfo = await Service.getInfo();
  final wsUri = vmServiceInfo.serverWebSocketUri!;
  print('VM Service accessible at: $wsUri');
}
```

... and the following launch config and cli commands:

### launch.json (debugger):
```json
    {
      "name": "launch.json example",
      "request": "launch",
      "type": "dart",
      "program": "bin/main.dart",
      "toolArgs": [
        "--observe",
        "--enable-vm-service=6968",
        "--disable-service-auth-codes"
      ],
    },
```
### cli command:
```console
dart run --observe --enable-vm-service=6968 --disable-service-auth-codes bin/main.dart
```

The output / behavior is different.

### debugger output (incorrect expected behavior)
```console
Connecting to VM Service at ws://127.0.0.1:51752/32Cv_oigsEk=/ws
Connected to the VM Service.
Starting server code...
VM Service accessible at: ws://127.0.0.1:51752/32Cv_oigsEk=/ws 
```

### cli output (correct expected behavior)

```console
❯ dart run --observe --enable-vm-service=6968 --disable-service-auth-codes bin/main.dart
Starting server code...
VM Service accessible at: ws://127.0.0.1:51780/ws
The Dart VM service is listening on http://127.0.0.1:6968/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:6968/devtools/?uri=ws://127.0.0.1:6968/ws
```

**Comment by DanTup** [comment]
@bkonyi my guess is that this is because the flag is passed to the VM by the debug adapter and the original VM Service _does_ use that port, but then the debug adapter starts DDS which binds a new port, and we take the URI from that?

https://github.com/dart-lang/sdk/blob/a6a2c57d689c5aca7d9fadd5dbf04615246ed198/pkg/dds/lib/src/dap/adapters/dart.dart#L792

What's the best way to handle this? Can we return the normal VM Service URI (I can't remember if DDS needs to proxy all the traffic or is just registering new services etc.)? If not, I wonder if we'd need to either parse the VM args in DAP (which doesn't seem ideal to duplicate here) and use the port for DDS _instead_ of passing it to the VM?

**Comment by bkonyi** [comment]
> @bkonyi my guess is that this is because the flag is passed to the VM by the debug adapter and the original VM Service _does_ use that port, but then the debug adapter starts DDS which binds a new port, and we take the URI from that?

It seems like that's the case. 

> What's the best way to handle this? Can we return the normal VM Service URI (I can't remember if DDS needs to proxy all the traffic or is just registering new services etc.)? If not, I wonder if we'd need to either parse the VM args in DAP (which doesn't seem ideal to duplicate here) and use the port for DDS _instead_ of passing it to the VM?

All traffic should go through DDS as any attempt to connect directly to the VM service while DDS is connected will either fail or get a redirect to DDS (depending on whether or not the websocket implementation allows for following redirects).

While there's definitely a way to handle this properly, I'm wondering why the Dart DAP adapter even needs to start DDS itself? I honestly can't remember why we decided to do this, but since we don't rely on `dart run` to launch DDS anymore (the VM service handles this now) maybe we can avoid the headache and just let the VM handle this?

**Comment by DanTup** [comment]
> While there's definitely a way to handle this properly, I'm wondering why the Dart DAP adapter even needs to start DDS itself?

I think we wanted to avoid an additional process and thought we might one day have DDS + DAP closer together (to avoid additional layers). I don't know if that still makes any sense though, and Flutter always has its own DDS and is hard-coded to set `false` to the DAP-provided DDS.

If you think it makes no sense to do here, I will remove it (keeping constructor the flag as a no-op initially, to simplify rolling the update into Flutter) and do some testing.
