### ISSUE TITLE
[extension types/analyzer] `The receiver can't be null` false negative on `extension type` typed values?

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#56759]
Consider:

```dart
void main() {
  const Foo a = Foo(0);
  const int b = 0;
 
  a?.toString();
// The receiver can't be null, so the null-aware operator '?.' is unnecessary.
// v
  b?.toString();
}

extension type const Foo(int i) {}
```

`b?.toString();` causes the analyzer to emit a `The receiver can't be null, so the null-aware operator '?.' is unnecessary.` diagnostic, but it looks to me like `a?.toString();` could also be annotated with a similar diagnostic.

**Comment by lrhn** [comment]
It's reasonable. The type of `b` is `int` which is a subtype of `Object`. That guarantees that the value cannot be `null`.

The type of `a` is `Foo`, which is *not* a subtype of `Object`, and also not a supertype of `Null`.

The current representation type of `Foo` is `int`, which means that the actual value won't be `null`, but depending on design, it may be reasonable and non-breaking for the author to change the representation type in a future version, maybe to `int?`.
The user of the type `Foo` is not allowed to assume that the value cannot be `null`, because that would make it breaking for the author to change that.

**Comment by eernstg** [comment]
That's a great answer, @lrhn!

Just one more thing comes to mind:

The analyzer should probably treat the members of `Object` differently than other members. Those members can safely be invoked on a receiver even in the case where that receiver could be null. The null safety specification does make this distinction:

> It is an error to call a method, setter, getter or operator on an expression whose type is potentially nullable and not `dynamic`, except for the methods, setters, getters, and operators on `Object`.

Of course, we're looking at the converse: The code has `?.` even though it isn't required, and the error message above is concerned with the case where the code has `.`, and the receiver is potentially nullable. But it seems to justify the following modification of the analyzer:

The analyzer would report that `e?.toString()` does not need `?.` _even in the case_ where the static type of `e` is potentially nullable (which includes the case where it is nullable). Similarly for `hashCode`, `runtimeType`, and `noSuchMethod`. We don't get any warnings in the following case today, but we would then get a warning:

```dart
void f(int? i) {
  var s = i?.toString(); // Warning, `?.` not needed.
  print(s);
}
```

Note that the signature has to be the one in `Object`, otherwise the given member should be treated as a non-`Object` member:

```dart
class A {
  String toString([int _ = 0]) => super.toString();
  MyType get runtimeType => MyType();
}

class MyType implements Type {
  noSuchMethod(_) => throw "Not reached";
}

void main() {
  A? a = A() as dynamic;
  a?.toString(15); // No warning, `?.` _is_ needed.
  MyType myType = a?.runtimeType ?? MyType(); // No warning.
}
```

**Comment by srawlins** [comment]
Thanks for the responses. I'll close as WAI then.
