### ISSUE TITLE
Incorrect record runtime type hash code in VM

### ISSUE THREAD

**Issue by osa1** [dart-lang/sdk#56771]
The test added in https://dart-review.googlesource.com/c/sdk/+/386200 is currently failing in VM.

Minimal repro:

```dart
void main() {
  final record3 = (List<int>.filled(3, 1, growable: false), "a");
  final record4 = (List<int>.filled(3, 1, growable: true), "b");
  print(record3.runtimeType == record4.runtimeType);
  print(record3.runtimeType.hashCode == record4.runtimeType.hashCode);
}
```

First line prints `true` so the record runtime types are equal, but second line prints `false` so the hash codes of equal objects are not the same.

**Comment by lrhn** [comment]
Records makes it hard(er) to cheat on `runtimeType`. If a class overrides the `runtimeType` getter, then it doesn't affect the runtime type of a record containing that value, which uses the *actual* runtime type of the object for equality.

It also means that if runtime code fiddles with record runtime type equality, which it seems to do here since it gives `true` for something that are not the same actual runtime types, it needs to fiddle with record `hashCode` too.

This is not just for lists:
```dart
void main() {
  var i1 = 1; // Smi.
  var i2 = -0x8000000000000000; // Not Smi.
  print((i1,).runtimeType == (i2,).runtimeType); // true
  print((i1,).runtimeType.hashCode == (i2,).runtimeType.hashCode); // false
  // And more nesting too.
  print(((i1,),).runtimeType == ((i2,),).runtimeType); // true
  print(((i1,),).runtimeType.hashCode == ((i2,),).runtimeType.hashCode); // false
}
```

**Comment by alexmarkov** [comment]
VM implementation of `Object.runtimeType` hides certain implementation types and maps them to certain public user-visible types (even though some of them are abstract):
```
_OneByteString, _TwoByteString -> String
_Smi, _Mint -> int
_Double -> double
_Type, _FunctionType, _RecordType, _TypeParameter -> Type
_List, _GrowableList, _ImmutableList -> List
```

However, `Object.runtimeType` was not performing such substitution recursively for types of record fields.

`Type.==` also compares certain distinct types as equal, matching the mapping above.

I see the following options for fixing this bug:
(1) Change `Object.runtimeType` for records to substitute field types using the mapping above (apply it recursively).
(2) Change `Type.hashCode` to substitute types before calculating hash, similarly to `Type.==`.
(3) Remove this type substitution altogether and show real implementation types to users.

(1) or (2) or both are fairly local and non-breaking changes.

However, this type substitution has been a recurring source of bugs, so I'm leaning towards (3), but I'm not sure if this is acceptable as it could be too breaking. I can imagine code like this:
```Dart
final handlers = <Type, Function>{};
handlers[int] = (int value) { ... };
handlers[String] = (String value) {...};
...
handlers[obj.runtimeType]!.call(obj)
```
It will be totally broken by this change, and not easily fixable as VM implementation types are private and not accessible from user code (cannot write `handlers[_Smi] = ...`).

@lrhn @mraleph @mkustermann @a-siva @rmacnak-google Any opinions / preferences?

**Comment by lrhn** [comment]
Break _all_ the `runtimeType`s!

More realistically, it might be possible to go for option 3, but it'll take some gentle nudging of the existing code base to make it not depend on `runtimeType` for things like this. I don't know where to start. Maybe changing the behavior of `runtimeType` in development mode first, so we don't break code that's currently in production, and give people time to change. And give them something to change to.

Probably can't make it language versioned (it's object behavior, not syntax semantics).

(I'd have expected `Set` and `Map` too, but if they're not hiding their subclasses today, that's one bullet dodged. And it's just be luck if `Symbol` is only one class, I could totally see a `_PrivateSymbol` subclass. I guess an empty library-ID per public name is cheaper than getting polymorphic.)

Since `List` is generic, using its `runtimeType`  is already questionable. A `handlers[List] = ...` wouldn't be found by `handlers(<Object?>[].runtimeType)`. Far too fragile to ever amount to anything.
Then it's really only `String` and `int`. The `int` version may or may not work on the web. (Using `double` wouldn't always work as intended, since `1.0.runtimeType` is `int`.)

I don't know how much code we would actually break. We could try and see.
I do know we won't break any *good* code, but that's not the bar for breaking. 😞 

Otherwise we should pick the cheaper of options 1 and 2. Since equality works without eagerly substituting, making `hashCode` work the same way is probably the smaller change. (Another option could be lazy canonicalization. If you never call `==` or `hashCode` on a record runtime type, there is no need to do anything. If you do, we might be able to destructively change the `_GrowableList<int>` to `List<int>` in the record field type. It shouldn't be much more expensive since we already need the `List<int>` for comparison (or at least, we'd likely need it for computing `hashCode`).
(The one thing to use `runtimeType` for, which isn't `==`, would be `toString`, so if we can make that cheap, and `==` lazily optimized, then it might be a sweet spot.)

**Comment by mkustermann** [comment]
I think using option (3) and use implementation classes will probably be way to breaking for the ecosystem. This would need to be rolled out in phases where people can transition their code, ... There's both: Very popular packages that are even parsing the `<obj>.runtimeType.toString()` and using `<obj>.runtimeType` in keys of hash maps. Especially for `int`, `String`, `List` this may cause quite a bit of issues.

Also from a usability: If users see `(_Smi, _Smi)` when printing a record, they will not understand what `_Smi` means. They will be confused. They probably expect it to say `(int, int)`.

My preference would be to go with `(1)`: We can clearly seperate `Type` objects that the VM operates on, and the `Type` objects we expose to end-users via `Object.runtimeType` and type literals. We could have an invariant at those `Type` objects that users see are always the masqueraded ones. Then the `.hashCode` / `operator==` / `toString()` will all work on the masqueraded types.

**Comment by lrhn** [comment]
So @mkustermann, let me see if I understand this correctly. 

* Every object has a way to find both its real runtime type (as defined by the object header) and an *apparent* (masquerading) runtime type, which is *usually* the same thing as the real runtime type.
* Some internal platform implementation classes are declares as, well, that. They should never be visible to user code.
* Only objects of those types have a different apparent runtime type than their actual runtime type, user defined type instances do not.
* And records, whose apparent runtime type is based on the apparent runtime type of the fields. The `Record.runtimeType` returns a `Type` object based on the apparent runtime type of the record fields. This works nicely and recursively for nested records.
* User written function types never contain a private type. Users can't write them, and we won't leak any function object with a type containing a private implementation class. The runtime type of functions do not depend on the runtime type of *objects*, like records do, so the declared type is all that matters. 

Then any `runtimeType` of an object whose real runtime type contains (or is) a private implementation class will be the apparent runtime type which contains no such private implementation types, and all is well.

And the difference between this and option 2 is that option 1 eagerly substitutes the apparent runtime type for the real runtime type when building the `Type` object, and option 2 does so dynamically when it needs to make an operation on the type, like equality or hash code. Which may be cheaper if we never do any equality or hash code operation, but potentially more expensive if we do several. (We can always make `toString` do what we want, no matter which version we choose. In the lazy version, the private implementation class types can report a different name for themselves to `toString`, without even having to find the corresponding type.)

**Comment by mkustermann** [comment]
> We can always make toString do what we want, no matter which version we choose. In the lazy version, the private implementation class types can report a different name for themselves to toString, without even having to find the corresponding type.

I think the `toString` should align with `operator==`/`hashCode`. If not, then one will get errors such as
```
Did not find "(int, int)" in map, available keys are: "(int, int)".
```
Or
```dart
if (obj.runtimeType != int) print(obj.runtimeType); // Prints 'int'
```

**Comment by lrhn** [comment]
Agree. If we chose option 3, it makes sense to show the actual runtime types.
If we go with option 1, then there is no issue, the type is eagerly normalized before you can ever call anything on it.
What I was trying to say is that for option 2, we can likely do `toString` without actually having to come up with the corresponding *type* for the private type that's going to be lazily hidden. We can just give each of these private types a string to use when printed. Just as an optimization.

**Comment by mraleph** [comment]
FWIW I would be okay breaking any code that relies on `"".runtimeType == String` and other equivalences. There is nothing anywhere in the documentation or specification that guarantees that. `String` is a just a class and as such can have private implementations. I did a quick search on GitHub and I found a whole bunch of awful code that does `x.runtimeType == int` (or `== String`) where developer most certainly just intended to write an `is int` (or `is String`).

**Comment by alexmarkov** [comment]
As there are concerns about (3) being too breaking, I implemented (1) in https://github.com/dart-lang/sdk/commit/ab19361e87a0248ade1e883f638542163f9100d1.

Still, it would be interesting to try out (3) and see how breaking it would be in practice.

**Comment by alexmarkov** [comment]
An attempt to remove hiding of internal VM types: https://dart-review.googlesource.com/c/sdk/+/386820.

It turns out there are a lot of failures including Dart SDK tests, co19, flutter and some package tests. Some of the failures:

```
00:00 +11 -1: /b/s/w/ir/cache/builder/flutter/packages/flutter_driver/test/src/real_tests/flutter_driver_test.dart: WebFlutterDriver ByValueKey finds by ValueKey [E]
  DriverError: Unsupported key value type foo.runtimeType. Flutter Driver only supports String, int
  
  package:flutter_driver/src/common/find.dart 213:7     new ByValueKey
  package:flutter_driver/src/driver/driver.dart 777:49  CommonFinders.byValueKey
  test/src/real_tests/flutter_driver_test.dart 860:31   main.<fn>.<fn>.<fn>
```

This is caused by the following code in Flutter:
```Dart
const List<Type> _supportedKeyValueTypes = <Type>[String, int];

    if (!_supportedKeyValueTypes.contains(keyValue.runtimeType)) {
      throw _createInvalidKeyValueTypeError('$keyValue.runtimeType');
    }
```

Some failed tests expect `'foo'.runtimeType.toString()` to be `'String'`:
```
  Expected: throws <Instance of 'MustachioResolutionError'> with `message`: contains '[length] is a getter on String, which is not visible to Mustache.'
    Actual: <Closure: () => String>
     Which: threw MustachioResolutionError:<MustachioResolutionError: [length] is a getter on _OneByteString, which is not visible to Mustache. To render [length] on _OneByteString, make it visible to Mustache via the `visibleTypes` parameter on `@Renderer`; to render [length] on a different type up in the context stack, perhaps provide [length] via a different name.>
            stack package:dartdoc/src/mustachio/renderer_base.dart 328:7                                       SimpleRenderer.getFields
                  package:dartdoc/src/mustachio/renderer_base.dart 224:25                                      RendererBase.renderBlock
```

co19 tests expect both `n.runtimeType.toString() == 'int'` and `n.runtimeType == int`:
```
Expect.equals(expected: <int>, actual: <_Smi>) fails.
#0      _fail (file:///Volumes/Work/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///Volumes/Work/s/w/ir/tests/co19/src/Utils/expect_common.dart:15:7)
#2      main (file:///Volumes/Work/s/w/ir/tests/co19/src/LanguageFeatures/Super-parameters/super_constructor_invocation_A02_t01.dart:47:10)
```
```Dart
  Expect.equals("int", c.i1.runtimeType.toString());
```
```
Expect.equals(expected: <int>, actual: <_Smi>) fails.
#0      _fail (file:///Volumes/Work/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///Volumes/Work/s/w/ir/tests/co19/src/Utils/expect_common.dart:15:7)
#2      main (file:///Volumes/Work/s/w/ir/tests/co19/src/Language/Expressions/Type_Cast/syntax_t08.dart:28:10)
```
```Dart
  Expect.equals(int, v1.runtimeType);
```
Another failure from Flutter which expects _Future to be printed as Future:
```
Expected: 'An exception was throw by Future<int> listened by\n'
Actual: 'An exception was throw by _Future<int> listened by\n'
```

So this change is indeed breaking.

**Comment by lrhn** [comment]
Not very surprised that the `toString` is breaking. Expecting `n.runtimeType.toString()` to be `int` is a very reasonable expectation, it's been true forever, and it's useful in testing. (And I've argued forever that it's not actually specified anywhere, but people keep using it so we likely can't break them now.)

I'm also not particularly surprised that `1.runtimeType != int` causes failing, but I am a little more worried for the code that breaks. It's harder to come up with reasonable use-cases for that, that can't be done at least as well in other, less fragile, ways.

I'd love to see how much breaks if the `toString` doesn't change.

**Comment by alexmarkov** [comment]
There are less failures, but it is still breaking even if we keep `toString` behavior for VM-internal types. See Patchset 5 in https://dart-review.googlesource.com/c/sdk/+/386820?tab=checks.

The problem is that `Object.runtimeType`, `Type.==`, `Type.hashCode` and `Type.toString` are all interconnected. Hiding internal types only in `toString` can be very confusing:
```Dart
  print(int);                   // int
  print(1.runtimeType);         // int
  print(1.runtimeType == int);  // false
```

The following failures in CFE and co19 tests illustrate this point:
```
Unhandled exception:
Expected int, actual int
#0      expect (file:///b/s/w/ir/pkg/front_end/testcases/extension_types/issue52284.dart:18:27)
#1      main (file:///b/s/w/ir/pkg/front_end/testcases/extension_types/issue52284.dart:14:3)
```
```
Expect.equals(expected: <int>, actual: <int>) fails.
#0      _fail (file:///Volumes/Work/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///Volumes/Work/s/w/ir/tests/co19/src/Utils/expect_common.dart:15:7)
#2      main (file:///Volumes/Work/s/w/ir/tests/co19/src/Language/Expressions/Type_Cast/syntax_t08.dart:28:10)
```
