### ISSUE TITLE
Wrong order of evaluating map entries

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#56848]
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/runtime_A02_t02.dart fails at run time on VM, dart2js and dart2wasm.
```dart
String _log = "";

int? f(int? v) {
  _log += "f($v);";
  return v;
}

main() {
  var map1 = {
    f(1): ?f(2),
    ?f(3): ?f(null),
    ?f(4): ?null
  };
  Expect.mapEquals({1: 2}, map1);
  Expect.equals("f(1);f(2);f(3);f(null);f(4);", _log); // Expect.equals(expected: <f(1);f(2);f(3);f(null);f(4);>, actual: <f(2);f(1);f(3);f(null);f(4);>) fails.
...
}
```
Why map value is evaluated before the key? According to the [spec](https://github.com/dart-lang/language/blob/main/accepted/future-releases/0323-null-aware-elements/feature-specification.md#runtime-semantics) the key should be evaluated first.

> - Else, if element is a nullAwareMapElement with entry k: v:
> 
> - Evaluate k to a value kv.
> 
> - If element has a null-aware key and kv is null, then stop. Else continue...
> 
> - Evaluate v to a value vv.
> 
> - If element has a null-aware value and vv is null, then stop. Else continue...
> 
> - Append an entry kv: vv to result.

**Comment by lrhn** [comment]
Nice optimization! Not sound, but nice thought. :wink: 

If `?f(2)` would be `null`, the value of `f(1)` isn't needed, otherwise it's definitely needed, so we can just call it afterwards.
That *only* works if the functions have no side-effect. With side effects, and promotion from left to right, the key expression *must* be evaluated first, whether the value expression bails out or not.

Soundness example:
```dart
int? ifEven(int x) => x.isEven ? x : null; // x == null here!
void main() {
  int? x = null as dynamic;
  var map = {(x ??= 0) : ?ifEven(x)?.toRadixString(16)};
  print(map); // prints {} ?!?
}
```
which fails with
```
NoSuchMethodError: The getter 'isEven' was called on null.
Receiver: null
Tried calling: isEven
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      ifEven (file:///home/lrn/dart/sdk/dev/nae.dart:2:25)
...
```
which isn't *sound*.

**Comment by eernstg** [comment]
Good catch!
