### ISSUE TITLE
Assist to make parameter into named

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56855]
Inspired by https://github.com/dart-lang/sdk/issues/53707

Today if you add a new final field to a class that already has a constructor you only have the option to add it to the constructor as an (_unnamed_) positional parameter.

![image](https://github.com/user-attachments/assets/66679e97-6e40-41fd-8702-800ae27c211b)

I'd like an assist to toggle between named, unnamed and positional parameter types.

**Comment by bwilkerson** [comment]
We have a refactoring that will do this for you. It's currently marked as experimental, which means that you have to set a flag somewhere in order to have it show up in VS Code (I've forgotten where the flag is but @DanTup will probably remember).

**Comment by FMorschel** [comment]
I've tested it and it does seem to work. Some final questions:

1. Is there an issue for it that I can follow?
2. Will it have the other options as well (optional positional and going back to unnamed)?
3. Why is it still experimental (what criteria is this trying to meet)?
4. Should I close this?

**Comment by bwilkerson** [comment]
> 1. Is there an issue for it that I can follow?

https://github.com/dart-lang/sdk/issues/45675 (but I'll note that we're notoriously bad at remembering to go back and close and issue when a feature ships, so it's not clear whether there will be anything to follow).

> 2. Will it have the other options as well (optional positional and going back to unnamed)?

That's the goal, but it's been a while since we've been able to work on it, so I can't give you a timeframe.

> 3. Why is it still experimental (what criteria is this trying to meet)?

We thought it needed more testing.

> 4. Should I close this?

Yes, I think this is a duplication.

> ... progress in the refactor ...

Agreed, we should probably have some kind of progress notification.
