### ISSUE TITLE
How can I ignore timezone while parsing DateTime?

### ISSUE THREAD

**Issue by adimshev** [dart-lang/sdk#56889]
```
final date = DateTime.parse("2021-01-07T18:05:18+0100");
print(date); // 2021-01-07 17:05:18.000Z
```

I wanna ignore `+0100`, so result should be `2021-01-07 18:05:18.000Z`.
Something like `DateTime.parse("2021-01-07T18:05:18+0100", ignoreTimezone: true);`.

Related issue https://github.com/dart-lang/sdk/issues/54993

**Comment by adimshev** [comment]
An alternative way is to copy the regular expression from the DateTime.parse implementation, but this is a bad way.

**Comment by lrhn** [comment]
I'd do 
```dart
final _tzRE = RegExp(r"(?:[+\-]\d\d(?::?\d\d)?|(?<![zZ]))$");
DateTime parseDateTimeIgnoreTZ(String input) {
  input = input.replaceFirst(_tzRE, "Z");
  return DateTime.parse(input);
}
```
This also adds a `Z` if the input has no time zone, so you always parse into UTC.
If that's not necessary, the RegExp can be made simpler:
```dart
final _tzRE = RegExp(r"[+\-]\d\d(?::?\d\d)?$");
```

Seems to work (always a good idea to *test* RegExps, you can never tell if they're correct by reading.)
```dart
void main() {
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18-0100"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18-01:00"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18-01"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18+0100"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18+01:00"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18+01"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18z"));
  print(parseDateTimeIgnoreTZ("2021-01-07T18:05:18Z"));
}
```

**Comment by adimshev** [comment]
It's frustrating to have to do this stuff manually.

**Comment by lrhn** [comment]
It is, but the goal of `DateTime.parse` is to faithfully represent its input in one of the two ways `DateTime` *can* represent points in time: UTC or "local time".
Ignoring part of the input is not being "faithful", so that's not a functionality that fits the class. 

Your problem here is that you have a textual representation of a point in time, and you want to represent a *different* time than that input. The `parse` function can't really help you with that, so you need to work on its input, not the `DateTime` created afterwards, which has been put into one of the two buckets that the class actually supports, and has therefore lost some of the information in the original input.

Parsing a date-time string with a time zone into a `DateTime` is lossful, the result will always be the same point in time in the UTC time zone, no matter which time zone the original was in.
