### ISSUE TITLE
unable to infer non nullable type in case of generics

### ISSUE THREAD

**Issue by bar4488** [dart-lang/sdk#56954]
In these cases we should be able to infer that the type cannot be null, however the current implementation raises a compile error:
```dart
class A<T> {
  final T value;

  A(this.value);
}

void main() {
  int? n = 3;
  int n2 = n == null ? 3 : n + 2; // as intended

  if (n != null) {
    int n2 = n; // as intended
  }

  A<int?> a = A(3);
  int b = a.value == null ? 3 : a.value + 2; // error: Operator '+' cannot be called on 'int?' because it is potentially null

  if (a.value != null) {
    int b = a.value; // error: A value of type 'int?' can't be assigned to a variable of type 'int'.
  }
}
```

**Comment by eernstg** [comment]
This is working as intended. You expect `a.value` to be promoted by the test `a.value == null`, but this would not be sound. That is so because `value` is an instance member of of `a`, and it could be overridden by a getter whose value differs each time you call it. (So it wouldn't be sound to assume that `a.value` is non-null just because it was non-null the previous time you called it).

**Comment by eernstg** [comment]
```dart
// --- Library 'a.dart'.

final class A1 {
  final int value;
  A1(this.value);
}

base class A2 extends A1 {
  A2(super.value);
}

// --- Library 'b.dart'.
import 'a.dart';

var _sillyCounter = 0;

base class B extends A2 {
  B(): super(0);
  int get value => ++_sillyCounter;  
}

// --- Library 'main.dart'.

void main() {
  A1 a = B();
  print('The value is ${a.value}, then ${a.value}');
}
```

Just like promotion, superinterface relationships also have special privileges in the same library (in this case: a subclass of a `final` class, in the same library, can be `base`, and this means that we can create a subclass in a different library).
