### ISSUE TITLE
Wrong return type for `getInstalledRelatedApps`.

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#56986]
`window.navigator.getInstalledRelatedApps()` should return a `List< RelatedApplication >` and not a `RelatedApplication`.

The current return signature is generating an error:
```text
errors.dart:296 Uncaught (in promise) DartError: TypeError: Instance of 'JSArray<dynamic>': type 'List<dynamic>' is not a subtype of type 'FutureOr<RelatedApplication>?'
    at Object.throw_ [as throw] (errors.dart:296:3)
    at Object._failedAsCheck (rti.dart:1405:3)
    at dart_rti.Rti.new._generalNullableAsCheckImplementation (rti.dart:1395:3)
    at dart_rti.Rti.new._installSpecializedAsCheck (rti.dart:1278:30)
    at js_util_patch.dart:483:58
```

Declaration:
https://github.com/dart-lang/sdk/blob/0b38e4b189d1358446f883d68e69cf7d81d6e0ac/sdk/lib/html/dart2js/html_dart2js.dart#L22795

Web API reference:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getInstalledRelatedApps

**Comment by biggs0125** [comment]
It does appear that the typing in `dart:html` is wrong for this API. However, we’re working on putting `dart:html` into deprecation mode which means we’re stopping fixes for these sorts of type errors, especially for experimental APIs. 

We recommend switching over to `package:web` if it contains the API you need, or using `dart:js_interop` otherwise. In this case, since `getInstalledRelatedApps` is an experimental API it won’t be included in `package:web`. This means you’ll have to invoke it a little more manually: 
```
import 'dart:js_interop';

extension type RelatedApplication(JSObject _) implements JSObject {
  external String? id;

  external String? platform;

  external String? url;
}

@JS('window.navigator.getInstalledRelatedApps')
external JSPromise<JSArray<RelatedApplication>> _getInstalledRelatedApps();

Future<List<RelatedApplication>> getInstalledRelatedApps() => _getInstalledRelatedApps().toDart.then((e) => e.toDart));
```

Then you can invoke the method like `await (getInstalledRelatedApps().toDart)`.

For more information on the new JS interop, see our [docs](https://dart.dev/interop/js-interop).

**Comment by gmpassos** [comment]
Thanks for the `dart:js_interop` example.

> For more information on the new JS interop, see our [docs](https://dart.dev/interop/js-interop).

I think this kind of example should be included in the `dart:js_interop` documentation.

The Dart team has invested a lot of effort into `dart:js_interop`, especially for Wasm compatibility. Since the future will likely rely on this new approach to interacting with JavaScript, good documentation and examples are essential to guide people’s efforts in the right direction.

Best regards.
