### ISSUE TITLE
Hovers for import prefixes should show valid Dart code for the import

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#57020]
https://github.com/dart-lang/sdk/issues/32735 improved the hovers for import prefixes, but the new text is in a field that usually contains valid Dart code and LSP wraps in triple backticks. This results in syntax highlighting being applied to English text:

![image](https://github.com/user-attachments/assets/f1f42602-9618-4fea-a3be-9b7f4ae893d9)

To maintain consistency, rather than removing the backticks we should update the element descriptions for import prefixes to be the valid Dart code that adds the relevant imports instead.

(cc @FMorschel)

**Comment by FMorschel** [comment]
As I wrote there as well:

> For consistency I believe we should always show all imports with the prefix in the order they're in.
> 
> Although I like the idea of sorting the elements or limiting them to the current namespace, it would not be consistent in the entirety of the library and that is something I would prefer, so that users are always aware of what would appear and in what order.

I see your point in limiting it, I just don't think it would be as consistent because you can either hover the prefix on a declaration like a class or a function, but you could also hover it by itself or at the import line.

I'd rather show all prefixed imports everywhere so that people are aware of what the actual prefix fully means.

I would not expect real code to have multiple imports using the same prefix to be a really common thing but when they appear, I'd like to show the user that this is being done so that they are aware every time this might be causing some confusion.

> I might misunderstand the purpose of the hover, but I assumed it was to help identify which import was being referenced in that case.

Although I see some truth in this, it might not be the only reason why this hover would be relevant. I think for what you are talking about here, three other issues would fit this category better (I think in this specific order of relevance but the first and second don't have that much priority over one another): 
- https://github.com/dart-lang/sdk/issues/56935
- https://github.com/dart-lang/sdk/issues/56584
- https://github.com/dart-lang/sdk/issues/56350

**Comment by FMorschel** [comment]
Here is the CL https://dart-review.googlesource.com/c/sdk/+/393382
