### ISSUE TITLE
Create an issue

### ISSUE THREAD

**Issue by tolotrasamuel** [dart-lang/sdk#57024]
Dart infers type incorrectly with inheritance.

Dart type inference is not working properly with inheritance and field overriding. 

If we don't explicitly write   `final Dog pet = Dog();` (repetitive) the analyzer thinks that `pet` is `Animal`.  (which is not wrong but problematic, it should be `Dog`)

    class Animal {}
    
    class Dog extends Animal {
      void bark() {
        print("Daawg!");
      }
    }
    
    abstract class Owner {
      Animal get pet;
    }
    
    class DogOwner extends Owner {
      @override
      final pet = Dog();
    }
    
    void main() {
      final dog = Dog();
      dog.bark(); // pass
    
      final owner = DogOwner();
      owner.pet.bark();  // error. Why ??
    }

However, `DogOwner.pet` is clearly of type `Dog` (at least for the human reader)

Is this a bug in Dart or intended ? I am curious to know why would this be intended.

Dart version 3.4.3

**Comment by eernstg** [comment]
You need to declare that the type of the getter in `DogOwner` is `Dog`:

```dart
class DogOwner extends Owner {
  @override
  final Dog pet = Dog();
}
```

When you don't declare the return type of a getter (in this case: the implicitly induced getter of the instance variable `DogOwner.pet`), the step which is called _override inference_ prevails over the kind of inference that provides the type of a variable based on its initializing expression. So `DogOwner.pet` has the type `Animal` rather than `Dog` because it overrides `Owner.pet` has type `Animal`.
