### ISSUE TITLE
Incorrect behavior of try/catch within finally within async* method

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#57046]
The following code shows different behavior on the Web and on the VM. It seems in dart2js case exception thrown from `(*)` is clobbering the exception which is currently in flight. 

```dart
Future<void> something(int v) async {
  await Future.delayed(Duration(milliseconds: 10));
  throw StateError('error $v');
}

Stream<int> _readLoop() async* {
  try {
    while (true) {
      yield 1;
      await something(0);
    }
  } catch (e) {
    throw StateError('converted');
  } finally {
    try {
      await something(1);  // (*)
    } catch (e) {
      print('Ignored: $e');
    }
  }
}

void main() async {
  try {
    await for (var _ in _readLoop()) {
    }
  } catch (e) {
    print('Caught: $e');
  }
}
```

```console
$ dart --version
Dart SDK version: 3.7.0-112.0.dev (dev) (Wed Nov 6 08:02:51 2024 -0800) on "macos_arm64"
$ dart test.dart
Ignored: Bad state: error 1
Caught: Bad state: converted
$ dart compile js test.dart
$ ~/.jsvu/v8 /Users/vegorov/src/flutter/flutter/bin/cache/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js out.js
Ignored: Bad state: error 1
Caught: Bad state: error 1
```

DDC might also have a problem with desugarring but of a different nature because in DartPad I get unhandled `StateError`.

/cc @natebiggs

**Comment by mnordine** [comment]
I think your program maybe should have:
```dart
print('Caught: $e');
```
instead of:
```dart
print(e);
```
?

**Comment by mraleph** [comment]
@mnordine good catch :) fixed it.

**Comment by biggs0125** [comment]
@mraleph Your initial assessment was right, dart2js's async control flow state machine is keeping a single 'error' variable per async function. If we nest error handlers then the inner handler will clobber the value already set by the outer one.

I have a fix that I'm verifying: https://dart-review.googlesource.com/c/sdk/+/395580
The fix keeps a stack of errors rather than a single error variable and pushes/pops as we enter/exit error handling scopes.
