### ISSUE TITLE
False warning of `dead_null_aware_expression` when using map pattern

### ISSUE THREAD

**Issue by jtdLab** [dart-lang/sdk#57060]
When using this code:

foo.dart
```dart
final map <String,dynamic>{}
```

bar.dart
```dart
if (map case {'language': String? language}) {
  language ??= 'en';
}
```

a `dead_null_aware_expression` is reported.

**Comment by devoncarew** [comment]
Thanks for the report! Can you post a full repro, perhaps as a dartpad link?

**Comment by jtdLab** [comment]
https://dartpad.dev/?id=a2a5897e1125a9dd930716186f9423f8

**Comment by julemand101** [comment]
@jtdLab 
Your example in the dartpad does not match the code you posted in the issue. Your code in DartPad are:
```dart
void main() {
  if (someMap() case {'language': String? language}) {
    language ??= 'en';
  }
}

Map<String, String> someMap() {
  return {};
}
```

Since the signature of `someMap()` are that it returns `Map<String, String>` it makes sense you get the error since the value would never be possible to be `null` since the values of this map can't be `null`.

If you instead change your `someMap()` to the one from your initial example:
```dart
Map<String, dynamic> someMap() {
  return {};
}
```

Or:
```dart
Map<String, String?> someMap() {
  return {};
}
```
The error goes away since now it is actually possible for the returned map value to be `null`.
