### ISSUE TITLE
Move class to file error

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#57398]
I got the following when refactoring my package with "Move class to file".

![image](https://github.com/user-attachments/assets/360f357b-d52e-4499-a01b-49d0aaaee54f)

I was trying to move a class to another file while I already had an export for it (the new not yet existing file) on the source file. I did that some times before and after that error so there might be something else to it. I've not yet been able to repro but I'll keep trying.

Here are the instrumentation logs for around the time when this happened.

[InstrumentationLog.zip](https://github.com/user-attachments/files/17806599/InstrumentationLog.zip)

---

CC: @DanTup

**Comment by DanTup** [comment]
@FMorschel from the log, it seems like it occurred when you were trying to move `extension AddDays` to another file. I'm unable to reproduce this, however I see you were using an SDK at d75c493e27f9bf2a89043860132462be665065c2 and I see that later that day 5cd0517bd66050b4edc7c52fd0f3fa3bd0f37a6d made changes to the `asElement` implementation. I wonder if it may have been fixed by that change?

**Comment by FMorschel** [comment]
Maybe, I've not yet updated. I was working on this PR https://github.com/FMorschel/due_date/pull/26 (this specific commit https://github.com/FMorschel/due_date/pull/26/commits/be709b5990373e1300004de83626630abc60f257). 

I'll see if I can repro this and I'll let you know. I'll also test after updating the SDK to see if this is fixed.

**Comment by FMorschel** [comment]
I can't even reproduce this myself with that commit. I'm not sure what I have done differently. In any case, I'll close this then as it seems to have been a one-off caused by a probably fixed error. Thanks for all the help!
