### ISSUE TITLE
Failures on Message scheduler test

### ISSUE THREAD

**Issue by jyameo** [dart-lang/sdk#59615]
There are new test failures on [[Message scheduler] Implement handling one message at a time.](https://github.com/dart-lang/sdk/commit/f7c9899217a9129ba78c3d7c453ab34c4cf2cdcc).

The tests
```
pkg/analysis_server/test/integration/server/message_scheduler_test RuntimeError (expected Pass)
pkg/analysis_server/test/lsp/code_actions_refactor_test RuntimeError (expected Pass)
```
are failing on configurations
```
analyzer-unittest-asserts-release-win
```
LOGS: https://dart-ci.appspot.com/log/any/analyzer-unittest-asserts-release-win/29285/pkg/analysis_server/test/integration/server/message_scheduler_test

**Comment by DanTup** [comment]
Yep, I can reproduce it - will take a look.

**Comment by keertip** [comment]
Thanks! The `LspServerMessageSchedulerTest | test_documentChange` also fails due to timeout. Likely the same issue.

**Comment by DanTup** [comment]
The issue is using `.path` on `file:///` URIs. On Mac/Linux, this works out the same (eg. `file:///foo/bar` -> `/foo/bar`) but on Windows it's incorrect (`file:///c:/foo/bar` -> `/c:/foo/bar` instead of `c:\foo\bar`). Calling `.toFilePath()` is better, but in this case I think we should compare URIs instead (and we should migrate refactors from paths to URIs).

Will ping you on a CL to fix shortly.

**Comment by DanTup** [comment]
@keertip I've opened https://dart-review.googlesource.com/c/sdk/+/397620 - you might need to find a second reviewer to land it though.
