### ISSUE TITLE
Extensions don't trigger library import for their names only

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#59723]
Repro:

extension.dart

```dart
extension Ext on int {}
```

main.dart:

```dart
/// This is a dart doc for [f] that uses an [Ext] type.
void f<E extends Ext>() {}
```

Neither `Ext` will trigger the quick-fix for the importing of `extension.dart`. If you add a line `Ext;` inside `f` it does.

I volunteer to help with this.

**Comment by FMorschel** [comment]
Here is the CL https://dart-review.googlesource.com/c/sdk/+/401040

**Comment by FMorschel** [comment]
This still makes one test fail. I'm on my lunch break now, when I get to my computer I'll add a comment on the CL asking for what I should do in that case.

**Comment by bwilkerson** [comment]
Note that the use of `Ext` in `void f<E extends Ext>() {}` is invalid because `Ext` isn't a type.

I can see wanting this behavior for the doc comment case, though, but for that case it should probably create a doc-import.

@srawlins

**Comment by FMorschel** [comment]
Yeah, I noticed later. I originally detected this by making a doc.

**Comment by FMorschel** [comment]
Currently the `LinterLintCode.comment_references` calls on `ImportLibrary`, which adds a normal import.

Adding a call for the `forExtension` constructor along with `forType` solves this but doesn't address your point of it being a doc-import. I can probably make this change with more time, but I'd make this CL only about fixing this and creating a new issue/CL for migrating those fixes for this.

Unfortunately, this is only accessible if that lint is enabled and it is off by default. Why is that? I'd expect more care for the docs from everyone and this being on would help with that.

**Comment by FMorschel** [comment]
Updated this CL to the above.

**Comment by bwilkerson** [comment]
> Unfortunately, this is only accessible if that lint is enabled and it is off by default. Why is that?

One reason is because the lint was written before there were doc imports. If we required users to add a normal import for every reference in a doc comment then the dependency graph would have far more edges than necessary in order to run the program, and that isn't good for users.

As I said elsewhere, we need to look at the lints/warnings for doc imports from a holistic perspective and figure out what the right UX is. It's possible that we'll convert the lint into a warning now that we have doc imports.
