### ISSUE TITLE
Async stack unwinding does not properly unwind a stack through `Future<List<T>> get wait`

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#59730]
``` Dart
Future<void> convert(String file) async {
  await Future.delayed(Duration(seconds: 10));
  throw "hello";
}

Future<void> main() async {
  var files = ['foo', 'bar'];
  var futures = files.map((file) {
    return convert(file);
  });
  try {
    await futures.wait;
  } catch (e) {
    print(e);
  }
}
```
When executing this code an Uncaught exception happens at the end of the function but all futures have been await using `await futures.wait;

 I think `Future<List<T>> get wait` is not doing his job properly

See screenshots for execution:

<img width="1440" alt="Screenshot 2024-12-16 at 22 22 26" src="https://github.com/user-attachments/assets/516cedde-bde5-43b3-b786-c3568ebefa97" />
<img width="1440" alt="Screenshot 2024-12-16 at 22 22 32" src="https://github.com/user-attachments/assets/9c93453c-3eff-40f9-a808-ef911f95e1f8" />
<img width="1440" alt="Screenshot 2024-12-16 at 22 22 49" src="https://github.com/user-attachments/assets/6d9956df-fa9f-4c20-90ff-66bf81a32cc8" />
<img width="1440" alt="Screenshot 2024-12-16 at 22 23 05" src="https://github.com/user-attachments/assets/334d3b7a-50e3-4541-b577-cb41baa89718" />
<img width="1440" alt="Screenshot 2024-12-16 at 22 23 17" src="https://github.com/user-attachments/assets/3dcbc5ab-b8a5-41fb-8931-04c83aba5455" />

**Comment by mraleph** [comment]
The exception itself is caught, but the debugger is treating it as uncaught. That happens quite often in async code because the only reliable way to figure out if exception will bubble through or not is to run `Future` implementation code. We have some heuristics - but these occasionally fail like here.

**Comment by stephane-archer** [comment]
Suggestions for Improvement:
- Track the "Await Stack": Like the "Call Stack" in synchronous code, tracking the "Await Stack" could help the debugger determine whether the exception is truly uncaught.
- Refine Heuristics: Updating heuristics to better handle common async patterns could reduce false positives.
- Debugger Context: The debugger could display clearer messages when exceptions are flagged due to heuristic limitations, reducing confusion.

@mraleph what are your thoughts on these propositions?

**Comment by mraleph** [comment]
> @mraleph what are your thoughts on these propositions?

That they are generated by some LLM and as such neither wrong nor right. Just saying words which kinda make sense together, but not truly showing any knowledge or comprehension. 

The actual fix is here: https://dart-review.googlesource.com/c/sdk/+/401062

**Comment by stephane-archer** [comment]
@mraleph LLM rephrases my words because I'm not good at writing and wrote something too long.

I have limited knowledge of the issue, I was expecting the debugger to be able to know the "Await Stack" like regular synchronous code.

I'm glad you were able to find a solution. What approach did you use? Refining the Heuristics?

**Comment by mraleph** [comment]
> What approach did you use?

The solution was to slightly rewrite `wait` extension and annotate some parts of it with `vm:awaiter-link` pragma so that unwinder could see through it.

Dart `Future` objects don't form a neat stack - they form a data flow graph held together by callbacks which transform and forward values. That's what makes this complicated. Both for debugging and stack trace reporting purposes we try to pretend that there is some sort of awaiter stack, but it is just not _entirely_ true.

**Comment by stephane-archer** [comment]
@mraleph, thanks for finding a solution so rapidly.

I have a limited understanding of this subject, but because the Dart runtime can associate the right future/exception with the right try-catch, would it make sense to share this flow graph with the debugger?
It seems like the runtime and the debugger track things differently.
Is this because the debugger (not made for async code?) wants to see a classic "call stack" while the runtime only knows who is waiting for whom (flow graph)?
What allows the runtime to create this flow graph but not the debugger?

**Comment by mraleph** [comment]
@stephane-archer Sorry for the delayed response.

The problem is that there is no true "flow graph" - at least not in a pure form. There is a maze of boxes (`Future` objects) which are connected through callbacks. These callbacks take a value from one box (`Future` which just completed), transform it (e.g. apply `then`), and put it into some another box (next `Future`). You can't really reliably know what happens with a value you put into one `Future` without running a bunch of Dart code which implements async machinery internals. 

That's why async unwinding is so complicated and unreliable - the async stack does not exist in "declarative" form (e.g. as a list of frames or even as a graph of connected computations), it is very imperative. You need to run the code to determine what will happen. 

That being said: both debugger logic and `StackTrace.current` logic are backed by the same machinery. If you see a good (not truncated) stack trace in `StackTrace.current` then debugger will also use the same stack trace.

**Comment by stephane-archer** [comment]
@mraleph Thanks for taking the time to explain this
