### ISSUE TITLE
cascade_invocations

### ISSUE THREAD

**Issue by amrgetment** [dart-lang/sdk#59807]
I wonder if you can add `fix all cascades` in the file not one by one fix
<img width="455" alt="image" src="https://github.com/user-attachments/assets/6492eb9c-5865-4b0c-91e5-0727aee7c8c6" />

- The Dart version and tooling diagnostic info (`dart info`)
```
#### General info

- Dart 3.5.4 (stable) (Wed Oct 16 16:18:51 2024 +0000) on "macos_x64"
- on macos / Version 15.0.1 (Build 24A348)
- locale is en-EG

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                     |
| ------: | ---: | -----------: | -------------------------------------------------------------------------------- |
|   62 MB | 0.0% |        28:07 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/uuKV8DUxYL3eCfsu   |
| 1285 MB | 0.0% |        28:07 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.102.0 |
|   76 MB | 0.0% |        28:08 | dart tooling-daemon --machine                                                    |
|   91 MB | 0.0% |        28:08 | flutter_tools.snapshot daemon                                                    |
```

- Whether you are using Windows, macOS, or Linux (if applicable)
macOS

**Comment by FMorschel** [comment]
Do you mean something like https://github.com/dart-lang/sdk/issues/52476? If so, that has been added and will be available after 3.7

**Comment by FMorschel** [comment]
As a note:

Since we still have https://github.com/dart-lang/sdk/issues/58662 (false positive/negatives) and possibly similar issues open, we decided not to add a "Fix all in file" option as it may result in possibly wrong code. What we added instead was an option to fix multiple lint triggers that are together and are related. So it will help a bit more but not fix all in the file. For that (I think this screenshot you took is from VS Code) you can open the problems tab and fix with right click there (also see https://github.com/microsoft/vscode/issues/236364).

**Comment by amrgetment** [comment]
thanks a lot, I will wait next release
