### ISSUE TITLE
Allow list literals ranges of the form a ... b

### ISSUE THREAD

**Issue by pwbecker** [dart-lang/sdk#7991]
Enhancement request:

Allow list literals to be ranges of the form a ... b

As in 

for (x in [0 ... 10])

This would also solve the problem of accessing indexes within for loops (or iterate in web_ui)
&nbsp;&nbsp;

**Comment by munificent** [comment]
This would make it really easy to create lists that allocate a monumental amount of memory when all you really want to do is loop through them. It could return an Iterable instead, but then the `[ ... ]` syntax starts to look misleading.

For a more general "do something for ranges", we'll use #26307 to track that. I'm going to close this one because I don't think we want a solution that involves actually creating a list of numbers.
