### ISSUE TITLE
Easier way to detect if object is null

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#8598]
In a dynamic scripting language, typing this feels weird:

if (obj != null)

I'd much rather do this:

if (obj)

But because I don't expect that to happen, might I suggest the following:

if (obj.isNull)

This is similar to the helpers we have like isEven and isEmpty.

Here's how I think isNull can be added:

Object.isNull returns false, unless the instance is of the class Null, in which case it returns true. Much like runtimeType is final, I think 'final get isNull' can be added. I'd go as far as to say it is a compile-time warning if isNull is implemented by a class.

I admit this is an aesthetic thing, but aesthetics matter.

Slight bonus, this drives home the point that null is an object.

**Comment by jibiel** [comment]
@lrhn Apologies for gravedigging but how `isNotNull` is any different from introducing `isNotEmpty` sugar for `length > 0`?

It's weird having to write `!= null` in a high level, mostly object-oriented modern language like it's JS 90s or something.

It's looks strange in a mostly-words-dot-notations-and-maps-code (Flutter) and sometimes it's visually harder to read as it breaks the flow of it.

**Comment by jodinathan** [comment]
> @lrhn Apologies for gravedigging but how `isNotNull` is any different from introducing `isNotEmpty` sugar for `length > 0`?
> 
> It's weird having to write `!= null` in a high level, mostly object-oriented modern language like it's JS 90s or something.
> 
> It's looks strange in a mostly-words-dot-notations-and-maps-code (Flutter) and sometimes it's visually harder to read as it breaks the flow of it.

that can be easily done with extension methods: https://dartpad.dartlang.org/ed0a241f8e6cb9d8b5d77f889f7800b1

```dart
extension AdvObj on Object {
  bool get isNotNull => this != null;
}
```

**Comment by lrhn** [comment]
There are two significant differences between `.isNull`/`isNotNull` and `isEmpty`/`isNotEmpty`.

The `isEmpty` differs from `.length == 0` in that it doesn't need to compute the length. For iterables, computing the length might take time linear in the number of elements (it really has to count them one by one), whereas `isEmpty`/`isNotEmpty` can be done in constant time for most iterables (a `.where` or `expand` iterable might need more since they can need to iterate elements which do not provide any elements for the result). The `isNull` has no such advantage over `== null`.
It's also more readable because it says the word `"empty"` rather than letting you infer that from the combination of `length` and `0`. The `isNull` has no such advantage over `== null`, which literally reads as "is null".

Second, the `== null` is special in that the Null Safety feature allows it to promote a variable to being non-null. 
An extension method like `.isNotNull` won't do that, so I *highly recommend* not introducing such extension methods. They will be useless very soon.
Example: `String? x = ...; if (x != null) number += x.length;` is valid, `String? x = ...; if (x.isNotNull) number += x.length;` is a compile-time error.

In some cases, the check for `null` can be combined with the operation to do in the null/non-null case, like `x ??= "a";` or `x?.length`. In others, they can't, and you need to do the `== null`.
