### ISSUE TITLE
Provide a base class for wrapping lists

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#8778]
It's quite common to need to wrap a List object with another list to either intercept certain calls or to coerce the element types. It would be nice if there was a standard base class for allowing this.

I recently had to create one in dart:html to expose a List&lt;Element&gt; as List&lt;TableRowElement&gt; without copying the list, but it seems to be more generally useful.

**Comment by lrhn** [comment]
The classes are available in `package:collection`. We do not plan to duplicate them in the platform SDK. That is obviously annoying for platform libraries like `dart:html` which cannot use packages, but since `dart:html` isn't shipped on all platforms, it's better to have the duplication only there.
