### ISSUE TITLE
VM accepts non-identifiers after $ in interpolation

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#8823]
It accepts, and then fails to find a variable by that name, all of the following:
&nbsp;&quot;$null&quot;
&nbsp;&quot;$true&quot;
&nbsp;&quot;$for&quot;

**Comment by mhausner** [comment]
Reading the spec I do not see that it mandates that "$null" is a compile-time error rather than runtime. Also, the VM now reports most compile-time errors at runtime, further blurring the distinction. Lastly, we'll have a new, shiny front-end soon which will have a new set of bugs, so I'm closing this one.

**Comment by lrhn** [comment]
The spec says that what follows a `$` in an interpolated string must be an *identifier*. The words `null`, `true` and `for` are reserved words, and therefore not identifiers.

The way the VM reports compile-time errors is different from how it reports undeclared identifiers.
For example:
```dart
func() {
  print("Hello world");
  var x = "$null/$true/$this/$for";
}
```
should not print "Hello world" if called because the entire function must fail to compile.

Waiting for the common front-end is reasonable, though, since this isn't an urgent problem.
