### ISSUE TITLE
Support non-ASCII characters in source code.

### ISSUE THREAD

**Issue by blois** [dart-lang/sdk#9088]
Dart currently does not support non-ASCII characters in source code, this can make it a real hassle when converting code from other languages.

For example, the extremely popular Javascript library D3 makes heavy use of non-ascii characters for many math functions, such as:
function d3_geo_forwardRotationλ(δλ) {
&nbsp;&nbsp;return function(λ, φ) {
&nbsp;&nbsp;&nbsp;&nbsp;return λ += δλ, [λ &gt; π ? λ - 2 * π : λ &lt; -π ? λ + 2 * π : λ, φ];
&nbsp;&nbsp;};
}

Source: https://github.com/mbostock/d3/blob/master/src/geo/rotation.js

**Comment by munificent** [comment]
I'm trying to minimize the number of open issues we have that are lingering because the team has no intention of doing it but we feel bad about shutting the door on it. I think it's better to be decisive and clear about which issues we don't intend to support. If it becomes more of a priority later, someone can always reopen the bug or file a new one.

This is one of those cases. Non-ASCII identifiers seem to cause as many problems as they solve in languages that support them. Do you *really* want to allow two visually identical identifiers that actually are different names?

Limiting to ASCII is definitely unfortunate for our many non-English friends, but it seems like the safer choice compared to the rathole that is Unicode identifiers.
