### ISSUE TITLE
dart VM exiting with error "Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8."

### ISSUE THREAD

**Issue by gramster** [dart-lang/sdk#9160]
I see when trying to run a Dart app. It is not a very useful or actionable error message for end users.

**Comment by CRTX** [comment]
Just wanted to add another reason for this exact error. This just happened to me when I changed my code from a dev box to a VPS box because I was running out of memory. I Googled everywhere for this error and couldn't find an answer until I ran a `pub get --verbose` a few times with inconsistent error messages until I got an out of memory exception from it.

Hopefully this helps someone else when Googling this error message!

**Comment by eduardotd** [comment]
@CRTX , Same here. I just created a swap file and it solved the problem
